Github User Fetcher: asprintf-compat.h File Reference
asprintf-compat.h File Reference
#include <stdarg.h>
#include <stddef.h>
#include "common.h"
Macros
#define CRI_PRINTF_FORMAT printf
Functions
CR_BEGIN_C_API CR_API int cr_asprintf (char **strp, const char *fmt,...)
CR_API int cr_vasprintf (char **strp, const char *fmt, va_list ap)
CR_API void cr_asprintf_free (char *buf)
CR_API int cri_fmt_bprintf (char **buf, size_t *offset, size_t *sz, const char *fmt,...)
CR_API int cri_fmt_vbprintf (char **buf, size_t *offset, size_t *sz, const char *fmt, va_list ap)
CR_API char * cri_strtok_r (char *str, const char *delim, char **saveptr)
Macro Definition Documentation
CRI_PRINTF_FORMAT
#define CRI_PRINTF_FORMAT printf
Definition at line 47 of file asprintf-compat.h.
Function Documentation
cr_asprintf()
CR_BEGIN_C_API CR_API int cr_asprintf (char ** strp, const char * fmt, ...)
Referenced by CRI_USER_TAG_ID(), CRI_USER_TAG_ID(), and CRI_USER_TAG_ID().
cr_asprintf_free()
CR_API void cr_asprintf_free (char * buf)
cr_vasprintf()
CR_API int cr_vasprintf (char ** strp, const char * fmt, va_list ap)
cri_fmt_bprintf()
CR_API int cri_fmt_bprintf (char ** buf, size_t * offset, size_t * sz, const char * fmt, ...)
cri_fmt_vbprintf()
CR_API int cri_fmt_vbprintf (char ** buf, size_t * offset, size_t * sz, const char * fmt, va_list ap)
cri_strtok_r()
CR_API char * cri_strtok_r (char * str, const char * delim, char ** saveptr)