Github User Fetcher: socket.c File Reference
socket.c File Reference
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <netdb.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <time.h>
#include "duktape.h"
Macros
#define _GNU_SOURCE
#define ERROR_FROM_ERRNO(ctx)
Functions
static void set_nonblocking (duk_context *ctx, int fd)
static void set_reuseaddr (duk_context *ctx, int fd)
static int socket_create_server_socket (duk_context *ctx)
static int socket_close (duk_context *ctx)
static int socket_accept (duk_context *ctx)
static int socket_connect (duk_context *ctx)
static int socket_read (duk_context *ctx)
static int socket_write (duk_context *ctx)
void socket_register (duk_context *ctx)
Variables
static duk_function_list_entry socket_funcs []
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 5 of file duktape-1.5.2/examples/eventloop/socket.c.
ERROR_FROM_ERRNO
#define ERROR_FROM_ERRNO (ctx)
Value:
        do { \
        duk_error(ctx, DUK_ERR_ERROR, "%s (errno=%d)", strerror(errno), errno); \
    } while (0)
Definition at line 19 of file duktape-1.5.2/examples/eventloop/socket.c.
#define  ERROR_FROM_ERRNO(ctx)  do { \
        duk_error(ctx, DUK_ERR_ERROR, "%s (errno=%d)", strerror(errno), errno); \
    } while (0)
Referenced by set_nonblocking(), set_reuseaddr(), socket_accept(), socket_close(), socket_connect(), socket_create_server_socket(), socket_read(), and socket_write().
Function Documentation
set_nonblocking()
static void set_nonblocking (duk_context * ctx, int fd) static
Definition at line 23 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    int rc;
    int flags;
    rc = fcntl(fd, F_GETFL);
    if (rc < 0) {
        ERROR_FROM_ERRNO(ctx);
    }
    flags = rc;
    flags |= O_NONBLOCK;
    rc = fcntl(fd, F_SETFL, flags);
    if (rc < 0) {
        ERROR_FROM_ERRNO(ctx);
    }
}
References ERROR_FROM_ERRNO.
Referenced by socket_accept(), socket_connect(), and socket_create_server_socket().
set_reuseaddr()
static void set_reuseaddr (duk_context * ctx, int fd) static
Definition at line 41 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    int val;
    int rc;
    val = 1;
    rc = setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (const void *) &val, sizeof(val));
    if (rc != 0) {
        ERROR_FROM_ERRNO(ctx);
    }
}
References ERROR_FROM_ERRNO.
Referenced by socket_create_server_socket().
socket_accept()
static int socket_accept (duk_context * ctx) static
Definition at line 133 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    int sock = duk_to_int(ctx, 0);
    int rc;
    struct sockaddr_in addr;
    socklen_t addrlen;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addrlen = sizeof(addr);
    rc = accept(sock, (struct sockaddr *) &addr, &addrlen);
    if (rc < 0) {
        ERROR_FROM_ERRNO(ctx);
    }
    set_nonblocking(ctx, sock);
#ifdef __APPLE__
    set_nosigpipe(ctx, sock);
#endif
    if (addrlen == sizeof(addr)) {
        uint32_t tmp = ntohl(addr.sin_addr.s_addr);
        duk_push_object(ctx);
        duk_push_string(ctx, "fd");
        duk_push_int(ctx, rc);
        duk_put_prop(ctx, -3);
        duk_push_string(ctx, "addr");
        duk_push_sprintf(ctx, "%d.%d.%d.%d", ((tmp >> 24) & 0xff), ((tmp >> 16) & 0xff), ((tmp >> 8) & 0xff), (tmp & 0xff));
        duk_put_prop(ctx, -3);
        duk_push_string(ctx, "port");
        duk_push_int(ctx, ntohs(addr.sin_port));
        duk_put_prop(ctx, -3);
        return 1;
    }
    return 0;
}
References duk_push_int(), duk_push_object(), duk_push_sprintf(), duk_push_string(), duk_put_prop(), duk_to_int(), ERROR_FROM_ERRNO, and set_nonblocking().
socket_close()
static int socket_close (duk_context * ctx) static
Definition at line 122 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    int sock = duk_to_int(ctx, 0);
    int rc;
    rc = close(sock);
    if (rc < 0) {
        ERROR_FROM_ERRNO(ctx);
    }
    return 0;
}
References duk_to_int(), and ERROR_FROM_ERRNO.
socket_connect()
static int socket_connect (duk_context * ctx) static
Definition at line 174 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    const char *addr = duk_to_string(ctx, 0);
    int port = duk_to_int(ctx, 1);
    int sock;
    struct sockaddr_in sockaddr;
    struct hostent *ent;
    struct in_addr **addr_list;
    struct in_addr *addr_inet;
    int i;
    int rc;
    sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock < 0) {
        ERROR_FROM_ERRNO(ctx);
    }
    set_nonblocking(ctx, sock);
#ifdef __APPLE__
    set_nosigpipe(ctx, sock);
#endif
    ent = gethostbyname(addr);
    if (!ent) {
        ERROR_FROM_ERRNO(ctx);
    }
    addr_list = (struct in_addr **) ent->h_addr_list;
    addr_inet = NULL;
    for (i = 0; addr_list[i]; i++) {
        addr_inet = addr_list[i];
        break;
    }
    if (!addr_inet) {
        duk_error(ctx, DUK_ERR_ERROR, "cannot resolve %s", addr);
    }
    memset(&sockaddr, 0, sizeof(sockaddr));
    sockaddr.sin_family = AF_INET;
    sockaddr.sin_port = htons(port);
    sockaddr.sin_addr = *addr_inet;
    rc = connect(sock, (const struct sockaddr *) &sockaddr, (socklen_t) sizeof(sockaddr));
    if (rc < 0) {
        if (errno == EINPROGRESS) {
#if 0
            fprintf(stderr, "connect() returned EINPROGRESS as expected, need to poll writability\n");
            fflush(stderr);
#endif
        } else {
            ERROR_FROM_ERRNO(ctx);
        }
    }
    duk_push_int(ctx, sock);
    return 1;
}
References DUK_ERR_ERROR, duk_error, duk_push_int(), duk_to_int(), duk_to_string(), ERROR_FROM_ERRNO, NULL, and set_nonblocking().
socket_create_server_socket()
static int socket_create_server_socket (duk_context * ctx) static
Definition at line 65 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    const char *addr = duk_to_string(ctx, 0);
    int port = duk_to_int(ctx, 1);
    int sock;
    struct sockaddr_in sockaddr;
    struct hostent *ent;
    struct in_addr **addr_list;
    struct in_addr *addr_inet;
    int i;
    int rc;
    sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock < 0) {
        ERROR_FROM_ERRNO(ctx);
    }
    set_nonblocking(ctx, sock);
    set_reuseaddr(ctx, sock);
#ifdef __APPLE__
    set_nosigpipe(ctx, sock);
#endif
    ent = gethostbyname(addr);
    if (!ent) {
        ERROR_FROM_ERRNO(ctx);
    }
    addr_list = (struct in_addr **) ent->h_addr_list;
    addr_inet = NULL;
    for (i = 0; addr_list[i]; i++) {
        addr_inet = addr_list[i];
        break;
    }
    if (!addr_inet) {
        duk_error(ctx, DUK_ERR_ERROR, "cannot resolve %s", addr);
    }
    memset(&sockaddr, 0, sizeof(sockaddr));
    sockaddr.sin_family = AF_INET;
    sockaddr.sin_port = htons(port);
    sockaddr.sin_addr = *addr_inet;
    rc = bind(sock, (const struct sockaddr *) &sockaddr, sizeof(sockaddr));
    if (rc < 0) {
        ERROR_FROM_ERRNO(ctx);
    }
    rc = listen(sock, 10 /*backlog*/);
    if (rc < 0) {
        (void) close(sock);
        ERROR_FROM_ERRNO(ctx);
    }
    duk_push_int(ctx, sock);
    return 1;
}
References DUK_ERR_ERROR, duk_error, duk_push_int(), duk_to_int(), duk_to_string(), ERROR_FROM_ERRNO, NULL, set_nonblocking(), and set_reuseaddr().
socket_read()
static int socket_read (duk_context * ctx) static
Definition at line 231 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    int sock = duk_to_int(ctx, 0);
    char readbuf[1024];
    int rc;
    void *data;
    rc = recvfrom(sock, (void *) readbuf, sizeof(readbuf), 0, NULL, NULL);
    if (rc < 0) {
        ERROR_FROM_ERRNO(ctx);
    }
    data = duk_push_fixed_buffer(ctx, rc);
    memcpy(data, readbuf, rc);
    return 1;
}
References duk_push_fixed_buffer, duk_to_int(), ERROR_FROM_ERRNO, and NULL.
socket_register()
void socket_register (duk_context * ctx)
Definition at line 279 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    /* Set global 'Socket'. */
    duk_push_global_object(ctx);
    duk_push_object(ctx);
    duk_put_function_list(ctx, -1, socket_funcs);
    duk_put_prop_string(ctx, -2, "Socket");
    duk_pop(ctx);
}
socket_write()
static int socket_write (duk_context * ctx) static
Definition at line 247 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    int sock = duk_to_int(ctx, 0);
    const char *data;
    size_t len;
    ssize_t rc;
    data = duk_to_buffer(ctx, 1, &len);
    /* MSG_NOSIGNAL: avoid SIGPIPE */
#ifdef __APPLE__
    rc = sendto(sock, (void *) data, len, 0, NULL, 0);
#else
    rc = sendto(sock, (void *) data, len, MSG_NOSIGNAL, NULL, 0);
#endif
    if (rc < 0) {
        ERROR_FROM_ERRNO(ctx);
    }
    duk_push_int(ctx, rc);
    return 1;
}
References duk_push_int(), duk_to_buffer, duk_to_int(), ERROR_FROM_ERRNO, MSG_NOSIGNAL, and NULL.
Variable Documentation
socket_funcs
duk_function_list_entry socket_funcs[] static
Initial value:
= {
    { "createServerSocket", socket_create_server_socket, 2 },
    { "close", socket_close, 1 },
    { "accept", socket_accept, 1 },
    { "connect", socket_connect, 2 },
    { "read", socket_read, 1 },
    { "write", socket_write, 2 },
    { NULL, NULL, 0 }
}
Definition at line 269 of file duktape-1.5.2/examples/eventloop/socket.c.
{
    { "createServerSocket", socket_create_server_socket, 2 },
    { "close", socket_close, 1 },
    { "accept", socket_accept, 1 },
    { "connect", socket_connect, 2 },
    { "read", socket_read, 1 },
    { "write", socket_write, 2 },
    { NULL, NULL, 0 }
};
Referenced by socket_register().