Github User Fetcher: duk_util_bitdecoder.c File Reference
duk_util_bitdecoder.c File Reference
#include "duk_internal.h"
Functions
DUK_INTERNAL duk_int32_t duk_bd_decode (duk_bitdecoder_ctx *ctx, duk_small_int_t bits)
DUK_INTERNAL duk_small_int_t duk_bd_decode_flag (duk_bitdecoder_ctx *ctx)
DUK_INTERNAL duk_int32_t duk_bd_decode_flagged (duk_bitdecoder_ctx *ctx, duk_small_int_t bits, duk_int32_t def_value)
Function Documentation
duk_bd_decode()
DUK_INTERNAL duk_int32_t duk_bd_decode (duk_bitdecoder_ctx * ctx, duk_small_int_t bits)
Definition at line 11 of file duktape-1.8.0/src-separate/duk_util_bitdecoder.c.
{
    duk_small_int_t shift;
    duk_uint32_t mask;
    duk_uint32_t tmp;
    /* Note: cannot read more than 24 bits without possibly shifting top bits out.
     * Fixable, but adds complexity.
     */
    DUK_ASSERT(bits >= 1 && bits <= 24);
    while (ctx->currbits < bits) {
#if 0
        DUK_DDD(DUK_DDDPRINT("decode_bits: shift more data (bits=%ld, currbits=%ld)",
                             (long) bits, (long) ctx->currbits));
#endif
        ctx->currval <<= 8;
        if (ctx->offset < ctx->length) {
            /* If ctx->offset >= ctx->length, we "shift zeroes in"
             * instead of croaking.
             */
            ctx->currval |= ctx->data[ctx->offset++];
        }
        ctx->currbits += 8;
    }
#if 0
    DUK_DDD(DUK_DDDPRINT("decode_bits: bits=%ld, currbits=%ld, currval=0x%08lx",
                         (long) bits, (long) ctx->currbits, (unsigned long) ctx->currval));
#endif
    /* Extract 'top' bits of currval; note that the extracted bits do not need
     * to be cleared, we just ignore them on next round.
     */
    shift = ctx->currbits - bits;
    mask = (1 << bits) - 1;
    tmp = (ctx->currval >> shift) & mask;
    ctx->currbits = shift;  /* remaining */
#if 0
    DUK_DDD(DUK_DDDPRINT("decode_bits: %ld bits -> 0x%08lx (%ld), currbits=%ld, currval=0x%08lx",
                         (long) bits, (unsigned long) tmp, (long) tmp, (long) ctx->currbits, (unsigned long) ctx->currval));
#endif
    return tmp;
}
References duk_bitdecoder_ctx::currbits, duk_bitdecoder_ctx::currval, duk_bitdecoder_ctx::data, DUK_ASSERT, DUK_DDD, DUK_DDDPRINT, duk_bitdecoder_ctx::length, mask, and duk_bitdecoder_ctx::offset.
Referenced by duk_bd_decode_flag(), and duk_bd_decode_flagged().
duk_bd_decode_flag()
DUK_INTERNAL duk_small_int_t duk_bd_decode_flag (duk_bitdecoder_ctx * ctx)
Definition at line 56 of file duktape-1.8.0/src-separate/duk_util_bitdecoder.c.
{
    return (duk_small_int_t) duk_bd_decode(ctx, 1);
}
References duk_bd_decode().
Referenced by duk_bd_decode_flagged().
duk_bd_decode_flagged()
DUK_INTERNAL duk_int32_t duk_bd_decode_flagged (duk_bitdecoder_ctx * ctx, duk_small_int_t bits, duk_int32_t def_value)
Definition at line 64 of file duktape-1.8.0/src-separate/duk_util_bitdecoder.c.
{
    if (duk_bd_decode_flag(ctx)) {
        return (duk_int32_t) duk_bd_decode(ctx, bits);
    } else {
        return def_value;
    }
}
References duk_bd_decode(), and duk_bd_decode_flag().