Github User Fetcher: duk_hobject.h File Reference
duk_hobject.h File Reference
Data Structures
struct duk_propaccessor
union duk_propvalue
struct duk_propdesc
struct duk_hobject
Macros
#define DUK_HOBJECT_FLAG_EXTENSIBLE DUK_HEAPHDR_USER_FLAG(0) /* object is extensible */
#define DUK_HOBJECT_FLAG_CONSTRUCTABLE DUK_HEAPHDR_USER_FLAG(1) /* object is constructable */
#define DUK_HOBJECT_FLAG_BOUND DUK_HEAPHDR_USER_FLAG(2) /* object established using Function.prototype.bind() */
#define DUK_HOBJECT_FLAG_COMPILEDFUNCTION DUK_HEAPHDR_USER_FLAG(4) /* object is a compiled function (duk_hcompiledfunction) */
#define DUK_HOBJECT_FLAG_NATIVEFUNCTION DUK_HEAPHDR_USER_FLAG(5) /* object is a native function (duk_hnativefunction) */
#define DUK_HOBJECT_FLAG_BUFFEROBJECT DUK_HEAPHDR_USER_FLAG(6) /* object is a buffer object (duk_hbufferobject) (always exotic) */
#define DUK_HOBJECT_FLAG_THREAD DUK_HEAPHDR_USER_FLAG(7) /* object is a thread (duk_hthread) */
#define DUK_HOBJECT_FLAG_ARRAY_PART DUK_HEAPHDR_USER_FLAG(8) /* object has an array part (a_size may still be 0) */
#define DUK_HOBJECT_FLAG_STRICT DUK_HEAPHDR_USER_FLAG(9) /* function: function object is strict */
#define DUK_HOBJECT_FLAG_NOTAIL DUK_HEAPHDR_USER_FLAG(10) /* function: function must not be tail called */
#define DUK_HOBJECT_FLAG_NEWENV DUK_HEAPHDR_USER_FLAG(11) /* function: create new environment when called (see duk_hcompiledfunction) */
#define DUK_HOBJECT_FLAG_NAMEBINDING DUK_HEAPHDR_USER_FLAG(12) /* function: create binding for func name (function templates only, used for named function expressions) */
#define DUK_HOBJECT_FLAG_CREATEARGS DUK_HEAPHDR_USER_FLAG(13) /* function: create an arguments object on function call */
#define DUK_HOBJECT_FLAG_ENVRECCLOSED DUK_HEAPHDR_USER_FLAG(14) /* envrec: (declarative) record is closed */
#define DUK_HOBJECT_FLAG_EXOTIC_ARRAY DUK_HEAPHDR_USER_FLAG(15) /* 'Array' object, array length and index exotic behavior */
#define DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ DUK_HEAPHDR_USER_FLAG(16) /* 'String' object, array index exotic behavior */
#define DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS DUK_HEAPHDR_USER_FLAG(17) /* 'Arguments' object and has arguments exotic behavior (non-strict callee) */
#define DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC DUK_HEAPHDR_USER_FLAG(18) /* Duktape/C (nativefunction) object, exotic 'length' */
#define DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ DUK_HEAPHDR_USER_FLAG(19) /* 'Proxy' object */
#define DUK_HOBJECT_FLAG_CLASS_BASE DUK_HEAPHDR_USER_FLAG_NUMBER(20)
#define DUK_HOBJECT_FLAG_CLASS_BITS 5
#define DUK_HOBJECT_GET_CLASS_NUMBER(h) DUK_HEAPHDR_GET_FLAG_RANGE(&(h)->hdr, DUK_HOBJECT_FLAG_CLASS_BASE, DUK_HOBJECT_FLAG_CLASS_BITS)
#define DUK_HOBJECT_SET_CLASS_NUMBER(h, v) DUK_HEAPHDR_SET_FLAG_RANGE(&(h)->hdr, DUK_HOBJECT_FLAG_CLASS_BASE, DUK_HOBJECT_FLAG_CLASS_BITS, (v))
#define DUK_HOBJECT_GET_CLASS_MASK(h) (1UL << DUK_HEAPHDR_GET_FLAG_RANGE(&(h)->hdr, DUK_HOBJECT_FLAG_CLASS_BASE, DUK_HOBJECT_FLAG_CLASS_BITS))
#define DUK_HOBJECT_CLASS_AS_FLAGS(v) (((duk_uint_t) (v)) << DUK_HOBJECT_FLAG_CLASS_BASE)
#define DUK_HOBJECT_CLASS_UNUSED 0
#define DUK_HOBJECT_CLASS_ARGUMENTS 1
#define DUK_HOBJECT_CLASS_ARRAY 2
#define DUK_HOBJECT_CLASS_BOOLEAN 3
#define DUK_HOBJECT_CLASS_DATE 4
#define DUK_HOBJECT_CLASS_ERROR 5
#define DUK_HOBJECT_CLASS_FUNCTION 6
#define DUK_HOBJECT_CLASS_JSON 7
#define DUK_HOBJECT_CLASS_MATH 8
#define DUK_HOBJECT_CLASS_NUMBER 9
#define DUK_HOBJECT_CLASS_OBJECT 10
#define DUK_HOBJECT_CLASS_REGEXP 11
#define DUK_HOBJECT_CLASS_STRING 12
#define DUK_HOBJECT_CLASS_GLOBAL 13
#define DUK_HOBJECT_CLASS_OBJENV 14 /* custom */
#define DUK_HOBJECT_CLASS_DECENV 15 /* custom */
#define DUK_HOBJECT_CLASS_BUFFER 16 /* custom; implies DUK_HOBJECT_IS_BUFFEROBJECT */
#define DUK_HOBJECT_CLASS_POINTER 17 /* custom */
#define DUK_HOBJECT_CLASS_THREAD 18 /* custom; implies DUK_HOBJECT_IS_THREAD */
#define DUK_HOBJECT_CLASS_ARRAYBUFFER 19 /* implies DUK_HOBJECT_IS_BUFFEROBJECT */
#define DUK_HOBJECT_CLASS_DATAVIEW 20
#define DUK_HOBJECT_CLASS_INT8ARRAY 21
#define DUK_HOBJECT_CLASS_UINT8ARRAY 22
#define DUK_HOBJECT_CLASS_UINT8CLAMPEDARRAY 23
#define DUK_HOBJECT_CLASS_INT16ARRAY 24
#define DUK_HOBJECT_CLASS_UINT16ARRAY 25
#define DUK_HOBJECT_CLASS_INT32ARRAY 26
#define DUK_HOBJECT_CLASS_UINT32ARRAY 27
#define DUK_HOBJECT_CLASS_FLOAT32ARRAY 28
#define DUK_HOBJECT_CLASS_FLOAT64ARRAY 29
#define DUK_HOBJECT_CLASS_MAX 29
#define DUK_HOBJECT_CMASK_ALL ((1UL << (DUK_HOBJECT_CLASS_MAX + 1)) - 1UL)
#define DUK_HOBJECT_CMASK_UNUSED (1UL << DUK_HOBJECT_CLASS_UNUSED)
#define DUK_HOBJECT_CMASK_ARGUMENTS (1UL << DUK_HOBJECT_CLASS_ARGUMENTS)
#define DUK_HOBJECT_CMASK_ARRAY (1UL << DUK_HOBJECT_CLASS_ARRAY)
#define DUK_HOBJECT_CMASK_BOOLEAN (1UL << DUK_HOBJECT_CLASS_BOOLEAN)
#define DUK_HOBJECT_CMASK_DATE (1UL << DUK_HOBJECT_CLASS_DATE)
#define DUK_HOBJECT_CMASK_ERROR (1UL << DUK_HOBJECT_CLASS_ERROR)
#define DUK_HOBJECT_CMASK_FUNCTION (1UL << DUK_HOBJECT_CLASS_FUNCTION)
#define DUK_HOBJECT_CMASK_JSON (1UL << DUK_HOBJECT_CLASS_JSON)
#define DUK_HOBJECT_CMASK_MATH (1UL << DUK_HOBJECT_CLASS_MATH)
#define DUK_HOBJECT_CMASK_NUMBER (1UL << DUK_HOBJECT_CLASS_NUMBER)
#define DUK_HOBJECT_CMASK_OBJECT (1UL << DUK_HOBJECT_CLASS_OBJECT)
#define DUK_HOBJECT_CMASK_REGEXP (1UL << DUK_HOBJECT_CLASS_REGEXP)
#define DUK_HOBJECT_CMASK_STRING (1UL << DUK_HOBJECT_CLASS_STRING)
#define DUK_HOBJECT_CMASK_GLOBAL (1UL << DUK_HOBJECT_CLASS_GLOBAL)
#define DUK_HOBJECT_CMASK_OBJENV (1UL << DUK_HOBJECT_CLASS_OBJENV)
#define DUK_HOBJECT_CMASK_DECENV (1UL << DUK_HOBJECT_CLASS_DECENV)
#define DUK_HOBJECT_CMASK_BUFFER (1UL << DUK_HOBJECT_CLASS_BUFFER)
#define DUK_HOBJECT_CMASK_POINTER (1UL << DUK_HOBJECT_CLASS_POINTER)
#define DUK_HOBJECT_CMASK_THREAD (1UL << DUK_HOBJECT_CLASS_THREAD)
#define DUK_HOBJECT_CMASK_ARRAYBUFFER (1UL << DUK_HOBJECT_CLASS_ARRAYBUFFER)
#define DUK_HOBJECT_CMASK_DATAVIEW (1UL << DUK_HOBJECT_CLASS_DATAVIEW)
#define DUK_HOBJECT_CMASK_INT8ARRAY (1UL << DUK_HOBJECT_CLASS_INT8ARRAY)
#define DUK_HOBJECT_CMASK_UINT8ARRAY (1UL << DUK_HOBJECT_CLASS_UINT8ARRAY)
#define DUK_HOBJECT_CMASK_UINT8CLAMPEDARRAY (1UL << DUK_HOBJECT_CLASS_UINT8CLAMPEDARRAY)
#define DUK_HOBJECT_CMASK_INT16ARRAY (1UL << DUK_HOBJECT_CLASS_INT16ARRAY)
#define DUK_HOBJECT_CMASK_UINT16ARRAY (1UL << DUK_HOBJECT_CLASS_UINT16ARRAY)
#define DUK_HOBJECT_CMASK_INT32ARRAY (1UL << DUK_HOBJECT_CLASS_INT32ARRAY)
#define DUK_HOBJECT_CMASK_UINT32ARRAY (1UL << DUK_HOBJECT_CLASS_UINT32ARRAY)
#define DUK_HOBJECT_CMASK_FLOAT32ARRAY (1UL << DUK_HOBJECT_CLASS_FLOAT32ARRAY)
#define DUK_HOBJECT_CMASK_FLOAT64ARRAY (1UL << DUK_HOBJECT_CLASS_FLOAT64ARRAY)
#define DUK_HOBJECT_CMASK_ALL_BUFFEROBJECTS
#define DUK_HOBJECT_IS_OBJENV(h) (DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_OBJENV)
#define DUK_HOBJECT_IS_DECENV(h) (DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_DECENV)
#define DUK_HOBJECT_IS_ENV(h) (DUK_HOBJECT_IS_OBJENV((h)) || DUK_HOBJECT_IS_DECENV((h)))
#define DUK_HOBJECT_IS_ARRAY(h) (DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_ARRAY)
#define DUK_HOBJECT_IS_COMPILEDFUNCTION(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_COMPILEDFUNCTION)
#define DUK_HOBJECT_IS_NATIVEFUNCTION(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NATIVEFUNCTION)
#define DUK_HOBJECT_IS_BUFFEROBJECT(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BUFFEROBJECT)
#define DUK_HOBJECT_IS_THREAD(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_THREAD)
#define DUK_HOBJECT_IS_NONBOUND_FUNCTION(h)
#define DUK_HOBJECT_IS_FUNCTION(h)
#define DUK_HOBJECT_IS_CALLABLE(h)
#define DUK_HOBJECT_EXOTIC_BEHAVIOR_FLAGS
#define DUK_HOBJECT_HAS_EXOTIC_BEHAVIOR(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_EXOTIC_BEHAVIOR_FLAGS)
#define DUK_HOBJECT_HAS_EXTENSIBLE(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXTENSIBLE)
#define DUK_HOBJECT_HAS_CONSTRUCTABLE(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CONSTRUCTABLE)
#define DUK_HOBJECT_HAS_BOUND(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BOUND)
#define DUK_HOBJECT_HAS_COMPILEDFUNCTION(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_COMPILEDFUNCTION)
#define DUK_HOBJECT_HAS_NATIVEFUNCTION(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NATIVEFUNCTION)
#define DUK_HOBJECT_HAS_BUFFEROBJECT(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BUFFEROBJECT)
#define DUK_HOBJECT_HAS_THREAD(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_THREAD)
#define DUK_HOBJECT_HAS_ARRAY_PART(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ARRAY_PART)
#define DUK_HOBJECT_HAS_STRICT(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_STRICT)
#define DUK_HOBJECT_HAS_NOTAIL(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NOTAIL)
#define DUK_HOBJECT_HAS_NEWENV(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NEWENV)
#define DUK_HOBJECT_HAS_NAMEBINDING(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NAMEBINDING)
#define DUK_HOBJECT_HAS_CREATEARGS(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CREATEARGS)
#define DUK_HOBJECT_HAS_ENVRECCLOSED(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ENVRECCLOSED)
#define DUK_HOBJECT_HAS_EXOTIC_ARRAY(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARRAY)
#define DUK_HOBJECT_HAS_EXOTIC_STRINGOBJ(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ)
#define DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS)
#define DUK_HOBJECT_HAS_EXOTIC_DUKFUNC(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC)
#define DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ(h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ)
#define DUK_HOBJECT_SET_EXTENSIBLE(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXTENSIBLE)
#define DUK_HOBJECT_SET_CONSTRUCTABLE(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CONSTRUCTABLE)
#define DUK_HOBJECT_SET_BOUND(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BOUND)
#define DUK_HOBJECT_SET_COMPILEDFUNCTION(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_COMPILEDFUNCTION)
#define DUK_HOBJECT_SET_NATIVEFUNCTION(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NATIVEFUNCTION)
#define DUK_HOBJECT_SET_BUFFEROBJECT(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BUFFEROBJECT)
#define DUK_HOBJECT_SET_THREAD(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_THREAD)
#define DUK_HOBJECT_SET_ARRAY_PART(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ARRAY_PART)
#define DUK_HOBJECT_SET_STRICT(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_STRICT)
#define DUK_HOBJECT_SET_NOTAIL(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NOTAIL)
#define DUK_HOBJECT_SET_NEWENV(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NEWENV)
#define DUK_HOBJECT_SET_NAMEBINDING(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NAMEBINDING)
#define DUK_HOBJECT_SET_CREATEARGS(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CREATEARGS)
#define DUK_HOBJECT_SET_ENVRECCLOSED(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ENVRECCLOSED)
#define DUK_HOBJECT_SET_EXOTIC_ARRAY(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARRAY)
#define DUK_HOBJECT_SET_EXOTIC_STRINGOBJ(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ)
#define DUK_HOBJECT_SET_EXOTIC_ARGUMENTS(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS)
#define DUK_HOBJECT_SET_EXOTIC_DUKFUNC(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC)
#define DUK_HOBJECT_SET_EXOTIC_PROXYOBJ(h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ)
#define DUK_HOBJECT_CLEAR_EXTENSIBLE(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXTENSIBLE)
#define DUK_HOBJECT_CLEAR_CONSTRUCTABLE(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CONSTRUCTABLE)
#define DUK_HOBJECT_CLEAR_BOUND(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BOUND)
#define DUK_HOBJECT_CLEAR_COMPILEDFUNCTION(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_COMPILEDFUNCTION)
#define DUK_HOBJECT_CLEAR_NATIVEFUNCTION(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NATIVEFUNCTION)
#define DUK_HOBJECT_CLEAR_BUFFEROBJECT(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BUFFEROBJECT)
#define DUK_HOBJECT_CLEAR_THREAD(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_THREAD)
#define DUK_HOBJECT_CLEAR_ARRAY_PART(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ARRAY_PART)
#define DUK_HOBJECT_CLEAR_STRICT(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_STRICT)
#define DUK_HOBJECT_CLEAR_NOTAIL(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NOTAIL)
#define DUK_HOBJECT_CLEAR_NEWENV(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NEWENV)
#define DUK_HOBJECT_CLEAR_NAMEBINDING(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NAMEBINDING)
#define DUK_HOBJECT_CLEAR_CREATEARGS(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CREATEARGS)
#define DUK_HOBJECT_CLEAR_ENVRECCLOSED(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ENVRECCLOSED)
#define DUK_HOBJECT_CLEAR_EXOTIC_ARRAY(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARRAY)
#define DUK_HOBJECT_CLEAR_EXOTIC_STRINGOBJ(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ)
#define DUK_HOBJECT_CLEAR_EXOTIC_ARGUMENTS(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS)
#define DUK_HOBJECT_CLEAR_EXOTIC_DUKFUNC(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC)
#define DUK_HOBJECT_CLEAR_EXOTIC_PROXYOBJ(h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ)
#define DUK_PROPDESC_FLAG_WRITABLE (1 << 0) /* E5 Section 8.6.1 */
#define DUK_PROPDESC_FLAG_ENUMERABLE (1 << 1) /* E5 Section 8.6.1 */
#define DUK_PROPDESC_FLAG_CONFIGURABLE (1 << 2) /* E5 Section 8.6.1 */
#define DUK_PROPDESC_FLAG_ACCESSOR (1 << 3) /* accessor */
#define DUK_PROPDESC_FLAG_VIRTUAL
#define DUK_PROPDESC_FLAGS_MASK
#define DUK_PROPDESC_FLAG_NO_OVERWRITE (1 << 4) /* internal define property: skip write silently if exists */
#define DUK_PROPDESC_FLAGS_NONE 0
#define DUK_PROPDESC_FLAGS_W (DUK_PROPDESC_FLAG_WRITABLE)
#define DUK_PROPDESC_FLAGS_E (DUK_PROPDESC_FLAG_ENUMERABLE)
#define DUK_PROPDESC_FLAGS_C (DUK_PROPDESC_FLAG_CONFIGURABLE)
#define DUK_PROPDESC_FLAGS_WE (DUK_PROPDESC_FLAG_WRITABLE | DUK_PROPDESC_FLAG_ENUMERABLE)
#define DUK_PROPDESC_FLAGS_WC (DUK_PROPDESC_FLAG_WRITABLE | DUK_PROPDESC_FLAG_CONFIGURABLE)
#define DUK_PROPDESC_FLAGS_EC (DUK_PROPDESC_FLAG_ENUMERABLE | DUK_PROPDESC_FLAG_CONFIGURABLE)
#define DUK_PROPDESC_FLAGS_WEC
#define DUK_GETDESC_FLAG_PUSH_VALUE (1 << 0) /* push value to stack */
#define DUK_GETDESC_FLAG_IGNORE_PROTOLOOP (1 << 1) /* don't throw for prototype loop */
#define DUK_ASSERT_HOBJECT_VALID(h)
#define DUK_HOBJECT_GET_PROPS(heap, h) ((h)->props)
#define DUK_HOBJECT_SET_PROPS(heap, h, x)
#define DUK_HOBJECT_P_ALLOC_SIZE(h) DUK_HOBJECT_P_COMPUTE_SIZE(DUK_HOBJECT_GET_ESIZE((h)), DUK_HOBJECT_GET_ASIZE((h)), DUK_HOBJECT_GET_HSIZE((h)))
#define DUK_HOBJECT_E_GET_KEY(heap, h, i) (DUK_HOBJECT_E_GET_KEY_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_E_GET_KEY_PTR(heap, h, i) (&DUK_HOBJECT_E_GET_KEY_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_E_GET_VALUE(heap, h, i) (DUK_HOBJECT_E_GET_VALUE_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_E_GET_VALUE_PTR(heap, h, i) (&DUK_HOBJECT_E_GET_VALUE_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_E_GET_VALUE_TVAL(heap, h, i) (DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).v)
#define DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(heap, h, i) (&DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).v)
#define DUK_HOBJECT_E_GET_VALUE_GETTER(heap, h, i) (DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.get)
#define DUK_HOBJECT_E_GET_VALUE_GETTER_PTR(heap, h, i) (&DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.get)
#define DUK_HOBJECT_E_GET_VALUE_SETTER(heap, h, i) (DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.set)
#define DUK_HOBJECT_E_GET_VALUE_SETTER_PTR(heap, h, i) (&DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.set)
#define DUK_HOBJECT_E_GET_FLAGS(heap, h, i) (DUK_HOBJECT_E_GET_FLAGS_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_E_GET_FLAGS_PTR(heap, h, i) (&DUK_HOBJECT_E_GET_FLAGS_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_A_GET_VALUE(heap, h, i) (DUK_HOBJECT_A_GET_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_A_GET_VALUE_PTR(heap, h, i) (&DUK_HOBJECT_A_GET_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_H_GET_INDEX(heap, h, i) (DUK_HOBJECT_H_GET_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_H_GET_INDEX_PTR(heap, h, i) (&DUK_HOBJECT_H_GET_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_E_SET_KEY(heap, h, i, k)
#define DUK_HOBJECT_E_SET_VALUE(heap, h, i, v)
#define DUK_HOBJECT_E_SET_VALUE_TVAL(heap, h, i, v)
#define DUK_HOBJECT_E_SET_VALUE_GETTER(heap, h, i, v)
#define DUK_HOBJECT_E_SET_VALUE_SETTER(heap, h, i, v)
#define DUK_HOBJECT_E_SET_FLAGS(heap, h, i, f)
#define DUK_HOBJECT_A_SET_VALUE(heap, h, i, v)
#define DUK_HOBJECT_A_SET_VALUE_TVAL(heap, h, i, v) DUK_HOBJECT_A_SET_VALUE((heap), (h), (i), (v)) /* alias for above */
#define DUK_HOBJECT_H_SET_INDEX(heap, h, i, v)
#define DUK_HOBJECT_E_SET_FLAG_BITS(heap, h, i, mask)
#define DUK_HOBJECT_E_CLEAR_FLAG_BITS(heap, h, i, mask)
#define DUK_HOBJECT_E_SLOT_IS_WRITABLE(heap, h, i) ((DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) & DUK_PROPDESC_FLAG_WRITABLE) != 0)
#define DUK_HOBJECT_E_SLOT_IS_ENUMERABLE(heap, h, i) ((DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) & DUK_PROPDESC_FLAG_ENUMERABLE) != 0)
#define DUK_HOBJECT_E_SLOT_IS_CONFIGURABLE(heap, h, i) ((DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) & DUK_PROPDESC_FLAG_CONFIGURABLE) != 0)
#define DUK_HOBJECT_E_SLOT_IS_ACCESSOR(heap, h, i) ((DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) & DUK_PROPDESC_FLAG_ACCESSOR) != 0)
#define DUK_HOBJECT_E_SLOT_SET_WRITABLE(heap, h, i) DUK_HOBJECT_E_SET_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_WRITABLE)
#define DUK_HOBJECT_E_SLOT_SET_ENUMERABLE(heap, h, i) DUK_HOBJECT_E_SET_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_ENUMERABLE)
#define DUK_HOBJECT_E_SLOT_SET_CONFIGURABLE(heap, h, i) DUK_HOBJECT_E_SET_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_CONFIGURABLE)
#define DUK_HOBJECT_E_SLOT_SET_ACCESSOR(heap, h, i) DUK_HOBJECT_E_SET_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_ACCESSOR)
#define DUK_HOBJECT_E_SLOT_CLEAR_WRITABLE(heap, h, i) DUK_HOBJECT_E_CLEAR_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_WRITABLE)
#define DUK_HOBJECT_E_SLOT_CLEAR_ENUMERABLE(heap, h, i) DUK_HOBJECT_E_CLEAR_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_ENUMERABLE)
#define DUK_HOBJECT_E_SLOT_CLEAR_CONFIGURABLE(heap, h, i) DUK_HOBJECT_E_CLEAR_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_CONFIGURABLE)
#define DUK_HOBJECT_E_SLOT_CLEAR_ACCESSOR(heap, h, i) DUK_HOBJECT_E_CLEAR_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_ACCESSOR)
#define DUK_PROPDESC_IS_WRITABLE(p) (((p)->flags & DUK_PROPDESC_FLAG_WRITABLE) != 0)
#define DUK_PROPDESC_IS_ENUMERABLE(p) (((p)->flags & DUK_PROPDESC_FLAG_ENUMERABLE) != 0)
#define DUK_PROPDESC_IS_CONFIGURABLE(p) (((p)->flags & DUK_PROPDESC_FLAG_CONFIGURABLE) != 0)
#define DUK_PROPDESC_IS_ACCESSOR(p) (((p)->flags & DUK_PROPDESC_FLAG_ACCESSOR) != 0)
#define DUK_HOBJECT_HASHIDX_UNUSED 0xffffffffUL
#define DUK_HOBJECT_HASHIDX_DELETED 0xfffffffeUL
#define DUK_HOBJECT_GET_ESIZE(h) ((h)->e_size)
#define DUK_HOBJECT_SET_ESIZE(h, v) do { (h)->e_size = (v); } while (0)
#define DUK_HOBJECT_GET_ENEXT(h) ((h)->e_next)
#define DUK_HOBJECT_SET_ENEXT(h, v) do { (h)->e_next = (v); } while (0)
#define DUK_HOBJECT_POSTINC_ENEXT(h) ((h)->e_next++)
#define DUK_HOBJECT_GET_ASIZE(h) ((h)->a_size)
#define DUK_HOBJECT_SET_ASIZE(h, v) do { (h)->a_size = (v); } while (0)
#define DUK_HOBJECT_GET_HSIZE(h) 0
#define DUK_HOBJECT_SET_HSIZE(h, v) do { DUK_ASSERT((v) == 0); } while (0)
#define DUK_HOBJECT_PROTOTYPE_CHAIN_SANITY 10000L
#define DUK_HOBJECT_BOUND_CHAIN_SANITY 10000L
#define DUK_HOBJECT_CLASS_NUMBER_TO_STRIDX(n) duk_class_number_to_stridx[(n)]
#define DUK_HOBJECT_GET_CLASS_STRING(heap, h)
#define DUK_HOBJECT_GET_PROTOTYPE(heap, h) ((h)->prototype)
#define DUK_HOBJECT_SET_PROTOTYPE(heap, h, x)
#define DUK_HOBJECT_SET_PROTOTYPE_UPDREF(thr, h, p) duk_hobject_set_prototype_updref((thr), (h), (p))
#define DUK_HOBJECT_MAX_PROPERTIES 0x7fffffffUL /* 2**31-1 ~= 2G properties */
#define DUK_HOBJECT_E_USE_HASH_LIMIT 32
#define DUK_HOBJECT_H_SIZE_DIVISOR 4 /* hash size approx. 1.25 times entries size */
#define DUK_HOBJECT_A_FAST_RESIZE_LIMIT 9 /* 112.5%, i.e. new size less than 12.5% higher -> fast resize */
#define DUK_HOBJECT_A_ABANDON_LIMIT 2 /* 25%, i.e. less than 25% used -> abandon */
#define DUK_HOBJECT_E_MIN_GROW_ADD 16
#define DUK_HOBJECT_E_MIN_GROW_DIVISOR 8 /* 2^3 -> 1/8 = 12.5% min growth */
#define DUK_HOBJECT_A_MIN_GROW_ADD 16
#define DUK_HOBJECT_A_MIN_GROW_DIVISOR 8 /* 2^3 -> 1/8 = 12.5% min growth */
#define DUK_HOBJECT_HASH_INITIAL(hash, h_size) ((hash) % (h_size))
#define DUK_HOBJECT_HASH_PROBE_STEP(hash) DUK_UTIL_GET_HASH_PROBE_STEP((hash))
#define DUK_PC2LINE_SKIP 64
#define DUK_PC2LINE_MAX_DIFF_LENGTH (((DUK_PC2LINE_SKIP - 1) * 35 + 7) / 8)
#define duk_hobject_get_internal_value_tval_ptr(heap, obj) duk_hobject_find_existing_entry_tval_ptr((heap), (obj), DUK_HEAP_STRING_INT_VALUE((heap)))
#define DUK_DELPROP_FLAG_THROW (1 << 0)
#define DUK_DELPROP_FLAG_FORCE (1 << 1)
Functions
DUK_INTERNAL_DECL duk_hobject * duk_hobject_alloc (duk_heap *heap, duk_uint_t hobject_flags)
DUK_INTERNAL_DECL duk_hcompiledfunction * duk_hcompiledfunction_alloc (duk_heap *heap, duk_uint_t hobject_flags)
DUK_INTERNAL_DECL duk_hnativefunction * duk_hnativefunction_alloc (duk_heap *heap, duk_uint_t hobject_flags)
DUK_INTERNAL duk_hbufferobject * duk_hbufferobject_alloc (duk_heap *heap, duk_uint_t hobject_flags)
DUK_INTERNAL_DECL duk_hthread * duk_hthread_alloc (duk_heap *heap, duk_uint_t hobject_flags)
DUK_INTERNAL_DECL void duk_hobject_find_existing_entry (duk_heap *heap, duk_hobject *obj, duk_hstring *key, duk_int_t *e_idx, duk_int_t *h_idx)
DUK_INTERNAL_DECL duk_tval * duk_hobject_find_existing_entry_tval_ptr (duk_heap *heap, duk_hobject *obj, duk_hstring *key)
DUK_INTERNAL_DECL duk_tval * duk_hobject_find_existing_entry_tval_ptr_and_attrs (duk_heap *heap, duk_hobject *obj, duk_hstring *key, duk_int_t *out_attrs)
DUK_INTERNAL_DECL duk_tval * duk_hobject_find_existing_array_entry_tval_ptr (duk_heap *heap, duk_hobject *obj, duk_uarridx_t i)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_get_own_propdesc (duk_hthread *thr, duk_hobject *obj, duk_hstring *key, duk_propdesc *out_desc, duk_small_uint_t flags)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_getprop (duk_hthread *thr, duk_tval *tv_obj, duk_tval *tv_key)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_putprop (duk_hthread *thr, duk_tval *tv_obj, duk_tval *tv_key, duk_tval *tv_val, duk_bool_t throw_flag)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_delprop (duk_hthread *thr, duk_tval *tv_obj, duk_tval *tv_key, duk_bool_t throw_flag)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_hasprop (duk_hthread *thr, duk_tval *tv_obj, duk_tval *tv_key)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_delprop_raw (duk_hthread *thr, duk_hobject *obj, duk_hstring *key, duk_small_uint_t flags)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_hasprop_raw (duk_hthread *thr, duk_hobject *obj, duk_hstring *key)
DUK_INTERNAL_DECL void duk_hobject_define_property_internal (duk_hthread *thr, duk_hobject *obj, duk_hstring *key, duk_small_uint_t flags)
DUK_INTERNAL_DECL void duk_hobject_define_property_internal_arridx (duk_hthread *thr, duk_hobject *obj, duk_uarridx_t arr_idx, duk_small_uint_t flags)
DUK_INTERNAL_DECL void duk_hobject_define_accessor_internal (duk_hthread *thr, duk_hobject *obj, duk_hstring *key, duk_hobject *getter, duk_hobject *setter, duk_small_uint_t propflags)
DUK_INTERNAL_DECL void duk_hobject_set_length (duk_hthread *thr, duk_hobject *obj, duk_uint32_t length)
DUK_INTERNAL_DECL void duk_hobject_set_length_zero (duk_hthread *thr, duk_hobject *obj)
DUK_INTERNAL_DECL duk_uint32_t duk_hobject_get_length (duk_hthread *thr, duk_hobject *obj)
DUK_INTERNAL_DECL void duk_hobject_prepare_property_descriptor (duk_context *ctx, duk_idx_t idx_in, duk_uint_t *out_defprop_flags, duk_idx_t *out_idx_value, duk_hobject **out_getter, duk_hobject **out_setter)
DUK_INTERNAL_DECL void duk_hobject_define_property_helper (duk_context *ctx, duk_uint_t defprop_flags, duk_hobject *obj, duk_hstring *key, duk_idx_t idx_value, duk_hobject *get, duk_hobject *set)
DUK_INTERNAL_DECL duk_ret_t duk_hobject_object_get_own_property_descriptor (duk_context *ctx)
DUK_INTERNAL_DECL void duk_hobject_object_seal_freeze_helper (duk_hthread *thr, duk_hobject *obj, duk_bool_t is_freeze)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_object_is_sealed_frozen_helper (duk_hthread *thr, duk_hobject *obj, duk_bool_t is_frozen)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_object_ownprop_helper (duk_context *ctx, duk_small_uint_t required_desc_flags)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_get_internal_value (duk_heap *heap, duk_hobject *obj, duk_tval *tv)
DUK_INTERNAL_DECL duk_hstring * duk_hobject_get_internal_value_string (duk_heap *heap, duk_hobject *obj)
DUK_INTERNAL_DECL void duk_hobject_compact_props (duk_hthread *thr, duk_hobject *obj)
DUK_INTERNAL_DECL void duk_hobject_enumerator_create (duk_context *ctx, duk_small_uint_t enum_flags)
DUK_INTERNAL_DECL duk_ret_t duk_hobject_get_enumerated_keys (duk_context *ctx, duk_small_uint_t enum_flags)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_enumerator_next (duk_context *ctx, duk_bool_t get_value)
DUK_INTERNAL_DECL void duk_hobject_set_prototype_updref (duk_hthread *thr, duk_hobject *h, duk_hobject *p)
DUK_INTERNAL_DECL void duk_hobject_run_finalizer (duk_hthread *thr, duk_hobject *obj)
DUK_INTERNAL_DECL duk_bool_t duk_hobject_prototype_chain_contains (duk_hthread *thr, duk_hobject *h, duk_hobject *p, duk_bool_t ignore_loop)
Variables
DUK_INTERNAL_DECL duk_uint8_t duk_class_number_to_stridx [32]
Macro Definition Documentation
DUK_ASSERT_HOBJECT_VALID
#define DUK_ASSERT_HOBJECT_VALID (h)
Value:
        do { \
        DUK_ASSERT((h) != NULL); \
        DUK_ASSERT(!DUK_HOBJECT_IS_CALLABLE((h)) || \
                   DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_FUNCTION); \
        DUK_ASSERT(!DUK_HOBJECT_IS_BUFFEROBJECT((h)) || \
                   (DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_BUFFER || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_ARRAYBUFFER || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_DATAVIEW || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_INT8ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_UINT8ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_UINT8CLAMPEDARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_INT16ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_UINT16ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_INT32ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_UINT32ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_FLOAT32ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_FLOAT64ARRAY)); \
    } while (0)
Definition at line 287 of file duktape-1.8.0/src-separate/duk_hobject.h.
 */
#define DUK_ASSERT_HOBJECT_VALID(h) do { \
        DUK_ASSERT((h) != NULL); \
        DUK_ASSERT(!DUK_HOBJECT_IS_CALLABLE((h)) || \
                   DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_FUNCTION); \
        DUK_ASSERT(!DUK_HOBJECT_IS_BUFFEROBJECT((h)) || \
                   (DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_BUFFER || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_ARRAYBUFFER || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_DATAVIEW || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_INT8ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_UINT8ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_UINT8CLAMPEDARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_INT16ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_UINT16ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_INT32ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_UINT32ARRAY || \
                    DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_FLOAT32ARRAY || \
DUK_DELPROP_FLAG_FORCE
#define DUK_DELPROP_FLAG_FORCE (1 << 1)
Definition at line 858 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_DELPROP_FLAG_THROW
#define DUK_DELPROP_FLAG_THROW (1 << 0)
Definition at line 857 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_GETDESC_FLAG_IGNORE_PROTOLOOP
#define DUK_GETDESC_FLAG_IGNORE_PROTOLOOP (1 << 1) /* don't throw for prototype loop */
Definition at line 279 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_GETDESC_FLAG_PUSH_VALUE
#define DUK_GETDESC_FLAG_PUSH_VALUE (1 << 0) /* push value to stack */
Definition at line 278 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_A_ABANDON_LIMIT
#define DUK_HOBJECT_A_ABANDON_LIMIT 2 /* 25%, i.e. less than 25% used -> abandon */
Definition at line 650 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_A_FAST_RESIZE_LIMIT
#define DUK_HOBJECT_A_FAST_RESIZE_LIMIT 9 /* 112.5%, i.e. new size less than 12.5% higher -> fast resize */
Definition at line 646 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_A_GET_VALUE
#define DUK_HOBJECT_A_GET_VALUE (heap, h, i) (DUK_HOBJECT_A_GET_BASE((heap), (h))[(i)])
Definition at line 478 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_A_GET_VALUE_PTR
#define DUK_HOBJECT_A_GET_VALUE_PTR (heap, h, i) (&DUK_HOBJECT_A_GET_BASE((heap), (h))[(i)])
Definition at line 479 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_A_MIN_GROW_ADD
#define DUK_HOBJECT_A_MIN_GROW_ADD 16
Definition at line 668 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_A_MIN_GROW_DIVISOR
#define DUK_HOBJECT_A_MIN_GROW_DIVISOR 8 /* 2^3 -> 1/8 = 12.5% min growth */
Definition at line 669 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_A_SET_VALUE
#define DUK_HOBJECT_A_SET_VALUE (heap, h, i, v)
Value:
        do { \
        DUK_HOBJECT_A_GET_VALUE((heap), (h), (i)) = (v); \
    } while (0)
Definition at line 501 of file duktape-1.8.0/src-separate/duk_hobject.h.
        DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) = (duk_uint8_t) (f); \
    } while (0)
#define DUK_HOBJECT_A_SET_VALUE(heap,h,i,v)  do { \
DUK_HOBJECT_A_SET_VALUE_TVAL
#define DUK_HOBJECT_A_SET_VALUE_TVAL (heap, h, i, v) DUK_HOBJECT_A_SET_VALUE((heap), (h), (i), (v)) /* alias for above */
Definition at line 504 of file duktape-1.8.0/src-separate/duk_hobject.h.
        DUK_HOBJECT_A_GET_VALUE((heap), (h), (i)) = (v); \
    } while (0)
DUK_HOBJECT_BOUND_CHAIN_SANITY
#define DUK_HOBJECT_BOUND_CHAIN_SANITY 10000L
Definition at line 587 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_ARGUMENTS
#define DUK_HOBJECT_CLASS_ARGUMENTS 1
Definition at line 78 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_ARRAY
#define DUK_HOBJECT_CLASS_ARRAY 2
Definition at line 79 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_ARRAYBUFFER
#define DUK_HOBJECT_CLASS_ARRAYBUFFER 19 /* implies DUK_HOBJECT_IS_BUFFEROBJECT */
Definition at line 96 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_AS_FLAGS
#define DUK_HOBJECT_CLASS_AS_FLAGS (v) (((duk_uint_t) (v)) << DUK_HOBJECT_FLAG_CLASS_BASE)
Definition at line 74 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_BOOLEAN
#define DUK_HOBJECT_CLASS_BOOLEAN 3
Definition at line 80 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_BUFFER
#define DUK_HOBJECT_CLASS_BUFFER 16 /* custom; implies DUK_HOBJECT_IS_BUFFEROBJECT */
Definition at line 93 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_DATAVIEW
#define DUK_HOBJECT_CLASS_DATAVIEW 20
Definition at line 97 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_DATE
#define DUK_HOBJECT_CLASS_DATE 4
Definition at line 81 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_DECENV
#define DUK_HOBJECT_CLASS_DECENV 15 /* custom */
Definition at line 92 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_ERROR
#define DUK_HOBJECT_CLASS_ERROR 5
Definition at line 82 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_FLOAT32ARRAY
#define DUK_HOBJECT_CLASS_FLOAT32ARRAY 28
Definition at line 105 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_FLOAT64ARRAY
#define DUK_HOBJECT_CLASS_FLOAT64ARRAY 29
Definition at line 106 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_FUNCTION
#define DUK_HOBJECT_CLASS_FUNCTION 6
Definition at line 83 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_GLOBAL
#define DUK_HOBJECT_CLASS_GLOBAL 13
Definition at line 90 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_INT16ARRAY
#define DUK_HOBJECT_CLASS_INT16ARRAY 24
Definition at line 101 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_INT32ARRAY
#define DUK_HOBJECT_CLASS_INT32ARRAY 26
Definition at line 103 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_INT8ARRAY
#define DUK_HOBJECT_CLASS_INT8ARRAY 21
Definition at line 98 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_JSON
#define DUK_HOBJECT_CLASS_JSON 7
Definition at line 84 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_MATH
#define DUK_HOBJECT_CLASS_MATH 8
Definition at line 85 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_MAX
#define DUK_HOBJECT_CLASS_MAX 29
Definition at line 107 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_NUMBER
#define DUK_HOBJECT_CLASS_NUMBER 9
Definition at line 86 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_NUMBER_TO_STRIDX
#define DUK_HOBJECT_CLASS_NUMBER_TO_STRIDX (n) duk_class_number_to_stridx[(n)]
Definition at line 594 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_OBJECT
#define DUK_HOBJECT_CLASS_OBJECT 10
Definition at line 87 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_OBJENV
#define DUK_HOBJECT_CLASS_OBJENV 14 /* custom */
Definition at line 91 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_POINTER
#define DUK_HOBJECT_CLASS_POINTER 17 /* custom */
Definition at line 94 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_REGEXP
#define DUK_HOBJECT_CLASS_REGEXP 11
Definition at line 88 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_STRING
#define DUK_HOBJECT_CLASS_STRING 12
Definition at line 89 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_THREAD
#define DUK_HOBJECT_CLASS_THREAD 18 /* custom; implies DUK_HOBJECT_IS_THREAD */
Definition at line 95 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_UINT16ARRAY
#define DUK_HOBJECT_CLASS_UINT16ARRAY 25
Definition at line 102 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_UINT32ARRAY
#define DUK_HOBJECT_CLASS_UINT32ARRAY 27
Definition at line 104 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_UINT8ARRAY
#define DUK_HOBJECT_CLASS_UINT8ARRAY 22
Definition at line 99 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_UINT8CLAMPEDARRAY
#define DUK_HOBJECT_CLASS_UINT8CLAMPEDARRAY 23
Definition at line 100 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLASS_UNUSED
#define DUK_HOBJECT_CLASS_UNUSED 0
Definition at line 77 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_ARRAY_PART
#define DUK_HOBJECT_CLEAR_ARRAY_PART (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ARRAY_PART)
Definition at line 236 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_BOUND
#define DUK_HOBJECT_CLEAR_BOUND (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BOUND)
Definition at line 231 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_BUFFEROBJECT
#define DUK_HOBJECT_CLEAR_BUFFEROBJECT (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BUFFEROBJECT)
Definition at line 234 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_COMPILEDFUNCTION
#define DUK_HOBJECT_CLEAR_COMPILEDFUNCTION (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_COMPILEDFUNCTION)
Definition at line 232 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_CONSTRUCTABLE
#define DUK_HOBJECT_CLEAR_CONSTRUCTABLE (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CONSTRUCTABLE)
Definition at line 230 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_CREATEARGS
#define DUK_HOBJECT_CLEAR_CREATEARGS (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CREATEARGS)
Definition at line 241 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_ENVRECCLOSED
#define DUK_HOBJECT_CLEAR_ENVRECCLOSED (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ENVRECCLOSED)
Definition at line 242 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_EXOTIC_ARGUMENTS
#define DUK_HOBJECT_CLEAR_EXOTIC_ARGUMENTS (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS)
Definition at line 245 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_EXOTIC_ARRAY
#define DUK_HOBJECT_CLEAR_EXOTIC_ARRAY (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARRAY)
Definition at line 243 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_EXOTIC_DUKFUNC
#define DUK_HOBJECT_CLEAR_EXOTIC_DUKFUNC (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC)
Definition at line 246 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_EXOTIC_PROXYOBJ
#define DUK_HOBJECT_CLEAR_EXOTIC_PROXYOBJ (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ)
Definition at line 247 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_EXOTIC_STRINGOBJ
#define DUK_HOBJECT_CLEAR_EXOTIC_STRINGOBJ (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ)
Definition at line 244 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_EXTENSIBLE
#define DUK_HOBJECT_CLEAR_EXTENSIBLE (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXTENSIBLE)
Definition at line 229 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_NAMEBINDING
#define DUK_HOBJECT_CLEAR_NAMEBINDING (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NAMEBINDING)
Definition at line 240 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_NATIVEFUNCTION
#define DUK_HOBJECT_CLEAR_NATIVEFUNCTION (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NATIVEFUNCTION)
Definition at line 233 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_NEWENV
#define DUK_HOBJECT_CLEAR_NEWENV (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NEWENV)
Definition at line 239 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_NOTAIL
#define DUK_HOBJECT_CLEAR_NOTAIL (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NOTAIL)
Definition at line 238 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_STRICT
#define DUK_HOBJECT_CLEAR_STRICT (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_STRICT)
Definition at line 237 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CLEAR_THREAD
#define DUK_HOBJECT_CLEAR_THREAD (h) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_THREAD)
Definition at line 235 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_ALL
#define DUK_HOBJECT_CMASK_ALL ((1UL << (DUK_HOBJECT_CLASS_MAX + 1)) - 1UL)
Definition at line 110 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_ALL_BUFFEROBJECTS
#define DUK_HOBJECT_CMASK_ALL_BUFFEROBJECTS
Value:
    (DUK_HOBJECT_CMASK_BUFFER | \
     DUK_HOBJECT_CMASK_ARRAYBUFFER | \
     DUK_HOBJECT_CMASK_DATAVIEW | \
     DUK_HOBJECT_CMASK_INT8ARRAY | \
     DUK_HOBJECT_CMASK_UINT8ARRAY | \
     DUK_HOBJECT_CMASK_UINT8CLAMPEDARRAY | \
     DUK_HOBJECT_CMASK_INT16ARRAY | \
     DUK_HOBJECT_CMASK_UINT16ARRAY | \
     DUK_HOBJECT_CMASK_INT32ARRAY | \
     DUK_HOBJECT_CMASK_UINT32ARRAY | \
     DUK_HOBJECT_CMASK_FLOAT32ARRAY | \
     DUK_HOBJECT_CMASK_FLOAT64ARRAY)
Definition at line 142 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_CMASK_ALL_BUFFEROBJECTS \
    (DUK_HOBJECT_CMASK_BUFFER | \
     DUK_HOBJECT_CMASK_ARRAYBUFFER | \
     DUK_HOBJECT_CMASK_DATAVIEW | \
     DUK_HOBJECT_CMASK_INT8ARRAY | \
     DUK_HOBJECT_CMASK_UINT8ARRAY | \
     DUK_HOBJECT_CMASK_UINT8CLAMPEDARRAY | \
     DUK_HOBJECT_CMASK_INT16ARRAY | \
     DUK_HOBJECT_CMASK_UINT16ARRAY | \
     DUK_HOBJECT_CMASK_INT32ARRAY | \
     DUK_HOBJECT_CMASK_UINT32ARRAY | \
     DUK_HOBJECT_CMASK_FLOAT32ARRAY | \
     DUK_HOBJECT_CMASK_FLOAT64ARRAY)
DUK_HOBJECT_CMASK_ARGUMENTS
#define DUK_HOBJECT_CMASK_ARGUMENTS (1UL << DUK_HOBJECT_CLASS_ARGUMENTS)
Definition at line 112 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_ARRAY
#define DUK_HOBJECT_CMASK_ARRAY (1UL << DUK_HOBJECT_CLASS_ARRAY)
Definition at line 113 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_ARRAYBUFFER
#define DUK_HOBJECT_CMASK_ARRAYBUFFER (1UL << DUK_HOBJECT_CLASS_ARRAYBUFFER)
Definition at line 130 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_BOOLEAN
#define DUK_HOBJECT_CMASK_BOOLEAN (1UL << DUK_HOBJECT_CLASS_BOOLEAN)
Definition at line 114 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_BUFFER
#define DUK_HOBJECT_CMASK_BUFFER (1UL << DUK_HOBJECT_CLASS_BUFFER)
Definition at line 127 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_DATAVIEW
#define DUK_HOBJECT_CMASK_DATAVIEW (1UL << DUK_HOBJECT_CLASS_DATAVIEW)
Definition at line 131 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_DATE
#define DUK_HOBJECT_CMASK_DATE (1UL << DUK_HOBJECT_CLASS_DATE)
Definition at line 115 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_DECENV
#define DUK_HOBJECT_CMASK_DECENV (1UL << DUK_HOBJECT_CLASS_DECENV)
Definition at line 126 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_ERROR
#define DUK_HOBJECT_CMASK_ERROR (1UL << DUK_HOBJECT_CLASS_ERROR)
Definition at line 116 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_FLOAT32ARRAY
#define DUK_HOBJECT_CMASK_FLOAT32ARRAY (1UL << DUK_HOBJECT_CLASS_FLOAT32ARRAY)
Definition at line 139 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_FLOAT64ARRAY
#define DUK_HOBJECT_CMASK_FLOAT64ARRAY (1UL << DUK_HOBJECT_CLASS_FLOAT64ARRAY)
Definition at line 140 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_FUNCTION
#define DUK_HOBJECT_CMASK_FUNCTION (1UL << DUK_HOBJECT_CLASS_FUNCTION)
Definition at line 117 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_GLOBAL
#define DUK_HOBJECT_CMASK_GLOBAL (1UL << DUK_HOBJECT_CLASS_GLOBAL)
Definition at line 124 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_INT16ARRAY
#define DUK_HOBJECT_CMASK_INT16ARRAY (1UL << DUK_HOBJECT_CLASS_INT16ARRAY)
Definition at line 135 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_INT32ARRAY
#define DUK_HOBJECT_CMASK_INT32ARRAY (1UL << DUK_HOBJECT_CLASS_INT32ARRAY)
Definition at line 137 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_INT8ARRAY
#define DUK_HOBJECT_CMASK_INT8ARRAY (1UL << DUK_HOBJECT_CLASS_INT8ARRAY)
Definition at line 132 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_JSON
#define DUK_HOBJECT_CMASK_JSON (1UL << DUK_HOBJECT_CLASS_JSON)
Definition at line 118 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_MATH
#define DUK_HOBJECT_CMASK_MATH (1UL << DUK_HOBJECT_CLASS_MATH)
Definition at line 119 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_NUMBER
#define DUK_HOBJECT_CMASK_NUMBER (1UL << DUK_HOBJECT_CLASS_NUMBER)
Definition at line 120 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_OBJECT
#define DUK_HOBJECT_CMASK_OBJECT (1UL << DUK_HOBJECT_CLASS_OBJECT)
Definition at line 121 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_OBJENV
#define DUK_HOBJECT_CMASK_OBJENV (1UL << DUK_HOBJECT_CLASS_OBJENV)
Definition at line 125 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_POINTER
#define DUK_HOBJECT_CMASK_POINTER (1UL << DUK_HOBJECT_CLASS_POINTER)
Definition at line 128 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_REGEXP
#define DUK_HOBJECT_CMASK_REGEXP (1UL << DUK_HOBJECT_CLASS_REGEXP)
Definition at line 122 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_STRING
#define DUK_HOBJECT_CMASK_STRING (1UL << DUK_HOBJECT_CLASS_STRING)
Definition at line 123 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_THREAD
#define DUK_HOBJECT_CMASK_THREAD (1UL << DUK_HOBJECT_CLASS_THREAD)
Definition at line 129 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_UINT16ARRAY
#define DUK_HOBJECT_CMASK_UINT16ARRAY (1UL << DUK_HOBJECT_CLASS_UINT16ARRAY)
Definition at line 136 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_UINT32ARRAY
#define DUK_HOBJECT_CMASK_UINT32ARRAY (1UL << DUK_HOBJECT_CLASS_UINT32ARRAY)
Definition at line 138 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_UINT8ARRAY
#define DUK_HOBJECT_CMASK_UINT8ARRAY (1UL << DUK_HOBJECT_CLASS_UINT8ARRAY)
Definition at line 133 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_UINT8CLAMPEDARRAY
#define DUK_HOBJECT_CMASK_UINT8CLAMPEDARRAY (1UL << DUK_HOBJECT_CLASS_UINT8CLAMPEDARRAY)
Definition at line 134 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_CMASK_UNUSED
#define DUK_HOBJECT_CMASK_UNUSED (1UL << DUK_HOBJECT_CLASS_UNUSED)
Definition at line 111 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_CLEAR_FLAG_BITS
#define DUK_HOBJECT_E_CLEAR_FLAG_BITS (heap, h, i, mask)
Value:
        do { \
        DUK_HOBJECT_E_GET_FLAGS_BASE((heap), (h))[(i)] &= ~(mask); \
    } while (0)
Definition at line 514 of file duktape-1.8.0/src-separate/duk_hobject.h.
    } while (0)
#define DUK_HOBJECT_E_CLEAR_FLAG_BITS(heap,h,i,mask)  do { \
DUK_HOBJECT_E_GET_FLAGS
#define DUK_HOBJECT_E_GET_FLAGS (heap, h, i) (DUK_HOBJECT_E_GET_FLAGS_BASE((heap), (h))[(i)])
Definition at line 476 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_FLAGS_PTR
#define DUK_HOBJECT_E_GET_FLAGS_PTR (heap, h, i) (&DUK_HOBJECT_E_GET_FLAGS_BASE((heap), (h))[(i)])
Definition at line 477 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_KEY
#define DUK_HOBJECT_E_GET_KEY (heap, h, i) (DUK_HOBJECT_E_GET_KEY_BASE((heap), (h))[(i)])
Definition at line 466 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_KEY_PTR
#define DUK_HOBJECT_E_GET_KEY_PTR (heap, h, i) (&DUK_HOBJECT_E_GET_KEY_BASE((heap), (h))[(i)])
Definition at line 467 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_VALUE
#define DUK_HOBJECT_E_GET_VALUE (heap, h, i) (DUK_HOBJECT_E_GET_VALUE_BASE((heap), (h))[(i)])
Definition at line 468 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_VALUE_GETTER
#define DUK_HOBJECT_E_GET_VALUE_GETTER (heap, h, i) (DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.get)
Definition at line 472 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_VALUE_GETTER_PTR
#define DUK_HOBJECT_E_GET_VALUE_GETTER_PTR (heap, h, i) (&DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.get)
Definition at line 473 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_VALUE_PTR
#define DUK_HOBJECT_E_GET_VALUE_PTR (heap, h, i) (&DUK_HOBJECT_E_GET_VALUE_BASE((heap), (h))[(i)])
Definition at line 469 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_VALUE_SETTER
#define DUK_HOBJECT_E_GET_VALUE_SETTER (heap, h, i) (DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.set)
Definition at line 474 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_VALUE_SETTER_PTR
#define DUK_HOBJECT_E_GET_VALUE_SETTER_PTR (heap, h, i) (&DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.set)
Definition at line 475 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_VALUE_TVAL
#define DUK_HOBJECT_E_GET_VALUE_TVAL (heap, h, i) (DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).v)
Definition at line 470 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_GET_VALUE_TVAL_PTR
#define DUK_HOBJECT_E_GET_VALUE_TVAL_PTR (heap, h, i) (&DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).v)
Definition at line 471 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_MIN_GROW_ADD
#define DUK_HOBJECT_E_MIN_GROW_ADD 16
Definition at line 664 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_MIN_GROW_DIVISOR
#define DUK_HOBJECT_E_MIN_GROW_DIVISOR 8 /* 2^3 -> 1/8 = 12.5% min growth */
Definition at line 665 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SET_FLAG_BITS
#define DUK_HOBJECT_E_SET_FLAG_BITS (heap, h, i, mask)
Value:
        do { \
        DUK_HOBJECT_E_GET_FLAGS_BASE((heap), (h))[(i)] |= (mask); \
    } while (0)
Definition at line 510 of file duktape-1.8.0/src-separate/duk_hobject.h.
    } while (0)
#define DUK_HOBJECT_E_SET_FLAG_BITS(heap,h,i,mask)  do { \
DUK_HOBJECT_E_SET_FLAGS
#define DUK_HOBJECT_E_SET_FLAGS (heap, h, i, f)
Value:
        do { \
        DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) = (duk_uint8_t) (f); \
    } while (0)
Definition at line 498 of file duktape-1.8.0/src-separate/duk_hobject.h.
        DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.set = (v); \
    } while (0)
#define DUK_HOBJECT_E_SET_FLAGS(heap,h,i,f)  do { \
DUK_HOBJECT_E_SET_KEY
#define DUK_HOBJECT_E_SET_KEY (heap, h, i, k)
Value:
        do { \
        DUK_HOBJECT_E_GET_KEY((heap), (h), (i)) = (k); \
    } while (0)
Definition at line 483 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_H_GET_INDEX_PTR(heap,h,i)        (&DUK_HOBJECT_H_GET_BASE((heap), (h))[(i)])
#define DUK_HOBJECT_E_SET_KEY(heap,h,i,k)  do { \
DUK_HOBJECT_E_SET_VALUE
#define DUK_HOBJECT_E_SET_VALUE (heap, h, i, v)
Value:
        do { \
        DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)) = (v); \
    } while (0)
Definition at line 486 of file duktape-1.8.0/src-separate/duk_hobject.h.
        DUK_HOBJECT_E_GET_KEY((heap), (h), (i)) = (k); \
    } while (0)
#define DUK_HOBJECT_E_SET_VALUE(heap,h,i,v)  do { \
DUK_HOBJECT_E_SET_VALUE_GETTER
#define DUK_HOBJECT_E_SET_VALUE_GETTER (heap, h, i, v)
Value:
        do { \
        DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.get = (v); \
    } while (0)
Definition at line 492 of file duktape-1.8.0/src-separate/duk_hobject.h.
        DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).v = (v); \
    } while (0)
#define DUK_HOBJECT_E_SET_VALUE_GETTER(heap,h,i,v)  do { \
DUK_HOBJECT_E_SET_VALUE_SETTER
#define DUK_HOBJECT_E_SET_VALUE_SETTER (heap, h, i, v)
Value:
        do { \
        DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.set = (v); \
    } while (0)
Definition at line 495 of file duktape-1.8.0/src-separate/duk_hobject.h.
        DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).a.get = (v); \
    } while (0)
#define DUK_HOBJECT_E_SET_VALUE_SETTER(heap,h,i,v)  do { \
DUK_HOBJECT_E_SET_VALUE_TVAL
#define DUK_HOBJECT_E_SET_VALUE_TVAL (heap, h, i, v)
Value:
        do { \
        DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)).v = (v); \
    } while (0)
Definition at line 489 of file duktape-1.8.0/src-separate/duk_hobject.h.
        DUK_HOBJECT_E_GET_VALUE((heap), (h), (i)) = (v); \
    } while (0)
#define DUK_HOBJECT_E_SET_VALUE_TVAL(heap,h,i,v)  do { \
DUK_HOBJECT_E_SLOT_CLEAR_ACCESSOR
#define DUK_HOBJECT_E_SLOT_CLEAR_ACCESSOR (heap, h, i) DUK_HOBJECT_E_CLEAR_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_ACCESSOR)
Definition at line 531 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_CLEAR_CONFIGURABLE
#define DUK_HOBJECT_E_SLOT_CLEAR_CONFIGURABLE (heap, h, i) DUK_HOBJECT_E_CLEAR_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_CONFIGURABLE)
Definition at line 530 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_CLEAR_ENUMERABLE
#define DUK_HOBJECT_E_SLOT_CLEAR_ENUMERABLE (heap, h, i) DUK_HOBJECT_E_CLEAR_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_ENUMERABLE)
Definition at line 529 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_CLEAR_WRITABLE
#define DUK_HOBJECT_E_SLOT_CLEAR_WRITABLE (heap, h, i) DUK_HOBJECT_E_CLEAR_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_WRITABLE)
Definition at line 528 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_IS_ACCESSOR
#define DUK_HOBJECT_E_SLOT_IS_ACCESSOR (heap, h, i) ((DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) & DUK_PROPDESC_FLAG_ACCESSOR) != 0)
Definition at line 521 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_IS_CONFIGURABLE
#define DUK_HOBJECT_E_SLOT_IS_CONFIGURABLE (heap, h, i) ((DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) & DUK_PROPDESC_FLAG_CONFIGURABLE) != 0)
Definition at line 520 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_IS_ENUMERABLE
#define DUK_HOBJECT_E_SLOT_IS_ENUMERABLE (heap, h, i) ((DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) & DUK_PROPDESC_FLAG_ENUMERABLE) != 0)
Definition at line 519 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_IS_WRITABLE
#define DUK_HOBJECT_E_SLOT_IS_WRITABLE (heap, h, i) ((DUK_HOBJECT_E_GET_FLAGS((heap), (h), (i)) & DUK_PROPDESC_FLAG_WRITABLE) != 0)
Definition at line 518 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_SET_ACCESSOR
#define DUK_HOBJECT_E_SLOT_SET_ACCESSOR (heap, h, i) DUK_HOBJECT_E_SET_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_ACCESSOR)
Definition at line 526 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_SET_CONFIGURABLE
#define DUK_HOBJECT_E_SLOT_SET_CONFIGURABLE (heap, h, i) DUK_HOBJECT_E_SET_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_CONFIGURABLE)
Definition at line 525 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_SET_ENUMERABLE
#define DUK_HOBJECT_E_SLOT_SET_ENUMERABLE (heap, h, i) DUK_HOBJECT_E_SET_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_ENUMERABLE)
Definition at line 524 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_SLOT_SET_WRITABLE
#define DUK_HOBJECT_E_SLOT_SET_WRITABLE (heap, h, i) DUK_HOBJECT_E_SET_FLAG_BITS((heap), (h), (i),DUK_PROPDESC_FLAG_WRITABLE)
Definition at line 523 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_E_USE_HASH_LIMIT
#define DUK_HOBJECT_E_USE_HASH_LIMIT 32
Definition at line 640 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_EXOTIC_BEHAVIOR_FLAGS
#define DUK_HOBJECT_EXOTIC_BEHAVIOR_FLAGS
Value:
                                                (DUK_HOBJECT_FLAG_EXOTIC_ARRAY | \
                                                DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS | \
                                                DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ | \
                                                DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC | \
                                                DUK_HOBJECT_FLAG_BUFFEROBJECT | \
                                                DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ)
Definition at line 180 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_EXOTIC_BEHAVIOR_FLAGS      (DUK_HOBJECT_FLAG_EXOTIC_ARRAY | \
                                                DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS | \
                                                DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ | \
                                                DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC | \
                                                DUK_HOBJECT_FLAG_BUFFEROBJECT | \
                                                DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ)
DUK_HOBJECT_FLAG_ARRAY_PART
#define DUK_HOBJECT_FLAG_ARRAY_PART DUK_HEAPHDR_USER_FLAG(8) /* object has an array part (a_size may still be 0) */
Definition at line 45 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_BOUND
#define DUK_HOBJECT_FLAG_BOUND DUK_HEAPHDR_USER_FLAG(2) /* object established using Function.prototype.bind() */
Definition at line 40 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_BUFFEROBJECT
#define DUK_HOBJECT_FLAG_BUFFEROBJECT DUK_HEAPHDR_USER_FLAG(6) /* object is a buffer object (duk_hbufferobject) (always exotic) */
Definition at line 43 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_CLASS_BASE
#define DUK_HOBJECT_FLAG_CLASS_BASE DUK_HEAPHDR_USER_FLAG_NUMBER(20)
Definition at line 58 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_CLASS_BITS
#define DUK_HOBJECT_FLAG_CLASS_BITS 5
Definition at line 59 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_COMPILEDFUNCTION
#define DUK_HOBJECT_FLAG_COMPILEDFUNCTION DUK_HEAPHDR_USER_FLAG(4) /* object is a compiled function (duk_hcompiledfunction) */
Definition at line 41 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_CONSTRUCTABLE
#define DUK_HOBJECT_FLAG_CONSTRUCTABLE DUK_HEAPHDR_USER_FLAG(1) /* object is constructable */
Definition at line 39 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_CREATEARGS
#define DUK_HOBJECT_FLAG_CREATEARGS DUK_HEAPHDR_USER_FLAG(13) /* function: create an arguments object on function call */
Definition at line 50 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_ENVRECCLOSED
#define DUK_HOBJECT_FLAG_ENVRECCLOSED DUK_HEAPHDR_USER_FLAG(14) /* envrec: (declarative) record is closed */
Definition at line 51 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS
#define DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS DUK_HEAPHDR_USER_FLAG(17) /* 'Arguments' object and has arguments exotic behavior (non-strict callee) */
Definition at line 54 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_EXOTIC_ARRAY
#define DUK_HOBJECT_FLAG_EXOTIC_ARRAY DUK_HEAPHDR_USER_FLAG(15) /* 'Array' object, array length and index exotic behavior */
Definition at line 52 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC
#define DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC DUK_HEAPHDR_USER_FLAG(18) /* Duktape/C (nativefunction) object, exotic 'length' */
Definition at line 55 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ
#define DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ DUK_HEAPHDR_USER_FLAG(19) /* 'Proxy' object */
Definition at line 56 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ
#define DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ DUK_HEAPHDR_USER_FLAG(16) /* 'String' object, array index exotic behavior */
Definition at line 53 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_EXTENSIBLE
#define DUK_HOBJECT_FLAG_EXTENSIBLE DUK_HEAPHDR_USER_FLAG(0) /* object is extensible */
Definition at line 38 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_NAMEBINDING
#define DUK_HOBJECT_FLAG_NAMEBINDING DUK_HEAPHDR_USER_FLAG(12) /* function: create binding for func name (function templates only, used for named function expressions) */
Definition at line 49 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_NATIVEFUNCTION
#define DUK_HOBJECT_FLAG_NATIVEFUNCTION DUK_HEAPHDR_USER_FLAG(5) /* object is a native function (duk_hnativefunction) */
Definition at line 42 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_NEWENV
#define DUK_HOBJECT_FLAG_NEWENV DUK_HEAPHDR_USER_FLAG(11) /* function: create new environment when called (see duk_hcompiledfunction) */
Definition at line 48 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_NOTAIL
#define DUK_HOBJECT_FLAG_NOTAIL DUK_HEAPHDR_USER_FLAG(10) /* function: function must not be tail called */
Definition at line 47 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_STRICT
#define DUK_HOBJECT_FLAG_STRICT DUK_HEAPHDR_USER_FLAG(9) /* function: function object is strict */
Definition at line 46 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_FLAG_THREAD
#define DUK_HOBJECT_FLAG_THREAD DUK_HEAPHDR_USER_FLAG(7) /* object is a thread (duk_hthread) */
Definition at line 44 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_GET_ASIZE
#define DUK_HOBJECT_GET_ASIZE (h) ((h)->a_size)
Definition at line 566 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_GET_CLASS_MASK
#define DUK_HOBJECT_GET_CLASS_MASK (h) (1UL << DUK_HEAPHDR_GET_FLAG_RANGE(&(h)->hdr, DUK_HOBJECT_FLAG_CLASS_BASE, DUK_HOBJECT_FLAG_CLASS_BITS))
Definition at line 66 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_GET_CLASS_MASK(h)          \
    (1UL << DUK_HEAPHDR_GET_FLAG_RANGE(&(h)->hdr, DUK_HOBJECT_FLAG_CLASS_BASE, DUK_HOBJECT_FLAG_CLASS_BITS))
DUK_HOBJECT_GET_CLASS_NUMBER
#define DUK_HOBJECT_GET_CLASS_NUMBER (h) DUK_HEAPHDR_GET_FLAG_RANGE(&(h)->hdr, DUK_HOBJECT_FLAG_CLASS_BASE, DUK_HOBJECT_FLAG_CLASS_BITS)
Definition at line 61 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_GET_CLASS_NUMBER(h)        \
    DUK_HEAPHDR_GET_FLAG_RANGE(&(h)->hdr, DUK_HOBJECT_FLAG_CLASS_BASE, DUK_HOBJECT_FLAG_CLASS_BITS)
DUK_HOBJECT_GET_CLASS_STRING
#define DUK_HOBJECT_GET_CLASS_STRING (heap, h)
Value:
    DUK_HEAP_GET_STRING( \
        (heap), \
        DUK_HOBJECT_CLASS_NUMBER_TO_STRIDX(DUK_HOBJECT_GET_CLASS_NUMBER((h))) \
    )
Definition at line 596 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_CLASS_NUMBER_TO_STRIDX(n)  duk_class_number_to_stridx[(n)]
#define DUK_HOBJECT_GET_CLASS_STRING(heap,h)          \
    DUK_HEAP_GET_STRING( \
        (heap), \
DUK_HOBJECT_GET_ENEXT
#define DUK_HOBJECT_GET_ENEXT (h) ((h)->e_next)
Definition at line 563 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_GET_ESIZE
#define DUK_HOBJECT_GET_ESIZE (h) ((h)->e_size)
Definition at line 561 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_GET_HSIZE
#define DUK_HOBJECT_GET_HSIZE (h) 0
Definition at line 572 of file duktape-1.8.0/src-separate/duk_hobject.h.
duk_hobject_get_internal_value_tval_ptr
#define duk_hobject_get_internal_value_tval_ptr (heap, obj) duk_hobject_find_existing_entry_tval_ptr((heap), (obj), DUK_HEAP_STRING_INT_VALUE((heap)))
Definition at line 847 of file duktape-1.8.0/src-separate/duk_hobject.h.
 * slot for internal value; this call can then access it directly.
 */
DUK_HOBJECT_GET_PROPS
#define DUK_HOBJECT_GET_PROPS (heap, h) ((h)->props)
Definition at line 317 of file duktape-1.8.0/src-separate/duk_hobject.h.
    } while (0)
#else
DUK_HOBJECT_GET_PROTOTYPE
#define DUK_HOBJECT_GET_PROTOTYPE (heap, h) ((h)->prototype)
Definition at line 613 of file duktape-1.8.0/src-separate/duk_hobject.h.
    } while (0)
#else
DUK_HOBJECT_H_GET_INDEX
#define DUK_HOBJECT_H_GET_INDEX (heap, h, i) (DUK_HOBJECT_H_GET_BASE((heap), (h))[(i)])
Definition at line 480 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_H_GET_INDEX_PTR
#define DUK_HOBJECT_H_GET_INDEX_PTR (heap, h, i) (&DUK_HOBJECT_H_GET_BASE((heap), (h))[(i)])
Definition at line 481 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_H_SET_INDEX
#define DUK_HOBJECT_H_SET_INDEX (heap, h, i, v)
Value:
        do { \
        DUK_HOBJECT_H_GET_INDEX((heap), (h), (i)) = (v); \
    } while (0)
Definition at line 506 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_A_SET_VALUE_TVAL(heap,h,i,v) \
    DUK_HOBJECT_A_SET_VALUE((heap), (h), (i), (v))  /* alias for above */
#define DUK_HOBJECT_H_SET_INDEX(heap,h,i,v)  do { \
DUK_HOBJECT_H_SIZE_DIVISOR
#define DUK_HOBJECT_H_SIZE_DIVISOR 4 /* hash size approx. 1.25 times entries size */
Definition at line 643 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_ARRAY_PART
#define DUK_HOBJECT_HAS_ARRAY_PART (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ARRAY_PART)
Definition at line 196 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_BOUND
#define DUK_HOBJECT_HAS_BOUND (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BOUND)
Definition at line 191 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_BUFFEROBJECT
#define DUK_HOBJECT_HAS_BUFFEROBJECT (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BUFFEROBJECT)
Definition at line 194 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_COMPILEDFUNCTION
#define DUK_HOBJECT_HAS_COMPILEDFUNCTION (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_COMPILEDFUNCTION)
Definition at line 192 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_CONSTRUCTABLE
#define DUK_HOBJECT_HAS_CONSTRUCTABLE (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CONSTRUCTABLE)
Definition at line 190 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_CREATEARGS
#define DUK_HOBJECT_HAS_CREATEARGS (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CREATEARGS)
Definition at line 201 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_ENVRECCLOSED
#define DUK_HOBJECT_HAS_ENVRECCLOSED (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ENVRECCLOSED)
Definition at line 202 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS
#define DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS)
Definition at line 205 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_EXOTIC_ARRAY
#define DUK_HOBJECT_HAS_EXOTIC_ARRAY (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARRAY)
Definition at line 203 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_EXOTIC_BEHAVIOR
#define DUK_HOBJECT_HAS_EXOTIC_BEHAVIOR (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_EXOTIC_BEHAVIOR_FLAGS)
Definition at line 187 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_EXOTIC_DUKFUNC
#define DUK_HOBJECT_HAS_EXOTIC_DUKFUNC (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC)
Definition at line 206 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ
#define DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ)
Definition at line 207 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_EXOTIC_STRINGOBJ
#define DUK_HOBJECT_HAS_EXOTIC_STRINGOBJ (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ)
Definition at line 204 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_EXTENSIBLE
#define DUK_HOBJECT_HAS_EXTENSIBLE (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXTENSIBLE)
Definition at line 189 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_NAMEBINDING
#define DUK_HOBJECT_HAS_NAMEBINDING (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NAMEBINDING)
Definition at line 200 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_NATIVEFUNCTION
#define DUK_HOBJECT_HAS_NATIVEFUNCTION (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NATIVEFUNCTION)
Definition at line 193 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_NEWENV
#define DUK_HOBJECT_HAS_NEWENV (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NEWENV)
Definition at line 199 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_NOTAIL
#define DUK_HOBJECT_HAS_NOTAIL (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NOTAIL)
Definition at line 198 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_STRICT
#define DUK_HOBJECT_HAS_STRICT (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_STRICT)
Definition at line 197 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HAS_THREAD
#define DUK_HOBJECT_HAS_THREAD (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_THREAD)
Definition at line 195 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HASH_INITIAL
#define DUK_HOBJECT_HASH_INITIAL (hash, h_size) ((hash) % (h_size))
Definition at line 672 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HASH_PROBE_STEP
#define DUK_HOBJECT_HASH_PROBE_STEP (hash) DUK_UTIL_GET_HASH_PROBE_STEP((hash))
Definition at line 673 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HASHIDX_DELETED
#define DUK_HOBJECT_HASHIDX_DELETED 0xfffffffeUL
Definition at line 539 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_HASHIDX_UNUSED
#define DUK_HOBJECT_HASHIDX_UNUSED 0xffffffffUL
Definition at line 538 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_IS_ARRAY
#define DUK_HOBJECT_IS_ARRAY (h) (DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_ARRAY)
Definition at line 159 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_IS_BUFFEROBJECT
#define DUK_HOBJECT_IS_BUFFEROBJECT (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BUFFEROBJECT)
Definition at line 162 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_IS_CALLABLE
#define DUK_HOBJECT_IS_CALLABLE (h)
Value:
                                                        DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, \
                                                        DUK_HOBJECT_FLAG_BOUND | \
                                                        DUK_HOBJECT_FLAG_COMPILEDFUNCTION | \
                                                        DUK_HOBJECT_FLAG_NATIVEFUNCTION)
Definition at line 174 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_IS_CALLABLE(h)             DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, \
                                                        DUK_HOBJECT_FLAG_BOUND | \
                                                        DUK_HOBJECT_FLAG_COMPILEDFUNCTION | \
                                                        DUK_HOBJECT_FLAG_NATIVEFUNCTION)
DUK_HOBJECT_IS_COMPILEDFUNCTION
#define DUK_HOBJECT_IS_COMPILEDFUNCTION (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_COMPILEDFUNCTION)
Definition at line 160 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_IS_DECENV
#define DUK_HOBJECT_IS_DECENV (h) (DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_DECENV)
Definition at line 157 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_IS_ENV
#define DUK_HOBJECT_IS_ENV (h) (DUK_HOBJECT_IS_OBJENV((h)) || DUK_HOBJECT_IS_DECENV((h)))
Definition at line 158 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_IS_FUNCTION
#define DUK_HOBJECT_IS_FUNCTION (h)
Value:
                                                        DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, \
                                                        DUK_HOBJECT_FLAG_BOUND | \
                                                        DUK_HOBJECT_FLAG_COMPILEDFUNCTION | \
                                                        DUK_HOBJECT_FLAG_NATIVEFUNCTION)
Definition at line 169 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_IS_FUNCTION(h)             DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, \
                                                        DUK_HOBJECT_FLAG_BOUND | \
                                                        DUK_HOBJECT_FLAG_COMPILEDFUNCTION | \
                                                        DUK_HOBJECT_FLAG_NATIVEFUNCTION)
DUK_HOBJECT_IS_NATIVEFUNCTION
#define DUK_HOBJECT_IS_NATIVEFUNCTION (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NATIVEFUNCTION)
Definition at line 161 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_IS_NONBOUND_FUNCTION
#define DUK_HOBJECT_IS_NONBOUND_FUNCTION (h)
Value:
                                                        DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, \
                                                        DUK_HOBJECT_FLAG_COMPILEDFUNCTION | \
                                                        DUK_HOBJECT_FLAG_NATIVEFUNCTION)
Definition at line 165 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_IS_NONBOUND_FUNCTION(h)    DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, \
                                                        DUK_HOBJECT_FLAG_COMPILEDFUNCTION | \
                                                        DUK_HOBJECT_FLAG_NATIVEFUNCTION)
DUK_HOBJECT_IS_OBJENV
#define DUK_HOBJECT_IS_OBJENV (h) (DUK_HOBJECT_GET_CLASS_NUMBER((h)) == DUK_HOBJECT_CLASS_OBJENV)
Definition at line 156 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_IS_THREAD
#define DUK_HOBJECT_IS_THREAD (h) DUK_HEAPHDR_CHECK_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_THREAD)
Definition at line 163 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_MAX_PROPERTIES
#define DUK_HOBJECT_MAX_PROPERTIES 0x7fffffffUL /* 2**31-1 ~= 2G properties */
Definition at line 636 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_P_ALLOC_SIZE
#define DUK_HOBJECT_P_ALLOC_SIZE (h) DUK_HOBJECT_P_COMPUTE_SIZE(DUK_HOBJECT_GET_ESIZE((h)), DUK_HOBJECT_GET_ASIZE((h)), DUK_HOBJECT_GET_HSIZE((h)))
Definition at line 463 of file duktape-1.8.0/src-separate/duk_hobject.h.
#endif  /* hobject property layout */
DUK_HOBJECT_POSTINC_ENEXT
#define DUK_HOBJECT_POSTINC_ENEXT (h) ((h)->e_next++)
Definition at line 565 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_PROTOTYPE_CHAIN_SANITY
#define DUK_HOBJECT_PROTOTYPE_CHAIN_SANITY 10000L
Definition at line 584 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_ARRAY_PART
#define DUK_HOBJECT_SET_ARRAY_PART (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ARRAY_PART)
Definition at line 216 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_ASIZE
#define DUK_HOBJECT_SET_ASIZE (h, v) do { (h)->a_size = (v); } while (0)
Definition at line 567 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_BOUND
#define DUK_HOBJECT_SET_BOUND (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BOUND)
Definition at line 211 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_BUFFEROBJECT
#define DUK_HOBJECT_SET_BUFFEROBJECT (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_BUFFEROBJECT)
Definition at line 214 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_CLASS_NUMBER
#define DUK_HOBJECT_SET_CLASS_NUMBER (h, v) DUK_HEAPHDR_SET_FLAG_RANGE(&(h)->hdr, DUK_HOBJECT_FLAG_CLASS_BASE, DUK_HOBJECT_FLAG_CLASS_BITS, (v))
Definition at line 63 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_SET_CLASS_NUMBER(h,v)      \
    DUK_HEAPHDR_SET_FLAG_RANGE(&(h)->hdr, DUK_HOBJECT_FLAG_CLASS_BASE, DUK_HOBJECT_FLAG_CLASS_BITS, (v))
DUK_HOBJECT_SET_COMPILEDFUNCTION
#define DUK_HOBJECT_SET_COMPILEDFUNCTION (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_COMPILEDFUNCTION)
Definition at line 212 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_CONSTRUCTABLE
#define DUK_HOBJECT_SET_CONSTRUCTABLE (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CONSTRUCTABLE)
Definition at line 210 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_CREATEARGS
#define DUK_HOBJECT_SET_CREATEARGS (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_CREATEARGS)
Definition at line 221 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_ENEXT
#define DUK_HOBJECT_SET_ENEXT (h, v) do { (h)->e_next = (v); } while (0)
Definition at line 564 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_ENVRECCLOSED
#define DUK_HOBJECT_SET_ENVRECCLOSED (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_ENVRECCLOSED)
Definition at line 222 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_ESIZE
#define DUK_HOBJECT_SET_ESIZE (h, v) do { (h)->e_size = (v); } while (0)
Definition at line 562 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_EXOTIC_ARGUMENTS
#define DUK_HOBJECT_SET_EXOTIC_ARGUMENTS (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARGUMENTS)
Definition at line 225 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_EXOTIC_ARRAY
#define DUK_HOBJECT_SET_EXOTIC_ARRAY (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_ARRAY)
Definition at line 223 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_EXOTIC_DUKFUNC
#define DUK_HOBJECT_SET_EXOTIC_DUKFUNC (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_DUKFUNC)
Definition at line 226 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_EXOTIC_PROXYOBJ
#define DUK_HOBJECT_SET_EXOTIC_PROXYOBJ (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_PROXYOBJ)
Definition at line 227 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_EXOTIC_STRINGOBJ
#define DUK_HOBJECT_SET_EXOTIC_STRINGOBJ (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXOTIC_STRINGOBJ)
Definition at line 224 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_EXTENSIBLE
#define DUK_HOBJECT_SET_EXTENSIBLE (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_EXTENSIBLE)
Definition at line 209 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_HSIZE
#define DUK_HOBJECT_SET_HSIZE (h, v) do { DUK_ASSERT((v) == 0); } while (0)
Definition at line 573 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_NAMEBINDING
#define DUK_HOBJECT_SET_NAMEBINDING (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NAMEBINDING)
Definition at line 220 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_NATIVEFUNCTION
#define DUK_HOBJECT_SET_NATIVEFUNCTION (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NATIVEFUNCTION)
Definition at line 213 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_NEWENV
#define DUK_HOBJECT_SET_NEWENV (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NEWENV)
Definition at line 219 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_NOTAIL
#define DUK_HOBJECT_SET_NOTAIL (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_NOTAIL)
Definition at line 218 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_PROPS
#define DUK_HOBJECT_SET_PROPS (heap, h, x)
Value:
        do { \
        (h)->props = (duk_uint8_t *) (x); \
    } while (0)
Definition at line 319 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_GET_PROPS(heap,h) \
    ((h)->props)
#define DUK_HOBJECT_SET_PROPS(heap,h,x) do { \
DUK_HOBJECT_SET_PROTOTYPE
#define DUK_HOBJECT_SET_PROTOTYPE (heap, h, x)
Value:
        do { \
        (h)->prototype = (x); \
    } while (0)
Definition at line 615 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_HOBJECT_GET_PROTOTYPE(heap,h) \
    ((h)->prototype)
#define DUK_HOBJECT_SET_PROTOTYPE(heap,h,x) do { \
DUK_HOBJECT_SET_PROTOTYPE_UPDREF
#define DUK_HOBJECT_SET_PROTOTYPE_UPDREF (thr, h, p) duk_hobject_set_prototype_updref((thr), (h), (p))
Definition at line 621 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_STRICT
#define DUK_HOBJECT_SET_STRICT (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_STRICT)
Definition at line 217 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_HOBJECT_SET_THREAD
#define DUK_HOBJECT_SET_THREAD (h) DUK_HEAPHDR_SET_FLAG_BITS(&(h)->hdr, DUK_HOBJECT_FLAG_THREAD)
Definition at line 215 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PC2LINE_MAX_DIFF_LENGTH
#define DUK_PC2LINE_MAX_DIFF_LENGTH (((DUK_PC2LINE_SKIP - 1) * 35 + 7) / 8)
Definition at line 682 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PC2LINE_SKIP
#define DUK_PC2LINE_SKIP 64
Definition at line 679 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAG_ACCESSOR
#define DUK_PROPDESC_FLAG_ACCESSOR (1 << 3) /* accessor */
Definition at line 253 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAG_CONFIGURABLE
#define DUK_PROPDESC_FLAG_CONFIGURABLE (1 << 2) /* E5 Section 8.6.1 */
Definition at line 252 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAG_ENUMERABLE
#define DUK_PROPDESC_FLAG_ENUMERABLE (1 << 1) /* E5 Section 8.6.1 */
Definition at line 251 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAG_NO_OVERWRITE
#define DUK_PROPDESC_FLAG_NO_OVERWRITE (1 << 4) /* internal define property: skip write silently if exists */
Definition at line 263 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAG_VIRTUAL
#define DUK_PROPDESC_FLAG_VIRTUAL
Value:
                                                             (1 << 4)    /* property is virtual: used in duk_propdesc, never stored
                                                             * (used by e.g. buffer virtual properties)
                                                             */
Definition at line 254 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAG_WRITABLE
#define DUK_PROPDESC_FLAG_WRITABLE (1 << 0) /* E5 Section 8.6.1 */
Definition at line 250 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAGS_C
#define DUK_PROPDESC_FLAGS_C (DUK_PROPDESC_FLAG_CONFIGURABLE)
Definition at line 269 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAGS_E
#define DUK_PROPDESC_FLAGS_E (DUK_PROPDESC_FLAG_ENUMERABLE)
Definition at line 268 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAGS_EC
#define DUK_PROPDESC_FLAGS_EC (DUK_PROPDESC_FLAG_ENUMERABLE | DUK_PROPDESC_FLAG_CONFIGURABLE)
Definition at line 272 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAGS_MASK
#define DUK_PROPDESC_FLAGS_MASK
Value:
                                                 (DUK_PROPDESC_FLAG_WRITABLE | \
                                                 DUK_PROPDESC_FLAG_ENUMERABLE | \
                                                 DUK_PROPDESC_FLAG_CONFIGURABLE | \
                                                 DUK_PROPDESC_FLAG_ACCESSOR)
Definition at line 255 of file duktape-1.8.0/src-separate/duk_hobject.h.
                                                             * (used by e.g. buffer virtual properties)
                                                             */
#define DUK_PROPDESC_FLAGS_MASK                 (DUK_PROPDESC_FLAG_WRITABLE | \
                                                 DUK_PROPDESC_FLAG_ENUMERABLE | \
DUK_PROPDESC_FLAGS_NONE
#define DUK_PROPDESC_FLAGS_NONE 0
Definition at line 266 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAGS_W
#define DUK_PROPDESC_FLAGS_W (DUK_PROPDESC_FLAG_WRITABLE)
Definition at line 267 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAGS_WC
#define DUK_PROPDESC_FLAGS_WC (DUK_PROPDESC_FLAG_WRITABLE | DUK_PROPDESC_FLAG_CONFIGURABLE)
Definition at line 271 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAGS_WE
#define DUK_PROPDESC_FLAGS_WE (DUK_PROPDESC_FLAG_WRITABLE | DUK_PROPDESC_FLAG_ENUMERABLE)
Definition at line 270 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_FLAGS_WEC
#define DUK_PROPDESC_FLAGS_WEC
Value:
                                                 (DUK_PROPDESC_FLAG_WRITABLE | \
                                                 DUK_PROPDESC_FLAG_ENUMERABLE | \
                                                 DUK_PROPDESC_FLAG_CONFIGURABLE)
Definition at line 273 of file duktape-1.8.0/src-separate/duk_hobject.h.
#define DUK_PROPDESC_FLAGS_WC                   (DUK_PROPDESC_FLAG_WRITABLE | DUK_PROPDESC_FLAG_CONFIGURABLE)
#define DUK_PROPDESC_FLAGS_EC                   (DUK_PROPDESC_FLAG_ENUMERABLE | DUK_PROPDESC_FLAG_CONFIGURABLE)
#define DUK_PROPDESC_FLAGS_WEC                  (DUK_PROPDESC_FLAG_WRITABLE | \
DUK_PROPDESC_IS_ACCESSOR
#define DUK_PROPDESC_IS_ACCESSOR (p) (((p)->flags & DUK_PROPDESC_FLAG_ACCESSOR) != 0)
Definition at line 536 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_IS_CONFIGURABLE
#define DUK_PROPDESC_IS_CONFIGURABLE (p) (((p)->flags & DUK_PROPDESC_FLAG_CONFIGURABLE) != 0)
Definition at line 535 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_IS_ENUMERABLE
#define DUK_PROPDESC_IS_ENUMERABLE (p) (((p)->flags & DUK_PROPDESC_FLAG_ENUMERABLE) != 0)
Definition at line 534 of file duktape-1.8.0/src-separate/duk_hobject.h.
DUK_PROPDESC_IS_WRITABLE
#define DUK_PROPDESC_IS_WRITABLE (p) (((p)->flags & DUK_PROPDESC_FLAG_WRITABLE) != 0)
Definition at line 533 of file duktape-1.8.0/src-separate/duk_hobject.h.
Function Documentation
duk_hbufferobject_alloc()
DUK_INTERNAL duk_hbufferobject * duk_hbufferobject_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 45950 of file duktape-1.5.2/src-noline/duktape.c.
              {
        return NULL;
    }
    DUK_MEMZERO(res, sizeof(duk_hnativefunction));
    duk__init_object_parts(heap, &res->obj, hobject_flags);
#ifdef DUK_USE_EXPLICIT_NULL_INIT
    res->func = NULL;
#endif
    return res;
}
DUK_INTERNAL duk_hbufferobject *duk_hbufferobject_alloc(duk_heap *heap, duk_uint_t hobject_flags) {
References duk_hbufferobject::buf, duk__init_object_parts(), DUK_ALLOC, DUK_ASSERT_HBUFFEROBJECT_VALID, DUK_MEMZERO, NULL, and duk_hbufferobject::obj.
Referenced by duk_push_bufferobject_raw().
duk_hcompiledfunction_alloc()
DUK_INTERNAL_DECL duk_hcompiledfunction * duk_hcompiledfunction_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 45908 of file duktape-1.5.2/src-noline/duktape.c.
              {
        return NULL;
    }
    DUK_MEMZERO(res, sizeof(duk_hobject));
    duk__init_object_parts(heap, res, hobject_flags);
    return res;
}
DUK_INTERNAL duk_hcompiledfunction *duk_hcompiledfunction_alloc(duk_heap *heap, duk_uint_t hobject_flags) {
    duk_hcompiledfunction *res;
    res = (duk_hcompiledfunction *) DUK_ALLOC(heap, sizeof(duk_hcompiledfunction));
    if (!res) {
        return NULL;
References duk_hcompiledfunction::bytecode, duk_hcompiledfunction::data, duk__init_object_parts(), DUK_ALLOC, DUK_MEMZERO, duk_hcompiledfunction::funcs, NULL, and duk_hcompiledfunction::obj.
Referenced by duk_push_compiledfunction().
duk_hnativefunction_alloc()
DUK_INTERNAL_DECL duk_hnativefunction * duk_hnativefunction_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 45932 of file duktape-1.5.2/src-noline/duktape.c.
References duk__init_object_parts(), DUK_ALLOC, DUK_MEMZERO, duk_hnativefunction::func, NULL, and duk_hnativefunction::obj.
Referenced by duk__push_c_function_raw().
duk_hobject_alloc()
DUK_INTERNAL_DECL duk_hobject * duk_hobject_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 45887 of file duktape-1.5.2/src-noline/duktape.c.
                                                : empty objects consume a minimum
     *  amount of memory.  Further, an initial allocation might fail and cause
     *  'obj' to "leak" (require a mark-and-sweep) since it is not reachable yet.
     */
}
/*
 *  Allocate an duk_hobject.
 *
 *  The allocated object has no allocation for properties; the caller may
 *  want to force a resize if a desired size is known.
 *
 *  The allocated object has zero reference count and is not reachable.
 *  The caller MUST make the object reachable and increase its reference
 *  count before invoking any operation that might require memory allocation.
 */
DUK_INTERNAL duk_hobject *duk_hobject_alloc(duk_heap *heap, duk_uint_t hobject_flags) {
    duk_hobject *res;
References duk__init_object_parts(), DUK_ALLOC, DUK_ASSERT, DUK_HOBJECT_FLAG_COMPILEDFUNCTION, DUK_HOBJECT_FLAG_NATIVEFUNCTION, DUK_HOBJECT_FLAG_THREAD, DUK_MEMZERO, and NULL.
Referenced by duk_heap_alloc(), and duk_push_object_helper().
duk_hobject_compact_props()
DUK_INTERNAL_DECL void duk_hobject_compact_props (duk_hthread * thr, duk_hobject * obj)
Definition at line 48116 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_uint32_t e_size;       /* currently used -> new size */
    duk_uint32_t a_size;       /* currently required */
    duk_uint32_t a_used;       /* actually used */
    duk_uint32_t h_size;
    duk_bool_t abandon_array;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(obj != NULL);
#if defined(DUK_USE_ROM_OBJECTS)
    if (DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) obj)) {
        DUK_DD(DUK_DDPRINT("ignore attempt to compact a rom object"));
        return;
    }
#endif
    e_size = duk__count_used_e_keys(thr, obj);
    duk__compute_a_stats(thr, obj, &a_used, &a_size);
    DUK_DD(DUK_DDPRINT("compacting hobject, used e keys %ld, used a keys %ld, min a size %ld, "
                       "resized array density would be: %ld/%ld = %lf",
                       (long) e_size, (long) a_used, (long) a_size,
                       (long) a_used, (long) a_size,
                       (double) a_used / (double) a_size));
    if (duk__abandon_array_density_check(a_used, a_size)) {
        DUK_DD(DUK_DDPRINT("decided to abandon array during compaction, a_used=%ld, a_size=%ld",
                           (long) a_used, (long) a_size));
        abandon_array = 1;
        e_size += a_used;
        a_size = 0;
    } else {
        DUK_DD(DUK_DDPRINT("decided to keep array during compaction"));
        abandon_array = 0;
References duk__abandon_array_density_check(), duk__compute_a_stats(), duk__count_used_e_keys(), duk__get_default_h_size(), duk__realloc_props(), DUK_ASSERT, DUK_DD, DUK_DDPRINT, DUK_HEAPHDR_HAS_READONLY, DUK_HOBJECT_E_USE_HASH_LIMIT, and NULL.
Referenced by duk__compact_object_list(), duk__protected_compact_object(), duk_bi_object_constructor_prevent_extensions(), duk_bi_object_constructor_seal_freeze_shared(), duk_compact(), duk_hobject_enumerator_create(), and duk_hthread_create_builtin_objects().
duk_hobject_define_accessor_internal()
DUK_INTERNAL_DECL void duk_hobject_define_accessor_internal (duk_hthread * thr, duk_hobject * obj, duk_hstring * key, duk_hobject * getter, duk_hobject * setter, duk_small_uint_t propflags)
Definition at line 51763 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_context *ctx = (duk_context *) thr;
    duk_int_t e_idx;
    duk_int_t h_idx;
    DUK_DDD(DUK_DDDPRINT("define new accessor (internal): thr=%p, obj=%!O, key=%!O, "
                         "getter=%!O, setter=%!O, flags=0x%02lx",
                         (void *) thr, (duk_heaphdr *) obj, (duk_heaphdr *) key,
                         (duk_heaphdr *) getter, (duk_heaphdr *) setter,
                         (unsigned long) propflags));
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT(key != NULL);
    DUK_ASSERT((propflags & ~DUK_PROPDESC_FLAGS_MASK) == 0);
    /* setter and/or getter may be NULL */
    DUK_ASSERT(!DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) obj));
References DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, DUK_DDD, DUK_DDDPRINT, DUK_HEAPHDR_HAS_READONLY, duk_hobject_define_property_internal(), DUK_HOBJECT_E_SET_VALUE_GETTER, DUK_HOBJECT_E_SET_VALUE_SETTER, DUK_HOBJECT_E_SLOT_SET_ACCESSOR, duk_hobject_find_existing_entry(), DUK_HOBJECT_GET_ENEXT, DUK_HOBJECT_INCREF_ALLOWNULL, DUK_PROPDESC_FLAGS_MASK, duk_push_undefined(), duk_hthread::heap, and NULL.
Referenced by duk_hthread_create_builtin_objects(), and duk_xdef_prop_stridx_thrower().
duk_hobject_define_property_helper()
DUK_INTERNAL_DECL void duk_hobject_define_property_helper (duk_context * ctx, duk_uint_t defprop_flags, duk_hobject * obj, duk_hstring * key, duk_idx_t idx_value, duk_hobject * get, duk_hobject * set)
Definition at line 52079 of file duktape-1.5.2/src-noline/duktape.c.
        : Ecmascript compliant [[DefineOwnProperty]](P, Desc, Throw) is not
 *  implemented directly, but Object.defineProperty() serves its purpose.
 *  We don't need the [[DefineOwnProperty]] internally and we don't have a
 *  property descriptor with 'missing values' so it's easier to avoid it
 *  entirely.
 *
 *  Note: this is only called for actual objects, not primitive values.
 *  This must support virtual properties for full objects (e.g. Strings)
 *  but not for plain values (e.g. strings).  Lightfuncs, even though
 *  primitive in a sense, are treated like objects and accepted as target
 *  values.
 */
/* XXX: this is a major target for size optimization */
DUK_INTERNAL
void duk_hobject_define_property_helper(duk_context *ctx,
                                        duk_uint_t defprop_flags,
                                        duk_hobject *obj,
                                        duk_hstring *key,
                                        duk_idx_t idx_value,
                                        duk_hobject *get,
                                        duk_hobject *set) {
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_uint32_t arr_idx;
    duk_tval tv;
    duk_bool_t has_enumerable;
    duk_bool_t has_configurable;
    duk_bool_t has_writable;
    duk_bool_t has_value;
    duk_bool_t has_get;
    duk_bool_t has_set;
    duk_bool_t is_enumerable;
    duk_bool_t is_configurable;
    duk_bool_t is_writable;
    duk_bool_t throw_flag;
    duk_bool_t force_flag;
    duk_small_uint_t new_flags;
    duk_propdesc curr;
    duk_uint32_t arridx_new_array_length;  /* != 0 => post-update for array 'length' (used when key is an array index) */
    duk_uint32_t arrlen_old_len;
    duk_uint32_t arrlen_new_len;
    duk_bool_t pending_write_protect;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(ctx != NULL);
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT(key != NULL);
    /* idx_value may be < 0 (no value), set and get may be NULL */
    DUK_ASSERT_VALSTACK_SPACE(thr, DUK__VALSTACK_SPACE);
    /* All the flags fit in 16 bits, so will fit into duk_bool_t. */
    has_writable = (defprop_flags & DUK_DEFPROP_HAVE_WRITABLE);
    has_enumerable = (defprop_flags & DUK_DEFPROP_HAVE_ENUMERABLE);
    has_configurable = (defprop_flags & DUK_DEFPROP_HAVE_CONFIGURABLE);
    has_value = (defprop_flags & DUK_DEFPROP_HAVE_VALUE);
    has_get = (defprop_flags & DUK_DEFPROP_HAVE_GETTER);
    has_set = (defprop_flags & DUK_DEFPROP_HAVE_SETTER);
    is_writable = (defprop_flags & DUK_DEFPROP_WRITABLE);
    is_enumerable = (defprop_flags & DUK_DEFPROP_ENUMERABLE);
    is_configurable = (defprop_flags & DUK_DEFPROP_CONFIGURABLE);
    throw_flag = 1;   /* Object.defineProperty() calls [[DefineOwnProperty]] with Throw=true */
    force_flag = (defprop_flags & DUK_DEFPROP_FORCE);
    arr_idx = DUK_HSTRING_GET_ARRIDX_SLOW(key);
    arridx_new_array_length = 0;
    pending_write_protect = 0;
    arrlen_old_len = 0;
    arrlen_new_len = 0;
    DUK_DDD(DUK_DDDPRINT("has_enumerable=%ld is_enumerable=%ld "
                         "has_configurable=%ld is_configurable=%ld "
                         "has_writable=%ld is_writable=%ld "
                         "has_value=%ld value=%!T "
                         "has_get=%ld get=%p=%!O "
                         "has_set=%ld set=%p=%!O "
                         "arr_idx=%ld",
                         (long) has_enumerable, (long) is_enumerable,
                         (long) has_configurable, (long) is_configurable,
                         (long) has_writable, (long) is_writable,
                         (long) has_value, (duk_tval *) (idx_value >= 0 ? duk_get_tval(ctx, idx_value) : NULL),
                         (long) has_get, (void *) get, (duk_heaphdr *) get,
                         (long) has_set, (void *) set, (duk_heaphdr *) set,
                         (long) arr_idx));
    /*
     *  Array exotic behaviors can be implemented at this point.  The local variables
     *  are essentially a 'value copy' of the input descriptor (Desc), which is modified
     *  by the Array [[DefineOwnProperty]] (E5 Section 15.4.5.1).
     */
    if (!DUK_HOBJECT_HAS_EXOTIC_ARRAY(obj)) {
        goto skip_array_exotic;
    }
    if (key == DUK_HTHREAD_STRING_LENGTH(thr)) {
        /* E5 Section 15.4.5.1, step 3, steps a - i are implemented here, j - n at the end */
        if (!has_value) {
            DUK_DDD(DUK_DDDPRINT("exotic array behavior for 'length', but no value in descriptor -> normal behavior"));
            goto skip_array_exotic;
        }
        DUK_DDD(DUK_DDDPRINT("exotic array behavior for 'length', value present in descriptor -> exotic behavior"));
        /*
         *  Get old and new length
         */
        /* Note: reuse 'curr' as a temp propdesc */
        arrlen_old_len = duk__get_old_array_length(thr, obj, &curr);
        duk_dup(ctx, idx_value);
        arrlen_new_len = duk__to_new_array_length_checked(thr);
        duk_push_u32(ctx, arrlen_new_len);
        duk_replace(ctx, idx_value);  /* step 3.e: replace 'Desc.[[Value]]' */
        DUK_DDD(DUK_DDDPRINT("old_len=%ld, new_len=%ld", (long) arrlen_old_len, (long) arrlen_new_len));
        if (arrlen_new_len >= arrlen_old_len) {
            /* standard behavior, step 3.f.i */
            DUK_DDD(DUK_DDDPRINT("new length is same or higher as previous => standard behavior"));
            goto skip_array_exotic;
        }
        DUK_DDD(DUK_DDDPRINT("new length is smaller than previous => exotic post behavior"));
        /* XXX: consolidated algorithm step 15.f -> redundant? */
        if (!(curr.flags & DUK_PROPDESC_FLAG_WRITABLE) && !force_flag) {
            /* Note: 'curr' refers to 'length' propdesc */
            goto fail_not_writable_array_length;
        }
        /* steps 3.h and 3.i */
        if (has_writable && !is_writable) {
            DUK_DDD(DUK_DDDPRINT("desc writable is false, force it back to true, and flag pending write protect"));
            is_writable = 1;
            pending_write_protect = 1;
        }
        /* remaining actual steps are carried out if standard DefineOwnProperty succeeds */
    } else if (arr_idx != DUK__NO_ARRAY_INDEX) {
        /* XXX: any chance of unifying this with the 'length' key handling? */
        /* E5 Section 15.4.5.1, step 4 */
        duk_uint32_t old_len;
        /* Note: use 'curr' as a temp propdesc */
        old_len = duk__get_old_array_length(thr, obj, &curr);
        if (arr_idx >= old_len) {
            DUK_DDD(DUK_DDDPRINT("defineProperty requires array length update "
                                 "(arr_idx=%ld, old_len=%ld)",
                                 (long) arr_idx, (long) old_len));
            if (!(curr.flags & DUK_PROPDESC_FLAG_WRITABLE)) {
                /* Note: 'curr' refers to 'length' propdesc */
                goto fail_not_writable_array_length;
            }
            /* actual update happens once write has been completed without
             * error below.
             */
            DUK_ASSERT(arr_idx != 0xffffffffUL);
            arridx_new_array_length = arr_idx + 1;
        } else {
            DUK_DDD(DUK_DDDPRINT("defineProperty does not require length update "
                                 "(arr_idx=%ld, old_len=%ld) -> standard behavior",
                                 (long) arr_idx, (long) old_len));
        }
    }
 skip_array_exotic:
    /* XXX: There is currently no support for writing buffer object
     * indexed elements here.  Attempt to do so will succeed and
     * write a concrete property into the buffer object.  This should
     * be fixed at some point but because buffers are a custom feature
     * anyway, this is relatively unimportant.
     */
    /*
     *  Actual Object.defineProperty() default algorithm.
     */
    /*
     *  First check whether property exists; if not, simple case.  This covers
     *  steps 1-4.
     */
    if (!duk__get_own_propdesc_raw(thr, obj, key, arr_idx, &curr, DUK_GETDESC_FLAG_PUSH_VALUE)) {
        DUK_DDD(DUK_DDDPRINT("property does not exist"));
        if (!DUK_HOBJECT_HAS_EXTENSIBLE(obj) && !force_flag) {
            goto fail_not_extensible;
        }
        /* XXX: share final setting code for value and flags?  difficult because
         * refcount code is different.  Share entry allocation?  But can't allocate
         * until array index checked.
         */
        /* steps 4.a and 4.b are tricky */
        if (has_set || has_get) {
            duk_int_t e_idx;
            DUK_DDD(DUK_DDDPRINT("create new accessor property"));
            DUK_ASSERT(has_set || set == NULL);
            DUK_ASSERT(has_get || get == NULL);
            DUK_ASSERT(!has_value);
            DUK_ASSERT(!has_writable);
            new_flags = DUK_PROPDESC_FLAG_ACCESSOR;  /* defaults, E5 Section 8.6.1, Table 7 */
            if (has_enumerable && is_enumerable) {
                new_flags |= DUK_PROPDESC_FLAG_ENUMERABLE;
            }
            if (has_configurable && is_configurable) {
                new_flags |= DUK_PROPDESC_FLAG_CONFIGURABLE;
            }
            if (arr_idx != DUK__NO_ARRAY_INDEX && DUK_HOBJECT_HAS_ARRAY_PART(obj)) {
                DUK_DDD(DUK_DDDPRINT("accessor cannot go to array part, abandon array"));
                duk__abandon_array_checked(thr, obj);
            }
            /* write to entry part */
            e_idx = duk__alloc_entry_checked(thr, obj, key);
            DUK_ASSERT(e_idx >= 0);
            DUK_HOBJECT_E_SET_VALUE_GETTER(thr->heap, obj, e_idx, get);
            DUK_HOBJECT_E_SET_VALUE_SETTER(thr->heap, obj, e_idx, set);
            DUK_HOBJECT_INCREF_ALLOWNULL(thr, get);
            DUK_HOBJECT_INCREF_ALLOWNULL(thr, set);
            DUK_HOBJECT_E_SET_FLAGS(thr->heap, obj, e_idx, new_flags);
            goto success_exotics;
        } else {
            duk_int_t e_idx;
            duk_tval *tv2;
            DUK_DDD(DUK_DDDPRINT("create new data property"));
            DUK_ASSERT(!has_set);
            DUK_ASSERT(!has_get);
            new_flags = 0;  /* defaults, E5 Section 8.6.1, Table 7 */
            if (has_writable && is_writable) {
                new_flags |= DUK_PROPDESC_FLAG_WRITABLE;
            }
            if (has_enumerable && is_enumerable) {
                new_flags |= DUK_PROPDESC_FLAG_ENUMERABLE;
            }
            if (has_configurable && is_configurable) {
                new_flags |= DUK_PROPDESC_FLAG_CONFIGURABLE;
            }
            if (has_value) {
                duk_tval *tv_tmp = duk_require_tval(ctx, idx_value);
                DUK_TVAL_SET_TVAL(&tv, tv_tmp);
            } else {
                DUK_TVAL_SET_UNDEFINED(&tv);  /* default value */
            }
            if (arr_idx != DUK__NO_ARRAY_INDEX && DUK_HOBJECT_HAS_ARRAY_PART(obj)) {
                if (new_flags == DUK_PROPDESC_FLAGS_WEC) {
#if 0
                    DUK_DDD(DUK_DDDPRINT("new data property attributes match array defaults, attempt to write to array part"));
                    /* may become sparse...*/
#endif
                    /* XXX: handling for array part missing now; this doesn't affect
                     * compliance but causes array entry writes using defineProperty()
                     * to always abandon array part.
                     */
                }
                DUK_DDD(DUK_DDDPRINT("new data property cannot go to array part, abandon array"));
                duk__abandon_array_checked(thr, obj);
                /* fall through */
            }
            /* write to entry part */
            e_idx = duk__alloc_entry_checked(thr, obj, key);
            DUK_ASSERT(e_idx >= 0);
            tv2 = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, obj, e_idx);
            DUK_TVAL_SET_TVAL(tv2, &tv);
            DUK_TVAL_INCREF(thr, tv2);
            DUK_HOBJECT_E_SET_FLAGS(thr->heap, obj, e_idx, new_flags);
            goto success_exotics;
        }
        DUK_UNREACHABLE();
    }
    /* we currently assume virtual properties are not configurable (as none of them are) */
    DUK_ASSERT((curr.e_idx >= 0 || curr.a_idx >= 0) || !(curr.flags & DUK_PROPDESC_FLAG_CONFIGURABLE));
    /* [obj key desc value get set curr_value] */
    /*
     *  Property already exists.  Steps 5-6 detect whether any changes need
     *  to be made.
     */
    if (has_enumerable) {
        if (is_enumerable) {
            if (!(curr.flags & DUK_PROPDESC_FLAG_ENUMERABLE)) {
                goto need_check;
            }
        } else {
            if (curr.flags & DUK_PROPDESC_FLAG_ENUMERABLE) {
                goto need_check;
            }
        }
    }
    if (has_configurable) {
        if (is_configurable) {
            if (!(curr.flags & DUK_PROPDESC_FLAG_CONFIGURABLE)) {
                goto need_check;
            }
        } else {
            if (curr.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) {
                goto need_check;
            }
        }
    }
    if (has_value) {
        duk_tval *tmp1;
        duk_tval *tmp2;
        /* attempt to change from accessor to data property */
        if (curr.flags & DUK_PROPDESC_FLAG_ACCESSOR) {
            goto need_check;
        }
        tmp1 = duk_require_tval(ctx, -1);         /* curr value */
        tmp2 = duk_require_tval(ctx, idx_value);  /* new value */
        if (!duk_js_samevalue(tmp1, tmp2)) {
            goto need_check;
        }
    }
    if (has_writable) {
        /* attempt to change from accessor to data property */
        if (curr.flags & DUK_PROPDESC_FLAG_ACCESSOR) {
            goto need_check;
        }
        if (is_writable) {
            if (!(curr.flags & DUK_PROPDESC_FLAG_WRITABLE)) {
                goto need_check;
            }
        } else {
            if (curr.flags & DUK_PROPDESC_FLAG_WRITABLE) {
                goto need_check;
            }
        }
    }
    if (has_set) {
        if (curr.flags & DUK_PROPDESC_FLAG_ACCESSOR) {
            if (set != curr.set) {
                goto need_check;
            }
        } else {
            goto need_check;
        }
    }
    if (has_get) {
        if (curr.flags & DUK_PROPDESC_FLAG_ACCESSOR) {
            if (get != curr.get) {
                goto need_check;
            }
        } else {
            goto need_check;
        }
    }
    /* property exists, either 'desc' is empty, or all values
     * match (SameValue)
     */
    goto success_no_exotics;
 need_check:
    /*
     *  Some change(s) need to be made.  Steps 7-11.
     */
    /* shared checks for all descriptor types */
    if (!(curr.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) && !force_flag) {
        if (has_configurable && is_configurable) {
            goto fail_not_configurable;
        }
        if (has_enumerable) {
            if (curr.flags & DUK_PROPDESC_FLAG_ENUMERABLE) {
                if (!is_enumerable) {
                    goto fail_not_configurable;
                }
            } else {
                if (is_enumerable) {
                    goto fail_not_configurable;
                }
            }
        }
    }
    /* Reject attempt to change virtual properties: not part of the
     * standard algorithm, applies currently to e.g. virtual index
     * properties of buffer objects (which are virtual but writable).
     * (Cannot "force" modification of a virtual property.)
     */
    if (curr.flags & DUK_PROPDESC_FLAG_VIRTUAL) {
        goto fail_virtual;
    }
    /* Reject attempt to change a read-only object. */
#if defined(DUK_USE_ROM_OBJECTS)
    if (DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) obj)) {
        DUK_DD(DUK_DDPRINT("attempt to define property on read-only target object"));
        goto fail_not_configurable;
    }
#endif
    /* descriptor type specific checks */
    if (has_set || has_get) {
        /* IsAccessorDescriptor(desc) == true */
        DUK_ASSERT(!has_writable);
        DUK_ASSERT(!has_value);
        if (curr.flags & DUK_PROPDESC_FLAG_ACCESSOR) {
            /* curr and desc are accessors */
            if (!(curr.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) && !force_flag) {
                if (has_set && set != curr.set) {
                    goto fail_not_configurable;
                }
                if (has_get && get != curr.get) {
                    goto fail_not_configurable;
                }
            }
        } else {
            duk_bool_t rc;
            duk_tval *tv1;
            duk_tval tv_tmp;
            /* curr is data, desc is accessor */
            if (!(curr.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) && !force_flag) {
                goto fail_not_configurable;
            }
            DUK_DDD(DUK_DDDPRINT("convert property to accessor property"));
            if (curr.a_idx >= 0) {
                DUK_DDD(DUK_DDDPRINT("property to convert is stored in an array entry, abandon array and re-lookup"));
                duk__abandon_array_checked(thr, obj);
                duk_pop(ctx);  /* remove old value */
                rc = duk__get_own_propdesc_raw(thr, obj, key, arr_idx, &curr, DUK_GETDESC_FLAG_PUSH_VALUE);
                DUK_UNREF(rc);
                DUK_ASSERT(rc != 0);
                DUK_ASSERT(curr.e_idx >= 0 && curr.a_idx < 0);
            }
            DUK_ASSERT(!DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, obj, curr.e_idx));
            /* Avoid side effects that might disturb curr.e_idx until
             * we're done editing the slot.
             */
            tv1 = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, obj, curr.e_idx);
            DUK_TVAL_SET_TVAL(&tv_tmp, tv1);
            DUK_TVAL_SET_UNDEFINED(tv1);
            DUK_HOBJECT_E_SET_VALUE_GETTER(thr->heap, obj, curr.e_idx, NULL);
            DUK_HOBJECT_E_SET_VALUE_SETTER(thr->heap, obj, curr.e_idx, NULL);
            DUK_HOBJECT_E_SLOT_CLEAR_WRITABLE(thr->heap, obj, curr.e_idx);
            DUK_HOBJECT_E_SLOT_SET_ACCESSOR(thr->heap, obj, curr.e_idx);
            DUK_DDD(DUK_DDDPRINT("flags after data->accessor conversion: 0x%02lx",
                                 (unsigned long) DUK_HOBJECT_E_GET_FLAGS(thr->heap, obj, curr.e_idx)));
            DUK_TVAL_DECREF(thr, &tv_tmp);  /* side effects */
            /* re-lookup to update curr.flags
             * XXX: would be faster to update directly
             */
            duk_pop(ctx);  /* remove old value */
            rc = duk__get_own_propdesc_raw(thr, obj, key, arr_idx, &curr, DUK_GETDESC_FLAG_PUSH_VALUE);
            DUK_UNREF(rc);
            DUK_ASSERT(rc != 0);
        }
    } else if (has_value || has_writable) {
        /* IsDataDescriptor(desc) == true */
        DUK_ASSERT(!has_set);
        DUK_ASSERT(!has_get);
        if (curr.flags & DUK_PROPDESC_FLAG_ACCESSOR) {
            duk_bool_t rc;
            duk_hobject *h_get;
            duk_hobject *h_set;
            /* curr is accessor, desc is data */
            if (!(curr.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) && !force_flag) {
                goto fail_not_configurable;
            }
            /* curr is accessor -> cannot be in array part */
            DUK_ASSERT(curr.e_idx >= 0 && curr.a_idx < 0);
            DUK_DDD(DUK_DDDPRINT("convert property to data property"));
            /* Avoid side effects that might disturb curr.e_idx until
             * we're done editing the slot.
             */
            DUK_ASSERT(DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, obj, curr.e_idx));
            h_get = DUK_HOBJECT_E_GET_VALUE_GETTER(thr->heap, obj, curr.e_idx);
            DUK_HOBJECT_E_SET_VALUE_GETTER(thr->heap, obj, curr.e_idx, NULL);
            h_set = DUK_HOBJECT_E_GET_VALUE_SETTER(thr->heap, obj, curr.e_idx);
            DUK_HOBJECT_E_SET_VALUE_SETTER(thr->heap, obj, curr.e_idx, NULL);
            DUK_TVAL_SET_UNDEFINED(DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, obj, curr.e_idx));
            DUK_HOBJECT_E_SLOT_CLEAR_WRITABLE(thr->heap, obj, curr.e_idx);
            DUK_HOBJECT_E_SLOT_CLEAR_ACCESSOR(thr->heap, obj, curr.e_idx);
            DUK_DDD(DUK_DDDPRINT("flags after accessor->data conversion: 0x%02lx",
                                 (unsigned long) DUK_HOBJECT_E_GET_FLAGS(thr->heap, obj, curr.e_idx)));
            DUK_HOBJECT_DECREF_ALLOWNULL(thr, h_get);  /* side effects */
            DUK_HOBJECT_DECREF_ALLOWNULL(thr, h_set);  /* side effects */
            /* re-lookup to update curr.flags
             * XXX: would be faster to update directly
             */
            duk_pop(ctx);  /* remove old value */
            rc = duk__get_own_propdesc_raw(thr, obj, key, arr_idx, &curr, DUK_GETDESC_FLAG_PUSH_VALUE);
            DUK_UNREF(rc);
            DUK_ASSERT(rc != 0);
        } else {
            /* curr and desc are data */
            if (!(curr.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) && !force_flag) {
                if (!(curr.flags & DUK_PROPDESC_FLAG_WRITABLE) && has_writable && is_writable) {
                    goto fail_not_configurable;
                }
                /* Note: changing from writable to non-writable is OK */
                if (!(curr.flags & DUK_PROPDESC_FLAG_WRITABLE) && has_value) {
                    duk_tval *tmp1 = duk_require_tval(ctx, -1);         /* curr value */
                    duk_tval *tmp2 = duk_require_tval(ctx, idx_value);  /* new value */
                    if (!duk_js_samevalue(tmp1, tmp2)) {
                        goto fail_not_configurable;
                    }
                }
            }
        }
    } else {
        /* IsGenericDescriptor(desc) == true; this means in practice that 'desc'
         * only has [[Enumerable]] or [[Configurable]] flag updates, which are
         * allowed at this point.
         */
        DUK_ASSERT(!has_value && !has_writable && !has_get && !has_set);
    }
    /*
     *  Start doing property attributes updates.  Steps 12-13.
     *
     *  Start by computing new attribute flags without writing yet.
     *  Property type conversion is done above if necessary.
     */
    new_flags = curr.flags;
    if (has_enumerable) {
        if (is_enumerable) {
            new_flags |= DUK_PROPDESC_FLAG_ENUMERABLE;
        } else {
            new_flags &= ~DUK_PROPDESC_FLAG_ENUMERABLE;
        }
    }
    if (has_configurable) {
        if (is_configurable) {
            new_flags |= DUK_PROPDESC_FLAG_CONFIGURABLE;
        } else {
            new_flags &= ~DUK_PROPDESC_FLAG_CONFIGURABLE;
        }
    }
    if (has_writable) {
        if (is_writable) {
            new_flags |= DUK_PROPDESC_FLAG_WRITABLE;
        } else {
            new_flags &= ~DUK_PROPDESC_FLAG_WRITABLE;
        }
    }
    /* XXX: write protect after flag? -> any chance of handling it here? */
    DUK_DDD(DUK_DDDPRINT("new flags that we want to write: 0x%02lx",
                         (unsigned long) new_flags));
    /*
     *  Check whether we need to abandon an array part (if it exists)
     */
    if (curr.a_idx >= 0) {
        duk_bool_t rc;
        DUK_ASSERT(curr.e_idx < 0);
        if (new_flags == DUK_PROPDESC_FLAGS_WEC) {
            duk_tval *tv1, *tv2;
            DUK_DDD(DUK_DDDPRINT("array index, new property attributes match array defaults, update in-place"));
            DUK_ASSERT(curr.flags == DUK_PROPDESC_FLAGS_WEC);  /* must have been, since in array part */
            DUK_ASSERT(!has_set);
            DUK_ASSERT(!has_get);
            tv2 = duk_require_tval(ctx, idx_value);
            tv1 = DUK_HOBJECT_A_GET_VALUE_PTR(thr->heap, obj, curr.a_idx);
            DUK_TVAL_SET_TVAL_UPDREF(thr, tv1, tv2);  /* side effects */
            goto success_exotics;
        }
        DUK_DDD(DUK_DDDPRINT("array index, new property attributes do not match array defaults, abandon array and re-lookup"));
        duk__abandon_array_checked(thr, obj);
        duk_pop(ctx);  /* remove old value */
        rc = duk__get_own_propdesc_raw(thr, obj, key, arr_idx, &curr, DUK_GETDESC_FLAG_PUSH_VALUE);
        DUK_UNREF(rc);
        DUK_ASSERT(rc != 0);
        DUK_ASSERT(curr.e_idx >= 0 && curr.a_idx < 0);
    }
    DUK_DDD(DUK_DDDPRINT("updating existing property in entry part"));
    /* array case is handled comprehensively above */
    DUK_ASSERT(curr.e_idx >= 0 && curr.a_idx < 0);
    DUK_DDD(DUK_DDDPRINT("update existing property attributes"));
    DUK_HOBJECT_E_SET_FLAGS(thr->heap, obj, curr.e_idx, new_flags);
    if (has_set) {
        duk_hobject *tmp;
        DUK_DDD(DUK_DDDPRINT("update existing property setter"));
        DUK_ASSERT(DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, obj, curr.e_idx));
        tmp = DUK_HOBJECT_E_GET_VALUE_SETTER(thr->heap, obj, curr.e_idx);
        DUK_UNREF(tmp);
        DUK_HOBJECT_E_SET_VALUE_SETTER(thr->heap, obj, curr.e_idx, set);
        DUK_HOBJECT_INCREF_ALLOWNULL(thr, set);
        DUK_HOBJECT_DECREF_ALLOWNULL(thr, tmp);  /* side effects */
    }
    if (has_get) {
        duk_hobject *tmp;
        DUK_DDD(DUK_DDDPRINT("update existing property getter"));
        DUK_ASSERT(DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, obj, curr.e_idx));
        tmp = DUK_HOBJECT_E_GET_VALUE_GETTER(thr->heap, obj, curr.e_idx);
        DUK_UNREF(tmp);
        DUK_HOBJECT_E_SET_VALUE_GETTER(thr->heap, obj, curr.e_idx, get);
        DUK_HOBJECT_INCREF_ALLOWNULL(thr, get);
        DUK_HOBJECT_DECREF_ALLOWNULL(thr, tmp);  /* side effects */
    }
    if (has_value) {
        duk_tval *tv1, *tv2;
        DUK_DDD(DUK_DDDPRINT("update existing property value"));
        DUK_ASSERT(!DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, obj, curr.e_idx));
        tv2 = duk_require_tval(ctx, idx_value);
        tv1 = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, obj, curr.e_idx);
        DUK_TVAL_SET_TVAL_UPDREF(thr, tv1, tv2);  /* side effects */
    }
    /*
     *  Standard algorithm succeeded without errors, check for exotic post-behaviors.
     *
     *  Arguments exotic behavior in E5 Section 10.6 occurs after the standard
     *  [[DefineOwnProperty]] has completed successfully.
     *
     *  Array exotic behavior in E5 Section 15.4.5.1 is implemented partly
     *  prior to the default [[DefineOwnProperty]], but:
     *    - for an array index key (e.g. "10") the final 'length' update occurs here
     *    - for 'length' key the element deletion and 'length' update occurs here
     */
 success_exotics:
    /* [obj key desc value get set curr_value] */
    if (DUK_HOBJECT_HAS_EXOTIC_ARRAY(obj)) {
        if (arridx_new_array_length > 0) {
            duk_tval *tmp;
            duk_bool_t rc;
            /*
             *  Note: zero works as a "no update" marker because the new length
             *  can never be zero after a new property is written.
             */
            /* E5 Section 15.4.5.1, steps 4.e.i - 4.e.ii */
            DUK_DDD(DUK_DDDPRINT("defineProperty successful, pending array length update to: %ld",
                                 (long) arridx_new_array_length));
            /* Note: reuse 'curr' */
            rc = duk__get_own_propdesc_raw(thr, obj, DUK_HTHREAD_STRING_LENGTH(thr), DUK__NO_ARRAY_INDEX, &curr, 0 /*flags*/);  /* don't push value */
            DUK_UNREF(rc);
            DUK_ASSERT(rc != 0);
            DUK_ASSERT(curr.e_idx >= 0);
            tmp = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, obj, curr.e_idx);
            DUK_ASSERT(DUK_TVAL_IS_NUMBER(tmp));
            /* no need for decref/incref because value is a number */
            DUK_TVAL_SET_FASTINT_U32(tmp, arridx_new_array_length);
        }
        if (key == DUK_HTHREAD_STRING_LENGTH(thr) && arrlen_new_len < arrlen_old_len) {
            /*
             *  E5 Section 15.4.5.1, steps 3.k - 3.n.  The order at the end combines
             *  the error case 3.l.iii and the success case 3.m-3.n.
             *
             *  Note: 'length' is always in entries part, so no array abandon issues for
             *  'writable' update.
             */
            /* XXX: investigate whether write protect can be handled above, if we
             * just update length here while ignoring its protected status
             */
            duk_tval *tmp;
            duk_uint32_t result_len;
            duk_bool_t rc;
            DUK_DDD(DUK_DDDPRINT("defineProperty successful, key is 'length', exotic array behavior, "
                                 "doing array element deletion and length update"));
            rc = duk__handle_put_array_length_smaller(thr, obj, arrlen_old_len, arrlen_new_len, force_flag, &result_len);
            /* update length (curr points to length, and we assume it's still valid) */
            DUK_ASSERT(result_len >= arrlen_new_len && result_len <= arrlen_old_len);
            DUK_ASSERT(curr.e_idx >= 0);
            DUK_ASSERT(!DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, obj, curr.e_idx));
            tmp = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, obj, curr.e_idx);
            DUK_ASSERT(DUK_TVAL_IS_NUMBER(tmp));
            /* no decref needed for a number */
            DUK_TVAL_SET_FASTINT_U32(tmp, result_len);
            DUK_ASSERT(DUK_TVAL_IS_NUMBER(tmp));
            if (pending_write_protect) {
                DUK_DDD(DUK_DDDPRINT("setting array length non-writable (pending writability update)"));
                DUK_HOBJECT_E_SLOT_CLEAR_WRITABLE(thr->heap, obj, curr.e_idx);
            }
            /*
             *  XXX: shrink array allocation or entries compaction here?
             */
            if (!rc) {
                goto fail_array_length_partial;
            }
        }
    } else if (arr_idx != DUK__NO_ARRAY_INDEX && DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS(obj)) {
        duk_hobject *map;
        duk_hobject *varenv;
        DUK_ASSERT(arridx_new_array_length == 0);
        DUK_ASSERT(!DUK_HOBJECT_HAS_EXOTIC_ARRAY(obj));  /* traits are separate; in particular, arguments not an array */
        map = NULL;
        varenv = NULL;
        if (!duk__lookup_arguments_map(thr, obj, key, &curr, &map, &varenv)) {
            goto success_no_exotics;
        }
        DUK_ASSERT(map != NULL);
        DUK_ASSERT(varenv != NULL);
        /* [obj key desc value get set curr_value varname] */
        if (has_set || has_get) {
            /* = IsAccessorDescriptor(Desc) */
            DUK_DDD(DUK_DDDPRINT("defineProperty successful, key mapped to arguments 'map' "
                                 "changed to an accessor, delete arguments binding"));
            (void) duk_hobject_delprop_raw(thr, map, key, 0);  /* ignore result */
        } else {
            /* Note: this order matters (final value before deleting map entry must be done) */
            DUK_DDD(DUK_DDDPRINT("defineProperty successful, key mapped to arguments 'map', "
                                 "check for value update / binding deletion"));
            if (has_value) {
                duk_hstring *varname;
                DUK_DDD(DUK_DDDPRINT("defineProperty successful, key mapped to arguments 'map', "
                                     "update bound value (variable/argument)"));
                varname = duk_require_hstring(ctx, -1);
                DUK_ASSERT(varname != NULL);
                DUK_DDD(DUK_DDDPRINT("arguments object automatic putvar for a bound variable; "
                                     "key=%!O, varname=%!O, value=%!T",
                                     (duk_heaphdr *) key,
                                     (duk_heaphdr *) varname,
                                     (duk_tval *) duk_require_tval(ctx, idx_value)));
                /* strict flag for putvar comes from our caller (currently: fixed) */
                duk_js_putvar_envrec(thr, varenv, varname, duk_require_tval(ctx, idx_value), throw_flag);
            }
            if (has_writable && !is_writable) {
                DUK_DDD(DUK_DDDPRINT("defineProperty successful, key mapped to arguments 'map', "
                                     "changed to non-writable, delete arguments binding"));
                (void) duk_hobject_delprop_raw(thr, map, key, 0);  /* ignore result */
            }
        }
        /* 'varname' is in stack in this else branch, leaving an unbalanced stack below,
         * but this doesn't matter now.
         */
    }
 success_no_exotics:
    return;
 fail_virtual:
    DUK_ERROR_TYPE(thr, DUK_STR_PROPERTY_IS_VIRTUAL);
    return;
References duk_propdesc::a_idx, duk__abandon_array_checked(), duk__alloc_entry_checked(), duk__get_old_array_length(), duk__get_own_propdesc_raw(), duk__handle_put_array_length_smaller(), duk__lookup_arguments_map(), DUK__NO_ARRAY_INDEX, duk__to_new_array_length_checked(), DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, DUK_DD, DUK_DDD, DUK_DDDPRINT, DUK_DDPRINT, DUK_DEFPROP_CONFIGURABLE, DUK_DEFPROP_ENUMERABLE, DUK_DEFPROP_FORCE, DUK_DEFPROP_HAVE_CONFIGURABLE, DUK_DEFPROP_HAVE_ENUMERABLE, DUK_DEFPROP_HAVE_GETTER, DUK_DEFPROP_HAVE_SETTER, DUK_DEFPROP_HAVE_VALUE, DUK_DEFPROP_HAVE_WRITABLE, DUK_DEFPROP_WRITABLE, duk_dup(), DUK_ERROR_TYPE, duk_get_tval(), DUK_GETDESC_FLAG_PUSH_VALUE, DUK_HEAPHDR_HAS_READONLY, DUK_HOBJECT_A_GET_VALUE_PTR, DUK_HOBJECT_DECREF_ALLOWNULL, duk_hobject_delprop_raw(), DUK_HOBJECT_E_GET_FLAGS, DUK_HOBJECT_E_GET_VALUE_GETTER, DUK_HOBJECT_E_GET_VALUE_SETTER, DUK_HOBJECT_E_GET_VALUE_TVAL_PTR, DUK_HOBJECT_E_SET_FLAGS, DUK_HOBJECT_E_SET_VALUE_GETTER, DUK_HOBJECT_E_SET_VALUE_SETTER, DUK_HOBJECT_E_SLOT_CLEAR_ACCESSOR, DUK_HOBJECT_E_SLOT_CLEAR_WRITABLE, DUK_HOBJECT_E_SLOT_IS_ACCESSOR, DUK_HOBJECT_E_SLOT_SET_ACCESSOR, DUK_HOBJECT_HAS_ARRAY_PART, DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS, DUK_HOBJECT_HAS_EXOTIC_ARRAY, DUK_HOBJECT_HAS_EXTENSIBLE, DUK_HOBJECT_INCREF_ALLOWNULL, DUK_HSTRING_GET_ARRIDX_SLOW, DUK_HTHREAD_STRING_LENGTH, duk_js_putvar_envrec(), duk_js_samevalue, duk_pop(), DUK_PROPDESC_FLAG_ACCESSOR, DUK_PROPDESC_FLAG_CONFIGURABLE, DUK_PROPDESC_FLAG_ENUMERABLE, DUK_PROPDESC_FLAG_VIRTUAL, DUK_PROPDESC_FLAG_WRITABLE, DUK_PROPDESC_FLAGS_WEC, duk_push_u32, duk_replace(), duk_require_hstring(), duk_require_tval(), DUK_STR_ARRAY_LENGTH_NOT_WRITABLE, DUK_STR_ARRAY_LENGTH_WRITE_FAILED, DUK_STR_NOT_CONFIGURABLE, DUK_STR_NOT_EXTENSIBLE, DUK_STR_PROPERTY_IS_VIRTUAL, DUK_TVAL_DECREF, DUK_TVAL_INCREF, DUK_TVAL_IS_NUMBER, DUK_TVAL_SET_FASTINT_U32, DUK_TVAL_SET_TVAL, DUK_TVAL_SET_TVAL_UPDREF, DUK_TVAL_SET_UNDEFINED, DUK_UNREACHABLE, DUK_UNREF, duk_propdesc::e_idx, duk_propdesc::flags, duk_propdesc::get, duk_hthread::heap, NULL, and duk_propdesc::set.
Referenced by duk_bi_object_constructor_define_properties(), duk_bi_object_constructor_define_property(), and duk_def_prop().
duk_hobject_define_property_internal()
DUK_INTERNAL_DECL void duk_hobject_define_property_internal (duk_hthread * thr, duk_hobject * obj, duk_hstring * key, duk_small_uint_t flags)
Definition at line 51590 of file duktape-1.5.2/src-noline/duktape.c.
                    :
 *    - virtual properties (error if write attempted)
 *    - getter/setter properties (error if write attempted)
 *    - non-default (!= WEC) attributes for array entries (error if attempted)
 *    - array abandoning: if array part exists, it is always extended
 *    - array 'length' updating
 *
 *  Stack: [... in_val] -> []
 *
 *  Used for e.g. built-in initialization and environment record
 *  operations.
 */
DUK_INTERNAL void duk_hobject_define_property_internal(duk_hthread *thr, duk_hobject *obj, duk_hstring *key, duk_small_uint_t flags) {
    duk_context *ctx = (duk_context *) thr;
    duk_propdesc desc;
    duk_uint32_t arr_idx;
    duk_int_t e_idx;
    duk_tval *tv1 = NULL;
    duk_tval *tv2 = NULL;
    duk_small_uint_t propflags = flags & DUK_PROPDESC_FLAGS_MASK;  /* mask out flags not actually stored */
    DUK_DDD(DUK_DDDPRINT("define new property (internal): thr=%p, obj=%!O, key=%!O, flags=0x%02lx, val=%!T",
                         (void *) thr, (duk_heaphdr *) obj, (duk_heaphdr *) key,
                         (unsigned long) flags, (duk_tval *) duk_get_tval(ctx, -1)));
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT(key != NULL);
    DUK_ASSERT(!DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) obj));
    DUK_ASSERT_VALSTACK_SPACE(thr, DUK__VALSTACK_SPACE);
    DUK_ASSERT(duk_is_valid_index(ctx, -1));  /* contains value */
    arr_idx = DUK_HSTRING_GET_ARRIDX_SLOW(key);
    if (duk__get_own_propdesc_raw(thr, obj, key, arr_idx, &desc, 0 /*flags*/)) {  /* don't push value */
        if (desc.e_idx >= 0) {
            if (flags & DUK_PROPDESC_FLAG_NO_OVERWRITE) {
                DUK_DDD(DUK_DDDPRINT("property already exists in the entry part -> skip as requested"));
                goto pop_exit;
            }
            DUK_DDD(DUK_DDDPRINT("property already exists in the entry part -> update value and attributes"));
            if (DUK_UNLIKELY(DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, obj, desc.e_idx))) {
                DUK_D(DUK_DPRINT("existing property is an accessor, not supported"));
                goto error_internal;
            }
            DUK_HOBJECT_E_SET_FLAGS(thr->heap, obj, desc.e_idx, propflags);
            tv1 = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, obj, desc.e_idx);
        } else if (desc.a_idx >= 0) {
            if (flags & DUK_PROPDESC_FLAG_NO_OVERWRITE) {
                DUK_DDD(DUK_DDDPRINT("property already exists in the array part -> skip as requested"));
                goto pop_exit;
            }
            DUK_DDD(DUK_DDDPRINT("property already exists in the array part -> update value (assert attributes)"));
            if (propflags != DUK_PROPDESC_FLAGS_WEC) {
                DUK_D(DUK_DPRINT("existing property in array part, but propflags not WEC (0x%02lx)",
                                 (unsigned long) propflags));
                goto error_internal;
            }
            tv1 = DUK_HOBJECT_A_GET_VALUE_PTR(thr->heap, obj, desc.a_idx);
        } else {
            if (flags & DUK_PROPDESC_FLAG_NO_OVERWRITE) {
                DUK_DDD(DUK_DDDPRINT("property already exists but is virtual -> skip as requested"));
                goto pop_exit;
            }
            DUK_DDD(DUK_DDDPRINT("property already exists but is virtual -> failure"));
            goto error_virtual;
        }
        goto write_value;
    }
    if (DUK_HOBJECT_HAS_ARRAY_PART(obj)) {
        if (arr_idx != DUK__NO_ARRAY_INDEX) {
            DUK_DDD(DUK_DDDPRINT("property does not exist, object has array part -> possibly extend array part and write value (assert attributes)"));
            DUK_ASSERT(propflags == DUK_PROPDESC_FLAGS_WEC);
            /* always grow the array, no sparse / abandon support here */
            if (arr_idx >= DUK_HOBJECT_GET_ASIZE(obj)) {
                duk__grow_props_for_array_item(thr, obj, arr_idx);
            }
            DUK_ASSERT(arr_idx < DUK_HOBJECT_GET_ASIZE(obj));
            tv1 = DUK_HOBJECT_A_GET_VALUE_PTR(thr->heap, obj, arr_idx);
            goto write_value;
        }
    }
    DUK_DDD(DUK_DDDPRINT("property does not exist, object belongs in entry part -> allocate new entry and write value and attributes"));
    e_idx = duk__alloc_entry_checked(thr, obj, key);  /* increases key refcount */
    DUK_ASSERT(e_idx >= 0);
    DUK_HOBJECT_E_SET_FLAGS(thr->heap, obj, e_idx, propflags);
    tv1 = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, obj, e_idx);
    /* new entry: previous value is garbage; set to undefined to share write_value */
    DUK_TVAL_SET_UNDEFINED(tv1);
    goto write_value;
 write_value:
    /* tv1 points to value storage */
    tv2 = duk_require_tval(ctx, -1);  /* late lookup, avoid side effects */
    DUK_DDD(DUK_DDDPRINT("writing/updating value: %!T -> %!T",
References duk_propdesc::a_idx, duk__alloc_entry_checked(), duk__get_own_propdesc_raw(), duk__grow_props_for_array_item(), DUK__NO_ARRAY_INDEX, DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, DUK_D, DUK_DDD, DUK_DDDPRINT, DUK_DPRINT, DUK_ERROR_INTERNAL_DEFMSG, DUK_ERROR_TYPE, duk_get_tval(), DUK_HEAPHDR_HAS_READONLY, DUK_HOBJECT_A_GET_VALUE_PTR, DUK_HOBJECT_E_GET_VALUE_TVAL_PTR, DUK_HOBJECT_E_SET_FLAGS, DUK_HOBJECT_E_SLOT_IS_ACCESSOR, DUK_HOBJECT_GET_ASIZE, DUK_HOBJECT_HAS_ARRAY_PART, DUK_HSTRING_GET_ARRIDX_SLOW, duk_is_valid_index(), duk_pop(), DUK_PROPDESC_FLAG_NO_OVERWRITE, DUK_PROPDESC_FLAGS_MASK, DUK_PROPDESC_FLAGS_WEC, duk_require_tval(), DUK_STR_REDEFINE_VIRT_PROP, DUK_TVAL_SET_TVAL_UPDREF, DUK_TVAL_SET_UNDEFINED, DUK_UNLIKELY, duk_propdesc::e_idx, duk_hthread::heap, and NULL.
Referenced by duk__declvar_helper(), duk_hobject_define_accessor_internal(), duk_hobject_define_property_internal_arridx(), duk_push_array(), duk_xdef_prop(), duk_xdef_prop_stridx(), and duk_xdef_prop_stridx_builtin().
duk_hobject_define_property_internal_arridx()
DUK_INTERNAL_DECL void duk_hobject_define_property_internal_arridx (duk_hthread * thr, duk_hobject * obj, duk_uarridx_t arr_idx, duk_small_uint_t flags)
Definition at line 51706 of file duktape-1.5.2/src-noline/duktape.c.
               :
    DUK_ERROR_INTERNAL_DEFMSG(thr);
    return;
 error_virtual:
    DUK_ERROR_TYPE(thr, DUK_STR_REDEFINE_VIRT_PROP);
    return;
}
/*
 *  Fast path for defining array indexed values without interning the key.
 *  This is used by e.g. code for Array prototype and traceback creation so
 *  must avoid interning.
 */
DUK_INTERNAL void duk_hobject_define_property_internal_arridx(duk_hthread *thr, duk_hobject *obj, duk_uarridx_t arr_idx, duk_small_uint_t flags) {
    duk_context *ctx = (duk_context *) thr;
    duk_hstring *key;
    duk_tval *tv1, *tv2;
    DUK_DDD(DUK_DDDPRINT("define new property (internal) arr_idx fast path: thr=%p, obj=%!O, "
                         "arr_idx=%ld, flags=0x%02lx, val=%!T",
                         (void *) thr, obj, (long) arr_idx, (unsigned long) flags,
                         (duk_tval *) duk_get_tval(ctx, -1)));
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT(!DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) obj));
    if (DUK_HOBJECT_HAS_ARRAY_PART(obj) &&
        arr_idx != DUK__NO_ARRAY_INDEX &&
        flags == DUK_PROPDESC_FLAGS_WEC) {
        DUK_ASSERT((flags & DUK_PROPDESC_FLAG_NO_OVERWRITE) == 0);  /* covered by comparison */
        DUK_DDD(DUK_DDDPRINT("define property to array part (property may or may not exist yet)"));
        /* always grow the array, no sparse / abandon support here */
        if (arr_idx >= DUK_HOBJECT_GET_ASIZE(obj)) {
            duk__grow_props_for_array_item(thr, obj, arr_idx);
        }
        DUK_ASSERT(arr_idx < DUK_HOBJECT_GET_ASIZE(obj));
        tv1 = DUK_HOBJECT_A_GET_VALUE_PTR(thr->heap, obj, arr_idx);
        tv2 = duk_require_tval(ctx, -1);
References duk__grow_props_for_array_item(), DUK__NO_ARRAY_INDEX, DUK_ASSERT, DUK_DDD, DUK_DDDPRINT, duk_get_tval(), DUK_HEAPHDR_HAS_READONLY, DUK_HOBJECT_A_GET_VALUE_PTR, duk_hobject_define_property_internal(), DUK_HOBJECT_GET_ASIZE, DUK_HOBJECT_HAS_ARRAY_PART, duk_insert(), duk_pop(), DUK_PROPDESC_FLAG_NO_OVERWRITE, DUK_PROPDESC_FLAGS_WEC, duk_push_uint(), duk_require_tval(), duk_to_hstring(), DUK_TVAL_SET_TVAL_UPDREF, duk_hthread::heap, and NULL.
Referenced by duk_xdef_prop_index().
duk_hobject_delprop()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_delprop (duk_hthread * thr, duk_tval * tv_obj, duk_tval * tv_key, duk_bool_t throw_flag)
Definition at line 51383 of file duktape-1.5.2/src-noline/duktape.c.
                      :
    DUK_DDD(DUK_DDDPRINT("delete failed: property found, not configurable"));
    if (throw_flag) {
        DUK_ERROR_TYPE(thr, DUK_STR_NOT_CONFIGURABLE);
    }
    return 0;
}
/*
 *  DELPROP: Ecmascript property deletion.
 */
DUK_INTERNAL duk_bool_t duk_hobject_delprop(duk_hthread *thr, duk_tval *tv_obj, duk_tval *tv_key, duk_bool_t throw_flag) {
    duk_context *ctx = (duk_context *) thr;
    duk_hstring *key = NULL;
#if defined(DUK_USE_ES6_PROXY)
    duk_propdesc desc;
#endif
    duk_int_t entry_top;
    duk_uint32_t arr_idx = DUK__NO_ARRAY_INDEX;
    duk_bool_t rc;
    DUK_DDD(DUK_DDDPRINT("delprop: thr=%p, obj=%p, key=%p (obj -> %!T, key -> %!T)",
                         (void *) thr, (void *) tv_obj, (void *) tv_key,
                         (duk_tval *) tv_obj, (duk_tval *) tv_key));
    DUK_ASSERT(ctx != NULL);
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(tv_obj != NULL);
    DUK_ASSERT(tv_key != NULL);
    DUK_ASSERT_VALSTACK_SPACE(thr, DUK__VALSTACK_SPACE);
    /* Storing the entry top is cheaper here to ensure stack is correct at exit,
     * as there are several paths out.
     */
    entry_top = duk_get_top(ctx);
    if (DUK_TVAL_IS_UNDEFINED(tv_obj) ||
        DUK_TVAL_IS_NULL(tv_obj)) {
        DUK_DDD(DUK_DDDPRINT("base object is undefined or null -> reject"));
        goto fail_invalid_base_uncond;
    }
    duk_push_tval(ctx, tv_obj);
    duk_push_tval(ctx, tv_key);
    tv_obj = DUK_GET_TVAL_NEGIDX(ctx, -2);
    if (DUK_TVAL_IS_OBJECT(tv_obj)) {
        duk_hobject *obj = DUK_TVAL_GET_OBJECT(tv_obj);
        DUK_ASSERT(obj != NULL);
#if defined(DUK_USE_ES6_PROXY)
        if (DUK_UNLIKELY(DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ(obj))) {
            duk_hobject *h_target;
            duk_bool_t tmp_bool;
            /* Note: proxy handling must happen before key is string coerced. */
            if (duk__proxy_check_prop(thr, obj, DUK_STRIDX_DELETE_PROPERTY, tv_key, &h_target)) {
                /* -> [ ... trap handler ] */
                DUK_DDD(DUK_DDDPRINT("-> proxy object 'deleteProperty' for key %!T", (duk_tval *) tv_key));
                duk_push_hobject(ctx, h_target);  /* target */
                duk_push_tval(ctx, tv_key);       /* P */
                duk_call_method(ctx, 2 /*nargs*/);
                tmp_bool = duk_to_boolean(ctx, -1);
                duk_pop(ctx);
                if (!tmp_bool) {
                    goto fail_proxy_rejected;  /* retval indicates delete failed */
                }
                /* Target object must be checked for a conflicting
                 * non-configurable property.
                 */
                arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
                DUK_ASSERT(key != NULL);
                if (duk__get_own_propdesc_raw(thr, h_target, key, arr_idx, &desc, 0 /*flags*/)) {  /* don't push value */
                    int desc_reject;
                    DUK_DDD(DUK_DDDPRINT("proxy 'deleteProperty': target has matching property %!O, check for "
                                         "conflicting property; desc.flags=0x%08lx, "
                                         "desc.get=%p, desc.set=%p",
                                         (duk_heaphdr *) key, (unsigned long) desc.flags,
                                         (void *) desc.get, (void *) desc.set));
                    desc_reject = !(desc.flags & DUK_PROPDESC_FLAG_CONFIGURABLE);
                    if (desc_reject) {
                        /* unconditional */
                        DUK_ERROR_TYPE(thr, DUK_STR_PROXY_REJECTED);
                    }
                }
                rc = 1;  /* success */
                goto done_rc;
            }
            obj = h_target;  /* resume delete to target */
        }
#endif  /* DUK_USE_ES6_PROXY */
        duk_to_string(ctx, -1);
        key = duk_get_hstring(ctx, -1);
        DUK_ASSERT(key != NULL);
        rc = duk_hobject_delprop_raw(thr, obj, key, throw_flag ? DUK_DELPROP_FLAG_THROW : 0);
        goto done_rc;
    } else if (DUK_TVAL_IS_STRING(tv_obj)) {
        /* XXX: unnecessary string coercion for array indices,
         * intentional to keep small.
         */
        duk_hstring *h = DUK_TVAL_GET_STRING(tv_obj);
        DUK_ASSERT(h != NULL);
        duk_to_string(ctx, -1);
        key = duk_get_hstring(ctx, -1);
        DUK_ASSERT(key != NULL);
        if (key == DUK_HTHREAD_STRING_LENGTH(thr)) {
            goto fail_not_configurable;
        }
        arr_idx = DUK_HSTRING_GET_ARRIDX_FAST(key);
        if (arr_idx != DUK__NO_ARRAY_INDEX &&
            arr_idx < DUK_HSTRING_GET_CHARLEN(h)) {
            goto fail_not_configurable;
        }
    } else if (DUK_TVAL_IS_BUFFER(tv_obj)) {
        /* XXX: unnecessary string coercion for array indices,
         * intentional to keep small; some overlap with string
         * handling.
         */
        duk_hbuffer *h = DUK_TVAL_GET_BUFFER(tv_obj);
        DUK_ASSERT(h != NULL);
        duk_to_string(ctx, -1);
        key = duk_get_hstring(ctx, -1);
        DUK_ASSERT(key != NULL);
        if (key == DUK_HTHREAD_STRING_LENGTH(thr)) {
            goto fail_not_configurable;
        }
        arr_idx = DUK_HSTRING_GET_ARRIDX_FAST(key);
        if (arr_idx != DUK__NO_ARRAY_INDEX &&
            arr_idx < DUK_HBUFFER_GET_SIZE(h)) {
            goto fail_not_configurable;
        }
    } else if (DUK_TVAL_IS_LIGHTFUNC(tv_obj)) {
        /* Lightfunc virtual properties are non-configurable, so
         * reject if match any of them.
         */
        duk_to_string(ctx, -1);
        key = duk_get_hstring(ctx, -1);
        DUK_ASSERT(key != NULL);
        if (duk__key_is_lightfunc_ownprop(thr, key)) {
            goto fail_not_configurable;
        }
    }
    /* non-object base, no offending virtual property */
    rc = 1;
    goto done_rc;
 done_rc:
    duk_set_top(ctx, entry_top);
    return rc;
 fail_invalid_base_uncond:
    /* Note: unconditional throw */
    DUK_ASSERT(duk_get_top(ctx) == entry_top);
#if defined(DUK_USE_PARANOID_ERRORS)
    DUK_ERROR_TYPE(thr, DUK_STR_INVALID_BASE);
#else
    DUK_ERROR_FMT2(thr, DUK_ERR_TYPE_ERROR, "cannot delete property %s of %s",
                   duk_push_string_tval_readable(ctx, tv_key), duk_push_string_tval_readable(ctx, tv_obj));
#endif
    return 0;
References duk__get_own_propdesc_raw(), duk__key_is_lightfunc_ownprop(), DUK__NO_ARRAY_INDEX, duk__proxy_check_prop(), duk__push_tval_to_hstring_arr_idx(), DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, duk_call_method(), DUK_DDD, DUK_DDDPRINT, DUK_DELPROP_FLAG_THROW, duk_dup(), DUK_ERR_TYPE_ERROR, DUK_ERROR_FMT2, DUK_ERROR_TYPE, duk_get_hstring(), duk_get_top(), DUK_GET_TVAL_NEGIDX, DUK_HBUFFER_GET_SIZE, duk_hobject_delprop_raw(), DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ, DUK_HSTRING_GET_ARRIDX_FAST, DUK_HSTRING_GET_CHARLEN, DUK_HTHREAD_STRING_LENGTH, duk_pop(), DUK_PROPDESC_FLAG_CONFIGURABLE, duk_push_hobject(), duk_push_string_tval_readable(), duk_push_tval(), duk_set_top(), DUK_STR_INVALID_BASE, DUK_STR_NOT_CONFIGURABLE, DUK_STR_PROXY_REJECTED, DUK_STRIDX_DELETE_PROPERTY, duk_to_boolean(), duk_to_string(), DUK_TVAL_GET_BUFFER, DUK_TVAL_GET_OBJECT, DUK_TVAL_GET_STRING, DUK_TVAL_IS_BUFFER, DUK_TVAL_IS_LIGHTFUNC, DUK_TVAL_IS_NULL, DUK_TVAL_IS_OBJECT, DUK_TVAL_IS_STRING, DUK_TVAL_IS_UNDEFINED, DUK_UNLIKELY, duk_propdesc::flags, duk_propdesc::get, duk_hthread::heap, NULL, and duk_propdesc::set.
Referenced by duk__js_execute_bytecode_inner(), and duk_del_prop().
duk_hobject_delprop_raw()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_delprop_raw (duk_hthread * thr, duk_hobject * obj, duk_hstring * key, duk_small_uint_t flags)
Definition at line 51215 of file duktape-1.5.2/src-noline/duktape.c.
              :
    DUK_DDD(DUK_DDDPRINT("result: error, internal"));
    if (throw_flag) {
        DUK_ERROR_INTERNAL_DEFMSG(thr);
    }
    duk_pop(ctx);  /* remove key */
    return 0;
}
/*
 *  Ecmascript compliant [[Delete]](P, Throw).
 */
DUK_INTERNAL duk_bool_t duk_hobject_delprop_raw(duk_hthread *thr, duk_hobject *obj, duk_hstring *key, duk_small_uint_t flags) {
    duk_propdesc desc;
    duk_tval *tv;
    duk_uint32_t arr_idx;
    duk_bool_t throw_flag;
    duk_bool_t force_flag;
    throw_flag = (flags & DUK_DELPROP_FLAG_THROW);
    force_flag = (flags & DUK_DELPROP_FLAG_FORCE);
    DUK_DDD(DUK_DDDPRINT("delprop_raw: thr=%p, obj=%p, key=%p, throw=%ld, force=%ld (obj -> %!O, key -> %!O)",
                         (void *) thr, (void *) obj, (void *) key, (long) throw_flag, (long) force_flag,
                         (duk_heaphdr *) obj, (duk_heaphdr *) key));
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT(key != NULL);
    DUK_ASSERT_VALSTACK_SPACE(thr, DUK__VALSTACK_SPACE);
    arr_idx = DUK_HSTRING_GET_ARRIDX_FAST(key);
    /* 0 = don't push current value */
    if (!duk__get_own_propdesc_raw(thr, obj, key, arr_idx, &desc, 0 /*flags*/)) {  /* don't push value */
        DUK_DDD(DUK_DDDPRINT("property not found, succeed always"));
        goto success;
    }
#if defined(DUK_USE_ROM_OBJECTS)
    if (DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) obj)) {
        DUK_DD(DUK_DDPRINT("attempt to delprop on read-only target object"));
        goto fail_not_configurable;
    }
#endif
    if ((desc.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) == 0 && !force_flag) {
        goto fail_not_configurable;
    }
    if (desc.a_idx < 0 && desc.e_idx < 0) {
        /* Currently there are no deletable virtual properties, but
         * with force_flag we might attempt to delete one.
         */
        goto fail_virtual;
    }
    if (desc.a_idx >= 0) {
        DUK_ASSERT(desc.e_idx < 0);
        tv = DUK_HOBJECT_A_GET_VALUE_PTR(thr->heap, obj, desc.a_idx);
        DUK_TVAL_SET_UNUSED_UPDREF(thr, tv);  /* side effects */
        goto success;
    } else {
        duk_hobject *h_get = NULL;
        duk_hobject *h_set = NULL;
        duk_tval tv_tmp;
        DUK_ASSERT(desc.a_idx < 0);
        /* Set property slot to an empty state.  Careful not to invoke
         * any side effects while using desc.e_idx so that it doesn't
         * get invalidated by a finalizer mutating our object.
         */
        /* remove hash entry (no decref) */
#if defined(DUK_USE_HOBJECT_HASH_PART)
        if (desc.h_idx >= 0) {
            duk_uint32_t *h_base = DUK_HOBJECT_H_GET_BASE(thr->heap, obj);
            DUK_DDD(DUK_DDDPRINT("removing hash entry at h_idx %ld", (long) desc.h_idx));
            DUK_ASSERT(DUK_HOBJECT_GET_HSIZE(obj) > 0);
            DUK_ASSERT((duk_uint32_t) desc.h_idx < DUK_HOBJECT_GET_HSIZE(obj));
            h_base[desc.h_idx] = DUK__HASH_DELETED;
        } else {
            DUK_ASSERT(DUK_HOBJECT_GET_HSIZE(obj) == 0);
        }
#else
        DUK_ASSERT(DUK_HOBJECT_GET_HSIZE(obj) == 0);
#endif
        /* remove value */
        DUK_DDD(DUK_DDDPRINT("before removing value, e_idx %ld, key %p, key at slot %p",
                             (long) desc.e_idx, (void *) key, (void *) DUK_HOBJECT_E_GET_KEY(thr->heap, obj, desc.e_idx)));
        DUK_DDD(DUK_DDDPRINT("removing value at e_idx %ld", (long) desc.e_idx));
        DUK_MEMSET((void *) &tv_tmp, 0, sizeof(tv_tmp));
        DUK_TVAL_SET_UNDEFINED(&tv_tmp);
        if (DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, obj, desc.e_idx)) {
            h_get = DUK_HOBJECT_E_GET_VALUE_GETTER(thr->heap, obj, desc.e_idx);
            h_set = DUK_HOBJECT_E_GET_VALUE_SETTER(thr->heap, obj, desc.e_idx);
            DUK_HOBJECT_E_SET_VALUE_GETTER(thr->heap, obj, desc.e_idx, NULL);
            DUK_HOBJECT_E_SET_VALUE_SETTER(thr->heap, obj, desc.e_idx, NULL);
        } else {
            tv = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, obj, desc.e_idx);
            DUK_TVAL_SET_TVAL(&tv_tmp, tv);
            DUK_TVAL_SET_UNDEFINED(tv);
        }
#if 0
        /* Not strictly necessary because if key == NULL, flag MUST be ignored. */
        DUK_HOBJECT_E_SET_FLAGS(thr->heap, obj, desc.e_idx, 0);
#endif
        /* remove key */
        DUK_DDD(DUK_DDDPRINT("before removing key, e_idx %ld, key %p, key at slot %p",
                             (long) desc.e_idx, (void *) key, (void *) DUK_HOBJECT_E_GET_KEY(thr->heap, obj, desc.e_idx)));
        DUK_DDD(DUK_DDDPRINT("removing key at e_idx %ld", (long) desc.e_idx));
        DUK_ASSERT(key == DUK_HOBJECT_E_GET_KEY(thr->heap, obj, desc.e_idx));
        DUK_HOBJECT_E_SET_KEY(thr->heap, obj, desc.e_idx, NULL);
        /* Do decrefs only with safe pointers to avoid side effects
         * disturbing e_idx.
         */
        DUK_TVAL_DECREF(thr, &tv_tmp);
        DUK_HOBJECT_DECREF_ALLOWNULL(thr, h_get);
        DUK_HOBJECT_DECREF_ALLOWNULL(thr, h_set);
        DUK_HSTRING_DECREF(thr, key);
        goto success;
    }
    DUK_UNREACHABLE();
 success:
    /*
     *  Argument exotic [[Delete]] behavior (E5 Section 10.6) is
     *  a post-check, keeping arguments internal 'map' in sync with
     *  any successful deletes (note that property does not need to
     *  exist for delete to 'succeed').
     *
     *  Delete key from 'map'.  Since 'map' only contains array index
     *  keys, we can use arr_idx for a fast skip.
     */
    DUK_DDD(DUK_DDDPRINT("delete successful, check for arguments exotic behavior"));
    if (arr_idx != DUK__NO_ARRAY_INDEX && DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS(obj)) {
        /* Note: only numbered indices are relevant, so arr_idx fast reject
         * is good (this is valid unless there are more than 4**32-1 arguments).
         */
        DUK_DDD(DUK_DDDPRINT("delete successful, arguments exotic behavior needed"));
        /* Note: we can reuse 'desc' here */
        (void) duk__check_arguments_map_for_delete(thr, obj, key, &desc);
    }
    DUK_DDD(DUK_DDDPRINT("delete successful"));
    return 1;
References duk_propdesc::a_idx, duk__check_arguments_map_for_delete(), duk__get_own_propdesc_raw(), DUK__HASH_DELETED, DUK__NO_ARRAY_INDEX, DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, DUK_DD, DUK_DDD, DUK_DDDPRINT, DUK_DDPRINT, DUK_DELPROP_FLAG_FORCE, DUK_DELPROP_FLAG_THROW, DUK_ERROR_TYPE, DUK_HEAPHDR_HAS_READONLY, DUK_HOBJECT_A_GET_VALUE_PTR, DUK_HOBJECT_DECREF_ALLOWNULL, DUK_HOBJECT_E_GET_KEY, DUK_HOBJECT_E_GET_VALUE_GETTER, DUK_HOBJECT_E_GET_VALUE_SETTER, DUK_HOBJECT_E_GET_VALUE_TVAL_PTR, DUK_HOBJECT_E_SET_FLAGS, DUK_HOBJECT_E_SET_KEY, DUK_HOBJECT_E_SET_VALUE_GETTER, DUK_HOBJECT_E_SET_VALUE_SETTER, DUK_HOBJECT_E_SLOT_IS_ACCESSOR, DUK_HOBJECT_GET_HSIZE, DUK_HOBJECT_H_GET_BASE, DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS, DUK_HSTRING_DECREF, DUK_HSTRING_GET_ARRIDX_FAST, DUK_MEMSET, DUK_PROPDESC_FLAG_CONFIGURABLE, DUK_STR_NOT_CONFIGURABLE, DUK_STR_PROPERTY_IS_VIRTUAL, DUK_TVAL_DECREF, DUK_TVAL_SET_TVAL, DUK_TVAL_SET_UNDEFINED, DUK_TVAL_SET_UNUSED_UPDREF, DUK_UNREACHABLE, duk_propdesc::e_idx, duk_propdesc::flags, duk_propdesc::h_idx, duk_hthread::heap, and NULL.
Referenced by duk__check_arguments_map_for_delete(), duk__delvar_helper(), duk__handle_put_array_length_smaller(), duk_hobject_define_property_helper(), duk_hobject_delprop(), and duk_hthread_create_builtin_objects().
duk_hobject_enumerator_create()
DUK_INTERNAL_DECL void duk_hobject_enumerator_create (duk_context * ctx, duk_small_uint_t enum_flags)
Definition at line 46200 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *enum_target;
    duk_hobject *curr;
    duk_hobject *res;
#if defined(DUK_USE_ES6_PROXY)
    duk_hobject *h_proxy_target;
    duk_hobject *h_proxy_handler;
    duk_hobject *h_trap_result;
#endif
    duk_uint_fast32_t i, len;  /* used for array, stack, and entry indices */
    DUK_ASSERT(ctx != NULL);
    DUK_DDD(DUK_DDDPRINT("create enumerator, stack top: %ld", (long) duk_get_top(ctx)));
    enum_target = duk_require_hobject(ctx, -1);
    DUK_ASSERT(enum_target != NULL);
    duk_push_object_internal(ctx);
    res = duk_require_hobject(ctx, -1);
    DUK_DDD(DUK_DDDPRINT("created internal object"));
    /* [enum_target res] */
    /* Target must be stored so that we can recheck whether or not
     * keys still exist when we enumerate.  This is not done if the
     * enumeration result comes from a proxy trap as there is no
     * real object to check against.
     */
    duk_push_hobject(ctx, enum_target);
    duk_put_prop_stridx(ctx, -2, DUK_STRIDX_INT_TARGET);
    /* Initialize index so that we skip internal control keys. */
    duk_push_int(ctx, DUK__ENUM_START_INDEX);
    duk_put_prop_stridx(ctx, -2, DUK_STRIDX_INT_NEXT);
    /*
     *  Proxy object handling
     */
#if defined(DUK_USE_ES6_PROXY)
    if (DUK_LIKELY((enum_flags & DUK_ENUM_NO_PROXY_BEHAVIOR) != 0)) {
        goto skip_proxy;
    }
    if (DUK_LIKELY(!duk_hobject_proxy_check(thr,
                                            enum_target,
                                            &h_proxy_target,
                                            &h_proxy_handler))) {
        goto skip_proxy;
    }
    DUK_DDD(DUK_DDDPRINT("proxy enumeration"));
    duk_push_hobject(ctx, h_proxy_handler);
    if (!duk_get_prop_stridx(ctx, -1, DUK_STRIDX_ENUMERATE)) {
        /* No need to replace the 'enum_target' value in stack, only the
         * enum_target reference.  This also ensures that the original
         * enum target is reachable, which keeps the proxy and the proxy
         * target reachable.  We do need to replace the internal _Target.
         */
        DUK_DDD(DUK_DDDPRINT("no enumerate trap, enumerate proxy target instead"));
        DUK_DDD(DUK_DDDPRINT("h_proxy_target=%!O", (duk_heaphdr *) h_proxy_target));
        enum_target = h_proxy_target;
        duk_push_hobject(ctx, enum_target);  /* -> [ ... enum_target res handler undefined target ] */
        duk_put_prop_stridx(ctx, -4, DUK_STRIDX_INT_TARGET);
        duk_pop_2(ctx);  /* -> [ ... enum_target res ] */
        goto skip_proxy;
    }
    /* [ ... enum_target res handler trap ] */
    duk_insert(ctx, -2);
    duk_push_hobject(ctx, h_proxy_target);    /* -> [ ... enum_target res trap handler target ] */
    duk_call_method(ctx, 1 /*nargs*/);        /* -> [ ... enum_target res trap_result ] */
    h_trap_result = duk_require_hobject(ctx, -1);
    DUK_UNREF(h_trap_result);
    /* Copy trap result keys into the enumerator object. */
    len = (duk_uint_fast32_t) duk_get_length(ctx, -1);
    for (i = 0; i < len; i++) {
        /* XXX: not sure what the correct semantic details are here,
         * e.g. handling of missing values (gaps), handling of non-array
         * trap results, etc.
         *
         * For keys, we simply skip non-string keys which seems to be
         * consistent with how e.g. Object.keys() will process proxy trap
         * results (ES6, Section 19.1.2.14).
         */
        if (duk_get_prop_index(ctx, -1, i) && duk_is_string(ctx, -1)) {
            /* [ ... enum_target res trap_result val ] */
            duk_push_true(ctx);
            /* [ ... enum_target res trap_result val true ] */
            duk_put_prop(ctx, -4);
        } else {
            duk_pop(ctx);
        }
    }
    /* [ ... enum_target res trap_result ] */
    duk_pop(ctx);
    duk_remove(ctx, -2);
    /* [ ... res ] */
    /* The internal _Target property is kept pointing to the original
     * enumeration target (the proxy object), so that the enumerator
     * 'next' operation can read property values if so requested.  The
     * fact that the _Target is a proxy disables key existence check
     * during enumeration.
     */
    DUK_DDD(DUK_DDDPRINT("proxy enumeration, final res: %!O", (duk_heaphdr *) res));
    goto compact_and_return;
 skip_proxy:
#endif  /* DUK_USE_ES6_PROXY */
    curr = enum_target;
    while (curr) {
        /*
         *  Virtual properties.
         *
         *  String and buffer indices are virtual and always enumerable,
         *  'length' is virtual and non-enumerable.  Array and arguments
         *  object props have special behavior but are concrete.
         */
        if (DUK_HOBJECT_HAS_EXOTIC_STRINGOBJ(curr) ||
            DUK_HOBJECT_IS_BUFFEROBJECT(curr)) {
            /* String and buffer enumeration behavior is identical now,
             * so use shared handler.
             */
            if (DUK_HOBJECT_HAS_EXOTIC_STRINGOBJ(curr)) {
                duk_hstring *h_val;
                h_val = duk_hobject_get_internal_value_string(thr->heap, curr);
                DUK_ASSERT(h_val != NULL);  /* string objects must not created without internal value */
                len = (duk_uint_fast32_t) DUK_HSTRING_GET_CHARLEN(h_val);
            } else {
                duk_hbufferobject *h_bufobj;
                DUK_ASSERT(DUK_HOBJECT_IS_BUFFEROBJECT(curr));
                h_bufobj = (duk_hbufferobject *) curr;
                if (h_bufobj == NULL) {
                    /* Neutered buffer, zero length seems
                     * like good behavior here.
                     */
                    len = 0;
                } else {
                    /* There's intentionally no check for
                     * current underlying buffer length.
                     */
                    len = (duk_uint_fast32_t) (h_bufobj->length >> h_bufobj->shift);
                }
            }
            for (i = 0; i < len; i++) {
                duk_hstring *k;
                k = duk_heap_string_intern_u32_checked(thr, i);
                DUK_ASSERT(k);
                duk_push_hstring(ctx, k);
                duk_push_true(ctx);
                /* [enum_target res key true] */
                duk_put_prop(ctx, -3);
                /* [enum_target res] */
            }
            /* 'length' and other virtual properties are not
             * enumerable, but are included if non-enumerable
             * properties are requested.
             */
            if (enum_flags & DUK_ENUM_INCLUDE_NONENUMERABLE) {
                duk_uint_fast32_t n;
                if (DUK_HOBJECT_IS_BUFFEROBJECT(curr)) {
                    n = sizeof(duk__bufferobject_virtual_props) / sizeof(duk_uint16_t);
                } else {
                    DUK_ASSERT(DUK_HOBJECT_HAS_EXOTIC_STRINGOBJ(curr));
                    DUK_ASSERT(duk__bufferobject_virtual_props[0] == DUK_STRIDX_LENGTH);
                    n = 1;  /* only 'length' */
                }
                for (i = 0; i < n; i++) {
                    duk_push_hstring_stridx(ctx, duk__bufferobject_virtual_props[i]);
                    duk_push_true(ctx);
                    duk_put_prop(ctx, -3);
                }
            }
        } else if (DUK_HOBJECT_HAS_EXOTIC_DUKFUNC(curr)) {
            if (enum_flags & DUK_ENUM_INCLUDE_NONENUMERABLE) {
                duk_push_hstring_stridx(ctx, DUK_STRIDX_LENGTH);
                duk_push_true(ctx);
                duk_put_prop(ctx, -3);
            }
        }
        /*
         *  Array part
         *
         *  Note: ordering between array and entry part must match 'abandon array'
         *  behavior in duk_hobject_props.c: key order after an array is abandoned
         *  must be the same.
         */
        for (i = 0; i < (duk_uint_fast32_t) DUK_HOBJECT_GET_ASIZE(curr); i++) {
            duk_hstring *k;
            duk_tval *tv;
            tv = DUK_HOBJECT_A_GET_VALUE_PTR(thr->heap, curr, i);
            if (DUK_TVAL_IS_UNUSED(tv)) {
                continue;
            }
            k = duk_heap_string_intern_u32_checked(thr, i);
            DUK_ASSERT(k);
            duk_push_hstring(ctx, k);
            duk_push_true(ctx);
            /* [enum_target res key true] */
            duk_put_prop(ctx, -3);
            /* [enum_target res] */
        }
        /*
         *  Entries part
         */
        for (i = 0; i < (duk_uint_fast32_t) DUK_HOBJECT_GET_ENEXT(curr); i++) {
            duk_hstring *k;
            k = DUK_HOBJECT_E_GET_KEY(thr->heap, curr, i);
            if (!k) {
                continue;
            }
            if (!DUK_HOBJECT_E_SLOT_IS_ENUMERABLE(thr->heap, curr, i) &&
                !(enum_flags & DUK_ENUM_INCLUDE_NONENUMERABLE)) {
                continue;
            }
            if (DUK_HSTRING_HAS_INTERNAL(k) &&
                !(enum_flags & DUK_ENUM_INCLUDE_INTERNAL)) {
                continue;
            }
            if ((enum_flags & DUK_ENUM_ARRAY_INDICES_ONLY) &&
                (DUK_HSTRING_GET_ARRIDX_SLOW(k) == DUK_HSTRING_NO_ARRAY_INDEX)) {
                continue;
            }
            DUK_ASSERT(DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, curr, i) ||
                       !DUK_TVAL_IS_UNUSED(&DUK_HOBJECT_E_GET_VALUE_PTR(thr->heap, curr, i)->v));
            duk_push_hstring(ctx, k);
            duk_push_true(ctx);
            /* [enum_target res key true] */
            duk_put_prop(ctx, -3);
            /* [enum_target res] */
        }
        if (enum_flags & DUK_ENUM_OWN_PROPERTIES_ONLY) {
            break;
        }
        curr = DUK_HOBJECT_GET_PROTOTYPE(thr->heap, curr);
    }
    /* [enum_target res] */
    duk_remove(ctx, -2);
    /* [res] */
    if ((enum_flags & (DUK_ENUM_ARRAY_INDICES_ONLY | DUK_ENUM_SORT_ARRAY_INDICES)) ==
                      (DUK_ENUM_ARRAY_INDICES_ONLY | DUK_ENUM_SORT_ARRAY_INDICES)) {
        /*
         *  Some E5/E5.1 algorithms require that array indices are iterated
         *  in a strictly ascending order.  This is the case for e.g.
         *  Array.prototype.forEach() and JSON.stringify() PropertyList
         *  handling.
         *
         *  To ensure this property for arrays with an array part (and
         *  arbitrary objects too, since e.g. forEach() can be applied
         *  to an array), the caller can request that we sort the keys
         *  here.
         */
        /* XXX: avoid this at least when enum_target is an Array, it has an
         * array part, and no ancestor properties were included?  Not worth
References duk__bufferobject_virtual_props, DUK__ENUM_START_INDEX, duk__sort_array_indices(), DUK_ASSERT, duk_call_method(), DUK_DDD, DUK_DDDPRINT, DUK_ENUM_ARRAY_INDICES_ONLY, DUK_ENUM_INCLUDE_INTERNAL, DUK_ENUM_INCLUDE_NONENUMERABLE, DUK_ENUM_NO_PROXY_BEHAVIOR, DUK_ENUM_OWN_PROPERTIES_ONLY, DUK_ENUM_SORT_ARRAY_INDICES, duk_get_length(), duk_get_prop_index(), duk_get_prop_stridx(), duk_get_top(), duk_get_tval(), duk_heap_string_intern_u32_checked(), DUK_HOBJECT_A_GET_VALUE_PTR, duk_hobject_compact_props(), DUK_HOBJECT_E_GET_KEY, DUK_HOBJECT_E_GET_VALUE_PTR, DUK_HOBJECT_E_SLOT_IS_ACCESSOR, DUK_HOBJECT_E_SLOT_IS_ENUMERABLE, DUK_HOBJECT_GET_ASIZE, DUK_HOBJECT_GET_ENEXT, duk_hobject_get_internal_value_string(), DUK_HOBJECT_GET_PROTOTYPE, DUK_HOBJECT_HAS_EXOTIC_DUKFUNC, DUK_HOBJECT_HAS_EXOTIC_STRINGOBJ, DUK_HOBJECT_IS_BUFFEROBJECT, duk_hobject_proxy_check(), DUK_HSTRING_GET_ARRIDX_SLOW, DUK_HSTRING_GET_CHARLEN, DUK_HSTRING_HAS_INTERNAL, DUK_HSTRING_NO_ARRAY_INDEX, duk_insert(), duk_is_string(), DUK_LIKELY, duk_pop(), duk_pop_2(), duk_push_hobject(), duk_push_hstring(), duk_push_hstring_stridx(), duk_push_int(), duk_push_object_internal(), duk_push_true(), duk_put_prop(), duk_put_prop_stridx(), duk_remove(), duk_require_hobject(), DUK_STRIDX_ENUMERATE, DUK_STRIDX_INT_NEXT, DUK_STRIDX_INT_TARGET, DUK_STRIDX_LENGTH, DUK_TVAL_IS_UNUSED, DUK_UNREF, duk_hthread::heap, duk_hbufferobject::length, NULL, and duk_hbufferobject::shift.
Referenced by duk__js_execute_bytecode_inner(), duk_enum(), and duk_hobject_get_enumerated_keys().
duk_hobject_enumerator_next()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_enumerator_next (duk_context * ctx, duk_bool_t get_value)
Definition at line 46518 of file duktape-1.5.2/src-noline/duktape.c.
                   :
#endif
    /* compact; no need to seal because object is internal */
    duk_hobject_compact_props(thr, res);
    DUK_DDD(DUK_DDDPRINT("created enumerator object: %!iT", (duk_tval *) duk_get_tval(ctx, -1)));
}
/*
 *  Returns non-zero if a key and/or value was enumerated, and:
 *
 *   [enum] -> [key]        (get_value == 0)
 *   [enum] -> [key value]  (get_value == 1)
 *
 *  Returns zero without pushing anything on the stack otherwise.
 */
DUK_INTERNAL duk_bool_t duk_hobject_enumerator_next(duk_context *ctx, duk_bool_t get_value) {
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *e;
    duk_hobject *enum_target;
    duk_hstring *res = NULL;
    duk_uint_fast32_t idx;
    duk_bool_t check_existence;
    DUK_ASSERT(ctx != NULL);
    /* [... enum] */
    e = duk_require_hobject(ctx, -1);
    /* XXX use get tval ptr, more efficient */
    duk_get_prop_stridx(ctx, -1, DUK_STRIDX_INT_NEXT);
    idx = (duk_uint_fast32_t) duk_require_uint(ctx, -1);
    duk_pop(ctx);
    DUK_DDD(DUK_DDDPRINT("enumeration: index is: %ld", (long) idx));
    /* Enumeration keys are checked against the enumeration target (to see
     * that they still exist).  In the proxy enumeration case _Target will
     * be the proxy, and checking key existence against the proxy is not
     * required (or sensible, as the keys may be fully virtual).
     */
    duk_get_prop_stridx(ctx, -1, DUK_STRIDX_INT_TARGET);
    enum_target = duk_require_hobject(ctx, -1);
    DUK_ASSERT(enum_target != NULL);
#if defined(DUK_USE_ES6_PROXY)
    check_existence = (!DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ(enum_target));
#else
    check_existence = 1;
#endif
    duk_pop(ctx);  /* still reachable */
    DUK_DDD(DUK_DDDPRINT("getting next enum value, enum_target=%!iO, enumerator=%!iT",
                         (duk_heaphdr *) enum_target, (duk_tval *) duk_get_tval(ctx, -1)));
    /* no array part */
    for (;;) {
        duk_hstring *k;
        if (idx >= DUK_HOBJECT_GET_ENEXT(e)) {
            DUK_DDD(DUK_DDDPRINT("enumeration: ran out of elements"));
            break;
        }
        /* we know these because enum objects are internally created */
        k = DUK_HOBJECT_E_GET_KEY(thr->heap, e, idx);
        DUK_ASSERT(k != NULL);
        DUK_ASSERT(!DUK_HOBJECT_E_SLOT_IS_ACCESSOR(thr->heap, e, idx));
        DUK_ASSERT(!DUK_TVAL_IS_UNUSED(&DUK_HOBJECT_E_GET_VALUE(thr->heap, e, idx).v));
        idx++;
        /* recheck that the property still exists */
        if (check_existence && !duk_hobject_hasprop_raw(thr, enum_target, k)) {
            DUK_DDD(DUK_DDDPRINT("property deleted during enumeration, skip"));
            continue;
        }
        DUK_DDD(DUK_DDDPRINT("enumeration: found element, key: %!O", (duk_heaphdr *) k));
        res = k;
        break;
    }
    DUK_DDD(DUK_DDDPRINT("enumeration: updating next index to %ld", (long) idx));
    duk_push_u32(ctx, (duk_uint32_t) idx);
    duk_put_prop_stridx(ctx, -2, DUK_STRIDX_INT_NEXT);
    /* [... enum] */
References DUK_ASSERT, DUK_DDD, DUK_DDDPRINT, duk_dup(), duk_get_prop(), duk_get_prop_stridx(), duk_get_tval(), DUK_HOBJECT_E_GET_KEY, DUK_HOBJECT_E_GET_VALUE, DUK_HOBJECT_E_SLOT_IS_ACCESSOR, DUK_HOBJECT_GET_ENEXT, DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ, duk_hobject_hasprop_raw(), duk_pop(), duk_push_hobject(), duk_push_hstring(), duk_push_u32, duk_put_prop_stridx(), duk_remove(), duk_require_hobject(), duk_require_uint(), DUK_STRIDX_INT_NEXT, DUK_STRIDX_INT_TARGET, DUK_TVAL_IS_UNUSED, duk_hthread::heap, and NULL.
Referenced by duk__js_execute_bytecode_inner(), and duk_next().
duk_hobject_find_existing_array_entry_tval_ptr()
DUK_INTERNAL_DECL duk_tval * duk_hobject_find_existing_array_entry_tval_ptr (duk_heap * heap, duk_hobject * obj, duk_uarridx_t i)
Definition at line 48300 of file duktape-1.5.2/src-noline/duktape.c.
{
        *out_attrs = DUK_HOBJECT_E_GET_FLAGS(heap, obj, e_idx);
        return DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(heap, obj, e_idx);
    } else {
        *out_attrs = 0;
        return NULL;
    }
}
References DUK_ASSERT, DUK_HOBJECT_A_GET_VALUE_PTR, DUK_HOBJECT_GET_ASIZE, DUK_HOBJECT_HAS_ARRAY_PART, DUK_UNREF, and NULL.
Referenced by duk__convert_to_func_template().
duk_hobject_find_existing_entry()
DUK_INTERNAL_DECL void duk_hobject_find_existing_entry (duk_heap * heap, duk_hobject * obj, duk_hstring * key, duk_int_t * e_idx, duk_int_t * h_idx)
Definition at line 48179 of file duktape-1.5.2/src-noline/duktape.c.
{
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT(key != NULL);
    DUK_ASSERT(e_idx != NULL);
    DUK_ASSERT(h_idx != NULL);
    DUK_UNREF(heap);
    if (DUK_LIKELY(DUK_HOBJECT_GET_HSIZE(obj) == 0))
    {
        /* Linear scan: more likely because most objects are small.
         * This is an important fast path.
         *
         * XXX: this might be worth inlining for property lookups.
         */
        duk_uint_fast32_t i;
        duk_uint_fast32_t n;
        duk_hstring **h_keys_base;
        DUK_DDD(DUK_DDDPRINT("duk_hobject_find_existing_entry() using linear scan for lookup"));
        h_keys_base = DUK_HOBJECT_E_GET_KEY_BASE(heap, obj);
        n = DUK_HOBJECT_GET_ENEXT(obj);
        for (i = 0; i < n; i++) {
            if (h_keys_base[i] == key) {
                *e_idx = i;
                *h_idx = -1;
                return;
            }
        }
    }
#if defined(DUK_USE_HOBJECT_HASH_PART)
    else
    {
        /* hash lookup */
        duk_uint32_t n;
        duk_uint32_t i, step;
        duk_uint32_t *h_base;
        DUK_DDD(DUK_DDDPRINT("duk_hobject_find_existing_entry() using hash part for lookup"));
        h_base = DUK_HOBJECT_H_GET_BASE(heap, obj);
        n = DUK_HOBJECT_GET_HSIZE(obj);
        i = DUK__HASH_INITIAL(DUK_HSTRING_GET_HASH(key), n);
        step = DUK__HASH_PROBE_STEP(DUK_HSTRING_GET_HASH(key));
        for (;;) {
            duk_uint32_t t;
            DUK_ASSERT_DISABLE(i >= 0);  /* unsigned */
            DUK_ASSERT(i < DUK_HOBJECT_GET_HSIZE(obj));
            t = h_base[i];
            DUK_ASSERT(t == DUK__HASH_UNUSED || t == DUK__HASH_DELETED ||
                       (t < DUK_HOBJECT_GET_ESIZE(obj)));  /* t >= 0 always true, unsigned */
            if (t == DUK__HASH_UNUSED) {
                break;
            } else if (t == DUK__HASH_DELETED) {
                DUK_DDD(DUK_DDDPRINT("lookup miss (deleted) i=%ld, t=%ld",
                                     (long) i, (long) t));
            } else {
                DUK_ASSERT(t < DUK_HOBJECT_GET_ESIZE(obj));
                if (DUK_HOBJECT_E_GET_KEY(heap, obj, t) == key) {
                    DUK_DDD(DUK_DDDPRINT("lookup hit i=%ld, t=%ld -> key %p",
                                         (long) i, (long) t, (void *) key));
                    *e_idx = t;
                    *h_idx = i;
References DUK__HASH_DELETED, DUK__HASH_INITIAL, DUK__HASH_PROBE_STEP, DUK__HASH_UNUSED, DUK_ASSERT, DUK_ASSERT_DISABLE, DUK_DDD, DUK_DDDPRINT, DUK_HOBJECT_E_GET_KEY, DUK_HOBJECT_E_GET_KEY_BASE, DUK_HOBJECT_GET_ENEXT, DUK_HOBJECT_GET_ESIZE, DUK_HOBJECT_GET_HSIZE, DUK_HOBJECT_H_GET_BASE, DUK_HSTRING_GET_HASH, DUK_LIKELY, DUK_UNREF, and NULL.
Referenced by duk__declvar_helper(), duk__get_own_propdesc_raw(), duk_hobject_define_accessor_internal(), duk_hobject_find_existing_entry_tval_ptr(), duk_hobject_find_existing_entry_tval_ptr_and_attrs(), and duk_hobject_get_internal_value().
duk_hobject_find_existing_entry_tval_ptr()
DUK_INTERNAL_DECL duk_tval * duk_hobject_find_existing_entry_tval_ptr (duk_heap * heap, duk_hobject * obj, duk_hstring * key)
Definition at line 48263 of file duktape-1.5.2/src-noline/duktape.c.
References DUK_ASSERT, DUK_HOBJECT_E_GET_VALUE_TVAL_PTR, DUK_HOBJECT_E_SLOT_IS_ACCESSOR, duk_hobject_find_existing_entry(), DUK_UNREF, and NULL.
Referenced by duk__declvar_helper(), duk__dump_buffer_prop(), duk__dump_formals(), duk__dump_string_prop(), duk__dump_uint32_prop(), duk__dump_varmap(), duk__err_augment_user(), duk__get_identifier_reference(), duk__getid_activation_regs(), duk__getid_open_decl_env_regs(), duk__handle_oldenv_for_call(), duk_create_activation_environment_record(), duk_hobject_proxy_check(), and duk_hthread_callstack_unwind().
duk_hobject_find_existing_entry_tval_ptr_and_attrs()
DUK_INTERNAL_DECL duk_tval * duk_hobject_find_existing_entry_tval_ptr_and_attrs (duk_heap * heap, duk_hobject * obj, duk_hstring * key, duk_int_t * out_attrs)
Definition at line 48280 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_int_t e_idx;
    duk_int_t h_idx;
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT(key != NULL);
    DUK_UNREF(heap);
    duk_hobject_find_existing_entry(heap, obj, key, &e_idx, &h_idx);
    if (e_idx >= 0 && !DUK_HOBJECT_E_SLOT_IS_ACCESSOR(heap, obj, e_idx)) {
        return DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(heap, obj, e_idx);
    } else {
        return NULL;
    }
}
/* For internal use: get non-accessor entry value and attributes */
DUK_INTERNAL duk_tval *duk_hobject_find_existing_entry_tval_ptr_and_attrs(duk_heap *heap, duk_hobject *obj, duk_hstring *key, duk_int_t *out_attrs) {
References DUK_ASSERT, DUK_HOBJECT_E_GET_FLAGS, DUK_HOBJECT_E_GET_VALUE_TVAL_PTR, DUK_HOBJECT_E_SLOT_IS_ACCESSOR, duk_hobject_find_existing_entry(), DUK_UNREF, and NULL.
Referenced by duk__get_identifier_reference().
duk_hobject_get_enumerated_keys()
DUK_INTERNAL_DECL duk_ret_t duk_hobject_get_enumerated_keys (duk_context * ctx, duk_small_uint_t enum_flags)
Definition at line 46614 of file duktape-1.5.2/src-noline/duktape.c.
               {
            duk_remove(ctx, -2);   /* -> [... key] */
        }
        return 1;
    } else {
        duk_pop(ctx);  /* -> [...] */
        return 0;
    }
}
/*
 *  Get enumerated keys in an Ecmascript array.  Matches Object.keys() behavior
 *  described in E5 Section 15.2.3.14.
 */
DUK_INTERNAL duk_ret_t duk_hobject_get_enumerated_keys(duk_context *ctx, duk_small_uint_t enum_flags) {
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *e;
    duk_uint_fast32_t i;
    duk_uint_fast32_t idx;
    DUK_ASSERT(ctx != NULL);
    DUK_ASSERT(duk_get_hobject(ctx, -1) != NULL);
    DUK_UNREF(thr);
    /* Create a temporary enumerator to get the (non-duplicated) key list;
     * the enumerator state is initialized without being needed, but that
     * has little impact.
     */
    duk_hobject_enumerator_create(ctx, enum_flags);
    duk_push_array(ctx);
    /* [enum_target enum res] */
    e = duk_require_hobject(ctx, -2);
    DUK_ASSERT(e != NULL);
    idx = 0;
    for (i = DUK__ENUM_START_INDEX; i < (duk_uint_fast32_t) DUK_HOBJECT_GET_ENEXT(e); i++) {
        duk_hstring *k;
References DUK__ENUM_START_INDEX, DUK_ASSERT, duk_get_hobject(), DUK_HOBJECT_E_GET_KEY, duk_hobject_enumerator_create(), DUK_HOBJECT_GET_ENEXT, duk_push_array(), duk_push_hstring(), duk_put_prop_index(), duk_remove(), duk_require_hobject(), DUK_UNREF, duk_hthread::heap, and NULL.
Referenced by duk__enc_object(), and duk_bi_object_constructor_keys_shared().
duk_hobject_get_internal_value()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_get_internal_value (duk_heap * heap, duk_hobject * obj, duk_tval * tv)
Definition at line 48403 of file duktape-1.5.2/src-noline/duktape.c.
{
References DUK_ASSERT, DUK_HEAP_STRING_INT_VALUE, DUK_HOBJECT_E_GET_VALUE_TVAL_PTR, DUK_HOBJECT_E_SLOT_IS_ACCESSOR, duk_hobject_find_existing_entry(), DUK_TVAL_SET_TVAL, DUK_TVAL_SET_UNDEFINED, and NULL.
Referenced by duk_hobject_get_internal_value_string().
duk_hobject_get_internal_value_string()
DUK_INTERNAL_DECL duk_hstring * duk_hobject_get_internal_value_string (duk_heap * heap, duk_hobject * obj)
Definition at line 48422 of file duktape-1.5.2/src-noline/duktape.c.
                    {
        DUK_ASSERT(!DUK_HOBJECT_E_SLOT_IS_ACCESSOR(heap, obj, e_idx));
        DUK_TVAL_SET_TVAL(tv_out, DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(heap, obj, e_idx));
        return 1;
    }
    DUK_TVAL_SET_UNDEFINED(tv_out);
    return 0;
}
DUK_INTERNAL duk_hstring *duk_hobject_get_internal_value_string(duk_heap *heap, duk_hobject *obj) {
    duk_tval tv;
References DUK_ASSERT, duk_hobject_get_internal_value(), DUK_MEMZERO, DUK_TVAL_GET_STRING, DUK_TVAL_IS_STRING, and NULL.
Referenced by duk__get_own_propdesc_raw(), and duk_hobject_enumerator_create().
duk_hobject_get_length()
DUK_INTERNAL_DECL duk_uint32_t duk_hobject_get_length (duk_hthread * thr, duk_hobject * obj)
Definition at line 51823 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_context *ctx = (duk_context *) thr;
    duk_push_hobject(ctx, obj);
    duk_push_hstring_stridx(ctx, DUK_STRIDX_LENGTH);
    duk_push_u32(ctx, length);
    (void) duk_hobject_putprop(thr,
                               DUK_GET_TVAL_NEGIDX(ctx, -3),
                               DUK_GET_TVAL_NEGIDX(ctx, -2),
                               DUK_GET_TVAL_NEGIDX(ctx, -1),
                               0);
    duk_pop_n(ctx, 3);
}
DUK_INTERNAL void duk_hobject_set_length_zero(duk_hthread *thr, duk_hobject *obj) {
    duk_hobject_set_length(thr, obj, 0);
References DUK_DOUBLE_2TO32, DUK_GET_TVAL_NEGIDX, duk_hobject_getprop(), duk_hobject_putprop(), duk_pop_n(), duk_push_hobject(), duk_push_hstring_stridx(), duk_push_u32, DUK_STRIDX_LENGTH, and duk_to_number().
Referenced by duk__convert_to_func_template(), and duk_get_length().
duk_hobject_get_own_propdesc()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_get_own_propdesc (duk_hthread * thr, duk_hobject * obj, duk_hstring * key, duk_propdesc * out_desc, duk_small_uint_t flags)
Definition at line 48945 of file duktape-1.5.2/src-noline/duktape.c.
{
            DUK_DDD(DUK_DDDPRINT("-> arguments exotic behavior overrides result: %!T -> %!T",
                                 (duk_tval *) duk_get_tval(ctx, -2),
                                 (duk_tval *) duk_get_tval(ctx, -1)));
References duk__get_own_propdesc_raw(), DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, DUK_HSTRING_GET_ARRIDX_SLOW, and NULL.
Referenced by duk__check_arguments_map_for_delete(), duk__lookup_arguments_map(), duk_hobject_object_get_own_property_descriptor(), and duk_hobject_object_ownprop_helper().
duk_hobject_getprop()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_getprop (duk_hthread * thr, duk_tval * tv_obj, duk_tval * tv_key)
Definition at line 49284 of file duktape-1.5.2/src-noline/duktape.c.
{
        data = (duk_uint8_t *) DUK_HBUFFER_GET_DATA_PTR(thr->heap, h_bufobj->buf) + h_bufobj->offset + byte_off;
        duk_hbufferobject_validated_write(ctx, h_bufobj, data, elem_size);
    } else {
        DUK_D(DUK_DPRINT("bufferobject access out of underlying buffer, ignoring (write skipped)"));
    }
    duk_pop(ctx);
    return 1;
}
/*
 *  GETPROP: Ecmascript property read.
 */
DUK_INTERNAL duk_bool_t duk_hobject_getprop(duk_hthread *thr, duk_tval *tv_obj, duk_tval *tv_key) {
    duk_context *ctx = (duk_context *) thr;
    duk_tval tv_obj_copy;
    duk_tval tv_key_copy;
    duk_hobject *curr = NULL;
    duk_hstring *key = NULL;
    duk_uint32_t arr_idx = DUK__NO_ARRAY_INDEX;
    duk_propdesc desc;
    duk_uint_t sanity;
    DUK_DDD(DUK_DDDPRINT("getprop: thr=%p, obj=%p, key=%p (obj -> %!T, key -> %!T)",
                         (void *) thr, (void *) tv_obj, (void *) tv_key,
                         (duk_tval *) tv_obj, (duk_tval *) tv_key));
    DUK_ASSERT(ctx != NULL);
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(tv_obj != NULL);
    DUK_ASSERT(tv_key != NULL);
    DUK_ASSERT_VALSTACK_SPACE(thr, DUK__VALSTACK_SPACE);
    /*
     *  Make a copy of tv_obj, tv_key, and tv_val to avoid any issues of
     *  them being invalidated by a valstack resize.
     *
     *  XXX: this is now an overkill for many fast paths.  Rework this
     *  to be faster (although switching to a valstack discipline might
     *  be a better solution overall).
     */
    DUK_TVAL_SET_TVAL(&tv_obj_copy, tv_obj);
    DUK_TVAL_SET_TVAL(&tv_key_copy, tv_key);
    tv_obj = &tv_obj_copy;
    tv_key = &tv_key_copy;
    /*
     *  Coercion and fast path processing
     */
    switch (DUK_TVAL_GET_TAG(tv_obj)) {
    case DUK_TAG_UNDEFINED:
    case DUK_TAG_NULL: {
        /* Note: unconditional throw */
        DUK_DDD(DUK_DDDPRINT("base object is undefined or null -> reject"));
#if defined(DUK_USE_PARANOID_ERRORS)
        DUK_ERROR_TYPE(thr, DUK_STR_INVALID_BASE);
#else
        DUK_ERROR_FMT2(thr, DUK_ERR_TYPE_ERROR, "cannot read property %s of %s",
                       duk_push_string_tval_readable(ctx, tv_key), duk_push_string_tval_readable(ctx, tv_obj));
#endif
        return 0;
    }
    case DUK_TAG_BOOLEAN: {
        DUK_DDD(DUK_DDDPRINT("base object is a boolean, start lookup from boolean prototype"));
        curr = thr->builtins[DUK_BIDX_BOOLEAN_PROTOTYPE];
        break;
    }
    case DUK_TAG_STRING: {
        duk_hstring *h = DUK_TVAL_GET_STRING(tv_obj);
        duk_int_t pop_count;
#if defined(DUK_USE_FASTINT)
        if (DUK_TVAL_IS_FASTINT(tv_key)) {
            arr_idx = duk__tval_fastint_to_arr_idx(tv_key);
            DUK_DDD(DUK_DDDPRINT("base object string, key is a fast-path fastint; arr_idx %ld", (long) arr_idx));
            pop_count = 0;
        } else
#endif
        if (DUK_TVAL_IS_NUMBER(tv_key)) {
            arr_idx = duk__tval_number_to_arr_idx(tv_key);
            DUK_DDD(DUK_DDDPRINT("base object string, key is a fast-path number; arr_idx %ld", (long) arr_idx));
            pop_count = 0;
        } else {
            arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
            DUK_ASSERT(key != NULL);
            DUK_DDD(DUK_DDDPRINT("base object string, key is a non-fast-path number; after "
                                 "coercion key is %!T, arr_idx %ld",
                                 (duk_tval *) duk_get_tval(ctx, -1), (long) arr_idx));
            pop_count = 1;
        }
        if (arr_idx != DUK__NO_ARRAY_INDEX &&
            arr_idx < DUK_HSTRING_GET_CHARLEN(h)) {
            duk_pop_n(ctx, pop_count);
            duk_push_hstring(ctx, h);
            duk_substring(ctx, -1, arr_idx, arr_idx + 1);  /* [str] -> [substr] */
            DUK_DDD(DUK_DDDPRINT("-> %!T (base is string, key is an index inside string length "
                                 "after coercion -> return char)",
                                 (duk_tval *) duk_get_tval(ctx, -1)));
            return 1;
        }
        if (pop_count == 0) {
            /* This is a pretty awkward control flow, but we need to recheck the
             * key coercion here.
             */
            arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
            DUK_ASSERT(key != NULL);
            DUK_DDD(DUK_DDDPRINT("base object string, key is a non-fast-path number; after "
                                 "coercion key is %!T, arr_idx %ld",
                                 (duk_tval *) duk_get_tval(ctx, -1), (long) arr_idx));
        }
        if (key == DUK_HTHREAD_STRING_LENGTH(thr)) {
            duk_pop(ctx);  /* [key] -> [] */
            duk_push_uint(ctx, (duk_uint_t) DUK_HSTRING_GET_CHARLEN(h));  /* [] -> [res] */
            DUK_DDD(DUK_DDDPRINT("-> %!T (base is string, key is 'length' after coercion -> "
                                 "return string length)",
                                 (duk_tval *) duk_get_tval(ctx, -1)));
            return 1;
        }
        DUK_DDD(DUK_DDDPRINT("base object is a string, start lookup from string prototype"));
        curr = thr->builtins[DUK_BIDX_STRING_PROTOTYPE];
        goto lookup;  /* avoid double coercion */
    }
    case DUK_TAG_OBJECT: {
        duk_tval *tmp;
        curr = DUK_TVAL_GET_OBJECT(tv_obj);
        DUK_ASSERT(curr != NULL);
        tmp = duk__getprop_shallow_fastpath_array_tval(thr, curr, tv_key);
        if (tmp) {
            duk_push_tval(ctx, tmp);
            DUK_DDD(DUK_DDDPRINT("-> %!T (base is object, key is a number, array part "
                                 "fast path)",
                                 (duk_tval *) duk_get_tval(ctx, -1)));
            return 1;
        }
        if (duk__getprop_fastpath_bufobj_tval(thr, curr, tv_key) != 0) {
            /* Read value pushed on stack. */
            DUK_DDD(DUK_DDDPRINT("-> %!T (base is bufobj, key is a number, bufferobject "
                                 "fast path)",
                                 (duk_tval *) duk_get_tval(ctx, -1)));
            return 1;
        }
#if defined(DUK_USE_ES6_PROXY)
        if (DUK_UNLIKELY(DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ(curr))) {
            duk_hobject *h_target;
            if (duk__proxy_check_prop(thr, curr, DUK_STRIDX_GET, tv_key, &h_target)) {
                /* -> [ ... trap handler ] */
                DUK_DDD(DUK_DDDPRINT("-> proxy object 'get' for key %!T", (duk_tval *) tv_key));
                duk_push_hobject(ctx, h_target);  /* target */
                duk_push_tval(ctx, tv_key);       /* P */
                duk_push_tval(ctx, tv_obj);       /* Receiver: Proxy object */
                duk_call_method(ctx, 3 /*nargs*/);
                /* Target object must be checked for a conflicting
                 * non-configurable property.
                 */
                arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
                DUK_ASSERT(key != NULL);
                if (duk__get_own_propdesc_raw(thr, h_target, key, arr_idx, &desc, DUK_GETDESC_FLAG_PUSH_VALUE)) {
                    duk_tval *tv_hook = duk_require_tval(ctx, -3);  /* value from hook */
                    duk_tval *tv_targ = duk_require_tval(ctx, -1);  /* value from target */
                    duk_bool_t datadesc_reject;
                    duk_bool_t accdesc_reject;
                    DUK_DDD(DUK_DDDPRINT("proxy 'get': target has matching property %!O, check for "
                                         "conflicting property; tv_hook=%!T, tv_targ=%!T, desc.flags=0x%08lx, "
                                         "desc.get=%p, desc.set=%p",
                                         (duk_heaphdr *) key, (duk_tval *) tv_hook, (duk_tval *) tv_targ,
                                         (unsigned long) desc.flags,
                                         (void *) desc.get, (void *) desc.set));
                    datadesc_reject = !(desc.flags & DUK_PROPDESC_FLAG_ACCESSOR) &&
                                      !(desc.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) &&
                                      !(desc.flags & DUK_PROPDESC_FLAG_WRITABLE) &&
                                      !duk_js_samevalue(tv_hook, tv_targ);
                    accdesc_reject = (desc.flags & DUK_PROPDESC_FLAG_ACCESSOR) &&
                                     !(desc.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) &&
                                     (desc.get == NULL) &&
                                     !DUK_TVAL_IS_UNDEFINED(tv_hook);
                    if (datadesc_reject || accdesc_reject) {
                        DUK_ERROR_TYPE(thr, DUK_STR_PROXY_REJECTED);
                    }
                    duk_pop_2(ctx);
                } else {
                    duk_pop(ctx);
                }
                return 1;  /* return value */
            }
            curr = h_target;  /* resume lookup from target */
            DUK_TVAL_SET_OBJECT(tv_obj, curr);
        }
#endif  /* DUK_USE_ES6_PROXY */
        if (DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS(curr)) {
            arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
            DUK_ASSERT(key != NULL);
            if (duk__check_arguments_map_for_get(thr, curr, key, &desc)) {
                DUK_DDD(DUK_DDDPRINT("-> %!T (base is object with arguments exotic behavior, "
                                     "key matches magically bound property -> skip standard "
                                     "Get with replacement value)",
                                     (duk_tval *) duk_get_tval(ctx, -1)));
                /* no need for 'caller' post-check, because 'key' must be an array index */
                duk_remove(ctx, -2);  /* [key result] -> [result] */
                return 1;
            }
            goto lookup;  /* avoid double coercion */
        }
        break;
    }
    /* Buffer has virtual properties similar to string, but indexed values
     * are numbers, not 1-byte buffers/strings which would perform badly.
     */
    case DUK_TAG_BUFFER: {
        duk_hbuffer *h = DUK_TVAL_GET_BUFFER(tv_obj);
        duk_int_t pop_count;
        /*
         *  Because buffer values are often looped over, a number fast path
         *  is important.
         */
#if defined(DUK_USE_FASTINT)
        if (DUK_TVAL_IS_FASTINT(tv_key)) {
            arr_idx = duk__tval_fastint_to_arr_idx(tv_key);
            DUK_DDD(DUK_DDDPRINT("base object buffer, key is a fast-path fastint; arr_idx %ld", (long) arr_idx));
            pop_count = 0;
        }
        else
#endif
        if (DUK_TVAL_IS_NUMBER(tv_key)) {
            arr_idx = duk__tval_number_to_arr_idx(tv_key);
            DUK_DDD(DUK_DDDPRINT("base object buffer, key is a fast-path number; arr_idx %ld", (long) arr_idx));
            pop_count = 0;
        } else {
            arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
            DUK_ASSERT(key != NULL);
            DUK_DDD(DUK_DDDPRINT("base object buffer, key is a non-fast-path number; after "
                                 "coercion key is %!T, arr_idx %ld",
                                 (duk_tval *) duk_get_tval(ctx, -1), (long) arr_idx));
            pop_count = 1;
        }
        if (arr_idx != DUK__NO_ARRAY_INDEX &&
            arr_idx < DUK_HBUFFER_GET_SIZE(h)) {
            duk_pop_n(ctx, pop_count);
            duk_push_uint(ctx, ((duk_uint8_t *) DUK_HBUFFER_GET_DATA_PTR(thr->heap, h))[arr_idx]);
            DUK_DDD(DUK_DDDPRINT("-> %!T (base is buffer, key is an index inside buffer length "
                                 "after coercion -> return byte as number)",
                                 (duk_tval *) duk_get_tval(ctx, -1)));
            return 1;
        }
        if (pop_count == 0) {
            /* This is a pretty awkward control flow, but we need to recheck the
             * key coercion here.
             */
            arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
            DUK_ASSERT(key != NULL);
            DUK_DDD(DUK_DDDPRINT("base object buffer, key is a non-fast-path number; after "
                                 "coercion key is %!T, arr_idx %ld",
                                 (duk_tval *) duk_get_tval(ctx, -1), (long) arr_idx));
        }
        if (key == DUK_HTHREAD_STRING_LENGTH(thr) ||
            key == DUK_HTHREAD_STRING_BYTE_LENGTH(thr)) {
            duk_pop(ctx);  /* [key] -> [] */
            duk_push_uint(ctx, (duk_uint_t) DUK_HBUFFER_GET_SIZE(h));  /* [] -> [res] */
            DUK_DDD(DUK_DDDPRINT("-> %!T (base is buffer, key is 'length' or 'byteLength' "
                                 "after coercion -> return buffer length)",
                                 (duk_tval *) duk_get_tval(ctx, -1)));
            return 1;
        } else if (key == DUK_HTHREAD_STRING_BYTE_OFFSET(thr)) {
            duk_pop(ctx);  /* [key] -> [] */
            duk_push_uint(ctx, 0);  /* [] -> [res] */
            DUK_DDD(DUK_DDDPRINT("-> %!T (base is buffer, key is 'byteOffset' after coercion -> "
                                 "return 0 for consistency with Buffer objects)",
                                 (duk_tval *) duk_get_tval(ctx, -1)));
            return 1;
        } else if (key == DUK_HTHREAD_STRING_BYTES_PER_ELEMENT(thr)) {
            duk_pop(ctx);  /* [key] -> [] */
            duk_push_uint(ctx, 1);  /* [] -> [res] */
            DUK_DDD(DUK_DDDPRINT("-> %!T (base is buffer, key is 'BYTES_PER_ELEMENT' after coercion -> "
                                 "return 1 for consistency with Buffer objects)",
                                 (duk_tval *) duk_get_tval(ctx, -1)));
            return 1;
        }
        DUK_DDD(DUK_DDDPRINT("base object is a buffer, start lookup from buffer prototype"));
        curr = thr->builtins[DUK_BIDX_BUFFER_PROTOTYPE];
        goto lookup;  /* avoid double coercion */
    }
    case DUK_TAG_POINTER: {
        DUK_DDD(DUK_DDDPRINT("base object is a pointer, start lookup from pointer prototype"));
        curr = thr->builtins[DUK_BIDX_POINTER_PROTOTYPE];
        break;
    }
    case DUK_TAG_LIGHTFUNC: {
        duk_int_t lf_flags = DUK_TVAL_GET_LIGHTFUNC_FLAGS(tv_obj);
        /* Must coerce key: if key is an object, it may coerce to e.g. 'length'. */
        arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
        if (key == DUK_HTHREAD_STRING_LENGTH(thr)) {
            duk_int_t lf_len = DUK_LFUNC_FLAGS_GET_LENGTH(lf_flags);
            duk_pop(ctx);
            duk_push_int(ctx, lf_len);
            return 1;
        } else if (key == DUK_HTHREAD_STRING_NAME(thr)) {
            duk_pop(ctx);
            duk_push_lightfunc_name(ctx, tv_obj);
            return 1;
        }
        DUK_DDD(DUK_DDDPRINT("base object is a lightfunc, start lookup from function prototype"));
        curr = thr->builtins[DUK_BIDX_FUNCTION_PROTOTYPE];
        goto lookup;  /* avoid double coercion */
    }
#if defined(DUK_USE_FASTINT)
    case DUK_TAG_FASTINT:
#endif
    default: {
        /* number */
        DUK_DDD(DUK_DDDPRINT("base object is a number, start lookup from number prototype"));
        DUK_ASSERT(!DUK_TVAL_IS_UNUSED(tv_obj));
        DUK_ASSERT(DUK_TVAL_IS_NUMBER(tv_obj));
        curr = thr->builtins[DUK_BIDX_NUMBER_PROTOTYPE];
        break;
    }
    }
    /* key coercion (unless already coerced above) */
    DUK_ASSERT(key == NULL);
    arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
    DUK_ASSERT(key != NULL);
    /*
     *  Property lookup
     */
 lookup:
    /* [key] (coerced) */
    DUK_ASSERT(curr != NULL);
    DUK_ASSERT(key != NULL);
    sanity = DUK_HOBJECT_PROTOTYPE_CHAIN_SANITY;
    do {
        if (!duk__get_own_propdesc_raw(thr, curr, key, arr_idx, &desc, DUK_GETDESC_FLAG_PUSH_VALUE)) {
            goto next_in_chain;
        }
        if (desc.get != NULL) {
            /* accessor with defined getter */
            DUK_ASSERT((desc.flags & DUK_PROPDESC_FLAG_ACCESSOR) != 0);
            duk_pop(ctx);                     /* [key undefined] -> [key] */
            duk_push_hobject(ctx, desc.get);
            duk_push_tval(ctx, tv_obj);       /* note: original, uncoerced base */
#ifdef DUK_USE_NONSTD_GETTER_KEY_ARGUMENT
            duk_dup(ctx, -3);
            duk_call_method(ctx, 1);          /* [key getter this key] -> [key retval] */
#else
            duk_call_method(ctx, 0);          /* [key getter this] -> [key retval] */
#endif
        } else {
            /* [key value] or [key undefined] */
            /* data property or accessor without getter */
            DUK_ASSERT(((desc.flags & DUK_PROPDESC_FLAG_ACCESSOR) == 0) ||
                       (desc.get == NULL));
            /* if accessor without getter, return value is undefined */
            DUK_ASSERT(((desc.flags & DUK_PROPDESC_FLAG_ACCESSOR) == 0) ||
                       duk_is_undefined(ctx, -1));
            /* Note: for an accessor without getter, falling through to
             * check for "caller" exotic behavior is unnecessary as
             * "undefined" will never activate the behavior.  But it does
             * no harm, so we'll do it anyway.
             */
        }
        goto found;  /* [key result] */
     next_in_chain:
        /* XXX: option to pretend property doesn't exist if sanity limit is
         * hit might be useful.
         */
        if (sanity-- == 0) {
            DUK_ERROR_RANGE(thr, DUK_STR_PROTOTYPE_CHAIN_LIMIT);
        }
        curr = DUK_HOBJECT_GET_PROTOTYPE(thr->heap, curr);
    } while (curr);
    /*
     *  Not found
     */
    duk_to_undefined(ctx, -1);  /* [key] -> [undefined] (default value) */
    DUK_DDD(DUK_DDDPRINT("-> %!T (not found)", (duk_tval *) duk_get_tval(ctx, -1)));
    return 0;
    /*
     *  Found; post-processing (Function and arguments objects)
     */
 found:
    /* [key result] */
#if !defined(DUK_USE_NONSTD_FUNC_CALLER_PROPERTY)
    /* Special behavior for 'caller' property of (non-bound) function objects
     * and non-strict Arguments objects: if 'caller' -value- (!) is a strict
     * mode function, throw a TypeError (E5 Sections 15.3.5.4, 10.6).
     * Quite interestingly, a non-strict function with no formal arguments
     * will get an arguments object -without- special 'caller' behavior!
     *
     * The E5.1 spec is a bit ambiguous if this special behavior applies when
     * a bound function is the base value (not the 'caller' value): Section
     * 15.3.4.5 (describing bind()) states that [[Get]] for bound functions
     * matches that of Section 15.3.5.4 ([[Get]] for Function instances).
     * However, Section 13.3.5.4 has "NOTE: Function objects created using
     * Function.prototype.bind use the default [[Get]] internal method."
     * The current implementation assumes this means that bound functions
     * should not have the special [[Get]] behavior.
     *
     * The E5.1 spec is also a bit unclear if the TypeError throwing is
     * applied if the 'caller' value is a strict bound function.  The
     * current implementation will throw even for both strict non-bound
     * and strict bound functions.
     *
     * See test-dev-strict-func-as-caller-prop-value.js for quite extensive
     * tests.
     *
     * This exotic behavior is disabled when the non-standard 'caller' property
     * is enabled, as it conflicts with the free use of 'caller'.
     */
    if (key == DUK_HTHREAD_STRING_CALLER(thr) &&
        DUK_TVAL_IS_OBJECT(tv_obj)) {
        duk_hobject *orig = DUK_TVAL_GET_OBJECT(tv_obj);
        DUK_ASSERT(orig != NULL);
        if (DUK_HOBJECT_IS_NONBOUND_FUNCTION(orig) ||
            DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS(orig)) {
            duk_hobject *h;
            /* XXX: The TypeError is currently not applied to bound
             * functions because the 'strict' flag is not copied by
             * bind().  This may or may not be correct, the specification
             * only refers to the value being a "strict mode Function
             * object" which is ambiguous.
             */
            DUK_ASSERT(!DUK_HOBJECT_HAS_BOUND(orig));
References duk_hthread::builtins, duk__check_arguments_map_for_get(), duk__get_own_propdesc_raw(), duk__getprop_fastpath_bufobj_tval(), duk__getprop_shallow_fastpath_array_tval(), DUK__NO_ARRAY_INDEX, duk__proxy_check_prop(), duk__push_tval_to_hstring_arr_idx(), duk__tval_number_to_arr_idx(), DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, DUK_BIDX_BOOLEAN_PROTOTYPE, DUK_BIDX_BUFFER_PROTOTYPE, DUK_BIDX_FUNCTION_PROTOTYPE, DUK_BIDX_NUMBER_PROTOTYPE, DUK_BIDX_POINTER_PROTOTYPE, DUK_BIDX_STRING_PROTOTYPE, duk_call_method(), DUK_DDD, DUK_DDDPRINT, duk_dup(), DUK_ERR_TYPE_ERROR, DUK_ERROR_FMT2, DUK_ERROR_RANGE, DUK_ERROR_TYPE, duk_get_hobject(), duk_get_tval(), DUK_GETDESC_FLAG_PUSH_VALUE, DUK_HBUFFER_GET_DATA_PTR, DUK_HBUFFER_GET_SIZE, DUK_HOBJECT_GET_PROTOTYPE, DUK_HOBJECT_HAS_BOUND, DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS, DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ, DUK_HOBJECT_HAS_STRICT, DUK_HOBJECT_IS_FUNCTION, DUK_HOBJECT_IS_NONBOUND_FUNCTION, DUK_HOBJECT_PROTOTYPE_CHAIN_SANITY, DUK_HSTRING_GET_CHARLEN, DUK_HTHREAD_STRING_BYTE_LENGTH, DUK_HTHREAD_STRING_BYTE_OFFSET, DUK_HTHREAD_STRING_BYTES_PER_ELEMENT, DUK_HTHREAD_STRING_CALLER, DUK_HTHREAD_STRING_LENGTH, DUK_HTHREAD_STRING_NAME, duk_is_undefined(), duk_js_samevalue, DUK_LFUNC_FLAGS_GET_LENGTH, duk_pop(), duk_pop_2(), duk_pop_n(), DUK_PROPDESC_FLAG_ACCESSOR, DUK_PROPDESC_FLAG_CONFIGURABLE, DUK_PROPDESC_FLAG_WRITABLE, duk_push_hobject(), duk_push_hstring(), duk_push_int(), duk_push_lightfunc_name(), duk_push_string_tval_readable(), duk_push_tval(), duk_push_uint(), duk_remove(), duk_require_tval(), DUK_STR_INVALID_BASE, DUK_STR_PROTOTYPE_CHAIN_LIMIT, DUK_STR_PROXY_REJECTED, DUK_STR_STRICT_CALLER_READ, DUK_STRIDX_GET, duk_substring(), DUK_TAG_BOOLEAN, DUK_TAG_BUFFER, DUK_TAG_LIGHTFUNC, DUK_TAG_NULL, DUK_TAG_OBJECT, DUK_TAG_POINTER, DUK_TAG_STRING, DUK_TAG_UNDEFINED, duk_to_undefined(), DUK_TVAL_GET_BUFFER, DUK_TVAL_GET_LIGHTFUNC_FLAGS, DUK_TVAL_GET_OBJECT, DUK_TVAL_GET_STRING, DUK_TVAL_GET_TAG, DUK_TVAL_IS_NUMBER, DUK_TVAL_IS_OBJECT, DUK_TVAL_IS_UNDEFINED, DUK_TVAL_IS_UNUSED, DUK_TVAL_SET_OBJECT, DUK_TVAL_SET_TVAL, DUK_UNLIKELY, duk_propdesc::flags, duk_propdesc::get, duk_hthread::heap, NULL, and duk_propdesc::set.
Referenced by duk__enc_value(), duk__getvar_helper(), duk__js_execute_bytecode_inner(), duk_get_prop(), and duk_hobject_get_length().
duk_hobject_hasprop()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_hasprop (duk_hthread * thr, duk_tval * tv_obj, duk_tval * tv_key)
Definition at line 49780 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_context *ctx = (duk_context *) thr;
    duk_tval tv_key_copy;
    duk_hobject *obj;
    duk_hstring *key;
    duk_uint32_t arr_idx;
    duk_bool_t rc;
    duk_propdesc desc;
    DUK_DDD(DUK_DDDPRINT("hasprop: thr=%p, obj=%p, key=%p (obj -> %!T, key -> %!T)",
                         (void *) thr, (void *) tv_obj, (void *) tv_key,
                         (duk_tval *) tv_obj, (duk_tval *) tv_key));
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(tv_obj != NULL);
    DUK_ASSERT(tv_key != NULL);
    DUK_ASSERT_VALSTACK_SPACE(thr, DUK__VALSTACK_SPACE);
    DUK_TVAL_SET_TVAL(&tv_key_copy, tv_key);
    tv_key = &tv_key_copy;
    /*
     *  The 'in' operator requires an object as its right hand side,
     *  throwing a TypeError unconditionally if this is not the case.
     *
     *  However, lightfuncs need to behave like fully fledged objects
     *  here to be maximally transparent, so we need to handle them
     *  here.
     */
    /* XXX: Refactor key coercion so that it's only called once.  It can't
     * be trivially lifted here because the object must be type checked
     * first.
     */
    if (DUK_TVAL_IS_OBJECT(tv_obj)) {
        obj = DUK_TVAL_GET_OBJECT(tv_obj);
        DUK_ASSERT(obj != NULL);
        arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
    } else if (DUK_TVAL_IS_LIGHTFUNC(tv_obj)) {
        arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
        if (duk__key_is_lightfunc_ownprop(thr, key)) {
            /* FOUND */
            rc = 1;
            goto pop_and_return;
        }
        /* If not found, resume existence check from Function.prototype.
         * We can just substitute the value in this case; nothing will
         * need the original base value (as would be the case with e.g.
         * setters/getters.
         */
        obj = thr->builtins[DUK_BIDX_FUNCTION_PROTOTYPE];
    } else {
        /* Note: unconditional throw */
        DUK_DDD(DUK_DDDPRINT("base object is not an object -> reject"));
        DUK_ERROR_TYPE(thr, DUK_STR_INVALID_BASE);
    }
    /* XXX: fast path for arrays? */
    DUK_ASSERT(key != NULL);
    DUK_ASSERT(obj != NULL);
    DUK_UNREF(arr_idx);
#if defined(DUK_USE_ES6_PROXY)
    if (DUK_UNLIKELY(DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ(obj))) {
        duk_hobject *h_target;
        duk_bool_t tmp_bool;
        /* XXX: the key in 'key in obj' is string coerced before we're called
         * (which is the required behavior in E5/E5.1/E6) so the key is a string
         * here already.
         */
        if (duk__proxy_check_prop(thr, obj, DUK_STRIDX_HAS, tv_key, &h_target)) {
            /* [ ... key trap handler ] */
            DUK_DDD(DUK_DDDPRINT("-> proxy object 'has' for key %!T", (duk_tval *) tv_key));
            duk_push_hobject(ctx, h_target);  /* target */
            duk_push_tval(ctx, tv_key);       /* P */
            duk_call_method(ctx, 2 /*nargs*/);
            tmp_bool = duk_to_boolean(ctx, -1);
            if (!tmp_bool) {
                /* Target object must be checked for a conflicting
                 * non-configurable property.
                 */
                if (duk__get_own_propdesc_raw(thr, h_target, key, arr_idx, &desc, 0 /*flags*/)) {  /* don't push value */
                    DUK_DDD(DUK_DDDPRINT("proxy 'has': target has matching property %!O, check for "
                                         "conflicting property; desc.flags=0x%08lx, "
                                         "desc.get=%p, desc.set=%p",
                                         (duk_heaphdr *) key, (unsigned long) desc.flags,
                                         (void *) desc.get, (void *) desc.set));
                    /* XXX: Extensibility check for target uses IsExtensible().  If we
                     * implemented the isExtensible trap and didn't reject proxies as
                     * proxy targets, it should be respected here.
                     */
                    if (!((desc.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) &&  /* property is configurable and */
                          DUK_HOBJECT_HAS_EXTENSIBLE(h_target))) {          /* ... target is extensible */
                        DUK_ERROR_TYPE(thr, DUK_STR_PROXY_REJECTED);
                    }
                }
            }
References duk_hthread::builtins, duk__get_own_propdesc_raw(), duk__get_propdesc(), duk__key_is_lightfunc_ownprop(), duk__proxy_check_prop(), duk__push_tval_to_hstring_arr_idx(), DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, DUK_BIDX_FUNCTION_PROTOTYPE, duk_call_method(), DUK_DDD, DUK_DDDPRINT, DUK_ERROR_TYPE, DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ, DUK_HOBJECT_HAS_EXTENSIBLE, duk_pop(), duk_pop_2(), DUK_PROPDESC_FLAG_CONFIGURABLE, duk_push_hobject(), duk_push_tval(), DUK_STR_INVALID_BASE, DUK_STR_PROXY_REJECTED, DUK_STRIDX_HAS, duk_to_boolean(), DUK_TVAL_GET_OBJECT, DUK_TVAL_IS_LIGHTFUNC, DUK_TVAL_IS_OBJECT, DUK_TVAL_SET_TVAL, DUK_UNLIKELY, DUK_UNREF, duk_propdesc::flags, duk_propdesc::get, duk_hthread::heap, NULL, and duk_propdesc::set.
Referenced by duk__get_identifier_reference(), duk_has_prop(), and duk_js_in().
duk_hobject_hasprop_raw()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_hasprop_raw (duk_hthread * thr, duk_hobject * obj, duk_hstring * key)
Definition at line 49916 of file duktape-1.5.2/src-noline/duktape.c.
               :
    duk_pop(ctx);  /* [ key ] -> [] */
    return rc;
}
/*
 *  HASPROP variant used internally.
 *
 *  This primitive must never throw an error, callers rely on this.
 *  In particular, don't throw an error for prototype loops; instead,
 *  pretend like the property doesn't exist if a prototype sanity limit
 *  is reached.
References duk__get_propdesc(), DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, DUK_GETDESC_FLAG_IGNORE_PROTOLOOP, dummy, duk_hthread::heap, and NULL.
Referenced by duk__err_augment_builtin_create(), duk__free_run_finalizers(), duk__get_identifier_reference(), duk__mark_finalizable(), duk__refzero_free_pending(), and duk_hobject_enumerator_next().
duk_hobject_object_get_own_property_descriptor()
DUK_INTERNAL_DECL duk_ret_t duk_hobject_object_get_own_property_descriptor (duk_context * ctx)
Definition at line 51845 of file duktape-1.5.2/src-noline/duktape.c.
{
        return (duk_uint32_t) val;
    }
    return 0;
}
/*
 *  Object.getOwnPropertyDescriptor()  (E5 Sections 15.2.3.3, 8.10.4)
 *
 *  This is an actual function call.
 */
DUK_INTERNAL duk_ret_t duk_hobject_object_get_own_property_descriptor(duk_context *ctx) {
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *obj;
    duk_hstring *key;
    duk_propdesc pd;
    duk_bool_t rc;
    DUK_ASSERT(ctx != NULL);
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    obj = duk_require_hobject_or_lfunc_coerce(ctx, 0);
    (void) duk_to_string(ctx, 1);
    key = duk_require_hstring(ctx, 1);
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT(key != NULL);
    DUK_ASSERT_VALSTACK_SPACE(thr, DUK__VALSTACK_SPACE);
    rc = duk_hobject_get_own_propdesc(thr, obj, key, &pd, DUK_GETDESC_FLAG_PUSH_VALUE);
    if (!rc) {
        duk_push_undefined(ctx);
        /* [obj key undefined] */
        return 1;
    }
    duk_push_object(ctx);
    /* [obj key value desc] */
    if (DUK_PROPDESC_IS_ACCESSOR(&pd)) {
        /* If a setter/getter is missing (undefined), the descriptor must
         * still have the property present with the value 'undefined'.
         */
        if (pd.get) {
            duk_push_hobject(ctx, pd.get);
        } else {
            duk_push_undefined(ctx);
        }
        duk_put_prop_stridx(ctx, -2, DUK_STRIDX_GET);
        if (pd.set) {
            duk_push_hobject(ctx, pd.set);
        } else {
            duk_push_undefined(ctx);
        }
References DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, duk_dup(), DUK_GETDESC_FLAG_PUSH_VALUE, duk_hobject_get_own_propdesc(), DUK_PROPDESC_IS_ACCESSOR, DUK_PROPDESC_IS_CONFIGURABLE, DUK_PROPDESC_IS_ENUMERABLE, DUK_PROPDESC_IS_WRITABLE, duk_push_boolean(), duk_push_hobject(), duk_push_object(), duk_push_undefined(), duk_put_prop_stridx(), duk_require_hobject_or_lfunc_coerce(), duk_require_hstring(), DUK_STRIDX_CONFIGURABLE, DUK_STRIDX_ENUMERABLE, DUK_STRIDX_GET, DUK_STRIDX_SET, DUK_STRIDX_VALUE, DUK_STRIDX_WRITABLE, duk_to_string(), duk_propdesc::get, duk_hthread::heap, NULL, and duk_propdesc::set.
Referenced by duk_bi_object_constructor_get_own_property_descriptor().
duk_hobject_object_is_sealed_frozen_helper()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_object_is_sealed_frozen_helper (duk_hthread * thr, duk_hobject * obj, duk_bool_t is_frozen)
Definition at line 53002 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_uint_fast32_t i;
    DUK_ASSERT(obj != NULL);
    DUK_UNREF(thr);
    /* Note: no allocation pressure, no need to check refcounts etc */
    /* must not be extensible */
    if (DUK_HOBJECT_HAS_EXTENSIBLE(obj)) {
        return 0;
    }
    /* all virtual properties are non-configurable and non-writable */
    /* entry part must not contain any configurable properties, or
     * writable properties (if is_frozen).
     */
    for (i = 0; i < DUK_HOBJECT_GET_ENEXT(obj); i++) {
        duk_small_uint_t flags;
        if (!DUK_HOBJECT_E_GET_KEY(thr->heap, obj, i)) {
            continue;
        }
        /* avoid multiple computations of flags address; bypasses macros */
        flags = (duk_small_uint_t) DUK_HOBJECT_E_GET_FLAGS(thr->heap, obj, i);
        if (flags & DUK_PROPDESC_FLAG_CONFIGURABLE) {
            return 0;
        }
        if (is_frozen &&
            !(flags & DUK_PROPDESC_FLAG_ACCESSOR) &&
References DUK_ASSERT, DUK_HOBJECT_A_GET_VALUE_PTR, DUK_HOBJECT_E_GET_FLAGS, DUK_HOBJECT_E_GET_KEY, DUK_HOBJECT_GET_ASIZE, DUK_HOBJECT_GET_ENEXT, DUK_HOBJECT_HAS_EXTENSIBLE, DUK_PROPDESC_FLAG_ACCESSOR, DUK_PROPDESC_FLAG_CONFIGURABLE, DUK_PROPDESC_FLAG_WRITABLE, DUK_TVAL_IS_UNUSED, DUK_UNREF, duk_hthread::heap, and NULL.
Referenced by duk_bi_object_constructor_is_extensible(), and duk_bi_object_constructor_is_sealed_frozen_shared().
duk_hobject_object_ownprop_helper()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_object_ownprop_helper (duk_context * ctx, duk_small_uint_t required_desc_flags)
Definition at line 52906 of file duktape-1.5.2/src-noline/duktape.c.
                    :
    DUK_ERROR_TYPE(thr, DUK_STR_NOT_EXTENSIBLE);
    return;
 fail_not_configurable:
    DUK_ERROR_TYPE(thr, DUK_STR_NOT_CONFIGURABLE);
    return;
 fail_array_length_partial:
    DUK_ERROR_TYPE(thr, DUK_STR_ARRAY_LENGTH_WRITE_FAILED);
    return;
}
/*
 *  Object.prototype.hasOwnProperty() and Object.prototype.propertyIsEnumerable().
 */
DUK_INTERNAL duk_bool_t duk_hobject_object_ownprop_helper(duk_context *ctx, duk_small_uint_t required_desc_flags) {
    duk_hthread *thr = (duk_hthread *) ctx;
References DUK_ASSERT, duk_hobject_get_own_propdesc(), duk_push_boolean(), duk_push_this_coercible_to_object(), duk_to_hstring(), duk_propdesc::flags, and NULL.
Referenced by duk_bi_object_prototype_has_own_property(), duk_bi_object_prototype_property_is_enumerable(), and duk_bi_pointer_constructor().
duk_hobject_object_seal_freeze_helper()
DUK_INTERNAL_DECL void duk_hobject_object_seal_freeze_helper (duk_hthread * thr, duk_hobject * obj, duk_bool_t is_freeze)
Definition at line 52941 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_uint_fast32_t i;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT_VALSTACK_SPACE(thr, DUK__VALSTACK_SPACE);
#if defined(DUK_USE_ROM_OBJECTS)
    if (DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) obj)) {
        DUK_DD(DUK_DDPRINT("attempt to seal/freeze a readonly object, reject"));
        DUK_ERROR_TYPE(thr, DUK_STR_NOT_CONFIGURABLE);
    }
#endif
    /*
     *  Abandon array part because all properties must become non-configurable.
     *  Note that this is now done regardless of whether this is always the case
     *  (skips check, but performance problem if caller would do this many times
     *  for the same object; not likely).
     */
    duk__abandon_array_checked(thr, obj);
    DUK_ASSERT(DUK_HOBJECT_GET_ASIZE(obj) == 0);
    for (i = 0; i < DUK_HOBJECT_GET_ENEXT(obj); i++) {
        duk_uint8_t *fp;
        /* since duk__abandon_array_checked() causes a resize, there should be no gaps in keys */
        DUK_ASSERT(DUK_HOBJECT_E_GET_KEY(thr->heap, obj, i) != NULL);
References duk__abandon_array_checked(), DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_VALSTACK_SPACE, DUK_DD, DUK_DDPRINT, DUK_ERROR_TYPE, DUK_HEAPHDR_HAS_READONLY, DUK_HOBJECT_CLEAR_EXTENSIBLE, DUK_HOBJECT_E_GET_FLAGS_PTR, DUK_HOBJECT_E_GET_KEY, DUK_HOBJECT_GET_ASIZE, DUK_HOBJECT_GET_ENEXT, DUK_PROPDESC_FLAG_ACCESSOR, DUK_PROPDESC_FLAG_CONFIGURABLE, DUK_PROPDESC_FLAG_WRITABLE, DUK_STR_NOT_CONFIGURABLE, duk_hthread::heap, and NULL.
Referenced by duk_bi_object_constructor_seal_freeze_shared().
duk_hobject_prepare_property_descriptor()
DUK_INTERNAL_DECL void duk_hobject_prepare_property_descriptor (duk_context * ctx, duk_idx_t idx_in, duk_uint_t * out_defprop_flags, duk_idx_t * out_idx_value, duk_hobject ** out_getter, duk_hobject ** out_setter)
Definition at line 51926 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_idx_t idx_value = -1;
    duk_hobject *getter = NULL;
    duk_hobject *setter = NULL;
    duk_bool_t is_data_desc = 0;
    duk_bool_t is_acc_desc = 0;
    duk_uint_t defprop_flags = 0;
    DUK_ASSERT(ctx != NULL);
    DUK_ASSERT(out_defprop_flags != NULL);
    DUK_ASSERT(out_idx_value != NULL);
    DUK_ASSERT(out_getter != NULL);
    DUK_ASSERT(out_setter != NULL);
    /* Must be an object, otherwise TypeError (E5.1 Section 8.10.5, step 1). */
    idx_in = duk_require_normalize_index(ctx, idx_in);
    (void) duk_require_hobject(ctx, idx_in);
    /* The coercion order must match the ToPropertyDescriptor() algorithm
     * so that side effects in coercion happen in the correct order.
     * (This order also happens to be compatible with duk_def_prop(),
     * although it doesn't matter in practice.)
     */
    if (duk_get_prop_stridx(ctx, idx_in, DUK_STRIDX_VALUE)) {
        is_data_desc = 1;
        defprop_flags |= DUK_DEFPROP_HAVE_VALUE;
        idx_value = duk_get_top_index(ctx);
        /* Leave 'value' on stack */
    } else {
        duk_pop(ctx);
    }
    if (duk_get_prop_stridx(ctx, idx_in, DUK_STRIDX_WRITABLE)) {
        is_data_desc = 1;
        if (duk_to_boolean(ctx, -1)) {
            defprop_flags |= DUK_DEFPROP_HAVE_WRITABLE | DUK_DEFPROP_WRITABLE;
        } else {
            defprop_flags |= DUK_DEFPROP_HAVE_WRITABLE;
        }
    }
    duk_pop(ctx);
    if (duk_get_prop_stridx(ctx, idx_in, DUK_STRIDX_GET)) {
        duk_tval *tv = duk_require_tval(ctx, -1);
        duk_hobject *h_get;
        if (DUK_TVAL_IS_UNDEFINED(tv)) {
            /* undefined is accepted */
            DUK_ASSERT(getter == NULL);
        } else {
            /* NOTE: lightfuncs are coerced to full functions because
             * lightfuncs don't fit into a property value slot.  This
             * has some side effects, see test-dev-lightfunc-accessor.js.
             */
            h_get = duk_get_hobject_or_lfunc_coerce(ctx, -1);
            if (h_get == NULL || !DUK_HOBJECT_IS_CALLABLE(h_get)) {
                goto type_error;
            }
            getter = h_get;
        }
        is_acc_desc = 1;
        defprop_flags |= DUK_DEFPROP_HAVE_GETTER;
        /* Leave 'getter' on stack */
    } else {
        duk_pop(ctx);
    }
    if (duk_get_prop_stridx(ctx, idx_in, DUK_STRIDX_SET)) {
        duk_tval *tv = duk_require_tval(ctx, -1);
        duk_hobject *h_set;
        if (DUK_TVAL_IS_UNDEFINED(tv)) {
            /* undefined is accepted */
            DUK_ASSERT(setter == NULL);
        }  else {
            /* NOTE: lightfuncs are coerced to full functions because
             * lightfuncs don't fit into a property value slot.  This
             * has some side effects, see test-dev-lightfunc-accessor.js.
             */
            h_set = duk_get_hobject_or_lfunc_coerce(ctx, -1);
            if (h_set == NULL || !DUK_HOBJECT_IS_CALLABLE(h_set)) {
                goto type_error;
            }
            setter = h_set;
        }
        is_acc_desc = 1;
        defprop_flags |= DUK_DEFPROP_HAVE_SETTER;
        /* Leave 'setter' on stack */
    } else {
        duk_pop(ctx);
    }
    if (duk_get_prop_stridx(ctx, idx_in, DUK_STRIDX_ENUMERABLE)) {
        if (duk_to_boolean(ctx, -1)) {
            defprop_flags |= DUK_DEFPROP_HAVE_ENUMERABLE | DUK_DEFPROP_ENUMERABLE;
        } else {
            defprop_flags |= DUK_DEFPROP_HAVE_ENUMERABLE;
        }
    }
    duk_pop(ctx);
    if (duk_get_prop_stridx(ctx, idx_in, DUK_STRIDX_CONFIGURABLE)) {
        if (duk_to_boolean(ctx, -1)) {
            defprop_flags |= DUK_DEFPROP_HAVE_CONFIGURABLE | DUK_DEFPROP_CONFIGURABLE;
        } else {
            defprop_flags |= DUK_DEFPROP_HAVE_CONFIGURABLE;
        }
    }
References DUK_ASSERT, DUK_DEFPROP_CONFIGURABLE, DUK_DEFPROP_ENUMERABLE, DUK_DEFPROP_HAVE_CONFIGURABLE, DUK_DEFPROP_HAVE_ENUMERABLE, DUK_DEFPROP_HAVE_GETTER, DUK_DEFPROP_HAVE_SETTER, DUK_DEFPROP_HAVE_VALUE, DUK_DEFPROP_HAVE_WRITABLE, DUK_DEFPROP_WRITABLE, DUK_ERROR_TYPE, duk_get_hobject_or_lfunc_coerce(), duk_get_prop_stridx(), duk_get_top_index(), DUK_HOBJECT_IS_CALLABLE, duk_pop(), duk_require_hobject(), duk_require_normalize_index(), duk_require_tval(), DUK_STR_INVALID_DESCRIPTOR, DUK_STRIDX_CONFIGURABLE, DUK_STRIDX_ENUMERABLE, DUK_STRIDX_GET, DUK_STRIDX_SET, DUK_STRIDX_VALUE, DUK_STRIDX_WRITABLE, duk_to_boolean(), DUK_TVAL_IS_UNDEFINED, and NULL.
Referenced by duk_bi_object_constructor_define_properties(), and duk_bi_object_constructor_define_property().
duk_hobject_prototype_chain_contains()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_prototype_chain_contains (duk_hthread * thr, duk_hobject * h, duk_hobject * p, duk_bool_t ignore_loop)
Definition at line 46773 of file duktape-1.5.2/src-noline/duktape.c.
{
        /* Note: we ask for one return value from duk_safe_call to get this
         * error debugging here.
         */
        DUK_D(DUK_DPRINT("wrapped finalizer call failed for object %p (ignored); error: %!T",
                         (void *) obj, (duk_tval *) duk_get_tval(ctx, -1)));
    }
    duk_pop_2(ctx);  /* -> [...] */
    DUK_ASSERT_TOP(ctx, entry_top);
}
/*
 *  Misc support functions
 */
/* include removed: duk_internal.h */
DUK_INTERNAL duk_bool_t duk_hobject_prototype_chain_contains(duk_hthread *thr, duk_hobject *h, duk_hobject *p, duk_bool_t ignore_loop) {
    duk_uint_t sanity;
    DUK_ASSERT(thr != NULL);
    /* False if the object is NULL or the prototype 'p' is NULL.
     * In particular, false if both are NULL (don't compare equal).
     */
    if (h == NULL || p == NULL) {
        return 0;
    }
    sanity = DUK_HOBJECT_PROTOTYPE_CHAIN_SANITY;
References DUK_ASSERT, DUK_D, DUK_DPRINT, DUK_ERROR_RANGE, duk_get_tval(), DUK_HOBJECT_GET_PROTOTYPE, DUK_HOBJECT_PROTOTYPE_CHAIN_SANITY, DUK_STR_PROTOTYPE_CHAIN_LIMIT, duk_hthread::heap, and NULL.
Referenced by duk_bi_nodejs_buffer_is_buffer(), duk_bi_object_prototype_is_prototype_of(), duk_err_augment_error_create(), and duk_err_augment_error_create().
duk_hobject_putprop()
DUK_INTERNAL_DECL duk_bool_t duk_hobject_putprop (duk_hthread * thr, duk_tval * tv_obj, duk_tval * tv_key, duk_tval * tv_val, duk_bool_t throw_flag)
Definition at line 50306 of file duktape-1.5.2/src-noline/duktape.c.
                          :
 *
 *      - Preprocessing before and postprocessing after an actual property
 *        write.  For example, array index write requires pre-checking the
 *        array 'length' property for access control, and may require an
 *        array 'length' update after the actual write has succeeded (but
 *        not if it fails).
 *
 *      - Deletion of multiple entries, as a result of array 'length' write.
 *
 *    * Input values are taken as pointers which may point to the valstack.
 *      If valstack is resized because of the put (this may happen at least
 *      when the array part is abandoned), the pointers can be invalidated.
 *      (We currently make a copy of all of the input values to avoid issues.)
 */
DUK_INTERNAL duk_bool_t duk_hobject_putprop(duk_hthread *thr, duk_tval *tv_obj, duk_tval *tv_key, duk_tval *tv_val, duk_bool_t throw_flag) {
    duk_context *ctx = (duk_context *) thr;
    duk_tval tv_obj_copy;
    duk_tval tv_key_copy;
    duk_tval tv_val_copy;
    duk_hobject *orig = NULL;  /* NULL if tv_obj is primitive */
    duk_hobject *curr;
    duk_hstring *key = NULL;
    duk_propdesc desc;
    duk_tval *tv;
    duk_uint32_t arr_idx;
    duk_bool_t rc;
    duk_int_t e_idx;
    duk_uint_t sanity;
    duk_uint32_t new_array_length = 0;  /* 0 = no update */
    DUK_DDD(DUK_DDDPRINT("putprop: thr=%p, obj=%p, key=%p, val=%p, throw=%ld "
                         "(obj -> %!T, key -> %!T, val -> %!T)",
                         (void *) thr, (void *) tv_obj, (void *) tv_key, (void *) tv_val,
                         (long) throw_flag, (duk_tval *) tv_obj, (duk_tval *) tv_key, (duk_tval *) tv_val));
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(thr->heap != NULL);
    DUK_ASSERT(ctx != NULL);
    DUK_ASSERT(tv_obj != NULL);
    DUK_ASSERT(tv_key != NULL);
    DUK_ASSERT(tv_val != NULL);
    DUK_ASSERT_VALSTACK_SPACE(thr, DUK__VALSTACK_SPACE);
    /*
     *  Make a copy of tv_obj, tv_key, and tv_val to avoid any issues of
     *  them being invalidated by a valstack resize.
     *
     *  XXX: this is an overkill for some paths, so optimize this later
     *  (or maybe switch to a stack arguments model entirely).
     */
    DUK_TVAL_SET_TVAL(&tv_obj_copy, tv_obj);
    DUK_TVAL_SET_TVAL(&tv_key_copy, tv_key);
    DUK_TVAL_SET_TVAL(&tv_val_copy, tv_val);
    tv_obj = &tv_obj_copy;
    tv_key = &tv_key_copy;
    tv_val = &tv_val_copy;
    /*
     *  Coercion and fast path processing.
     */
    switch (DUK_TVAL_GET_TAG(tv_obj)) {
    case DUK_TAG_UNDEFINED:
    case DUK_TAG_NULL: {
        /* Note: unconditional throw */
        DUK_DDD(DUK_DDDPRINT("base object is undefined or null -> reject (object=%!iT)",
                             (duk_tval *) tv_obj));
#if defined(DUK_USE_PARANOID_ERRORS)
        DUK_ERROR_TYPE(thr, DUK_STR_INVALID_BASE);
#else
        DUK_ERROR_FMT2(thr, DUK_ERR_TYPE_ERROR, "cannot write property %s of %s",
                       duk_push_string_tval_readable(ctx, tv_key), duk_push_string_tval_readable(ctx, tv_obj));
#endif
        return 0;
    }
    case DUK_TAG_BOOLEAN: {
        DUK_DDD(DUK_DDDPRINT("base object is a boolean, start lookup from boolean prototype"));
        curr = thr->builtins[DUK_BIDX_BOOLEAN_PROTOTYPE];
        break;
    }
    case DUK_TAG_STRING: {
        duk_hstring *h = DUK_TVAL_GET_STRING(tv_obj);
        /*
         *  Note: currently no fast path for array index writes.
         *  They won't be possible anyway as strings are immutable.
         */
        DUK_ASSERT(key == NULL);
        arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
        DUK_ASSERT(key != NULL);
        if (key == DUK_HTHREAD_STRING_LENGTH(thr)) {
            goto fail_not_writable;
        }
        if (arr_idx != DUK__NO_ARRAY_INDEX &&
            arr_idx < DUK_HSTRING_GET_CHARLEN(h)) {
            goto fail_not_writable;
        }
        DUK_DDD(DUK_DDDPRINT("base object is a string, start lookup from string prototype"));
        curr = thr->builtins[DUK_BIDX_STRING_PROTOTYPE];
        goto lookup;  /* avoid double coercion */
    }
    case DUK_TAG_OBJECT: {
        orig = DUK_TVAL_GET_OBJECT(tv_obj);
        DUK_ASSERT(orig != NULL);
#if defined(DUK_USE_ROM_OBJECTS)
        /* With this check in place fast paths won't need read-only
         * object checks.  This is technically incorrect if there are
         * setters that cause no writes to ROM objects, but current
         * built-ins don't have such setters.
         */
        if (DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) orig)) {
            DUK_DD(DUK_DDPRINT("attempt to putprop on read-only target object"));
            goto fail_not_writable_no_pop;  /* Must avoid duk_pop() in exit path */
        }
#endif
        /* The fast path for array property put is not fully compliant:
         * If one places conflicting number-indexed properties into
         * Array.prototype (for example, a non-writable Array.prototype[7])
         * the fast path will incorrectly ignore them.
         *
         * This fast path could be made compliant by falling through
         * to the slow path if the previous value was UNUSED.  This would
         * also remove the need to check for extensibility.  Right now a
         * non-extensible array is slower than an extensible one as far
         * as writes are concerned.
         *
         * The fast path behavior is documented in more detail here:
         * tests/ecmascript/test-misc-array-fast-write.js
         */
        if (duk__putprop_shallow_fastpath_array_tval(thr, orig, tv_key, tv_val, &desc) != 0) {
            DUK_DDD(DUK_DDDPRINT("array fast path success"));
            return 1;
        }
        if (duk__putprop_fastpath_bufobj_tval(thr, orig, tv_key, tv_val) != 0) {
            DUK_DDD(DUK_DDDPRINT("base is bufobj, key is a number, bufferobject fast path"));
            return 1;
        }
#if defined(DUK_USE_ES6_PROXY)
        if (DUK_UNLIKELY(DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ(orig))) {
            duk_hobject *h_target;
            duk_bool_t tmp_bool;
            if (duk__proxy_check_prop(thr, orig, DUK_STRIDX_SET, tv_key, &h_target)) {
                /* -> [ ... trap handler ] */
                DUK_DDD(DUK_DDDPRINT("-> proxy object 'set' for key %!T", (duk_tval *) tv_key));
                duk_push_hobject(ctx, h_target);  /* target */
                duk_push_tval(ctx, tv_key);       /* P */
                duk_push_tval(ctx, tv_val);       /* V */
                duk_push_tval(ctx, tv_obj);       /* Receiver: Proxy object */
                duk_call_method(ctx, 4 /*nargs*/);
                tmp_bool = duk_to_boolean(ctx, -1);
                duk_pop(ctx);
                if (!tmp_bool) {
                    goto fail_proxy_rejected;
                }
                /* Target object must be checked for a conflicting
                 * non-configurable property.
                 */
                arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
                DUK_ASSERT(key != NULL);
                if (duk__get_own_propdesc_raw(thr, h_target, key, arr_idx, &desc, DUK_GETDESC_FLAG_PUSH_VALUE)) {
                    duk_tval *tv_targ = duk_require_tval(ctx, -1);
                    duk_bool_t datadesc_reject;
                    duk_bool_t accdesc_reject;
                    DUK_DDD(DUK_DDDPRINT("proxy 'set': target has matching property %!O, check for "
                                         "conflicting property; tv_val=%!T, tv_targ=%!T, desc.flags=0x%08lx, "
                                         "desc.get=%p, desc.set=%p",
                                         (duk_heaphdr *) key, (duk_tval *) tv_val, (duk_tval *) tv_targ,
                                         (unsigned long) desc.flags,
                                         (void *) desc.get, (void *) desc.set));
                    datadesc_reject = !(desc.flags & DUK_PROPDESC_FLAG_ACCESSOR) &&
                                      !(desc.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) &&
                                      !(desc.flags & DUK_PROPDESC_FLAG_WRITABLE) &&
                                      !duk_js_samevalue(tv_val, tv_targ);
                    accdesc_reject = (desc.flags & DUK_PROPDESC_FLAG_ACCESSOR) &&
                                     !(desc.flags & DUK_PROPDESC_FLAG_CONFIGURABLE) &&
                                     (desc.set == NULL);
                    if (datadesc_reject || accdesc_reject) {
                        DUK_ERROR_TYPE(thr, DUK_STR_PROXY_REJECTED);
                    }
                    duk_pop_2(ctx);
                } else {
                    duk_pop(ctx);
                }
                return 1;  /* success */
            }
            orig = h_target;  /* resume write to target */
            DUK_TVAL_SET_OBJECT(tv_obj, orig);
        }
#endif  /* DUK_USE_ES6_PROXY */
        curr = orig;
        break;
    }
    case DUK_TAG_BUFFER: {
        duk_hbuffer *h = DUK_TVAL_GET_BUFFER(tv_obj);
        duk_int_t pop_count = 0;
        /*
         *  Because buffer values may be looped over and read/written
         *  from, an array index fast path is important.
         */
#if defined(DUK_USE_FASTINT)
        if (DUK_TVAL_IS_FASTINT(tv_key)) {
            arr_idx = duk__tval_fastint_to_arr_idx(tv_key);
            DUK_DDD(DUK_DDDPRINT("base object buffer, key is a fast-path fastint; arr_idx %ld", (long) arr_idx));
            pop_count = 0;
        } else
#endif
        if (DUK_TVAL_IS_NUMBER(tv_key)) {
            arr_idx = duk__tval_number_to_arr_idx(tv_key);
            DUK_DDD(DUK_DDDPRINT("base object buffer, key is a fast-path number; arr_idx %ld", (long) arr_idx));
            pop_count = 0;
        } else {
            arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
            DUK_ASSERT(key != NULL);
            DUK_DDD(DUK_DDDPRINT("base object buffer, key is a non-fast-path number; after "
                                 "coercion key is %!T, arr_idx %ld",
                                 (duk_tval *) duk_get_tval(ctx, -1), (long) arr_idx));
            pop_count = 1;
        }
        if (arr_idx != DUK__NO_ARRAY_INDEX &&
            arr_idx < DUK_HBUFFER_GET_SIZE(h)) {
            duk_uint8_t *data;
            DUK_DDD(DUK_DDDPRINT("writing to buffer data at index %ld", (long) arr_idx));
            data = (duk_uint8_t *) DUK_HBUFFER_GET_DATA_PTR(thr->heap, h);
            /* XXX: duk_to_int() ensures we'll get 8 lowest bits as
             * as input is within duk_int_t range (capped outside it).
             */
#if defined(DUK_USE_FASTINT)
            /* Buffer writes are often integers. */
            if (DUK_TVAL_IS_FASTINT(tv_val)) {
                data[arr_idx] = (duk_uint8_t) DUK_TVAL_GET_FASTINT_U32(tv_val);
            }
            else
#endif
            {
                duk_push_tval(ctx, tv_val);
                data[arr_idx] = (duk_uint8_t) duk_to_uint32(ctx, -1);
                pop_count++;
            }
            duk_pop_n(ctx, pop_count);
            DUK_DDD(DUK_DDDPRINT("result: success (buffer data write)"));
            return 1;
        }
        if (pop_count == 0) {
            /* This is a pretty awkward control flow, but we need to recheck the
             * key coercion here.
             */
            arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
            DUK_ASSERT(key != NULL);
            DUK_DDD(DUK_DDDPRINT("base object buffer, key is a non-fast-path number; after "
                                 "coercion key is %!T, arr_idx %ld",
                                 (duk_tval *) duk_get_tval(ctx, -1), (long) arr_idx));
        }
        if (key == DUK_HTHREAD_STRING_LENGTH(thr) ||
            key == DUK_HTHREAD_STRING_BYTE_LENGTH(thr) ||
            key == DUK_HTHREAD_STRING_BYTE_OFFSET(thr) ||
            key == DUK_HTHREAD_STRING_BYTES_PER_ELEMENT(thr)) {
            goto fail_not_writable;
        }
        DUK_DDD(DUK_DDDPRINT("base object is a buffer, start lookup from buffer prototype"));
        curr = thr->builtins[DUK_BIDX_BUFFER_PROTOTYPE];
        goto lookup;  /* avoid double coercion */
    }
    case DUK_TAG_POINTER: {
        DUK_DDD(DUK_DDDPRINT("base object is a pointer, start lookup from pointer prototype"));
        curr = thr->builtins[DUK_BIDX_POINTER_PROTOTYPE];
        break;
    }
    case DUK_TAG_LIGHTFUNC: {
        /* All lightfunc own properties are non-writable and the lightfunc
         * is considered non-extensible.  However, the write may be captured
         * by an inherited setter which means we can't stop the lookup here.
         */
        arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
        if (duk__key_is_lightfunc_ownprop(thr, key)) {
            goto fail_not_writable;
        }
        DUK_DDD(DUK_DDDPRINT("base object is a lightfunc, start lookup from function prototype"));
        curr = thr->builtins[DUK_BIDX_FUNCTION_PROTOTYPE];
        goto lookup;  /* avoid double coercion */
    }
#if defined(DUK_USE_FASTINT)
    case DUK_TAG_FASTINT:
#endif
    default: {
        /* number */
        DUK_DDD(DUK_DDDPRINT("base object is a number, start lookup from number prototype"));
        DUK_ASSERT(DUK_TVAL_IS_NUMBER(tv_obj));
        curr = thr->builtins[DUK_BIDX_NUMBER_PROTOTYPE];
        break;
    }
    }
    DUK_ASSERT(key == NULL);
    arr_idx = duk__push_tval_to_hstring_arr_idx(ctx, tv_key, &key);
    DUK_ASSERT(key != NULL);
 lookup:
    /*
     *  Check whether the property already exists in the prototype chain.
     *  Note that the actual write goes into the original base object
     *  (except if an accessor property captures the write).
     */
    /* [key] */
    DUK_ASSERT(curr != NULL);
    sanity = DUK_HOBJECT_PROTOTYPE_CHAIN_SANITY;
    do {
        if (!duk__get_own_propdesc_raw(thr, curr, key, arr_idx, &desc, 0 /*flags*/)) {  /* don't push value */
            goto next_in_chain;
        }
        if (desc.flags & DUK_PROPDESC_FLAG_ACCESSOR) {
            /*
             *  Found existing accessor property (own or inherited).
             *  Call setter with 'this' set to orig, and value as the only argument.
             *  Setter calls are OK even for ROM objects.
             *
             *  Note: no exotic arguments object behavior, because [[Put]] never
             *  calls [[DefineOwnProperty]] (E5 Section 8.12.5, step 5.b).
             */
            duk_hobject *setter;
            DUK_DD(DUK_DDPRINT("put to an own or inherited accessor, calling setter"));
            setter = DUK_HOBJECT_E_GET_VALUE_SETTER(thr->heap, curr, desc.e_idx);
            if (!setter) {
                goto fail_no_setter;
            }
            duk_push_hobject(ctx, setter);
            duk_push_tval(ctx, tv_obj);  /* note: original, uncoerced base */
            duk_push_tval(ctx, tv_val);  /* [key setter this val] */
#ifdef DUK_USE_NONSTD_SETTER_KEY_ARGUMENT
            duk_dup(ctx, -4);
            duk_call_method(ctx, 2);     /* [key setter this val key] -> [key retval] */
#else
            duk_call_method(ctx, 1);     /* [key setter this val] -> [key retval] */
#endif
            duk_pop(ctx);                /* ignore retval -> [key] */
            goto success_no_arguments_exotic;
        }
        if (orig == NULL) {
            /*
             *  Found existing own or inherited plain property, but original
             *  base is a primitive value.
             */
            DUK_DD(DUK_DDPRINT("attempt to create a new property in a primitive base object"));
            goto fail_base_primitive;
        }
        if (curr != orig) {
            /*
             *  Found existing inherited plain property.
             *  Do an access control check, and if OK, write
             *  new property to 'orig'.
             */
            if (!DUK_HOBJECT_HAS_EXTENSIBLE(orig)) {
                DUK_DD(DUK_DDPRINT("found existing inherited plain property, but original object is not extensible"));
                goto fail_not_extensible;
            }
            if (!(desc.flags & DUK_PROPDESC_FLAG_WRITABLE)) {
                DUK_DD(DUK_DDPRINT("found existing inherited plain property, original object is extensible, but inherited property is not writable"));
                goto fail_not_writable;
            }
            DUK_DD(DUK_DDPRINT("put to new property, object extensible, inherited property found and is writable"));
            goto create_new;
        } else {
            /*
             *  Found existing own (non-inherited) plain property.
             *  Do an access control check and update in place.
             */
            if (!(desc.flags & DUK_PROPDESC_FLAG_WRITABLE)) {
                DUK_DD(DUK_DDPRINT("found existing own (non-inherited) plain property, but property is not writable"));
                goto fail_not_writable;
            }
            if (desc.flags & DUK_PROPDESC_FLAG_VIRTUAL) {
                DUK_DD(DUK_DDPRINT("found existing own (non-inherited) virtual property, property is writable"));
                if (DUK_HOBJECT_IS_BUFFEROBJECT(curr)) {
                    duk_hbufferobject *h_bufobj;
                    duk_uint_t byte_off;
                    duk_small_uint_t elem_size;
                    h_bufobj = (duk_hbufferobject *) curr;
                    DUK_ASSERT_HBUFFEROBJECT_VALID(h_bufobj);
                    DUK_DD(DUK_DDPRINT("writable virtual property is in buffer object"));
                    /* Careful with wrapping: arr_idx upshift may easily wrap, whereas
                     * length downshift won't.
                     */
                    if (arr_idx < (h_bufobj->length >> h_bufobj->shift)) {
                        duk_uint8_t *data;
                        DUK_DDD(DUK_DDDPRINT("writing to buffer data at index %ld", (long) arr_idx));
                        DUK_ASSERT(arr_idx != DUK__NO_ARRAY_INDEX);  /* index/length check guarantees */
                        byte_off = arr_idx << h_bufobj->shift;       /* no wrap assuming h_bufobj->length is valid */
                        elem_size = 1 << h_bufobj->shift;
                        /* Coerce to number before validating pointers etc so that the
                         * number coercions in duk_hbufferobject_validated_write() are
                         * guaranteed to be side effect free and not invalidate the
                         * pointer checks we do here.
                         */
                        duk_push_tval(ctx, tv_val);
                        duk_to_number(ctx, -1);
                        if (h_bufobj->buf != NULL && DUK_HBUFFEROBJECT_VALID_BYTEOFFSET_EXCL(h_bufobj, byte_off + elem_size)) {
                            data = (duk_uint8_t *) DUK_HBUFFER_GET_DATA_PTR(thr->heap, h_bufobj->buf) + h_bufobj->offset + byte_off;
                            duk_hbufferobject_validated_write(ctx, h_bufobj, data, elem_size);
                        } else {
                            DUK_D(DUK_DPRINT("bufferobject access out of underlying buffer, ignoring (write skipped)"));
                        }
                        duk_pop(ctx);
                        goto success_no_arguments_exotic;
                    }
                }
                goto fail_internal;  /* should not happen */
            }
            DUK_DD(DUK_DDPRINT("put to existing own plain property, property is writable"));
            goto update_old;
        }
        DUK_UNREACHABLE();
     next_in_chain:
        /* XXX: option to pretend property doesn't exist if sanity limit is
         * hit might be useful.
         */
        if (sanity-- == 0) {
            DUK_ERROR_RANGE(thr, DUK_STR_PROTOTYPE_CHAIN_LIMIT);
        }
        curr = DUK_HOBJECT_GET_PROTOTYPE(thr->heap, curr);
    } while (curr);
    /*
     *  Property not found in prototype chain.
     */
    DUK_DDD(DUK_DDDPRINT("property not found in prototype chain"));
    if (orig == NULL) {
        DUK_DD(DUK_DDPRINT("attempt to create a new property in a primitive base object"));
        goto fail_base_primitive;
    }
    if (!DUK_HOBJECT_HAS_EXTENSIBLE(orig)) {
        DUK_DD(DUK_DDPRINT("put to a new property (not found in prototype chain), but original object not extensible"));
        goto fail_not_extensible;
    }
    goto create_new;
 update_old:
    /*
     *  Update an existing property of the base object.
     */
    /* [key] */
    DUK_DDD(DUK_DDDPRINT("update an existing property of the original object"));
    DUK_ASSERT(orig != NULL);
#if defined(DUK_USE_ROM_OBJECTS)
    /* This should not happen because DUK_TAG_OBJECT case checks
     * for this already, but check just in case.
     */
    if (DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) orig)) {
        goto fail_not_writable;
    }
#endif
    /* Although there are writable virtual properties (e.g. plain buffer
     * and buffer object number indices), they are handled before we come
     * here.
     */
    DUK_ASSERT((desc.flags & DUK_PROPDESC_FLAG_VIRTUAL) == 0);
    DUK_ASSERT(desc.a_idx >= 0 || desc.e_idx >= 0);
    if (DUK_HOBJECT_HAS_EXOTIC_ARRAY(orig) &&
        key == DUK_HTHREAD_STRING_LENGTH(thr)) {
        /*
         *  Write to 'length' of an array is a very complex case
         *  handled in a helper which updates both the array elements
         *  and writes the new 'length'.  The write may result in an
         *  unconditional RangeError or a partial write (indicated
         *  by a return code).
         *
         *  Note: the helper has an unnecessary writability check
         *  for 'length', we already know it is writable.
         */
        DUK_DDD(DUK_DDDPRINT("writing existing 'length' property to array exotic, invoke complex helper"));
        /* XXX: the helper currently assumes stack top contains new
         * 'length' value and the whole calling convention is not very
         * compatible with what we need.
         */
        duk_push_tval(ctx, tv_val);  /* [key val] */
        rc = duk__handle_put_array_length(thr, orig);
        duk_pop(ctx);  /* [key val] -> [key] */
        if (!rc) {
            goto fail_array_length_partial;
        }
        /* key is 'length', cannot match argument exotic behavior */
        goto success_no_arguments_exotic;
    }
    if (desc.e_idx >= 0) {
        tv = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, orig, desc.e_idx);
        DUK_DDD(DUK_DDDPRINT("previous entry value: %!iT", (duk_tval *) tv));
        DUK_TVAL_SET_TVAL_UPDREF(thr, tv, tv_val);  /* side effects */
        /* don't touch property attributes or hash part */
        DUK_DD(DUK_DDPRINT("put to an existing entry at index %ld -> new value %!iT",
                           (long) desc.e_idx, (duk_tval *) tv));
    } else {
        /* Note: array entries are always writable, so the writability check
         * above is pointless for them.  The check could be avoided with some
         * refactoring but is probably not worth it.
         */
        DUK_ASSERT(desc.a_idx >= 0);
        tv = DUK_HOBJECT_A_GET_VALUE_PTR(thr->heap, orig, desc.a_idx);
        DUK_DDD(DUK_DDDPRINT("previous array value: %!iT", (duk_tval *) tv));
        DUK_TVAL_SET_TVAL_UPDREF(thr, tv, tv_val);  /* side effects */
        DUK_DD(DUK_DDPRINT("put to an existing array entry at index %ld -> new value %!iT",
                           (long) desc.a_idx, (duk_tval *) tv));
    }
    /* Regardless of whether property is found in entry or array part,
     * it may have arguments exotic behavior (array indices may reside
     * in entry part for abandoned / non-existent array parts).
     */
    goto success_with_arguments_exotic;
 create_new:
    /*
     *  Create a new property in the original object.
     *
     *  Exotic properties need to be reconsidered here from a write
     *  perspective (not just property attributes perspective).
     *  However, the property does not exist in the object already,
     *  so this limits the kind of exotic properties that apply.
     */
    /* [key] */
    DUK_DDD(DUK_DDDPRINT("create new property to original object"));
    DUK_ASSERT(orig != NULL);
#if defined(DUK_USE_ROM_OBJECTS)
    /* This should not happen because DUK_TAG_OBJECT case checks
     * for this already, but check just in case.
     */
    if (DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) orig)) {
        goto fail_not_writable;
    }
#endif
    /* Not possible because array object 'length' is present
     * from its creation and cannot be deleted, and is thus
     * caught as an existing property above.
     */
    DUK_ASSERT(!(DUK_HOBJECT_HAS_EXOTIC_ARRAY(orig) &&
                 key == DUK_HTHREAD_STRING_LENGTH(thr)));
    if (DUK_HOBJECT_HAS_EXOTIC_ARRAY(orig) &&
        arr_idx != DUK__NO_ARRAY_INDEX) {
        /* automatic length update */
        duk_uint32_t old_len;
        old_len = duk__get_old_array_length(thr, orig, &desc);
        if (arr_idx >= old_len) {
            DUK_DDD(DUK_DDDPRINT("write new array entry requires length update "
                                 "(arr_idx=%ld, old_len=%ld)",
                                 (long) arr_idx, (long) old_len));
            if (!(desc.flags & DUK_PROPDESC_FLAG_WRITABLE)) {
                DUK_DD(DUK_DDPRINT("attempt to extend array, but array 'length' is not writable"));
                goto fail_not_writable;
            }
            /* Note: actual update happens once write has been completed
             * without error below.  The write should always succeed
             * from a specification viewpoint, but we may e.g. run out
             * of memory.  It's safer in this order.
             */
            DUK_ASSERT(arr_idx != 0xffffffffUL);
            new_array_length = arr_idx + 1;  /* flag for later write */
        } else {
            DUK_DDD(DUK_DDDPRINT("write new array entry does not require length update "
                                 "(arr_idx=%ld, old_len=%ld)",
                                 (long) arr_idx, (long) old_len));
        }
    }
 /* write_to_array_part: */
    /*
     *  Write to array part?
     *
     *  Note: array abandonding requires a property resize which uses
     *  'rechecks' valstack for temporaries and may cause any existing
     *  valstack pointers to be invalidated.  To protect against this,
     *  tv_obj, tv_key, and tv_val are copies of the original inputs.
     */
    if (arr_idx != DUK__NO_ARRAY_INDEX &&
        DUK_HOBJECT_HAS_ARRAY_PART(orig)) {
        if (arr_idx < DUK_HOBJECT_GET_ASIZE(orig)) {
            goto no_array_growth;
        }
        /*
         *  Array needs to grow, but we don't want it becoming too sparse.
         *  If it were to become sparse, abandon array part, moving all
         *  array entries into the entries part (for good).
         *
         *  Since we don't keep track of actual density (used vs. size) of
         *  the array part, we need to estimate somehow.  The check is made
         *  in two parts:
         *
         *    - Check whether the resize need is small compared to the
         *      current size (relatively); if so, resize without further
         *      checking (essentially we assume that the original part is
         *      "dense" so that the result would be dense enough).
         *
         *    - Otherwise, compute the resize using an actual density
         *      measurement based on counting the used array entries.
         */
        DUK_DDD(DUK_DDDPRINT("write to new array requires array resize, decide whether to do a "
                             "fast resize without abandon check (arr_idx=%ld, old_size=%ld)",
                             (long) arr_idx, (long) DUK_HOBJECT_GET_ASIZE(orig)));
        if (duk__abandon_array_slow_check_required(arr_idx, DUK_HOBJECT_GET_ASIZE(orig))) {
            duk_uint32_t old_used;
            duk_uint32_t old_size;
            DUK_DDD(DUK_DDDPRINT("=> fast check is NOT OK, do slow check for array abandon"));
            duk__compute_a_stats(thr, orig, &old_used, &old_size);
            DUK_DDD(DUK_DDDPRINT("abandon check, array stats: old_used=%ld, old_size=%ld, arr_idx=%ld",
                                 (long) old_used, (long) old_size, (long) arr_idx));
            /* Note: intentionally use approximations to shave a few instructions:
             *   a_used = old_used  (accurate: old_used + 1)
             *   a_size = arr_idx   (accurate: arr_idx + 1)
             */
            if (duk__abandon_array_density_check(old_used, arr_idx)) {
                DUK_DD(DUK_DDPRINT("write to new array entry beyond current length, "
                                   "decided to abandon array part (would become too sparse)"));
                /* abandoning requires a props allocation resize and
                 * 'rechecks' the valstack, invalidating any existing
                 * valstack value pointers!
                 */
                duk__abandon_array_checked(thr, orig);
                DUK_ASSERT(!DUK_HOBJECT_HAS_ARRAY_PART(orig));
                goto write_to_entry_part;
            }
            DUK_DDD(DUK_DDDPRINT("=> decided to keep array part"));
        } else {
            DUK_DDD(DUK_DDDPRINT("=> fast resize is OK"));
        }
        DUK_DD(DUK_DDPRINT("write to new array entry beyond current length, "
                           "decided to extend current allocation"));
        duk__grow_props_for_array_item(thr, orig, arr_idx);
     no_array_growth:
        /* Note: assume array part is comprehensive, so that either
         * the write goes to the array part, or we've abandoned the
         * array above (and will not come here).
         */
        DUK_ASSERT(DUK_HOBJECT_HAS_ARRAY_PART(orig));
        DUK_ASSERT(arr_idx < DUK_HOBJECT_GET_ASIZE(orig));
        tv = DUK_HOBJECT_A_GET_VALUE_PTR(thr->heap, orig, arr_idx);
        /* prev value must be unused, no decref */
        DUK_ASSERT(DUK_TVAL_IS_UNUSED(tv));
        DUK_TVAL_SET_TVAL(tv, tv_val);
        DUK_TVAL_INCREF(thr, tv);
        DUK_DD(DUK_DDPRINT("put to new array entry: %ld -> %!T",
                           (long) arr_idx, (duk_tval *) tv));
        /* Note: array part values are [[Writable]], [[Enumerable]],
         * and [[Configurable]] which matches the required attributes
         * here.
         */
        goto entry_updated;
    }
 write_to_entry_part:
    /*
     *  Write to entry part
     */
    /* entry allocation updates hash part and increases the key
     * refcount; may need a props allocation resize but doesn't
     * 'recheck' the valstack.
     */
    e_idx = duk__alloc_entry_checked(thr, orig, key);
    DUK_ASSERT(e_idx >= 0);
    tv = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, orig, e_idx);
    /* prev value can be garbage, no decref */
    DUK_TVAL_SET_TVAL(tv, tv_val);
    DUK_TVAL_INCREF(thr, tv);
    DUK_HOBJECT_E_SET_FLAGS(thr->heap, orig, e_idx, DUK_PROPDESC_FLAGS_WEC);
    goto entry_updated;
 entry_updated:
    /*
     *  Possible pending array length update, which must only be done
     *  if the actual entry write succeeded.
     */
    if (new_array_length > 0) {
        /*
         *  Note: zero works as a "no update" marker because the new length
         *  can never be zero after a new property is written.
         *
         *  Note: must re-lookup because calls above (e.g. duk__alloc_entry_checked())
         *  may realloc and compact properties and hence change e_idx.
         */
        DUK_DDD(DUK_DDDPRINT("write successful, pending array length update to: %ld",
                             (long) new_array_length));
        rc = duk__get_own_propdesc_raw(thr, orig, DUK_HTHREAD_STRING_LENGTH(thr), DUK__NO_ARRAY_INDEX, &desc, 0 /*flags*/);  /* don't push value */
        DUK_UNREF(rc);
        DUK_ASSERT(rc != 0);
        DUK_ASSERT(desc.e_idx >= 0);
        tv = DUK_HOBJECT_E_GET_VALUE_TVAL_PTR(thr->heap, orig, desc.e_idx);
        DUK_ASSERT(DUK_TVAL_IS_NUMBER(tv));
        /* no need for decref/incref because value is a number */
        DUK_TVAL_SET_FASTINT_U32(tv, new_array_length);
    }
    /*
     *  Arguments exotic behavior not possible for new properties: all
     *  magically bound properties are initially present in the arguments
     *  object, and if they are deleted, the binding is also removed from
     *  parameter map.
     */
    goto success_no_arguments_exotic;
 success_with_arguments_exotic:
    /*
     *  Arguments objects have exotic [[DefineOwnProperty]] which updates
     *  the internal 'map' of arguments for writes to currently mapped
     *  arguments.  More conretely, writes to mapped arguments generate
     *  a write to a bound variable.
     *
     *  The [[Put]] algorithm invokes [[DefineOwnProperty]] for existing
     *  data properties and new properties, but not for existing accessors.
     *  Hence, in E5 Section 10.6 ([[DefinedOwnProperty]] algorithm), we
     *  have a Desc with 'Value' (and possibly other properties too), and
     *  we end up in step 5.b.i.
     */
    if (arr_idx != DUK__NO_ARRAY_INDEX &&
        DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS(orig)) {
        /* Note: only numbered indices are relevant, so arr_idx fast reject
         * is good (this is valid unless there are more than 4**32-1 arguments).
         */
        DUK_DDD(DUK_DDDPRINT("putprop successful, arguments exotic behavior needed"));
        /* Note: we can reuse 'desc' here */
        /* XXX: top of stack must contain value, which helper doesn't touch,
         * rework to use tv_val directly?
         */
        duk_push_tval(ctx, tv_val);
        (void) duk__check_arguments_map_for_put(thr, orig, key, &desc, throw_flag);
        duk_pop(ctx);
    }
    /* fall thru */
 success_no_arguments_exotic:
    /* shared exit path now */
    DUK_DDD(DUK_DDDPRINT("result: success"));
    duk_pop(ctx);  /* remove key */
    return 1;
#if defined(DUK_USE_ES6_PROXY)
 fail_proxy_rejected:
    DUK_DDD(DUK_DDDPRINT("result: error, proxy rejects"));
    if (throw_flag) {
        DUK_ERROR_TYPE(thr, DUK_STR_PROXY_REJECTED);
    }
    /* Note: no key on stack */
    return 0;
#endif
 fail_base_primitive:
    DUK_DDD(DUK_DDDPRINT("result: error, base primitive"));
    if (throw_flag) {
#if defined(DUK_USE_PARANOID_ERRORS)
        DUK_ERROR_TYPE(thr, DUK_STR_INVALID_BASE);
#else
        DUK_ERROR_FMT2(thr, DUK_ERR_TYPE_ERROR, "cannot write property %s of %s",
                       duk_push_string_tval_readable(ctx, tv_key), duk_push_string_tval_readable(ctx, tv_obj));
#endif
    }
    duk_pop(ctx);  /* remove key */
    return 0;
 fail_not_extensible:
    DUK_DDD(DUK_DDDPRINT("result: error, not extensible"));
    if (throw_flag) {
        DUK_ERROR_TYPE(thr, DUK_STR_NOT_EXTENSIBLE);
    }
    duk_pop(ctx);  /* remove key */
    return 0;
 fail_not_writable:
    DUK_DDD(DUK_DDDPRINT("result: error, not writable"));
    if (throw_flag) {
        DUK_ERROR_TYPE(thr, DUK_STR_NOT_WRITABLE);
    }
    duk_pop(ctx);  /* remove key */
    return 0;
#if defined(DUK_USE_ROM_OBJECTS)
 fail_not_writable_no_pop:
    DUK_DDD(DUK_DDDPRINT("result: error, not writable"));
    if (throw_flag) {
        DUK_ERROR_TYPE(thr, DUK_STR_NOT_WRITABLE);
    }
    return 0;
#endif
 fail_array_length_partial:
    DUK_DDD(DUK_DDDPRINT("result: error, array length write only partially successful"));
    if (throw_flag) {
        DUK_ERROR_TYPE(thr, DUK_STR_ARRAY_LENGTH_WRITE_FAILED);
    }
    duk_pop(ctx);  /* remove key */
    return 0;
References duk_propdesc::a_idx, duk_hbufferobject::buf, duk_hthread::builtins, duk__abandon_array_checked(), duk__abandon_array_density_check(), duk__abandon_array_slow_check_required(), duk__alloc_entry_checked(), duk__check_arguments_map_for_put(), duk__compute_a_stats(), duk__get_old_array_length(), duk__get_own_propdesc_raw(), duk__grow_props_for_array_item(), duk__handle_put_array_length(), duk__key_is_lightfunc_ownprop(), DUK__NO_ARRAY_INDEX, duk__proxy_check_prop(), duk__push_tval_to_hstring_arr_idx(), duk__putprop_fastpath_bufobj_tval(), duk__putprop_shallow_fastpath_array_tval(), duk__tval_number_to_arr_idx(), DUK__VALSTACK_SPACE, DUK_ASSERT, DUK_ASSERT_HBUFFEROBJECT_VALID, DUK_ASSERT_VALSTACK_SPACE, DUK_BIDX_BOOLEAN_PROTOTYPE, DUK_BIDX_BUFFER_PROTOTYPE, DUK_BIDX_FUNCTION_PROTOTYPE, DUK_BIDX_NUMBER_PROTOTYPE, DUK_BIDX_POINTER_PROTOTYPE, DUK_BIDX_STRING_PROTOTYPE, duk_call_method(), DUK_D, DUK_DD, DUK_DDD, DUK_DDDPRINT, DUK_DDPRINT, DUK_DPRINT, duk_dup(), DUK_ERR_TYPE_ERROR, DUK_ERROR_FMT2, DUK_ERROR_INTERNAL_DEFMSG, DUK_ERROR_RANGE, DUK_ERROR_TYPE, duk_get_tval(), DUK_GETDESC_FLAG_PUSH_VALUE, DUK_HBUFFER_GET_DATA_PTR, DUK_HBUFFER_GET_SIZE, DUK_HBUFFEROBJECT_VALID_BYTEOFFSET_EXCL, duk_hbufferobject_validated_write(), DUK_HEAPHDR_HAS_READONLY, DUK_HOBJECT_A_GET_VALUE_PTR, DUK_HOBJECT_E_GET_VALUE_SETTER, DUK_HOBJECT_E_GET_VALUE_TVAL_PTR, DUK_HOBJECT_E_SET_FLAGS, DUK_HOBJECT_GET_ASIZE, DUK_HOBJECT_GET_PROTOTYPE, DUK_HOBJECT_HAS_ARRAY_PART, DUK_HOBJECT_HAS_EXOTIC_ARGUMENTS, DUK_HOBJECT_HAS_EXOTIC_ARRAY, DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ, DUK_HOBJECT_HAS_EXTENSIBLE, DUK_HOBJECT_IS_BUFFEROBJECT, DUK_HOBJECT_PROTOTYPE_CHAIN_SANITY, DUK_HSTRING_GET_CHARLEN, DUK_HTHREAD_STRING_BYTE_LENGTH, DUK_HTHREAD_STRING_BYTE_OFFSET, DUK_HTHREAD_STRING_BYTES_PER_ELEMENT, DUK_HTHREAD_STRING_LENGTH, duk_js_samevalue, duk_pop(), duk_pop_2(), duk_pop_n(), DUK_PROPDESC_FLAG_ACCESSOR, DUK_PROPDESC_FLAG_CONFIGURABLE, DUK_PROPDESC_FLAG_VIRTUAL, DUK_PROPDESC_FLAG_WRITABLE, DUK_PROPDESC_FLAGS_WEC, duk_push_hobject(), duk_push_string_tval_readable(), duk_push_tval(), duk_require_tval(), DUK_STR_ARRAY_LENGTH_WRITE_FAILED, DUK_STR_INVALID_BASE, DUK_STR_NOT_EXTENSIBLE, DUK_STR_NOT_WRITABLE, DUK_STR_PROTOTYPE_CHAIN_LIMIT, DUK_STR_PROXY_REJECTED, DUK_STR_SETTER_UNDEFINED, DUK_STRIDX_SET, DUK_TAG_BOOLEAN, DUK_TAG_BUFFER, DUK_TAG_LIGHTFUNC, DUK_TAG_NULL, DUK_TAG_OBJECT, DUK_TAG_POINTER, DUK_TAG_STRING, DUK_TAG_UNDEFINED, duk_to_boolean(), duk_to_number(), duk_to_uint32(), DUK_TVAL_GET_BUFFER, DUK_TVAL_GET_OBJECT, DUK_TVAL_GET_STRING, DUK_TVAL_GET_TAG, DUK_TVAL_INCREF, DUK_TVAL_IS_NUMBER, DUK_TVAL_IS_UNUSED, DUK_TVAL_SET_FASTINT_U32, DUK_TVAL_SET_OBJECT, DUK_TVAL_SET_TVAL, DUK_TVAL_SET_TVAL_UPDREF, DUK_UNLIKELY, DUK_UNREACHABLE, DUK_UNREF, duk_propdesc::e_idx, duk_propdesc::flags, duk_propdesc::get, duk_hthread::heap, duk_hbufferobject::length, NULL, duk_hbufferobject::offset, duk_propdesc::set, and duk_hbufferobject::shift.
Referenced by duk__js_execute_bytecode_inner(), duk__put_prop_shared(), duk__putvar_helper(), duk_hobject_get_length(), and duk_hobject_set_length().
duk_hobject_run_finalizer()
DUK_INTERNAL_DECL void duk_hobject_run_finalizer (duk_hthread * thr, duk_hobject * obj)
Definition at line 46711 of file duktape-1.5.2/src-noline/duktape.c.
{
        DUK_DDD(DUK_DDDPRINT("-> no finalizer or finalizer not callable"));
        return 0;
    }
    duk_dup(ctx, -2);
    duk_push_boolean(ctx, DUK_HEAP_HAS_FINALIZER_NORESCUE(thr->heap));
    DUK_DDD(DUK_DDDPRINT("-> finalizer found, calling finalizer"));
    duk_call(ctx, 2);  /* [ ... obj finalizer obj heapDestruct ]  -> [ ... obj retval ] */
    DUK_DDD(DUK_DDDPRINT("finalizer finished successfully"));
    return 0;
    /* Note: we rely on duk_safe_call() to fix up the stack for the caller,
     * so we don't need to pop stuff here.  There is no return value;
     * caller determines rescued status based on object refcount.
     */
}
DUK_INTERNAL void duk_hobject_run_finalizer(duk_hthread *thr, duk_hobject *obj) {
    duk_context *ctx = (duk_context *) thr;
    duk_ret_t rc;
#ifdef DUK_USE_ASSERTIONS
    duk_idx_t entry_top;
#endif
    DUK_DDD(DUK_DDDPRINT("running object finalizer for object: %p", (void *) obj));
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(ctx != NULL);
    DUK_ASSERT(obj != NULL);
    DUK_ASSERT_VALSTACK_SPACE(thr, 1);
#ifdef DUK_USE_ASSERTIONS
    entry_top = duk_get_top(ctx);
#endif
    /*
     *  Get and call the finalizer.  All of this must be wrapped
     *  in a protected call, because even getting the finalizer
     *  may trigger an error (getter may throw one, for instance).
     */
    DUK_ASSERT(!DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) obj));
    if (DUK_HEAPHDR_HAS_FINALIZED((duk_heaphdr *) obj)) {
        DUK_D(DUK_DPRINT("object already finalized, avoid running finalizer twice: %!O", obj));
        return;
    }
    DUK_HEAPHDR_SET_FINALIZED((duk_heaphdr *) obj);  /* ensure never re-entered until rescue cycle complete */
    if (DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ(obj)) {
        /* This shouldn't happen; call sites should avoid looking up
         * _Finalizer "through" a Proxy, but ignore if we come here
         * with a Proxy to avoid finalizer re-entry.
         */
        DUK_D(DUK_DPRINT("object is a proxy, skip finalizer call"));
        return;
    }
    /* XXX: use a NULL error handler for the finalizer call? */
References duk__finalize_helper(), DUK_ASSERT, DUK_ASSERT_TOP, DUK_ASSERT_VALSTACK_SPACE, DUK_D, DUK_DDD, DUK_DDDPRINT, DUK_DPRINT, DUK_EXEC_SUCCESS, duk_get_top(), duk_get_tval(), DUK_HEAPHDR_HAS_FINALIZED, DUK_HEAPHDR_HAS_READONLY, DUK_HEAPHDR_SET_FINALIZED, DUK_HOBJECT_HAS_EXOTIC_PROXYOBJ, duk_pop_2(), duk_push_hobject(), duk_safe_call(), and NULL.
Referenced by duk__free_run_finalizers(), duk__refzero_free_pending(), and duk__run_object_finalizers().
duk_hobject_set_length()
DUK_INTERNAL_DECL void duk_hobject_set_length (duk_hthread * thr, duk_hobject * obj, duk_uint32_t length)
Definition at line 51806 of file duktape-1.5.2/src-noline/duktape.c.
References DUK_GET_TVAL_NEGIDX, duk_hobject_putprop(), duk_pop_n(), duk_push_hobject(), duk_push_hstring_stridx(), duk_push_u32, and DUK_STRIDX_LENGTH.
Referenced by duk__js_execute_bytecode_inner(), duk_hobject_set_length_zero(), and duk_set_length().
duk_hobject_set_length_zero()
DUK_INTERNAL_DECL void duk_hobject_set_length_zero (duk_hthread * thr, duk_hobject * obj)
Definition at line 51819 of file duktape-1.5.2/src-noline/duktape.c.
References duk_hobject_set_length().
Referenced by duk__reset_func_for_pass2().
duk_hobject_set_prototype_updref()
DUK_INTERNAL_DECL void duk_hobject_set_prototype_updref (duk_hthread * thr, duk_hobject * h, duk_hobject * p)
Definition at line 46804 of file duktape-1.5.2/src-noline/duktape.c.
                    {
            return 1;
        }
        if (sanity-- == 0) {
            if (ignore_loop) {
                break;
            } else {
                DUK_ERROR_RANGE(thr, DUK_STR_PROTOTYPE_CHAIN_LIMIT);
            }
        }
        h = DUK_HOBJECT_GET_PROTOTYPE(thr->heap, h);
    } while (h);
    return 0;
References DUK_ASSERT, DUK_HOBJECT_DECREF_ALLOWNULL, DUK_HOBJECT_GET_PROTOTYPE, DUK_HOBJECT_INCREF_ALLOWNULL, DUK_HOBJECT_SET_PROTOTYPE, DUK_UNREF, and duk_hthread::heap.
duk_hthread_alloc()
DUK_INTERNAL_DECL duk_hthread * duk_hthread_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 45977 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_hthread *res;
    res = (duk_hthread *) DUK_ALLOC(heap, sizeof(duk_hthread));
    if (!res) {
        return NULL;
    }
    DUK_MEMZERO(res, sizeof(duk_hthread));
    duk__init_object_parts(heap, &res->obj, hobject_flags);
#ifdef DUK_USE_EXPLICIT_NULL_INIT
    res->ptr_curr_pc = NULL;
    res->heap = NULL;
    res->valstack = NULL;
    res->valstack_end = NULL;
    res->valstack_bottom = NULL;
    res->valstack_top = NULL;
    res->callstack = NULL;
    res->catchstack = NULL;
    res->resumer = NULL;
    res->compile_ctx = NULL,
#ifdef DUK_USE_HEAPPTR16
    res->strs16 = NULL;
#else
    res->strs = NULL;
#endif
References duk_hthread::builtins, duk_hthread::callstack, duk_hthread::callstack_max, duk_hthread::catchstack, duk_hthread::catchstack_max, duk_hthread::compile_ctx, duk__init_object_parts(), DUK_ALLOC, DUK_ASSERT, DUK_CALLSTACK_DEFAULT_MAX, DUK_CATCHSTACK_DEFAULT_MAX, DUK_MEMZERO, DUK_NUM_BUILTINS, DUK_VALSTACK_DEFAULT_MAX, duk_hthread::heap, NULL, duk_hthread::obj, duk_hthread::ptr_curr_pc, duk_hthread::resumer, duk_hthread::strict, duk_hthread::strs, duk_hthread::valstack, duk_hthread::valstack_bottom, duk_hthread::valstack_end, duk_hthread::valstack_max, and duk_hthread::valstack_top.
Referenced by duk__init_heap_thread(), and duk_push_thread_raw().
Variable Documentation
duk_class_number_to_stridx
DUK_INTERNAL_DECL duk_uint8_t duk_class_number_to_stridx[32]
Definition at line 820 of file duktape-1.8.0/src-separate/duk_hobject.h.