Github User Fetcher: duk_api_object.c File Reference
duk_api_object.c File Reference
#include "duk_internal.h"
Functions
DUK_EXTERNAL duk_bool_t duk_get_prop (duk_context *ctx, duk_idx_t obj_index)
DUK_EXTERNAL duk_bool_t duk_get_prop_string (duk_context *ctx, duk_idx_t obj_index, const char *key)
DUK_EXTERNAL duk_bool_t duk_get_prop_index (duk_context *ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
DUK_INTERNAL duk_bool_t duk_get_prop_stridx (duk_context *ctx, duk_idx_t obj_index, duk_small_int_t stridx)
DUK_INTERNAL duk_bool_t duk_get_prop_stridx_boolean (duk_context *ctx, duk_idx_t obj_index, duk_small_int_t stridx, duk_bool_t *out_has_prop)
DUK_LOCAL duk_bool_t duk__put_prop_shared (duk_context *ctx, duk_idx_t obj_idx, duk_idx_t idx_key)
DUK_EXTERNAL duk_bool_t duk_put_prop (duk_context *ctx, duk_idx_t obj_idx)
DUK_EXTERNAL duk_bool_t duk_put_prop_string (duk_context *ctx, duk_idx_t obj_idx, const char *key)
DUK_EXTERNAL duk_bool_t duk_put_prop_index (duk_context *ctx, duk_idx_t obj_idx, duk_uarridx_t arr_idx)
DUK_INTERNAL duk_bool_t duk_put_prop_stridx (duk_context *ctx, duk_idx_t obj_idx, duk_small_int_t stridx)
DUK_EXTERNAL duk_bool_t duk_del_prop (duk_context *ctx, duk_idx_t obj_index)
DUK_EXTERNAL duk_bool_t duk_del_prop_string (duk_context *ctx, duk_idx_t obj_index, const char *key)
DUK_EXTERNAL duk_bool_t duk_del_prop_index (duk_context *ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
DUK_INTERNAL duk_bool_t duk_del_prop_stridx (duk_context *ctx, duk_idx_t obj_index, duk_small_int_t stridx)
DUK_EXTERNAL duk_bool_t duk_has_prop (duk_context *ctx, duk_idx_t obj_index)
DUK_EXTERNAL duk_bool_t duk_has_prop_string (duk_context *ctx, duk_idx_t obj_index, const char *key)
DUK_EXTERNAL duk_bool_t duk_has_prop_index (duk_context *ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
DUK_INTERNAL duk_bool_t duk_has_prop_stridx (duk_context *ctx, duk_idx_t obj_index, duk_small_int_t stridx)
DUK_INTERNAL void duk_xdef_prop (duk_context *ctx, duk_idx_t obj_index, duk_small_uint_t desc_flags)
DUK_INTERNAL void duk_xdef_prop_index (duk_context *ctx, duk_idx_t obj_index, duk_uarridx_t arr_index, duk_small_uint_t desc_flags)
DUK_INTERNAL void duk_xdef_prop_stridx (duk_context *ctx, duk_idx_t obj_index, duk_small_int_t stridx, duk_small_uint_t desc_flags)
DUK_INTERNAL void duk_xdef_prop_stridx_builtin (duk_context *ctx, duk_idx_t obj_index, duk_small_int_t stridx, duk_small_int_t builtin_idx, duk_small_uint_t desc_flags)
DUK_INTERNAL void duk_xdef_prop_stridx_thrower (duk_context *ctx, duk_idx_t obj_index, duk_small_int_t stridx, duk_small_uint_t desc_flags)
DUK_EXTERNAL void duk_def_prop (duk_context *ctx, duk_idx_t obj_index, duk_uint_t flags)
DUK_EXTERNAL void duk_compact (duk_context *ctx, duk_idx_t obj_index)
DUK_EXTERNAL void duk_enum (duk_context *ctx, duk_idx_t obj_index, duk_uint_t enum_flags)
DUK_EXTERNAL duk_bool_t duk_next (duk_context *ctx, duk_idx_t enum_index, duk_bool_t get_value)
DUK_EXTERNAL void duk_put_function_list (duk_context *ctx, duk_idx_t obj_index, const duk_function_list_entry *funcs)
DUK_EXTERNAL void duk_put_number_list (duk_context *ctx, duk_idx_t obj_index, const duk_number_list_entry *numbers)
DUK_EXTERNAL duk_bool_t duk_get_global_string (duk_context *ctx, const char *key)
DUK_EXTERNAL duk_bool_t duk_put_global_string (duk_context *ctx, const char *key)
DUK_EXTERNAL void duk_get_prototype (duk_context *ctx, duk_idx_t index)
DUK_EXTERNAL void duk_set_prototype (duk_context *ctx, duk_idx_t index)
DUK_EXTERNAL void duk_get_finalizer (duk_context *ctx, duk_idx_t index)
DUK_EXTERNAL void duk_set_finalizer (duk_context *ctx, duk_idx_t index)
Function Documentation
duk__put_prop_shared()
DUK_LOCAL duk_bool_t duk__put_prop_shared (duk_context * ctx, duk_idx_t obj_idx, duk_idx_t idx_key)
Definition at line 85 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_tval *tv_obj;
    duk_tval *tv_key;
    duk_tval *tv_val;
    duk_small_int_t throw_flag;
    duk_bool_t rc;
    /* Note: copying tv_obj and tv_key to locals to shield against a valstack
     * resize is not necessary for a property put right now (putprop protects
     * against it internally).
     */
    /* Key and value indices are either (-2, -1) or (-1, -2).  Given idx_key,
     * idx_val is always (idx_key ^ 0x01).
     */
    DUK_ASSERT((idx_key == -2 && (idx_key ^ 1) == -1) ||
               (idx_key == -1 && (idx_key ^ 1) == -2));
    tv_obj = duk_require_tval(ctx, obj_idx);
    tv_key = duk_require_tval(ctx, idx_key);
    tv_val = duk_require_tval(ctx, idx_key ^ 1);
    throw_flag = duk_is_strict_call(ctx);
    rc = duk_hobject_putprop(thr, tv_obj, tv_key, tv_val, throw_flag);
    DUK_ASSERT(rc == 0 || rc == 1);
    duk_pop_2(ctx);  /* remove key and value */
    return rc;  /* 1 if property found, 0 otherwise */
}
References DUK_ASSERT, duk_hobject_putprop(), duk_is_strict_call(), duk_pop_2(), and duk_require_tval().
Referenced by duk_put_prop(), duk_put_prop_index(), duk_put_prop_stridx(), and duk_put_prop_string().
duk_compact()
DUK_EXTERNAL void duk_compact (duk_context * ctx, duk_idx_t obj_index)
Definition at line 441 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *obj;
    DUK_ASSERT_CTX_VALID(ctx);
    obj = duk_get_hobject(ctx, obj_index);
    if (obj) {
        /* Note: this may fail, caller should protect the call if necessary */
        duk_hobject_compact_props(thr, obj);
    }
}
References DUK_ASSERT_CTX_VALID, duk_get_hobject(), and duk_hobject_compact_props().
duk_def_prop()
DUK_EXTERNAL void duk_def_prop (duk_context * ctx, duk_idx_t obj_index, duk_uint_t flags)
Definition at line 349 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_idx_t idx_base;
    duk_hobject *obj;
    duk_hstring *key;
    duk_idx_t idx_value;
    duk_hobject *get;
    duk_hobject *set;
    duk_uint_t is_data_desc;
    duk_uint_t is_acc_desc;
    DUK_ASSERT_CTX_VALID(ctx);
    obj = duk_require_hobject(ctx, obj_index);
    is_data_desc = flags & (DUK_DEFPROP_HAVE_VALUE | DUK_DEFPROP_HAVE_WRITABLE);
    is_acc_desc = flags & (DUK_DEFPROP_HAVE_GETTER | DUK_DEFPROP_HAVE_SETTER);
    if (is_data_desc && is_acc_desc) {
        /* "Have" flags must not be conflicting so that they would
         * apply to both a plain property and an accessor at the same
         * time.
         */
        goto fail_invalid_desc;
    }
    idx_base = duk_get_top_index(ctx);
    if (flags & DUK_DEFPROP_HAVE_SETTER) {
        duk_require_type_mask(ctx, idx_base, DUK_TYPE_MASK_UNDEFINED |
                                             DUK_TYPE_MASK_OBJECT |
                                             DUK_TYPE_MASK_LIGHTFUNC);
        set = duk_get_hobject_or_lfunc_coerce(ctx, idx_base);
        if (set != NULL && !DUK_HOBJECT_IS_CALLABLE(set)) {
            goto fail_not_callable;
        }
        idx_base--;
    } else {
        set = NULL;
    }
    if (flags & DUK_DEFPROP_HAVE_GETTER) {
        duk_require_type_mask(ctx, idx_base, DUK_TYPE_MASK_UNDEFINED |
                                             DUK_TYPE_MASK_OBJECT |
                                             DUK_TYPE_MASK_LIGHTFUNC);
        get = duk_get_hobject_or_lfunc_coerce(ctx, idx_base);
        if (get != NULL && !DUK_HOBJECT_IS_CALLABLE(get)) {
            goto fail_not_callable;
        }
        idx_base--;
    } else {
        get = NULL;
    }
    if (flags & DUK_DEFPROP_HAVE_VALUE) {
        idx_value = idx_base;
        idx_base--;
    } else {
        idx_value = (duk_idx_t) -1;
    }
    key = duk_require_hstring(ctx, idx_base);
    duk_require_valid_index(ctx, idx_base);
    duk_hobject_define_property_helper(ctx,
                                       flags /*defprop_flags*/,
                                       obj,
                                       key,
                                       idx_value,
                                       get,
                                       set);
    /* Clean up stack */
    duk_set_top(ctx, idx_base);
    /* [ ... obj ... ] */
    return;
 fail_invalid_desc:
    DUK_ERROR_TYPE(thr, DUK_STR_INVALID_DESCRIPTOR);
    return;
 fail_not_callable:
    DUK_ERROR_TYPE(thr, DUK_STR_NOT_CALLABLE);
    return;
}
References DUK_ASSERT_CTX_VALID, DUK_DEFPROP_HAVE_GETTER, DUK_DEFPROP_HAVE_SETTER, DUK_DEFPROP_HAVE_VALUE, DUK_DEFPROP_HAVE_WRITABLE, DUK_ERROR_TYPE, duk_get_hobject_or_lfunc_coerce(), duk_get_top_index(), duk_hobject_define_property_helper(), DUK_HOBJECT_IS_CALLABLE, duk_require_hobject(), duk_require_hstring(), duk_require_type_mask, duk_require_valid_index(), duk_set_top(), DUK_STR_INVALID_DESCRIPTOR, DUK_STR_NOT_CALLABLE, DUK_TYPE_MASK_LIGHTFUNC, DUK_TYPE_MASK_OBJECT, DUK_TYPE_MASK_UNDEFINED, and NULL.
duk_del_prop()
DUK_EXTERNAL duk_bool_t duk_del_prop (duk_context * ctx, duk_idx_t obj_index)
Definition at line 154 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_tval *tv_obj;
    duk_tval *tv_key;
    duk_small_int_t throw_flag;
    duk_bool_t rc;
    DUK_ASSERT_CTX_VALID(ctx);
    /* Note: copying tv_obj and tv_key to locals to shield against a valstack
     * resize is not necessary for a property delete right now.
     */
    tv_obj = duk_require_tval(ctx, obj_index);
    tv_key = duk_require_tval(ctx, -1);
    throw_flag = duk_is_strict_call(ctx);
    rc = duk_hobject_delprop(thr, tv_obj, tv_key, throw_flag);
    DUK_ASSERT(rc == 0 || rc == 1);
    duk_pop(ctx);  /* remove key */
    return rc;
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_hobject_delprop(), duk_is_strict_call(), duk_pop(), and duk_require_tval().
Referenced by duk_del_prop_index(), duk_del_prop_stridx(), and duk_del_prop_string().
duk_del_prop_index()
DUK_EXTERNAL duk_bool_t duk_del_prop_index (duk_context * ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
Definition at line 187 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    duk_push_uarridx(ctx, arr_index);
    return duk_del_prop(ctx, obj_index);
}
References DUK_ASSERT_CTX_VALID, duk_del_prop(), duk_push_uarridx, and duk_require_normalize_index().
duk_del_prop_stridx()
DUK_INTERNAL duk_bool_t duk_del_prop_stridx (duk_context * ctx, duk_idx_t obj_index, duk_small_int_t stridx)
Definition at line 195 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT_DISABLE(stridx >= 0);
    DUK_ASSERT(stridx < DUK_HEAP_NUM_STRINGS);
    DUK_UNREF(thr);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    duk_push_hstring(ctx, DUK_HTHREAD_GET_STRING(thr, stridx));
    return duk_del_prop(ctx, obj_index);
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_ASSERT_DISABLE, duk_del_prop(), DUK_HEAP_NUM_STRINGS, DUK_HTHREAD_GET_STRING, duk_push_hstring(), duk_require_normalize_index(), and DUK_UNREF.
duk_del_prop_string()
DUK_EXTERNAL duk_bool_t duk_del_prop_string (duk_context * ctx, duk_idx_t obj_index, const char * key)
Definition at line 178 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT(key != NULL);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    duk_push_string(ctx, key);
    return duk_del_prop(ctx, obj_index);
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_del_prop(), duk_push_string(), duk_require_normalize_index(), and NULL.
duk_enum()
DUK_EXTERNAL void duk_enum (duk_context * ctx, duk_idx_t obj_index, duk_uint_t enum_flags)
Definition at line 456 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    duk_dup(ctx, obj_index);
    duk_require_hobject_or_lfunc_coerce(ctx, -1);
    duk_hobject_enumerator_create(ctx, enum_flags);   /* [target] -> [enum] */
}
References DUK_ASSERT_CTX_VALID, duk_dup(), duk_hobject_enumerator_create(), and duk_require_hobject_or_lfunc_coerce().
duk_get_finalizer()
DUK_EXTERNAL void duk_get_finalizer (duk_context * ctx, duk_idx_t index)
Definition at line 600 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    duk_get_prop_stridx(ctx, index, DUK_STRIDX_INT_FINALIZER);
}
References DUK_ASSERT_CTX_VALID, duk_get_prop_stridx(), DUK_STRIDX_INT_FINALIZER, and index.
duk_get_global_string()
DUK_EXTERNAL duk_bool_t duk_get_global_string (duk_context * ctx, const char * key)
Definition at line 510 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_bool_t ret;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT(thr->builtins[DUK_BIDX_GLOBAL] != NULL);
    /* XXX: direct implementation */
    duk_push_hobject(ctx, thr->builtins[DUK_BIDX_GLOBAL]);
    ret = duk_get_prop_string(ctx, -1, key);
    duk_remove(ctx, -2);
    return ret;
}
References duk_hthread::builtins, DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_BIDX_GLOBAL, duk_get_prop_string(), duk_push_hobject(), duk_remove(), and NULL.
duk_get_prop()
DUK_EXTERNAL duk_bool_t duk_get_prop (duk_context * ctx, duk_idx_t obj_index)
Definition at line 15 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_tval *tv_obj;
    duk_tval *tv_key;
    duk_bool_t rc;
    DUK_ASSERT_CTX_VALID(ctx);
    /* Note: copying tv_obj and tv_key to locals to shield against a valstack
     * resize is not necessary for a property get right now.
     */
    tv_obj = duk_require_tval(ctx, obj_index);
    tv_key = duk_require_tval(ctx, -1);
    rc = duk_hobject_getprop(thr, tv_obj, tv_key);
    DUK_ASSERT(rc == 0 || rc == 1);
    /* a value is left on stack regardless of rc */
    duk_remove(ctx, -2);  /* remove key */
    return rc;  /* 1 if property found, 0 otherwise */
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_hobject_getprop(), duk_remove(), and duk_require_tval().
Referenced by duk_get_prop_index(), duk_get_prop_stridx(), and duk_get_prop_string().
duk_get_prop_index()
DUK_EXTERNAL duk_bool_t duk_get_prop_index (duk_context * ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
Definition at line 47 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    duk_push_uarridx(ctx, arr_index);
    return duk_get_prop(ctx, obj_index);
}
References DUK_ASSERT_CTX_VALID, duk_get_prop(), duk_push_uarridx, and duk_require_normalize_index().
duk_get_prop_stridx()
DUK_INTERNAL duk_bool_t duk_get_prop_stridx (duk_context * ctx, duk_idx_t obj_index, duk_small_int_t stridx)
Definition at line 55 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT_DISABLE(stridx >= 0);
    DUK_ASSERT(stridx < DUK_HEAP_NUM_STRINGS);
    DUK_UNREF(thr);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    duk_push_hstring(ctx, DUK_HTHREAD_GET_STRING(thr, stridx));
    return duk_get_prop(ctx, obj_index);
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_ASSERT_DISABLE, duk_get_prop(), DUK_HEAP_NUM_STRINGS, DUK_HTHREAD_GET_STRING, duk_push_hstring(), duk_require_normalize_index(), and DUK_UNREF.
Referenced by duk_get_finalizer(), and duk_get_prop_stridx_boolean().
duk_get_prop_stridx_boolean()
DUK_INTERNAL duk_bool_t duk_get_prop_stridx_boolean (duk_context * ctx, duk_idx_t obj_index, duk_small_int_t stridx, duk_bool_t * out_has_prop)
Definition at line 68 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_bool_t rc;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT_DISABLE(stridx >= 0);
    DUK_ASSERT(stridx < DUK_HEAP_NUM_STRINGS);
    rc = duk_get_prop_stridx(ctx, obj_index, stridx);
    if (out_has_prop) {
        *out_has_prop = rc;
    }
    rc = duk_to_boolean(ctx, -1);
    DUK_ASSERT(rc == 0 || rc == 1);
    duk_pop(ctx);
    return rc;
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_ASSERT_DISABLE, duk_get_prop_stridx(), DUK_HEAP_NUM_STRINGS, duk_pop(), and duk_to_boolean().
duk_get_prop_string()
DUK_EXTERNAL duk_bool_t duk_get_prop_string (duk_context * ctx, duk_idx_t obj_index, const char * key)
Definition at line 38 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT(key != NULL);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    duk_push_string(ctx, key);
    return duk_get_prop(ctx, obj_index);
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_get_prop(), duk_push_string(), duk_require_normalize_index(), and NULL.
Referenced by duk_get_global_string().
duk_get_prototype()
DUK_EXTERNAL void duk_get_prototype (duk_context * ctx, duk_idx_t index)
Definition at line 545 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *obj;
    duk_hobject *proto;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_UNREF(thr);
    obj = duk_require_hobject(ctx, index);
    DUK_ASSERT(obj != NULL);
    /* XXX: shared helper for duk_push_hobject_or_undefined()? */
    proto = DUK_HOBJECT_GET_PROTOTYPE(thr->heap, obj);
    if (proto) {
        duk_push_hobject(ctx, proto);
    } else {
        duk_push_undefined(ctx);
    }
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_HOBJECT_GET_PROTOTYPE, duk_push_hobject(), duk_push_undefined(), duk_require_hobject(), DUK_UNREF, duk_hthread::heap, index, NULL, and proto.
duk_has_prop()
DUK_EXTERNAL duk_bool_t duk_has_prop (duk_context * ctx, duk_idx_t obj_index)
Definition at line 208 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_tval *tv_obj;
    duk_tval *tv_key;
    duk_bool_t rc;
    DUK_ASSERT_CTX_VALID(ctx);
    /* Note: copying tv_obj and tv_key to locals to shield against a valstack
     * resize is not necessary for a property existence check right now.
     */
    tv_obj = duk_require_tval(ctx, obj_index);
    tv_key = duk_require_tval(ctx, -1);
    rc = duk_hobject_hasprop(thr, tv_obj, tv_key);
    DUK_ASSERT(rc == 0 || rc == 1);
    duk_pop(ctx);  /* remove key */
    return rc;  /* 1 if property found, 0 otherwise */
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_hobject_hasprop(), duk_pop(), and duk_require_tval().
Referenced by duk_has_prop_index(), duk_has_prop_stridx(), and duk_has_prop_string().
duk_has_prop_index()
DUK_EXTERNAL duk_bool_t duk_has_prop_index (duk_context * ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
Definition at line 239 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    duk_push_uarridx(ctx, arr_index);
    return duk_has_prop(ctx, obj_index);
}
References DUK_ASSERT_CTX_VALID, duk_has_prop(), duk_push_uarridx, and duk_require_normalize_index().
duk_has_prop_stridx()
DUK_INTERNAL duk_bool_t duk_has_prop_stridx (duk_context * ctx, duk_idx_t obj_index, duk_small_int_t stridx)
Definition at line 247 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT_DISABLE(stridx >= 0);
    DUK_ASSERT(stridx < DUK_HEAP_NUM_STRINGS);
    DUK_UNREF(thr);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    duk_push_hstring(ctx, DUK_HTHREAD_GET_STRING(thr, stridx));
    return duk_has_prop(ctx, obj_index);
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_ASSERT_DISABLE, duk_has_prop(), DUK_HEAP_NUM_STRINGS, DUK_HTHREAD_GET_STRING, duk_push_hstring(), duk_require_normalize_index(), and DUK_UNREF.
duk_has_prop_string()
DUK_EXTERNAL duk_bool_t duk_has_prop_string (duk_context * ctx, duk_idx_t obj_index, const char * key)
Definition at line 230 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT(key != NULL);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    duk_push_string(ctx, key);
    return duk_has_prop(ctx, obj_index);
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_has_prop(), duk_push_string(), duk_require_normalize_index(), and NULL.
duk_next()
DUK_EXTERNAL duk_bool_t duk_next (duk_context * ctx, duk_idx_t enum_index, duk_bool_t get_value)
Definition at line 464 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    duk_require_hobject(ctx, enum_index);
    duk_dup(ctx, enum_index);
    return duk_hobject_enumerator_next(ctx, get_value);
}
References DUK_ASSERT_CTX_VALID, duk_dup(), duk_hobject_enumerator_next(), and duk_require_hobject().
duk_put_function_list()
DUK_EXTERNAL void duk_put_function_list (duk_context * ctx, duk_idx_t obj_index, const duk_function_list_entry * funcs)
Definition at line 476 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    const duk_function_list_entry *ent = funcs;
    DUK_ASSERT_CTX_VALID(ctx);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    if (ent != NULL) {
        while (ent->key != NULL) {
            duk_push_c_function(ctx, ent->value, ent->nargs);
            duk_put_prop_string(ctx, obj_index, ent->key);
            ent++;
        }
    }
}
References DUK_ASSERT_CTX_VALID, duk_push_c_function(), duk_put_prop_string(), duk_require_normalize_index(), funcs, duk_function_list_entry::key, duk_function_list_entry::nargs, NULL, and duk_function_list_entry::value.
duk_put_global_string()
DUK_EXTERNAL duk_bool_t duk_put_global_string (duk_context * ctx, const char * key)
Definition at line 525 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_bool_t ret;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT(thr->builtins[DUK_BIDX_GLOBAL] != NULL);
    /* XXX: direct implementation */
    duk_push_hobject(ctx, thr->builtins[DUK_BIDX_GLOBAL]);
    duk_insert(ctx, -2);
    ret = duk_put_prop_string(ctx, -2, key);  /* [ ... global val ] -> [ ... global ] */
    duk_pop(ctx);
    return ret;
}
References duk_hthread::builtins, DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_BIDX_GLOBAL, duk_insert(), duk_pop(), duk_push_hobject(), duk_put_prop_string(), and NULL.
duk_put_number_list()
DUK_EXTERNAL void duk_put_number_list (duk_context * ctx, duk_idx_t obj_index, const duk_number_list_entry * numbers)
Definition at line 491 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    const duk_number_list_entry *ent = numbers;
    DUK_ASSERT_CTX_VALID(ctx);
    obj_index = duk_require_normalize_index(ctx, obj_index);
    if (ent != NULL) {
        while (ent->key != NULL) {
            duk_push_number(ctx, ent->value);
            duk_put_prop_string(ctx, obj_index, ent->key);
            ent++;
        }
    }
}
References DUK_ASSERT_CTX_VALID, duk_push_number(), duk_put_prop_string(), duk_require_normalize_index(), duk_number_list_entry::key, NULL, and duk_number_list_entry::value.
duk_put_prop()
DUK_EXTERNAL duk_bool_t duk_put_prop (duk_context * ctx, duk_idx_t obj_idx)
Definition at line 115 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    return duk__put_prop_shared(ctx, obj_idx, -2);
}
References duk__put_prop_shared(), and DUK_ASSERT_CTX_VALID.
duk_put_prop_index()
DUK_EXTERNAL duk_bool_t duk_put_prop_index (duk_context * ctx, duk_idx_t obj_idx, duk_uarridx_t arr_idx)
Definition at line 133 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    obj_idx = duk_require_normalize_index(ctx, obj_idx);
    duk_push_uarridx(ctx, arr_idx);
    return duk__put_prop_shared(ctx, obj_idx, -1);
}
References duk__put_prop_shared(), DUK_ASSERT_CTX_VALID, duk_push_uarridx, and duk_require_normalize_index().
duk_put_prop_stridx()
DUK_INTERNAL duk_bool_t duk_put_prop_stridx (duk_context * ctx, duk_idx_t obj_idx, duk_small_int_t stridx)
Definition at line 141 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT_DISABLE(stridx >= 0);
    DUK_ASSERT(stridx < DUK_HEAP_NUM_STRINGS);
    DUK_UNREF(thr);
    obj_idx = duk_require_normalize_index(ctx, obj_idx);
    duk_push_hstring(ctx, DUK_HTHREAD_GET_STRING(thr, stridx));
    return duk__put_prop_shared(ctx, obj_idx, -1);
}
References duk__put_prop_shared(), DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_ASSERT_DISABLE, DUK_HEAP_NUM_STRINGS, DUK_HTHREAD_GET_STRING, duk_push_hstring(), duk_require_normalize_index(), and DUK_UNREF.
Referenced by duk_set_finalizer().
duk_put_prop_string()
DUK_EXTERNAL duk_bool_t duk_put_prop_string (duk_context * ctx, duk_idx_t obj_idx, const char * key)
Definition at line 120 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT(key != NULL);
    /* Careful here and with other duk_put_prop_xxx() helpers: the
     * target object and the property value may be in the same value
     * stack slot (unusual, but still conceptually clear).
     */
    obj_idx = duk_normalize_index(ctx, obj_idx);
    (void) duk_push_string(ctx, key);
    return duk__put_prop_shared(ctx, obj_idx, -1);
}
References duk__put_prop_shared(), DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_normalize_index(), duk_push_string(), and NULL.
Referenced by duk_put_function_list(), duk_put_global_string(), and duk_put_number_list().
duk_set_finalizer()
DUK_EXTERNAL void duk_set_finalizer (duk_context * ctx, duk_idx_t index)
Definition at line 606 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    duk_put_prop_stridx(ctx, index, DUK_STRIDX_INT_FINALIZER);
}
References DUK_ASSERT_CTX_VALID, duk_put_prop_stridx(), DUK_STRIDX_INT_FINALIZER, and index.
duk_set_prototype()
DUK_EXTERNAL void duk_set_prototype (duk_context * ctx, duk_idx_t index)
Definition at line 565 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *obj;
    duk_hobject *proto;
    DUK_ASSERT_CTX_VALID(ctx);
    obj = duk_require_hobject(ctx, index);
    DUK_ASSERT(obj != NULL);
    duk_require_type_mask(ctx, -1, DUK_TYPE_MASK_UNDEFINED |
                                   DUK_TYPE_MASK_OBJECT);
    proto = duk_get_hobject(ctx, -1);
    /* proto can also be NULL here (allowed explicitly) */
#if defined(DUK_USE_ROM_OBJECTS)
    if (DUK_HEAPHDR_HAS_READONLY((duk_heaphdr *) obj)) {
        DUK_ERROR_TYPE(thr, DUK_STR_NOT_CONFIGURABLE);  /* XXX: "read only object"? */
        return;
    }
#endif
    DUK_HOBJECT_SET_PROTOTYPE_UPDREF(thr, obj, proto);
    duk_pop(ctx);
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_ERROR_TYPE, duk_get_hobject(), DUK_HEAPHDR_HAS_READONLY, DUK_HOBJECT_SET_PROTOTYPE_UPDREF, duk_pop(), duk_require_hobject(), duk_require_type_mask, DUK_STR_NOT_CONFIGURABLE, DUK_TYPE_MASK_OBJECT, DUK_TYPE_MASK_UNDEFINED, index, NULL, and proto.
duk_xdef_prop()
DUK_INTERNAL void duk_xdef_prop (duk_context * ctx, duk_idx_t obj_index, duk_small_uint_t desc_flags)
Definition at line 265 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *obj;
    duk_hstring *key;
    DUK_ASSERT_CTX_VALID(ctx);
    obj = duk_require_hobject(ctx, obj_index);
    DUK_ASSERT(obj != NULL);
    key = duk_to_hstring(ctx, -2);
    DUK_ASSERT(key != NULL);
    DUK_ASSERT(duk_require_tval(ctx, -1) != NULL);
    duk_hobject_define_property_internal(thr, obj, key, desc_flags);
    duk_pop(ctx);  /* pop key */
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_hobject_define_property_internal(), duk_pop(), duk_require_hobject(), duk_require_tval(), duk_to_hstring(), and NULL.
duk_xdef_prop_index()
DUK_INTERNAL void duk_xdef_prop_index (duk_context * ctx, duk_idx_t obj_index, duk_uarridx_t arr_index, duk_small_uint_t desc_flags)
Definition at line 283 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *obj;
    DUK_ASSERT_CTX_VALID(ctx);
    obj = duk_require_hobject(ctx, obj_index);
    DUK_ASSERT(obj != NULL);
    duk_hobject_define_property_internal_arridx(thr, obj, arr_index, desc_flags);
    /* value popped by call */
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_hobject_define_property_internal_arridx(), duk_require_hobject(), and NULL.
duk_xdef_prop_stridx()
DUK_INTERNAL void duk_xdef_prop_stridx (duk_context * ctx, duk_idx_t obj_index, duk_small_int_t stridx, duk_small_uint_t desc_flags)
Definition at line 296 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *obj;
    duk_hstring *key;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT_DISABLE(stridx >= 0);
    DUK_ASSERT(stridx < DUK_HEAP_NUM_STRINGS);
    obj = duk_require_hobject(ctx, obj_index);
    DUK_ASSERT(obj != NULL);
    key = DUK_HTHREAD_GET_STRING(thr, stridx);
    DUK_ASSERT(key != NULL);
    DUK_ASSERT(duk_require_tval(ctx, -1) != NULL);
    duk_hobject_define_property_internal(thr, obj, key, desc_flags);
    /* value popped by call */
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_ASSERT_DISABLE, DUK_HEAP_NUM_STRINGS, duk_hobject_define_property_internal(), DUK_HTHREAD_GET_STRING, duk_require_hobject(), duk_require_tval(), and NULL.
duk_xdef_prop_stridx_builtin()
DUK_INTERNAL void duk_xdef_prop_stridx_builtin (duk_context * ctx, duk_idx_t obj_index, duk_small_int_t stridx, duk_small_int_t builtin_idx, duk_small_uint_t desc_flags)
Definition at line 315 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *obj;
    duk_hstring *key;
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ASSERT_DISABLE(stridx >= 0);
    DUK_ASSERT(stridx < DUK_HEAP_NUM_STRINGS);
    DUK_ASSERT_DISABLE(builtin_idx >= 0);
    DUK_ASSERT(builtin_idx < DUK_NUM_BUILTINS);
    obj = duk_require_hobject(ctx, obj_index);
    DUK_ASSERT(obj != NULL);
    key = DUK_HTHREAD_GET_STRING(thr, stridx);
    DUK_ASSERT(key != NULL);
    duk_push_hobject(ctx, thr->builtins[builtin_idx]);
    duk_hobject_define_property_internal(thr, obj, key, desc_flags);
    /* value popped by call */
}
References duk_hthread::builtins, DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_ASSERT_DISABLE, DUK_HEAP_NUM_STRINGS, duk_hobject_define_property_internal(), DUK_HTHREAD_GET_STRING, DUK_NUM_BUILTINS, duk_push_hobject(), duk_require_hobject(), and NULL.
duk_xdef_prop_stridx_thrower()
DUK_INTERNAL void duk_xdef_prop_stridx_thrower (duk_context * ctx, duk_idx_t obj_index, duk_small_int_t stridx, duk_small_uint_t desc_flags)
Definition at line 341 of file duktape-1.8.0/src-separate/duk_api_object.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_hobject *obj = duk_require_hobject(ctx, obj_index);
    duk_hobject *thrower = thr->builtins[DUK_BIDX_TYPE_ERROR_THROWER];
    duk_hobject_define_accessor_internal(thr, obj, DUK_HTHREAD_GET_STRING(thr, stridx), thrower, thrower, desc_flags);
}
References duk_hthread::builtins, DUK_BIDX_TYPE_ERROR_THROWER, duk_hobject_define_accessor_internal(), DUK_HTHREAD_GET_STRING, and duk_require_hobject().