Github User Fetcher: duk_lexer.h File Reference
duk_lexer.h File Reference
Data Structures
struct duk_token
struct duk_re_token
struct duk_lexer_point
struct duk_lexer_codepoint
struct duk_lexer_ctx
Macros
#define DUK_LEXER_INITCTX(ctx) duk_lexer_initctx((ctx))
#define DUK_LEXER_SETPOINT(ctx, pt) duk_lexer_setpoint((ctx), (pt))
#define DUK_LEXER_GETPOINT(ctx, pt)
#define DUK_LEXER_WINDOW_SIZE 6
#define DUK_TOK_MINVAL 0
#define DUK_TOK_EOF 0
#define DUK_TOK_IDENTIFIER 1
#define DUK_TOK_START_RESERVED 2
#define DUK_TOK_BREAK 2
#define DUK_TOK_CASE 3
#define DUK_TOK_CATCH 4
#define DUK_TOK_CONTINUE 5
#define DUK_TOK_DEBUGGER 6
#define DUK_TOK_DEFAULT 7
#define DUK_TOK_DELETE 8
#define DUK_TOK_DO 9
#define DUK_TOK_ELSE 10
#define DUK_TOK_FINALLY 11
#define DUK_TOK_FOR 12
#define DUK_TOK_FUNCTION 13
#define DUK_TOK_IF 14
#define DUK_TOK_IN 15
#define DUK_TOK_INSTANCEOF 16
#define DUK_TOK_NEW 17
#define DUK_TOK_RETURN 18
#define DUK_TOK_SWITCH 19
#define DUK_TOK_THIS 20
#define DUK_TOK_THROW 21
#define DUK_TOK_TRY 22
#define DUK_TOK_TYPEOF 23
#define DUK_TOK_VAR 24
#define DUK_TOK_CONST 25
#define DUK_TOK_VOID 26
#define DUK_TOK_WHILE 27
#define DUK_TOK_WITH 28
#define DUK_TOK_CLASS 29
#define DUK_TOK_ENUM 30
#define DUK_TOK_EXPORT 31
#define DUK_TOK_EXTENDS 32
#define DUK_TOK_IMPORT 33
#define DUK_TOK_SUPER 34
#define DUK_TOK_NULL 35
#define DUK_TOK_TRUE 36
#define DUK_TOK_FALSE 37
#define DUK_TOK_START_STRICT_RESERVED 38 /* inclusive */
#define DUK_TOK_IMPLEMENTS 38
#define DUK_TOK_INTERFACE 39
#define DUK_TOK_LET 40
#define DUK_TOK_PACKAGE 41
#define DUK_TOK_PRIVATE 42
#define DUK_TOK_PROTECTED 43
#define DUK_TOK_PUBLIC 44
#define DUK_TOK_STATIC 45
#define DUK_TOK_YIELD 46
#define DUK_TOK_END_RESERVED 47 /* exclusive */
#define DUK_TOK_GET 47
#define DUK_TOK_SET 48
#define DUK_TOK_LCURLY 49
#define DUK_TOK_RCURLY 50
#define DUK_TOK_LBRACKET 51
#define DUK_TOK_RBRACKET 52
#define DUK_TOK_LPAREN 53
#define DUK_TOK_RPAREN 54
#define DUK_TOK_PERIOD 55
#define DUK_TOK_SEMICOLON 56
#define DUK_TOK_COMMA 57
#define DUK_TOK_LT 58
#define DUK_TOK_GT 59
#define DUK_TOK_LE 60
#define DUK_TOK_GE 61
#define DUK_TOK_EQ 62
#define DUK_TOK_NEQ 63
#define DUK_TOK_SEQ 64
#define DUK_TOK_SNEQ 65
#define DUK_TOK_ADD 66
#define DUK_TOK_SUB 67
#define DUK_TOK_MUL 68
#define DUK_TOK_DIV 69
#define DUK_TOK_MOD 70
#define DUK_TOK_INCREMENT 71
#define DUK_TOK_DECREMENT 72
#define DUK_TOK_ALSHIFT 73 /* named "arithmetic" because result is signed */
#define DUK_TOK_ARSHIFT 74
#define DUK_TOK_RSHIFT 75
#define DUK_TOK_BAND 76
#define DUK_TOK_BOR 77
#define DUK_TOK_BXOR 78
#define DUK_TOK_LNOT 79
#define DUK_TOK_BNOT 80
#define DUK_TOK_LAND 81
#define DUK_TOK_LOR 82
#define DUK_TOK_QUESTION 83
#define DUK_TOK_COLON 84
#define DUK_TOK_EQUALSIGN 85
#define DUK_TOK_ADD_EQ 86
#define DUK_TOK_SUB_EQ 87
#define DUK_TOK_MUL_EQ 88
#define DUK_TOK_DIV_EQ 89
#define DUK_TOK_MOD_EQ 90
#define DUK_TOK_ALSHIFT_EQ 91
#define DUK_TOK_ARSHIFT_EQ 92
#define DUK_TOK_RSHIFT_EQ 93
#define DUK_TOK_BAND_EQ 94
#define DUK_TOK_BOR_EQ 95
#define DUK_TOK_BXOR_EQ 96
#define DUK_TOK_NUMBER 97
#define DUK_TOK_STRING 98
#define DUK_TOK_REGEXP 99
#define DUK_TOK_MAXVAL 99 /* inclusive */
#define DUK_STRIDX_TO_TOK(x) ((x) - DUK_STRIDX_START_RESERVED + DUK_TOK_START_RESERVED)
#define DUK_RETOK_EOF 0
#define DUK_RETOK_DISJUNCTION 1
#define DUK_RETOK_QUANTIFIER 2
#define DUK_RETOK_ASSERT_START 3
#define DUK_RETOK_ASSERT_END 4
#define DUK_RETOK_ASSERT_WORD_BOUNDARY 5
#define DUK_RETOK_ASSERT_NOT_WORD_BOUNDARY 6
#define DUK_RETOK_ASSERT_START_POS_LOOKAHEAD 7
#define DUK_RETOK_ASSERT_START_NEG_LOOKAHEAD 8
#define DUK_RETOK_ATOM_PERIOD 9
#define DUK_RETOK_ATOM_CHAR 10
#define DUK_RETOK_ATOM_DIGIT 11
#define DUK_RETOK_ATOM_NOT_DIGIT 12
#define DUK_RETOK_ATOM_WHITE 13
#define DUK_RETOK_ATOM_NOT_WHITE 14
#define DUK_RETOK_ATOM_WORD_CHAR 15
#define DUK_RETOK_ATOM_NOT_WORD_CHAR 16
#define DUK_RETOK_ATOM_BACKREFERENCE 17
#define DUK_RETOK_ATOM_START_CAPTURE_GROUP 18
#define DUK_RETOK_ATOM_START_NONCAPTURE_GROUP 19
#define DUK_RETOK_ATOM_START_CHARCLASS 20
#define DUK_RETOK_ATOM_START_CHARCLASS_INVERTED 21
#define DUK_RETOK_ATOM_END_GROUP 22
#define DUK_LEXER_TEMP_BUF_LIMIT 256
#define DUK_RE_QUANTIFIER_INFINITE ((duk_uint32_t) 0xffffffffUL)
Typedefs
typedef void(* duk_re_range_callback) (void *user, duk_codepoint_t r1, duk_codepoint_t r2, duk_bool_t direct)
Functions
DUK_INTERNAL_DECL void duk_lexer_initctx (duk_lexer_ctx *lex_ctx)
DUK_INTERNAL_DECL void duk_lexer_setpoint (duk_lexer_ctx *lex_ctx, duk_lexer_point *pt)
DUK_INTERNAL_DECL void duk_lexer_parse_js_input_element (duk_lexer_ctx *lex_ctx, duk_token *out_token, duk_bool_t strict_mode, duk_bool_t regexp_mode)
Macro Definition Documentation
DUK_LEXER_GETPOINT
#define DUK_LEXER_GETPOINT (ctx, pt)
Value:
                                           do { (pt)->offset = (ctx)->window[0].offset; \
                                           (pt)->line = (ctx)->window[0].line; } while (0)
Definition at line 33 of file duktape-1.8.0/src-separate/duk_lexer.h.
#define DUK_LEXER_GETPOINT(ctx,pt)    do { (pt)->offset = (ctx)->window[0].offset; \
                                           (pt)->line = (ctx)->window[0].line; } while (0)
DUK_LEXER_INITCTX
#define DUK_LEXER_INITCTX (ctx) duk_lexer_initctx((ctx))
Definition at line 29 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_LEXER_SETPOINT
#define DUK_LEXER_SETPOINT (ctx, pt) duk_lexer_setpoint((ctx), (pt))
Definition at line 31 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_LEXER_TEMP_BUF_LIMIT
#define DUK_LEXER_TEMP_BUF_LIMIT 256
Definition at line 345 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_LEXER_WINDOW_SIZE
#define DUK_LEXER_WINDOW_SIZE 6
Definition at line 37 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RE_QUANTIFIER_INFINITE
#define DUK_RE_QUANTIFIER_INFINITE ((duk_uint32_t) 0xffffffffUL)
Definition at line 364 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ASSERT_END
#define DUK_RETOK_ASSERT_END 4
Definition at line 324 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ASSERT_NOT_WORD_BOUNDARY
#define DUK_RETOK_ASSERT_NOT_WORD_BOUNDARY 6
Definition at line 326 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ASSERT_START
#define DUK_RETOK_ASSERT_START 3
Definition at line 323 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ASSERT_START_NEG_LOOKAHEAD
#define DUK_RETOK_ASSERT_START_NEG_LOOKAHEAD 8
Definition at line 328 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ASSERT_START_POS_LOOKAHEAD
#define DUK_RETOK_ASSERT_START_POS_LOOKAHEAD 7
Definition at line 327 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ASSERT_WORD_BOUNDARY
#define DUK_RETOK_ASSERT_WORD_BOUNDARY 5
Definition at line 325 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_BACKREFERENCE
#define DUK_RETOK_ATOM_BACKREFERENCE 17
Definition at line 337 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_CHAR
#define DUK_RETOK_ATOM_CHAR 10
Definition at line 330 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_DIGIT
#define DUK_RETOK_ATOM_DIGIT 11
Definition at line 331 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_END_GROUP
#define DUK_RETOK_ATOM_END_GROUP 22
Definition at line 342 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_NOT_DIGIT
#define DUK_RETOK_ATOM_NOT_DIGIT 12
Definition at line 332 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_NOT_WHITE
#define DUK_RETOK_ATOM_NOT_WHITE 14
Definition at line 334 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_NOT_WORD_CHAR
#define DUK_RETOK_ATOM_NOT_WORD_CHAR 16
Definition at line 336 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_PERIOD
#define DUK_RETOK_ATOM_PERIOD 9
Definition at line 329 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_START_CAPTURE_GROUP
#define DUK_RETOK_ATOM_START_CAPTURE_GROUP 18
Definition at line 338 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_START_CHARCLASS
#define DUK_RETOK_ATOM_START_CHARCLASS 20
Definition at line 340 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_START_CHARCLASS_INVERTED
#define DUK_RETOK_ATOM_START_CHARCLASS_INVERTED 21
Definition at line 341 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_START_NONCAPTURE_GROUP
#define DUK_RETOK_ATOM_START_NONCAPTURE_GROUP 19
Definition at line 339 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_WHITE
#define DUK_RETOK_ATOM_WHITE 13
Definition at line 333 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_ATOM_WORD_CHAR
#define DUK_RETOK_ATOM_WORD_CHAR 15
Definition at line 335 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_DISJUNCTION
#define DUK_RETOK_DISJUNCTION 1
Definition at line 321 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_EOF
#define DUK_RETOK_EOF 0
Definition at line 320 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_RETOK_QUANTIFIER
#define DUK_RETOK_QUANTIFIER 2
Definition at line 322 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_STRIDX_TO_TOK
#define DUK_STRIDX_TO_TOK (x) ((x) - DUK_STRIDX_START_RESERVED + DUK_TOK_START_RESERVED)
Definition at line 175 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_ADD
#define DUK_TOK_ADD 66
Definition at line 133 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_ADD_EQ
#define DUK_TOK_ADD_EQ 86
Definition at line 153 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_ALSHIFT
#define DUK_TOK_ALSHIFT 73 /* named "arithmetic" because result is signed */
Definition at line 140 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_ALSHIFT_EQ
#define DUK_TOK_ALSHIFT_EQ 91
Definition at line 158 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_ARSHIFT
#define DUK_TOK_ARSHIFT 74
Definition at line 141 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_ARSHIFT_EQ
#define DUK_TOK_ARSHIFT_EQ 92
Definition at line 159 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_BAND
#define DUK_TOK_BAND 76
Definition at line 143 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_BAND_EQ
#define DUK_TOK_BAND_EQ 94
Definition at line 161 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_BNOT
#define DUK_TOK_BNOT 80
Definition at line 147 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_BOR
#define DUK_TOK_BOR 77
Definition at line 144 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_BOR_EQ
#define DUK_TOK_BOR_EQ 95
Definition at line 162 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_BREAK
#define DUK_TOK_BREAK 2
Definition at line 52 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_BXOR
#define DUK_TOK_BXOR 78
Definition at line 145 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_BXOR_EQ
#define DUK_TOK_BXOR_EQ 96
Definition at line 163 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_CASE
#define DUK_TOK_CASE 3
Definition at line 53 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_CATCH
#define DUK_TOK_CATCH 4
Definition at line 54 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_CLASS
#define DUK_TOK_CLASS 29
Definition at line 81 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_COLON
#define DUK_TOK_COLON 84
Definition at line 151 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_COMMA
#define DUK_TOK_COMMA 57
Definition at line 124 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_CONST
#define DUK_TOK_CONST 25
Definition at line 75 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_CONTINUE
#define DUK_TOK_CONTINUE 5
Definition at line 55 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_DEBUGGER
#define DUK_TOK_DEBUGGER 6
Definition at line 56 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_DECREMENT
#define DUK_TOK_DECREMENT 72
Definition at line 139 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_DEFAULT
#define DUK_TOK_DEFAULT 7
Definition at line 57 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_DELETE
#define DUK_TOK_DELETE 8
Definition at line 58 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_DIV
#define DUK_TOK_DIV 69
Definition at line 136 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_DIV_EQ
#define DUK_TOK_DIV_EQ 89
Definition at line 156 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_DO
#define DUK_TOK_DO 9
Definition at line 59 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_ELSE
#define DUK_TOK_ELSE 10
Definition at line 60 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_END_RESERVED
#define DUK_TOK_END_RESERVED 47 /* exclusive */
Definition at line 107 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_ENUM
#define DUK_TOK_ENUM 30
Definition at line 82 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_EOF
#define DUK_TOK_EOF 0
Definition at line 45 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_EQ
#define DUK_TOK_EQ 62
Definition at line 129 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_EQUALSIGN
#define DUK_TOK_EQUALSIGN 85
Definition at line 152 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_EXPORT
#define DUK_TOK_EXPORT 31
Definition at line 83 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_EXTENDS
#define DUK_TOK_EXTENDS 32
Definition at line 84 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_FALSE
#define DUK_TOK_FALSE 37
Definition at line 93 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_FINALLY
#define DUK_TOK_FINALLY 11
Definition at line 61 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_FOR
#define DUK_TOK_FOR 12
Definition at line 62 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_FUNCTION
#define DUK_TOK_FUNCTION 13
Definition at line 63 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_GE
#define DUK_TOK_GE 61
Definition at line 128 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_GET
#define DUK_TOK_GET 47
Definition at line 112 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_GT
#define DUK_TOK_GT 59
Definition at line 126 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_IDENTIFIER
#define DUK_TOK_IDENTIFIER 1
Definition at line 48 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_IF
#define DUK_TOK_IF 14
Definition at line 64 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_IMPLEMENTS
#define DUK_TOK_IMPLEMENTS 38
Definition at line 97 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_IMPORT
#define DUK_TOK_IMPORT 33
Definition at line 85 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_IN
#define DUK_TOK_IN 15
Definition at line 65 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_INCREMENT
#define DUK_TOK_INCREMENT 71
Definition at line 138 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_INSTANCEOF
#define DUK_TOK_INSTANCEOF 16
Definition at line 66 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_INTERFACE
#define DUK_TOK_INTERFACE 39
Definition at line 98 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_LAND
#define DUK_TOK_LAND 81
Definition at line 148 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_LBRACKET
#define DUK_TOK_LBRACKET 51
Definition at line 118 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_LCURLY
#define DUK_TOK_LCURLY 49
Definition at line 116 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_LE
#define DUK_TOK_LE 60
Definition at line 127 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_LET
#define DUK_TOK_LET 40
Definition at line 99 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_LNOT
#define DUK_TOK_LNOT 79
Definition at line 146 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_LOR
#define DUK_TOK_LOR 82
Definition at line 149 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_LPAREN
#define DUK_TOK_LPAREN 53
Definition at line 120 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_LT
#define DUK_TOK_LT 58
Definition at line 125 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_MAXVAL
#define DUK_TOK_MAXVAL 99 /* inclusive */
Definition at line 172 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_MINVAL
#define DUK_TOK_MINVAL 0
Definition at line 42 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_MOD
#define DUK_TOK_MOD 70
Definition at line 137 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_MOD_EQ
#define DUK_TOK_MOD_EQ 90
Definition at line 157 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_MUL
#define DUK_TOK_MUL 68
Definition at line 135 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_MUL_EQ
#define DUK_TOK_MUL_EQ 88
Definition at line 155 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_NEQ
#define DUK_TOK_NEQ 63
Definition at line 130 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_NEW
#define DUK_TOK_NEW 17
Definition at line 67 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_NULL
#define DUK_TOK_NULL 35
Definition at line 91 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_NUMBER
#define DUK_TOK_NUMBER 97
Definition at line 168 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_PACKAGE
#define DUK_TOK_PACKAGE 41
Definition at line 100 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_PERIOD
#define DUK_TOK_PERIOD 55
Definition at line 122 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_PRIVATE
#define DUK_TOK_PRIVATE 42
Definition at line 101 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_PROTECTED
#define DUK_TOK_PROTECTED 43
Definition at line 102 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_PUBLIC
#define DUK_TOK_PUBLIC 44
Definition at line 103 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_QUESTION
#define DUK_TOK_QUESTION 83
Definition at line 150 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_RBRACKET
#define DUK_TOK_RBRACKET 52
Definition at line 119 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_RCURLY
#define DUK_TOK_RCURLY 50
Definition at line 117 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_REGEXP
#define DUK_TOK_REGEXP 99
Definition at line 170 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_RETURN
#define DUK_TOK_RETURN 18
Definition at line 68 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_RPAREN
#define DUK_TOK_RPAREN 54
Definition at line 121 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_RSHIFT
#define DUK_TOK_RSHIFT 75
Definition at line 142 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_RSHIFT_EQ
#define DUK_TOK_RSHIFT_EQ 93
Definition at line 160 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_SEMICOLON
#define DUK_TOK_SEMICOLON 56
Definition at line 123 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_SEQ
#define DUK_TOK_SEQ 64
Definition at line 131 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_SET
#define DUK_TOK_SET 48
Definition at line 113 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_SNEQ
#define DUK_TOK_SNEQ 65
Definition at line 132 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_START_RESERVED
#define DUK_TOK_START_RESERVED 2
Definition at line 51 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_START_STRICT_RESERVED
#define DUK_TOK_START_STRICT_RESERVED 38 /* inclusive */
Definition at line 96 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_STATIC
#define DUK_TOK_STATIC 45
Definition at line 104 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_STRING
#define DUK_TOK_STRING 98
Definition at line 169 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_SUB
#define DUK_TOK_SUB 67
Definition at line 134 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_SUB_EQ
#define DUK_TOK_SUB_EQ 87
Definition at line 154 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_SUPER
#define DUK_TOK_SUPER 34
Definition at line 86 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_SWITCH
#define DUK_TOK_SWITCH 19
Definition at line 69 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_THIS
#define DUK_TOK_THIS 20
Definition at line 70 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_THROW
#define DUK_TOK_THROW 21
Definition at line 71 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_TRUE
#define DUK_TOK_TRUE 36
Definition at line 92 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_TRY
#define DUK_TOK_TRY 22
Definition at line 72 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_TYPEOF
#define DUK_TOK_TYPEOF 23
Definition at line 73 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_VAR
#define DUK_TOK_VAR 24
Definition at line 74 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_VOID
#define DUK_TOK_VOID 26
Definition at line 76 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_WHILE
#define DUK_TOK_WHILE 27
Definition at line 77 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_WITH
#define DUK_TOK_WITH 28
Definition at line 78 of file duktape-1.8.0/src-separate/duk_lexer.h.
DUK_TOK_YIELD
#define DUK_TOK_YIELD 46
Definition at line 105 of file duktape-1.8.0/src-separate/duk_lexer.h.
Typedef Documentation
duk_re_range_callback
typedef void(* duk_re_range_callback) (void *user, duk_codepoint_t r1, duk_codepoint_t r2, duk_bool_t direct)
Definition at line 8 of file duktape-1.8.0/src-separate/duk_lexer.h.
Function Documentation
duk_lexer_initctx()
DUK_INTERNAL_DECL void duk_lexer_initctx (duk_lexer_ctx * lex_ctx)
Definition at line 73480 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_context *ctx = (duk_context *) lex_ctx->thr;
    DUK_ASSERT(valstack_idx == lex_ctx->slot1_idx || valstack_idx == lex_ctx->slot2_idx);
    DUK_BW_PUSH_AS_STRING(lex_ctx->thr, &lex_ctx->bw);
    duk_replace(ctx, valstack_idx);
}
References duk_lexer_ctx::buf, duk_lexer_ctx::bw, DUK_ASSERT, DUK_BW_PUSH_AS_STRING, DUK_MEMZERO, duk_replace(), duk_lexer_ctx::input, NULL, duk_lexer_ctx::slot1_idx, duk_lexer_ctx::slot2_idx, duk_lexer_ctx::thr, and duk_lexer_ctx::window.
duk_lexer_parse_js_input_element()
DUK_INTERNAL_DECL void duk_lexer_parse_js_input_element (duk_lexer_ctx * lex_ctx, duk_token * out_token, duk_bool_t strict_mode, duk_bool_t regexp_mode)
Definition at line 73618 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_codepoint_t x;           /* temporary, must be signed and 32-bit to hold Unicode code points */
    duk_small_uint_t advtok = 0; /* (advance << 8) + token_type, updated at function end,
                                  * init is unnecessary but suppresses "may be used uninitialized" warnings.
                                  */
    duk_bool_t got_lineterm = 0;  /* got lineterm preceding non-whitespace, non-lineterm token */
    if (++lex_ctx->token_count >= lex_ctx->token_limit) {
        DUK_ERROR_RANGE(lex_ctx->thr, "token limit");
        return;  /* unreachable */
    }
    out_token->t = DUK_TOK_EOF;
    out_token->t_nores = -1;  /* marker: copy t if not changed */
#if 0  /* not necessary to init, disabled for faster parsing */
    out_token->num = DUK_DOUBLE_NAN;
    out_token->str1 = NULL;
    out_token->str2 = NULL;
#endif
    out_token->num_escapes = 0;
    /* out_token->lineterm set by caller */
    /* This would be nice, but parsing is faster without resetting the
     * value slots.  The only side effect is that references to temporary
     * string values may linger until lexing is finished; they're then
     * freed normally.
     */
#if 0
    duk_to_undefined((duk_context *) lex_ctx->thr, lex_ctx->slot1_idx);
    duk_to_undefined((duk_context *) lex_ctx->thr, lex_ctx->slot2_idx);
#endif
    /* 'advtok' indicates how much to advance and which token id to assign
     * at the end.  This shared functionality minimizes code size.  All
     * code paths are required to set 'advtok' to some value, so no default
     * init value is used.  Code paths calling DUK_ERROR() never return so
     * they don't need to set advtok.
     */
    /*
     *  Matching order:
     *
     *    Punctuator first chars, also covers comments, regexps
     *    LineTerminator
     *    Identifier or reserved word, also covers null/true/false literals
     *    NumericLiteral
     *    StringLiteral
     *    EOF
     *
     *  The order does not matter as long as the longest match is
     *  always correctly identified.  There are order dependencies
     *  in the clauses, so it's not trivial to convert to a switch.
     */
 restart_lineupdate:
    out_token->start_line = lex_ctx->window[0].line;
 restart:
    out_token->start_offset = lex_ctx->window[0].offset;
    x = DUK__L0();
    switch (x) {
    case DUK_ASC_SPACE:
    case DUK_ASC_HT:  /* fast paths for space and tab */
        DUK__ADVANCECHARS(lex_ctx, 1);
        goto restart;
    case DUK_ASC_LF:  /* LF line terminator; CR LF and Unicode lineterms are handled in slow path */
        DUK__ADVANCECHARS(lex_ctx, 1);
        got_lineterm = 1;
        goto restart_lineupdate;
    case DUK_ASC_SLASH:  /* '/' */
        if (DUK__L1() == '/') {
            /*
             *  E5 Section 7.4, allow SourceCharacter (which is any 16-bit
             *  code point).
             */
            /* DUK__ADVANCECHARS(lex_ctx, 2) would be correct here, but it unnecessary */
            for (;;) {
                x = DUK__L0();
                if (x < 0 || duk_unicode_is_line_terminator(x)) {
                    break;
                }
                DUK__ADVANCECHARS(lex_ctx, 1);
            }
            goto restart;  /* line terminator will be handled on next round */
        } else if (DUK__L1() == '*') {
            /*
             *  E5 Section 7.4.  If the multi-line comment contains a newline,
             *  it is treated like a single line terminator for automatic
             *  semicolon insertion.
             */
            duk_bool_t last_asterisk = 0;
            DUK__ADVANCECHARS(lex_ctx, 2);
            for (;;) {
                x = DUK__L0();
                if (x < 0) {
                    DUK_ERROR_SYNTAX(lex_ctx->thr, "eof in multiline comment");
                }
                DUK__ADVANCECHARS(lex_ctx, 1);
                if (last_asterisk && x == '/') {
                    break;
                }
                if (duk_unicode_is_line_terminator(x)) {
                    got_lineterm = 1;
                }
                last_asterisk = (x == '*');
            }
            goto restart_lineupdate;
        } else if (regexp_mode) {
#if defined(DUK_USE_REGEXP_SUPPORT)
            /*
             *  "/" followed by something in regexp mode.  See E5 Section 7.8.5.
             *
             *  RegExp parsing is a bit complex.  First, the regexp body is delimited
             *  by forward slashes, but the body may also contain forward slashes as
             *  part of an escape sequence or inside a character class (delimited by
             *  square brackets).  A mini state machine is used to implement these.
             *
             *  Further, an early (parse time) error must be thrown if the regexp
             *  would cause a run-time error when used in the expression new RegExp(...).
             *  Parsing here simply extracts the (candidate) regexp, and also accepts
             *  invalid regular expressions (which are delimited properly).  The caller
             *  (compiler) must perform final validation and regexp compilation.
             *
             *  RegExp first char may not be '/' (single line comment) or '*' (multi-
             *  line comment).  These have already been checked above, so there is no
             *  need below for special handling of the first regexp character as in
             *  the E5 productions.
             *
             *  About unicode escapes within regexp literals:
             *
             *      E5 Section 7.8.5 grammar does NOT accept \uHHHH escapes.
             *      However, Section 6 states that regexps accept the escapes,
             *      see paragraph starting with "In string literals...".
             *      The regexp grammar, which sees the decoded regexp literal
             *      (after lexical parsing) DOES have a \uHHHH unicode escape.
             *      So, for instance:
             *
             *          /\u1234/
             *
             *      should first be parsed by the lexical grammar as:
             *
             *          '\' 'u'      RegularExpressionBackslashSequence
             *          '1'          RegularExpressionNonTerminator
             *          '2'          RegularExpressionNonTerminator
             *          '3'          RegularExpressionNonTerminator
             *          '4'          RegularExpressionNonTerminator
             *
             *      and the escape itself is then parsed by the regexp engine.
             *      This is the current implementation.
             *
             *  Minor spec inconsistency:
             *
             *      E5 Section 7.8.5 RegularExpressionBackslashSequence is:
             *
             *         \ RegularExpressionNonTerminator
             *
             *      while Section A.1 RegularExpressionBackslashSequence is:
             *
             *         \ NonTerminator
             *
             *      The latter is not normative and a typo.
             *
             */
            /* first, parse regexp body roughly */
            duk_small_int_t state = 0;  /* 0=base, 1=esc, 2=class, 3=class+esc */
            DUK__INITBUFFER(lex_ctx);
            for (;;) {
                DUK__ADVANCECHARS(lex_ctx, 1);  /* skip opening slash on first loop */
                x = DUK__L0();
                if (x < 0 || duk_unicode_is_line_terminator(x)) {
                    DUK_ERROR_SYNTAX(lex_ctx->thr, "eof or line terminator in regexp");
                }
                x = DUK__L0();  /* re-read to avoid spill / fetch */
                if (state == 0) {
                    if (x == '/') {
                        DUK__ADVANCECHARS(lex_ctx, 1);  /* eat closing slash */
                        break;
                    } else if (x == '\\') {
                        state = 1;
                    } else if (x == '[') {
                        state = 2;
                    }
                } else if (state == 1) {
                    state = 0;
                } else if (state == 2) {
                    if (x == ']') {
                        state = 0;
                    } else if (x == '\\') {
                        state = 3;
                    }
                } else { /* state == 3 */
                    state = 2;
                }
                DUK__APPENDBUFFER(lex_ctx, x);
            }
            duk__internbuffer(lex_ctx, lex_ctx->slot1_idx);
            out_token->str1 = duk_get_hstring((duk_context *) lex_ctx->thr, lex_ctx->slot1_idx);
            /* second, parse flags */
            DUK__INITBUFFER(lex_ctx);
            for (;;) {
                x = DUK__L0();
                if (!duk_unicode_is_identifier_part(x)) {
                    break;
                }
                x = DUK__L0();  /* re-read to avoid spill / fetch */
                DUK__APPENDBUFFER(lex_ctx, x);
                DUK__ADVANCECHARS(lex_ctx, 1);
            }
            duk__internbuffer(lex_ctx, lex_ctx->slot2_idx);
            out_token->str2 = duk_get_hstring((duk_context *) lex_ctx->thr, lex_ctx->slot2_idx);
            DUK__INITBUFFER(lex_ctx);  /* free some memory */
            /* validation of the regexp is caller's responsibility */
            advtok = DUK__ADVTOK(0, DUK_TOK_REGEXP);
#else
            DUK_ERROR_SYNTAX(lex_ctx->thr, "regexp support disabled");
#endif
        } else if (DUK__L1() == '=') {
            /* "/=" and not in regexp mode */
            advtok = DUK__ADVTOK(2, DUK_TOK_DIV_EQ);
        } else {
            /* "/" and not in regexp mode */
            advtok = DUK__ADVTOK(1, DUK_TOK_DIV);
        }
        break;
    case DUK_ASC_LCURLY:  /* '{' */
        advtok = DUK__ADVTOK(1, DUK_TOK_LCURLY);
        break;
    case DUK_ASC_RCURLY:  /* '}' */
        advtok = DUK__ADVTOK(1, DUK_TOK_RCURLY);
        break;
    case DUK_ASC_LPAREN:  /* '(' */
        advtok = DUK__ADVTOK(1, DUK_TOK_LPAREN);
        break;
    case DUK_ASC_RPAREN:  /* ')' */
        advtok = DUK__ADVTOK(1, DUK_TOK_RPAREN);
        break;
    case DUK_ASC_LBRACKET:  /* '[' */
        advtok = DUK__ADVTOK(1, DUK_TOK_LBRACKET);
        break;
    case DUK_ASC_RBRACKET:  /* ']' */
        advtok = DUK__ADVTOK(1, DUK_TOK_RBRACKET);
        break;
    case DUK_ASC_PERIOD:  /* '.' */
        if (DUK__ISDIGIT(DUK__L1())) {
            /* Period followed by a digit can only start DecimalLiteral
             * (handled in slow path).  We could jump straight into the
             * DecimalLiteral handling but should avoid goto to inside
             * a block.
             */
            goto slow_path;
        }
        advtok = DUK__ADVTOK(1, DUK_TOK_PERIOD);
        break;
    case DUK_ASC_SEMICOLON:  /* ';' */
        advtok = DUK__ADVTOK(1, DUK_TOK_SEMICOLON);
        break;
    case DUK_ASC_COMMA:  /* ',' */
        advtok = DUK__ADVTOK(1, DUK_TOK_COMMA);
        break;
    case DUK_ASC_LANGLE:  /* '<' */
        if (DUK__L1() == '<' && DUK__L2() == '=') {
            advtok = DUK__ADVTOK(3, DUK_TOK_ALSHIFT_EQ);
        } else if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_LE);
        } else if (DUK__L1() == '<') {
            advtok = DUK__ADVTOK(2, DUK_TOK_ALSHIFT);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_LT);
        }
        break;
    case DUK_ASC_RANGLE:  /* '>' */
        if (DUK__L1() == '>' && DUK__L2() == '>' && DUK__L3() == '=') {
            advtok = DUK__ADVTOK(4, DUK_TOK_RSHIFT_EQ);
        } else if (DUK__L1() == '>' && DUK__L2() == '>') {
            advtok = DUK__ADVTOK(3, DUK_TOK_RSHIFT);
        } else if (DUK__L1() == '>' && DUK__L2() == '=') {
            advtok = DUK__ADVTOK(3, DUK_TOK_ARSHIFT_EQ);
        } else if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_GE);
        } else if (DUK__L1() == '>') {
            advtok = DUK__ADVTOK(2, DUK_TOK_ARSHIFT);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_GT);
        }
        break;
    case DUK_ASC_EQUALS:  /* '=' */
        if (DUK__L1() == '=' && DUK__L2() == '=') {
            advtok = DUK__ADVTOK(3, DUK_TOK_SEQ);
        } else if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_EQ);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_EQUALSIGN);
        }
        break;
    case DUK_ASC_EXCLAMATION:  /* '!' */
        if (DUK__L1() == '=' && DUK__L2() == '=') {
            advtok = DUK__ADVTOK(3, DUK_TOK_SNEQ);
        } else if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_NEQ);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_LNOT);
        }
        break;
    case DUK_ASC_PLUS:  /* '+' */
        if (DUK__L1() == '+') {
            advtok = DUK__ADVTOK(2, DUK_TOK_INCREMENT);
        } else if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_ADD_EQ);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_ADD);
        }
        break;
    case DUK_ASC_MINUS:  /* '-' */
        if (DUK__L1() == '-') {
            advtok = DUK__ADVTOK(2, DUK_TOK_DECREMENT);
        } else if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_SUB_EQ);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_SUB);
        }
        break;
    case DUK_ASC_STAR:  /* '*' */
        if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_MUL_EQ);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_MUL);
        }
        break;
    case DUK_ASC_PERCENT:  /* '%' */
        if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_MOD_EQ);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_MOD);
        }
        break;
    case DUK_ASC_AMP:  /* '&' */
        if (DUK__L1() == '&') {
            advtok = DUK__ADVTOK(2, DUK_TOK_LAND);
        } else if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_BAND_EQ);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_BAND);
        }
        break;
    case DUK_ASC_PIPE:  /* '|' */
        if (DUK__L1() == '|') {
            advtok = DUK__ADVTOK(2, DUK_TOK_LOR);
        } else if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_BOR_EQ);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_BOR);
        }
        break;
    case DUK_ASC_CARET:  /* '^' */
        if (DUK__L1() == '=') {
            advtok = DUK__ADVTOK(2, DUK_TOK_BXOR_EQ);
        } else {
            advtok = DUK__ADVTOK(1, DUK_TOK_BXOR);
        }
        break;
    case DUK_ASC_TILDE:  /* '~' */
        advtok = DUK__ADVTOK(1, DUK_TOK_BNOT);
        break;
    case DUK_ASC_QUESTION:  /* '?' */
        advtok = DUK__ADVTOK(1, DUK_TOK_QUESTION);
        break;
    case DUK_ASC_COLON:  /* ':' */
        advtok = DUK__ADVTOK(1, DUK_TOK_COLON);
        break;
    case DUK_ASC_DOUBLEQUOTE:    /* '"' */
    case DUK_ASC_SINGLEQUOTE: {  /* '\'' */
        duk_small_int_t quote = x;  /* Note: duk_uint8_t type yields larger code */
        duk_small_int_t adv;
        DUK__INITBUFFER(lex_ctx);
        for (;;) {
            DUK__ADVANCECHARS(lex_ctx, 1);  /* eat opening quote on first loop */
            x = DUK__L0();
            if (x < 0 || duk_unicode_is_line_terminator(x)) {
                DUK_ERROR_SYNTAX(lex_ctx->thr, "eof or line terminator in string literal");
            }
            if (x == quote) {
                DUK__ADVANCECHARS(lex_ctx, 1);  /* eat closing quote */
                break;
            }
            if (x == '\\') {
                /* DUK__L0        -> '\' char
                 * DUK__L1 ... DUK__L5 -> more lookup
                 */
                x = DUK__L1();
                /* How much to advance before next loop; note that next loop
                 * will advance by 1 anyway, so -1 from the total escape
                 * length (e.g. len('\uXXXX') - 1 = 6 - 1).  As a default,
                 * 1 is good.
                 */
                adv = 2 - 1;  /* note: long live range */
                if (x < 0) {
                    DUK_ERROR_SYNTAX(lex_ctx->thr, "eof or line terminator in string literal");
                }
                if (duk_unicode_is_line_terminator(x)) {
                    /* line continuation */
                    if (x == 0x000d && DUK__L2() == 0x000a) {
                        /* CR LF again a special case */
                        adv = 3 - 1;
                    }
                } else if (x == '\'') {
                    DUK__APPENDBUFFER(lex_ctx, 0x0027);
                } else if (x == '"') {
                    DUK__APPENDBUFFER(lex_ctx, 0x0022);
                } else if (x == '\\') {
                    DUK__APPENDBUFFER(lex_ctx, 0x005c);
                } else if (x == 'b') {
                    DUK__APPENDBUFFER(lex_ctx, 0x0008);
                } else if (x == 'f') {
                    DUK__APPENDBUFFER(lex_ctx, 0x000c);
                } else if (x == 'n') {
                    DUK__APPENDBUFFER(lex_ctx, 0x000a);
                } else if (x == 'r') {
                    DUK__APPENDBUFFER(lex_ctx, 0x000d);
                } else if (x == 't') {
                    DUK__APPENDBUFFER(lex_ctx, 0x0009);
                } else if (x == 'v') {
                    DUK__APPENDBUFFER(lex_ctx, 0x000b);
                } else if (x == 'x') {
                    adv = 4 - 1;
                    DUK__APPENDBUFFER(lex_ctx, duk__decode_hexesc_from_window(lex_ctx, 2));
                } else if (x == 'u') {
                    adv = 6 - 1;
                    DUK__APPENDBUFFER(lex_ctx, duk__decode_uniesc_from_window(lex_ctx, 2));
                } else if (DUK__ISDIGIT(x)) {
                    duk_codepoint_t ch = 0;  /* initialized to avoid warnings of unused var */
                    /*
                     *  Octal escape or zero escape:
                     *    \0                                     (lookahead not DecimalDigit)
                     *    \1 ... \7                              (lookahead not DecimalDigit)
                     *    \ZeroToThree OctalDigit                (lookahead not DecimalDigit)
                     *    \FourToSeven OctalDigit                (no lookahead restrictions)
                     *    \ZeroToThree OctalDigit OctalDigit     (no lookahead restrictions)
                     *
                     *  Zero escape is part of the standard syntax.  Octal escapes are
                     *  defined in E5 Section B.1.2, and are only allowed in non-strict mode.
                     *  Any other productions starting with a decimal digit are invalid.
                     */
                    if (x == '0' && !DUK__ISDIGIT(DUK__L2())) {
                        /* Zero escape (also allowed in non-strict mode) */
                        ch = 0;
                        /* adv = 2 - 1 default OK */
#if defined(DUK_USE_OCTAL_SUPPORT)
                    } else if (strict_mode) {
                        /* No other escape beginning with a digit in strict mode */
                        DUK_ERROR_SYNTAX(lex_ctx->thr, "invalid escape in string literal");
                    } else if (DUK__ISDIGIT03(x) && DUK__ISOCTDIGIT(DUK__L2()) && DUK__ISOCTDIGIT(DUK__L3())) {
                        /* Three digit octal escape, digits validated. */
                        adv = 4 - 1;
                        ch = (duk__hexval(lex_ctx, x) << 6) +
                             (duk__hexval(lex_ctx, DUK__L2()) << 3) +
                             duk__hexval(lex_ctx, DUK__L3());
                    } else if (((DUK__ISDIGIT03(x) && !DUK__ISDIGIT(DUK__L3())) || DUK__ISDIGIT47(x)) &&
                               DUK__ISOCTDIGIT(DUK__L2())) {
                        /* Two digit octal escape, digits validated.
                         *
                         * The if-condition is a bit tricky.  We could catch e.g.
                         * '\039' in the three-digit escape and fail it there (by
                             * validating the digits), but we want to avoid extra
                         * additional validation code.
                         */
                        adv = 3 - 1;
                        ch = (duk__hexval(lex_ctx, x) << 3) +
                             duk__hexval(lex_ctx, DUK__L2());
                    } else if (DUK__ISDIGIT(x) && !DUK__ISDIGIT(DUK__L2())) {
                        /* One digit octal escape, digit validated. */
                        /* adv = 2 default OK */
                        ch = duk__hexval(lex_ctx, x);
#else
                    /* fall through to error */
#endif
                    } else {
                        DUK_ERROR_SYNTAX(lex_ctx->thr, "invalid escape in string literal");
                    }
                    DUK__APPENDBUFFER(lex_ctx, ch);
                } else {
                    /* escaped NonEscapeCharacter */
                    DUK__APPENDBUFFER(lex_ctx, x);
                }
                DUK__ADVANCECHARS(lex_ctx, adv);
                /* Track number of escapes; count not really needed but directive
                 * prologues need to detect whether there were any escapes or line
                 * continuations or not.
                 */
                out_token->num_escapes++;
            } else {
                /* part of string */
                DUK__APPENDBUFFER(lex_ctx, x);
            }
        }
        duk__internbuffer(lex_ctx, lex_ctx->slot1_idx);
        out_token->str1 = duk_get_hstring((duk_context *) lex_ctx->thr, lex_ctx->slot1_idx);
        DUK__INITBUFFER(lex_ctx);  /* free some memory */
        advtok = DUK__ADVTOK(0, DUK_TOK_STRING);
        break;
    }
    default:
        goto slow_path;
    }  /* switch */
    goto skip_slow_path;
 slow_path:
    if (duk_unicode_is_line_terminator(x)) {
        if (x == 0x000d && DUK__L1() == 0x000a) {
            /*
             *  E5 Section 7.3: CR LF is detected as a single line terminator for
             *  line numbers.  Here we also detect it as a single line terminator
             *  token.
             */
            DUK__ADVANCECHARS(lex_ctx, 2);
        } else {
            DUK__ADVANCECHARS(lex_ctx, 1);
        }
        got_lineterm = 1;
        goto restart_lineupdate;
    } else if (duk_unicode_is_identifier_start(x) || x == '\\') {
        /*
         *  Parse an identifier and then check whether it is:
         *    - reserved word (keyword or other reserved word)
         *    - "null"  (NullLiteral)
         *    - "true"  (BooleanLiteral)
         *    - "false" (BooleanLiteral)
         *    - anything else => identifier
         *
         *  This does not follow the E5 productions cleanly, but is
         *  useful and compact.
         *
         *  Note that identifiers may contain Unicode escapes,
         *  see E5 Sections 6 and 7.6.  They must be decoded first,
         *  and the result checked against allowed characters.
         *  The above if-clause accepts an identifier start and an
         *  '\' character -- no other token can begin with a '\'.
         *
         *  Note that "get" and "set" are not reserved words in E5
         *  specification so they are recognized as plain identifiers
         *  (the tokens DUK_TOK_GET and DUK_TOK_SET are actually not
         *  used now).  The compiler needs to work around this.
         *
         *  Strictly speaking, following Ecmascript longest match
         *  specification, an invalid escape for the first character
         *  should cause a syntax error.  However, an invalid escape
         *  for IdentifierParts should just terminate the identifier
         *  early (longest match), and let the next tokenization
         *  fail.  For instance Rhino croaks with 'foo\z' when
         *  parsing the identifier.  This has little practical impact.
         */
        duk_small_int_t i, i_end;
        duk_bool_t first = 1;
        duk_hstring *str;
        DUK__INITBUFFER(lex_ctx);
        for (;;) {
            /* re-lookup first char on first loop */
            if (DUK__L0() == '\\') {
                duk_codepoint_t ch;
                if (DUK__L1() != 'u') {
                    DUK_ERROR_SYNTAX(lex_ctx->thr, "invalid unicode escape in identifier");
                }
                ch = duk__decode_uniesc_from_window(lex_ctx, 2);
                /* IdentifierStart is stricter than IdentifierPart, so if the first
                 * character is escaped, must have a stricter check here.
                 */
                if (!(first ? duk_unicode_is_identifier_start(ch) : duk_unicode_is_identifier_part(ch))) {
                    DUK_ERROR_SYNTAX(lex_ctx->thr, "invalid unicode escape in identifier");
                }
                DUK__APPENDBUFFER(lex_ctx, ch);
                DUK__ADVANCECHARS(lex_ctx, 6);
                /* Track number of escapes: necessary for proper keyword
                 * detection.
                 */
                out_token->num_escapes++;
            } else {
                /* Note: first character is checked against this.  But because
                 * IdentifierPart includes all IdentifierStart characters, and
                 * the first character (if unescaped) has already been checked
                 * in the if condition, this is OK.
                 */
                if (!duk_unicode_is_identifier_part(DUK__L0())) {
                    break;
                }
                DUK__APPENDBUFFER(lex_ctx, DUK__L0());
                DUK__ADVANCECHARS(lex_ctx, 1);
            }
            first = 0;
        }
        duk__internbuffer(lex_ctx, lex_ctx->slot1_idx);
        out_token->str1 = duk_get_hstring((duk_context *) lex_ctx->thr, lex_ctx->slot1_idx);
        str = out_token->str1;
        DUK_ASSERT(str != NULL);
        out_token->t_nores = DUK_TOK_IDENTIFIER;
        DUK__INITBUFFER(lex_ctx);  /* free some memory */
        /*
         *  Interned identifier is compared against reserved words, which are
         *  currently interned into the heap context.  See genbuiltins.py.
         *
         *  Note that an escape in the identifier disables recognition of
         *  keywords; e.g. "\u0069f = 1;" is a valid statement (assigns to
         *  identifier named "if").  This is not necessarily compliant,
         *  see test-dec-escaped-char-in-keyword.js.
         *
         *  Note: "get" and "set" are awkward.  They are not officially
         *  ReservedWords (and indeed e.g. "var set = 1;" is valid), and
         *  must come out as DUK_TOK_IDENTIFIER.  The compiler needs to
         *  work around this a bit.
         */
        /* XXX: optimize by adding the token numbers directly into the
         * always interned duk_hstring objects (there should be enough
         * flag bits free for that)?
         */
        i_end = (strict_mode ? DUK_STRIDX_END_RESERVED : DUK_STRIDX_START_STRICT_RESERVED);
        advtok = DUK__ADVTOK(0, DUK_TOK_IDENTIFIER);
        if (out_token->num_escapes == 0) {
            for (i = DUK_STRIDX_START_RESERVED; i < i_end; i++) {
                DUK_ASSERT(i >= 0 && i < DUK_HEAP_NUM_STRINGS);
                if (DUK_HTHREAD_GET_STRING(lex_ctx->thr, i) == str) {
                    advtok = DUK__ADVTOK(0, DUK_STRIDX_TO_TOK(i));
                    break;
                }
            }
        }
    } else if (DUK__ISDIGIT(x) || (x == '.')) {
        /* Note: decimal number may start with a period, but must be followed by a digit */
        /*
         *  DecimalLiteral, HexIntegerLiteral, OctalIntegerLiteral
         *  "pre-parsing", followed by an actual, accurate parser step.
         *
         *  Note: the leading sign character ('+' or '-') is -not- part of
         *  the production in E5 grammar, and that the a DecimalLiteral
         *  starting with a '0' must be followed by a non-digit.  Leading
         *  zeroes are syntax errors and must be checked for.
         *
         *  XXX: the two step parsing process is quite awkward, it would
         *  be more straightforward to allow numconv to parse the longest
         *  valid prefix (it already does that, it only needs to indicate
         *  where the input ended).  However, the lexer decodes characters
         *  using a lookup window, so this is not a trivial change.
         */
        /* XXX: because of the final check below (that the literal is not
         * followed by a digit), this could maybe be simplified, if we bail
         * out early from a leading zero (and if there are no periods etc).
         * Maybe too complex.
         */
        duk_double_t val;
        duk_bool_t int_only = 0;
        duk_bool_t allow_hex = 0;
        duk_small_int_t state;  /* 0=before period/exp,
                                 * 1=after period, before exp
                                 * 2=after exp, allow '+' or '-'
                                 * 3=after exp and exp sign
                                 */
        duk_small_uint_t s2n_flags;
        duk_codepoint_t y;
        DUK__INITBUFFER(lex_ctx);
        y = DUK__L1();
        if (x == '0' && (y == 'x' || y == 'X')) {
            DUK__APPENDBUFFER(lex_ctx, x);
            DUK__APPENDBUFFER(lex_ctx, y);
            DUK__ADVANCECHARS(lex_ctx, 2);
            int_only = 1;
            allow_hex = 1;
#if defined(DUK_USE_OCTAL_SUPPORT)
        } else if (!strict_mode && x == '0' && DUK__ISDIGIT(y)) {
            /* Note: if DecimalLiteral starts with a '0', it can only be
             * followed by a period or an exponent indicator which starts
             * with 'e' or 'E'.  Hence the if-check above ensures that
             * OctalIntegerLiteral is the only valid NumericLiteral
             * alternative at this point (even if y is, say, '9').
             */
            DUK__APPENDBUFFER(lex_ctx, x);
            DUK__ADVANCECHARS(lex_ctx, 1);
            int_only = 1;
#endif
        }
        state = 0;
        for (;;) {
            x = DUK__L0();  /* re-lookup curr char on first round */
            if (DUK__ISDIGIT(x)) {
                /* Note: intentionally allow leading zeroes here, as the
                 * actual parser will check for them.
                 */
                if (state == 2) {
                    state = 3;
                }
            } else if (allow_hex && DUK__ISHEXDIGIT(x)) {
                /* Note: 'e' and 'E' are also accepted here. */
                ;
            } else if (x == '.') {
                if (state >= 1 || int_only) {
                    break;
                } else {
                    state = 1;
                }
            } else if (x == 'e' || x == 'E') {
                if (state >= 2 || int_only) {
                    break;
                } else {
                    state = 2;
                }
            } else if (x == '-' || x == '+') {
                if (state != 2) {
                    break;
                } else {
                    state = 3;
                }
            } else {
                break;
            }
            DUK__APPENDBUFFER(lex_ctx, x);
            DUK__ADVANCECHARS(lex_ctx, 1);
        }
        /* XXX: better coercion */
        duk__internbuffer(lex_ctx, lex_ctx->slot1_idx);
        s2n_flags = DUK_S2N_FLAG_ALLOW_EXP |
                    DUK_S2N_FLAG_ALLOW_FRAC |
                    DUK_S2N_FLAG_ALLOW_NAKED_FRAC |
                    DUK_S2N_FLAG_ALLOW_EMPTY_FRAC |
#if defined(DUK_USE_OCTAL_SUPPORT)
                    (strict_mode ? 0 : DUK_S2N_FLAG_ALLOW_AUTO_OCT_INT) |
#endif
                    DUK_S2N_FLAG_ALLOW_AUTO_HEX_INT;
        duk_dup((duk_context *) lex_ctx->thr, lex_ctx->slot1_idx);
        duk_numconv_parse((duk_context *) lex_ctx->thr, 10 /*radix*/, s2n_flags);
        val = duk_to_number((duk_context *) lex_ctx->thr, -1);
        if (DUK_ISNAN(val)) {
            DUK_ERROR_SYNTAX(lex_ctx->thr, "invalid numeric literal");
        }
        duk_replace((duk_context *) lex_ctx->thr, lex_ctx->slot1_idx);  /* could also just pop? */
        DUK__INITBUFFER(lex_ctx);  /* free some memory */
        /* Section 7.8.3 (note): NumericLiteral must be followed by something other than
         * IdentifierStart or DecimalDigit.
         */
        if (DUK__ISDIGIT(DUK__L0()) || duk_unicode_is_identifier_start(DUK__L0())) {
            DUK_ERROR_SYNTAX(lex_ctx->thr, "invalid numeric literal");
        }
        out_token->num = val;
        advtok = DUK__ADVTOK(0, DUK_TOK_NUMBER);
    } else if (duk_unicode_is_whitespace(DUK__LOOKUP(lex_ctx, 0))) {
        DUK__ADVANCECHARS(lex_ctx, 1);
        goto restart;
    } else if (x < 0) {
        advtok = DUK__ADVTOK(0, DUK_TOK_EOF);
    } else {
        DUK_ERROR_SYNTAX(lex_ctx->thr, "invalid token");
    }
 skip_slow_path:
    /*
     *  Shared exit path
     */
References duk_token::allow_auto_semi, DUK__ADVANCEBYTES, DUK__ADVANCECHARS, DUK__ADVTOK, DUK__APPENDBUFFER, duk__decode_hexesc_from_window(), duk__decode_uniesc_from_window(), duk__hexval(), DUK__INITBUFFER, duk__internbuffer(), DUK__ISDIGIT, DUK__ISDIGIT03, DUK__ISDIGIT47, DUK__ISHEXDIGIT, DUK__ISOCTDIGIT, DUK__L0, DUK__L1, DUK__L2, DUK__L3, DUK__LOOKUP, DUK_ASC_AMP, DUK_ASC_CARET, DUK_ASC_COLON, DUK_ASC_COMMA, DUK_ASC_DOUBLEQUOTE, DUK_ASC_EQUALS, DUK_ASC_EXCLAMATION, DUK_ASC_HT, DUK_ASC_LANGLE, DUK_ASC_LBRACKET, DUK_ASC_LCURLY, DUK_ASC_LF, DUK_ASC_LPAREN, DUK_ASC_MINUS, DUK_ASC_PERCENT, DUK_ASC_PERIOD, DUK_ASC_PIPE, DUK_ASC_PLUS, DUK_ASC_QUESTION, DUK_ASC_RANGLE, DUK_ASC_RBRACKET, DUK_ASC_RCURLY, DUK_ASC_RPAREN, DUK_ASC_SEMICOLON, DUK_ASC_SINGLEQUOTE, DUK_ASC_SLASH, DUK_ASC_SPACE, DUK_ASC_STAR, DUK_ASC_TILDE, DUK_ASSERT, DUK_DOUBLE_NAN, duk_dup(), DUK_ERROR_RANGE, DUK_ERROR_SYNTAX, duk_get_hstring(), DUK_HEAP_NUM_STRINGS, DUK_HTHREAD_GET_STRING, DUK_ISNAN, duk_numconv_parse(), duk_replace(), DUK_S2N_FLAG_ALLOW_AUTO_HEX_INT, DUK_S2N_FLAG_ALLOW_AUTO_OCT_INT, DUK_S2N_FLAG_ALLOW_EMPTY_FRAC, DUK_S2N_FLAG_ALLOW_EXP, DUK_S2N_FLAG_ALLOW_FRAC, DUK_S2N_FLAG_ALLOW_NAKED_FRAC, DUK_STRIDX_END_RESERVED, DUK_STRIDX_START_RESERVED, DUK_STRIDX_START_STRICT_RESERVED, DUK_STRIDX_TO_TOK, duk_to_number(), duk_to_undefined(), DUK_TOK_ADD, DUK_TOK_ADD_EQ, DUK_TOK_ALSHIFT, DUK_TOK_ALSHIFT_EQ, DUK_TOK_ARSHIFT, DUK_TOK_ARSHIFT_EQ, DUK_TOK_BAND, DUK_TOK_BAND_EQ, DUK_TOK_BNOT, DUK_TOK_BOR, DUK_TOK_BOR_EQ, DUK_TOK_BXOR, DUK_TOK_BXOR_EQ, DUK_TOK_COLON, DUK_TOK_COMMA, DUK_TOK_DECREMENT, DUK_TOK_DIV, DUK_TOK_DIV_EQ, DUK_TOK_EOF, DUK_TOK_EQ, DUK_TOK_EQUALSIGN, DUK_TOK_GE, DUK_TOK_GT, DUK_TOK_IDENTIFIER, DUK_TOK_INCREMENT, DUK_TOK_LAND, DUK_TOK_LBRACKET, DUK_TOK_LCURLY, DUK_TOK_LE, DUK_TOK_LNOT, DUK_TOK_LOR, DUK_TOK_LPAREN, DUK_TOK_LT, DUK_TOK_MOD, DUK_TOK_MOD_EQ, DUK_TOK_MUL, DUK_TOK_MUL_EQ, DUK_TOK_NEQ, DUK_TOK_NUMBER, DUK_TOK_PERIOD, DUK_TOK_QUESTION, DUK_TOK_RBRACKET, DUK_TOK_RCURLY, DUK_TOK_REGEXP, DUK_TOK_RPAREN, DUK_TOK_RSHIFT, DUK_TOK_RSHIFT_EQ, DUK_TOK_SEMICOLON, DUK_TOK_SEQ, DUK_TOK_SNEQ, DUK_TOK_STRING, DUK_TOK_SUB, DUK_TOK_SUB_EQ, duk_unicode_is_identifier_part(), duk_unicode_is_identifier_start(), duk_unicode_is_line_terminator(), duk_unicode_is_whitespace(), duk_lexer_codepoint::line, duk_token::lineterm, NULL, duk_token::num, duk_token::num_escapes, duk_lexer_codepoint::offset, duk_lexer_ctx::slot1_idx, duk_lexer_ctx::slot2_idx, duk_token::start_line, duk_token::start_offset, duk_token::str1, duk_token::str2, duk_token::t, duk_token::t_nores, duk_lexer_ctx::thr, duk_lexer_ctx::token_count, duk_lexer_ctx::token_limit, and duk_lexer_ctx::window.
Referenced by duk__advance_helper().
duk_lexer_setpoint()
DUK_INTERNAL_DECL void duk_lexer_setpoint (duk_lexer_ctx * lex_ctx, duk_lexer_point * pt)
Definition at line 73500 of file duktape-1.5.2/src-noline/duktape.c.
References duk__init_lexer_window(), DUK_ASSERT, DUK_ASSERT_DISABLE, duk_lexer_ctx::input_line, duk_lexer_ctx::input_offset, duk_lexer_point::line, and duk_lexer_point::offset.