Github User Fetcher: duk_api_debug.c File Reference
duk_api_debug.c File Reference
#include "duk_internal.h"
Functions
DUK_EXTERNAL void duk_push_context_dump (duk_context *ctx)
DUK_EXTERNAL void duk_debugger_attach_custom (duk_context *ctx, duk_debug_read_function read_cb, duk_debug_write_function write_cb, duk_debug_peek_function peek_cb, duk_debug_read_flush_function read_flush_cb, duk_debug_write_flush_function write_flush_cb, duk_debug_request_function request_cb, duk_debug_detached_function detached_cb, void *udata)
DUK_EXTERNAL void duk_debugger_detach (duk_context *ctx)
DUK_EXTERNAL void duk_debugger_cooperate (duk_context *ctx)
DUK_EXTERNAL duk_bool_t duk_debugger_notify (duk_context *ctx, duk_idx_t nvalues)
DUK_EXTERNAL void duk_debugger_pause (duk_context *ctx)
Function Documentation
duk_debugger_attach_custom()
DUK_EXTERNAL void duk_debugger_attach_custom (duk_context * ctx, duk_debug_read_function read_cb, duk_debug_write_function write_cb, duk_debug_peek_function peek_cb, duk_debug_read_flush_function read_flush_cb, duk_debug_write_flush_function write_flush_cb, duk_debug_request_function request_cb, duk_debug_detached_function detached_cb, void * udata)
Definition at line 209 of file duktape-1.8.0/src-separate/duk_api_debug.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_UNREF(read_cb);
    DUK_UNREF(write_cb);
    DUK_UNREF(peek_cb);
    DUK_UNREF(read_flush_cb);
    DUK_UNREF(write_flush_cb);
    DUK_UNREF(request_cb);
    DUK_UNREF(detached_cb);
    DUK_UNREF(udata);
    DUK_ERROR_API((duk_hthread *) ctx, "no debugger support");
}
References DUK_ASSERT_CTX_VALID, DUK_ERROR_API, and DUK_UNREF.
duk_debugger_cooperate()
DUK_EXTERNAL void duk_debugger_cooperate (duk_context * ctx)
Definition at line 235 of file duktape-1.8.0/src-separate/duk_api_debug.c.
{
    /* nop */
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_UNREF(ctx);
}
References DUK_ASSERT_CTX_VALID, and DUK_UNREF.
duk_debugger_detach()
DUK_EXTERNAL void duk_debugger_detach (duk_context * ctx)
Definition at line 230 of file duktape-1.8.0/src-separate/duk_api_debug.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ERROR_API((duk_hthread *) ctx, "no debugger support");
}
References DUK_ASSERT_CTX_VALID, and DUK_ERROR_API.
duk_debugger_notify()
DUK_EXTERNAL duk_bool_t duk_debugger_notify (duk_context * ctx, duk_idx_t nvalues)
Definition at line 241 of file duktape-1.8.0/src-separate/duk_api_debug.c.
{
    duk_idx_t top;
    DUK_ASSERT_CTX_VALID(ctx);
    top = duk_get_top(ctx);
    if (top < nvalues) {
        DUK_ERROR_API((duk_hthread *) ctx, "not enough stack values for notify");
        return 0;  /* unreachable */
    }
    /* No debugger support, just pop values. */
    duk_pop_n(ctx, nvalues);
    return 0;
}
References DUK_ASSERT_CTX_VALID, DUK_ERROR_API, duk_get_top(), and duk_pop_n().
duk_debugger_pause()
DUK_EXTERNAL void duk_debugger_pause (duk_context * ctx)
Definition at line 257 of file duktape-1.8.0/src-separate/duk_api_debug.c.
{
    /* Treat like debugger statement: nop */
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_UNREF(ctx);
}
References DUK_ASSERT_CTX_VALID, and DUK_UNREF.
duk_push_context_dump()
DUK_EXTERNAL void duk_push_context_dump (duk_context * ctx)
Definition at line 7 of file duktape-1.8.0/src-separate/duk_api_debug.c.
{
    duk_idx_t idx;
    duk_idx_t top;
    DUK_ASSERT_CTX_VALID(ctx);
    /* We don't duk_require_stack() here now, but rely on the caller having
     * enough space.
     */
    top = duk_get_top(ctx);
    duk_push_array(ctx);
    for (idx = 0; idx < top; idx++) {
        duk_dup(ctx, idx);
        duk_put_prop_index(ctx, -2, idx);
    }
    /* XXX: conversion errors should not propagate outwards.
     * Perhaps values need to be coerced individually?
     */
    duk_bi_json_stringify_helper(ctx,
                                 duk_get_top_index(ctx),  /*idx_value*/
                                 DUK_INVALID_INDEX,  /*idx_replacer*/
                                 DUK_INVALID_INDEX,  /*idx_space*/
                                 DUK_JSON_FLAG_EXT_CUSTOM |
                                 DUK_JSON_FLAG_ASCII_ONLY |
                                 DUK_JSON_FLAG_AVOID_KEY_QUOTES /*flags*/);
    duk_push_sprintf(ctx, "ctx: top=%ld, stack=%s", (long) top, (const char *) duk_safe_to_string(ctx, -1));
    duk_replace(ctx, -3);  /* [ ... arr jsonx(arr) res ] -> [ ... res jsonx(arr) ] */
    duk_pop(ctx);
    DUK_ASSERT(duk_is_string(ctx, -1));
}
References DUK_ASSERT, DUK_ASSERT_CTX_VALID, duk_bi_json_stringify_helper(), duk_dup(), duk_get_top(), duk_get_top_index(), DUK_INVALID_INDEX, duk_is_string(), DUK_JSON_FLAG_ASCII_ONLY, DUK_JSON_FLAG_AVOID_KEY_QUOTES, DUK_JSON_FLAG_EXT_CUSTOM, duk_pop(), duk_push_array(), duk_push_sprintf(), duk_put_prop_index(), duk_replace(), and duk_safe_to_string.