Github User Fetcher: gtkwindow.h File Reference
gtkwindow.h File Reference
#include <gtk/gtkapplication.h>
#include <gtk/gtkaccelgroup.h>
#include <gtk/gtkwidget.h>
Data Structures
struct _GtkWindow
struct _GtkWindowClass
Macros
#define GTK_TYPE_WINDOW (gtk_window_get_type ())
#define GTK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_WINDOW, GtkWindow))
#define GTK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_TYPE_WINDOW, GtkWindowClass))
#define GTK_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTK_TYPE_WINDOW))
#define GTK_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTK_TYPE_WINDOW))
#define GTK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTK_TYPE_WINDOW, GtkWindowClass))
Typedefs
typedef struct _GtkWindowClass GtkWindowClass
typedef struct _GtkWindowGroup GtkWindowGroup
typedef struct _GtkWindowGroupClass GtkWindowGroupClass
typedef struct _GtkWindowGroupPrivate GtkWindowGroupPrivate
Functions
GDK_AVAILABLE_IN_ALL GType gtk_window_get_type (void) G_GNUC_CONST
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_new (void)
GDK_AVAILABLE_IN_ALL void gtk_window_set_title (GtkWindow *window, const char *title)
GDK_AVAILABLE_IN_ALL const char * gtk_window_get_title (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_startup_id (GtkWindow *window, const char *startup_id)
GDK_AVAILABLE_IN_ALL void gtk_window_set_focus (GtkWindow *window, GtkWidget *focus)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_get_focus (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_default_widget (GtkWindow *window, GtkWidget *default_widget)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_get_default_widget (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_transient_for (GtkWindow *window, GtkWindow *parent)
GDK_AVAILABLE_IN_ALL GtkWindow * gtk_window_get_transient_for (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_destroy_with_parent (GtkWindow *window, gboolean setting)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_destroy_with_parent (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_hide_on_close (GtkWindow *window, gboolean setting)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_hide_on_close (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_mnemonics_visible (GtkWindow *window, gboolean setting)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_mnemonics_visible (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_focus_visible (GtkWindow *window, gboolean setting)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_focus_visible (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_resizable (GtkWindow *window, gboolean resizable)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_resizable (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_display (GtkWindow *window, GdkDisplay *display)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_is_active (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_decorated (GtkWindow *window, gboolean setting)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_decorated (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_deletable (GtkWindow *window, gboolean setting)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_deletable (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_icon_name (GtkWindow *window, const char *name)
GDK_AVAILABLE_IN_ALL const char * gtk_window_get_icon_name (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_default_icon_name (const char *name)
GDK_AVAILABLE_IN_ALL const char * gtk_window_get_default_icon_name (void)
GDK_AVAILABLE_IN_ALL void gtk_window_set_auto_startup_notification (gboolean setting)
GDK_AVAILABLE_IN_ALL void gtk_window_set_modal (GtkWindow *window, gboolean modal)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_modal (GtkWindow *window)
GDK_AVAILABLE_IN_ALL GListModel * gtk_window_get_toplevels (void)
GDK_AVAILABLE_IN_ALL GList * gtk_window_list_toplevels (void)
GDK_AVAILABLE_IN_ALL void gtk_window_present (GtkWindow *window)
void gtk_window_present_with_time (GtkWindow *window, guint32 timestamp)
GDK_AVAILABLE_IN_ALL void gtk_window_minimize (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_unminimize (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_maximize (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_unmaximize (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_fullscreen (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_unfullscreen (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_fullscreen_on_monitor (GtkWindow *window, GdkMonitor *monitor)
GDK_AVAILABLE_IN_ALL void gtk_window_close (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_default_size (GtkWindow *window, int width, int height)
GDK_AVAILABLE_IN_ALL void gtk_window_get_default_size (GtkWindow *window, int *width, int *height)
GDK_AVAILABLE_IN_ALL GtkWindowGroup * gtk_window_get_group (GtkWindow *window)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_has_group (GtkWindow *window)
GDK_AVAILABLE_IN_ALL GtkApplication * gtk_window_get_application (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_application (GtkWindow *window, GtkApplication *application)
GDK_AVAILABLE_IN_ALL void gtk_window_set_child (GtkWindow *window, GtkWidget *child)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_get_child (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_titlebar (GtkWindow *window, GtkWidget *titlebar)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_get_titlebar (GtkWindow *window)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_is_maximized (GtkWindow *window)
GDK_AVAILABLE_IN_ALL gboolean gtk_window_is_fullscreen (GtkWindow *window)
GDK_AVAILABLE_IN_4_12 gboolean gtk_window_is_suspended (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_destroy (GtkWindow *window)
GDK_AVAILABLE_IN_ALL void gtk_window_set_interactive_debugging (gboolean enable)
GDK_AVAILABLE_IN_4_2 void gtk_window_set_handle_menubar_accel (GtkWindow *window, gboolean handle_menubar_accel)
GDK_AVAILABLE_IN_4_2 gboolean gtk_window_get_handle_menubar_accel (GtkWindow *window)
Macro Definition Documentation
GTK_IS_WINDOW
#define GTK_IS_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTK_TYPE_WINDOW))
Definition at line 41 of file gtkwindow.h.
GTK_IS_WINDOW_CLASS
#define GTK_IS_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTK_TYPE_WINDOW))
Definition at line 42 of file gtkwindow.h.
GTK_TYPE_WINDOW
#define GTK_TYPE_WINDOW (gtk_window_get_type ())
Definition at line 38 of file gtkwindow.h.
GTK_WINDOW
#define GTK_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_WINDOW, GtkWindow))
Definition at line 39 of file gtkwindow.h.
Referenced by activate().
GTK_WINDOW_CLASS
#define GTK_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_TYPE_WINDOW, GtkWindowClass))
Definition at line 40 of file gtkwindow.h.
GTK_WINDOW_GET_CLASS
#define GTK_WINDOW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTK_TYPE_WINDOW, GtkWindowClass))
Definition at line 43 of file gtkwindow.h.
Typedef Documentation
GtkWindowClass
typedef struct _GtkWindowClass GtkWindowClass
Definition at line 45 of file gtkwindow.h.
GtkWindowGroup
typedef struct _GtkWindowGroup GtkWindowGroup
Definition at line 46 of file gtkwindow.h.
GtkWindowGroupClass
typedef struct _GtkWindowGroupClass GtkWindowGroupClass
Definition at line 47 of file gtkwindow.h.
GtkWindowGroupPrivate
typedef struct _GtkWindowGroupPrivate GtkWindowGroupPrivate
Definition at line 48 of file gtkwindow.h.
Function Documentation
gtk_window_close()
GDK_AVAILABLE_IN_ALL void gtk_window_close (GtkWindow * window)
gtk_window_destroy()
GDK_AVAILABLE_IN_ALL void gtk_window_destroy (GtkWindow * window)
Referenced by activate().
gtk_window_fullscreen()
GDK_AVAILABLE_IN_ALL void gtk_window_fullscreen (GtkWindow * window)
gtk_window_fullscreen_on_monitor()
GDK_AVAILABLE_IN_ALL void gtk_window_fullscreen_on_monitor (GtkWindow * window, GdkMonitor * monitor)
gtk_window_get_application()
GDK_AVAILABLE_IN_ALL GtkApplication * gtk_window_get_application (GtkWindow * window)
gtk_window_get_child()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_get_child (GtkWindow * window)
gtk_window_get_decorated()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_decorated (GtkWindow * window)
gtk_window_get_default_icon_name()
GDK_AVAILABLE_IN_ALL const char * gtk_window_get_default_icon_name (void)
gtk_window_get_default_size()
GDK_AVAILABLE_IN_ALL void gtk_window_get_default_size (GtkWindow * window, int * width, int * height)
gtk_window_get_default_widget()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_get_default_widget (GtkWindow * window)
gtk_window_get_deletable()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_deletable (GtkWindow * window)
gtk_window_get_destroy_with_parent()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_destroy_with_parent (GtkWindow * window)
gtk_window_get_focus()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_get_focus (GtkWindow * window)
gtk_window_get_focus_visible()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_focus_visible (GtkWindow * window)
gtk_window_get_group()
GDK_AVAILABLE_IN_ALL GtkWindowGroup * gtk_window_get_group (GtkWindow * window)
gtk_window_get_handle_menubar_accel()
GDK_AVAILABLE_IN_4_2 gboolean gtk_window_get_handle_menubar_accel (GtkWindow * window)
gtk_window_get_hide_on_close()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_hide_on_close (GtkWindow * window)
gtk_window_get_icon_name()
GDK_AVAILABLE_IN_ALL const char * gtk_window_get_icon_name (GtkWindow * window)
gtk_window_get_mnemonics_visible()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_mnemonics_visible (GtkWindow * window)
gtk_window_get_modal()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_modal (GtkWindow * window)
gtk_window_get_resizable()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_get_resizable (GtkWindow * window)
gtk_window_get_title()
GDK_AVAILABLE_IN_ALL const char * gtk_window_get_title (GtkWindow * window)
gtk_window_get_titlebar()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_get_titlebar (GtkWindow * window)
gtk_window_get_toplevels()
GDK_AVAILABLE_IN_ALL GListModel * gtk_window_get_toplevels (void)
gtk_window_get_transient_for()
GDK_AVAILABLE_IN_ALL GtkWindow * gtk_window_get_transient_for (GtkWindow * window)
gtk_window_get_type()
GDK_AVAILABLE_IN_ALL GType gtk_window_get_type (void)
gtk_window_has_group()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_has_group (GtkWindow * window)
gtk_window_is_active()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_is_active (GtkWindow * window)
gtk_window_is_fullscreen()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_is_fullscreen (GtkWindow * window)
gtk_window_is_maximized()
GDK_AVAILABLE_IN_ALL gboolean gtk_window_is_maximized (GtkWindow * window)
gtk_window_is_suspended()
GDK_AVAILABLE_IN_4_12 gboolean gtk_window_is_suspended (GtkWindow * window)
gtk_window_list_toplevels()
GDK_AVAILABLE_IN_ALL GList * gtk_window_list_toplevels (void)
gtk_window_maximize()
GDK_AVAILABLE_IN_ALL void gtk_window_maximize (GtkWindow * window)
gtk_window_minimize()
GDK_AVAILABLE_IN_ALL void gtk_window_minimize (GtkWindow * window)
gtk_window_new()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_window_new (void)
gtk_window_present()
GDK_AVAILABLE_IN_ALL void gtk_window_present (GtkWindow * window)
Referenced by activate().
gtk_window_present_with_time()
void gtk_window_present_with_time (GtkWindow * window, guint32 timestamp)
gtk_window_set_application()
GDK_AVAILABLE_IN_ALL void gtk_window_set_application (GtkWindow * window, GtkApplication * application)
gtk_window_set_auto_startup_notification()
GDK_AVAILABLE_IN_ALL void gtk_window_set_auto_startup_notification (gboolean setting)
gtk_window_set_child()
GDK_AVAILABLE_IN_ALL void gtk_window_set_child (GtkWindow * window, GtkWidget * child)
Referenced by activate().
gtk_window_set_decorated()
GDK_AVAILABLE_IN_ALL void gtk_window_set_decorated (GtkWindow * window, gboolean setting)
gtk_window_set_default_icon_name()
GDK_AVAILABLE_IN_ALL void gtk_window_set_default_icon_name (const char * name)
gtk_window_set_default_size()
GDK_AVAILABLE_IN_ALL void gtk_window_set_default_size (GtkWindow * window, int width, int height)
Referenced by activate().
gtk_window_set_default_widget()
GDK_AVAILABLE_IN_ALL void gtk_window_set_default_widget (GtkWindow * window, GtkWidget * default_widget)
gtk_window_set_deletable()
GDK_AVAILABLE_IN_ALL void gtk_window_set_deletable (GtkWindow * window, gboolean setting)
gtk_window_set_destroy_with_parent()
GDK_AVAILABLE_IN_ALL void gtk_window_set_destroy_with_parent (GtkWindow * window, gboolean setting)
gtk_window_set_display()
GDK_AVAILABLE_IN_ALL void gtk_window_set_display (GtkWindow * window, GdkDisplay * display)
gtk_window_set_focus()
GDK_AVAILABLE_IN_ALL void gtk_window_set_focus (GtkWindow * window, GtkWidget * focus)
gtk_window_set_focus_visible()
GDK_AVAILABLE_IN_ALL void gtk_window_set_focus_visible (GtkWindow * window, gboolean setting)
gtk_window_set_handle_menubar_accel()
GDK_AVAILABLE_IN_4_2 void gtk_window_set_handle_menubar_accel (GtkWindow * window, gboolean handle_menubar_accel)
gtk_window_set_hide_on_close()
GDK_AVAILABLE_IN_ALL void gtk_window_set_hide_on_close (GtkWindow * window, gboolean setting)
gtk_window_set_icon_name()
GDK_AVAILABLE_IN_ALL void gtk_window_set_icon_name (GtkWindow * window, const char * name)
gtk_window_set_interactive_debugging()
GDK_AVAILABLE_IN_ALL void gtk_window_set_interactive_debugging (gboolean enable)
gtk_window_set_mnemonics_visible()
GDK_AVAILABLE_IN_ALL void gtk_window_set_mnemonics_visible (GtkWindow * window, gboolean setting)
gtk_window_set_modal()
GDK_AVAILABLE_IN_ALL void gtk_window_set_modal (GtkWindow * window, gboolean modal)
gtk_window_set_resizable()
GDK_AVAILABLE_IN_ALL void gtk_window_set_resizable (GtkWindow * window, gboolean resizable)
gtk_window_set_startup_id()
GDK_AVAILABLE_IN_ALL void gtk_window_set_startup_id (GtkWindow * window, const char * startup_id)
gtk_window_set_title()
GDK_AVAILABLE_IN_ALL void gtk_window_set_title (GtkWindow * window, const char * title)
Referenced by activate().
gtk_window_set_titlebar()
GDK_AVAILABLE_IN_ALL void gtk_window_set_titlebar (GtkWindow * window, GtkWidget * titlebar)
gtk_window_set_transient_for()
GDK_AVAILABLE_IN_ALL void gtk_window_set_transient_for (GtkWindow * window, GtkWindow * parent)
gtk_window_unfullscreen()
GDK_AVAILABLE_IN_ALL void gtk_window_unfullscreen (GtkWindow * window)
gtk_window_unmaximize()
GDK_AVAILABLE_IN_ALL void gtk_window_unmaximize (GtkWindow * window)
gtk_window_unminimize()
GDK_AVAILABLE_IN_ALL void gtk_window_unminimize (GtkWindow * window)