Github User Fetcher: ldblib.c File Reference
ldblib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define ldblib_c
#define LUA_LIB
#define HOOKKEY "_HKEY"
#define gethooktable(L) luaL_getsubtable(L, LUA_REGISTRYINDEX, HOOKKEY)
Functions
static void checkstack (lua_State *L, lua_State *L1, int n)
static int db_getregistry (lua_State *L)
static int db_getmetatable (lua_State *L)
static int db_setmetatable (lua_State *L)
static int db_getuservalue (lua_State *L)
static int db_setuservalue (lua_State *L)
static void settabss (lua_State *L, const char *i, const char *v)
static void settabsi (lua_State *L, const char *i, int v)
static void settabsb (lua_State *L, const char *i, int v)
static lua_State * getthread (lua_State *L, int *arg)
static void treatstackoption (lua_State *L, lua_State *L1, const char *fname)
static int db_getinfo (lua_State *L)
static int db_getlocal (lua_State *L)
static int db_setlocal (lua_State *L)
static int auxupvalue (lua_State *L, int get)
static int db_getupvalue (lua_State *L)
static int db_setupvalue (lua_State *L)
static int checkupval (lua_State *L, int argf, int argnup)
static int db_upvalueid (lua_State *L)
static int db_upvaluejoin (lua_State *L)
static void hookf (lua_State *L, lua_Debug *ar)
static int makemask (const char *smask, int count)
static char * unmakemask (int mask, char *smask)
static int db_sethook (lua_State *L)
static int db_gethook (lua_State *L)
static int db_debug (lua_State *L)
static int db_traceback (lua_State *L)
LUAMOD_API int luaopen_debug (lua_State *L)
Variables
static const luaL_Reg dblib []
Macro Definition Documentation
gethooktable
#define gethooktable (L) luaL_getsubtable(L, LUA_REGISTRYINDEX, HOOKKEY)
Definition at line 264 of file lua-5.2.4/src/ldblib.c.
Referenced by db_gethook(), db_gethook(), db_sethook(), db_sethook(), and hookf().
HOOKKEY
#define HOOKKEY "_HKEY"
Definition at line 21 of file lua-5.2.4/src/ldblib.c.
ldblib_c
#define ldblib_c
Definition at line 12 of file lua-5.2.4/src/ldblib.c.
LUA_LIB
#define LUA_LIB
Definition at line 13 of file lua-5.2.4/src/ldblib.c.
Function Documentation
auxupvalue()
static int auxupvalue (lua_State * L, int get) static
Definition at line 213 of file lua-5.2.4/src/ldblib.c.
{
  const char *name;
  int n = luaL_checkint(L, 2);
  luaL_checktype(L, 1, LUA_TFUNCTION);
  name = get ? lua_getupvalue(L, 1, n) : lua_setupvalue(L, 1, n);
  if (name == NULL) return 0;
  lua_pushstring(L, name);
  lua_insert(L, -(get+1));
  return get + 1;
}
References lua_getupvalue(), lua_insert, lua_pushstring(), lua_setupvalue(), LUA_TFUNCTION, luaL_checkint, luaL_checktype(), name, and NULL.
Referenced by db_getupvalue(), and db_setupvalue().
checkstack()
static void checkstack (lua_State * L, lua_State * L1, int n) static
Definition at line 24 of file lua-5.2.4/src/ldblib.c.
{
  if (L != L1 && !lua_checkstack(L1, n))
    luaL_error(L, "stack overflow");
}
References lua_checkstack(), and luaL_error().
Referenced by db_gethook(), db_getinfo(), db_getlocal(), db_sethook(), and db_setlocal().
checkupval()
static int checkupval (lua_State * L, int argf, int argnup) static
Definition at line 236 of file lua-5.2.4/src/ldblib.c.
{
  lua_Debug ar;
  int nup = luaL_checkint(L, argnup);
  luaL_checktype(L, argf, LUA_TFUNCTION);
  lua_pushvalue(L, argf);
  lua_getinfo(L, ">u", &ar);
  luaL_argcheck(L, 1 <= nup && nup <= ar.nups, argnup, "invalid upvalue index");
  return nup;
}
References lua_getinfo(), lua_pushvalue(), LUA_TFUNCTION, luaL_argcheck, luaL_checkint, luaL_checktype(), and lua_Debug::nups.
Referenced by db_upvalueid(), and db_upvaluejoin().
db_debug()
static int db_debug (lua_State * L) static
Definition at line 354 of file lua-5.2.4/src/ldblib.c.
{
  for (;;) {
    char buffer[250];
    luai_writestringerror("%s", "lua_debug> ");
    if (fgets(buffer, sizeof(buffer), stdin) == 0 ||
        strcmp(buffer, "cont\n") == 0)
      return 0;
    if (luaL_loadbuffer(L, buffer, strlen(buffer), "=(debug command)") ||
        lua_pcall(L, 0, 0, 0))
      luai_writestringerror("%s\n", lua_tostring(L, -1));
    lua_settop(L, 0);  /* remove eventual returns */
  }
}
References lua_pcall, lua_settop(), lua_tostring, luai_writestringerror, and luaL_loadbuffer.
db_gethook()
static int db_gethook (lua_State * L) static
Definition at line 333 of file lua-5.2.4/src/ldblib.c.
{
  int arg;
  lua_State *L1 = getthread(L, &arg);
  char buff[5];
  int mask = lua_gethookmask(L1);
  lua_Hook hook = lua_gethook(L1);
  if (hook != NULL && hook != hookf)  /* external hook? */
    lua_pushliteral(L, "external hook");
  else {
    gethooktable(L);
    checkstack(L, L1, 1);
    lua_pushthread(L1); lua_xmove(L1, L, 1);
    lua_rawget(L, -2);   /* get hook */
    lua_remove(L, -2);  /* remove hook table */
  }
  lua_pushstring(L, unmakemask(mask, buff));
  lua_pushinteger(L, lua_gethookcount(L1));
  return 3;
}
References arg, checkstack(), gethooktable, getthread(), hookf(), lua_gethook(), lua_gethookcount(), lua_gethookmask(), lua_pushinteger(), lua_pushliteral, lua_pushstring(), lua_pushthread(), lua_rawget(), lua_remove, lua_xmove(), mask, NULL, and unmakemask().
db_getinfo()
static int db_getinfo (lua_State * L) static
Definition at line 117 of file lua-5.2.4/src/ldblib.c.
{
  lua_Debug ar;
  int arg;
  lua_State *L1 = getthread(L, &arg);
  const char *options = luaL_optstring(L, arg+2, "flnStu");
  checkstack(L, L1, 3);
  if (lua_isnumber(L, arg+1)) {
    if (!lua_getstack(L1, (int)lua_tointeger(L, arg+1), &ar)) {
      lua_pushnil(L);  /* level out of range */
      return 1;
    }
  }
  else if (lua_isfunction(L, arg+1)) {
    lua_pushfstring(L, ">%s", options);
    options = lua_tostring(L, -1);
    lua_pushvalue(L, arg+1);
    lua_xmove(L, L1, 1);
  }
  else
    return luaL_argerror(L, arg+1, "function or level expected");
  if (!lua_getinfo(L1, options, &ar))
    return luaL_argerror(L, arg+2, "invalid option");
  lua_createtable(L, 0, 2);
  if (strchr(options, 'S')) {
    settabss(L, "source", ar.source);
    settabss(L, "short_src", ar.short_src);
    settabsi(L, "linedefined", ar.linedefined);
    settabsi(L, "lastlinedefined", ar.lastlinedefined);
    settabss(L, "what", ar.what);
  }
  if (strchr(options, 'l'))
    settabsi(L, "currentline", ar.currentline);
  if (strchr(options, 'u')) {
    settabsi(L, "nups", ar.nups);
    settabsi(L, "nparams", ar.nparams);
    settabsb(L, "isvararg", ar.isvararg);
  }
  if (strchr(options, 'n')) {
    settabss(L, "name", ar.name);
    settabss(L, "namewhat", ar.namewhat);
  }
  if (strchr(options, 't'))
    settabsb(L, "istailcall", ar.istailcall);
  if (strchr(options, 'L'))
    treatstackoption(L, L1, "activelines");
  if (strchr(options, 'f'))
    treatstackoption(L, L1, "func");
  return 1;  /* return table */
}
References arg, checkstack(), lua_Debug::currentline, getthread(), lua_Debug::istailcall, lua_Debug::isvararg, lua_Debug::lastlinedefined, lua_Debug::linedefined, lua_createtable(), lua_getinfo(), lua_getstack(), lua_isfunction, lua_isnumber(), lua_pushfstring(), lua_pushnil(), lua_pushvalue(), lua_tointeger, lua_tostring, lua_xmove(), luaL_argerror(), luaL_optstring, lua_Debug::name, lua_Debug::namewhat, lua_Debug::nparams, lua_Debug::nups, settabsb(), settabsi(), settabss(), lua_Debug::short_src, lua_Debug::source, treatstackoption(), and lua_Debug::what.
db_getlocal()
static int db_getlocal (lua_State * L) static
Definition at line 168 of file lua-5.2.4/src/ldblib.c.
{
  int arg;
  lua_State *L1 = getthread(L, &arg);
  lua_Debug ar;
  const char *name;
  int nvar = luaL_checkint(L, arg+2);  /* local-variable index */
  if (lua_isfunction(L, arg + 1)) {  /* function argument? */
    lua_pushvalue(L, arg + 1);  /* push function */
    lua_pushstring(L, lua_getlocal(L, NULL, nvar));  /* push local name */
    return 1;
  }
  else {  /* stack-level argument */
    if (!lua_getstack(L1, luaL_checkint(L, arg+1), &ar))  /* out of range? */
      return luaL_argerror(L, arg+1, "level out of range");
    checkstack(L, L1, 1);
    name = lua_getlocal(L1, &ar, nvar);
    if (name) {
      lua_xmove(L1, L, 1);  /* push local value */
      lua_pushstring(L, name);  /* push name */
      lua_pushvalue(L, -2);  /* re-order */
      return 2;
    }
    else {
      lua_pushnil(L);  /* no name (nor value) */
      return 1;
    }
  }
}
References arg, checkstack(), getthread(), lua_getlocal(), lua_getstack(), lua_isfunction, lua_pushnil(), lua_pushstring(), lua_pushvalue(), lua_xmove(), luaL_argerror(), luaL_checkint, name, and NULL.
db_getmetatable()
static int db_getmetatable (lua_State * L) static
Definition at line 36 of file lua-5.2.4/src/ldblib.c.
{
  luaL_checkany(L, 1);
  if (!lua_getmetatable(L, 1)) {
    lua_pushnil(L);  /* no metatable */
  }
  return 1;
}
References lua_getmetatable(), lua_pushnil(), and luaL_checkany().
db_getregistry()
static int db_getregistry (lua_State * L) static
Definition at line 30 of file lua-5.2.4/src/ldblib.c.
{
  lua_pushvalue(L, LUA_REGISTRYINDEX);
  return 1;
}
References lua_pushvalue(), and LUA_REGISTRYINDEX.
db_getupvalue()
static int db_getupvalue (lua_State * L) static
Definition at line 225 of file lua-5.2.4/src/ldblib.c.
{
  return auxupvalue(L, 1);
}
References auxupvalue().
db_getuservalue()
static int db_getuservalue (lua_State * L) static
Definition at line 55 of file lua-5.2.4/src/ldblib.c.
{
  if (lua_type(L, 1) != LUA_TUSERDATA)
    lua_pushnil(L);
  else
    lua_getuservalue(L, 1);
  return 1;
}
References lua_getuservalue, lua_pushnil(), LUA_TUSERDATA, and lua_type().
db_sethook()
static int db_sethook (lua_State * L) static
hooktable.__mode = "k"
Definition at line 304 of file lua-5.2.4/src/ldblib.c.
{
  int arg, mask, count;
  lua_Hook func;
  lua_State *L1 = getthread(L, &arg);
  if (lua_isnoneornil(L, arg+1)) {
    lua_settop(L, arg+1);
    func = NULL; mask = 0; count = 0;  /* turn off hooks */
  }
  else {
    const char *smask = luaL_checkstring(L, arg+2);
    luaL_checktype(L, arg+1, LUA_TFUNCTION);
    count = luaL_optint(L, arg+3, 0);
    func = hookf; mask = makemask(smask, count);
  }
  if (gethooktable(L) == 0) {  /* creating hook table? */
    lua_pushstring(L, "k");
    lua_setfield(L, -2, "__mode");  /** hooktable.__mode = "k" */
    lua_pushvalue(L, -1);
    lua_setmetatable(L, -2);  /* setmetatable(hooktable) = hooktable */
  }
  checkstack(L, L1, 1);
  lua_pushthread(L1); lua_xmove(L1, L, 1);
  lua_pushvalue(L, arg+1);
  lua_rawset(L, -3);  /* set new hook */
  lua_sethook(L1, func, mask, count);  /* set hooks */
  return 0;
}
References arg, checkstack(), gethooktable, getthread(), hookf(), lua_isnoneornil, lua_pushstring(), lua_pushthread(), lua_pushvalue(), lua_rawset(), lua_setfield(), lua_sethook(), lua_setmetatable(), lua_settop(), LUA_TFUNCTION, lua_xmove(), luaL_checkstring, luaL_checktype(), luaL_optint, makemask(), mask, and NULL.
db_setlocal()
static int db_setlocal (lua_State * L) static
Definition at line 198 of file lua-5.2.4/src/ldblib.c.
{
  int arg;
  lua_State *L1 = getthread(L, &arg);
  lua_Debug ar;
  if (!lua_getstack(L1, luaL_checkint(L, arg+1), &ar))  /* out of range? */
    return luaL_argerror(L, arg+1, "level out of range");
  luaL_checkany(L, arg+3);
  lua_settop(L, arg+3);
  checkstack(L, L1, 1);
  lua_xmove(L, L1, 1);
  lua_pushstring(L, lua_setlocal(L1, &ar, luaL_checkint(L, arg+2)));
  return 1;
}
References arg, checkstack(), getthread(), lua_getstack(), lua_pushstring(), lua_setlocal(), lua_settop(), lua_xmove(), luaL_argerror(), luaL_checkany(), and luaL_checkint.
db_setmetatable()
static int db_setmetatable (lua_State * L) static
Definition at line 45 of file lua-5.2.4/src/ldblib.c.
{
  int t = lua_type(L, 2);
  luaL_argcheck(L, t == LUA_TNIL || t == LUA_TTABLE, 2,
                    "nil or table expected");
  lua_settop(L, 2);
  lua_setmetatable(L, 1);
  return 1;  /* return 1st argument */
}
References lua_setmetatable(), lua_settop(), LUA_TNIL, LUA_TTABLE, lua_type(), and luaL_argcheck.
db_setupvalue()
static int db_setupvalue (lua_State * L) static
Definition at line 230 of file lua-5.2.4/src/ldblib.c.
{
  luaL_checkany(L, 3);
  return auxupvalue(L, 0);
}
References auxupvalue(), and luaL_checkany().
db_setuservalue()
static int db_setuservalue (lua_State * L) static
Definition at line 64 of file lua-5.2.4/src/ldblib.c.
{
  if (lua_type(L, 1) == LUA_TLIGHTUSERDATA)
    luaL_argerror(L, 1, "full userdata expected, got light userdata");
  luaL_checktype(L, 1, LUA_TUSERDATA);
  if (!lua_isnoneornil(L, 2))
    luaL_checktype(L, 2, LUA_TTABLE);
  lua_settop(L, 2);
  lua_setuservalue(L, 1);
  return 1;
}
References lua_isnoneornil, lua_settop(), lua_setuservalue, LUA_TLIGHTUSERDATA, LUA_TTABLE, LUA_TUSERDATA, lua_type(), luaL_argerror(), and luaL_checktype().
db_traceback()
static int db_traceback (lua_State * L) static
Definition at line 369 of file lua-5.2.4/src/ldblib.c.
{
  int arg;
  lua_State *L1 = getthread(L, &arg);
  const char *msg = lua_tostring(L, arg + 1);
  if (msg == NULL && !lua_isnoneornil(L, arg + 1))  /* non-string 'msg'? */
    lua_pushvalue(L, arg + 1);  /* return it untouched */
  else {
    int level = luaL_optint(L, arg + 2, (L == L1) ? 1 : 0);
    luaL_traceback(L, L1, msg, level);
  }
  return 1;
}
References arg, getthread(), lua_isnoneornil, lua_pushvalue(), lua_tostring, luaL_optint, luaL_traceback(), and NULL.
db_upvalueid()
static int db_upvalueid (lua_State * L) static
Definition at line 247 of file lua-5.2.4/src/ldblib.c.
{
  int n = checkupval(L, 1, 2);
  lua_pushlightuserdata(L, lua_upvalueid(L, 1, n));
  return 1;
}
References checkupval(), lua_pushlightuserdata(), and lua_upvalueid().
db_upvaluejoin()
static int db_upvaluejoin (lua_State * L) static
Definition at line 254 of file lua-5.2.4/src/ldblib.c.
{
  int n1 = checkupval(L, 1, 2);
  int n2 = checkupval(L, 3, 4);
  luaL_argcheck(L, !lua_iscfunction(L, 1), 1, "Lua function expected");
  luaL_argcheck(L, !lua_iscfunction(L, 3), 3, "Lua function expected");
  lua_upvaluejoin(L, 1, n1, 3, n2);
  return 0;
}
References checkupval(), lua_iscfunction(), lua_upvaluejoin(), and luaL_argcheck.
getthread()
static lua_State * getthread (lua_State * L, int * arg) static
Definition at line 94 of file lua-5.2.4/src/ldblib.c.
{
  if (lua_isthread(L, 1)) {
    *arg = 1;
    return lua_tothread(L, 1);
  }
  else {
    *arg = 0;
    return L;
  }
}
References arg, lua_isthread, and lua_tothread().
Referenced by db_gethook(), db_getinfo(), db_getlocal(), db_sethook(), db_setlocal(), and db_traceback().
hookf()
static void hookf (lua_State * L, lua_Debug * ar) static
Definition at line 267 of file lua-5.2.4/src/ldblib.c.
{
  static const char *const hooknames[] =
    {"call", "return", "line", "count", "tail call"};
  gethooktable(L);
  lua_pushthread(L);
  lua_rawget(L, -2);
  if (lua_isfunction(L, -1)) {
    lua_pushstring(L, hooknames[(int)ar->event]);
    if (ar->currentline >= 0)
      lua_pushinteger(L, ar->currentline);
    else lua_pushnil(L);
    lua_assert(lua_getinfo(L, "lS", ar));
    lua_call(L, 2, 0);
  }
}
References lua_Debug::currentline, lua_Debug::event, gethooktable, lua_assert, lua_call, lua_getinfo(), lua_isfunction, lua_pushinteger(), lua_pushnil(), lua_pushstring(), lua_pushthread(), and lua_rawget().
Referenced by db_gethook(), and db_sethook().
luaopen_debug()
LUAMOD_API int luaopen_debug (lua_State * L)
Definition at line 404 of file lua-5.2.4/src/ldblib.c.
{
  luaL_newlib(L, dblib);
  return 1;
}
References dblib, and luaL_newlib.
makemask()
static int makemask (const char * smask, int count) static
Definition at line 284 of file lua-5.2.4/src/ldblib.c.
{
  int mask = 0;
  if (strchr(smask, 'c')) mask |= LUA_MASKCALL;
  if (strchr(smask, 'r')) mask |= LUA_MASKRET;
  if (strchr(smask, 'l')) mask |= LUA_MASKLINE;
  if (count > 0) mask |= LUA_MASKCOUNT;
  return mask;
}
References LUA_MASKCALL, LUA_MASKCOUNT, LUA_MASKLINE, LUA_MASKRET, and mask.
Referenced by db_sethook().
settabsb()
static void settabsb (lua_State * L, const char * i, int v) static
Definition at line 88 of file lua-5.2.4/src/ldblib.c.
{
  lua_pushboolean(L, v);
  lua_setfield(L, -2, i);
}
References lua_pushboolean(), and lua_setfield().
Referenced by db_getinfo().
settabsi()
static void settabsi (lua_State * L, const char * i, int v) static
Definition at line 82 of file lua-5.2.4/src/ldblib.c.
{
  lua_pushinteger(L, v);
  lua_setfield(L, -2, i);
}
References lua_pushinteger(), and lua_setfield().
Referenced by db_getinfo().
settabss()
static void settabss (lua_State * L, const char * i, const char * v) static
Definition at line 76 of file lua-5.2.4/src/ldblib.c.
{
  lua_pushstring(L, v);
  lua_setfield(L, -2, i);
}
References lua_pushstring(), and lua_setfield().
Referenced by db_getinfo().
treatstackoption()
static void treatstackoption (lua_State * L, lua_State * L1, const char * fname) static
Definition at line 106 of file lua-5.2.4/src/ldblib.c.
{
  if (L == L1) {
    lua_pushvalue(L, -2);
    lua_remove(L, -3);
  }
  else
    lua_xmove(L1, L, 1);
  lua_setfield(L, -2, fname);
}
References lua_pushvalue(), lua_remove, lua_setfield(), and lua_xmove().
Referenced by db_getinfo().
unmakemask()
static char * unmakemask (int mask, char * smask) static
Definition at line 294 of file lua-5.2.4/src/ldblib.c.
{
  int i = 0;
  if (mask & LUA_MASKCALL) smask[i++] = 'c';
  if (mask & LUA_MASKRET) smask[i++] = 'r';
  if (mask & LUA_MASKLINE) smask[i++] = 'l';
  smask[i] = '\0';
  return smask;
}
References LUA_MASKCALL, LUA_MASKLINE, LUA_MASKRET, and mask.
Referenced by db_gethook().
Variable Documentation
dblib
const luaL_Reg dblib[] static
Initial value:
= {
  {"debug", db_debug},
  {"getuservalue", db_getuservalue},
  {"gethook", db_gethook},
  {"getinfo", db_getinfo},
  {"getlocal", db_getlocal},
  {"getregistry", db_getregistry},
  {"getmetatable", db_getmetatable},
  {"getupvalue", db_getupvalue},
  {"upvaluejoin", db_upvaluejoin},
  {"upvalueid", db_upvalueid},
  {"setuservalue", db_setuservalue},
  {"sethook", db_sethook},
  {"setlocal", db_setlocal},
  {"setmetatable", db_setmetatable},
  {"setupvalue", db_setupvalue},
  {"traceback", db_traceback},
  {NULL, NULL}
}
Definition at line 383 of file lua-5.2.4/src/ldblib.c.
{
  {"debug", db_debug},
  {"getuservalue", db_getuservalue},
  {"gethook", db_gethook},
  {"getinfo", db_getinfo},
  {"getlocal", db_getlocal},
  {"getregistry", db_getregistry},
  {"getmetatable", db_getmetatable},
  {"getupvalue", db_getupvalue},
  {"upvaluejoin", db_upvaluejoin},
  {"upvalueid", db_upvalueid},
  {"setuservalue", db_setuservalue},
  {"sethook", db_sethook},
  {"setlocal", db_setlocal},
  {"setmetatable", db_setmetatable},
  {"setupvalue", db_setupvalue},
  {"traceback", db_traceback},
  {NULL, NULL}
};
Referenced by luaopen_debug().