Github User Fetcher: ltable.c File Reference
ltable.c File Reference
#include "lprefix.h"
#include <math.h>
#include <limits.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "lvm.h"
Data Structures
struct AuxsetnodeT
Macros
#define ltable_c
#define LUA_CORE
#define MAXABITS cast_int(sizeof(int) * CHAR_BIT - 1)
#define MAXASIZE (1u << MAXABITS)
#define MAXHBITS (MAXABITS - 1)
#define hashpow2(t, n) (gnode(t, lmod((n), sizenode(t))))
#define hashstr(t, str) hashpow2(t, (str)->hash)
#define hashboolean(t, p) hashpow2(t, p)
#define hashint(t, i) hashpow2(t, i)
#define hashmod(t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
#define hashpointer(t, p) hashmod(t, point2uint(p))
#define dummynode (&dummynode_)
Functions
static int l_hashfloat (lua_Number n)
static Node * mainposition (const Table *t, const TValue *key)
static unsigned int arrayindex (const TValue *key)
static unsigned int findindex (lua_State *L, Table *t, StkId key)
int luaH_next (lua_State *L, Table *t, StkId key)
static unsigned int computesizes (unsigned int nums[], unsigned int *pna)
static int countint (const TValue *key, unsigned int *nums)
static unsigned int numusearray (const Table *t, unsigned int *nums)
static int numusehash (const Table *t, unsigned int *nums, unsigned int *pna)
static void setarrayvector (lua_State *L, Table *t, unsigned int size)
static void setnodevector (lua_State *L, Table *t, unsigned int size)
static void auxsetnode (lua_State *L, void *ud)
void luaH_resize (lua_State *L, Table *t, unsigned int nasize, unsigned int nhsize)
void luaH_resizearray (lua_State *L, Table *t, unsigned int nasize)
static void rehash (lua_State *L, Table *t, const TValue *ek)
Table * luaH_new (lua_State *L)
void luaH_free (lua_State *L, Table *t)
static Node * getfreepos (Table *t)
TValue * luaH_newkey (lua_State *L, Table *t, const TValue *key)
const TValue * luaH_getint (Table *t, lua_Integer key)
const TValue * luaH_getshortstr (Table *t, TString *key)
static const TValue * getgeneric (Table *t, const TValue *key)
const TValue * luaH_getstr (Table *t, TString *key)
const TValue * luaH_get (Table *t, const TValue *key)
TValue * luaH_set (lua_State *L, Table *t, const TValue *key)
void luaH_setint (lua_State *L, Table *t, lua_Integer key, TValue *value)
static lua_Unsigned unbound_search (Table *t, lua_Unsigned j)
lua_Unsigned luaH_getn (Table *t)
Variables
static const Node dummynode_
Macro Definition Documentation
dummynode
#define dummynode (&dummynode_)
Definition at line 75 of file lua-5.3.6/src/ltable.c.
Referenced by setnodevector().
hashboolean
#define hashboolean (t, p) hashpow2(t, p)
Definition at line 61 of file lua-5.3.6/src/ltable.c.
Referenced by mainposition().
hashint
#define hashint (t, i) hashpow2(t, i)
Definition at line 62 of file lua-5.3.6/src/ltable.c.
Referenced by luaH_getint(), and mainposition().
hashmod
#define hashmod (t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
Definition at line 69 of file lua-5.3.6/src/ltable.c.
Referenced by mainposition().
hashpointer
#define hashpointer (t, p) hashmod(t, point2uint(p))
Definition at line 72 of file lua-5.3.6/src/ltable.c.
Referenced by mainposition().
hashpow2
#define hashpow2 (t, n) (gnode(t, lmod((n), sizenode(t))))
Definition at line 58 of file lua-5.3.6/src/ltable.c.
Referenced by mainposition().
hashstr
#define hashstr (t, str) hashpow2(t, (str)->hash)
Definition at line 60 of file lua-5.3.6/src/ltable.c.
Referenced by luaH_getshortstr(), and mainposition().
ltable_c
#define ltable_c
Definition at line 7 of file lua-5.3.6/src/ltable.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/ltable.c.
MAXABITS
#define MAXABITS cast_int(sizeof(int) * CHAR_BIT - 1)
Definition at line 46 of file lua-5.3.6/src/ltable.c.
Referenced by numusearray(), and rehash().
MAXASIZE
#define MAXASIZE (1u << MAXABITS)
Definition at line 47 of file lua-5.3.6/src/ltable.c.
Referenced by arrayindex().
MAXHBITS
#define MAXHBITS (MAXABITS - 1)
Definition at line 55 of file lua-5.3.6/src/ltable.c.
Referenced by setnodevector().
Function Documentation
arrayindex()
static unsigned int arrayindex (const TValue * key) static
Definition at line 144 of file lua-5.3.6/src/ltable.c.
{
  if (ttisinteger(key)) {
    lua_Integer k = ivalue(key);
    if (0 < k && (lua_Unsigned)k <= MAXASIZE)
      return cast(unsigned int, k);  /* 'key' is an appropriate array index */
  }
  return 0;  /* 'key' did not match some condition */
}
References cast, ivalue, MAXASIZE, and ttisinteger.
Referenced by countint(), and findindex().
auxsetnode()
static void auxsetnode (lua_State * L, void * ud) static
Definition at line 341 of file lua-5.3.6/src/ltable.c.
{
  AuxsetnodeT *asn = cast(AuxsetnodeT *, ud);
  setnodevector(L, asn->t, asn->nhsize);
}
References cast, AuxsetnodeT::nhsize, setnodevector(), and AuxsetnodeT::t.
Referenced by luaH_resize().
computesizes()
static unsigned int computesizes (unsigned int nums[], unsigned int * pna) static
Definition at line 219 of file lua-5.3.6/src/ltable.c.
{
  int i;
  unsigned int twotoi;  /* 2^i (candidate for optimal size) */
  unsigned int a = 0;  /* number of elements smaller than 2^i */
  unsigned int na = 0;  /* number of elements to go to array part */
  unsigned int optimal = 0;  /* optimal size for array part */
  /* loop while keys can fill more than half of total size */
  for (i = 0, twotoi = 1;
       twotoi > 0 && *pna > twotoi / 2;
       i++, twotoi *= 2) {
    if (nums[i] > 0) {
      a += nums[i];
      if (a > twotoi/2) {  /* more than half elements present? */
        optimal = twotoi;  /* optimal size (till now) */
        na = a;  /* all elements up to 'optimal' will go to array part */
      }
    }
  }
  lua_assert((optimal == 0 || optimal / 2 < na) && na <= optimal);
  *pna = na;
  return optimal;
}
References lua_assert.
Referenced by rehash().
countint()
static int countint (const TValue * key, unsigned int * nums) static
Definition at line 243 of file lua-5.3.6/src/ltable.c.
{
  unsigned int k = arrayindex(key);
  if (k != 0) {  /* is 'key' an appropriate array index? */
    nums[luaO_ceillog2(k)]++;  /* count as such */
    return 1;
  }
  else
    return 0;
}
References arrayindex(), and luaO_ceillog2().
Referenced by numusehash(), and rehash().
findindex()
static unsigned int findindex (lua_State * L, Table * t, StkId key) static
Definition at line 159 of file lua-5.3.6/src/ltable.c.
{
  unsigned int i;
  if (ttisnil(key)) return 0;  /* first iteration */
  i = arrayindex(key);
  if (i != 0 && i <= t->sizearray)  /* is 'key' inside array part? */
    return i;  /* yes; that's the index */
  else {
    int nx;
    Node *n = mainposition(t, key);
    for (;;) {  /* check whether 'key' is somewhere in the chain */
      /* key may be dead already, but it is ok to use it in 'next' */
      if (luaV_rawequalobj(gkey(n), key) ||
            (ttisdeadkey(gkey(n)) && iscollectable(key) &&
             deadvalue(gkey(n)) == gcvalue(key))) {
        i = cast_int(n - gnode(t, 0));  /* key index in hash table */
        /* hash elements are numbered after array ones */
        return (i + 1) + t->sizearray;
      }
      nx = gnext(n);
      if (nx == 0)
        luaG_runerror(L, "invalid key to 'next'");  /* key not found */
      else n += nx;
    }
  }
}
References arrayindex(), cast_int, deadvalue, gcvalue, gkey, gnext, gnode, iscollectable, luaG_runerror(), luaV_rawequalobj, mainposition(), Table::sizearray, ttisdeadkey, and ttisnil.
Referenced by luaH_next().
getfreepos()
static Node * getfreepos (Table * t) static
Definition at line 441 of file lua-5.3.6/src/ltable.c.
{
  if (!isdummy(t)) {
    while (t->lastfree > t->node) {
      t->lastfree--;
      if (ttisnil(gkey(t->lastfree)))
        return t->lastfree;
    }
  }
  return NULL;  /* could not find a free place */
}
References gkey, isdummy, Table::lastfree, Table::node, NULL, and ttisnil.
Referenced by luaH_newkey().
getgeneric()
static const TValue * getgeneric (Table * t, const TValue * key) static
Definition at line 560 of file lua-5.3.6/src/ltable.c.
{
  Node *n = mainposition(t, key);
  for (;;) {  /* check whether 'key' is somewhere in the chain */
    if (luaV_rawequalobj(gkey(n), key))
      return gval(n);  /* that's it */
    else {
      int nx = gnext(n);
      if (nx == 0)
        return luaO_nilobject;  /* not found */
      n += nx;
    }
  }
}
References gkey, gnext, gval, luaO_nilobject, luaV_rawequalobj, and mainposition().
Referenced by luaH_get(), and luaH_getstr().
l_hashfloat()
static int l_hashfloat (lua_Number n) static
Definition at line 97 of file lua-5.3.6/src/ltable.c.
{
  int i;
  lua_Integer ni;
  n = l_mathop(frexp)(n, &i) * -cast_num(INT_MIN);
  if (!lua_numbertointeger(n, &ni)) {  /* is 'n' inf/-inf/NaN? */
    lua_assert(luai_numisnan(n) || l_mathop(fabs)(n) == cast_num(HUGE_VAL));
    return 0;
  }
  else {  /* normal case */
    unsigned int u = cast(unsigned int, i) + cast(unsigned int, ni);
    return cast_int(u <= cast(unsigned int, INT_MAX) ? u : ~u);
  }
}
References cast, cast_int, cast_num, l_mathop, lua_assert, lua_numbertointeger, and luai_numisnan.
Referenced by mainposition().
luaH_free()
void luaH_free (lua_State * L, Table * t)
Definition at line 433 of file lua-5.3.6/src/ltable.c.
{
  if (!isdummy(t))
    luaM_freearray(L, t->node, cast(size_t, sizenode(t)));
  luaM_freearray(L, t->array, t->sizearray);
  luaM_free(L, t);
}
References Table::array, cast, isdummy, luaM_free, luaM_freearray, Table::node, Table::sizearray, and sizenode.
luaH_get()
const TValue * luaH_get (Table * t, const TValue * key)
Definition at line 589 of file lua-5.3.6/src/ltable.c.
{
  switch (ttype(key)) {
    case LUA_TSHRSTR: return luaH_getshortstr(t, tsvalue(key));
    case LUA_TNUMINT: return luaH_getint(t, ivalue(key));
    case LUA_TNIL: return luaO_nilobject;
    case LUA_TNUMFLT: {
      lua_Integer k;
      if (luaV_tointeger(key, &k, 0)) /* index is int? */
        return luaH_getint(t, k);  /* use specialized version */
      /* else... */
    }  /* FALLTHROUGH */
    default:
      return getgeneric(t, key);
  }
}
References getgeneric(), ivalue, LUA_TNIL, LUA_TNUMFLT, LUA_TNUMINT, LUA_TSHRSTR, luaH_getint(), luaH_getshortstr(), luaO_nilobject, luaV_tointeger(), tsvalue, and ttype.
Referenced by luaH_set().
luaH_getint()
const TValue * luaH_getint (Table * t, lua_Integer key)
Definition at line 516 of file lua-5.3.6/src/ltable.c.
{
  /* (1 <= key && key <= t->sizearray) */
  if (l_castS2U(key) - 1 < t->sizearray)
    return &t->array[key - 1];
  else {
    Node *n = hashint(t, key);
    for (;;) {  /* check whether 'key' is somewhere in the chain */
      if (ttisinteger(gkey(n)) && ivalue(gkey(n)) == key)
        return gval(n);  /* that's it */
      else {
        int nx = gnext(n);
        if (nx == 0) break;
        n += nx;
      }
    }
    return luaO_nilobject;
  }
}
References Table::array, gkey, gnext, gval, hashint, ivalue, l_castS2U, luaO_nilobject, Table::sizearray, and ttisinteger.
Referenced by luaH_get(), luaH_setint(), and unbound_search().
luaH_getn()
lua_Unsigned luaH_getn (Table * t)
Definition at line 660 of file lua-5.3.6/src/ltable.c.
{
  unsigned int j = t->sizearray;
  if (j > 0 && ttisnil(&t->array[j - 1])) {
    /* there is a boundary in the array part: (binary) search for it */
    unsigned int i = 0;
    while (j - i > 1) {
      unsigned int m = (i+j)/2;
      if (ttisnil(&t->array[m - 1])) j = m;
      else i = m;
    }
    return i;
  }
  /* else must find a boundary in hash part */
  else if (isdummy(t))  /* hash part is empty? */
    return j;  /* that is easy... */
  else return unbound_search(t, j);
}
References Table::array, isdummy, Table::sizearray, ttisnil, and unbound_search().
luaH_getshortstr()
const TValue * luaH_getshortstr (Table * t, TString * key)
Definition at line 539 of file lua-5.3.6/src/ltable.c.
{
  Node *n = hashstr(t, key);
  lua_assert(key->tt == LUA_TSHRSTR);
  for (;;) {  /* check whether 'key' is somewhere in the chain */
    const TValue *k = gkey(n);
    if (ttisshrstring(k) && eqshrstr(tsvalue(k), key))
      return gval(n);  /* that's it */
    else {
      int nx = gnext(n);
      if (nx == 0)
        return luaO_nilobject;  /* not found */
      n += nx;
    }
  }
}
References eqshrstr, gkey, gnext, gval, hashstr, lua_assert, LUA_TSHRSTR, luaO_nilobject, tsvalue, and ttisshrstring.
Referenced by luaH_get(), luaH_getstr(), luaT_gettm(), luaT_gettmbyobj(), luaT_objtypename(), and luaV_execute().
luaH_getstr()
const TValue * luaH_getstr (Table * t, TString * key)
Definition at line 575 of file lua-5.3.6/src/ltable.c.
{
  if (key->tt == LUA_TSHRSTR)
    return luaH_getshortstr(t, key);
  else {  /* for long strings, use generic case */
    TValue ko;
    setsvalue(cast(lua_State *, NULL), &ko, key);
    return getgeneric(t, &ko);
  }
}
References cast, getgeneric(), LUA_TSHRSTR, luaH_getshortstr(), NULL, and setsvalue.
luaH_new()
Table * luaH_new (lua_State * L)
Definition at line 421 of file lua-5.3.6/src/ltable.c.
{
  GCObject *o = luaC_newobj(L, LUA_TTABLE, sizeof(Table));
  Table *t = gco2t(o);
  t->metatable = NULL;
  t->flags = cast_byte(~0);
  t->array = NULL;
  t->sizearray = 0;
  setnodevector(L, t, 0);
  return t;
}
References Table::array, cast_byte, Table::flags, gco2t, LUA_TTABLE, luaC_newobj(), Table::metatable, NULL, setnodevector(), and Table::sizearray.
luaH_newkey()
TValue * luaH_newkey (lua_State * L, Table * t, const TValue * key)
Definition at line 461 of file lua-5.3.6/src/ltable.c.
{
  Node *mp;
  TValue aux;
  if (ttisnil(key)) luaG_runerror(L, "table index is nil");
  else if (ttisfloat(key)) {
    lua_Integer k;
    if (luaV_tointeger(key, &k, 0)) {  /* does index fit in an integer? */
      setivalue(&aux, k);
      key = &aux;  /* insert it as an integer */
    }
    else if (luai_numisnan(fltvalue(key)))
      luaG_runerror(L, "table index is NaN");
  }
  mp = mainposition(t, key);
  if (!ttisnil(gval(mp)) || isdummy(t)) {  /* main position is taken? */
    Node *othern;
    Node *f = getfreepos(t);  /* get a free place */
    if (f == NULL) {  /* cannot find a free place? */
      rehash(L, t, key);  /* grow table */
      /* whatever called 'newkey' takes care of TM cache */
      return luaH_set(L, t, key);  /* insert key into grown table */
    }
    lua_assert(!isdummy(t));
    othern = mainposition(t, gkey(mp));
    if (othern != mp) {  /* is colliding node out of its main position? */
      /* yes; move colliding node into free position */
      while (othern + gnext(othern) != mp)  /* find previous */
        othern += gnext(othern);
      gnext(othern) = cast_int(f - othern);  /* rechain to point to 'f' */
      *f = *mp;  /* copy colliding node into free pos. (mp->next also goes) */
      if (gnext(mp) != 0) {
        gnext(f) += cast_int(mp - f);  /* correct 'next' */
        gnext(mp) = 0;  /* now 'mp' is free */
      }
      setnilvalue(gval(mp));
    }
    else {  /* colliding node is in its own main position */
      /* new node will go into free position */
      if (gnext(mp) != 0)
        gnext(f) = cast_int((mp + gnext(mp)) - f);  /* chain new position */
      else lua_assert(gnext(f) == 0);
      gnext(mp) = cast_int(f - mp);
      mp = f;
    }
  }
  setnodekey(L, &mp->i_key, key);
  luaC_barrierback(L, t, key);
  lua_assert(ttisnil(gval(mp)));
  return gval(mp);
}
References cast_int, fltvalue, getfreepos(), gkey, gnext, gval, Node::i_key, isdummy, lua_assert, luaC_barrierback, luaG_runerror(), luaH_set(), luai_numisnan, luaV_tointeger(), mainposition(), NULL, rehash(), setivalue, setnilvalue, setnodekey, ttisfloat, and ttisnil.
Referenced by luaH_set(), and luaH_setint().
luaH_next()
int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 186 of file lua-5.3.6/src/ltable.c.
{
  unsigned int i = findindex(L, t, key);  /* find original element */
  for (; i < t->sizearray; i++) {  /* try first array part */
    if (!ttisnil(&t->array[i])) {  /* a non-nil value? */
      setivalue(key, i + 1);
      setobj2s(L, key+1, &t->array[i]);
      return 1;
    }
  }
  for (i -= t->sizearray; cast_int(i) < sizenode(t); i++) {  /* hash part */
    if (!ttisnil(gval(gnode(t, i)))) {  /* a non-nil value? */
      setobj2s(L, key, gkey(gnode(t, i)));
      setobj2s(L, key+1, gval(gnode(t, i)));
      return 1;
    }
  }
  return 0;  /* no more elements */
}
References Table::array, cast_int, findindex(), gkey, gnode, gval, setivalue, setobj2s, Table::sizearray, sizenode, and ttisnil.
luaH_resize()
void luaH_resize (lua_State * L, Table * t, unsigned int nasize, unsigned int nhsize)
Definition at line 347 of file lua-5.3.6/src/ltable.c.
{
  unsigned int i;
  int j;
  AuxsetnodeT asn;
  unsigned int oldasize = t->sizearray;
  int oldhsize = allocsizenode(t);
  Node *nold = t->node;  /* save old hash ... */
  if (nasize > oldasize)  /* array part must grow? */
    setarrayvector(L, t, nasize);
  /* create new hash part with appropriate size */
  asn.t = t; asn.nhsize = nhsize;
  if (luaD_rawrunprotected(L, auxsetnode, &asn) != LUA_OK) {  /* mem. error? */
    setarrayvector(L, t, oldasize);  /* array back to its original size */
    luaD_throw(L, LUA_ERRMEM);  /* rethrow memory error */
  }
  if (nasize < oldasize) {  /* array part must shrink? */
    t->sizearray = nasize;
    /* re-insert elements from vanishing slice */
    for (i=nasize; i<oldasize; i++) {
      if (!ttisnil(&t->array[i]))
        luaH_setint(L, t, i + 1, &t->array[i]);
    }
    /* shrink array */
    luaM_reallocvector(L, t->array, oldasize, nasize, TValue);
  }
  /* re-insert elements from hash part */
  for (j = oldhsize - 1; j >= 0; j--) {
    Node *old = nold + j;
    if (!ttisnil(gval(old))) {
      /* doesn't need barrier/invalidate cache, as entry was
         already present in the table */
      setobjt2t(L, luaH_set(L, t, gkey(old)), gval(old));
    }
  }
  if (oldhsize > 0)  /* not the dummy node? */
    luaM_freearray(L, nold, cast(size_t, oldhsize)); /* free old hash */
}
References allocsizenode, Table::array, auxsetnode(), cast, gkey, gval, LUA_ERRMEM, LUA_OK, luaD_rawrunprotected(), luaD_throw(), luaH_set(), luaH_setint(), luaM_freearray, luaM_reallocvector, AuxsetnodeT::nhsize, Table::node, setarrayvector(), setobjt2t, Table::sizearray, AuxsetnodeT::t, and ttisnil.
Referenced by luaH_resizearray(), and rehash().
luaH_resizearray()
void luaH_resizearray (lua_State * L, Table * t, unsigned int nasize)
Definition at line 387 of file lua-5.3.6/src/ltable.c.
{
  int nsize = allocsizenode(t);
  luaH_resize(L, t, nasize, nsize);
}
References allocsizenode, and luaH_resize().
luaH_set()
TValue * luaH_set (lua_State * L, Table * t, const TValue * key)
Definition at line 610 of file lua-5.3.6/src/ltable.c.
{
  const TValue *p = luaH_get(t, key);
  if (p != luaO_nilobject)
    return cast(TValue *, p);
  else return luaH_newkey(L, t, key);
}
References cast, luaH_get(), luaH_newkey(), and luaO_nilobject.
Referenced by luaH_newkey(), and luaH_resize().
luaH_setint()
void luaH_setint (lua_State * L, Table * t, lua_Integer key, TValue * value)
Definition at line 618 of file lua-5.3.6/src/ltable.c.
{
  const TValue *p = luaH_getint(t, key);
  TValue *cell;
  if (p != luaO_nilobject)
    cell = cast(TValue *, p);
  else {
    TValue k;
    setivalue(&k, key);
    cell = luaH_newkey(L, t, &k);
  }
  setobj2t(L, cell, value);
}
References cast, luaH_getint(), luaH_newkey(), luaO_nilobject, setivalue, setobj2t, and value.
Referenced by luaH_resize().
mainposition()
static Node * mainposition (const Table * t, const TValue * key) static
Definition at line 117 of file lua-5.3.6/src/ltable.c.
{
  switch (ttype(key)) {
    case LUA_TNUMINT:
      return hashint(t, ivalue(key));
    case LUA_TNUMFLT:
      return hashmod(t, l_hashfloat(fltvalue(key)));
    case LUA_TSHRSTR:
      return hashstr(t, tsvalue(key));
    case LUA_TLNGSTR:
      return hashpow2(t, luaS_hashlongstr(tsvalue(key)));
    case LUA_TBOOLEAN:
      return hashboolean(t, bvalue(key));
    case LUA_TLIGHTUSERDATA:
      return hashpointer(t, pvalue(key));
    case LUA_TLCF:
      return hashpointer(t, fvalue(key));
    default:
      lua_assert(!ttisdeadkey(key));
      return hashpointer(t, gcvalue(key));
  }
}
References bvalue, fltvalue, fvalue, gcvalue, hashboolean, hashint, hashmod, hashpointer, hashpow2, hashstr, ivalue, l_hashfloat(), lua_assert, LUA_TBOOLEAN, LUA_TLCF, LUA_TLIGHTUSERDATA, LUA_TLNGSTR, LUA_TNUMFLT, LUA_TNUMINT, LUA_TSHRSTR, luaS_hashlongstr(), pvalue, tsvalue, ttisdeadkey, and ttype.
Referenced by findindex(), getgeneric(), and luaH_newkey().
numusearray()
static unsigned int numusearray (const Table * t, unsigned int * nums) static
Definition at line 259 of file lua-5.3.6/src/ltable.c.
{
  int lg;
  unsigned int ttlg;  /* 2^lg */
  unsigned int ause = 0;  /* summation of 'nums' */
  unsigned int i = 1;  /* count to traverse all array keys */
  /* traverse each slice */
  for (lg = 0, ttlg = 1; lg <= MAXABITS; lg++, ttlg *= 2) {
    unsigned int lc = 0;  /* counter */
    unsigned int lim = ttlg;
    if (lim > t->sizearray) {
      lim = t->sizearray;  /* adjust upper limit */
      if (i > lim)
        break;  /* no more elements to count */
    }
    /* count elements in range (2^(lg - 1), 2^lg] */
    for (; i <= lim; i++) {
      if (!ttisnil(&t->array[i-1]))
        lc++;
    }
    nums[lg] += lc;
    ause += lc;
  }
  return ause;
}
References Table::array, MAXABITS, Table::sizearray, and ttisnil.
Referenced by rehash().
numusehash()
static int numusehash (const Table * t, unsigned int * nums, unsigned int * pna) static
Definition at line 285 of file lua-5.3.6/src/ltable.c.
{
  int totaluse = 0;  /* total number of elements */
  int ause = 0;  /* elements added to 'nums' (can go to array part) */
  int i = sizenode(t);
  while (i--) {
    Node *n = &t->node[i];
    if (!ttisnil(gval(n))) {
      ause += countint(gkey(n), nums);
      totaluse++;
    }
  }
  *pna += ause;
  return totaluse;
}
References countint(), gkey, gval, Table::node, sizenode, and ttisnil.
Referenced by rehash().
rehash()
static void rehash (lua_State * L, Table * t, const TValue * ek) static
Definition at line 395 of file lua-5.3.6/src/ltable.c.
{
  unsigned int asize;  /* optimal size for array part */
  unsigned int na;  /* number of keys in the array part */
  unsigned int nums[MAXABITS + 1];
  int i;
  int totaluse;
  for (i = 0; i <= MAXABITS; i++) nums[i] = 0;  /* reset counts */
  na = numusearray(t, nums);  /* count keys in array part */
  totaluse = na;  /* all those keys are integer keys */
  totaluse += numusehash(t, nums, &na);  /* count keys in hash part */
  /* count extra key */
  na += countint(ek, nums);
  totaluse++;
  /* compute new size for array part */
  asize = computesizes(nums, &na);
  /* resize the table to new computed sizes */
  luaH_resize(L, t, asize, totaluse - na);
}
References computesizes(), countint(), luaH_resize(), MAXABITS, numusearray(), and numusehash().
Referenced by luaH_newkey().
setarrayvector()
static void setarrayvector (lua_State * L, Table * t, unsigned int size) static
Definition at line 301 of file lua-5.3.6/src/ltable.c.
{
  unsigned int i;
  luaM_reallocvector(L, t->array, t->sizearray, size, TValue);
  for (i=t->sizearray; i<size; i++)
     setnilvalue(&t->array[i]);
  t->sizearray = size;
}
References Table::array, luaM_reallocvector, setnilvalue, and Table::sizearray.
Referenced by luaH_resize().
setnodevector()
static void setnodevector (lua_State * L, Table * t, unsigned int size) static
Definition at line 310 of file lua-5.3.6/src/ltable.c.
{
  if (size == 0) {  /* no elements to hash part? */
    t->node = cast(Node *, dummynode);  /* use common 'dummynode' */
    t->lsizenode = 0;
    t->lastfree = NULL;  /* signal that it is using dummy node */
  }
  else {
    int i;
    int lsize = luaO_ceillog2(size);
    if (lsize > MAXHBITS)
      luaG_runerror(L, "table overflow");
    size = twoto(lsize);
    t->node = luaM_newvector(L, size, Node);
    for (i = 0; i < (int)size; i++) {
      Node *n = gnode(t, i);
      gnext(n) = 0;
      setnilvalue(wgkey(n));
      setnilvalue(gval(n));
    }
    t->lsizenode = cast_byte(lsize);
    t->lastfree = gnode(t, size);  /* all positions are free */
  }
}
References cast, cast_byte, dummynode, gnext, gnode, gval, Table::lastfree, Table::lsizenode, luaG_runerror(), luaM_newvector, luaO_ceillog2(), MAXHBITS, Table::node, NULL, setnilvalue, twoto, and wgkey.
Referenced by auxsetnode(), and luaH_new().
unbound_search()
static lua_Unsigned unbound_search (Table * t, lua_Unsigned j) static
Definition at line 632 of file lua-5.3.6/src/ltable.c.
{
  lua_Unsigned i = j;  /* i is zero or a present index */
  j++;
  /* find 'i' and 'j' such that i is present and j is not */
  while (!ttisnil(luaH_getint(t, j))) {
    i = j;
    if (j > l_castS2U(LUA_MAXINTEGER) / 2) {  /* overflow? */
      /* table was built with bad purposes: resort to linear search */
      i = 1;
      while (!ttisnil(luaH_getint(t, i))) i++;
      return i - 1;
    }
    j *= 2;
  }
  /* now do a binary search between them */
  while (j - i > 1) {
    lua_Unsigned m = (i+j)/2;
    if (ttisnil(luaH_getint(t, m))) j = m;
    else i = m;
  }
  return i;
}
References l_castS2U, luaH_getint(), and ttisnil.
Referenced by luaH_getn().
Variable Documentation
dummynode_
const Node dummynode_ static
Initial value:
= {
  {NILCONSTANT},
  {{NILCONSTANT, 0}}
}
Definition at line 77 of file lua-5.3.6/src/ltable.c.
{
  {NILCONSTANT},  /* value */
  {{NILCONSTANT, 0}}  /* key */
};