Github User Fetcher: lcorolib.c File Reference
lcorolib.c File Reference
#include <stdlib.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lcorolib_c
#define LUA_LIB
Functions
static int auxresume (lua_State *L, lua_State *co, int narg)
static int luaB_coresume (lua_State *L)
static int luaB_auxwrap (lua_State *L)
static int luaB_cocreate (lua_State *L)
static int luaB_cowrap (lua_State *L)
static int luaB_yield (lua_State *L)
static int luaB_costatus (lua_State *L)
static int luaB_corunning (lua_State *L)
LUAMOD_API int luaopen_coroutine (lua_State *L)
Variables
static const luaL_Reg co_funcs []
Macro Definition Documentation
lcorolib_c
#define lcorolib_c
Definition at line 11 of file lua-5.2.4/src/lcorolib.c.
LUA_LIB
#define LUA_LIB
Definition at line 12 of file lua-5.2.4/src/lcorolib.c.
Function Documentation
auxresume()
static int auxresume (lua_State * L, lua_State * co, int narg) static
Definition at line 20 of file lua-5.2.4/src/lcorolib.c.
{
  int status;
  if (!lua_checkstack(co, narg)) {
    lua_pushliteral(L, "too many arguments to resume");
    return -1;  /* error flag */
  }
  if (lua_status(co) == LUA_OK && lua_gettop(co) == 0) {
    lua_pushliteral(L, "cannot resume dead coroutine");
    return -1;  /* error flag */
  }
  lua_xmove(L, co, narg);
  status = lua_resume(co, L, narg);
  if (status == LUA_OK || status == LUA_YIELD) {
    int nres = lua_gettop(co);
    if (!lua_checkstack(L, nres + 1)) {
      lua_pop(co, nres);  /* remove results anyway */
      lua_pushliteral(L, "too many results to resume");
      return -1;  /* error flag */
    }
    lua_xmove(co, L, nres);  /* move yielded values */
    return nres;
  }
  else {
    lua_xmove(co, L, 1);  /* move error message */
    return -1;  /* error flag */
  }
}
References lua_checkstack(), lua_gettop(), LUA_OK, lua_pop, lua_pushliteral, lua_resume(), lua_status(), lua_xmove(), and LUA_YIELD.
Referenced by luaB_auxwrap(), and luaB_coresume().
luaB_auxwrap()
static int luaB_auxwrap (lua_State * L) static
Definition at line 67 of file lua-5.2.4/src/lcorolib.c.
{
  lua_State *co = lua_tothread(L, lua_upvalueindex(1));
  int r = auxresume(L, co, lua_gettop(L));
  if (r < 0) {
    if (lua_isstring(L, -1)) {  /* error object is a string? */
      luaL_where(L, 1);  /* add extra info */
      lua_insert(L, -2);
      lua_concat(L, 2);
    }
    return lua_error(L);  /* propagate error */
  }
  return r;
}
References auxresume(), lua_concat(), lua_error(), lua_gettop(), lua_insert, lua_isstring(), lua_tothread(), lua_upvalueindex, and luaL_where().
Referenced by luaB_cowrap().
luaB_cocreate()
static int luaB_cocreate (lua_State * L) static
Definition at line 82 of file lua-5.2.4/src/lcorolib.c.
{
  lua_State *NL;
  luaL_checktype(L, 1, LUA_TFUNCTION);
  NL = lua_newthread(L);
  lua_pushvalue(L, 1);  /* move function to top */
  lua_xmove(L, NL, 1);  /* move function from L to NL */
  return 1;
}
References lua_newthread(), lua_pushvalue(), LUA_TFUNCTION, lua_xmove(), and luaL_checktype().
Referenced by luaB_cowrap().
luaB_coresume()
static int luaB_coresume (lua_State * L) static
Definition at line 49 of file lua-5.2.4/src/lcorolib.c.
{
  lua_State *co = lua_tothread(L, 1);
  int r;
  luaL_argcheck(L, co, 1, "coroutine expected");
  r = auxresume(L, co, lua_gettop(L) - 1);
  if (r < 0) {
    lua_pushboolean(L, 0);
    lua_insert(L, -2);
    return 2;  /* return false + error message */
  }
  else {
    lua_pushboolean(L, 1);
    lua_insert(L, -(r + 1));
    return r + 1;  /* return true + `resume' returns */
  }
}
References auxresume(), lua_gettop(), lua_insert, lua_pushboolean(), lua_tothread(), and luaL_argcheck.
luaB_corunning()
static int luaB_corunning (lua_State * L) static
Definition at line 132 of file lua-5.2.4/src/lcorolib.c.
{
  int ismain = lua_pushthread(L);
  lua_pushboolean(L, ismain);
  return 2;
}
References lua_pushboolean(), and lua_pushthread().
luaB_costatus()
static int luaB_costatus (lua_State * L) static
Definition at line 104 of file lua-5.2.4/src/lcorolib.c.
{
  lua_State *co = lua_tothread(L, 1);
  luaL_argcheck(L, co, 1, "coroutine expected");
  if (L == co) lua_pushliteral(L, "running");
  else {
    switch (lua_status(co)) {
      case LUA_YIELD:
        lua_pushliteral(L, "suspended");
        break;
      case LUA_OK: {
        lua_Debug ar;
        if (lua_getstack(co, 0, &ar) > 0)  /* does it have frames? */
          lua_pushliteral(L, "normal");  /* it is running */
        else if (lua_gettop(co) == 0)
            lua_pushliteral(L, "dead");
        else
          lua_pushliteral(L, "suspended");  /* initial state */
        break;
      }
      default:  /* some error occurred */
        lua_pushliteral(L, "dead");
        break;
    }
  }
  return 1;
}
References lua_getstack(), lua_gettop(), LUA_OK, lua_pushliteral, lua_status(), lua_tothread(), LUA_YIELD, and luaL_argcheck.
luaB_cowrap()
static int luaB_cowrap (lua_State * L) static
Definition at line 92 of file lua-5.2.4/src/lcorolib.c.
{
  luaB_cocreate(L);
  lua_pushcclosure(L, luaB_auxwrap, 1);
  return 1;
}
References lua_pushcclosure(), luaB_auxwrap(), and luaB_cocreate().
luaB_yield()
static int luaB_yield (lua_State * L) static
Definition at line 99 of file lua-5.2.4/src/lcorolib.c.
{
  return lua_yield(L, lua_gettop(L));
}
References lua_gettop(), and lua_yield.
luaopen_coroutine()
LUAMOD_API int luaopen_coroutine (lua_State * L)
Definition at line 151 of file lua-5.2.4/src/lcorolib.c.
{
  luaL_newlib(L, co_funcs);
  return 1;
}
References co_funcs, and luaL_newlib.
Variable Documentation
co_funcs
const luaL_Reg co_funcs[] static
Initial value:
= {
  {"create", luaB_cocreate},
  {"resume", luaB_coresume},
  {"running", luaB_corunning},
  {"status", luaB_costatus},
  {"wrap", luaB_cowrap},
  {"yield", luaB_yield},
  {NULL, NULL}
}
Definition at line 139 of file lua-5.2.4/src/lcorolib.c.
{
  {"create", luaB_cocreate},
  {"resume", luaB_coresume},
  {"running", luaB_corunning},
  {"status", luaB_costatus},
  {"wrap", luaB_cowrap},
  {"yield", luaB_yield},
  {NULL, NULL}
};
Referenced by luaopen_coroutine().