Github User Fetcher: lstring.c File Reference
lstring.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
Macros
#define lstring_c
#define LUA_CORE
#define MAXSTRTB cast_int(luaM_limitN(MAX_INT, TString*))
Functions
int luaS_eqlngstr (TString *a, TString *b)
unsigned int luaS_hash (const char *str, size_t l, unsigned int seed)
unsigned int luaS_hashlongstr (TString *ts)
static void tablerehash (TString **vect, int osize, int nsize)
void luaS_resize (lua_State *L, int nsize)
void luaS_clearcache (global_State *g)
void luaS_init (lua_State *L)
static TString * createstrobj (lua_State *L, size_t l, int tag, unsigned int h)
TString * luaS_createlngstrobj (lua_State *L, size_t l)
void luaS_remove (lua_State *L, TString *ts)
static void growstrtab (lua_State *L, stringtable *tb)
static TString * internshrstr (lua_State *L, const char *str, size_t l)
TString * luaS_newlstr (lua_State *L, const char *str, size_t l)
TString * luaS_new (lua_State *L, const char *str)
Udata * luaS_newudata (lua_State *L, size_t s, int nuvalue)
Macro Definition Documentation
lstring_c
#define lstring_c
Definition at line 7 of file lua-5.4.3/src/lstring.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/lstring.c.
MAXSTRTB
#define MAXSTRTB cast_int(luaM_limitN(MAX_INT, TString*))
Definition at line 28 of file lua-5.4.3/src/lstring.c.
Referenced by growstrtab().
Function Documentation
createstrobj()
static TString * createstrobj (lua_State * L, size_t l, int tag, unsigned int h) static
Definition at line 143 of file lua-5.4.3/src/lstring.c.
{
  TString *ts;
  GCObject *o;
  size_t totalsize;  /* total size of TString object */
  totalsize = sizelstring(l);
  o = luaC_newobj(L, tag, totalsize);
  ts = gco2ts(o);
  ts->hash = h;
  ts->extra = 0;
  getstr(ts)[l] = '\0';  /* ending 0 */
  return ts;
}
References TString::extra, gco2ts, getstr, TString::hash, luaC_newobj(), and sizelstring.
Referenced by internshrstr(), and luaS_createlngstrobj().
growstrtab()
static void growstrtab (lua_State * L, stringtable * tb) static
Definition at line 174 of file lua-5.4.3/src/lstring.c.
{
  if (l_unlikely(tb->nuse == MAX_INT)) {  /* too many strings? */
    luaC_fullgc(L, 1);  /* try to free some... */
    if (tb->nuse == MAX_INT)  /* still too many? */
      luaM_error(L);  /* cannot even create a message... */
  }
  if (tb->size <= MAXSTRTB / 2)  /* can grow string table? */
    luaS_resize(L, tb->size * 2);
}
References luaC_fullgc(), luaM_error, luaS_resize(), MAX_INT, MAXSTRTB, stringtable::nuse, and stringtable::size.
Referenced by internshrstr().
internshrstr()
static TString * internshrstr (lua_State * L, const char * str, size_t l) static
Definition at line 188 of file lua-5.4.3/src/lstring.c.
{
  TString *ts;
  global_State *g = G(L);
  stringtable *tb = &g->strt;
  unsigned int h = luaS_hash(str, l, g->seed);
  TString **list = &tb->hash[lmod(h, tb->size)];
  lua_assert(str != NULL);  /* otherwise 'memcmp'/'memcpy' are undefined */
  for (ts = *list; ts != NULL; ts = ts->u.hnext) {
    if (l == ts->shrlen && (memcmp(str, getstr(ts), l * sizeof(char)) == 0)) {
      /* found! */
      if (isdead(g, ts))  /* dead (but not collected yet)? */
        changewhite(ts);  /* resurrect it */
      return ts;
    }
  }
  /* else must create a new string */
  if (tb->nuse >= tb->size) {  /* need to grow string table? */
    growstrtab(L, tb);
    list = &tb->hash[lmod(h, tb->size)];  /* rehash with new size */
  }
  ts = createstrobj(L, l, LUA_VSHRSTR, h);
  memcpy(getstr(ts), str, l * sizeof(char));
  ts->shrlen = cast_byte(l);
  ts->u.hnext = *list;
  *list = ts;
  tb->nuse++;
  return ts;
}
References cast_byte, changewhite, createstrobj(), G, getstr, growstrtab(), stringtable::hash, TString::hnext, isdead, lmod, lua_assert, LUA_VSHRSTR, luaS_hash(), NULL, stringtable::nuse, global_State::seed, TString::shrlen, stringtable::size, global_State::strt, and TString::u.
Referenced by luaS_newlstr().
luaS_clearcache()
void luaS_clearcache (global_State * g)
Definition at line 110 of file lua-5.4.3/src/lstring.c.
{
  int i, j;
  for (i = 0; i < STRCACHE_N; i++)
    for (j = 0; j < STRCACHE_M; j++) {
      if (iswhite(g->strcache[i][j]))  /* will entry be collected? */
        g->strcache[i][j] = g->memerrmsg;  /* replace it with something fixed */
    }
}
References iswhite, global_State::memerrmsg, global_State::strcache, STRCACHE_M, and STRCACHE_N.
luaS_createlngstrobj()
TString * luaS_createlngstrobj (lua_State * L, size_t l)
Definition at line 157 of file lua-5.4.3/src/lstring.c.
{
  TString *ts = createstrobj(L, l, LUA_VLNGSTR, G(L)->seed);
  ts->u.lnglen = l;
  return ts;
}
References createstrobj(), G, TString::lnglen, LUA_VLNGSTR, and TString::u.
Referenced by luaS_newlstr().
luaS_eqlngstr()
int luaS_eqlngstr (TString * a, TString * b)
Definition at line 34 of file lua-5.4.3/src/lstring.c.
{
  size_t len = a->u.lnglen;
  lua_assert(a->tt == LUA_VLNGSTR && b->tt == LUA_VLNGSTR);
  return (a == b) ||  /* same instance or... */
    ((len == b->u.lnglen) &&  /* equal length and ... */
     (memcmp(getstr(a), getstr(b), len) == 0));  /* equal contents */
}
References getstr, TString::lnglen, lua_assert, LUA_VLNGSTR, and TString::u.
luaS_hash()
unsigned int luaS_hash (const char * str, size_t l, unsigned int seed)
Definition at line 43 of file lua-5.4.3/src/lstring.c.
{
  unsigned int h = seed ^ cast_uint(l);
  for (; l > 0; l--)
    h ^= ((h<<5) + (h>>2) + cast_byte(str[l - 1]));
  return h;
}
References cast_byte, and cast_uint.
Referenced by internshrstr(), and luaS_hashlongstr().
luaS_hashlongstr()
unsigned int luaS_hashlongstr (TString * ts)
Definition at line 51 of file lua-5.4.3/src/lstring.c.
{
  lua_assert(ts->tt == LUA_VLNGSTR);
  if (ts->extra == 0) {  /* no hash? */
    size_t len = ts->u.lnglen;
    ts->hash = luaS_hash(getstr(ts), len, ts->hash);
    ts->extra = 1;  /* now it has its hash */
  }
  return ts->hash;
}
References TString::extra, getstr, TString::hash, TString::lnglen, lua_assert, LUA_VLNGSTR, luaS_hash(), and TString::u.
luaS_init()
void luaS_init (lua_State * L)
Definition at line 123 of file lua-5.4.3/src/lstring.c.
{
  global_State *g = G(L);
  int i, j;
  stringtable *tb = &G(L)->strt;
  tb->hash = luaM_newvector(L, MINSTRTABSIZE, TString*);
  tablerehash(tb->hash, 0, MINSTRTABSIZE);  /* clear array */
  tb->size = MINSTRTABSIZE;
  /* pre-create memory-error message */
  g->memerrmsg = luaS_newliteral(L, MEMERRMSG);
  luaC_fix(L, obj2gco(g->memerrmsg));  /* it should never be collected */
  for (i = 0; i < STRCACHE_N; i++)  /* fill cache with valid strings */
    for (j = 0; j < STRCACHE_M; j++)
      g->strcache[i][j] = g->memerrmsg;
}
References G, stringtable::hash, luaC_fix(), luaM_newvector, luaS_newliteral, MEMERRMSG, global_State::memerrmsg, MINSTRTABSIZE, obj2gco, stringtable::size, global_State::strcache, STRCACHE_M, STRCACHE_N, and tablerehash().
luaS_new()
TString * luaS_new (lua_State * L, const char * str)
Definition at line 241 of file lua-5.4.3/src/lstring.c.
{
  unsigned int i = point2uint(str) % STRCACHE_N;  /* hash */
  int j;
  TString **p = G(L)->strcache[i];
  for (j = 0; j < STRCACHE_M; j++) {
    if (strcmp(str, getstr(p[j])) == 0)  /* hit? */
      return p[j];  /* that is it */
  }
  /* normal route */
  for (j = STRCACHE_M - 1; j > 0; j--)
    p[j] = p[j - 1];  /* move out last element */
  /* new element is first in the list */
  p[0] = luaS_newlstr(L, str, strlen(str));
  return p[0];
}
References G, getstr, luaS_newlstr(), point2uint, STRCACHE_M, and STRCACHE_N.
luaS_newlstr()
TString * luaS_newlstr (lua_State * L, const char * str, size_t l)
Definition at line 221 of file lua-5.4.3/src/lstring.c.
{
  if (l <= LUAI_MAXSHORTLEN)  /* short string? */
    return internshrstr(L, str, l);
  else {
    TString *ts;
    if (l_unlikely(l >= (MAX_SIZE - sizeof(TString))/sizeof(char)))
      luaM_toobig(L);
    ts = luaS_createlngstrobj(L, l);
    memcpy(getstr(ts), str, l * sizeof(char));
    return ts;
  }
}
References getstr, internshrstr(), LUAI_MAXSHORTLEN, luaM_toobig(), luaS_createlngstrobj(), and MAX_SIZE.
Referenced by luaS_new().
luaS_newudata()
Udata * luaS_newudata (lua_State * L, size_t s, int nuvalue)
Definition at line 258 of file lua-5.4.3/src/lstring.c.
{
  Udata *u;
  int i;
  GCObject *o;
  if (l_unlikely(s > MAX_SIZE - udatamemoffset(nuvalue)))
    luaM_toobig(L);
  o = luaC_newobj(L, LUA_VUSERDATA, sizeudata(nuvalue, s));
  u = gco2u(o);
  u->len = s;
  u->nuvalue = nuvalue;
  u->metatable = NULL;
  for (i = 0; i < nuvalue; i++)
    setnilvalue(&u->uv[i].uv);
  return u;
}
References gco2u, Udata::len, LUA_VUSERDATA, luaC_newobj(), luaM_toobig(), MAX_SIZE, Udata::metatable, NULL, Udata::nuvalue, s, setnilvalue, sizeudata, udatamemoffset, and Udata::uv.
luaS_remove()
void luaS_remove (lua_State * L, TString * ts)
Definition at line 164 of file lua-5.4.3/src/lstring.c.
{
  stringtable *tb = &G(L)->strt;
  TString **p = &tb->hash[lmod(ts->hash, tb->size)];
  while (*p != ts)  /* find previous element */
    p = &(*p)->u.hnext;
  *p = (*p)->u.hnext;  /* remove element from its list */
  tb->nuse--;
}
References G, TString::hash, stringtable::hash, TString::hnext, lmod, stringtable::nuse, stringtable::size, and TString::u.
luaS_resize()
void luaS_resize (lua_State * L, int nsize)
Definition at line 85 of file lua-5.4.3/src/lstring.c.
{
  stringtable *tb = &G(L)->strt;
  int osize = tb->size;
  TString **newvect;
  if (nsize < osize)  /* shrinking table? */
    tablerehash(tb->hash, osize, nsize);  /* depopulate shrinking part */
  newvect = luaM_reallocvector(L, tb->hash, osize, nsize, TString*);
  if (l_unlikely(newvect == NULL)) {  /* reallocation failed? */
    if (nsize < osize)  /* was it shrinking table? */
      tablerehash(tb->hash, nsize, osize);  /* restore to original size */
    /* leave table as it was */
  }
  else {  /* allocation succeeded */
    tb->hash = newvect;
    tb->size = nsize;
    if (nsize > osize)
      tablerehash(newvect, osize, nsize);  /* rehash for new size */
  }
}
References G, stringtable::hash, luaM_reallocvector, NULL, stringtable::size, and tablerehash().
Referenced by growstrtab().
tablerehash()
static void tablerehash (TString ** vect, int osize, int nsize) static
Definition at line 62 of file lua-5.4.3/src/lstring.c.
{
  int i;
  for (i = osize; i < nsize; i++)  /* clear new elements */
    vect[i] = NULL;
  for (i = 0; i < osize; i++) {  /* rehash old part of the array */
    TString *p = vect[i];
    vect[i] = NULL;
    while (p) {  /* for each string in the list */
      TString *hnext = p->u.hnext;  /* save next */
      unsigned int h = lmod(p->hash, nsize);  /* new position */
      p->u.hnext = vect[h];  /* chain it into array */
      vect[h] = p;
      p = hnext;
    }
  }
}
References TString::hash, TString::hnext, lmod, NULL, and TString::u.
Referenced by luaS_init(), and luaS_resize().