Github User Fetcher: llex.c File Reference
llex.c File Reference
#include "lprefix.h"
#include <locale.h>
#include <string.h>
#include "lua.h"
#include "lctype.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "llex.h"
#include "lobject.h"
#include "lparser.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "lzio.h"
Macros
#define llex_c
#define LUA_CORE
#define next(ls) (ls->current = zgetc(ls->z))
#define currIsNewline(ls) (ls->current == '\n' || ls->current == '\r')
#define save_and_next(ls) (save(ls, ls->current), next(ls))
Functions
static l_noret lexerror (LexState *ls, const char *msg, int token)
static void save (LexState *ls, int c)
void luaX_init (lua_State *L)
const char * luaX_token2str (LexState *ls, int token)
static const char * txtToken (LexState *ls, int token)
l_noret luaX_syntaxerror (LexState *ls, const char *msg)
TString * luaX_newstring (LexState *ls, const char *str, size_t l)
static void inclinenumber (LexState *ls)
void luaX_setinput (lua_State *L, LexState *ls, ZIO *z, TString *source, int firstchar)
static int check_next1 (LexState *ls, int c)
static int check_next2 (LexState *ls, const char *set)
static int read_numeral (LexState *ls, SemInfo *seminfo)
static size_t skip_sep (LexState *ls)
static void read_long_string (LexState *ls, SemInfo *seminfo, size_t sep)
static void esccheck (LexState *ls, int c, const char *msg)
static int gethexa (LexState *ls)
static int readhexaesc (LexState *ls)
static unsigned long readutf8esc (LexState *ls)
static void utf8esc (LexState *ls)
static int readdecesc (LexState *ls)
static void read_string (LexState *ls, int del, SemInfo *seminfo)
static int llex (LexState *ls, SemInfo *seminfo)
void luaX_next (LexState *ls)
int luaX_lookahead (LexState *ls)
Variables
static const char *const luaX_tokens []
Macro Definition Documentation
currIsNewline
#define currIsNewline (ls) (ls->current == '\n' || ls->current == '\r')
Definition at line 36 of file lua-5.3.6/src/llex.c.
Referenced by inclinenumber(), llex(), read_long_string(), and read_string().
llex_c
#define llex_c
Definition at line 7 of file lua-5.3.6/src/llex.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/llex.c.
next
#define next (ls) (ls->current = zgetc(ls->z))
Definition at line 32 of file lua-5.3.6/src/llex.c.
Referenced by check_next1(), inclinenumber(), llex(), read_long_string(), read_string(), and readutf8esc().
save_and_next
#define save_and_next (ls) (save(ls, ls->current), next(ls))
Definition at line 51 of file lua-5.3.6/src/llex.c.
Referenced by check_next2(), esccheck(), gethexa(), llex(), read_long_string(), read_numeral(), read_string(), readdecesc(), readutf8esc(), and skip_sep().
Function Documentation
check_next1()
static int check_next1 (LexState * ls, int c) static
Definition at line 186 of file lua-5.3.6/src/llex.c.
{
  if (ls->current == c) {
    next(ls);
    return 1;
  }
  else return 0;
}
References LexState::current, and next.
Referenced by llex().
check_next2()
static int check_next2 (LexState * ls, const char * set) static
Definition at line 199 of file lua-5.3.6/src/llex.c.
{
  lua_assert(set[2] == '\0');
  if (ls->current == set[0] || ls->current == set[1]) {
    save_and_next(ls);
    return 1;
  }
  else return 0;
}
References LexState::current, lua_assert, and save_and_next.
Referenced by read_numeral().
esccheck()
static void esccheck (LexState * ls, int c, const char * msg) static
Definition at line 306 of file lua-5.3.6/src/llex.c.
{
  if (!c) {
    if (ls->current != EOZ)
      save_and_next(ls);  /* add current to buffer for error message */
    lexerror(ls, msg, TK_STRING);
  }
}
References LexState::current, EOZ, lexerror(), save_and_next, and TK_STRING.
Referenced by gethexa(), read_string(), readdecesc(), and readutf8esc().
gethexa()
static int gethexa (LexState * ls) static
Definition at line 315 of file lua-5.3.6/src/llex.c.
{
  save_and_next(ls);
  esccheck (ls, lisxdigit(ls->current), "hexadecimal digit expected");
  return luaO_hexavalue(ls->current);
}
References LexState::current, esccheck(), lisxdigit, luaO_hexavalue(), and save_and_next.
Referenced by readhexaesc(), and readutf8esc().
inclinenumber()
static void inclinenumber (LexState * ls) static
Definition at line 151 of file lua-5.3.6/src/llex.c.
{
  int old = ls->current;
  lua_assert(currIsNewline(ls));
  next(ls);  /* skip '\n' or '\r' */
  if (currIsNewline(ls) && ls->current != old)
    next(ls);  /* skip '\n\r' or '\r\n' */
  if (++ls->linenumber >= MAX_INT)
    lexerror(ls, "chunk has too many lines", 0);
}
References LexState::current, currIsNewline, lexerror(), LexState::linenumber, lua_assert, MAX_INT, and next.
Referenced by llex(), read_long_string(), and read_string().
lexerror()
static l_noret lexerror (LexState * ls, const char * msg, int token) static
Definition at line 109 of file lua-5.3.6/src/llex.c.
{
  msg = luaG_addinfo(ls->L, msg, ls->source, ls->linenumber);
  if (token)
    luaO_pushfstring(ls->L, "%s near %s", msg, txtToken(ls, token));
  luaD_throw(ls->L, LUA_ERRSYNTAX);
}
References LexState::L, LexState::linenumber, LUA_ERRSYNTAX, luaD_throw(), luaG_addinfo(), luaO_pushfstring(), LexState::source, and txtToken().
Referenced by esccheck(), inclinenumber(), llex(), luaX_syntaxerror(), read_long_string(), read_numeral(), read_string(), and save().
llex()
static int llex (LexState * ls, SemInfo * seminfo) static
Definition at line 432 of file lua-5.3.6/src/llex.c.
{
  luaZ_resetbuffer(ls->buff);
  for (;;) {
    switch (ls->current) {
      case '\n': case '\r': {  /* line breaks */
        inclinenumber(ls);
        break;
      }
      case ' ': case '\f': case '\t': case '\v': {  /* spaces */
        next(ls);
        break;
      }
      case '-': {  /* '-' or '--' (comment) */
        next(ls);
        if (ls->current != '-') return '-';
        /* else is a comment */
        next(ls);
        if (ls->current == '[') {  /* long comment? */
          size_t sep = skip_sep(ls);
          luaZ_resetbuffer(ls->buff);  /* 'skip_sep' may dirty the buffer */
          if (sep >= 2) {
            read_long_string(ls, NULL, sep);  /* skip long comment */
            luaZ_resetbuffer(ls->buff);  /* previous call may dirty the buff. */
            break;
          }
        }
        /* else short comment */
        while (!currIsNewline(ls) && ls->current != EOZ)
          next(ls);  /* skip until end of line (or end of file) */
        break;
      }
      case '[': {  /* long string or simply '[' */
        size_t sep = skip_sep(ls);
        if (sep >= 2) {
          read_long_string(ls, seminfo, sep);
          return TK_STRING;
        }
        else if (sep == 0)  /* '[=...' missing second bracket */
          lexerror(ls, "invalid long string delimiter", TK_STRING);
        return '[';
      }
      case '=': {
        next(ls);
        if (check_next1(ls, '=')) return TK_EQ;
        else return '=';
      }
      case '<': {
        next(ls);
        if (check_next1(ls, '=')) return TK_LE;
        else if (check_next1(ls, '<')) return TK_SHL;
        else return '<';
      }
      case '>': {
        next(ls);
        if (check_next1(ls, '=')) return TK_GE;
        else if (check_next1(ls, '>')) return TK_SHR;
        else return '>';
      }
      case '/': {
        next(ls);
        if (check_next1(ls, '/')) return TK_IDIV;
        else return '/';
      }
      case '~': {
        next(ls);
        if (check_next1(ls, '=')) return TK_NE;
        else return '~';
      }
      case ':': {
        next(ls);
        if (check_next1(ls, ':')) return TK_DBCOLON;
        else return ':';
      }
      case '"': case '\'': {  /* short literal strings */
        read_string(ls, ls->current, seminfo);
        return TK_STRING;
      }
      case '.': {  /* '.', '..', '...', or number */
        save_and_next(ls);
        if (check_next1(ls, '.')) {
          if (check_next1(ls, '.'))
            return TK_DOTS;   /* '...' */
          else return TK_CONCAT;   /* '..' */
        }
        else if (!lisdigit(ls->current)) return '.';
        else return read_numeral(ls, seminfo);
      }
      case '0': case '1': case '2': case '3': case '4':
      case '5': case '6': case '7': case '8': case '9': {
        return read_numeral(ls, seminfo);
      }
      case EOZ: {
        return TK_EOS;
      }
      default: {
        if (lislalpha(ls->current)) {  /* identifier or reserved word? */
          TString *ts;
          do {
            save_and_next(ls);
          } while (lislalnum(ls->current));
          ts = luaX_newstring(ls, luaZ_buffer(ls->buff),
                                  luaZ_bufflen(ls->buff));
          seminfo->ts = ts;
          if (isreserved(ts))  /* reserved word? */
            return ts->extra - 1 + FIRST_RESERVED;
          else {
            return TK_NAME;
          }
        }
        else {  /* single-char tokens (+ - / ...) */
          int c = ls->current;
          next(ls);
          return c;
        }
      }
    }
  }
}
References LexState::buff, check_next1(), LexState::current, currIsNewline, EOZ, TString::extra, FIRST_RESERVED, inclinenumber(), isreserved, lexerror(), lisdigit, lislalnum, lislalpha, luaX_newstring(), luaZ_buffer, luaZ_bufflen, luaZ_resetbuffer, next, NULL, read_long_string(), read_numeral(), read_string(), save_and_next, skip_sep(), TK_CONCAT, TK_DBCOLON, TK_DOTS, TK_EOS, TK_EQ, TK_GE, TK_IDIV, TK_LE, TK_NAME, TK_NE, TK_SHL, TK_SHR, TK_STRING, and SemInfo::ts.
Referenced by luaX_lookahead(), and luaX_next().
luaX_init()
void luaX_init (lua_State * L)
Definition at line 70 of file lua-5.3.6/src/llex.c.
{
  int i;
  TString *e = luaS_newliteral(L, LUA_ENV);  /* create env name */
  luaC_fix(L, obj2gco(e));  /* never collect this name */
  for (i=0; i<NUM_RESERVED; i++) {
    TString *ts = luaS_new(L, luaX_tokens[i]);
    luaC_fix(L, obj2gco(ts));  /* reserved words are never collected */
    ts->extra = cast_byte(i+1);  /* reserved word */
  }
}
References cast_byte, TString::extra, LUA_ENV, luaC_fix(), luaS_new, luaS_newliteral, luaX_tokens, NUM_RESERVED, and obj2gco.
luaX_lookahead()
int luaX_lookahead (LexState * ls)
Definition at line 563 of file lua-5.3.6/src/llex.c.
{
  lua_assert(ls->lookahead.token == TK_EOS);
  ls->lookahead.token = llex(ls, &ls->lookahead.seminfo);
  return ls->lookahead.token;
}
References llex(), LexState::lookahead, lua_assert, Token::seminfo, TK_EOS, and Token::token.
luaX_newstring()
TString * luaX_newstring (LexState * ls, const char * str, size_t l)
Definition at line 127 of file lua-5.3.6/src/llex.c.
{
  lua_State *L = ls->L;
  TValue *o;  /* entry for 'str' */
  TString *ts = luaS_newlstr(L, str, l);  /* create new string */
  setsvalue2s(L, L->top++, ts);  /* temporarily anchor it in stack */
  o = luaH_set(L, ls->h, L->top - 1);
  if (ttisnil(o)) {  /* not in use yet? */
    /* boolean value does not need GC barrier;
       table has no metatable, so it does not need to invalidate cache */
    setbvalue(o, 1);  /* t[string] = true */
    luaC_checkGC(L);
  }
  else {  /* string already present */
    ts = tsvalue(keyfromval(o));  /* re-use value previously stored */
  }
  L->top--;  /* remove string from stack */
  return ts;
}
References LexState::h, keyfromval, LexState::L, luaC_checkGC, luaH_set(), luaS_newlstr(), setbvalue, setsvalue2s, lua_State::top, tsvalue, and ttisnil.
Referenced by llex(), read_long_string(), and read_string().
luaX_next()
void luaX_next (LexState * ls)
Definition at line 552 of file lua-5.3.6/src/llex.c.
{
  ls->lastline = ls->linenumber;
  if (ls->lookahead.token != TK_EOS) {  /* is there a look-ahead token? */
    ls->t = ls->lookahead;  /* use this one */
    ls->lookahead.token = TK_EOS;  /* and discharge it */
  }
  else
    ls->t.token = llex(ls, &ls->t.seminfo);  /* read next token */
}
References LexState::lastline, LexState::linenumber, llex(), LexState::lookahead, Token::seminfo, LexState::t, TK_EOS, and Token::token.
luaX_setinput()
void luaX_setinput (lua_State * L, LexState * ls, ZIO * z, TString * source, int firstchar)
Definition at line 162 of file lua-5.3.6/src/llex.c.
{
  ls->t.token = 0;
  ls->L = L;
  ls->current = firstchar;
  ls->lookahead.token = TK_EOS;  /* no look-ahead token */
  ls->z = z;
  ls->fs = NULL;
  ls->linenumber = 1;
  ls->lastline = 1;
  ls->source = source;
  ls->envn = luaS_newliteral(L, LUA_ENV);  /* get env name */
  luaZ_resizebuffer(ls->L, ls->buff, LUA_MINBUFFER);  /* initialize buffer */
}
References LexState::buff, LexState::current, LexState::envn, LexState::fs, LexState::L, LexState::lastline, LexState::linenumber, LexState::lookahead, LUA_ENV, LUA_MINBUFFER, luaS_newliteral, luaZ_resizebuffer, NULL, LexState::source, LexState::t, TK_EOS, Token::token, and LexState::z.
luaX_syntaxerror()
l_noret luaX_syntaxerror (LexState * ls, const char * msg)
Definition at line 117 of file lua-5.3.6/src/llex.c.
{
  lexerror(ls, msg, ls->t.token);
}
References lexerror(), LexState::t, and Token::token.
luaX_token2str()
const char * luaX_token2str (LexState * ls, int token)
Definition at line 82 of file lua-5.3.6/src/llex.c.
{
  if (token < FIRST_RESERVED) {  /* single-byte symbols? */
    lua_assert(token == cast_uchar(token));
    return luaO_pushfstring(ls->L, "'%c'", token);
  }
  else {
    const char *s = luaX_tokens[token - FIRST_RESERVED];
    if (token < TK_EOS)  /* fixed format (symbols and reserved words)? */
      return luaO_pushfstring(ls->L, "'%s'", s);
    else  /* names, strings, and numerals */
      return s;
  }
}
References cast_uchar, FIRST_RESERVED, LexState::L, lua_assert, luaO_pushfstring(), luaX_tokens, s, and TK_EOS.
Referenced by txtToken().
read_long_string()
static void read_long_string (LexState * ls, SemInfo * seminfo, size_t sep) static
Definition at line 267 of file lua-5.3.6/src/llex.c.
{
  int line = ls->linenumber;  /* initial line (for error message) */
  save_and_next(ls);  /* skip 2nd '[' */
  if (currIsNewline(ls))  /* string starts with a newline? */
    inclinenumber(ls);  /* skip it */
  for (;;) {
    switch (ls->current) {
      case EOZ: {  /* error */
        const char *what = (seminfo ? "string" : "comment");
        const char *msg = luaO_pushfstring(ls->L,
                     "unfinished long %s (starting at line %d)", what, line);
        lexerror(ls, msg, TK_EOS);
        break;  /* to avoid warnings */
      }
      case ']': {
        if (skip_sep(ls) == sep) {
          save_and_next(ls);  /* skip 2nd ']' */
          goto endloop;
        }
        break;
      }
      case '\n': case '\r': {
        save(ls, '\n');
        inclinenumber(ls);
        if (!seminfo) luaZ_resetbuffer(ls->buff);  /* avoid wasting space */
        break;
      }
      default: {
        if (seminfo) save_and_next(ls);
        else next(ls);
      }
    }
  } endloop:
  if (seminfo)
    seminfo->ts = luaX_newstring(ls, luaZ_buffer(ls->buff) + sep,
                                     luaZ_bufflen(ls->buff) - 2 * sep);
}
References LexState::buff, LexState::current, currIsNewline, EOZ, inclinenumber(), LexState::L, lexerror(), LexState::linenumber, luaO_pushfstring(), luaX_newstring(), luaZ_buffer, luaZ_bufflen, luaZ_resetbuffer, next, save(), save_and_next, skip_sep(), TK_EOS, and SemInfo::ts.
Referenced by llex().
read_numeral()
static int read_numeral (LexState * ls, SemInfo * seminfo) static
Definition at line 214 of file lua-5.3.6/src/llex.c.
{
  TValue obj;
  const char *expo = "Ee";
  int first = ls->current;
  lua_assert(lisdigit(ls->current));
  save_and_next(ls);
  if (first == '0' && check_next2(ls, "xX"))  /* hexadecimal? */
    expo = "Pp";
  for (;;) {
    if (check_next2(ls, expo))  /* exponent part? */
      check_next2(ls, "-+");  /* optional exponent sign */
    if (lisxdigit(ls->current))
      save_and_next(ls);
    else if (ls->current == '.')
      save_and_next(ls);
    else break;
  }
  save(ls, '\0');
  if (luaO_str2num(luaZ_buffer(ls->buff), &obj) == 0)  /* format error? */
    lexerror(ls, "malformed number", TK_FLT);
  if (ttisinteger(&obj)) {
    seminfo->i = ivalue(&obj);
    return TK_INT;
  }
  else {
    lua_assert(ttisfloat(&obj));
    seminfo->r = fltvalue(&obj);
    return TK_FLT;
  }
}
References LexState::buff, check_next2(), LexState::current, fltvalue, SemInfo::i, ivalue, lexerror(), lisdigit, lisxdigit, lua_assert, luaO_str2num(), luaZ_buffer, SemInfo::r, save(), save_and_next, TK_FLT, TK_INT, ttisfloat, and ttisinteger.
Referenced by llex().
read_string()
static void read_string (LexState * ls, int del, SemInfo * seminfo) static
Definition at line 369 of file lua-5.3.6/src/llex.c.
{
  save_and_next(ls);  /* keep delimiter (for error messages) */
  while (ls->current != del) {
    switch (ls->current) {
      case EOZ:
        lexerror(ls, "unfinished string", TK_EOS);
        break;  /* to avoid warnings */
      case '\n':
      case '\r':
        lexerror(ls, "unfinished string", TK_STRING);
        break;  /* to avoid warnings */
      case '\\': {  /* escape sequences */
        int c;  /* final character to be saved */
        save_and_next(ls);  /* keep '\\' for error messages */
        switch (ls->current) {
          case 'a': c = '\a'; goto read_save;
          case 'b': c = '\b'; goto read_save;
          case 'f': c = '\f'; goto read_save;
          case 'n': c = '\n'; goto read_save;
          case 'r': c = '\r'; goto read_save;
          case 't': c = '\t'; goto read_save;
          case 'v': c = '\v'; goto read_save;
          case 'x': c = readhexaesc(ls); goto read_save;
          case 'u': utf8esc(ls);  goto no_save;
          case '\n': case '\r':
            inclinenumber(ls); c = '\n'; goto only_save;
          case '\\': case '\"': case '\'':
            c = ls->current; goto read_save;
          case EOZ: goto no_save;  /* will raise an error next loop */
          case 'z': {  /* zap following span of spaces */
            luaZ_buffremove(ls->buff, 1);  /* remove '\\' */
            next(ls);  /* skip the 'z' */
            while (lisspace(ls->current)) {
              if (currIsNewline(ls)) inclinenumber(ls);
              else next(ls);
            }
            goto no_save;
          }
          default: {
            esccheck(ls, lisdigit(ls->current), "invalid escape sequence");
            c = readdecesc(ls);  /* digital escape '\ddd' */
            goto only_save;
          }
        }
       read_save:
         next(ls);
         /* go through */
       only_save:
         luaZ_buffremove(ls->buff, 1);  /* remove '\\' */
         save(ls, c);
         /* go through */
       no_save: break;
      }
      default:
        save_and_next(ls);
    }
  }
  save_and_next(ls);  /* skip delimiter */
  seminfo->ts = luaX_newstring(ls, luaZ_buffer(ls->buff) + 1,
                                   luaZ_bufflen(ls->buff) - 2);
}
References LexState::buff, LexState::current, currIsNewline, EOZ, esccheck(), inclinenumber(), lexerror(), lisdigit, lisspace, luaX_newstring(), luaZ_buffer, luaZ_bufflen, luaZ_buffremove, next, readdecesc(), readhexaesc(), save(), save_and_next, TK_EOS, TK_STRING, SemInfo::ts, and utf8esc().
Referenced by llex().
readdecesc()
static int readdecesc (LexState * ls) static
Definition at line 356 of file lua-5.3.6/src/llex.c.
{
  int i;
  int r = 0;  /* result accumulator */
  for (i = 0; i < 3 && lisdigit(ls->current); i++) {  /* read up to 3 digits */
    r = 10*r + ls->current - '0';
    save_and_next(ls);
  }
  esccheck(ls, r <= UCHAR_MAX, "decimal escape too large");
  luaZ_buffremove(ls->buff, i);  /* remove read digits from buffer */
  return r;
}
References LexState::buff, LexState::current, esccheck(), lisdigit, luaZ_buffremove, and save_and_next.
Referenced by read_string().
readhexaesc()
static int readhexaesc (LexState * ls) static
Definition at line 322 of file lua-5.3.6/src/llex.c.
{
  int r = gethexa(ls);
  r = (r << 4) + gethexa(ls);
  luaZ_buffremove(ls->buff, 2);  /* remove saved chars from buffer */
  return r;
}
References LexState::buff, gethexa(), and luaZ_buffremove.
Referenced by read_string().
readutf8esc()
static unsigned long readutf8esc (LexState * ls) static
Definition at line 330 of file lua-5.3.6/src/llex.c.
{
  unsigned long r;
  int i = 4;  /* chars to be removed: '\', 'u', '{', and first digit */
  save_and_next(ls);  /* skip 'u' */
  esccheck(ls, ls->current == '{', "missing '{'");
  r = gethexa(ls);  /* must have at least one digit */
  while ((save_and_next(ls), lisxdigit(ls->current))) {
    i++;
    r = (r << 4) + luaO_hexavalue(ls->current);
    esccheck(ls, r <= 0x10FFFF, "UTF-8 value too large");
  }
  esccheck(ls, ls->current == '}', "missing '}'");
  next(ls);  /* skip '}' */
  luaZ_buffremove(ls->buff, i);  /* remove saved chars from buffer */
  return r;
}
References LexState::buff, LexState::current, esccheck(), gethexa(), lisxdigit, luaO_hexavalue(), luaZ_buffremove, next, and save_and_next.
Referenced by utf8esc().
save()
static void save (LexState * ls, int c) static
Definition at line 57 of file lua-5.3.6/src/llex.c.
{
  Mbuffer *b = ls->buff;
  if (luaZ_bufflen(b) + 1 > luaZ_sizebuffer(b)) {
    size_t newsize;
    if (luaZ_sizebuffer(b) >= MAX_SIZE/2)
      lexerror(ls, "lexical element too long", 0);
    newsize = luaZ_sizebuffer(b) * 2;
    luaZ_resizebuffer(ls->L, b, newsize);
  }
  b->buffer[luaZ_bufflen(b)++] = cast(char, c);
}
References LexState::buff, Mbuffer::buffer, cast, LexState::L, lexerror(), luaZ_bufflen, luaZ_resizebuffer, luaZ_sizebuffer, and MAX_SIZE.
Referenced by read_long_string(), read_numeral(), read_string(), txtToken(), and utf8esc().
skip_sep()
static size_t skip_sep (LexState * ls) static
Definition at line 251 of file lua-5.3.6/src/llex.c.
{
  size_t count = 0;
  int s = ls->current;
  lua_assert(s == '[' || s == ']');
  save_and_next(ls);
  while (ls->current == '=') {
    save_and_next(ls);
    count++;
  }
  return (ls->current == s) ? count + 2
         : (count == 0) ? 1
         : 0;
}
References LexState::current, lua_assert, s, and save_and_next.
Referenced by llex(), and read_long_string().
txtToken()
static const char * txtToken (LexState * ls, int token) static
Definition at line 97 of file lua-5.3.6/src/llex.c.
{
  switch (token) {
    case TK_NAME: case TK_STRING:
    case TK_FLT: case TK_INT:
      save(ls, '\0');
      return luaO_pushfstring(ls->L, "'%s'", luaZ_buffer(ls->buff));
    default:
      return luaX_token2str(ls, token);
  }
}
References LexState::buff, LexState::L, luaO_pushfstring(), luaX_token2str(), luaZ_buffer, save(), TK_FLT, TK_INT, TK_NAME, and TK_STRING.
Referenced by lexerror().
utf8esc()
static void utf8esc (LexState * ls) static
Definition at line 348 of file lua-5.3.6/src/llex.c.
{
  char buff[UTF8BUFFSZ];
  int n = luaO_utf8esc(buff, readutf8esc(ls));
  for (; n > 0; n--)  /* add 'buff' to string */
    save(ls, buff[UTF8BUFFSZ - n]);
}
References luaO_utf8esc(), readutf8esc(), save(), and UTF8BUFFSZ.
Referenced by read_string().
Variable Documentation
luaX_tokens
const char* const luaX_tokens[] static
Initial value:
= {
    "and", "break", "do", "else", "elseif",
    "end", "false", "for", "function", "goto", "if",
    "in", "local", "nil", "not", "or", "repeat",
    "return", "then", "true", "until", "while",
    "//", "..", "...", "==", ">=", "<=", "~=",
    "<<", ">>", "::", "<eof>",
    "<number>", "<integer>", "<name>", "<string>"
}
Definition at line 40 of file lua-5.3.6/src/llex.c.
{
    "and", "break", "do", "else", "elseif",
    "end", "false", "for", "function", "goto", "if",
    "in", "local", "nil", "not", "or", "repeat",
    "return", "then", "true", "until", "while",
    "//", "..", "...", "==", ">=", "<=", "~=",
    "<<", ">>", "::", "<eof>",
    "<number>", "<integer>", "<name>", "<string>"
};
Referenced by luaX_init(), and luaX_token2str().