Github User Fetcher: ltm.c File Reference
ltm.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lvm.h"
Macros
#define ltm_c
#define LUA_CORE
Functions
void luaT_init (lua_State *L)
const TValue * luaT_gettm (Table *events, TMS event, TString *ename)
const TValue * luaT_gettmbyobj (lua_State *L, const TValue *o, TMS event)
const char * luaT_objtypename (lua_State *L, const TValue *o)
void luaT_callTM (lua_State *L, const TValue *f, const TValue *p1, const TValue *p2, const TValue *p3)
void luaT_callTMres (lua_State *L, const TValue *f, const TValue *p1, const TValue *p2, StkId res)
static int callbinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
void luaT_trybinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
void luaT_tryconcatTM (lua_State *L)
void luaT_trybinassocTM (lua_State *L, const TValue *p1, const TValue *p2, int flip, StkId res, TMS event)
void luaT_trybiniTM (lua_State *L, const TValue *p1, lua_Integer i2, int flip, StkId res, TMS event)
int luaT_callorderTM (lua_State *L, const TValue *p1, const TValue *p2, TMS event)
int luaT_callorderiTM (lua_State *L, const TValue *p1, int v2, int flip, int isfloat, TMS event)
void luaT_adjustvarargs (lua_State *L, int nfixparams, CallInfo *ci, const Proto *p)
void luaT_getvarargs (lua_State *L, CallInfo *ci, StkId where, int wanted)
Variables
static const char udatatypename [] = "userdata"
LUAI_DDEF const char *const luaT_typenames_ [LUA_TOTALTYPES]
Macro Definition Documentation
ltm_c
#define ltm_c
Definition at line 7 of file lua-5.4.3/src/ltm.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/ltm.c.
Function Documentation
callbinTM()
static int callbinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event) static
Definition at line 137 of file lua-5.4.3/src/ltm.c.
{
  const TValue *tm = luaT_gettmbyobj(L, p1, event);  /* try first operand */
  if (notm(tm))
    tm = luaT_gettmbyobj(L, p2, event);  /* try second operand */
  if (notm(tm)) return 0;
  luaT_callTMres(L, tm, p1, p2, res);
  return 1;
}
References luaT_callTMres(), luaT_gettmbyobj(), and notm.
Referenced by luaT_callorderTM(), luaT_trybinTM(), and luaT_tryconcatTM().
luaT_adjustvarargs()
void luaT_adjustvarargs (lua_State * L, int nfixparams, CallInfo * ci, const Proto * p)
Definition at line 238 of file lua-5.4.3/src/ltm.c.
{
  int i;
  int actual = cast_int(L->top - ci->func) - 1;  /* number of arguments */
  int nextra = actual - nfixparams;  /* number of extra arguments */
  ci->u.l.nextraargs = nextra;
  luaD_checkstack(L, p->maxstacksize + 1);
  /* copy function to the top of the stack */
  setobjs2s(L, L->top++, ci->func);
  /* move fixed parameters to the top of the stack */
  for (i = 1; i <= nfixparams; i++) {
    setobjs2s(L, L->top++, ci->func + i);
    setnilvalue(s2v(ci->func + i));  /* erase original parameter (for GC) */
  }
  ci->func += actual + 1;
  ci->top += actual + 1;
  lua_assert(L->top <= ci->top && ci->top <= L->stack_last);
}
References cast_int, CallInfo::func, CallInfo::l, lua_assert, luaD_checkstack, Proto::maxstacksize, CallInfo::nextraargs, s2v, setnilvalue, setobjs2s, lua_State::stack_last, CallInfo::top, lua_State::top, and CallInfo::u.
Referenced by luaV_execute().
luaT_callorderiTM()
int luaT_callorderiTM (lua_State * L, const TValue * p1, int v2, int flip, int isfloat, TMS event)
Definition at line 221 of file lua-5.4.3/src/ltm.c.
{
  TValue aux; const TValue *p2;
  if (isfloat) {
    setfltvalue(&aux, cast_num(v2));
  }
  else
    setivalue(&aux, v2);
  if (flip) {  /* arguments were exchanged? */
    p2 = p1; p1 = &aux;  /* correct them */
  }
  else
    p2 = &aux;
  return luaT_callorderTM(L, p1, p2, event);
}
References cast_num, luaT_callorderTM(), setfltvalue, and setivalue.
luaT_callorderTM()
int luaT_callorderTM (lua_State * L, const TValue * p1, const TValue * p2, TMS event)
Definition at line 201 of file lua-5.4.3/src/ltm.c.
{
  if (callbinTM(L, p1, p2, L->top, event))  /* try original event */
    return !l_isfalse(s2v(L->top));
#if defined(LUA_COMPAT_LT_LE)
  else if (event == TM_LE) {
      /* try '!(p2 < p1)' for '(p1 <= p2)' */
      L->ci->callstatus |= CIST_LEQ;  /* mark it is doing 'lt' for 'le' */
      if (callbinTM(L, p2, p1, L->top, TM_LT)) {
        L->ci->callstatus ^= CIST_LEQ;  /* clear mark */
        return l_isfalse(s2v(L->top));
      }
      /* else error will remove this 'ci'; no need to clear mark */
  }
#endif
  luaG_ordererror(L, p1, p2);  /* no metamethod found */
  return 0;  /* to avoid warnings */
}
References callbinTM(), CallInfo::callstatus, lua_State::ci, CIST_LEQ, l_isfalse, luaG_ordererror(), s2v, TM_LE, TM_LT, and lua_State::top.
Referenced by luaT_callorderiTM().
luaT_callTM()
void luaT_callTM (lua_State * L, const TValue * f, const TValue * p1, const TValue * p2, const TValue * p3)
Definition at line 103 of file lua-5.4.3/src/ltm.c.
{
  StkId func = L->top;
  setobj2s(L, func, f);  /* push function (assume EXTRA_STACK) */
  setobj2s(L, func + 1, p1);  /* 1st argument */
  setobj2s(L, func + 2, p2);  /* 2nd argument */
  setobj2s(L, func + 3, p3);  /* 3rd argument */
  L->top = func + 4;
  /* metamethod may yield only when called from Lua code */
  if (isLuacode(L->ci))
    luaD_call(L, func, 0);
  else
    luaD_callnoyield(L, func, 0);
}
References lua_State::ci, isLuacode, luaD_call(), luaD_callnoyield(), setobj2s, and lua_State::top.
luaT_callTMres()
void luaT_callTMres (lua_State * L, const TValue * f, const TValue * p1, const TValue * p2, StkId res)
Definition at line 119 of file lua-5.4.3/src/ltm.c.
{
  ptrdiff_t result = savestack(L, res);
  StkId func = L->top;
  setobj2s(L, func, f);  /* push function (assume EXTRA_STACK) */
  setobj2s(L, func + 1, p1);  /* 1st argument */
  setobj2s(L, func + 2, p2);  /* 2nd argument */
  L->top += 3;
  /* metamethod may yield only when called from Lua code */
  if (isLuacode(L->ci))
    luaD_call(L, func, 1);
  else
    luaD_callnoyield(L, func, 1);
  res = restorestack(L, result);
  setobjs2s(L, res, --L->top);  /* move result to its place */
}
References lua_State::ci, isLuacode, luaD_call(), luaD_callnoyield(), restorestack, savestack, setobj2s, setobjs2s, and lua_State::top.
Referenced by callbinTM(), luaV_equalobj(), luaV_finishget(), and luaV_objlen().
luaT_gettm()
const TValue * luaT_gettm (Table * events, TMS event, TString * ename)
Definition at line 60 of file lua-5.4.3/src/ltm.c.
{
  const TValue *tm = luaH_getshortstr(events, ename);
  lua_assert(event <= TM_EQ);
  if (notm(tm)) {  /* no tag method? */
    events->flags |= cast_byte(1u<<event);  /* cache this fact */
    return NULL;
  }
  else return tm;
}
References cast_byte, Table::flags, lua_assert, luaH_getshortstr(), notm, NULL, and TM_EQ.
luaT_gettmbyobj()
const TValue * luaT_gettmbyobj (lua_State * L, const TValue * o, TMS event)
Definition at line 71 of file lua-5.4.3/src/ltm.c.
{
  Table *mt;
  switch (ttype(o)) {
    case LUA_TTABLE:
      mt = hvalue(o)->metatable;
      break;
    case LUA_TUSERDATA:
      mt = uvalue(o)->metatable;
      break;
    default:
      mt = G(L)->mt[ttype(o)];
  }
  return (mt ? luaH_getshortstr(mt, G(L)->tmname[event]) : &G(L)->nilvalue);
}
References G, hvalue, LUA_TTABLE, LUA_TUSERDATA, luaH_getshortstr(), Table::metatable, tmname, ttype, and uvalue.
Referenced by callbinTM().
luaT_getvarargs()
void luaT_getvarargs (lua_State * L, CallInfo * ci, StkId where, int wanted)
Definition at line 258 of file lua-5.4.3/src/ltm.c.
{
  int i;
  int nextra = ci->u.l.nextraargs;
  if (wanted < 0) {
    wanted = nextra;  /* get all extra arguments available */
    checkstackGCp(L, nextra, where);  /* ensure stack space */
    L->top = where + nextra;  /* next instruction will need top */
  }
  for (i = 0; i < wanted && i < nextra; i++)
    setobjs2s(L, where + i, ci->func - nextra + i);
  for (; i < wanted; i++)   /* complete required results with nil */
    setnilvalue(s2v(where + i));
}
References checkstackGCp, CallInfo::func, CallInfo::l, CallInfo::nextraargs, s2v, setnilvalue, setobjs2s, lua_State::top, and CallInfo::u.
Referenced by luaV_execute().
luaT_init()
void luaT_init (lua_State * L)
Definition at line 38 of file lua-5.4.3/src/ltm.c.
{
  static const char *const luaT_eventname[] = {  /* ORDER TM */
    "__index", "__newindex",
    "__gc", "__mode", "__len", "__eq",
    "__add", "__sub", "__mul", "__mod", "__pow",
    "__div", "__idiv",
    "__band", "__bor", "__bxor", "__shl", "__shr",
    "__unm", "__bnot", "__lt", "__le",
    "__concat", "__call", "__close"
  };
  int i;
  for (i=0; i<TM_N; i++) {
    G(L)->tmname[i] = luaS_new(L, luaT_eventname[i]);
    luaC_fix(L, obj2gco(G(L)->tmname[i]));  /* never collect these names */
  }
}
References G, luaC_fix(), luaS_new, obj2gco, TM_N, and tmname.
luaT_objtypename()
const char * luaT_objtypename (lua_State * L, const TValue * o)
Definition at line 91 of file lua-5.4.3/src/ltm.c.
{
  Table *mt;
  if ((ttistable(o) && (mt = hvalue(o)->metatable) != NULL) ||
      (ttisfulluserdata(o) && (mt = uvalue(o)->metatable) != NULL)) {
    const TValue *name = luaH_getshortstr(mt, luaS_new(L, "__name"));
    if (ttisstring(name))  /* is '__name' a string? */
      return getstr(tsvalue(name));  /* use it as type name */
  }
  return ttypename(ttype(o));  /* else use standard type name */
}
References getstr, hvalue, luaH_getshortstr(), luaS_new, name, NULL, tsvalue, ttisfulluserdata, ttisstring, ttistable, ttype, ttypename, and uvalue.
luaT_trybinassocTM()
void luaT_trybinassocTM (lua_State * L, const TValue * p1, const TValue * p2, int flip, StkId res, TMS event)
Definition at line 175 of file lua-5.4.3/src/ltm.c.
{
  if (flip)
    luaT_trybinTM(L, p2, p1, res, event);
  else
    luaT_trybinTM(L, p1, p2, res, event);
}
References luaT_trybinTM().
Referenced by luaT_trybiniTM(), and luaV_execute().
luaT_trybiniTM()
void luaT_trybiniTM (lua_State * L, const TValue * p1, lua_Integer i2, int flip, StkId res, TMS event)
Definition at line 184 of file lua-5.4.3/src/ltm.c.
{
  TValue aux;
  setivalue(&aux, i2);
  luaT_trybinassocTM(L, p1, &aux, flip, res, event);
}
References luaT_trybinassocTM(), and setivalue.
Referenced by luaV_execute().
luaT_trybinTM()
void luaT_trybinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 148 of file lua-5.4.3/src/ltm.c.
{
  if (l_unlikely(!callbinTM(L, p1, p2, res, event))) {
    switch (event) {
      case TM_BAND: case TM_BOR: case TM_BXOR:
      case TM_SHL: case TM_SHR: case TM_BNOT: {
        if (ttisnumber(p1) && ttisnumber(p2))
          luaG_tointerror(L, p1, p2);
        else
          luaG_opinterror(L, p1, p2, "perform bitwise operation on");
      }
      /* calls never return, but to avoid warnings: *//* FALLTHROUGH */
      default:
        luaG_opinterror(L, p1, p2, "perform arithmetic on");
    }
  }
}
References callbinTM(), luaG_opinterror(), luaG_tointerror(), TM_BAND, TM_BNOT, TM_BOR, TM_BXOR, TM_SHL, TM_SHR, and ttisnumber.
Referenced by luaT_trybinassocTM().
luaT_tryconcatTM()
void luaT_tryconcatTM (lua_State * L)
Definition at line 167 of file lua-5.4.3/src/ltm.c.
{
  StkId top = L->top;
  if (l_unlikely(!callbinTM(L, s2v(top - 2), s2v(top - 1), top - 2,
                               TM_CONCAT)))
    luaG_concaterror(L, s2v(top - 2), s2v(top - 1));
}
References callbinTM(), luaG_concaterror(), s2v, TM_CONCAT, and lua_State::top.
Referenced by luaV_concat().
Variable Documentation
luaT_typenames_
LUAI_DDEF const char* const luaT_typenames_[LUA_TOTALTYPES]
Initial value:
= {
  "no value",
  "nil", "boolean", udatatypename, "number",
  "string", "table", "function", udatatypename, "thread",
  "upvalue", "proto"
}
Definition at line 30 of file lua-5.4.3/src/ltm.c.
{
  "no value",
  "nil", "boolean", udatatypename, "number",
  "string", "table", "function", udatatypename, "thread",
  "upvalue", "proto" /* these last cases are used for tests only */
};
udatatypename
const char udatatypename[] = "userdata" static
Definition at line 28 of file lua-5.4.3/src/ltm.c.