Github User Fetcher: lundump.c File Reference
lundump.c File Reference
#include "lprefix.h"
#include <limits.h>
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstring.h"
#include "lundump.h"
#include "lzio.h"
Data Structures
struct LoadState
Macros
#define lundump_c
#define LUA_CORE
#define luai_verifycode(L, f) /* empty */
#define loadVector(S, b, n) loadBlock(S,b,(n)*sizeof((b)[0]))
#define loadVar(S, x) loadVector(S,&x,1)
#define checksize(S, t) fchecksize(S,sizeof(t),#t)
Functions
static l_noret error (LoadState *S, const char *why)
static void loadBlock (LoadState *S, void *b, size_t size)
static lu_byte loadByte (LoadState *S)
static size_t loadUnsigned (LoadState *S, size_t limit)
static size_t loadSize (LoadState *S)
static int loadInt (LoadState *S)
static lua_Number loadNumber (LoadState *S)
static lua_Integer loadInteger (LoadState *S)
static TString * loadStringN (LoadState *S, Proto *p)
static TString * loadString (LoadState *S, Proto *p)
static void loadCode (LoadState *S, Proto *f)
static void loadFunction (LoadState *S, Proto *f, TString *psource)
static void loadConstants (LoadState *S, Proto *f)
static void loadProtos (LoadState *S, Proto *f)
static void loadUpvalues (LoadState *S, Proto *f)
static void loadDebug (LoadState *S, Proto *f)
static void checkliteral (LoadState *S, const char *s, const char *msg)
static void fchecksize (LoadState *S, size_t size, const char *tname)
static void checkHeader (LoadState *S)
LClosure * luaU_undump (lua_State *L, ZIO *Z, const char *name)
Macro Definition Documentation
checksize
#define checksize (S, t) fchecksize(S,sizeof(t),#t)
Definition at line 288 of file lua-5.4.3/src/lundump.c.
Referenced by checkHeader().
loadVar
#define loadVar (S, x) loadVector(S,&x,1)
Definition at line 58 of file lua-5.4.3/src/lundump.c.
Referenced by loadInteger(), and loadNumber().
loadVector
#define loadVector (S, b, n) loadBlock(S,b,(n)*sizeof((b)[0]))
Definition at line 50 of file lua-5.4.3/src/lundump.c.
Referenced by checkliteral(), loadCode(), loadDebug(), and loadStringN().
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/lundump.c.
luai_verifycode
#define luai_verifycode (L, f) /* empty */
Definition at line 29 of file lua-5.4.3/src/lundump.c.
Referenced by luaU_undump().
lundump_c
#define lundump_c
Definition at line 7 of file lua-5.4.3/src/lundump.c.
Function Documentation
checkHeader()
static void checkHeader (LoadState * S) static
Definition at line 290 of file lua-5.4.3/src/lundump.c.
{
  /* skip 1st char (already read and checked) */
  checkliteral(S, &LUA_SIGNATURE[1], "not a binary chunk");
  if (loadByte(S) != LUAC_VERSION)
    error(S, "version mismatch");
  if (loadByte(S) != LUAC_FORMAT)
    error(S, "format mismatch");
  checkliteral(S, LUAC_DATA, "corrupted chunk");
  checksize(S, Instruction);
  checksize(S, lua_Integer);
  checksize(S, lua_Number);
  if (loadInteger(S) != LUAC_INT)
    error(S, "integer format mismatch");
  if (loadNumber(S) != LUAC_NUM)
    error(S, "float format mismatch");
}
References checkliteral(), checksize, error(), loadByte(), loadInteger(), loadNumber(), LUA_SIGNATURE, LUAC_DATA, LUAC_FORMAT, LUAC_INT, LUAC_NUM, LUAC_VERSION, and S.
Referenced by luaU_undump().
checkliteral()
static void checkliteral (LoadState * S, const char * s, const char * msg) static
Definition at line 273 of file lua-5.4.3/src/lundump.c.
{
  char buff[sizeof(LUA_SIGNATURE) + sizeof(LUAC_DATA)]; /* larger than both */
  size_t len = strlen(s);
  loadVector(S, buff, len);
  if (memcmp(s, buff, len) != 0)
    error(S, msg);
}
References error(), loadVector, LUA_SIGNATURE, LUAC_DATA, S, and s.
Referenced by checkHeader().
error()
static l_noret error (LoadState * S, const char * why) static
Definition at line 40 of file lua-5.4.3/src/lundump.c.
{
  luaO_pushfstring(S->L, "%s: bad binary format (%s)", S->name, why);
  luaD_throw(S->L, LUA_ERRSYNTAX);
}
References LUA_ERRSYNTAX, luaD_throw(), luaO_pushfstring(), and S.
Referenced by checkHeader(), checkliteral(), fchecksize(), loadBlock(), loadByte(), loadString(), and loadUnsigned().
fchecksize()
static void fchecksize (LoadState * S, size_t size, const char * tname) static
Definition at line 282 of file lua-5.4.3/src/lundump.c.
{
  if (loadByte(S) != size)
    error(S, luaO_pushfstring(S->L, "%s size mismatch", tname));
}
References error(), loadByte(), luaO_pushfstring(), and S.
loadBlock()
static void loadBlock (LoadState * S, void * b, size_t size) static
Definition at line 52 of file lua-5.4.3/src/lundump.c.
{
  if (luaZ_read(S->Z, b, size) != 0)
    error(S, "truncated chunk");
}
References error(), luaZ_read(), and S.
loadByte()
static lu_byte loadByte (LoadState * S) static
Definition at line 61 of file lua-5.4.3/src/lundump.c.
{
  int b = zgetc(S->Z);
  if (b == EOZ)
    error(S, "truncated chunk");
  return cast_byte(b);
}
References cast_byte, EOZ, error(), S, and zgetc.
Referenced by checkHeader(), fchecksize(), loadConstants(), loadFunction(), loadUnsigned(), loadUpvalues(), and luaU_undump().
loadCode()
static void loadCode (LoadState * S, Proto * f) static
Definition at line 144 of file lua-5.4.3/src/lundump.c.
{
  int n = loadInt(S);
  f->code = luaM_newvectorchecked(S->L, n, Instruction);
  f->sizecode = n;
  loadVector(S, f->code, n);
}
References Proto::code, loadInt(), loadVector, luaM_newvectorchecked, S, and Proto::sizecode.
Referenced by loadFunction().
loadConstants()
static void loadConstants (LoadState * S, Proto * f) static
Definition at line 155 of file lua-5.4.3/src/lundump.c.
{
  int i;
  int n = loadInt(S);
  f->k = luaM_newvectorchecked(S->L, n, TValue);
  f->sizek = n;
  for (i = 0; i < n; i++)
    setnilvalue(&f->k[i]);
  for (i = 0; i < n; i++) {
    TValue *o = &f->k[i];
    int t = loadByte(S);
    switch (t) {
      case LUA_VNIL:
        setnilvalue(o);
        break;
      case LUA_VFALSE:
        setbfvalue(o);
        break;
      case LUA_VTRUE:
        setbtvalue(o);
        break;
      case LUA_VNUMFLT:
        setfltvalue(o, loadNumber(S));
        break;
      case LUA_VNUMINT:
        setivalue(o, loadInteger(S));
        break;
      case LUA_VSHRSTR:
      case LUA_VLNGSTR:
        setsvalue2n(S->L, o, loadString(S, f));
        break;
      default: lua_assert(0);
    }
  }
}
References Proto::k, loadByte(), loadInt(), loadInteger(), loadNumber(), loadString(), lua_assert, LUA_VFALSE, LUA_VLNGSTR, LUA_VNIL, LUA_VNUMFLT, LUA_VNUMINT, LUA_VSHRSTR, LUA_VTRUE, luaM_newvectorchecked, S, setbfvalue, setbtvalue, setfltvalue, setivalue, setnilvalue, setsvalue2n, and Proto::sizek.
Referenced by loadFunction().
loadDebug()
static void loadDebug (LoadState * S, Proto * f) static
Definition at line 227 of file lua-5.4.3/src/lundump.c.
{
  int i, n;
  n = loadInt(S);
  f->lineinfo = luaM_newvectorchecked(S->L, n, ls_byte);
  f->sizelineinfo = n;
  loadVector(S, f->lineinfo, n);
  n = loadInt(S);
  f->abslineinfo = luaM_newvectorchecked(S->L, n, AbsLineInfo);
  f->sizeabslineinfo = n;
  for (i = 0; i < n; i++) {
    f->abslineinfo[i].pc = loadInt(S);
    f->abslineinfo[i].line = loadInt(S);
  }
  n = loadInt(S);
  f->locvars = luaM_newvectorchecked(S->L, n, LocVar);
  f->sizelocvars = n;
  for (i = 0; i < n; i++)
    f->locvars[i].varname = NULL;
  for (i = 0; i < n; i++) {
    f->locvars[i].varname = loadStringN(S, f);
    f->locvars[i].startpc = loadInt(S);
    f->locvars[i].endpc = loadInt(S);
  }
  n = loadInt(S);
  for (i = 0; i < n; i++)
    f->upvalues[i].name = loadStringN(S, f);
}
References Proto::abslineinfo, LocVar::endpc, AbsLineInfo::line, Proto::lineinfo, loadInt(), loadStringN(), loadVector, Proto::locvars, luaM_newvectorchecked, NULL, AbsLineInfo::pc, S, Proto::sizeabslineinfo, Proto::sizelineinfo, Proto::sizelocvars, LocVar::startpc, Proto::upvalues, and LocVar::varname.
Referenced by loadFunction().
loadFunction()
static void loadFunction (LoadState * S, Proto * f, TString * psource) static
Definition at line 256 of file lua-5.4.3/src/lundump.c.
{
  f->source = loadStringN(S, f);
  if (f->source == NULL)  /* no source in dump? */
    f->source = psource;  /* reuse parent's source */
  f->linedefined = loadInt(S);
  f->lastlinedefined = loadInt(S);
  f->numparams = loadByte(S);
  f->is_vararg = loadByte(S);
  f->maxstacksize = loadByte(S);
  loadCode(S, f);
  loadConstants(S, f);
  loadUpvalues(S, f);
  loadProtos(S, f);
  loadDebug(S, f);
}
References Proto::is_vararg, Proto::lastlinedefined, Proto::linedefined, loadByte(), loadCode(), loadConstants(), loadDebug(), loadInt(), loadProtos(), loadStringN(), loadUpvalues(), Proto::maxstacksize, NULL, Proto::numparams, S, and Proto::source.
Referenced by loadProtos(), and luaU_undump().
loadInt()
static int loadInt (LoadState * S) static
Definition at line 88 of file lua-5.4.3/src/lundump.c.
{
  return cast_int(loadUnsigned(S, INT_MAX));
}
References cast_int, loadUnsigned(), and S.
Referenced by loadCode(), loadConstants(), loadDebug(), loadFunction(), loadProtos(), and loadUpvalues().
loadInteger()
static lua_Integer loadInteger (LoadState * S) static
Definition at line 100 of file lua-5.4.3/src/lundump.c.
{
  lua_Integer x;
  loadVar(S, x);
  return x;
}
References loadVar, and S.
Referenced by checkHeader(), and loadConstants().
loadNumber()
static lua_Number loadNumber (LoadState * S) static
Definition at line 93 of file lua-5.4.3/src/lundump.c.
{
  lua_Number x;
  loadVar(S, x);
  return x;
}
References loadVar, and S.
Referenced by checkHeader(), and loadConstants().
loadProtos()
static void loadProtos (LoadState * S, Proto * f) static
Definition at line 191 of file lua-5.4.3/src/lundump.c.
{
  int i;
  int n = loadInt(S);
  f->p = luaM_newvectorchecked(S->L, n, Proto *);
  f->sizep = n;
  for (i = 0; i < n; i++)
    f->p[i] = NULL;
  for (i = 0; i < n; i++) {
    f->p[i] = luaF_newproto(S->L);
    luaC_objbarrier(S->L, f, f->p[i]);
    loadFunction(S, f->p[i], f->source);
  }
}
References loadFunction(), loadInt(), luaC_objbarrier, luaF_newproto(), luaM_newvectorchecked, NULL, Proto::p, S, Proto::sizep, and Proto::source.
Referenced by loadFunction().
loadSize()
static size_t loadSize (LoadState * S) static
Definition at line 83 of file lua-5.4.3/src/lundump.c.
{
  return loadUnsigned(S, ~(size_t)0);
}
References loadUnsigned(), and S.
Referenced by loadStringN().
loadString()
static TString * loadString (LoadState * S, Proto * p) static
Definition at line 136 of file lua-5.4.3/src/lundump.c.
{
  TString *st = loadStringN(S, p);
  if (st == NULL)
    error(S, "bad format for constant string");
  return st;
}
References error(), loadStringN(), NULL, and S.
Referenced by loadConstants().
loadStringN()
static TString * loadStringN (LoadState * S, Proto * p) static
Definition at line 110 of file lua-5.4.3/src/lundump.c.
{
  lua_State *L = S->L;
  TString *ts;
  size_t size = loadSize(S);
  if (size == 0)  /* no string? */
    return NULL;
  else if (--size <= LUAI_MAXSHORTLEN) {  /* short string? */
    char buff[LUAI_MAXSHORTLEN];
    loadVector(S, buff, size);  /* load string into buffer */
    ts = luaS_newlstr(L, buff, size);  /* create string */
  }
  else {  /* long string */
    ts = luaS_createlngstrobj(L, size);  /* create string */
    setsvalue2s(L, L->top, ts);  /* anchor it ('loadVector' can GC) */
    luaD_inctop(L);
    loadVector(S, getstr(ts), size);  /* load directly in final place */
    L->top--;  /* pop string */
  }
  luaC_objbarrier(L, p, ts);
  return ts;
}
References getstr, loadSize(), loadVector, luaC_objbarrier, luaD_inctop(), LUAI_MAXSHORTLEN, luaS_createlngstrobj(), luaS_newlstr(), NULL, S, setsvalue2s, and lua_State::top.
Referenced by loadDebug(), loadFunction(), and loadString().
loadUnsigned()
static size_t loadUnsigned (LoadState * S, size_t limit) static
Definition at line 69 of file lua-5.4.3/src/lundump.c.
{
  size_t x = 0;
  int b;
  limit >>= 7;
  do {
    b = loadByte(S);
    if (x >= limit)
      error(S, "integer overflow");
    x = (x << 7) | (b & 0x7f);
  } while ((b & 0x80) == 0);
  return x;
}
References error(), loadByte(), and S.
Referenced by loadInt(), and loadSize().
loadUpvalues()
static void loadUpvalues (LoadState * S, Proto * f) static
Definition at line 212 of file lua-5.4.3/src/lundump.c.
{
  int i, n;
  n = loadInt(S);
  f->upvalues = luaM_newvectorchecked(S->L, n, Upvaldesc);
  f->sizeupvalues = n;
  for (i = 0; i < n; i++)  /* make array valid for GC */
    f->upvalues[i].name = NULL;
  for (i = 0; i < n; i++) {  /* following calls can raise errors */
    f->upvalues[i].instack = loadByte(S);
    f->upvalues[i].idx = loadByte(S);
    f->upvalues[i].kind = loadByte(S);
  }
}
References loadByte(), loadInt(), luaM_newvectorchecked, NULL, S, Proto::sizeupvalues, and Proto::upvalues.
Referenced by loadFunction().
luaU_undump()
LClosure * luaU_undump (lua_State * L, ZIO * Z, const char * name)
Definition at line 311 of file lua-5.4.3/src/lundump.c.
{
  LoadState S;
  LClosure *cl;
  if (*name == '@' || *name == '=')
    S.name = name + 1;
  else if (*name == LUA_SIGNATURE[0])
    S.name = "binary string";
  else
    S.name = name;
  S.L = L;
  S.Z = Z;
  checkHeader(&S);
  cl = luaF_newLclosure(L, loadByte(&S));
  setclLvalue2s(L, L->top, cl);
  luaD_inctop(L);
  cl->p = luaF_newproto(L);
  luaC_objbarrier(L, cl, cl->p);
  loadFunction(&S, cl->p, NULL);
  lua_assert(cl->nupvalues == cl->p->sizeupvalues);
  luai_verifycode(L, cl->p);
  return cl;
}
References checkHeader(), loadByte(), loadFunction(), lua_assert, LUA_SIGNATURE, luaC_objbarrier, luaD_inctop(), luaF_newLclosure(), luaF_newproto(), luai_verifycode, name, NULL, LClosure::p, S, setclLvalue2s, Proto::sizeupvalues, and lua_State::top.