Github User Fetcher: lstate.c File Reference
lstate.c File Reference
#include "lprefix.h"
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "llex.h"
#include "lmem.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include <time.h>
Data Structures
struct LX
struct LG
Macros
#define lstate_c
#define LUA_CORE
#define fromstate(L) (cast(LX *, cast(lu_byte *, (L)) - offsetof(LX, l)))
#define addbuff(b, p, e)
Typedefs
typedef struct LX LX
typedef struct LG LG
Functions
static unsigned int luai_makeseed (lua_State *L)
void luaE_setdebt (global_State *g, l_mem debt)
LUA_API int lua_setcstacklimit (lua_State *L, unsigned int limit)
CallInfo * luaE_extendCI (lua_State *L)
void luaE_freeCI (lua_State *L)
void luaE_shrinkCI (lua_State *L)
void luaE_checkcstack (lua_State *L)
LUAI_FUNC void luaE_incCstack (lua_State *L)
static void stack_init (lua_State *L1, lua_State *L)
static void freestack (lua_State *L)
static void init_registry (lua_State *L, global_State *g)
static void f_luaopen (lua_State *L, void *ud)
static void preinit_thread (lua_State *L, global_State *g)
static void close_state (lua_State *L)
LUA_API lua_State * lua_newthread (lua_State *L)
void luaE_freethread (lua_State *L, lua_State *L1)
int luaE_resetthread (lua_State *L, int status)
LUA_API int lua_resetthread (lua_State *L)
LUA_API lua_State * lua_newstate (lua_Alloc f, void *ud)
LUA_API void lua_close (lua_State *L)
void luaE_warning (lua_State *L, const char *msg, int tocont)
void luaE_warnerror (lua_State *L, const char *where)
Macro Definition Documentation
addbuff
#define addbuff (b, p, e)
Value:
  { size_t t = cast_sizet(e); \
    memcpy(b + p, &t, sizeof(t)); p += sizeof(t); }
Definition at line 67 of file lua-5.4.3/src/lstate.c.
#define addbuff(b,p,e) \
  { size_t t = cast_sizet(e); \
    memcpy(b + p, &t, sizeof(t)); p += sizeof(t); }
Referenced by luai_makeseed().
fromstate
#define fromstate (L) (cast(LX *, cast(lu_byte *, (L)) - offsetof(LX, l)))
Definition at line 51 of file lua-5.4.3/src/lstate.c.
Referenced by close_state(), and luaE_freethread().
lstate_c
#define lstate_c
Definition at line 7 of file lua-5.4.3/src/lstate.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/lstate.c.
Typedef Documentation
LG
typedef struct LG LG
LX
typedef struct LX LX
Function Documentation
close_state()
static void close_state (lua_State * L) static
Definition at line 269 of file lua-5.4.3/src/lstate.c.
{
  global_State *g = G(L);
  if (!completestate(g))  /* closing a partially built state? */
    luaC_freeallobjects(L);  /* jucst collect its objects */
  else {  /* closing a fully built state */
    luaD_closeprotected(L, 1, LUA_OK);  /* close all upvalues */
    luaC_freeallobjects(L);  /* collect all objects */
    luai_userstateclose(L);
  }
  luaM_freearray(L, G(L)->strt.hash, G(L)->strt.size);
  freestack(L);
  lua_assert(gettotalbytes(g) == sizeof(LG));
  (*g->frealloc)(g->ud, fromstate(L), sizeof(LG), 0);  /* free main block */
}
References completestate, global_State::frealloc, freestack(), fromstate, G, gettotalbytes, lua_assert, LUA_OK, luaC_freeallobjects(), luaD_closeprotected(), luai_userstateclose, luaM_freearray, and global_State::ud.
Referenced by lua_close(), and lua_newstate().
f_luaopen()
static void f_luaopen (lua_State * L, void * ud) static
Definition at line 231 of file lua-5.4.3/src/lstate.c.
{
  global_State *g = G(L);
  UNUSED(ud);
  stack_init(L, L);  /* init stack */
  init_registry(L, g);
  luaS_init(L);
  luaT_init(L);
  luaX_init(L);
  g->gcrunning = 1;  /* allow gc */
  setnilvalue(&g->nilvalue);  /* now state is complete */
  luai_userstateopen(L);
}
References G, global_State::gcrunning, init_registry(), luai_userstateopen, luaS_init(), luaT_init(), luaX_init(), global_State::nilvalue, setnilvalue, stack_init(), and UNUSED.
Referenced by lua_newstate().
freestack()
static void freestack (lua_State * L) static
Definition at line 203 of file lua-5.4.3/src/lstate.c.
{
  if (L->stack == NULL)
    return;  /* stack not completely built yet */
  L->ci = &L->base_ci;  /* free the entire 'ci' list */
  luaE_freeCI(L);
  lua_assert(L->nci == 0);
  luaM_freearray(L, L->stack, stacksize(L) + EXTRA_STACK);  /* free stack */
}
References lua_State::base_ci, lua_State::ci, EXTRA_STACK, lua_assert, luaE_freeCI(), luaM_freearray, lua_State::nci, NULL, lua_State::stack, and stacksize.
Referenced by close_state(), and luaE_freethread().
init_registry()
static void init_registry (lua_State * L, global_State * g) static
Definition at line 216 of file lua-5.4.3/src/lstate.c.
{
  /* create registry */
  Table *registry = luaH_new(L);
  sethvalue(L, &g->l_registry, registry);
  luaH_resize(L, registry, LUA_RIDX_LAST, 0);
  /* registry[LUA_RIDX_MAINTHREAD] = L */
  setthvalue(L, &registry->array[LUA_RIDX_MAINTHREAD - 1], L);
  /* registry[LUA_RIDX_GLOBALS] = new table (table of globals) */
  sethvalue(L, &registry->array[LUA_RIDX_GLOBALS - 1], luaH_new(L));
}
References global_State::l_registry, LUA_RIDX_GLOBALS, LUA_RIDX_LAST, LUA_RIDX_MAINTHREAD, luaH_new(), luaH_resize(), registry, sethvalue, and setthvalue.
Referenced by f_luaopen().
lua_close()
LUA_API void lua_close (lua_State * L)
Definition at line 410 of file lua-5.4.3/src/lstate.c.
{
  lua_lock(L);
  L = G(L)->mainthread;  /* only the main thread can be closed */
  close_state(L);
}
References close_state(), G, and lua_lock.
lua_newstate()
LUA_API lua_State * lua_newstate (lua_Alloc f, void * ud)
Definition at line 354 of file lua-5.4.3/src/lstate.c.
{
  int i;
  lua_State *L;
  global_State *g;
  LG *l = cast(LG *, (*f)(ud, NULL, LUA_TTHREAD, sizeof(LG)));
  if (l == NULL) return NULL;
  L = &l->l.l;
  g = &l->g;
  L->tt = LUA_VTHREAD;
  g->currentwhite = bitmask(WHITE0BIT);
  L->marked = luaC_white(g);
  preinit_thread(L, g);
  g->allgc = obj2gco(L);  /* by now, only object is the main thread */
  L->next = NULL;
  incnny(L);  /* main thread is always non yieldable */
  g->frealloc = f;
  g->ud = ud;
  g->warnf = NULL;
  g->ud_warn = NULL;
  g->mainthread = L;
  g->seed = luai_makeseed(L);
  g->gcrunning = 0;  /* no GC while building state */
  g->strt.size = g->strt.nuse = 0;
  g->strt.hash = NULL;
  setnilvalue(&g->l_registry);
  g->panic = NULL;
  g->gcstate = GCSpause;
  g->gckind = KGC_INC;
  g->gcstopem = 0;
  g->gcemergency = 0;
  g->finobj = g->tobefnz = g->fixedgc = NULL;
  g->firstold1 = g->survival = g->old1 = g->reallyold = NULL;
  g->finobjsur = g->finobjold1 = g->finobjrold = NULL;
  g->sweepgc = NULL;
  g->gray = g->grayagain = NULL;
  g->weak = g->ephemeron = g->allweak = NULL;
  g->twups = NULL;
  g->totalbytes = sizeof(LG);
  g->GCdebt = 0;
  g->lastatomic = 0;
  setivalue(&g->nilvalue, 0);  /* to signal that state is not yet built */
  setgcparam(g->gcpause, LUAI_GCPAUSE);
  setgcparam(g->gcstepmul, LUAI_GCMUL);
  g->gcstepsize = LUAI_GCSTEPSIZE;
  setgcparam(g->genmajormul, LUAI_GENMAJORMUL);
  g->genminormul = LUAI_GENMINORMUL;
  for (i=0; i < LUA_NUMTAGS; i++) g->mt[i] = NULL;
  if (luaD_rawrunprotected(L, f_luaopen, NULL) != LUA_OK) {
    /* memory allocation error: free partial state */
    close_state(L);
    L = NULL;
  }
  return L;
}
References global_State::allgc, global_State::allweak, bitmask, cast, close_state(), global_State::currentwhite, global_State::ephemeron, f_luaopen(), global_State::finobj, global_State::finobjold1, global_State::finobjrold, global_State::finobjsur, global_State::firstold1, global_State::fixedgc, global_State::frealloc, LG::g, global_State::GCdebt, global_State::gcemergency, global_State::gckind, global_State::gcpause, global_State::gcrunning, GCSpause, global_State::gcstate, global_State::gcstepmul, global_State::gcstepsize, global_State::gcstopem, global_State::genmajormul, global_State::genminormul, global_State::gray, global_State::grayagain, stringtable::hash, incnny, KGC_INC, LG::l, global_State::l_registry, global_State::lastatomic, LUA_NUMTAGS, LUA_OK, LUA_TTHREAD, LUA_VTHREAD, luaC_white, luaD_rawrunprotected(), LUAI_GCMUL, LUAI_GCPAUSE, LUAI_GCSTEPSIZE, LUAI_GENMAJORMUL, LUAI_GENMINORMUL, luai_makeseed, global_State::mainthread, global_State::mt, global_State::nilvalue, NULL, stringtable::nuse, obj2gco, global_State::old1, global_State::panic, preinit_thread(), global_State::reallyold, global_State::seed, setgcparam, setivalue, setnilvalue, stringtable::size, global_State::strt, global_State::survival, global_State::sweepgc, global_State::tobefnz, global_State::totalbytes, global_State::twups, global_State::ud, global_State::ud_warn, global_State::warnf, global_State::weak, and WHITE0BIT.
Referenced by luai_makeseed().
lua_newthread()
LUA_API lua_State * lua_newthread (lua_State * L)
Definition at line 285 of file lua-5.4.3/src/lstate.c.
{
  global_State *g;
  lua_State *L1;
  lua_lock(L);
  g = G(L);
  luaC_checkGC(L);
  /* create new thread */
  L1 = &cast(LX *, luaM_newobject(L, LUA_TTHREAD, sizeof(LX)))->l;
  L1->marked = luaC_white(g);
  L1->tt = LUA_VTHREAD;
  /* link it on list 'allgc' */
  L1->next = g->allgc;
  g->allgc = obj2gco(L1);
  /* anchor it on L stack */
  setthvalue2s(L, L->top, L1);
  api_incr_top(L);
  preinit_thread(L1, g);
  L1->hookmask = L->hookmask;
  L1->basehookcount = L->basehookcount;
  L1->hook = L->hook;
  resethookcount(L1);
  /* initialize L1 extra space */
  memcpy(lua_getextraspace(L1), lua_getextraspace(g->mainthread),
         LUA_EXTRASPACE);
  luai_userstatethread(L, L1);
  stack_init(L1, L);  /* init stack */
  lua_unlock(L);
  return L1;
}
References global_State::allgc, api_incr_top, lua_State::basehookcount, cast, G, lua_State::hook, lua_State::hookmask, LUA_EXTRASPACE, lua_getextraspace, lua_lock, LUA_TTHREAD, lua_unlock, LUA_VTHREAD, luaC_checkGC, luaC_white, luai_userstatethread, luaM_newobject, global_State::mainthread, obj2gco, preinit_thread(), resethookcount, setthvalue2s, stack_init(), and lua_State::top.
lua_resetthread()
LUA_API int lua_resetthread (lua_State * L)
Definition at line 345 of file lua-5.4.3/src/lstate.c.
{
  int status;
  lua_lock(L);
  status = luaE_resetthread(L, L->status);
  lua_unlock(L);
  return status;
}
References lua_lock, lua_unlock, luaE_resetthread(), and lua_State::status.
Referenced by luaB_auxwrap(), and luaB_close().
lua_setcstacklimit()
LUA_API int lua_setcstacklimit (lua_State * L, unsigned int limit)
Definition at line 99 of file lua-5.4.3/src/lstate.c.
{
  UNUSED(L); UNUSED(limit);
  return LUAI_MAXCCALLS;  /* warning?? */
}
References LUAI_MAXCCALLS, and UNUSED.
Referenced by db_setcstacklimit().
luaE_checkcstack()
void luaE_checkcstack (lua_State * L)
Definition at line 165 of file lua-5.4.3/src/lstate.c.
{
  if (getCcalls(L) == LUAI_MAXCCALLS)
    luaG_runerror(L, "C stack overflow");
  else if (getCcalls(L) >= (LUAI_MAXCCALLS / 10 * 11))
    luaD_throw(L, LUA_ERRERR);  /* error while handing stack error */
}
References getCcalls, LUA_ERRERR, luaD_throw(), luaG_runerror(), and LUAI_MAXCCALLS.
Referenced by ccall(), and luaE_incCstack().
luaE_extendCI()
CallInfo * luaE_extendCI (lua_State * L)
Definition at line 105 of file lua-5.4.3/src/lstate.c.
{
  CallInfo *ci;
  lua_assert(L->ci->next == NULL);
  ci = luaM_new(L, CallInfo);
  lua_assert(L->ci->next == NULL);
  L->ci->next = ci;
  ci->previous = L->ci;
  ci->next = NULL;
  ci->u.l.trap = 0;
  L->nci++;
  return ci;
}
References lua_State::ci, CallInfo::l, lua_assert, luaM_new, lua_State::nci, CallInfo::next, NULL, CallInfo::previous, CallInfo::trap, and CallInfo::u.
luaE_freeCI()
void luaE_freeCI (lua_State * L)
Definition at line 122 of file lua-5.4.3/src/lstate.c.
{
  CallInfo *ci = L->ci;
  CallInfo *next = ci->next;
  ci->next = NULL;
  while ((ci = next) != NULL) {
    next = ci->next;
    luaM_free(L, ci);
    L->nci--;
  }
}
References lua_State::ci, luaM_free, lua_State::nci, next, CallInfo::next, and NULL.
Referenced by freestack().
luaE_freethread()
void luaE_freethread (lua_State * L, lua_State * L1)
Definition at line 316 of file lua-5.4.3/src/lstate.c.
{
  LX *l = fromstate(L1);
  luaF_closeupval(L1, L1->stack);  /* close all upvalues */
  lua_assert(L1->openupval == NULL);
  luai_userstatefree(L, L1);
  freestack(L1);
  luaM_free(L, l);
}
References freestack(), fromstate, lua_assert, luaF_closeupval(), luai_userstatefree, luaM_free, NULL, lua_State::openupval, and lua_State::stack.
luaE_incCstack()
LUAI_FUNC void luaE_incCstack (lua_State * L)
Definition at line 173 of file lua-5.4.3/src/lstate.c.
{
  L->nCcalls++;
  if (l_unlikely(getCcalls(L) >= LUAI_MAXCCALLS))
    luaE_checkcstack(L);
}
References getCcalls, luaE_checkcstack(), LUAI_MAXCCALLS, and lua_State::nCcalls.
Referenced by resume().
luaE_resetthread()
int luaE_resetthread (lua_State * L, int status)
Definition at line 326 of file lua-5.4.3/src/lstate.c.
{
  CallInfo *ci = L->ci = &L->base_ci;  /* unwind CallInfo list */
  setnilvalue(s2v(L->stack));  /* 'function' entry for basic 'ci' */
  ci->func = L->stack;
  ci->callstatus = CIST_C;
  if (status == LUA_YIELD)
    status = LUA_OK;
  status = luaD_closeprotected(L, 1, status);
  if (status != LUA_OK)  /* errors? */
    luaD_seterrorobj(L, status, L->stack + 1);
  else
    L->top = L->stack + 1;
  ci->top = L->top + LUA_MINSTACK;
  L->status = cast_byte(status);
  luaD_reallocstack(L, cast_int(ci->top - L->stack), 0);
  return status;
}
References lua_State::base_ci, CallInfo::callstatus, cast_byte, cast_int, lua_State::ci, CIST_C, CallInfo::func, LUA_MINSTACK, LUA_OK, LUA_YIELD, luaD_closeprotected(), luaD_reallocstack(), luaD_seterrorobj(), s2v, setnilvalue, lua_State::stack, lua_State::status, CallInfo::top, and lua_State::top.
Referenced by lua_resetthread(), and luaD_throw().
luaE_setdebt()
void luaE_setdebt (global_State * g, l_mem debt)
Definition at line 89 of file lua-5.4.3/src/lstate.c.
{
  l_mem tb = gettotalbytes(g);
  lua_assert(tb > 0);
  if (debt < tb - MAX_LMEM)
    debt = tb - MAX_LMEM;  /* will make 'totalbytes == MAX_LMEM' */
  g->totalbytes = tb - debt;
  g->GCdebt = debt;
}
References global_State::GCdebt, gettotalbytes, lua_assert, MAX_LMEM, and global_State::totalbytes.
luaE_shrinkCI()
void luaE_shrinkCI (lua_State * L)
Definition at line 138 of file lua-5.4.3/src/lstate.c.
{
  CallInfo *ci = L->ci->next;  /* first free CallInfo */
  CallInfo *next;
  if (ci == NULL)
    return;  /* no extra elements */
  while ((next = ci->next) != NULL) {  /* two extra elements? */
    CallInfo *next2 = next->next;  /* next's next */
    ci->next = next2;  /* remove next from the list */
    L->nci--;
    luaM_free(L, next);  /* free next */
    if (next2 == NULL)
      break;  /* no more elements */
    else {
      next2->previous = ci;
      ci = next2;  /* continue */
    }
  }
}
References lua_State::ci, luaM_free, lua_State::nci, next, CallInfo::next, NULL, and CallInfo::previous.
luaE_warnerror()
void luaE_warnerror (lua_State * L, const char * where)
Definition at line 427 of file lua-5.4.3/src/lstate.c.
{
  TValue *errobj = s2v(L->top - 1);  /* error object */
  const char *msg = (ttisstring(errobj))
                  ? svalue(errobj)
                  : "error object is not a string";
  /* produce warning "error in %s (%s)" (where, msg) */
  luaE_warning(L, "error in ", 1);
  luaE_warning(L, where, 1);
  luaE_warning(L, " (", 1);
  luaE_warning(L, msg, 1);
  luaE_warning(L, ")", 0);
}
References luaE_warning(), s2v, svalue, lua_State::top, and ttisstring.
Referenced by GCTM().
luaE_warning()
void luaE_warning (lua_State * L, const char * msg, int tocont)
Definition at line 417 of file lua-5.4.3/src/lstate.c.
{
  lua_WarnFunction wf = G(L)->warnf;
  if (wf != NULL)
    wf(G(L)->ud_warn, msg, tocont);
}
References G, and NULL.
Referenced by lua_warning(), and luaE_warnerror().
luai_makeseed()
static unsigned int luai_makeseed (lua_State * L) static
Definition at line 71 of file lua-5.4.3/src/lstate.c.
{
  char buff[3 * sizeof(size_t)];
  unsigned int h = cast_uint(time(NULL));
  int p = 0;
  addbuff(buff, p, L);  /* heap variable */
  addbuff(buff, p, &h);  /* local variable */
  addbuff(buff, p, &lua_newstate);  /* public function */
  lua_assert(p == sizeof(buff));
  return luaS_hash(buff, p, h);
}
References addbuff, cast_uint, lua_assert, lua_newstate(), luaS_hash(), and NULL.
preinit_thread()
static void preinit_thread (lua_State * L, global_State * g) static
Definition at line 249 of file lua-5.4.3/src/lstate.c.
{
  G(L) = g;
  L->stack = NULL;
  L->ci = NULL;
  L->nci = 0;
  L->twups = L;  /* thread has no upvalues */
  L->nCcalls = 0;
  L->errorJmp = NULL;
  L->hook = NULL;
  L->hookmask = 0;
  L->basehookcount = 0;
  L->allowhook = 1;
  resethookcount(L);
  L->openupval = NULL;
  L->status = LUA_OK;
  L->errfunc = 0;
  L->oldpc = 0;
}
References lua_State::allowhook, lua_State::basehookcount, lua_State::ci, lua_State::errfunc, lua_State::errorJmp, G, lua_State::hook, lua_State::hookmask, LUA_OK, lua_State::nCcalls, lua_State::nci, NULL, lua_State::oldpc, lua_State::openupval, resethookcount, lua_State::stack, lua_State::status, and lua_State::twups.
Referenced by lua_newstate(), and lua_newthread().
stack_init()
static void stack_init (lua_State * L1, lua_State * L) static
Definition at line 180 of file lua-5.4.3/src/lstate.c.
{
  int i; CallInfo *ci;
  /* initialize stack array */
  L1->stack = luaM_newvector(L, BASIC_STACK_SIZE + EXTRA_STACK, StackValue);
  L1->tbclist = L1->stack;
  for (i = 0; i < BASIC_STACK_SIZE + EXTRA_STACK; i++)
    setnilvalue(s2v(L1->stack + i));  /* erase new stack */
  L1->top = L1->stack;
  L1->stack_last = L1->stack + BASIC_STACK_SIZE;
  /* initialize first ci */
  ci = &L1->base_ci;
  ci->next = ci->previous = NULL;
  ci->callstatus = CIST_C;
  ci->func = L1->top;
  ci->u.c.k = NULL;
  ci->nresults = 0;
  setnilvalue(s2v(L1->top));  /* 'function' entry for this 'ci' */
  L1->top++;
  ci->top = L1->top + LUA_MINSTACK;
  L1->ci = ci;
}
References lua_State::base_ci, BASIC_STACK_SIZE, CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_C, EXTRA_STACK, CallInfo::func, CallInfo::k, LUA_MINSTACK, luaM_newvector, CallInfo::next, CallInfo::nresults, NULL, CallInfo::previous, s2v, setnilvalue, lua_State::stack, lua_State::stack_last, lua_State::tbclist, CallInfo::top, lua_State::top, and CallInfo::u.
Referenced by f_luaopen(), and lua_newthread().