Github User Fetcher: lgc.c File Reference
lgc.c File Reference
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
Macros
#define lgc_c
#define LUA_CORE
#define GCSTEPSIZE 1024u
#define GCSWEEPMAX 40
#define GCSWEEPCOST 10
#define GCFINALIZECOST 100
#define maskmarks cast_byte(~(bitmask(BLACKBIT)|WHITEBITS))
#define makewhite(g, x) ((x)->gch.marked = cast_byte(((x)->gch.marked & maskmarks) | luaC_white(g)))
#define white2gray(x) reset2bits((x)->gch.marked, WHITE0BIT, WHITE1BIT)
#define black2gray(x) resetbit((x)->gch.marked, BLACKBIT)
#define stringmark(s) reset2bits((s)->tsv.marked, WHITE0BIT, WHITE1BIT)
#define isfinalized(u) testbit((u)->marked, FINALIZEDBIT)
#define markfinalized(u) l_setbit((u)->marked, FINALIZEDBIT)
#define KEYWEAK bitmask(KEYWEAKBIT)
#define VALUEWEAK bitmask(VALUEWEAKBIT)
#define markvalue(g, o)
#define markobject(g, t)
#define setthreshold(g) (g->GCthreshold = (g->estimate/100) * g->gcpause)
#define sweepwholelist(L, p) sweeplist(L,p,MAX_LUMEM)
Functions
static void removeentry (Node *n)
static void reallymarkobject (global_State *g, GCObject *o)
static void marktmu (global_State *g)
size_t luaC_separateudata (lua_State *L, int all)
static int traversetable (global_State *g, Table *h)
static void traverseproto (global_State *g, Proto *f)
static void traverseclosure (global_State *g, Closure *cl)
static void checkstacksizes (lua_State *L, StkId max)
static void traversestack (global_State *g, lua_State *l)
static l_mem propagatemark (global_State *g)
static size_t propagateall (global_State *g)
static int iscleared (const TValue *o, int iskey)
static void cleartable (GCObject *l)
static void freeobj (lua_State *L, GCObject *o)
static GCObject ** sweeplist (lua_State *L, GCObject **p, lu_mem count)
static void checkSizes (lua_State *L)
static void GCTM (lua_State *L)
void luaC_callGCTM (lua_State *L)
void luaC_freeall (lua_State *L)
static void markmt (global_State *g)
static void markroot (lua_State *L)
static void remarkupvals (global_State *g)
static void atomic (lua_State *L)
static l_mem singlestep (lua_State *L)
void luaC_step (lua_State *L)
void luaC_fullgc (lua_State *L)
void luaC_barrierf (lua_State *L, GCObject *o, GCObject *v)
void luaC_barrierback (lua_State *L, Table *t)
void luaC_link (lua_State *L, GCObject *o, lu_byte tt)
void luaC_linkupval (lua_State *L, UpVal *uv)
Macro Definition Documentation
black2gray
#define black2gray (x) resetbit((x)->gch.marked, BLACKBIT)
Definition at line 38 of file lua-5.1.5/src/lgc.c.
Referenced by luaC_barrierback(), and propagatemark().
GCFINALIZECOST
#define GCFINALIZECOST 100
Definition at line 29 of file lua-5.1.5/src/lgc.c.
Referenced by singlestep().
GCSTEPSIZE
#define GCSTEPSIZE 1024u
Definition at line 26 of file lua-5.1.5/src/lgc.c.
Referenced by incstep(), lua_gc(), and luaC_step().
GCSWEEPCOST
#define GCSWEEPCOST 10
Definition at line 28 of file lua-5.1.5/src/lgc.c.
Referenced by singlestep().
GCSWEEPMAX
#define GCSWEEPMAX 40
Definition at line 27 of file lua-5.1.5/src/lgc.c.
Referenced by singlestep().
isfinalized
#define isfinalized (u) testbit((u)->marked, FINALIZEDBIT)
Definition at line 43 of file lua-5.1.5/src/lgc.c.
Referenced by iscleared(), and luaC_separateudata().
KEYWEAK
#define KEYWEAK bitmask(KEYWEAKBIT)
Definition at line 47 of file lua-5.1.5/src/lgc.c.
Referenced by traversetable().
lgc_c
#define lgc_c
Definition at line 9 of file lua-5.1.5/src/lgc.c.
LUA_CORE
#define LUA_CORE
Definition at line 10 of file lua-5.1.5/src/lgc.c.
makewhite
#define makewhite (g, x) ((x)->gch.marked = cast_byte(((x)->gch.marked & maskmarks) | luaC_white(g)))
Definition at line 34 of file lua-5.1.5/src/lgc.c.
#define makewhite(g,x)  \
   ((x)->gch.marked = cast_byte(((x)->gch.marked & maskmarks) | luaC_white(g)))
Referenced by GCTM(), luaC_barrierf(), luaC_linkupval(), marktmu(), and sweeplist().
markfinalized
#define markfinalized (u) l_setbit((u)->marked, FINALIZEDBIT)
Definition at line 44 of file lua-5.1.5/src/lgc.c.
Referenced by luaC_separateudata().
markobject
#define markobject (g, t)
Value:
        { if (iswhite(obj2gco(t))) \
        reallymarkobject(g, obj2gco(t)); }
Definition at line 55 of file lua-5.1.5/src/lgc.c.
#define markobject(g,t) { if (iswhite(obj2gco(t))) \
        reallymarkobject(g, obj2gco(t)); }
Referenced by atomic(), markmt(), markroot(), reallymarkobject(), traverseclosure(), traverseproto(), and traversetable().
markvalue
#define markvalue (g, o)
Value:
  { checkconsistency(o); \
  if (iscollectable(o) && iswhite(gcvalue(o))) reallymarkobject(g,gcvalue(o)); }
Definition at line 52 of file lua-5.1.5/src/lgc.c.
#define markvalue(g,o) { checkconsistency(o); \
  if (iscollectable(o) && iswhite(gcvalue(o))) reallymarkobject(g,gcvalue(o)); }
Referenced by markroot(), reallymarkobject(), remarkupvals(), traverseclosure(), traverseproto(), traversestack(), and traversetable().
maskmarks
#define maskmarks cast_byte(~(bitmask(BLACKBIT)|WHITEBITS))
Definition at line 32 of file lua-5.1.5/src/lgc.c.
setthreshold
#define setthreshold (g) (g->GCthreshold = (g->estimate/100) * g->gcpause)
Definition at line 59 of file lua-5.1.5/src/lgc.c.
Referenced by luaC_fullgc(), and luaC_step().
stringmark
#define stringmark (s) reset2bits((s)->tsv.marked, WHITE0BIT, WHITE1BIT)
Definition at line 40 of file lua-5.1.5/src/lgc.c.
Referenced by iscleared(), and traverseproto().
sweepwholelist
#define sweepwholelist (L, p) sweeplist(L,p,MAX_LUMEM)
Definition at line 404 of file lua-5.1.5/src/lgc.c.
Referenced by luaC_freeall(), singlestep(), and sweeplist().
VALUEWEAK
#define VALUEWEAK bitmask(VALUEWEAKBIT)
Definition at line 48 of file lua-5.1.5/src/lgc.c.
Referenced by traversetable().
white2gray
#define white2gray (x) reset2bits((x)->gch.marked, WHITE0BIT, WHITE1BIT)
Definition at line 37 of file lua-5.1.5/src/lgc.c.
Referenced by reallymarkobject().
Function Documentation
atomic()
static void atomic (lua_State * L) static
Definition at line 525 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  size_t udsize;  /* total size of userdata to be finalized */
  /* remark occasional upvalues of (maybe) dead threads */
  remarkupvals(g);
  /* traverse objects cautch by write barrier and by 'remarkupvals' */
  propagateall(g);
  /* remark weak tables */
  g->gray = g->weak;
  g->weak = NULL;
  lua_assert(!iswhite(obj2gco(g->mainthread)));
  markobject(g, L);  /* mark running thread */
  markmt(g);  /* mark basic metatables (again) */
  propagateall(g);
  /* remark gray again */
  g->gray = g->grayagain;
  g->grayagain = NULL;
  propagateall(g);
  udsize = luaC_separateudata(L, 0);  /* separate userdata to be finalized */
  marktmu(g);  /* mark `preserved' userdata */
  udsize += propagateall(g);  /* remark, to propagate `preserveness' */
  cleartable(g->weak);  /* remove collected objects from weak tables */
  /* flip current white */
  g->currentwhite = cast_byte(otherwhite(g));
  g->sweepstrgc = 0;
  g->sweepgc = &g->rootgc;
  g->gcstate = GCSsweepstring;
  g->estimate = g->totalbytes - udsize;  /* first estimate */
}
References cast_byte, cleartable(), global_State::currentwhite, global_State::estimate, G, GCSsweepstring, global_State::gcstate, global_State::gray, global_State::grayagain, iswhite, lua_assert, luaC_separateudata(), global_State::mainthread, markmt(), markobject, marktmu(), NULL, obj2gco, otherwhite, propagateall(), remarkupvals(), global_State::rootgc, global_State::sweepgc, global_State::sweepstrgc, global_State::totalbytes, and global_State::weak.
Referenced by singlestep().
checkSizes()
static void checkSizes (lua_State * L) static
Definition at line 431 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  /* check size of string hash */
  if (g->strt.nuse < cast(lu_int32, g->strt.size/4) &&
      g->strt.size > MINSTRTABSIZE*2)
    luaS_resize(L, g->strt.size/2);  /* table is too big */
  /* check size of buffer */
  if (luaZ_sizebuffer(&g->buff) > LUA_MINBUFFER*2) {  /* buffer too big? */
    size_t newsize = luaZ_sizebuffer(&g->buff) / 2;
    luaZ_resizebuffer(L, &g->buff, newsize);
  }
}
References global_State::buff, cast, G, LUA_MINBUFFER, luaS_resize(), luaZ_resizebuffer, luaZ_sizebuffer, MINSTRTABSIZE, stringtable::nuse, stringtable::size, and global_State::strt.
Referenced by singlestep().
checkstacksizes()
static void checkstacksizes (lua_State * L, StkId max) static
Definition at line 241 of file lua-5.1.5/src/lgc.c.
{
  int ci_used = cast_int(L->ci - L->base_ci);  /* number of `ci' in use */
  int s_used = cast_int(max - L->stack);  /* part of stack in use */
  if (L->size_ci > LUAI_MAXCALLS)  /* handling overflow? */
    return;  /* do not touch the stacks */
  if (4*ci_used < L->size_ci && 2*BASIC_CI_SIZE < L->size_ci)
    luaD_reallocCI(L, L->size_ci/2);  /* still big enough... */
  condhardstacktests(luaD_reallocCI(L, ci_used + 1));
  if (4*s_used < L->stacksize &&
      2*(BASIC_STACK_SIZE+EXTRA_STACK) < L->stacksize)
    luaD_reallocstack(L, L->stacksize/2);  /* still big enough... */
  condhardstacktests(luaD_reallocstack(L, s_used));
}
References lua_State::base_ci, BASIC_STACK_SIZE, cast_int, lua_State::ci, condhardstacktests, EXTRA_STACK, luaD_reallocCI(), luaD_reallocstack(), LUAI_MAXCALLS, lua_State::size_ci, lua_State::stack, lua_State::stacksize, and stacksize.
Referenced by traversestack().
cleartable()
static void cleartable (GCObject * l) static
Definition at line 351 of file lua-5.1.5/src/lgc.c.
{
  while (l) {
    Table *h = gco2h(l);
    int i = h->sizearray;
    lua_assert(testbit(h->marked, VALUEWEAKBIT) ||
               testbit(h->marked, KEYWEAKBIT));
    if (testbit(h->marked, VALUEWEAKBIT)) {
      while (i--) {
        TValue *o = &h->array[i];
        if (iscleared(o, 0))  /* value was collected? */
          setnilvalue(o);  /* remove value */
      }
    }
    i = sizenode(h);
    while (i--) {
      Node *n = gnode(h, i);
      if (!ttisnil(gval(n)) &&  /* non-empty entry? */
          (iscleared(key2tval(n), 1) || iscleared(gval(n), 0))) {
        setnilvalue(gval(n));  /* remove value ... */
        removeentry(n);  /* remove entry from table */
      }
    }
    l = h->gclist;
  }
}
References Table::array, Table::gclist, gco2h, gnode, gval, iscleared(), key2tval, KEYWEAKBIT, lua_assert, removeentry(), setnilvalue, Table::sizearray, sizenode, testbit, ttisnil, and VALUEWEAKBIT.
Referenced by atomic().
freeobj()
static void freeobj (lua_State * L, GCObject * o) static
Definition at line 378 of file lua-5.1.5/src/lgc.c.
{
  switch (o->gch.tt) {
    case LUA_TPROTO: luaF_freeproto(L, gco2p(o)); break;
    case LUA_TFUNCTION: luaF_freeclosure(L, gco2cl(o)); break;
    case LUA_TUPVAL: luaF_freeupval(L, gco2uv(o)); break;
    case LUA_TTABLE: luaH_free(L, gco2h(o)); break;
    case LUA_TTHREAD: {
      lua_assert(gco2th(o) != L && gco2th(o) != G(L)->mainthread);
      luaE_freethread(L, gco2th(o));
      break;
    }
    case LUA_TSTRING: {
      G(L)->strt.nuse--;
      luaM_freemem(L, o, sizestring(gco2ts(o)));
      break;
    }
    case LUA_TUSERDATA: {
      luaM_freemem(L, o, sizeudata(gco2u(o)));
      break;
    }
    default: lua_assert(0);
  }
}
References G, GCObject::gch, gco2cl, gco2h, gco2p, gco2th, gco2ts, gco2u, gco2uv, lua_assert, LUA_TFUNCTION, LUA_TPROTO, LUA_TSTRING, LUA_TTABLE, LUA_TTHREAD, LUA_TUPVAL, LUA_TUSERDATA, luaE_freethread(), luaF_freeclosure(), luaF_freeproto(), luaF_freeupval(), luaH_free(), luaM_freemem, sizestring, and sizeudata.
Referenced by sweeplist().
GCTM()
static void GCTM (lua_State * L) static
Definition at line 445 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  GCObject *o = g->tmudata->gch.next;  /* get first element */
  Udata *udata = rawgco2u(o);
  const TValue *tm;
  /* remove udata from `tmudata' */
  if (o == g->tmudata)  /* last element? */
    g->tmudata = NULL;
  else
    g->tmudata->gch.next = udata->uv.next;
  udata->uv.next = g->mainthread->next;  /* return it to `root' list */
  g->mainthread->next = o;
  makewhite(g, o);
  tm = fasttm(L, udata->uv.metatable, TM_GC);
  if (tm != NULL) {
    lu_byte oldah = L->allowhook;
    lu_mem oldt = g->GCthreshold;
    L->allowhook = 0;  /* stop debug hooks during GC tag method */
    g->GCthreshold = 2*g->totalbytes;  /* avoid GC steps */
    setobj2s(L, L->top, tm);
    setuvalue(L, L->top+1, udata);
    L->top += 2;
    luaD_call(L, L->top - 2, 0);
    L->allowhook = oldah;  /* restore hooks */
    g->GCthreshold = oldt;  /* restore threshold */
  }
}
References lua_State::allowhook, fasttm, G, GCObject::gch, global_State::GCthreshold, luaD_call(), global_State::mainthread, makewhite, Udata::metatable, NULL, rawgco2u, setobj2s, setuvalue, TM_GC, global_State::tmudata, lua_State::top, global_State::totalbytes, and Udata::uv.
Referenced by luaC_callGCTM(), and singlestep().
iscleared()
static int iscleared (const TValue * o, int iskey) static
Definition at line 337 of file lua-5.1.5/src/lgc.c.
{
  if (!iscollectable(o)) return 0;
  if (ttisstring(o)) {
    stringmark(rawtsvalue(o));  /* strings are `values', so are never weak */
    return 0;
  }
  return iswhite(gcvalue(o)) ||
    (ttisuserdata(o) && (!iskey && isfinalized(uvalue(o))));
}
References gcvalue, iscollectable, isfinalized, iswhite, rawtsvalue, stringmark, ttisstring, ttisuserdata, and uvalue.
Referenced by cleartable().
luaC_barrierback()
void luaC_barrierback (lua_State * L, Table * t)
Definition at line 674 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  GCObject *o = obj2gco(t);
  lua_assert(isblack(o) && !isdead(g, o));
  lua_assert(g->gcstate != GCSfinalize && g->gcstate != GCSpause);
  black2gray(o);  /* make table gray (again) */
  t->gclist = g->grayagain;
  g->grayagain = o;
}
References black2gray, G, Table::gclist, GCSfinalize, GCSpause, global_State::gcstate, global_State::grayagain, isblack, isdead, lua_assert, and obj2gco.
luaC_barrierf()
void luaC_barrierf (lua_State * L, GCObject * o, GCObject * v)
Definition at line 661 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(isblack(o) && iswhite(v) && !isdead(g, v) && !isdead(g, o));
  lua_assert(g->gcstate != GCSfinalize && g->gcstate != GCSpause);
  lua_assert(ttype(&o->gch) != LUA_TTABLE);
  /* must keep invariant? */
  if (g->gcstate == GCSpropagate)
    reallymarkobject(g, v);  /* restore invariant */
  else  /* don't mind */
    makewhite(g, o);  /* mark as white just to avoid other barriers */
}
References G, GCObject::gch, GCSfinalize, GCSpause, GCSpropagate, global_State::gcstate, isblack, isdead, iswhite, lua_assert, LUA_TTABLE, makewhite, reallymarkobject(), and ttype.
luaC_callGCTM()
void luaC_callGCTM (lua_State * L)
Definition at line 477 of file lua-5.1.5/src/lgc.c.
{
  while (G(L)->tmudata)
    GCTM(L);
}
References G, and GCTM().
Referenced by callallgcTM().
luaC_freeall()
void luaC_freeall (lua_State * L)
Definition at line 483 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  int i;
  g->currentwhite = WHITEBITS | bitmask(SFIXEDBIT);  /* mask to collect all elements */
  sweepwholelist(L, &g->rootgc);
  for (i = 0; i < g->strt.size; i++)  /* free all string lists */
    sweepwholelist(L, &g->strt.hash[i]);
}
References bitmask, global_State::currentwhite, G, stringtable::hash, global_State::rootgc, SFIXEDBIT, stringtable::size, global_State::strt, sweepwholelist, and WHITEBITS.
Referenced by close_state().
luaC_fullgc()
void luaC_fullgc (lua_State * L)
Definition at line 635 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  if (g->gcstate <= GCSpropagate) {
    /* reset sweep marks to sweep all elements (returning them to white) */
    g->sweepstrgc = 0;
    g->sweepgc = &g->rootgc;
    /* reset other collector lists */
    g->gray = NULL;
    g->grayagain = NULL;
    g->weak = NULL;
    g->gcstate = GCSsweepstring;
  }
  lua_assert(g->gcstate != GCSpause && g->gcstate != GCSpropagate);
  /* finish any pending sweep phase */
  while (g->gcstate != GCSfinalize) {
    lua_assert(g->gcstate == GCSsweepstring || g->gcstate == GCSsweep);
    singlestep(L);
  }
  markroot(L);
  while (g->gcstate != GCSpause) {
    singlestep(L);
  }
  setthreshold(g);
}
References G, GCSfinalize, GCSpause, GCSpropagate, GCSsweep, GCSsweepstring, global_State::gcstate, global_State::gray, global_State::grayagain, lua_assert, markroot(), NULL, global_State::rootgc, setthreshold, singlestep(), global_State::sweepgc, global_State::sweepstrgc, and global_State::weak.
Referenced by growstrtab(), lua_gc(), lua_gc(), luaM_realloc_(), and tryagain().
luaC_link()
void luaC_link (lua_State * L, GCObject * o, lu_byte tt)
Definition at line 685 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  o->gch.next = g->rootgc;
  g->rootgc = o;
  o->gch.marked = luaC_white(g);
  o->gch.tt = tt;
}
References G, GCObject::gch, luaC_white, and global_State::rootgc.
Referenced by luaE_newthread(), luaF_newCclosure(), luaF_newLclosure(), luaF_newproto(), luaF_newupval(), and luaH_new().
luaC_linkupval()
void luaC_linkupval (lua_State * L, UpVal * uv)
Definition at line 694 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  GCObject *o = obj2gco(uv);
  o->gch.next = g->rootgc;  /* link upvalue into `rootgc' list */
  g->rootgc = o;
  if (isgray(o)) {
    if (g->gcstate == GCSpropagate) {
      gray2black(o);  /* closed upvalues need barrier */
      luaC_barrier(L, uv, uv->v);
    }
    else {  /* sweep phase: sweep it (turning it into white) */
      makewhite(g, o);
      lua_assert(g->gcstate != GCSfinalize && g->gcstate != GCSpause);
    }
  }
}
References G, GCObject::gch, GCSfinalize, GCSpause, GCSpropagate, global_State::gcstate, gray2black, isgray, lua_assert, luaC_barrier, makewhite, obj2gco, global_State::rootgc, and UpVal::v.
Referenced by luaF_close().
luaC_separateudata()
size_t luaC_separateudata (lua_State * L, int all)
Definition at line 128 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  size_t deadmem = 0;
  GCObject **p = &g->mainthread->next;
  GCObject *curr;
  while ((curr = *p) != NULL) {
    if (!(iswhite(curr) || all) || isfinalized(gco2u(curr)))
      p = &curr->gch.next;  /* don't bother with them */
    else if (fasttm(L, gco2u(curr)->metatable, TM_GC) == NULL) {
      markfinalized(gco2u(curr));  /* don't need finalization */
      p = &curr->gch.next;
    }
    else {  /* must call its gc method */
      deadmem += sizeudata(gco2u(curr));
      markfinalized(gco2u(curr));
      *p = curr->gch.next;
      /* link `curr' at the end of `tmudata' list */
      if (g->tmudata == NULL)  /* list is empty? */
        g->tmudata = curr->gch.next = curr;  /* creates a circular list */
      else {
        curr->gch.next = g->tmudata->gch.next;
        g->tmudata->gch.next = curr;
        g->tmudata = curr;
      }
    }
  }
  return deadmem;
}
References fasttm, G, GCObject::gch, gco2u, isfinalized, iswhite, global_State::mainthread, markfinalized, NULL, sizeudata, TM_GC, and global_State::tmudata.
Referenced by atomic(), and lua_close().
luaC_step()
void luaC_step (lua_State * L)
Definition at line 610 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  l_mem lim = (GCSTEPSIZE/100) * g->gcstepmul;
  if (lim == 0)
    lim = (MAX_LUMEM-1)/2;  /* no limit */
  g->gcdept += g->totalbytes - g->GCthreshold;
  do {
    lim -= singlestep(L);
    if (g->gcstate == GCSpause)
      break;
  } while (lim > 0);
  if (g->gcstate != GCSpause) {
    if (g->gcdept < GCSTEPSIZE)
      g->GCthreshold = g->totalbytes + GCSTEPSIZE;  /* - lim/g->gcstepmul;*/
    else {
      g->gcdept -= GCSTEPSIZE;
      g->GCthreshold = g->totalbytes;
    }
  }
  else {
    setthreshold(g);
  }
}
References G, global_State::gcdept, GCSpause, global_State::gcstate, global_State::gcstepmul, GCSTEPSIZE, global_State::GCthreshold, MAX_LUMEM, setthreshold, singlestep(), and global_State::totalbytes.
Referenced by lua_gc(), and lua_gc().
markmt()
static void markmt (global_State * g) static
Definition at line 493 of file lua-5.1.5/src/lgc.c.
{
  int i;
  for (i=0; i<NUM_TAGS; i++)
    if (g->mt[i]) markobject(g, g->mt[i]);
}
References markobject, global_State::mt, and NUM_TAGS.
Referenced by atomic(), and markroot().
markroot()
static void markroot (lua_State * L) static
Definition at line 501 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  g->gray = NULL;
  g->grayagain = NULL;
  g->weak = NULL;
  markobject(g, g->mainthread);
  /* make global table be traversed before main stack */
  markvalue(g, gt(g->mainthread));
  markvalue(g, registry(L));
  markmt(g);
  g->gcstate = GCSpropagate;
}
References G, GCSpropagate, global_State::gcstate, global_State::gray, global_State::grayagain, gt, global_State::mainthread, markmt(), markobject, markvalue, NULL, registry, and global_State::weak.
Referenced by luaC_fullgc(), and singlestep().
marktmu()
static void marktmu (global_State * g) static
Definition at line 115 of file lua-5.1.5/src/lgc.c.
{
  GCObject *u = g->tmudata;
  if (u) {
    do {
      u = u->gch.next;
      makewhite(g, u);  /* may be marked, if left from previous GC */
      reallymarkobject(g, u);
    } while (u != g->tmudata);
  }
}
References GCObject::gch, makewhite, reallymarkobject(), and global_State::tmudata.
Referenced by atomic().
propagateall()
static size_t propagateall (global_State * g) static
Definition at line 323 of file lua-5.1.5/src/lgc.c.
{
  size_t m = 0;
  while (g->gray) m += propagatemark(g);
  return m;
}
References global_State::gray, and propagatemark().
Referenced by atomic().
propagatemark()
static l_mem propagatemark (global_State * g) static
Definition at line 277 of file lua-5.1.5/src/lgc.c.
{
  GCObject *o = g->gray;
  lua_assert(isgray(o));
  gray2black(o);
  switch (o->gch.tt) {
    case LUA_TTABLE: {
      Table *h = gco2h(o);
      g->gray = h->gclist;
      if (traversetable(g, h))  /* table is weak? */
        black2gray(o);  /* keep it gray */
      return sizeof(Table) + sizeof(TValue) * h->sizearray +
                             sizeof(Node) * sizenode(h);
    }
    case LUA_TFUNCTION: {
      Closure *cl = gco2cl(o);
      g->gray = cl->c.gclist;
      traverseclosure(g, cl);
      return (cl->c.isC) ? sizeCclosure(cl->c.nupvalues) :
                           sizeLclosure(cl->l.nupvalues);
    }
    case LUA_TTHREAD: {
      lua_State *th = gco2th(o);
      g->gray = th->gclist;
      th->gclist = g->grayagain;
      g->grayagain = o;
      black2gray(o);
      traversestack(g, th);
      return sizeof(lua_State) + sizeof(TValue) * th->stacksize +
                                 sizeof(CallInfo) * th->size_ci;
    }
    case LUA_TPROTO: {
      Proto *p = gco2p(o);
      g->gray = p->gclist;
      traverseproto(g, p);
      return sizeof(Proto) + sizeof(Instruction) * p->sizecode +
                             sizeof(Proto *) * p->sizep +
                             sizeof(TValue) * p->sizek +
                             sizeof(int) * p->sizelineinfo +
                             sizeof(LocVar) * p->sizelocvars +
                             sizeof(TString *) * p->sizeupvalues;
    }
    default: lua_assert(0); return 0;
  }
}
References black2gray, Closure::c, GCObject::gch, Proto::gclist, Table::gclist, lua_State::gclist, gco2cl, gco2h, gco2p, gco2th, global_State::gray, gray2black, global_State::grayagain, isgray, Closure::l, lua_assert, LUA_TFUNCTION, LUA_TPROTO, LUA_TTABLE, LUA_TTHREAD, lua_State::size_ci, Table::sizearray, sizeCclosure, Proto::sizecode, Proto::sizek, sizeLclosure, Proto::sizelineinfo, Proto::sizelocvars, sizenode, Proto::sizep, Proto::sizeupvalues, lua_State::stacksize, traverseclosure(), traverseproto(), traversestack(), and traversetable().
Referenced by propagateall(), and singlestep().
reallymarkobject()
static void reallymarkobject (global_State * g, GCObject * o) static
Definition at line 69 of file lua-5.1.5/src/lgc.c.
{
  lua_assert(iswhite(o) && !isdead(g, o));
  white2gray(o);
  switch (o->gch.tt) {
    case LUA_TSTRING: {
      return;
    }
    case LUA_TUSERDATA: {
      Table *mt = gco2u(o)->metatable;
      gray2black(o);  /* udata are never gray */
      if (mt) markobject(g, mt);
      markobject(g, gco2u(o)->env);
      return;
    }
    case LUA_TUPVAL: {
      UpVal *uv = gco2uv(o);
      markvalue(g, uv->v);
      if (uv->v == &uv->u.value)  /* closed? */
        gray2black(o);  /* open upvalues are never black */
      return;
    }
    case LUA_TFUNCTION: {
      gco2cl(o)->c.gclist = g->gray;
      g->gray = o;
      break;
    }
    case LUA_TTABLE: {
      gco2h(o)->gclist = g->gray;
      g->gray = o;
      break;
    }
    case LUA_TTHREAD: {
      gco2th(o)->gclist = g->gray;
      g->gray = o;
      break;
    }
    case LUA_TPROTO: {
      gco2p(o)->gclist = g->gray;
      g->gray = o;
      break;
    }
    default: lua_assert(0);
  }
}
References GCObject::gch, gco2cl, gco2h, gco2p, gco2th, gco2u, gco2uv, global_State::gray, gray2black, isdead, iswhite, lua_assert, LUA_TFUNCTION, LUA_TPROTO, LUA_TSTRING, LUA_TTABLE, LUA_TTHREAD, LUA_TUPVAL, LUA_TUSERDATA, markobject, markvalue, Table::metatable, UpVal::u, UpVal::v, UpVal::value, and white2gray.
Referenced by luaC_barrierf(), and marktmu().
remarkupvals()
static void remarkupvals (global_State * g) static
Definition at line 515 of file lua-5.1.5/src/lgc.c.
{
  UpVal *uv;
  for (uv = g->uvhead.u.l.next; uv != &g->uvhead; uv = uv->u.l.next) {
    lua_assert(uv->u.l.next->u.l.prev == uv && uv->u.l.prev->u.l.next == uv);
    if (isgray(obj2gco(uv)))
      markvalue(g, uv->v);
  }
}
References isgray, UpVal::l, lua_assert, markvalue, UpVal::next, obj2gco, UpVal::prev, UpVal::u, global_State::uvhead, and UpVal::v.
Referenced by atomic().
removeentry()
static void removeentry (Node * n) static
Definition at line 62 of file lua-5.1.5/src/lgc.c.
{
  lua_assert(ttisnil(gval(n)));
  if (iscollectable(gkey(n)))
    setttype(gkey(n), LUA_TDEADKEY);  /* dead key; remove it */
}
References gkey, gval, iscollectable, lua_assert, LUA_TDEADKEY, setttype, and ttisnil.
Referenced by cleartable(), and traversetable().
singlestep()
static l_mem singlestep (lua_State * L) static
Definition at line 556 of file lua-5.1.5/src/lgc.c.
{
  global_State *g = G(L);
  /*lua_checkmemory(L);*/
  switch (g->gcstate) {
    case GCSpause: {
      markroot(L);  /* start a new collection */
      return 0;
    }
    case GCSpropagate: {
      if (g->gray)
        return propagatemark(g);
      else {  /* no more `gray' objects */
        atomic(L);  /* finish mark phase */
        return 0;
      }
    }
    case GCSsweepstring: {
      lu_mem old = g->totalbytes;
      sweepwholelist(L, &g->strt.hash[g->sweepstrgc++]);
      if (g->sweepstrgc >= g->strt.size)  /* nothing more to sweep? */
        g->gcstate = GCSsweep;  /* end sweep-string phase */
      lua_assert(old >= g->totalbytes);
      g->estimate -= old - g->totalbytes;
      return GCSWEEPCOST;
    }
    case GCSsweep: {
      lu_mem old = g->totalbytes;
      g->sweepgc = sweeplist(L, g->sweepgc, GCSWEEPMAX);
      if (*g->sweepgc == NULL) {  /* nothing more to sweep? */
        checkSizes(L);
        g->gcstate = GCSfinalize;  /* end sweep phase */
      }
      lua_assert(old >= g->totalbytes);
      g->estimate -= old - g->totalbytes;
      return GCSWEEPMAX*GCSWEEPCOST;
    }
    case GCSfinalize: {
      if (g->tmudata) {
        GCTM(L);
        if (g->estimate > GCFINALIZECOST)
          g->estimate -= GCFINALIZECOST;
        return GCFINALIZECOST;
      }
      else {
        g->gcstate = GCSpause;  /* end collection */
        g->gcdept = 0;
        return 0;
      }
    }
    default: lua_assert(0); return 0;
  }
}
References atomic(), checkSizes(), global_State::estimate, G, global_State::gcdept, GCFINALIZECOST, GCSfinalize, GCSpause, GCSpropagate, GCSsweep, GCSsweepstring, global_State::gcstate, GCSWEEPCOST, GCSWEEPMAX, GCTM(), global_State::gray, stringtable::hash, lua_assert, markroot(), NULL, propagatemark(), stringtable::size, global_State::strt, global_State::sweepgc, sweeplist(), global_State::sweepstrgc, sweepwholelist, global_State::tmudata, and global_State::totalbytes.
Referenced by luaC_fullgc(), and luaC_step().
sweeplist()
static GCObject ** sweeplist (lua_State * L, GCObject ** p, lu_mem count) static
Definition at line 407 of file lua-5.1.5/src/lgc.c.
{
  GCObject *curr;
  global_State *g = G(L);
  int deadmask = otherwhite(g);
  while ((curr = *p) != NULL && count-- > 0) {
    if (curr->gch.tt == LUA_TTHREAD)  /* sweep open upvalues of each thread */
      sweepwholelist(L, &gco2th(curr)->openupval);
    if ((curr->gch.marked ^ WHITEBITS) & deadmask) {  /* not dead? */
      lua_assert(!isdead(g, curr) || testbit(curr->gch.marked, FIXEDBIT));
      makewhite(g, curr);  /* make it white (for next cycle) */
      p = &curr->gch.next;
    }
    else {  /* must erase `curr' */
      lua_assert(isdead(g, curr) || deadmask == bitmask(SFIXEDBIT));
      *p = curr->gch.next;
      if (curr == g->rootgc)  /* is the first element of the list? */
        g->rootgc = curr->gch.next;  /* adjust first */
      freeobj(L, curr);
    }
  }
  return p;
}
References bitmask, FIXEDBIT, freeobj(), G, GCObject::gch, gco2th, isdead, lua_assert, LUA_TTHREAD, makewhite, NULL, otherwhite, global_State::rootgc, SFIXEDBIT, sweepwholelist, testbit, and WHITEBITS.
Referenced by singlestep().
traverseclosure()
static void traverseclosure (global_State * g, Closure * cl) static
Definition at line 224 of file lua-5.1.5/src/lgc.c.
{
  markobject(g, cl->c.env);
  if (cl->c.isC) {
    int i;
    for (i=0; i<cl->c.nupvalues; i++)  /* mark its upvalues */
      markvalue(g, &cl->c.upvalue[i]);
  }
  else {
    int i;
    lua_assert(cl->l.nupvalues == cl->l.p->nups);
    markobject(g, cl->l.p);
    for (i=0; i<cl->l.nupvalues; i++)  /* mark its upvalues */
      markobject(g, cl->l.upvals[i]);
  }
}
References Closure::c, Closure::l, lua_assert, markobject, markvalue, Proto::nups, LClosure::p, LClosure::upvals, and CClosure::upvalue.
Referenced by propagatemark().
traverseproto()
static void traverseproto (global_State * g, Proto * f) static
Definition at line 203 of file lua-5.1.5/src/lgc.c.
{
  int i;
  if (f->source) stringmark(f->source);
  for (i=0; i<f->sizek; i++)  /* mark literals */
    markvalue(g, &f->k[i]);
  for (i=0; i<f->sizeupvalues; i++) {  /* mark upvalue names */
    if (f->upvalues[i])
      stringmark(f->upvalues[i]);
  }
  for (i=0; i<f->sizep; i++) {  /* mark nested protos */
    if (f->p[i])
      markobject(g, f->p[i]);
  }
  for (i=0; i<f->sizelocvars; i++) {  /* mark local-variable names */
    if (f->locvars[i].varname)
      stringmark(f->locvars[i].varname);
  }
}
References Proto::k, Proto::locvars, markobject, markvalue, Proto::p, Proto::sizek, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, stringmark, Proto::upvalues, and LocVar::varname.
Referenced by propagatemark().
traversestack()
static void traversestack (global_State * g, lua_State * l) static
Definition at line 256 of file lua-5.1.5/src/lgc.c.
{
  StkId o, lim;
  CallInfo *ci;
  markvalue(g, gt(l));
  lim = l->top;
  for (ci = l->base_ci; ci <= l->ci; ci++) {
    lua_assert(ci->top <= l->stack_last);
    if (lim < ci->top) lim = ci->top;
  }
  for (o = l->stack; o < l->top; o++)
    markvalue(g, o);
  for (; o <= lim; o++)
    setnilvalue(o);
  checkstacksizes(l, lim);
}
References lua_State::base_ci, checkstacksizes(), lua_State::ci, gt, lua_assert, markvalue, setnilvalue, lua_State::stack, lua_State::stack_last, CallInfo::top, and lua_State::top.
Referenced by propagatemark().
traversetable()
static int traversetable (global_State * g, Table * h) static
Definition at line 158 of file lua-5.1.5/src/lgc.c.
{
  int i;
  int weakkey = 0;
  int weakvalue = 0;
  const TValue *mode;
  if (h->metatable)
    markobject(g, h->metatable);
  mode = gfasttm(g, h->metatable, TM_MODE);
  if (mode && ttisstring(mode)) {  /* is there a weak mode? */
    weakkey = (strchr(svalue(mode), 'k') != NULL);
    weakvalue = (strchr(svalue(mode), 'v') != NULL);
    if (weakkey || weakvalue) {  /* is really weak? */
      h->marked &= ~(KEYWEAK | VALUEWEAK);  /* clear bits */
      h->marked |= cast_byte((weakkey << KEYWEAKBIT) |
                             (weakvalue << VALUEWEAKBIT));
      h->gclist = g->weak;  /* must be cleared after GC, ... */
      g->weak = obj2gco(h);  /* ... so put in the appropriate list */
    }
  }
  if (weakkey && weakvalue) return 1;
  if (!weakvalue) {
    i = h->sizearray;
    while (i--)
      markvalue(g, &h->array[i]);
  }
  i = sizenode(h);
  while (i--) {
    Node *n = gnode(h, i);
    lua_assert(ttype(gkey(n)) != LUA_TDEADKEY || ttisnil(gval(n)));
    if (ttisnil(gval(n)))
      removeentry(n);  /* remove empty entries */
    else {
      lua_assert(!ttisnil(gkey(n)));
      if (!weakkey) markvalue(g, gkey(n));
      if (!weakvalue) markvalue(g, gval(n));
    }
  }
  return weakkey || weakvalue;
}
References Table::array, cast_byte, Table::gclist, gfasttm, gkey, gnode, gval, KEYWEAK, KEYWEAKBIT, lua_assert, LUA_TDEADKEY, markobject, markvalue, Table::metatable, NULL, obj2gco, removeentry(), Table::sizearray, sizenode, svalue, TM_MODE, ttisnil, ttisstring, ttype, VALUEWEAK, VALUEWEAKBIT, and global_State::weak.
Referenced by propagatemark().