Github User Fetcher: ltable.h File Reference
ltable.h File Reference
#include "lobject.h"
Macros
#define gnode(t, i) (&(t)->node[i])
#define gval(n) (&(n)->i_val)
#define gnext(n) ((n)->u.next)
#define invalidateTMcache(t) ((t)->flags &= ~maskflags)
#define isdummy(t) ((t)->lastfree == NULL)
#define allocsizenode(t) (isdummy(t) ? 0 : sizenode(t))
#define nodefromval(v) cast(Node *, (v))
Functions
LUAI_FUNC const TValue * luaH_getint (Table *t, lua_Integer key)
LUAI_FUNC void luaH_setint (lua_State *L, Table *t, lua_Integer key, TValue *value)
LUAI_FUNC const TValue * luaH_getshortstr (Table *t, TString *key)
LUAI_FUNC const TValue * luaH_getstr (Table *t, TString *key)
LUAI_FUNC const TValue * luaH_get (Table *t, const TValue *key)
LUAI_FUNC void luaH_newkey (lua_State *L, Table *t, const TValue *key, TValue *value)
LUAI_FUNC void luaH_set (lua_State *L, Table *t, const TValue *key, TValue *value)
LUAI_FUNC void luaH_finishset (lua_State *L, Table *t, const TValue *key, const TValue *slot, TValue *value)
LUAI_FUNC Table * luaH_new (lua_State *L)
LUAI_FUNC void luaH_resize (lua_State *L, Table *t, unsigned int nasize, unsigned int nhsize)
LUAI_FUNC void luaH_resizearray (lua_State *L, Table *t, unsigned int nasize)
LUAI_FUNC void luaH_free (lua_State *L, Table *t)
LUAI_FUNC int luaH_next (lua_State *L, Table *t, StkId key)
LUAI_FUNC lua_Unsigned luaH_getn (Table *t)
LUAI_FUNC unsigned int luaH_realasize (const Table *t)
Macro Definition Documentation
allocsizenode
#define allocsizenode (t) (isdummy(t) ? 0 : sizenode(t))
Definition at line 31 of file lua-5.4.3/src/ltable.h.
gnext
#define gnext (n) ((n)->u.next)
Definition at line 15 of file lua-5.4.3/src/ltable.h.
gnode
#define gnode (t, i) (&(t)->node[i])
Definition at line 13 of file lua-5.4.3/src/ltable.h.
gval
#define gval (n) (&(n)->i_val)
Definition at line 14 of file lua-5.4.3/src/ltable.h.
invalidateTMcache
#define invalidateTMcache (t) ((t)->flags &= ~maskflags)
Definition at line 23 of file lua-5.4.3/src/ltable.h.
isdummy
#define isdummy (t) ((t)->lastfree == NULL)
Definition at line 27 of file lua-5.4.3/src/ltable.h.
nodefromval
#define nodefromval (v) cast(Node *, (v))
Definition at line 35 of file lua-5.4.3/src/ltable.h.
Referenced by findindex(), and luaX_newstring().
Function Documentation
luaH_finishset()
LUAI_FUNC void luaH_finishset (lua_State * L, Table * t, const TValue * key, const TValue * slot, TValue * value)
Definition at line 800 of file lua-5.4.3/src/ltable.c.
{
  if (isabstkey(slot))
    luaH_newkey(L, t, key, value);
  else
    setobj2t(L, cast(TValue *, slot), value);
}
References cast, isabstkey, luaH_newkey(), setobj2t, and value.
Referenced by addk(), luaH_set(), luaV_finishset(), and luaX_newstring().
luaH_free()
LUAI_FUNC void luaH_free (lua_State * L, Table * t)
Definition at line 374 of file lua-5.1.5/src/ltable.c.
{
  if (t->node != dummynode)
    luaM_freearray(L, t->node, sizenode(t), Node);
  luaM_freearray(L, t->array, t->sizearray, TValue);
  luaM_free(L, t);
}
References Table::array, cast, dummynode, freehash(), isdummy, luaH_realasize(), luaM_free, luaM_freearray, Table::node, Table::sizearray, and sizenode.
Referenced by freeobj(), freeobj(), freeobj(), and freeobj().
luaH_get()
LUAI_FUNC const TValue * luaH_get (Table * t, const TValue * key)
Definition at line 469 of file lua-5.1.5/src/ltable.c.
{
  switch (ttype(key)) {
    case LUA_TNIL: return luaO_nilobject;
    case LUA_TSTRING: return luaH_getstr(t, rawtsvalue(key));
    case LUA_TNUMBER: {
      int k;
      lua_Number n = nvalue(key);
      lua_number2int(k, n);
      if (luai_numeq(cast_num(k), nvalue(key))) /* index is int? */
        return luaH_getnum(t, k);  /* use specialized version */
      /* else go through */
    }
    default: {
      Node *n = mainposition(t, key);
      do {  /* check whether `key' is somewhere in the chain */
        if (luaO_rawequalObj(key2tval(n), key))
          return gval(n);  /* that's it */
        else n = gnext(n);
      } while (n);
      return luaO_nilobject;
    }
  }
}
References absentkey, cast_num, F2Ieq, fltvalue, getgeneric(), getgeneric(), gkey, gnext, gval, ivalue, key2tval, lua_number2int, LUA_TNIL, LUA_TNUMBER, LUA_TNUMFLT, LUA_TNUMINT, LUA_TSHRSTR, LUA_TSTRING, LUA_VNIL, LUA_VNUMFLT, LUA_VNUMINT, LUA_VSHRSTR, luaH_getint(), luaH_getint(), luaH_getnum(), luaH_getshortstr(), luaH_getstr(), luai_numeq, luaO_nilobject, luaO_rawequalObj(), luaV_flttointeger(), luaV_rawequalobj, luaV_tointeger(), mainposition(), mainposition(), nvalue, rawtsvalue, tsvalue, ttype, and ttypetag.
Referenced by addk(), lua_gettable(), lua_rawget(), lua_rawgetp(), lua_settable(), luaH_set(), luaH_set(), luaV_execute(), luaV_finishget(), luaV_finishset(), luaV_finishset(), luaV_gettable(), and luaV_settable().
luaH_getint()
LUAI_FUNC const TValue * luaH_getint (Table * t, lua_Integer key)
Definition at line 516 of file lua-5.3.6/src/ltable.c.
{
  /* (1 <= key && key <= t->sizearray) */
  if (l_castS2U(key) - 1 < t->sizearray)
    return &t->array[key - 1];
  else {
    Node *n = hashint(t, key);
    for (;;) {  /* check whether 'key' is somewhere in the chain */
      if (ttisinteger(gkey(n)) && ivalue(gkey(n)) == key)
        return gval(n);  /* that's it */
      else {
        int nx = gnext(n);
        if (nx == 0) break;
        n += nx;
      }
    }
    return luaO_nilobject;
  }
}
References absentkey, Table::alimit, Table::array, cast_uint, gkey, gnext, gval, hashint, ivalue, keyisinteger, keyival, l_castS2U, limitequalsasize, luaH_realasize(), luaO_nilobject, Table::sizearray, and ttisinteger.
Referenced by hash_search(), luaH_get(), luaH_getn(), luaH_setint(), and unbound_search().
luaH_getn()
LUAI_FUNC lua_Unsigned luaH_getn (Table * t)
Definition at line 560 of file lua-5.1.5/src/ltable.c.
{
  unsigned int j = t->sizearray;
  if (j > 0 && ttisnil(&t->array[j - 1])) {
    /* there is a boundary in the array part: (binary) search for it */
    unsigned int i = 0;
    while (j - i > 1) {
      unsigned int m = (i+j)/2;
      if (ttisnil(&t->array[m - 1])) j = m;
      else i = m;
    }
    return i;
  }
  /* else must find a boundary in hash part */
  else if (t->node == dummynode)  /* hash part is empty? */
    return j;  /* that is easy... */
  else return unbound_search(t, j);
}
References Table::alimit, Table::array, binsearch(), cast, dummynode, hash_search(), isdummy, isempty, ispow2, ispow2realasize(), limitequalsasize, lua_assert, luaH_getint(), luaH_realasize(), Table::node, setnorealasize, Table::sizearray, ttisnil, unbound_search(), unbound_search(), and unbound_search().
Referenced by lua_objlen(), lua_rawlen(), luaV_execute(), and luaV_objlen().
luaH_getshortstr()
LUAI_FUNC const TValue * luaH_getshortstr (Table * t, TString * key)
Definition at line 539 of file lua-5.3.6/src/ltable.c.
{
  Node *n = hashstr(t, key);
  lua_assert(key->tt == LUA_TSHRSTR);
  for (;;) {  /* check whether 'key' is somewhere in the chain */
    const TValue *k = gkey(n);
    if (ttisshrstring(k) && eqshrstr(tsvalue(k), key))
      return gval(n);  /* that's it */
    else {
      int nx = gnext(n);
      if (nx == 0)
        return luaO_nilobject;  /* not found */
      n += nx;
    }
  }
}
References absentkey, eqshrstr, gkey, gnext, gval, hashstr, keyisshrstr, keystrval, lua_assert, LUA_TSHRSTR, LUA_VSHRSTR, luaO_nilobject, tsvalue, and ttisshrstring.
Referenced by luaH_get(), luaH_getstr(), luaT_gettm(), luaT_gettmbyobj(), luaT_objtypename(), and luaV_execute().
luaH_getstr()
LUAI_FUNC const TValue * luaH_getstr (Table * t, TString * key)
Definition at line 455 of file lua-5.1.5/src/ltable.c.
{
  Node *n = hashstr(t, key);
  do {  /* check whether `key' is somewhere in the chain */
    if (ttisstring(gkey(n)) && rawtsvalue(gkey(n)) == key)
      return gval(n);  /* that's it */
    else n = gnext(n);
  } while (n);
  return luaO_nilobject;
}
References cast, eqshrstr, getgeneric(), getgeneric(), gkey, gnext, gval, hashstr, lua_assert, LUA_TSHRSTR, LUA_VSHRSTR, luaH_getshortstr(), luaO_nilobject, NULL, rawtsvalue, setsvalue, TString::tsv, ttisshrstring, and ttisstring.
Referenced by auxgetstr(), auxgetstr(), auxsetstr(), auxsetstr(), luaH_get(), luaH_setstr(), luaT_gettm(), luaT_gettmbyobj(), luaV_execute(), luaV_execute(), and luaX_newstring().
luaH_new()
LUAI_FUNC Table * luaH_new (lua_State * L)
Definition at line 368 of file lua-5.2.4/src/ltable.c.
{
  Table *t = &luaC_newobj(L, LUA_TTABLE, sizeof(Table), NULL, 0)->h;
  t->metatable = NULL;
  t->flags = cast_byte(~0);
  t->array = NULL;
  t->sizearray = 0;
  setnodevector(L, t, 0);
  return t;
}
References Table::alimit, Table::array, cast_byte, Table::flags, gco2t, GCObject::h, LUA_TTABLE, LUA_VTABLE, luaC_newobj(), maskflags, Table::metatable, NULL, setnodevector(), setnodevector(), setnodevector(), and Table::sizearray.
luaH_newkey()
LUAI_FUNC void luaH_newkey (lua_State * L, Table * t, const TValue * key, TValue * value)
Definition at line 654 of file lua-5.4.3/src/ltable.c.
{
  Node *mp;
  TValue aux;
  if (l_unlikely(ttisnil(key)))
    luaG_runerror(L, "table index is nil");
  else if (ttisfloat(key)) {
    lua_Number f = fltvalue(key);
    lua_Integer k;
    if (luaV_flttointeger(f, &k, F2Ieq)) {  /* does key fit in an integer? */
      setivalue(&aux, k);
      key = &aux;  /* insert it as an integer */
    }
    else if (l_unlikely(luai_numisnan(f)))
      luaG_runerror(L, "table index is NaN");
  }
  if (ttisnil(value))
    return;  /* do not insert nil values */
  mp = mainpositionTV(t, key);
  if (!isempty(gval(mp)) || isdummy(t)) {  /* main position is taken? */
    Node *othern;
    Node *f = getfreepos(t);  /* get a free place */
    if (f == NULL) {  /* cannot find a free place? */
      rehash(L, t, key);  /* grow table */
      /* whatever called 'newkey' takes care of TM cache */
      luaH_set(L, t, key, value);  /* insert key into grown table */
      return;
    }
    lua_assert(!isdummy(t));
    othern = mainposition(t, keytt(mp), &keyval(mp));
    if (othern != mp) {  /* is colliding node out of its main position? */
      /* yes; move colliding node into free position */
      while (othern + gnext(othern) != mp)  /* find previous */
        othern += gnext(othern);
      gnext(othern) = cast_int(f - othern);  /* rechain to point to 'f' */
      *f = *mp;  /* copy colliding node into free pos. (mp->next also goes) */
      if (gnext(mp) != 0) {
        gnext(f) += cast_int(mp - f);  /* correct 'next' */
        gnext(mp) = 0;  /* now 'mp' is free */
      }
      setempty(gval(mp));
    }
    else {  /* colliding node is in its own main position */
      /* new node will go into free position */
      if (gnext(mp) != 0)
        gnext(f) = cast_int((mp + gnext(mp)) - f);  /* chain new position */
      else lua_assert(gnext(f) == 0);
      gnext(mp) = cast_int(f - mp);
      mp = f;
    }
  }
  setnodekey(L, mp, key);
  luaC_barrierback(L, obj2gco(t), key);
  lua_assert(isempty(gval(mp)));
  setobj2t(L, gval(mp), value);
}
References cast_int, F2Ieq, fltvalue, getfreepos(), gnext, gval, isdummy, isempty, keytt, keyval, lua_assert, luaC_barrierback, luaG_runerror(), luaH_set(), luai_numisnan, luaV_flttointeger(), mainposition(), mainpositionTV(), NULL, obj2gco, rehash(), setempty, setivalue, setnodekey, setobj2t, ttisfloat, ttisnil, and value.
Referenced by luaH_finishset(), and luaH_setint().
luaH_next()
LUAI_FUNC int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 162 of file lua-5.1.5/src/ltable.c.
{
  int i = findindex(L, t, key);  /* find original element */
  for (i++; i < t->sizearray; i++) {  /* try first array part */
    if (!ttisnil(&t->array[i])) {  /* a non-nil value? */
      setnvalue(key, cast_num(i+1));
      setobj2s(L, key+1, &t->array[i]);
      return 1;
    }
  }
  for (i -= t->sizearray; i < sizenode(t); i++) {  /* then hash part */
    if (!ttisnil(gval(gnode(t, i)))) {  /* a non-nil value? */
      setobj2s(L, key, key2tval(gnode(t, i)));
      setobj2s(L, key+1, gval(gnode(t, i)));
      return 1;
    }
  }
  return 0;  /* no more elements */
}
References Table::array, cast_int, cast_num, findindex(), findindex(), findindex(), findindex(), getnodekey, gkey, gnode, gval, isempty, key2tval, luaH_realasize(), s2v, setivalue, setnvalue, setobj2s, Table::sizearray, sizenode, and ttisnil.
Referenced by lua_next().
luaH_realasize()
LUAI_FUNC unsigned int luaH_realasize (const Table * t)
Definition at line 241 of file lua-5.4.3/src/ltable.c.
{
  if (limitequalsasize(t))
    return t->alimit;  /* this is the size */
  else {
    unsigned int size = t->alimit;
    /* compute the smallest power of 2 not smaller than 'n' */
    size |= (size >> 1);
    size |= (size >> 2);
    size |= (size >> 4);
    size |= (size >> 8);
    size |= (size >> 16);
#if (UINT_MAX >> 30) > 3
    size |= (size >> 32);  /* unsigned int has more than 32 bits */
#endif
    size++;
    lua_assert(ispow2(size) && size/2 < t->alimit && t->alimit < size);
    return size;
  }
}
References Table::alimit, ispow2, limitequalsasize, and lua_assert.
Referenced by clearbyvalues(), luaH_free(), luaH_getint(), luaH_getn(), luaH_next(), luaV_execute(), setlimittosize(), traverseephemeron(), and traversestrongtable().
luaH_resize()
LUAI_FUNC void luaH_resize (lua_State * L, Table * t, unsigned int nasize, unsigned int nhsize)
Definition at line 347 of file lua-5.3.6/src/ltable.c.
{
  unsigned int i;
  int j;
  AuxsetnodeT asn;
  unsigned int oldasize = t->sizearray;
  int oldhsize = allocsizenode(t);
  Node *nold = t->node;  /* save old hash ... */
  if (nasize > oldasize)  /* array part must grow? */
    setarrayvector(L, t, nasize);
  /* create new hash part with appropriate size */
  asn.t = t; asn.nhsize = nhsize;
  if (luaD_rawrunprotected(L, auxsetnode, &asn) != LUA_OK) {  /* mem. error? */
    setarrayvector(L, t, oldasize);  /* array back to its original size */
    luaD_throw(L, LUA_ERRMEM);  /* rethrow memory error */
  }
  if (nasize < oldasize) {  /* array part must shrink? */
    t->sizearray = nasize;
    /* re-insert elements from vanishing slice */
    for (i=nasize; i<oldasize; i++) {
      if (!ttisnil(&t->array[i]))
        luaH_setint(L, t, i + 1, &t->array[i]);
    }
    /* shrink array */
    luaM_reallocvector(L, t->array, oldasize, nasize, TValue);
  }
  /* re-insert elements from hash part */
  for (j = oldhsize - 1; j >= 0; j--) {
    Node *old = nold + j;
    if (!ttisnil(gval(old))) {
      /* doesn't need barrier/invalidate cache, as entry was
         already present in the table */
      setobjt2t(L, luaH_set(L, t, gkey(old)), gval(old));
    }
  }
  if (oldhsize > 0)  /* not the dummy node? */
    luaM_freearray(L, nold, cast(size_t, oldhsize)); /* free old hash */
}
References Table::alimit, allocsizenode, Table::array, auxsetnode(), cast, exchangehashpart(), freehash(), gkey, gval, isempty, LUA_ERRMEM, LUA_OK, luaD_rawrunprotected(), luaD_throw(), luaH_set(), luaH_setint(), luaM_error, luaM_freearray, luaM_reallocvector, AuxsetnodeT::nhsize, Table::node, NULL, reinsert(), setarrayvector(), setempty, setlimittosize(), setnodevector(), setobjt2t, Table::sizearray, AuxsetnodeT::t, and ttisnil.
Referenced by luaH_resizearray(), rehash(), and rehash().
luaH_resizearray()
LUAI_FUNC void luaH_resizearray (lua_State * L, Table * t, unsigned int nasize)
Definition at line 387 of file lua-5.3.6/src/ltable.c.
{
  int nsize = allocsizenode(t);
  luaH_resize(L, t, nasize, nsize);
}
References allocsizenode, luaH_resize(), and luaH_resize().
luaH_set()
LUAI_FUNC void luaH_set (lua_State * L, Table * t, const TValue * key, TValue * value)
Definition at line 813 of file lua-5.4.3/src/ltable.c.
{
  const TValue *slot = luaH_get(t, key);
  luaH_finishset(L, t, key, slot, value);
}
References luaH_finishset(), luaH_get(), and value.
Referenced by luaH_newkey(), and reinsert().
luaH_setint()
LUAI_FUNC void luaH_setint (lua_State * L, Table * t, lua_Integer key, TValue * value)
Definition at line 618 of file lua-5.3.6/src/ltable.c.
{
  const TValue *p = luaH_getint(t, key);
  TValue *cell;
  if (p != luaO_nilobject)
    cell = cast(TValue *, p);
  else {
    TValue k;
    setivalue(&k, key);
    cell = luaH_newkey(L, t, &k);
  }
  setobj2t(L, cell, value);
}
References cast, isabstkey, luaH_getint(), luaH_newkey(), luaH_newkey(), luaO_nilobject, setivalue, setobj2t, and value.
Referenced by luaH_resize(), and luaH_resize().