Github User Fetcher: lundump.c File Reference
lundump.c File Reference
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstring.h"
#include "lundump.h"
#include "lzio.h"
Data Structures
struct LoadState
Macros
#define lundump_c
#define LUA_CORE
#define LoadMem(S, b, n, size) LoadBlock(S,b,(n)*(size))
#define LoadByte(S) (lu_byte)LoadChar(S)
#define LoadVar(S, x) LoadMem(S,&x,1,sizeof(x))
#define LoadVector(S, b, n, size) LoadMem(S,b,n,size)
#define luai_verifycode(L, b, f) /* empty */
#define N0 LUAC_HEADERSIZE
#define N1 (sizeof(LUA_SIGNATURE)-sizeof(char))
#define N2 N1+2
#define N3 N2+6
#define MYINT(s) (s[0]-'0')
#define VERSION MYINT(LUA_VERSION_MAJOR)*16+MYINT(LUA_VERSION_MINOR)
#define FORMAT 0 /* this is the official format */
Functions
static l_noret error (LoadState *S, const char *why)
static void LoadBlock (LoadState *S, void *b, size_t size)
static int LoadChar (LoadState *S)
static int LoadInt (LoadState *S)
static lua_Number LoadNumber (LoadState *S)
static TString * LoadString (LoadState *S)
static void LoadCode (LoadState *S, Proto *f)
static void LoadFunction (LoadState *S, Proto *f)
static void LoadConstants (LoadState *S, Proto *f)
static void LoadUpvalues (LoadState *S, Proto *f)
static void LoadDebug (LoadState *S, Proto *f)
static void LoadHeader (LoadState *S)
Closure * luaU_undump (lua_State *L, ZIO *Z, Mbuffer *buff, const char *name)
void luaU_header (lu_byte *h)
Macro Definition Documentation
FORMAT
#define FORMAT 0 /* this is the official format */
Definition at line 237 of file lua-5.2.4/src/lundump.c.
Referenced by luaU_header().
LoadByte
#define LoadByte (S) (lu_byte)LoadChar(S)
Definition at line 37 of file lua-5.2.4/src/lundump.c.
Referenced by LoadFunction(), and LoadUpvalues().
LoadMem
#define LoadMem (S, b, n, size) LoadBlock(S,b,(n)*(size))
Definition at line 36 of file lua-5.2.4/src/lundump.c.
LoadVar
#define LoadVar (S, x) LoadMem(S,&x,1,sizeof(x))
Definition at line 38 of file lua-5.2.4/src/lundump.c.
Referenced by LoadChar(), LoadInt(), LoadNumber(), and LoadString().
LoadVector
#define LoadVector (S, b, n, size) LoadMem(S,b,n,size)
Definition at line 39 of file lua-5.2.4/src/lundump.c.
Referenced by LoadCode(), and LoadDebug().
LUA_CORE
#define LUA_CORE
Definition at line 10 of file lua-5.2.4/src/lundump.c.
luai_verifycode
#define luai_verifycode (L, b, f) /* empty */
Definition at line 42 of file lua-5.2.4/src/lundump.c.
Referenced by luaU_undump().
lundump_c
#define lundump_c
Definition at line 9 of file lua-5.2.4/src/lundump.c.
MYINT
#define MYINT (s) (s[0]-'0')
Definition at line 235 of file lua-5.2.4/src/lundump.c.
N0
#define N0 LUAC_HEADERSIZE
Definition at line 185 of file lua-5.2.4/src/lundump.c.
Referenced by LoadHeader().
N1
#define N1 (sizeof(LUA_SIGNATURE)-sizeof(char))
Definition at line 186 of file lua-5.2.4/src/lundump.c.
Referenced by LoadHeader().
N2
#define N2 N1+2
Definition at line 187 of file lua-5.2.4/src/lundump.c.
Referenced by LoadHeader().
N3
#define N3 N2+6
Definition at line 188 of file lua-5.2.4/src/lundump.c.
Referenced by LoadHeader().
VERSION
#define VERSION MYINT(LUA_VERSION_MAJOR)*16+MYINT(LUA_VERSION_MINOR)
Definition at line 236 of file lua-5.2.4/src/lundump.c.
Referenced by luaU_header().
Function Documentation
error()
static l_noret error (LoadState * S, const char * why) static
Definition at line 30 of file lua-5.2.4/src/lundump.c.
{
 luaO_pushfstring(S->L,"%s: %s precompiled chunk",S->name,why);
 luaD_throw(S->L,LUA_ERRSYNTAX);
}
References LUA_ERRSYNTAX, luaD_throw(), luaO_pushfstring(), and S.
Referenced by LoadBlock(), LoadHeader(), and LoadInt().
LoadBlock()
static void LoadBlock (LoadState * S, void * b, size_t size) static
Definition at line 45 of file lua-5.2.4/src/lundump.c.
{
 if (luaZ_read(S->Z,b,size)!=0) error(S,"truncated");
}
References error(), luaZ_read(), and S.
Referenced by LoadHeader(), and LoadString().
LoadChar()
static int LoadChar (LoadState * S) static
Definition at line 50 of file lua-5.2.4/src/lundump.c.
{
 char x;
 LoadVar(S,x);
 return x;
}
References LoadVar, and S.
Referenced by LoadConstants().
LoadCode()
static void LoadCode (LoadState * S, Proto * f) static
Definition at line 86 of file lua-5.2.4/src/lundump.c.
{
 int n=LoadInt(S);
 f->code=luaM_newvector(S->L,n,Instruction);
 f->sizecode=n;
 LoadVector(S,f->code,n,sizeof(Instruction));
}
References Proto::code, LoadInt(), LoadVector, luaM_newvector, S, and Proto::sizecode.
Referenced by LoadFunction().
LoadConstants()
static void LoadConstants (LoadState * S, Proto * f) static
Definition at line 96 of file lua-5.2.4/src/lundump.c.
{
 int i,n;
 n=LoadInt(S);
 f->k=luaM_newvector(S->L,n,TValue);
 f->sizek=n;
 for (i=0; i<n; i++) setnilvalue(&f->k[i]);
 for (i=0; i<n; i++)
 {
  TValue* o=&f->k[i];
  int t=LoadChar(S);
  switch (t)
  {
   case LUA_TNIL:
    setnilvalue(o);
    break;
   case LUA_TBOOLEAN:
    setbvalue(o,LoadChar(S));
    break;
   case LUA_TNUMBER:
    setnvalue(o,LoadNumber(S));
    break;
   case LUA_TSTRING:
    setsvalue2n(S->L,o,LoadString(S));
    break;
    default: lua_assert(0);
  }
 }
 n=LoadInt(S);
 f->p=luaM_newvector(S->L,n,Proto*);
 f->sizep=n;
 for (i=0; i<n; i++) f->p[i]=NULL;
 for (i=0; i<n; i++)
 {
  f->p[i]=luaF_newproto(S->L);
  LoadFunction(S,f->p[i]);
 }
}
References Proto::k, LoadChar(), LoadFunction(), LoadInt(), LoadNumber(), LoadString(), lua_assert, LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, LUA_TSTRING, luaF_newproto(), luaM_newvector, NULL, Proto::p, S, setbvalue, setnilvalue, setnvalue, setsvalue2n, Proto::sizek, and Proto::sizep.
Referenced by LoadFunction().
LoadDebug()
static void LoadDebug (LoadState * S, Proto * f) static
Definition at line 149 of file lua-5.2.4/src/lundump.c.
{
 int i,n;
 f->source=LoadString(S);
 n=LoadInt(S);
 f->lineinfo=luaM_newvector(S->L,n,int);
 f->sizelineinfo=n;
 LoadVector(S,f->lineinfo,n,sizeof(int));
 n=LoadInt(S);
 f->locvars=luaM_newvector(S->L,n,LocVar);
 f->sizelocvars=n;
 for (i=0; i<n; i++) f->locvars[i].varname=NULL;
 for (i=0; i<n; i++)
 {
  f->locvars[i].varname=LoadString(S);
  f->locvars[i].startpc=LoadInt(S);
  f->locvars[i].endpc=LoadInt(S);
 }
 n=LoadInt(S);
 for (i=0; i<n; i++) f->upvalues[i].name=LoadString(S);
}
References LocVar::endpc, Proto::lineinfo, LoadInt(), LoadString(), LoadVector, Proto::locvars, luaM_newvector, NULL, S, Proto::sizelineinfo, Proto::sizelocvars, Proto::source, LocVar::startpc, Proto::upvalues, and LocVar::varname.
Referenced by LoadFunction().
LoadFunction()
static void LoadFunction (LoadState * S, Proto * f) static
Definition at line 171 of file lua-5.2.4/src/lundump.c.
{
 f->linedefined=LoadInt(S);
 f->lastlinedefined=LoadInt(S);
 f->numparams=LoadByte(S);
 f->is_vararg=LoadByte(S);
 f->maxstacksize=LoadByte(S);
 LoadCode(S,f);
 LoadConstants(S,f);
 LoadUpvalues(S,f);
 LoadDebug(S,f);
}
References Proto::is_vararg, Proto::lastlinedefined, Proto::linedefined, LoadByte, LoadCode(), LoadConstants(), LoadDebug(), LoadInt(), LoadUpvalues(), Proto::maxstacksize, Proto::numparams, and S.
Referenced by LoadConstants(), and luaU_undump().
LoadHeader()
static void LoadHeader (LoadState * S) static
Definition at line 190 of file lua-5.2.4/src/lundump.c.
{
 lu_byte h[LUAC_HEADERSIZE];
 lu_byte s[LUAC_HEADERSIZE];
 luaU_header(h);
 memcpy(s,h,sizeof(char));          /* first char already read */
 LoadBlock(S,s+sizeof(char),LUAC_HEADERSIZE-sizeof(char));
 if (memcmp(h,s,N0)==0) return;
 if (memcmp(h,s,N1)!=0) error(S,"not a");
 if (memcmp(h,s,N2)!=0) error(S,"version mismatch in");
 if (memcmp(h,s,N3)!=0) error(S,"incompatible"); else error(S,"corrupted");
}
References error(), LoadBlock(), LUAC_HEADERSIZE, luaU_header(), N0, N1, N2, N3, S, and s.
Referenced by luaU_undump().
LoadInt()
static int LoadInt (LoadState * S) static
Definition at line 57 of file lua-5.2.4/src/lundump.c.
{
 int x;
 LoadVar(S,x);
 if (x<0) error(S,"corrupted");
 return x;
}
References error(), LoadVar, and S.
Referenced by LoadCode(), LoadConstants(), LoadDebug(), LoadFunction(), and LoadUpvalues().
LoadNumber()
static lua_Number LoadNumber (LoadState * S) static
Definition at line 65 of file lua-5.2.4/src/lundump.c.
{
 lua_Number x;
 LoadVar(S,x);
 return x;
}
References LoadVar, and S.
Referenced by LoadConstants().
LoadString()
static TString * LoadString (LoadState * S) static
Definition at line 72 of file lua-5.2.4/src/lundump.c.
{
 size_t size;
 LoadVar(S,size);
 if (size==0)
  return NULL;
 else
 {
  char* s=luaZ_openspace(S->L,S->b,size);
  LoadBlock(S,s,size*sizeof(char));
  return luaS_newlstr(S->L,s,size-1);       /* remove trailing '\0' */
 }
}
References LoadBlock(), LoadVar, luaS_newlstr(), luaZ_openspace(), NULL, S, and s.
Referenced by LoadConstants(), and LoadDebug().
LoadUpvalues()
static void LoadUpvalues (LoadState * S, Proto * f) static
Definition at line 135 of file lua-5.2.4/src/lundump.c.
{
 int i,n;
 n=LoadInt(S);
 f->upvalues=luaM_newvector(S->L,n,Upvaldesc);
 f->sizeupvalues=n;
 for (i=0; i<n; i++) f->upvalues[i].name=NULL;
 for (i=0; i<n; i++)
 {
  f->upvalues[i].instack=LoadByte(S);
  f->upvalues[i].idx=LoadByte(S);
 }
}
References LoadByte, LoadInt(), luaM_newvector, NULL, S, Proto::sizeupvalues, and Proto::upvalues.
Referenced by LoadFunction().
luaU_header()
void luaU_header (lu_byte * h)
Definition at line 244 of file lua-5.2.4/src/lundump.c.
{
 int x=1;
 memcpy(h,LUA_SIGNATURE,sizeof(LUA_SIGNATURE)-sizeof(char));
 h+=sizeof(LUA_SIGNATURE)-sizeof(char);
 *h++=cast_byte(VERSION);
 *h++=cast_byte(FORMAT);
 *h++=cast_byte(*(char*)&x);            /* endianness */
 *h++=cast_byte(sizeof(int));
 *h++=cast_byte(sizeof(size_t));
 *h++=cast_byte(sizeof(Instruction));
 *h++=cast_byte(sizeof(lua_Number));
 *h++=cast_byte(((lua_Number)0.5)==0);      /* is lua_Number integral? */
 memcpy(h,LUAC_TAIL,sizeof(LUAC_TAIL)-sizeof(char));
}
References cast_byte, FORMAT, LUA_SIGNATURE, LUAC_TAIL, and VERSION.
Referenced by LoadHeader().
luaU_undump()
Closure * luaU_undump (lua_State * L, ZIO * Z, Mbuffer * buff, const char * name)
Definition at line 206 of file lua-5.2.4/src/lundump.c.
{
 LoadState S;
 Closure* cl;
 if (*name=='@' || *name=='=')
  S.name=name+1;
 else if (*name==LUA_SIGNATURE[0])
  S.name="binary string";
 else
  S.name=name;
 S.L=L;
 S.Z=Z;
 S.b=buff;
 LoadHeader(&S);
 cl=luaF_newLclosure(L,1);
 setclLvalue(L,L->top,cl); incr_top(L);
 cl->l.p=luaF_newproto(L);
 LoadFunction(&S,cl->l.p);
 if (cl->l.p->sizeupvalues != 1)
 {
  Proto* p=cl->l.p;
  cl=luaF_newLclosure(L,cl->l.p->sizeupvalues);
  cl->l.p=p;
  setclLvalue(L,L->top-1,cl);
 }
 luai_verifycode(L,buff,cl->l.p);
 return cl;
}
References incr_top, Closure::l, LoadFunction(), LoadHeader(), LUA_SIGNATURE, luaF_newLclosure(), luaF_newproto(), luai_verifycode, name, LClosure::p, S, setclLvalue, Proto::sizeupvalues, and lua_State::top.