Github User Fetcher: lutf8lib.c File Reference
lutf8lib.c File Reference
#include "lprefix.h"
#include <assert.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lutf8lib_c
#define LUA_LIB
#define MAXUNICODE 0x10FFFFu
#define MAXUTF 0x7FFFFFFFu
#define iscont(p) ((*(p) & 0xC0) == 0x80)
#define UTF8PATT "[\0-\x7F\xC2-\xFD][\x80-\xBF]*"
Typedefs
typedef unsigned long utfint
Functions
static lua_Integer u_posrelat (lua_Integer pos, size_t len)
static const char * utf8_decode (const char *s, utfint *val, int strict)
static int utflen (lua_State *L)
static int codepoint (lua_State *L)
static void pushutfchar (lua_State *L, int arg)
static int utfchar (lua_State *L)
static int byteoffset (lua_State *L)
static int iter_aux (lua_State *L, int strict)
static int iter_auxstrict (lua_State *L)
static int iter_auxlax (lua_State *L)
static int iter_codes (lua_State *L)
LUAMOD_API int luaopen_utf8 (lua_State *L)
Variables
static const luaL_Reg funcs []
Macro Definition Documentation
iscont
#define iscont (p) ((*(p) & 0xC0) == 0x80)
Definition at line 38 of file lua-5.4.3/src/lutf8lib.c.
Referenced by byteoffset(), and iter_aux().
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.4.3/src/lutf8lib.c.
lutf8lib_c
#define lutf8lib_c
Definition at line 7 of file lua-5.4.3/src/lutf8lib.c.
MAXUNICODE
#define MAXUNICODE 0x10FFFFu
Definition at line 24 of file lua-5.4.3/src/lutf8lib.c.
Referenced by utf8_decode().
MAXUTF
#define MAXUTF 0x7FFFFFFFu
Definition at line 26 of file lua-5.4.3/src/lutf8lib.c.
Referenced by pushutfchar(), and utf8_decode().
UTF8PATT
#define UTF8PATT "[\0-\x7F\xC2-\xFD][\x80-\xBF]*"
Definition at line 268 of file lua-5.4.3/src/lutf8lib.c.
Referenced by luaopen_utf8().
Typedef Documentation
utfint
typedef unsigned long utfint
Definition at line 34 of file lua-5.4.3/src/lutf8lib.c.
Function Documentation
byteoffset()
static int byteoffset (lua_State * L) static
Definition at line 183 of file lua-5.4.3/src/lutf8lib.c.
{
  size_t len;
  const char *s = luaL_checklstring(L, 1, &len);
  lua_Integer n  = luaL_checkinteger(L, 2);
  lua_Integer posi = (n >= 0) ? 1 : len + 1;
  posi = u_posrelat(luaL_optinteger(L, 3, posi), len);
  luaL_argcheck(L, 1 <= posi && --posi <= (lua_Integer)len, 3,
                   "position out of bounds");
  if (n == 0) {
    /* find beginning of current byte sequence */
    while (posi > 0 && iscont(s + posi)) posi--;
  }
  else {
    if (iscont(s + posi))
      return luaL_error(L, "initial position is a continuation byte");
    if (n < 0) {
       while (n < 0 && posi > 0) {  /* move back */
         do {  /* find beginning of previous character */
           posi--;
         } while (posi > 0 && iscont(s + posi));
         n++;
       }
     }
     else {
       n--;  /* do not move for 1st character */
       while (n > 0 && posi < (lua_Integer)len) {
         do {  /* find beginning of next character */
           posi++;
         } while (iscont(s + posi));  /* (cannot pass final '\0') */
         n--;
       }
     }
  }
  if (n == 0)  /* did it find given character? */
    lua_pushinteger(L, posi + 1);
  else  /* no such character */
    luaL_pushfail(L);
  return 1;
}
References iscont, lua_pushinteger(), luaL_argcheck, luaL_checkinteger(), luaL_checklstring(), luaL_error(), luaL_optinteger(), luaL_pushfail, s, and u_posrelat().
codepoint()
static int codepoint (lua_State * L) static
Definition at line 122 of file lua-5.4.3/src/lutf8lib.c.
{
  size_t len;
  const char *s = luaL_checklstring(L, 1, &len);
  lua_Integer posi = u_posrelat(luaL_optinteger(L, 2, 1), len);
  lua_Integer pose = u_posrelat(luaL_optinteger(L, 3, posi), len);
  int lax = lua_toboolean(L, 4);
  int n;
  const char *se;
  luaL_argcheck(L, posi >= 1, 2, "out of bounds");
  luaL_argcheck(L, pose <= (lua_Integer)len, 3, "out of bounds");
  if (posi > pose) return 0;  /* empty interval; return no values */
  if (pose - posi >= INT_MAX)  /* (lua_Integer -> int) overflow? */
    return luaL_error(L, "string slice too long");
  n = (int)(pose -  posi) + 1;  /* upper bound for number of returns */
  luaL_checkstack(L, n, "string slice too long");
  n = 0;  /* count the number of returns */
  se = s + pose;  /* string end */
  for (s += posi - 1; s < se;) {
    utfint code;
    s = utf8_decode(s, &code, !lax);
    if (s == NULL)
      return luaL_error(L, "invalid UTF-8 code");
    lua_pushinteger(L, code);
    n++;
  }
  return n;
}
References lua_pushinteger(), lua_toboolean(), luaL_argcheck, luaL_checklstring(), luaL_checkstack(), luaL_error(), luaL_optinteger(), NULL, s, u_posrelat(), and utf8_decode().
iter_aux()
static int iter_aux (lua_State * L, int strict) static
Definition at line 224 of file lua-5.4.3/src/lutf8lib.c.
{
  size_t len;
  const char *s = luaL_checklstring(L, 1, &len);
  lua_Integer n = lua_tointeger(L, 2) - 1;
  if (n < 0)  /* first iteration? */
    n = 0;  /* start from here */
  else if (n < (lua_Integer)len) {
    n++;  /* skip current byte */
    while (iscont(s + n)) n++;  /* and its continuations */
  }
  if (n >= (lua_Integer)len)
    return 0;  /* no more codepoints */
  else {
    utfint code;
    const char *next = utf8_decode(s + n, &code, strict);
    if (next == NULL)
      return luaL_error(L, "invalid UTF-8 code");
    lua_pushinteger(L, n + 1);
    lua_pushinteger(L, code);
    return 2;
  }
}
References iscont, lua_pushinteger(), lua_tointeger, luaL_checklstring(), luaL_error(), next, NULL, s, and utf8_decode().
Referenced by iter_auxlax(), and iter_auxstrict().
iter_auxlax()
static int iter_auxlax (lua_State * L) static
Definition at line 252 of file lua-5.4.3/src/lutf8lib.c.
{
  return iter_aux(L, 0);
}
References iter_aux().
Referenced by iter_codes().
iter_auxstrict()
static int iter_auxstrict (lua_State * L) static
Definition at line 248 of file lua-5.4.3/src/lutf8lib.c.
{
  return iter_aux(L, 1);
}
References iter_aux().
Referenced by iter_codes().
iter_codes()
static int iter_codes (lua_State * L) static
Definition at line 257 of file lua-5.4.3/src/lutf8lib.c.
{
  int lax = lua_toboolean(L, 2);
  luaL_checkstring(L, 1);
  lua_pushcfunction(L, lax ? iter_auxlax : iter_auxstrict);
  lua_pushvalue(L, 1);
  lua_pushinteger(L, 0);
  return 3;
}
References iter_auxlax(), iter_auxstrict(), lua_pushcfunction, lua_pushinteger(), lua_pushvalue(), lua_toboolean(), and luaL_checkstring.
luaopen_utf8()
LUAMOD_API int luaopen_utf8 (lua_State * L)
Definition at line 283 of file lua-5.4.3/src/lutf8lib.c.
{
  luaL_newlib(L, funcs);
  lua_pushlstring(L, UTF8PATT, sizeof(UTF8PATT)/sizeof(char) - 1);
  lua_setfield(L, -2, "charpattern");
  return 1;
}
References funcs, funcs, lua_pushlstring(), lua_setfield(), luaL_newlib, and UTF8PATT.
pushutfchar()
static void pushutfchar (lua_State * L, int arg) static
Definition at line 151 of file lua-5.4.3/src/lutf8lib.c.
{
  lua_Unsigned code = (lua_Unsigned)luaL_checkinteger(L, arg);
  luaL_argcheck(L, code <= MAXUTF, arg, "value out of range");
  lua_pushfstring(L, "%U", (long)code);
}
References arg, lua_pushfstring(), luaL_argcheck, luaL_checkinteger(), and MAXUTF.
Referenced by utfchar().
u_posrelat()
static lua_Integer u_posrelat (lua_Integer pos, size_t len) static
Definition at line 43 of file lua-5.4.3/src/lutf8lib.c.
{
  if (pos >= 0) return pos;
  else if (0u - (size_t)pos > len) return 0;
  else return (lua_Integer)len + pos + 1;
}
Referenced by byteoffset(), codepoint(), and utflen().
utf8_decode()
static const char * utf8_decode (const char * s, utfint * val, int strict) static
Definition at line 57 of file lua-5.4.3/src/lutf8lib.c.
{
  static const utfint limits[] =
        {~(utfint)0, 0x80, 0x800, 0x10000u, 0x200000u, 0x4000000u};
  unsigned int c = (unsigned char)s[0];
  utfint res = 0;  /* final result */
  if (c < 0x80)  /* ascii? */
    res = c;
  else {
    int count = 0;  /* to count number of continuation bytes */
    for (; c & 0x40; c <<= 1) {  /* while it needs continuation bytes... */
      unsigned int cc = (unsigned char)s[++count];  /* read next byte */
      if ((cc & 0xC0) != 0x80)  /* not a continuation byte? */
        return NULL;  /* invalid byte sequence */
      res = (res << 6) | (cc & 0x3F);  /* add lower 6 bits from cont. byte */
    }
    res |= ((utfint)(c & 0x7F) << (count * 5));  /* add first byte */
    if (count > 5 || res > MAXUTF || res < limits[count])
      return NULL;  /* invalid byte sequence */
    s += count;  /* skip continuation bytes read */
  }
  if (strict) {
    /* check for invalid code points; too large or surrogates */
    if (res > MAXUNICODE || (0xD800u <= res && res <= 0xDFFFu))
      return NULL;
  }
  if (val) *val = res;
  return s + 1;  /* +1 to include first byte */
}
References MAXUNICODE, MAXUTF, NULL, and s.
Referenced by codepoint(), iter_aux(), and utflen().
utfchar()
static int utfchar (lua_State * L) static
Definition at line 161 of file lua-5.4.3/src/lutf8lib.c.
{
  int n = lua_gettop(L);  /* number of arguments */
  if (n == 1)  /* optimize common case of single char */
    pushutfchar(L, 1);
  else {
    int i;
    luaL_Buffer b;
    luaL_buffinit(L, &b);
    for (i = 1; i <= n; i++) {
      pushutfchar(L, i);
      luaL_addvalue(&b);
    }
    luaL_pushresult(&b);
  }
  return 1;
}
References lua_gettop(), luaL_addvalue(), luaL_buffinit(), luaL_pushresult(), and pushutfchar().
utflen()
static int utflen (lua_State * L) static
Definition at line 92 of file lua-5.4.3/src/lutf8lib.c.
{
  lua_Integer n = 0;  /* counter for the number of characters */
  size_t len;  /* string length in bytes */
  const char *s = luaL_checklstring(L, 1, &len);
  lua_Integer posi = u_posrelat(luaL_optinteger(L, 2, 1), len);
  lua_Integer posj = u_posrelat(luaL_optinteger(L, 3, -1), len);
  int lax = lua_toboolean(L, 4);
  luaL_argcheck(L, 1 <= posi && --posi <= (lua_Integer)len, 2,
                   "initial position out of bounds");
  luaL_argcheck(L, --posj < (lua_Integer)len, 3,
                   "final position out of bounds");
  while (posi <= posj) {
    const char *s1 = utf8_decode(s + posi, NULL, !lax);
    if (s1 == NULL) {  /* conversion error? */
      luaL_pushfail(L);  /* return fail ... */
      lua_pushinteger(L, posi + 1);  /* ... and current position */
      return 2;
    }
    posi = s1 - s;
    n++;
  }
  lua_pushinteger(L, n);
  return 1;
}
References lua_pushinteger(), lua_toboolean(), luaL_argcheck, luaL_checklstring(), luaL_optinteger(), luaL_pushfail, NULL, s, u_posrelat(), and utf8_decode().
Variable Documentation
funcs
const luaL_Reg funcs[] static
Initial value:
= {
  {"offset", byteoffset},
  {"codepoint", codepoint},
  {"char", utfchar},
  {"len", utflen},
  {"codes", iter_codes},
  {"charpattern", NULL},
  {NULL, NULL}
}
Definition at line 271 of file lua-5.4.3/src/lutf8lib.c.
{
  {"offset", byteoffset},
  {"codepoint", codepoint},
  {"char", utfchar},
  {"len", utflen},
  {"codes", iter_codes},
  /* placeholders */
  {"charpattern", NULL},
  {NULL, NULL}
};
Referenced by luaopen_utf8().