Github User Fetcher: lauxlib.c File Reference
lauxlib.c File Reference
#include "lprefix.h"
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
Data Structures
struct UBox
struct LoadF
struct LoadS
Macros
#define lauxlib_c
#define LUA_LIB
#define LEVELS1 10 /* size of the first part of the stack */
#define LEVELS2 11 /* size of the second part of the stack */
#define l_inspectstat(stat, what) /* no op */
#define buffonstack(B) ((B)->b != (B)->initb)
#define freelist 0
Typedefs
typedef struct UBox UBox
typedef struct LoadF LoadF
typedef struct LoadS LoadS
Functions
static int findfield (lua_State *L, int objidx, int level)
static int pushglobalfuncname (lua_State *L, lua_Debug *ar)
static void pushfuncname (lua_State *L, lua_Debug *ar)
static int lastlevel (lua_State *L)
LUALIB_API void luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level)
LUALIB_API int luaL_argerror (lua_State *L, int arg, const char *extramsg)
static int typeerror (lua_State *L, int arg, const char *tname)
static void tag_error (lua_State *L, int arg, int tag)
LUALIB_API void luaL_where (lua_State *L, int level)
LUALIB_API int luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int luaL_fileresult (lua_State *L, int stat, const char *fname)
LUALIB_API int luaL_execresult (lua_State *L, int stat)
LUALIB_API int luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void luaL_setmetatable (lua_State *L, const char *tname)
LUALIB_API void * luaL_testudata (lua_State *L, int ud, const char *tname)
LUALIB_API void * luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API int luaL_checkoption (lua_State *L, int arg, const char *def, const char *const lst[])
LUALIB_API void luaL_checkstack (lua_State *L, int space, const char *msg)
LUALIB_API void luaL_checktype (lua_State *L, int arg, int t)
LUALIB_API void luaL_checkany (lua_State *L, int arg)
LUALIB_API const char * luaL_checklstring (lua_State *L, int arg, size_t *len)
LUALIB_API const char * luaL_optlstring (lua_State *L, int arg, const char *def, size_t *len)
LUALIB_API lua_Number luaL_checknumber (lua_State *L, int arg)
LUALIB_API lua_Number luaL_optnumber (lua_State *L, int arg, lua_Number def)
static void interror (lua_State *L, int arg)
LUALIB_API lua_Integer luaL_checkinteger (lua_State *L, int arg)
LUALIB_API lua_Integer luaL_optinteger (lua_State *L, int arg, lua_Integer def)
static void * resizebox (lua_State *L, int idx, size_t newsize)
static int boxgc (lua_State *L)
static void * newbox (lua_State *L, size_t newsize)
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void luaL_pushresult (luaL_Buffer *B)
LUALIB_API void luaL_pushresultsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addvalue (luaL_Buffer *B)
LUALIB_API void luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API char * luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz)
LUALIB_API int luaL_ref (lua_State *L, int t)
LUALIB_API void luaL_unref (lua_State *L, int t, int ref)
static const char * getF (lua_State *L, void *ud, size_t *size)
static int errfile (lua_State *L, const char *what, int fnameindex)
static int skipBOM (LoadF *lf)
static int skipcomment (LoadF *lf, int *cp)
LUALIB_API int luaL_loadfilex (lua_State *L, const char *filename, const char *mode)
static const char * getS (lua_State *L, void *ud, size_t *size)
LUALIB_API int luaL_loadbufferx (lua_State *L, const char *buff, size_t size, const char *name, const char *mode)
LUALIB_API int luaL_loadstring (lua_State *L, const char *s)
LUALIB_API int luaL_getmetafield (lua_State *L, int obj, const char *event)
LUALIB_API int luaL_callmeta (lua_State *L, int obj, const char *event)
LUALIB_API lua_Integer luaL_len (lua_State *L, int idx)
LUALIB_API const char * luaL_tolstring (lua_State *L, int idx, size_t *len)
LUALIB_API void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUALIB_API int luaL_getsubtable (lua_State *L, int idx, const char *fname)
LUALIB_API void luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb)
LUALIB_API const char * luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
static void * l_alloc (void *ud, void *ptr, size_t osize, size_t nsize)
static int panic (lua_State *L)
LUALIB_API lua_State * luaL_newstate (void)
LUALIB_API void luaL_checkversion_ (lua_State *L, lua_Number ver, size_t sz)
Macro Definition Documentation
buffonstack
#define buffonstack (B) ((B)->b != (B)->initb)
Definition at line 499 of file lua-5.3.6/src/lauxlib.c.
Referenced by luaL_addvalue(), luaL_prepbuffsize(), and luaL_pushresult().
freelist
#define freelist 0
Definition at line 592 of file lua-5.3.6/src/lauxlib.c.
Referenced by luaL_ref(), and luaL_unref().
l_inspectstat
#define l_inspectstat (stat, what) /* no op */
Definition at line 267 of file lua-5.3.6/src/lauxlib.c.
Referenced by luaL_execresult().
lauxlib_c
#define lauxlib_c
Definition at line 7 of file lua-5.3.6/src/lauxlib.c.
LEVELS1
#define LEVELS1 10 /* size of the first part of the stack */
Definition at line 37 of file lua-5.3.6/src/lauxlib.c.
Referenced by luaL_traceback().
LEVELS2
#define LEVELS2 11 /* size of the second part of the stack */
Definition at line 38 of file lua-5.3.6/src/lauxlib.c.
Referenced by luaL_traceback().
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.3.6/src/lauxlib.c.
Typedef Documentation
LoadF
typedef struct LoadF LoadF
LoadS
typedef struct LoadS LoadS
UBox
typedef struct UBox UBox
Function Documentation
boxgc()
static int boxgc (lua_State * L) static
Definition at line 476 of file lua-5.3.6/src/lauxlib.c.
{
  resizebox(L, 1, 0);
  return 0;
}
References resizebox().
Referenced by newbox().
errfile()
static int errfile (lua_State * L, const char * what, int fnameindex) static
Definition at line 660 of file lua-5.3.6/src/lauxlib.c.
{
  const char *serr = strerror(errno);
  const char *filename = lua_tostring(L, fnameindex) + 1;
  lua_pushfstring(L, "cannot %s %s: %s", what, filename, serr);
  lua_remove(L, fnameindex);
  return LUA_ERRFILE;
}
References LUA_ERRFILE, lua_pushfstring(), lua_remove, and lua_tostring.
Referenced by luaL_loadfilex().
findfield()
static int findfield (lua_State * L, int objidx, int level) static
Definition at line 46 of file lua-5.3.6/src/lauxlib.c.
{
  if (level == 0 || !lua_istable(L, -1))
    return 0;  /* not found */
  lua_pushnil(L);  /* start 'next' loop */
  while (lua_next(L, -2)) {  /* for each pair in table */
    if (lua_type(L, -2) == LUA_TSTRING) {  /* ignore non-string keys */
      if (lua_rawequal(L, objidx, -1)) {  /* found object? */
        lua_pop(L, 1);  /* remove value (but keep name) */
        return 1;
      }
      else if (findfield(L, objidx, level - 1)) {  /* try recursively */
        lua_remove(L, -2);  /* remove table (but keep name) */
        lua_pushliteral(L, ".");
        lua_insert(L, -2);  /* place '.' between the two names */
        lua_concat(L, 3);
        return 1;
      }
    }
    lua_pop(L, 1);  /* remove value */
  }
  return 0;  /* not found */
}
References findfield(), lua_concat(), lua_insert, lua_istable, lua_next(), lua_pop, lua_pushliteral, lua_pushnil(), lua_rawequal(), lua_remove, LUA_TSTRING, and lua_type().
Referenced by findfield(), and pushglobalfuncname().
getF()
static const char * getF (lua_State * L, void * ud, size_t * size) static
Definition at line 642 of file lua-5.3.6/src/lauxlib.c.
{
  LoadF *lf = (LoadF *)ud;
  (void)L;  /* not used */
  if (lf->n > 0) {  /* are there pre-read characters to be read? */
    *size = lf->n;  /* return them (chars already in buffer) */
    lf->n = 0;  /* no more pre-read characters */
  }
  else {  /* read a block from file */
    /* 'fread' can return > 0 *and* set the EOF flag. If next call to
       'getF' called 'fread', it might still wait for user input.
       The next check avoids this problem. */
    if (feof(lf->f)) return NULL;
    *size = fread(lf->buff, 1, sizeof(lf->buff), lf->f);  /* read block */
  }
  return lf->buff;
}
References LoadF::buff, LoadF::f, fread(), LoadF::n, and NULL.
Referenced by luaL_loadfilex().
getS()
static const char * getS (lua_State * L, void * ud, size_t * size) static
Definition at line 745 of file lua-5.3.6/src/lauxlib.c.
{
  LoadS *ls = (LoadS *)ud;
  (void)L;  /* not used */
  if (ls->size == 0) return NULL;
  *size = ls->size;
  ls->size = 0;
  return ls->s;
}
References NULL, LoadS::s, and LoadS::size.
Referenced by luaL_loadbufferx().
interror()
static void interror (lua_State * L, int arg) static
Definition at line 422 of file lua-5.3.6/src/lauxlib.c.
{
  if (lua_isnumber(L, arg))
    luaL_argerror(L, arg, "number has no integer representation");
  else
    tag_error(L, arg, LUA_TNUMBER);
}
References arg, lua_isnumber(), LUA_TNUMBER, luaL_argerror(), and tag_error().
Referenced by luaL_checkinteger().
l_alloc()
static void * l_alloc (void * ud, void * ptr, size_t osize, size_t nsize) static
Definition at line 1008 of file lua-5.3.6/src/lauxlib.c.
{
  (void)ud; (void)osize;  /* not used */
  if (nsize == 0) {
    free(ptr);
    return NULL;
  }
  else {  /* cannot fail when shrinking a block */
    void *newptr = realloc(ptr, nsize);
    if (newptr == NULL && ptr != NULL && nsize <= osize)
      return ptr;  /* keep the original block */
    else  /* no fail or not shrinking */
     return newptr;  /* use the new block */
  }
}
References free, NULL, and realloc.
Referenced by luaL_newstate().
lastlevel()
static int lastlevel (lua_State * L) static
Definition at line 110 of file lua-5.3.6/src/lauxlib.c.
{
  lua_Debug ar;
  int li = 1, le = 1;
  /* find an upper bound */
  while (lua_getstack(L, le, &ar)) { li = le; le *= 2; }
  /* do a binary search */
  while (li < le) {
    int m = (li + le)/2;
    if (lua_getstack(L, m, &ar)) li = m + 1;
    else le = m;
  }
  return le - 1;
}
References lua_getstack().
Referenced by luaL_traceback().
luaL_addlstring()
LUALIB_API void luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 528 of file lua-5.3.6/src/lauxlib.c.
{
  if (l > 0) {  /* avoid 'memcpy' when 's' can be NULL */
    char *b = luaL_prepbuffsize(B, l);
    memcpy(b, s, l * sizeof(char));
    luaL_addsize(B, l);
  }
}
References luaL_addsize, luaL_prepbuffsize(), and s.
Referenced by luaL_addstring(), luaL_addvalue(), and luaL_gsub().
luaL_addstring()
LUALIB_API void luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 537 of file lua-5.3.6/src/lauxlib.c.
{
  luaL_addlstring(B, s, strlen(s));
}
References luaL_addlstring(), and s.
Referenced by luaL_gsub().
luaL_addvalue()
LUALIB_API void luaL_addvalue (luaL_Buffer * B)
Definition at line 558 of file lua-5.3.6/src/lauxlib.c.
{
  lua_State *L = B->L;
  size_t l;
  const char *s = lua_tolstring(L, -1, &l);
  if (buffonstack(B))
    lua_insert(L, -2);  /* put value below buffer */
  luaL_addlstring(B, s, l);
  lua_remove(L, (buffonstack(B)) ? -2 : -1);  /* remove value */
}
References buffonstack, luaL_Buffer::L, lua_insert, lua_remove, lua_tolstring(), luaL_addlstring(), and s.
luaL_argerror()
LUALIB_API int luaL_argerror (lua_State * L, int arg, const char * extramsg)
Definition at line 164 of file lua-5.3.6/src/lauxlib.c.
{
  lua_Debug ar;
  if (!lua_getstack(L, 0, &ar))  /* no stack frame? */
    return luaL_error(L, "bad argument #%d (%s)", arg, extramsg);
  lua_getinfo(L, "n", &ar);
  if (strcmp(ar.namewhat, "method") == 0) {
    arg--;  /* do not count 'self' */
    if (arg == 0)  /* error is in the self argument itself? */
      return luaL_error(L, "calling '%s' on bad self (%s)",
                           ar.name, extramsg);
  }
  if (ar.name == NULL)
    ar.name = (pushglobalfuncname(L, &ar)) ? lua_tostring(L, -1) : "?";
  return luaL_error(L, "bad argument #%d to '%s' (%s)",
                        arg, ar.name, extramsg);
}
References arg, lua_getinfo(), lua_getstack(), lua_tostring, luaL_error(), lua_Debug::name, lua_Debug::namewhat, NULL, and pushglobalfuncname().
Referenced by interror(), luaL_checkany(), luaL_checkoption(), and typeerror().
luaL_buffinit()
LUALIB_API void luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 569 of file lua-5.3.6/src/lauxlib.c.
{
  B->L = L;
  B->b = B->initb;
  B->n = 0;
  B->size = LUAL_BUFFERSIZE;
}
References luaL_Buffer::b, luaL_Buffer::initb, luaL_Buffer::L, LUAL_BUFFERSIZE, luaL_Buffer::n, and luaL_Buffer::size.
Referenced by luaL_buffinitsize(), and luaL_gsub().
luaL_buffinitsize()
LUALIB_API char * luaL_buffinitsize (lua_State * L, luaL_Buffer * B, size_t sz)
Definition at line 577 of file lua-5.3.6/src/lauxlib.c.
{
  luaL_buffinit(L, B);
  return luaL_prepbuffsize(B, sz);
}
References luaL_buffinit(), and luaL_prepbuffsize().
luaL_callmeta()
LUALIB_API int luaL_callmeta (lua_State * L, int obj, const char * event)
Definition at line 788 of file lua-5.3.6/src/lauxlib.c.
{
  obj = lua_absindex(L, obj);
  if (luaL_getmetafield(L, obj, event) == LUA_TNIL)  /* no metafield? */
    return 0;
  lua_pushvalue(L, obj);
  lua_call(L, 1, 1);
  return 1;
}
References lua_absindex(), lua_call, lua_pushvalue(), LUA_TNIL, and luaL_getmetafield().
Referenced by luaL_tolstring().
luaL_checkany()
LUALIB_API void luaL_checkany (lua_State * L, int arg)
Definition at line 384 of file lua-5.3.6/src/lauxlib.c.
{
  if (lua_type(L, arg) == LUA_TNONE)
    luaL_argerror(L, arg, "value expected");
}
References arg, LUA_TNONE, lua_type(), and luaL_argerror().
luaL_checkinteger()
LUALIB_API lua_Integer luaL_checkinteger (lua_State * L, int arg)
Definition at line 430 of file lua-5.3.6/src/lauxlib.c.
{
  int isnum;
  lua_Integer d = lua_tointegerx(L, arg, &isnum);
  if (!isnum) {
    interror(L, arg);
  }
  return d;
}
References arg, interror(), and lua_tointegerx().
Referenced by luaL_optinteger().
luaL_checklstring()
LUALIB_API const char * luaL_checklstring (lua_State * L, int arg, size_t * len)
Definition at line 390 of file lua-5.3.6/src/lauxlib.c.
{
  const char *s = lua_tolstring(L, arg, len);
  if (!s) tag_error(L, arg, LUA_TSTRING);
  return s;
}
References arg, lua_tolstring(), LUA_TSTRING, s, and tag_error().
Referenced by luaL_optlstring().
luaL_checknumber()
LUALIB_API lua_Number luaL_checknumber (lua_State * L, int arg)
Definition at line 408 of file lua-5.3.6/src/lauxlib.c.
{
  int isnum;
  lua_Number d = lua_tonumberx(L, arg, &isnum);
  if (!isnum)
    tag_error(L, arg, LUA_TNUMBER);
  return d;
}
References arg, LUA_TNUMBER, lua_tonumberx(), and tag_error().
Referenced by luaL_optnumber().
luaL_checkoption()
LUALIB_API int luaL_checkoption (lua_State * L, int arg, const char * def, const char *const lst[])
Definition at line 348 of file lua-5.3.6/src/lauxlib.c.
{
  const char *name = (def) ? luaL_optstring(L, arg, def) :
                             luaL_checkstring(L, arg);
  int i;
  for (i=0; lst[i]; i++)
    if (strcmp(lst[i], name) == 0)
      return i;
  return luaL_argerror(L, arg,
                       lua_pushfstring(L, "invalid option '%s'", name));
}
References arg, lua_pushfstring(), luaL_argerror(), luaL_checkstring, luaL_optstring, and name.
luaL_checkstack()
LUALIB_API void luaL_checkstack (lua_State * L, int space, const char * msg)
Definition at line 368 of file lua-5.3.6/src/lauxlib.c.
{
  if (!lua_checkstack(L, space)) {
    if (msg)
      luaL_error(L, "stack overflow (%s)", msg);
    else
      luaL_error(L, "stack overflow");
  }
}
References lua_checkstack(), and luaL_error().
Referenced by luaL_setfuncs(), and luaL_traceback().
luaL_checktype()
LUALIB_API void luaL_checktype (lua_State * L, int arg, int t)
Definition at line 378 of file lua-5.3.6/src/lauxlib.c.
{
  if (lua_type(L, arg) != t)
    tag_error(L, arg, t);
}
References arg, lua_type(), and tag_error().
luaL_checkudata()
LUALIB_API void * luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 333 of file lua-5.3.6/src/lauxlib.c.
{
  void *p = luaL_testudata(L, ud, tname);
  if (p == NULL) typeerror(L, ud, tname);
  return p;
}
References luaL_testudata(), NULL, and typeerror().
luaL_checkversion_()
LUALIB_API void luaL_checkversion_ (lua_State * L, lua_Number ver, size_t sz)
Definition at line 1038 of file lua-5.3.6/src/lauxlib.c.
{
  const lua_Number *v = lua_version(L);
  if (sz != LUAL_NUMSIZES)  /* check numeric types */
    luaL_error(L, "core and library have incompatible numeric types");
  if (v != lua_version(NULL))
    luaL_error(L, "multiple Lua VMs detected");
  else if (*v != ver)
    luaL_error(L, "version mismatch: app. needs %f, Lua core provides %f",
                  (LUAI_UACNUMBER)ver, (LUAI_UACNUMBER)*v);
}
References lua_version(), LUAI_UACNUMBER, luaL_error(), LUAL_NUMSIZES, and NULL.
luaL_error()
LUALIB_API int luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 223 of file lua-5.3.6/src/lauxlib.c.
{
  va_list argp;
  va_start(argp, fmt);
  luaL_where(L, 1);
  lua_pushvfstring(L, fmt, argp);
  va_end(argp);
  lua_concat(L, 2);
  return lua_error(L);
}
References lua_concat(), lua_error(), lua_pushvfstring(), and luaL_where().
Referenced by luaL_argerror(), luaL_checkstack(), luaL_checkversion_(), luaL_len(), luaL_prepbuffsize(), luaL_tolstring(), and resizebox().
luaL_execresult()
LUALIB_API int luaL_execresult (lua_State * L, int stat)
Definition at line 274 of file lua-5.3.6/src/lauxlib.c.
{
  const char *what = "exit";  /* type of termination */
  if (stat == -1)  /* error? */
    return luaL_fileresult(L, 0, NULL);
  else {
    l_inspectstat(stat, what);  /* interpret result */
    if (*what == 'e' && stat == 0)  /* successful termination? */
      lua_pushboolean(L, 1);
    else
      lua_pushnil(L);
    lua_pushstring(L, what);
    lua_pushinteger(L, stat);
    return 3;  /* return true/nil,what,code */
  }
}
References l_inspectstat, lua_pushboolean(), lua_pushinteger(), lua_pushnil(), lua_pushstring(), luaL_fileresult(), and NULL.
luaL_fileresult()
LUALIB_API int luaL_fileresult (lua_State * L, int stat, const char * fname)
Definition at line 234 of file lua-5.3.6/src/lauxlib.c.
{
  int en = errno;  /* calls to Lua API may change this value */
  if (stat) {
    lua_pushboolean(L, 1);
    return 1;
  }
  else {
    lua_pushnil(L);
    if (fname)
      lua_pushfstring(L, "%s: %s", fname, strerror(en));
    else
      lua_pushstring(L, strerror(en));
    lua_pushinteger(L, en);
    return 3;
  }
}
References lua_pushboolean(), lua_pushfstring(), lua_pushinteger(), lua_pushnil(), and lua_pushstring().
Referenced by luaL_execresult().
luaL_getmetafield()
LUALIB_API int luaL_getmetafield (lua_State * L, int obj, const char * event)
Definition at line 772 of file lua-5.3.6/src/lauxlib.c.
{
  if (!lua_getmetatable(L, obj))  /* no metatable? */
    return LUA_TNIL;
  else {
    int tt;
    lua_pushstring(L, event);
    tt = lua_rawget(L, -2);
    if (tt == LUA_TNIL)  /* is metafield nil? */
      lua_pop(L, 2);  /* remove metatable and metafield */
    else
      lua_remove(L, -2);  /* remove only metatable */
    return tt;  /* return metafield type */
  }
}
References lua_getmetatable(), lua_pop, lua_pushstring(), lua_rawget(), lua_remove, and LUA_TNIL.
Referenced by luaL_callmeta(), luaL_tolstring(), and typeerror().
luaL_getsubtable()
LUALIB_API int luaL_getsubtable (lua_State * L, int idx, const char * fname)
Definition at line 951 of file lua-5.3.6/src/lauxlib.c.
{
  if (lua_getfield(L, idx, fname) == LUA_TTABLE)
    return 1;  /* table already there */
  else {
    lua_pop(L, 1);  /* remove previous result */
    idx = lua_absindex(L, idx);
    lua_newtable(L);
    lua_pushvalue(L, -1);  /* copy to be left at top */
    lua_setfield(L, idx, fname);  /* assign new table to field */
    return 0;  /* false, because did not find table there */
  }
}
References lua_absindex(), lua_getfield(), lua_newtable, lua_pop, lua_pushvalue(), lua_setfield(), and LUA_TTABLE.
Referenced by luaL_requiref().
luaL_gsub()
LUALIB_API const char * luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 991 of file lua-5.3.6/src/lauxlib.c.
{
  const char *wild;
  size_t l = strlen(p);
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  while ((wild = strstr(s, p)) != NULL) {
    luaL_addlstring(&b, s, wild - s);  /* push prefix */
    luaL_addstring(&b, r);  /* push replacement in place of pattern */
    s = wild + l;  /* continue after 'p' */
  }
  luaL_addstring(&b, s);  /* push last suffix */
  luaL_pushresult(&b);
  return lua_tostring(L, -1);
}
References lua_tostring, luaL_addlstring(), luaL_addstring(), luaL_buffinit(), luaL_pushresult(), NULL, and s.
luaL_len()
LUALIB_API lua_Integer luaL_len (lua_State * L, int idx)
Definition at line 798 of file lua-5.3.6/src/lauxlib.c.
{
  lua_Integer l;
  int isnum;
  lua_len(L, idx);
  l = lua_tointegerx(L, -1, &isnum);
  if (!isnum)
    luaL_error(L, "object length is not an integer");
  lua_pop(L, 1);  /* remove object */
  return l;
}
References lua_len(), lua_pop, lua_tointegerx(), and luaL_error().
luaL_loadbufferx()
LUALIB_API int luaL_loadbufferx (lua_State * L, const char * buff, size_t size, const char * name, const char * mode)
Definition at line 755 of file lua-5.3.6/src/lauxlib.c.
{
  LoadS ls;
  ls.s = buff;
  ls.size = size;
  return lua_load(L, getS, &ls, name, mode);
}
References getS(), lua_load(), name, LoadS::s, and LoadS::size.
luaL_loadfilex()
LUALIB_API int luaL_loadfilex (lua_State * L, const char * filename, const char * mode)
Definition at line 703 of file lua-5.3.6/src/lauxlib.c.
{
  LoadF lf;
  int status, readstatus;
  int c;
  int fnameindex = lua_gettop(L) + 1;  /* index of filename on the stack */
  if (filename == NULL) {
    lua_pushliteral(L, "=stdin");
    lf.f = stdin;
  }
  else {
    lua_pushfstring(L, "@%s", filename);
    lf.f = fopen(filename, "r");
    if (lf.f == NULL) return errfile(L, "open", fnameindex);
  }
  if (skipcomment(&lf, &c))  /* read initial portion */
    lf.buff[lf.n++] = '\n';  /* add line to correct line numbers */
  if (c == LUA_SIGNATURE[0] && filename) {  /* binary file? */
    lf.f = freopen(filename, "rb", lf.f);  /* reopen in binary mode */
    if (lf.f == NULL) return errfile(L, "reopen", fnameindex);
    skipcomment(&lf, &c);  /* re-read initial portion */
  }
  if (c != EOF)
    lf.buff[lf.n++] = c;  /* 'c' is the first character of the stream */
  status = lua_load(L, getF, &lf, lua_tostring(L, -1), mode);
  readstatus = ferror(lf.f);
  if (filename) fclose(lf.f);  /* close file (even in case of errors) */
  if (readstatus) {
    lua_settop(L, fnameindex);  /* ignore results from 'lua_load' */
    return errfile(L, "read", fnameindex);
  }
  lua_remove(L, fnameindex);
  return status;
}
References LoadF::buff, errfile(), LoadF::f, getF(), lua_gettop(), lua_load(), lua_pushfstring(), lua_pushliteral, lua_remove, lua_settop(), LUA_SIGNATURE, lua_tostring, LoadF::n, NULL, and skipcomment().
luaL_loadstring()
LUALIB_API int luaL_loadstring (lua_State * L, const char * s)
Definition at line 764 of file lua-5.3.6/src/lauxlib.c.
{
  return luaL_loadbuffer(L, s, strlen(s), s);
}
References luaL_loadbuffer, and s.
luaL_newmetatable()
LUALIB_API int luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 299 of file lua-5.3.6/src/lauxlib.c.
{
  if (luaL_getmetatable(L, tname) != LUA_TNIL)  /* name already in use? */
    return 0;  /* leave previous value on top, but return 0 */
  lua_pop(L, 1);
  lua_createtable(L, 0, 2);  /* create metatable */
  lua_pushstring(L, tname);
  lua_setfield(L, -2, "__name");  /* metatable.__name = tname */
  lua_pushvalue(L, -1);
  lua_setfield(L, LUA_REGISTRYINDEX, tname);  /* registry.name = metatable */
  return 1;
}
References lua_createtable(), lua_pop, lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), LUA_TNIL, and luaL_getmetatable.
Referenced by newbox().
luaL_newstate()
LUALIB_API lua_State * luaL_newstate (void)
Definition at line 1031 of file lua-5.3.6/src/lauxlib.c.
{
  lua_State *L = lua_newstate(l_alloc, NULL);
  if (L) lua_atpanic(L, &panic);
  return L;
}
References l_alloc(), lua_atpanic(), lua_newstate(), NULL, and panic().
luaL_optinteger()
LUALIB_API lua_Integer luaL_optinteger (lua_State * L, int arg, lua_Integer def)
Definition at line 440 of file lua-5.3.6/src/lauxlib.c.
{
  return luaL_opt(L, luaL_checkinteger, arg, def);
}
References arg, luaL_checkinteger(), and luaL_opt.
luaL_optlstring()
LUALIB_API const char * luaL_optlstring (lua_State * L, int arg, const char * def, size_t * len)
Definition at line 397 of file lua-5.3.6/src/lauxlib.c.
{
  if (lua_isnoneornil(L, arg)) {
    if (len)
      *len = (def ? strlen(def) : 0);
    return def;
  }
  else return luaL_checklstring(L, arg, len);
}
References arg, lua_isnoneornil, and luaL_checklstring().
luaL_optnumber()
LUALIB_API lua_Number luaL_optnumber (lua_State * L, int arg, lua_Number def)
Definition at line 417 of file lua-5.3.6/src/lauxlib.c.
{
  return luaL_opt(L, luaL_checknumber, arg, def);
}
References arg, luaL_checknumber(), and luaL_opt.
luaL_prepbuffsize()
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer * B, size_t sz)
Definition at line 505 of file lua-5.3.6/src/lauxlib.c.
{
  lua_State *L = B->L;
  if (B->size - B->n < sz) {  /* not enough space? */
    char *newbuff;
    size_t newsize = B->size * 2;  /* double buffer size */
    if (newsize - B->n < sz)  /* not big enough? */
      newsize = B->n + sz;
    if (newsize < B->n || newsize - B->n < sz)
      luaL_error(L, "buffer too large");
    /* create larger buffer */
    if (buffonstack(B))
      newbuff = (char *)resizebox(L, -1, newsize);
    else {  /* no buffer yet */
      newbuff = (char *)newbox(L, newsize);
      memcpy(newbuff, B->b, B->n * sizeof(char));  /* copy original content */
    }
    B->b = newbuff;
    B->size = newsize;
  }
  return &B->b[B->n];
}
References luaL_Buffer::b, buffonstack, luaL_Buffer::L, luaL_error(), luaL_Buffer::n, newbox(), resizebox(), and luaL_Buffer::size.
Referenced by luaL_addlstring(), and luaL_buffinitsize().
luaL_pushresult()
LUALIB_API void luaL_pushresult (luaL_Buffer * B)
Definition at line 542 of file lua-5.3.6/src/lauxlib.c.
{
  lua_State *L = B->L;
  lua_pushlstring(L, B->b, B->n);
  if (buffonstack(B)) {
    resizebox(L, -2, 0);  /* delete old buffer */
    lua_remove(L, -2);  /* remove its header from the stack */
  }
}
References luaL_Buffer::b, buffonstack, luaL_Buffer::L, lua_pushlstring(), lua_remove, luaL_Buffer::n, and resizebox().
Referenced by luaL_gsub(), and luaL_pushresultsize().
luaL_pushresultsize()
LUALIB_API void luaL_pushresultsize (luaL_Buffer * B, size_t sz)
Definition at line 552 of file lua-5.3.6/src/lauxlib.c.
{
  luaL_addsize(B, sz);
  luaL_pushresult(B);
}
References luaL_addsize, and luaL_pushresult().
luaL_ref()
LUALIB_API int luaL_ref (lua_State * L, int t)
Definition at line 595 of file lua-5.3.6/src/lauxlib.c.
{
  int ref;
  if (lua_isnil(L, -1)) {
    lua_pop(L, 1);  /* remove from stack */
    return LUA_REFNIL;  /* 'nil' has a unique fixed reference */
  }
  t = lua_absindex(L, t);
  lua_rawgeti(L, t, freelist);  /* get first free element */
  ref = (int)lua_tointeger(L, -1);  /* ref = t[freelist] */
  lua_pop(L, 1);  /* remove it from stack */
  if (ref != 0) {  /* any free element? */
    lua_rawgeti(L, t, ref);  /* remove it from list */
    lua_rawseti(L, t, freelist);  /* (t[freelist] = t[ref]) */
  }
  else  /* no free elements */
    ref = (int)lua_rawlen(L, t) + 1;  /* get a new reference */
  lua_rawseti(L, t, ref);
  return ref;
}
References freelist, lua_absindex(), lua_isnil, lua_pop, lua_rawgeti(), lua_rawlen, lua_rawseti(), LUA_REFNIL, and lua_tointeger.
luaL_requiref()
LUALIB_API void luaL_requiref (lua_State * L, const char * modname, lua_CFunction openf, int glb)
Definition at line 971 of file lua-5.3.6/src/lauxlib.c.
{
  luaL_getsubtable(L, LUA_REGISTRYINDEX, LUA_LOADED_TABLE);
  lua_getfield(L, -1, modname);  /* LOADED[modname] */
  if (!lua_toboolean(L, -1)) {  /* package not already loaded? */
    lua_pop(L, 1);  /* remove field */
    lua_pushcfunction(L, openf);
    lua_pushstring(L, modname);  /* argument to open function */
    lua_call(L, 1, 1);  /* call 'openf' to open module */
    lua_pushvalue(L, -1);  /* make copy of module (call result) */
    lua_setfield(L, -3, modname);  /* LOADED[modname] = module */
  }
  lua_remove(L, -2);  /* remove LOADED table */
  if (glb) {
    lua_pushvalue(L, -1);  /* copy of module */
    lua_setglobal(L, modname);  /* _G[modname] = module */
  }
}
References lua_call, lua_getfield(), LUA_LOADED_TABLE, lua_pop, lua_pushcfunction, lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_remove, lua_setfield(), lua_setglobal, lua_toboolean(), and luaL_getsubtable().
luaL_setfuncs()
LUALIB_API void luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 934 of file lua-5.3.6/src/lauxlib.c.
{
  luaL_checkstack(L, nup, "too many upvalues");
  for (; l->name != NULL; l++) {  /* fill the table with given functions */
    int i;
    for (i = 0; i < nup; i++)  /* copy upvalues to the top */
      lua_pushvalue(L, -nup);
    lua_pushcclosure(L, l->func, nup);  /* closure with those upvalues */
    lua_setfield(L, -(nup + 2), l->name);
  }
  lua_pop(L, nup);  /* remove upvalues */
}
References luaL_Reg::func, lua_pop, lua_pushcclosure(), lua_pushvalue(), lua_setfield(), luaL_checkstack(), luaL_Reg::name, and NULL.
luaL_setmetatable()
LUALIB_API void luaL_setmetatable (lua_State * L, const char * tname)
Definition at line 312 of file lua-5.3.6/src/lauxlib.c.
{
  luaL_getmetatable(L, tname);
  lua_setmetatable(L, -2);
}
References lua_setmetatable(), and luaL_getmetatable.
luaL_testudata()
LUALIB_API void * luaL_testudata (lua_State * L, int ud, const char * tname)
Definition at line 318 of file lua-5.3.6/src/lauxlib.c.
{
  void *p = lua_touserdata(L, ud);
  if (p != NULL) {  /* value is a userdata? */
    if (lua_getmetatable(L, ud)) {  /* does it have a metatable? */
      luaL_getmetatable(L, tname);  /* get correct metatable */
      if (!lua_rawequal(L, -1, -2))  /* not the same? */
        p = NULL;  /* value is a userdata with wrong metatable */
      lua_pop(L, 2);  /* remove both metatables */
      return p;
    }
  }
  return NULL;  /* value is not a userdata with a metatable */
}
References lua_getmetatable(), lua_pop, lua_rawequal(), lua_touserdata(), luaL_getmetatable, and NULL.
Referenced by luaL_checkudata().
luaL_tolstring()
LUALIB_API const char * luaL_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 810 of file lua-5.3.6/src/lauxlib.c.
{
  if (luaL_callmeta(L, idx, "__tostring")) {  /* metafield? */
    if (!lua_isstring(L, -1))
      luaL_error(L, "'__tostring' must return a string");
  }
  else {
    switch (lua_type(L, idx)) {
      case LUA_TNUMBER: {
        if (lua_isinteger(L, idx))
          lua_pushfstring(L, "%I", (LUAI_UACINT)lua_tointeger(L, idx));
        else
          lua_pushfstring(L, "%f", (LUAI_UACNUMBER)lua_tonumber(L, idx));
        break;
      }
      case LUA_TSTRING:
        lua_pushvalue(L, idx);
        break;
      case LUA_TBOOLEAN:
        lua_pushstring(L, (lua_toboolean(L, idx) ? "true" : "false"));
        break;
      case LUA_TNIL:
        lua_pushliteral(L, "nil");
        break;
      default: {
        int tt = luaL_getmetafield(L, idx, "__name");  /* try name */
        const char *kind = (tt == LUA_TSTRING) ? lua_tostring(L, -1) :
                                                 luaL_typename(L, idx);
        lua_pushfstring(L, "%s: %p", kind, lua_topointer(L, idx));
        if (tt != LUA_TNIL)
          lua_remove(L, -2);  /* remove '__name' */
        break;
      }
    }
  }
  return lua_tolstring(L, -1, len);
}
References lua_isinteger(), lua_isstring(), lua_pushfstring(), lua_pushliteral, lua_pushstring(), lua_pushvalue(), lua_remove, LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, lua_toboolean(), lua_tointeger, lua_tolstring(), lua_tonumber, lua_topointer(), lua_tostring, LUA_TSTRING, lua_type(), LUAI_UACINT, LUAI_UACNUMBER, luaL_callmeta(), luaL_error(), luaL_getmetafield(), and luaL_typename.
luaL_traceback()
LUALIB_API void luaL_traceback (lua_State * L, lua_State * L1, const char * msg, int level)
Definition at line 125 of file lua-5.3.6/src/lauxlib.c.
{
  lua_Debug ar;
  int top = lua_gettop(L);
  int last = lastlevel(L1);
  int n1 = (last - level > LEVELS1 + LEVELS2) ? LEVELS1 : -1;
  if (msg)
    lua_pushfstring(L, "%s\n", msg);
  luaL_checkstack(L, 10, NULL);
  lua_pushliteral(L, "stack traceback:");
  while (lua_getstack(L1, level++, &ar)) {
    if (n1-- == 0) {  /* too many levels? */
      lua_pushliteral(L, "\n\t...");  /* add a '...' */
      level = last - LEVELS2 + 1;  /* and skip to last ones */
    }
    else {
      lua_getinfo(L1, "Slnt", &ar);
      lua_pushfstring(L, "\n\t%s:", ar.short_src);
      if (ar.currentline > 0)
        lua_pushfstring(L, "%d:", ar.currentline);
      lua_pushliteral(L, " in ");
      pushfuncname(L, &ar);
      if (ar.istailcall)
        lua_pushliteral(L, "\n\t(...tail calls...)");
      lua_concat(L, lua_gettop(L) - top);
    }
  }
  lua_concat(L, lua_gettop(L) - top);
}
References lua_Debug::currentline, lua_Debug::istailcall, lastlevel(), LEVELS1, LEVELS2, lua_concat(), lua_getinfo(), lua_getstack(), lua_gettop(), lua_pushfstring(), lua_pushliteral, luaL_checkstack(), NULL, pushfuncname(), and lua_Debug::short_src.
luaL_unref()
LUALIB_API void luaL_unref (lua_State * L, int t, int ref)
Definition at line 616 of file lua-5.3.6/src/lauxlib.c.
{
  if (ref >= 0) {
    t = lua_absindex(L, t);
    lua_rawgeti(L, t, freelist);
    lua_rawseti(L, t, ref);  /* t[ref] = t[freelist] */
    lua_pushinteger(L, ref);
    lua_rawseti(L, t, freelist);  /* t[freelist] = ref */
  }
}
References freelist, lua_absindex(), lua_pushinteger(), lua_rawgeti(), and lua_rawseti().
luaL_where()
LUALIB_API void luaL_where (lua_State * L, int level)
Definition at line 205 of file lua-5.3.6/src/lauxlib.c.
{
  lua_Debug ar;
  if (lua_getstack(L, level, &ar)) {  /* check function at level */
    lua_getinfo(L, "Sl", &ar);  /* get info about it */
    if (ar.currentline > 0) {  /* is there info? */
      lua_pushfstring(L, "%s:%d: ", ar.short_src, ar.currentline);
      return;
    }
  }
  lua_pushfstring(L, "");  /* else, no information available... */
}
References lua_Debug::currentline, lua_getinfo(), lua_getstack(), lua_pushfstring(), and lua_Debug::short_src.
Referenced by luaL_error().
newbox()
static void * newbox (lua_State * L, size_t newsize) static
Definition at line 482 of file lua-5.3.6/src/lauxlib.c.
{
  UBox *box = (UBox *)lua_newuserdata(L, sizeof(UBox));
  box->box = NULL;
  box->bsize = 0;
  if (luaL_newmetatable(L, "LUABOX")) {  /* creating metatable? */
    lua_pushcfunction(L, boxgc);
    lua_setfield(L, -2, "__gc");  /* metatable.__gc = boxgc */
  }
  lua_setmetatable(L, -2);
  return resizebox(L, -1, newsize);
}
References UBox::box, boxgc(), UBox::bsize, lua_newuserdata, lua_pushcfunction, lua_setfield(), lua_setmetatable(), luaL_newmetatable(), NULL, and resizebox().
Referenced by luaL_prepbuffsize().
panic()
static int panic (lua_State * L) static
Definition at line 1024 of file lua-5.3.6/src/lauxlib.c.
{
  lua_writestringerror("PANIC: unprotected error in call to Lua API (%s)\n",
                        lua_tostring(L, -1));
  return 0;  /* return to Lua to abort */
}
References lua_tostring, and lua_writestringerror.
Referenced by luaL_newstate().
pushfuncname()
static void pushfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 94 of file lua-5.3.6/src/lauxlib.c.
{
  if (pushglobalfuncname(L, ar)) {  /* try first a global name */
    lua_pushfstring(L, "function '%s'", lua_tostring(L, -1));
    lua_remove(L, -2);  /* remove name */
  }
  else if (*ar->namewhat != '\0')  /* is there a name from code? */
    lua_pushfstring(L, "%s '%s'", ar->namewhat, ar->name);  /* use it */
  else if (*ar->what == 'm')  /* main? */
      lua_pushliteral(L, "main chunk");
  else if (*ar->what != 'C')  /* for Lua functions, use <file:line> */
    lua_pushfstring(L, "function <%s:%d>", ar->short_src, ar->linedefined);
  else  /* nothing left... */
    lua_pushliteral(L, "?");
}
References lua_Debug::linedefined, lua_pushfstring(), lua_pushliteral, lua_remove, lua_tostring, lua_Debug::name, lua_Debug::namewhat, pushglobalfuncname(), lua_Debug::short_src, and lua_Debug::what.
Referenced by luaL_traceback().
pushglobalfuncname()
static int pushglobalfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 73 of file lua-5.3.6/src/lauxlib.c.
{
  int top = lua_gettop(L);
  lua_getinfo(L, "f", ar);  /* push function */
  lua_getfield(L, LUA_REGISTRYINDEX, LUA_LOADED_TABLE);
  if (findfield(L, top + 1, 2)) {
    const char *name = lua_tostring(L, -1);
    if (strncmp(name, "_G.", 3) == 0) {  /* name start with '_G.'? */
      lua_pushstring(L, name + 3);  /* push name without prefix */
      lua_remove(L, -2);  /* remove original name */
    }
    lua_copy(L, -1, top + 1);  /* move name to proper place */
    lua_pop(L, 2);  /* remove pushed values */
    return 1;
  }
  else {
    lua_settop(L, top);  /* remove function and global table */
    return 0;
  }
}
References findfield(), lua_copy(), lua_getfield(), lua_getinfo(), lua_gettop(), LUA_LOADED_TABLE, lua_pop, lua_pushstring(), LUA_REGISTRYINDEX, lua_remove, lua_settop(), lua_tostring, and name.
Referenced by luaL_argerror(), and pushfuncname().
resizebox()
static void * resizebox (lua_State * L, int idx, size_t newsize) static
Definition at line 461 of file lua-5.3.6/src/lauxlib.c.
{
  void *ud;
  lua_Alloc allocf = lua_getallocf(L, &ud);
  UBox *box = (UBox *)lua_touserdata(L, idx);
  void *temp = allocf(ud, box->box, box->bsize, newsize);
  if (temp == NULL && newsize > 0) {  /* allocation error? */
    resizebox(L, idx, 0);  /* free buffer */
    luaL_error(L, "not enough memory for buffer allocation");
  }
  box->box = temp;
  box->bsize = newsize;
  return temp;
}
References UBox::box, UBox::bsize, lua_getallocf(), lua_touserdata(), luaL_error(), NULL, and resizebox().
Referenced by boxgc(), luaL_prepbuffsize(), luaL_pushresult(), newbox(), and resizebox().
skipBOM()
static int skipBOM (LoadF * lf) static
Definition at line 669 of file lua-5.3.6/src/lauxlib.c.
{
  const char *p = "\xEF\xBB\xBF";  /* UTF-8 BOM mark */
  int c;
  lf->n = 0;
  do {
    c = getc(lf->f);
    if (c == EOF || c != *(const unsigned char *)p++) return c;
    lf->buff[lf->n++] = c;  /* to be read by the parser */
  } while (*p != '\0');
  lf->n = 0;  /* prefix matched; discard it */
  return getc(lf->f);  /* return next character */
}
References LoadF::buff, LoadF::f, and LoadF::n.
Referenced by skipcomment().
skipcomment()
static int skipcomment (LoadF * lf, int * cp) static
Definition at line 690 of file lua-5.3.6/src/lauxlib.c.
{
  int c = *cp = skipBOM(lf);
  if (c == '#') {  /* first line is a comment (Unix exec. file)? */
    do {  /* skip first line */
      c = getc(lf->f);
    } while (c != EOF && c != '\n');
    *cp = getc(lf->f);  /* skip end-of-line, if present */
    return 1;  /* there was a comment */
  }
  else return 0;  /* no comment */
}
References LoadF::f, and skipBOM().
Referenced by luaL_loadfilex().
tag_error()
static void tag_error (lua_State * L, int arg, int tag) static
Definition at line 196 of file lua-5.3.6/src/lauxlib.c.
{
  typeerror(L, arg, lua_typename(L, tag));
}
References arg, lua_typename(), and typeerror().
Referenced by interror(), luaL_checklstring(), luaL_checknumber(), and luaL_checktype().
typeerror()
static int typeerror (lua_State * L, int arg, const char * tname) static
Definition at line 182 of file lua-5.3.6/src/lauxlib.c.
{
  const char *msg;
  const char *typearg;  /* name for the type of the actual argument */
  if (luaL_getmetafield(L, arg, "__name") == LUA_TSTRING)
    typearg = lua_tostring(L, -1);  /* use the given type name */
  else if (lua_type(L, arg) == LUA_TLIGHTUSERDATA)
    typearg = "light userdata";  /* special name for messages */
  else
    typearg = luaL_typename(L, arg);  /* standard name */
  msg = lua_pushfstring(L, "%s expected, got %s", tname, typearg);
  return luaL_argerror(L, arg, msg);
}
References arg, lua_pushfstring(), LUA_TLIGHTUSERDATA, lua_tostring, LUA_TSTRING, lua_type(), luaL_argerror(), luaL_getmetafield(), and luaL_typename.
Referenced by luaL_checkudata(), and tag_error().