Github User Fetcher: luac.c File Reference
luac.c File Reference
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "ldo.h"
#include "lfunc.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lstring.h"
#include "lundump.h"
Data Structures
struct Smain
Macros
#define luac_c
#define LUA_CORE
#define PROGNAME "luac" /* default program name */
#define OUTPUT PROGNAME ".out" /* default output file */
#define IS(s) (strcmp(argv[i],s)==0)
#define toproto(L, i) (clvalue(L->top+(i))->l.p)
Functions
static void fatal (const char *message)
static void cannot (const char *what)
static void usage (const char *message)
static int doargs (int argc, char *argv[])
static const Proto * combine (lua_State *L, int n)
static int writer (lua_State *L, const void *p, size_t size, void *u)
static int pmain (lua_State *L)
int main (int argc, char *argv[])
Variables
static int listing =0
static int dumping =1
static int stripping =0
static char Output [] ={ OUTPUT }
static const char * output =Output
static const char * progname =PROGNAME
Macro Definition Documentation
IS
#define IS (s) (strcmp(argv[i],s)==0)
Definition at line 68 of file lua-5.1.5/src/luac.c.
Referenced by doargs(), and pmain().
LUA_CORE
#define LUA_CORE
Definition at line 13 of file lua-5.1.5/src/luac.c.
luac_c
#define luac_c
Definition at line 12 of file lua-5.1.5/src/luac.c.
OUTPUT
#define OUTPUT PROGNAME ".out" /* default output file */
Definition at line 27 of file lua-5.1.5/src/luac.c.
PROGNAME
#define PROGNAME "luac" /* default program name */
Definition at line 26 of file lua-5.1.5/src/luac.c.
Referenced by combine().
toproto
#define toproto (L, i) (clvalue(L->top+(i))->l.p)
Definition at line 117 of file lua-5.1.5/src/luac.c.
Referenced by combine().
Function Documentation
cannot()
static void cannot (const char * what) static
Definition at line 42 of file lua-5.1.5/src/luac.c.
{
 fprintf(stderr,"%s: cannot %s %s: %s\n",progname,what,output,strerror(errno));
 exit(EXIT_FAILURE);
}
References output, and progname.
Referenced by pmain().
combine()
static const Proto * combine (lua_State * L, int n) static
Definition at line 119 of file lua-5.1.5/src/luac.c.
{
 if (n==1)
  return toproto(L,-1);
 else
 {
  int i,pc;
  Proto* f=luaF_newproto(L);
  setptvalue2s(L,L->top,f); incr_top(L);
  f->source=luaS_newliteral(L,"=(" PROGNAME ")");
  f->maxstacksize=1;
  pc=2*n+1;
  f->code=luaM_newvector(L,pc,Instruction);
  f->sizecode=pc;
  f->p=luaM_newvector(L,n,Proto*);
  f->sizep=n;
  pc=0;
  for (i=0; i<n; i++)
  {
   f->p[i]=toproto(L,i-n-1);
   f->code[pc++]=CREATE_ABx(OP_CLOSURE,0,i);
   f->code[pc++]=CREATE_ABC(OP_CALL,0,1,1);
  }
  f->code[pc++]=CREATE_ABC(OP_RETURN,0,1,0);
  return f;
 }
}
References Proto::code, CREATE_ABC, CREATE_ABx, incr_top, luaF_newproto(), luaM_newvector, luaS_newliteral, Proto::maxstacksize, OP_CALL, OP_CLOSURE, OP_RETURN, Proto::p, PROGNAME, setptvalue2s, Proto::sizecode, Proto::sizep, Proto::source, lua_State::top, and toproto.
Referenced by pmain().
doargs()
static int doargs (int argc, char * argv[]) static
Definition at line 70 of file lua-5.1.5/src/luac.c.
{
 int i;
 int version=0;
 if (argv[0]!=NULL && *argv[0]!=0) progname=argv[0];
 for (i=1; i<argc; i++)
 {
  if (*argv[i]!='-')            /* end of options; keep it */
   break;
  else if (IS("--"))            /* end of options; skip it */
  {
   ++i;
   if (version) ++version;
   break;
  }
  else if (IS("-"))         /* end of options; use stdin */
   break;
  else if (IS("-l"))            /* list */
   ++listing;
  else if (IS("-o"))            /* output file */
  {
   output=argv[++i];
   if (output==NULL || *output==0) usage(LUA_QL("-o") " needs argument");
   if (IS("-")) output=NULL;
  }
  else if (IS("-p"))            /* parse only */
   dumping=0;
  else if (IS("-s"))            /* strip debug information */
   stripping=1;
  else if (IS("-v"))            /* show version */
   ++version;
  else                  /* unknown option */
   usage(argv[i]);
 }
 if (i==argc && (listing || !dumping))
 {
  dumping=0;
  argv[--i]=Output;
 }
 if (version)
 {
  printf("%s  %s\n",LUA_RELEASE,LUA_COPYRIGHT);
  if (version==argc-1) exit(EXIT_SUCCESS);
 }
 return i;
}
References dumping, IS, listing, LUA_COPYRIGHT, LUA_QL, LUA_RELEASE, NULL, Output, output, printf, progname, stripping, and usage().
Referenced by main().
fatal()
static void fatal (const char * message) static
Definition at line 36 of file lua-5.1.5/src/luac.c.
{
 fprintf(stderr,"%s: %s\n",progname,message);
 exit(EXIT_FAILURE);
}
References progname.
Referenced by duk_err_setup_heap_ljstate(), main(), and pmain().
main()
int main (int argc, char * argv[])
Definition at line 186 of file lua-5.1.5/src/luac.c.
{
 lua_State* L;
 struct Smain s;
 int i=doargs(argc,argv);
 argc-=i; argv+=i;
 if (argc<=0) usage("no input files given");
 L=lua_open();
 if (L==NULL) fatal("not enough memory for state");
 s.argc=argc;
 s.argv=argv;
 if (lua_cpcall(L,pmain,&s)!=0) fatal(lua_tostring(L,-1));
 lua_close(L);
 return EXIT_SUCCESS;
}
References Smain::argc, Smain::argv, doargs(), fatal(), lua_close(), lua_cpcall(), lua_open, lua_tostring, NULL, pmain(), s, and usage().
pmain()
static int pmain (lua_State * L) static
Definition at line 158 of file lua-5.1.5/src/luac.c.
{
 struct Smain* s = (struct Smain*)lua_touserdata(L, 1);
 int argc=s->argc;
 char** argv=s->argv;
 const Proto* f;
 int i;
 if (!lua_checkstack(L,argc)) fatal("too many input files");
 for (i=0; i<argc; i++)
 {
  const char* filename=IS("-") ? NULL : argv[i];
  if (luaL_loadfile(L,filename)!=0) fatal(lua_tostring(L,-1));
 }
 f=combine(L,argc);
 if (listing) luaU_print(f,listing>1);
 if (dumping)
 {
  FILE* D= (output==NULL) ? stdout : fopen(output,"wb");
  if (D==NULL) cannot("open");
  lua_lock(L);
  luaU_dump(L,f,writer,D,stripping);
  lua_unlock(L);
  if (ferror(D)) cannot("write");
  if (fclose(D)) cannot("close");
 }
 return 0;
}
References Smain::argc, Smain::argv, cannot(), combine(), dumping, fatal(), IS, listing, lua_checkstack(), lua_lock, lua_tostring, lua_touserdata(), lua_unlock, luaL_loadfile, luaU_dump(), luaU_print, NULL, output, s, stripping, and writer().
Referenced by main().
usage()
static void usage (const char * message) static
Definition at line 48 of file lua-5.1.5/src/luac.c.
{
 if (*message=='-')
  fprintf(stderr,"%s: unrecognized option " LUA_QS "\n",progname,message);
 else
  fprintf(stderr,"%s: %s\n",progname,message);
 fprintf(stderr,
 "usage: %s [options] [filenames].\n"
 "Available options are:\n"
 "  -        process stdin\n"
 "  -l       list\n"
 "  -o name  output to file " LUA_QL("name") " (default is \"%s\")\n"
 "  -p       parse only\n"
 "  -s       strip debug information\n"
 "  -v       show version information\n"
 "  --       stop handling options\n",
 progname,Output);
 exit(EXIT_FAILURE);
}
References LUA_QL, LUA_QS, Output, and progname.
Referenced by doargs(), and main().
writer()
static int writer (lua_State * L, const void * p, size_t size, void * u) static
Definition at line 147 of file lua-5.1.5/src/luac.c.
{
 UNUSED(L);
 return (fwrite(p,size,1,(FILE*)u)!=1) && (size!=0);
}
References fwrite(), and UNUSED.
Referenced by pmain().
Variable Documentation
dumping
int dumping =1 static
Definition at line 30 of file lua-5.1.5/src/luac.c.
Referenced by doargs(), and pmain().
listing
int listing =0 static
Definition at line 29 of file lua-5.1.5/src/luac.c.
Referenced by doargs(), and pmain().
Output
char Output[] ={ OUTPUT } static
Definition at line 32 of file lua-5.1.5/src/luac.c.
{ OUTPUT }; /* default output file name */
Referenced by doargs(), and usage().
output
const char* output =Output static
Definition at line 33 of file lua-5.1.5/src/luac.c.
Referenced by cannot(), display_output(), doargs(), get_req_headers(), and pmain().
progname
const char* progname =PROGNAME static
Definition at line 34 of file lua-5.1.5/src/luac.c.
Referenced by cannot(), doargs(), fatal(), and usage().
stripping
int stripping =0 static
Definition at line 31 of file lua-5.1.5/src/luac.c.
Referenced by doargs(), and pmain().