Github User Fetcher: lmathlib.c File Reference
lmathlib.c File Reference
#include "lprefix.h"
#include <stdlib.h>
#include <math.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lmathlib_c
#define LUA_LIB
#define PI (l_mathop(3.141592653589793238462643383279502884))
#define l_rand() rand()
#define l_srand(x) srand(x)
#define L_RANDMAX RAND_MAX
Functions
static int math_abs (lua_State *L)
static int math_sin (lua_State *L)
static int math_cos (lua_State *L)
static int math_tan (lua_State *L)
static int math_asin (lua_State *L)
static int math_acos (lua_State *L)
static int math_atan (lua_State *L)
static int math_toint (lua_State *L)
static void pushnumint (lua_State *L, lua_Number d)
static int math_floor (lua_State *L)
static int math_ceil (lua_State *L)
static int math_fmod (lua_State *L)
static int math_modf (lua_State *L)
static int math_sqrt (lua_State *L)
static int math_ult (lua_State *L)
static int math_log (lua_State *L)
static int math_exp (lua_State *L)
static int math_deg (lua_State *L)
static int math_rad (lua_State *L)
static int math_min (lua_State *L)
static int math_max (lua_State *L)
static int math_random (lua_State *L)
static int math_randomseed (lua_State *L)
static int math_type (lua_State *L)
LUAMOD_API int luaopen_math (lua_State *L)
Variables
static const luaL_Reg mathlib []
Macro Definition Documentation
l_rand
#define l_rand () rand()
Definition at line 32 of file lua-5.3.6/src/lmathlib.c.
Referenced by math_random(), and math_randomseed().
L_RANDMAX
#define L_RANDMAX RAND_MAX
Definition at line 34 of file lua-5.3.6/src/lmathlib.c.
Referenced by math_random().
l_srand
#define l_srand (x) srand(x)
Definition at line 33 of file lua-5.3.6/src/lmathlib.c.
Referenced by math_randomseed().
lmathlib_c
#define lmathlib_c
Definition at line 7 of file lua-5.3.6/src/lmathlib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.3.6/src/lmathlib.c.
PI
#define PI (l_mathop(3.141592653589793238462643383279502884))
Definition at line 23 of file lua-5.3.6/src/lmathlib.c.
Referenced by luaopen_math(), math_deg(), and math_rad().
Function Documentation
luaopen_math()
LUAMOD_API int luaopen_math (lua_State * L)
Definition at line 398 of file lua-5.3.6/src/lmathlib.c.
{
  luaL_newlib(L, mathlib);
  lua_pushnumber(L, PI);
  lua_setfield(L, -2, "pi");
  lua_pushnumber(L, (lua_Number)HUGE_VAL);
  lua_setfield(L, -2, "huge");
  lua_pushinteger(L, LUA_MAXINTEGER);
  lua_setfield(L, -2, "maxinteger");
  lua_pushinteger(L, LUA_MININTEGER);
  lua_setfield(L, -2, "mininteger");
  return 1;
}
References lua_pushinteger(), lua_pushnumber(), lua_setfield(), luaL_newlib, mathlib, and PI.
math_abs()
static int math_abs (lua_State * L) static
Definition at line 39 of file lua-5.3.6/src/lmathlib.c.
{
  if (lua_isinteger(L, 1)) {
    lua_Integer n = lua_tointeger(L, 1);
    if (n < 0) n = (lua_Integer)(0u - (lua_Unsigned)n);
    lua_pushinteger(L, n);
  }
  else
    lua_pushnumber(L, l_mathop(fabs)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_isinteger(), lua_pushinteger(), lua_pushnumber(), lua_tointeger, and luaL_checknumber().
math_acos()
static int math_acos (lua_State * L) static
Definition at line 70 of file lua-5.3.6/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(acos)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_asin()
static int math_asin (lua_State * L) static
Definition at line 65 of file lua-5.3.6/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(asin)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_atan()
static int math_atan (lua_State * L) static
Definition at line 75 of file lua-5.3.6/src/lmathlib.c.
{
  lua_Number y = luaL_checknumber(L, 1);
  lua_Number x = luaL_optnumber(L, 2, 1);
  lua_pushnumber(L, l_mathop(atan2)(y, x));
  return 1;
}
References l_mathop, lua_pushnumber(), luaL_checknumber(), and luaL_optnumber().
math_ceil()
static int math_ceil (lua_State * L) static
Definition at line 116 of file lua-5.3.6/src/lmathlib.c.
{
  if (lua_isinteger(L, 1))
    lua_settop(L, 1);  /* integer is its own ceil */
  else {
    lua_Number d = l_mathop(ceil)(luaL_checknumber(L, 1));
    pushnumint(L, d);
  }
  return 1;
}
References l_mathop, lua_isinteger(), lua_settop(), luaL_checknumber(), and pushnumint().
math_cos()
static int math_cos (lua_State * L) static
Definition at line 55 of file lua-5.3.6/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(cos)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_deg()
static int math_deg (lua_State * L) static
Definition at line 204 of file lua-5.3.6/src/lmathlib.c.
{
  lua_pushnumber(L, luaL_checknumber(L, 1) * (l_mathop(180.0) / PI));
  return 1;
}
References l_mathop, lua_pushnumber(), luaL_checknumber(), and PI.
math_exp()
static int math_exp (lua_State * L) static
Definition at line 199 of file lua-5.3.6/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(exp)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_floor()
static int math_floor (lua_State * L) static
Definition at line 105 of file lua-5.3.6/src/lmathlib.c.
{
  if (lua_isinteger(L, 1))
    lua_settop(L, 1);  /* integer is its own floor */
  else {
    lua_Number d = l_mathop(floor)(luaL_checknumber(L, 1));
    pushnumint(L, d);
  }
  return 1;
}
References l_mathop, lua_isinteger(), lua_settop(), luaL_checknumber(), and pushnumint().
math_fmod()
static int math_fmod (lua_State * L) static
Definition at line 127 of file lua-5.3.6/src/lmathlib.c.
{
  if (lua_isinteger(L, 1) && lua_isinteger(L, 2)) {
    lua_Integer d = lua_tointeger(L, 2);
    if ((lua_Unsigned)d + 1u <= 1u) {  /* special cases: -1 or 0 */
      luaL_argcheck(L, d != 0, 2, "zero");
      lua_pushinteger(L, 0);  /* avoid overflow with 0x80000... / -1 */
    }
    else
      lua_pushinteger(L, lua_tointeger(L, 1) % d);
  }
  else
    lua_pushnumber(L, l_mathop(fmod)(luaL_checknumber(L, 1),
                                     luaL_checknumber(L, 2)));
  return 1;
}
References l_mathop, lua_isinteger(), lua_pushinteger(), lua_pushnumber(), lua_tointeger, luaL_argcheck, and luaL_checknumber().
math_log()
static int math_log (lua_State * L) static
Definition at line 179 of file lua-5.3.6/src/lmathlib.c.
{
  lua_Number x = luaL_checknumber(L, 1);
  lua_Number res;
  if (lua_isnoneornil(L, 2))
    res = l_mathop(log)(x);
  else {
    lua_Number base = luaL_checknumber(L, 2);
#if !defined(LUA_USE_C89)
    if (base == l_mathop(2.0))
      res = l_mathop(log2)(x); else
#endif
    if (base == l_mathop(10.0))
      res = l_mathop(log10)(x);
    else
      res = l_mathop(log)(x)/l_mathop(log)(base);
  }
  lua_pushnumber(L, res);
  return 1;
}
References l_mathop, lua_isnoneornil, lua_pushnumber(), and luaL_checknumber().
math_max()
static int math_max (lua_State * L) static
Definition at line 229 of file lua-5.3.6/src/lmathlib.c.
{
  int n = lua_gettop(L);  /* number of arguments */
  int imax = 1;  /* index of current maximum value */
  int i;
  luaL_argcheck(L, n >= 1, 1, "value expected");
  for (i = 2; i <= n; i++) {
    if (lua_compare(L, imax, i, LUA_OPLT))
      imax = i;
  }
  lua_pushvalue(L, imax);
  return 1;
}
References lua_compare(), lua_gettop(), LUA_OPLT, lua_pushvalue(), and luaL_argcheck.
math_min()
static int math_min (lua_State * L) static
Definition at line 215 of file lua-5.3.6/src/lmathlib.c.
{
  int n = lua_gettop(L);  /* number of arguments */
  int imin = 1;  /* index of current minimum value */
  int i;
  luaL_argcheck(L, n >= 1, 1, "value expected");
  for (i = 2; i <= n; i++) {
    if (lua_compare(L, i, imin, LUA_OPLT))
      imin = i;
  }
  lua_pushvalue(L, imin);
  return 1;
}
References lua_compare(), lua_gettop(), LUA_OPLT, lua_pushvalue(), and luaL_argcheck.
math_modf()
static int math_modf (lua_State * L) static
Definition at line 149 of file lua-5.3.6/src/lmathlib.c.
{
  if (lua_isinteger(L ,1)) {
    lua_settop(L, 1);  /* number is its own integer part */
    lua_pushnumber(L, 0);  /* no fractional part */
  }
  else {
    lua_Number n = luaL_checknumber(L, 1);
    /* integer part (rounds toward zero) */
    lua_Number ip = (n < 0) ? l_mathop(ceil)(n) : l_mathop(floor)(n);
    pushnumint(L, ip);
    /* fractional part (test needed for inf/-inf) */
    lua_pushnumber(L, (n == ip) ? l_mathop(0.0) : (n - ip));
  }
  return 2;
}
References l_mathop, lua_isinteger(), lua_pushnumber(), lua_settop(), luaL_checknumber(), and pushnumint().
math_rad()
static int math_rad (lua_State * L) static
Definition at line 209 of file lua-5.3.6/src/lmathlib.c.
{
  lua_pushnumber(L, luaL_checknumber(L, 1) * (PI / l_mathop(180.0)));
  return 1;
}
References l_mathop, lua_pushnumber(), luaL_checknumber(), and PI.
math_random()
static int math_random (lua_State * L) static
Definition at line 247 of file lua-5.3.6/src/lmathlib.c.
{
  lua_Integer low, up;
  double r = (double)l_rand() * (1.0 / ((double)L_RANDMAX + 1.0));
  switch (lua_gettop(L)) {  /* check number of arguments */
    case 0: {  /* no arguments */
      lua_pushnumber(L, (lua_Number)r);  /* Number between 0 and 1 */
      return 1;
    }
    case 1: {  /* only upper limit */
      low = 1;
      up = luaL_checkinteger(L, 1);
      break;
    }
    case 2: {  /* lower and upper limits */
      low = luaL_checkinteger(L, 1);
      up = luaL_checkinteger(L, 2);
      break;
    }
    default: return luaL_error(L, "wrong number of arguments");
  }
  /* random integer in the interval [low, up] */
  luaL_argcheck(L, low <= up, 1, "interval is empty");
  luaL_argcheck(L, low >= 0 || up <= LUA_MAXINTEGER + low, 1,
                   "interval too large");
  r *= (double)(up - low) + 1.0;
  lua_pushinteger(L, (lua_Integer)r + low);
  return 1;
}
References l_rand, L_RANDMAX, lua_gettop(), lua_pushinteger(), lua_pushnumber(), luaL_argcheck, luaL_checkinteger(), and luaL_error().
math_randomseed()
static int math_randomseed (lua_State * L) static
Definition at line 277 of file lua-5.3.6/src/lmathlib.c.
{
  l_srand((unsigned int)(lua_Integer)luaL_checknumber(L, 1));
  (void)l_rand(); /* discard first value to avoid undesirable correlations */
  return 0;
}
References l_rand, l_srand, and luaL_checknumber().
math_sin()
static int math_sin (lua_State * L) static
Definition at line 50 of file lua-5.3.6/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(sin)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_sqrt()
static int math_sqrt (lua_State * L) static
Definition at line 166 of file lua-5.3.6/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(sqrt)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_tan()
static int math_tan (lua_State * L) static
Definition at line 60 of file lua-5.3.6/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(tan)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_toint()
static int math_toint (lua_State * L) static
Definition at line 83 of file lua-5.3.6/src/lmathlib.c.
{
  int valid;
  lua_Integer n = lua_tointegerx(L, 1, &valid);
  if (valid)
    lua_pushinteger(L, n);
  else {
    luaL_checkany(L, 1);
    lua_pushnil(L);  /* value is not convertible to integer */
  }
  return 1;
}
References lua_pushinteger(), lua_pushnil(), lua_tointegerx(), and luaL_checkany().
math_type()
static int math_type (lua_State * L) static
Definition at line 284 of file lua-5.3.6/src/lmathlib.c.
{
  if (lua_type(L, 1) == LUA_TNUMBER) {
      if (lua_isinteger(L, 1))
        lua_pushliteral(L, "integer");
      else
        lua_pushliteral(L, "float");
  }
  else {
    luaL_checkany(L, 1);
    lua_pushnil(L);
  }
  return 1;
}
References lua_isinteger(), lua_pushliteral, lua_pushnil(), LUA_TNUMBER, lua_type(), and luaL_checkany().
math_ult()
static int math_ult (lua_State * L) static
Definition at line 172 of file lua-5.3.6/src/lmathlib.c.
{
  lua_Integer a = luaL_checkinteger(L, 1);
  lua_Integer b = luaL_checkinteger(L, 2);
  lua_pushboolean(L, (lua_Unsigned)a < (lua_Unsigned)b);
  return 1;
}
References lua_pushboolean(), and luaL_checkinteger().
pushnumint()
static void pushnumint (lua_State * L, lua_Number d) static
Definition at line 96 of file lua-5.3.6/src/lmathlib.c.
{
  lua_Integer n;
  if (lua_numbertointeger(d, &n))  /* does 'd' fit in an integer? */
    lua_pushinteger(L, n);  /* result is integer */
  else
    lua_pushnumber(L, d);  /* result is float */
}
References lua_numbertointeger, lua_pushinteger(), and lua_pushnumber().
Referenced by math_ceil(), math_floor(), and math_modf().
Variable Documentation
mathlib
const luaL_Reg mathlib[] static
Definition at line 352 of file lua-5.3.6/src/lmathlib.c.
{
  {"abs",   math_abs},
  {"acos",  math_acos},
  {"asin",  math_asin},
  {"atan",  math_atan},
  {"ceil",  math_ceil},
  {"cos",   math_cos},
  {"deg",   math_deg},
  {"exp",   math_exp},
  {"tointeger", math_toint},
  {"floor", math_floor},
  {"fmod",   math_fmod},
  {"ult",   math_ult},
  {"log",   math_log},
  {"max",   math_max},
  {"min",   math_min},
  {"modf",   math_modf},
  {"rad",   math_rad},
  {"random",     math_random},
  {"randomseed", math_randomseed},
  {"sin",   math_sin},
  {"sqrt",  math_sqrt},
  {"tan",   math_tan},
  {"type", math_type},
#if defined(LUA_COMPAT_MATHLIB)
  {"atan2", math_atan},
  {"cosh",   math_cosh},
  {"sinh",   math_sinh},
  {"tanh",   math_tanh},
  {"pow",   math_pow},
  {"frexp", math_frexp},
  {"ldexp", math_ldexp},
  {"log10", math_log10},
#endif
  /* placeholders */
  {"pi", NULL},
  {"huge", NULL},
  {"maxinteger", NULL},
  {"mininteger", NULL},
  {NULL, NULL}
};
Referenced by luaopen_math().