Github User Fetcher: lundump.c File Reference
lundump.c File Reference
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstring.h"
#include "lundump.h"
#include "lzio.h"
Data Structures
struct LoadState
Macros
#define lundump_c
#define LUA_CORE
#define IF(c, s) if (c) error(S,s)
#define LoadMem(S, b, n, size) LoadBlock(S,b,(n)*(size))
#define LoadByte(S) (lu_byte)LoadChar(S)
#define LoadVar(S, x) LoadMem(S,&x,1,sizeof(x))
#define LoadVector(S, b, n, size) LoadMem(S,b,n,size)
Functions
static void error (LoadState *S, const char *why)
static void LoadBlock (LoadState *S, void *b, size_t size)
static int LoadChar (LoadState *S)
static int LoadInt (LoadState *S)
static lua_Number LoadNumber (LoadState *S)
static TString * LoadString (LoadState *S)
static void LoadCode (LoadState *S, Proto *f)
static Proto * LoadFunction (LoadState *S, TString *p)
static void LoadConstants (LoadState *S, Proto *f)
static void LoadDebug (LoadState *S, Proto *f)
static void LoadHeader (LoadState *S)
Proto * luaU_undump (lua_State *L, ZIO *Z, Mbuffer *buff, const char *name)
void luaU_header (char *h)
Macro Definition Documentation
IF
#define IF (c, s) if (c) error(S,s)
Definition at line 34 of file lua-5.1.5/src/lundump.c.
Referenced by LoadBlock(), LoadFunction(), LoadHeader(), and LoadInt().
LoadByte
#define LoadByte (S) (lu_byte)LoadChar(S)
Definition at line 44 of file lua-5.1.5/src/lundump.c.
Referenced by checkHeader(), fchecksize(), LoadConstants(), LoadFunction(), LoadFunction(), LoadString(), LoadUpvalues(), and luaU_undump().
LoadMem
#define LoadMem (S, b, n, size) LoadBlock(S,b,(n)*(size))
Definition at line 43 of file lua-5.1.5/src/lundump.c.
LoadVar
#define LoadVar (S, x) LoadMem(S,&x,1,sizeof(x))
Definition at line 45 of file lua-5.1.5/src/lundump.c.
Referenced by LoadChar(), LoadInt(), LoadNumber(), and LoadString().
LoadVector
#define LoadVector (S, b, n, size) LoadMem(S,b,n,size)
Definition at line 46 of file lua-5.1.5/src/lundump.c.
Referenced by LoadCode(), and LoadDebug().
LUA_CORE
#define LUA_CORE
Definition at line 10 of file lua-5.1.5/src/lundump.c.
lundump_c
#define lundump_c
Definition at line 9 of file lua-5.1.5/src/lundump.c.
Function Documentation
error()
static void error (LoadState * S, const char * why) static
Definition at line 36 of file lua-5.1.5/src/lundump.c.
{
 luaO_pushfstring(S->L,"%s: %s in precompiled chunk",S->name,why);
 luaD_throw(S->L,LUA_ERRSYNTAX);
}
References LUA_ERRSYNTAX, luaD_throw(), luaO_pushfstring(), and S.
Referenced by connect_socket(), duk__base64_decode_helper(), duk__hobject_pc2line_query_raw(), duk__init_heap_strings(), duk__parse_regexp_flags(), duk_base64_encode(), duk_bi_date_get_local_tzoffset_gmtime(), duk_default_panic_handler(), duk_hbuffer_alloc(), duk_heap_alloc(), duk_heap_strcache_offset_char2byte(), duk_hthread_create_builtin_objects(), fetch_github_user(), fileio_readfile(), fileio_readfile(), g_clear_fd(), g_unix_pipe_close(), g_unix_pipe_open(), handle_fh(), handle_fh(), handle_fh(), handle_file(), handle_file(), handle_file(), LoadConstants(), LoadFunction(), mg_connect_client(), mg_connect_client_impl(), mg_connect_client_secure(), mg_connect_websocket_client_impl(), mg_start2(), mg_start_domain2(), on_button_clicked(), and start_civetweb().
LoadBlock()
static void LoadBlock (LoadState * S, void * b, size_t size) static
Definition at line 48 of file lua-5.1.5/src/lundump.c.
{
 size_t r=luaZ_read(S->Z,b,size);
 IF (r!=0, "unexpected end");
}
References IF, luaZ_read(), and S.
Referenced by LoadHeader(), and LoadString().
LoadChar()
static int LoadChar (LoadState * S) static
Definition at line 54 of file lua-5.1.5/src/lundump.c.
{
 char x;
 LoadVar(S,x);
 return x;
}
References LoadVar, and S.
Referenced by LoadConstants().
LoadCode()
static void LoadCode (LoadState * S, Proto * f) static
Definition at line 90 of file lua-5.1.5/src/lundump.c.
{
 int n=LoadInt(S);
 f->code=luaM_newvector(S->L,n,Instruction);
 f->sizecode=n;
 LoadVector(S,f->code,n,sizeof(Instruction));
}
References Proto::code, LoadInt(), LoadVector, luaM_newvector, S, and Proto::sizecode.
Referenced by LoadFunction().
LoadConstants()
static void LoadConstants (LoadState * S, Proto * f) static
Definition at line 100 of file lua-5.1.5/src/lundump.c.
{
 int i,n;
 n=LoadInt(S);
 f->k=luaM_newvector(S->L,n,TValue);
 f->sizek=n;
 for (i=0; i<n; i++) setnilvalue(&f->k[i]);
 for (i=0; i<n; i++)
 {
  TValue* o=&f->k[i];
  int t=LoadChar(S);
  switch (t)
  {
   case LUA_TNIL:
    setnilvalue(o);
    break;
   case LUA_TBOOLEAN:
    setbvalue(o,LoadChar(S)!=0);
    break;
   case LUA_TNUMBER:
    setnvalue(o,LoadNumber(S));
    break;
   case LUA_TSTRING:
    setsvalue2n(S->L,o,LoadString(S));
    break;
   default:
    error(S,"bad constant");
    break;
  }
 }
 n=LoadInt(S);
 f->p=luaM_newvector(S->L,n,Proto*);
 f->sizep=n;
 for (i=0; i<n; i++) f->p[i]=NULL;
 for (i=0; i<n; i++) f->p[i]=LoadFunction(S,f->source);
}
References error(), Proto::k, LoadChar(), LoadFunction(), LoadInt(), LoadNumber(), LoadString(), LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, LUA_TSTRING, luaM_newvector, NULL, Proto::p, S, setbvalue, setnilvalue, setnvalue, setsvalue2n, Proto::sizek, Proto::sizep, and Proto::source.
Referenced by LoadFunction().
LoadDebug()
static void LoadDebug (LoadState * S, Proto * f) static
Definition at line 137 of file lua-5.1.5/src/lundump.c.
{
 int i,n;
 n=LoadInt(S);
 f->lineinfo=luaM_newvector(S->L,n,int);
 f->sizelineinfo=n;
 LoadVector(S,f->lineinfo,n,sizeof(int));
 n=LoadInt(S);
 f->locvars=luaM_newvector(S->L,n,LocVar);
 f->sizelocvars=n;
 for (i=0; i<n; i++) f->locvars[i].varname=NULL;
 for (i=0; i<n; i++)
 {
  f->locvars[i].varname=LoadString(S);
  f->locvars[i].startpc=LoadInt(S);
  f->locvars[i].endpc=LoadInt(S);
 }
 n=LoadInt(S);
 f->upvalues=luaM_newvector(S->L,n,TString*);
 f->sizeupvalues=n;
 for (i=0; i<n; i++) f->upvalues[i]=NULL;
 for (i=0; i<n; i++) f->upvalues[i]=LoadString(S);
}
References LocVar::endpc, Proto::lineinfo, LoadInt(), LoadString(), LoadVector, Proto::locvars, luaM_newvector, NULL, S, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizeupvalues, LocVar::startpc, Proto::upvalues, and LocVar::varname.
Referenced by LoadFunction().
LoadFunction()
static Proto * LoadFunction (LoadState * S, TString * p) static
Definition at line 161 of file lua-5.1.5/src/lundump.c.
{
 Proto* f;
 if (++S->L->nCcalls > LUAI_MAXCCALLS) error(S,"code too deep");
 f=luaF_newproto(S->L);
 setptvalue2s(S->L,S->L->top,f); incr_top(S->L);
 f->source=LoadString(S); if (f->source==NULL) f->source=p;
 f->linedefined=LoadInt(S);
 f->lastlinedefined=LoadInt(S);
 f->nups=LoadByte(S);
 f->numparams=LoadByte(S);
 f->is_vararg=LoadByte(S);
 f->maxstacksize=LoadByte(S);
 LoadCode(S,f);
 LoadConstants(S,f);
 LoadDebug(S,f);
 IF (!luaG_checkcode(f), "bad code");
 S->L->top--;
 S->L->nCcalls--;
 return f;
}
References error(), IF, incr_top, Proto::is_vararg, Proto::lastlinedefined, Proto::linedefined, LoadByte, LoadCode(), LoadConstants(), LoadDebug(), LoadInt(), LoadString(), luaF_newproto(), luaG_checkcode(), LUAI_MAXCCALLS, Proto::maxstacksize, NULL, Proto::numparams, Proto::nups, S, setptvalue2s, and Proto::source.
Referenced by LoadConstants(), and luaU_undump().
LoadHeader()
static void LoadHeader (LoadState * S) static
Definition at line 183 of file lua-5.1.5/src/lundump.c.
{
 char h[LUAC_HEADERSIZE];
 char s[LUAC_HEADERSIZE];
 luaU_header(h);
 LoadBlock(S,s,LUAC_HEADERSIZE);
 IF (memcmp(h,s,LUAC_HEADERSIZE)!=0, "bad header");
}
References IF, LoadBlock(), LUAC_HEADERSIZE, luaU_header(), S, and s.
Referenced by luaU_undump().
LoadInt()
static int LoadInt (LoadState * S) static
Definition at line 61 of file lua-5.1.5/src/lundump.c.
{
 int x;
 LoadVar(S,x);
 IF (x<0, "bad integer");
 return x;
}
References IF, LoadVar, and S.
Referenced by LoadCode(), LoadConstants(), LoadDebug(), and LoadFunction().
LoadNumber()
static lua_Number LoadNumber (LoadState * S) static
Definition at line 69 of file lua-5.1.5/src/lundump.c.
{
 lua_Number x;
 LoadVar(S,x);
 return x;
}
References LoadVar, and S.
Referenced by LoadConstants().
LoadString()
static TString * LoadString (LoadState * S) static
Definition at line 76 of file lua-5.1.5/src/lundump.c.
{
 size_t size;
 LoadVar(S,size);
 if (size==0)
  return NULL;
 else
 {
  char* s=luaZ_openspace(S->L,S->b,size);
  LoadBlock(S,s,size);
  return luaS_newlstr(S->L,s,size-1);       /* remove trailing '\0' */
 }
}
References LoadBlock(), LoadVar, luaS_newlstr(), luaZ_openspace(), NULL, S, and s.
Referenced by LoadConstants(), LoadDebug(), and LoadFunction().
luaU_header()
void luaU_header (char * h)
Definition at line 214 of file lua-5.1.5/src/lundump.c.
{
 int x=1;
 memcpy(h,LUA_SIGNATURE,sizeof(LUA_SIGNATURE)-1);
 h+=sizeof(LUA_SIGNATURE)-1;
 *h++=(char)LUAC_VERSION;
 *h++=(char)LUAC_FORMAT;
 *h++=(char)*(char*)&x;             /* endianness */
 *h++=(char)sizeof(int);
 *h++=(char)sizeof(size_t);
 *h++=(char)sizeof(Instruction);
 *h++=(char)sizeof(lua_Number);
 *h++=(char)(((lua_Number)0.5)==0);     /* is lua_Number integral? */
}
References LUA_SIGNATURE, LUAC_FORMAT, and LUAC_VERSION.
Referenced by DumpHeader(), DumpHeader(), and LoadHeader().
luaU_undump()
Proto * luaU_undump (lua_State * L, ZIO * Z, Mbuffer * buff, const char * name)
Definition at line 195 of file lua-5.1.5/src/lundump.c.
{
 LoadState S;
 if (*name=='@' || *name=='=')
  S.name=name+1;
 else if (*name==LUA_SIGNATURE[0])
  S.name="binary string";
 else
  S.name=name;
 S.L=L;
 S.Z=Z;
 S.b=buff;
 LoadHeader(&S);
 return LoadFunction(&S,luaS_newliteral(L,"=?"));
}
References LoadFunction(), LoadHeader(), LUA_SIGNATURE, luaS_newliteral, name, LoadState::name, and S.
Referenced by f_parser(), f_parser(), f_parser(), and f_parser().