Github User Fetcher: lcode.c File Reference
lcode.c File Reference
#include "lprefix.h"
#include <math.h>
#include <stdlib.h>
#include "lua.h"
#include "lcode.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "llex.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
#include "lstring.h"
#include "ltable.h"
#include "lvm.h"
Macros
#define lcode_c
#define LUA_CORE
#define MAXREGS 255
#define hasjumps(e) ((e)->t != (e)->f)
Functions
static int tonumeral (const expdesc *e, TValue *v)
void luaK_nil (FuncState *fs, int from, int n)
static int getjump (FuncState *fs, int pc)
static void fixjump (FuncState *fs, int pc, int dest)
void luaK_concat (FuncState *fs, int *l1, int l2)
int luaK_jump (FuncState *fs)
void luaK_ret (FuncState *fs, int first, int nret)
static int condjump (FuncState *fs, OpCode op, int A, int B, int C)
int luaK_getlabel (FuncState *fs)
static Instruction * getjumpcontrol (FuncState *fs, int pc)
static int patchtestreg (FuncState *fs, int node, int reg)
static void removevalues (FuncState *fs, int list)
static void patchlistaux (FuncState *fs, int list, int vtarget, int reg, int dtarget)
static void dischargejpc (FuncState *fs)
void luaK_patchtohere (FuncState *fs, int list)
void luaK_patchlist (FuncState *fs, int list, int target)
void luaK_patchclose (FuncState *fs, int list, int level)
static int luaK_code (FuncState *fs, Instruction i)
int luaK_codeABC (FuncState *fs, OpCode o, int a, int b, int c)
int luaK_codeABx (FuncState *fs, OpCode o, int a, unsigned int bc)
static int codeextraarg (FuncState *fs, int a)
int luaK_codek (FuncState *fs, int reg, int k)
void luaK_checkstack (FuncState *fs, int n)
void luaK_reserveregs (FuncState *fs, int n)
static void freereg (FuncState *fs, int reg)
static void freeexp (FuncState *fs, expdesc *e)
static void freeexps (FuncState *fs, expdesc *e1, expdesc *e2)
static int addk (FuncState *fs, TValue *key, TValue *v)
int luaK_stringK (FuncState *fs, TString *s)
int luaK_intK (FuncState *fs, lua_Integer n)
static int luaK_numberK (FuncState *fs, lua_Number r)
static int boolK (FuncState *fs, int b)
static int nilK (FuncState *fs)
void luaK_setreturns (FuncState *fs, expdesc *e, int nresults)
void luaK_setoneret (FuncState *fs, expdesc *e)
void luaK_dischargevars (FuncState *fs, expdesc *e)
static void discharge2reg (FuncState *fs, expdesc *e, int reg)
static void discharge2anyreg (FuncState *fs, expdesc *e)
static int code_loadbool (FuncState *fs, int A, int b, int jump)
static int need_value (FuncState *fs, int list)
static void exp2reg (FuncState *fs, expdesc *e, int reg)
void luaK_exp2nextreg (FuncState *fs, expdesc *e)
int luaK_exp2anyreg (FuncState *fs, expdesc *e)
void luaK_exp2anyregup (FuncState *fs, expdesc *e)
void luaK_exp2val (FuncState *fs, expdesc *e)
int luaK_exp2RK (FuncState *fs, expdesc *e)
void luaK_storevar (FuncState *fs, expdesc *var, expdesc *ex)
void luaK_self (FuncState *fs, expdesc *e, expdesc *key)
static void negatecondition (FuncState *fs, expdesc *e)
static int jumponcond (FuncState *fs, expdesc *e, int cond)
void luaK_goiftrue (FuncState *fs, expdesc *e)
void luaK_goiffalse (FuncState *fs, expdesc *e)
static void codenot (FuncState *fs, expdesc *e)
void luaK_indexed (FuncState *fs, expdesc *t, expdesc *k)
static int validop (int op, TValue *v1, TValue *v2)
static int constfolding (FuncState *fs, int op, expdesc *e1, const expdesc *e2)
static void codeunexpval (FuncState *fs, OpCode op, expdesc *e, int line)
static void codebinexpval (FuncState *fs, OpCode op, expdesc *e1, expdesc *e2, int line)
static void codecomp (FuncState *fs, BinOpr opr, expdesc *e1, expdesc *e2)
void luaK_prefix (FuncState *fs, UnOpr op, expdesc *e, int line)
void luaK_infix (FuncState *fs, BinOpr op, expdesc *v)
void luaK_posfix (FuncState *fs, BinOpr op, expdesc *e1, expdesc *e2, int line)
void luaK_fixline (FuncState *fs, int line)
void luaK_setlist (FuncState *fs, int base, int nelems, int tostore)
Macro Definition Documentation
hasjumps
#define hasjumps (e) ((e)->t != (e)->f)
Definition at line 36 of file lua-5.3.6/src/lcode.c.
Referenced by exp2reg(), luaK_exp2anyreg(), luaK_exp2anyregup(), luaK_exp2val(), luaK_indexed(), and tonumeral().
lcode_c
#define lcode_c
Definition at line 7 of file lua-5.3.6/src/lcode.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/lcode.c.
MAXREGS
#define MAXREGS 255
Definition at line 33 of file lua-5.3.6/src/lcode.c.
Referenced by luaK_checkstack().
Function Documentation
addk()
static int addk (FuncState * fs, TValue * key, TValue * v) static
Definition at line 428 of file lua-5.3.6/src/lcode.c.
{
  lua_State *L = fs->ls->L;
  Proto *f = fs->f;
  TValue *idx = luaH_set(L, fs->ls->h, key);  /* index scanner table */
  int k, oldsize;
  if (ttisinteger(idx)) {  /* is there an index there? */
    k = cast_int(ivalue(idx));
    /* correct value? (warning: must distinguish floats from integers!) */
    if (k < fs->nk && ttype(&f->k[k]) == ttype(v) &&
                      luaV_rawequalobj(&f->k[k], v))
      return k;  /* reuse index */
  }
  /* constant not found; create a new entry */
  oldsize = f->sizek;
  k = fs->nk;
  /* numerical value does not need GC barrier;
     table has no metatable, so it does not need to invalidate cache */
  setivalue(idx, k);
  luaM_growvector(L, f->k, k, f->sizek, TValue, MAXARG_Ax, "constants");
  while (oldsize < f->sizek) setnilvalue(&f->k[oldsize++]);
  setobj(L, &f->k[k], v);
  fs->nk++;
  luaC_barrier(L, f, v);
  return k;
}
References cast_int, FuncState::f, LexState::h, ivalue, Proto::k, LexState::L, FuncState::ls, luaC_barrier, luaH_set(), luaM_growvector, luaV_rawequalobj, MAXARG_Ax, FuncState::nk, setivalue, setnilvalue, setobj, Proto::sizek, ttisinteger, and ttype.
Referenced by boolK(), luaK_intK(), luaK_numberK(), luaK_stringK(), and nilK().
boolK()
static int boolK (FuncState * fs, int b) static
Definition at line 491 of file lua-5.3.6/src/lcode.c.
{
  TValue o;
  setbvalue(&o, b);
  return addk(fs, &o, &o);  /* use boolean itself as key */
}
References addk(), and setbvalue.
Referenced by luaK_exp2RK().
code_loadbool()
static int code_loadbool (FuncState * fs, int A, int b, int jump) static
Definition at line 649 of file lua-5.3.6/src/lcode.c.
{
  luaK_getlabel(fs);  /* those instructions may be jump targets */
  return luaK_codeABC(fs, OP_LOADBOOL, A, b, jump);
}
References luaK_codeABC, luaK_getlabel(), and OP_LOADBOOL.
Referenced by exp2reg().
codebinexpval()
static void codebinexpval (FuncState * fs, OpCode op, expdesc * e1, expdesc * e2, int line) static
Definition at line 1022 of file lua-5.3.6/src/lcode.c.
{
  int rk2 = luaK_exp2RK(fs, e2);  /* both operands are "RK" */
  int rk1 = luaK_exp2RK(fs, e1);
  freeexps(fs, e1, e2);
  e1->u.info = luaK_codeABC(fs, op, 0, rk1, rk2);  /* generate opcode */
  e1->k = VRELOCABLE;  /* all those operations are relocatable */
  luaK_fixline(fs, line);
}
References freeexps(), expdesc::info, expdesc::k, luaK_codeABC, luaK_exp2RK(), luaK_fixline(), expdesc::u, and VRELOCABLE.
Referenced by luaK_posfix().
codecomp()
static void codecomp (FuncState * fs, BinOpr opr, expdesc * e1, expdesc * e2) static
Definition at line 1037 of file lua-5.3.6/src/lcode.c.
{
  int rk1 = (e1->k == VK) ? RKASK(e1->u.info)
                          : check_exp(e1->k == VNONRELOC, e1->u.info);
  int rk2 = luaK_exp2RK(fs, e2);
  freeexps(fs, e1, e2);
  switch (opr) {
    case OPR_NE: {  /* '(a ~= b)' ==> 'not (a == b)' */
      e1->u.info = condjump(fs, OP_EQ, 0, rk1, rk2);
      break;
    }
    case OPR_GT: case OPR_GE: {
      /* '(a > b)' ==> '(b < a)';  '(a >= b)' ==> '(b <= a)' */
      OpCode op = cast(OpCode, (opr - OPR_NE) + OP_EQ);
      e1->u.info = condjump(fs, op, 1, rk2, rk1);  /* invert operands */
      break;
    }
    default: {  /* '==', '<', '<=' use their own opcodes */
      OpCode op = cast(OpCode, (opr - OPR_EQ) + OP_EQ);
      e1->u.info = condjump(fs, op, 1, rk1, rk2);
      break;
    }
  }
  e1->k = VJMP;
}
References cast, check_exp, condjump(), freeexps(), expdesc::info, expdesc::k, luaK_exp2RK(), OP_EQ, OPR_EQ, OPR_GE, OPR_GT, OPR_NE, RKASK, expdesc::u, VJMP, VK, and VNONRELOC.
Referenced by luaK_posfix().
codeextraarg()
static int codeextraarg (FuncState * fs, int a) static
Definition at line 335 of file lua-5.3.6/src/lcode.c.
{
  lua_assert(a <= MAXARG_Ax);
  return luaK_code(fs, CREATE_Ax(OP_EXTRAARG, a));
}
References CREATE_Ax, lua_assert, luaK_code(), MAXARG_Ax, and OP_EXTRAARG.
Referenced by luaK_codek(), and luaK_setlist().
codenot()
static void codenot (FuncState * fs, expdesc * e) static
Definition at line 910 of file lua-5.3.6/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VNIL: case VFALSE: {
      e->k = VTRUE;  /* true == not nil == not false */
      break;
    }
    case VK: case VKFLT: case VKINT: case VTRUE: {
      e->k = VFALSE;  /* false == not "x" == not 0.5 == not 1 == not true */
      break;
    }
    case VJMP: {
      negatecondition(fs, e);
      break;
    }
    case VRELOCABLE:
    case VNONRELOC: {
      discharge2anyreg(fs, e);
      freeexp(fs, e);
      e->u.info = luaK_codeABC(fs, OP_NOT, 0, e->u.info, 0);
      e->k = VRELOCABLE;
      break;
    }
    default: lua_assert(0);  /* cannot happen */
  }
  /* interchange true and false lists */
  { int temp = e->f; e->f = e->t; e->t = temp; }
  removevalues(fs, e->f);  /* values are useless when negated */
  removevalues(fs, e->t);
}
References discharge2anyreg(), expdesc::f, freeexp(), expdesc::info, expdesc::k, lua_assert, luaK_codeABC, luaK_dischargevars(), negatecondition(), OP_NOT, removevalues(), expdesc::t, expdesc::u, VFALSE, VJMP, VK, VKFLT, VKINT, VNIL, VNONRELOC, VRELOCABLE, and VTRUE.
Referenced by luaK_prefix().
codeunexpval()
static void codeunexpval (FuncState * fs, OpCode op, expdesc * e, int line) static
Definition at line 1004 of file lua-5.3.6/src/lcode.c.
{
  int r = luaK_exp2anyreg(fs, e);  /* opcodes operate only on registers */
  freeexp(fs, e);
  e->u.info = luaK_codeABC(fs, op, 0, r, 0);  /* generate opcode */
  e->k = VRELOCABLE;  /* all those operations are relocatable */
  luaK_fixline(fs, line);
}
References freeexp(), expdesc::info, expdesc::k, luaK_codeABC, luaK_exp2anyreg(), luaK_fixline(), expdesc::u, and VRELOCABLE.
Referenced by luaK_prefix().
condjump()
static int condjump (FuncState * fs, OpCode op, int A, int B, int C) static
Definition at line 158 of file lua-5.3.6/src/lcode.c.
{
  luaK_codeABC(fs, op, A, B, C);
  return luaK_jump(fs);
}
References luaK_codeABC, and luaK_jump().
Referenced by codecomp(), and jumponcond().
constfolding()
static int constfolding (FuncState * fs, int op, expdesc * e1, const expdesc * e2) static
Definition at line 978 of file lua-5.3.6/src/lcode.c.
{
  TValue v1, v2, res;
  if (!tonumeral(e1, &v1) || !tonumeral(e2, &v2) || !validop(op, &v1, &v2))
    return 0;  /* non-numeric operands or not safe to fold */
  luaO_arith(fs->ls->L, op, &v1, &v2, &res);  /* does operation */
  if (ttisinteger(&res)) {
    e1->k = VKINT;
    e1->u.ival = ivalue(&res);
  }
  else {  /* folds neither NaN nor 0.0 (to avoid problems with -0.0) */
    lua_Number n = fltvalue(&res);
    if (luai_numisnan(n) || n == 0)
      return 0;
    e1->k = VKFLT;
    e1->u.nval = n;
  }
  return 1;
}
References fltvalue, expdesc::ival, ivalue, expdesc::k, LexState::L, FuncState::ls, luai_numisnan, luaO_arith(), expdesc::nval, tonumeral(), ttisinteger, expdesc::u, validop(), VKFLT, and VKINT.
Referenced by luaK_posfix(), and luaK_prefix().
discharge2anyreg()
static void discharge2anyreg (FuncState * fs, expdesc * e) static
Definition at line 641 of file lua-5.3.6/src/lcode.c.
{
  if (e->k != VNONRELOC) {  /* no fixed register yet? */
    luaK_reserveregs(fs, 1);  /* get a register */
    discharge2reg(fs, e, fs->freereg-1);  /* put value there */
  }
}
References discharge2reg(), FuncState::freereg, expdesc::k, luaK_reserveregs(), and VNONRELOC.
Referenced by codenot(), and jumponcond().
discharge2reg()
static void discharge2reg (FuncState * fs, expdesc * e, int reg) static
Definition at line 595 of file lua-5.3.6/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VNIL: {
      luaK_nil(fs, reg, 1);
      break;
    }
    case VFALSE: case VTRUE: {
      luaK_codeABC(fs, OP_LOADBOOL, reg, e->k == VTRUE, 0);
      break;
    }
    case VK: {
      luaK_codek(fs, reg, e->u.info);
      break;
    }
    case VKFLT: {
      luaK_codek(fs, reg, luaK_numberK(fs, e->u.nval));
      break;
    }
    case VKINT: {
      luaK_codek(fs, reg, luaK_intK(fs, e->u.ival));
      break;
    }
    case VRELOCABLE: {
      Instruction *pc = &getinstruction(fs, e);
      SETARG_A(*pc, reg);  /* instruction will put result in 'reg' */
      break;
    }
    case VNONRELOC: {
      if (reg != e->u.info)
        luaK_codeABC(fs, OP_MOVE, reg, e->u.info, 0);
      break;
    }
    default: {
      lua_assert(e->k == VJMP);
      return;  /* nothing to do... */
    }
  }
  e->u.info = reg;
  e->k = VNONRELOC;
}
References getinstruction, expdesc::info, expdesc::ival, expdesc::k, lua_assert, luaK_codeABC, luaK_codek(), luaK_dischargevars(), luaK_intK(), luaK_nil(), luaK_numberK(), expdesc::nval, OP_LOADBOOL, OP_MOVE, SETARG_A, expdesc::u, VFALSE, VJMP, VK, VKFLT, VKINT, VNIL, VNONRELOC, VRELOCABLE, and VTRUE.
Referenced by discharge2anyreg(), and exp2reg().
dischargejpc()
static void dischargejpc (FuncState * fs) static
Definition at line 242 of file lua-5.3.6/src/lcode.c.
{
  patchlistaux(fs, fs->jpc, fs->pc, NO_REG, fs->pc);
  fs->jpc = NO_JUMP;
}
References FuncState::jpc, NO_JUMP, NO_REG, patchlistaux(), and FuncState::pc.
Referenced by luaK_code().
exp2reg()
static void exp2reg (FuncState * fs, expdesc * e, int reg) static
Definition at line 675 of file lua-5.3.6/src/lcode.c.
{
  discharge2reg(fs, e, reg);
  if (e->k == VJMP)  /* expression itself is a test? */
    luaK_concat(fs, &e->t, e->u.info);  /* put this jump in 't' list */
  if (hasjumps(e)) {
    int final;  /* position after whole expression */
    int p_f = NO_JUMP;  /* position of an eventual LOAD false */
    int p_t = NO_JUMP;  /* position of an eventual LOAD true */
    if (need_value(fs, e->t) || need_value(fs, e->f)) {
      int fj = (e->k == VJMP) ? NO_JUMP : luaK_jump(fs);
      p_f = code_loadbool(fs, reg, 0, 1);
      p_t = code_loadbool(fs, reg, 1, 0);
      luaK_patchtohere(fs, fj);
    }
    final = luaK_getlabel(fs);
    patchlistaux(fs, e->f, final, reg, p_f);
    patchlistaux(fs, e->t, final, reg, p_t);
  }
  e->f = e->t = NO_JUMP;
  e->u.info = reg;
  e->k = VNONRELOC;
}
References code_loadbool(), discharge2reg(), expdesc::f, hasjumps, expdesc::info, expdesc::k, luaK_concat(), luaK_getlabel(), luaK_jump(), luaK_patchtohere(), need_value(), NO_JUMP, patchlistaux(), expdesc::t, expdesc::u, VJMP, and VNONRELOC.
Referenced by luaK_exp2anyreg(), luaK_exp2nextreg(), and luaK_storevar().
fixjump()
static void fixjump (FuncState * fs, int pc, int dest) static
Definition at line 103 of file lua-5.3.6/src/lcode.c.
{
  Instruction *jmp = &fs->f->code[pc];
  int offset = dest - (pc + 1);
  lua_assert(dest != NO_JUMP);
  if (abs(offset) > MAXARG_sBx)
    luaX_syntaxerror(fs->ls, "control structure too long");
  SETARG_sBx(*jmp, offset);
}
References Proto::code, FuncState::f, FuncState::ls, lua_assert, luaX_syntaxerror(), MAXARG_sBx, NO_JUMP, and SETARG_sBx.
Referenced by luaK_concat(), and patchlistaux().
freeexp()
static void freeexp (FuncState * fs, expdesc * e) static
Definition at line 397 of file lua-5.3.6/src/lcode.c.
{
  if (e->k == VNONRELOC)
    freereg(fs, e->u.info);
}
References freereg(), expdesc::info, expdesc::k, expdesc::u, and VNONRELOC.
Referenced by codenot(), codeunexpval(), jumponcond(), luaK_exp2nextreg(), luaK_posfix(), luaK_self(), and luaK_storevar().
freeexps()
static void freeexps (FuncState * fs, expdesc * e1, expdesc * e2) static
Definition at line 407 of file lua-5.3.6/src/lcode.c.
{
  int r1 = (e1->k == VNONRELOC) ? e1->u.info : -1;
  int r2 = (e2->k == VNONRELOC) ? e2->u.info : -1;
  if (r1 > r2) {
    freereg(fs, r1);
    freereg(fs, r2);
  }
  else {
    freereg(fs, r2);
    freereg(fs, r1);
  }
}
References freereg(), expdesc::info, expdesc::k, expdesc::u, and VNONRELOC.
Referenced by codebinexpval(), and codecomp().
freereg()
static void freereg (FuncState * fs, int reg) static
Definition at line 386 of file lua-5.3.6/src/lcode.c.
{
  if (!ISK(reg) && reg >= fs->nactvar) {
    fs->freereg--;
    lua_assert(reg == fs->freereg);
  }
}
References FuncState::freereg, ISK, lua_assert, and FuncState::nactvar.
Referenced by freeexp(), freeexps(), and luaK_dischargevars().
getjump()
static int getjump (FuncState * fs, int pc) static
Definition at line 90 of file lua-5.3.6/src/lcode.c.
{
  int offset = GETARG_sBx(fs->f->code[pc]);
  if (offset == NO_JUMP)  /* point to itself represents end of list */
    return NO_JUMP;  /* end of list */
  else
    return (pc+1)+offset;  /* turn offset into absolute position */
}
References Proto::code, FuncState::f, GETARG_sBx, and NO_JUMP.
Referenced by luaK_concat(), luaK_patchclose(), need_value(), patchlistaux(), and removevalues().
getjumpcontrol()
static Instruction * getjumpcontrol (FuncState * fs, int pc) static
Definition at line 179 of file lua-5.3.6/src/lcode.c.
{
  Instruction *pi = &fs->f->code[pc];
  if (pc >= 1 && testTMode(GET_OPCODE(*(pi-1))))
    return pi-1;
  else
    return pi;
}
References Proto::code, FuncState::f, GET_OPCODE, and testTMode.
Referenced by need_value(), negatecondition(), and patchtestreg().
jumponcond()
static int jumponcond (FuncState * fs, expdesc * e, int cond) static
Definition at line 839 of file lua-5.3.6/src/lcode.c.
{
  if (e->k == VRELOCABLE) {
    Instruction ie = getinstruction(fs, e);
    if (GET_OPCODE(ie) == OP_NOT) {
      fs->pc--;  /* remove previous OP_NOT */
      return condjump(fs, OP_TEST, GETARG_B(ie), 0, !cond);
    }
    /* else go through */
  }
  discharge2anyreg(fs, e);
  freeexp(fs, e);
  return condjump(fs, OP_TESTSET, NO_REG, e->u.info, cond);
}
References cond(), condjump(), discharge2anyreg(), freeexp(), GET_OPCODE, GETARG_B, getinstruction, expdesc::info, expdesc::k, NO_REG, OP_NOT, OP_TEST, OP_TESTSET, FuncState::pc, expdesc::u, and VRELOCABLE.
Referenced by luaK_goiffalse(), and luaK_goiftrue().
luaK_checkstack()
void luaK_checkstack (FuncState * fs, int n)
Definition at line 361 of file lua-5.3.6/src/lcode.c.
{
  int newstack = fs->freereg + n;
  if (newstack > fs->f->maxstacksize) {
    if (newstack >= MAXREGS)
      luaX_syntaxerror(fs->ls,
        "function or expression needs too many registers");
    fs->f->maxstacksize = cast_byte(newstack);
  }
}
References cast_byte, FuncState::f, FuncState::freereg, FuncState::ls, luaX_syntaxerror(), MAXREGS, and Proto::maxstacksize.
Referenced by luaK_reserveregs().
luaK_code()
static int luaK_code (FuncState * fs, Instruction i) static
Definition at line 293 of file lua-5.3.6/src/lcode.c.
{
  Proto *f = fs->f;
  dischargejpc(fs);  /* 'pc' will change */
  /* put new instruction in code array */
  luaM_growvector(fs->ls->L, f->code, fs->pc, f->sizecode, Instruction,
                  MAX_INT, "opcodes");
  f->code[fs->pc] = i;
  /* save corresponding line information */
  luaM_growvector(fs->ls->L, f->lineinfo, fs->pc, f->sizelineinfo, int,
                  MAX_INT, "opcodes");
  f->lineinfo[fs->pc] = fs->ls->lastline;
  return fs->pc++;
}
References Proto::code, dischargejpc(), FuncState::f, LexState::L, LexState::lastline, Proto::lineinfo, FuncState::ls, luaM_growvector, MAX_INT, FuncState::pc, Proto::sizecode, and Proto::sizelineinfo.
Referenced by codeextraarg(), luaK_codeABC(), and luaK_codeABx().
luaK_codeABC()
int luaK_codeABC (FuncState * fs, OpCode o, int a, int b, int c)
Definition at line 312 of file lua-5.3.6/src/lcode.c.
{
  lua_assert(getOpMode(o) == iABC);
  lua_assert(getBMode(o) != OpArgN || b == 0);
  lua_assert(getCMode(o) != OpArgN || c == 0);
  lua_assert(a <= MAXARG_A && b <= MAXARG_B && c <= MAXARG_C);
  return luaK_code(fs, CREATE_ABC(o, a, b, c));
}
References CREATE_ABC, getBMode, getCMode, getOpMode, iABC, lua_assert, luaK_code(), MAXARG_A, MAXARG_B, MAXARG_C, and OpArgN.
luaK_codeABx()
int luaK_codeABx (FuncState * fs, OpCode o, int a, unsigned int bc)
Definition at line 324 of file lua-5.3.6/src/lcode.c.
{
  lua_assert(getOpMode(o) == iABx || getOpMode(o) == iAsBx);
  lua_assert(getCMode(o) == OpArgN);
  lua_assert(a <= MAXARG_A && bc <= MAXARG_Bx);
  return luaK_code(fs, CREATE_ABx(o, a, bc));
}
References CREATE_ABx, getCMode, getOpMode, iABx, iAsBx, lua_assert, luaK_code(), MAXARG_A, MAXARG_Bx, and OpArgN.
Referenced by luaK_codek().
luaK_codek()
int luaK_codek (FuncState * fs, int reg, int k)
Definition at line 346 of file lua-5.3.6/src/lcode.c.
{
  if (k <= MAXARG_Bx)
    return luaK_codeABx(fs, OP_LOADK, reg, k);
  else {
    int p = luaK_codeABx(fs, OP_LOADKX, reg, 0);
    codeextraarg(fs, k);
    return p;
  }
}
References codeextraarg(), luaK_codeABx(), MAXARG_Bx, OP_LOADK, and OP_LOADKX.
Referenced by discharge2reg().
luaK_concat()
void luaK_concat (FuncState * fs, int * l1, int l2)
Definition at line 116 of file lua-5.3.6/src/lcode.c.
{
  if (l2 == NO_JUMP) return;  /* nothing to concatenate? */
  else if (*l1 == NO_JUMP)  /* no original list? */
    *l1 = l2;  /* 'l1' points to 'l2' */
  else {
    int list = *l1;
    int next;
    while ((next = getjump(fs, list)) != NO_JUMP)  /* find last element */
      list = next;
    fixjump(fs, list, l2);  /* last element links to 'l2' */
  }
}
References fixjump(), getjump(), next, and NO_JUMP.
Referenced by exp2reg(), luaK_goiffalse(), luaK_goiftrue(), luaK_jump(), luaK_patchtohere(), and luaK_posfix().
luaK_dischargevars()
void luaK_dischargevars (FuncState * fs, expdesc * e)
Definition at line 556 of file lua-5.3.6/src/lcode.c.
{
  switch (e->k) {
    case VLOCAL: {  /* already in a register */
      e->k = VNONRELOC;  /* becomes a non-relocatable value */
      break;
    }
    case VUPVAL: {  /* move value to some (pending) register */
      e->u.info = luaK_codeABC(fs, OP_GETUPVAL, 0, e->u.info, 0);
      e->k = VRELOCABLE;
      break;
    }
    case VINDEXED: {
      OpCode op;
      freereg(fs, e->u.ind.idx);
      if (e->u.ind.vt == VLOCAL) {  /* is 't' in a register? */
        freereg(fs, e->u.ind.t);
        op = OP_GETTABLE;
      }
      else {
        lua_assert(e->u.ind.vt == VUPVAL);
        op = OP_GETTABUP;  /* 't' is in an upvalue */
      }
      e->u.info = luaK_codeABC(fs, op, 0, e->u.ind.t, e->u.ind.idx);
      e->k = VRELOCABLE;
      break;
    }
    case VVARARG: case VCALL: {
      luaK_setoneret(fs, e);
      break;
    }
    default: break;  /* there is one value available (somewhere) */
  }
}
References freereg(), expdesc::idx, expdesc::ind, expdesc::info, expdesc::k, lua_assert, luaK_codeABC, luaK_setoneret(), OP_GETTABLE, OP_GETTABUP, OP_GETUPVAL, expdesc::t, expdesc::u, VCALL, VINDEXED, VLOCAL, VNONRELOC, VRELOCABLE, expdesc::vt, VUPVAL, and VVARARG.
Referenced by codenot(), discharge2reg(), luaK_exp2anyreg(), luaK_exp2nextreg(), luaK_exp2val(), luaK_goiffalse(), luaK_goiftrue(), and luaK_posfix().
luaK_exp2anyreg()
int luaK_exp2anyreg (FuncState * fs, expdesc * e)
Definition at line 715 of file lua-5.3.6/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  if (e->k == VNONRELOC) {  /* expression already has a register? */
    if (!hasjumps(e))  /* no jumps? */
      return e->u.info;  /* result is already in a register */
    if (e->u.info >= fs->nactvar) {  /* reg. is not a local? */
      exp2reg(fs, e, e->u.info);  /* put final result in it */
      return e->u.info;
    }
  }
  luaK_exp2nextreg(fs, e);  /* otherwise, use next available register */
  return e->u.info;
}
References exp2reg(), hasjumps, expdesc::info, expdesc::k, luaK_dischargevars(), luaK_exp2nextreg(), FuncState::nactvar, expdesc::u, and VNONRELOC.
Referenced by codeunexpval(), luaK_exp2anyregup(), luaK_exp2RK(), luaK_exp2val(), luaK_self(), and luaK_storevar().
luaK_exp2anyregup()
void luaK_exp2anyregup (FuncState * fs, expdesc * e)
Definition at line 734 of file lua-5.3.6/src/lcode.c.
{
  if (e->k != VUPVAL || hasjumps(e))
    luaK_exp2anyreg(fs, e);
}
References hasjumps, expdesc::k, luaK_exp2anyreg(), and VUPVAL.
luaK_exp2nextreg()
void luaK_exp2nextreg (FuncState * fs, expdesc * e)
Definition at line 703 of file lua-5.3.6/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  freeexp(fs, e);
  luaK_reserveregs(fs, 1);
  exp2reg(fs, e, fs->freereg - 1);
}
References exp2reg(), freeexp(), FuncState::freereg, luaK_dischargevars(), and luaK_reserveregs().
Referenced by luaK_exp2anyreg(), luaK_infix(), and luaK_posfix().
luaK_exp2RK()
int luaK_exp2RK (FuncState * fs, expdesc * e)
Definition at line 758 of file lua-5.3.6/src/lcode.c.
{
  luaK_exp2val(fs, e);
  switch (e->k) {  /* move constants to 'k' */
    case VTRUE: e->u.info = boolK(fs, 1); goto vk;
    case VFALSE: e->u.info = boolK(fs, 0); goto vk;
    case VNIL: e->u.info = nilK(fs); goto vk;
    case VKINT: e->u.info = luaK_intK(fs, e->u.ival); goto vk;
    case VKFLT: e->u.info = luaK_numberK(fs, e->u.nval); goto vk;
    case VK:
     vk:
      e->k = VK;
      if (e->u.info <= MAXINDEXRK)  /* constant fits in 'argC'? */
        return RKASK(e->u.info);
      else break;
    default: break;
  }
  /* not a constant in the right range: put it in a register */
  return luaK_exp2anyreg(fs, e);
}
References boolK(), expdesc::info, expdesc::ival, expdesc::k, luaK_exp2anyreg(), luaK_exp2val(), luaK_intK(), luaK_numberK(), MAXINDEXRK, nilK(), expdesc::nval, RKASK, expdesc::u, VFALSE, VK, VKFLT, VKINT, VNIL, and VTRUE.
Referenced by codebinexpval(), codecomp(), luaK_indexed(), luaK_infix(), luaK_self(), and luaK_storevar().
luaK_exp2val()
void luaK_exp2val (FuncState * fs, expdesc * e)
Definition at line 744 of file lua-5.3.6/src/lcode.c.
{
  if (hasjumps(e))
    luaK_exp2anyreg(fs, e);
  else
    luaK_dischargevars(fs, e);
}
References hasjumps, luaK_dischargevars(), and luaK_exp2anyreg().
Referenced by luaK_exp2RK(), and luaK_posfix().
luaK_fixline()
void luaK_fixline (FuncState * fs, int line)
Definition at line 1177 of file lua-5.3.6/src/lcode.c.
{
  fs->f->lineinfo[fs->pc - 1] = line;
}
References FuncState::f, Proto::lineinfo, and FuncState::pc.
Referenced by codebinexpval(), and codeunexpval().
luaK_getlabel()
int luaK_getlabel (FuncState * fs)
Definition at line 168 of file lua-5.3.6/src/lcode.c.
{
  fs->lasttarget = fs->pc;
  return fs->pc;
}
References FuncState::lasttarget, and FuncState::pc.
Referenced by code_loadbool(), exp2reg(), and luaK_patchtohere().
luaK_goiffalse()
void luaK_goiffalse (FuncState * fs, expdesc * e)
Definition at line 884 of file lua-5.3.6/src/lcode.c.
{
  int pc;  /* pc of new jump */
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VJMP: {
      pc = e->u.info;  /* already jump if true */
      break;
    }
    case VNIL: case VFALSE: {
      pc = NO_JUMP;  /* always false; do nothing */
      break;
    }
    default: {
      pc = jumponcond(fs, e, 1);  /* jump if true */
      break;
    }
  }
  luaK_concat(fs, &e->t, pc);  /* insert new jump in 't' list */
  luaK_patchtohere(fs, e->f);  /* false list jumps to here (to go through) */
  e->f = NO_JUMP;
}
References expdesc::f, expdesc::info, jumponcond(), expdesc::k, luaK_concat(), luaK_dischargevars(), luaK_patchtohere(), NO_JUMP, expdesc::t, expdesc::u, VFALSE, VJMP, and VNIL.
Referenced by luaK_infix().
luaK_goiftrue()
void luaK_goiftrue (FuncState * fs, expdesc * e)
Definition at line 857 of file lua-5.3.6/src/lcode.c.
{
  int pc;  /* pc of new jump */
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VJMP: {  /* condition? */
      negatecondition(fs, e);  /* jump when it is false */
      pc = e->u.info;  /* save jump position */
      break;
    }
    case VK: case VKFLT: case VKINT: case VTRUE: {
      pc = NO_JUMP;  /* always true; do nothing */
      break;
    }
    default: {
      pc = jumponcond(fs, e, 0);  /* jump when false */
      break;
    }
  }
  luaK_concat(fs, &e->f, pc);  /* insert new jump in false list */
  luaK_patchtohere(fs, e->t);  /* true list jumps to here (to go through) */
  e->t = NO_JUMP;
}
References expdesc::f, expdesc::info, jumponcond(), expdesc::k, luaK_concat(), luaK_dischargevars(), luaK_patchtohere(), negatecondition(), NO_JUMP, expdesc::t, expdesc::u, VJMP, VK, VKFLT, VKINT, and VTRUE.
Referenced by luaK_infix().
luaK_indexed()
void luaK_indexed (FuncState * fs, expdesc * t, expdesc * k)
Definition at line 946 of file lua-5.3.6/src/lcode.c.
{
  lua_assert(!hasjumps(t) && (vkisinreg(t->k) || t->k == VUPVAL));
  t->u.ind.t = t->u.info;  /* register or upvalue index */
  t->u.ind.idx = luaK_exp2RK(fs, k);  /* R/K index for key */
  t->u.ind.vt = (t->k == VUPVAL) ? VUPVAL : VLOCAL;
  t->k = VINDEXED;
}
References hasjumps, expdesc::idx, expdesc::ind, expdesc::info, expdesc::k, lua_assert, luaK_exp2RK(), expdesc::t, expdesc::u, VINDEXED, vkisinreg, VLOCAL, expdesc::vt, and VUPVAL.
luaK_infix()
void luaK_infix (FuncState * fs, BinOpr op, expdesc * v)
Definition at line 1086 of file lua-5.3.6/src/lcode.c.
{
  switch (op) {
    case OPR_AND: {
      luaK_goiftrue(fs, v);  /* go ahead only if 'v' is true */
      break;
    }
    case OPR_OR: {
      luaK_goiffalse(fs, v);  /* go ahead only if 'v' is false */
      break;
    }
    case OPR_CONCAT: {
      luaK_exp2nextreg(fs, v);  /* operand must be on the 'stack' */
      break;
    }
    case OPR_ADD: case OPR_SUB:
    case OPR_MUL: case OPR_DIV: case OPR_IDIV:
    case OPR_MOD: case OPR_POW:
    case OPR_BAND: case OPR_BOR: case OPR_BXOR:
    case OPR_SHL: case OPR_SHR: {
      if (!tonumeral(v, NULL))
        luaK_exp2RK(fs, v);
      /* else keep numeral, which may be folded with 2nd operand */
      break;
    }
    default: {
      luaK_exp2RK(fs, v);
      break;
    }
  }
}
References luaK_exp2nextreg(), luaK_exp2RK(), luaK_goiffalse(), luaK_goiftrue(), NULL, OPR_ADD, OPR_AND, OPR_BAND, OPR_BOR, OPR_BXOR, OPR_CONCAT, OPR_DIV, OPR_IDIV, OPR_MOD, OPR_MUL, OPR_OR, OPR_POW, OPR_SHL, OPR_SHR, OPR_SUB, and tonumeral().
luaK_intK()
int luaK_intK (FuncState * fs, lua_Integer n)
Definition at line 471 of file lua-5.3.6/src/lcode.c.
{
  TValue k, o;
  setpvalue(&k, cast(void*, cast(size_t, n)));
  setivalue(&o, n);
  return addk(fs, &k, &o);
}
References addk(), cast, setivalue, and setpvalue.
Referenced by discharge2reg(), fornum(), and luaK_exp2RK().
luaK_jump()
int luaK_jump (FuncState * fs)
Definition at line 136 of file lua-5.3.6/src/lcode.c.
{
  int jpc = fs->jpc;  /* save list of jumps to here */
  int j;
  fs->jpc = NO_JUMP;  /* no more jumps to here */
  j = luaK_codeAsBx(fs, OP_JMP, 0, NO_JUMP);
  luaK_concat(fs, &j, jpc);  /* keep them on hold */
  return j;
}
References FuncState::jpc, luaK_codeAsBx, luaK_concat(), NO_JUMP, and OP_JMP.
Referenced by condjump(), and exp2reg().
luaK_nil()
void luaK_nil (FuncState * fs, int from, int n)
Definition at line 64 of file lua-5.3.6/src/lcode.c.
{
  Instruction *previous;
  int l = from + n - 1;  /* last register to set nil */
  if (fs->pc > fs->lasttarget) {  /* no jumps to current position? */
    previous = &fs->f->code[fs->pc-1];
    if (GET_OPCODE(*previous) == OP_LOADNIL) {  /* previous is LOADNIL? */
      int pfrom = GETARG_A(*previous);  /* get previous range */
      int pl = pfrom + GETARG_B(*previous);
      if ((pfrom <= from && from <= pl + 1) ||
          (from <= pfrom && pfrom <= l + 1)) {  /* can connect both? */
        if (pfrom < from) from = pfrom;  /* from = min(from, pfrom) */
        if (pl > l) l = pl;  /* l = max(l, pl) */
        SETARG_A(*previous, from);
        SETARG_B(*previous, l - from);
        return;
      }
    }  /* else go through */
  }
  luaK_codeABC(fs, OP_LOADNIL, from, n - 1, 0);  /* else no optimization */
}
References Proto::code, FuncState::f, GET_OPCODE, GETARG_A, GETARG_B, FuncState::lasttarget, luaK_codeABC, OP_LOADNIL, FuncState::pc, SETARG_A, and SETARG_B.
Referenced by discharge2reg().
luaK_numberK()
static int luaK_numberK (FuncState * fs, lua_Number r) static
Definition at line 481 of file lua-5.3.6/src/lcode.c.
{
  TValue o;
  setfltvalue(&o, r);
  return addk(fs, &o, &o);  /* use number itself as key */
}
References addk(), and setfltvalue.
Referenced by discharge2reg(), and luaK_exp2RK().
luaK_patchclose()
void luaK_patchclose (FuncState * fs, int list, int level)
Definition at line 278 of file lua-5.3.6/src/lcode.c.
{
  level++;  /* argument is +1 to reserve 0 as non-op */
  for (; list != NO_JUMP; list = getjump(fs, list)) {
    lua_assert(GET_OPCODE(fs->f->code[list]) == OP_JMP &&
                (GETARG_A(fs->f->code[list]) == 0 ||
                 GETARG_A(fs->f->code[list]) >= level));
    SETARG_A(fs->f->code[list], level);
  }
}
References Proto::code, FuncState::f, GET_OPCODE, GETARG_A, getjump(), lua_assert, NO_JUMP, OP_JMP, and SETARG_A.
luaK_patchlist()
void luaK_patchlist (FuncState * fs, int list, int target)
Definition at line 263 of file lua-5.3.6/src/lcode.c.
{
  if (target == fs->pc)  /* 'target' is current position? */
    luaK_patchtohere(fs, list);  /* add list to pending jumps */
  else {
    lua_assert(target < fs->pc);
    patchlistaux(fs, list, target, NO_REG, target);
  }
}
References lua_assert, luaK_patchtohere(), NO_REG, patchlistaux(), and FuncState::pc.
luaK_patchtohere()
void luaK_patchtohere (FuncState * fs, int list)
Definition at line 252 of file lua-5.3.6/src/lcode.c.
{
  luaK_getlabel(fs);  /* mark "here" as a jump target */
  luaK_concat(fs, &fs->jpc, list);
}
References FuncState::jpc, luaK_concat(), and luaK_getlabel().
Referenced by exp2reg(), luaK_goiffalse(), luaK_goiftrue(), and luaK_patchlist().
luaK_posfix()
void luaK_posfix (FuncState * fs, BinOpr op, expdesc * e1, expdesc * e2, int line)
Definition at line 1124 of file lua-5.3.6/src/lcode.c.
{
  switch (op) {
    case OPR_AND: {
      lua_assert(e1->t == NO_JUMP);  /* list closed by 'luK_infix' */
      luaK_dischargevars(fs, e2);
      luaK_concat(fs, &e2->f, e1->f);
      *e1 = *e2;
      break;
    }
    case OPR_OR: {
      lua_assert(e1->f == NO_JUMP);  /* list closed by 'luK_infix' */
      luaK_dischargevars(fs, e2);
      luaK_concat(fs, &e2->t, e1->t);
      *e1 = *e2;
      break;
    }
    case OPR_CONCAT: {
      luaK_exp2val(fs, e2);
      if (e2->k == VRELOCABLE &&
          GET_OPCODE(getinstruction(fs, e2)) == OP_CONCAT) {
        lua_assert(e1->u.info == GETARG_B(getinstruction(fs, e2))-1);
        freeexp(fs, e1);
        SETARG_B(getinstruction(fs, e2), e1->u.info);
        e1->k = VRELOCABLE; e1->u.info = e2->u.info;
      }
      else {
        luaK_exp2nextreg(fs, e2);  /* operand must be on the 'stack' */
        codebinexpval(fs, OP_CONCAT, e1, e2, line);
      }
      break;
    }
    case OPR_ADD: case OPR_SUB: case OPR_MUL: case OPR_DIV:
    case OPR_IDIV: case OPR_MOD: case OPR_POW:
    case OPR_BAND: case OPR_BOR: case OPR_BXOR:
    case OPR_SHL: case OPR_SHR: {
      if (!constfolding(fs, op + LUA_OPADD, e1, e2))
        codebinexpval(fs, cast(OpCode, op + OP_ADD), e1, e2, line);
      break;
    }
    case OPR_EQ: case OPR_LT: case OPR_LE:
    case OPR_NE: case OPR_GT: case OPR_GE: {
      codecomp(fs, op, e1, e2);
      break;
    }
    default: lua_assert(0);
  }
}
References cast, codebinexpval(), codecomp(), constfolding(), expdesc::f, freeexp(), GET_OPCODE, GETARG_B, getinstruction, expdesc::info, expdesc::k, lua_assert, LUA_OPADD, luaK_concat(), luaK_dischargevars(), luaK_exp2nextreg(), luaK_exp2val(), NO_JUMP, OP_ADD, OP_CONCAT, OPR_ADD, OPR_AND, OPR_BAND, OPR_BOR, OPR_BXOR, OPR_CONCAT, OPR_DIV, OPR_EQ, OPR_GE, OPR_GT, OPR_IDIV, OPR_LE, OPR_LT, OPR_MOD, OPR_MUL, OPR_NE, OPR_OR, OPR_POW, OPR_SHL, OPR_SHR, OPR_SUB, SETARG_B, expdesc::t, expdesc::u, and VRELOCABLE.
luaK_prefix()
void luaK_prefix (FuncState * fs, UnOpr op, expdesc * e, int line)
Definition at line 1066 of file lua-5.3.6/src/lcode.c.
{
  static const expdesc ef = {VKINT, {0}, NO_JUMP, NO_JUMP};
  switch (op) {
    case OPR_MINUS: case OPR_BNOT:  /* use 'ef' as fake 2nd operand */
      if (constfolding(fs, op + LUA_OPUNM, e, &ef))
        break;
      /* FALLTHROUGH */
    case OPR_LEN:
      codeunexpval(fs, cast(OpCode, op + OP_UNM), e, line);
      break;
    case OPR_NOT: codenot(fs, e); break;
    default: lua_assert(0);
  }
}
References cast, codenot(), codeunexpval(), constfolding(), lua_assert, LUA_OPUNM, NO_JUMP, OP_UNM, OPR_BNOT, OPR_LEN, OPR_MINUS, OPR_NOT, and VKINT.
luaK_reserveregs()
void luaK_reserveregs (FuncState * fs, int n)
Definition at line 375 of file lua-5.3.6/src/lcode.c.
{
  luaK_checkstack(fs, n);
  fs->freereg += n;
}
References FuncState::freereg, and luaK_checkstack().
Referenced by discharge2anyreg(), luaK_exp2nextreg(), luaK_self(), and luaK_setreturns().
luaK_ret()
void luaK_ret (FuncState * fs, int first, int nret)
Definition at line 149 of file lua-5.3.6/src/lcode.c.
{
  luaK_codeABC(fs, OP_RETURN, first, nret+1, 0);
}
References luaK_codeABC, and OP_RETURN.
luaK_self()
void luaK_self (FuncState * fs, expdesc * e, expdesc * key)
Definition at line 809 of file lua-5.3.6/src/lcode.c.
{
  int ereg;
  luaK_exp2anyreg(fs, e);
  ereg = e->u.info;  /* register where 'e' was placed */
  freeexp(fs, e);
  e->u.info = fs->freereg;  /* base register for op_self */
  e->k = VNONRELOC;  /* self expression has a fixed register */
  luaK_reserveregs(fs, 2);  /* function and 'self' produced by op_self */
  luaK_codeABC(fs, OP_SELF, e->u.info, ereg, luaK_exp2RK(fs, key));
  freeexp(fs, key);
}
References freeexp(), FuncState::freereg, expdesc::info, expdesc::k, luaK_codeABC, luaK_exp2anyreg(), luaK_exp2RK(), luaK_reserveregs(), OP_SELF, expdesc::u, and VNONRELOC.
luaK_setlist()
void luaK_setlist (FuncState * fs, int base, int nelems, int tostore)
Definition at line 1189 of file lua-5.3.6/src/lcode.c.
{
  int c =  (nelems - 1)/LFIELDS_PER_FLUSH + 1;
  int b = (tostore == LUA_MULTRET) ? 0 : tostore;
  lua_assert(tostore != 0 && tostore <= LFIELDS_PER_FLUSH);
  if (c <= MAXARG_C)
    luaK_codeABC(fs, OP_SETLIST, base, b, c);
  else if (c <= MAXARG_Ax) {
    luaK_codeABC(fs, OP_SETLIST, base, b, 0);
    codeextraarg(fs, c);
  }
  else
    luaX_syntaxerror(fs->ls, "constructor too long");
  fs->freereg = base + 1;  /* free registers with list values */
}
References codeextraarg(), FuncState::freereg, LFIELDS_PER_FLUSH, FuncState::ls, lua_assert, LUA_MULTRET, luaK_codeABC, luaX_syntaxerror(), MAXARG_Ax, MAXARG_C, and OP_SETLIST.
luaK_setoneret()
void luaK_setoneret (FuncState * fs, expdesc * e)
Definition at line 539 of file lua-5.3.6/src/lcode.c.
{
  if (e->k == VCALL) {  /* expression is an open function call? */
    /* already returns 1 value */
    lua_assert(GETARG_C(getinstruction(fs, e)) == 2);
    e->k = VNONRELOC;  /* result has fixed position */
    e->u.info = GETARG_A(getinstruction(fs, e));
  }
  else if (e->k == VVARARG) {
    SETARG_B(getinstruction(fs, e), 2);
    e->k = VRELOCABLE;  /* can relocate its simple result */
  }
}
References GETARG_A, GETARG_C, getinstruction, expdesc::info, expdesc::k, lua_assert, SETARG_B, expdesc::u, VCALL, VNONRELOC, VRELOCABLE, and VVARARG.
Referenced by luaK_dischargevars().
luaK_setreturns()
void luaK_setreturns (FuncState * fs, expdesc * e, int nresults)
Definition at line 515 of file lua-5.3.6/src/lcode.c.
{
  if (e->k == VCALL) {  /* expression is an open function call? */
    SETARG_C(getinstruction(fs, e), nresults + 1);
  }
  else if (e->k == VVARARG) {
    Instruction *pc = &getinstruction(fs, e);
    SETARG_B(*pc, nresults + 1);
    SETARG_A(*pc, fs->freereg);
    luaK_reserveregs(fs, 1);
  }
  else lua_assert(nresults == LUA_MULTRET);
}
References FuncState::freereg, getinstruction, expdesc::k, lua_assert, LUA_MULTRET, luaK_reserveregs(), SETARG_A, SETARG_B, SETARG_C, VCALL, and VVARARG.
luaK_storevar()
void luaK_storevar (FuncState * fs, expdesc * var, expdesc * ex)
Definition at line 782 of file lua-5.3.6/src/lcode.c.
{
  switch (var->k) {
    case VLOCAL: {
      freeexp(fs, ex);
      exp2reg(fs, ex, var->u.info);  /* compute 'ex' into proper place */
      return;
    }
    case VUPVAL: {
      int e = luaK_exp2anyreg(fs, ex);
      luaK_codeABC(fs, OP_SETUPVAL, e, var->u.info, 0);
      break;
    }
    case VINDEXED: {
      OpCode op = (var->u.ind.vt == VLOCAL) ? OP_SETTABLE : OP_SETTABUP;
      int e = luaK_exp2RK(fs, ex);
      luaK_codeABC(fs, op, var->u.ind.t, var->u.ind.idx, e);
      break;
    }
    default: lua_assert(0);  /* invalid var kind to store */
  }
  freeexp(fs, ex);
}
References exp2reg(), freeexp(), expdesc::idx, expdesc::ind, expdesc::info, expdesc::k, lua_assert, luaK_codeABC, luaK_exp2anyreg(), luaK_exp2RK(), OP_SETTABLE, OP_SETTABUP, OP_SETUPVAL, expdesc::t, expdesc::u, VINDEXED, VLOCAL, expdesc::vt, and VUPVAL.
luaK_stringK()
int luaK_stringK (FuncState * fs, TString * s)
Definition at line 458 of file lua-5.3.6/src/lcode.c.
{
  TValue o;
  setsvalue(fs->ls->L, &o, s);
  return addk(fs, &o, &o);  /* use string itself as key */
}
References addk(), LexState::L, FuncState::ls, s, and setsvalue.
need_value()
static int need_value (FuncState * fs, int list) static
Definition at line 659 of file lua-5.3.6/src/lcode.c.
{
  for (; list != NO_JUMP; list = getjump(fs, list)) {
    Instruction i = *getjumpcontrol(fs, list);
    if (GET_OPCODE(i) != OP_TESTSET) return 1;
  }
  return 0;  /* not found */
}
References GET_OPCODE, getjump(), getjumpcontrol(), NO_JUMP, and OP_TESTSET.
Referenced by exp2reg().
negatecondition()
static void negatecondition (FuncState * fs, expdesc * e) static
Definition at line 825 of file lua-5.3.6/src/lcode.c.
{
  Instruction *pc = getjumpcontrol(fs, e->u.info);
  lua_assert(testTMode(GET_OPCODE(*pc)) && GET_OPCODE(*pc) != OP_TESTSET &&
                                           GET_OPCODE(*pc) != OP_TEST);
  SETARG_A(*pc, !(GETARG_A(*pc)));
}
References GET_OPCODE, GETARG_A, getjumpcontrol(), expdesc::info, lua_assert, OP_TEST, OP_TESTSET, SETARG_A, testTMode, and expdesc::u.
Referenced by codenot(), and luaK_goiftrue().
nilK()
static int nilK (FuncState * fs) static
Definition at line 501 of file lua-5.3.6/src/lcode.c.
{
  TValue k, v;
  setnilvalue(&v);
  /* cannot use nil as key; instead use table itself to represent nil */
  sethvalue(fs->ls->L, &k, fs->ls->h);
  return addk(fs, &k, &v);
}
References addk(), LexState::h, LexState::L, FuncState::ls, sethvalue, and setnilvalue.
Referenced by luaK_exp2RK().
patchlistaux()
static void patchlistaux (FuncState * fs, int list, int vtarget, int reg, int dtarget) static
Definition at line 224 of file lua-5.3.6/src/lcode.c.
{
  while (list != NO_JUMP) {
    int next = getjump(fs, list);
    if (patchtestreg(fs, list, reg))
      fixjump(fs, list, vtarget);
    else
      fixjump(fs, list, dtarget);  /* jump to default target */
    list = next;
  }
}
References fixjump(), getjump(), next, NO_JUMP, and patchtestreg().
Referenced by dischargejpc(), exp2reg(), and luaK_patchlist().
patchtestreg()
static int patchtestreg (FuncState * fs, int node, int reg) static
Definition at line 195 of file lua-5.3.6/src/lcode.c.
{
  Instruction *i = getjumpcontrol(fs, node);
  if (GET_OPCODE(*i) != OP_TESTSET)
    return 0;  /* cannot patch other instructions */
  if (reg != NO_REG && reg != GETARG_B(*i))
    SETARG_A(*i, reg);
  else {
     /* no register to put value or register already has the value;
        change instruction to simple test */
    *i = CREATE_ABC(OP_TEST, GETARG_B(*i), 0, GETARG_C(*i));
  }
  return 1;
}
References CREATE_ABC, GET_OPCODE, GETARG_B, GETARG_C, getjumpcontrol(), NO_REG, OP_TEST, OP_TESTSET, and SETARG_A.
Referenced by patchlistaux(), and removevalues().
removevalues()
static void removevalues (FuncState * fs, int list) static
Definition at line 213 of file lua-5.3.6/src/lcode.c.
{
  for (; list != NO_JUMP; list = getjump(fs, list))
      patchtestreg(fs, list, NO_REG);
}
References getjump(), NO_JUMP, NO_REG, and patchtestreg().
Referenced by codenot().
tonumeral()
static int tonumeral (const expdesc * e, TValue * v) static
Definition at line 43 of file lua-5.3.6/src/lcode.c.
{
  if (hasjumps(e))
    return 0;  /* not a numeral */
  switch (e->k) {
    case VKINT:
      if (v) setivalue(v, e->u.ival);
      return 1;
    case VKFLT:
      if (v) setfltvalue(v, e->u.nval);
      return 1;
    default: return 0;
  }
}
References hasjumps, expdesc::ival, expdesc::k, expdesc::nval, setfltvalue, setivalue, expdesc::u, VKFLT, and VKINT.
Referenced by constfolding(), and luaK_infix().
validop()
static int validop (int op, TValue * v1, TValue * v2) static
Definition at line 960 of file lua-5.3.6/src/lcode.c.
{
  switch (op) {
    case LUA_OPBAND: case LUA_OPBOR: case LUA_OPBXOR:
    case LUA_OPSHL: case LUA_OPSHR: case LUA_OPBNOT: {  /* conversion errors */
      lua_Integer i;
      return (tointeger(v1, &i) && tointeger(v2, &i));
    }
    case LUA_OPDIV: case LUA_OPIDIV: case LUA_OPMOD:  /* division by 0 */
      return (nvalue(v2) != 0);
    default: return 1;  /* everything else is valid */
  }
}
References LUA_OPBAND, LUA_OPBNOT, LUA_OPBOR, LUA_OPBXOR, LUA_OPDIV, LUA_OPIDIV, LUA_OPMOD, LUA_OPSHL, LUA_OPSHR, nvalue, and tointeger.
Referenced by constfolding().