Github User Fetcher: loadlib.c File Reference
loadlib.c File Reference
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define loadlib_c
#define LUA_LIB
#define LUA_POF "luaopen_"
#define LUA_OFSEP "_"
#define LIBPREFIX "LOADLIB: "
#define POF LUA_POF
#define LIB_FAIL "open"
#define ERRLIB 1
#define ERRFUNC 2
#define setprogdir(L) ((void)0)
#define LIB_FAIL "absent"
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
#define sentinel ((void *)&sentinel_)
#define AUXMARK "\1"
Functions
static void ll_unloadlib (void *lib)
static void * ll_load (lua_State *L, const char *path)
static lua_CFunction ll_sym (lua_State *L, void *lib, const char *sym)
static void ** ll_register (lua_State *L, const char *path)
static int gctm (lua_State *L)
static int ll_loadfunc (lua_State *L, const char *path, const char *sym)
static int ll_loadlib (lua_State *L)
static int readable (const char *filename)
static const char * pushnexttemplate (lua_State *L, const char *path)
static const char * findfile (lua_State *L, const char *name, const char *pname)
static void loaderror (lua_State *L, const char *filename)
static int loader_Lua (lua_State *L)
static const char * mkfuncname (lua_State *L, const char *modname)
static int loader_C (lua_State *L)
static int loader_Croot (lua_State *L)
static int loader_preload (lua_State *L)
static int ll_require (lua_State *L)
static void setfenv (lua_State *L)
static void dooptions (lua_State *L, int n)
static void modinit (lua_State *L, const char *modname)
static int ll_module (lua_State *L)
static int ll_seeall (lua_State *L)
static void setpath (lua_State *L, const char *fieldname, const char *envname, const char *def)
LUALIB_API int luaopen_package (lua_State *L)
Variables
static const int sentinel_ = 0
static const luaL_Reg pk_funcs []
static const luaL_Reg ll_funcs []
static const lua_CFunction loaders []
Macro Definition Documentation
AUXMARK
#define AUXMARK "\1"
Definition at line 590 of file lua-5.1.5/src/loadlib.c.
Referenced by setpath().
DLMSG
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
Definition at line 236 of file lua-5.1.5/src/loadlib.c.
Referenced by ll_load(), and ll_sym().
ERRFUNC
#define ERRFUNC 2
Definition at line 40 of file lua-5.1.5/src/loadlib.c.
Referenced by ll_loadfunc(), and loader_Croot().
ERRLIB
#define ERRLIB 1
Definition at line 39 of file lua-5.1.5/src/loadlib.c.
Referenced by ll_loadfunc(), and ll_loadlib().
LIB_FAIL [1/2]
#define LIB_FAIL "open"
Definition at line 35 of file lua-5.1.5/src/loadlib.c.
Referenced by ll_loadlib().
LIB_FAIL [2/2]
#define LIB_FAIL "absent"
Definition at line 35 of file lua-5.1.5/src/loadlib.c.
LIBPREFIX
#define LIBPREFIX "LOADLIB: "
Definition at line 32 of file lua-5.1.5/src/loadlib.c.
Referenced by ll_register().
loadlib_c
#define loadlib_c
Definition at line 16 of file lua-5.1.5/src/loadlib.c.
LUA_LIB
#define LUA_LIB
Definition at line 17 of file lua-5.1.5/src/loadlib.c.
LUA_OFSEP
#define LUA_OFSEP "_"
Definition at line 29 of file lua-5.1.5/src/loadlib.c.
Referenced by mkfuncname().
LUA_POF
#define LUA_POF "luaopen_"
Definition at line 26 of file lua-5.1.5/src/loadlib.c.
POF
#define POF LUA_POF
Definition at line 34 of file lua-5.1.5/src/loadlib.c.
Referenced by mkfuncname().
sentinel
#define sentinel ((void *)&sentinel_)
Definition at line 448 of file lua-5.1.5/src/loadlib.c.
Referenced by ll_require().
setprogdir
#define setprogdir (L) ((void)0)
Definition at line 42 of file lua-5.1.5/src/loadlib.c.
Referenced by setpath().
Function Documentation
dooptions()
static void dooptions (lua_State * L, int n) static
Definition at line 519 of file lua-5.1.5/src/loadlib.c.
{
  int i;
  for (i = 2; i <= n; i++) {
    lua_pushvalue(L, i);  /* get option (a function) */
    lua_pushvalue(L, -2);  /* module */
    lua_call(L, 1, 0);
  }
}
References lua_call, and lua_pushvalue().
Referenced by ll_module().
findfile()
static const char * findfile (lua_State * L, const char * name, const char * pname) static
Definition at line 351 of file lua-5.1.5/src/loadlib.c.
{
  const char *path;
  name = luaL_gsub(L, name, ".", LUA_DIRSEP);
  lua_getfield(L, LUA_ENVIRONINDEX, pname);
  path = lua_tostring(L, -1);
  if (path == NULL)
    luaL_error(L, LUA_QL("package.%s") " must be a string", pname);
  lua_pushliteral(L, "");  /* error accumulator */
  while ((path = pushnexttemplate(L, path)) != NULL) {
    const char *filename;
    filename = luaL_gsub(L, lua_tostring(L, -1), LUA_PATH_MARK, name);
    lua_remove(L, -2);  /* remove path template */
    if (readable(filename))  /* does file exist and is readable? */
      return filename;  /* return that file name */
    lua_pushfstring(L, "\n\tno file " LUA_QS, filename);
    lua_remove(L, -2);  /* remove file name */
    lua_concat(L, 2);  /* add entry to possible error message */
  }
  return NULL;  /* not found */
}
References lua_concat(), LUA_DIRSEP, LUA_ENVIRONINDEX, lua_getfield(), LUA_PATH_MARK, lua_pushfstring(), lua_pushliteral, LUA_QL, LUA_QS, lua_remove, lua_tostring, luaL_error(), luaL_gsub(), name, NULL, pushnexttemplate(), and readable().
Referenced by loader_C(), loader_Croot(), and loader_Lua().
gctm()
static int gctm (lua_State * L) static
Definition at line 286 of file lua-5.1.5/src/loadlib.c.
{
  void **lib = (void **)luaL_checkudata(L, 1, "_LOADLIB");
  if (*lib) ll_unloadlib(*lib);
  *lib = NULL;  /* mark library as closed */
  return 0;
}
References ll_unloadlib(), luaL_checkudata(), and NULL.
Referenced by luaopen_package().
ll_load()
static void * ll_load (lua_State * L, const char * path) static
Definition at line 244 of file lua-5.1.5/src/loadlib.c.
{
  (void)path;  /* to avoid warnings */
  lua_pushliteral(L, DLMSG);
  return NULL;
}
References DLMSG, lua_pushliteral, and NULL.
Referenced by ll_loadfunc().
ll_loadfunc()
static int ll_loadfunc (lua_State * L, const char * path, const char * sym) static
Definition at line 294 of file lua-5.1.5/src/loadlib.c.
{
  void **reg = ll_register(L, path);
  if (*reg == NULL) *reg = ll_load(L, path);
  if (*reg == NULL)
    return ERRLIB;  /* unable to load library */
  else {
    lua_CFunction f = ll_sym(L, *reg, sym);
    if (f == NULL)
      return ERRFUNC;  /* unable to find function */
    lua_pushcfunction(L, f);
    return 0;  /* return function */
  }
}
References ERRFUNC, ERRLIB, ll_load(), ll_register(), ll_sym(), lua_pushcfunction, and NULL.
Referenced by ll_loadlib(), loader_C(), and loader_Croot().
ll_loadlib()
static int ll_loadlib (lua_State * L) static
Definition at line 309 of file lua-5.1.5/src/loadlib.c.
{
  const char *path = luaL_checkstring(L, 1);
  const char *init = luaL_checkstring(L, 2);
  int stat = ll_loadfunc(L, path, init);
  if (stat == 0)  /* no errors? */
    return 1;  /* return the loaded function */
  else {  /* error; error message is on stack top */
    lua_pushnil(L);
    lua_insert(L, -2);
    lua_pushstring(L, (stat == ERRLIB) ?  LIB_FAIL : "init");
    return 3;  /* return nil, error message, and where */
  }
}
References ERRLIB, LIB_FAIL, ll_loadfunc(), lua_insert, lua_pushnil(), lua_pushstring(), and luaL_checkstring.
ll_module()
static int ll_module (lua_State * L) static
Definition at line 544 of file lua-5.1.5/src/loadlib.c.
{
  const char *modname = luaL_checkstring(L, 1);
  int loaded = lua_gettop(L) + 1;  /* index of _LOADED table */
  lua_getfield(L, LUA_REGISTRYINDEX, "_LOADED");
  lua_getfield(L, loaded, modname);  /* get _LOADED[modname] */
  if (!lua_istable(L, -1)) {  /* not found? */
    lua_pop(L, 1);  /* remove previous result */
    /* try global variable (and create one if it does not exist) */
    if (luaL_findtable(L, LUA_GLOBALSINDEX, modname, 1) != NULL)
      return luaL_error(L, "name conflict for module " LUA_QS, modname);
    lua_pushvalue(L, -1);
    lua_setfield(L, loaded, modname);  /* _LOADED[modname] = new table */
  }
  /* check whether table already has a _NAME field */
  lua_getfield(L, -1, "_NAME");
  if (!lua_isnil(L, -1))  /* is table an initialized module? */
    lua_pop(L, 1);
  else {  /* no; initialize it */
    lua_pop(L, 1);
    modinit(L, modname);
  }
  lua_pushvalue(L, -1);
  setfenv(L);
  dooptions(L, loaded - 1);
  return 0;
}
References dooptions(), lua_getfield(), lua_gettop(), LUA_GLOBALSINDEX, lua_isnil, lua_istable, lua_pop, lua_pushvalue(), LUA_QS, LUA_REGISTRYINDEX, lua_setfield(), luaL_checkstring, luaL_error(), luaL_findtable(), modinit(), NULL, and setfenv().
ll_register()
static void ** ll_register (lua_State * L, const char * path) static
Definition at line 262 of file lua-5.1.5/src/loadlib.c.
{
  void **plib;
  lua_pushfstring(L, "%s%s", LIBPREFIX, path);
  lua_gettable(L, LUA_REGISTRYINDEX);  /* check library in registry? */
  if (!lua_isnil(L, -1))  /* is there an entry? */
    plib = (void **)lua_touserdata(L, -1);
  else {  /* no entry yet; create one */
    lua_pop(L, 1);
    plib = (void **)lua_newuserdata(L, sizeof(const void *));
    *plib = NULL;
    luaL_getmetatable(L, "_LOADLIB");
    lua_setmetatable(L, -2);
    lua_pushfstring(L, "%s%s", LIBPREFIX, path);
    lua_pushvalue(L, -2);
    lua_settable(L, LUA_REGISTRYINDEX);
  }
  return plib;
}
References LIBPREFIX, lua_gettable(), lua_isnil, lua_newuserdata, lua_pop, lua_pushfstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setmetatable(), lua_settable(), lua_touserdata(), luaL_getmetatable, and NULL.
Referenced by ll_loadfunc().
ll_require()
static int ll_require (lua_State * L) static
Definition at line 451 of file lua-5.1.5/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  int i;
  lua_settop(L, 1);  /* _LOADED table will be at index 2 */
  lua_getfield(L, LUA_REGISTRYINDEX, "_LOADED");
  lua_getfield(L, 2, name);
  if (lua_toboolean(L, -1)) {  /* is it there? */
    if (lua_touserdata(L, -1) == sentinel)  /* check loops */
      luaL_error(L, "loop or previous error loading module " LUA_QS, name);
    return 1;  /* package is already loaded */
  }
  /* else must load it; iterate over available loaders */
  lua_getfield(L, LUA_ENVIRONINDEX, "loaders");
  if (!lua_istable(L, -1))
    luaL_error(L, LUA_QL("package.loaders") " must be a table");
  lua_pushliteral(L, "");  /* error message accumulator */
  for (i=1; ; i++) {
    lua_rawgeti(L, -2, i);  /* get a loader */
    if (lua_isnil(L, -1))
      luaL_error(L, "module " LUA_QS " not found:%s",
                    name, lua_tostring(L, -2));
    lua_pushstring(L, name);
    lua_call(L, 1, 1);  /* call it */
    if (lua_isfunction(L, -1))  /* did it find module? */
      break;  /* module loaded successfully */
    else if (lua_isstring(L, -1))  /* loader returned error message? */
      lua_concat(L, 2);  /* accumulate it */
    else
      lua_pop(L, 1);
  }
  lua_pushlightuserdata(L, sentinel);
  lua_setfield(L, 2, name);  /* _LOADED[name] = sentinel */
  lua_pushstring(L, name);  /* pass name as argument to module */
  lua_call(L, 1, 1);  /* run loaded module */
  if (!lua_isnil(L, -1))  /* non-nil return? */
    lua_setfield(L, 2, name);  /* _LOADED[name] = returned value */
  lua_getfield(L, 2, name);
  if (lua_touserdata(L, -1) == sentinel) {   /* module did not set a value? */
    lua_pushboolean(L, 1);  /* use true as result */
    lua_pushvalue(L, -1);  /* extra copy to be returned */
    lua_setfield(L, 2, name);  /* _LOADED[name] = true */
  }
  return 1;
}
References lua_call, lua_concat(), LUA_ENVIRONINDEX, lua_getfield(), lua_isfunction, lua_isnil, lua_isstring(), lua_istable, lua_pop, lua_pushboolean(), lua_pushlightuserdata(), lua_pushliteral, lua_pushstring(), lua_pushvalue(), LUA_QL, LUA_QS, lua_rawgeti(), LUA_REGISTRYINDEX, lua_setfield(), lua_settop(), lua_toboolean(), lua_tostring, lua_touserdata(), luaL_checkstring, luaL_error(), name, and sentinel.
ll_seeall()
static int ll_seeall (lua_State * L) static
Definition at line 572 of file lua-5.1.5/src/loadlib.c.
{
  luaL_checktype(L, 1, LUA_TTABLE);
  if (!lua_getmetatable(L, 1)) {
    lua_createtable(L, 0, 1); /* create new metatable */
    lua_pushvalue(L, -1);
    lua_setmetatable(L, 1);
  }
  lua_pushvalue(L, LUA_GLOBALSINDEX);
  lua_setfield(L, -2, "__index");  /* mt.__index = _G */
  return 0;
}
References lua_createtable(), lua_getmetatable(), LUA_GLOBALSINDEX, lua_pushvalue(), lua_setfield(), lua_setmetatable(), LUA_TTABLE, and luaL_checktype().
ll_sym()
static lua_CFunction ll_sym (lua_State * L, void * lib, const char * sym) static
Definition at line 251 of file lua-5.1.5/src/loadlib.c.
{
  (void)lib; (void)sym;  /* to avoid warnings */
  lua_pushliteral(L, DLMSG);
  return NULL;
}
References DLMSG, lua_pushliteral, and NULL.
Referenced by ll_loadfunc().
ll_unloadlib()
static void ll_unloadlib (void * lib) static
Definition at line 239 of file lua-5.1.5/src/loadlib.c.
{
  (void)lib;  /* to avoid warnings */
}
Referenced by gctm().
loader_C()
static int loader_C (lua_State * L) static
Definition at line 402 of file lua-5.1.5/src/loadlib.c.
{
  const char *funcname;
  const char *name = luaL_checkstring(L, 1);
  const char *filename = findfile(L, name, "cpath");
  if (filename == NULL) return 1;  /* library not found in this path */
  funcname = mkfuncname(L, name);
  if (ll_loadfunc(L, filename, funcname) != 0)
    loaderror(L, filename);
  return 1;  /* library loaded successfully */
}
References findfile(), funcname(), ll_loadfunc(), loaderror(), luaL_checkstring, mkfuncname(), name, and NULL.
loader_Croot()
static int loader_Croot (lua_State * L) static
Definition at line 414 of file lua-5.1.5/src/loadlib.c.
{
  const char *funcname;
  const char *filename;
  const char *name = luaL_checkstring(L, 1);
  const char *p = strchr(name, '.');
  int stat;
  if (p == NULL) return 0;  /* is root */
  lua_pushlstring(L, name, p - name);
  filename = findfile(L, lua_tostring(L, -1), "cpath");
  if (filename == NULL) return 1;  /* root not found */
  funcname = mkfuncname(L, name);
  if ((stat = ll_loadfunc(L, filename, funcname)) != 0) {
    if (stat != ERRFUNC) loaderror(L, filename);  /* real error */
    lua_pushfstring(L, "\n\tno module " LUA_QS " in file " LUA_QS,
                       name, filename);
    return 1;  /* function not found */
  }
  return 1;
}
References ERRFUNC, findfile(), funcname(), ll_loadfunc(), loaderror(), lua_pushfstring(), lua_pushlstring(), LUA_QS, lua_tostring, luaL_checkstring, mkfuncname(), name, and NULL.
loader_Lua()
static int loader_Lua (lua_State * L) static
Definition at line 380 of file lua-5.1.5/src/loadlib.c.
{
  const char *filename;
  const char *name = luaL_checkstring(L, 1);
  filename = findfile(L, name, "path");
  if (filename == NULL) return 1;  /* library not found in this path */
  if (luaL_loadfile(L, filename) != 0)
    loaderror(L, filename);
  return 1;  /* library loaded successfully */
}
References findfile(), loaderror(), luaL_checkstring, luaL_loadfile, name, and NULL.
loader_preload()
static int loader_preload (lua_State * L) static
Definition at line 435 of file lua-5.1.5/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  lua_getfield(L, LUA_ENVIRONINDEX, "preload");
  if (!lua_istable(L, -1))
    luaL_error(L, LUA_QL("package.preload") " must be a table");
  lua_getfield(L, -1, name);
  if (lua_isnil(L, -1))  /* not found? */
    lua_pushfstring(L, "\n\tno field package.preload['%s']", name);
  return 1;
}
References LUA_ENVIRONINDEX, lua_getfield(), lua_isnil, lua_istable, lua_pushfstring(), LUA_QL, luaL_checkstring, luaL_error(), and name.
loaderror()
static void loaderror (lua_State * L, const char * filename) static
Definition at line 374 of file lua-5.1.5/src/loadlib.c.
{
  luaL_error(L, "error loading module " LUA_QS " from file " LUA_QS ":\n\t%s",
                lua_tostring(L, 1), filename, lua_tostring(L, -1));
}
References LUA_QS, lua_tostring, and luaL_error().
Referenced by loader_C(), loader_Croot(), and loader_Lua().
luaopen_package()
LUALIB_API int luaopen_package (lua_State * L)
Definition at line 627 of file lua-5.1.5/src/loadlib.c.
{
  int i;
  /* create new type _LOADLIB */
  luaL_newmetatable(L, "_LOADLIB");
  lua_pushcfunction(L, gctm);
  lua_setfield(L, -2, "__gc");
  /* create `package' table */
  luaL_register(L, LUA_LOADLIBNAME, pk_funcs);
#if defined(LUA_COMPAT_LOADLIB)
  lua_getfield(L, -1, "loadlib");
  lua_setfield(L, LUA_GLOBALSINDEX, "loadlib");
#endif
  lua_pushvalue(L, -1);
  lua_replace(L, LUA_ENVIRONINDEX);
  /* create `loaders' table */
  lua_createtable(L, sizeof(loaders)/sizeof(loaders[0]) - 1, 0);
  /* fill it with pre-defined loaders */
  for (i=0; loaders[i] != NULL; i++) {
    lua_pushcfunction(L, loaders[i]);
    lua_rawseti(L, -2, i+1);
  }
  lua_setfield(L, -2, "loaders");  /* put it in field `loaders' */
  setpath(L, "path", LUA_PATH, LUA_PATH_DEFAULT);  /* set field `path' */
  setpath(L, "cpath", LUA_CPATH, LUA_CPATH_DEFAULT); /* set field `cpath' */
  /* store config information */
  lua_pushliteral(L, LUA_DIRSEP "\n" LUA_PATHSEP "\n" LUA_PATH_MARK "\n"
                     LUA_EXECDIR "\n" LUA_IGMARK);
  lua_setfield(L, -2, "config");
  /* set field `loaded' */
  luaL_findtable(L, LUA_REGISTRYINDEX, "_LOADED", 2);
  lua_setfield(L, -2, "loaded");
  /* set field `preload' */
  lua_newtable(L);
  lua_setfield(L, -2, "preload");
  lua_pushvalue(L, LUA_GLOBALSINDEX);
  luaL_register(L, NULL, ll_funcs);  /* open lib into global table */
  lua_pop(L, 1);
  return 1;  /* return 'package' table */
}
References gctm(), ll_funcs, loaders, LUA_CPATH, LUA_CPATH_DEFAULT, lua_createtable(), LUA_DIRSEP, LUA_ENVIRONINDEX, LUA_EXECDIR, lua_getfield(), LUA_GLOBALSINDEX, LUA_IGMARK, LUA_LOADLIBNAME, lua_newtable, LUA_PATH, LUA_PATH_DEFAULT, LUA_PATH_MARK, LUA_PATHSEP, lua_pop, lua_pushcfunction, lua_pushliteral, lua_pushvalue(), lua_rawseti(), LUA_REGISTRYINDEX, lua_replace, lua_setfield(), luaL_findtable(), luaL_newmetatable(), luaL_register(), NULL, pk_funcs, and setpath().
mkfuncname()
static const char * mkfuncname (lua_State * L, const char * modname) static
Definition at line 391 of file lua-5.1.5/src/loadlib.c.
{
  const char *funcname;
  const char *mark = strchr(modname, *LUA_IGMARK);
  if (mark) modname = mark + 1;
  funcname = luaL_gsub(L, modname, ".", LUA_OFSEP);
  funcname = lua_pushfstring(L, POF"%s", funcname);
  lua_remove(L, -2);  /* remove 'gsub' result */
  return funcname;
}
References funcname(), LUA_IGMARK, LUA_OFSEP, lua_pushfstring(), lua_remove, luaL_gsub(), and POF.
Referenced by loader_C(), and loader_Croot().
modinit()
static void modinit (lua_State * L, const char * modname) static
Definition at line 529 of file lua-5.1.5/src/loadlib.c.
{
  const char *dot;
  lua_pushvalue(L, -1);
  lua_setfield(L, -2, "_M");  /* module._M = module */
  lua_pushstring(L, modname);
  lua_setfield(L, -2, "_NAME");
  dot = strrchr(modname, '.');  /* look for last dot in module name */
  if (dot == NULL) dot = modname;
  else dot++;
  /* set _PACKAGE as package name (full module name minus last part) */
  lua_pushlstring(L, modname, dot - modname);
  lua_setfield(L, -2, "_PACKAGE");
}
References lua_pushlstring(), lua_pushstring(), lua_pushvalue(), lua_setfield(), and NULL.
Referenced by ll_module().
pushnexttemplate()
static const char * pushnexttemplate (lua_State * L, const char * path) static
Definition at line 340 of file lua-5.1.5/src/loadlib.c.
{
  const char *l;
  while (*path == *LUA_PATHSEP) path++;  /* skip separators */
  if (*path == '\0') return NULL;  /* no more templates */
  l = strchr(path, *LUA_PATHSEP);  /* find next separator */
  if (l == NULL) l = path + strlen(path);
  lua_pushlstring(L, path, l - path);  /* template */
  return l;
}
References LUA_PATHSEP, lua_pushlstring(), and NULL.
Referenced by findfile().
readable()
static int readable (const char * filename) static
Definition at line 332 of file lua-5.1.5/src/loadlib.c.
{
  FILE *f = fopen(filename, "r");  /* try to open file */
  if (f == NULL) return 0;  /* open failed */
  fclose(f);
  return 1;
}
References NULL.
Referenced by findfile().
setfenv()
static void setfenv (lua_State * L) static
Definition at line 507 of file lua-5.1.5/src/loadlib.c.
{
  lua_Debug ar;
  if (lua_getstack(L, 1, &ar) == 0 ||
      lua_getinfo(L, "f", &ar) == 0 ||  /* get calling function */
      lua_iscfunction(L, -1))
    luaL_error(L, LUA_QL("module") " not called from a Lua function");
  lua_pushvalue(L, -2);
  lua_setfenv(L, -2);
  lua_pop(L, 1);
}
References lua_getinfo(), lua_getstack(), lua_iscfunction(), lua_pop, lua_pushvalue(), LUA_QL, lua_setfenv(), and luaL_error().
Referenced by ll_module().
setpath()
static void setpath (lua_State * L, const char * fieldname, const char * envname, const char * def) static
Definition at line 592 of file lua-5.1.5/src/loadlib.c.
{
  const char *path = getenv(envname);
  if (path == NULL)  /* no environment variable? */
    lua_pushstring(L, def);  /* use default */
  else {
    /* replace ";;" by ";AUXMARK;" and then AUXMARK by default path */
    path = luaL_gsub(L, path, LUA_PATHSEP LUA_PATHSEP,
                              LUA_PATHSEP AUXMARK LUA_PATHSEP);
    luaL_gsub(L, path, AUXMARK, def);
    lua_remove(L, -2);
  }
  setprogdir(L);
  lua_setfield(L, -2, fieldname);
}
References AUXMARK, LUA_PATHSEP, lua_pushstring(), lua_remove, lua_setfield(), luaL_gsub(), NULL, and setprogdir.
Referenced by luaopen_package().
Variable Documentation
ll_funcs
const luaL_Reg ll_funcs[] static
Initial value:
= {
  {"module", ll_module},
  {"require", ll_require},
  {NULL, NULL}
}
Definition at line 616 of file lua-5.1.5/src/loadlib.c.
{
  {"module", ll_module},
  {"require", ll_require},
  {NULL, NULL}
};
Referenced by luaopen_package().
loaders
const lua_CFunction loaders[] static
Initial value:
=
  {loader_preload, loader_Lua, loader_C, loader_Croot, NULL}
Definition at line 623 of file lua-5.1.5/src/loadlib.c.
  {loader_preload, loader_Lua, loader_C, loader_Croot, NULL};
Referenced by luaopen_package().
pk_funcs
const luaL_Reg pk_funcs[] static
Initial value:
= {
  {"loadlib", ll_loadlib},
  {"seeall", ll_seeall},
  {NULL, NULL}
}
Definition at line 609 of file lua-5.1.5/src/loadlib.c.
{
  {"loadlib", ll_loadlib},
  {"seeall", ll_seeall},
  {NULL, NULL}
};
Referenced by luaopen_package().
sentinel_
const int sentinel_ = 0 static
Definition at line 447 of file lua-5.1.5/src/loadlib.c.