Github User Fetcher: ltm.h File Reference
ltm.h File Reference
#include "lobject.h"
Macros
#define maskflags (~(~0u << (TM_EQ + 1)))
#define notm(tm) ttisnil(tm)
#define gfasttm(g, et, e)
#define fasttm(l, et, e) gfasttm(G(l), et, e)
#define ttypename(x) luaT_typenames_[(x) + 1]
Enumerations
enum TMS {
TM_INDEX , TM_NEWINDEX , TM_GC , TM_MODE ,
TM_LEN , TM_EQ , TM_ADD , TM_SUB ,
TM_MUL , TM_MOD , TM_POW , TM_DIV ,
TM_IDIV , TM_BAND , TM_BOR , TM_BXOR ,
TM_SHL , TM_SHR , TM_UNM , TM_BNOT ,
TM_LT , TM_LE , TM_CONCAT , TM_CALL ,
TM_CLOSE , TM_N
}
Functions
LUAI_FUNC const char * luaT_objtypename (lua_State *L, const TValue *o)
LUAI_FUNC const TValue * luaT_gettm (Table *events, TMS event, TString *ename)
LUAI_FUNC const TValue * luaT_gettmbyobj (lua_State *L, const TValue *o, TMS event)
LUAI_FUNC void luaT_init (lua_State *L)
LUAI_FUNC void luaT_callTM (lua_State *L, const TValue *f, const TValue *p1, const TValue *p2, const TValue *p3)
LUAI_FUNC void luaT_callTMres (lua_State *L, const TValue *f, const TValue *p1, const TValue *p2, StkId p3)
LUAI_FUNC void luaT_trybinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
LUAI_FUNC void luaT_tryconcatTM (lua_State *L)
LUAI_FUNC void luaT_trybinassocTM (lua_State *L, const TValue *p1, const TValue *p2, int inv, StkId res, TMS event)
LUAI_FUNC void luaT_trybiniTM (lua_State *L, const TValue *p1, lua_Integer i2, int inv, StkId res, TMS event)
LUAI_FUNC int luaT_callorderTM (lua_State *L, const TValue *p1, const TValue *p2, TMS event)
LUAI_FUNC int luaT_callorderiTM (lua_State *L, const TValue *p1, int v2, int inv, int isfloat, TMS event)
LUAI_FUNC void luaT_adjustvarargs (lua_State *L, int nfixparams, struct CallInfo *ci, const Proto *p)
LUAI_FUNC void luaT_getvarargs (lua_State *L, struct CallInfo *ci, StkId where, int wanted)
Macro Definition Documentation
fasttm
#define fasttm (l, et, e) gfasttm(G(l), et, e)
Definition at line 67 of file lua-5.4.3/src/ltm.h.
gfasttm
#define gfasttm (g, et, e)
Value:
  ((et) == NULL ? NULL : \
  ((et)->flags & (1u<<(e))) ? NULL : luaT_gettm(et, e, (g)->tmname[e]))
Definition at line 64 of file lua-5.4.3/src/ltm.h.
#define gfasttm(g,et,e) ((et) == NULL ? NULL : \
  ((et)->flags & (1u<<(e))) ? NULL : luaT_gettm(et, e, (g)->tmname[e]))
maskflags
#define maskflags (~(~0u << (TM_EQ + 1)))
Definition at line 54 of file lua-5.4.3/src/ltm.h.
Referenced by luaH_new().
notm
#define notm (tm) ttisnil(tm)
Definition at line 61 of file lua-5.4.3/src/ltm.h.
Referenced by callbinTM(), GCTM(), luaT_gettm(), luaV_finishget(), luaV_finishset(), and luaV_objlen().
ttypename
#define ttypename (x) luaT_typenames_[(x) + 1]
Definition at line 69 of file lua-5.4.3/src/ltm.h.
Enumeration Type Documentation
TMS
enum TMS
Enumerator
TM_INDEX
TM_NEWINDEX
TM_GC
TM_MODE
TM_LEN
TM_EQ
TM_ADD
TM_SUB
TM_MUL
TM_MOD
TM_POW
TM_DIV
TM_IDIV
TM_BAND
TM_BOR
TM_BXOR
TM_SHL
TM_SHR
TM_UNM
TM_BNOT
TM_LT
TM_LE
TM_CONCAT
TM_CALL
TM_CLOSE
TM_N
Definition at line 18 of file lua-5.4.3/src/ltm.h.
             {
  TM_INDEX,
  TM_NEWINDEX,
  TM_GC,
  TM_MODE,
  TM_LEN,
  TM_EQ,  /* last tag method with fast access */
  TM_ADD,
  TM_SUB,
  TM_MUL,
  TM_MOD,
  TM_POW,
  TM_DIV,
  TM_IDIV,
  TM_BAND,
  TM_BOR,
  TM_BXOR,
  TM_SHL,
  TM_SHR,
  TM_UNM,
  TM_BNOT,
  TM_LT,
  TM_LE,
  TM_CONCAT,
  TM_CALL,
  TM_CLOSE,
  TM_N      /* number of elements in the enum */
} TMS;
Function Documentation
luaT_adjustvarargs()
LUAI_FUNC void luaT_adjustvarargs (lua_State * L, int nfixparams, struct CallInfo * ci, const Proto * p)
Definition at line 238 of file lua-5.4.3/src/ltm.c.
{
  int i;
  int actual = cast_int(L->top - ci->func) - 1;  /* number of arguments */
  int nextra = actual - nfixparams;  /* number of extra arguments */
  ci->u.l.nextraargs = nextra;
  luaD_checkstack(L, p->maxstacksize + 1);
  /* copy function to the top of the stack */
  setobjs2s(L, L->top++, ci->func);
  /* move fixed parameters to the top of the stack */
  for (i = 1; i <= nfixparams; i++) {
    setobjs2s(L, L->top++, ci->func + i);
    setnilvalue(s2v(ci->func + i));  /* erase original parameter (for GC) */
  }
  ci->func += actual + 1;
  ci->top += actual + 1;
  lua_assert(L->top <= ci->top && ci->top <= L->stack_last);
}
References cast_int, CallInfo::func, CallInfo::l, lua_assert, luaD_checkstack, Proto::maxstacksize, CallInfo::nextraargs, s2v, setnilvalue, setobjs2s, lua_State::stack_last, CallInfo::top, lua_State::top, and CallInfo::u.
Referenced by luaV_execute().
luaT_callorderiTM()
LUAI_FUNC int luaT_callorderiTM (lua_State * L, const TValue * p1, int v2, int inv, int isfloat, TMS event)
Definition at line 221 of file lua-5.4.3/src/ltm.c.
{
  TValue aux; const TValue *p2;
  if (isfloat) {
    setfltvalue(&aux, cast_num(v2));
  }
  else
    setivalue(&aux, v2);
  if (flip) {  /* arguments were exchanged? */
    p2 = p1; p1 = &aux;  /* correct them */
  }
  else
    p2 = &aux;
  return luaT_callorderTM(L, p1, p2, event);
}
References cast_num, luaT_callorderTM(), setfltvalue, and setivalue.
luaT_callorderTM()
LUAI_FUNC int luaT_callorderTM (lua_State * L, const TValue * p1, const TValue * p2, TMS event)
Definition at line 158 of file lua-5.3.6/src/ltm.c.
{
  if (!luaT_callbinTM(L, p1, p2, L->top, event))
    return -1;  /* no metamethod */
  else
    return !l_isfalse(L->top);
}
References callbinTM(), CallInfo::callstatus, lua_State::ci, CIST_LEQ, l_isfalse, luaG_ordererror(), luaT_callbinTM(), s2v, TM_LE, TM_LT, and lua_State::top.
Referenced by lessequalothers(), lessthanothers(), luaT_callorderiTM(), luaV_lessequal(), and luaV_lessthan().
luaT_callTM()
LUAI_FUNC void luaT_callTM (lua_State * L, const TValue * f, const TValue * p1, const TValue * p2, const TValue * p3)
Definition at line 103 of file lua-5.4.3/src/ltm.c.
{
  StkId func = L->top;
  setobj2s(L, func, f);  /* push function (assume EXTRA_STACK) */
  setobj2s(L, func + 1, p1);  /* 1st argument */
  setobj2s(L, func + 2, p2);  /* 2nd argument */
  setobj2s(L, func + 3, p3);  /* 3rd argument */
  L->top = func + 4;
  /* metamethod may yield only when called from Lua code */
  if (isLuacode(L->ci))
    luaD_call(L, func, 0);
  else
    luaD_callnoyield(L, func, 0);
}
References lua_State::ci, isLuacode, luaD_call(), luaD_callnoyield(), setobj2s, and lua_State::top.
luaT_callTMres()
LUAI_FUNC void luaT_callTMres (lua_State * L, const TValue * f, const TValue * p1, const TValue * p2, StkId p3)
Definition at line 119 of file lua-5.4.3/src/ltm.c.
{
  ptrdiff_t result = savestack(L, res);
  StkId func = L->top;
  setobj2s(L, func, f);  /* push function (assume EXTRA_STACK) */
  setobj2s(L, func + 1, p1);  /* 1st argument */
  setobj2s(L, func + 2, p2);  /* 2nd argument */
  L->top += 3;
  /* metamethod may yield only when called from Lua code */
  if (isLuacode(L->ci))
    luaD_call(L, func, 1);
  else
    luaD_callnoyield(L, func, 1);
  res = restorestack(L, result);
  setobjs2s(L, res, --L->top);  /* move result to its place */
}
References lua_State::ci, isLuacode, luaD_call(), luaD_callnoyield(), restorestack, savestack, setobj2s, setobjs2s, and lua_State::top.
Referenced by callbinTM(), luaV_equalobj(), luaV_finishget(), and luaV_objlen().
luaT_gettm()
LUAI_FUNC const TValue * luaT_gettm (Table * events, TMS event, TString * ename)
Definition at line 50 of file lua-5.1.5/src/ltm.c.
{
  const TValue *tm = luaH_getstr(events, ename);
  lua_assert(event <= TM_EQ);
  if (ttisnil(tm)) {  /* no tag method? */
    events->flags |= cast_byte(1u<<event);  /* cache this fact */
    return NULL;
  }
  else return tm;
}
References cast_byte, Table::flags, lua_assert, luaH_getshortstr(), luaH_getstr(), notm, NULL, TM_EQ, and ttisnil.
luaT_gettmbyobj()
LUAI_FUNC const TValue * luaT_gettmbyobj (lua_State * L, const TValue * o, TMS event)
Definition at line 61 of file lua-5.1.5/src/ltm.c.
{
  Table *mt;
  switch (ttype(o)) {
    case LUA_TTABLE:
      mt = hvalue(o)->metatable;
      break;
    case LUA_TUSERDATA:
      mt = uvalue(o)->metatable;
      break;
    default:
      mt = G(L)->mt[ttype(o)];
  }
  return (mt ? luaH_getstr(mt, G(L)->tmname[event]) : luaO_nilobject);
}
References G, hvalue, LUA_TTABLE, LUA_TUSERDATA, luaH_getshortstr(), luaH_getstr(), luaO_nilobject, Table::metatable, tmname, ttnov, ttype, ttypenv, and uvalue.
Referenced by call_binTM(), call_binTM(), call_orderTM(), callbinTM(), callclosemethod(), checkclosemth(), GCTM(), GCTM(), GCTM(), luaD_tryfuncTM(), luaT_callbinTM(), luaV_finishget(), luaV_finishOp(), luaV_finishset(), luaV_finishset(), luaV_gettable(), luaV_objlen(), luaV_settable(), tryfuncTM(), tryfuncTM(), and tryfuncTM().
luaT_getvarargs()
LUAI_FUNC void luaT_getvarargs (lua_State * L, struct CallInfo * ci, StkId where, int wanted)
Definition at line 258 of file lua-5.4.3/src/ltm.c.
{
  int i;
  int nextra = ci->u.l.nextraargs;
  if (wanted < 0) {
    wanted = nextra;  /* get all extra arguments available */
    checkstackGCp(L, nextra, where);  /* ensure stack space */
    L->top = where + nextra;  /* next instruction will need top */
  }
  for (i = 0; i < wanted && i < nextra; i++)
    setobjs2s(L, where + i, ci->func - nextra + i);
  for (; i < wanted; i++)   /* complete required results with nil */
    setnilvalue(s2v(where + i));
}
References checkstackGCp, CallInfo::func, CallInfo::l, CallInfo::nextraargs, s2v, setnilvalue, setobjs2s, lua_State::top, and CallInfo::u.
Referenced by luaV_execute().
luaT_init()
LUAI_FUNC void luaT_init (lua_State * L)
Definition at line 30 of file lua-5.1.5/src/ltm.c.
{
  static const char *const luaT_eventname[] = {  /* ORDER TM */
    "__index", "__newindex",
    "__gc", "__mode", "__eq",
    "__add", "__sub", "__mul", "__div", "__mod",
    "__pow", "__unm", "__len", "__lt", "__le",
    "__concat", "__call"
  };
  int i;
  for (i=0; i<TM_N; i++) {
    G(L)->tmname[i] = luaS_new(L, luaT_eventname[i]);
    luaS_fix(G(L)->tmname[i]);  /* never collect these names */
  }
}
References G, luaC_fix(), luaS_fix, luaS_new, obj2gco, TM_N, and tmname.
Referenced by f_luaopen(), f_luaopen(), f_luaopen(), and f_luaopen().
luaT_objtypename()
LUAI_FUNC const char * luaT_objtypename (lua_State * L, const TValue * o)
Definition at line 90 of file lua-5.3.6/src/ltm.c.
{
  Table *mt;
  if ((ttistable(o) && (mt = hvalue(o)->metatable) != NULL) ||
      (ttisfulluserdata(o) && (mt = uvalue(o)->metatable) != NULL)) {
    const TValue *name = luaH_getshortstr(mt, luaS_new(L, "__name"));
    if (ttisstring(name))  /* is '__name' a string? */
      return getstr(tsvalue(name));  /* use it as type name */
  }
  return ttypename(ttnov(o));  /* else use standard type name */
}
References getstr, hvalue, luaH_getshortstr(), luaS_new, name, NULL, tsvalue, ttisfulluserdata, ttisstring, ttistable, ttnov, ttype, ttypename, and uvalue.
Referenced by luaG_callerror(), luaG_forerror(), luaG_ordererror(), and luaG_typeerror().
luaT_trybinassocTM()
LUAI_FUNC void luaT_trybinassocTM (lua_State * L, const TValue * p1, const TValue * p2, int inv, StkId res, TMS event)
Definition at line 175 of file lua-5.4.3/src/ltm.c.
{
  if (flip)
    luaT_trybinTM(L, p2, p1, res, event);
  else
    luaT_trybinTM(L, p1, p2, res, event);
}
References luaT_trybinTM().
Referenced by luaT_trybiniTM(), and luaV_execute().
luaT_trybiniTM()
LUAI_FUNC void luaT_trybiniTM (lua_State * L, const TValue * p1, lua_Integer i2, int inv, StkId res, TMS event)
Definition at line 184 of file lua-5.4.3/src/ltm.c.
{
  TValue aux;
  setivalue(&aux, i2);
  luaT_trybinassocTM(L, p1, &aux, flip, res, event);
}
References luaT_trybinassocTM(), and setivalue.
Referenced by luaV_execute().
luaT_trybinTM()
LUAI_FUNC void luaT_trybinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 135 of file lua-5.3.6/src/ltm.c.
{
  if (!luaT_callbinTM(L, p1, p2, res, event)) {
    switch (event) {
      case TM_CONCAT:
        luaG_concaterror(L, p1, p2);
      /* call never returns, but to avoid warnings: *//* FALLTHROUGH */
      case TM_BAND: case TM_BOR: case TM_BXOR:
      case TM_SHL: case TM_SHR: case TM_BNOT: {
        lua_Number dummy;
        if (tonumber(p1, &dummy) && tonumber(p2, &dummy))
          luaG_tointerror(L, p1, p2);
        else
          luaG_opinterror(L, p1, p2, "perform bitwise operation on");
      }
      /* calls never return, but to avoid warnings: *//* FALLTHROUGH */
      default:
        luaG_opinterror(L, p1, p2, "perform arithmetic on");
    }
  }
}
References callbinTM(), dummy, luaG_concaterror(), luaG_opinterror(), luaG_tointerror(), luaT_callbinTM(), TM_BAND, TM_BNOT, TM_BOR, TM_BXOR, TM_CONCAT, TM_SHL, TM_SHR, tonumber, and ttisnumber.
Referenced by luaO_arith(), luaO_arith(), luaT_trybinassocTM(), luaV_concat(), luaV_execute(), and luaV_execute().
luaT_tryconcatTM()
LUAI_FUNC void luaT_tryconcatTM (lua_State * L)
Definition at line 167 of file lua-5.4.3/src/ltm.c.
{
  StkId top = L->top;
  if (l_unlikely(!callbinTM(L, s2v(top - 2), s2v(top - 1), top - 2,
                               TM_CONCAT)))
    luaG_concaterror(L, s2v(top - 2), s2v(top - 1));
}
References callbinTM(), luaG_concaterror(), s2v, TM_CONCAT, and lua_State::top.
Referenced by luaV_concat().