Github User Fetcher: lundump.c File Reference
lundump.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstring.h"
#include "lundump.h"
#include "lzio.h"
Data Structures
struct LoadState
Macros
#define lundump_c
#define LUA_CORE
#define luai_verifycode(L, b, f) /* empty */
#define LoadVector(S, b, n) LoadBlock(S,b,(n)*sizeof((b)[0]))
#define LoadVar(S, x) LoadVector(S,&x,1)
#define checksize(S, t) fchecksize(S,sizeof(t),#t)
Functions
static l_noret error (LoadState *S, const char *why)
static void LoadBlock (LoadState *S, void *b, size_t size)
static lu_byte LoadByte (LoadState *S)
static int LoadInt (LoadState *S)
static lua_Number LoadNumber (LoadState *S)
static lua_Integer LoadInteger (LoadState *S)
static TString * LoadString (LoadState *S, Proto *p)
static void LoadCode (LoadState *S, Proto *f)
static void LoadFunction (LoadState *S, Proto *f, TString *psource)
static void LoadConstants (LoadState *S, Proto *f)
static void LoadProtos (LoadState *S, Proto *f)
static void LoadUpvalues (LoadState *S, Proto *f)
static void LoadDebug (LoadState *S, Proto *f)
static void checkliteral (LoadState *S, const char *s, const char *msg)
static void fchecksize (LoadState *S, size_t size, const char *tname)
static void checkHeader (LoadState *S)
LClosure * luaU_undump (lua_State *L, ZIO *Z, const char *name)
Macro Definition Documentation
checksize
#define checksize (S, t) fchecksize(S,sizeof(t),#t)
Definition at line 241 of file lua-5.3.6/src/lundump.c.
Referenced by checkHeader().
LoadVar
#define LoadVar (S, x) LoadVector(S,&x,1)
Definition at line 57 of file lua-5.3.6/src/lundump.c.
Referenced by LoadByte(), LoadInt(), LoadInteger(), LoadNumber(), and LoadString().
LoadVector
#define LoadVector (S, b, n) LoadBlock(S,b,(n)*sizeof((b)[0]))
Definition at line 49 of file lua-5.3.6/src/lundump.c.
Referenced by checkliteral(), LoadCode(), LoadDebug(), and LoadString().
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/lundump.c.
luai_verifycode
#define luai_verifycode (L, b, f) /* empty */
Definition at line 28 of file lua-5.3.6/src/lundump.c.
Referenced by luaU_undump().
lundump_c
#define lundump_c
Definition at line 7 of file lua-5.3.6/src/lundump.c.
Function Documentation
checkHeader()
static void checkHeader (LoadState * S) static
Definition at line 243 of file lua-5.3.6/src/lundump.c.
{
  checkliteral(S, LUA_SIGNATURE + 1, "not a");  /* 1st char already checked */
  if (LoadByte(S) != LUAC_VERSION)
    error(S, "version mismatch in");
  if (LoadByte(S) != LUAC_FORMAT)
    error(S, "format mismatch in");
  checkliteral(S, LUAC_DATA, "corrupted");
  checksize(S, int);
  checksize(S, size_t);
  checksize(S, Instruction);
  checksize(S, lua_Integer);
  checksize(S, lua_Number);
  if (LoadInteger(S) != LUAC_INT)
    error(S, "endianness mismatch in");
  if (LoadNumber(S) != LUAC_NUM)
    error(S, "float format mismatch in");
}
References checkliteral(), checksize, error(), LoadByte, LoadInteger(), LoadNumber(), LUA_SIGNATURE, LUAC_DATA, LUAC_FORMAT, LUAC_INT, LUAC_NUM, LUAC_VERSION, and S.
Referenced by luaU_undump().
checkliteral()
static void checkliteral (LoadState * S, const char * s, const char * msg) static
Definition at line 226 of file lua-5.3.6/src/lundump.c.
{
  char buff[sizeof(LUA_SIGNATURE) + sizeof(LUAC_DATA)]; /* larger than both */
  size_t len = strlen(s);
  LoadVector(S, buff, len);
  if (memcmp(s, buff, len) != 0)
    error(S, msg);
}
References error(), LoadVector, LUA_SIGNATURE, LUAC_DATA, S, and s.
Referenced by checkHeader().
error()
static l_noret error (LoadState * S, const char * why) static
Definition at line 39 of file lua-5.3.6/src/lundump.c.
{
  luaO_pushfstring(S->L, "%s: %s precompiled chunk", S->name, why);
  luaD_throw(S->L, LUA_ERRSYNTAX);
}
References LUA_ERRSYNTAX, luaD_throw(), luaO_pushfstring(), and S.
Referenced by checkHeader(), checkliteral(), fchecksize(), and LoadBlock().
fchecksize()
static void fchecksize (LoadState * S, size_t size, const char * tname) static
Definition at line 235 of file lua-5.3.6/src/lundump.c.
{
  if (LoadByte(S) != size)
    error(S, luaO_pushfstring(S->L, "%s size mismatch in", tname));
}
References error(), LoadByte, luaO_pushfstring(), and S.
LoadBlock()
static void LoadBlock (LoadState * S, void * b, size_t size) static
Definition at line 51 of file lua-5.3.6/src/lundump.c.
{
  if (luaZ_read(S->Z, b, size) != 0)
    error(S, "truncated");
}
References error(), luaZ_read(), and S.
LoadByte()
static lu_byte LoadByte (LoadState * S) static
Definition at line 60 of file lua-5.3.6/src/lundump.c.
{
  lu_byte x;
  LoadVar(S, x);
  return x;
}
References LoadVar, and S.
LoadCode()
static void LoadCode (LoadState * S, Proto * f) static
Definition at line 113 of file lua-5.3.6/src/lundump.c.
{
  int n = LoadInt(S);
  f->code = luaM_newvector(S->L, n, Instruction);
  f->sizecode = n;
  LoadVector(S, f->code, n);
}
References Proto::code, LoadInt(), LoadVector, luaM_newvector, S, and Proto::sizecode.
Referenced by LoadFunction().
LoadConstants()
static void LoadConstants (LoadState * S, Proto * f) static
Definition at line 124 of file lua-5.3.6/src/lundump.c.
{
  int i;
  int n = LoadInt(S);
  f->k = luaM_newvector(S->L, n, TValue);
  f->sizek = n;
  for (i = 0; i < n; i++)
    setnilvalue(&f->k[i]);
  for (i = 0; i < n; i++) {
    TValue *o = &f->k[i];
    int t = LoadByte(S);
    switch (t) {
    case LUA_TNIL:
      setnilvalue(o);
      break;
    case LUA_TBOOLEAN:
      setbvalue(o, LoadByte(S));
      break;
    case LUA_TNUMFLT:
      setfltvalue(o, LoadNumber(S));
      break;
    case LUA_TNUMINT:
      setivalue(o, LoadInteger(S));
      break;
    case LUA_TSHRSTR:
    case LUA_TLNGSTR:
      setsvalue2n(S->L, o, LoadString(S, f));
      break;
    default:
      lua_assert(0);
    }
  }
}
References Proto::k, LoadByte, LoadInt(), LoadInteger(), LoadNumber(), LoadString(), lua_assert, LUA_TBOOLEAN, LUA_TLNGSTR, LUA_TNIL, LUA_TNUMFLT, LUA_TNUMINT, LUA_TSHRSTR, luaM_newvector, S, setbvalue, setfltvalue, setivalue, setnilvalue, setsvalue2n, and Proto::sizek.
Referenced by LoadFunction().
LoadDebug()
static void LoadDebug (LoadState * S, Proto * f) static
Definition at line 187 of file lua-5.3.6/src/lundump.c.
{
  int i, n;
  n = LoadInt(S);
  f->lineinfo = luaM_newvector(S->L, n, int);
  f->sizelineinfo = n;
  LoadVector(S, f->lineinfo, n);
  n = LoadInt(S);
  f->locvars = luaM_newvector(S->L, n, LocVar);
  f->sizelocvars = n;
  for (i = 0; i < n; i++)
    f->locvars[i].varname = NULL;
  for (i = 0; i < n; i++) {
    f->locvars[i].varname = LoadString(S, f);
    f->locvars[i].startpc = LoadInt(S);
    f->locvars[i].endpc = LoadInt(S);
  }
  n = LoadInt(S);
  for (i = 0; i < n; i++)
    f->upvalues[i].name = LoadString(S, f);
}
References LocVar::endpc, Proto::lineinfo, LoadInt(), LoadString(), LoadVector, Proto::locvars, luaM_newvector, NULL, S, Proto::sizelineinfo, Proto::sizelocvars, LocVar::startpc, Proto::upvalues, and LocVar::varname.
Referenced by LoadFunction().
LoadFunction()
static void LoadFunction (LoadState * S, Proto * f, TString * psource) static
Definition at line 209 of file lua-5.3.6/src/lundump.c.
{
  f->source = LoadString(S, f);
  if (f->source == NULL)  /* no source in dump? */
    f->source = psource;  /* reuse parent's source */
  f->linedefined = LoadInt(S);
  f->lastlinedefined = LoadInt(S);
  f->numparams = LoadByte(S);
  f->is_vararg = LoadByte(S);
  f->maxstacksize = LoadByte(S);
  LoadCode(S, f);
  LoadConstants(S, f);
  LoadUpvalues(S, f);
  LoadProtos(S, f);
  LoadDebug(S, f);
}
References Proto::is_vararg, Proto::lastlinedefined, Proto::linedefined, LoadByte, LoadCode(), LoadConstants(), LoadDebug(), LoadInt(), LoadProtos(), LoadString(), LoadUpvalues(), Proto::maxstacksize, NULL, Proto::numparams, S, and Proto::source.
Referenced by LoadProtos(), and luaU_undump().
LoadInt()
static int LoadInt (LoadState * S) static
Definition at line 67 of file lua-5.3.6/src/lundump.c.
{
  int x;
  LoadVar(S, x);
  return x;
}
References LoadVar, and S.
Referenced by LoadCode(), LoadConstants(), LoadDebug(), LoadFunction(), LoadProtos(), and LoadUpvalues().
LoadInteger()
static lua_Integer LoadInteger (LoadState * S) static
Definition at line 81 of file lua-5.3.6/src/lundump.c.
{
  lua_Integer x;
  LoadVar(S, x);
  return x;
}
References LoadVar, and S.
Referenced by checkHeader(), and LoadConstants().
LoadNumber()
static lua_Number LoadNumber (LoadState * S) static
Definition at line 74 of file lua-5.3.6/src/lundump.c.
{
  lua_Number x;
  LoadVar(S, x);
  return x;
}
References LoadVar, and S.
Referenced by checkHeader(), and LoadConstants().
LoadProtos()
static void LoadProtos (LoadState * S, Proto * f) static
Definition at line 158 of file lua-5.3.6/src/lundump.c.
{
  int i;
  int n = LoadInt(S);
  f->p = luaM_newvector(S->L, n, Proto *);
  f->sizep = n;
  for (i = 0; i < n; i++)
    f->p[i] = NULL;
  for (i = 0; i < n; i++) {
    f->p[i] = luaF_newproto(S->L);
    luaC_objbarrier(S->L, f, f->p[i]);
    LoadFunction(S, f->p[i], f->source);
  }
}
References LoadFunction(), LoadInt(), luaC_objbarrier, luaF_newproto(), luaM_newvector, NULL, Proto::p, S, Proto::sizep, and Proto::source.
Referenced by LoadFunction().
LoadString()
static TString * LoadString (LoadState * S, Proto * p) static
Definition at line 88 of file lua-5.3.6/src/lundump.c.
{
  lua_State *L = S->L;
  size_t size = LoadByte(S);
  TString *ts;
  if (size == 0xFF)
    LoadVar(S, size);
  if (size == 0)
    return NULL;
  else if (--size <= LUAI_MAXSHORTLEN) {  /* short string? */
    char buff[LUAI_MAXSHORTLEN];
    LoadVector(S, buff, size);
    ts = luaS_newlstr(L, buff, size);
  }
  else {  /* long string */
    ts = luaS_createlngstrobj(L, size);
    setsvalue2s(L, L->top, ts);  /* anchor it ('loadVector' can GC) */
    luaD_inctop(L);
    LoadVector(S, getstr(ts), size);  /* load directly in final place */
    L->top--;  /* pop string */
  }
  luaC_objbarrier(L, p, ts);
  return ts;
}
References getstr, LoadByte, LoadVar, LoadVector, luaC_objbarrier, luaD_inctop(), LUAI_MAXSHORTLEN, luaS_createlngstrobj(), luaS_newlstr(), NULL, S, setsvalue2s, and lua_State::top.
Referenced by LoadConstants(), LoadDebug(), and LoadFunction().
LoadUpvalues()
static void LoadUpvalues (LoadState * S, Proto * f) static
Definition at line 173 of file lua-5.3.6/src/lundump.c.
{
  int i, n;
  n = LoadInt(S);
  f->upvalues = luaM_newvector(S->L, n, Upvaldesc);
  f->sizeupvalues = n;
  for (i = 0; i < n; i++)
    f->upvalues[i].name = NULL;
  for (i = 0; i < n; i++) {
    f->upvalues[i].instack = LoadByte(S);
    f->upvalues[i].idx = LoadByte(S);
  }
}
References LoadByte, LoadInt(), luaM_newvector, NULL, S, Proto::sizeupvalues, and Proto::upvalues.
Referenced by LoadFunction().
luaU_undump()
LClosure * luaU_undump (lua_State * L, ZIO * Z, const char * name)
Definition at line 265 of file lua-5.3.6/src/lundump.c.
{
  LoadState S;
  LClosure *cl;
  if (*name == '@' || *name == '=')
    S.name = name + 1;
  else if (*name == LUA_SIGNATURE[0])
    S.name = "binary string";
  else
    S.name = name;
  S.L = L;
  S.Z = Z;
  checkHeader(&S);
  cl = luaF_newLclosure(L, LoadByte(&S));
  setclLvalue(L, L->top, cl);
  luaD_inctop(L);
  cl->p = luaF_newproto(L);
  luaC_objbarrier(L, cl, cl->p);
  LoadFunction(&S, cl->p, NULL);
  lua_assert(cl->nupvalues == cl->p->sizeupvalues);
  luai_verifycode(L, buff, cl->p);
  return cl;
}
References checkHeader(), LoadByte, LoadFunction(), lua_assert, LUA_SIGNATURE, luaC_objbarrier, luaD_inctop(), luaF_newLclosure(), luaF_newproto(), luai_verifycode, name, NULL, LClosure::p, S, setclLvalue, Proto::sizeupvalues, and lua_State::top.