Github User Fetcher: lzio.c File Reference
lzio.c File Reference
#include <string.h>
#include "lua.h"
#include "llimits.h"
#include "lmem.h"
#include "lstate.h"
#include "lzio.h"
Macros
#define lzio_c
#define LUA_CORE
Functions
int luaZ_fill (ZIO *z)
int luaZ_lookahead (ZIO *z)
void luaZ_init (lua_State *L, ZIO *z, lua_Reader reader, void *data)
size_t luaZ_read (ZIO *z, void *b, size_t n)
char * luaZ_openspace (lua_State *L, Mbuffer *buff, size_t n)
Macro Definition Documentation
LUA_CORE
#define LUA_CORE
Definition at line 11 of file lua-5.1.5/src/lzio.c.
lzio_c
#define lzio_c
Definition at line 10 of file lua-5.1.5/src/lzio.c.
Function Documentation
luaZ_fill()
int luaZ_fill (ZIO * z)
Definition at line 21 of file lua-5.1.5/src/lzio.c.
                       {
  size_t size;
  lua_State *L = z->L;
  const char *buff;
  lua_unlock(L);
  buff = z->reader(L, z->data, &size);
  lua_lock(L);
  if (buff == NULL || size == 0) return EOZ;
  z->n = size - 1;
  z->p = buff;
  return char2int(*(z->p++));
}
References char2int, Zio::data, EOZ, Zio::L, lua_lock, lua_unlock, Zio::n, NULL, Zio::p, and Zio::reader.
Referenced by luaZ_lookahead().
luaZ_init()
void luaZ_init (lua_State * L, ZIO * z, lua_Reader reader, void * data)
Definition at line 48 of file lua-5.1.5/src/lzio.c.
{
  z->L = L;
  z->reader = reader;
  z->data = data;
  z->n = 0;
  z->p = NULL;
}
References Zio::data, Zio::L, Zio::n, NULL, Zio::p, Zio::reader, and reader().
Referenced by lua_load(), and lua_load().
luaZ_lookahead()
int luaZ_lookahead (ZIO * z)
Definition at line 35 of file lua-5.1.5/src/lzio.c.
{
  if (z->n == 0) {
    if (luaZ_fill(z) == EOZ)
      return EOZ;
    else {
      z->n++;  /* luaZ_fill removed first byte; put back it */
      z->p--;
    }
  }
  return char2int(*z->p);
}
References char2int, EOZ, luaZ_fill(), Zio::n, and Zio::p.
Referenced by f_parser(), and luaZ_read().
luaZ_openspace()
char * luaZ_openspace (lua_State * L, Mbuffer * buff, size_t n)
Definition at line 74 of file lua-5.1.5/src/lzio.c.
{
  if (n > buff->buffsize) {
    if (n < LUA_MINBUFFER) n = LUA_MINBUFFER;
    luaZ_resizebuffer(L, buff, n);
  }
  return buff->buffer;
}
References Mbuffer::buffer, Mbuffer::buffsize, LUA_MINBUFFER, and luaZ_resizebuffer.
Referenced by LoadString(), LoadString(), luaV_concat(), and luaV_concat().
luaZ_read()
size_t luaZ_read (ZIO * z, void * b, size_t n)
Definition at line 58 of file lua-5.1.5/src/lzio.c.
{
  while (n) {
    size_t m;
    if (luaZ_lookahead(z) == EOZ)
      return n;  /* return number of missing bytes */
    m = (n <= z->n) ? n : z->n;  /* min. between n and z->n */
    memcpy(b, z->p, m);
    z->n -= m;
    z->p += m;
    b = (char *)b + m;
    n -= m;
  }
  return 0;
}
References EOZ, luaZ_lookahead(), Zio::n, and Zio::p.
Referenced by LoadBlock(), LoadBlock(), LoadBlock(), and loadBlock().