Github User Fetcher: lapi.c File Reference
lapi.c File Reference
#include <stdarg.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lundump.h"
#include "lvm.h"
Data Structures
struct CallS
Macros
#define lapi_c
#define LUA_CORE
#define NONVALIDVALUE cast(TValue *, luaO_nilobject)
#define isvalid(o) ((o) != luaO_nilobject)
#define ispseudo(i) ((i) <= LUA_REGISTRYINDEX)
#define isstackindex(i, o) (isvalid(o) && !ispseudo(i))
#define api_checkvalidindex(L, o) api_check(L, isvalid(o), "invalid index")
#define api_checkstackindex(L, i, o) api_check(L, isstackindex(i, o), "index not in the stack")
#define checkresults(L, na, nr)
Functions
static TValue * index2addr (lua_State *L, int idx)
static void growstack (lua_State *L, void *ud)
LUA_API int lua_checkstack (lua_State *L, int size)
LUA_API void lua_xmove (lua_State *from, lua_State *to, int n)
LUA_API lua_CFunction lua_atpanic (lua_State *L, lua_CFunction panicf)
LUA_API const lua_Number * lua_version (lua_State *L)
LUA_API int lua_absindex (lua_State *L, int idx)
LUA_API int lua_gettop (lua_State *L)
LUA_API void lua_settop (lua_State *L, int idx)
LUA_API void lua_remove (lua_State *L, int idx)
LUA_API void lua_insert (lua_State *L, int idx)
static void moveto (lua_State *L, TValue *fr, int idx)
LUA_API void lua_replace (lua_State *L, int idx)
LUA_API void lua_copy (lua_State *L, int fromidx, int toidx)
LUA_API void lua_pushvalue (lua_State *L, int idx)
LUA_API int lua_type (lua_State *L, int idx)
LUA_API const char * lua_typename (lua_State *L, int t)
LUA_API int lua_iscfunction (lua_State *L, int idx)
LUA_API int lua_isnumber (lua_State *L, int idx)
LUA_API int lua_isstring (lua_State *L, int idx)
LUA_API int lua_isuserdata (lua_State *L, int idx)
LUA_API int lua_rawequal (lua_State *L, int index1, int index2)
LUA_API void lua_arith (lua_State *L, int op)
LUA_API int lua_compare (lua_State *L, int index1, int index2, int op)
LUA_API lua_Number lua_tonumberx (lua_State *L, int idx, int *isnum)
LUA_API lua_Integer lua_tointegerx (lua_State *L, int idx, int *isnum)
LUA_API lua_Unsigned lua_tounsignedx (lua_State *L, int idx, int *isnum)
LUA_API int lua_toboolean (lua_State *L, int idx)
LUA_API const char * lua_tolstring (lua_State *L, int idx, size_t *len)
LUA_API size_t lua_rawlen (lua_State *L, int idx)
LUA_API lua_CFunction lua_tocfunction (lua_State *L, int idx)
LUA_API void * lua_touserdata (lua_State *L, int idx)
LUA_API lua_State * lua_tothread (lua_State *L, int idx)
LUA_API const void * lua_topointer (lua_State *L, int idx)
LUA_API void lua_pushnil (lua_State *L)
LUA_API void lua_pushnumber (lua_State *L, lua_Number n)
LUA_API void lua_pushinteger (lua_State *L, lua_Integer n)
LUA_API void lua_pushunsigned (lua_State *L, lua_Unsigned u)
LUA_API const char * lua_pushlstring (lua_State *L, const char *s, size_t len)
LUA_API const char * lua_pushstring (lua_State *L, const char *s)
LUA_API const char * lua_pushvfstring (lua_State *L, const char *fmt, va_list argp)
LUA_API const char * lua_pushfstring (lua_State *L, const char *fmt,...)
LUA_API void lua_pushcclosure (lua_State *L, lua_CFunction fn, int n)
LUA_API void lua_pushboolean (lua_State *L, int b)
LUA_API void lua_pushlightuserdata (lua_State *L, void *p)
LUA_API int lua_pushthread (lua_State *L)
LUA_API void lua_getglobal (lua_State *L, const char *var)
LUA_API void lua_gettable (lua_State *L, int idx)
LUA_API void lua_getfield (lua_State *L, int idx, const char *k)
LUA_API void lua_rawget (lua_State *L, int idx)
LUA_API void lua_rawgeti (lua_State *L, int idx, int n)
LUA_API void lua_rawgetp (lua_State *L, int idx, const void *p)
LUA_API void lua_createtable (lua_State *L, int narray, int nrec)
LUA_API int lua_getmetatable (lua_State *L, int objindex)
LUA_API void lua_getuservalue (lua_State *L, int idx)
LUA_API void lua_setglobal (lua_State *L, const char *var)
LUA_API void lua_settable (lua_State *L, int idx)
LUA_API void lua_setfield (lua_State *L, int idx, const char *k)
LUA_API void lua_rawset (lua_State *L, int idx)
LUA_API void lua_rawseti (lua_State *L, int idx, int n)
LUA_API void lua_rawsetp (lua_State *L, int idx, const void *p)
LUA_API int lua_setmetatable (lua_State *L, int objindex)
LUA_API void lua_setuservalue (lua_State *L, int idx)
LUA_API int lua_getctx (lua_State *L, int *ctx)
LUA_API void lua_callk (lua_State *L, int nargs, int nresults, int ctx, lua_CFunction k)
static void f_call (lua_State *L, void *ud)
LUA_API int lua_pcallk (lua_State *L, int nargs, int nresults, int errfunc, int ctx, lua_CFunction k)
LUA_API int lua_load (lua_State *L, lua_Reader reader, void *data, const char *chunkname, const char *mode)
LUA_API int lua_dump (lua_State *L, lua_Writer writer, void *data)
LUA_API int lua_status (lua_State *L)
LUA_API int lua_gc (lua_State *L, int what, int data)
LUA_API int lua_error (lua_State *L)
LUA_API int lua_next (lua_State *L, int idx)
LUA_API void lua_concat (lua_State *L, int n)
LUA_API void lua_len (lua_State *L, int idx)
LUA_API lua_Alloc lua_getallocf (lua_State *L, void **ud)
LUA_API void lua_setallocf (lua_State *L, lua_Alloc f, void *ud)
LUA_API void * lua_newuserdata (lua_State *L, size_t size)
static const char * aux_upvalue (StkId fi, int n, TValue **val, GCObject **owner)
LUA_API const char * lua_getupvalue (lua_State *L, int funcindex, int n)
LUA_API const char * lua_setupvalue (lua_State *L, int funcindex, int n)
static UpVal ** getupvalref (lua_State *L, int fidx, int n, LClosure **pf)
LUA_API void * lua_upvalueid (lua_State *L, int fidx, int n)
LUA_API void lua_upvaluejoin (lua_State *L, int fidx1, int n1, int fidx2, int n2)
Variables
const char lua_ident []
Macro Definition Documentation
api_checkstackindex
#define api_checkstackindex (L, i, o) api_check(L, isstackindex(i, o), "index not in the stack")
Definition at line 51 of file lua-5.2.4/src/lapi.c.
#define api_checkstackindex(L, i, o)  \
    api_check(L, isstackindex(i, o), "index not in the stack")
Referenced by lua_insert(), lua_pcallk(), and lua_remove().
api_checkvalidindex
#define api_checkvalidindex (L, o) api_check(L, isvalid(o), "invalid index")
Definition at line 49 of file lua-5.2.4/src/lapi.c.
Referenced by moveto().
checkresults
#define checkresults (L, na, nr)
Value:
     api_check(L, (nr) == LUA_MULTRET || (L->ci->top - L->top >= (nr) - (na)), \
    "results from function overflow current stack size")
Definition at line 875 of file lua-5.2.4/src/lapi.c.
#define checkresults(L,na,nr) \
     api_check(L, (nr) == LUA_MULTRET || (L->ci->top - L->top >= (nr) - (na)), \
    "results from function overflow current stack size")
Referenced by lua_callk(), and lua_pcallk().
ispseudo
#define ispseudo (i) ((i) <= LUA_REGISTRYINDEX)
Definition at line 44 of file lua-5.2.4/src/lapi.c.
Referenced by index2addr(), and lua_absindex().
isstackindex
#define isstackindex (i, o) (isvalid(o) && !ispseudo(i))
Definition at line 47 of file lua-5.2.4/src/lapi.c.
isvalid
#define isvalid (o) ((o) != luaO_nilobject)
Definition at line 41 of file lua-5.2.4/src/lapi.c.
Referenced by lua_compare(), lua_rawequal(), and lua_type().
lapi_c
#define lapi_c
Definition at line 11 of file lua-5.2.4/src/lapi.c.
LUA_CORE
#define LUA_CORE
Definition at line 12 of file lua-5.2.4/src/lapi.c.
NONVALIDVALUE
#define NONVALIDVALUE cast(TValue *, luaO_nilobject)
Definition at line 38 of file lua-5.2.4/src/lapi.c.
Referenced by index2addr().
Function Documentation
aux_upvalue()
static const char * aux_upvalue (StkId fi, int n, TValue ** val, GCObject ** owner) static
Definition at line 1188 of file lua-5.2.4/src/lapi.c.
{
  switch (ttype(fi)) {
    case LUA_TCCL: {  /* C closure */
      CClosure *f = clCvalue(fi);
      if (!(1 <= n && n <= f->nupvalues)) return NULL;
      *val = &f->upvalue[n-1];
      if (owner) *owner = obj2gco(f);
      return "";
    }
    case LUA_TLCL: {  /* Lua closure */
      LClosure *f = clLvalue(fi);
      TString *name;
      Proto *p = f->p;
      if (!(1 <= n && n <= p->sizeupvalues)) return NULL;
      *val = f->upvals[n-1]->v;
      if (owner) *owner = obj2gco(f->upvals[n - 1]);
      name = p->upvalues[n-1].name;
      return (name == NULL) ? "" : getstr(name);
    }
    default: return NULL;  /* not a closure */
  }
}
References clCvalue, clLvalue, getstr, LUA_TCCL, LUA_TLCL, name, NULL, obj2gco, owner, LClosure::p, ttype, LClosure::upvals, CClosure::upvalue, Proto::upvalues, and UpVal::v.
Referenced by lua_getupvalue(), and lua_setupvalue().
f_call()
static void f_call (lua_State * L, void * ud) static
Definition at line 921 of file lua-5.2.4/src/lapi.c.
{
  struct CallS *c = cast(struct CallS *, ud);
  luaD_call(L, c->func, c->nresults, 0);
}
References cast, CallS::func, luaD_call(), and CallS::nresults.
Referenced by lua_pcallk().
getupvalref()
static UpVal ** getupvalref (lua_State * L, int fidx, int n, LClosure ** pf) static
Definition at line 1246 of file lua-5.2.4/src/lapi.c.
{
  LClosure *f;
  StkId fi = index2addr(L, fidx);
  api_check(L, ttisLclosure(fi), "Lua function expected");
  f = clLvalue(fi);
  api_check(L, (1 <= n && n <= f->p->sizeupvalues), "invalid upvalue index");
  if (pf) *pf = f;
  return &f->upvals[n - 1];  /* get its upvalue pointer */
}
References api_check, clLvalue, index2addr(), ttisLclosure, and LClosure::upvals.
Referenced by lua_upvalueid(), and lua_upvaluejoin().
growstack()
static void growstack (lua_State * L, void * ud) static
Definition at line 86 of file lua-5.2.4/src/lapi.c.
{
  int size = *(int *)ud;
  luaD_growstack(L, size);
}
References luaD_growstack().
Referenced by lua_checkstack().
index2addr()
static TValue * index2addr (lua_State * L, int idx) static
Definition at line 55 of file lua-5.2.4/src/lapi.c.
{
  CallInfo *ci = L->ci;
  if (idx > 0) {
    TValue *o = ci->func + idx;
    api_check(L, idx <= ci->top - (ci->func + 1), "unacceptable index");
    if (o >= L->top) return NONVALIDVALUE;
    else return o;
  }
  else if (!ispseudo(idx)) {  /* negative index */
    api_check(L, idx != 0 && -idx <= L->top - (ci->func + 1), "invalid index");
    return L->top + idx;
  }
  else if (idx == LUA_REGISTRYINDEX)
    return &G(L)->l_registry;
  else {  /* upvalues */
    idx = LUA_REGISTRYINDEX - idx;
    api_check(L, idx <= MAXUPVAL + 1, "upvalue index too large");
    if (ttislcf(ci->func))  /* light C function? */
      return NONVALIDVALUE;  /* it has no upvalues */
    else {
      CClosure *func = clCvalue(ci->func);
      return (idx <= func->nupvalues) ? &func->upvalue[idx-1] : NONVALIDVALUE;
    }
  }
}
References api_check, lua_State::ci, clCvalue, CallInfo::func, G, ispseudo, LUA_REGISTRYINDEX, MAXUPVAL, NONVALIDVALUE, lua_State::top, ttislcf, and CClosure::upvalue.
Referenced by getupvalref(), lua_compare(), lua_copy(), lua_getfield(), lua_getmetatable(), lua_gettable(), lua_getupvalue(), lua_getuservalue(), lua_insert(), lua_iscfunction(), lua_isnumber(), lua_isuserdata(), lua_len(), lua_next(), lua_pcallk(), lua_pushvalue(), lua_rawequal(), lua_rawget(), lua_rawgeti(), lua_rawgetp(), lua_rawlen(), lua_rawset(), lua_rawseti(), lua_rawsetp(), lua_remove(), lua_setfield(), lua_setmetatable(), lua_settable(), lua_setupvalue(), lua_setuservalue(), lua_toboolean(), lua_tocfunction(), lua_tointegerx(), lua_tolstring(), lua_tonumberx(), lua_topointer(), lua_tothread(), lua_tounsignedx(), lua_touserdata(), lua_type(), lua_upvalueid(), and moveto().
lua_absindex()
LUA_API int lua_absindex (lua_State * L, int idx)
Definition at line 153 of file lua-5.2.4/src/lapi.c.
{
  return (idx > 0 || ispseudo(idx))
         ? idx
         : cast_int(L->top - L->ci->func + idx);
}
References cast_int, lua_State::ci, CallInfo::func, ispseudo, and lua_State::top.
Referenced by luaL_callmeta(), luaL_getsubtable(), luaL_ref(), and luaL_unref().
lua_arith()
LUA_API void lua_arith (lua_State * L, int op)
Definition at line 293 of file lua-5.2.4/src/lapi.c.
{
  StkId o1;  /* 1st operand */
  StkId o2;  /* 2nd operand */
  lua_lock(L);
  if (op != LUA_OPUNM) /* all other operations expect two operands */
    api_checknelems(L, 2);
  else {  /* for unary minus, add fake 2nd operand */
    api_checknelems(L, 1);
    setobjs2s(L, L->top, L->top - 1);
    L->top++;
  }
  o1 = L->top - 2;
  o2 = L->top - 1;
  if (ttisnumber(o1) && ttisnumber(o2)) {
    setnvalue(o1, luaO_arith(op, nvalue(o1), nvalue(o2)));
  }
  else
    luaV_arith(L, o1, o1, o2, cast(TMS, op - LUA_OPADD + TM_ADD));
  L->top--;
  lua_unlock(L);
}
References api_checknelems, cast, lua_lock, LUA_OPADD, LUA_OPUNM, lua_unlock, luaO_arith(), luaV_arith(), nvalue, setnvalue, setobjs2s, TM_ADD, lua_State::top, and ttisnumber.
Referenced by arith().
lua_atpanic()
LUA_API lua_CFunction lua_atpanic (lua_State * L, lua_CFunction panicf)
Definition at line 127 of file lua-5.2.4/src/lapi.c.
{
  lua_CFunction old;
  lua_lock(L);
  old = G(L)->panic;
  G(L)->panic = panicf;
  lua_unlock(L);
  return old;
}
References G, lua_lock, and lua_unlock.
lua_callk()
LUA_API void lua_callk (lua_State * L, int nargs, int nresults, int ctx, lua_CFunction k)
Definition at line 889 of file lua-5.2.4/src/lapi.c.
{
  StkId func;
  lua_lock(L);
  api_check(L, k == NULL || !isLua(L->ci),
    "cannot use continuations inside hooks");
  api_checknelems(L, nargs+1);
  api_check(L, L->status == LUA_OK, "cannot do calls on non-normal thread");
  checkresults(L, nargs, nresults);
  func = L->top - (nargs+1);
  if (k != NULL && L->nny == 0) {  /* need to prepare continuation? */
    L->ci->u.c.k = k;  /* save continuation */
    L->ci->u.c.ctx = ctx;  /* save context */
    luaD_call(L, func, nresults, 1);  /* do the call */
  }
  else  /* no continuation or no yieldable */
    luaD_call(L, func, nresults, 0);  /* just do the call */
  adjustresults(L, nresults);
  lua_unlock(L);
}
References adjustresults, api_check, api_checknelems, CallInfo::c, checkresults, lua_State::ci, CallInfo::ctx, isLua, CallInfo::k, lua_lock, LUA_OK, lua_unlock, luaD_call(), lua_State::nny, NULL, lua_State::status, lua_State::top, and CallInfo::u.
Referenced by luaB_dofile(), luaB_dofile(), and luaB_dofile().
lua_checkstack()
LUA_API int lua_checkstack (lua_State * L, int size)
Definition at line 92 of file lua-5.2.4/src/lapi.c.
{
  int res;
  CallInfo *ci = L->ci;
  lua_lock(L);
  if (L->stack_last - L->top > size)  /* stack large enough? */
    res = 1;  /* yes; check is OK */
  else {  /* no; need to grow stack */
    int inuse = cast_int(L->top - L->stack) + EXTRA_STACK;
    if (inuse > LUAI_MAXSTACK - size)  /* can grow without overflow? */
      res = 0;  /* no */
    else  /* try to grow stack */
      res = (luaD_rawrunprotected(L, &growstack, &size) == LUA_OK);
  }
  if (res && ci->top < L->top + size)
    ci->top = L->top + size;  /* adjust frame top */
  lua_unlock(L);
  return res;
}
References cast_int, lua_State::ci, EXTRA_STACK, growstack(), lua_lock, LUA_OK, lua_unlock, luaD_rawrunprotected(), LUAI_MAXSTACK, lua_State::stack, lua_State::stack_last, CallInfo::top, and lua_State::top.
lua_compare()
LUA_API int lua_compare (lua_State * L, int index1, int index2, int op)
Definition at line 316 of file lua-5.2.4/src/lapi.c.
{
  StkId o1, o2;
  int i = 0;
  lua_lock(L);  /* may call tag method */
  o1 = index2addr(L, index1);
  o2 = index2addr(L, index2);
  if (isvalid(o1) && isvalid(o2)) {
    switch (op) {
      case LUA_OPEQ: i = equalobj(L, o1, o2); break;
      case LUA_OPLT: i = luaV_lessthan(L, o1, o2); break;
      case LUA_OPLE: i = luaV_lessequal(L, o1, o2); break;
      default: api_check(L, 0, "invalid option");
    }
  }
  lua_unlock(L);
  return i;
}
References api_check, equalobj, index2addr(), isvalid, lua_lock, LUA_OPEQ, LUA_OPLE, LUA_OPLT, lua_unlock, luaV_lessequal(), and luaV_lessthan().
Referenced by math_max(), math_max(), math_min(), math_min(), sort_comp(), sort_comp(), sort_comp(), tmove(), and tmove().
lua_concat()
LUA_API void lua_concat (lua_State * L, int n)
Definition at line 1131 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  api_checknelems(L, n);
  if (n >= 2) {
    luaC_checkGC(L);
    luaV_concat(L, n);
  }
  else if (n == 0) {  /* push empty string */
    setsvalue2s(L, L->top, luaS_newlstr(L, "", 0));
    api_incr_top(L);
  }
  /* else n == 1; nothing to do */
  lua_unlock(L);
}
References api_checknelems, api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaS_newlstr(), luaV_concat(), setsvalue2s, and lua_State::top.
lua_copy()
LUA_API void lua_copy (lua_State * L, int fromidx, int toidx)
Definition at line 226 of file lua-5.2.4/src/lapi.c.
{
  TValue *fr;
  lua_lock(L);
  fr = index2addr(L, fromidx);
  moveto(L, fr, toidx);
  lua_unlock(L);
}
References index2addr(), lua_lock, lua_unlock, and moveto().
Referenced by ll_require(), luaB_xpcall(), pushglobalfuncname(), pushglobalfuncname(), and pushglobalfuncname().
lua_createtable()
LUA_API void lua_createtable (lua_State * L, int narray, int nrec)
Definition at line 673 of file lua-5.2.4/src/lapi.c.
{
  Table *t;
  lua_lock(L);
  luaC_checkGC(L);
  t = luaH_new(L);
  sethvalue(L, L->top, t);
  api_incr_top(L);
  if (narray > 0 || nrec > 0)
    luaH_resize(L, t, narray, nrec);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaH_new(), luaH_resize(), sethvalue, and lua_State::top.
lua_dump()
LUA_API int lua_dump (lua_State * L, lua_Writer writer, void * data)
Definition at line 997 of file lua-5.2.4/src/lapi.c.
{
  int status;
  TValue *o;
  lua_lock(L);
  api_checknelems(L, 1);
  o = L->top - 1;
  if (isLfunction(o))
    status = luaU_dump(L, getproto(o), writer, data, 0);
  else
    status = 1;
  lua_unlock(L);
  return status;
}
References api_checknelems, getproto, isLfunction, lua_lock, lua_unlock, luaU_dump(), lua_State::top, and writer().
lua_error()
LUA_API int lua_error (lua_State * L)
Definition at line 1105 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  api_checknelems(L, 1);
  luaG_errormsg(L);
  /* code unreachable; will unlock when control actually leaves the kernel */
  return 0;  /* to avoid warnings */
}
References api_checknelems, lua_lock, and luaG_errormsg().
lua_gc()
LUA_API int lua_gc (lua_State * L, int what, int data)
Definition at line 1021 of file lua-5.2.4/src/lapi.c.
{
  int res = 0;
  global_State *g;
  lua_lock(L);
  g = G(L);
  switch (what) {
    case LUA_GCSTOP: {
      g->gcrunning = 0;
      break;
    }
    case LUA_GCRESTART: {
      luaE_setdebt(g, 0);
      g->gcrunning = 1;
      break;
    }
    case LUA_GCCOLLECT: {
      luaC_fullgc(L, 0);
      break;
    }
    case LUA_GCCOUNT: {
      /* GC values are expressed in Kbytes: #bytes/2^10 */
      res = cast_int(gettotalbytes(g) >> 10);
      break;
    }
    case LUA_GCCOUNTB: {
      res = cast_int(gettotalbytes(g) & 0x3ff);
      break;
    }
    case LUA_GCSTEP: {
      if (g->gckind == KGC_GEN) {  /* generational mode? */
        res = (g->GCestimate == 0);  /* true if it will do major collection */
        luaC_forcestep(L);  /* do a single step */
      }
      else {
       lu_mem debt = cast(lu_mem, data) * 1024 - GCSTEPSIZE;
       if (g->gcrunning)
         debt += g->GCdebt;  /* include current debt */
       luaE_setdebt(g, debt);
       luaC_forcestep(L);
       if (g->gcstate == GCSpause)  /* end of cycle? */
         res = 1;  /* signal it */
      }
      break;
    }
    case LUA_GCSETPAUSE: {
      res = g->gcpause;
      g->gcpause = data;
      break;
    }
    case LUA_GCSETMAJORINC: {
      res = g->gcmajorinc;
      g->gcmajorinc = data;
      break;
    }
    case LUA_GCSETSTEPMUL: {
      res = g->gcstepmul;
      g->gcstepmul = data;
      break;
    }
    case LUA_GCISRUNNING: {
      res = g->gcrunning;
      break;
    }
    case LUA_GCGEN: {  /* change collector to generational mode */
      luaC_changemode(L, KGC_GEN);
      break;
    }
    case LUA_GCINC: {  /* change collector to incremental mode */
      luaC_changemode(L, KGC_NORMAL);
      break;
    }
    default: res = -1;  /* invalid option */
  }
  lua_unlock(L);
  return res;
}
References cast, cast_int, G, global_State::GCdebt, global_State::GCestimate, global_State::gckind, global_State::gcmajorinc, global_State::gcpause, global_State::gcrunning, GCSpause, global_State::gcstate, global_State::gcstepmul, GCSTEPSIZE, gettotalbytes, KGC_GEN, KGC_NORMAL, LUA_GCCOLLECT, LUA_GCCOUNT, LUA_GCCOUNTB, LUA_GCGEN, LUA_GCINC, LUA_GCISRUNNING, LUA_GCRESTART, LUA_GCSETMAJORINC, LUA_GCSETPAUSE, LUA_GCSETSTEPMUL, LUA_GCSTEP, LUA_GCSTOP, lua_lock, lua_unlock, luaC_changemode(), luaC_forcestep(), luaC_fullgc(), and luaE_setdebt().
lua_getallocf()
LUA_API lua_Alloc lua_getallocf (lua_State * L, void ** ud)
Definition at line 1157 of file lua-5.2.4/src/lapi.c.
{
  lua_Alloc f;
  lua_lock(L);
  if (ud) *ud = G(L)->ud;
  f = G(L)->frealloc;
  lua_unlock(L);
  return f;
}
References G, lua_lock, and lua_unlock.
lua_getctx()
LUA_API int lua_getctx (lua_State * L, int * ctx)
Definition at line 880 of file lua-5.2.4/src/lapi.c.
{
  if (L->ci->callstatus & CIST_YIELDED) {
    if (ctx) *ctx = L->ci->u.c.ctx;
    return L->ci->u.c.status;
  }
  else return LUA_OK;
}
References CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_YIELDED, CallInfo::ctx, LUA_OK, CallInfo::status, and CallInfo::u.
Referenced by pcallcont().
lua_getfield()
LUA_API void lua_getfield (lua_State * L, int idx, const char * k)
Definition at line 628 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  setsvalue2s(L, L->top, luaS_new(L, k));
  api_incr_top(L);
  luaV_gettable(L, t, L->top - 1, L->top - 1);
  lua_unlock(L);
}
References api_incr_top, index2addr(), lua_lock, lua_unlock, luaS_new, luaV_gettable, setsvalue2s, and lua_State::top.
lua_getglobal()
LUA_API void lua_getglobal (lua_State * L, const char * var)
Definition at line 608 of file lua-5.2.4/src/lapi.c.
{
  Table *reg = hvalue(&G(L)->l_registry);
  const TValue *gt;  /* global table */
  lua_lock(L);
  gt = luaH_getint(reg, LUA_RIDX_GLOBALS);
  setsvalue2s(L, L->top++, luaS_new(L, var));
  luaV_gettable(L, gt, L->top - 1, L->top - 1);
  lua_unlock(L);
}
References G, gt, hvalue, lua_lock, LUA_RIDX_GLOBALS, lua_unlock, luaH_getint(), luaS_new, luaV_gettable, setsvalue2s, and lua_State::top.
lua_getmetatable()
LUA_API int lua_getmetatable (lua_State * L, int objindex)
Definition at line 686 of file lua-5.2.4/src/lapi.c.
{
  const TValue *obj;
  Table *mt = NULL;
  int res;
  lua_lock(L);
  obj = index2addr(L, objindex);
  switch (ttypenv(obj)) {
    case LUA_TTABLE:
      mt = hvalue(obj)->metatable;
      break;
    case LUA_TUSERDATA:
      mt = uvalue(obj)->metatable;
      break;
    default:
      mt = G(L)->mt[ttypenv(obj)];
      break;
  }
  if (mt == NULL)
    res = 0;
  else {
    sethvalue(L, L->top, mt);
    api_incr_top(L);
    res = 1;
  }
  lua_unlock(L);
  return res;
}
References api_incr_top, G, hvalue, index2addr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, Table::metatable, NULL, sethvalue, lua_State::top, ttypenv, and uvalue.
lua_gettable()
LUA_API void lua_gettable (lua_State * L, int idx)
Definition at line 619 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  luaV_gettable(L, t, L->top - 1, L->top - 1);
  lua_unlock(L);
}
References index2addr(), lua_lock, lua_unlock, luaV_gettable, and lua_State::top.
lua_gettop()
LUA_API int lua_gettop (lua_State * L)
Definition at line 160 of file lua-5.2.4/src/lapi.c.
{
  return cast_int(L->top - (L->ci->func + 1));
}
References cast_int, lua_State::ci, CallInfo::func, and lua_State::top.
lua_getupvalue()
LUA_API const char * lua_getupvalue (lua_State * L, int funcindex, int n)
Definition at line 1213 of file lua-5.2.4/src/lapi.c.
{
  const char *name;
  TValue *val = NULL;  /* to avoid warnings */
  lua_lock(L);
  name = aux_upvalue(index2addr(L, funcindex), n, &val, NULL);
  if (name) {
    setobj2s(L, L->top, val);
    api_incr_top(L);
  }
  lua_unlock(L);
  return name;
}
References api_incr_top, aux_upvalue(), index2addr(), lua_lock, lua_unlock, name, NULL, setobj2s, and lua_State::top.
lua_getuservalue()
LUA_API void lua_getuservalue (lua_State * L, int idx)
Definition at line 715 of file lua-5.2.4/src/lapi.c.
{
  StkId o;
  lua_lock(L);
  o = index2addr(L, idx);
  api_check(L, ttisuserdata(o), "userdata expected");
  if (uvalue(o)->env) {
    sethvalue(L, L->top, uvalue(o)->env);
  } else
    setnilvalue(L->top);
  api_incr_top(L);
  lua_unlock(L);
}
References api_check, api_incr_top, index2addr(), lua_lock, lua_unlock, sethvalue, setnilvalue, lua_State::top, ttisuserdata, and uvalue.
lua_insert()
LUA_API void lua_insert (lua_State * L, int idx)
Definition at line 193 of file lua-5.2.4/src/lapi.c.
{
  StkId p;
  StkId q;
  lua_lock(L);
  p = index2addr(L, idx);
  api_checkstackindex(L, idx, p);
  for (q = L->top; q > p; q--)  /* use L->top as a temporary */
    setobjs2s(L, q, q - 1);
  setobjs2s(L, p, L->top);
  lua_unlock(L);
}
References api_checkstackindex, index2addr(), lua_lock, lua_unlock, setobjs2s, and lua_State::top.
lua_iscfunction()
LUA_API int lua_iscfunction (lua_State * L, int idx)
Definition at line 261 of file lua-5.2.4/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  return (ttislcf(o) || (ttisCclosure(o)));
}
References index2addr(), ttisCclosure, and ttislcf.
lua_isnumber()
LUA_API int lua_isnumber (lua_State * L, int idx)
Definition at line 267 of file lua-5.2.4/src/lapi.c.
{
  TValue n;
  const TValue *o = index2addr(L, idx);
  return tonumber(o, &n);
}
References index2addr(), and tonumber.
lua_isstring()
LUA_API int lua_isstring (lua_State * L, int idx)
Definition at line 274 of file lua-5.2.4/src/lapi.c.
{
  int t = lua_type(L, idx);
  return (t == LUA_TSTRING || t == LUA_TNUMBER);
}
References LUA_TNUMBER, LUA_TSTRING, and lua_type().
lua_isuserdata()
LUA_API int lua_isuserdata (lua_State * L, int idx)
Definition at line 280 of file lua-5.2.4/src/lapi.c.
{
  const TValue *o = index2addr(L, idx);
  return (ttisuserdata(o) || ttislightuserdata(o));
}
References index2addr(), ttislightuserdata, and ttisuserdata.
lua_len()
LUA_API void lua_len (lua_State * L, int idx)
Definition at line 1147 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  luaV_objlen(L, L->top, t);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, index2addr(), lua_lock, lua_unlock, luaV_objlen(), and lua_State::top.
Referenced by luaL_len().
lua_load()
LUA_API int lua_load (lua_State * L, lua_Reader reader, void * data, const char * chunkname, const char * mode)
Definition at line 973 of file lua-5.2.4/src/lapi.c.
{
  ZIO z;
  int status;
  lua_lock(L);
  if (!chunkname) chunkname = "?";
  luaZ_init(L, &z, reader, data);
  status = luaD_protectedparser(L, &z, chunkname, mode);
  if (status == LUA_OK) {  /* no errors? */
    LClosure *f = clLvalue(L->top - 1);  /* get newly created function */
    if (f->nupvalues == 1) {  /* does it have one upvalue? */
      /* get global table from registry */
      Table *reg = hvalue(&G(L)->l_registry);
      const TValue *gt = luaH_getint(reg, LUA_RIDX_GLOBALS);
      /* set global table as 1st upvalue of 'f' (may be LUA_ENV) */
      setobj(L, f->upvals[0]->v, gt);
      luaC_barrier(L, f->upvals[0], gt);
    }
  }
  lua_unlock(L);
  return status;
}
References clLvalue, G, gt, hvalue, lua_lock, LUA_OK, LUA_RIDX_GLOBALS, lua_unlock, luaC_barrier, luaD_protectedparser(), luaH_getint(), luaZ_init(), reader(), setobj, lua_State::top, LClosure::upvals, and UpVal::v.
lua_newuserdata()
LUA_API void * lua_newuserdata (lua_State * L, size_t size)
Definition at line 1175 of file lua-5.2.4/src/lapi.c.
{
  Udata *u;
  lua_lock(L);
  luaC_checkGC(L);
  u = luaS_newudata(L, size, NULL);
  setuvalue(L, L->top, u);
  api_incr_top(L);
  lua_unlock(L);
  return u + 1;
}
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaS_newudata(), NULL, setuvalue, and lua_State::top.
lua_next()
LUA_API int lua_next (lua_State * L, int idx)
Definition at line 1114 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  int more;
  lua_lock(L);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  more = luaH_next(L, hvalue(t), L->top - 1);
  if (more) {
    api_incr_top(L);
  }
  else  /* no more elements */
    L->top -= 1;  /* remove key */
  lua_unlock(L);
  return more;
}
References api_check, api_incr_top, hvalue, index2addr(), lua_lock, lua_unlock, luaH_next(), lua_State::top, and ttistable.
lua_pcallk()
LUA_API int lua_pcallk (lua_State * L, int nargs, int nresults, int errfunc, int ctx, lua_CFunction k)
Definition at line 928 of file lua-5.2.4/src/lapi.c.
{
  struct CallS c;
  int status;
  ptrdiff_t func;
  lua_lock(L);
  api_check(L, k == NULL || !isLua(L->ci),
    "cannot use continuations inside hooks");
  api_checknelems(L, nargs+1);
  api_check(L, L->status == LUA_OK, "cannot do calls on non-normal thread");
  checkresults(L, nargs, nresults);
  if (errfunc == 0)
    func = 0;
  else {
    StkId o = index2addr(L, errfunc);
    api_checkstackindex(L, errfunc, o);
    func = savestack(L, o);
  }
  c.func = L->top - (nargs+1);  /* function to be called */
  if (k == NULL || L->nny > 0) {  /* no continuation or no yieldable? */
    c.nresults = nresults;  /* do a 'conventional' protected call */
    status = luaD_pcall(L, f_call, &c, savestack(L, c.func), func);
  }
  else {  /* prepare continuation (call is already protected by 'resume') */
    CallInfo *ci = L->ci;
    ci->u.c.k = k;  /* save continuation */
    ci->u.c.ctx = ctx;  /* save context */
    /* save information for error recovery */
    ci->extra = savestack(L, c.func);
    ci->u.c.old_allowhook = L->allowhook;
    ci->u.c.old_errfunc = L->errfunc;
    L->errfunc = func;
    /* mark that function may do error recovery */
    ci->callstatus |= CIST_YPCALL;
    luaD_call(L, c.func, nresults, 1);  /* do the call */
    ci->callstatus &= ~CIST_YPCALL;
    L->errfunc = ci->u.c.old_errfunc;
    status = LUA_OK;  /* if it is here, there were no errors */
  }
  adjustresults(L, nresults);
  lua_unlock(L);
  return status;
}
References adjustresults, lua_State::allowhook, api_check, api_checknelems, api_checkstackindex, CallInfo::c, CallInfo::callstatus, checkresults, lua_State::ci, CIST_YPCALL, CallInfo::ctx, lua_State::errfunc, CallInfo::extra, f_call(), CallS::func, index2addr(), isLua, CallInfo::k, lua_lock, LUA_OK, lua_unlock, luaD_call(), luaD_pcall(), lua_State::nny, CallS::nresults, NULL, CallInfo::old_allowhook, CallInfo::old_errfunc, savestack, lua_State::status, lua_State::top, and CallInfo::u.
Referenced by luaB_pcall(), luaB_pcall(), luaB_pcall(), luaB_xpcall(), luaB_xpcall(), and luaB_xpcall().
lua_pushboolean()
LUA_API void lua_pushboolean (lua_State * L, int b)
Definition at line 577 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  setbvalue(L->top, (b != 0));  /* ensure that true is 1 */
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setbvalue, and lua_State::top.
lua_pushcclosure()
LUA_API void lua_pushcclosure (lua_State * L, lua_CFunction fn, int n)
Definition at line 555 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  if (n == 0) {
    setfvalue(L->top, fn);
  }
  else {
    Closure *cl;
    api_checknelems(L, n);
    api_check(L, n <= MAXUPVAL, "upvalue index too large");
    luaC_checkGC(L);
    cl = luaF_newCclosure(L, n);
    cl->c.f = fn;
    L->top -= n;
    while (n--)
      setobj2n(L, &cl->c.upvalue[n], L->top + n);
    setclCvalue(L, L->top, cl);
  }
  api_incr_top(L);
  lua_unlock(L);
}
References api_check, api_checknelems, api_incr_top, Closure::c, CClosure::f, lua_lock, lua_unlock, luaC_checkGC, luaF_newCclosure(), MAXUPVAL, setclCvalue, setfvalue, setobj2n, lua_State::top, and CClosure::upvalue.
lua_pushfstring()
LUA_API const char * lua_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 542 of file lua-5.2.4/src/lapi.c.
{
  const char *ret;
  va_list argp;
  lua_lock(L);
  luaC_checkGC(L);
  va_start(argp, fmt);
  ret = luaO_pushvfstring(L, fmt, argp);
  va_end(argp);
  lua_unlock(L);
  return ret;
}
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
lua_pushinteger()
LUA_API void lua_pushinteger (lua_State * L, lua_Integer n)
Definition at line 483 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  setnvalue(L->top, cast_num(n));
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, cast_num, lua_lock, lua_unlock, setnvalue, and lua_State::top.
lua_pushlightuserdata()
LUA_API void lua_pushlightuserdata (lua_State * L, void * p)
Definition at line 585 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  setpvalue(L->top, p);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setpvalue, and lua_State::top.
lua_pushlstring()
LUA_API const char * lua_pushlstring (lua_State * L, const char * s, size_t len)
Definition at line 501 of file lua-5.2.4/src/lapi.c.
{
  TString *ts;
  lua_lock(L);
  luaC_checkGC(L);
  ts = luaS_newlstr(L, s, len);
  setsvalue2s(L, L->top, ts);
  api_incr_top(L);
  lua_unlock(L);
  return getstr(ts);
}
References api_incr_top, getstr, lua_lock, lua_unlock, luaC_checkGC, luaS_newlstr(), s, setsvalue2s, and lua_State::top.
lua_pushnil()
LUA_API void lua_pushnil (lua_State * L)
Definition at line 465 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  setnilvalue(L->top);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
Referenced by lua_pushstring().
lua_pushnumber()
LUA_API void lua_pushnumber (lua_State * L, lua_Number n)
Definition at line 473 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  setnvalue(L->top, n);
  luai_checknum(L, L->top,
    luaG_runerror(L, "C API - attempt to push a signaling NaN"));
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, luaG_runerror(), luai_checknum, setnvalue, and lua_State::top.
lua_pushstring()
LUA_API const char * lua_pushstring (lua_State * L, const char * s)
Definition at line 513 of file lua-5.2.4/src/lapi.c.
{
  if (s == NULL) {
    lua_pushnil(L);
    return NULL;
  }
  else {
    TString *ts;
    lua_lock(L);
    luaC_checkGC(L);
    ts = luaS_new(L, s);
    setsvalue2s(L, L->top, ts);
    api_incr_top(L);
    lua_unlock(L);
    return getstr(ts);
  }
}
References api_incr_top, getstr, lua_lock, lua_pushnil(), lua_unlock, luaC_checkGC, luaS_new, NULL, s, setsvalue2s, and lua_State::top.
lua_pushthread()
LUA_API int lua_pushthread (lua_State * L)
Definition at line 593 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  setthvalue(L, L->top, L);
  api_incr_top(L);
  lua_unlock(L);
  return (G(L)->mainthread == L);
}
References api_incr_top, G, lua_lock, lua_unlock, setthvalue, and lua_State::top.
lua_pushunsigned()
LUA_API void lua_pushunsigned (lua_State * L, lua_Unsigned u)
Definition at line 491 of file lua-5.2.4/src/lapi.c.
{
  lua_Number n;
  lua_lock(L);
  n = lua_unsigned2number(u);
  setnvalue(L->top, n);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, lua_unsigned2number, setnvalue, and lua_State::top.
Referenced by b_and(), b_arshift(), b_extract(), b_not(), b_or(), b_replace(), b_rot(), b_shift(), and b_xor().
lua_pushvalue()
LUA_API void lua_pushvalue (lua_State * L, int idx)
Definition at line 235 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  setobj2s(L, L->top, index2addr(L, idx));
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, index2addr(), lua_lock, lua_unlock, setobj2s, and lua_State::top.
lua_pushvfstring()
LUA_API const char * lua_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 531 of file lua-5.2.4/src/lapi.c.
{
  const char *ret;
  lua_lock(L);
  luaC_checkGC(L);
  ret = luaO_pushvfstring(L, fmt, argp);
  lua_unlock(L);
  return ret;
}
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
lua_rawequal()
LUA_API int lua_rawequal (lua_State * L, int index1, int index2)
Definition at line 286 of file lua-5.2.4/src/lapi.c.
{
  StkId o1 = index2addr(L, index1);
  StkId o2 = index2addr(L, index2);
  return (isvalid(o1) && isvalid(o2)) ? luaV_rawequalobj(o1, o2) : 0;
}
References index2addr(), isvalid, and luaV_rawequalobj.
lua_rawget()
LUA_API void lua_rawget (lua_State * L, int idx)
Definition at line 639 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  setobj2s(L, L->top - 1, luaH_get(hvalue(t), L->top - 1));
  lua_unlock(L);
}
References api_check, hvalue, index2addr(), lua_lock, lua_unlock, luaH_get(), setobj2s, lua_State::top, and ttistable.
lua_rawgeti()
LUA_API void lua_rawgeti (lua_State * L, int idx, int n)
Definition at line 649 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  setobj2s(L, L->top, luaH_getint(hvalue(t), n));
  api_incr_top(L);
  lua_unlock(L);
}
References api_check, api_incr_top, hvalue, index2addr(), lua_lock, lua_unlock, luaH_getint(), setobj2s, lua_State::top, and ttistable.
lua_rawgetp()
LUA_API void lua_rawgetp (lua_State * L, int idx, const void * p)
Definition at line 660 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  TValue k;
  lua_lock(L);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  setpvalue(&k, cast(void *, p));
  setobj2s(L, L->top, luaH_get(hvalue(t), &k));
  api_incr_top(L);
  lua_unlock(L);
}
References api_check, api_incr_top, cast, hvalue, index2addr(), lua_lock, lua_unlock, luaH_get(), setobj2s, setpvalue, lua_State::top, and ttistable.
Referenced by addtoclib(), checkclib(), db_gethook(), db_sethook(), and hookf().
lua_rawlen()
LUA_API size_t lua_rawlen (lua_State * L, int idx)
Definition at line 407 of file lua-5.2.4/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  switch (ttypenv(o)) {
    case LUA_TSTRING: return tsvalue(o)->len;
    case LUA_TUSERDATA: return uvalue(o)->len;
    case LUA_TTABLE: return luaH_getn(hvalue(o));
    default: return 0;
  }
}
References hvalue, index2addr(), LUA_TSTRING, LUA_TTABLE, LUA_TUSERDATA, luaH_getn(), tsvalue, ttypenv, and uvalue.
lua_rawset()
LUA_API void lua_rawset (lua_State * L, int idx)
Definition at line 770 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  api_checknelems(L, 2);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  setobj2t(L, luaH_set(L, hvalue(t), L->top-2), L->top-1);
  invalidateTMcache(hvalue(t));
  luaC_barrierback(L, gcvalue(t), L->top-1);
  L->top -= 2;
  lua_unlock(L);
}
References api_check, api_checknelems, gcvalue, hvalue, index2addr(), invalidateTMcache, lua_lock, lua_unlock, luaC_barrierback, luaH_set(), setobj2t, lua_State::top, and ttistable.
lua_rawseti()
LUA_API void lua_rawseti (lua_State * L, int idx, int n)
Definition at line 784 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  api_checknelems(L, 1);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  luaH_setint(L, hvalue(t), n, L->top - 1);
  luaC_barrierback(L, gcvalue(t), L->top-1);
  L->top--;
  lua_unlock(L);
}
References api_check, api_checknelems, gcvalue, hvalue, index2addr(), lua_lock, lua_unlock, luaC_barrierback, luaH_setint(), lua_State::top, and ttistable.
lua_rawsetp()
LUA_API void lua_rawsetp (lua_State * L, int idx, const void * p)
Definition at line 797 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  TValue k;
  lua_lock(L);
  api_checknelems(L, 1);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  setpvalue(&k, cast(void *, p));
  setobj2t(L, luaH_set(L, hvalue(t), &k), L->top - 1);
  luaC_barrierback(L, gcvalue(t), L->top - 1);
  L->top--;
  lua_unlock(L);
}
References api_check, api_checknelems, cast, gcvalue, hvalue, index2addr(), lua_lock, lua_unlock, luaC_barrierback, luaH_set(), setobj2t, setpvalue, lua_State::top, and ttistable.
Referenced by createclibstable(), and db_sethook().
lua_remove()
LUA_API void lua_remove (lua_State * L, int idx)
Definition at line 182 of file lua-5.2.4/src/lapi.c.
{
  StkId p;
  lua_lock(L);
  p = index2addr(L, idx);
  api_checkstackindex(L, idx, p);
  while (++p < L->top) setobjs2s(L, p-1, p);
  L->top--;
  lua_unlock(L);
}
References api_checkstackindex, index2addr(), lua_lock, lua_unlock, setobjs2s, and lua_State::top.
lua_replace()
LUA_API void lua_replace (lua_State * L, int idx)
Definition at line 217 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  api_checknelems(L, 1);
  moveto(L, L->top - 1, idx);
  L->top--;
  lua_unlock(L);
}
References api_checknelems, lua_lock, lua_unlock, moveto(), and lua_State::top.
lua_setallocf()
LUA_API void lua_setallocf (lua_State * L, lua_Alloc f, void * ud)
Definition at line 1167 of file lua-5.2.4/src/lapi.c.
{
  lua_lock(L);
  G(L)->ud = ud;
  G(L)->frealloc = f;
  lua_unlock(L);
}
References G, lua_lock, and lua_unlock.
lua_setfield()
LUA_API void lua_setfield (lua_State * L, int idx, const char * k)
Definition at line 758 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  api_checknelems(L, 1);
  t = index2addr(L, idx);
  setsvalue2s(L, L->top++, luaS_new(L, k));
  luaV_settable(L, t, L->top - 1, L->top - 2);
  L->top -= 2;  /* pop value and key */
  lua_unlock(L);
}
References api_checknelems, index2addr(), lua_lock, lua_unlock, luaS_new, luaV_settable, setsvalue2s, and lua_State::top.
lua_setglobal()
LUA_API void lua_setglobal (lua_State * L, const char * var)
Definition at line 734 of file lua-5.2.4/src/lapi.c.
{
  Table *reg = hvalue(&G(L)->l_registry);
  const TValue *gt;  /* global table */
  lua_lock(L);
  api_checknelems(L, 1);
  gt = luaH_getint(reg, LUA_RIDX_GLOBALS);
  setsvalue2s(L, L->top++, luaS_new(L, var));
  luaV_settable(L, gt, L->top - 1, L->top - 2);
  L->top -= 2;  /* pop value and key */
  lua_unlock(L);
}
References api_checknelems, G, gt, hvalue, lua_lock, LUA_RIDX_GLOBALS, lua_unlock, luaH_getint(), luaS_new, luaV_settable, setsvalue2s, and lua_State::top.
lua_setmetatable()
LUA_API int lua_setmetatable (lua_State * L, int objindex)
Definition at line 812 of file lua-5.2.4/src/lapi.c.
{
  TValue *obj;
  Table *mt;
  lua_lock(L);
  api_checknelems(L, 1);
  obj = index2addr(L, objindex);
  if (ttisnil(L->top - 1))
    mt = NULL;
  else {
    api_check(L, ttistable(L->top - 1), "table expected");
    mt = hvalue(L->top - 1);
  }
  switch (ttypenv(obj)) {
    case LUA_TTABLE: {
      hvalue(obj)->metatable = mt;
      if (mt) {
        luaC_objbarrierback(L, gcvalue(obj), mt);
        luaC_checkfinalizer(L, gcvalue(obj), mt);
      }
      break;
    }
    case LUA_TUSERDATA: {
      uvalue(obj)->metatable = mt;
      if (mt) {
        luaC_objbarrier(L, rawuvalue(obj), mt);
        luaC_checkfinalizer(L, gcvalue(obj), mt);
      }
      break;
    }
    default: {
      G(L)->mt[ttypenv(obj)] = mt;
      break;
    }
  }
  L->top--;
  lua_unlock(L);
  return 1;
}
References api_check, api_checknelems, G, gcvalue, hvalue, index2addr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, luaC_checkfinalizer(), luaC_objbarrier, luaC_objbarrierback, NULL, rawuvalue, lua_State::top, ttisnil, ttistable, ttypenv, and uvalue.
lua_settable()
LUA_API void lua_settable (lua_State * L, int idx)
Definition at line 747 of file lua-5.2.4/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  api_checknelems(L, 2);
  t = index2addr(L, idx);
  luaV_settable(L, t, L->top - 2, L->top - 1);
  L->top -= 2;  /* pop index and value */
  lua_unlock(L);
}
References api_checknelems, index2addr(), lua_lock, lua_unlock, luaV_settable, and lua_State::top.
lua_settop()
LUA_API void lua_settop (lua_State * L, int idx)
Definition at line 165 of file lua-5.2.4/src/lapi.c.
{
  StkId func = L->ci->func;
  lua_lock(L);
  if (idx >= 0) {
    api_check(L, idx <= L->stack_last - (func + 1), "new top too large");
    while (L->top < (func + 1) + idx)
      setnilvalue(L->top++);
    L->top = (func + 1) + idx;
  }
  else {
    api_check(L, -(idx+1) <= (L->top - (func + 1)), "invalid new top");
    L->top += idx+1;  /* `subtract' index (index is negative) */
  }
  lua_unlock(L);
}
References api_check, lua_State::ci, CallInfo::func, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
lua_setupvalue()
LUA_API const char * lua_setupvalue (lua_State * L, int funcindex, int n)
Definition at line 1227 of file lua-5.2.4/src/lapi.c.
{
  const char *name;
  TValue *val = NULL;  /* to avoid warnings */
  GCObject *owner = NULL;  /* to avoid warnings */
  StkId fi;
  lua_lock(L);
  fi = index2addr(L, funcindex);
  api_checknelems(L, 1);
  name = aux_upvalue(fi, n, &val, &owner);
  if (name) {
    L->top--;
    setobj(L, val, L->top);
    luaC_barrier(L, owner, L->top);
  }
  lua_unlock(L);
  return name;
}
References api_checknelems, aux_upvalue(), index2addr(), lua_lock, lua_unlock, luaC_barrier, name, NULL, owner, setobj, and lua_State::top.
lua_setuservalue()
LUA_API void lua_setuservalue (lua_State * L, int idx)
Definition at line 852 of file lua-5.2.4/src/lapi.c.
{
  StkId o;
  lua_lock(L);
  api_checknelems(L, 1);
  o = index2addr(L, idx);
  api_check(L, ttisuserdata(o), "userdata expected");
  if (ttisnil(L->top - 1))
    uvalue(o)->env = NULL;
  else {
    api_check(L, ttistable(L->top - 1), "table expected");
    uvalue(o)->env = hvalue(L->top - 1);
    luaC_objbarrier(L, gcvalue(o), hvalue(L->top - 1));
  }
  L->top--;
  lua_unlock(L);
}
References api_check, api_checknelems, gcvalue, hvalue, index2addr(), lua_lock, lua_unlock, luaC_objbarrier, NULL, lua_State::top, ttisnil, ttistable, ttisuserdata, and uvalue.
lua_status()
LUA_API int lua_status (lua_State * L)
Definition at line 1012 of file lua-5.2.4/src/lapi.c.
{
  return L->status;
}
References lua_State::status.
lua_toboolean()
LUA_API int lua_toboolean (lua_State * L, int idx)
Definition at line 383 of file lua-5.2.4/src/lapi.c.
{
  const TValue *o = index2addr(L, idx);
  return !l_isfalse(o);
}
References index2addr(), and l_isfalse.
lua_tocfunction()
LUA_API lua_CFunction lua_tocfunction (lua_State * L, int idx)
Definition at line 418 of file lua-5.2.4/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  if (ttislcf(o)) return fvalue(o);
  else if (ttisCclosure(o))
    return clCvalue(o)->f;
  else return NULL;  /* not a C function */
}
References clCvalue, fvalue, index2addr(), NULL, ttisCclosure, and ttislcf.
lua_tointegerx()
LUA_API lua_Integer lua_tointegerx (lua_State * L, int idx, int * isnum)
Definition at line 349 of file lua-5.2.4/src/lapi.c.
{
  TValue n;
  const TValue *o = index2addr(L, idx);
  if (tonumber(o, &n)) {
    lua_Integer res;
    lua_Number num = nvalue(o);
    lua_number2integer(res, num);
    if (isnum) *isnum = 1;
    return res;
  }
  else {
    if (isnum) *isnum = 0;
    return 0;
  }
}
References index2addr(), lua_number2integer, nvalue, and tonumber.
Referenced by getfield(), getfield(), getfield(), luaL_checkinteger(), luaL_checkinteger(), luaL_len(), math_toint(), and math_toint().
lua_tolstring()
LUA_API const char * lua_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 389 of file lua-5.2.4/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  if (!ttisstring(o)) {
    lua_lock(L);  /* `luaV_tostring' may create a new string */
    if (!luaV_tostring(L, o)) {  /* conversion failed? */
      if (len != NULL) *len = 0;
      lua_unlock(L);
      return NULL;
    }
    luaC_checkGC(L);
    o = index2addr(L, idx);  /* previous call may reallocate the stack */
    lua_unlock(L);
  }
  if (len != NULL) *len = tsvalue(o)->len;
  return svalue(o);
}
References index2addr(), lua_lock, lua_unlock, luaC_checkGC, luaV_tostring(), NULL, svalue, tsvalue, and ttisstring.
lua_tonumberx()
LUA_API lua_Number lua_tonumberx (lua_State * L, int idx, int * isnum)
Definition at line 335 of file lua-5.2.4/src/lapi.c.
{
  TValue n;
  const TValue *o = index2addr(L, idx);
  if (tonumber(o, &n)) {
    if (isnum) *isnum = 1;
    return nvalue(o);
  }
  else {
    if (isnum) *isnum = 0;
    return 0;
  }
}
References index2addr(), nvalue, and tonumber.
Referenced by luaB_tonumber(), luaL_checknumber(), and luaL_checknumber().
lua_topointer()
LUA_API const void * lua_topointer (lua_State * L, int idx)
Definition at line 443 of file lua-5.2.4/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  switch (ttype(o)) {
    case LUA_TTABLE: return hvalue(o);
    case LUA_TLCL: return clLvalue(o);
    case LUA_TCCL: return clCvalue(o);
    case LUA_TLCF: return cast(void *, cast(size_t, fvalue(o)));
    case LUA_TTHREAD: return thvalue(o);
    case LUA_TUSERDATA:
    case LUA_TLIGHTUSERDATA:
      return lua_touserdata(L, idx);
    default: return NULL;
  }
}
References cast, clCvalue, clLvalue, fvalue, hvalue, index2addr(), LUA_TCCL, LUA_TLCF, LUA_TLCL, LUA_TLIGHTUSERDATA, lua_touserdata(), LUA_TTABLE, LUA_TTHREAD, LUA_TUSERDATA, NULL, thvalue, and ttype.
lua_tothread()
LUA_API lua_State * lua_tothread (lua_State * L, int idx)
Definition at line 437 of file lua-5.2.4/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  return (!ttisthread(o)) ? NULL : thvalue(o);
}
References index2addr(), NULL, thvalue, and ttisthread.
lua_tounsignedx()
LUA_API lua_Unsigned lua_tounsignedx (lua_State * L, int idx, int * isnum)
Definition at line 366 of file lua-5.2.4/src/lapi.c.
{
  TValue n;
  const TValue *o = index2addr(L, idx);
  if (tonumber(o, &n)) {
    lua_Unsigned res;
    lua_Number num = nvalue(o);
    lua_number2unsigned(res, num);
    if (isnum) *isnum = 1;
    return res;
  }
  else {
    if (isnum) *isnum = 0;
    return 0;
  }
}
References index2addr(), lua_number2unsigned, nvalue, and tonumber.
Referenced by luaL_checkunsigned().
lua_touserdata()
LUA_API void * lua_touserdata (lua_State * L, int idx)
Definition at line 427 of file lua-5.2.4/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  switch (ttypenv(o)) {
    case LUA_TUSERDATA: return (rawuvalue(o) + 1);
    case LUA_TLIGHTUSERDATA: return pvalue(o);
    default: return NULL;
  }
}
References index2addr(), LUA_TLIGHTUSERDATA, LUA_TUSERDATA, NULL, pvalue, rawuvalue, and ttypenv.
Referenced by lua_topointer().
lua_type()
LUA_API int lua_type (lua_State * L, int idx)
Definition at line 249 of file lua-5.2.4/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  return (isvalid(o) ? ttypenv(o) : LUA_TNONE);
}
References index2addr(), isvalid, LUA_TNONE, and ttypenv.
Referenced by lua_isstring().
lua_typename()
LUA_API const char * lua_typename (lua_State * L, int t)
Definition at line 255 of file lua-5.2.4/src/lapi.c.
{
  UNUSED(L);
  return ttypename(t);
}
References ttypename, and UNUSED.
lua_upvalueid()
LUA_API void * lua_upvalueid (lua_State * L, int fidx, int n)
Definition at line 1257 of file lua-5.2.4/src/lapi.c.
{
  StkId fi = index2addr(L, fidx);
  switch (ttype(fi)) {
    case LUA_TLCL: {  /* lua closure */
      return *getupvalref(L, fidx, n, NULL);
    }
    case LUA_TCCL: {  /* C closure */
      CClosure *f = clCvalue(fi);
      api_check(L, 1 <= n && n <= f->nupvalues, "invalid upvalue index");
      return &f->upvalue[n - 1];
    }
    default: {
      api_check(L, 0, "closure expected");
      return NULL;
    }
  }
}
References api_check, clCvalue, getupvalref(), index2addr(), LUA_TCCL, LUA_TLCL, NULL, ttype, and CClosure::upvalue.
Referenced by checkupval(), db_upvalueid(), and db_upvalueid().
lua_upvaluejoin()
LUA_API void lua_upvaluejoin (lua_State * L, int fidx1, int n1, int fidx2, int n2)
Definition at line 1276 of file lua-5.2.4/src/lapi.c.
{
  LClosure *f1;
  UpVal **up1 = getupvalref(L, fidx1, n1, &f1);
  UpVal **up2 = getupvalref(L, fidx2, n2, NULL);
  *up1 = *up2;
  luaC_objbarrier(L, f1, *up2);
}
References getupvalref(), luaC_objbarrier, and NULL.
Referenced by db_upvaluejoin(), db_upvaluejoin(), and db_upvaluejoin().
lua_version()
LUA_API const lua_Number * lua_version (lua_State * L)
Definition at line 137 of file lua-5.2.4/src/lapi.c.
{
  static const lua_Number version = LUA_VERSION_NUM;
  if (L == NULL) return &version;
  else return G(L)->version;
}
References G, LUA_VERSION_NUM, and NULL.
Referenced by f_luaopen(), f_luaopen(), luaL_checkversion_(), and luaL_checkversion_().
lua_xmove()
LUA_API void lua_xmove (lua_State * from, lua_State * to, int n)
Definition at line 112 of file lua-5.2.4/src/lapi.c.
{
  int i;
  if (from == to) return;
  lua_lock(to);
  api_checknelems(from, n);
  api_check(from, G(from) == G(to), "moving among independent states");
  api_check(from, to->ci->top - to->top >= n, "not enough elements to move");
  from->top -= n;
  for (i = 0; i < n; i++) {
    setobj2s(to, to->top++, from->top + i);
  }
  lua_unlock(to);
}
References api_check, api_checknelems, lua_State::ci, G, lua_lock, lua_unlock, setobj2s, CallInfo::top, and lua_State::top.
moveto()
static void moveto (lua_State * L, TValue * fr, int idx) static
Definition at line 206 of file lua-5.2.4/src/lapi.c.
{
  TValue *to = index2addr(L, idx);
  api_checkvalidindex(L, to);
  setobj(L, to, fr);
  if (idx < LUA_REGISTRYINDEX)  /* function upvalue? */
    luaC_barrier(L, clCvalue(L->ci->func), fr);
  /* LUA_REGISTRYINDEX does not need gc barrier
     (collector revisits it before finishing collection) */
}
References api_checkvalidindex, lua_State::ci, clCvalue, CallInfo::func, index2addr(), LUA_REGISTRYINDEX, luaC_barrier, and setobj.
Referenced by lua_copy(), and lua_replace().
Variable Documentation
lua_ident
const char lua_ident[]
Initial value:
=
  "$LuaVersion: " LUA_COPYRIGHT " $"
  "$LuaAuthors: " LUA_AUTHORS " $"
Definition at line 32 of file lua-5.2.4/src/lapi.c.