Github User Fetcher: ltm.c File Reference
ltm.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lvm.h"
Macros
#define ltm_c
#define LUA_CORE
Functions
void luaT_init (lua_State *L)
const TValue * luaT_gettm (Table *events, TMS event, TString *ename)
const TValue * luaT_gettmbyobj (lua_State *L, const TValue *o, TMS event)
const char * luaT_objtypename (lua_State *L, const TValue *o)
void luaT_callTM (lua_State *L, const TValue *f, const TValue *p1, const TValue *p2, TValue *p3, int hasres)
int luaT_callbinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
void luaT_trybinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
int luaT_callorderTM (lua_State *L, const TValue *p1, const TValue *p2, TMS event)
Variables
static const char udatatypename [] = "userdata"
LUAI_DDEF const char *const luaT_typenames_ [LUA_TOTALTAGS]
Macro Definition Documentation
ltm_c
#define ltm_c
Definition at line 7 of file lua-5.3.6/src/ltm.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/ltm.c.
Function Documentation
luaT_callbinTM()
int luaT_callbinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 124 of file lua-5.3.6/src/ltm.c.
{
  const TValue *tm = luaT_gettmbyobj(L, p1, event);  /* try first operand */
  if (ttisnil(tm))
    tm = luaT_gettmbyobj(L, p2, event);  /* try second operand */
  if (ttisnil(tm)) return 0;
  luaT_callTM(L, tm, p1, p2, res, 1);
  return 1;
}
References luaT_callTM(), luaT_gettmbyobj(), and ttisnil.
Referenced by luaT_callorderTM(), and luaT_trybinTM().
luaT_callorderTM()
int luaT_callorderTM (lua_State * L, const TValue * p1, const TValue * p2, TMS event)
Definition at line 158 of file lua-5.3.6/src/ltm.c.
{
  if (!luaT_callbinTM(L, p1, p2, L->top, event))
    return -1;  /* no metamethod */
  else
    return !l_isfalse(L->top);
}
References l_isfalse, luaT_callbinTM(), and lua_State::top.
Referenced by lessequalothers(), lessthanothers(), luaV_lessequal(), and luaV_lessthan().
luaT_callTM()
void luaT_callTM (lua_State * L, const TValue * f, const TValue * p1, const TValue * p2, TValue * p3, int hasres)
Definition at line 102 of file lua-5.3.6/src/ltm.c.
{
  ptrdiff_t result = savestack(L, p3);
  StkId func = L->top;
  setobj2s(L, func, f);  /* push function (assume EXTRA_STACK) */
  setobj2s(L, func + 1, p1);  /* 1st argument */
  setobj2s(L, func + 2, p2);  /* 2nd argument */
  L->top += 3;
  if (!hasres)  /* no result? 'p3' is third argument */
    setobj2s(L, L->top++, p3);  /* 3rd argument */
  /* metamethod may yield only when called from Lua code */
  if (isLua(L->ci))
    luaD_call(L, func, hasres);
  else
    luaD_callnoyield(L, func, hasres);
  if (hasres) {  /* if has result, move it to its place */
    p3 = restorestack(L, result);
    setobjs2s(L, p3, --L->top);
  }
}
References lua_State::ci, isLua, luaD_call(), luaD_callnoyield(), restorestack, savestack, setobj2s, setobjs2s, and lua_State::top.
Referenced by luaT_callbinTM(), luaV_equalobj(), luaV_finishget(), luaV_finishset(), luaV_finishset(), and luaV_objlen().
luaT_gettm()
const TValue * luaT_gettm (Table * events, TMS event, TString * ename)
Definition at line 59 of file lua-5.3.6/src/ltm.c.
{
  const TValue *tm = luaH_getshortstr(events, ename);
  lua_assert(event <= TM_EQ);
  if (ttisnil(tm)) {  /* no tag method? */
    events->flags |= cast_byte(1u<<event);  /* cache this fact */
    return NULL;
  }
  else return tm;
}
References cast_byte, Table::flags, lua_assert, luaH_getshortstr(), NULL, TM_EQ, and ttisnil.
luaT_gettmbyobj()
const TValue * luaT_gettmbyobj (lua_State * L, const TValue * o, TMS event)
Definition at line 70 of file lua-5.3.6/src/ltm.c.
{
  Table *mt;
  switch (ttnov(o)) {
    case LUA_TTABLE:
      mt = hvalue(o)->metatable;
      break;
    case LUA_TUSERDATA:
      mt = uvalue(o)->metatable;
      break;
    default:
      mt = G(L)->mt[ttnov(o)];
  }
  return (mt ? luaH_getshortstr(mt, G(L)->tmname[event]) : luaO_nilobject);
}
References G, hvalue, LUA_TTABLE, LUA_TUSERDATA, luaH_getshortstr(), luaO_nilobject, Table::metatable, tmname, ttnov, and uvalue.
Referenced by luaT_callbinTM().
luaT_init()
void luaT_init (lua_State * L)
Definition at line 37 of file lua-5.3.6/src/ltm.c.
{
  static const char *const luaT_eventname[] = {  /* ORDER TM */
    "__index", "__newindex",
    "__gc", "__mode", "__len", "__eq",
    "__add", "__sub", "__mul", "__mod", "__pow",
    "__div", "__idiv",
    "__band", "__bor", "__bxor", "__shl", "__shr",
    "__unm", "__bnot", "__lt", "__le",
    "__concat", "__call"
  };
  int i;
  for (i=0; i<TM_N; i++) {
    G(L)->tmname[i] = luaS_new(L, luaT_eventname[i]);
    luaC_fix(L, obj2gco(G(L)->tmname[i]));  /* never collect these names */
  }
}
References G, luaC_fix(), luaS_new, obj2gco, TM_N, and tmname.
luaT_objtypename()
const char * luaT_objtypename (lua_State * L, const TValue * o)
Definition at line 90 of file lua-5.3.6/src/ltm.c.
{
  Table *mt;
  if ((ttistable(o) && (mt = hvalue(o)->metatable) != NULL) ||
      (ttisfulluserdata(o) && (mt = uvalue(o)->metatable) != NULL)) {
    const TValue *name = luaH_getshortstr(mt, luaS_new(L, "__name"));
    if (ttisstring(name))  /* is '__name' a string? */
      return getstr(tsvalue(name));  /* use it as type name */
  }
  return ttypename(ttnov(o));  /* else use standard type name */
}
References getstr, hvalue, luaH_getshortstr(), luaS_new, name, NULL, tsvalue, ttisfulluserdata, ttisstring, ttistable, ttnov, ttypename, and uvalue.
Referenced by luaG_callerror(), luaG_forerror(), luaG_ordererror(), and luaG_typeerror().
luaT_trybinTM()
void luaT_trybinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 135 of file lua-5.3.6/src/ltm.c.
{
  if (!luaT_callbinTM(L, p1, p2, res, event)) {
    switch (event) {
      case TM_CONCAT:
        luaG_concaterror(L, p1, p2);
      /* call never returns, but to avoid warnings: *//* FALLTHROUGH */
      case TM_BAND: case TM_BOR: case TM_BXOR:
      case TM_SHL: case TM_SHR: case TM_BNOT: {
        lua_Number dummy;
        if (tonumber(p1, &dummy) && tonumber(p2, &dummy))
          luaG_tointerror(L, p1, p2);
        else
          luaG_opinterror(L, p1, p2, "perform bitwise operation on");
      }
      /* calls never return, but to avoid warnings: *//* FALLTHROUGH */
      default:
        luaG_opinterror(L, p1, p2, "perform arithmetic on");
    }
  }
}
References dummy, luaG_concaterror(), luaG_opinterror(), luaG_tointerror(), luaT_callbinTM(), TM_BAND, TM_BNOT, TM_BOR, TM_BXOR, TM_CONCAT, TM_SHL, TM_SHR, and tonumber.
Referenced by luaO_arith(), luaO_arith(), luaV_concat(), luaV_execute(), and luaV_execute().
Variable Documentation
luaT_typenames_
LUAI_DDEF const char* const luaT_typenames_[LUA_TOTALTAGS]
Initial value:
= {
  "no value",
  "nil", "boolean", udatatypename, "number",
  "string", "table", "function", udatatypename, "thread",
  "proto"
}
Definition at line 29 of file lua-5.3.6/src/ltm.c.
{
  "no value",
  "nil", "boolean", udatatypename, "number",
  "string", "table", "function", udatatypename, "thread",
  "proto" /* this last case is used for tests only */
};
udatatypename
const char udatatypename[] = "userdata" static
Definition at line 27 of file lua-5.3.6/src/ltm.c.