Github User Fetcher: ltable.c File Reference
ltable.c File Reference
#include <math.h>
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "ltable.h"
Macros
#define ltable_c
#define LUA_CORE
#define MAXBITS (LUAI_BITSINT-2)
#define MAXASIZE (1 << MAXBITS)
#define hashpow2(t, n) (gnode(t, lmod((n), sizenode(t))))
#define hashstr(t, str) hashpow2(t, (str)->tsv.hash)
#define hashboolean(t, p) hashpow2(t, p)
#define hashmod(t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
#define hashpointer(t, p) hashmod(t, IntPoint(p))
#define numints cast_int(sizeof(lua_Number)/sizeof(int))
#define dummynode (&dummynode_)
Functions
static Node * hashnum (const Table *t, lua_Number n)
static Node * mainposition (const Table *t, const TValue *key)
static int arrayindex (const TValue *key)
static int findindex (lua_State *L, Table *t, StkId key)
int luaH_next (lua_State *L, Table *t, StkId key)
static int computesizes (int nums[], int *narray)
static int countint (const TValue *key, int *nums)
static int numusearray (const Table *t, int *nums)
static int numusehash (const Table *t, int *nums, int *pnasize)
static void setarrayvector (lua_State *L, Table *t, int size)
static void setnodevector (lua_State *L, Table *t, int size)
static void resize (lua_State *L, Table *t, int nasize, int nhsize)
void luaH_resizearray (lua_State *L, Table *t, int nasize)
static void rehash (lua_State *L, Table *t, const TValue *ek)
Table * luaH_new (lua_State *L, int narray, int nhash)
void luaH_free (lua_State *L, Table *t)
static Node * getfreepos (Table *t)
static TValue * newkey (lua_State *L, Table *t, const TValue *key)
const TValue * luaH_getnum (Table *t, int key)
const TValue * luaH_getstr (Table *t, TString *key)
const TValue * luaH_get (Table *t, const TValue *key)
TValue * luaH_set (lua_State *L, Table *t, const TValue *key)
TValue * luaH_setnum (lua_State *L, Table *t, int key)
TValue * luaH_setstr (lua_State *L, Table *t, TString *key)
static int unbound_search (Table *t, unsigned int j)
int luaH_getn (Table *t)
Variables
static const Node dummynode_
Macro Definition Documentation
dummynode
#define dummynode (&dummynode_)
Definition at line 73 of file lua-5.1.5/src/ltable.c.
Referenced by luaH_free(), luaH_getn(), luaH_new(), luaH_resizearray(), newkey(), resize(), and setnodevector().
hashboolean
#define hashboolean (t, p) hashpow2(t, p)
Definition at line 53 of file lua-5.1.5/src/ltable.c.
Referenced by mainposition().
hashmod
#define hashmod (t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
Definition at line 60 of file lua-5.1.5/src/ltable.c.
Referenced by hashnum().
hashpointer
#define hashpointer (t, p) hashmod(t, IntPoint(p))
Definition at line 63 of file lua-5.1.5/src/ltable.c.
Referenced by mainposition().
hashpow2
#define hashpow2 (t, n) (gnode(t, lmod((n), sizenode(t))))
Definition at line 50 of file lua-5.1.5/src/ltable.c.
hashstr
#define hashstr (t, str) hashpow2(t, (str)->tsv.hash)
Definition at line 52 of file lua-5.1.5/src/ltable.c.
Referenced by luaH_getstr(), and mainposition().
ltable_c
#define ltable_c
Definition at line 24 of file lua-5.1.5/src/ltable.c.
LUA_CORE
#define LUA_CORE
Definition at line 25 of file lua-5.1.5/src/ltable.c.
MAXASIZE
#define MAXASIZE (1 << MAXBITS)
Definition at line 47 of file lua-5.1.5/src/ltable.c.
Referenced by countint().
MAXBITS
#define MAXBITS (LUAI_BITSINT-2)
Definition at line 44 of file lua-5.1.5/src/ltable.c.
Referenced by numusearray(), rehash(), and setnodevector().
numints
#define numints cast_int(sizeof(lua_Number)/sizeof(int))
Definition at line 69 of file lua-5.1.5/src/ltable.c.
Referenced by hashnum().
Function Documentation
arrayindex()
static int arrayindex (const TValue * key) static
Definition at line 120 of file lua-5.1.5/src/ltable.c.
{
  if (ttisnumber(key)) {
    lua_Number n = nvalue(key);
    int k;
    lua_number2int(k, n);
    if (luai_numeq(cast_num(k), n))
      return k;
  }
  return -1;  /* `key' did not match some condition */
}
References cast_num, lua_number2int, luai_numeq, nvalue, and ttisnumber.
Referenced by countint(), and findindex().
computesizes()
static int computesizes (int nums[], int * narray) static
Definition at line 189 of file lua-5.1.5/src/ltable.c.
{
  int i;
  int twotoi;  /* 2^i */
  int a = 0;  /* number of elements smaller than 2^i */
  int na = 0;  /* number of elements to go to array part */
  int n = 0;  /* optimal size for array part */
  for (i = 0, twotoi = 1; twotoi/2 < *narray; i++, twotoi *= 2) {
    if (nums[i] > 0) {
      a += nums[i];
      if (a > twotoi/2) {  /* more than half elements present? */
        n = twotoi;  /* optimal size (till now) */
        na = a;  /* all elements smaller than n will go to array part */
      }
    }
    if (a == *narray) break;  /* all elements already counted */
  }
  *narray = n;
  lua_assert(*narray/2 <= na && na <= *narray);
  return na;
}
References lua_assert.
Referenced by rehash().
countint()
static int countint (const TValue * key, int * nums) static
Definition at line 211 of file lua-5.1.5/src/ltable.c.
{
  int k = arrayindex(key);
  if (0 < k && k <= MAXASIZE) {  /* is `key' an appropriate array index? */
    nums[ceillog2(k)]++;  /* count as such */
    return 1;
  }
  else
    return 0;
}
References arrayindex(), ceillog2, and MAXASIZE.
Referenced by numusehash(), and rehash().
findindex()
static int findindex (lua_State * L, Table * t, StkId key) static
Definition at line 137 of file lua-5.1.5/src/ltable.c.
{
  int i;
  if (ttisnil(key)) return -1;  /* first iteration */
  i = arrayindex(key);
  if (0 < i && i <= t->sizearray)  /* is `key' inside array part? */
    return i-1;  /* yes; that's the index (corrected to C) */
  else {
    Node *n = mainposition(t, key);
    do {  /* check whether `key' is somewhere in the chain */
      /* key may be dead already, but it is ok to use it in `next' */
      if (luaO_rawequalObj(key2tval(n), key) ||
            (ttype(gkey(n)) == LUA_TDEADKEY && iscollectable(key) &&
             gcvalue(gkey(n)) == gcvalue(key))) {
        i = cast_int(n - gnode(t, 0));  /* key index in hash table */
        /* hash elements are numbered after array ones */
        return i + t->sizearray;
      }
      else n = gnext(n);
    } while (n);
    luaG_runerror(L, "invalid key to " LUA_QL("next"));  /* key not found */
    return 0;  /* to avoid warnings */
  }
}
References arrayindex(), cast_int, gcvalue, gkey, gnext, gnode, iscollectable, key2tval, LUA_QL, LUA_TDEADKEY, luaG_runerror(), luaO_rawequalObj(), mainposition(), Table::sizearray, ttisnil, and ttype.
Referenced by luaH_next().
getfreepos()
static Node * getfreepos (Table * t) static
Definition at line 382 of file lua-5.1.5/src/ltable.c.
{
  while (t->lastfree-- > t->node) {
    if (ttisnil(gkey(t->lastfree)))
      return t->lastfree;
  }
  return NULL;  /* could not find a free place */
}
References gkey, Table::lastfree, Table::node, NULL, and ttisnil.
Referenced by newkey().
hashnum()
static Node * hashnum (const Table * t, lua_Number n) static
Definition at line 84 of file lua-5.1.5/src/ltable.c.
{
  unsigned int a[numints];
  int i;
  if (luai_numeq(n, 0))  /* avoid problems with -0 */
    return gnode(t, 0);
  memcpy(a, &n, sizeof(a));
  for (i = 1; i < numints; i++) a[0] += a[i];
  return hashmod(t, a[0]);
}
References gnode, hashmod, luai_numeq, and numints.
Referenced by luaH_getnum(), and mainposition().
luaH_free()
void luaH_free (lua_State * L, Table * t)
Definition at line 374 of file lua-5.1.5/src/ltable.c.
{
  if (t->node != dummynode)
    luaM_freearray(L, t->node, sizenode(t), Node);
  luaM_freearray(L, t->array, t->sizearray, TValue);
  luaM_free(L, t);
}
References Table::array, dummynode, luaM_free, luaM_freearray, Table::node, Table::sizearray, and sizenode.
Referenced by freeobj(), freeobj(), freeobj(), and freeobj().
luaH_get()
const TValue * luaH_get (Table * t, const TValue * key)
Definition at line 469 of file lua-5.1.5/src/ltable.c.
{
  switch (ttype(key)) {
    case LUA_TNIL: return luaO_nilobject;
    case LUA_TSTRING: return luaH_getstr(t, rawtsvalue(key));
    case LUA_TNUMBER: {
      int k;
      lua_Number n = nvalue(key);
      lua_number2int(k, n);
      if (luai_numeq(cast_num(k), nvalue(key))) /* index is int? */
        return luaH_getnum(t, k);  /* use specialized version */
      /* else go through */
    }
    default: {
      Node *n = mainposition(t, key);
      do {  /* check whether `key' is somewhere in the chain */
        if (luaO_rawequalObj(key2tval(n), key))
          return gval(n);  /* that's it */
        else n = gnext(n);
      } while (n);
      return luaO_nilobject;
    }
  }
}
References cast_num, gnext, gval, key2tval, lua_number2int, LUA_TNIL, LUA_TNUMBER, LUA_TSTRING, luaH_getnum(), luaH_getstr(), luai_numeq, luaO_nilobject, luaO_rawequalObj(), mainposition(), nvalue, rawtsvalue, and ttype.
Referenced by addk(), lua_gettable(), lua_rawget(), lua_rawgetp(), lua_settable(), luaH_set(), luaV_execute(), luaV_finishget(), luaV_finishset(), luaV_finishset(), luaV_gettable(), and luaV_settable().
luaH_getn()
int luaH_getn (Table * t)
Definition at line 560 of file lua-5.1.5/src/ltable.c.
{
  unsigned int j = t->sizearray;
  if (j > 0 && ttisnil(&t->array[j - 1])) {
    /* there is a boundary in the array part: (binary) search for it */
    unsigned int i = 0;
    while (j - i > 1) {
      unsigned int m = (i+j)/2;
      if (ttisnil(&t->array[m - 1])) j = m;
      else i = m;
    }
    return i;
  }
  /* else must find a boundary in hash part */
  else if (t->node == dummynode)  /* hash part is empty? */
    return j;  /* that is easy... */
  else return unbound_search(t, j);
}
References Table::array, dummynode, Table::node, Table::sizearray, ttisnil, and unbound_search().
Referenced by lua_objlen(), lua_rawlen(), luaV_execute(), and luaV_objlen().
luaH_getnum()
const TValue * luaH_getnum (Table * t, int key)
Definition at line 435 of file lua-5.1.5/src/ltable.c.
{
  /* (1 <= key && key <= t->sizearray) */
  if (cast(unsigned int, key-1) < cast(unsigned int, t->sizearray))
    return &t->array[key-1];
  else {
    lua_Number nk = cast_num(key);
    Node *n = hashnum(t, nk);
    do {  /* check whether `key' is somewhere in the chain */
      if (ttisnumber(gkey(n)) && luai_numeq(nvalue(gkey(n)), nk))
        return gval(n);  /* that's it */
      else n = gnext(n);
    } while (n);
    return luaO_nilobject;
  }
}
References Table::array, cast, cast_num, gkey, gnext, gval, hashnum(), luai_numeq, luaO_nilobject, nvalue, Table::sizearray, and ttisnumber.
Referenced by lua_rawgeti(), luaH_get(), luaH_setnum(), and unbound_search().
luaH_getstr()
const TValue * luaH_getstr (Table * t, TString * key)
Definition at line 455 of file lua-5.1.5/src/ltable.c.
{
  Node *n = hashstr(t, key);
  do {  /* check whether `key' is somewhere in the chain */
    if (ttisstring(gkey(n)) && rawtsvalue(gkey(n)) == key)
      return gval(n);  /* that's it */
    else n = gnext(n);
  } while (n);
  return luaO_nilobject;
}
References gkey, gnext, gval, hashstr, luaO_nilobject, rawtsvalue, and ttisstring.
Referenced by auxgetstr(), auxgetstr(), auxsetstr(), auxsetstr(), luaH_get(), luaH_setstr(), luaT_gettm(), luaT_gettmbyobj(), luaV_execute(), luaV_execute(), and luaX_newstring().
luaH_new()
Table * luaH_new (lua_State * L, int narray, int nhash)
Definition at line 358 of file lua-5.1.5/src/ltable.c.
{
  Table *t = luaM_new(L, Table);
  luaC_link(L, obj2gco(t), LUA_TTABLE);
  t->metatable = NULL;
  t->flags = cast_byte(~0);
  /* temporary values (kept only if some malloc fails) */
  t->array = NULL;
  t->sizearray = 0;
  t->lsizenode = 0;
  t->node = cast(Node *, dummynode);
  setarrayvector(L, t, narray);
  setnodevector(L, t, nhash);
  return t;
}
References Table::array, cast, cast_byte, dummynode, Table::flags, Table::lsizenode, LUA_TTABLE, luaC_link(), luaM_new, Table::metatable, Table::node, NULL, obj2gco, setarrayvector(), setnodevector(), and Table::sizearray.
Referenced by adjust_varargs(), collectvalidlines(), collectvalidlines(), collectvalidlines(), collectvalidlines(), f_luaopen(), init_registry(), init_registry(), init_registry(), lua_createtable(), luaV_execute(), luaV_execute(), luaV_execute(), luaY_parser(), open_func(), and open_func().
luaH_next()
int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 162 of file lua-5.1.5/src/ltable.c.
{
  int i = findindex(L, t, key);  /* find original element */
  for (i++; i < t->sizearray; i++) {  /* try first array part */
    if (!ttisnil(&t->array[i])) {  /* a non-nil value? */
      setnvalue(key, cast_num(i+1));
      setobj2s(L, key+1, &t->array[i]);
      return 1;
    }
  }
  for (i -= t->sizearray; i < sizenode(t); i++) {  /* then hash part */
    if (!ttisnil(gval(gnode(t, i)))) {  /* a non-nil value? */
      setobj2s(L, key, key2tval(gnode(t, i)));
      setobj2s(L, key+1, gval(gnode(t, i)));
      return 1;
    }
  }
  return 0;  /* no more elements */
}
References Table::array, cast_num, findindex(), gnode, gval, key2tval, setnvalue, setobj2s, Table::sizearray, sizenode, and ttisnil.
Referenced by lua_next().
luaH_resizearray()
void luaH_resizearray (lua_State * L, Table * t, int nasize)
Definition at line 327 of file lua-5.1.5/src/ltable.c.
{
  int nsize = (t->node == dummynode) ? 0 : sizenode(t);
  resize(L, t, nasize, nsize);
}
References dummynode, Table::node, resize(), and sizenode.
Referenced by luaV_execute(), luaV_execute(), and luaV_execute().
luaH_set()
TValue * luaH_set (lua_State * L, Table * t, const TValue * key)
Definition at line 494 of file lua-5.1.5/src/ltable.c.
{
  const TValue *p = luaH_get(t, key);
  t->flags = 0;
  if (p != luaO_nilobject)
    return cast(TValue *, p);
  else {
    if (ttisnil(key)) luaG_runerror(L, "table index is nil");
    else if (ttisnumber(key) && luai_numisnan(nvalue(key)))
      luaG_runerror(L, "table index is NaN");
    return newkey(L, t, key);
  }
}
References cast, Table::flags, luaG_runerror(), luaH_get(), luai_numisnan, luaO_nilobject, newkey(), nvalue, ttisnil, and ttisnumber.
Referenced by addk(), addk(), addk(), aux_rawset(), lua_rawset(), lua_rawsetp(), luaV_settable(), luaX_newstring(), newkey(), and resize().
luaH_setnum()
TValue * luaH_setnum (lua_State * L, Table * t, int key)
Definition at line 508 of file lua-5.1.5/src/ltable.c.
{
  const TValue *p = luaH_getnum(t, key);
  if (p != luaO_nilobject)
    return cast(TValue *, p);
  else {
    TValue k;
    setnvalue(&k, cast_num(key));
    return newkey(L, t, &k);
  }
}
References cast, cast_num, luaH_getnum(), luaO_nilobject, newkey(), and setnvalue.
Referenced by adjust_varargs(), collectvalidlines(), lua_rawseti(), luaV_execute(), and resize().
luaH_setstr()
TValue * luaH_setstr (lua_State * L, Table * t, TString * key)
Definition at line 520 of file lua-5.1.5/src/ltable.c.
{
  const TValue *p = luaH_getstr(t, key);
  if (p != luaO_nilobject)
    return cast(TValue *, p);
  else {
    TValue k;
    setsvalue(L, &k, key);
    return newkey(L, t, &k);
  }
}
References cast, luaH_getstr(), luaO_nilobject, newkey(), and setsvalue.
Referenced by adjust_varargs(), and luaX_newstring().
mainposition()
static Node * mainposition (const Table * t, const TValue * key) static
Definition at line 100 of file lua-5.1.5/src/ltable.c.
{
  switch (ttype(key)) {
    case LUA_TNUMBER:
      return hashnum(t, nvalue(key));
    case LUA_TSTRING:
      return hashstr(t, rawtsvalue(key));
    case LUA_TBOOLEAN:
      return hashboolean(t, bvalue(key));
    case LUA_TLIGHTUSERDATA:
      return hashpointer(t, pvalue(key));
    default:
      return hashpointer(t, gcvalue(key));
  }
}
References bvalue, gcvalue, hashboolean, hashnum(), hashpointer, hashstr, LUA_TBOOLEAN, LUA_TLIGHTUSERDATA, LUA_TNUMBER, LUA_TSTRING, nvalue, pvalue, rawtsvalue, and ttype.
Referenced by findindex(), luaH_get(), and newkey().
newkey()
static TValue * newkey (lua_State * L, Table * t, const TValue * key) static
Definition at line 399 of file lua-5.1.5/src/ltable.c.
{
  Node *mp = mainposition(t, key);
  if (!ttisnil(gval(mp)) || mp == dummynode) {
    Node *othern;
    Node *n = getfreepos(t);  /* get a free place */
    if (n == NULL) {  /* cannot find a free place? */
      rehash(L, t, key);  /* grow table */
      return luaH_set(L, t, key);  /* re-insert key into grown table */
    }
    lua_assert(n != dummynode);
    othern = mainposition(t, key2tval(mp));
    if (othern != mp) {  /* is colliding node out of its main position? */
      /* yes; move colliding node into free position */
      while (gnext(othern) != mp) othern = gnext(othern);  /* find previous */
      gnext(othern) = n;  /* redo the chain with `n' in place of `mp' */
      *n = *mp;  /* copy colliding node into free pos. (mp->next also goes) */
      gnext(mp) = NULL;  /* now `mp' is free */
      setnilvalue(gval(mp));
    }
    else {  /* colliding node is in its own main position */
      /* new node will go into free position */
      gnext(n) = gnext(mp);  /* chain new position */
      gnext(mp) = n;
      mp = n;
    }
  }
  gkey(mp)->value = key->value; gkey(mp)->tt = key->tt;
  luaC_barriert(L, t, key);
  lua_assert(ttisnil(gval(mp)));
  return gval(mp);
}
References dummynode, getfreepos(), gkey, gnext, gval, key2tval, lua_assert, luaC_barriert, luaH_set(), mainposition(), NULL, rehash(), setnilvalue, and ttisnil.
Referenced by luaH_set(), luaH_setnum(), and luaH_setstr().
numusearray()
static int numusearray (const Table * t, int * nums) static
Definition at line 222 of file lua-5.1.5/src/ltable.c.
{
  int lg;
  int ttlg;  /* 2^lg */
  int ause = 0;  /* summation of `nums' */
  int i = 1;  /* count to traverse all array keys */
  for (lg=0, ttlg=1; lg<=MAXBITS; lg++, ttlg*=2) {  /* for each slice */
    int lc = 0;  /* counter */
    int lim = ttlg;
    if (lim > t->sizearray) {
      lim = t->sizearray;  /* adjust upper limit */
      if (i > lim)
        break;  /* no more elements to count */
    }
    /* count elements in range (2^(lg-1), 2^lg] */
    for (; i <= lim; i++) {
      if (!ttisnil(&t->array[i-1]))
        lc++;
    }
    nums[lg] += lc;
    ause += lc;
  }
  return ause;
}
References Table::array, MAXBITS, Table::sizearray, and ttisnil.
Referenced by rehash().
numusehash()
static int numusehash (const Table * t, int * nums, int * pnasize) static
Definition at line 247 of file lua-5.1.5/src/ltable.c.
{
  int totaluse = 0;  /* total number of elements */
  int ause = 0;  /* summation of `nums' */
  int i = sizenode(t);
  while (i--) {
    Node *n = &t->node[i];
    if (!ttisnil(gval(n))) {
      ause += countint(key2tval(n), nums);
      totaluse++;
    }
  }
  *pnasize += ause;
  return totaluse;
}
References countint(), gval, key2tval, Table::node, sizenode, and ttisnil.
Referenced by rehash().
rehash()
static void rehash (lua_State * L, Table * t, const TValue * ek) static
Definition at line 333 of file lua-5.1.5/src/ltable.c.
{
  int nasize, na;
  int nums[MAXBITS+1];  /* nums[i] = number of keys between 2^(i-1) and 2^i */
  int i;
  int totaluse;
  for (i=0; i<=MAXBITS; i++) nums[i] = 0;  /* reset counts */
  nasize = numusearray(t, nums);  /* count keys in array part */
  totaluse = nasize;  /* all those keys are integer keys */
  totaluse += numusehash(t, nums, &nasize);  /* count keys in hash part */
  /* count extra key */
  nasize += countint(ek, nums);
  totaluse++;
  /* compute new size for array part */
  na = computesizes(nums, &nasize);
  /* resize the table to new computed sizes */
  resize(L, t, nasize, totaluse - na);
}
References computesizes(), countint(), MAXBITS, numusearray(), numusehash(), and resize().
Referenced by newkey().
resize()
static void resize (lua_State * L, Table * t, int nasize, int nhsize) static
Definition at line 297 of file lua-5.1.5/src/ltable.c.
{
  int i;
  int oldasize = t->sizearray;
  int oldhsize = t->lsizenode;
  Node *nold = t->node;  /* save old hash ... */
  if (nasize > oldasize)  /* array part must grow? */
    setarrayvector(L, t, nasize);
  /* create new hash part with appropriate size */
  setnodevector(L, t, nhsize);
  if (nasize < oldasize) {  /* array part must shrink? */
    t->sizearray = nasize;
    /* re-insert elements from vanishing slice */
    for (i=nasize; i<oldasize; i++) {
      if (!ttisnil(&t->array[i]))
        setobjt2t(L, luaH_setnum(L, t, i+1), &t->array[i]);
    }
    /* shrink array */
    luaM_reallocvector(L, t->array, oldasize, nasize, TValue);
  }
  /* re-insert elements from hash part */
  for (i = twoto(oldhsize) - 1; i >= 0; i--) {
    Node *old = nold+i;
    if (!ttisnil(gval(old)))
      setobjt2t(L, luaH_set(L, t, key2tval(old)), gval(old));
  }
  if (nold != dummynode)
    luaM_freearray(L, nold, twoto(oldhsize), Node);  /* free old array */
}
References Table::array, dummynode, gval, key2tval, Table::lsizenode, luaH_set(), luaH_setnum(), luaM_freearray, luaM_reallocvector, Table::node, setarrayvector(), setnodevector(), setobjt2t, Table::sizearray, ttisnil, and twoto.
Referenced by luaH_resizearray(), and rehash().
setarrayvector()
static void setarrayvector (lua_State * L, Table * t, int size) static
Definition at line 263 of file lua-5.1.5/src/ltable.c.
{
  int i;
  luaM_reallocvector(L, t->array, t->sizearray, size, TValue);
  for (i=t->sizearray; i<size; i++)
     setnilvalue(&t->array[i]);
  t->sizearray = size;
}
References Table::array, luaM_reallocvector, setnilvalue, and Table::sizearray.
Referenced by luaH_new(), and resize().
setnodevector()
static void setnodevector (lua_State * L, Table * t, int size) static
Definition at line 272 of file lua-5.1.5/src/ltable.c.
{
  int lsize;
  if (size == 0) {  /* no elements to hash part? */
    t->node = cast(Node *, dummynode);  /* use common `dummynode' */
    lsize = 0;
  }
  else {
    int i;
    lsize = ceillog2(size);
    if (lsize > MAXBITS)
      luaG_runerror(L, "table overflow");
    size = twoto(lsize);
    t->node = luaM_newvector(L, size, Node);
    for (i=0; i<size; i++) {
      Node *n = gnode(t, i);
      gnext(n) = NULL;
      setnilvalue(gkey(n));
      setnilvalue(gval(n));
    }
  }
  t->lsizenode = cast_byte(lsize);
  t->lastfree = gnode(t, size);  /* all positions are free */
}
References cast, cast_byte, ceillog2, dummynode, gkey, gnext, gnode, gval, Table::lastfree, Table::lsizenode, luaG_runerror(), luaM_newvector, MAXBITS, Table::node, NULL, setnilvalue, and twoto.
Referenced by luaH_new(), and resize().
unbound_search()
static int unbound_search (Table * t, unsigned int j) static
Definition at line 532 of file lua-5.1.5/src/ltable.c.
{
  unsigned int i = j;  /* i is zero or a present index */
  j++;
  /* find `i' and `j' such that i is present and j is not */
  while (!ttisnil(luaH_getnum(t, j))) {
    i = j;
    j *= 2;
    if (j > cast(unsigned int, MAX_INT)) {  /* overflow? */
      /* table was built with bad purposes: resort to linear search */
      i = 1;
      while (!ttisnil(luaH_getnum(t, i))) i++;
      return i - 1;
    }
  }
  /* now do a binary search between them */
  while (j - i > 1) {
    unsigned int m = (i+j)/2;
    if (ttisnil(luaH_getnum(t, m))) j = m;
    else i = m;
  }
  return i;
}
References cast, luaH_getnum(), MAX_INT, and ttisnil.
Referenced by luaH_getn().
Variable Documentation
dummynode_
const Node dummynode_ static
Initial value:
= {
  {{NULL}, LUA_TNIL},
  {{{NULL}, LUA_TNIL, NULL}}
}
Definition at line 75 of file lua-5.1.5/src/ltable.c.
{
  {{NULL}, LUA_TNIL},  /* value */
  {{{NULL}, LUA_TNIL, NULL}}  /* key */
};