Github User Fetcher: lstring.c File Reference
lstring.c File Reference
#include <string.h>
#include "lua.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
Macros
#define lstring_c
#define LUA_CORE
#define LUAI_HASHLIMIT 5
Functions
int luaS_eqlngstr (TString *a, TString *b)
int luaS_eqstr (TString *a, TString *b)
unsigned int luaS_hash (const char *str, size_t l, unsigned int seed)
void luaS_resize (lua_State *L, int newsize)
static TString * createstrobj (lua_State *L, const char *str, size_t l, int tag, unsigned int h, GCObject **list)
static TString * newshrstr (lua_State *L, const char *str, size_t l, unsigned int h)
static TString * internshrstr (lua_State *L, const char *str, size_t l)
TString * luaS_newlstr (lua_State *L, const char *str, size_t l)
TString * luaS_new (lua_State *L, const char *str)
Udata * luaS_newudata (lua_State *L, size_t s, Table *e)
Macro Definition Documentation
lstring_c
#define lstring_c
Definition at line 10 of file lua-5.2.4/src/lstring.c.
LUA_CORE
#define LUA_CORE
Definition at line 11 of file lua-5.2.4/src/lstring.c.
LUAI_HASHLIMIT
#define LUAI_HASHLIMIT 5
Definition at line 26 of file lua-5.2.4/src/lstring.c.
Referenced by luaS_hash().
Function Documentation
createstrobj()
static TString * createstrobj (lua_State * L, const char * str, size_t l, int tag, unsigned int h, GCObject ** list) static
Definition at line 98 of file lua-5.2.4/src/lstring.c.
{
  TString *ts;
  size_t totalsize;  /* total size of TString object */
  totalsize = sizeof(TString) + ((l + 1) * sizeof(char));
  ts = &luaC_newobj(L, tag, totalsize, list, 0)->ts;
  ts->tsv.len = l;
  ts->tsv.hash = h;
  ts->tsv.extra = 0;
  memcpy(ts+1, str, l*sizeof(char));
  ((char *)(ts+1))[l] = '\0';  /* ending 0 */
  return ts;
}
References TString::extra, TString::hash, TString::len, luaC_newobj(), GCObject::ts, and TString::tsv.
Referenced by luaS_newlstr(), and newshrstr().
internshrstr()
static TString * internshrstr (lua_State * L, const char * str, size_t l) static
Definition at line 133 of file lua-5.2.4/src/lstring.c.
{
  GCObject *o;
  global_State *g = G(L);
  unsigned int h = luaS_hash(str, l, g->seed);
  for (o = g->strt.hash[lmod(h, g->strt.size)];
       o != NULL;
       o = gch(o)->next) {
    TString *ts = rawgco2ts(o);
    if (h == ts->tsv.hash &&
        l == ts->tsv.len &&
        (memcmp(str, getstr(ts), l * sizeof(char)) == 0)) {
      if (isdead(G(L), o))  /* string is dead (but was not collected yet)? */
        changewhite(o);  /* resurrect it */
      return ts;
    }
  }
  return newshrstr(L, str, l, h);  /* not found; create a new string */
}
References changewhite, G, gch, getstr, TString::hash, stringtable::hash, isdead, TString::len, lmod, luaS_hash(), newshrstr(), NULL, rawgco2ts, global_State::seed, stringtable::size, global_State::strt, and TString::tsv.
Referenced by luaS_newlstr().
luaS_eqlngstr()
int luaS_eqlngstr (TString * a, TString * b)
Definition at line 33 of file lua-5.2.4/src/lstring.c.
{
  size_t len = a->tsv.len;
  lua_assert(a->tsv.tt == LUA_TLNGSTR && b->tsv.tt == LUA_TLNGSTR);
  return (a == b) ||  /* same instance or... */
    ((len == b->tsv.len) &&  /* equal length and ... */
     (memcmp(getstr(a), getstr(b), len) == 0));  /* equal contents */
}
References getstr, TString::len, lua_assert, LUA_TLNGSTR, and TString::tsv.
Referenced by equalkey(), luaS_eqstr(), luaV_equalobj(), and luaV_equalobj_().
luaS_eqstr()
int luaS_eqstr (TString * a, TString * b)
Definition at line 45 of file lua-5.2.4/src/lstring.c.
{
  return (a->tsv.tt == b->tsv.tt) &&
         (a->tsv.tt == LUA_TSHRSTR ? eqshrstr(a, b) : luaS_eqlngstr(a, b));
}
References eqshrstr, LUA_TSHRSTR, luaS_eqlngstr(), and TString::tsv.
Referenced by checkrepeated(), closegoto(), findgotos(), findlabel(), searchupvalue(), and searchvar().
luaS_hash()
unsigned int luaS_hash (const char * str, size_t l, unsigned int seed)
Definition at line 51 of file lua-5.2.4/src/lstring.c.
{
  unsigned int h = seed ^ cast(unsigned int, l);
  size_t l1;
  size_t step = (l >> LUAI_HASHLIMIT) + 1;
  for (l1 = l; l1 >= step; l1 -= step)
    h = h ^ ((h<<5) + (h>>2) + cast_byte(str[l1 - 1]));
  return h;
}
References cast, cast_byte, and LUAI_HASHLIMIT.
Referenced by internshrstr(), luai_makeseed(), mainposition(), makeseed(), and makeseed().
luaS_new()
TString * luaS_new (lua_State * L, const char * str)
Definition at line 170 of file lua-5.2.4/src/lstring.c.
{
  return luaS_newlstr(L, str, strlen(str));
}
References luaS_newlstr().
luaS_newlstr()
TString * luaS_newlstr (lua_State * L, const char * str, size_t l)
Definition at line 156 of file lua-5.2.4/src/lstring.c.
{
  if (l <= LUAI_MAXSHORTLEN)  /* short string? */
    return internshrstr(L, str, l);
  else {
    if (l + 1 > (MAX_SIZET - sizeof(TString))/sizeof(char))
      luaM_toobig(L);
    return createstrobj(L, str, l, LUA_TLNGSTR, G(L)->seed, NULL);
  }
}
References createstrobj(), G, internshrstr(), LUA_TLNGSTR, LUAI_MAXSHORTLEN, luaM_toobig(), MAX_SIZET, and NULL.
Referenced by luaS_new().
luaS_newudata()
Udata * luaS_newudata (lua_State * L, size_t s, Table * e)
Definition at line 175 of file lua-5.2.4/src/lstring.c.
{
  Udata *u;
  if (s > MAX_SIZET - sizeof(Udata))
    luaM_toobig(L);
  u = &luaC_newobj(L, LUA_TUSERDATA, sizeof(Udata) + s, NULL, 0)->u;
  u->uv.len = s;
  u->uv.metatable = NULL;
  u->uv.env = e;
  return u;
}
References Udata::env, Udata::len, LUA_TUSERDATA, luaC_newobj(), luaM_toobig(), MAX_SIZET, Udata::metatable, NULL, s, GCObject::u, and Udata::uv.
luaS_resize()
void luaS_resize (lua_State * L, int newsize)
Definition at line 64 of file lua-5.2.4/src/lstring.c.
{
  int i;
  stringtable *tb = &G(L)->strt;
  /* cannot resize while GC is traversing strings */
  luaC_runtilstate(L, ~bitmask(GCSsweepstring));
  if (newsize > tb->size) {
    luaM_reallocvector(L, tb->hash, tb->size, newsize, GCObject *);
    for (i = tb->size; i < newsize; i++) tb->hash[i] = NULL;
  }
  /* rehash */
  for (i=0; i<tb->size; i++) {
    GCObject *p = tb->hash[i];
    tb->hash[i] = NULL;
    while (p) {  /* for each node in the list */
      GCObject *next = gch(p)->next;  /* save next */
      unsigned int h = lmod(gco2ts(p)->hash, newsize);  /* new position */
      gch(p)->next = tb->hash[h];  /* chain it */
      tb->hash[h] = p;
      resetoldbit(p);  /* see MOVE OLD rule */
      p = next;
    }
  }
  if (newsize < tb->size) {
    /* shrinking slice must be empty */
    lua_assert(tb->hash[newsize] == NULL && tb->hash[tb->size - 1] == NULL);
    luaM_reallocvector(L, tb->hash, tb->size, newsize, GCObject *);
  }
  tb->size = newsize;
}
References bitmask, G, gch, gco2ts, GCSsweepstring, stringtable::hash, lmod, lua_assert, luaC_runtilstate(), luaM_reallocvector, next, NULL, resetoldbit, and stringtable::size.
Referenced by newshrstr().
newshrstr()
static TString * newshrstr (lua_State * L, const char * str, size_t l, unsigned int h) static
Definition at line 116 of file lua-5.2.4/src/lstring.c.
{
  GCObject **list;  /* (pointer to) list where it will be inserted */
  stringtable *tb = &G(L)->strt;
  TString *s;
  if (tb->nuse >= cast(lu_int32, tb->size) && tb->size <= MAX_INT/2)
    luaS_resize(L, tb->size*2);  /* too crowded */
  list = &tb->hash[lmod(h, tb->size)];
  s = createstrobj(L, str, l, LUA_TSHRSTR, h, list);
  tb->nuse++;
  return s;
}
References cast, createstrobj(), G, stringtable::hash, lmod, LUA_TSHRSTR, luaS_resize(), MAX_INT, stringtable::nuse, s, and stringtable::size.
Referenced by internshrstr().