Github User Fetcher: lobject.c File Reference
lobject.c File Reference
#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "ldo.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "lvm.h"
Macros
#define lobject_c
#define LUA_CORE
Functions
int luaO_int2fb (unsigned int x)
int luaO_fb2int (int x)
int luaO_log2 (unsigned int x)
int luaO_rawequalObj (const TValue *t1, const TValue *t2)
int luaO_str2d (const char *s, lua_Number *result)
static void pushstr (lua_State *L, const char *str)
const char * luaO_pushvfstring (lua_State *L, const char *fmt, va_list argp)
const char * luaO_pushfstring (lua_State *L, const char *fmt,...)
void luaO_chunkid (char *out, const char *source, size_t bufflen)
Variables
const TValue luaO_nilobject_ = {{NULL}, LUA_TNIL}
Macro Definition Documentation
lobject_c
#define lobject_c
Definition at line 13 of file lua-5.1.5/src/lobject.c.
LUA_CORE
#define LUA_CORE
Definition at line 14 of file lua-5.1.5/src/lobject.c.
Function Documentation
luaO_chunkid()
void luaO_chunkid (char * out, const char * source, size_t bufflen)
Definition at line 182 of file lua-5.1.5/src/lobject.c.
{
  if (*source == '=') {
    strncpy(out, source+1, bufflen);  /* remove first char */
    out[bufflen-1] = '\0';  /* ensures null termination */
  }
  else {  /* out = "source", or "...source" */
    if (*source == '@') {
      size_t l;
      source++;  /* skip the `@' */
      bufflen -= sizeof(" '...' ");
      l = strlen(source);
      strcpy(out, "");
      if (l > bufflen) {
        source += (l-bufflen);  /* get last part of file name */
        strcat(out, "...");
      }
      strcat(out, source);
    }
    else {  /* out = [string "string"] */
      size_t len = strcspn(source, "\n\r");  /* stop at first newline */
      bufflen -= sizeof(" [string \"...\"] ");
      if (len > bufflen) len = bufflen;
      strcpy(out, "[string \"");
      if (source[len] != '\0') {  /* must truncate? */
        strncat(out, source, len);
        strcat(out, "...");
      }
      else
        strcat(out, source);
      strcat(out, "\"]");
    }
  }
}
References bufflen.
Referenced by addinfo(), addinfo(), funcinfo(), funcinfo(), funcinfo(), funcinfo(), info_tailcall(), lexerror(), luaG_addinfo(), and luaX_lexerror().
luaO_fb2int()
int luaO_fb2int (int x)
Definition at line 47 of file lua-5.1.5/src/lobject.c.
{
  int e = (x >> 3) & 31;
  if (e == 0) return x;
  else return ((x & 7)+8) << (e - 1);
}
Referenced by luaV_execute(), and luaV_execute().
luaO_int2fb()
int luaO_int2fb (unsigned int x)
Definition at line 35 of file lua-5.1.5/src/lobject.c.
{
  int e = 0;  /* expoent */
  while (x >= 16) {
    x = (x+1) >> 1;
    e++;
  }
  if (x < 8) return x;
  else return ((e+1) << 3) | (cast_int(x) - 8);
}
References cast_int.
Referenced by constructor(), constructor(), and constructor().
luaO_log2()
int luaO_log2 (unsigned int x)
Definition at line 54 of file lua-5.1.5/src/lobject.c.
{
  static const lu_byte log_2[256] = {
    0,1,2,2,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
    7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
    7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
  };
  int l = -1;
  while (x >= 256) { l += 8; x >>= 8; }
  return l + log_2[x];
}
luaO_pushfstring()
const char * luaO_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 172 of file lua-5.1.5/src/lobject.c.
{
  const char *msg;
  va_list argp;
  va_start(argp, fmt);
  msg = luaO_pushvfstring(L, fmt, argp);
  va_end(argp);
  return msg;
}
References luaO_pushvfstring().
Referenced by addinfo(), addinfo(), check_match(), check_match(), check_match(), check_match(), check_readonly(), checkmode(), checkmode(), checkmode(), checkrepeated(), checkrepeated(), checkrepeated(), closegoto(), closegoto(), error(), error(), error(), error(), error_expected(), error_expected(), error_expected(), error_expected(), errorlimit(), errorlimit(), errorlimit(), errorlimit(), fchecksize(), fchecksize(), GCTM(), GCTM(), getlocalattribute(), jumpscopeerror(), lexerror(), lexerror(), lexerror(), luaG_addinfo(), luaX_lexerror(), luaX_token2str(), read_long_string(), read_long_string(), txtToken(), txtToken(), txtToken(), undefgoto(), undefgoto(), undefgoto(), varinfo(), and varinfo().
luaO_pushvfstring()
const char * luaO_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 111 of file lua-5.1.5/src/lobject.c.
{
  int n = 1;
  pushstr(L, "");
  for (;;) {
    const char *e = strchr(fmt, '%');
    if (e == NULL) break;
    setsvalue2s(L, L->top, luaS_newlstr(L, fmt, e-fmt));
    incr_top(L);
    switch (*(e+1)) {
      case 's': {
        const char *s = va_arg(argp, char *);
        if (s == NULL) s = "(null)";
        pushstr(L, s);
        break;
      }
      case 'c': {
        char buff[2];
        buff[0] = cast(char, va_arg(argp, int));
        buff[1] = '\0';
        pushstr(L, buff);
        break;
      }
      case 'd': {
        setnvalue(L->top, cast_num(va_arg(argp, int)));
        incr_top(L);
        break;
      }
      case 'f': {
        setnvalue(L->top, cast_num(va_arg(argp, l_uacNumber)));
        incr_top(L);
        break;
      }
      case 'p': {
        char buff[4*sizeof(void *) + 8]; /* should be enough space for a `%p' */
        sprintf(buff, "%p", va_arg(argp, void *));
        pushstr(L, buff);
        break;
      }
      case '%': {
        pushstr(L, "%");
        break;
      }
      default: {
        char buff[3];
        buff[0] = '%';
        buff[1] = *(e+1);
        buff[2] = '\0';
        pushstr(L, buff);
        break;
      }
    }
    n += 2;
    fmt = e+2;
  }
  pushstr(L, fmt);
  luaV_concat(L, n+1, cast_int(L->top - L->base) - 1);
  L->top -= n;
  return svalue(L->top - 1);
}
References lua_State::base, cast, cast_int, cast_num, incr_top, luaS_newlstr(), luaV_concat(), NULL, pushstr(), s, setnvalue, setsvalue2s, svalue, and lua_State::top.
Referenced by lua_pushfstring(), lua_pushvfstring(), luaG_runerror(), and luaO_pushfstring().
luaO_rawequalObj()
int luaO_rawequalObj (const TValue * t1, const TValue * t2)
Definition at line 72 of file lua-5.1.5/src/lobject.c.
{
  if (ttype(t1) != ttype(t2)) return 0;
  else switch (ttype(t1)) {
    case LUA_TNIL:
      return 1;
    case LUA_TNUMBER:
      return luai_numeq(nvalue(t1), nvalue(t2));
    case LUA_TBOOLEAN:
      return bvalue(t1) == bvalue(t2);  /* boolean true must be 1 !! */
    case LUA_TLIGHTUSERDATA:
      return pvalue(t1) == pvalue(t2);
    default:
      lua_assert(iscollectable(t1));
      return gcvalue(t1) == gcvalue(t2);
  }
}
References bvalue, gcvalue, iscollectable, lua_assert, LUA_TBOOLEAN, LUA_TLIGHTUSERDATA, LUA_TNIL, LUA_TNUMBER, luai_numeq, nvalue, pvalue, and ttype.
Referenced by addk(), call_orderTM(), findindex(), get_compTM(), lua_rawequal(), and luaH_get().
luaO_str2d()
int luaO_str2d (const char * s, lua_Number * result)
Definition at line 90 of file lua-5.1.5/src/lobject.c.
{
  char *endptr;
  *result = lua_str2number(s, &endptr);
  if (endptr == s) return 0;  /* conversion failed */
  if (*endptr == 'x' || *endptr == 'X')  /* maybe an hexadecimal constant? */
    *result = cast_num(strtoul(s, &endptr, 16));
  if (*endptr == '\0') return 1;  /* most common case */
  while (isspace(cast(unsigned char, *endptr))) endptr++;
  if (*endptr != '\0') return 0;  /* invalid trailing characters? */
  return 1;
}
References cast, cast_num, lua_str2number, and s.
Referenced by luaV_tonumber(), read_numeral(), and trydecpoint().
pushstr()
static void pushstr (lua_State * L, const char * str) static
Definition at line 104 of file lua-5.1.5/src/lobject.c.
{
  setsvalue2s(L, L->top, luaS_new(L, str));
  incr_top(L);
}
References incr_top, luaS_new, setsvalue2s, and lua_State::top.
Referenced by luaO_pushvfstring().
Variable Documentation
luaO_nilobject_
const TValue luaO_nilobject_ = {{NULL}, LUA_TNIL}
Definition at line 27 of file lua-5.1.5/src/lobject.c.
{{NULL}, LUA_TNIL};