Github User Fetcher: ldo.h File Reference
ldo.h File Reference
#include "lobject.h"
#include "lstate.h"
#include "lzio.h"
Macros
#define luaD_checkstackaux(L, n, pre, pos)
#define luaD_checkstack(L, n) luaD_checkstackaux(L,n,(void)0,(void)0)
#define savestack(L, p) ((char *)(p) - (char *)L->stack)
#define restorestack(L, n) ((TValue *)((char *)L->stack + (n)))
Typedefs
typedef void(* Pfunc) (lua_State *L, void *ud)
Functions
LUAI_FUNC int luaD_protectedparser (lua_State *L, ZIO *z, const char *name, const char *mode)
LUAI_FUNC void luaD_hook (lua_State *L, int event, int line)
LUAI_FUNC int luaD_precall (lua_State *L, StkId func, int nresults)
LUAI_FUNC void luaD_call (lua_State *L, StkId func, int nResults)
LUAI_FUNC void luaD_callnoyield (lua_State *L, StkId func, int nResults)
LUAI_FUNC int luaD_pcall (lua_State *L, Pfunc func, void *u, ptrdiff_t oldtop, ptrdiff_t ef)
LUAI_FUNC int luaD_poscall (lua_State *L, CallInfo *ci, StkId firstResult, int nres)
LUAI_FUNC void luaD_reallocstack (lua_State *L, int newsize)
LUAI_FUNC void luaD_growstack (lua_State *L, int n)
LUAI_FUNC void luaD_shrinkstack (lua_State *L)
LUAI_FUNC void luaD_inctop (lua_State *L)
LUAI_FUNC l_noret luaD_throw (lua_State *L, int errcode)
LUAI_FUNC int luaD_rawrunprotected (lua_State *L, Pfunc f, void *ud)
Macro Definition Documentation
luaD_checkstack
#define luaD_checkstack (L, n) luaD_checkstackaux(L,n,(void)0,(void)0)
Definition at line 28 of file lua-5.3.6/src/ldo.h.
luaD_checkstackaux
#define luaD_checkstackaux (L, n, pre, pos)
Value:
    if (L->stack_last - L->top <= (n)) \
      { pre; luaD_growstack(L, n); pos; } else { condmovestack(L,pre,pos); }
Definition at line 23 of file lua-5.3.6/src/ldo.h.
#define luaD_checkstackaux(L,n,pre,pos)  \
    if (L->stack_last - L->top <= (n)) \
      { pre; luaD_growstack(L, n); pos; } else { condmovestack(L,pre,pos); }
restorestack
#define restorestack (L, n) ((TValue *)((char *)L->stack + (n)))
Definition at line 33 of file lua-5.3.6/src/ldo.h.
savestack
#define savestack (L, p) ((char *)(p) - (char *)L->stack)
Definition at line 32 of file lua-5.3.6/src/ldo.h.
Typedef Documentation
Pfunc
typedef void(* Pfunc) (lua_State *L, void *ud)
Definition at line 37 of file lua-5.3.6/src/ldo.h.
Function Documentation
luaD_call()
LUAI_FUNC void luaD_call (lua_State * L, StkId func, int nResults)
Definition at line 370 of file lua-5.1.5/src/ldo.c.
{
  if (++L->nCcalls >= LUAI_MAXCCALLS) {
    if (L->nCcalls == LUAI_MAXCCALLS)
      luaG_runerror(L, "C stack overflow");
    else if (L->nCcalls >= (LUAI_MAXCCALLS + (LUAI_MAXCCALLS>>3)))
      luaD_throw(L, LUA_ERRERR);  /* error while handing stack error */
  }
  if (luaD_precall(L, func, nResults) == PCRLUA)  /* is a Lua function? */
    luaV_execute(L, 1);  /* call it */
  L->nCcalls--;
  luaC_checkGC(L);
}
luaD_callnoyield()
LUAI_FUNC void luaD_callnoyield (lua_State * L, StkId func, int nResults)
Definition at line 507 of file lua-5.3.6/src/ldo.c.
{
  L->nny++;
  luaD_call(L, func, nResults);
  L->nny--;
}
luaD_growstack()
LUAI_FUNC void luaD_growstack (lua_State * L, int n)
Definition at line 161 of file lua-5.1.5/src/ldo.c.
{
  if (n <= L->stacksize)  /* double size is enough? */
    luaD_reallocstack(L, 2*L->stacksize);
  else
    luaD_reallocstack(L, L->stacksize + n);
}
References cast_int, ERRORSTACKSIZE, EXTRA_STACK, LUA_ERRERR, luaD_reallocstack(), luaD_throw(), luaG_runerror(), LUAI_MAXSTACK, lua_State::stack, lua_State::stacksize, stacksize, and lua_State::top.
Referenced by growstack(), growstack(), and lua_checkstack().
luaD_hook()
LUAI_FUNC void luaD_hook (lua_State * L, int event, int line)
Definition at line 217 of file lua-5.2.4/src/ldo.c.
{
  lua_Hook hook = L->hook;
  if (hook && L->allowhook) {
    CallInfo *ci = L->ci;
    ptrdiff_t top = savestack(L, L->top);
    ptrdiff_t ci_top = savestack(L, ci->top);
    lua_Debug ar;
    ar.event = event;
    ar.currentline = line;
    ar.i_ci = ci;
    luaD_checkstack(L, LUA_MINSTACK);  /* ensure minimum stack size */
    ci->top = L->top + LUA_MINSTACK;
    lua_assert(ci->top <= L->stack_last);
    L->allowhook = 0;  /* cannot call hooks inside a hook */
    ci->callstatus |= CIST_HOOKED;
    lua_unlock(L);
    (*hook)(L, &ar);
    lua_lock(L);
    lua_assert(!L->allowhook);
    L->allowhook = 1;
    ci->top = restorestack(L, ci_top);
    L->top = restorestack(L, top);
    ci->callstatus &= ~CIST_HOOKED;
  }
}
References lua_State::allowhook, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, lua_Debug::currentline, lua_Debug::event, lua_State::hook, lua_Debug::i_ci, lua_assert, lua_lock, LUA_MINSTACK, lua_unlock, luaD_checkstack, restorestack, savestack, lua_State::stack_last, CallInfo::top, and lua_State::top.
Referenced by callhook(), callhook(), luaD_poscall(), luaD_poscall(), luaD_precall(), luaG_traceexec(), luaG_traceexec(), and traceexec().
luaD_inctop()
LUAI_FUNC void luaD_inctop (lua_State * L)
Definition at line 240 of file lua-5.3.6/src/ldo.c.
{
  luaD_checkstack(L, 1);
  L->top++;
}
luaD_pcall()
LUAI_FUNC int luaD_pcall (lua_State * L, Pfunc func, void * u, ptrdiff_t oldtop, ptrdiff_t ef)
Definition at line 456 of file lua-5.1.5/src/ldo.c.
{
  int status;
  unsigned short oldnCcalls = L->nCcalls;
  ptrdiff_t old_ci = saveci(L, L->ci);
  lu_byte old_allowhooks = L->allowhook;
  ptrdiff_t old_errfunc = L->errfunc;
  L->errfunc = ef;
  status = luaD_rawrunprotected(L, func, u);
  if (status != 0) {  /* an error occurred? */
    StkId oldtop = restorestack(L, old_top);
    luaF_close(L, oldtop);  /* close eventual pending closures */
    luaD_seterrorobj(L, status, oldtop);
    L->nCcalls = oldnCcalls;
    L->ci = restoreci(L, old_ci);
    L->base = L->ci->base;
    L->savedpc = L->ci->savedpc;
    L->allowhook = old_allowhooks;
    restore_stack_limit(L);
  }
  L->errfunc = old_errfunc;
  return status;
}
luaD_poscall()
LUAI_FUNC int luaD_poscall (lua_State * L, CallInfo * ci, StkId firstResult, int nres)
Definition at line 376 of file lua-5.3.6/src/ldo.c.
{
  StkId res;
  int wanted = ci->nresults;
  if (L->hookmask & (LUA_MASKRET | LUA_MASKLINE)) {
    if (L->hookmask & LUA_MASKRET) {
      ptrdiff_t fr = savestack(L, firstResult);  /* hook may change stack */
      luaD_hook(L, LUA_HOOKRET, -1);
      firstResult = restorestack(L, fr);
    }
    L->oldpc = ci->previous->u.l.savedpc;  /* 'oldpc' for caller function */
  }
  res = ci->func;  /* res == final position of 1st result */
  L->ci = ci->previous;  /* back to caller */
  /* move results to proper place */
  return moveresults(L, firstResult, res, nres, wanted);
}
References lua_State::ci, CallInfo::func, lua_State::hookmask, CallInfo::l, LUA_HOOKRET, LUA_MASKLINE, LUA_MASKRET, luaD_hook(), moveresults(), CallInfo::nresults, lua_State::oldpc, CallInfo::previous, restorestack, CallInfo::savedpc, savestack, and CallInfo::u.
Referenced by finishCcall(), luaD_precall(), and resume().
luaD_precall()
LUAI_FUNC int luaD_precall (lua_State * L, StkId func, int nresults)
Definition at line 265 of file lua-5.1.5/src/ldo.c.
{
  LClosure *cl;
  ptrdiff_t funcr;
  if (!ttisfunction(func)) /* `func' is not a function? */
    func = tryfuncTM(L, func);  /* check the `function' tag method */
  funcr = savestack(L, func);
  cl = &clvalue(func)->l;
  L->ci->savedpc = L->savedpc;
  if (!cl->isC) {  /* Lua function? prepare its call */
    CallInfo *ci;
    StkId st, base;
    Proto *p = cl->p;
    luaD_checkstack(L, p->maxstacksize);
    func = restorestack(L, funcr);
    if (!p->is_vararg) {  /* no varargs? */
      base = func + 1;
      if (L->top > base + p->numparams)
        L->top = base + p->numparams;
    }
    else {  /* vararg function */
      int nargs = cast_int(L->top - func) - 1;
      base = adjust_varargs(L, p, nargs);
      func = restorestack(L, funcr);  /* previous call may change the stack */
    }
    ci = inc_ci(L);  /* now `enter' new function */
    ci->func = func;
    L->base = ci->base = base;
    ci->top = L->base + p->maxstacksize;
    lua_assert(ci->top <= L->stack_last);
    L->savedpc = p->code;  /* starting point */
    ci->tailcalls = 0;
    ci->nresults = nresults;
    for (st = L->top; st < ci->top; st++)
      setnilvalue(st);
    L->top = ci->top;
    if (L->hookmask & LUA_MASKCALL) {
      L->savedpc++;  /* hooks assume 'pc' is already incremented */
      luaD_callhook(L, LUA_HOOKCALL, -1);
      L->savedpc--;  /* correct 'pc' */
    }
    return PCRLUA;
  }
  else {  /* if is a C function, call it */
    CallInfo *ci;
    int n;
    luaD_checkstack(L, LUA_MINSTACK);  /* ensure minimum stack size */
    ci = inc_ci(L);  /* now `enter' new function */
    ci->func = restorestack(L, funcr);
    L->base = ci->base = ci->func + 1;
    ci->top = L->top + LUA_MINSTACK;
    lua_assert(ci->top <= L->stack_last);
    ci->nresults = nresults;
    if (L->hookmask & LUA_MASKCALL)
      luaD_callhook(L, LUA_HOOKCALL, -1);
    lua_unlock(L);
    n = (*curr_func(L)->c.f)(L);  /* do the actual call */
    lua_lock(L);
    if (n < 0)  /* yielding? */
      return PCRYIELD;
    else {
      luaD_poscall(L, L->top - n);
      return PCRC;
    }
  }
}
luaD_protectedparser()
LUAI_FUNC int luaD_protectedparser (lua_State * L, ZIO * z, const char * name, const char * mode)
Definition at line 662 of file lua-5.2.4/src/ldo.c.
{
  struct SParser p;
  int status;
  L->nny++;  /* cannot yield during parsing */
  p.z = z; p.name = name; p.mode = mode;
  p.dyd.actvar.arr = NULL; p.dyd.actvar.size = 0;
  p.dyd.gt.arr = NULL; p.dyd.gt.size = 0;
  p.dyd.label.arr = NULL; p.dyd.label.size = 0;
  luaZ_initbuffer(L, &p.buff);
  status = luaD_pcall(L, f_parser, &p, savestack(L, L->top), L->errfunc);
  luaZ_freebuffer(L, &p.buff);
  luaM_freearray(L, p.dyd.actvar.arr, p.dyd.actvar.size);
  luaM_freearray(L, p.dyd.gt.arr, p.dyd.gt.size);
  luaM_freearray(L, p.dyd.label.arr, p.dyd.label.size);
  L->nny--;
  return status;
}
luaD_rawrunprotected()
LUAI_FUNC int luaD_rawrunprotected (lua_State * L, Pfunc f, void * ud)
Definition at line 111 of file lua-5.1.5/src/ldo.c.
{
  struct lua_longjmp lj;
  lj.status = 0;
  lj.previous = L->errorJmp;  /* chain new error handler */
  L->errorJmp = &lj;
  LUAI_TRY(L, &lj,
    (*f)(L, ud);
  );
  L->errorJmp = lj.previous;  /* restore old error handler */
  return lj.status;
}
luaD_reallocstack()
LUAI_FUNC void luaD_reallocstack (lua_State * L, int newsize)
Definition at line 141 of file lua-5.1.5/src/ldo.c.
{
  TValue *oldstack = L->stack;
  int realsize = newsize + 1 + EXTRA_STACK;
  lua_assert(L->stack_last - L->stack == L->stacksize - EXTRA_STACK - 1);
  luaM_reallocvector(L, L->stack, L->stacksize, realsize, TValue);
  L->stacksize = realsize;
  L->stack_last = L->stack+newsize;
  correctstack(L, oldstack);
}
References correctstack(), correctstack(), correctstack(), ERRORSTACKSIZE, EXTRA_STACK, lua_assert, LUAI_MAXSTACK, luaM_reallocvector, setnilvalue, lua_State::stack, lua_State::stack_last, and lua_State::stacksize.
Referenced by checkstacksizes(), luaD_growstack(), luaD_shrinkstack(), and luaE_resetthread().
luaD_shrinkstack()
LUAI_FUNC void luaD_shrinkstack (lua_State * L)
Definition at line 205 of file lua-5.2.4/src/ldo.c.
{
  int inuse = stackinuse(L);
  int goodsize = inuse + (inuse / 8) + 2*EXTRA_STACK;
  if (goodsize > LUAI_MAXSTACK) goodsize = LUAI_MAXSTACK;
  if (inuse > LUAI_MAXSTACK ||  /* handling stack overflow? */
      goodsize >= L->stacksize)  /* would grow instead of shrink? */
    condmovestack(L);  /* don't change stack (change only for debugging) */
  else
    luaD_reallocstack(L, goodsize);  /* shrink it */
}
luaD_throw()
LUAI_FUNC l_noret luaD_throw (lua_State * L, int errcode)
Definition at line 94 of file lua-5.1.5/src/ldo.c.
{
  if (L->errorJmp) {
    L->errorJmp->status = errcode;
    LUAI_THROW(L, L->errorJmp);
  }
  else {
    L->status = cast_byte(errcode);
    if (G(L)->panic) {
      resetstack(L, errcode);
      lua_unlock(L);
      G(L)->panic(L);
    }
    exit(EXIT_FAILURE);
  }
}