Github User Fetcher: lua_struct.c File Reference
lua_struct.c File Reference
#include <ctype.h>
#include <limits.h>
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
Data Structures
struct cD
struct Header
Macros
#define STRUCT_INT long
#define MAXINTSIZE 32
#define isp2(x) ((x) > 0 && ((x) & ((x) - 1)) == 0)
#define PADDING (sizeof(struct cD) - sizeof(double))
#define MAXALIGN (PADDING > sizeof(int) ? PADDING : sizeof(int))
#define BIG 0
#define LITTLE 1
#define defaultoptions(h) ((h)->endian = native.endian, (h)->align = 1)
Typedefs
typedef STRUCT_INT Inttype
typedef unsigned STRUCT_INT Uinttype
typedef struct Header Header
Functions
static int getnum (const char **fmt, int df)
static size_t optsize (lua_State *L, char opt, const char **fmt)
static int gettoalign (size_t len, Header *h, int opt, size_t size)
static void controloptions (lua_State *L, int opt, const char **fmt, Header *h)
static void putinteger (lua_State *L, luaL_Buffer *b, int arg, int endian, int size)
static void correctbytes (char *b, int size, int endian)
static int b_pack (lua_State *L)
static lua_Number getinteger (const char *buff, int endian, int issigned, int size)
static int b_unpack (lua_State *L)
static int b_size (lua_State *L)
LUALIB_API int luaopen_struct (lua_State *L)
Variables
union {
int dummy
char endian
} native = {1}
static const struct luaL_Reg thislib []
Macro Definition Documentation
BIG
#define BIG 0
Definition at line 75 of file lua_struct.c.
Referenced by controloptions(), and getinteger().
defaultoptions
#define defaultoptions (h) ((h)->endian = native.endian, (h)->align = 1)
Definition at line 104 of file lua_struct.c.
Referenced by b_pack(), b_size(), and b_unpack().
isp2
#define isp2 (x) ((x) > 0 && ((x) & ((x) - 1)) == 0)
Definition at line 61 of file lua_struct.c.
Referenced by controloptions().
LITTLE
#define LITTLE 1
Definition at line 76 of file lua_struct.c.
Referenced by controloptions(), and putinteger().
MAXALIGN
#define MAXALIGN (PADDING > sizeof(int) ? PADDING : sizeof(int))
Definition at line 71 of file lua_struct.c.
Referenced by controloptions().
MAXINTSIZE
#define MAXINTSIZE 32
Definition at line 58 of file lua_struct.c.
Referenced by optsize(), and putinteger().
PADDING
#define PADDING (sizeof(struct cD) - sizeof(double))
Definition at line 70 of file lua_struct.c.
STRUCT_INT
#define STRUCT_INT long
Definition at line 48 of file lua_struct.c.
Typedef Documentation
Header
typedef struct Header Header
Inttype
typedef STRUCT_INT Inttype
Definition at line 51 of file lua_struct.c.
Uinttype
typedef unsigned STRUCT_INT Uinttype
Definition at line 54 of file lua_struct.c.
Function Documentation
b_pack()
static int b_pack (lua_State * L) static
Definition at line 205 of file lua_struct.c.
{
  luaL_Buffer b;
  const char *fmt = luaL_checkstring(L, 1);
  Header h;
  int arg = 2;
  size_t totalsize = 0;
  defaultoptions(&h);
  lua_pushnil(L);  /* mark to separate arguments from string buffer */
  luaL_buffinit(L, &b);
  while (*fmt != '\0') {
    int opt = *fmt++;
    size_t size = optsize(L, opt, &fmt);
    int toalign = gettoalign(totalsize, &h, opt, size);
    totalsize += toalign;
    while (toalign-- > 0) luaL_addchar(&b, '\0');
    switch (opt) {
      case 'b': case 'B': case 'h': case 'H':
      case 'l': case 'L': case 'T': case 'i': case 'I': {  /* integer types */
        putinteger(L, &b, arg++, h.endian, size);
        break;
      }
      case 'x': {
        luaL_addchar(&b, '\0');
        break;
      }
      case 'f': {
        float f = (float)luaL_checknumber(L, arg++);
        correctbytes((char *)&f, size, h.endian);
        luaL_addlstring(&b, (char *)&f, size);
        break;
      }
      case 'd': {
        double d = luaL_checknumber(L, arg++);
        correctbytes((char *)&d, size, h.endian);
        luaL_addlstring(&b, (char *)&d, size);
        break;
      }
      case 'c': case 's': {
        size_t l;
        const char *s = luaL_checklstring(L, arg++, &l);
        if (size == 0) size = l;
        luaL_argcheck(L, l >= (size_t)size, arg, "string too short");
        luaL_addlstring(&b, s, size);
        if (opt == 's') {
          luaL_addchar(&b, '\0');  /* add zero at the end */
          size++;
        }
        break;
      }
      default: controloptions(L, opt, &fmt, &h);
    }
    totalsize += size;
  }
  luaL_pushresult(&b);
  return 1;
}
References arg, controloptions(), correctbytes(), defaultoptions, Header::endian, gettoalign(), lua_pushnil(), luaL_addchar, luaL_addlstring(), luaL_argcheck, luaL_buffinit(), luaL_checklstring(), luaL_checknumber(), luaL_checkstring, luaL_pushresult(), optsize(), putinteger(), and s.
b_size()
static int b_size (lua_State * L) static
Definition at line 359 of file lua_struct.c.
{
  Header h;
  const char *fmt = luaL_checkstring(L, 1);
  size_t pos = 0;
  defaultoptions(&h);
  while (*fmt) {
    int opt = *fmt++;
    size_t size = optsize(L, opt, &fmt);
    pos += gettoalign(pos, &h, opt, size);
    if (opt == 's')
      luaL_argerror(L, 1, "option 's' has no fixed size");
    else if (opt == 'c' && size == 0)
      luaL_argerror(L, 1, "option 'c0' has no fixed size");
    if (!isalnum(opt))
      controloptions(L, opt, &fmt, &h);
    pos += size;
  }
  lua_pushinteger(L, pos);
  return 1;
}
References controloptions(), defaultoptions, gettoalign(), lua_pushinteger(), luaL_argerror(), luaL_checkstring, and optsize().
b_unpack()
static int b_unpack (lua_State * L) static
Definition at line 290 of file lua_struct.c.
{
  Header h;
  const char *fmt = luaL_checkstring(L, 1);
  size_t ld;
  const char *data = luaL_checklstring(L, 2, &ld);
  size_t pos = (size_t)luaL_optinteger(L, 3, 1) - 1;
  int n = 0;  /* number of results */
  luaL_argcheck(L, pos <= ld, 3, "initial position out of string");
  defaultoptions(&h);
  while (*fmt) {
    int opt = *fmt++;
    size_t size = optsize(L, opt, &fmt);
    pos += gettoalign(pos, &h, opt, size);
    luaL_argcheck(L, size <= ld - pos, 2, "data string too short");
    /* stack space for item + next position */
    luaL_checkstack(L, 2, "too many results");
    switch (opt) {
      case 'b': case 'B': case 'h': case 'H':
      case 'l': case 'L': case 'T': case 'i':  case 'I': {  /* integer types */
        int issigned = islower(opt);
        lua_Number res = getinteger(data+pos, h.endian, issigned, size);
        lua_pushnumber(L, res); n++;
        break;
      }
      case 'x': {
        break;
      }
      case 'f': {
        float f;
        memcpy(&f, data+pos, size);
        correctbytes((char *)&f, sizeof(f), h.endian);
        lua_pushnumber(L, f); n++;
        break;
      }
      case 'd': {
        double d;
        memcpy(&d, data+pos, size);
        correctbytes((char *)&d, sizeof(d), h.endian);
        lua_pushnumber(L, d); n++;
        break;
      }
      case 'c': {
        if (size == 0) {
          if (n == 0 || !lua_isnumber(L, -1))
            luaL_error(L, "format 'c0' needs a previous size");
          size = lua_tonumber(L, -1);
          lua_pop(L, 1); n--;
          luaL_argcheck(L, size <= ld - pos, 2, "data string too short");
        }
        lua_pushlstring(L, data+pos, size); n++;
        break;
      }
      case 's': {
        const char *e = (const char *)memchr(data+pos, '\0', ld - pos);
        if (e == NULL)
          luaL_error(L, "unfinished string in data");
        size = (e - (data+pos)) + 1;
        lua_pushlstring(L, data+pos, size - 1); n++;
        break;
      }
      default: controloptions(L, opt, &fmt, &h);
    }
    pos += size;
  }
  lua_pushinteger(L, pos + 1);  /* next position */
  return n + 1;
}
References controloptions(), correctbytes(), defaultoptions, Header::endian, getinteger(), gettoalign(), lua_isnumber(), lua_pop, lua_pushinteger(), lua_pushlstring(), lua_pushnumber(), lua_tonumber, luaL_argcheck, luaL_checklstring(), luaL_checkstack(), luaL_checkstring, luaL_error(), luaL_optinteger(), NULL, and optsize().
controloptions()
static void controloptions (lua_State * L, int opt, const char ** fmt, Header * h) static
Definition at line 145 of file lua_struct.c.
{
  switch (opt) {
    case  ' ': return;  /* ignore white spaces */
    case '>': h->endian = BIG; return;
    case '<': h->endian = LITTLE; return;
    case '!': {
      int a = getnum(fmt, MAXALIGN);
      if (!isp2(a))
        luaL_error(L, "alignment %d is not a power of 2", a);
      h->align = a;
      return;
    }
    default: {
      const char *msg = lua_pushfstring(L, "invalid format option '%c'", opt);
      luaL_argerror(L, 1, msg);
    }
  }
}
References Header::align, BIG, Header::endian, getnum(), isp2, LITTLE, lua_pushfstring(), luaL_argerror(), luaL_error(), and MAXALIGN.
Referenced by b_pack(), b_size(), and b_unpack().
correctbytes()
static void correctbytes (char * b, int size, int endian) static
Definition at line 193 of file lua_struct.c.
{
  if (endian != native.endian) {
    int i = 0;
    while (i < --size) {
      char temp = b[i];
      b[i++] = b[size];
      b[size] = temp;
    }
  }
}
References endian, and native.
Referenced by b_pack(), and b_unpack().
getinteger()
static lua_Number getinteger (const char * buff, int endian, int issigned, int size) static
Definition at line 263 of file lua_struct.c.
{
  Uinttype l = 0;
  int i;
  if (endian == BIG) {
    for (i = 0; i < size; i++) {
      l <<= 8;
      l |= (Uinttype)(unsigned char)buff[i];
    }
  }
  else {
    for (i = size - 1; i >= 0; i--) {
      l <<= 8;
      l |= (Uinttype)(unsigned char)buff[i];
    }
  }
  if (!issigned)
    return (lua_Number)l;
  else {  /* signed format */
    Uinttype mask = (Uinttype)(~((Uinttype)0)) << (size*8 - 1);
    if (l & mask)  /* negative value? */
      l |= mask;  /* signal extension */
    return (lua_Number)(Inttype)l;
  }
}
References BIG, endian, and mask.
Referenced by b_unpack().
getnum()
static int getnum (const char ** fmt, int df) static
Definition at line 91 of file lua_struct.c.
{
  if (!isdigit(**fmt))  /* no number? */
    return df;  /* return default value */
  else {
    int a = 0;
    do {
      a = a*10 + *((*fmt)++) - '0';
    } while (isdigit(**fmt));
    return a;
  }
}
Referenced by controloptions(), and optsize().
gettoalign()
static int gettoalign (size_t len, Header * h, int opt, size_t size) static
Definition at line 134 of file lua_struct.c.
{
  if (size == 0 || opt == 'c') return 0;
  if (size > (size_t)h->align)
    size = h->align;  /* respect max. alignment */
  return (size - (len & (size - 1))) & (size - 1);
}
References Header::align.
Referenced by b_pack(), b_size(), and b_unpack().
luaopen_struct()
LUALIB_API int luaopen_struct (lua_State * L)
Definition at line 394 of file lua_struct.c.
{
  /* added to global environment */
  luaL_newlib(L, thislib);
  lua_pushvalue(L, -1);
  lua_setglobal(L, "struct");
  return 1;
}
References lua_pushvalue(), lua_setglobal, luaL_newlib, and thislib.
optsize()
static size_t optsize (lua_State * L, char opt, const char ** fmt) static
Definition at line 108 of file lua_struct.c.
{
  switch (opt) {
    case 'B': case 'b': return sizeof(char);
    case 'H': case 'h': return sizeof(short);
    case 'L': case 'l': return sizeof(long);
    case 'T': return sizeof(size_t);
    case 'f':  return sizeof(float);
    case 'd':  return sizeof(double);
    case 'x': return 1;
    case 'c': return getnum(fmt, 1);
    case 'i': case 'I': {
      int sz = getnum(fmt, sizeof(int));
      if (sz > MAXINTSIZE)
        luaL_error(L, "integral size %d is larger than limit of %d",
                       sz, MAXINTSIZE);
      return sz;
    }
    default: return 0;  /* other cases do not need alignment */
  }
}
References getnum(), luaL_error(), and MAXINTSIZE.
Referenced by b_pack(), b_size(), and b_unpack().
putinteger()
static void putinteger (lua_State * L, luaL_Buffer * b, int arg, int endian, int size) static
Definition at line 166 of file lua_struct.c.
{
  lua_Number n = luaL_checknumber(L, arg);
  Uinttype value;
  char buff[MAXINTSIZE];
  if (n < 0)
    value = (Uinttype)(Inttype)n;
  else
    value = (Uinttype)n;
  if (endian == LITTLE) {
    int i;
    for (i = 0; i < size; i++) {
      buff[i] = (value & 0xff);
      value >>= 8;
    }
  }
  else {
    int i;
    for (i = size - 1; i >= 0; i--) {
      buff[i] = (value & 0xff);
      value >>= 8;
    }
  }
  luaL_addlstring(b, buff, size);
}
References arg, endian, LITTLE, luaL_addlstring(), luaL_checknumber(), MAXINTSIZE, and value.
Referenced by b_pack().
Variable Documentation
dummy
int dummy
Definition at line 80 of file lua_struct.c.
endian
char endian
Definition at line 81 of file lua_struct.c.
Referenced by correctbytes(), getinteger(), and putinteger().
[union]
union { ... } native
Referenced by correctbytes().
thislib
const struct luaL_Reg thislib[] static
Initial value:
= {
  {"pack", b_pack},
  {"unpack", b_unpack},
  {"size", b_size},
  {NULL, NULL}
}
Definition at line 384 of file lua_struct.c.
{
  {"pack", b_pack},
  {"unpack", b_unpack},
  {"size", b_size},
  {NULL, NULL}
};
Referenced by luaopen_struct().