Github User Fetcher: server.h File Reference
server.h File Reference
Declaration of the HTTP server functions.
Functions
void start_http_server (int port)
Starts the HTTP server.
Detailed Description
Declaration of the HTTP server functions.
Definition in file server.h.
Function Documentation
start_http_server()
void start_http_server (int port)
Starts the HTTP server.
Initializes and runs the Civetweb server on the specified port.
Parameters
port TCP port number to listen on.
Starts the HTTP server.
Configures Civetweb with basic options and handles incoming user requests. The server runs indefinitely until manually interrupted.
Parameters
port The TCP port to listen on.
Definition at line 59 of file server.c.
{
  char *port_str = NULL;
  if (asprintf(&port_str, "%d", port) == -1) {
    (void)fprintf(stderr, "Failed to allocate memory for port\n");
    return;
  }
  const char *options[] = {"listening_ports",
                           port_str,
                           "enable_keep_alive",
                           "yes",
                           "access_log_file",
                           "access.log",
                           NULL};
  struct mg_callbacks callbacks = {0};
  struct mg_context *ctx = mg_start(&callbacks, NULL, options);
  if (!ctx) {
    (void)fprintf(stderr, "Failed to start Civetweb server\n");
    return;
  }
  mg_set_request_handler(ctx, "/", user_handler, NULL);
  printf("Server started on port %s. Visit http://localhost:%s/USERNAME\n",
         port_str, port_str);
  puts("Press Ctrl+C to quit.");
  free(port_str);
  // Keep running (or use signal handler in future)
  while (1) {
    sleep(1);
  }
  mg_stop(ctx);
}
References mg_context::callbacks, free, mg_set_request_handler(), mg_start(), mg_stop(), NULL, printf, and user_handler().
Referenced by main().