Github User Fetcher: stdcheaders.h File Reference
stdcheaders.h File Reference
#include <sys/types.h>
Functions
size_t fread (void *, size_t, size_t, FILE *)
size_t fwrite (const void *, size_t, size_t, FILE *)
int strcasecmp (const char *, const char *)
int strncasecmp (const char *, const char *, size_t)
Function Documentation
fread()
size_t fread (void * , size_t , size_t , FILE *)
Referenced by do_jxpretty(), do_jxpretty(), do_sandbox_test(), do_sandbox_test(), fileio_readfile(), fileio_readfile(), getF(), getF(), getF(), getF(), handle_fh(), handle_fh(), handle_fh(), read_all(), read_all(), read_all(), read_chars(), read_chars(), read_chars(), read_chars(), send_file_data(), and Xml_load().
fwrite()
size_t fwrite (const void * , size_t , size_t , FILE *)
Referenced by g_write(), g_write(), g_write(), g_write(), handle_interactive(), handle_interactive(), mg_modify_passwords_file_ha1(), mg_store_body(), push_inner(), run_client(), wrapped_compile_execute(), wrapped_compile_execute(), writer(), writer(), writer(), and writer().
strcasecmp()
int strcasecmp (const char * , const char *)
strncasecmp()
int strncasecmp (const char * , const char * , size_t)