Github User Fetcher: HttpSession Class Reference
HttpSession Class Reference
Public Member Functions
HttpSession (tcp::socket socket)
void start ()
Private Member Functions
void read_request ()
void handle_request ()
Private Attributes
tcp::socket socket_
beast::flat_buffer buffer_
http::request< http::string_body > req_
Detailed Description
Definition at line 23 of file server.cpp.
Constructor & Destructor Documentation
HttpSession()
HttpSession::HttpSession (tcp::socket socket) inline explicit
Definition at line 25 of file server.cpp.
        : socket_(std::move(socket)) {}
Member Function Documentation
handle_request()
void HttpSession::handle_request () inline private
Definition at line 46 of file server.cpp.
{
        auto res = std::make_shared<http::response<http::string_body>>();
        res->version(req_.version());
        res->keep_alive(false);
        std::string target(req_.target());
        std::string username = target.length() > 1 ? target.substr(1) : "";
        if (username.empty()) {
            res->result(http::status::bad_request);
            res->set(http::field::content_type, "text/plain");
            res->body() = "Missing username in request URI.";
        } else {
            try {
                User user = fetch_github_user(username);
                nlohmann::json j = {
                    {"login", user.getLogin()},
                    {"name", user.getName()},
                    {"company", user.getCompany()},
                    {"location", user.getLocation()}
                };
                res->result(http::status::ok);
                res->set(http::field::content_type, "application/json");
                res->body() = j.dump();
            } catch (const std::exception& e) {
                res->result(http::status::not_found);
                res->set(http::field::content_type, "text/plain");
                res->body() = std::string("Error fetching user: ") + e.what();
            }
        }
        res->prepare_payload();
        auto self = shared_from_this();
        http::async_write(socket_, *res,
            [self, res](beast::error_code ec, std::size_t) {
                self->socket_.shutdown(tcp::socket::shutdown_send, ec);
            });
    }
References fetch_github_user(), req_, and socket_.
read_request()
void HttpSession::read_request () inline private
Definition at line 37 of file server.cpp.
{
        auto self = shared_from_this();
        http::async_read(socket_, buffer_, req_,
            [self](beast::error_code ec, std::size_t) {
                if (!ec)
                    self->handle_request();
            });
    }
References buffer_, req_, and socket_.
Referenced by start().
start()
void HttpSession::start () inline
Definition at line 28 of file server.cpp.
                 {
        read_request();
    }
References read_request().
Field Documentation
buffer_
beast::flat_buffer HttpSession::buffer_ private
Definition at line 34 of file server.cpp.
Referenced by read_request().
req_
http::request<http::string_body> HttpSession::req_ private
Definition at line 35 of file server.cpp.
Referenced by handle_request(), and read_request().
socket_
tcp::socket HttpSession::socket_ private
Definition at line 33 of file server.cpp.
Referenced by handle_request(), and read_request().
The documentation for this class was generated from the following file:
server.cpp