Github User Fetcher: GitHubUserFetcherWindow Class Reference
GitHubUserFetcherWindow Class Reference
Public Member Functions
GitHubUserFetcherWindow ()
Private Member Functions
void on_button_clicked ()
void show_message (const std::string &msg)
Private Attributes
Gtk::Box box
Gtk::Entry entry
Gtk::Button button
Gtk::ScrolledWindow scrolled_window
Gtk::TextView text_view
Detailed Description
Definition at line 8 of file gui.cpp.
Constructor & Destructor Documentation
GitHubUserFetcherWindow()
GitHubUserFetcherWindow::GitHubUserFetcherWindow () inline
Definition at line 10 of file gui.cpp.
{
        set_title("GitHub User Fetcher");
        set_default_size(400, 300);
        // Layout
        box.set_orientation(Gtk::Orientation::VERTICAL);
        set_child(box);
        entry.set_placeholder_text("Enter GitHub username...");
        box.append(entry);
        button.set_label("Fetch User");
        box.append(button);
        scrolled_window.set_child(text_view);
        scrolled_window.set_policy(Gtk::PolicyType::AUTOMATIC, Gtk::PolicyType::AUTOMATIC);
        scrolled_window.set_expand(true);
        box.append(scrolled_window);
        text_view.set_editable(false);
        text_view.set_wrap_mode(Gtk::WrapMode::WORD);
        button.signal_clicked().connect(sigc::mem_fun(*this, &GitHubUserFetcherWindow::on_button_clicked));
    }
References box, button, entry, on_button_clicked(), scrolled_window, and text_view.
Member Function Documentation
on_button_clicked()
void GitHubUserFetcherWindow::on_button_clicked () inline private
Definition at line 42 of file gui.cpp.
{
        std::string username = entry.get_text();
        if (username.empty()) {
            show_message("Please enter a username.");
            return;
        }
        // Clear previous result
        text_view.get_buffer()->set_text("Fetching...");
        // Run fetch in a background thread
        std::thread([this, username]() {
            try {
                User user = fetch_github_user(username);
                nlohmann::json j = {
                    {"login", user.getLogin()},
                    {"name", user.getName()},
                    {"company", user.getCompany()},
                    {"location", user.getLocation()}
                };
                std::string result = j.dump(4);
                // Update UI in main thread
                Glib::signal_idle().connect_once([this, result]() {
                    text_view.get_buffer()->set_text(result);
                });
            } catch (const std::exception& e) {
                std::string error_msg = std::string("Error: ") + e.what();
                Glib::signal_idle().connect_once([this, error_msg]() {
                    text_view.get_buffer()->set_text(error_msg);
                });
            }
        }).detach();
    }
References entry, fetch_github_user(), show_message(), and text_view.
Referenced by GitHubUserFetcherWindow().
show_message()
void GitHubUserFetcherWindow::show_message (const std::string & msg) inline private
Definition at line 79 of file gui.cpp.
{
        text_view.get_buffer()->set_text(msg);
    }
References text_view.
Referenced by on_button_clicked().
Field Documentation
box
Gtk::Box GitHubUserFetcherWindow::box private
Definition at line 36 of file gui.cpp.
Referenced by GitHubUserFetcherWindow().
button
Gtk::Button GitHubUserFetcherWindow::button private
Definition at line 38 of file gui.cpp.
Referenced by GitHubUserFetcherWindow().
entry
Gtk::Entry GitHubUserFetcherWindow::entry private
Definition at line 37 of file gui.cpp.
Referenced by GitHubUserFetcherWindow(), and on_button_clicked().
scrolled_window
Gtk::ScrolledWindow GitHubUserFetcherWindow::scrolled_window private
Definition at line 39 of file gui.cpp.
Referenced by GitHubUserFetcherWindow().
text_view
Gtk::TextView GitHubUserFetcherWindow::text_view private
Definition at line 40 of file gui.cpp.
Referenced by GitHubUserFetcherWindow(), on_button_clicked(), and show_message().
The documentation for this class was generated from the following file:
gui.cpp