Github User Fetcher: uppercase.c File Reference
uppercase.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "duktape.h"
Functions
static int dummy_upper_case (duk_context *ctx)
int main (int argc, char *argv[])
Function Documentation
dummy_upper_case()
static int dummy_upper_case (duk_context * ctx) static
Definition at line 6 of file duktape-1.5.2/examples/guide/uppercase.c.
{
    size_t sz;
    const char *val = duk_require_lstring(ctx, 0, &sz);
    size_t i;
    /* We're going to need 'sz' additional entries on the stack. */
    duk_require_stack(ctx, sz);
    for (i = 0; i < sz; i++) {
        char ch = val[i];
        if (ch >= 'a' && ch <= 'z') {
            ch = ch - 'a' + 'A';
        }
        duk_push_lstring(ctx, (const char *) &ch, 1);
    }
    duk_concat(ctx, sz);
    return 1;
}
References duk_concat(), duk_push_lstring(), duk_require_lstring(), and duk_require_stack().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 26 of file duktape-1.5.2/examples/guide/uppercase.c.
{
    duk_context *ctx;
    if (argc < 2) { exit(1); }
    ctx = duk_create_heap_default();
    if (!ctx) { exit(1); }
    duk_push_c_function(ctx, dummy_upper_case, 1);
    duk_push_string(ctx, argv[1]);
    duk_call(ctx, 1);
    printf("%s -> %s\n", argv[1], duk_to_string(ctx, -1));
    duk_pop(ctx);
    duk_destroy_heap(ctx);
    return 0;
}
References duk_call(), duk_create_heap_default, duk_destroy_heap(), duk_pop(), duk_push_c_function(), duk_push_string(), duk_to_string(), dummy_upper_case(), and printf.