Github User Fetcher: eval.c File Reference
eval.c File Reference
#include "duktape.h"
#include <stdio.h>
Functions
static int eval_raw (duk_context *ctx)
static int tostring_raw (duk_context *ctx)
static void usage_exit (void)
int main (int argc, char *argv[])
Function Documentation
eval_raw()
static int eval_raw (duk_context * ctx) static
Definition at line 9 of file duktape-1.5.2/examples/eval/eval.c.
{
    duk_eval(ctx);
    return 1;
}
References duk_eval.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 25 of file duktape-1.5.2/examples/eval/eval.c.
{
    duk_context *ctx;
    int i;
    const char *res;
    if (argc < 2) {
        usage_exit();
    }
    ctx = duk_create_heap_default();
    for (i = 1; i < argc; i++) {
        printf("=== eval: '%s' ===\n", argv[i]);
        duk_push_string(ctx, argv[i]);
        duk_safe_call(ctx, eval_raw, 1 /*nargs*/, 1 /*nrets*/);
        duk_safe_call(ctx, tostring_raw, 1 /*nargs*/, 1 /*nrets*/);
        res = duk_get_string(ctx, -1);
        printf("%s\n", res ? res : "null");
        duk_pop(ctx);
    }
    duk_destroy_heap(ctx);
    return 0;
}
References duk_create_heap_default, duk_destroy_heap(), duk_get_string(), duk_pop(), duk_push_string(), duk_safe_call(), eval_raw(), printf, tostring_raw(), and usage_exit().
tostring_raw()
static int tostring_raw (duk_context * ctx) static
Definition at line 14 of file duktape-1.5.2/examples/eval/eval.c.
{
    duk_to_string(ctx, -1);
    return 1;
}
References duk_to_string().
Referenced by main().
usage_exit()
static void usage_exit (void) static
Definition at line 19 of file duktape-1.5.2/examples/eval/eval.c.
{
    fprintf(stderr, "Usage: eval <expression> [<expression>] ...\n");
    fflush(stderr);
    exit(1);
}
Referenced by main().