Github User Fetcher: duk_trans_socket_windows.c File Reference
duk_trans_socket_windows.c File Reference
#include <windows.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <stdio.h>
#include <string.h>
#include "duktape.h"
Macros
#define WIN32_LEAN_AND_MEAN
#define DUK_DEBUG_PORT 9091
#define DUK_DEBUG_ADDRESS "0.0.0.0"
#define DUK__STRINGIFY_HELPER(x) #x
#define DUK__STRINGIFY(x) DUK__STRINGIFY_HELPER(x)
Functions
void duk_trans_socket_init (void)
void duk_trans_socket_finish (void)
void duk_trans_socket_waitconn (void)
duk_size_t duk_trans_socket_read_cb (void *udata, char *buffer, duk_size_t length)
duk_size_t duk_trans_socket_write_cb (void *udata, const char *buffer, duk_size_t length)
duk_size_t duk_trans_socket_peek_cb (void *udata)
void duk_trans_socket_read_flush_cb (void *udata)
void duk_trans_socket_write_flush_cb (void *udata)
Variables
static SOCKET server_sock = INVALID_SOCKET
static SOCKET client_sock = INVALID_SOCKET
static int wsa_inited = 0
Macro Definition Documentation
DUK__STRINGIFY
#define DUK__STRINGIFY (x) DUK__STRINGIFY_HELPER(x)
Definition at line 62 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
Referenced by duk_trans_socket_init().
DUK__STRINGIFY_HELPER
#define DUK__STRINGIFY_HELPER (x) #x
Definition at line 61 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
DUK_DEBUG_ADDRESS
#define DUK_DEBUG_ADDRESS "0.0.0.0"
Definition at line 59 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
Referenced by duk_trans_socket_init().
DUK_DEBUG_PORT
#define DUK_DEBUG_PORT 9091
Definition at line 56 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
Referenced by duk_trans_socket_init(), and duk_trans_socket_waitconn().
WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
Definition at line 32 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
Function Documentation
duk_trans_socket_finish()
void duk_trans_socket_finish (void)
Definition at line 150 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
{
    if (client_sock != INVALID_SOCKET) {
        (void) closesocket(client_sock);
        client_sock = INVALID_SOCKET;
    }
    if (server_sock != INVALID_SOCKET) {
        (void) closesocket(server_sock);
        server_sock = INVALID_SOCKET;
    }
    if (wsa_inited) {
        WSACleanup();
        wsa_inited = 0;
    }
}
References client_sock, client_sock, closesocket, INVALID_SOCKET, server_sock, server_sock, and wsa_inited.
duk_trans_socket_init()
void duk_trans_socket_init (void)
Definition at line 76 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
{
    WSADATA wsa_data;
    struct addrinfo hints;
    struct addrinfo *result = NULL;
    int rc;
    memset((void *) &wsa_data, 0, sizeof(wsa_data));
    memset((void *) &hints, 0, sizeof(hints));
    rc = WSAStartup(MAKEWORD(2, 2), &wsa_data);
    if (rc != 0) {
        fprintf(stderr, "%s: WSAStartup() failed: %d\n", __FILE__, rc);
        fflush(stderr);
        goto fail;
    }
    wsa_inited = 1;
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_protocol = IPPROTO_TCP;
    hints.ai_flags = AI_PASSIVE;
    rc = getaddrinfo(DUK_DEBUG_ADDRESS, DUK__STRINGIFY(DUK_DEBUG_PORT), &hints, &result);
    if (rc != 0) {
        fprintf(stderr, "%s: getaddrinfo() failed: %d\n", __FILE__, rc);
        fflush(stderr);
        goto fail;
    }
    server_sock = socket(result->ai_family, result->ai_socktype, result->ai_protocol);
    if (server_sock == INVALID_SOCKET) {
        fprintf(stderr, "%s: socket() failed with error: %ld\n",
                __FILE__, (long) WSAGetLastError());
        fflush(stderr);
        goto fail;
    }
    rc = bind(server_sock, result->ai_addr, (int) result->ai_addrlen);
    if (rc == SOCKET_ERROR) {
        fprintf(stderr, "%s: bind() failed with error: %ld\n",
                __FILE__, (long) WSAGetLastError());
        fflush(stderr);
        goto fail;
    }
    rc = listen(server_sock, SOMAXCONN);
    if (rc == SOCKET_ERROR) {
        fprintf(stderr, "%s: listen() failed with error: %ld\n",
                __FILE__, (long) WSAGetLastError());
        fflush(stderr);
        goto fail;
    }
    if (result != NULL) {
        freeaddrinfo(result);
        result = NULL;
    }
    return;
 fail:
    if (result != NULL) {
        freeaddrinfo(result);
        result = NULL;
    }
    if (server_sock != INVALID_SOCKET) {
        (void) closesocket(server_sock);
        server_sock = INVALID_SOCKET;
    }
    if (wsa_inited) {
        WSACleanup();
        wsa_inited = 0;
    }
}
References closesocket, DUK__STRINGIFY, DUK_DEBUG_ADDRESS, DUK_DEBUG_PORT, INVALID_SOCKET, NULL, server_sock, server_sock, and wsa_inited.
Referenced by create_duktape_heap(), and create_duktape_heap().
duk_trans_socket_peek_cb()
duk_size_t duk_trans_socket_peek_cb (void * udata)
Definition at line 331 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
{
    u_long avail;
    int rc;
    (void) udata;  /* not needed by the example */
#if defined(DEBUG_PRINTS)
    fprintf(stderr, "%s: udata=%p\n", __FUNCTION__, (void *) udata);
    fflush(stderr);
#endif
    if (client_sock == INVALID_SOCKET) {
        return 0;
    }
    avail = 0;
    rc = ioctlsocket(client_sock, FIONREAD, &avail);
    if (rc != 0) {
        fprintf(stderr, "%s: ioctlsocket() returned %d, closing connection\n",
                __FILE__, rc);
        fflush(stderr);
        goto fail;  /* also returns 0, which is correct */
    } else {
        if (avail == 0) {
            return 0;  /* nothing to read */
        } else {
            return 1;  /* something to read */
        }
    }
    /* never here */
 fail:
    if (client_sock != INVALID_SOCKET) {
        (void) closesocket(client_sock);
        client_sock = INVALID_SOCKET;
    }
    return 0;
}
References client_sock, client_sock, closesocket, and INVALID_SOCKET.
Referenced by create_duktape_heap(), and create_duktape_heap().
duk_trans_socket_read_cb()
duk_size_t duk_trans_socket_read_cb (void * udata, char * buffer, duk_size_t length)
Definition at line 214 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
{
    int ret;
    (void) udata;  /* not needed by the example */
#if defined(DEBUG_PRINTS)
    fprintf(stderr, "%s: udata=%p, buffer=%p, length=%ld\n",
            __FUNCTION__, (void *) udata, (void *) buffer, (long) length);
    fflush(stderr);
#endif
    if (client_sock == INVALID_SOCKET) {
        return 0;
    }
    if (length == 0) {
        /* This shouldn't happen. */
        fprintf(stderr, "%s: read request length == 0, closing connection\n",
                __FILE__);
        fflush(stderr);
        goto fail;
    }
    if (buffer == NULL) {
        /* This shouldn't happen. */
        fprintf(stderr, "%s: read request buffer == NULL, closing connection\n",
                __FILE__);
        fflush(stderr);
        goto fail;
    }
    /* In a production quality implementation there would be a sanity
     * timeout here to recover from "black hole" disconnects.
     */
    ret = recv(client_sock, (void *) buffer, (int) length, 0);
    if (ret < 0) {
        fprintf(stderr, "%s: debug read failed, error %d, closing connection\n",
                __FILE__, ret);
        fflush(stderr);
        goto fail;
    } else if (ret == 0) {
        fprintf(stderr, "%s: debug read failed, ret == 0 (EOF), closing connection\n",
                __FILE__);
        fflush(stderr);
        goto fail;
    } else if (ret > (int) length) {
        fprintf(stderr, "%s: debug read failed, ret too large (%ld > %ld), closing connection\n",
                __FILE__, (long) ret, (long) length);
        fflush(stderr);
        goto fail;
    }
    return (duk_size_t) ret;
 fail:
    if (client_sock != INVALID_SOCKET) {
        (void) closesocket(client_sock);
        client_sock = INVALID_SOCKET;
    }
    return 0;
}
References client_sock, client_sock, closesocket, INVALID_SOCKET, and NULL.
Referenced by create_duktape_heap(), and create_duktape_heap().
duk_trans_socket_read_flush_cb()
void duk_trans_socket_read_flush_cb (void * udata)
Definition at line 370 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
{
    (void) udata;  /* not needed by the example */
#if defined(DEBUG_PRINTS)
    fprintf(stderr, "%s: udata=%p\n", __FUNCTION__, (void *) udata);
    fflush(stderr);
#endif
    /* Read flush: Duktape may not be making any more read calls at this
     * time.  If the transport maintains a receive window, it can use a
     * read flush as a signal to update the window status to the remote
     * peer.  A read flush is guaranteed to occur before Duktape stops
     * reading for a while; it may occur in other situations as well so
     * it's not a 100% reliable indication.
     */
    /* This TCP transport requires no read flush handling so ignore.
     * You can also pass a NULL to duk_debugger_attach() and not
     * implement this callback at all.
     */
}
Referenced by create_duktape_heap(), and create_duktape_heap().
duk_trans_socket_waitconn()
void duk_trans_socket_waitconn (void)
Definition at line 165 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
{
    if (server_sock == INVALID_SOCKET) {
        fprintf(stderr, "%s: no server socket, skip waiting for connection\n",
                __FILE__);
        fflush(stderr);
        return;
    }
    if (client_sock != INVALID_SOCKET) {
        (void) closesocket(client_sock);
        client_sock = INVALID_SOCKET;
    }
    fprintf(stderr, "Waiting for debug connection on port %d\n", (int) DUK_DEBUG_PORT);
    fflush(stderr);
    client_sock = accept(server_sock, NULL, NULL);
    if (client_sock == INVALID_SOCKET) {
        fprintf(stderr, "%s: accept() failed with error %ld, skip waiting for connection\n",
                __FILE__, (long) WSAGetLastError());
        fflush(stderr);
        goto fail;
    }
    fprintf(stderr, "Debug connection established\n");
    fflush(stderr);
    /* XXX: For now, close the listen socket because we won't accept new
     * connections anyway.  A better implementation would allow multiple
     * debug attaches.
     */
    if (server_sock != INVALID_SOCKET) {
        (void) closesocket(server_sock);
        server_sock = INVALID_SOCKET;
    }
    return;
 fail:
    if (client_sock != INVALID_SOCKET) {
        (void) closesocket(client_sock);
        client_sock = INVALID_SOCKET;
    }
}
References client_sock, client_sock, closesocket, DUK_DEBUG_PORT, INVALID_SOCKET, NULL, server_sock, and server_sock.
Referenced by create_duktape_heap(), and create_duktape_heap().
duk_trans_socket_write_cb()
duk_size_t duk_trans_socket_write_cb (void * udata, const char * buffer, duk_size_t length)
Definition at line 278 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
{
    int ret;
    (void) udata;  /* not needed by the example */
#if defined(DEBUG_PRINTS)
    fprintf(stderr, "%s: udata=%p, buffer=%p, length=%ld\n",
            __FUNCTION__, (void *) udata, (const void *) buffer, (long) length);
    fflush(stderr);
#endif
    if (client_sock == INVALID_SOCKET) {
        return 0;
    }
    if (length == 0) {
        /* This shouldn't happen. */
        fprintf(stderr, "%s: write request length == 0, closing connection\n",
                __FILE__);
        fflush(stderr);
        goto fail;
    }
    if (buffer == NULL) {
        /* This shouldn't happen. */
        fprintf(stderr, "%s: write request buffer == NULL, closing connection\n",
                __FILE__);
        fflush(stderr);
        goto fail;
    }
    /* In a production quality implementation there would be a sanity
     * timeout here to recover from "black hole" disconnects.
     */
    ret = send(client_sock, (const void *) buffer, (int) length, 0);
    if (ret <= 0 || ret > (int) length) {
        fprintf(stderr, "%s: debug write failed, ret %d, closing connection\n",
                __FILE__, ret);
        fflush(stderr);
        goto fail;
    }
    return (duk_size_t) ret;
 fail:
    if (client_sock != INVALID_SOCKET) {
        (void) closesocket(INVALID_SOCKET);
        client_sock = INVALID_SOCKET;
    }
    return 0;
}
References client_sock, client_sock, closesocket, INVALID_SOCKET, and NULL.
Referenced by create_duktape_heap(), and create_duktape_heap().
duk_trans_socket_write_flush_cb()
void duk_trans_socket_write_flush_cb (void * udata)
Definition at line 392 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
{
    (void) udata;  /* not needed by the example */
#if defined(DEBUG_PRINTS)
    fprintf(stderr, "%s: udata=%p\n", __FUNCTION__, (void *) udata);
    fflush(stderr);
#endif
    /* Write flush.  If the transport combines multiple writes
     * before actually sending, a write flush is an indication
     * to write out any pending bytes: Duktape may not be doing
     * any more writes on this occasion.
     */
    /* This TCP transport requires no write flush handling so ignore.
     * You can also pass a NULL to duk_debugger_attach() and not
     * implement this callback at all.
     */
    return;
}
Referenced by create_duktape_heap(), and create_duktape_heap().
Variable Documentation
client_sock
SOCKET client_sock = INVALID_SOCKET static
Definition at line 69 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
Referenced by duk_trans_socket_finish(), duk_trans_socket_peek_cb(), duk_trans_socket_read_cb(), duk_trans_socket_waitconn(), and duk_trans_socket_write_cb().
server_sock
SOCKET server_sock = INVALID_SOCKET static
Definition at line 68 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
Referenced by duk_trans_socket_finish(), duk_trans_socket_init(), and duk_trans_socket_waitconn().
wsa_inited
int wsa_inited = 0 static
Definition at line 70 of file duktape-1.8.0/examples/debug-trans-socket/duk_trans_socket_windows.c.
Referenced by duk_trans_socket_finish(), and duk_trans_socket_init().