Github User Fetcher: cpp_exceptions.cpp File Reference
cpp_exceptions.cpp File Reference
#include <stdio.h>
#include <exception>
#include "duktape.h"
Data Structures
class my_class
class my_exception
class my_exception2
Macros
#define NOEXCEPT throw()
Functions
duk_ret_t test1 (duk_context *ctx)
duk_ret_t test2 (duk_context *ctx)
duk_ret_t test3 (duk_context *ctx)
duk_ret_t test4 (duk_context *ctx)
duk_ret_t test5 (duk_context *ctx)
int main (int argc, char *argv[])
Macro Definition Documentation
NOEXCEPT
#define NOEXCEPT throw()
Definition at line 35 of file duktape-1.8.0/examples/cpp-exceptions/cpp_exceptions.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 143 of file duktape-1.8.0/examples/cpp-exceptions/cpp_exceptions.cpp.
{
    duk_context *ctx = duk_create_heap_default();
    duk_int_t rc;
    (void) argc; (void) argv;  /* suppress warning */
    printf("*** test1 - duk_pcall()\n");
    duk_push_c_function(ctx, test1, 0);
    rc = duk_pcall(ctx, 0);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test1 - duk_safe_call()\n");
    rc = duk_safe_call(ctx, test1, 0, 1);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test1 - ecmascript try-catch\n");
    duk_push_c_function(ctx, test1, 0);
    duk_put_global_string(ctx, "test1");
    duk_eval_string_noresult(ctx,
        "try {\n"
        "    test1();\n"
        "} catch (e) {\n"
        "    print(e.stack || e);\n"
        "}\n");
    printf("\n");
    printf("*** test2 - duk_pcall()\n");
    duk_push_c_function(ctx, test2, 0);
    rc = duk_pcall(ctx, 0);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test2 - duk_safe_call()\n");
    rc = duk_safe_call(ctx, test2, 0, 1);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test2 - ecmascript try-catch\n");
    duk_push_c_function(ctx, test2, 0);
    duk_put_global_string(ctx, "test2");
    duk_eval_string_noresult(ctx,
        "try {\n"
        "    test2();\n"
        "} catch (e) {\n"
        "    print(e.stack || e);\n"
        "}\n");
    printf("\n");
    printf("*** test3 - duk_pcall()\n");
    duk_push_c_function(ctx, test3, 0);
    rc = duk_pcall(ctx, 0);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test3 - duk_safe_call()\n");
    rc = duk_safe_call(ctx, test3, 0, 1);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test3 - ecmascript try-catch\n");
    duk_push_c_function(ctx, test3, 0);
    duk_put_global_string(ctx, "test3");
    duk_eval_string_noresult(ctx,
        "try {\n"
        "    test3();\n"
        "} catch (e) {\n"
        "    print(e.stack || e);\n"
        "}\n");
    printf("\n");
    printf("*** test4 - duk_pcall()\n");
    duk_push_c_function(ctx, test4, 0);
    rc = duk_pcall(ctx, 0);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test4 - duk_safe_call()\n");
    rc = duk_safe_call(ctx, test4, 0, 1);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test4 - ecmascript try-catch\n");
    duk_push_c_function(ctx, test4, 0);
    duk_put_global_string(ctx, "test4");
    duk_eval_string_noresult(ctx,
        "try {\n"
        "    test4();\n"
        "} catch (e) {\n"
        "    print(e.stack || e);\n"
        "}\n");
    printf("\n");
    printf("*** test5 - duk_pcall()\n");
    duk_push_c_function(ctx, test5, 0);
    rc = duk_pcall(ctx, 0);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test5 - duk_safe_call()\n");
    rc = duk_safe_call(ctx, test5, 0, 1);
    printf("--> rc=%ld (%s)\n", (long) rc, duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
    printf("\n");
    printf("*** test5 - ecmascript try-catch\n");
    duk_push_c_function(ctx, test5, 0);
    duk_put_global_string(ctx, "test5");
    duk_eval_string_noresult(ctx,
        "try {\n"
        "    test5();\n"
        "} catch (e) {\n"
        "    print(e.stack || e);\n"
        "}\n");
    printf("\n");
    printf("*** done\n");
    duk_destroy_heap(ctx);
    return 0;
}
References duk_create_heap_default, duk_destroy_heap(), duk_eval_string_noresult, duk_pcall(), duk_pop(), duk_push_c_function(), duk_put_global_string(), duk_safe_call(), duk_safe_to_string, printf, test1(), test2(), test3(), test4(), and test5().
test1()
duk_ret_t test1 (duk_context * ctx)
Definition at line 61 of file duktape-1.8.0/examples/cpp-exceptions/cpp_exceptions.cpp.
{
    my_class myclass;
    duk_eval_string(ctx, "aiee=");
    return 0;
}
References duk_eval_string.
Referenced by main().
test2()
duk_ret_t test2 (duk_context * ctx)
Definition at line 74 of file duktape-1.8.0/examples/cpp-exceptions/cpp_exceptions.cpp.
{
    my_class myclass;
    try {
        throw 123;
    } catch (int myvalue) {
        printf("Caught: %d\n", myvalue);
    }
    return 0;
}
References printf.
Referenced by main().
test3()
duk_ret_t test3 (duk_context * ctx)
Definition at line 95 of file duktape-1.8.0/examples/cpp-exceptions/cpp_exceptions.cpp.
{
    my_class myclass;
    throw 123;  /* ERROR: exception propagated to Duktape */
    return 0;
}
Referenced by main().
test4()
duk_ret_t test4 (duk_context * ctx)
Definition at line 114 of file duktape-1.8.0/examples/cpp-exceptions/cpp_exceptions.cpp.
{
    my_class myclass;
    my_exception myexc;
    throw myexc;  /* ERROR: exception propagated to Duktape */
    return 0;
}
Referenced by main().
test5()
duk_ret_t test5 (duk_context * ctx)
Definition at line 134 of file duktape-1.8.0/examples/cpp-exceptions/cpp_exceptions.cpp.
{
    my_class myclass;
    my_exception2 myexc;
    throw myexc;  /* ERROR: exception propagated to Duktape */
    return 0;
}
Referenced by main().