Github User Fetcher: duk_alloc_logging.c File Reference
duk_alloc_logging.c File Reference
#include "duktape.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
Data Structures
struct alloc_hdr
Macros
#define ALLOC_LOG_FILE "/tmp/duk-alloc-log.txt"
Functions
static void write_log (const char *fmt,...)
void * duk_alloc_logging (void *udata, duk_size_t size)
void * duk_realloc_logging (void *udata, void *ptr, duk_size_t size)
void duk_free_logging (void *udata, void *ptr)
Variables
static FILE * log_file = NULL
Macro Definition Documentation
ALLOC_LOG_FILE
#define ALLOC_LOG_FILE "/tmp/duk-alloc-log.txt"
Definition at line 23 of file duktape-1.5.2/examples/alloc-logging/duk_alloc_logging.c.
Referenced by write_log().
Function Documentation
duk_alloc_logging()
void * duk_alloc_logging (void * udata, duk_size_t size)
Definition at line 53 of file duktape-1.5.2/examples/alloc-logging/duk_alloc_logging.c.
{
    alloc_hdr *hdr;
    void *ret;
    (void) udata;  /* Suppress warning. */
    if (size == 0) {
        write_log("A NULL %ld\n", (long) size);
        return NULL;
    }
    hdr = (alloc_hdr *) malloc(size + sizeof(alloc_hdr));
    if (!hdr) {
        write_log("A FAIL %ld\n", (long) size);
        return NULL;
    }
    hdr->u.sz = size;
    ret = (void *) (hdr + 1);
    write_log("A %p %ld\n", ret, (long) size);
    return ret;
}
References malloc, NULL, alloc_hdr::sz, alloc_hdr::u, and write_log().
Referenced by create_duktape_heap(), and create_duktape_heap().
duk_free_logging()
void duk_free_logging (void * udata, void * ptr)
Definition at line 126 of file duktape-1.5.2/examples/alloc-logging/duk_alloc_logging.c.
{
    alloc_hdr *hdr;
    (void) udata;  /* Suppress warning. */
    if (!ptr) {
        write_log("F NULL 0\n");
        return;
    }
    hdr = (alloc_hdr *) (void *) ((unsigned char *) ptr - sizeof(alloc_hdr));
    write_log("F %p %ld\n", ptr, (long) hdr->u.sz);
    free((void *) hdr);
}
References free, alloc_hdr::sz, alloc_hdr::u, and write_log().
Referenced by create_duktape_heap(), and create_duktape_heap().
duk_realloc_logging()
void * duk_realloc_logging (void * udata, void * ptr, duk_size_t size)
Definition at line 75 of file duktape-1.5.2/examples/alloc-logging/duk_alloc_logging.c.
{
    alloc_hdr *hdr;
    size_t old_size;
    void *t;
    void *ret;
    (void) udata;  /* Suppress warning. */
    /* Handle the ptr-NULL vs. size-zero cases explicitly to minimize
     * platform assumptions.  You can get away with much less in specific
     * well-behaving environments.
     */
    if (ptr) {
        hdr = (alloc_hdr *) (void *) ((unsigned char *) ptr - sizeof(alloc_hdr));
        old_size = hdr->u.sz;
        if (size == 0) {
            write_log("R %p %ld NULL 0\n", ptr, (long) old_size);
            free((void *) hdr);
            return NULL;
        } else {
            t = realloc((void *) hdr, size + sizeof(alloc_hdr));
            if (!t) {
                write_log("R %p %ld FAIL %ld\n", ptr, (long) old_size, (long) size);
                return NULL;
            }
            hdr = (alloc_hdr *) t;
            hdr->u.sz = size;
            ret = (void *) (hdr + 1);
            write_log("R %p %ld %p %ld\n", ptr, (long) old_size, ret, (long) size);
            return ret;
        }
    } else {
        if (size == 0) {
            write_log("R NULL 0 NULL 0\n");
            return NULL;
        } else {
            hdr = (alloc_hdr *) malloc(size + sizeof(alloc_hdr));
            if (!hdr) {
                write_log("R NULL 0 FAIL %ld\n", (long) size);
                return NULL;
            }
            hdr->u.sz = size;
            ret = (void *) (hdr + 1);
            write_log("R NULL 0 %p %ld\n", ret, (long) size);
            return ret;
        }
    }
}
References free, malloc, NULL, realloc, alloc_hdr::sz, alloc_hdr::u, and write_log().
Referenced by create_duktape_heap(), and create_duktape_heap().
write_log()
static void write_log (const char * fmt, ...) static
Definition at line 38 of file duktape-1.5.2/examples/alloc-logging/duk_alloc_logging.c.
{
    va_list ap;
    if (!log_file) {
        log_file = fopen(ALLOC_LOG_FILE, "wb");
        if (!log_file) {
            return;
        }
    }
    va_start(ap, fmt);
    vfprintf(log_file, fmt, ap);
    va_end(ap);
}
References ALLOC_LOG_FILE, and log_file.
Referenced by duk_alloc_logging(), duk_free_logging(), and duk_realloc_logging().
Variable Documentation
log_file
FILE* log_file = NULL static
Definition at line 36 of file duktape-1.5.2/examples/alloc-logging/duk_alloc_logging.c.
Referenced by write_log().