Github User Fetcher: duk_hobject_alloc.c File Reference
duk_hobject_alloc.c File Reference
#include "duk_internal.h"
Functions
DUK_LOCAL void duk__init_object_parts (duk_heap *heap, duk_hobject *obj, duk_uint_t hobject_flags)
DUK_INTERNAL duk_hobject * duk_hobject_alloc (duk_heap *heap, duk_uint_t hobject_flags)
DUK_INTERNAL duk_hcompiledfunction * duk_hcompiledfunction_alloc (duk_heap *heap, duk_uint_t hobject_flags)
DUK_INTERNAL duk_hnativefunction * duk_hnativefunction_alloc (duk_heap *heap, duk_uint_t hobject_flags)
DUK_INTERNAL duk_hbufferobject * duk_hbufferobject_alloc (duk_heap *heap, duk_uint_t hobject_flags)
DUK_INTERNAL duk_hthread * duk_hthread_alloc (duk_heap *heap, duk_uint_t hobject_flags)
Function Documentation
duk__init_object_parts()
DUK_LOCAL void duk__init_object_parts (duk_heap * heap, duk_hobject * obj, duk_uint_t hobject_flags)
Definition at line 11 of file duktape-1.5.2/src-separate/duk_hobject_alloc.c.
{
#ifdef DUK_USE_EXPLICIT_NULL_INIT
    DUK_HOBJECT_SET_PROPS(heap, obj, NULL);
#endif
    /* XXX: macro? sets both heaphdr and object flags */
    obj->hdr.h_flags = hobject_flags;
    DUK_HEAPHDR_SET_TYPE(&obj->hdr, DUK_HTYPE_OBJECT);  /* also goes into flags */
#if defined(DUK_USE_HEAPPTR16)
    /* Zero encoded pointer is required to match NULL */
    DUK_HEAPHDR_SET_NEXT(heap, &obj->hdr, NULL);
#if defined(DUK_USE_DOUBLE_LINKED_HEAP)
    DUK_HEAPHDR_SET_PREV(heap, &obj->hdr, NULL);
#endif
#endif
    DUK_ASSERT_HEAPHDR_LINKS(heap, &obj->hdr);
    DUK_HEAP_INSERT_INTO_HEAP_ALLOCATED(heap, &obj->hdr);
    /*
     *  obj->props is intentionally left as NULL, and duk_hobject_props.c must deal
     *  with this properly.  This is intentional: empty objects consume a minimum
     *  amount of memory.  Further, an initial allocation might fail and cause
     *  'obj' to "leak" (require a mark-and-sweep) since it is not reachable yet.
     */
}
References DUK_ASSERT_HEAPHDR_LINKS, DUK_HEAP_INSERT_INTO_HEAP_ALLOCATED, DUK_HEAPHDR_SET_NEXT, DUK_HEAPHDR_SET_PREV, DUK_HEAPHDR_SET_TYPE, DUK_HOBJECT_SET_PROPS, DUK_HTYPE_OBJECT, duk_heaphdr::h_flags, duk_hobject::hdr, and NULL.
Referenced by duk_hbufferobject_alloc(), duk_hcompiledfunction_alloc(), duk_hnativefunction_alloc(), duk_hobject_alloc(), and duk_hthread_alloc().
duk_hbufferobject_alloc()
DUK_INTERNAL duk_hbufferobject * duk_hbufferobject_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 112 of file duktape-1.5.2/src-separate/duk_hobject_alloc.c.
{
    duk_hbufferobject *res;
    res = (duk_hbufferobject *) DUK_ALLOC(heap, sizeof(duk_hbufferobject));
    if (!res) {
        return NULL;
    }
    DUK_MEMZERO(res, sizeof(duk_hbufferobject));
    duk__init_object_parts(heap, &res->obj, hobject_flags);
#ifdef DUK_USE_EXPLICIT_NULL_INIT
    res->buf = NULL;
#endif
    DUK_ASSERT_HBUFFEROBJECT_VALID(res);
    return res;
}
References duk_hbufferobject::buf, duk__init_object_parts(), DUK_ALLOC, DUK_ASSERT_HBUFFEROBJECT_VALID, DUK_MEMZERO, NULL, and duk_hbufferobject::obj.
duk_hcompiledfunction_alloc()
DUK_INTERNAL duk_hcompiledfunction * duk_hcompiledfunction_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 70 of file duktape-1.5.2/src-separate/duk_hobject_alloc.c.
{
    duk_hcompiledfunction *res;
    res = (duk_hcompiledfunction *) DUK_ALLOC(heap, sizeof(duk_hcompiledfunction));
    if (!res) {
        return NULL;
    }
    DUK_MEMZERO(res, sizeof(duk_hcompiledfunction));
    duk__init_object_parts(heap, &res->obj, hobject_flags);
#ifdef DUK_USE_EXPLICIT_NULL_INIT
#ifdef DUK_USE_HEAPPTR16
    /* NULL pointer is required to encode to zero, so memset is enough. */
#else
    res->data = NULL;
    res->funcs = NULL;
    res->bytecode = NULL;
#endif
#endif
    return res;
}
References duk_hcompiledfunction::bytecode, duk_hcompiledfunction::data, duk__init_object_parts(), DUK_ALLOC, DUK_MEMZERO, duk_hcompiledfunction::funcs, NULL, and duk_hcompiledfunction::obj.
duk_hnativefunction_alloc()
DUK_INTERNAL duk_hnativefunction * duk_hnativefunction_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 94 of file duktape-1.5.2/src-separate/duk_hobject_alloc.c.
{
    duk_hnativefunction *res;
    res = (duk_hnativefunction *) DUK_ALLOC(heap, sizeof(duk_hnativefunction));
    if (!res) {
        return NULL;
    }
    DUK_MEMZERO(res, sizeof(duk_hnativefunction));
    duk__init_object_parts(heap, &res->obj, hobject_flags);
#ifdef DUK_USE_EXPLICIT_NULL_INIT
    res->func = NULL;
#endif
    return res;
}
References duk__init_object_parts(), DUK_ALLOC, DUK_MEMZERO, duk_hnativefunction::func, NULL, and duk_hnativefunction::obj.
duk_hobject_alloc()
DUK_INTERNAL duk_hobject * duk_hobject_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 49 of file duktape-1.5.2/src-separate/duk_hobject_alloc.c.
{
    duk_hobject *res;
    DUK_ASSERT(heap != NULL);
    /* different memory layout, alloc size, and init */
    DUK_ASSERT((hobject_flags & DUK_HOBJECT_FLAG_COMPILEDFUNCTION) == 0);
    DUK_ASSERT((hobject_flags & DUK_HOBJECT_FLAG_NATIVEFUNCTION) == 0);
    DUK_ASSERT((hobject_flags & DUK_HOBJECT_FLAG_THREAD) == 0);
    res = (duk_hobject *) DUK_ALLOC(heap, sizeof(duk_hobject));
    if (!res) {
        return NULL;
    }
    DUK_MEMZERO(res, sizeof(duk_hobject));
    duk__init_object_parts(heap, res, hobject_flags);
    return res;
}
References duk__init_object_parts(), DUK_ALLOC, DUK_ASSERT, DUK_HOBJECT_FLAG_COMPILEDFUNCTION, DUK_HOBJECT_FLAG_NATIVEFUNCTION, DUK_HOBJECT_FLAG_THREAD, DUK_MEMZERO, and NULL.
duk_hthread_alloc()
DUK_INTERNAL duk_hthread * duk_hthread_alloc (duk_heap * heap, duk_uint_t hobject_flags)
Definition at line 139 of file duktape-1.5.2/src-separate/duk_hobject_alloc.c.
{
    duk_hthread *res;
    res = (duk_hthread *) DUK_ALLOC(heap, sizeof(duk_hthread));
    if (!res) {
        return NULL;
    }
    DUK_MEMZERO(res, sizeof(duk_hthread));
    duk__init_object_parts(heap, &res->obj, hobject_flags);
#ifdef DUK_USE_EXPLICIT_NULL_INIT
    res->ptr_curr_pc = NULL;
    res->heap = NULL;
    res->valstack = NULL;
    res->valstack_end = NULL;
    res->valstack_bottom = NULL;
    res->valstack_top = NULL;
    res->callstack = NULL;
    res->catchstack = NULL;
    res->resumer = NULL;
    res->compile_ctx = NULL,
#ifdef DUK_USE_HEAPPTR16
    res->strs16 = NULL;
#else
    res->strs = NULL;
#endif
    {
        int i;
        for (i = 0; i < DUK_NUM_BUILTINS; i++) {
            res->builtins[i] = NULL;
        }
    }
#endif
    /* when nothing is running, API calls are in non-strict mode */
    DUK_ASSERT(res->strict == 0);
    res->heap = heap;
    res->valstack_max = DUK_VALSTACK_DEFAULT_MAX;
    res->callstack_max = DUK_CALLSTACK_DEFAULT_MAX;
    res->catchstack_max = DUK_CATCHSTACK_DEFAULT_MAX;
    return res;
}
References duk_hthread::builtins, duk_hthread::callstack, duk_hthread::callstack_max, duk_hthread::catchstack, duk_hthread::catchstack_max, duk_hthread::compile_ctx, duk__init_object_parts(), DUK_ALLOC, DUK_ASSERT, DUK_CALLSTACK_DEFAULT_MAX, DUK_CATCHSTACK_DEFAULT_MAX, DUK_MEMZERO, DUK_NUM_BUILTINS, DUK_VALSTACK_DEFAULT_MAX, duk_hthread::heap, NULL, duk_hthread::obj, duk_hthread::ptr_curr_pc, duk_hthread::resumer, duk_hthread::strict, duk_hthread::strs, duk_hthread::valstack, duk_hthread::valstack_bottom, duk_hthread::valstack_end, duk_hthread::valstack_max, and duk_hthread::valstack_top.