Github User Fetcher: duk_error_macros.c File Reference
duk_error_macros.c File Reference
#include "duk_internal.h"
Macros
#define DUK__ERRFMT_BUFSIZE 256 /* size for formatting buffers */
Functions
DUK_INTERNAL void duk_err_handle_error_fmt (duk_hthread *thr, const char *filename, duk_uint_t line_and_code, const char *fmt,...)
DUK_INTERNAL void duk_err_handle_error (duk_hthread *thr, const char *filename, duk_uint_t line_and_code, const char *msg)
DUK_INTERNAL void duk_err_require_type_index (duk_hthread *thr, const char *filename, duk_int_t linenumber, duk_idx_t index, const char *expect_name)
DUK_INTERNAL void duk_err_range (duk_hthread *thr, const char *filename, duk_int_t linenumber, const char *message)
DUK_INTERNAL void duk_err_api_index (duk_hthread *thr, const char *filename, duk_int_t linenumber, duk_idx_t index)
DUK_INTERNAL void duk_err_api (duk_hthread *thr, const char *filename, duk_int_t linenumber, const char *message)
DUK_INTERNAL void duk_err_unimplemented_defmsg (duk_hthread *thr, const char *filename, duk_int_t linenumber)
DUK_INTERNAL void duk_err_internal_defmsg (duk_hthread *thr, const char *filename, duk_int_t linenumber)
DUK_INTERNAL void duk_err_internal (duk_hthread *thr, const char *filename, duk_int_t linenumber, const char *message)
DUK_INTERNAL void duk_err_alloc (duk_hthread *thr, const char *filename, duk_int_t linenumber, const char *message)
DUK_INTERNAL void duk_default_fatal_handler (duk_context *ctx, duk_errcode_t code, const char *msg)
DUK_INTERNAL void duk_default_panic_handler (duk_errcode_t code, const char *msg)
Macro Definition Documentation
DUK__ERRFMT_BUFSIZE
#define DUK__ERRFMT_BUFSIZE 256 /* size for formatting buffers */
Definition at line 7 of file duktape-1.5.2/src-separate/duk_error_macros.c.
Referenced by duk_err_handle_error_fmt().
Function Documentation
duk_default_fatal_handler()
DUK_INTERNAL void duk_default_fatal_handler (duk_context * ctx, duk_errcode_t code, const char * msg)
Definition at line 109 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    DUK_UNREF(ctx);
#if defined(DUK_USE_FILE_IO)
    DUK_FPRINTF(DUK_STDERR, "FATAL %ld: %s\n", (long) code, (const char *) (msg ? msg : "null"));
    DUK_FFLUSH(DUK_STDERR);
#else
    /* omit print */
#endif
    DUK_D(DUK_DPRINT("default fatal handler called, code %ld -> calling DUK_PANIC()", (long) code));
    DUK_PANIC(code, msg);
    DUK_UNREACHABLE();
}
References DUK_D, DUK_DPRINT, DUK_FFLUSH, DUK_FPRINTF, DUK_PANIC, DUK_STDERR, DUK_UNREACHABLE, and DUK_UNREF.
duk_default_panic_handler()
DUK_INTERNAL void duk_default_panic_handler (duk_errcode_t code, const char * msg)
Definition at line 127 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
#if defined(DUK_USE_FILE_IO)
    DUK_FPRINTF(DUK_STDERR, "PANIC %ld: %s ("
#if defined(DUK_USE_PANIC_ABORT)
                "calling abort"
#elif defined(DUK_USE_PANIC_EXIT)
                "calling exit"
#elif defined(DUK_USE_PANIC_SEGFAULT)
                "segfaulting on purpose"
#else
#error no DUK_USE_PANIC_xxx macro defined
#endif
                ")\n", (long) code, (const char *) (msg ? msg : "null"));
    DUK_FFLUSH(DUK_STDERR);
#else
    /* omit print */
    DUK_UNREF(code);
    DUK_UNREF(msg);
#endif
#if defined(DUK_USE_PANIC_ABORT)
    DUK_ABORT();
#elif defined(DUK_USE_PANIC_EXIT)
    DUK_EXIT(-1);
#elif defined(DUK_USE_PANIC_SEGFAULT)
    /* exit() afterwards to satisfy "noreturn" */
    DUK_CAUSE_SEGFAULT();  /* SCANBUILD: "Dereference of null pointer", normal */
    DUK_EXIT(-1);
#else
#error no DUK_USE_PANIC_xxx macro defined
#endif
    DUK_UNREACHABLE();
}
References DUK_ABORT, DUK_CAUSE_SEGFAULT, DUK_EXIT, DUK_FFLUSH, DUK_FPRINTF, DUK_STDERR, DUK_UNREACHABLE, DUK_UNREF, DUK_USE_PANIC_ABORT, and error().
duk_err_alloc()
DUK_INTERNAL void duk_err_alloc (duk_hthread * thr, const char * filename, duk_int_t linenumber, const char * message)
Definition at line 72 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    DUK_ERROR_RAW(thr, filename, linenumber, DUK_ERR_ALLOC_ERROR, message);
}
References DUK_ERR_ALLOC_ERROR, and DUK_ERROR_RAW.
duk_err_api()
DUK_INTERNAL void duk_err_api (duk_hthread * thr, const char * filename, duk_int_t linenumber, const char * message)
Definition at line 55 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    DUK_ERROR_RAW(thr, filename, linenumber, DUK_ERR_API_ERROR, message);
}
References DUK_ERR_API_ERROR, and DUK_ERROR_RAW.
duk_err_api_index()
DUK_INTERNAL void duk_err_api_index (duk_hthread * thr, const char * filename, duk_int_t linenumber, duk_idx_t index)
Definition at line 52 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    DUK_ERROR_RAW_FMT1(thr, filename, linenumber, DUK_ERR_API_ERROR, "invalid stack index %ld", (long) (index));
}
References DUK_ERR_API_ERROR, DUK_ERROR_RAW_FMT1, and index.
duk_err_handle_error()
DUK_INTERNAL void duk_err_handle_error (duk_hthread * thr, const char * filename, duk_uint_t line_and_code, const char * msg)
Definition at line 21 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    duk_err_create_and_throw(thr, (duk_errcode_t) (line_and_code >> 24), msg, filename, (duk_int_t) (line_and_code & 0x00ffffffL));
}
References duk_err_create_and_throw().
duk_err_handle_error_fmt()
DUK_INTERNAL void duk_err_handle_error_fmt (duk_hthread * thr, const char * filename, duk_uint_t line_and_code, const char * fmt, ...)
Definition at line 11 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    va_list ap;
    char msg[DUK__ERRFMT_BUFSIZE];
    va_start(ap, fmt);
    (void) DUK_VSNPRINTF(msg, sizeof(msg), fmt, ap);
    msg[sizeof(msg) - 1] = (char) 0;
    duk_err_create_and_throw(thr, (duk_errcode_t) (line_and_code >> 24), msg, filename, (duk_int_t) (line_and_code & 0x00ffffffL));
    va_end(ap);  /* dead code, but ensures portability (see Linux man page notes) */
}
References DUK__ERRFMT_BUFSIZE, duk_err_create_and_throw(), and DUK_VSNPRINTF.
duk_err_internal()
DUK_INTERNAL void duk_err_internal (duk_hthread * thr, const char * filename, duk_int_t linenumber, const char * message)
Definition at line 69 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    DUK_ERROR_RAW(thr, filename, linenumber, DUK_ERR_INTERNAL_ERROR, message);
}
References DUK_ERR_INTERNAL_ERROR, and DUK_ERROR_RAW.
duk_err_internal_defmsg()
DUK_INTERNAL void duk_err_internal_defmsg (duk_hthread * thr, const char * filename, duk_int_t linenumber)
Definition at line 66 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    DUK_ERROR_RAW(thr, filename, linenumber, DUK_ERR_INTERNAL_ERROR, DUK_STR_INTERNAL_ERROR);
}
References DUK_ERR_INTERNAL_ERROR, DUK_ERROR_RAW, and DUK_STR_INTERNAL_ERROR.
duk_err_range()
DUK_INTERNAL void duk_err_range (duk_hthread * thr, const char * filename, duk_int_t linenumber, const char * message)
Definition at line 49 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    DUK_ERROR_RAW(thr, filename, linenumber, DUK_ERR_RANGE_ERROR, message);
}
References DUK_ERR_RANGE_ERROR, and DUK_ERROR_RAW.
duk_err_require_type_index()
DUK_INTERNAL void duk_err_require_type_index (duk_hthread * thr, const char * filename, duk_int_t linenumber, duk_idx_t index, const char * expect_name)
Definition at line 44 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    DUK_ERROR_RAW_FMT3(thr, filename, linenumber, DUK_ERR_TYPE_ERROR, "%s required, found %s (stack index %ld)",
                       expect_name, duk_push_string_readable((duk_context *) thr, index), (long) index);
}
References DUK_ERR_TYPE_ERROR, DUK_ERROR_RAW_FMT3, duk_push_string_readable(), and index.
duk_err_unimplemented_defmsg()
DUK_INTERNAL void duk_err_unimplemented_defmsg (duk_hthread * thr, const char * filename, duk_int_t linenumber)
Definition at line 58 of file duktape-1.5.2/src-separate/duk_error_macros.c.
{
    DUK_ERROR_RAW(thr, filename, linenumber, DUK_ERR_UNIMPLEMENTED_ERROR, DUK_STR_UNIMPLEMENTED);
}
References DUK_ERR_UNIMPLEMENTED_ERROR, DUK_ERROR_RAW, and DUK_STR_UNIMPLEMENTED.