Github User Fetcher: fileio.c File Reference
fileio.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "duktape.h"
Functions
static int fileio_readfile (duk_context *ctx)
void fileio_register (duk_context *ctx)
Variables
static duk_function_list_entry fileio_funcs []
Function Documentation
fileio_readfile()
static int fileio_readfile (duk_context * ctx) static
Definition at line 11 of file duktape-1.8.0/examples/eventloop/fileio.c.
{
    const char *filename = duk_to_string(ctx, 0);
    FILE *f = NULL;
    long len;
    void *buf;
    size_t got;
    if (!filename) {
        goto error;
    }
    f = fopen(filename, "rb");
    if (!f) {
        goto error;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        goto error;
    }
    len = ftell(f);
    if (fseek(f, 0, SEEK_SET) != 0) {
        goto error;
    }
    buf = duk_push_fixed_buffer(ctx, (size_t) len);
    got = fread(buf, 1, len, f);
    if (got != (size_t) len) {
        goto error;
    }
    fclose(f);
    f = NULL;
    return 1;
 error:
    if (f) {
        fclose(f);
    }
    return DUK_RET_ERROR;
}
References duk_push_fixed_buffer, DUK_RET_ERROR, duk_to_string(), error(), fread(), and NULL.
fileio_register()
void fileio_register (duk_context * ctx)
Definition at line 62 of file duktape-1.8.0/examples/eventloop/fileio.c.
{
    /* Set global 'FileIo'. */
    duk_push_global_object(ctx);
    duk_push_object(ctx);
    duk_put_function_list(ctx, -1, fileio_funcs);
    duk_put_prop_string(ctx, -2, "FileIo");
    duk_pop(ctx);
}
References duk_pop(), duk_push_global_object(), duk_push_object(), duk_put_function_list(), duk_put_prop_string(), and fileio_funcs.
Referenced by main().
Variable Documentation
fileio_funcs
duk_function_list_entry fileio_funcs[] static
Initial value:
= {
    { "readfile", fileio_readfile, 1 },
    { NULL, NULL, 0 }
}
Definition at line 57 of file duktape-1.8.0/examples/eventloop/fileio.c.
{
    { "readfile", fileio_readfile, 1 },
    { NULL, NULL, 0 }
};
Referenced by fileio_register().