Github User Fetcher: duk_util.h File Reference
duk_util.h File Reference
Data Structures
struct duk_bitdecoder_ctx
struct duk_bitencoder_ctx
struct duk_bufwriter_ctx
Macros
#define DUK_UTIL_MIN_HASH_PRIME 17 /* must match genhashsizes.py */
#define DUK_UTIL_GET_HASH_PROBE_STEP(hash) (duk_util_probe_steps[(hash) & 0x1f])
#define DUK_RAW_WRITE_U8(ptr, val)
#define DUK_RAW_WRITE_U16_BE(ptr, val) duk_raw_write_u16_be(&(ptr), (duk_uint16_t) (val))
#define DUK_RAW_WRITE_U32_BE(ptr, val) duk_raw_write_u32_be(&(ptr), (duk_uint32_t) (val))
#define DUK_RAW_WRITE_DOUBLE_BE(ptr, val) duk_raw_write_double_be(&(ptr), (duk_double_t) (val))
#define DUK_RAW_WRITE_XUTF8(ptr, val)
#define DUK_RAW_WRITE_CESU8(ptr, val)
#define DUK_RAW_READ_U8(ptr) ((duk_uint8_t) (*(ptr)++))
#define DUK_RAW_READ_U16_BE(ptr) duk_raw_read_u16_be(&(ptr));
#define DUK_RAW_READ_U32_BE(ptr) duk_raw_read_u32_be(&(ptr));
#define DUK_RAW_READ_DOUBLE_BE(ptr) duk_raw_read_double_be(&(ptr));
#define DUK_BW_SPARE_ADD 64
#define DUK_BW_SPARE_SHIFT 4 /* 2^4 -> 1/16 = 6.25% spare */
#define DUK_BW_INIT_PUSHBUF(thr, bw_ctx, sz)
#define DUK_BW_INIT_WITHBUF(thr, bw_ctx, buf)
#define DUK_BW_COMPACT(thr, bw_ctx)
#define DUK_BW_PUSH_AS_STRING(thr, bw_ctx)
#define DUK_BW_ASSERT_VALID_EXPR(thr, bw_ctx)
#define DUK_BW_ASSERT_VALID(thr, bw_ctx)
#define DUK_BW_GET_PTR(thr, bw_ctx) ((bw_ctx)->p)
#define DUK_BW_SET_PTR(thr, bw_ctx, ptr)
#define DUK_BW_ADD_PTR(thr, bw_ctx, delta)
#define DUK_BW_GET_BASEPTR(thr, bw_ctx) ((bw_ctx)->p_base)
#define DUK_BW_GET_LIMITPTR(thr, bw_ctx) ((bw_ctx)->p_limit)
#define DUK_BW_GET_SIZE(thr, bw_ctx) ((duk_size_t) ((bw_ctx)->p - (bw_ctx)->p_base))
#define DUK_BW_SET_SIZE(thr, bw_ctx, sz)
#define DUK_BW_RESET_SIZE(thr, bw_ctx)
#define DUK_BW_GET_BUFFER(thr, bw_ctx) ((bw_ctx)->buf)
#define DUK_BW_ENSURE(thr, bw_ctx, sz)
#define DUK_BW_ENSURE_RAW(thr, bw_ctx, sz, ptr)
#define DUK_BW_ENSURE_GETPTR(thr, bw_ctx, sz) DUK_BW_ENSURE_RAW((thr), (bw_ctx), (sz), (bw_ctx)->p)
#define DUK_BW_ASSERT_SPACE_EXPR(thr, bw_ctx, sz)
#define DUK_BW_ASSERT_SPACE(thr, bw_ctx, sz)
#define DUK_BW_SETPTR_AND_COMPACT(thr, bw_ctx, ptr)
#define DUK_BW_WRITE_RAW_U8(thr, bw_ctx, val)
#define DUK_BW_WRITE_RAW_U8_2(thr, bw_ctx, val1, val2)
#define DUK_BW_WRITE_RAW_U8_3(thr, bw_ctx, val1, val2, val3)
#define DUK_BW_WRITE_RAW_U8_4(thr, bw_ctx, val1, val2, val3, val4)
#define DUK_BW_WRITE_RAW_U8_5(thr, bw_ctx, val1, val2, val3, val4, val5)
#define DUK_BW_WRITE_RAW_U8_6(thr, bw_ctx, val1, val2, val3, val4, val5, val6)
#define DUK_BW_WRITE_RAW_XUTF8(thr, bw_ctx, cp)
#define DUK_BW_WRITE_RAW_CESU8(thr, bw_ctx, cp)
#define DUK_BW_WRITE_RAW_BYTES(thr, bw_ctx, valptr, valsz)
#define DUK_BW_WRITE_RAW_CSTRING(thr, bw_ctx, val)
#define DUK_BW_WRITE_RAW_HSTRING(thr, bw_ctx, val)
#define DUK_BW_WRITE_RAW_HBUFFER(thr, bw_ctx, val)
#define DUK_BW_WRITE_RAW_HBUFFER_FIXED(thr, bw_ctx, val)
#define DUK_BW_WRITE_RAW_HBUFFER_DYNAMIC(thr, bw_ctx, val)
#define DUK_BW_WRITE_RAW_SLICE(thr, bw, dst_off, dst_len) duk_bw_write_raw_slice((thr), (bw), (dst_off), (dst_len))
#define DUK_BW_INSERT_RAW_BYTES(thr, bw, dst_off, buf, len) duk_bw_insert_raw_bytes((thr), (bw), (dst_off), (buf), (len))
#define DUK_BW_INSERT_RAW_SLICE(thr, bw, dst_off, src_off, len) duk_bw_insert_raw_slice((thr), (bw), (dst_off), (src_off), (len))
#define DUK_BW_INSERT_RAW_AREA(thr, bw, off, len) duk_bw_insert_raw_area((thr), (bw), (off), (len))
#define DUK_BW_REMOVE_RAW_SLICE(thr, bw, off, len) duk_bw_remove_raw_slice((thr), (bw), (off), (len))
#define DUK_BW_WRITE_ENSURE_U8(thr, bw_ctx, val)
#define DUK_BW_WRITE_ENSURE_U8_2(thr, bw_ctx, val1, val2)
#define DUK_BW_WRITE_ENSURE_U8_3(thr, bw_ctx, val1, val2, val3)
#define DUK_BW_WRITE_ENSURE_U8_4(thr, bw_ctx, val1, val2, val3, val4)
#define DUK_BW_WRITE_ENSURE_U8_5(thr, bw_ctx, val1, val2, val3, val4, val5)
#define DUK_BW_WRITE_ENSURE_U8_6(thr, bw_ctx, val1, val2, val3, val4, val5, val6)
#define DUK_BW_WRITE_ENSURE_XUTF8(thr, bw_ctx, cp)
#define DUK_BW_WRITE_ENSURE_CESU8(thr, bw_ctx, cp)
#define DUK_BW_WRITE_ENSURE_BYTES(thr, bw_ctx, valptr, valsz)
#define DUK_BW_WRITE_ENSURE_CSTRING(thr, bw_ctx, val)
#define DUK_BW_WRITE_ENSURE_HSTRING(thr, bw_ctx, val)
#define DUK_BW_WRITE_ENSURE_HBUFFER(thr, bw_ctx, val)
#define DUK_BW_WRITE_ENSURE_HBUFFER_FIXED(thr, bw_ctx, val)
#define DUK_BW_WRITE_ENSURE_HBUFFER_DYNAMIC(thr, bw_ctx, val)
#define DUK_BW_WRITE_ENSURE_SLICE(thr, bw, dst_off, dst_len) duk_bw_write_ensure_slice((thr), (bw), (dst_off), (dst_len))
#define DUK_BW_INSERT_ENSURE_BYTES(thr, bw, dst_off, buf, len) duk_bw_insert_ensure_bytes((thr), (bw), (dst_off), (buf), (len))
#define DUK_BW_INSERT_ENSURE_SLICE(thr, bw, dst_off, src_off, len) duk_bw_insert_ensure_slice((thr), (bw), (dst_off), (src_off), (len))
#define DUK_BW_INSERT_ENSURE_AREA(thr, bw, off, len)
#define DUK_BW_REMOVE_ENSURE_SLICE(thr, bw, off, len)
Functions
DUK_INTERNAL_DECL duk_int32_t duk_bd_decode (duk_bitdecoder_ctx *ctx, duk_small_int_t bits)
DUK_INTERNAL_DECL duk_small_int_t duk_bd_decode_flag (duk_bitdecoder_ctx *ctx)
DUK_INTERNAL_DECL duk_int32_t duk_bd_decode_flagged (duk_bitdecoder_ctx *ctx, duk_small_int_t bits, duk_int32_t def_value)
DUK_INTERNAL_DECL void duk_be_encode (duk_bitencoder_ctx *ctx, duk_uint32_t data, duk_small_int_t bits)
DUK_INTERNAL_DECL void duk_be_finish (duk_bitencoder_ctx *ctx)
DUK_INTERNAL_DECL duk_uint32_t duk_util_tinyrandom_get_bits (duk_hthread *thr, duk_small_int_t n)
DUK_INTERNAL_DECL duk_double_t duk_util_tinyrandom_get_double (duk_hthread *thr)
DUK_INTERNAL_DECL void duk_bw_init (duk_hthread *thr, duk_bufwriter_ctx *bw_ctx, duk_hbuffer_dynamic *h_buf)
DUK_INTERNAL_DECL void duk_bw_init_pushbuf (duk_hthread *thr, duk_bufwriter_ctx *bw_ctx, duk_size_t buf_size)
DUK_INTERNAL_DECL duk_uint8_t * duk_bw_resize (duk_hthread *thr, duk_bufwriter_ctx *bw_ctx, duk_size_t sz)
DUK_INTERNAL_DECL void duk_bw_compact (duk_hthread *thr, duk_bufwriter_ctx *bw_ctx)
DUK_INTERNAL_DECL void duk_bw_write_raw_slice (duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t src_off, duk_size_t len)
DUK_INTERNAL_DECL void duk_bw_write_ensure_slice (duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t src_off, duk_size_t len)
DUK_INTERNAL_DECL void duk_bw_insert_raw_bytes (duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t dst_off, const duk_uint8_t *buf, duk_size_t len)
DUK_INTERNAL_DECL void duk_bw_insert_ensure_bytes (duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t dst_off, const duk_uint8_t *buf, duk_size_t len)
DUK_INTERNAL_DECL void duk_bw_insert_raw_slice (duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t dst_off, duk_size_t src_off, duk_size_t len)
DUK_INTERNAL_DECL void duk_bw_insert_ensure_slice (duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t dst_off, duk_size_t src_off, duk_size_t len)
DUK_INTERNAL_DECL duk_uint8_t * duk_bw_insert_raw_area (duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t off, duk_size_t len)
DUK_INTERNAL_DECL duk_uint8_t * duk_bw_insert_ensure_area (duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t off, duk_size_t len)
DUK_INTERNAL_DECL void duk_bw_remove_raw_slice (duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t off, duk_size_t len)
DUK_INTERNAL_DECL duk_uint16_t duk_raw_read_u16_be (duk_uint8_t **p)
DUK_INTERNAL_DECL duk_uint32_t duk_raw_read_u32_be (duk_uint8_t **p)
DUK_INTERNAL_DECL duk_double_t duk_raw_read_double_be (duk_uint8_t **p)
DUK_INTERNAL_DECL void duk_raw_write_u16_be (duk_uint8_t **p, duk_uint16_t val)
DUK_INTERNAL_DECL void duk_raw_write_u32_be (duk_uint8_t **p, duk_uint32_t val)
DUK_INTERNAL_DECL void duk_raw_write_double_be (duk_uint8_t **p, duk_double_t val)
Variables
DUK_INTERNAL_DECL const duk_uint8_t duk_lc_digits [36]
DUK_INTERNAL_DECL const duk_uint8_t duk_uc_nybbles [16]
DUK_INTERNAL_DECL const duk_int8_t duk_hex_dectab [256]
Macro Definition Documentation
DUK_BW_ADD_PTR
#define DUK_BW_ADD_PTR (thr, bw_ctx, delta)
Value:
        do { \
        (bw_ctx)->p += (delta); \
    } while (0)
Definition at line 170 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_ADD_PTR(thr,bw_ctx,delta) do { \
        (bw_ctx)->p += (delta); \
    } while (0)
DUK_BW_ASSERT_SPACE
#define DUK_BW_ASSERT_SPACE (thr, bw_ctx, sz)
Value:
        do { \
        DUK_BW_ASSERT_SPACE_EXPR((thr), (bw_ctx), (sz)); \
    } while (0)
Definition at line 212 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_ASSERT_SPACE(thr,bw_ctx,sz) do { \
        DUK_BW_ASSERT_SPACE_EXPR((thr), (bw_ctx), (sz)); \
    } while (0)
DUK_BW_ASSERT_SPACE_EXPR
#define DUK_BW_ASSERT_SPACE_EXPR (thr, bw_ctx, sz)
Value:
    (DUK_BW_ASSERT_VALID_EXPR((thr), (bw_ctx)), \
     DUK_ASSERT_EXPR((duk_size_t) ((bw_ctx)->p_limit - (bw_ctx)->p) >= (duk_size_t) (sz)))
Definition at line 209 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_ASSERT_SPACE_EXPR(thr,bw_ctx,sz) \
    (DUK_BW_ASSERT_VALID_EXPR((thr), (bw_ctx)), \
     DUK_ASSERT_EXPR((duk_size_t) ((bw_ctx)->p_limit - (bw_ctx)->p) >= (duk_size_t) (sz)))
DUK_BW_ASSERT_VALID
#define DUK_BW_ASSERT_VALID (thr, bw_ctx)
Value:
        do { \
        DUK_BW_ASSERT_VALID_EXPR((thr), (bw_ctx)); \
    } while (0)
Definition at line 159 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_ASSERT_VALID(thr,bw_ctx) do { \
        DUK_BW_ASSERT_VALID_EXPR((thr), (bw_ctx)); \
    } while (0)
DUK_BW_ASSERT_VALID_EXPR
#define DUK_BW_ASSERT_VALID_EXPR (thr, bw_ctx)
Value:
    DUK_ASSERT_EXPR((bw_ctx) != NULL && \
                    (bw_ctx)->buf != NULL && \
            ((DUK_HBUFFER_DYNAMIC_GET_SIZE((bw_ctx)->buf) == 0) || \
                ((bw_ctx)->p != NULL && \
                         (bw_ctx)->p_base != NULL && \
                         (bw_ctx)->p_limit != NULL && \
                         (bw_ctx)->p_limit >= (bw_ctx)->p_base && \
                         (bw_ctx)->p >= (bw_ctx)->p_base && \
                         (bw_ctx)->p <= (bw_ctx)->p_limit)))
Definition at line 149 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_ASSERT_VALID_EXPR(thr,bw_ctx) \
    DUK_ASSERT_EXPR((bw_ctx) != NULL && \
                    (bw_ctx)->buf != NULL && \
            ((DUK_HBUFFER_DYNAMIC_GET_SIZE((bw_ctx)->buf) == 0) || \
                ((bw_ctx)->p != NULL && \
                         (bw_ctx)->p_base != NULL && \
                         (bw_ctx)->p_limit != NULL && \
                         (bw_ctx)->p_limit >= (bw_ctx)->p_base && \
                         (bw_ctx)->p >= (bw_ctx)->p_base && \
                         (bw_ctx)->p <= (bw_ctx)->p_limit)))
DUK_BW_COMPACT
#define DUK_BW_COMPACT (thr, bw_ctx)
Value:
        do { \
        /* Make underlying buffer compact to match DUK_BW_GET_SIZE(). */ \
        duk_bw_compact((thr), (bw_ctx)); \
    } while (0)
Definition at line 135 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_COMPACT(thr,bw_ctx) do { \
        /* Make underlying buffer compact to match DUK_BW_GET_SIZE(). */ \
        duk_bw_compact((thr), (bw_ctx)); \
    } while (0)
DUK_BW_ENSURE
#define DUK_BW_ENSURE (thr, bw_ctx, sz)
Value:
        do { \
        duk_size_t duk__sz, duk__space; \
        DUK_BW_ASSERT_VALID((thr), (bw_ctx)); \
        duk__sz = (sz); \
        duk__space = (duk_size_t) ((bw_ctx)->p_limit - (bw_ctx)->p); \
        if (duk__space < duk__sz) { \
            (void) duk_bw_resize((thr), (bw_ctx), duk__sz); \
        } \
    } while (0)
Definition at line 192 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_ENSURE(thr,bw_ctx,sz) do { \
        duk_size_t duk__sz, duk__space; \
        DUK_BW_ASSERT_VALID((thr), (bw_ctx)); \
        duk__sz = (sz); \
        duk__space = (duk_size_t) ((bw_ctx)->p_limit - (bw_ctx)->p); \
        if (duk__space < duk__sz) { \
            (void) duk_bw_resize((thr), (bw_ctx), duk__sz); \
        } \
    } while (0)
DUK_BW_ENSURE_GETPTR
#define DUK_BW_ENSURE_GETPTR (thr, bw_ctx, sz) DUK_BW_ENSURE_RAW((thr), (bw_ctx), (sz), (bw_ctx)->p)
Definition at line 207 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_ENSURE_GETPTR(thr,bw_ctx,sz) \
    DUK_BW_ENSURE_RAW((thr), (bw_ctx), (sz), (bw_ctx)->p)
DUK_BW_ENSURE_RAW
#define DUK_BW_ENSURE_RAW (thr, bw_ctx, sz, ptr)
Value:
    (((duk_size_t) ((bw_ctx)->p_limit - (ptr)) >= (sz)) ? \
     (ptr) : \
     ((bw_ctx)->p = (ptr), duk_bw_resize((thr),(bw_ctx),(sz))))
Definition at line 203 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_ENSURE_RAW(thr,bw_ctx,sz,ptr) \
    (((duk_size_t) ((bw_ctx)->p_limit - (ptr)) >= (sz)) ? \
     (ptr) : \
     ((bw_ctx)->p = (ptr), duk_bw_resize((thr),(bw_ctx),(sz))))
DUK_BW_GET_BASEPTR
#define DUK_BW_GET_BASEPTR (thr, bw_ctx) ((bw_ctx)->p_base)
Definition at line 173 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_GET_BASEPTR(thr,bw_ctx) \
    ((bw_ctx)->p_base)
DUK_BW_GET_BUFFER
#define DUK_BW_GET_BUFFER (thr, bw_ctx) ((bw_ctx)->buf)
Definition at line 187 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_GET_BUFFER(thr,bw_ctx) \
    ((bw_ctx)->buf)
DUK_BW_GET_LIMITPTR
#define DUK_BW_GET_LIMITPTR (thr, bw_ctx) ((bw_ctx)->p_limit)
Definition at line 175 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_GET_LIMITPTR(thr,bw_ctx) \
    ((bw_ctx)->p_limit)
DUK_BW_GET_PTR
#define DUK_BW_GET_PTR (thr, bw_ctx) ((bw_ctx)->p)
Definition at line 165 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_GET_PTR(thr,bw_ctx) \
    ((bw_ctx)->p)
DUK_BW_GET_SIZE
#define DUK_BW_GET_SIZE (thr, bw_ctx) ((duk_size_t) ((bw_ctx)->p - (bw_ctx)->p_base))
Definition at line 177 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_GET_SIZE(thr,bw_ctx) \
    ((duk_size_t) ((bw_ctx)->p - (bw_ctx)->p_base))
DUK_BW_INIT_PUSHBUF
#define DUK_BW_INIT_PUSHBUF (thr, bw_ctx, sz)
Value:
        do { \
        duk_bw_init_pushbuf((thr), (bw_ctx), (sz)); \
    } while (0)
Definition at line 129 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_INIT_PUSHBUF(thr,bw_ctx,sz) do { \
        duk_bw_init_pushbuf((thr), (bw_ctx), (sz)); \
    } while (0)
DUK_BW_INIT_WITHBUF
#define DUK_BW_INIT_WITHBUF (thr, bw_ctx, buf)
Value:
        do { \
        duk_bw_init((thr), (bw_ctx), (buf)); \
    } while (0)
Definition at line 132 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_INIT_WITHBUF(thr,bw_ctx,buf) do { \
        duk_bw_init((thr), (bw_ctx), (buf)); \
    } while (0)
DUK_BW_INSERT_ENSURE_AREA
#define DUK_BW_INSERT_ENSURE_AREA (thr, bw, off, len)
Value:
    /* Evaluates to (duk_uint8_t *) pointing to start of area. */ \
    duk_bw_insert_ensure_area((thr), (bw), (off), (len))
Definition at line 454 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_INSERT_ENSURE_AREA(thr,bw,off,len) \
    /* Evaluates to (duk_uint8_t *) pointing to start of area. */ \
    duk_bw_insert_ensure_area((thr), (bw), (off), (len))
DUK_BW_INSERT_ENSURE_BYTES
#define DUK_BW_INSERT_ENSURE_BYTES (thr, bw, dst_off, buf, len) duk_bw_insert_ensure_bytes((thr), (bw), (dst_off), (buf), (len))
Definition at line 450 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_INSERT_ENSURE_BYTES(thr,bw,dst_off,buf,len) \
    duk_bw_insert_ensure_bytes((thr), (bw), (dst_off), (buf), (len))
DUK_BW_INSERT_ENSURE_SLICE
#define DUK_BW_INSERT_ENSURE_SLICE (thr, bw, dst_off, src_off, len) duk_bw_insert_ensure_slice((thr), (bw), (dst_off), (src_off), (len))
Definition at line 452 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_INSERT_ENSURE_SLICE(thr,bw,dst_off,src_off,len) \
    duk_bw_insert_ensure_slice((thr), (bw), (dst_off), (src_off), (len))
DUK_BW_INSERT_RAW_AREA
#define DUK_BW_INSERT_RAW_AREA (thr, bw, off, len) duk_bw_insert_raw_area((thr), (bw), (off), (len))
Definition at line 359 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_INSERT_RAW_AREA(thr,bw,off,len) \
    duk_bw_insert_raw_area((thr), (bw), (off), (len))
DUK_BW_INSERT_RAW_BYTES
#define DUK_BW_INSERT_RAW_BYTES (thr, bw, dst_off, buf, len) duk_bw_insert_raw_bytes((thr), (bw), (dst_off), (buf), (len))
Definition at line 346 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_INSERT_RAW_BYTES(thr,bw,dst_off,buf,len) \
    duk_bw_insert_raw_bytes((thr), (bw), (dst_off), (buf), (len))
DUK_BW_INSERT_RAW_SLICE
#define DUK_BW_INSERT_RAW_SLICE (thr, bw, dst_off, src_off, len) duk_bw_insert_raw_slice((thr), (bw), (dst_off), (src_off), (len))
Definition at line 352 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_INSERT_RAW_SLICE(thr,bw,dst_off,src_off,len) \
    duk_bw_insert_raw_slice((thr), (bw), (dst_off), (src_off), (len))
DUK_BW_PUSH_AS_STRING
#define DUK_BW_PUSH_AS_STRING (thr, bw_ctx)
Value:
        do { \
        duk_push_lstring((duk_context *) (thr), \
                         (const char *) (bw_ctx)->p_base, \
                         (duk_size_t) ((bw_ctx)->p - (bw_ctx)->p_base)); \
    } while (0)
Definition at line 139 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_PUSH_AS_STRING(thr,bw_ctx) do { \
        duk_push_lstring((duk_context *) (thr), \
                         (const char *) (bw_ctx)->p_base, \
                         (duk_size_t) ((bw_ctx)->p - (bw_ctx)->p_base)); \
    } while (0)
DUK_BW_REMOVE_ENSURE_SLICE
#define DUK_BW_REMOVE_ENSURE_SLICE (thr, bw, off, len)
Value:
    /* No difference between raw/ensure because the buffer shrinks. */ \
    DUK_BW_REMOVE_RAW_SLICE((thr), (bw), (off), (len))
Definition at line 457 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_REMOVE_ENSURE_SLICE(thr,bw,off,len) \
    /* No difference between raw/ensure because the buffer shrinks. */ \
    DUK_BW_REMOVE_RAW_SLICE((thr), (bw), (off), (len))
DUK_BW_REMOVE_RAW_SLICE
#define DUK_BW_REMOVE_RAW_SLICE (thr, bw, off, len) duk_bw_remove_raw_slice((thr), (bw), (off), (len))
Definition at line 363 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_REMOVE_RAW_SLICE(thr,bw,off,len) \
    duk_bw_remove_raw_slice((thr), (bw), (off), (len))
DUK_BW_RESET_SIZE
#define DUK_BW_RESET_SIZE (thr, bw_ctx)
Value:
        do { \
        /* Reset to zero size, keep current limit. */ \
        (bw_ctx)->p = (bw_ctx)->p_base; \
    } while (0)
Definition at line 183 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_RESET_SIZE(thr,bw_ctx) do { \
        /* Reset to zero size, keep current limit. */ \
        (bw_ctx)->p = (bw_ctx)->p_base; \
    } while (0)
DUK_BW_SET_PTR
#define DUK_BW_SET_PTR (thr, bw_ctx, ptr)
Value:
        do { \
        (bw_ctx)->p = (ptr); \
    } while (0)
Definition at line 167 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_SET_PTR(thr,bw_ctx,ptr) do { \
        (bw_ctx)->p = (ptr); \
    } while (0)
DUK_BW_SET_SIZE
#define DUK_BW_SET_SIZE (thr, bw_ctx, sz)
Value:
        do { \
        DUK_ASSERT((duk_size_t) (sz) <= (duk_size_t) ((bw_ctx)->p - (bw_ctx)->p_base)); \
        (bw_ctx)->p = (bw_ctx)->p_base + (sz); \
    } while (0)
Definition at line 179 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_SET_SIZE(thr,bw_ctx,sz) do { \
        DUK_ASSERT((duk_size_t) (sz) <= (duk_size_t) ((bw_ctx)->p - (bw_ctx)->p_base)); \
        (bw_ctx)->p = (bw_ctx)->p_base + (sz); \
    } while (0)
DUK_BW_SETPTR_AND_COMPACT
#define DUK_BW_SETPTR_AND_COMPACT (thr, bw_ctx, ptr)
Value:
        do { \
        (bw_ctx)->p = (ptr); \
        duk_bw_compact((thr), (bw_ctx)); \
    } while (0)
Definition at line 218 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_SETPTR_AND_COMPACT(thr,bw_ctx,ptr) do { \
        (bw_ctx)->p = (ptr); \
        duk_bw_compact((thr), (bw_ctx)); \
    } while (0)
DUK_BW_SPARE_ADD
#define DUK_BW_SPARE_ADD 64
Definition at line 124 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_BW_SPARE_SHIFT
#define DUK_BW_SPARE_SHIFT 4 /* 2^4 -> 1/16 = 6.25% spare */
Definition at line 125 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_BW_WRITE_ENSURE_BYTES
#define DUK_BW_WRITE_ENSURE_BYTES (thr, bw_ctx, valptr, valsz)
Value:
        do { \
        const void *duk__valptr; \
        duk_size_t duk__valsz; \
        duk__valptr = (const void *) (valptr); \
        duk__valsz = (duk_size_t) (valsz); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__valsz); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), duk__valptr, duk__valsz); \
        (bw_ctx)->p += duk__valsz; \
    } while (0)
Definition at line 401 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_BYTES(thr,bw_ctx,valptr,valsz) do { \
        const void *duk__valptr; \
        duk_size_t duk__valsz; \
        duk__valptr = (const void *) (valptr); \
        duk__valsz = (duk_size_t) (valsz); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__valsz); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), duk__valptr, duk__valsz); \
        (bw_ctx)->p += duk__valsz; \
    } while (0)
DUK_BW_WRITE_ENSURE_CESU8
#define DUK_BW_WRITE_ENSURE_CESU8 (thr, bw_ctx, cp)
Value:
        do { \
        DUK_BW_ENSURE((thr), (bw_ctx), DUK_UNICODE_MAX_CESU8_LENGTH); \
        DUK_BW_WRITE_RAW_CESU8((thr), (bw_ctx), (cp)); \
    } while (0)
Definition at line 396 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_CESU8(thr,bw_ctx,cp) do { \
        DUK_BW_ENSURE((thr), (bw_ctx), DUK_UNICODE_MAX_CESU8_LENGTH); \
        DUK_BW_WRITE_RAW_CESU8((thr), (bw_ctx), (cp)); \
    } while (0)
DUK_BW_WRITE_ENSURE_CSTRING
#define DUK_BW_WRITE_ENSURE_CSTRING (thr, bw_ctx, val)
Value:
        do { \
        const duk_uint8_t *duk__val; \
        duk_size_t duk__val_len; \
        duk__val = (const duk_uint8_t *) (val); \
        duk__val_len = DUK_STRLEN((const char *) duk__val); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) duk__val, duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 410 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_CSTRING(thr,bw_ctx,val) do { \
        const duk_uint8_t *duk__val; \
        duk_size_t duk__val_len; \
        duk__val = (const duk_uint8_t *) (val); \
        duk__val_len = DUK_STRLEN((const char *) duk__val); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) duk__val, duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_ENSURE_HBUFFER
#define DUK_BW_WRITE_ENSURE_HBUFFER (thr, bw_ctx, val)
Value:
        do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_GET_SIZE((val)); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 426 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_HBUFFER(thr,bw_ctx,val) do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_GET_SIZE((val)); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_ENSURE_HBUFFER_DYNAMIC
#define DUK_BW_WRITE_ENSURE_HBUFFER_DYNAMIC (thr, bw_ctx, val)
Value:
        do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_DYNAMIC_GET_SIZE((val)); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_DYNAMIC_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 440 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_HBUFFER_DYNAMIC(thr,bw_ctx,val) do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_DYNAMIC_GET_SIZE((val)); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_DYNAMIC_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_ENSURE_HBUFFER_FIXED
#define DUK_BW_WRITE_ENSURE_HBUFFER_FIXED (thr, bw_ctx, val)
Value:
        do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_FIXED_GET_SIZE((val)); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_FIXED_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 433 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_HBUFFER_FIXED(thr,bw_ctx,val) do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_FIXED_GET_SIZE((val)); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_FIXED_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_ENSURE_HSTRING
#define DUK_BW_WRITE_ENSURE_HSTRING (thr, bw_ctx, val)
Value:
        do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HSTRING_GET_BYTELEN((val)); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HSTRING_GET_DATA((val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 419 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_HSTRING(thr,bw_ctx,val) do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HSTRING_GET_BYTELEN((val)); \
        DUK_BW_ENSURE((thr), (bw_ctx), duk__val_len); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HSTRING_GET_DATA((val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_ENSURE_SLICE
#define DUK_BW_WRITE_ENSURE_SLICE (thr, bw, dst_off, dst_len) duk_bw_write_ensure_slice((thr), (bw), (dst_off), (dst_len))
Definition at line 448 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_SLICE(thr,bw,dst_off,dst_len) \
    duk_bw_write_ensure_slice((thr), (bw), (dst_off), (dst_len))
DUK_BW_WRITE_ENSURE_U8
#define DUK_BW_WRITE_ENSURE_U8 (thr, bw_ctx, val)
Value:
        do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 1); \
        DUK_BW_WRITE_RAW_U8((thr), (bw_ctx), (val)); \
    } while (0)
Definition at line 368 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_U8(thr,bw_ctx,val) do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 1); \
        DUK_BW_WRITE_RAW_U8((thr), (bw_ctx), (val)); \
    } while (0)
DUK_BW_WRITE_ENSURE_U8_2
#define DUK_BW_WRITE_ENSURE_U8_2 (thr, bw_ctx, val1, val2)
Value:
        do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 2); \
        DUK_BW_WRITE_RAW_U8_2((thr), (bw_ctx), (val1), (val2)); \
    } while (0)
Definition at line 372 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_U8_2(thr,bw_ctx,val1,val2) do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 2); \
        DUK_BW_WRITE_RAW_U8_2((thr), (bw_ctx), (val1), (val2)); \
    } while (0)
DUK_BW_WRITE_ENSURE_U8_3
#define DUK_BW_WRITE_ENSURE_U8_3 (thr, bw_ctx, val1, val2, val3)
Value:
        do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 3); \
        DUK_BW_WRITE_RAW_U8_3((thr), (bw_ctx), (val1), (val2), (val3)); \
    } while (0)
Definition at line 376 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_U8_3(thr,bw_ctx,val1,val2,val3) do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 3); \
        DUK_BW_WRITE_RAW_U8_3((thr), (bw_ctx), (val1), (val2), (val3)); \
    } while (0)
DUK_BW_WRITE_ENSURE_U8_4
#define DUK_BW_WRITE_ENSURE_U8_4 (thr, bw_ctx, val1, val2, val3, val4)
Value:
        do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 4); \
        DUK_BW_WRITE_RAW_U8_4((thr), (bw_ctx), (val1), (val2), (val3), (val4)); \
    } while (0)
Definition at line 380 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_U8_4(thr,bw_ctx,val1,val2,val3,val4) do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 4); \
        DUK_BW_WRITE_RAW_U8_4((thr), (bw_ctx), (val1), (val2), (val3), (val4)); \
    } while (0)
DUK_BW_WRITE_ENSURE_U8_5
#define DUK_BW_WRITE_ENSURE_U8_5 (thr, bw_ctx, val1, val2, val3, val4, val5)
Value:
        do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 5); \
        DUK_BW_WRITE_RAW_U8_5((thr), (bw_ctx), (val1), (val2), (val3), (val4), (val5)); \
    } while (0)
Definition at line 384 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_U8_5(thr,bw_ctx,val1,val2,val3,val4,val5) do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 5); \
        DUK_BW_WRITE_RAW_U8_5((thr), (bw_ctx), (val1), (val2), (val3), (val4), (val5)); \
    } while (0)
DUK_BW_WRITE_ENSURE_U8_6
#define DUK_BW_WRITE_ENSURE_U8_6 (thr, bw_ctx, val1, val2, val3, val4, val5, val6)
Value:
        do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 6); \
        DUK_BW_WRITE_RAW_U8_6((thr), (bw_ctx), (val1), (val2), (val3), (val4), (val5), (val6)); \
    } while (0)
Definition at line 388 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_U8_6(thr,bw_ctx,val1,val2,val3,val4,val5,val6) do { \
        DUK_BW_ENSURE((thr), (bw_ctx), 6); \
        DUK_BW_WRITE_RAW_U8_6((thr), (bw_ctx), (val1), (val2), (val3), (val4), (val5), (val6)); \
    } while (0)
DUK_BW_WRITE_ENSURE_XUTF8
#define DUK_BW_WRITE_ENSURE_XUTF8 (thr, bw_ctx, cp)
Value:
        do { \
        DUK_BW_ENSURE((thr), (bw_ctx), DUK_UNICODE_MAX_XUTF8_LENGTH); \
        DUK_BW_WRITE_RAW_XUTF8((thr), (bw_ctx), (cp)); \
    } while (0)
Definition at line 392 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_ENSURE_XUTF8(thr,bw_ctx,cp) do { \
        DUK_BW_ENSURE((thr), (bw_ctx), DUK_UNICODE_MAX_XUTF8_LENGTH); \
        DUK_BW_WRITE_RAW_XUTF8((thr), (bw_ctx), (cp)); \
    } while (0)
DUK_BW_WRITE_RAW_BYTES
#define DUK_BW_WRITE_RAW_BYTES (thr, bw_ctx, valptr, valsz)
Value:
        do { \
        const void *duk__valptr; \
        duk_size_t duk__valsz; \
        duk__valptr = (const void *) (valptr); \
        duk__valsz = (duk_size_t) (valsz); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), duk__valptr, duk__valsz); \
        (bw_ctx)->p += duk__valsz; \
    } while (0)
Definition at line 300 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_BYTES(thr,bw_ctx,valptr,valsz) do { \
        const void *duk__valptr; \
        duk_size_t duk__valsz; \
        duk__valptr = (const void *) (valptr); \
        duk__valsz = (duk_size_t) (valsz); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), duk__valptr, duk__valsz); \
        (bw_ctx)->p += duk__valsz; \
    } while (0)
DUK_BW_WRITE_RAW_CESU8
#define DUK_BW_WRITE_RAW_CESU8 (thr, bw_ctx, cp)
Value:
        do { \
        duk_ucodepoint_t duk__cp; \
        duk_small_int_t duk__enc_len; \
        duk__cp = (duk_ucodepoint_t) (cp); \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), duk_unicode_get_cesu8_length(duk__cp)); \
        duk__enc_len = duk_unicode_encode_cesu8(duk__cp, (bw_ctx)->p); \
        (bw_ctx)->p += duk__enc_len; \
    } while (0)
Definition at line 291 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_CESU8(thr,bw_ctx,cp) do { \
        duk_ucodepoint_t duk__cp; \
        duk_small_int_t duk__enc_len; \
        duk__cp = (duk_ucodepoint_t) (cp); \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), duk_unicode_get_cesu8_length(duk__cp)); \
        duk__enc_len = duk_unicode_encode_cesu8(duk__cp, (bw_ctx)->p); \
        (bw_ctx)->p += duk__enc_len; \
    } while (0)
DUK_BW_WRITE_RAW_CSTRING
#define DUK_BW_WRITE_RAW_CSTRING (thr, bw_ctx, val)
Value:
        do { \
        const duk_uint8_t *duk__val; \
        duk_size_t duk__val_len; \
        duk__val = (const duk_uint8_t *) (val); \
        duk__val_len = DUK_STRLEN((const char *) duk__val); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) duk__val, duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 308 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_CSTRING(thr,bw_ctx,val) do { \
        const duk_uint8_t *duk__val; \
        duk_size_t duk__val_len; \
        duk__val = (const duk_uint8_t *) (val); \
        duk__val_len = DUK_STRLEN((const char *) duk__val); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) duk__val, duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_RAW_HBUFFER
#define DUK_BW_WRITE_RAW_HBUFFER (thr, bw_ctx, val)
Value:
        do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_GET_SIZE((val)); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 322 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_HBUFFER(thr,bw_ctx,val) do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_GET_SIZE((val)); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_RAW_HBUFFER_DYNAMIC
#define DUK_BW_WRITE_RAW_HBUFFER_DYNAMIC (thr, bw_ctx, val)
Value:
        do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_DYNAMIC_GET_SIZE((val)); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_DYNAMIC_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 334 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_HBUFFER_DYNAMIC(thr,bw_ctx,val) do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_DYNAMIC_GET_SIZE((val)); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_DYNAMIC_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_RAW_HBUFFER_FIXED
#define DUK_BW_WRITE_RAW_HBUFFER_FIXED (thr, bw_ctx, val)
Value:
        do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_FIXED_GET_SIZE((val)); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_FIXED_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 328 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_HBUFFER_FIXED(thr,bw_ctx,val) do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HBUFFER_FIXED_GET_SIZE((val)); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HBUFFER_FIXED_GET_DATA_PTR((thr)->heap, (val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_RAW_HSTRING
#define DUK_BW_WRITE_RAW_HSTRING (thr, bw_ctx, val)
Value:
        do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HSTRING_GET_BYTELEN((val)); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HSTRING_GET_DATA((val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
Definition at line 316 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_HSTRING(thr,bw_ctx,val) do { \
        duk_size_t duk__val_len; \
        duk__val_len = DUK_HSTRING_GET_BYTELEN((val)); \
        DUK_MEMCPY((void *) ((bw_ctx)->p), (const void *) DUK_HSTRING_GET_DATA((val)), duk__val_len); \
        (bw_ctx)->p += duk__val_len; \
    } while (0)
DUK_BW_WRITE_RAW_SLICE
#define DUK_BW_WRITE_RAW_SLICE (thr, bw, dst_off, dst_len) duk_bw_write_raw_slice((thr), (bw), (dst_off), (dst_len))
Definition at line 342 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_SLICE(thr,bw,dst_off,dst_len) \
    duk_bw_write_raw_slice((thr), (bw), (dst_off), (dst_len))
DUK_BW_WRITE_RAW_U8
#define DUK_BW_WRITE_RAW_U8 (thr, bw_ctx, val)
Value:
        do { \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 1); \
        *(bw_ctx)->p++ = (duk_uint8_t) (val); \
    } while (0)
Definition at line 229 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_U8(thr,bw_ctx,val) do { \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 1); \
        *(bw_ctx)->p++ = (duk_uint8_t) (val); \
    } while (0)
DUK_BW_WRITE_RAW_U8_2
#define DUK_BW_WRITE_RAW_U8_2 (thr, bw_ctx, val1, val2)
Value:
        do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 2); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        (bw_ctx)->p = duk__p; \
    } while (0)
Definition at line 233 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_U8_2(thr,bw_ctx,val1,val2) do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 2); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        (bw_ctx)->p = duk__p; \
    } while (0)
DUK_BW_WRITE_RAW_U8_3
#define DUK_BW_WRITE_RAW_U8_3 (thr, bw_ctx, val1, val2, val3)
Value:
        do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 3); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        *duk__p++ = (duk_uint8_t) (val3); \
        (bw_ctx)->p = duk__p; \
    } while (0)
Definition at line 241 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_U8_3(thr,bw_ctx,val1,val2,val3) do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 3); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        *duk__p++ = (duk_uint8_t) (val3); \
        (bw_ctx)->p = duk__p; \
    } while (0)
DUK_BW_WRITE_RAW_U8_4
#define DUK_BW_WRITE_RAW_U8_4 (thr, bw_ctx, val1, val2, val3, val4)
Value:
        do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 4); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        *duk__p++ = (duk_uint8_t) (val3); \
        *duk__p++ = (duk_uint8_t) (val4); \
        (bw_ctx)->p = duk__p; \
    } while (0)
Definition at line 250 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_U8_4(thr,bw_ctx,val1,val2,val3,val4) do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 4); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        *duk__p++ = (duk_uint8_t) (val3); \
        *duk__p++ = (duk_uint8_t) (val4); \
        (bw_ctx)->p = duk__p; \
    } while (0)
DUK_BW_WRITE_RAW_U8_5
#define DUK_BW_WRITE_RAW_U8_5 (thr, bw_ctx, val1, val2, val3, val4, val5)
Value:
        do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 5); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        *duk__p++ = (duk_uint8_t) (val3); \
        *duk__p++ = (duk_uint8_t) (val4); \
        *duk__p++ = (duk_uint8_t) (val5); \
        (bw_ctx)->p = duk__p; \
    } while (0)
Definition at line 260 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_U8_5(thr,bw_ctx,val1,val2,val3,val4,val5) do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 5); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        *duk__p++ = (duk_uint8_t) (val3); \
        *duk__p++ = (duk_uint8_t) (val4); \
        *duk__p++ = (duk_uint8_t) (val5); \
        (bw_ctx)->p = duk__p; \
    } while (0)
DUK_BW_WRITE_RAW_U8_6
#define DUK_BW_WRITE_RAW_U8_6 (thr, bw_ctx, val1, val2, val3, val4, val5, val6)
Value:
        do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 6); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        *duk__p++ = (duk_uint8_t) (val3); \
        *duk__p++ = (duk_uint8_t) (val4); \
        *duk__p++ = (duk_uint8_t) (val5); \
        *duk__p++ = (duk_uint8_t) (val6); \
        (bw_ctx)->p = duk__p; \
    } while (0)
Definition at line 271 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_U8_6(thr,bw_ctx,val1,val2,val3,val4,val5,val6) do { \
        duk_uint8_t *duk__p; \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), 6); \
        duk__p = (bw_ctx)->p; \
        *duk__p++ = (duk_uint8_t) (val1); \
        *duk__p++ = (duk_uint8_t) (val2); \
        *duk__p++ = (duk_uint8_t) (val3); \
        *duk__p++ = (duk_uint8_t) (val4); \
        *duk__p++ = (duk_uint8_t) (val5); \
        *duk__p++ = (duk_uint8_t) (val6); \
        (bw_ctx)->p = duk__p; \
    } while (0)
DUK_BW_WRITE_RAW_XUTF8
#define DUK_BW_WRITE_RAW_XUTF8 (thr, bw_ctx, cp)
Value:
        do { \
        duk_ucodepoint_t duk__cp; \
        duk_small_int_t duk__enc_len; \
        duk__cp = (cp); \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), duk_unicode_get_xutf8_length(duk__cp)); \
        duk__enc_len = duk_unicode_encode_xutf8(duk__cp, (bw_ctx)->p); \
        (bw_ctx)->p += duk__enc_len; \
    } while (0)
Definition at line 283 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_BW_WRITE_RAW_XUTF8(thr,bw_ctx,cp) do { \
        duk_ucodepoint_t duk__cp; \
        duk_small_int_t duk__enc_len; \
        duk__cp = (cp); \
        DUK_BW_ASSERT_SPACE((thr), (bw_ctx), duk_unicode_get_xutf8_length(duk__cp)); \
        duk__enc_len = duk_unicode_encode_xutf8(duk__cp, (bw_ctx)->p); \
        (bw_ctx)->p += duk__enc_len; \
    } while (0)
DUK_RAW_READ_DOUBLE_BE
#define DUK_RAW_READ_DOUBLE_BE (ptr) duk_raw_read_double_be(&(ptr));
Definition at line 90 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_RAW_READ_U16_BE
#define DUK_RAW_READ_U16_BE (ptr) duk_raw_read_u16_be(&(ptr));
Definition at line 88 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_RAW_READ_U32_BE
#define DUK_RAW_READ_U32_BE (ptr) duk_raw_read_u32_be(&(ptr));
Definition at line 89 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_RAW_READ_U8
#define DUK_RAW_READ_U8 (ptr) ((duk_uint8_t) (*(ptr)++))
Definition at line 87 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_RAW_WRITE_CESU8
#define DUK_RAW_WRITE_CESU8 (ptr, val)
Value:
        do { \
        /* 'ptr' is evaluated both as LHS and RHS. */ \
        duk_uint8_t *duk__ptr; \
        duk_small_int_t duk__len; \
        duk__ptr = (duk_uint8_t *) (ptr); \
        duk__len = duk_unicode_encode_cesu8((duk_ucodepoint_t) (val), duk__ptr); \
        duk__ptr += duk__len; \
        (ptr) = duk__ptr; \
    } while (0)
Definition at line 77 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_RAW_WRITE_CESU8(ptr,val)  do { \
        /* 'ptr' is evaluated both as LHS and RHS. */ \
        duk_uint8_t *duk__ptr; \
        duk_small_int_t duk__len; \
        duk__ptr = (duk_uint8_t *) (ptr); \
        duk__len = duk_unicode_encode_cesu8((duk_ucodepoint_t) (val), duk__ptr); \
        duk__ptr += duk__len; \
        (ptr) = duk__ptr; \
    } while (0)
DUK_RAW_WRITE_DOUBLE_BE
#define DUK_RAW_WRITE_DOUBLE_BE (ptr, val) duk_raw_write_double_be(&(ptr), (duk_double_t) (val))
Definition at line 67 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_RAW_WRITE_U16_BE
#define DUK_RAW_WRITE_U16_BE (ptr, val) duk_raw_write_u16_be(&(ptr), (duk_uint16_t) (val))
Definition at line 65 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_RAW_WRITE_U32_BE
#define DUK_RAW_WRITE_U32_BE (ptr, val) duk_raw_write_u32_be(&(ptr), (duk_uint32_t) (val))
Definition at line 66 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_RAW_WRITE_U8
#define DUK_RAW_WRITE_U8 (ptr, val)
Value:
        do { \
        *(ptr)++ = (duk_uint8_t) (val); \
    } while (0)
Definition at line 62 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_RAW_WRITE_U8(ptr,val)  do { \
        *(ptr)++ = (duk_uint8_t) (val); \
    } while (0)
DUK_RAW_WRITE_XUTF8
#define DUK_RAW_WRITE_XUTF8 (ptr, val)
Value:
        do { \
        /* 'ptr' is evaluated both as LHS and RHS. */ \
        duk_uint8_t *duk__ptr; \
        duk_small_int_t duk__len; \
        duk__ptr = (duk_uint8_t *) (ptr); \
        duk__len = duk_unicode_encode_xutf8((duk_ucodepoint_t) (val), duk__ptr); \
        duk__ptr += duk__len; \
        (ptr) = duk__ptr; \
    } while (0)
Definition at line 68 of file duktape-1.8.0/src-separate/duk_util.h.
#define DUK_RAW_WRITE_XUTF8(ptr,val)  do { \
        /* 'ptr' is evaluated both as LHS and RHS. */ \
        duk_uint8_t *duk__ptr; \
        duk_small_int_t duk__len; \
        duk__ptr = (duk_uint8_t *) (ptr); \
        duk__len = duk_unicode_encode_xutf8((duk_ucodepoint_t) (val), duk__ptr); \
        duk__ptr += duk__len; \
        (ptr) = duk__ptr; \
    } while (0)
DUK_UTIL_GET_HASH_PROBE_STEP
#define DUK_UTIL_GET_HASH_PROBE_STEP (hash) (duk_util_probe_steps[(hash) & 0x1f])
Definition at line 10 of file duktape-1.8.0/src-separate/duk_util.h.
DUK_UTIL_MIN_HASH_PRIME
#define DUK_UTIL_MIN_HASH_PRIME 17 /* must match genhashsizes.py */
Definition at line 8 of file duktape-1.8.0/src-separate/duk_util.h.
Function Documentation
duk_bd_decode()
DUK_INTERNAL_DECL duk_int32_t duk_bd_decode (duk_bitdecoder_ctx * ctx, duk_small_int_t bits)
Definition at line 85971 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_small_int_t shift;
    duk_uint32_t mask;
    duk_uint32_t tmp;
    /* Note: cannot read more than 24 bits without possibly shifting top bits out.
     * Fixable, but adds complexity.
     */
    DUK_ASSERT(bits >= 1 && bits <= 24);
    while (ctx->currbits < bits) {
#if 0
        DUK_DDD(DUK_DDDPRINT("decode_bits: shift more data (bits=%ld, currbits=%ld)",
                             (long) bits, (long) ctx->currbits));
#endif
        ctx->currval <<= 8;
        if (ctx->offset < ctx->length) {
            /* If ctx->offset >= ctx->length, we "shift zeroes in"
             * instead of croaking.
             */
            ctx->currval |= ctx->data[ctx->offset++];
        }
        ctx->currbits += 8;
    }
#if 0
    DUK_DDD(DUK_DDDPRINT("decode_bits: bits=%ld, currbits=%ld, currval=0x%08lx",
                         (long) bits, (long) ctx->currbits, (unsigned long) ctx->currval));
References duk_bitdecoder_ctx::currbits, duk_bitdecoder_ctx::currval, duk_bitdecoder_ctx::data, DUK_ASSERT, DUK_DDD, DUK_DDDPRINT, duk_bitdecoder_ctx::length, mask, and duk_bitdecoder_ctx::offset.
Referenced by duk__hobject_pc2line_query_raw(), duk__init_heap_strings(), duk__push_double(), duk__push_stridx(), duk__push_string(), duk__slow_case_conversion(), duk__uni_decode_value(), duk_bd_decode_flag(), duk_bd_decode_flagged(), duk_be_encode(), and duk_hthread_create_builtin_objects().
duk_bd_decode_flag()
DUK_INTERNAL_DECL duk_small_int_t duk_bd_decode_flag (duk_bitdecoder_ctx * ctx)
Definition at line 86016 of file duktape-1.5.2/src-noline/duktape.c.
References duk_bd_decode().
Referenced by duk__hobject_pc2line_query_raw(), duk__push_stridx_or_string(), duk_bd_decode_flagged(), duk_be_encode(), and duk_hthread_create_builtin_objects().
duk_bd_decode_flagged()
DUK_INTERNAL_DECL duk_int32_t duk_bd_decode_flagged (duk_bitdecoder_ctx * ctx, duk_small_int_t bits, duk_int32_t def_value)
Definition at line 86024 of file duktape-1.5.2/src-noline/duktape.c.
                                     : %ld bits -> 0x%08lx (%ld), currbits=%ld, currval=0x%08lx",
                         (long) bits, (unsigned long) tmp, (long) tmp, (long) ctx->currbits, (unsigned long) ctx->currval));
#endif
    return tmp;
References duk_bd_decode(), and duk_bd_decode_flag().
Referenced by duk_hthread_create_builtin_objects().
duk_be_encode()
DUK_INTERNAL_DECL void duk_be_encode (duk_bitencoder_ctx * ctx, duk_uint32_t data, duk_small_int_t bits)
Definition at line 86037 of file duktape-1.5.2/src-noline/duktape.c.
{
    if (duk_bd_decode_flag(ctx)) {
        return (duk_int32_t) duk_bd_decode(ctx, bits);
    } else {
        return def_value;
    }
}
/*
 *  Bitstream encoder.
 */
/* include removed: duk_internal.h */
DUK_INTERNAL void duk_be_encode(duk_bitencoder_ctx *ctx, duk_uint32_t data, duk_small_int_t bits) {
    duk_uint8_t tmp;
    DUK_ASSERT(ctx != NULL);
    DUK_ASSERT(ctx->currbits < 8);
    /* This limitation would be fixable but adds unnecessary complexity. */
References duk_bitencoder_ctx::currbits, duk_bitencoder_ctx::currval, duk_bitencoder_ctx::data, DUK_ASSERT, duk_bd_decode(), duk_bd_decode_flag(), duk_bitencoder_ctx::length, NULL, duk_bitencoder_ctx::offset, and duk_bitencoder_ctx::truncated.
Referenced by duk__bw_update_ptrs(), duk_be_finish(), and duk_hobject_pc2line_pack().
duk_be_finish()
DUK_INTERNAL_DECL void duk_be_finish (duk_bitencoder_ctx * ctx)
Definition at line 86062 of file duktape-1.5.2/src-noline/duktape.c.
{
        if (ctx->offset < ctx->length) {
            tmp = (duk_uint8_t) ((ctx->currval >> (ctx->currbits - 8)) & 0xff);
            ctx->data[ctx->offset++] = tmp;
        } else {
            /* If buffer has been exhausted, truncate bitstream */
            ctx->truncated = 1;
        }
References duk_bitencoder_ctx::currbits, duk_bitencoder_ctx::currval, duk_bitencoder_ctx::data, DUK_ASSERT, duk_be_encode(), duk_bitencoder_ctx::length, NULL, duk_bitencoder_ctx::offset, and duk_bitencoder_ctx::truncated.
Referenced by duk_hobject_pc2line_pack().
duk_bw_compact()
DUK_INTERNAL_DECL void duk_bw_compact (duk_hthread * thr, duk_bufwriter_ctx * bw_ctx)
Definition at line 86162 of file duktape-1.5.2/src-noline/duktape.c.
References duk_bufwriter_ctx::buf, duk__bw_update_ptrs(), DUK_ASSERT, duk_hbuffer_resize(), DUK_UNREF, NULL, duk_bufwriter_ctx::p, and duk_bufwriter_ctx::p_base.
duk_bw_init()
DUK_INTERNAL_DECL void duk_bw_init (duk_hthread * thr, duk_bufwriter_ctx * bw_ctx, duk_hbuffer_dynamic * h_buf)
Definition at line 86098 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_uint8_t *p;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw_ctx != NULL);
    DUK_UNREF(thr);
References duk_bufwriter_ctx::buf, duk__bw_update_ptrs(), DUK_ASSERT, DUK_HBUFFER_DYNAMIC_GET_DATA_PTR, DUK_HBUFFER_DYNAMIC_GET_SIZE, DUK_UNREF, duk_hthread::heap, and NULL.
duk_bw_init_pushbuf()
DUK_INTERNAL_DECL void duk_bw_init_pushbuf (duk_hthread * thr, duk_bufwriter_ctx * bw_ctx, duk_size_t buf_size)
Definition at line 86109 of file duktape-1.5.2/src-noline/duktape.c.
{
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw_ctx != NULL);
    DUK_ASSERT(h_buf != NULL);
References duk_bufwriter_ctx::buf, duk__bw_update_ptrs(), DUK_ASSERT, duk_get_hbuffer(), duk_push_dynamic_buffer, and NULL.
duk_bw_insert_ensure_area()
DUK_INTERNAL_DECL duk_uint8_t * duk_bw_insert_ensure_area (duk_hthread * thr, duk_bufwriter_ctx * bw, duk_size_t off, duk_size_t len)
Definition at line 86309 of file duktape-1.5.2/src-noline/duktape.c.
References DUK_ASSERT, DUK_BW_ENSURE, DUK_BW_GET_SIZE, duk_bw_insert_raw_area(), DUK_UNREF, and NULL.
duk_bw_insert_ensure_bytes()
DUK_INTERNAL_DECL void duk_bw_insert_ensure_bytes (duk_hthread * thr, duk_bufwriter_ctx * bw, duk_size_t dst_off, const duk_uint8_t * buf, duk_size_t len)
Definition at line 86227 of file duktape-1.5.2/src-noline/duktape.c.
References DUK_ASSERT, DUK_BW_ENSURE, DUK_BW_GET_SIZE, duk_bw_insert_raw_bytes(), DUK_UNREF, and NULL.
duk_bw_insert_ensure_slice()
DUK_INTERNAL_DECL void duk_bw_insert_ensure_slice (duk_hthread * thr, duk_bufwriter_ctx * bw, duk_size_t dst_off, duk_size_t src_off, duk_size_t len)
Definition at line 86275 of file duktape-1.5.2/src-noline/duktape.c.
References DUK_ASSERT, DUK_BW_ENSURE, DUK_BW_GET_SIZE, duk_bw_insert_raw_slice(), DUK_UNREF, and NULL.
duk_bw_insert_raw_area()
DUK_INTERNAL_DECL duk_uint8_t * duk_bw_insert_raw_area (duk_hthread * thr, duk_bufwriter_ctx * bw, duk_size_t off, duk_size_t len)
Definition at line 86291 of file duktape-1.5.2/src-noline/duktape.c.
{
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw != NULL);
    DUK_ASSERT(dst_off <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(src_off <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(len <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(src_off + len <= DUK_BW_GET_SIZE(thr, bw));
    DUK_UNREF(thr);
    /* Don't support "straddled" source now. */
    DUK_ASSERT(dst_off <= src_off || dst_off >= src_off + len);
    DUK_BW_ENSURE(thr, bw, len);
    duk_bw_insert_raw_slice(thr, bw, dst_off, src_off, len);
}
References DUK_ASSERT, DUK_BW_ENSURE, DUK_BW_GET_SIZE, duk_bw_insert_raw_slice(), DUK_MEMMOVE, DUK_UNREF, NULL, duk_bufwriter_ctx::p, and duk_bufwriter_ctx::p_base.
Referenced by duk_bw_insert_ensure_area().
duk_bw_insert_raw_bytes()
DUK_INTERNAL_DECL void duk_bw_insert_raw_bytes (duk_hthread * thr, duk_bufwriter_ctx * bw, duk_size_t dst_off, const duk_uint8_t * buf, duk_size_t len)
Definition at line 86203 of file duktape-1.5.2/src-noline/duktape.c.
{
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw != NULL);
    DUK_ASSERT(src_off <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(len <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(src_off + len <= DUK_BW_GET_SIZE(thr, bw));
    DUK_UNREF(thr);
    DUK_BW_ENSURE(thr, bw, len);
    duk_bw_write_raw_slice(thr, bw, src_off, len);
}
DUK_INTERNAL void duk_bw_insert_raw_bytes(duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t dst_off, const duk_uint8_t *buf, duk_size_t len) {
    duk_uint8_t *p_base;
    duk_size_t buf_sz, move_sz;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw != NULL);
References DUK_ASSERT, DUK_BW_GET_SIZE, DUK_MEMCPY, DUK_MEMMOVE, DUK_UNREF, NULL, duk_bufwriter_ctx::p, and duk_bufwriter_ctx::p_base.
Referenced by duk_bw_insert_ensure_bytes().
duk_bw_insert_raw_slice()
DUK_INTERNAL_DECL void duk_bw_insert_raw_slice (duk_hthread * thr, duk_bufwriter_ctx * bw, duk_size_t dst_off, duk_size_t src_off, duk_size_t len)
Definition at line 86238 of file duktape-1.5.2/src-noline/duktape.c.
{
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw != NULL);
    DUK_ASSERT(dst_off <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(buf != NULL);
    DUK_UNREF(thr);
    DUK_BW_ENSURE(thr, bw, len);
    duk_bw_insert_raw_bytes(thr, bw, dst_off, buf, len);
}
DUK_INTERNAL void duk_bw_insert_raw_slice(duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t dst_off, duk_size_t src_off, duk_size_t len) {
    duk_uint8_t *p_base;
    duk_size_t buf_sz, move_sz;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw != NULL);
    DUK_ASSERT(dst_off <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(src_off <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(len <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(src_off + len <= DUK_BW_GET_SIZE(thr, bw));
    DUK_UNREF(thr);
    p_base = bw->p_base;
    /* Don't support "straddled" source now. */
    DUK_ASSERT(dst_off <= src_off || dst_off >= src_off + len);
    if (dst_off <= src_off) {
        /* Target is before source.  Source offset is expressed as
References DUK_ASSERT, DUK_BW_GET_SIZE, DUK_MEMCPY, DUK_MEMMOVE, DUK_UNREF, NULL, duk_bufwriter_ctx::p, and duk_bufwriter_ctx::p_base.
Referenced by duk_bw_insert_ensure_slice(), and duk_bw_insert_raw_area().
duk_bw_remove_raw_slice()
DUK_INTERNAL_DECL void duk_bw_remove_raw_slice (duk_hthread * thr, duk_bufwriter_ctx * bw, duk_size_t off, duk_size_t len)
Definition at line 86319 of file duktape-1.5.2/src-noline/duktape.c.
{
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw != NULL);
    DUK_ASSERT(off <= DUK_BW_GET_SIZE(thr, bw));
    DUK_UNREF(thr);
    DUK_BW_ENSURE(thr, bw, len);
    return duk_bw_insert_raw_area(thr, bw, off, len);
}
DUK_INTERNAL void duk_bw_remove_raw_slice(duk_hthread *thr, duk_bufwriter_ctx *bw, duk_size_t off, duk_size_t len) {
    duk_size_t move_sz;
    duk_uint8_t *p_base;
    duk_uint8_t *p_src;
    duk_uint8_t *p_dst;
References DUK_ASSERT, DUK_BW_GET_SIZE, DUK_MEMMOVE, DUK_UNREF, NULL, duk_bufwriter_ctx::p, and duk_bufwriter_ctx::p_base.
duk_bw_resize()
DUK_INTERNAL_DECL duk_uint8_t * duk_bw_resize (duk_hthread * thr, duk_bufwriter_ctx * bw_ctx, duk_size_t sz)
Definition at line 86124 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_context *ctx;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw_ctx != NULL);
    ctx = (duk_context *) thr;
    (void) duk_push_dynamic_buffer(ctx, buf_size);
    bw_ctx->buf = (duk_hbuffer_dynamic *) duk_get_hbuffer(ctx, -1);
    duk__bw_update_ptrs(thr, bw_ctx, 0, buf_size);
}
/* Resize target buffer for requested size.  Called by the macro only when the
 * fast path test (= there is space) fails.
 */
DUK_INTERNAL duk_uint8_t *duk_bw_resize(duk_hthread *thr, duk_bufwriter_ctx *bw_ctx, duk_size_t sz) {
    duk_size_t curr_off;
    duk_size_t add_sz;
    duk_size_t new_sz;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw_ctx != NULL);
    /* We could do this operation without caller updating bw_ctx->ptr,
     * but by writing it back here we can share code better.
     */
    curr_off = (duk_size_t) (bw_ctx->p - bw_ctx->p_base);
    add_sz = (curr_off >> DUK_BW_SPARE_SHIFT) + DUK_BW_SPARE_ADD;
    new_sz = curr_off + sz + add_sz;
    if (new_sz < curr_off) {
        /* overflow */
        DUK_ERROR_RANGE(thr, DUK_STR_BUFFER_TOO_LONG);
        return NULL;  /* not reachable */
References duk_bufwriter_ctx::buf, duk__bw_update_ptrs(), DUK_ASSERT, DUK_BW_SPARE_ADD, DUK_BW_SPARE_SHIFT, DUK_DD, DUK_DDPRINT, DUK_ERROR_RANGE, duk_hbuffer_resize(), DUK_STR_BUFFER_TOO_LONG, NULL, duk_bufwriter_ctx::p, and duk_bufwriter_ctx::p_base.
duk_bw_write_ensure_slice()
DUK_INTERNAL_DECL void duk_bw_write_ensure_slice (duk_hthread * thr, duk_bufwriter_ctx * bw, duk_size_t src_off, duk_size_t len)
Definition at line 86191 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_uint8_t *p_base;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw != NULL);
    DUK_ASSERT(src_off <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(len <= DUK_BW_GET_SIZE(thr, bw));
    DUK_ASSERT(src_off + len <= DUK_BW_GET_SIZE(thr, bw));
    DUK_UNREF(thr);
    p_base = bw->p_base;
References DUK_ASSERT, DUK_BW_ENSURE, DUK_BW_GET_SIZE, duk_bw_write_raw_slice(), DUK_MEMCPY, DUK_UNREF, NULL, duk_bufwriter_ctx::p, and duk_bufwriter_ctx::p_base.
duk_bw_write_raw_slice()
DUK_INTERNAL_DECL void duk_bw_write_raw_slice (duk_hthread * thr, duk_bufwriter_ctx * bw, duk_size_t src_off, duk_size_t len)
Definition at line 86174 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_size_t len;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(bw_ctx != NULL);
    DUK_UNREF(thr);
    len = (duk_size_t) (bw_ctx->p - bw_ctx->p_base);
    duk_hbuffer_resize(thr, bw_ctx->buf, len);
    duk__bw_update_ptrs(thr, bw_ctx, len, len);
}
References DUK_ASSERT, DUK_BW_GET_SIZE, DUK_MEMCPY, DUK_UNREF, NULL, duk_bufwriter_ctx::p, and duk_bufwriter_ctx::p_base.
Referenced by duk_bw_write_ensure_slice().
duk_raw_read_double_be()
DUK_INTERNAL_DECL duk_double_t duk_raw_read_double_be (duk_uint8_t ** p)
Definition at line 86378 of file duktape-1.5.2/src-noline/duktape.c.
{
    union {
        duk_uint8_t b[4];
        duk_uint32_t x;
    } u;
    DUK_MEMCPY((void *) u.b, (const void *) (*p), (size_t) 4);
    u.x = DUK_NTOH32(u.x);
    *p += 4;
    return u.x;
}
References duk_double_union::d, DUK_MEMCPY, and duk_double_union::ui.
duk_raw_read_u16_be()
DUK_INTERNAL_DECL duk_uint16_t duk_raw_read_u16_be (duk_uint8_t ** p)
Definition at line 86354 of file duktape-1.5.2/src-noline/duktape.c.
References DUK_MEMCPY.
duk_raw_read_u32_be()
DUK_INTERNAL_DECL duk_uint32_t duk_raw_read_u32_be (duk_uint8_t ** p)
Definition at line 86366 of file duktape-1.5.2/src-noline/duktape.c.
{
    union {
        duk_uint8_t b[2];
        duk_uint16_t x;
    } u;
References DUK_MEMCPY.
duk_raw_write_double_be()
DUK_INTERNAL_DECL void duk_raw_write_double_be (duk_uint8_t ** p, duk_double_t val)
Definition at line 86418 of file duktape-1.5.2/src-noline/duktape.c.
{
    union {
        duk_uint8_t b[4];
        duk_uint32_t x;
    } u;
    u.x = DUK_HTON32(val);
    DUK_MEMCPY((void *) (*p), (const void *) u.b, (size_t) 4);
    *p += 4;
}
References duk_double_union::d, DUK_MEMCPY, and duk_double_union::ui.
duk_raw_write_u16_be()
DUK_INTERNAL_DECL void duk_raw_write_u16_be (duk_uint8_t ** p, duk_uint16_t val)
Definition at line 86396 of file duktape-1.5.2/src-noline/duktape.c.
          {
        duk_uint8_t b[4];
        duk_uint32_t x;
    } u;
    DUK_MEMCPY((void *) u.b, (const void *) (*p), (size_t) 4);
    u.x = DUK_NTOH32(u.x);
    du.ui[DUK_DBL_IDX_UI0] = u.x;
    DUK_MEMCPY((void *) u.b, (const void *) (*p + 4), (size_t) 4);
References DUK_MEMCPY.
duk_raw_write_u32_be()
DUK_INTERNAL_DECL void duk_raw_write_u32_be (duk_uint8_t ** p, duk_uint32_t val)
Definition at line 86407 of file duktape-1.5.2/src-noline/duktape.c.
{
    union {
        duk_uint8_t b[2];
        duk_uint16_t x;
References DUK_MEMCPY.
duk_util_tinyrandom_get_bits()
DUK_INTERNAL_DECL duk_uint32_t duk_util_tinyrandom_get_bits (duk_hthread * thr, duk_small_int_t n)
Definition at line 86508 of file duktape-1.5.2/src-noline/duktape.c.
                                { \
        (rnd) += ((rnd) * (rnd)) | 0x05; \
        (rnd) = ((rnd) & 0xffffffffU);       /* if duk_uint32_t is exactly 32 bits, this is a NOP */ \
    } while (0)
#define DUK__RND_BIT(rnd)  ((rnd) >> 31)  /* only use the highest bit */
References DUK__RND_BIT, DUK__UPDATE_RND, duk_hthread::heap, and duk_heap::rnd_state.
Referenced by duk__array_qsort().
duk_util_tinyrandom_get_double()
DUK_INTERNAL_DECL duk_double_t duk_util_tinyrandom_get_double (duk_hthread * thr)
Definition at line 86526 of file duktape-1.5.2/src-noline/duktape.c.
{
        DUK__UPDATE_RND(rnd);
        res <<= 1;
        res += DUK__RND_BIT(rnd);
    }
    thr->heap->rnd_state = rnd;
    return res;
}
DUK_INTERNAL duk_double_t duk_util_tinyrandom_get_double(duk_hthread *thr) {
    duk_double_t t;
    duk_small_int_t n;
    duk_uint32_t rnd;
    /*
     *  XXX: could make this a lot faster if we create the double memory
     *  representation directly.  Feasible easily (must be uniform random).
     */
    rnd = thr->heap->rnd_state;
References DUK__RND_BIT, DUK__UPDATE_RND, DUK_ASSERT, duk_hthread::heap, and duk_heap::rnd_state.
Referenced by duk_bi_math_object_random().
Variable Documentation
duk_hex_dectab
DUK_INTERNAL_DECL const duk_int8_t duk_hex_dectab[256]
Definition at line 468 of file duktape-1.8.0/src-separate/duk_util.h.
duk_lc_digits
DUK_INTERNAL_DECL const duk_uint8_t duk_lc_digits[36]
Definition at line 466 of file duktape-1.8.0/src-separate/duk_util.h.
duk_uc_nybbles
DUK_INTERNAL_DECL const duk_uint8_t duk_uc_nybbles[16]
Definition at line 467 of file duktape-1.8.0/src-separate/duk_util.h.