Github User Fetcher: hello.c File Reference
hello.c File Reference
#include "duktape.h"
Functions
int adder (duk_context *ctx)
int main (int argc, char *argv[])
Function Documentation
adder()
int adder (duk_context * ctx)
Definition at line 7 of file duktape-1.8.0/examples/hello/hello.c.
{
    int i;
    int n = duk_get_top(ctx);  /* #args */
    double res = 0.0;
    for (i = 0; i < n; i++) {
        res += duk_to_number(ctx, i);
    }
    duk_push_number(ctx, res);
    return 1;  /* one return value */
}
References duk_get_top(), duk_push_number(), and duk_to_number().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 20 of file duktape-1.8.0/examples/hello/hello.c.
{
    duk_context *ctx = duk_create_heap_default();
    (void) argc; (void) argv;  /* suppress warning */
    duk_eval_string(ctx, "print('Hello world!');");
    duk_push_global_object(ctx);
    duk_push_c_function(ctx, adder, DUK_VARARGS);
    duk_put_prop_string(ctx, -2, "adder");
    duk_pop(ctx);  /* pop global */
    duk_eval_string(ctx, "print('2+3=' + adder(2, 3));");
    duk_pop(ctx);  /* pop eval result */
    duk_destroy_heap(ctx);
    return 0;
}
References adder(), duk_create_heap_default, duk_destroy_heap(), duk_eval_string, duk_pop(), duk_push_c_function(), duk_push_global_object(), duk_put_prop_string(), and DUK_VARARGS.