Github User Fetcher: duk_hbuffer_ops.c File Reference
duk_hbuffer_ops.c File Reference
#include "duk_internal.h"
Functions
DUK_INTERNAL void duk_hbuffer_resize (duk_hthread *thr, duk_hbuffer_dynamic *buf, duk_size_t new_size)
DUK_INTERNAL void duk_hbuffer_reset (duk_hthread *thr, duk_hbuffer_dynamic *buf)
Function Documentation
duk_hbuffer_reset()
DUK_INTERNAL void duk_hbuffer_reset (duk_hthread * thr, duk_hbuffer_dynamic * buf)
Definition at line 75 of file duktape-1.5.2/src-separate/duk_hbuffer_ops.c.
{
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(buf != NULL);
    DUK_ASSERT(DUK_HBUFFER_HAS_DYNAMIC(buf));
    DUK_ASSERT(!DUK_HBUFFER_HAS_EXTERNAL(buf));
    duk_hbuffer_resize(thr, buf, 0);
}
References DUK_ASSERT, DUK_HBUFFER_HAS_DYNAMIC, DUK_HBUFFER_HAS_EXTERNAL, duk_hbuffer_resize(), and NULL.
duk_hbuffer_resize()
DUK_INTERNAL void duk_hbuffer_resize (duk_hthread * thr, duk_hbuffer_dynamic * buf, duk_size_t new_size)
Definition at line 18 of file duktape-1.5.2/src-separate/duk_hbuffer_ops.c.
{
    void *res;
    duk_size_t prev_size;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(buf != NULL);
    DUK_ASSERT(DUK_HBUFFER_HAS_DYNAMIC(buf));
    DUK_ASSERT(!DUK_HBUFFER_HAS_EXTERNAL(buf));
    /*
     *  Maximum size check
     */
    if (new_size > DUK_HBUFFER_MAX_BYTELEN) {
        DUK_ERROR_RANGE(thr, "buffer too long");
    }
    /*
     *  Note: use indirect realloc variant just in case mark-and-sweep
     *  (finalizers) might resize this same buffer during garbage
     *  collection.
     */
    res = DUK_REALLOC_INDIRECT(thr->heap, duk_hbuffer_get_dynalloc_ptr, (void *) buf, new_size);
    if (res != NULL || new_size == 0) {
        /* 'res' may be NULL if new allocation size is 0. */
        DUK_DDD(DUK_DDDPRINT("resized dynamic buffer %p:%ld -> %p:%ld",
                             (void *) DUK_HBUFFER_DYNAMIC_GET_DATA_PTR(thr->heap, buf),
                             (long) DUK_HBUFFER_DYNAMIC_GET_SIZE(buf),
                             (void *) res,
                             (long) new_size));
        /*
         *  The entire allocated buffer area, regardless of actual used
         *  size, is kept zeroed in resizes for simplicity.  If the buffer
         *  is grown, zero the new part.
         */
        prev_size = DUK_HBUFFER_DYNAMIC_GET_SIZE(buf);
        if (new_size > prev_size) {
            DUK_ASSERT(new_size - prev_size > 0);
#ifdef DUK_USE_ZERO_BUFFER_DATA
            DUK_MEMZERO((void *) ((char *) res + prev_size),
                        (duk_size_t) (new_size - prev_size));
#endif
        }
        DUK_HBUFFER_DYNAMIC_SET_SIZE(buf, new_size);
        DUK_HBUFFER_DYNAMIC_SET_DATA_PTR(thr->heap, buf, res);
    } else {
        DUK_ERROR_ALLOC_DEFMSG(thr);
    }
    DUK_ASSERT(res != NULL || new_size == 0);
}
References DUK_ASSERT, DUK_DDD, DUK_DDDPRINT, DUK_ERROR_ALLOC_DEFMSG, DUK_ERROR_RANGE, DUK_HBUFFER_DYNAMIC_GET_DATA_PTR, DUK_HBUFFER_DYNAMIC_GET_SIZE, DUK_HBUFFER_DYNAMIC_SET_DATA_PTR, DUK_HBUFFER_DYNAMIC_SET_SIZE, duk_hbuffer_get_dynalloc_ptr(), DUK_HBUFFER_HAS_DYNAMIC, DUK_HBUFFER_HAS_EXTERNAL, DUK_HBUFFER_MAX_BYTELEN, DUK_MEMZERO, DUK_REALLOC_INDIRECT, duk_hthread::heap, and NULL.
Referenced by duk_hbuffer_reset().