Github User Fetcher: ncurses.c File Reference
ncurses.c File Reference
#include <curses.h>
#include "duktape.h"
Functions
static int ncurses_initscr (duk_context *ctx)
static int ncurses_endwin (duk_context *ctx)
static int ncurses_delscreen (duk_context *ctx)
static int ncurses_getmaxyx (duk_context *ctx)
static int ncurses_printw (duk_context *ctx)
static int ncurses_mvprintw (duk_context *ctx)
static int ncurses_refresh (duk_context *ctx)
static int ncurses_getch (duk_context *ctx)
void ncurses_register (duk_context *ctx)
Variables
static duk_function_list_entry ncurses_funcs []
Function Documentation
ncurses_delscreen()
static int ncurses_delscreen (duk_context * ctx) static
Definition at line 30 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    /* XXX: no screen management now */
    (void) ctx;
    return 0;
}
ncurses_endwin()
static int ncurses_endwin (duk_context * ctx) static
Definition at line 22 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    int rc;
    rc = endwin();
    duk_push_int(ctx, rc);
    return 1;
}
References duk_push_int().
ncurses_getch()
static int ncurses_getch (duk_context * ctx) static
Definition at line 78 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    int rc;
    rc = getch();
    duk_push_int(ctx, rc);
    return 1;
}
References duk_push_int().
ncurses_getmaxyx()
static int ncurses_getmaxyx (duk_context * ctx) static
Definition at line 36 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    int row, col;
    getmaxyx(stdscr, row, col);
    duk_push_array(ctx);
    duk_push_int(ctx, row);
    duk_put_prop_index(ctx, -2, 0);
    duk_push_int(ctx, col);
    duk_put_prop_index(ctx, -2, 1);
    return 1;
}
References duk_push_array(), duk_push_int(), and duk_put_prop_index().
ncurses_initscr()
static int ncurses_initscr (duk_context * ctx) static
Definition at line 14 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    WINDOW *win;
    win = initscr();
    duk_push_pointer(ctx, (void *) win);
    return 1;
}
References duk_push_pointer().
ncurses_mvprintw()
static int ncurses_mvprintw (duk_context * ctx) static
Definition at line 59 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    int y = duk_to_int(ctx, 0);
    int x = duk_to_int(ctx, 1);
    const char *str = duk_to_string(ctx, 2);
    int rc;
    rc = mvprintw(y, x, "%s", str);
    duk_push_int(ctx, rc);
    return 1;
}
References duk_push_int(), duk_to_int(), and duk_to_string().
ncurses_printw()
static int ncurses_printw (duk_context * ctx) static
Definition at line 49 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    int rc;
    const char *str;
    str = duk_to_string(ctx, 0);
    rc = printw("%s", str);
    duk_push_int(ctx, rc);
    return 1;
}
References duk_push_int(), and duk_to_string().
ncurses_refresh()
static int ncurses_refresh (duk_context * ctx) static
Definition at line 70 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    int rc;
    rc = refresh();
    duk_push_int(ctx, rc);
    return 1;
}
References duk_push_int().
ncurses_register()
void ncurses_register (duk_context * ctx)
Definition at line 98 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    /* Set global 'Ncurses'. */
    duk_push_global_object(ctx);
    duk_push_object(ctx);
    duk_put_function_list(ctx, -1, ncurses_funcs);
    duk_put_prop_string(ctx, -2, "Ncurses");
    duk_pop(ctx);
}
Variable Documentation
ncurses_funcs
duk_function_list_entry ncurses_funcs[] static
Initial value:
= {
    { "initscr", ncurses_initscr, 0 },
    { "endwin", ncurses_endwin, 0 },
    { "delscreen", ncurses_delscreen, 0 },
    { "getmaxyx", ncurses_getmaxyx, 0 },
    { "printw", ncurses_printw, 1 },
    { "mvprintw", ncurses_mvprintw, 3 },
    { "refresh", ncurses_refresh, 0 },
    { "getch", ncurses_getch, 0 },
    { NULL, NULL, 0 }
}
Definition at line 86 of file duktape-1.5.2/examples/eventloop/ncurses.c.
{
    { "initscr", ncurses_initscr, 0 },
    { "endwin", ncurses_endwin, 0 },
    { "delscreen", ncurses_delscreen, 0 },
    { "getmaxyx", ncurses_getmaxyx, 0 },
    { "printw", ncurses_printw, 1 },
    { "mvprintw", ncurses_mvprintw, 3 },
    { "refresh", ncurses_refresh, 0 },
    { "getch", ncurses_getch, 0 },
    { NULL, NULL, 0 }
};
Referenced by ncurses_register().