Github User Fetcher: duk_hbuffer.h File Reference
duk_hbuffer.h File Reference
Data Structures
struct duk_hbuffer
struct duk_hbuffer_fixed
struct duk_hbuffer_dynamic
struct duk_hbuffer_external
Macros
#define DUK_HBUFFER_FLAG_DYNAMIC DUK_HEAPHDR_USER_FLAG(0) /* buffer is behind a pointer, dynamic or external */
#define DUK_HBUFFER_FLAG_EXTERNAL DUK_HEAPHDR_USER_FLAG(1) /* buffer pointer is to an externally allocated buffer */
#define DUK_HBUFFER_HAS_DYNAMIC(x) DUK_HEAPHDR_CHECK_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_DYNAMIC)
#define DUK_HBUFFER_HAS_EXTERNAL(x) DUK_HEAPHDR_CHECK_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_EXTERNAL)
#define DUK_HBUFFER_SET_DYNAMIC(x) DUK_HEAPHDR_SET_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_DYNAMIC)
#define DUK_HBUFFER_SET_EXTERNAL(x) DUK_HEAPHDR_SET_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_EXTERNAL)
#define DUK_HBUFFER_CLEAR_DYNAMIC(x) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_DYNAMIC)
#define DUK_HBUFFER_CLEAR_EXTERNAL(x) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_EXTERNAL)
#define DUK_HBUFFER_MAX_BYTELEN (0x7ffffffeUL)
#define DUK_HBUFFER_GET_SIZE(x) (((duk_hbuffer *) (x))->size)
#define DUK_HBUFFER_SET_SIZE(x, v)
#define DUK_HBUFFER_ADD_SIZE(x, dv)
#define DUK_HBUFFER_SUB_SIZE(x, dv)
#define DUK_HBUFFER_FIXED_GET_SIZE(x) DUK_HBUFFER_GET_SIZE((duk_hbuffer *) (x))
#define DUK_HBUFFER_FIXED_SET_SIZE(x, v) DUK_HBUFFER_SET_SIZE((duk_hbuffer *) (x))
#define DUK_HBUFFER_DYNAMIC_GET_SIZE(x) DUK_HBUFFER_GET_SIZE((duk_hbuffer *) (x))
#define DUK_HBUFFER_DYNAMIC_SET_SIZE(x, v) DUK_HBUFFER_SET_SIZE((duk_hbuffer *) (x), (v))
#define DUK_HBUFFER_DYNAMIC_ADD_SIZE(x, dv) DUK_HBUFFER_ADD_SIZE((duk_hbuffer *) (x), (dv))
#define DUK_HBUFFER_DYNAMIC_SUB_SIZE(x, dv) DUK_HBUFFER_SUB_SIZE((duk_hbuffer *) (x), (dv))
#define DUK_HBUFFER_EXTERNAL_GET_SIZE(x) DUK_HBUFFER_GET_SIZE((duk_hbuffer *) (x))
#define DUK_HBUFFER_EXTERNAL_SET_SIZE(x, v) DUK_HBUFFER_SET_SIZE((duk_hbuffer *) (x), (v))
#define DUK_HBUFFER_FIXED_GET_DATA_PTR(heap, x) ((duk_uint8_t *) (((duk_hbuffer_fixed *) (x)) + 1))
#define DUK_HBUFFER_DYNAMIC_GET_DATA_PTR(heap, x) ((x)->curr_alloc)
#define DUK_HBUFFER_DYNAMIC_SET_DATA_PTR(heap, x, v)
#define DUK_HBUFFER_DYNAMIC_SET_DATA_PTR_NULL(heap, x)
#define DUK_HBUFFER_EXTERNAL_GET_DATA_PTR(heap, x) ((void *) (x)->curr_alloc)
#define DUK_HBUFFER_EXTERNAL_SET_DATA_PTR(heap, x, v)
#define DUK_HBUFFER_EXTERNAL_SET_DATA_PTR_NULL(heap, x)
#define DUK_HBUFFER_GET_DATA_PTR(heap, x)
Functions
DUK_INTERNAL_DECL duk_hbuffer * duk_hbuffer_alloc (duk_heap *heap, duk_size_t size, duk_small_uint_t flags, void **out_bufdata)
DUK_INTERNAL_DECL void * duk_hbuffer_get_dynalloc_ptr (duk_heap *heap, void *ud)
DUK_INTERNAL_DECL void duk_hbuffer_resize (duk_hthread *thr, duk_hbuffer_dynamic *buf, duk_size_t new_size)
DUK_INTERNAL_DECL void duk_hbuffer_reset (duk_hthread *thr, duk_hbuffer_dynamic *buf)
Macro Definition Documentation
DUK_HBUFFER_ADD_SIZE
#define DUK_HBUFFER_ADD_SIZE (x, dv)
Value:
        do { \
        (x)->size += (dv); \
    } while (0)
Definition at line 81 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
#define DUK_HBUFFER_ADD_SIZE(x,dv)  do { \
        (x)->size += (dv); \
    } while (0)
DUK_HBUFFER_CLEAR_DYNAMIC
#define DUK_HBUFFER_CLEAR_DYNAMIC (x) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_DYNAMIC)
Definition at line 32 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_CLEAR_EXTERNAL
#define DUK_HBUFFER_CLEAR_EXTERNAL (x) DUK_HEAPHDR_CLEAR_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_EXTERNAL)
Definition at line 33 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_DYNAMIC_ADD_SIZE
#define DUK_HBUFFER_DYNAMIC_ADD_SIZE (x, dv) DUK_HBUFFER_ADD_SIZE((duk_hbuffer *) (x), (dv))
Definition at line 94 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_DYNAMIC_GET_DATA_PTR
#define DUK_HBUFFER_DYNAMIC_GET_DATA_PTR (heap, x) ((x)->curr_alloc)
Definition at line 112 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_DYNAMIC_GET_SIZE
#define DUK_HBUFFER_DYNAMIC_GET_SIZE (x) DUK_HBUFFER_GET_SIZE((duk_hbuffer *) (x))
Definition at line 92 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_DYNAMIC_SET_DATA_PTR
#define DUK_HBUFFER_DYNAMIC_SET_DATA_PTR (heap, x, v)
Value:
        do { \
        (x)->curr_alloc = (void *) (v); \
    } while (0)
Definition at line 113 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
#define DUK_HBUFFER_DYNAMIC_SET_DATA_PTR(heap,x,v)     do { \
        (x)->curr_alloc = (void *) (v); \
    } while (0)
DUK_HBUFFER_DYNAMIC_SET_DATA_PTR_NULL
#define DUK_HBUFFER_DYNAMIC_SET_DATA_PTR_NULL (heap, x)
Value:
        do { \
        (x)->curr_alloc = (void *) NULL; \
    } while (0)
Definition at line 116 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
#define DUK_HBUFFER_DYNAMIC_SET_DATA_PTR_NULL(heap,x)  do { \
        (x)->curr_alloc = (void *) NULL; \
    } while (0)
DUK_HBUFFER_DYNAMIC_SET_SIZE
#define DUK_HBUFFER_DYNAMIC_SET_SIZE (x, v) DUK_HBUFFER_SET_SIZE((duk_hbuffer *) (x), (v))
Definition at line 93 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_DYNAMIC_SUB_SIZE
#define DUK_HBUFFER_DYNAMIC_SUB_SIZE (x, dv) DUK_HBUFFER_SUB_SIZE((duk_hbuffer *) (x), (dv))
Definition at line 95 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_EXTERNAL_GET_DATA_PTR
#define DUK_HBUFFER_EXTERNAL_GET_DATA_PTR (heap, x) ((void *) (x)->curr_alloc)
Definition at line 134 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
#define DUK_HBUFFER_EXTERNAL_GET_DATA_PTR(heap,x) \
    ((void *) (x)->curr_alloc)
DUK_HBUFFER_EXTERNAL_GET_SIZE
#define DUK_HBUFFER_EXTERNAL_GET_SIZE (x) DUK_HBUFFER_GET_SIZE((duk_hbuffer *) (x))
Definition at line 97 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_EXTERNAL_SET_DATA_PTR
#define DUK_HBUFFER_EXTERNAL_SET_DATA_PTR (heap, x, v)
Value:
        do { \
        (x)->curr_alloc = (void *) (v); \
    } while (0)
Definition at line 136 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
#define DUK_HBUFFER_EXTERNAL_SET_DATA_PTR(heap,x,v)     do { \
        (x)->curr_alloc = (void *) (v); \
    } while (0)
DUK_HBUFFER_EXTERNAL_SET_DATA_PTR_NULL
#define DUK_HBUFFER_EXTERNAL_SET_DATA_PTR_NULL (heap, x)
Value:
        do { \
        (x)->curr_alloc = (void *) NULL; \
    } while (0)
Definition at line 139 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
#define DUK_HBUFFER_EXTERNAL_SET_DATA_PTR_NULL(heap,x)  do { \
        (x)->curr_alloc = (void *) NULL; \
    } while (0)
DUK_HBUFFER_EXTERNAL_SET_SIZE
#define DUK_HBUFFER_EXTERNAL_SET_SIZE (x, v) DUK_HBUFFER_SET_SIZE((duk_hbuffer *) (x), (v))
Definition at line 98 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_FIXED_GET_DATA_PTR
#define DUK_HBUFFER_FIXED_GET_DATA_PTR (heap, x) ((duk_uint8_t *) (((duk_hbuffer_fixed *) (x)) + 1))
Definition at line 100 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_FIXED_GET_SIZE
#define DUK_HBUFFER_FIXED_GET_SIZE (x) DUK_HBUFFER_GET_SIZE((duk_hbuffer *) (x))
Definition at line 89 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_FIXED_SET_SIZE
#define DUK_HBUFFER_FIXED_SET_SIZE (x, v) DUK_HBUFFER_SET_SIZE((duk_hbuffer *) (x))
Definition at line 90 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_FLAG_DYNAMIC
#define DUK_HBUFFER_FLAG_DYNAMIC DUK_HEAPHDR_USER_FLAG(0) /* buffer is behind a pointer, dynamic or external */
Definition at line 23 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_FLAG_EXTERNAL
#define DUK_HBUFFER_FLAG_EXTERNAL DUK_HEAPHDR_USER_FLAG(1) /* buffer pointer is to an externally allocated buffer */
Definition at line 24 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_GET_DATA_PTR
#define DUK_HBUFFER_GET_DATA_PTR (heap, x)
Value:
    ( \
    DUK_HBUFFER_HAS_DYNAMIC((x)) ? \
        DUK_HBUFFER_DYNAMIC_GET_DATA_PTR((heap), (duk_hbuffer_dynamic *) (x)) : \
        DUK_HBUFFER_FIXED_GET_DATA_PTR((heap), (duk_hbuffer_fixed *) (x)) \
    )
Definition at line 161 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
#define DUK_HBUFFER_GET_DATA_PTR(heap,x)  (\
    DUK_HBUFFER_HAS_DYNAMIC((x)) ? \
        DUK_HBUFFER_DYNAMIC_GET_DATA_PTR((heap), (duk_hbuffer_dynamic *) (x)) : \
        DUK_HBUFFER_FIXED_GET_DATA_PTR((heap), (duk_hbuffer_fixed *) (x)) \
    )
DUK_HBUFFER_GET_SIZE
#define DUK_HBUFFER_GET_SIZE (x) (((duk_hbuffer *) (x))->size)
Definition at line 77 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_HAS_DYNAMIC
#define DUK_HBUFFER_HAS_DYNAMIC (x) DUK_HEAPHDR_CHECK_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_DYNAMIC)
Definition at line 26 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_HAS_EXTERNAL
#define DUK_HBUFFER_HAS_EXTERNAL (x) DUK_HEAPHDR_CHECK_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_EXTERNAL)
Definition at line 27 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_MAX_BYTELEN
#define DUK_HBUFFER_MAX_BYTELEN (0x7ffffffeUL)
Definition at line 51 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_SET_DYNAMIC
#define DUK_HBUFFER_SET_DYNAMIC (x) DUK_HEAPHDR_SET_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_DYNAMIC)
Definition at line 29 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_SET_EXTERNAL
#define DUK_HBUFFER_SET_EXTERNAL (x) DUK_HEAPHDR_SET_FLAG_BITS(&(x)->hdr, DUK_HBUFFER_FLAG_EXTERNAL)
Definition at line 30 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
DUK_HBUFFER_SET_SIZE
#define DUK_HBUFFER_SET_SIZE (x, v)
Value:
        do { \
        ((duk_hbuffer *) (x))->size = (v); \
    } while (0)
Definition at line 78 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
#define DUK_HBUFFER_SET_SIZE(x,v)   do { \
        ((duk_hbuffer *) (x))->size = (v); \
    } while (0)
DUK_HBUFFER_SUB_SIZE
#define DUK_HBUFFER_SUB_SIZE (x, dv)
Value:
        do { \
        (x)->size -= (dv); \
    } while (0)
Definition at line 84 of file duktape-1.8.0/src-separate/duk_hbuffer.h.
#define DUK_HBUFFER_SUB_SIZE(x,dv)  do { \
        (x)->size -= (dv); \
    } while (0)
Function Documentation
duk_hbuffer_alloc()
DUK_INTERNAL_DECL duk_hbuffer * duk_hbuffer_alloc (duk_heap * heap, duk_size_t size, duk_small_uint_t flags, void ** out_bufdata)
Definition at line 40476 of file duktape-1.5.2/src-noline/duktape.c.
{
    duk_hbuffer *res = NULL;
    duk_size_t header_size;
    duk_size_t alloc_size;
    DUK_ASSERT(heap != NULL);
    DUK_ASSERT(out_bufdata != NULL);
    DUK_DDD(DUK_DDDPRINT("allocate hbuffer"));
    /* Size sanity check.  Should not be necessary because caller is
     * required to check this, but we don't want to cause a segfault
     * if the size wraps either in duk_size_t computation or when
     * storing the size in a 16-bit field.
     */
    if (size > DUK_HBUFFER_MAX_BYTELEN) {
        DUK_D(DUK_DPRINT("hbuffer alloc failed: size too large: %ld", (long) size));
        return NULL;  /* no need to write 'out_bufdata' */
    }
    if (flags & DUK_BUF_FLAG_EXTERNAL) {
        header_size = sizeof(duk_hbuffer_external);
        alloc_size = sizeof(duk_hbuffer_external);
    } else if (flags & DUK_BUF_FLAG_DYNAMIC) {
        header_size = sizeof(duk_hbuffer_dynamic);
        alloc_size = sizeof(duk_hbuffer_dynamic);
    } else {
        header_size = sizeof(duk_hbuffer_fixed);
        alloc_size = sizeof(duk_hbuffer_fixed) + size;
        DUK_ASSERT(alloc_size >= sizeof(duk_hbuffer_fixed));  /* no wrapping */
    }
    res = (duk_hbuffer *) DUK_ALLOC(heap, alloc_size);
    if (!res) {
        goto error;
    }
    /* zero everything unless requested not to do so */
#if defined(DUK_USE_ZERO_BUFFER_DATA)
    DUK_MEMZERO((void *) res,
                (flags & DUK_BUF_FLAG_NOZERO) ? header_size : alloc_size);
#else
    DUK_MEMZERO((void *) res, header_size);
#endif
    if (flags & DUK_BUF_FLAG_EXTERNAL) {
        duk_hbuffer_external *h;
        h = (duk_hbuffer_external *) res;
        DUK_UNREF(h);
        *out_bufdata = NULL;
#if defined(DUK_USE_EXPLICIT_NULL_INIT)
#if defined(DUK_USE_HEAPPTR16)
/* the compressed pointer is zeroed which maps to NULL, so nothing to do. */
#else
        DUK_HBUFFER_EXTERNAL_SET_DATA_PTR(heap, h, NULL);
#endif
#endif
        DUK_ASSERT(DUK_HBUFFER_EXTERNAL_GET_DATA_PTR(heap, h) == NULL);
    } else if (flags & DUK_BUF_FLAG_DYNAMIC) {
        duk_hbuffer_dynamic *h = (duk_hbuffer_dynamic *) res;
        void *ptr;
        if (size > 0) {
            DUK_ASSERT(!(flags & DUK_BUF_FLAG_EXTERNAL));  /* alloc external with size zero */
            DUK_DDD(DUK_DDDPRINT("dynamic buffer with nonzero size, alloc actual buffer"));
#ifdef DUK_USE_ZERO_BUFFER_DATA
            ptr = DUK_ALLOC_ZEROED(heap, size);
#else
            ptr = DUK_ALLOC(heap, size);
#endif
            if (!ptr) {
                /* Because size > 0, NULL check is correct */
                goto error;
            }
            *out_bufdata = ptr;
            DUK_HBUFFER_DYNAMIC_SET_DATA_PTR(heap, h, ptr);
        } else {
            *out_bufdata = NULL;
#if defined(DUK_USE_EXPLICIT_NULL_INIT)
#if defined(DUK_USE_HEAPPTR16)
/* the compressed pointer is zeroed which maps to NULL, so nothing to do. */
#else
            DUK_HBUFFER_DYNAMIC_SET_DATA_PTR(heap, h, NULL);
#endif
#endif
            DUK_ASSERT(DUK_HBUFFER_DYNAMIC_GET_DATA_PTR(heap, h) == NULL);
        }
    } else {
        *out_bufdata = (void *) ((duk_hbuffer_fixed *) res + 1);
    }
    DUK_HBUFFER_SET_SIZE(res, size);
    DUK_HEAPHDR_SET_TYPE(&res->hdr, DUK_HTYPE_BUFFER);
    if (flags & DUK_BUF_FLAG_DYNAMIC) {
        DUK_HBUFFER_SET_DYNAMIC(res);
References DUK_ALLOC, DUK_ALLOC_ZEROED, DUK_ASSERT, DUK_BUF_FLAG_DYNAMIC, DUK_BUF_FLAG_EXTERNAL, DUK_BUF_FLAG_NOZERO, DUK_D, DUK_DD, DUK_DDD, DUK_DDDPRINT, DUK_DDPRINT, DUK_DPRINT, DUK_FREE, DUK_HBUFFER_DYNAMIC_GET_DATA_PTR, DUK_HBUFFER_DYNAMIC_SET_DATA_PTR, DUK_HBUFFER_EXTERNAL_GET_DATA_PTR, DUK_HBUFFER_EXTERNAL_SET_DATA_PTR, DUK_HBUFFER_MAX_BYTELEN, DUK_HBUFFER_SET_DYNAMIC, DUK_HBUFFER_SET_EXTERNAL, DUK_HBUFFER_SET_SIZE, DUK_HEAP_INSERT_INTO_HEAP_ALLOCATED, DUK_HEAPHDR_SET_TYPE, DUK_HTYPE_BUFFER, DUK_MEMZERO, DUK_UNREF, error(), duk_hbuffer::hdr, and NULL.
Referenced by duk_push_buffer_raw().
duk_hbuffer_get_dynalloc_ptr()
DUK_INTERNAL_DECL void * duk_hbuffer_get_dynalloc_ptr (duk_heap * heap, void * ud)
Definition at line 40593 of file duktape-1.5.2/src-noline/duktape.c.
           {
        DUK_ASSERT(!(flags & DUK_BUF_FLAG_EXTERNAL));
    }
        DUK_HEAP_INSERT_INTO_HEAP_ALLOCATED(heap, &res->hdr);
References DUK_HBUFFER_DYNAMIC_GET_DATA_PTR, and DUK_UNREF.
Referenced by duk_hbuffer_resize().
duk_hbuffer_reset()
DUK_INTERNAL_DECL void duk_hbuffer_reset (duk_hthread * thr, duk_hbuffer_dynamic * buf)
Definition at line 40672 of file duktape-1.5.2/src-noline/duktape.c.
{
            DUK_ASSERT(new_size - prev_size > 0);
#ifdef DUK_USE_ZERO_BUFFER_DATA
            DUK_MEMZERO((void *) ((char *) res + prev_size),
                        (duk_size_t) (new_size - prev_size));
#endif
        }
References DUK_ASSERT, DUK_HBUFFER_HAS_DYNAMIC, DUK_HBUFFER_HAS_EXTERNAL, duk_hbuffer_resize(), DUK_MEMZERO, and NULL.
Referenced by duk__reset_func_for_pass2().
duk_hbuffer_resize()
DUK_INTERNAL_DECL void duk_hbuffer_resize (duk_hthread * thr, duk_hbuffer_dynamic * buf, duk_size_t new_size)
Definition at line 40615 of file duktape-1.5.2/src-noline/duktape.c.
{
    void *res;
    duk_size_t prev_size;
    DUK_ASSERT(thr != NULL);
    DUK_ASSERT(buf != NULL);
    DUK_ASSERT(DUK_HBUFFER_HAS_DYNAMIC(buf));
    DUK_ASSERT(!DUK_HBUFFER_HAS_EXTERNAL(buf));
    /*
     *  Maximum size check
     */
    if (new_size > DUK_HBUFFER_MAX_BYTELEN) {
        DUK_ERROR_RANGE(thr, "buffer too long");
    }
    /*
     *  Note: use indirect realloc variant just in case mark-and-sweep
     *  (finalizers) might resize this same buffer during garbage
     *  collection.
     */
    res = DUK_REALLOC_INDIRECT(thr->heap, duk_hbuffer_get_dynalloc_ptr, (void *) buf, new_size);
    if (res != NULL || new_size == 0) {
        /* 'res' may be NULL if new allocation size is 0. */
        DUK_DDD(DUK_DDDPRINT("resized dynamic buffer %p:%ld -> %p:%ld",
                             (void *) DUK_HBUFFER_DYNAMIC_GET_DATA_PTR(thr->heap, buf),
                             (long) DUK_HBUFFER_DYNAMIC_GET_SIZE(buf),
                             (void *) res,
                             (long) new_size));
        /*
         *  The entire allocated buffer area, regardless of actual used
         *  size, is kept zeroed in resizes for simplicity.  If the buffer
         *  is grown, zero the new part.
         */
References DUK_ASSERT, DUK_DDD, DUK_DDDPRINT, DUK_ERROR_ALLOC_DEFMSG, DUK_ERROR_RANGE, DUK_HBUFFER_DYNAMIC_GET_DATA_PTR, DUK_HBUFFER_DYNAMIC_GET_SIZE, DUK_HBUFFER_DYNAMIC_SET_DATA_PTR, DUK_HBUFFER_DYNAMIC_SET_SIZE, duk_hbuffer_get_dynalloc_ptr(), DUK_HBUFFER_HAS_DYNAMIC, DUK_HBUFFER_HAS_EXTERNAL, DUK_HBUFFER_MAX_BYTELEN, DUK_MEMZERO, DUK_REALLOC_INDIRECT, duk_hthread::heap, and NULL.
Referenced by duk__add_label(), duk__appendbuffer(), duk__initbuffer(), duk__reset_labels_to_length(), duk_bw_compact(), duk_bw_resize(), duk_hbuffer_reset(), duk_hobject_pc2line_pack(), and duk_resize_buffer().