Github User Fetcher: duk_api_var.c File Reference
duk_api_var.c File Reference
#include "duk_internal.h"
Functions
DUK_EXTERNAL void duk_get_var (duk_context *ctx)
DUK_EXTERNAL void duk_put_var (duk_context *ctx)
DUK_EXTERNAL duk_bool_t duk_del_var (duk_context *ctx)
DUK_EXTERNAL duk_bool_t duk_has_var (duk_context *ctx)
Function Documentation
duk_del_var()
DUK_EXTERNAL duk_bool_t duk_del_var (duk_context * ctx)
Definition at line 74 of file duktape-1.5.2/src-separate/duk_api_var.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ERROR_UNIMPLEMENTED_DEFMSG((duk_hthread *) ctx);
    return 0;
}
References DUK_ASSERT_CTX_VALID, and DUK_ERROR_UNIMPLEMENTED_DEFMSG.
duk_get_var()
DUK_EXTERNAL void duk_get_var (duk_context * ctx)
Definition at line 7 of file duktape-1.5.2/src-separate/duk_api_var.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_activation *act;
    duk_hstring *h_varname;
    duk_small_int_t throw_flag = 1;  /* always throw ReferenceError for unresolvable */
    DUK_ASSERT_CTX_VALID(ctx);
    h_varname = duk_require_hstring(ctx, -1);  /* XXX: tostring? */
    DUK_ASSERT(h_varname != NULL);
    act = duk_hthread_get_current_activation(thr);
    if (act) {
        (void) duk_js_getvar_activation(thr, act, h_varname, throw_flag);  /* -> [ ... varname val this ] */
    } else {
        /* Outside any activation -> look up from global. */
        DUK_ASSERT(thr->builtins[DUK_BIDX_GLOBAL_ENV] != NULL);
        (void) duk_js_getvar_envrec(thr, thr->builtins[DUK_BIDX_GLOBAL_ENV], h_varname, throw_flag);
    }
    /* [ ... varname val this ]  (because throw_flag == 1, always resolved) */
    duk_pop(ctx);
    duk_remove(ctx, -2);
    /* [ ... val ] */
    /* Return value would be pointless: because throw_flag==1, we always
     * throw if the identifier doesn't resolve.
     */
    return;
}
References duk_hthread::builtins, DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_BIDX_GLOBAL_ENV, duk_hthread_get_current_activation(), duk_js_getvar_activation(), duk_js_getvar_envrec(), duk_pop(), duk_remove(), duk_require_hstring(), and NULL.
duk_has_var()
DUK_EXTERNAL duk_bool_t duk_has_var (duk_context * ctx)
Definition at line 81 of file duktape-1.5.2/src-separate/duk_api_var.c.
{
    DUK_ASSERT_CTX_VALID(ctx);
    DUK_ERROR_UNIMPLEMENTED_DEFMSG((duk_hthread *) ctx);
    return 0;
}
References DUK_ASSERT_CTX_VALID, and DUK_ERROR_UNIMPLEMENTED_DEFMSG.
duk_put_var()
DUK_EXTERNAL void duk_put_var (duk_context * ctx)
Definition at line 40 of file duktape-1.5.2/src-separate/duk_api_var.c.
{
    duk_hthread *thr = (duk_hthread *) ctx;
    duk_activation *act;
    duk_hstring *h_varname;
    duk_tval *tv_val;
    duk_small_int_t throw_flag;
    DUK_ASSERT_CTX_VALID(ctx);
    h_varname = duk_require_hstring(ctx, -2);  /* XXX: tostring? */
    DUK_ASSERT(h_varname != NULL);
    tv_val = duk_require_tval(ctx, -1);
    throw_flag = duk_is_strict_call(ctx);
    act = duk_hthread_get_current_activation(thr);
    if (act) {
        duk_js_putvar_activation(thr, act, h_varname, tv_val, throw_flag);  /* -> [ ... varname val this ] */
    } else {
        /* Outside any activation -> put to global. */
        DUK_ASSERT(thr->builtins[DUK_BIDX_GLOBAL_ENV] != NULL);
        duk_js_putvar_envrec(thr, thr->builtins[DUK_BIDX_GLOBAL_ENV], h_varname, tv_val, throw_flag);
    }
    /* [ ... varname val ] */
    duk_pop_2(ctx);
    /* [ ... ] */
    return;
}
References duk_hthread::builtins, DUK_ASSERT, DUK_ASSERT_CTX_VALID, DUK_BIDX_GLOBAL_ENV, duk_hthread_get_current_activation(), duk_is_strict_call(), duk_js_putvar_activation(), duk_js_putvar_envrec(), duk_pop_2(), duk_require_hstring(), duk_require_tval(), and NULL.