Github User Fetcher: easy.h File Reference
easy.h File Reference
Data Structures
struct curl_blob
Macros
#define CURL_BLOB_COPY 1 /* tell libcurl to copy the data */
#define CURL_BLOB_NOCOPY 0 /* tell libcurl to NOT copy the data */
Functions
CURL_EXTERN CURL * curl_easy_init (void)
CURL_EXTERN CURLcode curl_easy_setopt (CURL *curl, CURLoption option,...)
CURL_EXTERN CURLcode curl_easy_perform (CURL *curl)
CURL_EXTERN void curl_easy_cleanup (CURL *curl)
CURL_EXTERN CURLcode curl_easy_getinfo (CURL *curl, CURLINFO info,...)
CURL_EXTERN CURL * curl_easy_duphandle (CURL *curl)
CURL_EXTERN void curl_easy_reset (CURL *curl)
CURL_EXTERN CURLcode curl_easy_recv (CURL *curl, void *buffer, size_t buflen, size_t *n)
CURL_EXTERN CURLcode curl_easy_send (CURL *curl, const void *buffer, size_t buflen, size_t *n)
CURL_EXTERN CURLcode curl_easy_upkeep (CURL *curl)
Macro Definition Documentation
CURL_BLOB_COPY
#define CURL_BLOB_COPY 1 /* tell libcurl to copy the data */
Definition at line 31 of file easy.h.
CURL_BLOB_NOCOPY
#define CURL_BLOB_NOCOPY 0 /* tell libcurl to NOT copy the data */
Definition at line 32 of file easy.h.
Function Documentation
curl_easy_cleanup()
CURL_EXTERN void curl_easy_cleanup (CURL * curl)
Referenced by fetch_github_user().
curl_easy_duphandle()
CURL_EXTERN CURL * curl_easy_duphandle (CURL * curl)
curl_easy_getinfo()
CURL_EXTERN CURLcode curl_easy_getinfo (CURL * curl, CURLINFO info, ...)
curl_easy_init()
CURL_EXTERN CURL * curl_easy_init (void)
Referenced by fetch_github_user().
curl_easy_perform()
CURL_EXTERN CURLcode curl_easy_perform (CURL * curl)
Referenced by fetch_github_user().
curl_easy_recv()
CURL_EXTERN CURLcode curl_easy_recv (CURL * curl, void * buffer, size_t buflen, size_t * n)
curl_easy_reset()
CURL_EXTERN void curl_easy_reset (CURL * curl)
curl_easy_send()
CURL_EXTERN CURLcode curl_easy_send (CURL * curl, const void * buffer, size_t buflen, size_t * n)
curl_easy_setopt()
CURL_EXTERN CURLcode curl_easy_setopt (CURL * curl, CURLoption option, ...)
curl_easy_upkeep()
CURL_EXTERN CURLcode curl_easy_upkeep (CURL * curl)