Github User Fetcher: gdataset.h File Reference
gdataset.h File Reference
#include <glib/gquark.h>
Macros
#define G_DATALIST_FLAGS_MASK 0x3
#define g_datalist_id_set_data(dl, q, d) g_datalist_id_set_data_full ((dl), (q), (d), NULL)
#define g_datalist_id_remove_data(dl, q) g_datalist_id_set_data ((dl), (q), NULL)
#define g_datalist_set_data_full(dl, k, d, f) g_datalist_id_set_data_full ((dl), g_quark_from_string (k), (d), (f))
#define g_datalist_remove_no_notify(dl, k) g_datalist_id_remove_no_notify ((dl), g_quark_try_string (k))
#define g_datalist_set_data(dl, k, d) g_datalist_set_data_full ((dl), (k), (d), NULL)
#define g_datalist_remove_data(dl, k) g_datalist_id_set_data ((dl), g_quark_try_string (k), NULL)
#define g_dataset_id_set_data(l, k, d) g_dataset_id_set_data_full ((l), (k), (d), NULL)
#define g_dataset_id_remove_data(l, k) g_dataset_id_set_data ((l), (k), NULL)
#define g_dataset_get_data(l, k) (g_dataset_id_get_data ((l), g_quark_try_string (k)))
#define g_dataset_set_data_full(l, k, d, f) g_dataset_id_set_data_full ((l), g_quark_from_string (k), (d), (f))
#define g_dataset_remove_no_notify(l, k) g_dataset_id_remove_no_notify ((l), g_quark_try_string (k))
#define g_dataset_set_data(l, k, d) g_dataset_set_data_full ((l), (k), (d), NULL)
#define g_dataset_remove_data(l, k) g_dataset_id_set_data ((l), g_quark_try_string (k), NULL)
Typedefs
typedef typedefG_BEGIN_DECLS struct _GData GData
typedef void(* GDataForeachFunc) (GQuark key_id, gpointer data, gpointer user_data)
typedef gpointer(* GDuplicateFunc) (gpointer data, gpointer user_data)
Functions
GLIB_AVAILABLE_IN_ALL void g_datalist_init (GData **datalist)
GLIB_AVAILABLE_IN_ALL void g_datalist_clear (GData **datalist)
GLIB_AVAILABLE_IN_ALL gpointer g_datalist_id_get_data (GData **datalist, GQuark key_id)
GLIB_AVAILABLE_IN_ALL void g_datalist_id_set_data_full (GData **datalist, GQuark key_id, gpointer data, GDestroyNotify destroy_func)
GLIB_AVAILABLE_IN_2_74 void g_datalist_id_remove_multiple (GData **datalist, GQuark *keys, gsize n_keys)
GLIB_AVAILABLE_IN_2_34 gpointer g_datalist_id_dup_data (GData **datalist, GQuark key_id, GDuplicateFunc dup_func, gpointer user_data)
GLIB_AVAILABLE_IN_2_34 gboolean g_datalist_id_replace_data (GData **datalist, GQuark key_id, gpointer oldval, gpointer newval, GDestroyNotify destroy, GDestroyNotify *old_destroy)
GLIB_AVAILABLE_IN_ALL gpointer g_datalist_id_remove_no_notify (GData **datalist, GQuark key_id)
GLIB_AVAILABLE_IN_ALL void g_datalist_foreach (GData **datalist, GDataForeachFunc func, gpointer user_data)
GLIB_AVAILABLE_IN_ALL void g_datalist_set_flags (GData **datalist, guint flags)
GLIB_AVAILABLE_IN_ALL void g_datalist_unset_flags (GData **datalist, guint flags)
GLIB_AVAILABLE_IN_ALL guint g_datalist_get_flags (GData **datalist)
GLIB_AVAILABLE_IN_ALL void g_dataset_destroy (gconstpointer dataset_location)
GLIB_AVAILABLE_IN_ALL gpointer g_dataset_id_get_data (gconstpointer dataset_location, GQuark key_id)
GLIB_AVAILABLE_IN_ALL gpointer g_datalist_get_data (GData **datalist, const gchar *key)
GLIB_AVAILABLE_IN_ALL void g_dataset_id_set_data_full (gconstpointer dataset_location, GQuark key_id, gpointer data, GDestroyNotify destroy_func)
GLIB_AVAILABLE_IN_ALL gpointer g_dataset_id_remove_no_notify (gconstpointer dataset_location, GQuark key_id)
GLIB_AVAILABLE_IN_ALL void g_dataset_foreach (gconstpointer dataset_location, GDataForeachFunc func, gpointer user_data)
Macro Definition Documentation
G_DATALIST_FLAGS_MASK
#define G_DATALIST_FLAGS_MASK 0x3
G_DATALIST_FLAGS_MASK:
A bitmask that restricts the possible flags passed to g_datalist_set_flags(). Passing a flags value where flags & ~G_DATALIST_FLAGS_MASK != 0 is an error.
Definition at line 93 of file gdataset.h.
g_datalist_id_remove_data
#define g_datalist_id_remove_data (dl, q) g_datalist_id_set_data ((dl), (q), NULL)
Definition at line 106 of file gdataset.h.
#define   g_datalist_id_remove_data(dl, q)      \
     g_datalist_id_set_data ((dl), (q), NULL)
g_datalist_id_set_data
#define g_datalist_id_set_data (dl, q, d) g_datalist_id_set_data_full ((dl), (q), (d), NULL)
Definition at line 104 of file gdataset.h.
#define   g_datalist_id_set_data(dl, q, d)      \
     g_datalist_id_set_data_full ((dl), (q), (d), NULL)
Referenced by g_object_notify_queue_thaw().
g_datalist_remove_data
#define g_datalist_remove_data (dl, k) g_datalist_id_set_data ((dl), g_quark_try_string (k), NULL)
Definition at line 114 of file gdataset.h.
#define   g_datalist_remove_data(dl, k)         \
     g_datalist_id_set_data ((dl), g_quark_try_string (k), NULL)
g_datalist_remove_no_notify
#define g_datalist_remove_no_notify (dl, k) g_datalist_id_remove_no_notify ((dl), g_quark_try_string (k))
Definition at line 110 of file gdataset.h.
#define   g_datalist_remove_no_notify(dl, k)    \
     g_datalist_id_remove_no_notify ((dl), g_quark_try_string (k))
g_datalist_set_data
#define g_datalist_set_data (dl, k, d) g_datalist_set_data_full ((dl), (k), (d), NULL)
Definition at line 112 of file gdataset.h.
#define   g_datalist_set_data(dl, k, d)         \
     g_datalist_set_data_full ((dl), (k), (d), NULL)
g_datalist_set_data_full
#define g_datalist_set_data_full (dl, k, d, f) g_datalist_id_set_data_full ((dl), g_quark_from_string (k), (d), (f))
Definition at line 108 of file gdataset.h.
#define   g_datalist_set_data_full(dl, k, d, f) \
     g_datalist_id_set_data_full ((dl), g_quark_from_string (k), (d), (f))
g_dataset_get_data
#define g_dataset_get_data (l, k) (g_dataset_id_get_data ((l), g_quark_try_string (k)))
Definition at line 143 of file gdataset.h.
#define   g_dataset_get_data(l, k)              \
     (g_dataset_id_get_data ((l), g_quark_try_string (k)))
g_dataset_id_remove_data
#define g_dataset_id_remove_data (l, k) g_dataset_id_set_data ((l), (k), NULL)
Definition at line 141 of file gdataset.h.
#define   g_dataset_id_remove_data(l, k)        \
     g_dataset_id_set_data ((l), (k), NULL)
g_dataset_id_set_data
#define g_dataset_id_set_data (l, k, d) g_dataset_id_set_data_full ((l), (k), (d), NULL)
Definition at line 139 of file gdataset.h.
#define   g_dataset_id_set_data(l, k, d)        \
     g_dataset_id_set_data_full ((l), (k), (d), NULL)
g_dataset_remove_data
#define g_dataset_remove_data (l, k) g_dataset_id_set_data ((l), g_quark_try_string (k), NULL)
Definition at line 151 of file gdataset.h.
#define   g_dataset_remove_data(l, k)           \
     g_dataset_id_set_data ((l), g_quark_try_string (k), NULL)
g_dataset_remove_no_notify
#define g_dataset_remove_no_notify (l, k) g_dataset_id_remove_no_notify ((l), g_quark_try_string (k))
Definition at line 147 of file gdataset.h.
#define   g_dataset_remove_no_notify(l, k)      \
     g_dataset_id_remove_no_notify ((l), g_quark_try_string (k))
g_dataset_set_data
#define g_dataset_set_data (l, k, d) g_dataset_set_data_full ((l), (k), (d), NULL)
Definition at line 149 of file gdataset.h.
#define   g_dataset_set_data(l, k, d)           \
     g_dataset_set_data_full ((l), (k), (d), NULL)
g_dataset_set_data_full
#define g_dataset_set_data_full (l, k, d, f) g_dataset_id_set_data_full ((l), g_quark_from_string (k), (d), (f))
Definition at line 145 of file gdataset.h.
#define   g_dataset_set_data_full(l, k, d, f)   \
     g_dataset_id_set_data_full ((l), g_quark_from_string (k), (d), (f))
Typedef Documentation
GData
typedef typedefG_BEGIN_DECLS struct _GData GData
Definition at line 38 of file gdataset.h.
GDataForeachFunc
typedef void(* GDataForeachFunc) (GQuark key_id, gpointer data, gpointer user_data)
Definition at line 40 of file gdataset.h.
GDuplicateFunc
typedef gpointer(* GDuplicateFunc) (gpointer data, gpointer user_data)
Definition at line 63 of file gdataset.h.
Function Documentation
g_datalist_clear()
GLIB_AVAILABLE_IN_ALL void g_datalist_clear (GData ** datalist)
g_datalist_foreach()
GLIB_AVAILABLE_IN_ALL void g_datalist_foreach (GData ** datalist, GDataForeachFunc func, gpointer user_data)
g_datalist_get_data()
GLIB_AVAILABLE_IN_ALL gpointer g_datalist_get_data (GData ** datalist, const gchar * key)
g_datalist_get_flags()
GLIB_AVAILABLE_IN_ALL guint g_datalist_get_flags (GData ** datalist)
g_datalist_id_dup_data()
GLIB_AVAILABLE_IN_2_34 gpointer g_datalist_id_dup_data (GData ** datalist, GQuark key_id, GDuplicateFunc dup_func, gpointer user_data)
g_datalist_id_get_data()
GLIB_AVAILABLE_IN_ALL gpointer g_datalist_id_get_data (GData ** datalist, GQuark key_id)
Referenced by g_object_notify_queue_freeze(), and g_object_notify_queue_from_object().
g_datalist_id_remove_multiple()
GLIB_AVAILABLE_IN_2_74 void g_datalist_id_remove_multiple (GData ** datalist, GQuark * keys, gsize n_keys)
g_datalist_id_remove_no_notify()
GLIB_AVAILABLE_IN_ALL gpointer g_datalist_id_remove_no_notify (GData ** datalist, GQuark key_id)
g_datalist_id_replace_data()
GLIB_AVAILABLE_IN_2_34 gboolean g_datalist_id_replace_data (GData ** datalist, GQuark key_id, gpointer oldval, gpointer newval, GDestroyNotify destroy, GDestroyNotify * old_destroy)
g_datalist_id_set_data_full()
GLIB_AVAILABLE_IN_ALL void g_datalist_id_set_data_full (GData ** datalist, GQuark key_id, gpointer data, GDestroyNotify destroy_func)
Referenced by g_object_notify_queue_freeze().
g_datalist_init()
GLIB_AVAILABLE_IN_ALL void g_datalist_init (GData ** datalist)
g_datalist_set_flags()
GLIB_AVAILABLE_IN_ALL void g_datalist_set_flags (GData ** datalist, guint flags)
g_datalist_unset_flags()
GLIB_AVAILABLE_IN_ALL void g_datalist_unset_flags (GData ** datalist, guint flags)
g_dataset_destroy()
GLIB_AVAILABLE_IN_ALL void g_dataset_destroy (gconstpointer dataset_location)
g_dataset_foreach()
GLIB_AVAILABLE_IN_ALL void g_dataset_foreach (gconstpointer dataset_location, GDataForeachFunc func, gpointer user_data)
g_dataset_id_get_data()
GLIB_AVAILABLE_IN_ALL gpointer g_dataset_id_get_data (gconstpointer dataset_location, GQuark key_id)
g_dataset_id_remove_no_notify()
GLIB_AVAILABLE_IN_ALL gpointer g_dataset_id_remove_no_notify (gconstpointer dataset_location, GQuark key_id)
g_dataset_id_set_data_full()
GLIB_AVAILABLE_IN_ALL void g_dataset_id_set_data_full (gconstpointer dataset_location, GQuark key_id, gpointer data, GDestroyNotify destroy_func)