Github User Fetcher: gobjectnotifyqueue.c File Reference
gobjectnotifyqueue.c File Reference
#include <string.h>
#include <glib-object.h>
Data Structures
struct _GObjectNotifyContext
struct _GObjectNotifyQueue
Macros
#define __G_OBJECT_NOTIFY_QUEUE_H__
Typedefs
typedef typedefG_BEGIN_DECLS struct _GObjectNotifyContext GObjectNotifyContext
typedef struct _GObjectNotifyQueue GObjectNotifyQueue
typedef void(* GObjectNotifyQueueDispatcher) (GObject *object, guint n_pspecs, GParamSpec **pspecs)
Functions
G_LOCK_DEFINE_STATIC (notify_lock)
static void g_object_notify_queue_free (gpointer data)
static GObjectNotifyQueue * g_object_notify_queue_freeze (GObject *object, GObjectNotifyContext *context)
static void g_object_notify_queue_thaw (GObject *object, GObjectNotifyQueue *nqueue)
static void g_object_notify_queue_clear (GObject *object G_GNUC_UNUSED, GObjectNotifyQueue *nqueue)
static void g_object_notify_queue_add (GObject *object G_GNUC_UNUSED, GObjectNotifyQueue *nqueue, GParamSpec *pspec)
static GObjectNotifyQueue * g_object_notify_queue_from_object (GObject *object, GObjectNotifyContext *context)
Macro Definition Documentation
__G_OBJECT_NOTIFY_QUEUE_H__
#define __G_OBJECT_NOTIFY_QUEUE_H__
Definition at line 28 of file gobjectnotifyqueue.c.
Typedef Documentation
GObjectNotifyContext
typedef typedefG_BEGIN_DECLS struct _GObjectNotifyContext GObjectNotifyContext
Definition at line 38 of file gobjectnotifyqueue.c.
GObjectNotifyQueue
typedef struct _GObjectNotifyQueue GObjectNotifyQueue
Definition at line 39 of file gobjectnotifyqueue.c.
GObjectNotifyQueueDispatcher
typedef void(* GObjectNotifyQueueDispatcher) (GObject *object, guint n_pspecs, GParamSpec **pspecs)
Definition at line 40 of file gobjectnotifyqueue.c.
Function Documentation
G_LOCK_DEFINE_STATIC()
G_LOCK_DEFINE_STATIC (notify_lock)
g_object_notify_queue_add()
static void g_object_notify_queue_add (GObject *object G_GNUC_UNUSED, GObjectNotifyQueue * nqueue, GParamSpec * pspec) inline static
Definition at line 159 of file gobjectnotifyqueue.c.
{
  if (pspec->flags & G_PARAM_READABLE)
    {
      GParamSpec *redirect;
      G_LOCK(notify_lock);
      g_return_if_fail (nqueue->n_pspecs < 65535);
      redirect = g_param_spec_get_redirect_target (pspec);
      if (redirect)
    pspec = redirect;
      /* we do the deduping in _thaw */
      if (g_slist_find (nqueue->pspecs, pspec) == NULL)
        {
          nqueue->pspecs = g_slist_prepend (nqueue->pspecs, pspec);
          nqueue->n_pspecs++;
        }
      G_UNLOCK(notify_lock);
    }
}
References _GParamSpec::flags, G_LOCK, G_PARAM_READABLE, g_param_spec_get_redirect_target(), g_return_if_fail, g_slist_find(), g_slist_prepend(), G_UNLOCK, _GObjectNotifyQueue::n_pspecs, NULL, and _GObjectNotifyQueue::pspecs.
g_object_notify_queue_clear()
static void g_object_notify_queue_clear (GObject *object G_GNUC_UNUSED, GObjectNotifyQueue * nqueue) inline static
Definition at line 144 of file gobjectnotifyqueue.c.
{
  g_return_if_fail (nqueue->freeze_count > 0);
  G_LOCK(notify_lock);
  g_slist_free (nqueue->pspecs);
  nqueue->pspecs = NULL;
  nqueue->n_pspecs = 0;
  G_UNLOCK(notify_lock);
}
References _GObjectNotifyQueue::freeze_count, G_LOCK, g_return_if_fail, g_slist_free(), G_UNLOCK, _GObjectNotifyQueue::n_pspecs, NULL, and _GObjectNotifyQueue::pspecs.
g_object_notify_queue_free()
static void g_object_notify_queue_free (gpointer data) static
Definition at line 64 of file gobjectnotifyqueue.c.
{
  GObjectNotifyQueue *nqueue = data;
  g_slist_free (nqueue->pspecs);
  g_slice_free (GObjectNotifyQueue, nqueue);
}
References g_slice_free, g_slist_free(), and _GObjectNotifyQueue::pspecs.
Referenced by g_object_notify_queue_freeze().
g_object_notify_queue_freeze()
static GObjectNotifyQueue * g_object_notify_queue_freeze (GObject * object, GObjectNotifyContext * context) inline static
Definition at line 73 of file gobjectnotifyqueue.c.
{
  GObjectNotifyQueue *nqueue;
  G_LOCK(notify_lock);
  nqueue = g_datalist_id_get_data (&object->qdata, context->quark_notify_queue);
  if (!nqueue)
    {
      nqueue = g_slice_new0 (GObjectNotifyQueue);
      nqueue->context = context;
      g_datalist_id_set_data_full (&object->qdata, context->quark_notify_queue,
                   nqueue, g_object_notify_queue_free);
    }
  if (nqueue->freeze_count >= 65535)
    g_critical("Free queue for %s (%p) is larger than 65535,"
               " called g_object_freeze_notify() too often."
               " Forgot to call g_object_thaw_notify() or infinite loop",
               G_OBJECT_TYPE_NAME (object), object);
  else
    nqueue->freeze_count++;
  G_UNLOCK(notify_lock);
  return nqueue;
}
References _GObjectNotifyQueue::context, _GObjectNotifyQueue::freeze_count, g_critical, g_datalist_id_get_data(), g_datalist_id_set_data_full(), G_LOCK, g_object_notify_queue_free(), G_OBJECT_TYPE_NAME, g_slice_new0, G_UNLOCK, and _GObject::qdata.
g_object_notify_queue_from_object()
static GObjectNotifyQueue * g_object_notify_queue_from_object (GObject * object, GObjectNotifyContext * context) inline static
Definition at line 192 of file gobjectnotifyqueue.c.
{
  return g_datalist_id_get_data (&object->qdata, context->quark_notify_queue);
}
References g_datalist_id_get_data(), and _GObject::qdata.
g_object_notify_queue_thaw()
static void g_object_notify_queue_thaw (GObject * object, GObjectNotifyQueue * nqueue) inline static
Definition at line 101 of file gobjectnotifyqueue.c.
{
  GObjectNotifyContext *context = nqueue->context;
  GParamSpec *pspecs_mem[16], **pspecs, **free_me = NULL;
  GSList *slist;
  guint n_pspecs = 0;
  g_return_if_fail (nqueue->freeze_count > 0);
  g_return_if_fail (g_atomic_int_get(&object->ref_count) > 0);
  G_LOCK(notify_lock);
  /* Just make sure we never get into some nasty race condition */
  if (G_UNLIKELY(nqueue->freeze_count == 0)) {
    G_UNLOCK(notify_lock);
    g_critical ("%s: property-changed notification for %s(%p) is not frozen",
            G_STRFUNC, G_OBJECT_TYPE_NAME (object), object);
    return;
  }
  nqueue->freeze_count--;
  if (nqueue->freeze_count) {
    G_UNLOCK(notify_lock);
    return;
  }
  pspecs = nqueue->n_pspecs > 16 ? free_me = g_new (GParamSpec*, nqueue->n_pspecs) : pspecs_mem;
  for (slist = nqueue->pspecs; slist; slist = slist->next)
    {
      pspecs[n_pspecs++] = slist->data;
    }
  g_datalist_id_set_data (&object->qdata, context->quark_notify_queue, NULL);
  G_UNLOCK(notify_lock);
  if (n_pspecs)
    context->dispatcher (object, n_pspecs, pspecs);
  g_free (free_me);
}
References _GObjectNotifyQueue::context, _GObjectNotifyQueue::freeze_count, g_atomic_int_get, g_critical, g_datalist_id_set_data, g_free(), G_LOCK, g_new, G_OBJECT_TYPE_NAME, g_return_if_fail, G_STRFUNC, G_UNLIKELY, G_UNLOCK, _GObjectNotifyQueue::n_pspecs, NULL, _GObjectNotifyQueue::pspecs, _GObject::qdata, and _GObject::ref_count.