Github User Fetcher: gslist.h File Reference
gslist.h File Reference
#include <glib/gmem.h>
#include <glib/gnode.h>
Data Structures
struct _GSList
Macros
#define g_slist_free1 g_slist_free_1
#define g_clear_slist(slist_ptr, destroy)
#define g_slist_next(slist) ((slist) ? (((GSList *)(slist))->next) : NULL)
Typedefs
typedef typedefG_BEGIN_DECLS struct _GSList GSList
Functions
GLIB_AVAILABLE_IN_ALL GSList * g_slist_alloc (void) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL void g_slist_free (GSList *list)
GLIB_AVAILABLE_IN_ALL void g_slist_free_1 (GSList *list)
GLIB_AVAILABLE_IN_ALL void g_slist_free_full (GSList *list, GDestroyNotify free_func)
GLIB_AVAILABLE_IN_ALL GSList * g_slist_append (GSList *list, gpointer data) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_prepend (GSList *list, gpointer data) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_insert (GSList *list, gpointer data, gint position) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_insert_sorted (GSList *list, gpointer data, GCompareFunc func) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_insert_sorted_with_data (GSList *list, gpointer data, GCompareDataFunc func, gpointer user_data) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_insert_before (GSList *slist, GSList *sibling, gpointer data) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_concat (GSList *list1, GSList *list2) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_remove (GSList *list, gconstpointer data) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_remove_all (GSList *list, gconstpointer data) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_remove_link (GSList *list, GSList *link_) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_delete_link (GSList *list, GSList *link_) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_reverse (GSList *list) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_copy (GSList *list) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_2_34 GSList * g_slist_copy_deep (GSList *list, GCopyFunc func, gpointer user_data) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_nth (GSList *list, guint n)
GLIB_AVAILABLE_IN_ALL GSList * g_slist_find (GSList *list, gconstpointer data)
GLIB_AVAILABLE_IN_ALL GSList * g_slist_find_custom (GSList *list, gconstpointer data, GCompareFunc func)
GLIB_AVAILABLE_IN_ALL gint g_slist_position (GSList *list, GSList *llink)
GLIB_AVAILABLE_IN_ALL gint g_slist_index (GSList *list, gconstpointer data)
GLIB_AVAILABLE_IN_ALL GSList * g_slist_last (GSList *list)
GLIB_AVAILABLE_IN_ALL guint g_slist_length (GSList *list)
GLIB_AVAILABLE_IN_ALL void g_slist_foreach (GSList *list, GFunc func, gpointer user_data)
GLIB_AVAILABLE_IN_ALL GSList * g_slist_sort (GSList *list, GCompareFunc compare_func) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL GSList * g_slist_sort_with_data (GSList *list, GCompareDataFunc compare_func, gpointer user_data) G_GNUC_WARN_UNUSED_RESULT
GLIB_AVAILABLE_IN_ALL gpointer g_slist_nth_data (GSList *list, guint n)
GLIB_AVAILABLE_IN_2_64 void g_clear_slist (GSList **slist_ptr, GDestroyNotify destroy)
Macro Definition Documentation
g_clear_slist
#define g_clear_slist (slist_ptr, destroy)
Value:
  G_STMT_START {                                 \
    GSList *_slist;                              \
                                                 \
    _slist = *(slist_ptr);                       \
    if (_slist)                                  \
      {                                          \
        *slist_ptr = NULL;                       \
                                                 \
        if ((destroy) != NULL)                   \
          g_slist_free_full (_slist, (destroy)); \
        else                                     \
          g_slist_free (_slist);                 \
      }                                          \
  } G_STMT_END                                   \
  GLIB_AVAILABLE_MACRO_IN_2_64
Definition at line 145 of file gslist.h.
#define  g_clear_slist(slist_ptr, destroy)       \
  G_STMT_START {                                 \
    GSList *_slist;                              \
                                                 \
    _slist = *(slist_ptr);                       \
    if (_slist)                                  \
      {                                          \
        *slist_ptr = NULL;                       \
                                                 \
        if ((destroy) != NULL)                   \
          g_slist_free_full (_slist, (destroy)); \
        else                                     \
          g_slist_free (_slist);                 \
      }                                          \
  } G_STMT_END                                   \
  GLIB_AVAILABLE_MACRO_IN_2_64
g_slist_free1
#define g_slist_free1 g_slist_free_1
Definition at line 55 of file gslist.h.
g_slist_next
#define g_slist_next (slist) ((slist) ? (((GSList *)(slist))->next) : NULL)
Definition at line 162 of file gslist.h.
Typedef Documentation
GSList
typedef typedefG_BEGIN_DECLS struct _GSList GSList
Definition at line 39 of file gslist.h.
Function Documentation
g_clear_slist()
GLIB_AVAILABLE_IN_2_64 void g_clear_slist (GSList ** slist_ptr, GDestroyNotify destroy)
g_slist_alloc()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_alloc (void)
g_slist_append()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_append (GSList * list, gpointer data)
g_slist_concat()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_concat (GSList * list1, GSList * list2)
g_slist_copy()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_copy (GSList * list)
g_slist_copy_deep()
GLIB_AVAILABLE_IN_2_34 GSList * g_slist_copy_deep (GSList * list, GCopyFunc func, gpointer user_data)
g_slist_delete_link()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_delete_link (GSList * list, GSList * link_)
g_slist_find()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_find (GSList * list, gconstpointer data)
Referenced by g_object_notify_queue_add().
g_slist_find_custom()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_find_custom (GSList * list, gconstpointer data, GCompareFunc func)
g_slist_foreach()
GLIB_AVAILABLE_IN_ALL void g_slist_foreach (GSList * list, GFunc func, gpointer user_data)
g_slist_free()
GLIB_AVAILABLE_IN_ALL void g_slist_free (GSList * list)
Referenced by g_object_notify_queue_clear(), and g_object_notify_queue_free().
g_slist_free_1()
GLIB_AVAILABLE_IN_ALL void g_slist_free_1 (GSList * list)
g_slist_free_full()
GLIB_AVAILABLE_IN_ALL void g_slist_free_full (GSList * list, GDestroyNotify free_func)
g_slist_index()
GLIB_AVAILABLE_IN_ALL gint g_slist_index (GSList * list, gconstpointer data)
g_slist_insert()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_insert (GSList * list, gpointer data, gint position)
g_slist_insert_before()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_insert_before (GSList * slist, GSList * sibling, gpointer data)
g_slist_insert_sorted()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_insert_sorted (GSList * list, gpointer data, GCompareFunc func)
g_slist_insert_sorted_with_data()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_insert_sorted_with_data (GSList * list, gpointer data, GCompareDataFunc func, gpointer user_data)
g_slist_last()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_last (GSList * list)
g_slist_length()
GLIB_AVAILABLE_IN_ALL guint g_slist_length (GSList * list)
g_slist_nth()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_nth (GSList * list, guint n)
g_slist_nth_data()
GLIB_AVAILABLE_IN_ALL gpointer g_slist_nth_data (GSList * list, guint n)
g_slist_position()
GLIB_AVAILABLE_IN_ALL gint g_slist_position (GSList * list, GSList * llink)
g_slist_prepend()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_prepend (GSList * list, gpointer data)
Referenced by g_object_notify_queue_add().
g_slist_remove()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_remove (GSList * list, gconstpointer data)
g_slist_remove_all()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_remove_all (GSList * list, gconstpointer data)
g_slist_remove_link()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_remove_link (GSList * list, GSList * link_)
g_slist_reverse()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_reverse (GSList * list)
g_slist_sort()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_sort (GSList * list, GCompareFunc compare_func)
g_slist_sort_with_data()
GLIB_AVAILABLE_IN_ALL GSList * g_slist_sort_with_data (GSList * list, GCompareDataFunc compare_func, gpointer user_data)