Github User Fetcher: gstdio.h File Reference
gstdio.h File Reference
#include <glib/gprintf.h>
#include <errno.h>
#include <sys/stat.h>
Macros
#define g_chmod chmod
#define g_open open
#define g_creat creat
#define g_rename rename
#define g_mkdir mkdir
#define g_stat stat
#define g_lstat lstat
#define g_remove remove
#define g_fopen fopen
#define g_freopen freopen
#define g_fsync fsync
#define g_utime utime
Typedefs
typedef typedefG_BEGIN_DECLS struct stat GStatBuf
Functions
GLIB_AVAILABLE_IN_ALL int g_access (const gchar *filename, int mode)
GLIB_AVAILABLE_IN_ALL int g_chdir (const gchar *path)
GLIB_AVAILABLE_IN_ALL int g_unlink (const gchar *filename)
GLIB_AVAILABLE_IN_ALL int g_rmdir (const gchar *filename)
GLIB_AVAILABLE_IN_2_36 gboolean g_close (gint fd, GError **error)
static GLIB_AVAILABLE_STATIC_INLINE_IN_2_76 gboolean g_clear_fd (int *fd_ptr, GError **error)
Macro Definition Documentation
g_chmod
#define g_chmod chmod
Definition at line 72 of file gstdio.h.
g_creat
#define g_creat creat
Definition at line 74 of file gstdio.h.
g_fopen
#define g_fopen fopen
Definition at line 80 of file gstdio.h.
g_freopen
#define g_freopen freopen
Definition at line 81 of file gstdio.h.
g_fsync
#define g_fsync fsync
Definition at line 82 of file gstdio.h.
g_lstat
#define g_lstat lstat
Definition at line 78 of file gstdio.h.
g_mkdir
#define g_mkdir mkdir
Definition at line 76 of file gstdio.h.
g_open
#define g_open open
Definition at line 73 of file gstdio.h.
g_remove
#define g_remove remove
Definition at line 79 of file gstdio.h.
g_rename
#define g_rename rename
Definition at line 75 of file gstdio.h.
g_stat
#define g_stat stat
Definition at line 77 of file gstdio.h.
g_utime
#define g_utime utime
Definition at line 83 of file gstdio.h.
Typedef Documentation
GStatBuf
typedef typedefG_BEGIN_DECLS struct stat GStatBuf
Definition at line 56 of file gstdio.h.
Function Documentation
g_access()
GLIB_AVAILABLE_IN_ALL int g_access (const gchar * filename, int mode)
g_chdir()
GLIB_AVAILABLE_IN_ALL int g_chdir (const gchar * path)
g_clear_fd()
static GLIB_AVAILABLE_STATIC_INLINE_IN_2_76 gboolean g_clear_fd (int * fd_ptr, GError ** error) inline static
Definition at line 184 of file gstdio.h.
{
  int fd = *fd_ptr;
  *fd_ptr = -1;
  if (fd < 0)
    return TRUE;
  /* Suppress "Not available before" warning */
  G_GNUC_BEGIN_IGNORE_DEPRECATIONS
  return g_close (fd, error);
  G_GNUC_END_IGNORE_DEPRECATIONS
}
References error(), g_close(), G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and TRUE.
Referenced by g_unix_pipe_close().
g_close()
GLIB_AVAILABLE_IN_2_36 gboolean g_close (gint fd, GError ** error)
Referenced by g_clear_fd().
g_rmdir()
GLIB_AVAILABLE_IN_ALL int g_rmdir (const gchar * filename)
g_unlink()
GLIB_AVAILABLE_IN_ALL int g_unlink (const gchar * filename)