Github User Fetcher: gstrfuncs.h File Reference
gstrfuncs.h File Reference
#include <stdarg.h>
#include <string.h>
#include <glib/gmacros.h>
#include <glib/gtypes.h>
#include <glib/gerror.h>
#include <glib/gmem.h>
Macros
#define g_ascii_isalnum(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_ALNUM) != 0)
#define g_ascii_isalpha(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_ALPHA) != 0)
#define g_ascii_iscntrl(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_CNTRL) != 0)
#define g_ascii_isdigit(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_DIGIT) != 0)
#define g_ascii_isgraph(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_GRAPH) != 0)
#define g_ascii_islower(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_LOWER) != 0)
#define g_ascii_isprint(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_PRINT) != 0)
#define g_ascii_ispunct(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_PUNCT) != 0)
#define g_ascii_isspace(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_SPACE) != 0)
#define g_ascii_isupper(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_UPPER) != 0)
#define g_ascii_isxdigit(c) ((g_ascii_table[(guchar) (c)] & G_ASCII_XDIGIT) != 0)
#define G_STR_DELIMITERS "_-|> <."
#define G_ASCII_DTOSTR_BUF_SIZE (29 + 10)
#define g_strstrip(string) g_strchomp (g_strchug (string))
#define G_NUMBER_PARSER_ERROR (g_number_parser_error_quark ())
Typedefs
typedef gchar ** GStrv
Enumerations
enum GAsciiType {
G_ASCII_ALNUM = 1 << 0 , G_ASCII_ALPHA = 1 << 1 , G_ASCII_CNTRL = 1 << 2 , G_ASCII_DIGIT = 1 << 3 ,
G_ASCII_GRAPH = 1 << 4 , G_ASCII_LOWER = 1 << 5 , G_ASCII_PRINT = 1 << 6 , G_ASCII_PUNCT = 1 << 7 ,
G_ASCII_SPACE = 1 << 8 , G_ASCII_UPPER = 1 << 9 , G_ASCII_XDIGIT = 1 << 10
}
enum GNumberParserError { G_NUMBER_PARSER_ERROR_INVALID , G_NUMBER_PARSER_ERROR_OUT_OF_BOUNDS }
Functions
GLIB_AVAILABLE_IN_ALL gchar g_ascii_tolower (gchar c) G_GNUC_CONST
GLIB_AVAILABLE_IN_ALL gchar g_ascii_toupper (gchar c) G_GNUC_CONST
GLIB_AVAILABLE_IN_ALL gint g_ascii_digit_value (gchar c) G_GNUC_CONST
GLIB_AVAILABLE_IN_ALL gint g_ascii_xdigit_value (gchar c) G_GNUC_CONST
GLIB_AVAILABLE_IN_ALL gchar * g_strdelimit (gchar *string, const gchar *delimiters, gchar new_delimiter)
GLIB_AVAILABLE_IN_ALL gchar * g_strcanon (gchar *string, const gchar *valid_chars, gchar substitutor)
GLIB_AVAILABLE_IN_ALL const gchar * g_strerror (gint errnum) G_GNUC_CONST
GLIB_AVAILABLE_IN_ALL const gchar * g_strsignal (gint signum) G_GNUC_CONST
GLIB_AVAILABLE_IN_ALL gchar * g_strreverse (gchar *string)
GLIB_AVAILABLE_IN_ALL gsize g_strlcpy (gchar *dest, const gchar *src, gsize dest_size)
GLIB_AVAILABLE_IN_ALL gsize g_strlcat (gchar *dest, const gchar *src, gsize dest_size)
GLIB_AVAILABLE_IN_ALL gchar * g_strstr_len (const gchar *haystack, gssize haystack_len, const gchar *needle)
GLIB_AVAILABLE_IN_ALL gchar * g_strrstr (const gchar *haystack, const gchar *needle)
GLIB_AVAILABLE_IN_ALL gchar * g_strrstr_len (const gchar *haystack, gssize haystack_len, const gchar *needle)
GLIB_AVAILABLE_IN_ALL gboolean g_str_has_suffix (const gchar *str, const gchar *suffix)
GLIB_AVAILABLE_IN_ALL gboolean g_str_has_prefix (const gchar *str, const gchar *prefix)
GLIB_AVAILABLE_IN_ALL gdouble g_strtod (const gchar *nptr, gchar **endptr)
GLIB_AVAILABLE_IN_ALL gdouble g_ascii_strtod (const gchar *nptr, gchar **endptr)
GLIB_AVAILABLE_IN_ALL guint64 g_ascii_strtoull (const gchar *nptr, gchar **endptr, guint base)
GLIB_AVAILABLE_IN_ALL gint64 g_ascii_strtoll (const gchar *nptr, gchar **endptr, guint base)
GLIB_AVAILABLE_IN_ALL gchar * g_ascii_dtostr (gchar *buffer, gint buf_len, gdouble d)
GLIB_AVAILABLE_IN_ALL gchar * g_ascii_formatd (gchar *buffer, gint buf_len, const gchar *format, gdouble d)
GLIB_AVAILABLE_IN_ALL gchar * g_strchug (gchar *string)
GLIB_AVAILABLE_IN_ALL gchar * g_strchomp (gchar *string)
GLIB_AVAILABLE_IN_ALL gint g_ascii_strcasecmp (const gchar *s1, const gchar *s2)
GLIB_AVAILABLE_IN_ALL gint g_ascii_strncasecmp (const gchar *s1, const gchar *s2, gsize n)
GLIB_AVAILABLE_IN_ALL gchar * g_ascii_strdown (const gchar *str, gssize len) G_GNUC_MALLOC
GLIB_AVAILABLE_IN_ALL gchar * g_ascii_strup (const gchar *str, gssize len) G_GNUC_MALLOC
GLIB_AVAILABLE_IN_2_40 gboolean g_str_is_ascii (const gchar *str)
GLIB_DEPRECATED gint g_strcasecmp (const gchar *s1, const gchar *s2)
GLIB_DEPRECATED gint g_strncasecmp (const gchar *s1, const gchar *s2, guint n)
GLIB_DEPRECATED gchar * g_strdown (gchar *string)
GLIB_DEPRECATED gchar * g_strup (gchar *string)
GLIB_AVAILABLE_IN_ALL gchar * g_strdup (const gchar *str) G_GNUC_MALLOC
GLIB_AVAILABLE_IN_ALL gchar * g_strdup_printf (const gchar *format,...) G_GNUC_PRINTF(1
GLIB_AVAILABLE_IN_ALL gchar * g_strdup_vprintf (const gchar *format, va_list args) G_GNUC_PRINTF(1
GLIB_AVAILABLE_IN_ALL gchar * g_strndup (const gchar *str, gsize n) G_GNUC_MALLOC
GLIB_AVAILABLE_IN_ALL gchar * g_strnfill (gsize length, gchar fill_char) G_GNUC_MALLOC
GLIB_AVAILABLE_IN_ALL gchar * g_strconcat (const gchar *string1,...) G_GNUC_MALLOC G_GNUC_NULL_TERMINATED
GLIB_AVAILABLE_IN_ALL gchar * g_strjoin (const gchar *separator,...) G_GNUC_MALLOC G_GNUC_NULL_TERMINATED
GLIB_AVAILABLE_IN_ALL gchar * g_strcompress (const gchar *source) G_GNUC_MALLOC
GLIB_AVAILABLE_IN_ALL gchar * g_strescape (const gchar *source, const gchar *exceptions) G_GNUC_MALLOC
gpointer g_memdup (gconstpointer mem, guint byte_size) G_GNUC_ALLOC_SIZE(2)
GLIB_AVAILABLE_IN_2_68 gpointer g_memdup2 (gconstpointer mem, gsize byte_size) G_GNUC_ALLOC_SIZE(2)
GLIB_AVAILABLE_IN_ALL gchar ** g_strsplit (const gchar *string, const gchar *delimiter, gint max_tokens)
GLIB_AVAILABLE_IN_ALL gchar ** g_strsplit_set (const gchar *string, const gchar *delimiters, gint max_tokens)
GLIB_AVAILABLE_IN_ALL gchar * g_strjoinv (const gchar *separator, gchar **str_array) G_GNUC_MALLOC
GLIB_AVAILABLE_IN_ALL void g_strfreev (gchar **str_array)
GLIB_AVAILABLE_IN_ALL gchar ** g_strdupv (gchar **str_array)
GLIB_AVAILABLE_IN_ALL guint g_strv_length (gchar **str_array)
GLIB_AVAILABLE_IN_ALL gchar * g_stpcpy (gchar *dest, const char *src)
GLIB_AVAILABLE_IN_2_40 gchar * g_str_to_ascii (const gchar *str, const gchar *from_locale)
GLIB_AVAILABLE_IN_2_40 gchar ** g_str_tokenize_and_fold (const gchar *string, const gchar *translit_locale, gchar ***ascii_alternates)
GLIB_AVAILABLE_IN_2_40 gboolean g_str_match_string (const gchar *search_term, const gchar *potential_hit, gboolean accept_alternates)
GLIB_AVAILABLE_IN_2_44 gboolean g_strv_contains (const gchar *const *strv, const gchar *str)
GLIB_AVAILABLE_IN_2_60 gboolean g_strv_equal (const gchar *const *strv1, const gchar *const *strv2)
GLIB_AVAILABLE_IN_2_54 GQuark g_number_parser_error_quark (void)
GLIB_AVAILABLE_IN_2_54 gboolean g_ascii_string_to_signed (const gchar *str, guint base, gint64 min, gint64 max, gint64 *out_num, GError **error)
GLIB_AVAILABLE_IN_2_54 gboolean g_ascii_string_to_unsigned (const gchar *str, guint base, guint64 min, guint64 max, guint64 *out_num, GError **error)
static GLIB_AVAILABLE_STATIC_INLINE_IN_2_76 gboolean g_set_str (char **str_pointer, const char *new_str)
Variables
GLIB_VAR const guint16 *const g_ascii_table
GLIB_AVAILABLE_IN_ALL gchar G_GNUC_MALLOC
Macro Definition Documentation
G_ASCII_DTOSTR_BUF_SIZE
#define G_ASCII_DTOSTR_BUF_SIZE (29 + 10)
Definition at line 230 of file gstrfuncs.h.
g_ascii_isalnum
#define g_ascii_isalnum (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_ALNUM) != 0)
Definition at line 61 of file gstrfuncs.h.
#define g_ascii_isalnum(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_ALNUM) != 0)
g_ascii_isalpha
#define g_ascii_isalpha (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_ALPHA) != 0)
Definition at line 64 of file gstrfuncs.h.
#define g_ascii_isalpha(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_ALPHA) != 0)
g_ascii_iscntrl
#define g_ascii_iscntrl (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_CNTRL) != 0)
Definition at line 67 of file gstrfuncs.h.
#define g_ascii_iscntrl(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_CNTRL) != 0)
g_ascii_isdigit
#define g_ascii_isdigit (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_DIGIT) != 0)
Definition at line 70 of file gstrfuncs.h.
#define g_ascii_isdigit(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_DIGIT) != 0)
g_ascii_isgraph
#define g_ascii_isgraph (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_GRAPH) != 0)
Definition at line 73 of file gstrfuncs.h.
#define g_ascii_isgraph(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_GRAPH) != 0)
g_ascii_islower
#define g_ascii_islower (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_LOWER) != 0)
Definition at line 76 of file gstrfuncs.h.
#define g_ascii_islower(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_LOWER) != 0)
g_ascii_isprint
#define g_ascii_isprint (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_PRINT) != 0)
Definition at line 79 of file gstrfuncs.h.
#define g_ascii_isprint(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_PRINT) != 0)
g_ascii_ispunct
#define g_ascii_ispunct (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_PUNCT) != 0)
Definition at line 82 of file gstrfuncs.h.
#define g_ascii_ispunct(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_PUNCT) != 0)
g_ascii_isspace
#define g_ascii_isspace (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_SPACE) != 0)
Definition at line 85 of file gstrfuncs.h.
#define g_ascii_isspace(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_SPACE) != 0)
g_ascii_isupper
#define g_ascii_isupper (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_UPPER) != 0)
Definition at line 88 of file gstrfuncs.h.
#define g_ascii_isupper(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_UPPER) != 0)
g_ascii_isxdigit
#define g_ascii_isxdigit (c) ((g_ascii_table[(guchar) (c)] & G_ASCII_XDIGIT) != 0)
Definition at line 91 of file gstrfuncs.h.
#define g_ascii_isxdigit(c) \
  ((g_ascii_table[(guchar) (c)] & G_ASCII_XDIGIT) != 0)
G_NUMBER_PARSER_ERROR
#define G_NUMBER_PARSER_ERROR (g_number_parser_error_quark ())
G_NUMBER_PARSER_ERROR:
Domain for errors returned by functions converting a string to a number.
Since: 2.54
Definition at line 424 of file gstrfuncs.h.
G_STR_DELIMITERS
#define G_STR_DELIMITERS "_-|> <."
Definition at line 107 of file gstrfuncs.h.
g_strstrip
#define g_strstrip (string) g_strchomp (g_strchug (string))
Definition at line 248 of file gstrfuncs.h.
Typedef Documentation
GStrv
typedef gchar** GStrv
Definition at line 354 of file gstrfuncs.h.
Enumeration Type Documentation
GAsciiType
enum GAsciiType
Enumerator
G_ASCII_ALNUM
G_ASCII_ALPHA
G_ASCII_CNTRL
G_ASCII_DIGIT
G_ASCII_GRAPH
G_ASCII_LOWER
G_ASCII_PRINT
G_ASCII_PUNCT
G_ASCII_SPACE
G_ASCII_UPPER
G_ASCII_XDIGIT
Definition at line 45 of file gstrfuncs.h.
             {
  G_ASCII_ALNUM  = 1 << 0,
  G_ASCII_ALPHA  = 1 << 1,
  G_ASCII_CNTRL  = 1 << 2,
  G_ASCII_DIGIT  = 1 << 3,
  G_ASCII_GRAPH  = 1 << 4,
  G_ASCII_LOWER  = 1 << 5,
  G_ASCII_PRINT  = 1 << 6,
  G_ASCII_PUNCT  = 1 << 7,
  G_ASCII_SPACE  = 1 << 8,
  G_ASCII_UPPER  = 1 << 9,
  G_ASCII_XDIGIT = 1 << 10
} GAsciiType;
GNumberParserError
enum GNumberParserError
GNumberParserError: @G_NUMBER_PARSER_ERROR_INVALID: string was not a valid number @G_NUMBER_PARSER_ERROR_OUT_OF_BOUNDS: string was a number, but out of bounds
Error codes returned by functions converting a string to a number.
Since: 2.54
Enumerator
G_NUMBER_PARSER_ERROR_INVALID
G_NUMBER_PARSER_ERROR_OUT_OF_BOUNDS
Definition at line 410 of file gstrfuncs.h.
  {
    G_NUMBER_PARSER_ERROR_INVALID,
    G_NUMBER_PARSER_ERROR_OUT_OF_BOUNDS,
  } GNumberParserError;
Function Documentation
g_ascii_digit_value()
GLIB_AVAILABLE_IN_ALL gint g_ascii_digit_value (gchar c)
g_ascii_dtostr()
GLIB_AVAILABLE_IN_ALL gchar * g_ascii_dtostr (gchar * buffer, gint buf_len, gdouble d)
g_ascii_formatd()
GLIB_AVAILABLE_IN_ALL gchar * g_ascii_formatd (gchar * buffer, gint buf_len, const gchar * format, gdouble d)
g_ascii_strcasecmp()
GLIB_AVAILABLE_IN_ALL gint g_ascii_strcasecmp (const gchar * s1, const gchar * s2)
g_ascii_strdown()
GLIB_AVAILABLE_IN_ALL gchar * g_ascii_strdown (const gchar * str, gssize len)
g_ascii_string_to_signed()
GLIB_AVAILABLE_IN_2_54 gboolean g_ascii_string_to_signed (const gchar * str, guint base, gint64 min, gint64 max, gint64 * out_num, GError ** error)
g_ascii_string_to_unsigned()
GLIB_AVAILABLE_IN_2_54 gboolean g_ascii_string_to_unsigned (const gchar * str, guint base, guint64 min, guint64 max, guint64 * out_num, GError ** error)
g_ascii_strncasecmp()
GLIB_AVAILABLE_IN_ALL gint g_ascii_strncasecmp (const gchar * s1, const gchar * s2, gsize n)
g_ascii_strtod()
GLIB_AVAILABLE_IN_ALL gdouble g_ascii_strtod (const gchar * nptr, gchar ** endptr)
g_ascii_strtoll()
GLIB_AVAILABLE_IN_ALL gint64 g_ascii_strtoll (const gchar * nptr, gchar ** endptr, guint base)
g_ascii_strtoull()
GLIB_AVAILABLE_IN_ALL guint64 g_ascii_strtoull (const gchar * nptr, gchar ** endptr, guint base)
g_ascii_strup()
GLIB_AVAILABLE_IN_ALL gchar * g_ascii_strup (const gchar * str, gssize len)
g_ascii_tolower()
GLIB_AVAILABLE_IN_ALL gchar g_ascii_tolower (gchar c)
g_ascii_toupper()
GLIB_AVAILABLE_IN_ALL gchar g_ascii_toupper (gchar c)
g_ascii_xdigit_value()
GLIB_AVAILABLE_IN_ALL gint g_ascii_xdigit_value (gchar c)
g_memdup()
gpointer g_memdup (gconstpointer mem, guint byte_size)
g_memdup2()
GLIB_AVAILABLE_IN_2_68 gpointer g_memdup2 (gconstpointer mem, gsize byte_size)
g_number_parser_error_quark()
GLIB_AVAILABLE_IN_2_54 GQuark g_number_parser_error_quark (void)
g_set_str()
static GLIB_AVAILABLE_STATIC_INLINE_IN_2_76 gboolean g_set_str (char ** str_pointer, const char * new_str) inline static
g_set_str: (skip) @str_pointer: (inout) (not optional) (nullable): a pointer to either a string or NULL @new_str: (nullable): a string to assign to @str_pointer
Updates a pointer to a string to a copy of @new_str and returns whether the string was changed.
If @new_str matches the previous string, this function is a no-op. If @new_str is different, a copy of it will be assigned to @str_pointer and the previous string pointed to by @str_pointer will be freed with [func@.nosp@m.GLib.nosp@m..free].
@str_pointer must not be NULL, but can point to a NULL value.
One convenient usage of this function is in implementing property settings:
void
foo_set_bar (Foo        *foo,
             const char *new_bar)
{
  g_return_if_fail (IS_FOO (foo));
  if (g_set_str (&foo->bar, new_bar))
    g_object_notify (foo, "bar");
}
Returns: true if the value of @str_pointer changed, false otherwise
Since: 2.76
Definition at line 480 of file gstrfuncs.h.
{
  char *copy;
  if (*str_pointer == new_str ||
      (*str_pointer && new_str && strcmp (*str_pointer, new_str) == 0))
    return FALSE;
  copy = g_strdup (new_str);
  g_free (*str_pointer);
  *str_pointer = copy;
  return TRUE;
}
References FALSE, g_free(), g_strdup(), and TRUE.
g_stpcpy()
GLIB_AVAILABLE_IN_ALL gchar * g_stpcpy (gchar * dest, const char * src)
g_str_has_prefix()
GLIB_AVAILABLE_IN_ALL gboolean g_str_has_prefix (const gchar * str, const gchar * prefix)
g_str_has_suffix()
GLIB_AVAILABLE_IN_ALL gboolean g_str_has_suffix (const gchar * str, const gchar * suffix)
g_str_is_ascii()
GLIB_AVAILABLE_IN_2_40 gboolean g_str_is_ascii (const gchar * str)
g_str_match_string()
GLIB_AVAILABLE_IN_2_40 gboolean g_str_match_string (const gchar * search_term, const gchar * potential_hit, gboolean accept_alternates)
g_str_to_ascii()
GLIB_AVAILABLE_IN_2_40 gchar * g_str_to_ascii (const gchar * str, const gchar * from_locale)
g_str_tokenize_and_fold()
GLIB_AVAILABLE_IN_2_40 gchar ** g_str_tokenize_and_fold (const gchar * string, const gchar * translit_locale, gchar *** ascii_alternates)
g_strcanon()
GLIB_AVAILABLE_IN_ALL gchar * g_strcanon (gchar * string, const gchar * valid_chars, gchar substitutor)
g_strcasecmp()
GLIB_DEPRECATED gint g_strcasecmp (const gchar * s1, const gchar * s2)
g_strchomp()
GLIB_AVAILABLE_IN_ALL gchar * g_strchomp (gchar * string)
g_strchug()
GLIB_AVAILABLE_IN_ALL gchar * g_strchug (gchar * string)
g_strcompress()
GLIB_AVAILABLE_IN_ALL gchar * g_strcompress (const gchar * source)
g_strconcat()
GLIB_AVAILABLE_IN_ALL gchar * g_strconcat (const gchar * string1, ...)
g_strdelimit()
GLIB_AVAILABLE_IN_ALL gchar * g_strdelimit (gchar * string, const gchar * delimiters, gchar new_delimiter)
g_strdown()
GLIB_DEPRECATED gchar * g_strdown (gchar * string)
g_strdup()
GLIB_AVAILABLE_IN_ALL gchar * g_strdup (const gchar * str)
Referenced by g_set_str(), and g_strjoin().
g_strdup_printf()
GLIB_AVAILABLE_IN_ALL gchar * g_strdup_printf (const gchar * format, ...)
Referenced by on_button_clicked().
g_strdup_vprintf()
GLIB_AVAILABLE_IN_ALL gchar * g_strdup_vprintf (const gchar * format, va_list args)
g_strdupv()
GLIB_AVAILABLE_IN_ALL gchar ** g_strdupv (gchar ** str_array)
g_strerror()
GLIB_AVAILABLE_IN_ALL const gchar * g_strerror (gint errnum)
g_strescape()
GLIB_AVAILABLE_IN_ALL gchar * g_strescape (const gchar * source, const gchar * exceptions)
g_strfreev()
GLIB_AVAILABLE_IN_ALL void g_strfreev (gchar ** str_array)
g_strjoin()
GLIB_AVAILABLE_IN_ALL gchar * g_strjoin (const gchar * separator, ...)
References g_malloc(), g_strdup(), and NULL.
g_strjoinv()
GLIB_AVAILABLE_IN_ALL gchar * g_strjoinv (const gchar * separator, gchar ** str_array)
g_strlcat()
GLIB_AVAILABLE_IN_ALL gsize g_strlcat (gchar * dest, const gchar * src, gsize dest_size)
g_strlcpy()
GLIB_AVAILABLE_IN_ALL gsize g_strlcpy (gchar * dest, const gchar * src, gsize dest_size)
g_strncasecmp()
GLIB_DEPRECATED gint g_strncasecmp (const gchar * s1, const gchar * s2, guint n)
g_strndup()
GLIB_AVAILABLE_IN_ALL gchar * g_strndup (const gchar * str, gsize n)
g_strnfill()
GLIB_AVAILABLE_IN_ALL gchar * g_strnfill (gsize length, gchar fill_char)
g_strreverse()
GLIB_AVAILABLE_IN_ALL gchar * g_strreverse (gchar * string)
g_strrstr()
GLIB_AVAILABLE_IN_ALL gchar * g_strrstr (const gchar * haystack, const gchar * needle)
g_strrstr_len()
GLIB_AVAILABLE_IN_ALL gchar * g_strrstr_len (const gchar * haystack, gssize haystack_len, const gchar * needle)
g_strsignal()
GLIB_AVAILABLE_IN_ALL const gchar * g_strsignal (gint signum)
g_strsplit()
GLIB_AVAILABLE_IN_ALL gchar ** g_strsplit (const gchar * string, const gchar * delimiter, gint max_tokens)
g_strsplit_set()
GLIB_AVAILABLE_IN_ALL gchar ** g_strsplit_set (const gchar * string, const gchar * delimiters, gint max_tokens)
g_strstr_len()
GLIB_AVAILABLE_IN_ALL gchar * g_strstr_len (const gchar * haystack, gssize haystack_len, const gchar * needle)
g_strtod()
GLIB_AVAILABLE_IN_ALL gdouble g_strtod (const gchar * nptr, gchar ** endptr)
g_strup()
GLIB_DEPRECATED gchar * g_strup (gchar * string)
g_strv_contains()
GLIB_AVAILABLE_IN_2_44 gboolean g_strv_contains (const gchar *const * strv, const gchar * str)
g_strv_equal()
GLIB_AVAILABLE_IN_2_60 gboolean g_strv_equal (const gchar *const * strv1, const gchar *const * strv2)
g_strv_length()
GLIB_AVAILABLE_IN_ALL guint g_strv_length (gchar ** str_array)
Variable Documentation
g_ascii_table
GLIB_VAR const guint16* const g_ascii_table
Definition at line 59 of file gstrfuncs.h.
G_GNUC_MALLOC
GLIB_AVAILABLE_IN_ALL gchar G_GNUC_MALLOC
Definition at line 287 of file gstrfuncs.h.