Github User Fetcher: gtktextview.h File Reference
gtktextview.h File Reference
#include <gtk/gtkwidget.h>
#include <gtk/gtkimcontext.h>
#include <gtk/gtktextbuffer.h>
Data Structures
struct _GtkTextView
struct _GtkTextViewClass
Macros
#define GTK_TYPE_TEXT_VIEW (gtk_text_view_get_type ())
#define GTK_TEXT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_TEXT_VIEW, GtkTextView))
#define GTK_TEXT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_TYPE_TEXT_VIEW, GtkTextViewClass))
#define GTK_IS_TEXT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTK_TYPE_TEXT_VIEW))
#define GTK_IS_TEXT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTK_TYPE_TEXT_VIEW))
#define GTK_TEXT_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTK_TYPE_TEXT_VIEW, GtkTextViewClass))
#define GTK_TEXT_VIEW_PRIORITY_VALIDATE (GDK_PRIORITY_REDRAW + 5)
Typedefs
typedef struct _GtkTextView GtkTextView
typedef struct _GtkTextViewPrivate GtkTextViewPrivate
typedef struct _GtkTextViewClass GtkTextViewClass
Enumerations
enum GtkTextWindowType {
GTK_TEXT_WINDOW_WIDGET = 1 , GTK_TEXT_WINDOW_TEXT , GTK_TEXT_WINDOW_LEFT , GTK_TEXT_WINDOW_RIGHT ,
GTK_TEXT_WINDOW_TOP , GTK_TEXT_WINDOW_BOTTOM
}
enum GtkTextViewLayer { GTK_TEXT_VIEW_LAYER_BELOW_TEXT , GTK_TEXT_VIEW_LAYER_ABOVE_TEXT }
enum GtkTextExtendSelection { GTK_TEXT_EXTEND_SELECTION_WORD , GTK_TEXT_EXTEND_SELECTION_LINE }
Functions
GDK_AVAILABLE_IN_ALL GType gtk_text_view_get_type (void) G_GNUC_CONST
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_text_view_new (void)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_text_view_new_with_buffer (GtkTextBuffer *buffer)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_buffer (GtkTextView *text_view, GtkTextBuffer *buffer)
GDK_AVAILABLE_IN_ALL GtkTextBuffer * gtk_text_view_get_buffer (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_scroll_to_iter (GtkTextView *text_view, GtkTextIter *iter, double within_margin, gboolean use_align, double xalign, double yalign)
GDK_AVAILABLE_IN_ALL void gtk_text_view_scroll_to_mark (GtkTextView *text_view, GtkTextMark *mark, double within_margin, gboolean use_align, double xalign, double yalign)
GDK_AVAILABLE_IN_ALL void gtk_text_view_scroll_mark_onscreen (GtkTextView *text_view, GtkTextMark *mark)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_move_mark_onscreen (GtkTextView *text_view, GtkTextMark *mark)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_place_cursor_onscreen (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_visible_rect (GtkTextView *text_view, GdkRectangle *visible_rect)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_cursor_visible (GtkTextView *text_view, gboolean setting)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_cursor_visible (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_reset_cursor_blink (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_cursor_locations (GtkTextView *text_view, const GtkTextIter *iter, GdkRectangle *strong, GdkRectangle *weak)
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_iter_location (GtkTextView *text_view, const GtkTextIter *iter, GdkRectangle *location)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_iter_at_location (GtkTextView *text_view, GtkTextIter *iter, int x, int y)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_iter_at_position (GtkTextView *text_view, GtkTextIter *iter, int *trailing, int x, int y)
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_line_yrange (GtkTextView *text_view, const GtkTextIter *iter, int *y, int *height)
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_line_at_y (GtkTextView *text_view, GtkTextIter *target_iter, int y, int *line_top)
GDK_AVAILABLE_IN_ALL void gtk_text_view_buffer_to_window_coords (GtkTextView *text_view, GtkTextWindowType win, int buffer_x, int buffer_y, int *window_x, int *window_y)
GDK_AVAILABLE_IN_ALL void gtk_text_view_window_to_buffer_coords (GtkTextView *text_view, GtkTextWindowType win, int window_x, int window_y, int *buffer_x, int *buffer_y)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_forward_display_line (GtkTextView *text_view, GtkTextIter *iter)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_backward_display_line (GtkTextView *text_view, GtkTextIter *iter)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_forward_display_line_end (GtkTextView *text_view, GtkTextIter *iter)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_backward_display_line_start (GtkTextView *text_view, GtkTextIter *iter)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_starts_display_line (GtkTextView *text_view, const GtkTextIter *iter)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_move_visually (GtkTextView *text_view, GtkTextIter *iter, int count)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_im_context_filter_keypress (GtkTextView *text_view, GdkEvent *event)
GDK_AVAILABLE_IN_ALL void gtk_text_view_reset_im_context (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_text_view_get_gutter (GtkTextView *text_view, GtkTextWindowType win)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_gutter (GtkTextView *text_view, GtkTextWindowType win, GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_text_view_add_child_at_anchor (GtkTextView *text_view, GtkWidget *child, GtkTextChildAnchor *anchor)
GDK_AVAILABLE_IN_ALL void gtk_text_view_add_overlay (GtkTextView *text_view, GtkWidget *child, int xpos, int ypos)
GDK_AVAILABLE_IN_ALL void gtk_text_view_move_overlay (GtkTextView *text_view, GtkWidget *child, int xpos, int ypos)
GDK_AVAILABLE_IN_ALL void gtk_text_view_remove (GtkTextView *text_view, GtkWidget *child)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_wrap_mode (GtkTextView *text_view, GtkWrapMode wrap_mode)
GDK_AVAILABLE_IN_ALL GtkWrapMode gtk_text_view_get_wrap_mode (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_editable (GtkTextView *text_view, gboolean setting)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_editable (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_overwrite (GtkTextView *text_view, gboolean overwrite)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_overwrite (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_accepts_tab (GtkTextView *text_view, gboolean accepts_tab)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_accepts_tab (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_pixels_above_lines (GtkTextView *text_view, int pixels_above_lines)
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_pixels_above_lines (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_pixels_below_lines (GtkTextView *text_view, int pixels_below_lines)
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_pixels_below_lines (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_pixels_inside_wrap (GtkTextView *text_view, int pixels_inside_wrap)
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_pixels_inside_wrap (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_justification (GtkTextView *text_view, GtkJustification justification)
GDK_AVAILABLE_IN_ALL GtkJustification gtk_text_view_get_justification (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_left_margin (GtkTextView *text_view, int left_margin)
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_left_margin (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_right_margin (GtkTextView *text_view, int right_margin)
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_right_margin (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_top_margin (GtkTextView *text_view, int top_margin)
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_top_margin (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_bottom_margin (GtkTextView *text_view, int bottom_margin)
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_bottom_margin (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_indent (GtkTextView *text_view, int indent)
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_indent (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_tabs (GtkTextView *text_view, PangoTabArray *tabs)
GDK_AVAILABLE_IN_ALL PangoTabArray * gtk_text_view_get_tabs (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_input_purpose (GtkTextView *text_view, GtkInputPurpose purpose)
GDK_AVAILABLE_IN_ALL GtkInputPurpose gtk_text_view_get_input_purpose (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_input_hints (GtkTextView *text_view, GtkInputHints hints)
GDK_AVAILABLE_IN_ALL GtkInputHints gtk_text_view_get_input_hints (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_monospace (GtkTextView *text_view, gboolean monospace)
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_monospace (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_extra_menu (GtkTextView *text_view, GMenuModel *model)
GDK_AVAILABLE_IN_ALL GMenuModel * gtk_text_view_get_extra_menu (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL PangoContext * gtk_text_view_get_rtl_context (GtkTextView *text_view)
GDK_AVAILABLE_IN_ALL PangoContext * gtk_text_view_get_ltr_context (GtkTextView *text_view)
Macro Definition Documentation
GTK_IS_TEXT_VIEW
#define GTK_IS_TEXT_VIEW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTK_TYPE_TEXT_VIEW))
Definition at line 40 of file gtktextview.h.
GTK_IS_TEXT_VIEW_CLASS
#define GTK_IS_TEXT_VIEW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTK_TYPE_TEXT_VIEW))
Definition at line 41 of file gtktextview.h.
GTK_TEXT_VIEW
#define GTK_TEXT_VIEW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_TEXT_VIEW, GtkTextView))
Definition at line 38 of file gtktextview.h.
Referenced by activate().
GTK_TEXT_VIEW_CLASS
#define GTK_TEXT_VIEW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_TYPE_TEXT_VIEW, GtkTextViewClass))
Definition at line 39 of file gtktextview.h.
GTK_TEXT_VIEW_GET_CLASS
#define GTK_TEXT_VIEW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTK_TYPE_TEXT_VIEW, GtkTextViewClass))
Definition at line 42 of file gtktextview.h.
GTK_TEXT_VIEW_PRIORITY_VALIDATE
#define GTK_TEXT_VIEW_PRIORITY_VALIDATE (GDK_PRIORITY_REDRAW + 5)
GTK_TEXT_VIEW_PRIORITY_VALIDATE: (value 125)
The priority at which the text view validates onscreen lines in an idle job in the background.
Definition at line 101 of file gtktextview.h.
GTK_TYPE_TEXT_VIEW
#define GTK_TYPE_TEXT_VIEW (gtk_text_view_get_type ())
Definition at line 37 of file gtktextview.h.
Typedef Documentation
GtkTextView
typedef struct _GtkTextView GtkTextView
Definition at line 103 of file gtktextview.h.
GtkTextViewClass
typedef struct _GtkTextViewClass GtkTextViewClass
Definition at line 105 of file gtktextview.h.
GtkTextViewPrivate
typedef struct _GtkTextViewPrivate GtkTextViewPrivate
Definition at line 104 of file gtktextview.h.
Enumeration Type Documentation
GtkTextExtendSelection
enum GtkTextExtendSelection
GtkTextExtendSelection: @GTK_TEXT_EXTEND_SELECTION_WORD: Selects the current word. It is triggered by a double-click for example. @GTK_TEXT_EXTEND_SELECTION_LINE: Selects the current line. It is triggered by a triple-click for example.
Granularity types that extend the text selection. Use the GtkTextView::extend-selection signal to customize the selection.
Enumerator
GTK_TEXT_EXTEND_SELECTION_WORD
GTK_TEXT_EXTEND_SELECTION_LINE
Definition at line 89 of file gtktextview.h.
{
  GTK_TEXT_EXTEND_SELECTION_WORD,
  GTK_TEXT_EXTEND_SELECTION_LINE
} GtkTextExtendSelection;
GtkTextViewLayer
enum GtkTextViewLayer
GtkTextViewLayer: @GTK_TEXT_VIEW_LAYER_BELOW_TEXT: The layer rendered below the text (but above the background). @GTK_TEXT_VIEW_LAYER_ABOVE_TEXT: The layer rendered above the text.
Used to reference the layers of GtkTextView for the purpose of customized drawing with the ::snapshot_layer vfunc.
Enumerator
GTK_TEXT_VIEW_LAYER_BELOW_TEXT
GTK_TEXT_VIEW_LAYER_ABOVE_TEXT
Definition at line 73 of file gtktextview.h.
{
  GTK_TEXT_VIEW_LAYER_BELOW_TEXT,
  GTK_TEXT_VIEW_LAYER_ABOVE_TEXT
} GtkTextViewLayer;
GtkTextWindowType
enum GtkTextWindowType
GtkTextWindowType: @GTK_TEXT_WINDOW_WIDGET: Window that floats over scrolling areas. @GTK_TEXT_WINDOW_TEXT: Scrollable text window. @GTK_TEXT_WINDOW_LEFT: Left side border window. @GTK_TEXT_WINDOW_RIGHT: Right side border window. @GTK_TEXT_WINDOW_TOP: Top border window. @GTK_TEXT_WINDOW_BOTTOM: Bottom border window.
Used to reference the parts of GtkTextView.
Enumerator
GTK_TEXT_WINDOW_WIDGET
GTK_TEXT_WINDOW_TEXT
GTK_TEXT_WINDOW_LEFT
GTK_TEXT_WINDOW_RIGHT
GTK_TEXT_WINDOW_TOP
GTK_TEXT_WINDOW_BOTTOM
Definition at line 55 of file gtktextview.h.
{
  GTK_TEXT_WINDOW_WIDGET = 1,
  GTK_TEXT_WINDOW_TEXT,
  GTK_TEXT_WINDOW_LEFT,
  GTK_TEXT_WINDOW_RIGHT,
  GTK_TEXT_WINDOW_TOP,
  GTK_TEXT_WINDOW_BOTTOM
} GtkTextWindowType;
Function Documentation
gtk_text_view_add_child_at_anchor()
GDK_AVAILABLE_IN_ALL void gtk_text_view_add_child_at_anchor (GtkTextView * text_view, GtkWidget * child, GtkTextChildAnchor * anchor)
gtk_text_view_add_overlay()
GDK_AVAILABLE_IN_ALL void gtk_text_view_add_overlay (GtkTextView * text_view, GtkWidget * child, int xpos, int ypos)
gtk_text_view_backward_display_line()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_backward_display_line (GtkTextView * text_view, GtkTextIter * iter)
gtk_text_view_backward_display_line_start()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_backward_display_line_start (GtkTextView * text_view, GtkTextIter * iter)
gtk_text_view_buffer_to_window_coords()
GDK_AVAILABLE_IN_ALL void gtk_text_view_buffer_to_window_coords (GtkTextView * text_view, GtkTextWindowType win, int buffer_x, int buffer_y, int * window_x, int * window_y)
gtk_text_view_forward_display_line()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_forward_display_line (GtkTextView * text_view, GtkTextIter * iter)
gtk_text_view_forward_display_line_end()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_forward_display_line_end (GtkTextView * text_view, GtkTextIter * iter)
gtk_text_view_get_accepts_tab()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_accepts_tab (GtkTextView * text_view)
gtk_text_view_get_bottom_margin()
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_bottom_margin (GtkTextView * text_view)
gtk_text_view_get_buffer()
GDK_AVAILABLE_IN_ALL GtkTextBuffer * gtk_text_view_get_buffer (GtkTextView * text_view)
Referenced by activate().
gtk_text_view_get_cursor_locations()
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_cursor_locations (GtkTextView * text_view, const GtkTextIter * iter, GdkRectangle * strong, GdkRectangle * weak)
gtk_text_view_get_cursor_visible()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_cursor_visible (GtkTextView * text_view)
gtk_text_view_get_editable()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_editable (GtkTextView * text_view)
gtk_text_view_get_extra_menu()
GDK_AVAILABLE_IN_ALL GMenuModel * gtk_text_view_get_extra_menu (GtkTextView * text_view)
gtk_text_view_get_gutter()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_text_view_get_gutter (GtkTextView * text_view, GtkTextWindowType win)
gtk_text_view_get_indent()
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_indent (GtkTextView * text_view)
gtk_text_view_get_input_hints()
GDK_AVAILABLE_IN_ALL GtkInputHints gtk_text_view_get_input_hints (GtkTextView * text_view)
gtk_text_view_get_input_purpose()
GDK_AVAILABLE_IN_ALL GtkInputPurpose gtk_text_view_get_input_purpose (GtkTextView * text_view)
gtk_text_view_get_iter_at_location()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_iter_at_location (GtkTextView * text_view, GtkTextIter * iter, int x, int y)
gtk_text_view_get_iter_at_position()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_iter_at_position (GtkTextView * text_view, GtkTextIter * iter, int * trailing, int x, int y)
gtk_text_view_get_iter_location()
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_iter_location (GtkTextView * text_view, const GtkTextIter * iter, GdkRectangle * location)
gtk_text_view_get_justification()
GDK_AVAILABLE_IN_ALL GtkJustification gtk_text_view_get_justification (GtkTextView * text_view)
gtk_text_view_get_left_margin()
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_left_margin (GtkTextView * text_view)
gtk_text_view_get_line_at_y()
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_line_at_y (GtkTextView * text_view, GtkTextIter * target_iter, int y, int * line_top)
gtk_text_view_get_line_yrange()
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_line_yrange (GtkTextView * text_view, const GtkTextIter * iter, int * y, int * height)
gtk_text_view_get_ltr_context()
GDK_AVAILABLE_IN_ALL PangoContext * gtk_text_view_get_ltr_context (GtkTextView * text_view)
gtk_text_view_get_monospace()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_monospace (GtkTextView * text_view)
gtk_text_view_get_overwrite()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_get_overwrite (GtkTextView * text_view)
gtk_text_view_get_pixels_above_lines()
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_pixels_above_lines (GtkTextView * text_view)
gtk_text_view_get_pixels_below_lines()
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_pixels_below_lines (GtkTextView * text_view)
gtk_text_view_get_pixels_inside_wrap()
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_pixels_inside_wrap (GtkTextView * text_view)
gtk_text_view_get_right_margin()
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_right_margin (GtkTextView * text_view)
gtk_text_view_get_rtl_context()
GDK_AVAILABLE_IN_ALL PangoContext * gtk_text_view_get_rtl_context (GtkTextView * text_view)
gtk_text_view_get_tabs()
GDK_AVAILABLE_IN_ALL PangoTabArray * gtk_text_view_get_tabs (GtkTextView * text_view)
gtk_text_view_get_top_margin()
GDK_AVAILABLE_IN_ALL int gtk_text_view_get_top_margin (GtkTextView * text_view)
gtk_text_view_get_type()
GDK_AVAILABLE_IN_ALL GType gtk_text_view_get_type (void)
gtk_text_view_get_visible_rect()
GDK_AVAILABLE_IN_ALL void gtk_text_view_get_visible_rect (GtkTextView * text_view, GdkRectangle * visible_rect)
gtk_text_view_get_wrap_mode()
GDK_AVAILABLE_IN_ALL GtkWrapMode gtk_text_view_get_wrap_mode (GtkTextView * text_view)
gtk_text_view_im_context_filter_keypress()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_im_context_filter_keypress (GtkTextView * text_view, GdkEvent * event)
gtk_text_view_move_mark_onscreen()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_move_mark_onscreen (GtkTextView * text_view, GtkTextMark * mark)
gtk_text_view_move_overlay()
GDK_AVAILABLE_IN_ALL void gtk_text_view_move_overlay (GtkTextView * text_view, GtkWidget * child, int xpos, int ypos)
gtk_text_view_move_visually()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_move_visually (GtkTextView * text_view, GtkTextIter * iter, int count)
gtk_text_view_new()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_text_view_new (void)
Referenced by activate().
gtk_text_view_new_with_buffer()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_text_view_new_with_buffer (GtkTextBuffer * buffer)
gtk_text_view_place_cursor_onscreen()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_place_cursor_onscreen (GtkTextView * text_view)
gtk_text_view_remove()
GDK_AVAILABLE_IN_ALL void gtk_text_view_remove (GtkTextView * text_view, GtkWidget * child)
gtk_text_view_reset_cursor_blink()
GDK_AVAILABLE_IN_ALL void gtk_text_view_reset_cursor_blink (GtkTextView * text_view)
gtk_text_view_reset_im_context()
GDK_AVAILABLE_IN_ALL void gtk_text_view_reset_im_context (GtkTextView * text_view)
gtk_text_view_scroll_mark_onscreen()
GDK_AVAILABLE_IN_ALL void gtk_text_view_scroll_mark_onscreen (GtkTextView * text_view, GtkTextMark * mark)
gtk_text_view_scroll_to_iter()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_scroll_to_iter (GtkTextView * text_view, GtkTextIter * iter, double within_margin, gboolean use_align, double xalign, double yalign)
gtk_text_view_scroll_to_mark()
GDK_AVAILABLE_IN_ALL void gtk_text_view_scroll_to_mark (GtkTextView * text_view, GtkTextMark * mark, double within_margin, gboolean use_align, double xalign, double yalign)
gtk_text_view_set_accepts_tab()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_accepts_tab (GtkTextView * text_view, gboolean accepts_tab)
gtk_text_view_set_bottom_margin()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_bottom_margin (GtkTextView * text_view, int bottom_margin)
gtk_text_view_set_buffer()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_buffer (GtkTextView * text_view, GtkTextBuffer * buffer)
gtk_text_view_set_cursor_visible()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_cursor_visible (GtkTextView * text_view, gboolean setting)
gtk_text_view_set_editable()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_editable (GtkTextView * text_view, gboolean setting)
Referenced by activate().
gtk_text_view_set_extra_menu()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_extra_menu (GtkTextView * text_view, GMenuModel * model)
gtk_text_view_set_gutter()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_gutter (GtkTextView * text_view, GtkTextWindowType win, GtkWidget * widget)
gtk_text_view_set_indent()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_indent (GtkTextView * text_view, int indent)
gtk_text_view_set_input_hints()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_input_hints (GtkTextView * text_view, GtkInputHints hints)
gtk_text_view_set_input_purpose()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_input_purpose (GtkTextView * text_view, GtkInputPurpose purpose)
gtk_text_view_set_justification()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_justification (GtkTextView * text_view, GtkJustification justification)
gtk_text_view_set_left_margin()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_left_margin (GtkTextView * text_view, int left_margin)
gtk_text_view_set_monospace()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_monospace (GtkTextView * text_view, gboolean monospace)
gtk_text_view_set_overwrite()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_overwrite (GtkTextView * text_view, gboolean overwrite)
gtk_text_view_set_pixels_above_lines()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_pixels_above_lines (GtkTextView * text_view, int pixels_above_lines)
gtk_text_view_set_pixels_below_lines()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_pixels_below_lines (GtkTextView * text_view, int pixels_below_lines)
gtk_text_view_set_pixels_inside_wrap()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_pixels_inside_wrap (GtkTextView * text_view, int pixels_inside_wrap)
gtk_text_view_set_right_margin()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_right_margin (GtkTextView * text_view, int right_margin)
gtk_text_view_set_tabs()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_tabs (GtkTextView * text_view, PangoTabArray * tabs)
gtk_text_view_set_top_margin()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_top_margin (GtkTextView * text_view, int top_margin)
gtk_text_view_set_wrap_mode()
GDK_AVAILABLE_IN_ALL void gtk_text_view_set_wrap_mode (GtkTextView * text_view, GtkWrapMode wrap_mode)
Referenced by activate().
gtk_text_view_starts_display_line()
GDK_AVAILABLE_IN_ALL gboolean gtk_text_view_starts_display_line (GtkTextView * text_view, const GtkTextIter * iter)
gtk_text_view_window_to_buffer_coords()
GDK_AVAILABLE_IN_ALL void gtk_text_view_window_to_buffer_coords (GtkTextView * text_view, GtkTextWindowType win, int window_x, int window_y, int * buffer_x, int * buffer_y)