Github User Fetcher: gtkwidget.h File Reference
gtkwidget.h File Reference
#include <gdk/gdk.h>
#include <gsk/gsk.h>
#include <gtk/gtkenums.h>
#include <gtk/gtkshortcut.h>
#include <gtk/gtkshortcutaction.h>
#include <gtk/gtktypes.h>
Data Structures
struct _GtkRequisition
struct _GtkWidget
struct _GtkWidgetClass
Macros
#define GTK_TYPE_WIDGET (gtk_widget_get_type ())
#define GTK_WIDGET(widget) (G_TYPE_CHECK_INSTANCE_CAST ((widget), GTK_TYPE_WIDGET, GtkWidget))
#define GTK_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_TYPE_WIDGET, GtkWidgetClass))
#define GTK_IS_WIDGET(widget) (G_TYPE_CHECK_INSTANCE_TYPE ((widget), GTK_TYPE_WIDGET))
#define GTK_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTK_TYPE_WIDGET))
#define GTK_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTK_TYPE_WIDGET, GtkWidgetClass))
#define GTK_TYPE_REQUISITION (gtk_requisition_get_type ())
#define gtk_widget_class_bind_template_callback(widget_class, callback)
#define gtk_widget_class_bind_template_child(widget_class, TypeName, member_name)
#define gtk_widget_class_bind_template_child_internal(widget_class, TypeName, member_name)
#define gtk_widget_class_bind_template_child_private(widget_class, TypeName, member_name)
#define gtk_widget_class_bind_template_child_internal_private(widget_class, TypeName, member_name)
Typedefs
typedef struct _GtkWidgetPrivate GtkWidgetPrivate
typedef struct _GtkWidgetClass GtkWidgetClass
typedef struct _GtkWidgetClassPrivate GtkWidgetClassPrivate
typedef GdkRectangle GtkAllocation
typedef gboolean(* GtkTickCallback) (GtkWidget *widget, GdkFrameClock *frame_clock, gpointer user_data)
typedef void(* GtkWidgetActionActivateFunc) (GtkWidget *widget, const char *action_name, GVariant *parameter)
Functions
GDK_AVAILABLE_IN_ALL GType gtk_widget_get_type (void) G_GNUC_CONST
GDK_AVAILABLE_IN_ALL void gtk_widget_unparent (GtkWidget *widget)
void gtk_widget_show (GtkWidget *widget)
void gtk_widget_hide (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_map (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_unmap (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_realize (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_unrealize (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_queue_draw (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_queue_resize (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_queue_allocate (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GdkFrameClock * gtk_widget_get_frame_clock (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_size_allocate (GtkWidget *widget, const GtkAllocation *allocation, int baseline)
GDK_AVAILABLE_IN_ALL void gtk_widget_allocate (GtkWidget *widget, int width, int height, int baseline, GskTransform *transform)
GDK_AVAILABLE_IN_ALL GtkSizeRequestMode gtk_widget_get_request_mode (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_measure (GtkWidget *widget, GtkOrientation orientation, int for_size, int *minimum, int *natural, int *minimum_baseline, int *natural_baseline)
GDK_AVAILABLE_IN_ALL void gtk_widget_get_preferred_size (GtkWidget *widget, GtkRequisition *minimum_size, GtkRequisition *natural_size)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_layout_manager (GtkWidget *widget, GtkLayoutManager *layout_manager)
GDK_AVAILABLE_IN_ALL GtkLayoutManager * gtk_widget_get_layout_manager (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_layout_manager_type (GtkWidgetClass *widget_class, GType type)
GDK_AVAILABLE_IN_ALL GType gtk_widget_class_get_layout_manager_type (GtkWidgetClass *widget_class)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_add_binding (GtkWidgetClass *widget_class, guint keyval, GdkModifierType mods, GtkShortcutFunc callback, const char *format_string,...)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_add_binding_signal (GtkWidgetClass *widget_class, guint keyval, GdkModifierType mods, const char *signal, const char *format_string,...)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_add_binding_action (GtkWidgetClass *widget_class, guint keyval, GdkModifierType mods, const char *action_name, const char *format_string,...)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_add_shortcut (GtkWidgetClass *widget_class, GtkShortcut *shortcut)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_activate_signal (GtkWidgetClass *widget_class, guint signal_id)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_activate_signal_from_name (GtkWidgetClass *widget_class, const char *signal_name)
GDK_AVAILABLE_IN_ALL guint gtk_widget_class_get_activate_signal (GtkWidgetClass *widget_class)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_mnemonic_activate (GtkWidget *widget, gboolean group_cycling)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_activate (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_can_focus (GtkWidget *widget, gboolean can_focus)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_can_focus (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_focusable (GtkWidget *widget, gboolean focusable)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_focusable (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_has_focus (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_focus (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_has_visible_focus (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_grab_focus (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_focus_on_click (GtkWidget *widget, gboolean focus_on_click)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_focus_on_click (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_can_target (GtkWidget *widget, gboolean can_target)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_can_target (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_has_default (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_receives_default (GtkWidget *widget, gboolean receives_default)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_receives_default (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_name (GtkWidget *widget, const char *name)
GDK_AVAILABLE_IN_ALL const char * gtk_widget_get_name (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_state_flags (GtkWidget *widget, GtkStateFlags flags, gboolean clear)
GDK_AVAILABLE_IN_ALL void gtk_widget_unset_state_flags (GtkWidget *widget, GtkStateFlags flags)
GDK_AVAILABLE_IN_ALL GtkStateFlags gtk_widget_get_state_flags (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_sensitive (GtkWidget *widget, gboolean sensitive)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_sensitive (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_sensitive (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_visible (GtkWidget *widget, gboolean visible)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_visible (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_visible (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_drawable (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_realized (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_mapped (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_parent (GtkWidget *widget, GtkWidget *parent)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_parent (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GtkRoot * gtk_widget_get_root (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GtkNative * gtk_widget_get_native (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_child_visible (GtkWidget *widget, gboolean child_visible)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_child_visible (GtkWidget *widget)
int gtk_widget_get_allocated_width (GtkWidget *widget)
int gtk_widget_get_allocated_height (GtkWidget *widget)
int gtk_widget_get_allocated_baseline (GtkWidget *widget)
void gtk_widget_get_allocation (GtkWidget *widget, GtkAllocation *allocation)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_compute_transform (GtkWidget *widget, GtkWidget *target, graphene_matrix_t *out_transform) G_GNUC_WARN_UNUSED_RESULT
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_compute_bounds (GtkWidget *widget, GtkWidget *target, graphene_rect_t *out_bounds) G_GNUC_WARN_UNUSED_RESULT
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_compute_point (GtkWidget *widget, GtkWidget *target, const graphene_point_t *point, graphene_point_t *out_point) G_GNUC_WARN_UNUSED_RESULT
GDK_AVAILABLE_IN_ALL int gtk_widget_get_width (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL int gtk_widget_get_height (GtkWidget *widget)
GDK_AVAILABLE_IN_4_12 int gtk_widget_get_baseline (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL int gtk_widget_get_size (GtkWidget *widget, GtkOrientation orientation)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_child_focus (GtkWidget *widget, GtkDirectionType direction)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_keynav_failed (GtkWidget *widget, GtkDirectionType direction)
GDK_AVAILABLE_IN_ALL void gtk_widget_error_bell (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_size_request (GtkWidget *widget, int width, int height)
GDK_AVAILABLE_IN_ALL void gtk_widget_get_size_request (GtkWidget *widget, int *width, int *height)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_opacity (GtkWidget *widget, double opacity)
GDK_AVAILABLE_IN_ALL double gtk_widget_get_opacity (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_overflow (GtkWidget *widget, GtkOverflow overflow)
GDK_AVAILABLE_IN_ALL GtkOverflow gtk_widget_get_overflow (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_ancestor (GtkWidget *widget, GType widget_type)
GDK_AVAILABLE_IN_ALL int gtk_widget_get_scale_factor (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GdkDisplay * gtk_widget_get_display (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GtkSettings * gtk_widget_get_settings (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GdkClipboard * gtk_widget_get_clipboard (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GdkClipboard * gtk_widget_get_primary_clipboard (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_hexpand (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_hexpand (GtkWidget *widget, gboolean expand)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_hexpand_set (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_hexpand_set (GtkWidget *widget, gboolean set)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_vexpand (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_vexpand (GtkWidget *widget, gboolean expand)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_vexpand_set (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_vexpand_set (GtkWidget *widget, gboolean set)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_compute_expand (GtkWidget *widget, GtkOrientation orientation)
GDK_AVAILABLE_IN_ALL GtkAlign gtk_widget_get_halign (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_halign (GtkWidget *widget, GtkAlign align)
GDK_AVAILABLE_IN_ALL GtkAlign gtk_widget_get_valign (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_valign (GtkWidget *widget, GtkAlign align)
GDK_AVAILABLE_IN_ALL int gtk_widget_get_margin_start (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_margin_start (GtkWidget *widget, int margin)
GDK_AVAILABLE_IN_ALL int gtk_widget_get_margin_end (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_margin_end (GtkWidget *widget, int margin)
GDK_AVAILABLE_IN_ALL int gtk_widget_get_margin_top (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_margin_top (GtkWidget *widget, int margin)
GDK_AVAILABLE_IN_ALL int gtk_widget_get_margin_bottom (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_margin_bottom (GtkWidget *widget, int margin)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_ancestor (GtkWidget *widget, GtkWidget *ancestor)
gboolean gtk_widget_translate_coordinates (GtkWidget *src_widget, GtkWidget *dest_widget, double src_x, double src_y, double *dest_x, double *dest_y)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_contains (GtkWidget *widget, double x, double y)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_pick (GtkWidget *widget, double x, double y, GtkPickFlags flags)
GDK_AVAILABLE_IN_ALL void gtk_widget_add_controller (GtkWidget *widget, GtkEventController *controller)
GDK_AVAILABLE_IN_ALL void gtk_widget_remove_controller (GtkWidget *widget, GtkEventController *controller)
GDK_AVAILABLE_IN_ALL PangoContext * gtk_widget_create_pango_context (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL PangoContext * gtk_widget_get_pango_context (GtkWidget *widget)
GDK_DEPRECATED_IN_4_16 void gtk_widget_set_font_options (GtkWidget *widget, const cairo_font_options_t *options)
GDK_DEPRECATED_IN_4_16 const cairo_font_options_t * gtk_widget_get_font_options (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL PangoLayout * gtk_widget_create_pango_layout (GtkWidget *widget, const char *text)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_direction (GtkWidget *widget, GtkTextDirection dir)
GDK_AVAILABLE_IN_ALL GtkTextDirection gtk_widget_get_direction (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_default_direction (GtkTextDirection dir)
GDK_AVAILABLE_IN_ALL GtkTextDirection gtk_widget_get_default_direction (void)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_cursor (GtkWidget *widget, GdkCursor *cursor)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_cursor_from_name (GtkWidget *widget, const char *name)
GDK_AVAILABLE_IN_ALL GdkCursor * gtk_widget_get_cursor (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GList * gtk_widget_list_mnemonic_labels (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_add_mnemonic_label (GtkWidget *widget, GtkWidget *label)
GDK_AVAILABLE_IN_ALL void gtk_widget_remove_mnemonic_label (GtkWidget *widget, GtkWidget *label)
GDK_AVAILABLE_IN_ALL void gtk_widget_trigger_tooltip_query (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_tooltip_text (GtkWidget *widget, const char *text)
GDK_AVAILABLE_IN_ALL const char * gtk_widget_get_tooltip_text (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_tooltip_markup (GtkWidget *widget, const char *markup)
GDK_AVAILABLE_IN_ALL const char * gtk_widget_get_tooltip_markup (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_has_tooltip (GtkWidget *widget, gboolean has_tooltip)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_has_tooltip (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GType gtk_requisition_get_type (void) G_GNUC_CONST
GDK_AVAILABLE_IN_ALL GtkRequisition * gtk_requisition_new (void) G_GNUC_MALLOC
GDK_AVAILABLE_IN_ALL GtkRequisition * gtk_requisition_copy (const GtkRequisition *requisition)
GDK_AVAILABLE_IN_ALL void gtk_requisition_free (GtkRequisition *requisition)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_in_destruction (GtkWidget *widget)
GDK_DEPRECATED_IN_4_10 GtkStyleContext * gtk_widget_get_style_context (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_css_name (GtkWidgetClass *widget_class, const char *name)
GDK_AVAILABLE_IN_ALL const char * gtk_widget_class_get_css_name (GtkWidgetClass *widget_class)
GDK_AVAILABLE_IN_ALL guint gtk_widget_add_tick_callback (GtkWidget *widget, GtkTickCallback callback, gpointer user_data, GDestroyNotify notify)
GDK_AVAILABLE_IN_ALL void gtk_widget_remove_tick_callback (GtkWidget *widget, guint id)
GDK_AVAILABLE_IN_ALL void gtk_widget_init_template (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GObject * gtk_widget_get_template_child (GtkWidget *widget, GType widget_type, const char *name)
GDK_AVAILABLE_IN_4_8 void gtk_widget_dispose_template (GtkWidget *widget, GType widget_type)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_template (GtkWidgetClass *widget_class, GBytes *template_bytes)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_template_from_resource (GtkWidgetClass *widget_class, const char *resource_name)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_bind_template_callback_full (GtkWidgetClass *widget_class, const char *callback_name, GCallback callback_symbol)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_template_scope (GtkWidgetClass *widget_class, GtkBuilderScope *scope)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_bind_template_child_full (GtkWidgetClass *widget_class, const char *name, gboolean internal_child, gssize struct_offset)
GDK_AVAILABLE_IN_ALL void gtk_widget_insert_action_group (GtkWidget *widget, const char *name, GActionGroup *group)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_activate_action (GtkWidget *widget, const char *name, const char *format_string,...)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_activate_action_variant (GtkWidget *widget, const char *name, GVariant *args)
GDK_AVAILABLE_IN_ALL void gtk_widget_activate_default (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_font_map (GtkWidget *widget, PangoFontMap *font_map)
GDK_AVAILABLE_IN_ALL PangoFontMap * gtk_widget_get_font_map (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_first_child (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_last_child (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_next_sibling (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_prev_sibling (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GListModel * gtk_widget_observe_children (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL GListModel * gtk_widget_observe_controllers (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_insert_after (GtkWidget *widget, GtkWidget *parent, GtkWidget *previous_sibling)
GDK_AVAILABLE_IN_ALL void gtk_widget_insert_before (GtkWidget *widget, GtkWidget *parent, GtkWidget *next_sibling)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_focus_child (GtkWidget *widget, GtkWidget *child)
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_focus_child (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_snapshot_child (GtkWidget *widget, GtkWidget *child, GtkSnapshot *snapshot)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_should_layout (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL const char * gtk_widget_get_css_name (GtkWidget *self) G_GNUC_PURE
GDK_AVAILABLE_IN_ALL void gtk_widget_add_css_class (GtkWidget *widget, const char *css_class)
GDK_AVAILABLE_IN_ALL void gtk_widget_remove_css_class (GtkWidget *widget, const char *css_class)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_has_css_class (GtkWidget *widget, const char *css_class)
GDK_AVAILABLE_IN_ALL char ** gtk_widget_get_css_classes (GtkWidget *widget)
GDK_AVAILABLE_IN_ALL void gtk_widget_set_css_classes (GtkWidget *widget, const char **classes)
GDK_AVAILABLE_IN_4_10 void gtk_widget_get_color (GtkWidget *widget, GdkRGBA *color)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_install_action (GtkWidgetClass *widget_class, const char *action_name, const char *parameter_type, GtkWidgetActionActivateFunc activate)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_install_property_action (GtkWidgetClass *widget_class, const char *action_name, const char *property_name)
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_class_query_action (GtkWidgetClass *widget_class, guint index_, GType *owner, const char **action_name, const GVariantType **parameter_type, const char **property_name)
GDK_AVAILABLE_IN_ALL void gtk_widget_action_set_enabled (GtkWidget *widget, const char *action_name, gboolean enabled)
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_accessible_role (GtkWidgetClass *widget_class, GtkAccessibleRole accessible_role)
GDK_AVAILABLE_IN_ALL GtkAccessibleRole gtk_widget_class_get_accessible_role (GtkWidgetClass *widget_class)
Macro Definition Documentation
GTK_IS_WIDGET
#define GTK_IS_WIDGET (widget) (G_TYPE_CHECK_INSTANCE_TYPE ((widget), GTK_TYPE_WIDGET))
Definition at line 46 of file gtkwidget.h.
GTK_IS_WIDGET_CLASS
#define GTK_IS_WIDGET_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTK_TYPE_WIDGET))
Definition at line 47 of file gtkwidget.h.
GTK_TYPE_REQUISITION
#define GTK_TYPE_REQUISITION (gtk_requisition_get_type ())
Definition at line 50 of file gtkwidget.h.
GTK_TYPE_WIDGET
#define GTK_TYPE_WIDGET (gtk_widget_get_type ())
Definition at line 43 of file gtkwidget.h.
GTK_WIDGET
#define GTK_WIDGET (widget) (G_TYPE_CHECK_INSTANCE_CAST ((widget), GTK_TYPE_WIDGET, GtkWidget))
Definition at line 44 of file gtkwidget.h.
Referenced by activate().
GTK_WIDGET_CLASS
#define GTK_WIDGET_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_TYPE_WIDGET, GtkWidgetClass))
Definition at line 45 of file gtkwidget.h.
gtk_widget_class_bind_template_callback
#define gtk_widget_class_bind_template_callback (widget_class, callback)
Value:
  gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (widget_class), \
                                                #callback, \
                                                G_CALLBACK (callback))
gtk_widget_class_bind_template_callback: @widget_class: a GtkWidgetClass @callback: the callback symbol
Binds a callback function defined in a template to the @widget_class.
This macro is a convenience wrapper around the gtk_widget_class_bind_template_callback_full() function. It is not supported after gtk_widget_class_set_template_scope() has been used on @widget_class.
Definition at line 740 of file gtkwidget.h.
#define gtk_widget_class_bind_template_callback(widget_class, callback) \
  gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (widget_class), \
                                                #callback, \
                                                G_CALLBACK (callback))
gtk_widget_class_bind_template_child
#define gtk_widget_class_bind_template_child (widget_class, TypeName, member_name)
Value:
  gtk_widget_class_bind_template_child_full (widget_class, \
                                             #member_name, \
                                             FALSE, \
                                             G_STRUCT_OFFSET (TypeName, member_name))
gtk_widget_class_bind_template_child: @widget_class: a GtkWidgetClass @TypeName: the type name of this widget @member_name: name of the instance member in the instance struct for @data_type
Binds a child widget defined in a template to the @widget_class.
This macro is a convenience wrapper around the gtk_widget_class_bind_template_child_full() function.
This macro will use the offset of the @member_name inside the @TypeName instance structure.
Definition at line 759 of file gtkwidget.h.
#define gtk_widget_class_bind_template_child(widget_class, TypeName, member_name) \
  gtk_widget_class_bind_template_child_full (widget_class, \
                                             #member_name, \
                                             FALSE, \
                                             G_STRUCT_OFFSET (TypeName, member_name))
gtk_widget_class_bind_template_child_internal
#define gtk_widget_class_bind_template_child_internal (widget_class, TypeName, member_name)
Value:
  gtk_widget_class_bind_template_child_full (widget_class, \
                                             #member_name, \
                                             TRUE, \
                                             G_STRUCT_OFFSET (TypeName, member_name))
gtk_widget_class_bind_template_child_internal: @widget_class: a GtkWidgetClass @TypeName: the type name, in CamelCase @member_name: name of the instance member in the instance struct for @data_type
Binds a child widget defined in a template to the @widget_class, and also makes it available as an internal child in GtkBuilder, under the name @member_name.
This macro is a convenience wrapper around the gtk_widget_class_bind_template_child_full() function.
This macro will use the offset of the @member_name inside the @TypeName instance structure.
Definition at line 781 of file gtkwidget.h.
#define gtk_widget_class_bind_template_child_internal(widget_class, TypeName, member_name) \
  gtk_widget_class_bind_template_child_full (widget_class, \
                                             #member_name, \
                                             TRUE, \
                                             G_STRUCT_OFFSET (TypeName, member_name))
gtk_widget_class_bind_template_child_internal_private
#define gtk_widget_class_bind_template_child_internal_private (widget_class, TypeName, member_name)
Value:
  gtk_widget_class_bind_template_child_full (widget_class, \
                                             #member_name, \
                                             TRUE, \
                                             G_PRIVATE_OFFSET (TypeName, member_name))
gtk_widget_class_bind_template_child_internal_private: @widget_class: a GtkWidgetClass @TypeName: the type name, in CamelCase @member_name: name of the instance private member on the private struct for @data_type
Binds a child widget defined in a template to the @widget_class, and also makes it available as an internal child in GtkBuilder, under the name @member_name.
This macro is a convenience wrapper around the gtk_widget_class_bind_template_child_full() function.
This macro will use the offset of the @member_name inside the @TypeName private data structure.
Definition at line 824 of file gtkwidget.h.
#define gtk_widget_class_bind_template_child_internal_private(widget_class, TypeName, member_name) \
  gtk_widget_class_bind_template_child_full (widget_class, \
                                             #member_name, \
                                             TRUE, \
                                             G_PRIVATE_OFFSET (TypeName, member_name))
gtk_widget_class_bind_template_child_private
#define gtk_widget_class_bind_template_child_private (widget_class, TypeName, member_name)
Value:
  gtk_widget_class_bind_template_child_full (widget_class, \
                                             #member_name, \
                                             FALSE, \
                                             G_PRIVATE_OFFSET (TypeName, member_name))
gtk_widget_class_bind_template_child_private: @widget_class: a GtkWidgetClass @TypeName: the type name of this widget @member_name: name of the instance private member in the private struct for @data_type
Binds a child widget defined in a template to the @widget_class.
This macro is a convenience wrapper around the gtk_widget_class_bind_template_child_full() function.
This macro will use the offset of the @member_name inside the @TypeName private data structure (it uses G_PRIVATE_OFFSET(), so the private struct must be added with G_ADD_PRIVATE()).
Definition at line 802 of file gtkwidget.h.
#define gtk_widget_class_bind_template_child_private(widget_class, TypeName, member_name) \
  gtk_widget_class_bind_template_child_full (widget_class, \
                                             #member_name, \
                                             FALSE, \
                                             G_PRIVATE_OFFSET (TypeName, member_name))
GTK_WIDGET_GET_CLASS
#define GTK_WIDGET_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTK_TYPE_WIDGET, GtkWidgetClass))
Definition at line 48 of file gtkwidget.h.
Typedef Documentation
GtkAllocation
typedef GdkRectangle GtkAllocation
GtkAllocation: @x: the X position of the widgets area relative to its parents allocation. @y: the Y position of the widgets area relative to its parents allocation. @width: the width of the widgets allocated area. @height: the height of the widgets allocated area.
The rectangle representing the area allocated for a widget by its parent.
Definition at line 65 of file gtkwidget.h.
GtkTickCallback
typedef gboolean(* GtkTickCallback) (GtkWidget *widget, GdkFrameClock *frame_clock, gpointer user_data)
GtkTickCallback: @widget: the widget @frame_clock: the frame clock for the widget (same as calling gtk_widget_get_frame_clock()) @user_data: user data passed to gtk_widget_add_tick_callback().
Callback type for adding a function to update animations. See gtk_widget_add_tick_callback().
Returns: G_SOURCE_CONTINUE if the tick callback should continue to be called, G_SOURCE_REMOVE if the tick callback should be removed.
Definition at line 78 of file gtkwidget.h.
GtkWidgetActionActivateFunc
typedef void(* GtkWidgetActionActivateFunc) (GtkWidget *widget, const char *action_name, GVariant *parameter)
GtkWidgetActionActivateFunc: @widget: the widget to which the action belongs @action_name: the action name @parameter: (nullable): parameter for activation
The type of the callback functions used for activating actions installed with gtk_widget_class_install_action().
The @parameter must match the @parameter_type of the action.
Definition at line 947 of file gtkwidget.h.
GtkWidgetClass
typedef struct _GtkWidgetClass GtkWidgetClass
Definition at line 53 of file gtkwidget.h.
GtkWidgetClassPrivate
typedef struct _GtkWidgetClassPrivate GtkWidgetClassPrivate
Definition at line 54 of file gtkwidget.h.
GtkWidgetPrivate
typedef struct _GtkWidgetPrivate GtkWidgetPrivate
Definition at line 52 of file gtkwidget.h.
Function Documentation
gtk_requisition_copy()
GDK_AVAILABLE_IN_ALL GtkRequisition * gtk_requisition_copy (const GtkRequisition * requisition)
gtk_requisition_free()
GDK_AVAILABLE_IN_ALL void gtk_requisition_free (GtkRequisition * requisition)
gtk_requisition_get_type()
GDK_AVAILABLE_IN_ALL GType gtk_requisition_get_type (void)
gtk_requisition_new()
GDK_AVAILABLE_IN_ALL GtkRequisition * gtk_requisition_new (void)
gtk_widget_action_set_enabled()
GDK_AVAILABLE_IN_ALL void gtk_widget_action_set_enabled (GtkWidget * widget, const char * action_name, gboolean enabled)
gtk_widget_activate()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_activate (GtkWidget * widget)
gtk_widget_activate_action()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_activate_action (GtkWidget * widget, const char * name, const char * format_string, ...)
gtk_widget_activate_action_variant()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_activate_action_variant (GtkWidget * widget, const char * name, GVariant * args)
gtk_widget_activate_default()
GDK_AVAILABLE_IN_ALL void gtk_widget_activate_default (GtkWidget * widget)
gtk_widget_add_controller()
GDK_AVAILABLE_IN_ALL void gtk_widget_add_controller (GtkWidget * widget, GtkEventController * controller)
gtk_widget_add_css_class()
GDK_AVAILABLE_IN_ALL void gtk_widget_add_css_class (GtkWidget * widget, const char * css_class)
Referenced by activate().
gtk_widget_add_mnemonic_label()
GDK_AVAILABLE_IN_ALL void gtk_widget_add_mnemonic_label (GtkWidget * widget, GtkWidget * label)
gtk_widget_add_tick_callback()
GDK_AVAILABLE_IN_ALL guint gtk_widget_add_tick_callback (GtkWidget * widget, GtkTickCallback callback, gpointer user_data, GDestroyNotify notify)
gtk_widget_allocate()
GDK_AVAILABLE_IN_ALL void gtk_widget_allocate (GtkWidget * widget, int width, int height, int baseline, GskTransform * transform)
gtk_widget_child_focus()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_child_focus (GtkWidget * widget, GtkDirectionType direction)
gtk_widget_class_add_binding()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_add_binding (GtkWidgetClass * widget_class, guint keyval, GdkModifierType mods, GtkShortcutFunc callback, const char * format_string, ...)
gtk_widget_class_add_binding_action()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_add_binding_action (GtkWidgetClass * widget_class, guint keyval, GdkModifierType mods, const char * action_name, const char * format_string, ...)
gtk_widget_class_add_binding_signal()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_add_binding_signal (GtkWidgetClass * widget_class, guint keyval, GdkModifierType mods, const char * signal, const char * format_string, ...)
gtk_widget_class_add_shortcut()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_add_shortcut (GtkWidgetClass * widget_class, GtkShortcut * shortcut)
gtk_widget_class_bind_template_callback_full()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_bind_template_callback_full (GtkWidgetClass * widget_class, const char * callback_name, GCallback callback_symbol)
gtk_widget_class_bind_template_child_full()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_bind_template_child_full (GtkWidgetClass * widget_class, const char * name, gboolean internal_child, gssize struct_offset)
gtk_widget_class_get_accessible_role()
GDK_AVAILABLE_IN_ALL GtkAccessibleRole gtk_widget_class_get_accessible_role (GtkWidgetClass * widget_class)
gtk_widget_class_get_activate_signal()
GDK_AVAILABLE_IN_ALL guint gtk_widget_class_get_activate_signal (GtkWidgetClass * widget_class)
gtk_widget_class_get_css_name()
GDK_AVAILABLE_IN_ALL const char * gtk_widget_class_get_css_name (GtkWidgetClass * widget_class)
gtk_widget_class_get_layout_manager_type()
GDK_AVAILABLE_IN_ALL GType gtk_widget_class_get_layout_manager_type (GtkWidgetClass * widget_class)
gtk_widget_class_install_action()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_install_action (GtkWidgetClass * widget_class, const char * action_name, const char * parameter_type, GtkWidgetActionActivateFunc activate)
gtk_widget_class_install_property_action()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_install_property_action (GtkWidgetClass * widget_class, const char * action_name, const char * property_name)
gtk_widget_class_query_action()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_class_query_action (GtkWidgetClass * widget_class, guint index_, GType * owner, const char ** action_name, const GVariantType ** parameter_type, const char ** property_name)
gtk_widget_class_set_accessible_role()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_accessible_role (GtkWidgetClass * widget_class, GtkAccessibleRole accessible_role)
gtk_widget_class_set_activate_signal()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_activate_signal (GtkWidgetClass * widget_class, guint signal_id)
gtk_widget_class_set_activate_signal_from_name()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_activate_signal_from_name (GtkWidgetClass * widget_class, const char * signal_name)
gtk_widget_class_set_css_name()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_css_name (GtkWidgetClass * widget_class, const char * name)
gtk_widget_class_set_layout_manager_type()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_layout_manager_type (GtkWidgetClass * widget_class, GType type)
gtk_widget_class_set_template()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_template (GtkWidgetClass * widget_class, GBytes * template_bytes)
gtk_widget_class_set_template_from_resource()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_template_from_resource (GtkWidgetClass * widget_class, const char * resource_name)
gtk_widget_class_set_template_scope()
GDK_AVAILABLE_IN_ALL void gtk_widget_class_set_template_scope (GtkWidgetClass * widget_class, GtkBuilderScope * scope)
gtk_widget_compute_bounds()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_compute_bounds (GtkWidget * widget, GtkWidget * target, graphene_rect_t * out_bounds)
gtk_widget_compute_expand()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_compute_expand (GtkWidget * widget, GtkOrientation orientation)
gtk_widget_compute_point()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_compute_point (GtkWidget * widget, GtkWidget * target, const graphene_point_t * point, graphene_point_t * out_point)
gtk_widget_compute_transform()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_compute_transform (GtkWidget * widget, GtkWidget * target, graphene_matrix_t * out_transform)
gtk_widget_contains()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_contains (GtkWidget * widget, double x, double y)
gtk_widget_create_pango_context()
GDK_AVAILABLE_IN_ALL PangoContext * gtk_widget_create_pango_context (GtkWidget * widget)
gtk_widget_create_pango_layout()
GDK_AVAILABLE_IN_ALL PangoLayout * gtk_widget_create_pango_layout (GtkWidget * widget, const char * text)
gtk_widget_dispose_template()
GDK_AVAILABLE_IN_4_8 void gtk_widget_dispose_template (GtkWidget * widget, GType widget_type)
gtk_widget_error_bell()
GDK_AVAILABLE_IN_ALL void gtk_widget_error_bell (GtkWidget * widget)
gtk_widget_get_allocated_baseline()
int gtk_widget_get_allocated_baseline (GtkWidget * widget)
gtk_widget_get_allocated_height()
int gtk_widget_get_allocated_height (GtkWidget * widget)
gtk_widget_get_allocated_width()
int gtk_widget_get_allocated_width (GtkWidget * widget)
gtk_widget_get_allocation()
void gtk_widget_get_allocation (GtkWidget * widget, GtkAllocation * allocation)
gtk_widget_get_ancestor()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_ancestor (GtkWidget * widget, GType widget_type)
gtk_widget_get_baseline()
GDK_AVAILABLE_IN_4_12 int gtk_widget_get_baseline (GtkWidget * widget)
gtk_widget_get_can_focus()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_can_focus (GtkWidget * widget)
gtk_widget_get_can_target()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_can_target (GtkWidget * widget)
gtk_widget_get_child_visible()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_child_visible (GtkWidget * widget)
gtk_widget_get_clipboard()
GDK_AVAILABLE_IN_ALL GdkClipboard * gtk_widget_get_clipboard (GtkWidget * widget)
gtk_widget_get_color()
GDK_AVAILABLE_IN_4_10 void gtk_widget_get_color (GtkWidget * widget, GdkRGBA * color)
gtk_widget_get_css_classes()
GDK_AVAILABLE_IN_ALL char ** gtk_widget_get_css_classes (GtkWidget * widget)
gtk_widget_get_css_name()
GDK_AVAILABLE_IN_ALL const char * gtk_widget_get_css_name (GtkWidget * self)
gtk_widget_get_cursor()
GDK_AVAILABLE_IN_ALL GdkCursor * gtk_widget_get_cursor (GtkWidget * widget)
gtk_widget_get_default_direction()
GDK_AVAILABLE_IN_ALL GtkTextDirection gtk_widget_get_default_direction (void)
gtk_widget_get_direction()
GDK_AVAILABLE_IN_ALL GtkTextDirection gtk_widget_get_direction (GtkWidget * widget)
gtk_widget_get_display()
GDK_AVAILABLE_IN_ALL GdkDisplay * gtk_widget_get_display (GtkWidget * widget)
gtk_widget_get_first_child()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_first_child (GtkWidget * widget)
gtk_widget_get_focus_child()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_focus_child (GtkWidget * widget)
gtk_widget_get_focus_on_click()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_focus_on_click (GtkWidget * widget)
gtk_widget_get_focusable()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_focusable (GtkWidget * widget)
gtk_widget_get_font_map()
GDK_AVAILABLE_IN_ALL PangoFontMap * gtk_widget_get_font_map (GtkWidget * widget)
gtk_widget_get_font_options()
GDK_DEPRECATED_IN_4_16 const cairo_font_options_t * gtk_widget_get_font_options (GtkWidget * widget)
gtk_widget_get_frame_clock()
GDK_AVAILABLE_IN_ALL GdkFrameClock * gtk_widget_get_frame_clock (GtkWidget * widget)
gtk_widget_get_halign()
GDK_AVAILABLE_IN_ALL GtkAlign gtk_widget_get_halign (GtkWidget * widget)
gtk_widget_get_has_tooltip()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_has_tooltip (GtkWidget * widget)
gtk_widget_get_height()
GDK_AVAILABLE_IN_ALL int gtk_widget_get_height (GtkWidget * widget)
gtk_widget_get_hexpand()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_hexpand (GtkWidget * widget)
gtk_widget_get_hexpand_set()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_hexpand_set (GtkWidget * widget)
gtk_widget_get_last_child()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_last_child (GtkWidget * widget)
gtk_widget_get_layout_manager()
GDK_AVAILABLE_IN_ALL GtkLayoutManager * gtk_widget_get_layout_manager (GtkWidget * widget)
gtk_widget_get_mapped()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_mapped (GtkWidget * widget)
gtk_widget_get_margin_bottom()
GDK_AVAILABLE_IN_ALL int gtk_widget_get_margin_bottom (GtkWidget * widget)
gtk_widget_get_margin_end()
GDK_AVAILABLE_IN_ALL int gtk_widget_get_margin_end (GtkWidget * widget)
gtk_widget_get_margin_start()
GDK_AVAILABLE_IN_ALL int gtk_widget_get_margin_start (GtkWidget * widget)
gtk_widget_get_margin_top()
GDK_AVAILABLE_IN_ALL int gtk_widget_get_margin_top (GtkWidget * widget)
gtk_widget_get_name()
GDK_AVAILABLE_IN_ALL const char * gtk_widget_get_name (GtkWidget * widget)
gtk_widget_get_native()
GDK_AVAILABLE_IN_ALL GtkNative * gtk_widget_get_native (GtkWidget * widget)
gtk_widget_get_next_sibling()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_next_sibling (GtkWidget * widget)
gtk_widget_get_opacity()
GDK_AVAILABLE_IN_ALL double gtk_widget_get_opacity (GtkWidget * widget)
gtk_widget_get_overflow()
GDK_AVAILABLE_IN_ALL GtkOverflow gtk_widget_get_overflow (GtkWidget * widget)
gtk_widget_get_pango_context()
GDK_AVAILABLE_IN_ALL PangoContext * gtk_widget_get_pango_context (GtkWidget * widget)
gtk_widget_get_parent()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_parent (GtkWidget * widget)
gtk_widget_get_preferred_size()
GDK_AVAILABLE_IN_ALL void gtk_widget_get_preferred_size (GtkWidget * widget, GtkRequisition * minimum_size, GtkRequisition * natural_size)
gtk_widget_get_prev_sibling()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_get_prev_sibling (GtkWidget * widget)
gtk_widget_get_primary_clipboard()
GDK_AVAILABLE_IN_ALL GdkClipboard * gtk_widget_get_primary_clipboard (GtkWidget * widget)
gtk_widget_get_realized()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_realized (GtkWidget * widget)
gtk_widget_get_receives_default()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_receives_default (GtkWidget * widget)
gtk_widget_get_request_mode()
GDK_AVAILABLE_IN_ALL GtkSizeRequestMode gtk_widget_get_request_mode (GtkWidget * widget)
gtk_widget_get_root()
GDK_AVAILABLE_IN_ALL GtkRoot * gtk_widget_get_root (GtkWidget * widget)
gtk_widget_get_scale_factor()
GDK_AVAILABLE_IN_ALL int gtk_widget_get_scale_factor (GtkWidget * widget)
gtk_widget_get_sensitive()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_sensitive (GtkWidget * widget)
gtk_widget_get_settings()
GDK_AVAILABLE_IN_ALL GtkSettings * gtk_widget_get_settings (GtkWidget * widget)
gtk_widget_get_size()
GDK_AVAILABLE_IN_ALL int gtk_widget_get_size (GtkWidget * widget, GtkOrientation orientation)
gtk_widget_get_size_request()
GDK_AVAILABLE_IN_ALL void gtk_widget_get_size_request (GtkWidget * widget, int * width, int * height)
gtk_widget_get_state_flags()
GDK_AVAILABLE_IN_ALL GtkStateFlags gtk_widget_get_state_flags (GtkWidget * widget)
gtk_widget_get_style_context()
GDK_DEPRECATED_IN_4_10 GtkStyleContext * gtk_widget_get_style_context (GtkWidget * widget)
gtk_widget_get_template_child()
GDK_AVAILABLE_IN_ALL GObject * gtk_widget_get_template_child (GtkWidget * widget, GType widget_type, const char * name)
gtk_widget_get_tooltip_markup()
GDK_AVAILABLE_IN_ALL const char * gtk_widget_get_tooltip_markup (GtkWidget * widget)
gtk_widget_get_tooltip_text()
GDK_AVAILABLE_IN_ALL const char * gtk_widget_get_tooltip_text (GtkWidget * widget)
gtk_widget_get_type()
GDK_AVAILABLE_IN_ALL GType gtk_widget_get_type (void)
gtk_widget_get_valign()
GDK_AVAILABLE_IN_ALL GtkAlign gtk_widget_get_valign (GtkWidget * widget)
gtk_widget_get_vexpand()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_vexpand (GtkWidget * widget)
gtk_widget_get_vexpand_set()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_vexpand_set (GtkWidget * widget)
gtk_widget_get_visible()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_get_visible (GtkWidget * widget)
gtk_widget_get_width()
GDK_AVAILABLE_IN_ALL int gtk_widget_get_width (GtkWidget * widget)
gtk_widget_grab_focus()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_grab_focus (GtkWidget * widget)
gtk_widget_has_css_class()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_has_css_class (GtkWidget * widget, const char * css_class)
gtk_widget_has_default()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_has_default (GtkWidget * widget)
gtk_widget_has_focus()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_has_focus (GtkWidget * widget)
gtk_widget_has_visible_focus()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_has_visible_focus (GtkWidget * widget)
gtk_widget_hide()
void gtk_widget_hide (GtkWidget * widget)
gtk_widget_in_destruction()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_in_destruction (GtkWidget * widget)
gtk_widget_init_template()
GDK_AVAILABLE_IN_ALL void gtk_widget_init_template (GtkWidget * widget)
gtk_widget_insert_action_group()
GDK_AVAILABLE_IN_ALL void gtk_widget_insert_action_group (GtkWidget * widget, const char * name, GActionGroup * group)
gtk_widget_insert_after()
GDK_AVAILABLE_IN_ALL void gtk_widget_insert_after (GtkWidget * widget, GtkWidget * parent, GtkWidget * previous_sibling)
gtk_widget_insert_before()
GDK_AVAILABLE_IN_ALL void gtk_widget_insert_before (GtkWidget * widget, GtkWidget * parent, GtkWidget * next_sibling)
gtk_widget_is_ancestor()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_ancestor (GtkWidget * widget, GtkWidget * ancestor)
gtk_widget_is_drawable()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_drawable (GtkWidget * widget)
gtk_widget_is_focus()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_focus (GtkWidget * widget)
gtk_widget_is_sensitive()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_sensitive (GtkWidget * widget)
gtk_widget_is_visible()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_is_visible (GtkWidget * widget)
gtk_widget_keynav_failed()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_keynav_failed (GtkWidget * widget, GtkDirectionType direction)
gtk_widget_list_mnemonic_labels()
GDK_AVAILABLE_IN_ALL GList * gtk_widget_list_mnemonic_labels (GtkWidget * widget)
gtk_widget_map()
GDK_AVAILABLE_IN_ALL void gtk_widget_map (GtkWidget * widget)
gtk_widget_measure()
GDK_AVAILABLE_IN_ALL void gtk_widget_measure (GtkWidget * widget, GtkOrientation orientation, int for_size, int * minimum, int * natural, int * minimum_baseline, int * natural_baseline)
gtk_widget_mnemonic_activate()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_mnemonic_activate (GtkWidget * widget, gboolean group_cycling)
gtk_widget_observe_children()
GDK_AVAILABLE_IN_ALL GListModel * gtk_widget_observe_children (GtkWidget * widget)
gtk_widget_observe_controllers()
GDK_AVAILABLE_IN_ALL GListModel * gtk_widget_observe_controllers (GtkWidget * widget)
gtk_widget_pick()
GDK_AVAILABLE_IN_ALL GtkWidget * gtk_widget_pick (GtkWidget * widget, double x, double y, GtkPickFlags flags)
gtk_widget_queue_allocate()
GDK_AVAILABLE_IN_ALL void gtk_widget_queue_allocate (GtkWidget * widget)
gtk_widget_queue_draw()
GDK_AVAILABLE_IN_ALL void gtk_widget_queue_draw (GtkWidget * widget)
gtk_widget_queue_resize()
GDK_AVAILABLE_IN_ALL void gtk_widget_queue_resize (GtkWidget * widget)
gtk_widget_realize()
GDK_AVAILABLE_IN_ALL void gtk_widget_realize (GtkWidget * widget)
gtk_widget_remove_controller()
GDK_AVAILABLE_IN_ALL void gtk_widget_remove_controller (GtkWidget * widget, GtkEventController * controller)
gtk_widget_remove_css_class()
GDK_AVAILABLE_IN_ALL void gtk_widget_remove_css_class (GtkWidget * widget, const char * css_class)
gtk_widget_remove_mnemonic_label()
GDK_AVAILABLE_IN_ALL void gtk_widget_remove_mnemonic_label (GtkWidget * widget, GtkWidget * label)
gtk_widget_remove_tick_callback()
GDK_AVAILABLE_IN_ALL void gtk_widget_remove_tick_callback (GtkWidget * widget, guint id)
gtk_widget_set_can_focus()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_can_focus (GtkWidget * widget, gboolean can_focus)
gtk_widget_set_can_target()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_can_target (GtkWidget * widget, gboolean can_target)
gtk_widget_set_child_visible()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_child_visible (GtkWidget * widget, gboolean child_visible)
gtk_widget_set_css_classes()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_css_classes (GtkWidget * widget, const char ** classes)
gtk_widget_set_cursor()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_cursor (GtkWidget * widget, GdkCursor * cursor)
gtk_widget_set_cursor_from_name()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_cursor_from_name (GtkWidget * widget, const char * name)
gtk_widget_set_default_direction()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_default_direction (GtkTextDirection dir)
gtk_widget_set_direction()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_direction (GtkWidget * widget, GtkTextDirection dir)
gtk_widget_set_focus_child()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_focus_child (GtkWidget * widget, GtkWidget * child)
gtk_widget_set_focus_on_click()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_focus_on_click (GtkWidget * widget, gboolean focus_on_click)
gtk_widget_set_focusable()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_focusable (GtkWidget * widget, gboolean focusable)
gtk_widget_set_font_map()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_font_map (GtkWidget * widget, PangoFontMap * font_map)
gtk_widget_set_font_options()
GDK_DEPRECATED_IN_4_16 void gtk_widget_set_font_options (GtkWidget * widget, const cairo_font_options_t * options)
gtk_widget_set_halign()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_halign (GtkWidget * widget, GtkAlign align)
gtk_widget_set_has_tooltip()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_has_tooltip (GtkWidget * widget, gboolean has_tooltip)
gtk_widget_set_hexpand()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_hexpand (GtkWidget * widget, gboolean expand)
gtk_widget_set_hexpand_set()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_hexpand_set (GtkWidget * widget, gboolean set)
gtk_widget_set_layout_manager()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_layout_manager (GtkWidget * widget, GtkLayoutManager * layout_manager)
gtk_widget_set_margin_bottom()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_margin_bottom (GtkWidget * widget, int margin)
Referenced by activate().
gtk_widget_set_margin_end()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_margin_end (GtkWidget * widget, int margin)
Referenced by activate().
gtk_widget_set_margin_start()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_margin_start (GtkWidget * widget, int margin)
Referenced by activate().
gtk_widget_set_margin_top()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_margin_top (GtkWidget * widget, int margin)
Referenced by activate().
gtk_widget_set_name()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_name (GtkWidget * widget, const char * name)
gtk_widget_set_opacity()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_opacity (GtkWidget * widget, double opacity)
gtk_widget_set_overflow()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_overflow (GtkWidget * widget, GtkOverflow overflow)
gtk_widget_set_parent()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_parent (GtkWidget * widget, GtkWidget * parent)
gtk_widget_set_receives_default()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_receives_default (GtkWidget * widget, gboolean receives_default)
gtk_widget_set_sensitive()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_sensitive (GtkWidget * widget, gboolean sensitive)
gtk_widget_set_size_request()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_size_request (GtkWidget * widget, int width, int height)
gtk_widget_set_state_flags()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_state_flags (GtkWidget * widget, GtkStateFlags flags, gboolean clear)
gtk_widget_set_tooltip_markup()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_tooltip_markup (GtkWidget * widget, const char * markup)
gtk_widget_set_tooltip_text()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_tooltip_text (GtkWidget * widget, const char * text)
gtk_widget_set_valign()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_valign (GtkWidget * widget, GtkAlign align)
gtk_widget_set_vexpand()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_vexpand (GtkWidget * widget, gboolean expand)
Referenced by activate().
gtk_widget_set_vexpand_set()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_vexpand_set (GtkWidget * widget, gboolean set)
gtk_widget_set_visible()
GDK_AVAILABLE_IN_ALL void gtk_widget_set_visible (GtkWidget * widget, gboolean visible)
gtk_widget_should_layout()
GDK_AVAILABLE_IN_ALL gboolean gtk_widget_should_layout (GtkWidget * widget)
gtk_widget_show()
void gtk_widget_show (GtkWidget * widget)
gtk_widget_size_allocate()
GDK_AVAILABLE_IN_ALL void gtk_widget_size_allocate (GtkWidget * widget, const GtkAllocation * allocation, int baseline)
gtk_widget_snapshot_child()
GDK_AVAILABLE_IN_ALL void gtk_widget_snapshot_child (GtkWidget * widget, GtkWidget * child, GtkSnapshot * snapshot)
gtk_widget_translate_coordinates()
gboolean gtk_widget_translate_coordinates (GtkWidget * src_widget, GtkWidget * dest_widget, double src_x, double src_y, double * dest_x, double * dest_y)
gtk_widget_trigger_tooltip_query()
GDK_AVAILABLE_IN_ALL void gtk_widget_trigger_tooltip_query (GtkWidget * widget)
gtk_widget_unmap()
GDK_AVAILABLE_IN_ALL void gtk_widget_unmap (GtkWidget * widget)
gtk_widget_unparent()
GDK_AVAILABLE_IN_ALL void gtk_widget_unparent (GtkWidget * widget)
gtk_widget_unrealize()
GDK_AVAILABLE_IN_ALL void gtk_widget_unrealize (GtkWidget * widget)
gtk_widget_unset_state_flags()
GDK_AVAILABLE_IN_ALL void gtk_widget_unset_state_flags (GtkWidget * widget, GtkStateFlags flags)