Github User Fetcher: lfs.h File Reference
lfs.h File Reference
Macros
#define chdir_error strerror(errno)
#define LFS_EXPORT
Functions
LFS_EXPORT int luaopen_lfs (lua_State *L)
Macro Definition Documentation
chdir_error
#define chdir_error strerror(errno)
Definition at line 12 of file lfs.h.
Referenced by change_dir().
LFS_EXPORT
#define LFS_EXPORT
Definition at line 24 of file lfs.h.
Function Documentation
luaopen_lfs()
LFS_EXPORT int luaopen_lfs (lua_State * L)
Definition at line 1173 of file lfs.c.
{
  dir_create_meta(L);
  lock_create_meta(L);
  new_lib(L, fslib);
  lua_pushvalue(L, -1);
  lua_setglobal(L, LFS_LIBNAME);
  set_info(L);
  return 1;
}
References dir_create_meta(), fslib, LFS_LIBNAME, lock_create_meta(), lua_pushvalue(), lua_setglobal, new_lib, and set_info().