Github User Fetcher: lsqlite3.c File Reference
lsqlite3.c File Reference
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "civetweb_lua.h"
#include "sqlite3.h"
Data Structures
struct sdb_func
struct sdb
struct sdb_vm
struct lcontext
struct scc
struct sdb_bu
Macros
#define SQLITE_OMIT_PROGRESS_CALLBACK 0
#define LSQLITE_OMIT_UPDATE_HOOK 0
#define SQLITE3_OPEN(L, filename, flags) sqlite3_open_v2(L,filename,flags,NULL)
#define PUSH_INT64(L, i64in, fallback)
#define LSQLITE_VERSION "unknown"
#define SC(s) { #s, SQLITE_ ## s },
#define LSC(s) { #s, LSQLITE_ ## s },
Typedefs
typedef struct sdb sdb
typedef struct sdb_vm sdb_vm
typedef struct sdb_bu sdb_bu
typedef struct sdb_func sdb_func
Functions
static void vm_push_column (lua_State *L, sqlite3_stmt *vm, int idx)
static sdb_vm * newvm (lua_State *L, sdb *db)
static int cleanupvm (lua_State *L, sdb_vm *svm)
static int stepvm (lua_State *L, sdb_vm *svm)
static sdb_vm * lsqlite_getvm (lua_State *L, int index)
static sdb_vm * lsqlite_checkvm (lua_State *L, int index)
static int dbvm_isopen (lua_State *L)
static int dbvm_tostring (lua_State *L)
static int dbvm_gc (lua_State *L)
static int dbvm_step (lua_State *L)
static int dbvm_finalize (lua_State *L)
static int dbvm_reset (lua_State *L)
static void dbvm_check_contents (lua_State *L, sdb_vm *svm)
static void dbvm_check_index (lua_State *L, sdb_vm *svm, int index)
static void dbvm_check_bind_index (lua_State *L, sdb_vm *svm, int index)
static int dbvm_last_insert_rowid (lua_State *L)
static int dbvm_columns (lua_State *L)
static int dbvm_get_value (lua_State *L)
static int dbvm_get_name (lua_State *L)
static int dbvm_get_type (lua_State *L)
static int dbvm_get_values (lua_State *L)
static int dbvm_get_names (lua_State *L)
static int dbvm_get_types (lua_State *L)
static int dbvm_get_uvalues (lua_State *L)
static int dbvm_get_unames (lua_State *L)
static int dbvm_get_utypes (lua_State *L)
static int dbvm_get_named_values (lua_State *L)
static int dbvm_get_named_types (lua_State *L)
static int dbvm_bind_index (lua_State *L, sqlite3_stmt *vm, int index, int lindex)
static int dbvm_bind_parameter_count (lua_State *L)
static int dbvm_bind_parameter_name (lua_State *L)
static int dbvm_bind (lua_State *L)
static int dbvm_bind_blob (lua_State *L)
static int dbvm_bind_values (lua_State *L)
static int dbvm_bind_names (lua_State *L)
static sdb * newdb (lua_State *L)
static int cleanupdb (lua_State *L, sdb *db)
static sdb * lsqlite_getdb (lua_State *L, int index)
static sdb * lsqlite_checkdb (lua_State *L, int index)
static lcontext * lsqlite_make_context (lua_State *L)
static lcontext * lsqlite_getcontext (lua_State *L, int index)
static lcontext * lsqlite_checkcontext (lua_State *L, int index)
static int lcontext_tostring (lua_State *L)
static void lcontext_check_aggregate (lua_State *L, lcontext *ctx)
static int lcontext_user_data (lua_State *L)
static int lcontext_get_aggregate_context (lua_State *L)
static int lcontext_set_aggregate_context (lua_State *L)
static int lcontext_aggregate_count (lua_State *L)
static int lcontext_result (lua_State *L)
static int lcontext_result_blob (lua_State *L)
static int lcontext_result_double (lua_State *L)
static int lcontext_result_error (lua_State *L)
static int lcontext_result_int (lua_State *L)
static int lcontext_result_null (lua_State *L)
static int lcontext_result_text (lua_State *L)
static int db_isopen (lua_State *L)
static int db_last_insert_rowid (lua_State *L)
static int db_changes (lua_State *L)
static int db_total_changes (lua_State *L)
static int db_errcode (lua_State *L)
static int db_errmsg (lua_State *L)
static int db_interrupt (lua_State *L)
static int db_db_filename (lua_State *L)
static void db_push_value (lua_State *L, sqlite3_value *value)
static void db_sql_normal_function (sqlite3_context *context, int argc, sqlite3_value **argv)
static void db_sql_finalize_function (sqlite3_context *context)
static int db_register_function (lua_State *L, int aggregate)
static int db_create_function (lua_State *L)
static int db_create_aggregate (lua_State *L)
static int collwrapper (scc *co, int l1, const void *p1, int l2, const void *p2)
static void collfree (scc *co)
static int db_create_collation (lua_State *L)
static int db_load_extension (lua_State *L)
static void db_trace_callback (void *user, const char *sql)
static int db_trace (lua_State *L)
static void db_update_hook_callback (void *user, int op, char const *dbname, char const *tblname, sqlite3_int64 rowid)
static int db_update_hook (lua_State *L)
static int db_commit_hook_callback (void *user)
static int db_commit_hook (lua_State *L)
static void db_rollback_hook_callback (void *user)
static int db_rollback_hook (lua_State *L)
static int db_progress_callback (void *user)
static int db_progress_handler (lua_State *L)
static int cleanupbu (lua_State *L, sdb_bu *sbu)
static int lsqlite_backup_init (lua_State *L)
static sdb_bu * lsqlite_getbu (lua_State *L, int index)
static sdb_bu * lsqlite_checkbu (lua_State *L, int index)
static int dbbu_gc (lua_State *L)
static int dbbu_step (lua_State *L)
static int dbbu_remaining (lua_State *L)
static int dbbu_pagecount (lua_State *L)
static int dbbu_finish (lua_State *L)
static int db_busy_callback (void *user, int tries)
static int db_busy_handler (lua_State *L)
static int db_busy_timeout (lua_State *L)
static int db_exec_callback (void *user, int columns, char **data, char **names)
static int db_exec (lua_State *L)
static int db_prepare (lua_State *L)
static int db_do_next_row (lua_State *L, int packed)
static int db_next_row (lua_State *L)
static int db_next_packed_row (lua_State *L)
static int db_next_named_row (lua_State *L)
static int dbvm_do_rows (lua_State *L, int(*f)(lua_State *))
static int dbvm_rows (lua_State *L)
static int dbvm_nrows (lua_State *L)
static int dbvm_urows (lua_State *L)
static int db_do_rows (lua_State *L, int(*f)(lua_State *))
static int db_rows (lua_State *L)
static int db_nrows (lua_State *L)
static int db_urows (lua_State *L)
static int db_tostring (lua_State *L)
static int db_close (lua_State *L)
static int db_close_vm (lua_State *L)
static int db_get_ptr (lua_State *L)
static int db_gc (lua_State *L)
static int lsqlite_version (lua_State *L)
static int lsqlite_complete (lua_State *L)
static int lsqlite_temp_directory (lua_State *L)
static int lsqlite_do_open (lua_State *L, const char *filename, int flags)
static int lsqlite_open (lua_State *L)
static int lsqlite_open_memory (lua_State *L)
static int lsqlite_open_ptr (lua_State *L)
static int lsqlite_newindex (lua_State *L)
static int lsqlite_lversion (lua_State *L)
static void create_meta (lua_State *L, const char *name, const luaL_Reg *lib)
static int luaopen_sqlitelib (lua_State *L)
LUALIB_API int luaopen_lsqlite3 (lua_State *L)
Variables
static const char * sqlite_meta = ":sqlite3"
static const char * sqlite_vm_meta = ":sqlite3:vm"
static const char * sqlite_bu_meta = ":sqlite3:bu"
static const char * sqlite_ctx_meta = ":sqlite3:ctx"
static int sqlite_ctx_meta_ref
struct {
const char * name
int value
} sqlite_constants []
static const luaL_Reg dblib []
static const luaL_Reg vmlib []
static const luaL_Reg ctxlib []
static const luaL_Reg dbbulib []
static const luaL_Reg sqlitelib []
Macro Definition Documentation
LSC
#define LSC (s) { #s, LSQLITE_ ## s },
Definition at line 2151 of file lsqlite3.c.
LSQLITE_OMIT_UPDATE_HOOK
#define LSQLITE_OMIT_UPDATE_HOOK 0
Definition at line 64 of file lsqlite3.c.
LSQLITE_VERSION
#define LSQLITE_VERSION "unknown"
Definition at line 2134 of file lsqlite3.c.
Referenced by lsqlite_lversion().
PUSH_INT64
#define PUSH_INT64 (L, i64in, fallback)
Value:
    do { \
        sqlite_int64 i64 = i64in; \
        lua_Number n = (lua_Number)i64; \
        if (n == i64) lua_pushnumber(L, n); \
        else fallback; \
    } while (0)
Definition at line 147 of file lsqlite3.c.
#define PUSH_INT64(L,i64in,fallback) \
    do { \
        sqlite_int64 i64 = i64in; \
        lua_Number n = (lua_Number)i64; \
        if (n == i64) lua_pushnumber(L, n); \
        else fallback; \
    } while (0)
Referenced by db_last_insert_rowid(), db_push_value(), db_update_hook_callback(), dbvm_last_insert_rowid(), and vm_push_column().
SC
#define SC (s) { #s, SQLITE_ ## s },
Definition at line 2150 of file lsqlite3.c.
SQLITE3_OPEN
#define SQLITE3_OPEN (L, filename, flags) sqlite3_open_v2(L,filename,flags,NULL)
Definition at line 69 of file lsqlite3.c.
Referenced by lsqlite_do_open().
SQLITE_OMIT_PROGRESS_CALLBACK
#define SQLITE_OMIT_PROGRESS_CALLBACK 0
Definition at line 61 of file lsqlite3.c.
Typedef Documentation
sdb
typedef struct sdb sdb
Definition at line 72 of file lsqlite3.c.
sdb_bu
typedef struct sdb_bu sdb_bu
Definition at line 74 of file lsqlite3.c.
sdb_func
typedef struct sdb_func sdb_func
Definition at line 75 of file lsqlite3.c.
sdb_vm
typedef struct sdb_vm sdb_vm
Definition at line 73 of file lsqlite3.c.
Function Documentation
cleanupbu()
static int cleanupbu (lua_State * L, sdb_bu * sbu) static
Definition at line 1572 of file lsqlite3.c.
{
    if (!sbu->bu) return 0; /* already finished */
    /* remove table from registry */
    lua_pushlightuserdata(L, sbu->bu);
    lua_pushnil(L);
    lua_rawset(L, LUA_REGISTRYINDEX);
    lua_pushinteger(L, sqlite3_backup_finish(sbu->bu));
    sbu->bu = NULL;
    return 1;
}
References sdb_bu::bu, lua_pushinteger(), lua_pushlightuserdata(), lua_pushnil(), lua_rawset(), LUA_REGISTRYINDEX, NULL, and sqlite3_backup_finish().
Referenced by dbbu_finish(), and dbbu_gc().
cleanupdb()
static int cleanupdb (lua_State * L, sdb * db) static
Definition at line 654 of file lsqlite3.c.
{
    sdb_func *func;
    sdb_func *func_next;
    int top;
    int result;
    /* free associated virtual machines */
    lua_pushlightuserdata(L, db);
    lua_rawget(L, LUA_REGISTRYINDEX);
    /* close all used handles */
    top = lua_gettop(L);
    lua_pushnil(L);
    while (lua_next(L, -2)) {
        sdb_vm *svm = lua_touserdata(L, -2); /* key: vm; val: sql text */
        cleanupvm(L, svm);
        lua_settop(L, top);
        lua_pushnil(L);
    }
    lua_pop(L, 1); /* pop vm table */
    /* remove entry in lua registry table */
    lua_pushlightuserdata(L, db);
    lua_pushnil(L);
    lua_rawset(L, LUA_REGISTRYINDEX);
    /* 'free' all references */
    luaL_unref(L, LUA_REGISTRYINDEX, db->busy_cb);
    luaL_unref(L, LUA_REGISTRYINDEX, db->busy_udata);
    luaL_unref(L, LUA_REGISTRYINDEX, db->progress_cb);
    luaL_unref(L, LUA_REGISTRYINDEX, db->progress_udata);
    luaL_unref(L, LUA_REGISTRYINDEX, db->trace_cb);
    luaL_unref(L, LUA_REGISTRYINDEX, db->trace_udata);
#if !defined(LSQLITE_OMIT_UPDATE_HOOK) || !LSQLITE_OMIT_UPDATE_HOOK
    luaL_unref(L, LUA_REGISTRYINDEX, db->update_hook_cb);
    luaL_unref(L, LUA_REGISTRYINDEX, db->update_hook_udata);
    luaL_unref(L, LUA_REGISTRYINDEX, db->commit_hook_cb);
    luaL_unref(L, LUA_REGISTRYINDEX, db->commit_hook_udata);
    luaL_unref(L, LUA_REGISTRYINDEX, db->rollback_hook_cb);
    luaL_unref(L, LUA_REGISTRYINDEX, db->rollback_hook_udata);
#endif
    /* close database */
    result = sqlite3_close(db->db);
    db->db = NULL;
    /* free associated memory with created functions */
    func = db->func;
    while (func) {
        func_next = func->next;
        luaL_unref(L, LUA_REGISTRYINDEX, func->fn_step);
        luaL_unref(L, LUA_REGISTRYINDEX, func->fn_finalize);
        luaL_unref(L, LUA_REGISTRYINDEX, func->udata);
        free(func);
        func = func_next;
    }
    db->func = NULL;
    return result;
}
References sdb::busy_cb, sdb::busy_udata, cleanupvm(), sdb::commit_hook_cb, sdb::commit_hook_udata, sdb::db, sdb_func::fn_finalize, sdb_func::fn_step, free, sdb::func, lua_gettop(), lua_next(), lua_pop, lua_pushlightuserdata(), lua_pushnil(), lua_rawget(), lua_rawset(), LUA_REGISTRYINDEX, lua_settop(), lua_touserdata(), luaL_unref(), sdb_func::next, NULL, sdb::progress_cb, sdb::progress_udata, sdb::rollback_hook_cb, sdb::rollback_hook_udata, sqlite3_close(), sdb::trace_cb, sdb::trace_udata, sdb_func::udata, sdb::update_hook_cb, and sdb::update_hook_udata.
Referenced by db_close(), db_gc(), and lsqlite_do_open().
cleanupvm()
static int cleanupvm (lua_State * L, sdb_vm * svm) static
Definition at line 223 of file lsqlite3.c.
{
    /* remove entry in database table - no harm if not present in the table */
    lua_pushlightuserdata(L, svm->db);
    lua_rawget(L, LUA_REGISTRYINDEX);
    lua_pushlightuserdata(L, svm);
    lua_pushnil(L);
    lua_rawset(L, -3);
    lua_pop(L, 1);
    svm->columns = 0;
    svm->has_values = 0;
    if (!svm->vm) return 0;
    lua_pushinteger(L, sqlite3_finalize(svm->vm));
    svm->vm = NULL;
    return 1;
}
References sdb_vm::columns, sdb_vm::db, sdb_vm::has_values, lua_pop, lua_pushinteger(), lua_pushlightuserdata(), lua_pushnil(), lua_rawget(), lua_rawset(), LUA_REGISTRYINDEX, NULL, sqlite3_finalize(), and sdb_vm::vm.
Referenced by cleanupdb(), db_do_next_row(), db_do_rows(), db_prepare(), dbvm_finalize(), and dbvm_gc().
collfree()
static void collfree (scc * co) static
Definition at line 1187 of file lsqlite3.c.
{
    if (co) {
        luaL_unref(co->L,LUA_REGISTRYINDEX,co->ref);
        free(co);
    }
}
References free, scc::L, LUA_REGISTRYINDEX, luaL_unref(), and scc::ref.
Referenced by db_create_collation().
collwrapper()
static int collwrapper (scc * co, int l1, const void * p1, int l2, const void * p2) static
Definition at line 1175 of file lsqlite3.c.
{
    int res=0;
    lua_State *L=co->L;
    lua_rawgeti(L,LUA_REGISTRYINDEX,co->ref);
    lua_pushlstring(L,p1,l1);
    lua_pushlstring(L,p2,l2);
    if (lua_pcall(L,2,1,0)==0) res=(int)lua_tonumber(L,-1);
    lua_pop(L,1);
    return res;
}
References scc::L, lua_pcall, lua_pop, lua_pushlstring(), lua_rawgeti(), LUA_REGISTRYINDEX, lua_tonumber, and scc::ref.
Referenced by db_create_collation().
create_meta()
static void create_meta (lua_State * L, const char * name, const luaL_Reg * lib) static
Definition at line 2365 of file lsqlite3.c.
{
    luaL_newmetatable(L, name);
    lua_pushstring(L, "__index");
    lua_pushvalue(L, -2);               /* push metatable */
    lua_rawset(L, -3);                  /* metatable.__index = metatable */
    /* register metatable functions */
    luaL_openlib(L, NULL, lib, 0);
    /* remove metatable from stack */
    lua_pop(L, 1);
}
References lua_pop, lua_pushstring(), lua_pushvalue(), lua_rawset(), luaL_newmetatable(), name, and NULL.
Referenced by luaopen_lsqlite3().
db_busy_callback()
static int db_busy_callback (void * user, int tries) static
Definition at line 1678 of file lsqlite3.c.
{
    int retry = 0; /* abort by default */
    sdb *db = (sdb*)user;
    lua_State *L = db->L;
    int top = lua_gettop(L);
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->busy_cb);
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->busy_udata);
    lua_pushinteger(L, tries);
    /* call lua function */
    if (!lua_pcall(L, 2, 1, 0))
        retry = lua_toboolean(L, -1);
    lua_settop(L, top);
    return retry;
}
References sdb::busy_cb, sdb::busy_udata, sdb::L, lua_gettop(), lua_pcall, lua_pushinteger(), lua_rawgeti(), LUA_REGISTRYINDEX, lua_settop(), and lua_toboolean().
Referenced by db_busy_handler().
db_busy_handler()
static int db_busy_handler (lua_State * L) static
Definition at line 1696 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    if (lua_gettop(L) < 2 || lua_isnil(L, 2)) {
        luaL_unref(L, LUA_REGISTRYINDEX, db->busy_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->busy_udata);
        db->busy_cb =
        db->busy_udata = LUA_NOREF;
        /* clear busy handler */
        sqlite3_busy_handler(db->db, NULL, NULL);
    }
    else {
        luaL_checktype(L, 2, LUA_TFUNCTION);
        /* make sure we have an userdata field (even if nil) */
        lua_settop(L, 3);
        luaL_unref(L, LUA_REGISTRYINDEX, db->busy_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->busy_udata);
        db->busy_udata = luaL_ref(L, LUA_REGISTRYINDEX);
        db->busy_cb = luaL_ref(L, LUA_REGISTRYINDEX);
        /* set busy handler */
        sqlite3_busy_handler(db->db, db_busy_callback, db);
    }
    return 0;
}
References sdb::busy_cb, sdb::busy_udata, sdb::db, db_busy_callback(), lsqlite_checkdb(), lua_gettop(), lua_isnil, LUA_NOREF, LUA_REGISTRYINDEX, lua_settop(), LUA_TFUNCTION, luaL_checktype(), luaL_ref(), luaL_unref(), NULL, and sqlite3_busy_handler().
db_busy_timeout()
static int db_busy_timeout (lua_State * L) static
Definition at line 1727 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    int timeout = luaL_checkint(L, 2);
    sqlite3_busy_timeout(db->db, timeout);
    /* if there was a timeout callback registered, it is now
    ** invalid/useless. free any references we may have */
    luaL_unref(L, LUA_REGISTRYINDEX, db->busy_cb);
    luaL_unref(L, LUA_REGISTRYINDEX, db->busy_udata);
    db->busy_cb =
    db->busy_udata = LUA_NOREF;
    return 0;
}
References sdb::busy_cb, sdb::busy_udata, sdb::db, lsqlite_checkdb(), LUA_NOREF, LUA_REGISTRYINDEX, luaL_checkint, luaL_unref(), and sqlite3_busy_timeout().
db_changes()
static int db_changes (lua_State * L) static
Definition at line 903 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    lua_pushinteger(L, sqlite3_changes(db->db));
    return 1;
}
References sdb::db, lsqlite_checkdb(), lua_pushinteger(), and sqlite3_changes().
db_close()
static int db_close (lua_State * L) static
Definition at line 1984 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    lua_pushinteger(L, cleanupdb(L, db));
    return 1;
}
References cleanupdb(), lsqlite_checkdb(), and lua_pushinteger().
db_close_vm()
static int db_close_vm (lua_State * L) static
Definition at line 1990 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    /* cleanup temporary only tables? */
    int temp = lua_toboolean(L, 2);
    /* free associated virtual machines */
    lua_pushlightuserdata(L, db);
    lua_rawget(L, LUA_REGISTRYINDEX);
    /* close all used handles */
    lua_pushnil(L);
    while (lua_next(L, -2)) {
        sdb_vm *svm = lua_touserdata(L, -2); /* key: vm; val: sql text */
        if ((!temp || svm->temp) && svm->vm)
        {
            sqlite3_finalize(svm->vm);
            svm->vm = NULL;
        }
        /* leave key in the stack */
        lua_pop(L, 1);
    }
    return 0;
}
References lsqlite_checkdb(), lua_next(), lua_pop, lua_pushlightuserdata(), lua_pushnil(), lua_rawget(), LUA_REGISTRYINDEX, lua_toboolean(), lua_touserdata(), NULL, sqlite3_finalize(), sdb_vm::temp, and sdb_vm::vm.
db_commit_hook()
static int db_commit_hook (lua_State * L) static
Definition at line 1395 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    if (lua_gettop(L) < 2 || lua_isnil(L, 2)) {
        luaL_unref(L, LUA_REGISTRYINDEX, db->commit_hook_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->commit_hook_udata);
        db->commit_hook_cb =
        db->commit_hook_udata = LUA_NOREF;
        /* clear commit_hook handler */
        sqlite3_commit_hook(db->db, NULL, NULL);
    }
    else {
        luaL_checktype(L, 2, LUA_TFUNCTION);
        /* make sure we have an userdata field (even if nil) */
        lua_settop(L, 3);
        luaL_unref(L, LUA_REGISTRYINDEX, db->commit_hook_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->commit_hook_udata);
        db->commit_hook_udata = luaL_ref(L, LUA_REGISTRYINDEX);
        db->commit_hook_cb = luaL_ref(L, LUA_REGISTRYINDEX);
        /* set commit_hook handler */
        sqlite3_commit_hook(db->db, db_commit_hook_callback, db);
    }
    return 0;
}
References sdb::commit_hook_cb, sdb::commit_hook_udata, sdb::db, db_commit_hook_callback(), lsqlite_checkdb(), lua_gettop(), lua_isnil, LUA_NOREF, LUA_REGISTRYINDEX, lua_settop(), LUA_TFUNCTION, luaL_checktype(), luaL_ref(), luaL_unref(), NULL, and sqlite3_commit_hook().
db_commit_hook_callback()
static int db_commit_hook_callback (void * user) static
Definition at line 1377 of file lsqlite3.c.
{
    sdb *db = (sdb*)user;
    lua_State *L = db->L;
    int top = lua_gettop(L);
    int rollback = 0;
    /* setup lua callback call */
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->commit_hook_cb);    /* get callback */
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->commit_hook_udata); /* get callback user data */
    /* call lua function */
    if (!lua_pcall(L, 1, 1, 0))
        rollback = lua_toboolean(L, -1); /* use result if there was no error */
    lua_settop(L, top);
    return rollback;
}
References sdb::commit_hook_cb, sdb::commit_hook_udata, sdb::L, lua_gettop(), lua_pcall, lua_rawgeti(), LUA_REGISTRYINDEX, lua_settop(), and lua_toboolean().
Referenced by db_commit_hook().
db_create_aggregate()
static int db_create_aggregate (lua_State * L) static
Definition at line 1163 of file lsqlite3.c.
{
    return db_register_function(L, 1);
}
References db_register_function().
db_create_collation()
static int db_create_collation (lua_State * L) static
Definition at line 1194 of file lsqlite3.c.
{
    sdb *db=lsqlite_checkdb(L,1);
    const char *collname=luaL_checkstring(L,2);
    scc *co=NULL;
    int (*collfunc)(scc *,int,const void *,int,const void *)=NULL;
    lua_settop(L,3); /* default args to nil, and exclude extras */
    if (lua_isfunction(L,3)) collfunc=collwrapper;
    else if (!lua_isnil(L,3))
        luaL_error(L,"create_collation: function or nil expected");
    if (collfunc != NULL) {
        co=(scc *)malloc(sizeof(scc)); /* userdata is a no-no as it
                                          will be garbage-collected */
        if (co) {
            co->L=L;
            /* lua_settop(L,3) above means we don't need: lua_pushvalue(L,3); */
            co->ref=luaL_ref(L,LUA_REGISTRYINDEX);
        }
        else luaL_error(L,"create_collation: could not allocate callback");
    }
    sqlite3_create_collation_v2(db->db, collname, SQLITE_UTF8,
        (void *)co,
        (int(*)(void*,int,const void*,int,const void*))collfunc,
        (void(*)(void*))collfree);
    return 0;
}
References collfree(), collwrapper(), sdb::db, scc::L, lsqlite_checkdb(), lua_isfunction, lua_isnil, LUA_REGISTRYINDEX, lua_settop(), luaL_checkstring, luaL_error(), luaL_ref(), malloc, NULL, scc::ref, sqlite3_create_collation_v2(), and SQLITE_UTF8.
db_create_function()
static int db_create_function (lua_State * L) static
Definition at line 1159 of file lsqlite3.c.
{
    return db_register_function(L, 0);
}
References db_register_function().
db_db_filename()
static int db_db_filename (lua_State * L) static
Definition at line 933 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    const char *db_name = luaL_checkstring(L, 2);
    // sqlite3_db_filename may return NULL, in that case Lua pushes nil...
    lua_pushstring(L, sqlite3_db_filename(db->db, db_name));
    return 1;
}
References sdb::db, lsqlite_checkdb(), lua_pushstring(), luaL_checkstring, and sqlite3_db_filename().
db_do_next_row()
static int db_do_next_row (lua_State * L, int packed) static
Definition at line 1851 of file lsqlite3.c.
{
    int result;
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm;
    int columns;
    int i;
    result = stepvm(L, svm);
    vm = svm->vm; /* stepvm may change svm->vm if re-prepare is needed */
    svm->has_values = result == SQLITE_ROW ? 1 : 0;
    svm->columns = columns = sqlite3_data_count(vm);
    if (result == SQLITE_ROW) {
        if (packed) {
            if (packed == 1) {
                lua_createtable(L, columns, 0);
                for (i = 0; i < columns;) {
                    vm_push_column(L, vm, i);
                    lua_rawseti(L, -2, ++i);
                }
            }
            else {
                lua_createtable(L, 0, columns);
                for (i = 0; i < columns; ++i) {
                    lua_pushstring(L, sqlite3_column_name(vm, i));
                    vm_push_column(L, vm, i);
                    lua_rawset(L, -3);
                }
            }
            return 1;
        }
        else {
            lua_checkstack(L, columns);
            for (i = 0; i < columns; ++i)
                vm_push_column(L, vm, i);
            return svm->columns;
        }
    }
    if (svm->temp) {
        /* finalize and check for errors */
        result = sqlite3_finalize(vm);
        svm->vm = NULL;
        cleanupvm(L, svm);
    }
    else if (result == SQLITE_DONE) {
        result = sqlite3_reset(vm);
    }
    if (result != SQLITE_OK) {
        lua_pushstring(L, sqlite3_errmsg(svm->db->db));
        lua_error(L);
    }
    return 0;
}
References cleanupvm(), sdb_vm::columns, sdb::db, sdb_vm::db, sdb_vm::has_values, lsqlite_checkvm(), lua_checkstack(), lua_createtable(), lua_error(), lua_pushstring(), lua_rawset(), lua_rawseti(), NULL, sqlite3_column_name(), sqlite3_data_count(), sqlite3_errmsg(), sqlite3_finalize(), sqlite3_reset(), SQLITE_DONE, SQLITE_OK, SQLITE_ROW, stepvm(), sdb_vm::temp, sdb_vm::vm, and vm_push_column().
Referenced by db_next_named_row(), db_next_packed_row(), and db_next_row().
db_do_rows()
static int db_do_rows (lua_State * L, int(*)(lua_State *) f) static
Definition at line 1940 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    const char *sql = luaL_checkstring(L, 2);
    sdb_vm *svm;
    lua_settop(L,2); /* db,sql is on top of stack for call to newvm */
    svm = newvm(L, db);
    svm->temp = 1;
    if (sqlite3_prepare_v2(db->db, sql, -1, &svm->vm, NULL) != SQLITE_OK) {
        lua_pushstring(L, sqlite3_errmsg(svm->db->db));
        if (cleanupvm(L, svm) == 1)
            lua_pop(L, 1); /* this should not happen since sqlite3_prepare_v2 will not set ->vm on error */
        lua_error(L);
    }
    lua_pushcfunction(L, f);
    lua_insert(L, -2);
    return 2;
}
References cleanupvm(), sdb::db, sdb_vm::db, lsqlite_checkdb(), lua_error(), lua_insert, lua_pop, lua_pushcfunction, lua_pushstring(), lua_settop(), luaL_checkstring, newvm(), NULL, sqlite3_errmsg(), sqlite3_prepare_v2(), SQLITE_OK, sdb_vm::temp, and sdb_vm::vm.
Referenced by db_nrows(), db_rows(), and db_urows().
db_errcode()
static int db_errcode (lua_State * L) static
Definition at line 915 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    lua_pushinteger(L, sqlite3_errcode(db->db));
    return 1;
}
References sdb::db, lsqlite_checkdb(), lua_pushinteger(), and sqlite3_errcode().
db_errmsg()
static int db_errmsg (lua_State * L) static
Definition at line 921 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    lua_pushstring(L, sqlite3_errmsg(db->db));
    return 1;
}
References sdb::db, lsqlite_checkdb(), lua_pushstring(), and sqlite3_errmsg().
db_exec()
static int db_exec (lua_State * L) static
Definition at line 1797 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    const char *sql = luaL_checkstring(L, 2);
    int result;
    if (!lua_isnoneornil(L, 3)) {
        /* stack:
        **  3: callback function
        **  4: userdata
        **  5: column names
        **  6: reusable column values
        */
        luaL_checktype(L, 3, LUA_TFUNCTION);
        lua_settop(L, 4);   /* 'trap' userdata - nil extra parameters */
        lua_pushnil(L);     /* column names not known at this point */
        lua_newtable(L);    /* column values table */
        result = sqlite3_exec(db->db, sql, db_exec_callback, L, NULL);
    }
    else {
        /* no callbacks */
        result = sqlite3_exec(db->db, sql, NULL, NULL, NULL);
    }
    lua_pushinteger(L, result);
    return 1;
}
References sdb::db, db_exec_callback(), lsqlite_checkdb(), lua_isnoneornil, lua_newtable, lua_pushinteger(), lua_pushnil(), lua_settop(), LUA_TFUNCTION, luaL_checkstring, luaL_checktype(), NULL, and sqlite3_exec().
db_exec_callback()
static int db_exec_callback (void * user, int columns, char ** data, char ** names) static
Definition at line 1750 of file lsqlite3.c.
{
    int result = SQLITE_ABORT; /* abort by default */
    lua_State *L = (lua_State*)user;
    int n;
    int top = lua_gettop(L);
    lua_pushvalue(L, 3); /* function to call */
    lua_pushvalue(L, 4); /* user data */
    lua_pushinteger(L, columns); /* total number of rows in result */
    /* column values */
    lua_pushvalue(L, 6);
    for (n = 0; n < columns;) {
        lua_pushstring(L, data[n++]);
        lua_rawseti(L, -2, n);
    }
    /* columns names */
    lua_pushvalue(L, 5);
    if (lua_isnil(L, -1)) {
        lua_pop(L, 1);
        lua_createtable(L, columns, 0);
        lua_pushvalue(L, -1);
        lua_replace(L, 5);
        for (n = 0; n < columns;) {
            lua_pushstring(L, names[n++]);
            lua_rawseti(L, -2, n);
        }
    }
    /* call lua function */
    if (!lua_pcall(L, 4, 1, 0)) {
#if LUA_VERSION_NUM > 502
        if (lua_isinteger(L, -1))
            result = lua_tointeger(L, -1);
        else
#endif
        if (lua_isnumber(L, -1))
            result = (int)lua_tonumber(L, -1);
    }
    lua_settop(L, top);
    return result;
}
References lua_createtable(), lua_gettop(), lua_isinteger(), lua_isnil, lua_isnumber(), lua_pcall, lua_pop, lua_pushinteger(), lua_pushstring(), lua_pushvalue(), lua_rawseti(), lua_replace, lua_settop(), lua_tointeger, lua_tonumber, and SQLITE_ABORT.
Referenced by db_exec().
db_gc()
static int db_gc (lua_State * L) static
Definition at line 2027 of file lsqlite3.c.
{
    sdb *db = lsqlite_getdb(L, 1);
    if (db->db != NULL)  /* ignore closed databases */
        cleanupdb(L, db);
    return 0;
}
References cleanupdb(), sdb::db, lsqlite_getdb(), and NULL.
db_get_ptr()
static int db_get_ptr (lua_State * L) static
Definition at line 2021 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    lua_pushlightuserdata(L, db->db);
    return 1;
}
References sdb::db, lsqlite_checkdb(), and lua_pushlightuserdata().
db_interrupt()
static int db_interrupt (lua_State * L) static
Definition at line 927 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    sqlite3_interrupt(db->db);
    return 0;
}
References sdb::db, lsqlite_checkdb(), and sqlite3_interrupt().
db_isopen()
static int db_isopen (lua_State * L) static
Definition at line 889 of file lsqlite3.c.
{
    sdb *db = lsqlite_getdb(L, 1);
    lua_pushboolean(L, db->db != NULL ? 1 : 0);
    return 1;
}
References sdb::db, lsqlite_getdb(), lua_pushboolean(), and NULL.
db_last_insert_rowid()
static int db_last_insert_rowid (lua_State * L) static
Definition at line 895 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    /* conversion warning: int64 -> luaNumber */
    sqlite_int64 rowid = sqlite3_last_insert_rowid(db->db);
    PUSH_INT64(L, rowid, lua_pushfstring(L, "%ll", rowid));
    return 1;
}
References sdb::db, lsqlite_checkdb(), lua_pushfstring(), PUSH_INT64, and sqlite3_last_insert_rowid().
db_load_extension()
static int db_load_extension (lua_State * L) static
Definition at line 1222 of file lsqlite3.c.
{
    sdb *db=lsqlite_checkdb(L,1);
    const char *extname=luaL_optstring(L,2,NULL);
    const char *entrypoint=luaL_optstring(L,3,NULL);
    int result;
    char *errmsg = NULL;
    if (extname == NULL) {
        result = sqlite3_enable_load_extension(db->db,0); /* disable extension loading */
    }
    else {
        sqlite3_enable_load_extension(db->db,1); /* enable extension loading */
        result = sqlite3_load_extension(db->db,extname,entrypoint,&errmsg);
    }
    if (result == SQLITE_OK) {
        lua_pushboolean(L,1);
        return 1;
    }
    lua_pushboolean(L,0); /* so, assert(load_extension(...)) works */
    lua_pushstring(L,errmsg);
    sqlite3_free(errmsg);
    return 2;
}
References sdb::db, lsqlite_checkdb(), lua_pushboolean(), lua_pushstring(), luaL_optstring, NULL, sqlite3_enable_load_extension(), sqlite3_free(), sqlite3_load_extension(), and SQLITE_OK.
db_next_named_row()
static int db_next_named_row (lua_State * L) static
Definition at line 1915 of file lsqlite3.c.
{
    return db_do_next_row(L, 2);
}
References db_do_next_row().
Referenced by db_nrows(), and dbvm_nrows().
db_next_packed_row()
static int db_next_packed_row (lua_State * L) static
Definition at line 1911 of file lsqlite3.c.
{
    return db_do_next_row(L, 1);
}
References db_do_next_row().
Referenced by db_rows(), and dbvm_rows().
db_next_row()
static int db_next_row (lua_State * L) static
Definition at line 1907 of file lsqlite3.c.
{
    return db_do_next_row(L, 0);
}
References db_do_next_row().
Referenced by db_urows(), and dbvm_urows().
db_nrows()
static int db_nrows (lua_State * L) static
Definition at line 1964 of file lsqlite3.c.
{
    return db_do_rows(L, db_next_named_row);
}
References db_do_rows(), and db_next_named_row().
db_prepare()
static int db_prepare (lua_State * L) static
Definition at line 1829 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    const char *sql = luaL_checkstring(L, 2);
    int sql_len = lua_strlen(L, 2);
    const char *sqltail;
    sdb_vm *svm;
    lua_settop(L,2); /* db,sql is on top of stack for call to newvm */
    svm = newvm(L, db);
    if (sqlite3_prepare_v2(db->db, sql, sql_len, &svm->vm, &sqltail) != SQLITE_OK) {
        lua_pushnil(L);
        lua_pushinteger(L, sqlite3_errcode(db->db));
        if (cleanupvm(L, svm) == 1)
            lua_pop(L, 1); /* this should not happen since sqlite3_prepare_v2 will not set ->vm on error */
        return 2;
    }
    /* vm already in the stack */
    lua_pushstring(L, sqltail);
    return 2;
}
References cleanupvm(), sdb::db, lsqlite_checkdb(), lua_pop, lua_pushinteger(), lua_pushnil(), lua_pushstring(), lua_settop(), lua_strlen, luaL_checkstring, newvm(), sqlite3_errcode(), sqlite3_prepare_v2(), SQLITE_OK, and sdb_vm::vm.
db_progress_callback()
static int db_progress_callback (void * user) static
Definition at line 1494 of file lsqlite3.c.
{
    int result = 1; /* abort by default */
    sdb *db = (sdb*)user;
    lua_State *L = db->L;
    int top = lua_gettop(L);
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->progress_cb);
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->progress_udata);
    /* call lua function */
    if (!lua_pcall(L, 1, 1, 0))
        result = lua_toboolean(L, -1);
    lua_settop(L, top);
    return result;
}
References sdb::L, lua_gettop(), lua_pcall, lua_rawgeti(), LUA_REGISTRYINDEX, lua_settop(), lua_toboolean(), sdb::progress_cb, and sdb::progress_udata.
Referenced by db_progress_handler().
db_progress_handler()
static int db_progress_handler (lua_State * L) static
Definition at line 1511 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    if (lua_gettop(L) < 2 || lua_isnil(L, 2)) {
        luaL_unref(L, LUA_REGISTRYINDEX, db->progress_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->progress_udata);
        db->progress_cb =
        db->progress_udata = LUA_NOREF;
        /* clear busy handler */
        sqlite3_progress_handler(db->db, 0, NULL, NULL);
    }
    else {
        int nop = luaL_checkint(L, 2);  /* number of opcodes */
        luaL_checktype(L, 3, LUA_TFUNCTION);
        /* make sure we have an userdata field (even if nil) */
        lua_settop(L, 4);
        luaL_unref(L, LUA_REGISTRYINDEX, db->progress_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->progress_udata);
        db->progress_udata = luaL_ref(L, LUA_REGISTRYINDEX);
        db->progress_cb = luaL_ref(L, LUA_REGISTRYINDEX);
        /* set progress callback */
        sqlite3_progress_handler(db->db, nop, db_progress_callback, db);
    }
    return 0;
}
References sdb::db, db_progress_callback(), lsqlite_checkdb(), lua_gettop(), lua_isnil, LUA_NOREF, LUA_REGISTRYINDEX, lua_settop(), LUA_TFUNCTION, luaL_checkint, luaL_checktype(), luaL_ref(), luaL_unref(), NULL, sdb::progress_cb, sdb::progress_udata, and sqlite3_progress_handler().
db_push_value()
static void db_push_value (lua_State * L, sqlite3_value * value) static
Definition at line 945 of file lsqlite3.c.
{
    switch (sqlite3_value_type(value)) {
        case SQLITE_TEXT:
            lua_pushlstring(L, (const char*)sqlite3_value_text(value), sqlite3_value_bytes(value));
            break;
        case SQLITE_INTEGER:
            PUSH_INT64(L, sqlite3_value_int64(value)
                        , lua_pushlstring(L, (const char*)sqlite3_value_text(value)
                                            , sqlite3_value_bytes(value)));
            break;
        case SQLITE_FLOAT:
            lua_pushnumber(L, sqlite3_value_double(value));
            break;
        case SQLITE_BLOB:
            lua_pushlstring(L, sqlite3_value_blob(value), sqlite3_value_bytes(value));
            break;
        case SQLITE_NULL:
            lua_pushnil(L);
            break;
        default:
            /* things done properly (SQLite + Lua SQLite)
            ** this should never happen */
            lua_pushnil(L);
            break;
    }
}
References lua_pushlstring(), lua_pushnil(), lua_pushnumber(), PUSH_INT64, sqlite3_value_blob(), sqlite3_value_bytes(), sqlite3_value_double(), sqlite3_value_int64(), sqlite3_value_text(), sqlite3_value_type(), SQLITE_BLOB, SQLITE_FLOAT, SQLITE_INTEGER, SQLITE_NULL, SQLITE_TEXT, and value.
Referenced by db_sql_normal_function().
db_register_function()
static int db_register_function (lua_State * L, int aggregate) static
Definition at line 1098 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    const char *name;
    int args;
    int result;
    sdb_func *func;
    /* safety measure */
    if (aggregate) aggregate = 1;
    name = luaL_checkstring(L, 2);
    args = luaL_checkint(L, 3);
    luaL_checktype(L, 4, LUA_TFUNCTION);
    if (aggregate) luaL_checktype(L, 5, LUA_TFUNCTION);
    /* maybe an alternative way to allocate memory should be used/avoided */
    func = (sdb_func*)malloc(sizeof(sdb_func));
    if (func == NULL) {
        luaL_error(L, "out of memory");
    }
    result = sqlite3_create_function(
        db->db, name, args, SQLITE_UTF8, func,
        aggregate ? NULL : db_sql_normal_function,
        aggregate ? db_sql_normal_function : NULL,
        aggregate ? db_sql_finalize_function : NULL
    );
    if (result == SQLITE_OK) {
        /* safety measures for userdata field to be present in the stack */
        lua_settop(L, 5 + aggregate);
        /* save registered function in db function list */
        func->db = db;
        func->aggregate = aggregate;
        func->next = db->func;
        db->func = func;
        /* save the setp/normal function callback */
        lua_pushvalue(L, 4);
        func->fn_step = luaL_ref(L, LUA_REGISTRYINDEX);
        /* save user data */
        lua_pushvalue(L, 5+aggregate);
        func->udata = luaL_ref(L, LUA_REGISTRYINDEX);
        if (aggregate) {
            lua_pushvalue(L, 5);
            func->fn_finalize = luaL_ref(L, LUA_REGISTRYINDEX);
        }
        else
            func->fn_finalize = LUA_NOREF;
    }
    else {
        /* free allocated memory */
        free(func);
    }
    lua_pushboolean(L, result == SQLITE_OK ? 1 : 0);
    return 1;
}
References sdb_func::aggregate, sdb_func::db, sdb::db, db_sql_finalize_function(), db_sql_normal_function(), sdb_func::fn_finalize, sdb_func::fn_step, free, sdb::func, lsqlite_checkdb(), LUA_NOREF, lua_pushboolean(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_settop(), LUA_TFUNCTION, luaL_checkint, luaL_checkstring, luaL_checktype(), luaL_error(), luaL_ref(), malloc, name, sdb_func::next, NULL, sqlite3_create_function(), SQLITE_OK, SQLITE_UTF8, and sdb_func::udata.
Referenced by db_create_aggregate(), and db_create_function().
db_rollback_hook()
static int db_rollback_hook (lua_State * L) static
Definition at line 1450 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    if (lua_gettop(L) < 2 || lua_isnil(L, 2)) {
        luaL_unref(L, LUA_REGISTRYINDEX, db->rollback_hook_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->rollback_hook_udata);
        db->rollback_hook_cb =
        db->rollback_hook_udata = LUA_NOREF;
        /* clear rollback_hook handler */
        sqlite3_rollback_hook(db->db, NULL, NULL);
    }
    else {
        luaL_checktype(L, 2, LUA_TFUNCTION);
        /* make sure we have an userdata field (even if nil) */
        lua_settop(L, 3);
        luaL_unref(L, LUA_REGISTRYINDEX, db->rollback_hook_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->rollback_hook_udata);
        db->rollback_hook_udata = luaL_ref(L, LUA_REGISTRYINDEX);
        db->rollback_hook_cb = luaL_ref(L, LUA_REGISTRYINDEX);
        /* set rollback_hook handler */
        sqlite3_rollback_hook(db->db, db_rollback_hook_callback, db);
    }
    return 0;
}
References sdb::db, db_rollback_hook_callback(), lsqlite_checkdb(), lua_gettop(), lua_isnil, LUA_NOREF, LUA_REGISTRYINDEX, lua_settop(), LUA_TFUNCTION, luaL_checktype(), luaL_ref(), luaL_unref(), NULL, sdb::rollback_hook_cb, sdb::rollback_hook_udata, and sqlite3_rollback_hook().
db_rollback_hook_callback()
static void db_rollback_hook_callback (void * user) static
Definition at line 1434 of file lsqlite3.c.
{
    sdb *db = (sdb*)user;
    lua_State *L = db->L;
    int top = lua_gettop(L);
    /* setup lua callback call */
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->rollback_hook_cb);    /* get callback */
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->rollback_hook_udata); /* get callback user data */
    /* call lua function */
    lua_pcall(L, 1, 0, 0);
    /* ignore any error generated by this function */
    lua_settop(L, top);
}
References sdb::L, lua_gettop(), lua_pcall, lua_rawgeti(), LUA_REGISTRYINDEX, lua_settop(), sdb::rollback_hook_cb, and sdb::rollback_hook_udata.
Referenced by db_rollback_hook().
db_rows()
static int db_rows (lua_State * L) static
Definition at line 1960 of file lsqlite3.c.
{
    return db_do_rows(L, db_next_packed_row);
}
References db_do_rows(), and db_next_packed_row().
db_sql_finalize_function()
static void db_sql_finalize_function (sqlite3_context * context) static
Definition at line 1042 of file lsqlite3.c.
{
    sdb_func *func = (sdb_func*)sqlite3_user_data(context);
    lua_State *L = func->db->L;
    void *p = sqlite3_aggregate_context(context, 1); /* minimal mem usage */
    lcontext *ctx;
    int top = lua_gettop(L);
    lua_rawgeti(L, LUA_REGISTRYINDEX, func->fn_finalize);   /* function to call */
    /* i think it is OK to use assume that using a light user data
    ** as an entry on LUA REGISTRY table will be unique */
    lua_pushlightuserdata(L, p);
    lua_rawget(L, LUA_REGISTRYINDEX);       /* context table */
    if (lua_isnil(L, -1)) { /* not yet created? - shouldn't happen in finalize function */
        lua_pop(L, 1);
        ctx = lsqlite_make_context(L);
        lua_pushlightuserdata(L, p);
        lua_pushvalue(L, -2);
        lua_rawset(L, LUA_REGISTRYINDEX);
    }
    else
        ctx = lsqlite_getcontext(L, -1);
    /* set context */
    ctx->ctx = context;
    if (lua_pcall(L, 1, 0, 0)) {
        sqlite3_result_error(context, lua_tostring(L, -1), -1);
    }
    /* invalidate context */
    ctx->ctx = NULL;
    /* cleanup context */
    luaL_unref(L, LUA_REGISTRYINDEX, ctx->ud);
    /* remove it from registry */
    lua_pushlightuserdata(L, p);
    lua_pushnil(L);
    lua_rawset(L, LUA_REGISTRYINDEX);
    lua_settop(L, top);
}
References lcontext::ctx, sdb_func::db, sdb_func::fn_finalize, sdb::L, lsqlite_getcontext(), lsqlite_make_context(), lua_gettop(), lua_isnil, lua_pcall, lua_pop, lua_pushlightuserdata(), lua_pushnil(), lua_pushvalue(), lua_rawget(), lua_rawgeti(), lua_rawset(), LUA_REGISTRYINDEX, lua_settop(), lua_tostring, luaL_unref(), NULL, sqlite3_aggregate_context(), sqlite3_result_error(), sqlite3_user_data(), and lcontext::ud.
Referenced by db_register_function().
db_sql_normal_function()
static void db_sql_normal_function (sqlite3_context * context, int argc, sqlite3_value ** argv) static
Definition at line 983 of file lsqlite3.c.
{
    sdb_func *func = (sdb_func*)sqlite3_user_data(context);
    lua_State *L = func->db->L;
    int n;
    lcontext *ctx;
    int top = lua_gettop(L);
    /* ensure there is enough space in the stack */
    lua_checkstack(L, argc + 3);
    lua_rawgeti(L, LUA_REGISTRYINDEX, func->fn_step);   /* function to call */
    if (!func->aggregate) {
        ctx = lsqlite_make_context(L); /* push context - used to set results */
    }
    else {
        /* reuse context userdata value */
        void *p = sqlite3_aggregate_context(context, 1);
        /* i think it is OK to use assume that using a light user data
        ** as an entry on LUA REGISTRY table will be unique */
        lua_pushlightuserdata(L, p);
        lua_rawget(L, LUA_REGISTRYINDEX);       /* context table */
        if (lua_isnil(L, -1)) { /* not yet created? */
            lua_pop(L, 1);
            ctx = lsqlite_make_context(L);
            lua_pushlightuserdata(L, p);
            lua_pushvalue(L, -2);
            lua_rawset(L, LUA_REGISTRYINDEX);
        }
        else
            ctx = lsqlite_getcontext(L, -1);
    }
    /* push params */
    for (n = 0; n < argc; ++n) {
        db_push_value(L, argv[n]);
    }
    /* set context */
    ctx->ctx = context;
    if (lua_pcall(L, argc + 1, 0, 0)) {
        const char *errmsg = lua_tostring(L, -1);
        int size = lua_strlen(L, -1);
        sqlite3_result_error(context, errmsg, size);
    }
    /* invalidate context */
    ctx->ctx = NULL;
    if (!func->aggregate) {
        luaL_unref(L, LUA_REGISTRYINDEX, ctx->ud);
    }
    lua_settop(L, top);
}
References sdb_func::aggregate, lcontext::ctx, sdb_func::db, db_push_value(), sdb_func::fn_step, sdb::L, lsqlite_getcontext(), lsqlite_make_context(), lua_checkstack(), lua_gettop(), lua_isnil, lua_pcall, lua_pop, lua_pushlightuserdata(), lua_pushvalue(), lua_rawget(), lua_rawgeti(), lua_rawset(), LUA_REGISTRYINDEX, lua_settop(), lua_strlen, lua_tostring, luaL_unref(), NULL, sqlite3_aggregate_context(), sqlite3_result_error(), sqlite3_user_data(), and lcontext::ud.
Referenced by db_register_function().
db_tostring()
static int db_tostring (lua_State * L) static
Definition at line 1973 of file lsqlite3.c.
{
    char buff[32];
    sdb *db = lsqlite_getdb(L, 1);
    if (db->db == NULL)
        strcpy(buff, "closed");
    else
        sprintf(buff, "%p", lua_touserdata(L, 1));
    lua_pushfstring(L, "sqlite database (%s)", buff);
    return 1;
}
References sdb::db, lsqlite_getdb(), lua_pushfstring(), lua_touserdata(), and NULL.
db_total_changes()
static int db_total_changes (lua_State * L) static
Definition at line 909 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    lua_pushinteger(L, sqlite3_total_changes(db->db));
    return 1;
}
References sdb::db, lsqlite_checkdb(), lua_pushinteger(), and sqlite3_total_changes().
db_trace()
static int db_trace (lua_State * L) static
Definition at line 1272 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    if (lua_gettop(L) < 2 || lua_isnil(L, 2)) {
        luaL_unref(L, LUA_REGISTRYINDEX, db->trace_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->trace_udata);
        db->trace_cb =
        db->trace_udata = LUA_NOREF;
        /* clear trace handler */
        sqlite3_trace(db->db, NULL, NULL);
    }
    else {
        luaL_checktype(L, 2, LUA_TFUNCTION);
        /* make sure we have an userdata field (even if nil) */
        lua_settop(L, 3);
        luaL_unref(L, LUA_REGISTRYINDEX, db->trace_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->trace_udata);
        db->trace_udata = luaL_ref(L, LUA_REGISTRYINDEX);
        db->trace_cb = luaL_ref(L, LUA_REGISTRYINDEX);
        /* set trace handler */
        sqlite3_trace(db->db, db_trace_callback, db);
    }
    return 0;
}
References sdb::db, db_trace_callback(), lsqlite_checkdb(), lua_gettop(), lua_isnil, LUA_NOREF, LUA_REGISTRYINDEX, lua_settop(), LUA_TFUNCTION, luaL_checktype(), luaL_ref(), luaL_unref(), NULL, sqlite3_trace(), sdb::trace_cb, and sdb::trace_udata.
db_trace_callback()
static void db_trace_callback (void * user, const char * sql) static
Definition at line 1255 of file lsqlite3.c.
{
    sdb *db = (sdb*)user;
    lua_State *L = db->L;
    int top = lua_gettop(L);
    /* setup lua callback call */
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->trace_cb);    /* get callback */
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->trace_udata); /* get callback user data */
    lua_pushstring(L, sql); /* traced sql statement */
    /* call lua function */
    lua_pcall(L, 2, 0, 0);
    /* ignore any error generated by this function */
    lua_settop(L, top);
}
References sdb::L, lua_gettop(), lua_pcall, lua_pushstring(), lua_rawgeti(), LUA_REGISTRYINDEX, lua_settop(), sdb::trace_cb, and sdb::trace_udata.
Referenced by db_trace().
db_update_hook()
static int db_update_hook (lua_State * L) static
Definition at line 1336 of file lsqlite3.c.
{
    sdb *db = lsqlite_checkdb(L, 1);
    if (lua_gettop(L) < 2 || lua_isnil(L, 2)) {
        luaL_unref(L, LUA_REGISTRYINDEX, db->update_hook_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->update_hook_udata);
        db->update_hook_cb =
        db->update_hook_udata = LUA_NOREF;
        /* clear update_hook handler */
        sqlite3_update_hook(db->db, NULL, NULL);
    }
    else {
        luaL_checktype(L, 2, LUA_TFUNCTION);
        /* make sure we have an userdata field (even if nil) */
        lua_settop(L, 3);
        luaL_unref(L, LUA_REGISTRYINDEX, db->update_hook_cb);
        luaL_unref(L, LUA_REGISTRYINDEX, db->update_hook_udata);
        db->update_hook_udata = luaL_ref(L, LUA_REGISTRYINDEX);
        db->update_hook_cb = luaL_ref(L, LUA_REGISTRYINDEX);
        /* set update_hook handler */
        sqlite3_update_hook(db->db, db_update_hook_callback, db);
    }
    return 0;
}
References sdb::db, db_update_hook_callback(), lsqlite_checkdb(), lua_gettop(), lua_isnil, LUA_NOREF, LUA_REGISTRYINDEX, lua_settop(), LUA_TFUNCTION, luaL_checktype(), luaL_ref(), luaL_unref(), NULL, sqlite3_update_hook(), sdb::update_hook_cb, and sdb::update_hook_udata.
db_update_hook_callback()
static void db_update_hook_callback (void * user, int op, char const * dbname, char const * tblname, sqlite3_int64 rowid) static
Definition at line 1314 of file lsqlite3.c.
{
    sdb *db = (sdb*)user;
    lua_State *L = db->L;
    int top = lua_gettop(L);
    lua_Number n;
    /* setup lua callback call */
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->update_hook_cb);    /* get callback */
    lua_rawgeti(L, LUA_REGISTRYINDEX, db->update_hook_udata); /* get callback user data */
    lua_pushinteger(L, op);
    lua_pushstring(L, dbname); /* update_hook database name */
    lua_pushstring(L, tblname); /* update_hook database name */
    PUSH_INT64(L, rowid, lua_pushfstring(L, "%ll", rowid));
    /* call lua function */
    lua_pcall(L, 5, 0, 0);
    /* ignore any error generated by this function */
    lua_settop(L, top);
}
References sdb::L, lua_gettop(), lua_pcall, lua_pushfstring(), lua_pushinteger(), lua_pushstring(), lua_rawgeti(), LUA_REGISTRYINDEX, lua_settop(), PUSH_INT64, sdb::update_hook_cb, and sdb::update_hook_udata.
Referenced by db_update_hook().
db_urows()
static int db_urows (lua_State * L) static
Definition at line 1969 of file lsqlite3.c.
{
    return db_do_rows(L, db_next_row);
}
References db_do_rows(), and db_next_row().
dbbu_finish()
static int dbbu_finish (lua_State * L) static
Definition at line 1663 of file lsqlite3.c.
{
    sdb_bu *sbu = lsqlite_checkbu(L, 1);
    return cleanupbu(L, sbu);
}
References cleanupbu(), and lsqlite_checkbu().
dbbu_gc()
static int dbbu_gc (lua_State * L) static
Definition at line 1634 of file lsqlite3.c.
{
    sdb_bu *sbu = lsqlite_getbu(L, 1);
    if (sbu->bu != NULL) {
        cleanupbu(L, sbu);
        lua_pop(L, 1);
    }
    /* else ignore if already finished */
    return 0;
}
References sdb_bu::bu, cleanupbu(), lsqlite_getbu(), lua_pop, and NULL.
dbbu_pagecount()
static int dbbu_pagecount (lua_State * L) static
Definition at line 1657 of file lsqlite3.c.
{
    sdb_bu *sbu = lsqlite_checkbu(L, 1);
    lua_pushinteger(L, sqlite3_backup_pagecount(sbu->bu));
    return 1;
}
References sdb_bu::bu, lsqlite_checkbu(), lua_pushinteger(), and sqlite3_backup_pagecount().
dbbu_remaining()
static int dbbu_remaining (lua_State * L) static
Definition at line 1651 of file lsqlite3.c.
{
    sdb_bu *sbu = lsqlite_checkbu(L, 1);
    lua_pushinteger(L, sqlite3_backup_remaining(sbu->bu));
    return 1;
}
References sdb_bu::bu, lsqlite_checkbu(), lua_pushinteger(), and sqlite3_backup_remaining().
dbbu_step()
static int dbbu_step (lua_State * L) static
Definition at line 1644 of file lsqlite3.c.
{
    sdb_bu *sbu = lsqlite_checkbu(L, 1);
    int nPage = luaL_checkint(L, 2);
    lua_pushinteger(L, sqlite3_backup_step(sbu->bu, nPage));
    return 1;
}
References sdb_bu::bu, lsqlite_checkbu(), lua_pushinteger(), luaL_checkint, and sqlite3_backup_step().
dbvm_bind()
static int dbvm_bind (lua_State * L) static
Definition at line 528 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int index = luaL_checkint(L, 2);
    int result;
    dbvm_check_bind_index(L, svm, index);
    result = dbvm_bind_index(L, vm, index, 3);
    lua_pushinteger(L, result);
    return 1;
}
References dbvm_bind_index(), dbvm_check_bind_index(), index, lsqlite_checkvm(), lua_pushinteger(), luaL_checkint, and sdb_vm::vm.
dbvm_bind_blob()
static int dbvm_bind_blob (lua_State * L) static
Definition at line 541 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    int index = luaL_checkint(L, 2);
    const char *value = luaL_checkstring(L, 3);
    int len = lua_strlen(L, 3);
    lua_pushinteger(L, sqlite3_bind_blob(svm->vm, index, value, len, SQLITE_TRANSIENT));
    return 1;
}
References index, lsqlite_checkvm(), lua_pushinteger(), lua_strlen, luaL_checkint, luaL_checkstring, sqlite3_bind_blob(), SQLITE_TRANSIENT, value, and sdb_vm::vm.
dbvm_bind_index()
static int dbvm_bind_index (lua_State * L, sqlite3_stmt * vm, int index, int lindex) static
Definition at line 492 of file lsqlite3.c.
{
    switch (lua_type(L, lindex)) {
        case LUA_TSTRING:
            return sqlite3_bind_text(vm, index, lua_tostring(L, lindex), lua_strlen(L, lindex), SQLITE_TRANSIENT);
        case LUA_TNUMBER:
#if LUA_VERSION_NUM > 502
            if (lua_isinteger(L, lindex))
                return sqlite3_bind_int64(vm, index, lua_tointeger(L, lindex));
#endif
            return sqlite3_bind_double(vm, index, lua_tonumber(L, lindex));
        case LUA_TBOOLEAN:
            return sqlite3_bind_int(vm, index, lua_toboolean(L, lindex) ? 1 : 0);
        case LUA_TNONE:
        case LUA_TNIL:
            return sqlite3_bind_null(vm, index);
        default:
            luaL_error(L, "index (%d) - invalid data type for bind (%s)", index, lua_typename(L, lua_type(L, lindex)));
            return SQLITE_MISUSE; /*!*/
    }
}
References index, lua_isinteger(), lua_strlen, LUA_TBOOLEAN, LUA_TNIL, LUA_TNONE, LUA_TNUMBER, lua_toboolean(), lua_tointeger, lua_tonumber, lua_tostring, LUA_TSTRING, lua_type(), lua_typename(), luaL_error(), sqlite3_bind_double(), sqlite3_bind_int(), sqlite3_bind_int64(), sqlite3_bind_null(), sqlite3_bind_text(), SQLITE_MISUSE, and SQLITE_TRANSIENT.
Referenced by dbvm_bind(), dbvm_bind_names(), and dbvm_bind_values().
dbvm_bind_names()
static int dbvm_bind_names (lua_State * L) static
Definition at line 575 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int count = sqlite3_bind_parameter_count(vm);
    const char *name;
    int result, n;
    luaL_checktype(L, 2, LUA_TTABLE);
    for (n = 1; n <= count; ++n) {
        name = sqlite3_bind_parameter_name(vm, n);
        if (name && (name[0] == ':' || name[0] == '$')) {
            lua_pushstring(L, ++name);
            lua_gettable(L, 2);
            result = dbvm_bind_index(L, vm, n, -1);
            lua_pop(L, 1);
        }
        else {
            lua_pushinteger(L, n);
            lua_gettable(L, 2);
            result = dbvm_bind_index(L, vm, n, -1);
            lua_pop(L, 1);
        }
        if (result != SQLITE_OK) {
            lua_pushinteger(L, result);
            return 1;
        }
    }
    lua_pushinteger(L, SQLITE_OK);
    return 1;
}
References dbvm_bind_index(), lsqlite_checkvm(), lua_gettable(), lua_pop, lua_pushinteger(), lua_pushstring(), LUA_TTABLE, luaL_checktype(), name, sqlite3_bind_parameter_count(), sqlite3_bind_parameter_name(), SQLITE_OK, and sdb_vm::vm.
dbvm_bind_parameter_count()
static int dbvm_bind_parameter_count (lua_State * L) static
Definition at line 514 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    lua_pushinteger(L, sqlite3_bind_parameter_count(svm->vm));
    return 1;
}
References lsqlite_checkvm(), lua_pushinteger(), sqlite3_bind_parameter_count(), and sdb_vm::vm.
dbvm_bind_parameter_name()
static int dbvm_bind_parameter_name (lua_State * L) static
Definition at line 520 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    int index = luaL_checknumber(L, 2);
    dbvm_check_bind_index(L, svm, index);
    lua_pushstring(L, sqlite3_bind_parameter_name(svm->vm, index));
    return 1;
}
References dbvm_check_bind_index(), index, lsqlite_checkvm(), lua_pushstring(), luaL_checknumber(), sqlite3_bind_parameter_name(), and sdb_vm::vm.
dbvm_bind_values()
static int dbvm_bind_values (lua_State * L) static
Definition at line 551 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int top = lua_gettop(L);
    int result, n;
    if (top - 1 != sqlite3_bind_parameter_count(vm))
        luaL_error(L,
            "incorrect number of parameters to bind (%d given, %d to bind)",
            top - 1,
            sqlite3_bind_parameter_count(vm)
        );
    for (n = 2; n <= top; ++n) {
        if ((result = dbvm_bind_index(L, vm, n - 1, n)) != SQLITE_OK) {
            lua_pushinteger(L, result);
            return 1;
        }
    }
    lua_pushinteger(L, SQLITE_OK);
    return 1;
}
References dbvm_bind_index(), lsqlite_checkvm(), lua_gettop(), lua_pushinteger(), luaL_error(), sqlite3_bind_parameter_count(), SQLITE_OK, and sdb_vm::vm.
dbvm_check_bind_index()
static void dbvm_check_bind_index (lua_State * L, sdb_vm * svm, int index) static
Definition at line 319 of file lsqlite3.c.
{
    if (index < 1 || index > sqlite3_bind_parameter_count(svm->vm)) {
        luaL_error(L, "bind index out of range [1..%d]", sqlite3_bind_parameter_count(svm->vm));
    }
}
References luaL_error(), sqlite3_bind_parameter_count(), and sdb_vm::vm.
Referenced by dbvm_bind(), and dbvm_bind_parameter_name().
dbvm_check_contents()
static void dbvm_check_contents (lua_State * L, sdb_vm * svm) static
Definition at line 307 of file lsqlite3.c.
{
    if (!svm->has_values) {
        luaL_error(L, "misuse of function");
    }
}
References sdb_vm::has_values, and luaL_error().
Referenced by dbvm_get_named_values(), dbvm_get_uvalues(), dbvm_get_value(), and dbvm_get_values().
dbvm_check_index()
static void dbvm_check_index (lua_State * L, sdb_vm * svm, int index) static
Definition at line 313 of file lsqlite3.c.
{
    if (index < 0 || index >= svm->columns) {
        luaL_error(L, "index out of range [0..%d]", svm->columns - 1);
    }
}
References sdb_vm::columns, and luaL_error().
Referenced by dbvm_get_name(), dbvm_get_type(), and dbvm_get_value().
dbvm_columns()
static int dbvm_columns (lua_State * L) static
Definition at line 338 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    lua_pushinteger(L, sqlite3_column_count(svm->vm));
    return 1;
}
References lsqlite_checkvm(), lua_pushinteger(), sqlite3_column_count(), and sdb_vm::vm.
dbvm_do_rows()
static int dbvm_do_rows (lua_State * L, int(*)(lua_State *) f) static
Definition at line 1919 of file lsqlite3.c.
{
    /* sdb_vm *svm =  */
    lsqlite_checkvm(L, 1);
    lua_pushvalue(L,1);
    lua_pushcfunction(L, f);
    lua_insert(L, -2);
    return 2;
}
References lsqlite_checkvm(), lua_insert, lua_pushcfunction, and lua_pushvalue().
Referenced by dbvm_nrows(), dbvm_rows(), and dbvm_urows().
dbvm_finalize()
static int dbvm_finalize (lua_State * L) static
Definition at line 295 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    return cleanupvm(L, svm);
}
References cleanupvm(), and lsqlite_checkvm().
dbvm_gc()
static int dbvm_gc (lua_State * L) static
Definition at line 276 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_getvm(L, 1);
    if (svm->vm != NULL)  /* ignore closed vms */
        cleanupvm(L, svm);
    return 0;
}
References cleanupvm(), lsqlite_getvm(), NULL, and sdb_vm::vm.
dbvm_get_name()
static int dbvm_get_name (lua_State * L) static
Definition at line 359 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    int index = luaL_checknumber(L, 2);
    dbvm_check_index(L, svm, index);
    lua_pushstring(L, sqlite3_column_name(svm->vm, index));
    return 1;
}
References dbvm_check_index(), index, lsqlite_checkvm(), lua_pushstring(), luaL_checknumber(), sqlite3_column_name(), and sdb_vm::vm.
dbvm_get_named_types()
static int dbvm_get_named_types (lua_State * L) static
Definition at line 471 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int columns = sqlite3_column_count(vm);
    int n;
    lua_createtable(L, 0, columns);
    for (n = 0; n < columns; ++n) {
        lua_pushstring(L, sqlite3_column_name(vm, n));
        lua_pushstring(L, sqlite3_column_decltype(vm, n));
        lua_rawset(L, -3);
    }
    return 1;
}
References lsqlite_checkvm(), lua_createtable(), lua_pushstring(), lua_rawset(), sqlite3_column_count(), sqlite3_column_decltype(), sqlite3_column_name(), and sdb_vm::vm.
dbvm_get_named_values()
static int dbvm_get_named_values (lua_State * L) static
Definition at line 455 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int columns = svm->columns;
    int n;
    dbvm_check_contents(L, svm);
    lua_createtable(L, 0, columns);
    for (n = 0; n < columns; ++n) {
        lua_pushstring(L, sqlite3_column_name(vm, n));
        vm_push_column(L, vm, n);
        lua_rawset(L, -3);
    }
    return 1;
}
References sdb_vm::columns, dbvm_check_contents(), lsqlite_checkvm(), lua_createtable(), lua_pushstring(), lua_rawset(), sqlite3_column_name(), sdb_vm::vm, and vm_push_column().
dbvm_get_names()
static int dbvm_get_names (lua_State * L) static
Definition at line 390 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int columns = sqlite3_column_count(vm); /* valid as soon as statement prepared */
    int n;
    lua_createtable(L, columns, 0);
    for (n = 0; n < columns;) {
        lua_pushstring(L, sqlite3_column_name(vm, n++));
        lua_rawseti(L, -2, n);
    }
    return 1;
}
References lsqlite_checkvm(), lua_createtable(), lua_pushstring(), lua_rawseti(), sqlite3_column_count(), sqlite3_column_name(), and sdb_vm::vm.
dbvm_get_type()
static int dbvm_get_type (lua_State * L) static
Definition at line 367 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    int index = luaL_checknumber(L, 2);
    dbvm_check_index(L, svm, index);
    lua_pushstring(L, sqlite3_column_decltype(svm->vm, index));
    return 1;
}
References dbvm_check_index(), index, lsqlite_checkvm(), lua_pushstring(), luaL_checknumber(), sqlite3_column_decltype(), and sdb_vm::vm.
dbvm_get_types()
static int dbvm_get_types (lua_State * L) static
Definition at line 404 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int columns = sqlite3_column_count(vm); /* valid as soon as statement prepared */
    int n;
    lua_createtable(L, columns, 0);
    for (n = 0; n < columns;) {
        lua_pushstring(L, sqlite3_column_decltype(vm, n++));
        lua_rawseti(L, -2, n);
    }
    return 1;
}
References lsqlite_checkvm(), lua_createtable(), lua_pushstring(), lua_rawseti(), sqlite3_column_count(), sqlite3_column_decltype(), and sdb_vm::vm.
dbvm_get_unames()
static int dbvm_get_unames (lua_State * L) static
Definition at line 431 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int columns = sqlite3_column_count(vm); /* valid as soon as statement prepared */
    int n;
    lua_checkstack(L, columns);
    for (n = 0; n < columns; ++n)
        lua_pushstring(L, sqlite3_column_name(vm, n));
    return columns;
}
References lsqlite_checkvm(), lua_checkstack(), lua_pushstring(), sqlite3_column_count(), sqlite3_column_name(), and sdb_vm::vm.
dbvm_get_utypes()
static int dbvm_get_utypes (lua_State * L) static
Definition at line 443 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int columns = sqlite3_column_count(vm); /* valid as soon as statement prepared */
    int n;
    lua_checkstack(L, columns);
    for (n = 0; n < columns; ++n)
        lua_pushstring(L, sqlite3_column_decltype(vm, n));
    return columns;
}
References lsqlite_checkvm(), lua_checkstack(), lua_pushstring(), sqlite3_column_count(), sqlite3_column_decltype(), and sdb_vm::vm.
dbvm_get_uvalues()
static int dbvm_get_uvalues (lua_State * L) static
Definition at line 418 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int columns = svm->columns;
    int n;
    dbvm_check_contents(L, svm);
    lua_checkstack(L, columns);
    for (n = 0; n < columns; ++n)
        vm_push_column(L, vm, n);
    return columns;
}
References sdb_vm::columns, dbvm_check_contents(), lsqlite_checkvm(), lua_checkstack(), sdb_vm::vm, and vm_push_column().
dbvm_get_value()
static int dbvm_get_value (lua_State * L) static
Definition at line 350 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    int index = luaL_checkint(L, 2);
    dbvm_check_contents(L, svm);
    dbvm_check_index(L, svm, index);
    vm_push_column(L, svm->vm, index);
    return 1;
}
References dbvm_check_contents(), dbvm_check_index(), index, lsqlite_checkvm(), luaL_checkint, sdb_vm::vm, and vm_push_column().
dbvm_get_values()
static int dbvm_get_values (lua_State * L) static
Definition at line 375 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_stmt *vm = svm->vm;
    int columns = svm->columns;
    int n;
    dbvm_check_contents(L, svm);
    lua_createtable(L, columns, 0);
    for (n = 0; n < columns;) {
        vm_push_column(L, vm, n++);
        lua_rawseti(L, -2, n);
    }
    return 1;
}
References sdb_vm::columns, dbvm_check_contents(), lsqlite_checkvm(), lua_createtable(), lua_rawseti(), sdb_vm::vm, and vm_push_column().
dbvm_isopen()
static int dbvm_isopen (lua_State * L) static
Definition at line 259 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_getvm(L, 1);
    lua_pushboolean(L, svm->vm != NULL ? 1 : 0);
    return 1;
}
References lsqlite_getvm(), lua_pushboolean(), NULL, and sdb_vm::vm.
dbvm_last_insert_rowid()
static int dbvm_last_insert_rowid (lua_State * L) static
Definition at line 325 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    /* conversion warning: int64 -> luaNumber */
    sqlite_int64 rowid = sqlite3_last_insert_rowid(svm->db->db);
    PUSH_INT64(L, rowid, lua_pushfstring(L, "%ll", rowid));
    return 1;
}
References sdb::db, sdb_vm::db, lsqlite_checkvm(), lua_pushfstring(), PUSH_INT64, and sqlite3_last_insert_rowid().
dbvm_nrows()
static int dbvm_nrows (lua_State * L) static
Definition at line 1932 of file lsqlite3.c.
{
    return dbvm_do_rows(L, db_next_named_row);
}
References db_next_named_row(), and dbvm_do_rows().
dbvm_reset()
static int dbvm_reset (lua_State * L) static
Definition at line 300 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    sqlite3_reset(svm->vm);
    lua_pushinteger(L, sqlite3_errcode(svm->db->db));
    return 1;
}
References sdb::db, sdb_vm::db, lsqlite_checkvm(), lua_pushinteger(), sqlite3_errcode(), sqlite3_reset(), and sdb_vm::vm.
dbvm_rows()
static int dbvm_rows (lua_State * L) static
Definition at line 1928 of file lsqlite3.c.
{
    return dbvm_do_rows(L, db_next_packed_row);
}
References db_next_packed_row(), and dbvm_do_rows().
dbvm_step()
static int dbvm_step (lua_State * L) static
Definition at line 283 of file lsqlite3.c.
{
    int result;
    sdb_vm *svm = lsqlite_checkvm(L, 1);
    result = stepvm(L, svm);
    svm->has_values = result == SQLITE_ROW ? 1 : 0;
    svm->columns = sqlite3_data_count(svm->vm);
    lua_pushinteger(L, result);
    return 1;
}
References sdb_vm::columns, sdb_vm::has_values, lsqlite_checkvm(), lua_pushinteger(), sqlite3_data_count(), SQLITE_ROW, stepvm(), and sdb_vm::vm.
dbvm_tostring()
static int dbvm_tostring (lua_State * L) static
Definition at line 265 of file lsqlite3.c.
{
    char buff[39];
    sdb_vm *svm = lsqlite_getvm(L, 1);
    if (svm->vm == NULL)
        strcpy(buff, "closed");
    else
        sprintf(buff, "%p", svm);
    lua_pushfstring(L, "sqlite virtual machine (%s)", buff);
    return 1;
}
References lsqlite_getvm(), lua_pushfstring(), NULL, and sdb_vm::vm.
dbvm_urows()
static int dbvm_urows (lua_State * L) static
Definition at line 1936 of file lsqlite3.c.
{
    return dbvm_do_rows(L, db_next_row);
}
References db_next_row(), and dbvm_do_rows().
lcontext_aggregate_count()
static int lcontext_aggregate_count (lua_State * L) static
Definition at line 801 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    lcontext_check_aggregate(L, ctx);
    lua_pushinteger(L, sqlite3_aggregate_count(ctx->ctx));
    return 1;
}
References lcontext::ctx, lcontext_check_aggregate(), lsqlite_checkcontext(), lua_pushinteger(), and sqlite3_aggregate_count().
lcontext_check_aggregate()
static void lcontext_check_aggregate (lua_State * L, lcontext * ctx) static
Definition at line 771 of file lsqlite3.c.
{
    sdb_func *func = (sdb_func*)sqlite3_user_data(ctx->ctx);
    if (!func->aggregate) {
        luaL_error(L, "attempt to call aggregate method from scalar function");
    }
}
References sdb_func::aggregate, lcontext::ctx, luaL_error(), and sqlite3_user_data().
Referenced by lcontext_aggregate_count(), lcontext_get_aggregate_context(), and lcontext_set_aggregate_context().
lcontext_get_aggregate_context()
static int lcontext_get_aggregate_context (lua_State * L) static
Definition at line 785 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    lcontext_check_aggregate(L, ctx);
    lua_rawgeti(L, LUA_REGISTRYINDEX, ctx->ud);
    return 1;
}
References lcontext_check_aggregate(), lsqlite_checkcontext(), lua_rawgeti(), LUA_REGISTRYINDEX, and lcontext::ud.
lcontext_result()
static int lcontext_result (lua_State * L) static
Definition at line 813 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    switch (lua_type(L, 2)) {
        case LUA_TNUMBER:
#if LUA_VERSION_NUM > 502
            if (lua_isinteger(L, 2))
                sqlite3_result_int64(ctx->ctx, luaL_checkinteger(L, 2));
            else
#endif
            sqlite3_result_double(ctx->ctx, luaL_checknumber(L, 2));
            break;
        case LUA_TSTRING:
            sqlite3_result_text(ctx->ctx, luaL_checkstring(L, 2), lua_strlen(L, 2), SQLITE_TRANSIENT);
            break;
        case LUA_TNIL:
        case LUA_TNONE:
            sqlite3_result_null(ctx->ctx);
            break;
        default:
            luaL_error(L, "invalid result type %s", lua_typename(L, 2));
            break;
    }
    return 0;
}
References lcontext::ctx, lsqlite_checkcontext(), lua_isinteger(), lua_strlen, LUA_TNIL, LUA_TNONE, LUA_TNUMBER, LUA_TSTRING, lua_type(), lua_typename(), luaL_checkinteger(), luaL_checknumber(), luaL_checkstring, luaL_error(), sqlite3_result_double(), sqlite3_result_int64(), sqlite3_result_null(), sqlite3_result_text(), and SQLITE_TRANSIENT.
lcontext_result_blob()
static int lcontext_result_blob (lua_State * L) static
Definition at line 839 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    const char *blob = luaL_checkstring(L, 2);
    int size = lua_strlen(L, 2);
    sqlite3_result_blob(ctx->ctx, (const void*)blob, size, SQLITE_TRANSIENT);
    return 0;
}
References lcontext::ctx, lsqlite_checkcontext(), lua_strlen, luaL_checkstring, sqlite3_result_blob(), and SQLITE_TRANSIENT.
lcontext_result_double()
static int lcontext_result_double (lua_State * L) static
Definition at line 847 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    double d = luaL_checknumber(L, 2);
    sqlite3_result_double(ctx->ctx, d);
    return 0;
}
References lcontext::ctx, lsqlite_checkcontext(), luaL_checknumber(), and sqlite3_result_double().
lcontext_result_error()
static int lcontext_result_error (lua_State * L) static
Definition at line 854 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    const char *err = luaL_checkstring(L, 2);
    int size = lua_strlen(L, 2);
    sqlite3_result_error(ctx->ctx, err, size);
    return 0;
}
References lcontext::ctx, lsqlite_checkcontext(), lua_strlen, luaL_checkstring, and sqlite3_result_error().
lcontext_result_int()
static int lcontext_result_int (lua_State * L) static
Definition at line 862 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    int i = luaL_checkint(L, 2);
    sqlite3_result_int(ctx->ctx, i);
    return 0;
}
References lcontext::ctx, lsqlite_checkcontext(), luaL_checkint, and sqlite3_result_int().
lcontext_result_null()
static int lcontext_result_null (lua_State * L) static
Definition at line 869 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    sqlite3_result_null(ctx->ctx);
    return 0;
}
References lcontext::ctx, lsqlite_checkcontext(), and sqlite3_result_null().
lcontext_result_text()
static int lcontext_result_text (lua_State * L) static
Definition at line 875 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    const char *text = luaL_checkstring(L, 2);
    int size = lua_strlen(L, 2);
    sqlite3_result_text(ctx->ctx, text, size, SQLITE_TRANSIENT);
    return 0;
}
References lcontext::ctx, lsqlite_checkcontext(), lua_strlen, luaL_checkstring, sqlite3_result_text(), and SQLITE_TRANSIENT.
lcontext_set_aggregate_context()
static int lcontext_set_aggregate_context (lua_State * L) static
Definition at line 792 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    lcontext_check_aggregate(L, ctx);
    lua_settop(L, 2);
    luaL_unref(L, LUA_REGISTRYINDEX, ctx->ud);
    ctx->ud = luaL_ref(L, LUA_REGISTRYINDEX);
    return 0;
}
References lcontext_check_aggregate(), lsqlite_checkcontext(), LUA_REGISTRYINDEX, lua_settop(), luaL_ref(), luaL_unref(), and lcontext::ud.
lcontext_tostring()
static int lcontext_tostring (lua_State * L) static
Definition at line 760 of file lsqlite3.c.
{
    char buff[39];
    lcontext *ctx = lsqlite_getcontext(L, 1);
    if (ctx->ctx == NULL)
        strcpy(buff, "closed");
    else
        sprintf(buff, "%p", ctx->ctx);
    lua_pushfstring(L, "sqlite function context (%s)", buff);
    return 1;
}
References lcontext::ctx, lsqlite_getcontext(), lua_pushfstring(), and NULL.
lcontext_user_data()
static int lcontext_user_data (lua_State * L) static
Definition at line 778 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_checkcontext(L, 1);
    sdb_func *func = (sdb_func*)sqlite3_user_data(ctx->ctx);
    lua_rawgeti(L, LUA_REGISTRYINDEX, func->udata);
    return 1;
}
References lcontext::ctx, lsqlite_checkcontext(), lua_rawgeti(), LUA_REGISTRYINDEX, sqlite3_user_data(), and sdb_func::udata.
lsqlite_backup_init()
static int lsqlite_backup_init (lua_State * L) static
Definition at line 1587 of file lsqlite3.c.
{
    sdb *target_db = lsqlite_checkdb(L, 1);
    const char *target_nm = luaL_checkstring(L, 2);
    sdb *source_db = lsqlite_checkdb(L, 3);
    const char *source_nm = luaL_checkstring(L, 4);
    sqlite3_backup *bu = sqlite3_backup_init(target_db->db, target_nm, source_db->db, source_nm);
    if (NULL != bu) {
        sdb_bu *sbu = (sdb_bu*)lua_newuserdata(L, sizeof(sdb_bu));
        luaL_getmetatable(L, sqlite_bu_meta);
        lua_setmetatable(L, -2);        /* set metatable */
        sbu->bu = bu;
        /* create table from registry */
        /* to prevent referenced databases from being garbage collected while bu is live */
        lua_pushlightuserdata(L, bu);
        lua_createtable(L, 2, 0);
        /* add source and target dbs to table at indices 1 and 2 */
        lua_pushvalue(L, 1); /* target db */
        lua_rawseti(L, -2, 1);
        lua_pushvalue(L, 3); /* source db */
        lua_rawseti(L, -2, 2);
        /* put table in registry with key lightuserdata bu */
        lua_rawset(L, LUA_REGISTRYINDEX);
        return 1;
    }
    else {
        return 0;
    }
}
References sdb_bu::bu, sdb::db, lsqlite_checkdb(), lua_createtable(), lua_newuserdata, lua_pushlightuserdata(), lua_pushvalue(), lua_rawset(), lua_rawseti(), LUA_REGISTRYINDEX, lua_setmetatable(), luaL_checkstring, luaL_getmetatable, NULL, sqlite3_backup_init(), and sqlite_bu_meta.
lsqlite_checkbu()
static sdb_bu * lsqlite_checkbu (lua_State * L, int index) static
Definition at line 1628 of file lsqlite3.c.
{
    sdb_bu *sbu = lsqlite_getbu(L, index);
    if (sbu->bu == NULL) luaL_argerror(L, index, "attempt to use closed sqlite database backup");
    return sbu;
}
References sdb_bu::bu, index, lsqlite_getbu(), luaL_argerror(), and NULL.
Referenced by dbbu_finish(), dbbu_pagecount(), dbbu_remaining(), and dbbu_step().
lsqlite_checkcontext()
static lcontext * lsqlite_checkcontext (lua_State * L, int index) static
Definition at line 754 of file lsqlite3.c.
{
    lcontext *ctx = lsqlite_getcontext(L, index);
    if (ctx->ctx == NULL) luaL_argerror(L, index, "invalid sqlite context");
    return ctx;
}
References lcontext::ctx, index, lsqlite_getcontext(), luaL_argerror(), and NULL.
Referenced by lcontext_aggregate_count(), lcontext_get_aggregate_context(), lcontext_result(), lcontext_result_blob(), lcontext_result_double(), lcontext_result_error(), lcontext_result_int(), lcontext_result_null(), lcontext_result_text(), lcontext_set_aggregate_context(), and lcontext_user_data().
lsqlite_checkdb()
static sdb * lsqlite_checkdb (lua_State * L, int index) static
Definition at line 722 of file lsqlite3.c.
{
    sdb *db = lsqlite_getdb(L, index);
    if (db->db == NULL) luaL_argerror(L, index, "attempt to use closed sqlite database");
    return db;
}
References sdb::db, index, lsqlite_getdb(), luaL_argerror(), and NULL.
Referenced by db_busy_handler(), db_busy_timeout(), db_changes(), db_close(), db_close_vm(), db_commit_hook(), db_create_collation(), db_db_filename(), db_do_rows(), db_errcode(), db_errmsg(), db_exec(), db_get_ptr(), db_interrupt(), db_last_insert_rowid(), db_load_extension(), db_prepare(), db_progress_handler(), db_register_function(), db_rollback_hook(), db_total_changes(), db_trace(), db_update_hook(), and lsqlite_backup_init().
lsqlite_checkvm()
static sdb_vm * lsqlite_checkvm (lua_State * L, int index) static
Definition at line 253 of file lsqlite3.c.
{
    sdb_vm *svm = lsqlite_getvm(L, index);
    if (svm->vm == NULL) luaL_argerror(L, index, "attempt to use closed sqlite virtual machine");
    return svm;
}
References index, lsqlite_getvm(), luaL_argerror(), NULL, and sdb_vm::vm.
Referenced by db_do_next_row(), dbvm_bind(), dbvm_bind_blob(), dbvm_bind_names(), dbvm_bind_parameter_count(), dbvm_bind_parameter_name(), dbvm_bind_values(), dbvm_columns(), dbvm_do_rows(), dbvm_finalize(), dbvm_get_name(), dbvm_get_named_types(), dbvm_get_named_values(), dbvm_get_names(), dbvm_get_type(), dbvm_get_types(), dbvm_get_unames(), dbvm_get_utypes(), dbvm_get_uvalues(), dbvm_get_value(), dbvm_get_values(), dbvm_last_insert_rowid(), dbvm_reset(), and dbvm_step().
lsqlite_complete()
static int lsqlite_complete (lua_State * L) static
Definition at line 2045 of file lsqlite3.c.
{
    const char *sql = luaL_checkstring(L, 1);
    lua_pushboolean(L, sqlite3_complete(sql));
    return 1;
}
References lua_pushboolean(), luaL_checkstring, and sqlite3_complete().
lsqlite_do_open()
static int lsqlite_do_open (lua_State * L, const char * filename, int flags) static
Definition at line 2072 of file lsqlite3.c.
{
    sdb *db = newdb(L); /* create and leave in stack */
    if (SQLITE3_OPEN(filename, &db->db, flags) == SQLITE_OK) {
        /* database handle already in the stack - return it */
        return 1;
    }
    /* failed to open database */
    lua_pushnil(L);                             /* push nil */
    lua_pushinteger(L, sqlite3_errcode(db->db));
    lua_pushstring(L, sqlite3_errmsg(db->db));  /* push error message */
    /* clean things up */
    cleanupdb(L, db);
    /* return */
    return 3;
}
References cleanupdb(), sdb::db, lua_pushinteger(), lua_pushnil(), lua_pushstring(), newdb(), sqlite3_errcode(), sqlite3_errmsg(), SQLITE3_OPEN, and SQLITE_OK.
Referenced by lsqlite_open(), and lsqlite_open_memory().
lsqlite_getbu()
static sdb_bu * lsqlite_getbu (lua_State * L, int index) static
Definition at line 1622 of file lsqlite3.c.
{
    sdb_bu *sbu = (sdb_bu*)luaL_checkudata(L, index, sqlite_bu_meta);
    if (sbu == NULL) luaL_typerror(L, index, "sqlite database backup");
    return sbu;
}
References index, luaL_checkudata(), luaL_typerror(), NULL, and sqlite_bu_meta.
Referenced by dbbu_gc(), and lsqlite_checkbu().
lsqlite_getcontext()
static lcontext * lsqlite_getcontext (lua_State * L, int index) static
Definition at line 748 of file lsqlite3.c.
{
    lcontext *ctx = (lcontext*)luaL_checkudata(L, index, sqlite_ctx_meta);
    if (ctx == NULL) luaL_typerror(L, index, "sqlite context");
    return ctx;
}
References index, luaL_checkudata(), luaL_typerror(), NULL, and sqlite_ctx_meta.
Referenced by db_sql_finalize_function(), db_sql_normal_function(), lcontext_tostring(), and lsqlite_checkcontext().
lsqlite_getdb()
static sdb * lsqlite_getdb (lua_State * L, int index) static
Definition at line 716 of file lsqlite3.c.
{
    sdb *db = (sdb*)luaL_checkudata(L, index, sqlite_meta);
    if (db == NULL) luaL_typerror(L, index, "sqlite database");
    return db;
}
References index, luaL_checkudata(), luaL_typerror(), NULL, and sqlite_meta.
Referenced by db_gc(), db_isopen(), db_tostring(), and lsqlite_checkdb().
lsqlite_getvm()
static sdb_vm * lsqlite_getvm (lua_State * L, int index) static
Definition at line 247 of file lsqlite3.c.
{
    sdb_vm *svm = (sdb_vm*)luaL_checkudata(L, index, sqlite_vm_meta);
    if (svm == NULL) luaL_argerror(L, index, "bad sqlite virtual machine");
    return svm;
}
References index, luaL_argerror(), luaL_checkudata(), NULL, and sqlite_vm_meta.
Referenced by dbvm_gc(), dbvm_isopen(), dbvm_tostring(), and lsqlite_checkvm().
lsqlite_lversion()
static int lsqlite_lversion (lua_State * L) static
Definition at line 2139 of file lsqlite3.c.
{
    lua_pushstring(L, LSQLITE_VERSION);
    return 1;
}
References LSQLITE_VERSION, and lua_pushstring().
lsqlite_make_context()
static lcontext * lsqlite_make_context (lua_State * L) static
Definition at line 739 of file lsqlite3.c.
{
    lcontext *ctx = (lcontext*)lua_newuserdata(L, sizeof(lcontext));
    lua_rawgeti(L, LUA_REGISTRYINDEX, sqlite_ctx_meta_ref);
    lua_setmetatable(L, -2);
    ctx->ctx = NULL;
    ctx->ud = LUA_NOREF;
    return ctx;
}
References lcontext::ctx, lua_newuserdata, LUA_NOREF, lua_rawgeti(), LUA_REGISTRYINDEX, lua_setmetatable(), NULL, sqlite_ctx_meta_ref, and lcontext::ud.
Referenced by db_sql_finalize_function(), and db_sql_normal_function().
lsqlite_newindex()
static int lsqlite_newindex (lua_State * L) static
Definition at line 2126 of file lsqlite3.c.
{
    lua_pushliteral(L, "attempt to change readonly table");
    lua_error(L);
    return 0;
}
References lua_error(), and lua_pushliteral.
lsqlite_open()
static int lsqlite_open (lua_State * L) static
Definition at line 2092 of file lsqlite3.c.
{
    const char *filename = luaL_checkstring(L, 1);
    int flags = luaL_optinteger(L, 2, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE);
    return lsqlite_do_open(L, filename, flags);
}
References lsqlite_do_open(), luaL_checkstring, luaL_optinteger(), SQLITE_OPEN_CREATE, and SQLITE_OPEN_READWRITE.
lsqlite_open_memory()
static int lsqlite_open_memory (lua_State * L) static
Definition at line 2098 of file lsqlite3.c.
{
    return lsqlite_do_open(L, ":memory:", SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE);
}
References lsqlite_do_open(), SQLITE_OPEN_CREATE, and SQLITE_OPEN_READWRITE.
lsqlite_open_ptr()
static int lsqlite_open_ptr (lua_State * L) static
Definition at line 2107 of file lsqlite3.c.
{
    sqlite3 *db_ptr;
    sdb *db;
    int rc;
    luaL_checktype(L, 1, LUA_TLIGHTUSERDATA);
    db_ptr = lua_touserdata(L, 1);
    /* This is the only API function that runs sqlite3SafetyCheck regardless of
     * SQLITE_ENABLE_API_ARMOR and does almost nothing (without an SQL
     * statement) */
    rc = sqlite3_exec(db_ptr, NULL, NULL, NULL, NULL);
    if (rc != SQLITE_OK)
        luaL_argerror(L, 1, "not a valid SQLite3 pointer");
    db = newdb(L); /* create and leave in stack */
    db->db = db_ptr;
    return 1;
}
References sdb::db, LUA_TLIGHTUSERDATA, lua_touserdata(), luaL_argerror(), luaL_checktype(), newdb(), NULL, sqlite3_exec(), and SQLITE_OK.
lsqlite_temp_directory()
static int lsqlite_temp_directory (lua_State * L) static
Definition at line 2052 of file lsqlite3.c.
{
    const char *oldtemp = sqlite3_temp_directory;
    if (!lua_isnone(L, 1)) {
        const char *temp = luaL_optstring(L, 1, NULL);
        if (sqlite3_temp_directory) {
            sqlite3_free((char*)sqlite3_temp_directory);
        }
        if (temp) {
            sqlite3_temp_directory = sqlite3_mprintf("%s", temp);
        }
        else {
            sqlite3_temp_directory = NULL;
        }
    }
    lua_pushstring(L, oldtemp);
    return 1;
}
References lua_isnone, lua_pushstring(), luaL_optstring, NULL, sqlite3_free(), sqlite3_mprintf(), and sqlite3_temp_directory.
lsqlite_version()
static int lsqlite_version (lua_State * L) static
Definition at line 2040 of file lsqlite3.c.
{
    lua_pushstring(L, sqlite3_libversion());
    return 1;
}
References lua_pushstring(), and sqlite3_libversion().
luaopen_lsqlite3()
LUALIB_API int luaopen_lsqlite3 (lua_State * L)
Definition at line 2384 of file lsqlite3.c.
{
    create_meta(L, sqlite_meta, dblib);
    create_meta(L, sqlite_vm_meta, vmlib);
    create_meta(L, sqlite_bu_meta, dbbulib);
    create_meta(L, sqlite_ctx_meta, ctxlib);
    luaL_getmetatable(L, sqlite_ctx_meta);
    sqlite_ctx_meta_ref = luaL_ref(L, LUA_REGISTRYINDEX);
    /* register global sqlite3 library */
    luaL_requiref(L, "sqlite3", luaopen_sqlitelib, 1);
    {
        int i = 0;
        /* add constants to global table */
        while (sqlite_constants[i].name) {
            lua_pushstring(L, sqlite_constants[i].name);
            lua_pushinteger(L, sqlite_constants[i].value);
            lua_rawset(L, -3);
            ++i;
        }
    }
    /* set sqlite's metatable to itself - set as readonly (__newindex) */
    lua_pushvalue(L, -1);
    lua_setmetatable(L, -2);
    return 1;
}
References create_meta(), ctxlib, dbbulib, dblib, lua_pushinteger(), lua_pushstring(), lua_pushvalue(), lua_rawset(), LUA_REGISTRYINDEX, lua_setmetatable(), luaL_getmetatable, luaL_ref(), luaL_requiref(), luaopen_sqlitelib(), name, sqlite_bu_meta, sqlite_constants, sqlite_ctx_meta, sqlite_ctx_meta_ref, sqlite_meta, sqlite_vm_meta, value, and vmlib.
luaopen_sqlitelib()
static int luaopen_sqlitelib (lua_State * L) static
Definition at line 2378 of file lsqlite3.c.
{
    luaL_newlibtable(L, sqlitelib);
    luaL_setfuncs(L, sqlitelib, 0);
    return 1;
}
References luaL_newlibtable, luaL_setfuncs(), and sqlitelib.
Referenced by luaopen_lsqlite3().
newdb()
static sdb * newdb (lua_State * L) static
Definition at line 621 of file lsqlite3.c.
{
    sdb *db = (sdb*)lua_newuserdata(L, sizeof(sdb));
    db->L = L;
    db->db = NULL;  /* database handle is currently `closed' */
    db->func = NULL;
    db->busy_cb =
    db->busy_udata =
    db->progress_cb =
    db->progress_udata =
    db->trace_cb =
    db->trace_udata =
#if !defined(LSQLITE_OMIT_UPDATE_HOOK) || !LSQLITE_OMIT_UPDATE_HOOK
    db->update_hook_cb =
    db->update_hook_udata =
    db->commit_hook_cb =
    db->commit_hook_udata =
    db->rollback_hook_cb =
    db->rollback_hook_udata =
#endif
     LUA_NOREF;
    luaL_getmetatable(L, sqlite_meta);
    lua_setmetatable(L, -2);        /* set metatable */
    /* to keep track of 'open' virtual machines */
    lua_pushlightuserdata(L, db);
    lua_newtable(L);
    lua_rawset(L, LUA_REGISTRYINDEX);
    return db;
}
References sdb::busy_cb, sdb::busy_udata, sdb::commit_hook_cb, sdb::commit_hook_udata, sdb::db, sdb::func, sdb::L, lua_newtable, lua_newuserdata, LUA_NOREF, lua_pushlightuserdata(), lua_rawset(), LUA_REGISTRYINDEX, lua_setmetatable(), luaL_getmetatable, NULL, sdb::progress_cb, sdb::progress_udata, sdb::rollback_hook_cb, sdb::rollback_hook_udata, sqlite_meta, sdb::trace_cb, sdb::trace_udata, sdb::update_hook_cb, and sdb::update_hook_udata.
Referenced by lsqlite_do_open(), and lsqlite_open_ptr().
newvm()
static sdb_vm * newvm (lua_State * L, sdb * db) static
Definition at line 200 of file lsqlite3.c.
{
    sdb_vm *svm = (sdb_vm*)lua_newuserdata(L, sizeof(sdb_vm)); /* db sql svm_ud -- */
    luaL_getmetatable(L, sqlite_vm_meta);
    lua_setmetatable(L, -2);        /* set metatable */
    svm->db = db;
    svm->columns = 0;
    svm->has_values = 0;
    svm->vm = NULL;
    svm->temp = 0;
    /* add an entry on the database table: svm -> db to keep db live while svm is live */
    lua_pushlightuserdata(L, db);     /* db sql svm_ud db_lud -- */
    lua_rawget(L, LUA_REGISTRYINDEX); /* db sql svm_ud reg[db_lud] -- */
    lua_pushlightuserdata(L, svm);    /* db sql svm_ud reg[db_lud] svm_lud -- */
    lua_pushvalue(L, -5);             /* db sql svm_ud reg[db_lud] svm_lud db -- */
    lua_rawset(L, -3);                /* (reg[db_lud])[svm_lud] = db ; set the db for this vm */
    lua_pop(L, 1);                    /* db sql svm_ud -- */
    return svm;
}
References sdb_vm::columns, sdb_vm::db, sdb_vm::has_values, lua_newuserdata, lua_pop, lua_pushlightuserdata(), lua_pushvalue(), lua_rawget(), lua_rawset(), LUA_REGISTRYINDEX, lua_setmetatable(), luaL_getmetatable, NULL, sqlite_vm_meta, sdb_vm::temp, and sdb_vm::vm.
Referenced by db_do_rows(), and db_prepare().
stepvm()
static int stepvm (lua_State * L, sdb_vm * svm) static
Definition at line 243 of file lsqlite3.c.
{
    return sqlite3_step(svm->vm);
}
References sqlite3_step(), and sdb_vm::vm.
Referenced by db_do_next_row(), and dbvm_step().
vm_push_column()
static void vm_push_column (lua_State * L, sqlite3_stmt * vm, int idx) static
Definition at line 162 of file lsqlite3.c.
{
    switch (sqlite3_column_type(vm, idx)) {
        case SQLITE_INTEGER:
            PUSH_INT64(L, sqlite3_column_int64(vm, idx)
                     , lua_pushlstring(L, (const char*)sqlite3_column_text(vm, idx)
                                        , sqlite3_column_bytes(vm, idx)));
            break;
        case SQLITE_FLOAT:
            lua_pushnumber(L, sqlite3_column_double(vm, idx));
            break;
        case SQLITE_TEXT:
            lua_pushlstring(L, (const char*)sqlite3_column_text(vm, idx), sqlite3_column_bytes(vm, idx));
            break;
        case SQLITE_BLOB:
            lua_pushlstring(L, sqlite3_column_blob(vm, idx), sqlite3_column_bytes(vm, idx));
            break;
        case SQLITE_NULL:
            lua_pushnil(L);
            break;
        default:
            lua_pushnil(L);
            break;
    }
}
References lua_pushlstring(), lua_pushnil(), lua_pushnumber(), PUSH_INT64, sqlite3_column_blob(), sqlite3_column_bytes(), sqlite3_column_double(), sqlite3_column_int64(), sqlite3_column_text(), sqlite3_column_type(), SQLITE_BLOB, SQLITE_FLOAT, SQLITE_INTEGER, SQLITE_NULL, and SQLITE_TEXT.
Referenced by db_do_next_row(), dbvm_get_named_values(), dbvm_get_uvalues(), dbvm_get_value(), and dbvm_get_values().
Variable Documentation
ctxlib
const luaL_Reg ctxlib[] static
Initial value:
= {
    {"user_data",               lcontext_user_data              },
    {"get_aggregate_data",      lcontext_get_aggregate_context  },
    {"set_aggregate_data",      lcontext_set_aggregate_context  },
    {"aggregate_count",         lcontext_aggregate_count        },
    {"result",                  lcontext_result                 },
    {"result_null",             lcontext_result_null            },
    {"result_number",           lcontext_result_double          },
    {"result_double",           lcontext_result_double          },
    {"result_int",              lcontext_result_int             },
    {"result_text",             lcontext_result_text            },
    {"result_blob",             lcontext_result_blob            },
    {"result_error",            lcontext_result_error           },
    {"__tostring",              lcontext_tostring               },
    {NULL, NULL}
}
Definition at line 2316 of file lsqlite3.c.
{
    {"user_data",               lcontext_user_data              },
    {"get_aggregate_data",      lcontext_get_aggregate_context  },
    {"set_aggregate_data",      lcontext_set_aggregate_context  },
    {"aggregate_count",         lcontext_aggregate_count        },
    {"result",                  lcontext_result                 },
    {"result_null",             lcontext_result_null            },
    {"result_number",           lcontext_result_double          },
    {"result_double",           lcontext_result_double          },
    {"result_int",              lcontext_result_int             },
    {"result_text",             lcontext_result_text            },
    {"result_blob",             lcontext_result_blob            },
    {"result_error",            lcontext_result_error           },
    {"__tostring",              lcontext_tostring               },
    {NULL, NULL}
};
Referenced by luaopen_lsqlite3().
dbbulib
const luaL_Reg dbbulib[] static
Initial value:
= {
    {"step",        dbbu_step       },
    {"remaining",   dbbu_remaining  },
    {"pagecount",   dbbu_pagecount  },
    {"finish",      dbbu_finish     },
    {"__gc",        dbbu_gc         },
    {NULL, NULL}
}
Definition at line 2336 of file lsqlite3.c.
{
    {"step",        dbbu_step       },
    {"remaining",   dbbu_remaining  },
    {"pagecount",   dbbu_pagecount  },
    {"finish",      dbbu_finish     },
//  {"__tostring",  dbbu_tostring   },
    {"__gc",        dbbu_gc         },
    {NULL, NULL}
};
Referenced by luaopen_lsqlite3().
dblib
const luaL_Reg dblib[] static
Definition at line 2224 of file lsqlite3.c.
{
    {"isopen",              db_isopen               },
    {"last_insert_rowid",   db_last_insert_rowid    },
    {"changes",             db_changes              },
    {"total_changes",       db_total_changes        },
    {"errcode",             db_errcode              },
    {"error_code",          db_errcode              },
    {"errmsg",              db_errmsg               },
    {"error_message",       db_errmsg               },
    {"interrupt",           db_interrupt            },
    {"db_filename",         db_db_filename          },
    {"create_function",     db_create_function      },
    {"create_aggregate",    db_create_aggregate     },
    {"create_collation",    db_create_collation     },
    {"load_extension",      db_load_extension       },
    {"trace",               db_trace                },
    {"progress_handler",    db_progress_handler     },
    {"busy_timeout",        db_busy_timeout         },
    {"busy_handler",        db_busy_handler         },
#if !defined(LSQLITE_OMIT_UPDATE_HOOK) || !LSQLITE_OMIT_UPDATE_HOOK
    {"update_hook",         db_update_hook          },
    {"commit_hook",         db_commit_hook          },
    {"rollback_hook",       db_rollback_hook        },
#endif
    {"prepare",             db_prepare              },
    {"rows",                db_rows                 },
    {"urows",               db_urows                },
    {"nrows",               db_nrows                },
    {"exec",                db_exec                 },
    {"execute",             db_exec                 },
    {"close",               db_close                },
    {"close_vm",            db_close_vm             },
    {"get_ptr",             db_get_ptr              },
    {"__tostring",          db_tostring             },
    {"__gc",                db_gc                   },
    {NULL, NULL}
};
Referenced by luaopen_lsqlite3().
name
const char* name
Definition at line 2154 of file lsqlite3.c.
Referenced by _file_info_(), aux_upvalue(), aux_upvalue(), aux_upvalue(), auxopen(), auxupvalue(), auxupvalue(), auxupvalue(), auxupvalue(), checkrepeated(), create_meta(), createlabel(), db_getlocal(), db_getlocal(), db_getlocal(), db_getlocal(), db_register_function(), db_setlocal(), db_setlocal(), dbvm_bind_names(), dofile(), dofile(), dofile(), dofile(), dolibrary(), dolibrary(), dolibrary(), dolibrary(), dostring(), dostring(), dostring(), dostring(), duk__declvar_helper(), duk__delvar_helper(), duk__get_identifier_reference(), duk__getid_activation_regs(), duk__getid_open_decl_env_regs(), duk__getvar_helper(), duk__js_execute_bytecode_inner(), duk__putvar_helper(), duk_js_declvar_activation(), duk_js_delvar_activation(), duk_js_getvar_activation(), duk_js_getvar_envrec(), duk_js_putvar_activation(), duk_js_putvar_envrec(), fetch_github_user(), fetch_github_user(), findfile(), findfile(), findfile(), findfile(), findlabel(), findloader(), findloader(), findloader(), findlocal(), findlocal(), findlocal(), funcnamefromcode(), funcnamefromcode(), get_header(), get_option_index(), get_req_headers(), get_system_name(), getfuncname(), getfuncname(), getfuncname(), getfuncname(), getnextfilename(), getobjname(), getobjname(), getobjname(), getobjname(), getupvalname(), getupvalname(), getupvalname(), gotostat(), gxf(), handle_luainit(), handle_luainit(), handle_luainit(), indexupvalue(), init_ssl_ctx(), kname(), kname(), kname(), labelstat(), ll_require(), ll_require(), ll_require(), ll_require(), loader_C(), loader_Croot(), loader_Lua(), loader_preload(), lua_getglobal(), lua_getlocal(), lua_getupvalue(), lua_setglobal(), lua_setlocal(), lua_setupvalue(), luaD_protectedparser(), luaD_protectedparser(), luaG_callerror(), luaG_findlocal(), luaG_typeerror(), luaL_checkoption(), luaL_checkoption(), luaL_loadbuffer(), luaL_loadbufferx(), luaopen_lsqlite3(), luaT_objtypename(), luaU_undump(), luaU_undump(), luaY_parser(), luaY_parser(), mg_get_header(), mg_get_option(), mg_get_system_info(), mg_get_var(), mg_get_var2(), mg_init_library(), mg_set_thread_name(), mg_split_form_urlencoded(), mg_start2(), mg_start_domain2(), new_localvar(), new_localvar(), new_localvar(), new_localvar(), new_localvarliteral_(), new_localvarliteral_(), newgotoentry(), newlabelentry(), newlabelentry(), newlabelentry(), newupvalue(), newupvalue(), newupvalue(), open_auth_file(), parse_auth_header(), print_props(), pushglobalfuncname(), pushglobalfuncname(), rkname(), rname(), searcher_C(), searcher_C(), searcher_C(), searcher_Croot(), searcher_Croot(), searcher_Croot(), searcher_Lua(), searcher_Lua(), searcher_Lua(), searcher_preload(), searcher_preload(), searcher_preload(), searchpath(), searchpath(), searchpath(), searchupvalue(), searchupvalue(), searchupvalue(), set_option(), set_ports_option(), show_usage_and_exit(), varinfo(), and varinfo().
sqlite_bu_meta
const char* sqlite_bu_meta = ":sqlite3:bu" static
Definition at line 126 of file lsqlite3.c.
Referenced by lsqlite_backup_init(), lsqlite_getbu(), and luaopen_lsqlite3().
[struct]
const struct { ... } sqlite_constants[]
Referenced by luaopen_lsqlite3().
sqlite_ctx_meta
const char* sqlite_ctx_meta = ":sqlite3:ctx" static
Definition at line 127 of file lsqlite3.c.
Referenced by lsqlite_getcontext(), and luaopen_lsqlite3().
sqlite_ctx_meta_ref
int sqlite_ctx_meta_ref static
Definition at line 128 of file lsqlite3.c.
Referenced by lsqlite_make_context(), and luaopen_lsqlite3().
sqlite_meta
const char* sqlite_meta = ":sqlite3" static
Definition at line 124 of file lsqlite3.c.
Referenced by lsqlite_getdb(), luaopen_lsqlite3(), and newdb().
sqlite_vm_meta
const char* sqlite_vm_meta = ":sqlite3:vm" static
Definition at line 125 of file lsqlite3.c.
Referenced by lsqlite_getvm(), luaopen_lsqlite3(), and newvm().
sqlitelib
const luaL_Reg sqlitelib[] static
Initial value:
= {
    {"lversion",        lsqlite_lversion        },
    {"version",         lsqlite_version         },
    {"complete",        lsqlite_complete        },
    {"temp_directory",  lsqlite_temp_directory  },
    {"open",            lsqlite_open            },
    {"open_memory",     lsqlite_open_memory     },
    {"open_ptr",        lsqlite_open_ptr        },
    {"backup_init",     lsqlite_backup_init     },
    {"__newindex",      lsqlite_newindex        },
    {NULL, NULL}
}
Definition at line 2348 of file lsqlite3.c.
{
    {"lversion",        lsqlite_lversion        },
    {"version",         lsqlite_version         },
    {"complete",        lsqlite_complete        },
#ifndef _WIN32
    {"temp_directory",  lsqlite_temp_directory  },
#endif
    {"open",            lsqlite_open            },
    {"open_memory",     lsqlite_open_memory     },
    {"open_ptr",        lsqlite_open_ptr        },
    {"backup_init",     lsqlite_backup_init     },
    {"__newindex",      lsqlite_newindex        },
    {NULL, NULL}
};
Referenced by luaopen_sqlitelib().
value
int value
Definition at line 2155 of file lsqlite3.c.
Referenced by codeInteger(), codeReal(), db_push_value(), dbvm_bind_blob(), json_array_append(), json_array_insert(), json_array_set(), json_object_iter_set(), json_object_set(), json_object_set_nocheck(), json_object_setn(), json_object_setn_nocheck(), luaH_finishset(), luaH_newkey(), luaH_set(), luaH_setint(), luaH_setint(), luaopen_lsqlite3(), mg_split_form_urlencoded(), mg_start2(), mg_start_domain2(), parse_auth_header(), putinteger(), set_option(), setboolfield(), setboolfield(), setboolfield(), setboolfield(), setfield(), setfield(), setfield(), setfield(), and sqlite3VdbeIntValue().
vmlib
const luaL_Reg vmlib[] static
Definition at line 2268 of file lsqlite3.c.
{
    {"isopen",              dbvm_isopen             },
    {"step",                dbvm_step               },
    {"reset",               dbvm_reset              },
    {"finalize",            dbvm_finalize           },
    {"columns",             dbvm_columns            },
    {"bind",                dbvm_bind               },
    {"bind_values",         dbvm_bind_values        },
    {"bind_names",          dbvm_bind_names         },
    {"bind_blob",           dbvm_bind_blob          },
    {"bind_parameter_count",dbvm_bind_parameter_count},
    {"bind_parameter_name", dbvm_bind_parameter_name},
    {"get_value",           dbvm_get_value          },
    {"get_values",          dbvm_get_values         },
    {"get_name",            dbvm_get_name           },
    {"get_names",           dbvm_get_names          },
    {"get_type",            dbvm_get_type           },
    {"get_types",           dbvm_get_types          },
    {"get_uvalues",         dbvm_get_uvalues        },
    {"get_unames",          dbvm_get_unames         },
    {"get_utypes",          dbvm_get_utypes         },
    {"get_named_values",    dbvm_get_named_values   },
    {"get_named_types",     dbvm_get_named_types    },
    {"rows",                dbvm_rows               },
    {"urows",               dbvm_urows              },
    {"nrows",               dbvm_nrows              },
    {"last_insert_rowid",   dbvm_last_insert_rowid  },
    /* compatibility names (added by request) */
    {"idata",               dbvm_get_values         },
    {"inames",              dbvm_get_names          },
    {"itypes",              dbvm_get_types          },
    {"data",                dbvm_get_named_values   },
    {"type",                dbvm_get_named_types    },
    {"__tostring",          dbvm_tostring           },
    {"__gc",                dbvm_gc                 },
    { NULL, NULL }
};
Referenced by luaopen_lsqlite3().