Github User Fetcher: lcode.c File Reference
lcode.c File Reference
#include "lprefix.h"
#include <limits.h>
#include <math.h>
#include <stdlib.h>
#include "lua.h"
#include "lcode.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "llex.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
#include "lstring.h"
#include "ltable.h"
#include "lvm.h"
Macros
#define lcode_c
#define LUA_CORE
#define MAXREGS 255
#define hasjumps(e) ((e)->t != (e)->f)
#define LIMLINEDIFF 0x80
Functions
static int codesJ (FuncState *fs, OpCode o, int sj, int k)
l_noret luaK_semerror (LexState *ls, const char *msg)
static int tonumeral (const expdesc *e, TValue *v)
static TValue * const2val (FuncState *fs, const expdesc *e)
int luaK_exp2const (FuncState *fs, const expdesc *e, TValue *v)
static Instruction * previousinstruction (FuncState *fs)
void luaK_nil (FuncState *fs, int from, int n)
static int getjump (FuncState *fs, int pc)
static void fixjump (FuncState *fs, int pc, int dest)
void luaK_concat (FuncState *fs, int *l1, int l2)
int luaK_jump (FuncState *fs)
void luaK_ret (FuncState *fs, int first, int nret)
static int condjump (FuncState *fs, OpCode op, int A, int B, int C, int k)
int luaK_getlabel (FuncState *fs)
static Instruction * getjumpcontrol (FuncState *fs, int pc)
static int patchtestreg (FuncState *fs, int node, int reg)
static void removevalues (FuncState *fs, int list)
static void patchlistaux (FuncState *fs, int list, int vtarget, int reg, int dtarget)
void luaK_patchlist (FuncState *fs, int list, int target)
void luaK_patchtohere (FuncState *fs, int list)
static void savelineinfo (FuncState *fs, Proto *f, int line)
static void removelastlineinfo (FuncState *fs)
static void removelastinstruction (FuncState *fs)
int luaK_code (FuncState *fs, Instruction i)
int luaK_codeABCk (FuncState *fs, OpCode o, int a, int b, int c, int k)
int luaK_codeABx (FuncState *fs, OpCode o, int a, unsigned int bc)
int luaK_codeAsBx (FuncState *fs, OpCode o, int a, int bc)
static int codeextraarg (FuncState *fs, int a)
static int luaK_codek (FuncState *fs, int reg, int k)
void luaK_checkstack (FuncState *fs, int n)
void luaK_reserveregs (FuncState *fs, int n)
static void freereg (FuncState *fs, int reg)
static void freeregs (FuncState *fs, int r1, int r2)
static void freeexp (FuncState *fs, expdesc *e)
static void freeexps (FuncState *fs, expdesc *e1, expdesc *e2)
static int addk (FuncState *fs, TValue *key, TValue *v)
static int stringK (FuncState *fs, TString *s)
static int luaK_intK (FuncState *fs, lua_Integer n)
static int luaK_numberK (FuncState *fs, lua_Number r)
static int boolF (FuncState *fs)
static int boolT (FuncState *fs)
static int nilK (FuncState *fs)
static int fitsC (lua_Integer i)
static int fitsBx (lua_Integer i)
void luaK_int (FuncState *fs, int reg, lua_Integer i)
static void luaK_float (FuncState *fs, int reg, lua_Number f)
static void const2exp (TValue *v, expdesc *e)
void luaK_setreturns (FuncState *fs, expdesc *e, int nresults)
static void str2K (FuncState *fs, expdesc *e)
void luaK_setoneret (FuncState *fs, expdesc *e)
void luaK_dischargevars (FuncState *fs, expdesc *e)
static void discharge2reg (FuncState *fs, expdesc *e, int reg)
static void discharge2anyreg (FuncState *fs, expdesc *e)
static int code_loadbool (FuncState *fs, int A, OpCode op)
static int need_value (FuncState *fs, int list)
static void exp2reg (FuncState *fs, expdesc *e, int reg)
void luaK_exp2nextreg (FuncState *fs, expdesc *e)
int luaK_exp2anyreg (FuncState *fs, expdesc *e)
void luaK_exp2anyregup (FuncState *fs, expdesc *e)
void luaK_exp2val (FuncState *fs, expdesc *e)
static int luaK_exp2K (FuncState *fs, expdesc *e)
int luaK_exp2RK (FuncState *fs, expdesc *e)
static void codeABRK (FuncState *fs, OpCode o, int a, int b, expdesc *ec)
void luaK_storevar (FuncState *fs, expdesc *var, expdesc *ex)
void luaK_self (FuncState *fs, expdesc *e, expdesc *key)
static void negatecondition (FuncState *fs, expdesc *e)
static int jumponcond (FuncState *fs, expdesc *e, int cond)
void luaK_goiftrue (FuncState *fs, expdesc *e)
void luaK_goiffalse (FuncState *fs, expdesc *e)
static void codenot (FuncState *fs, expdesc *e)
static int isKstr (FuncState *fs, expdesc *e)
int luaK_isKint (expdesc *e)
static int isCint (expdesc *e)
static int isSCint (expdesc *e)
static int isSCnumber (expdesc *e, int *pi, int *isfloat)
void luaK_indexed (FuncState *fs, expdesc *t, expdesc *k)
static int validop (int op, TValue *v1, TValue *v2)
static int constfolding (FuncState *fs, int op, expdesc *e1, const expdesc *e2)
static void codeunexpval (FuncState *fs, OpCode op, expdesc *e, int line)
static void finishbinexpval (FuncState *fs, expdesc *e1, expdesc *e2, OpCode op, int v2, int flip, int line, OpCode mmop, TMS event)
static void codebinexpval (FuncState *fs, OpCode op, expdesc *e1, expdesc *e2, int line)
static void codebini (FuncState *fs, OpCode op, expdesc *e1, expdesc *e2, int flip, int line, TMS event)
static int finishbinexpneg (FuncState *fs, expdesc *e1, expdesc *e2, OpCode op, int line, TMS event)
static void swapexps (expdesc *e1, expdesc *e2)
static void codearith (FuncState *fs, BinOpr opr, expdesc *e1, expdesc *e2, int flip, int line)
static void codecommutative (FuncState *fs, BinOpr op, expdesc *e1, expdesc *e2, int line)
static void codebitwise (FuncState *fs, BinOpr opr, expdesc *e1, expdesc *e2, int line)
static void codeorder (FuncState *fs, OpCode op, expdesc *e1, expdesc *e2)
static void codeeq (FuncState *fs, BinOpr opr, expdesc *e1, expdesc *e2)
void luaK_prefix (FuncState *fs, UnOpr op, expdesc *e, int line)
void luaK_infix (FuncState *fs, BinOpr op, expdesc *v)
static void codeconcat (FuncState *fs, expdesc *e1, expdesc *e2, int line)
void luaK_posfix (FuncState *fs, BinOpr opr, expdesc *e1, expdesc *e2, int line)
void luaK_fixline (FuncState *fs, int line)
void luaK_settablesize (FuncState *fs, int pc, int ra, int asize, int hsize)
void luaK_setlist (FuncState *fs, int base, int nelems, int tostore)
static int finaltarget (Instruction *code, int i)
void luaK_finish (FuncState *fs)
Macro Definition Documentation
hasjumps
#define hasjumps (e) ((e)->t != (e)->f)
Definition at line 37 of file lua-5.4.3/src/lcode.c.
Referenced by exp2reg(), isKstr(), isSCnumber(), luaK_exp2anyreg(), luaK_exp2anyregup(), luaK_exp2const(), luaK_exp2K(), luaK_exp2val(), luaK_indexed(), luaK_isKint(), and tonumeral().
lcode_c
#define lcode_c
Definition at line 7 of file lua-5.4.3/src/lcode.c.
LIMLINEDIFF
#define LIMLINEDIFF 0x80
Definition at line 318 of file lua-5.4.3/src/lcode.c.
Referenced by savelineinfo().
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/lcode.c.
MAXREGS
#define MAXREGS 255
Definition at line 34 of file lua-5.4.3/src/lcode.c.
Referenced by luaK_checkstack().
Function Documentation
addk()
static int addk (FuncState * fs, TValue * key, TValue * v) static
Definition at line 542 of file lua-5.4.3/src/lcode.c.
{
  TValue val;
  lua_State *L = fs->ls->L;
  Proto *f = fs->f;
  const TValue *idx = luaH_get(fs->ls->h, key);  /* query scanner table */
  int k, oldsize;
  if (ttisinteger(idx)) {  /* is there an index there? */
    k = cast_int(ivalue(idx));
    /* correct value? (warning: must distinguish floats from integers!) */
    if (k < fs->nk && ttypetag(&f->k[k]) == ttypetag(v) &&
                      luaV_rawequalobj(&f->k[k], v))
      return k;  /* reuse index */
  }
  /* constant not found; create a new entry */
  oldsize = f->sizek;
  k = fs->nk;
  /* numerical value does not need GC barrier;
     table has no metatable, so it does not need to invalidate cache */
  setivalue(&val, k);
  luaH_finishset(L, fs->ls->h, key, idx, &val);
  luaM_growvector(L, f->k, k, f->sizek, TValue, MAXARG_Ax, "constants");
  while (oldsize < f->sizek) setnilvalue(&f->k[oldsize++]);
  setobj(L, &f->k[k], v);
  fs->nk++;
  luaC_barrier(L, f, v);
  return k;
}
References cast_int, FuncState::f, LexState::h, ivalue, Proto::k, LexState::L, FuncState::ls, luaC_barrier, luaH_finishset(), luaH_get(), luaM_growvector, luaV_rawequalobj, MAXARG_Ax, FuncState::nk, setivalue, setnilvalue, setobj, Proto::sizek, ttisinteger, and ttypetag.
Referenced by boolF(), boolT(), luaK_intK(), luaK_numberK(), nilK(), and stringK().
boolF()
static int boolF (FuncState * fs) static
Definition at line 607 of file lua-5.4.3/src/lcode.c.
{
  TValue o;
  setbfvalue(&o);
  return addk(fs, &o, &o);  /* use boolean itself as key */
}
References addk(), and setbfvalue.
Referenced by luaK_exp2K().
boolT()
static int boolT (FuncState * fs) static
Definition at line 617 of file lua-5.4.3/src/lcode.c.
{
  TValue o;
  setbtvalue(&o);
  return addk(fs, &o, &o);  /* use boolean itself as key */
}
References addk(), and setbtvalue.
Referenced by luaK_exp2K().
code_loadbool()
static int code_loadbool (FuncState * fs, int A, OpCode op) static
Definition at line 870 of file lua-5.4.3/src/lcode.c.
{
  luaK_getlabel(fs);  /* those instructions may be jump targets */
  return luaK_codeABC(fs, op, A, 0, 0);
}
References luaK_codeABC, and luaK_getlabel().
Referenced by exp2reg().
codeABRK()
static void codeABRK (FuncState * fs, OpCode o, int a, int b, expdesc * ec) static
Definition at line 1020 of file lua-5.4.3/src/lcode.c.
{
  int k = luaK_exp2RK(fs, ec);
  luaK_codeABCk(fs, o, a, b, ec->u.info, k);
}
References expdesc::info, luaK_codeABCk(), luaK_exp2RK(), and expdesc::u.
Referenced by luaK_self(), and luaK_storevar().
codearith()
static void codearith (FuncState * fs, BinOpr opr, expdesc * e1, expdesc * e2, int flip, int line) static
Definition at line 1426 of file lua-5.4.3/src/lcode.c.
{
  TMS event = cast(TMS, opr + TM_ADD);
  if (tonumeral(e2, NULL) && luaK_exp2K(fs, e2)) {  /* K operand? */
    int v2 = e2->u.info;  /* K index */
    OpCode op = cast(OpCode, opr + OP_ADDK);
    finishbinexpval(fs, e1, e2, op, v2, flip, line, OP_MMBINK, event);
  }
  else {  /* 'e2' is neither an immediate nor a K operand */
    OpCode op = cast(OpCode, opr + OP_ADD);
    if (flip)
      swapexps(e1, e2);  /* back to original order */
    codebinexpval(fs, op, e1, e2, line);  /* use standard operators */
  }
}
References cast, codebinexpval(), finishbinexpval(), expdesc::info, luaK_exp2K(), NULL, OP_ADD, OP_ADDK, OP_MMBINK, swapexps(), TM_ADD, tonumeral(), and expdesc::u.
Referenced by codecommutative(), and luaK_posfix().
codebinexpval()
static void codebinexpval (FuncState * fs, OpCode op, expdesc * e1, expdesc * e2, int line) static
Definition at line 1374 of file lua-5.4.3/src/lcode.c.
{
  int v2 = luaK_exp2anyreg(fs, e2);  /* both operands are in registers */
  lua_assert(OP_ADD <= op && op <= OP_SHR);
  finishbinexpval(fs, e1, e2, op, v2, 0, line, OP_MMBIN,
                  cast(TMS, (op - OP_ADD) + TM_ADD));
}
References cast, finishbinexpval(), lua_assert, luaK_exp2anyreg(), OP_ADD, OP_MMBIN, OP_SHR, and TM_ADD.
Referenced by codearith(), codebitwise(), and luaK_posfix().
codebini()
static void codebini (FuncState * fs, OpCode op, expdesc * e1, expdesc * e2, int flip, int line, TMS event) static
Definition at line 1386 of file lua-5.4.3/src/lcode.c.
{
  int v2 = int2sC(cast_int(e2->u.ival));  /* immediate operand */
  lua_assert(e2->k == VKINT);
  finishbinexpval(fs, e1, e2, op, v2, flip, line, OP_MMBINI, event);
}
References cast_int, finishbinexpval(), int2sC, expdesc::ival, expdesc::k, lua_assert, OP_MMBINI, expdesc::u, and VKINT.
Referenced by codecommutative(), and luaK_posfix().
codebitwise()
static void codebitwise (FuncState * fs, BinOpr opr, expdesc * e1, expdesc * e2, int line) static
Definition at line 1466 of file lua-5.4.3/src/lcode.c.
{
  int flip = 0;
  int v2;
  OpCode op;
  if (e1->k == VKINT && luaK_exp2RK(fs, e1)) {
    swapexps(e1, e2);  /* 'e2' will be the constant operand */
    flip = 1;
  }
  else if (!(e2->k == VKINT && luaK_exp2RK(fs, e2))) {  /* no constants? */
    op = cast(OpCode, opr + OP_ADD);
    codebinexpval(fs, op, e1, e2, line);  /* all-register opcodes */
    return;
  }
  v2 = e2->u.info;  /* index in K array */
  op = cast(OpCode, opr + OP_ADDK);
  lua_assert(ttisinteger(&fs->f->k[v2]));
  finishbinexpval(fs, e1, e2, op, v2, flip, line, OP_MMBINK,
                  cast(TMS, opr + TM_ADD));
}
References cast, codebinexpval(), FuncState::f, finishbinexpval(), expdesc::info, Proto::k, expdesc::k, lua_assert, luaK_exp2RK(), OP_ADD, OP_ADDK, OP_MMBINK, swapexps(), TM_ADD, ttisinteger, expdesc::u, and VKINT.
Referenced by luaK_posfix().
codecommutative()
static void codecommutative (FuncState * fs, BinOpr op, expdesc * e1, expdesc * e2, int line) static
Definition at line 1448 of file lua-5.4.3/src/lcode.c.
{
  int flip = 0;
  if (tonumeral(e1, NULL)) {  /* is first operand a numeric constant? */
    swapexps(e1, e2);  /* change order */
    flip = 1;
  }
  if (op == OPR_ADD && isSCint(e2))  /* immediate operand? */
    codebini(fs, cast(OpCode, OP_ADDI), e1, e2, flip, line, TM_ADD);
  else
    codearith(fs, op, e1, e2, flip, line);
}
References cast, codearith(), codebini(), isSCint(), NULL, OP_ADDI, OPR_ADD, swapexps(), TM_ADD, and tonumeral().
Referenced by luaK_posfix().
codeconcat()
static void codeconcat (FuncState * fs, expdesc * e1, expdesc * e2, int line) static
Definition at line 1622 of file lua-5.4.3/src/lcode.c.
{
  Instruction *ie2 = previousinstruction(fs);
  if (GET_OPCODE(*ie2) == OP_CONCAT) {  /* is 'e2' a concatenation? */
    int n = GETARG_B(*ie2);  /* # of elements concatenated in 'e2' */
    lua_assert(e1->u.info + 1 == GETARG_A(*ie2));
    freeexp(fs, e2);
    SETARG_A(*ie2, e1->u.info);  /* correct first element ('e1') */
    SETARG_B(*ie2, n + 1);  /* will concatenate one more element */
  }
  else {  /* 'e2' is not a concatenation */
    luaK_codeABC(fs, OP_CONCAT, e1->u.info, 2, 0);  /* new concat opcode */
    freeexp(fs, e2);
    luaK_fixline(fs, line);
  }
}
References freeexp(), GET_OPCODE, GETARG_A, GETARG_B, expdesc::info, lua_assert, luaK_codeABC, luaK_fixline(), OP_CONCAT, previousinstruction(), SETARG_A, SETARG_B, and expdesc::u.
Referenced by luaK_posfix().
codeeq()
static void codeeq (FuncState * fs, BinOpr opr, expdesc * e1, expdesc * e2) static
Definition at line 1522 of file lua-5.4.3/src/lcode.c.
{
  int r1, r2;
  int im;
  int isfloat = 0;  /* not needed here, but kept for symmetry */
  OpCode op;
  if (e1->k != VNONRELOC) {
    lua_assert(e1->k == VK || e1->k == VKINT || e1->k == VKFLT);
    swapexps(e1, e2);
  }
  r1 = luaK_exp2anyreg(fs, e1);  /* 1st expression must be in register */
  if (isSCnumber(e2, &im, &isfloat)) {
    op = OP_EQI;
    r2 = im;  /* immediate operand */
  }
  else if (luaK_exp2RK(fs, e2)) {  /* 1st expression is constant? */
    op = OP_EQK;
    r2 = e2->u.info;  /* constant index */
  }
  else {
    op = OP_EQ;  /* will compare two registers */
    r2 = luaK_exp2anyreg(fs, e2);
  }
  freeexps(fs, e1, e2);
  e1->u.info = condjump(fs, op, r1, r2, isfloat, (opr == OPR_EQ));
  e1->k = VJMP;
}
References condjump(), freeexps(), expdesc::info, isSCnumber(), expdesc::k, lua_assert, luaK_exp2anyreg(), luaK_exp2RK(), OP_EQ, OP_EQI, OP_EQK, OPR_EQ, swapexps(), expdesc::u, VJMP, VK, VKFLT, VKINT, and VNONRELOC.
Referenced by luaK_posfix().
codeextraarg()
static int codeextraarg (FuncState * fs, int a) static
Definition at line 439 of file lua-5.4.3/src/lcode.c.
{
  lua_assert(a <= MAXARG_Ax);
  return luaK_code(fs, CREATE_Ax(OP_EXTRAARG, a));
}
References CREATE_Ax, lua_assert, luaK_code(), MAXARG_Ax, and OP_EXTRAARG.
Referenced by luaK_codek(), and luaK_setlist().
codenot()
static void codenot (FuncState * fs, expdesc * e) static
Definition at line 1168 of file lua-5.4.3/src/lcode.c.
{
  switch (e->k) {
    case VNIL: case VFALSE: {
      e->k = VTRUE;  /* true == not nil == not false */
      break;
    }
    case VK: case VKFLT: case VKINT: case VKSTR: case VTRUE: {
      e->k = VFALSE;  /* false == not "x" == not 0.5 == not 1 == not true */
      break;
    }
    case VJMP: {
      negatecondition(fs, e);
      break;
    }
    case VRELOC:
    case VNONRELOC: {
      discharge2anyreg(fs, e);
      freeexp(fs, e);
      e->u.info = luaK_codeABC(fs, OP_NOT, 0, e->u.info, 0);
      e->k = VRELOC;
      break;
    }
    default: lua_assert(0);  /* cannot happen */
  }
  /* interchange true and false lists */
  { int temp = e->f; e->f = e->t; e->t = temp; }
  removevalues(fs, e->f);  /* values are useless when negated */
  removevalues(fs, e->t);
}
References discharge2anyreg(), expdesc::f, freeexp(), expdesc::info, expdesc::k, lua_assert, luaK_codeABC, negatecondition(), OP_NOT, removevalues(), expdesc::t, expdesc::u, VFALSE, VJMP, VK, VKFLT, VKINT, VKSTR, VNIL, VNONRELOC, VRELOC, and VTRUE.
Referenced by luaK_prefix().
codeorder()
static void codeorder (FuncState * fs, OpCode op, expdesc * e1, expdesc * e2) static
Definition at line 1492 of file lua-5.4.3/src/lcode.c.
{
  int r1, r2;
  int im;
  int isfloat = 0;
  if (isSCnumber(e2, &im, &isfloat)) {
    /* use immediate operand */
    r1 = luaK_exp2anyreg(fs, e1);
    r2 = im;
    op = cast(OpCode, (op - OP_LT) + OP_LTI);
  }
  else if (isSCnumber(e1, &im, &isfloat)) {
    /* transform (A < B) to (B > A) and (A <= B) to (B >= A) */
    r1 = luaK_exp2anyreg(fs, e2);
    r2 = im;
    op = (op == OP_LT) ? OP_GTI : OP_GEI;
  }
  else {  /* regular case, compare two registers */
    r1 = luaK_exp2anyreg(fs, e1);
    r2 = luaK_exp2anyreg(fs, e2);
  }
  freeexps(fs, e1, e2);
  e1->u.info = condjump(fs, op, r1, r2, isfloat, 1);
  e1->k = VJMP;
}
References cast, condjump(), freeexps(), expdesc::info, isSCnumber(), expdesc::k, luaK_exp2anyreg(), OP_GEI, OP_GTI, OP_LT, OP_LTI, expdesc::u, and VJMP.
Referenced by luaK_posfix().
codesJ()
static int codesJ (FuncState * fs, OpCode o, int sj, int k) static
Definition at line 428 of file lua-5.4.3/src/lcode.c.
{
  unsigned int j = sj + OFFSET_sJ;
  lua_assert(getOpMode(o) == isJ);
  lua_assert(j <= MAXARG_sJ && (k & ~1) == 0);
  return luaK_code(fs, CREATE_sJ(o, j, k));
}
References CREATE_sJ, getOpMode, isJ, lua_assert, luaK_code(), MAXARG_sJ, and OFFSET_sJ.
Referenced by luaK_jump().
codeunexpval()
static void codeunexpval (FuncState * fs, OpCode op, expdesc * e, int line) static
Definition at line 1341 of file lua-5.4.3/src/lcode.c.
{
  int r = luaK_exp2anyreg(fs, e);  /* opcodes operate only on registers */
  freeexp(fs, e);
  e->u.info = luaK_codeABC(fs, op, 0, r, 0);  /* generate opcode */
  e->k = VRELOC;  /* all those operations are relocatable */
  luaK_fixline(fs, line);
}
References freeexp(), expdesc::info, expdesc::k, luaK_codeABC, luaK_exp2anyreg(), luaK_fixline(), expdesc::u, and VRELOC.
Referenced by luaK_prefix().
condjump()
static int condjump (FuncState * fs, OpCode op, int A, int B, int C, int k) static
Definition at line 221 of file lua-5.4.3/src/lcode.c.
{
  luaK_codeABCk(fs, op, A, B, C, k);
  return luaK_jump(fs);
}
References luaK_codeABCk(), and luaK_jump().
Referenced by codeeq(), codeorder(), and jumponcond().
const2exp()
static void const2exp (TValue * v, expdesc * e) static
Definition at line 674 of file lua-5.4.3/src/lcode.c.
{
  switch (ttypetag(v)) {
    case LUA_VNUMINT:
      e->k = VKINT; e->u.ival = ivalue(v);
      break;
    case LUA_VNUMFLT:
      e->k = VKFLT; e->u.nval = fltvalue(v);
      break;
    case LUA_VFALSE:
      e->k = VFALSE;
      break;
    case LUA_VTRUE:
      e->k = VTRUE;
      break;
    case LUA_VNIL:
      e->k = VNIL;
      break;
    case LUA_VSHRSTR:  case LUA_VLNGSTR:
      e->k = VKSTR; e->u.strval = tsvalue(v);
      break;
    default: lua_assert(0);
  }
}
References fltvalue, expdesc::ival, ivalue, expdesc::k, lua_assert, LUA_VFALSE, LUA_VLNGSTR, LUA_VNIL, LUA_VNUMFLT, LUA_VNUMINT, LUA_VSHRSTR, LUA_VTRUE, expdesc::nval, expdesc::strval, tsvalue, ttypetag, expdesc::u, VFALSE, VKFLT, VKINT, VKSTR, VNIL, and VTRUE.
Referenced by luaK_dischargevars().
const2val()
static TValue * const2val (FuncState * fs, const expdesc * e) static
Definition at line 73 of file lua-5.4.3/src/lcode.c.
{
  lua_assert(e->k == VCONST);
  return &fs->ls->dyd->actvar.arr[e->u.info].k;
}
References Dyndata::actvar, Dyndata::arr, LexState::dyd, expdesc::info, expdesc::k, Vardesc::k, FuncState::ls, lua_assert, expdesc::u, and VCONST.
Referenced by luaK_dischargevars(), and luaK_exp2const().
constfolding()
static int constfolding (FuncState * fs, int op, expdesc * e1, const expdesc * e2) static
Definition at line 1315 of file lua-5.4.3/src/lcode.c.
{
  TValue v1, v2, res;
  if (!tonumeral(e1, &v1) || !tonumeral(e2, &v2) || !validop(op, &v1, &v2))
    return 0;  /* non-numeric operands or not safe to fold */
  luaO_rawarith(fs->ls->L, op, &v1, &v2, &res);  /* does operation */
  if (ttisinteger(&res)) {
    e1->k = VKINT;
    e1->u.ival = ivalue(&res);
  }
  else {  /* folds neither NaN nor 0.0 (to avoid problems with -0.0) */
    lua_Number n = fltvalue(&res);
    if (luai_numisnan(n) || n == 0)
      return 0;
    e1->k = VKFLT;
    e1->u.nval = n;
  }
  return 1;
}
References fltvalue, expdesc::ival, ivalue, expdesc::k, LexState::L, FuncState::ls, luai_numisnan, luaO_rawarith(), expdesc::nval, tonumeral(), ttisinteger, expdesc::u, validop(), VKFLT, and VKINT.
Referenced by luaK_posfix(), and luaK_prefix().
discharge2anyreg()
static void discharge2anyreg (FuncState * fs, expdesc * e) static
Definition at line 862 of file lua-5.4.3/src/lcode.c.
{
  if (e->k != VNONRELOC) {  /* no fixed register yet? */
    luaK_reserveregs(fs, 1);  /* get a register */
    discharge2reg(fs, e, fs->freereg-1);  /* put value there */
  }
}
References discharge2reg(), FuncState::freereg, expdesc::k, luaK_reserveregs(), and VNONRELOC.
Referenced by codenot(), and jumponcond().
discharge2reg()
static void discharge2reg (FuncState * fs, expdesc * e, int reg) static
Definition at line 807 of file lua-5.4.3/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VNIL: {
      luaK_nil(fs, reg, 1);
      break;
    }
    case VFALSE: {
      luaK_codeABC(fs, OP_LOADFALSE, reg, 0, 0);
      break;
    }
    case VTRUE: {
      luaK_codeABC(fs, OP_LOADTRUE, reg, 0, 0);
      break;
    }
    case VKSTR: {
      str2K(fs, e);
    }  /* FALLTHROUGH */
    case VK: {
      luaK_codek(fs, reg, e->u.info);
      break;
    }
    case VKFLT: {
      luaK_float(fs, reg, e->u.nval);
      break;
    }
    case VKINT: {
      luaK_int(fs, reg, e->u.ival);
      break;
    }
    case VRELOC: {
      Instruction *pc = &getinstruction(fs, e);
      SETARG_A(*pc, reg);  /* instruction will put result in 'reg' */
      break;
    }
    case VNONRELOC: {
      if (reg != e->u.info)
        luaK_codeABC(fs, OP_MOVE, reg, e->u.info, 0);
      break;
    }
    default: {
      lua_assert(e->k == VJMP);
      return;  /* nothing to do... */
    }
  }
  e->u.info = reg;
  e->k = VNONRELOC;
}
References getinstruction, expdesc::info, expdesc::ival, expdesc::k, lua_assert, luaK_codeABC, luaK_codek(), luaK_dischargevars(), luaK_float(), luaK_int(), luaK_nil(), expdesc::nval, OP_LOADFALSE, OP_LOADTRUE, OP_MOVE, SETARG_A, str2K(), expdesc::u, VFALSE, VJMP, VK, VKFLT, VKINT, VKSTR, VNIL, VNONRELOC, VRELOC, and VTRUE.
Referenced by discharge2anyreg(), and exp2reg().
exp2reg()
static void exp2reg (FuncState * fs, expdesc * e, int reg) static
Definition at line 896 of file lua-5.4.3/src/lcode.c.
{
  discharge2reg(fs, e, reg);
  if (e->k == VJMP)  /* expression itself is a test? */
    luaK_concat(fs, &e->t, e->u.info);  /* put this jump in 't' list */
  if (hasjumps(e)) {
    int final;  /* position after whole expression */
    int p_f = NO_JUMP;  /* position of an eventual LOAD false */
    int p_t = NO_JUMP;  /* position of an eventual LOAD true */
    if (need_value(fs, e->t) || need_value(fs, e->f)) {
      int fj = (e->k == VJMP) ? NO_JUMP : luaK_jump(fs);
      p_f = code_loadbool(fs, reg, OP_LFALSESKIP);  /* skip next inst. */
      p_t = code_loadbool(fs, reg, OP_LOADTRUE);
      /* jump around these booleans if 'e' is not a test */
      luaK_patchtohere(fs, fj);
    }
    final = luaK_getlabel(fs);
    patchlistaux(fs, e->f, final, reg, p_f);
    patchlistaux(fs, e->t, final, reg, p_t);
  }
  e->f = e->t = NO_JUMP;
  e->u.info = reg;
  e->k = VNONRELOC;
}
References code_loadbool(), discharge2reg(), expdesc::f, hasjumps, expdesc::info, expdesc::k, luaK_concat(), luaK_getlabel(), luaK_jump(), luaK_patchtohere(), need_value(), NO_JUMP, OP_LFALSESKIP, OP_LOADTRUE, patchlistaux(), expdesc::t, expdesc::u, VJMP, and VNONRELOC.
Referenced by luaK_exp2anyreg(), luaK_exp2nextreg(), and luaK_storevar().
finaltarget()
static int finaltarget (Instruction * code, int i) static
Definition at line 1769 of file lua-5.4.3/src/lcode.c.
{
  int count;
  for (count = 0; count < 100; count++) {  /* avoid infinite loops */
    Instruction pc = code[i];
    if (GET_OPCODE(pc) != OP_JMP)
      break;
     else
       i += GETARG_sJ(pc) + 1;
  }
  return i;
}
References GET_OPCODE, GETARG_sJ, and OP_JMP.
Referenced by luaK_finish().
finishbinexpneg()
static int finishbinexpneg (FuncState * fs, expdesc * e1, expdesc * e2, OpCode op, int line, TMS event) static
Definition at line 1398 of file lua-5.4.3/src/lcode.c.
{
  if (!luaK_isKint(e2))
    return 0;  /* not an integer constant */
  else {
    lua_Integer i2 = e2->u.ival;
    if (!(fitsC(i2) && fitsC(-i2)))
      return 0;  /* not in the proper range */
    else {  /* operating a small integer constant */
      int v2 = cast_int(i2);
      finishbinexpval(fs, e1, e2, op, int2sC(-v2), 0, line, OP_MMBINI, event);
      /* correct metamethod argument */
      SETARG_B(fs->f->code[fs->pc - 1], int2sC(v2));
      return 1;  /* successfully coded */
    }
  }
}
References cast_int, Proto::code, FuncState::f, finishbinexpval(), fitsC(), int2sC, expdesc::ival, luaK_isKint(), OP_MMBINI, FuncState::pc, SETARG_B, and expdesc::u.
Referenced by luaK_posfix().
finishbinexpval()
static void finishbinexpval (FuncState * fs, expdesc * e1, expdesc * e2, OpCode op, int v2, int flip, int line, OpCode mmop, TMS event) static
Definition at line 1356 of file lua-5.4.3/src/lcode.c.
{
  int v1 = luaK_exp2anyreg(fs, e1);
  int pc = luaK_codeABCk(fs, op, 0, v1, v2, 0);
  freeexps(fs, e1, e2);
  e1->u.info = pc;
  e1->k = VRELOC;  /* all those operations are relocatable */
  luaK_fixline(fs, line);
  luaK_codeABCk(fs, mmop, v1, v2, event, flip);  /* to call metamethod */
  luaK_fixline(fs, line);
}
References freeexps(), expdesc::info, expdesc::k, luaK_codeABCk(), luaK_exp2anyreg(), luaK_fixline(), expdesc::u, and VRELOC.
Referenced by codearith(), codebinexpval(), codebini(), codebitwise(), and finishbinexpneg().
fitsBx()
static int fitsBx (lua_Integer i) static
Definition at line 649 of file lua-5.4.3/src/lcode.c.
{
  return (-OFFSET_sBx <= i && i <= MAXARG_Bx - OFFSET_sBx);
}
References MAXARG_Bx, and OFFSET_sBx.
Referenced by luaK_float(), and luaK_int().
fitsC()
static int fitsC (lua_Integer i) static
Definition at line 641 of file lua-5.4.3/src/lcode.c.
{
  return (l_castS2U(i) + OFFSET_sC <= cast_uint(MAXARG_C));
}
References cast_uint, l_castS2U, MAXARG_C, and OFFSET_sC.
Referenced by finishbinexpneg(), isSCint(), and isSCnumber().
fixjump()
static void fixjump (FuncState * fs, int pc, int dest) static
Definition at line 166 of file lua-5.4.3/src/lcode.c.
{
  Instruction *jmp = &fs->f->code[pc];
  int offset = dest - (pc + 1);
  lua_assert(dest != NO_JUMP);
  if (!(-OFFSET_sJ <= offset && offset <= MAXARG_sJ - OFFSET_sJ))
    luaX_syntaxerror(fs->ls, "control structure too long");
  lua_assert(GET_OPCODE(*jmp) == OP_JMP);
  SETARG_sJ(*jmp, offset);
}
References Proto::code, FuncState::f, GET_OPCODE, FuncState::ls, lua_assert, luaX_syntaxerror(), MAXARG_sJ, NO_JUMP, OFFSET_sJ, OP_JMP, and SETARG_sJ.
Referenced by luaK_concat(), luaK_finish(), and patchlistaux().
freeexp()
static void freeexp (FuncState * fs, expdesc * e) static
Definition at line 516 of file lua-5.4.3/src/lcode.c.
{
  if (e->k == VNONRELOC)
    freereg(fs, e->u.info);
}
References freereg(), expdesc::info, expdesc::k, expdesc::u, and VNONRELOC.
Referenced by codeconcat(), codenot(), codeunexpval(), jumponcond(), luaK_exp2nextreg(), luaK_self(), and luaK_storevar().
freeexps()
static void freeexps (FuncState * fs, expdesc * e1, expdesc * e2) static
Definition at line 526 of file lua-5.4.3/src/lcode.c.
{
  int r1 = (e1->k == VNONRELOC) ? e1->u.info : -1;
  int r2 = (e2->k == VNONRELOC) ? e2->u.info : -1;
  freeregs(fs, r1, r2);
}
References freeregs(), expdesc::info, expdesc::k, expdesc::u, and VNONRELOC.
Referenced by codeeq(), codeorder(), and finishbinexpval().
freereg()
static void freereg (FuncState * fs, int reg) static
Definition at line 490 of file lua-5.4.3/src/lcode.c.
{
  if (reg >= luaY_nvarstack(fs)) {
    fs->freereg--;
    lua_assert(reg == fs->freereg);
  }
}
References FuncState::freereg, lua_assert, and luaY_nvarstack().
Referenced by freeexp(), freeregs(), and luaK_dischargevars().
freeregs()
static void freeregs (FuncState * fs, int r1, int r2) static
Definition at line 501 of file lua-5.4.3/src/lcode.c.
{
  if (r1 > r2) {
    freereg(fs, r1);
    freereg(fs, r2);
  }
  else {
    freereg(fs, r2);
    freereg(fs, r1);
  }
}
References freereg().
Referenced by freeexps(), and luaK_dischargevars().
getjump()
static int getjump (FuncState * fs, int pc) static
Definition at line 153 of file lua-5.4.3/src/lcode.c.
{
  int offset = GETARG_sJ(fs->f->code[pc]);
  if (offset == NO_JUMP)  /* point to itself represents end of list */
    return NO_JUMP;  /* end of list */
  else
    return (pc+1)+offset;  /* turn offset into absolute position */
}
References Proto::code, FuncState::f, GETARG_sJ, and NO_JUMP.
Referenced by luaK_concat(), need_value(), patchlistaux(), and removevalues().
getjumpcontrol()
static Instruction * getjumpcontrol (FuncState * fs, int pc) static
Definition at line 242 of file lua-5.4.3/src/lcode.c.
{
  Instruction *pi = &fs->f->code[pc];
  if (pc >= 1 && testTMode(GET_OPCODE(*(pi-1))))
    return pi-1;
  else
    return pi;
}
References Proto::code, FuncState::f, GET_OPCODE, and testTMode.
Referenced by need_value(), negatecondition(), and patchtestreg().
isCint()
static int isCint (expdesc * e) static
Definition at line 1219 of file lua-5.4.3/src/lcode.c.
{
  return luaK_isKint(e) && (l_castS2U(e->u.ival) <= l_castS2U(MAXARG_C));
}
References expdesc::ival, l_castS2U, luaK_isKint(), MAXARG_C, and expdesc::u.
Referenced by luaK_indexed().
isKstr()
static int isKstr (FuncState * fs, expdesc * e) static
Definition at line 1202 of file lua-5.4.3/src/lcode.c.
{
  return (e->k == VK && !hasjumps(e) && e->u.info <= MAXARG_B &&
          ttisshrstring(&fs->f->k[e->u.info]));
}
References FuncState::f, hasjumps, expdesc::info, Proto::k, expdesc::k, MAXARG_B, ttisshrstring, expdesc::u, and VK.
Referenced by luaK_indexed().
isSCint()
static int isSCint (expdesc * e) static
Definition at line 1228 of file lua-5.4.3/src/lcode.c.
{
  return luaK_isKint(e) && fitsC(e->u.ival);
}
References fitsC(), expdesc::ival, luaK_isKint(), and expdesc::u.
Referenced by codecommutative(), and luaK_posfix().
isSCnumber()
static int isSCnumber (expdesc * e, int * pi, int * isfloat) static
Definition at line 1237 of file lua-5.4.3/src/lcode.c.
{
  lua_Integer i;
  if (e->k == VKINT)
    i = e->u.ival;
  else if (e->k == VKFLT && luaV_flttointeger(e->u.nval, &i, F2Ieq))
    *isfloat = 1;
  else
    return 0;  /* not a number */
  if (!hasjumps(e) && fitsC(i)) {
    *pi = int2sC(cast_int(i));
    return 1;
  }
  else
    return 0;
}
References cast_int, F2Ieq, fitsC(), hasjumps, int2sC, expdesc::ival, expdesc::k, luaV_flttointeger(), expdesc::nval, expdesc::u, VKFLT, and VKINT.
Referenced by codeeq(), codeorder(), and luaK_infix().
jumponcond()
static int jumponcond (FuncState * fs, expdesc * e, int cond) static
Definition at line 1097 of file lua-5.4.3/src/lcode.c.
{
  if (e->k == VRELOC) {
    Instruction ie = getinstruction(fs, e);
    if (GET_OPCODE(ie) == OP_NOT) {
      removelastinstruction(fs);  /* remove previous OP_NOT */
      return condjump(fs, OP_TEST, GETARG_B(ie), 0, 0, !cond);
    }
    /* else go through */
  }
  discharge2anyreg(fs, e);
  freeexp(fs, e);
  return condjump(fs, OP_TESTSET, NO_REG, e->u.info, 0, cond);
}
References cond(), condjump(), discharge2anyreg(), freeexp(), GET_OPCODE, GETARG_B, getinstruction, expdesc::info, expdesc::k, NO_REG, OP_NOT, OP_TEST, OP_TESTSET, removelastinstruction(), expdesc::u, and VRELOC.
Referenced by luaK_goiffalse(), and luaK_goiftrue().
luaK_checkstack()
void luaK_checkstack (FuncState * fs, int n)
Definition at line 465 of file lua-5.4.3/src/lcode.c.
{
  int newstack = fs->freereg + n;
  if (newstack > fs->f->maxstacksize) {
    if (newstack >= MAXREGS)
      luaX_syntaxerror(fs->ls,
        "function or expression needs too many registers");
    fs->f->maxstacksize = cast_byte(newstack);
  }
}
References cast_byte, FuncState::f, FuncState::freereg, FuncState::ls, luaX_syntaxerror(), MAXREGS, and Proto::maxstacksize.
Referenced by luaK_reserveregs().
luaK_code()
int luaK_code (FuncState * fs, Instruction i)
Definition at line 381 of file lua-5.4.3/src/lcode.c.
{
  Proto *f = fs->f;
  /* put new instruction in code array */
  luaM_growvector(fs->ls->L, f->code, fs->pc, f->sizecode, Instruction,
                  MAX_INT, "opcodes");
  f->code[fs->pc++] = i;
  savelineinfo(fs, f, fs->ls->lastline);
  return fs->pc - 1;  /* index of new instruction */
}
References Proto::code, FuncState::f, LexState::L, LexState::lastline, FuncState::ls, luaM_growvector, MAX_INT, FuncState::pc, savelineinfo(), and Proto::sizecode.
Referenced by codeextraarg(), codesJ(), luaK_codeABCk(), luaK_codeABx(), and luaK_codeAsBx().
luaK_codeABCk()
int luaK_codeABCk (FuncState * fs, OpCode o, int a, int b, int c, int k)
Definition at line 396 of file lua-5.4.3/src/lcode.c.
{
  lua_assert(getOpMode(o) == iABC);
  lua_assert(a <= MAXARG_A && b <= MAXARG_B &&
             c <= MAXARG_C && (k & ~1) == 0);
  return luaK_code(fs, CREATE_ABCk(o, a, b, c, k));
}
References CREATE_ABCk, getOpMode, iABC, lua_assert, luaK_code(), MAXARG_A, MAXARG_B, and MAXARG_C.
Referenced by codeABRK(), condjump(), finishbinexpval(), and luaK_setlist().
luaK_codeABx()
int luaK_codeABx (FuncState * fs, OpCode o, int a, unsigned int bc)
Definition at line 407 of file lua-5.4.3/src/lcode.c.
{
  lua_assert(getOpMode(o) == iABx);
  lua_assert(a <= MAXARG_A && bc <= MAXARG_Bx);
  return luaK_code(fs, CREATE_ABx(o, a, bc));
}
References CREATE_ABx, getOpMode, iABx, lua_assert, luaK_code(), MAXARG_A, and MAXARG_Bx.
Referenced by luaK_codek().
luaK_codeAsBx()
int luaK_codeAsBx (FuncState * fs, OpCode o, int a, int bc)
Definition at line 417 of file lua-5.4.3/src/lcode.c.
{
  unsigned int b = bc + OFFSET_sBx;
  lua_assert(getOpMode(o) == iAsBx);
  lua_assert(a <= MAXARG_A && b <= MAXARG_Bx);
  return luaK_code(fs, CREATE_ABx(o, a, b));
}
References CREATE_ABx, getOpMode, iAsBx, lua_assert, luaK_code(), MAXARG_A, MAXARG_Bx, and OFFSET_sBx.
luaK_codek()
static int luaK_codek (FuncState * fs, int reg, int k) static
Definition at line 450 of file lua-5.4.3/src/lcode.c.
{
  if (k <= MAXARG_Bx)
    return luaK_codeABx(fs, OP_LOADK, reg, k);
  else {
    int p = luaK_codeABx(fs, OP_LOADKX, reg, 0);
    codeextraarg(fs, k);
    return p;
  }
}
References codeextraarg(), luaK_codeABx(), MAXARG_Bx, OP_LOADK, and OP_LOADKX.
Referenced by discharge2reg(), luaK_float(), and luaK_int().
luaK_concat()
void luaK_concat (FuncState * fs, int * l1, int l2)
Definition at line 180 of file lua-5.4.3/src/lcode.c.
{
  if (l2 == NO_JUMP) return;  /* nothing to concatenate? */
  else if (*l1 == NO_JUMP)  /* no original list? */
    *l1 = l2;  /* 'l1' points to 'l2' */
  else {
    int list = *l1;
    int next;
    while ((next = getjump(fs, list)) != NO_JUMP)  /* find last element */
      list = next;
    fixjump(fs, list, l2);  /* last element links to 'l2' */
  }
}
References fixjump(), getjump(), next, and NO_JUMP.
Referenced by exp2reg(), luaK_goiffalse(), luaK_goiftrue(), and luaK_posfix().
luaK_dischargevars()
void luaK_dischargevars (FuncState * fs, expdesc * e)
Definition at line 754 of file lua-5.4.3/src/lcode.c.
{
  switch (e->k) {
    case VCONST: {
      const2exp(const2val(fs, e), e);
      break;
    }
    case VLOCAL: {  /* already in a register */
      e->u.info = e->u.var.ridx;
      e->k = VNONRELOC;  /* becomes a non-relocatable value */
      break;
    }
    case VUPVAL: {  /* move value to some (pending) register */
      e->u.info = luaK_codeABC(fs, OP_GETUPVAL, 0, e->u.info, 0);
      e->k = VRELOC;
      break;
    }
    case VINDEXUP: {
      e->u.info = luaK_codeABC(fs, OP_GETTABUP, 0, e->u.ind.t, e->u.ind.idx);
      e->k = VRELOC;
      break;
    }
    case VINDEXI: {
      freereg(fs, e->u.ind.t);
      e->u.info = luaK_codeABC(fs, OP_GETI, 0, e->u.ind.t, e->u.ind.idx);
      e->k = VRELOC;
      break;
    }
    case VINDEXSTR: {
      freereg(fs, e->u.ind.t);
      e->u.info = luaK_codeABC(fs, OP_GETFIELD, 0, e->u.ind.t, e->u.ind.idx);
      e->k = VRELOC;
      break;
    }
    case VINDEXED: {
      freeregs(fs, e->u.ind.t, e->u.ind.idx);
      e->u.info = luaK_codeABC(fs, OP_GETTABLE, 0, e->u.ind.t, e->u.ind.idx);
      e->k = VRELOC;
      break;
    }
    case VVARARG: case VCALL: {
      luaK_setoneret(fs, e);
      break;
    }
    default: break;  /* there is one value available (somewhere) */
  }
}
References const2exp(), const2val(), freereg(), freeregs(), expdesc::idx, expdesc::ind, expdesc::info, expdesc::k, luaK_codeABC, luaK_setoneret(), OP_GETFIELD, OP_GETI, OP_GETTABLE, OP_GETTABUP, OP_GETUPVAL, expdesc::ridx, expdesc::t, expdesc::u, expdesc::var, VCALL, VCONST, VINDEXED, VINDEXI, VINDEXSTR, VINDEXUP, VLOCAL, VNONRELOC, VRELOC, VUPVAL, and VVARARG.
Referenced by discharge2reg(), luaK_exp2anyreg(), luaK_exp2nextreg(), luaK_exp2val(), luaK_goiffalse(), luaK_goiftrue(), luaK_infix(), luaK_posfix(), and luaK_prefix().
luaK_exp2anyreg()
int luaK_exp2anyreg (FuncState * fs, expdesc * e)
Definition at line 936 of file lua-5.4.3/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  if (e->k == VNONRELOC) {  /* expression already has a register? */
    if (!hasjumps(e))  /* no jumps? */
      return e->u.info;  /* result is already in a register */
    if (e->u.info >= luaY_nvarstack(fs)) {  /* reg. is not a local? */
      exp2reg(fs, e, e->u.info);  /* put final result in it */
      return e->u.info;
    }
    /* else expression has jumps and cannot change its register
       to hold the jump values, because it is a local variable.
       Go through to the default case. */
  }
  luaK_exp2nextreg(fs, e);  /* default: use next available register */
  return e->u.info;
}
References exp2reg(), hasjumps, expdesc::info, expdesc::k, luaK_dischargevars(), luaK_exp2nextreg(), luaY_nvarstack(), expdesc::u, and VNONRELOC.
Referenced by codebinexpval(), codeeq(), codeorder(), codeunexpval(), finishbinexpval(), luaK_exp2anyregup(), luaK_exp2RK(), luaK_exp2val(), luaK_indexed(), luaK_infix(), luaK_self(), and luaK_storevar().
luaK_exp2anyregup()
void luaK_exp2anyregup (FuncState * fs, expdesc * e)
Definition at line 958 of file lua-5.4.3/src/lcode.c.
{
  if (e->k != VUPVAL || hasjumps(e))
    luaK_exp2anyreg(fs, e);
}
References hasjumps, expdesc::k, luaK_exp2anyreg(), and VUPVAL.
luaK_exp2const()
int luaK_exp2const (FuncState * fs, const expdesc * e, TValue * v)
Definition at line 83 of file lua-5.4.3/src/lcode.c.
{
  if (hasjumps(e))
    return 0;  /* not a constant */
  switch (e->k) {
    case VFALSE:
      setbfvalue(v);
      return 1;
    case VTRUE:
      setbtvalue(v);
      return 1;
    case VNIL:
      setnilvalue(v);
      return 1;
    case VKSTR: {
      setsvalue(fs->ls->L, v, e->u.strval);
      return 1;
    }
    case VCONST: {
      setobj(fs->ls->L, v, const2val(fs, e));
      return 1;
    }
    default: return tonumeral(e, v);
  }
}
References const2val(), hasjumps, expdesc::k, LexState::L, FuncState::ls, setbfvalue, setbtvalue, setnilvalue, setobj, setsvalue, expdesc::strval, tonumeral(), expdesc::u, VCONST, VFALSE, VKSTR, VNIL, and VTRUE.
Referenced by localstat().
luaK_exp2K()
static int luaK_exp2K (FuncState * fs, expdesc * e) static
Definition at line 980 of file lua-5.4.3/src/lcode.c.
{
  if (!hasjumps(e)) {
    int info;
    switch (e->k) {  /* move constants to 'k' */
      case VTRUE: info = boolT(fs); break;
      case VFALSE: info = boolF(fs); break;
      case VNIL: info = nilK(fs); break;
      case VKINT: info = luaK_intK(fs, e->u.ival); break;
      case VKFLT: info = luaK_numberK(fs, e->u.nval); break;
      case VKSTR: info = stringK(fs, e->u.strval); break;
      case VK: info = e->u.info; break;
      default: return 0;  /* not a constant */
    }
    if (info <= MAXINDEXRK) {  /* does constant fit in 'argC'? */
      e->k = VK;  /* make expression a 'K' expression */
      e->u.info = info;
      return 1;
    }
  }
  /* else, expression doesn't fit; leave it unchanged */
  return 0;
}
References boolF(), boolT(), hasjumps, expdesc::info, expdesc::ival, expdesc::k, luaK_intK(), luaK_numberK(), MAXINDEXRK, nilK(), expdesc::nval, stringK(), expdesc::strval, expdesc::u, VFALSE, VK, VKFLT, VKINT, VKSTR, VNIL, and VTRUE.
Referenced by codearith(), and luaK_exp2RK().
luaK_exp2nextreg()
void luaK_exp2nextreg (FuncState * fs, expdesc * e)
Definition at line 924 of file lua-5.4.3/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  freeexp(fs, e);
  luaK_reserveregs(fs, 1);
  exp2reg(fs, e, fs->freereg - 1);
}
References exp2reg(), freeexp(), FuncState::freereg, luaK_dischargevars(), and luaK_reserveregs().
Referenced by luaK_exp2anyreg(), luaK_infix(), and luaK_posfix().
luaK_exp2RK()
int luaK_exp2RK (FuncState * fs, expdesc * e)
Definition at line 1010 of file lua-5.4.3/src/lcode.c.
{
  if (luaK_exp2K(fs, e))
    return 1;
  else {  /* not a constant in the right range: put it in a register */
    luaK_exp2anyreg(fs, e);
    return 0;
  }
}
References luaK_exp2anyreg(), and luaK_exp2K().
Referenced by codeABRK(), codebitwise(), codeeq(), and luaK_infix().
luaK_exp2val()
void luaK_exp2val (FuncState * fs, expdesc * e)
Definition at line 968 of file lua-5.4.3/src/lcode.c.
{
  if (hasjumps(e))
    luaK_exp2anyreg(fs, e);
  else
    luaK_dischargevars(fs, e);
}
References hasjumps, luaK_dischargevars(), and luaK_exp2anyreg().
luaK_finish()
void luaK_finish (FuncState * fs)
Definition at line 1786 of file lua-5.4.3/src/lcode.c.
{
  int i;
  Proto *p = fs->f;
  for (i = 0; i < fs->pc; i++) {
    Instruction *pc = &p->code[i];
    lua_assert(i == 0 || isOT(*(pc - 1)) == isIT(*pc));
    switch (GET_OPCODE(*pc)) {
      case OP_RETURN0: case OP_RETURN1: {
        if (!(fs->needclose || p->is_vararg))
          break;  /* no extra work */
        /* else use OP_RETURN to do the extra work */
        SET_OPCODE(*pc, OP_RETURN);
      }  /* FALLTHROUGH */
      case OP_RETURN: case OP_TAILCALL: {
        if (fs->needclose)
          SETARG_k(*pc, 1);  /* signal that it needs to close */
        if (p->is_vararg)
          SETARG_C(*pc, p->numparams + 1);  /* signal that it is vararg */
        break;
      }
      case OP_JMP: {
        int target = finaltarget(p->code, i);
        fixjump(fs, i, target);
        break;
      }
      default: break;
    }
  }
}
References Proto::code, FuncState::f, finaltarget(), fixjump(), GET_OPCODE, Proto::is_vararg, isIT, isOT, lua_assert, FuncState::needclose, Proto::numparams, OP_JMP, OP_RETURN, OP_RETURN0, OP_RETURN1, OP_TAILCALL, FuncState::pc, SET_OPCODE, SETARG_C, and SETARG_k.
Referenced by close_func().
luaK_fixline()
void luaK_fixline (FuncState * fs, int line)
Definition at line 1726 of file lua-5.4.3/src/lcode.c.
{
  removelastlineinfo(fs);
  savelineinfo(fs, fs->f, line);
}
References FuncState::f, removelastlineinfo(), and savelineinfo().
Referenced by codeconcat(), codeunexpval(), and finishbinexpval().
luaK_float()
static void luaK_float (FuncState * fs, int reg, lua_Number f) static
Definition at line 662 of file lua-5.4.3/src/lcode.c.
{
  lua_Integer fi;
  if (luaV_flttointeger(f, &fi, F2Ieq) && fitsBx(fi))
    luaK_codeAsBx(fs, OP_LOADF, reg, cast_int(fi));
  else
    luaK_codek(fs, reg, luaK_numberK(fs, f));
}
References cast_int, F2Ieq, fitsBx(), luaK_codeAsBx, luaK_codek(), luaK_numberK(), luaV_flttointeger(), and OP_LOADF.
Referenced by discharge2reg().
luaK_getlabel()
int luaK_getlabel (FuncState * fs)
Definition at line 231 of file lua-5.4.3/src/lcode.c.
{
  fs->lasttarget = fs->pc;
  return fs->pc;
}
References FuncState::lasttarget, and FuncState::pc.
Referenced by code_loadbool(), exp2reg(), and luaK_patchtohere().
luaK_goiffalse()
void luaK_goiffalse (FuncState * fs, expdesc * e)
Definition at line 1142 of file lua-5.4.3/src/lcode.c.
{
  int pc;  /* pc of new jump */
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VJMP: {
      pc = e->u.info;  /* already jump if true */
      break;
    }
    case VNIL: case VFALSE: {
      pc = NO_JUMP;  /* always false; do nothing */
      break;
    }
    default: {
      pc = jumponcond(fs, e, 1);  /* jump if true */
      break;
    }
  }
  luaK_concat(fs, &e->t, pc);  /* insert new jump in 't' list */
  luaK_patchtohere(fs, e->f);  /* false list jumps to here (to go through) */
  e->f = NO_JUMP;
}
References expdesc::f, expdesc::info, jumponcond(), expdesc::k, luaK_concat(), luaK_dischargevars(), luaK_patchtohere(), NO_JUMP, expdesc::t, expdesc::u, VFALSE, VJMP, and VNIL.
Referenced by luaK_infix().
luaK_goiftrue()
void luaK_goiftrue (FuncState * fs, expdesc * e)
Definition at line 1115 of file lua-5.4.3/src/lcode.c.
{
  int pc;  /* pc of new jump */
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VJMP: {  /* condition? */
      negatecondition(fs, e);  /* jump when it is false */
      pc = e->u.info;  /* save jump position */
      break;
    }
    case VK: case VKFLT: case VKINT: case VKSTR: case VTRUE: {
      pc = NO_JUMP;  /* always true; do nothing */
      break;
    }
    default: {
      pc = jumponcond(fs, e, 0);  /* jump when false */
      break;
    }
  }
  luaK_concat(fs, &e->f, pc);  /* insert new jump in false list */
  luaK_patchtohere(fs, e->t);  /* true list jumps to here (to go through) */
  e->t = NO_JUMP;
}
References expdesc::f, expdesc::info, jumponcond(), expdesc::k, luaK_concat(), luaK_dischargevars(), luaK_patchtohere(), negatecondition(), NO_JUMP, expdesc::t, expdesc::u, VJMP, VK, VKFLT, VKINT, VKSTR, and VTRUE.
Referenced by luaK_infix().
luaK_indexed()
void luaK_indexed (FuncState * fs, expdesc * t, expdesc * k)
Definition at line 1260 of file lua-5.4.3/src/lcode.c.
{
  if (k->k == VKSTR)
    str2K(fs, k);
  lua_assert(!hasjumps(t) &&
             (t->k == VLOCAL || t->k == VNONRELOC || t->k == VUPVAL));
  if (t->k == VUPVAL && !isKstr(fs, k))  /* upvalue indexed by non 'Kstr'? */
    luaK_exp2anyreg(fs, t);  /* put it in a register */
  if (t->k == VUPVAL) {
    t->u.ind.t = t->u.info;  /* upvalue index */
    t->u.ind.idx = k->u.info;  /* literal string */
    t->k = VINDEXUP;
  }
  else {
    /* register index of the table */
    t->u.ind.t = (t->k == VLOCAL) ? t->u.var.ridx: t->u.info;
    if (isKstr(fs, k)) {
      t->u.ind.idx = k->u.info;  /* literal string */
      t->k = VINDEXSTR;
    }
    else if (isCint(k)) {
      t->u.ind.idx = cast_int(k->u.ival);  /* int. constant in proper range */
      t->k = VINDEXI;
    }
    else {
      t->u.ind.idx = luaK_exp2anyreg(fs, k);  /* register */
      t->k = VINDEXED;
    }
  }
}
References cast_int, hasjumps, expdesc::idx, expdesc::ind, expdesc::info, isCint(), isKstr(), expdesc::ival, expdesc::k, lua_assert, luaK_exp2anyreg(), expdesc::ridx, str2K(), expdesc::t, expdesc::u, expdesc::var, VINDEXED, VINDEXI, VINDEXSTR, VINDEXUP, VKSTR, VLOCAL, VNONRELOC, and VUPVAL.
luaK_infix()
void luaK_infix (FuncState * fs, BinOpr op, expdesc * v)
Definition at line 1574 of file lua-5.4.3/src/lcode.c.
{
  luaK_dischargevars(fs, v);
  switch (op) {
    case OPR_AND: {
      luaK_goiftrue(fs, v);  /* go ahead only if 'v' is true */
      break;
    }
    case OPR_OR: {
      luaK_goiffalse(fs, v);  /* go ahead only if 'v' is false */
      break;
    }
    case OPR_CONCAT: {
      luaK_exp2nextreg(fs, v);  /* operand must be on the stack */
      break;
    }
    case OPR_ADD: case OPR_SUB:
    case OPR_MUL: case OPR_DIV: case OPR_IDIV:
    case OPR_MOD: case OPR_POW:
    case OPR_BAND: case OPR_BOR: case OPR_BXOR:
    case OPR_SHL: case OPR_SHR: {
      if (!tonumeral(v, NULL))
        luaK_exp2anyreg(fs, v);
      /* else keep numeral, which may be folded with 2nd operand */
      break;
    }
    case OPR_EQ: case OPR_NE: {
      if (!tonumeral(v, NULL))
        luaK_exp2RK(fs, v);
      /* else keep numeral, which may be an immediate operand */
      break;
    }
    case OPR_LT: case OPR_LE:
    case OPR_GT: case OPR_GE: {
      int dummy, dummy2;
      if (!isSCnumber(v, &dummy, &dummy2))
        luaK_exp2anyreg(fs, v);
      /* else keep numeral, which may be an immediate operand */
      break;
    }
    default: lua_assert(0);
  }
}
References dummy, isSCnumber(), lua_assert, luaK_dischargevars(), luaK_exp2anyreg(), luaK_exp2nextreg(), luaK_exp2RK(), luaK_goiffalse(), luaK_goiftrue(), NULL, OPR_ADD, OPR_AND, OPR_BAND, OPR_BOR, OPR_BXOR, OPR_CONCAT, OPR_DIV, OPR_EQ, OPR_GE, OPR_GT, OPR_IDIV, OPR_LE, OPR_LT, OPR_MOD, OPR_MUL, OPR_NE, OPR_OR, OPR_POW, OPR_SHL, OPR_SHR, OPR_SUB, and tonumeral().
luaK_int()
void luaK_int (FuncState * fs, int reg, lua_Integer i)
Definition at line 654 of file lua-5.4.3/src/lcode.c.
{
  if (fitsBx(i))
    luaK_codeAsBx(fs, OP_LOADI, reg, cast_int(i));
  else
    luaK_codek(fs, reg, luaK_intK(fs, i));
}
References cast_int, fitsBx(), luaK_codeAsBx, luaK_codek(), luaK_intK(), and OP_LOADI.
Referenced by discharge2reg(), and fornum().
luaK_intK()
static int luaK_intK (FuncState * fs, lua_Integer n) static
Definition at line 587 of file lua-5.4.3/src/lcode.c.
{
  TValue k, o;
  setpvalue(&k, cast_voidp(cast_sizet(n)));
  setivalue(&o, n);
  return addk(fs, &k, &o);
}
References addk(), cast_sizet, cast_voidp, setivalue, and setpvalue.
Referenced by luaK_exp2K(), and luaK_int().
luaK_isKint()
int luaK_isKint (expdesc * e)
Definition at line 1210 of file lua-5.4.3/src/lcode.c.
{
  return (e->k == VKINT && !hasjumps(e));
}
References hasjumps, expdesc::k, and VKINT.
Referenced by finishbinexpneg(), isCint(), and isSCint().
luaK_jump()
int luaK_jump (FuncState * fs)
Definition at line 198 of file lua-5.4.3/src/lcode.c.
{
  return codesJ(fs, OP_JMP, NO_JUMP, 0);
}
References codesJ(), NO_JUMP, and OP_JMP.
Referenced by condjump(), and exp2reg().
luaK_nil()
void luaK_nil (FuncState * fs, int from, int n)
Definition at line 130 of file lua-5.4.3/src/lcode.c.
{
  int l = from + n - 1;  /* last register to set nil */
  Instruction *previous = previousinstruction(fs);
  if (GET_OPCODE(*previous) == OP_LOADNIL) {  /* previous is LOADNIL? */
    int pfrom = GETARG_A(*previous);  /* get previous range */
    int pl = pfrom + GETARG_B(*previous);
    if ((pfrom <= from && from <= pl + 1) ||
        (from <= pfrom && pfrom <= l + 1)) {  /* can connect both? */
      if (pfrom < from) from = pfrom;  /* from = min(from, pfrom) */
      if (pl > l) l = pl;  /* l = max(l, pl) */
      SETARG_A(*previous, from);
      SETARG_B(*previous, l - from);
      return;
    }  /* else go through */
  }
  luaK_codeABC(fs, OP_LOADNIL, from, n - 1, 0);  /* else no optimization */
}
References GET_OPCODE, GETARG_A, GETARG_B, luaK_codeABC, OP_LOADNIL, previousinstruction(), SETARG_A, and SETARG_B.
Referenced by discharge2reg().
luaK_numberK()
static int luaK_numberK (FuncState * fs, lua_Number r) static
Definition at line 597 of file lua-5.4.3/src/lcode.c.
{
  TValue o;
  setfltvalue(&o, r);
  return addk(fs, &o, &o);  /* use number itself as key */
}
References addk(), and setfltvalue.
Referenced by luaK_exp2K(), and luaK_float().
luaK_patchlist()
void luaK_patchlist (FuncState * fs, int list, int target)
Definition at line 305 of file lua-5.4.3/src/lcode.c.
{
  lua_assert(target <= fs->pc);
  patchlistaux(fs, list, target, NO_REG, target);
}
References lua_assert, NO_REG, and patchlistaux().
Referenced by luaK_patchtohere().
luaK_patchtohere()
void luaK_patchtohere (FuncState * fs, int list)
Definition at line 311 of file lua-5.4.3/src/lcode.c.
{
  int hr = luaK_getlabel(fs);  /* mark "here" as a jump target */
  luaK_patchlist(fs, list, hr);
}
References luaK_getlabel(), and luaK_patchlist().
Referenced by exp2reg(), luaK_goiffalse(), and luaK_goiftrue().
luaK_posfix()
void luaK_posfix (FuncState * fs, BinOpr opr, expdesc * e1, expdesc * e2, int line)
Definition at line 1642 of file lua-5.4.3/src/lcode.c.
{
  luaK_dischargevars(fs, e2);
  if (foldbinop(opr) && constfolding(fs, opr + LUA_OPADD, e1, e2))
    return;  /* done by folding */
  switch (opr) {
    case OPR_AND: {
      lua_assert(e1->t == NO_JUMP);  /* list closed by 'luaK_infix' */
      luaK_concat(fs, &e2->f, e1->f);
      *e1 = *e2;
      break;
    }
    case OPR_OR: {
      lua_assert(e1->f == NO_JUMP);  /* list closed by 'luaK_infix' */
      luaK_concat(fs, &e2->t, e1->t);
      *e1 = *e2;
      break;
    }
    case OPR_CONCAT: {  /* e1 .. e2 */
      luaK_exp2nextreg(fs, e2);
      codeconcat(fs, e1, e2, line);
      break;
    }
    case OPR_ADD: case OPR_MUL: {
      codecommutative(fs, opr, e1, e2, line);
      break;
    }
    case OPR_SUB: {
      if (finishbinexpneg(fs, e1, e2, OP_ADDI, line, TM_SUB))
        break; /* coded as (r1 + -I) */
      /* ELSE */
    }  /* FALLTHROUGH */
    case OPR_DIV: case OPR_IDIV: case OPR_MOD: case OPR_POW: {
      codearith(fs, opr, e1, e2, 0, line);
      break;
    }
    case OPR_BAND: case OPR_BOR: case OPR_BXOR: {
      codebitwise(fs, opr, e1, e2, line);
      break;
    }
    case OPR_SHL: {
      if (isSCint(e1)) {
        swapexps(e1, e2);
        codebini(fs, OP_SHLI, e1, e2, 1, line, TM_SHL);  /* I << r2 */
      }
      else if (finishbinexpneg(fs, e1, e2, OP_SHRI, line, TM_SHL)) {
        /* coded as (r1 >> -I) */;
      }
      else  /* regular case (two registers) */
       codebinexpval(fs, OP_SHL, e1, e2, line);
      break;
    }
    case OPR_SHR: {
      if (isSCint(e2))
        codebini(fs, OP_SHRI, e1, e2, 0, line, TM_SHR);  /* r1 >> I */
      else  /* regular case (two registers) */
        codebinexpval(fs, OP_SHR, e1, e2, line);
      break;
    }
    case OPR_EQ: case OPR_NE: {
      codeeq(fs, opr, e1, e2);
      break;
    }
    case OPR_LT: case OPR_LE: {
      OpCode op = cast(OpCode, (opr - OPR_EQ) + OP_EQ);
      codeorder(fs, op, e1, e2);
      break;
    }
    case OPR_GT: case OPR_GE: {
      /* '(a > b)' <=> '(b < a)';  '(a >= b)' <=> '(b <= a)' */
      OpCode op = cast(OpCode, (opr - OPR_NE) + OP_EQ);
      swapexps(e1, e2);
      codeorder(fs, op, e1, e2);
      break;
    }
    default: lua_assert(0);
  }
}
References cast, codearith(), codebinexpval(), codebini(), codebitwise(), codecommutative(), codeconcat(), codeeq(), codeorder(), constfolding(), expdesc::f, finishbinexpneg(), foldbinop, isSCint(), lua_assert, LUA_OPADD, luaK_concat(), luaK_dischargevars(), luaK_exp2nextreg(), NO_JUMP, OP_ADDI, OP_EQ, OP_SHL, OP_SHLI, OP_SHR, OP_SHRI, OPR_ADD, OPR_AND, OPR_BAND, OPR_BOR, OPR_BXOR, OPR_CONCAT, OPR_DIV, OPR_EQ, OPR_GE, OPR_GT, OPR_IDIV, OPR_LE, OPR_LT, OPR_MOD, OPR_MUL, OPR_NE, OPR_OR, OPR_POW, OPR_SHL, OPR_SHR, OPR_SUB, swapexps(), expdesc::t, TM_SHL, TM_SHR, and TM_SUB.
luaK_prefix()
void luaK_prefix (FuncState * fs, UnOpr op, expdesc * e, int line)
Definition at line 1553 of file lua-5.4.3/src/lcode.c.
{
  static const expdesc ef = {VKINT, {0}, NO_JUMP, NO_JUMP};
  luaK_dischargevars(fs, e);
  switch (op) {
    case OPR_MINUS: case OPR_BNOT:  /* use 'ef' as fake 2nd operand */
      if (constfolding(fs, op + LUA_OPUNM, e, &ef))
        break;
      /* else */ /* FALLTHROUGH */
    case OPR_LEN:
      codeunexpval(fs, cast(OpCode, op + OP_UNM), e, line);
      break;
    case OPR_NOT: codenot(fs, e); break;
    default: lua_assert(0);
  }
}
References cast, codenot(), codeunexpval(), constfolding(), lua_assert, LUA_OPUNM, luaK_dischargevars(), NO_JUMP, OP_UNM, OPR_BNOT, OPR_LEN, OPR_MINUS, OPR_NOT, and VKINT.
luaK_reserveregs()
void luaK_reserveregs (FuncState * fs, int n)
Definition at line 479 of file lua-5.4.3/src/lcode.c.
{
  luaK_checkstack(fs, n);
  fs->freereg += n;
}
References FuncState::freereg, and luaK_checkstack().
Referenced by discharge2anyreg(), luaK_exp2nextreg(), luaK_self(), and luaK_setreturns().
luaK_ret()
void luaK_ret (FuncState * fs, int first, int nret)
Definition at line 206 of file lua-5.4.3/src/lcode.c.
{
  OpCode op;
  switch (nret) {
    case 0: op = OP_RETURN0; break;
    case 1: op = OP_RETURN1; break;
    default: op = OP_RETURN; break;
  }
  luaK_codeABC(fs, op, first, nret + 1, 0);
}
References luaK_codeABC, OP_RETURN, OP_RETURN0, and OP_RETURN1.
luaK_self()
void luaK_self (FuncState * fs, expdesc * e, expdesc * key)
Definition at line 1067 of file lua-5.4.3/src/lcode.c.
{
  int ereg;
  luaK_exp2anyreg(fs, e);
  ereg = e->u.info;  /* register where 'e' was placed */
  freeexp(fs, e);
  e->u.info = fs->freereg;  /* base register for op_self */
  e->k = VNONRELOC;  /* self expression has a fixed register */
  luaK_reserveregs(fs, 2);  /* function and 'self' produced by op_self */
  codeABRK(fs, OP_SELF, e->u.info, ereg, key);
  freeexp(fs, key);
}
References codeABRK(), freeexp(), FuncState::freereg, expdesc::info, expdesc::k, luaK_exp2anyreg(), luaK_reserveregs(), OP_SELF, expdesc::u, and VNONRELOC.
luaK_semerror()
l_noret luaK_semerror (LexState * ls, const char * msg)
Definition at line 45 of file lua-5.4.3/src/lcode.c.
{
  ls->t.token = 0;  /* remove "near <token>" from final message */
  luaX_syntaxerror(ls, msg);
}
References luaX_syntaxerror(), LexState::t, and Token::token.
Referenced by check_readonly(), checkrepeated(), getlocalattribute(), jumpscopeerror(), localstat(), and undefgoto().
luaK_setlist()
void luaK_setlist (FuncState * fs, int base, int nelems, int tostore)
Definition at line 1750 of file lua-5.4.3/src/lcode.c.
{
  lua_assert(tostore != 0 && tostore <= LFIELDS_PER_FLUSH);
  if (tostore == LUA_MULTRET)
    tostore = 0;
  if (nelems <= MAXARG_C)
    luaK_codeABC(fs, OP_SETLIST, base, tostore, nelems);
  else {
    int extra = nelems / (MAXARG_C + 1);
    nelems %= (MAXARG_C + 1);
    luaK_codeABCk(fs, OP_SETLIST, base, tostore, nelems, 1);
    codeextraarg(fs, extra);
  }
  fs->freereg = base + 1;  /* free registers with list values */
}
References codeextraarg(), FuncState::freereg, LFIELDS_PER_FLUSH, lua_assert, LUA_MULTRET, luaK_codeABC, luaK_codeABCk(), MAXARG_C, and OP_SETLIST.
luaK_setoneret()
void luaK_setoneret (FuncState * fs, expdesc * e)
Definition at line 736 of file lua-5.4.3/src/lcode.c.
{
  if (e->k == VCALL) {  /* expression is an open function call? */
    /* already returns 1 value */
    lua_assert(GETARG_C(getinstruction(fs, e)) == 2);
    e->k = VNONRELOC;  /* result has fixed position */
    e->u.info = GETARG_A(getinstruction(fs, e));
  }
  else if (e->k == VVARARG) {
    SETARG_C(getinstruction(fs, e), 2);
    e->k = VRELOC;  /* can relocate its simple result */
  }
}
References GETARG_A, GETARG_C, getinstruction, expdesc::info, expdesc::k, lua_assert, SETARG_C, expdesc::u, VCALL, VNONRELOC, VRELOC, and VVARARG.
Referenced by luaK_dischargevars().
luaK_setreturns()
void luaK_setreturns (FuncState * fs, expdesc * e, int nresults)
Definition at line 703 of file lua-5.4.3/src/lcode.c.
{
  Instruction *pc = &getinstruction(fs, e);
  if (e->k == VCALL)  /* expression is an open function call? */
    SETARG_C(*pc, nresults + 1);
  else {
    lua_assert(e->k == VVARARG);
    SETARG_C(*pc, nresults + 1);
    SETARG_A(*pc, fs->freereg);
    luaK_reserveregs(fs, 1);
  }
}
References FuncState::freereg, getinstruction, expdesc::k, lua_assert, luaK_reserveregs(), SETARG_A, SETARG_C, VCALL, and VVARARG.
luaK_settablesize()
void luaK_settablesize (FuncState * fs, int pc, int ra, int asize, int hsize)
Definition at line 1732 of file lua-5.4.3/src/lcode.c.
{
  Instruction *inst = &fs->f->code[pc];
  int rb = (hsize != 0) ? luaO_ceillog2(hsize) + 1 : 0;  /* hash size */
  int extra = asize / (MAXARG_C + 1);  /* higher bits of array size */
  int rc = asize % (MAXARG_C + 1);  /* lower bits of array size */
  int k = (extra > 0);  /* true iff needs extra argument */
  *inst = CREATE_ABCk(OP_NEWTABLE, ra, rb, rc, k);
  *(inst + 1) = CREATE_Ax(OP_EXTRAARG, extra);
}
References Proto::code, CREATE_ABCk, CREATE_Ax, FuncState::f, luaO_ceillog2(), MAXARG_C, OP_EXTRAARG, and OP_NEWTABLE.
Referenced by constructor().
luaK_storevar()
void luaK_storevar (FuncState * fs, expdesc * var, expdesc * ex)
Definition at line 1030 of file lua-5.4.3/src/lcode.c.
{
  switch (var->k) {
    case VLOCAL: {
      freeexp(fs, ex);
      exp2reg(fs, ex, var->u.var.ridx);  /* compute 'ex' into proper place */
      return;
    }
    case VUPVAL: {
      int e = luaK_exp2anyreg(fs, ex);
      luaK_codeABC(fs, OP_SETUPVAL, e, var->u.info, 0);
      break;
    }
    case VINDEXUP: {
      codeABRK(fs, OP_SETTABUP, var->u.ind.t, var->u.ind.idx, ex);
      break;
    }
    case VINDEXI: {
      codeABRK(fs, OP_SETI, var->u.ind.t, var->u.ind.idx, ex);
      break;
    }
    case VINDEXSTR: {
      codeABRK(fs, OP_SETFIELD, var->u.ind.t, var->u.ind.idx, ex);
      break;
    }
    case VINDEXED: {
      codeABRK(fs, OP_SETTABLE, var->u.ind.t, var->u.ind.idx, ex);
      break;
    }
    default: lua_assert(0);  /* invalid var kind to store */
  }
  freeexp(fs, ex);
}
References codeABRK(), exp2reg(), freeexp(), expdesc::idx, expdesc::ind, expdesc::info, expdesc::k, lua_assert, luaK_codeABC, luaK_exp2anyreg(), OP_SETFIELD, OP_SETI, OP_SETTABLE, OP_SETTABUP, OP_SETUPVAL, expdesc::ridx, expdesc::t, expdesc::u, expdesc::var, VINDEXED, VINDEXI, VINDEXSTR, VINDEXUP, VLOCAL, and VUPVAL.
need_value()
static int need_value (FuncState * fs, int list) static
Definition at line 880 of file lua-5.4.3/src/lcode.c.
{
  for (; list != NO_JUMP; list = getjump(fs, list)) {
    Instruction i = *getjumpcontrol(fs, list);
    if (GET_OPCODE(i) != OP_TESTSET) return 1;
  }
  return 0;  /* not found */
}
References GET_OPCODE, getjump(), getjumpcontrol(), NO_JUMP, and OP_TESTSET.
Referenced by exp2reg().
negatecondition()
static void negatecondition (FuncState * fs, expdesc * e) static
Definition at line 1083 of file lua-5.4.3/src/lcode.c.
{
  Instruction *pc = getjumpcontrol(fs, e->u.info);
  lua_assert(testTMode(GET_OPCODE(*pc)) && GET_OPCODE(*pc) != OP_TESTSET &&
                                           GET_OPCODE(*pc) != OP_TEST);
  SETARG_k(*pc, (GETARG_k(*pc) ^ 1));
}
References GET_OPCODE, GETARG_k, getjumpcontrol(), expdesc::info, lua_assert, OP_TEST, OP_TESTSET, SETARG_k, testTMode, and expdesc::u.
Referenced by codenot(), and luaK_goiftrue().
nilK()
static int nilK (FuncState * fs) static
Definition at line 627 of file lua-5.4.3/src/lcode.c.
{
  TValue k, v;
  setnilvalue(&v);
  /* cannot use nil as key; instead use table itself to represent nil */
  sethvalue(fs->ls->L, &k, fs->ls->h);
  return addk(fs, &k, &v);
}
References addk(), LexState::h, LexState::L, FuncState::ls, sethvalue, and setnilvalue.
Referenced by luaK_exp2K().
patchlistaux()
static void patchlistaux (FuncState * fs, int list, int vtarget, int reg, int dtarget) static
Definition at line 287 of file lua-5.4.3/src/lcode.c.
{
  while (list != NO_JUMP) {
    int next = getjump(fs, list);
    if (patchtestreg(fs, list, reg))
      fixjump(fs, list, vtarget);
    else
      fixjump(fs, list, dtarget);  /* jump to default target */
    list = next;
  }
}
References fixjump(), getjump(), next, NO_JUMP, and patchtestreg().
Referenced by exp2reg(), and luaK_patchlist().
patchtestreg()
static int patchtestreg (FuncState * fs, int node, int reg) static
Definition at line 258 of file lua-5.4.3/src/lcode.c.
{
  Instruction *i = getjumpcontrol(fs, node);
  if (GET_OPCODE(*i) != OP_TESTSET)
    return 0;  /* cannot patch other instructions */
  if (reg != NO_REG && reg != GETARG_B(*i))
    SETARG_A(*i, reg);
  else {
     /* no register to put value or register already has the value;
        change instruction to simple test */
    *i = CREATE_ABCk(OP_TEST, GETARG_B(*i), 0, 0, GETARG_k(*i));
  }
  return 1;
}
References CREATE_ABCk, GET_OPCODE, GETARG_B, GETARG_k, getjumpcontrol(), NO_REG, OP_TEST, OP_TESTSET, and SETARG_A.
Referenced by patchlistaux(), and removevalues().
previousinstruction()
static Instruction * previousinstruction (FuncState * fs) static
Definition at line 115 of file lua-5.4.3/src/lcode.c.
{
  static const Instruction invalidinstruction = ~(Instruction)0;
  if (fs->pc > fs->lasttarget)
    return &fs->f->code[fs->pc - 1];  /* previous instruction */
  else
    return cast(Instruction*, &invalidinstruction);
}
References cast, Proto::code, FuncState::f, FuncState::lasttarget, and FuncState::pc.
Referenced by codeconcat(), and luaK_nil().
removelastinstruction()
static void removelastinstruction (FuncState * fs) static
Definition at line 371 of file lua-5.4.3/src/lcode.c.
{
  removelastlineinfo(fs);
  fs->pc--;
}
References FuncState::pc, and removelastlineinfo().
Referenced by jumponcond().
removelastlineinfo()
static void removelastlineinfo (FuncState * fs) static
Definition at line 352 of file lua-5.4.3/src/lcode.c.
{
  Proto *f = fs->f;
  int pc = fs->pc - 1;  /* last instruction coded */
  if (f->lineinfo[pc] != ABSLINEINFO) {  /* relative line info? */
    fs->previousline -= f->lineinfo[pc];  /* correct last line saved */
    fs->iwthabs--;  /* undo previous increment */
  }
  else {  /* absolute line information */
    lua_assert(f->abslineinfo[fs->nabslineinfo - 1].pc == pc);
    fs->nabslineinfo--;  /* remove it */
    fs->iwthabs = MAXIWTHABS + 1;  /* force next line info to be absolute */
  }
}
References ABSLINEINFO, Proto::abslineinfo, FuncState::f, FuncState::iwthabs, Proto::lineinfo, lua_assert, MAXIWTHABS, FuncState::nabslineinfo, FuncState::pc, AbsLineInfo::pc, and FuncState::previousline.
Referenced by luaK_fixline(), and removelastinstruction().
removevalues()
static void removevalues (FuncState * fs, int list) static
Definition at line 276 of file lua-5.4.3/src/lcode.c.
{
  for (; list != NO_JUMP; list = getjump(fs, list))
      patchtestreg(fs, list, NO_REG);
}
References getjump(), NO_JUMP, NO_REG, and patchtestreg().
Referenced by codenot().
savelineinfo()
static void savelineinfo (FuncState * fs, Proto * f, int line) static
Definition at line 328 of file lua-5.4.3/src/lcode.c.
{
  int linedif = line - fs->previousline;
  int pc = fs->pc - 1;  /* last instruction coded */
  if (abs(linedif) >= LIMLINEDIFF || fs->iwthabs++ >= MAXIWTHABS) {
    luaM_growvector(fs->ls->L, f->abslineinfo, fs->nabslineinfo,
                    f->sizeabslineinfo, AbsLineInfo, MAX_INT, "lines");
    f->abslineinfo[fs->nabslineinfo].pc = pc;
    f->abslineinfo[fs->nabslineinfo++].line = line;
    linedif = ABSLINEINFO;  /* signal that there is absolute information */
    fs->iwthabs = 1;  /* restart counter */
  }
  luaM_growvector(fs->ls->L, f->lineinfo, pc, f->sizelineinfo, ls_byte,
                  MAX_INT, "opcodes");
  f->lineinfo[pc] = linedif;
  fs->previousline = line;  /* last line saved */
}
References ABSLINEINFO, Proto::abslineinfo, FuncState::iwthabs, LexState::L, LIMLINEDIFF, AbsLineInfo::line, Proto::lineinfo, FuncState::ls, luaM_growvector, MAX_INT, MAXIWTHABS, FuncState::nabslineinfo, FuncState::pc, AbsLineInfo::pc, FuncState::previousline, Proto::sizeabslineinfo, and Proto::sizelineinfo.
Referenced by luaK_code(), and luaK_fixline().
str2K()
static void str2K (FuncState * fs, expdesc * e) static
Definition at line 719 of file lua-5.4.3/src/lcode.c.
{
  lua_assert(e->k == VKSTR);
  e->u.info = stringK(fs, e->u.strval);
  e->k = VK;
}
References expdesc::info, expdesc::k, lua_assert, stringK(), expdesc::strval, expdesc::u, VK, and VKSTR.
Referenced by discharge2reg(), and luaK_indexed().
stringK()
static int stringK (FuncState * fs, TString * s) static
Definition at line 574 of file lua-5.4.3/src/lcode.c.
{
  TValue o;
  setsvalue(fs->ls->L, &o, s);
  return addk(fs, &o, &o);  /* use string itself as key */
}
References addk(), LexState::L, FuncState::ls, s, and setsvalue.
Referenced by luaK_exp2K(), and str2K().
swapexps()
static void swapexps (expdesc * e1, expdesc * e2) static
Definition at line 1417 of file lua-5.4.3/src/lcode.c.
{
  expdesc temp = *e1; *e1 = *e2; *e2 = temp;  /* swap 'e1' and 'e2' */
}
Referenced by codearith(), codebitwise(), codecommutative(), codeeq(), and luaK_posfix().
tonumeral()
static int tonumeral (const expdesc * e, TValue * v) static
Definition at line 55 of file lua-5.4.3/src/lcode.c.
{
  if (hasjumps(e))
    return 0;  /* not a numeral */
  switch (e->k) {
    case VKINT:
      if (v) setivalue(v, e->u.ival);
      return 1;
    case VKFLT:
      if (v) setfltvalue(v, e->u.nval);
      return 1;
    default: return 0;
  }
}
References hasjumps, expdesc::ival, expdesc::k, expdesc::nval, setfltvalue, setivalue, expdesc::u, VKFLT, and VKINT.
Referenced by codearith(), codecommutative(), constfolding(), luaK_exp2const(), and luaK_infix().
validop()
static int validop (int op, TValue * v1, TValue * v2) static
Definition at line 1296 of file lua-5.4.3/src/lcode.c.
{
  switch (op) {
    case LUA_OPBAND: case LUA_OPBOR: case LUA_OPBXOR:
    case LUA_OPSHL: case LUA_OPSHR: case LUA_OPBNOT: {  /* conversion errors */
      lua_Integer i;
      return (luaV_tointegerns(v1, &i, LUA_FLOORN2I) &&
              luaV_tointegerns(v2, &i, LUA_FLOORN2I));
    }
    case LUA_OPDIV: case LUA_OPIDIV: case LUA_OPMOD:  /* division by 0 */
      return (nvalue(v2) != 0);
    default: return 1;  /* everything else is valid */
  }
}
References LUA_FLOORN2I, LUA_OPBAND, LUA_OPBNOT, LUA_OPBOR, LUA_OPBXOR, LUA_OPDIV, LUA_OPIDIV, LUA_OPMOD, LUA_OPSHL, LUA_OPSHR, luaV_tointegerns(), and nvalue.
Referenced by constfolding().