Github User Fetcher: liolib.c File Reference
liolib.c File Reference
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define liolib_c
#define LUA_LIB
#define IO_INPUT 1
#define IO_OUTPUT 2
#define tofilep(L) ((FILE **)luaL_checkudata(L, 1, LUA_FILEHANDLE))
Functions
static int pushresult (lua_State *L, int i, const char *filename)
static void fileerror (lua_State *L, int arg, const char *filename)
static int io_type (lua_State *L)
static FILE * tofile (lua_State *L)
static FILE ** newfile (lua_State *L)
static int io_noclose (lua_State *L)
static int io_pclose (lua_State *L)
static int io_fclose (lua_State *L)
static int aux_close (lua_State *L)
static int io_close (lua_State *L)
static int io_gc (lua_State *L)
static int io_tostring (lua_State *L)
static int io_open (lua_State *L)
static int io_popen (lua_State *L)
static int io_tmpfile (lua_State *L)
static FILE * getiofile (lua_State *L, int findex)
static int g_iofile (lua_State *L, int f, const char *mode)
static int io_input (lua_State *L)
static int io_output (lua_State *L)
static int io_readline (lua_State *L)
static void aux_lines (lua_State *L, int idx, int toclose)
static int f_lines (lua_State *L)
static int io_lines (lua_State *L)
static int read_number (lua_State *L, FILE *f)
static int test_eof (lua_State *L, FILE *f)
static int read_line (lua_State *L, FILE *f)
static int read_chars (lua_State *L, FILE *f, size_t n)
static int g_read (lua_State *L, FILE *f, int first)
static int io_read (lua_State *L)
static int f_read (lua_State *L)
static int g_write (lua_State *L, FILE *f, int arg)
static int io_write (lua_State *L)
static int f_write (lua_State *L)
static int f_seek (lua_State *L)
static int f_setvbuf (lua_State *L)
static int io_flush (lua_State *L)
static int f_flush (lua_State *L)
static void createmeta (lua_State *L)
static void createstdfile (lua_State *L, FILE *f, int k, const char *fname)
static void newfenv (lua_State *L, lua_CFunction cls)
LUALIB_API int luaopen_io (lua_State *L)
Variables
static const char *const fnames [] = {"input", "output"}
static const luaL_Reg iolib []
static const luaL_Reg flib []
Macro Definition Documentation
IO_INPUT
#define IO_INPUT 1
Definition at line 23 of file lua-5.1.5/src/liolib.c.
Referenced by io_input(), io_lines(), io_read(), and luaopen_io().
IO_OUTPUT
#define IO_OUTPUT 2
Definition at line 24 of file lua-5.1.5/src/liolib.c.
Referenced by io_close(), io_flush(), io_output(), io_write(), and luaopen_io().
liolib_c
#define liolib_c
Definition at line 13 of file lua-5.1.5/src/liolib.c.
LUA_LIB
#define LUA_LIB
Definition at line 14 of file lua-5.1.5/src/liolib.c.
tofilep
#define tofilep (L) ((FILE **)luaL_checkudata(L, 1, LUA_FILEHANDLE))
Definition at line 54 of file lua-5.1.5/src/liolib.c.
Referenced by io_fclose(), io_gc(), io_pclose(), io_tostring(), and tofile().
Function Documentation
aux_close()
static int aux_close (lua_State * L) static
Definition at line 127 of file lua-5.1.5/src/liolib.c.
{
  lua_getfenv(L, 1);
  lua_getfield(L, -1, "__close");
  return (lua_tocfunction(L, -1))(L);
}
References lua_getfenv(), lua_getfield(), and lua_tocfunction().
Referenced by io_close(), io_gc(), and io_readline().
aux_lines()
static void aux_lines (lua_State * L, int idx, int toclose) static
Definition at line 234 of file lua-5.1.5/src/liolib.c.
{
  lua_pushvalue(L, idx);
  lua_pushboolean(L, toclose);  /* close/not close file when finished */
  lua_pushcclosure(L, io_readline, 2);
}
References io_readline(), lua_pushboolean(), lua_pushcclosure(), and lua_pushvalue().
Referenced by f_lines(), and io_lines().
createmeta()
static void createmeta (lua_State * L) static
Definition at line 510 of file lua-5.1.5/src/liolib.c.
{
  luaL_newmetatable(L, LUA_FILEHANDLE);  /* create metatable for file handles */
  lua_pushvalue(L, -1);  /* push metatable */
  lua_setfield(L, -2, "__index");  /* metatable.__index = metatable */
  luaL_register(L, NULL, flib);  /* file methods */
}
References flib, LUA_FILEHANDLE, lua_pushvalue(), lua_setfield(), luaL_newmetatable(), luaL_register(), and NULL.
Referenced by luaopen_io().
createstdfile()
static void createstdfile (lua_State * L, FILE * f, int k, const char * fname) static
Definition at line 518 of file lua-5.1.5/src/liolib.c.
{
  *newfile(L) = f;
  if (k > 0) {
    lua_pushvalue(L, -1);
    lua_rawseti(L, LUA_ENVIRONINDEX, k);
  }
  lua_pushvalue(L, -2);  /* copy environment */
  lua_setfenv(L, -2);  /* set it */
  lua_setfield(L, -3, fname);
}
References LUA_ENVIRONINDEX, lua_pushvalue(), lua_rawseti(), lua_setfenv(), lua_setfield(), and newfile().
Referenced by luaopen_io().
f_flush()
static int f_flush (lua_State * L) static
Definition at line 475 of file lua-5.1.5/src/liolib.c.
{
  return pushresult(L, fflush(tofile(L)) == 0, NULL);
}
References NULL, pushresult(), and tofile().
f_lines()
static int f_lines (lua_State * L) static
Definition at line 241 of file lua-5.1.5/src/liolib.c.
{
  tofile(L);  /* check that it's a valid file handle */
  aux_lines(L, 1, 0);
  return 1;
}
References aux_lines(), and tofile().
Referenced by io_lines().
f_read()
static int f_read (lua_State * L) static
Definition at line 386 of file lua-5.1.5/src/liolib.c.
{
  return g_read(L, tofile(L), 2);
}
References g_read(), and tofile().
f_seek()
static int f_seek (lua_State * L) static
Definition at line 442 of file lua-5.1.5/src/liolib.c.
{
  static const int mode[] = {SEEK_SET, SEEK_CUR, SEEK_END};
  static const char *const modenames[] = {"set", "cur", "end", NULL};
  FILE *f = tofile(L);
  int op = luaL_checkoption(L, 2, "cur", modenames);
  long offset = luaL_optlong(L, 3, 0);
  op = fseek(f, offset, mode[op]);
  if (op)
    return pushresult(L, 0, NULL);  /* error */
  else {
    lua_pushinteger(L, ftell(f));
    return 1;
  }
}
References lua_pushinteger(), luaL_checkoption(), luaL_optlong, NULL, pushresult(), and tofile().
f_setvbuf()
static int f_setvbuf (lua_State * L) static
Definition at line 458 of file lua-5.1.5/src/liolib.c.
{
  static const int mode[] = {_IONBF, _IOFBF, _IOLBF};
  static const char *const modenames[] = {"no", "full", "line", NULL};
  FILE *f = tofile(L);
  int op = luaL_checkoption(L, 2, NULL, modenames);
  lua_Integer sz = luaL_optinteger(L, 3, LUAL_BUFFERSIZE);
  int res = setvbuf(f, NULL, mode[op], sz);
  return pushresult(L, res == 0, NULL);
}
References LUAL_BUFFERSIZE, luaL_checkoption(), luaL_optinteger(), NULL, pushresult(), and tofile().
f_write()
static int f_write (lua_State * L) static
Definition at line 437 of file lua-5.1.5/src/liolib.c.
{
  return g_write(L, tofile(L), 2);
}
References g_write(), and tofile().
fileerror()
static void fileerror (lua_State * L, int arg, const char * filename) static
Definition at line 48 of file lua-5.1.5/src/liolib.c.
{
  lua_pushfstring(L, "%s: %s", filename, strerror(errno));
  luaL_argerror(L, arg, lua_tostring(L, -1));
}
References arg, lua_pushfstring(), lua_tostring, and luaL_argerror().
Referenced by g_iofile(), and io_lines().
g_iofile()
static int g_iofile (lua_State * L, int f, const char * mode) static
Definition at line 200 of file lua-5.1.5/src/liolib.c.
{
  if (!lua_isnoneornil(L, 1)) {
    const char *filename = lua_tostring(L, 1);
    if (filename) {
      FILE **pf = newfile(L);
      *pf = fopen(filename, mode);
      if (*pf == NULL)
        fileerror(L, 1, filename);
    }
    else {
      tofile(L);  /* check that it's a valid file handle */
      lua_pushvalue(L, 1);
    }
    lua_rawseti(L, LUA_ENVIRONINDEX, f);
  }
  /* return current value */
  lua_rawgeti(L, LUA_ENVIRONINDEX, f);
  return 1;
}
References fileerror(), LUA_ENVIRONINDEX, lua_isnoneornil, lua_pushvalue(), lua_rawgeti(), lua_rawseti(), lua_tostring, newfile(), NULL, and tofile().
Referenced by io_input(), and io_output().
g_read()
static int g_read (lua_State * L, FILE * f, int first) static
Definition at line 334 of file lua-5.1.5/src/liolib.c.
{
  int nargs = lua_gettop(L) - 1;
  int success;
  int n;
  clearerr(f);
  if (nargs == 0) {  /* no arguments? */
    success = read_line(L, f);
    n = first+1;  /* to return 1 result */
  }
  else {  /* ensure stack space for all results and for auxlib's buffer */
    luaL_checkstack(L, nargs+LUA_MINSTACK, "too many arguments");
    success = 1;
    for (n = first; nargs-- && success; n++) {
      if (lua_type(L, n) == LUA_TNUMBER) {
        size_t l = (size_t)lua_tointeger(L, n);
        success = (l == 0) ? test_eof(L, f) : read_chars(L, f, l);
      }
      else {
        const char *p = lua_tostring(L, n);
        luaL_argcheck(L, p && p[0] == '*', n, "invalid option");
        switch (p[1]) {
          case 'n':  /* number */
            success = read_number(L, f);
            break;
          case 'l':  /* line */
            success = read_line(L, f);
            break;
          case 'a':  /* file */
            read_chars(L, f, ~((size_t)0));  /* read MAX_SIZE_T chars */
            success = 1; /* always success */
            break;
          default:
            return luaL_argerror(L, n, "invalid format");
        }
      }
    }
  }
  if (ferror(f))
    return pushresult(L, 0, NULL);
  if (!success) {
    lua_pop(L, 1);  /* remove last result */
    lua_pushnil(L);  /* push nil instead */
  }
  return n - first;
}
References lua_gettop(), LUA_MINSTACK, lua_pop, lua_pushnil(), LUA_TNUMBER, lua_tointeger, lua_tostring, lua_type(), luaL_argcheck, luaL_argerror(), luaL_checkstack(), NULL, pushresult(), read_chars(), read_line(), read_number(), and test_eof().
Referenced by f_read(), and io_read().
g_write()
static int g_write (lua_State * L, FILE * f, int arg) static
Definition at line 413 of file lua-5.1.5/src/liolib.c.
{
  int nargs = lua_gettop(L) - 1;
  int status = 1;
  for (; nargs--; arg++) {
    if (lua_type(L, arg) == LUA_TNUMBER) {
      /* optimization: could be done exactly as for strings */
      status = status &&
          fprintf(f, LUA_NUMBER_FMT, lua_tonumber(L, arg)) > 0;
    }
    else {
      size_t l;
      const char *s = luaL_checklstring(L, arg, &l);
      status = status && (fwrite(s, sizeof(char), l, f) == l);
    }
  }
  return pushresult(L, status, NULL);
}
References arg, fwrite(), lua_gettop(), LUA_NUMBER_FMT, LUA_TNUMBER, lua_tonumber, lua_type(), luaL_checklstring(), NULL, pushresult(), and s.
Referenced by f_write(), and io_write().
getiofile()
static FILE * getiofile (lua_State * L, int findex) static
Definition at line 190 of file lua-5.1.5/src/liolib.c.
{
  FILE *f;
  lua_rawgeti(L, LUA_ENVIRONINDEX, findex);
  f = *(FILE **)lua_touserdata(L, -1);
  if (f == NULL)
    luaL_error(L, "standard %s file is closed", fnames[findex - 1]);
  return f;
}
References fnames, LUA_ENVIRONINDEX, lua_rawgeti(), lua_touserdata(), luaL_error(), and NULL.
Referenced by io_flush(), io_read(), and io_write().
io_close()
static int io_close (lua_State * L) static
Definition at line 134 of file lua-5.1.5/src/liolib.c.
{
  if (lua_isnone(L, 1))
    lua_rawgeti(L, LUA_ENVIRONINDEX, IO_OUTPUT);
  tofile(L);  /* make sure argument is a file */
  return aux_close(L);
}
References aux_close(), IO_OUTPUT, LUA_ENVIRONINDEX, lua_isnone, lua_rawgeti(), and tofile().
io_fclose()
static int io_fclose (lua_State * L) static
Definition at line 119 of file lua-5.1.5/src/liolib.c.
{
  FILE **p = tofilep(L);
  int ok = (fclose(*p) == 0);
  *p = NULL;
  return pushresult(L, ok, NULL);
}
References NULL, pushresult(), and tofilep.
Referenced by luaopen_io().
io_flush()
static int io_flush (lua_State * L) static
Definition at line 470 of file lua-5.1.5/src/liolib.c.
{
  return pushresult(L, fflush(getiofile(L, IO_OUTPUT)) == 0, NULL);
}
References getiofile(), IO_OUTPUT, NULL, and pushresult().
io_gc()
static int io_gc (lua_State * L) static
Definition at line 142 of file lua-5.1.5/src/liolib.c.
{
  FILE *f = *tofilep(L);
  /* ignore closed files */
  if (f != NULL)
    aux_close(L);
  return 0;
}
References aux_close(), NULL, and tofilep.
io_input()
static int io_input (lua_State * L) static
Definition at line 221 of file lua-5.1.5/src/liolib.c.
{
  return g_iofile(L, IO_INPUT, "r");
}
References g_iofile(), and IO_INPUT.
io_lines()
static int io_lines (lua_State * L) static
Definition at line 248 of file lua-5.1.5/src/liolib.c.
{
  if (lua_isnoneornil(L, 1)) {  /* no arguments? */
    /* will iterate over default input */
    lua_rawgeti(L, LUA_ENVIRONINDEX, IO_INPUT);
    return f_lines(L);
  }
  else {
    const char *filename = luaL_checkstring(L, 1);
    FILE **pf = newfile(L);
    *pf = fopen(filename, "r");
    if (*pf == NULL)
      fileerror(L, 1, filename);
    aux_lines(L, lua_gettop(L), 1);
    return 1;
  }
}
References aux_lines(), f_lines(), fileerror(), IO_INPUT, LUA_ENVIRONINDEX, lua_gettop(), lua_isnoneornil, lua_rawgeti(), luaL_checkstring, newfile(), and NULL.
io_noclose()
static int io_noclose (lua_State * L) static
Definition at line 98 of file lua-5.1.5/src/liolib.c.
{
  lua_pushnil(L);
  lua_pushliteral(L, "cannot close standard file");
  return 2;
}
References lua_pushliteral, and lua_pushnil().
Referenced by luaopen_io().
io_open()
static int io_open (lua_State * L) static
Definition at line 161 of file lua-5.1.5/src/liolib.c.
{
  const char *filename = luaL_checkstring(L, 1);
  const char *mode = luaL_optstring(L, 2, "r");
  FILE **pf = newfile(L);
  *pf = fopen(filename, mode);
  return (*pf == NULL) ? pushresult(L, 0, filename) : 1;
}
References luaL_checkstring, luaL_optstring, newfile(), NULL, and pushresult().
io_output()
static int io_output (lua_State * L) static
Definition at line 226 of file lua-5.1.5/src/liolib.c.
{
  return g_iofile(L, IO_OUTPUT, "w");
}
References g_iofile(), and IO_OUTPUT.
io_pclose()
static int io_pclose (lua_State * L) static
Definition at line 108 of file lua-5.1.5/src/liolib.c.
{
  FILE **p = tofilep(L);
  int ok = lua_pclose(L, *p);
  *p = NULL;
  return pushresult(L, ok, NULL);
}
References lua_pclose, NULL, pushresult(), and tofilep.
Referenced by luaopen_io().
io_popen()
static int io_popen (lua_State * L) static
Definition at line 174 of file lua-5.1.5/src/liolib.c.
{
  const char *filename = luaL_checkstring(L, 1);
  const char *mode = luaL_optstring(L, 2, "r");
  FILE **pf = newfile(L);
  *pf = lua_popen(L, filename, mode);
  return (*pf == NULL) ? pushresult(L, 0, filename) : 1;
}
References lua_popen, luaL_checkstring, luaL_optstring, newfile(), NULL, and pushresult().
io_read()
static int io_read (lua_State * L) static
Definition at line 381 of file lua-5.1.5/src/liolib.c.
{
  return g_read(L, getiofile(L, IO_INPUT), 1);
}
References g_read(), getiofile(), and IO_INPUT.
io_readline()
static int io_readline (lua_State * L) static
Definition at line 391 of file lua-5.1.5/src/liolib.c.
{
  FILE *f = *(FILE **)lua_touserdata(L, lua_upvalueindex(1));
  int sucess;
  if (f == NULL)  /* file is already closed? */
    luaL_error(L, "file is already closed");
  sucess = read_line(L, f);
  if (ferror(f))
    return luaL_error(L, "%s", strerror(errno));
  if (sucess) return 1;
  else {  /* EOF */
    if (lua_toboolean(L, lua_upvalueindex(2))) {  /* generator created file? */
      lua_settop(L, 0);
      lua_pushvalue(L, lua_upvalueindex(1));
      aux_close(L);  /* close it */
    }
    return 0;
  }
}
References aux_close(), lua_pushvalue(), lua_settop(), lua_toboolean(), lua_touserdata(), lua_upvalueindex, luaL_error(), NULL, and read_line().
Referenced by aux_lines().
io_tmpfile()
static int io_tmpfile (lua_State * L) static
Definition at line 183 of file lua-5.1.5/src/liolib.c.
{
  FILE **pf = newfile(L);
  *pf = tmpfile();
  return (*pf == NULL) ? pushresult(L, 0, NULL) : 1;
}
References newfile(), NULL, and pushresult().
io_tostring()
static int io_tostring (lua_State * L) static
Definition at line 151 of file lua-5.1.5/src/liolib.c.
{
  FILE *f = *tofilep(L);
  if (f == NULL)
    lua_pushliteral(L, "file (closed)");
  else
    lua_pushfstring(L, "file (%p)", f);
  return 1;
}
References lua_pushfstring(), lua_pushliteral, NULL, and tofilep.
io_type()
static int io_type (lua_State * L) static
Definition at line 57 of file lua-5.1.5/src/liolib.c.
{
  void *ud;
  luaL_checkany(L, 1);
  ud = lua_touserdata(L, 1);
  lua_getfield(L, LUA_REGISTRYINDEX, LUA_FILEHANDLE);
  if (ud == NULL || !lua_getmetatable(L, 1) || !lua_rawequal(L, -2, -1))
    lua_pushnil(L);  /* not a file */
  else if (*((FILE **)ud) == NULL)
    lua_pushliteral(L, "closed file");
  else
    lua_pushliteral(L, "file");
  return 1;
}
References LUA_FILEHANDLE, lua_getfield(), lua_getmetatable(), lua_pushliteral, lua_pushnil(), lua_rawequal(), LUA_REGISTRYINDEX, lua_touserdata(), luaL_checkany(), and NULL.
io_write()
static int io_write (lua_State * L) static
Definition at line 432 of file lua-5.1.5/src/liolib.c.
{
  return g_write(L, getiofile(L, IO_OUTPUT), 1);
}
References g_write(), getiofile(), and IO_OUTPUT.
luaopen_io()
LUALIB_API int luaopen_io (lua_State * L)
Definition at line 537 of file lua-5.1.5/src/liolib.c.
{
  createmeta(L);
  /* create (private) environment (with fields IO_INPUT, IO_OUTPUT, __close) */
  newfenv(L, io_fclose);
  lua_replace(L, LUA_ENVIRONINDEX);
  /* open library */
  luaL_register(L, LUA_IOLIBNAME, iolib);
  /* create (and set) default files */
  newfenv(L, io_noclose);  /* close function for default files */
  createstdfile(L, stdin, IO_INPUT, "stdin");
  createstdfile(L, stdout, IO_OUTPUT, "stdout");
  createstdfile(L, stderr, 0, "stderr");
  lua_pop(L, 1);  /* pop environment for default files */
  lua_getfield(L, -1, "popen");
  newfenv(L, io_pclose);  /* create environment for 'popen' */
  lua_setfenv(L, -2);  /* set fenv for 'popen' */
  lua_pop(L, 1);  /* pop 'popen' */
  return 1;
}
References createmeta(), createstdfile(), io_fclose(), IO_INPUT, io_noclose(), IO_OUTPUT, io_pclose(), iolib, LUA_ENVIRONINDEX, lua_getfield(), LUA_IOLIBNAME, lua_pop, lua_replace, lua_setfenv(), luaL_register(), and newfenv().
newfenv()
static void newfenv (lua_State * L, lua_CFunction cls) static
Definition at line 530 of file lua-5.1.5/src/liolib.c.
{
  lua_createtable(L, 0, 1);
  lua_pushcfunction(L, cls);
  lua_setfield(L, -2, "__close");
}
References lua_createtable(), lua_pushcfunction, and lua_setfield().
Referenced by luaopen_io().
newfile()
static FILE ** newfile (lua_State * L) static
Definition at line 86 of file lua-5.1.5/src/liolib.c.
{
  FILE **pf = (FILE **)lua_newuserdata(L, sizeof(FILE *));
  *pf = NULL;  /* file handle is currently `closed' */
  luaL_getmetatable(L, LUA_FILEHANDLE);
  lua_setmetatable(L, -2);
  return pf;
}
References LUA_FILEHANDLE, lua_newuserdata, lua_setmetatable(), luaL_getmetatable, and NULL.
Referenced by createstdfile(), g_iofile(), io_lines(), io_open(), io_popen(), and io_tmpfile().
pushresult()
static int pushresult (lua_State * L, int i, const char * filename) static
Definition at line 30 of file lua-5.1.5/src/liolib.c.
{
  int en = errno;  /* calls to Lua API may change this value */
  if (i) {
    lua_pushboolean(L, 1);
    return 1;
  }
  else {
    lua_pushnil(L);
    if (filename)
      lua_pushfstring(L, "%s: %s", filename, strerror(en));
    else
      lua_pushfstring(L, "%s", strerror(en));
    lua_pushinteger(L, en);
    return 3;
  }
}
References lua_pushboolean(), lua_pushfstring(), lua_pushinteger(), and lua_pushnil().
Referenced by f_flush(), f_seek(), f_setvbuf(), g_read(), g_write(), io_fclose(), io_flush(), io_open(), io_pclose(), io_popen(), and io_tmpfile().
read_chars()
static int read_chars (lua_State * L, FILE * f, size_t n) static
Definition at line 316 of file lua-5.1.5/src/liolib.c.
{
  size_t rlen;  /* how much to read */
  size_t nr;  /* number of chars actually read */
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  rlen = LUAL_BUFFERSIZE;  /* try to read that much each time */
  do {
    char *p = luaL_prepbuffer(&b);
    if (rlen > n) rlen = n;  /* cannot read more than asked */
    nr = fread(p, sizeof(char), rlen, f);
    luaL_addsize(&b, nr);
    n -= nr;  /* still have to read `n' chars */
  } while (n > 0 && nr == rlen);  /* until end of count or eof */
  luaL_pushresult(&b);  /* close buffer */
  return (n == 0 || lua_objlen(L, -1) > 0);
}
References fread(), lua_objlen(), luaL_addsize, LUAL_BUFFERSIZE, luaL_buffinit(), luaL_prepbuffer, and luaL_pushresult().
Referenced by g_read().
read_line()
static int read_line (lua_State * L, FILE * f) static
Definition at line 294 of file lua-5.1.5/src/liolib.c.
{
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  for (;;) {
    size_t l;
    char *p = luaL_prepbuffer(&b);
    if (fgets(p, LUAL_BUFFERSIZE, f) == NULL) {  /* eof? */
      luaL_pushresult(&b);  /* close buffer */
      return (lua_objlen(L, -1) > 0);  /* check whether read something */
    }
    l = strlen(p);
    if (l == 0 || p[l-1] != '\n')
      luaL_addsize(&b, l);
    else {
      luaL_addsize(&b, l - 1);  /* do not include `eol' */
      luaL_pushresult(&b);  /* close buffer */
      return 1;  /* read at least an `eol' */
    }
  }
}
References lua_objlen(), luaL_addsize, LUAL_BUFFERSIZE, luaL_buffinit(), luaL_prepbuffer, luaL_pushresult(), and NULL.
Referenced by g_read(), and io_readline().
read_number()
static int read_number (lua_State * L, FILE * f) static
Definition at line 273 of file lua-5.1.5/src/liolib.c.
{
  lua_Number d;
  if (fscanf(f, LUA_NUMBER_SCAN, &d) == 1) {
    lua_pushnumber(L, d);
    return 1;
  }
  else {
    lua_pushnil(L);  /* "result" to be removed */
    return 0;  /* read fails */
  }
}
References LUA_NUMBER_SCAN, lua_pushnil(), and lua_pushnumber().
Referenced by g_read().
test_eof()
static int test_eof (lua_State * L, FILE * f) static
Definition at line 286 of file lua-5.1.5/src/liolib.c.
{
  int c = getc(f);
  ungetc(c, f);
  lua_pushlstring(L, NULL, 0);
  return (c != EOF);
}
References lua_pushlstring(), and NULL.
Referenced by g_read().
tofile()
static FILE * tofile (lua_State * L) static
Definition at line 72 of file lua-5.1.5/src/liolib.c.
{
  FILE **f = tofilep(L);
  if (*f == NULL)
    luaL_error(L, "attempt to use a closed file");
  return *f;
}
References luaL_error(), NULL, and tofilep.
Referenced by f_flush(), f_lines(), f_read(), f_seek(), f_setvbuf(), f_write(), g_iofile(), and io_close().
Variable Documentation
flib
const luaL_Reg flib[] static
Initial value:
= {
  {"close", io_close},
  {"flush", f_flush},
  {"lines", f_lines},
  {"read", f_read},
  {"seek", f_seek},
  {"setvbuf", f_setvbuf},
  {"write", f_write},
  {"__gc", io_gc},
  {"__tostring", io_tostring},
  {NULL, NULL}
}
Definition at line 496 of file lua-5.1.5/src/liolib.c.
{
  {"close", io_close},
  {"flush", f_flush},
  {"lines", f_lines},
  {"read", f_read},
  {"seek", f_seek},
  {"setvbuf", f_setvbuf},
  {"write", f_write},
  {"__gc", io_gc},
  {"__tostring", io_tostring},
  {NULL, NULL}
};
Referenced by createmeta().
fnames
const char* const fnames[] = {"input", "output"} static
Definition at line 27 of file lua-5.1.5/src/liolib.c.
{"input", "output"};
Referenced by getiofile().
iolib
const luaL_Reg iolib[] static
Initial value:
= {
  {"close", io_close},
  {"flush", io_flush},
  {"input", io_input},
  {"lines", io_lines},
  {"open", io_open},
  {"output", io_output},
  {"popen", io_popen},
  {"read", io_read},
  {"tmpfile", io_tmpfile},
  {"type", io_type},
  {"write", io_write},
  {NULL, NULL}
}
Definition at line 480 of file lua-5.1.5/src/liolib.c.
{
  {"close", io_close},
  {"flush", io_flush},
  {"input", io_input},
  {"lines", io_lines},
  {"open", io_open},
  {"output", io_output},
  {"popen", io_popen},
  {"read", io_read},
  {"tmpfile", io_tmpfile},
  {"type", io_type},
  {"write", io_write},
  {NULL, NULL}
};
Referenced by luaopen_io().