Github User Fetcher: ltable.h File Reference
ltable.h File Reference
#include "lobject.h"
Macros
#define gnode(t, i) (&(t)->node[i])
#define gval(n) (&(n)->i_val)
#define gnext(n) ((n)->i_key.nk.next)
#define gkey(n) cast(const TValue*, (&(n)->i_key.tvk))
#define wgkey(n) (&(n)->i_key.nk)
#define invalidateTMcache(t) ((t)->flags = 0)
#define isdummy(t) ((t)->lastfree == NULL)
#define allocsizenode(t) (isdummy(t) ? 0 : sizenode(t))
#define keyfromval(v) (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
Functions
LUAI_FUNC const TValue * luaH_getint (Table *t, lua_Integer key)
LUAI_FUNC void luaH_setint (lua_State *L, Table *t, lua_Integer key, TValue *value)
LUAI_FUNC const TValue * luaH_getshortstr (Table *t, TString *key)
LUAI_FUNC const TValue * luaH_getstr (Table *t, TString *key)
LUAI_FUNC const TValue * luaH_get (Table *t, const TValue *key)
LUAI_FUNC TValue * luaH_newkey (lua_State *L, Table *t, const TValue *key)
LUAI_FUNC TValue * luaH_set (lua_State *L, Table *t, const TValue *key)
LUAI_FUNC Table * luaH_new (lua_State *L)
LUAI_FUNC void luaH_resize (lua_State *L, Table *t, unsigned int nasize, unsigned int nhsize)
LUAI_FUNC void luaH_resizearray (lua_State *L, Table *t, unsigned int nasize)
LUAI_FUNC void luaH_free (lua_State *L, Table *t)
LUAI_FUNC int luaH_next (lua_State *L, Table *t, StkId key)
LUAI_FUNC lua_Unsigned luaH_getn (Table *t)
Macro Definition Documentation
allocsizenode
#define allocsizenode (t) (isdummy(t) ? 0 : sizenode(t))
Definition at line 35 of file lua-5.3.6/src/ltable.h.
Referenced by luaH_resize(), luaH_resizearray(), traversetable(), and traversetable().
gkey
#define gkey (n) cast(const TValue*, (&(n)->i_key.tvk))
Definition at line 19 of file lua-5.3.6/src/ltable.h.
gnext
#define gnext (n) ((n)->i_key.nk.next)
Definition at line 15 of file lua-5.3.6/src/ltable.h.
gnode
#define gnode (t, i) (&(t)->node[i])
Definition at line 13 of file lua-5.3.6/src/ltable.h.
gval
#define gval (n) (&(n)->i_val)
Definition at line 14 of file lua-5.3.6/src/ltable.h.
invalidateTMcache
#define invalidateTMcache (t) ((t)->flags = 0)
Definition at line 27 of file lua-5.3.6/src/ltable.h.
isdummy
#define isdummy (t) ((t)->lastfree == NULL)
Definition at line 31 of file lua-5.3.6/src/ltable.h.
keyfromval
#define keyfromval (v) (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
Definition at line 39 of file lua-5.3.6/src/ltable.h.
#define keyfromval(v) \
  (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
wgkey
#define wgkey (n) (&(n)->i_key.nk)
Definition at line 25 of file lua-5.3.6/src/ltable.h.
Referenced by removeentry(), and setnodevector().
Function Documentation
luaH_free()
LUAI_FUNC void luaH_free (lua_State * L, Table * t)
Definition at line 374 of file lua-5.1.5/src/ltable.c.
{
  if (t->node != dummynode)
    luaM_freearray(L, t->node, sizenode(t), Node);
  luaM_freearray(L, t->array, t->sizearray, TValue);
  luaM_free(L, t);
}
luaH_get()
LUAI_FUNC const TValue * luaH_get (Table * t, const TValue * key)
Definition at line 469 of file lua-5.1.5/src/ltable.c.
{
  switch (ttype(key)) {
    case LUA_TNIL: return luaO_nilobject;
    case LUA_TSTRING: return luaH_getstr(t, rawtsvalue(key));
    case LUA_TNUMBER: {
      int k;
      lua_Number n = nvalue(key);
      lua_number2int(k, n);
      if (luai_numeq(cast_num(k), nvalue(key))) /* index is int? */
        return luaH_getnum(t, k);  /* use specialized version */
      /* else go through */
    }
    default: {
      Node *n = mainposition(t, key);
      do {  /* check whether `key' is somewhere in the chain */
        if (luaO_rawequalObj(key2tval(n), key))
          return gval(n);  /* that's it */
        else n = gnext(n);
      } while (n);
      return luaO_nilobject;
    }
  }
}
luaH_getint()
LUAI_FUNC const TValue * luaH_getint (Table * t, lua_Integer key)
Definition at line 516 of file lua-5.3.6/src/ltable.c.
{
  /* (1 <= key && key <= t->sizearray) */
  if (l_castS2U(key) - 1 < t->sizearray)
    return &t->array[key - 1];
  else {
    Node *n = hashint(t, key);
    for (;;) {  /* check whether 'key' is somewhere in the chain */
      if (ttisinteger(gkey(n)) && ivalue(gkey(n)) == key)
        return gval(n);  /* that's it */
      else {
        int nx = gnext(n);
        if (nx == 0) break;
        n += nx;
      }
    }
    return luaO_nilobject;
  }
}
luaH_getn()
LUAI_FUNC lua_Unsigned luaH_getn (Table * t)
Definition at line 560 of file lua-5.1.5/src/ltable.c.
{
  unsigned int j = t->sizearray;
  if (j > 0 && ttisnil(&t->array[j - 1])) {
    /* there is a boundary in the array part: (binary) search for it */
    unsigned int i = 0;
    while (j - i > 1) {
      unsigned int m = (i+j)/2;
      if (ttisnil(&t->array[m - 1])) j = m;
      else i = m;
    }
    return i;
  }
  /* else must find a boundary in hash part */
  else if (t->node == dummynode)  /* hash part is empty? */
    return j;  /* that is easy... */
  else return unbound_search(t, j);
}
luaH_getshortstr()
LUAI_FUNC const TValue * luaH_getshortstr (Table * t, TString * key)
Definition at line 539 of file lua-5.3.6/src/ltable.c.
{
  Node *n = hashstr(t, key);
  lua_assert(key->tt == LUA_TSHRSTR);
  for (;;) {  /* check whether 'key' is somewhere in the chain */
    const TValue *k = gkey(n);
    if (ttisshrstring(k) && eqshrstr(tsvalue(k), key))
      return gval(n);  /* that's it */
    else {
      int nx = gnext(n);
      if (nx == 0)
        return luaO_nilobject;  /* not found */
      n += nx;
    }
  }
}
luaH_getstr()
LUAI_FUNC const TValue * luaH_getstr (Table * t, TString * key)
Definition at line 455 of file lua-5.1.5/src/ltable.c.
{
  Node *n = hashstr(t, key);
  do {  /* check whether `key' is somewhere in the chain */
    if (ttisstring(gkey(n)) && rawtsvalue(gkey(n)) == key)
      return gval(n);  /* that's it */
    else n = gnext(n);
  } while (n);
  return luaO_nilobject;
}
luaH_new()
LUAI_FUNC Table * luaH_new (lua_State * L)
Definition at line 368 of file lua-5.2.4/src/ltable.c.
{
  Table *t = &luaC_newobj(L, LUA_TTABLE, sizeof(Table), NULL, 0)->h;
  t->metatable = NULL;
  t->flags = cast_byte(~0);
  t->array = NULL;
  t->sizearray = 0;
  setnodevector(L, t, 0);
  return t;
}
luaH_newkey()
LUAI_FUNC TValue * luaH_newkey (lua_State * L, Table * t, const TValue * key)
Definition at line 405 of file lua-5.2.4/src/ltable.c.
{
  Node *mp;
  if (ttisnil(key)) luaG_runerror(L, "table index is nil");
  else if (ttisnumber(key) && luai_numisnan(L, nvalue(key)))
    luaG_runerror(L, "table index is NaN");
  mp = mainposition(t, key);
  if (!ttisnil(gval(mp)) || isdummy(mp)) {  /* main position is taken? */
    Node *othern;
    Node *n = getfreepos(t);  /* get a free place */
    if (n == NULL) {  /* cannot find a free place? */
      rehash(L, t, key);  /* grow table */
      /* whatever called 'newkey' take care of TM cache and GC barrier */
      return luaH_set(L, t, key);  /* insert key into grown table */
    }
    lua_assert(!isdummy(n));
    othern = mainposition(t, gkey(mp));
    if (othern != mp) {  /* is colliding node out of its main position? */
      /* yes; move colliding node into free position */
      while (gnext(othern) != mp) othern = gnext(othern);  /* find previous */
      gnext(othern) = n;  /* redo the chain with `n' in place of `mp' */
      *n = *mp;  /* copy colliding node into free pos. (mp->next also goes) */
      gnext(mp) = NULL;  /* now `mp' is free */
      setnilvalue(gval(mp));
    }
    else {  /* colliding node is in its own main position */
      /* new node will go into free position */
      gnext(n) = gnext(mp);  /* chain new position */
      gnext(mp) = n;
      mp = n;
    }
  }
  setobj2t(L, gkey(mp), key);
  luaC_barrierback(L, obj2gco(t), key);
  lua_assert(ttisnil(gval(mp)));
  return gval(mp);
}
References cast_int, fltvalue, getfreepos(), getfreepos(), gkey, gnext, gval, Node::i_key, isdummy, lua_assert, luaC_barrierback, luaG_runerror(), luaH_set(), luai_numisnan, luaV_tointeger(), mainposition(), mainposition(), NULL, nvalue, obj2gco, rehash(), rehash(), setivalue, setnilvalue, setnodekey, setobj2t, ttisfloat, ttisnil, and ttisnumber.
Referenced by luaH_set(), luaH_setint(), luaH_setint(), luaV_finishset(), and luaV_settable().
luaH_next()
LUAI_FUNC int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 162 of file lua-5.1.5/src/ltable.c.
{
  int i = findindex(L, t, key);  /* find original element */
  for (i++; i < t->sizearray; i++) {  /* try first array part */
    if (!ttisnil(&t->array[i])) {  /* a non-nil value? */
      setnvalue(key, cast_num(i+1));
      setobj2s(L, key+1, &t->array[i]);
      return 1;
    }
  }
  for (i -= t->sizearray; i < sizenode(t); i++) {  /* then hash part */
    if (!ttisnil(gval(gnode(t, i)))) {  /* a non-nil value? */
      setobj2s(L, key, key2tval(gnode(t, i)));
      setobj2s(L, key+1, gval(gnode(t, i)));
      return 1;
    }
  }
  return 0;  /* no more elements */
}
luaH_resize()
LUAI_FUNC void luaH_resize (lua_State * L, Table * t, unsigned int nasize, unsigned int nhsize)
Definition at line 347 of file lua-5.3.6/src/ltable.c.
{
  unsigned int i;
  int j;
  AuxsetnodeT asn;
  unsigned int oldasize = t->sizearray;
  int oldhsize = allocsizenode(t);
  Node *nold = t->node;  /* save old hash ... */
  if (nasize > oldasize)  /* array part must grow? */
    setarrayvector(L, t, nasize);
  /* create new hash part with appropriate size */
  asn.t = t; asn.nhsize = nhsize;
  if (luaD_rawrunprotected(L, auxsetnode, &asn) != LUA_OK) {  /* mem. error? */
    setarrayvector(L, t, oldasize);  /* array back to its original size */
    luaD_throw(L, LUA_ERRMEM);  /* rethrow memory error */
  }
  if (nasize < oldasize) {  /* array part must shrink? */
    t->sizearray = nasize;
    /* re-insert elements from vanishing slice */
    for (i=nasize; i<oldasize; i++) {
      if (!ttisnil(&t->array[i]))
        luaH_setint(L, t, i + 1, &t->array[i]);
    }
    /* shrink array */
    luaM_reallocvector(L, t->array, oldasize, nasize, TValue);
  }
  /* re-insert elements from hash part */
  for (j = oldhsize - 1; j >= 0; j--) {
    Node *old = nold + j;
    if (!ttisnil(gval(old))) {
      /* doesn't need barrier/invalidate cache, as entry was
         already present in the table */
      setobjt2t(L, luaH_set(L, t, gkey(old)), gval(old));
    }
  }
  if (oldhsize > 0)  /* not the dummy node? */
    luaM_freearray(L, nold, cast(size_t, oldhsize)); /* free old hash */
}
luaH_resizearray()
LUAI_FUNC void luaH_resizearray (lua_State * L, Table * t, unsigned int nasize)
Definition at line 387 of file lua-5.3.6/src/ltable.c.
{
  int nsize = allocsizenode(t);
  luaH_resize(L, t, nasize, nsize);
}
luaH_set()
LUAI_FUNC TValue * luaH_set (lua_State * L, Table * t, const TValue * key)
Definition at line 494 of file lua-5.1.5/src/ltable.c.
{
  const TValue *p = luaH_get(t, key);
  t->flags = 0;
  if (p != luaO_nilobject)
    return cast(TValue *, p);
  else {
    if (ttisnil(key)) luaG_runerror(L, "table index is nil");
    else if (ttisnumber(key) && luai_numisnan(nvalue(key)))
      luaG_runerror(L, "table index is NaN");
    return newkey(L, t, key);
  }
}
References cast, Table::flags, luaG_runerror(), luaH_get(), luaH_newkey(), luai_numisnan, luaO_nilobject, newkey(), nvalue, ttisnil, and ttisnumber.
Referenced by addk(), addk(), addk(), aux_rawset(), lua_rawset(), lua_rawsetp(), luaH_newkey(), luaH_resize(), luaH_resize(), luaV_settable(), luaX_newstring(), newkey(), and resize().
luaH_setint()
LUAI_FUNC void luaH_setint (lua_State * L, Table * t, lua_Integer key, TValue * value)
Definition at line 618 of file lua-5.3.6/src/ltable.c.
{
  const TValue *p = luaH_getint(t, key);
  TValue *cell;
  if (p != luaO_nilobject)
    cell = cast(TValue *, p);
  else {
    TValue k;
    setivalue(&k, key);
    cell = luaH_newkey(L, t, &k);
  }
  setobj2t(L, cell, value);
}