Github User Fetcher: lmem.h File Reference
lmem.h File Reference
#include <stddef.h>
#include "llimits.h"
#include "lua.h"
Macros
#define luaM_error(L) luaD_throw(L, LUA_ERRMEM)
#define luaM_testsize(n, e) (sizeof(n) >= sizeof(size_t) && cast_sizet((n)) + 1 > MAX_SIZET/(e))
#define luaM_checksize(L, n, e) (luaM_testsize(n,e) ? luaM_toobig(L) : cast_void(0))
#define luaM_limitN(n, t)
#define luaM_reallocvchar(L, b, on, n) cast_charp(luaM_saferealloc_(L, (b), (on)*sizeof(char), (n)*sizeof(char)))
#define luaM_freemem(L, b, s) luaM_free_(L, (b), (s))
#define luaM_free(L, b) luaM_free_(L, (b), sizeof(*(b)))
#define luaM_freearray(L, b, n) luaM_free_(L, (b), (n)*sizeof(*(b)))
#define luaM_new(L, t) cast(t*, luaM_malloc_(L, sizeof(t), 0))
#define luaM_newvector(L, n, t) cast(t*, luaM_malloc_(L, (n)*sizeof(t), 0))
#define luaM_newvectorchecked(L, n, t) (luaM_checksize(L,n,sizeof(t)), luaM_newvector(L,n,t))
#define luaM_newobject(L, tag, s) luaM_malloc_(L, (s), tag)
#define luaM_growvector(L, v, nelems, size, t, limit, e)
#define luaM_reallocvector(L, v, oldn, n, t)
#define luaM_shrinkvector(L, v, size, fs, t) ((v)=cast(t *, luaM_shrinkvector_(L, v, &(size), fs, sizeof(t))))
Functions
LUAI_FUNC l_noret luaM_toobig (lua_State *L)
LUAI_FUNC void * luaM_realloc_ (lua_State *L, void *block, size_t oldsize, size_t size)
LUAI_FUNC void * luaM_saferealloc_ (lua_State *L, void *block, size_t oldsize, size_t size)
LUAI_FUNC void luaM_free_ (lua_State *L, void *block, size_t osize)
LUAI_FUNC void * luaM_growaux_ (lua_State *L, void *block, int nelems, int *size, int size_elem, int limit, const char *what)
LUAI_FUNC void * luaM_shrinkvector_ (lua_State *L, void *block, int *nelem, int final_n, int size_elem)
LUAI_FUNC void * luaM_malloc_ (lua_State *L, size_t size, int tag)
Macro Definition Documentation
luaM_checksize
#define luaM_checksize (L, n, e) (luaM_testsize(n,e) ? luaM_toobig(L) : cast_void(0))
Definition at line 34 of file lua-5.4.3/src/lmem.h.
#define luaM_checksize(L,n,e)  \
    (luaM_testsize(n,e) ? luaM_toobig(L) : cast_void(0))
luaM_error
#define luaM_error (L) luaD_throw(L, LUA_ERRMEM)
Definition at line 17 of file lua-5.4.3/src/lmem.h.
Referenced by growstrtab(), lua_error(), luaD_reallocstack(), luaH_resize(), luaM_malloc_(), and luaM_saferealloc_().
luaM_free
#define luaM_free (L, b) luaM_free_(L, (b), sizeof(*(b)))
Definition at line 56 of file lua-5.4.3/src/lmem.h.
luaM_freearray
#define luaM_freearray (L, b, n) luaM_free_(L, (b), (n)*sizeof(*(b)))
Definition at line 57 of file lua-5.4.3/src/lmem.h.
luaM_freemem
#define luaM_freemem (L, b, s) luaM_free_(L, (b), (s))
Definition at line 55 of file lua-5.4.3/src/lmem.h.
luaM_growvector
#define luaM_growvector (L, v, nelems, size, t, limit, e)
Value:
    ((v)=cast(t *, luaM_growaux_(L,v,nelems,&(size),sizeof(t), \
                         luaM_limitN(limit,t),e)))
Definition at line 66 of file lua-5.4.3/src/lmem.h.
#define luaM_growvector(L,v,nelems,size,t,limit,e) \
    ((v)=cast(t *, luaM_growaux_(L,v,nelems,&(size),sizeof(t), \
                         luaM_limitN(limit,t),e)))
luaM_limitN
#define luaM_limitN (n, t)
Value:
  ((cast_sizet(n) <= MAX_SIZET/sizeof(t)) ? (n) :  \
     cast_uint((MAX_SIZET/sizeof(t))))
Definition at line 44 of file lua-5.4.3/src/lmem.h.
#define luaM_limitN(n,t)  \
  ((cast_sizet(n) <= MAX_SIZET/sizeof(t)) ? (n) :  \
     cast_uint((MAX_SIZET/sizeof(t))))
luaM_new
#define luaM_new (L, t) cast(t*, luaM_malloc_(L, sizeof(t), 0))
Definition at line 59 of file lua-5.4.3/src/lmem.h.
luaM_newobject
#define luaM_newobject (L, tag, s) luaM_malloc_(L, (s), tag)
Definition at line 64 of file lua-5.4.3/src/lmem.h.
luaM_newvector
#define luaM_newvector (L, n, t) cast(t*, luaM_malloc_(L, (n)*sizeof(t), 0))
Definition at line 60 of file lua-5.4.3/src/lmem.h.
luaM_newvectorchecked
#define luaM_newvectorchecked (L, n, t) (luaM_checksize(L,n,sizeof(t)), luaM_newvector(L,n,t))
Definition at line 61 of file lua-5.4.3/src/lmem.h.
#define luaM_newvectorchecked(L,n,t) \
  (luaM_checksize(L,n,sizeof(t)), luaM_newvector(L,n,t))
Referenced by loadCode(), loadConstants(), loadDebug(), loadProtos(), and loadUpvalues().
luaM_reallocvchar
#define luaM_reallocvchar (L, b, on, n) cast_charp(luaM_saferealloc_(L, (b), (on)*sizeof(char), (n)*sizeof(char)))
Definition at line 52 of file lua-5.4.3/src/lmem.h.
#define luaM_reallocvchar(L,b,on,n)  \
  cast_charp(luaM_saferealloc_(L, (b), (on)*sizeof(char), (n)*sizeof(char)))
luaM_reallocvector
#define luaM_reallocvector (L, v, oldn, n, t)
Value:
   (cast(t *, luaM_realloc_(L, v, cast_sizet(oldn) * sizeof(t), \
                                  cast_sizet(n) * sizeof(t))))
Definition at line 70 of file lua-5.4.3/src/lmem.h.
#define luaM_reallocvector(L, v,oldn,n,t) \
   (cast(t *, luaM_realloc_(L, v, cast_sizet(oldn) * sizeof(t), \
                                  cast_sizet(n) * sizeof(t))))
luaM_shrinkvector
#define luaM_shrinkvector (L, v, size, fs, t) ((v)=cast(t *, luaM_shrinkvector_(L, v, &(size), fs, sizeof(t))))
Definition at line 74 of file lua-5.4.3/src/lmem.h.
#define luaM_shrinkvector(L,v,size,fs,t) \
   ((v)=cast(t *, luaM_shrinkvector_(L, v, &(size), fs, sizeof(t))))
Referenced by close_func().
luaM_testsize
#define luaM_testsize (n, e) (sizeof(n) >= sizeof(size_t) && cast_sizet((n)) + 1 > MAX_SIZET/(e))
Definition at line 31 of file lua-5.4.3/src/lmem.h.
#define luaM_testsize(n,e)  \
    (sizeof(n) >= sizeof(size_t) && cast_sizet((n)) + 1 > MAX_SIZET/(e))
Function Documentation
luaM_free_()
LUAI_FUNC void luaM_free_ (lua_State * L, void * block, size_t osize)
Definition at line 132 of file lua-5.4.3/src/lmem.c.
{
  global_State *g = G(L);
  lua_assert((osize == 0) == (block == NULL));
  (*g->frealloc)(g->ud, block, osize, 0);
  g->GCdebt -= osize;
}
References block(), global_State::frealloc, G, global_State::GCdebt, lua_assert, NULL, and global_State::ud.
luaM_growaux_()
LUAI_FUNC void * luaM_growaux_ (lua_State * L, void * block, int nelems, int * size, int size_elem, int limit, const char * what)
Definition at line 79 of file lua-5.4.3/src/lmem.c.
{
  void *newblock;
  int size = *psize;
  if (nelems + 1 <= size)  /* does one extra element still fit? */
    return block;  /* nothing to be done */
  if (size >= limit / 2) {  /* cannot double it? */
    if (l_unlikely(size >= limit))  /* cannot grow even a little? */
      luaG_runerror(L, "too many %s (limit is %d)", what, limit);
    size = limit;  /* still have at least one free place */
  }
  else {
    size *= 2;
    if (size < MINSIZEARRAY)
      size = MINSIZEARRAY;  /* minimum size */
  }
  lua_assert(nelems + 1 <= size && size <= limit);
  /* 'limit' ensures that multiplication will not overflow */
  newblock = luaM_saferealloc_(L, block, cast_sizet(*psize) * size_elems,
                                         cast_sizet(size) * size_elems);
  *psize = size;  /* update only when everything else is OK */
  return newblock;
}
References block(), cast_sizet, lua_assert, luaG_runerror(), luaM_saferealloc_(), and MINSIZEARRAY.
luaM_malloc_()
LUAI_FUNC void * luaM_malloc_ (lua_State * L, size_t size, int tag)
Definition at line 187 of file lua-5.4.3/src/lmem.c.
{
  if (size == 0)
    return NULL;  /* that's all */
  else {
    global_State *g = G(L);
    void *newblock = firsttry(g, NULL, tag, size);
    if (l_unlikely(newblock == NULL)) {
      newblock = tryagain(L, NULL, tag, size);
      if (newblock == NULL)
        luaM_error(L);
    }
    g->GCdebt += size;
    return newblock;
  }
}
References firsttry, G, global_State::GCdebt, luaM_error, NULL, and tryagain().
luaM_realloc_()
LUAI_FUNC void * luaM_realloc_ (lua_State * L, void * block, size_t oldsize, size_t size)
Definition at line 76 of file lua-5.1.5/src/lmem.c.
{
  global_State *g = G(L);
  lua_assert((osize == 0) == (block == NULL));
  block = (*g->frealloc)(g->ud, block, osize, nsize);
  if (block == NULL && nsize > 0)
    luaD_throw(L, LUA_ERRMEM);
  lua_assert((nsize == 0) == (block == NULL));
  g->totalbytes = (g->totalbytes - osize) + nsize;
  return block;
}
References api_check, block(), firsttry, global_State::frealloc, G, global_State::GCdebt, global_State::gcrunning, lua_assert, LUA_ERRMEM, luaC_fullgc(), luaD_throw(), NULL, global_State::totalbytes, tryagain(), global_State::ud, and global_State::version.
Referenced by luaM_saferealloc_().
luaM_saferealloc_()
LUAI_FUNC void * luaM_saferealloc_ (lua_State * L, void * block, size_t oldsize, size_t size)
Definition at line 178 of file lua-5.4.3/src/lmem.c.
{
  void *newblock = luaM_realloc_(L, block, osize, nsize);
  if (l_unlikely(newblock == NULL && nsize > 0))  /* allocation failed? */
    luaM_error(L);
  return newblock;
}
References block(), luaM_error, luaM_realloc_(), and NULL.
Referenced by luaM_growaux_(), and luaM_shrinkvector_().
luaM_shrinkvector_()
LUAI_FUNC void * luaM_shrinkvector_ (lua_State * L, void * block, int * nelem, int final_n, int size_elem)
Definition at line 110 of file lua-5.4.3/src/lmem.c.
{
  void *newblock;
  size_t oldsize = cast_sizet((*size) * size_elem);
  size_t newsize = cast_sizet(final_n * size_elem);
  lua_assert(newsize <= oldsize);
  newblock = luaM_saferealloc_(L, block, oldsize, newsize);
  *size = final_n;
  return newblock;
}
References block(), cast_sizet, lua_assert, and luaM_saferealloc_().
luaM_toobig()
LUAI_FUNC l_noret luaM_toobig (lua_State * L)
Definition at line 66 of file lua-5.1.5/src/lmem.c.
{
  luaG_runerror(L, "memory allocation error: block too big");
  return NULL;  /* to avoid warnings */
}
References luaG_runerror(), and NULL.
Referenced by luaS_newlstr(), luaS_newudata(), luaS_newudata(), luaS_newudata(), and newlstr().