Github User Fetcher: lparser.c File Reference
lparser.c File Reference
#include <string.h>
#include "lua.h"
#include "lcode.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "llex.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
Data Structures
struct BlockCnt
struct ConsControl
struct LHS_assign
Macros
#define lparser_c
#define LUA_CORE
#define hasmultret(k) ((k) == VCALL || (k) == VVARARG)
#define getlocvar(fs, i) ((fs)->f->locvars[(fs)->actvar[i]])
#define luaY_checklimit(fs, v, l, m) if ((v)>(l)) errorlimit(fs,l,m)
#define check_condition(ls, c, msg) { if (!(c)) luaX_syntaxerror(ls, msg); }
#define new_localvarliteral(ls, v, n) new_localvar(ls, luaX_newstring(ls, "" v, (sizeof(v)/sizeof(char))-1), n)
#define leavelevel(ls) ((ls)->L->nCcalls--)
#define UNARY_PRIORITY 8 /* priority for unary operators */
Typedefs
typedef struct BlockCnt BlockCnt
Functions
static void chunk (LexState *ls)
static void expr (LexState *ls, expdesc *v)
static void anchor_token (LexState *ls)
static void error_expected (LexState *ls, int token)
static void errorlimit (FuncState *fs, int limit, const char *what)
static int testnext (LexState *ls, int c)
static void check (LexState *ls, int c)
static void checknext (LexState *ls, int c)
static void check_match (LexState *ls, int what, int who, int where)
static TString * str_checkname (LexState *ls)
static void init_exp (expdesc *e, expkind k, int i)
static void codestring (LexState *ls, expdesc *e, TString *s)
static void checkname (LexState *ls, expdesc *e)
static int registerlocalvar (LexState *ls, TString *varname)
static void new_localvar (LexState *ls, TString *name, int n)
static void adjustlocalvars (LexState *ls, int nvars)
static void removevars (LexState *ls, int tolevel)
static int indexupvalue (FuncState *fs, TString *name, expdesc *v)
static int searchvar (FuncState *fs, TString *n)
static void markupval (FuncState *fs, int level)
static int singlevaraux (FuncState *fs, TString *n, expdesc *var, int base)
static void singlevar (LexState *ls, expdesc *var)
static void adjust_assign (LexState *ls, int nvars, int nexps, expdesc *e)
static void enterlevel (LexState *ls)
static void enterblock (FuncState *fs, BlockCnt *bl, lu_byte isbreakable)
static void leaveblock (FuncState *fs)
static void pushclosure (LexState *ls, FuncState *func, expdesc *v)
static void open_func (LexState *ls, FuncState *fs)
static void close_func (LexState *ls)
Proto * luaY_parser (lua_State *L, ZIO *z, Mbuffer *buff, const char *name)
static void field (LexState *ls, expdesc *v)
static void yindex (LexState *ls, expdesc *v)
static void recfield (LexState *ls, struct ConsControl *cc)
static void closelistfield (FuncState *fs, struct ConsControl *cc)
static void lastlistfield (FuncState *fs, struct ConsControl *cc)
static void listfield (LexState *ls, struct ConsControl *cc)
static void constructor (LexState *ls, expdesc *t)
static void parlist (LexState *ls)
static void body (LexState *ls, expdesc *e, int needself, int line)
static int explist1 (LexState *ls, expdesc *v)
static void funcargs (LexState *ls, expdesc *f)
static void prefixexp (LexState *ls, expdesc *v)
static void primaryexp (LexState *ls, expdesc *v)
static void simpleexp (LexState *ls, expdesc *v)
static UnOpr getunopr (int op)
static BinOpr getbinopr (int op)
static BinOpr subexpr (LexState *ls, expdesc *v, unsigned int limit)
static int block_follow (int token)
static void block (LexState *ls)
static void check_conflict (LexState *ls, struct LHS_assign *lh, expdesc *v)
static void assignment (LexState *ls, struct LHS_assign *lh, int nvars)
static int cond (LexState *ls)
static void breakstat (LexState *ls)
static void whilestat (LexState *ls, int line)
static void repeatstat (LexState *ls, int line)
static int exp1 (LexState *ls)
static void forbody (LexState *ls, int base, int line, int nvars, int isnum)
static void fornum (LexState *ls, TString *varname, int line)
static void forlist (LexState *ls, TString *indexname)
static void forstat (LexState *ls, int line)
static int test_then_block (LexState *ls)
static void ifstat (LexState *ls, int line)
static void localfunc (LexState *ls)
static void localstat (LexState *ls)
static int funcname (LexState *ls, expdesc *v)
static void funcstat (LexState *ls, int line)
static void exprstat (LexState *ls)
static void retstat (LexState *ls)
static int statement (LexState *ls)
Variables
struct {
lu_byte left
lu_byte right
} priority []
Macro Definition Documentation
check_condition
#define check_condition (ls, c, msg) { if (!(c)) luaX_syntaxerror(ls, msg); }
Definition at line 100 of file lua-5.1.5/src/lparser.c.
Referenced by assignment(), and simpleexp().
getlocvar
#define getlocvar (fs, i) ((fs)->f->locvars[(fs)->actvar[i]])
Definition at line 32 of file lua-5.1.5/src/lparser.c.
Referenced by adjustlocalvars(), adjustlocalvars(), adjustlocalvars(), closegoto(), closegoto(), localfunc(), localfunc(), localfunc(), removevars(), removevars(), removevars(), searchvar(), searchvar(), and searchvar().
hasmultret
#define hasmultret (k) ((k) == VCALL || (k) == VVARARG)
Definition at line 30 of file lua-5.1.5/src/lparser.c.
Referenced by adjust_assign(), funcargs(), lastlistfield(), and retstat().
leavelevel
#define leavelevel (ls) ((ls)->L->nCcalls--)
Definition at line 282 of file lua-5.1.5/src/lparser.c.
Referenced by chunk(), and subexpr().
lparser_c
#define lparser_c
Definition at line 10 of file lua-5.1.5/src/lparser.c.
LUA_CORE
#define LUA_CORE
Definition at line 11 of file lua-5.1.5/src/lparser.c.
luaY_checklimit
#define luaY_checklimit (fs, v, l, m) if ((v)>(l)) errorlimit(fs,l,m)
Definition at line 34 of file lua-5.1.5/src/lparser.c.
Referenced by assignment(), indexupvalue(), listfield(), new_localvar(), and recfield().
new_localvarliteral
#define new_localvarliteral (ls, v, n) new_localvar(ls, luaX_newstring(ls, "" v, (sizeof(v)/sizeof(char))-1), n)
Definition at line 156 of file lua-5.1.5/src/lparser.c.
#define new_localvarliteral(ls,v,n) \
  new_localvar(ls, luaX_newstring(ls, "" v, (sizeof(v)/sizeof(char))-1), n)
Referenced by body(), forlist(), fornum(), and parlist().
UNARY_PRIORITY
#define UNARY_PRIORITY 8 /* priority for unary operators */
Definition at line 821 of file lua-5.1.5/src/lparser.c.
Referenced by subexpr().
Typedef Documentation
BlockCnt
typedef struct BlockCnt BlockCnt
Function Documentation
adjust_assign()
static void adjust_assign (LexState * ls, int nvars, int nexps, expdesc * e) static
Definition at line 256 of file lua-5.1.5/src/lparser.c.
{
  FuncState *fs = ls->fs;
  int extra = nvars - nexps;
  if (hasmultret(e->k)) {
    extra++;  /* includes call itself */
    if (extra < 0) extra = 0;
    luaK_setreturns(fs, e, extra);  /* last exp. provides the difference */
    if (extra > 1) luaK_reserveregs(fs, extra-1);
  }
  else {
    if (e->k != VVOID) luaK_exp2nextreg(fs, e);  /* close last expression */
    if (extra > 0) {
      int reg = fs->freereg;
      luaK_reserveregs(fs, extra);
      luaK_nil(fs, reg, extra);
    }
  }
}
References FuncState::freereg, LexState::fs, hasmultret, expdesc::k, luaK_exp2nextreg(), luaK_nil(), luaK_reserveregs(), luaK_setreturns(), and VVOID.
Referenced by assignment(), forlist(), and localstat().
adjustlocalvars()
static void adjustlocalvars (LexState * ls, int nvars) static
Definition at line 167 of file lua-5.1.5/src/lparser.c.
{
  FuncState *fs = ls->fs;
  fs->nactvar = cast_byte(fs->nactvar + nvars);
  for (; nvars; nvars--) {
    getlocvar(fs, fs->nactvar - nvars).startpc = fs->pc;
  }
}
References cast_byte, LexState::fs, getlocvar, FuncState::nactvar, and FuncState::pc.
Referenced by body(), forbody(), localfunc(), localstat(), and parlist().
anchor_token()
static void anchor_token (LexState * ls) static
Definition at line 57 of file lua-5.1.5/src/lparser.c.
{
  if (ls->t.token == TK_NAME || ls->t.token == TK_STRING) {
    TString *ts = ls->t.seminfo.ts;
    luaX_newstring(ls, getstr(ts), ts->tsv.len);
  }
}
References getstr, TString::len, luaX_newstring(), Token::seminfo, LexState::t, TK_NAME, TK_STRING, Token::token, SemInfo::ts, and TString::tsv.
Referenced by close_func().
assignment()
static void assignment (LexState * ls, struct LHS_assign * lh, int nvars) static
Definition at line 931 of file lua-5.1.5/src/lparser.c.
{
  expdesc e;
  check_condition(ls, VLOCAL <= lh->v.k && lh->v.k <= VINDEXED,
                      "syntax error");
  if (testnext(ls, ',')) {  /* assignment -> `,' primaryexp assignment */
    struct LHS_assign nv;
    nv.prev = lh;
    primaryexp(ls, &nv.v);
    if (nv.v.k == VLOCAL)
      check_conflict(ls, lh, &nv.v);
    luaY_checklimit(ls->fs, nvars, LUAI_MAXCCALLS - ls->L->nCcalls,
                    "variables in assignment");
    assignment(ls, &nv, nvars+1);
  }
  else {  /* assignment -> `=' explist1 */
    int nexps;
    checknext(ls, '=');
    nexps = explist1(ls, &e);
    if (nexps != nvars) {
      adjust_assign(ls, nvars, nexps, &e);
      if (nexps > nvars)
        ls->fs->freereg -= nexps - nvars;  /* remove extra values */
    }
    else {
      luaK_setoneret(ls->fs, &e);  /* close last expression */
      luaK_storevar(ls->fs, &lh->v, &e);
      return;  /* avoid default */
    }
  }
  init_exp(&e, VNONRELOC, ls->fs->freereg-1);  /* default assignment */
  luaK_storevar(ls->fs, &lh->v, &e);
}
References adjust_assign(), assignment(), check_condition, check_conflict(), checknext(), explist1(), FuncState::freereg, LexState::fs, init_exp(), expdesc::k, LexState::L, LUAI_MAXCCALLS, luaK_setoneret(), luaK_storevar(), luaY_checklimit, lua_State::nCcalls, LHS_assign::prev, primaryexp(), testnext(), LHS_assign::v, VINDEXED, VLOCAL, and VNONRELOC.
Referenced by assignment(), and exprstat().
block()
static void block (LexState * ls) static
Definition at line 881 of file lua-5.1.5/src/lparser.c.
{
  /* block -> chunk */
  FuncState *fs = ls->fs;
  BlockCnt bl;
  enterblock(fs, &bl, 0);
  chunk(ls);
  lua_assert(bl.breaklist == NO_JUMP);
  leaveblock(fs);
}
References BlockCnt::breaklist, chunk(), enterblock(), LexState::fs, leaveblock(), lua_assert, and NO_JUMP.
Referenced by duk__trans_call_cooperate(), duk__trans_call_cooperate(), forbody(), ifstat(), luaM_free_(), luaM_growaux_(), luaM_growaux_(), luaM_growaux_(), luaM_realloc_(), luaM_saferealloc_(), luaM_shrinkvector_(), mg_get_context_info(), mg_get_system_info(), my_cooperate(), statement(), test_then_block(), tryagain(), and whilestat().
block_follow()
static int block_follow (int token) static
Definition at line 871 of file lua-5.1.5/src/lparser.c.
{
  switch (token) {
    case TK_ELSE: case TK_ELSEIF: case TK_END:
    case TK_UNTIL: case TK_EOS:
      return 1;
    default: return 0;
  }
}
References TK_ELSE, TK_ELSEIF, TK_END, TK_EOS, and TK_UNTIL.
Referenced by chunk(), and retstat().
body()
static void body (LexState * ls, expdesc * e, int needself, int line) static
Definition at line 576 of file lua-5.1.5/src/lparser.c.
{
  /* body ->  `(' parlist `)' chunk END */
  FuncState new_fs;
  open_func(ls, &new_fs);
  new_fs.f->linedefined = line;
  checknext(ls, '(');
  if (needself) {
    new_localvarliteral(ls, "self", 0);
    adjustlocalvars(ls, 1);
  }
  parlist(ls);
  checknext(ls, ')');
  chunk(ls);
  new_fs.f->lastlinedefined = ls->linenumber;
  check_match(ls, TK_END, TK_FUNCTION, line);
  close_func(ls);
  pushclosure(ls, &new_fs, e);
}
References adjustlocalvars(), check_match(), checknext(), chunk(), close_func(), FuncState::f, Proto::lastlinedefined, Proto::linedefined, LexState::linenumber, new_localvarliteral, open_func(), parlist(), pushclosure(), TK_END, and TK_FUNCTION.
Referenced by funcstat(), localfunc(), mg_read_inner(), and simpleexp().
breakstat()
static void breakstat (LexState * ls) static
Definition at line 975 of file lua-5.1.5/src/lparser.c.
{
  FuncState *fs = ls->fs;
  BlockCnt *bl = fs->bl;
  int upval = 0;
  while (bl && !bl->isbreakable) {
    upval |= bl->upval;
    bl = bl->previous;
  }
  if (!bl)
    luaX_syntaxerror(ls, "no loop to break");
  if (upval)
    luaK_codeABC(fs, OP_CLOSE, bl->nactvar, 0, 0);
  luaK_concat(fs, &bl->breaklist, luaK_jump(fs));
}
References FuncState::bl, BlockCnt::breaklist, LexState::fs, BlockCnt::isbreakable, luaK_codeABC, luaK_concat(), luaK_jump(), luaX_syntaxerror(), BlockCnt::nactvar, OP_CLOSE, BlockCnt::previous, and BlockCnt::upval.
Referenced by repeatstat(), and statement().
check()
static void check (LexState * ls, int c) static
Definition at line 89 of file lua-5.1.5/src/lparser.c.
{
  if (ls->t.token != c)
    error_expected(ls, c);
}
References error_expected(), LexState::t, and Token::token.
check_conflict()
static void check_conflict (LexState * ls, struct LHS_assign * lh, expdesc * v) static
Definition at line 908 of file lua-5.1.5/src/lparser.c.
{
  FuncState *fs = ls->fs;
  int extra = fs->freereg;  /* eventual position to save local variable */
  int conflict = 0;
  for (; lh; lh = lh->prev) {
    if (lh->v.k == VINDEXED) {
      if (lh->v.u.s.info == v->u.s.info) {  /* conflict? */
        conflict = 1;
        lh->v.u.s.info = extra;  /* previous assignment will use safe copy */
      }
      if (lh->v.u.s.aux == v->u.s.info) {  /* conflict? */
        conflict = 1;
        lh->v.u.s.aux = extra;  /* previous assignment will use safe copy */
      }
    }
  }
  if (conflict) {
    luaK_codeABC(fs, OP_MOVE, fs->freereg, v->u.s.info, 0);  /* make copy */
    luaK_reserveregs(fs, 1);
  }
}
References expdesc::aux, FuncState::freereg, LexState::fs, expdesc::info, expdesc::k, luaK_codeABC, luaK_reserveregs(), OP_MOVE, LHS_assign::prev, expdesc::s, expdesc::u, LHS_assign::v, and VINDEXED.
Referenced by assignment().
check_match()
static void check_match (LexState * ls, int what, int who, int where) static
Definition at line 104 of file lua-5.1.5/src/lparser.c.
{
  if (!testnext(ls, what)) {
    if (where == ls->linenumber)
      error_expected(ls, what);
    else {
      luaX_syntaxerror(ls, luaO_pushfstring(ls->L,
             LUA_QS " expected (to close " LUA_QS " at line %d)",
              luaX_token2str(ls, what), luaX_token2str(ls, who), where));
    }
  }
}
References error_expected(), LexState::L, LexState::linenumber, LUA_QS, luaO_pushfstring(), luaX_syntaxerror(), luaX_token2str(), and testnext().
Referenced by body(), constructor(), forstat(), funcargs(), ifstat(), prefixexp(), repeatstat(), statement(), and whilestat().
checkname()
static void checkname (LexState * ls, expdesc * e) static
Definition at line 138 of file lua-5.1.5/src/lparser.c.
{
  codestring(ls, e, str_checkname(ls));
}
References codestring(), and str_checkname().
Referenced by field(), primaryexp(), and recfield().
checknext()
static void checknext (LexState * ls, int c) static
Definition at line 94 of file lua-5.1.5/src/lparser.c.
{
  check(ls, c);
  luaX_next(ls);
}
References check, and luaX_next().
Referenced by assignment(), body(), constructor(), forbody(), forlist(), fornum(), recfield(), test_then_block(), whilestat(), and yindex().
chunk()
static void chunk (LexState * ls) static
Definition at line 1325 of file lua-5.1.5/src/lparser.c.
{
  /* chunk -> { stat [`;'] } */
  int islast = 0;
  enterlevel(ls);
  while (!islast && !block_follow(ls->t.token)) {
    islast = statement(ls);
    testnext(ls, ';');
    lua_assert(ls->fs->f->maxstacksize >= ls->fs->freereg &&
               ls->fs->freereg >= ls->fs->nactvar);
    ls->fs->freereg = ls->fs->nactvar;  /* free registers */
  }
  leavelevel(ls);
}
References block_follow(), enterlevel, FuncState::f, FuncState::freereg, LexState::fs, leavelevel, lua_assert, Proto::maxstacksize, FuncState::nactvar, statement(), LexState::t, testnext(), and Token::token.
Referenced by block(), body(), luaY_parser(), mg_send_chunk(), repeatstat(), runargs(), and runargs().
close_func()
static void close_func (LexState * ls) static
Definition at line 356 of file lua-5.1.5/src/lparser.c.
{
  lua_State *L = ls->L;
  FuncState *fs = ls->fs;
  Proto *f = fs->f;
  removevars(ls, 0);
  luaK_ret(fs, 0, 0);  /* final return */
  luaM_reallocvector(L, f->code, f->sizecode, fs->pc, Instruction);
  f->sizecode = fs->pc;
  luaM_reallocvector(L, f->lineinfo, f->sizelineinfo, fs->pc, int);
  f->sizelineinfo = fs->pc;
  luaM_reallocvector(L, f->k, f->sizek, fs->nk, TValue);
  f->sizek = fs->nk;
  luaM_reallocvector(L, f->p, f->sizep, fs->np, Proto *);
  f->sizep = fs->np;
  luaM_reallocvector(L, f->locvars, f->sizelocvars, fs->nlocvars, LocVar);
  f->sizelocvars = fs->nlocvars;
  luaM_reallocvector(L, f->upvalues, f->sizeupvalues, f->nups, TString *);
  f->sizeupvalues = f->nups;
  lua_assert(luaG_checkcode(f));
  lua_assert(fs->bl == NULL);
  ls->fs = fs->prev;
  /* last token read was anchored in defunct function; must reanchor it */
  if (fs) anchor_token(ls);
  L->top -= 2;  /* remove table and prototype from the stack */
}
References anchor_token(), FuncState::bl, Proto::code, FuncState::f, LexState::fs, Proto::k, LexState::L, Proto::lineinfo, Proto::locvars, lua_assert, luaG_checkcode(), luaK_ret(), luaM_reallocvector, FuncState::nk, FuncState::nlocvars, FuncState::np, NULL, Proto::nups, Proto::p, FuncState::pc, FuncState::prev, removevars(), Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, lua_State::top, and Proto::upvalues.
Referenced by body(), luaY_parser(), mg_connect_websocket_client(), mg_connect_websocket_client_extensions(), mg_connect_websocket_client_impl(), mg_connect_websocket_client_secure(), and mg_connect_websocket_client_secure_extensions().
closelistfield()
static void closelistfield (FuncState * fs, struct ConsControl * cc) static
Definition at line 464 of file lua-5.1.5/src/lparser.c.
{
  if (cc->v.k == VVOID) return;  /* there is no list item */
  luaK_exp2nextreg(fs, &cc->v);
  cc->v.k = VVOID;
  if (cc->tostore == LFIELDS_PER_FLUSH) {
    luaK_setlist(fs, cc->t->u.s.info, cc->na, cc->tostore);  /* flush */
    cc->tostore = 0;  /* no more items pending */
  }
}
References expdesc::info, expdesc::k, LFIELDS_PER_FLUSH, luaK_exp2nextreg(), luaK_setlist(), ConsControl::na, expdesc::s, ConsControl::t, ConsControl::tostore, expdesc::u, ConsControl::v, and VVOID.
Referenced by constructor().
codestring()
static void codestring (LexState * ls, expdesc * e, TString * s) static
Definition at line 133 of file lua-5.1.5/src/lparser.c.
{
  init_exp(e, VK, luaK_stringK(ls->fs, s));
}
References LexState::fs, init_exp(), luaK_stringK(), s, and VK.
Referenced by checkname(), funcargs(), and simpleexp().
cond()
static int cond (LexState * ls) static
Definition at line 965 of file lua-5.1.5/src/lparser.c.
{
  /* cond -> exp */
  expdesc v;
  expr(ls, &v);  /* read condition */
  if (v.k == VNIL) v.k = VFALSE;  /* `falses' are all equal here */
  luaK_goiftrue(ls->fs, &v);
  return v.f;
}
References expr(), expdesc::f, LexState::fs, expdesc::k, luaK_goiftrue(), LHS_assign::v, VFALSE, and VNIL.
Referenced by codecomp(), codecomp(), jumponcond(), jumponcond(), jumponcond(), jumponcond(), luaV_execute(), repeatstat(), test_then_block(), and whilestat().
constructor()
static void constructor (LexState * ls, expdesc * t) static
Definition at line 498 of file lua-5.1.5/src/lparser.c.
{
  /* constructor -> ?? */
  FuncState *fs = ls->fs;
  int line = ls->linenumber;
  int pc = luaK_codeABC(fs, OP_NEWTABLE, 0, 0, 0);
  struct ConsControl cc;
  cc.na = cc.nh = cc.tostore = 0;
  cc.t = t;
  init_exp(t, VRELOCABLE, pc);
  init_exp(&cc.v, VVOID, 0);  /* no value (yet) */
  luaK_exp2nextreg(ls->fs, t);  /* fix it at stack top (for gc) */
  checknext(ls, '{');
  do {
    lua_assert(cc.v.k == VVOID || cc.tostore > 0);
    if (ls->t.token == '}') break;
    closelistfield(fs, &cc);
    switch(ls->t.token) {
      case TK_NAME: {  /* may be listfields or recfields */
        luaX_lookahead(ls);
        if (ls->lookahead.token != '=')  /* expression? */
          listfield(ls, &cc);
        else
          recfield(ls, &cc);
        break;
      }
      case '[': {  /* constructor_item -> recfield */
        recfield(ls, &cc);
        break;
      }
      default: {  /* constructor_part -> listfield */
        listfield(ls, &cc);
        break;
      }
    }
  } while (testnext(ls, ',') || testnext(ls, ';'));
  check_match(ls, '}', '{', line);
  lastlistfield(fs, &cc);
  SETARG_B(fs->f->code[pc], luaO_int2fb(cc.na)); /* set initial array size */
  SETARG_C(fs->f->code[pc], luaO_int2fb(cc.nh));  /* set initial table size */
}
References check_match(), checknext(), closelistfield(), Proto::code, FuncState::f, LexState::fs, init_exp(), expdesc::k, lastlistfield(), LexState::linenumber, listfield(), LexState::lookahead, lua_assert, luaK_codeABC, luaK_exp2nextreg(), luaO_int2fb(), luaX_lookahead(), ConsControl::na, ConsControl::nh, OP_NEWTABLE, recfield(), SETARG_B, SETARG_C, LexState::t, ConsControl::t, testnext(), TK_NAME, Token::token, ConsControl::tostore, ConsControl::v, VRELOCABLE, and VVOID.
Referenced by funcargs(), and simpleexp().
enterblock()
static void enterblock (FuncState * fs, BlockCnt * bl, lu_byte isbreakable) static
Definition at line 285 of file lua-5.1.5/src/lparser.c.
{
  bl->breaklist = NO_JUMP;
  bl->isbreakable = isbreakable;
  bl->nactvar = fs->nactvar;
  bl->upval = 0;
  bl->previous = fs->bl;
  fs->bl = bl;
  lua_assert(fs->freereg == fs->nactvar);
}
References FuncState::bl, BlockCnt::breaklist, FuncState::freereg, BlockCnt::isbreakable, lua_assert, BlockCnt::nactvar, FuncState::nactvar, NO_JUMP, BlockCnt::previous, and BlockCnt::upval.
Referenced by block(), forbody(), forstat(), repeatstat(), and whilestat().
enterlevel()
static void enterlevel (LexState * ls) static
Definition at line 276 of file lua-5.1.5/src/lparser.c.
{
  if (++ls->L->nCcalls > LUAI_MAXCCALLS)
    luaX_lexerror(ls, "chunk has too many syntax levels", 0);
}
References LexState::L, LUAI_MAXCCALLS, luaX_lexerror(), and lua_State::nCcalls.
error_expected()
static void error_expected (LexState * ls, int token) static
Definition at line 65 of file lua-5.1.5/src/lparser.c.
{
  luaX_syntaxerror(ls,
      luaO_pushfstring(ls->L, LUA_QS " expected", luaX_token2str(ls, token)));
}
References LexState::L, LUA_QS, luaO_pushfstring(), luaX_syntaxerror(), and luaX_token2str().
Referenced by check(), and check_match().
errorlimit()
static void errorlimit (FuncState * fs, int limit, const char * what) static
Definition at line 71 of file lua-5.1.5/src/lparser.c.
{
  const char *msg = (fs->f->linedefined == 0) ?
    luaO_pushfstring(fs->L, "main function has more than %d %s", limit, what) :
    luaO_pushfstring(fs->L, "function at line %d has more than %d %s",
                            fs->f->linedefined, limit, what);
  luaX_lexerror(fs->ls, msg, 0);
}
References FuncState::f, FuncState::L, Proto::linedefined, FuncState::ls, luaO_pushfstring(), and luaX_lexerror().
exp1()
static int exp1 (LexState * ls) static
Definition at line 1036 of file lua-5.1.5/src/lparser.c.
{
  expdesc e;
  int k;
  expr(ls, &e);
  k = e.k;
  luaK_exp2nextreg(ls->fs, &e);
  return k;
}
References expr(), LexState::fs, expdesc::k, and luaK_exp2nextreg().
Referenced by fornum(), and lua_strx2number().
explist1()
static int explist1 (LexState * ls, expdesc * v) static
Definition at line 596 of file lua-5.1.5/src/lparser.c.
{
  /* explist1 -> expr { `,' expr } */
  int n = 1;  /* at least one expression */
  expr(ls, v);
  while (testnext(ls, ',')) {
    luaK_exp2nextreg(ls->fs, v);
    expr(ls, v);
    n++;
  }
  return n;
}
References expr(), LexState::fs, luaK_exp2nextreg(), testnext(), and ConsControl::v.
Referenced by assignment(), forlist(), funcargs(), localstat(), and retstat().
expr()
static void expr (LexState * ls, expdesc * v) static
Definition at line 856 of file lua-5.1.5/src/lparser.c.
{
  subexpr(ls, v, 0);
}
References subexpr().
Referenced by cond(), exp1(), explist1(), listfield(), prefixexp(), recfield(), and yindex().
exprstat()
static void exprstat (LexState * ls) static
Definition at line 1224 of file lua-5.1.5/src/lparser.c.
{
  /* stat -> func | assignment */
  FuncState *fs = ls->fs;
  struct LHS_assign v;
  primaryexp(ls, &v.v);
  if (v.v.k == VCALL)  /* stat -> func */
    SETARG_C(getcode(fs, &v.v), 1);  /* call statement uses no results */
  else {  /* stat -> assignment */
    v.prev = NULL;
    assignment(ls, &v, 1);
  }
}
References assignment(), LexState::fs, getcode, expdesc::k, NULL, primaryexp(), SETARG_C, LHS_assign::v, and VCALL.
Referenced by statement().
field()
static void field (LexState * ls, expdesc * v) static
Definition at line 407 of file lua-5.1.5/src/lparser.c.
{
  /* field -> ['.' | ':'] NAME */
  FuncState *fs = ls->fs;
  expdesc key;
  luaK_exp2anyreg(fs, v);
  luaX_next(ls);  /* skip the dot or colon */
  checkname(ls, &key);
  luaK_indexed(fs, v, &key);
}
References checkname(), LexState::fs, FuncState::ls, luaK_exp2anyreg(), luaK_indexed(), and luaX_next().
Referenced by funcname(), and primaryexp().
forbody()
static void forbody (LexState * ls, int base, int line, int nvars, int isnum) static
Definition at line 1046 of file lua-5.1.5/src/lparser.c.
{
  /* forbody -> DO block */
  BlockCnt bl;
  FuncState *fs = ls->fs;
  int prep, endfor;
  adjustlocalvars(ls, 3);  /* control variables */
  checknext(ls, TK_DO);
  prep = isnum ? luaK_codeAsBx(fs, OP_FORPREP, base, NO_JUMP) : luaK_jump(fs);
  enterblock(fs, &bl, 0);  /* scope for declared variables */
  adjustlocalvars(ls, nvars);
  luaK_reserveregs(fs, nvars);
  block(ls);
  leaveblock(fs);  /* end of scope for declared variables */
  luaK_patchtohere(fs, prep);
  endfor = (isnum) ? luaK_codeAsBx(fs, OP_FORLOOP, base, NO_JUMP) :
                     luaK_codeABC(fs, OP_TFORLOOP, base, 0, nvars);
  luaK_fixline(fs, line);  /* pretend that `OP_FOR' starts the loop */
  luaK_patchlist(fs, (isnum ? endfor : luaK_jump(fs)), prep + 1);
}
References adjustlocalvars(), block(), checknext(), enterblock(), LexState::fs, leaveblock(), luaK_codeABC, luaK_codeAsBx, luaK_fixline(), luaK_jump(), luaK_patchlist(), luaK_patchtohere(), luaK_reserveregs(), NO_JUMP, OP_FORLOOP, OP_FORPREP, OP_TFORLOOP, and TK_DO.
Referenced by forlist(), and fornum().
forlist()
static void forlist (LexState * ls, TString * indexname) static
Definition at line 1089 of file lua-5.1.5/src/lparser.c.
{
  /* forlist -> NAME {,NAME} IN explist1 forbody */
  FuncState *fs = ls->fs;
  expdesc e;
  int nvars = 0;
  int line;
  int base = fs->freereg;
  /* create control variables */
  new_localvarliteral(ls, "(for generator)", nvars++);
  new_localvarliteral(ls, "(for state)", nvars++);
  new_localvarliteral(ls, "(for control)", nvars++);
  /* create declared variables */
  new_localvar(ls, indexname, nvars++);
  while (testnext(ls, ','))
    new_localvar(ls, str_checkname(ls), nvars++);
  checknext(ls, TK_IN);
  line = ls->linenumber;
  adjust_assign(ls, 3, explist1(ls, &e), &e);
  luaK_checkstack(fs, 3);  /* extra space to call generator */
  forbody(ls, base, line, nvars - 3, 0);
}
References adjust_assign(), checknext(), explist1(), forbody(), FuncState::freereg, LexState::fs, LexState::linenumber, luaK_checkstack(), new_localvar(), new_localvarliteral, str_checkname(), testnext(), and TK_IN.
Referenced by forstat().
fornum()
static void fornum (LexState * ls, TString * varname, int line) static
Definition at line 1067 of file lua-5.1.5/src/lparser.c.
{
  /* fornum -> NAME = exp1,exp1[,exp1] forbody */
  FuncState *fs = ls->fs;
  int base = fs->freereg;
  new_localvarliteral(ls, "(for index)", 0);
  new_localvarliteral(ls, "(for limit)", 1);
  new_localvarliteral(ls, "(for step)", 2);
  new_localvar(ls, varname, 3);
  checknext(ls, '=');
  exp1(ls);  /* initial value */
  checknext(ls, ',');
  exp1(ls);  /* limit */
  if (testnext(ls, ','))
    exp1(ls);  /* optional step */
  else {  /* default step = 1 */
    luaK_codeABx(fs, OP_LOADK, fs->freereg, luaK_numberK(fs, 1));
    luaK_reserveregs(fs, 1);
  }
  forbody(ls, base, line, 1, 1);
}
References checknext(), exp1(), forbody(), FuncState::freereg, LexState::fs, luaK_codeABx(), luaK_numberK(), luaK_reserveregs(), new_localvar(), new_localvarliteral, OP_LOADK, and testnext().
Referenced by forstat().
forstat()
static void forstat (LexState * ls, int line) static
Definition at line 1112 of file lua-5.1.5/src/lparser.c.
{
  /* forstat -> FOR (fornum | forlist) END */
  FuncState *fs = ls->fs;
  TString *varname;
  BlockCnt bl;
  enterblock(fs, &bl, 1);  /* scope for loop and control variables */
  luaX_next(ls);  /* skip `for' */
  varname = str_checkname(ls);  /* first variable name */
  switch (ls->t.token) {
    case '=': fornum(ls, varname, line); break;
    case ',': case TK_IN: forlist(ls, varname); break;
    default: luaX_syntaxerror(ls, LUA_QL("=") " or " LUA_QL("in") " expected");
  }
  check_match(ls, TK_END, TK_FOR, line);
  leaveblock(fs);  /* loop scope (`break' jumps to this point) */
}
References check_match(), enterblock(), forlist(), fornum(), LexState::fs, leaveblock(), LUA_QL, luaX_next(), luaX_syntaxerror(), str_checkname(), LexState::t, TK_END, TK_FOR, TK_IN, and Token::token.
Referenced by statement().
funcargs()
static void funcargs (LexState * ls, expdesc * f) static
Definition at line 609 of file lua-5.1.5/src/lparser.c.
{
  FuncState *fs = ls->fs;
  expdesc args;
  int base, nparams;
  int line = ls->linenumber;
  switch (ls->t.token) {
    case '(': {  /* funcargs -> `(' [ explist1 ] `)' */
      if (line != ls->lastline)
        luaX_syntaxerror(ls,"ambiguous syntax (function call x new statement)");
      luaX_next(ls);
      if (ls->t.token == ')')  /* arg list is empty? */
        args.k = VVOID;
      else {
        explist1(ls, &args);
        luaK_setmultret(fs, &args);
      }
      check_match(ls, ')', '(', line);
      break;
    }
    case '{': {  /* funcargs -> constructor */
      constructor(ls, &args);
      break;
    }
    case TK_STRING: {  /* funcargs -> STRING */
      codestring(ls, &args, ls->t.seminfo.ts);
      luaX_next(ls);  /* must use `seminfo' before `next' */
      break;
    }
    default: {
      luaX_syntaxerror(ls, "function arguments expected");
      return;
    }
  }
  lua_assert(f->k == VNONRELOC);
  base = f->u.s.info;  /* base register for call */
  if (hasmultret(args.k))
    nparams = LUA_MULTRET;  /* open call */
  else {
    if (args.k != VVOID)
      luaK_exp2nextreg(fs, &args);  /* close last argument */
    nparams = fs->freereg - (base+1);
  }
  init_exp(f, VCALL, luaK_codeABC(fs, OP_CALL, base, nparams+1, 2));
  luaK_fixline(fs, line);
  fs->freereg = base+1;  /* call remove function and arguments and leaves
                            (unless changed) one result */
}
References check_match(), codestring(), constructor(), explist1(), FuncState::freereg, LexState::fs, hasmultret, expdesc::info, init_exp(), expdesc::k, LexState::lastline, LexState::linenumber, lua_assert, LUA_MULTRET, luaK_codeABC, luaK_exp2nextreg(), luaK_fixline(), luaK_setmultret, luaX_next(), luaX_syntaxerror(), OP_CALL, expdesc::s, Token::seminfo, LexState::t, TK_STRING, Token::token, SemInfo::ts, expdesc::u, VCALL, VNONRELOC, and VVOID.
Referenced by primaryexp().
funcname()
static int funcname (LexState * ls, expdesc * v) static
Definition at line 1198 of file lua-5.1.5/src/lparser.c.
{
  /* funcname -> NAME {field} [`:' NAME] */
  int needself = 0;
  singlevar(ls, v);
  while (ls->t.token == '.')
    field(ls, v);
  if (ls->t.token == ':') {
    needself = 1;
    field(ls, v);
  }
  return needself;
}
References field(), singlevar(), LexState::t, Token::token, and LHS_assign::v.
Referenced by _file_lock(), check_file(), duk__error_getter_helper(), funcstat(), loader_C(), loader_Croot(), loadfunc(), and mkfuncname().
funcstat()
static void funcstat (LexState * ls, int line) static
Definition at line 1212 of file lua-5.1.5/src/lparser.c.
{
  /* funcstat -> FUNCTION funcname body */
  int needself;
  expdesc v, b;
  luaX_next(ls);  /* skip FUNCTION */
  needself = funcname(ls, &v);
  body(ls, &b, needself, line);
  luaK_storevar(ls->fs, &v, &b);
  luaK_fixline(ls->fs, line);  /* definition `happens' in the first line */
}
References body(), LexState::fs, funcname(), luaK_fixline(), luaK_storevar(), luaX_next(), and LHS_assign::v.
Referenced by statement().
getbinopr()
static BinOpr getbinopr (int op) static
Definition at line 788 of file lua-5.1.5/src/lparser.c.
{
  switch (op) {
    case '+': return OPR_ADD;
    case '-': return OPR_SUB;
    case '*': return OPR_MUL;
    case '/': return OPR_DIV;
    case '%': return OPR_MOD;
    case '^': return OPR_POW;
    case TK_CONCAT: return OPR_CONCAT;
    case TK_NE: return OPR_NE;
    case TK_EQ: return OPR_EQ;
    case '<': return OPR_LT;
    case TK_LE: return OPR_LE;
    case '>': return OPR_GT;
    case TK_GE: return OPR_GE;
    case TK_AND: return OPR_AND;
    case TK_OR: return OPR_OR;
    default: return OPR_NOBINOPR;
  }
}
References OPR_ADD, OPR_AND, OPR_CONCAT, OPR_DIV, OPR_EQ, OPR_GE, OPR_GT, OPR_LE, OPR_LT, OPR_MOD, OPR_MUL, OPR_NE, OPR_NOBINOPR, OPR_OR, OPR_POW, OPR_SUB, TK_AND, TK_CONCAT, TK_EQ, TK_GE, TK_LE, TK_NE, and TK_OR.
Referenced by subexpr().
getunopr()
static UnOpr getunopr (int op) static
Definition at line 778 of file lua-5.1.5/src/lparser.c.
{
  switch (op) {
    case TK_NOT: return OPR_NOT;
    case '-': return OPR_MINUS;
    case '#': return OPR_LEN;
    default: return OPR_NOUNOPR;
  }
}
References OPR_LEN, OPR_MINUS, OPR_NOT, OPR_NOUNOPR, and TK_NOT.
Referenced by subexpr().
ifstat()
static void ifstat (LexState * ls, int line) static
Definition at line 1141 of file lua-5.1.5/src/lparser.c.
{
  /* ifstat -> IF cond THEN block {ELSEIF cond THEN block} [ELSE block] END */
  FuncState *fs = ls->fs;
  int flist;
  int escapelist = NO_JUMP;
  flist = test_then_block(ls);  /* IF cond THEN block */
  while (ls->t.token == TK_ELSEIF) {
    luaK_concat(fs, &escapelist, luaK_jump(fs));
    luaK_patchtohere(fs, flist);
    flist = test_then_block(ls);  /* ELSEIF cond THEN block */
  }
  if (ls->t.token == TK_ELSE) {
    luaK_concat(fs, &escapelist, luaK_jump(fs));
    luaK_patchtohere(fs, flist);
    luaX_next(ls);  /* skip ELSE (after patch, for correct line info) */
    block(ls);  /* `else' part */
  }
  else
    luaK_concat(fs, &escapelist, flist);
  luaK_patchtohere(fs, escapelist);
  check_match(ls, TK_END, TK_IF, line);
}
References block(), check_match(), LexState::fs, luaK_concat(), luaK_jump(), luaK_patchtohere(), luaX_next(), NO_JUMP, LexState::t, test_then_block(), TK_ELSE, TK_ELSEIF, TK_END, TK_IF, and Token::token.
Referenced by statement().
indexupvalue()
static int indexupvalue (FuncState * fs, TString * name, expdesc * v) static
Definition at line 183 of file lua-5.1.5/src/lparser.c.
{
  int i;
  Proto *f = fs->f;
  int oldsize = f->sizeupvalues;
  for (i=0; i<f->nups; i++) {
    if (fs->upvalues[i].k == v->k && fs->upvalues[i].info == v->u.s.info) {
      lua_assert(f->upvalues[i] == name);
      return i;
    }
  }
  /* new one */
  luaY_checklimit(fs, f->nups + 1, LUAI_MAXUPVALUES, "upvalues");
  luaM_growvector(fs->L, f->upvalues, f->nups, f->sizeupvalues,
                  TString *, MAX_INT, "");
  while (oldsize < f->sizeupvalues) f->upvalues[oldsize++] = NULL;
  f->upvalues[f->nups] = name;
  luaC_objbarrier(fs->L, f, name);
  lua_assert(v->k == VLOCAL || v->k == VUPVAL);
  fs->upvalues[f->nups].k = cast_byte(v->k);
  fs->upvalues[f->nups].info = cast_byte(v->u.s.info);
  return f->nups++;
}
References cast_byte, FuncState::f, expdesc::info, upvaldesc::info, expdesc::k, upvaldesc::k, FuncState::L, lua_assert, luaC_objbarrier, LUAI_MAXUPVALUES, luaM_growvector, luaY_checklimit, MAX_INT, name, NULL, Proto::nups, expdesc::s, Proto::sizeupvalues, expdesc::u, Proto::upvalues, FuncState::upvalues, VLOCAL, and VUPVAL.
Referenced by singlevaraux().
init_exp()
static void init_exp (expdesc * e, expkind k, int i) static
Definition at line 126 of file lua-5.1.5/src/lparser.c.
{
  e->f = e->t = NO_JUMP;
  e->k = k;
  e->u.s.info = i;
}
References expdesc::f, expdesc::info, expdesc::k, NO_JUMP, expdesc::s, expdesc::t, and expdesc::u.
Referenced by assignment(), codestring(), constructor(), funcargs(), localfunc(), pushclosure(), simpleexp(), and singlevaraux().
lastlistfield()
static void lastlistfield (FuncState * fs, struct ConsControl * cc) static
Definition at line 475 of file lua-5.1.5/src/lparser.c.
{
  if (cc->tostore == 0) return;
  if (hasmultret(cc->v.k)) {
    luaK_setmultret(fs, &cc->v);
    luaK_setlist(fs, cc->t->u.s.info, cc->na, LUA_MULTRET);
    cc->na--;  /* do not count last expression (unknown number of elements) */
  }
  else {
    if (cc->v.k != VVOID)
      luaK_exp2nextreg(fs, &cc->v);
    luaK_setlist(fs, cc->t->u.s.info, cc->na, cc->tostore);
  }
}
References hasmultret, expdesc::info, expdesc::k, LUA_MULTRET, luaK_exp2nextreg(), luaK_setlist(), luaK_setmultret, ConsControl::na, expdesc::s, ConsControl::t, ConsControl::tostore, expdesc::u, ConsControl::v, and VVOID.
Referenced by constructor().
leaveblock()
static void leaveblock (FuncState * fs) static
Definition at line 296 of file lua-5.1.5/src/lparser.c.
{
  BlockCnt *bl = fs->bl;
  fs->bl = bl->previous;
  removevars(fs->ls, bl->nactvar);
  if (bl->upval)
    luaK_codeABC(fs, OP_CLOSE, bl->nactvar, 0, 0);
  /* a block either controls scope or breaks (never both) */
  lua_assert(!bl->isbreakable || !bl->upval);
  lua_assert(bl->nactvar == fs->nactvar);
  fs->freereg = fs->nactvar;  /* free registers */
  luaK_patchtohere(fs, bl->breaklist);
}
References FuncState::bl, BlockCnt::breaklist, FuncState::freereg, BlockCnt::isbreakable, FuncState::ls, lua_assert, luaK_codeABC, luaK_patchtohere(), BlockCnt::nactvar, FuncState::nactvar, OP_CLOSE, BlockCnt::previous, removevars(), and BlockCnt::upval.
Referenced by block(), forbody(), forstat(), repeatstat(), and whilestat().
listfield()
static void listfield (LexState * ls, struct ConsControl * cc) static
Definition at line 490 of file lua-5.1.5/src/lparser.c.
{
  expr(ls, &cc->v);
  luaY_checklimit(ls->fs, cc->na, MAX_INT, "items in a constructor");
  cc->na++;
  cc->tostore++;
}
References expr(), LexState::fs, luaY_checklimit, MAX_INT, ConsControl::na, ConsControl::tostore, and ConsControl::v.
Referenced by constructor().
localfunc()
static void localfunc (LexState * ls) static
Definition at line 1165 of file lua-5.1.5/src/lparser.c.
{
  expdesc v, b;
  FuncState *fs = ls->fs;
  new_localvar(ls, str_checkname(ls), 0);
  init_exp(&v, VLOCAL, fs->freereg);
  luaK_reserveregs(fs, 1);
  adjustlocalvars(ls, 1);
  body(ls, &b, 0, ls->linenumber);
  luaK_storevar(fs, &v, &b);
  /* debug information will only see the variable after this point! */
  getlocvar(fs, fs->nactvar - 1).startpc = fs->pc;
}
References adjustlocalvars(), body(), FuncState::freereg, LexState::fs, getlocvar, init_exp(), LexState::linenumber, luaK_reserveregs(), luaK_storevar(), FuncState::nactvar, new_localvar(), FuncState::pc, str_checkname(), LHS_assign::v, and VLOCAL.
Referenced by statement().
localstat()
static void localstat (LexState * ls) static
Definition at line 1179 of file lua-5.1.5/src/lparser.c.
{
  /* stat -> LOCAL NAME {`,' NAME} [`=' explist1] */
  int nvars = 0;
  int nexps;
  expdesc e;
  do {
    new_localvar(ls, str_checkname(ls), nvars++);
  } while (testnext(ls, ','));
  if (testnext(ls, '='))
    nexps = explist1(ls, &e);
  else {
    e.k = VVOID;
    nexps = 0;
  }
  adjust_assign(ls, nvars, nexps, &e);
  adjustlocalvars(ls, nvars);
}
References adjust_assign(), adjustlocalvars(), explist1(), expdesc::k, new_localvar(), str_checkname(), testnext(), and VVOID.
Referenced by statement().
luaY_parser()
Proto * luaY_parser (lua_State * L, ZIO * z, Mbuffer * buff, const char * name)
Definition at line 383 of file lua-5.1.5/src/lparser.c.
{
  struct LexState lexstate;
  struct FuncState funcstate;
  lexstate.buff = buff;
  luaX_setinput(L, &lexstate, z, luaS_new(L, name));
  open_func(&lexstate, &funcstate);
  funcstate.f->is_vararg = VARARG_ISVARARG;  /* main func. is always vararg */
  luaX_next(&lexstate);  /* read first token */
  chunk(&lexstate);
  check(&lexstate, TK_EOS);
  close_func(&lexstate);
  lua_assert(funcstate.prev == NULL);
  lua_assert(funcstate.f->nups == 0);
  lua_assert(lexstate.fs == NULL);
  return funcstate.f;
}
References LexState::buff, check, chunk(), close_func(), FuncState::f, LexState::fs, Proto::is_vararg, FuncState::L, lua_assert, luaS_new, luaX_next(), luaX_setinput(), name, NULL, Proto::nups, open_func(), FuncState::prev, TK_EOS, and VARARG_ISVARARG.
markupval()
static void markupval (FuncState * fs, int level) static
Definition at line 217 of file lua-5.1.5/src/lparser.c.
{
  BlockCnt *bl = fs->bl;
  while (bl && bl->nactvar > level) bl = bl->previous;
  if (bl) bl->upval = 1;
}
References FuncState::bl, BlockCnt::nactvar, BlockCnt::previous, and BlockCnt::upval.
Referenced by singlevaraux().
new_localvar()
static void new_localvar (LexState * ls, TString * name, int n) static
Definition at line 160 of file lua-5.1.5/src/lparser.c.
{
  FuncState *fs = ls->fs;
  luaY_checklimit(fs, fs->nactvar+n+1, LUAI_MAXVARS, "local variables");
  fs->actvar[fs->nactvar+n] = cast(unsigned short, registerlocalvar(ls, name));
}
References FuncState::actvar, cast, LexState::fs, LUAI_MAXVARS, luaY_checklimit, FuncState::nactvar, name, and registerlocalvar().
Referenced by forlist(), fornum(), localfunc(), localstat(), and parlist().
open_func()
static void open_func (LexState * ls, FuncState * fs) static
Definition at line 328 of file lua-5.1.5/src/lparser.c.
{
  lua_State *L = ls->L;
  Proto *f = luaF_newproto(L);
  fs->f = f;
  fs->prev = ls->fs;  /* linked list of funcstates */
  fs->ls = ls;
  fs->L = L;
  ls->fs = fs;
  fs->pc = 0;
  fs->lasttarget = -1;
  fs->jpc = NO_JUMP;
  fs->freereg = 0;
  fs->nk = 0;
  fs->np = 0;
  fs->nlocvars = 0;
  fs->nactvar = 0;
  fs->bl = NULL;
  f->source = ls->source;
  f->maxstacksize = 2;  /* registers 0/1 are always valid */
  fs->h = luaH_new(L, 0, 0);
  /* anchor table of constants and prototype (to avoid being collected) */
  sethvalue2s(L, L->top, fs->h);
  incr_top(L);
  setptvalue2s(L, L->top, f);
  incr_top(L);
}
References FuncState::bl, FuncState::f, FuncState::freereg, LexState::fs, FuncState::h, incr_top, FuncState::jpc, LexState::L, FuncState::L, FuncState::lasttarget, FuncState::ls, luaF_newproto(), luaH_new(), Proto::maxstacksize, FuncState::nactvar, FuncState::nk, FuncState::nlocvars, NO_JUMP, FuncState::np, NULL, FuncState::pc, FuncState::prev, sethvalue2s, setptvalue2s, LexState::source, Proto::source, and lua_State::top.
Referenced by body(), and luaY_parser().
parlist()
static void parlist (LexState * ls) static
Definition at line 543 of file lua-5.1.5/src/lparser.c.
{
  /* parlist -> [ param { `,' param } ] */
  FuncState *fs = ls->fs;
  Proto *f = fs->f;
  int nparams = 0;
  f->is_vararg = 0;
  if (ls->t.token != ')') {  /* is `parlist' not empty? */
    do {
      switch (ls->t.token) {
        case TK_NAME: {  /* param -> NAME */
          new_localvar(ls, str_checkname(ls), nparams++);
          break;
        }
        case TK_DOTS: {  /* param -> `...' */
          luaX_next(ls);
#if defined(LUA_COMPAT_VARARG)
          /* use `arg' as default name */
          new_localvarliteral(ls, "arg", nparams++);
          f->is_vararg = VARARG_HASARG | VARARG_NEEDSARG;
#endif
          f->is_vararg |= VARARG_ISVARARG;
          break;
        }
        default: luaX_syntaxerror(ls, "<name> or " LUA_QL("...") " expected");
      }
    } while (!f->is_vararg && testnext(ls, ','));
  }
  adjustlocalvars(ls, nparams);
  f->numparams = cast_byte(fs->nactvar - (f->is_vararg & VARARG_HASARG));
  luaK_reserveregs(fs, fs->nactvar);  /* reserve register for parameters */
}
References adjustlocalvars(), cast_byte, FuncState::f, LexState::fs, Proto::is_vararg, LUA_QL, luaK_reserveregs(), luaX_next(), luaX_syntaxerror(), FuncState::nactvar, new_localvar(), new_localvarliteral, Proto::numparams, str_checkname(), LexState::t, testnext(), TK_DOTS, TK_NAME, Token::token, VARARG_HASARG, VARARG_ISVARARG, and VARARG_NEEDSARG.
Referenced by body().
prefixexp()
static void prefixexp (LexState * ls, expdesc * v) static
Definition at line 667 of file lua-5.1.5/src/lparser.c.
{
  /* prefixexp -> NAME | '(' expr ')' */
  switch (ls->t.token) {
    case '(': {
      int line = ls->linenumber;
      luaX_next(ls);
      expr(ls, v);
      check_match(ls, ')', '(', line);
      luaK_dischargevars(ls->fs, v);
      return;
    }
    case TK_NAME: {
      singlevar(ls, v);
      return;
    }
    default: {
      luaX_syntaxerror(ls, "unexpected symbol");
      return;
    }
  }
}
References check_match(), expr(), LexState::fs, LexState::linenumber, luaK_dischargevars(), luaX_next(), luaX_syntaxerror(), singlevar(), LexState::t, TK_NAME, Token::token, and ConsControl::v.
Referenced by primaryexp().
primaryexp()
static void primaryexp (LexState * ls, expdesc * v) static
Definition at line 690 of file lua-5.1.5/src/lparser.c.
{
  /* primaryexp ->
        prefixexp { `.' NAME | `[' exp `]' | `:' NAME funcargs | funcargs } */
  FuncState *fs = ls->fs;
  prefixexp(ls, v);
  for (;;) {
    switch (ls->t.token) {
      case '.': {  /* field */
        field(ls, v);
        break;
      }
      case '[': {  /* `[' exp1 `]' */
        expdesc key;
        luaK_exp2anyreg(fs, v);
        yindex(ls, &key);
        luaK_indexed(fs, v, &key);
        break;
      }
      case ':': {  /* `:' NAME funcargs */
        expdesc key;
        luaX_next(ls);
        checkname(ls, &key);
        luaK_self(fs, v, &key);
        funcargs(ls, v);
        break;
      }
      case '(': case TK_STRING: case '{': {  /* funcargs */
        luaK_exp2nextreg(fs, v);
        funcargs(ls, v);
        break;
      }
      default: return;
    }
  }
}
References checkname(), field(), LexState::fs, funcargs(), luaK_exp2anyreg(), luaK_exp2nextreg(), luaK_indexed(), luaK_self(), luaX_next(), prefixexp(), LexState::t, TK_STRING, Token::token, ConsControl::v, and yindex().
Referenced by assignment(), exprstat(), and simpleexp().
pushclosure()
static void pushclosure (LexState * ls, FuncState * func, expdesc * v) static
Definition at line 310 of file lua-5.1.5/src/lparser.c.
{
  FuncState *fs = ls->fs;
  Proto *f = fs->f;
  int oldsize = f->sizep;
  int i;
  luaM_growvector(ls->L, f->p, fs->np, f->sizep, Proto *,
                  MAXARG_Bx, "constant table overflow");
  while (oldsize < f->sizep) f->p[oldsize++] = NULL;
  f->p[fs->np++] = func->f;
  luaC_objbarrier(ls->L, f, func->f);
  init_exp(v, VRELOCABLE, luaK_codeABx(fs, OP_CLOSURE, 0, fs->np-1));
  for (i=0; i<func->f->nups; i++) {
    OpCode o = (func->upvalues[i].k == VLOCAL) ? OP_MOVE : OP_GETUPVAL;
    luaK_codeABC(fs, o, 0, func->upvalues[i].info, 0);
  }
}
References FuncState::f, LexState::fs, upvaldesc::info, init_exp(), upvaldesc::k, LexState::L, luaC_objbarrier, luaK_codeABC, luaK_codeABx(), luaM_growvector, MAXARG_Bx, FuncState::np, NULL, Proto::nups, OP_CLOSURE, OP_GETUPVAL, OP_MOVE, Proto::p, Proto::sizep, FuncState::upvalues, VLOCAL, and VRELOCABLE.
Referenced by body().
recfield()
static void recfield (LexState * ls, struct ConsControl * cc) static
Definition at line 443 of file lua-5.1.5/src/lparser.c.
{
  /* recfield -> (NAME | `['exp1`]') = exp1 */
  FuncState *fs = ls->fs;
  int reg = ls->fs->freereg;
  expdesc key, val;
  int rkkey;
  if (ls->t.token == TK_NAME) {
    luaY_checklimit(fs, cc->nh, MAX_INT, "items in a constructor");
    checkname(ls, &key);
  }
  else  /* ls->t.token == '[' */
    yindex(ls, &key);
  cc->nh++;
  checknext(ls, '=');
  rkkey = luaK_exp2RK(fs, &key);
  expr(ls, &val);
  luaK_codeABC(fs, OP_SETTABLE, cc->t->u.s.info, rkkey, luaK_exp2RK(fs, &val));
  fs->freereg = reg;  /* free registers */
}
References checkname(), checknext(), expr(), FuncState::freereg, LexState::fs, expdesc::info, luaK_codeABC, luaK_exp2RK(), luaY_checklimit, MAX_INT, ConsControl::nh, OP_SETTABLE, expdesc::s, LexState::t, ConsControl::t, TK_NAME, Token::token, expdesc::u, and yindex().
Referenced by constructor().
registerlocalvar()
static int registerlocalvar (LexState * ls, TString * varname) static
Definition at line 143 of file lua-5.1.5/src/lparser.c.
{
  FuncState *fs = ls->fs;
  Proto *f = fs->f;
  int oldsize = f->sizelocvars;
  luaM_growvector(ls->L, f->locvars, fs->nlocvars, f->sizelocvars,
                  LocVar, SHRT_MAX, "too many local variables");
  while (oldsize < f->sizelocvars) f->locvars[oldsize++].varname = NULL;
  f->locvars[fs->nlocvars].varname = varname;
  luaC_objbarrier(ls->L, f, varname);
  return fs->nlocvars++;
}
References FuncState::f, LexState::fs, LexState::L, Proto::locvars, luaC_objbarrier, luaM_growvector, FuncState::nlocvars, NULL, Proto::sizelocvars, and LocVar::varname.
Referenced by new_localvar().
removevars()
static void removevars (LexState * ls, int tolevel) static
Definition at line 176 of file lua-5.1.5/src/lparser.c.
{
  FuncState *fs = ls->fs;
  while (fs->nactvar > tolevel)
    getlocvar(fs, --fs->nactvar).endpc = fs->pc;
}
References LexState::fs, getlocvar, FuncState::nactvar, and FuncState::pc.
Referenced by close_func(), and leaveblock().
repeatstat()
static void repeatstat (LexState * ls, int line) static
Definition at line 1010 of file lua-5.1.5/src/lparser.c.
{
  /* repeatstat -> REPEAT block UNTIL cond */
  int condexit;
  FuncState *fs = ls->fs;
  int repeat_init = luaK_getlabel(fs);
  BlockCnt bl1, bl2;
  enterblock(fs, &bl1, 1);  /* loop block */
  enterblock(fs, &bl2, 0);  /* scope block */
  luaX_next(ls);  /* skip REPEAT */
  chunk(ls);
  check_match(ls, TK_UNTIL, TK_REPEAT, line);
  condexit = cond(ls);  /* read condition (inside scope block) */
  if (!bl2.upval) {  /* no upvalues? */
    leaveblock(fs);  /* finish scope */
    luaK_patchlist(ls->fs, condexit, repeat_init);  /* close the loop */
  }
  else {  /* complete semantics when there are upvalues */
    breakstat(ls);  /* if condition then break */
    luaK_patchtohere(ls->fs, condexit);  /* else... */
    leaveblock(fs);  /* finish scope... */
    luaK_patchlist(ls->fs, luaK_jump(fs), repeat_init);  /* and repeat */
  }
  leaveblock(fs);  /* finish loop */
}
References breakstat(), check_match(), chunk(), cond(), enterblock(), LexState::fs, leaveblock(), luaK_getlabel(), luaK_jump(), luaK_patchlist(), luaK_patchtohere(), luaX_next(), TK_REPEAT, TK_UNTIL, and BlockCnt::upval.
Referenced by statement().
retstat()
static void retstat (LexState * ls) static
Definition at line 1238 of file lua-5.1.5/src/lparser.c.
{
  /* stat -> RETURN explist */
  FuncState *fs = ls->fs;
  expdesc e;
  int first, nret;  /* registers with returned values */
  luaX_next(ls);  /* skip RETURN */
  if (block_follow(ls->t.token) || ls->t.token == ';')
    first = nret = 0;  /* return no values */
  else {
    nret = explist1(ls, &e);  /* optional return values */
    if (hasmultret(e.k)) {
      luaK_setmultret(fs, &e);
      if (e.k == VCALL && nret == 1) {  /* tail call? */
        SET_OPCODE(getcode(fs,&e), OP_TAILCALL);
        lua_assert(GETARG_A(getcode(fs,&e)) == fs->nactvar);
      }
      first = fs->nactvar;
      nret = LUA_MULTRET;  /* return all values */
    }
    else {
      if (nret == 1)  /* only one single value? */
        first = luaK_exp2anyreg(fs, &e);
      else {
        luaK_exp2nextreg(fs, &e);  /* values must go to the `stack' */
        first = fs->nactvar;  /* return all `active' values */
        lua_assert(nret == fs->freereg - first);
      }
    }
  }
  luaK_ret(fs, first, nret);
}
References block_follow(), explist1(), FuncState::freereg, LexState::fs, GETARG_A, getcode, hasmultret, expdesc::k, lua_assert, LUA_MULTRET, luaK_exp2anyreg(), luaK_exp2nextreg(), luaK_ret(), luaK_setmultret, luaX_next(), FuncState::nactvar, OP_TAILCALL, SET_OPCODE, LexState::t, Token::token, and VCALL.
Referenced by statement().
searchvar()
static int searchvar (FuncState * fs, TString * n) static
Definition at line 207 of file lua-5.1.5/src/lparser.c.
{
  int i;
  for (i=fs->nactvar-1; i >= 0; i--) {
    if (n == getlocvar(fs, i).varname)
      return i;
  }
  return -1;  /* not found */
}
References getlocvar, and FuncState::nactvar.
Referenced by singlevaraux().
simpleexp()
static void simpleexp (LexState * ls, expdesc * v) static
Definition at line 727 of file lua-5.1.5/src/lparser.c.
{
  /* simpleexp -> NUMBER | STRING | NIL | true | false | ... |
                  constructor | FUNCTION body | primaryexp */
  switch (ls->t.token) {
    case TK_NUMBER: {
      init_exp(v, VKNUM, 0);
      v->u.nval = ls->t.seminfo.r;
      break;
    }
    case TK_STRING: {
      codestring(ls, v, ls->t.seminfo.ts);
      break;
    }
    case TK_NIL: {
      init_exp(v, VNIL, 0);
      break;
    }
    case TK_TRUE: {
      init_exp(v, VTRUE, 0);
      break;
    }
    case TK_FALSE: {
      init_exp(v, VFALSE, 0);
      break;
    }
    case TK_DOTS: {  /* vararg */
      FuncState *fs = ls->fs;
      check_condition(ls, fs->f->is_vararg,
                      "cannot use " LUA_QL("...") " outside a vararg function");
      fs->f->is_vararg &= ~VARARG_NEEDSARG;  /* don't need 'arg' */
      init_exp(v, VVARARG, luaK_codeABC(fs, OP_VARARG, 0, 1, 0));
      break;
    }
    case '{': {  /* constructor */
      constructor(ls, v);
      return;
    }
    case TK_FUNCTION: {
      luaX_next(ls);
      body(ls, v, 0, ls->linenumber);
      return;
    }
    default: {
      primaryexp(ls, v);
      return;
    }
  }
  luaX_next(ls);
}
References body(), check_condition, codestring(), constructor(), FuncState::f, LexState::fs, init_exp(), Proto::is_vararg, LexState::linenumber, LUA_QL, luaK_codeABC, luaX_next(), expdesc::nval, OP_VARARG, primaryexp(), SemInfo::r, Token::seminfo, LexState::t, TK_DOTS, TK_FALSE, TK_FUNCTION, TK_NIL, TK_NUMBER, TK_STRING, TK_TRUE, Token::token, SemInfo::ts, expdesc::u, ConsControl::v, VFALSE, VKNUM, VNIL, VTRUE, and VVARARG.
Referenced by subexpr().
singlevar()
static void singlevar (LexState * ls, expdesc * var) static
Definition at line 248 of file lua-5.1.5/src/lparser.c.
{
  TString *varname = str_checkname(ls);
  FuncState *fs = ls->fs;
  if (singlevaraux(fs, varname, var, 1) == VGLOBAL)
    var->u.s.info = luaK_stringK(fs, varname);  /* info points to global name */
}
References LexState::fs, expdesc::info, luaK_stringK(), expdesc::s, singlevaraux(), str_checkname(), expdesc::u, and VGLOBAL.
Referenced by funcname(), and prefixexp().
singlevaraux()
static int singlevaraux (FuncState * fs, TString * n, expdesc * var, int base) static
Definition at line 224 of file lua-5.1.5/src/lparser.c.
{
  if (fs == NULL) {  /* no more levels? */
    init_exp(var, VGLOBAL, NO_REG);  /* default is global variable */
    return VGLOBAL;
  }
  else {
    int v = searchvar(fs, n);  /* look up at current level */
    if (v >= 0) {
      init_exp(var, VLOCAL, v);
      if (!base)
        markupval(fs, v);  /* local will be used as an upval */
      return VLOCAL;
    }
    else {  /* not found at current level; try upper one */
      if (singlevaraux(fs->prev, n, var, 0) == VGLOBAL)
        return VGLOBAL;
      var->u.s.info = indexupvalue(fs, n, var);  /* else was LOCAL or UPVAL */
      var->k = VUPVAL;  /* upvalue in this level */
      return VUPVAL;
    }
  }
}
References indexupvalue(), expdesc::info, init_exp(), expdesc::k, markupval(), NO_REG, NULL, FuncState::prev, expdesc::s, searchvar(), singlevaraux(), expdesc::u, VGLOBAL, VLOCAL, and VUPVAL.
Referenced by singlevar(), and singlevaraux().
statement()
static int statement (LexState * ls) static
Definition at line 1271 of file lua-5.1.5/src/lparser.c.
{
  int line = ls->linenumber;  /* may be needed for error messages */
  switch (ls->t.token) {
    case TK_IF: {  /* stat -> ifstat */
      ifstat(ls, line);
      return 0;
    }
    case TK_WHILE: {  /* stat -> whilestat */
      whilestat(ls, line);
      return 0;
    }
    case TK_DO: {  /* stat -> DO block END */
      luaX_next(ls);  /* skip DO */
      block(ls);
      check_match(ls, TK_END, TK_DO, line);
      return 0;
    }
    case TK_FOR: {  /* stat -> forstat */
      forstat(ls, line);
      return 0;
    }
    case TK_REPEAT: {  /* stat -> repeatstat */
      repeatstat(ls, line);
      return 0;
    }
    case TK_FUNCTION: {
      funcstat(ls, line);  /* stat -> funcstat */
      return 0;
    }
    case TK_LOCAL: {  /* stat -> localstat */
      luaX_next(ls);  /* skip LOCAL */
      if (testnext(ls, TK_FUNCTION))  /* local function? */
        localfunc(ls);
      else
        localstat(ls);
      return 0;
    }
    case TK_RETURN: {  /* stat -> retstat */
      retstat(ls);
      return 1;  /* must be last statement */
    }
    case TK_BREAK: {  /* stat -> breakstat */
      luaX_next(ls);  /* skip BREAK */
      breakstat(ls);
      return 1;  /* must be last statement */
    }
    default: {
      exprstat(ls);
      return 0;  /* to avoid warnings */
    }
  }
}
References block(), breakstat(), check_match(), exprstat(), forstat(), funcstat(), ifstat(), LexState::linenumber, localfunc(), localstat(), luaX_next(), repeatstat(), retstat(), LexState::t, testnext(), TK_BREAK, TK_DO, TK_END, TK_FOR, TK_FUNCTION, TK_IF, TK_LOCAL, TK_REPEAT, TK_RETURN, TK_WHILE, Token::token, and whilestat().
Referenced by chunk().
str_checkname()
static TString * str_checkname (LexState * ls) static
Definition at line 117 of file lua-5.1.5/src/lparser.c.
{
  TString *ts;
  check(ls, TK_NAME);
  ts = ls->t.seminfo.ts;
  luaX_next(ls);
  return ts;
}
References check, luaX_next(), Token::seminfo, LexState::t, TK_NAME, and SemInfo::ts.
Referenced by checkname(), forlist(), forstat(), localfunc(), localstat(), parlist(), and singlevar().
subexpr()
static BinOpr subexpr (LexState * ls, expdesc * v, unsigned int limit) static
Definition at line 828 of file lua-5.1.5/src/lparser.c.
{
  BinOpr op;
  UnOpr uop;
  enterlevel(ls);
  uop = getunopr(ls->t.token);
  if (uop != OPR_NOUNOPR) {
    luaX_next(ls);
    subexpr(ls, v, UNARY_PRIORITY);
    luaK_prefix(ls->fs, uop, v);
  }
  else simpleexp(ls, v);
  /* expand while operators have priorities higher than `limit' */
  op = getbinopr(ls->t.token);
  while (op != OPR_NOBINOPR && priority[op].left > limit) {
    expdesc v2;
    BinOpr nextop;
    luaX_next(ls);
    luaK_infix(ls->fs, op, v);
    /* read sub-expression with higher priority */
    nextop = subexpr(ls, &v2, priority[op].right);
    luaK_posfix(ls->fs, op, v, &v2);
    op = nextop;
  }
  leavelevel(ls);
  return op;  /* return first untreated operator */
}
References enterlevel, LexState::fs, getbinopr(), getunopr(), leavelevel, left, luaK_infix(), luaK_posfix(), luaK_prefix(), luaX_next(), OPR_NOBINOPR, OPR_NOUNOPR, priority, right, simpleexp(), subexpr(), LexState::t, Token::token, and UNARY_PRIORITY.
Referenced by expr(), and subexpr().
test_then_block()
static int test_then_block (LexState * ls) static
Definition at line 1130 of file lua-5.1.5/src/lparser.c.
{
  /* test_then_block -> [IF | ELSEIF] cond THEN block */
  int condexit;
  luaX_next(ls);  /* skip IF or ELSEIF */
  condexit = cond(ls);
  checknext(ls, TK_THEN);
  block(ls);  /* `then' part */
  return condexit;
}
References block(), checknext(), cond(), luaX_next(), and TK_THEN.
Referenced by ifstat().
testnext()
static int testnext (LexState * ls, int c) static
Definition at line 80 of file lua-5.1.5/src/lparser.c.
{
  if (ls->t.token == c) {
    luaX_next(ls);
    return 1;
  }
  else return 0;
}
References luaX_next(), LexState::t, and Token::token.
Referenced by assignment(), check_match(), chunk(), constructor(), explist1(), forlist(), fornum(), localstat(), parlist(), and statement().
whilestat()
static void whilestat (LexState * ls, int line) static
Definition at line 991 of file lua-5.1.5/src/lparser.c.
{
  /* whilestat -> WHILE cond DO block END */
  FuncState *fs = ls->fs;
  int whileinit;
  int condexit;
  BlockCnt bl;
  luaX_next(ls);  /* skip WHILE */
  whileinit = luaK_getlabel(fs);
  condexit = cond(ls);
  enterblock(fs, &bl, 1);
  checknext(ls, TK_DO);
  block(ls);
  luaK_patchlist(fs, luaK_jump(fs), whileinit);
  check_match(ls, TK_END, TK_WHILE, line);
  leaveblock(fs);
  luaK_patchtohere(fs, condexit);  /* false conditions finish the loop */
}
References block(), check_match(), checknext(), cond(), enterblock(), LexState::fs, leaveblock(), luaK_getlabel(), luaK_jump(), luaK_patchlist(), luaK_patchtohere(), luaX_next(), TK_DO, TK_END, and TK_WHILE.
Referenced by statement().
yindex()
static void yindex (LexState * ls, expdesc * v) static
Definition at line 418 of file lua-5.1.5/src/lparser.c.
{
  /* index -> '[' expr ']' */
  luaX_next(ls);  /* skip the '[' */
  expr(ls, v);
  luaK_exp2val(ls->fs, v);
  checknext(ls, ']');
}
References checknext(), expr(), LexState::fs, FuncState::ls, luaK_exp2val(), and luaX_next().
Referenced by primaryexp(), and recfield().
Variable Documentation
left
lu_byte left
Definition at line 811 of file lua-5.1.5/src/lparser.c.
Referenced by duk__enc_quote_string(), duk__expr_led(), duk__transform_callback_decode_uri(), duk__transform_callback_unescape(), duk_bi_string_prototype_replace(), graphene_simd4x4f_init_frustum(), graphene_simd4x4f_init_ortho(), and subexpr().
[struct]
const struct { ... } priority[]
Initial value:
= {
   {6, 6}, {6, 6}, {7, 7}, {7, 7}, {7, 7},
   {10, 9}, {5, 4},
   {3, 3}, {3, 3},
   {3, 3}, {3, 3}, {3, 3}, {3, 3},
   {2, 2}, {1, 1}
}
Referenced by subexpr().
right
lu_byte right
Definition at line 812 of file lua-5.1.5/src/lparser.c.
Referenced by graphene_simd4x4f_init_frustum(), graphene_simd4x4f_init_ortho(), and subexpr().