Github User Fetcher: ldo.c File Reference
ldo.c File Reference
#include <setjmp.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lundump.h"
#include "lvm.h"
#include "lzio.h"
Data Structures
struct lua_longjmp
struct SParser
Macros
#define ldo_c
#define LUA_CORE
#define LUAI_THROW(L, c) longjmp((c)->b, 1)
#define LUAI_TRY(L, c, a) if (setjmp((c)->b) == 0) { a }
#define luai_jmpbuf jmp_buf
#define ERRORSTACKSIZE (LUAI_MAXSTACK + 200)
#define next_ci(L) (L->ci = (L->ci->next ? L->ci->next : luaE_extendCI(L)))
Functions
static void seterrorobj (lua_State *L, int errcode, StkId oldtop)
l_noret luaD_throw (lua_State *L, int errcode)
int luaD_rawrunprotected (lua_State *L, Pfunc f, void *ud)
static void correctstack (lua_State *L, TValue *oldstack)
void luaD_reallocstack (lua_State *L, int newsize)
void luaD_growstack (lua_State *L, int n)
static int stackinuse (lua_State *L)
void luaD_shrinkstack (lua_State *L)
void luaD_hook (lua_State *L, int event, int line)
static void callhook (lua_State *L, CallInfo *ci)
static StkId adjust_varargs (lua_State *L, Proto *p, int actual)
static StkId tryfuncTM (lua_State *L, StkId func)
int luaD_precall (lua_State *L, StkId func, int nresults)
int luaD_poscall (lua_State *L, StkId firstResult)
void luaD_call (lua_State *L, StkId func, int nResults, int allowyield)
static void finishCcall (lua_State *L)
static void unroll (lua_State *L, void *ud)
static CallInfo * findpcall (lua_State *L)
static int recover (lua_State *L, int status)
static l_noret resume_error (lua_State *L, const char *msg, StkId firstArg)
static void resume (lua_State *L, void *ud)
LUA_API int lua_resume (lua_State *L, lua_State *from, int nargs)
LUA_API int lua_yieldk (lua_State *L, int nresults, int ctx, lua_CFunction k)
int luaD_pcall (lua_State *L, Pfunc func, void *u, ptrdiff_t old_top, ptrdiff_t ef)
static void checkmode (lua_State *L, const char *mode, const char *x)
static void f_parser (lua_State *L, void *ud)
int luaD_protectedparser (lua_State *L, ZIO *z, const char *name, const char *mode)
Macro Definition Documentation
ERRORSTACKSIZE
#define ERRORSTACKSIZE (LUAI_MAXSTACK + 200)
Definition at line 158 of file lua-5.2.4/src/ldo.c.
Referenced by luaD_growstack(), and luaD_reallocstack().
ldo_c
#define ldo_c
Definition at line 12 of file lua-5.2.4/src/ldo.c.
LUA_CORE
#define LUA_CORE
Definition at line 13 of file lua-5.2.4/src/ldo.c.
luai_jmpbuf
#define luai_jmpbuf jmp_buf
Definition at line 68 of file lua-5.2.4/src/ldo.c.
LUAI_THROW
#define LUAI_THROW (L, c) longjmp((c)->b, 1)
Definition at line 66 of file lua-5.2.4/src/ldo.c.
Referenced by luaD_throw().
LUAI_TRY
#define LUAI_TRY (L, c, a) if (setjmp((c)->b) == 0) { a }
Definition at line 67 of file lua-5.2.4/src/ldo.c.
Referenced by luaD_rawrunprotected().
next_ci
#define next_ci (L) (L->ci = (L->ci->next ? L->ci->next : luaE_extendCI(L)))
Definition at line 290 of file lua-5.2.4/src/ldo.c.
Referenced by luaD_precall().
Function Documentation
adjust_varargs()
static StkId adjust_varargs (lua_State * L, Proto * p, int actual) static
Definition at line 257 of file lua-5.2.4/src/ldo.c.
{
  int i;
  int nfixargs = p->numparams;
  StkId base, fixed;
  lua_assert(actual >= nfixargs);
  /* move fixed parameters to final position */
  luaD_checkstack(L, p->maxstacksize);  /* check again for new 'base' */
  fixed = L->top - actual;  /* first fixed argument */
  base = L->top;  /* final position of first argument */
  for (i=0; i<nfixargs; i++) {
    setobjs2s(L, L->top++, fixed + i);
    setnilvalue(fixed + i);
  }
  return base;
}
References lua_assert, luaD_checkstack, Proto::maxstacksize, Proto::numparams, setnilvalue, setobjs2s, and lua_State::top.
Referenced by luaD_precall().
callhook()
static void callhook (lua_State * L, CallInfo * ci) static
Definition at line 244 of file lua-5.2.4/src/ldo.c.
{
  int hook = LUA_HOOKCALL;
  ci->u.l.savedpc++;  /* hooks assume 'pc' is already incremented */
  if (isLua(ci->previous) &&
      GET_OPCODE(*(ci->previous->u.l.savedpc - 1)) == OP_TAILCALL) {
    ci->callstatus |= CIST_TAIL;
    hook = LUA_HOOKTAILCALL;
  }
  luaD_hook(L, hook, -1);
  ci->u.l.savedpc--;  /* correct 'pc' */
}
References CallInfo::callstatus, CIST_TAIL, GET_OPCODE, isLua, CallInfo::l, LUA_HOOKCALL, LUA_HOOKTAILCALL, luaD_hook(), OP_TAILCALL, CallInfo::previous, CallInfo::savedpc, and CallInfo::u.
Referenced by luaD_precall().
checkmode()
static void checkmode (lua_State * L, const char * mode, const char * x) static
Definition at line 631 of file lua-5.2.4/src/ldo.c.
{
  if (mode && strchr(mode, x[0]) == NULL) {
    luaO_pushfstring(L,
       "attempt to load a %s chunk (mode is " LUA_QS ")", x, mode);
    luaD_throw(L, LUA_ERRSYNTAX);
  }
}
References LUA_ERRSYNTAX, LUA_QS, luaD_throw(), luaO_pushfstring(), and NULL.
Referenced by f_parser().
correctstack()
static void correctstack (lua_State * L, TValue * oldstack) static
Definition at line 142 of file lua-5.2.4/src/ldo.c.
{
  CallInfo *ci;
  GCObject *up;
  L->top = (L->top - oldstack) + L->stack;
  for (up = L->openupval; up != NULL; up = up->gch.next)
    gco2uv(up)->v = (gco2uv(up)->v - oldstack) + L->stack;
  for (ci = L->ci; ci != NULL; ci = ci->previous) {
    ci->top = (ci->top - oldstack) + L->stack;
    ci->func = (ci->func - oldstack) + L->stack;
    if (isLua(ci))
      ci->u.l.base = (ci->u.l.base - oldstack) + L->stack;
  }
}
References CallInfo::base, lua_State::ci, CallInfo::func, GCObject::gch, gco2uv, isLua, CallInfo::l, NULL, lua_State::openupval, CallInfo::previous, lua_State::stack, CallInfo::top, lua_State::top, and CallInfo::u.
Referenced by luaD_reallocstack().
f_parser()
static void f_parser (lua_State * L, void * ud) static
Definition at line 640 of file lua-5.2.4/src/ldo.c.
{
  int i;
  Closure *cl;
  struct SParser *p = cast(struct SParser *, ud);
  int c = zgetc(p->z);  /* read first character */
  if (c == LUA_SIGNATURE[0]) {
    checkmode(L, p->mode, "binary");
    cl = luaU_undump(L, p->z, &p->buff, p->name);
  }
  else {
    checkmode(L, p->mode, "text");
    cl = luaY_parser(L, p->z, &p->buff, &p->dyd, p->name, c);
  }
  lua_assert(cl->l.nupvalues == cl->l.p->sizeupvalues);
  for (i = 0; i < cl->l.nupvalues; i++) {  /* initialize upvalues */
    UpVal *up = luaF_newupval(L);
    cl->l.upvals[i] = up;
    luaC_objbarrier(L, cl, up);
  }
}
References SParser::buff, cast, checkmode(), SParser::dyd, Closure::l, lua_assert, LUA_SIGNATURE, luaC_objbarrier, luaF_newupval(), luaU_undump(), luaY_parser(), SParser::mode, SParser::name, LClosure::p, Proto::sizeupvalues, LClosure::upvals, SParser::z, and zgetc.
Referenced by luaD_protectedparser().
findpcall()
static CallInfo * findpcall (lua_State * L) static
Definition at line 451 of file lua-5.2.4/src/ldo.c.
{
  CallInfo *ci;
  for (ci = L->ci; ci != NULL; ci = ci->previous) {  /* search for a pcall */
    if (ci->callstatus & CIST_YPCALL)
      return ci;
  }
  return NULL;  /* no pending pcall */
}
References CallInfo::callstatus, lua_State::ci, CIST_YPCALL, NULL, and CallInfo::previous.
Referenced by recover().
finishCcall()
static void finishCcall (lua_State * L) static
Definition at line 408 of file lua-5.2.4/src/ldo.c.
{
  CallInfo *ci = L->ci;
  int n;
  lua_assert(ci->u.c.k != NULL);  /* must have a continuation */
  lua_assert(L->nny == 0);
  if (ci->callstatus & CIST_YPCALL) {  /* was inside a pcall? */
    ci->callstatus &= ~CIST_YPCALL;  /* finish 'lua_pcall' */
    L->errfunc = ci->u.c.old_errfunc;
  }
  /* finish 'lua_callk'/'lua_pcall' */
  adjustresults(L, ci->nresults);
  /* call continuation function */
  if (!(ci->callstatus & CIST_STAT))  /* no call status? */
    ci->u.c.status = LUA_YIELD;  /* 'default' status */
  lua_assert(ci->u.c.status != LUA_OK);
  ci->callstatus = (ci->callstatus & ~(CIST_YPCALL | CIST_STAT)) | CIST_YIELDED;
  lua_unlock(L);
  n = (*ci->u.c.k)(L);
  lua_lock(L);
  api_checknelems(L, n);
  /* finish 'luaD_precall' */
  luaD_poscall(L, L->top - n);
}
References adjustresults, api_checknelems, CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_STAT, CIST_YIELDED, CIST_YPCALL, lua_State::errfunc, CallInfo::k, lua_assert, lua_lock, LUA_OK, lua_unlock, LUA_YIELD, luaD_poscall(), lua_State::nny, CallInfo::nresults, NULL, CallInfo::old_errfunc, CallInfo::status, lua_State::top, and CallInfo::u.
Referenced by unroll().
lua_resume()
LUA_API int lua_resume (lua_State * L, lua_State * from, int nargs)
Definition at line 535 of file lua-5.2.4/src/ldo.c.
{
  int status;
  int oldnny = L->nny;  /* save 'nny' */
  lua_lock(L);
  luai_userstateresume(L, nargs);
  L->nCcalls = (from) ? from->nCcalls + 1 : 1;
  L->nny = 0;  /* allow yields */
  api_checknelems(L, (L->status == LUA_OK) ? nargs + 1 : nargs);
  status = luaD_rawrunprotected(L, resume, L->top - nargs);
  if (status == -1)  /* error calling 'lua_resume'? */
    status = LUA_ERRRUN;
  else {  /* yield or regular error */
    while (status != LUA_OK && status != LUA_YIELD) {  /* error? */
      if (recover(L, status))  /* recover point? */
        status = luaD_rawrunprotected(L, unroll, NULL);  /* run continuation */
      else {  /* unrecoverable error */
        L->status = cast_byte(status);  /* mark thread as `dead' */
        seterrorobj(L, status, L->top);
        L->ci->top = L->top;
        break;
      }
    }
    lua_assert(status == L->status);
  }
  L->nny = oldnny;  /* restore 'nny' */
  L->nCcalls--;
  lua_assert(L->nCcalls == ((from) ? from->nCcalls : 0));
  lua_unlock(L);
  return status;
}
References api_checknelems, cast_byte, lua_State::ci, lua_assert, LUA_ERRRUN, lua_lock, LUA_OK, lua_unlock, LUA_YIELD, luaD_rawrunprotected(), luai_userstateresume, lua_State::nCcalls, lua_State::nny, NULL, recover(), resume(), seterrorobj(), lua_longjmp::status, lua_State::status, CallInfo::top, lua_State::top, and unroll().
lua_yieldk()
LUA_API int lua_yieldk (lua_State * L, int nresults, int ctx, lua_CFunction k)
Definition at line 567 of file lua-5.2.4/src/ldo.c.
{
  CallInfo *ci = L->ci;
  luai_userstateyield(L, nresults);
  lua_lock(L);
  api_checknelems(L, nresults);
  if (L->nny > 0) {
    if (L != G(L)->mainthread)
      luaG_runerror(L, "attempt to yield across a C-call boundary");
    else
      luaG_runerror(L, "attempt to yield from outside a coroutine");
  }
  L->status = LUA_YIELD;
  ci->extra = savestack(L, ci->func);  /* save current 'func' */
  if (isLua(ci)) {  /* inside a hook? */
    api_check(L, k == NULL, "hooks cannot continue after yielding");
  }
  else {
    if ((ci->u.c.k = k) != NULL)  /* is there a continuation? */
      ci->u.c.ctx = ctx;  /* save context */
    ci->func = L->top - nresults - 1;  /* protect stack below results */
    luaD_throw(L, LUA_YIELD);
  }
  lua_assert(ci->callstatus & CIST_HOOKED);  /* must be inside a hook */
  lua_unlock(L);
  return 0;  /* return to 'luaD_hook' */
}
References api_check, api_checknelems, CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, CallInfo::ctx, CallInfo::extra, CallInfo::func, G, isLua, CallInfo::k, lua_assert, lua_lock, lua_unlock, LUA_YIELD, luaD_throw(), luaG_runerror(), luai_userstateyield, lua_State::nny, NULL, savestack, lua_State::status, lua_State::top, and CallInfo::u.
luaD_call()
void luaD_call (lua_State * L, StkId func, int nResults, int allowyield)
Definition at line 393 of file lua-5.2.4/src/ldo.c.
{
  if (++L->nCcalls >= LUAI_MAXCCALLS) {
    if (L->nCcalls == LUAI_MAXCCALLS)
      luaG_runerror(L, "C stack overflow");
    else if (L->nCcalls >= (LUAI_MAXCCALLS + (LUAI_MAXCCALLS>>3)))
      luaD_throw(L, LUA_ERRERR);  /* error while handing stack error */
  }
  if (!allowyield) L->nny++;
  if (!luaD_precall(L, func, nResults))  /* is a Lua function? */
    luaV_execute(L);  /* call it */
  if (!allowyield) L->nny--;
  L->nCcalls--;
}
References LUA_ERRERR, luaD_precall(), luaD_throw(), luaG_runerror(), LUAI_MAXCCALLS, luaV_execute(), lua_State::nCcalls, and lua_State::nny.
luaD_growstack()
void luaD_growstack (lua_State * L, int n)
Definition at line 175 of file lua-5.2.4/src/ldo.c.
{
  int size = L->stacksize;
  if (size > LUAI_MAXSTACK)  /* error after extra size? */
    luaD_throw(L, LUA_ERRERR);
  else {
    int needed = cast_int(L->top - L->stack) + n + EXTRA_STACK;
    int newsize = 2 * size;
    if (newsize > LUAI_MAXSTACK) newsize = LUAI_MAXSTACK;
    if (newsize < needed) newsize = needed;
    if (newsize > LUAI_MAXSTACK) {  /* stack overflow? */
      luaD_reallocstack(L, ERRORSTACKSIZE);
      luaG_runerror(L, "stack overflow");
    }
    else
      luaD_reallocstack(L, newsize);
  }
}
References cast_int, ERRORSTACKSIZE, EXTRA_STACK, LUA_ERRERR, luaD_reallocstack(), luaD_throw(), luaG_runerror(), LUAI_MAXSTACK, lua_State::stack, lua_State::stacksize, and lua_State::top.
luaD_hook()
void luaD_hook (lua_State * L, int event, int line)
Definition at line 217 of file lua-5.2.4/src/ldo.c.
{
  lua_Hook hook = L->hook;
  if (hook && L->allowhook) {
    CallInfo *ci = L->ci;
    ptrdiff_t top = savestack(L, L->top);
    ptrdiff_t ci_top = savestack(L, ci->top);
    lua_Debug ar;
    ar.event = event;
    ar.currentline = line;
    ar.i_ci = ci;
    luaD_checkstack(L, LUA_MINSTACK);  /* ensure minimum stack size */
    ci->top = L->top + LUA_MINSTACK;
    lua_assert(ci->top <= L->stack_last);
    L->allowhook = 0;  /* cannot call hooks inside a hook */
    ci->callstatus |= CIST_HOOKED;
    lua_unlock(L);
    (*hook)(L, &ar);
    lua_lock(L);
    lua_assert(!L->allowhook);
    L->allowhook = 1;
    ci->top = restorestack(L, ci_top);
    L->top = restorestack(L, top);
    ci->callstatus &= ~CIST_HOOKED;
  }
}
References lua_State::allowhook, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, lua_Debug::currentline, lua_Debug::event, lua_State::hook, lua_Debug::i_ci, lua_assert, lua_lock, LUA_MINSTACK, lua_unlock, luaD_checkstack, restorestack, savestack, lua_State::stack_last, CallInfo::top, and lua_State::top.
Referenced by callhook(), luaD_poscall(), luaD_precall(), luaG_traceexec(), luaG_traceexec(), and traceexec().
luaD_pcall()
int luaD_pcall (lua_State * L, Pfunc func, void * u, ptrdiff_t old_top, ptrdiff_t ef)
Definition at line 595 of file lua-5.2.4/src/ldo.c.
{
  int status;
  CallInfo *old_ci = L->ci;
  lu_byte old_allowhooks = L->allowhook;
  unsigned short old_nny = L->nny;
  ptrdiff_t old_errfunc = L->errfunc;
  L->errfunc = ef;
  status = luaD_rawrunprotected(L, func, u);
  if (status != LUA_OK) {  /* an error occurred? */
    StkId oldtop = restorestack(L, old_top);
    luaF_close(L, oldtop);  /* close possible pending closures */
    seterrorobj(L, status, oldtop);
    L->ci = old_ci;
    L->allowhook = old_allowhooks;
    L->nny = old_nny;
    luaD_shrinkstack(L);
  }
  L->errfunc = old_errfunc;
  return status;
}
References lua_State::allowhook, lua_State::ci, lua_State::errfunc, LUA_OK, luaD_rawrunprotected(), luaD_shrinkstack(), luaF_close(), lua_State::nny, restorestack, seterrorobj(), and lua_longjmp::status.
Referenced by luaD_protectedparser().
luaD_poscall()
int luaD_poscall (lua_State * L, StkId firstResult)
Definition at line 362 of file lua-5.2.4/src/ldo.c.
{
  StkId res;
  int wanted, i;
  CallInfo *ci = L->ci;
  if (L->hookmask & (LUA_MASKRET | LUA_MASKLINE)) {
    if (L->hookmask & LUA_MASKRET) {
      ptrdiff_t fr = savestack(L, firstResult);  /* hook may change stack */
      luaD_hook(L, LUA_HOOKRET, -1);
      firstResult = restorestack(L, fr);
    }
    L->oldpc = ci->previous->u.l.savedpc;  /* 'oldpc' for caller function */
  }
  res = ci->func;  /* res == final position of 1st result */
  wanted = ci->nresults;
  L->ci = ci = ci->previous;  /* back to caller */
  /* move results to correct place */
  for (i = wanted; i != 0 && firstResult < L->top; i--)
    setobjs2s(L, res++, firstResult++);
  while (i-- > 0)
    setnilvalue(res++);
  L->top = res;
  return (wanted - LUA_MULTRET);  /* 0 iff wanted == LUA_MULTRET */
}
References lua_State::ci, CallInfo::func, lua_State::hookmask, CallInfo::l, LUA_HOOKRET, LUA_MASKLINE, LUA_MASKRET, LUA_MULTRET, luaD_hook(), CallInfo::nresults, lua_State::oldpc, CallInfo::previous, restorestack, CallInfo::savedpc, savestack, setnilvalue, setobjs2s, lua_State::top, and CallInfo::u.
Referenced by finishCcall(), luaD_precall(), and resume().
luaD_precall()
int luaD_precall (lua_State * L, StkId func, int nresults)
Definition at line 296 of file lua-5.2.4/src/ldo.c.
{
  lua_CFunction f;
  CallInfo *ci;
  int n;  /* number of arguments (Lua) or returns (C) */
  ptrdiff_t funcr = savestack(L, func);
  switch (ttype(func)) {
    case LUA_TLCF:  /* light C function */
      f = fvalue(func);
      goto Cfunc;
    case LUA_TCCL: {  /* C closure */
      f = clCvalue(func)->f;
     Cfunc:
      luaD_checkstack(L, LUA_MINSTACK);  /* ensure minimum stack size */
      ci = next_ci(L);  /* now 'enter' new function */
      ci->nresults = nresults;
      ci->func = restorestack(L, funcr);
      ci->top = L->top + LUA_MINSTACK;
      lua_assert(ci->top <= L->stack_last);
      ci->callstatus = 0;
      luaC_checkGC(L);  /* stack grow uses memory */
      if (L->hookmask & LUA_MASKCALL)
        luaD_hook(L, LUA_HOOKCALL, -1);
      lua_unlock(L);
      n = (*f)(L);  /* do the actual call */
      lua_lock(L);
      api_checknelems(L, n);
      luaD_poscall(L, L->top - n);
      return 1;
    }
    case LUA_TLCL: {  /* Lua function: prepare its call */
      StkId base;
      Proto *p = clLvalue(func)->p;
      n = cast_int(L->top - func) - 1;  /* number of real arguments */
      luaD_checkstack(L, p->maxstacksize);
      for (; n < p->numparams; n++)
        setnilvalue(L->top++);  /* complete missing arguments */
      if (!p->is_vararg) {
        func = restorestack(L, funcr);
        base = func + 1;
      }
      else {
        base = adjust_varargs(L, p, n);
        func = restorestack(L, funcr);  /* previous call can change stack */
      }
      ci = next_ci(L);  /* now 'enter' new function */
      ci->nresults = nresults;
      ci->func = func;
      ci->u.l.base = base;
      ci->top = base + p->maxstacksize;
      lua_assert(ci->top <= L->stack_last);
      ci->u.l.savedpc = p->code;  /* starting point */
      ci->callstatus = CIST_LUA;
      L->top = ci->top;
      luaC_checkGC(L);  /* stack grow uses memory */
      if (L->hookmask & LUA_MASKCALL)
        callhook(L, ci);
      return 0;
    }
    default: {  /* not a function */
      func = tryfuncTM(L, func);  /* retry with 'function' tag method */
      return luaD_precall(L, func, nresults);  /* now it must be a function */
    }
  }
}
References adjust_varargs(), api_checknelems, CallInfo::base, callhook(), CallInfo::callstatus, cast_int, CIST_LUA, clCvalue, clLvalue, Proto::code, CallInfo::func, fvalue, lua_State::hookmask, Proto::is_vararg, CallInfo::l, lua_assert, LUA_HOOKCALL, lua_lock, LUA_MASKCALL, LUA_MINSTACK, LUA_TCCL, LUA_TLCF, LUA_TLCL, lua_unlock, luaC_checkGC, luaD_checkstack, luaD_hook(), luaD_poscall(), luaD_precall(), Proto::maxstacksize, next_ci, CallInfo::nresults, Proto::numparams, Proto::p, restorestack, CallInfo::savedpc, savestack, setnilvalue, lua_State::stack_last, CallInfo::top, lua_State::top, tryfuncTM(), ttype, and CallInfo::u.
Referenced by luaD_call(), luaD_precall(), and resume().
luaD_protectedparser()
int luaD_protectedparser (lua_State * L, ZIO * z, const char * name, const char * mode)
Definition at line 662 of file lua-5.2.4/src/ldo.c.
{
  struct SParser p;
  int status;
  L->nny++;  /* cannot yield during parsing */
  p.z = z; p.name = name; p.mode = mode;
  p.dyd.actvar.arr = NULL; p.dyd.actvar.size = 0;
  p.dyd.gt.arr = NULL; p.dyd.gt.size = 0;
  p.dyd.label.arr = NULL; p.dyd.label.size = 0;
  luaZ_initbuffer(L, &p.buff);
  status = luaD_pcall(L, f_parser, &p, savestack(L, L->top), L->errfunc);
  luaZ_freebuffer(L, &p.buff);
  luaM_freearray(L, p.dyd.actvar.arr, p.dyd.actvar.size);
  luaM_freearray(L, p.dyd.gt.arr, p.dyd.gt.size);
  luaM_freearray(L, p.dyd.label.arr, p.dyd.label.size);
  L->nny--;
  return status;
}
References Dyndata::actvar, Labellist::arr, Dyndata::arr, SParser::buff, SParser::dyd, lua_State::errfunc, f_parser(), Dyndata::gt, Dyndata::label, luaD_pcall(), luaM_freearray, luaZ_freebuffer, luaZ_initbuffer, SParser::mode, name, SParser::name, lua_State::nny, NULL, savestack, Labellist::size, Dyndata::size, lua_State::top, and SParser::z.
luaD_rawrunprotected()
int luaD_rawrunprotected (lua_State * L, Pfunc f, void * ud)
Definition at line 125 of file lua-5.2.4/src/ldo.c.
{
  unsigned short oldnCcalls = L->nCcalls;
  struct lua_longjmp lj;
  lj.status = LUA_OK;
  lj.previous = L->errorJmp;  /* chain new error handler */
  L->errorJmp = &lj;
  LUAI_TRY(L, &lj,
    (*f)(L, ud);
  );
  L->errorJmp = lj.previous;  /* restore old error handler */
  L->nCcalls = oldnCcalls;
  return lj.status;
}
References lua_State::errorJmp, LUA_OK, LUAI_TRY, lua_State::nCcalls, lua_longjmp::previous, and lua_longjmp::status.
Referenced by lua_resume(), and luaD_pcall().
luaD_reallocstack()
void luaD_reallocstack (lua_State * L, int newsize)
Definition at line 161 of file lua-5.2.4/src/ldo.c.
{
  TValue *oldstack = L->stack;
  int lim = L->stacksize;
  lua_assert(newsize <= LUAI_MAXSTACK || newsize == ERRORSTACKSIZE);
  lua_assert(L->stack_last - L->stack == L->stacksize - EXTRA_STACK);
  luaM_reallocvector(L, L->stack, L->stacksize, newsize, TValue);
  for (; lim < newsize; lim++)
    setnilvalue(L->stack + lim); /* erase new segment */
  L->stacksize = newsize;
  L->stack_last = L->stack + newsize - EXTRA_STACK;
  correctstack(L, oldstack);
}
References correctstack(), ERRORSTACKSIZE, EXTRA_STACK, lua_assert, LUAI_MAXSTACK, luaM_reallocvector, setnilvalue, lua_State::stack, lua_State::stack_last, and lua_State::stacksize.
Referenced by luaD_growstack(), and luaD_shrinkstack().
luaD_shrinkstack()
void luaD_shrinkstack (lua_State * L)
Definition at line 205 of file lua-5.2.4/src/ldo.c.
{
  int inuse = stackinuse(L);
  int goodsize = inuse + (inuse / 8) + 2*EXTRA_STACK;
  if (goodsize > LUAI_MAXSTACK) goodsize = LUAI_MAXSTACK;
  if (inuse > LUAI_MAXSTACK ||  /* handling stack overflow? */
      goodsize >= L->stacksize)  /* would grow instead of shrink? */
    condmovestack(L);  /* don't change stack (change only for debugging) */
  else
    luaD_reallocstack(L, goodsize);  /* shrink it */
}
References condmovestack, EXTRA_STACK, luaD_reallocstack(), LUAI_MAXSTACK, stackinuse(), and lua_State::stacksize.
Referenced by luaD_pcall(), recover(), sweepthread(), traversethread(), and traversethread().
luaD_throw()
l_noret luaD_throw (lua_State * L, int errcode)
Definition at line 103 of file lua-5.2.4/src/ldo.c.
{
  if (L->errorJmp) {  /* thread has an error handler? */
    L->errorJmp->status = errcode;  /* set status */
    LUAI_THROW(L, L->errorJmp);  /* jump to it */
  }
  else {  /* thread has no error handler */
    L->status = cast_byte(errcode);  /* mark it as dead */
    if (G(L)->mainthread->errorJmp) {  /* main thread has a handler? */
      setobjs2s(L, G(L)->mainthread->top++, L->top - 1);  /* copy error obj. */
      luaD_throw(G(L)->mainthread, errcode);  /* re-throw in main thread */
    }
    else {  /* no handler at all; abort */
      if (G(L)->panic) {  /* panic function? */
        lua_unlock(L);
        G(L)->panic(L);  /* call it (last chance to jump out) */
      }
      abort();
    }
  }
}
References cast_byte, lua_State::errorJmp, G, lua_unlock, luaD_throw(), LUAI_THROW, panic(), setobjs2s, lua_longjmp::status, lua_State::status, and lua_State::top.
Referenced by checkmode(), lua_yieldk(), luaD_call(), luaD_growstack(), luaD_throw(), and resume_error().
recover()
static int recover (lua_State * L, int status) static
Definition at line 461 of file lua-5.2.4/src/ldo.c.
{
  StkId oldtop;
  CallInfo *ci = findpcall(L);
  if (ci == NULL) return 0;  /* no recovery point */
  /* "finish" luaD_pcall */
  oldtop = restorestack(L, ci->extra);
  luaF_close(L, oldtop);
  seterrorobj(L, status, oldtop);
  L->ci = ci;
  L->allowhook = ci->u.c.old_allowhook;
  L->nny = 0;  /* should be zero to be yieldable */
  luaD_shrinkstack(L);
  L->errfunc = ci->u.c.old_errfunc;
  ci->callstatus |= CIST_STAT;  /* call has error status */
  ci->u.c.status = status;  /* (here it is) */
  return 1;  /* continue running the coroutine */
}
References lua_State::allowhook, CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_STAT, lua_State::errfunc, CallInfo::extra, findpcall(), luaD_shrinkstack(), luaF_close(), lua_State::nny, NULL, CallInfo::old_allowhook, CallInfo::old_errfunc, restorestack, seterrorobj(), lua_longjmp::status, CallInfo::status, and CallInfo::u.
Referenced by lua_resume().
resume()
static void resume (lua_State * L, void * ud) static
Definition at line 496 of file lua-5.2.4/src/ldo.c.
{
  int nCcalls = L->nCcalls;
  StkId firstArg = cast(StkId, ud);
  CallInfo *ci = L->ci;
  if (nCcalls >= LUAI_MAXCCALLS)
    resume_error(L, "C stack overflow", firstArg);
  if (L->status == LUA_OK) {  /* may be starting a coroutine */
    if (ci != &L->base_ci)  /* not in base level? */
      resume_error(L, "cannot resume non-suspended coroutine", firstArg);
    /* coroutine is in base level; start running it */
    if (!luaD_precall(L, firstArg - 1, LUA_MULTRET))  /* Lua function? */
      luaV_execute(L);  /* call it */
  }
  else if (L->status != LUA_YIELD)
    resume_error(L, "cannot resume dead coroutine", firstArg);
  else {  /* resuming from previous yield */
    L->status = LUA_OK;
    ci->func = restorestack(L, ci->extra);
    if (isLua(ci))  /* yielded inside a hook? */
      luaV_execute(L);  /* just continue running Lua code */
    else {  /* 'common' yield */
      if (ci->u.c.k != NULL) {  /* does it have a continuation? */
        int n;
        ci->u.c.status = LUA_YIELD;  /* 'default' status */
        ci->callstatus |= CIST_YIELDED;
        lua_unlock(L);
        n = (*ci->u.c.k)(L);  /* call continuation */
        lua_lock(L);
        api_checknelems(L, n);
        firstArg = L->top - n;  /* yield results come from continuation */
      }
      luaD_poscall(L, firstArg);  /* finish 'luaD_precall' */
    }
    unroll(L, NULL);
  }
  lua_assert(nCcalls == L->nCcalls);
}
References api_checknelems, lua_State::base_ci, CallInfo::c, CallInfo::callstatus, cast, lua_State::ci, CIST_YIELDED, CallInfo::extra, CallInfo::func, isLua, CallInfo::k, lua_assert, lua_lock, LUA_MULTRET, LUA_OK, lua_unlock, LUA_YIELD, luaD_poscall(), luaD_precall(), LUAI_MAXCCALLS, luaV_execute(), lua_State::nCcalls, NULL, restorestack, resume_error(), lua_State::status, CallInfo::status, lua_State::top, CallInfo::u, and unroll().
Referenced by lua_resume().
resume_error()
static l_noret resume_error (lua_State * L, const char * msg, StkId firstArg) static
Definition at line 485 of file lua-5.2.4/src/ldo.c.
{
  L->top = firstArg;  /* remove args from the stack */
  setsvalue2s(L, L->top, luaS_new(L, msg));  /* push error message */
  api_incr_top(L);
  luaD_throw(L, -1);  /* jump back to 'lua_resume' */
}
References api_incr_top, luaD_throw(), luaS_new, setsvalue2s, and lua_State::top.
Referenced by resume().
seterrorobj()
static void seterrorobj (lua_State * L, int errcode, StkId oldtop) static
Definition at line 84 of file lua-5.2.4/src/ldo.c.
{
  switch (errcode) {
    case LUA_ERRMEM: {  /* memory error? */
      setsvalue2s(L, oldtop, G(L)->memerrmsg); /* reuse preregistered msg. */
      break;
    }
    case LUA_ERRERR: {
      setsvalue2s(L, oldtop, luaS_newliteral(L, "error in error handling"));
      break;
    }
    default: {
      setobjs2s(L, oldtop, L->top - 1);  /* error message on current top */
      break;
    }
  }
  L->top = oldtop + 1;
}
References G, LUA_ERRERR, LUA_ERRMEM, luaS_newliteral, setobjs2s, setsvalue2s, and lua_State::top.
Referenced by lua_resume(), luaD_pcall(), and recover().
stackinuse()
static int stackinuse (lua_State * L) static
Definition at line 194 of file lua-5.2.4/src/ldo.c.
{
  CallInfo *ci;
  StkId lim = L->top;
  for (ci = L->ci; ci != NULL; ci = ci->previous) {
    lua_assert(ci->top <= L->stack_last);
    if (lim < ci->top) lim = ci->top;
  }
  return cast_int(lim - L->stack) + 1;  /* part of stack in use */
}
References cast_int, lua_State::ci, lua_assert, NULL, CallInfo::previous, lua_State::stack, lua_State::stack_last, CallInfo::top, and lua_State::top.
Referenced by luaD_shrinkstack().
tryfuncTM()
static StkId tryfuncTM (lua_State * L, StkId func) static
Definition at line 274 of file lua-5.2.4/src/ldo.c.
{
  const TValue *tm = luaT_gettmbyobj(L, func, TM_CALL);
  StkId p;
  ptrdiff_t funcr = savestack(L, func);
  if (!ttisfunction(tm))
    luaG_typeerror(L, func, "call");
  /* Open a hole inside the stack at `func' */
  for (p = L->top; p > func; p--) setobjs2s(L, p, p-1);
  incr_top(L);
  func = restorestack(L, funcr);  /* previous call may change stack */
  setobj2s(L, func, tm);  /* tag method is the new function to be called */
  return func;
}
References incr_top, luaG_typeerror(), luaT_gettmbyobj(), restorestack, savestack, setobj2s, setobjs2s, TM_CALL, lua_State::top, and ttisfunction.
Referenced by luaD_precall().
unroll()
static void unroll (lua_State * L, void * ud) static
Definition at line 433 of file lua-5.2.4/src/ldo.c.
{
  UNUSED(ud);
  for (;;) {
    if (L->ci == &L->base_ci)  /* stack is empty? */
      return;  /* coroutine finished normally */
    if (!isLua(L->ci))  /* C function? */
      finishCcall(L);
    else {  /* Lua function */
      luaV_finishOp(L);  /* finish interrupted instruction */
      luaV_execute(L);  /* execute down to higher C 'boundary' */
    }
  }
}
References lua_State::base_ci, lua_State::ci, finishCcall(), isLua, luaV_execute(), luaV_finishOp(), and UNUSED.
Referenced by lua_resume(), and resume().