Github User Fetcher: lstate.c File Reference
lstate.c File Reference
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "llex.h"
#include "lmem.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include <time.h>
Data Structures
struct LX
struct LG
Macros
#define lstate_c
#define LUA_CORE
#define LUAI_GCPAUSE 200 /* 200% */
#define LUAI_GCMAJOR 200 /* 200% */
#define LUAI_GCMUL 200 /* GC runs 'twice the speed' of memory allocation */
#define MEMERRMSG "not enough memory"
#define luai_makeseed() cast(unsigned int, time(NULL))
#define fromstate(L) (cast(LX *, cast(lu_byte *, (L)) - offsetof(LX, l)))
#define addbuff(b, p, e)
Typedefs
typedef struct LX LX
typedef struct LG LG
Functions
static unsigned int makeseed (lua_State *L)
void luaE_setdebt (global_State *g, l_mem debt)
CallInfo * luaE_extendCI (lua_State *L)
void luaE_freeCI (lua_State *L)
static void stack_init (lua_State *L1, lua_State *L)
static void freestack (lua_State *L)
static void init_registry (lua_State *L, global_State *g)
static void f_luaopen (lua_State *L, void *ud)
static void preinit_state (lua_State *L, global_State *g)
static void close_state (lua_State *L)
LUA_API lua_State * lua_newthread (lua_State *L)
void luaE_freethread (lua_State *L, lua_State *L1)
LUA_API lua_State * lua_newstate (lua_Alloc f, void *ud)
LUA_API void lua_close (lua_State *L)
Macro Definition Documentation
addbuff
#define addbuff (b, p, e)
Value:
  { size_t t = cast(size_t, e); \
    memcpy(buff + p, &t, sizeof(t)); p += sizeof(t); }
Definition at line 85 of file lua-5.2.4/src/lstate.c.
#define addbuff(b,p,e) \
  { size_t t = cast(size_t, e); \
    memcpy(buff + p, &t, sizeof(t)); p += sizeof(t); }
Referenced by makeseed().
fromstate
#define fromstate (L) (cast(LX *, cast(lu_byte *, (L)) - offsetof(LX, l)))
Definition at line 77 of file lua-5.2.4/src/lstate.c.
Referenced by close_state(), and luaE_freethread().
lstate_c
#define lstate_c
Definition at line 11 of file lua-5.2.4/src/lstate.c.
LUA_CORE
#define LUA_CORE
Definition at line 12 of file lua-5.2.4/src/lstate.c.
LUAI_GCMAJOR
#define LUAI_GCMAJOR 200 /* 200% */
Definition at line 34 of file lua-5.2.4/src/lstate.c.
Referenced by lua_newstate().
LUAI_GCMUL
#define LUAI_GCMUL 200 /* GC runs 'twice the speed' of memory allocation */
Definition at line 38 of file lua-5.2.4/src/lstate.c.
Referenced by lua_newstate().
LUAI_GCPAUSE
#define LUAI_GCPAUSE 200 /* 200% */
Definition at line 30 of file lua-5.2.4/src/lstate.c.
Referenced by lua_newstate().
luai_makeseed
#define luai_makeseed () cast(unsigned int, time(NULL))
Definition at line 51 of file lua-5.2.4/src/lstate.c.
Referenced by lua_newstate(), and makeseed().
MEMERRMSG
#define MEMERRMSG "not enough memory"
Definition at line 42 of file lua-5.2.4/src/lstate.c.
Referenced by f_luaopen().
Typedef Documentation
LG
typedef struct LG LG
LX
typedef struct LX LX
Function Documentation
close_state()
static void close_state (lua_State * L) static
Definition at line 223 of file lua-5.2.4/src/lstate.c.
{
  global_State *g = G(L);
  luaF_close(L, L->stack);  /* close all upvalues for this thread */
  luaC_freeallobjects(L);  /* collect all objects */
  if (g->version)  /* closing a fully built state? */
    luai_userstateclose(L);
  luaM_freearray(L, G(L)->strt.hash, G(L)->strt.size);
  luaZ_freebuffer(L, &g->buff);
  freestack(L);
  lua_assert(gettotalbytes(g) == sizeof(LG));
  (*g->frealloc)(g->ud, fromstate(L), sizeof(LG), 0);  /* free main block */
}
References global_State::buff, global_State::frealloc, freestack(), fromstate, G, gettotalbytes, lua_assert, luaC_freeallobjects(), luaF_close(), luai_userstateclose, luaM_freearray, luaZ_freebuffer, lua_State::stack, global_State::ud, and global_State::version.
Referenced by lua_close(), and lua_newstate().
f_luaopen()
static void f_luaopen (lua_State * L, void * ud) static
Definition at line 183 of file lua-5.2.4/src/lstate.c.
{
  global_State *g = G(L);
  UNUSED(ud);
  stack_init(L, L);  /* init stack */
  init_registry(L, g);
  luaS_resize(L, MINSTRTABSIZE);  /* initial size of string table */
  luaT_init(L);
  luaX_init(L);
  /* pre-create memory-error message */
  g->memerrmsg = luaS_newliteral(L, MEMERRMSG);
  luaS_fix(g->memerrmsg);  /* it should never be collected */
  g->gcrunning = 1;  /* allow gc */
  g->version = lua_version(NULL);
  luai_userstateopen(L);
}
References G, global_State::gcrunning, init_registry(), lua_version(), luai_userstateopen, luaS_fix, luaS_newliteral, luaS_resize(), luaT_init(), luaX_init(), MEMERRMSG, global_State::memerrmsg, MINSTRTABSIZE, NULL, stack_init(), UNUSED, and global_State::version.
Referenced by lua_newstate().
freestack()
static void freestack (lua_State * L) static
Definition at line 153 of file lua-5.2.4/src/lstate.c.
{
  if (L->stack == NULL)
    return;  /* stack not completely built yet */
  L->ci = &L->base_ci;  /* free the entire 'ci' list */
  luaE_freeCI(L);
  luaM_freearray(L, L->stack, L->stacksize);  /* free stack array */
}
References lua_State::base_ci, lua_State::ci, luaE_freeCI(), luaM_freearray, NULL, lua_State::stack, and lua_State::stacksize.
Referenced by close_state(), and luaE_freethread().
init_registry()
static void init_registry (lua_State * L, global_State * g) static
Definition at line 165 of file lua-5.2.4/src/lstate.c.
{
  TValue mt;
  /* create registry */
  Table *registry = luaH_new(L);
  sethvalue(L, &g->l_registry, registry);
  luaH_resize(L, registry, LUA_RIDX_LAST, 0);
  /* registry[LUA_RIDX_MAINTHREAD] = L */
  setthvalue(L, &mt, L);
  luaH_setint(L, registry, LUA_RIDX_MAINTHREAD, &mt);
  /* registry[LUA_RIDX_GLOBALS] = table of globals */
  sethvalue(L, &mt, luaH_new(L));
  luaH_setint(L, registry, LUA_RIDX_GLOBALS, &mt);
}
References global_State::l_registry, LUA_RIDX_GLOBALS, LUA_RIDX_LAST, LUA_RIDX_MAINTHREAD, luaH_new(), luaH_resize(), luaH_setint(), registry, sethvalue, and setthvalue.
Referenced by f_luaopen().
lua_close()
LUA_API void lua_close (lua_State * L)
Definition at line 317 of file lua-5.2.4/src/lstate.c.
{
  L = G(L)->mainthread;  /* only the main thread can be closed */
  lua_lock(L);
  close_state(L);
}
References close_state(), G, and lua_lock.
lua_newstate()
LUA_API lua_State * lua_newstate (lua_Alloc f, void * ud)
Definition at line 266 of file lua-5.2.4/src/lstate.c.
{
  int i;
  lua_State *L;
  global_State *g;
  LG *l = cast(LG *, (*f)(ud, NULL, LUA_TTHREAD, sizeof(LG)));
  if (l == NULL) return NULL;
  L = &l->l.l;
  g = &l->g;
  L->next = NULL;
  L->tt = LUA_TTHREAD;
  g->currentwhite = bit2mask(WHITE0BIT, FIXEDBIT);
  L->marked = luaC_white(g);
  g->gckind = KGC_NORMAL;
  preinit_state(L, g);
  g->frealloc = f;
  g->ud = ud;
  g->mainthread = L;
  g->seed = makeseed(L);
  g->uvhead.u.l.prev = &g->uvhead;
  g->uvhead.u.l.next = &g->uvhead;
  g->gcrunning = 0;  /* no GC while building state */
  g->GCestimate = 0;
  g->strt.size = 0;
  g->strt.nuse = 0;
  g->strt.hash = NULL;
  setnilvalue(&g->l_registry);
  luaZ_initbuffer(L, &g->buff);
  g->panic = NULL;
  g->version = NULL;
  g->gcstate = GCSpause;
  g->allgc = NULL;
  g->finobj = NULL;
  g->tobefnz = NULL;
  g->sweepgc = g->sweepfin = NULL;
  g->gray = g->grayagain = NULL;
  g->weak = g->ephemeron = g->allweak = NULL;
  g->totalbytes = sizeof(LG);
  g->GCdebt = 0;
  g->gcpause = LUAI_GCPAUSE;
  g->gcmajorinc = LUAI_GCMAJOR;
  g->gcstepmul = LUAI_GCMUL;
  for (i=0; i < LUA_NUMTAGS; i++) g->mt[i] = NULL;
  if (luaD_rawrunprotected(L, f_luaopen, NULL) != LUA_OK) {
    /* memory allocation error: free partial state */
    close_state(L);
    L = NULL;
  }
  return L;
}
References global_State::allgc, global_State::allweak, bit2mask, global_State::buff, cast, close_state(), global_State::currentwhite, global_State::ephemeron, f_luaopen(), global_State::finobj, FIXEDBIT, global_State::frealloc, LG::g, global_State::GCdebt, global_State::GCestimate, global_State::gckind, global_State::gcmajorinc, global_State::gcpause, global_State::gcrunning, GCSpause, global_State::gcstate, global_State::gcstepmul, global_State::gray, global_State::grayagain, stringtable::hash, KGC_NORMAL, UpVal::l, LG::l, global_State::l_registry, LUA_NUMTAGS, LUA_OK, LUA_TTHREAD, luaC_white, luaD_rawrunprotected(), LUAI_GCMAJOR, LUAI_GCMUL, LUAI_GCPAUSE, luaZ_initbuffer, global_State::mainthread, makeseed(), global_State::mt, UpVal::next, NULL, stringtable::nuse, global_State::panic, preinit_state(), UpVal::prev, global_State::seed, setnilvalue, stringtable::size, global_State::strt, global_State::sweepfin, global_State::sweepgc, global_State::tobefnz, global_State::totalbytes, UpVal::u, global_State::ud, global_State::uvhead, global_State::version, global_State::weak, and WHITE0BIT.
Referenced by makeseed().
lua_newthread()
LUA_API lua_State * lua_newthread (lua_State * L)
Definition at line 237 of file lua-5.2.4/src/lstate.c.
{
  lua_State *L1;
  lua_lock(L);
  luaC_checkGC(L);
  L1 = &luaC_newobj(L, LUA_TTHREAD, sizeof(LX), NULL, offsetof(LX, l))->th;
  setthvalue(L, L->top, L1);
  api_incr_top(L);
  preinit_state(L1, G(L));
  L1->hookmask = L->hookmask;
  L1->basehookcount = L->basehookcount;
  L1->hook = L->hook;
  resethookcount(L1);
  luai_userstatethread(L, L1);
  stack_init(L1, L);  /* init stack */
  lua_unlock(L);
  return L1;
}
References api_incr_top, lua_State::basehookcount, G, lua_State::hook, lua_State::hookmask, lua_lock, LUA_TTHREAD, lua_unlock, luaC_checkGC, luaC_newobj(), luai_userstatethread, NULL, offsetof, preinit_state(), resethookcount, setthvalue, stack_init(), GCObject::th, and lua_State::top.
luaE_extendCI()
CallInfo * luaE_extendCI (lua_State * L)
Definition at line 112 of file lua-5.2.4/src/lstate.c.
{
  CallInfo *ci = luaM_new(L, CallInfo);
  lua_assert(L->ci->next == NULL);
  L->ci->next = ci;
  ci->previous = L->ci;
  ci->next = NULL;
  return ci;
}
References lua_State::ci, lua_assert, luaM_new, CallInfo::next, NULL, and CallInfo::previous.
luaE_freeCI()
void luaE_freeCI (lua_State * L)
Definition at line 122 of file lua-5.2.4/src/lstate.c.
{
  CallInfo *ci = L->ci;
  CallInfo *next = ci->next;
  ci->next = NULL;
  while ((ci = next) != NULL) {
    next = ci->next;
    luaM_free(L, ci);
  }
}
References lua_State::ci, luaM_free, next, CallInfo::next, and NULL.
Referenced by freestack(), luaD_shrinkstack(), and sweepthread().
luaE_freethread()
void luaE_freethread (lua_State * L, lua_State * L1)
Definition at line 256 of file lua-5.2.4/src/lstate.c.
{
  LX *l = fromstate(L1);
  luaF_close(L1, L1->stack);  /* close all upvalues for this thread */
  lua_assert(L1->openupval == NULL);
  luai_userstatefree(L, L1);
  freestack(L1);
  luaM_free(L, l);
}
References freestack(), fromstate, lua_assert, luaF_close(), luai_userstatefree, luaM_free, NULL, lua_State::openupval, and lua_State::stack.
luaE_setdebt()
void luaE_setdebt (global_State * g, l_mem debt)
Definition at line 106 of file lua-5.2.4/src/lstate.c.
{
  g->totalbytes -= (debt - g->GCdebt);
  g->GCdebt = debt;
}
References global_State::GCdebt, and global_State::totalbytes.
Referenced by incstep(), incstep(), lua_gc(), lua_gc(), luaC_step(), setminordebt(), setpause(), setpause(), and setpause().
makeseed()
static unsigned int makeseed (lua_State * L) static
Definition at line 89 of file lua-5.2.4/src/lstate.c.
{
  char buff[4 * sizeof(size_t)];
  unsigned int h = luai_makeseed();
  int p = 0;
  addbuff(buff, p, L);  /* heap variable */
  addbuff(buff, p, &h);  /* local variable */
  addbuff(buff, p, luaO_nilobject);  /* global variable */
  addbuff(buff, p, &lua_newstate);  /* public function */
  lua_assert(p == sizeof(buff));
  return luaS_hash(buff, p, h);
}
References addbuff, lua_assert, lua_newstate(), luai_makeseed, luaO_nilobject, and luaS_hash().
Referenced by lua_newstate().
preinit_state()
static void preinit_state (lua_State * L, global_State * g) static
Definition at line 204 of file lua-5.2.4/src/lstate.c.
{
  G(L) = g;
  L->stack = NULL;
  L->ci = NULL;
  L->stacksize = 0;
  L->errorJmp = NULL;
  L->nCcalls = 0;
  L->hook = NULL;
  L->hookmask = 0;
  L->basehookcount = 0;
  L->allowhook = 1;
  resethookcount(L);
  L->openupval = NULL;
  L->nny = 1;
  L->status = LUA_OK;
  L->errfunc = 0;
}
References lua_State::allowhook, lua_State::basehookcount, lua_State::ci, lua_State::errfunc, lua_State::errorJmp, G, lua_State::hook, lua_State::hookmask, LUA_OK, lua_State::nCcalls, lua_State::nny, NULL, lua_State::openupval, resethookcount, lua_State::stack, lua_State::stacksize, and lua_State::status.
Referenced by lua_newstate(), and lua_newthread().
stack_init()
static void stack_init (lua_State * L1, lua_State * L) static
Definition at line 133 of file lua-5.2.4/src/lstate.c.
{
  int i; CallInfo *ci;
  /* initialize stack array */
  L1->stack = luaM_newvector(L, BASIC_STACK_SIZE, TValue);
  L1->stacksize = BASIC_STACK_SIZE;
  for (i = 0; i < BASIC_STACK_SIZE; i++)
    setnilvalue(L1->stack + i);  /* erase new stack */
  L1->top = L1->stack;
  L1->stack_last = L1->stack + L1->stacksize - EXTRA_STACK;
  /* initialize first ci */
  ci = &L1->base_ci;
  ci->next = ci->previous = NULL;
  ci->callstatus = 0;
  ci->func = L1->top;
  setnilvalue(L1->top++);  /* 'function' entry for this 'ci' */
  ci->top = L1->top + LUA_MINSTACK;
  L1->ci = ci;
}
References lua_State::base_ci, BASIC_STACK_SIZE, CallInfo::callstatus, lua_State::ci, EXTRA_STACK, CallInfo::func, LUA_MINSTACK, luaM_newvector, CallInfo::next, NULL, CallInfo::previous, setnilvalue, lua_State::stack, lua_State::stack_last, lua_State::stacksize, CallInfo::top, and lua_State::top.
Referenced by f_luaopen(), and lua_newthread().