Github User Fetcher: loadlib.c File Reference
loadlib.c File Reference
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define loadlib_c
#define LUA_LIB
#define LUA_PATH "LUA_PATH"
#define LUA_CPATH "LUA_CPATH"
#define LUA_PATHSUFFIX "_" LUA_VERSION_MAJOR "_" LUA_VERSION_MINOR
#define LUA_PATHVERSION LUA_PATH LUA_PATHSUFFIX
#define LUA_CPATHVERSION LUA_CPATH LUA_PATHSUFFIX
#define LUA_PATH_SEP ";"
#define LUA_PATH_MARK "?"
#define LUA_EXEC_DIR "!"
#define LUA_IGMARK "-"
#define LUA_CSUBSEP LUA_DIRSEP
#define LUA_LSUBSEP LUA_DIRSEP
#define LUA_POF "luaopen_"
#define LUA_OFSEP "_"
#define CLIBS "_CLIBS"
#define LIB_FAIL "open"
#define ERRLIB 1
#define ERRFUNC 2
#define setprogdir(L) ((void)0)
#define LIB_FAIL "absent"
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
#define AUXMARK "\1"
Functions
static void ll_unloadlib (void *lib)
static void * ll_load (lua_State *L, const char *path, int seeglb)
static lua_CFunction ll_sym (lua_State *L, void *lib, const char *sym)
static void * ll_checkclib (lua_State *L, const char *path)
static void ll_addtoclib (lua_State *L, const char *path, void *plib)
static int gctm (lua_State *L)
static int ll_loadfunc (lua_State *L, const char *path, const char *sym)
static int ll_loadlib (lua_State *L)
static int readable (const char *filename)
static const char * pushnexttemplate (lua_State *L, const char *path)
static const char * searchpath (lua_State *L, const char *name, const char *path, const char *sep, const char *dirsep)
static int ll_searchpath (lua_State *L)
static const char * findfile (lua_State *L, const char *name, const char *pname, const char *dirsep)
static int checkload (lua_State *L, int stat, const char *filename)
static int searcher_Lua (lua_State *L)
static int loadfunc (lua_State *L, const char *filename, const char *modname)
static int searcher_C (lua_State *L)
static int searcher_Croot (lua_State *L)
static int searcher_preload (lua_State *L)
static void findloader (lua_State *L, const char *name)
static int ll_require (lua_State *L)
static int noenv (lua_State *L)
static void setpath (lua_State *L, const char *fieldname, const char *envname1, const char *envname2, const char *def)
static void createsearcherstable (lua_State *L)
LUAMOD_API int luaopen_package (lua_State *L)
Variables
static const luaL_Reg pk_funcs []
static const luaL_Reg ll_funcs []
Macro Definition Documentation
AUXMARK
#define AUXMARK "\1"
Definition at line 622 of file lua-5.2.4/src/loadlib.c.
Referenced by setpath().
CLIBS
#define CLIBS "_CLIBS"
Definition at line 96 of file lua-5.2.4/src/loadlib.c.
Referenced by ll_addtoclib(), ll_checkclib(), and luaopen_package().
DLMSG
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
Definition at line 226 of file lua-5.2.4/src/loadlib.c.
Referenced by ll_load(), and ll_sym().
ERRFUNC
#define ERRFUNC 2
Definition at line 103 of file lua-5.2.4/src/loadlib.c.
Referenced by ll_loadfunc(), loadfunc(), and searcher_Croot().
ERRLIB
#define ERRLIB 1
Definition at line 102 of file lua-5.2.4/src/loadlib.c.
Referenced by ll_loadfunc(), and ll_loadlib().
LIB_FAIL [1/2]
#define LIB_FAIL "open"
Definition at line 98 of file lua-5.2.4/src/loadlib.c.
Referenced by ll_loadlib().
LIB_FAIL [2/2]
#define LIB_FAIL "absent"
Definition at line 98 of file lua-5.2.4/src/loadlib.c.
loadlib_c
#define loadlib_c
Definition at line 24 of file lua-5.2.4/src/loadlib.c.
LUA_CPATH
#define LUA_CPATH "LUA_CPATH"
Definition at line 42 of file lua-5.2.4/src/loadlib.c.
Referenced by luaopen_package().
LUA_CPATHVERSION
#define LUA_CPATHVERSION LUA_CPATH LUA_PATHSUFFIX
Definition at line 48 of file lua-5.2.4/src/loadlib.c.
Referenced by luaopen_package().
LUA_CSUBSEP
#define LUA_CSUBSEP LUA_DIRSEP
Definition at line 80 of file lua-5.2.4/src/loadlib.c.
Referenced by searcher_C(), and searcher_Croot().
LUA_EXEC_DIR
#define LUA_EXEC_DIR "!"
Definition at line 66 of file lua-5.2.4/src/loadlib.c.
Referenced by luaopen_package().
LUA_IGMARK
#define LUA_IGMARK "-"
Definition at line 69 of file lua-5.2.4/src/loadlib.c.
Referenced by loadfunc(), and luaopen_package().
LUA_LIB
#define LUA_LIB
Definition at line 25 of file lua-5.2.4/src/loadlib.c.
LUA_LSUBSEP
#define LUA_LSUBSEP LUA_DIRSEP
Definition at line 84 of file lua-5.2.4/src/loadlib.c.
Referenced by searcher_Lua().
LUA_OFSEP
#define LUA_OFSEP "_"
Definition at line 92 of file lua-5.2.4/src/loadlib.c.
Referenced by loadfunc().
LUA_PATH
#define LUA_PATH "LUA_PATH"
Definition at line 38 of file lua-5.2.4/src/loadlib.c.
Referenced by luaopen_package().
LUA_PATH_MARK
#define LUA_PATH_MARK "?"
Definition at line 63 of file lua-5.2.4/src/loadlib.c.
Referenced by luaopen_package(), and searchpath().
LUA_PATH_SEP
#define LUA_PATH_SEP ";"
Definition at line 60 of file lua-5.2.4/src/loadlib.c.
Referenced by getnextfilename(), luaopen_package(), pusherrornotfound(), pushnexttemplate(), pushnexttemplate(), setpath(), setpath(), and setpath().
LUA_PATHSUFFIX
#define LUA_PATHSUFFIX "_" LUA_VERSION_MAJOR "_" LUA_VERSION_MINOR
Definition at line 45 of file lua-5.2.4/src/loadlib.c.
LUA_PATHVERSION
#define LUA_PATHVERSION LUA_PATH LUA_PATHSUFFIX
Definition at line 47 of file lua-5.2.4/src/loadlib.c.
Referenced by luaopen_package().
LUA_POF
#define LUA_POF "luaopen_"
Definition at line 89 of file lua-5.2.4/src/loadlib.c.
Referenced by loadfunc().
setprogdir
#define setprogdir (L) ((void)0)
Definition at line 105 of file lua-5.2.4/src/loadlib.c.
Referenced by setpath().
Function Documentation
checkload()
static int checkload (lua_State * L, int stat, const char * filename) static
Definition at line 398 of file lua-5.2.4/src/loadlib.c.
{
  if (stat) {  /* module loaded successfully? */
    lua_pushstring(L, filename);  /* will be 2nd argument to module */
    return 2;  /* return open function and file name */
  }
  else
    return luaL_error(L, "error loading module " LUA_QS
                         " from file " LUA_QS ":\n\t%s",
                          lua_tostring(L, 1), filename, lua_tostring(L, -1));
}
References lua_pushstring(), LUA_QS, lua_tostring, and luaL_error().
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
createsearcherstable()
static void createsearcherstable (lua_State * L) static
Definition at line 675 of file lua-5.2.4/src/loadlib.c.
{
  static const lua_CFunction searchers[] =
    {searcher_preload, searcher_Lua, searcher_C, searcher_Croot, NULL};
  int i;
  /* create 'searchers' table */
  lua_createtable(L, sizeof(searchers)/sizeof(searchers[0]) - 1, 0);
  /* fill it with pre-defined searchers */
  for (i=0; searchers[i] != NULL; i++) {
    lua_pushvalue(L, -2);  /* set 'package' as upvalue for all searchers */
    lua_pushcclosure(L, searchers[i], 1);
    lua_rawseti(L, -2, i+1);
  }
}
References lua_createtable(), lua_pushcclosure(), lua_pushvalue(), lua_rawseti(), NULL, searcher_C(), searcher_Croot(), searcher_Lua(), and searcher_preload().
Referenced by luaopen_package().
findfile()
static const char * findfile (lua_State * L, const char * name, const char * pname, const char * dirsep) static
Definition at line 386 of file lua-5.2.4/src/loadlib.c.
{
  const char *path;
  lua_getfield(L, lua_upvalueindex(1), pname);
  path = lua_tostring(L, -1);
  if (path == NULL)
    luaL_error(L, LUA_QL("package.%s") " must be a string", pname);
  return searchpath(L, name, path, ".", dirsep);
}
References lua_getfield(), LUA_QL, lua_tostring, lua_upvalueindex, luaL_error(), name, NULL, and searchpath().
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
findloader()
static void findloader (lua_State * L, const char * name) static
Definition at line 478 of file lua-5.2.4/src/loadlib.c.
{
  int i;
  luaL_Buffer msg;  /* to build error message */
  luaL_buffinit(L, &msg);
  lua_getfield(L, lua_upvalueindex(1), "searchers");  /* will be at index 3 */
  if (!lua_istable(L, 3))
    luaL_error(L, LUA_QL("package.searchers") " must be a table");
  /*  iterate over available searchers to find a loader */
  for (i = 1; ; i++) {
    lua_rawgeti(L, 3, i);  /* get a searcher */
    if (lua_isnil(L, -1)) {  /* no more searchers? */
      lua_pop(L, 1);  /* remove nil */
      luaL_pushresult(&msg);  /* create error message */
      luaL_error(L, "module " LUA_QS " not found:%s",
                    name, lua_tostring(L, -1));
    }
    lua_pushstring(L, name);
    lua_call(L, 1, 2);  /* call it */
    if (lua_isfunction(L, -2))  /* did it find a loader? */
      return;  /* module loader found */
    else if (lua_isstring(L, -2)) {  /* searcher returned error message? */
      lua_pop(L, 1);  /* remove extra return */
      luaL_addvalue(&msg);  /* concatenate error message */
    }
    else
      lua_pop(L, 2);  /* remove both returns */
  }
}
References lua_call, lua_getfield(), lua_isfunction, lua_isnil, lua_isstring(), lua_istable, lua_pop, lua_pushstring(), LUA_QL, LUA_QS, lua_rawgeti(), lua_tostring, lua_upvalueindex, luaL_addvalue(), luaL_buffinit(), luaL_error(), luaL_pushresult(), and name.
Referenced by ll_require().
gctm()
static int gctm (lua_State * L) static
Definition at line 275 of file lua-5.2.4/src/loadlib.c.
{
  int n = luaL_len(L, 1);
  for (; n >= 1; n--) {  /* for each handle, in reverse order */
    lua_rawgeti(L, 1, n);  /* get handle CLIBS[n] */
    ll_unloadlib(lua_touserdata(L, -1));
    lua_pop(L, 1);  /* pop handle */
  }
  return 0;
}
References ll_unloadlib(), lua_pop, lua_rawgeti(), lua_touserdata(), and luaL_len().
Referenced by luaopen_package().
ll_addtoclib()
static void ll_addtoclib (lua_State * L, const char * path, void * plib) static
Definition at line 261 of file lua-5.2.4/src/loadlib.c.
{
  lua_getfield(L, LUA_REGISTRYINDEX, CLIBS);
  lua_pushlightuserdata(L, plib);
  lua_pushvalue(L, -1);
  lua_setfield(L, -3, path);  /* CLIBS[path] = plib */
  lua_rawseti(L, -2, luaL_len(L, -2) + 1);  /* CLIBS[#CLIBS + 1] = plib */
  lua_pop(L, 1);  /* pop CLIBS table */
}
References CLIBS, lua_getfield(), lua_pop, lua_pushlightuserdata(), lua_pushvalue(), lua_rawseti(), LUA_REGISTRYINDEX, lua_setfield(), and luaL_len().
Referenced by ll_loadfunc().
ll_checkclib()
static void * ll_checkclib (lua_State * L, const char * path) static
Definition at line 251 of file lua-5.2.4/src/loadlib.c.
{
  void *plib;
  lua_getfield(L, LUA_REGISTRYINDEX, CLIBS);
  lua_getfield(L, -1, path);
  plib = lua_touserdata(L, -1);  /* plib = CLIBS[path] */
  lua_pop(L, 2);  /* pop CLIBS table and 'plib' */
  return plib;
}
References CLIBS, lua_getfield(), lua_pop, LUA_REGISTRYINDEX, and lua_touserdata().
Referenced by ll_loadfunc().
ll_load()
static void * ll_load (lua_State * L, const char * path, int seeglb) static
Definition at line 234 of file lua-5.2.4/src/loadlib.c.
{
  (void)(path); (void)(seeglb);  /* not used */
  lua_pushliteral(L, DLMSG);
  return NULL;
}
References DLMSG, lua_pushliteral, and NULL.
Referenced by ll_loadfunc().
ll_loadfunc()
static int ll_loadfunc (lua_State * L, const char * path, const char * sym) static
Definition at line 286 of file lua-5.2.4/src/loadlib.c.
{
  void *reg = ll_checkclib(L, path);  /* check loaded C libraries */
  if (reg == NULL) {  /* must load library? */
    reg = ll_load(L, path, *sym == '*');
    if (reg == NULL) return ERRLIB;  /* unable to load library */
    ll_addtoclib(L, path, reg);
  }
  if (*sym == '*') {  /* loading only library (no function)? */
    lua_pushboolean(L, 1);  /* return 'true' */
    return 0;  /* no errors */
  }
  else {
    lua_CFunction f = ll_sym(L, reg, sym);
    if (f == NULL)
      return ERRFUNC;  /* unable to find function */
    lua_pushcfunction(L, f);  /* else create new function */
    return 0;  /* no errors */
  }
}
References ERRFUNC, ERRLIB, ll_addtoclib(), ll_checkclib(), ll_load(), ll_sym(), lua_pushboolean(), lua_pushcfunction, and NULL.
Referenced by ll_loadlib(), and loadfunc().
ll_loadlib()
static int ll_loadlib (lua_State * L) static
Definition at line 307 of file lua-5.2.4/src/loadlib.c.
{
  const char *path = luaL_checkstring(L, 1);
  const char *init = luaL_checkstring(L, 2);
  int stat = ll_loadfunc(L, path, init);
  if (stat == 0)  /* no errors? */
    return 1;  /* return the loaded function */
  else {  /* error; error message is on stack top */
    lua_pushnil(L);
    lua_insert(L, -2);
    lua_pushstring(L, (stat == ERRLIB) ?  LIB_FAIL : "init");
    return 3;  /* return nil, error message, and where */
  }
}
References ERRLIB, LIB_FAIL, ll_loadfunc(), lua_insert, lua_pushnil(), lua_pushstring(), and luaL_checkstring.
ll_require()
static int ll_require (lua_State * L) static
Definition at line 508 of file lua-5.2.4/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  lua_settop(L, 1);  /* _LOADED table will be at index 2 */
  lua_getfield(L, LUA_REGISTRYINDEX, "_LOADED");
  lua_getfield(L, 2, name);  /* _LOADED[name] */
  if (lua_toboolean(L, -1))  /* is it there? */
    return 1;  /* package is already loaded */
  /* else must load package */
  lua_pop(L, 1);  /* remove 'getfield' result */
  findloader(L, name);
  lua_pushstring(L, name);  /* pass name as argument to module loader */
  lua_insert(L, -2);  /* name is 1st argument (before search data) */
  lua_call(L, 2, 1);  /* run loader to load module */
  if (!lua_isnil(L, -1))  /* non-nil return? */
    lua_setfield(L, 2, name);  /* _LOADED[name] = returned value */
  lua_getfield(L, 2, name);
  if (lua_isnil(L, -1)) {   /* module did not set a value? */
    lua_pushboolean(L, 1);  /* use true as result */
    lua_pushvalue(L, -1);  /* extra copy to be returned */
    lua_setfield(L, 2, name);  /* _LOADED[name] = true */
  }
  return 1;
}
References findloader(), lua_call, lua_getfield(), lua_insert, lua_isnil, lua_pop, lua_pushboolean(), lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_settop(), lua_toboolean(), luaL_checkstring, and name.
ll_searchpath()
static int ll_searchpath (lua_State * L) static
Definition at line 372 of file lua-5.2.4/src/loadlib.c.
{
  const char *f = searchpath(L, luaL_checkstring(L, 1),
                                luaL_checkstring(L, 2),
                                luaL_optstring(L, 3, "."),
                                luaL_optstring(L, 4, LUA_DIRSEP));
  if (f != NULL) return 1;
  else {  /* error message is on top of the stack */
    lua_pushnil(L);
    lua_insert(L, -2);
    return 2;  /* return nil + error message */
  }
}
References LUA_DIRSEP, lua_insert, lua_pushnil(), luaL_checkstring, luaL_optstring, NULL, and searchpath().
ll_sym()
static lua_CFunction ll_sym (lua_State * L, void * lib, const char * sym) static
Definition at line 241 of file lua-5.2.4/src/loadlib.c.
{
  (void)(lib); (void)(sym);  /* not used */
  lua_pushliteral(L, DLMSG);
  return NULL;
}
References DLMSG, lua_pushliteral, and NULL.
Referenced by ll_loadfunc().
ll_unloadlib()
static void ll_unloadlib (void * lib) static
Definition at line 229 of file lua-5.2.4/src/loadlib.c.
{
  (void)(lib);  /* not used */
}
Referenced by gctm().
loadfunc()
static int loadfunc (lua_State * L, const char * filename, const char * modname) static
Definition at line 419 of file lua-5.2.4/src/loadlib.c.
{
  const char *funcname;
  const char *mark;
  modname = luaL_gsub(L, modname, ".", LUA_OFSEP);
  mark = strchr(modname, *LUA_IGMARK);
  if (mark) {
    int stat;
    funcname = lua_pushlstring(L, modname, mark - modname);
    funcname = lua_pushfstring(L, LUA_POF"%s", funcname);
    stat = ll_loadfunc(L, filename, funcname);
    if (stat != ERRFUNC) return stat;
    modname = mark + 1;  /* else go ahead and try old-style name */
  }
  funcname = lua_pushfstring(L, LUA_POF"%s", modname);
  return ll_loadfunc(L, filename, funcname);
}
References ERRFUNC, funcname(), ll_loadfunc(), LUA_IGMARK, LUA_OFSEP, LUA_POF, lua_pushfstring(), lua_pushlstring(), and luaL_gsub().
Referenced by searcher_C(), and searcher_Croot().
luaopen_package()
LUAMOD_API int luaopen_package (lua_State * L)
Definition at line 690 of file lua-5.2.4/src/loadlib.c.
{
  /* create table CLIBS to keep track of loaded C libraries */
  luaL_getsubtable(L, LUA_REGISTRYINDEX, CLIBS);
  lua_createtable(L, 0, 1);  /* metatable for CLIBS */
  lua_pushcfunction(L, gctm);
  lua_setfield(L, -2, "__gc");  /* set finalizer for CLIBS table */
  lua_setmetatable(L, -2);
  /* create `package' table */
  luaL_newlib(L, pk_funcs);
  createsearcherstable(L);
#if defined(LUA_COMPAT_LOADERS)
  lua_pushvalue(L, -1);  /* make a copy of 'searchers' table */
  lua_setfield(L, -3, "loaders");  /* put it in field `loaders' */
#endif
  lua_setfield(L, -2, "searchers");  /* put it in field 'searchers' */
  /* set field 'path' */
  setpath(L, "path", LUA_PATHVERSION, LUA_PATH, LUA_PATH_DEFAULT);
  /* set field 'cpath' */
  setpath(L, "cpath", LUA_CPATHVERSION, LUA_CPATH, LUA_CPATH_DEFAULT);
  /* store config information */
  lua_pushliteral(L, LUA_DIRSEP "\n" LUA_PATH_SEP "\n" LUA_PATH_MARK "\n"
                     LUA_EXEC_DIR "\n" LUA_IGMARK "\n");
  lua_setfield(L, -2, "config");
  /* set field `loaded' */
  luaL_getsubtable(L, LUA_REGISTRYINDEX, "_LOADED");
  lua_setfield(L, -2, "loaded");
  /* set field `preload' */
  luaL_getsubtable(L, LUA_REGISTRYINDEX, "_PRELOAD");
  lua_setfield(L, -2, "preload");
  lua_pushglobaltable(L);
  lua_pushvalue(L, -2);  /* set 'package' as upvalue for next lib */
  luaL_setfuncs(L, ll_funcs, 1);  /* open lib into global table */
  lua_pop(L, 1);  /* pop global table */
  return 1;  /* return 'package' table */
}
References CLIBS, createsearcherstable(), gctm(), ll_funcs, LUA_CPATH, LUA_CPATH_DEFAULT, LUA_CPATHVERSION, lua_createtable(), LUA_DIRSEP, LUA_EXEC_DIR, LUA_IGMARK, LUA_PATH, LUA_PATH_DEFAULT, LUA_PATH_MARK, LUA_PATH_SEP, LUA_PATHVERSION, lua_pop, lua_pushcfunction, lua_pushglobaltable, lua_pushliteral, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_setmetatable(), luaL_getsubtable(), luaL_newlib, luaL_setfuncs(), pk_funcs, and setpath().
noenv()
static int noenv (lua_State * L) static
Definition at line 628 of file lua-5.2.4/src/loadlib.c.
{
  int b;
  lua_getfield(L, LUA_REGISTRYINDEX, "LUA_NOENV");
  b = lua_toboolean(L, -1);
  lua_pop(L, 1);  /* remove value */
  return b;
}
References lua_getfield(), lua_pop, LUA_REGISTRYINDEX, and lua_toboolean().
Referenced by setpath().
pushnexttemplate()
static const char * pushnexttemplate (lua_State * L, const char * path) static
Definition at line 338 of file lua-5.2.4/src/loadlib.c.
{
  const char *l;
  while (*path == *LUA_PATH_SEP) path++;  /* skip separators */
  if (*path == '\0') return NULL;  /* no more templates */
  l = strchr(path, *LUA_PATH_SEP);  /* find next separator */
  if (l == NULL) l = path + strlen(path);
  lua_pushlstring(L, path, l - path);  /* template */
  return l;
}
References LUA_PATH_SEP, lua_pushlstring(), and NULL.
Referenced by searchpath().
readable()
static int readable (const char * filename) static
Definition at line 330 of file lua-5.2.4/src/loadlib.c.
{
  FILE *f = fopen(filename, "r");  /* try to open file */
  if (f == NULL) return 0;  /* open failed */
  fclose(f);
  return 1;
}
References NULL.
Referenced by searchpath().
searcher_C()
static int searcher_C (lua_State * L) static
Definition at line 437 of file lua-5.2.4/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  const char *filename = findfile(L, name, "cpath", LUA_CSUBSEP);
  if (filename == NULL) return 1;  /* module not found in this path */
  return checkload(L, (loadfunc(L, filename, name) == 0), filename);
}
References checkload(), findfile(), loadfunc(), LUA_CSUBSEP, luaL_checkstring, name, and NULL.
Referenced by createsearcherstable().
searcher_Croot()
static int searcher_Croot (lua_State * L) static
Definition at line 445 of file lua-5.2.4/src/loadlib.c.
{
  const char *filename;
  const char *name = luaL_checkstring(L, 1);
  const char *p = strchr(name, '.');
  int stat;
  if (p == NULL) return 0;  /* is root */
  lua_pushlstring(L, name, p - name);
  filename = findfile(L, lua_tostring(L, -1), "cpath", LUA_CSUBSEP);
  if (filename == NULL) return 1;  /* root not found */
  if ((stat = loadfunc(L, filename, name)) != 0) {
    if (stat != ERRFUNC)
      return checkload(L, 0, filename);  /* real error */
    else {  /* open function not found */
      lua_pushfstring(L, "\n\tno module " LUA_QS " in file " LUA_QS,
                         name, filename);
      return 1;
    }
  }
  lua_pushstring(L, filename);  /* will be 2nd argument to module */
  return 2;
}
References checkload(), ERRFUNC, findfile(), loadfunc(), LUA_CSUBSEP, lua_pushfstring(), lua_pushlstring(), lua_pushstring(), LUA_QS, lua_tostring, luaL_checkstring, name, and NULL.
Referenced by createsearcherstable().
searcher_Lua()
static int searcher_Lua (lua_State * L) static
Definition at line 410 of file lua-5.2.4/src/loadlib.c.
{
  const char *filename;
  const char *name = luaL_checkstring(L, 1);
  filename = findfile(L, name, "path", LUA_LSUBSEP);
  if (filename == NULL) return 1;  /* module not found in this path */
  return checkload(L, (luaL_loadfile(L, filename) == LUA_OK), filename);
}
References checkload(), findfile(), LUA_LSUBSEP, LUA_OK, luaL_checkstring, luaL_loadfile, name, and NULL.
Referenced by createsearcherstable().
searcher_preload()
static int searcher_preload (lua_State * L) static
Definition at line 468 of file lua-5.2.4/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  lua_getfield(L, LUA_REGISTRYINDEX, "_PRELOAD");
  lua_getfield(L, -1, name);
  if (lua_isnil(L, -1))  /* not found? */
    lua_pushfstring(L, "\n\tno field package.preload['%s']", name);
  return 1;
}
References lua_getfield(), lua_isnil, lua_pushfstring(), LUA_REGISTRYINDEX, luaL_checkstring, and name.
Referenced by createsearcherstable().
searchpath()
static const char * searchpath (lua_State * L, const char * name, const char * path, const char * sep, const char * dirsep) static
Definition at line 349 of file lua-5.2.4/src/loadlib.c.
{
  luaL_Buffer msg;  /* to build error message */
  luaL_buffinit(L, &msg);
  if (*sep != '\0')  /* non-empty separator? */
    name = luaL_gsub(L, name, sep, dirsep);  /* replace it by 'dirsep' */
  while ((path = pushnexttemplate(L, path)) != NULL) {
    const char *filename = luaL_gsub(L, lua_tostring(L, -1),
                                     LUA_PATH_MARK, name);
    lua_remove(L, -2);  /* remove path template */
    if (readable(filename))  /* does file exist and is readable? */
      return filename;  /* return that file name */
    lua_pushfstring(L, "\n\tno file " LUA_QS, filename);
    lua_remove(L, -2);  /* remove file name */
    luaL_addvalue(&msg);  /* concatenate error msg. entry */
  }
  luaL_pushresult(&msg);  /* create error message */
  return NULL;  /* not found */
}
References LUA_PATH_MARK, lua_pushfstring(), LUA_QS, lua_remove, lua_tostring, luaL_addvalue(), luaL_buffinit(), luaL_gsub(), luaL_pushresult(), name, NULL, pushnexttemplate(), and readable().
Referenced by findfile(), and ll_searchpath().
setpath()
static void setpath (lua_State * L, const char * fieldname, const char * envname1, const char * envname2, const char * def) static
Definition at line 637 of file lua-5.2.4/src/loadlib.c.
{
  const char *path = getenv(envname1);
  if (path == NULL)  /* no environment variable? */
    path = getenv(envname2);  /* try alternative name */
  if (path == NULL || noenv(L))  /* no environment variable? */
    lua_pushstring(L, def);  /* use default */
  else {
    /* replace ";;" by ";AUXMARK;" and then AUXMARK by default path */
    path = luaL_gsub(L, path, LUA_PATH_SEP LUA_PATH_SEP,
                              LUA_PATH_SEP AUXMARK LUA_PATH_SEP);
    luaL_gsub(L, path, AUXMARK, def);
    lua_remove(L, -2);
  }
  setprogdir(L);
  lua_setfield(L, -2, fieldname);
}
References AUXMARK, LUA_PATH_SEP, lua_pushstring(), lua_remove, lua_setfield(), luaL_gsub(), noenv(), NULL, and setprogdir.
Referenced by luaopen_package().
Variable Documentation
ll_funcs
const luaL_Reg ll_funcs[] static
Initial value:
= {
  {"require", ll_require},
  {NULL, NULL}
}
Definition at line 666 of file lua-5.2.4/src/loadlib.c.
{
#if defined(LUA_COMPAT_MODULE)
  {"module", ll_module},
#endif
  {"require", ll_require},
  {NULL, NULL}
};
Referenced by luaopen_package().
pk_funcs
const luaL_Reg pk_funcs[] static
Initial value:
= {
  {"loadlib", ll_loadlib},
  {"searchpath", ll_searchpath},
  {NULL, NULL}
}
Definition at line 656 of file lua-5.2.4/src/loadlib.c.
{
  {"loadlib", ll_loadlib},
  {"searchpath", ll_searchpath},
#if defined(LUA_COMPAT_MODULE)
  {"seeall", ll_seeall},
#endif
  {NULL, NULL}
};
Referenced by luaopen_package().