Github User Fetcher: linit.c File Reference
linit.c File Reference
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
Macros
#define linit_c
#define LUA_LIB
Functions
LUALIB_API void luaL_openlibs (lua_State *L)
Variables
static const luaL_Reg lualibs []
Macro Definition Documentation
linit_c
#define linit_c
Definition at line 8 of file lua-5.1.5/src/linit.c.
LUA_LIB
#define LUA_LIB
Definition at line 9 of file lua-5.1.5/src/linit.c.
Function Documentation
luaL_openlibs()
LUALIB_API void luaL_openlibs (lua_State * L)
Definition at line 30 of file lua-5.1.5/src/linit.c.
{
  const luaL_Reg *lib = lualibs;
  for (; lib->func; lib++) {
    lua_pushcfunction(L, lib->func);
    lua_pushstring(L, lib->name);
    lua_call(L, 1, 0);
  }
}
References luaL_Reg::func, lua_call, lua_pushcfunction, lua_pushstring(), lualibs, and luaL_Reg::name.
Referenced by pmain(), pmain(), pmain(), and pmain().
Variable Documentation
lualibs
const luaL_Reg lualibs[] static
Initial value:
= {
  {"", luaopen_base},
  {LUA_LOADLIBNAME, luaopen_package},
  {LUA_TABLIBNAME, luaopen_table},
  {LUA_IOLIBNAME, luaopen_io},
  {LUA_OSLIBNAME, luaopen_os},
  {LUA_STRLIBNAME, luaopen_string},
  {LUA_MATHLIBNAME, luaopen_math},
  {LUA_DBLIBNAME, luaopen_debug},
  {NULL, NULL}
}
Definition at line 17 of file lua-5.1.5/src/linit.c.
{
  {"", luaopen_base},
  {LUA_LOADLIBNAME, luaopen_package},
  {LUA_TABLIBNAME, luaopen_table},
  {LUA_IOLIBNAME, luaopen_io},
  {LUA_OSLIBNAME, luaopen_os},
  {LUA_STRLIBNAME, luaopen_string},
  {LUA_MATHLIBNAME, luaopen_math},
  {LUA_DBLIBNAME, luaopen_debug},
  {NULL, NULL}
};
Referenced by luaL_openlibs().