Github User Fetcher: ldo.c File Reference
ldo.c File Reference
#include "lprefix.h"
#include <setjmp.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lundump.h"
#include "lvm.h"
#include "lzio.h"
Data Structures
struct lua_longjmp
struct SParser
Macros
#define ldo_c
#define LUA_CORE
#define errorstatus(s) ((s) > LUA_YIELD)
#define LUAI_THROW(L, c) longjmp((c)->b, 1)
#define LUAI_TRY(L, c, a) if (setjmp((c)->b) == 0) { a }
#define luai_jmpbuf jmp_buf
#define ERRORSTACKSIZE (LUAI_MAXSTACK + 200)
#define next_ci(L) (L->ci = (L->ci->next ? L->ci->next : luaE_extendCI(L)))
#define checkstackp(L, n, p)
Functions
static void seterrorobj (lua_State *L, int errcode, StkId oldtop)
l_noret luaD_throw (lua_State *L, int errcode)
int luaD_rawrunprotected (lua_State *L, Pfunc f, void *ud)
static void correctstack (lua_State *L, TValue *oldstack)
void luaD_reallocstack (lua_State *L, int newsize)
void luaD_growstack (lua_State *L, int n)
static int stackinuse (lua_State *L)
void luaD_shrinkstack (lua_State *L)
void luaD_inctop (lua_State *L)
void luaD_hook (lua_State *L, int event, int line)
static void callhook (lua_State *L, CallInfo *ci)
static StkId adjust_varargs (lua_State *L, Proto *p, int actual)
static void tryfuncTM (lua_State *L, StkId func)
static int moveresults (lua_State *L, const TValue *firstResult, StkId res, int nres, int wanted)
int luaD_poscall (lua_State *L, CallInfo *ci, StkId firstResult, int nres)
int luaD_precall (lua_State *L, StkId func, int nresults)
static void stackerror (lua_State *L)
void luaD_call (lua_State *L, StkId func, int nResults)
void luaD_callnoyield (lua_State *L, StkId func, int nResults)
static void finishCcall (lua_State *L, int status)
static void unroll (lua_State *L, void *ud)
static CallInfo * findpcall (lua_State *L)
static int recover (lua_State *L, int status)
static int resume_error (lua_State *L, const char *msg, int narg)
static void resume (lua_State *L, void *ud)
LUA_API int lua_resume (lua_State *L, lua_State *from, int nargs)
LUA_API int lua_isyieldable (lua_State *L)
LUA_API int lua_yieldk (lua_State *L, int nresults, lua_KContext ctx, lua_KFunction k)
int luaD_pcall (lua_State *L, Pfunc func, void *u, ptrdiff_t old_top, ptrdiff_t ef)
static void checkmode (lua_State *L, const char *mode, const char *x)
static void f_parser (lua_State *L, void *ud)
int luaD_protectedparser (lua_State *L, ZIO *z, const char *name, const char *mode)
Macro Definition Documentation
checkstackp
#define checkstackp (L, n, p)
Value:
  luaD_checkstackaux(L, n, \
    ptrdiff_t t__ = savestack(L, p);  /* save 'p' */ \
    luaC_checkGC(L),  /* stack grow uses memory */ \
    p = restorestack(L, t__))  /* 'pos' part: restore 'p' */
Definition at line 399 of file lua-5.3.6/src/ldo.c.
#define checkstackp(L,n,p)  \
  luaD_checkstackaux(L, n, \
    ptrdiff_t t__ = savestack(L, p);  /* save 'p' */ \
    luaC_checkGC(L),  /* stack grow uses memory */ \
    p = restorestack(L, t__))  /* 'pos' part: restore 'p' */
Referenced by luaD_precall().
ERRORSTACKSIZE
#define ERRORSTACKSIZE (LUAI_MAXSTACK + 200)
Definition at line 174 of file lua-5.3.6/src/ldo.c.
Referenced by luaD_growstack(), and luaD_reallocstack().
errorstatus
#define errorstatus (s) ((s) > LUA_YIELD)
Definition at line 38 of file lua-5.3.6/src/ldo.c.
Referenced by lua_resume().
ldo_c
#define ldo_c
Definition at line 7 of file lua-5.3.6/src/ldo.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/ldo.c.
luai_jmpbuf
#define luai_jmpbuf jmp_buf
Definition at line 75 of file lua-5.3.6/src/ldo.c.
LUAI_THROW
#define LUAI_THROW (L, c) longjmp((c)->b, 1)
Definition at line 73 of file lua-5.3.6/src/ldo.c.
Referenced by luaD_throw().
LUAI_TRY
#define LUAI_TRY (L, c, a) if (setjmp((c)->b) == 0) { a }
Definition at line 74 of file lua-5.3.6/src/ldo.c.
Referenced by luaD_rawrunprotected().
next_ci
#define next_ci (L) (L->ci = (L->ci->next ? L->ci->next : luaE_extendCI(L)))
Definition at line 395 of file lua-5.3.6/src/ldo.c.
Referenced by luaD_precall().
Function Documentation
adjust_varargs()
static StkId adjust_varargs (lua_State * L, Proto * p, int actual) static
Definition at line 293 of file lua-5.3.6/src/ldo.c.
{
  int i;
  int nfixargs = p->numparams;
  StkId base, fixed;
  /* move fixed parameters to final position */
  fixed = L->top - actual;  /* first fixed argument */
  base = L->top;  /* final position of first argument */
  for (i = 0; i < nfixargs && i < actual; i++) {
    setobjs2s(L, L->top++, fixed + i);
    setnilvalue(fixed + i);  /* erase original copy (for GC) */
  }
  for (; i < nfixargs; i++)
    setnilvalue(L->top++);  /* complete missing arguments */
  return base;
}
References Proto::numparams, setnilvalue, setobjs2s, and lua_State::top.
Referenced by luaD_precall().
callhook()
static void callhook (lua_State * L, CallInfo * ci) static
Definition at line 280 of file lua-5.3.6/src/ldo.c.
{
  int hook = LUA_HOOKCALL;
  ci->u.l.savedpc++;  /* hooks assume 'pc' is already incremented */
  if (isLua(ci->previous) &&
      GET_OPCODE(*(ci->previous->u.l.savedpc - 1)) == OP_TAILCALL) {
    ci->callstatus |= CIST_TAIL;
    hook = LUA_HOOKTAILCALL;
  }
  luaD_hook(L, hook, -1);
  ci->u.l.savedpc--;  /* correct 'pc' */
}
References CallInfo::callstatus, CIST_TAIL, GET_OPCODE, isLua, CallInfo::l, LUA_HOOKCALL, LUA_HOOKTAILCALL, luaD_hook(), OP_TAILCALL, CallInfo::previous, CallInfo::savedpc, and CallInfo::u.
Referenced by luaD_precall().
checkmode()
static void checkmode (lua_State * L, const char * mode, const char * x) static
Definition at line 757 of file lua-5.3.6/src/ldo.c.
{
  if (mode && strchr(mode, x[0]) == NULL) {
    luaO_pushfstring(L,
       "attempt to load a %s chunk (mode is '%s')", x, mode);
    luaD_throw(L, LUA_ERRSYNTAX);
  }
}
References LUA_ERRSYNTAX, luaD_throw(), luaO_pushfstring(), and NULL.
Referenced by f_parser().
correctstack()
static void correctstack (lua_State * L, TValue * oldstack) static
Definition at line 158 of file lua-5.3.6/src/ldo.c.
{
  CallInfo *ci;
  UpVal *up;
  L->top = (L->top - oldstack) + L->stack;
  for (up = L->openupval; up != NULL; up = up->u.open.next)
    up->v = (up->v - oldstack) + L->stack;
  for (ci = L->ci; ci != NULL; ci = ci->previous) {
    ci->top = (ci->top - oldstack) + L->stack;
    ci->func = (ci->func - oldstack) + L->stack;
    if (isLua(ci))
      ci->u.l.base = (ci->u.l.base - oldstack) + L->stack;
  }
}
References CallInfo::base, lua_State::ci, CallInfo::func, isLua, CallInfo::l, UpVal::next, NULL, UpVal::open, lua_State::openupval, CallInfo::previous, lua_State::stack, CallInfo::top, lua_State::top, UpVal::u, CallInfo::u, and UpVal::v.
Referenced by luaD_reallocstack().
f_parser()
static void f_parser (lua_State * L, void * ud) static
Definition at line 766 of file lua-5.3.6/src/ldo.c.
{
  LClosure *cl;
  struct SParser *p = cast(struct SParser *, ud);
  int c = zgetc(p->z);  /* read first character */
  if (c == LUA_SIGNATURE[0]) {
    checkmode(L, p->mode, "binary");
    cl = luaU_undump(L, p->z, p->name);
  }
  else {
    checkmode(L, p->mode, "text");
    cl = luaY_parser(L, p->z, &p->buff, &p->dyd, p->name, c);
  }
  lua_assert(cl->nupvalues == cl->p->sizeupvalues);
  luaF_initupvals(L, cl);
}
References SParser::buff, cast, checkmode(), SParser::dyd, lua_assert, LUA_SIGNATURE, luaF_initupvals(), luaU_undump(), luaY_parser(), SParser::mode, SParser::name, LClosure::p, Proto::sizeupvalues, SParser::z, and zgetc.
Referenced by luaD_protectedparser().
findpcall()
static CallInfo * findpcall (lua_State * L) static
Definition at line 566 of file lua-5.3.6/src/ldo.c.
{
  CallInfo *ci;
  for (ci = L->ci; ci != NULL; ci = ci->previous) {  /* search for a pcall */
    if (ci->callstatus & CIST_YPCALL)
      return ci;
  }
  return NULL;  /* no pending pcall */
}
References CallInfo::callstatus, lua_State::ci, CIST_YPCALL, NULL, and CallInfo::previous.
Referenced by recover().
finishCcall()
static void finishCcall (lua_State * L, int status) static
Definition at line 518 of file lua-5.3.6/src/ldo.c.
{
  CallInfo *ci = L->ci;
  int n;
  /* must have a continuation and must be able to call it */
  lua_assert(ci->u.c.k != NULL && L->nny == 0);
  /* error status can only happen in a protected call */
  lua_assert((ci->callstatus & CIST_YPCALL) || status == LUA_YIELD);
  if (ci->callstatus & CIST_YPCALL) {  /* was inside a pcall? */
    ci->callstatus &= ~CIST_YPCALL;  /* continuation is also inside it */
    L->errfunc = ci->u.c.old_errfunc;  /* with the same error function */
  }
  /* finish 'lua_callk'/'lua_pcall'; CIST_YPCALL and 'errfunc' already
     handled */
  adjustresults(L, ci->nresults);
  lua_unlock(L);
  n = (*ci->u.c.k)(L, status, ci->u.c.ctx);  /* call continuation function */
  lua_lock(L);
  api_checknelems(L, n);
  luaD_poscall(L, ci, L->top - n, n);  /* finish 'luaD_precall' */
}
References adjustresults, api_checknelems, CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_YPCALL, CallInfo::ctx, lua_State::errfunc, CallInfo::k, lua_assert, lua_lock, lua_unlock, LUA_YIELD, luaD_poscall(), lua_State::nny, CallInfo::nresults, NULL, CallInfo::old_errfunc, lua_longjmp::status, lua_State::top, and CallInfo::u.
Referenced by unroll().
lua_isyieldable()
LUA_API int lua_isyieldable (lua_State * L)
Definition at line 687 of file lua-5.3.6/src/ldo.c.
{
  return (L->nny == 0);
}
References lua_State::nny.
Referenced by luaB_yieldable(), and luaB_yieldable().
lua_resume()
LUA_API int lua_resume (lua_State * L, lua_State * from, int nargs)
Definition at line 648 of file lua-5.3.6/src/ldo.c.
{
  int status;
  unsigned short oldnny = L->nny;  /* save "number of non-yieldable" calls */
  lua_lock(L);
  if (L->status == LUA_OK) {  /* may be starting a coroutine */
    if (L->ci != &L->base_ci)  /* not in base level? */
      return resume_error(L, "cannot resume non-suspended coroutine", nargs);
  }
  else if (L->status != LUA_YIELD)
    return resume_error(L, "cannot resume dead coroutine", nargs);
  L->nCcalls = (from) ? from->nCcalls + 1 : 1;
  if (L->nCcalls >= LUAI_MAXCCALLS)
    return resume_error(L, "C stack overflow", nargs);
  luai_userstateresume(L, nargs);
  L->nny = 0;  /* allow yields */
  api_checknelems(L, (L->status == LUA_OK) ? nargs + 1 : nargs);
  status = luaD_rawrunprotected(L, resume, &nargs);
  if (status == -1)  /* error calling 'lua_resume'? */
    status = LUA_ERRRUN;
  else {  /* continue running after recoverable errors */
    while (errorstatus(status) && recover(L, status)) {
      /* unroll continuation */
      status = luaD_rawrunprotected(L, unroll, &status);
    }
    if (errorstatus(status)) {  /* unrecoverable error? */
      L->status = cast_byte(status);  /* mark thread as 'dead' */
      seterrorobj(L, status, L->top);  /* push error message */
      L->ci->top = L->top;
    }
    else lua_assert(status == L->status);  /* normal end or yield */
  }
  L->nny = oldnny;  /* restore 'nny' */
  L->nCcalls--;
  lua_assert(L->nCcalls == ((from) ? from->nCcalls : 0));
  lua_unlock(L);
  return status;
}
References api_checknelems, lua_State::base_ci, cast_byte, lua_State::ci, errorstatus, lua_assert, LUA_ERRRUN, lua_lock, LUA_OK, lua_unlock, LUA_YIELD, luaD_rawrunprotected(), LUAI_MAXCCALLS, luai_userstateresume, lua_State::nCcalls, lua_State::nny, recover(), resume(), resume_error(), seterrorobj(), lua_longjmp::status, lua_State::status, CallInfo::top, lua_State::top, and unroll().
lua_yieldk()
LUA_API int lua_yieldk (lua_State * L, int nresults, lua_KContext ctx, lua_KFunction k)
Definition at line 692 of file lua-5.3.6/src/ldo.c.
{
  CallInfo *ci = L->ci;
  luai_userstateyield(L, nresults);
  lua_lock(L);
  api_checknelems(L, nresults);
  if (L->nny > 0) {
    if (L != G(L)->mainthread)
      luaG_runerror(L, "attempt to yield across a C-call boundary");
    else
      luaG_runerror(L, "attempt to yield from outside a coroutine");
  }
  L->status = LUA_YIELD;
  ci->extra = savestack(L, ci->func);  /* save current 'func' */
  if (isLua(ci)) {  /* inside a hook? */
    api_check(L, k == NULL, "hooks cannot continue after yielding");
  }
  else {
    if ((ci->u.c.k = k) != NULL)  /* is there a continuation? */
      ci->u.c.ctx = ctx;  /* save context */
    ci->func = L->top - nresults - 1;  /* protect stack below results */
    luaD_throw(L, LUA_YIELD);
  }
  lua_assert(ci->callstatus & CIST_HOOKED);  /* must be inside a hook */
  lua_unlock(L);
  return 0;  /* return to 'luaD_hook' */
}
References api_check, api_checknelems, CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, CallInfo::ctx, CallInfo::extra, CallInfo::func, G, isLua, CallInfo::k, lua_assert, lua_lock, lua_unlock, LUA_YIELD, luaD_throw(), luaG_runerror(), luai_userstateyield, lua_State::nny, NULL, savestack, lua_State::status, lua_State::top, and CallInfo::u.
luaD_call()
void luaD_call (lua_State * L, StkId func, int nResults)
Definition at line 495 of file lua-5.3.6/src/ldo.c.
{
  if (++L->nCcalls >= LUAI_MAXCCALLS)
    stackerror(L);
  if (!luaD_precall(L, func, nResults))  /* is a Lua function? */
    luaV_execute(L);  /* call it */
  L->nCcalls--;
}
References luaD_precall(), LUAI_MAXCCALLS, luaV_execute(), lua_State::nCcalls, and stackerror().
Referenced by luaD_callnoyield().
luaD_callnoyield()
void luaD_callnoyield (lua_State * L, StkId func, int nResults)
Definition at line 507 of file lua-5.3.6/src/ldo.c.
{
  L->nny++;
  luaD_call(L, func, nResults);
  L->nny--;
}
References luaD_call(), and lua_State::nny.
Referenced by callclosemethod(), dothecall(), dothecall(), f_call(), f_call(), lua_callk(), luaG_errormsg(), luaT_callTM(), luaT_callTM(), and luaT_callTMres().
luaD_growstack()
void luaD_growstack (lua_State * L, int n)
Definition at line 191 of file lua-5.3.6/src/ldo.c.
{
  int size = L->stacksize;
  if (size > LUAI_MAXSTACK)  /* error after extra size? */
    luaD_throw(L, LUA_ERRERR);
  else {
    int needed = cast_int(L->top - L->stack) + n + EXTRA_STACK;
    int newsize = 2 * size;
    if (newsize > LUAI_MAXSTACK) newsize = LUAI_MAXSTACK;
    if (newsize < needed) newsize = needed;
    if (newsize > LUAI_MAXSTACK) {  /* stack overflow? */
      luaD_reallocstack(L, ERRORSTACKSIZE);
      luaG_runerror(L, "stack overflow");
    }
    else
      luaD_reallocstack(L, newsize);
  }
}
References cast_int, ERRORSTACKSIZE, EXTRA_STACK, LUA_ERRERR, luaD_reallocstack(), luaD_throw(), luaG_runerror(), LUAI_MAXSTACK, lua_State::stack, lua_State::stacksize, and lua_State::top.
luaD_hook()
void luaD_hook (lua_State * L, int event, int line)
Definition at line 253 of file lua-5.3.6/src/ldo.c.
{
  lua_Hook hook = L->hook;
  if (hook && L->allowhook) {  /* make sure there is a hook */
    CallInfo *ci = L->ci;
    ptrdiff_t top = savestack(L, L->top);
    ptrdiff_t ci_top = savestack(L, ci->top);
    lua_Debug ar;
    ar.event = event;
    ar.currentline = line;
    ar.i_ci = ci;
    luaD_checkstack(L, LUA_MINSTACK);  /* ensure minimum stack size */
    ci->top = L->top + LUA_MINSTACK;
    lua_assert(ci->top <= L->stack_last);
    L->allowhook = 0;  /* cannot call hooks inside a hook */
    ci->callstatus |= CIST_HOOKED;
    lua_unlock(L);
    (*hook)(L, &ar);
    lua_lock(L);
    lua_assert(!L->allowhook);
    L->allowhook = 1;
    ci->top = restorestack(L, ci_top);
    L->top = restorestack(L, top);
    ci->callstatus &= ~CIST_HOOKED;
  }
}
References lua_State::allowhook, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, lua_Debug::currentline, lua_Debug::event, lua_State::hook, lua_Debug::i_ci, lua_assert, lua_lock, LUA_MINSTACK, lua_unlock, luaD_checkstack, restorestack, savestack, lua_State::stack_last, CallInfo::top, and lua_State::top.
Referenced by callhook(), luaD_poscall(), and luaD_precall().
luaD_inctop()
void luaD_inctop (lua_State * L)
Definition at line 240 of file lua-5.3.6/src/ldo.c.
{
  luaD_checkstack(L, 1);
  L->top++;
}
References luaD_checkstack, and lua_State::top.
Referenced by LoadString(), loadStringN(), luaO_pushvfstring(), luaU_undump(), luaY_parser(), and pushstr().
luaD_pcall()
int luaD_pcall (lua_State * L, Pfunc func, void * u, ptrdiff_t old_top, ptrdiff_t ef)
Definition at line 721 of file lua-5.3.6/src/ldo.c.
{
  int status;
  CallInfo *old_ci = L->ci;
  lu_byte old_allowhooks = L->allowhook;
  unsigned short old_nny = L->nny;
  ptrdiff_t old_errfunc = L->errfunc;
  L->errfunc = ef;
  status = luaD_rawrunprotected(L, func, u);
  if (status != LUA_OK) {  /* an error occurred? */
    StkId oldtop = restorestack(L, old_top);
    luaF_close(L, oldtop);  /* close possible pending closures */
    seterrorobj(L, status, oldtop);
    L->ci = old_ci;
    L->allowhook = old_allowhooks;
    L->nny = old_nny;
    luaD_shrinkstack(L);
  }
  L->errfunc = old_errfunc;
  return status;
}
References lua_State::allowhook, lua_State::ci, lua_State::errfunc, LUA_OK, luaD_rawrunprotected(), luaD_shrinkstack(), luaF_close(), lua_State::nny, restorestack, seterrorobj(), and lua_longjmp::status.
Referenced by luaD_protectedparser().
luaD_poscall()
int luaD_poscall (lua_State * L, CallInfo * ci, StkId firstResult, int nres)
Definition at line 376 of file lua-5.3.6/src/ldo.c.
{
  StkId res;
  int wanted = ci->nresults;
  if (L->hookmask & (LUA_MASKRET | LUA_MASKLINE)) {
    if (L->hookmask & LUA_MASKRET) {
      ptrdiff_t fr = savestack(L, firstResult);  /* hook may change stack */
      luaD_hook(L, LUA_HOOKRET, -1);
      firstResult = restorestack(L, fr);
    }
    L->oldpc = ci->previous->u.l.savedpc;  /* 'oldpc' for caller function */
  }
  res = ci->func;  /* res == final position of 1st result */
  L->ci = ci->previous;  /* back to caller */
  /* move results to proper place */
  return moveresults(L, firstResult, res, nres, wanted);
}
References lua_State::ci, CallInfo::func, lua_State::hookmask, CallInfo::l, LUA_HOOKRET, LUA_MASKLINE, LUA_MASKRET, luaD_hook(), moveresults(), CallInfo::nresults, lua_State::oldpc, CallInfo::previous, restorestack, CallInfo::savedpc, savestack, and CallInfo::u.
Referenced by finishCcall(), luaD_precall(), and resume().
luaD_precall()
int luaD_precall (lua_State * L, StkId func, int nresults)
Definition at line 413 of file lua-5.3.6/src/ldo.c.
{
  lua_CFunction f;
  CallInfo *ci;
  switch (ttype(func)) {
    case LUA_TCCL:  /* C closure */
      f = clCvalue(func)->f;
      goto Cfunc;
    case LUA_TLCF:  /* light C function */
      f = fvalue(func);
     Cfunc: {
      int n;  /* number of returns */
      checkstackp(L, LUA_MINSTACK, func);  /* ensure minimum stack size */
      ci = next_ci(L);  /* now 'enter' new function */
      ci->nresults = nresults;
      ci->func = func;
      ci->top = L->top + LUA_MINSTACK;
      lua_assert(ci->top <= L->stack_last);
      ci->callstatus = 0;
      if (L->hookmask & LUA_MASKCALL)
        luaD_hook(L, LUA_HOOKCALL, -1);
      lua_unlock(L);
      n = (*f)(L);  /* do the actual call */
      lua_lock(L);
      api_checknelems(L, n);
      luaD_poscall(L, ci, L->top - n, n);
      return 1;
    }
    case LUA_TLCL: {  /* Lua function: prepare its call */
      StkId base;
      Proto *p = clLvalue(func)->p;
      int n = cast_int(L->top - func) - 1;  /* number of real arguments */
      int fsize = p->maxstacksize;  /* frame size */
      checkstackp(L, fsize, func);
      if (p->is_vararg)
        base = adjust_varargs(L, p, n);
      else {  /* non vararg function */
        for (; n < p->numparams; n++)
          setnilvalue(L->top++);  /* complete missing arguments */
        base = func + 1;
      }
      ci = next_ci(L);  /* now 'enter' new function */
      ci->nresults = nresults;
      ci->func = func;
      ci->u.l.base = base;
      L->top = ci->top = base + fsize;
      lua_assert(ci->top <= L->stack_last);
      ci->u.l.savedpc = p->code;  /* starting point */
      ci->callstatus = CIST_LUA;
      if (L->hookmask & LUA_MASKCALL)
        callhook(L, ci);
      return 0;
    }
    default: {  /* not a function */
      checkstackp(L, 1, func);  /* ensure space for metamethod */
      tryfuncTM(L, func);  /* try to get '__call' metamethod */
      return luaD_precall(L, func, nresults);  /* now it must be a function */
    }
  }
}
References adjust_varargs(), api_checknelems, CallInfo::base, callhook(), CallInfo::callstatus, cast_int, checkstackp, CIST_LUA, clCvalue, clLvalue, Proto::code, CallInfo::func, fvalue, lua_State::hookmask, Proto::is_vararg, CallInfo::l, lua_assert, LUA_HOOKCALL, lua_lock, LUA_MASKCALL, LUA_MINSTACK, LUA_TCCL, LUA_TLCF, LUA_TLCL, lua_unlock, luaD_hook(), luaD_poscall(), luaD_precall(), Proto::maxstacksize, next_ci, CallInfo::nresults, Proto::numparams, Proto::p, CallInfo::savedpc, setnilvalue, lua_State::stack_last, CallInfo::top, lua_State::top, tryfuncTM(), ttype, and CallInfo::u.
Referenced by luaD_call(), luaD_precall(), and resume().
luaD_protectedparser()
int luaD_protectedparser (lua_State * L, ZIO * z, const char * name, const char * mode)
Definition at line 783 of file lua-5.3.6/src/ldo.c.
{
  struct SParser p;
  int status;
  L->nny++;  /* cannot yield during parsing */
  p.z = z; p.name = name; p.mode = mode;
  p.dyd.actvar.arr = NULL; p.dyd.actvar.size = 0;
  p.dyd.gt.arr = NULL; p.dyd.gt.size = 0;
  p.dyd.label.arr = NULL; p.dyd.label.size = 0;
  luaZ_initbuffer(L, &p.buff);
  status = luaD_pcall(L, f_parser, &p, savestack(L, L->top), L->errfunc);
  luaZ_freebuffer(L, &p.buff);
  luaM_freearray(L, p.dyd.actvar.arr, p.dyd.actvar.size);
  luaM_freearray(L, p.dyd.gt.arr, p.dyd.gt.size);
  luaM_freearray(L, p.dyd.label.arr, p.dyd.label.size);
  L->nny--;
  return status;
}
References Dyndata::actvar, Labellist::arr, Dyndata::arr, SParser::buff, SParser::dyd, lua_State::errfunc, f_parser(), Dyndata::gt, Dyndata::label, luaD_pcall(), luaM_freearray, luaZ_freebuffer, luaZ_initbuffer, SParser::mode, name, SParser::name, lua_State::nny, NULL, savestack, Labellist::size, Dyndata::size, lua_State::top, and SParser::z.
luaD_rawrunprotected()
int luaD_rawrunprotected (lua_State * L, Pfunc f, void * ud)
Definition at line 136 of file lua-5.3.6/src/ldo.c.
{
  unsigned short oldnCcalls = L->nCcalls;
  struct lua_longjmp lj;
  lj.status = LUA_OK;
  lj.previous = L->errorJmp;  /* chain new error handler */
  L->errorJmp = &lj;
  LUAI_TRY(L, &lj,
    (*f)(L, ud);
  );
  L->errorJmp = lj.previous;  /* restore old error handler */
  L->nCcalls = oldnCcalls;
  return lj.status;
}
References lua_State::errorJmp, LUA_OK, LUAI_TRY, lua_State::nCcalls, lua_longjmp::previous, and lua_longjmp::status.
Referenced by lua_resume(), and luaD_pcall().
luaD_reallocstack()
void luaD_reallocstack (lua_State * L, int newsize)
Definition at line 177 of file lua-5.3.6/src/ldo.c.
{
  TValue *oldstack = L->stack;
  int lim = L->stacksize;
  lua_assert(newsize <= LUAI_MAXSTACK || newsize == ERRORSTACKSIZE);
  lua_assert(L->stack_last - L->stack == L->stacksize - EXTRA_STACK);
  luaM_reallocvector(L, L->stack, L->stacksize, newsize, TValue);
  for (; lim < newsize; lim++)
    setnilvalue(L->stack + lim); /* erase new segment */
  L->stacksize = newsize;
  L->stack_last = L->stack + newsize - EXTRA_STACK;
  correctstack(L, oldstack);
}
References correctstack(), ERRORSTACKSIZE, EXTRA_STACK, lua_assert, LUAI_MAXSTACK, luaM_reallocvector, setnilvalue, lua_State::stack, lua_State::stack_last, and lua_State::stacksize.
Referenced by luaD_growstack(), and luaD_shrinkstack().
luaD_shrinkstack()
void luaD_shrinkstack (lua_State * L)
Definition at line 221 of file lua-5.3.6/src/ldo.c.
{
  int inuse = stackinuse(L);
  int goodsize = inuse + (inuse / 8) + 2*EXTRA_STACK;
  if (goodsize > LUAI_MAXSTACK)
    goodsize = LUAI_MAXSTACK;  /* respect stack limit */
  if (L->stacksize > LUAI_MAXSTACK)  /* had been handling stack overflow? */
    luaE_freeCI(L);  /* free all CIs (list grew because of an error) */
  else
    luaE_shrinkCI(L);  /* shrink list */
  /* if thread is currently not handling a stack overflow and its
     good size is smaller than current size, shrink its stack */
  if (inuse <= (LUAI_MAXSTACK - EXTRA_STACK) &&
      goodsize < L->stacksize)
    luaD_reallocstack(L, goodsize);
  else  /* don't change stack */
    condmovestack(L,{},{});  /* (change only for debugging) */
}
References condmovestack, EXTRA_STACK, luaD_reallocstack(), luaE_freeCI(), luaE_shrinkCI(), LUAI_MAXSTACK, stackinuse(), lua_State::stacksize, and stacksize.
Referenced by luaD_pcall(), and recover().
luaD_throw()
l_noret luaD_throw (lua_State * L, int errcode)
Definition at line 110 of file lua-5.3.6/src/ldo.c.
{
  if (L->errorJmp) {  /* thread has an error handler? */
    L->errorJmp->status = errcode;  /* set status */
    LUAI_THROW(L, L->errorJmp);  /* jump to it */
  }
  else {  /* thread has no error handler */
    global_State *g = G(L);
    L->status = cast_byte(errcode);  /* mark it as dead */
    if (g->mainthread->errorJmp) {  /* main thread has a handler? */
      setobjs2s(L, g->mainthread->top++, L->top - 1);  /* copy error obj. */
      luaD_throw(g->mainthread, errcode);  /* re-throw in main thread */
    }
    else {  /* no handler at all; abort */
      if (g->panic) {  /* panic function? */
        seterrorobj(L, errcode, L->top);  /* assume EXTRA_STACK */
        if (L->ci->top < L->top)
          L->ci->top = L->top;  /* pushing msg. can break this invariant */
        lua_unlock(L);
        g->panic(L);  /* call panic function (last chance to jump out) */
      }
      abort();
    }
  }
}
References cast_byte, lua_State::ci, lua_State::errorJmp, G, lua_unlock, luaD_throw(), LUAI_THROW, global_State::mainthread, global_State::panic, seterrorobj(), setobjs2s, lua_longjmp::status, lua_State::status, CallInfo::top, and lua_State::top.
Referenced by checkmode(), lua_yieldk(), luaD_growstack(), luaD_throw(), and stackerror().
moveresults()
static int moveresults (lua_State * L, const TValue * firstResult, StkId res, int nres, int wanted) static
Definition at line 334 of file lua-5.3.6/src/ldo.c.
{
  switch (wanted) {  /* handle typical cases separately */
    case 0: break;  /* nothing to move */
    case 1: {  /* one result needed */
      if (nres == 0)   /* no results? */
        firstResult = luaO_nilobject;  /* adjust with nil */
      setobjs2s(L, res, firstResult);  /* move it to proper place */
      break;
    }
    case LUA_MULTRET: {
      int i;
      for (i = 0; i < nres; i++)  /* move all results to correct place */
        setobjs2s(L, res + i, firstResult + i);
      L->top = res + nres;
      return 0;  /* wanted == LUA_MULTRET */
    }
    default: {
      int i;
      if (wanted <= nres) {  /* enough results? */
        for (i = 0; i < wanted; i++)  /* move wanted results to correct place */
          setobjs2s(L, res + i, firstResult + i);
      }
      else {  /* not enough results; use all of them plus nils */
        for (i = 0; i < nres; i++)  /* move all results to correct place */
          setobjs2s(L, res + i, firstResult + i);
        for (; i < wanted; i++)  /* complete wanted number of results */
          setnilvalue(res + i);
      }
      break;
    }
  }
  L->top = res + wanted;  /* top points after the last result */
  return 1;
}
References LUA_MULTRET, luaO_nilobject, setnilvalue, setobjs2s, and lua_State::top.
Referenced by luaD_poscall().
recover()
static int recover (lua_State * L, int status) static
Definition at line 581 of file lua-5.3.6/src/ldo.c.
{
  StkId oldtop;
  CallInfo *ci = findpcall(L);
  if (ci == NULL) return 0;  /* no recovery point */
  /* "finish" luaD_pcall */
  oldtop = restorestack(L, ci->extra);
  luaF_close(L, oldtop);
  seterrorobj(L, status, oldtop);
  L->ci = ci;
  L->allowhook = getoah(ci->callstatus);  /* restore original 'allowhook' */
  L->nny = 0;  /* should be zero to be yieldable */
  luaD_shrinkstack(L);
  L->errfunc = ci->u.c.old_errfunc;
  return 1;  /* continue running the coroutine */
}
References lua_State::allowhook, CallInfo::c, CallInfo::callstatus, lua_State::ci, lua_State::errfunc, CallInfo::extra, findpcall(), getoah, luaD_shrinkstack(), luaF_close(), lua_State::nny, NULL, CallInfo::old_errfunc, restorestack, seterrorobj(), lua_longjmp::status, and CallInfo::u.
Referenced by lua_resume().
resume()
static void resume (lua_State * L, void * ud) static
Definition at line 619 of file lua-5.3.6/src/ldo.c.
{
  int n = *(cast(int*, ud));  /* number of arguments */
  StkId firstArg = L->top - n;  /* first argument */
  CallInfo *ci = L->ci;
  if (L->status == LUA_OK) {  /* starting a coroutine? */
    if (!luaD_precall(L, firstArg - 1, LUA_MULTRET))  /* Lua function? */
      luaV_execute(L);  /* call it */
  }
  else {  /* resuming from previous yield */
    lua_assert(L->status == LUA_YIELD);
    L->status = LUA_OK;  /* mark that it is running (again) */
    ci->func = restorestack(L, ci->extra);
    if (isLua(ci))  /* yielded inside a hook? */
      luaV_execute(L);  /* just continue running Lua code */
    else {  /* 'common' yield */
      if (ci->u.c.k != NULL) {  /* does it have a continuation function? */
        lua_unlock(L);
        n = (*ci->u.c.k)(L, LUA_YIELD, ci->u.c.ctx); /* call continuation */
        lua_lock(L);
        api_checknelems(L, n);
        firstArg = L->top - n;  /* yield results come from continuation */
      }
      luaD_poscall(L, ci, firstArg, n);  /* finish 'luaD_precall' */
    }
    unroll(L, NULL);  /* run continuation */
  }
}
References api_checknelems, CallInfo::c, cast, lua_State::ci, CallInfo::ctx, CallInfo::extra, CallInfo::func, isLua, CallInfo::k, lua_assert, lua_lock, LUA_MULTRET, LUA_OK, lua_unlock, LUA_YIELD, luaD_poscall(), luaD_precall(), luaV_execute(), NULL, restorestack, lua_State::status, lua_State::top, CallInfo::u, and unroll().
Referenced by lua_resume().
resume_error()
static int resume_error (lua_State * L, const char * msg, int narg) static
Definition at line 603 of file lua-5.3.6/src/ldo.c.
{
  L->top -= narg;  /* remove args from the stack */
  setsvalue2s(L, L->top, luaS_new(L, msg));  /* push error message */
  api_incr_top(L);
  lua_unlock(L);
  return LUA_ERRRUN;
}
References api_incr_top, LUA_ERRRUN, lua_unlock, luaS_new, setsvalue2s, and lua_State::top.
Referenced by lua_resume().
seterrorobj()
static void seterrorobj (lua_State * L, int errcode, StkId oldtop) static
Definition at line 91 of file lua-5.3.6/src/ldo.c.
{
  switch (errcode) {
    case LUA_ERRMEM: {  /* memory error? */
      setsvalue2s(L, oldtop, G(L)->memerrmsg); /* reuse preregistered msg. */
      break;
    }
    case LUA_ERRERR: {
      setsvalue2s(L, oldtop, luaS_newliteral(L, "error in error handling"));
      break;
    }
    default: {
      setobjs2s(L, oldtop, L->top - 1);  /* error message on current top */
      break;
    }
  }
  L->top = oldtop + 1;
}
References G, LUA_ERRERR, LUA_ERRMEM, luaS_newliteral, setobjs2s, setsvalue2s, and lua_State::top.
Referenced by lua_resume(), luaD_pcall(), luaD_throw(), and recover().
stackerror()
static void stackerror (lua_State * L) static
Definition at line 481 of file lua-5.3.6/src/ldo.c.
{
  if (L->nCcalls == LUAI_MAXCCALLS)
    luaG_runerror(L, "C stack overflow");
  else if (L->nCcalls >= (LUAI_MAXCCALLS + (LUAI_MAXCCALLS>>3)))
    luaD_throw(L, LUA_ERRERR);  /* error while handing stack error */
}
References LUA_ERRERR, luaD_throw(), luaG_runerror(), LUAI_MAXCCALLS, and lua_State::nCcalls.
Referenced by luaD_call().
stackinuse()
static int stackinuse (lua_State * L) static
Definition at line 210 of file lua-5.3.6/src/ldo.c.
{
  CallInfo *ci;
  StkId lim = L->top;
  for (ci = L->ci; ci != NULL; ci = ci->previous) {
    if (lim < ci->top) lim = ci->top;
  }
  lua_assert(lim <= L->stack_last);
  return cast_int(lim - L->stack) + 1;  /* part of stack in use */
}
References cast_int, lua_State::ci, lua_assert, NULL, CallInfo::previous, lua_State::stack, CallInfo::top, and lua_State::top.
Referenced by luaD_shrinkstack().
tryfuncTM()
static void tryfuncTM (lua_State * L, StkId func) static
Definition at line 315 of file lua-5.3.6/src/ldo.c.
{
  const TValue *tm = luaT_gettmbyobj(L, func, TM_CALL);
  StkId p;
  if (!ttisfunction(tm))
    luaG_typeerror(L, func, "call");
  /* Open a hole inside the stack at 'func' */
  for (p = L->top; p > func; p--)
    setobjs2s(L, p, p-1);
  L->top++;  /* slot ensured by caller */
  setobj2s(L, func, tm);  /* tag method is the new function to be called */
}
References luaG_typeerror(), luaT_gettmbyobj(), setobj2s, setobjs2s, TM_CALL, lua_State::top, and ttisfunction.
Referenced by luaD_precall().
unroll()
static void unroll (lua_State * L, void * ud) static
Definition at line 548 of file lua-5.3.6/src/ldo.c.
{
  if (ud != NULL)  /* error status? */
    finishCcall(L, *(int *)ud);  /* finish 'lua_pcallk' callee */
  while (L->ci != &L->base_ci) {  /* something in the stack */
    if (!isLua(L->ci))  /* C function? */
      finishCcall(L, LUA_YIELD);  /* complete its execution */
    else {  /* Lua function */
      luaV_finishOp(L);  /* finish interrupted instruction */
      luaV_execute(L);  /* execute down to higher C 'boundary' */
    }
  }
}
References lua_State::base_ci, lua_State::ci, finishCcall(), isLua, LUA_YIELD, luaV_execute(), luaV_finishOp(), and NULL.
Referenced by lua_resume(), and resume().