Github User Fetcher: ldebug.c File Reference
ldebug.c File Reference
#include <stdarg.h>
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "lcode.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lvm.h"
Macros
#define ldebug_c
#define LUA_CORE
#define check(x) if (!(x)) return 0;
#define checkjump(pt, pc) check(0 <= pc && pc < pt->sizecode)
#define checkreg(pt, reg) check((reg) < (pt)->maxstacksize)
#define checkopenop(pt, pc) luaG_checkopenop((pt)->code[(pc)+1])
Functions
static const char * getfuncname (lua_State *L, CallInfo *ci, const char **name)
static int currentpc (lua_State *L, CallInfo *ci)
static int currentline (lua_State *L, CallInfo *ci)
LUA_API int lua_sethook (lua_State *L, lua_Hook func, int mask, int count)
LUA_API lua_Hook lua_gethook (lua_State *L)
LUA_API int lua_gethookmask (lua_State *L)
LUA_API int lua_gethookcount (lua_State *L)
LUA_API int lua_getstack (lua_State *L, int level, lua_Debug *ar)
static Proto * getluaproto (CallInfo *ci)
static const char * findlocal (lua_State *L, CallInfo *ci, int n)
LUA_API const char * lua_getlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char * lua_setlocal (lua_State *L, const lua_Debug *ar, int n)
static void funcinfo (lua_Debug *ar, Closure *cl)
static void info_tailcall (lua_Debug *ar)
static void collectvalidlines (lua_State *L, Closure *f)
static int auxgetinfo (lua_State *L, const char *what, lua_Debug *ar, Closure *f, CallInfo *ci)
LUA_API int lua_getinfo (lua_State *L, const char *what, lua_Debug *ar)
static int precheck (const Proto *pt)
int luaG_checkopenop (Instruction i)
static int checkArgMode (const Proto *pt, int r, enum OpArgMask mode)
static Instruction symbexec (const Proto *pt, int lastpc, int reg)
int luaG_checkcode (const Proto *pt)
static const char * kname (Proto *p, int c)
static const char * getobjname (lua_State *L, CallInfo *ci, int stackpos, const char **name)
static int isinstack (CallInfo *ci, const TValue *o)
void luaG_typeerror (lua_State *L, const TValue *o, const char *op)
void luaG_concaterror (lua_State *L, StkId p1, StkId p2)
void luaG_aritherror (lua_State *L, const TValue *p1, const TValue *p2)
int luaG_ordererror (lua_State *L, const TValue *p1, const TValue *p2)
static void addinfo (lua_State *L, const char *msg)
void luaG_errormsg (lua_State *L)
void luaG_runerror (lua_State *L, const char *fmt,...)
Macro Definition Documentation
check
#define check (x) if (!(x)) return 0;
Definition at line 268 of file lua-5.1.5/src/ldebug.c.
Referenced by checkArgMode(), checknext(), checknext(), checknext(), checknext(), luaG_checkopenop(), luaY_parser(), mainfunc(), mainfunc(), mainfunc(), precheck(), str_checkname(), str_checkname(), str_checkname(), str_checkname(), and symbexec().
checkjump
#define checkjump (pt, pc) check(0 <= pc && pc < pt->sizecode)
Definition at line 270 of file lua-5.1.5/src/ldebug.c.
checkopenop
#define checkopenop (pt, pc) luaG_checkopenop((pt)->code[(pc)+1])
Definition at line 288 of file lua-5.1.5/src/ldebug.c.
Referenced by symbexec().
checkreg
#define checkreg (pt, reg) check((reg) < (pt)->maxstacksize)
Definition at line 272 of file lua-5.1.5/src/ldebug.c.
Referenced by checkArgMode(), and symbexec().
ldebug_c
#define ldebug_c
Definition at line 13 of file lua-5.1.5/src/ldebug.c.
LUA_CORE
#define LUA_CORE
Definition at line 14 of file lua-5.1.5/src/ldebug.c.
Function Documentation
addinfo()
static void addinfo (lua_State * L, const char * msg) static
Definition at line 607 of file lua-5.1.5/src/ldebug.c.
{
  CallInfo *ci = L->ci;
  if (isLua(ci)) {  /* is Lua code? */
    char buff[LUA_IDSIZE];  /* add file:line information */
    int line = currentline(L, ci);
    luaO_chunkid(buff, getstr(getluaproto(ci)->source), LUA_IDSIZE);
    luaO_pushfstring(L, "%s:%d: %s", buff, line, msg);
  }
}
References lua_State::ci, currentline(), getluaproto(), getstr, isLua, LUA_IDSIZE, luaO_chunkid(), and luaO_pushfstring().
Referenced by luaG_runerror().
auxgetinfo()
static int auxgetinfo (lua_State * L, const char * what, lua_Debug * ar, Closure * f, CallInfo * ci) static
Definition at line 193 of file lua-5.1.5/src/ldebug.c.
{
  int status = 1;
  if (f == NULL) {
    info_tailcall(ar);
    return status;
  }
  for (; *what; what++) {
    switch (*what) {
      case 'S': {
        funcinfo(ar, f);
        break;
      }
      case 'l': {
        ar->currentline = (ci) ? currentline(L, ci) : -1;
        break;
      }
      case 'u': {
        ar->nups = f->c.nupvalues;
        break;
      }
      case 'n': {
        ar->namewhat = (ci) ? getfuncname(L, ci, &ar->name) : NULL;
        if (ar->namewhat == NULL) {
          ar->namewhat = "";  /* not found */
          ar->name = NULL;
        }
        break;
      }
      case 'L':
      case 'f':  /* handled by lua_getinfo */
        break;
      default: status = 0;  /* invalid option */
    }
  }
  return status;
}
References Closure::c, currentline(), lua_Debug::currentline, funcinfo(), getfuncname(), info_tailcall(), lua_Debug::name, lua_Debug::namewhat, NULL, and lua_Debug::nups.
Referenced by lua_getinfo().
checkArgMode()
static int checkArgMode (const Proto * pt, int r, enum OpArgMask mode) static
Definition at line 304 of file lua-5.1.5/src/ldebug.c.
{
  switch (mode) {
    case OpArgN: check(r == 0); break;
    case OpArgU: break;
    case OpArgR: checkreg(pt, r); break;
    case OpArgK:
      check(ISK(r) ? INDEXK(r) < pt->sizek : r < pt->maxstacksize);
      break;
  }
  return 1;
}
References check, checkreg, INDEXK, ISK, Proto::maxstacksize, OpArgK, OpArgN, OpArgR, OpArgU, and Proto::sizek.
Referenced by symbexec().
collectvalidlines()
static void collectvalidlines (lua_State * L, Closure * f) static
Definition at line 177 of file lua-5.1.5/src/ldebug.c.
{
  if (f == NULL || f->c.isC) {
    setnilvalue(L->top);
  }
  else {
    Table *t = luaH_new(L, 0, 0);
    int *lineinfo = f->l.p->lineinfo;
    int i;
    for (i=0; i<f->l.p->sizelineinfo; i++)
      setbvalue(luaH_setnum(L, t, lineinfo[i]), 1);
    sethvalue(L, L->top, t);
  }
  incr_top(L);
}
References Closure::c, incr_top, Closure::l, Proto::lineinfo, luaH_new(), luaH_setnum(), NULL, LClosure::p, setbvalue, sethvalue, setnilvalue, Proto::sizelineinfo, and lua_State::top.
Referenced by lua_getinfo().
currentline()
static int currentline (lua_State * L, CallInfo * ci) static
Definition at line 44 of file lua-5.1.5/src/ldebug.c.
{
  int pc = currentpc(L, ci);
  if (pc < 0)
    return -1;  /* only active lua functions have current-line information */
  else
    return getline(ci_func(ci)->l.p, pc);
}
References ci_func, currentpc(), and getline.
Referenced by addinfo(), auxgetinfo(), collectvalidlines(), and nextline().
currentpc()
static int currentpc (lua_State * L, CallInfo * ci) static
Definition at line 36 of file lua-5.1.5/src/ldebug.c.
{
  if (!isLua(ci)) return -1;  /* function is not a Lua function? */
  if (ci == L->ci)
    ci->savedpc = L->savedpc;
  return pcRel(ci->savedpc, ci_func(ci)->l.p);
}
References lua_State::ci, ci_func, isLua, pcRel, CallInfo::savedpc, and lua_State::savedpc.
Referenced by currentline(), findlocal(), getfuncname(), and getobjname().
findlocal()
static const char * findlocal (lua_State * L, CallInfo * ci, int n) static
Definition at line 112 of file lua-5.1.5/src/ldebug.c.
{
  const char *name;
  Proto *fp = getluaproto(ci);
  if (fp && (name = luaF_getlocalname(fp, n, currentpc(L, ci))) != NULL)
    return name;  /* is a local variable in a Lua function */
  else {
    StkId limit = (ci == L->ci) ? L->top : (ci+1)->func;
    if (limit - ci->base >= n && n > 0)  /* is 'n' inside 'ci' stack? */
      return "(*temporary)";
    else
      return NULL;
  }
}
References CallInfo::base, lua_State::ci, currentpc(), getluaproto(), luaF_getlocalname(), name, NULL, and lua_State::top.
Referenced by lua_getlocal(), and lua_setlocal().
funcinfo()
static void funcinfo (lua_Debug * ar, Closure * cl) static
Definition at line 150 of file lua-5.1.5/src/ldebug.c.
{
  if (cl->c.isC) {
    ar->source = "=[C]";
    ar->linedefined = -1;
    ar->lastlinedefined = -1;
    ar->what = "C";
  }
  else {
    ar->source = getstr(cl->l.p->source);
    ar->linedefined = cl->l.p->linedefined;
    ar->lastlinedefined = cl->l.p->lastlinedefined;
    ar->what = (ar->linedefined == 0) ? "main" : "Lua";
  }
  luaO_chunkid(ar->short_src, ar->source, LUA_IDSIZE);
}
References Closure::c, getstr, Closure::l, Proto::lastlinedefined, lua_Debug::lastlinedefined, Proto::linedefined, lua_Debug::linedefined, LUA_IDSIZE, luaO_chunkid(), LClosure::p, lua_Debug::short_src, Proto::source, lua_Debug::source, and lua_Debug::what.
Referenced by auxgetinfo().
getfuncname()
static const char * getfuncname (lua_State * L, CallInfo * ci, const char ** name) static
Definition at line 544 of file lua-5.1.5/src/ldebug.c.
{
  Instruction i;
  if ((isLua(ci) && ci->tailcalls > 0) || !isLua(ci - 1))
    return NULL;  /* calling function is not Lua (or is unknown) */
  ci--;  /* calling function */
  i = ci_func(ci)->l.p->code[currentpc(L, ci)];
  if (GET_OPCODE(i) == OP_CALL || GET_OPCODE(i) == OP_TAILCALL ||
      GET_OPCODE(i) == OP_TFORLOOP)
    return getobjname(L, ci, GETARG_A(i), name);
  else
    return NULL;  /* no useful name can be found */
}
References ci_func, currentpc(), GET_OPCODE, GETARG_A, getobjname(), isLua, CallInfo::l, name, NULL, OP_CALL, OP_TAILCALL, OP_TFORLOOP, and CallInfo::tailcalls.
Referenced by auxgetinfo().
getluaproto()
static Proto * getluaproto (CallInfo * ci) static
Definition at line 107 of file lua-5.1.5/src/ldebug.c.
{
  return (isLua(ci) ? ci_func(ci)->l.p : NULL);
}
References ci_func, isLua, and NULL.
Referenced by addinfo(), and findlocal().
getobjname()
static const char * getobjname (lua_State * L, CallInfo * ci, int stackpos, const char ** name) static
Definition at line 497 of file lua-5.1.5/src/ldebug.c.
{
  if (isLua(ci)) {  /* a Lua function? */
    Proto *p = ci_func(ci)->l.p;
    int pc = currentpc(L, ci);
    Instruction i;
    *name = luaF_getlocalname(p, stackpos+1, pc);
    if (*name)  /* is a local? */
      return "local";
    i = symbexec(p, pc, stackpos);  /* try symbolic execution */
    lua_assert(pc != -1);
    switch (GET_OPCODE(i)) {
      case OP_GETGLOBAL: {
        int g = GETARG_Bx(i);  /* global index */
        lua_assert(ttisstring(&p->k[g]));
        *name = svalue(&p->k[g]);
        return "global";
      }
      case OP_MOVE: {
        int a = GETARG_A(i);
        int b = GETARG_B(i);  /* move from `b' to `a' */
        if (b < a)
          return getobjname(L, ci, b, name);  /* get name for `b' */
        break;
      }
      case OP_GETTABLE: {
        int k = GETARG_C(i);  /* key index */
        *name = kname(p, k);
        return "field";
      }
      case OP_GETUPVAL: {
        int u = GETARG_B(i);  /* upvalue index */
        *name = p->upvalues ? getstr(p->upvalues[u]) : "?";
        return "upvalue";
      }
      case OP_SELF: {
        int k = GETARG_C(i);  /* key index */
        *name = kname(p, k);
        return "method";
      }
      default: break;
    }
  }
  return NULL;  /* no useful name found */
}
References ci_func, currentpc(), GET_OPCODE, GETARG_A, GETARG_B, GETARG_Bx, GETARG_C, getobjname(), getstr, isLua, Proto::k, kname(), lua_assert, luaF_getlocalname(), name, NULL, OP_GETGLOBAL, OP_GETTABLE, OP_GETUPVAL, OP_MOVE, OP_SELF, Proto::p, svalue, symbexec(), ttisstring, and Proto::upvalues.
Referenced by getfuncname(), getobjname(), and luaG_typeerror().
info_tailcall()
static void info_tailcall (lua_Debug * ar) static
Definition at line 167 of file lua-5.1.5/src/ldebug.c.
{
  ar->name = ar->namewhat = "";
  ar->what = "tail";
  ar->lastlinedefined = ar->linedefined = ar->currentline = -1;
  ar->source = "=(tail call)";
  luaO_chunkid(ar->short_src, ar->source, LUA_IDSIZE);
  ar->nups = 0;
}
References lua_Debug::currentline, lua_Debug::lastlinedefined, lua_Debug::linedefined, LUA_IDSIZE, luaO_chunkid(), lua_Debug::name, lua_Debug::namewhat, lua_Debug::nups, lua_Debug::short_src, lua_Debug::source, and lua_Debug::what.
Referenced by auxgetinfo().
isinstack()
static int isinstack (CallInfo * ci, const TValue * o) static
Definition at line 559 of file lua-5.1.5/src/ldebug.c.
{
  StkId p;
  for (p = ci->base; p < ci->top; p++)
    if (o == p) return 1;
  return 0;
}
References CallInfo::base, and CallInfo::top.
Referenced by luaG_typeerror().
kname()
static const char * kname (Proto * p, int c) static
Definition at line 489 of file lua-5.1.5/src/ldebug.c.
{
  if (ISK(c) && ttisstring(&p->k[INDEXK(c)]))
    return svalue(&p->k[INDEXK(c)]);
  else
    return "?";
}
References INDEXK, ISK, Proto::k, svalue, and ttisstring.
Referenced by getobjname().
lua_gethook()
LUA_API lua_Hook lua_gethook (lua_State * L)
Definition at line 69 of file lua-5.1.5/src/ldebug.c.
{
  return L->hook;
}
References lua_State::hook.
Referenced by db_gethook(), db_gethook(), db_gethook(), and db_gethook().
lua_gethookcount()
LUA_API int lua_gethookcount (lua_State * L)
Definition at line 79 of file lua-5.1.5/src/ldebug.c.
{
  return L->basehookcount;
}
References lua_State::basehookcount.
Referenced by db_gethook(), db_gethook(), db_gethook(), and db_gethook().
lua_gethookmask()
LUA_API int lua_gethookmask (lua_State * L)
Definition at line 74 of file lua-5.1.5/src/ldebug.c.
{
  return L->hookmask;
}
References lua_State::hookmask.
Referenced by db_gethook(), db_gethook(), db_gethook(), and db_gethook().
lua_getinfo()
LUA_API int lua_getinfo (lua_State * L, const char * what, lua_Debug * ar)
Definition at line 232 of file lua-5.1.5/src/ldebug.c.
{
  int status;
  Closure *f = NULL;
  CallInfo *ci = NULL;
  lua_lock(L);
  if (*what == '>') {
    StkId func = L->top - 1;
    luai_apicheck(L, ttisfunction(func));
    what++;  /* skip the '>' */
    f = clvalue(func);
    L->top--;  /* pop function */
  }
  else if (ar->i_ci != 0) {  /* no tail call? */
    ci = L->base_ci + ar->i_ci;
    lua_assert(ttisfunction(ci->func));
    f = clvalue(ci->func);
  }
  status = auxgetinfo(L, what, ar, f, ci);
  if (strchr(what, 'f')) {
    if (f == NULL) setnilvalue(L->top);
    else setclvalue(L, L->top, f);
    incr_top(L);
  }
  if (strchr(what, 'L'))
    collectvalidlines(L, f);
  lua_unlock(L);
  return status;
}
References auxgetinfo(), lua_State::base_ci, clvalue, collectvalidlines(), CallInfo::func, lua_Debug::i_ci, incr_top, lua_assert, lua_lock, lua_unlock, luai_apicheck, NULL, setclvalue, setnilvalue, lua_State::top, and ttisfunction.
Referenced by checkupval(), db_errorfb(), db_getinfo(), db_getinfo(), db_getinfo(), db_getinfo(), getfunc(), hookf(), hookf(), hookf(), hookf(), luaL_argerror(), luaL_argerror(), luaL_traceback(), luaL_where(), pushglobalfuncname(), pushglobalfuncname(), pushglobalfuncname(), and setfenv().
lua_getlocal()
LUA_API const char * lua_getlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 127 of file lua-5.1.5/src/ldebug.c.
{
  CallInfo *ci = L->base_ci + ar->i_ci;
  const char *name = findlocal(L, ci, n);
  lua_lock(L);
  if (name)
      luaA_pushobject(L, ci->base + (n - 1));
  lua_unlock(L);
  return name;
}
References CallInfo::base, lua_State::base_ci, findlocal(), lua_Debug::i_ci, lua_lock, lua_unlock, luaA_pushobject(), and name.
Referenced by db_getlocal(), db_getlocal(), db_getlocal(), and db_getlocal().
lua_getstack()
LUA_API int lua_getstack (lua_State * L, int level, lua_Debug * ar)
Definition at line 84 of file lua-5.1.5/src/ldebug.c.
{
  int status;
  CallInfo *ci;
  lua_lock(L);
  for (ci = L->ci; level > 0 && ci > L->base_ci; ci--) {
    level--;
    if (f_isLua(ci))  /* Lua function? */
      level -= ci->tailcalls;  /* skip lost tail calls */
  }
  if (level == 0 && ci > L->base_ci) {  /* level found? */
    status = 1;
    ar->i_ci = cast_int(ci - L->base_ci);
  }
  else if (level < 0) {  /* level is of a lost tail call? */
    status = 1;
    ar->i_ci = 0;
  }
  else status = 0;  /* no such level */
  lua_unlock(L);
  return status;
}
References lua_State::base_ci, cast_int, lua_State::ci, f_isLua, lua_Debug::i_ci, lua_lock, lua_unlock, and CallInfo::tailcalls.
Referenced by auxstatus(), costatus(), countlevels(), db_errorfb(), db_getinfo(), db_getinfo(), db_getinfo(), db_getinfo(), db_getlocal(), db_getlocal(), db_getlocal(), db_getlocal(), db_setlocal(), db_setlocal(), db_setlocal(), db_setlocal(), getfunc(), lastlevel(), lastlevel(), luaB_costatus(), luaB_costatus(), luaL_argerror(), luaL_argerror(), luaL_traceback(), luaL_where(), and setfenv().
lua_sethook()
LUA_API int lua_sethook (lua_State * L, lua_Hook func, int mask, int count)
Definition at line 56 of file lua-5.1.5/src/ldebug.c.
{
  if (func == NULL || mask == 0) {  /* turn off hooks? */
    mask = 0;
    func = NULL;
  }
  L->hook = func;
  L->basehookcount = count;
  resethookcount(L);
  L->hookmask = cast_byte(mask);
  return 1;
}
References lua_State::basehookcount, cast_byte, lua_State::hook, lua_State::hookmask, mask, NULL, and resethookcount.
Referenced by db_sethook(), db_sethook(), db_sethook(), db_sethook(), laction(), laction(), laction(), laction(), lstop(), lstop(), lstop(), and lstop().
lua_setlocal()
LUA_API const char * lua_setlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 138 of file lua-5.1.5/src/ldebug.c.
{
  CallInfo *ci = L->base_ci + ar->i_ci;
  const char *name = findlocal(L, ci, n);
  lua_lock(L);
  if (name)
      setobjs2s(L, ci->base + (n - 1), L->top - 1);
  L->top--;  /* pop value */
  lua_unlock(L);
  return name;
}
References CallInfo::base, lua_State::base_ci, findlocal(), lua_Debug::i_ci, lua_lock, lua_unlock, name, setobjs2s, and lua_State::top.
Referenced by db_setlocal(), db_setlocal(), db_setlocal(), and db_setlocal().
luaG_aritherror()
void luaG_aritherror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 588 of file lua-5.1.5/src/ldebug.c.
{
  TValue temp;
  if (luaV_tonumber(p1, &temp) == NULL)
    p2 = p1;  /* first operand is wrong */
  luaG_typeerror(L, p2, "perform arithmetic on");
}
References luaG_typeerror(), luaV_tonumber(), and NULL.
Referenced by Arith(), and luaV_arith().
luaG_checkcode()
int luaG_checkcode (const Proto * pt)
Definition at line 484 of file lua-5.1.5/src/ldebug.c.
{
  return (symbexec(pt, pt->sizecode, NO_REG) != 0);
}
References NO_REG, Proto::sizecode, and symbexec().
Referenced by close_func(), and LoadFunction().
luaG_checkopenop()
int luaG_checkopenop (Instruction i)
Definition at line 290 of file lua-5.1.5/src/ldebug.c.
{
  switch (GET_OPCODE(i)) {
    case OP_CALL:
    case OP_TAILCALL:
    case OP_RETURN:
    case OP_SETLIST: {
      check(GETARG_B(i) == 0);
      return 1;
    }
    default: return 0;  /* invalid instruction after an open call */
  }
}
References check, GET_OPCODE, GETARG_B, OP_CALL, OP_RETURN, OP_SETLIST, and OP_TAILCALL.
Referenced by luaV_execute().
luaG_concaterror()
void luaG_concaterror (lua_State * L, StkId p1, StkId p2)
Definition at line 581 of file lua-5.1.5/src/ldebug.c.
{
  if (ttisstring(p1) || ttisnumber(p1)) p1 = p2;
  lua_assert(!ttisstring(p1) && !ttisnumber(p1));
  luaG_typeerror(L, p1, "concatenate");
}
References lua_assert, luaG_typeerror(), ttisnumber, and ttisstring.
Referenced by luaT_trybinTM(), luaT_tryconcatTM(), luaV_concat(), and luaV_concat().
luaG_errormsg()
void luaG_errormsg (lua_State * L)
Definition at line 618 of file lua-5.1.5/src/ldebug.c.
{
  if (L->errfunc != 0) {  /* is there an error handling function? */
    StkId errfunc = restorestack(L, L->errfunc);
    if (!ttisfunction(errfunc)) luaD_throw(L, LUA_ERRERR);
    setobjs2s(L, L->top, L->top - 1);  /* move argument */
    setobjs2s(L, L->top - 1, errfunc);  /* push function */
    incr_top(L);
    luaD_call(L, L->top - 2, 1);  /* call it */
  }
  luaD_throw(L, LUA_ERRRUN);
}
References lua_State::errfunc, incr_top, LUA_ERRERR, LUA_ERRRUN, luaD_call(), luaD_throw(), restorestack, setobjs2s, lua_State::top, and ttisfunction.
Referenced by lua_error(), and luaG_runerror().
luaG_ordererror()
int luaG_ordererror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 596 of file lua-5.1.5/src/ldebug.c.
{
  const char *t1 = luaT_typenames[ttype(p1)];
  const char *t2 = luaT_typenames[ttype(p2)];
  if (t1[2] == t2[2])
    luaG_runerror(L, "attempt to compare two %s values", t1);
  else
    luaG_runerror(L, "attempt to compare %s with %s", t1, t2);
  return 0;
}
References luaG_runerror(), luaT_typenames, and ttype.
Referenced by lessequal(), luaT_callorderTM(), luaV_lessequal(), and luaV_lessthan().
luaG_runerror()
void luaG_runerror (lua_State * L, const char * fmt, ...)
Definition at line 631 of file lua-5.1.5/src/ldebug.c.
{
  va_list argp;
  va_start(argp, fmt);
  addinfo(L, luaO_pushvfstring(L, fmt, argp));
  va_end(argp);
  luaG_errormsg(L);
}
References addinfo(), luaG_errormsg(), and luaO_pushvfstring().
Referenced by checkclosemth(), findindex(), findindex(), findindex(), findindex(), forprep(), growCI(), lua_pushnumber(), lua_replace(), lua_yield(), lua_yieldk(), lua_yieldk(), luaD_call(), luaD_call(), luaD_growstack(), luaD_growstack(), luaE_checkcstack(), luaG_ordererror(), luaG_typeerror(), luaH_newkey(), luaH_newkey(), luaH_set(), luaM_growaux_(), luaM_growaux_(), luaM_growaux_(), luaM_toobig(), luaO_pushvfstring(), luaV_concat(), luaV_concat(), luaV_div(), luaV_execute(), luaV_execute(), luaV_finishget(), luaV_finishset(), luaV_finishset(), luaV_gettable(), luaV_idiv(), luaV_mod(), luaV_settable(), setnodevector(), setnodevector(), setnodevector(), setnodevector(), and stackerror().
luaG_typeerror()
void luaG_typeerror (lua_State * L, const TValue * o, const char * op)
Definition at line 567 of file lua-5.1.5/src/ldebug.c.
{
  const char *name = NULL;
  const char *t = luaT_typenames[ttype(o)];
  const char *kind = (isinstack(L->ci, o)) ?
                         getobjname(L, L->ci, cast_int(o - L->base), &name) :
                         NULL;
  if (kind)
    luaG_runerror(L, "attempt to %s %s " LUA_QS " (a %s value)",
                op, kind, name, t);
  else
    luaG_runerror(L, "attempt to %s a %s value", op, t);
}
References lua_State::base, cast_int, lua_State::ci, getobjname(), isinstack(), LUA_QS, luaG_runerror(), luaT_typenames, name, NULL, and ttype.
Referenced by luaG_aritherror(), luaG_concaterror(), luaV_execute(), luaV_finishget(), luaV_finishset(), luaV_finishset(), luaV_gettable(), luaV_objlen(), luaV_settable(), tryfuncTM(), tryfuncTM(), and tryfuncTM().
precheck()
static int precheck (const Proto * pt) static
Definition at line 276 of file lua-5.1.5/src/ldebug.c.
{
  check(pt->maxstacksize <= MAXSTACK);
  check(pt->numparams+(pt->is_vararg & VARARG_HASARG) <= pt->maxstacksize);
  check(!(pt->is_vararg & VARARG_NEEDSARG) ||
              (pt->is_vararg & VARARG_HASARG));
  check(pt->sizeupvalues <= pt->nups);
  check(pt->sizelineinfo == pt->sizecode || pt->sizelineinfo == 0);
  check(pt->sizecode > 0 && GET_OPCODE(pt->code[pt->sizecode-1]) == OP_RETURN);
  return 1;
}
References check, Proto::code, GET_OPCODE, Proto::is_vararg, MAXSTACK, Proto::maxstacksize, Proto::numparams, Proto::nups, OP_RETURN, Proto::sizecode, Proto::sizelineinfo, Proto::sizeupvalues, VARARG_HASARG, and VARARG_NEEDSARG.
Referenced by symbexec().
symbexec()
static Instruction symbexec (const Proto * pt, int lastpc, int reg) static
Definition at line 317 of file lua-5.1.5/src/ldebug.c.
{
  int pc;
  int last;  /* stores position of last instruction that changed `reg' */
  last = pt->sizecode-1;  /* points to final return (a `neutral' instruction) */
  check(precheck(pt));
  for (pc = 0; pc < lastpc; pc++) {
    Instruction i = pt->code[pc];
    OpCode op = GET_OPCODE(i);
    int a = GETARG_A(i);
    int b = 0;
    int c = 0;
    check(op < NUM_OPCODES);
    checkreg(pt, a);
    switch (getOpMode(op)) {
      case iABC: {
        b = GETARG_B(i);
        c = GETARG_C(i);
        check(checkArgMode(pt, b, getBMode(op)));
        check(checkArgMode(pt, c, getCMode(op)));
        break;
      }
      case iABx: {
        b = GETARG_Bx(i);
        if (getBMode(op) == OpArgK) check(b < pt->sizek);
        break;
      }
      case iAsBx: {
        b = GETARG_sBx(i);
        if (getBMode(op) == OpArgR) {
          int dest = pc+1+b;
          check(0 <= dest && dest < pt->sizecode);
          if (dest > 0) {
            int j;
            /* check that it does not jump to a setlist count; this
               is tricky, because the count from a previous setlist may
               have the same value of an invalid setlist; so, we must
               go all the way back to the first of them (if any) */
            for (j = 0; j < dest; j++) {
              Instruction d = pt->code[dest-1-j];
              if (!(GET_OPCODE(d) == OP_SETLIST && GETARG_C(d) == 0)) break;
            }
            /* if 'j' is even, previous value is not a setlist (even if
               it looks like one) */
            check((j&1) == 0);
          }
        }
        break;
      }
    }
    if (testAMode(op)) {
      if (a == reg) last = pc;  /* change register `a' */
    }
    if (testTMode(op)) {
      check(pc+2 < pt->sizecode);  /* check skip */
      check(GET_OPCODE(pt->code[pc+1]) == OP_JMP);
    }
    switch (op) {
      case OP_LOADBOOL: {
        if (c == 1) {  /* does it jump? */
          check(pc+2 < pt->sizecode);  /* check its jump */
          check(GET_OPCODE(pt->code[pc+1]) != OP_SETLIST ||
                GETARG_C(pt->code[pc+1]) != 0);
        }
        break;
      }
      case OP_LOADNIL: {
        if (a <= reg && reg <= b)
          last = pc;  /* set registers from `a' to `b' */
        break;
      }
      case OP_GETUPVAL:
      case OP_SETUPVAL: {
        check(b < pt->nups);
        break;
      }
      case OP_GETGLOBAL:
      case OP_SETGLOBAL: {
        check(ttisstring(&pt->k[b]));
        break;
      }
      case OP_SELF: {
        checkreg(pt, a+1);
        if (reg == a+1) last = pc;
        break;
      }
      case OP_CONCAT: {
        check(b < c);  /* at least two operands */
        break;
      }
      case OP_TFORLOOP: {
        check(c >= 1);  /* at least one result (control variable) */
        checkreg(pt, a+2+c);  /* space for results */
        if (reg >= a+2) last = pc;  /* affect all regs above its base */
        break;
      }
      case OP_FORLOOP:
      case OP_FORPREP:
        checkreg(pt, a+3);
        /* go through */
      case OP_JMP: {
        int dest = pc+1+b;
        /* not full check and jump is forward and do not skip `lastpc'? */
        if (reg != NO_REG && pc < dest && dest <= lastpc)
          pc += b;  /* do the jump */
        break;
      }
      case OP_CALL:
      case OP_TAILCALL: {
        if (b != 0) {
          checkreg(pt, a+b-1);
        }
        c--;  /* c = num. returns */
        if (c == LUA_MULTRET) {
          check(checkopenop(pt, pc));
        }
        else if (c != 0)
          checkreg(pt, a+c-1);
        if (reg >= a) last = pc;  /* affect all registers above base */
        break;
      }
      case OP_RETURN: {
        b--;  /* b = num. returns */
        if (b > 0) checkreg(pt, a+b-1);
        break;
      }
      case OP_SETLIST: {
        if (b > 0) checkreg(pt, a + b);
        if (c == 0) {
          pc++;
          check(pc < pt->sizecode - 1);
        }
        break;
      }
      case OP_CLOSURE: {
        int nup, j;
        check(b < pt->sizep);
        nup = pt->p[b]->nups;
        check(pc + nup < pt->sizecode);
        for (j = 1; j <= nup; j++) {
          OpCode op1 = GET_OPCODE(pt->code[pc + j]);
          check(op1 == OP_GETUPVAL || op1 == OP_MOVE);
        }
        if (reg != NO_REG)  /* tracing? */
          pc += nup;  /* do not 'execute' these pseudo-instructions */
        break;
      }
      case OP_VARARG: {
        check((pt->is_vararg & VARARG_ISVARARG) &&
             !(pt->is_vararg & VARARG_NEEDSARG));
        b--;
        if (b == LUA_MULTRET) check(checkopenop(pt, pc));
        checkreg(pt, a+b-1);
        break;
      }
      default: break;
    }
  }
  return pt->code[last];
}
References check, checkArgMode(), checkopenop, checkreg, Proto::code, GET_OPCODE, GETARG_A, GETARG_B, GETARG_Bx, GETARG_C, GETARG_sBx, getBMode, getCMode, getOpMode, iABC, iABx, iAsBx, Proto::is_vararg, Proto::k, LUA_MULTRET, NO_REG, NUM_OPCODES, Proto::nups, OP_CALL, OP_CLOSURE, OP_CONCAT, OP_FORLOOP, OP_FORPREP, OP_GETGLOBAL, OP_GETUPVAL, OP_JMP, OP_LOADBOOL, OP_LOADNIL, OP_MOVE, OP_RETURN, OP_SELF, OP_SETGLOBAL, OP_SETLIST, OP_SETUPVAL, OP_TAILCALL, OP_TFORLOOP, OP_VARARG, OpArgK, OpArgR, Proto::p, precheck(), Proto::sizecode, testAMode, testTMode, ttisstring, VARARG_ISVARARG, and VARARG_NEEDSARG.
Referenced by getobjname(), and luaG_checkcode().