Github User Fetcher: lualib.h File Reference
lualib.h File Reference
#include "lua.h"
Macros
#define LUA_VERSUFFIX "_" LUA_VERSION_MAJOR "_" LUA_VERSION_MINOR
#define LUA_COLIBNAME "coroutine"
#define LUA_TABLIBNAME "table"
#define LUA_IOLIBNAME "io"
#define LUA_OSLIBNAME "os"
#define LUA_STRLIBNAME "string"
#define LUA_UTF8LIBNAME "utf8"
#define LUA_BITLIBNAME "bit32"
#define LUA_MATHLIBNAME "math"
#define LUA_DBLIBNAME "debug"
#define LUA_LOADLIBNAME "package"
#define lua_assert(x) ((void)0)
Functions
LUAMOD_API int luaopen_base (lua_State *L)
LUAMOD_API int luaopen_coroutine (lua_State *L)
LUAMOD_API int luaopen_table (lua_State *L)
LUAMOD_API int luaopen_io (lua_State *L)
LUAMOD_API int luaopen_os (lua_State *L)
LUAMOD_API int luaopen_string (lua_State *L)
LUAMOD_API int luaopen_utf8 (lua_State *L)
LUAMOD_API int luaopen_bit32 (lua_State *L)
LUAMOD_API int luaopen_math (lua_State *L)
LUAMOD_API int luaopen_debug (lua_State *L)
LUAMOD_API int luaopen_package (lua_State *L)
LUALIB_API void luaL_openlibs (lua_State *L)
Macro Definition Documentation
lua_assert
#define lua_assert (x) ((void)0)
Definition at line 57 of file lua-5.3.6/src/lualib.h.
LUA_BITLIBNAME
#define LUA_BITLIBNAME "bit32"
Definition at line 38 of file lua-5.3.6/src/lualib.h.
LUA_COLIBNAME
#define LUA_COLIBNAME "coroutine"
Definition at line 20 of file lua-5.3.6/src/lualib.h.
LUA_DBLIBNAME
#define LUA_DBLIBNAME "debug"
Definition at line 44 of file lua-5.3.6/src/lualib.h.
LUA_IOLIBNAME
#define LUA_IOLIBNAME "io"
Definition at line 26 of file lua-5.3.6/src/lualib.h.
LUA_LOADLIBNAME
#define LUA_LOADLIBNAME "package"
Definition at line 47 of file lua-5.3.6/src/lualib.h.
LUA_MATHLIBNAME
#define LUA_MATHLIBNAME "math"
Definition at line 41 of file lua-5.3.6/src/lualib.h.
LUA_OSLIBNAME
#define LUA_OSLIBNAME "os"
Definition at line 29 of file lua-5.3.6/src/lualib.h.
LUA_STRLIBNAME
#define LUA_STRLIBNAME "string"
Definition at line 32 of file lua-5.3.6/src/lualib.h.
LUA_TABLIBNAME
#define LUA_TABLIBNAME "table"
Definition at line 23 of file lua-5.3.6/src/lualib.h.
LUA_UTF8LIBNAME
#define LUA_UTF8LIBNAME "utf8"
Definition at line 35 of file lua-5.3.6/src/lualib.h.
LUA_VERSUFFIX
#define LUA_VERSUFFIX "_" LUA_VERSION_MAJOR "_" LUA_VERSION_MINOR
Definition at line 15 of file lua-5.3.6/src/lualib.h.
Referenced by setpath(), and setpath().
Function Documentation
luaL_openlibs()
LUALIB_API void luaL_openlibs (lua_State * L)
Definition at line 30 of file lua-5.1.5/src/linit.c.
{
  const luaL_Reg *lib = lualibs;
  for (; lib->func; lib++) {
    lua_pushcfunction(L, lib->func);
    lua_pushstring(L, lib->name);
    lua_call(L, 1, 0);
  }
}
luaopen_base()
LUAMOD_API int luaopen_base (lua_State * L)
Definition at line 648 of file lua-5.1.5/src/lbaselib.c.
{
  base_open(L);
  luaL_register(L, LUA_COLIBNAME, co_funcs);
  return 2;
}
luaopen_bit32()
LUAMOD_API int luaopen_bit32 (lua_State * L)
Definition at line 208 of file lua-5.2.4/src/lbitlib.c.
{
  luaL_newlib(L, bitlib);
  return 1;
}
References bitlib, luaL_error(), and luaL_newlib.
luaopen_coroutine()
LUAMOD_API int luaopen_coroutine (lua_State * L)
Definition at line 151 of file lua-5.2.4/src/lcorolib.c.
{
  luaL_newlib(L, co_funcs);
  return 1;
}
luaopen_debug()
LUAMOD_API int luaopen_debug (lua_State * L)
Definition at line 394 of file lua-5.1.5/src/ldblib.c.
{
  luaL_register(L, LUA_DBLIBNAME, dblib);
  return 1;
}
luaopen_io()
LUAMOD_API int luaopen_io (lua_State * L)
Definition at line 537 of file lua-5.1.5/src/liolib.c.
{
  createmeta(L);
  /* create (private) environment (with fields IO_INPUT, IO_OUTPUT, __close) */
  newfenv(L, io_fclose);
  lua_replace(L, LUA_ENVIRONINDEX);
  /* open library */
  luaL_register(L, LUA_IOLIBNAME, iolib);
  /* create (and set) default files */
  newfenv(L, io_noclose);  /* close function for default files */
  createstdfile(L, stdin, IO_INPUT, "stdin");
  createstdfile(L, stdout, IO_OUTPUT, "stdout");
  createstdfile(L, stderr, 0, "stderr");
  lua_pop(L, 1);  /* pop environment for default files */
  lua_getfield(L, -1, "popen");
  newfenv(L, io_pclose);  /* create environment for 'popen' */
  lua_setfenv(L, -2);  /* set fenv for 'popen' */
  lua_pop(L, 1);  /* pop 'popen' */
  return 1;
}
luaopen_math()
LUAMOD_API int luaopen_math (lua_State * L)
Definition at line 251 of file lua-5.1.5/src/lmathlib.c.
{
  luaL_register(L, LUA_MATHLIBNAME, mathlib);
  lua_pushnumber(L, PI);
  lua_setfield(L, -2, "pi");
  lua_pushnumber(L, HUGE_VAL);
  lua_setfield(L, -2, "huge");
#if defined(LUA_COMPAT_MOD)
  lua_getfield(L, -1, "fmod");
  lua_setfield(L, -2, "mod");
#endif
  return 1;
}
luaopen_os()
LUAMOD_API int luaopen_os (lua_State * L)
Definition at line 239 of file lua-5.1.5/src/loslib.c.
{
  luaL_register(L, LUA_OSLIBNAME, syslib);
  return 1;
}
luaopen_package()
LUAMOD_API int luaopen_package (lua_State * L)
Definition at line 627 of file lua-5.1.5/src/loadlib.c.
{
  int i;
  /* create new type _LOADLIB */
  luaL_newmetatable(L, "_LOADLIB");
  lua_pushcfunction(L, gctm);
  lua_setfield(L, -2, "__gc");
  /* create `package' table */
  luaL_register(L, LUA_LOADLIBNAME, pk_funcs);
#if defined(LUA_COMPAT_LOADLIB)
  lua_getfield(L, -1, "loadlib");
  lua_setfield(L, LUA_GLOBALSINDEX, "loadlib");
#endif
  lua_pushvalue(L, -1);
  lua_replace(L, LUA_ENVIRONINDEX);
  /* create `loaders' table */
  lua_createtable(L, sizeof(loaders)/sizeof(loaders[0]) - 1, 0);
  /* fill it with pre-defined loaders */
  for (i=0; loaders[i] != NULL; i++) {
    lua_pushcfunction(L, loaders[i]);
    lua_rawseti(L, -2, i+1);
  }
  lua_setfield(L, -2, "loaders");  /* put it in field `loaders' */
  setpath(L, "path", LUA_PATH, LUA_PATH_DEFAULT);  /* set field `path' */
  setpath(L, "cpath", LUA_CPATH, LUA_CPATH_DEFAULT); /* set field `cpath' */
  /* store config information */
  lua_pushliteral(L, LUA_DIRSEP "\n" LUA_PATHSEP "\n" LUA_PATH_MARK "\n"
                     LUA_EXECDIR "\n" LUA_IGMARK);
  lua_setfield(L, -2, "config");
  /* set field `loaded' */
  luaL_findtable(L, LUA_REGISTRYINDEX, "_LOADED", 2);
  lua_setfield(L, -2, "loaded");
  /* set field `preload' */
  lua_newtable(L);
  lua_setfield(L, -2, "preload");
  lua_pushvalue(L, LUA_GLOBALSINDEX);
  luaL_register(L, NULL, ll_funcs);  /* open lib into global table */
  lua_pop(L, 1);
  return 1;  /* return 'package' table */
}
luaopen_string()
LUAMOD_API int luaopen_string (lua_State * L)
Definition at line 862 of file lua-5.1.5/src/lstrlib.c.
{
  luaL_register(L, LUA_STRLIBNAME, strlib);
#if defined(LUA_COMPAT_GFIND)
  lua_getfield(L, -1, "gmatch");
  lua_setfield(L, -2, "gfind");
#endif
  createmetatable(L);
  return 1;
}
luaopen_table()
LUAMOD_API int luaopen_table (lua_State * L)
Definition at line 283 of file lua-5.1.5/src/ltablib.c.
{
  luaL_register(L, LUA_TABLIBNAME, tab_funcs);
  return 1;
}
luaopen_utf8()
LUAMOD_API int luaopen_utf8 (lua_State * L)
Definition at line 250 of file lua-5.3.6/src/lutf8lib.c.
{
  luaL_newlib(L, funcs);
  lua_pushlstring(L, UTF8PATT, sizeof(UTF8PATT)/sizeof(char) - 1);
  lua_setfield(L, -2, "charpattern");
  return 1;
}
References funcs, lua_pushlstring(), lua_setfield(), luaL_newlib, and UTF8PATT.