Github User Fetcher: lauxlib.c File Reference
lauxlib.c File Reference
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
Data Structures
struct LoadF
struct LoadS
Macros
#define lauxlib_c
#define LUA_LIB
#define LEVELS1 12 /* size of the first part of the stack */
#define LEVELS2 10 /* size of the second part of the stack */
#define inspectstat(stat, what) /* no op */
#define buffonstack(B) ((B)->b != (B)->initb)
#define freelist 0
Typedefs
typedef struct LoadF LoadF
typedef struct LoadS LoadS
Functions
static int findfield (lua_State *L, int objidx, int level)
static int pushglobalfuncname (lua_State *L, lua_Debug *ar)
static void pushfuncname (lua_State *L, lua_Debug *ar)
static int countlevels (lua_State *L)
LUALIB_API void luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level)
LUALIB_API int luaL_argerror (lua_State *L, int narg, const char *extramsg)
static int typeerror (lua_State *L, int narg, const char *tname)
static void tag_error (lua_State *L, int narg, int tag)
LUALIB_API void luaL_where (lua_State *L, int level)
LUALIB_API int luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int luaL_fileresult (lua_State *L, int stat, const char *fname)
LUALIB_API int luaL_execresult (lua_State *L, int stat)
LUALIB_API int luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void luaL_setmetatable (lua_State *L, const char *tname)
LUALIB_API void * luaL_testudata (lua_State *L, int ud, const char *tname)
LUALIB_API void * luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API int luaL_checkoption (lua_State *L, int narg, const char *def, const char *const lst[])
LUALIB_API void luaL_checkstack (lua_State *L, int space, const char *msg)
LUALIB_API void luaL_checktype (lua_State *L, int narg, int t)
LUALIB_API void luaL_checkany (lua_State *L, int narg)
LUALIB_API const char * luaL_checklstring (lua_State *L, int narg, size_t *len)
LUALIB_API const char * luaL_optlstring (lua_State *L, int narg, const char *def, size_t *len)
LUALIB_API lua_Number luaL_checknumber (lua_State *L, int narg)
LUALIB_API lua_Number luaL_optnumber (lua_State *L, int narg, lua_Number def)
LUALIB_API lua_Integer luaL_checkinteger (lua_State *L, int narg)
LUALIB_API lua_Unsigned luaL_checkunsigned (lua_State *L, int narg)
LUALIB_API lua_Integer luaL_optinteger (lua_State *L, int narg, lua_Integer def)
LUALIB_API lua_Unsigned luaL_optunsigned (lua_State *L, int narg, lua_Unsigned def)
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void luaL_pushresult (luaL_Buffer *B)
LUALIB_API void luaL_pushresultsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addvalue (luaL_Buffer *B)
LUALIB_API void luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API char * luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz)
LUALIB_API int luaL_ref (lua_State *L, int t)
LUALIB_API void luaL_unref (lua_State *L, int t, int ref)
static const char * getF (lua_State *L, void *ud, size_t *size)
static int errfile (lua_State *L, const char *what, int fnameindex)
static int skipBOM (LoadF *lf)
static int skipcomment (LoadF *lf, int *cp)
LUALIB_API int luaL_loadfilex (lua_State *L, const char *filename, const char *mode)
static const char * getS (lua_State *L, void *ud, size_t *size)
LUALIB_API int luaL_loadbufferx (lua_State *L, const char *buff, size_t size, const char *name, const char *mode)
LUALIB_API int luaL_loadstring (lua_State *L, const char *s)
LUALIB_API int luaL_getmetafield (lua_State *L, int obj, const char *event)
LUALIB_API int luaL_callmeta (lua_State *L, int obj, const char *event)
LUALIB_API int luaL_len (lua_State *L, int idx)
LUALIB_API const char * luaL_tolstring (lua_State *L, int idx, size_t *len)
LUALIB_API void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUALIB_API int luaL_getsubtable (lua_State *L, int idx, const char *fname)
LUALIB_API void luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb)
LUALIB_API const char * luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
static void * l_alloc (void *ud, void *ptr, size_t osize, size_t nsize)
static int panic (lua_State *L)
LUALIB_API lua_State * luaL_newstate (void)
LUALIB_API void luaL_checkversion_ (lua_State *L, lua_Number ver)
Macro Definition Documentation
buffonstack
#define buffonstack (B) ((B)->b != (B)->initb)
Definition at line 431 of file lua-5.2.4/src/lauxlib.c.
Referenced by luaL_addvalue(), luaL_prepbuffsize(), and luaL_pushresult().
freelist
#define freelist 0
Definition at line 519 of file lua-5.2.4/src/lauxlib.c.
Referenced by luaL_ref(), and luaL_unref().
inspectstat
#define inspectstat (stat, what) /* no op */
Definition at line 240 of file lua-5.2.4/src/lauxlib.c.
Referenced by luaL_execresult().
lauxlib_c
#define lauxlib_c
Definition at line 19 of file lua-5.2.4/src/lauxlib.c.
LEVELS1
#define LEVELS1 12 /* size of the first part of the stack */
Definition at line 34 of file lua-5.2.4/src/lauxlib.c.
Referenced by luaL_traceback().
LEVELS2
#define LEVELS2 10 /* size of the second part of the stack */
Definition at line 35 of file lua-5.2.4/src/lauxlib.c.
Referenced by luaL_traceback().
LUA_LIB
#define LUA_LIB
Definition at line 20 of file lua-5.2.4/src/lauxlib.c.
Typedef Documentation
LoadF
typedef struct LoadF LoadF
LoadS
typedef struct LoadS LoadS
Function Documentation
countlevels()
static int countlevels (lua_State * L) static
Definition at line 101 of file lua-5.2.4/src/lauxlib.c.
{
  lua_Debug ar;
  int li = 1, le = 1;
  /* find an upper bound */
  while (lua_getstack(L, le, &ar)) { li = le; le *= 2; }
  /* do a binary search */
  while (li < le) {
    int m = (li + le)/2;
    if (lua_getstack(L, m, &ar)) li = m + 1;
    else le = m;
  }
  return le - 1;
}
References lua_getstack().
Referenced by luaL_traceback().
errfile()
static int errfile (lua_State * L, const char * what, int fnameindex) static
Definition at line 587 of file lua-5.2.4/src/lauxlib.c.
{
  const char *serr = strerror(errno);
  const char *filename = lua_tostring(L, fnameindex) + 1;
  lua_pushfstring(L, "cannot %s %s: %s", what, filename, serr);
  lua_remove(L, fnameindex);
  return LUA_ERRFILE;
}
References LUA_ERRFILE, lua_pushfstring(), lua_remove, and lua_tostring.
Referenced by luaL_loadfilex().
findfield()
static int findfield (lua_State * L, int objidx, int level) static
Definition at line 43 of file lua-5.2.4/src/lauxlib.c.
{
  if (level == 0 || !lua_istable(L, -1))
    return 0;  /* not found */
  lua_pushnil(L);  /* start 'next' loop */
  while (lua_next(L, -2)) {  /* for each pair in table */
    if (lua_type(L, -2) == LUA_TSTRING) {  /* ignore non-string keys */
      if (lua_rawequal(L, objidx, -1)) {  /* found object? */
        lua_pop(L, 1);  /* remove value (but keep name) */
        return 1;
      }
      else if (findfield(L, objidx, level - 1)) {  /* try recursively */
        lua_remove(L, -2);  /* remove table (but keep name) */
        lua_pushliteral(L, ".");
        lua_insert(L, -2);  /* place '.' between the two names */
        lua_concat(L, 3);
        return 1;
      }
    }
    lua_pop(L, 1);  /* remove value */
  }
  return 0;  /* not found */
}
References findfield(), lua_concat(), lua_insert, lua_istable, lua_next(), lua_pop, lua_pushliteral, lua_pushnil(), lua_rawequal(), lua_remove, LUA_TSTRING, and lua_type().
Referenced by findfield(), and pushglobalfuncname().
getF()
static const char * getF (lua_State * L, void * ud, size_t * size) static
Definition at line 569 of file lua-5.2.4/src/lauxlib.c.
{
  LoadF *lf = (LoadF *)ud;
  (void)L;  /* not used */
  if (lf->n > 0) {  /* are there pre-read characters to be read? */
    *size = lf->n;  /* return them (chars already in buffer) */
    lf->n = 0;  /* no more pre-read characters */
  }
  else {  /* read a block from file */
    /* 'fread' can return > 0 *and* set the EOF flag. If next call to
       'getF' called 'fread', it might still wait for user input.
       The next check avoids this problem. */
    if (feof(lf->f)) return NULL;
    *size = fread(lf->buff, 1, sizeof(lf->buff), lf->f);  /* read block */
  }
  return lf->buff;
}
References LoadF::buff, LoadF::f, fread(), LoadF::n, and NULL.
Referenced by luaL_loadfilex().
getS()
static const char * getS (lua_State * L, void * ud, size_t * size) static
Definition at line 672 of file lua-5.2.4/src/lauxlib.c.
{
  LoadS *ls = (LoadS *)ud;
  (void)L;  /* not used */
  if (ls->size == 0) return NULL;
  *size = ls->size;
  ls->size = 0;
  return ls->s;
}
References NULL, LoadS::s, and LoadS::size.
Referenced by luaL_loadbufferx().
l_alloc()
static void * l_alloc (void * ud, void * ptr, size_t osize, size_t nsize) static
Definition at line 919 of file lua-5.2.4/src/lauxlib.c.
{
  (void)ud; (void)osize;  /* not used */
  if (nsize == 0) {
    free(ptr);
    return NULL;
  }
  else
    return realloc(ptr, nsize);
}
References free, NULL, and realloc.
Referenced by luaL_newstate().
luaL_addlstring()
LUALIB_API void luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 459 of file lua-5.2.4/src/lauxlib.c.
{
  char *b = luaL_prepbuffsize(B, l);
  memcpy(b, s, l * sizeof(char));
  luaL_addsize(B, l);
}
References luaL_addsize, luaL_prepbuffsize(), and s.
Referenced by luaL_addstring(), luaL_addvalue(), and luaL_gsub().
luaL_addstring()
LUALIB_API void luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 466 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_addlstring(B, s, strlen(s));
}
References luaL_addlstring(), and s.
Referenced by luaL_gsub().
luaL_addvalue()
LUALIB_API void luaL_addvalue (luaL_Buffer * B)
Definition at line 485 of file lua-5.2.4/src/lauxlib.c.
{
  lua_State *L = B->L;
  size_t l;
  const char *s = lua_tolstring(L, -1, &l);
  if (buffonstack(B))
    lua_insert(L, -2);  /* put value below buffer */
  luaL_addlstring(B, s, l);
  lua_remove(L, (buffonstack(B)) ? -2 : -1);  /* remove value */
}
References buffonstack, luaL_Buffer::L, lua_insert, lua_remove, lua_tolstring(), luaL_addlstring(), and s.
luaL_argerror()
LUALIB_API int luaL_argerror (lua_State * L, int narg, const char * extramsg)
Definition at line 153 of file lua-5.2.4/src/lauxlib.c.
{
  lua_Debug ar;
  if (!lua_getstack(L, 0, &ar))  /* no stack frame? */
    return luaL_error(L, "bad argument #%d (%s)", narg, extramsg);
  lua_getinfo(L, "n", &ar);
  if (strcmp(ar.namewhat, "method") == 0) {
    narg--;  /* do not count `self' */
    if (narg == 0)  /* error is in the self argument itself? */
      return luaL_error(L, "calling " LUA_QS " on bad self (%s)",
                           ar.name, extramsg);
  }
  if (ar.name == NULL)
    ar.name = (pushglobalfuncname(L, &ar)) ? lua_tostring(L, -1) : "?";
  return luaL_error(L, "bad argument #%d to " LUA_QS " (%s)",
                        narg, ar.name, extramsg);
}
References lua_getinfo(), lua_getstack(), LUA_QS, lua_tostring, luaL_error(), lua_Debug::name, lua_Debug::namewhat, NULL, and pushglobalfuncname().
Referenced by luaL_checkany(), luaL_checkoption(), and typeerror().
luaL_buffinit()
LUALIB_API void luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 496 of file lua-5.2.4/src/lauxlib.c.
{
  B->L = L;
  B->b = B->initb;
  B->n = 0;
  B->size = LUAL_BUFFERSIZE;
}
References luaL_Buffer::b, luaL_Buffer::initb, luaL_Buffer::L, LUAL_BUFFERSIZE, luaL_Buffer::n, and luaL_Buffer::size.
Referenced by luaL_buffinitsize(), and luaL_gsub().
luaL_buffinitsize()
LUALIB_API char * luaL_buffinitsize (lua_State * L, luaL_Buffer * B, size_t sz)
Definition at line 504 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_buffinit(L, B);
  return luaL_prepbuffsize(B, sz);
}
References luaL_buffinit(), and luaL_prepbuffsize().
Referenced by str_char(), str_char(), str_char(), str_lower(), str_lower(), str_lower(), str_rep(), str_rep(), str_rep(), str_reverse(), str_reverse(), str_reverse(), str_upper(), str_upper(), and str_upper().
luaL_callmeta()
LUALIB_API int luaL_callmeta (lua_State * L, int obj, const char * event)
Definition at line 715 of file lua-5.2.4/src/lauxlib.c.
{
  obj = lua_absindex(L, obj);
  if (!luaL_getmetafield(L, obj, event))  /* no metafield? */
    return 0;
  lua_pushvalue(L, obj);
  lua_call(L, 1, 1);
  return 1;
}
References lua_absindex(), lua_call, lua_pushvalue(), and luaL_getmetafield().
Referenced by luaL_tolstring().
luaL_checkany()
LUALIB_API void luaL_checkany (lua_State * L, int narg)
Definition at line 351 of file lua-5.2.4/src/lauxlib.c.
{
  if (lua_type(L, narg) == LUA_TNONE)
    luaL_argerror(L, narg, "value expected");
}
References LUA_TNONE, lua_type(), and luaL_argerror().
luaL_checkinteger()
LUALIB_API lua_Integer luaL_checkinteger (lua_State * L, int narg)
Definition at line 389 of file lua-5.2.4/src/lauxlib.c.
{
  int isnum;
  lua_Integer d = lua_tointegerx(L, narg, &isnum);
  if (!isnum)
    tag_error(L, narg, LUA_TNUMBER);
  return d;
}
References LUA_TNUMBER, lua_tointegerx(), and tag_error().
Referenced by luaL_optinteger().
luaL_checklstring()
LUALIB_API const char * luaL_checklstring (lua_State * L, int narg, size_t * len)
Definition at line 357 of file lua-5.2.4/src/lauxlib.c.
{
  const char *s = lua_tolstring(L, narg, len);
  if (!s) tag_error(L, narg, LUA_TSTRING);
  return s;
}
References lua_tolstring(), LUA_TSTRING, s, and tag_error().
Referenced by luaL_optlstring().
luaL_checknumber()
LUALIB_API lua_Number luaL_checknumber (lua_State * L, int narg)
Definition at line 375 of file lua-5.2.4/src/lauxlib.c.
{
  int isnum;
  lua_Number d = lua_tonumberx(L, narg, &isnum);
  if (!isnum)
    tag_error(L, narg, LUA_TNUMBER);
  return d;
}
References LUA_TNUMBER, lua_tonumberx(), and tag_error().
Referenced by luaL_optnumber().
luaL_checkoption()
LUALIB_API int luaL_checkoption (lua_State * L, int narg, const char * def, const char *const lst[])
Definition at line 320 of file lua-5.2.4/src/lauxlib.c.
{
  const char *name = (def) ? luaL_optstring(L, narg, def) :
                             luaL_checkstring(L, narg);
  int i;
  for (i=0; lst[i]; i++)
    if (strcmp(lst[i], name) == 0)
      return i;
  return luaL_argerror(L, narg,
                       lua_pushfstring(L, "invalid option " LUA_QS, name));
}
References lua_pushfstring(), LUA_QS, luaL_argerror(), luaL_checkstring, luaL_optstring, and name.
luaL_checkstack()
LUALIB_API void luaL_checkstack (lua_State * L, int space, const char * msg)
Definition at line 333 of file lua-5.2.4/src/lauxlib.c.
{
  /* keep some extra space to run error routines, if needed */
  const int extra = LUA_MINSTACK;
  if (!lua_checkstack(L, space + extra)) {
    if (msg)
      luaL_error(L, "stack overflow (%s)", msg);
    else
      luaL_error(L, "stack overflow");
  }
}
References lua_checkstack(), LUA_MINSTACK, and luaL_error().
Referenced by luaL_setfuncs().
luaL_checktype()
LUALIB_API void luaL_checktype (lua_State * L, int narg, int t)
Definition at line 345 of file lua-5.2.4/src/lauxlib.c.
{
  if (lua_type(L, narg) != t)
    tag_error(L, narg, t);
}
References lua_type(), and tag_error().
luaL_checkudata()
LUALIB_API void * luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 305 of file lua-5.2.4/src/lauxlib.c.
{
  void *p = luaL_testudata(L, ud, tname);
  if (p == NULL) typeerror(L, ud, tname);
  return p;
}
References luaL_testudata(), NULL, and typeerror().
luaL_checkunsigned()
LUALIB_API lua_Unsigned luaL_checkunsigned (lua_State * L, int narg)
Definition at line 398 of file lua-5.2.4/src/lauxlib.c.
{
  int isnum;
  lua_Unsigned d = lua_tounsignedx(L, narg, &isnum);
  if (!isnum)
    tag_error(L, narg, LUA_TNUMBER);
  return d;
}
References LUA_TNUMBER, lua_tounsignedx(), and tag_error().
Referenced by andaux(), b_arshift(), b_extract(), b_lshift(), b_or(), b_replace(), b_rot(), b_rshift(), b_xor(), luaL_optunsigned(), and math_randomseed().
luaL_checkversion_()
LUALIB_API void luaL_checkversion_ (lua_State * L, lua_Number ver)
Definition at line 944 of file lua-5.2.4/src/lauxlib.c.
{
  const lua_Number *v = lua_version(L);
  if (v != lua_version(NULL))
    luaL_error(L, "multiple Lua VMs detected");
  else if (*v != ver)
    luaL_error(L, "version mismatch: app. needs %f, Lua core provides %f",
                  ver, *v);
  /* check conversions number -> integer types */
  lua_pushnumber(L, -(lua_Number)0x1234);
  if (lua_tointeger(L, -1) != -0x1234 ||
      lua_tounsigned(L, -1) != (lua_Unsigned)-0x1234)
    luaL_error(L, "bad conversion number->int;"
                  " must recompile Lua with proper settings");
  lua_pop(L, 1);
}
References lua_pop, lua_pushnumber(), lua_tointeger, lua_tounsigned, lua_version(), luaL_error(), and NULL.
luaL_error()
LUALIB_API int luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 196 of file lua-5.2.4/src/lauxlib.c.
{
  va_list argp;
  va_start(argp, fmt);
  luaL_where(L, 1);
  lua_pushvfstring(L, fmt, argp);
  va_end(argp);
  lua_concat(L, 2);
  return lua_error(L);
}
References lua_concat(), lua_error(), lua_pushvfstring(), and luaL_where().
Referenced by luaL_argerror(), luaL_checkstack(), luaL_checkversion_(), luaL_len(), and luaL_prepbuffsize().
luaL_execresult()
LUALIB_API int luaL_execresult (lua_State * L, int stat)
Definition at line 247 of file lua-5.2.4/src/lauxlib.c.
{
  const char *what = "exit";  /* type of termination */
  if (stat == -1)  /* error? */
    return luaL_fileresult(L, 0, NULL);
  else {
    inspectstat(stat, what);  /* interpret result */
    if (*what == 'e' && stat == 0)  /* successful termination? */
      lua_pushboolean(L, 1);
    else
      lua_pushnil(L);
    lua_pushstring(L, what);
    lua_pushinteger(L, stat);
    return 3;  /* return true/nil,what,code */
  }
}
References inspectstat, lua_pushboolean(), lua_pushinteger(), lua_pushnil(), lua_pushstring(), luaL_fileresult(), and NULL.
Referenced by io_pclose(), io_pclose(), io_pclose(), os_execute(), os_execute(), and os_execute().
luaL_fileresult()
LUALIB_API int luaL_fileresult (lua_State * L, int stat, const char * fname)
Definition at line 207 of file lua-5.2.4/src/lauxlib.c.
{
  int en = errno;  /* calls to Lua API may change this value */
  if (stat) {
    lua_pushboolean(L, 1);
    return 1;
  }
  else {
    lua_pushnil(L);
    if (fname)
      lua_pushfstring(L, "%s: %s", fname, strerror(en));
    else
      lua_pushstring(L, strerror(en));
    lua_pushinteger(L, en);
    return 3;
  }
}
References lua_pushboolean(), lua_pushfstring(), lua_pushinteger(), lua_pushnil(), and lua_pushstring().
Referenced by f_flush(), f_flush(), f_flush(), f_seek(), f_seek(), f_seek(), f_setvbuf(), f_setvbuf(), f_setvbuf(), g_read(), g_read(), g_read(), g_write(), g_write(), g_write(), io_fclose(), io_fclose(), io_fclose(), io_flush(), io_flush(), io_flush(), io_open(), io_open(), io_open(), io_popen(), io_popen(), io_popen(), io_tmpfile(), io_tmpfile(), io_tmpfile(), luaL_execresult(), os_remove(), os_remove(), os_remove(), os_rename(), os_rename(), and os_rename().
luaL_getmetafield()
LUALIB_API int luaL_getmetafield (lua_State * L, int obj, const char * event)
Definition at line 699 of file lua-5.2.4/src/lauxlib.c.
{
  if (!lua_getmetatable(L, obj))  /* no metatable? */
    return 0;
  lua_pushstring(L, event);
  lua_rawget(L, -2);
  if (lua_isnil(L, -1)) {
    lua_pop(L, 2);  /* remove metatable and metafield */
    return 0;
  }
  else {
    lua_remove(L, -2);  /* remove only metatable */
    return 1;
  }
}
References lua_getmetatable(), lua_isnil, lua_pop, lua_pushstring(), lua_rawget(), and lua_remove.
Referenced by luaL_callmeta().
luaL_getsubtable()
LUALIB_API int luaL_getsubtable (lua_State * L, int idx, const char * fname)
Definition at line 866 of file lua-5.2.4/src/lauxlib.c.
{
  lua_getfield(L, idx, fname);
  if (lua_istable(L, -1)) return 1;  /* table already there */
  else {
    lua_pop(L, 1);  /* remove previous result */
    idx = lua_absindex(L, idx);
    lua_newtable(L);
    lua_pushvalue(L, -1);  /* copy to be left at top */
    lua_setfield(L, idx, fname);  /* assign new table to field */
    return 0;  /* false, because did not find table there */
  }
}
References lua_absindex(), lua_getfield(), lua_istable, lua_newtable, lua_pop, lua_pushvalue(), and lua_setfield().
Referenced by createclibstable(), db_sethook(), luaL_openlibs(), luaL_requiref(), and luaopen_package().
luaL_gsub()
LUALIB_API const char * luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 902 of file lua-5.2.4/src/lauxlib.c.
{
  const char *wild;
  size_t l = strlen(p);
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  while ((wild = strstr(s, p)) != NULL) {
    luaL_addlstring(&b, s, wild - s);  /* push prefix */
    luaL_addstring(&b, r);  /* push replacement in place of pattern */
    s = wild + l;  /* continue after `p' */
  }
  luaL_addstring(&b, s);  /* push last suffix */
  luaL_pushresult(&b);
  return lua_tostring(L, -1);
}
References lua_tostring, luaL_addlstring(), luaL_addstring(), luaL_buffinit(), luaL_pushresult(), NULL, and s.
luaL_len()
LUALIB_API int luaL_len (lua_State * L, int idx)
Definition at line 725 of file lua-5.2.4/src/lauxlib.c.
{
  int l;
  int isnum;
  lua_len(L, idx);
  l = (int)lua_tointegerx(L, -1, &isnum);
  if (!isnum)
    luaL_error(L, "object length is not a number");
  lua_pop(L, 1);  /* remove object */
  return l;
}
References lua_len(), lua_pop, lua_tointegerx(), and luaL_error().
Referenced by addtoclib(), addtoclib(), gctm(), gctm(), gctm(), ll_addtoclib(), pushargs(), pushargs(), tconcat(), tunpack(), unpack(), and unpack().
luaL_loadbufferx()
LUALIB_API int luaL_loadbufferx (lua_State * L, const char * buff, size_t size, const char * name, const char * mode)
Definition at line 682 of file lua-5.2.4/src/lauxlib.c.
{
  LoadS ls;
  ls.s = buff;
  ls.size = size;
  return lua_load(L, getS, &ls, name, mode);
}
References getS(), lua_load(), name, LoadS::s, and LoadS::size.
Referenced by luaB_load(), luaB_load(), and luaB_load().
luaL_loadfilex()
LUALIB_API int luaL_loadfilex (lua_State * L, const char * filename, const char * mode)
Definition at line 630 of file lua-5.2.4/src/lauxlib.c.
{
  LoadF lf;
  int status, readstatus;
  int c;
  int fnameindex = lua_gettop(L) + 1;  /* index of filename on the stack */
  if (filename == NULL) {
    lua_pushliteral(L, "=stdin");
    lf.f = stdin;
  }
  else {
    lua_pushfstring(L, "@%s", filename);
    lf.f = fopen(filename, "r");
    if (lf.f == NULL) return errfile(L, "open", fnameindex);
  }
  if (skipcomment(&lf, &c))  /* read initial portion */
    lf.buff[lf.n++] = '\n';  /* add line to correct line numbers */
  if (c == LUA_SIGNATURE[0] && filename) {  /* binary file? */
    lf.f = freopen(filename, "rb", lf.f);  /* reopen in binary mode */
    if (lf.f == NULL) return errfile(L, "reopen", fnameindex);
    skipcomment(&lf, &c);  /* re-read initial portion */
  }
  if (c != EOF)
    lf.buff[lf.n++] = c;  /* 'c' is the first character of the stream */
  status = lua_load(L, getF, &lf, lua_tostring(L, -1), mode);
  readstatus = ferror(lf.f);
  if (filename) fclose(lf.f);  /* close file (even in case of errors) */
  if (readstatus) {
    lua_settop(L, fnameindex);  /* ignore results from `lua_load' */
    return errfile(L, "read", fnameindex);
  }
  lua_remove(L, fnameindex);
  return status;
}
References LoadF::buff, errfile(), LoadF::f, getF(), lua_gettop(), lua_load(), lua_pushfstring(), lua_pushliteral, lua_remove, lua_settop(), LUA_SIGNATURE, lua_tostring, LoadF::n, NULL, and skipcomment().
Referenced by luaB_loadfile(), luaB_loadfile(), and luaB_loadfile().
luaL_loadstring()
LUALIB_API int luaL_loadstring (lua_State * L, const char * s)
Definition at line 691 of file lua-5.2.4/src/lauxlib.c.
{
  return luaL_loadbuffer(L, s, strlen(s), s);
}
References luaL_loadbuffer, and s.
luaL_newmetatable()
LUALIB_API int luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 272 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_getmetatable(L, tname);  /* try to get metatable */
  if (!lua_isnil(L, -1))  /* name already in use? */
    return 0;  /* leave previous value on top, but return 0 */
  lua_pop(L, 1);
  lua_newtable(L);  /* create metatable */
  lua_pushvalue(L, -1);
  lua_setfield(L, LUA_REGISTRYINDEX, tname);  /* registry.name = metatable */
  return 1;
}
References lua_isnil, lua_newtable, lua_pop, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), and luaL_getmetatable.
luaL_newstate()
LUALIB_API lua_State * luaL_newstate (void)
Definition at line 937 of file lua-5.2.4/src/lauxlib.c.
{
  lua_State *L = lua_newstate(l_alloc, NULL);
  if (L) lua_atpanic(L, &panic);
  return L;
}
References l_alloc(), lua_atpanic(), lua_newstate(), NULL, and panic().
luaL_optinteger()
LUALIB_API lua_Integer luaL_optinteger (lua_State * L, int narg, lua_Integer def)
Definition at line 407 of file lua-5.2.4/src/lauxlib.c.
{
  return luaL_opt(L, luaL_checkinteger, narg, def);
}
References luaL_checkinteger(), and luaL_opt.
luaL_optlstring()
LUALIB_API const char * luaL_optlstring (lua_State * L, int narg, const char * def, size_t * len)
Definition at line 364 of file lua-5.2.4/src/lauxlib.c.
{
  if (lua_isnoneornil(L, narg)) {
    if (len)
      *len = (def ? strlen(def) : 0);
    return def;
  }
  else return luaL_checklstring(L, narg, len);
}
References lua_isnoneornil, and luaL_checklstring().
luaL_optnumber()
LUALIB_API lua_Number luaL_optnumber (lua_State * L, int narg, lua_Number def)
Definition at line 384 of file lua-5.2.4/src/lauxlib.c.
{
  return luaL_opt(L, luaL_checknumber, narg, def);
}
References luaL_checknumber(), and luaL_opt.
luaL_optunsigned()
LUALIB_API lua_Unsigned luaL_optunsigned (lua_State * L, int narg, lua_Unsigned def)
Definition at line 413 of file lua-5.2.4/src/lauxlib.c.
{
  return luaL_opt(L, luaL_checkunsigned, narg, def);
}
References luaL_checkunsigned(), and luaL_opt.
luaL_prepbuffsize()
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer * B, size_t sz)
Definition at line 437 of file lua-5.2.4/src/lauxlib.c.
{
  lua_State *L = B->L;
  if (B->size - B->n < sz) {  /* not enough space? */
    char *newbuff;
    size_t newsize = B->size * 2;  /* double buffer size */
    if (newsize - B->n < sz)  /* not big enough? */
      newsize = B->n + sz;
    if (newsize < B->n || newsize - B->n < sz)
      luaL_error(L, "buffer too large");
    /* create larger buffer */
    newbuff = (char *)lua_newuserdata(L, newsize * sizeof(char));
    /* move content to new buffer */
    memcpy(newbuff, B->b, B->n * sizeof(char));
    if (buffonstack(B))
      lua_remove(L, -2);  /* remove old buffer */
    B->b = newbuff;
    B->size = newsize;
  }
  return &B->b[B->n];
}
References luaL_Buffer::b, buffonstack, luaL_Buffer::L, lua_newuserdata, lua_remove, luaL_error(), luaL_Buffer::n, and luaL_Buffer::size.
Referenced by addliteral(), addliteral(), luaL_addlstring(), luaL_buffinitsize(), os_date(), os_date(), packint(), packint(), read_all(), read_chars(), read_chars(), read_chars(), str_format(), str_format(), str_format(), str_pack(), and str_pack().
luaL_pushresult()
LUALIB_API void luaL_pushresult (luaL_Buffer * B)
Definition at line 471 of file lua-5.2.4/src/lauxlib.c.
{
  lua_State *L = B->L;
  lua_pushlstring(L, B->b, B->n);
  if (buffonstack(B))
    lua_remove(L, -2);  /* remove old buffer */
}
References luaL_Buffer::b, buffonstack, luaL_Buffer::L, lua_pushlstring(), lua_remove, and luaL_Buffer::n.
Referenced by luaL_gsub(), and luaL_pushresultsize().
luaL_pushresultsize()
LUALIB_API void luaL_pushresultsize (luaL_Buffer * B, size_t sz)
Definition at line 479 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_addsize(B, sz);
  luaL_pushresult(B);
}
References luaL_addsize, and luaL_pushresult().
Referenced by str_char(), str_char(), str_char(), str_lower(), str_lower(), str_lower(), str_rep(), str_rep(), str_rep(), str_reverse(), str_reverse(), str_reverse(), str_upper(), str_upper(), and str_upper().
luaL_ref()
LUALIB_API int luaL_ref (lua_State * L, int t)
Definition at line 522 of file lua-5.2.4/src/lauxlib.c.
{
  int ref;
  if (lua_isnil(L, -1)) {
    lua_pop(L, 1);  /* remove from stack */
    return LUA_REFNIL;  /* `nil' has a unique fixed reference */
  }
  t = lua_absindex(L, t);
  lua_rawgeti(L, t, freelist);  /* get first free element */
  ref = (int)lua_tointeger(L, -1);  /* ref = t[freelist] */
  lua_pop(L, 1);  /* remove it from stack */
  if (ref != 0) {  /* any free element? */
    lua_rawgeti(L, t, ref);  /* remove it from list */
    lua_rawseti(L, t, freelist);  /* (t[freelist] = t[ref]) */
  }
  else  /* no free elements */
    ref = (int)lua_rawlen(L, t) + 1;  /* get a new reference */
  lua_rawseti(L, t, ref);
  return ref;
}
References freelist, lua_absindex(), lua_isnil, lua_pop, lua_rawgeti(), lua_rawlen, lua_rawseti(), LUA_REFNIL, and lua_tointeger.
luaL_requiref()
LUALIB_API void luaL_requiref (lua_State * L, const char * modname, lua_CFunction openf, int glb)
Definition at line 886 of file lua-5.2.4/src/lauxlib.c.
{
  lua_pushcfunction(L, openf);
  lua_pushstring(L, modname);  /* argument to open function */
  lua_call(L, 1, 1);  /* open module */
  luaL_getsubtable(L, LUA_REGISTRYINDEX, "_LOADED");
  lua_pushvalue(L, -2);  /* make copy of module (call result) */
  lua_setfield(L, -2, modname);  /* _LOADED[modname] = module */
  lua_pop(L, 1);  /* remove _LOADED table */
  if (glb) {
    lua_pushvalue(L, -1);  /* copy of 'mod' */
    lua_setglobal(L, modname);  /* _G[modname] = module */
  }
}
References lua_call, lua_pop, lua_pushcfunction, lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_setglobal, and luaL_getsubtable().
Referenced by luaL_openlibs(), and luaopen_lsqlite3().
luaL_setfuncs()
LUALIB_API void luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 848 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_checkversion(L);
  luaL_checkstack(L, nup, "too many upvalues");
  for (; l->name != NULL; l++) {  /* fill the table with given functions */
    int i;
    for (i = 0; i < nup; i++)  /* copy upvalues to the top */
      lua_pushvalue(L, -nup);
    lua_pushcclosure(L, l->func, nup);  /* closure with those upvalues */
    lua_setfield(L, -(nup + 2), l->name);
  }
  lua_pop(L, nup);  /* remove upvalues */
}
References luaL_Reg::func, lua_pop, lua_pushcclosure(), lua_pushvalue(), lua_setfield(), luaL_checkstack(), luaL_checkversion, luaL_Reg::name, and NULL.
Referenced by createmeta(), createmeta(), createmeta(), createmetatable(), luaopen_base(), luaopen_package(), luaopen_sqlitelib(), and setrandfunc().
luaL_setmetatable()
LUALIB_API void luaL_setmetatable (lua_State * L, const char * tname)
Definition at line 284 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_getmetatable(L, tname);
  lua_setmetatable(L, -2);
}
References lua_setmetatable(), and luaL_getmetatable.
Referenced by newprefile(), newprefile(), and newprefile().
luaL_testudata()
LUALIB_API void * luaL_testudata (lua_State * L, int ud, const char * tname)
Definition at line 290 of file lua-5.2.4/src/lauxlib.c.
{
  void *p = lua_touserdata(L, ud);
  if (p != NULL) {  /* value is a userdata? */
    if (lua_getmetatable(L, ud)) {  /* does it have a metatable? */
      luaL_getmetatable(L, tname);  /* get correct metatable */
      if (!lua_rawequal(L, -1, -2))  /* not the same? */
        p = NULL;  /* value is a userdata with wrong metatable */
      lua_pop(L, 2);  /* remove both metatables */
      return p;
    }
  }
  return NULL;  /* value is not a userdata with a metatable */
}
References lua_getmetatable(), lua_pop, lua_rawequal(), lua_touserdata(), luaL_getmetatable, and NULL.
Referenced by io_type(), io_type(), io_type(), and luaL_checkudata().
luaL_tolstring()
LUALIB_API const char * luaL_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 737 of file lua-5.2.4/src/lauxlib.c.
{
  if (!luaL_callmeta(L, idx, "__tostring")) {  /* no metafield? */
    switch (lua_type(L, idx)) {
      case LUA_TNUMBER:
      case LUA_TSTRING:
        lua_pushvalue(L, idx);
        break;
      case LUA_TBOOLEAN:
        lua_pushstring(L, (lua_toboolean(L, idx) ? "true" : "false"));
        break;
      case LUA_TNIL:
        lua_pushliteral(L, "nil");
        break;
      default:
        lua_pushfstring(L, "%s: %p", luaL_typename(L, idx),
                                            lua_topointer(L, idx));
        break;
    }
  }
  return lua_tolstring(L, -1, len);
}
References lua_pushfstring(), lua_pushliteral, lua_pushstring(), lua_pushvalue(), LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, lua_toboolean(), lua_tolstring(), lua_topointer(), LUA_TSTRING, lua_type(), luaL_callmeta(), and luaL_typename.
Referenced by add_s(), addliteral(), addliteral(), db_debug(), get_prompt(), luaB_print(), luaB_tostring(), luaB_tostring(), luaB_tostring(), str_format(), str_format(), and str_format().
luaL_traceback()
LUALIB_API void luaL_traceback (lua_State * L, lua_State * L1, const char * msg, int level)
Definition at line 116 of file lua-5.2.4/src/lauxlib.c.
{
  lua_Debug ar;
  int top = lua_gettop(L);
  int numlevels = countlevels(L1);
  int mark = (numlevels > LEVELS1 + LEVELS2) ? LEVELS1 : 0;
  if (msg) lua_pushfstring(L, "%s\n", msg);
  lua_pushliteral(L, "stack traceback:");
  while (lua_getstack(L1, level++, &ar)) {
    if (level == mark) {  /* too many levels? */
      lua_pushliteral(L, "\n\t...");  /* add a '...' */
      level = numlevels - LEVELS2;  /* and skip to last ones */
    }
    else {
      lua_getinfo(L1, "Slnt", &ar);
      lua_pushfstring(L, "\n\t%s:", ar.short_src);
      if (ar.currentline > 0)
        lua_pushfstring(L, "%d:", ar.currentline);
      lua_pushliteral(L, " in ");
      pushfuncname(L, &ar);
      if (ar.istailcall)
        lua_pushliteral(L, "\n\t(...tail calls...)");
      lua_concat(L, lua_gettop(L) - top);
    }
  }
  lua_concat(L, lua_gettop(L) - top);
}
References countlevels(), lua_Debug::currentline, lua_Debug::istailcall, LEVELS1, LEVELS2, lua_concat(), lua_getinfo(), lua_getstack(), lua_gettop(), lua_pushfstring(), lua_pushliteral, pushfuncname(), and lua_Debug::short_src.
Referenced by db_traceback(), db_traceback(), db_traceback(), msghandler(), msghandler(), and traceback().
luaL_unref()
LUALIB_API void luaL_unref (lua_State * L, int t, int ref)
Definition at line 543 of file lua-5.2.4/src/lauxlib.c.
{
  if (ref >= 0) {
    t = lua_absindex(L, t);
    lua_rawgeti(L, t, freelist);
    lua_rawseti(L, t, ref);  /* t[ref] = t[freelist] */
    lua_pushinteger(L, ref);
    lua_rawseti(L, t, freelist);  /* t[freelist] = ref */
  }
}
References freelist, lua_absindex(), lua_pushinteger(), lua_rawgeti(), and lua_rawseti().
luaL_where()
LUALIB_API void luaL_where (lua_State * L, int level)
Definition at line 183 of file lua-5.2.4/src/lauxlib.c.
{
  lua_Debug ar;
  if (lua_getstack(L, level, &ar)) {  /* check function at level */
    lua_getinfo(L, "Sl", &ar);  /* get info about it */
    if (ar.currentline > 0) {  /* is there info? */
      lua_pushfstring(L, "%s:%d: ", ar.short_src, ar.currentline);
      return;
    }
  }
  lua_pushliteral(L, "");  /* else, no information available... */
}
References lua_Debug::currentline, lua_getinfo(), lua_getstack(), lua_pushfstring(), lua_pushliteral, and lua_Debug::short_src.
Referenced by luaL_error().
panic()
static int panic (lua_State * L) static
Definition at line 930 of file lua-5.2.4/src/lauxlib.c.
{
  luai_writestringerror("PANIC: unprotected error in call to Lua API (%s)\n",
                   lua_tostring(L, -1));
  return 0;  /* return to Lua to abort */
}
References lua_tostring, and luai_writestringerror.
Referenced by luaL_newstate().
pushfuncname()
static void pushfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 83 of file lua-5.2.4/src/lauxlib.c.
{
  if (*ar->namewhat != '\0')  /* is there a name? */
    lua_pushfstring(L, "function " LUA_QS, ar->name);
  else if (*ar->what == 'm')  /* main? */
      lua_pushliteral(L, "main chunk");
  else if (*ar->what == 'C') {
    if (pushglobalfuncname(L, ar)) {
      lua_pushfstring(L, "function " LUA_QS, lua_tostring(L, -1));
      lua_remove(L, -2);  /* remove name */
    }
    else
      lua_pushliteral(L, "?");
  }
  else
    lua_pushfstring(L, "function <%s:%d>", ar->short_src, ar->linedefined);
}
References lua_Debug::linedefined, lua_pushfstring(), lua_pushliteral, LUA_QS, lua_remove, lua_tostring, lua_Debug::name, lua_Debug::namewhat, pushglobalfuncname(), lua_Debug::short_src, and lua_Debug::what.
Referenced by luaL_traceback().
pushglobalfuncname()
static int pushglobalfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 67 of file lua-5.2.4/src/lauxlib.c.
{
  int top = lua_gettop(L);
  lua_getinfo(L, "f", ar);  /* push function */
  lua_pushglobaltable(L);
  if (findfield(L, top + 1, 2)) {
    lua_copy(L, -1, top + 1);  /* move name to proper place */
    lua_pop(L, 2);  /* remove pushed values */
    return 1;
  }
  else {
    lua_settop(L, top);  /* remove function and global table */
    return 0;
  }
}
References findfield(), lua_copy(), lua_getinfo(), lua_gettop(), lua_pop, lua_pushglobaltable, and lua_settop().
Referenced by luaL_argerror(), and pushfuncname().
skipBOM()
static int skipBOM (LoadF * lf) static
Definition at line 596 of file lua-5.2.4/src/lauxlib.c.
{
  const char *p = "\xEF\xBB\xBF";  /* Utf8 BOM mark */
  int c;
  lf->n = 0;
  do {
    c = getc(lf->f);
    if (c == EOF || c != *(const unsigned char *)p++) return c;
    lf->buff[lf->n++] = c;  /* to be read by the parser */
  } while (*p != '\0');
  lf->n = 0;  /* prefix matched; discard it */
  return getc(lf->f);  /* return next character */
}
References LoadF::buff, LoadF::f, and LoadF::n.
Referenced by skipcomment().
skipcomment()
static int skipcomment (LoadF * lf, int * cp) static
Definition at line 617 of file lua-5.2.4/src/lauxlib.c.
{
  int c = *cp = skipBOM(lf);
  if (c == '#') {  /* first line is a comment (Unix exec. file)? */
    do {  /* skip first line */
      c = getc(lf->f);
    } while (c != EOF && c != '\n') ;
    *cp = getc(lf->f);  /* skip end-of-line, if present */
    return 1;  /* there was a comment */
  }
  else return 0;  /* no comment */
}
References LoadF::f, and skipBOM().
Referenced by luaL_loadfilex().
tag_error()
static void tag_error (lua_State * L, int narg, int tag) static
Definition at line 178 of file lua-5.2.4/src/lauxlib.c.
{
  typeerror(L, narg, lua_typename(L, tag));
}
References lua_typename(), and typeerror().
Referenced by luaL_checkinteger(), luaL_checklstring(), luaL_checknumber(), luaL_checktype(), and luaL_checkunsigned().
typeerror()
static int typeerror (lua_State * L, int narg, const char * tname) static
Definition at line 171 of file lua-5.2.4/src/lauxlib.c.
{
  const char *msg = lua_pushfstring(L, "%s expected, got %s",
                                    tname, luaL_typename(L, narg));
  return luaL_argerror(L, narg, msg);
}
References lua_pushfstring(), luaL_argerror(), and luaL_typename.
Referenced by luaL_checkudata(), and tag_error().