Github User Fetcher: loslib.c File Reference
loslib.c File Reference
#include "lprefix.h"
#include <errno.h>
#include <locale.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define loslib_c
#define LUA_LIB
#define L_STRFTIMEC89 "aAbBcdHIjmMpSUwWxXyYZ%"
#define L_STRFTIMEC99
#define L_STRFTIMEWIN
#define LUA_STRFTIMEOPTIONS L_STRFTIMEC99
#define l_timet lua_Integer
#define l_pushtime(L, t) lua_pushinteger(L,(lua_Integer)(t))
#define l_gettime(L, arg) luaL_checkinteger(L, arg)
#define l_gmtime(t, r) ((void)(r)->tm_sec, gmtime(t))
#define l_localtime(t, r) ((void)(r)->tm_sec, localtime(t))
#define LUA_TMPNAMBUFSIZE L_tmpnam
#define lua_tmpnam(b, e) { e = (tmpnam(b) == NULL); }
#define SIZETIMEFMT 250
Functions
static int os_execute (lua_State *L)
static int os_remove (lua_State *L)
static int os_rename (lua_State *L)
static int os_tmpname (lua_State *L)
static int os_getenv (lua_State *L)
static int os_clock (lua_State *L)
static void setfield (lua_State *L, const char *key, int value, int delta)
static void setboolfield (lua_State *L, const char *key, int value)
static void setallfields (lua_State *L, struct tm *stm)
static int getboolfield (lua_State *L, const char *key)
static int getfield (lua_State *L, const char *key, int d, int delta)
static const char * checkoption (lua_State *L, const char *conv, ptrdiff_t convlen, char *buff)
static time_t l_checktime (lua_State *L, int arg)
static int os_date (lua_State *L)
static int os_time (lua_State *L)
static int os_difftime (lua_State *L)
static int os_setlocale (lua_State *L)
static int os_exit (lua_State *L)
LUAMOD_API int luaopen_os (lua_State *L)
Variables
static const luaL_Reg syslib []
Macro Definition Documentation
l_gettime
#define l_gettime (L, arg) luaL_checkinteger(L, arg)
Definition at line 69 of file lua-5.4.3/src/loslib.c.
Referenced by l_checktime().
l_gmtime
#define l_gmtime (t, r) ((void)(r)->tm_sec, gmtime(t))
Definition at line 94 of file lua-5.4.3/src/loslib.c.
Referenced by os_date().
l_localtime
#define l_localtime (t, r) ((void)(r)->tm_sec, localtime(t))
Definition at line 95 of file lua-5.4.3/src/loslib.c.
Referenced by os_date().
l_pushtime
#define l_pushtime (L, t) lua_pushinteger(L,(lua_Integer)(t))
Definition at line 68 of file lua-5.4.3/src/loslib.c.
Referenced by os_time().
L_STRFTIMEC89
#define L_STRFTIMEC89 "aAbBcdHIjmMpSUwWxXyYZ%"
Definition at line 34 of file lua-5.4.3/src/loslib.c.
L_STRFTIMEC99
#define L_STRFTIMEC99
Value:
    "aAbBcCdDeFgGhHIjmMnprRStTuUVwWxXyYzZ%" \
    "||" "EcECExEXEyEY" "OdOeOHOIOmOMOSOuOUOVOwOWOy"  /* two-char options */
Definition at line 37 of file lua-5.4.3/src/loslib.c.
#define L_STRFTIMEC99 "aAbBcCdDeFgGhHIjmMnprRStTuUVwWxXyYzZ%" \
    "||" "EcECExEXEyEY" "OdOeOHOIOmOMOSOuOUOVOwOWOy"  /* two-char options */
L_STRFTIMEWIN
#define L_STRFTIMEWIN
Value:
    "aAbBcdHIjmMpSUwWxXyYzZ%" \
    "||" "#c#x#d#H#I#j#m#M#S#U#w#W#y#Y"  /* two-char options */
Definition at line 41 of file lua-5.4.3/src/loslib.c.
#define L_STRFTIMEWIN "aAbBcdHIjmMpSUwWxXyYzZ%" \
    "||" "#c#x#d#H#I#j#m#M#S#U#w#W#y#Y"  /* two-char options */
l_timet
#define l_timet lua_Integer
Definition at line 67 of file lua-5.4.3/src/loslib.c.
Referenced by l_checktime(), and os_time().
loslib_c
#define loslib_c
Definition at line 7 of file lua-5.4.3/src/loslib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.4.3/src/loslib.c.
LUA_STRFTIMEOPTIONS
#define LUA_STRFTIMEOPTIONS L_STRFTIMEC99
Definition at line 49 of file lua-5.4.3/src/loslib.c.
Referenced by checkoption().
lua_tmpnam
#define lua_tmpnam (b, e) { e = (tmpnam(b) == NULL); }
Definition at line 133 of file lua-5.4.3/src/loslib.c.
Referenced by os_tmpname().
LUA_TMPNAMBUFSIZE
#define LUA_TMPNAMBUFSIZE L_tmpnam
Definition at line 132 of file lua-5.4.3/src/loslib.c.
Referenced by os_tmpname().
SIZETIMEFMT
#define SIZETIMEFMT 250
Definition at line 301 of file lua-5.4.3/src/loslib.c.
Referenced by os_date().
Function Documentation
checkoption()
static const char * checkoption (lua_State * L, const char * conv, ptrdiff_t convlen, char * buff) static
Definition at line 274 of file lua-5.4.3/src/loslib.c.
{
  const char *option = LUA_STRFTIMEOPTIONS;
  int oplen = 1;  /* length of options being checked */
  for (; *option != '\0' && oplen <= convlen; option += oplen) {
    if (*option == '|')  /* next block? */
      oplen++;  /* will check options with next length (+1) */
    else if (memcmp(conv, option, oplen) == 0) {  /* match? */
      memcpy(buff, conv, oplen);  /* copy valid option to buffer */
      buff[oplen] = '\0';
      return conv + oplen;  /* return next item */
    }
  }
  luaL_argerror(L, 1,
    lua_pushfstring(L, "invalid conversion specifier '%%%s'", conv));
  return conv;  /* to avoid warnings */
}
References lua_pushfstring(), LUA_STRFTIMEOPTIONS, and luaL_argerror().
Referenced by os_date().
getboolfield()
static int getboolfield (lua_State * L, const char * key) static
Definition at line 243 of file lua-5.4.3/src/loslib.c.
{
  int res;
  res = (lua_getfield(L, -1, key) == LUA_TNIL) ? -1 : lua_toboolean(L, -1);
  lua_pop(L, 1);
  return res;
}
References lua_getfield(), lua_pop, LUA_TNIL, and lua_toboolean().
Referenced by os_time().
getfield()
static int getfield (lua_State * L, const char * key, int d, int delta) static
Definition at line 251 of file lua-5.4.3/src/loslib.c.
{
  int isnum;
  int t = lua_getfield(L, -1, key);  /* get field and its type */
  lua_Integer res = lua_tointegerx(L, -1, &isnum);
  if (!isnum) {  /* field is not an integer? */
    if (l_unlikely(t != LUA_TNIL))  /* some other value? */
      return luaL_error(L, "field '%s' is not an integer", key);
    else if (l_unlikely(d < 0))  /* absent field; no default? */
      return luaL_error(L, "field '%s' missing in date table", key);
    res = d;
  }
  else {
    /* unsigned avoids overflow when lua_Integer has 32 bits */
    if (!(res >= 0 ? (lua_Unsigned)res <= (lua_Unsigned)INT_MAX + delta
                   : (lua_Integer)INT_MIN + delta <= res))
      return luaL_error(L, "field '%s' is out-of-bound", key);
    res -= delta;
  }
  lua_pop(L, 1);
  return (int)res;
}
References lua_getfield(), lua_pop, LUA_TNIL, lua_tointegerx(), and luaL_error().
Referenced by os_time().
l_checktime()
static time_t l_checktime (lua_State * L, int arg) static
Definition at line 293 of file lua-5.4.3/src/loslib.c.
{
  l_timet t = l_gettime(L, arg);
  luaL_argcheck(L, (time_t)t == t, arg, "time out-of-bounds");
  return (time_t)t;
}
References arg, l_gettime, l_timet, and luaL_argcheck.
Referenced by os_date(), and os_difftime().
luaopen_os()
LUAMOD_API int luaopen_os (lua_State * L)
Definition at line 426 of file lua-5.4.3/src/loslib.c.
{
  luaL_newlib(L, syslib);
  return 1;
}
References luaL_newlib, and syslib.
os_clock()
static int os_clock (lua_State * L) static
Definition at line 186 of file lua-5.4.3/src/loslib.c.
{
  lua_pushnumber(L, ((lua_Number)clock())/(lua_Number)CLOCKS_PER_SEC);
  return 1;
}
References lua_pushnumber().
os_date()
static int os_date (lua_State * L) static
Definition at line 304 of file lua-5.4.3/src/loslib.c.
{
  size_t slen;
  const char *s = luaL_optlstring(L, 1, "%c", &slen);
  time_t t = luaL_opt(L, l_checktime, 2, time(NULL));
  const char *se = s + slen;  /* 's' end */
  struct tm tmr, *stm;
  if (*s == '!') {  /* UTC? */
    stm = l_gmtime(&t, &tmr);
    s++;  /* skip '!' */
  }
  else
    stm = l_localtime(&t, &tmr);
  if (stm == NULL)  /* invalid date? */
    return luaL_error(L,
                 "date result cannot be represented in this installation");
  if (strcmp(s, "*t") == 0) {
    lua_createtable(L, 0, 9);  /* 9 = number of fields */
    setallfields(L, stm);
  }
  else {
    char cc[4];  /* buffer for individual conversion specifiers */
    luaL_Buffer b;
    cc[0] = '%';
    luaL_buffinit(L, &b);
    while (s < se) {
      if (*s != '%')  /* not a conversion specifier? */
        luaL_addchar(&b, *s++);
      else {
        size_t reslen;
        char *buff = luaL_prepbuffsize(&b, SIZETIMEFMT);
        s++;  /* skip '%' */
        s = checkoption(L, s, se - s, cc + 1);  /* copy specifier to 'cc' */
        reslen = strftime(buff, SIZETIMEFMT, cc, stm);
        luaL_addsize(&b, reslen);
      }
    }
    luaL_pushresult(&b);
  }
  return 1;
}
References checkoption(), l_checktime(), l_gmtime, l_localtime, lua_createtable(), luaL_addchar, luaL_addsize, luaL_buffinit(), luaL_error(), luaL_opt, luaL_optlstring(), luaL_prepbuffsize(), luaL_pushresult(), NULL, s, setallfields(), and SIZETIMEFMT.
os_difftime()
static int os_difftime (lua_State * L) static
Definition at line 372 of file lua-5.4.3/src/loslib.c.
{
  time_t t1 = l_checktime(L, 1);
  time_t t2 = l_checktime(L, 2);
  lua_pushnumber(L, (lua_Number)difftime(t1, t2));
  return 1;
}
References l_checktime(), and lua_pushnumber().
os_execute()
static int os_execute (lua_State * L) static
Definition at line 142 of file lua-5.4.3/src/loslib.c.
{
  const char *cmd = luaL_optstring(L, 1, NULL);
  int stat;
  errno = 0;
  stat = system(cmd);
  if (cmd != NULL)
    return luaL_execresult(L, stat);
  else {
    lua_pushboolean(L, stat);  /* true if there is a shell */
    return 1;
  }
}
References lua_pushboolean(), luaL_execresult(), luaL_optstring, and NULL.
os_exit()
static int os_exit (lua_State * L) static
Definition at line 394 of file lua-5.4.3/src/loslib.c.
{
  int status;
  if (lua_isboolean(L, 1))
    status = (lua_toboolean(L, 1) ? EXIT_SUCCESS : EXIT_FAILURE);
  else
    status = (int)luaL_optinteger(L, 1, EXIT_SUCCESS);
  if (lua_toboolean(L, 2))
    lua_close(L);
  if (L) exit(status);  /* 'if' to avoid warnings for unreachable 'return' */
  return 0;
}
References lua_close(), lua_isboolean, lua_toboolean(), and luaL_optinteger().
os_getenv()
static int os_getenv (lua_State * L) static
Definition at line 180 of file lua-5.4.3/src/loslib.c.
{
  lua_pushstring(L, getenv(luaL_checkstring(L, 1)));  /* if NULL push nil */
  return 1;
}
References lua_pushstring(), and luaL_checkstring.
os_remove()
static int os_remove (lua_State * L) static
Definition at line 156 of file lua-5.4.3/src/loslib.c.
{
  const char *filename = luaL_checkstring(L, 1);
  return luaL_fileresult(L, remove(filename) == 0, filename);
}
References luaL_checkstring, and luaL_fileresult().
os_rename()
static int os_rename (lua_State * L) static
Definition at line 162 of file lua-5.4.3/src/loslib.c.
{
  const char *fromname = luaL_checkstring(L, 1);
  const char *toname = luaL_checkstring(L, 2);
  return luaL_fileresult(L, rename(fromname, toname) == 0, NULL);
}
References luaL_checkstring, luaL_fileresult(), and NULL.
os_setlocale()
static int os_setlocale (lua_State * L) static
Definition at line 382 of file lua-5.4.3/src/loslib.c.
{
  static const int cat[] = {LC_ALL, LC_COLLATE, LC_CTYPE, LC_MONETARY,
                      LC_NUMERIC, LC_TIME};
  static const char *const catnames[] = {"all", "collate", "ctype", "monetary",
     "numeric", "time", NULL};
  const char *l = luaL_optstring(L, 1, NULL);
  int op = luaL_checkoption(L, 2, "all", catnames);
  lua_pushstring(L, setlocale(cat[op], l));
  return 1;
}
References lua_pushstring(), luaL_checkoption(), luaL_optstring, and NULL.
os_time()
static int os_time (lua_State * L) static
Definition at line 346 of file lua-5.4.3/src/loslib.c.
{
  time_t t;
  if (lua_isnoneornil(L, 1))  /* called without args? */
    t = time(NULL);  /* get current time */
  else {
    struct tm ts;
    luaL_checktype(L, 1, LUA_TTABLE);
    lua_settop(L, 1);  /* make sure table is at the top */
    ts.tm_year = getfield(L, "year", -1, 1900);
    ts.tm_mon = getfield(L, "month", -1, 1);
    ts.tm_mday = getfield(L, "day", -1, 0);
    ts.tm_hour = getfield(L, "hour", 12, 0);
    ts.tm_min = getfield(L, "min", 0, 0);
    ts.tm_sec = getfield(L, "sec", 0, 0);
    ts.tm_isdst = getboolfield(L, "isdst");
    t = mktime(&ts);
    setallfields(L, &ts);  /* update fields with normalized values */
  }
  if (t != (time_t)(l_timet)t || t == (time_t)(-1))
    return luaL_error(L,
                  "time result cannot be represented in this installation");
  l_pushtime(L, t);
  return 1;
}
References getboolfield(), getfield(), l_pushtime, l_timet, lua_isnoneornil, lua_settop(), LUA_TTABLE, luaL_checktype(), luaL_error(), NULL, and setallfields().
os_tmpname()
static int os_tmpname (lua_State * L) static
Definition at line 169 of file lua-5.4.3/src/loslib.c.
{
  char buff[LUA_TMPNAMBUFSIZE];
  int err;
  lua_tmpnam(buff, err);
  if (l_unlikely(err))
    return luaL_error(L, "unable to generate a unique filename");
  lua_pushstring(L, buff);
  return 1;
}
References lua_pushstring(), lua_tmpnam, LUA_TMPNAMBUFSIZE, and luaL_error().
setallfields()
static void setallfields (lua_State * L, struct tm * stm) static
Definition at line 230 of file lua-5.4.3/src/loslib.c.
{
  setfield(L, "year", stm->tm_year, 1900);
  setfield(L, "month", stm->tm_mon, 1);
  setfield(L, "day", stm->tm_mday, 0);
  setfield(L, "hour", stm->tm_hour, 0);
  setfield(L, "min", stm->tm_min, 0);
  setfield(L, "sec", stm->tm_sec, 0);
  setfield(L, "yday", stm->tm_yday, 1);
  setfield(L, "wday", stm->tm_wday, 1);
  setboolfield(L, "isdst", stm->tm_isdst);
}
References setboolfield(), and setfield().
Referenced by os_date(), and os_time().
setboolfield()
static void setboolfield (lua_State * L, const char * key, int value) static
Definition at line 219 of file lua-5.4.3/src/loslib.c.
{
  if (value < 0)  /* undefined? */
    return;  /* does not set field */
  lua_pushboolean(L, value);
  lua_setfield(L, -2, key);
}
References lua_pushboolean(), lua_setfield(), and value.
Referenced by setallfields().
setfield()
static void setfield (lua_State * L, const char * key, int value, int delta) static
Definition at line 209 of file lua-5.4.3/src/loslib.c.
{
  #if (defined(LUA_NUMTIME) && LUA_MAXINTEGER <= INT_MAX)
    if (l_unlikely(value > LUA_MAXINTEGER - delta))
      luaL_error(L, "field '%s' is out-of-bound", key);
  #endif
  lua_pushinteger(L, (lua_Integer)value + delta);
  lua_setfield(L, -2, key);
}
References lua_pushinteger(), lua_setfield(), luaL_error(), and value.
Referenced by setallfields().
Variable Documentation
syslib
const luaL_Reg syslib[] static
Initial value:
= {
  {"clock",     os_clock},
  {"date",      os_date},
  {"difftime",  os_difftime},
  {"execute",   os_execute},
  {"exit",      os_exit},
  {"getenv",    os_getenv},
  {"remove",    os_remove},
  {"rename",    os_rename},
  {"setlocale", os_setlocale},
  {"time",      os_time},
  {"tmpname",   os_tmpname},
  {NULL, NULL}
}
Definition at line 407 of file lua-5.4.3/src/loslib.c.
{
  {"clock",     os_clock},
  {"date",      os_date},
  {"difftime",  os_difftime},
  {"execute",   os_execute},
  {"exit",      os_exit},
  {"getenv",    os_getenv},
  {"remove",    os_remove},
  {"rename",    os_rename},
  {"setlocale", os_setlocale},
  {"time",      os_time},
  {"tmpname",   os_tmpname},
  {NULL, NULL}
};
Referenced by luaopen_os().