Github User Fetcher: ldump.c File Reference
ldump.c File Reference
#include <stddef.h>
#include "lua.h"
#include "lobject.h"
#include "lstate.h"
#include "lundump.h"
Data Structures
struct DumpState
Macros
#define ldump_c
#define LUA_CORE
#define DumpMem(b, n, size, D) DumpBlock(b,(n)*(size),D)
#define DumpVar(x, D) DumpMem(&x,1,sizeof(x),D)
#define DumpCode(f, D) DumpVector(f->code,f->sizecode,sizeof(Instruction),D)
Functions
static void DumpBlock (const void *b, size_t size, DumpState *D)
static void DumpChar (int y, DumpState *D)
static void DumpInt (int x, DumpState *D)
static void DumpNumber (lua_Number x, DumpState *D)
static void DumpVector (const void *b, int n, size_t size, DumpState *D)
static void DumpString (const TString *s, DumpState *D)
static void DumpFunction (const Proto *f, const TString *p, DumpState *D)
static void DumpConstants (const Proto *f, DumpState *D)
static void DumpDebug (const Proto *f, DumpState *D)
static void DumpHeader (DumpState *D)
int luaU_dump (lua_State *L, const Proto *f, lua_Writer w, void *data, int strip)
Macro Definition Documentation
DumpCode
#define DumpCode (f, D) DumpVector(f->code,f->sizecode,sizeof(Instruction),D)
Definition at line 76 of file lua-5.1.5/src/ldump.c.
Referenced by DumpFunction(), and DumpFunction().
DumpMem
#define DumpMem (b, n, size, D) DumpBlock(b,(n)*(size),D)
Definition at line 26 of file lua-5.1.5/src/ldump.c.
Referenced by DumpVector().
DumpVar
#define DumpVar (x, D) DumpMem(&x,1,sizeof(x),D)
Definition at line 27 of file lua-5.1.5/src/ldump.c.
Referenced by DumpChar(), DumpInt(), DumpNumber(), and DumpString().
ldump_c
#define ldump_c
Definition at line 9 of file lua-5.1.5/src/ldump.c.
LUA_CORE
#define LUA_CORE
Definition at line 10 of file lua-5.1.5/src/ldump.c.
Function Documentation
DumpBlock()
static void DumpBlock (const void * b, size_t size, DumpState * D) static
Definition at line 29 of file lua-5.1.5/src/ldump.c.
{
 if (D->status==0)
 {
  lua_unlock(D->L);
  D->status=(*D->writer)(D->L,b,size,D->data);
  lua_lock(D->L);
 }
}
References DumpState::data, DumpState::L, lua_lock, lua_unlock, DumpState::status, and DumpState::writer.
Referenced by DumpHeader(), and DumpString().
DumpChar()
static void DumpChar (int y, DumpState * D) static
Definition at line 39 of file lua-5.1.5/src/ldump.c.
{
 char x=(char)y;
 DumpVar(x,D);
}
References DumpVar.
Referenced by DumpConstants(), and DumpFunction().
DumpConstants()
static void DumpConstants (const Proto * f, DumpState * D) static
Definition at line 80 of file lua-5.1.5/src/ldump.c.
{
 int i,n=f->sizek;
 DumpInt(n,D);
 for (i=0; i<n; i++)
 {
  const TValue* o=&f->k[i];
  DumpChar(ttype(o),D);
  switch (ttype(o))
  {
   case LUA_TNIL:
    break;
   case LUA_TBOOLEAN:
    DumpChar(bvalue(o),D);
    break;
   case LUA_TNUMBER:
    DumpNumber(nvalue(o),D);
    break;
   case LUA_TSTRING:
    DumpString(rawtsvalue(o),D);
    break;
   default:
    lua_assert(0);          /* cannot happen */
    break;
  }
 }
 n=f->sizep;
 DumpInt(n,D);
 for (i=0; i<n; i++) DumpFunction(f->p[i],f->source,D);
}
References bvalue, DumpChar(), DumpFunction(), DumpInt(), DumpNumber(), DumpString(), Proto::k, lua_assert, LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, LUA_TSTRING, nvalue, Proto::p, rawtsvalue, Proto::sizek, Proto::sizep, Proto::source, and ttype.
Referenced by DumpFunction().
DumpDebug()
static void DumpDebug (const Proto * f, DumpState * D) static
Definition at line 111 of file lua-5.1.5/src/ldump.c.
{
 int i,n;
 n= (D->strip) ? 0 : f->sizelineinfo;
 DumpVector(f->lineinfo,n,sizeof(int),D);
 n= (D->strip) ? 0 : f->sizelocvars;
 DumpInt(n,D);
 for (i=0; i<n; i++)
 {
  DumpString(f->locvars[i].varname,D);
  DumpInt(f->locvars[i].startpc,D);
  DumpInt(f->locvars[i].endpc,D);
 }
 n= (D->strip) ? 0 : f->sizeupvalues;
 DumpInt(n,D);
 for (i=0; i<n; i++) DumpString(f->upvalues[i],D);
}
References DumpInt(), DumpString(), DumpVector, LocVar::endpc, Proto::lineinfo, Proto::locvars, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizeupvalues, LocVar::startpc, DumpState::strip, Proto::upvalues, and LocVar::varname.
Referenced by DumpFunction().
DumpFunction()
static void DumpFunction (const Proto * f, const TString * p, DumpState * D) static
Definition at line 129 of file lua-5.1.5/src/ldump.c.
{
 DumpString((f->source==p || D->strip) ? NULL : f->source,D);
 DumpInt(f->linedefined,D);
 DumpInt(f->lastlinedefined,D);
 DumpChar(f->nups,D);
 DumpChar(f->numparams,D);
 DumpChar(f->is_vararg,D);
 DumpChar(f->maxstacksize,D);
 DumpCode(f,D);
 DumpConstants(f,D);
 DumpDebug(f,D);
}
References DumpChar(), DumpCode, DumpConstants(), DumpDebug(), DumpInt(), DumpString(), Proto::is_vararg, Proto::lastlinedefined, Proto::linedefined, Proto::maxstacksize, NULL, Proto::numparams, Proto::nups, Proto::source, and DumpState::strip.
Referenced by DumpConstants(), and luaU_dump().
DumpHeader()
static void DumpHeader (DumpState * D) static
Definition at line 143 of file lua-5.1.5/src/ldump.c.
{
 char h[LUAC_HEADERSIZE];
 luaU_header(h);
 DumpBlock(h,LUAC_HEADERSIZE,D);
}
References DumpBlock(), LUAC_HEADERSIZE, and luaU_header().
Referenced by luaU_dump().
DumpInt()
static void DumpInt (int x, DumpState * D) static
Definition at line 45 of file lua-5.1.5/src/ldump.c.
{
 DumpVar(x,D);
}
References DumpVar.
Referenced by DumpConstants(), DumpDebug(), DumpFunction(), and DumpVector().
DumpNumber()
static void DumpNumber (lua_Number x, DumpState * D) static
Definition at line 50 of file lua-5.1.5/src/ldump.c.
{
 DumpVar(x,D);
}
References DumpVar.
Referenced by DumpConstants().
DumpString()
static void DumpString (const TString * s, DumpState * D) static
Definition at line 61 of file lua-5.1.5/src/ldump.c.
{
 if (s==NULL || getstr(s)==NULL)
 {
  size_t size=0;
  DumpVar(size,D);
 }
 else
 {
  size_t size=s->tsv.len+1;     /* include trailing '\0' */
  DumpVar(size,D);
  DumpBlock(getstr(s),size,D);
 }
}
References DumpBlock(), DumpVar, getstr, NULL, and s.
Referenced by DumpConstants(), DumpDebug(), and DumpFunction().
DumpVector()
static void DumpVector (const void * b, int n, size_t size, DumpState * D) static
Definition at line 55 of file lua-5.1.5/src/ldump.c.
{
 DumpInt(n,D);
 DumpMem(b,n,size,D);
}
References DumpInt(), and DumpMem.
luaU_dump()
int luaU_dump (lua_State * L, const Proto * f, lua_Writer w, void * data, int strip)
Definition at line 153 of file lua-5.1.5/src/ldump.c.
{
 DumpState D;
 D.L=L;
 D.writer=w;
 D.data=data;
 D.strip=strip;
 D.status=0;
 DumpHeader(&D);
 DumpFunction(f,NULL,&D);
 return D.status;
}
References DumpState::data, DumpFunction(), DumpHeader(), DumpState::L, NULL, DumpState::status, DumpState::strip, and DumpState::writer.
Referenced by lua_dump(), lua_dump(), pmain(), pmain(), pmain(), and pmain().