Github User Fetcher: lapi.c File Reference
lapi.c File Reference
#include "lprefix.h"
#include <stdarg.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lundump.h"
#include "lvm.h"
Data Structures
struct CallS
Macros
#define lapi_c
#define LUA_CORE
#define NONVALIDVALUE cast(TValue *, luaO_nilobject)
#define isvalid(o) ((o) != luaO_nilobject)
#define ispseudo(i) ((i) <= LUA_REGISTRYINDEX)
#define isupvalue(i) ((i) < LUA_REGISTRYINDEX)
#define isstackindex(i, o) (isvalid(o) && !ispseudo(i))
#define api_checkvalidindex(l, o) api_check(l, isvalid(o), "invalid index")
#define api_checkstackindex(l, i, o) api_check(l, isstackindex(i, o), "index not in the stack")
#define checkresults(L, na, nr)
Functions
static TValue * index2addr (lua_State *L, int idx)
static void growstack (lua_State *L, void *ud)
LUA_API int lua_checkstack (lua_State *L, int n)
LUA_API void lua_xmove (lua_State *from, lua_State *to, int n)
LUA_API lua_CFunction lua_atpanic (lua_State *L, lua_CFunction panicf)
LUA_API const lua_Number * lua_version (lua_State *L)
LUA_API int lua_absindex (lua_State *L, int idx)
LUA_API int lua_gettop (lua_State *L)
LUA_API void lua_settop (lua_State *L, int idx)
static void reverse (lua_State *L, StkId from, StkId to)
LUA_API void lua_rotate (lua_State *L, int idx, int n)
LUA_API void lua_copy (lua_State *L, int fromidx, int toidx)
LUA_API void lua_pushvalue (lua_State *L, int idx)
LUA_API int lua_type (lua_State *L, int idx)
LUA_API const char * lua_typename (lua_State *L, int t)
LUA_API int lua_iscfunction (lua_State *L, int idx)
LUA_API int lua_isinteger (lua_State *L, int idx)
LUA_API int lua_isnumber (lua_State *L, int idx)
LUA_API int lua_isstring (lua_State *L, int idx)
LUA_API int lua_isuserdata (lua_State *L, int idx)
LUA_API int lua_rawequal (lua_State *L, int index1, int index2)
LUA_API void lua_arith (lua_State *L, int op)
LUA_API int lua_compare (lua_State *L, int index1, int index2, int op)
LUA_API size_t lua_stringtonumber (lua_State *L, const char *s)
LUA_API lua_Number lua_tonumberx (lua_State *L, int idx, int *pisnum)
LUA_API lua_Integer lua_tointegerx (lua_State *L, int idx, int *pisnum)
LUA_API int lua_toboolean (lua_State *L, int idx)
LUA_API const char * lua_tolstring (lua_State *L, int idx, size_t *len)
LUA_API size_t lua_rawlen (lua_State *L, int idx)
LUA_API lua_CFunction lua_tocfunction (lua_State *L, int idx)
LUA_API void * lua_touserdata (lua_State *L, int idx)
LUA_API lua_State * lua_tothread (lua_State *L, int idx)
LUA_API const void * lua_topointer (lua_State *L, int idx)
LUA_API void lua_pushnil (lua_State *L)
LUA_API void lua_pushnumber (lua_State *L, lua_Number n)
LUA_API void lua_pushinteger (lua_State *L, lua_Integer n)
LUA_API const char * lua_pushlstring (lua_State *L, const char *s, size_t len)
LUA_API const char * lua_pushstring (lua_State *L, const char *s)
LUA_API const char * lua_pushvfstring (lua_State *L, const char *fmt, va_list argp)
LUA_API const char * lua_pushfstring (lua_State *L, const char *fmt,...)
LUA_API void lua_pushcclosure (lua_State *L, lua_CFunction fn, int n)
LUA_API void lua_pushboolean (lua_State *L, int b)
LUA_API void lua_pushlightuserdata (lua_State *L, void *p)
LUA_API int lua_pushthread (lua_State *L)
static int auxgetstr (lua_State *L, const TValue *t, const char *k)
LUA_API int lua_getglobal (lua_State *L, const char *name)
LUA_API int lua_gettable (lua_State *L, int idx)
LUA_API int lua_getfield (lua_State *L, int idx, const char *k)
LUA_API int lua_geti (lua_State *L, int idx, lua_Integer n)
LUA_API int lua_rawget (lua_State *L, int idx)
LUA_API int lua_rawgeti (lua_State *L, int idx, lua_Integer n)
LUA_API int lua_rawgetp (lua_State *L, int idx, const void *p)
LUA_API void lua_createtable (lua_State *L, int narray, int nrec)
LUA_API int lua_getmetatable (lua_State *L, int objindex)
LUA_API int lua_getuservalue (lua_State *L, int idx)
static void auxsetstr (lua_State *L, const TValue *t, const char *k)
LUA_API void lua_setglobal (lua_State *L, const char *name)
LUA_API void lua_settable (lua_State *L, int idx)
LUA_API void lua_setfield (lua_State *L, int idx, const char *k)
LUA_API void lua_seti (lua_State *L, int idx, lua_Integer n)
LUA_API void lua_rawset (lua_State *L, int idx)
LUA_API void lua_rawseti (lua_State *L, int idx, lua_Integer n)
LUA_API void lua_rawsetp (lua_State *L, int idx, const void *p)
LUA_API int lua_setmetatable (lua_State *L, int objindex)
LUA_API void lua_setuservalue (lua_State *L, int idx)
LUA_API void lua_callk (lua_State *L, int nargs, int nresults, lua_KContext ctx, lua_KFunction k)
static void f_call (lua_State *L, void *ud)
LUA_API int lua_pcallk (lua_State *L, int nargs, int nresults, int errfunc, lua_KContext ctx, lua_KFunction k)
LUA_API int lua_load (lua_State *L, lua_Reader reader, void *data, const char *chunkname, const char *mode)
LUA_API int lua_dump (lua_State *L, lua_Writer writer, void *data, int strip)
LUA_API int lua_status (lua_State *L)
LUA_API int lua_gc (lua_State *L, int what, int data)
LUA_API int lua_error (lua_State *L)
LUA_API int lua_next (lua_State *L, int idx)
LUA_API void lua_concat (lua_State *L, int n)
LUA_API void lua_len (lua_State *L, int idx)
LUA_API lua_Alloc lua_getallocf (lua_State *L, void **ud)
LUA_API void lua_setallocf (lua_State *L, lua_Alloc f, void *ud)
LUA_API void * lua_newuserdata (lua_State *L, size_t size)
static const char * aux_upvalue (StkId fi, int n, TValue **val, CClosure **owner, UpVal **uv)
LUA_API const char * lua_getupvalue (lua_State *L, int funcindex, int n)
LUA_API const char * lua_setupvalue (lua_State *L, int funcindex, int n)
static UpVal ** getupvalref (lua_State *L, int fidx, int n)
LUA_API void * lua_upvalueid (lua_State *L, int fidx, int n)
LUA_API void lua_upvaluejoin (lua_State *L, int fidx1, int n1, int fidx2, int n2)
Variables
const char lua_ident []
Macro Definition Documentation
api_checkstackindex
#define api_checkstackindex (l, i, o) api_check(l, isstackindex(i, o), "index not in the stack")
Definition at line 56 of file lua-5.3.6/src/lapi.c.
#define api_checkstackindex(l, i, o)  \
    api_check(l, isstackindex(i, o), "index not in the stack")
Referenced by lua_pcallk(), and lua_rotate().
api_checkvalidindex
#define api_checkvalidindex (l, o) api_check(l, isvalid(o), "invalid index")
Definition at line 54 of file lua-5.3.6/src/lapi.c.
Referenced by lua_copy().
checkresults
#define checkresults (L, na, nr)
Value:
     api_check(L, (nr) == LUA_MULTRET || (L->ci->top - L->top >= (nr) - (na)), \
    "results from function overflow current stack size")
Definition at line 904 of file lua-5.3.6/src/lapi.c.
#define checkresults(L,na,nr) \
     api_check(L, (nr) == LUA_MULTRET || (L->ci->top - L->top >= (nr) - (na)), \
    "results from function overflow current stack size")
Referenced by lua_callk(), and lua_pcallk().
ispseudo
#define ispseudo (i) ((i) <= LUA_REGISTRYINDEX)
Definition at line 46 of file lua-5.3.6/src/lapi.c.
Referenced by index2addr(), and lua_absindex().
isstackindex
#define isstackindex (i, o) (isvalid(o) && !ispseudo(i))
Definition at line 52 of file lua-5.3.6/src/lapi.c.
isupvalue
#define isupvalue (i) ((i) < LUA_REGISTRYINDEX)
Definition at line 49 of file lua-5.3.6/src/lapi.c.
Referenced by lua_copy().
isvalid
#define isvalid (o) ((o) != luaO_nilobject)
Definition at line 43 of file lua-5.3.6/src/lapi.c.
Referenced by lua_compare(), lua_rawequal(), and lua_type().
lapi_c
#define lapi_c
Definition at line 7 of file lua-5.3.6/src/lapi.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/lapi.c.
NONVALIDVALUE
#define NONVALIDVALUE cast(TValue *, luaO_nilobject)
Definition at line 40 of file lua-5.3.6/src/lapi.c.
Referenced by index2addr().
Function Documentation
aux_upvalue()
static const char * aux_upvalue (StkId fi, int n, TValue ** val, CClosure ** owner, UpVal ** uv) static
Definition at line 1197 of file lua-5.3.6/src/lapi.c.
{
  switch (ttype(fi)) {
    case LUA_TCCL: {  /* C closure */
      CClosure *f = clCvalue(fi);
      if (!(1 <= n && n <= f->nupvalues)) return NULL;
      *val = &f->upvalue[n-1];
      if (owner) *owner = f;
      return "";
    }
    case LUA_TLCL: {  /* Lua closure */
      LClosure *f = clLvalue(fi);
      TString *name;
      Proto *p = f->p;
      if (!(1 <= n && n <= p->sizeupvalues)) return NULL;
      *val = f->upvals[n-1]->v;
      if (uv) *uv = f->upvals[n - 1];
      name = p->upvalues[n-1].name;
      return (name == NULL) ? "(*no name)" : getstr(name);
    }
    default: return NULL;  /* not a closure */
  }
}
References clCvalue, clLvalue, getstr, LUA_TCCL, LUA_TLCL, name, NULL, owner, LClosure::p, ttype, LClosure::upvals, CClosure::upvalue, Proto::upvalues, and UpVal::v.
Referenced by lua_getupvalue(), and lua_setupvalue().
auxgetstr()
static int auxgetstr (lua_State * L, const TValue * t, const char * k) static
Definition at line 588 of file lua-5.3.6/src/lapi.c.
{
  const TValue *slot;
  TString *str = luaS_new(L, k);
  if (luaV_fastget(L, t, str, slot, luaH_getstr)) {
    setobj2s(L, L->top, slot);
    api_incr_top(L);
  }
  else {
    setsvalue2s(L, L->top, str);
    api_incr_top(L);
    luaV_finishget(L, t, L->top - 1, L->top - 1, slot);
  }
  lua_unlock(L);
  return ttnov(L->top - 1);
}
References api_incr_top, lua_unlock, luaH_getstr(), luaS_new, luaV_fastget, luaV_finishget(), setobj2s, setsvalue2s, lua_State::top, and ttnov.
Referenced by lua_getfield(), and lua_getglobal().
auxsetstr()
static void auxsetstr (lua_State * L, const TValue * t, const char * k) static
Definition at line 743 of file lua-5.3.6/src/lapi.c.
{
  const TValue *slot;
  TString *str = luaS_new(L, k);
  api_checknelems(L, 1);
  if (luaV_fastset(L, t, str, slot, luaH_getstr, L->top - 1))
    L->top--;  /* pop value */
  else {
    setsvalue2s(L, L->top, str);  /* push 'str' (to make it a TValue) */
    api_incr_top(L);
    luaV_finishset(L, t, L->top - 1, L->top - 2, slot);
    L->top -= 2;  /* pop value and key */
  }
  lua_unlock(L);  /* lock done by caller */
}
References api_checknelems, api_incr_top, lua_unlock, luaH_getstr(), luaS_new, luaV_fastset, luaV_finishset(), setsvalue2s, and lua_State::top.
Referenced by lua_setfield(), and lua_setglobal().
f_call()
static void f_call (lua_State * L, void * ud) static
Definition at line 941 of file lua-5.3.6/src/lapi.c.
{
  struct CallS *c = cast(struct CallS *, ud);
  luaD_callnoyield(L, c->func, c->nresults);
}
References cast, CallS::func, luaD_callnoyield(), and CallS::nresults.
Referenced by lua_pcallk().
getupvalref()
static UpVal ** getupvalref (lua_State * L, int fidx, int n) static
Definition at line 1257 of file lua-5.3.6/src/lapi.c.
{
  LClosure *f;
  StkId fi = index2addr(L, fidx);
  api_check(L, ttisLclosure(fi), "Lua function expected");
  f = clLvalue(fi);
  api_check(L, (1 <= n && n <= f->p->sizeupvalues), "invalid upvalue index");
  return &f->upvals[n - 1];  /* get its upvalue pointer */
}
References api_check, clLvalue, index2addr(), ttisLclosure, and LClosure::upvals.
Referenced by lua_upvalueid(), and lua_upvaluejoin().
growstack()
static void growstack (lua_State * L, void * ud) static
Definition at line 91 of file lua-5.3.6/src/lapi.c.
{
  int size = *(int *)ud;
  luaD_growstack(L, size);
}
References luaD_growstack().
Referenced by lua_checkstack().
index2addr()
static TValue * index2addr (lua_State * L, int idx) static
Definition at line 60 of file lua-5.3.6/src/lapi.c.
{
  CallInfo *ci = L->ci;
  if (idx > 0) {
    TValue *o = ci->func + idx;
    api_check(L, idx <= ci->top - (ci->func + 1), "unacceptable index");
    if (o >= L->top) return NONVALIDVALUE;
    else return o;
  }
  else if (!ispseudo(idx)) {  /* negative index */
    api_check(L, idx != 0 && -idx <= L->top - (ci->func + 1), "invalid index");
    return L->top + idx;
  }
  else if (idx == LUA_REGISTRYINDEX)
    return &G(L)->l_registry;
  else {  /* upvalues */
    idx = LUA_REGISTRYINDEX - idx;
    api_check(L, idx <= MAXUPVAL + 1, "upvalue index too large");
    if (ttislcf(ci->func))  /* light C function? */
      return NONVALIDVALUE;  /* it has no upvalues */
    else {
      CClosure *func = clCvalue(ci->func);
      return (idx <= func->nupvalues) ? &func->upvalue[idx-1] : NONVALIDVALUE;
    }
  }
}
References api_check, lua_State::ci, clCvalue, CallInfo::func, G, ispseudo, LUA_REGISTRYINDEX, MAXUPVAL, NONVALIDVALUE, lua_State::top, ttislcf, and CClosure::upvalue.
Referenced by getupvalref(), lua_compare(), lua_copy(), lua_getfield(), lua_geti(), lua_getmetatable(), lua_gettable(), lua_getupvalue(), lua_getuservalue(), lua_iscfunction(), lua_isinteger(), lua_isnumber(), lua_isstring(), lua_isuserdata(), lua_len(), lua_next(), lua_pcallk(), lua_pushvalue(), lua_rawequal(), lua_rawget(), lua_rawgeti(), lua_rawgetp(), lua_rawlen(), lua_rawset(), lua_rawseti(), lua_rawsetp(), lua_rotate(), lua_setfield(), lua_seti(), lua_setmetatable(), lua_settable(), lua_setupvalue(), lua_setuservalue(), lua_toboolean(), lua_tocfunction(), lua_tointegerx(), lua_tolstring(), lua_tonumberx(), lua_topointer(), lua_tothread(), lua_touserdata(), lua_type(), and lua_upvalueid().
lua_absindex()
LUA_API int lua_absindex (lua_State * L, int idx)
Definition at line 160 of file lua-5.3.6/src/lapi.c.
{
  return (idx > 0 || ispseudo(idx))
         ? idx
         : cast_int(L->top - L->ci->func) + idx;
}
References cast_int, lua_State::ci, CallInfo::func, ispseudo, and lua_State::top.
lua_arith()
LUA_API void lua_arith (lua_State * L, int op)
Definition at line 302 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  if (op != LUA_OPUNM && op != LUA_OPBNOT)
    api_checknelems(L, 2);  /* all other operations expect two operands */
  else {  /* for unary operations, add fake 2nd operand */
    api_checknelems(L, 1);
    setobjs2s(L, L->top, L->top - 1);
    api_incr_top(L);
  }
  /* first operand at top - 2, second at top - 1; result go to top - 2 */
  luaO_arith(L, op, L->top - 2, L->top - 1, L->top - 2);
  L->top--;  /* remove second operand */
  lua_unlock(L);
}
References api_checknelems, api_incr_top, lua_lock, LUA_OPBNOT, LUA_OPUNM, lua_unlock, luaO_arith(), setobjs2s, and lua_State::top.
lua_atpanic()
LUA_API lua_CFunction lua_atpanic (lua_State * L, lua_CFunction panicf)
Definition at line 134 of file lua-5.3.6/src/lapi.c.
{
  lua_CFunction old;
  lua_lock(L);
  old = G(L)->panic;
  G(L)->panic = panicf;
  lua_unlock(L);
  return old;
}
References G, lua_lock, and lua_unlock.
lua_callk()
LUA_API void lua_callk (lua_State * L, int nargs, int nresults, lua_KContext ctx, lua_KFunction k)
Definition at line 909 of file lua-5.3.6/src/lapi.c.
{
  StkId func;
  lua_lock(L);
  api_check(L, k == NULL || !isLua(L->ci),
    "cannot use continuations inside hooks");
  api_checknelems(L, nargs+1);
  api_check(L, L->status == LUA_OK, "cannot do calls on non-normal thread");
  checkresults(L, nargs, nresults);
  func = L->top - (nargs+1);
  if (k != NULL && L->nny == 0) {  /* need to prepare continuation? */
    L->ci->u.c.k = k;  /* save continuation */
    L->ci->u.c.ctx = ctx;  /* save context */
    luaD_call(L, func, nresults);  /* do the call */
  }
  else  /* no continuation or no yieldable */
    luaD_callnoyield(L, func, nresults);  /* just do the call */
  adjustresults(L, nresults);
  lua_unlock(L);
}
References adjustresults, api_check, api_checknelems, CallInfo::c, checkresults, lua_State::ci, CallInfo::ctx, isLua, CallInfo::k, lua_lock, LUA_OK, lua_unlock, luaD_call(), luaD_callnoyield(), lua_State::nny, NULL, lua_State::status, lua_State::top, and CallInfo::u.
lua_checkstack()
LUA_API int lua_checkstack (lua_State * L, int n)
Definition at line 97 of file lua-5.3.6/src/lapi.c.
{
  int res;
  CallInfo *ci = L->ci;
  lua_lock(L);
  api_check(L, n >= 0, "negative 'n'");
  if (L->stack_last - L->top > n)  /* stack large enough? */
    res = 1;  /* yes; check is OK */
  else {  /* no; need to grow stack */
    int inuse = cast_int(L->top - L->stack) + EXTRA_STACK;
    if (inuse > LUAI_MAXSTACK - n)  /* can grow without overflow? */
      res = 0;  /* no */
    else  /* try to grow stack */
      res = (luaD_rawrunprotected(L, &growstack, &n) == LUA_OK);
  }
  if (res && ci->top < L->top + n)
    ci->top = L->top + n;  /* adjust frame top */
  lua_unlock(L);
  return res;
}
References api_check, cast_int, lua_State::ci, EXTRA_STACK, growstack(), lua_lock, LUA_OK, lua_unlock, luaD_rawrunprotected(), LUAI_MAXSTACK, lua_State::stack, lua_State::stack_last, CallInfo::top, and lua_State::top.
lua_compare()
LUA_API int lua_compare (lua_State * L, int index1, int index2, int op)
Definition at line 318 of file lua-5.3.6/src/lapi.c.
{
  StkId o1, o2;
  int i = 0;
  lua_lock(L);  /* may call tag method */
  o1 = index2addr(L, index1);
  o2 = index2addr(L, index2);
  if (isvalid(o1) && isvalid(o2)) {
    switch (op) {
      case LUA_OPEQ: i = luaV_equalobj(L, o1, o2); break;
      case LUA_OPLT: i = luaV_lessthan(L, o1, o2); break;
      case LUA_OPLE: i = luaV_lessequal(L, o1, o2); break;
      default: api_check(L, 0, "invalid option");
    }
  }
  lua_unlock(L);
  return i;
}
References api_check, index2addr(), isvalid, lua_lock, LUA_OPEQ, LUA_OPLE, LUA_OPLT, lua_unlock, luaV_equalobj(), luaV_lessequal(), and luaV_lessthan().
lua_concat()
LUA_API void lua_concat (lua_State * L, int n)
Definition at line 1140 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  api_checknelems(L, n);
  if (n >= 2) {
    luaV_concat(L, n);
  }
  else if (n == 0) {  /* push empty string */
    setsvalue2s(L, L->top, luaS_newlstr(L, "", 0));
    api_incr_top(L);
  }
  /* else n == 1; nothing to do */
  luaC_checkGC(L);
  lua_unlock(L);
}
References api_checknelems, api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaS_newlstr(), luaV_concat(), setsvalue2s, and lua_State::top.
lua_copy()
LUA_API void lua_copy (lua_State * L, int fromidx, int toidx)
Definition at line 222 of file lua-5.3.6/src/lapi.c.
{
  TValue *fr, *to;
  lua_lock(L);
  fr = index2addr(L, fromidx);
  to = index2addr(L, toidx);
  api_checkvalidindex(L, to);
  setobj(L, to, fr);
  if (isupvalue(toidx))  /* function upvalue? */
    luaC_barrier(L, clCvalue(L->ci->func), fr);
  /* LUA_REGISTRYINDEX does not need gc barrier
     (collector revisits it before finishing collection) */
  lua_unlock(L);
}
References api_checkvalidindex, lua_State::ci, clCvalue, CallInfo::func, index2addr(), isupvalue, lua_lock, lua_unlock, luaC_barrier, and setobj.
lua_createtable()
LUA_API void lua_createtable (lua_State * L, int narray, int nrec)
Definition at line 684 of file lua-5.3.6/src/lapi.c.
{
  Table *t;
  lua_lock(L);
  t = luaH_new(L);
  sethvalue(L, L->top, t);
  api_incr_top(L);
  if (narray > 0 || nrec > 0)
    luaH_resize(L, t, narray, nrec);
  luaC_checkGC(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaH_new(), luaH_resize(), sethvalue, and lua_State::top.
lua_dump()
LUA_API int lua_dump (lua_State * L, lua_Writer writer, void * data, int strip)
Definition at line 1016 of file lua-5.3.6/src/lapi.c.
{
  int status;
  TValue *o;
  lua_lock(L);
  api_checknelems(L, 1);
  o = L->top - 1;
  if (isLfunction(o))
    status = luaU_dump(L, getproto(o), writer, data, strip);
  else
    status = 1;
  lua_unlock(L);
  return status;
}
References api_checknelems, getproto, isLfunction, lua_lock, lua_unlock, luaU_dump(), lua_State::top, and writer().
lua_error()
LUA_API int lua_error (lua_State * L)
Definition at line 1114 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  api_checknelems(L, 1);
  luaG_errormsg(L);
  /* code unreachable; will unlock when control actually leaves the kernel */
  return 0;  /* to avoid warnings */
}
References api_checknelems, lua_lock, and luaG_errormsg().
lua_gc()
LUA_API int lua_gc (lua_State * L, int what, int data)
Definition at line 1040 of file lua-5.3.6/src/lapi.c.
{
  int res = 0;
  global_State *g;
  lua_lock(L);
  g = G(L);
  switch (what) {
    case LUA_GCSTOP: {
      g->gcrunning = 0;
      break;
    }
    case LUA_GCRESTART: {
      luaE_setdebt(g, 0);
      g->gcrunning = 1;
      break;
    }
    case LUA_GCCOLLECT: {
      luaC_fullgc(L, 0);
      break;
    }
    case LUA_GCCOUNT: {
      /* GC values are expressed in Kbytes: #bytes/2^10 */
      res = cast_int(gettotalbytes(g) >> 10);
      break;
    }
    case LUA_GCCOUNTB: {
      res = cast_int(gettotalbytes(g) & 0x3ff);
      break;
    }
    case LUA_GCSTEP: {
      l_mem debt = 1;  /* =1 to signal that it did an actual step */
      lu_byte oldrunning = g->gcrunning;
      g->gcrunning = 1;  /* allow GC to run */
      if (data == 0) {
        luaE_setdebt(g, -GCSTEPSIZE);  /* to do a "small" step */
        luaC_step(L);
      }
      else {  /* add 'data' to total debt */
        debt = cast(l_mem, data) * 1024 + g->GCdebt;
        luaE_setdebt(g, debt);
        luaC_checkGC(L);
      }
      g->gcrunning = oldrunning;  /* restore previous state */
      if (debt > 0 && g->gcstate == GCSpause)  /* end of cycle? */
        res = 1;  /* signal it */
      break;
    }
    case LUA_GCSETPAUSE: {
      res = g->gcpause;
      g->gcpause = data;
      break;
    }
    case LUA_GCSETSTEPMUL: {
      res = g->gcstepmul;
      if (data < 40) data = 40;  /* avoid ridiculous low values (and 0) */
      g->gcstepmul = data;
      break;
    }
    case LUA_GCISRUNNING: {
      res = g->gcrunning;
      break;
    }
    default: res = -1;  /* invalid option */
  }
  lua_unlock(L);
  return res;
}
References cast, cast_int, G, global_State::GCdebt, global_State::gcpause, global_State::gcrunning, GCSpause, global_State::gcstate, global_State::gcstepmul, GCSTEPSIZE, gettotalbytes, LUA_GCCOLLECT, LUA_GCCOUNT, LUA_GCCOUNTB, LUA_GCISRUNNING, LUA_GCRESTART, LUA_GCSETPAUSE, LUA_GCSETSTEPMUL, LUA_GCSTEP, LUA_GCSTOP, lua_lock, lua_unlock, luaC_checkGC, luaC_fullgc(), luaC_step(), and luaE_setdebt().
lua_getallocf()
LUA_API lua_Alloc lua_getallocf (lua_State * L, void ** ud)
Definition at line 1166 of file lua-5.3.6/src/lapi.c.
{
  lua_Alloc f;
  lua_lock(L);
  if (ud) *ud = G(L)->ud;
  f = G(L)->frealloc;
  lua_unlock(L);
  return f;
}
References G, lua_lock, and lua_unlock.
lua_getfield()
LUA_API int lua_getfield (lua_State * L, int idx, const char * k)
Definition at line 622 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  return auxgetstr(L, index2addr(L, idx), k);
}
References auxgetstr(), index2addr(), and lua_lock.
lua_getglobal()
LUA_API int lua_getglobal (lua_State * L, const char * name)
Definition at line 605 of file lua-5.3.6/src/lapi.c.
{
  Table *reg = hvalue(&G(L)->l_registry);
  lua_lock(L);
  return auxgetstr(L, luaH_getint(reg, LUA_RIDX_GLOBALS), name);
}
References auxgetstr(), G, hvalue, lua_lock, LUA_RIDX_GLOBALS, luaH_getint(), and name.
lua_geti()
LUA_API int lua_geti (lua_State * L, int idx, lua_Integer n)
Definition at line 628 of file lua-5.3.6/src/lapi.c.
{
  StkId t;
  const TValue *slot;
  lua_lock(L);
  t = index2addr(L, idx);
  if (luaV_fastget(L, t, n, slot, luaH_getint)) {
    setobj2s(L, L->top, slot);
    api_incr_top(L);
  }
  else {
    setivalue(L->top, n);
    api_incr_top(L);
    luaV_finishget(L, t, L->top - 1, L->top - 1, slot);
  }
  lua_unlock(L);
  return ttnov(L->top - 1);
}
References api_incr_top, index2addr(), lua_lock, lua_unlock, luaH_getint(), luaV_fastget, luaV_finishget(), setivalue, setobj2s, lua_State::top, and ttnov.
Referenced by addfield(), addfield(), auxsort(), auxsort(), ipairsaux(), ipairsaux(), partition(), partition(), tinsert(), tinsert(), tmove(), tmove(), tremove(), tremove(), tunpack(), and unpack().
lua_getmetatable()
LUA_API int lua_getmetatable (lua_State * L, int objindex)
Definition at line 697 of file lua-5.3.6/src/lapi.c.
{
  const TValue *obj;
  Table *mt;
  int res = 0;
  lua_lock(L);
  obj = index2addr(L, objindex);
  switch (ttnov(obj)) {
    case LUA_TTABLE:
      mt = hvalue(obj)->metatable;
      break;
    case LUA_TUSERDATA:
      mt = uvalue(obj)->metatable;
      break;
    default:
      mt = G(L)->mt[ttnov(obj)];
      break;
  }
  if (mt != NULL) {
    sethvalue(L, L->top, mt);
    api_incr_top(L);
    res = 1;
  }
  lua_unlock(L);
  return res;
}
References api_incr_top, G, hvalue, index2addr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, Table::metatable, NULL, sethvalue, lua_State::top, ttnov, and uvalue.
lua_gettable()
LUA_API int lua_gettable (lua_State * L, int idx)
Definition at line 612 of file lua-5.3.6/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  luaV_gettable(L, t, L->top - 1, L->top - 1);
  lua_unlock(L);
  return ttnov(L->top - 1);
}
References index2addr(), lua_lock, lua_unlock, luaV_gettable, lua_State::top, and ttnov.
lua_gettop()
LUA_API int lua_gettop (lua_State * L)
Definition at line 167 of file lua-5.3.6/src/lapi.c.
{
  return cast_int(L->top - (L->ci->func + 1));
}
References cast_int, lua_State::ci, CallInfo::func, and lua_State::top.
lua_getupvalue()
LUA_API const char * lua_getupvalue (lua_State * L, int funcindex, int n)
Definition at line 1222 of file lua-5.3.6/src/lapi.c.
{
  const char *name;
  TValue *val = NULL;  /* to avoid warnings */
  lua_lock(L);
  name = aux_upvalue(index2addr(L, funcindex), n, &val, NULL, NULL);
  if (name) {
    setobj2s(L, L->top, val);
    api_incr_top(L);
  }
  lua_unlock(L);
  return name;
}
References api_incr_top, aux_upvalue(), index2addr(), lua_lock, lua_unlock, name, NULL, setobj2s, and lua_State::top.
lua_getuservalue()
LUA_API int lua_getuservalue (lua_State * L, int idx)
Definition at line 724 of file lua-5.3.6/src/lapi.c.
{
  StkId o;
  lua_lock(L);
  o = index2addr(L, idx);
  api_check(L, ttisfulluserdata(o), "full userdata expected");
  getuservalue(L, uvalue(o), L->top);
  api_incr_top(L);
  lua_unlock(L);
  return ttnov(L->top - 1);
}
References api_check, api_incr_top, getuservalue, index2addr(), lua_lock, lua_unlock, lua_State::top, ttisfulluserdata, ttnov, and uvalue.
lua_iscfunction()
LUA_API int lua_iscfunction (lua_State * L, int idx)
Definition at line 264 of file lua-5.3.6/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  return (ttislcf(o) || (ttisCclosure(o)));
}
References index2addr(), ttisCclosure, and ttislcf.
lua_isinteger()
LUA_API int lua_isinteger (lua_State * L, int idx)
Definition at line 270 of file lua-5.3.6/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  return ttisinteger(o);
}
References index2addr(), and ttisinteger.
Referenced by addliteral(), addliteral(), db_exec_callback(), dbvm_bind_index(), g_write(), g_write(), lcontext_result(), luaL_ref(), luaL_tolstring(), luaL_unref(), math_abs(), math_abs(), math_ceil(), math_ceil(), math_floor(), math_floor(), math_fmod(), math_fmod(), math_modf(), math_modf(), math_type(), and math_type().
lua_isnumber()
LUA_API int lua_isnumber (lua_State * L, int idx)
Definition at line 276 of file lua-5.3.6/src/lapi.c.
{
  lua_Number n;
  const TValue *o = index2addr(L, idx);
  return tonumber(o, &n);
}
References index2addr(), and tonumber.
lua_isstring()
LUA_API int lua_isstring (lua_State * L, int idx)
Definition at line 283 of file lua-5.3.6/src/lapi.c.
{
  const TValue *o = index2addr(L, idx);
  return (ttisstring(o) || cvt2str(o));
}
References cvt2str, index2addr(), and ttisstring.
lua_isuserdata()
LUA_API int lua_isuserdata (lua_State * L, int idx)
Definition at line 289 of file lua-5.3.6/src/lapi.c.
{
  const TValue *o = index2addr(L, idx);
  return (ttisfulluserdata(o) || ttislightuserdata(o));
}
References index2addr(), ttisfulluserdata, and ttislightuserdata.
lua_len()
LUA_API void lua_len (lua_State * L, int idx)
Definition at line 1156 of file lua-5.3.6/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  luaV_objlen(L, L->top, t);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, index2addr(), lua_lock, lua_unlock, luaV_objlen(), and lua_State::top.
lua_load()
LUA_API int lua_load (lua_State * L, lua_Reader reader, void * data, const char * chunkname, const char * mode)
Definition at line 992 of file lua-5.3.6/src/lapi.c.
{
  ZIO z;
  int status;
  lua_lock(L);
  if (!chunkname) chunkname = "?";
  luaZ_init(L, &z, reader, data);
  status = luaD_protectedparser(L, &z, chunkname, mode);
  if (status == LUA_OK) {  /* no errors? */
    LClosure *f = clLvalue(L->top - 1);  /* get newly created function */
    if (f->nupvalues >= 1) {  /* does it have an upvalue? */
      /* get global table from registry */
      Table *reg = hvalue(&G(L)->l_registry);
      const TValue *gt = luaH_getint(reg, LUA_RIDX_GLOBALS);
      /* set global table as 1st upvalue of 'f' (may be LUA_ENV) */
      setobj(L, f->upvals[0]->v, gt);
      luaC_upvalbarrier(L, f->upvals[0]);
    }
  }
  lua_unlock(L);
  return status;
}
References clLvalue, G, gt, hvalue, lua_lock, LUA_OK, LUA_RIDX_GLOBALS, lua_unlock, luaC_upvalbarrier, luaD_protectedparser(), luaH_getint(), luaZ_init(), reader(), setobj, lua_State::top, LClosure::upvals, and UpVal::v.
lua_newuserdata()
LUA_API void * lua_newuserdata (lua_State * L, size_t size)
Definition at line 1184 of file lua-5.3.6/src/lapi.c.
{
  Udata *u;
  lua_lock(L);
  u = luaS_newudata(L, size);
  setuvalue(L, L->top, u);
  api_incr_top(L);
  luaC_checkGC(L);
  lua_unlock(L);
  return getudatamem(u);
}
References api_incr_top, getudatamem, lua_lock, lua_unlock, luaC_checkGC, luaS_newudata(), setuvalue, and lua_State::top.
lua_next()
LUA_API int lua_next (lua_State * L, int idx)
Definition at line 1123 of file lua-5.3.6/src/lapi.c.
{
  StkId t;
  int more;
  lua_lock(L);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  more = luaH_next(L, hvalue(t), L->top - 1);
  if (more) {
    api_incr_top(L);
  }
  else  /* no more elements */
    L->top -= 1;  /* remove key */
  lua_unlock(L);
  return more;
}
References api_check, api_incr_top, hvalue, index2addr(), lua_lock, lua_unlock, luaH_next(), lua_State::top, and ttistable.
lua_pcallk()
LUA_API int lua_pcallk (lua_State * L, int nargs, int nresults, int errfunc, lua_KContext ctx, lua_KFunction k)
Definition at line 948 of file lua-5.3.6/src/lapi.c.
{
  struct CallS c;
  int status;
  ptrdiff_t func;
  lua_lock(L);
  api_check(L, k == NULL || !isLua(L->ci),
    "cannot use continuations inside hooks");
  api_checknelems(L, nargs+1);
  api_check(L, L->status == LUA_OK, "cannot do calls on non-normal thread");
  checkresults(L, nargs, nresults);
  if (errfunc == 0)
    func = 0;
  else {
    StkId o = index2addr(L, errfunc);
    api_checkstackindex(L, errfunc, o);
    func = savestack(L, o);
  }
  c.func = L->top - (nargs+1);  /* function to be called */
  if (k == NULL || L->nny > 0) {  /* no continuation or no yieldable? */
    c.nresults = nresults;  /* do a 'conventional' protected call */
    status = luaD_pcall(L, f_call, &c, savestack(L, c.func), func);
  }
  else {  /* prepare continuation (call is already protected by 'resume') */
    CallInfo *ci = L->ci;
    ci->u.c.k = k;  /* save continuation */
    ci->u.c.ctx = ctx;  /* save context */
    /* save information for error recovery */
    ci->extra = savestack(L, c.func);
    ci->u.c.old_errfunc = L->errfunc;
    L->errfunc = func;
    setoah(ci->callstatus, L->allowhook);  /* save value of 'allowhook' */
    ci->callstatus |= CIST_YPCALL;  /* function can do error recovery */
    luaD_call(L, c.func, nresults);  /* do the call */
    ci->callstatus &= ~CIST_YPCALL;
    L->errfunc = ci->u.c.old_errfunc;
    status = LUA_OK;  /* if it is here, there were no errors */
  }
  adjustresults(L, nresults);
  lua_unlock(L);
  return status;
}
References adjustresults, lua_State::allowhook, api_check, api_checknelems, api_checkstackindex, CallInfo::c, CallInfo::callstatus, checkresults, lua_State::ci, CIST_YPCALL, CallInfo::ctx, lua_State::errfunc, CallInfo::extra, f_call(), CallS::func, index2addr(), isLua, CallInfo::k, lua_lock, LUA_OK, lua_unlock, luaD_call(), luaD_pcall(), lua_State::nny, CallS::nresults, NULL, CallInfo::old_errfunc, savestack, setoah, lua_State::status, lua_State::top, and CallInfo::u.
lua_pushboolean()
LUA_API void lua_pushboolean (lua_State * L, int b)
Definition at line 557 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  setbvalue(L->top, (b != 0));  /* ensure that true is 1 */
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setbvalue, and lua_State::top.
lua_pushcclosure()
LUA_API void lua_pushcclosure (lua_State * L, lua_CFunction fn, int n)
Definition at line 532 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  if (n == 0) {
    setfvalue(L->top, fn);
    api_incr_top(L);
  }
  else {
    CClosure *cl;
    api_checknelems(L, n);
    api_check(L, n <= MAXUPVAL, "upvalue index too large");
    cl = luaF_newCclosure(L, n);
    cl->f = fn;
    L->top -= n;
    while (n--) {
      setobj2n(L, &cl->upvalue[n], L->top + n);
      /* does not need barrier because closure is white */
    }
    setclCvalue(L, L->top, cl);
    api_incr_top(L);
    luaC_checkGC(L);
  }
  lua_unlock(L);
}
References api_check, api_checknelems, api_incr_top, CClosure::f, lua_lock, lua_unlock, luaC_checkGC, luaF_newCclosure(), MAXUPVAL, setclCvalue, setfvalue, setobj2n, lua_State::top, and CClosure::upvalue.
lua_pushfstring()
LUA_API const char * lua_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 519 of file lua-5.3.6/src/lapi.c.
{
  const char *ret;
  va_list argp;
  lua_lock(L);
  va_start(argp, fmt);
  ret = luaO_pushvfstring(L, fmt, argp);
  va_end(argp);
  luaC_checkGC(L);
  lua_unlock(L);
  return ret;
}
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
lua_pushinteger()
LUA_API void lua_pushinteger (lua_State * L, lua_Integer n)
Definition at line 466 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  setivalue(L->top, n);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setivalue, and lua_State::top.
lua_pushlightuserdata()
LUA_API void lua_pushlightuserdata (lua_State * L, void * p)
Definition at line 565 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  setpvalue(L->top, p);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setpvalue, and lua_State::top.
lua_pushlstring()
LUA_API const char * lua_pushlstring (lua_State * L, const char * s, size_t len)
Definition at line 479 of file lua-5.3.6/src/lapi.c.
{
  TString *ts;
  lua_lock(L);
  ts = (len == 0) ? luaS_new(L, "") : luaS_newlstr(L, s, len);
  setsvalue2s(L, L->top, ts);
  api_incr_top(L);
  luaC_checkGC(L);
  lua_unlock(L);
  return getstr(ts);
}
References api_incr_top, getstr, lua_lock, lua_unlock, luaC_checkGC, luaS_new, luaS_newlstr(), s, setsvalue2s, and lua_State::top.
lua_pushnil()
LUA_API void lua_pushnil (lua_State * L)
Definition at line 450 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  setnilvalue(L->top);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
lua_pushnumber()
LUA_API void lua_pushnumber (lua_State * L, lua_Number n)
Definition at line 458 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  setfltvalue(L->top, n);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setfltvalue, and lua_State::top.
lua_pushstring()
LUA_API const char * lua_pushstring (lua_State * L, const char * s)
Definition at line 491 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  if (s == NULL)
    setnilvalue(L->top);
  else {
    TString *ts;
    ts = luaS_new(L, s);
    setsvalue2s(L, L->top, ts);
    s = getstr(ts);  /* internal copy's address */
  }
  api_incr_top(L);
  luaC_checkGC(L);
  lua_unlock(L);
  return s;
}
References api_incr_top, getstr, lua_lock, lua_unlock, luaC_checkGC, luaS_new, NULL, s, setnilvalue, setsvalue2s, and lua_State::top.
lua_pushthread()
LUA_API int lua_pushthread (lua_State * L)
Definition at line 573 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  setthvalue(L, L->top, L);
  api_incr_top(L);
  lua_unlock(L);
  return (G(L)->mainthread == L);
}
References api_incr_top, G, lua_lock, lua_unlock, setthvalue, and lua_State::top.
lua_pushvalue()
LUA_API void lua_pushvalue (lua_State * L, int idx)
Definition at line 237 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  setobj2s(L, L->top, index2addr(L, idx));
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, index2addr(), lua_lock, lua_unlock, setobj2s, and lua_State::top.
lua_pushvfstring()
LUA_API const char * lua_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 508 of file lua-5.3.6/src/lapi.c.
{
  const char *ret;
  lua_lock(L);
  ret = luaO_pushvfstring(L, fmt, argp);
  luaC_checkGC(L);
  lua_unlock(L);
  return ret;
}
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
lua_rawequal()
LUA_API int lua_rawequal (lua_State * L, int index1, int index2)
Definition at line 295 of file lua-5.3.6/src/lapi.c.
{
  StkId o1 = index2addr(L, index1);
  StkId o2 = index2addr(L, index2);
  return (isvalid(o1) && isvalid(o2)) ? luaV_rawequalobj(o1, o2) : 0;
}
References index2addr(), isvalid, and luaV_rawequalobj.
lua_rawget()
LUA_API int lua_rawget (lua_State * L, int idx)
Definition at line 647 of file lua-5.3.6/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  setobj2s(L, L->top - 1, luaH_get(hvalue(t), L->top - 1));
  lua_unlock(L);
  return ttnov(L->top - 1);
}
References api_check, hvalue, index2addr(), lua_lock, lua_unlock, luaH_get(), setobj2s, lua_State::top, ttistable, and ttnov.
lua_rawgeti()
LUA_API int lua_rawgeti (lua_State * L, int idx, lua_Integer n)
Definition at line 658 of file lua-5.3.6/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  setobj2s(L, L->top, luaH_getint(hvalue(t), n));
  api_incr_top(L);
  lua_unlock(L);
  return ttnov(L->top - 1);
}
References api_check, api_incr_top, hvalue, index2addr(), lua_lock, lua_unlock, luaH_getint(), setobj2s, lua_State::top, ttistable, and ttnov.
lua_rawgetp()
LUA_API int lua_rawgetp (lua_State * L, int idx, const void * p)
Definition at line 670 of file lua-5.3.6/src/lapi.c.
{
  StkId t;
  TValue k;
  lua_lock(L);
  t = index2addr(L, idx);
  api_check(L, ttistable(t), "table expected");
  setpvalue(&k, cast(void *, p));
  setobj2s(L, L->top, luaH_get(hvalue(t), &k));
  api_incr_top(L);
  lua_unlock(L);
  return ttnov(L->top - 1);
}
References api_check, api_incr_top, cast, hvalue, index2addr(), lua_lock, lua_unlock, luaH_get(), setobj2s, setpvalue, lua_State::top, ttistable, and ttnov.
lua_rawlen()
LUA_API size_t lua_rawlen (lua_State * L, int idx)
Definition at line 392 of file lua-5.3.6/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  switch (ttype(o)) {
    case LUA_TSHRSTR: return tsvalue(o)->shrlen;
    case LUA_TLNGSTR: return tsvalue(o)->u.lnglen;
    case LUA_TUSERDATA: return uvalue(o)->len;
    case LUA_TTABLE: return luaH_getn(hvalue(o));
    default: return 0;
  }
}
References hvalue, index2addr(), LUA_TLNGSTR, LUA_TSHRSTR, LUA_TTABLE, LUA_TUSERDATA, luaH_getn(), tsvalue, ttype, and uvalue.
lua_rawset()
LUA_API void lua_rawset (lua_State * L, int idx)
Definition at line 801 of file lua-5.3.6/src/lapi.c.
{
  StkId o;
  TValue *slot;
  lua_lock(L);
  api_checknelems(L, 2);
  o = index2addr(L, idx);
  api_check(L, ttistable(o), "table expected");
  slot = luaH_set(L, hvalue(o), L->top - 2);
  setobj2t(L, slot, L->top - 1);
  invalidateTMcache(hvalue(o));
  luaC_barrierback(L, hvalue(o), L->top-1);
  L->top -= 2;
  lua_unlock(L);
}
References api_check, api_checknelems, hvalue, index2addr(), invalidateTMcache, lua_lock, lua_unlock, luaC_barrierback, luaH_set(), setobj2t, lua_State::top, and ttistable.
lua_rawseti()
LUA_API void lua_rawseti (lua_State * L, int idx, lua_Integer n)
Definition at line 817 of file lua-5.3.6/src/lapi.c.
{
  StkId o;
  lua_lock(L);
  api_checknelems(L, 1);
  o = index2addr(L, idx);
  api_check(L, ttistable(o), "table expected");
  luaH_setint(L, hvalue(o), n, L->top - 1);
  luaC_barrierback(L, hvalue(o), L->top-1);
  L->top--;
  lua_unlock(L);
}
References api_check, api_checknelems, hvalue, index2addr(), lua_lock, lua_unlock, luaC_barrierback, luaH_setint(), lua_State::top, and ttistable.
lua_rawsetp()
LUA_API void lua_rawsetp (lua_State * L, int idx, const void * p)
Definition at line 830 of file lua-5.3.6/src/lapi.c.
{
  StkId o;
  TValue k, *slot;
  lua_lock(L);
  api_checknelems(L, 1);
  o = index2addr(L, idx);
  api_check(L, ttistable(o), "table expected");
  setpvalue(&k, cast(void *, p));
  slot = luaH_set(L, hvalue(o), &k);
  setobj2t(L, slot, L->top - 1);
  luaC_barrierback(L, hvalue(o), L->top - 1);
  L->top--;
  lua_unlock(L);
}
References api_check, api_checknelems, cast, hvalue, index2addr(), lua_lock, lua_unlock, luaC_barrierback, luaH_set(), setobj2t, setpvalue, lua_State::top, and ttistable.
lua_rotate()
LUA_API void lua_rotate (lua_State * L, int idx, int n)
Definition at line 207 of file lua-5.3.6/src/lapi.c.
{
  StkId p, t, m;
  lua_lock(L);
  t = L->top - 1;  /* end of stack segment being rotated */
  p = index2addr(L, idx);  /* start of segment */
  api_checkstackindex(L, idx, p);
  api_check(L, (n >= 0 ? n : -n) <= (t - p + 1), "invalid 'n'");
  m = (n >= 0 ? t - n : p - n - 1);  /* end of prefix */
  reverse(L, p, m);  /* reverse the prefix with length 'n' */
  reverse(L, m + 1, t);  /* reverse the suffix */
  reverse(L, p, t);  /* reverse the entire segment */
  lua_unlock(L);
}
References api_check, api_checkstackindex, index2addr(), lua_lock, lua_unlock, reverse(), and lua_State::top.
Referenced by aux_lines(), aux_lines(), db_getlocal(), db_getlocal(), ll_require(), luaB_xpcall(), luaB_xpcall(), treatstackoption(), and treatstackoption().
lua_setallocf()
LUA_API void lua_setallocf (lua_State * L, lua_Alloc f, void * ud)
Definition at line 1176 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);
  G(L)->ud = ud;
  G(L)->frealloc = f;
  lua_unlock(L);
}
References G, lua_lock, and lua_unlock.
lua_setfield()
LUA_API void lua_setfield (lua_State * L, int idx, const char * k)
Definition at line 777 of file lua-5.3.6/src/lapi.c.
{
  lua_lock(L);  /* unlock done in 'auxsetstr' */
  auxsetstr(L, index2addr(L, idx), k);
}
References auxsetstr(), index2addr(), and lua_lock.
lua_setglobal()
LUA_API void lua_setglobal (lua_State * L, const char * name)
Definition at line 759 of file lua-5.3.6/src/lapi.c.
{
  Table *reg = hvalue(&G(L)->l_registry);
  lua_lock(L);  /* unlock done in 'auxsetstr' */
  auxsetstr(L, luaH_getint(reg, LUA_RIDX_GLOBALS), name);
}
References auxsetstr(), G, hvalue, lua_lock, LUA_RIDX_GLOBALS, luaH_getint(), and name.
lua_seti()
LUA_API void lua_seti (lua_State * L, int idx, lua_Integer n)
Definition at line 783 of file lua-5.3.6/src/lapi.c.
{
  StkId t;
  const TValue *slot;
  lua_lock(L);
  api_checknelems(L, 1);
  t = index2addr(L, idx);
  if (luaV_fastset(L, t, n, slot, luaH_getint, L->top - 1))
    L->top--;  /* pop value */
  else {
    setivalue(L->top, n);
    api_incr_top(L);
    luaV_finishset(L, t, L->top - 1, L->top - 2, slot);
    L->top -= 2;  /* pop value and key */
  }
  lua_unlock(L);
}
References api_checknelems, api_incr_top, index2addr(), lua_lock, lua_unlock, luaH_getint(), luaV_fastset, luaV_finishset(), setivalue, and lua_State::top.
Referenced by pack(), set2(), set2(), tinsert(), tinsert(), tmove(), tmove(), tpack(), tremove(), and tremove().
lua_setmetatable()
LUA_API int lua_setmetatable (lua_State * L, int objindex)
Definition at line 846 of file lua-5.3.6/src/lapi.c.
{
  TValue *obj;
  Table *mt;
  lua_lock(L);
  api_checknelems(L, 1);
  obj = index2addr(L, objindex);
  if (ttisnil(L->top - 1))
    mt = NULL;
  else {
    api_check(L, ttistable(L->top - 1), "table expected");
    mt = hvalue(L->top - 1);
  }
  switch (ttnov(obj)) {
    case LUA_TTABLE: {
      hvalue(obj)->metatable = mt;
      if (mt) {
        luaC_objbarrier(L, gcvalue(obj), mt);
        luaC_checkfinalizer(L, gcvalue(obj), mt);
      }
      break;
    }
    case LUA_TUSERDATA: {
      uvalue(obj)->metatable = mt;
      if (mt) {
        luaC_objbarrier(L, uvalue(obj), mt);
        luaC_checkfinalizer(L, gcvalue(obj), mt);
      }
      break;
    }
    default: {
      G(L)->mt[ttnov(obj)] = mt;
      break;
    }
  }
  L->top--;
  lua_unlock(L);
  return 1;
}
References api_check, api_checknelems, G, gcvalue, hvalue, index2addr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, luaC_checkfinalizer(), luaC_objbarrier, NULL, lua_State::top, ttisnil, ttistable, ttnov, and uvalue.
lua_settable()
LUA_API void lua_settable (lua_State * L, int idx)
Definition at line 766 of file lua-5.3.6/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  api_checknelems(L, 2);
  t = index2addr(L, idx);
  luaV_settable(L, t, L->top - 2, L->top - 1);
  L->top -= 2;  /* pop index and value */
  lua_unlock(L);
}
References api_checknelems, index2addr(), lua_lock, lua_unlock, luaV_settable, and lua_State::top.
lua_settop()
LUA_API void lua_settop (lua_State * L, int idx)
Definition at line 172 of file lua-5.3.6/src/lapi.c.
{
  StkId func = L->ci->func;
  lua_lock(L);
  if (idx >= 0) {
    api_check(L, idx <= L->stack_last - (func + 1), "new top too large");
    while (L->top < (func + 1) + idx)
      setnilvalue(L->top++);
    L->top = (func + 1) + idx;
  }
  else {
    api_check(L, -(idx+1) <= (L->top - (func + 1)), "invalid new top");
    L->top += idx+1;  /* 'subtract' index (index is negative) */
  }
  lua_unlock(L);
}
References api_check, lua_State::ci, CallInfo::func, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
lua_setupvalue()
LUA_API const char * lua_setupvalue (lua_State * L, int funcindex, int n)
Definition at line 1236 of file lua-5.3.6/src/lapi.c.
{
  const char *name;
  TValue *val = NULL;  /* to avoid warnings */
  CClosure *owner = NULL;
  UpVal *uv = NULL;
  StkId fi;
  lua_lock(L);
  fi = index2addr(L, funcindex);
  api_checknelems(L, 1);
  name = aux_upvalue(fi, n, &val, &owner, &uv);
  if (name) {
    L->top--;
    setobj(L, val, L->top);
    if (owner) { luaC_barrier(L, owner, L->top); }
    else if (uv) { luaC_upvalbarrier(L, uv); }
  }
  lua_unlock(L);
  return name;
}
References api_checknelems, aux_upvalue(), index2addr(), lua_lock, lua_unlock, luaC_barrier, luaC_upvalbarrier, name, NULL, owner, setobj, and lua_State::top.
lua_setuservalue()
LUA_API void lua_setuservalue (lua_State * L, int idx)
Definition at line 886 of file lua-5.3.6/src/lapi.c.
{
  StkId o;
  lua_lock(L);
  api_checknelems(L, 1);
  o = index2addr(L, idx);
  api_check(L, ttisfulluserdata(o), "full userdata expected");
  setuservalue(L, uvalue(o), L->top - 1);
  luaC_barrier(L, gcvalue(o), L->top - 1);
  L->top--;
  lua_unlock(L);
}
References api_check, api_checknelems, gcvalue, index2addr(), lua_lock, lua_unlock, luaC_barrier, setuservalue, lua_State::top, ttisfulluserdata, and uvalue.
lua_status()
LUA_API int lua_status (lua_State * L)
Definition at line 1031 of file lua-5.3.6/src/lapi.c.
{
  return L->status;
}
References lua_State::status.
lua_stringtonumber()
LUA_API size_t lua_stringtonumber (lua_State * L, const char * s)
Definition at line 337 of file lua-5.3.6/src/lapi.c.
{
  size_t sz = luaO_str2num(s, L->top);
  if (sz != 0)
    api_incr_top(L);
  return sz;
}
References api_incr_top, luaO_str2num(), s, and lua_State::top.
Referenced by luaB_tonumber(), luaB_tonumber(), read_number(), read_number(), and tonum().
lua_toboolean()
LUA_API int lua_toboolean (lua_State * L, int idx)
Definition at line 367 of file lua-5.3.6/src/lapi.c.
{
  const TValue *o = index2addr(L, idx);
  return !l_isfalse(o);
}
References index2addr(), and l_isfalse.
lua_tocfunction()
LUA_API lua_CFunction lua_tocfunction (lua_State * L, int idx)
Definition at line 404 of file lua-5.3.6/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  if (ttislcf(o)) return fvalue(o);
  else if (ttisCclosure(o))
    return clCvalue(o)->f;
  else return NULL;  /* not a C function */
}
References clCvalue, fvalue, index2addr(), NULL, ttisCclosure, and ttislcf.
lua_tointegerx()
LUA_API lua_Integer lua_tointegerx (lua_State * L, int idx, int * pisnum)
Definition at line 356 of file lua-5.3.6/src/lapi.c.
{
  lua_Integer res;
  const TValue *o = index2addr(L, idx);
  int isnum = tointeger(o, &res);
  if (!isnum)
    res = 0;  /* call to 'tointeger' may change 'n' even if it fails */
  if (pisnum) *pisnum = isnum;
  return res;
}
References index2addr(), and tointeger.
lua_tolstring()
LUA_API const char * lua_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 373 of file lua-5.3.6/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  if (!ttisstring(o)) {
    if (!cvt2str(o)) {  /* not convertible? */
      if (len != NULL) *len = 0;
      return NULL;
    }
    lua_lock(L);  /* 'luaO_tostring' may create a new string */
    luaO_tostring(L, o);
    luaC_checkGC(L);
    o = index2addr(L, idx);  /* previous call may reallocate the stack */
    lua_unlock(L);
  }
  if (len != NULL)
    *len = vslen(o);
  return svalue(o);
}
References cvt2str, index2addr(), lua_lock, lua_unlock, luaC_checkGC, luaO_tostring(), NULL, svalue, ttisstring, and vslen.
lua_tonumberx()
LUA_API lua_Number lua_tonumberx (lua_State * L, int idx, int * pisnum)
Definition at line 345 of file lua-5.3.6/src/lapi.c.
{
  lua_Number n;
  const TValue *o = index2addr(L, idx);
  int isnum = tonumber(o, &n);
  if (!isnum)
    n = 0;  /* call to 'tonumber' may change 'n' even if it fails */
  if (pisnum) *pisnum = isnum;
  return n;
}
References index2addr(), and tonumber.
lua_topointer()
LUA_API const void * lua_topointer (lua_State * L, int idx)
Definition at line 429 of file lua-5.3.6/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  switch (ttype(o)) {
    case LUA_TTABLE: return hvalue(o);
    case LUA_TLCL: return clLvalue(o);
    case LUA_TCCL: return clCvalue(o);
    case LUA_TLCF: return cast(void *, cast(size_t, fvalue(o)));
    case LUA_TTHREAD: return thvalue(o);
    case LUA_TUSERDATA: return getudatamem(uvalue(o));
    case LUA_TLIGHTUSERDATA: return pvalue(o);
    default: return NULL;
  }
}
References cast, clCvalue, clLvalue, fvalue, getudatamem, hvalue, index2addr(), LUA_TCCL, LUA_TLCF, LUA_TLCL, LUA_TLIGHTUSERDATA, LUA_TTABLE, LUA_TTHREAD, LUA_TUSERDATA, NULL, pvalue, thvalue, ttype, and uvalue.
lua_tothread()
LUA_API lua_State * lua_tothread (lua_State * L, int idx)
Definition at line 423 of file lua-5.3.6/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  return (!ttisthread(o)) ? NULL : thvalue(o);
}
References index2addr(), NULL, thvalue, and ttisthread.
lua_touserdata()
LUA_API void * lua_touserdata (lua_State * L, int idx)
Definition at line 413 of file lua-5.3.6/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  switch (ttnov(o)) {
    case LUA_TUSERDATA: return getudatamem(uvalue(o));
    case LUA_TLIGHTUSERDATA: return pvalue(o);
    default: return NULL;
  }
}
References getudatamem, index2addr(), LUA_TLIGHTUSERDATA, LUA_TUSERDATA, NULL, pvalue, ttnov, and uvalue.
lua_type()
LUA_API int lua_type (lua_State * L, int idx)
Definition at line 251 of file lua-5.3.6/src/lapi.c.
{
  StkId o = index2addr(L, idx);
  return (isvalid(o) ? ttnov(o) : LUA_TNONE);
}
References index2addr(), isvalid, LUA_TNONE, and ttnov.
lua_typename()
LUA_API const char * lua_typename (lua_State * L, int t)
Definition at line 257 of file lua-5.3.6/src/lapi.c.
{
  UNUSED(L);
  api_check(L, LUA_TNONE <= t && t < LUA_NUMTAGS, "invalid tag");
  return ttypename(t);
}
References api_check, LUA_NUMTAGS, LUA_TNONE, ttypename, and UNUSED.
lua_upvalueid()
LUA_API void * lua_upvalueid (lua_State * L, int fidx, int n)
Definition at line 1267 of file lua-5.3.6/src/lapi.c.
{
  StkId fi = index2addr(L, fidx);
  switch (ttype(fi)) {
    case LUA_TLCL: {  /* lua closure */
      return *getupvalref(L, fidx, n);
    }
    case LUA_TCCL: {  /* C closure */
      CClosure *f = clCvalue(fi);
      api_check(L, 1 <= n && n <= f->nupvalues, "invalid upvalue index");
      return &f->upvalue[n - 1];
    }
    default: {
      api_check(L, 0, "closure expected");
      return NULL;
    }
  }
}
References api_check, clCvalue, getupvalref(), index2addr(), LUA_TCCL, LUA_TLCL, NULL, ttype, and CClosure::upvalue.
lua_upvaluejoin()
LUA_API void lua_upvaluejoin (lua_State * L, int fidx1, int n1, int fidx2, int n2)
Definition at line 1286 of file lua-5.3.6/src/lapi.c.
{
  UpVal **up1 = getupvalref(L, fidx1, n1);
  UpVal **up2 = getupvalref(L, fidx2, n2);
  if (*up1 == *up2)
    return;
  luaC_upvdeccount(L, *up1);
  *up1 = *up2;
  (*up1)->refcount++;
  if (upisopen(*up1)) (*up1)->u.open.touched = 1;
  luaC_upvalbarrier(L, *up1);
}
References getupvalref(), luaC_upvalbarrier, luaC_upvdeccount(), UpVal::refcount, and upisopen.
lua_version()
LUA_API const lua_Number * lua_version (lua_State * L)
Definition at line 144 of file lua-5.3.6/src/lapi.c.
{
  static const lua_Number version = LUA_VERSION_NUM;
  if (L == NULL) return &version;
  else return G(L)->version;
}
References G, LUA_VERSION_NUM, and NULL.
lua_xmove()
LUA_API void lua_xmove (lua_State * from, lua_State * to, int n)
Definition at line 118 of file lua-5.3.6/src/lapi.c.
{
  int i;
  if (from == to) return;
  lua_lock(to);
  api_checknelems(from, n);
  api_check(from, G(from) == G(to), "moving among independent states");
  api_check(from, to->ci->top - to->top >= n, "stack overflow");
  from->top -= n;
  for (i = 0; i < n; i++) {
    setobj2s(to, to->top, from->top + i);
    to->top++;  /* stack already checked by previous 'api_check' */
  }
  lua_unlock(to);
}
References api_check, api_checknelems, lua_State::ci, G, lua_lock, lua_unlock, setobj2s, CallInfo::top, and lua_State::top.
reverse()
static void reverse (lua_State * L, StkId from, StkId to) static
Definition at line 193 of file lua-5.3.6/src/lapi.c.
{
  for (; from < to; from++, to--) {
    TValue temp;
    setobj(L, &temp, from);
    setobjs2s(L, from, to);
    setobj2s(L, to, &temp);
  }
}
References setobj, setobj2s, and setobjs2s.
Referenced by lua_rotate().
Variable Documentation
lua_ident
const char lua_ident[]
Initial value:
=
  "$LuaVersion: " LUA_COPYRIGHT " $"
  "$LuaAuthors: " LUA_AUTHORS " $"
Definition at line 34 of file lua-5.3.6/src/lapi.c.