Github User Fetcher: lfunc.h File Reference
lfunc.h File Reference
#include "lobject.h"
Macros
#define sizeCclosure(n)
#define sizeLclosure(n)
#define isintwups(L) (L->twups != L)
#define MAXUPVAL 255
#define upisopen(up) ((up)->v != &(up)->u.value)
#define uplevel(up) check_exp(upisopen(up), cast(StkId, (up)->v))
#define MAXMISS 10
#define CLOSEKTOP (-1)
Functions
LUAI_FUNC Proto * luaF_newproto (lua_State *L)
LUAI_FUNC CClosure * luaF_newCclosure (lua_State *L, int nupvals)
LUAI_FUNC LClosure * luaF_newLclosure (lua_State *L, int nupvals)
LUAI_FUNC void luaF_initupvals (lua_State *L, LClosure *cl)
LUAI_FUNC UpVal * luaF_findupval (lua_State *L, StkId level)
LUAI_FUNC void luaF_newtbcupval (lua_State *L, StkId level)
LUAI_FUNC void luaF_closeupval (lua_State *L, StkId level)
LUAI_FUNC void luaF_close (lua_State *L, StkId level, int status, int yy)
LUAI_FUNC void luaF_unlinkupval (UpVal *uv)
LUAI_FUNC void luaF_freeproto (lua_State *L, Proto *f)
LUAI_FUNC const char * luaF_getlocalname (const Proto *func, int local_number, int pc)
Macro Definition Documentation
CLOSEKTOP
#define CLOSEKTOP (-1)
Definition at line 47 of file lua-5.4.3/src/lfunc.h.
Referenced by lua_closeslot(), lua_settop(), luaV_execute(), moveresults(), and prepcallclosemth().
isintwups
#define isintwups (L) (L->twups != L)
Definition at line 22 of file lua-5.4.3/src/lfunc.h.
MAXMISS
#define MAXMISS 10
Definition at line 42 of file lua-5.4.3/src/lfunc.h.
MAXUPVAL
#define MAXUPVAL 255
Definition at line 29 of file lua-5.4.3/src/lfunc.h.
sizeCclosure
#define sizeCclosure (n)
Value:
                         (cast_int(offsetof(CClosure, upvalue)) + \
                         cast_int(sizeof(TValue)) * (n))
Definition at line 14 of file lua-5.4.3/src/lfunc.h.
#define sizeCclosure(n) (cast_int(offsetof(CClosure, upvalue)) + \
                         cast_int(sizeof(TValue)) * (n))
sizeLclosure
#define sizeLclosure (n)
Value:
                         (cast_int(offsetof(LClosure, upvals)) + \
                         cast_int(sizeof(TValue *)) * (n))
Definition at line 17 of file lua-5.4.3/src/lfunc.h.
#define sizeLclosure(n) (cast_int(offsetof(LClosure, upvals)) + \
                         cast_int(sizeof(TValue *)) * (n))
upisopen
#define upisopen (up) ((up)->v != &(up)->u.value)
Definition at line 32 of file lua-5.4.3/src/lfunc.h.
uplevel
#define uplevel (up) check_exp(upisopen(up), cast(StkId, (up)->v))
Definition at line 35 of file lua-5.4.3/src/lfunc.h.
Referenced by correctstack(), luaF_closeupval(), and luaF_findupval().
Function Documentation
luaF_close()
LUAI_FUNC void luaF_close (lua_State * L, StkId level, int status, int yy)
Definition at line 228 of file lua-5.4.3/src/lfunc.c.
{
  ptrdiff_t levelrel = savestack(L, level);
  luaF_closeupval(L, level);  /* first, close the upvalues */
  while (L->tbclist >= level) {  /* traverse tbc's down to that level */
    StkId tbc = L->tbclist;  /* get variable index */
    poptbclist(L);  /* remove it from list */
    prepcallclosemth(L, tbc, status, yy);  /* close variable */
    level = restorestack(L, levelrel);
  }
}
References luaF_closeupval(), poptbclist(), prepcallclosemth(), restorestack, savestack, and lua_State::tbclist.
luaF_closeupval()
LUAI_FUNC void luaF_closeupval (lua_State * L, StkId level)
Definition at line 194 of file lua-5.4.3/src/lfunc.c.
{
  UpVal *uv;
  StkId upl;  /* stack index pointed by 'uv' */
  while ((uv = L->openupval) != NULL && (upl = uplevel(uv)) >= level) {
    TValue *slot = &uv->u.value;  /* new position for value */
    lua_assert(uplevel(uv) < L->top);
    luaF_unlinkupval(uv);  /* remove upvalue from 'openupval' list */
    setobj(L, slot, uv->v);  /* move value to upvalue slot */
    uv->v = slot;  /* now current value lives here */
    if (!iswhite(uv)) {  /* neither white nor dead? */
      nw2black(uv);  /* closed upvalues cannot be gray */
      luaC_barrier(L, uv, slot);
    }
  }
}
References iswhite, lua_assert, luaC_barrier, luaF_unlinkupval(), NULL, nw2black, lua_State::openupval, setobj, lua_State::top, UpVal::u, uplevel, UpVal::v, and UpVal::value.
Referenced by luaE_freethread(), luaF_close(), and luaV_execute().
luaF_findupval()
LUAI_FUNC UpVal * luaF_findupval (lua_State * L, StkId level)
Definition at line 53 of file lua-5.1.5/src/lfunc.c.
{
  global_State *g = G(L);
  GCObject **pp = &L->openupval;
  UpVal *p;
  UpVal *uv;
  while (*pp != NULL && (p = ngcotouv(*pp))->v >= level) {
    lua_assert(p->v != &p->u.value);
    if (p->v == level) {  /* found a corresponding upvalue? */
      if (isdead(g, obj2gco(p)))  /* is it dead? */
        changewhite(obj2gco(p));  /* ressurect it */
      return p;
    }
    pp = &p->next;
  }
  uv = luaM_new(L, UpVal);  /* not found: create a new one */
  uv->tt = LUA_TUPVAL;
  uv->marked = luaC_white(g);
  uv->v = level;  /* current value lives in the stack */
  uv->next = *pp;  /* chain it in the proper position */
  *pp = obj2gco(uv);
  uv->u.l.prev = &g->uvhead;  /* double link it in `uvhead' list */
  uv->u.l.next = g->uvhead.u.l.next;
  uv->u.l.next->u.l.prev = uv;
  g->uvhead.u.l.next = uv;
  lua_assert(uv->u.l.next->u.l.prev == uv && uv->u.l.prev->u.l.next == uv);
  return uv;
}
References changewhite, G, gco2uv, isdead, isintwups, isold, UpVal::l, lua_assert, LUA_TUPVAL, luaC_newobj(), luaC_white, luaM_new, newupval(), UpVal::next, ngcotouv, NULL, obj2gco, UpVal::open, lua_State::openupval, UpVal::prev, UpVal::refcount, UpVal::touched, lua_State::twups, UpVal::u, upisopen, uplevel, GCObject::uv, global_State::uvhead, UpVal::v, and UpVal::value.
Referenced by luaV_execute(), pushclosure(), pushclosure(), and pushclosure().
luaF_freeproto()
LUAI_FUNC void luaF_freeproto (lua_State * L, Proto * f)
Definition at line 141 of file lua-5.1.5/src/lfunc.c.
{
  luaM_freearray(L, f->code, f->sizecode, Instruction);
  luaM_freearray(L, f->p, f->sizep, Proto *);
  luaM_freearray(L, f->k, f->sizek, TValue);
  luaM_freearray(L, f->lineinfo, f->sizelineinfo, int);
  luaM_freearray(L, f->locvars, f->sizelocvars, struct LocVar);
  luaM_freearray(L, f->upvalues, f->sizeupvalues, TString *);
  luaM_free(L, f);
}
References Proto::abslineinfo, Proto::code, Proto::k, Proto::lineinfo, Proto::locvars, luaM_free, luaM_freearray, Proto::p, Proto::sizeabslineinfo, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, and Proto::upvalues.
Referenced by freeobj(), freeobj(), freeobj(), and freeobj().
luaF_getlocalname()
LUAI_FUNC const char * luaF_getlocalname (const Proto * func, int local_number, int pc)
Definition at line 163 of file lua-5.1.5/src/lfunc.c.
{
  int i;
  for (i = 0; i<f->sizelocvars && f->locvars[i].startpc <= pc; i++) {
    if (pc < f->locvars[i].endpc) {  /* is variable active? */
      local_number--;
      if (local_number == 0)
        return getstr(f->locvars[i].varname);
    }
  }
  return NULL;  /* not found */
}
References getstr, Proto::locvars, NULL, Proto::sizelocvars, LocVar::startpc, and LocVar::varname.
Referenced by findlocal(), findlocal(), findlocal(), getobjname(), getobjname(), getobjname(), getobjname(), lua_getlocal(), and luaG_findlocal().
luaF_initupvals()
LUAI_FUNC void luaF_initupvals (lua_State * L, LClosure * cl)
Definition at line 45 of file lua-5.3.6/src/lfunc.c.
{
  int i;
  for (i = 0; i < cl->nupvalues; i++) {
    UpVal *uv = luaM_new(L, UpVal);
    uv->refcount = 1;
    uv->v = &uv->u.value;  /* make it closed */
    setnilvalue(uv->v);
    cl->upvals[i] = uv;
  }
}
References gco2upv, LUA_VUPVAL, luaC_newobj(), luaC_objbarrier, luaM_new, UpVal::refcount, setnilvalue, UpVal::u, LClosure::upvals, UpVal::v, and UpVal::value.
Referenced by f_parser(), and f_parser().
luaF_newCclosure()
LUAI_FUNC CClosure * luaF_newCclosure (lua_State * L, int nupvals)
Definition at line 23 of file lua-5.2.4/src/lfunc.c.
{
  Closure *c = &luaC_newobj(L, LUA_TCCL, sizeCclosure(n), NULL, 0)->cl;
  c->c.nupvalues = cast_byte(n);
  return c;
}
References Closure::c, cast_byte, GCObject::cl, gco2ccl, LUA_TCCL, LUA_VCCL, luaC_newobj(), NULL, and sizeCclosure.
luaF_newLclosure()
LUAI_FUNC LClosure * luaF_newLclosure (lua_State * L, int nupvals)
Definition at line 30 of file lua-5.2.4/src/lfunc.c.
{
  Closure *c = &luaC_newobj(L, LUA_TLCL, sizeLclosure(n), NULL, 0)->cl;
  c->l.p = NULL;
  c->l.nupvalues = cast_byte(n);
  while (n--) c->l.upvals[n] = NULL;
  return c;
}
References cast_byte, GCObject::cl, gco2lcl, Closure::l, LUA_TLCL, LUA_VLCL, luaC_newobj(), NULL, LClosure::p, sizeLclosure, and LClosure::upvals.
luaF_newproto()
LUAI_FUNC Proto * luaF_newproto (lua_State * L)
Definition at line 115 of file lua-5.1.5/src/lfunc.c.
{
  Proto *f = luaM_new(L, Proto);
  luaC_link(L, obj2gco(f), LUA_TPROTO);
  f->k = NULL;
  f->sizek = 0;
  f->p = NULL;
  f->sizep = 0;
  f->code = NULL;
  f->sizecode = 0;
  f->sizelineinfo = 0;
  f->sizeupvalues = 0;
  f->nups = 0;
  f->upvalues = NULL;
  f->numparams = 0;
  f->is_vararg = 0;
  f->maxstacksize = 0;
  f->lineinfo = NULL;
  f->sizelocvars = 0;
  f->locvars = NULL;
  f->linedefined = 0;
  f->lastlinedefined = 0;
  f->source = NULL;
  return f;
}
References Proto::abslineinfo, Proto::cache, Proto::code, gco2p, Proto::is_vararg, Proto::k, Proto::lastlinedefined, Proto::linedefined, Proto::lineinfo, Proto::locvars, LUA_TPROTO, LUA_VPROTO, luaC_link(), luaC_newobj(), luaM_new, Proto::maxstacksize, NULL, Proto::numparams, Proto::nups, obj2gco, Proto::p, GCObject::p, Proto::sizeabslineinfo, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, and Proto::upvalues.
Referenced by addprototype(), addprototype(), addprototype(), combine(), LoadConstants(), LoadFunction(), LoadProtos(), loadProtos(), luaU_undump(), luaU_undump(), luaY_parser(), and open_func().
luaF_newtbcupval()
LUAI_FUNC void luaF_newtbcupval (lua_State * L, StkId level)
Definition at line 169 of file lua-5.4.3/src/lfunc.c.
{
  lua_assert(level > L->tbclist);
  if (l_isfalse(s2v(level)))
    return;  /* false doesn't need to be closed */
  checkclosemth(L, level);  /* value must have a close method */
  while (cast_uint(level - L->tbclist) > MAXDELTA) {
    L->tbclist += MAXDELTA;  /* create a dummy node at maximum delta */
    L->tbclist->tbclist.delta = 0;
  }
  level->tbclist.delta = cast(unsigned short, level - L->tbclist);
  L->tbclist = level;
}
References cast, cast_uint, checkclosemth(), l_isfalse, lua_assert, MAXDELTA, s2v, and lua_State::tbclist.
Referenced by lua_toclose(), and luaV_execute().
luaF_unlinkupval()
LUAI_FUNC void luaF_unlinkupval (UpVal * uv)
Definition at line 183 of file lua-5.4.3/src/lfunc.c.
{
  lua_assert(upisopen(uv));
  *uv->u.open.previous = uv->u.open.next;
  if (uv->u.open.next)
    uv->u.open.next->u.open.previous = uv->u.open.previous;
}
References lua_assert, UpVal::next, UpVal::open, UpVal::previous, UpVal::u, and upisopen.
Referenced by freeupval(), and luaF_closeupval().