Github User Fetcher: llex.h File Reference
llex.h File Reference
#include "lobject.h"
#include "lzio.h"
Data Structures
union SemInfo
struct Token
struct LexState
Macros
#define FIRST_RESERVED 257
#define TOKEN_LEN (sizeof("function")/sizeof(char))
#define NUM_RESERVED (cast(int, TK_WHILE-FIRST_RESERVED+1))
Typedefs
typedef struct Token Token
typedef struct LexState LexState
Enumerations
enum RESERVED {
TK_AND = FIRST_RESERVED , TK_BREAK , TK_DO , TK_ELSE ,
TK_ELSEIF , TK_END , TK_FALSE , TK_FOR ,
TK_FUNCTION , TK_IF , TK_IN , TK_LOCAL ,
TK_NIL , TK_NOT , TK_OR , TK_REPEAT ,
TK_RETURN , TK_THEN , TK_TRUE , TK_UNTIL ,
TK_WHILE , TK_CONCAT , TK_DOTS , TK_EQ ,
TK_GE , TK_LE , TK_NE , TK_NUMBER ,
TK_NAME , TK_STRING , TK_EOS
}
Functions
LUAI_FUNC void luaX_init (lua_State *L)
LUAI_FUNC void luaX_setinput (lua_State *L, LexState *ls, ZIO *z, TString *source)
LUAI_FUNC TString * luaX_newstring (LexState *ls, const char *str, size_t l)
LUAI_FUNC void luaX_next (LexState *ls)
LUAI_FUNC void luaX_lookahead (LexState *ls)
LUAI_FUNC void luaX_lexerror (LexState *ls, const char *msg, int token)
LUAI_FUNC void luaX_syntaxerror (LexState *ls, const char *s)
LUAI_FUNC const char * luaX_token2str (LexState *ls, int token)
Variables
LUAI_DATA const char *const luaX_tokens []
Macro Definition Documentation
FIRST_RESERVED
#define FIRST_RESERVED 257
Definition at line 14 of file lua-5.1.5/src/llex.h.
Referenced by llex(), llex(), llex(), llex(), and luaX_token2str().
NUM_RESERVED
#define NUM_RESERVED (cast(int, TK_WHILE-FIRST_RESERVED+1))
Definition at line 36 of file lua-5.1.5/src/llex.h.
Referenced by luaX_init().
TOKEN_LEN
#define TOKEN_LEN (sizeof("function")/sizeof(char))
Definition at line 17 of file lua-5.1.5/src/llex.h.
Referenced by luaX_init().
Typedef Documentation
LexState
typedef struct LexState LexState
Token
typedef struct Token Token
Enumeration Type Documentation
RESERVED
enum RESERVED
Enumerator
TK_AND
TK_BREAK
TK_DO
TK_ELSE
TK_ELSEIF
TK_END
TK_FALSE
TK_FOR
TK_FUNCTION
TK_IF
TK_IN
TK_LOCAL
TK_NIL
TK_NOT
TK_OR
TK_REPEAT
TK_RETURN
TK_THEN
TK_TRUE
TK_UNTIL
TK_WHILE
TK_CONCAT
TK_DOTS
TK_EQ
TK_GE
TK_LE
TK_NE
TK_NUMBER
TK_NAME
TK_STRING
TK_EOS
Definition at line 24 of file lua-5.1.5/src/llex.h.
              {
  /* terminal symbols denoted by reserved words */
  TK_AND = FIRST_RESERVED, TK_BREAK,
  TK_DO, TK_ELSE, TK_ELSEIF, TK_END, TK_FALSE, TK_FOR, TK_FUNCTION,
  TK_IF, TK_IN, TK_LOCAL, TK_NIL, TK_NOT, TK_OR, TK_REPEAT,
  TK_RETURN, TK_THEN, TK_TRUE, TK_UNTIL, TK_WHILE,
  /* other terminal symbols */
  TK_CONCAT, TK_DOTS, TK_EQ, TK_GE, TK_LE, TK_NE, TK_NUMBER,
  TK_NAME, TK_STRING, TK_EOS
};
Function Documentation
luaX_init()
LUAI_FUNC void luaX_init (lua_State * L)
Definition at line 21 of file noparser.c.
{
  UNUSED(L);
}
luaX_lexerror()
LUAI_FUNC void luaX_lexerror (LexState * ls, const char * msg, int token)
Definition at line 102 of file lua-5.1.5/src/llex.c.
{
  char buff[MAXSRC];
  luaO_chunkid(buff, getstr(ls->source), MAXSRC);
  msg = luaO_pushfstring(ls->L, "%s:%d: %s", buff, ls->linenumber, msg);
  if (token)
    luaO_pushfstring(ls->L, "%s near " LUA_QS, msg, txtToken(ls, token));
  luaD_throw(ls->L, LUA_ERRSYNTAX);
}
References getstr, LexState::L, LexState::linenumber, LUA_ERRSYNTAX, LUA_QS, luaD_throw(), luaO_chunkid(), luaO_pushfstring(), MAXSRC, LexState::source, and txtToken().
Referenced by enterlevel(), errorlimit(), llex(), luaX_syntaxerror(), read_long_string(), read_string(), save(), and trydecpoint().
luaX_lookahead()
LUAI_FUNC void luaX_lookahead (LexState * ls)
Definition at line 459 of file lua-5.1.5/src/llex.c.
{
  lua_assert(ls->lookahead.token == TK_EOS);
  ls->lookahead.token = llex(ls, &ls->lookahead.seminfo);
}
luaX_newstring()
LUAI_FUNC TString * luaX_newstring (LexState * ls, const char * str, size_t l)
Definition at line 117 of file lua-5.1.5/src/llex.c.
{
  lua_State *L = ls->L;
  TString *ts = luaS_newlstr(L, str, l);
  TValue *o = luaH_setstr(L, ls->fs->h, ts);  /* entry for `str' */
  if (ttisnil(o)) {
    setbvalue(o, 1);  /* make sure `str' will not be collected */
    luaC_checkGC(L);
  }
  return ts;
}
luaX_next()
LUAI_FUNC void luaX_next (LexState * ls)
Definition at line 448 of file lua-5.1.5/src/llex.c.
{
  ls->lastline = ls->linenumber;
  if (ls->lookahead.token != TK_EOS) {  /* is there a look-ahead token? */
    ls->t = ls->lookahead;  /* use this one */
    ls->lookahead.token = TK_EOS;  /* and discharge it */
  }
  else
    ls->t.token = llex(ls, &ls->t.seminfo);  /* read next token */
}
luaX_setinput()
LUAI_FUNC void luaX_setinput (lua_State * L, LexState * ls, ZIO * z, TString * source)
Definition at line 140 of file lua-5.1.5/src/llex.c.
{
  ls->decpoint = '.';
  ls->L = L;
  ls->lookahead.token = TK_EOS;  /* no look-ahead token */
  ls->z = z;
  ls->fs = NULL;
  ls->linenumber = 1;
  ls->lastline = 1;
  ls->source = source;
  luaZ_resizebuffer(ls->L, ls->buff, LUA_MINBUFFER);  /* initialize buffer */
  next(ls);  /* read first char */
}
References LexState::buff, LexState::decpoint, LexState::fs, LexState::L, LexState::lastline, LexState::linenumber, LexState::lookahead, LUA_MINBUFFER, luaZ_resizebuffer, next, NULL, LexState::source, TK_EOS, Token::token, and LexState::z.
Referenced by luaY_parser(), and luaY_parser().
luaX_syntaxerror()
LUAI_FUNC void luaX_syntaxerror (LexState * ls, const char * s)
Definition at line 112 of file lua-5.1.5/src/llex.c.
{
  luaX_lexerror(ls, msg, ls->t.token);
}
luaX_token2str()
LUAI_FUNC const char * luaX_token2str (LexState * ls, int token)
Definition at line 78 of file lua-5.1.5/src/llex.c.
{
  if (token < FIRST_RESERVED) {
    lua_assert(token == cast(unsigned char, token));
    return (iscntrl(token)) ? luaO_pushfstring(ls->L, "char(%d)", token) :
                              luaO_pushfstring(ls->L, "%c", token);
  }
  else
    return luaX_tokens[token-FIRST_RESERVED];
}
Variable Documentation
luaX_tokens
LUAI_DATA const char* const luaX_tokens[]
Definition at line 40 of file lua-5.1.5/src/llex.h.