Github User Fetcher: lgc.c File Reference
lgc.c File Reference
#include "lprefix.h"
#include <stdio.h>
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
Macros
#define lgc_c
#define LUA_CORE
#define GCSWEEPMAX 100
#define GCFINMAX 10
#define GCFINALIZECOST 50
#define WORK2MEM sizeof(TValue)
#define PAUSEADJ 100
#define maskcolors (bitmask(BLACKBIT) | WHITEBITS)
#define maskgcbits (maskcolors | AGEBITS)
#define makewhite(g, x) (x->marked = cast_byte((x->marked & ~maskcolors) | luaC_white(g)))
#define set2gray(x) resetbits(x->marked, maskcolors)
#define set2black(x) (x->marked = cast_byte((x->marked & ~WHITEBITS) | bitmask(BLACKBIT)))
#define valiswhite(x) (iscollectable(x) && iswhite(gcvalue(x)))
#define keyiswhite(n) (keyiscollectable(n) && iswhite(gckey(n)))
#define gcvalueN(o) (iscollectable(o) ? gcvalue(o) : NULL)
#define markvalue(g, o)
#define markkey(g, n) { if keyiswhite(n) reallymarkobject(g,gckey(n)); }
#define markobject(g, t) { if (iswhite(t)) reallymarkobject(g, obj2gco(t)); }
#define markobjectN(g, t) { if (t) markobject(g,t); }
#define gnodelast(h) gnode(h, cast_sizet(sizenode(h)))
#define linkgclist(o, p) linkgclist_(obj2gco(o), &(o)->gclist, &(p))
#define linkobjgclist(o, p) linkgclist_(obj2gco(o), getgclist(o), &(p))
Functions
static void reallymarkobject (global_State *g, GCObject *o)
static lu_mem atomic (lua_State *L)
static void entersweep (lua_State *L)
static GCObject ** getgclist (GCObject *o)
static void linkgclist_ (GCObject *o, GCObject **pnext, GCObject **list)
static void clearkey (Node *n)
static int iscleared (global_State *g, const GCObject *o)
void luaC_barrier_ (lua_State *L, GCObject *o, GCObject *v)
void luaC_barrierback_ (lua_State *L, GCObject *o)
void luaC_fix (lua_State *L, GCObject *o)
GCObject * luaC_newobj (lua_State *L, int tt, size_t sz)
static void markmt (global_State *g)
static lu_mem markbeingfnz (global_State *g)
static int remarkupvals (global_State *g)
static void cleargraylists (global_State *g)
static void restartcollection (global_State *g)
static void genlink (global_State *g, GCObject *o)
static void traverseweakvalue (global_State *g, Table *h)
static int traverseephemeron (global_State *g, Table *h, int inv)
static void traversestrongtable (global_State *g, Table *h)
static lu_mem traversetable (global_State *g, Table *h)
static int traverseudata (global_State *g, Udata *u)
static int traverseproto (global_State *g, Proto *f)
static int traverseCclosure (global_State *g, CClosure *cl)
static int traverseLclosure (global_State *g, LClosure *cl)
static int traversethread (global_State *g, lua_State *th)
static lu_mem propagatemark (global_State *g)
static lu_mem propagateall (global_State *g)
static void convergeephemerons (global_State *g)
static void clearbykeys (global_State *g, GCObject *l)
static void clearbyvalues (global_State *g, GCObject *l, GCObject *f)
static void freeupval (lua_State *L, UpVal *uv)
static void freeobj (lua_State *L, GCObject *o)
static GCObject ** sweeplist (lua_State *L, GCObject **p, int countin, int *countout)
static GCObject ** sweeptolive (lua_State *L, GCObject **p)
static void checkSizes (lua_State *L, global_State *g)
static GCObject * udata2finalize (global_State *g)
static void dothecall (lua_State *L, void *ud)
static void GCTM (lua_State *L)
static int runafewfinalizers (lua_State *L, int n)
static void callallpendingfinalizers (lua_State *L)
static GCObject ** findlast (GCObject **p)
static void separatetobefnz (global_State *g, int all)
static void checkpointer (GCObject **p, GCObject *o)
static void correctpointers (global_State *g, GCObject *o)
void luaC_checkfinalizer (lua_State *L, GCObject *o, Table *mt)
static void setpause (global_State *g)
static void sweep2old (lua_State *L, GCObject **p)
static GCObject ** sweepgen (lua_State *L, global_State *g, GCObject **p, GCObject *limit, GCObject **pfirstold1)
static void whitelist (global_State *g, GCObject *p)
static GCObject ** correctgraylist (GCObject **p)
static void correctgraylists (global_State *g)
static void markold (global_State *g, GCObject *from, GCObject *to)
static void finishgencycle (lua_State *L, global_State *g)
static void youngcollection (lua_State *L, global_State *g)
static void atomic2gen (lua_State *L, global_State *g)
static lu_mem entergen (lua_State *L, global_State *g)
static void enterinc (global_State *g)
void luaC_changemode (lua_State *L, int newmode)
static lu_mem fullgen (lua_State *L, global_State *g)
static void setminordebt (global_State *g)
static void stepgenfull (lua_State *L, global_State *g)
static void genstep (lua_State *L, global_State *g)
static void deletelist (lua_State *L, GCObject *p, GCObject *limit)
void luaC_freeallobjects (lua_State *L)
static int sweepstep (lua_State *L, global_State *g, int nextstate, GCObject **nextlist)
static lu_mem singlestep (lua_State *L)
void luaC_runtilstate (lua_State *L, int statesmask)
static void incstep (lua_State *L, global_State *g)
void luaC_step (lua_State *L)
static void fullinc (lua_State *L, global_State *g)
void luaC_fullgc (lua_State *L, int isemergency)
Macro Definition Documentation
GCFINALIZECOST
#define GCFINALIZECOST 50
Definition at line 46 of file lua-5.4.3/src/lgc.c.
Referenced by singlestep().
GCFINMAX
#define GCFINMAX 10
Definition at line 40 of file lua-5.4.3/src/lgc.c.
Referenced by singlestep().
GCSWEEPMAX
#define GCSWEEPMAX 100
Definition at line 35 of file lua-5.4.3/src/lgc.c.
Referenced by sweepstep().
gcvalueN
#define gcvalueN (o) (iscollectable(o) ? gcvalue(o) : NULL)
Definition at line 91 of file lua-5.4.3/src/lgc.c.
Referenced by clearbyvalues(), and traverseweakvalue().
gnodelast
#define gnodelast (h) gnode(h, cast_sizet(sizenode(h)))
Definition at line 122 of file lua-5.4.3/src/lgc.c.
Referenced by clearbykeys(), clearbyvalues(), traversestrongtable(), and traverseweakvalue().
keyiswhite
#define keyiswhite (n) (keyiscollectable(n) && iswhite(gckey(n)))
Definition at line 85 of file lua-5.4.3/src/lgc.c.
lgc_c
#define lgc_c
Definition at line 7 of file lua-5.4.3/src/lgc.c.
linkgclist
#define linkgclist (o, p) linkgclist_(obj2gco(o), &(o)->gclist, &(p))
Definition at line 146 of file lua-5.4.3/src/lgc.c.
Referenced by sweep2old(), traverseephemeron(), traversetable(), traversethread(), and traverseweakvalue().
linkobjgclist
#define linkobjgclist (o, p) linkgclist_(obj2gco(o), getgclist(o), &(p))
Definition at line 159 of file lua-5.4.3/src/lgc.c.
Referenced by genlink(), luaC_barrierback_(), and reallymarkobject().
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/lgc.c.
makewhite
#define makewhite (g, x) (x->marked = cast_byte((x->marked & ~maskcolors) | luaC_white(g)))
Definition at line 71 of file lua-5.4.3/src/lgc.c.
#define makewhite(g,x)  \
  (x->marked = cast_byte((x->marked & ~maskcolors) | luaC_white(g)))
Referenced by luaC_barrier_(), luaC_checkfinalizer(), and udata2finalize().
markkey
#define markkey (g, n) { if keyiswhite(n) reallymarkobject(g,gckey(n)); }
Definition at line 97 of file lua-5.4.3/src/lgc.c.
Referenced by traversestrongtable(), and traverseweakvalue().
markobject
#define markobject (g, t) { if (iswhite(t)) reallymarkobject(g, obj2gco(t)); }
Definition at line 99 of file lua-5.4.3/src/lgc.c.
Referenced by atomic(), iscleared(), markbeingfnz(), restartcollection(), and traversethread().
markobjectN
#define markobjectN (g, t) { if (t) markobject(g,t); }
Definition at line 105 of file lua-5.4.3/src/lgc.c.
Referenced by markmt(), reallymarkobject(), traverseLclosure(), traverseproto(), traversetable(), and traverseudata().
markvalue
#define markvalue (g, o)
Value:
  { checkliveness(g->mainthread,o); \
  if (valiswhite(o)) reallymarkobject(g,gcvalue(o)); }
Definition at line 94 of file lua-5.4.3/src/lgc.c.
#define markvalue(g,o) { checkliveness(g->mainthread,o); \
  if (valiswhite(o)) reallymarkobject(g,gcvalue(o)); }
Referenced by atomic(), reallymarkobject(), remarkupvals(), restartcollection(), traverseCclosure(), traverseproto(), traversestrongtable(), traversethread(), and traverseudata().
maskcolors
#define maskcolors (bitmask(BLACKBIT) | WHITEBITS)
Definition at line 64 of file lua-5.4.3/src/lgc.c.
maskgcbits
#define maskgcbits (maskcolors | AGEBITS)
Definition at line 67 of file lua-5.4.3/src/lgc.c.
Referenced by sweeplist(), and whitelist().
PAUSEADJ
#define PAUSEADJ 100
Definition at line 60 of file lua-5.4.3/src/lgc.c.
Referenced by setpause().
set2black
#define set2black (x) (x->marked = cast_byte((x->marked & ~WHITEBITS) | bitmask(BLACKBIT)))
Definition at line 79 of file lua-5.4.3/src/lgc.c.
#define set2black(x)  \
  (x->marked = cast_byte((x->marked & ~WHITEBITS) | bitmask(BLACKBIT)))
Referenced by reallymarkobject().
set2gray
#define set2gray (x) resetbits(x->marked, maskcolors)
Definition at line 75 of file lua-5.4.3/src/lgc.c.
Referenced by linkgclist_(), luaC_barrierback_(), luaC_fix(), reallymarkobject(), and sweep2old().
valiswhite
#define valiswhite (x) (iscollectable(x) && iswhite(gcvalue(x)))
Definition at line 83 of file lua-5.4.3/src/lgc.c.
Referenced by traverseephemeron().
WORK2MEM
#define WORK2MEM sizeof(TValue)
Definition at line 53 of file lua-5.4.3/src/lgc.c.
Referenced by incstep().
Function Documentation
atomic()
static lu_mem atomic (lua_State * L) static
Definition at line 1516 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  lu_mem work = 0;
  GCObject *origweak, *origall;
  GCObject *grayagain = g->grayagain;  /* save original list */
  g->grayagain = NULL;
  lua_assert(g->ephemeron == NULL && g->weak == NULL);
  lua_assert(!iswhite(g->mainthread));
  g->gcstate = GCSatomic;
  markobject(g, L);  /* mark running thread */
  /* registry and global metatables may be changed by API */
  markvalue(g, &g->l_registry);
  markmt(g);  /* mark global metatables */
  work += propagateall(g);  /* empties 'gray' list */
  /* remark occasional upvalues of (maybe) dead threads */
  work += remarkupvals(g);
  work += propagateall(g);  /* propagate changes */
  g->gray = grayagain;
  work += propagateall(g);  /* traverse 'grayagain' list */
  convergeephemerons(g);
  /* at this point, all strongly accessible objects are marked. */
  /* Clear values from weak tables, before checking finalizers */
  clearbyvalues(g, g->weak, NULL);
  clearbyvalues(g, g->allweak, NULL);
  origweak = g->weak; origall = g->allweak;
  separatetobefnz(g, 0);  /* separate objects to be finalized */
  work += markbeingfnz(g);  /* mark objects that will be finalized */
  work += propagateall(g);  /* remark, to propagate 'resurrection' */
  convergeephemerons(g);
  /* at this point, all resurrected objects are marked. */
  /* remove dead objects from weak tables */
  clearbykeys(g, g->ephemeron);  /* clear keys from all ephemeron tables */
  clearbykeys(g, g->allweak);  /* clear keys from all 'allweak' tables */
  /* clear values from resurrected weak tables */
  clearbyvalues(g, g->weak, origweak);
  clearbyvalues(g, g->allweak, origall);
  luaS_clearcache(g);
  g->currentwhite = cast_byte(otherwhite(g));  /* flip current white */
  lua_assert(g->gray == NULL);
  return work;  /* estimate of slots marked by 'atomic' */
}
References global_State::allweak, cast_byte, clearbykeys(), clearbyvalues(), convergeephemerons(), global_State::currentwhite, global_State::ephemeron, G, GCSatomic, global_State::gcstate, global_State::gray, global_State::grayagain, iswhite, global_State::l_registry, lua_assert, luaS_clearcache(), global_State::mainthread, markbeingfnz(), markmt(), markobject, markvalue, NULL, otherwhite, propagateall(), remarkupvals(), separatetobefnz(), and global_State::weak.
Referenced by entergen(), singlestep(), stepgenfull(), and youngcollection().
atomic2gen()
static void atomic2gen (lua_State * L, global_State * g) static
Definition at line 1265 of file lua-5.4.3/src/lgc.c.
{
  cleargraylists(g);
  /* sweep all elements making them old */
  g->gcstate = GCSswpallgc;
  sweep2old(L, &g->allgc);
  /* everything alive now is old */
  g->reallyold = g->old1 = g->survival = g->allgc;
  g->firstold1 = NULL;  /* there are no OLD1 objects anywhere */
  /* repeat for 'finobj' lists */
  sweep2old(L, &g->finobj);
  g->finobjrold = g->finobjold1 = g->finobjsur = g->finobj;
  sweep2old(L, &g->tobefnz);
  g->gckind = KGC_GEN;
  g->lastatomic = 0;
  g->GCestimate = gettotalbytes(g);  /* base for memory control */
  finishgencycle(L, g);
}
References global_State::allgc, cleargraylists(), finishgencycle(), global_State::finobj, global_State::finobjold1, global_State::finobjrold, global_State::finobjsur, global_State::firstold1, global_State::GCestimate, global_State::gckind, GCSswpallgc, global_State::gcstate, gettotalbytes, KGC_GEN, global_State::lastatomic, NULL, global_State::old1, global_State::reallyold, global_State::survival, sweep2old(), and global_State::tobefnz.
Referenced by entergen(), and stepgenfull().
callallpendingfinalizers()
static void callallpendingfinalizers (lua_State * L) static
Definition at line 942 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  while (g->tobefnz)
    GCTM(L);
}
References G, GCTM(), and global_State::tobefnz.
Referenced by finishgencycle(), and luaC_freeallobjects().
checkpointer()
static void checkpointer (GCObject ** p, GCObject * o) static
Definition at line 989 of file lua-5.4.3/src/lgc.c.
{
  if (o == *p)
    *p = o->next;
}
Referenced by correctpointers().
checkSizes()
static void checkSizes (lua_State * L, global_State * g) static
Definition at line 863 of file lua-5.4.3/src/lgc.c.
{
  if (!g->gcemergency) {
    if (g->strt.nuse < g->strt.size / 4) {  /* string table too big? */
      l_mem olddebt = g->GCdebt;
      luaS_resize(L, g->strt.size / 2);
      g->GCestimate += g->GCdebt - olddebt;  /* correct estimate */
    }
  }
}
References global_State::GCdebt, global_State::gcemergency, global_State::GCestimate, luaS_resize(), stringtable::nuse, stringtable::size, and global_State::strt.
Referenced by finishgencycle(), and singlestep().
clearbykeys()
static void clearbykeys (global_State * g, GCObject * l) static
Definition at line 717 of file lua-5.4.3/src/lgc.c.
{
  for (; l; l = gco2t(l)->gclist) {
    Table *h = gco2t(l);
    Node *limit = gnodelast(h);
    Node *n;
    for (n = gnode(h, 0); n < limit; n++) {
      if (iscleared(g, gckeyN(n)))  /* unmarked key? */
        setempty(gval(n));  /* remove entry */
      if (isempty(gval(n)))  /* is entry empty? */
        clearkey(n);  /* clear its key */
    }
  }
}
References clearkey(), gckeyN, gco2t, gnode, gnodelast, gval, iscleared(), isempty, and setempty.
Referenced by atomic().
clearbyvalues()
static void clearbyvalues (global_State * g, GCObject * l, GCObject * f) static
Definition at line 736 of file lua-5.4.3/src/lgc.c.
{
  for (; l != f; l = gco2t(l)->gclist) {
    Table *h = gco2t(l);
    Node *n, *limit = gnodelast(h);
    unsigned int i;
    unsigned int asize = luaH_realasize(h);
    for (i = 0; i < asize; i++) {
      TValue *o = &h->array[i];
      if (iscleared(g, gcvalueN(o)))  /* value was collected? */
        setempty(o);  /* remove entry */
    }
    for (n = gnode(h, 0); n < limit; n++) {
      if (iscleared(g, gcvalueN(gval(n))))  /* unmarked value? */
        setempty(gval(n));  /* remove entry */
      if (isempty(gval(n)))  /* is entry empty? */
        clearkey(n);  /* clear its key */
    }
  }
}
References Table::array, clearkey(), gco2t, gcvalueN, gnode, gnodelast, gval, iscleared(), isempty, luaH_realasize(), and setempty.
Referenced by atomic().
cleargraylists()
static void cleargraylists (global_State * g) static
Definition at line 388 of file lua-5.4.3/src/lgc.c.
{
  g->gray = g->grayagain = NULL;
  g->weak = g->allweak = g->ephemeron = NULL;
}
References global_State::allweak, global_State::ephemeron, global_State::gray, global_State::grayagain, NULL, and global_State::weak.
Referenced by atomic2gen(), and restartcollection().
clearkey()
static void clearkey (Node * n) static
Definition at line 171 of file lua-5.4.3/src/lgc.c.
{
  lua_assert(isempty(gval(n)));
  if (keyiscollectable(n))
    setdeadkey(n);  /* unused key; remove it */
}
References gval, isempty, keyiscollectable, lua_assert, and setdeadkey.
Referenced by clearbykeys(), clearbyvalues(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
convergeephemerons()
static void convergeephemerons (global_State * g) static
Definition at line 683 of file lua-5.4.3/src/lgc.c.
{
  int changed;
  int dir = 0;
  do {
    GCObject *w;
    GCObject *next = g->ephemeron;  /* get ephemeron list */
    g->ephemeron = NULL;  /* tables may return to this list when traversed */
    changed = 0;
    while ((w = next) != NULL) {  /* for each ephemeron table */
      Table *h = gco2t(w);
      next = h->gclist;  /* list is rebuilt during loop */
      nw2black(h);  /* out of the list (for now) */
      if (traverseephemeron(g, h, dir)) {  /* marked some value? */
        propagateall(g);  /* propagate changes */
        changed = 1;  /* will have to revisit all ephemeron tables */
      }
    }
    dir = !dir;  /* invert direction next time */
  } while (changed);  /* repeat until no more changes */
}
References global_State::ephemeron, Table::gclist, gco2t, next, NULL, nw2black, propagateall(), and traverseephemeron().
Referenced by atomic().
correctgraylist()
static GCObject ** correctgraylist (GCObject ** p) static
Definition at line 1145 of file lua-5.4.3/src/lgc.c.
{
  GCObject *curr;
  while ((curr = *p) != NULL) {
    GCObject **next = getgclist(curr);
    if (iswhite(curr))
      goto remove;  /* remove all white objects */
    else if (getage(curr) == G_TOUCHED1) {  /* touched in this cycle? */
      lua_assert(isgray(curr));
      nw2black(curr);  /* make it black, for next barrier */
      changeage(curr, G_TOUCHED1, G_TOUCHED2);
      goto remain;  /* keep it in the list and go to next element */
    }
    else if (curr->tt == LUA_VTHREAD) {
      lua_assert(isgray(curr));
      goto remain;  /* keep non-white threads on the list */
    }
    else {  /* everything else is removed */
      lua_assert(isold(curr));  /* young objects should be white here */
      if (getage(curr) == G_TOUCHED2)  /* advance from TOUCHED2... */
        changeage(curr, G_TOUCHED2, G_OLD);  /* ... to OLD */
      nw2black(curr);  /* make object black (to be removed) */
      goto remove;
    }
    remove: *p = *next; continue;
    remain: p = next; continue;
  }
  return p;
}
References changeage, G_OLD, G_TOUCHED1, G_TOUCHED2, getage, getgclist(), isgray, isold, iswhite, lua_assert, LUA_VTHREAD, next, NULL, and nw2black.
Referenced by correctgraylists().
correctgraylists()
static void correctgraylists (global_State * g) static
Definition at line 1178 of file lua-5.4.3/src/lgc.c.
{
  GCObject **list = correctgraylist(&g->grayagain);
  *list = g->weak; g->weak = NULL;
  list = correctgraylist(list);
  *list = g->allweak; g->allweak = NULL;
  list = correctgraylist(list);
  *list = g->ephemeron; g->ephemeron = NULL;
  correctgraylist(list);
}
References global_State::allweak, correctgraylist(), global_State::ephemeron, global_State::grayagain, NULL, and global_State::weak.
Referenced by finishgencycle().
correctpointers()
static void correctpointers (global_State * g, GCObject * o) static
Definition at line 999 of file lua-5.4.3/src/lgc.c.
{
  checkpointer(&g->survival, o);
  checkpointer(&g->old1, o);
  checkpointer(&g->reallyold, o);
  checkpointer(&g->firstold1, o);
}
References checkpointer(), global_State::firstold1, global_State::old1, global_State::reallyold, and global_State::survival.
Referenced by luaC_checkfinalizer().
deletelist()
static void deletelist (lua_State * L, GCObject * p, GCObject * limit) static
Definition at line 1490 of file lua-5.4.3/src/lgc.c.
{
  while (p != limit) {
    GCObject *next = p->next;
    freeobj(L, p);
    p = next;
  }
}
References freeobj(), and next.
Referenced by luaC_freeallobjects().
dothecall()
static void dothecall (lua_State * L, void * ud) static
Definition at line 893 of file lua-5.4.3/src/lgc.c.
{
  UNUSED(ud);
  luaD_callnoyield(L, L->top - 2, 0);
}
References luaD_callnoyield(), lua_State::top, and UNUSED.
Referenced by GCTM().
entergen()
static lu_mem entergen (lua_State * L, global_State * g) static
Definition at line 1293 of file lua-5.4.3/src/lgc.c.
{
  lu_mem numobjs;
  luaC_runtilstate(L, bitmask(GCSpause));  /* prepare to start a new cycle */
  luaC_runtilstate(L, bitmask(GCSpropagate));  /* start new cycle */
  numobjs = atomic(L);  /* propagates all and then do the atomic stuff */
  atomic2gen(L, g);
  return numobjs;
}
References atomic(), atomic2gen(), bitmask, GCSpause, GCSpropagate, and luaC_runtilstate().
Referenced by fullgen(), and luaC_changemode().
enterinc()
static void enterinc (global_State * g) static
Definition at line 1308 of file lua-5.4.3/src/lgc.c.
{
  whitelist(g, g->allgc);
  g->reallyold = g->old1 = g->survival = NULL;
  whitelist(g, g->finobj);
  whitelist(g, g->tobefnz);
  g->finobjrold = g->finobjold1 = g->finobjsur = NULL;
  g->gcstate = GCSpause;
  g->gckind = KGC_INC;
  g->lastatomic = 0;
}
References global_State::allgc, global_State::finobj, global_State::finobjold1, global_State::finobjrold, global_State::finobjsur, global_State::gckind, GCSpause, global_State::gcstate, KGC_INC, global_State::lastatomic, NULL, global_State::old1, global_State::reallyold, global_State::survival, global_State::tobefnz, and whitelist().
Referenced by fullgen(), luaC_changemode(), and stepgenfull().
entersweep()
static void entersweep (lua_State * L) static
Definition at line 1478 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  g->gcstate = GCSswpallgc;
  lua_assert(g->sweepgc == NULL);
  g->sweepgc = sweeptolive(L, &g->allgc);
}
References global_State::allgc, G, GCSswpallgc, global_State::gcstate, lua_assert, NULL, global_State::sweepgc, and sweeptolive().
Referenced by fullinc(), singlestep(), and stepgenfull().
findlast()
static GCObject ** findlast (GCObject ** p) static
Definition at line 952 of file lua-5.4.3/src/lgc.c.
{
  while (*p != NULL)
    p = &(*p)->next;
  return p;
}
References NULL.
Referenced by separatetobefnz().
finishgencycle()
static void finishgencycle (lua_State * L, global_State * g) static
Definition at line 1210 of file lua-5.4.3/src/lgc.c.
{
  correctgraylists(g);
  checkSizes(L, g);
  g->gcstate = GCSpropagate;  /* skip restart */
  if (!g->gcemergency)
    callallpendingfinalizers(L);
}
References callallpendingfinalizers(), checkSizes(), correctgraylists(), global_State::gcemergency, GCSpropagate, and global_State::gcstate.
Referenced by atomic2gen(), and youngcollection().
freeobj()
static void freeobj (lua_State * L, GCObject * o) static
Definition at line 764 of file lua-5.4.3/src/lgc.c.
{
  switch (o->tt) {
    case LUA_VPROTO:
      luaF_freeproto(L, gco2p(o));
      break;
    case LUA_VUPVAL:
      freeupval(L, gco2upv(o));
      break;
    case LUA_VLCL: {
      LClosure *cl = gco2lcl(o);
      luaM_freemem(L, cl, sizeLclosure(cl->nupvalues));
      break;
    }
    case LUA_VCCL: {
      CClosure *cl = gco2ccl(o);
      luaM_freemem(L, cl, sizeCclosure(cl->nupvalues));
      break;
    }
    case LUA_VTABLE:
      luaH_free(L, gco2t(o));
      break;
    case LUA_VTHREAD:
      luaE_freethread(L, gco2th(o));
      break;
    case LUA_VUSERDATA: {
      Udata *u = gco2u(o);
      luaM_freemem(L, o, sizeudata(u->nuvalue, u->len));
      break;
    }
    case LUA_VSHRSTR: {
      TString *ts = gco2ts(o);
      luaS_remove(L, ts);  /* remove it from hash table */
      luaM_freemem(L, ts, sizelstring(ts->shrlen));
      break;
    }
    case LUA_VLNGSTR: {
      TString *ts = gco2ts(o);
      luaM_freemem(L, ts, sizelstring(ts->u.lnglen));
      break;
    }
    default: lua_assert(0);
  }
}
References freeupval(), gco2ccl, gco2lcl, gco2p, gco2t, gco2th, gco2ts, gco2u, gco2upv, Udata::len, TString::lnglen, lua_assert, LUA_VCCL, LUA_VLCL, LUA_VLNGSTR, LUA_VPROTO, LUA_VSHRSTR, LUA_VTABLE, LUA_VTHREAD, LUA_VUPVAL, LUA_VUSERDATA, luaE_freethread(), luaF_freeproto(), luaH_free(), luaM_freemem, luaS_remove(), Udata::nuvalue, TString::shrlen, sizeCclosure, sizeLclosure, sizelstring, sizeudata, and TString::u.
Referenced by deletelist(), sweep2old(), sweepgen(), and sweeplist().
freeupval()
static void freeupval (lua_State * L, UpVal * uv) static
Definition at line 757 of file lua-5.4.3/src/lgc.c.
{
  if (upisopen(uv))
    luaF_unlinkupval(uv);
  luaM_free(L, uv);
}
References luaF_unlinkupval(), luaM_free, and upisopen.
Referenced by freeobj().
fullgen()
static lu_mem fullgen (lua_State * L, global_State * g) static
Definition at line 1338 of file lua-5.4.3/src/lgc.c.
{
  enterinc(g);
  return entergen(L, g);
}
References entergen(), and enterinc().
Referenced by genstep(), and luaC_fullgc().
fullinc()
static void fullinc (lua_State * L, global_State * g) static
Definition at line 1697 of file lua-5.4.3/src/lgc.c.
{
  if (keepinvariant(g))  /* black objects? */
    entersweep(L); /* sweep everything to turn them back to white */
  /* finish any pending sweep phase to start a new cycle */
  luaC_runtilstate(L, bitmask(GCSpause));
  luaC_runtilstate(L, bitmask(GCScallfin));  /* run up to finalizers */
  /* estimate must be correct after a full GC cycle */
  lua_assert(g->GCestimate == gettotalbytes(g));
  luaC_runtilstate(L, bitmask(GCSpause));  /* finish collection */
  setpause(g);
}
References bitmask, entersweep(), global_State::GCestimate, GCScallfin, GCSpause, gettotalbytes, keepinvariant, lua_assert, luaC_runtilstate(), and setpause().
Referenced by luaC_fullgc().
GCTM()
static void GCTM (lua_State * L) static
Definition at line 899 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  const TValue *tm;
  TValue v;
  lua_assert(!g->gcemergency);
  setgcovalue(L, &v, udata2finalize(g));
  tm = luaT_gettmbyobj(L, &v, TM_GC);
  if (!notm(tm)) {  /* is there a finalizer? */
    int status;
    lu_byte oldah = L->allowhook;
    int running  = g->gcrunning;
    L->allowhook = 0;  /* stop debug hooks during GC metamethod */
    g->gcrunning = 0;  /* avoid GC steps */
    setobj2s(L, L->top++, tm);  /* push finalizer... */
    setobj2s(L, L->top++, &v);  /* ... and its argument */
    L->ci->callstatus |= CIST_FIN;  /* will run a finalizer */
    status = luaD_pcall(L, dothecall, NULL, savestack(L, L->top - 2), 0);
    L->ci->callstatus &= ~CIST_FIN;  /* not running a finalizer anymore */
    L->allowhook = oldah;  /* restore hooks */
    g->gcrunning = running;  /* restore state */
    if (l_unlikely(status != LUA_OK)) {  /* error while running __gc? */
      luaE_warnerror(L, "__gc metamethod");
      L->top--;  /* pops error object */
    }
  }
}
References lua_State::allowhook, CallInfo::callstatus, lua_State::ci, CIST_FIN, dothecall(), G, global_State::gcemergency, global_State::gcrunning, lua_assert, LUA_OK, luaD_pcall(), luaE_warnerror(), luaT_gettmbyobj(), notm, NULL, savestack, setgcovalue, setobj2s, TM_GC, lua_State::top, and udata2finalize().
Referenced by callallpendingfinalizers(), and runafewfinalizers().
genlink()
static void genlink (global_State * g, GCObject * o) static
Definition at line 424 of file lua-5.4.3/src/lgc.c.
{
  lua_assert(isblack(o));
  if (getage(o) == G_TOUCHED1) {  /* touched in this cycle? */
    linkobjgclist(o, g->grayagain);  /* link it back in 'grayagain' */
  }  /* everything else do not need to be linked back */
  else if (getage(o) == G_TOUCHED2)
    changeage(o, G_TOUCHED2, G_OLD);  /* advance age */
}
References changeage, G_OLD, G_TOUCHED1, G_TOUCHED2, getage, global_State::grayagain, isblack, linkobjgclist, and lua_assert.
Referenced by traverseephemeron(), traversestrongtable(), and traverseudata().
genstep()
static void genstep (lua_State * L, global_State * g) static
Definition at line 1414 of file lua-5.4.3/src/lgc.c.
{
  if (g->lastatomic != 0)  /* last collection was a bad one? */
    stepgenfull(L, g);  /* do a full step */
  else {
    lu_mem majorbase = g->GCestimate;  /* memory after last major collection */
    lu_mem majorinc = (majorbase / 100) * getgcparam(g->genmajormul);
    if (g->GCdebt > 0 && gettotalbytes(g) > majorbase + majorinc) {
      lu_mem numobjs = fullgen(L, g);  /* do a major collection */
      if (gettotalbytes(g) < majorbase + (majorinc / 2)) {
        /* collected at least half of memory growth since last major
           collection; keep doing minor collections */
        setminordebt(g);
      }
      else {  /* bad collection */
        g->lastatomic = numobjs;  /* signal that last collection was bad */
        setpause(g);  /* do a long wait for next (major) collection */
      }
    }
    else {  /* regular case; do a minor collection */
      youngcollection(L, g);
      setminordebt(g);
      g->GCestimate = majorbase;  /* preserve base value */
    }
  }
  lua_assert(isdecGCmodegen(g));
}
References fullgen(), global_State::GCdebt, global_State::GCestimate, global_State::genmajormul, getgcparam, gettotalbytes, isdecGCmodegen, global_State::lastatomic, lua_assert, setminordebt(), setpause(), stepgenfull(), and youngcollection().
Referenced by luaC_step().
getgclist()
static GCObject ** getgclist (GCObject * o) static
Definition at line 125 of file lua-5.4.3/src/lgc.c.
{
  switch (o->tt) {
    case LUA_VTABLE: return &gco2t(o)->gclist;
    case LUA_VLCL: return &gco2lcl(o)->gclist;
    case LUA_VCCL: return &gco2ccl(o)->gclist;
    case LUA_VTHREAD: return &gco2th(o)->gclist;
    case LUA_VPROTO: return &gco2p(o)->gclist;
    case LUA_VUSERDATA: {
      Udata *u = gco2u(o);
      lua_assert(u->nuvalue > 0);
      return &u->gclist;
    }
    default: lua_assert(0); return 0;
  }
}
References Udata::gclist, gco2ccl, gco2lcl, gco2p, gco2t, gco2th, gco2u, lua_assert, LUA_VCCL, LUA_VLCL, LUA_VPROTO, LUA_VTABLE, LUA_VTHREAD, LUA_VUSERDATA, and Udata::nuvalue.
Referenced by correctgraylist(), and propagatemark().
incstep()
static void incstep (lua_State * L, global_State * g) static
Definition at line 1657 of file lua-5.4.3/src/lgc.c.
{
  int stepmul = (getgcparam(g->gcstepmul) | 1);  /* avoid division by 0 */
  l_mem debt = (g->GCdebt / WORK2MEM) * stepmul;
  l_mem stepsize = (g->gcstepsize <= log2maxs(l_mem))
                 ? ((cast(l_mem, 1) << g->gcstepsize) / WORK2MEM) * stepmul
                 : MAX_LMEM;  /* overflow; keep maximum value */
  do {  /* repeat until pause or enough "credit" (negative debt) */
    lu_mem work = singlestep(L);  /* perform one single step */
    debt -= work;
  } while (debt > -stepsize && g->gcstate != GCSpause);
  if (g->gcstate == GCSpause)
    setpause(g);  /* pause until next cycle */
  else {
    debt = (debt / stepmul) * WORK2MEM;  /* convert 'work units' to bytes */
    luaE_setdebt(g, debt);
  }
}
References cast, global_State::GCdebt, GCSpause, global_State::gcstate, global_State::gcstepmul, global_State::gcstepsize, getgcparam, log2maxs, luaE_setdebt(), MAX_LMEM, setpause(), singlestep(), and WORK2MEM.
Referenced by luaC_step().
iscleared()
static int iscleared (global_State * g, const GCObject * o) static
Definition at line 185 of file lua-5.4.3/src/lgc.c.
{
  if (o == NULL) return 0;  /* non-collectable value */
  else if (novariant(o->tt) == LUA_TSTRING) {
    markobject(g, o);  /* strings are 'values', so are never weak */
    return 0;
  }
  else return iswhite(o);
}
References iswhite, LUA_TSTRING, markobject, novariant, and NULL.
Referenced by clearbykeys(), clearbyvalues(), traverseephemeron(), and traverseweakvalue().
linkgclist_()
static void linkgclist_ (GCObject * o, GCObject ** pnext, GCObject ** list) static
Definition at line 148 of file lua-5.4.3/src/lgc.c.
{
  lua_assert(!isgray(o));  /* cannot be in a gray list */
  *pnext = *list;
  *list = o;
  set2gray(o);  /* now it is */
}
References isgray, lua_assert, and set2gray.
luaC_barrier_()
void luaC_barrier_ (lua_State * L, GCObject * o, GCObject * v)
Definition at line 208 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(isblack(o) && iswhite(v) && !isdead(g, v) && !isdead(g, o));
  if (keepinvariant(g)) {  /* must keep invariant? */
    reallymarkobject(g, v);  /* restore invariant */
    if (isold(o)) {
      lua_assert(!isold(v));  /* white object could not be old */
      setage(v, G_OLD0);  /* restore generational invariant */
    }
  }
  else {  /* sweep phase */
    lua_assert(issweepphase(g));
    if (g->gckind == KGC_INC)  /* incremental mode? */
      makewhite(g, o);  /* mark 'o' as white to avoid other barriers */
  }
}
References G, G_OLD0, global_State::gckind, isblack, isdead, isold, issweepphase, iswhite, keepinvariant, KGC_INC, lua_assert, makewhite, reallymarkobject(), and setage.
luaC_barrierback_()
void luaC_barrierback_ (lua_State * L, GCObject * o)
Definition at line 230 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(isblack(o) && !isdead(g, o));
  lua_assert((g->gckind == KGC_GEN) == (isold(o) && getage(o) != G_TOUCHED1));
  if (getage(o) == G_TOUCHED2)  /* already in gray list? */
    set2gray(o);  /* make it gray to become touched1 */
  else  /* link it in 'grayagain' and paint it gray */
    linkobjgclist(o, g->grayagain);
  if (isold(o))  /* generational mode? */
    setage(o, G_TOUCHED1);  /* touched in current cycle */
}
References G, G_TOUCHED1, G_TOUCHED2, global_State::gckind, getage, global_State::grayagain, isblack, isdead, isold, KGC_GEN, linkobjgclist, lua_assert, set2gray, and setage.
luaC_changemode()
void luaC_changemode (lua_State * L, int newmode)
Definition at line 1323 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  if (newmode != g->gckind) {
    if (newmode == KGC_GEN)  /* entering generational mode? */
      entergen(L, g);
    else
      enterinc(g);  /* entering incremental mode */
  }
  g->lastatomic = 0;
}
References entergen(), enterinc(), G, global_State::gckind, KGC_GEN, and global_State::lastatomic.
Referenced by luaC_freeallobjects().
luaC_checkfinalizer()
void luaC_checkfinalizer (lua_State * L, GCObject * o, Table * mt)
Definition at line 1011 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  if (tofinalize(o) ||                 /* obj. is already marked... */
      gfasttm(g, mt, TM_GC) == NULL)   /* or has no finalizer? */
    return;  /* nothing to be done */
  else {  /* move 'o' to 'finobj' list */
    GCObject **p;
    if (issweepphase(g)) {
      makewhite(g, o);  /* "sweep" object 'o' */
      if (g->sweepgc == &o->next)  /* should not remove 'sweepgc' object */
        g->sweepgc = sweeptolive(L, g->sweepgc);  /* change 'sweepgc' */
    }
    else
      correctpointers(g, o);
    /* search for pointer pointing to 'o' */
    for (p = &g->allgc; *p != o; p = &(*p)->next) { /* empty */ }
    *p = o->next;  /* remove 'o' from 'allgc' list */
    o->next = g->finobj;  /* link it in 'finobj' list */
    g->finobj = o;
    l_setbit(o->marked, FINALIZEDBIT);  /* mark it as such */
  }
}
References global_State::allgc, correctpointers(), FINALIZEDBIT, global_State::finobj, G, gfasttm, issweepphase, l_setbit, makewhite, NULL, global_State::sweepgc, sweeptolive(), TM_GC, and tofinalize.
luaC_fix()
void luaC_fix (lua_State * L, GCObject * o)
Definition at line 243 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(g->allgc == o);  /* object must be 1st in 'allgc' list! */
  set2gray(o);  /* they will be gray forever */
  setage(o, G_OLD);  /* and old forever */
  g->allgc = o->next;  /* remove object from 'allgc' list */
  o->next = g->fixedgc;  /* link it to 'fixedgc' list */
  g->fixedgc = o;
}
References global_State::allgc, global_State::fixedgc, G, G_OLD, lua_assert, set2gray, and setage.
luaC_freeallobjects()
void luaC_freeallobjects (lua_State * L)
Definition at line 1503 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  luaC_changemode(L, KGC_INC);
  separatetobefnz(g, 1);  /* separate all objects with finalizers */
  lua_assert(g->finobj == NULL);
  callallpendingfinalizers(L);
  deletelist(L, g->allgc, obj2gco(g->mainthread));
  deletelist(L, g->finobj, NULL);
  deletelist(L, g->fixedgc, NULL);  /* collect fixed objects */
  lua_assert(g->strt.nuse == 0);
}
References global_State::allgc, callallpendingfinalizers(), deletelist(), global_State::finobj, global_State::fixedgc, G, KGC_INC, lua_assert, luaC_changemode(), global_State::mainthread, NULL, stringtable::nuse, obj2gco, separatetobefnz(), and global_State::strt.
luaC_fullgc()
void luaC_fullgc (lua_State * L, int isemergency)
Definition at line 1715 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(!g->gcemergency);
  g->gcemergency = isemergency;  /* set flag */
  if (g->gckind == KGC_INC)
    fullinc(L, g);
  else
    fullgen(L, g);
  g->gcemergency = 0;
}
References fullgen(), fullinc(), G, global_State::gcemergency, global_State::gckind, KGC_INC, and lua_assert.
luaC_newobj()
GCObject * luaC_newobj (lua_State * L, int tt, size_t sz)
Definition at line 258 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  GCObject *o = cast(GCObject *, luaM_newobject(L, novariant(tt), sz));
  o->marked = luaC_white(g);
  o->tt = tt;
  o->next = g->allgc;
  g->allgc = o;
  return o;
}
References global_State::allgc, cast, G, luaC_white, luaM_newobject, and novariant.
luaC_runtilstate()
void luaC_runtilstate (lua_State * L, int statesmask)
Definition at line 1643 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  while (!testbit(statesmask, g->gcstate))
    singlestep(L);
}
References G, global_State::gcstate, singlestep(), and testbit.
Referenced by entergen(), fullinc(), and stepgenfull().
luaC_step()
void luaC_step (lua_State * L)
Definition at line 1678 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(!g->gcemergency);
  if (g->gcrunning) {  /* running? */
    if(isdecGCmodegen(g))
      genstep(L, g);
    else
      incstep(L, g);
  }
}
References G, global_State::gcemergency, global_State::gcrunning, genstep(), incstep(), isdecGCmodegen, and lua_assert.
markbeingfnz()
static lu_mem markbeingfnz (global_State * g) static
Definition at line 339 of file lua-5.4.3/src/lgc.c.
{
  GCObject *o;
  lu_mem count = 0;
  for (o = g->tobefnz; o != NULL; o = o->next) {
    count++;
    markobject(g, o);
  }
  return count;
}
References markobject, NULL, and global_State::tobefnz.
Referenced by atomic(), and restartcollection().
markmt()
static void markmt (global_State * g) static
Definition at line 329 of file lua-5.4.3/src/lgc.c.
{
  int i;
  for (i=0; i < LUA_NUMTAGS; i++)
    markobjectN(g, g->mt[i]);
}
References LUA_NUMTAGS, markobjectN, and global_State::mt.
Referenced by atomic(), and restartcollection().
markold()
static void markold (global_State * g, GCObject * from, GCObject * to) static
Definition at line 1194 of file lua-5.4.3/src/lgc.c.
{
  GCObject *p;
  for (p = from; p != to; p = p->next) {
    if (getage(p) == G_OLD1) {
      lua_assert(!iswhite(p));
      changeage(p, G_OLD1, G_OLD);  /* now they are old */
      if (isblack(p))
        reallymarkobject(g, p);
    }
  }
}
References changeage, G_OLD, G_OLD1, getage, isblack, iswhite, lua_assert, and reallymarkobject().
Referenced by youngcollection().
propagateall()
static lu_mem propagateall (global_State * g) static
Definition at line 668 of file lua-5.4.3/src/lgc.c.
{
  lu_mem tot = 0;
  while (g->gray)
    tot += propagatemark(g);
  return tot;
}
References global_State::gray, and propagatemark().
Referenced by atomic(), and convergeephemerons().
propagatemark()
static lu_mem propagatemark (global_State * g) static
Definition at line 652 of file lua-5.4.3/src/lgc.c.
{
  GCObject *o = g->gray;
  nw2black(o);
  g->gray = *getgclist(o);  /* remove from 'gray' list */
  switch (o->tt) {
    case LUA_VTABLE: return traversetable(g, gco2t(o));
    case LUA_VUSERDATA: return traverseudata(g, gco2u(o));
    case LUA_VLCL: return traverseLclosure(g, gco2lcl(o));
    case LUA_VCCL: return traverseCclosure(g, gco2ccl(o));
    case LUA_VPROTO: return traverseproto(g, gco2p(o));
    case LUA_VTHREAD: return traversethread(g, gco2th(o));
    default: lua_assert(0); return 0;
  }
}
References gco2ccl, gco2lcl, gco2p, gco2t, gco2th, gco2u, getgclist(), global_State::gray, lua_assert, LUA_VCCL, LUA_VLCL, LUA_VPROTO, LUA_VTABLE, LUA_VTHREAD, LUA_VUSERDATA, nw2black, traverseCclosure(), traverseLclosure(), traverseproto(), traversetable(), traversethread(), and traverseudata().
Referenced by propagateall(), and singlestep().
reallymarkobject()
static void reallymarkobject (global_State * g, GCObject * o) static
Definition at line 291 of file lua-5.4.3/src/lgc.c.
{
  switch (o->tt) {
    case LUA_VSHRSTR:
    case LUA_VLNGSTR: {
      set2black(o);  /* nothing to visit */
      break;
    }
    case LUA_VUPVAL: {
      UpVal *uv = gco2upv(o);
      if (upisopen(uv))
        set2gray(uv);  /* open upvalues are kept gray */
      else
        set2black(uv);  /* closed upvalues are visited here */
      markvalue(g, uv->v);  /* mark its content */
      break;
    }
    case LUA_VUSERDATA: {
      Udata *u = gco2u(o);
      if (u->nuvalue == 0) {  /* no user values? */
        markobjectN(g, u->metatable);  /* mark its metatable */
        set2black(u);  /* nothing else to mark */
        break;
      }
      /* else... */
    }  /* FALLTHROUGH */
    case LUA_VLCL: case LUA_VCCL: case LUA_VTABLE:
    case LUA_VTHREAD: case LUA_VPROTO: {
      linkobjgclist(o, g->gray);  /* to be visited later */
      break;
    }
    default: lua_assert(0); break;
  }
}
References gco2u, gco2upv, global_State::gray, linkobjgclist, lua_assert, LUA_VCCL, LUA_VLCL, LUA_VLNGSTR, LUA_VPROTO, LUA_VSHRSTR, LUA_VTABLE, LUA_VTHREAD, LUA_VUPVAL, LUA_VUSERDATA, markobjectN, markvalue, Udata::metatable, Udata::nuvalue, set2black, set2gray, upisopen, and UpVal::v.
Referenced by luaC_barrier_(), markold(), and traverseephemeron().
remarkupvals()
static int remarkupvals (global_State * g) static
Definition at line 361 of file lua-5.4.3/src/lgc.c.
{
  lua_State *thread;
  lua_State **p = &g->twups;
  int work = 0;  /* estimate of how much work was done here */
  while ((thread = *p) != NULL) {
    work++;
    if (!iswhite(thread) && thread->openupval != NULL)
      p = &thread->twups;  /* keep marked thread with upvalues in the list */
    else {  /* thread is not marked or without upvalues */
      UpVal *uv;
      lua_assert(!isold(thread) || thread->openupval == NULL);
      *p = thread->twups;  /* remove thread from the list */
      thread->twups = thread;  /* mark that it is out of list */
      for (uv = thread->openupval; uv != NULL; uv = uv->u.open.next) {
        lua_assert(getage(uv) <= getage(thread));
        work++;
        if (!iswhite(uv)) {  /* upvalue already visited? */
          lua_assert(upisopen(uv) && isgray(uv));
          markvalue(g, uv->v);  /* mark its value */
        }
      }
    }
  }
  return work;
}
References getage, isgray, isold, iswhite, lua_assert, markvalue, UpVal::next, NULL, UpVal::open, lua_State::openupval, global_State::twups, lua_State::twups, UpVal::u, upisopen, and UpVal::v.
Referenced by atomic().
restartcollection()
static void restartcollection (global_State * g) static
Definition at line 397 of file lua-5.4.3/src/lgc.c.
{
  cleargraylists(g);
  markobject(g, g->mainthread);
  markvalue(g, &g->l_registry);
  markmt(g);
  markbeingfnz(g);  /* mark any finalizing object left from previous cycle */
}
References cleargraylists(), global_State::l_registry, global_State::mainthread, markbeingfnz(), markmt(), markobject, and markvalue.
Referenced by singlestep().
runafewfinalizers()
static int runafewfinalizers (lua_State * L, int n) static
Definition at line 930 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  int i;
  for (i = 0; i < n && g->tobefnz; i++)
    GCTM(L);  /* call one finalizer */
  return i;
}
References G, GCTM(), and global_State::tobefnz.
Referenced by singlestep().
separatetobefnz()
static void separatetobefnz (global_State * g, int all) static
Definition at line 966 of file lua-5.4.3/src/lgc.c.
{
  GCObject *curr;
  GCObject **p = &g->finobj;
  GCObject **lastnext = findlast(&g->tobefnz);
  while ((curr = *p) != g->finobjold1) {  /* traverse all finalizable objects */
    lua_assert(tofinalize(curr));
    if (!(iswhite(curr) || all))  /* not being collected? */
      p = &curr->next;  /* don't bother with it */
    else {
      if (curr == g->finobjsur)  /* removing 'finobjsur'? */
        g->finobjsur = curr->next;  /* correct it */
      *p = curr->next;  /* remove 'curr' from 'finobj' list */
      curr->next = *lastnext;  /* link at the end of 'tobefnz' list */
      *lastnext = curr;
      lastnext = &curr->next;
    }
  }
}
References findlast(), global_State::finobj, global_State::finobjold1, global_State::finobjsur, iswhite, lua_assert, global_State::tobefnz, and tofinalize.
Referenced by atomic(), and luaC_freeallobjects().
setminordebt()
static void setminordebt (global_State * g) static
Definition at line 1348 of file lua-5.4.3/src/lgc.c.
{
  luaE_setdebt(g, -(cast(l_mem, (gettotalbytes(g) / 100)) * g->genminormul));
}
References cast, global_State::genminormul, gettotalbytes, and luaE_setdebt().
Referenced by genstep(), and stepgenfull().
setpause()
static void setpause (global_State * g) static
Definition at line 1457 of file lua-5.4.3/src/lgc.c.
{
  l_mem threshold, debt;
  int pause = getgcparam(g->gcpause);
  l_mem estimate = g->GCestimate / PAUSEADJ;  /* adjust 'estimate' */
  lua_assert(estimate > 0);
  threshold = (pause < MAX_LMEM / estimate)  /* overflow? */
            ? estimate * pause  /* no overflow */
            : MAX_LMEM;  /* overflow; truncate to maximum */
  debt = gettotalbytes(g) - threshold;
  if (debt > 0) debt = 0;
  luaE_setdebt(g, debt);
}
References global_State::GCestimate, global_State::gcpause, getgcparam, gettotalbytes, lua_assert, luaE_setdebt(), MAX_LMEM, and PAUSEADJ.
Referenced by fullinc(), genstep(), incstep(), and stepgenfull().
singlestep()
static lu_mem singlestep (lua_State * L) static
Definition at line 1576 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  lu_mem work;
  lua_assert(!g->gcstopem);  /* collector is not reentrant */
  g->gcstopem = 1;  /* no emergency collections while collecting */
  switch (g->gcstate) {
    case GCSpause: {
      restartcollection(g);
      g->gcstate = GCSpropagate;
      work = 1;
      break;
    }
    case GCSpropagate: {
      if (g->gray == NULL) {  /* no more gray objects? */
        g->gcstate = GCSenteratomic;  /* finish propagate phase */
        work = 0;
      }
      else
        work = propagatemark(g);  /* traverse one gray object */
      break;
    }
    case GCSenteratomic: {
      work = atomic(L);  /* work is what was traversed by 'atomic' */
      entersweep(L);
      g->GCestimate = gettotalbytes(g);  /* first estimate */;
      break;
    }
    case GCSswpallgc: {  /* sweep "regular" objects */
      work = sweepstep(L, g, GCSswpfinobj, &g->finobj);
      break;
    }
    case GCSswpfinobj: {  /* sweep objects with finalizers */
      work = sweepstep(L, g, GCSswptobefnz, &g->tobefnz);
      break;
    }
    case GCSswptobefnz: {  /* sweep objects to be finalized */
      work = sweepstep(L, g, GCSswpend, NULL);
      break;
    }
    case GCSswpend: {  /* finish sweeps */
      checkSizes(L, g);
      g->gcstate = GCScallfin;
      work = 0;
      break;
    }
    case GCScallfin: {  /* call remaining finalizers */
      if (g->tobefnz && !g->gcemergency) {
        g->gcstopem = 0;  /* ok collections during finalizers */
        work = runafewfinalizers(L, GCFINMAX) * GCFINALIZECOST;
      }
      else {  /* emergency mode or no more finalizers */
        g->gcstate = GCSpause;  /* finish collection */
        work = 0;
      }
      break;
    }
    default: lua_assert(0); return 0;
  }
  g->gcstopem = 0;
  return work;
}
References atomic(), checkSizes(), entersweep(), global_State::finobj, G, global_State::gcemergency, global_State::GCestimate, GCFINALIZECOST, GCFINMAX, GCScallfin, GCSenteratomic, GCSpause, GCSpropagate, GCSswpallgc, GCSswpend, GCSswpfinobj, GCSswptobefnz, global_State::gcstate, global_State::gcstopem, gettotalbytes, global_State::gray, lua_assert, NULL, propagatemark(), restartcollection(), runafewfinalizers(), sweepstep(), and global_State::tobefnz.
Referenced by incstep(), and luaC_runtilstate().
stepgenfull()
static void stepgenfull (lua_State * L, global_State * g) static
Definition at line 1374 of file lua-5.4.3/src/lgc.c.
{
  lu_mem newatomic;  /* count of traversed objects */
  lu_mem lastatomic = g->lastatomic;  /* count from last collection */
  if (g->gckind == KGC_GEN)  /* still in generational mode? */
    enterinc(g);  /* enter incremental mode */
  luaC_runtilstate(L, bitmask(GCSpropagate));  /* start new cycle */
  newatomic = atomic(L);  /* mark everybody */
  if (newatomic < lastatomic + (lastatomic >> 3)) {  /* good collection? */
    atomic2gen(L, g);  /* return to generational mode */
    setminordebt(g);
  }
  else {  /* another bad collection; stay in incremental mode */
    g->GCestimate = gettotalbytes(g);  /* first estimate */;
    entersweep(L);
    luaC_runtilstate(L, bitmask(GCSpause));  /* finish collection */
    setpause(g);
    g->lastatomic = newatomic;
  }
}
References atomic(), atomic2gen(), bitmask, enterinc(), entersweep(), global_State::GCestimate, global_State::gckind, GCSpause, GCSpropagate, gettotalbytes, KGC_GEN, global_State::lastatomic, luaC_runtilstate(), setminordebt(), and setpause().
Referenced by genstep().
sweep2old()
static void sweep2old (lua_State * L, GCObject ** p) static
Definition at line 1052 of file lua-5.4.3/src/lgc.c.
{
  GCObject *curr;
  global_State *g = G(L);
  while ((curr = *p) != NULL) {
    if (iswhite(curr)) {  /* is 'curr' dead? */
      lua_assert(isdead(g, curr));
      *p = curr->next;  /* remove 'curr' from list */
      freeobj(L, curr);  /* erase 'curr' */
    }
    else {  /* all surviving objects become old */
      setage(curr, G_OLD);
      if (curr->tt == LUA_VTHREAD) {  /* threads must be watched */
        lua_State *th = gco2th(curr);
        linkgclist(th, g->grayagain);  /* insert into 'grayagain' list */
      }
      else if (curr->tt == LUA_VUPVAL && upisopen(gco2upv(curr)))
        set2gray(curr);  /* open upvalues are always gray */
      else  /* everything else is black */
        nw2black(curr);
      p = &curr->next;  /* go to next element */
    }
  }
}
References freeobj(), G, G_OLD, gco2th, gco2upv, global_State::grayagain, isdead, iswhite, linkgclist, lua_assert, LUA_VTHREAD, LUA_VUPVAL, NULL, nw2black, set2gray, setage, and upisopen.
Referenced by atomic2gen().
sweepgen()
static GCObject ** sweepgen (lua_State * L, global_State * g, GCObject ** p, GCObject * limit, GCObject ** pfirstold1) static
Definition at line 1088 of file lua-5.4.3/src/lgc.c.
{
  static const lu_byte nextage[] = {
    G_SURVIVAL,  /* from G_NEW */
    G_OLD1,      /* from G_SURVIVAL */
    G_OLD1,      /* from G_OLD0 */
    G_OLD,       /* from G_OLD1 */
    G_OLD,       /* from G_OLD (do not change) */
    G_TOUCHED1,  /* from G_TOUCHED1 (do not change) */
    G_TOUCHED2   /* from G_TOUCHED2 (do not change) */
  };
  int white = luaC_white(g);
  GCObject *curr;
  while ((curr = *p) != limit) {
    if (iswhite(curr)) {  /* is 'curr' dead? */
      lua_assert(!isold(curr) && isdead(g, curr));
      *p = curr->next;  /* remove 'curr' from list */
      freeobj(L, curr);  /* erase 'curr' */
    }
    else {  /* correct mark and age */
      if (getage(curr) == G_NEW) {  /* new objects go back to white */
        int marked = curr->marked & ~maskgcbits;  /* erase GC bits */
        curr->marked = cast_byte(marked | G_SURVIVAL | white);
      }
      else {  /* all other objects will be old, and so keep their color */
        setage(curr, nextage[getage(curr)]);
        if (getage(curr) == G_OLD1 && *pfirstold1 == NULL)
          *pfirstold1 = curr;  /* first OLD1 object in the list */
      }
      p = &curr->next;  /* go to next element */
    }
  }
  return p;
}
References cast_byte, freeobj(), G_NEW, G_OLD, G_OLD1, G_SURVIVAL, G_TOUCHED1, G_TOUCHED2, getage, isdead, isold, iswhite, lua_assert, luaC_white, NULL, and setage.
Referenced by youngcollection().
sweeplist()
static GCObject ** sweeplist (lua_State * L, GCObject ** p, int countin, int * countout) static
Definition at line 816 of file lua-5.4.3/src/lgc.c.
{
  global_State *g = G(L);
  int ow = otherwhite(g);
  int i;
  int white = luaC_white(g);  /* current white */
  for (i = 0; *p != NULL && i < countin; i++) {
    GCObject *curr = *p;
    int marked = curr->marked;
    if (isdeadm(ow, marked)) {  /* is 'curr' dead? */
      *p = curr->next;  /* remove 'curr' from list */
      freeobj(L, curr);  /* erase 'curr' */
    }
    else {  /* change mark to 'white' */
      curr->marked = cast_byte((marked & ~maskgcbits) | white);
      p = &curr->next;  /* go to next element */
    }
  }
  if (countout)
    *countout = i;  /* number of elements traversed */
  return (*p == NULL) ? NULL : p;
}
References cast_byte, freeobj(), G, isdeadm, luaC_white, maskgcbits, NULL, and otherwhite.
Referenced by sweepstep(), and sweeptolive().
sweepstep()
static int sweepstep (lua_State * L, global_State * g, int nextstate, GCObject ** nextlist) static
Definition at line 1559 of file lua-5.4.3/src/lgc.c.
{
  if (g->sweepgc) {
    l_mem olddebt = g->GCdebt;
    int count;
    g->sweepgc = sweeplist(L, g->sweepgc, GCSWEEPMAX, &count);
    g->GCestimate += g->GCdebt - olddebt;  /* update estimate */
    return count;
  }
  else {  /* enter next state */
    g->gcstate = nextstate;
    g->sweepgc = nextlist;
    return 0;  /* no work done */
  }
}
References global_State::GCdebt, global_State::GCestimate, global_State::gcstate, GCSWEEPMAX, global_State::sweepgc, and sweeplist().
Referenced by singlestep().
sweeptolive()
static GCObject ** sweeptolive (lua_State * L, GCObject ** p) static
Definition at line 843 of file lua-5.4.3/src/lgc.c.
{
  GCObject **old = p;
  do {
    p = sweeplist(L, p, 1, NULL);
  } while (p == old);
  return p;
}
References NULL, and sweeplist().
Referenced by entersweep(), and luaC_checkfinalizer().
traverseCclosure()
static int traverseCclosure (global_State * g, CClosure * cl) static
Definition at line 587 of file lua-5.4.3/src/lgc.c.
{
  int i;
  for (i = 0; i < cl->nupvalues; i++)  /* mark its upvalues */
    markvalue(g, &cl->upvalue[i]);
  return 1 + cl->nupvalues;
}
References markvalue, and CClosure::upvalue.
Referenced by propagatemark().
traverseephemeron()
static int traverseephemeron (global_State * g, Table * h, int inv) static
Definition at line 474 of file lua-5.4.3/src/lgc.c.
{
  int marked = 0;  /* true if an object is marked in this traversal */
  int hasclears = 0;  /* true if table has white keys */
  int hasww = 0;  /* true if table has entry "white-key -> white-value" */
  unsigned int i;
  unsigned int asize = luaH_realasize(h);
  unsigned int nsize = sizenode(h);
  /* traverse array part */
  for (i = 0; i < asize; i++) {
    if (valiswhite(&h->array[i])) {
      marked = 1;
      reallymarkobject(g, gcvalue(&h->array[i]));
    }
  }
  /* traverse hash part; if 'inv', traverse descending
     (see 'convergeephemerons') */
  for (i = 0; i < nsize; i++) {
    Node *n = inv ? gnode(h, nsize - 1 - i) : gnode(h, i);
    if (isempty(gval(n)))  /* entry is empty? */
      clearkey(n);  /* clear its key */
    else if (iscleared(g, gckeyN(n))) {  /* key is not marked (yet)? */
      hasclears = 1;  /* table must be cleared */
      if (valiswhite(gval(n)))  /* value not marked yet? */
        hasww = 1;  /* white-white entry */
    }
    else if (valiswhite(gval(n))) {  /* value not marked yet? */
      marked = 1;
      reallymarkobject(g, gcvalue(gval(n)));  /* mark it now */
    }
  }
  /* link table into proper list */
  if (g->gcstate == GCSpropagate)
    linkgclist(h, g->grayagain);  /* must retraverse it in atomic phase */
  else if (hasww)  /* table has white->white entries? */
    linkgclist(h, g->ephemeron);  /* have to propagate again */
  else if (hasclears)  /* table has white keys? */
    linkgclist(h, g->allweak);  /* may have to clean white keys */
  else
    genlink(g, obj2gco(h));  /* check whether collector still needs to see it */
  return marked;
}
References global_State::allweak, Table::array, clearkey(), global_State::ephemeron, gckeyN, GCSpropagate, global_State::gcstate, gcvalue, genlink(), gnode, global_State::grayagain, gval, iscleared(), isempty, linkgclist, luaH_realasize(), obj2gco, reallymarkobject(), sizenode, and valiswhite.
Referenced by convergeephemerons(), and traversetable().
traverseLclosure()
static int traverseLclosure (global_State * g, LClosure * cl) static
Definition at line 598 of file lua-5.4.3/src/lgc.c.
{
  int i;
  markobjectN(g, cl->p);  /* mark its prototype */
  for (i = 0; i < cl->nupvalues; i++) {  /* visit its upvalues */
    UpVal *uv = cl->upvals[i];
    markobjectN(g, uv);  /* mark upvalue */
  }
  return 1 + cl->nupvalues;
}
References markobjectN, LClosure::p, and LClosure::upvals.
Referenced by propagatemark().
traverseproto()
static int traverseproto (global_State * g, Proto * f) static
Definition at line 572 of file lua-5.4.3/src/lgc.c.
{
  int i;
  markobjectN(g, f->source);
  for (i = 0; i < f->sizek; i++)  /* mark literals */
    markvalue(g, &f->k[i]);
  for (i = 0; i < f->sizeupvalues; i++)  /* mark upvalue names */
    markobjectN(g, f->upvalues[i].name);
  for (i = 0; i < f->sizep; i++)  /* mark nested protos */
    markobjectN(g, f->p[i]);
  for (i = 0; i < f->sizelocvars; i++)  /* mark local-variable names */
    markobjectN(g, f->locvars[i].varname);
  return 1 + f->sizek + f->sizeupvalues + f->sizep + f->sizelocvars;
}
References Proto::k, Proto::locvars, markobjectN, markvalue, Proto::p, Proto::sizek, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, Proto::upvalues, and LocVar::varname.
Referenced by propagatemark().
traversestrongtable()
static void traversestrongtable (global_State * g, Table * h) static
Definition at line 517 of file lua-5.4.3/src/lgc.c.
{
  Node *n, *limit = gnodelast(h);
  unsigned int i;
  unsigned int asize = luaH_realasize(h);
  for (i = 0; i < asize; i++)  /* traverse array part */
    markvalue(g, &h->array[i]);
  for (n = gnode(h, 0); n < limit; n++) {  /* traverse hash part */
    if (isempty(gval(n)))  /* entry is empty? */
      clearkey(n);  /* clear its key */
    else {
      lua_assert(!keyisnil(n));
      markkey(g, n);
      markvalue(g, gval(n));
    }
  }
  genlink(g, obj2gco(h));
}
References Table::array, clearkey(), genlink(), gnode, gnodelast, gval, isempty, keyisnil, lua_assert, luaH_realasize(), markkey, markvalue, and obj2gco.
Referenced by traversetable().
traversetable()
static lu_mem traversetable (global_State * g, Table * h) static
Definition at line 536 of file lua-5.4.3/src/lgc.c.
{
  const char *weakkey, *weakvalue;
  const TValue *mode = gfasttm(g, h->metatable, TM_MODE);
  markobjectN(g, h->metatable);
  if (mode && ttisstring(mode) &&  /* is there a weak mode? */
      (cast_void(weakkey = strchr(svalue(mode), 'k')),
       cast_void(weakvalue = strchr(svalue(mode), 'v')),
       (weakkey || weakvalue))) {  /* is really weak? */
    if (!weakkey)  /* strong keys? */
      traverseweakvalue(g, h);
    else if (!weakvalue)  /* strong values? */
      traverseephemeron(g, h, 0);
    else  /* all weak */
      linkgclist(h, g->allweak);  /* nothing to traverse now */
  }
  else  /* not weak */
    traversestrongtable(g, h);
  return 1 + h->alimit + 2 * allocsizenode(h);
}
References Table::alimit, allocsizenode, global_State::allweak, cast_void, gfasttm, linkgclist, markobjectN, Table::metatable, svalue, TM_MODE, traverseephemeron(), traversestrongtable(), traverseweakvalue(), and ttisstring.
Referenced by propagatemark().
traversethread()
static int traversethread (global_State * g, lua_State * th) static
Definition at line 621 of file lua-5.4.3/src/lgc.c.
{
  UpVal *uv;
  StkId o = th->stack;
  if (isold(th) || g->gcstate == GCSpropagate)
    linkgclist(th, g->grayagain);  /* insert into 'grayagain' list */
  if (o == NULL)
    return 1;  /* stack not completely built yet */
  lua_assert(g->gcstate == GCSatomic ||
             th->openupval == NULL || isintwups(th));
  for (; o < th->top; o++)  /* mark live elements in the stack */
    markvalue(g, s2v(o));
  for (uv = th->openupval; uv != NULL; uv = uv->u.open.next)
    markobject(g, uv);  /* open upvalues cannot be collected */
  if (g->gcstate == GCSatomic) {  /* final traversal? */
    for (; o < th->stack_last + EXTRA_STACK; o++)
      setnilvalue(s2v(o));  /* clear dead stack slice */
    /* 'remarkupvals' may have removed thread from 'twups' list */
    if (!isintwups(th) && th->openupval != NULL) {
      th->twups = g->twups;  /* link it back to the list */
      g->twups = th;
    }
  }
  else if (!g->gcemergency)
    luaD_shrinkstack(th); /* do not change stack in emergency cycle */
  return 1 + stacksize(th);
}
References EXTRA_STACK, global_State::gcemergency, GCSatomic, GCSpropagate, global_State::gcstate, global_State::grayagain, isintwups, isold, linkgclist, lua_assert, luaD_shrinkstack(), markobject, markvalue, UpVal::next, NULL, UpVal::open, lua_State::openupval, s2v, setnilvalue, lua_State::stack, lua_State::stack_last, stacksize, lua_State::top, global_State::twups, lua_State::twups, and UpVal::u.
Referenced by propagatemark().
traverseudata()
static int traverseudata (global_State * g, Udata * u) static
Definition at line 557 of file lua-5.4.3/src/lgc.c.
{
  int i;
  markobjectN(g, u->metatable);  /* mark its metatable */
  for (i = 0; i < u->nuvalue; i++)
    markvalue(g, &u->uv[i].uv);
  genlink(g, obj2gco(u));
  return 1 + u->nuvalue;
}
References genlink(), markobjectN, markvalue, Udata::metatable, Udata::nuvalue, obj2gco, and Udata::uv.
Referenced by propagatemark().
traverseweakvalue()
static void traverseweakvalue (global_State * g, Table * h) static
Definition at line 440 of file lua-5.4.3/src/lgc.c.
{
  Node *n, *limit = gnodelast(h);
  /* if there is array part, assume it may have white values (it is not
     worth traversing it now just to check) */
  int hasclears = (h->alimit > 0);
  for (n = gnode(h, 0); n < limit; n++) {  /* traverse hash part */
    if (isempty(gval(n)))  /* entry is empty? */
      clearkey(n);  /* clear its key */
    else {
      lua_assert(!keyisnil(n));
      markkey(g, n);
      if (!hasclears && iscleared(g, gcvalueN(gval(n))))  /* a white value? */
        hasclears = 1;  /* table will have to be cleared */
    }
  }
  if (g->gcstate == GCSatomic && hasclears)
    linkgclist(h, g->weak);  /* has to be cleared later */
  else
    linkgclist(h, g->grayagain);  /* must retraverse it in atomic phase */
}
References Table::alimit, clearkey(), GCSatomic, global_State::gcstate, gcvalueN, gnode, gnodelast, global_State::grayagain, gval, iscleared(), isempty, keyisnil, linkgclist, lua_assert, markkey, and global_State::weak.
Referenced by traversetable().
udata2finalize()
static GCObject * udata2finalize (global_State * g) static
Definition at line 878 of file lua-5.4.3/src/lgc.c.
{
  GCObject *o = g->tobefnz;  /* get first element */
  lua_assert(tofinalize(o));
  g->tobefnz = o->next;  /* remove it from 'tobefnz' list */
  o->next = g->allgc;  /* return it to 'allgc' list */
  g->allgc = o;
  resetbit(o->marked, FINALIZEDBIT);  /* object is "normal" again */
  if (issweepphase(g))
    makewhite(g, o);  /* "sweep" object */
  else if (getage(o) == G_OLD1)
    g->firstold1 = o;  /* it is the first OLD1 object in the list */
  return o;
}
References global_State::allgc, FINALIZEDBIT, global_State::firstold1, G_OLD1, getage, issweepphase, lua_assert, makewhite, resetbit, global_State::tobefnz, and tofinalize.
Referenced by GCTM().
whitelist()
static void whitelist (global_State * g, GCObject * p) static
Definition at line 1129 of file lua-5.4.3/src/lgc.c.
{
  int white = luaC_white(g);
  for (; p != NULL; p = p->next)
    p->marked = cast_byte((p->marked & ~maskgcbits) | white);
}
References cast_byte, luaC_white, maskgcbits, and NULL.
Referenced by enterinc().
youngcollection()
static void youngcollection (lua_State * L, global_State * g) static
Definition at line 1224 of file lua-5.4.3/src/lgc.c.
{
  GCObject **psurvival;  /* to point to first non-dead survival object */
  GCObject *dummy;  /* dummy out parameter to 'sweepgen' */
  lua_assert(g->gcstate == GCSpropagate);
  if (g->firstold1) {  /* are there regular OLD1 objects? */
    markold(g, g->firstold1, g->reallyold);  /* mark them */
    g->firstold1 = NULL;  /* no more OLD1 objects (for now) */
  }
  markold(g, g->finobj, g->finobjrold);
  markold(g, g->tobefnz, NULL);
  atomic(L);
  /* sweep nursery and get a pointer to its last live element */
  g->gcstate = GCSswpallgc;
  psurvival = sweepgen(L, g, &g->allgc, g->survival, &g->firstold1);
  /* sweep 'survival' */
  sweepgen(L, g, psurvival, g->old1, &g->firstold1);
  g->reallyold = g->old1;
  g->old1 = *psurvival;  /* 'survival' survivals are old now */
  g->survival = g->allgc;  /* all news are survivals */
  /* repeat for 'finobj' lists */
  dummy = NULL;  /* no 'firstold1' optimization for 'finobj' lists */
  psurvival = sweepgen(L, g, &g->finobj, g->finobjsur, &dummy);
  /* sweep 'survival' */
  sweepgen(L, g, psurvival, g->finobjold1, &dummy);
  g->finobjrold = g->finobjold1;
  g->finobjold1 = *psurvival;  /* 'survival' survivals are old now */
  g->finobjsur = g->finobj;  /* all news are survivals */
  sweepgen(L, g, &g->tobefnz, NULL, &dummy);
  finishgencycle(L, g);
}
References global_State::allgc, atomic(), dummy, finishgencycle(), global_State::finobj, global_State::finobjold1, global_State::finobjrold, global_State::finobjsur, global_State::firstold1, GCSpropagate, GCSswpallgc, global_State::gcstate, lua_assert, markold(), NULL, global_State::old1, global_State::reallyold, global_State::survival, sweepgen(), and global_State::tobefnz.
Referenced by genstep().