Github User Fetcher: ldo.c File Reference
ldo.c File Reference
#include "lprefix.h"
#include <setjmp.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lundump.h"
#include "lvm.h"
#include "lzio.h"
Data Structures
struct lua_longjmp
struct CloseP
struct SParser
Macros
#define ldo_c
#define LUA_CORE
#define errorstatus(s) ((s) > LUA_YIELD)
#define LUAI_THROW(L, c) longjmp((c)->b, 1)
#define LUAI_TRY(L, c, a) if (setjmp((c)->b) == 0) { a }
#define luai_jmpbuf jmp_buf
#define ERRORSTACKSIZE (LUAI_MAXSTACK + 200)
#define next_ci(L) (L->ci->next ? L->ci->next : luaE_extendCI(L))
Functions
void luaD_seterrorobj (lua_State *L, int errcode, StkId oldtop)
l_noret luaD_throw (lua_State *L, int errcode)
int luaD_rawrunprotected (lua_State *L, Pfunc f, void *ud)
static void correctstack (lua_State *L, StkId oldstack, StkId newstack)
int luaD_reallocstack (lua_State *L, int newsize, int raiseerror)
int luaD_growstack (lua_State *L, int n, int raiseerror)
static int stackinuse (lua_State *L)
void luaD_shrinkstack (lua_State *L)
void luaD_inctop (lua_State *L)
void luaD_hook (lua_State *L, int event, int line, int ftransfer, int ntransfer)
void luaD_hookcall (lua_State *L, CallInfo *ci)
static void rethook (lua_State *L, CallInfo *ci, int nres)
void luaD_tryfuncTM (lua_State *L, StkId func)
static void moveresults (lua_State *L, StkId res, int nres, int wanted)
void luaD_poscall (lua_State *L, CallInfo *ci, int nres)
void luaD_pretailcall (lua_State *L, CallInfo *ci, StkId func, int narg1)
CallInfo * luaD_precall (lua_State *L, StkId func, int nresults)
static void ccall (lua_State *L, StkId func, int nResults, int inc)
void luaD_call (lua_State *L, StkId func, int nResults)
void luaD_callnoyield (lua_State *L, StkId func, int nResults)
static int finishpcallk (lua_State *L, CallInfo *ci)
static void finishCcall (lua_State *L, CallInfo *ci)
static void unroll (lua_State *L, void *ud)
static CallInfo * findpcall (lua_State *L)
static int resume_error (lua_State *L, const char *msg, int narg)
static void resume (lua_State *L, void *ud)
static int precover (lua_State *L, int status)
LUA_API int lua_resume (lua_State *L, lua_State *from, int nargs, int *nresults)
LUA_API int lua_isyieldable (lua_State *L)
LUA_API int lua_yieldk (lua_State *L, int nresults, lua_KContext ctx, lua_KFunction k)
static void closepaux (lua_State *L, void *ud)
int luaD_closeprotected (lua_State *L, ptrdiff_t level, int status)
int luaD_pcall (lua_State *L, Pfunc func, void *u, ptrdiff_t old_top, ptrdiff_t ef)
static void checkmode (lua_State *L, const char *mode, const char *x)
static void f_parser (lua_State *L, void *ud)
int luaD_protectedparser (lua_State *L, ZIO *z, const char *name, const char *mode)
Macro Definition Documentation
ERRORSTACKSIZE
#define ERRORSTACKSIZE (LUAI_MAXSTACK + 200)
Definition at line 177 of file lua-5.4.3/src/ldo.c.
Referenced by luaD_growstack(), and luaD_reallocstack().
errorstatus
#define errorstatus (s) ((s) > LUA_YIELD)
Definition at line 38 of file lua-5.4.3/src/ldo.c.
Referenced by lua_resume(), luaD_seterrorobj(), and precover().
ldo_c
#define ldo_c
Definition at line 7 of file lua-5.4.3/src/ldo.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/ldo.c.
luai_jmpbuf
#define luai_jmpbuf jmp_buf
Definition at line 75 of file lua-5.4.3/src/ldo.c.
LUAI_THROW
#define LUAI_THROW (L, c) longjmp((c)->b, 1)
Definition at line 73 of file lua-5.4.3/src/ldo.c.
Referenced by luaD_throw().
LUAI_TRY
#define LUAI_TRY (L, c, a) if (setjmp((c)->b) == 0) { a }
Definition at line 74 of file lua-5.4.3/src/ldo.c.
Referenced by luaD_rawrunprotected().
next_ci
#define next_ci (L) (L->ci->next ? L->ci->next : luaE_extendCI(L))
Definition at line 473 of file lua-5.4.3/src/ldo.c.
Referenced by luaD_precall().
Function Documentation
ccall()
static void ccall (lua_State * L, StkId func, int nResults, int inc) static
Definition at line 570 of file lua-5.4.3/src/ldo.c.
{
  CallInfo *ci;
  L->nCcalls += inc;
  if (l_unlikely(getCcalls(L) >= LUAI_MAXCCALLS))
    luaE_checkcstack(L);
  if ((ci = luaD_precall(L, func, nResults)) != NULL) {  /* Lua function? */
    ci->callstatus = CIST_FRESH;  /* mark that it is a "fresh" execute */
    luaV_execute(L, ci);  /* call it */
  }
  L->nCcalls -= inc;
}
References CallInfo::callstatus, CIST_FRESH, getCcalls, luaD_precall(), luaE_checkcstack(), LUAI_MAXCCALLS, luaV_execute(), lua_State::nCcalls, and NULL.
Referenced by luaD_call(), luaD_callnoyield(), and resume().
checkmode()
static void checkmode (lua_State * L, const char * mode, const char * x) static
Definition at line 918 of file lua-5.4.3/src/ldo.c.
{
  if (mode && strchr(mode, x[0]) == NULL) {
    luaO_pushfstring(L,
       "attempt to load a %s chunk (mode is '%s')", x, mode);
    luaD_throw(L, LUA_ERRSYNTAX);
  }
}
References LUA_ERRSYNTAX, luaD_throw(), luaO_pushfstring(), and NULL.
Referenced by f_parser().
closepaux()
static void closepaux (lua_State * L, void * ud) static
Definition at line 853 of file lua-5.4.3/src/ldo.c.
{
  struct CloseP *pcl = cast(struct CloseP *, ud);
  luaF_close(L, pcl->level, pcl->status, 0);
}
References cast, CloseP::level, luaF_close(), and CloseP::status.
Referenced by luaD_closeprotected().
correctstack()
static void correctstack (lua_State * L, StkId oldstack, StkId newstack) static
Definition at line 160 of file lua-5.4.3/src/ldo.c.
{
  CallInfo *ci;
  UpVal *up;
  L->top = (L->top - oldstack) + newstack;
  L->tbclist = (L->tbclist - oldstack) + newstack;
  for (up = L->openupval; up != NULL; up = up->u.open.next)
    up->v = s2v((uplevel(up) - oldstack) + newstack);
  for (ci = L->ci; ci != NULL; ci = ci->previous) {
    ci->top = (ci->top - oldstack) + newstack;
    ci->func = (ci->func - oldstack) + newstack;
    if (isLua(ci))
      ci->u.l.trap = 1;  /* signal to update 'trap' in 'luaV_execute' */
  }
}
References lua_State::ci, CallInfo::func, isLua, CallInfo::l, UpVal::next, NULL, UpVal::open, lua_State::openupval, CallInfo::previous, s2v, lua_State::tbclist, CallInfo::top, lua_State::top, CallInfo::trap, UpVal::u, CallInfo::u, uplevel, and UpVal::v.
Referenced by luaD_reallocstack().
f_parser()
static void f_parser (lua_State * L, void * ud) static
Definition at line 927 of file lua-5.4.3/src/ldo.c.
{
  LClosure *cl;
  struct SParser *p = cast(struct SParser *, ud);
  int c = zgetc(p->z);  /* read first character */
  if (c == LUA_SIGNATURE[0]) {
    checkmode(L, p->mode, "binary");
    cl = luaU_undump(L, p->z, p->name);
  }
  else {
    checkmode(L, p->mode, "text");
    cl = luaY_parser(L, p->z, &p->buff, &p->dyd, p->name, c);
  }
  lua_assert(cl->nupvalues == cl->p->sizeupvalues);
  luaF_initupvals(L, cl);
}
References SParser::buff, cast, checkmode(), SParser::dyd, lua_assert, LUA_SIGNATURE, luaF_initupvals(), luaU_undump(), luaY_parser(), SParser::mode, SParser::name, LClosure::p, Proto::sizeupvalues, SParser::z, and zgetc.
Referenced by luaD_protectedparser().
findpcall()
static CallInfo * findpcall (lua_State * L) static
Definition at line 695 of file lua-5.4.3/src/ldo.c.
{
  CallInfo *ci;
  for (ci = L->ci; ci != NULL; ci = ci->previous) {  /* search for a pcall */
    if (ci->callstatus & CIST_YPCALL)
      return ci;
  }
  return NULL;  /* no pending pcall */
}
References CallInfo::callstatus, lua_State::ci, CIST_YPCALL, NULL, and CallInfo::previous.
Referenced by precover().
finishCcall()
static void finishCcall (lua_State * L, CallInfo * ci) static
Definition at line 649 of file lua-5.4.3/src/ldo.c.
{
  int n;  /* actual number of results from C function */
  if (ci->callstatus & CIST_CLSRET) {  /* was returning? */
    lua_assert(hastocloseCfunc(ci->nresults));
    n = ci->u2.nres;  /* just redo 'luaD_poscall' */
    /* don't need to reset CIST_CLSRET, as it will be set again anyway */
  }
  else {
    int status = LUA_YIELD;  /* default if there were no errors */
    /* must have a continuation and must be able to call it */
    lua_assert(ci->u.c.k != NULL && yieldable(L));
    if (ci->callstatus & CIST_YPCALL)   /* was inside a 'lua_pcallk'? */
      status = finishpcallk(L, ci);  /* finish it */
    adjustresults(L, LUA_MULTRET);  /* finish 'lua_callk' */
    lua_unlock(L);
    n = (*ci->u.c.k)(L, status, ci->u.c.ctx);  /* call continuation */
    lua_lock(L);
    api_checknelems(L, n);
  }
  luaD_poscall(L, ci, n);  /* finish 'luaD_call' */
}
References adjustresults, api_checknelems, CallInfo::c, CallInfo::callstatus, CIST_CLSRET, CIST_YPCALL, CallInfo::ctx, finishpcallk(), hastocloseCfunc, CallInfo::k, lua_assert, lua_lock, LUA_MULTRET, lua_unlock, LUA_YIELD, luaD_poscall(), CallInfo::nres, CallInfo::nresults, NULL, lua_longjmp::status, CallInfo::u, CallInfo::u2, and yieldable.
Referenced by unroll().
finishpcallk()
static int finishpcallk (lua_State * L, CallInfo * ci) static
Definition at line 615 of file lua-5.4.3/src/ldo.c.
{
  int status = getcistrecst(ci);  /* get original status */
  if (l_likely(status == LUA_OK))  /* no error? */
    status = LUA_YIELD;  /* was interrupted by an yield */
  else {  /* error */
    StkId func = restorestack(L, ci->u2.funcidx);
    L->allowhook = getoah(ci->callstatus);  /* restore 'allowhook' */
    luaF_close(L, func, status, 1);  /* can yield or raise an error */
    func = restorestack(L, ci->u2.funcidx);  /* stack may be moved */
    luaD_seterrorobj(L, status, func);
    luaD_shrinkstack(L);   /* restore stack size in case of overflow */
    setcistrecst(ci, LUA_OK);  /* clear original status */
  }
  ci->callstatus &= ~CIST_YPCALL;
  L->errfunc = ci->u.c.old_errfunc;
  /* if it is here, there were errors or yields; unlike 'lua_pcallk',
     do not change status */
  return status;
}
References lua_State::allowhook, CallInfo::c, CallInfo::callstatus, lua_State::errfunc, CallInfo::funcidx, getcistrecst, getoah, LUA_OK, LUA_YIELD, luaD_seterrorobj(), luaD_shrinkstack(), luaF_close(), CallInfo::old_errfunc, restorestack, setcistrecst, lua_longjmp::status, CallInfo::u, and CallInfo::u2.
Referenced by finishCcall().
lua_isyieldable()
LUA_API int lua_isyieldable (lua_State * L)
Definition at line 805 of file lua-5.4.3/src/ldo.c.
{
  return yieldable(L);
}
References yieldable.
lua_resume()
LUA_API int lua_resume (lua_State * L, lua_State * from, int nargs, int * nresults)
Definition at line 773 of file lua-5.4.3/src/ldo.c.
{
  int status;
  lua_lock(L);
  if (L->status == LUA_OK) {  /* may be starting a coroutine */
    if (L->ci != &L->base_ci)  /* not in base level? */
      return resume_error(L, "cannot resume non-suspended coroutine", nargs);
    else if (L->top - (L->ci->func + 1) == nargs)  /* no function? */
      return resume_error(L, "cannot resume dead coroutine", nargs);
  }
  else if (L->status != LUA_YIELD)  /* ended with errors? */
    return resume_error(L, "cannot resume dead coroutine", nargs);
  L->nCcalls = (from) ? getCcalls(from) : 0;
  luai_userstateresume(L, nargs);
  api_checknelems(L, (L->status == LUA_OK) ? nargs + 1 : nargs);
  status = luaD_rawrunprotected(L, resume, &nargs);
   /* continue running after recoverable errors */
  status = precover(L, status);
  if (l_likely(!errorstatus(status)))
    lua_assert(status == L->status);  /* normal end or yield */
  else {  /* unrecoverable error */
    L->status = cast_byte(status);  /* mark thread as 'dead' */
    luaD_seterrorobj(L, status, L->top);  /* push error message */
    L->ci->top = L->top;
  }
  *nresults = (status == LUA_YIELD) ? L->ci->u2.nyield
                                    : cast_int(L->top - (L->ci->func + 1));
  lua_unlock(L);
  return status;
}
References api_checknelems, lua_State::base_ci, cast_byte, cast_int, lua_State::ci, errorstatus, CallInfo::func, getCcalls, lua_assert, lua_lock, LUA_OK, lua_unlock, LUA_YIELD, luaD_rawrunprotected(), luaD_seterrorobj(), luai_userstateresume, lua_State::nCcalls, CallInfo::nyield, precover(), resume(), resume_error(), lua_longjmp::status, lua_State::status, CallInfo::top, lua_State::top, and CallInfo::u2.
lua_yieldk()
LUA_API int lua_yieldk (lua_State * L, int nresults, lua_KContext ctx, lua_KFunction k)
Definition at line 810 of file lua-5.4.3/src/ldo.c.
{
  CallInfo *ci;
  luai_userstateyield(L, nresults);
  lua_lock(L);
  ci = L->ci;
  api_checknelems(L, nresults);
  if (l_unlikely(!yieldable(L))) {
    if (L != G(L)->mainthread)
      luaG_runerror(L, "attempt to yield across a C-call boundary");
    else
      luaG_runerror(L, "attempt to yield from outside a coroutine");
  }
  L->status = LUA_YIELD;
  ci->u2.nyield = nresults;  /* save number of results */
  if (isLua(ci)) {  /* inside a hook? */
    lua_assert(!isLuacode(ci));
    api_check(L, nresults == 0, "hooks cannot yield values");
    api_check(L, k == NULL, "hooks cannot continue after yielding");
  }
  else {
    if ((ci->u.c.k = k) != NULL)  /* is there a continuation? */
      ci->u.c.ctx = ctx;  /* save context */
    luaD_throw(L, LUA_YIELD);
  }
  lua_assert(ci->callstatus & CIST_HOOKED);  /* must be inside a hook */
  lua_unlock(L);
  return 0;  /* return to 'luaD_hook' */
}
References api_check, api_checknelems, CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, CallInfo::ctx, G, isLua, isLuacode, CallInfo::k, lua_assert, lua_lock, lua_unlock, LUA_YIELD, luaD_throw(), luaG_runerror(), luai_userstateyield, NULL, CallInfo::nyield, lua_State::status, CallInfo::u, CallInfo::u2, and yieldable.
luaD_call()
void luaD_call (lua_State * L, StkId func, int nResults)
Definition at line 586 of file lua-5.4.3/src/ldo.c.
{
  ccall(L, func, nResults, 1);
}
References ccall().
luaD_callnoyield()
void luaD_callnoyield (lua_State * L, StkId func, int nResults)
Definition at line 594 of file lua-5.4.3/src/ldo.c.
{
  ccall(L, func, nResults, nyci);
}
References ccall(), and nyci.
luaD_closeprotected()
int luaD_closeprotected (lua_State * L, ptrdiff_t level, int status)
Definition at line 863 of file lua-5.4.3/src/ldo.c.
{
  CallInfo *old_ci = L->ci;
  lu_byte old_allowhooks = L->allowhook;
  for (;;) {  /* keep closing upvalues until no more errors */
    struct CloseP pcl;
    pcl.level = restorestack(L, level); pcl.status = status;
    status = luaD_rawrunprotected(L, &closepaux, &pcl);
    if (l_likely(status == LUA_OK))  /* no more errors? */
      return pcl.status;
    else {  /* an error occurred; restore saved state and repeat */
      L->ci = old_ci;
      L->allowhook = old_allowhooks;
    }
  }
}
References lua_State::allowhook, lua_State::ci, closepaux(), CloseP::level, LUA_OK, luaD_rawrunprotected(), restorestack, and CloseP::status.
Referenced by close_state(), luaD_pcall(), and luaE_resetthread().
luaD_growstack()
int luaD_growstack (lua_State * L, int n, int raiseerror)
Definition at line 219 of file lua-5.4.3/src/ldo.c.
{
  int size = stacksize(L);
  if (l_unlikely(size > LUAI_MAXSTACK)) {
    /* if stack is larger than maximum, thread is already using the
       extra space reserved for errors, that is, thread is handling
       a stack error; cannot grow further than that. */
    lua_assert(stacksize(L) == ERRORSTACKSIZE);
    if (raiseerror)
      luaD_throw(L, LUA_ERRERR);  /* error inside message handler */
    return 0;  /* if not 'raiseerror', just signal it */
  }
  else {
    int newsize = 2 * size;  /* tentative new size */
    int needed = cast_int(L->top - L->stack) + n;
    if (newsize > LUAI_MAXSTACK)  /* cannot cross the limit */
      newsize = LUAI_MAXSTACK;
    if (newsize < needed)  /* but must respect what was asked for */
      newsize = needed;
    if (l_likely(newsize <= LUAI_MAXSTACK))
      return luaD_reallocstack(L, newsize, raiseerror);
    else {  /* stack overflow */
      /* add extra size to be able to handle the error message */
      luaD_reallocstack(L, ERRORSTACKSIZE, raiseerror);
      if (raiseerror)
        luaG_runerror(L, "stack overflow");
      return 0;
    }
  }
}
References cast_int, ERRORSTACKSIZE, lua_assert, LUA_ERRERR, luaD_reallocstack(), luaD_throw(), luaG_runerror(), LUAI_MAXSTACK, lua_State::stack, stacksize, and lua_State::top.
luaD_hook()
void luaD_hook (lua_State * L, int event, int line, int ftransfer, int ntransfer)
Definition at line 306 of file lua-5.4.3/src/ldo.c.
{
  lua_Hook hook = L->hook;
  if (hook && L->allowhook) {  /* make sure there is a hook */
    int mask = CIST_HOOKED;
    CallInfo *ci = L->ci;
    ptrdiff_t top = savestack(L, L->top);  /* preserve original 'top' */
    ptrdiff_t ci_top = savestack(L, ci->top);  /* idem for 'ci->top' */
    lua_Debug ar;
    ar.event = event;
    ar.currentline = line;
    ar.i_ci = ci;
    if (ntransfer != 0) {
      mask |= CIST_TRAN;  /* 'ci' has transfer information */
      ci->u2.transferinfo.ftransfer = ftransfer;
      ci->u2.transferinfo.ntransfer = ntransfer;
    }
    if (isLua(ci) && L->top < ci->top)
      L->top = ci->top;  /* protect entire activation register */
    luaD_checkstack(L, LUA_MINSTACK);  /* ensure minimum stack size */
    if (ci->top < L->top + LUA_MINSTACK)
      ci->top = L->top + LUA_MINSTACK;
    L->allowhook = 0;  /* cannot call hooks inside a hook */
    ci->callstatus |= mask;
    lua_unlock(L);
    (*hook)(L, &ar);
    lua_lock(L);
    lua_assert(!L->allowhook);
    L->allowhook = 1;
    ci->top = restorestack(L, ci_top);
    L->top = restorestack(L, top);
    ci->callstatus &= ~mask;
  }
}
References lua_State::allowhook, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, CIST_TRAN, lua_Debug::currentline, lua_Debug::event, CallInfo::ftransfer, lua_State::hook, lua_Debug::i_ci, isLua, lua_assert, lua_lock, LUA_MINSTACK, lua_unlock, luaD_checkstack, mask, CallInfo::ntransfer, restorestack, savestack, CallInfo::top, lua_State::top, CallInfo::transferinfo, and CallInfo::u2.
Referenced by luaD_hookcall(), luaD_precall(), and rethook().
luaD_hookcall()
void luaD_hookcall (lua_State * L, CallInfo * ci)
Definition at line 347 of file lua-5.4.3/src/ldo.c.
{
  L->oldpc = 0;  /* set 'oldpc' for new function */
  if (L->hookmask & LUA_MASKCALL) {  /* is call hook on? */
    int event = (ci->callstatus & CIST_TAIL) ? LUA_HOOKTAILCALL
                                             : LUA_HOOKCALL;
    Proto *p = ci_func(ci)->p;
    ci->u.l.savedpc++;  /* hooks assume 'pc' is already incremented */
    luaD_hook(L, event, -1, 1, p->numparams);
    ci->u.l.savedpc--;  /* correct 'pc' */
  }
}
References CallInfo::callstatus, ci_func, CIST_TAIL, lua_State::hookmask, CallInfo::l, LUA_HOOKCALL, LUA_HOOKTAILCALL, LUA_MASKCALL, luaD_hook(), Proto::numparams, lua_State::oldpc, Proto::p, CallInfo::savedpc, and CallInfo::u.
Referenced by luaV_execute().
luaD_inctop()
void luaD_inctop (lua_State * L)
Definition at line 293 of file lua-5.4.3/src/ldo.c.
{
  luaD_checkstack(L, 1);
  L->top++;
}
References luaD_checkstack, and lua_State::top.
luaD_pcall()
int luaD_pcall (lua_State * L, Pfunc func, void * u, ptrdiff_t old_top, ptrdiff_t ef)
Definition at line 885 of file lua-5.4.3/src/ldo.c.
{
  int status;
  CallInfo *old_ci = L->ci;
  lu_byte old_allowhooks = L->allowhook;
  ptrdiff_t old_errfunc = L->errfunc;
  L->errfunc = ef;
  status = luaD_rawrunprotected(L, func, u);
  if (l_unlikely(status != LUA_OK)) {  /* an error occurred? */
    L->ci = old_ci;
    L->allowhook = old_allowhooks;
    status = luaD_closeprotected(L, old_top, status);
    luaD_seterrorobj(L, status, restorestack(L, old_top));
    luaD_shrinkstack(L);   /* restore stack size in case of overflow */
  }
  L->errfunc = old_errfunc;
  return status;
}
References lua_State::allowhook, lua_State::ci, lua_State::errfunc, LUA_OK, luaD_closeprotected(), luaD_rawrunprotected(), luaD_seterrorobj(), luaD_shrinkstack(), restorestack, and CloseP::status.
Referenced by luaD_protectedparser().
luaD_poscall()
void luaD_poscall (lua_State * L, CallInfo * ci, int nres)
Definition at line 459 of file lua-5.4.3/src/ldo.c.
{
  int wanted = ci->nresults;
  if (l_unlikely(L->hookmask && !hastocloseCfunc(wanted)))
    rethook(L, ci, nres);
  /* move results to proper place */
  moveresults(L, ci->func, nres, wanted);
  /* function cannot be in any of these cases when returning */
  lua_assert(!(ci->callstatus &
        (CIST_HOOKED | CIST_YPCALL | CIST_FIN | CIST_TRAN | CIST_CLSRET)));
  L->ci = ci->previous;  /* back to caller (after closing variables) */
}
References CallInfo::callstatus, lua_State::ci, CIST_CLSRET, CIST_FIN, CIST_HOOKED, CIST_TRAN, CIST_YPCALL, CallInfo::func, hastocloseCfunc, lua_State::hookmask, lua_assert, moveresults(), CallInfo::nresults, CallInfo::previous, and rethook().
Referenced by finishCcall(), luaD_precall(), and resume().
luaD_precall()
CallInfo * luaD_precall (lua_State * L, StkId func, int nresults)
Definition at line 508 of file lua-5.4.3/src/ldo.c.
{
  lua_CFunction f;
 retry:
  switch (ttypetag(s2v(func))) {
    case LUA_VCCL:  /* C closure */
      f = clCvalue(s2v(func))->f;
      goto Cfunc;
    case LUA_VLCF:  /* light C function */
      f = fvalue(s2v(func));
     Cfunc: {
      int n;  /* number of returns */
      CallInfo *ci;
      checkstackGCp(L, LUA_MINSTACK, func);  /* ensure minimum stack size */
      L->ci = ci = next_ci(L);
      ci->nresults = nresults;
      ci->callstatus = CIST_C;
      ci->top = L->top + LUA_MINSTACK;
      ci->func = func;
      lua_assert(ci->top <= L->stack_last);
      if (l_unlikely(L->hookmask & LUA_MASKCALL)) {
        int narg = cast_int(L->top - func) - 1;
        luaD_hook(L, LUA_HOOKCALL, -1, 1, narg);
      }
      lua_unlock(L);
      n = (*f)(L);  /* do the actual call */
      lua_lock(L);
      api_checknelems(L, n);
      luaD_poscall(L, ci, n);
      return NULL;
    }
    case LUA_VLCL: {  /* Lua function */
      CallInfo *ci;
      Proto *p = clLvalue(s2v(func))->p;
      int narg = cast_int(L->top - func) - 1;  /* number of real arguments */
      int nfixparams = p->numparams;
      int fsize = p->maxstacksize;  /* frame size */
      checkstackGCp(L, fsize, func);
      L->ci = ci = next_ci(L);
      ci->nresults = nresults;
      ci->u.l.savedpc = p->code;  /* starting point */
      ci->top = func + 1 + fsize;
      ci->func = func;
      L->ci = ci;
      for (; narg < nfixparams; narg++)
        setnilvalue(s2v(L->top++));  /* complete missing arguments */
      lua_assert(ci->top <= L->stack_last);
      return ci;
    }
    default: {  /* not a function */
      checkstackGCp(L, 1, func);  /* space for metamethod */
      luaD_tryfuncTM(L, func);  /* try to get '__call' metamethod */
      goto retry;  /* try again with metamethod */
    }
  }
}
References api_checknelems, CallInfo::callstatus, cast_int, checkstackGCp, lua_State::ci, CIST_C, clCvalue, clLvalue, Proto::code, CallInfo::func, fvalue, lua_State::hookmask, CallInfo::l, lua_assert, LUA_HOOKCALL, lua_lock, LUA_MASKCALL, LUA_MINSTACK, lua_unlock, LUA_VCCL, LUA_VLCF, LUA_VLCL, luaD_hook(), luaD_poscall(), luaD_tryfuncTM(), Proto::maxstacksize, next_ci, CallInfo::nresults, NULL, Proto::numparams, Proto::p, s2v, CallInfo::savedpc, setnilvalue, lua_State::stack_last, CallInfo::top, lua_State::top, ttypetag, and CallInfo::u.
Referenced by ccall().
luaD_pretailcall()
void luaD_pretailcall (lua_State * L, CallInfo * ci, StkId func, int narg1)
Definition at line 481 of file lua-5.4.3/src/ldo.c.
{
  Proto *p = clLvalue(s2v(func))->p;
  int fsize = p->maxstacksize;  /* frame size */
  int nfixparams = p->numparams;
  int i;
  for (i = 0; i < narg1; i++)  /* move down function and arguments */
    setobjs2s(L, ci->func + i, func + i);
  checkstackGC(L, fsize);
  func = ci->func;  /* moved-down function */
  for (; narg1 <= nfixparams; narg1++)
    setnilvalue(s2v(func + narg1));  /* complete missing arguments */
  ci->top = func + 1 + fsize;  /* top for new function */
  lua_assert(ci->top <= L->stack_last);
  ci->u.l.savedpc = p->code;  /* starting point */
  ci->callstatus |= CIST_TAIL;
  L->top = func + narg1;  /* set top */
}
References CallInfo::callstatus, checkstackGC, CIST_TAIL, clLvalue, Proto::code, CallInfo::func, CallInfo::l, lua_assert, Proto::maxstacksize, Proto::numparams, Proto::p, s2v, CallInfo::savedpc, setnilvalue, setobjs2s, lua_State::stack_last, CallInfo::top, lua_State::top, and CallInfo::u.
Referenced by luaV_execute().
luaD_protectedparser()
int luaD_protectedparser (lua_State * L, ZIO * z, const char * name, const char * mode)
Definition at line 944 of file lua-5.4.3/src/ldo.c.
{
  struct SParser p;
  int status;
  incnny(L);  /* cannot yield during parsing */
  p.z = z; p.name = name; p.mode = mode;
  p.dyd.actvar.arr = NULL; p.dyd.actvar.size = 0;
  p.dyd.gt.arr = NULL; p.dyd.gt.size = 0;
  p.dyd.label.arr = NULL; p.dyd.label.size = 0;
  luaZ_initbuffer(L, &p.buff);
  status = luaD_pcall(L, f_parser, &p, savestack(L, L->top), L->errfunc);
  luaZ_freebuffer(L, &p.buff);
  luaM_freearray(L, p.dyd.actvar.arr, p.dyd.actvar.size);
  luaM_freearray(L, p.dyd.gt.arr, p.dyd.gt.size);
  luaM_freearray(L, p.dyd.label.arr, p.dyd.label.size);
  decnny(L);
  return status;
}
References Dyndata::actvar, Labellist::arr, Dyndata::arr, SParser::buff, decnny, SParser::dyd, lua_State::errfunc, f_parser(), Dyndata::gt, incnny, Dyndata::label, luaD_pcall(), luaM_freearray, luaZ_freebuffer, luaZ_initbuffer, SParser::mode, name, SParser::name, NULL, savestack, Labellist::size, Dyndata::size, lua_State::top, and SParser::z.
luaD_rawrunprotected()
int luaD_rawrunprotected (lua_State * L, Pfunc f, void * ud)
Definition at line 138 of file lua-5.4.3/src/ldo.c.
{
  l_uint32 oldnCcalls = L->nCcalls;
  struct lua_longjmp lj;
  lj.status = LUA_OK;
  lj.previous = L->errorJmp;  /* chain new error handler */
  L->errorJmp = &lj;
  LUAI_TRY(L, &lj,
    (*f)(L, ud);
  );
  L->errorJmp = lj.previous;  /* restore old error handler */
  L->nCcalls = oldnCcalls;
  return lj.status;
}
References lua_State::errorJmp, LUA_OK, LUAI_TRY, lua_State::nCcalls, lua_longjmp::previous, and lua_longjmp::status.
Referenced by lua_resume(), luaD_closeprotected(), luaD_pcall(), and precover().
luaD_reallocstack()
int luaD_reallocstack (lua_State * L, int newsize, int raiseerror)
Definition at line 191 of file lua-5.4.3/src/ldo.c.
{
  int oldsize = stacksize(L);
  int i;
  StkId newstack = luaM_reallocvector(L, NULL, 0,
                                      newsize + EXTRA_STACK, StackValue);
  lua_assert(newsize <= LUAI_MAXSTACK || newsize == ERRORSTACKSIZE);
  if (l_unlikely(newstack == NULL)) {  /* reallocation failed? */
    if (raiseerror)
      luaM_error(L);
    else return 0;  /* do not raise an error */
  }
  /* number of elements to be copied to the new stack */
  i = ((oldsize <= newsize) ? oldsize : newsize) + EXTRA_STACK;
  memcpy(newstack, L->stack, i * sizeof(StackValue));
  for (; i < newsize + EXTRA_STACK; i++)
    setnilvalue(s2v(newstack + i)); /* erase new segment */
  correctstack(L, L->stack, newstack);
  luaM_freearray(L, L->stack, oldsize + EXTRA_STACK);
  L->stack = newstack;
  L->stack_last = L->stack + newsize;
  return 1;
}
References correctstack(), ERRORSTACKSIZE, EXTRA_STACK, lua_assert, LUAI_MAXSTACK, luaM_error, luaM_freearray, luaM_reallocvector, NULL, s2v, setnilvalue, lua_State::stack, lua_State::stack_last, and stacksize.
Referenced by luaD_growstack(), and luaD_shrinkstack().
luaD_seterrorobj()
void luaD_seterrorobj (lua_State * L, int errcode, StkId oldtop)
Definition at line 91 of file lua-5.4.3/src/ldo.c.
{
  switch (errcode) {
    case LUA_ERRMEM: {  /* memory error? */
      setsvalue2s(L, oldtop, G(L)->memerrmsg); /* reuse preregistered msg. */
      break;
    }
    case LUA_ERRERR: {
      setsvalue2s(L, oldtop, luaS_newliteral(L, "error in error handling"));
      break;
    }
    case LUA_OK: {  /* special case only for closing upvalues */
      setnilvalue(s2v(oldtop));  /* no error message */
      break;
    }
    default: {
      lua_assert(errorstatus(errcode));  /* real error */
      setobjs2s(L, oldtop, L->top - 1);  /* error message on current top */
      break;
    }
  }
  L->top = oldtop + 1;
}
References errorstatus, G, lua_assert, LUA_ERRERR, LUA_ERRMEM, LUA_OK, luaS_newliteral, s2v, setnilvalue, setobjs2s, setsvalue2s, and lua_State::top.
Referenced by finishpcallk(), lua_resume(), and luaD_pcall().
luaD_shrinkstack()
void luaD_shrinkstack (lua_State * L)
Definition at line 274 of file lua-5.4.3/src/ldo.c.
{
  int inuse = stackinuse(L);
  int nsize = inuse * 2;  /* proposed new size */
  int max = inuse * 3;  /* maximum "reasonable" size */
  if (max > LUAI_MAXSTACK) {
    max = LUAI_MAXSTACK;  /* respect stack limit */
    if (nsize > LUAI_MAXSTACK)
      nsize = LUAI_MAXSTACK;
  }
  /* if thread is currently not handling a stack overflow and its
     size is larger than maximum "reasonable" size, shrink it */
  if (inuse <= LUAI_MAXSTACK && stacksize(L) > max)
    luaD_reallocstack(L, nsize, 0);  /* ok if that fails */
  else  /* don't change stack */
    condmovestack(L,{},{});  /* (change only for debugging) */
  luaE_shrinkCI(L);  /* shrink CI list */
}
References condmovestack, luaD_reallocstack(), luaE_shrinkCI(), LUAI_MAXSTACK, stackinuse(), and stacksize.
Referenced by finishpcallk(), and luaD_pcall().
luaD_throw()
l_noret luaD_throw (lua_State * L, int errcode)
Definition at line 115 of file lua-5.4.3/src/ldo.c.
{
  if (L->errorJmp) {  /* thread has an error handler? */
    L->errorJmp->status = errcode;  /* set status */
    LUAI_THROW(L, L->errorJmp);  /* jump to it */
  }
  else {  /* thread has no error handler */
    global_State *g = G(L);
    errcode = luaE_resetthread(L, errcode);  /* close all upvalues */
    if (g->mainthread->errorJmp) {  /* main thread has a handler? */
      setobjs2s(L, g->mainthread->top++, L->top - 1);  /* copy error obj. */
      luaD_throw(g->mainthread, errcode);  /* re-throw in main thread */
    }
    else {  /* no handler at all; abort */
      if (g->panic) {  /* panic function? */
        lua_unlock(L);
        g->panic(L);  /* call panic function (last chance to jump out) */
      }
      abort();
    }
  }
}
References lua_State::errorJmp, G, lua_unlock, luaD_throw(), luaE_resetthread(), LUAI_THROW, global_State::mainthread, global_State::panic, setobjs2s, lua_longjmp::status, and lua_State::top.
Referenced by checkmode(), lua_yieldk(), luaD_growstack(), and luaD_throw().
luaD_tryfuncTM()
void luaD_tryfuncTM (lua_State * L, StkId func)
Definition at line 390 of file lua-5.4.3/src/ldo.c.
{
  const TValue *tm = luaT_gettmbyobj(L, s2v(func), TM_CALL);
  StkId p;
  if (l_unlikely(ttisnil(tm)))
    luaG_callerror(L, s2v(func));  /* nothing to call */
  for (p = L->top; p > func; p--)  /* open space for metamethod */
    setobjs2s(L, p, p-1);
  L->top++;  /* stack space pre-allocated by the caller */
  setobj2s(L, func, tm);  /* metamethod is the new function to be called */
}
References luaG_callerror(), luaT_gettmbyobj(), s2v, setobj2s, setobjs2s, TM_CALL, lua_State::top, and ttisnil.
Referenced by luaD_precall(), and luaV_execute().
moveresults()
static void moveresults (lua_State * L, StkId res, int nres, int wanted) static
Definition at line 408 of file lua-5.4.3/src/ldo.c.
{
  StkId firstresult;
  int i;
  switch (wanted) {  /* handle typical cases separately */
    case 0:  /* no values needed */
      L->top = res;
      return;
    case 1:  /* one value needed */
      if (nres == 0)   /* no results? */
        setnilvalue(s2v(res));  /* adjust with nil */
      else  /* at least one result */
        setobjs2s(L, res, L->top - nres);  /* move it to proper place */
      L->top = res + 1;
      return;
    case LUA_MULTRET:
      wanted = nres;  /* we want all results */
      break;
    default:  /* two/more results and/or to-be-closed variables */
      if (hastocloseCfunc(wanted)) {  /* to-be-closed variables? */
        ptrdiff_t savedres = savestack(L, res);
        L->ci->callstatus |= CIST_CLSRET;  /* in case of yields */
        L->ci->u2.nres = nres;
        luaF_close(L, res, CLOSEKTOP, 1);
        L->ci->callstatus &= ~CIST_CLSRET;
        if (L->hookmask)  /* if needed, call hook after '__close's */
          rethook(L, L->ci, nres);
        res = restorestack(L, savedres);  /* close and hook can move stack */
        wanted = decodeNresults(wanted);
        if (wanted == LUA_MULTRET)
          wanted = nres;  /* we want all results */
      }
      break;
  }
  /* generic case */
  firstresult = L->top - nres;  /* index of first result */
  if (nres > wanted)  /* extra results? */
    nres = wanted;  /* don't need them */
  for (i = 0; i < nres; i++)  /* move all results to correct place */
    setobjs2s(L, res + i, firstresult + i);
  for (; i < wanted; i++)  /* complete wanted number of results */
    setnilvalue(s2v(res + i));
  L->top = res + wanted;  /* top points after the last result */
}
References CallInfo::callstatus, lua_State::ci, CIST_CLSRET, CLOSEKTOP, decodeNresults, hastocloseCfunc, lua_State::hookmask, LUA_MULTRET, luaF_close(), CallInfo::nres, restorestack, rethook(), s2v, savestack, setnilvalue, setobjs2s, lua_State::top, and CallInfo::u2.
Referenced by luaD_poscall().
precover()
static int precover (lua_State * L, int status) static
Definition at line 762 of file lua-5.4.3/src/ldo.c.
{
  CallInfo *ci;
  while (errorstatus(status) && (ci = findpcall(L)) != NULL) {
    L->ci = ci;  /* go down to recovery functions */
    setcistrecst(ci, status);  /* status to finish 'pcall' */
    status = luaD_rawrunprotected(L, unroll, NULL);
  }
  return status;
}
References lua_State::ci, errorstatus, findpcall(), luaD_rawrunprotected(), NULL, setcistrecst, lua_longjmp::status, and unroll().
Referenced by lua_resume().
resume()
static void resume (lua_State * L, void * ud) static
Definition at line 726 of file lua-5.4.3/src/ldo.c.
{
  int n = *(cast(int*, ud));  /* number of arguments */
  StkId firstArg = L->top - n;  /* first argument */
  CallInfo *ci = L->ci;
  if (L->status == LUA_OK)  /* starting a coroutine? */
    ccall(L, firstArg - 1, LUA_MULTRET, 1);  /* just call its body */
  else {  /* resuming from previous yield */
    lua_assert(L->status == LUA_YIELD);
    L->status = LUA_OK;  /* mark that it is running (again) */
    luaE_incCstack(L);  /* control the C stack */
    if (isLua(ci)) {  /* yielded inside a hook? */
      L->top = firstArg;  /* discard arguments */
      luaV_execute(L, ci);  /* just continue running Lua code */
    }
    else {  /* 'common' yield */
      if (ci->u.c.k != NULL) {  /* does it have a continuation function? */
        lua_unlock(L);
        n = (*ci->u.c.k)(L, LUA_YIELD, ci->u.c.ctx); /* call continuation */
        lua_lock(L);
        api_checknelems(L, n);
      }
      luaD_poscall(L, ci, n);  /* finish 'luaD_call' */
    }
    unroll(L, NULL);  /* run continuation */
  }
}
References api_checknelems, CallInfo::c, cast, ccall(), lua_State::ci, CallInfo::ctx, isLua, CallInfo::k, lua_assert, lua_lock, LUA_MULTRET, LUA_OK, lua_unlock, LUA_YIELD, luaD_poscall(), luaE_incCstack(), luaV_execute(), NULL, lua_State::status, lua_State::top, CallInfo::u, and unroll().
Referenced by lua_resume().
resume_error()
static int resume_error (lua_State * L, const char * msg, int narg) static
Definition at line 710 of file lua-5.4.3/src/ldo.c.
{
  L->top -= narg;  /* remove args from the stack */
  setsvalue2s(L, L->top, luaS_new(L, msg));  /* push error message */
  api_incr_top(L);
  lua_unlock(L);
  return LUA_ERRRUN;
}
References api_incr_top, LUA_ERRRUN, lua_unlock, luaS_new, setsvalue2s, and lua_State::top.
Referenced by lua_resume().
rethook()
static void rethook (lua_State * L, CallInfo * ci, int nres) static
Definition at line 365 of file lua-5.4.3/src/ldo.c.
{
  if (L->hookmask & LUA_MASKRET) {  /* is return hook on? */
    StkId firstres = L->top - nres;  /* index of first result */
    int delta = 0;  /* correction for vararg functions */
    int ftransfer;
    if (isLua(ci)) {
      Proto *p = ci_func(ci)->p;
      if (p->is_vararg)
        delta = ci->u.l.nextraargs + p->numparams + 1;
    }
    ci->func += delta;  /* if vararg, back to virtual 'func' */
    ftransfer = cast(unsigned short, firstres - ci->func);
    luaD_hook(L, LUA_HOOKRET, -1, ftransfer, nres);  /* call it */
    ci->func -= delta;
  }
  if (isLua(ci = ci->previous))
    L->oldpc = pcRel(ci->u.l.savedpc, ci_func(ci)->p);  /* set 'oldpc' */
}
References cast, ci_func, CallInfo::func, lua_State::hookmask, Proto::is_vararg, isLua, CallInfo::l, LUA_HOOKRET, LUA_MASKRET, luaD_hook(), CallInfo::nextraargs, Proto::numparams, lua_State::oldpc, Proto::p, pcRel, CallInfo::previous, CallInfo::savedpc, lua_State::top, and CallInfo::u.
Referenced by luaD_poscall(), and moveresults().
stackinuse()
static int stackinuse (lua_State * L) static
Definition at line 250 of file lua-5.4.3/src/ldo.c.
{
  CallInfo *ci;
  int res;
  StkId lim = L->top;
  for (ci = L->ci; ci != NULL; ci = ci->previous) {
    if (lim < ci->top) lim = ci->top;
  }
  lua_assert(lim <= L->stack_last);
  res = cast_int(lim - L->stack) + 1;  /* part of stack in use */
  if (res < LUA_MINSTACK)
    res = LUA_MINSTACK;  /* ensure a minimum size */
  return res;
}
References cast_int, lua_State::ci, lua_assert, LUA_MINSTACK, NULL, CallInfo::previous, lua_State::stack, CallInfo::top, and lua_State::top.
Referenced by luaD_shrinkstack().
unroll()
static void unroll (lua_State * L, void * ud) static
Definition at line 677 of file lua-5.4.3/src/ldo.c.
{
  CallInfo *ci;
  UNUSED(ud);
  while ((ci = L->ci) != &L->base_ci) {  /* something in the stack */
    if (!isLua(ci))  /* C function? */
      finishCcall(L, ci);  /* complete its execution */
    else {  /* Lua function */
      luaV_finishOp(L);  /* finish interrupted instruction */
      luaV_execute(L, ci);  /* execute down to higher C 'boundary' */
    }
  }
}
References lua_State::base_ci, lua_State::ci, finishCcall(), isLua, luaV_execute(), luaV_finishOp(), and UNUSED.
Referenced by precover(), and resume().