Github User Fetcher: lcorolib.c File Reference
lcorolib.c File Reference
#include "lprefix.h"
#include <stdlib.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lcorolib_c
#define LUA_LIB
#define COS_RUN 0
#define COS_DEAD 1
#define COS_YIELD 2
#define COS_NORM 3
Functions
static lua_State * getco (lua_State *L)
static int auxresume (lua_State *L, lua_State *co, int narg)
static int luaB_coresume (lua_State *L)
static int luaB_auxwrap (lua_State *L)
static int luaB_cocreate (lua_State *L)
static int luaB_cowrap (lua_State *L)
static int luaB_yield (lua_State *L)
static int auxstatus (lua_State *L, lua_State *co)
static int luaB_costatus (lua_State *L)
static int luaB_yieldable (lua_State *L)
static int luaB_corunning (lua_State *L)
static int luaB_close (lua_State *L)
LUAMOD_API int luaopen_coroutine (lua_State *L)
Variables
static const char *const statname []
static const luaL_Reg co_funcs []
Macro Definition Documentation
COS_DEAD
#define COS_DEAD 1
Definition at line 118 of file lua-5.4.3/src/lcorolib.c.
Referenced by auxstatus(), and luaB_close().
COS_NORM
#define COS_NORM 3
Definition at line 120 of file lua-5.4.3/src/lcorolib.c.
Referenced by auxstatus().
COS_RUN
#define COS_RUN 0
Definition at line 117 of file lua-5.4.3/src/lcorolib.c.
Referenced by auxstatus().
COS_YIELD
#define COS_YIELD 2
Definition at line 119 of file lua-5.4.3/src/lcorolib.c.
Referenced by auxstatus(), and luaB_close().
lcorolib_c
#define lcorolib_c
Definition at line 7 of file lua-5.4.3/src/lcorolib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.4.3/src/lcorolib.c.
Function Documentation
auxresume()
static int auxresume (lua_State * L, lua_State * co, int narg) static
Definition at line 32 of file lua-5.4.3/src/lcorolib.c.
{
  int status, nres;
  if (l_unlikely(!lua_checkstack(co, narg))) {
    lua_pushliteral(L, "too many arguments to resume");
    return -1;  /* error flag */
  }
  lua_xmove(L, co, narg);
  status = lua_resume(co, L, narg, &nres);
  if (l_likely(status == LUA_OK || status == LUA_YIELD)) {
    if (l_unlikely(!lua_checkstack(L, nres + 1))) {
      lua_pop(co, nres);  /* remove results anyway */
      lua_pushliteral(L, "too many results to resume");
      return -1;  /* error flag */
    }
    lua_xmove(co, L, nres);  /* move yielded values */
    return nres;
  }
  else {
    lua_xmove(co, L, 1);  /* move error message */
    return -1;  /* error flag */
  }
}
References lua_checkstack(), LUA_OK, lua_pop, lua_pushliteral, lua_resume(), lua_xmove(), and LUA_YIELD.
Referenced by luaB_auxwrap(), and luaB_coresume().
auxstatus()
static int auxstatus (lua_State * L, lua_State * co) static
Definition at line 127 of file lua-5.4.3/src/lcorolib.c.
{
  if (L == co) return COS_RUN;
  else {
    switch (lua_status(co)) {
      case LUA_YIELD:
        return COS_YIELD;
      case LUA_OK: {
        lua_Debug ar;
        if (lua_getstack(co, 0, &ar))  /* does it have frames? */
          return COS_NORM;  /* it is running */
        else if (lua_gettop(co) == 0)
            return COS_DEAD;
        else
          return COS_YIELD;  /* initial state */
      }
      default:  /* some error occurred */
        return COS_DEAD;
    }
  }
}
References COS_DEAD, COS_NORM, COS_RUN, COS_YIELD, lua_getstack(), lua_gettop(), LUA_OK, lua_status(), and LUA_YIELD.
Referenced by luaB_close(), and luaB_costatus().
getco()
static lua_State * getco (lua_State * L) static
Definition at line 21 of file lua-5.4.3/src/lcorolib.c.
{
  lua_State *co = lua_tothread(L, 1);
  luaL_argexpected(L, co, 1, "thread");
  return co;
}
References lua_tothread(), and luaL_argexpected.
Referenced by luaB_close(), luaB_coresume(), luaB_costatus(), and luaB_yieldable().
luaB_auxwrap()
static int luaB_auxwrap (lua_State * L) static
Definition at line 73 of file lua-5.4.3/src/lcorolib.c.
{
  lua_State *co = lua_tothread(L, lua_upvalueindex(1));
  int r = auxresume(L, co, lua_gettop(L));
  if (l_unlikely(r < 0)) {  /* error? */
    int stat = lua_status(co);
    if (stat != LUA_OK && stat != LUA_YIELD) {  /* error in the coroutine? */
      stat = lua_resetthread(co);  /* close its tbc variables */
      lua_assert(stat != LUA_OK);
      lua_xmove(co, L, 1);  /* copy error message */
    }
    if (stat != LUA_ERRMEM &&  /* not a memory error and ... */
        lua_type(L, -1) == LUA_TSTRING) {  /* ... error object is a string? */
      luaL_where(L, 1);  /* add extra info, if available */
      lua_insert(L, -2);
      lua_concat(L, 2);
    }
    return lua_error(L);  /* propagate error */
  }
  return r;
}
References auxresume(), lua_assert, lua_concat(), LUA_ERRMEM, lua_error(), lua_gettop(), lua_insert, LUA_OK, lua_resetthread(), lua_status(), lua_tothread(), LUA_TSTRING, lua_type(), lua_upvalueindex, lua_xmove(), LUA_YIELD, and luaL_where().
Referenced by luaB_cowrap().
luaB_close()
static int luaB_close (lua_State * L) static
Definition at line 170 of file lua-5.4.3/src/lcorolib.c.
{
  lua_State *co = getco(L);
  int status = auxstatus(L, co);
  switch (status) {
    case COS_DEAD: case COS_YIELD: {
      status = lua_resetthread(co);
      if (status == LUA_OK) {
        lua_pushboolean(L, 1);
        return 1;
      }
      else {
        lua_pushboolean(L, 0);
        lua_xmove(co, L, 1);  /* copy error message */
        return 2;
      }
    }
    default:  /* normal or running coroutine */
      return luaL_error(L, "cannot close a %s coroutine", statname[status]);
  }
}
References auxstatus(), COS_DEAD, COS_YIELD, getco(), LUA_OK, lua_pushboolean(), lua_resetthread(), lua_xmove(), luaL_error(), and statname.
luaB_cocreate()
static int luaB_cocreate (lua_State * L) static
Definition at line 95 of file lua-5.4.3/src/lcorolib.c.
{
  lua_State *NL;
  luaL_checktype(L, 1, LUA_TFUNCTION);
  NL = lua_newthread(L);
  lua_pushvalue(L, 1);  /* move function to top */
  lua_xmove(L, NL, 1);  /* move function from L to NL */
  return 1;
}
References lua_newthread(), lua_pushvalue(), LUA_TFUNCTION, lua_xmove(), and luaL_checktype().
Referenced by luaB_cowrap().
luaB_coresume()
static int luaB_coresume (lua_State * L) static
Definition at line 56 of file lua-5.4.3/src/lcorolib.c.
{
  lua_State *co = getco(L);
  int r;
  r = auxresume(L, co, lua_gettop(L) - 1);
  if (l_unlikely(r < 0)) {
    lua_pushboolean(L, 0);
    lua_insert(L, -2);
    return 2;  /* return false + error message */
  }
  else {
    lua_pushboolean(L, 1);
    lua_insert(L, -(r + 1));
    return r + 1;  /* return true + 'resume' returns */
  }
}
References auxresume(), getco(), lua_gettop(), lua_insert, and lua_pushboolean().
luaB_corunning()
static int luaB_corunning (lua_State * L) static
Definition at line 163 of file lua-5.4.3/src/lcorolib.c.
{
  int ismain = lua_pushthread(L);
  lua_pushboolean(L, ismain);
  return 2;
}
References lua_pushboolean(), and lua_pushthread().
luaB_costatus()
static int luaB_costatus (lua_State * L) static
Definition at line 149 of file lua-5.4.3/src/lcorolib.c.
{
  lua_State *co = getco(L);
  lua_pushstring(L, statname[auxstatus(L, co)]);
  return 1;
}
References auxstatus(), getco(), lua_pushstring(), and statname.
luaB_cowrap()
static int luaB_cowrap (lua_State * L) static
Definition at line 105 of file lua-5.4.3/src/lcorolib.c.
{
  luaB_cocreate(L);
  lua_pushcclosure(L, luaB_auxwrap, 1);
  return 1;
}
References lua_pushcclosure(), luaB_auxwrap(), and luaB_cocreate().
luaB_yield()
static int luaB_yield (lua_State * L) static
Definition at line 112 of file lua-5.4.3/src/lcorolib.c.
{
  return lua_yield(L, lua_gettop(L));
}
References lua_gettop(), and lua_yield.
luaB_yieldable()
static int luaB_yieldable (lua_State * L) static
Definition at line 156 of file lua-5.4.3/src/lcorolib.c.
{
  lua_State *co = lua_isnone(L, 1) ? L : getco(L);
  lua_pushboolean(L, lua_isyieldable(co));
  return 1;
}
References getco(), lua_isnone, lua_isyieldable(), and lua_pushboolean().
luaopen_coroutine()
LUAMOD_API int luaopen_coroutine (lua_State * L)
Definition at line 206 of file lua-5.4.3/src/lcorolib.c.
{
  luaL_newlib(L, co_funcs);
  return 1;
}
References co_funcs, and luaL_newlib.
Variable Documentation
co_funcs
const luaL_Reg co_funcs[] static
Initial value:
= {
  {"create", luaB_cocreate},
  {"resume", luaB_coresume},
  {"running", luaB_corunning},
  {"status", luaB_costatus},
  {"wrap", luaB_cowrap},
  {"yield", luaB_yield},
  {"isyieldable", luaB_yieldable},
  {"close", luaB_close},
  {NULL, NULL}
}
Definition at line 192 of file lua-5.4.3/src/lcorolib.c.
{
  {"create", luaB_cocreate},
  {"resume", luaB_coresume},
  {"running", luaB_corunning},
  {"status", luaB_costatus},
  {"wrap", luaB_cowrap},
  {"yield", luaB_yield},
  {"isyieldable", luaB_yieldable},
  {"close", luaB_close},
  {NULL, NULL}
};
Referenced by luaopen_coroutine().
statname
const char* const statname[] static
Initial value:
=
  {"running", "dead", "suspended", "normal"}
Definition at line 123 of file lua-5.4.3/src/lcorolib.c.
  {"running", "dead", "suspended", "normal"};
Referenced by luaB_close(), and luaB_costatus().