Github User Fetcher: llex.c File Reference
llex.c File Reference
#include <ctype.h>
#include <locale.h>
#include <string.h>
#include "lua.h"
#include "ldo.h"
#include "llex.h"
#include "lobject.h"
#include "lparser.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "lzio.h"
Macros
#define llex_c
#define LUA_CORE
#define next(ls) (ls->current = zgetc(ls->z))
#define currIsNewline(ls) (ls->current == '\n' || ls->current == '\r')
#define save_and_next(ls) (save(ls, ls->current), next(ls))
#define MAXSRC 80
Functions
static void save (LexState *ls, int c)
void luaX_init (lua_State *L)
const char * luaX_token2str (LexState *ls, int token)
static const char * txtToken (LexState *ls, int token)
void luaX_lexerror (LexState *ls, const char *msg, int token)
void luaX_syntaxerror (LexState *ls, const char *msg)
TString * luaX_newstring (LexState *ls, const char *str, size_t l)
static void inclinenumber (LexState *ls)
void luaX_setinput (lua_State *L, LexState *ls, ZIO *z, TString *source)
static int check_next (LexState *ls, const char *set)
static void buffreplace (LexState *ls, char from, char to)
static void trydecpoint (LexState *ls, SemInfo *seminfo)
static void read_numeral (LexState *ls, SemInfo *seminfo)
static int skip_sep (LexState *ls)
static void read_long_string (LexState *ls, SemInfo *seminfo, int sep)
static void read_string (LexState *ls, int del, SemInfo *seminfo)
static int llex (LexState *ls, SemInfo *seminfo)
void luaX_next (LexState *ls)
void luaX_lookahead (LexState *ls)
Variables
const char *const luaX_tokens []
Macro Definition Documentation
currIsNewline
#define currIsNewline (ls) (ls->current == '\n' || ls->current == '\r')
Definition at line 33 of file lua-5.1.5/src/llex.c.
Referenced by inclinenumber(), llex(), and read_long_string().
llex_c
#define llex_c
Definition at line 12 of file lua-5.1.5/src/llex.c.
LUA_CORE
#define LUA_CORE
Definition at line 13 of file lua-5.1.5/src/llex.c.
MAXSRC
#define MAXSRC 80
Definition at line 75 of file lua-5.1.5/src/llex.c.
Referenced by luaX_lexerror().
next
#define next (ls) (ls->current = zgetc(ls->z))
Definition at line 28 of file lua-5.1.5/src/llex.c.
Referenced by convergeephemerons(), convergeephemerons(), convergeephemerons(), correctgraylist(), deletelist(), duk__case_transform_helper(), duk__compact_object_list(), duk__free_allocated(), duk__free_markandsweep_finalize_list(), duk__free_refzero_list(), duk__free_run_finalizers(), duk__free_stringtable(), duk__run_object_finalizers(), duk__sweep_heap(), duk_unicode_case_convert_string(), getOverflowPage(), inclinenumber(), iter_aux(), iter_aux(), llex(), luaE_freeCI(), luaE_shrinkCI(), luaK_concat(), luaK_patchclose(), luaS_resize(), luaX_setinput(), newupval(), patchlistaux(), patchlistaux(), patchlistaux(), patchlistaux(), read_long_string(), and read_string().
save_and_next
#define save_and_next (ls) (save(ls, ls->current), next(ls))
Definition at line 48 of file lua-5.1.5/src/llex.c.
Referenced by check_next(), llex(), read_long_string(), read_numeral(), read_string(), and skip_sep().
Function Documentation
buffreplace()
static void buffreplace (LexState * ls, char from, char to) static
Definition at line 171 of file lua-5.1.5/src/llex.c.
{
  size_t n = luaZ_bufflen(ls->buff);
  char *p = luaZ_buffer(ls->buff);
  while (n--)
    if (p[n] == from) p[n] = to;
}
References LexState::buff, luaZ_buffer, and luaZ_bufflen.
Referenced by read_numeral(), and trydecpoint().
check_next()
static int check_next (LexState * ls, const char * set) static
Definition at line 163 of file lua-5.1.5/src/llex.c.
{
  if (!strchr(set, ls->current))
    return 0;
  save_and_next(ls);
  return 1;
}
References LexState::current, and save_and_next.
Referenced by llex(), and read_numeral().
inclinenumber()
static void inclinenumber (LexState * ls) static
Definition at line 129 of file lua-5.1.5/src/llex.c.
{
  int old = ls->current;
  lua_assert(currIsNewline(ls));
  next(ls);  /* skip `\n' or `\r' */
  if (currIsNewline(ls) && ls->current != old)
    next(ls);  /* skip `\n\r' or `\r\n' */
  if (++ls->linenumber >= MAX_INT)
    luaX_syntaxerror(ls, "chunk has too many lines");
}
References LexState::current, currIsNewline, LexState::linenumber, lua_assert, luaX_syntaxerror(), MAX_INT, and next.
Referenced by llex(), read_long_string(), and read_string().
llex()
static int llex (LexState * ls, SemInfo * seminfo) static
Definition at line 334 of file lua-5.1.5/src/llex.c.
{
  luaZ_resetbuffer(ls->buff);
  for (;;) {
    switch (ls->current) {
      case '\n':
      case '\r': {
        inclinenumber(ls);
        continue;
      }
      case '-': {
        next(ls);
        if (ls->current != '-') return '-';
        /* else is a comment */
        next(ls);
        if (ls->current == '[') {
          int sep = skip_sep(ls);
          luaZ_resetbuffer(ls->buff);  /* `skip_sep' may dirty the buffer */
          if (sep >= 0) {
            read_long_string(ls, NULL, sep);  /* long comment */
            luaZ_resetbuffer(ls->buff);
            continue;
          }
        }
        /* else short comment */
        while (!currIsNewline(ls) && ls->current != EOZ)
          next(ls);
        continue;
      }
      case '[': {
        int sep = skip_sep(ls);
        if (sep >= 0) {
          read_long_string(ls, seminfo, sep);
          return TK_STRING;
        }
        else if (sep == -1) return '[';
        else luaX_lexerror(ls, "invalid long string delimiter", TK_STRING);
      }
      case '=': {
        next(ls);
        if (ls->current != '=') return '=';
        else { next(ls); return TK_EQ; }
      }
      case '<': {
        next(ls);
        if (ls->current != '=') return '<';
        else { next(ls); return TK_LE; }
      }
      case '>': {
        next(ls);
        if (ls->current != '=') return '>';
        else { next(ls); return TK_GE; }
      }
      case '~': {
        next(ls);
        if (ls->current != '=') return '~';
        else { next(ls); return TK_NE; }
      }
      case '"':
      case '\'': {
        read_string(ls, ls->current, seminfo);
        return TK_STRING;
      }
      case '.': {
        save_and_next(ls);
        if (check_next(ls, ".")) {
          if (check_next(ls, "."))
            return TK_DOTS;   /* ... */
          else return TK_CONCAT;   /* .. */
        }
        else if (!isdigit(ls->current)) return '.';
        else {
          read_numeral(ls, seminfo);
          return TK_NUMBER;
        }
      }
      case EOZ: {
        return TK_EOS;
      }
      default: {
        if (isspace(ls->current)) {
          lua_assert(!currIsNewline(ls));
          next(ls);
          continue;
        }
        else if (isdigit(ls->current)) {
          read_numeral(ls, seminfo);
          return TK_NUMBER;
        }
        else if (isalpha(ls->current) || ls->current == '_') {
          /* identifier or reserved word */
          TString *ts;
          do {
            save_and_next(ls);
          } while (isalnum(ls->current) || ls->current == '_');
          ts = luaX_newstring(ls, luaZ_buffer(ls->buff),
                                  luaZ_bufflen(ls->buff));
          if (ts->tsv.reserved > 0)  /* reserved word? */
            return ts->tsv.reserved - 1 + FIRST_RESERVED;
          else {
            seminfo->ts = ts;
            return TK_NAME;
          }
        }
        else {
          int c = ls->current;
          next(ls);
          return c;  /* single-char tokens (+ - / ...) */
        }
      }
    }
  }
}
References LexState::buff, check_next(), LexState::current, currIsNewline, EOZ, FIRST_RESERVED, inclinenumber(), lua_assert, luaX_lexerror(), luaX_newstring(), luaZ_buffer, luaZ_bufflen, luaZ_resetbuffer, next, NULL, read_long_string(), read_numeral(), read_string(), TString::reserved, save_and_next, skip_sep(), TK_CONCAT, TK_DOTS, TK_EOS, TK_EQ, TK_GE, TK_LE, TK_NAME, TK_NE, TK_NUMBER, TK_STRING, SemInfo::ts, and TString::tsv.
Referenced by luaX_lookahead(), and luaX_next().
luaX_init()
void luaX_init (lua_State * L)
Definition at line 64 of file lua-5.1.5/src/llex.c.
{
  int i;
  for (i=0; i<NUM_RESERVED; i++) {
    TString *ts = luaS_new(L, luaX_tokens[i]);
    luaS_fix(ts);  /* reserved words are never collected */
    lua_assert(strlen(luaX_tokens[i])+1 <= TOKEN_LEN);
    ts->tsv.reserved = cast_byte(i+1);  /* reserved word */
  }
}
References cast_byte, lua_assert, luaS_fix, luaS_new, luaX_tokens, NUM_RESERVED, TString::reserved, TOKEN_LEN, and TString::tsv.
luaX_lexerror()
void luaX_lexerror (LexState * ls, const char * msg, int token)
Definition at line 102 of file lua-5.1.5/src/llex.c.
{
  char buff[MAXSRC];
  luaO_chunkid(buff, getstr(ls->source), MAXSRC);
  msg = luaO_pushfstring(ls->L, "%s:%d: %s", buff, ls->linenumber, msg);
  if (token)
    luaO_pushfstring(ls->L, "%s near " LUA_QS, msg, txtToken(ls, token));
  luaD_throw(ls->L, LUA_ERRSYNTAX);
}
References getstr, LexState::L, LexState::linenumber, LUA_ERRSYNTAX, LUA_QS, luaD_throw(), luaO_chunkid(), luaO_pushfstring(), MAXSRC, LexState::source, and txtToken().
Referenced by enterlevel(), errorlimit(), llex(), luaX_syntaxerror(), read_long_string(), read_string(), save(), and trydecpoint().
luaX_lookahead()
void luaX_lookahead (LexState * ls)
Definition at line 459 of file lua-5.1.5/src/llex.c.
{
  lua_assert(ls->lookahead.token == TK_EOS);
  ls->lookahead.token = llex(ls, &ls->lookahead.seminfo);
}
References llex(), LexState::lookahead, lua_assert, Token::seminfo, TK_EOS, and Token::token.
Referenced by constructor(), field(), field(), and field().
luaX_newstring()
TString * luaX_newstring (LexState * ls, const char * str, size_t l)
Definition at line 117 of file lua-5.1.5/src/llex.c.
{
  lua_State *L = ls->L;
  TString *ts = luaS_newlstr(L, str, l);
  TValue *o = luaH_setstr(L, ls->fs->h, ts);  /* entry for `str' */
  if (ttisnil(o)) {
    setbvalue(o, 1);  /* make sure `str' will not be collected */
    luaC_checkGC(L);
  }
  return ts;
}
References LexState::fs, FuncState::h, LexState::L, luaC_checkGC, luaH_setstr(), luaS_newlstr(), setbvalue, and ttisnil.
Referenced by anchor_token(), anchor_token(), llex(), new_localvarliteral_(), new_localvarliteral_(), read_long_string(), and read_string().
luaX_next()
void luaX_next (LexState * ls)
Definition at line 448 of file lua-5.1.5/src/llex.c.
{
  ls->lastline = ls->linenumber;
  if (ls->lookahead.token != TK_EOS) {  /* is there a look-ahead token? */
    ls->t = ls->lookahead;  /* use this one */
    ls->lookahead.token = TK_EOS;  /* and discharge it */
  }
  else
    ls->t.token = llex(ls, &ls->t.seminfo);  /* read next token */
}
References LexState::lastline, LexState::linenumber, llex(), LexState::lookahead, Token::seminfo, LexState::t, TK_EOS, and Token::token.
Referenced by breakstat(), checknext(), checknext(), checknext(), checknext(), field(), fieldsel(), fieldsel(), fieldsel(), forstat(), forstat(), forstat(), forstat(), funcargs(), funcargs(), funcargs(), funcargs(), funcstat(), funcstat(), funcstat(), funcstat(), gotostat(), gotostat(), ifstat(), luaY_parser(), mainfunc(), mainfunc(), mainfunc(), parlist(), parlist(), parlist(), parlist(), prefixexp(), primaryexp(), primaryexp(), primaryexp(), primaryexp(), repeatstat(), repeatstat(), repeatstat(), repeatstat(), retstat(), simpleexp(), simpleexp(), simpleexp(), simpleexp(), statement(), statement(), statement(), statement(), str_checkname(), str_checkname(), str_checkname(), str_checkname(), subexpr(), subexpr(), subexpr(), subexpr(), suffixedexp(), suffixedexp(), suffixedexp(), test_then_block(), test_then_block(), test_then_block(), test_then_block(), testnext(), testnext(), testnext(), testnext(), whilestat(), whilestat(), whilestat(), whilestat(), yindex(), yindex(), yindex(), and yindex().
luaX_setinput()
void luaX_setinput (lua_State * L, LexState * ls, ZIO * z, TString * source)
Definition at line 140 of file lua-5.1.5/src/llex.c.
{
  ls->decpoint = '.';
  ls->L = L;
  ls->lookahead.token = TK_EOS;  /* no look-ahead token */
  ls->z = z;
  ls->fs = NULL;
  ls->linenumber = 1;
  ls->lastline = 1;
  ls->source = source;
  luaZ_resizebuffer(ls->L, ls->buff, LUA_MINBUFFER);  /* initialize buffer */
  next(ls);  /* read first char */
}
References LexState::buff, LexState::decpoint, LexState::fs, LexState::L, LexState::lastline, LexState::linenumber, LexState::lookahead, LUA_MINBUFFER, luaZ_resizebuffer, next, NULL, LexState::source, TK_EOS, Token::token, and LexState::z.
Referenced by luaY_parser(), and luaY_parser().
luaX_syntaxerror()
void luaX_syntaxerror (LexState * ls, const char * msg)
Definition at line 112 of file lua-5.1.5/src/llex.c.
{
  luaX_lexerror(ls, msg, ls->t.token);
}
References luaX_lexerror(), LexState::t, and Token::token.
Referenced by breakstat(), check_match(), check_match(), check_match(), check_match(), error_expected(), error_expected(), error_expected(), error_expected(), errorlimit(), errorlimit(), errorlimit(), fixforjump(), fixjump(), fixjump(), fixjump(), fixjump(), forstat(), forstat(), forstat(), forstat(), funcargs(), funcargs(), funcargs(), funcargs(), inclinenumber(), luaK_checkstack(), luaK_semerror(), luaK_setlist(), parlist(), parlist(), parlist(), parlist(), prefixexp(), primaryexp(), primaryexp(), primaryexp(), semerror(), and semerror().
luaX_token2str()
const char * luaX_token2str (LexState * ls, int token)
Definition at line 78 of file lua-5.1.5/src/llex.c.
{
  if (token < FIRST_RESERVED) {
    lua_assert(token == cast(unsigned char, token));
    return (iscntrl(token)) ? luaO_pushfstring(ls->L, "char(%d)", token) :
                              luaO_pushfstring(ls->L, "%c", token);
  }
  else
    return luaX_tokens[token-FIRST_RESERVED];
}
References cast, FIRST_RESERVED, LexState::L, lua_assert, luaO_pushfstring(), and luaX_tokens.
Referenced by check_match(), check_match(), check_match(), check_match(), error_expected(), error_expected(), error_expected(), error_expected(), and txtToken().
read_long_string()
static void read_long_string (LexState * ls, SemInfo * seminfo, int sep) static
Definition at line 223 of file lua-5.1.5/src/llex.c.
{
  int cont = 0;
  (void)(cont);  /* avoid warnings when `cont' is not used */
  save_and_next(ls);  /* skip 2nd `[' */
  if (currIsNewline(ls))  /* string starts with a newline? */
    inclinenumber(ls);  /* skip it */
  for (;;) {
    switch (ls->current) {
      case EOZ:
        luaX_lexerror(ls, (seminfo) ? "unfinished long string" :
                                   "unfinished long comment", TK_EOS);
        break;  /* to avoid warnings */
#if defined(LUA_COMPAT_LSTR)
      case '[': {
        if (skip_sep(ls) == sep) {
          save_and_next(ls);  /* skip 2nd `[' */
          cont++;
#if LUA_COMPAT_LSTR == 1
          if (sep == 0)
            luaX_lexerror(ls, "nesting of [[...]] is deprecated", '[');
#endif
        }
        break;
      }
#endif
      case ']': {
        if (skip_sep(ls) == sep) {
          save_and_next(ls);  /* skip 2nd `]' */
#if defined(LUA_COMPAT_LSTR) && LUA_COMPAT_LSTR == 2
          cont--;
          if (sep == 0 && cont >= 0) break;
#endif
          goto endloop;
        }
        break;
      }
      case '\n':
      case '\r': {
        save(ls, '\n');
        inclinenumber(ls);
        if (!seminfo) luaZ_resetbuffer(ls->buff);  /* avoid wasting space */
        break;
      }
      default: {
        if (seminfo) save_and_next(ls);
        else next(ls);
      }
    }
  } endloop:
  if (seminfo)
    seminfo->ts = luaX_newstring(ls, luaZ_buffer(ls->buff) + (2 + sep),
                                     luaZ_bufflen(ls->buff) - 2*(2 + sep));
}
References LexState::buff, LexState::current, currIsNewline, EOZ, inclinenumber(), luaX_lexerror(), luaX_newstring(), luaZ_buffer, luaZ_bufflen, luaZ_resetbuffer, next, save(), save_and_next, skip_sep(), TK_EOS, and SemInfo::ts.
Referenced by llex().
read_numeral()
static void read_numeral (LexState * ls, SemInfo * seminfo) static
Definition at line 194 of file lua-5.1.5/src/llex.c.
{
  lua_assert(isdigit(ls->current));
  do {
    save_and_next(ls);
  } while (isdigit(ls->current) || ls->current == '.');
  if (check_next(ls, "Ee"))  /* `E'? */
    check_next(ls, "+-");  /* optional exponent sign */
  while (isalnum(ls->current) || ls->current == '_')
    save_and_next(ls);
  save(ls, '\0');
  buffreplace(ls, '.', ls->decpoint);  /* follow locale for decimal point */
  if (!luaO_str2d(luaZ_buffer(ls->buff), &seminfo->r))  /* format error? */
    trydecpoint(ls, seminfo); /* try to update decimal point separator */
}
References LexState::buff, buffreplace(), check_next(), LexState::current, LexState::decpoint, lua_assert, luaO_str2d(), luaZ_buffer, SemInfo::r, save(), save_and_next, and trydecpoint().
Referenced by llex().
read_string()
static void read_string (LexState * ls, int del, SemInfo * seminfo) static
Definition at line 278 of file lua-5.1.5/src/llex.c.
{
  save_and_next(ls);
  while (ls->current != del) {
    switch (ls->current) {
      case EOZ:
        luaX_lexerror(ls, "unfinished string", TK_EOS);
        continue;  /* to avoid warnings */
      case '\n':
      case '\r':
        luaX_lexerror(ls, "unfinished string", TK_STRING);
        continue;  /* to avoid warnings */
      case '\\': {
        int c;
        next(ls);  /* do not save the `\' */
        switch (ls->current) {
          case 'a': c = '\a'; break;
          case 'b': c = '\b'; break;
          case 'f': c = '\f'; break;
          case 'n': c = '\n'; break;
          case 'r': c = '\r'; break;
          case 't': c = '\t'; break;
          case 'v': c = '\v'; break;
          case '\n':  /* go through */
          case '\r': save(ls, '\n'); inclinenumber(ls); continue;
          case EOZ: continue;  /* will raise an error next loop */
          default: {
            if (!isdigit(ls->current))
              save_and_next(ls);  /* handles \\, \", \', and \? */
            else {  /* \xxx */
              int i = 0;
              c = 0;
              do {
                c = 10*c + (ls->current-'0');
                next(ls);
              } while (++i<3 && isdigit(ls->current));
              if (c > UCHAR_MAX)
                luaX_lexerror(ls, "escape sequence too large", TK_STRING);
              save(ls, c);
            }
            continue;
          }
        }
        save(ls, c);
        next(ls);
        continue;
      }
      default:
        save_and_next(ls);
    }
  }
  save_and_next(ls);  /* skip delimiter */
  seminfo->ts = luaX_newstring(ls, luaZ_buffer(ls->buff) + 1,
                                   luaZ_bufflen(ls->buff) - 2);
}
References LexState::buff, LexState::current, EOZ, inclinenumber(), luaX_lexerror(), luaX_newstring(), luaZ_buffer, luaZ_bufflen, next, save(), save_and_next, TK_EOS, TK_STRING, and SemInfo::ts.
Referenced by llex().
save()
static void save (LexState * ls, int c) static
Definition at line 51 of file lua-5.1.5/src/llex.c.
{
  Mbuffer *b = ls->buff;
  if (b->n + 1 > b->buffsize) {
    size_t newsize;
    if (b->buffsize >= MAX_SIZET/2)
      luaX_lexerror(ls, "lexical element too long", 0);
    newsize = b->buffsize * 2;
    luaZ_resizebuffer(ls->L, b, newsize);
  }
  b->buffer[b->n++] = cast(char, c);
}
References LexState::buff, Mbuffer::buffer, Mbuffer::buffsize, cast, LexState::L, luaX_lexerror(), luaZ_resizebuffer, MAX_SIZET, and Mbuffer::n.
Referenced by read_long_string(), read_numeral(), read_string(), and txtToken().
skip_sep()
static int skip_sep (LexState * ls) static
Definition at line 210 of file lua-5.1.5/src/llex.c.
{
  int count = 0;
  int s = ls->current;
  lua_assert(s == '[' || s == ']');
  save_and_next(ls);
  while (ls->current == '=') {
    save_and_next(ls);
    count++;
  }
  return (ls->current == s) ? count : (-count) - 1;
}
References LexState::current, lua_assert, s, and save_and_next.
Referenced by llex(), and read_long_string().
trydecpoint()
static void trydecpoint (LexState * ls, SemInfo * seminfo) static
Definition at line 179 of file lua-5.1.5/src/llex.c.
{
  /* format error: try to update decimal point separator */
  struct lconv *cv = localeconv();
  char old = ls->decpoint;
  ls->decpoint = (cv ? cv->decimal_point[0] : '.');
  buffreplace(ls, old, ls->decpoint);  /* try updated decimal separator */
  if (!luaO_str2d(luaZ_buffer(ls->buff), &seminfo->r)) {
    /* format error with correct decimal point: no more options */
    buffreplace(ls, ls->decpoint, '.');  /* undo change (for error message) */
    luaX_lexerror(ls, "malformed number", TK_NUMBER);
  }
}
References LexState::buff, buffreplace(), LexState::decpoint, luaO_str2d(), luaX_lexerror(), luaZ_buffer, SemInfo::r, and TK_NUMBER.
Referenced by read_numeral().
txtToken()
static const char * txtToken (LexState * ls, int token) static
Definition at line 89 of file lua-5.1.5/src/llex.c.
{
  switch (token) {
    case TK_NAME:
    case TK_STRING:
    case TK_NUMBER:
      save(ls, '\0');
      return luaZ_buffer(ls->buff);
    default:
      return luaX_token2str(ls, token);
  }
}
References LexState::buff, luaX_token2str(), luaZ_buffer, save(), TK_NAME, TK_NUMBER, and TK_STRING.
Referenced by luaX_lexerror().
Variable Documentation
luaX_tokens
const char* const luaX_tokens[]
Initial value:
= {
    "and", "break", "do", "else", "elseif",
    "end", "false", "for", "function", "if",
    "in", "local", "nil", "not", "or", "repeat",
    "return", "then", "true", "until", "while",
    "..", "...", "==", ">=", "<=", "~=",
    "<number>", "<name>", "<string>", "<eof>",
    NULL
}
Definition at line 37 of file lua-5.1.5/src/llex.c.
{
    "and", "break", "do", "else", "elseif",
    "end", "false", "for", "function", "if",
    "in", "local", "nil", "not", "or", "repeat",
    "return", "then", "true", "until", "while",
    "..", "...", "==", ">=", "<=", "~=",
    "<number>", "<name>", "<string>", "<eof>",
    NULL
};
Referenced by luaX_init(), and luaX_token2str().