Github User Fetcher: ltm.h File Reference
ltm.h File Reference
#include "lobject.h"
Macros
#define gfasttm(g, et, e)
#define fasttm(l, et, e) gfasttm(G(l), et, e)
#define ttypename(x) luaT_typenames_[(x) + 1]
Enumerations
enum TMS {
TM_INDEX , TM_NEWINDEX , TM_GC , TM_MODE ,
TM_LEN , TM_EQ , TM_ADD , TM_SUB ,
TM_MUL , TM_MOD , TM_POW , TM_DIV ,
TM_IDIV , TM_BAND , TM_BOR , TM_BXOR ,
TM_SHL , TM_SHR , TM_UNM , TM_BNOT ,
TM_LT , TM_LE , TM_CONCAT , TM_CALL ,
TM_N
}
Functions
LUAI_FUNC const char * luaT_objtypename (lua_State *L, const TValue *o)
LUAI_FUNC const TValue * luaT_gettm (Table *events, TMS event, TString *ename)
LUAI_FUNC const TValue * luaT_gettmbyobj (lua_State *L, const TValue *o, TMS event)
LUAI_FUNC void luaT_init (lua_State *L)
LUAI_FUNC void luaT_callTM (lua_State *L, const TValue *f, const TValue *p1, const TValue *p2, TValue *p3, int hasres)
LUAI_FUNC int luaT_callbinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
LUAI_FUNC void luaT_trybinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
LUAI_FUNC int luaT_callorderTM (lua_State *L, const TValue *p1, const TValue *p2, TMS event)
Variables
LUAI_DDEC const char *const luaT_typenames_ [LUA_TOTALTAGS]
Macro Definition Documentation
fasttm
#define fasttm (l, et, e) gfasttm(G(l), et, e)
Definition at line 51 of file lua-5.3.6/src/ltm.h.
gfasttm
#define gfasttm (g, et, e)
Value:
  ((et) == NULL ? NULL : \
  ((et)->flags & (1u<<(e))) ? NULL : luaT_gettm(et, e, (g)->tmname[e]))
Definition at line 48 of file lua-5.3.6/src/ltm.h.
#define gfasttm(g,et,e) ((et) == NULL ? NULL : \
  ((et)->flags & (1u<<(e))) ? NULL : luaT_gettm(et, e, (g)->tmname[e]))
ttypename
#define ttypename (x) luaT_typenames_[(x) + 1]
Definition at line 53 of file lua-5.3.6/src/ltm.h.
Enumeration Type Documentation
TMS
enum TMS
Enumerator
TM_INDEX
TM_NEWINDEX
TM_GC
TM_MODE
TM_LEN
TM_EQ
TM_ADD
TM_SUB
TM_MUL
TM_MOD
TM_POW
TM_DIV
TM_IDIV
TM_BAND
TM_BOR
TM_BXOR
TM_SHL
TM_SHR
TM_UNM
TM_BNOT
TM_LT
TM_LE
TM_CONCAT
TM_CALL
TM_N
Definition at line 18 of file lua-5.3.6/src/ltm.h.
             {
  TM_INDEX,
  TM_NEWINDEX,
  TM_GC,
  TM_MODE,
  TM_LEN,
  TM_EQ,  /* last tag method with fast access */
  TM_ADD,
  TM_SUB,
  TM_MUL,
  TM_MOD,
  TM_POW,
  TM_DIV,
  TM_IDIV,
  TM_BAND,
  TM_BOR,
  TM_BXOR,
  TM_SHL,
  TM_SHR,
  TM_UNM,
  TM_BNOT,
  TM_LT,
  TM_LE,
  TM_CONCAT,
  TM_CALL,
  TM_N      /* number of elements in the enum */
} TMS;
Function Documentation
luaT_callbinTM()
LUAI_FUNC int luaT_callbinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 124 of file lua-5.3.6/src/ltm.c.
{
  const TValue *tm = luaT_gettmbyobj(L, p1, event);  /* try first operand */
  if (ttisnil(tm))
    tm = luaT_gettmbyobj(L, p2, event);  /* try second operand */
  if (ttisnil(tm)) return 0;
  luaT_callTM(L, tm, p1, p2, res, 1);
  return 1;
}
References luaT_callTM(), luaT_gettmbyobj(), and ttisnil.
Referenced by luaT_callorderTM(), and luaT_trybinTM().
luaT_callorderTM()
LUAI_FUNC int luaT_callorderTM (lua_State * L, const TValue * p1, const TValue * p2, TMS event)
Definition at line 158 of file lua-5.3.6/src/ltm.c.
{
  if (!luaT_callbinTM(L, p1, p2, L->top, event))
    return -1;  /* no metamethod */
  else
    return !l_isfalse(L->top);
}
luaT_callTM()
LUAI_FUNC void luaT_callTM (lua_State * L, const TValue * f, const TValue * p1, const TValue * p2, TValue * p3, int hasres)
Definition at line 102 of file lua-5.3.6/src/ltm.c.
{
  ptrdiff_t result = savestack(L, p3);
  StkId func = L->top;
  setobj2s(L, func, f);  /* push function (assume EXTRA_STACK) */
  setobj2s(L, func + 1, p1);  /* 1st argument */
  setobj2s(L, func + 2, p2);  /* 2nd argument */
  L->top += 3;
  if (!hasres)  /* no result? 'p3' is third argument */
    setobj2s(L, L->top++, p3);  /* 3rd argument */
  /* metamethod may yield only when called from Lua code */
  if (isLua(L->ci))
    luaD_call(L, func, hasres);
  else
    luaD_callnoyield(L, func, hasres);
  if (hasres) {  /* if has result, move it to its place */
    p3 = restorestack(L, result);
    setobjs2s(L, p3, --L->top);
  }
}
References lua_State::ci, isLua, luaD_call(), luaD_callnoyield(), restorestack, savestack, setobj2s, setobjs2s, and lua_State::top.
Referenced by luaT_callbinTM(), luaV_equalobj(), luaV_finishget(), luaV_finishset(), luaV_finishset(), and luaV_objlen().
luaT_gettm()
LUAI_FUNC const TValue * luaT_gettm (Table * events, TMS event, TString * ename)
Definition at line 50 of file lua-5.1.5/src/ltm.c.
{
  const TValue *tm = luaH_getstr(events, ename);
  lua_assert(event <= TM_EQ);
  if (ttisnil(tm)) {  /* no tag method? */
    events->flags |= cast_byte(1u<<event);  /* cache this fact */
    return NULL;
  }
  else return tm;
}
luaT_gettmbyobj()
LUAI_FUNC const TValue * luaT_gettmbyobj (lua_State * L, const TValue * o, TMS event)
Definition at line 61 of file lua-5.1.5/src/ltm.c.
{
  Table *mt;
  switch (ttype(o)) {
    case LUA_TTABLE:
      mt = hvalue(o)->metatable;
      break;
    case LUA_TUSERDATA:
      mt = uvalue(o)->metatable;
      break;
    default:
      mt = G(L)->mt[ttype(o)];
  }
  return (mt ? luaH_getstr(mt, G(L)->tmname[event]) : luaO_nilobject);
}
luaT_init()
LUAI_FUNC void luaT_init (lua_State * L)
Definition at line 30 of file lua-5.1.5/src/ltm.c.
{
  static const char *const luaT_eventname[] = {  /* ORDER TM */
    "__index", "__newindex",
    "__gc", "__mode", "__eq",
    "__add", "__sub", "__mul", "__div", "__mod",
    "__pow", "__unm", "__len", "__lt", "__le",
    "__concat", "__call"
  };
  int i;
  for (i=0; i<TM_N; i++) {
    G(L)->tmname[i] = luaS_new(L, luaT_eventname[i]);
    luaS_fix(G(L)->tmname[i]);  /* never collect these names */
  }
}
luaT_objtypename()
LUAI_FUNC const char * luaT_objtypename (lua_State * L, const TValue * o)
Definition at line 90 of file lua-5.3.6/src/ltm.c.
{
  Table *mt;
  if ((ttistable(o) && (mt = hvalue(o)->metatable) != NULL) ||
      (ttisfulluserdata(o) && (mt = uvalue(o)->metatable) != NULL)) {
    const TValue *name = luaH_getshortstr(mt, luaS_new(L, "__name"));
    if (ttisstring(name))  /* is '__name' a string? */
      return getstr(tsvalue(name));  /* use it as type name */
  }
  return ttypename(ttnov(o));  /* else use standard type name */
}
luaT_trybinTM()
LUAI_FUNC void luaT_trybinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 135 of file lua-5.3.6/src/ltm.c.
{
  if (!luaT_callbinTM(L, p1, p2, res, event)) {
    switch (event) {
      case TM_CONCAT:
        luaG_concaterror(L, p1, p2);
      /* call never returns, but to avoid warnings: *//* FALLTHROUGH */
      case TM_BAND: case TM_BOR: case TM_BXOR:
      case TM_SHL: case TM_SHR: case TM_BNOT: {
        lua_Number dummy;
        if (tonumber(p1, &dummy) && tonumber(p2, &dummy))
          luaG_tointerror(L, p1, p2);
        else
          luaG_opinterror(L, p1, p2, "perform bitwise operation on");
      }
      /* calls never return, but to avoid warnings: *//* FALLTHROUGH */
      default:
        luaG_opinterror(L, p1, p2, "perform arithmetic on");
    }
  }
}
Variable Documentation
luaT_typenames_
LUAI_DDEC const char* const luaT_typenames_[LUA_TOTALTAGS]
Definition at line 55 of file lua-5.3.6/src/ltm.h.