Github User Fetcher: lparser.c File Reference
lparser.c File Reference
#include "lprefix.h"
#include <limits.h>
#include <string.h>
#include "lua.h"
#include "lcode.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "llex.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
Data Structures
struct BlockCnt
struct ConsControl
struct LHS_assign
Macros
#define lparser_c
#define LUA_CORE
#define MAXVARS 200
#define hasmultret(k) ((k) == VCALL || (k) == VVARARG)
#define eqstr(a, b) ((a) == (b))
#define check_condition(ls, c, msg) { if (!(c)) luaX_syntaxerror(ls, msg); }
#define new_localvarliteral(ls, v)
#define enterlevel(ls) luaE_incCstack(ls->L)
#define leavelevel(ls) ((ls)->L->nCcalls--)
#define UNARY_PRIORITY 12 /* priority for unary operators */
Typedefs
typedef struct BlockCnt BlockCnt
typedef struct ConsControl ConsControl
Functions
static void statement (LexState *ls)
static void expr (LexState *ls, expdesc *v)
static l_noret error_expected (LexState *ls, int token)
static l_noret errorlimit (FuncState *fs, int limit, const char *what)
static void checklimit (FuncState *fs, int v, int l, const char *what)
static int testnext (LexState *ls, int c)
static void check (LexState *ls, int c)
static void checknext (LexState *ls, int c)
static void check_match (LexState *ls, int what, int who, int where)
static TString * str_checkname (LexState *ls)
static void init_exp (expdesc *e, expkind k, int i)
static void codestring (expdesc *e, TString *s)
static void codename (LexState *ls, expdesc *e)
static int registerlocalvar (LexState *ls, FuncState *fs, TString *varname)
static int new_localvar (LexState *ls, TString *name)
static Vardesc * getlocalvardesc (FuncState *fs, int vidx)
static int reglevel (FuncState *fs, int nvar)
int luaY_nvarstack (FuncState *fs)
static LocVar * localdebuginfo (FuncState *fs, int vidx)
static void init_var (FuncState *fs, expdesc *e, int vidx)
static void check_readonly (LexState *ls, expdesc *e)
static void adjustlocalvars (LexState *ls, int nvars)
static void removevars (FuncState *fs, int tolevel)
static int searchupvalue (FuncState *fs, TString *name)
static Upvaldesc * allocupvalue (FuncState *fs)
static int newupvalue (FuncState *fs, TString *name, expdesc *v)
static int searchvar (FuncState *fs, TString *n, expdesc *var)
static void markupval (FuncState *fs, int level)
static void singlevaraux (FuncState *fs, TString *n, expdesc *var, int base)
static void singlevar (LexState *ls, expdesc *var)
static void adjust_assign (LexState *ls, int nvars, int nexps, expdesc *e)
static l_noret jumpscopeerror (LexState *ls, Labeldesc *gt)
static void solvegoto (LexState *ls, int g, Labeldesc *label)
static Labeldesc * findlabel (LexState *ls, TString *name)
static int newlabelentry (LexState *ls, Labellist *l, TString *name, int line, int pc)
static int newgotoentry (LexState *ls, TString *name, int line, int pc)
static int solvegotos (LexState *ls, Labeldesc *lb)
static int createlabel (LexState *ls, TString *name, int line, int last)
static void movegotosout (FuncState *fs, BlockCnt *bl)
static void enterblock (FuncState *fs, BlockCnt *bl, lu_byte isloop)
static l_noret undefgoto (LexState *ls, Labeldesc *gt)
static void leaveblock (FuncState *fs)
static Proto * addprototype (LexState *ls)
static void codeclosure (LexState *ls, expdesc *v)
static void open_func (LexState *ls, FuncState *fs, BlockCnt *bl)
static void close_func (LexState *ls)
static int block_follow (LexState *ls, int withuntil)
static void statlist (LexState *ls)
static void fieldsel (LexState *ls, expdesc *v)
static void yindex (LexState *ls, expdesc *v)
static void recfield (LexState *ls, ConsControl *cc)
static void closelistfield (FuncState *fs, ConsControl *cc)
static void lastlistfield (FuncState *fs, ConsControl *cc)
static void listfield (LexState *ls, ConsControl *cc)
static void field (LexState *ls, ConsControl *cc)
static void constructor (LexState *ls, expdesc *t)
static void setvararg (FuncState *fs, int nparams)
static void parlist (LexState *ls)
static void body (LexState *ls, expdesc *e, int ismethod, int line)
static int explist (LexState *ls, expdesc *v)
static void funcargs (LexState *ls, expdesc *f, int line)
static void primaryexp (LexState *ls, expdesc *v)
static void suffixedexp (LexState *ls, expdesc *v)
static void simpleexp (LexState *ls, expdesc *v)
static UnOpr getunopr (int op)
static BinOpr getbinopr (int op)
static BinOpr subexpr (LexState *ls, expdesc *v, int limit)
static void block (LexState *ls)
static void check_conflict (LexState *ls, struct LHS_assign *lh, expdesc *v)
static void restassign (LexState *ls, struct LHS_assign *lh, int nvars)
static int cond (LexState *ls)
static void gotostat (LexState *ls)
static void breakstat (LexState *ls)
static void checkrepeated (LexState *ls, TString *name)
static void labelstat (LexState *ls, TString *name, int line)
static void whilestat (LexState *ls, int line)
static void repeatstat (LexState *ls, int line)
static void exp1 (LexState *ls)
static void fixforjump (FuncState *fs, int pc, int dest, int back)
static void forbody (LexState *ls, int base, int line, int nvars, int isgen)
static void fornum (LexState *ls, TString *varname, int line)
static void forlist (LexState *ls, TString *indexname)
static void forstat (LexState *ls, int line)
static void test_then_block (LexState *ls, int *escapelist)
static void ifstat (LexState *ls, int line)
static void localfunc (LexState *ls)
static int getlocalattribute (LexState *ls)
static void checktoclose (LexState *ls, int level)
static void localstat (LexState *ls)
static int funcname (LexState *ls, expdesc *v)
static void funcstat (LexState *ls, int line)
static void exprstat (LexState *ls)
static void retstat (LexState *ls)
static void mainfunc (LexState *ls, FuncState *fs)
LClosure * luaY_parser (lua_State *L, ZIO *z, Mbuffer *buff, Dyndata *dyd, const char *name, int firstchar)
Variables
struct {
lu_byte left
lu_byte right
} priority []
Macro Definition Documentation
check_condition
#define check_condition (ls, c, msg) { if (!(c)) luaX_syntaxerror(ls, msg); }
Definition at line 122 of file lua-5.4.3/src/lparser.c.
Referenced by exprstat(), restassign(), and simpleexp().
enterlevel
#define enterlevel (ls) luaE_incCstack(ls->L)
Definition at line 492 of file lua-5.4.3/src/lparser.c.
Referenced by chunk(), restassign(), statement(), statement(), statement(), subexpr(), subexpr(), subexpr(), and subexpr().
eqstr
#define eqstr (a, b) ((a) == (b))
Definition at line 43 of file lua-5.4.3/src/lparser.c.
Referenced by findlabel(), newupvalue(), searchupvalue(), searchvar(), solvegoto(), solvegotos(), and undefgoto().
hasmultret
#define hasmultret (k) ((k) == VCALL || (k) == VVARARG)
Definition at line 38 of file lua-5.4.3/src/lparser.c.
Referenced by adjust_assign(), funcargs(), lastlistfield(), and retstat().
leavelevel
#define leavelevel (ls) ((ls)->L->nCcalls--)
Definition at line 495 of file lua-5.4.3/src/lparser.c.
Referenced by restassign(), statement(), and subexpr().
lparser_c
#define lparser_c
Definition at line 7 of file lua-5.4.3/src/lparser.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/lparser.c.
MAXVARS
#define MAXVARS 200
Definition at line 35 of file lua-5.4.3/src/lparser.c.
Referenced by new_localvar().
new_localvarliteral
#define new_localvarliteral (ls, v)
Value:
    new_localvar(ls,  \
      luaX_newstring(ls, "" v, (sizeof(v)/sizeof(char)) - 1));
Definition at line 208 of file lua-5.4.3/src/lparser.c.
#define new_localvarliteral(ls,v) \
    new_localvar(ls,  \
      luaX_newstring(ls, "" v, (sizeof(v)/sizeof(char)) - 1));
Referenced by body(), forlist(), and fornum().
UNARY_PRIORITY
#define UNARY_PRIORITY 12 /* priority for unary operators */
Definition at line 1241 of file lua-5.4.3/src/lparser.c.
Referenced by subexpr().
Typedef Documentation
BlockCnt
typedef struct BlockCnt BlockCnt
ConsControl
typedef struct ConsControl ConsControl
Function Documentation
addprototype()
static Proto * addprototype (LexState * ls) static
Definition at line 686 of file lua-5.4.3/src/lparser.c.
{
  Proto *clp;
  lua_State *L = ls->L;
  FuncState *fs = ls->fs;
  Proto *f = fs->f;  /* prototype of current function */
  if (fs->np >= f->sizep) {
    int oldsize = f->sizep;
    luaM_growvector(L, f->p, fs->np, f->sizep, Proto *, MAXARG_Bx, "functions");
    while (oldsize < f->sizep)
      f->p[oldsize++] = NULL;
  }
  f->p[fs->np++] = clp = luaF_newproto(L);
  luaC_objbarrier(L, f, clp);
  return clp;
}
References FuncState::f, LexState::fs, LexState::L, luaC_objbarrier, luaF_newproto(), luaM_growvector, MAXARG_Bx, FuncState::np, NULL, Proto::p, and Proto::sizep.
Referenced by body().
adjust_assign()
static void adjust_assign (LexState * ls, int nvars, int nexps, expdesc * e) static
Definition at line 470 of file lua-5.4.3/src/lparser.c.
{
  FuncState *fs = ls->fs;
  int needed = nvars - nexps;  /* extra values needed */
  if (hasmultret(e->k)) {  /* last expression has multiple returns? */
    int extra = needed + 1;  /* discount last expression itself */
    if (extra < 0)
      extra = 0;
    luaK_setreturns(fs, e, extra);  /* last exp. provides the difference */
  }
  else {
    if (e->k != VVOID)  /* at least one expression? */
      luaK_exp2nextreg(fs, e);  /* close last expression */
    if (needed > 0)  /* missing values? */
      luaK_nil(fs, fs->freereg, needed);  /* complete with nils */
  }
  if (needed > 0)
    luaK_reserveregs(fs, needed);  /* registers for extra values */
  else  /* adding 'needed' is actually a subtraction */
    fs->freereg += needed;  /* remove extra values */
}
References FuncState::freereg, LexState::fs, hasmultret, expdesc::k, luaK_exp2nextreg(), luaK_nil(), luaK_reserveregs(), luaK_setreturns(), and VVOID.
Referenced by forlist(), localstat(), and restassign().
adjustlocalvars()
static void adjustlocalvars (LexState * ls, int nvars) static
Definition at line 311 of file lua-5.4.3/src/lparser.c.
{
  FuncState *fs = ls->fs;
  int reglevel = luaY_nvarstack(fs);
  int i;
  for (i = 0; i < nvars; i++) {
    int vidx = fs->nactvar++;
    Vardesc *var = getlocalvardesc(fs, vidx);
    var->vd.ridx = reglevel++;
    var->vd.pidx = registerlocalvar(ls, fs, var->vd.name);
  }
}
References LexState::fs, getlocalvardesc(), luaY_nvarstack(), FuncState::nactvar, Vardesc::name, Vardesc::pidx, registerlocalvar(), reglevel(), Vardesc::ridx, and Vardesc::vd.
Referenced by body(), forbody(), forlist(), fornum(), localfunc(), localstat(), and parlist().
allocupvalue()
static Upvaldesc * allocupvalue (FuncState * fs) static
Definition at line 352 of file lua-5.4.3/src/lparser.c.
{
  Proto *f = fs->f;
  int oldsize = f->sizeupvalues;
  checklimit(fs, fs->nups + 1, MAXUPVAL, "upvalues");
  luaM_growvector(fs->ls->L, f->upvalues, fs->nups, f->sizeupvalues,
                  Upvaldesc, MAXUPVAL, "upvalues");
  while (oldsize < f->sizeupvalues)
    f->upvalues[oldsize++].name = NULL;
  return &f->upvalues[fs->nups++];
}
References checklimit(), FuncState::f, LexState::L, FuncState::ls, luaM_growvector, MAXUPVAL, NULL, FuncState::nups, Proto::sizeupvalues, and Proto::upvalues.
Referenced by mainfunc(), and newupvalue().
block()
static void block (LexState * ls) static
Definition at line 1293 of file lua-5.4.3/src/lparser.c.
{
  /* block -> statlist */
  FuncState *fs = ls->fs;
  BlockCnt bl;
  enterblock(fs, &bl, 0);
  statlist(ls);
  leaveblock(fs);
}
References enterblock(), LexState::fs, leaveblock(), and statlist().
Referenced by forbody(), ifstat(), statement(), and whilestat().
block_follow()
static int block_follow (LexState * ls, int withuntil) static
Definition at line 776 of file lua-5.4.3/src/lparser.c.
{
  switch (ls->t.token) {
    case TK_ELSE: case TK_ELSEIF:
    case TK_END: case TK_EOS:
      return 1;
    case TK_UNTIL: return withuntil;
    default: return 0;
  }
}
References LexState::t, TK_ELSE, TK_ELSEIF, TK_END, TK_EOS, TK_UNTIL, and Token::token.
Referenced by labelstat(), retstat(), statlist(), and test_then_block().
body()
static void body (LexState * ls, expdesc * e, int ismethod, int line) static
Definition at line 978 of file lua-5.4.3/src/lparser.c.
{
  /* body ->  '(' parlist ')' block END */
  FuncState new_fs;
  BlockCnt bl;
  new_fs.f = addprototype(ls);
  new_fs.f->linedefined = line;
  open_func(ls, &new_fs, &bl);
  checknext(ls, '(');
  if (ismethod) {
    new_localvarliteral(ls, "self");  /* create 'self' parameter */
    adjustlocalvars(ls, 1);
  }
  parlist(ls);
  checknext(ls, ')');
  statlist(ls);
  new_fs.f->lastlinedefined = ls->linenumber;
  check_match(ls, TK_END, TK_FUNCTION, line);
  codeclosure(ls, e);
  close_func(ls);
}
References addprototype(), adjustlocalvars(), check_match(), checknext(), close_func(), codeclosure(), FuncState::f, Proto::lastlinedefined, Proto::linedefined, LexState::linenumber, new_localvarliteral, open_func(), parlist(), statlist(), TK_END, and TK_FUNCTION.
Referenced by funcstat(), localfunc(), and simpleexp().
breakstat()
static void breakstat (LexState * ls) static
Definition at line 1426 of file lua-5.4.3/src/lparser.c.
{
  int line = ls->linenumber;
  luaX_next(ls);  /* skip break */
  newgotoentry(ls, luaS_newliteral(ls->L, "break"), line, luaK_jump(ls->fs));
}
References LexState::fs, LexState::L, LexState::linenumber, luaK_jump(), luaS_newliteral, luaX_next(), and newgotoentry().
Referenced by statement().
check()
static void check (LexState * ls, int c) static
Definition at line 107 of file lua-5.4.3/src/lparser.c.
{
  if (ls->t.token != c)
    error_expected(ls, c);
}
References error_expected(), LexState::t, and Token::token.
check_conflict()
static void check_conflict (LexState * ls, struct LHS_assign * lh, expdesc * v) static
Definition at line 1319 of file lua-5.4.3/src/lparser.c.
{
  FuncState *fs = ls->fs;
  int extra = fs->freereg;  /* eventual position to save local variable */
  int conflict = 0;
  for (; lh; lh = lh->prev) {  /* check all previous assignments */
    if (vkisindexed(lh->v.k)) {  /* assignment to table field? */
      if (lh->v.k == VINDEXUP) {  /* is table an upvalue? */
        if (v->k == VUPVAL && lh->v.u.ind.t == v->u.info) {
          conflict = 1;  /* table is the upvalue being assigned now */
          lh->v.k = VINDEXSTR;
          lh->v.u.ind.t = extra;  /* assignment will use safe copy */
        }
      }
      else {  /* table is a register */
        if (v->k == VLOCAL && lh->v.u.ind.t == v->u.var.ridx) {
          conflict = 1;  /* table is the local being assigned now */
          lh->v.u.ind.t = extra;  /* assignment will use safe copy */
        }
        /* is index the local being assigned? */
        if (lh->v.k == VINDEXED && v->k == VLOCAL &&
            lh->v.u.ind.idx == v->u.var.ridx) {
          conflict = 1;
          lh->v.u.ind.idx = extra;  /* previous assignment will use safe copy */
        }
      }
    }
  }
  if (conflict) {
    /* copy upvalue/local value to a temporary (in position 'extra') */
    if (v->k == VLOCAL)
      luaK_codeABC(fs, OP_MOVE, extra, v->u.var.ridx, 0);
    else
      luaK_codeABC(fs, OP_GETUPVAL, extra, v->u.info, 0);
    luaK_reserveregs(fs, 1);
  }
}
References FuncState::freereg, LexState::fs, expdesc::idx, expdesc::ind, expdesc::info, expdesc::k, luaK_codeABC, luaK_reserveregs(), OP_GETUPVAL, OP_MOVE, LHS_assign::prev, expdesc::ridx, expdesc::t, expdesc::u, LHS_assign::v, expdesc::var, VINDEXED, VINDEXSTR, VINDEXUP, vkisindexed, VLOCAL, and VUPVAL.
Referenced by restassign().
check_match()
static void check_match (LexState * ls, int what, int who, int where) static
Definition at line 130 of file lua-5.4.3/src/lparser.c.
{
  if (l_unlikely(!testnext(ls, what))) {
    if (where == ls->linenumber)  /* all in the same line? */
      error_expected(ls, what);  /* do not need a complex message */
    else {
      luaX_syntaxerror(ls, luaO_pushfstring(ls->L,
             "%s expected (to close %s at line %d)",
              luaX_token2str(ls, what), luaX_token2str(ls, who), where));
    }
  }
}
References error_expected(), LexState::L, LexState::linenumber, luaO_pushfstring(), luaX_syntaxerror(), luaX_token2str(), and testnext().
Referenced by body(), constructor(), forstat(), funcargs(), ifstat(), primaryexp(), repeatstat(), statement(), and whilestat().
check_readonly()
static void check_readonly (LexState * ls, expdesc * e) static
Definition at line 277 of file lua-5.4.3/src/lparser.c.
{
  FuncState *fs = ls->fs;
  TString *varname = NULL;  /* to be set if variable is const */
  switch (e->k) {
    case VCONST: {
      varname = ls->dyd->actvar.arr[e->u.info].vd.name;
      break;
    }
    case VLOCAL: {
      Vardesc *vardesc = getlocalvardesc(fs, e->u.var.vidx);
      if (vardesc->vd.kind != VDKREG)  /* not a regular variable? */
        varname = vardesc->vd.name;
      break;
    }
    case VUPVAL: {
      Upvaldesc *up = &fs->f->upvalues[e->u.info];
      if (up->kind != VDKREG)
        varname = up->name;
      break;
    }
    default:
      return;  /* other cases cannot be read-only */
  }
  if (varname) {
    const char *msg = luaO_pushfstring(ls->L,
       "attempt to assign to const variable '%s'", getstr(varname));
    luaK_semerror(ls, msg);  /* error */
  }
}
References Dyndata::actvar, Dyndata::arr, LexState::dyd, FuncState::f, LexState::fs, getlocalvardesc(), getstr, expdesc::info, expdesc::k, Upvaldesc::kind, Vardesc::kind, LexState::L, luaK_semerror(), luaO_pushfstring(), Upvaldesc::name, Vardesc::name, NULL, expdesc::u, Proto::upvalues, expdesc::var, VCONST, Vardesc::vd, VDKREG, expdesc::vidx, VLOCAL, and VUPVAL.
Referenced by restassign().
checklimit()
static void checklimit (FuncState * fs, int v, int l, const char * what) static
Definition at line 87 of file lua-5.4.3/src/lparser.c.
{
  if (v > l) errorlimit(fs, l, what);
}
References errorlimit().
Referenced by allocupvalue(), new_localvar(), and recfield().
checknext()
static void checknext (LexState * ls, int c) static
Definition at line 116 of file lua-5.4.3/src/lparser.c.
{
  check(ls, c);
  luaX_next(ls);
}
References check, and luaX_next().
Referenced by body(), constructor(), forbody(), forlist(), fornum(), getlocalattribute(), labelstat(), recfield(), restassign(), test_then_block(), whilestat(), and yindex().
checkrepeated()
static void checkrepeated (LexState * ls, TString * name) static
Definition at line 1436 of file lua-5.4.3/src/lparser.c.
{
  Labeldesc *lb = findlabel(ls, name);
  if (l_unlikely(lb != NULL)) {  /* already defined? */
    const char *msg = "label '%s' already defined on line %d";
    msg = luaO_pushfstring(ls->L, msg, getstr(name), lb->line);
    luaK_semerror(ls, msg);  /* error */
  }
}
References findlabel(), getstr, LexState::L, Labeldesc::line, luaK_semerror(), luaO_pushfstring(), name, and NULL.
Referenced by labelstat().
checktoclose()
static void checktoclose (LexState * ls, int level) static
Definition at line 1706 of file lua-5.4.3/src/lparser.c.
{
  if (level != -1) {  /* is there a to-be-closed variable? */
    FuncState *fs = ls->fs;
    markupval(fs, level + 1);
    fs->bl->insidetbc = 1;  /* in the scope of a to-be-closed variable */
    luaK_codeABC(fs, OP_TBC, reglevel(fs, level), 0, 0);
  }
}
References FuncState::bl, LexState::fs, BlockCnt::insidetbc, luaK_codeABC, markupval(), OP_TBC, and reglevel().
Referenced by localstat().
close_func()
static void close_func (LexState * ls) static
Definition at line 744 of file lua-5.4.3/src/lparser.c.
{
  lua_State *L = ls->L;
  FuncState *fs = ls->fs;
  Proto *f = fs->f;
  luaK_ret(fs, luaY_nvarstack(fs), 0);  /* final return */
  leaveblock(fs);
  lua_assert(fs->bl == NULL);
  luaK_finish(fs);
  luaM_shrinkvector(L, f->code, f->sizecode, fs->pc, Instruction);
  luaM_shrinkvector(L, f->lineinfo, f->sizelineinfo, fs->pc, ls_byte);
  luaM_shrinkvector(L, f->abslineinfo, f->sizeabslineinfo,
                       fs->nabslineinfo, AbsLineInfo);
  luaM_shrinkvector(L, f->k, f->sizek, fs->nk, TValue);
  luaM_shrinkvector(L, f->p, f->sizep, fs->np, Proto *);
  luaM_shrinkvector(L, f->locvars, f->sizelocvars, fs->ndebugvars, LocVar);
  luaM_shrinkvector(L, f->upvalues, f->sizeupvalues, fs->nups, Upvaldesc);
  ls->fs = fs->prev;
  luaC_checkGC(L);
}
References Proto::abslineinfo, FuncState::bl, Proto::code, FuncState::f, LexState::fs, Proto::k, LexState::L, leaveblock(), Proto::lineinfo, Proto::locvars, lua_assert, luaC_checkGC, luaK_finish(), luaK_ret(), luaM_shrinkvector, luaY_nvarstack(), FuncState::nabslineinfo, FuncState::ndebugvars, FuncState::nk, FuncState::np, NULL, FuncState::nups, Proto::p, FuncState::pc, FuncState::prev, Proto::sizeabslineinfo, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, and Proto::upvalues.
Referenced by body(), and mainfunc().
closelistfield()
static void closelistfield (FuncState * fs, ConsControl * cc) static
Definition at line 856 of file lua-5.4.3/src/lparser.c.
{
  if (cc->v.k == VVOID) return;  /* there is no list item */
  luaK_exp2nextreg(fs, &cc->v);
  cc->v.k = VVOID;
  if (cc->tostore == LFIELDS_PER_FLUSH) {
    luaK_setlist(fs, cc->t->u.info, cc->na, cc->tostore);  /* flush */
    cc->na += cc->tostore;
    cc->tostore = 0;  /* no more items pending */
  }
}
References expdesc::info, expdesc::k, LFIELDS_PER_FLUSH, luaK_exp2nextreg(), luaK_setlist(), ConsControl::na, ConsControl::t, ConsControl::tostore, expdesc::u, ConsControl::v, and VVOID.
Referenced by constructor().
codeclosure()
static void codeclosure (LexState * ls, expdesc * v) static
Definition at line 710 of file lua-5.4.3/src/lparser.c.
{
  FuncState *fs = ls->fs->prev;
  init_exp(v, VRELOC, luaK_codeABx(fs, OP_CLOSURE, 0, fs->np - 1));
  luaK_exp2nextreg(fs, v);  /* fix it at the last register */
}
References LexState::fs, init_exp(), luaK_codeABx(), luaK_exp2nextreg(), FuncState::np, OP_CLOSURE, FuncState::prev, and VRELOC.
Referenced by body().
codename()
static void codename (LexState * ls, expdesc * e) static
Definition at line 166 of file lua-5.4.3/src/lparser.c.
{
  codestring(e, str_checkname(ls));
}
References codestring(), and str_checkname().
Referenced by fieldsel(), recfield(), and suffixedexp().
codestring()
static void codestring (expdesc * e, TString * s) static
Definition at line 159 of file lua-5.4.3/src/lparser.c.
{
  e->f = e->t = NO_JUMP;
  e->k = VKSTR;
  e->u.strval = s;
}
References expdesc::f, expdesc::k, NO_JUMP, s, expdesc::strval, expdesc::t, expdesc::u, and VKSTR.
Referenced by codename(), funcargs(), simpleexp(), and singlevar().
cond()
static int cond (LexState * ls) static
Definition at line 1394 of file lua-5.4.3/src/lparser.c.
{
  /* cond -> exp */
  expdesc v;
  expr(ls, &v);  /* read condition */
  if (v.k == VNIL) v.k = VFALSE;  /* 'falses' are all equal here */
  luaK_goiftrue(ls->fs, &v);
  return v.f;
}
References expr(), expdesc::f, LexState::fs, expdesc::k, luaK_goiftrue(), LHS_assign::v, VFALSE, and VNIL.
Referenced by repeatstat(), and whilestat().
constructor()
static void constructor (LexState * ls, expdesc * t) static
Definition at line 913 of file lua-5.4.3/src/lparser.c.
{
  /* constructor -> '{' [ field { sep field } [sep] ] '}'
     sep -> ',' | ';' */
  FuncState *fs = ls->fs;
  int line = ls->linenumber;
  int pc = luaK_codeABC(fs, OP_NEWTABLE, 0, 0, 0);
  ConsControl cc;
  luaK_code(fs, 0);  /* space for extra arg. */
  cc.na = cc.nh = cc.tostore = 0;
  cc.t = t;
  init_exp(t, VNONRELOC, fs->freereg);  /* table will be at stack top */
  luaK_reserveregs(fs, 1);
  init_exp(&cc.v, VVOID, 0);  /* no value (yet) */
  checknext(ls, '{');
  do {
    lua_assert(cc.v.k == VVOID || cc.tostore > 0);
    if (ls->t.token == '}') break;
    closelistfield(fs, &cc);
    field(ls, &cc);
  } while (testnext(ls, ',') || testnext(ls, ';'));
  check_match(ls, '}', '{', line);
  lastlistfield(fs, &cc);
  luaK_settablesize(fs, pc, t->u.info, cc.na, cc.nh);
}
References check_match(), checknext(), closelistfield(), field(), FuncState::freereg, LexState::fs, expdesc::info, init_exp(), expdesc::k, lastlistfield(), LexState::linenumber, lua_assert, luaK_code(), luaK_codeABC, luaK_reserveregs(), luaK_settablesize(), ConsControl::na, ConsControl::nh, OP_NEWTABLE, LexState::t, ConsControl::t, testnext(), Token::token, ConsControl::tostore, expdesc::u, ConsControl::v, VNONRELOC, and VVOID.
Referenced by funcargs(), and simpleexp().
createlabel()
static int createlabel (LexState * ls, TString * name, int line, int last) static
Definition at line 596 of file lua-5.4.3/src/lparser.c.
{
  FuncState *fs = ls->fs;
  Labellist *ll = &ls->dyd->label;
  int l = newlabelentry(ls, ll, name, line, luaK_getlabel(fs));
  if (last) {  /* label is last no-op statement in the block? */
    /* assume that locals are already out of scope */
    ll->arr[l].nactvar = fs->bl->nactvar;
  }
  if (solvegotos(ls, &ll->arr[l])) {  /* need close? */
    luaK_codeABC(fs, OP_CLOSE, luaY_nvarstack(fs), 0, 0);
    return 1;
  }
  return 0;
}
References Labellist::arr, FuncState::bl, LexState::dyd, LexState::fs, Dyndata::label, luaK_codeABC, luaK_getlabel(), luaY_nvarstack(), BlockCnt::nactvar, Labeldesc::nactvar, name, newlabelentry(), OP_CLOSE, and solvegotos().
Referenced by labelstat(), and leaveblock().
enterblock()
static void enterblock (FuncState * fs, BlockCnt * bl, lu_byte isloop) static
Definition at line 630 of file lua-5.4.3/src/lparser.c.
{
  bl->isloop = isloop;
  bl->nactvar = fs->nactvar;
  bl->firstlabel = fs->ls->dyd->label.n;
  bl->firstgoto = fs->ls->dyd->gt.n;
  bl->upval = 0;
  bl->insidetbc = (fs->bl != NULL && fs->bl->insidetbc);
  bl->previous = fs->bl;
  fs->bl = bl;
  lua_assert(fs->freereg == luaY_nvarstack(fs));
}
References FuncState::bl, LexState::dyd, BlockCnt::firstgoto, BlockCnt::firstlabel, FuncState::freereg, Dyndata::gt, BlockCnt::insidetbc, BlockCnt::isloop, Dyndata::label, FuncState::ls, lua_assert, luaY_nvarstack(), Labellist::n, BlockCnt::nactvar, FuncState::nactvar, NULL, BlockCnt::previous, and BlockCnt::upval.
Referenced by block(), forbody(), forstat(), open_func(), repeatstat(), test_then_block(), and whilestat().
error_expected()
static l_noret error_expected (LexState * ls, int token) static
Definition at line 68 of file lua-5.4.3/src/lparser.c.
{
  luaX_syntaxerror(ls,
      luaO_pushfstring(ls->L, "%s expected", luaX_token2str(ls, token)));
}
References LexState::L, luaO_pushfstring(), luaX_syntaxerror(), and luaX_token2str().
Referenced by check(), and check_match().
errorlimit()
static l_noret errorlimit (FuncState * fs, int limit, const char * what) static
Definition at line 74 of file lua-5.4.3/src/lparser.c.
{
  lua_State *L = fs->ls->L;
  const char *msg;
  int line = fs->f->linedefined;
  const char *where = (line == 0)
                      ? "main function"
                      : luaO_pushfstring(L, "function at line %d", line);
  msg = luaO_pushfstring(L, "too many %s (limit is %d) in %s",
                             what, limit, where);
  luaX_syntaxerror(fs->ls, msg);
}
References FuncState::f, LexState::L, Proto::linedefined, FuncState::ls, luaO_pushfstring(), and luaX_syntaxerror().
Referenced by checklimit().
exp1()
static void exp1 (LexState * ls) static
Definition at line 1505 of file lua-5.4.3/src/lparser.c.
{
  expdesc e;
  expr(ls, &e);
  luaK_exp2nextreg(ls->fs, &e);
  lua_assert(e.k == VNONRELOC);
}
References expr(), LexState::fs, expdesc::k, lua_assert, luaK_exp2nextreg(), and VNONRELOC.
Referenced by fornum().
explist()
static int explist (LexState * ls, expdesc * v) static
Definition at line 1000 of file lua-5.4.3/src/lparser.c.
{
  /* explist -> expr { ',' expr } */
  int n = 1;  /* at least one expression */
  expr(ls, v);
  while (testnext(ls, ',')) {
    luaK_exp2nextreg(ls->fs, v);
    expr(ls, v);
    n++;
  }
  return n;
}
References expr(), LexState::fs, luaK_exp2nextreg(), and testnext().
Referenced by forlist(), funcargs(), localstat(), restassign(), and retstat().
expr()
static void expr (LexState * ls, expdesc * v) static
Definition at line 1278 of file lua-5.4.3/src/lparser.c.
{
  subexpr(ls, v, 0);
}
References subexpr().
Referenced by cond(), exp1(), explist(), listfield(), primaryexp(), recfield(), test_then_block(), and yindex().
exprstat()
static void exprstat (LexState * ls) static
Definition at line 1784 of file lua-5.4.3/src/lparser.c.
{
  /* stat -> func | assignment */
  FuncState *fs = ls->fs;
  struct LHS_assign v;
  suffixedexp(ls, &v.v);
  if (ls->t.token == '=' || ls->t.token == ',') { /* stat -> assignment ? */
    v.prev = NULL;
    restassign(ls, &v, 1);
  }
  else {  /* stat -> func */
    Instruction *inst;
    check_condition(ls, v.v.k == VCALL, "syntax error");
    inst = &getinstruction(fs, &v.v);
    SETARG_C(*inst, 1);  /* call statement uses no results */
  }
}
References check_condition, LexState::fs, getinstruction, expdesc::k, NULL, restassign(), SETARG_C, suffixedexp(), LexState::t, Token::token, LHS_assign::v, and VCALL.
Referenced by statement().
field()
static void field (LexState * ls, ConsControl * cc) static
Definition at line 891 of file lua-5.4.3/src/lparser.c.
{
  /* field -> listfield | recfield */
  switch(ls->t.token) {
    case TK_NAME: {  /* may be 'listfield' or 'recfield' */
      if (luaX_lookahead(ls) != '=')  /* expression? */
        listfield(ls, cc);
      else
        recfield(ls, cc);
      break;
    }
    case '[': {
      recfield(ls, cc);
      break;
    }
    default: {
      listfield(ls, cc);
      break;
    }
  }
}
References listfield(), luaX_lookahead(), recfield(), LexState::t, TK_NAME, and Token::token.
Referenced by constructor().
fieldsel()
static void fieldsel (LexState * ls, expdesc * v) static
Definition at line 799 of file lua-5.4.3/src/lparser.c.
{
  /* fieldsel -> ['.' | ':'] NAME */
  FuncState *fs = ls->fs;
  expdesc key;
  luaK_exp2anyregup(fs, v);
  luaX_next(ls);  /* skip the dot or colon */
  codename(ls, &key);
  luaK_indexed(fs, v, &key);
}
References codename(), LexState::fs, luaK_exp2anyregup(), luaK_indexed(), and luaX_next().
Referenced by funcname(), and suffixedexp().
findlabel()
static Labeldesc * findlabel (LexState * ls, TString * name) static
Definition at line 532 of file lua-5.4.3/src/lparser.c.
{
  int i;
  Dyndata *dyd = ls->dyd;
  /* check labels in current function for a match */
  for (i = ls->fs->firstlabel; i < dyd->label.n; i++) {
    Labeldesc *lb = &dyd->label.arr[i];
    if (eqstr(lb->name, name))  /* correct label? */
      return lb;
  }
  return NULL;  /* label not found */
}
References Labellist::arr, LexState::dyd, eqstr, FuncState::firstlabel, LexState::fs, Dyndata::label, Labellist::n, name, Labeldesc::name, and NULL.
Referenced by checkrepeated(), and gotostat().
fixforjump()
static void fixforjump (FuncState * fs, int pc, int dest, int back) static
Definition at line 1518 of file lua-5.4.3/src/lparser.c.
{
  Instruction *jmp = &fs->f->code[pc];
  int offset = dest - (pc + 1);
  if (back)
    offset = -offset;
  if (l_unlikely(offset > MAXARG_Bx))
    luaX_syntaxerror(fs->ls, "control structure too long");
  SETARG_Bx(*jmp, offset);
}
References Proto::code, FuncState::f, FuncState::ls, luaX_syntaxerror(), MAXARG_Bx, and SETARG_Bx.
Referenced by forbody().
forbody()
static void forbody (LexState * ls, int base, int line, int nvars, int isgen) static
Definition at line 1532 of file lua-5.4.3/src/lparser.c.
{
  /* forbody -> DO block */
  static const OpCode forprep[2] = {OP_FORPREP, OP_TFORPREP};
  static const OpCode forloop[2] = {OP_FORLOOP, OP_TFORLOOP};
  BlockCnt bl;
  FuncState *fs = ls->fs;
  int prep, endfor;
  checknext(ls, TK_DO);
  prep = luaK_codeABx(fs, forprep[isgen], base, 0);
  enterblock(fs, &bl, 0);  /* scope for declared variables */
  adjustlocalvars(ls, nvars);
  luaK_reserveregs(fs, nvars);
  block(ls);
  leaveblock(fs);  /* end of scope for declared variables */
  fixforjump(fs, prep, luaK_getlabel(fs), 0);
  if (isgen) {  /* generic for? */
    luaK_codeABC(fs, OP_TFORCALL, base, 0, nvars);
    luaK_fixline(fs, line);
  }
  endfor = luaK_codeABx(fs, forloop[isgen], base, 0);
  fixforjump(fs, endfor, prep + 1, 1);
  luaK_fixline(fs, line);
}
References adjustlocalvars(), block(), checknext(), enterblock(), fixforjump(), forprep(), LexState::fs, leaveblock(), luaK_codeABC, luaK_codeABx(), luaK_fixline(), luaK_getlabel(), luaK_reserveregs(), OP_FORLOOP, OP_FORPREP, OP_TFORCALL, OP_TFORLOOP, OP_TFORPREP, and TK_DO.
Referenced by forlist(), and fornum().
forlist()
static void forlist (LexState * ls, TString * indexname) static
Definition at line 1580 of file lua-5.4.3/src/lparser.c.
{
  /* forlist -> NAME {,NAME} IN explist forbody */
  FuncState *fs = ls->fs;
  expdesc e;
  int nvars = 5;  /* gen, state, control, toclose, 'indexname' */
  int line;
  int base = fs->freereg;
  /* create control variables */
  new_localvarliteral(ls, "(for state)");
  new_localvarliteral(ls, "(for state)");
  new_localvarliteral(ls, "(for state)");
  new_localvarliteral(ls, "(for state)");
  /* create declared variables */
  new_localvar(ls, indexname);
  while (testnext(ls, ',')) {
    new_localvar(ls, str_checkname(ls));
    nvars++;
  }
  checknext(ls, TK_IN);
  line = ls->linenumber;
  adjust_assign(ls, 4, explist(ls, &e), &e);
  adjustlocalvars(ls, 4);  /* control variables */
  markupval(fs, fs->nactvar);  /* last control var. must be closed */
  luaK_checkstack(fs, 3);  /* extra space to call generator */
  forbody(ls, base, line, nvars - 4, 1);
}
References adjust_assign(), adjustlocalvars(), checknext(), explist(), forbody(), FuncState::freereg, LexState::fs, LexState::linenumber, luaK_checkstack(), markupval(), FuncState::nactvar, new_localvar(), new_localvarliteral, str_checkname(), testnext(), and TK_IN.
Referenced by forstat().
fornum()
static void fornum (LexState * ls, TString * varname, int line) static
Definition at line 1557 of file lua-5.4.3/src/lparser.c.
{
  /* fornum -> NAME = exp,exp[,exp] forbody */
  FuncState *fs = ls->fs;
  int base = fs->freereg;
  new_localvarliteral(ls, "(for state)");
  new_localvarliteral(ls, "(for state)");
  new_localvarliteral(ls, "(for state)");
  new_localvar(ls, varname);
  checknext(ls, '=');
  exp1(ls);  /* initial value */
  checknext(ls, ',');
  exp1(ls);  /* limit */
  if (testnext(ls, ','))
    exp1(ls);  /* optional step */
  else {  /* default step = 1 */
    luaK_int(fs, fs->freereg, 1);
    luaK_reserveregs(fs, 1);
  }
  adjustlocalvars(ls, 3);  /* control variables */
  forbody(ls, base, line, 1, 0);
}
References adjustlocalvars(), checknext(), exp1(), forbody(), FuncState::freereg, LexState::fs, luaK_int(), luaK_reserveregs(), new_localvar(), new_localvarliteral, and testnext().
Referenced by forstat().
forstat()
static void forstat (LexState * ls, int line) static
Definition at line 1608 of file lua-5.4.3/src/lparser.c.
{
  /* forstat -> FOR (fornum | forlist) END */
  FuncState *fs = ls->fs;
  TString *varname;
  BlockCnt bl;
  enterblock(fs, &bl, 1);  /* scope for loop and control variables */
  luaX_next(ls);  /* skip 'for' */
  varname = str_checkname(ls);  /* first variable name */
  switch (ls->t.token) {
    case '=': fornum(ls, varname, line); break;
    case ',': case TK_IN: forlist(ls, varname); break;
    default: luaX_syntaxerror(ls, "'=' or 'in' expected");
  }
  check_match(ls, TK_END, TK_FOR, line);
  leaveblock(fs);  /* loop scope ('break' jumps to this point) */
}
References check_match(), enterblock(), forlist(), fornum(), LexState::fs, leaveblock(), luaX_next(), luaX_syntaxerror(), str_checkname(), LexState::t, TK_END, TK_FOR, TK_IN, and Token::token.
Referenced by statement().
funcargs()
static void funcargs (LexState * ls, expdesc * f, int line) static
Definition at line 1013 of file lua-5.4.3/src/lparser.c.
{
  FuncState *fs = ls->fs;
  expdesc args;
  int base, nparams;
  switch (ls->t.token) {
    case '(': {  /* funcargs -> '(' [ explist ] ')' */
      luaX_next(ls);
      if (ls->t.token == ')')  /* arg list is empty? */
        args.k = VVOID;
      else {
        explist(ls, &args);
        if (hasmultret(args.k))
          luaK_setmultret(fs, &args);
      }
      check_match(ls, ')', '(', line);
      break;
    }
    case '{': {  /* funcargs -> constructor */
      constructor(ls, &args);
      break;
    }
    case TK_STRING: {  /* funcargs -> STRING */
      codestring(&args, ls->t.seminfo.ts);
      luaX_next(ls);  /* must use 'seminfo' before 'next' */
      break;
    }
    default: {
      luaX_syntaxerror(ls, "function arguments expected");
    }
  }
  lua_assert(f->k == VNONRELOC);
  base = f->u.info;  /* base register for call */
  if (hasmultret(args.k))
    nparams = LUA_MULTRET;  /* open call */
  else {
    if (args.k != VVOID)
      luaK_exp2nextreg(fs, &args);  /* close last argument */
    nparams = fs->freereg - (base+1);
  }
  init_exp(f, VCALL, luaK_codeABC(fs, OP_CALL, base, nparams+1, 2));
  luaK_fixline(fs, line);
  fs->freereg = base+1;  /* call remove function and arguments and leaves
                            (unless changed) one result */
}
References check_match(), codestring(), constructor(), explist(), FuncState::freereg, LexState::fs, hasmultret, expdesc::info, init_exp(), expdesc::k, lua_assert, LUA_MULTRET, luaK_codeABC, luaK_exp2nextreg(), luaK_fixline(), luaK_setmultret, luaX_next(), luaX_syntaxerror(), OP_CALL, Token::seminfo, LexState::t, TK_STRING, Token::token, SemInfo::ts, expdesc::u, VCALL, VNONRELOC, and VVOID.
Referenced by suffixedexp().
funcname()
static int funcname (LexState * ls, expdesc * v) static
Definition at line 1758 of file lua-5.4.3/src/lparser.c.
{
  /* funcname -> NAME {fieldsel} [':' NAME] */
  int ismethod = 0;
  singlevar(ls, v);
  while (ls->t.token == '.')
    fieldsel(ls, v);
  if (ls->t.token == ':') {
    ismethod = 1;
    fieldsel(ls, v);
  }
  return ismethod;
}
References fieldsel(), singlevar(), LexState::t, Token::token, and LHS_assign::v.
Referenced by funcstat().
funcstat()
static void funcstat (LexState * ls, int line) static
Definition at line 1772 of file lua-5.4.3/src/lparser.c.
{
  /* funcstat -> FUNCTION funcname body */
  int ismethod;
  expdesc v, b;
  luaX_next(ls);  /* skip FUNCTION */
  ismethod = funcname(ls, &v);
  body(ls, &b, ismethod, line);
  luaK_storevar(ls->fs, &v, &b);
  luaK_fixline(ls->fs, line);  /* definition "happens" in the first line */
}
References body(), LexState::fs, funcname(), luaK_fixline(), luaK_storevar(), luaX_next(), and LHS_assign::v.
Referenced by statement().
getbinopr()
static BinOpr getbinopr (int op) static
Definition at line 1194 of file lua-5.4.3/src/lparser.c.
{
  switch (op) {
    case '+': return OPR_ADD;
    case '-': return OPR_SUB;
    case '*': return OPR_MUL;
    case '%': return OPR_MOD;
    case '^': return OPR_POW;
    case '/': return OPR_DIV;
    case TK_IDIV: return OPR_IDIV;
    case '&': return OPR_BAND;
    case '|': return OPR_BOR;
    case '~': return OPR_BXOR;
    case TK_SHL: return OPR_SHL;
    case TK_SHR: return OPR_SHR;
    case TK_CONCAT: return OPR_CONCAT;
    case TK_NE: return OPR_NE;
    case TK_EQ: return OPR_EQ;
    case '<': return OPR_LT;
    case TK_LE: return OPR_LE;
    case '>': return OPR_GT;
    case TK_GE: return OPR_GE;
    case TK_AND: return OPR_AND;
    case TK_OR: return OPR_OR;
    default: return OPR_NOBINOPR;
  }
}
References OPR_ADD, OPR_AND, OPR_BAND, OPR_BOR, OPR_BXOR, OPR_CONCAT, OPR_DIV, OPR_EQ, OPR_GE, OPR_GT, OPR_IDIV, OPR_LE, OPR_LT, OPR_MOD, OPR_MUL, OPR_NE, OPR_NOBINOPR, OPR_OR, OPR_POW, OPR_SHL, OPR_SHR, OPR_SUB, TK_AND, TK_CONCAT, TK_EQ, TK_GE, TK_IDIV, TK_LE, TK_NE, TK_OR, TK_SHL, and TK_SHR.
Referenced by subexpr().
getlocalattribute()
static int getlocalattribute (LexState * ls) static
Definition at line 1689 of file lua-5.4.3/src/lparser.c.
{
  /* ATTRIB -> ['<' Name '>'] */
  if (testnext(ls, '<')) {
    const char *attr = getstr(str_checkname(ls));
    checknext(ls, '>');
    if (strcmp(attr, "const") == 0)
      return RDKCONST;  /* read-only variable */
    else if (strcmp(attr, "close") == 0)
      return RDKTOCLOSE;  /* to-be-closed variable */
    else
      luaK_semerror(ls,
        luaO_pushfstring(ls->L, "unknown attribute '%s'", attr));
  }
  return VDKREG;  /* regular variable */
}
References checknext(), getstr, LexState::L, luaK_semerror(), luaO_pushfstring(), RDKCONST, RDKTOCLOSE, str_checkname(), testnext(), and VDKREG.
Referenced by localstat().
getlocalvardesc()
static Vardesc * getlocalvardesc (FuncState * fs, int vidx) static
Definition at line 219 of file lua-5.4.3/src/lparser.c.
{
  return &fs->ls->dyd->actvar.arr[fs->firstlocal + vidx];
}
References Dyndata::actvar, Dyndata::arr, LexState::dyd, FuncState::firstlocal, and FuncState::ls.
Referenced by adjustlocalvars(), check_readonly(), init_var(), jumpscopeerror(), localdebuginfo(), localstat(), newupvalue(), reglevel(), and searchvar().
getunopr()
static UnOpr getunopr (int op) static
Definition at line 1183 of file lua-5.4.3/src/lparser.c.
{
  switch (op) {
    case TK_NOT: return OPR_NOT;
    case '-': return OPR_MINUS;
    case '~': return OPR_BNOT;
    case '#': return OPR_LEN;
    default: return OPR_NOUNOPR;
  }
}
References OPR_BNOT, OPR_LEN, OPR_MINUS, OPR_NOT, OPR_NOUNOPR, and TK_NOT.
Referenced by subexpr().
gotostat()
static void gotostat (LexState * ls) static
Definition at line 1404 of file lua-5.4.3/src/lparser.c.
{
  FuncState *fs = ls->fs;
  int line = ls->linenumber;
  TString *name = str_checkname(ls);  /* label's name */
  Labeldesc *lb = findlabel(ls, name);
  if (lb == NULL)  /* no label? */
    /* forward jump; will be resolved when the label is declared */
    newgotoentry(ls, name, line, luaK_jump(fs));
  else {  /* found a label */
    /* backward jump; will be resolved here */
    int lblevel = reglevel(fs, lb->nactvar);  /* label level */
    if (luaY_nvarstack(fs) > lblevel)  /* leaving the scope of a variable? */
      luaK_codeABC(fs, OP_CLOSE, lblevel, 0, 0);
    /* create jump and link it to the label */
    luaK_patchlist(fs, luaK_jump(fs), lb->pc);
  }
}
References findlabel(), LexState::fs, LexState::linenumber, luaK_codeABC, luaK_jump(), luaK_patchlist(), luaY_nvarstack(), Labeldesc::nactvar, name, newgotoentry(), NULL, OP_CLOSE, Labeldesc::pc, reglevel(), and str_checkname().
Referenced by statement().
ifstat()
static void ifstat (LexState * ls, int line) static
Definition at line 1663 of file lua-5.4.3/src/lparser.c.
{
  /* ifstat -> IF cond THEN block {ELSEIF cond THEN block} [ELSE block] END */
  FuncState *fs = ls->fs;
  int escapelist = NO_JUMP;  /* exit list for finished parts */
  test_then_block(ls, &escapelist);  /* IF cond THEN block */
  while (ls->t.token == TK_ELSEIF)
    test_then_block(ls, &escapelist);  /* ELSEIF cond THEN block */
  if (testnext(ls, TK_ELSE))
    block(ls);  /* 'else' part */
  check_match(ls, TK_END, TK_IF, line);
  luaK_patchtohere(fs, escapelist);  /* patch escape list to 'if' end */
}
References block(), check_match(), LexState::fs, luaK_patchtohere(), NO_JUMP, LexState::t, test_then_block(), testnext(), TK_ELSE, TK_ELSEIF, TK_END, TK_IF, and Token::token.
Referenced by statement().
init_exp()
static void init_exp (expdesc * e, expkind k, int i) static
Definition at line 152 of file lua-5.4.3/src/lparser.c.
{
  e->f = e->t = NO_JUMP;
  e->k = k;
  e->u.info = i;
}
References expdesc::f, expdesc::info, expdesc::k, NO_JUMP, expdesc::t, and expdesc::u.
Referenced by codeclosure(), constructor(), funcargs(), restassign(), searchvar(), simpleexp(), and singlevaraux().
init_var()
static void init_var (FuncState * fs, expdesc * e, int vidx) static
Definition at line 266 of file lua-5.4.3/src/lparser.c.
{
  e->f = e->t = NO_JUMP;
  e->k = VLOCAL;
  e->u.var.vidx = vidx;
  e->u.var.ridx = getlocalvardesc(fs, vidx)->vd.ridx;
}
References expdesc::f, getlocalvardesc(), expdesc::k, NO_JUMP, expdesc::ridx, Vardesc::ridx, expdesc::t, expdesc::u, expdesc::var, Vardesc::vd, expdesc::vidx, and VLOCAL.
Referenced by searchvar().
jumpscopeerror()
static l_noret jumpscopeerror (LexState * ls, Labeldesc * gt) static
Definition at line 502 of file lua-5.4.3/src/lparser.c.
{
  const char *varname = getstr(getlocalvardesc(ls->fs, gt->nactvar)->vd.name);
  const char *msg = "<goto %s> at line %d jumps into the scope of local '%s'";
  msg = luaO_pushfstring(ls->L, msg, getstr(gt->name), gt->line, varname);
  luaK_semerror(ls, msg);  /* raise the error */
}
References LexState::fs, getlocalvardesc(), getstr, gt, LexState::L, luaK_semerror(), luaO_pushfstring(), FuncState::nactvar, Vardesc::name, and Vardesc::vd.
Referenced by solvegoto().
labelstat()
static void labelstat (LexState * ls, TString * name, int line) static
Definition at line 1446 of file lua-5.4.3/src/lparser.c.
{
  /* label -> '::' NAME '::' */
  checknext(ls, TK_DBCOLON);  /* skip double colon */
  while (ls->t.token == ';' || ls->t.token == TK_DBCOLON)
    statement(ls);  /* skip other no-op statements */
  checkrepeated(ls, name);  /* check for repeated labels */
  createlabel(ls, name, line, block_follow(ls, 0));
}
References block_follow(), checknext(), checkrepeated(), createlabel(), name, statement(), LexState::t, TK_DBCOLON, and Token::token.
Referenced by statement().
lastlistfield()
static void lastlistfield (FuncState * fs, ConsControl * cc) static
Definition at line 868 of file lua-5.4.3/src/lparser.c.
{
  if (cc->tostore == 0) return;
  if (hasmultret(cc->v.k)) {
    luaK_setmultret(fs, &cc->v);
    luaK_setlist(fs, cc->t->u.info, cc->na, LUA_MULTRET);
    cc->na--;  /* do not count last expression (unknown number of elements) */
  }
  else {
    if (cc->v.k != VVOID)
      luaK_exp2nextreg(fs, &cc->v);
    luaK_setlist(fs, cc->t->u.info, cc->na, cc->tostore);
  }
  cc->na += cc->tostore;
}
References hasmultret, expdesc::info, expdesc::k, LUA_MULTRET, luaK_exp2nextreg(), luaK_setlist(), luaK_setmultret, ConsControl::na, ConsControl::t, ConsControl::tostore, expdesc::u, ConsControl::v, and VVOID.
Referenced by constructor().
leaveblock()
static void leaveblock (FuncState * fs) static
Definition at line 660 of file lua-5.4.3/src/lparser.c.
{
  BlockCnt *bl = fs->bl;
  LexState *ls = fs->ls;
  int hasclose = 0;
  int stklevel = reglevel(fs, bl->nactvar);  /* level outside the block */
  if (bl->isloop)  /* fix pending breaks? */
    hasclose = createlabel(ls, luaS_newliteral(ls->L, "break"), 0, 0);
  if (!hasclose && bl->previous && bl->upval)
    luaK_codeABC(fs, OP_CLOSE, stklevel, 0, 0);
  fs->bl = bl->previous;
  removevars(fs, bl->nactvar);
  lua_assert(bl->nactvar == fs->nactvar);
  fs->freereg = stklevel;  /* free registers */
  ls->dyd->label.n = bl->firstlabel;  /* remove local labels */
  if (bl->previous)  /* inner block? */
    movegotosout(fs, bl);  /* update pending gotos to outer block */
  else {
    if (bl->firstgoto < ls->dyd->gt.n)  /* pending gotos in outer block? */
      undefgoto(ls, &ls->dyd->gt.arr[bl->firstgoto]);  /* error */
  }
}
References Labellist::arr, FuncState::bl, createlabel(), LexState::dyd, BlockCnt::firstgoto, BlockCnt::firstlabel, FuncState::freereg, Dyndata::gt, BlockCnt::isloop, LexState::L, Dyndata::label, FuncState::ls, lua_assert, luaK_codeABC, luaS_newliteral, movegotosout(), Labellist::n, BlockCnt::nactvar, FuncState::nactvar, OP_CLOSE, BlockCnt::previous, reglevel(), removevars(), undefgoto(), and BlockCnt::upval.
Referenced by block(), close_func(), forbody(), forstat(), repeatstat(), test_then_block(), and whilestat().
listfield()
static void listfield (LexState * ls, ConsControl * cc) static
Definition at line 884 of file lua-5.4.3/src/lparser.c.
{
  /* listfield -> exp */
  expr(ls, &cc->v);
  cc->tostore++;
}
References expr(), ConsControl::tostore, and ConsControl::v.
Referenced by field().
localdebuginfo()
static LocVar * localdebuginfo (FuncState * fs, int vidx) static
Definition at line 251 of file lua-5.4.3/src/lparser.c.
{
  Vardesc *vd = getlocalvardesc(fs,  vidx);
  if (vd->vd.kind == RDKCTC)
    return NULL;  /* no debug info. for constants */
  else {
    int idx = vd->vd.pidx;
    lua_assert(idx < fs->ndebugvars);
    return &fs->f->locvars[idx];
  }
}
References FuncState::f, getlocalvardesc(), Vardesc::kind, Proto::locvars, lua_assert, NULL, Vardesc::pidx, RDKCTC, and Vardesc::vd.
Referenced by localfunc(), and removevars().
localfunc()
static void localfunc (LexState * ls) static
Definition at line 1677 of file lua-5.4.3/src/lparser.c.
{
  expdesc b;
  FuncState *fs = ls->fs;
  int fvar = fs->nactvar;  /* function's variable index */
  new_localvar(ls, str_checkname(ls));  /* new local variable */
  adjustlocalvars(ls, 1);  /* enter its scope */
  body(ls, &b, 0, ls->linenumber);  /* function created in next register */
  /* debug information will only see the variable after this point! */
  localdebuginfo(fs, fvar)->startpc = fs->pc;
}
References adjustlocalvars(), body(), LexState::fs, LexState::linenumber, localdebuginfo(), FuncState::nactvar, new_localvar(), FuncState::pc, LocVar::startpc, and str_checkname().
Referenced by statement().
localstat()
static void localstat (LexState * ls) static
Definition at line 1716 of file lua-5.4.3/src/lparser.c.
{
  /* stat -> LOCAL NAME ATTRIB { ',' NAME ATTRIB } ['=' explist] */
  FuncState *fs = ls->fs;
  int toclose = -1;  /* index of to-be-closed variable (if any) */
  Vardesc *var;  /* last variable */
  int vidx, kind;  /* index and kind of last variable */
  int nvars = 0;
  int nexps;
  expdesc e;
  do {
    vidx = new_localvar(ls, str_checkname(ls));
    kind = getlocalattribute(ls);
    getlocalvardesc(fs, vidx)->vd.kind = kind;
    if (kind == RDKTOCLOSE) {  /* to-be-closed? */
      if (toclose != -1)  /* one already present? */
        luaK_semerror(ls, "multiple to-be-closed variables in local list");
      toclose = fs->nactvar + nvars;
    }
    nvars++;
  } while (testnext(ls, ','));
  if (testnext(ls, '='))
    nexps = explist(ls, &e);
  else {
    e.k = VVOID;
    nexps = 0;
  }
  var = getlocalvardesc(fs, vidx);  /* get last variable */
  if (nvars == nexps &&  /* no adjustments? */
      var->vd.kind == RDKCONST &&  /* last variable is const? */
      luaK_exp2const(fs, &e, &var->k)) {  /* compile-time constant? */
    var->vd.kind = RDKCTC;  /* variable is a compile-time constant */
    adjustlocalvars(ls, nvars - 1);  /* exclude last variable */
    fs->nactvar++;  /* but count it */
  }
  else {
    adjust_assign(ls, nvars, nexps, &e);
    adjustlocalvars(ls, nvars);
  }
  checktoclose(ls, toclose);
}
References adjust_assign(), adjustlocalvars(), checktoclose(), explist(), LexState::fs, getlocalattribute(), getlocalvardesc(), expdesc::k, Vardesc::k, Vardesc::kind, luaK_exp2const(), luaK_semerror(), FuncState::nactvar, new_localvar(), RDKCONST, RDKCTC, RDKTOCLOSE, str_checkname(), testnext(), Vardesc::vd, and VVOID.
Referenced by statement().
luaY_nvarstack()
int luaY_nvarstack (FuncState * fs)
Definition at line 243 of file lua-5.4.3/src/lparser.c.
{
  return reglevel(fs, fs->nactvar);
}
References FuncState::nactvar, and reglevel().
Referenced by adjustlocalvars(), close_func(), createlabel(), enterblock(), freereg(), gotostat(), luaK_exp2anyreg(), retstat(), and statement().
luaY_parser()
LClosure * luaY_parser (lua_State * L, ZIO * z, Mbuffer * buff, Dyndata * dyd, const char * name, int firstchar)
Definition at line 1931 of file lua-5.4.3/src/lparser.c.
{
  LexState lexstate;
  FuncState funcstate;
  LClosure *cl = luaF_newLclosure(L, 1);  /* create main closure */
  setclLvalue2s(L, L->top, cl);  /* anchor it (to avoid being collected) */
  luaD_inctop(L);
  lexstate.h = luaH_new(L);  /* create table for scanner */
  sethvalue2s(L, L->top, lexstate.h);  /* anchor it */
  luaD_inctop(L);
  funcstate.f = cl->p = luaF_newproto(L);
  luaC_objbarrier(L, cl, cl->p);
  funcstate.f->source = luaS_new(L, name);  /* create and anchor TString */
  luaC_objbarrier(L, funcstate.f, funcstate.f->source);
  lexstate.buff = buff;
  lexstate.dyd = dyd;
  dyd->actvar.n = dyd->gt.n = dyd->label.n = 0;
  luaX_setinput(L, &lexstate, z, funcstate.f->source, firstchar);
  mainfunc(&lexstate, &funcstate);
  lua_assert(!funcstate.prev && funcstate.nups == 1 && !lexstate.fs);
  /* all scopes should be correctly finished */
  lua_assert(dyd->actvar.n == 0 && dyd->gt.n == 0 && dyd->label.n == 0);
  L->top--;  /* remove scanner's table */
  return cl;  /* closure is on the stack, too */
}
References Dyndata::actvar, LexState::buff, LexState::dyd, FuncState::f, LexState::fs, Dyndata::gt, LexState::h, Dyndata::label, lua_assert, luaC_objbarrier, luaD_inctop(), luaF_newLclosure(), luaF_newproto(), luaH_new(), luaS_new, luaX_setinput(), mainfunc(), Labellist::n, Dyndata::n, name, FuncState::nups, LClosure::p, FuncState::prev, setclLvalue2s, sethvalue2s, Proto::source, and lua_State::top.
mainfunc()
static void mainfunc (LexState * ls, FuncState * fs) static
Definition at line 1913 of file lua-5.4.3/src/lparser.c.
{
  BlockCnt bl;
  Upvaldesc *env;
  open_func(ls, fs, &bl);
  setvararg(fs, 0);  /* main function is always declared vararg */
  env = allocupvalue(fs);  /* ...set environment upvalue */
  env->instack = 1;
  env->idx = 0;
  env->kind = VDKREG;
  env->name = ls->envn;
  luaC_objbarrier(ls->L, fs->f, env->name);
  luaX_next(ls);  /* read first token */
  statlist(ls);  /* parse main body */
  check(ls, TK_EOS);
  close_func(ls);
}
References allocupvalue(), check, close_func(), LexState::envn, FuncState::f, Upvaldesc::idx, Upvaldesc::instack, Upvaldesc::kind, LexState::L, luaC_objbarrier, luaX_next(), Upvaldesc::name, open_func(), setvararg(), statlist(), TK_EOS, and VDKREG.
Referenced by luaY_parser().
markupval()
static void markupval (FuncState * fs, int level) static
Definition at line 410 of file lua-5.4.3/src/lparser.c.
{
  BlockCnt *bl = fs->bl;
  while (bl->nactvar > level)
    bl = bl->previous;
  bl->upval = 1;
  fs->needclose = 1;
}
References FuncState::bl, BlockCnt::nactvar, FuncState::needclose, BlockCnt::previous, and BlockCnt::upval.
Referenced by checktoclose(), forlist(), and singlevaraux().
movegotosout()
static void movegotosout (FuncState * fs, BlockCnt * bl) static
Definition at line 616 of file lua-5.4.3/src/lparser.c.
{
  int i;
  Labellist *gl = &fs->ls->dyd->gt;
  /* correct pending gotos to current block */
  for (i = bl->firstgoto; i < gl->n; i++) {  /* for each pending goto */
    Labeldesc *gt = &gl->arr[i];
    /* leaving a variable scope? */
    if (reglevel(fs, gt->nactvar) > reglevel(fs, bl->nactvar))
      gt->close |= bl->upval;  /* jump may need a close */
    gt->nactvar = bl->nactvar;  /* update goto level */
  }
}
References Labellist::arr, Labeldesc::close, LexState::dyd, BlockCnt::firstgoto, gt, Dyndata::gt, FuncState::ls, Labellist::n, BlockCnt::nactvar, FuncState::nactvar, reglevel(), and BlockCnt::upval.
Referenced by leaveblock().
new_localvar()
static int new_localvar (LexState * ls, TString * name) static
Definition at line 193 of file lua-5.4.3/src/lparser.c.
{
  lua_State *L = ls->L;
  FuncState *fs = ls->fs;
  Dyndata *dyd = ls->dyd;
  Vardesc *var;
  checklimit(fs, dyd->actvar.n + 1 - fs->firstlocal,
                 MAXVARS, "local variables");
  luaM_growvector(L, dyd->actvar.arr, dyd->actvar.n + 1,
                  dyd->actvar.size, Vardesc, USHRT_MAX, "local variables");
  var = &dyd->actvar.arr[dyd->actvar.n++];
  var->vd.kind = VDKREG;  /* default */
  var->vd.name = name;
  return dyd->actvar.n - 1 - fs->firstlocal;
}
References Dyndata::actvar, Dyndata::arr, checklimit(), LexState::dyd, FuncState::firstlocal, LexState::fs, Vardesc::kind, LexState::L, luaM_growvector, MAXVARS, Dyndata::n, name, Vardesc::name, Dyndata::size, Vardesc::vd, and VDKREG.
Referenced by forlist(), fornum(), localfunc(), localstat(), and parlist().
newgotoentry()
static int newgotoentry (LexState * ls, TString * name, int line, int pc) static
Definition at line 563 of file lua-5.4.3/src/lparser.c.
{
  return newlabelentry(ls, &ls->dyd->gt, name, line, pc);
}
References LexState::dyd, Dyndata::gt, name, and newlabelentry().
Referenced by breakstat(), gotostat(), and test_then_block().
newlabelentry()
static int newlabelentry (LexState * ls, Labellist * l, TString * name, int line, int pc) static
Definition at line 548 of file lua-5.4.3/src/lparser.c.
{
  int n = l->n;
  luaM_growvector(ls->L, l->arr, n, l->size,
                  Labeldesc, SHRT_MAX, "labels/gotos");
  l->arr[n].name = name;
  l->arr[n].line = line;
  l->arr[n].nactvar = ls->fs->nactvar;
  l->arr[n].close = 0;
  l->arr[n].pc = pc;
  l->n = n + 1;
  return n;
}
References Labellist::arr, Labeldesc::close, LexState::fs, LexState::L, Labeldesc::line, luaM_growvector, Labellist::n, FuncState::nactvar, Labeldesc::nactvar, name, Labeldesc::name, Labeldesc::pc, and Labellist::size.
Referenced by createlabel(), and newgotoentry().
newupvalue()
static int newupvalue (FuncState * fs, TString * name, expdesc * v) static
Definition at line 364 of file lua-5.4.3/src/lparser.c.
{
  Upvaldesc *up = allocupvalue(fs);
  FuncState *prev = fs->prev;
  if (v->k == VLOCAL) {
    up->instack = 1;
    up->idx = v->u.var.ridx;
    up->kind = getlocalvardesc(prev, v->u.var.vidx)->vd.kind;
    lua_assert(eqstr(name, getlocalvardesc(prev, v->u.var.vidx)->vd.name));
  }
  else {
    up->instack = 0;
    up->idx = cast_byte(v->u.info);
    up->kind = prev->f->upvalues[v->u.info].kind;
    lua_assert(eqstr(name, prev->f->upvalues[v->u.info].name));
  }
  up->name = name;
  luaC_objbarrier(fs->ls->L, fs->f, name);
  return fs->nups - 1;
}
References allocupvalue(), cast_byte, eqstr, FuncState::f, getlocalvardesc(), Upvaldesc::idx, expdesc::info, Upvaldesc::instack, expdesc::k, Upvaldesc::kind, Vardesc::kind, LexState::L, FuncState::ls, lua_assert, luaC_objbarrier, name, Upvaldesc::name, Vardesc::name, FuncState::nups, FuncState::prev, expdesc::ridx, expdesc::u, Proto::upvalues, expdesc::var, Vardesc::vd, expdesc::vidx, and VLOCAL.
Referenced by singlevaraux().
open_func()
static void open_func (LexState * ls, FuncState * fs, BlockCnt * bl) static
Definition at line 717 of file lua-5.4.3/src/lparser.c.
{
  Proto *f = fs->f;
  fs->prev = ls->fs;  /* linked list of funcstates */
  fs->ls = ls;
  ls->fs = fs;
  fs->pc = 0;
  fs->previousline = f->linedefined;
  fs->iwthabs = 0;
  fs->lasttarget = 0;
  fs->freereg = 0;
  fs->nk = 0;
  fs->nabslineinfo = 0;
  fs->np = 0;
  fs->nups = 0;
  fs->ndebugvars = 0;
  fs->nactvar = 0;
  fs->needclose = 0;
  fs->firstlocal = ls->dyd->actvar.n;
  fs->firstlabel = ls->dyd->label.n;
  fs->bl = NULL;
  f->source = ls->source;
  luaC_objbarrier(ls->L, f, f->source);
  f->maxstacksize = 2;  /* registers 0/1 are always valid */
  enterblock(fs, bl, 0);
}
References Dyndata::actvar, FuncState::bl, LexState::dyd, enterblock(), FuncState::f, FuncState::firstlabel, FuncState::firstlocal, FuncState::freereg, LexState::fs, FuncState::iwthabs, LexState::L, Dyndata::label, FuncState::lasttarget, Proto::linedefined, FuncState::ls, luaC_objbarrier, Proto::maxstacksize, Labellist::n, Dyndata::n, FuncState::nabslineinfo, FuncState::nactvar, FuncState::ndebugvars, FuncState::needclose, FuncState::nk, FuncState::np, NULL, FuncState::nups, FuncState::pc, FuncState::prev, FuncState::previousline, LexState::source, and Proto::source.
Referenced by body(), and mainfunc().
parlist()
static void parlist (LexState * ls) static
Definition at line 947 of file lua-5.4.3/src/lparser.c.
{
  /* parlist -> [ {NAME ','} (NAME | '...') ] */
  FuncState *fs = ls->fs;
  Proto *f = fs->f;
  int nparams = 0;
  int isvararg = 0;
  if (ls->t.token != ')') {  /* is 'parlist' not empty? */
    do {
      switch (ls->t.token) {
        case TK_NAME: {
          new_localvar(ls, str_checkname(ls));
          nparams++;
          break;
        }
        case TK_DOTS: {
          luaX_next(ls);
          isvararg = 1;
          break;
        }
        default: luaX_syntaxerror(ls, "<name> or '...' expected");
      }
    } while (!isvararg && testnext(ls, ','));
  }
  adjustlocalvars(ls, nparams);
  f->numparams = cast_byte(fs->nactvar);
  if (isvararg)
    setvararg(fs, f->numparams);  /* declared vararg */
  luaK_reserveregs(fs, fs->nactvar);  /* reserve registers for parameters */
}
References adjustlocalvars(), cast_byte, FuncState::f, LexState::fs, luaK_reserveregs(), luaX_next(), luaX_syntaxerror(), FuncState::nactvar, new_localvar(), Proto::numparams, setvararg(), str_checkname(), LexState::t, testnext(), TK_DOTS, TK_NAME, and Token::token.
Referenced by body().
primaryexp()
static void primaryexp (LexState * ls, expdesc * v) static
Definition at line 1068 of file lua-5.4.3/src/lparser.c.
{
  /* primaryexp -> NAME | '(' expr ')' */
  switch (ls->t.token) {
    case '(': {
      int line = ls->linenumber;
      luaX_next(ls);
      expr(ls, v);
      check_match(ls, ')', '(', line);
      luaK_dischargevars(ls->fs, v);
      return;
    }
    case TK_NAME: {
      singlevar(ls, v);
      return;
    }
    default: {
      luaX_syntaxerror(ls, "unexpected symbol");
    }
  }
}
References check_match(), expr(), LexState::fs, LexState::linenumber, luaK_dischargevars(), luaX_next(), luaX_syntaxerror(), singlevar(), LexState::t, TK_NAME, and Token::token.
Referenced by suffixedexp().
recfield()
static void recfield (LexState * ls, ConsControl * cc) static
Definition at line 835 of file lua-5.4.3/src/lparser.c.
{
  /* recfield -> (NAME | '['exp']') = exp */
  FuncState *fs = ls->fs;
  int reg = ls->fs->freereg;
  expdesc tab, key, val;
  if (ls->t.token == TK_NAME) {
    checklimit(fs, cc->nh, MAX_INT, "items in a constructor");
    codename(ls, &key);
  }
  else  /* ls->t.token == '[' */
    yindex(ls, &key);
  cc->nh++;
  checknext(ls, '=');
  tab = *cc->t;
  luaK_indexed(fs, &tab, &key);
  expr(ls, &val);
  luaK_storevar(fs, &tab, &val);
  fs->freereg = reg;  /* free registers */
}
References checklimit(), checknext(), codename(), expr(), FuncState::freereg, LexState::fs, luaK_indexed(), luaK_storevar(), MAX_INT, ConsControl::nh, LexState::t, ConsControl::t, TK_NAME, Token::token, and yindex().
Referenced by field().
registerlocalvar()
static int registerlocalvar (LexState * ls, FuncState * fs, TString * varname) static
Definition at line 175 of file lua-5.4.3/src/lparser.c.
{
  Proto *f = fs->f;
  int oldsize = f->sizelocvars;
  luaM_growvector(ls->L, f->locvars, fs->ndebugvars, f->sizelocvars,
                  LocVar, SHRT_MAX, "local variables");
  while (oldsize < f->sizelocvars)
    f->locvars[oldsize++].varname = NULL;
  f->locvars[fs->ndebugvars].varname = varname;
  f->locvars[fs->ndebugvars].startpc = fs->pc;
  luaC_objbarrier(ls->L, f, varname);
  return fs->ndebugvars++;
}
References FuncState::f, LexState::L, Proto::locvars, luaC_objbarrier, luaM_growvector, FuncState::ndebugvars, NULL, FuncState::pc, Proto::sizelocvars, LocVar::startpc, and LocVar::varname.
Referenced by adjustlocalvars().
reglevel()
static int reglevel (FuncState * fs, int nvar) static
Definition at line 229 of file lua-5.4.3/src/lparser.c.
{
  while (nvar-- > 0) {
    Vardesc *vd = getlocalvardesc(fs, nvar);  /* get previous variable */
    if (vd->vd.kind != RDKCTC)  /* is in a register? */
      return vd->vd.ridx + 1;
  }
  return 0;  /* no variables in registers */
}
References getlocalvardesc(), Vardesc::kind, RDKCTC, Vardesc::ridx, and Vardesc::vd.
Referenced by adjustlocalvars(), checktoclose(), gotostat(), leaveblock(), luaY_nvarstack(), movegotosout(), and repeatstat().
removevars()
static void removevars (FuncState * fs, int tolevel) static
Definition at line 328 of file lua-5.4.3/src/lparser.c.
{
  fs->ls->dyd->actvar.n -= (fs->nactvar - tolevel);
  while (fs->nactvar > tolevel) {
    LocVar *var = localdebuginfo(fs, --fs->nactvar);
    if (var)  /* does it have debug information? */
      var->endpc = fs->pc;
  }
}
References Dyndata::actvar, LexState::dyd, LocVar::endpc, localdebuginfo(), FuncState::ls, Dyndata::n, FuncState::nactvar, and FuncState::pc.
Referenced by leaveblock().
repeatstat()
static void repeatstat (LexState * ls, int line) static
Definition at line 1475 of file lua-5.4.3/src/lparser.c.
{
  /* repeatstat -> REPEAT block UNTIL cond */
  int condexit;
  FuncState *fs = ls->fs;
  int repeat_init = luaK_getlabel(fs);
  BlockCnt bl1, bl2;
  enterblock(fs, &bl1, 1);  /* loop block */
  enterblock(fs, &bl2, 0);  /* scope block */
  luaX_next(ls);  /* skip REPEAT */
  statlist(ls);
  check_match(ls, TK_UNTIL, TK_REPEAT, line);
  condexit = cond(ls);  /* read condition (inside scope block) */
  leaveblock(fs);  /* finish scope */
  if (bl2.upval) {  /* upvalues? */
    int exit = luaK_jump(fs);  /* normal exit must jump over fix */
    luaK_patchtohere(fs, condexit);  /* repetition must close upvalues */
    luaK_codeABC(fs, OP_CLOSE, reglevel(fs, bl2.nactvar), 0, 0);
    condexit = luaK_jump(fs);  /* repeat after closing upvalues */
    luaK_patchtohere(fs, exit);  /* normal exit comes to here */
  }
  luaK_patchlist(fs, condexit, repeat_init);  /* close the loop */
  leaveblock(fs);  /* finish loop */
}
References check_match(), cond(), enterblock(), LexState::fs, leaveblock(), luaK_codeABC, luaK_getlabel(), luaK_jump(), luaK_patchlist(), luaK_patchtohere(), luaX_next(), BlockCnt::nactvar, OP_CLOSE, reglevel(), statlist(), TK_REPEAT, TK_UNTIL, and BlockCnt::upval.
Referenced by statement().
restassign()
static void restassign (LexState * ls, struct LHS_assign * lh, int nvars) static
Definition at line 1363 of file lua-5.4.3/src/lparser.c.
{
  expdesc e;
  check_condition(ls, vkisvar(lh->v.k), "syntax error");
  check_readonly(ls, &lh->v);
  if (testnext(ls, ',')) {  /* restassign -> ',' suffixedexp restassign */
    struct LHS_assign nv;
    nv.prev = lh;
    suffixedexp(ls, &nv.v);
    if (!vkisindexed(nv.v.k))
      check_conflict(ls, lh, &nv.v);
    enterlevel(ls);  /* control recursion depth */
    restassign(ls, &nv, nvars+1);
    leavelevel(ls);
  }
  else {  /* restassign -> '=' explist */
    int nexps;
    checknext(ls, '=');
    nexps = explist(ls, &e);
    if (nexps != nvars)
      adjust_assign(ls, nvars, nexps, &e);
    else {
      luaK_setoneret(ls->fs, &e);  /* close last expression */
      luaK_storevar(ls->fs, &lh->v, &e);
      return;  /* avoid default */
    }
  }
  init_exp(&e, VNONRELOC, ls->fs->freereg-1);  /* default assignment */
  luaK_storevar(ls->fs, &lh->v, &e);
}
References adjust_assign(), check_condition, check_conflict(), check_readonly(), checknext(), enterlevel, explist(), FuncState::freereg, LexState::fs, init_exp(), expdesc::k, leavelevel, luaK_setoneret(), luaK_storevar(), LHS_assign::prev, restassign(), suffixedexp(), testnext(), LHS_assign::v, vkisindexed, vkisvar, and VNONRELOC.
Referenced by exprstat(), and restassign().
retstat()
static void retstat (LexState * ls) static
Definition at line 1802 of file lua-5.4.3/src/lparser.c.
{
  /* stat -> RETURN [explist] [';'] */
  FuncState *fs = ls->fs;
  expdesc e;
  int nret;  /* number of values being returned */
  int first = luaY_nvarstack(fs);  /* first slot to be returned */
  if (block_follow(ls, 1) || ls->t.token == ';')
    nret = 0;  /* return no values */
  else {
    nret = explist(ls, &e);  /* optional return values */
    if (hasmultret(e.k)) {
      luaK_setmultret(fs, &e);
      if (e.k == VCALL && nret == 1 && !fs->bl->insidetbc) {  /* tail call? */
        SET_OPCODE(getinstruction(fs,&e), OP_TAILCALL);
        lua_assert(GETARG_A(getinstruction(fs,&e)) == luaY_nvarstack(fs));
      }
      nret = LUA_MULTRET;  /* return all values */
    }
    else {
      if (nret == 1)  /* only one single value? */
        first = luaK_exp2anyreg(fs, &e);  /* can use original slot */
      else {  /* values must go to the top of the stack */
        luaK_exp2nextreg(fs, &e);
        lua_assert(nret == fs->freereg - first);
      }
    }
  }
  luaK_ret(fs, first, nret);
  testnext(ls, ';');  /* skip optional semicolon */
}
References FuncState::bl, block_follow(), explist(), FuncState::freereg, LexState::fs, GETARG_A, getinstruction, hasmultret, BlockCnt::insidetbc, expdesc::k, lua_assert, LUA_MULTRET, luaK_exp2anyreg(), luaK_exp2nextreg(), luaK_ret(), luaK_setmultret, luaY_nvarstack(), OP_TAILCALL, SET_OPCODE, LexState::t, testnext(), Token::token, and VCALL.
Referenced by statement().
searchupvalue()
static int searchupvalue (FuncState * fs, TString * name) static
Definition at line 342 of file lua-5.4.3/src/lparser.c.
{
  int i;
  Upvaldesc *up = fs->f->upvalues;
  for (i = 0; i < fs->nups; i++) {
    if (eqstr(up[i].name, name)) return i;
  }
  return -1;  /* not found */
}
References eqstr, FuncState::f, name, FuncState::nups, and Proto::upvalues.
Referenced by singlevaraux().
searchvar()
static int searchvar (FuncState * fs, TString * n, expdesc * var) static
Definition at line 390 of file lua-5.4.3/src/lparser.c.
{
  int i;
  for (i = cast_int(fs->nactvar) - 1; i >= 0; i--) {
    Vardesc *vd = getlocalvardesc(fs, i);
    if (eqstr(n, vd->vd.name)) {  /* found? */
      if (vd->vd.kind == RDKCTC)  /* compile-time constant? */
        init_exp(var, VCONST, fs->firstlocal + i);
      else  /* real variable */
        init_var(fs, var, i);
      return var->k;
    }
  }
  return -1;  /* not found */
}
References cast_int, eqstr, FuncState::firstlocal, getlocalvardesc(), init_exp(), init_var(), expdesc::k, Vardesc::kind, FuncState::nactvar, Vardesc::name, RDKCTC, VCONST, and Vardesc::vd.
Referenced by singlevaraux().
setvararg()
static void setvararg (FuncState * fs, int nparams) static
Definition at line 941 of file lua-5.4.3/src/lparser.c.
{
  fs->f->is_vararg = 1;
  luaK_codeABC(fs, OP_VARARGPREP, nparams, 0, 0);
}
References FuncState::f, Proto::is_vararg, luaK_codeABC, and OP_VARARGPREP.
Referenced by mainfunc(), and parlist().
simpleexp()
static void simpleexp (LexState * ls, expdesc * v) static
Definition at line 1128 of file lua-5.4.3/src/lparser.c.
{
  /* simpleexp -> FLT | INT | STRING | NIL | TRUE | FALSE | ... |
                  constructor | FUNCTION body | suffixedexp */
  switch (ls->t.token) {
    case TK_FLT: {
      init_exp(v, VKFLT, 0);
      v->u.nval = ls->t.seminfo.r;
      break;
    }
    case TK_INT: {
      init_exp(v, VKINT, 0);
      v->u.ival = ls->t.seminfo.i;
      break;
    }
    case TK_STRING: {
      codestring(v, ls->t.seminfo.ts);
      break;
    }
    case TK_NIL: {
      init_exp(v, VNIL, 0);
      break;
    }
    case TK_TRUE: {
      init_exp(v, VTRUE, 0);
      break;
    }
    case TK_FALSE: {
      init_exp(v, VFALSE, 0);
      break;
    }
    case TK_DOTS: {  /* vararg */
      FuncState *fs = ls->fs;
      check_condition(ls, fs->f->is_vararg,
                      "cannot use '...' outside a vararg function");
      init_exp(v, VVARARG, luaK_codeABC(fs, OP_VARARG, 0, 0, 1));
      break;
    }
    case '{': {  /* constructor */
      constructor(ls, v);
      return;
    }
    case TK_FUNCTION: {
      luaX_next(ls);
      body(ls, v, 0, ls->linenumber);
      return;
    }
    default: {
      suffixedexp(ls, v);
      return;
    }
  }
  luaX_next(ls);
}
References body(), check_condition, codestring(), constructor(), FuncState::f, LexState::fs, SemInfo::i, init_exp(), Proto::is_vararg, expdesc::ival, LexState::linenumber, luaK_codeABC, luaX_next(), expdesc::nval, OP_VARARG, SemInfo::r, Token::seminfo, suffixedexp(), LexState::t, TK_DOTS, TK_FALSE, TK_FLT, TK_FUNCTION, TK_INT, TK_NIL, TK_STRING, TK_TRUE, Token::token, SemInfo::ts, expdesc::u, VFALSE, VKFLT, VKINT, VNIL, VTRUE, and VVARARG.
Referenced by subexpr().
singlevar()
static void singlevar (LexState * ls, expdesc * var) static
Definition at line 452 of file lua-5.4.3/src/lparser.c.
{
  TString *varname = str_checkname(ls);
  FuncState *fs = ls->fs;
  singlevaraux(fs, varname, var, 1);
  if (var->k == VVOID) {  /* global name? */
    expdesc key;
    singlevaraux(fs, ls->envn, var, 1);  /* get environment variable */
    lua_assert(var->k != VVOID);  /* this one must exist */
    codestring(&key, varname);  /* key is variable name */
    luaK_indexed(fs, var, &key);  /* env[varname] */
  }
}
References codestring(), LexState::envn, LexState::fs, expdesc::k, lua_assert, luaK_indexed(), singlevaraux(), str_checkname(), and VVOID.
Referenced by funcname(), and primaryexp().
singlevaraux()
static void singlevaraux (FuncState * fs, TString * n, expdesc * var, int base) static
Definition at line 424 of file lua-5.4.3/src/lparser.c.
{
  if (fs == NULL)  /* no more levels? */
    init_exp(var, VVOID, 0);  /* default is global */
  else {
    int v = searchvar(fs, n, var);  /* look up locals at current level */
    if (v >= 0) {  /* found? */
      if (v == VLOCAL && !base)
        markupval(fs, var->u.var.vidx);  /* local will be used as an upval */
    }
    else {  /* not found as local at current level; try upvalues */
      int idx = searchupvalue(fs, n);  /* try existing upvalues */
      if (idx < 0) {  /* not found? */
        singlevaraux(fs->prev, n, var, 0);  /* try upper levels */
        if (var->k == VLOCAL || var->k == VUPVAL)  /* local or upvalue? */
          idx  = newupvalue(fs, n, var);  /* will be a new upvalue */
        else  /* it is a global or a constant */
          return;  /* don't need to do anything at this level */
      }
      init_exp(var, VUPVAL, idx);  /* new or old upvalue */
    }
  }
}
References init_exp(), expdesc::k, markupval(), newupvalue(), NULL, FuncState::prev, searchupvalue(), searchvar(), singlevaraux(), expdesc::u, expdesc::var, expdesc::vidx, VLOCAL, VUPVAL, and VVOID.
Referenced by singlevar(), and singlevaraux().
solvegoto()
static void solvegoto (LexState * ls, int g, Labeldesc * label) static
Definition at line 515 of file lua-5.4.3/src/lparser.c.
{
  int i;
  Labellist *gl = &ls->dyd->gt;  /* list of goto's */
  Labeldesc *gt = &gl->arr[g];  /* goto to be resolved */
  lua_assert(eqstr(gt->name, label->name));
  if (l_unlikely(gt->nactvar < label->nactvar))  /* enter some scope? */
    jumpscopeerror(ls, gt);
  luaK_patchlist(ls->fs, gt->pc, label->pc);
  for (i = g; i < gl->n - 1; i++)  /* remove goto from pending list */
    gl->arr[i] = gl->arr[i + 1];
  gl->n--;
}
References Labellist::arr, LexState::dyd, eqstr, LexState::fs, gt, Dyndata::gt, jumpscopeerror(), lua_assert, luaK_patchlist(), Labellist::n, Labeldesc::nactvar, Labeldesc::name, FuncState::pc, and Labeldesc::pc.
Referenced by solvegotos().
solvegotos()
static int solvegotos (LexState * ls, Labeldesc * lb) static
Definition at line 573 of file lua-5.4.3/src/lparser.c.
{
  Labellist *gl = &ls->dyd->gt;
  int i = ls->fs->bl->firstgoto;
  int needsclose = 0;
  while (i < gl->n) {
    if (eqstr(gl->arr[i].name, lb->name)) {
      needsclose |= gl->arr[i].close;
      solvegoto(ls, i, lb);  /* will remove 'i' from the list */
    }
    else
      i++;
  }
  return needsclose;
}
References Labellist::arr, FuncState::bl, Labeldesc::close, LexState::dyd, eqstr, BlockCnt::firstgoto, LexState::fs, Dyndata::gt, Labeldesc::name, and solvegoto().
Referenced by createlabel().
statement()
static void statement (LexState * ls) static
Definition at line 1834 of file lua-5.4.3/src/lparser.c.
{
  int line = ls->linenumber;  /* may be needed for error messages */
  enterlevel(ls);
  switch (ls->t.token) {
    case ';': {  /* stat -> ';' (empty statement) */
      luaX_next(ls);  /* skip ';' */
      break;
    }
    case TK_IF: {  /* stat -> ifstat */
      ifstat(ls, line);
      break;
    }
    case TK_WHILE: {  /* stat -> whilestat */
      whilestat(ls, line);
      break;
    }
    case TK_DO: {  /* stat -> DO block END */
      luaX_next(ls);  /* skip DO */
      block(ls);
      check_match(ls, TK_END, TK_DO, line);
      break;
    }
    case TK_FOR: {  /* stat -> forstat */
      forstat(ls, line);
      break;
    }
    case TK_REPEAT: {  /* stat -> repeatstat */
      repeatstat(ls, line);
      break;
    }
    case TK_FUNCTION: {  /* stat -> funcstat */
      funcstat(ls, line);
      break;
    }
    case TK_LOCAL: {  /* stat -> localstat */
      luaX_next(ls);  /* skip LOCAL */
      if (testnext(ls, TK_FUNCTION))  /* local function? */
        localfunc(ls);
      else
        localstat(ls);
      break;
    }
    case TK_DBCOLON: {  /* stat -> label */
      luaX_next(ls);  /* skip double colon */
      labelstat(ls, str_checkname(ls), line);
      break;
    }
    case TK_RETURN: {  /* stat -> retstat */
      luaX_next(ls);  /* skip RETURN */
      retstat(ls);
      break;
    }
    case TK_BREAK: {  /* stat -> breakstat */
      breakstat(ls);
      break;
    }
    case TK_GOTO: {  /* stat -> 'goto' NAME */
      luaX_next(ls);  /* skip 'goto' */
      gotostat(ls);
      break;
    }
    default: {  /* stat -> func | assignment */
      exprstat(ls);
      break;
    }
  }
  lua_assert(ls->fs->f->maxstacksize >= ls->fs->freereg &&
             ls->fs->freereg >= luaY_nvarstack(ls->fs));
  ls->fs->freereg = luaY_nvarstack(ls->fs);  /* free registers */
  leavelevel(ls);
}
References block(), breakstat(), check_match(), enterlevel, exprstat(), FuncState::f, forstat(), FuncState::freereg, LexState::fs, funcstat(), gotostat(), ifstat(), labelstat(), leavelevel, LexState::linenumber, localfunc(), localstat(), lua_assert, luaX_next(), luaY_nvarstack(), Proto::maxstacksize, repeatstat(), retstat(), str_checkname(), LexState::t, testnext(), TK_BREAK, TK_DBCOLON, TK_DO, TK_END, TK_FOR, TK_FUNCTION, TK_GOTO, TK_IF, TK_LOCAL, TK_REPEAT, TK_RETURN, TK_WHILE, Token::token, and whilestat().
Referenced by labelstat(), and statlist().
statlist()
static void statlist (LexState * ls) static
Definition at line 787 of file lua-5.4.3/src/lparser.c.
{
  /* statlist -> { stat [';'] } */
  while (!block_follow(ls, 1)) {
    if (ls->t.token == TK_RETURN) {
      statement(ls);
      return;  /* 'return' must be last statement */
    }
    statement(ls);
  }
}
References block_follow(), statement(), LexState::t, TK_RETURN, and Token::token.
Referenced by block(), body(), mainfunc(), repeatstat(), and test_then_block().
str_checkname()
static TString * str_checkname (LexState * ls) static
Definition at line 143 of file lua-5.4.3/src/lparser.c.
{
  TString *ts;
  check(ls, TK_NAME);
  ts = ls->t.seminfo.ts;
  luaX_next(ls);
  return ts;
}
References check, luaX_next(), Token::seminfo, LexState::t, TK_NAME, and SemInfo::ts.
Referenced by codename(), forlist(), forstat(), getlocalattribute(), gotostat(), localfunc(), localstat(), parlist(), singlevar(), and statement().
subexpr()
static BinOpr subexpr (LexState * ls, expdesc * v, int limit) static
Definition at line 1248 of file lua-5.4.3/src/lparser.c.
{
  BinOpr op;
  UnOpr uop;
  enterlevel(ls);
  uop = getunopr(ls->t.token);
  if (uop != OPR_NOUNOPR) {  /* prefix (unary) operator? */
    int line = ls->linenumber;
    luaX_next(ls);  /* skip operator */
    subexpr(ls, v, UNARY_PRIORITY);
    luaK_prefix(ls->fs, uop, v, line);
  }
  else simpleexp(ls, v);
  /* expand while operators have priorities higher than 'limit' */
  op = getbinopr(ls->t.token);
  while (op != OPR_NOBINOPR && priority[op].left > limit) {
    expdesc v2;
    BinOpr nextop;
    int line = ls->linenumber;
    luaX_next(ls);  /* skip operator */
    luaK_infix(ls->fs, op, v);
    /* read sub-expression with higher priority */
    nextop = subexpr(ls, &v2, priority[op].right);
    luaK_posfix(ls->fs, op, v, &v2, line);
    op = nextop;
  }
  leavelevel(ls);
  return op;  /* return first untreated operator */
}
References enterlevel, LexState::fs, getbinopr(), getunopr(), leavelevel, left, LexState::linenumber, luaK_infix(), luaK_posfix(), luaK_prefix(), luaX_next(), OPR_NOBINOPR, OPR_NOUNOPR, priority, right, simpleexp(), subexpr(), LexState::t, Token::token, and UNARY_PRIORITY.
Referenced by expr(), and subexpr().
suffixedexp()
static void suffixedexp (LexState * ls, expdesc * v) static
Definition at line 1090 of file lua-5.4.3/src/lparser.c.
{
  /* suffixedexp ->
       primaryexp { '.' NAME | '[' exp ']' | ':' NAME funcargs | funcargs } */
  FuncState *fs = ls->fs;
  int line = ls->linenumber;
  primaryexp(ls, v);
  for (;;) {
    switch (ls->t.token) {
      case '.': {  /* fieldsel */
        fieldsel(ls, v);
        break;
      }
      case '[': {  /* '[' exp ']' */
        expdesc key;
        luaK_exp2anyregup(fs, v);
        yindex(ls, &key);
        luaK_indexed(fs, v, &key);
        break;
      }
      case ':': {  /* ':' NAME funcargs */
        expdesc key;
        luaX_next(ls);
        codename(ls, &key);
        luaK_self(fs, v, &key);
        funcargs(ls, v, line);
        break;
      }
      case '(': case TK_STRING: case '{': {  /* funcargs */
        luaK_exp2nextreg(fs, v);
        funcargs(ls, v, line);
        break;
      }
      default: return;
    }
  }
}
References codename(), fieldsel(), LexState::fs, funcargs(), LexState::linenumber, luaK_exp2anyregup(), luaK_exp2nextreg(), luaK_indexed(), luaK_self(), luaX_next(), primaryexp(), LexState::t, TK_STRING, Token::token, and yindex().
Referenced by exprstat(), restassign(), and simpleexp().
test_then_block()
static void test_then_block (LexState * ls, int * escapelist) static
Definition at line 1626 of file lua-5.4.3/src/lparser.c.
{
  /* test_then_block -> [IF | ELSEIF] cond THEN block */
  BlockCnt bl;
  FuncState *fs = ls->fs;
  expdesc v;
  int jf;  /* instruction to skip 'then' code (if condition is false) */
  luaX_next(ls);  /* skip IF or ELSEIF */
  expr(ls, &v);  /* read condition */
  checknext(ls, TK_THEN);
  if (ls->t.token == TK_BREAK) {  /* 'if x then break' ? */
    int line = ls->linenumber;
    luaK_goiffalse(ls->fs, &v);  /* will jump if condition is true */
    luaX_next(ls);  /* skip 'break' */
    enterblock(fs, &bl, 0);  /* must enter block before 'goto' */
    newgotoentry(ls, luaS_newliteral(ls->L, "break"), line, v.t);
    while (testnext(ls, ';')) {}  /* skip semicolons */
    if (block_follow(ls, 0)) {  /* jump is the entire block? */
      leaveblock(fs);
      return;  /* and that is it */
    }
    else  /* must skip over 'then' part if condition is false */
      jf = luaK_jump(fs);
  }
  else {  /* regular case (not a break) */
    luaK_goiftrue(ls->fs, &v);  /* skip over block if condition is false */
    enterblock(fs, &bl, 0);
    jf = v.f;
  }
  statlist(ls);  /* 'then' part */
  leaveblock(fs);
  if (ls->t.token == TK_ELSE ||
      ls->t.token == TK_ELSEIF)  /* followed by 'else'/'elseif'? */
    luaK_concat(fs, escapelist, luaK_jump(fs));  /* must jump over it */
  luaK_patchtohere(fs, jf);
}
References block_follow(), checknext(), enterblock(), expr(), expdesc::f, LexState::fs, LexState::L, leaveblock(), LexState::linenumber, luaK_concat(), luaK_goiffalse(), luaK_goiftrue(), luaK_jump(), luaK_patchtohere(), luaS_newliteral, luaX_next(), newgotoentry(), statlist(), LexState::t, expdesc::t, testnext(), TK_BREAK, TK_ELSE, TK_ELSEIF, TK_THEN, Token::token, and LHS_assign::v.
Referenced by ifstat().
testnext()
static int testnext (LexState * ls, int c) static
Definition at line 95 of file lua-5.4.3/src/lparser.c.
{
  if (ls->t.token == c) {
    luaX_next(ls);
    return 1;
  }
  else return 0;
}
References luaX_next(), LexState::t, and Token::token.
Referenced by check_match(), constructor(), explist(), forlist(), fornum(), getlocalattribute(), ifstat(), localstat(), parlist(), restassign(), retstat(), statement(), and test_then_block().
undefgoto()
static l_noret undefgoto (LexState * ls, Labeldesc * gt) static
Definition at line 646 of file lua-5.4.3/src/lparser.c.
{
  const char *msg;
  if (eqstr(gt->name, luaS_newliteral(ls->L, "break"))) {
    msg = "break outside loop at line %d";
    msg = luaO_pushfstring(ls->L, msg, gt->line);
  }
  else {
    msg = "no visible label '%s' for <goto> at line %d";
    msg = luaO_pushfstring(ls->L, msg, getstr(gt->name), gt->line);
  }
  luaK_semerror(ls, msg);
}
References eqstr, getstr, gt, LexState::L, luaK_semerror(), luaO_pushfstring(), and luaS_newliteral.
Referenced by leaveblock().
whilestat()
static void whilestat (LexState * ls, int line) static
Definition at line 1456 of file lua-5.4.3/src/lparser.c.
{
  /* whilestat -> WHILE cond DO block END */
  FuncState *fs = ls->fs;
  int whileinit;
  int condexit;
  BlockCnt bl;
  luaX_next(ls);  /* skip WHILE */
  whileinit = luaK_getlabel(fs);
  condexit = cond(ls);
  enterblock(fs, &bl, 1);
  checknext(ls, TK_DO);
  block(ls);
  luaK_jumpto(fs, whileinit);
  check_match(ls, TK_END, TK_WHILE, line);
  leaveblock(fs);
  luaK_patchtohere(fs, condexit);  /* false conditions finish the loop */
}
References block(), check_match(), checknext(), cond(), enterblock(), LexState::fs, leaveblock(), luaK_getlabel(), luaK_jumpto, luaK_patchtohere(), luaX_next(), TK_DO, TK_END, and TK_WHILE.
Referenced by statement().
yindex()
static void yindex (LexState * ls, expdesc * v) static
Definition at line 810 of file lua-5.4.3/src/lparser.c.
{
  /* index -> '[' expr ']' */
  luaX_next(ls);  /* skip the '[' */
  expr(ls, v);
  luaK_exp2val(ls->fs, v);
  checknext(ls, ']');
}
References checknext(), expr(), LexState::fs, luaK_exp2val(), and luaX_next().
Referenced by recfield(), and suffixedexp().
Variable Documentation
left
lu_byte left
Definition at line 1226 of file lua-5.4.3/src/lparser.c.
Referenced by subexpr().
[struct]
const struct { ... } priority[]
Initial value:
= {
   {10, 10}, {10, 10},
   {11, 11}, {11, 11},
   {14, 13},
   {11, 11}, {11, 11},
   {6, 6}, {4, 4}, {5, 5},
   {7, 7}, {7, 7},
   {9, 8},
   {3, 3}, {3, 3}, {3, 3},
   {3, 3}, {3, 3}, {3, 3},
   {2, 2}, {1, 1}
}
Referenced by subexpr().
right
lu_byte right
Definition at line 1227 of file lua-5.4.3/src/lparser.c.
Referenced by subexpr().