Github User Fetcher: lfunc.c File Reference
lfunc.c File Reference
#include "lprefix.h"
#include <stddef.h>
#include "lua.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
Macros
#define lfunc_c
#define LUA_CORE
Functions
CClosure * luaF_newCclosure (lua_State *L, int n)
LClosure * luaF_newLclosure (lua_State *L, int n)
void luaF_initupvals (lua_State *L, LClosure *cl)
UpVal * luaF_findupval (lua_State *L, StkId level)
void luaF_close (lua_State *L, StkId level)
Proto * luaF_newproto (lua_State *L)
void luaF_freeproto (lua_State *L, Proto *f)
const char * luaF_getlocalname (const Proto *f, int local_number, int pc)
Macro Definition Documentation
lfunc_c
#define lfunc_c
Definition at line 7 of file lua-5.3.6/src/lfunc.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/lfunc.c.
Function Documentation
luaF_close()
void luaF_close (lua_State * L, StkId level)
Definition at line 83 of file lua-5.3.6/src/lfunc.c.
{
  UpVal *uv;
  while (L->openupval != NULL && (uv = L->openupval)->v >= level) {
    lua_assert(upisopen(uv));
    L->openupval = uv->u.open.next;  /* remove from 'open' list */
    if (uv->refcount == 0)  /* no references? */
      luaM_free(L, uv);  /* free upvalue */
    else {
      setobj(L, &uv->u.value, uv->v);  /* move value to upvalue slot */
      uv->v = &uv->u.value;  /* now current value lives here */
      luaC_upvalbarrier(L, uv);
    }
  }
}
References lua_assert, luaC_upvalbarrier, luaM_free, UpVal::next, NULL, UpVal::open, lua_State::openupval, UpVal::refcount, setobj, UpVal::u, upisopen, UpVal::v, and UpVal::value.
luaF_findupval()
UpVal * luaF_findupval (lua_State * L, StkId level)
Definition at line 57 of file lua-5.3.6/src/lfunc.c.
{
  UpVal **pp = &L->openupval;
  UpVal *p;
  UpVal *uv;
  lua_assert(isintwups(L) || L->openupval == NULL);
  while (*pp != NULL && (p = *pp)->v >= level) {
    lua_assert(upisopen(p));
    if (p->v == level)  /* found a corresponding upvalue? */
      return p;  /* return it */
    pp = &p->u.open.next;
  }
  /* not found: create a new upvalue */
  uv = luaM_new(L, UpVal);
  uv->refcount = 0;
  uv->u.open.next = *pp;  /* link it to list of open upvalues */
  uv->u.open.touched = 1;
  *pp = uv;
  uv->v = level;  /* current value lives in the stack */
  if (!isintwups(L)) {  /* thread not in list of threads with upvalues? */
    L->twups = G(L)->twups;  /* link it to the list */
    G(L)->twups = L;
  }
  return uv;
}
References G, isintwups, lua_assert, luaM_new, UpVal::next, NULL, UpVal::open, lua_State::openupval, UpVal::refcount, UpVal::touched, lua_State::twups, UpVal::u, upisopen, and UpVal::v.
luaF_freeproto()
void luaF_freeproto (lua_State * L, Proto * f)
Definition at line 125 of file lua-5.3.6/src/lfunc.c.
{
  luaM_freearray(L, f->code, f->sizecode);
  luaM_freearray(L, f->p, f->sizep);
  luaM_freearray(L, f->k, f->sizek);
  luaM_freearray(L, f->lineinfo, f->sizelineinfo);
  luaM_freearray(L, f->locvars, f->sizelocvars);
  luaM_freearray(L, f->upvalues, f->sizeupvalues);
  luaM_free(L, f);
}
References Proto::code, Proto::k, Proto::lineinfo, Proto::locvars, luaM_free, luaM_freearray, Proto::p, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, and Proto::upvalues.
luaF_getlocalname()
const char * luaF_getlocalname (const Proto * f, int local_number, int pc)
Definition at line 140 of file lua-5.3.6/src/lfunc.c.
{
  int i;
  for (i = 0; i<f->sizelocvars && f->locvars[i].startpc <= pc; i++) {
    if (pc < f->locvars[i].endpc) {  /* is variable active? */
      local_number--;
      if (local_number == 0)
        return getstr(f->locvars[i].varname);
    }
  }
  return NULL;  /* not found */
}
References getstr, Proto::locvars, NULL, Proto::sizelocvars, LocVar::startpc, and LocVar::varname.
luaF_initupvals()
void luaF_initupvals (lua_State * L, LClosure * cl)
Definition at line 45 of file lua-5.3.6/src/lfunc.c.
{
  int i;
  for (i = 0; i < cl->nupvalues; i++) {
    UpVal *uv = luaM_new(L, UpVal);
    uv->refcount = 1;
    uv->v = &uv->u.value;  /* make it closed */
    setnilvalue(uv->v);
    cl->upvals[i] = uv;
  }
}
References luaM_new, UpVal::refcount, setnilvalue, UpVal::u, LClosure::upvals, UpVal::v, and UpVal::value.
Referenced by f_parser(), and f_parser().
luaF_newCclosure()
CClosure * luaF_newCclosure (lua_State * L, int n)
Definition at line 25 of file lua-5.3.6/src/lfunc.c.
{
  GCObject *o = luaC_newobj(L, LUA_TCCL, sizeCclosure(n));
  CClosure *c = gco2ccl(o);
  c->nupvalues = cast_byte(n);
  return c;
}
References cast_byte, gco2ccl, LUA_TCCL, luaC_newobj(), and sizeCclosure.
luaF_newLclosure()
LClosure * luaF_newLclosure (lua_State * L, int n)
Definition at line 33 of file lua-5.3.6/src/lfunc.c.
{
  GCObject *o = luaC_newobj(L, LUA_TLCL, sizeLclosure(n));
  LClosure *c = gco2lcl(o);
  c->p = NULL;
  c->nupvalues = cast_byte(n);
  while (n--) c->upvals[n] = NULL;
  return c;
}
References cast_byte, gco2lcl, LUA_TLCL, luaC_newobj(), NULL, LClosure::p, sizeLclosure, and LClosure::upvals.
luaF_newproto()
Proto * luaF_newproto (lua_State * L)
Definition at line 99 of file lua-5.3.6/src/lfunc.c.
{
  GCObject *o = luaC_newobj(L, LUA_TPROTO, sizeof(Proto));
  Proto *f = gco2p(o);
  f->k = NULL;
  f->sizek = 0;
  f->p = NULL;
  f->sizep = 0;
  f->code = NULL;
  f->cache = NULL;
  f->sizecode = 0;
  f->lineinfo = NULL;
  f->sizelineinfo = 0;
  f->upvalues = NULL;
  f->sizeupvalues = 0;
  f->numparams = 0;
  f->is_vararg = 0;
  f->maxstacksize = 0;
  f->locvars = NULL;
  f->sizelocvars = 0;
  f->linedefined = 0;
  f->lastlinedefined = 0;
  f->source = NULL;
  return f;
}
References Proto::cache, Proto::code, gco2p, Proto::is_vararg, Proto::k, Proto::lastlinedefined, Proto::linedefined, Proto::lineinfo, Proto::locvars, LUA_TPROTO, luaC_newobj(), Proto::maxstacksize, NULL, Proto::numparams, Proto::p, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, and Proto::upvalues.