Github User Fetcher: lua.c File Reference
lua.c File Reference
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lua_c
#define LUA_PROMPT "> "
#define LUA_PROMPT2 ">> "
#define LUA_PROGNAME "lua"
#define LUA_MAXINPUT 512
#define LUA_INIT "LUA_INIT"
#define LUA_INITVERSION LUA_INIT "_" LUA_VERSION_MAJOR "_" LUA_VERSION_MINOR
#define lua_stdin_is_tty() 1 /* assume stdin is a tty */
#define lua_readline(L, b, p)
#define lua_saveline(L, idx) { (void)L; (void)idx; }
#define lua_freeline(L, b) { (void)L; (void)b; }
#define EOFMARK "<eof>"
#define marklen (sizeof(EOFMARK)/sizeof(char) - 1)
#define noextrachars(x) {if ((x)[2] != '\0') return -1;}
#define has_i 0 /* -i */
#define has_v 1 /* -v */
#define has_e 2 /* -e */
#define has_E 3 /* -E */
#define num_has 4 /* number of 'has_*' */
Functions
static void lstop (lua_State *L, lua_Debug *ar)
static void laction (int i)
static void print_usage (const char *badoption)
static void l_message (const char *pname, const char *msg)
static int report (lua_State *L, int status)
static void finalreport (lua_State *L, int status)
static int traceback (lua_State *L)
static int docall (lua_State *L, int narg, int nres)
static void print_version (void)
static int getargs (lua_State *L, char **argv, int n)
static int dofile (lua_State *L, const char *name)
static int dostring (lua_State *L, const char *s, const char *name)
static int dolibrary (lua_State *L, const char *name)
static const char * get_prompt (lua_State *L, int firstline)
static int incomplete (lua_State *L, int status)
static int pushline (lua_State *L, int firstline)
static int loadline (lua_State *L)
static void dotty (lua_State *L)
static int handle_script (lua_State *L, char **argv, int n)
static int collectargs (char **argv, int *args)
static int runargs (lua_State *L, char **argv, int n)
static int handle_luainit (lua_State *L)
static int pmain (lua_State *L)
int main (int argc, char **argv)
Variables
static lua_State * globalL = NULL
static const char * progname = LUA_PROGNAME
Macro Definition Documentation
EOFMARK
#define EOFMARK "<eof>"
Definition at line 244 of file lua-5.2.4/src/lua.c.
Referenced by incomplete().
has_e
#define has_e 2 /* -e */
Definition at line 351 of file lua-5.2.4/src/lua.c.
Referenced by collectargs(), pmain(), and pmain().
has_E
#define has_E 3 /* -E */
Definition at line 352 of file lua-5.2.4/src/lua.c.
Referenced by collectargs(), and pmain().
has_i
#define has_i 0 /* -i */
Definition at line 349 of file lua-5.2.4/src/lua.c.
Referenced by collectargs(), pmain(), and pmain().
has_v
#define has_v 1 /* -v */
Definition at line 350 of file lua-5.2.4/src/lua.c.
Referenced by collectargs(), pmain(), and pmain().
lua_c
#define lua_c
Definition at line 13 of file lua-5.2.4/src/lua.c.
lua_freeline
#define lua_freeline (L, b) { (void)L; (void)b; }
Definition at line 81 of file lua-5.2.4/src/lua.c.
Referenced by pushline(), and pushline().
LUA_INIT
#define LUA_INIT "LUA_INIT"
Definition at line 35 of file lua-5.2.4/src/lua.c.
Referenced by handle_luainit().
LUA_INITVERSION
#define LUA_INITVERSION LUA_INIT "_" LUA_VERSION_MAJOR "_" LUA_VERSION_MINOR
Definition at line 38 of file lua-5.2.4/src/lua.c.
#define LUA_INITVERSION  \
    LUA_INIT "_" LUA_VERSION_MAJOR "_" LUA_VERSION_MINOR
Referenced by handle_luainit().
LUA_MAXINPUT
#define LUA_MAXINPUT 512
Definition at line 31 of file lua-5.2.4/src/lua.c.
Referenced by pushline(), and pushline().
LUA_PROGNAME
#define LUA_PROGNAME "lua"
Definition at line 27 of file lua-5.2.4/src/lua.c.
LUA_PROMPT
#define LUA_PROMPT "> "
Definition at line 22 of file lua-5.2.4/src/lua.c.
Referenced by get_prompt(), and get_prompt().
LUA_PROMPT2
#define LUA_PROMPT2 ">> "
Definition at line 23 of file lua-5.2.4/src/lua.c.
Referenced by get_prompt(), and get_prompt().
lua_readline
#define lua_readline (L, b, p)
Value:
        ((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
        fgets(b, LUA_MAXINPUT, stdin) != NULL)  /* get line */
Definition at line 77 of file lua-5.2.4/src/lua.c.
#define lua_readline(L,b,p) \
        ((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
        fgets(b, LUA_MAXINPUT, stdin) != NULL)  /* get line */
Referenced by pushline(), and pushline().
lua_saveline
#define lua_saveline (L, idx) { (void)L; (void)idx; }
Definition at line 80 of file lua-5.2.4/src/lua.c.
Referenced by loadline(), and loadline().
lua_stdin_is_tty
#define lua_stdin_is_tty () 1 /* assume stdin is a tty */
Definition at line 54 of file lua-5.2.4/src/lua.c.
Referenced by pmain(), and pmain().
marklen
#define marklen (sizeof(EOFMARK)/sizeof(char) - 1)
Definition at line 245 of file lua-5.2.4/src/lua.c.
Referenced by incomplete().
noextrachars
#define noextrachars (x) {if ((x)[2] != '\0') return -1;}
Definition at line 345 of file lua-5.2.4/src/lua.c.
Referenced by collectargs().
num_has
#define num_has 4 /* number of 'has_*' */
Definition at line 354 of file lua-5.2.4/src/lua.c.
Referenced by pmain().
Function Documentation
collectargs()
static int collectargs (char ** argv, int * args) static
Definition at line 357 of file lua-5.2.4/src/lua.c.
{
  int i;
  for (i = 1; argv[i] != NULL; i++) {
    if (argv[i][0] != '-')  /* not an option? */
        return i;
    switch (argv[i][1]) {  /* option */
      case '-':
        noextrachars(argv[i]);
        return (argv[i+1] != NULL ? i+1 : 0);
      case '\0':
        return i;
      case 'E':
        args[has_E] = 1;
        break;
      case 'i':
        noextrachars(argv[i]);
        args[has_i] = 1;  /* go through */
      case 'v':
        noextrachars(argv[i]);
        args[has_v] = 1;
        break;
      case 'e':
        args[has_e] = 1;  /* go through */
      case 'l':  /* both options need an argument */
        if (argv[i][2] == '\0') {  /* no concatenated argument? */
          i++;  /* try next 'argv' */
          if (argv[i] == NULL || argv[i][0] == '-')
            return -(i - 1);  /* no next argument or it is another option */
        }
        break;
      default:  /* invalid option; return its index... */
        return -i;  /* ...as a negative value */
    }
  }
  return 0;
}
References has_e, has_E, has_i, has_v, noextrachars, and NULL.
Referenced by pmain().
docall()
static int docall (lua_State * L, int narg, int nres) static
Definition at line 172 of file lua-5.2.4/src/lua.c.
{
  int status;
  int base = lua_gettop(L) - narg;  /* function index */
  lua_pushcfunction(L, traceback);  /* push traceback function */
  lua_insert(L, base);  /* put it under chunk and args */
  globalL = L;  /* to be available to 'laction' */
  signal(SIGINT, laction);
  status = lua_pcall(L, narg, nres, base);
  signal(SIGINT, SIG_DFL);
  lua_remove(L, base);  /* remove traceback function */
  return status;
}
References globalL, laction(), lua_gettop(), lua_insert, lua_pcall, lua_pushcfunction, lua_remove, and traceback().
Referenced by dofile(), dolibrary(), dostring(), dotty(), and handle_script().
dofile()
static int dofile (lua_State * L, const char * name) static
Definition at line 210 of file lua-5.2.4/src/lua.c.
{
  int status = luaL_loadfile(L, name);
  if (status == LUA_OK) status = docall(L, 0, 0);
  return report(L, status);
}
References docall(), LUA_OK, luaL_loadfile, name, and report().
Referenced by handle_luainit(), and pmain().
dolibrary()
static int dolibrary (lua_State * L, const char * name) static
Definition at line 224 of file lua-5.2.4/src/lua.c.
{
  int status;
  lua_getglobal(L, "require");
  lua_pushstring(L, name);
  status = docall(L, 1, 1);  /* call 'require(name)' */
  if (status == LUA_OK)
    lua_setglobal(L, name);  /* global[name] = require return */
  return report(L, status);
}
References docall(), lua_getglobal, LUA_OK, lua_pushstring(), lua_setglobal, name, and report().
Referenced by runargs().
dostring()
static int dostring (lua_State * L, const char * s, const char * name) static
Definition at line 217 of file lua-5.2.4/src/lua.c.
{
  int status = luaL_loadbuffer(L, s, strlen(s), name);
  if (status == LUA_OK) status = docall(L, 0, 0);
  return report(L, status);
}
References docall(), LUA_OK, luaL_loadbuffer, name, report(), and s.
Referenced by handle_luainit(), and runargs().
dotty()
static void dotty (lua_State * L) static
Definition at line 303 of file lua-5.2.4/src/lua.c.
{
  int status;
  const char *oldprogname = progname;
  progname = NULL;
  while ((status = loadline(L)) != -1) {
    if (status == LUA_OK) status = docall(L, 0, LUA_MULTRET);
    report(L, status);
    if (status == LUA_OK && lua_gettop(L) > 0) {  /* any result to print? */
      luaL_checkstack(L, LUA_MINSTACK, "too many results to print");
      lua_getglobal(L, "print");
      lua_insert(L, 1);
      if (lua_pcall(L, lua_gettop(L)-1, 0, 0) != LUA_OK)
        l_message(progname, lua_pushfstring(L,
                               "error calling " LUA_QL("print") " (%s)",
                               lua_tostring(L, -1)));
    }
  }
  lua_settop(L, 0);  /* clear stack */
  luai_writeline();
  progname = oldprogname;
}
References docall(), l_message(), loadline(), lua_getglobal, lua_gettop(), lua_insert, LUA_MINSTACK, LUA_MULTRET, LUA_OK, lua_pcall, lua_pushfstring(), LUA_QL, lua_settop(), lua_tostring, luaL_checkstack(), NULL, progname, and report().
Referenced by pmain().
finalreport()
static void finalreport (lua_State * L, int status) static
Definition at line 149 of file lua-5.2.4/src/lua.c.
{
  if (status != LUA_OK) {
    const char *msg = (lua_type(L, -1) == LUA_TSTRING) ? lua_tostring(L, -1)
                                                       : NULL;
    if (msg == NULL) msg = "(error object is not a string)";
    l_message(progname, msg);
    lua_pop(L, 1);
  }
}
References l_message(), LUA_OK, lua_pop, lua_tostring, LUA_TSTRING, lua_type(), NULL, and progname.
Referenced by main().
get_prompt()
static const char * get_prompt (lua_State * L, int firstline) static
Definition at line 235 of file lua-5.2.4/src/lua.c.
{
  const char *p;
  lua_getglobal(L, firstline ? "_PROMPT" : "_PROMPT2");
  p = lua_tostring(L, -1);
  if (p == NULL) p = (firstline ? LUA_PROMPT : LUA_PROMPT2);
  return p;
}
References lua_getglobal, LUA_PROMPT, LUA_PROMPT2, lua_tostring, and NULL.
Referenced by pushline().
getargs()
static int getargs (lua_State * L, char ** argv, int n) static
Definition at line 192 of file lua-5.2.4/src/lua.c.
{
  int narg;
  int i;
  int argc = 0;
  while (argv[argc]) argc++;  /* count total number of arguments */
  narg = argc - (n + 1);  /* number of arguments to the script */
  luaL_checkstack(L, narg + 3, "too many arguments to script");
  for (i=n+1; i < argc; i++)
    lua_pushstring(L, argv[i]);
  lua_createtable(L, narg, n + 1);
  for (i=0; i < argc; i++) {
    lua_pushstring(L, argv[i]);
    lua_rawseti(L, -2, i - n);
  }
  return narg;
}
References lua_createtable(), lua_pushstring(), lua_rawseti(), and luaL_checkstack().
Referenced by handle_script().
handle_luainit()
static int handle_luainit (lua_State * L) static
Definition at line 423 of file lua-5.2.4/src/lua.c.
{
  const char *name = "=" LUA_INITVERSION;
  const char *init = getenv(name + 1);
  if (init == NULL) {
    name = "=" LUA_INIT;
    init = getenv(name + 1);  /* try alternative name */
  }
  if (init == NULL) return LUA_OK;
  else if (init[0] == '@')
    return dofile(L, init+1);
  else
    return dostring(L, init, name);
}
References dofile(), dostring(), LUA_INIT, LUA_INITVERSION, LUA_OK, name, and NULL.
Referenced by pmain().
handle_script()
static int handle_script (lua_State * L, char ** argv, int n) static
Definition at line 326 of file lua-5.2.4/src/lua.c.
{
  int status;
  const char *fname;
  int narg = getargs(L, argv, n);  /* collect arguments */
  lua_setglobal(L, "arg");
  fname = argv[n];
  if (strcmp(fname, "-") == 0 && strcmp(argv[n-1], "--") != 0)
    fname = NULL;  /* stdin */
  status = luaL_loadfile(L, fname);
  lua_insert(L, -(narg+1));
  if (status == LUA_OK)
    status = docall(L, narg, LUA_MULTRET);
  else
    lua_pop(L, narg);
  return report(L, status);
}
References docall(), getargs(), lua_insert, LUA_MULTRET, LUA_OK, lua_pop, lua_setglobal, luaL_loadfile, NULL, and report().
Referenced by pmain().
incomplete()
static int incomplete (lua_State * L, int status) static
Definition at line 247 of file lua-5.2.4/src/lua.c.
{
  if (status == LUA_ERRSYNTAX) {
    size_t lmsg;
    const char *msg = lua_tolstring(L, -1, &lmsg);
    if (lmsg >= marklen && strcmp(msg + lmsg - marklen, EOFMARK) == 0) {
      lua_pop(L, 1);
      return 1;
    }
  }
  return 0;  /* else... */
}
References EOFMARK, LUA_ERRSYNTAX, lua_pop, lua_tolstring(), and marklen.
Referenced by loadline().
l_message()
static void l_message (const char * pname, const char * msg) static
Definition at line 129 of file lua-5.2.4/src/lua.c.
{
  if (pname) luai_writestringerror("%s: ", pname);
  luai_writestringerror("%s\n", msg);
}
References luai_writestringerror.
Referenced by dotty(), finalreport(), main(), and report().
laction()
static void laction (int i) static
Definition at line 101 of file lua-5.2.4/src/lua.c.
{
  signal(i, SIG_DFL); /* if another SIGINT happens before lstop,
                              terminate process (default action) */
  lua_sethook(globalL, lstop, LUA_MASKCALL | LUA_MASKRET | LUA_MASKCOUNT, 1);
}
References globalL, lstop(), LUA_MASKCALL, LUA_MASKCOUNT, LUA_MASKRET, and lua_sethook().
Referenced by docall().
loadline()
static int loadline (lua_State * L) static
Definition at line 281 of file lua-5.2.4/src/lua.c.
{
  int status;
  lua_settop(L, 0);
  if (!pushline(L, 1))
    return -1;  /* no input */
  for (;;) {  /* repeat until gets a complete line */
    size_t l;
    const char *line = lua_tolstring(L, 1, &l);
    status = luaL_loadbuffer(L, line, l, "=stdin");
    if (!incomplete(L, status)) break;  /* cannot try to add lines? */
    if (!pushline(L, 0))  /* no more input? */
      return -1;
    lua_pushliteral(L, "\n");  /* add a new line... */
    lua_insert(L, -2);  /* ...between the two lines */
    lua_concat(L, 3);  /* join them */
  }
  lua_saveline(L, 1);
  lua_remove(L, 1);  /* remove line */
  return status;
}
References incomplete(), lua_concat(), lua_insert, lua_pushliteral, lua_remove, lua_saveline, lua_settop(), lua_tolstring(), luaL_loadbuffer, and pushline().
Referenced by dotty().
lstop()
static void lstop (lua_State * L, lua_Debug * ar) static
Definition at line 94 of file lua-5.2.4/src/lua.c.
{
  (void)ar;  /* unused arg. */
  lua_sethook(L, NULL, 0, 0);
  luaL_error(L, "interrupted!");
}
References lua_sethook(), luaL_error(), and NULL.
Referenced by laction().
main()
int main (int argc, char ** argv)
Definition at line 480 of file lua-5.2.4/src/lua.c.
{
  int status, result;
  lua_State *L = luaL_newstate();  /* create state */
  if (L == NULL) {
    l_message(argv[0], "cannot create state: not enough memory");
    return EXIT_FAILURE;
  }
  /* call 'pmain' in protected mode */
  lua_pushcfunction(L, &pmain);
  lua_pushinteger(L, argc);  /* 1st argument */
  lua_pushlightuserdata(L, argv); /* 2nd argument */
  status = lua_pcall(L, 2, 1, 0);
  result = lua_toboolean(L, -1);  /* get result */
  finalreport(L, status);
  lua_close(L);
  return (result && status == LUA_OK) ? EXIT_SUCCESS : EXIT_FAILURE;
}
References finalreport(), l_message(), lua_close(), LUA_OK, lua_pcall, lua_pushcfunction, lua_pushinteger(), lua_pushlightuserdata(), lua_toboolean(), luaL_newstate(), NULL, and pmain().
pmain()
static int pmain (lua_State * L) static
Definition at line 438 of file lua-5.2.4/src/lua.c.
{
  int argc = (int)lua_tointeger(L, 1);
  char **argv = (char **)lua_touserdata(L, 2);
  int script;
  int args[num_has];
  args[has_i] = args[has_v] = args[has_e] = args[has_E] = 0;
  if (argv[0] && argv[0][0]) progname = argv[0];
  script = collectargs(argv, args);
  if (script < 0) {  /* invalid arg? */
    print_usage(argv[-script]);
    return 0;
  }
  if (args[has_v]) print_version();
  if (args[has_E]) {  /* option '-E'? */
    lua_pushboolean(L, 1);  /* signal for libraries to ignore env. vars. */
    lua_setfield(L, LUA_REGISTRYINDEX, "LUA_NOENV");
  }
  /* open standard libraries */
  luaL_checkversion(L);
  lua_gc(L, LUA_GCSTOP, 0);  /* stop collector during initialization */
  luaL_openlibs(L);  /* open libraries */
  lua_gc(L, LUA_GCRESTART, 0);
  if (!args[has_E] && handle_luainit(L) != LUA_OK)
    return 0;  /* error running LUA_INIT */
  /* execute arguments -e and -l */
  if (!runargs(L, argv, (script > 0) ? script : argc)) return 0;
  /* execute main script (if there is one) */
  if (script && handle_script(L, argv, script) != LUA_OK) return 0;
  if (args[has_i])  /* -i option? */
    dotty(L);
  else if (script == 0 && !args[has_e] && !args[has_v]) {  /* no arguments? */
    if (lua_stdin_is_tty()) {
      print_version();
      dotty(L);
    }
    else dofile(L, NULL);  /* executes stdin as a file */
  }
  lua_pushboolean(L, 1);  /* signal no errors */
  return 1;
}
References collectargs(), dofile(), dotty(), handle_luainit(), handle_script(), has_e, has_E, has_i, has_v, lua_gc(), LUA_GCRESTART, LUA_GCSTOP, LUA_OK, lua_pushboolean(), LUA_REGISTRYINDEX, lua_setfield(), lua_stdin_is_tty, lua_tointeger, lua_touserdata(), luaL_checkversion, luaL_openlibs(), NULL, num_has, print_usage(), print_version(), progname, and runargs().
Referenced by main().
print_usage()
static void print_usage (const char * badoption) static
Definition at line 108 of file lua-5.2.4/src/lua.c.
{
  luai_writestringerror("%s: ", progname);
  if (badoption[1] == 'e' || badoption[1] == 'l')
    luai_writestringerror("'%s' needs argument\n", badoption);
  else
    luai_writestringerror("unrecognized option '%s'\n", badoption);
  luai_writestringerror(
  "usage: %s [options] [script [args]]\n"
  "Available options are:\n"
  "  -e stat  execute string " LUA_QL("stat") "\n"
  "  -i       enter interactive mode after executing " LUA_QL("script") "\n"
  "  -l name  require library " LUA_QL("name") "\n"
  "  -v       show version information\n"
  "  -E       ignore environment variables\n"
  "  --       stop handling options\n"
  "  -        stop handling options and execute stdin\n"
  ,
  progname);
}
References LUA_QL, luai_writestringerror, and progname.
print_version()
static void print_version (void) static
Definition at line 186 of file lua-5.2.4/src/lua.c.
{
  luai_writestring(LUA_COPYRIGHT, strlen(LUA_COPYRIGHT));
  luai_writeline();
}
References LUA_COPYRIGHT.
Referenced by pmain().
pushline()
static int pushline (lua_State * L, int firstline) static
Definition at line 260 of file lua-5.2.4/src/lua.c.
{
  char buffer[LUA_MAXINPUT];
  char *b = buffer;
  size_t l;
  const char *prmt = get_prompt(L, firstline);
  int readstatus = lua_readline(L, b, prmt);
  lua_pop(L, 1);  /* remove result from 'get_prompt' */
  if (readstatus == 0)
    return 0;  /* no input */
  l = strlen(b);
  if (l > 0 && b[l-1] == '\n')  /* line ends with newline? */
    b[l-1] = '\0';  /* remove it */
  if (firstline && b[0] == '=')  /* first line starts with `=' ? */
    lua_pushfstring(L, "return %s", b+1);  /* change it to `return' */
  else
    lua_pushstring(L, b);
  lua_freeline(L, b);
  return 1;
}
References get_prompt(), lua_freeline, LUA_MAXINPUT, lua_pop, lua_pushfstring(), lua_pushstring(), and lua_readline.
Referenced by loadline().
report()
static int report (lua_State * L, int status) static
Definition at line 135 of file lua-5.2.4/src/lua.c.
{
  if (status != LUA_OK && !lua_isnil(L, -1)) {
    const char *msg = lua_tostring(L, -1);
    if (msg == NULL) msg = "(error object is not a string)";
    l_message(progname, msg);
    lua_pop(L, 1);
    /* force a complete garbage collection in case of errors */
    lua_gc(L, LUA_GCCOLLECT, 0);
  }
  return status;
}
References l_message(), lua_gc(), LUA_GCCOLLECT, lua_isnil, LUA_OK, lua_pop, lua_tostring, NULL, and progname.
Referenced by dofile(), dolibrary(), dostring(), dotty(), and handle_script().
runargs()
static int runargs (lua_State * L, char ** argv, int n) static
Definition at line 395 of file lua-5.2.4/src/lua.c.
{
  int i;
  for (i = 1; i < n; i++) {
    lua_assert(argv[i][0] == '-');
    switch (argv[i][1]) {  /* option */
      case 'e': {
        const char *chunk = argv[i] + 2;
        if (*chunk == '\0') chunk = argv[++i];
        lua_assert(chunk != NULL);
        if (dostring(L, chunk, "=(command line)") != LUA_OK)
          return 0;
        break;
      }
      case 'l': {
        const char *filename = argv[i] + 2;
        if (*filename == '\0') filename = argv[++i];
        lua_assert(filename != NULL);
        if (dolibrary(L, filename) != LUA_OK)
          return 0;  /* stop if file fails */
        break;
      }
      default: break;
    }
  }
  return 1;
}
References chunk(), dolibrary(), dostring(), lua_assert, LUA_OK, and NULL.
Referenced by pmain().
traceback()
static int traceback (lua_State * L) static
Definition at line 160 of file lua-5.2.4/src/lua.c.
{
  const char *msg = lua_tostring(L, 1);
  if (msg)
    luaL_traceback(L, L, msg, 1);
  else if (!lua_isnoneornil(L, 1)) {  /* is there an error object? */
    if (!luaL_callmeta(L, 1, "__tostring"))  /* try its 'tostring' metamethod */
      lua_pushliteral(L, "(no error message)");
  }
  return 1;
}
References lua_isnoneornil, lua_pushliteral, lua_tostring, luaL_callmeta(), and luaL_traceback().
Referenced by docall().
Variable Documentation
globalL
lua_State* globalL = NULL static
Definition at line 88 of file lua-5.2.4/src/lua.c.
Referenced by docall(), and laction().
progname
const char* progname = LUA_PROGNAME static
Definition at line 90 of file lua-5.2.4/src/lua.c.
Referenced by dotty(), finalreport(), pmain(), print_usage(), and report().