Github User Fetcher: luac.c File Reference
luac.c File Reference
#include "lprefix.h"
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "ldebug.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lopnames.h"
#include "lstate.h"
#include "lundump.h"
Macros
#define luac_c
#define LUA_CORE
#define luaU_print PrintFunction
#define PROGNAME "luac" /* default program name */
#define OUTPUT PROGNAME ".out" /* default output file */
#define IS(s) (strcmp(argv[i],s)==0)
#define FUNCTION "(function()end)();"
#define toproto(L, i) getproto(s2v(L->top+(i)))
#define UPVALNAME(x) ((f->upvalues[x].name) ? getstr(f->upvalues[x].name) : "-")
#define VOID(p) ((const void*)(p))
#define eventname(i) (getstr(tmname[i]))
#define COMMENT "\t; "
#define EXTRAARG GETARG_Ax(code[pc+1])
#define EXTRAARGC (EXTRAARG*(MAXARG_C+1))
#define ISK (isk ? "k" : "")
#define SS(x) ((x==1)?"":"s")
#define S(x) (int)(x),SS(x)
Functions
static void PrintFunction (const Proto *f, int full)
static void fatal (const char *message)
static void cannot (const char *what)
static void usage (const char *message)
static int doargs (int argc, char *argv[])
static const char * reader (lua_State *L, void *ud, size_t *size)
static const Proto * combine (lua_State *L, int n)
static int writer (lua_State *L, const void *p, size_t size, void *u)
static int pmain (lua_State *L)
int main (int argc, char *argv[])
static void PrintString (const TString *ts)
static void PrintType (const Proto *f, int i)
static void PrintConstant (const Proto *f, int i)
static void PrintCode (const Proto *f)
static void PrintHeader (const Proto *f)
static void PrintDebug (const Proto *f)
Variables
static int listing =0
static int dumping =1
static int stripping =0
static char Output [] ={ OUTPUT }
static const char * output =Output
static const char * progname =PROGNAME
static TString ** tmname
Macro Definition Documentation
COMMENT
#define COMMENT "\t; "
Definition at line 330 of file lua-5.4.3/src/luac.c.
Referenced by PrintCode().
eventname
#define eventname (i) (getstr(tmname[i]))
Definition at line 219 of file lua-5.4.3/src/luac.c.
Referenced by PrintCode().
EXTRAARG
#define EXTRAARG GETARG_Ax(code[pc+1])
Definition at line 331 of file lua-5.4.3/src/luac.c.
Referenced by PrintCode().
EXTRAARGC
#define EXTRAARGC (EXTRAARG*(MAXARG_C+1))
Definition at line 332 of file lua-5.4.3/src/luac.c.
Referenced by PrintCode().
FUNCTION
#define FUNCTION "(function()end)();"
Definition at line 124 of file lua-5.4.3/src/luac.c.
Referenced by reader().
IS
#define IS (s) (strcmp(argv[i],s)==0)
Definition at line 74 of file lua-5.4.3/src/luac.c.
Referenced by doargs(), and pmain().
ISK
#define ISK (isk ? "k" : "")
Definition at line 333 of file lua-5.4.3/src/luac.c.
Referenced by PrintCode().
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/luac.c.
luac_c
#define luac_c
Definition at line 7 of file lua-5.4.3/src/luac.c.
luaU_print
#define luaU_print PrintFunction
Definition at line 29 of file lua-5.4.3/src/luac.c.
Referenced by pmain().
OUTPUT
#define OUTPUT PROGNAME ".out" /* default output file */
Definition at line 32 of file lua-5.4.3/src/luac.c.
PROGNAME
#define PROGNAME "luac" /* default program name */
Definition at line 31 of file lua-5.4.3/src/luac.c.
Referenced by combine().
S
#define S (x) (int)(x),SS(x)
Definition at line 667 of file lua-5.4.3/src/luac.c.
Referenced by PrintHeader().
SS
#define SS (x) ((x==1)?"":"s")
Definition at line 666 of file lua-5.4.3/src/luac.c.
Referenced by PrintHeader().
toproto
#define toproto (L, i) getproto(s2v(L->top+(i)))
Definition at line 141 of file lua-5.4.3/src/luac.c.
Referenced by combine().
UPVALNAME
#define UPVALNAME (x) ((f->upvalues[x].name) ? getstr(f->upvalues[x].name) : "-")
Definition at line 217 of file lua-5.4.3/src/luac.c.
Referenced by PrintCode(), and PrintDebug().
VOID
#define VOID (p) ((const void*)(p))
Definition at line 218 of file lua-5.4.3/src/luac.c.
Referenced by PrintCode(), PrintDebug(), and PrintHeader().
Function Documentation
cannot()
static void cannot (const char * what) static
Definition at line 48 of file lua-5.4.3/src/luac.c.
{
 fprintf(stderr,"%s: cannot %s %s: %s\n",progname,what,output,strerror(errno));
 exit(EXIT_FAILURE);
}
References output, and progname.
Referenced by pmain().
combine()
static const Proto * combine (lua_State * L, int n) static
Definition at line 143 of file lua-5.4.3/src/luac.c.
{
 if (n==1)
  return toproto(L,-1);
 else
 {
  Proto* f;
  int i=n;
  if (lua_load(L,reader,&i,"=(" PROGNAME ")",NULL)!=LUA_OK) fatal(lua_tostring(L,-1));
  f=toproto(L,-1);
  for (i=0; i<n; i++)
  {
   f->p[i]=toproto(L,i-n-1);
   if (f->p[i]->sizeupvalues>0) f->p[i]->upvalues[0].instack=0;
  }
  f->sizelineinfo=0;
  return f;
 }
}
References fatal(), lua_load(), LUA_OK, lua_tostring, NULL, Proto::p, PROGNAME, reader(), Proto::sizelineinfo, Proto::sizeupvalues, toproto, and Proto::upvalues.
Referenced by pmain().
doargs()
static int doargs (int argc, char * argv[]) static
Definition at line 76 of file lua-5.4.3/src/luac.c.
{
 int i;
 int version=0;
 if (argv[0]!=NULL && *argv[0]!=0) progname=argv[0];
 for (i=1; i<argc; i++)
 {
  if (*argv[i]!='-')            /* end of options; keep it */
   break;
  else if (IS("--"))            /* end of options; skip it */
  {
   ++i;
   if (version) ++version;
   break;
  }
  else if (IS("-"))         /* end of options; use stdin */
   break;
  else if (IS("-l"))            /* list */
   ++listing;
  else if (IS("-o"))            /* output file */
  {
   output=argv[++i];
   if (output==NULL || *output==0 || (*output=='-' && output[1]!=0))
    usage("'-o' needs argument");
   if (IS("-")) output=NULL;
  }
  else if (IS("-p"))            /* parse only */
   dumping=0;
  else if (IS("-s"))            /* strip debug information */
   stripping=1;
  else if (IS("-v"))            /* show version */
   ++version;
  else                  /* unknown option */
   usage(argv[i]);
 }
 if (i==argc && (listing || !dumping))
 {
  dumping=0;
  argv[--i]=Output;
 }
 if (version)
 {
  printf("%s\n",LUA_COPYRIGHT);
  if (version==argc-1) exit(EXIT_SUCCESS);
 }
 return i;
}
References dumping, IS, listing, LUA_COPYRIGHT, NULL, Output, output, printf, progname, stripping, and usage().
Referenced by main().
fatal()
static void fatal (const char * message) static
Definition at line 42 of file lua-5.4.3/src/luac.c.
{
 fprintf(stderr,"%s: %s\n",progname,message);
 exit(EXIT_FAILURE);
}
References progname.
Referenced by combine(), main(), and pmain().
main()
int main (int argc, char * argv[])
Definition at line 197 of file lua-5.4.3/src/luac.c.
{
 lua_State* L;
 int i=doargs(argc,argv);
 argc-=i; argv+=i;
 if (argc<=0) usage("no input files given");
 L=luaL_newstate();
 if (L==NULL) fatal("cannot create state: not enough memory");
 lua_pushcfunction(L,&pmain);
 lua_pushinteger(L,argc);
 lua_pushlightuserdata(L,argv);
 if (lua_pcall(L,2,0,0)!=LUA_OK) fatal(lua_tostring(L,-1));
 lua_close(L);
 return EXIT_SUCCESS;
}
References doargs(), fatal(), lua_close(), LUA_OK, lua_pcall, lua_pushcfunction, lua_pushinteger(), lua_pushlightuserdata(), lua_tostring, luaL_newstate(), NULL, pmain(), and usage().
pmain()
static int pmain (lua_State * L) static
Definition at line 169 of file lua-5.4.3/src/luac.c.
{
 int argc=(int)lua_tointeger(L,1);
 char** argv=(char**)lua_touserdata(L,2);
 const Proto* f;
 int i;
 tmname=G(L)->tmname;
 if (!lua_checkstack(L,argc)) fatal("too many input files");
 for (i=0; i<argc; i++)
 {
  const char* filename=IS("-") ? NULL : argv[i];
  if (luaL_loadfile(L,filename)!=LUA_OK) fatal(lua_tostring(L,-1));
 }
 f=combine(L,argc);
 if (listing) luaU_print(f,listing>1);
 if (dumping)
 {
  FILE* D= (output==NULL) ? stdout : fopen(output,"wb");
  if (D==NULL) cannot("open");
  lua_lock(L);
  luaU_dump(L,f,writer,D,stripping);
  lua_unlock(L);
  if (ferror(D)) cannot("write");
  if (fclose(D)) cannot("close");
 }
 return 0;
}
References cannot(), combine(), dumping, fatal(), G, IS, listing, lua_checkstack(), lua_lock, LUA_OK, lua_tointeger, lua_tostring, lua_touserdata(), lua_unlock, luaL_loadfile, luaU_dump(), luaU_print, NULL, output, stripping, tmname, and writer().
Referenced by main().
PrintCode()
static void PrintCode (const Proto * f) static
Definition at line 335 of file lua-5.4.3/src/luac.c.
{
 const Instruction* code=f->code;
 int pc,n=f->sizecode;
 for (pc=0; pc<n; pc++)
 {
  Instruction i=code[pc];
  OpCode o=GET_OPCODE(i);
  int a=GETARG_A(i);
  int b=GETARG_B(i);
  int c=GETARG_C(i);
  int ax=GETARG_Ax(i);
  int bx=GETARG_Bx(i);
  int sb=GETARG_sB(i);
  int sc=GETARG_sC(i);
  int sbx=GETARG_sBx(i);
  int isk=GETARG_k(i);
  int line=luaG_getfuncline(f,pc);
  printf("\t%d\t",pc+1);
  if (line>0) printf("[%d]\t",line); else printf("[-]\t");
  printf("%-9s\t",opnames[o]);
  switch (o)
  {
   case OP_MOVE:
    printf("%d %d",a,b);
    break;
   case OP_LOADI:
    printf("%d %d",a,sbx);
    break;
   case OP_LOADF:
    printf("%d %d",a,sbx);
    break;
   case OP_LOADK:
    printf("%d %d",a,bx);
    printf(COMMENT); PrintConstant(f,bx);
    break;
   case OP_LOADKX:
    printf("%d",a);
    printf(COMMENT); PrintConstant(f,EXTRAARG);
    break;
   case OP_LOADFALSE:
    printf("%d",a);
    break;
   case OP_LFALSESKIP:
    printf("%d",a);
    break;
   case OP_LOADTRUE:
    printf("%d",a);
    break;
   case OP_LOADNIL:
    printf("%d %d",a,b);
    printf(COMMENT "%d out",b+1);
    break;
   case OP_GETUPVAL:
    printf("%d %d",a,b);
    printf(COMMENT "%s",UPVALNAME(b));
    break;
   case OP_SETUPVAL:
    printf("%d %d",a,b);
    printf(COMMENT "%s",UPVALNAME(b));
    break;
   case OP_GETTABUP:
    printf("%d %d %d",a,b,c);
    printf(COMMENT "%s",UPVALNAME(b));
    printf(" "); PrintConstant(f,c);
    break;
   case OP_GETTABLE:
    printf("%d %d %d",a,b,c);
    break;
   case OP_GETI:
    printf("%d %d %d",a,b,c);
    break;
   case OP_GETFIELD:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_SETTABUP:
    printf("%d %d %d%s",a,b,c,ISK);
    printf(COMMENT "%s",UPVALNAME(a));
    printf(" "); PrintConstant(f,b);
    if (isk) { printf(" "); PrintConstant(f,c); }
    break;
   case OP_SETTABLE:
    printf("%d %d %d%s",a,b,c,ISK);
    if (isk) { printf(COMMENT); PrintConstant(f,c); }
    break;
   case OP_SETI:
    printf("%d %d %d%s",a,b,c,ISK);
    if (isk) { printf(COMMENT); PrintConstant(f,c); }
    break;
   case OP_SETFIELD:
    printf("%d %d %d%s",a,b,c,ISK);
    printf(COMMENT); PrintConstant(f,b);
    if (isk) { printf(" "); PrintConstant(f,c); }
    break;
   case OP_NEWTABLE:
    printf("%d %d %d",a,b,c);
    printf(COMMENT "%d",c+EXTRAARGC);
    break;
   case OP_SELF:
    printf("%d %d %d%s",a,b,c,ISK);
    if (isk) { printf(COMMENT); PrintConstant(f,c); }
    break;
   case OP_ADDI:
    printf("%d %d %d",a,b,sc);
    break;
   case OP_ADDK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_SUBK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_MULK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_MODK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_POWK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_DIVK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_IDIVK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_BANDK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_BORK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_BXORK:
    printf("%d %d %d",a,b,c);
    printf(COMMENT); PrintConstant(f,c);
    break;
   case OP_SHRI:
    printf("%d %d %d",a,b,sc);
    break;
   case OP_SHLI:
    printf("%d %d %d",a,b,sc);
    break;
   case OP_ADD:
    printf("%d %d %d",a,b,c);
    break;
   case OP_SUB:
    printf("%d %d %d",a,b,c);
    break;
   case OP_MUL:
    printf("%d %d %d",a,b,c);
    break;
   case OP_MOD:
    printf("%d %d %d",a,b,c);
    break;
   case OP_POW:
    printf("%d %d %d",a,b,c);
    break;
   case OP_DIV:
    printf("%d %d %d",a,b,c);
    break;
   case OP_IDIV:
    printf("%d %d %d",a,b,c);
    break;
   case OP_BAND:
    printf("%d %d %d",a,b,c);
    break;
   case OP_BOR:
    printf("%d %d %d",a,b,c);
    break;
   case OP_BXOR:
    printf("%d %d %d",a,b,c);
    break;
   case OP_SHL:
    printf("%d %d %d",a,b,c);
    break;
   case OP_SHR:
    printf("%d %d %d",a,b,c);
    break;
   case OP_MMBIN:
    printf("%d %d %d",a,b,c);
    printf(COMMENT "%s",eventname(c));
    break;
   case OP_MMBINI:
    printf("%d %d %d %d",a,sb,c,isk);
    printf(COMMENT "%s",eventname(c));
    if (isk) printf(" flip");
    break;
   case OP_MMBINK:
    printf("%d %d %d %d",a,b,c,isk);
    printf(COMMENT "%s ",eventname(c)); PrintConstant(f,b);
    if (isk) printf(" flip");
    break;
   case OP_UNM:
    printf("%d %d",a,b);
    break;
   case OP_BNOT:
    printf("%d %d",a,b);
    break;
   case OP_NOT:
    printf("%d %d",a,b);
    break;
   case OP_LEN:
    printf("%d %d",a,b);
    break;
   case OP_CONCAT:
    printf("%d %d",a,b);
    break;
   case OP_CLOSE:
    printf("%d",a);
    break;
   case OP_TBC:
    printf("%d",a);
    break;
   case OP_JMP:
    printf("%d",GETARG_sJ(i));
    printf(COMMENT "to %d",GETARG_sJ(i)+pc+2);
    break;
   case OP_EQ:
    printf("%d %d %d",a,b,isk);
    break;
   case OP_LT:
    printf("%d %d %d",a,b,isk);
    break;
   case OP_LE:
    printf("%d %d %d",a,b,isk);
    break;
   case OP_EQK:
    printf("%d %d %d",a,b,isk);
    printf(COMMENT); PrintConstant(f,b);
    break;
   case OP_EQI:
    printf("%d %d %d",a,sb,isk);
    break;
   case OP_LTI:
    printf("%d %d %d",a,sb,isk);
    break;
   case OP_LEI:
    printf("%d %d %d",a,sb,isk);
    break;
   case OP_GTI:
    printf("%d %d %d",a,sb,isk);
    break;
   case OP_GEI:
    printf("%d %d %d",a,sb,isk);
    break;
   case OP_TEST:
    printf("%d %d",a,isk);
    break;
   case OP_TESTSET:
    printf("%d %d %d",a,b,isk);
    break;
   case OP_CALL:
    printf("%d %d %d",a,b,c);
    printf(COMMENT);
    if (b==0) printf("all in "); else printf("%d in ",b-1);
    if (c==0) printf("all out"); else printf("%d out",c-1);
    break;
   case OP_TAILCALL:
    printf("%d %d %d",a,b,c);
    printf(COMMENT "%d in",b-1);
    break;
   case OP_RETURN:
    printf("%d %d %d",a,b,c);
    printf(COMMENT);
    if (b==0) printf("all out"); else printf("%d out",b-1);
    break;
   case OP_RETURN0:
    break;
   case OP_RETURN1:
    printf("%d",a);
    break;
   case OP_FORLOOP:
    printf("%d %d",a,bx);
    printf(COMMENT "to %d",pc-bx+2);
    break;
   case OP_FORPREP:
    printf("%d %d",a,bx);
    printf(COMMENT "to %d",pc+bx+2);
    break;
   case OP_TFORPREP:
    printf("%d %d",a,bx);
    printf(COMMENT "to %d",pc+bx+2);
    break;
   case OP_TFORCALL:
    printf("%d %d",a,c);
    break;
   case OP_TFORLOOP:
    printf("%d %d",a,bx);
    printf(COMMENT "to %d",pc-bx+2);
    break;
   case OP_SETLIST:
    printf("%d %d %d",a,b,c);
    if (isk) printf(COMMENT "%d",c+EXTRAARGC);
    break;
   case OP_CLOSURE:
    printf("%d %d",a,bx);
    printf(COMMENT "%p",VOID(f->p[bx]));
    break;
   case OP_VARARG:
    printf("%d %d",a,c);
    printf(COMMENT);
    if (c==0) printf("all out"); else printf("%d out",c-1);
    break;
   case OP_VARARGPREP:
    printf("%d",a);
    break;
   case OP_EXTRAARG:
    printf("%d",ax);
    break;
#if 0
   default:
    printf("%d %d %d",a,b,c);
    printf(COMMENT "not handled");
    break;
#endif
  }
  printf("\n");
 }
}
References Proto::code, COMMENT, eventname, EXTRAARG, EXTRAARGC, GET_OPCODE, GETARG_A, GETARG_Ax, GETARG_B, GETARG_Bx, GETARG_C, GETARG_k, GETARG_sB, GETARG_sBx, GETARG_sC, GETARG_sJ, ISK, luaG_getfuncline(), OP_ADD, OP_ADDI, OP_ADDK, OP_BAND, OP_BANDK, OP_BNOT, OP_BOR, OP_BORK, OP_BXOR, OP_BXORK, OP_CALL, OP_CLOSE, OP_CLOSURE, OP_CONCAT, OP_DIV, OP_DIVK, OP_EQ, OP_EQI, OP_EQK, OP_EXTRAARG, OP_FORLOOP, OP_FORPREP, OP_GEI, OP_GETFIELD, OP_GETI, OP_GETTABLE, OP_GETTABUP, OP_GETUPVAL, OP_GTI, OP_IDIV, OP_IDIVK, OP_JMP, OP_LE, OP_LEI, OP_LEN, OP_LFALSESKIP, OP_LOADF, OP_LOADFALSE, OP_LOADI, OP_LOADK, OP_LOADKX, OP_LOADNIL, OP_LOADTRUE, OP_LT, OP_LTI, OP_MMBIN, OP_MMBINI, OP_MMBINK, OP_MOD, OP_MODK, OP_MOVE, OP_MUL, OP_MULK, OP_NEWTABLE, OP_NOT, OP_POW, OP_POWK, OP_RETURN, OP_RETURN0, OP_RETURN1, OP_SELF, OP_SETFIELD, OP_SETI, OP_SETLIST, OP_SETTABLE, OP_SETTABUP, OP_SETUPVAL, OP_SHL, OP_SHLI, OP_SHR, OP_SHRI, OP_SUB, OP_SUBK, OP_TAILCALL, OP_TBC, OP_TEST, OP_TESTSET, OP_TFORCALL, OP_TFORLOOP, OP_TFORPREP, OP_UNM, OP_VARARG, OP_VARARGPREP, opnames, Proto::p, PrintConstant(), printf, Proto::sizecode, UPVALNAME, and VOID.
Referenced by PrintFunction().
PrintConstant()
static void PrintConstant (const Proto * f, int i) static
Definition at line 295 of file lua-5.4.3/src/luac.c.
{
 const TValue* o=&f->k[i];
 switch (ttypetag(o))
 {
  case LUA_VNIL:
    printf("nil");
    break;
  case LUA_VFALSE:
    printf("false");
    break;
  case LUA_VTRUE:
    printf("true");
    break;
  case LUA_VNUMFLT:
    {
    char buff[100];
    sprintf(buff,LUA_NUMBER_FMT,fltvalue(o));
    printf("%s",buff);
    if (buff[strspn(buff,"-0123456789")]=='\0') printf(".0");
    break;
    }
  case LUA_VNUMINT:
    printf(LUA_INTEGER_FMT,ivalue(o));
    break;
  case LUA_VSHRSTR:
  case LUA_VLNGSTR:
    PrintString(tsvalue(o));
    break;
  default:              /* cannot happen */
    printf("?%d",ttypetag(o));
    break;
 }
}
References fltvalue, ivalue, Proto::k, LUA_INTEGER_FMT, LUA_NUMBER_FMT, LUA_VFALSE, LUA_VLNGSTR, LUA_VNIL, LUA_VNUMFLT, LUA_VNUMINT, LUA_VSHRSTR, LUA_VTRUE, printf, PrintString(), tsvalue, and ttypetag.
Referenced by PrintCode(), and PrintDebug().
PrintDebug()
static void PrintDebug (const Proto * f) static
Definition at line 689 of file lua-5.4.3/src/luac.c.
{
 int i,n;
 n=f->sizek;
 printf("constants (%d) for %p:\n",n,VOID(f));
 for (i=0; i<n; i++)
 {
  printf("\t%d\t",i);
  PrintType(f,i);
  PrintConstant(f,i);
  printf("\n");
 }
 n=f->sizelocvars;
 printf("locals (%d) for %p:\n",n,VOID(f));
 for (i=0; i<n; i++)
 {
  printf("\t%d\t%s\t%d\t%d\n",
  i,getstr(f->locvars[i].varname),f->locvars[i].startpc+1,f->locvars[i].endpc+1);
 }
 n=f->sizeupvalues;
 printf("upvalues (%d) for %p:\n",n,VOID(f));
 for (i=0; i<n; i++)
 {
  printf("\t%d\t%s\t%d\t%d\n",
  i,UPVALNAME(i),f->upvalues[i].instack,f->upvalues[i].idx);
 }
}
References LocVar::endpc, getstr, Proto::locvars, PrintConstant(), printf, PrintType(), Proto::sizek, Proto::sizelocvars, Proto::sizeupvalues, LocVar::startpc, UPVALNAME, Proto::upvalues, LocVar::varname, and VOID.
Referenced by PrintFunction().
PrintFunction()
static void PrintFunction (const Proto * f, int full) static
Definition at line 717 of file lua-5.4.3/src/luac.c.
{
 int i,n=f->sizep;
 PrintHeader(f);
 PrintCode(f);
 if (full) PrintDebug(f);
 for (i=0; i<n; i++) PrintFunction(f->p[i],full);
}
References Proto::p, PrintCode(), PrintDebug(), PrintFunction, PrintHeader(), and Proto::sizep.
PrintHeader()
static void PrintHeader (const Proto * f) static
Definition at line 669 of file lua-5.4.3/src/luac.c.
{
 const char* s=f->source ? getstr(f->source) : "=?";
 if (*s=='@' || *s=='=')
  s++;
 else if (*s==LUA_SIGNATURE[0])
  s="(bstring)";
 else
  s="(string)";
 printf("\n%s <%s:%d,%d> (%d instruction%s at %p)\n",
    (f->linedefined==0)?"main":"function",s,
    f->linedefined,f->lastlinedefined,
    S(f->sizecode),VOID(f));
 printf("%d%s param%s, %d slot%s, %d upvalue%s, ",
    (int)(f->numparams),f->is_vararg?"+":"",SS(f->numparams),
    S(f->maxstacksize),S(f->sizeupvalues));
 printf("%d local%s, %d constant%s, %d function%s\n",
    S(f->sizelocvars),S(f->sizek),S(f->sizep));
}
References getstr, Proto::is_vararg, Proto::lastlinedefined, Proto::linedefined, LUA_SIGNATURE, Proto::maxstacksize, Proto::numparams, printf, S, s, Proto::sizecode, Proto::sizek, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, SS, and VOID.
Referenced by PrintFunction().
PrintString()
static void PrintString (const TString * ts) static
Definition at line 221 of file lua-5.4.3/src/luac.c.
{
 const char* s=getstr(ts);
 size_t i,n=tsslen(ts);
 printf("\"");
 for (i=0; i<n; i++)
 {
  int c=(int)(unsigned char)s[i];
  switch (c)
  {
   case '"':
    printf("\\\"");
    break;
   case '\\':
    printf("\\\\");
    break;
   case '\a':
    printf("\\a");
    break;
   case '\b':
    printf("\\b");
    break;
   case '\f':
    printf("\\f");
    break;
   case '\n':
    printf("\\n");
    break;
   case '\r':
    printf("\\r");
    break;
   case '\t':
    printf("\\t");
    break;
   case '\v':
    printf("\\v");
    break;
   default:
    if (isprint(c)) printf("%c",c); else printf("\\%03d",c);
    break;
  }
 }
 printf("\"");
}
References getstr, printf, s, and tsslen.
Referenced by PrintConstant().
PrintType()
static void PrintType (const Proto * f, int i) static
Definition at line 266 of file lua-5.4.3/src/luac.c.
{
 const TValue* o=&f->k[i];
 switch (ttypetag(o))
 {
  case LUA_VNIL:
    printf("N");
    break;
  case LUA_VFALSE:
  case LUA_VTRUE:
    printf("B");
    break;
  case LUA_VNUMFLT:
    printf("F");
    break;
  case LUA_VNUMINT:
    printf("I");
    break;
  case LUA_VSHRSTR:
  case LUA_VLNGSTR:
    printf("S");
    break;
  default:              /* cannot happen */
    printf("?%d",ttypetag(o));
    break;
 }
 printf("\t");
}
References Proto::k, LUA_VFALSE, LUA_VLNGSTR, LUA_VNIL, LUA_VNUMFLT, LUA_VNUMINT, LUA_VSHRSTR, LUA_VTRUE, printf, and ttypetag.
Referenced by PrintDebug().
reader()
static const char * reader (lua_State * L, void * ud, size_t * size) static
Definition at line 126 of file lua-5.4.3/src/luac.c.
{
 UNUSED(L);
 if ((*(int*)ud)--)
 {
  *size=sizeof(FUNCTION)-1;
  return FUNCTION;
 }
 else
 {
  *size=0;
  return NULL;
 }
}
References FUNCTION, NULL, and UNUSED.
Referenced by combine().
usage()
static void usage (const char * message) static
Definition at line 54 of file lua-5.4.3/src/luac.c.
{
 if (*message=='-')
  fprintf(stderr,"%s: unrecognized option '%s'\n",progname,message);
 else
  fprintf(stderr,"%s: %s\n",progname,message);
 fprintf(stderr,
  "usage: %s [options] [filenames]\n"
  "Available options are:\n"
  "  -l       list (use -l -l for full listing)\n"
  "  -o name  output to file 'name' (default is \"%s\")\n"
  "  -p       parse only\n"
  "  -s       strip debug information\n"
  "  -v       show version information\n"
  "  --       stop handling options\n"
  "  -        stop handling options and process stdin\n"
  ,progname,Output);
 exit(EXIT_FAILURE);
}
References Output, and progname.
Referenced by doargs(), and main().
writer()
static int writer (lua_State * L, const void * p, size_t size, void * u) static
Definition at line 163 of file lua-5.4.3/src/luac.c.
{
 UNUSED(L);
 return (fwrite(p,size,1,(FILE*)u)!=1) && (size!=0);
}
References fwrite(), and UNUSED.
Referenced by pmain().
Variable Documentation
dumping
int dumping =1 static
Definition at line 35 of file lua-5.4.3/src/luac.c.
Referenced by doargs(), and pmain().
listing
int listing =0 static
Definition at line 34 of file lua-5.4.3/src/luac.c.
Referenced by doargs(), and pmain().
Output
char Output[] ={ OUTPUT } static
Definition at line 37 of file lua-5.4.3/src/luac.c.
{ OUTPUT }; /* default output file name */
Referenced by doargs(), and usage().
output
const char* output =Output static
Definition at line 38 of file lua-5.4.3/src/luac.c.
Referenced by cannot(), doargs(), and pmain().
progname
const char* progname =PROGNAME static
Definition at line 39 of file lua-5.4.3/src/luac.c.
Referenced by cannot(), doargs(), fatal(), and usage().
stripping
int stripping =0 static
Definition at line 36 of file lua-5.4.3/src/luac.c.
Referenced by doargs(), and pmain().
tmname
TString** tmname static
Definition at line 40 of file lua-5.4.3/src/luac.c.
Referenced by funcnamefromcode(), funcnamefromcode(), getfuncname(), luaT_gettmbyobj(), luaT_init(), and pmain().