Github User Fetcher: ltablib.c File Reference
ltablib.c File Reference
#include <limits.h>
#include <stddef.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define ltablib_c
#define LUA_LIB
#define aux_getn(L, n) (luaL_checktype(L, n, LUA_TTABLE), luaL_len(L, n))
Functions
static int tinsert (lua_State *L)
static int tremove (lua_State *L)
static void addfield (lua_State *L, luaL_Buffer *b, int i)
static int tconcat (lua_State *L)
static int pack (lua_State *L)
static int unpack (lua_State *L)
static void set2 (lua_State *L, int i, int j)
static int sort_comp (lua_State *L, int a, int b)
static void auxsort (lua_State *L, int l, int u)
static int sort (lua_State *L)
LUAMOD_API int luaopen_table (lua_State *L)
Variables
static const luaL_Reg tab_funcs []
Macro Definition Documentation
aux_getn
#define aux_getn (L, n) (luaL_checktype(L, n, LUA_TTABLE), luaL_len(L, n))
Definition at line 20 of file lua-5.2.4/src/ltablib.c.
Referenced by sort(), tinsert(), and tremove().
ltablib_c
#define ltablib_c
Definition at line 11 of file lua-5.2.4/src/ltablib.c.
LUA_LIB
#define LUA_LIB
Definition at line 12 of file lua-5.2.4/src/ltablib.c.
Function Documentation
addfield()
static void addfield (lua_State * L, luaL_Buffer * b, int i) static
Definition at line 85 of file lua-5.2.4/src/ltablib.c.
{
  lua_rawgeti(L, 1, i);
  if (!lua_isstring(L, -1))
    luaL_error(L, "invalid value (%s) at index %d in table for "
                  LUA_QL("concat"), luaL_typename(L, -1), i);
  luaL_addvalue(b);
}
References lua_isstring(), LUA_QL, lua_rawgeti(), luaL_addvalue(), luaL_error(), and luaL_typename.
Referenced by tconcat().
auxsort()
static void auxsort (lua_State * L, int l, int u) static
Definition at line 186 of file lua-5.2.4/src/ltablib.c.
{
  while (l < u) {  /* for tail recursion */
    int i, j;
    /* sort elements a[l], a[(l+u)/2] and a[u] */
    lua_rawgeti(L, 1, l);
    lua_rawgeti(L, 1, u);
    if (sort_comp(L, -1, -2))  /* a[u] < a[l]? */
      set2(L, l, u);  /* swap a[l] - a[u] */
    else
      lua_pop(L, 2);
    if (u-l == 1) break;  /* only 2 elements */
    i = (l+u)/2;
    lua_rawgeti(L, 1, i);
    lua_rawgeti(L, 1, l);
    if (sort_comp(L, -2, -1))  /* a[i]<a[l]? */
      set2(L, i, l);
    else {
      lua_pop(L, 1);  /* remove a[l] */
      lua_rawgeti(L, 1, u);
      if (sort_comp(L, -1, -2))  /* a[u]<a[i]? */
        set2(L, i, u);
      else
        lua_pop(L, 2);
    }
    if (u-l == 2) break;  /* only 3 elements */
    lua_rawgeti(L, 1, i);  /* Pivot */
    lua_pushvalue(L, -1);
    lua_rawgeti(L, 1, u-1);
    set2(L, i, u-1);
    /* a[l] <= P == a[u-1] <= a[u], only need to sort from l+1 to u-2 */
    i = l; j = u-1;
    for (;;) {  /* invariant: a[l..i] <= P <= a[j..u] */
      /* repeat ++i until a[i] >= P */
      while (lua_rawgeti(L, 1, ++i), sort_comp(L, -1, -2)) {
        if (i>=u) luaL_error(L, "invalid order function for sorting");
        lua_pop(L, 1);  /* remove a[i] */
      }
      /* repeat --j until a[j] <= P */
      while (lua_rawgeti(L, 1, --j), sort_comp(L, -3, -1)) {
        if (j<=l) luaL_error(L, "invalid order function for sorting");
        lua_pop(L, 1);  /* remove a[j] */
      }
      if (j<i) {
        lua_pop(L, 3);  /* pop pivot, a[i], a[j] */
        break;
      }
      set2(L, i, j);
    }
    lua_rawgeti(L, 1, u-1);
    lua_rawgeti(L, 1, i);
    set2(L, u-1, i);  /* swap pivot (a[u-1]) with a[i] */
    /* a[l..i-1] <= a[i] == P <= a[i+1..u] */
    /* adjust so that smaller half is in [j..i] and larger one in [l..u] */
    if (i-l < u-i) {
      j=l; i=i-1; l=i+2;
    }
    else {
      j=i+1; i=u; u=j-2;
    }
    auxsort(L, j, i);  /* call recursively the smaller one */
  }  /* repeat the routine for the larger one */
}
References auxsort(), lua_pop, lua_pushvalue(), lua_rawgeti(), luaL_error(), set2(), and sort_comp().
Referenced by auxsort(), and sort().
luaopen_table()
LUAMOD_API int luaopen_table (lua_State * L)
Definition at line 276 of file lua-5.2.4/src/ltablib.c.
{
  luaL_newlib(L, tab_funcs);
#if defined(LUA_COMPAT_UNPACK)
  /* _G.unpack = table.unpack */
  lua_getfield(L, -1, "unpack");
  lua_setglobal(L, "unpack");
#endif
  return 1;
}
References lua_getfield(), lua_setglobal, luaL_newlib, and tab_funcs.
pack()
static int pack (lua_State * L) static
Definition at line 120 of file lua-5.2.4/src/ltablib.c.
{
  int n = lua_gettop(L);  /* number of elements to pack */
  lua_createtable(L, n, 1);  /* create result table */
  lua_pushinteger(L, n);
  lua_setfield(L, -2, "n");  /* t.n = number of elements */
  if (n > 0) {  /* at least one element? */
    int i;
    lua_pushvalue(L, 1);
    lua_rawseti(L, -2, 1);  /* insert first element */
    lua_replace(L, 1);  /* move table into index 1 */
    for (i = n; i >= 2; i--)  /* assign other elements */
      lua_rawseti(L, 1, i);
  }
  return 1;  /* return table */
}
References lua_createtable(), lua_gettop(), lua_pushinteger(), lua_pushvalue(), lua_rawseti(), lua_replace, and lua_setfield().
set2()
static void set2 (lua_State * L, int i, int j) static
Definition at line 166 of file lua-5.2.4/src/ltablib.c.
{
  lua_rawseti(L, 1, i);
  lua_rawseti(L, 1, j);
}
References lua_rawseti().
Referenced by auxsort().
sort()
static int sort (lua_State * L) static
Definition at line 249 of file lua-5.2.4/src/ltablib.c.
{
  int n = aux_getn(L, 1);
  luaL_checkstack(L, 40, "");  /* assume array is smaller than 2^40 */
  if (!lua_isnoneornil(L, 2))  /* is there a 2nd argument? */
    luaL_checktype(L, 2, LUA_TFUNCTION);
  lua_settop(L, 2);  /* make sure there is two arguments */
  auxsort(L, 1, n);
  return 0;
}
References aux_getn, auxsort(), lua_isnoneornil, lua_settop(), LUA_TFUNCTION, luaL_checkstack(), and luaL_checktype().
sort_comp()
static int sort_comp (lua_State * L, int a, int b) static
Definition at line 171 of file lua-5.2.4/src/ltablib.c.
{
  if (!lua_isnil(L, 2)) {  /* function? */
    int res;
    lua_pushvalue(L, 2);
    lua_pushvalue(L, a-1);  /* -1 to compensate function */
    lua_pushvalue(L, b-2);  /* -2 to compensate function and `a' */
    lua_call(L, 2, 1);
    res = lua_toboolean(L, -1);
    lua_pop(L, 1);
    return res;
  }
  else  /* a < b? */
    return lua_compare(L, a, b, LUA_OPLT);
}
References lua_call, lua_compare(), lua_isnil, LUA_OPLT, lua_pop, lua_pushvalue(), and lua_toboolean().
Referenced by auxsort().
tconcat()
static int tconcat (lua_State * L) static
Definition at line 94 of file lua-5.2.4/src/ltablib.c.
{
  luaL_Buffer b;
  size_t lsep;
  int i, last;
  const char *sep = luaL_optlstring(L, 2, "", &lsep);
  luaL_checktype(L, 1, LUA_TTABLE);
  i = luaL_optint(L, 3, 1);
  last = luaL_opt(L, luaL_checkint, 4, luaL_len(L, 1));
  luaL_buffinit(L, &b);
  for (; i < last; i++) {
    addfield(L, &b, i);
    luaL_addlstring(&b, sep, lsep);
  }
  if (i == last)  /* add last value (if interval was not empty) */
    addfield(L, &b, i);
  luaL_pushresult(&b);
  return 1;
}
References addfield(), LUA_TTABLE, luaL_addlstring(), luaL_buffinit(), luaL_checkint, luaL_checktype(), luaL_len(), luaL_opt, luaL_optint, luaL_optlstring(), and luaL_pushresult().
tinsert()
static int tinsert (lua_State * L) static
Definition at line 42 of file lua-5.2.4/src/ltablib.c.
{
  int e = aux_getn(L, 1) + 1;  /* first empty element */
  int pos;  /* where to insert new element */
  switch (lua_gettop(L)) {
    case 2: {  /* called with only 2 arguments */
      pos = e;  /* insert new element at the end */
      break;
    }
    case 3: {
      int i;
      pos = luaL_checkint(L, 2);  /* 2nd argument is the position */
      luaL_argcheck(L, 1 <= pos && pos <= e, 2, "position out of bounds");
      for (i = e; i > pos; i--) {  /* move up elements */
        lua_rawgeti(L, 1, i-1);
        lua_rawseti(L, 1, i);  /* t[i] = t[i-1] */
      }
      break;
    }
    default: {
      return luaL_error(L, "wrong number of arguments to " LUA_QL("insert"));
    }
  }
  lua_rawseti(L, 1, pos);  /* t[pos] = v */
  return 0;
}
References aux_getn, lua_gettop(), LUA_QL, lua_rawgeti(), lua_rawseti(), luaL_argcheck, luaL_checkint, and luaL_error().
tremove()
static int tremove (lua_State * L) static
Definition at line 69 of file lua-5.2.4/src/ltablib.c.
{
  int size = aux_getn(L, 1);
  int pos = luaL_optint(L, 2, size);
  if (pos != size)  /* validate 'pos' if given */
    luaL_argcheck(L, 1 <= pos && pos <= size + 1, 1, "position out of bounds");
  lua_rawgeti(L, 1, pos);  /* result = t[pos] */
  for ( ; pos < size; pos++) {
    lua_rawgeti(L, 1, pos+1);
    lua_rawseti(L, 1, pos);  /* t[pos] = t[pos+1] */
  }
  lua_pushnil(L);
  lua_rawseti(L, 1, pos);  /* t[pos] = nil */
  return 1;
}
References aux_getn, lua_pushnil(), lua_rawgeti(), lua_rawseti(), luaL_argcheck, and luaL_optint.
unpack()
static int unpack (lua_State * L) static
Definition at line 137 of file lua-5.2.4/src/ltablib.c.
{
  int i, e;
  unsigned int n;
  luaL_checktype(L, 1, LUA_TTABLE);
  i = luaL_optint(L, 2, 1);
  e = luaL_opt(L, luaL_checkint, 3, luaL_len(L, 1));
  if (i > e) return 0;  /* empty range */
  n = (unsigned int)e - (unsigned int)i;  /* number of elements minus 1 */
  if (n > (INT_MAX - 10) || !lua_checkstack(L, ++n))
    return luaL_error(L, "too many results to unpack");
  lua_rawgeti(L, 1, i);  /* push arg[i] (avoiding overflow problems) */
  while (i++ < e)  /* push arg[i + 1...e] */
    lua_rawgeti(L, 1, i);
  return n;
}
References lua_checkstack(), lua_rawgeti(), LUA_TTABLE, luaL_checkint, luaL_checktype(), luaL_error(), luaL_len(), luaL_opt, and luaL_optint.
Variable Documentation
tab_funcs
const luaL_Reg tab_funcs[] static
Initial value:
= {
  {"concat", tconcat},
  {"insert", tinsert},
  {"pack", pack},
  {"unpack", unpack},
  {"remove", tremove},
  {"sort", sort},
  {NULL, NULL}
}
Definition at line 262 of file lua-5.2.4/src/ltablib.c.
{
  {"concat", tconcat},
#if defined(LUA_COMPAT_MAXN)
  {"maxn", maxn},
#endif
  {"insert", tinsert},
  {"pack", pack},
  {"unpack", unpack},
  {"remove", tremove},
  {"sort", sort},
  {NULL, NULL}
};
Referenced by luaopen_table().