Github User Fetcher: ldblib.c File Reference
ldblib.c File Reference
#include "lprefix.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define ldblib_c
#define LUA_LIB
Functions
static void checkstack (lua_State *L, lua_State *L1, int n)
static int db_getregistry (lua_State *L)
static int db_getmetatable (lua_State *L)
static int db_setmetatable (lua_State *L)
static int db_getuservalue (lua_State *L)
static int db_setuservalue (lua_State *L)
static lua_State * getthread (lua_State *L, int *arg)
static void settabss (lua_State *L, const char *k, const char *v)
static void settabsi (lua_State *L, const char *k, int v)
static void settabsb (lua_State *L, const char *k, int v)
static void treatstackoption (lua_State *L, lua_State *L1, const char *fname)
static int db_getinfo (lua_State *L)
static int db_getlocal (lua_State *L)
static int db_setlocal (lua_State *L)
static int auxupvalue (lua_State *L, int get)
static int db_getupvalue (lua_State *L)
static int db_setupvalue (lua_State *L)
static void * checkupval (lua_State *L, int argf, int argnup, int *pnup)
static int db_upvalueid (lua_State *L)
static int db_upvaluejoin (lua_State *L)
static void hookf (lua_State *L, lua_Debug *ar)
static int makemask (const char *smask, int count)
static char * unmakemask (int mask, char *smask)
static int db_sethook (lua_State *L)
static int db_gethook (lua_State *L)
static int db_debug (lua_State *L)
static int db_traceback (lua_State *L)
static int db_setcstacklimit (lua_State *L)
LUAMOD_API int luaopen_debug (lua_State *L)
Variables
static const char *const HOOKKEY = "_HOOKKEY"
static const luaL_Reg dblib []
Macro Definition Documentation
ldblib_c
#define ldblib_c
Definition at line 7 of file lua-5.4.3/src/ldblib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.4.3/src/ldblib.c.
Function Documentation
auxupvalue()
static int auxupvalue (lua_State * L, int get) static
Definition at line 258 of file lua-5.4.3/src/ldblib.c.
{
  const char *name;
  int n = (int)luaL_checkinteger(L, 2);  /* upvalue index */
  luaL_checktype(L, 1, LUA_TFUNCTION);  /* closure */
  name = get ? lua_getupvalue(L, 1, n) : lua_setupvalue(L, 1, n);
  if (name == NULL) return 0;
  lua_pushstring(L, name);
  lua_insert(L, -(get+1));  /* no-op if get is false */
  return get + 1;
}
References lua_getupvalue(), lua_insert, lua_pushstring(), lua_setupvalue(), LUA_TFUNCTION, luaL_checkinteger(), luaL_checktype(), name, and NULL.
Referenced by db_getupvalue(), and db_setupvalue().
checkstack()
static void checkstack (lua_State * L, lua_State * L1, int n) static
Definition at line 35 of file lua-5.4.3/src/ldblib.c.
{
  if (l_unlikely(L != L1 && !lua_checkstack(L1, n)))
    luaL_error(L, "stack overflow");
}
References lua_checkstack(), and luaL_error().
Referenced by db_gethook(), db_getinfo(), db_getlocal(), db_sethook(), and db_setlocal().
checkupval()
static void * checkupval (lua_State * L, int argf, int argnup, int * pnup) static
Definition at line 285 of file lua-5.4.3/src/ldblib.c.
{
  void *id;
  int nup = (int)luaL_checkinteger(L, argnup);  /* upvalue index */
  luaL_checktype(L, argf, LUA_TFUNCTION);  /* closure */
  id = lua_upvalueid(L, argf, nup);
  if (pnup) {
    luaL_argcheck(L, id != NULL, argnup, "invalid upvalue index");
    *pnup = nup;
  }
  return id;
}
References LUA_TFUNCTION, lua_upvalueid(), luaL_argcheck, luaL_checkinteger(), luaL_checktype(), and NULL.
Referenced by db_upvalueid(), and db_upvaluejoin().
db_debug()
static int db_debug (lua_State * L) static
Definition at line 420 of file lua-5.4.3/src/ldblib.c.
{
  for (;;) {
    char buffer[250];
    lua_writestringerror("%s", "lua_debug> ");
    if (fgets(buffer, sizeof(buffer), stdin) == NULL ||
        strcmp(buffer, "cont\n") == 0)
      return 0;
    if (luaL_loadbuffer(L, buffer, strlen(buffer), "=(debug command)") ||
        lua_pcall(L, 0, 0, 0))
      lua_writestringerror("%s\n", luaL_tolstring(L, -1, NULL));
    lua_settop(L, 0);  /* remove eventual returns */
  }
}
References lua_pcall, lua_settop(), lua_writestringerror, luaL_loadbuffer, luaL_tolstring(), and NULL.
db_gethook()
static int db_gethook (lua_State * L) static
Definition at line 395 of file lua-5.4.3/src/ldblib.c.
{
  int arg;
  lua_State *L1 = getthread(L, &arg);
  char buff[5];
  int mask = lua_gethookmask(L1);
  lua_Hook hook = lua_gethook(L1);
  if (hook == NULL) {  /* no hook? */
    luaL_pushfail(L);
    return 1;
  }
  else if (hook != hookf)  /* external hook? */
    lua_pushliteral(L, "external hook");
  else {  /* hook table must exist */
    lua_getfield(L, LUA_REGISTRYINDEX, HOOKKEY);
    checkstack(L, L1, 1);
    lua_pushthread(L1); lua_xmove(L1, L, 1);
    lua_rawget(L, -2);   /* 1st result = hooktable[L1] */
    lua_remove(L, -2);  /* remove hook table */
  }
  lua_pushstring(L, unmakemask(mask, buff));  /* 2nd result = mask */
  lua_pushinteger(L, lua_gethookcount(L1));  /* 3rd result = count */
  return 3;
}
References arg, checkstack(), getthread(), hookf(), HOOKKEY, lua_getfield(), lua_gethook(), lua_gethookcount(), lua_gethookmask(), lua_pushinteger(), lua_pushliteral, lua_pushstring(), lua_pushthread(), lua_rawget(), LUA_REGISTRYINDEX, lua_remove, lua_xmove(), luaL_pushfail, mask, NULL, and unmakemask().
db_getinfo()
static int db_getinfo (lua_State * L) static
Definition at line 149 of file lua-5.4.3/src/ldblib.c.
{
  lua_Debug ar;
  int arg;
  lua_State *L1 = getthread(L, &arg);
  const char *options = luaL_optstring(L, arg+2, "flnSrtu");
  checkstack(L, L1, 3);
  luaL_argcheck(L, options[0] != '>', arg + 2, "invalid option '>'");
  if (lua_isfunction(L, arg + 1)) {  /* info about a function? */
    options = lua_pushfstring(L, ">%s", options);  /* add '>' to 'options' */
    lua_pushvalue(L, arg + 1);  /* move function to 'L1' stack */
    lua_xmove(L, L1, 1);
  }
  else {  /* stack level */
    if (!lua_getstack(L1, (int)luaL_checkinteger(L, arg + 1), &ar)) {
      luaL_pushfail(L);  /* level out of range */
      return 1;
    }
  }
  if (!lua_getinfo(L1, options, &ar))
    return luaL_argerror(L, arg+2, "invalid option");
  lua_newtable(L);  /* table to collect results */
  if (strchr(options, 'S')) {
    lua_pushlstring(L, ar.source, ar.srclen);
    lua_setfield(L, -2, "source");
    settabss(L, "short_src", ar.short_src);
    settabsi(L, "linedefined", ar.linedefined);
    settabsi(L, "lastlinedefined", ar.lastlinedefined);
    settabss(L, "what", ar.what);
  }
  if (strchr(options, 'l'))
    settabsi(L, "currentline", ar.currentline);
  if (strchr(options, 'u')) {
    settabsi(L, "nups", ar.nups);
    settabsi(L, "nparams", ar.nparams);
    settabsb(L, "isvararg", ar.isvararg);
  }
  if (strchr(options, 'n')) {
    settabss(L, "name", ar.name);
    settabss(L, "namewhat", ar.namewhat);
  }
  if (strchr(options, 'r')) {
    settabsi(L, "ftransfer", ar.ftransfer);
    settabsi(L, "ntransfer", ar.ntransfer);
  }
  if (strchr(options, 't'))
    settabsb(L, "istailcall", ar.istailcall);
  if (strchr(options, 'L'))
    treatstackoption(L, L1, "activelines");
  if (strchr(options, 'f'))
    treatstackoption(L, L1, "func");
  return 1;  /* return table */
}
References arg, checkstack(), lua_Debug::currentline, lua_Debug::ftransfer, getthread(), lua_Debug::istailcall, lua_Debug::isvararg, lua_Debug::lastlinedefined, lua_Debug::linedefined, lua_getinfo(), lua_getstack(), lua_isfunction, lua_newtable, lua_pushfstring(), lua_pushlstring(), lua_pushvalue(), lua_setfield(), lua_xmove(), luaL_argcheck, luaL_argerror(), luaL_checkinteger(), luaL_optstring, luaL_pushfail, lua_Debug::name, lua_Debug::namewhat, lua_Debug::nparams, lua_Debug::ntransfer, lua_Debug::nups, settabsb(), settabsi(), settabss(), lua_Debug::short_src, lua_Debug::source, lua_Debug::srclen, treatstackoption(), and lua_Debug::what.
db_getlocal()
static int db_getlocal (lua_State * L) static
Definition at line 203 of file lua-5.4.3/src/ldblib.c.
{
  int arg;
  lua_State *L1 = getthread(L, &arg);
  int nvar = (int)luaL_checkinteger(L, arg + 2);  /* local-variable index */
  if (lua_isfunction(L, arg + 1)) {  /* function argument? */
    lua_pushvalue(L, arg + 1);  /* push function */
    lua_pushstring(L, lua_getlocal(L, NULL, nvar));  /* push local name */
    return 1;  /* return only name (there is no value) */
  }
  else {  /* stack-level argument */
    lua_Debug ar;
    const char *name;
    int level = (int)luaL_checkinteger(L, arg + 1);
    if (l_unlikely(!lua_getstack(L1, level, &ar)))  /* out of range? */
      return luaL_argerror(L, arg+1, "level out of range");
    checkstack(L, L1, 1);
    name = lua_getlocal(L1, &ar, nvar);
    if (name) {
      lua_xmove(L1, L, 1);  /* move local value */
      lua_pushstring(L, name);  /* push name */
      lua_rotate(L, -2, 1);  /* re-order */
      return 2;
    }
    else {
      luaL_pushfail(L);  /* no name (nor value) */
      return 1;
    }
  }
}
References arg, checkstack(), getthread(), lua_getlocal(), lua_getstack(), lua_isfunction, lua_pushstring(), lua_pushvalue(), lua_rotate(), lua_xmove(), luaL_argerror(), luaL_checkinteger(), luaL_pushfail, name, and NULL.
db_getmetatable()
static int db_getmetatable (lua_State * L) static
Definition at line 47 of file lua-5.4.3/src/ldblib.c.
{
  luaL_checkany(L, 1);
  if (!lua_getmetatable(L, 1)) {
    lua_pushnil(L);  /* no metatable */
  }
  return 1;
}
References lua_getmetatable(), lua_pushnil(), and luaL_checkany().
db_getregistry()
static int db_getregistry (lua_State * L) static
Definition at line 41 of file lua-5.4.3/src/ldblib.c.
{
  lua_pushvalue(L, LUA_REGISTRYINDEX);
  return 1;
}
References lua_pushvalue(), and LUA_REGISTRYINDEX.
db_getupvalue()
static int db_getupvalue (lua_State * L) static
Definition at line 270 of file lua-5.4.3/src/ldblib.c.
{
  return auxupvalue(L, 1);
}
References auxupvalue().
db_getuservalue()
static int db_getuservalue (lua_State * L) static
Definition at line 65 of file lua-5.4.3/src/ldblib.c.
{
  int n = (int)luaL_optinteger(L, 2, 1);
  if (lua_type(L, 1) != LUA_TUSERDATA)
    luaL_pushfail(L);
  else if (lua_getiuservalue(L, 1, n) != LUA_TNONE) {
    lua_pushboolean(L, 1);
    return 2;
  }
  return 1;
}
References lua_getiuservalue(), lua_pushboolean(), LUA_TNONE, LUA_TUSERDATA, lua_type(), luaL_optinteger(), and luaL_pushfail.
db_setcstacklimit()
static int db_setcstacklimit (lua_State * L) static
Definition at line 449 of file lua-5.4.3/src/ldblib.c.
{
  int limit = (int)luaL_checkinteger(L, 1);
  int res = lua_setcstacklimit(L, limit);
  lua_pushinteger(L, res);
  return 1;
}
References lua_pushinteger(), lua_setcstacklimit(), and luaL_checkinteger().
db_sethook()
static int db_sethook (lua_State * L) static
hooktable.__mode = "k"
Definition at line 365 of file lua-5.4.3/src/ldblib.c.
{
  int arg, mask, count;
  lua_Hook func;
  lua_State *L1 = getthread(L, &arg);
  if (lua_isnoneornil(L, arg+1)) {  /* no hook? */
    lua_settop(L, arg+1);
    func = NULL; mask = 0; count = 0;  /* turn off hooks */
  }
  else {
    const char *smask = luaL_checkstring(L, arg+2);
    luaL_checktype(L, arg+1, LUA_TFUNCTION);
    count = (int)luaL_optinteger(L, arg + 3, 0);
    func = hookf; mask = makemask(smask, count);
  }
  if (!luaL_getsubtable(L, LUA_REGISTRYINDEX, HOOKKEY)) {
    /* table just created; initialize it */
    lua_pushliteral(L, "k");
    lua_setfield(L, -2, "__mode");  /** hooktable.__mode = "k" */
    lua_pushvalue(L, -1);
    lua_setmetatable(L, -2);  /* metatable(hooktable) = hooktable */
  }
  checkstack(L, L1, 1);
  lua_pushthread(L1); lua_xmove(L1, L, 1);  /* key (thread) */
  lua_pushvalue(L, arg + 1);  /* value (hook function) */
  lua_rawset(L, -3);  /* hooktable[L1] = new Lua hook */
  lua_sethook(L1, func, mask, count);
  return 0;
}
References arg, checkstack(), getthread(), hookf(), HOOKKEY, lua_isnoneornil, lua_pushliteral, lua_pushthread(), lua_pushvalue(), lua_rawset(), LUA_REGISTRYINDEX, lua_setfield(), lua_sethook(), lua_setmetatable(), lua_settop(), LUA_TFUNCTION, lua_xmove(), luaL_checkstring, luaL_checktype(), luaL_getsubtable(), luaL_optinteger(), makemask(), mask, and NULL.
db_setlocal()
static int db_setlocal (lua_State * L) static
Definition at line 234 of file lua-5.4.3/src/ldblib.c.
{
  int arg;
  const char *name;
  lua_State *L1 = getthread(L, &arg);
  lua_Debug ar;
  int level = (int)luaL_checkinteger(L, arg + 1);
  int nvar = (int)luaL_checkinteger(L, arg + 2);
  if (l_unlikely(!lua_getstack(L1, level, &ar)))  /* out of range? */
    return luaL_argerror(L, arg+1, "level out of range");
  luaL_checkany(L, arg+3);
  lua_settop(L, arg+3);
  checkstack(L, L1, 1);
  lua_xmove(L, L1, 1);
  name = lua_setlocal(L1, &ar, nvar);
  if (name == NULL)
    lua_pop(L1, 1);  /* pop value (if not popped by 'lua_setlocal') */
  lua_pushstring(L, name);
  return 1;
}
References arg, checkstack(), getthread(), lua_getstack(), lua_pop, lua_pushstring(), lua_setlocal(), lua_settop(), lua_xmove(), luaL_argerror(), luaL_checkany(), luaL_checkinteger(), name, and NULL.
db_setmetatable()
static int db_setmetatable (lua_State * L) static
Definition at line 56 of file lua-5.4.3/src/ldblib.c.
{
  int t = lua_type(L, 2);
  luaL_argexpected(L, t == LUA_TNIL || t == LUA_TTABLE, 2, "nil or table");
  lua_settop(L, 2);
  lua_setmetatable(L, 1);
  return 1;  /* return 1st argument */
}
References lua_setmetatable(), lua_settop(), LUA_TNIL, LUA_TTABLE, lua_type(), and luaL_argexpected.
db_setupvalue()
static int db_setupvalue (lua_State * L) static
Definition at line 275 of file lua-5.4.3/src/ldblib.c.
{
  luaL_checkany(L, 3);
  return auxupvalue(L, 0);
}
References auxupvalue(), and luaL_checkany().
db_setuservalue()
static int db_setuservalue (lua_State * L) static
Definition at line 77 of file lua-5.4.3/src/ldblib.c.
{
  int n = (int)luaL_optinteger(L, 3, 1);
  luaL_checktype(L, 1, LUA_TUSERDATA);
  luaL_checkany(L, 2);
  lua_settop(L, 2);
  if (!lua_setiuservalue(L, 1, n))
    luaL_pushfail(L);
  return 1;
}
References lua_setiuservalue(), lua_settop(), LUA_TUSERDATA, luaL_checkany(), luaL_checktype(), luaL_optinteger(), and luaL_pushfail.
db_traceback()
static int db_traceback (lua_State * L) static
Definition at line 435 of file lua-5.4.3/src/ldblib.c.
{
  int arg;
  lua_State *L1 = getthread(L, &arg);
  const char *msg = lua_tostring(L, arg + 1);
  if (msg == NULL && !lua_isnoneornil(L, arg + 1))  /* non-string 'msg'? */
    lua_pushvalue(L, arg + 1);  /* return it untouched */
  else {
    int level = (int)luaL_optinteger(L, arg + 2, (L == L1) ? 1 : 0);
    luaL_traceback(L, L1, msg, level);
  }
  return 1;
}
References arg, getthread(), lua_isnoneornil, lua_pushvalue(), lua_tostring, luaL_optinteger(), luaL_traceback(), and NULL.
db_upvalueid()
static int db_upvalueid (lua_State * L) static
Definition at line 298 of file lua-5.4.3/src/ldblib.c.
{
  void *id = checkupval(L, 1, 2, NULL);
  if (id != NULL)
    lua_pushlightuserdata(L, id);
  else
    luaL_pushfail(L);
  return 1;
}
References checkupval(), lua_pushlightuserdata(), luaL_pushfail, and NULL.
db_upvaluejoin()
static int db_upvaluejoin (lua_State * L) static
Definition at line 308 of file lua-5.4.3/src/ldblib.c.
{
  int n1, n2;
  checkupval(L, 1, 2, &n1);
  checkupval(L, 3, 4, &n2);
  luaL_argcheck(L, !lua_iscfunction(L, 1), 1, "Lua function expected");
  luaL_argcheck(L, !lua_iscfunction(L, 3), 3, "Lua function expected");
  lua_upvaluejoin(L, 1, n1, 3, n2);
  return 0;
}
References checkupval(), lua_iscfunction(), lua_upvaluejoin(), and luaL_argcheck.
getthread()
static lua_State * getthread (lua_State * L, int * arg) static
Definition at line 94 of file lua-5.4.3/src/ldblib.c.
{
  if (lua_isthread(L, 1)) {
    *arg = 1;
    return lua_tothread(L, 1);
  }
  else {
    *arg = 0;
    return L;  /* function will operate over current thread */
  }
}
References arg, lua_isthread, and lua_tothread().
Referenced by db_gethook(), db_getinfo(), db_getlocal(), db_sethook(), db_setlocal(), and db_traceback().
hookf()
static void hookf (lua_State * L, lua_Debug * ar) static
Definition at line 323 of file lua-5.4.3/src/ldblib.c.
{
  static const char *const hooknames[] =
    {"call", "return", "line", "count", "tail call"};
  lua_getfield(L, LUA_REGISTRYINDEX, HOOKKEY);
  lua_pushthread(L);
  if (lua_rawget(L, -2) == LUA_TFUNCTION) {  /* is there a hook function? */
    lua_pushstring(L, hooknames[(int)ar->event]);  /* push event name */
    if (ar->currentline >= 0)
      lua_pushinteger(L, ar->currentline);  /* push current line */
    else lua_pushnil(L);
    lua_assert(lua_getinfo(L, "lS", ar));
    lua_call(L, 2, 0);  /* call hook function */
  }
}
References lua_Debug::currentline, lua_Debug::event, HOOKKEY, lua_assert, lua_call, lua_getfield(), lua_getinfo(), lua_pushinteger(), lua_pushnil(), lua_pushstring(), lua_pushthread(), lua_rawget(), LUA_REGISTRYINDEX, and LUA_TFUNCTION.
Referenced by db_gethook(), and db_sethook().
luaopen_debug()
LUAMOD_API int luaopen_debug (lua_State * L)
Definition at line 479 of file lua-5.4.3/src/ldblib.c.
{
  luaL_newlib(L, dblib);
  return 1;
}
References dblib, and luaL_newlib.
makemask()
static int makemask (const char * smask, int count) static
Definition at line 342 of file lua-5.4.3/src/ldblib.c.
{
  int mask = 0;
  if (strchr(smask, 'c')) mask |= LUA_MASKCALL;
  if (strchr(smask, 'r')) mask |= LUA_MASKRET;
  if (strchr(smask, 'l')) mask |= LUA_MASKLINE;
  if (count > 0) mask |= LUA_MASKCOUNT;
  return mask;
}
References LUA_MASKCALL, LUA_MASKCOUNT, LUA_MASKLINE, LUA_MASKRET, and mask.
Referenced by db_sethook().
settabsb()
static void settabsb (lua_State * L, const char * k, int v) static
Definition at line 121 of file lua-5.4.3/src/ldblib.c.
{
  lua_pushboolean(L, v);
  lua_setfield(L, -2, k);
}
References lua_pushboolean(), and lua_setfield().
Referenced by db_getinfo().
settabsi()
static void settabsi (lua_State * L, const char * k, int v) static
Definition at line 116 of file lua-5.4.3/src/ldblib.c.
{
  lua_pushinteger(L, v);
  lua_setfield(L, -2, k);
}
References lua_pushinteger(), and lua_setfield().
Referenced by db_getinfo().
settabss()
static void settabss (lua_State * L, const char * k, const char * v) static
Definition at line 111 of file lua-5.4.3/src/ldblib.c.
{
  lua_pushstring(L, v);
  lua_setfield(L, -2, k);
}
References lua_pushstring(), and lua_setfield().
Referenced by db_getinfo().
treatstackoption()
static void treatstackoption (lua_State * L, lua_State * L1, const char * fname) static
Definition at line 134 of file lua-5.4.3/src/ldblib.c.
{
  if (L == L1)
    lua_rotate(L, -2, 1);  /* exchange object and table */
  else
    lua_xmove(L1, L, 1);  /* move object to the "main" stack */
  lua_setfield(L, -2, fname);  /* put object into table */
}
References lua_rotate(), lua_setfield(), and lua_xmove().
Referenced by db_getinfo().
unmakemask()
static char * unmakemask (int mask, char * smask) static
Definition at line 355 of file lua-5.4.3/src/ldblib.c.
{
  int i = 0;
  if (mask & LUA_MASKCALL) smask[i++] = 'c';
  if (mask & LUA_MASKRET) smask[i++] = 'r';
  if (mask & LUA_MASKLINE) smask[i++] = 'l';
  smask[i] = '\0';
  return smask;
}
References LUA_MASKCALL, LUA_MASKLINE, LUA_MASKRET, and mask.
Referenced by db_gethook().
Variable Documentation
dblib
const luaL_Reg dblib[] static
Initial value:
= {
  {"debug", db_debug},
  {"getuservalue", db_getuservalue},
  {"gethook", db_gethook},
  {"getinfo", db_getinfo},
  {"getlocal", db_getlocal},
  {"getregistry", db_getregistry},
  {"getmetatable", db_getmetatable},
  {"getupvalue", db_getupvalue},
  {"upvaluejoin", db_upvaluejoin},
  {"upvalueid", db_upvalueid},
  {"setuservalue", db_setuservalue},
  {"sethook", db_sethook},
  {"setlocal", db_setlocal},
  {"setmetatable", db_setmetatable},
  {"setupvalue", db_setupvalue},
  {"traceback", db_traceback},
  {"setcstacklimit", db_setcstacklimit},
  {NULL, NULL}
}
Definition at line 457 of file lua-5.4.3/src/ldblib.c.
{
  {"debug", db_debug},
  {"getuservalue", db_getuservalue},
  {"gethook", db_gethook},
  {"getinfo", db_getinfo},
  {"getlocal", db_getlocal},
  {"getregistry", db_getregistry},
  {"getmetatable", db_getmetatable},
  {"getupvalue", db_getupvalue},
  {"upvaluejoin", db_upvaluejoin},
  {"upvalueid", db_upvalueid},
  {"setuservalue", db_setuservalue},
  {"sethook", db_sethook},
  {"setlocal", db_setlocal},
  {"setmetatable", db_setmetatable},
  {"setupvalue", db_setupvalue},
  {"traceback", db_traceback},
  {"setcstacklimit", db_setcstacklimit},
  {NULL, NULL}
};
Referenced by luaopen_debug().
HOOKKEY
const char* const HOOKKEY = "_HOOKKEY" static
Definition at line 27 of file lua-5.4.3/src/ldblib.c.
Referenced by db_gethook(), db_sethook(), and hookf().