Github User Fetcher: lstate.c File Reference
lstate.c File Reference
#include <stddef.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "llex.h"
#include "lmem.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
Data Structures
struct LG
Macros
#define lstate_c
#define LUA_CORE
#define state_size(x) (sizeof(x) + LUAI_EXTRASPACE)
#define fromstate(l) (cast(lu_byte *, (l)) - LUAI_EXTRASPACE)
#define tostate(l) (cast(lua_State *, cast(lu_byte *, l) + LUAI_EXTRASPACE))
Typedefs
typedef struct LG LG
Functions
static void stack_init (lua_State *L1, lua_State *L)
static void freestack (lua_State *L, lua_State *L1)
static void f_luaopen (lua_State *L, void *ud)
static void preinit_state (lua_State *L, global_State *g)
static void close_state (lua_State *L)
lua_State * luaE_newthread (lua_State *L)
void luaE_freethread (lua_State *L, lua_State *L1)
LUA_API lua_State * lua_newstate (lua_Alloc f, void *ud)
static void callallgcTM (lua_State *L, void *ud)
LUA_API void lua_close (lua_State *L)
Macro Definition Documentation
fromstate
#define fromstate (l) (cast(lu_byte *, (l)) - LUAI_EXTRASPACE)
Definition at line 28 of file lua-5.1.5/src/lstate.c.
Referenced by close_state(), and luaE_freethread().
lstate_c
#define lstate_c
Definition at line 10 of file lua-5.1.5/src/lstate.c.
LUA_CORE
#define LUA_CORE
Definition at line 11 of file lua-5.1.5/src/lstate.c.
state_size
#define state_size (x) (sizeof(x) + LUAI_EXTRASPACE)
Definition at line 27 of file lua-5.1.5/src/lstate.c.
Referenced by close_state(), lua_newstate(), luaE_freethread(), and luaE_newthread().
tostate
#define tostate (l) (cast(lua_State *, cast(lu_byte *, l) + LUAI_EXTRASPACE))
Definition at line 29 of file lua-5.1.5/src/lstate.c.
Referenced by lua_newstate(), and luaE_newthread().
Typedef Documentation
LG
typedef struct LG LG
Function Documentation
callallgcTM()
static void callallgcTM (lua_State * L, void * ud) static
Definition at line 193 of file lua-5.1.5/src/lstate.c.
{
  UNUSED(ud);
  luaC_callGCTM(L);  /* call GC metamethods for all udata */
}
References luaC_callGCTM(), and UNUSED.
Referenced by lua_close().
close_state()
static void close_state (lua_State * L) static
Definition at line 105 of file lua-5.1.5/src/lstate.c.
{
  global_State *g = G(L);
  luaF_close(L, L->stack);  /* close all upvalues for this thread */
  luaC_freeall(L);  /* collect all objects */
  lua_assert(g->rootgc == obj2gco(L));
  lua_assert(g->strt.nuse == 0);
  luaM_freearray(L, G(L)->strt.hash, G(L)->strt.size, TString *);
  luaZ_freebuffer(L, &g->buff);
  freestack(L, L);
  lua_assert(g->totalbytes == sizeof(LG));
  (*g->frealloc)(g->ud, fromstate(L), state_size(LG), 0);
}
References global_State::buff, global_State::frealloc, freestack(), fromstate, G, lua_assert, luaC_freeall(), luaF_close(), luaM_freearray, luaZ_freebuffer, stringtable::nuse, obj2gco, global_State::rootgc, lua_State::stack, state_size, global_State::strt, global_State::totalbytes, and global_State::ud.
Referenced by lua_close(), and lua_newstate().
f_luaopen()
static void f_luaopen (lua_State * L, void * ud) static
Definition at line 70 of file lua-5.1.5/src/lstate.c.
{
  global_State *g = G(L);
  UNUSED(ud);
  stack_init(L, L);  /* init stack */
  sethvalue(L, gt(L), luaH_new(L, 0, 2));  /* table of globals */
  sethvalue(L, registry(L), luaH_new(L, 0, 2));  /* registry */
  luaS_resize(L, MINSTRTABSIZE);  /* initial size of string table */
  luaT_init(L);
  luaX_init(L);
  luaS_fix(luaS_newliteral(L, MEMERRMSG));
  g->GCthreshold = 4*g->totalbytes;
}
References G, global_State::GCthreshold, gt, luaH_new(), luaS_fix, luaS_newliteral, luaS_resize(), luaT_init(), luaX_init(), MEMERRMSG, MINSTRTABSIZE, registry, sethvalue, stack_init(), global_State::totalbytes, and UNUSED.
Referenced by lua_newstate().
freestack()
static void freestack (lua_State * L, lua_State * L1) static
Definition at line 61 of file lua-5.1.5/src/lstate.c.
{
  luaM_freearray(L, L1->base_ci, L1->size_ci, CallInfo);
  luaM_freearray(L, L1->stack, L1->stacksize, TValue);
}
References lua_State::base_ci, luaM_freearray, lua_State::size_ci, lua_State::stack, and lua_State::stacksize.
Referenced by close_state(), and luaE_freethread().
lua_close()
LUA_API void lua_close (lua_State * L)
Definition at line 199 of file lua-5.1.5/src/lstate.c.
{
  L = G(L)->mainthread;  /* only the main thread can be closed */
  lua_lock(L);
  luaF_close(L, L->stack);  /* close all upvalues for this thread */
  luaC_separateudata(L, 1);  /* separate udata that have GC metamethods */
  L->errfunc = 0;  /* no error function during GC metamethods */
  do {  /* repeat until no more errors */
    L->ci = L->base_ci;
    L->base = L->top = L->ci->base;
    L->nCcalls = L->baseCcalls = 0;
  } while (luaD_rawrunprotected(L, callallgcTM, NULL) != 0);
  lua_assert(G(L)->tmudata == NULL);
  luai_userstateclose(L);
  close_state(L);
}
References CallInfo::base, lua_State::base, lua_State::base_ci, lua_State::baseCcalls, callallgcTM(), lua_State::ci, close_state(), lua_State::errfunc, G, lua_assert, lua_lock, luaC_separateudata(), luaD_rawrunprotected(), luaF_close(), luai_userstateclose, lua_State::nCcalls, NULL, lua_State::stack, and lua_State::top.
Referenced by main(), main(), main(), master_thread_run(), os_exit(), os_exit(), and os_exit().
lua_newstate()
LUA_API lua_State * lua_newstate (lua_Alloc f, void * ud)
Definition at line 143 of file lua-5.1.5/src/lstate.c.
{
  int i;
  lua_State *L;
  global_State *g;
  void *l = (*f)(ud, NULL, 0, state_size(LG));
  if (l == NULL) return NULL;
  L = tostate(l);
  g = &((LG *)L)->g;
  L->next = NULL;
  L->tt = LUA_TTHREAD;
  g->currentwhite = bit2mask(WHITE0BIT, FIXEDBIT);
  L->marked = luaC_white(g);
  set2bits(L->marked, FIXEDBIT, SFIXEDBIT);
  preinit_state(L, g);
  g->frealloc = f;
  g->ud = ud;
  g->mainthread = L;
  g->uvhead.u.l.prev = &g->uvhead;
  g->uvhead.u.l.next = &g->uvhead;
  g->GCthreshold = 0;  /* mark it as unfinished state */
  g->strt.size = 0;
  g->strt.nuse = 0;
  g->strt.hash = NULL;
  setnilvalue(registry(L));
  luaZ_initbuffer(L, &g->buff);
  g->panic = NULL;
  g->gcstate = GCSpause;
  g->rootgc = obj2gco(L);
  g->sweepstrgc = 0;
  g->sweepgc = &g->rootgc;
  g->gray = NULL;
  g->grayagain = NULL;
  g->weak = NULL;
  g->tmudata = NULL;
  g->totalbytes = sizeof(LG);
  g->gcpause = LUAI_GCPAUSE;
  g->gcstepmul = LUAI_GCMUL;
  g->gcdept = 0;
  for (i=0; i<NUM_TAGS; i++) g->mt[i] = NULL;
  if (luaD_rawrunprotected(L, f_luaopen, NULL) != 0) {
    /* memory allocation error: free partial state */
    close_state(L);
    L = NULL;
  }
  else
    luai_userstateopen(L);
  return L;
}
References bit2mask, global_State::buff, close_state(), global_State::currentwhite, f_luaopen(), FIXEDBIT, global_State::frealloc, global_State::gcdept, global_State::gcpause, GCSpause, global_State::gcstate, global_State::gcstepmul, global_State::GCthreshold, global_State::gray, global_State::grayagain, stringtable::hash, UpVal::l, LUA_TTHREAD, luaC_white, luaD_rawrunprotected(), LUAI_GCMUL, LUAI_GCPAUSE, luai_userstateopen, luaZ_initbuffer, global_State::mainthread, global_State::mt, UpVal::next, NULL, NUM_TAGS, stringtable::nuse, obj2gco, global_State::panic, preinit_state(), UpVal::prev, registry, global_State::rootgc, set2bits, setnilvalue, SFIXEDBIT, stringtable::size, state_size, global_State::strt, global_State::sweepgc, global_State::sweepstrgc, global_State::tmudata, tostate, global_State::totalbytes, UpVal::u, global_State::ud, global_State::uvhead, global_State::weak, and WHITE0BIT.
Referenced by luaL_newstate().
luaE_freethread()
void luaE_freethread (lua_State * L, lua_State * L1)
Definition at line 134 of file lua-5.1.5/src/lstate.c.
{
  luaF_close(L1, L1->stack);  /* close all upvalues for this thread */
  lua_assert(L1->openupval == NULL);
  luai_userstatefree(L1);
  freestack(L, L1);
  luaM_freemem(L, fromstate(L1), state_size(lua_State));
}
References freestack(), fromstate, lua_assert, luaF_close(), luai_userstatefree, luaM_freemem, NULL, lua_State::openupval, lua_State::stack, and state_size.
Referenced by freeobj(), freeobj(), freeobj(), and freeobj().
luaE_newthread()
lua_State * luaE_newthread (lua_State * L)
Definition at line 119 of file lua-5.1.5/src/lstate.c.
{
  lua_State *L1 = tostate(luaM_malloc(L, state_size(lua_State)));
  luaC_link(L, obj2gco(L1), LUA_TTHREAD);
  preinit_state(L1, G(L));
  stack_init(L1, L);  /* init stack */
  setobj2n(L, gt(L1), gt(L));  /* share table of globals */
  L1->hookmask = L->hookmask;
  L1->basehookcount = L->basehookcount;
  L1->hook = L->hook;
  resethookcount(L1);
  lua_assert(iswhite(obj2gco(L1)));
  return L1;
}
References lua_State::basehookcount, G, gt, lua_State::hook, lua_State::hookmask, iswhite, lua_assert, LUA_TTHREAD, luaC_link(), luaM_malloc, obj2gco, preinit_state(), resethookcount, setobj2n, stack_init(), state_size, and tostate.
Referenced by lua_newthread().
preinit_state()
static void preinit_state (lua_State * L, global_State * g) static
Definition at line 84 of file lua-5.1.5/src/lstate.c.
{
  G(L) = g;
  L->stack = NULL;
  L->stacksize = 0;
  L->errorJmp = NULL;
  L->hook = NULL;
  L->hookmask = 0;
  L->basehookcount = 0;
  L->allowhook = 1;
  resethookcount(L);
  L->openupval = NULL;
  L->size_ci = 0;
  L->nCcalls = L->baseCcalls = 0;
  L->status = 0;
  L->base_ci = L->ci = NULL;
  L->savedpc = NULL;
  L->errfunc = 0;
  setnilvalue(gt(L));
}
References lua_State::allowhook, lua_State::base_ci, lua_State::baseCcalls, lua_State::basehookcount, lua_State::ci, lua_State::errfunc, lua_State::errorJmp, G, gt, lua_State::hook, lua_State::hookmask, lua_State::nCcalls, NULL, lua_State::openupval, resethookcount, lua_State::savedpc, setnilvalue, lua_State::size_ci, lua_State::stack, lua_State::stacksize, and lua_State::status.
Referenced by lua_newstate(), and luaE_newthread().
stack_init()
static void stack_init (lua_State * L1, lua_State * L) static
Definition at line 42 of file lua-5.1.5/src/lstate.c.
{
  /* initialize CallInfo array */
  L1->base_ci = luaM_newvector(L, BASIC_CI_SIZE, CallInfo);
  L1->ci = L1->base_ci;
  L1->size_ci = BASIC_CI_SIZE;
  L1->end_ci = L1->base_ci + L1->size_ci - 1;
  /* initialize stack array */
  L1->stack = luaM_newvector(L, BASIC_STACK_SIZE + EXTRA_STACK, TValue);
  L1->stacksize = BASIC_STACK_SIZE + EXTRA_STACK;
  L1->top = L1->stack;
  L1->stack_last = L1->stack+(L1->stacksize - EXTRA_STACK)-1;
  /* initialize first ci */
  L1->ci->func = L1->top;
  setnilvalue(L1->top++);  /* `function' entry for this `ci' */
  L1->base = L1->ci->base = L1->top;
  L1->ci->top = L1->top + LUA_MINSTACK;
}
References CallInfo::base, lua_State::base, lua_State::base_ci, BASIC_CI_SIZE, BASIC_STACK_SIZE, lua_State::ci, lua_State::end_ci, EXTRA_STACK, CallInfo::func, LUA_MINSTACK, luaM_newvector, setnilvalue, lua_State::size_ci, lua_State::stack, lua_State::stack_last, lua_State::stacksize, CallInfo::top, and lua_State::top.
Referenced by f_luaopen(), and luaE_newthread().