Github User Fetcher: lapi.c File Reference
lapi.c File Reference
#include <assert.h>
#include <math.h>
#include <stdarg.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lundump.h"
#include "lvm.h"
Data Structures
struct CallS
struct CCallS
Macros
#define lapi_c
#define LUA_CORE
#define api_checknelems(L, n) api_check(L, (n) <= (L->top - L->base))
#define api_checkvalidindex(L, i) api_check(L, (i) != luaO_nilobject)
#define api_incr_top(L) {api_check(L, L->top < L->ci->top); L->top++;}
#define adjustresults(L, nres) { if (nres == LUA_MULTRET && L->top >= L->ci->top) L->ci->top = L->top; }
#define checkresults(L, na, nr) api_check(L, (nr) == LUA_MULTRET || (L->ci->top - L->top >= (nr) - (na)))
Functions
static TValue * index2adr (lua_State *L, int idx)
static Table * getcurrenv (lua_State *L)
void luaA_pushobject (lua_State *L, const TValue *o)
LUA_API int lua_checkstack (lua_State *L, int size)
LUA_API void lua_xmove (lua_State *from, lua_State *to, int n)
LUA_API void lua_setlevel (lua_State *from, lua_State *to)
LUA_API lua_CFunction lua_atpanic (lua_State *L, lua_CFunction panicf)
LUA_API lua_State * lua_newthread (lua_State *L)
LUA_API int lua_gettop (lua_State *L)
LUA_API void lua_settop (lua_State *L, int idx)
LUA_API void lua_remove (lua_State *L, int idx)
LUA_API void lua_insert (lua_State *L, int idx)
LUA_API void lua_replace (lua_State *L, int idx)
LUA_API void lua_pushvalue (lua_State *L, int idx)
LUA_API int lua_type (lua_State *L, int idx)
LUA_API const char * lua_typename (lua_State *L, int t)
LUA_API int lua_iscfunction (lua_State *L, int idx)
LUA_API int lua_isnumber (lua_State *L, int idx)
LUA_API int lua_isstring (lua_State *L, int idx)
LUA_API int lua_isuserdata (lua_State *L, int idx)
LUA_API int lua_rawequal (lua_State *L, int index1, int index2)
LUA_API int lua_equal (lua_State *L, int index1, int index2)
LUA_API int lua_lessthan (lua_State *L, int index1, int index2)
LUA_API lua_Number lua_tonumber (lua_State *L, int idx)
LUA_API lua_Integer lua_tointeger (lua_State *L, int idx)
LUA_API int lua_toboolean (lua_State *L, int idx)
LUA_API const char * lua_tolstring (lua_State *L, int idx, size_t *len)
LUA_API size_t lua_objlen (lua_State *L, int idx)
LUA_API lua_CFunction lua_tocfunction (lua_State *L, int idx)
LUA_API void * lua_touserdata (lua_State *L, int idx)
LUA_API lua_State * lua_tothread (lua_State *L, int idx)
LUA_API const void * lua_topointer (lua_State *L, int idx)
LUA_API void lua_pushnil (lua_State *L)
LUA_API void lua_pushnumber (lua_State *L, lua_Number n)
LUA_API void lua_pushinteger (lua_State *L, lua_Integer n)
LUA_API void lua_pushlstring (lua_State *L, const char *s, size_t len)
LUA_API void lua_pushstring (lua_State *L, const char *s)
LUA_API const char * lua_pushvfstring (lua_State *L, const char *fmt, va_list argp)
LUA_API const char * lua_pushfstring (lua_State *L, const char *fmt,...)
LUA_API void lua_pushcclosure (lua_State *L, lua_CFunction fn, int n)
LUA_API void lua_pushboolean (lua_State *L, int b)
LUA_API void lua_pushlightuserdata (lua_State *L, void *p)
LUA_API int lua_pushthread (lua_State *L)
LUA_API void lua_gettable (lua_State *L, int idx)
LUA_API void lua_getfield (lua_State *L, int idx, const char *k)
LUA_API void lua_rawget (lua_State *L, int idx)
LUA_API void lua_rawgeti (lua_State *L, int idx, int n)
LUA_API void lua_createtable (lua_State *L, int narray, int nrec)
LUA_API int lua_getmetatable (lua_State *L, int objindex)
LUA_API void lua_getfenv (lua_State *L, int idx)
LUA_API void lua_settable (lua_State *L, int idx)
LUA_API void lua_setfield (lua_State *L, int idx, const char *k)
LUA_API void lua_rawset (lua_State *L, int idx)
LUA_API void lua_rawseti (lua_State *L, int idx, int n)
LUA_API int lua_setmetatable (lua_State *L, int objindex)
LUA_API int lua_setfenv (lua_State *L, int idx)
LUA_API void lua_call (lua_State *L, int nargs, int nresults)
static void f_call (lua_State *L, void *ud)
LUA_API int lua_pcall (lua_State *L, int nargs, int nresults, int errfunc)
static void f_Ccall (lua_State *L, void *ud)
LUA_API int lua_cpcall (lua_State *L, lua_CFunction func, void *ud)
LUA_API int lua_load (lua_State *L, lua_Reader reader, void *data, const char *chunkname)
LUA_API int lua_dump (lua_State *L, lua_Writer writer, void *data)
LUA_API int lua_status (lua_State *L)
LUA_API int lua_gc (lua_State *L, int what, int data)
LUA_API int lua_error (lua_State *L)
LUA_API int lua_next (lua_State *L, int idx)
LUA_API void lua_concat (lua_State *L, int n)
LUA_API lua_Alloc lua_getallocf (lua_State *L, void **ud)
LUA_API void lua_setallocf (lua_State *L, lua_Alloc f, void *ud)
LUA_API void * lua_newuserdata (lua_State *L, size_t size)
static const char * aux_upvalue (StkId fi, int n, TValue **val)
LUA_API const char * lua_getupvalue (lua_State *L, int funcindex, int n)
LUA_API const char * lua_setupvalue (lua_State *L, int funcindex, int n)
Variables
const char lua_ident []
Macro Definition Documentation
adjustresults
#define adjustresults (L, nres) { if (nres == LUA_MULTRET && L->top >= L->ci->top) L->ci->top = L->top; }
Definition at line 768 of file lua-5.1.5/src/lapi.c.
#define adjustresults(L,nres) \
    { if (nres == LUA_MULTRET && L->top >= L->ci->top) L->ci->top = L->top; }
Referenced by finishCcall(), finishCcall(), finishCcall(), lua_call(), lua_callk(), lua_callk(), lua_pcall(), lua_pcallk(), and lua_pcallk().
api_checknelems
#define api_checknelems (L, n) api_check(L, (n) <= (L->top - L->base))
Definition at line 41 of file lua-5.1.5/src/lapi.c.
Referenced by aux_rawset(), auxsetstr(), auxsetstr(), finishCcall(), finishCcall(), finishCcall(), lua_arith(), lua_call(), lua_callk(), lua_callk(), lua_concat(), lua_dump(), lua_dump(), lua_error(), lua_next(), lua_pcall(), lua_pcallk(), lua_pcallk(), lua_pushcclosure(), lua_rawget(), lua_rawset(), lua_rawseti(), lua_rawseti(), lua_rawsetp(), lua_replace(), lua_resume(), lua_resume(), lua_setfenv(), lua_setfield(), lua_setglobal(), lua_seti(), lua_setiuservalue(), lua_setmetatable(), lua_settable(), lua_setupvalue(), lua_setuservalue(), lua_xmove(), lua_yieldk(), lua_yieldk(), luaD_precall(), resume(), resume(), and resume().
api_checkvalidindex
#define api_checkvalidindex (L, i) api_check(L, (i) != luaO_nilobject)
Definition at line 43 of file lua-5.1.5/src/lapi.c.
Referenced by lua_getfenv(), lua_getfield(), lua_gettable(), lua_insert(), lua_pcall(), lua_remove(), lua_replace(), lua_setfenv(), lua_setfield(), lua_setmetatable(), and lua_settable().
api_incr_top
#define api_incr_top (L) {api_check(L, L->top < L->ci->top); L->top++;}
Definition at line 45 of file lua-5.1.5/src/lapi.c.
Referenced by auxgetstr(), auxgetstr(), auxsetstr(), auxsetstr(), collectvalidlines(), collectvalidlines(), collectvalidlines(), f_Ccall(), finishrawget(), lua_arith(), lua_concat(), lua_createtable(), lua_getfenv(), lua_getfield(), lua_geti(), lua_getinfo(), lua_getiuservalue(), lua_getlocal(), lua_getmetatable(), lua_getupvalue(), lua_getuservalue(), lua_len(), lua_newthread(), lua_newuserdata(), lua_newuserdatauv(), lua_next(), lua_pushboolean(), lua_pushcclosure(), lua_pushinteger(), lua_pushlightuserdata(), lua_pushlstring(), lua_pushnil(), lua_pushnumber(), lua_pushstring(), lua_pushthread(), lua_pushunsigned(), lua_pushvalue(), lua_rawgeti(), lua_rawgeti(), lua_rawgetp(), lua_seti(), lua_stringtonumber(), luaA_pushobject(), resume_error(), resume_error(), and resume_error().
checkresults
#define checkresults (L, na, nr) api_check(L, (nr) == LUA_MULTRET || (L->ci->top - L->top >= (nr) - (na)))
Definition at line 772 of file lua-5.1.5/src/lapi.c.
#define checkresults(L,na,nr) \
     api_check(L, (nr) == LUA_MULTRET || (L->ci->top - L->top >= (nr) - (na)))
Referenced by lua_call(), and lua_pcall().
lapi_c
#define lapi_c
Definition at line 13 of file lua-5.1.5/src/lapi.c.
LUA_CORE
#define LUA_CORE
Definition at line 14 of file lua-5.1.5/src/lapi.c.
Function Documentation
aux_upvalue()
static const char * aux_upvalue (StkId fi, int n, TValue ** val) static
Definition at line 1039 of file lua-5.1.5/src/lapi.c.
{
  Closure *f;
  if (!ttisfunction(fi)) return NULL;
  f = clvalue(fi);
  if (f->c.isC) {
    if (!(1 <= n && n <= f->c.nupvalues)) return NULL;
    *val = &f->c.upvalue[n-1];
    return "";
  }
  else {
    Proto *p = f->l.p;
    if (!(1 <= n && n <= p->sizeupvalues)) return NULL;
    *val = f->l.upvals[n-1]->v;
    return getstr(p->upvalues[n-1]);
  }
}
References Closure::c, clvalue, getstr, Closure::l, NULL, LClosure::p, ttisfunction, LClosure::upvals, CClosure::upvalue, Proto::upvalues, and UpVal::v.
Referenced by lua_getupvalue(), and lua_setupvalue().
f_call()
static void f_call (lua_State * L, void * ud) static
Definition at line 798 of file lua-5.1.5/src/lapi.c.
{
  struct CallS *c = cast(struct CallS *, ud);
  luaD_call(L, c->func, c->nresults);
}
References cast, CallS::func, luaD_call(), and CallS::nresults.
Referenced by lua_pcall().
f_Ccall()
static void f_Ccall (lua_State * L, void * ud) static
Definition at line 837 of file lua-5.1.5/src/lapi.c.
{
  struct CCallS *c = cast(struct CCallS *, ud);
  Closure *cl;
  cl = luaF_newCclosure(L, 0, getcurrenv(L));
  cl->c.f = c->func;
  setclvalue(L, L->top, cl);  /* push function */
  api_incr_top(L);
  setpvalue(L->top, c->ud);  /* push only argument */
  api_incr_top(L);
  luaD_call(L, L->top - 2, 0);
}
References api_incr_top, Closure::c, cast, CClosure::f, CCallS::func, getcurrenv(), luaD_call(), luaF_newCclosure(), setclvalue, setpvalue, lua_State::top, and CCallS::ud.
Referenced by lua_cpcall().
getcurrenv()
static Table * getcurrenv (lua_State * L) static
Definition at line 79 of file lua-5.1.5/src/lapi.c.
{
  if (L->ci == L->base_ci)  /* no enclosing function? */
    return hvalue(gt(L));  /* use global table as environment */
  else {
    Closure *func = curr_func(L);
    return func->c.env;
  }
}
References lua_State::base_ci, Closure::c, lua_State::ci, curr_func, gt, and hvalue.
Referenced by f_Ccall(), lua_newuserdata(), and lua_pushcclosure().
index2adr()
static TValue * index2adr (lua_State * L, int idx) static
Definition at line 49 of file lua-5.1.5/src/lapi.c.
{
  if (idx > 0) {
    TValue *o = L->base + (idx - 1);
    api_check(L, idx <= L->ci->top - L->base);
    if (o >= L->top) return cast(TValue *, luaO_nilobject);
    else return o;
  }
  else if (idx > LUA_REGISTRYINDEX) {
    api_check(L, idx != 0 && -idx <= L->top - L->base);
    return L->top + idx;
  }
  else switch (idx) {  /* pseudo-indices */
    case LUA_REGISTRYINDEX: return registry(L);
    case LUA_ENVIRONINDEX: {
      Closure *func = curr_func(L);
      sethvalue(L, &L->env, func->c.env);
      return &L->env;
    }
    case LUA_GLOBALSINDEX: return gt(L);
    default: {
      Closure *func = curr_func(L);
      idx = LUA_GLOBALSINDEX - idx;
      return (idx <= func->c.nupvalues)
                ? &func->c.upvalue[idx-1]
                : cast(TValue *, luaO_nilobject);
    }
  }
}
References api_check, lua_State::base, Closure::c, cast, curr_func, lua_State::env, gt, LUA_ENVIRONINDEX, LUA_GLOBALSINDEX, LUA_REGISTRYINDEX, luaO_nilobject, registry, sethvalue, lua_State::top, and CClosure::upvalue.
Referenced by lua_equal(), lua_getfenv(), lua_getfield(), lua_getmetatable(), lua_gettable(), lua_getupvalue(), lua_insert(), lua_iscfunction(), lua_isnumber(), lua_isuserdata(), lua_lessthan(), lua_next(), lua_objlen(), lua_pcall(), lua_pushvalue(), lua_rawequal(), lua_rawget(), lua_rawgeti(), lua_rawset(), lua_rawseti(), lua_remove(), lua_replace(), lua_setfenv(), lua_setfield(), lua_setmetatable(), lua_settable(), lua_setupvalue(), lua_toboolean(), lua_tocfunction(), lua_tointeger(), lua_tolstring(), lua_tonumber(), lua_topointer(), lua_tothread(), lua_touserdata(), and lua_type().
lua_atpanic()
LUA_API lua_CFunction lua_atpanic (lua_State * L, lua_CFunction panicf)
Definition at line 130 of file lua-5.1.5/src/lapi.c.
{
  lua_CFunction old;
  lua_lock(L);
  old = G(L)->panic;
  G(L)->panic = panicf;
  lua_unlock(L);
  return old;
}
References G, lua_lock, and lua_unlock.
Referenced by luaL_newstate().
lua_call()
LUA_API void lua_call (lua_State * L, int nargs, int nresults)
Definition at line 776 of file lua-5.1.5/src/lapi.c.
{
  StkId func;
  lua_lock(L);
  api_checknelems(L, nargs+1);
  checkresults(L, nargs, nresults);
  func = L->top - (nargs+1);
  luaD_call(L, func, nresults);
  adjustresults(L, nresults);
  lua_unlock(L);
}
References adjustresults, api_checknelems, checkresults, lua_lock, lua_unlock, luaD_call(), and lua_State::top.
lua_checkstack()
LUA_API int lua_checkstack (lua_State * L, int size)
Definition at line 95 of file lua-5.1.5/src/lapi.c.
{
  int res = 1;
  lua_lock(L);
  if (size > LUAI_MAXCSTACK || (L->top - L->base + size) > LUAI_MAXCSTACK)
    res = 0;  /* stack overflow */
  else if (size > 0) {
    luaD_checkstack(L, size);
    if (L->ci->top < L->top + size)
      L->ci->top = L->top + size;
  }
  lua_unlock(L);
  return res;
}
References lua_State::base, lua_State::ci, lua_lock, lua_unlock, luaD_checkstack, LUAI_MAXCSTACK, CallInfo::top, and lua_State::top.
Referenced by auxresume(), auxresume(), auxresume(), auxresume(), checkstack(), checkstack(), checkstack(), db_do_next_row(), db_sql_normal_function(), dbvm_get_unames(), dbvm_get_utypes(), dbvm_get_uvalues(), finishpcall(), luaB_unpack(), luaL_checkstack(), luaL_checkstack(), pmain(), pmain(), pmain(), pmain(), tunpack(), unpack(), and unpack().
lua_concat()
LUA_API void lua_concat (lua_State * L, int n)
Definition at line 990 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  api_checknelems(L, n);
  if (n >= 2) {
    luaC_checkGC(L);
    luaV_concat(L, n, cast_int(L->top - L->base) - 1);
    L->top -= (n-1);
  }
  else if (n == 0) {  /* push empty string */
    setsvalue2s(L, L->top, luaS_newlstr(L, "", 0));
    api_incr_top(L);
  }
  /* else n == 1; nothing to do */
  lua_unlock(L);
}
References api_checknelems, api_incr_top, lua_State::base, cast_int, lua_lock, lua_unlock, luaC_checkGC, luaS_newlstr(), luaV_concat(), setsvalue2s, and lua_State::top.
Referenced by adjuststack(), db_errorfb(), findfield(), findfield(), findfield(), findfile(), ll_require(), loadline(), loadline(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_error(), luaB_error(), luaB_error(), luaB_error(), luaL_error(), luaL_pushresult(), luaL_traceback(), multiline(), multiline(), and Xml_str().
lua_cpcall()
LUA_API int lua_cpcall (lua_State * L, lua_CFunction func, void * ud)
Definition at line 850 of file lua-5.1.5/src/lapi.c.
{
  struct CCallS c;
  int status;
  lua_lock(L);
  c.func = func;
  c.ud = ud;
  status = luaD_pcall(L, f_Ccall, &c, savestack(L, L->top), 0);
  lua_unlock(L);
  return status;
}
References f_Ccall(), CCallS::func, lua_lock, lua_unlock, luaD_pcall(), savestack, lua_State::top, and CCallS::ud.
Referenced by main(), and main().
lua_createtable()
LUA_API void lua_createtable (lua_State * L, int narray, int nrec)
Definition at line 578 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  luaC_checkGC(L);
  sethvalue(L, L->top, luaH_new(L, narray, nrec));
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaH_new(), sethvalue, and lua_State::top.
Referenced by base_open(), createargtable(), createargtable(), createclibstable(), createclibstable(), createmetatable(), createmetatable(), createmetatable(), createsearcherstable(), createsearcherstable(), createsearcherstable(), db_do_next_row(), db_exec_callback(), db_getinfo(), db_getinfo(), db_sethook(), dbvm_get_named_types(), dbvm_get_named_values(), dbvm_get_names(), dbvm_get_types(), dbvm_get_values(), getargs(), getargs(), gethooktable(), ll_seeall(), lsqlite_backup_init(), luaL_findtable(), luaL_newmetatable(), luaopen_package(), newfenv(), os_date(), os_date(), os_date(), os_date(), pack(), pack(), and tpack().
lua_dump()
LUA_API int lua_dump (lua_State * L, lua_Writer writer, void * data)
Definition at line 875 of file lua-5.1.5/src/lapi.c.
{
  int status;
  TValue *o;
  lua_lock(L);
  api_checknelems(L, 1);
  o = L->top - 1;
  if (isLfunction(o))
    status = luaU_dump(L, clvalue(o)->l.p, writer, data, 0);
  else
    status = 1;
  lua_unlock(L);
  return status;
}
References api_checknelems, clvalue, isLfunction, lua_lock, lua_unlock, luaU_dump(), lua_State::top, and writer().
Referenced by str_dump(), str_dump(), str_dump(), and str_dump().
lua_equal()
LUA_API int lua_equal (lua_State * L, int index1, int index2)
Definition at line 287 of file lua-5.1.5/src/lapi.c.
{
  StkId o1, o2;
  int i;
  lua_lock(L);  /* may call tag method */
  o1 = index2adr(L, index1);
  o2 = index2adr(L, index2);
  i = (o1 == luaO_nilobject || o2 == luaO_nilobject) ? 0 : equalobj(L, o1, o2);
  lua_unlock(L);
  return i;
}
References equalobj, index2adr(), lua_lock, lua_unlock, and luaO_nilobject.
Referenced by Xml_iterate(), and Xml_match().
lua_error()
LUA_API int lua_error (lua_State * L)
Definition at line 964 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  api_checknelems(L, 1);
  luaG_errormsg(L);
  lua_unlock(L);
  return 0;  /* to avoid warnings */
}
References api_checknelems, lua_lock, lua_unlock, and luaG_errormsg().
Referenced by db_do_next_row(), db_do_rows(), lsqlite_newindex(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_dofile(), luaB_dofile(), luaB_dofile(), luaB_dofile(), luaB_error(), luaB_error(), luaB_error(), luaB_error(), luaL_error(), luaY_parser(), and resizebox().
lua_gc()
LUA_API int lua_gc (lua_State * L, int what, int data)
Definition at line 899 of file lua-5.1.5/src/lapi.c.
{
  int res = 0;
  global_State *g;
  lua_lock(L);
  g = G(L);
  switch (what) {
    case LUA_GCSTOP: {
      g->GCthreshold = MAX_LUMEM;
      break;
    }
    case LUA_GCRESTART: {
      g->GCthreshold = g->totalbytes;
      break;
    }
    case LUA_GCCOLLECT: {
      luaC_fullgc(L);
      break;
    }
    case LUA_GCCOUNT: {
      /* GC values are expressed in Kbytes: #bytes/2^10 */
      res = cast_int(g->totalbytes >> 10);
      break;
    }
    case LUA_GCCOUNTB: {
      res = cast_int(g->totalbytes & 0x3ff);
      break;
    }
    case LUA_GCSTEP: {
      lu_mem a = (cast(lu_mem, data) << 10);
      if (a <= g->totalbytes)
        g->GCthreshold = g->totalbytes - a;
      else
        g->GCthreshold = 0;
      while (g->GCthreshold <= g->totalbytes) {
        luaC_step(L);
        if (g->gcstate == GCSpause) {  /* end of cycle? */
          res = 1;  /* signal it */
          break;
        }
      }
      break;
    }
    case LUA_GCSETPAUSE: {
      res = g->gcpause;
      g->gcpause = data;
      break;
    }
    case LUA_GCSETSTEPMUL: {
      res = g->gcstepmul;
      g->gcstepmul = data;
      break;
    }
    default: res = -1;  /* invalid option */
  }
  lua_unlock(L);
  return res;
}
References cast, cast_int, G, global_State::gcpause, GCSpause, global_State::gcstate, global_State::gcstepmul, global_State::GCthreshold, LUA_GCCOLLECT, LUA_GCCOUNT, LUA_GCCOUNTB, LUA_GCRESTART, LUA_GCSETPAUSE, LUA_GCSETSTEPMUL, LUA_GCSTEP, LUA_GCSTOP, lua_lock, lua_unlock, luaC_fullgc(), luaC_step(), MAX_LUMEM, and global_State::totalbytes.
Referenced by docall(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), pmain(), pmain(), pmain(), and report().
lua_getallocf()
LUA_API lua_Alloc lua_getallocf (lua_State * L, void ** ud)
Definition at line 1007 of file lua-5.1.5/src/lapi.c.
{
  lua_Alloc f;
  lua_lock(L);
  if (ud) *ud = G(L)->ud;
  f = G(L)->frealloc;
  lua_unlock(L);
  return f;
}
References G, lua_lock, lua_unlock, and CCallS::ud.
Referenced by resizebox(), and resizebox().
lua_getfenv()
LUA_API void lua_getfenv (lua_State * L, int idx)
Definition at line 616 of file lua-5.1.5/src/lapi.c.
{
  StkId o;
  lua_lock(L);
  o = index2adr(L, idx);
  api_checkvalidindex(L, o);
  switch (ttype(o)) {
    case LUA_TFUNCTION:
      sethvalue(L, L->top, clvalue(o)->c.env);
      break;
    case LUA_TUSERDATA:
      sethvalue(L, L->top, uvalue(o)->env);
      break;
    case LUA_TTHREAD:
      setobj2s(L, L->top,  gt(thvalue(o)));
      break;
    default:
      setnilvalue(L->top);
      break;
  }
  api_incr_top(L);
  lua_unlock(L);
}
References api_checkvalidindex, api_incr_top, clvalue, gt, index2adr(), lua_lock, LUA_TFUNCTION, LUA_TTHREAD, LUA_TUSERDATA, lua_unlock, sethvalue, setnilvalue, setobj2s, thvalue, lua_State::top, ttype, and uvalue.
Referenced by aux_close(), db_getfenv(), and luaB_getfenv().
lua_getfield()
LUA_API void lua_getfield (lua_State * L, int idx, const char * k)
Definition at line 544 of file lua-5.1.5/src/lapi.c.
{
  StkId t;
  TValue key;
  lua_lock(L);
  t = index2adr(L, idx);
  api_checkvalidindex(L, t);
  setsvalue(L, &key, luaS_new(L, k));
  luaV_gettable(L, t, &key, L->top);
  api_incr_top(L);
  lua_unlock(L);
}
References api_checkvalidindex, api_incr_top, index2adr(), lua_lock, lua_unlock, luaS_new, luaV_gettable, setsvalue, and lua_State::top.
Referenced by addtoclib(), aux_close(), checkclib(), checkclib(), db_gethook(), findfile(), findfile(), findfile(), findfile(), findloader(), findloader(), findloader(), g_iofile(), g_iofile(), g_iofile(), get_prompt(), getboolfield(), getboolfield(), getboolfield(), getboolfield(), getfield(), getfield(), getfield(), getfield(), getiofile(), getiofile(), getiofile(), hookf(), io_close(), io_close(), io_close(), io_lines(), io_lines(), io_lines(), io_type(), ll_addtoclib(), ll_checkclib(), ll_module(), ll_require(), ll_require(), ll_require(), ll_require(), loader_preload(), luaI_openlib(), luaL_checkudata(), luaL_getsubtable(), luaL_newmetatable(), luaL_requiref(), luaopen_io(), luaopen_math(), luaopen_package(), luaopen_string(), luaopen_table(), noenv(), noenv(), noenv(), pushglobalfuncname(), pushglobalfuncname(), searcher_preload(), searcher_preload(), searcher_preload(), and traceback().
lua_getmetatable()
LUA_API int lua_getmetatable (lua_State * L, int objindex)
Definition at line 587 of file lua-5.1.5/src/lapi.c.
{
  const TValue *obj;
  Table *mt = NULL;
  int res;
  lua_lock(L);
  obj = index2adr(L, objindex);
  switch (ttype(obj)) {
    case LUA_TTABLE:
      mt = hvalue(obj)->metatable;
      break;
    case LUA_TUSERDATA:
      mt = uvalue(obj)->metatable;
      break;
    default:
      mt = G(L)->mt[ttype(obj)];
      break;
  }
  if (mt == NULL)
    res = 0;
  else {
    sethvalue(L, L->top, mt);
    api_incr_top(L);
    res = 1;
  }
  lua_unlock(L);
  return res;
}
References api_incr_top, G, hvalue, index2adr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, Table::metatable, NULL, sethvalue, lua_State::top, ttype, and uvalue.
Referenced by checktab(), checktab(), db_getmetatable(), db_getmetatable(), db_getmetatable(), db_getmetatable(), io_type(), ll_seeall(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_newproxy(), luaL_checkudata(), luaL_getmetafield(), and luaL_testudata().
lua_gettable()
LUA_API void lua_gettable (lua_State * L, int idx)
Definition at line 534 of file lua-5.1.5/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2adr(L, idx);
  api_checkvalidindex(L, t);
  luaV_gettable(L, t, L->top - 1, L->top - 1);
  lua_unlock(L);
}
References api_checkvalidindex, index2adr(), lua_lock, lua_unlock, luaV_gettable, and lua_State::top.
Referenced by add_value(), add_value(), add_value(), add_value(), dbvm_bind_names(), ll_register(), and Xml_pushDecode().
lua_gettop()
LUA_API int lua_gettop (lua_State * L)
Definition at line 159 of file lua-5.1.5/src/lapi.c.
{
  return cast_int(L->top - L->base);
}
References lua_State::base, cast_int, and lua_State::top.
Referenced by andaux(), aux_lines(), aux_lines(), aux_lines(), auxresume(), auxresume(), auxresume(), auxstatus(), b_or(), b_xor(), cleanupdb(), costatus(), db_busy_callback(), db_busy_handler(), db_commit_hook(), db_commit_hook_callback(), db_errorfb(), db_exec_callback(), db_progress_callback(), db_progress_handler(), db_rollback_hook(), db_rollback_hook_callback(), db_sql_finalize_function(), db_sql_normal_function(), db_trace(), db_trace_callback(), db_update_hook(), db_update_hook_callback(), dbvm_bind_values(), do_gsub(), docall(), docall(), docall(), docall(), dofilecont(), dofilecont(), dofilecont(), dotty(), dotty(), file_utime(), finishpcall(), finishpcall(), finishpcall(), g_read(), g_read(), g_read(), g_read(), g_write(), g_write(), g_write(), g_write(), io_lines(), l_print(), l_print(), ll_module(), loadline(), loadline(), luaB_assert(), luaB_assert(), luaB_assert(), luaB_assert(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_coresume(), luaB_coresume(), luaB_coresume(), luaB_coresume(), luaB_costatus(), luaB_costatus(), luaB_dofile(), luaB_pcall(), luaB_pcall(), luaB_pcall(), luaB_pcall(), luaB_print(), luaB_print(), luaB_print(), luaB_print(), luaB_select(), luaB_select(), luaB_select(), luaB_select(), luaB_warn(), luaB_xpcall(), luaB_xpcall(), luaB_xpcall(), luaB_xpcall(), luaB_yield(), luaB_yield(), luaB_yield(), luaB_yield(), luaL_loadfile(), luaL_loadfilex(), luaL_traceback(), make_xml_object(), math_max(), math_max(), math_max(), math_max(), math_min(), math_min(), math_min(), math_min(), math_random(), math_random(), math_random(), math_random(), pack(), pack(), print(), pushglobalfuncname(), pushglobalfuncname(), pushglobalfuncname(), str_char(), str_char(), str_char(), str_char(), str_format(), str_format(), str_format(), str_format(), tinsert(), tinsert(), tinsert(), tinsert(), tpack(), utfchar(), utfchar(), Xml_eval(), and Xml_pushEncode().
lua_getupvalue()
LUA_API const char * lua_getupvalue (lua_State * L, int funcindex, int n)
Definition at line 1057 of file lua-5.1.5/src/lapi.c.
{
  const char *name;
  TValue *val;
  lua_lock(L);
  name = aux_upvalue(index2adr(L, funcindex), n, &val);
  if (name) {
    setobj2s(L, L->top, val);
    api_incr_top(L);
  }
  lua_unlock(L);
  return name;
}
References api_incr_top, aux_upvalue(), index2adr(), lua_lock, lua_unlock, name, setobj2s, and lua_State::top.
Referenced by auxupvalue(), auxupvalue(), auxupvalue(), auxupvalue(), and checkupval().
lua_insert()
LUA_API void lua_insert (lua_State * L, int idx)
Definition at line 191 of file lua-5.1.5/src/lapi.c.
{
  StkId p;
  StkId q;
  lua_lock(L);
  p = index2adr(L, idx);
  api_checkvalidindex(L, p);
  for (q = L->top; q>p; q--) setobjs2s(L, q, q-1);
  setobjs2s(L, p, L->top);
  lua_unlock(L);
}
References api_checkvalidindex, index2adr(), lua_lock, lua_unlock, setobjs2s, and lua_State::top.
lua_iscfunction()
LUA_API int lua_iscfunction (lua_State * L, int idx)
Definition at line 254 of file lua-5.1.5/src/lapi.c.
{
  StkId o = index2adr(L, idx);
  return iscfunction(o);
}
References index2adr(), and iscfunction.
Referenced by auxupvalue(), db_upvaluejoin(), db_upvaluejoin(), db_upvaluejoin(), luaB_cocreate(), luaB_getfenv(), luaB_setfenv(), and setfenv().
lua_isnumber()
LUA_API int lua_isnumber (lua_State * L, int idx)
Definition at line 260 of file lua-5.1.5/src/lapi.c.
{
  TValue n;
  const TValue *o = index2adr(L, idx);
  return tonumber(o, &n);
}
References index2adr(), and tonumber.
Referenced by b_unpack(), db_errorfb(), db_exec_callback(), db_getinfo(), db_getinfo(), getfield(), interror(), interror(), luaB_setfenv(), luaB_tonumber(), luaL_checkinteger(), and luaL_checknumber().
lua_isstring()
LUA_API int lua_isstring (lua_State * L, int idx)
Definition at line 267 of file lua-5.1.5/src/lapi.c.
{
  int t = lua_type(L, idx);
  return (t == LUA_TSTRING || t == LUA_TNUMBER);
}
References LUA_TNUMBER, LUA_TSTRING, and lua_type().
Referenced by _file_info_(), add_value(), add_value(), add_value(), add_value(), addfield(), addfield(), addfield(), addfield(), db_errorfb(), findloader(), findloader(), findloader(), generic_reader(), generic_reader(), generic_reader(), generic_reader(), link_info(), ll_require(), luaB_auxwrap(), luaB_auxwrap(), luaB_error(), luaB_error(), luaL_tolstring(), print(), and traceback().
lua_isuserdata()
LUA_API int lua_isuserdata (lua_State * L, int idx)
Definition at line 273 of file lua-5.1.5/src/lapi.c.
{
  const TValue *o = index2adr(L, idx);
  return (ttisuserdata(o) || ttislightuserdata(o));
}
References index2adr(), ttislightuserdata, and ttisuserdata.
Referenced by Xml_eval().
lua_lessthan()
LUA_API int lua_lessthan (lua_State * L, int index1, int index2)
Definition at line 299 of file lua-5.1.5/src/lapi.c.
{
  StkId o1, o2;
  int i;
  lua_lock(L);  /* may call tag method */
  o1 = index2adr(L, index1);
  o2 = index2adr(L, index2);
  i = (o1 == luaO_nilobject || o2 == luaO_nilobject) ? 0
       : luaV_lessthan(L, o1, o2);
  lua_unlock(L);
  return i;
}
References index2adr(), lua_lock, lua_unlock, luaO_nilobject, and luaV_lessthan().
Referenced by sort_comp().
lua_load()
LUA_API int lua_load (lua_State * L, lua_Reader reader, void * data, const char * chunkname)
Definition at line 862 of file lua-5.1.5/src/lapi.c.
{
  ZIO z;
  int status;
  lua_lock(L);
  if (!chunkname) chunkname = "?";
  luaZ_init(L, &z, reader, data);
  status = luaD_protectedparser(L, &z, chunkname);
  lua_unlock(L);
  return status;
}
References lua_lock, lua_unlock, luaD_protectedparser(), luaZ_init(), and reader().
Referenced by combine(), combine(), combine(), luaB_load(), luaB_load(), luaB_load(), luaB_load(), luaL_loadbuffer(), luaL_loadbufferx(), luaL_loadfile(), and luaL_loadfilex().
lua_newthread()
LUA_API lua_State * lua_newthread (lua_State * L)
Definition at line 140 of file lua-5.1.5/src/lapi.c.
{
  lua_State *L1;
  lua_lock(L);
  luaC_checkGC(L);
  L1 = luaE_newthread(L);
  setthvalue(L, L->top, L1);
  api_incr_top(L);
  lua_unlock(L);
  luai_userstatethread(L, L1);
  return L1;
}
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaE_newthread(), luai_userstatethread, setthvalue, and lua_State::top.
Referenced by luaB_cocreate(), luaB_cocreate(), luaB_cocreate(), and luaB_cocreate().
lua_newuserdata()
LUA_API void * lua_newuserdata (lua_State * L, size_t size)
Definition at line 1025 of file lua-5.1.5/src/lapi.c.
{
  Udata *u;
  lua_lock(L);
  luaC_checkGC(L);
  u = luaS_newudata(L, size, getcurrenv(L));
  setuvalue(L, L->top, u);
  api_incr_top(L);
  lua_unlock(L);
  return u + 1;
}
References api_incr_top, getcurrenv(), lua_lock, lua_unlock, luaC_checkGC, luaS_newudata(), setuvalue, and lua_State::top.
lua_next()
LUA_API int lua_next (lua_State * L, int idx)
Definition at line 973 of file lua-5.1.5/src/lapi.c.
{
  StkId t;
  int more;
  lua_lock(L);
  t = index2adr(L, idx);
  api_check(L, ttistable(t));
  more = luaH_next(L, hvalue(t), L->top - 1);
  if (more) {
    api_incr_top(L);
  }
  else  /* no more elements */
    L->top -= 1;  /* remove key */
  lua_unlock(L);
  return more;
}
References api_check, api_incr_top, hvalue, index2adr(), lua_lock, lua_unlock, luaH_next(), lua_State::top, and ttistable.
Referenced by cleanupdb(), db_close_vm(), findfield(), findfield(), findfield(), foreach(), luaB_next(), luaB_next(), luaB_next(), luaB_next(), maxn(), Xml_pushDecode(), Xml_pushEncode(), and Xml_str().
lua_objlen()
LUA_API size_t lua_objlen (lua_State * L, int idx)
Definition at line 361 of file lua-5.1.5/src/lapi.c.
{
  StkId o = index2adr(L, idx);
  switch (ttype(o)) {
    case LUA_TSTRING: return tsvalue(o)->len;
    case LUA_TUSERDATA: return uvalue(o)->len;
    case LUA_TTABLE: return luaH_getn(hvalue(o));
    case LUA_TNUMBER: {
      size_t l;
      lua_lock(L);  /* `luaV_tostring' may create a new string */
      l = (luaV_tostring(L, o) ? tsvalue(o)->len : 0);
      lua_unlock(L);
      return l;
    }
    default: return 0;
  }
}
References hvalue, index2adr(), lua_lock, LUA_TNUMBER, LUA_TSTRING, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, luaH_getn(), luaV_tostring(), tsvalue, ttype, and uvalue.
Referenced by luaL_ref(), read_chars(), and read_line().
lua_pcall()
LUA_API int lua_pcall (lua_State * L, int nargs, int nresults, int errfunc)
Definition at line 805 of file lua-5.1.5/src/lapi.c.
{
  struct CallS c;
  int status;
  ptrdiff_t func;
  lua_lock(L);
  api_checknelems(L, nargs+1);
  checkresults(L, nargs, nresults);
  if (errfunc == 0)
    func = 0;
  else {
    StkId o = index2adr(L, errfunc);
    api_checkvalidindex(L, o);
    func = savestack(L, o);
  }
  c.func = L->top - (nargs+1);  /* function to be called */
  c.nresults = nresults;
  status = luaD_pcall(L, f_call, &c, savestack(L, c.func), func);
  adjustresults(L, nresults);
  lua_unlock(L);
  return status;
}
References adjustresults, api_checknelems, api_checkvalidindex, checkresults, f_call(), CallS::func, index2adr(), lua_lock, lua_unlock, luaD_pcall(), CallS::nresults, savestack, and lua_State::top.
lua_pushboolean()
LUA_API void lua_pushboolean (lua_State * L, int b)
Definition at line 503 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  setbvalue(L->top, (b != 0));  /* ensure that true is 1 */
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setbvalue, and lua_State::top.
Referenced by aux_lines(), aux_lines(), aux_lines(), aux_lines(), b_test(), change_dir(), db_getuservalue(), db_isopen(), db_load_extension(), db_register_function(), db_setmetatable(), dbvm_isopen(), file_lock(), file_unlock(), find_on_match(), finishpcall(), finishpcall(), finishpcall(), lfs_g_setmode(), ll_loadfunc(), ll_require(), ll_require(), ll_require(), ll_require(), lookforfunc(), lookforfunc(), lsqlite_complete(), luaB_close(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_coresume(), luaB_coresume(), luaB_coresume(), luaB_coresume(), luaB_corunning(), luaB_corunning(), luaB_corunning(), luaB_newproxy(), luaB_pcall(), luaB_pcall(), luaB_pcall(), luaB_rawequal(), luaB_rawequal(), luaB_rawequal(), luaB_rawequal(), luaB_xpcall(), luaB_xpcall(), luaB_xpcall(), luaB_yieldable(), luaB_yieldable(), luaL_execresult(), luaL_fileresult(), luaL_setfuncs(), math_ult(), math_ult(), os_execute(), os_execute(), os_execute(), os_pushresult(), pmain(), pmain(), pmain(), pushresult(), pushresult(), setboolfield(), setboolfield(), setboolfield(), setboolfield(), settabsb(), settabsb(), settabsb(), Xml_find(), and Xml_iterate().
lua_pushcclosure()
LUA_API void lua_pushcclosure (lua_State * L, lua_CFunction fn, int n)
Definition at line 486 of file lua-5.1.5/src/lapi.c.
{
  Closure *cl;
  lua_lock(L);
  luaC_checkGC(L);
  api_checknelems(L, n);
  cl = luaF_newCclosure(L, n, getcurrenv(L));
  cl->c.f = fn;
  L->top -= n;
  while (n--)
    setobj2n(L, &cl->c.upvalue[n], L->top+n);
  setclvalue(L, L->top, cl);
  lua_assert(iswhite(obj2gco(cl)));
  api_incr_top(L);
  lua_unlock(L);
}
References api_checknelems, api_incr_top, Closure::c, CClosure::f, getcurrenv(), iswhite, lua_assert, lua_lock, lua_unlock, luaC_checkGC, luaF_newCclosure(), obj2gco, setclvalue, setobj2n, lua_State::top, and CClosure::upvalue.
Referenced by aux_lines(), aux_lines(), aux_lines(), aux_lines(), auxopen(), base_open(), createsearcherstable(), createsearcherstable(), createsearcherstable(), gmatch(), gmatch(), gmatch(), gmatch(), luaB_cowrap(), luaB_cowrap(), luaB_cowrap(), luaB_cowrap(), luaI_openlib(), luaL_setfuncs(), and Xml_find().
lua_pushfstring()
LUA_API const char * lua_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 473 of file lua-5.1.5/src/lapi.c.
{
  const char *ret;
  va_list argp;
  lua_lock(L);
  luaC_checkGC(L);
  va_start(argp, fmt);
  ret = luaO_pushvfstring(L, fmt, argp);
  va_end(argp);
  lua_unlock(L);
  return ret;
}
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
Referenced by _file_info_(), addreturn(), addreturn(), auxresume(), change_dir(), checkoption(), checkoption(), checkoption(), controloptions(), db_errorfb(), db_getinfo(), db_getinfo(), db_getinfo(), db_getinfo(), db_last_insert_rowid(), db_tostring(), db_update_hook_callback(), dbvm_last_insert_rowid(), dbvm_tostring(), dotty(), dotty(), errfile(), errfile(), errfile(), errfile(), f_tostring(), f_tostring(), f_tostring(), file_lock(), file_unlock(), fileerror(), findfile(), io_tostring(), l_print(), l_print(), lcontext_tostring(), ll_register(), loader_Croot(), loader_preload(), loadfunc(), loadfunc(), loadfunc(), luaB_tostring(), luaL_checkoption(), luaL_checkoption(), luaL_fileresult(), luaL_loadfile(), luaL_loadfilex(), luaL_tolstring(), luaL_traceback(), luaL_typeerror(), luaL_typerror(), luaL_where(), mkfuncname(), msghandler(), msghandler(), os_pushresult(), pusherror(), pushfuncname(), pushfuncname(), pushfuncname(), pushline(), pushline(), pushline(), pushline(), pushresult(), pushutfchar(), pushutfchar(), searcher_Croot(), searcher_Croot(), searcher_Croot(), searcher_preload(), searcher_preload(), searcher_preload(), searchpath(), searchpath(), setpath(), setpath(), typeerror(), typeerror(), and Xml_str().
lua_pushinteger()
LUA_API void lua_pushinteger (lua_State * L, lua_Integer n)
Definition at line 437 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  setnvalue(L->top, cast_num(n));
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, cast_num, lua_lock, lua_unlock, setnvalue, and lua_State::top.
Referenced by _file_info_(), aux_lines(), aux_lines(), aux_lines(), b_size(), b_unpack(), byteoffset(), byteoffset(), cleanupbu(), cleanupvm(), codepoint(), codepoint(), db_busy_callback(), db_changes(), db_close(), db_errcode(), db_exec(), db_exec_callback(), db_gethook(), db_gethook(), db_gethook(), db_gethook(), db_prepare(), db_setcstacklimit(), db_total_changes(), db_update_hook_callback(), dbbu_pagecount(), dbbu_remaining(), dbbu_step(), dbvm_bind(), dbvm_bind_blob(), dbvm_bind_names(), dbvm_bind_parameter_count(), dbvm_bind_values(), dbvm_columns(), dbvm_reset(), dbvm_step(), f_seek(), f_seek(), f_seek(), foreachi(), get_onecapture(), getn(), gmatch(), gmatch(), gmatch_aux(), gmatch_aux(), hookf(), hookf(), hookf(), hookf(), ipairsaux(), ipairsaux(), ipairsaux(), ipairsaux(), iter_aux(), iter_aux(), iter_codes(), iter_codes(), lcontext_aggregate_count(), lsqlite_do_open(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_gcinfo(), luaB_ipairs(), luaB_ipairs(), luaB_ipairs(), luaB_rawlen(), luaB_rawlen(), luaB_rawlen(), luaB_select(), luaB_select(), luaB_select(), luaB_select(), luaB_tonumber(), luaB_tonumber(), luaL_execresult(), luaL_fileresult(), luaL_ref(), luaL_unref(), luaopen_lsqlite3(), luaopen_LuaXML_lib(), luaopen_math(), main(), main(), math_abs(), math_abs(), math_fmod(), math_fmod(), math_frexp(), math_frexp(), math_random(), math_random(), math_toint(), math_toint(), os_execute(), os_pushresult(), pack(), pack(), pairsmeta(), pairsmeta(), push_onecapture(), push_onecapture(), push_onecapture(), push_st_atime(), push_st_blksize(), push_st_blocks(), push_st_ctime(), push_st_dev(), push_st_gid(), push_st_ino(), push_st_mtime(), push_st_nlink(), push_st_rdev(), push_st_size(), push_st_uid(), push_TAG_key(), pusherror(), pushnumint(), pushnumint(), pushresult(), setfield(), setfield(), setfield(), setfield(), setseed(), settabsi(), settabsi(), settabsi(), settabsi(), str_byte(), str_byte(), str_byte(), str_byte(), str_find_aux(), str_find_aux(), str_find_aux(), str_find_aux(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), str_len(), str_len(), str_len(), str_len(), str_packsize(), str_packsize(), str_unpack(), str_unpack(), tpack(), traceback(), utflen(), utflen(), Xml_iterate(), and Xml_str().
lua_pushlightuserdata()
LUA_API void lua_pushlightuserdata (lua_State * L, void * p)
Definition at line 511 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  setpvalue(L->top, p);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setpvalue, and lua_State::top.
Referenced by addtoclib(), addtoclib(), cleanupbu(), cleanupdb(), cleanupvm(), db_close_vm(), db_get_ptr(), db_gethook(), db_sethook(), db_sql_finalize_function(), db_sql_normal_function(), db_upvalueid(), db_upvalueid(), db_upvalueid(), gethooktable(), hookf(), ll_addtoclib(), ll_require(), lsqlite_backup_init(), luaL_buffinit(), main(), main(), newdb(), newvm(), and Xml_load().
lua_pushlstring()
LUA_API void lua_pushlstring (lua_State * L, const char * s, size_t len)
Definition at line 445 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  luaC_checkGC(L);
  setsvalue2s(L, L->top, luaS_newlstr(L, s, len));
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaS_newlstr(), s, setsvalue2s, and lua_State::top.
Referenced by add_value(), add_value(), add_value(), b_unpack(), collwrapper(), db_getinfo(), db_push_value(), emptybuffer(), loader_Croot(), loadfunc(), loadfunc(), loadfunc(), lua_pushstring(), luaL_findtable(), luaL_pushresult(), luaopen_utf8(), modinit(), push_link_target(), push_onecapture(), push_onecapture(), push_onecapture(), push_onecapture(), pushline(), pushline(), pushnexttemplate(), pushnexttemplate(), pushnexttemplate(), searcher_Croot(), searcher_Croot(), searcher_Croot(), str_sub(), str_sub(), str_sub(), str_sub(), str_unpack(), str_unpack(), test_eof(), test_eof(), vm_push_column(), Xml_eval(), Xml_pushDecode(), and XMLencoding_replacement().
lua_pushnil()
LUA_API void lua_pushnil (lua_State * L)
Definition at line 421 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  setnilvalue(L->top);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
Referenced by _file_info_(), b_pack(), byteoffset(), change_dir(), cleanupbu(), cleanupdb(), cleanupvm(), db_close_vm(), db_exec(), db_gethook(), db_getinfo(), db_getinfo(), db_getinfo(), db_getlocal(), db_getlocal(), db_getlocal(), db_getmetatable(), db_getmetatable(), db_getmetatable(), db_getmetatable(), db_getuservalue(), db_getuservalue(), db_prepare(), db_push_value(), db_sql_finalize_function(), dir_iter(), dir_iter_factory(), file_lock(), file_unlock(), findfield(), findfield(), findfield(), foreach(), g_read(), g_read(), g_read(), get_dir(), hookf(), hookf(), hookf(), hookf(), io_lines(), io_lines(), io_lines(), io_noclose(), io_noclose(), io_noclose(), io_type(), io_type(), io_type(), lfs_g_setmode(), lfs_lock_dir(), ll_loadlib(), ll_loadlib(), ll_loadlib(), ll_searchpath(), ll_searchpath(), load_aux(), load_aux(), load_aux(), lsqlite_do_open(), lua_pushstring(), luaB_corunning(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_next(), luaB_next(), luaB_next(), luaB_next(), luaB_pairs(), luaB_pairs(), luaB_pcall(), luaB_tonumber(), luaB_tonumber(), luaB_tonumber(), luaL_execresult(), luaL_fileresult(), make_link(), math_toint(), math_type(), maxn(), os_date(), os_date(), os_pushresult(), os_time(), os_time(), pairsmeta(), pairsmeta(), pusherror(), pushresult(), read_number(), read_number(), read_number(), read_number(), str_find_aux(), str_find_aux(), str_find_aux(), str_pack(), str_pack(), tremove(), tremove(), tremove(), tremove(), utflen(), vm_push_column(), Xml_pushDecode(), Xml_pushEncode(), and Xml_str().
lua_pushnumber()
LUA_API void lua_pushnumber (lua_State * L, lua_Number n)
Definition at line 429 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  setnvalue(L->top, n);
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, lua_lock, lua_unlock, setnvalue, and lua_State::top.
Referenced by b_unpack(), db_push_value(), f_seek(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_tonumber(), luaB_tonumber(), luaL_checkversion_(), luaopen_math(), math_abs(), math_abs(), math_abs(), math_abs(), math_acos(), math_acos(), math_acos(), math_acos(), math_asin(), math_asin(), math_asin(), math_asin(), math_atan(), math_atan(), math_atan(), math_atan(), math_atan2(), math_atan2(), math_ceil(), math_ceil(), math_cos(), math_cos(), math_cos(), math_cos(), math_cosh(), math_cosh(), math_deg(), math_deg(), math_deg(), math_deg(), math_exp(), math_exp(), math_exp(), math_exp(), math_floor(), math_floor(), math_fmod(), math_fmod(), math_fmod(), math_fmod(), math_frexp(), math_frexp(), math_ldexp(), math_ldexp(), math_log(), math_log(), math_log(), math_log(), math_log10(), math_max(), math_max(), math_min(), math_min(), math_modf(), math_modf(), math_modf(), math_modf(), math_pow(), math_pow(), math_rad(), math_rad(), math_rad(), math_rad(), math_random(), math_random(), math_random(), math_random(), math_sin(), math_sin(), math_sin(), math_sin(), math_sinh(), math_sinh(), math_sqrt(), math_sqrt(), math_sqrt(), math_sqrt(), math_tan(), math_tan(), math_tan(), math_tan(), math_tanh(), math_tanh(), maxn(), os_clock(), os_clock(), os_clock(), os_clock(), os_difftime(), os_difftime(), os_difftime(), os_difftime(), os_time(), os_time(), pushnumint(), pushnumint(), read_number(), read_number(), str_unpack(), str_unpack(), and vm_push_column().
lua_pushstring()
LUA_API void lua_pushstring (lua_State * L, const char * s)
Definition at line 454 of file lua-5.1.5/src/lapi.c.
{
  if (s == NULL)
    lua_pushnil(L);
  else
    lua_pushlstring(L, s, strlen(s));
}
References lua_pushlstring(), lua_pushnil(), NULL, and s.
Referenced by _file_info_(), auxupvalue(), auxupvalue(), auxupvalue(), auxupvalue(), checkfield(), checkfield(), checkload(), checkload(), checkload(), create_meta(), createargtable(), createargtable(), db_db_filename(), db_do_next_row(), db_do_rows(), db_errmsg(), db_exec_callback(), db_gethook(), db_gethook(), db_gethook(), db_gethook(), db_getlocal(), db_getlocal(), db_getlocal(), db_getlocal(), db_load_extension(), db_prepare(), db_sethook(), db_sethook(), db_setlocal(), db_setlocal(), db_setlocal(), db_setlocal(), db_trace_callback(), db_update_hook_callback(), dbvm_bind_names(), dbvm_bind_parameter_name(), dbvm_get_name(), dbvm_get_named_types(), dbvm_get_named_values(), dbvm_get_names(), dbvm_get_type(), dbvm_get_types(), dbvm_get_unames(), dbvm_get_utypes(), dir_iter(), dolibrary(), dolibrary(), dolibrary(), dolibrary(), findloader(), findloader(), findloader(), finishpcall(), get_dir(), getargs(), getargs(), hookf(), hookf(), hookf(), hookf(), lfs_g_setmode(), lfs_lock_dir(), ll_loadlib(), ll_loadlib(), ll_loadlib(), ll_loadlib(), ll_require(), ll_require(), ll_require(), lsqlite_do_open(), lsqlite_lversion(), lsqlite_temp_directory(), lsqlite_version(), luaB_costatus(), luaB_costatus(), luaB_tostring(), luaB_type(), luaB_type(), luaB_type(), luaB_type(), luaL_execresult(), luaL_fileresult(), luaL_getmetafield(), luaL_newmetatable(), luaL_openlibs(), luaL_requiref(), luaL_tolstring(), luaopen_lsqlite3(), make_link(), math_type(), mg_start2(), modinit(), os_getenv(), os_getenv(), os_getenv(), os_getenv(), os_setlocale(), os_setlocale(), os_setlocale(), os_setlocale(), os_tmpname(), os_tmpname(), os_tmpname(), os_tmpname(), push_st_mode(), push_st_perm(), pusherror(), pushglobalfuncname(), pushglobalfuncname(), pushline(), pushline(), pushmode(), searcher_Croot(), searcher_Croot(), searcher_Croot(), searchpath(), setpath(), setpath(), setpath(), setpath(), settabss(), settabss(), settabss(), settabss(), and Xml_eval().
lua_pushthread()
LUA_API int lua_pushthread (lua_State * L)
Definition at line 519 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  setthvalue(L, L->top, L);
  api_incr_top(L);
  lua_unlock(L);
  return (G(L)->mainthread == L);
}
References api_incr_top, G, lua_lock, lua_unlock, setthvalue, and lua_State::top.
Referenced by db_gethook(), db_gethook(), db_gethook(), db_sethook(), db_sethook(), db_sethook(), hookf(), hookf(), hookf(), luaB_corunning(), luaB_corunning(), luaB_corunning(), luaB_corunning(), and luaB_setfenv().
lua_pushvalue()
LUA_API void lua_pushvalue (lua_State * L, int idx)
Definition at line 228 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  setobj2s(L, L->top, index2adr(L, idx));
  api_incr_top(L);
  lua_unlock(L);
}
References api_incr_top, index2adr(), lua_lock, lua_unlock, setobj2s, and lua_State::top.
Referenced by add_value(), add_value(), add_value(), add_value(), addtoclib(), addtoclib(), aux_lines(), aux_lines(), aux_lines(), auxsort(), auxsort(), auxsort(), auxsort(), base_open(), checkupval(), create_meta(), createmeta(), createmeta(), createmeta(), createmetatable(), createmetatable(), createmetatable(), createmetatable(), createsearcherstable(), createsearcherstable(), createsearcherstable(), createstdfile(), createstdfile(), createstdfile(), createstdfile(), db_exec_callback(), db_getinfo(), db_getinfo(), db_getinfo(), db_getinfo(), db_getlocal(), db_getlocal(), db_getlocal(), db_getlocal(), db_getregistry(), db_getregistry(), db_getregistry(), db_getregistry(), db_register_function(), db_sethook(), db_sethook(), db_sethook(), db_sethook(), db_sql_finalize_function(), db_sql_normal_function(), db_traceback(), db_traceback(), db_traceback(), dbvm_do_rows(), dir_iter_factory(), dooptions(), f_write(), f_write(), f_write(), finishpcall(), finishpcall(), foreach(), foreachi(), g_iofile(), g_iofile(), g_iofile(), g_iofile(), generic_reader(), generic_reader(), generic_reader(), generic_reader(), getfunc(), gethooktable(), io_lines(), io_readline(), io_readline(), io_readline(), io_readline(), iter_codes(), iter_codes(), ll_addtoclib(), ll_module(), ll_register(), ll_require(), ll_require(), ll_require(), ll_require(), ll_seeall(), load_aux(), load_aux(), load_aux(), lsqlite_backup_init(), luaB_cocreate(), luaB_cocreate(), luaB_cocreate(), luaB_cocreate(), luaB_error(), luaB_error(), luaB_error(), luaB_error(), luaB_getfenv(), luaB_ipairs(), luaB_ipairs(), luaB_ipairs(), luaB_newproxy(), luaB_pairs(), luaB_pairs(), luaB_print(), luaB_print(), luaB_print(), luaB_setfenv(), luaB_tostring(), luaB_xpcall(), luaB_xpcall(), luaB_xpcall(), luaI_openlib(), luaL_callmeta(), luaL_findtable(), luaL_getsubtable(), luaL_newmetatable(), luaL_requiref(), luaL_setfuncs(), luaL_tolstring(), luaopen_base(), luaopen_lfs(), luaopen_lsqlite3(), luaopen_LuaXML_lib(), luaopen_package(), luaopen_struct(), math_max(), math_max(), math_min(), math_min(), modinit(), newvm(), pack(), pairsmeta(), pairsmeta(), setfenv(), setn(), sort_comp(), sort_comp(), sort_comp(), sort_comp(), str_format(), str_gsub(), tmove(), tmove(), tonum(), traceback(), treatstackoption(), treatstackoption(), Xml_append(), Xml_eval(), Xml_find(), Xml_iterate(), Xml_match(), Xml_new(), Xml_pushEncode(), Xml_str(), and Xml_tag().
lua_pushvfstring()
LUA_API const char * lua_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 462 of file lua-5.1.5/src/lapi.c.
{
  const char *ret;
  lua_lock(L);
  luaC_checkGC(L);
  ret = luaO_pushvfstring(L, fmt, argp);
  lua_unlock(L);
  return ret;
}
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
Referenced by luaL_error().
lua_rawequal()
LUA_API int lua_rawequal (lua_State * L, int index1, int index2)
Definition at line 279 of file lua-5.1.5/src/lapi.c.
{
  StkId o1 = index2adr(L, index1);
  StkId o2 = index2adr(L, index2);
  return (o1 == luaO_nilobject || o2 == luaO_nilobject) ? 0
         : luaO_rawequalObj(o1, o2);
}
References index2adr(), luaO_nilobject, and luaO_rawequalObj().
Referenced by findfield(), findfield(), findfield(), io_type(), luaB_rawequal(), luaB_rawequal(), luaB_rawequal(), luaB_rawequal(), luaL_checkudata(), and luaL_testudata().
lua_rawget()
LUA_API void lua_rawget (lua_State * L, int idx)
Definition at line 557 of file lua-5.1.5/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  t = index2adr(L, idx);
  api_check(L, ttistable(t));
  setobj2s(L, L->top - 1, luaH_get(hvalue(t), L->top - 1));
  lua_unlock(L);
}
References api_check, hvalue, index2adr(), lua_lock, lua_unlock, luaH_get(), setobj2s, lua_State::top, and ttistable.
Referenced by checkfield(), checkfield(), cleanupdb(), cleanupvm(), db_close_vm(), db_gethook(), db_gethook(), db_gethook(), db_gethook(), db_sql_finalize_function(), db_sql_normal_function(), gethooktable(), hookf(), hookf(), hookf(), hookf(), luaB_newproxy(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaL_findtable(), luaL_getmetafield(), newvm(), Xml_match(), Xml_str(), and Xml_tag().
lua_rawgeti()
LUA_API void lua_rawgeti (lua_State * L, int idx, int n)
Definition at line 567 of file lua-5.1.5/src/lapi.c.
{
  StkId o;
  lua_lock(L);
  o = index2adr(L, idx);
  api_check(L, ttistable(o));
  setobj2s(L, L->top, luaH_getnum(hvalue(o), n));
  api_incr_top(L);
  lua_unlock(L);
}
References api_check, api_incr_top, hvalue, index2adr(), lua_lock, lua_unlock, luaH_getnum(), setobj2s, lua_State::top, and ttistable.
Referenced by addfield(), addfield(), auxsort(), auxsort(), collwrapper(), db_busy_callback(), db_commit_hook_callback(), db_progress_callback(), db_rollback_hook_callback(), db_sql_finalize_function(), db_sql_normal_function(), db_trace_callback(), db_update_hook_callback(), findloader(), findloader(), findloader(), foreachi(), g_iofile(), gctm(), gctm(), gctm(), getiofile(), io_close(), io_lines(), ipairsaux(), ipairsaux(), lcontext_get_aggregate_context(), lcontext_user_data(), ll_require(), lsqlite_make_context(), luaB_unpack(), luaL_ref(), luaL_unref(), pushargs(), pushargs(), tinsert(), tinsert(), tremove(), tremove(), unpack(), Xml_find(), Xml_iterate(), Xml_pushDecode(), Xml_pushEncode(), Xml_registerCode(), and Xml_str().
lua_rawset()
LUA_API void lua_rawset (lua_State * L, int idx)
Definition at line 671 of file lua-5.1.5/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  api_checknelems(L, 2);
  t = index2adr(L, idx);
  api_check(L, ttistable(t));
  setobj2t(L, luaH_set(L, hvalue(t), L->top-2), L->top-1);
  luaC_barriert(L, hvalue(t), L->top-1);
  L->top -= 2;
  lua_unlock(L);
}
References api_check, api_checknelems, hvalue, index2adr(), lua_lock, lua_unlock, luaC_barriert, luaH_set(), setobj2t, lua_State::top, and ttistable.
Referenced by _file_info_(), cleanupbu(), cleanupdb(), cleanupvm(), create_meta(), db_do_next_row(), db_sethook(), db_sethook(), db_sethook(), db_sethook(), db_sql_finalize_function(), db_sql_normal_function(), dbvm_get_named_types(), dbvm_get_named_values(), gethooktable(), lsqlite_backup_init(), luaB_newproxy(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaopen_lsqlite3(), luaopen_LuaXML_lib(), mg_start2(), newdb(), newvm(), Xml_eval(), Xml_registerCode(), and Xml_tag().
lua_rawseti()
LUA_API void lua_rawseti (lua_State * L, int idx, int n)
Definition at line 684 of file lua-5.1.5/src/lapi.c.
{
  StkId o;
  lua_lock(L);
  api_checknelems(L, 1);
  o = index2adr(L, idx);
  api_check(L, ttistable(o));
  setobj2t(L, luaH_setnum(L, hvalue(o), n), L->top-1);
  luaC_barriert(L, hvalue(o), L->top-1);
  L->top--;
  lua_unlock(L);
}
References api_check, api_checknelems, hvalue, index2adr(), lua_lock, lua_unlock, luaC_barriert, luaH_setnum(), setobj2t, lua_State::top, and ttistable.
Referenced by addtoclib(), addtoclib(), createargtable(), createargtable(), createsearcherstable(), createsearcherstable(), createsearcherstable(), createstdfile(), db_do_next_row(), db_exec_callback(), dbvm_get_names(), dbvm_get_types(), dbvm_get_values(), find_on_match(), g_iofile(), getargs(), getargs(), ll_addtoclib(), lsqlite_backup_init(), luaL_ref(), luaL_unref(), luaopen_package(), pack(), set2(), set2(), tinsert(), tinsert(), tremove(), tremove(), Xml_append(), Xml_eval(), and Xml_str().
lua_remove()
LUA_API void lua_remove (lua_State * L, int idx)
Definition at line 180 of file lua-5.1.5/src/lapi.c.
{
  StkId p;
  lua_lock(L);
  p = index2adr(L, idx);
  api_checkvalidindex(L, p);
  while (++p < L->top) setobjs2s(L, p-1, p);
  L->top--;
  lua_unlock(L);
}
References api_checkvalidindex, index2adr(), lua_lock, lua_unlock, setobjs2s, and lua_State::top.
lua_replace()
LUA_API void lua_replace (lua_State * L, int idx)
Definition at line 203 of file lua-5.1.5/src/lapi.c.
{
  StkId o;
  lua_lock(L);
  /* explicit test for incompatible code */
  if (idx == LUA_ENVIRONINDEX && L->ci == L->base_ci)
    luaG_runerror(L, "no calling environment");
  api_checknelems(L, 1);
  o = index2adr(L, idx);
  api_checkvalidindex(L, o);
  if (idx == LUA_ENVIRONINDEX) {
    Closure *func = curr_func(L);
    api_check(L, ttistable(L->top - 1));
    func->c.env = hvalue(L->top - 1);
    luaC_barrier(L, func, L->top - 1);
  }
  else {
    setobj(L, o, L->top - 1);
    if (idx < LUA_GLOBALSINDEX)  /* function upvalue? */
      luaC_barrier(L, curr_func(L), L->top - 1);
  }
  L->top--;
  lua_unlock(L);
}
References api_check, api_checknelems, api_checkvalidindex, lua_State::base_ci, Closure::c, lua_State::ci, curr_func, hvalue, index2adr(), LUA_ENVIRONINDEX, LUA_GLOBALSINDEX, lua_lock, lua_unlock, luaC_barrier, luaG_runerror(), setobj, lua_State::top, and ttistable.
lua_setallocf()
LUA_API void lua_setallocf (lua_State * L, lua_Alloc f, void * ud)
Definition at line 1017 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  G(L)->ud = ud;
  G(L)->frealloc = f;
  lua_unlock(L);
}
References G, lua_lock, lua_unlock, and CCallS::ud.
lua_setfenv()
LUA_API int lua_setfenv (lua_State * L, int idx)
Definition at line 734 of file lua-5.1.5/src/lapi.c.
{
  StkId o;
  int res = 1;
  lua_lock(L);
  api_checknelems(L, 1);
  o = index2adr(L, idx);
  api_checkvalidindex(L, o);
  api_check(L, ttistable(L->top - 1));
  switch (ttype(o)) {
    case LUA_TFUNCTION:
      clvalue(o)->c.env = hvalue(L->top - 1);
      break;
    case LUA_TUSERDATA:
      uvalue(o)->env = hvalue(L->top - 1);
      break;
    case LUA_TTHREAD:
      sethvalue(L, gt(thvalue(o)), hvalue(L->top - 1));
      break;
    default:
      res = 0;
      break;
  }
  if (res) luaC_objbarrier(L, gcvalue(o), hvalue(L->top - 1));
  L->top--;
  lua_unlock(L);
  return res;
}
References api_check, api_checknelems, api_checkvalidindex, clvalue, gcvalue, gt, hvalue, index2adr(), lua_lock, LUA_TFUNCTION, LUA_TTHREAD, LUA_TUSERDATA, lua_unlock, luaC_objbarrier, sethvalue, thvalue, lua_State::top, ttistable, ttype, and uvalue.
Referenced by createstdfile(), db_setfenv(), luaB_setfenv(), luaopen_io(), and setfenv().
lua_setfield()
LUA_API void lua_setfield (lua_State * L, int idx, const char * k)
Definition at line 657 of file lua-5.1.5/src/lapi.c.
{
  StkId t;
  TValue key;
  lua_lock(L);
  api_checknelems(L, 1);
  t = index2adr(L, idx);
  api_checkvalidindex(L, t);
  setsvalue(L, &key, luaS_new(L, k));
  luaV_settable(L, t, &key, L->top - 1);
  L->top--;  /* pop value */
  lua_unlock(L);
}
References api_checknelems, api_checkvalidindex, index2adr(), lua_lock, lua_unlock, luaS_new, luaV_settable, setsvalue, and lua_State::top.
Referenced by addtoclib(), addtoclib(), auxopen(), base_open(), createclibstable(), createclibstable(), createmeta(), createmeta(), createmeta(), createmeta(), createmetatable(), createmetatable(), createmetatable(), createmetatable(), createsearcherstable(), createsearcherstable(), createstdfile(), createstdfile(), createstdfile(), createstdfile(), db_getinfo(), db_sethook(), db_sethook(), db_sethook(), dir_create_meta(), g_iofile(), g_iofile(), g_iofile(), link_info(), ll_addtoclib(), ll_module(), ll_require(), ll_require(), ll_require(), ll_require(), ll_seeall(), lock_create_meta(), luaI_openlib(), luaL_getsubtable(), luaL_newmetatable(), luaL_openlibs(), luaL_requiref(), luaL_setfuncs(), luaopen_base(), luaopen_LuaXML_lib(), luaopen_math(), luaopen_package(), luaopen_string(), luaopen_utf8(), modinit(), newbox(), newfenv(), pack(), pack(), pmain(), pmain(), pmain(), set_info(), setboolfield(), setboolfield(), setboolfield(), setboolfield(), setfield(), setfield(), setfield(), setfield(), setpath(), setpath(), setpath(), setpath(), settabsb(), settabsb(), settabsb(), settabsi(), settabsi(), settabsi(), settabsi(), settabss(), settabss(), settabss(), settabss(), tpack(), treatstackoption(), treatstackoption(), treatstackoption(), and treatstackoption().
lua_setlevel()
LUA_API void lua_setlevel (lua_State * from, lua_State * to)
Definition at line 125 of file lua-5.1.5/src/lapi.c.
{
  to->nCcalls = from->nCcalls;
}
References lua_State::nCcalls.
Referenced by auxresume().
lua_setmetatable()
LUA_API int lua_setmetatable (lua_State * L, int objindex)
Definition at line 697 of file lua-5.1.5/src/lapi.c.
{
  TValue *obj;
  Table *mt;
  lua_lock(L);
  api_checknelems(L, 1);
  obj = index2adr(L, objindex);
  api_checkvalidindex(L, obj);
  if (ttisnil(L->top - 1))
    mt = NULL;
  else {
    api_check(L, ttistable(L->top - 1));
    mt = hvalue(L->top - 1);
  }
  switch (ttype(obj)) {
    case LUA_TTABLE: {
      hvalue(obj)->metatable = mt;
      if (mt)
        luaC_objbarriert(L, hvalue(obj), mt);
      break;
    }
    case LUA_TUSERDATA: {
      uvalue(obj)->metatable = mt;
      if (mt)
        luaC_objbarrier(L, rawuvalue(obj), mt);
      break;
    }
    default: {
      G(L)->mt[ttype(obj)] = mt;
      break;
    }
  }
  L->top--;
  lua_unlock(L);
  return 1;
}
References api_check, api_checknelems, api_checkvalidindex, G, hvalue, index2adr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, luaC_objbarrier, luaC_objbarriert, NULL, rawuvalue, lua_State::top, ttisnil, ttistable, ttype, and uvalue.
Referenced by base_open(), createclibstable(), createclibstable(), createmetatable(), createmetatable(), createmetatable(), createmetatable(), db_sethook(), db_sethook(), db_sethook(), db_setmetatable(), db_setmetatable(), db_setmetatable(), db_setmetatable(), dir_iter_factory(), lfs_lock_dir(), ll_register(), ll_seeall(), lsqlite_backup_init(), lsqlite_make_context(), luaB_newproxy(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaL_setmetatable(), luaopen_lsqlite3(), luaopen_package(), make_xml_object(), newbox(), newbox(), newdb(), newfile(), and newvm().
lua_settable()
LUA_API void lua_settable (lua_State * L, int idx)
Definition at line 645 of file lua-5.1.5/src/lapi.c.
{
  StkId t;
  lua_lock(L);
  api_checknelems(L, 2);
  t = index2adr(L, idx);
  api_checkvalidindex(L, t);
  luaV_settable(L, t, L->top - 2, L->top - 1);
  L->top -= 2;  /* pop index and value */
  lua_unlock(L);
}
References api_checknelems, api_checkvalidindex, index2adr(), lua_lock, lua_unlock, luaV_settable, and lua_State::top.
Referenced by ll_register(), and luaL_findtable().
lua_settop()
LUA_API void lua_settop (lua_State * L, int idx)
Definition at line 164 of file lua-5.1.5/src/lapi.c.
{
  lua_lock(L);
  if (idx >= 0) {
    api_check(L, idx <= L->stack_last - L->base);
    while (L->top < L->base + idx)
      setnilvalue(L->top++);
    L->top = L->base + idx;
  }
  else {
    api_check(L, -(idx+1) <= (L->top - L->base));
    L->top += idx+1;  /* `subtract' index (index is negative) */
  }
  lua_unlock(L);
}
References api_check, lua_State::base, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
Referenced by _file_info_(), cleanupdb(), db_busy_callback(), db_busy_handler(), db_commit_hook(), db_commit_hook_callback(), db_create_collation(), db_debug(), db_debug(), db_debug(), db_debug(), db_do_rows(), db_exec(), db_exec_callback(), db_prepare(), db_progress_callback(), db_progress_handler(), db_register_function(), db_rollback_hook(), db_rollback_hook_callback(), db_setfenv(), db_sethook(), db_sethook(), db_sethook(), db_sethook(), db_setlocal(), db_setlocal(), db_setlocal(), db_setlocal(), db_setmetatable(), db_setmetatable(), db_setmetatable(), db_setmetatable(), db_setuservalue(), db_setuservalue(), db_setuservalue(), db_sql_finalize_function(), db_sql_normal_function(), db_trace(), db_trace_callback(), db_update_hook(), db_update_hook_callback(), doREPL(), doREPL(), dotty(), dotty(), find_on_match(), finishpcall(), gmatch(), gmatch(), gmatch(), gmatch(), io_readline(), io_readline(), io_readline(), io_readline(), lcontext_set_aggregate_context(), ll_require(), ll_require(), ll_require(), ll_require(), loadline(), loadline(), loadline(), loadline(), luaB_assert(), luaB_assert(), luaB_dofile(), luaB_dofile(), luaB_dofile(), luaB_error(), luaB_error(), luaB_error(), luaB_error(), luaB_load(), luaB_load(), luaB_load(), luaB_load(), luaB_newproxy(), luaB_next(), luaB_next(), luaB_next(), luaB_next(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_tonumber(), luaB_tonumber(), luaB_xpcall(), luaL_loadfile(), luaL_loadfilex(), math_ceil(), math_ceil(), math_floor(), math_floor(), math_modf(), math_modf(), os_time(), os_time(), os_time(), os_time(), pushglobalfuncname(), pushglobalfuncname(), pushglobalfuncname(), sort(), sort(), sort(), sort(), str_dump(), str_dump(), str_dump(), str_dump(), trymt(), Xml_append(), Xml_eval(), Xml_find(), Xml_iterate(), Xml_match(), Xml_new(), Xml_registerCode(), Xml_str(), and Xml_tag().
lua_setupvalue()
LUA_API const char * lua_setupvalue (lua_State * L, int funcindex, int n)
Definition at line 1071 of file lua-5.1.5/src/lapi.c.
{
  const char *name;
  TValue *val;
  StkId fi;
  lua_lock(L);
  fi = index2adr(L, funcindex);
  api_checknelems(L, 1);
  name = aux_upvalue(fi, n, &val);
  if (name) {
    L->top--;
    setobj(L, val, L->top);
    luaC_barrier(L, clvalue(fi), L->top);
  }
  lua_unlock(L);
  return name;
}
References api_checknelems, aux_upvalue(), clvalue, index2adr(), lua_lock, lua_unlock, luaC_barrier, name, setobj, and lua_State::top.
Referenced by auxupvalue(), auxupvalue(), auxupvalue(), auxupvalue(), load_aux(), load_aux(), and load_aux().
lua_status()
LUA_API int lua_status (lua_State * L)
Definition at line 890 of file lua-5.1.5/src/lapi.c.
{
  return L->status;
}
References lua_State::status.
Referenced by auxresume(), auxresume(), auxstatus(), costatus(), luaB_auxwrap(), luaB_costatus(), and luaB_costatus().
lua_toboolean()
LUA_API int lua_toboolean (lua_State * L, int idx)
Definition at line 337 of file lua-5.1.5/src/lapi.c.
{
  const TValue *o = index2adr(L, idx);
  return !l_isfalse(o);
}
References index2adr(), and l_isfalse.
Referenced by add_value(), add_value(), add_value(), add_value(), codepoint(), db_busy_callback(), db_close_vm(), db_commit_hook_callback(), db_progress_callback(), dbvm_bind_index(), getboolfield(), getboolfield(), getboolfield(), getboolfield(), io_readline(), io_readline(), io_readline(), io_readline(), iter_codes(), ll_require(), ll_require(), ll_require(), ll_require(), log_access(), luaB_assert(), luaB_assert(), luaB_assert(), luaB_assert(), luaB_newproxy(), luaB_tostring(), luaL_requiref(), luaL_tolstring(), main(), make_link(), noenv(), noenv(), noenv(), os_exit(), os_exit(), os_exit(), print(), sort_comp(), sort_comp(), sort_comp(), sort_comp(), str_dump(), str_dump(), str_find_aux(), str_find_aux(), str_find_aux(), str_find_aux(), utflen(), and Xml_iterate().
lua_tocfunction()
LUA_API lua_CFunction lua_tocfunction (lua_State * L, int idx)
Definition at line 379 of file lua-5.1.5/src/lapi.c.
{
  StkId o = index2adr(L, idx);
  return (!iscfunction(o)) ? NULL : clvalue(o)->c.f;
}
References clvalue, index2adr(), iscfunction, and NULL.
Referenced by aux_close().
lua_tointeger()
LUA_API lua_Integer lua_tointeger (lua_State * L, int idx)
Definition at line 323 of file lua-5.1.5/src/lapi.c.
{
  TValue n;
  const TValue *o = index2adr(L, idx);
  if (tonumber(o, &n)) {
    lua_Integer res;
    lua_Number num = nvalue(o);
    lua_number2integer(res, num);
    return res;
  }
  else
    return 0;
}
References index2adr(), lua_number2integer, nvalue, and tonumber.
lua_tolstring()
LUA_API const char * lua_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 343 of file lua-5.1.5/src/lapi.c.
{
  StkId o = index2adr(L, idx);
  if (!ttisstring(o)) {
    lua_lock(L);  /* `luaV_tostring' may create a new string */
    if (!luaV_tostring(L, o)) {  /* conversion failed? */
      if (len != NULL) *len = 0;
      lua_unlock(L);
      return NULL;
    }
    luaC_checkGC(L);
    o = index2adr(L, idx);  /* previous call may reallocate the stack */
    lua_unlock(L);
  }
  if (len != NULL) *len = tsvalue(o)->len;
  return svalue(o);
}
References index2adr(), lua_lock, lua_unlock, luaC_checkGC, luaV_tostring(), NULL, svalue, tsvalue, and ttisstring.
Referenced by add_s(), add_s(), add_s(), add_s(), addliteral(), addliteral(), generic_reader(), generic_reader(), generic_reader(), generic_reader(), gmatch_aux(), gmatch_aux(), incomplete(), incomplete(), incomplete(), incomplete(), loadline(), log_access(), luaB_load(), luaB_load(), luaB_load(), luaB_print(), luaB_print(), luaB_tonumber(), luaB_tonumber(), luaL_addvalue(), luaL_checklstring(), luaL_checklstring(), luaL_tolstring(), multiline(), multiline(), and tonum().
lua_tonumber()
LUA_API lua_Number lua_tonumber (lua_State * L, int idx)
Definition at line 313 of file lua-5.1.5/src/lapi.c.
{
  TValue n;
  const TValue *o = index2adr(L, idx);
  if (tonumber(o, &n))
    return nvalue(o);
  else
    return 0;
}
References index2adr(), nvalue, and tonumber.
lua_topointer()
LUA_API const void * lua_topointer (lua_State * L, int idx)
Definition at line 401 of file lua-5.1.5/src/lapi.c.
{
  StkId o = index2adr(L, idx);
  switch (ttype(o)) {
    case LUA_TTABLE: return hvalue(o);
    case LUA_TFUNCTION: return clvalue(o);
    case LUA_TTHREAD: return thvalue(o);
    case LUA_TUSERDATA:
    case LUA_TLIGHTUSERDATA:
      return lua_touserdata(L, idx);
    default: return NULL;
  }
}
References clvalue, hvalue, index2adr(), LUA_TFUNCTION, LUA_TLIGHTUSERDATA, lua_touserdata(), LUA_TTABLE, LUA_TTHREAD, LUA_TUSERDATA, NULL, thvalue, and ttype.
Referenced by luaB_tostring(), luaL_tolstring(), print(), and str_format().
lua_tothread()
LUA_API lua_State * lua_tothread (lua_State * L, int idx)
Definition at line 395 of file lua-5.1.5/src/lapi.c.
{
  StkId o = index2adr(L, idx);
  return (!ttisthread(o)) ? NULL : thvalue(o);
}
References index2adr(), NULL, thvalue, and ttisthread.
Referenced by getco(), getco(), getthread(), getthread(), getthread(), getthread(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_coresume(), luaB_coresume(), luaB_costatus(), and luaB_costatus().
lua_touserdata()
LUA_API void * lua_touserdata (lua_State * L, int idx)
Definition at line 385 of file lua-5.1.5/src/lapi.c.
{
  StkId o = index2adr(L, idx);
  switch (ttype(o)) {
    case LUA_TUSERDATA: return (rawuvalue(o) + 1);
    case LUA_TLIGHTUSERDATA: return pvalue(o);
    default: return NULL;
  }
}
References index2adr(), LUA_TLIGHTUSERDATA, LUA_TUSERDATA, NULL, pvalue, rawuvalue, and ttype.
Referenced by checkclib(), checkclib(), cleanupdb(), db_close_vm(), db_tostring(), dir_close(), gctm(), gctm(), gctm(), getiofile(), getiofile(), getiofile(), getiofile(), gmatch_aux(), gmatch_aux(), io_readline(), io_readline(), io_readline(), io_readline(), io_type(), ll_checkclib(), ll_register(), ll_require(), lsqlite_open_ptr(), lua_topointer(), luaL_checkudata(), luaL_testudata(), math_random(), math_randomseed(), pmain(), pmain(), pmain(), pmain(), pmain(), pmain(), pmain(), pmain(), resizebox(), resizebox(), and Xml_eval().
lua_type()
LUA_API int lua_type (lua_State * L, int idx)
Definition at line 242 of file lua-5.1.5/src/lapi.c.
{
  StkId o = index2adr(L, idx);
  return (o == luaO_nilobject) ? LUA_TNONE : ttype(o);
}
References index2adr(), LUA_TNONE, luaO_nilobject, and ttype.
Referenced by add_value(), addliteral(), addliteral(), checktab(), checktab(), db_getuservalue(), db_getuservalue(), db_getuservalue(), db_setmetatable(), db_setmetatable(), db_setmetatable(), db_setmetatable(), db_setuservalue(), dbvm_bind_index(), finalreport(), findfield(), findfield(), findfield(), g_read(), g_read(), g_read(), g_read(), g_write(), g_write(), g_write(), g_write(), lcontext_result(), link_info(), log_access(), lua_isstring(), luaB_auxwrap(), luaB_auxwrap(), luaB_error(), luaB_error(), luaB_rawlen(), luaB_rawlen(), luaB_rawlen(), luaB_select(), luaB_select(), luaB_select(), luaB_select(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_tonumber(), luaB_tonumber(), luaB_tostring(), luaB_type(), luaB_type(), luaL_checkany(), luaL_checkany(), luaL_checktype(), luaL_checktype(), luaL_tolstring(), luaL_typeerror(), master_thread_run(), math_type(), math_type(), maxn(), msghandler(), msghandler(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), tonum(), trymt(), typeerror(), Xml_append(), Xml_iterate(), Xml_match(), Xml_new(), Xml_pushEncode(), Xml_str(), and Xml_tag().
lua_typename()
LUA_API const char * lua_typename (lua_State * L, int t)
Definition at line 248 of file lua-5.1.5/src/lapi.c.
{
  UNUSED(L);
  return (t == LUA_TNONE) ? "no value" : luaT_typenames[t];
}
References LUA_TNONE, luaT_typenames, and UNUSED.
Referenced by dbvm_bind_index(), lcontext_result(), luaB_type(), luaB_type(), tag_error(), tag_error(), tag_error(), tag_error(), and Xml_str().
lua_xmove()
LUA_API void lua_xmove (lua_State * from, lua_State * to, int n)
Definition at line 110 of file lua-5.1.5/src/lapi.c.
{
  int i;
  if (from == to) return;
  lua_lock(to);
  api_checknelems(from, n);
  api_check(from, G(from) == G(to));
  api_check(from, to->ci->top - to->top >= n);
  from->top -= n;
  for (i = 0; i < n; i++) {
    setobj2s(to, to->top++, from->top + i);
  }
  lua_unlock(to);
}
References api_check, api_checknelems, lua_State::ci, G, lua_lock, lua_unlock, setobj2s, CallInfo::top, and lua_State::top.
Referenced by auxresume(), auxresume(), auxresume(), auxresume(), db_gethook(), db_gethook(), db_gethook(), db_getinfo(), db_getinfo(), db_getinfo(), db_getinfo(), db_getlocal(), db_getlocal(), db_getlocal(), db_getlocal(), db_sethook(), db_sethook(), db_sethook(), db_setlocal(), db_setlocal(), db_setlocal(), db_setlocal(), luaB_auxwrap(), luaB_close(), luaB_cocreate(), luaB_cocreate(), luaB_cocreate(), luaB_cocreate(), treatstackoption(), treatstackoption(), treatstackoption(), and treatstackoption().
luaA_pushobject()
void luaA_pushobject (lua_State * L, const TValue * o)
Definition at line 89 of file lua-5.1.5/src/lapi.c.
{
  setobj2s(L, L->top, o);
  api_incr_top(L);
}
References api_incr_top, setobj2s, and lua_State::top.
Referenced by lua_getlocal().
Variable Documentation
lua_ident
const char lua_ident[]
Initial value:
=
  "$Lua: " LUA_RELEASE " " LUA_COPYRIGHT " $\n"
  "$Authors: " LUA_AUTHORS " $\n"
  "$URL: www.lua.org $\n"
Definition at line 34 of file lua-5.1.5/src/lapi.c.