Github User Fetcher: liolib.c File Reference
liolib.c File Reference
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define _LARGEFILE_SOURCE 1
#define _FILE_OFFSET_BITS 64
#define liolib_c
#define LUA_LIB
#define lua_checkmode(mode)
#define lua_popen(L, c, m)
#define lua_pclose(L, file) ((void)((void)L, file), -1)
#define l_fseek(f, o, w) fseek(f,o,w)
#define l_ftell(f) ftell(f)
#define l_seeknum long
#define IO_PREFIX "_IO_"
#define IO_INPUT (IO_PREFIX "input")
#define IO_OUTPUT (IO_PREFIX "output")
#define tolstream(L) ((LStream *)luaL_checkudata(L, 1, LUA_FILEHANDLE))
#define isclosed(p) ((p)->closef == NULL)
#define MAX_SIZE_T (~(size_t)0)
Typedefs
typedef luaL_Stream LStream
Functions
static int io_type (lua_State *L)
static int f_tostring (lua_State *L)
static FILE * tofile (lua_State *L)
static LStream * newprefile (lua_State *L)
static int aux_close (lua_State *L)
static int io_close (lua_State *L)
static int f_gc (lua_State *L)
static int io_fclose (lua_State *L)
static LStream * newfile (lua_State *L)
static void opencheck (lua_State *L, const char *fname, const char *mode)
static int io_open (lua_State *L)
static int io_pclose (lua_State *L)
static int io_popen (lua_State *L)
static int io_tmpfile (lua_State *L)
static FILE * getiofile (lua_State *L, const char *findex)
static int g_iofile (lua_State *L, const char *f, const char *mode)
static int io_input (lua_State *L)
static int io_output (lua_State *L)
static int io_readline (lua_State *L)
static void aux_lines (lua_State *L, int toclose)
static int f_lines (lua_State *L)
static int io_lines (lua_State *L)
static int read_number (lua_State *L, FILE *f)
static int test_eof (lua_State *L, FILE *f)
static int read_line (lua_State *L, FILE *f, int chop)
static void read_all (lua_State *L, FILE *f)
static int read_chars (lua_State *L, FILE *f, size_t n)
static int g_read (lua_State *L, FILE *f, int first)
static int io_read (lua_State *L)
static int f_read (lua_State *L)
static int g_write (lua_State *L, FILE *f, int arg)
static int io_write (lua_State *L)
static int f_write (lua_State *L)
static int f_seek (lua_State *L)
static int f_setvbuf (lua_State *L)
static int io_flush (lua_State *L)
static int f_flush (lua_State *L)
static void createmeta (lua_State *L)
static int io_noclose (lua_State *L)
static void createstdfile (lua_State *L, FILE *f, const char *k, const char *fname)
LUAMOD_API int luaopen_io (lua_State *L)
Variables
static const luaL_Reg iolib []
static const luaL_Reg flib []
Macro Definition Documentation
_FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64
Definition at line 14 of file lua-5.2.4/src/liolib.c.
_LARGEFILE_SOURCE
#define _LARGEFILE_SOURCE 1
Definition at line 13 of file lua-5.2.4/src/liolib.c.
IO_INPUT
#define IO_INPUT (IO_PREFIX "input")
Definition at line 118 of file lua-5.2.4/src/liolib.c.
Referenced by io_input(), io_lines(), io_read(), and luaopen_io().
IO_OUTPUT
#define IO_OUTPUT (IO_PREFIX "output")
Definition at line 119 of file lua-5.2.4/src/liolib.c.
Referenced by io_close(), io_flush(), io_output(), io_write(), and luaopen_io().
IO_PREFIX
#define IO_PREFIX "_IO_"
Definition at line 117 of file lua-5.2.4/src/liolib.c.
Referenced by getiofile().
isclosed
#define isclosed (p) ((p)->closef == NULL)
Definition at line 127 of file lua-5.2.4/src/liolib.c.
Referenced by f_gc(), f_tostring(), getiofile(), io_readline(), io_type(), and tofile().
l_fseek
#define l_fseek (f, o, w) fseek(f,o,w)
Definition at line 109 of file lua-5.2.4/src/liolib.c.
Referenced by f_seek().
l_ftell
#define l_ftell (f) ftell(f)
Definition at line 110 of file lua-5.2.4/src/liolib.c.
Referenced by f_seek().
l_seeknum
#define l_seeknum long
Definition at line 111 of file lua-5.2.4/src/liolib.c.
Referenced by f_seek().
liolib_c
#define liolib_c
Definition at line 23 of file lua-5.2.4/src/liolib.c.
lua_checkmode
#define lua_checkmode (mode)
Value:
    (*mode != '\0' && strchr("rwa", *(mode++)) != NULL &&   \
    (*mode != '+' || ++mode) &&  /* skip if char is '+' */  \
    (*mode != 'b' || ++mode) &&  /* skip if char is 'b' */  \
    (*mode == '\0'))
Definition at line 39 of file lua-5.2.4/src/liolib.c.
#define lua_checkmode(mode) \
    (*mode != '\0' && strchr("rwa", *(mode++)) != NULL &&   \
    (*mode != '+' || ++mode) &&  /* skip if char is '+' */  \
    (*mode != 'b' || ++mode) &&  /* skip if char is 'b' */  \
    (*mode == '\0'))
Referenced by io_open().
LUA_LIB
#define LUA_LIB
Definition at line 24 of file lua-5.2.4/src/liolib.c.
lua_pclose
#define lua_pclose (L, file) ((void)((void)L, file), -1)
Definition at line 71 of file lua-5.2.4/src/liolib.c.
Referenced by io_pclose().
lua_popen
#define lua_popen (L, c, m)
Value:
        ((void)((void)c, m),  \
        luaL_error(L, LUA_QL("popen") " not supported"), (FILE*)0)
Definition at line 69 of file lua-5.2.4/src/liolib.c.
#define lua_popen(L,c,m)        ((void)((void)c, m),  \
        luaL_error(L, LUA_QL("popen") " not supported"), (FILE*)0)
Referenced by io_popen().
MAX_SIZE_T
#define MAX_SIZE_T (~(size_t)0)
Definition at line 393 of file lua-5.2.4/src/liolib.c.
Referenced by read_all().
tolstream
#define tolstream (L) ((LStream *)luaL_checkudata(L, 1, LUA_FILEHANDLE))
Definition at line 125 of file lua-5.2.4/src/liolib.c.
Referenced by aux_close(), f_gc(), f_tostring(), io_fclose(), io_noclose(), io_pclose(), and tofile().
Typedef Documentation
LStream
typedef luaL_Stream LStream
Definition at line 122 of file lua-5.2.4/src/liolib.c.
Function Documentation
aux_close()
static int aux_close (lua_State * L) static
Definition at line 176 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = tolstream(L);
  lua_CFunction cf = p->closef;
  p->closef = NULL;  /* mark stream as closed */
  return (*cf)(L);  /* close it */
}
References luaL_Stream::closef, NULL, and tolstream.
Referenced by f_gc(), io_close(), and io_readline().
aux_lines()
static void aux_lines (lua_State * L, int toclose) static
Definition at line 303 of file lua-5.2.4/src/liolib.c.
{
  int i;
  int n = lua_gettop(L) - 1;  /* number of arguments to read */
  /* ensure that arguments will fit here and into 'io_readline' stack */
  luaL_argcheck(L, n <= LUA_MINSTACK - 3, LUA_MINSTACK - 3, "too many options");
  lua_pushvalue(L, 1);  /* file handle */
  lua_pushinteger(L, n);  /* number of arguments to read */
  lua_pushboolean(L, toclose);  /* close/not close file when finished */
  for (i = 1; i <= n; i++) lua_pushvalue(L, i + 1);  /* copy arguments */
  lua_pushcclosure(L, io_readline, 3 + n);
}
References io_readline(), lua_gettop(), LUA_MINSTACK, lua_pushboolean(), lua_pushcclosure(), lua_pushinteger(), lua_pushvalue(), and luaL_argcheck.
Referenced by f_lines(), and io_lines().
createmeta()
static void createmeta (lua_State * L) static
Definition at line 623 of file lua-5.2.4/src/liolib.c.
{
  luaL_newmetatable(L, LUA_FILEHANDLE);  /* create metatable for file handles */
  lua_pushvalue(L, -1);  /* push metatable */
  lua_setfield(L, -2, "__index");  /* metatable.__index = metatable */
  luaL_setfuncs(L, flib, 0);  /* add file methods to new metatable */
  lua_pop(L, 1);  /* pop new metatable */
}
References flib, LUA_FILEHANDLE, lua_pop, lua_pushvalue(), lua_setfield(), luaL_newmetatable(), and luaL_setfuncs().
Referenced by luaopen_io().
createstdfile()
static void createstdfile (lua_State * L, FILE * f, const char * k, const char * fname) static
Definition at line 644 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = newprefile(L);
  p->f = f;
  p->closef = &io_noclose;
  if (k != NULL) {
    lua_pushvalue(L, -1);
    lua_setfield(L, LUA_REGISTRYINDEX, k);  /* add file to registry */
  }
  lua_setfield(L, -2, fname);  /* add file to module */
}
References luaL_Stream::closef, luaL_Stream::f, io_noclose(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), newprefile(), and NULL.
Referenced by luaopen_io().
f_flush()
static int f_flush (lua_State * L) static
Definition at line 582 of file lua-5.2.4/src/liolib.c.
{
  return luaL_fileresult(L, fflush(tofile(L)) == 0, NULL);
}
References luaL_fileresult(), NULL, and tofile().
f_gc()
static int f_gc (lua_State * L) static
Definition at line 192 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = tolstream(L);
  if (!isclosed(p) && p->f != NULL)
    aux_close(L);  /* ignore closed and incompletely open files */
  return 0;
}
References aux_close(), luaL_Stream::f, isclosed, NULL, and tolstream.
f_lines()
static int f_lines (lua_State * L) static
Definition at line 316 of file lua-5.2.4/src/liolib.c.
{
  tofile(L);  /* check that it's a valid file handle */
  aux_lines(L, 0);
  return 1;
}
References aux_lines(), and tofile().
f_read()
static int f_read (lua_State * L) static
Definition at line 479 of file lua-5.2.4/src/liolib.c.
{
  return g_read(L, tofile(L), 2);
}
References g_read(), and tofile().
f_seek()
static int f_seek (lua_State * L) static
Definition at line 546 of file lua-5.2.4/src/liolib.c.
{
  static const int mode[] = {SEEK_SET, SEEK_CUR, SEEK_END};
  static const char *const modenames[] = {"set", "cur", "end", NULL};
  FILE *f = tofile(L);
  int op = luaL_checkoption(L, 2, "cur", modenames);
  lua_Number p3 = luaL_optnumber(L, 3, 0);
  l_seeknum offset = (l_seeknum)p3;
  luaL_argcheck(L, (lua_Number)offset == p3, 3,
                  "not an integer in proper range");
  op = l_fseek(f, offset, mode[op]);
  if (op)
    return luaL_fileresult(L, 0, NULL);  /* error */
  else {
    lua_pushnumber(L, (lua_Number)l_ftell(f));
    return 1;
  }
}
References l_fseek, l_ftell, l_seeknum, lua_pushnumber(), luaL_argcheck, luaL_checkoption(), luaL_fileresult(), luaL_optnumber(), NULL, and tofile().
f_setvbuf()
static int f_setvbuf (lua_State * L) static
Definition at line 565 of file lua-5.2.4/src/liolib.c.
{
  static const int mode[] = {_IONBF, _IOFBF, _IOLBF};
  static const char *const modenames[] = {"no", "full", "line", NULL};
  FILE *f = tofile(L);
  int op = luaL_checkoption(L, 2, NULL, modenames);
  lua_Integer sz = luaL_optinteger(L, 3, LUAL_BUFFERSIZE);
  int res = setvbuf(f, NULL, mode[op], sz);
  return luaL_fileresult(L, res == 0, NULL);
}
References LUAL_BUFFERSIZE, luaL_checkoption(), luaL_fileresult(), luaL_optinteger(), NULL, and tofile().
f_tostring()
static int f_tostring (lua_State * L) static
Definition at line 144 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = tolstream(L);
  if (isclosed(p))
    lua_pushliteral(L, "file (closed)");
  else
    lua_pushfstring(L, "file (%p)", p->f);
  return 1;
}
References luaL_Stream::f, isclosed, lua_pushfstring(), lua_pushliteral, and tolstream.
f_write()
static int f_write (lua_State * L) static
Definition at line 539 of file lua-5.2.4/src/liolib.c.
{
  FILE *f = tofile(L);
  lua_pushvalue(L, 1);  /* push file at the stack top (to be returned) */
  return g_write(L, f, 2);
}
References g_write(), lua_pushvalue(), and tofile().
g_iofile()
static int g_iofile (lua_State * L, const char * f, const char * mode) static
Definition at line 273 of file lua-5.2.4/src/liolib.c.
{
  if (!lua_isnoneornil(L, 1)) {
    const char *filename = lua_tostring(L, 1);
    if (filename)
      opencheck(L, filename, mode);
    else {
      tofile(L);  /* check that it's a valid file handle */
      lua_pushvalue(L, 1);
    }
    lua_setfield(L, LUA_REGISTRYINDEX, f);
  }
  /* return current value */
  lua_getfield(L, LUA_REGISTRYINDEX, f);
  return 1;
}
References lua_getfield(), lua_isnoneornil, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_tostring, opencheck(), and tofile().
Referenced by io_input(), and io_output().
g_read()
static int g_read (lua_State * L, FILE * f, int first) static
Definition at line 424 of file lua-5.2.4/src/liolib.c.
{
  int nargs = lua_gettop(L) - 1;
  int success;
  int n;
  clearerr(f);
  if (nargs == 0) {  /* no arguments? */
    success = read_line(L, f, 1);
    n = first+1;  /* to return 1 result */
  }
  else {  /* ensure stack space for all results and for auxlib's buffer */
    luaL_checkstack(L, nargs+LUA_MINSTACK, "too many arguments");
    success = 1;
    for (n = first; nargs-- && success; n++) {
      if (lua_type(L, n) == LUA_TNUMBER) {
        size_t l = (size_t)lua_tointeger(L, n);
        success = (l == 0) ? test_eof(L, f) : read_chars(L, f, l);
      }
      else {
        const char *p = lua_tostring(L, n);
        luaL_argcheck(L, p && p[0] == '*', n, "invalid option");
        switch (p[1]) {
          case 'n':  /* number */
            success = read_number(L, f);
            break;
          case 'l':  /* line */
            success = read_line(L, f, 1);
            break;
          case 'L':  /* line with end-of-line */
            success = read_line(L, f, 0);
            break;
          case 'a':  /* file */
            read_all(L, f);  /* read entire file */
            success = 1; /* always success */
            break;
          default:
            return luaL_argerror(L, n, "invalid format");
        }
      }
    }
  }
  if (ferror(f))
    return luaL_fileresult(L, 0, NULL);
  if (!success) {
    lua_pop(L, 1);  /* remove last result */
    lua_pushnil(L);  /* push nil instead */
  }
  return n - first;
}
References lua_gettop(), LUA_MINSTACK, lua_pop, lua_pushnil(), LUA_TNUMBER, lua_tointeger, lua_tostring, lua_type(), luaL_argcheck, luaL_argerror(), luaL_checkstack(), luaL_fileresult(), NULL, read_all(), read_chars(), read_line(), read_number(), and test_eof().
Referenced by f_read(), io_read(), and io_readline().
g_write()
static int g_write (lua_State * L, FILE * f, int arg) static
Definition at line 514 of file lua-5.2.4/src/liolib.c.
{
  int nargs = lua_gettop(L) - arg;
  int status = 1;
  for (; nargs--; arg++) {
    if (lua_type(L, arg) == LUA_TNUMBER) {
      /* optimization: could be done exactly as for strings */
      status = status &&
          fprintf(f, LUA_NUMBER_FMT, lua_tonumber(L, arg)) > 0;
    }
    else {
      size_t l;
      const char *s = luaL_checklstring(L, arg, &l);
      status = status && (fwrite(s, sizeof(char), l, f) == l);
    }
  }
  if (status) return 1;  /* file handle already on stack top */
  else return luaL_fileresult(L, status, NULL);
}
References arg, fwrite(), lua_gettop(), LUA_NUMBER_FMT, LUA_TNUMBER, lua_tonumber, lua_type(), luaL_checklstring(), luaL_fileresult(), NULL, and s.
Referenced by f_write(), and io_write().
getiofile()
static FILE * getiofile (lua_State * L, const char * findex) static
Definition at line 263 of file lua-5.2.4/src/liolib.c.
{
  LStream *p;
  lua_getfield(L, LUA_REGISTRYINDEX, findex);
  p = (LStream *)lua_touserdata(L, -1);
  if (isclosed(p))
    luaL_error(L, "standard %s file is closed", findex + strlen(IO_PREFIX));
  return p->f;
}
References luaL_Stream::f, IO_PREFIX, isclosed, lua_getfield(), LUA_REGISTRYINDEX, lua_touserdata(), and luaL_error().
Referenced by io_flush(), io_read(), and io_write().
io_close()
static int io_close (lua_State * L) static
Definition at line 184 of file lua-5.2.4/src/liolib.c.
{
  if (lua_isnone(L, 1))  /* no argument? */
    lua_getfield(L, LUA_REGISTRYINDEX, IO_OUTPUT);  /* use standard output */
  tofile(L);  /* make sure argument is an open stream */
  return aux_close(L);
}
References aux_close(), IO_OUTPUT, lua_getfield(), lua_isnone, LUA_REGISTRYINDEX, and tofile().
io_fclose()
static int io_fclose (lua_State * L) static
Definition at line 203 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = tolstream(L);
  int res = fclose(p->f);
  return luaL_fileresult(L, (res == 0), NULL);
}
References luaL_Stream::f, luaL_fileresult(), NULL, and tolstream.
Referenced by newfile().
io_flush()
static int io_flush (lua_State * L) static
Definition at line 577 of file lua-5.2.4/src/liolib.c.
{
  return luaL_fileresult(L, fflush(getiofile(L, IO_OUTPUT)) == 0, NULL);
}
References getiofile(), IO_OUTPUT, luaL_fileresult(), and NULL.
io_input()
static int io_input (lua_State * L) static
Definition at line 290 of file lua-5.2.4/src/liolib.c.
{
  return g_iofile(L, IO_INPUT, "r");
}
References g_iofile(), and IO_INPUT.
io_lines()
static int io_lines (lua_State * L) static
Definition at line 323 of file lua-5.2.4/src/liolib.c.
{
  int toclose;
  if (lua_isnone(L, 1)) lua_pushnil(L);  /* at least one argument */
  if (lua_isnil(L, 1)) {  /* no file name? */
    lua_getfield(L, LUA_REGISTRYINDEX, IO_INPUT);  /* get default input */
    lua_replace(L, 1);  /* put it at index 1 */
    tofile(L);  /* check that it's a valid file handle */
    toclose = 0;  /* do not close it after iteration */
  }
  else {  /* open a new file */
    const char *filename = luaL_checkstring(L, 1);
    opencheck(L, filename, "r");
    lua_replace(L, 1);  /* put file at index 1 */
    toclose = 1;  /* close it after iteration */
  }
  aux_lines(L, toclose);
  return 1;
}
References aux_lines(), IO_INPUT, lua_getfield(), lua_isnil, lua_isnone, lua_pushnil(), LUA_REGISTRYINDEX, lua_replace, luaL_checkstring, opencheck(), and tofile().
io_noclose()
static int io_noclose (lua_State * L) static
Definition at line 635 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = tolstream(L);
  p->closef = &io_noclose;  /* keep file opened */
  lua_pushnil(L);
  lua_pushliteral(L, "cannot close standard file");
  return 2;
}
References luaL_Stream::closef, io_noclose(), lua_pushliteral, lua_pushnil(), and tolstream.
Referenced by createstdfile(), and io_noclose().
io_open()
static int io_open (lua_State * L) static
Definition at line 226 of file lua-5.2.4/src/liolib.c.
{
  const char *filename = luaL_checkstring(L, 1);
  const char *mode = luaL_optstring(L, 2, "r");
  LStream *p = newfile(L);
  const char *md = mode;  /* to traverse/check mode */
  luaL_argcheck(L, lua_checkmode(md), 2, "invalid mode");
  p->f = fopen(filename, mode);
  return (p->f == NULL) ? luaL_fileresult(L, 0, filename) : 1;
}
References luaL_Stream::f, lua_checkmode, luaL_argcheck, luaL_checkstring, luaL_fileresult(), luaL_optstring, newfile(), and NULL.
io_output()
static int io_output (lua_State * L) static
Definition at line 295 of file lua-5.2.4/src/liolib.c.
{
  return g_iofile(L, IO_OUTPUT, "w");
}
References g_iofile(), and IO_OUTPUT.
io_pclose()
static int io_pclose (lua_State * L) static
Definition at line 240 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = tolstream(L);
  return luaL_execresult(L, lua_pclose(L, p->f));
}
References luaL_Stream::f, lua_pclose, luaL_execresult(), and tolstream.
Referenced by io_popen().
io_popen()
static int io_popen (lua_State * L) static
Definition at line 246 of file lua-5.2.4/src/liolib.c.
{
  const char *filename = luaL_checkstring(L, 1);
  const char *mode = luaL_optstring(L, 2, "r");
  LStream *p = newprefile(L);
  p->f = lua_popen(L, filename, mode);
  p->closef = &io_pclose;
  return (p->f == NULL) ? luaL_fileresult(L, 0, filename) : 1;
}
References luaL_Stream::closef, luaL_Stream::f, io_pclose(), lua_popen, luaL_checkstring, luaL_fileresult(), luaL_optstring, newprefile(), and NULL.
io_read()
static int io_read (lua_State * L) static
Definition at line 474 of file lua-5.2.4/src/liolib.c.
{
  return g_read(L, getiofile(L, IO_INPUT), 1);
}
References g_read(), getiofile(), and IO_INPUT.
io_readline()
static int io_readline (lua_State * L) static
Definition at line 484 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = (LStream *)lua_touserdata(L, lua_upvalueindex(1));
  int i;
  int n = (int)lua_tointeger(L, lua_upvalueindex(2));
  if (isclosed(p))  /* file is already closed? */
    return luaL_error(L, "file is already closed");
  lua_settop(L , 1);
  for (i = 1; i <= n; i++)  /* push arguments to 'g_read' */
    lua_pushvalue(L, lua_upvalueindex(3 + i));
  n = g_read(L, p->f, 2);  /* 'n' is number of results */
  lua_assert(n > 0);  /* should return at least a nil */
  if (!lua_isnil(L, -n))  /* read at least one value? */
    return n;  /* return them */
  else {  /* first result is nil: EOF or error */
    if (n > 1) {  /* is there error information? */
      /* 2nd result is error message */
      return luaL_error(L, "%s", lua_tostring(L, -n + 1));
    }
    if (lua_toboolean(L, lua_upvalueindex(3))) {  /* generator created file? */
      lua_settop(L, 0);
      lua_pushvalue(L, lua_upvalueindex(1));
      aux_close(L);  /* close it */
    }
    return 0;
  }
}
References aux_close(), luaL_Stream::f, g_read(), isclosed, lua_assert, lua_isnil, lua_pushvalue(), lua_settop(), lua_toboolean(), lua_tointeger, lua_tostring, lua_touserdata(), lua_upvalueindex, and luaL_error().
Referenced by aux_lines().
io_tmpfile()
static int io_tmpfile (lua_State * L) static
Definition at line 256 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = newfile(L);
  p->f = tmpfile();
  return (p->f == NULL) ? luaL_fileresult(L, 0, NULL) : 1;
}
References luaL_Stream::f, luaL_fileresult(), newfile(), and NULL.
io_type()
static int io_type (lua_State * L) static
Definition at line 130 of file lua-5.2.4/src/liolib.c.
{
  LStream *p;
  luaL_checkany(L, 1);
  p = (LStream *)luaL_testudata(L, 1, LUA_FILEHANDLE);
  if (p == NULL)
    lua_pushnil(L);  /* not a file */
  else if (isclosed(p))
    lua_pushliteral(L, "closed file");
  else
    lua_pushliteral(L, "file");
  return 1;
}
References isclosed, LUA_FILEHANDLE, lua_pushliteral, lua_pushnil(), luaL_checkany(), luaL_testudata(), and NULL.
io_write()
static int io_write (lua_State * L) static
Definition at line 534 of file lua-5.2.4/src/liolib.c.
{
  return g_write(L, getiofile(L, IO_OUTPUT), 1);
}
References g_write(), getiofile(), and IO_OUTPUT.
luaopen_io()
LUAMOD_API int luaopen_io (lua_State * L)
Definition at line 657 of file lua-5.2.4/src/liolib.c.
{
  luaL_newlib(L, iolib);  /* new module */
  createmeta(L);
  /* create (and set) default files */
  createstdfile(L, stdin, IO_INPUT, "stdin");
  createstdfile(L, stdout, IO_OUTPUT, "stdout");
  createstdfile(L, stderr, NULL, "stderr");
  return 1;
}
References createmeta(), createstdfile(), IO_INPUT, IO_OUTPUT, iolib, luaL_newlib, and NULL.
newfile()
static LStream * newfile (lua_State * L) static
Definition at line 210 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = newprefile(L);
  p->f = NULL;
  p->closef = &io_fclose;
  return p;
}
References luaL_Stream::closef, luaL_Stream::f, io_fclose(), newprefile(), and NULL.
Referenced by io_open(), io_tmpfile(), and opencheck().
newprefile()
static LStream * newprefile (lua_State * L) static
Definition at line 168 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = (LStream *)lua_newuserdata(L, sizeof(LStream));
  p->closef = NULL;  /* mark file handle as 'closed' */
  luaL_setmetatable(L, LUA_FILEHANDLE);
  return p;
}
References luaL_Stream::closef, LUA_FILEHANDLE, lua_newuserdata, luaL_setmetatable(), and NULL.
Referenced by createstdfile(), io_popen(), and newfile().
opencheck()
static void opencheck (lua_State * L, const char * fname, const char * mode) static
Definition at line 218 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = newfile(L);
  p->f = fopen(fname, mode);
  if (p->f == NULL)
    luaL_error(L, "cannot open file " LUA_QS " (%s)", fname, strerror(errno));
}
References luaL_Stream::f, LUA_QS, luaL_error(), newfile(), and NULL.
Referenced by g_iofile(), and io_lines().
read_all()
static void read_all (lua_State * L, FILE * f) static
Definition at line 395 of file lua-5.2.4/src/liolib.c.
{
  size_t rlen = LUAL_BUFFERSIZE;  /* how much to read in each cycle */
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  for (;;) {
    char *p = luaL_prepbuffsize(&b, rlen);
    size_t nr = fread(p, sizeof(char), rlen, f);
    luaL_addsize(&b, nr);
    if (nr < rlen) break;  /* eof? */
    else if (rlen <= (MAX_SIZE_T / 4))  /* avoid buffers too large */
      rlen *= 2;  /* double buffer size at each iteration */
  }
  luaL_pushresult(&b);  /* close buffer */
}
References fread(), luaL_addsize, LUAL_BUFFERSIZE, luaL_buffinit(), luaL_prepbuffsize(), luaL_pushresult(), and MAX_SIZE_T.
Referenced by g_read().
read_chars()
static int read_chars (lua_State * L, FILE * f, size_t n) static
Definition at line 411 of file lua-5.2.4/src/liolib.c.
{
  size_t nr;  /* number of chars actually read */
  char *p;
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  p = luaL_prepbuffsize(&b, n);  /* prepare buffer to read whole block */
  nr = fread(p, sizeof(char), n, f);  /* try to read 'n' chars */
  luaL_addsize(&b, nr);
  luaL_pushresult(&b);  /* close buffer */
  return (nr > 0);  /* true iff read something */
}
References fread(), luaL_addsize, luaL_buffinit(), luaL_prepbuffsize(), and luaL_pushresult().
Referenced by g_read().
read_line()
static int read_line (lua_State * L, FILE * f, int chop) static
Definition at line 371 of file lua-5.2.4/src/liolib.c.
{
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  for (;;) {
    size_t l;
    char *p = luaL_prepbuffer(&b);
    if (fgets(p, LUAL_BUFFERSIZE, f) == NULL) {  /* eof? */
      luaL_pushresult(&b);  /* close buffer */
      return (lua_rawlen(L, -1) > 0);  /* check whether read something */
    }
    l = strlen(p);
    if (l == 0 || p[l-1] != '\n')
      luaL_addsize(&b, l);
    else {
      luaL_addsize(&b, l - chop);  /* chop 'eol' if needed */
      luaL_pushresult(&b);  /* close buffer */
      return 1;  /* read at least an `eol' */
    }
  }
}
References lua_rawlen, luaL_addsize, LUAL_BUFFERSIZE, luaL_buffinit(), luaL_prepbuffer, luaL_pushresult(), and NULL.
Referenced by g_read().
read_number()
static int read_number (lua_State * L, FILE * f) static
Definition at line 350 of file lua-5.2.4/src/liolib.c.
{
  lua_Number d;
  if (fscanf(f, LUA_NUMBER_SCAN, &d) == 1) {
    lua_pushnumber(L, d);
    return 1;
  }
  else {
   lua_pushnil(L);  /* "result" to be removed */
   return 0;  /* read fails */
  }
}
References LUA_NUMBER_SCAN, lua_pushnil(), and lua_pushnumber().
Referenced by g_read().
test_eof()
static int test_eof (lua_State * L, FILE * f) static
Definition at line 363 of file lua-5.2.4/src/liolib.c.
{
  int c = getc(f);
  ungetc(c, f);
  lua_pushlstring(L, NULL, 0);
  return (c != EOF);
}
References lua_pushlstring(), and NULL.
Referenced by g_read().
tofile()
static FILE * tofile (lua_State * L) static
Definition at line 154 of file lua-5.2.4/src/liolib.c.
{
  LStream *p = tolstream(L);
  if (isclosed(p))
    luaL_error(L, "attempt to use a closed file");
  lua_assert(p->f);
  return p->f;
}
References luaL_Stream::f, isclosed, lua_assert, luaL_error(), and tolstream.
Referenced by f_flush(), f_lines(), f_read(), f_seek(), f_setvbuf(), f_write(), g_iofile(), io_close(), and io_lines().
Variable Documentation
flib
const luaL_Reg flib[] static
Initial value:
= {
  {"close", io_close},
  {"flush", f_flush},
  {"lines", f_lines},
  {"read", f_read},
  {"seek", f_seek},
  {"setvbuf", f_setvbuf},
  {"write", f_write},
  {"__gc", f_gc},
  {"__tostring", f_tostring},
  {NULL, NULL}
}
Definition at line 609 of file lua-5.2.4/src/liolib.c.
{
  {"close", io_close},
  {"flush", f_flush},
  {"lines", f_lines},
  {"read", f_read},
  {"seek", f_seek},
  {"setvbuf", f_setvbuf},
  {"write", f_write},
  {"__gc", f_gc},
  {"__tostring", f_tostring},
  {NULL, NULL}
};
Referenced by createmeta().
iolib
const luaL_Reg iolib[] static
Initial value:
= {
  {"close", io_close},
  {"flush", io_flush},
  {"input", io_input},
  {"lines", io_lines},
  {"open", io_open},
  {"output", io_output},
  {"popen", io_popen},
  {"read", io_read},
  {"tmpfile", io_tmpfile},
  {"type", io_type},
  {"write", io_write},
  {NULL, NULL}
}
Definition at line 590 of file lua-5.2.4/src/liolib.c.
{
  {"close", io_close},
  {"flush", io_flush},
  {"input", io_input},
  {"lines", io_lines},
  {"open", io_open},
  {"output", io_output},
  {"popen", io_popen},
  {"read", io_read},
  {"tmpfile", io_tmpfile},
  {"type", io_type},
  {"write", io_write},
  {NULL, NULL}
};
Referenced by luaopen_io().