Github User Fetcher: lfunc.c File Reference
lfunc.c File Reference
#include "lprefix.h"
#include <stddef.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
Macros
#define lfunc_c
#define LUA_CORE
#define MAXDELTA ((256ul << ((sizeof(L->stack->tbclist.delta) - 1) * 8)) - 1)
Functions
CClosure * luaF_newCclosure (lua_State *L, int nupvals)
LClosure * luaF_newLclosure (lua_State *L, int nupvals)
void luaF_initupvals (lua_State *L, LClosure *cl)
static UpVal * newupval (lua_State *L, int tbc, StkId level, UpVal **prev)
UpVal * luaF_findupval (lua_State *L, StkId level)
static void callclosemethod (lua_State *L, TValue *obj, TValue *err, int yy)
static void checkclosemth (lua_State *L, StkId level)
static void prepcallclosemth (lua_State *L, StkId level, int status, int yy)
void luaF_newtbcupval (lua_State *L, StkId level)
void luaF_unlinkupval (UpVal *uv)
void luaF_closeupval (lua_State *L, StkId level)
static void poptbclist (lua_State *L)
void luaF_close (lua_State *L, StkId level, int status, int yy)
Proto * luaF_newproto (lua_State *L)
void luaF_freeproto (lua_State *L, Proto *f)
const char * luaF_getlocalname (const Proto *f, int local_number, int pc)
Macro Definition Documentation
lfunc_c
#define lfunc_c
Definition at line 7 of file lua-5.4.3/src/lfunc.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/lfunc.c.
MAXDELTA
#define MAXDELTA ((256ul << ((sizeof(L->stack->tbclist.delta) - 1) * 8)) - 1)
Definition at line 162 of file lua-5.4.3/src/lfunc.c.
#define MAXDELTA  \
    ((256ul << ((sizeof(L->stack->tbclist.delta) - 1) * 8)) - 1)
Referenced by luaF_newtbcupval(), and poptbclist().
Function Documentation
callclosemethod()
static void callclosemethod (lua_State * L, TValue * obj, TValue * err, int yy) static
Definition at line 108 of file lua-5.4.3/src/lfunc.c.
{
  StkId top = L->top;
  const TValue *tm = luaT_gettmbyobj(L, obj, TM_CLOSE);
  setobj2s(L, top, tm);  /* will call metamethod... */
  setobj2s(L, top + 1, obj);  /* with 'self' as the 1st argument */
  setobj2s(L, top + 2, err);  /* and error msg. as 2nd argument */
  L->top = top + 3;  /* add function and arguments */
  if (yy)
    luaD_call(L, top, 0);
  else
    luaD_callnoyield(L, top, 0);
}
References luaD_call(), luaD_callnoyield(), luaT_gettmbyobj(), setobj2s, TM_CLOSE, and lua_State::top.
Referenced by prepcallclosemth().
checkclosemth()
static void checkclosemth (lua_State * L, StkId level) static
Definition at line 126 of file lua-5.4.3/src/lfunc.c.
{
  const TValue *tm = luaT_gettmbyobj(L, s2v(level), TM_CLOSE);
  if (ttisnil(tm)) {  /* no metamethod? */
    int idx = cast_int(level - L->ci->func);  /* variable index */
    const char *vname = luaG_findlocal(L, L->ci, idx, NULL);
    if (vname == NULL) vname = "?";
    luaG_runerror(L, "variable '%s' got a non-closable value", vname);
  }
}
References cast_int, lua_State::ci, CallInfo::func, luaG_findlocal(), luaG_runerror(), luaT_gettmbyobj(), NULL, s2v, TM_CLOSE, and ttisnil.
Referenced by luaF_newtbcupval().
luaF_close()
void luaF_close (lua_State * L, StkId level, int status, int yy)
Definition at line 228 of file lua-5.4.3/src/lfunc.c.
{
  ptrdiff_t levelrel = savestack(L, level);
  luaF_closeupval(L, level);  /* first, close the upvalues */
  while (L->tbclist >= level) {  /* traverse tbc's down to that level */
    StkId tbc = L->tbclist;  /* get variable index */
    poptbclist(L);  /* remove it from list */
    prepcallclosemth(L, tbc, status, yy);  /* close variable */
    level = restorestack(L, levelrel);
  }
}
References luaF_closeupval(), poptbclist(), prepcallclosemth(), restorestack, savestack, and lua_State::tbclist.
luaF_closeupval()
void luaF_closeupval (lua_State * L, StkId level)
Definition at line 194 of file lua-5.4.3/src/lfunc.c.
{
  UpVal *uv;
  StkId upl;  /* stack index pointed by 'uv' */
  while ((uv = L->openupval) != NULL && (upl = uplevel(uv)) >= level) {
    TValue *slot = &uv->u.value;  /* new position for value */
    lua_assert(uplevel(uv) < L->top);
    luaF_unlinkupval(uv);  /* remove upvalue from 'openupval' list */
    setobj(L, slot, uv->v);  /* move value to upvalue slot */
    uv->v = slot;  /* now current value lives here */
    if (!iswhite(uv)) {  /* neither white nor dead? */
      nw2black(uv);  /* closed upvalues cannot be gray */
      luaC_barrier(L, uv, slot);
    }
  }
}
References iswhite, lua_assert, luaC_barrier, luaF_unlinkupval(), NULL, nw2black, lua_State::openupval, setobj, lua_State::top, UpVal::u, uplevel, UpVal::v, and UpVal::value.
Referenced by luaE_freethread(), luaF_close(), and luaV_execute().
luaF_findupval()
UpVal * luaF_findupval (lua_State * L, StkId level)
Definition at line 88 of file lua-5.4.3/src/lfunc.c.
{
  UpVal **pp = &L->openupval;
  UpVal *p;
  lua_assert(isintwups(L) || L->openupval == NULL);
  while ((p = *pp) != NULL && uplevel(p) >= level) {  /* search for it */
    lua_assert(!isdead(G(L), p));
    if (uplevel(p) == level)  /* corresponding upvalue? */
      return p;  /* return it */
    pp = &p->u.open.next;
  }
  /* not found: create a new upvalue after 'pp' */
  return newupval(L, 0, level, pp);
}
References G, isdead, isintwups, lua_assert, newupval(), UpVal::next, NULL, UpVal::open, lua_State::openupval, UpVal::u, and uplevel.
luaF_freeproto()
void luaF_freeproto (lua_State * L, Proto * f)
Definition at line 267 of file lua-5.4.3/src/lfunc.c.
{
  luaM_freearray(L, f->code, f->sizecode);
  luaM_freearray(L, f->p, f->sizep);
  luaM_freearray(L, f->k, f->sizek);
  luaM_freearray(L, f->lineinfo, f->sizelineinfo);
  luaM_freearray(L, f->abslineinfo, f->sizeabslineinfo);
  luaM_freearray(L, f->locvars, f->sizelocvars);
  luaM_freearray(L, f->upvalues, f->sizeupvalues);
  luaM_free(L, f);
}
References Proto::abslineinfo, Proto::code, Proto::k, Proto::lineinfo, Proto::locvars, luaM_free, luaM_freearray, Proto::p, Proto::sizeabslineinfo, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, and Proto::upvalues.
luaF_getlocalname()
const char * luaF_getlocalname (const Proto * f, int local_number, int pc)
Definition at line 283 of file lua-5.4.3/src/lfunc.c.
{
  int i;
  for (i = 0; i<f->sizelocvars && f->locvars[i].startpc <= pc; i++) {
    if (pc < f->locvars[i].endpc) {  /* is variable active? */
      local_number--;
      if (local_number == 0)
        return getstr(f->locvars[i].varname);
    }
  }
  return NULL;  /* not found */
}
References getstr, Proto::locvars, NULL, Proto::sizelocvars, LocVar::startpc, and LocVar::varname.
luaF_initupvals()
void luaF_initupvals (lua_State * L, LClosure * cl)
Definition at line 48 of file lua-5.4.3/src/lfunc.c.
{
  int i;
  for (i = 0; i < cl->nupvalues; i++) {
    GCObject *o = luaC_newobj(L, LUA_VUPVAL, sizeof(UpVal));
    UpVal *uv = gco2upv(o);
    uv->v = &uv->u.value;  /* make it closed */
    setnilvalue(uv->v);
    cl->upvals[i] = uv;
    luaC_objbarrier(L, cl, uv);
  }
}
References gco2upv, LUA_VUPVAL, luaC_newobj(), luaC_objbarrier, setnilvalue, UpVal::u, LClosure::upvals, UpVal::v, and UpVal::value.
luaF_newCclosure()
CClosure * luaF_newCclosure (lua_State * L, int nupvals)
Definition at line 27 of file lua-5.4.3/src/lfunc.c.
{
  GCObject *o = luaC_newobj(L, LUA_VCCL, sizeCclosure(nupvals));
  CClosure *c = gco2ccl(o);
  c->nupvalues = cast_byte(nupvals);
  return c;
}
References cast_byte, gco2ccl, LUA_VCCL, luaC_newobj(), and sizeCclosure.
luaF_newLclosure()
LClosure * luaF_newLclosure (lua_State * L, int nupvals)
Definition at line 35 of file lua-5.4.3/src/lfunc.c.
{
  GCObject *o = luaC_newobj(L, LUA_VLCL, sizeLclosure(nupvals));
  LClosure *c = gco2lcl(o);
  c->p = NULL;
  c->nupvalues = cast_byte(nupvals);
  while (nupvals--) c->upvals[nupvals] = NULL;
  return c;
}
References cast_byte, gco2lcl, LUA_VLCL, luaC_newobj(), NULL, LClosure::p, sizeLclosure, and LClosure::upvals.
luaF_newproto()
Proto * luaF_newproto (lua_State * L)
Definition at line 240 of file lua-5.4.3/src/lfunc.c.
{
  GCObject *o = luaC_newobj(L, LUA_VPROTO, sizeof(Proto));
  Proto *f = gco2p(o);
  f->k = NULL;
  f->sizek = 0;
  f->p = NULL;
  f->sizep = 0;
  f->code = NULL;
  f->sizecode = 0;
  f->lineinfo = NULL;
  f->sizelineinfo = 0;
  f->abslineinfo = NULL;
  f->sizeabslineinfo = 0;
  f->upvalues = NULL;
  f->sizeupvalues = 0;
  f->numparams = 0;
  f->is_vararg = 0;
  f->maxstacksize = 0;
  f->locvars = NULL;
  f->sizelocvars = 0;
  f->linedefined = 0;
  f->lastlinedefined = 0;
  f->source = NULL;
  return f;
}
References Proto::abslineinfo, Proto::code, gco2p, Proto::is_vararg, Proto::k, Proto::lastlinedefined, Proto::linedefined, Proto::lineinfo, Proto::locvars, LUA_VPROTO, luaC_newobj(), Proto::maxstacksize, NULL, Proto::numparams, Proto::p, Proto::sizeabslineinfo, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, and Proto::upvalues.
luaF_newtbcupval()
void luaF_newtbcupval (lua_State * L, StkId level)
Definition at line 169 of file lua-5.4.3/src/lfunc.c.
{
  lua_assert(level > L->tbclist);
  if (l_isfalse(s2v(level)))
    return;  /* false doesn't need to be closed */
  checkclosemth(L, level);  /* value must have a close method */
  while (cast_uint(level - L->tbclist) > MAXDELTA) {
    L->tbclist += MAXDELTA;  /* create a dummy node at maximum delta */
    L->tbclist->tbclist.delta = 0;
  }
  level->tbclist.delta = cast(unsigned short, level - L->tbclist);
  L->tbclist = level;
}
References cast, cast_uint, checkclosemth(), l_isfalse, lua_assert, MAXDELTA, s2v, and lua_State::tbclist.
Referenced by lua_toclose(), and luaV_execute().
luaF_unlinkupval()
void luaF_unlinkupval (UpVal * uv)
Definition at line 183 of file lua-5.4.3/src/lfunc.c.
{
  lua_assert(upisopen(uv));
  *uv->u.open.previous = uv->u.open.next;
  if (uv->u.open.next)
    uv->u.open.next->u.open.previous = uv->u.open.previous;
}
References lua_assert, UpVal::next, UpVal::open, UpVal::previous, UpVal::u, and upisopen.
Referenced by freeupval(), and luaF_closeupval().
newupval()
static UpVal * newupval (lua_State * L, int tbc, StkId level, UpVal ** prev) static
Definition at line 65 of file lua-5.4.3/src/lfunc.c.
{
  GCObject *o = luaC_newobj(L, LUA_VUPVAL, sizeof(UpVal));
  UpVal *uv = gco2upv(o);
  UpVal *next = *prev;
  uv->v = s2v(level);  /* current value lives in the stack */
  uv->tbc = tbc;
  uv->u.open.next = next;  /* link it to list of open upvalues */
  uv->u.open.previous = prev;
  if (next)
    next->u.open.previous = &uv->u.open.next;
  *prev = uv;
  if (!isintwups(L)) {  /* thread not in list of threads with upvalues? */
    L->twups = G(L)->twups;  /* link it to the list */
    G(L)->twups = L;
  }
  return uv;
}
References G, gco2upv, isintwups, LUA_VUPVAL, luaC_newobj(), next, UpVal::next, UpVal::open, UpVal::previous, s2v, UpVal::tbc, lua_State::twups, UpVal::u, and UpVal::v.
Referenced by luaF_findupval().
poptbclist()
static void poptbclist (lua_State * L) static
Definition at line 214 of file lua-5.4.3/src/lfunc.c.
{
  StkId tbc = L->tbclist;
  lua_assert(tbc->tbclist.delta > 0);  /* first element cannot be dummy */
  tbc -= tbc->tbclist.delta;
  while (tbc > L->stack && tbc->tbclist.delta == 0)
    tbc -= MAXDELTA;  /* remove dummy nodes */
  L->tbclist = tbc;
}
References lua_assert, MAXDELTA, lua_State::stack, and lua_State::tbclist.
Referenced by luaF_close().
prepcallclosemth()
static void prepcallclosemth (lua_State * L, StkId level, int status, int yy) static
Definition at line 144 of file lua-5.4.3/src/lfunc.c.
{
  TValue *uv = s2v(level);  /* value being closed */
  TValue *errobj;
  if (status == CLOSEKTOP)
    errobj = &G(L)->nilvalue;  /* error object is nil */
  else {  /* 'luaD_seterrorobj' will set top to level + 2 */
    errobj = s2v(level + 1);  /* error object goes after 'uv' */
    luaD_seterrorobj(L, status, level + 1);  /* set error object */
  }
  callclosemethod(L, uv, errobj, yy);
}
References callclosemethod(), CLOSEKTOP, G, luaD_seterrorobj(), and s2v.
Referenced by luaF_close().