Github User Fetcher: lbitlib.c File Reference
lbitlib.c File Reference
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lbitlib_c
#define LUA_LIB
#define LUA_NBITS 32
#define ALLONES (~(((~(lua_Unsigned)0) << (LUA_NBITS - 1)) << 1))
#define trim(x) ((x) & ALLONES)
#define mask(n) (~((ALLONES << 1) << ((n) - 1)))
Typedefs
typedef lua_Unsigned b_uint
Functions
static b_uint andaux (lua_State *L)
static int b_and (lua_State *L)
static int b_test (lua_State *L)
static int b_or (lua_State *L)
static int b_xor (lua_State *L)
static int b_not (lua_State *L)
static int b_shift (lua_State *L, b_uint r, int i)
static int b_lshift (lua_State *L)
static int b_rshift (lua_State *L)
static int b_arshift (lua_State *L)
static int b_rot (lua_State *L, int i)
static int b_lrot (lua_State *L)
static int b_rrot (lua_State *L)
static int fieldargs (lua_State *L, int farg, int *width)
static int b_extract (lua_State *L)
static int b_replace (lua_State *L)
LUAMOD_API int luaopen_bit32 (lua_State *L)
Variables
static const luaL_Reg bitlib []
Macro Definition Documentation
ALLONES
#define ALLONES (~(((~(lua_Unsigned)0) << (LUA_NBITS - 1)) << 1))
Definition at line 22 of file lua-5.2.4/src/lbitlib.c.
Referenced by b_arshift().
lbitlib_c
#define lbitlib_c
Definition at line 7 of file lua-5.2.4/src/lbitlib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.2.4/src/lbitlib.c.
LUA_NBITS
#define LUA_NBITS 32
Definition at line 18 of file lua-5.2.4/src/lbitlib.c.
Referenced by b_arshift(), b_rot(), b_shift(), and fieldargs().
mask
#define mask (n) (~((ALLONES << 1) << ((n) - 1)))
Definition at line 29 of file lua-5.2.4/src/lbitlib.c.
Referenced by b_extract(), b_replace(), db_gethook(), db_gethook(), db_gethook(), db_gethook(), db_sethook(), db_sethook(), db_sethook(), db_sethook(), duk_bd_decode(), duk_check_type_mask(), exprSelectUsage(), g_bit_nth_lsf_impl(), g_bit_nth_msf_impl(), getinteger(), lua_sethook(), luaD_hook(), luaG_traceexec(), luaG_traceexec(), makemask(), makemask(), makemask(), makemask(), parse_match_net(), sqlite3FindInIndex(), sqlite3FkOldmask(), sqlite3GenerateRowDelete(), sqlite3InitOne(), sqlite3ParseUri(), sqlite3Pragma(), sqlite3TriggerColmask(), sqlite3TriggersExist(), sqlite3VdbeDeleteAuxData(), sqlite3WhereExprUsageNN(), traceexec(), traceexec(), unixModeBit(), unixShmLock(), unixShmSystemLock(), unmakemask(), unmakemask(), unmakemask(), unmakemask(), unpackint(), unpackint(), and whereRangeScanEst().
trim
#define trim (x) ((x) & ALLONES)
Definition at line 25 of file lua-5.2.4/src/lbitlib.c.
Referenced by andaux(), b_arshift(), b_not(), b_or(), b_rot(), b_shift(), b_xor(), and sqlite3RegisterBuiltinFunctions().
Typedef Documentation
b_uint
typedef lua_Unsigned b_uint
Definition at line 32 of file lua-5.2.4/src/lbitlib.c.
Function Documentation
andaux()
static b_uint andaux (lua_State * L) static
Definition at line 36 of file lua-5.2.4/src/lbitlib.c.
{
  int i, n = lua_gettop(L);
  b_uint r = ~(b_uint)0;
  for (i = 1; i <= n; i++)
    r &= luaL_checkunsigned(L, i);
  return trim(r);
}
References lua_gettop(), luaL_checkunsigned(), and trim.
Referenced by b_and(), and b_test().
b_and()
static int b_and (lua_State * L) static
Definition at line 45 of file lua-5.2.4/src/lbitlib.c.
{
  b_uint r = andaux(L);
  lua_pushunsigned(L, r);
  return 1;
}
References andaux(), and lua_pushunsigned().
b_arshift()
static int b_arshift (lua_State * L) static
Definition at line 113 of file lua-5.2.4/src/lbitlib.c.
{
  b_uint r = luaL_checkunsigned(L, 1);
  int i = luaL_checkint(L, 2);
  if (i < 0 || !(r & ((b_uint)1 << (LUA_NBITS - 1))))
    return b_shift(L, r, -i);
  else {  /* arithmetic shift for 'negative' number */
    if (i >= LUA_NBITS) r = ALLONES;
    else
      r = trim((r >> i) | ~(~(b_uint)0 >> i));  /* add signal bit */
    lua_pushunsigned(L, r);
    return 1;
  }
}
References ALLONES, b_shift(), LUA_NBITS, lua_pushunsigned(), luaL_checkint, luaL_checkunsigned(), and trim.
b_extract()
static int b_extract (lua_State * L) static
Definition at line 167 of file lua-5.2.4/src/lbitlib.c.
{
  int w;
  b_uint r = luaL_checkunsigned(L, 1);
  int f = fieldargs(L, 2, &w);
  r = (r >> f) & mask(w);
  lua_pushunsigned(L, r);
  return 1;
}
References fieldargs(), lua_pushunsigned(), luaL_checkunsigned(), and mask.
b_lrot()
static int b_lrot (lua_State * L) static
Definition at line 139 of file lua-5.2.4/src/lbitlib.c.
{
  return b_rot(L, luaL_checkint(L, 2));
}
References b_rot(), and luaL_checkint.
b_lshift()
static int b_lshift (lua_State * L) static
Definition at line 103 of file lua-5.2.4/src/lbitlib.c.
{
  return b_shift(L, luaL_checkunsigned(L, 1), luaL_checkint(L, 2));
}
References b_shift(), luaL_checkint, and luaL_checkunsigned().
b_not()
static int b_not (lua_State * L) static
Definition at line 79 of file lua-5.2.4/src/lbitlib.c.
{
  b_uint r = ~luaL_checkunsigned(L, 1);
  lua_pushunsigned(L, trim(r));
  return 1;
}
References lua_pushunsigned(), and trim.
b_or()
static int b_or (lua_State * L) static
Definition at line 59 of file lua-5.2.4/src/lbitlib.c.
{
  int i, n = lua_gettop(L);
  b_uint r = 0;
  for (i = 1; i <= n; i++)
    r |= luaL_checkunsigned(L, i);
  lua_pushunsigned(L, trim(r));
  return 1;
}
References lua_gettop(), lua_pushunsigned(), luaL_checkunsigned(), and trim.
b_replace()
static int b_replace (lua_State * L) static
Definition at line 177 of file lua-5.2.4/src/lbitlib.c.
{
  int w;
  b_uint r = luaL_checkunsigned(L, 1);
  b_uint v = luaL_checkunsigned(L, 2);
  int f = fieldargs(L, 3, &w);
  int m = mask(w);
  v &= m;  /* erase bits outside given width */
  r = (r & ~(m << f)) | (v << f);
  lua_pushunsigned(L, r);
  return 1;
}
References fieldargs(), lua_pushunsigned(), luaL_checkunsigned(), and mask.
b_rot()
static int b_rot (lua_State * L, int i) static
Definition at line 128 of file lua-5.2.4/src/lbitlib.c.
{
  b_uint r = luaL_checkunsigned(L, 1);
  i &= (LUA_NBITS - 1);  /* i = i % NBITS */
  r = trim(r);
  if (i != 0)  /* avoid undefined shift of LUA_NBITS when i == 0 */
    r = (r << i) | (r >> (LUA_NBITS - i));
  lua_pushunsigned(L, trim(r));
  return 1;
}
References LUA_NBITS, lua_pushunsigned(), luaL_checkunsigned(), and trim.
Referenced by b_lrot(), and b_rrot().
b_rrot()
static int b_rrot (lua_State * L) static
Definition at line 144 of file lua-5.2.4/src/lbitlib.c.
{
  return b_rot(L, -luaL_checkint(L, 2));
}
References b_rot(), and luaL_checkint.
b_rshift()
static int b_rshift (lua_State * L) static
Definition at line 108 of file lua-5.2.4/src/lbitlib.c.
{
  return b_shift(L, luaL_checkunsigned(L, 1), -luaL_checkint(L, 2));
}
References b_shift(), luaL_checkint, and luaL_checkunsigned().
b_shift()
static int b_shift (lua_State * L, b_uint r, int i) static
Definition at line 86 of file lua-5.2.4/src/lbitlib.c.
{
  if (i < 0) {  /* shift right? */
    i = -i;
    r = trim(r);
    if (i >= LUA_NBITS) r = 0;
    else r >>= i;
  }
  else {  /* shift left */
    if (i >= LUA_NBITS) r = 0;
    else r <<= i;
    r = trim(r);
  }
  lua_pushunsigned(L, r);
  return 1;
}
References LUA_NBITS, lua_pushunsigned(), and trim.
Referenced by b_arshift(), b_lshift(), and b_rshift().
b_test()
static int b_test (lua_State * L) static
Definition at line 52 of file lua-5.2.4/src/lbitlib.c.
{
  b_uint r = andaux(L);
  lua_pushboolean(L, r != 0);
  return 1;
}
References andaux(), and lua_pushboolean().
b_xor()
static int b_xor (lua_State * L) static
Definition at line 69 of file lua-5.2.4/src/lbitlib.c.
{
  int i, n = lua_gettop(L);
  b_uint r = 0;
  for (i = 1; i <= n; i++)
    r ^= luaL_checkunsigned(L, i);
  lua_pushunsigned(L, trim(r));
  return 1;
}
References lua_gettop(), lua_pushunsigned(), luaL_checkunsigned(), and trim.
fieldargs()
static int fieldargs (lua_State * L, int farg, int * width) static
Definition at line 155 of file lua-5.2.4/src/lbitlib.c.
{
  int f = luaL_checkint(L, farg);
  int w = luaL_optint(L, farg + 1, 1);
  luaL_argcheck(L, 0 <= f, farg, "field cannot be negative");
  luaL_argcheck(L, 0 < w, farg + 1, "width must be positive");
  if (f + w > LUA_NBITS)
    luaL_error(L, "trying to access non-existent bits");
  *width = w;
  return f;
}
References LUA_NBITS, luaL_argcheck, luaL_checkint, luaL_error(), and luaL_optint.
Referenced by b_extract(), and b_replace().
luaopen_bit32()
LUAMOD_API int luaopen_bit32 (lua_State * L)
Definition at line 208 of file lua-5.2.4/src/lbitlib.c.
{
  luaL_newlib(L, bitlib);
  return 1;
}
References bitlib, and luaL_newlib.
Variable Documentation
bitlib
const luaL_Reg bitlib[] static
Initial value:
= {
  {"arshift", b_arshift},
  {"band", b_and},
  {"bnot", b_not},
  {"bor", b_or},
  {"bxor", b_xor},
  {"btest", b_test},
  {"extract", b_extract},
  {"lrotate", b_lrot},
  {"lshift", b_lshift},
  {"replace", b_replace},
  {"rrotate", b_rrot},
  {"rshift", b_rshift},
  {NULL, NULL}
}
Definition at line 190 of file lua-5.2.4/src/lbitlib.c.
{
  {"arshift", b_arshift},
  {"band", b_and},
  {"bnot", b_not},
  {"bor", b_or},
  {"bxor", b_xor},
  {"btest", b_test},
  {"extract", b_extract},
  {"lrotate", b_lrot},
  {"lshift", b_lshift},
  {"replace", b_replace},
  {"rrotate", b_rrot},
  {"rshift", b_rshift},
  {NULL, NULL}
};
Referenced by luaopen_bit32().