Github User Fetcher: ltable.c File Reference
ltable.c File Reference
#include "lprefix.h"
#include <math.h>
#include <limits.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "lvm.h"
Macros
#define ltable_c
#define LUA_CORE
#define MAXABITS cast_int(sizeof(int) * CHAR_BIT - 1)
#define MAXASIZE luaM_limitN(1u << MAXABITS, TValue)
#define MAXHBITS (MAXABITS - 1)
#define MAXHSIZE luaM_limitN(1u << MAXHBITS, Node)
#define hashpow2(t, n) (gnode(t, lmod((n), sizenode(t))))
#define hashmod(t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
#define hashstr(t, str) hashpow2(t, (str)->hash)
#define hashboolean(t, p) hashpow2(t, p)
#define hashint(t, i) hashpow2(t, i)
#define hashpointer(t, p) hashmod(t, point2uint(p))
#define dummynode (&dummynode_)
#define limitequalsasize(t) (isrealasize(t) || ispow2((t)->alimit))
#define limitasasize(t) check_exp(isrealasize(t), t->alimit)
Functions
static int l_hashfloat (lua_Number n)
static Node * mainposition (const Table *t, int ktt, const Value *kvl)
static Node * mainpositionTV (const Table *t, const TValue *key)
static int equalkey (const TValue *k1, const Node *n2, int deadok)
LUAI_FUNC unsigned int luaH_realasize (const Table *t)
static int ispow2realasize (const Table *t)
static unsigned int setlimittosize (Table *t)
static const TValue * getgeneric (Table *t, const TValue *key, int deadok)
static unsigned int arrayindex (lua_Integer k)
static unsigned int findindex (lua_State *L, Table *t, TValue *key, unsigned int asize)
int luaH_next (lua_State *L, Table *t, StkId key)
static void freehash (lua_State *L, Table *t)
static unsigned int computesizes (unsigned int nums[], unsigned int *pna)
static int countint (lua_Integer key, unsigned int *nums)
static unsigned int numusearray (const Table *t, unsigned int *nums)
static int numusehash (const Table *t, unsigned int *nums, unsigned int *pna)
static void setnodevector (lua_State *L, Table *t, unsigned int size)
static void reinsert (lua_State *L, Table *ot, Table *t)
static void exchangehashpart (Table *t1, Table *t2)
void luaH_resize (lua_State *L, Table *t, unsigned int newasize, unsigned int nhsize)
void luaH_resizearray (lua_State *L, Table *t, unsigned int nasize)
static void rehash (lua_State *L, Table *t, const TValue *ek)
Table * luaH_new (lua_State *L)
void luaH_free (lua_State *L, Table *t)
static Node * getfreepos (Table *t)
void luaH_newkey (lua_State *L, Table *t, const TValue *key, TValue *value)
const TValue * luaH_getint (Table *t, lua_Integer key)
const TValue * luaH_getshortstr (Table *t, TString *key)
const TValue * luaH_getstr (Table *t, TString *key)
const TValue * luaH_get (Table *t, const TValue *key)
void luaH_finishset (lua_State *L, Table *t, const TValue *key, const TValue *slot, TValue *value)
void luaH_set (lua_State *L, Table *t, const TValue *key, TValue *value)
void luaH_setint (lua_State *L, Table *t, lua_Integer key, TValue *value)
static lua_Unsigned hash_search (Table *t, lua_Unsigned j)
static unsigned int binsearch (const TValue *array, unsigned int i, unsigned int j)
lua_Unsigned luaH_getn (Table *t)
Variables
static const Node dummynode_
static const TValue absentkey = {ABSTKEYCONSTANT}
Macro Definition Documentation
dummynode
#define dummynode (&dummynode_)
Definition at line 93 of file lua-5.4.3/src/ltable.c.
Referenced by setnodevector().
hashboolean
#define hashboolean (t, p) hashpow2(t, p)
Definition at line 85 of file lua-5.4.3/src/ltable.c.
Referenced by mainposition().
hashint
#define hashint (t, i) hashpow2(t, i)
Definition at line 87 of file lua-5.4.3/src/ltable.c.
Referenced by luaH_getint(), and mainposition().
hashmod
#define hashmod (t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
Definition at line 81 of file lua-5.4.3/src/ltable.c.
Referenced by mainposition().
hashpointer
#define hashpointer (t, p) hashmod(t, point2uint(p))
Definition at line 90 of file lua-5.4.3/src/ltable.c.
Referenced by mainposition().
hashpow2
#define hashpow2 (t, n) (gnode(t, lmod((n), sizenode(t))))
Definition at line 75 of file lua-5.4.3/src/ltable.c.
Referenced by mainposition().
hashstr
#define hashstr (t, str) hashpow2(t, (str)->hash)
Definition at line 84 of file lua-5.4.3/src/ltable.c.
Referenced by luaH_getshortstr(), and mainposition().
limitasasize
#define limitasasize (t) check_exp(isrealasize(t), t->alimit)
Definition at line 279 of file lua-5.4.3/src/ltable.c.
Referenced by numusearray().
limitequalsasize
#define limitequalsasize (t) (isrealasize(t) || ispow2((t)->alimit))
Definition at line 235 of file lua-5.4.3/src/ltable.c.
Referenced by luaH_getint(), luaH_getn(), and luaH_realasize().
ltable_c
#define ltable_c
Definition at line 7 of file lua-5.4.3/src/ltable.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/ltable.c.
MAXABITS
#define MAXABITS cast_int(sizeof(int) * CHAR_BIT - 1)
Definition at line 46 of file lua-5.4.3/src/ltable.c.
Referenced by numusearray(), and rehash().
MAXASIZE
#define MAXASIZE luaM_limitN(1u << MAXABITS, TValue)
Definition at line 54 of file lua-5.4.3/src/ltable.c.
Referenced by arrayindex().
MAXHBITS
#define MAXHBITS (MAXABITS - 1)
Definition at line 60 of file lua-5.4.3/src/ltable.c.
Referenced by setnodevector().
MAXHSIZE
#define MAXHSIZE luaM_limitN(1u << MAXHBITS, Node)
Definition at line 68 of file lua-5.4.3/src/ltable.c.
Referenced by setnodevector().
Function Documentation
arrayindex()
static unsigned int arrayindex (lua_Integer k) static
Definition at line 307 of file lua-5.4.3/src/ltable.c.
{
  if (l_castS2U(k) - 1u < MAXASIZE)  /* 'k' in [1, MAXASIZE]? */
    return cast_uint(k);  /* 'key' is an appropriate array index */
  else
    return 0;
}
References cast_uint, l_castS2U, and MAXASIZE.
Referenced by countint(), and findindex().
binsearch()
static unsigned int binsearch (const TValue * array, unsigned int i, unsigned int j) static
Definition at line 869 of file lua-5.4.3/src/ltable.c.
{
  while (j - i > 1u) {  /* binary search */
    unsigned int m = (i + j) / 2;
    if (isempty(&array[m - 1])) j = m;
    else i = m;
  }
  return i;
}
References isempty.
Referenced by luaH_getn().
computesizes()
static unsigned int computesizes (unsigned int nums[], unsigned int * pna) static
Definition at line 380 of file lua-5.4.3/src/ltable.c.
{
  int i;
  unsigned int twotoi;  /* 2^i (candidate for optimal size) */
  unsigned int a = 0;  /* number of elements smaller than 2^i */
  unsigned int na = 0;  /* number of elements to go to array part */
  unsigned int optimal = 0;  /* optimal size for array part */
  /* loop while keys can fill more than half of total size */
  for (i = 0, twotoi = 1;
       twotoi > 0 && *pna > twotoi / 2;
       i++, twotoi *= 2) {
    a += nums[i];
    if (a > twotoi/2) {  /* more than half elements present? */
      optimal = twotoi;  /* optimal size (till now) */
      na = a;  /* all elements up to 'optimal' will go to array part */
    }
  }
  lua_assert((optimal == 0 || optimal / 2 < na) && na <= optimal);
  *pna = na;
  return optimal;
}
References lua_assert.
Referenced by rehash().
countint()
static int countint (lua_Integer key, unsigned int * nums) static
Definition at line 402 of file lua-5.4.3/src/ltable.c.
{
  unsigned int k = arrayindex(key);
  if (k != 0) {  /* is 'key' an appropriate array index? */
    nums[luaO_ceillog2(k)]++;  /* count as such */
    return 1;
  }
  else
    return 0;
}
References arrayindex(), and luaO_ceillog2().
Referenced by numusehash(), and rehash().
equalkey()
static int equalkey (const TValue * k1, const Node * n2, int deadok) static
Definition at line 207 of file lua-5.4.3/src/ltable.c.
{
  if ((rawtt(k1) != keytt(n2)) &&  /* not the same variants? */
       !(deadok && keyisdead(n2) && iscollectable(k1)))
   return 0;  /* cannot be same key */
  switch (keytt(n2)) {
    case LUA_VNIL: case LUA_VFALSE: case LUA_VTRUE:
      return 1;
    case LUA_VNUMINT:
      return (ivalue(k1) == keyival(n2));
    case LUA_VNUMFLT:
      return luai_numeq(fltvalue(k1), fltvalueraw(keyval(n2)));
    case LUA_VLIGHTUSERDATA:
      return pvalue(k1) == pvalueraw(keyval(n2));
    case LUA_VLCF:
      return fvalue(k1) == fvalueraw(keyval(n2));
    case ctb(LUA_VLNGSTR):
      return luaS_eqlngstr(tsvalue(k1), keystrval(n2));
    default:
      return gcvalue(k1) == gcvalueraw(keyval(n2));
  }
}
References ctb, fltvalue, fltvalueraw, fvalue, fvalueraw, gcvalue, gcvalueraw, iscollectable, ivalue, keyisdead, keyival, keystrval, keytt, keyval, LUA_VFALSE, LUA_VLCF, LUA_VLIGHTUSERDATA, LUA_VLNGSTR, LUA_VNIL, LUA_VNUMFLT, LUA_VNUMINT, LUA_VTRUE, luai_numeq, luaS_eqlngstr(), pvalue, pvalueraw, rawtt, and tsvalue.
Referenced by getgeneric().
exchangehashpart()
static void exchangehashpart (Table * t1, Table * t2) static
Definition at line 516 of file lua-5.4.3/src/ltable.c.
{
  lu_byte lsizenode = t1->lsizenode;
  Node *node = t1->node;
  Node *lastfree = t1->lastfree;
  t1->lsizenode = t2->lsizenode;
  t1->node = t2->node;
  t1->lastfree = t2->lastfree;
  t2->lsizenode = lsizenode;
  t2->node = node;
  t2->lastfree = lastfree;
}
References Table::lastfree, Table::lsizenode, and Table::node.
Referenced by luaH_resize().
findindex()
static unsigned int findindex (lua_State * L, Table * t, TValue * key, unsigned int asize) static
Definition at line 320 of file lua-5.4.3/src/ltable.c.
{
  unsigned int i;
  if (ttisnil(key)) return 0;  /* first iteration */
  i = ttisinteger(key) ? arrayindex(ivalue(key)) : 0;
  if (i - 1u < asize)  /* is 'key' inside array part? */
    return i;  /* yes; that's the index */
  else {
    const TValue *n = getgeneric(t, key, 1);
    if (l_unlikely(isabstkey(n)))
      luaG_runerror(L, "invalid key to 'next'");  /* key not found */
    i = cast_int(nodefromval(n) - gnode(t, 0));  /* key index in hash table */
    /* hash elements are numbered after array ones */
    return (i + 1) + asize;
  }
}
References arrayindex(), cast_int, getgeneric(), gnode, isabstkey, ivalue, luaG_runerror(), nodefromval, ttisinteger, and ttisnil.
Referenced by luaH_next().
freehash()
static void freehash (lua_State * L, Table * t) static
Definition at line 360 of file lua-5.4.3/src/ltable.c.
{
  if (!isdummy(t))
    luaM_freearray(L, t->node, cast_sizet(sizenode(t)));
}
References cast_sizet, isdummy, luaM_freearray, Table::node, and sizenode.
Referenced by luaH_free(), and luaH_resize().
getfreepos()
static Node * getfreepos (Table * t) static
Definition at line 634 of file lua-5.4.3/src/ltable.c.
{
  if (!isdummy(t)) {
    while (t->lastfree > t->node) {
      t->lastfree--;
      if (keyisnil(t->lastfree))
        return t->lastfree;
    }
  }
  return NULL;  /* could not find a free place */
}
References isdummy, keyisnil, Table::lastfree, Table::node, and NULL.
Referenced by luaH_newkey().
getgeneric()
static const TValue * getgeneric (Table * t, const TValue * key, int deadok) static
Definition at line 288 of file lua-5.4.3/src/ltable.c.
{
  Node *n = mainpositionTV(t, key);
  for (;;) {  /* check whether 'key' is somewhere in the chain */
    if (equalkey(key, n, deadok))
      return gval(n);  /* that's it */
    else {
      int nx = gnext(n);
      if (nx == 0)
        return &absentkey;  /* not found */
      n += nx;
    }
  }
}
References absentkey, equalkey(), gnext, gval, and mainpositionTV().
Referenced by findindex(), luaH_get(), and luaH_getstr().
hash_search()
static lua_Unsigned hash_search (Table * t, lua_Unsigned j) static
Definition at line 844 of file lua-5.4.3/src/ltable.c.
{
  lua_Unsigned i;
  if (j == 0) j++;  /* the caller ensures 'j + 1' is present */
  do {
    i = j;  /* 'i' is a present index */
    if (j <= l_castS2U(LUA_MAXINTEGER) / 2)
      j *= 2;
    else {
      j = LUA_MAXINTEGER;
      if (isempty(luaH_getint(t, j)))  /* t[j] not present? */
        break;  /* 'j' now is an absent index */
      else  /* weird case */
        return j;  /* well, max integer is a boundary... */
    }
  } while (!isempty(luaH_getint(t, j)));  /* repeat until an absent t[j] */
  /* i < j  &&  t[i] present  &&  t[j] absent */
  while (j - i > 1u) {  /* do a binary search between them */
    lua_Unsigned m = (i + j) / 2;
    if (isempty(luaH_getint(t, m))) j = m;
    else i = m;
  }
  return i;
}
References isempty, l_castS2U, and luaH_getint().
Referenced by luaH_getn().
ispow2realasize()
static int ispow2realasize (const Table * t) static
Definition at line 267 of file lua-5.4.3/src/ltable.c.
{
  return (!isrealasize(t) || ispow2(t->alimit));
}
References Table::alimit, ispow2, and isrealasize.
Referenced by luaH_getn().
l_hashfloat()
static int l_hashfloat (lua_Number n) static
Definition at line 119 of file lua-5.4.3/src/ltable.c.
{
  int i;
  lua_Integer ni;
  n = l_mathop(frexp)(n, &i) * -cast_num(INT_MIN);
  if (!lua_numbertointeger(n, &ni)) {  /* is 'n' inf/-inf/NaN? */
    lua_assert(luai_numisnan(n) || l_mathop(fabs)(n) == cast_num(HUGE_VAL));
    return 0;
  }
  else {  /* normal case */
    unsigned int u = cast_uint(i) + cast_uint(ni);
    return cast_int(u <= cast_uint(INT_MAX) ? u : ~u);
  }
}
References cast_int, cast_num, cast_uint, l_mathop, lua_assert, lua_numbertointeger, and luai_numisnan.
Referenced by mainposition().
luaH_finishset()
void luaH_finishset (lua_State * L, Table * t, const TValue * key, const TValue * slot, TValue * value)
Definition at line 800 of file lua-5.4.3/src/ltable.c.
{
  if (isabstkey(slot))
    luaH_newkey(L, t, key, value);
  else
    setobj2t(L, cast(TValue *, slot), value);
}
References cast, isabstkey, luaH_newkey(), setobj2t, and value.
Referenced by addk(), luaH_set(), luaV_finishset(), and luaX_newstring().
luaH_free()
void luaH_free (lua_State * L, Table * t)
Definition at line 627 of file lua-5.4.3/src/ltable.c.
{
  freehash(L, t);
  luaM_freearray(L, t->array, luaH_realasize(t));
  luaM_free(L, t);
}
References Table::array, freehash(), luaH_realasize(), luaM_free, and luaM_freearray.
luaH_get()
const TValue * luaH_get (Table * t, const TValue * key)
Definition at line 777 of file lua-5.4.3/src/ltable.c.
{
  switch (ttypetag(key)) {
    case LUA_VSHRSTR: return luaH_getshortstr(t, tsvalue(key));
    case LUA_VNUMINT: return luaH_getint(t, ivalue(key));
    case LUA_VNIL: return &absentkey;
    case LUA_VNUMFLT: {
      lua_Integer k;
      if (luaV_flttointeger(fltvalue(key), &k, F2Ieq)) /* integral index? */
        return luaH_getint(t, k);  /* use specialized version */
      /* else... */
    }  /* FALLTHROUGH */
    default:
      return getgeneric(t, key, 0);
  }
}
References absentkey, F2Ieq, fltvalue, getgeneric(), ivalue, LUA_VNIL, LUA_VNUMFLT, LUA_VNUMINT, LUA_VSHRSTR, luaH_getint(), luaH_getshortstr(), luaV_flttointeger(), tsvalue, and ttypetag.
Referenced by luaH_set().
luaH_getint()
const TValue * luaH_getint (Table * t, lua_Integer key)
Definition at line 719 of file lua-5.4.3/src/ltable.c.
{
  if (l_castS2U(key) - 1u < t->alimit)  /* 'key' in [1, t->alimit]? */
    return &t->array[key - 1];
  else if (!limitequalsasize(t) &&  /* key still may be in the array part? */
           (l_castS2U(key) == t->alimit + 1 ||
            l_castS2U(key) - 1u < luaH_realasize(t))) {
    t->alimit = cast_uint(key);  /* probably '#t' is here now */
    return &t->array[key - 1];
  }
  else {
    Node *n = hashint(t, key);
    for (;;) {  /* check whether 'key' is somewhere in the chain */
      if (keyisinteger(n) && keyival(n) == key)
        return gval(n);  /* that's it */
      else {
        int nx = gnext(n);
        if (nx == 0) break;
        n += nx;
      }
    }
    return &absentkey;
  }
}
References absentkey, Table::alimit, Table::array, cast_uint, gnext, gval, hashint, keyisinteger, keyival, l_castS2U, limitequalsasize, and luaH_realasize().
Referenced by hash_search(), luaH_get(), luaH_getn(), and luaH_setint().
luaH_getn()
lua_Unsigned luaH_getn (Table * t)
Definition at line 912 of file lua-5.4.3/src/ltable.c.
{
  unsigned int limit = t->alimit;
  if (limit > 0 && isempty(&t->array[limit - 1])) {  /* (1)? */
    /* there must be a boundary before 'limit' */
    if (limit >= 2 && !isempty(&t->array[limit - 2])) {
      /* 'limit - 1' is a boundary; can it be a new limit? */
      if (ispow2realasize(t) && !ispow2(limit - 1)) {
        t->alimit = limit - 1;
        setnorealasize(t);  /* now 'alimit' is not the real size */
      }
      return limit - 1;
    }
    else {  /* must search for a boundary in [0, limit] */
      unsigned int boundary = binsearch(t->array, 0, limit);
      /* can this boundary represent the real size of the array? */
      if (ispow2realasize(t) && boundary > luaH_realasize(t) / 2) {
        t->alimit = boundary;  /* use it as the new limit */
        setnorealasize(t);
      }
      return boundary;
    }
  }
  /* 'limit' is zero or present in table */
  if (!limitequalsasize(t)) {  /* (2)? */
    /* 'limit' > 0 and array has more elements after 'limit' */
    if (isempty(&t->array[limit]))  /* 'limit + 1' is empty? */
      return limit;  /* this is the boundary */
    /* else, try last element in the array */
    limit = luaH_realasize(t);
    if (isempty(&t->array[limit - 1])) {  /* empty? */
      /* there must be a boundary in the array after old limit,
         and it must be a valid new limit */
      unsigned int boundary = binsearch(t->array, t->alimit, limit);
      t->alimit = boundary;
      return boundary;
    }
    /* else, new limit is present in the table; check the hash part */
  }
  /* (3) 'limit' is the last element and either is zero or present in table */
  lua_assert(limit == luaH_realasize(t) &&
             (limit == 0 || !isempty(&t->array[limit - 1])));
  if (isdummy(t) || isempty(luaH_getint(t, cast(lua_Integer, limit + 1))))
    return limit;  /* 'limit + 1' is absent */
  else  /* 'limit + 1' is also present */
    return hash_search(t, limit);
}
References Table::alimit, Table::array, binsearch(), cast, hash_search(), isdummy, isempty, ispow2, ispow2realasize(), limitequalsasize, lua_assert, luaH_getint(), luaH_realasize(), and setnorealasize.
luaH_getshortstr()
const TValue * luaH_getshortstr (Table * t, TString * key)
Definition at line 747 of file lua-5.4.3/src/ltable.c.
{
  Node *n = hashstr(t, key);
  lua_assert(key->tt == LUA_VSHRSTR);
  for (;;) {  /* check whether 'key' is somewhere in the chain */
    if (keyisshrstr(n) && eqshrstr(keystrval(n), key))
      return gval(n);  /* that's it */
    else {
      int nx = gnext(n);
      if (nx == 0)
        return &absentkey;  /* not found */
      n += nx;
    }
  }
}
References absentkey, eqshrstr, gnext, gval, hashstr, keyisshrstr, keystrval, lua_assert, and LUA_VSHRSTR.
Referenced by luaH_get(), and luaH_getstr().
luaH_getstr()
const TValue * luaH_getstr (Table * t, TString * key)
Definition at line 763 of file lua-5.4.3/src/ltable.c.
{
  if (key->tt == LUA_VSHRSTR)
    return luaH_getshortstr(t, key);
  else {  /* for long strings, use generic case */
    TValue ko;
    setsvalue(cast(lua_State *, NULL), &ko, key);
    return getgeneric(t, &ko, 0);
  }
}
References cast, getgeneric(), LUA_VSHRSTR, luaH_getshortstr(), NULL, and setsvalue.
luaH_new()
Table * luaH_new (lua_State * L)
Definition at line 615 of file lua-5.4.3/src/ltable.c.
{
  GCObject *o = luaC_newobj(L, LUA_VTABLE, sizeof(Table));
  Table *t = gco2t(o);
  t->metatable = NULL;
  t->flags = cast_byte(maskflags);  /* table has no metamethod fields */
  t->array = NULL;
  t->alimit = 0;
  setnodevector(L, t, 0);
  return t;
}
References Table::alimit, Table::array, cast_byte, Table::flags, gco2t, LUA_VTABLE, luaC_newobj(), maskflags, Table::metatable, NULL, and setnodevector().
luaH_newkey()
void luaH_newkey (lua_State * L, Table * t, const TValue * key, TValue * value)
Definition at line 654 of file lua-5.4.3/src/ltable.c.
{
  Node *mp;
  TValue aux;
  if (l_unlikely(ttisnil(key)))
    luaG_runerror(L, "table index is nil");
  else if (ttisfloat(key)) {
    lua_Number f = fltvalue(key);
    lua_Integer k;
    if (luaV_flttointeger(f, &k, F2Ieq)) {  /* does key fit in an integer? */
      setivalue(&aux, k);
      key = &aux;  /* insert it as an integer */
    }
    else if (l_unlikely(luai_numisnan(f)))
      luaG_runerror(L, "table index is NaN");
  }
  if (ttisnil(value))
    return;  /* do not insert nil values */
  mp = mainpositionTV(t, key);
  if (!isempty(gval(mp)) || isdummy(t)) {  /* main position is taken? */
    Node *othern;
    Node *f = getfreepos(t);  /* get a free place */
    if (f == NULL) {  /* cannot find a free place? */
      rehash(L, t, key);  /* grow table */
      /* whatever called 'newkey' takes care of TM cache */
      luaH_set(L, t, key, value);  /* insert key into grown table */
      return;
    }
    lua_assert(!isdummy(t));
    othern = mainposition(t, keytt(mp), &keyval(mp));
    if (othern != mp) {  /* is colliding node out of its main position? */
      /* yes; move colliding node into free position */
      while (othern + gnext(othern) != mp)  /* find previous */
        othern += gnext(othern);
      gnext(othern) = cast_int(f - othern);  /* rechain to point to 'f' */
      *f = *mp;  /* copy colliding node into free pos. (mp->next also goes) */
      if (gnext(mp) != 0) {
        gnext(f) += cast_int(mp - f);  /* correct 'next' */
        gnext(mp) = 0;  /* now 'mp' is free */
      }
      setempty(gval(mp));
    }
    else {  /* colliding node is in its own main position */
      /* new node will go into free position */
      if (gnext(mp) != 0)
        gnext(f) = cast_int((mp + gnext(mp)) - f);  /* chain new position */
      else lua_assert(gnext(f) == 0);
      gnext(mp) = cast_int(f - mp);
      mp = f;
    }
  }
  setnodekey(L, mp, key);
  luaC_barrierback(L, obj2gco(t), key);
  lua_assert(isempty(gval(mp)));
  setobj2t(L, gval(mp), value);
}
References cast_int, F2Ieq, fltvalue, getfreepos(), gnext, gval, isdummy, isempty, keytt, keyval, lua_assert, luaC_barrierback, luaG_runerror(), luaH_set(), luai_numisnan, luaV_flttointeger(), mainposition(), mainpositionTV(), NULL, obj2gco, rehash(), setempty, setivalue, setnodekey, setobj2t, ttisfloat, ttisnil, and value.
Referenced by luaH_finishset(), and luaH_setint().
luaH_next()
int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 338 of file lua-5.4.3/src/ltable.c.
{
  unsigned int asize = luaH_realasize(t);
  unsigned int i = findindex(L, t, s2v(key), asize);  /* find original key */
  for (; i < asize; i++) {  /* try first array part */
    if (!isempty(&t->array[i])) {  /* a non-empty entry? */
      setivalue(s2v(key), i + 1);
      setobj2s(L, key + 1, &t->array[i]);
      return 1;
    }
  }
  for (i -= asize; cast_int(i) < sizenode(t); i++) {  /* hash part */
    if (!isempty(gval(gnode(t, i)))) {  /* a non-empty entry? */
      Node *n = gnode(t, i);
      getnodekey(L, s2v(key), n);
      setobj2s(L, key + 1, gval(n));
      return 1;
    }
  }
  return 0;  /* no more elements */
}
References Table::array, cast_int, findindex(), getnodekey, gnode, gval, isempty, luaH_realasize(), s2v, setivalue, setobj2s, and sizenode.
luaH_realasize()
LUAI_FUNC unsigned int luaH_realasize (const Table * t)
Definition at line 241 of file lua-5.4.3/src/ltable.c.
{
  if (limitequalsasize(t))
    return t->alimit;  /* this is the size */
  else {
    unsigned int size = t->alimit;
    /* compute the smallest power of 2 not smaller than 'n' */
    size |= (size >> 1);
    size |= (size >> 2);
    size |= (size >> 4);
    size |= (size >> 8);
    size |= (size >> 16);
#if (UINT_MAX >> 30) > 3
    size |= (size >> 32);  /* unsigned int has more than 32 bits */
#endif
    size++;
    lua_assert(ispow2(size) && size/2 < t->alimit && t->alimit < size);
    return size;
  }
}
References Table::alimit, ispow2, limitequalsasize, and lua_assert.
Referenced by clearbyvalues(), luaH_free(), luaH_getint(), luaH_getn(), luaH_next(), luaV_execute(), setlimittosize(), traverseephemeron(), and traversestrongtable().
luaH_resize()
void luaH_resize (lua_State * L, Table * t, unsigned int newasize, unsigned int nhsize)
Definition at line 542 of file lua-5.4.3/src/ltable.c.
{
  unsigned int i;
  Table newt;  /* to keep the new hash part */
  unsigned int oldasize = setlimittosize(t);
  TValue *newarray;
  /* create new hash part with appropriate size into 'newt' */
  setnodevector(L, &newt, nhsize);
  if (newasize < oldasize) {  /* will array shrink? */
    t->alimit = newasize;  /* pretend array has new size... */
    exchangehashpart(t, &newt);  /* and new hash */
    /* re-insert into the new hash the elements from vanishing slice */
    for (i = newasize; i < oldasize; i++) {
      if (!isempty(&t->array[i]))
        luaH_setint(L, t, i + 1, &t->array[i]);
    }
    t->alimit = oldasize;  /* restore current size... */
    exchangehashpart(t, &newt);  /* and hash (in case of errors) */
  }
  /* allocate new array */
  newarray = luaM_reallocvector(L, t->array, oldasize, newasize, TValue);
  if (l_unlikely(newarray == NULL && newasize > 0)) {  /* allocation failed? */
    freehash(L, &newt);  /* release new hash part */
    luaM_error(L);  /* raise error (with array unchanged) */
  }
  /* allocation ok; initialize new part of the array */
  exchangehashpart(t, &newt);  /* 't' has the new hash ('newt' has the old) */
  t->array = newarray;  /* set new array part */
  t->alimit = newasize;
  for (i = oldasize; i < newasize; i++)  /* clear new slice of the array */
     setempty(&t->array[i]);
  /* re-insert elements from old hash part into new parts */
  reinsert(L, &newt, t);  /* 'newt' now has the old hash */
  freehash(L, &newt);  /* free old hash part */
}
References Table::alimit, Table::array, exchangehashpart(), freehash(), isempty, luaH_setint(), luaM_error, luaM_reallocvector, NULL, reinsert(), setempty, setlimittosize(), and setnodevector().
Referenced by luaH_resizearray(), and rehash().
luaH_resizearray()
void luaH_resizearray (lua_State * L, Table * t, unsigned int nasize)
Definition at line 579 of file lua-5.4.3/src/ltable.c.
{
  int nsize = allocsizenode(t);
  luaH_resize(L, t, nasize, nsize);
}
References allocsizenode, and luaH_resize().
luaH_set()
void luaH_set (lua_State * L, Table * t, const TValue * key, TValue * value)
Definition at line 813 of file lua-5.4.3/src/ltable.c.
{
  const TValue *slot = luaH_get(t, key);
  luaH_finishset(L, t, key, slot, value);
}
References luaH_finishset(), luaH_get(), and value.
Referenced by luaH_newkey(), and reinsert().
luaH_setint()
void luaH_setint (lua_State * L, Table * t, lua_Integer key, TValue * value)
Definition at line 819 of file lua-5.4.3/src/ltable.c.
{
  const TValue *p = luaH_getint(t, key);
  if (isabstkey(p)) {
    TValue k;
    setivalue(&k, key);
    luaH_newkey(L, t, &k, value);
  }
  else
    setobj2t(L, cast(TValue *, p), value);
}
References cast, isabstkey, luaH_getint(), luaH_newkey(), setivalue, setobj2t, and value.
Referenced by luaH_resize().
mainposition()
static Node * mainposition (const Table * t, int ktt, const Value * kvl) static
Definition at line 141 of file lua-5.4.3/src/ltable.c.
{
  switch (withvariant(ktt)) {
    case LUA_VNUMINT: {
      lua_Integer key = ivalueraw(*kvl);
      return hashint(t, key);
    }
    case LUA_VNUMFLT: {
      lua_Number n = fltvalueraw(*kvl);
      return hashmod(t, l_hashfloat(n));
    }
    case LUA_VSHRSTR: {
      TString *ts = tsvalueraw(*kvl);
      return hashstr(t, ts);
    }
    case LUA_VLNGSTR: {
      TString *ts = tsvalueraw(*kvl);
      return hashpow2(t, luaS_hashlongstr(ts));
    }
    case LUA_VFALSE:
      return hashboolean(t, 0);
    case LUA_VTRUE:
      return hashboolean(t, 1);
    case LUA_VLIGHTUSERDATA: {
      void *p = pvalueraw(*kvl);
      return hashpointer(t, p);
    }
    case LUA_VLCF: {
      lua_CFunction f = fvalueraw(*kvl);
      return hashpointer(t, f);
    }
    default: {
      GCObject *o = gcvalueraw(*kvl);
      return hashpointer(t, o);
    }
  }
}
References fltvalueraw, fvalueraw, gcvalueraw, hashboolean, hashint, hashmod, hashpointer, hashpow2, hashstr, ivalueraw, l_hashfloat(), LUA_VFALSE, LUA_VLCF, LUA_VLIGHTUSERDATA, LUA_VLNGSTR, LUA_VNUMFLT, LUA_VNUMINT, LUA_VSHRSTR, LUA_VTRUE, luaS_hashlongstr(), pvalueraw, tsvalueraw, and withvariant.
Referenced by luaH_newkey(), and mainpositionTV().
mainpositionTV()
static Node * mainpositionTV (const Table * t, const TValue * key) static
Definition at line 182 of file lua-5.4.3/src/ltable.c.
{
  return mainposition(t, rawtt(key), valraw(key));
}
References mainposition(), rawtt, and valraw.
Referenced by getgeneric(), and luaH_newkey().
numusearray()
static unsigned int numusearray (const Table * t, unsigned int * nums) static
Definition at line 418 of file lua-5.4.3/src/ltable.c.
{
  int lg;
  unsigned int ttlg;  /* 2^lg */
  unsigned int ause = 0;  /* summation of 'nums' */
  unsigned int i = 1;  /* count to traverse all array keys */
  unsigned int asize = limitasasize(t);  /* real array size */
  /* traverse each slice */
  for (lg = 0, ttlg = 1; lg <= MAXABITS; lg++, ttlg *= 2) {
    unsigned int lc = 0;  /* counter */
    unsigned int lim = ttlg;
    if (lim > asize) {
      lim = asize;  /* adjust upper limit */
      if (i > lim)
        break;  /* no more elements to count */
    }
    /* count elements in range (2^(lg - 1), 2^lg] */
    for (; i <= lim; i++) {
      if (!isempty(&t->array[i-1]))
        lc++;
    }
    nums[lg] += lc;
    ause += lc;
  }
  return ause;
}
References Table::array, isempty, limitasasize, and MAXABITS.
Referenced by rehash().
numusehash()
static int numusehash (const Table * t, unsigned int * nums, unsigned int * pna) static
Definition at line 445 of file lua-5.4.3/src/ltable.c.
{
  int totaluse = 0;  /* total number of elements */
  int ause = 0;  /* elements added to 'nums' (can go to array part) */
  int i = sizenode(t);
  while (i--) {
    Node *n = &t->node[i];
    if (!isempty(gval(n))) {
      if (keyisinteger(n))
        ause += countint(keyival(n), nums);
      totaluse++;
    }
  }
  *pna += ause;
  return totaluse;
}
References countint(), gval, isempty, keyisinteger, keyival, Table::node, and sizenode.
Referenced by rehash().
rehash()
static void rehash (lua_State * L, Table * t, const TValue * ek) static
Definition at line 587 of file lua-5.4.3/src/ltable.c.
{
  unsigned int asize;  /* optimal size for array part */
  unsigned int na;  /* number of keys in the array part */
  unsigned int nums[MAXABITS + 1];
  int i;
  int totaluse;
  for (i = 0; i <= MAXABITS; i++) nums[i] = 0;  /* reset counts */
  setlimittosize(t);
  na = numusearray(t, nums);  /* count keys in array part */
  totaluse = na;  /* all those keys are integer keys */
  totaluse += numusehash(t, nums, &na);  /* count keys in hash part */
  /* count extra key */
  if (ttisinteger(ek))
    na += countint(ivalue(ek), nums);
  totaluse++;
  /* compute new size for array part */
  asize = computesizes(nums, &na);
  /* resize the table to new computed sizes */
  luaH_resize(L, t, asize, totaluse - na);
}
References computesizes(), countint(), ivalue, luaH_resize(), MAXABITS, numusearray(), numusehash(), setlimittosize(), and ttisinteger.
Referenced by luaH_newkey().
reinsert()
static void reinsert (lua_State * L, Table * ot, Table * t) static
Definition at line 497 of file lua-5.4.3/src/ltable.c.
{
  int j;
  int size = sizenode(ot);
  for (j = 0; j < size; j++) {
    Node *old = gnode(ot, j);
    if (!isempty(gval(old))) {
      /* doesn't need barrier/invalidate cache, as entry was
         already present in the table */
      TValue k;
      getnodekey(L, &k, old);
      luaH_set(L, t, &k, gval(old));
    }
  }
}
References getnodekey, gnode, gval, isempty, luaH_set(), and sizenode.
Referenced by luaH_resize().
setlimittosize()
static unsigned int setlimittosize (Table * t) static
Definition at line 272 of file lua-5.4.3/src/ltable.c.
{
  t->alimit = luaH_realasize(t);
  setrealasize(t);
  return t->alimit;
}
References Table::alimit, luaH_realasize(), and setrealasize.
Referenced by luaH_resize(), and rehash().
setnodevector()
static void setnodevector (lua_State * L, Table * t, unsigned int size) static
Definition at line 469 of file lua-5.4.3/src/ltable.c.
{
  if (size == 0) {  /* no elements to hash part? */
    t->node = cast(Node *, dummynode);  /* use common 'dummynode' */
    t->lsizenode = 0;
    t->lastfree = NULL;  /* signal that it is using dummy node */
  }
  else {
    int i;
    int lsize = luaO_ceillog2(size);
    if (lsize > MAXHBITS || (1u << lsize) > MAXHSIZE)
      luaG_runerror(L, "table overflow");
    size = twoto(lsize);
    t->node = luaM_newvector(L, size, Node);
    for (i = 0; i < (int)size; i++) {
      Node *n = gnode(t, i);
      gnext(n) = 0;
      setnilkey(n);
      setempty(gval(n));
    }
    t->lsizenode = cast_byte(lsize);
    t->lastfree = gnode(t, size);  /* all positions are free */
  }
}
References cast, cast_byte, dummynode, gnext, gnode, gval, Table::lastfree, Table::lsizenode, luaG_runerror(), luaM_newvector, luaO_ceillog2(), MAXHBITS, MAXHSIZE, Table::node, NULL, setempty, setnilkey, and twoto.
Referenced by luaH_new(), and luaH_resize().
Variable Documentation
absentkey
const TValue absentkey = {ABSTKEYCONSTANT} static
Definition at line 101 of file lua-5.4.3/src/ltable.c.
{ABSTKEYCONSTANT};
Referenced by getgeneric(), luaH_get(), luaH_getint(), and luaH_getshortstr().
dummynode_
const Node dummynode_ static
Initial value:
= {
  {{NULL}, LUA_VEMPTY,
   LUA_VNIL, 0, {NULL}}
}
Definition at line 95 of file lua-5.4.3/src/ltable.c.
{
  {{NULL}, LUA_VEMPTY,  /* value's value and type */
   LUA_VNIL, 0, {NULL}}  /* key type, next, and key value */
};