Github User Fetcher: lstate.h File Reference
lstate.h File Reference
#include "lua.h"
#include "lobject.h"
#include "ltm.h"
#include "lzio.h"
#include <signal.h>
Data Structures
struct stringtable
struct CallInfo
struct global_State
struct lua_State
union GCUnion
Macros
#define yieldable(L) (((L)->nCcalls & 0xffff0000) == 0)
#define getCcalls(L) ((L)->nCcalls & 0xffff)
#define incnny(L) ((L)->nCcalls += 0x10000)
#define decnny(L) ((L)->nCcalls -= 0x10000)
#define nyci (0x10000 | 1)
#define l_signalT sig_atomic_t
#define EXTRA_STACK 5
#define BASIC_STACK_SIZE (2*LUA_MINSTACK)
#define stacksize(th) cast_int((th)->stack_last - (th)->stack)
#define KGC_INC 0 /* incremental gc */
#define KGC_GEN 1 /* generational gc */
#define CIST_OAH (1<<0) /* original value of 'allowhook' */
#define CIST_C (1<<1) /* call is running a C function */
#define CIST_FRESH (1<<2) /* call is on a fresh "luaV_execute" frame */
#define CIST_HOOKED (1<<3) /* call is running a debug hook */
#define CIST_YPCALL (1<<4) /* doing a yieldable protected call */
#define CIST_TAIL (1<<5) /* call was tail called */
#define CIST_HOOKYIELD (1<<6) /* last hook called yielded */
#define CIST_FIN (1<<7) /* call is running a finalizer */
#define CIST_TRAN (1<<8) /* 'ci' has transfer information */
#define CIST_CLSRET (1<<9) /* function is closing tbc variables */
#define CIST_RECST 10
#define getcistrecst(ci) (((ci)->callstatus >> CIST_RECST) & 7)
#define setcistrecst(ci, st)
#define isLua(ci) (!((ci)->callstatus & CIST_C))
#define isLuacode(ci) (!((ci)->callstatus & (CIST_C | CIST_HOOKED)))
#define setoah(st, v) ((st) = ((st) & ~CIST_OAH) | (v))
#define getoah(st) ((st) & CIST_OAH)
#define G(L) (L->l_G)
#define completestate(g) ttisnil(&g->nilvalue)
#define cast_u(o) cast(union GCUnion *, (o))
#define gco2ts(o) check_exp(novariant((o)->tt) == LUA_TSTRING, &((cast_u(o))->ts))
#define gco2u(o) check_exp((o)->tt == LUA_VUSERDATA, &((cast_u(o))->u))
#define gco2lcl(o) check_exp((o)->tt == LUA_VLCL, &((cast_u(o))->cl.l))
#define gco2ccl(o) check_exp((o)->tt == LUA_VCCL, &((cast_u(o))->cl.c))
#define gco2cl(o) check_exp(novariant((o)->tt) == LUA_TFUNCTION, &((cast_u(o))->cl))
#define gco2t(o) check_exp((o)->tt == LUA_VTABLE, &((cast_u(o))->h))
#define gco2p(o) check_exp((o)->tt == LUA_VPROTO, &((cast_u(o))->p))
#define gco2th(o) check_exp((o)->tt == LUA_VTHREAD, &((cast_u(o))->th))
#define gco2upv(o) check_exp((o)->tt == LUA_VUPVAL, &((cast_u(o))->upv))
#define obj2gco(v) check_exp((v)->tt >= LUA_TSTRING, &(cast_u(v)->gc))
#define gettotalbytes(g) cast(lu_mem, (g)->totalbytes + (g)->GCdebt)
Typedefs
typedef struct stringtable stringtable
typedef struct CallInfo CallInfo
typedef struct global_State global_State
Functions
LUAI_FUNC void luaE_setdebt (global_State *g, l_mem debt)
LUAI_FUNC void luaE_freethread (lua_State *L, lua_State *L1)
LUAI_FUNC CallInfo * luaE_extendCI (lua_State *L)
LUAI_FUNC void luaE_freeCI (lua_State *L)
LUAI_FUNC void luaE_shrinkCI (lua_State *L)
LUAI_FUNC void luaE_checkcstack (lua_State *L)
LUAI_FUNC void luaE_incCstack (lua_State *L)
LUAI_FUNC void luaE_warning (lua_State *L, const char *msg, int tocont)
LUAI_FUNC void luaE_warnerror (lua_State *L, const char *where)
LUAI_FUNC int luaE_resetthread (lua_State *L, int status)
Macro Definition Documentation
BASIC_STACK_SIZE
#define BASIC_STACK_SIZE (2*LUA_MINSTACK)
Definition at line 140 of file lua-5.4.3/src/lstate.h.
cast_u
#define cast_u (o) cast(union GCUnion *, (o))
Definition at line 365 of file lua-5.4.3/src/lstate.h.
CIST_C
#define CIST_C (1<<1) /* call is running a C function */
Definition at line 206 of file lua-5.4.3/src/lstate.h.
Referenced by luaD_precall(), luaE_resetthread(), and stack_init().
CIST_CLSRET
#define CIST_CLSRET (1<<9) /* function is closing tbc variables */
Definition at line 214 of file lua-5.4.3/src/lstate.h.
Referenced by finishCcall(), luaD_poscall(), and moveresults().
CIST_FIN
#define CIST_FIN (1<<7) /* call is running a finalizer */
Definition at line 212 of file lua-5.4.3/src/lstate.h.
CIST_FRESH
#define CIST_FRESH (1<<2) /* call is on a fresh "luaV_execute" frame */
Definition at line 207 of file lua-5.4.3/src/lstate.h.
CIST_HOOKED
#define CIST_HOOKED (1<<3) /* call is running a debug hook */
Definition at line 208 of file lua-5.4.3/src/lstate.h.
CIST_HOOKYIELD
#define CIST_HOOKYIELD (1<<6) /* last hook called yielded */
Definition at line 211 of file lua-5.4.3/src/lstate.h.
CIST_OAH
#define CIST_OAH (1<<0) /* original value of 'allowhook' */
Definition at line 205 of file lua-5.4.3/src/lstate.h.
CIST_RECST
#define CIST_RECST 10
Definition at line 216 of file lua-5.4.3/src/lstate.h.
CIST_TAIL
#define CIST_TAIL (1<<5) /* call was tail called */
Definition at line 210 of file lua-5.4.3/src/lstate.h.
CIST_TRAN
#define CIST_TRAN (1<<8) /* 'ci' has transfer information */
Definition at line 213 of file lua-5.4.3/src/lstate.h.
Referenced by auxgetinfo(), luaD_hook(), and luaD_poscall().
CIST_YPCALL
#define CIST_YPCALL (1<<4) /* doing a yieldable protected call */
Definition at line 209 of file lua-5.4.3/src/lstate.h.
completestate
#define completestate (g) ttisnil(&g->nilvalue)
Definition at line 336 of file lua-5.4.3/src/lstate.h.
Referenced by close_state(), and tryagain().
decnny
#define decnny (L) ((L)->nCcalls -= 0x10000)
Definition at line 109 of file lua-5.4.3/src/lstate.h.
Referenced by luaD_protectedparser().
EXTRA_STACK
#define EXTRA_STACK 5
Definition at line 137 of file lua-5.4.3/src/lstate.h.
G
#define G (L) (L->l_G)
Definition at line 330 of file lua-5.4.3/src/lstate.h.
gco2ccl
#define gco2ccl (o) check_exp((o)->tt == LUA_VCCL, &((cast_u(o))->cl.c))
Definition at line 372 of file lua-5.4.3/src/lstate.h.
gco2cl
#define gco2cl (o) check_exp(novariant((o)->tt) == LUA_TFUNCTION, &((cast_u(o))->cl))
Definition at line 373 of file lua-5.4.3/src/lstate.h.
#define gco2cl(o)  \
    check_exp(novariant((o)->tt) == LUA_TFUNCTION, &((cast_u(o))->cl))
gco2lcl
#define gco2lcl (o) check_exp((o)->tt == LUA_VLCL, &((cast_u(o))->cl.l))
Definition at line 371 of file lua-5.4.3/src/lstate.h.
gco2p
#define gco2p (o) check_exp((o)->tt == LUA_VPROTO, &((cast_u(o))->p))
Definition at line 376 of file lua-5.4.3/src/lstate.h.
gco2t
#define gco2t (o) check_exp((o)->tt == LUA_VTABLE, &((cast_u(o))->h))
Definition at line 375 of file lua-5.4.3/src/lstate.h.
gco2th
#define gco2th (o) check_exp((o)->tt == LUA_VTHREAD, &((cast_u(o))->th))
Definition at line 377 of file lua-5.4.3/src/lstate.h.
gco2ts
#define gco2ts (o) check_exp(novariant((o)->tt) == LUA_TSTRING, &((cast_u(o))->ts))
Definition at line 368 of file lua-5.4.3/src/lstate.h.
#define gco2ts(o)  \
    check_exp(novariant((o)->tt) == LUA_TSTRING, &((cast_u(o))->ts))
gco2u
#define gco2u (o) check_exp((o)->tt == LUA_VUSERDATA, &((cast_u(o))->u))
Definition at line 370 of file lua-5.4.3/src/lstate.h.
gco2upv
#define gco2upv (o) check_exp((o)->tt == LUA_VUPVAL, &((cast_u(o))->upv))
Definition at line 378 of file lua-5.4.3/src/lstate.h.
Referenced by freeobj(), luaF_initupvals(), newupval(), reallymarkobject(), and sweep2old().
getCcalls
#define getCcalls (L) ((L)->nCcalls & 0xffff)
Definition at line 102 of file lua-5.4.3/src/lstate.h.
Referenced by ccall(), lua_resume(), luaE_checkcstack(), and luaE_incCstack().
getcistrecst
#define getcistrecst (ci) (((ci)->callstatus >> CIST_RECST) & 7)
Definition at line 228 of file lua-5.4.3/src/lstate.h.
Referenced by finishpcallk().
getoah
#define getoah (st) ((st) & CIST_OAH)
Definition at line 243 of file lua-5.4.3/src/lstate.h.
gettotalbytes
#define gettotalbytes (g) cast(lu_mem, (g)->totalbytes + (g)->GCdebt)
Definition at line 389 of file lua-5.4.3/src/lstate.h.
incnny
#define incnny (L) ((L)->nCcalls += 0x10000)
Definition at line 106 of file lua-5.4.3/src/lstate.h.
Referenced by lua_newstate(), and luaD_protectedparser().
isLua
#define isLua (ci) (!((ci)->callstatus & CIST_C))
Definition at line 236 of file lua-5.4.3/src/lstate.h.
isLuacode
#define isLuacode (ci) (!((ci)->callstatus & (CIST_C | CIST_HOOKED)))
Definition at line 239 of file lua-5.4.3/src/lstate.h.
Referenced by lua_yieldk(), luaT_callTM(), and luaT_callTMres().
KGC_GEN
#define KGC_GEN 1 /* generational gc */
Definition at line 147 of file lua-5.4.3/src/lstate.h.
KGC_INC
#define KGC_INC 0 /* incremental gc */
Definition at line 146 of file lua-5.4.3/src/lstate.h.
Referenced by enterinc(), lua_gc(), lua_newstate(), luaC_barrier_(), luaC_freeallobjects(), and luaC_fullgc().
l_signalT
#define l_signalT sig_atomic_t
Definition at line 126 of file lua-5.4.3/src/lstate.h.
nyci
#define nyci (0x10000 | 1)
Definition at line 112 of file lua-5.4.3/src/lstate.h.
Referenced by luaD_callnoyield().
obj2gco
#define obj2gco (v) check_exp((v)->tt >= LUA_TSTRING, &(cast_u(v)->gc))
Definition at line 385 of file lua-5.4.3/src/lstate.h.
setcistrecst
#define setcistrecst (ci, st)
Value:
  check_exp(((st) & 7) == (st),   /* status must fit in three bits */  \
            ((ci)->callstatus = ((ci)->callstatus & ~(7 << CIST_RECST))  \
                                                  | ((st) << CIST_RECST)))
Definition at line 229 of file lua-5.4.3/src/lstate.h.
#define setcistrecst(ci,st)  \
  check_exp(((st) & 7) == (st),   /* status must fit in three bits */  \
            ((ci)->callstatus = ((ci)->callstatus & ~(7 << CIST_RECST))  \
                                                  | ((st) << CIST_RECST)))
Referenced by finishpcallk(), and precover().
setoah
#define setoah (st, v) ((st) = ((st) & ~CIST_OAH) | (v))
Definition at line 242 of file lua-5.4.3/src/lstate.h.
stacksize
#define stacksize (th) cast_int((th)->stack_last - (th)->stack)
Definition at line 142 of file lua-5.4.3/src/lstate.h.
Referenced by checkstacksizes(), freestack(), luaD_growstack(), luaD_growstack(), luaD_reallocstack(), luaD_shrinkstack(), and traversethread().
yieldable
#define yieldable (L) (((L)->nCcalls & 0xffff0000) == 0)
Definition at line 99 of file lua-5.4.3/src/lstate.h.
Referenced by finishCcall(), lua_callk(), lua_isyieldable(), lua_pcallk(), and lua_yieldk().
Typedef Documentation
CallInfo
typedef struct CallInfo CallInfo
global_State
typedef struct global_State global_State
stringtable
typedef struct stringtable stringtable
Function Documentation
luaE_checkcstack()
LUAI_FUNC void luaE_checkcstack (lua_State * L)
Definition at line 165 of file lua-5.4.3/src/lstate.c.
{
  if (getCcalls(L) == LUAI_MAXCCALLS)
    luaG_runerror(L, "C stack overflow");
  else if (getCcalls(L) >= (LUAI_MAXCCALLS / 10 * 11))
    luaD_throw(L, LUA_ERRERR);  /* error while handing stack error */
}
References getCcalls, LUA_ERRERR, luaD_throw(), luaG_runerror(), and LUAI_MAXCCALLS.
Referenced by ccall(), and luaE_incCstack().
luaE_extendCI()
LUAI_FUNC CallInfo * luaE_extendCI (lua_State * L)
Definition at line 112 of file lua-5.2.4/src/lstate.c.
{
  CallInfo *ci = luaM_new(L, CallInfo);
  lua_assert(L->ci->next == NULL);
  L->ci->next = ci;
  ci->previous = L->ci;
  ci->next = NULL;
  return ci;
}
References lua_State::ci, CallInfo::l, lua_assert, luaM_new, lua_State::nci, CallInfo::next, NULL, CallInfo::previous, CallInfo::trap, and CallInfo::u.
luaE_freeCI()
LUAI_FUNC void luaE_freeCI (lua_State * L)
Definition at line 122 of file lua-5.2.4/src/lstate.c.
{
  CallInfo *ci = L->ci;
  CallInfo *next = ci->next;
  ci->next = NULL;
  while ((ci = next) != NULL) {
    next = ci->next;
    luaM_free(L, ci);
  }
}
References lua_State::ci, luaM_free, lua_State::nci, next, CallInfo::next, and NULL.
Referenced by freestack(), freestack(), freestack(), luaD_shrinkstack(), and sweepthread().
luaE_freethread()
LUAI_FUNC void luaE_freethread (lua_State * L, lua_State * L1)
Definition at line 134 of file lua-5.1.5/src/lstate.c.
{
  luaF_close(L1, L1->stack);  /* close all upvalues for this thread */
  lua_assert(L1->openupval == NULL);
  luai_userstatefree(L1);
  freestack(L, L1);
  luaM_freemem(L, fromstate(L1), state_size(lua_State));
}
References freestack(), freestack(), freestack(), freestack(), fromstate, lua_assert, luaF_close(), luaF_closeupval(), luai_userstatefree, luaM_free, luaM_freemem, NULL, lua_State::openupval, lua_State::stack, and state_size.
Referenced by freeobj(), freeobj(), freeobj(), and freeobj().
luaE_incCstack()
LUAI_FUNC void luaE_incCstack (lua_State * L)
Definition at line 173 of file lua-5.4.3/src/lstate.c.
{
  L->nCcalls++;
  if (l_unlikely(getCcalls(L) >= LUAI_MAXCCALLS))
    luaE_checkcstack(L);
}
References getCcalls, luaE_checkcstack(), LUAI_MAXCCALLS, and lua_State::nCcalls.
Referenced by resume().
luaE_resetthread()
LUAI_FUNC int luaE_resetthread (lua_State * L, int status)
Definition at line 326 of file lua-5.4.3/src/lstate.c.
{
  CallInfo *ci = L->ci = &L->base_ci;  /* unwind CallInfo list */
  setnilvalue(s2v(L->stack));  /* 'function' entry for basic 'ci' */
  ci->func = L->stack;
  ci->callstatus = CIST_C;
  if (status == LUA_YIELD)
    status = LUA_OK;
  status = luaD_closeprotected(L, 1, status);
  if (status != LUA_OK)  /* errors? */
    luaD_seterrorobj(L, status, L->stack + 1);
  else
    L->top = L->stack + 1;
  ci->top = L->top + LUA_MINSTACK;
  L->status = cast_byte(status);
  luaD_reallocstack(L, cast_int(ci->top - L->stack), 0);
  return status;
}
References lua_State::base_ci, CallInfo::callstatus, cast_byte, cast_int, lua_State::ci, CIST_C, CallInfo::func, LUA_MINSTACK, LUA_OK, LUA_YIELD, luaD_closeprotected(), luaD_reallocstack(), luaD_seterrorobj(), s2v, setnilvalue, lua_State::stack, lua_State::status, CallInfo::top, and lua_State::top.
Referenced by lua_resetthread(), and luaD_throw().
luaE_setdebt()
LUAI_FUNC void luaE_setdebt (global_State * g, l_mem debt)
Definition at line 106 of file lua-5.2.4/src/lstate.c.
{
  g->totalbytes -= (debt - g->GCdebt);
  g->GCdebt = debt;
}
References global_State::GCdebt, gettotalbytes, lua_assert, MAX_LMEM, and global_State::totalbytes.
Referenced by incstep(), incstep(), lua_gc(), lua_gc(), luaC_step(), setminordebt(), setpause(), setpause(), and setpause().
luaE_shrinkCI()
LUAI_FUNC void luaE_shrinkCI (lua_State * L)
Definition at line 137 of file lua-5.3.6/src/lstate.c.
{
  CallInfo *ci = L->ci;
  CallInfo *next2;  /* next's next */
  /* while there are two nexts */
  while (ci->next != NULL && (next2 = ci->next->next) != NULL) {
    luaM_free(L, ci->next);  /* free next */
    L->nci--;
    ci->next = next2;  /* remove 'next' from the list */
    next2->previous = ci;
    ci = next2;  /* keep next's next */
  }
}
References lua_State::ci, luaM_free, lua_State::nci, next, CallInfo::next, NULL, and CallInfo::previous.
Referenced by luaD_shrinkstack().
luaE_warnerror()
LUAI_FUNC void luaE_warnerror (lua_State * L, const char * where)
Definition at line 427 of file lua-5.4.3/src/lstate.c.
{
  TValue *errobj = s2v(L->top - 1);  /* error object */
  const char *msg = (ttisstring(errobj))
                  ? svalue(errobj)
                  : "error object is not a string";
  /* produce warning "error in %s (%s)" (where, msg) */
  luaE_warning(L, "error in ", 1);
  luaE_warning(L, where, 1);
  luaE_warning(L, " (", 1);
  luaE_warning(L, msg, 1);
  luaE_warning(L, ")", 0);
}
References luaE_warning(), s2v, svalue, lua_State::top, and ttisstring.
Referenced by GCTM().
luaE_warning()
LUAI_FUNC void luaE_warning (lua_State * L, const char * msg, int tocont)
Definition at line 417 of file lua-5.4.3/src/lstate.c.
{
  lua_WarnFunction wf = G(L)->warnf;
  if (wf != NULL)
    wf(G(L)->ud_warn, msg, tocont);
}
References G, and NULL.
Referenced by lua_warning(), and luaE_warnerror().