Github User Fetcher: lgc.c File Reference
lgc.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
Macros
#define lgc_c
#define LUA_CORE
#define GCSinsideatomic (GCSpause + 1)
#define GCSWEEPCOST ((sizeof(TString) + 4) / 4)
#define GCSWEEPMAX (cast_int((GCSTEPSIZE / GCSWEEPCOST) / 4))
#define GCFINALIZECOST GCSWEEPCOST
#define STEPMULADJ 200
#define PAUSEADJ 100
#define maskcolors (~(bitmask(BLACKBIT) | WHITEBITS))
#define makewhite(g, x) (x->marked = cast_byte((x->marked & maskcolors) | luaC_white(g)))
#define white2gray(x) resetbits(x->marked, WHITEBITS)
#define black2gray(x) resetbit(x->marked, BLACKBIT)
#define valiswhite(x) (iscollectable(x) && iswhite(gcvalue(x)))
#define checkdeadkey(n) lua_assert(!ttisdeadkey(gkey(n)) || ttisnil(gval(n)))
#define checkconsistency(obj) lua_longassert(!iscollectable(obj) || righttt(obj))
#define markvalue(g, o)
#define markobject(g, t) { if (iswhite(t)) reallymarkobject(g, obj2gco(t)); }
#define markobjectN(g, t) { if (t) markobject(g,t); }
#define gnodelast(h) gnode(h, cast(size_t, sizenode(h)))
#define linkgclist(o, p) ((o)->gclist = (p), (p) = obj2gco(o))
#define sweepwholelist(L, p) sweeplist(L,p,MAX_LUMEM)
Functions
static void reallymarkobject (global_State *g, GCObject *o)
static void removeentry (Node *n)
static int iscleared (global_State *g, const TValue *o)
void luaC_barrier_ (lua_State *L, GCObject *o, GCObject *v)
void luaC_barrierback_ (lua_State *L, Table *t)
void luaC_upvalbarrier_ (lua_State *L, UpVal *uv)
void luaC_fix (lua_State *L, GCObject *o)
GCObject * luaC_newobj (lua_State *L, int tt, size_t sz)
static void markmt (global_State *g)
static void markbeingfnz (global_State *g)
static void remarkupvals (global_State *g)
static void restartcollection (global_State *g)
static void traverseweakvalue (global_State *g, Table *h)
static int traverseephemeron (global_State *g, Table *h)
static void traversestrongtable (global_State *g, Table *h)
static lu_mem traversetable (global_State *g, Table *h)
static int traverseproto (global_State *g, Proto *f)
static lu_mem traverseCclosure (global_State *g, CClosure *cl)
static lu_mem traverseLclosure (global_State *g, LClosure *cl)
static lu_mem traversethread (global_State *g, lua_State *th)
static void propagatemark (global_State *g)
static void propagateall (global_State *g)
static void convergeephemerons (global_State *g)
static void clearkeys (global_State *g, GCObject *l, GCObject *f)
static void clearvalues (global_State *g, GCObject *l, GCObject *f)
void luaC_upvdeccount (lua_State *L, UpVal *uv)
static void freeLclosure (lua_State *L, LClosure *cl)
static void freeobj (lua_State *L, GCObject *o)
static GCObject ** sweeplist (lua_State *L, GCObject **p, lu_mem count)
static GCObject ** sweeptolive (lua_State *L, GCObject **p)
static void checkSizes (lua_State *L, global_State *g)
static GCObject * udata2finalize (global_State *g)
static void dothecall (lua_State *L, void *ud)
static void GCTM (lua_State *L, int propagateerrors)
static int runafewfinalizers (lua_State *L)
static void callallpendingfinalizers (lua_State *L)
static GCObject ** findlast (GCObject **p)
static void separatetobefnz (global_State *g, int all)
void luaC_checkfinalizer (lua_State *L, GCObject *o, Table *mt)
static void setpause (global_State *g)
static void entersweep (lua_State *L)
void luaC_freeallobjects (lua_State *L)
static l_mem atomic (lua_State *L)
static lu_mem sweepstep (lua_State *L, global_State *g, int nextstate, GCObject **nextlist)
static lu_mem singlestep (lua_State *L)
void luaC_runtilstate (lua_State *L, int statesmask)
static l_mem getdebt (global_State *g)
void luaC_step (lua_State *L)
void luaC_fullgc (lua_State *L, int isemergency)
Macro Definition Documentation
black2gray
#define black2gray (x) resetbit(x->marked, BLACKBIT)
Definition at line 71 of file lua-5.3.6/src/lgc.c.
Referenced by luaC_barrierback_(), propagatemark(), and traversetable().
checkconsistency
#define checkconsistency (obj) lua_longassert(!iscollectable(obj) || righttt(obj))
Definition at line 79 of file lua-5.3.6/src/lgc.c.
#define checkconsistency(obj)  \
  lua_longassert(!iscollectable(obj) || righttt(obj))
checkdeadkey
#define checkdeadkey (n) lua_assert(!ttisdeadkey(gkey(n)) || ttisnil(gval(n)))
Definition at line 76 of file lua-5.3.6/src/lgc.c.
Referenced by traverseephemeron(), traversestrongtable(), and traverseweakvalue().
GCFINALIZECOST
#define GCFINALIZECOST GCSWEEPCOST
Definition at line 45 of file lua-5.3.6/src/lgc.c.
Referenced by singlestep().
GCSinsideatomic
#define GCSinsideatomic (GCSpause + 1)
Definition at line 33 of file lua-5.3.6/src/lgc.c.
Referenced by atomic(), traverseLclosure(), and traversethread().
GCSWEEPCOST
#define GCSWEEPCOST ((sizeof(TString) + 4) / 4)
Definition at line 39 of file lua-5.3.6/src/lgc.c.
Referenced by sweepstep().
GCSWEEPMAX
#define GCSWEEPMAX (cast_int((GCSTEPSIZE / GCSWEEPCOST) / 4))
Definition at line 42 of file lua-5.3.6/src/lgc.c.
Referenced by sweepstep().
gnodelast
#define gnodelast (h) gnode(h, cast(size_t, sizenode(h)))
Definition at line 107 of file lua-5.3.6/src/lgc.c.
Referenced by clearkeys(), clearvalues(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
lgc_c
#define lgc_c
Definition at line 7 of file lua-5.3.6/src/lgc.c.
linkgclist
#define linkgclist (o, p) ((o)->gclist = (p), (p) = obj2gco(o))
Definition at line 113 of file lua-5.3.6/src/lgc.c.
Referenced by luaC_barrierback_(), propagatemark(), reallymarkobject(), traverseephemeron(), traversetable(), and traverseweakvalue().
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/lgc.c.
makewhite
#define makewhite (g, x) (x->marked = cast_byte((x->marked & maskcolors) | luaC_white(g)))
Definition at line 67 of file lua-5.3.6/src/lgc.c.
#define makewhite(g,x)  \
 (x->marked = cast_byte((x->marked & maskcolors) | luaC_white(g)))
Referenced by luaC_barrier_(), luaC_checkfinalizer(), singlestep(), and udata2finalize().
markobject
#define markobject (g, t) { if (iswhite(t)) reallymarkobject(g, obj2gco(t)); }
Definition at line 86 of file lua-5.3.6/src/lgc.c.
Referenced by atomic(), iscleared(), luaC_upvalbarrier_(), markbeingfnz(), and restartcollection().
markobjectN
#define markobjectN (g, t) { if (t) markobject(g,t); }
Definition at line 92 of file lua-5.3.6/src/lgc.c.
Referenced by markmt(), reallymarkobject(), traverseLclosure(), traverseproto(), and traversetable().
markvalue
#define markvalue (g, o)
Value:
  { checkconsistency(o); \
  if (valiswhite(o)) reallymarkobject(g,gcvalue(o)); }
Definition at line 83 of file lua-5.3.6/src/lgc.c.
#define markvalue(g,o) { checkconsistency(o); \
  if (valiswhite(o)) reallymarkobject(g,gcvalue(o)); }
Referenced by atomic(), remarkupvals(), restartcollection(), traverseCclosure(), traverseLclosure(), traverseproto(), traversestrongtable(), traversethread(), and traverseweakvalue().
maskcolors
#define maskcolors (~(bitmask(BLACKBIT) | WHITEBITS))
Definition at line 66 of file lua-5.3.6/src/lgc.c.
Referenced by sweeplist().
PAUSEADJ
#define PAUSEADJ 100
Definition at line 59 of file lua-5.3.6/src/lgc.c.
Referenced by setpause().
STEPMULADJ
#define STEPMULADJ 200
Definition at line 52 of file lua-5.3.6/src/lgc.c.
Referenced by getdebt(), and luaC_step().
sweepwholelist
#define sweepwholelist (L, p) sweeplist(L,p,MAX_LUMEM)
Definition at line 724 of file lua-5.3.6/src/lgc.c.
Referenced by luaC_freeallobjects().
valiswhite
#define valiswhite (x) (iscollectable(x) && iswhite(gcvalue(x)))
Definition at line 74 of file lua-5.3.6/src/lgc.c.
Referenced by reallymarkobject(), removeentry(), and traverseephemeron().
white2gray
#define white2gray (x) resetbits(x->marked, WHITEBITS)
Definition at line 70 of file lua-5.3.6/src/lgc.c.
Referenced by luaC_fix(), and reallymarkobject().
Function Documentation
atomic()
static l_mem atomic (lua_State * L) static
Definition at line 982 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  l_mem work;
  GCObject *origweak, *origall;
  GCObject *grayagain = g->grayagain;  /* save original list */
  lua_assert(g->ephemeron == NULL && g->weak == NULL);
  lua_assert(!iswhite(g->mainthread));
  g->gcstate = GCSinsideatomic;
  g->GCmemtrav = 0;  /* start counting work */
  markobject(g, L);  /* mark running thread */
  /* registry and global metatables may be changed by API */
  markvalue(g, &g->l_registry);
  markmt(g);  /* mark global metatables */
  /* remark occasional upvalues of (maybe) dead threads */
  remarkupvals(g);
  propagateall(g);  /* propagate changes */
  work = g->GCmemtrav;  /* stop counting (do not recount 'grayagain') */
  g->gray = grayagain;
  propagateall(g);  /* traverse 'grayagain' list */
  g->GCmemtrav = 0;  /* restart counting */
  convergeephemerons(g);
  /* at this point, all strongly accessible objects are marked. */
  /* Clear values from weak tables, before checking finalizers */
  clearvalues(g, g->weak, NULL);
  clearvalues(g, g->allweak, NULL);
  origweak = g->weak; origall = g->allweak;
  work += g->GCmemtrav;  /* stop counting (objects being finalized) */
  separatetobefnz(g, 0);  /* separate objects to be finalized */
  g->gcfinnum = 1;  /* there may be objects to be finalized */
  markbeingfnz(g);  /* mark objects that will be finalized */
  propagateall(g);  /* remark, to propagate 'resurrection' */
  g->GCmemtrav = 0;  /* restart counting */
  convergeephemerons(g);
  /* at this point, all resurrected objects are marked. */
  /* remove dead objects from weak tables */
  clearkeys(g, g->ephemeron, NULL);  /* clear keys from all ephemeron tables */
  clearkeys(g, g->allweak, NULL);  /* clear keys from all 'allweak' tables */
  /* clear values from resurrected weak tables */
  clearvalues(g, g->weak, origweak);
  clearvalues(g, g->allweak, origall);
  luaS_clearcache(g);
  g->currentwhite = cast_byte(otherwhite(g));  /* flip current white */
  work += g->GCmemtrav;  /* complete counting */
  return work;  /* estimate of memory marked by 'atomic' */
}
References global_State::allweak, cast_byte, clearkeys(), clearvalues(), convergeephemerons(), global_State::currentwhite, global_State::ephemeron, G, global_State::gcfinnum, global_State::GCmemtrav, GCSinsideatomic, global_State::gcstate, global_State::gray, global_State::grayagain, iswhite, global_State::l_registry, lua_assert, luaS_clearcache(), global_State::mainthread, markbeingfnz(), markmt(), markobject, markvalue, NULL, otherwhite, propagateall(), remarkupvals(), separatetobefnz(), and global_State::weak.
Referenced by singlestep().
callallpendingfinalizers()
static void callallpendingfinalizers (lua_State * L) static
Definition at line 859 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  while (g->tobefnz)
    GCTM(L, 0);
}
References G, GCTM(), and global_State::tobefnz.
Referenced by luaC_freeallobjects().
checkSizes()
static void checkSizes (lua_State * L, global_State * g) static
Definition at line 778 of file lua-5.3.6/src/lgc.c.
{
  if (g->gckind != KGC_EMERGENCY) {
    l_mem olddebt = g->GCdebt;
    if (g->strt.nuse < g->strt.size / 4)  /* string table too big? */
      luaS_resize(L, g->strt.size / 2);  /* shrink it a little */
    g->GCestimate += g->GCdebt - olddebt;  /* update estimate */
  }
}
References global_State::GCdebt, global_State::GCestimate, global_State::gckind, KGC_EMERGENCY, luaS_resize(), stringtable::nuse, stringtable::size, and global_State::strt.
Referenced by singlestep().
clearkeys()
static void clearkeys (global_State * g, GCObject * l, GCObject * f) static
Definition at line 639 of file lua-5.3.6/src/lgc.c.
{
  for (; l != f; l = gco2t(l)->gclist) {
    Table *h = gco2t(l);
    Node *n, *limit = gnodelast(h);
    for (n = gnode(h, 0); n < limit; n++) {
      if (!ttisnil(gval(n)) && (iscleared(g, gkey(n)))) {
        setnilvalue(gval(n));  /* remove value ... */
      }
      if (ttisnil(gval(n)))  /* is entry empty? */
        removeentry(n);  /* remove entry from table */
    }
  }
}
References gco2t, gkey, gnode, gnodelast, gval, iscleared(), removeentry(), setnilvalue, and ttisnil.
Referenced by atomic().
clearvalues()
static void clearvalues (global_State * g, GCObject * l, GCObject * f) static
Definition at line 658 of file lua-5.3.6/src/lgc.c.
{
  for (; l != f; l = gco2t(l)->gclist) {
    Table *h = gco2t(l);
    Node *n, *limit = gnodelast(h);
    unsigned int i;
    for (i = 0; i < h->sizearray; i++) {
      TValue *o = &h->array[i];
      if (iscleared(g, o))  /* value was collected? */
        setnilvalue(o);  /* remove value */
    }
    for (n = gnode(h, 0); n < limit; n++) {
      if (!ttisnil(gval(n)) && iscleared(g, gval(n))) {
        setnilvalue(gval(n));  /* remove value ... */
        removeentry(n);  /* and remove entry from table */
      }
    }
  }
}
References Table::array, gco2t, gnode, gnodelast, gval, iscleared(), removeentry(), setnilvalue, Table::sizearray, and ttisnil.
Referenced by atomic().
convergeephemerons()
static void convergeephemerons (global_State * g) static
Definition at line 608 of file lua-5.3.6/src/lgc.c.
{
  int changed;
  do {
    GCObject *w;
    GCObject *next = g->ephemeron;  /* get ephemeron list */
    g->ephemeron = NULL;  /* tables may return to this list when traversed */
    changed = 0;
    while ((w = next) != NULL) {
      next = gco2t(w)->gclist;
      if (traverseephemeron(g, gco2t(w))) {  /* traverse marked some value? */
        propagateall(g);  /* propagate changes */
        changed = 1;  /* will have to revisit all ephemeron tables */
      }
    }
  } while (changed);
}
References global_State::ephemeron, gco2t, next, NULL, propagateall(), and traverseephemeron().
Referenced by atomic().
dothecall()
static void dothecall (lua_State * L, void * ud) static
Definition at line 801 of file lua-5.3.6/src/lgc.c.
{
  UNUSED(ud);
  luaD_callnoyield(L, L->top - 2, 0);
}
References luaD_callnoyield(), lua_State::top, and UNUSED.
Referenced by GCTM().
entersweep()
static void entersweep (lua_State * L) static
Definition at line 959 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  g->gcstate = GCSswpallgc;
  lua_assert(g->sweepgc == NULL);
  g->sweepgc = sweeplist(L, &g->allgc, 1);
}
References global_State::allgc, G, GCSswpallgc, global_State::gcstate, lua_assert, NULL, global_State::sweepgc, and sweeplist().
Referenced by luaC_fullgc(), and singlestep().
findlast()
static GCObject ** findlast (GCObject ** p) static
Definition at line 869 of file lua-5.3.6/src/lgc.c.
{
  while (*p != NULL)
    p = &(*p)->next;
  return p;
}
References NULL.
Referenced by separatetobefnz().
freeLclosure()
static void freeLclosure (lua_State * L, LClosure * cl) static
Definition at line 686 of file lua-5.3.6/src/lgc.c.
{
  int i;
  for (i = 0; i < cl->nupvalues; i++) {
    UpVal *uv = cl->upvals[i];
    if (uv)
      luaC_upvdeccount(L, uv);
  }
  luaM_freemem(L, cl, sizeLclosure(cl->nupvalues));
}
References luaC_upvdeccount(), luaM_freemem, sizeLclosure, and LClosure::upvals.
Referenced by freeobj().
freeobj()
static void freeobj (lua_State * L, GCObject * o) static
Definition at line 697 of file lua-5.3.6/src/lgc.c.
{
  switch (o->tt) {
    case LUA_TPROTO: luaF_freeproto(L, gco2p(o)); break;
    case LUA_TLCL: {
      freeLclosure(L, gco2lcl(o));
      break;
    }
    case LUA_TCCL: {
      luaM_freemem(L, o, sizeCclosure(gco2ccl(o)->nupvalues));
      break;
    }
    case LUA_TTABLE: luaH_free(L, gco2t(o)); break;
    case LUA_TTHREAD: luaE_freethread(L, gco2th(o)); break;
    case LUA_TUSERDATA: luaM_freemem(L, o, sizeudata(gco2u(o))); break;
    case LUA_TSHRSTR:
      luaS_remove(L, gco2ts(o));  /* remove it from hash table */
      luaM_freemem(L, o, sizelstring(gco2ts(o)->shrlen));
      break;
    case LUA_TLNGSTR: {
      luaM_freemem(L, o, sizelstring(gco2ts(o)->u.lnglen));
      break;
    }
    default: lua_assert(0);
  }
}
References freeLclosure(), gco2ccl, gco2lcl, gco2p, gco2t, gco2th, gco2ts, gco2u, lua_assert, LUA_TCCL, LUA_TLCL, LUA_TLNGSTR, LUA_TPROTO, LUA_TSHRSTR, LUA_TTABLE, LUA_TTHREAD, LUA_TUSERDATA, luaE_freethread(), luaF_freeproto(), luaH_free(), luaM_freemem, luaS_remove(), sizeCclosure, sizelstring, and sizeudata.
Referenced by sweeplist().
GCTM()
static void GCTM (lua_State * L, int propagateerrors) static
Definition at line 807 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  const TValue *tm;
  TValue v;
  setgcovalue(L, &v, udata2finalize(g));
  tm = luaT_gettmbyobj(L, &v, TM_GC);
  if (tm != NULL && ttisfunction(tm)) {  /* is there a finalizer? */
    int status;
    lu_byte oldah = L->allowhook;
    int running  = g->gcrunning;
    L->allowhook = 0;  /* stop debug hooks during GC metamethod */
    g->gcrunning = 0;  /* avoid GC steps */
    setobj2s(L, L->top, tm);  /* push finalizer... */
    setobj2s(L, L->top + 1, &v);  /* ... and its argument */
    L->top += 2;  /* and (next line) call the finalizer */
    L->ci->callstatus |= CIST_FIN;  /* will run a finalizer */
    status = luaD_pcall(L, dothecall, NULL, savestack(L, L->top - 2), 0);
    L->ci->callstatus &= ~CIST_FIN;  /* not running a finalizer anymore */
    L->allowhook = oldah;  /* restore hooks */
    g->gcrunning = running;  /* restore state */
    if (status != LUA_OK && propagateerrors) {  /* error while running __gc? */
      if (status == LUA_ERRRUN) {  /* is there an error object? */
        const char *msg = (ttisstring(L->top - 1))
                            ? svalue(L->top - 1)
                            : "no message";
        luaO_pushfstring(L, "error in __gc metamethod (%s)", msg);
        status = LUA_ERRGCMM;  /* error in __gc metamethod */
      }
      luaD_throw(L, status);  /* re-throw error */
    }
  }
}
References lua_State::allowhook, CallInfo::callstatus, lua_State::ci, CIST_FIN, dothecall(), G, global_State::gcrunning, LUA_ERRGCMM, LUA_ERRRUN, LUA_OK, luaD_pcall(), luaD_throw(), luaO_pushfstring(), luaT_gettmbyobj(), NULL, savestack, setgcovalue, setobj2s, svalue, TM_GC, lua_State::top, ttisfunction, ttisstring, and udata2finalize().
Referenced by callallpendingfinalizers(), and runafewfinalizers().
getdebt()
static l_mem getdebt (global_State * g) static
Definition at line 1115 of file lua-5.3.6/src/lgc.c.
{
  l_mem debt = g->GCdebt;
  int stepmul = g->gcstepmul;
  if (debt <= 0) return 0;  /* minimal debt */
  else {
    debt = (debt / STEPMULADJ) + 1;
    debt = (debt < MAX_LMEM / stepmul) ? debt * stepmul : MAX_LMEM;
    return debt;
  }
}
References global_State::GCdebt, global_State::gcstepmul, MAX_LMEM, and STEPMULADJ.
Referenced by luaC_step().
iscleared()
static int iscleared (global_State * g, const TValue * o) static
Definition at line 139 of file lua-5.3.6/src/lgc.c.
{
  if (!iscollectable(o)) return 0;
  else if (ttisstring(o)) {
    markobject(g, tsvalue(o));  /* strings are 'values', so are never weak */
    return 0;
  }
  else return iswhite(gcvalue(o));
}
References gcvalue, iscollectable, iswhite, markobject, tsvalue, and ttisstring.
Referenced by clearkeys(), clearvalues(), traverseephemeron(), and traverseweakvalue().
luaC_barrier_()
void luaC_barrier_ (lua_State * L, GCObject * o, GCObject * v)
Definition at line 155 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(isblack(o) && iswhite(v) && !isdead(g, v) && !isdead(g, o));
  if (keepinvariant(g))  /* must keep invariant? */
    reallymarkobject(g, v);  /* restore invariant */
  else {  /* sweep phase */
    lua_assert(issweepphase(g));
    makewhite(g, o);  /* mark main obj. as white to avoid other barriers */
  }
}
References G, isblack, isdead, issweepphase, iswhite, keepinvariant, lua_assert, makewhite, and reallymarkobject().
luaC_barrierback_()
void luaC_barrierback_ (lua_State * L, Table * t)
Definition at line 171 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(isblack(t) && !isdead(g, t));
  black2gray(t);  /* make table gray (again) */
  linkgclist(t, g->grayagain);
}
References black2gray, G, global_State::grayagain, isblack, isdead, linkgclist, and lua_assert.
luaC_checkfinalizer()
void luaC_checkfinalizer (lua_State * L, GCObject * o, Table * mt)
Definition at line 902 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  if (tofinalize(o) ||                 /* obj. is already marked... */
      gfasttm(g, mt, TM_GC) == NULL)   /* or has no finalizer? */
    return;  /* nothing to be done */
  else {  /* move 'o' to 'finobj' list */
    GCObject **p;
    if (issweepphase(g)) {
      makewhite(g, o);  /* "sweep" object 'o' */
      if (g->sweepgc == &o->next)  /* should not remove 'sweepgc' object */
        g->sweepgc = sweeptolive(L, g->sweepgc);  /* change 'sweepgc' */
    }
    /* search for pointer pointing to 'o' */
    for (p = &g->allgc; *p != o; p = &(*p)->next) { /* empty */ }
    *p = o->next;  /* remove 'o' from 'allgc' list */
    o->next = g->finobj;  /* link it in 'finobj' list */
    g->finobj = o;
    l_setbit(o->marked, FINALIZEDBIT);  /* mark it as such */
  }
}
References global_State::allgc, FINALIZEDBIT, global_State::finobj, G, gfasttm, issweepphase, l_setbit, makewhite, NULL, global_State::sweepgc, sweeptolive(), TM_GC, and tofinalize.
luaC_fix()
void luaC_fix (lua_State * L, GCObject * o)
Definition at line 194 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(g->allgc == o);  /* object must be 1st in 'allgc' list! */
  white2gray(o);  /* they will be gray forever */
  g->allgc = o->next;  /* remove object from 'allgc' list */
  o->next = g->fixedgc;  /* link it to 'fixedgc' list */
  g->fixedgc = o;
}
References global_State::allgc, global_State::fixedgc, G, lua_assert, and white2gray.
Referenced by luaS_init(), luaT_init(), and luaX_init().
luaC_freeallobjects()
void luaC_freeallobjects (lua_State * L)
Definition at line 967 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  separatetobefnz(g, 1);  /* separate all objects with finalizers */
  lua_assert(g->finobj == NULL);
  callallpendingfinalizers(L);
  lua_assert(g->tobefnz == NULL);
  g->currentwhite = WHITEBITS; /* this "white" makes all objects look dead */
  g->gckind = KGC_NORMAL;
  sweepwholelist(L, &g->finobj);
  sweepwholelist(L, &g->allgc);
  sweepwholelist(L, &g->fixedgc);  /* collect fixed objects */
  lua_assert(g->strt.nuse == 0);
}
References global_State::allgc, callallpendingfinalizers(), global_State::currentwhite, global_State::finobj, global_State::fixedgc, G, global_State::gckind, KGC_NORMAL, lua_assert, NULL, stringtable::nuse, separatetobefnz(), global_State::strt, sweepwholelist, global_State::tobefnz, and WHITEBITS.
luaC_fullgc()
void luaC_fullgc (lua_State * L, int isemergency)
Definition at line 1159 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(g->gckind == KGC_NORMAL);
  if (isemergency) g->gckind = KGC_EMERGENCY;  /* set flag */
  if (keepinvariant(g)) {  /* black objects? */
    entersweep(L); /* sweep everything to turn them back to white */
  }
  /* finish any pending sweep phase to start a new cycle */
  luaC_runtilstate(L, bitmask(GCSpause));
  luaC_runtilstate(L, ~bitmask(GCSpause));  /* start new collection */
  luaC_runtilstate(L, bitmask(GCScallfin));  /* run up to finalizers */
  /* estimate must be correct after a full GC cycle */
  lua_assert(g->GCestimate == gettotalbytes(g));
  luaC_runtilstate(L, bitmask(GCSpause));  /* finish collection */
  g->gckind = KGC_NORMAL;
  setpause(g);
}
References bitmask, entersweep(), G, global_State::GCestimate, global_State::gckind, GCScallfin, GCSpause, gettotalbytes, keepinvariant, KGC_EMERGENCY, KGC_NORMAL, lua_assert, luaC_runtilstate(), and setpause().
luaC_newobj()
GCObject * luaC_newobj (lua_State * L, int tt, size_t sz)
Definition at line 208 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  GCObject *o = cast(GCObject *, luaM_newobject(L, novariant(tt), sz));
  o->marked = luaC_white(g);
  o->tt = tt;
  o->next = g->allgc;
  g->allgc = o;
  return o;
}
References global_State::allgc, cast, G, luaC_white, luaM_newobject, and novariant.
luaC_runtilstate()
void luaC_runtilstate (lua_State * L, int statesmask)
Definition at line 1104 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  while (!testbit(statesmask, g->gcstate))
    singlestep(L);
}
References G, global_State::gcstate, singlestep(), and testbit.
Referenced by luaC_fullgc().
luaC_step()
void luaC_step (lua_State * L)
Definition at line 1129 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  l_mem debt = getdebt(g);  /* GC deficit (be paid now) */
  if (!g->gcrunning) {  /* not running? */
    luaE_setdebt(g, -GCSTEPSIZE * 10);  /* avoid being called too often */
    return;
  }
  do {  /* repeat until pause or enough "credit" (negative debt) */
    lu_mem work = singlestep(L);  /* perform one single step */
    debt -= work;
  } while (debt > -GCSTEPSIZE && g->gcstate != GCSpause);
  if (g->gcstate == GCSpause)
    setpause(g);  /* pause until next cycle */
  else {
    debt = (debt / g->gcstepmul) * STEPMULADJ;  /* convert 'work units' to Kb */
    luaE_setdebt(g, debt);
    runafewfinalizers(L);
  }
}
References G, global_State::gcrunning, GCSpause, global_State::gcstate, global_State::gcstepmul, GCSTEPSIZE, getdebt(), luaE_setdebt(), runafewfinalizers(), setpause(), singlestep(), and STEPMULADJ.
luaC_upvalbarrier_()
void luaC_upvalbarrier_ (lua_State * L, UpVal * uv)
Definition at line 185 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  GCObject *o = gcvalue(uv->v);
  lua_assert(!upisopen(uv));  /* ensured by macro luaC_upvalbarrier */
  if (keepinvariant(g))
    markobject(g, o);
}
References G, gcvalue, keepinvariant, lua_assert, markobject, upisopen, and UpVal::v.
luaC_upvdeccount()
void luaC_upvdeccount (lua_State * L, UpVal * uv)
Definition at line 678 of file lua-5.3.6/src/lgc.c.
{
  lua_assert(uv->refcount > 0);
  uv->refcount--;
  if (uv->refcount == 0 && !upisopen(uv))
    luaM_free(L, uv);
}
References lua_assert, luaM_free, UpVal::refcount, and upisopen.
Referenced by freeLclosure(), and lua_upvaluejoin().
markbeingfnz()
static void markbeingfnz (global_State * g) static
Definition at line 299 of file lua-5.3.6/src/lgc.c.
{
  GCObject *o;
  for (o = g->tobefnz; o != NULL; o = o->next)
    markobject(g, o);
}
References markobject, NULL, and global_State::tobefnz.
Referenced by atomic(), and restartcollection().
markmt()
static void markmt (global_State * g) static
Definition at line 289 of file lua-5.3.6/src/lgc.c.
{
  int i;
  for (i=0; i < LUA_NUMTAGS; i++)
    markobjectN(g, g->mt[i]);
}
References LUA_NUMTAGS, markobjectN, and global_State::mt.
Referenced by atomic(), and restartcollection().
propagateall()
static void propagateall (global_State * g) static
Definition at line 603 of file lua-5.3.6/src/lgc.c.
{
  while (g->gray) propagatemark(g);
}
References global_State::gray, and propagatemark().
Referenced by atomic(), convergeephemerons(), and singlestep().
propagatemark()
static void propagatemark (global_State * g) static
Definition at line 559 of file lua-5.3.6/src/lgc.c.
{
  lu_mem size;
  GCObject *o = g->gray;
  lua_assert(isgray(o));
  gray2black(o);
  switch (o->tt) {
    case LUA_TTABLE: {
      Table *h = gco2t(o);
      g->gray = h->gclist;  /* remove from 'gray' list */
      size = traversetable(g, h);
      break;
    }
    case LUA_TLCL: {
      LClosure *cl = gco2lcl(o);
      g->gray = cl->gclist;  /* remove from 'gray' list */
      size = traverseLclosure(g, cl);
      break;
    }
    case LUA_TCCL: {
      CClosure *cl = gco2ccl(o);
      g->gray = cl->gclist;  /* remove from 'gray' list */
      size = traverseCclosure(g, cl);
      break;
    }
    case LUA_TTHREAD: {
      lua_State *th = gco2th(o);
      g->gray = th->gclist;  /* remove from 'gray' list */
      linkgclist(th, g->grayagain);  /* insert into 'grayagain' list */
      black2gray(o);
      size = traversethread(g, th);
      break;
    }
    case LUA_TPROTO: {
      Proto *p = gco2p(o);
      g->gray = p->gclist;  /* remove from 'gray' list */
      size = traverseproto(g, p);
      break;
    }
    default: lua_assert(0); return;
  }
  g->GCmemtrav += size;
}
References black2gray, Proto::gclist, Table::gclist, lua_State::gclist, global_State::GCmemtrav, gco2ccl, gco2lcl, gco2p, gco2t, gco2th, global_State::gray, gray2black, global_State::grayagain, isgray, linkgclist, lua_assert, LUA_TCCL, LUA_TLCL, LUA_TPROTO, LUA_TTABLE, LUA_TTHREAD, traverseCclosure(), traverseLclosure(), traverseproto(), traversetable(), and traversethread().
Referenced by propagateall(), and singlestep().
reallymarkobject()
static void reallymarkobject (global_State * g, GCObject * o) static
Definition at line 235 of file lua-5.3.6/src/lgc.c.
{
 reentry:
  white2gray(o);
  switch (o->tt) {
    case LUA_TSHRSTR: {
      gray2black(o);
      g->GCmemtrav += sizelstring(gco2ts(o)->shrlen);
      break;
    }
    case LUA_TLNGSTR: {
      gray2black(o);
      g->GCmemtrav += sizelstring(gco2ts(o)->u.lnglen);
      break;
    }
    case LUA_TUSERDATA: {
      TValue uvalue;
      markobjectN(g, gco2u(o)->metatable);  /* mark its metatable */
      gray2black(o);
      g->GCmemtrav += sizeudata(gco2u(o));
      getuservalue(g->mainthread, gco2u(o), &uvalue);
      if (valiswhite(&uvalue)) {  /* markvalue(g, &uvalue); */
        o = gcvalue(&uvalue);
        goto reentry;
      }
      break;
    }
    case LUA_TLCL: {
      linkgclist(gco2lcl(o), g->gray);
      break;
    }
    case LUA_TCCL: {
      linkgclist(gco2ccl(o), g->gray);
      break;
    }
    case LUA_TTABLE: {
      linkgclist(gco2t(o), g->gray);
      break;
    }
    case LUA_TTHREAD: {
      linkgclist(gco2th(o), g->gray);
      break;
    }
    case LUA_TPROTO: {
      linkgclist(gco2p(o), g->gray);
      break;
    }
    default: lua_assert(0); break;
  }
}
References global_State::GCmemtrav, gco2ccl, gco2lcl, gco2p, gco2t, gco2th, gco2ts, gco2u, gcvalue, getuservalue, global_State::gray, gray2black, linkgclist, lua_assert, LUA_TCCL, LUA_TLCL, LUA_TLNGSTR, LUA_TPROTO, LUA_TSHRSTR, LUA_TTABLE, LUA_TTHREAD, LUA_TUSERDATA, global_State::mainthread, markobjectN, sizelstring, sizeudata, uvalue, valiswhite, and white2gray.
Referenced by luaC_barrier_(), and traverseephemeron().
remarkupvals()
static void remarkupvals (global_State * g) static
Definition at line 312 of file lua-5.3.6/src/lgc.c.
{
  lua_State *thread;
  lua_State **p = &g->twups;
  while ((thread = *p) != NULL) {
    lua_assert(!isblack(thread));  /* threads are never black */
    if (isgray(thread) && thread->openupval != NULL)
      p = &thread->twups;  /* keep marked thread with upvalues in the list */
    else {  /* thread is not marked or without upvalues */
      UpVal *uv;
      *p = thread->twups;  /* remove thread from the list */
      thread->twups = thread;  /* mark that it is out of list */
      for (uv = thread->openupval; uv != NULL; uv = uv->u.open.next) {
        if (uv->u.open.touched) {
          markvalue(g, uv->v);  /* remark upvalue's value */
          uv->u.open.touched = 0;
        }
      }
    }
  }
}
References isblack, isgray, lua_assert, markvalue, UpVal::next, NULL, UpVal::open, lua_State::openupval, UpVal::touched, global_State::twups, lua_State::twups, UpVal::u, and UpVal::v.
Referenced by atomic().
removeentry()
static void removeentry (Node * n) static
Definition at line 125 of file lua-5.3.6/src/lgc.c.
{
  lua_assert(ttisnil(gval(n)));
  if (valiswhite(gkey(n)))
    setdeadvalue(wgkey(n));  /* unused and unmarked key; remove it */
}
References gkey, gval, lua_assert, setdeadvalue, ttisnil, valiswhite, and wgkey.
Referenced by clearkeys(), clearvalues(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
restartcollection()
static void restartcollection (global_State * g) static
Definition at line 337 of file lua-5.3.6/src/lgc.c.
{
  g->gray = g->grayagain = NULL;
  g->weak = g->allweak = g->ephemeron = NULL;
  markobject(g, g->mainthread);
  markvalue(g, &g->l_registry);
  markmt(g);
  markbeingfnz(g);  /* mark any finalizing object left from previous cycle */
}
References global_State::allweak, global_State::ephemeron, global_State::gray, global_State::grayagain, global_State::l_registry, global_State::mainthread, markbeingfnz(), markmt(), markobject, markvalue, NULL, and global_State::weak.
Referenced by singlestep().
runafewfinalizers()
static int runafewfinalizers (lua_State * L) static
Definition at line 844 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  unsigned int i;
  lua_assert(!g->tobefnz || g->gcfinnum > 0);
  for (i = 0; g->tobefnz && i < g->gcfinnum; i++)
    GCTM(L, 1);  /* call one finalizer */
  g->gcfinnum = (!g->tobefnz) ? 0  /* nothing more to finalize? */
                    : g->gcfinnum * 2;  /* else call a few more next time */
  return i;
}
References G, global_State::gcfinnum, GCTM(), lua_assert, and global_State::tobefnz.
Referenced by luaC_step(), and singlestep().
separatetobefnz()
static void separatetobefnz (global_State * g, int all) static
Definition at line 880 of file lua-5.3.6/src/lgc.c.
{
  GCObject *curr;
  GCObject **p = &g->finobj;
  GCObject **lastnext = findlast(&g->tobefnz);
  while ((curr = *p) != NULL) {  /* traverse all finalizable objects */
    lua_assert(tofinalize(curr));
    if (!(iswhite(curr) || all))  /* not being collected? */
      p = &curr->next;  /* don't bother with it */
    else {
      *p = curr->next;  /* remove 'curr' from 'finobj' list */
      curr->next = *lastnext;  /* link at the end of 'tobefnz' list */
      *lastnext = curr;
      lastnext = &curr->next;
    }
  }
}
References findlast(), global_State::finobj, iswhite, lua_assert, NULL, global_State::tobefnz, and tofinalize.
Referenced by atomic(), and luaC_freeallobjects().
setpause()
static void setpause (global_State * g) static
Definition at line 940 of file lua-5.3.6/src/lgc.c.
{
  l_mem threshold, debt;
  l_mem estimate = g->GCestimate / PAUSEADJ;  /* adjust 'estimate' */
  lua_assert(estimate > 0);
  threshold = (g->gcpause < MAX_LMEM / estimate)  /* overflow? */
            ? estimate * g->gcpause  /* no overflow */
            : MAX_LMEM;  /* overflow; truncate to maximum */
  debt = gettotalbytes(g) - threshold;
  luaE_setdebt(g, debt);
}
References global_State::GCestimate, global_State::gcpause, gettotalbytes, lua_assert, luaE_setdebt(), MAX_LMEM, and PAUSEADJ.
Referenced by luaC_fullgc(), and luaC_step().
singlestep()
static lu_mem singlestep (lua_State * L) static
Definition at line 1045 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  switch (g->gcstate) {
    case GCSpause: {
      g->GCmemtrav = g->strt.size * sizeof(GCObject*);
      restartcollection(g);
      g->gcstate = GCSpropagate;
      return g->GCmemtrav;
    }
    case GCSpropagate: {
      g->GCmemtrav = 0;
      lua_assert(g->gray);
      propagatemark(g);
       if (g->gray == NULL)  /* no more gray objects? */
        g->gcstate = GCSatomic;  /* finish propagate phase */
      return g->GCmemtrav;  /* memory traversed in this step */
    }
    case GCSatomic: {
      lu_mem work;
      propagateall(g);  /* make sure gray list is empty */
      work = atomic(L);  /* work is what was traversed by 'atomic' */
      entersweep(L);
      g->GCestimate = gettotalbytes(g);  /* first estimate */;
      return work;
    }
    case GCSswpallgc: {  /* sweep "regular" objects */
      return sweepstep(L, g, GCSswpfinobj, &g->finobj);
    }
    case GCSswpfinobj: {  /* sweep objects with finalizers */
      return sweepstep(L, g, GCSswptobefnz, &g->tobefnz);
    }
    case GCSswptobefnz: {  /* sweep objects to be finalized */
      return sweepstep(L, g, GCSswpend, NULL);
    }
    case GCSswpend: {  /* finish sweeps */
      makewhite(g, g->mainthread);  /* sweep main thread */
      checkSizes(L, g);
      g->gcstate = GCScallfin;
      return 0;
    }
    case GCScallfin: {  /* call remaining finalizers */
      if (g->tobefnz && g->gckind != KGC_EMERGENCY) {
        int n = runafewfinalizers(L);
        return (n * GCFINALIZECOST);
      }
      else {  /* emergency mode or no more finalizers */
        g->gcstate = GCSpause;  /* finish collection */
        return 0;
      }
    }
    default: lua_assert(0); return 0;
  }
}
References atomic(), checkSizes(), entersweep(), global_State::finobj, G, global_State::GCestimate, GCFINALIZECOST, global_State::gckind, global_State::GCmemtrav, GCSatomic, GCScallfin, GCSpause, GCSpropagate, GCSswpallgc, GCSswpend, GCSswpfinobj, GCSswptobefnz, global_State::gcstate, gettotalbytes, global_State::gray, KGC_EMERGENCY, lua_assert, global_State::mainthread, makewhite, NULL, propagateall(), propagatemark(), restartcollection(), runafewfinalizers(), stringtable::size, global_State::strt, sweepstep(), and global_State::tobefnz.
Referenced by luaC_runtilstate(), and luaC_step().
sweeplist()
static GCObject ** sweeplist (lua_State * L, GCObject ** p, lu_mem count) static
Definition at line 735 of file lua-5.3.6/src/lgc.c.
{
  global_State *g = G(L);
  int ow = otherwhite(g);
  int white = luaC_white(g);  /* current white */
  while (*p != NULL && count-- > 0) {
    GCObject *curr = *p;
    int marked = curr->marked;
    if (isdeadm(ow, marked)) {  /* is 'curr' dead? */
      *p = curr->next;  /* remove 'curr' from list */
      freeobj(L, curr);  /* erase 'curr' */
    }
    else {  /* change mark to 'white' */
      curr->marked = cast_byte((marked & maskcolors) | white);
      p = &curr->next;  /* go to next element */
    }
  }
  return (*p == NULL) ? NULL : p;
}
References cast_byte, freeobj(), G, isdeadm, luaC_white, maskcolors, NULL, and otherwhite.
Referenced by entersweep(), sweepstep(), and sweeptolive().
sweepstep()
static lu_mem sweepstep (lua_State * L, global_State * g, int nextstate, GCObject ** nextlist) static
Definition at line 1029 of file lua-5.3.6/src/lgc.c.
{
  if (g->sweepgc) {
    l_mem olddebt = g->GCdebt;
    g->sweepgc = sweeplist(L, g->sweepgc, GCSWEEPMAX);
    g->GCestimate += g->GCdebt - olddebt;  /* update estimate */
    if (g->sweepgc)  /* is there still something to sweep? */
      return (GCSWEEPMAX * GCSWEEPCOST);
  }
  /* else enter next state */
  g->gcstate = nextstate;
  g->sweepgc = nextlist;
  return 0;
}
References global_State::GCdebt, global_State::GCestimate, global_State::gcstate, GCSWEEPCOST, GCSWEEPMAX, global_State::sweepgc, and sweeplist().
Referenced by singlestep().
sweeptolive()
static GCObject ** sweeptolive (lua_State * L, GCObject ** p) static
Definition at line 758 of file lua-5.3.6/src/lgc.c.
{
  GCObject **old = p;
  do {
    p = sweeplist(L, p, 1);
  } while (p == old);
  return p;
}
References sweeplist().
Referenced by luaC_checkfinalizer().
traverseCclosure()
static lu_mem traverseCclosure (global_State * g, CClosure * cl) static
Definition at line 501 of file lua-5.3.6/src/lgc.c.
{
  int i;
  for (i = 0; i < cl->nupvalues; i++)  /* mark its upvalues */
    markvalue(g, &cl->upvalue[i]);
  return sizeCclosure(cl->nupvalues);
}
References markvalue, sizeCclosure, and CClosure::upvalue.
Referenced by propagatemark().
traverseephemeron()
static int traverseephemeron (global_State * g, Table * h) static
Definition at line 394 of file lua-5.3.6/src/lgc.c.
{
  int marked = 0;  /* true if an object is marked in this traversal */
  int hasclears = 0;  /* true if table has white keys */
  int hasww = 0;  /* true if table has entry "white-key -> white-value" */
  Node *n, *limit = gnodelast(h);
  unsigned int i;
  /* traverse array part */
  for (i = 0; i < h->sizearray; i++) {
    if (valiswhite(&h->array[i])) {
      marked = 1;
      reallymarkobject(g, gcvalue(&h->array[i]));
    }
  }
  /* traverse hash part */
  for (n = gnode(h, 0); n < limit; n++) {
    checkdeadkey(n);
    if (ttisnil(gval(n)))  /* entry is empty? */
      removeentry(n);  /* remove it */
    else if (iscleared(g, gkey(n))) {  /* key is not marked (yet)? */
      hasclears = 1;  /* table must be cleared */
      if (valiswhite(gval(n)))  /* value not marked yet? */
        hasww = 1;  /* white-white entry */
    }
    else if (valiswhite(gval(n))) {  /* value not marked yet? */
      marked = 1;
      reallymarkobject(g, gcvalue(gval(n)));  /* mark it now */
    }
  }
  /* link table into proper list */
  if (g->gcstate == GCSpropagate)
    linkgclist(h, g->grayagain);  /* must retraverse it in atomic phase */
  else if (hasww)  /* table has white->white entries? */
    linkgclist(h, g->ephemeron);  /* have to propagate again */
  else if (hasclears)  /* table has white keys? */
    linkgclist(h, g->allweak);  /* may have to clean white keys */
  return marked;
}
References global_State::allweak, Table::array, checkdeadkey, global_State::ephemeron, GCSpropagate, global_State::gcstate, gcvalue, gkey, gnode, gnodelast, global_State::grayagain, gval, iscleared(), linkgclist, reallymarkobject(), removeentry(), Table::sizearray, ttisnil, and valiswhite.
Referenced by convergeephemerons(), and traversetable().
traverseLclosure()
static lu_mem traverseLclosure (global_State * g, LClosure * cl) static
Definition at line 514 of file lua-5.3.6/src/lgc.c.
{
  int i;
  markobjectN(g, cl->p);  /* mark its prototype */
  for (i = 0; i < cl->nupvalues; i++) {  /* mark its upvalues */
    UpVal *uv = cl->upvals[i];
    if (uv != NULL) {
      if (upisopen(uv) && g->gcstate != GCSinsideatomic)
        uv->u.open.touched = 1;  /* can be marked in 'remarkupvals' */
      else
        markvalue(g, uv->v);
    }
  }
  return sizeLclosure(cl->nupvalues);
}
References GCSinsideatomic, global_State::gcstate, markobjectN, markvalue, NULL, UpVal::open, LClosure::p, sizeLclosure, UpVal::touched, UpVal::u, upisopen, LClosure::upvals, and UpVal::v.
Referenced by propagatemark().
traverseproto()
static int traverseproto (global_State * g, Proto * f) static
Definition at line 479 of file lua-5.3.6/src/lgc.c.
{
  int i;
  if (f->cache && iswhite(f->cache))
    f->cache = NULL;  /* allow cache to be collected */
  markobjectN(g, f->source);
  for (i = 0; i < f->sizek; i++)  /* mark literals */
    markvalue(g, &f->k[i]);
  for (i = 0; i < f->sizeupvalues; i++)  /* mark upvalue names */
    markobjectN(g, f->upvalues[i].name);
  for (i = 0; i < f->sizep; i++)  /* mark nested protos */
    markobjectN(g, f->p[i]);
  for (i = 0; i < f->sizelocvars; i++)  /* mark local-variable names */
    markobjectN(g, f->locvars[i].varname);
  return sizeof(Proto) + sizeof(Instruction) * f->sizecode +
                         sizeof(Proto *) * f->sizep +
                         sizeof(TValue) * f->sizek +
                         sizeof(int) * f->sizelineinfo +
                         sizeof(LocVar) * f->sizelocvars +
                         sizeof(Upvaldesc) * f->sizeupvalues;
}
References Proto::cache, iswhite, Proto::k, Proto::locvars, markobjectN, markvalue, NULL, Proto::p, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, Proto::upvalues, and LocVar::varname.
Referenced by propagatemark().
traversestrongtable()
static void traversestrongtable (global_State * g, Table * h) static
Definition at line 433 of file lua-5.3.6/src/lgc.c.
{
  Node *n, *limit = gnodelast(h);
  unsigned int i;
  for (i = 0; i < h->sizearray; i++)  /* traverse array part */
    markvalue(g, &h->array[i]);
  for (n = gnode(h, 0); n < limit; n++) {  /* traverse hash part */
    checkdeadkey(n);
    if (ttisnil(gval(n)))  /* entry is empty? */
      removeentry(n);  /* remove it */
    else {
      lua_assert(!ttisnil(gkey(n)));
      markvalue(g, gkey(n));  /* mark key */
      markvalue(g, gval(n));  /* mark value */
    }
  }
}
References Table::array, checkdeadkey, gkey, gnode, gnodelast, gval, lua_assert, markvalue, removeentry(), Table::sizearray, and ttisnil.
Referenced by traversetable().
traversetable()
static lu_mem traversetable (global_State * g, Table * h) static
Definition at line 451 of file lua-5.3.6/src/lgc.c.
{
  const char *weakkey, *weakvalue;
  const TValue *mode = gfasttm(g, h->metatable, TM_MODE);
  markobjectN(g, h->metatable);
  if (mode && ttisstring(mode) &&  /* is there a weak mode? */
      ((weakkey = strchr(svalue(mode), 'k')),
       (weakvalue = strchr(svalue(mode), 'v')),
       (weakkey || weakvalue))) {  /* is really weak? */
    black2gray(h);  /* keep table gray */
    if (!weakkey)  /* strong keys? */
      traverseweakvalue(g, h);
    else if (!weakvalue)  /* strong values? */
      traverseephemeron(g, h);
    else  /* all weak */
      linkgclist(h, g->allweak);  /* nothing to traverse now */
  }
  else  /* not weak */
    traversestrongtable(g, h);
  return sizeof(Table) + sizeof(TValue) * h->sizearray +
                         sizeof(Node) * cast(size_t, allocsizenode(h));
}
References allocsizenode, global_State::allweak, black2gray, cast, gfasttm, linkgclist, markobjectN, Table::metatable, Table::sizearray, svalue, TM_MODE, traverseephemeron(), traversestrongtable(), traverseweakvalue(), and ttisstring.
Referenced by propagatemark().
traversethread()
static lu_mem traversethread (global_State * g, lua_State * th) static
Definition at line 530 of file lua-5.3.6/src/lgc.c.
{
  StkId o = th->stack;
  if (o == NULL)
    return 1;  /* stack not completely built yet */
  lua_assert(g->gcstate == GCSinsideatomic ||
             th->openupval == NULL || isintwups(th));
  for (; o < th->top; o++)  /* mark live elements in the stack */
    markvalue(g, o);
  if (g->gcstate == GCSinsideatomic) {  /* final traversal? */
    StkId lim = th->stack + th->stacksize;  /* real end of stack */
    for (; o < lim; o++)  /* clear not-marked stack slice */
      setnilvalue(o);
    /* 'remarkupvals' may have removed thread from 'twups' list */
    if (!isintwups(th) && th->openupval != NULL) {
      th->twups = g->twups;  /* link it back to the list */
      g->twups = th;
    }
  }
  else if (g->gckind != KGC_EMERGENCY)
    luaD_shrinkstack(th); /* do not change stack in emergency cycle */
  return (sizeof(lua_State) + sizeof(TValue) * th->stacksize +
          sizeof(CallInfo) * th->nci);
}
References global_State::gckind, GCSinsideatomic, global_State::gcstate, isintwups, KGC_EMERGENCY, lua_assert, luaD_shrinkstack(), markvalue, lua_State::nci, NULL, lua_State::openupval, setnilvalue, lua_State::stack, lua_State::stacksize, lua_State::top, global_State::twups, and lua_State::twups.
Referenced by propagatemark().
traverseweakvalue()
static void traverseweakvalue (global_State * g, Table * h) static
Definition at line 361 of file lua-5.3.6/src/lgc.c.
{
  Node *n, *limit = gnodelast(h);
  /* if there is array part, assume it may have white values (it is not
     worth traversing it now just to check) */
  int hasclears = (h->sizearray > 0);
  for (n = gnode(h, 0); n < limit; n++) {  /* traverse hash part */
    checkdeadkey(n);
    if (ttisnil(gval(n)))  /* entry is empty? */
      removeentry(n);  /* remove it */
    else {
      lua_assert(!ttisnil(gkey(n)));
      markvalue(g, gkey(n));  /* mark key */
      if (!hasclears && iscleared(g, gval(n)))  /* is there a white value? */
        hasclears = 1;  /* table will have to be cleared */
    }
  }
  if (g->gcstate == GCSpropagate)
    linkgclist(h, g->grayagain);  /* must retraverse it in atomic phase */
  else if (hasclears)
    linkgclist(h, g->weak);  /* has to be cleared later */
}
References checkdeadkey, GCSpropagate, global_State::gcstate, gkey, gnode, gnodelast, global_State::grayagain, gval, iscleared(), linkgclist, lua_assert, markvalue, removeentry(), Table::sizearray, ttisnil, and global_State::weak.
Referenced by traversetable().
udata2finalize()
static GCObject * udata2finalize (global_State * g) static
Definition at line 788 of file lua-5.3.6/src/lgc.c.
{
  GCObject *o = g->tobefnz;  /* get first element */
  lua_assert(tofinalize(o));
  g->tobefnz = o->next;  /* remove it from 'tobefnz' list */
  o->next = g->allgc;  /* return it to 'allgc' list */
  g->allgc = o;
  resetbit(o->marked, FINALIZEDBIT);  /* object is "normal" again */
  if (issweepphase(g))
    makewhite(g, o);  /* "sweep" object */
  return o;
}
References global_State::allgc, FINALIZEDBIT, issweepphase, lua_assert, makewhite, resetbit, global_State::tobefnz, and tofinalize.
Referenced by GCTM().