Github User Fetcher: ldo.h File Reference
ldo.h File Reference
#include "lobject.h"
#include "lstate.h"
#include "lzio.h"
Macros
#define luaD_checkstackaux(L, n, pre, pos)
#define luaD_checkstack(L, n) luaD_checkstackaux(L,n,(void)0,(void)0)
#define savestack(L, p) ((char *)(p) - (char *)L->stack)
#define restorestack(L, n) ((StkId)((char *)L->stack + (n)))
#define checkstackGCp(L, n, p)
#define checkstackGC(L, fsize) luaD_checkstackaux(L, (fsize), luaC_checkGC(L), (void)0)
Typedefs
typedef void(* Pfunc) (lua_State *L, void *ud)
Functions
LUAI_FUNC void luaD_seterrorobj (lua_State *L, int errcode, StkId oldtop)
LUAI_FUNC int luaD_protectedparser (lua_State *L, ZIO *z, const char *name, const char *mode)
LUAI_FUNC void luaD_hook (lua_State *L, int event, int line, int fTransfer, int nTransfer)
LUAI_FUNC void luaD_hookcall (lua_State *L, CallInfo *ci)
LUAI_FUNC void luaD_pretailcall (lua_State *L, CallInfo *ci, StkId func, int n)
LUAI_FUNC CallInfo * luaD_precall (lua_State *L, StkId func, int nResults)
LUAI_FUNC void luaD_call (lua_State *L, StkId func, int nResults)
LUAI_FUNC void luaD_callnoyield (lua_State *L, StkId func, int nResults)
LUAI_FUNC void luaD_tryfuncTM (lua_State *L, StkId func)
LUAI_FUNC int luaD_closeprotected (lua_State *L, ptrdiff_t level, int status)
LUAI_FUNC int luaD_pcall (lua_State *L, Pfunc func, void *u, ptrdiff_t oldtop, ptrdiff_t ef)
LUAI_FUNC void luaD_poscall (lua_State *L, CallInfo *ci, int nres)
LUAI_FUNC int luaD_reallocstack (lua_State *L, int newsize, int raiseerror)
LUAI_FUNC int luaD_growstack (lua_State *L, int n, int raiseerror)
LUAI_FUNC void luaD_shrinkstack (lua_State *L)
LUAI_FUNC void luaD_inctop (lua_State *L)
LUAI_FUNC l_noret luaD_throw (lua_State *L, int errcode)
LUAI_FUNC int luaD_rawrunprotected (lua_State *L, Pfunc f, void *ud)
Macro Definition Documentation
checkstackGC
#define checkstackGC (L, fsize) luaD_checkstackaux(L, (fsize), luaC_checkGC(L), (void)0)
Definition at line 48 of file lua-5.4.3/src/ldo.h.
#define checkstackGC(L,fsize)  \
    luaD_checkstackaux(L, (fsize), luaC_checkGC(L), (void)0)
Referenced by luaD_pretailcall().
checkstackGCp
#define checkstackGCp (L, n, p)
Value:
  luaD_checkstackaux(L, n, \
    ptrdiff_t t__ = savestack(L, p);  /* save 'p' */ \
    luaC_checkGC(L),  /* stack grow uses memory */ \
    p = restorestack(L, t__))  /* 'pos' part: restore 'p' */
Definition at line 40 of file lua-5.4.3/src/ldo.h.
#define checkstackGCp(L,n,p)  \
  luaD_checkstackaux(L, n, \
    ptrdiff_t t__ = savestack(L, p);  /* save 'p' */ \
    luaC_checkGC(L),  /* stack grow uses memory */ \
    p = restorestack(L, t__))  /* 'pos' part: restore 'p' */
Referenced by luaD_precall(), luaT_getvarargs(), and luaV_execute().
luaD_checkstack
#define luaD_checkstack (L, n) luaD_checkstackaux(L,n,(void)0,(void)0)
Definition at line 31 of file lua-5.4.3/src/ldo.h.
luaD_checkstackaux
#define luaD_checkstackaux (L, n, pre, pos)
Value:
    if (l_unlikely(L->stack_last - L->top <= (n))) \
      { pre; luaD_growstack(L, n, 1); pos; } \
        else { condmovestack(L,pre,pos); }
Definition at line 25 of file lua-5.4.3/src/ldo.h.
#define luaD_checkstackaux(L,n,pre,pos)  \
    if (l_unlikely(L->stack_last - L->top <= (n))) \
      { pre; luaD_growstack(L, n, 1); pos; } \
        else { condmovestack(L,pre,pos); }
restorestack
#define restorestack (L, n) ((StkId)((char *)L->stack + (n)))
Definition at line 36 of file lua-5.4.3/src/ldo.h.
savestack
#define savestack (L, p) ((char *)(p) - (char *)L->stack)
Definition at line 35 of file lua-5.4.3/src/ldo.h.
Typedef Documentation
Pfunc
typedef void(* Pfunc) (lua_State *L, void *ud)
Definition at line 53 of file lua-5.4.3/src/ldo.h.
Function Documentation
luaD_call()
LUAI_FUNC void luaD_call (lua_State * L, StkId func, int nResults)
Definition at line 370 of file lua-5.1.5/src/ldo.c.
{
  if (++L->nCcalls >= LUAI_MAXCCALLS) {
    if (L->nCcalls == LUAI_MAXCCALLS)
      luaG_runerror(L, "C stack overflow");
    else if (L->nCcalls >= (LUAI_MAXCCALLS + (LUAI_MAXCCALLS>>3)))
      luaD_throw(L, LUA_ERRERR);  /* error while handing stack error */
  }
  if (luaD_precall(L, func, nResults) == PCRLUA)  /* is a Lua function? */
    luaV_execute(L, 1);  /* call it */
  L->nCcalls--;
  luaC_checkGC(L);
}
References ccall(), LUA_ERRERR, luaC_checkGC, luaD_precall(), luaD_throw(), luaG_runerror(), LUAI_MAXCCALLS, luaV_execute(), lua_State::nCcalls, PCRLUA, and stackerror().
Referenced by callclosemethod(), callTM(), callTM(), callTMres(), dothecall(), f_call(), f_call(), f_Ccall(), GCTM(), lua_call(), lua_callk(), lua_callk(), lua_pcallk(), lua_pcallk(), luaD_callnoyield(), luaG_errormsg(), luaT_callTM(), luaT_callTM(), luaT_callTMres(), luaV_execute(), luaV_execute(), and luaV_execute().
luaD_callnoyield()
LUAI_FUNC void luaD_callnoyield (lua_State * L, StkId func, int nResults)
Definition at line 507 of file lua-5.3.6/src/ldo.c.
{
  L->nny++;
  luaD_call(L, func, nResults);
  L->nny--;
}
References ccall(), luaD_call(), lua_State::nny, and nyci.
Referenced by callclosemethod(), dothecall(), dothecall(), f_call(), f_call(), lua_callk(), luaG_errormsg(), luaT_callTM(), luaT_callTM(), and luaT_callTMres().
luaD_closeprotected()
LUAI_FUNC int luaD_closeprotected (lua_State * L, ptrdiff_t level, int status)
Definition at line 863 of file lua-5.4.3/src/ldo.c.
{
  CallInfo *old_ci = L->ci;
  lu_byte old_allowhooks = L->allowhook;
  for (;;) {  /* keep closing upvalues until no more errors */
    struct CloseP pcl;
    pcl.level = restorestack(L, level); pcl.status = status;
    status = luaD_rawrunprotected(L, &closepaux, &pcl);
    if (l_likely(status == LUA_OK))  /* no more errors? */
      return pcl.status;
    else {  /* an error occurred; restore saved state and repeat */
      L->ci = old_ci;
      L->allowhook = old_allowhooks;
    }
  }
}
References lua_State::allowhook, lua_State::ci, closepaux(), CloseP::level, LUA_OK, luaD_rawrunprotected(), restorestack, and CloseP::status.
Referenced by close_state(), luaD_pcall(), and luaE_resetthread().
luaD_growstack()
LUAI_FUNC int luaD_growstack (lua_State * L, int n, int raiseerror)
Definition at line 219 of file lua-5.4.3/src/ldo.c.
{
  int size = stacksize(L);
  if (l_unlikely(size > LUAI_MAXSTACK)) {
    /* if stack is larger than maximum, thread is already using the
       extra space reserved for errors, that is, thread is handling
       a stack error; cannot grow further than that. */
    lua_assert(stacksize(L) == ERRORSTACKSIZE);
    if (raiseerror)
      luaD_throw(L, LUA_ERRERR);  /* error inside message handler */
    return 0;  /* if not 'raiseerror', just signal it */
  }
  else {
    int newsize = 2 * size;  /* tentative new size */
    int needed = cast_int(L->top - L->stack) + n;
    if (newsize > LUAI_MAXSTACK)  /* cannot cross the limit */
      newsize = LUAI_MAXSTACK;
    if (newsize < needed)  /* but must respect what was asked for */
      newsize = needed;
    if (l_likely(newsize <= LUAI_MAXSTACK))
      return luaD_reallocstack(L, newsize, raiseerror);
    else {  /* stack overflow */
      /* add extra size to be able to handle the error message */
      luaD_reallocstack(L, ERRORSTACKSIZE, raiseerror);
      if (raiseerror)
        luaG_runerror(L, "stack overflow");
      return 0;
    }
  }
}
References cast_int, ERRORSTACKSIZE, lua_assert, LUA_ERRERR, luaD_reallocstack(), luaD_throw(), luaG_runerror(), LUAI_MAXSTACK, lua_State::stack, stacksize, and lua_State::top.
luaD_hook()
LUAI_FUNC void luaD_hook (lua_State * L, int event, int line, int fTransfer, int nTransfer)
Definition at line 306 of file lua-5.4.3/src/ldo.c.
{
  lua_Hook hook = L->hook;
  if (hook && L->allowhook) {  /* make sure there is a hook */
    int mask = CIST_HOOKED;
    CallInfo *ci = L->ci;
    ptrdiff_t top = savestack(L, L->top);  /* preserve original 'top' */
    ptrdiff_t ci_top = savestack(L, ci->top);  /* idem for 'ci->top' */
    lua_Debug ar;
    ar.event = event;
    ar.currentline = line;
    ar.i_ci = ci;
    if (ntransfer != 0) {
      mask |= CIST_TRAN;  /* 'ci' has transfer information */
      ci->u2.transferinfo.ftransfer = ftransfer;
      ci->u2.transferinfo.ntransfer = ntransfer;
    }
    if (isLua(ci) && L->top < ci->top)
      L->top = ci->top;  /* protect entire activation register */
    luaD_checkstack(L, LUA_MINSTACK);  /* ensure minimum stack size */
    if (ci->top < L->top + LUA_MINSTACK)
      ci->top = L->top + LUA_MINSTACK;
    L->allowhook = 0;  /* cannot call hooks inside a hook */
    ci->callstatus |= mask;
    lua_unlock(L);
    (*hook)(L, &ar);
    lua_lock(L);
    lua_assert(!L->allowhook);
    L->allowhook = 1;
    ci->top = restorestack(L, ci_top);
    L->top = restorestack(L, top);
    ci->callstatus &= ~mask;
  }
}
References lua_State::allowhook, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, CIST_TRAN, lua_Debug::currentline, lua_Debug::event, CallInfo::ftransfer, lua_State::hook, lua_Debug::i_ci, isLua, lua_assert, lua_lock, LUA_MINSTACK, lua_unlock, luaD_checkstack, mask, CallInfo::ntransfer, restorestack, savestack, CallInfo::top, lua_State::top, CallInfo::transferinfo, and CallInfo::u2.
Referenced by luaD_hookcall(), luaD_precall(), and rethook().
luaD_hookcall()
LUAI_FUNC void luaD_hookcall (lua_State * L, CallInfo * ci)
Definition at line 347 of file lua-5.4.3/src/ldo.c.
{
  L->oldpc = 0;  /* set 'oldpc' for new function */
  if (L->hookmask & LUA_MASKCALL) {  /* is call hook on? */
    int event = (ci->callstatus & CIST_TAIL) ? LUA_HOOKTAILCALL
                                             : LUA_HOOKCALL;
    Proto *p = ci_func(ci)->p;
    ci->u.l.savedpc++;  /* hooks assume 'pc' is already incremented */
    luaD_hook(L, event, -1, 1, p->numparams);
    ci->u.l.savedpc--;  /* correct 'pc' */
  }
}
References CallInfo::callstatus, ci_func, CIST_TAIL, lua_State::hookmask, CallInfo::l, LUA_HOOKCALL, LUA_HOOKTAILCALL, LUA_MASKCALL, luaD_hook(), Proto::numparams, lua_State::oldpc, Proto::p, CallInfo::savedpc, and CallInfo::u.
Referenced by luaV_execute().
luaD_inctop()
LUAI_FUNC void luaD_inctop (lua_State * L)
Definition at line 240 of file lua-5.3.6/src/ldo.c.
{
  luaD_checkstack(L, 1);
  L->top++;
}
References luaD_checkstack, and lua_State::top.
Referenced by LoadString(), loadStringN(), luaO_pushvfstring(), luaU_undump(), luaY_parser(), and pushstr().
luaD_pcall()
LUAI_FUNC int luaD_pcall (lua_State * L, Pfunc func, void * u, ptrdiff_t oldtop, ptrdiff_t ef)
Definition at line 456 of file lua-5.1.5/src/ldo.c.
{
  int status;
  unsigned short oldnCcalls = L->nCcalls;
  ptrdiff_t old_ci = saveci(L, L->ci);
  lu_byte old_allowhooks = L->allowhook;
  ptrdiff_t old_errfunc = L->errfunc;
  L->errfunc = ef;
  status = luaD_rawrunprotected(L, func, u);
  if (status != 0) {  /* an error occurred? */
    StkId oldtop = restorestack(L, old_top);
    luaF_close(L, oldtop);  /* close eventual pending closures */
    luaD_seterrorobj(L, status, oldtop);
    L->nCcalls = oldnCcalls;
    L->ci = restoreci(L, old_ci);
    L->base = L->ci->base;
    L->savedpc = L->ci->savedpc;
    L->allowhook = old_allowhooks;
    restore_stack_limit(L);
  }
  L->errfunc = old_errfunc;
  return status;
}
References lua_State::allowhook, CallInfo::base, lua_State::base, lua_State::ci, lua_State::errfunc, LUA_OK, luaD_closeprotected(), luaD_rawrunprotected(), luaD_seterrorobj(), luaD_shrinkstack(), luaF_close(), lua_State::nCcalls, lua_State::nny, restore_stack_limit(), restoreci, restorestack, saveci, CallInfo::savedpc, lua_State::savedpc, seterrorobj(), seterrorobj(), lua_longjmp::status, and CloseP::status.
Referenced by GCTM(), GCTM(), GCTM(), lua_cpcall(), lua_pcall(), lua_pcallk(), lua_pcallk(), luaD_protectedparser(), and luaD_protectedparser().
luaD_poscall()
LUAI_FUNC void luaD_poscall (lua_State * L, CallInfo * ci, int nres)
Definition at line 459 of file lua-5.4.3/src/ldo.c.
{
  int wanted = ci->nresults;
  if (l_unlikely(L->hookmask && !hastocloseCfunc(wanted)))
    rethook(L, ci, nres);
  /* move results to proper place */
  moveresults(L, ci->func, nres, wanted);
  /* function cannot be in any of these cases when returning */
  lua_assert(!(ci->callstatus &
        (CIST_HOOKED | CIST_YPCALL | CIST_FIN | CIST_TRAN | CIST_CLSRET)));
  L->ci = ci->previous;  /* back to caller (after closing variables) */
}
References CallInfo::callstatus, lua_State::ci, CIST_CLSRET, CIST_FIN, CIST_HOOKED, CIST_TRAN, CIST_YPCALL, CallInfo::func, hastocloseCfunc, lua_State::hookmask, lua_assert, moveresults(), CallInfo::nresults, CallInfo::previous, and rethook().
Referenced by finishCcall(), luaD_precall(), and resume().
luaD_precall()
LUAI_FUNC CallInfo * luaD_precall (lua_State * L, StkId func, int nResults)
Definition at line 265 of file lua-5.1.5/src/ldo.c.
{
  LClosure *cl;
  ptrdiff_t funcr;
  if (!ttisfunction(func)) /* `func' is not a function? */
    func = tryfuncTM(L, func);  /* check the `function' tag method */
  funcr = savestack(L, func);
  cl = &clvalue(func)->l;
  L->ci->savedpc = L->savedpc;
  if (!cl->isC) {  /* Lua function? prepare its call */
    CallInfo *ci;
    StkId st, base;
    Proto *p = cl->p;
    luaD_checkstack(L, p->maxstacksize);
    func = restorestack(L, funcr);
    if (!p->is_vararg) {  /* no varargs? */
      base = func + 1;
      if (L->top > base + p->numparams)
        L->top = base + p->numparams;
    }
    else {  /* vararg function */
      int nargs = cast_int(L->top - func) - 1;
      base = adjust_varargs(L, p, nargs);
      func = restorestack(L, funcr);  /* previous call may change the stack */
    }
    ci = inc_ci(L);  /* now `enter' new function */
    ci->func = func;
    L->base = ci->base = base;
    ci->top = L->base + p->maxstacksize;
    lua_assert(ci->top <= L->stack_last);
    L->savedpc = p->code;  /* starting point */
    ci->tailcalls = 0;
    ci->nresults = nresults;
    for (st = L->top; st < ci->top; st++)
      setnilvalue(st);
    L->top = ci->top;
    if (L->hookmask & LUA_MASKCALL) {
      L->savedpc++;  /* hooks assume 'pc' is already incremented */
      luaD_callhook(L, LUA_HOOKCALL, -1);
      L->savedpc--;  /* correct 'pc' */
    }
    return PCRLUA;
  }
  else {  /* if is a C function, call it */
    CallInfo *ci;
    int n;
    luaD_checkstack(L, LUA_MINSTACK);  /* ensure minimum stack size */
    ci = inc_ci(L);  /* now `enter' new function */
    ci->func = restorestack(L, funcr);
    L->base = ci->base = ci->func + 1;
    ci->top = L->top + LUA_MINSTACK;
    lua_assert(ci->top <= L->stack_last);
    ci->nresults = nresults;
    if (L->hookmask & LUA_MASKCALL)
      luaD_callhook(L, LUA_HOOKCALL, -1);
    lua_unlock(L);
    n = (*curr_func(L)->c.f)(L);  /* do the actual call */
    lua_lock(L);
    if (n < 0)  /* yielding? */
      return PCRYIELD;
    else {
      luaD_poscall(L, L->top - n);
      return PCRC;
    }
  }
}
References adjust_varargs(), adjust_varargs(), adjust_varargs(), api_checknelems, CallInfo::base, lua_State::base, callhook(), callhook(), CallInfo::callstatus, cast_int, checkstackGCp, checkstackp, lua_State::ci, CIST_C, CIST_LUA, clCvalue, clLvalue, clvalue, Proto::code, curr_func, CallInfo::func, fvalue, lua_State::hookmask, inc_ci, Proto::is_vararg, CallInfo::l, lua_assert, LUA_HOOKCALL, lua_lock, LUA_MASKCALL, LUA_MINSTACK, LUA_TCCL, LUA_TLCF, LUA_TLCL, lua_unlock, LUA_VCCL, LUA_VLCF, LUA_VLCL, luaC_checkGC, luaD_callhook(), luaD_checkstack, luaD_hook(), luaD_hook(), luaD_poscall(), luaD_poscall(), luaD_poscall(), luaD_precall(), luaD_tryfuncTM(), Proto::maxstacksize, next_ci, CallInfo::nresults, NULL, Proto::numparams, Proto::p, LClosure::p, PCRC, PCRLUA, PCRYIELD, restorestack, s2v, CallInfo::savedpc, lua_State::savedpc, savestack, setnilvalue, lua_State::stack_last, CallInfo::tailcalls, CallInfo::top, lua_State::top, tryfuncTM(), tryfuncTM(), tryfuncTM(), ttisfunction, ttype, ttypetag, and CallInfo::u.
Referenced by ccall(), luaD_call(), luaD_call(), luaD_precall(), luaV_execute(), luaV_execute(), luaV_execute(), resume(), resume(), and resume().
luaD_pretailcall()
LUAI_FUNC void luaD_pretailcall (lua_State * L, CallInfo * ci, StkId func, int n)
Definition at line 481 of file lua-5.4.3/src/ldo.c.
{
  Proto *p = clLvalue(s2v(func))->p;
  int fsize = p->maxstacksize;  /* frame size */
  int nfixparams = p->numparams;
  int i;
  for (i = 0; i < narg1; i++)  /* move down function and arguments */
    setobjs2s(L, ci->func + i, func + i);
  checkstackGC(L, fsize);
  func = ci->func;  /* moved-down function */
  for (; narg1 <= nfixparams; narg1++)
    setnilvalue(s2v(func + narg1));  /* complete missing arguments */
  ci->top = func + 1 + fsize;  /* top for new function */
  lua_assert(ci->top <= L->stack_last);
  ci->u.l.savedpc = p->code;  /* starting point */
  ci->callstatus |= CIST_TAIL;
  L->top = func + narg1;  /* set top */
}
References CallInfo::callstatus, checkstackGC, CIST_TAIL, clLvalue, Proto::code, CallInfo::func, CallInfo::l, lua_assert, Proto::maxstacksize, Proto::numparams, Proto::p, s2v, CallInfo::savedpc, setnilvalue, setobjs2s, lua_State::stack_last, CallInfo::top, lua_State::top, and CallInfo::u.
Referenced by luaV_execute().
luaD_protectedparser()
LUAI_FUNC int luaD_protectedparser (lua_State * L, ZIO * z, const char * name, const char * mode)
Definition at line 662 of file lua-5.2.4/src/ldo.c.
{
  struct SParser p;
  int status;
  L->nny++;  /* cannot yield during parsing */
  p.z = z; p.name = name; p.mode = mode;
  p.dyd.actvar.arr = NULL; p.dyd.actvar.size = 0;
  p.dyd.gt.arr = NULL; p.dyd.gt.size = 0;
  p.dyd.label.arr = NULL; p.dyd.label.size = 0;
  luaZ_initbuffer(L, &p.buff);
  status = luaD_pcall(L, f_parser, &p, savestack(L, L->top), L->errfunc);
  luaZ_freebuffer(L, &p.buff);
  luaM_freearray(L, p.dyd.actvar.arr, p.dyd.actvar.size);
  luaM_freearray(L, p.dyd.gt.arr, p.dyd.gt.size);
  luaM_freearray(L, p.dyd.label.arr, p.dyd.label.size);
  L->nny--;
  return status;
}
References Dyndata::actvar, Labellist::arr, Dyndata::arr, SParser::buff, decnny, SParser::dyd, lua_State::errfunc, f_parser(), f_parser(), f_parser(), Dyndata::gt, incnny, Dyndata::label, luaD_pcall(), luaM_freearray, luaZ_freebuffer, luaZ_initbuffer, SParser::mode, name, SParser::name, lua_State::nny, NULL, savestack, Labellist::size, Dyndata::size, lua_State::top, and SParser::z.
luaD_rawrunprotected()
LUAI_FUNC int luaD_rawrunprotected (lua_State * L, Pfunc f, void * ud)
Definition at line 111 of file lua-5.1.5/src/ldo.c.
{
  struct lua_longjmp lj;
  lj.status = 0;
  lj.previous = L->errorJmp;  /* chain new error handler */
  L->errorJmp = &lj;
  LUAI_TRY(L, &lj,
    (*f)(L, ud);
  );
  L->errorJmp = lj.previous;  /* restore old error handler */
  return lj.status;
}
References lua_State::errorJmp, LUA_OK, LUAI_TRY, lua_State::nCcalls, lua_longjmp::previous, and lua_longjmp::status.
Referenced by lua_checkstack(), lua_checkstack(), lua_close(), lua_newstate(), lua_resume(), lua_resume(), lua_resume(), luaD_closeprotected(), luaD_pcall(), luaH_resize(), and precover().
luaD_reallocstack()
LUAI_FUNC int luaD_reallocstack (lua_State * L, int newsize, int raiseerror)
Definition at line 191 of file lua-5.4.3/src/ldo.c.
{
  int oldsize = stacksize(L);
  int i;
  StkId newstack = luaM_reallocvector(L, NULL, 0,
                                      newsize + EXTRA_STACK, StackValue);
  lua_assert(newsize <= LUAI_MAXSTACK || newsize == ERRORSTACKSIZE);
  if (l_unlikely(newstack == NULL)) {  /* reallocation failed? */
    if (raiseerror)
      luaM_error(L);
    else return 0;  /* do not raise an error */
  }
  /* number of elements to be copied to the new stack */
  i = ((oldsize <= newsize) ? oldsize : newsize) + EXTRA_STACK;
  memcpy(newstack, L->stack, i * sizeof(StackValue));
  for (; i < newsize + EXTRA_STACK; i++)
    setnilvalue(s2v(newstack + i)); /* erase new segment */
  correctstack(L, L->stack, newstack);
  luaM_freearray(L, L->stack, oldsize + EXTRA_STACK);
  L->stack = newstack;
  L->stack_last = L->stack + newsize;
  return 1;
}
References correctstack(), ERRORSTACKSIZE, EXTRA_STACK, lua_assert, LUAI_MAXSTACK, luaM_error, luaM_freearray, luaM_reallocvector, NULL, s2v, setnilvalue, lua_State::stack, lua_State::stack_last, and stacksize.
Referenced by luaD_growstack(), and luaD_shrinkstack().
luaD_seterrorobj()
LUAI_FUNC void luaD_seterrorobj (lua_State * L, int errcode, StkId oldtop)
Definition at line 51 of file lua-5.1.5/src/ldo.c.
{
  switch (errcode) {
    case LUA_ERRMEM: {
      setsvalue2s(L, oldtop, luaS_newliteral(L, MEMERRMSG));
      break;
    }
    case LUA_ERRERR: {
      setsvalue2s(L, oldtop, luaS_newliteral(L, "error in error handling"));
      break;
    }
    case LUA_ERRSYNTAX:
    case LUA_ERRRUN: {
      setobjs2s(L, oldtop, L->top - 1);  /* error message on current top */
      break;
    }
  }
  L->top = oldtop + 1;
}
References errorstatus, G, lua_assert, LUA_ERRERR, LUA_ERRMEM, LUA_ERRRUN, LUA_ERRSYNTAX, LUA_OK, luaS_newliteral, MEMERRMSG, s2v, setnilvalue, setobjs2s, setsvalue2s, and lua_State::top.
Referenced by finishpcallk(), lua_resume(), lua_resume(), luaD_pcall(), luaE_resetthread(), prepcallclosemth(), and resetstack().
luaD_shrinkstack()
LUAI_FUNC void luaD_shrinkstack (lua_State * L)
Definition at line 205 of file lua-5.2.4/src/ldo.c.
{
  int inuse = stackinuse(L);
  int goodsize = inuse + (inuse / 8) + 2*EXTRA_STACK;
  if (goodsize > LUAI_MAXSTACK) goodsize = LUAI_MAXSTACK;
  if (inuse > LUAI_MAXSTACK ||  /* handling stack overflow? */
      goodsize >= L->stacksize)  /* would grow instead of shrink? */
    condmovestack(L);  /* don't change stack (change only for debugging) */
  else
    luaD_reallocstack(L, goodsize);  /* shrink it */
}
References condmovestack, EXTRA_STACK, luaD_reallocstack(), luaD_reallocstack(), luaE_freeCI(), luaE_shrinkCI(), LUAI_MAXSTACK, stackinuse(), stackinuse(), stackinuse(), lua_State::stacksize, and stacksize.
Referenced by finishpcallk(), luaD_pcall(), recover(), recover(), sweepthread(), traversethread(), and traversethread().
luaD_throw()
LUAI_FUNC l_noret luaD_throw (lua_State * L, int errcode)
Definition at line 94 of file lua-5.1.5/src/ldo.c.
{
  if (L->errorJmp) {
    L->errorJmp->status = errcode;
    LUAI_THROW(L, L->errorJmp);
  }
  else {
    L->status = cast_byte(errcode);
    if (G(L)->panic) {
      resetstack(L, errcode);
      lua_unlock(L);
      G(L)->panic(L);
    }
    exit(EXIT_FAILURE);
  }
}
References cast_byte, lua_State::ci, lua_State::errorJmp, G, lua_unlock, luaD_throw(), luaE_resetthread(), LUAI_THROW, global_State::mainthread, panic(), global_State::panic, resetstack(), seterrorobj(), setobjs2s, lua_longjmp::status, lua_State::status, CallInfo::top, and lua_State::top.
Referenced by checkmode(), checkmode(), checkmode(), error(), error(), error(), error(), GCTM(), GCTM(), growCI(), lexerror(), lexerror(), lexerror(), lua_yieldk(), lua_yieldk(), luaD_call(), luaD_call(), luaD_growstack(), luaD_growstack(), luaD_throw(), luaE_checkcstack(), luaG_errormsg(), luaG_traceexec(), luaG_traceexec(), luaH_resize(), luaM_realloc_(), luaX_lexerror(), resume_error(), stackerror(), and traceexec().
luaD_tryfuncTM()
LUAI_FUNC void luaD_tryfuncTM (lua_State * L, StkId func)
Definition at line 390 of file lua-5.4.3/src/ldo.c.
{
  const TValue *tm = luaT_gettmbyobj(L, s2v(func), TM_CALL);
  StkId p;
  if (l_unlikely(ttisnil(tm)))
    luaG_callerror(L, s2v(func));  /* nothing to call */
  for (p = L->top; p > func; p--)  /* open space for metamethod */
    setobjs2s(L, p, p-1);
  L->top++;  /* stack space pre-allocated by the caller */
  setobj2s(L, func, tm);  /* metamethod is the new function to be called */
}
References luaG_callerror(), luaT_gettmbyobj(), s2v, setobj2s, setobjs2s, TM_CALL, lua_State::top, and ttisnil.
Referenced by luaD_precall(), and luaV_execute().