Github User Fetcher: ldebug.c File Reference
ldebug.c File Reference
#include "lprefix.h"
#include <stdarg.h>
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "lcode.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lvm.h"
Macros
#define ldebug_c
#define LUA_CORE
#define noLuaClosure(f) ((f) == NULL || (f)->c.tt == LUA_VCCL)
Functions
static const char * funcnamefromcode (lua_State *L, CallInfo *ci, const char **name)
static int currentpc (CallInfo *ci)
static int getbaseline (const Proto *f, int pc, int *basepc)
int luaG_getfuncline (const Proto *f, int pc)
static int getcurrentline (CallInfo *ci)
static void settraps (CallInfo *ci)
LUA_API void lua_sethook (lua_State *L, lua_Hook func, int mask, int count)
LUA_API lua_Hook lua_gethook (lua_State *L)
LUA_API int lua_gethookmask (lua_State *L)
LUA_API int lua_gethookcount (lua_State *L)
LUA_API int lua_getstack (lua_State *L, int level, lua_Debug *ar)
static const char * upvalname (const Proto *p, int uv)
static const char * findvararg (CallInfo *ci, int n, StkId *pos)
const char * luaG_findlocal (lua_State *L, CallInfo *ci, int n, StkId *pos)
LUA_API const char * lua_getlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char * lua_setlocal (lua_State *L, const lua_Debug *ar, int n)
static void funcinfo (lua_Debug *ar, Closure *cl)
static int nextline (const Proto *p, int currentline, int pc)
static void collectvalidlines (lua_State *L, Closure *f)
static const char * getfuncname (lua_State *L, CallInfo *ci, const char **name)
static int auxgetinfo (lua_State *L, const char *what, lua_Debug *ar, Closure *f, CallInfo *ci)
LUA_API int lua_getinfo (lua_State *L, const char *what, lua_Debug *ar)
static const char * getobjname (const Proto *p, int lastpc, int reg, const char **name)
static void kname (const Proto *p, int c, const char **name)
static void rname (const Proto *p, int pc, int c, const char **name)
static void rkname (const Proto *p, int pc, Instruction i, const char **name)
static int filterpc (int pc, int jmptarget)
static int findsetreg (const Proto *p, int lastpc, int reg)
static const char * gxf (const Proto *p, int pc, Instruction i, int isup)
static int isinstack (CallInfo *ci, const TValue *o)
static const char * getupvalname (CallInfo *ci, const TValue *o, const char **name)
static const char * varinfo (lua_State *L, const TValue *o)
l_noret luaG_typeerror (lua_State *L, const TValue *o, const char *op)
l_noret luaG_callerror (lua_State *L, const TValue *o)
l_noret luaG_forerror (lua_State *L, const TValue *o, const char *what)
l_noret luaG_concaterror (lua_State *L, const TValue *p1, const TValue *p2)
l_noret luaG_opinterror (lua_State *L, const TValue *p1, const TValue *p2, const char *msg)
l_noret luaG_tointerror (lua_State *L, const TValue *p1, const TValue *p2)
l_noret luaG_ordererror (lua_State *L, const TValue *p1, const TValue *p2)
const char * luaG_addinfo (lua_State *L, const char *msg, TString *src, int line)
l_noret luaG_errormsg (lua_State *L)
l_noret luaG_runerror (lua_State *L, const char *fmt,...)
static int changedline (const Proto *p, int oldpc, int newpc)
int luaG_traceexec (lua_State *L, const Instruction *pc)
Macro Definition Documentation
ldebug_c
#define ldebug_c
Definition at line 7 of file lua-5.4.3/src/ldebug.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/ldebug.c.
noLuaClosure
#define noLuaClosure (f) ((f) == NULL || (f)->c.tt == LUA_VCCL)
Definition at line 34 of file lua-5.4.3/src/ldebug.c.
Referenced by auxgetinfo(), collectvalidlines(), and funcinfo().
Function Documentation
auxgetinfo()
static int auxgetinfo (lua_State * L, const char * what, lua_Debug * ar, Closure * f, CallInfo * ci) static
Definition at line 326 of file lua-5.4.3/src/ldebug.c.
{
  int status = 1;
  for (; *what; what++) {
    switch (*what) {
      case 'S': {
        funcinfo(ar, f);
        break;
      }
      case 'l': {
        ar->currentline = (ci && isLua(ci)) ? getcurrentline(ci) : -1;
        break;
      }
      case 'u': {
        ar->nups = (f == NULL) ? 0 : f->c.nupvalues;
        if (noLuaClosure(f)) {
          ar->isvararg = 1;
          ar->nparams = 0;
        }
        else {
          ar->isvararg = f->l.p->is_vararg;
          ar->nparams = f->l.p->numparams;
        }
        break;
      }
      case 't': {
        ar->istailcall = (ci) ? ci->callstatus & CIST_TAIL : 0;
        break;
      }
      case 'n': {
        ar->namewhat = getfuncname(L, ci, &ar->name);
        if (ar->namewhat == NULL) {
          ar->namewhat = "";  /* not found */
          ar->name = NULL;
        }
        break;
      }
      case 'r': {
        if (ci == NULL || !(ci->callstatus & CIST_TRAN))
          ar->ftransfer = ar->ntransfer = 0;
        else {
          ar->ftransfer = ci->u2.transferinfo.ftransfer;
          ar->ntransfer = ci->u2.transferinfo.ntransfer;
        }
        break;
      }
      case 'L':
      case 'f':  /* handled by lua_getinfo */
        break;
      default: status = 0;  /* invalid option */
    }
  }
  return status;
}
References Closure::c, CallInfo::callstatus, CIST_TAIL, CIST_TRAN, lua_Debug::currentline, CallInfo::ftransfer, lua_Debug::ftransfer, funcinfo(), getcurrentline(), getfuncname(), Proto::is_vararg, isLua, lua_Debug::istailcall, lua_Debug::isvararg, Closure::l, lua_Debug::name, lua_Debug::namewhat, noLuaClosure, lua_Debug::nparams, CallInfo::ntransfer, lua_Debug::ntransfer, NULL, Proto::numparams, lua_Debug::nups, LClosure::p, CallInfo::transferinfo, and CallInfo::u2.
Referenced by lua_getinfo().
changedline()
static int changedline (const Proto * p, int oldpc, int newpc) static
Definition at line 800 of file lua-5.4.3/src/ldebug.c.
{
  if (p->lineinfo == NULL)  /* no debug information? */
    return 0;
  if (newpc - oldpc < MAXIWTHABS / 2) {  /* not too far apart? */
    int delta = 0;  /* line diference */
    int pc = oldpc;
    for (;;) {
      int lineinfo = p->lineinfo[++pc];
      if (lineinfo == ABSLINEINFO)
        break;  /* cannot compute delta; fall through */
      delta += lineinfo;
      if (pc == newpc)
        return (delta != 0);  /* delta computed successfully */
    }
  }
  /* either instructions are too far apart or there is an absolute line
     info in the way; compute line difference explicitly */
  return (luaG_getfuncline(p, oldpc) != luaG_getfuncline(p, newpc));
}
References ABSLINEINFO, Proto::lineinfo, luaG_getfuncline(), MAXIWTHABS, and NULL.
Referenced by luaG_traceexec().
collectvalidlines()
static void collectvalidlines (lua_State * L, Closure * f) static
Definition at line 290 of file lua-5.4.3/src/ldebug.c.
{
  if (noLuaClosure(f)) {
    setnilvalue(s2v(L->top));
    api_incr_top(L);
  }
  else {
    int i;
    TValue v;
    const Proto *p = f->l.p;
    int currentline = p->linedefined;
    Table *t = luaH_new(L);  /* new table to store active lines */
    sethvalue2s(L, L->top, t);  /* push it on stack */
    api_incr_top(L);
    setbtvalue(&v);  /* boolean 'true' to be the value of all indices */
    for (i = 0; i < p->sizelineinfo; i++) {  /* for all instructions */
      currentline = nextline(p, currentline, i);  /* get its line */
      luaH_setint(L, t, currentline, &v);  /* table[line] = true */
    }
  }
}
References api_incr_top, currentline(), Closure::l, Proto::linedefined, luaH_new(), luaH_setint(), nextline(), noLuaClosure, LClosure::p, s2v, setbtvalue, sethvalue2s, setnilvalue, Proto::sizelineinfo, and lua_State::top.
Referenced by lua_getinfo().
currentpc()
static int currentpc (CallInfo * ci) static
Definition at line 41 of file lua-5.4.3/src/ldebug.c.
{
  lua_assert(isLua(ci));
  return pcRel(ci->u.l.savedpc, ci_func(ci)->p);
}
References ci_func, isLua, CallInfo::l, lua_assert, pcRel, CallInfo::savedpc, and CallInfo::u.
Referenced by funcnamefromcode(), getcurrentline(), luaG_findlocal(), and varinfo().
filterpc()
static int filterpc (int pc, int jmptarget) static
Definition at line 454 of file lua-5.4.3/src/ldebug.c.
{
  if (pc < jmptarget)  /* is code conditional (inside a jump)? */
    return -1;  /* cannot know who sets that register */
  else return pc;  /* current position sets that register */
}
Referenced by findsetreg().
findsetreg()
static int findsetreg (const Proto * p, int lastpc, int reg) static
Definition at line 464 of file lua-5.4.3/src/ldebug.c.
{
  int pc;
  int setreg = -1;  /* keep last instruction that changed 'reg' */
  int jmptarget = 0;  /* any code before this address is conditional */
  if (testMMMode(GET_OPCODE(p->code[lastpc])))
    lastpc--;  /* previous instruction was not actually executed */
  for (pc = 0; pc < lastpc; pc++) {
    Instruction i = p->code[pc];
    OpCode op = GET_OPCODE(i);
    int a = GETARG_A(i);
    int change;  /* true if current instruction changed 'reg' */
    switch (op) {
      case OP_LOADNIL: {  /* set registers from 'a' to 'a+b' */
        int b = GETARG_B(i);
        change = (a <= reg && reg <= a + b);
        break;
      }
      case OP_TFORCALL: {  /* affect all regs above its base */
        change = (reg >= a + 2);
        break;
      }
      case OP_CALL:
      case OP_TAILCALL: {  /* affect all registers above base */
        change = (reg >= a);
        break;
      }
      case OP_JMP: {  /* doesn't change registers, but changes 'jmptarget' */
        int b = GETARG_sJ(i);
        int dest = pc + 1 + b;
        /* jump does not skip 'lastpc' and is larger than current one? */
        if (dest <= lastpc && dest > jmptarget)
          jmptarget = dest;  /* update 'jmptarget' */
        change = 0;
        break;
      }
      default:  /* any instruction that sets A */
        change = (testAMode(op) && reg == a);
        break;
    }
    if (change)
      setreg = filterpc(pc, jmptarget);
  }
  return setreg;
}
References Proto::code, filterpc(), GET_OPCODE, GETARG_A, GETARG_B, GETARG_sJ, OP_CALL, OP_JMP, OP_LOADNIL, OP_TAILCALL, OP_TFORCALL, testAMode, and testMMMode.
Referenced by getobjname().
findvararg()
static const char * findvararg (CallInfo * ci, int n, StkId * pos) static
Definition at line 184 of file lua-5.4.3/src/ldebug.c.
{
  if (clLvalue(s2v(ci->func))->p->is_vararg) {
    int nextra = ci->u.l.nextraargs;
    if (n >= -nextra) {  /* 'n' is negative */
      *pos = ci->func - nextra - (n + 1);
      return "(vararg)";  /* generic name for any vararg */
    }
  }
  return NULL;  /* no such vararg */
}
References clLvalue, CallInfo::func, CallInfo::l, CallInfo::nextraargs, NULL, s2v, and CallInfo::u.
Referenced by luaG_findlocal().
funcinfo()
static void funcinfo (lua_Debug * ar, Closure * cl) static
Definition at line 256 of file lua-5.4.3/src/ldebug.c.
{
  if (noLuaClosure(cl)) {
    ar->source = "=[C]";
    ar->srclen = LL("=[C]");
    ar->linedefined = -1;
    ar->lastlinedefined = -1;
    ar->what = "C";
  }
  else {
    const Proto *p = cl->l.p;
    if (p->source) {
      ar->source = getstr(p->source);
      ar->srclen = tsslen(p->source);
    }
    else {
      ar->source = "=?";
      ar->srclen = LL("=?");
    }
    ar->linedefined = p->linedefined;
    ar->lastlinedefined = p->lastlinedefined;
    ar->what = (ar->linedefined == 0) ? "main" : "Lua";
  }
  luaO_chunkid(ar->short_src, ar->source, ar->srclen);
}
References getstr, Closure::l, Proto::lastlinedefined, lua_Debug::lastlinedefined, Proto::linedefined, lua_Debug::linedefined, LL, luaO_chunkid(), noLuaClosure, LClosure::p, lua_Debug::short_src, Proto::source, lua_Debug::source, lua_Debug::srclen, tsslen, and lua_Debug::what.
Referenced by auxgetinfo().
funcnamefromcode()
static const char * funcnamefromcode (lua_State * L, CallInfo * ci, const char ** name) static
Definition at line 593 of file lua-5.4.3/src/ldebug.c.
{
  TMS tm = (TMS)0;  /* (initial value avoids warnings) */
  const Proto *p = ci_func(ci)->p;  /* calling function */
  int pc = currentpc(ci);  /* calling instruction index */
  Instruction i = p->code[pc];  /* calling instruction */
  if (ci->callstatus & CIST_HOOKED) {  /* was it called inside a hook? */
    *name = "?";
    return "hook";
  }
  switch (GET_OPCODE(i)) {
    case OP_CALL:
    case OP_TAILCALL:
      return getobjname(p, pc, GETARG_A(i), name);  /* get function name */
    case OP_TFORCALL: {  /* for iterator */
      *name = "for iterator";
       return "for iterator";
    }
    /* other instructions can do calls through metamethods */
    case OP_SELF: case OP_GETTABUP: case OP_GETTABLE:
    case OP_GETI: case OP_GETFIELD:
      tm = TM_INDEX;
      break;
    case OP_SETTABUP: case OP_SETTABLE: case OP_SETI: case OP_SETFIELD:
      tm = TM_NEWINDEX;
      break;
    case OP_MMBIN: case OP_MMBINI: case OP_MMBINK: {
      tm = cast(TMS, GETARG_C(i));
      break;
    }
    case OP_UNM: tm = TM_UNM; break;
    case OP_BNOT: tm = TM_BNOT; break;
    case OP_LEN: tm = TM_LEN; break;
    case OP_CONCAT: tm = TM_CONCAT; break;
    case OP_EQ: tm = TM_EQ; break;
    /* no cases for OP_EQI and OP_EQK, as they don't call metamethods */
    case OP_LT: case OP_LTI: case OP_GTI: tm = TM_LT; break;
    case OP_LE: case OP_LEI: case OP_GEI: tm = TM_LE; break;
    case OP_CLOSE: case OP_RETURN: tm = TM_CLOSE; break;
    default:
      return NULL;  /* cannot find a reasonable name */
  }
  *name = getstr(G(L)->tmname[tm]) + 2;
  return "metamethod";
}
References CallInfo::callstatus, cast, ci_func, CIST_HOOKED, Proto::code, currentpc(), G, GET_OPCODE, GETARG_A, GETARG_C, getobjname(), getstr, name, NULL, OP_BNOT, OP_CALL, OP_CLOSE, OP_CONCAT, OP_EQ, OP_GEI, OP_GETFIELD, OP_GETI, OP_GETTABLE, OP_GETTABUP, OP_GTI, OP_LE, OP_LEI, OP_LEN, OP_LT, OP_LTI, OP_MMBIN, OP_MMBINI, OP_MMBINK, OP_RETURN, OP_SELF, OP_SETFIELD, OP_SETI, OP_SETTABLE, OP_SETTABUP, OP_TAILCALL, OP_TFORCALL, OP_UNM, Proto::p, TM_BNOT, TM_CLOSE, TM_CONCAT, TM_EQ, TM_INDEX, TM_LE, TM_LEN, TM_LT, TM_NEWINDEX, TM_UNM, and tmname.
Referenced by getfuncname(), and luaG_callerror().
getbaseline()
static int getbaseline (const Proto * f, int pc, int * basepc) static
Definition at line 60 of file lua-5.4.3/src/ldebug.c.
{
  if (f->sizeabslineinfo == 0 || pc < f->abslineinfo[0].pc) {
    *basepc = -1;  /* start from the beginning */
    return f->linedefined;
  }
  else {
    int i = cast_uint(pc) / MAXIWTHABS - 1;  /* get an estimate */
    /* estimate must be a lower bond of the correct base */
    lua_assert(i < 0 ||
              (i < f->sizeabslineinfo && f->abslineinfo[i].pc <= pc));
    while (i + 1 < f->sizeabslineinfo && pc >= f->abslineinfo[i + 1].pc)
      i++;  /* low estimate; adjust it */
    *basepc = f->abslineinfo[i].pc;
    return f->abslineinfo[i].line;
  }
}
References Proto::abslineinfo, cast_uint, AbsLineInfo::line, Proto::linedefined, lua_assert, MAXIWTHABS, AbsLineInfo::pc, and Proto::sizeabslineinfo.
Referenced by luaG_getfuncline().
getcurrentline()
static int getcurrentline (CallInfo * ci) static
Definition at line 98 of file lua-5.4.3/src/ldebug.c.
{
  return luaG_getfuncline(ci_func(ci)->p, currentpc(ci));
}
References ci_func, currentpc(), and luaG_getfuncline().
Referenced by auxgetinfo(), and luaG_runerror().
getfuncname()
static const char * getfuncname (lua_State * L, CallInfo * ci, const char ** name) static
Definition at line 312 of file lua-5.4.3/src/ldebug.c.
{
  if (ci == NULL)  /* no 'ci'? */
    return NULL;  /* no info */
  else if (ci->callstatus & CIST_FIN) {  /* is this a finalizer? */
    *name = "__gc";
    return "metamethod";  /* report it as such */
  }
  /* calling function is a known Lua function? */
  else if (!(ci->callstatus & CIST_TAIL) && isLua(ci->previous))
    return funcnamefromcode(L, ci->previous, name);
  else return NULL;  /* no way to find a name */
}
References CallInfo::callstatus, CIST_FIN, CIST_TAIL, funcnamefromcode(), isLua, name, NULL, and CallInfo::previous.
Referenced by auxgetinfo().
getobjname()
static const char * getobjname (const Proto * p, int lastpc, int reg, const char ** name) static
Definition at line 525 of file lua-5.4.3/src/ldebug.c.
{
  int pc;
  *name = luaF_getlocalname(p, reg + 1, lastpc);
  if (*name)  /* is a local? */
    return "local";
  /* else try symbolic execution */
  pc = findsetreg(p, lastpc, reg);
  if (pc != -1) {  /* could find instruction? */
    Instruction i = p->code[pc];
    OpCode op = GET_OPCODE(i);
    switch (op) {
      case OP_MOVE: {
        int b = GETARG_B(i);  /* move from 'b' to 'a' */
        if (b < GETARG_A(i))
          return getobjname(p, pc, b, name);  /* get name for 'b' */
        break;
      }
      case OP_GETTABUP: {
        int k = GETARG_C(i);  /* key index */
        kname(p, k, name);
        return gxf(p, pc, i, 1);
      }
      case OP_GETTABLE: {
        int k = GETARG_C(i);  /* key index */
        rname(p, pc, k, name);
        return gxf(p, pc, i, 0);
      }
      case OP_GETI: {
        *name = "integer index";
        return "field";
      }
      case OP_GETFIELD: {
        int k = GETARG_C(i);  /* key index */
        kname(p, k, name);
        return gxf(p, pc, i, 0);
      }
      case OP_GETUPVAL: {
        *name = upvalname(p, GETARG_B(i));
        return "upvalue";
      }
      case OP_LOADK:
      case OP_LOADKX: {
        int b = (op == OP_LOADK) ? GETARG_Bx(i)
                                 : GETARG_Ax(p->code[pc + 1]);
        if (ttisstring(&p->k[b])) {
          *name = svalue(&p->k[b]);
          return "constant";
        }
        break;
      }
      case OP_SELF: {
        rkname(p, pc, i, name);
        return "method";
      }
      default: break;  /* go through to return NULL */
    }
  }
  return NULL;  /* could not find reasonable name */
}
References Proto::code, findsetreg(), GET_OPCODE, GETARG_A, GETARG_Ax, GETARG_B, GETARG_Bx, GETARG_C, getobjname(), gxf(), Proto::k, kname(), luaF_getlocalname(), name, NULL, OP_GETFIELD, OP_GETI, OP_GETTABLE, OP_GETTABUP, OP_GETUPVAL, OP_LOADK, OP_LOADKX, OP_MOVE, OP_SELF, rkname(), rname(), svalue, ttisstring, and upvalname().
Referenced by funcnamefromcode(), getobjname(), gxf(), rname(), and varinfo().
getupvalname()
static const char * getupvalname (CallInfo * ci, const TValue * o, const char ** name) static
Definition at line 664 of file lua-5.4.3/src/ldebug.c.
{
  LClosure *c = ci_func(ci);
  int i;
  for (i = 0; i < c->nupvalues; i++) {
    if (c->upvals[i]->v == o) {
      *name = upvalname(c->p, i);
      return "upvalue";
    }
  }
  return NULL;
}
References ci_func, name, NULL, LClosure::p, upvalname(), LClosure::upvals, and UpVal::v.
Referenced by varinfo().
gxf()
static const char * gxf (const Proto * p, int pc, Instruction i, int isup) static
Definition at line 514 of file lua-5.4.3/src/ldebug.c.
{
  int t = GETARG_B(i);  /* table index */
  const char *name;  /* name of indexed variable */
  if (isup)  /* is an upvalue? */
    name = upvalname(p, t);
  else
    getobjname(p, pc, t, &name);
  return (name && strcmp(name, LUA_ENV) == 0) ? "global" : "field";
}
References GETARG_B, getobjname(), LUA_ENV, name, and upvalname().
Referenced by getobjname().
isinstack()
static int isinstack (CallInfo * ci, const TValue * o) static
Definition at line 649 of file lua-5.4.3/src/ldebug.c.
{
  StkId pos;
  for (pos = ci->func + 1; pos < ci->top; pos++) {
    if (o == s2v(pos))
      return 1;
  }
  return 0;  /* not found */
}
References CallInfo::func, s2v, and CallInfo::top.
Referenced by varinfo().
kname()
static void kname (const Proto * p, int c, const char ** name) static
Definition at line 426 of file lua-5.4.3/src/ldebug.c.
{
  TValue *kvalue = &p->k[c];
  *name = (ttisstring(kvalue)) ? svalue(kvalue) : "?";
}
References Proto::k, name, svalue, and ttisstring.
Referenced by getobjname(), and rkname().
lua_gethook()
LUA_API lua_Hook lua_gethook (lua_State * L)
Definition at line 145 of file lua-5.4.3/src/ldebug.c.
{
  return L->hook;
}
References lua_State::hook.
lua_gethookcount()
LUA_API int lua_gethookcount (lua_State * L)
Definition at line 155 of file lua-5.4.3/src/ldebug.c.
{
  return L->basehookcount;
}
References lua_State::basehookcount.
lua_gethookmask()
LUA_API int lua_gethookmask (lua_State * L)
Definition at line 150 of file lua-5.4.3/src/ldebug.c.
{
  return L->hookmask;
}
References lua_State::hookmask.
lua_getinfo()
LUA_API int lua_getinfo (lua_State * L, const char * what, lua_Debug * ar)
Definition at line 382 of file lua-5.4.3/src/ldebug.c.
{
  int status;
  Closure *cl;
  CallInfo *ci;
  TValue *func;
  lua_lock(L);
  if (*what == '>') {
    ci = NULL;
    func = s2v(L->top - 1);
    api_check(L, ttisfunction(func), "function expected");
    what++;  /* skip the '>' */
    L->top--;  /* pop function */
  }
  else {
    ci = ar->i_ci;
    func = s2v(ci->func);
    lua_assert(ttisfunction(func));
  }
  cl = ttisclosure(func) ? clvalue(func) : NULL;
  status = auxgetinfo(L, what, ar, cl, ci);
  if (strchr(what, 'f')) {
    setobj2s(L, L->top, func);
    api_incr_top(L);
  }
  if (strchr(what, 'L'))
    collectvalidlines(L, cl);
  lua_unlock(L);
  return status;
}
References api_check, api_incr_top, auxgetinfo(), clvalue, collectvalidlines(), CallInfo::func, lua_Debug::i_ci, lua_assert, lua_lock, lua_unlock, NULL, s2v, setobj2s, lua_State::top, ttisclosure, and ttisfunction.
lua_getlocal()
LUA_API const char * lua_getlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 220 of file lua-5.4.3/src/ldebug.c.
{
  const char *name;
  lua_lock(L);
  if (ar == NULL) {  /* information about non-active function? */
    if (!isLfunction(s2v(L->top - 1)))  /* not a Lua function? */
      name = NULL;
    else  /* consider live variables at function start (parameters) */
      name = luaF_getlocalname(clLvalue(s2v(L->top - 1))->p, n, 0);
  }
  else {  /* active function; get information through 'ar' */
    StkId pos = NULL;  /* to avoid warnings */
    name = luaG_findlocal(L, ar->i_ci, n, &pos);
    if (name) {
      setobjs2s(L, L->top, pos);
      api_incr_top(L);
    }
  }
  lua_unlock(L);
  return name;
}
References api_incr_top, clLvalue, lua_Debug::i_ci, isLfunction, lua_lock, lua_unlock, luaF_getlocalname(), luaG_findlocal(), name, NULL, s2v, setobjs2s, and lua_State::top.
lua_getstack()
LUA_API int lua_getstack (lua_State * L, int level, lua_Debug * ar)
Definition at line 160 of file lua-5.4.3/src/ldebug.c.
{
  int status;
  CallInfo *ci;
  if (level < 0) return 0;  /* invalid (negative) level */
  lua_lock(L);
  for (ci = L->ci; level > 0 && ci != &L->base_ci; ci = ci->previous)
    level--;
  if (level == 0 && ci != &L->base_ci) {  /* level found? */
    status = 1;
    ar->i_ci = ci;
  }
  else status = 0;  /* no such level */
  lua_unlock(L);
  return status;
}
References lua_State::base_ci, lua_State::ci, lua_Debug::i_ci, lua_lock, lua_unlock, and CallInfo::previous.
lua_sethook()
LUA_API void lua_sethook (lua_State * L, lua_Hook func, int mask, int count)
Definition at line 131 of file lua-5.4.3/src/ldebug.c.
{
  if (func == NULL || mask == 0) {  /* turn off hooks? */
    mask = 0;
    func = NULL;
  }
  L->hook = func;
  L->basehookcount = count;
  resethookcount(L);
  L->hookmask = cast_byte(mask);
  if (mask)
    settraps(L->ci);  /* to trace inside 'luaV_execute' */
}
References lua_State::basehookcount, cast_byte, lua_State::ci, lua_State::hook, lua_State::hookmask, mask, NULL, resethookcount, and settraps().
lua_setlocal()
LUA_API const char * lua_setlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 242 of file lua-5.4.3/src/ldebug.c.
{
  StkId pos = NULL;  /* to avoid warnings */
  const char *name;
  lua_lock(L);
  name = luaG_findlocal(L, ar->i_ci, n, &pos);
  if (name) {
    setobjs2s(L, pos, L->top - 1);
    L->top--;  /* pop value */
  }
  lua_unlock(L);
  return name;
}
References lua_Debug::i_ci, lua_lock, lua_unlock, luaG_findlocal(), name, NULL, setobjs2s, and lua_State::top.
luaG_addinfo()
const char * luaG_addinfo (lua_State * L, const char * msg, TString * src, int line)
Definition at line 753 of file lua-5.4.3/src/ldebug.c.
{
  char buff[LUA_IDSIZE];
  if (src)
    luaO_chunkid(buff, getstr(src), tsslen(src));
  else {  /* no source available; use "?" instead */
    buff[0] = '?'; buff[1] = '\0';
  }
  return luaO_pushfstring(L, "%s:%d: %s", buff, line, msg);
}
References getstr, LUA_IDSIZE, luaO_chunkid(), luaO_pushfstring(), and tsslen.
Referenced by luaG_runerror().
luaG_callerror()
l_noret luaG_callerror (lua_State * L, const TValue * o)
Definition at line 698 of file lua-5.4.3/src/ldebug.c.
{
  CallInfo *ci = L->ci;
  const char *name = NULL;  /* to avoid warnings */
  const char *what = (isLua(ci)) ? funcnamefromcode(L, ci, &name) : NULL;
  if (what != NULL) {
    const char *t = luaT_objtypename(L, o);
    luaG_runerror(L, "%s '%s' is not callable (a %s value)", what, name, t);
  }
  else
    luaG_typeerror(L, o, "call");
}
References lua_State::ci, funcnamefromcode(), isLua, luaG_runerror(), luaG_typeerror(), luaT_objtypename(), name, and NULL.
Referenced by luaD_tryfuncTM().
luaG_concaterror()
l_noret luaG_concaterror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 717 of file lua-5.4.3/src/ldebug.c.
{
  if (ttisstring(p1) || cvt2str(p1)) p1 = p2;
  luaG_typeerror(L, p1, "concatenate");
}
References cvt2str, luaG_typeerror(), and ttisstring.
luaG_errormsg()
l_noret luaG_errormsg (lua_State * L)
Definition at line 765 of file lua-5.4.3/src/ldebug.c.
{
  if (L->errfunc != 0) {  /* is there an error handling function? */
    StkId errfunc = restorestack(L, L->errfunc);
    lua_assert(ttisfunction(s2v(errfunc)));
    setobjs2s(L, L->top, L->top - 1);  /* move argument */
    setobjs2s(L, L->top - 1, errfunc);  /* push function */
    L->top++;  /* assume EXTRA_STACK */
    luaD_callnoyield(L, L->top - 2, 1);  /* call it */
  }
  luaD_throw(L, LUA_ERRRUN);
}
References lua_State::errfunc, lua_assert, LUA_ERRRUN, luaD_callnoyield(), luaD_throw(), restorestack, s2v, setobjs2s, lua_State::top, and ttisfunction.
Referenced by luaG_runerror().
luaG_findlocal()
const char * luaG_findlocal (lua_State * L, CallInfo * ci, int n, StkId * pos)
Definition at line 196 of file lua-5.4.3/src/ldebug.c.
{
  StkId base = ci->func + 1;
  const char *name = NULL;
  if (isLua(ci)) {
    if (n < 0)  /* access to vararg values? */
      return findvararg(ci, n, pos);
    else
      name = luaF_getlocalname(ci_func(ci)->p, n, currentpc(ci));
  }
  if (name == NULL) {  /* no 'standard' name? */
    StkId limit = (ci == L->ci) ? L->top : ci->next->func;
    if (limit - base >= n && n > 0) {  /* is 'n' inside 'ci' stack? */
      /* generic name for any valid slot */
      name = isLua(ci) ? "(temporary)" : "(C temporary)";
    }
    else
      return NULL;  /* no name */
  }
  if (pos)
    *pos = base + (n - 1);
  return name;
}
References lua_State::ci, ci_func, currentpc(), findvararg(), CallInfo::func, isLua, luaF_getlocalname(), name, CallInfo::next, NULL, and lua_State::top.
Referenced by checkclosemth(), lua_getlocal(), and lua_setlocal().
luaG_forerror()
l_noret luaG_forerror (lua_State * L, const TValue * o, const char * what)
Definition at line 711 of file lua-5.4.3/src/ldebug.c.
{
  luaG_runerror(L, "bad 'for' %s (number expected, got %s)",
                   what, luaT_objtypename(L, o));
}
References luaG_runerror(), and luaT_objtypename().
Referenced by forlimit(), and forprep().
luaG_getfuncline()
int luaG_getfuncline (const Proto * f, int pc)
Definition at line 83 of file lua-5.4.3/src/ldebug.c.
{
  if (f->lineinfo == NULL)  /* no debug information? */
    return -1;
  else {
    int basepc;
    int baseline = getbaseline(f, pc, &basepc);
    while (basepc++ < pc) {  /* walk until given instruction */
      lua_assert(f->lineinfo[basepc] != ABSLINEINFO);
      baseline += f->lineinfo[basepc];  /* correct line */
    }
    return baseline;
  }
}
References ABSLINEINFO, getbaseline(), Proto::lineinfo, lua_assert, and NULL.
Referenced by changedline(), getcurrentline(), luaG_traceexec(), nextline(), and PrintCode().
luaG_opinterror()
l_noret luaG_opinterror (lua_State * L, const TValue * p1, const TValue * p2, const char * msg)
Definition at line 723 of file lua-5.4.3/src/ldebug.c.
{
  if (!ttisnumber(p1))  /* first operand is wrong? */
    p2 = p1;  /* now second is wrong */
  luaG_typeerror(L, p2, msg);
}
References luaG_typeerror(), and ttisnumber.
luaG_ordererror()
l_noret luaG_ordererror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 742 of file lua-5.4.3/src/ldebug.c.
{
  const char *t1 = luaT_objtypename(L, p1);
  const char *t2 = luaT_objtypename(L, p2);
  if (strcmp(t1, t2) == 0)
    luaG_runerror(L, "attempt to compare two %s values", t1);
  else
    luaG_runerror(L, "attempt to compare %s with %s", t1, t2);
}
References luaG_runerror(), and luaT_objtypename().
luaG_runerror()
l_noret luaG_runerror (lua_State * L, const char * fmt, ...)
Definition at line 778 of file lua-5.4.3/src/ldebug.c.
{
  CallInfo *ci = L->ci;
  const char *msg;
  va_list argp;
  luaC_checkGC(L);  /* error message uses memory */
  va_start(argp, fmt);
  msg = luaO_pushvfstring(L, fmt, argp);  /* format message */
  va_end(argp);
  if (isLua(ci))  /* if Lua function, add source:line information */
    luaG_addinfo(L, msg, ci_func(ci)->p->source, getcurrentline(ci));
  luaG_errormsg(L);
}
References lua_State::ci, ci_func, getcurrentline(), isLua, luaC_checkGC, luaG_addinfo(), luaG_errormsg(), and luaO_pushvfstring().
Referenced by luaG_callerror(), luaG_forerror(), luaG_ordererror(), luaG_tointerror(), and luaG_typeerror().
luaG_tointerror()
l_noret luaG_tointerror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 734 of file lua-5.4.3/src/ldebug.c.
{
  lua_Integer temp;
  if (!luaV_tointegerns(p1, &temp, LUA_FLOORN2I))
    p2 = p1;
  luaG_runerror(L, "number%s has no integer representation", varinfo(L, p2));
}
References LUA_FLOORN2I, luaG_runerror(), luaV_tointegerns(), and varinfo().
luaG_traceexec()
int luaG_traceexec (lua_State * L, const Instruction * pc)
Definition at line 833 of file lua-5.4.3/src/ldebug.c.
{
  CallInfo *ci = L->ci;
  lu_byte mask = L->hookmask;
  const Proto *p = ci_func(ci)->p;
  int counthook;
  if (!(mask & (LUA_MASKLINE | LUA_MASKCOUNT))) {  /* no hooks? */
    ci->u.l.trap = 0;  /* don't need to stop again */
    return 0;  /* turn off 'trap' */
  }
  pc++;  /* reference is always next instruction */
  ci->u.l.savedpc = pc;  /* save 'pc' */
  counthook = (--L->hookcount == 0 && (mask & LUA_MASKCOUNT));
  if (counthook)
    resethookcount(L);  /* reset count */
  else if (!(mask & LUA_MASKLINE))
    return 1;  /* no line hook and count != 0; nothing to be done now */
  if (ci->callstatus & CIST_HOOKYIELD) {  /* called hook last time? */
    ci->callstatus &= ~CIST_HOOKYIELD;  /* erase mark */
    return 1;  /* do not call hook again (VM yielded, so it did not move) */
  }
  if (!isIT(*(ci->u.l.savedpc - 1)))  /* top not being used? */
    L->top = ci->top;  /* correct top */
  if (counthook)
    luaD_hook(L, LUA_HOOKCOUNT, -1, 0, 0);  /* call count hook */
  if (mask & LUA_MASKLINE) {
    /* 'L->oldpc' may be invalid; use zero in this case */
    int oldpc = (L->oldpc < p->sizecode) ? L->oldpc : 0;
    int npci = pcRel(pc, p);
    if (npci <= oldpc ||  /* call hook when jump back (loop), */
        changedline(p, oldpc, npci)) {  /* or when enter new line */
      int newline = luaG_getfuncline(p, npci);
      luaD_hook(L, LUA_HOOKLINE, newline, 0, 0);  /* call line hook */
    }
    L->oldpc = npci;  /* 'pc' of last call to line hook */
  }
  if (L->status == LUA_YIELD) {  /* did hook yield? */
    if (counthook)
      L->hookcount = 1;  /* undo decrement to zero */
    ci->u.l.savedpc--;  /* undo increment (resume will increment it again) */
    ci->callstatus |= CIST_HOOKYIELD;  /* mark that it yielded */
    luaD_throw(L, LUA_YIELD);
  }
  return 1;  /* keep 'trap' on */
}
References CallInfo::callstatus, changedline(), lua_State::ci, ci_func, CIST_HOOKYIELD, lua_State::hookcount, lua_State::hookmask, isIT, CallInfo::l, LUA_HOOKCOUNT, LUA_HOOKLINE, LUA_MASKCOUNT, LUA_MASKLINE, LUA_YIELD, luaD_hook(), luaD_throw(), luaG_getfuncline(), mask, lua_State::oldpc, Proto::p, pcRel, resethookcount, CallInfo::savedpc, Proto::sizecode, lua_State::status, CallInfo::top, lua_State::top, CallInfo::trap, and CallInfo::u.
luaG_typeerror()
l_noret luaG_typeerror (lua_State * L, const TValue * o, const char * op)
Definition at line 692 of file lua-5.4.3/src/ldebug.c.
{
  const char *t = luaT_objtypename(L, o);
  luaG_runerror(L, "attempt to %s a %s value%s", op, t, varinfo(L, o));
}
References luaG_runerror(), luaT_objtypename(), and varinfo().
Referenced by luaG_callerror(), luaG_concaterror(), and luaG_opinterror().
nextline()
static int nextline (const Proto * p, int currentline, int pc) static
Definition at line 282 of file lua-5.4.3/src/ldebug.c.
{
  if (p->lineinfo[pc] != ABSLINEINFO)
    return currentline + p->lineinfo[pc];
  else
    return luaG_getfuncline(p, pc);
}
References ABSLINEINFO, currentline(), Proto::lineinfo, and luaG_getfuncline().
Referenced by collectvalidlines().
rkname()
static void rkname (const Proto * p, int pc, Instruction i, const char ** name) static
Definition at line 445 of file lua-5.4.3/src/ldebug.c.
{
  int c = GETARG_C(i);  /* key index */
  if (GETARG_k(i))  /* is 'c' a constant? */
    kname(p, c, name);
  else  /* 'c' is a register */
    rname(p, pc, c, name);
}
References GETARG_C, GETARG_k, kname(), name, and rname().
Referenced by getobjname().
rname()
static void rname (const Proto * p, int pc, int c, const char ** name) static
Definition at line 435 of file lua-5.4.3/src/ldebug.c.
{
  const char *what = getobjname(p, pc, c, name); /* search for 'c' */
  if (!(what && *what == 'c'))  /* did not find a constant name? */
    *name = "?";
}
References getobjname(), and name.
Referenced by getobjname(), and rkname().
settraps()
static void settraps (CallInfo * ci) static
Definition at line 114 of file lua-5.4.3/src/ldebug.c.
{
  for (; ci != NULL; ci = ci->previous)
    if (isLua(ci))
      ci->u.l.trap = 1;
}
References isLua, CallInfo::l, NULL, CallInfo::previous, CallInfo::trap, and CallInfo::u.
Referenced by lua_sethook().
upvalname()
static const char * upvalname (const Proto * p, int uv) static
Definition at line 177 of file lua-5.4.3/src/ldebug.c.
{
  TString *s = check_exp(uv < p->sizeupvalues, p->upvalues[uv].name);
  if (s == NULL) return "?";
  else return getstr(s);
}
References check_exp, getstr, NULL, s, and Proto::upvalues.
Referenced by getobjname(), getupvalname(), and gxf().
varinfo()
static const char * varinfo (lua_State * L, const TValue * o) static
Definition at line 678 of file lua-5.4.3/src/ldebug.c.
{
  const char *name = NULL;  /* to avoid warnings */
  CallInfo *ci = L->ci;
  const char *kind = NULL;
  if (isLua(ci)) {
    kind = getupvalname(ci, o, &name);  /* check whether 'o' is an upvalue */
    if (!kind && isinstack(ci, o))  /* no? try a register */
      kind = getobjname(ci_func(ci)->p, currentpc(ci),
                        cast_int(cast(StkId, o) - (ci->func + 1)), &name);
  }
  return (kind) ? luaO_pushfstring(L, " (%s '%s')", kind, name) : "";
}
References cast, cast_int, lua_State::ci, ci_func, currentpc(), CallInfo::func, getobjname(), getupvalname(), isinstack(), isLua, luaO_pushfstring(), name, and NULL.
Referenced by luaG_tointerror(), and luaG_typeerror().