Github User Fetcher: lgc.c File Reference
lgc.c File Reference
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
Macros
#define lgc_c
#define LUA_CORE
#define GCSWEEPCOST ((sizeof(TString) + 4) / 4)
#define GCSWEEPMAX (cast_int((GCSTEPSIZE / GCSWEEPCOST) / 4))
#define GCFINALIZENUM 4
#define STEPMULADJ 200
#define PAUSEADJ 100
#define maskcolors (~(bit2mask(BLACKBIT, OLDBIT) | WHITEBITS))
#define makewhite(g, x) (gch(x)->marked = cast_byte((gch(x)->marked & maskcolors) | luaC_white(g)))
#define white2gray(x) resetbits(gch(x)->marked, WHITEBITS)
#define black2gray(x) resetbit(gch(x)->marked, BLACKBIT)
#define isfinalized(x) testbit(gch(x)->marked, FINALIZEDBIT)
#define checkdeadkey(n) lua_assert(!ttisdeadkey(gkey(n)) || ttisnil(gval(n)))
#define checkconsistency(obj) lua_longassert(!iscollectable(obj) || righttt(obj))
#define markvalue(g, o)
#define markobject(g, t)
#define gnodelast(h) gnode(h, cast(size_t, sizenode(h)))
#define linktable(h, p) ((h)->gclist = *(p), *(p) = obj2gco(h))
#define sweepwholelist(L, p) sweeplist(L,p,MAX_LUMEM)
#define sweepphases (bitmask(GCSsweepstring) | bitmask(GCSsweepudata) | bitmask(GCSsweep))
Functions
static void reallymarkobject (global_State *g, GCObject *o)
static void removeentry (Node *n)
static int iscleared (global_State *g, const TValue *o)
void luaC_barrier_ (lua_State *L, GCObject *o, GCObject *v)
void luaC_barrierback_ (lua_State *L, GCObject *o)
LUAI_FUNC void luaC_barrierproto_ (lua_State *L, Proto *p, Closure *c)
void luaC_checkupvalcolor (global_State *g, UpVal *uv)
GCObject * luaC_newobj (lua_State *L, int tt, size_t sz, GCObject **list, int offset)
static void markmt (global_State *g)
static void markbeingfnz (global_State *g)
static void remarkupvals (global_State *g)
static void restartcollection (global_State *g)
static void traverseweakvalue (global_State *g, Table *h)
static int traverseephemeron (global_State *g, Table *h)
static void traversestrongtable (global_State *g, Table *h)
static lu_mem traversetable (global_State *g, Table *h)
static int traverseproto (global_State *g, Proto *f)
static lu_mem traverseCclosure (global_State *g, CClosure *cl)
static lu_mem traverseLclosure (global_State *g, LClosure *cl)
static lu_mem traversestack (global_State *g, lua_State *th)
static void propagatemark (global_State *g)
static void propagateall (global_State *g)
static void propagatelist (global_State *g, GCObject *l)
static void retraversegrays (global_State *g)
static void convergeephemerons (global_State *g)
static void clearkeys (global_State *g, GCObject *l, GCObject *f)
static void clearvalues (global_State *g, GCObject *l, GCObject *f)
static void freeobj (lua_State *L, GCObject *o)
static GCObject ** sweeplist (lua_State *L, GCObject **p, lu_mem count)
static void sweepthread (lua_State *L, lua_State *L1)
static GCObject ** sweeptolive (lua_State *L, GCObject **p, int *n)
static void checkSizes (lua_State *L)
static GCObject * udata2finalize (global_State *g)
static void dothecall (lua_State *L, void *ud)
static void GCTM (lua_State *L, int propagateerrors)
static void separatetobefnz (lua_State *L, int all)
void luaC_checkfinalizer (lua_State *L, GCObject *o, Table *mt)
static void setpause (global_State *g, l_mem estimate)
static int entersweep (lua_State *L)
void luaC_changemode (lua_State *L, int mode)
static void callallpendingfinalizers (lua_State *L, int propagateerrors)
void luaC_freeallobjects (lua_State *L)
static l_mem atomic (lua_State *L)
static lu_mem singlestep (lua_State *L)
void luaC_runtilstate (lua_State *L, int statesmask)
static void generationalcollection (lua_State *L)
static void incstep (lua_State *L)
void luaC_forcestep (lua_State *L)
void luaC_step (lua_State *L)
void luaC_fullgc (lua_State *L, int isemergency)
Macro Definition Documentation
black2gray
#define black2gray (x) resetbit(gch(x)->marked, BLACKBIT)
Definition at line 63 of file lua-5.2.4/src/lgc.c.
Referenced by luaC_barrierback_(), luaC_barrierproto_(), propagatemark(), and traversetable().
checkconsistency
#define checkconsistency (obj) lua_longassert(!iscollectable(obj) || righttt(obj))
Definition at line 71 of file lua-5.2.4/src/lgc.c.
#define checkconsistency(obj)  \
  lua_longassert(!iscollectable(obj) || righttt(obj))
checkdeadkey
#define checkdeadkey (n) lua_assert(!ttisdeadkey(gkey(n)) || ttisnil(gval(n)))
Definition at line 68 of file lua-5.2.4/src/lgc.c.
Referenced by traverseephemeron(), traversestrongtable(), and traverseweakvalue().
GCFINALIZENUM
#define GCFINALIZENUM 4
Definition at line 37 of file lua-5.2.4/src/lgc.c.
Referenced by luaC_forcestep().
GCSWEEPCOST
#define GCSWEEPCOST ((sizeof(TString) + 4) / 4)
Definition at line 31 of file lua-5.2.4/src/lgc.c.
Referenced by singlestep().
GCSWEEPMAX
#define GCSWEEPMAX (cast_int((GCSTEPSIZE / GCSWEEPCOST) / 4))
Definition at line 34 of file lua-5.2.4/src/lgc.c.
Referenced by singlestep().
gnodelast
#define gnodelast (h) gnode(h, cast(size_t, sizenode(h)))
Definition at line 94 of file lua-5.2.4/src/lgc.c.
Referenced by clearkeys(), clearvalues(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
isfinalized
#define isfinalized (x) testbit(gch(x)->marked, FINALIZEDBIT)
Definition at line 66 of file lua-5.2.4/src/lgc.c.
Referenced by luaC_checkfinalizer(), separatetobefnz(), and udata2finalize().
lgc_c
#define lgc_c
Definition at line 9 of file lua-5.2.4/src/lgc.c.
linktable
#define linktable (h, p) ((h)->gclist = *(p), *(p) = obj2gco(h))
Definition at line 100 of file lua-5.2.4/src/lgc.c.
Referenced by reallymarkobject(), traverseephemeron(), traversetable(), and traverseweakvalue().
LUA_CORE
#define LUA_CORE
Definition at line 10 of file lua-5.2.4/src/lgc.c.
makewhite
#define makewhite (g, x) (gch(x)->marked = cast_byte((gch(x)->marked & maskcolors) | luaC_white(g)))
Definition at line 59 of file lua-5.2.4/src/lgc.c.
#define makewhite(g,x)  \
 (gch(x)->marked = cast_byte((gch(x)->marked & maskcolors) | luaC_white(g)))
Referenced by luaC_barrier_(), luaC_checkfinalizer(), luaC_checkupvalcolor(), markbeingfnz(), and udata2finalize().
markobject
#define markobject (g, t)
Value:
        { if ((t) && iswhite(obj2gco(t))) \
        reallymarkobject(g, obj2gco(t)); }
Definition at line 78 of file lua-5.2.4/src/lgc.c.
#define markobject(g,t) { if ((t) && iswhite(obj2gco(t))) \
        reallymarkobject(g, obj2gco(t)); }
Referenced by atomic(), iscleared(), markmt(), reallymarkobject(), restartcollection(), traverseLclosure(), traverseproto(), and traversetable().
markvalue
#define markvalue (g, o)
Value:
  { checkconsistency(o); \
  if (valiswhite(o)) reallymarkobject(g,gcvalue(o)); }
Definition at line 75 of file lua-5.2.4/src/lgc.c.
#define markvalue(g,o) { checkconsistency(o); \
  if (valiswhite(o)) reallymarkobject(g,gcvalue(o)); }
Referenced by atomic(), luaC_checkupvalcolor(), reallymarkobject(), remarkupvals(), restartcollection(), traverseCclosure(), traverseproto(), traversestack(), traversestrongtable(), and traverseweakvalue().
maskcolors
#define maskcolors (~(bit2mask(BLACKBIT, OLDBIT) | WHITEBITS))
Definition at line 58 of file lua-5.2.4/src/lgc.c.
Referenced by sweeplist().
PAUSEADJ
#define PAUSEADJ 100
Definition at line 51 of file lua-5.2.4/src/lgc.c.
Referenced by setpause().
STEPMULADJ
#define STEPMULADJ 200
Definition at line 44 of file lua-5.2.4/src/lgc.c.
Referenced by incstep().
sweepphases
#define sweepphases (bitmask(GCSsweepstring) | bitmask(GCSsweepudata) | bitmask(GCSsweep))
Definition at line 924 of file lua-5.2.4/src/lgc.c.
#define sweepphases  \
    (bitmask(GCSsweepstring) | bitmask(GCSsweepudata) | bitmask(GCSsweep))
Referenced by luaC_changemode().
sweepwholelist
#define sweepwholelist (L, p) sweeplist(L,p,MAX_LUMEM)
Definition at line 690 of file lua-5.2.4/src/lgc.c.
Referenced by luaC_freeallobjects(), singlestep(), and sweepthread().
white2gray
#define white2gray (x) resetbits(gch(x)->marked, WHITEBITS)
Definition at line 62 of file lua-5.2.4/src/lgc.c.
Referenced by reallymarkobject().
Function Documentation
atomic()
static l_mem atomic (lua_State * L) static
Definition at line 999 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  l_mem work = -cast(l_mem, g->GCmemtrav);  /* start counting work */
  GCObject *origweak, *origall;
  lua_assert(!iswhite(obj2gco(g->mainthread)));
  markobject(g, L);  /* mark running thread */
  /* registry and global metatables may be changed by API */
  markvalue(g, &g->l_registry);
  markmt(g);  /* mark basic metatables */
  /* remark occasional upvalues of (maybe) dead threads */
  remarkupvals(g);
  propagateall(g);  /* propagate changes */
  work += g->GCmemtrav;  /* stop counting (do not (re)count grays) */
  /* traverse objects caught by write barrier and by 'remarkupvals' */
  retraversegrays(g);
  work -= g->GCmemtrav;  /* restart counting */
  convergeephemerons(g);
  /* at this point, all strongly accessible objects are marked. */
  /* clear values from weak tables, before checking finalizers */
  clearvalues(g, g->weak, NULL);
  clearvalues(g, g->allweak, NULL);
  origweak = g->weak; origall = g->allweak;
  work += g->GCmemtrav;  /* stop counting (objects being finalized) */
  separatetobefnz(L, 0);  /* separate objects to be finalized */
  markbeingfnz(g);  /* mark objects that will be finalized */
  propagateall(g);  /* remark, to propagate `preserveness' */
  work -= g->GCmemtrav;  /* restart counting */
  convergeephemerons(g);
  /* at this point, all resurrected objects are marked. */
  /* remove dead objects from weak tables */
  clearkeys(g, g->ephemeron, NULL);  /* clear keys from all ephemeron tables */
  clearkeys(g, g->allweak, NULL);  /* clear keys from all allweak tables */
  /* clear values from resurrected weak tables */
  clearvalues(g, g->weak, origweak);
  clearvalues(g, g->allweak, origall);
  g->currentwhite = cast_byte(otherwhite(g));  /* flip current white */
  work += g->GCmemtrav;  /* complete counting */
  return work;  /* estimate of memory marked by 'atomic' */
}
References global_State::allweak, cast, cast_byte, clearkeys(), clearvalues(), convergeephemerons(), global_State::currentwhite, global_State::ephemeron, G, global_State::GCmemtrav, iswhite, global_State::l_registry, lua_assert, global_State::mainthread, markbeingfnz(), markmt(), markobject, markvalue, NULL, obj2gco, otherwhite, propagateall(), remarkupvals(), retraversegrays(), separatetobefnz(), and global_State::weak.
Referenced by singlestep().
callallpendingfinalizers()
static void callallpendingfinalizers (lua_State * L, int propagateerrors) static
Definition at line 974 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  while (g->tobefnz) {
    resetoldbit(g->tobefnz);
    GCTM(L, propagateerrors);
  }
}
References G, GCTM(), resetoldbit, and global_State::tobefnz.
Referenced by luaC_freeallobjects(), and luaC_fullgc().
checkSizes()
static void checkSizes (lua_State * L) static
Definition at line 778 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  if (g->gckind != KGC_EMERGENCY) {  /* do not change sizes in emergency */
    int hs = g->strt.size / 2;  /* half the size of the string table */
    if (g->strt.nuse < cast(lu_int32, hs))  /* using less than that half? */
      luaS_resize(L, hs);  /* halve its size */
    luaZ_freebuffer(L, &g->buff);  /* free concatenation buffer */
  }
}
References global_State::buff, cast, G, global_State::gckind, KGC_EMERGENCY, luaS_resize(), luaZ_freebuffer, stringtable::nuse, stringtable::size, and global_State::strt.
Referenced by singlestep().
clearkeys()
static void clearkeys (global_State * g, GCObject * l, GCObject * f) static
Definition at line 625 of file lua-5.2.4/src/lgc.c.
{
  for (; l != f; l = gco2t(l)->gclist) {
    Table *h = gco2t(l);
    Node *n, *limit = gnodelast(h);
    for (n = gnode(h, 0); n < limit; n++) {
      if (!ttisnil(gval(n)) && (iscleared(g, gkey(n)))) {
        setnilvalue(gval(n));  /* remove value ... */
        removeentry(n);  /* and remove entry from table */
      }
    }
  }
}
References gco2t, gkey, gnode, gnodelast, gval, iscleared(), removeentry(), setnilvalue, and ttisnil.
Referenced by atomic().
clearvalues()
static void clearvalues (global_State * g, GCObject * l, GCObject * f) static
Definition at line 643 of file lua-5.2.4/src/lgc.c.
{
  for (; l != f; l = gco2t(l)->gclist) {
    Table *h = gco2t(l);
    Node *n, *limit = gnodelast(h);
    int i;
    for (i = 0; i < h->sizearray; i++) {
      TValue *o = &h->array[i];
      if (iscleared(g, o))  /* value was collected? */
        setnilvalue(o);  /* remove value */
    }
    for (n = gnode(h, 0); n < limit; n++) {
      if (!ttisnil(gval(n)) && iscleared(g, gval(n))) {
        setnilvalue(gval(n));  /* remove value ... */
        removeentry(n);  /* and remove entry from table */
      }
    }
  }
}
References Table::array, gco2t, gnode, gnodelast, gval, iscleared(), removeentry(), setnilvalue, Table::sizearray, and ttisnil.
Referenced by atomic().
convergeephemerons()
static void convergeephemerons (global_State * g) static
Definition at line 594 of file lua-5.2.4/src/lgc.c.
{
  int changed;
  do {
    GCObject *w;
    GCObject *next = g->ephemeron;  /* get ephemeron list */
    g->ephemeron = NULL;  /* tables will return to this list when traversed */
    changed = 0;
    while ((w = next) != NULL) {
      next = gco2t(w)->gclist;
      if (traverseephemeron(g, gco2t(w))) {  /* traverse marked some value? */
        propagateall(g);  /* propagate changes */
        changed = 1;  /* will have to revisit all ephemeron tables */
      }
    }
  } while (changed);
}
References global_State::ephemeron, gco2t, next, NULL, propagateall(), and traverseephemeron().
Referenced by atomic().
dothecall()
static void dothecall (lua_State * L, void * ud) static
Definition at line 803 of file lua-5.2.4/src/lgc.c.
{
  UNUSED(ud);
  luaD_call(L, L->top - 2, 0, 0);
}
References luaD_call(), lua_State::top, and UNUSED.
Referenced by GCTM().
entersweep()
static int entersweep (lua_State * L) static
Definition at line 936 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  int n = 0;
  g->gcstate = GCSsweepstring;
  lua_assert(g->sweepgc == NULL && g->sweepfin == NULL);
  /* prepare to sweep strings, finalizable objects, and regular objects */
  g->sweepstrgc = 0;
  g->sweepfin = sweeptolive(L, &g->finobj, &n);
  g->sweepgc = sweeptolive(L, &g->allgc, &n);
  return n;
}
References global_State::allgc, global_State::finobj, G, GCSsweepstring, global_State::gcstate, lua_assert, NULL, global_State::sweepfin, global_State::sweepgc, global_State::sweepstrgc, and sweeptolive().
Referenced by luaC_changemode(), luaC_fullgc(), and singlestep().
freeobj()
static void freeobj (lua_State * L, GCObject * o) static
Definition at line 663 of file lua-5.2.4/src/lgc.c.
{
  switch (gch(o)->tt) {
    case LUA_TPROTO: luaF_freeproto(L, gco2p(o)); break;
    case LUA_TLCL: {
      luaM_freemem(L, o, sizeLclosure(gco2lcl(o)->nupvalues));
      break;
    }
    case LUA_TCCL: {
      luaM_freemem(L, o, sizeCclosure(gco2ccl(o)->nupvalues));
      break;
    }
    case LUA_TUPVAL: luaF_freeupval(L, gco2uv(o)); break;
    case LUA_TTABLE: luaH_free(L, gco2t(o)); break;
    case LUA_TTHREAD: luaE_freethread(L, gco2th(o)); break;
    case LUA_TUSERDATA: luaM_freemem(L, o, sizeudata(gco2u(o))); break;
    case LUA_TSHRSTR:
      G(L)->strt.nuse--;
      /* go through */
    case LUA_TLNGSTR: {
      luaM_freemem(L, o, sizestring(gco2ts(o)));
      break;
    }
    default: lua_assert(0);
  }
}
References G, gch, gco2ccl, gco2lcl, gco2p, gco2t, gco2th, gco2ts, gco2u, gco2uv, lua_assert, LUA_TCCL, LUA_TLCL, LUA_TLNGSTR, LUA_TPROTO, LUA_TSHRSTR, LUA_TTABLE, LUA_TTHREAD, LUA_TUPVAL, LUA_TUSERDATA, luaE_freethread(), luaF_freeproto(), luaF_freeupval(), luaH_free(), luaM_freemem, sizeCclosure, sizeLclosure, sizestring, and sizeudata.
Referenced by sweeplist().
GCTM()
static void GCTM (lua_State * L, int propagateerrors) static
Definition at line 809 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  const TValue *tm;
  TValue v;
  setgcovalue(L, &v, udata2finalize(g));
  tm = luaT_gettmbyobj(L, &v, TM_GC);
  if (tm != NULL && ttisfunction(tm)) {  /* is there a finalizer? */
    int status;
    lu_byte oldah = L->allowhook;
    int running  = g->gcrunning;
    L->allowhook = 0;  /* stop debug hooks during GC metamethod */
    g->gcrunning = 0;  /* avoid GC steps */
    setobj2s(L, L->top, tm);  /* push finalizer... */
    setobj2s(L, L->top + 1, &v);  /* ... and its argument */
    L->top += 2;  /* and (next line) call the finalizer */
    status = luaD_pcall(L, dothecall, NULL, savestack(L, L->top - 2), 0);
    L->allowhook = oldah;  /* restore hooks */
    g->gcrunning = running;  /* restore state */
    if (status != LUA_OK && propagateerrors) {  /* error while running __gc? */
      if (status == LUA_ERRRUN) {  /* is there an error object? */
        const char *msg = (ttisstring(L->top - 1))
                            ? svalue(L->top - 1)
                            : "no message";
        luaO_pushfstring(L, "error in __gc metamethod (%s)", msg);
        status = LUA_ERRGCMM;  /* error in __gc metamethod */
      }
      luaD_throw(L, status);  /* re-throw error */
    }
  }
}
References lua_State::allowhook, dothecall(), G, global_State::gcrunning, LUA_ERRGCMM, LUA_ERRRUN, LUA_OK, luaD_pcall(), luaD_throw(), luaO_pushfstring(), luaT_gettmbyobj(), NULL, savestack, setgcovalue, setobj2s, svalue, TM_GC, lua_State::top, ttisfunction, ttisstring, and udata2finalize().
Referenced by callallpendingfinalizers(), and luaC_forcestep().
generationalcollection()
static void generationalcollection (lua_State * L) static
Definition at line 1117 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(g->gcstate == GCSpropagate);
  if (g->GCestimate == 0) {  /* signal for another major collection? */
    luaC_fullgc(L, 0);  /* perform a full regular collection */
    g->GCestimate = gettotalbytes(g);  /* update control */
  }
  else {
    lu_mem estimate = g->GCestimate;
    luaC_runtilstate(L, bitmask(GCSpause));  /* run complete (minor) cycle */
    g->gcstate = GCSpropagate;  /* skip restart */
    if (gettotalbytes(g) > (estimate / 100) * g->gcmajorinc)
      g->GCestimate = 0;  /* signal for a major collection */
    else
      g->GCestimate = estimate;  /* keep estimate from last major coll. */
  }
  setpause(g, gettotalbytes(g));
  lua_assert(g->gcstate == GCSpropagate);
}
References bitmask, G, global_State::GCestimate, global_State::gcmajorinc, GCSpause, GCSpropagate, global_State::gcstate, gettotalbytes, lua_assert, luaC_fullgc(), luaC_runtilstate(), and setpause().
Referenced by luaC_forcestep().
incstep()
static void incstep (lua_State * L) static
Definition at line 1139 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  l_mem debt = g->GCdebt;
  int stepmul = g->gcstepmul;
  if (stepmul < 40) stepmul = 40;  /* avoid ridiculous low values (and 0) */
  /* convert debt from Kb to 'work units' (avoid zero debt and overflows) */
  debt = (debt / STEPMULADJ) + 1;
  debt = (debt < MAX_LMEM / stepmul) ? debt * stepmul : MAX_LMEM;
  do {  /* always perform at least one single step */
    lu_mem work = singlestep(L);  /* do some work */
    debt -= work;
  } while (debt > -GCSTEPSIZE && g->gcstate != GCSpause);
  if (g->gcstate == GCSpause)
    setpause(g, g->GCestimate);  /* pause until next cycle */
  else {
    debt = (debt / stepmul) * STEPMULADJ;  /* convert 'work units' to Kb */
    luaE_setdebt(g, debt);
  }
}
References G, global_State::GCdebt, global_State::GCestimate, GCSpause, global_State::gcstate, global_State::gcstepmul, GCSTEPSIZE, luaE_setdebt(), MAX_LMEM, setpause(), singlestep(), and STEPMULADJ.
Referenced by luaC_forcestep().
iscleared()
static int iscleared (global_State * g, const TValue * o) static
Definition at line 121 of file lua-5.2.4/src/lgc.c.
{
  if (!iscollectable(o)) return 0;
  else if (ttisstring(o)) {
    markobject(g, rawtsvalue(o));  /* strings are `values', so are never weak */
    return 0;
  }
  else return iswhite(gcvalue(o));
}
References gcvalue, iscollectable, iswhite, markobject, rawtsvalue, and ttisstring.
Referenced by clearkeys(), clearvalues(), traverseephemeron(), and traverseweakvalue().
luaC_barrier_()
void luaC_barrier_ (lua_State * L, GCObject * o, GCObject * v)
Definition at line 135 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(isblack(o) && iswhite(v) && !isdead(g, v) && !isdead(g, o));
  lua_assert(g->gcstate != GCSpause);
  lua_assert(gch(o)->tt != LUA_TTABLE);
  if (keepinvariantout(g))  /* must keep invariant? */
    reallymarkobject(g, v);  /* restore invariant */
  else {  /* sweep phase */
    lua_assert(issweepphase(g));
    makewhite(g, o);  /* mark main obj. as white to avoid other barriers */
  }
}
References G, gch, GCSpause, global_State::gcstate, isblack, isdead, issweepphase, iswhite, keepinvariantout, lua_assert, LUA_TTABLE, makewhite, and reallymarkobject().
luaC_barrierback_()
void luaC_barrierback_ (lua_State * L, GCObject * o)
Definition at line 155 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(isblack(o) && !isdead(g, o) && gch(o)->tt == LUA_TTABLE);
  black2gray(o);  /* make object gray (again) */
  gco2t(o)->gclist = g->grayagain;
  g->grayagain = o;
}
References black2gray, G, gch, gco2t, global_State::grayagain, isblack, isdead, lua_assert, and LUA_TTABLE.
luaC_barrierproto_()
LUAI_FUNC void luaC_barrierproto_ (lua_State * L, Proto * p, Closure * c)
Definition at line 172 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  lua_assert(isblack(obj2gco(p)));
  if (p->cache == NULL) {  /* first time? */
    luaC_objbarrier(L, p, c);
  }
  else {  /* use a backward barrier */
    black2gray(obj2gco(p));  /* make prototype gray (again) */
    p->gclist = g->grayagain;
    g->grayagain = obj2gco(p);
  }
}
References black2gray, Proto::cache, G, Proto::gclist, global_State::grayagain, isblack, lua_assert, luaC_objbarrier, NULL, and obj2gco.
luaC_changemode()
void luaC_changemode (lua_State * L, int mode)
Definition at line 952 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  if (mode == g->gckind) return;  /* nothing to change */
  if (mode == KGC_GEN) {  /* change to generational mode */
    /* make sure gray lists are consistent */
    luaC_runtilstate(L, bitmask(GCSpropagate));
    g->GCestimate = gettotalbytes(g);
    g->gckind = KGC_GEN;
  }
  else {  /* change to incremental mode */
    /* sweep all objects to turn them back to white
       (as white has not changed, nothing extra will be collected) */
    g->gckind = KGC_NORMAL;
    entersweep(L);
    luaC_runtilstate(L, ~sweepphases);
  }
}
References bitmask, entersweep(), G, global_State::GCestimate, global_State::gckind, GCSpropagate, gettotalbytes, KGC_GEN, KGC_NORMAL, luaC_runtilstate(), and sweepphases.
Referenced by lua_gc(), and lua_gc().
luaC_checkfinalizer()
void luaC_checkfinalizer (lua_State * L, GCObject * o, Table * mt)
Definition at line 873 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  if (testbit(gch(o)->marked, SEPARATED) || /* obj. is already separated... */
      isfinalized(o) ||                           /* ... or is finalized... */
      gfasttm(g, mt, TM_GC) == NULL)                /* or has no finalizer? */
    return;  /* nothing to be done */
  else {  /* move 'o' to 'finobj' list */
    GCObject **p;
    GCheader *ho = gch(o);
    if (g->sweepgc == &ho->next) {  /* avoid removing current sweep object */
      lua_assert(issweepphase(g));
      g->sweepgc = sweeptolive(L, g->sweepgc, NULL);
    }
    /* search for pointer pointing to 'o' */
    for (p = &g->allgc; *p != o; p = &gch(*p)->next) { /* empty */ }
    *p = ho->next;  /* remove 'o' from root list */
    ho->next = g->finobj;  /* link it in list 'finobj' */
    g->finobj = o;
    l_setbit(ho->marked, SEPARATED);  /* mark it as such */
    if (!keepinvariantout(g))  /* not keeping invariant? */
      makewhite(g, o);  /* "sweep" object */
    else
      resetoldbit(o);  /* see MOVE OLD rule */
  }
}
References global_State::allgc, global_State::finobj, G, gch, gfasttm, isfinalized, issweepphase, keepinvariantout, l_setbit, lua_assert, makewhite, NULL, resetoldbit, SEPARATED, global_State::sweepgc, sweeptolive(), testbit, and TM_GC.
Referenced by lua_setmetatable().
luaC_checkupvalcolor()
void luaC_checkupvalcolor (global_State * g, UpVal * uv)
Definition at line 190 of file lua-5.2.4/src/lgc.c.
{
  GCObject *o = obj2gco(uv);
  lua_assert(!isblack(o));  /* open upvalues are never black */
  if (isgray(o)) {
    if (keepinvariant(g)) {
      resetoldbit(o);  /* see MOVE OLD rule */
      gray2black(o);  /* it is being visited now */
      markvalue(g, uv->v);
    }
    else {
      lua_assert(issweepphase(g));
      makewhite(g, o);
    }
  }
}
References gray2black, isblack, isgray, issweepphase, keepinvariant, lua_assert, makewhite, markvalue, obj2gco, resetoldbit, and UpVal::v.
Referenced by luaF_close().
luaC_forcestep()
void luaC_forcestep (lua_State * L)
Definition at line 1163 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  int i;
  if (isgenerational(g)) generationalcollection(L);
  else incstep(L);
  /* run a few finalizers (or all of them at the end of a collect cycle) */
  for (i = 0; g->tobefnz && (i < GCFINALIZENUM || g->gcstate == GCSpause); i++)
    GCTM(L, 1);  /* call one finalizer */
}
References G, GCFINALIZENUM, GCSpause, global_State::gcstate, GCTM(), generationalcollection(), incstep(), isgenerational, and global_State::tobefnz.
Referenced by lua_gc(), and luaC_step().
luaC_freeallobjects()
void luaC_freeallobjects (lua_State * L)
Definition at line 983 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  int i;
  separatetobefnz(L, 1);  /* separate all objects with finalizers */
  lua_assert(g->finobj == NULL);
  callallpendingfinalizers(L, 0);
  g->currentwhite = WHITEBITS; /* this "white" makes all objects look dead */
  g->gckind = KGC_NORMAL;
  sweepwholelist(L, &g->finobj);  /* finalizers can create objs. in 'finobj' */
  sweepwholelist(L, &g->allgc);
  for (i = 0; i < g->strt.size; i++)  /* free all string lists */
    sweepwholelist(L, &g->strt.hash[i]);
  lua_assert(g->strt.nuse == 0);
}
References global_State::allgc, callallpendingfinalizers(), global_State::currentwhite, global_State::finobj, G, global_State::gckind, stringtable::hash, KGC_NORMAL, lua_assert, NULL, stringtable::nuse, separatetobefnz(), stringtable::size, global_State::strt, sweepwholelist, and WHITEBITS.
Referenced by close_state(), close_state(), and close_state().
luaC_fullgc()
void luaC_fullgc (lua_State * L, int isemergency)
Definition at line 1189 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  int origkind = g->gckind;
  lua_assert(origkind != KGC_EMERGENCY);
  if (isemergency)  /* do not run finalizers during emergency GC */
    g->gckind = KGC_EMERGENCY;
  else {
    g->gckind = KGC_NORMAL;
    callallpendingfinalizers(L, 1);
  }
  if (keepinvariant(g)) {  /* may there be some black objects? */
    /* must sweep all objects to turn them back to white
       (as white has not changed, nothing will be collected) */
    entersweep(L);
  }
  /* finish any pending sweep phase to start a new cycle */
  luaC_runtilstate(L, bitmask(GCSpause));
  luaC_runtilstate(L, ~bitmask(GCSpause));  /* start new collection */
  luaC_runtilstate(L, bitmask(GCSpause));  /* run entire collection */
  if (origkind == KGC_GEN) {  /* generational mode? */
    /* generational mode must be kept in propagate phase */
    luaC_runtilstate(L, bitmask(GCSpropagate));
  }
  g->gckind = origkind;
  setpause(g, gettotalbytes(g));
  if (!isemergency)   /* do not run finalizers during emergency GC */
    callallpendingfinalizers(L, 1);
}
References bitmask, callallpendingfinalizers(), entersweep(), G, global_State::gckind, GCSpause, GCSpropagate, gettotalbytes, keepinvariant, KGC_EMERGENCY, KGC_GEN, KGC_NORMAL, lua_assert, luaC_runtilstate(), and setpause().
Referenced by generationalcollection().
luaC_newobj()
GCObject * luaC_newobj (lua_State * L, int tt, size_t sz, GCObject ** list, int offset)
Definition at line 212 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  char *raw = cast(char *, luaM_newobject(L, novariant(tt), sz));
  GCObject *o = obj2gco(raw + offset);
  if (list == NULL)
    list = &g->allgc;  /* standard list for collectable objects */
  gch(o)->marked = luaC_white(g);
  gch(o)->tt = tt;
  gch(o)->next = *list;
  *list = o;
  return o;
}
References global_State::allgc, cast, G, gch, luaC_white, luaM_newobject, novariant, NULL, and obj2gco.
Referenced by createstrobj(), createstrobj(), createstrobj(), lua_newthread(), luaF_findupval(), luaF_initupvals(), luaF_newCclosure(), luaF_newCclosure(), luaF_newLclosure(), luaF_newLclosure(), luaF_newproto(), luaF_newupval(), luaH_new(), luaS_newudata(), luaS_newudata(), luaS_newudata(), and newupval().
luaC_runtilstate()
void luaC_runtilstate (lua_State * L, int statesmask)
Definition at line 1110 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  while (!testbit(statesmask, g->gcstate))
    singlestep(L);
}
References G, global_State::gcstate, singlestep(), and testbit.
Referenced by generationalcollection(), luaC_changemode(), luaC_fullgc(), and luaS_resize().
luaC_step()
void luaC_step (lua_State * L)
Definition at line 1177 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  if (g->gcrunning) luaC_forcestep(L);
  else luaE_setdebt(g, -GCSTEPSIZE);  /* avoid being called too often */
}
References G, global_State::gcrunning, GCSTEPSIZE, luaC_forcestep(), and luaE_setdebt().
markbeingfnz()
static void markbeingfnz (global_State * g) static
Definition at line 311 of file lua-5.2.4/src/lgc.c.
{
  GCObject *o;
  for (o = g->tobefnz; o != NULL; o = gch(o)->next) {
    makewhite(g, o);
    reallymarkobject(g, o);
  }
}
References gch, makewhite, NULL, reallymarkobject(), and global_State::tobefnz.
Referenced by atomic(), and restartcollection().
markmt()
static void markmt (global_State * g) static
Definition at line 301 of file lua-5.2.4/src/lgc.c.
{
  int i;
  for (i=0; i < LUA_NUMTAGS; i++)
    markobject(g, g->mt[i]);
}
References LUA_NUMTAGS, markobject, and global_State::mt.
Referenced by atomic(), and restartcollection().
propagateall()
static void propagateall (global_State * g) static
Definition at line 566 of file lua-5.2.4/src/lgc.c.
{
  while (g->gray) propagatemark(g);
}
References global_State::gray, and propagatemark().
Referenced by atomic(), convergeephemerons(), propagatelist(), and retraversegrays().
propagatelist()
static void propagatelist (global_State * g, GCObject * l) static
Definition at line 571 of file lua-5.2.4/src/lgc.c.
{
  lua_assert(g->gray == NULL);  /* no grays left */
  g->gray = l;
  propagateall(g);  /* traverse all elements from 'l' */
}
References global_State::gray, lua_assert, NULL, and propagateall().
Referenced by retraversegrays().
propagatemark()
static void propagatemark (global_State * g) static
Definition at line 521 of file lua-5.2.4/src/lgc.c.
{
  lu_mem size;
  GCObject *o = g->gray;
  lua_assert(isgray(o));
  gray2black(o);
  switch (gch(o)->tt) {
    case LUA_TTABLE: {
      Table *h = gco2t(o);
      g->gray = h->gclist;  /* remove from 'gray' list */
      size = traversetable(g, h);
      break;
    }
    case LUA_TLCL: {
      LClosure *cl = gco2lcl(o);
      g->gray = cl->gclist;  /* remove from 'gray' list */
      size = traverseLclosure(g, cl);
      break;
    }
    case LUA_TCCL: {
      CClosure *cl = gco2ccl(o);
      g->gray = cl->gclist;  /* remove from 'gray' list */
      size = traverseCclosure(g, cl);
      break;
    }
    case LUA_TTHREAD: {
      lua_State *th = gco2th(o);
      g->gray = th->gclist;  /* remove from 'gray' list */
      th->gclist = g->grayagain;
      g->grayagain = o;  /* insert into 'grayagain' list */
      black2gray(o);
      size = traversestack(g, th);
      break;
    }
    case LUA_TPROTO: {
      Proto *p = gco2p(o);
      g->gray = p->gclist;  /* remove from 'gray' list */
      size = traverseproto(g, p);
      break;
    }
    default: lua_assert(0); return;
  }
  g->GCmemtrav += size;
}
References black2gray, gch, Proto::gclist, Table::gclist, lua_State::gclist, global_State::GCmemtrav, gco2ccl, gco2lcl, gco2p, gco2t, gco2th, global_State::gray, gray2black, global_State::grayagain, isgray, lua_assert, LUA_TCCL, LUA_TLCL, LUA_TPROTO, LUA_TTABLE, LUA_TTHREAD, traverseCclosure(), traverseLclosure(), traverseproto(), traversestack(), and traversetable().
Referenced by propagateall(), and singlestep().
reallymarkobject()
static void reallymarkobject (global_State * g, GCObject * o) static
Definition at line 243 of file lua-5.2.4/src/lgc.c.
{
  lu_mem size;
  white2gray(o);
  switch (gch(o)->tt) {
    case LUA_TSHRSTR:
    case LUA_TLNGSTR: {
      size = sizestring(gco2ts(o));
      break;  /* nothing else to mark; make it black */
    }
    case LUA_TUSERDATA: {
      Table *mt = gco2u(o)->metatable;
      markobject(g, mt);
      markobject(g, gco2u(o)->env);
      size = sizeudata(gco2u(o));
      break;
    }
    case LUA_TUPVAL: {
      UpVal *uv = gco2uv(o);
      markvalue(g, uv->v);
      if (uv->v != &uv->u.value)  /* open? */
        return;  /* open upvalues remain gray */
      size = sizeof(UpVal);
      break;
    }
    case LUA_TLCL: {
      gco2lcl(o)->gclist = g->gray;
      g->gray = o;
      return;
    }
    case LUA_TCCL: {
      gco2ccl(o)->gclist = g->gray;
      g->gray = o;
      return;
    }
    case LUA_TTABLE: {
      linktable(gco2t(o), &g->gray);
      return;
    }
    case LUA_TTHREAD: {
      gco2th(o)->gclist = g->gray;
      g->gray = o;
      return;
    }
    case LUA_TPROTO: {
      gco2p(o)->gclist = g->gray;
      g->gray = o;
      return;
    }
    default: lua_assert(0); return;
  }
  gray2black(o);
  g->GCmemtrav += size;
}
References gch, global_State::GCmemtrav, gco2ccl, gco2lcl, gco2p, gco2t, gco2th, gco2ts, gco2u, gco2uv, global_State::gray, gray2black, linktable, lua_assert, LUA_TCCL, LUA_TLCL, LUA_TLNGSTR, LUA_TPROTO, LUA_TSHRSTR, LUA_TTABLE, LUA_TTHREAD, LUA_TUPVAL, LUA_TUSERDATA, markobject, markvalue, Table::metatable, sizestring, sizeudata, UpVal::u, UpVal::v, UpVal::value, and white2gray.
Referenced by luaC_barrier_(), markbeingfnz(), and traverseephemeron().
remarkupvals()
static void remarkupvals (global_State * g) static
Definition at line 324 of file lua-5.2.4/src/lgc.c.
{
  UpVal *uv;
  for (uv = g->uvhead.u.l.next; uv != &g->uvhead; uv = uv->u.l.next) {
    if (isgray(obj2gco(uv)))
      markvalue(g, uv->v);
  }
}
References isgray, UpVal::l, markvalue, UpVal::next, obj2gco, UpVal::u, global_State::uvhead, and UpVal::v.
Referenced by atomic().
removeentry()
static void removeentry (Node * n) static
Definition at line 107 of file lua-5.2.4/src/lgc.c.
{
  lua_assert(ttisnil(gval(n)));
  if (valiswhite(gkey(n)))
    setdeadvalue(gkey(n));  /* unused and unmarked key; remove it */
}
References gkey, gval, lua_assert, setdeadvalue, ttisnil, and valiswhite.
Referenced by clearkeys(), clearvalues(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
restartcollection()
static void restartcollection (global_State * g) static
Definition at line 337 of file lua-5.2.4/src/lgc.c.
{
  g->gray = g->grayagain = NULL;
  g->weak = g->allweak = g->ephemeron = NULL;
  markobject(g, g->mainthread);
  markvalue(g, &g->l_registry);
  markmt(g);
  markbeingfnz(g);  /* mark any finalizing object left from previous cycle */
}
References global_State::allweak, global_State::ephemeron, global_State::gray, global_State::grayagain, global_State::l_registry, global_State::mainthread, markbeingfnz(), markmt(), markobject, markvalue, NULL, and global_State::weak.
Referenced by singlestep().
retraversegrays()
static void retraversegrays (global_State * g) static
Definition at line 582 of file lua-5.2.4/src/lgc.c.
{
  GCObject *weak = g->weak;  /* save original lists */
  GCObject *grayagain = g->grayagain;
  GCObject *ephemeron = g->ephemeron;
  g->weak = g->grayagain = g->ephemeron = NULL;
  propagateall(g);  /* traverse main gray list */
  propagatelist(g, grayagain);
  propagatelist(g, weak);
  propagatelist(g, ephemeron);
}
References global_State::ephemeron, global_State::grayagain, NULL, propagateall(), propagatelist(), and global_State::weak.
Referenced by atomic().
separatetobefnz()
static void separatetobefnz (lua_State * L, int all) static
Definition at line 845 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  GCObject **p = &g->finobj;
  GCObject *curr;
  GCObject **lastnext = &g->tobefnz;
  /* find last 'next' field in 'tobefnz' list (to add elements in its end) */
  while (*lastnext != NULL)
    lastnext = &gch(*lastnext)->next;
  while ((curr = *p) != NULL) {  /* traverse all finalizable objects */
    lua_assert(!isfinalized(curr));
    lua_assert(testbit(gch(curr)->marked, SEPARATED));
    if (!(iswhite(curr) || all))  /* not being collected? */
      p = &gch(curr)->next;  /* don't bother with it */
    else {
      l_setbit(gch(curr)->marked, FINALIZEDBIT); /* won't be finalized again */
      *p = gch(curr)->next;  /* remove 'curr' from 'finobj' list */
      gch(curr)->next = *lastnext;  /* link at the end of 'tobefnz' list */
      *lastnext = curr;
      lastnext = &gch(curr)->next;
    }
  }
}
References FINALIZEDBIT, global_State::finobj, G, gch, isfinalized, iswhite, l_setbit, lua_assert, NULL, SEPARATED, testbit, and global_State::tobefnz.
Referenced by atomic(), and luaC_freeallobjects().
setpause()
static void setpause (global_State * g, l_mem estimate) static
Definition at line 913 of file lua-5.2.4/src/lgc.c.
{
  l_mem debt, threshold;
  estimate = estimate / PAUSEADJ;  /* adjust 'estimate' */
  threshold = (g->gcpause < MAX_LMEM / estimate)  /* overflow? */
            ? estimate * g->gcpause  /* no overflow */
            : MAX_LMEM;  /* overflow; truncate to maximum */
  debt = -cast(l_mem, threshold - gettotalbytes(g));
  luaE_setdebt(g, debt);
}
References cast, global_State::gcpause, gettotalbytes, luaE_setdebt(), MAX_LMEM, and PAUSEADJ.
Referenced by generationalcollection(), incstep(), and luaC_fullgc().
singlestep()
static lu_mem singlestep (lua_State * L) static
Definition at line 1040 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  switch (g->gcstate) {
    case GCSpause: {
      /* start to count memory traversed */
      g->GCmemtrav = g->strt.size * sizeof(GCObject*);
      lua_assert(!isgenerational(g));
      restartcollection(g);
      g->gcstate = GCSpropagate;
      return g->GCmemtrav;
    }
    case GCSpropagate: {
      if (g->gray) {
        lu_mem oldtrav = g->GCmemtrav;
        propagatemark(g);
        return g->GCmemtrav - oldtrav;  /* memory traversed in this step */
      }
      else {  /* no more `gray' objects */
        lu_mem work;
        int sw;
        g->gcstate = GCSatomic;  /* finish mark phase */
        g->GCestimate = g->GCmemtrav;  /* save what was counted */;
        work = atomic(L);  /* add what was traversed by 'atomic' */
        g->GCestimate += work;  /* estimate of total memory traversed */
        sw = entersweep(L);
        return work + sw * GCSWEEPCOST;
      }
    }
    case GCSsweepstring: {
      int i;
      for (i = 0; i < GCSWEEPMAX && g->sweepstrgc + i < g->strt.size; i++)
        sweepwholelist(L, &g->strt.hash[g->sweepstrgc + i]);
      g->sweepstrgc += i;
      if (g->sweepstrgc >= g->strt.size)  /* no more strings to sweep? */
        g->gcstate = GCSsweepudata;
      return i * GCSWEEPCOST;
    }
    case GCSsweepudata: {
      if (g->sweepfin) {
        g->sweepfin = sweeplist(L, g->sweepfin, GCSWEEPMAX);
        return GCSWEEPMAX*GCSWEEPCOST;
      }
      else {
        g->gcstate = GCSsweep;
        return 0;
      }
    }
    case GCSsweep: {
      if (g->sweepgc) {
        g->sweepgc = sweeplist(L, g->sweepgc, GCSWEEPMAX);
        return GCSWEEPMAX*GCSWEEPCOST;
      }
      else {
        /* sweep main thread */
        GCObject *mt = obj2gco(g->mainthread);
        sweeplist(L, &mt, 1);
        checkSizes(L);
        g->gcstate = GCSpause;  /* finish collection */
        return GCSWEEPCOST;
      }
    }
    default: lua_assert(0); return 0;
  }
}
References atomic(), checkSizes(), entersweep(), G, global_State::GCestimate, global_State::GCmemtrav, GCSatomic, GCSpause, GCSpropagate, GCSsweep, GCSsweepstring, GCSsweepudata, global_State::gcstate, GCSWEEPCOST, GCSWEEPMAX, global_State::gray, stringtable::hash, isgenerational, lua_assert, global_State::mainthread, obj2gco, propagatemark(), restartcollection(), stringtable::size, global_State::strt, global_State::sweepfin, global_State::sweepgc, sweeplist(), global_State::sweepstrgc, and sweepwholelist.
Referenced by incstep(), and luaC_runtilstate().
sweeplist()
static GCObject ** sweeplist (lua_State * L, GCObject ** p, lu_mem count) static
Definition at line 719 of file lua-5.2.4/src/lgc.c.
{
  global_State *g = G(L);
  int ow = otherwhite(g);
  int toclear, toset;  /* bits to clear and to set in all live objects */
  int tostop;  /* stop sweep when this is true */
  if (isgenerational(g)) {  /* generational mode? */
    toclear = ~0;  /* clear nothing */
    toset = bitmask(OLDBIT);  /* set the old bit of all surviving objects */
    tostop = bitmask(OLDBIT);  /* do not sweep old generation */
  }
  else {  /* normal mode */
    toclear = maskcolors;  /* clear all color bits + old bit */
    toset = luaC_white(g);  /* make object white */
    tostop = 0;  /* do not stop */
  }
  while (*p != NULL && count-- > 0) {
    GCObject *curr = *p;
    int marked = gch(curr)->marked;
    if (isdeadm(ow, marked)) {  /* is 'curr' dead? */
      *p = gch(curr)->next;  /* remove 'curr' from list */
      freeobj(L, curr);  /* erase 'curr' */
    }
    else {
      if (testbits(marked, tostop))
        return NULL;  /* stop sweeping this list */
      if (gch(curr)->tt == LUA_TTHREAD)
        sweepthread(L, gco2th(curr));  /* sweep thread's upvalues */
      /* update marks */
      gch(curr)->marked = cast_byte((marked & toclear) | toset);
      p = &gch(curr)->next;  /* go to next element */
    }
  }
  return (*p == NULL) ? NULL : p;
}
References bitmask, cast_byte, freeobj(), G, gch, gco2th, isdeadm, isgenerational, LUA_TTHREAD, luaC_white, maskcolors, NULL, OLDBIT, otherwhite, sweepthread(), and testbits.
Referenced by singlestep(), and sweeptolive().
sweepthread()
static void sweepthread (lua_State * L, lua_State * L1) static
Definition at line 698 of file lua-5.2.4/src/lgc.c.
{
  if (L1->stack == NULL) return;  /* stack not completely built yet */
  sweepwholelist(L, &L1->openupval);  /* sweep open upvalues */
  luaE_freeCI(L1);  /* free extra CallInfo slots */
  /* should not change the stack during an emergency gc cycle */
  if (G(L)->gckind != KGC_EMERGENCY)
    luaD_shrinkstack(L1);
}
References G, KGC_EMERGENCY, luaD_shrinkstack(), luaE_freeCI(), NULL, lua_State::openupval, lua_State::stack, and sweepwholelist.
Referenced by sweeplist().
sweeptolive()
static GCObject ** sweeptolive (lua_State * L, GCObject ** p, int * n) static
Definition at line 758 of file lua-5.2.4/src/lgc.c.
{
  GCObject ** old = p;
  int i = 0;
  do {
    i++;
    p = sweeplist(L, p, 1);
  } while (p == old);
  if (n) *n += i;
  return p;
}
References sweeplist().
Referenced by entersweep(), and luaC_checkfinalizer().
traverseCclosure()
static lu_mem traverseCclosure (global_State * g, CClosure * cl) static
Definition at line 479 of file lua-5.2.4/src/lgc.c.
{
  int i;
  for (i = 0; i < cl->nupvalues; i++)  /* mark its upvalues */
    markvalue(g, &cl->upvalue[i]);
  return sizeCclosure(cl->nupvalues);
}
References markvalue, sizeCclosure, and CClosure::upvalue.
Referenced by propagatemark().
traverseephemeron()
static int traverseephemeron (global_State * g, Table * h) static
Definition at line 378 of file lua-5.2.4/src/lgc.c.
{
  int marked = 0;  /* true if an object is marked in this traversal */
  int hasclears = 0;  /* true if table has white keys */
  int prop = 0;  /* true if table has entry "white-key -> white-value" */
  Node *n, *limit = gnodelast(h);
  int i;
  /* traverse array part (numeric keys are 'strong') */
  for (i = 0; i < h->sizearray; i++) {
    if (valiswhite(&h->array[i])) {
      marked = 1;
      reallymarkobject(g, gcvalue(&h->array[i]));
    }
  }
  /* traverse hash part */
  for (n = gnode(h, 0); n < limit; n++) {
    checkdeadkey(n);
    if (ttisnil(gval(n)))  /* entry is empty? */
      removeentry(n);  /* remove it */
    else if (iscleared(g, gkey(n))) {  /* key is not marked (yet)? */
      hasclears = 1;  /* table must be cleared */
      if (valiswhite(gval(n)))  /* value not marked yet? */
        prop = 1;  /* must propagate again */
    }
    else if (valiswhite(gval(n))) {  /* value not marked yet? */
      marked = 1;
      reallymarkobject(g, gcvalue(gval(n)));  /* mark it now */
    }
  }
  if (g->gcstate != GCSatomic || prop)
    linktable(h, &g->ephemeron);  /* have to propagate again */
  else if (hasclears)  /* does table have white keys? */
    linktable(h, &g->allweak);  /* may have to clean white keys */
  else  /* no white keys */
    linktable(h, &g->grayagain);  /* no need to clean */
  return marked;
}
References global_State::allweak, Table::array, checkdeadkey, global_State::ephemeron, GCSatomic, global_State::gcstate, gcvalue, gkey, gnode, gnodelast, global_State::grayagain, gval, iscleared(), linktable, reallymarkobject(), removeentry(), Table::sizearray, ttisnil, and valiswhite.
Referenced by convergeephemerons(), and traversetable().
traverseLclosure()
static lu_mem traverseLclosure (global_State * g, LClosure * cl) static
Definition at line 486 of file lua-5.2.4/src/lgc.c.
{
  int i;
  markobject(g, cl->p);  /* mark its prototype */
  for (i = 0; i < cl->nupvalues; i++)  /* mark its upvalues */
    markobject(g, cl->upvals[i]);
  return sizeLclosure(cl->nupvalues);
}
References markobject, LClosure::p, sizeLclosure, and LClosure::upvals.
Referenced by propagatemark().
traverseproto()
static int traverseproto (global_State * g, Proto * f) static
Definition at line 457 of file lua-5.2.4/src/lgc.c.
{
  int i;
  if (f->cache && iswhite(obj2gco(f->cache)))
    f->cache = NULL;  /* allow cache to be collected */
  markobject(g, f->source);
  for (i = 0; i < f->sizek; i++)  /* mark literals */
    markvalue(g, &f->k[i]);
  for (i = 0; i < f->sizeupvalues; i++)  /* mark upvalue names */
    markobject(g, f->upvalues[i].name);
  for (i = 0; i < f->sizep; i++)  /* mark nested protos */
    markobject(g, f->p[i]);
  for (i = 0; i < f->sizelocvars; i++)  /* mark local-variable names */
    markobject(g, f->locvars[i].varname);
  return sizeof(Proto) + sizeof(Instruction) * f->sizecode +
                         sizeof(Proto *) * f->sizep +
                         sizeof(TValue) * f->sizek +
                         sizeof(int) * f->sizelineinfo +
                         sizeof(LocVar) * f->sizelocvars +
                         sizeof(Upvaldesc) * f->sizeupvalues;
}
References Proto::cache, iswhite, Proto::k, Proto::locvars, markobject, markvalue, NULL, obj2gco, Proto::p, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, Proto::upvalues, and LocVar::varname.
Referenced by propagatemark().
traversestack()
static lu_mem traversestack (global_State * g, lua_State * th) static
Definition at line 495 of file lua-5.2.4/src/lgc.c.
{
  int n = 0;
  StkId o = th->stack;
  if (o == NULL)
    return 1;  /* stack not completely built yet */
  for (; o < th->top; o++)  /* mark live elements in the stack */
    markvalue(g, o);
  if (g->gcstate == GCSatomic) {  /* final traversal? */
    StkId lim = th->stack + th->stacksize;  /* real end of stack */
    for (; o < lim; o++)  /* clear not-marked stack slice */
      setnilvalue(o);
  }
  else {  /* count call infos to compute size */
    CallInfo *ci;
    for (ci = &th->base_ci; ci != th->ci; ci = ci->next)
      n++;
  }
  return sizeof(lua_State) + sizeof(TValue) * th->stacksize +
         sizeof(CallInfo) * n;
}
References lua_State::base_ci, lua_State::ci, GCSatomic, global_State::gcstate, markvalue, CallInfo::next, NULL, setnilvalue, lua_State::stack, lua_State::stacksize, and lua_State::top.
Referenced by propagatemark().
traversestrongtable()
static void traversestrongtable (global_State * g, Table * h) static
Definition at line 416 of file lua-5.2.4/src/lgc.c.
{
  Node *n, *limit = gnodelast(h);
  int i;
  for (i = 0; i < h->sizearray; i++)  /* traverse array part */
    markvalue(g, &h->array[i]);
  for (n = gnode(h, 0); n < limit; n++) {  /* traverse hash part */
    checkdeadkey(n);
    if (ttisnil(gval(n)))  /* entry is empty? */
      removeentry(n);  /* remove it */
    else {
      lua_assert(!ttisnil(gkey(n)));
      markvalue(g, gkey(n));  /* mark key */
      markvalue(g, gval(n));  /* mark value */
    }
  }
}
References Table::array, checkdeadkey, gkey, gnode, gnodelast, gval, lua_assert, markvalue, removeentry(), Table::sizearray, and ttisnil.
Referenced by traversetable().
traversetable()
static lu_mem traversetable (global_State * g, Table * h) static
Definition at line 434 of file lua-5.2.4/src/lgc.c.
{
  const char *weakkey, *weakvalue;
  const TValue *mode = gfasttm(g, h->metatable, TM_MODE);
  markobject(g, h->metatable);
  if (mode && ttisstring(mode) &&  /* is there a weak mode? */
      ((weakkey = strchr(svalue(mode), 'k')),
       (weakvalue = strchr(svalue(mode), 'v')),
       (weakkey || weakvalue))) {  /* is really weak? */
    black2gray(obj2gco(h));  /* keep table gray */
    if (!weakkey)  /* strong keys? */
      traverseweakvalue(g, h);
    else if (!weakvalue)  /* strong values? */
      traverseephemeron(g, h);
    else  /* all weak */
      linktable(h, &g->allweak);  /* nothing to traverse now */
  }
  else  /* not weak */
    traversestrongtable(g, h);
  return sizeof(Table) + sizeof(TValue) * h->sizearray +
                         sizeof(Node) * cast(size_t, sizenode(h));
}
References global_State::allweak, black2gray, cast, gfasttm, linktable, markobject, Table::metatable, obj2gco, Table::sizearray, sizenode, svalue, TM_MODE, traverseephemeron(), traversestrongtable(), traverseweakvalue(), and ttisstring.
Referenced by propagatemark().
traverseweakvalue()
static void traverseweakvalue (global_State * g, Table * h) static
Definition at line 355 of file lua-5.2.4/src/lgc.c.
{
  Node *n, *limit = gnodelast(h);
  /* if there is array part, assume it may have white values (do not
     traverse it just to check) */
  int hasclears = (h->sizearray > 0);
  for (n = gnode(h, 0); n < limit; n++) {
    checkdeadkey(n);
    if (ttisnil(gval(n)))  /* entry is empty? */
      removeentry(n);  /* remove it */
    else {
      lua_assert(!ttisnil(gkey(n)));
      markvalue(g, gkey(n));  /* mark key */
      if (!hasclears && iscleared(g, gval(n)))  /* is there a white value? */
        hasclears = 1;  /* table will have to be cleared */
    }
  }
  if (hasclears)
    linktable(h, &g->weak);  /* has to be cleared later */
  else  /* no white values */
    linktable(h, &g->grayagain);  /* no need to clean */
}
References checkdeadkey, gkey, gnode, gnodelast, global_State::grayagain, gval, iscleared(), linktable, lua_assert, markvalue, removeentry(), Table::sizearray, ttisnil, and global_State::weak.
Referenced by traversetable().
udata2finalize()
static GCObject * udata2finalize (global_State * g) static
Definition at line 789 of file lua-5.2.4/src/lgc.c.
{
  GCObject *o = g->tobefnz;  /* get first element */
  lua_assert(isfinalized(o));
  g->tobefnz = gch(o)->next;  /* remove it from 'tobefnz' list */
  gch(o)->next = g->allgc;  /* return it to 'allgc' list */
  g->allgc = o;
  resetbit(gch(o)->marked, SEPARATED);  /* mark that it is not in 'tobefnz' */
  lua_assert(!isold(o));  /* see MOVE OLD rule */
  if (!keepinvariantout(g))  /* not keeping invariant? */
    makewhite(g, o);  /* "sweep" object */
  return o;
}
References global_State::allgc, gch, isfinalized, isold, keepinvariantout, lua_assert, makewhite, resetbit, SEPARATED, and global_State::tobefnz.
Referenced by GCTM().