Github User Fetcher: lua.c File Reference
lua.c File Reference
#include "lprefix.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lua_c
#define LUA_PROGNAME "lua"
#define LUA_INIT_VAR "LUA_INIT"
#define LUA_INITVARVERSION LUA_INIT_VAR LUA_VERSUFFIX
#define setsignal signal
#define has_error 1 /* bad option */
#define has_i 2 /* -i */
#define has_v 4 /* -v */
#define has_e 8 /* -e */
#define has_E 16 /* -E */
#define LUA_PROMPT "> "
#define LUA_PROMPT2 ">> "
#define LUA_MAXINPUT 512
#define lua_stdin_is_tty() 1 /* assume stdin is a tty */
#define lua_initreadline(L) ((void)L)
#define lua_readline(L, b, p)
#define lua_saveline(L, line) { (void)L; (void)line; }
#define lua_freeline(L, b) { (void)L; (void)b; }
#define EOFMARK "<eof>"
#define marklen (sizeof(EOFMARK)/sizeof(char) - 1)
Functions
static void lstop (lua_State *L, lua_Debug *ar)
static void laction (int i)
static void print_usage (const char *badoption)
static void l_message (const char *pname, const char *msg)
static int report (lua_State *L, int status)
static int msghandler (lua_State *L)
static int docall (lua_State *L, int narg, int nres)
static void print_version (void)
static void createargtable (lua_State *L, char **argv, int argc, int script)
static int dochunk (lua_State *L, int status)
static int dofile (lua_State *L, const char *name)
static int dostring (lua_State *L, const char *s, const char *name)
static int dolibrary (lua_State *L, const char *name)
static int pushargs (lua_State *L)
static int handle_script (lua_State *L, char **argv)
static int collectargs (char **argv, int *first)
static int runargs (lua_State *L, char **argv, int n)
static int handle_luainit (lua_State *L)
static const char * get_prompt (lua_State *L, int firstline)
static int incomplete (lua_State *L, int status)
static int pushline (lua_State *L, int firstline)
static int addreturn (lua_State *L)
static int multiline (lua_State *L)
static int loadline (lua_State *L)
static void l_print (lua_State *L)
static void doREPL (lua_State *L)
static int pmain (lua_State *L)
int main (int argc, char **argv)
Variables
static lua_State * globalL = NULL
static const char * progname = LUA_PROGNAME
Macro Definition Documentation
EOFMARK
#define EOFMARK "<eof>"
Definition at line 454 of file lua-5.4.3/src/lua.c.
Referenced by incomplete().
has_e
#define has_e 8 /* -e */
Definition at line 258 of file lua-5.4.3/src/lua.c.
Referenced by collectargs(), and pmain().
has_E
#define has_E 16 /* -E */
Definition at line 259 of file lua-5.4.3/src/lua.c.
Referenced by collectargs(), and pmain().
has_error
#define has_error 1 /* bad option */
Definition at line 255 of file lua-5.4.3/src/lua.c.
Referenced by collectargs(), and pmain().
has_i
#define has_i 2 /* -i */
Definition at line 256 of file lua-5.4.3/src/lua.c.
Referenced by collectargs(), and pmain().
has_v
#define has_v 4 /* -v */
Definition at line 257 of file lua-5.4.3/src/lua.c.
Referenced by collectargs(), and pmain().
lua_c
#define lua_c
Definition at line 7 of file lua-5.4.3/src/lua.c.
lua_freeline
#define lua_freeline (L, b) { (void)L; (void)b; }
Definition at line 431 of file lua-5.4.3/src/lua.c.
Referenced by pushline().
LUA_INIT_VAR
#define LUA_INIT_VAR "LUA_INIT"
Definition at line 29 of file lua-5.4.3/src/lua.c.
Referenced by handle_luainit().
lua_initreadline
#define lua_initreadline (L) ((void)L)
Definition at line 426 of file lua-5.4.3/src/lua.c.
Referenced by doREPL().
LUA_INITVARVERSION
#define LUA_INITVARVERSION LUA_INIT_VAR LUA_VERSUFFIX
Definition at line 32 of file lua-5.4.3/src/lua.c.
Referenced by handle_luainit().
LUA_MAXINPUT
#define LUA_MAXINPUT 512
Definition at line 375 of file lua-5.4.3/src/lua.c.
Referenced by pushline().
LUA_PROGNAME
#define LUA_PROGNAME "lua"
Definition at line 25 of file lua-5.4.3/src/lua.c.
LUA_PROMPT
#define LUA_PROMPT "> "
Definition at line 370 of file lua-5.4.3/src/lua.c.
Referenced by get_prompt().
LUA_PROMPT2
#define LUA_PROMPT2 ">> "
Definition at line 371 of file lua-5.4.3/src/lua.c.
Referenced by get_prompt().
lua_readline
#define lua_readline (L, b, p)
Value:
        ((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
        fgets(b, LUA_MAXINPUT, stdin) != NULL)  /* get line */
Definition at line 427 of file lua-5.4.3/src/lua.c.
#define lua_readline(L,b,p) \
        ((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
        fgets(b, LUA_MAXINPUT, stdin) != NULL)  /* get line */
Referenced by pushline().
lua_saveline
#define lua_saveline (L, line) { (void)L; (void)line; }
Definition at line 430 of file lua-5.4.3/src/lua.c.
Referenced by addreturn(), and multiline().
lua_stdin_is_tty
#define lua_stdin_is_tty () 1 /* assume stdin is a tty */
Definition at line 400 of file lua-5.4.3/src/lua.c.
Referenced by pmain().
marklen
#define marklen (sizeof(EOFMARK)/sizeof(char) - 1)
Definition at line 455 of file lua-5.4.3/src/lua.c.
Referenced by incomplete().
setsignal
#define setsignal signal
Definition at line 55 of file lua-5.4.3/src/lua.c.
Referenced by docall(), and laction().
Function Documentation
addreturn()
static int addreturn (lua_State * L) static
Definition at line 504 of file lua-5.4.3/src/lua.c.
{
  const char *line = lua_tostring(L, -1);  /* original line */
  const char *retline = lua_pushfstring(L, "return %s;", line);
  int status = luaL_loadbuffer(L, retline, strlen(retline), "=stdin");
  if (status == LUA_OK) {
    lua_remove(L, -2);  /* remove modified line */
    if (line[0] != '\0')  /* non empty? */
      lua_saveline(L, line);  /* keep history */
  }
  else
    lua_pop(L, 2);  /* pop result from 'luaL_loadbuffer' and modified line */
  return status;
}
References LUA_OK, lua_pop, lua_pushfstring(), lua_remove, lua_saveline, lua_tostring, and luaL_loadbuffer.
Referenced by loadline().
collectargs()
static int collectargs (char ** argv, int * first) static
Definition at line 268 of file lua-5.4.3/src/lua.c.
{
  int args = 0;
  int i;
  for (i = 1; argv[i] != NULL; i++) {
    *first = i;
    if (argv[i][0] != '-')  /* not an option? */
        return args;  /* stop handling options */
    switch (argv[i][1]) {  /* else check option */
      case '-':  /* '--' */
        if (argv[i][2] != '\0')  /* extra characters after '--'? */
          return has_error;  /* invalid option */
        *first = i + 1;
        return args;
      case '\0':  /* '-' */
        return args;  /* script "name" is '-' */
      case 'E':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_E;
        break;
      case 'W':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        break;
      case 'i':
        args |= has_i;  /* (-i implies -v) *//* FALLTHROUGH */
      case 'v':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_v;
        break;
      case 'e':
        args |= has_e;  /* FALLTHROUGH */
      case 'l':  /* both options need an argument */
        if (argv[i][2] == '\0') {  /* no concatenated argument? */
          i++;  /* try next 'argv' */
          if (argv[i] == NULL || argv[i][0] == '-')
            return has_error;  /* no next argument or it is another option */
        }
        break;
      default:  /* invalid option */
        return has_error;
    }
  }
  *first = i;  /* no script name */
  return args;
}
References has_e, has_E, has_error, has_i, has_v, and NULL.
Referenced by pmain().
createargtable()
static void createargtable (lua_State * L, char ** argv, int argc, int script) static
Definition at line 180 of file lua-5.4.3/src/lua.c.
{
  int i, narg;
  if (script == argc) script = 0;  /* no script name? */
  narg = argc - (script + 1);  /* number of positive indices */
  lua_createtable(L, narg, script + 1);
  for (i = 0; i < argc; i++) {
    lua_pushstring(L, argv[i]);
    lua_rawseti(L, -2, i - script);
  }
  lua_setglobal(L, "arg");
}
References lua_createtable(), lua_pushstring(), lua_rawseti(), and lua_setglobal.
Referenced by pmain().
docall()
static int docall (lua_State * L, int narg, int nres) static
Definition at line 152 of file lua-5.4.3/src/lua.c.
{
  int status;
  int base = lua_gettop(L) - narg;  /* function index */
  lua_pushcfunction(L, msghandler);  /* push message handler */
  lua_insert(L, base);  /* put it under function and args */
  globalL = L;  /* to be available to 'laction' */
  setsignal(SIGINT, laction);  /* set C-signal handler */
  status = lua_pcall(L, narg, nres, base);
  setsignal(SIGINT, SIG_DFL); /* reset C-signal handler */
  lua_remove(L, base);  /* remove message handler from the stack */
  return status;
}
References globalL, laction(), lua_gettop(), lua_insert, lua_pcall, lua_pushcfunction, lua_remove, msghandler(), and setsignal.
Referenced by dochunk(), dolibrary(), doREPL(), and handle_script().
dochunk()
static int dochunk (lua_State * L, int status) static
Definition at line 193 of file lua-5.4.3/src/lua.c.
{
  if (status == LUA_OK) status = docall(L, 0, 0);
  return report(L, status);
}
References docall(), LUA_OK, and report().
Referenced by dofile(), and dostring().
dofile()
static int dofile (lua_State * L, const char * name) static
Definition at line 199 of file lua-5.4.3/src/lua.c.
{
  return dochunk(L, luaL_loadfile(L, name));
}
References dochunk(), luaL_loadfile, and name.
Referenced by handle_luainit(), and pmain().
dolibrary()
static int dolibrary (lua_State * L, const char * name) static
Definition at line 213 of file lua-5.4.3/src/lua.c.
{
  int status;
  lua_getglobal(L, "require");
  lua_pushstring(L, name);
  status = docall(L, 1, 1);  /* call 'require(name)' */
  if (status == LUA_OK)
    lua_setglobal(L, name);  /* global[name] = require return */
  return report(L, status);
}
References docall(), lua_getglobal, LUA_OK, lua_pushstring(), lua_setglobal, name, and report().
Referenced by runargs().
doREPL()
static void doREPL (lua_State * L) static
Definition at line 577 of file lua-5.4.3/src/lua.c.
{
  int status;
  const char *oldprogname = progname;
  progname = NULL;  /* no 'progname' on errors in interactive mode */
  lua_initreadline(L);
  while ((status = loadline(L)) != -1) {
    if (status == LUA_OK)
      status = docall(L, 0, LUA_MULTRET);
    if (status == LUA_OK) l_print(L);
    else report(L, status);
  }
  lua_settop(L, 0);  /* clear stack */
  lua_writeline();
  progname = oldprogname;
}
References docall(), l_print(), loadline(), lua_initreadline, LUA_MULTRET, LUA_OK, lua_settop(), lua_writeline, NULL, progname, and report().
Referenced by pmain().
dostring()
static int dostring (lua_State * L, const char * s, const char * name) static
Definition at line 204 of file lua-5.4.3/src/lua.c.
{
  return dochunk(L, luaL_loadbuffer(L, s, strlen(s), name));
}
References dochunk(), luaL_loadbuffer, name, and s.
Referenced by handle_luainit(), and runargs().
get_prompt()
static const char * get_prompt (lua_State * L, int firstline) static
Definition at line 443 of file lua-5.4.3/src/lua.c.
{
  if (lua_getglobal(L, firstline ? "_PROMPT" : "_PROMPT2") == LUA_TNIL)
    return (firstline ? LUA_PROMPT : LUA_PROMPT2);  /* use the default */
  else {  /* apply 'tostring' over the value */
    const char *p = luaL_tolstring(L, -1, NULL);
    lua_remove(L, -2);  /* remove original value */
    return p;
  }
}
References lua_getglobal, LUA_PROMPT, LUA_PROMPT2, lua_remove, LUA_TNIL, luaL_tolstring(), and NULL.
Referenced by pushline().
handle_luainit()
static int handle_luainit (lua_State * L) static
Definition at line 348 of file lua-5.4.3/src/lua.c.
{
  const char *name = "=" LUA_INITVARVERSION;
  const char *init = getenv(name + 1);
  if (init == NULL) {
    name = "=" LUA_INIT_VAR;
    init = getenv(name + 1);  /* try alternative name */
  }
  if (init == NULL) return LUA_OK;
  else if (init[0] == '@')
    return dofile(L, init+1);
  else
    return dostring(L, init, name);
}
References dofile(), dostring(), LUA_INIT_VAR, LUA_INITVARVERSION, LUA_OK, name, and NULL.
Referenced by pmain().
handle_script()
static int handle_script (lua_State * L, char ** argv) static
Definition at line 240 of file lua-5.4.3/src/lua.c.
{
  int status;
  const char *fname = argv[0];
  if (strcmp(fname, "-") == 0 && strcmp(argv[-1], "--") != 0)
    fname = NULL;  /* stdin */
  status = luaL_loadfile(L, fname);
  if (status == LUA_OK) {
    int n = pushargs(L);  /* push arguments to script */
    status = docall(L, n, LUA_MULTRET);
  }
  return report(L, status);
}
References docall(), LUA_MULTRET, LUA_OK, luaL_loadfile, NULL, pushargs(), and report().
Referenced by pmain().
incomplete()
static int incomplete (lua_State * L, int status) static
Definition at line 463 of file lua-5.4.3/src/lua.c.
{
  if (status == LUA_ERRSYNTAX) {
    size_t lmsg;
    const char *msg = lua_tolstring(L, -1, &lmsg);
    if (lmsg >= marklen && strcmp(msg + lmsg - marklen, EOFMARK) == 0) {
      lua_pop(L, 1);
      return 1;
    }
  }
  return 0;  /* else... */
}
References EOFMARK, LUA_ERRSYNTAX, lua_pop, lua_tolstring(), and marklen.
Referenced by multiline().
l_message()
static void l_message (const char * pname, const char * msg) static
Definition at line 109 of file lua-5.4.3/src/lua.c.
{
  if (pname) lua_writestringerror("%s: ", pname);
  lua_writestringerror("%s\n", msg);
}
References lua_writestringerror.
Referenced by l_print(), main(), and report().
l_print()
static void l_print (lua_State * L) static
Definition at line 560 of file lua-5.4.3/src/lua.c.
{
  int n = lua_gettop(L);
  if (n > 0) {  /* any result to be printed? */
    luaL_checkstack(L, LUA_MINSTACK, "too many results to print");
    lua_getglobal(L, "print");
    lua_insert(L, 1);
    if (lua_pcall(L, n, 0, 0) != LUA_OK)
      l_message(progname, lua_pushfstring(L, "error calling 'print' (%s)",
                                             lua_tostring(L, -1)));
  }
}
References l_message(), lua_getglobal, lua_gettop(), lua_insert, LUA_MINSTACK, LUA_OK, lua_pcall, lua_pushfstring(), lua_tostring, luaL_checkstack(), and progname.
Referenced by doREPL().
laction()
static void laction (int i) static
Definition at line 76 of file lua-5.4.3/src/lua.c.
{
  int flag = LUA_MASKCALL | LUA_MASKRET | LUA_MASKLINE | LUA_MASKCOUNT;
  setsignal(i, SIG_DFL); /* if another SIGINT happens, terminate process */
  lua_sethook(globalL, lstop, flag, 1);
}
References globalL, lstop(), LUA_MASKCALL, LUA_MASKCOUNT, LUA_MASKLINE, LUA_MASKRET, lua_sethook(), and setsignal.
Referenced by docall().
loadline()
static int loadline (lua_State * L) static
Definition at line 544 of file lua-5.4.3/src/lua.c.
{
  int status;
  lua_settop(L, 0);
  if (!pushline(L, 1))
    return -1;  /* no input */
  if ((status = addreturn(L)) != LUA_OK)  /* 'return ...' did not work? */
    status = multiline(L);  /* try as command, maybe with continuation lines */
  lua_remove(L, 1);  /* remove line from the stack */
  lua_assert(lua_gettop(L) == 1);
  return status;
}
References addreturn(), lua_assert, lua_gettop(), LUA_OK, lua_remove, lua_settop(), multiline(), and pushline().
Referenced by doREPL().
lstop()
static void lstop (lua_State * L, lua_Debug * ar) static
Definition at line 63 of file lua-5.4.3/src/lua.c.
{
  (void)ar;  /* unused arg. */
  lua_sethook(L, NULL, 0, 0);  /* reset hook */
  luaL_error(L, "interrupted!");
}
References lua_sethook(), luaL_error(), and NULL.
Referenced by laction().
main()
int main (int argc, char ** argv)
Definition at line 643 of file lua-5.4.3/src/lua.c.
{
  int status, result;
  lua_State *L = luaL_newstate();  /* create state */
  if (L == NULL) {
    l_message(argv[0], "cannot create state: not enough memory");
    return EXIT_FAILURE;
  }
  lua_pushcfunction(L, &pmain);  /* to call 'pmain' in protected mode */
  lua_pushinteger(L, argc);  /* 1st argument */
  lua_pushlightuserdata(L, argv); /* 2nd argument */
  status = lua_pcall(L, 2, 1, 0);  /* do the call */
  result = lua_toboolean(L, -1);  /* get result */
  report(L, status);
  lua_close(L);
  return (result && status == LUA_OK) ? EXIT_SUCCESS : EXIT_FAILURE;
}
References l_message(), lua_close(), LUA_OK, lua_pcall, lua_pushcfunction, lua_pushinteger(), lua_pushlightuserdata(), lua_toboolean(), luaL_newstate(), NULL, pmain(), and report().
msghandler()
static int msghandler (lua_State * L) static
Definition at line 133 of file lua-5.4.3/src/lua.c.
{
  const char *msg = lua_tostring(L, 1);
  if (msg == NULL) {  /* is error object not a string? */
    if (luaL_callmeta(L, 1, "__tostring") &&  /* does it have a metamethod */
        lua_type(L, -1) == LUA_TSTRING)  /* that produces a string? */
      return 1;  /* that is the message */
    else
      msg = lua_pushfstring(L, "(error object is a %s value)",
                               luaL_typename(L, 1));
  }
  luaL_traceback(L, L, msg, 1);  /* append a standard traceback */
  return 1;  /* return the traceback */
}
References lua_pushfstring(), lua_tostring, LUA_TSTRING, lua_type(), luaL_callmeta(), luaL_traceback(), luaL_typename, and NULL.
Referenced by docall().
multiline()
static int multiline (lua_State * L) static
Definition at line 522 of file lua-5.4.3/src/lua.c.
{
  for (;;) {  /* repeat until gets a complete statement */
    size_t len;
    const char *line = lua_tolstring(L, 1, &len);  /* get what it has */
    int status = luaL_loadbuffer(L, line, len, "=stdin");  /* try it */
    if (!incomplete(L, status) || !pushline(L, 0)) {
      lua_saveline(L, line);  /* keep history */
      return status;  /* cannot or should not try to add continuation line */
    }
    lua_pushliteral(L, "\n");  /* add newline... */
    lua_insert(L, -2);  /* ...between the two lines */
    lua_concat(L, 3);  /* join them */
  }
}
References incomplete(), lua_concat(), lua_insert, lua_pushliteral, lua_saveline, lua_tolstring(), luaL_loadbuffer, and pushline().
Referenced by loadline().
pmain()
static int pmain (lua_State * L) static
Definition at line 600 of file lua-5.4.3/src/lua.c.
{
  int argc = (int)lua_tointeger(L, 1);
  char **argv = (char **)lua_touserdata(L, 2);
  int script;
  int args = collectargs(argv, &script);
  luaL_checkversion(L);  /* check that interpreter has correct version */
  if (argv[0] && argv[0][0]) progname = argv[0];
  if (args == has_error) {  /* bad arg? */
    print_usage(argv[script]);  /* 'script' has index of bad arg. */
    return 0;
  }
  if (args & has_v)  /* option '-v'? */
    print_version();
  if (args & has_E) {  /* option '-E'? */
    lua_pushboolean(L, 1);  /* signal for libraries to ignore env. vars. */
    lua_setfield(L, LUA_REGISTRYINDEX, "LUA_NOENV");
  }
  luaL_openlibs(L);  /* open standard libraries */
  createargtable(L, argv, argc, script);  /* create table 'arg' */
  lua_gc(L, LUA_GCGEN, 0, 0);  /* GC in generational mode */
  if (!(args & has_E)) {  /* no option '-E'? */
    if (handle_luainit(L) != LUA_OK)  /* run LUA_INIT */
      return 0;  /* error running LUA_INIT */
  }
  if (!runargs(L, argv, script))  /* execute arguments -e and -l */
    return 0;  /* something failed */
  if (script < argc &&  /* execute main script (if there is one) */
      handle_script(L, argv + script) != LUA_OK)
    return 0;
  if (args & has_i)  /* -i option? */
    doREPL(L);  /* do read-eval-print loop */
  else if (script == argc && !(args & (has_e | has_v))) {  /* no arguments? */
    if (lua_stdin_is_tty()) {  /* running in interactive mode? */
      print_version();
      doREPL(L);  /* do read-eval-print loop */
    }
    else dofile(L, NULL);  /* executes stdin as a file */
  }
  lua_pushboolean(L, 1);  /* signal no errors */
  return 1;
}
References collectargs(), createargtable(), dofile(), doREPL(), handle_luainit(), handle_script(), has_e, has_E, has_error, has_i, has_v, lua_gc(), LUA_GCGEN, LUA_OK, lua_pushboolean(), LUA_REGISTRYINDEX, lua_setfield(), lua_stdin_is_tty, lua_tointeger, lua_touserdata(), luaL_checkversion, luaL_openlibs(), NULL, print_usage(), print_version(), progname, and runargs().
Referenced by main().
print_usage()
static void print_usage (const char * badoption) static
Definition at line 83 of file lua-5.4.3/src/lua.c.
{
  lua_writestringerror("%s: ", progname);
  if (badoption[1] == 'e' || badoption[1] == 'l')
    lua_writestringerror("'%s' needs argument\n", badoption);
  else
    lua_writestringerror("unrecognized option '%s'\n", badoption);
  lua_writestringerror(
  "usage: %s [options] [script [args]]\n"
  "Available options are:\n"
  "  -e stat  execute string 'stat'\n"
  "  -i       enter interactive mode after executing 'script'\n"
  "  -l name  require library 'name' into global 'name'\n"
  "  -v       show version information\n"
  "  -E       ignore environment variables\n"
  "  -W       turn warnings on\n"
  "  --       stop handling options\n"
  "  -        stop handling options and execute stdin\n"
  ,
  progname);
}
References lua_writestringerror, and progname.
print_version()
static void print_version (void) static
Definition at line 166 of file lua-5.4.3/src/lua.c.
{
  lua_writestring(LUA_COPYRIGHT, strlen(LUA_COPYRIGHT));
  lua_writeline();
}
References LUA_COPYRIGHT, lua_writeline, and lua_writestring.
Referenced by pmain().
pushargs()
static int pushargs (lua_State * L) static
Definition at line 227 of file lua-5.4.3/src/lua.c.
{
  int i, n;
  if (lua_getglobal(L, "arg") != LUA_TTABLE)
    luaL_error(L, "'arg' is not a table");
  n = (int)luaL_len(L, -1);
  luaL_checkstack(L, n + 3, "too many arguments to script");
  for (i = 1; i <= n; i++)
    lua_rawgeti(L, -i, i);
  lua_remove(L, -i);  /* remove table from the stack */
  return n;
}
References lua_getglobal, lua_rawgeti(), lua_remove, LUA_TTABLE, luaL_checkstack(), luaL_error(), and luaL_len().
Referenced by handle_script().
pushline()
static int pushline (lua_State * L, int firstline) static
Definition at line 479 of file lua-5.4.3/src/lua.c.
{
  char buffer[LUA_MAXINPUT];
  char *b = buffer;
  size_t l;
  const char *prmt = get_prompt(L, firstline);
  int readstatus = lua_readline(L, b, prmt);
  if (readstatus == 0)
    return 0;  /* no input (prompt will be popped by caller) */
  lua_pop(L, 1);  /* remove prompt */
  l = strlen(b);
  if (l > 0 && b[l-1] == '\n')  /* line ends with newline? */
    b[--l] = '\0';  /* remove it */
  if (firstline && b[0] == '=')  /* for compatibility with 5.2, ... */
    lua_pushfstring(L, "return %s", b + 1);  /* change '=' to 'return' */
  else
    lua_pushlstring(L, b, l);
  lua_freeline(L, b);
  return 1;
}
References get_prompt(), lua_freeline, LUA_MAXINPUT, lua_pop, lua_pushfstring(), lua_pushlstring(), and lua_readline.
Referenced by loadline(), and multiline().
report()
static int report (lua_State * L, int status) static
Definition at line 120 of file lua-5.4.3/src/lua.c.
{
  if (status != LUA_OK) {
    const char *msg = lua_tostring(L, -1);
    l_message(progname, msg);
    lua_pop(L, 1);  /* remove message */
  }
  return status;
}
References l_message(), LUA_OK, lua_pop, lua_tostring, and progname.
Referenced by dochunk(), dolibrary(), doREPL(), handle_script(), and main().
runargs()
static int runargs (lua_State * L, char ** argv, int n) static
Definition at line 322 of file lua-5.4.3/src/lua.c.
{
  int i;
  for (i = 1; i < n; i++) {
    int option = argv[i][1];
    lua_assert(argv[i][0] == '-');  /* already checked */
    switch (option) {
      case 'e':  case 'l': {
        int status;
        const char *extra = argv[i] + 2;  /* both options need an argument */
        if (*extra == '\0') extra = argv[++i];
        lua_assert(extra != NULL);
        status = (option == 'e')
                 ? dostring(L, extra, "=(command line)")
                 : dolibrary(L, extra);
        if (status != LUA_OK) return 0;
        break;
      }
      case 'W':
        lua_warning(L, "@on", 0);  /* warnings on */
        break;
    }
  }
  return 1;
}
References dolibrary(), dostring(), lua_assert, LUA_OK, lua_warning(), and NULL.
Referenced by pmain().
Variable Documentation
globalL
lua_State* globalL = NULL static
Definition at line 35 of file lua-5.4.3/src/lua.c.
Referenced by docall(), and laction().
progname
const char* progname = LUA_PROGNAME static
Definition at line 37 of file lua-5.4.3/src/lua.c.
Referenced by doREPL(), l_print(), pmain(), print_usage(), and report().