Github User Fetcher: lstrlib.c File Reference
lstrlib.c File Reference
#include <ctype.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Data Structures
struct MatchState
Macros
#define lstrlib_c
#define LUA_LIB
#define uchar(c) ((unsigned char)(c))
#define CAP_UNFINISHED (-1)
#define CAP_POSITION (-2)
#define L_ESC '%'
#define SPECIALS "^$*+?.([%-"
#define MAX_ITEM 512
#define FLAGS "-+ #0"
#define MAX_FORMAT (sizeof(FLAGS) + sizeof(LUA_INTFRMLEN) + 10)
Typedefs
typedef struct MatchState MatchState
Functions
static int str_len (lua_State *L)
static ptrdiff_t posrelat (ptrdiff_t pos, size_t len)
static int str_sub (lua_State *L)
static int str_reverse (lua_State *L)
static int str_lower (lua_State *L)
static int str_upper (lua_State *L)
static int str_rep (lua_State *L)
static int str_byte (lua_State *L)
static int str_char (lua_State *L)
static int writer (lua_State *L, const void *b, size_t size, void *B)
static int str_dump (lua_State *L)
static int check_capture (MatchState *ms, int l)
static int capture_to_close (MatchState *ms)
static const char * classend (MatchState *ms, const char *p)
static int match_class (int c, int cl)
static int matchbracketclass (int c, const char *p, const char *ec)
static int singlematch (int c, const char *p, const char *ep)
static const char * match (MatchState *ms, const char *s, const char *p)
static const char * matchbalance (MatchState *ms, const char *s, const char *p)
static const char * max_expand (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * min_expand (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * start_capture (MatchState *ms, const char *s, const char *p, int what)
static const char * end_capture (MatchState *ms, const char *s, const char *p)
static const char * match_capture (MatchState *ms, const char *s, int l)
static const char * lmemfind (const char *s1, size_t l1, const char *s2, size_t l2)
static void push_onecapture (MatchState *ms, int i, const char *s, const char *e)
static int push_captures (MatchState *ms, const char *s, const char *e)
static int str_find_aux (lua_State *L, int find)
static int str_find (lua_State *L)
static int str_match (lua_State *L)
static int gmatch_aux (lua_State *L)
static int gmatch (lua_State *L)
static int gfind_nodef (lua_State *L)
static void add_s (MatchState *ms, luaL_Buffer *b, const char *s, const char *e)
static void add_value (MatchState *ms, luaL_Buffer *b, const char *s, const char *e)
static int str_gsub (lua_State *L)
static void addquoted (lua_State *L, luaL_Buffer *b, int arg)
static const char * scanformat (lua_State *L, const char *strfrmt, char *form)
static void addintlen (char *form)
static int str_format (lua_State *L)
static void createmetatable (lua_State *L)
LUALIB_API int luaopen_string (lua_State *L)
Variables
static const luaL_Reg strlib []
Macro Definition Documentation
CAP_POSITION
#define CAP_POSITION (-2)
Definition at line 168 of file lua-5.1.5/src/lstrlib.c.
Referenced by match(), and push_onecapture().
CAP_UNFINISHED
#define CAP_UNFINISHED (-1)
Definition at line 167 of file lua-5.1.5/src/lstrlib.c.
Referenced by capture_to_close(), check_capture(), end_capture(), match(), and push_onecapture().
FLAGS
#define FLAGS "-+ #0"
Definition at line 688 of file lua-5.1.5/src/lstrlib.c.
Referenced by scanformat().
L_ESC
#define L_ESC '%'
Definition at line 182 of file lua-5.1.5/src/lstrlib.c.
Referenced by add_s(), classend(), match(), matchbracketclass(), singlematch(), and str_format().
lstrlib_c
#define lstrlib_c
Definition at line 14 of file lua-5.1.5/src/lstrlib.c.
LUA_LIB
#define LUA_LIB
Definition at line 15 of file lua-5.1.5/src/lstrlib.c.
MAX_FORMAT
#define MAX_FORMAT (sizeof(FLAGS) + sizeof(LUA_INTFRMLEN) + 10)
Definition at line 693 of file lua-5.1.5/src/lstrlib.c.
Referenced by str_format().
MAX_ITEM
#define MAX_ITEM 512
Definition at line 686 of file lua-5.1.5/src/lstrlib.c.
Referenced by str_format().
SPECIALS
#define SPECIALS "^$*+?.([%-"
Definition at line 183 of file lua-5.1.5/src/lstrlib.c.
Referenced by str_find_aux().
uchar
#define uchar (c) ((unsigned char)(c))
Definition at line 24 of file lua-5.1.5/src/lstrlib.c.
Referenced by add_s(), match(), matchbracketclass(), max_expand(), min_expand(), scanformat(), singlematch(), str_byte(), str_char(), str_lower(), and str_upper().
Typedef Documentation
MatchState
typedef struct MatchState MatchState
Function Documentation
add_s()
static void add_s (MatchState * ms, luaL_Buffer * b, const char * s, const char * e) static
Definition at line 590 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l, i;
  const char *news = lua_tolstring(ms->L, 3, &l);
  for (i = 0; i < l; i++) {
    if (news[i] != L_ESC)
      luaL_addchar(b, news[i]);
    else {
      i++;  /* skip ESC */
      if (!isdigit(uchar(news[i])))
        luaL_addchar(b, news[i]);
      else if (news[i] == '0')
          luaL_addlstring(b, s, e - s);
      else {
        push_onecapture(ms, news[i] - '1', s, e);
        luaL_addvalue(b);  /* add capture to accumulated result */
      }
    }
  }
}
References MatchState::L, L_ESC, lua_tolstring(), luaL_addchar, luaL_addlstring(), luaL_addvalue(), push_onecapture(), s, and uchar.
Referenced by add_value().
add_value()
static void add_value (MatchState * ms, luaL_Buffer * b, const char * s, const char * e) static
Definition at line 612 of file lua-5.1.5/src/lstrlib.c.
{
  lua_State *L = ms->L;
  switch (lua_type(L, 3)) {
    case LUA_TNUMBER:
    case LUA_TSTRING: {
      add_s(ms, b, s, e);
      return;
    }
    case LUA_TFUNCTION: {
      int n;
      lua_pushvalue(L, 3);
      n = push_captures(ms, s, e);
      lua_call(L, n, 1);
      break;
    }
    case LUA_TTABLE: {
      push_onecapture(ms, 0, s, e);
      lua_gettable(L, 3);
      break;
    }
  }
  if (!lua_toboolean(L, -1)) {  /* nil or false? */
    lua_pop(L, 1);
    lua_pushlstring(L, s, e - s);  /* keep original text */
  }
  else if (!lua_isstring(L, -1))
    luaL_error(L, "invalid replacement value (a %s)", luaL_typename(L, -1));
  luaL_addvalue(b);  /* add result to accumulator */
}
References add_s(), MatchState::L, lua_call, lua_gettable(), lua_isstring(), lua_pop, lua_pushlstring(), lua_pushvalue(), LUA_TFUNCTION, LUA_TNUMBER, lua_toboolean(), LUA_TSTRING, LUA_TTABLE, lua_type(), luaL_addvalue(), luaL_error(), luaL_typename, push_captures(), push_onecapture(), and s.
Referenced by str_gsub().
addintlen()
static void addintlen (char * form) static
Definition at line 747 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l = strlen(form);
  char spec = form[l - 1];
  strcpy(form + l - 1, LUA_INTFRMLEN);
  form[l + sizeof(LUA_INTFRMLEN) - 2] = spec;
  form[l + sizeof(LUA_INTFRMLEN) - 1] = '\0';
}
References LUA_INTFRMLEN.
Referenced by str_format().
addquoted()
static void addquoted (lua_State * L, luaL_Buffer * b, int arg) static
Definition at line 696 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l;
  const char *s = luaL_checklstring(L, arg, &l);
  luaL_addchar(b, '"');
  while (l--) {
    switch (*s) {
      case '"': case '\\': case '\n': {
        luaL_addchar(b, '\\');
        luaL_addchar(b, *s);
        break;
      }
      case '\r': {
        luaL_addlstring(b, "\\r", 2);
        break;
      }
      case '\0': {
        luaL_addlstring(b, "\\000", 4);
        break;
      }
      default: {
        luaL_addchar(b, *s);
        break;
      }
    }
    s++;
  }
  luaL_addchar(b, '"');
}
References arg, luaL_addchar, luaL_addlstring(), luaL_checklstring(), and s.
Referenced by str_format().
capture_to_close()
static int capture_to_close (MatchState * ms) static
Definition at line 194 of file lua-5.1.5/src/lstrlib.c.
{
  int level = ms->level;
  for (level--; level>=0; level--)
    if (ms->capture[level].len == CAP_UNFINISHED) return level;
  return luaL_error(ms->L, "invalid pattern capture");
}
References CAP_UNFINISHED, MatchState::capture, MatchState::L, MatchState::len, MatchState::level, and luaL_error().
Referenced by end_capture().
check_capture()
static int check_capture (MatchState * ms, int l) static
Definition at line 186 of file lua-5.1.5/src/lstrlib.c.
{
  l -= '1';
  if (l < 0 || l >= ms->level || ms->capture[l].len == CAP_UNFINISHED)
    return luaL_error(ms->L, "invalid capture index");
  return l;
}
References CAP_UNFINISHED, MatchState::capture, MatchState::L, MatchState::len, MatchState::level, and luaL_error().
Referenced by match_capture().
classend()
static const char * classend (MatchState * ms, const char * p) static
Definition at line 202 of file lua-5.1.5/src/lstrlib.c.
{
  switch (*p++) {
    case L_ESC: {
      if (*p == '\0')
        luaL_error(ms->L, "malformed pattern (ends with " LUA_QL("%%") ")");
      return p+1;
    }
    case '[': {
      if (*p == '^') p++;
      do {  /* look for a `]' */
        if (*p == '\0')
          luaL_error(ms->L, "malformed pattern (missing " LUA_QL("]") ")");
        if (*(p++) == L_ESC && *p != '\0')
          p++;  /* skip escapes (e.g. `%]') */
      } while (*p != ']');
      return p+1;
    }
    default: {
      return p;
    }
  }
}
References MatchState::L, L_ESC, LUA_QL, and luaL_error().
Referenced by match().
createmetatable()
static void createmetatable (lua_State * L) static
Definition at line 847 of file lua-5.1.5/src/lstrlib.c.
{
  lua_createtable(L, 0, 1);  /* create metatable for strings */
  lua_pushliteral(L, "");  /* dummy string */
  lua_pushvalue(L, -2);
  lua_setmetatable(L, -2);  /* set string metatable */
  lua_pop(L, 1);  /* pop dummy string */
  lua_pushvalue(L, -2);  /* string library... */
  lua_setfield(L, -2, "__index");  /* ...is the __index metamethod */
  lua_pop(L, 1);  /* pop metatable */
}
References lua_createtable(), lua_pop, lua_pushliteral, lua_pushvalue(), lua_setfield(), and lua_setmetatable().
Referenced by luaopen_string().
end_capture()
static const char * end_capture (MatchState * ms, const char * s, const char * p) static
Definition at line 343 of file lua-5.1.5/src/lstrlib.c.
{
  int l = capture_to_close(ms);
  const char *res;
  ms->capture[l].len = s - ms->capture[l].init;  /* close capture */
  if ((res = match(ms, s, p)) == NULL)  /* match failed? */
    ms->capture[l].len = CAP_UNFINISHED;  /* undo capture */
  return res;
}
References CAP_UNFINISHED, MatchState::capture, capture_to_close(), MatchState::init, MatchState::len, match(), NULL, and s.
Referenced by match().
gfind_nodef()
static int gfind_nodef (lua_State * L) static
Definition at line 584 of file lua-5.1.5/src/lstrlib.c.
{
  return luaL_error(L, LUA_QL("string.gfind") " was renamed to "
                       LUA_QL("string.gmatch"));
}
References LUA_QL, and luaL_error().
gmatch()
static int gmatch (lua_State * L) static
Definition at line 574 of file lua-5.1.5/src/lstrlib.c.
{
  luaL_checkstring(L, 1);
  luaL_checkstring(L, 2);
  lua_settop(L, 2);
  lua_pushinteger(L, 0);
  lua_pushcclosure(L, gmatch_aux, 3);
  return 1;
}
References gmatch_aux(), lua_pushcclosure(), lua_pushinteger(), lua_settop(), and luaL_checkstring.
gmatch_aux()
static int gmatch_aux (lua_State * L) static
Definition at line 548 of file lua-5.1.5/src/lstrlib.c.
{
  MatchState ms;
  size_t ls;
  const char *s = lua_tolstring(L, lua_upvalueindex(1), &ls);
  const char *p = lua_tostring(L, lua_upvalueindex(2));
  const char *src;
  ms.L = L;
  ms.src_init = s;
  ms.src_end = s+ls;
  for (src = s + (size_t)lua_tointeger(L, lua_upvalueindex(3));
       src <= ms.src_end;
       src++) {
    const char *e;
    ms.level = 0;
    if ((e = match(&ms, src, p)) != NULL) {
      lua_Integer newstart = e-s;
      if (e == src) newstart++;  /* empty match? go at least one position */
      lua_pushinteger(L, newstart);
      lua_replace(L, lua_upvalueindex(3));
      return push_captures(&ms, src, e);
    }
  }
  return 0;  /* not found */
}
References MatchState::L, MatchState::level, lua_pushinteger(), lua_replace, lua_tointeger, lua_tolstring(), lua_tostring, lua_upvalueindex, match(), NULL, push_captures(), s, MatchState::src_end, and MatchState::src_init.
Referenced by gmatch().
lmemfind()
static const char * lmemfind (const char * s1, size_t l1, const char * s2, size_t l2) static
Definition at line 444 of file lua-5.1.5/src/lstrlib.c.
{
  if (l2 == 0) return s1;  /* empty strings are everywhere */
  else if (l2 > l1) return NULL;  /* avoids a negative `l1' */
  else {
    const char *init;  /* to search for a `*s2' inside `s1' */
    l2--;  /* 1st char will be checked by `memchr' */
    l1 = l1-l2;  /* `s2' cannot be found after that */
    while (l1 > 0 && (init = (const char *)memchr(s1, *s2, l1)) != NULL) {
      init++;   /* 1st char is already checked */
      if (memcmp(init, s2+1, l2) == 0)
        return init-1;
      else {  /* correct `l1' and `s1' to try again */
        l1 -= init-s1;
        s1 = init;
      }
    }
    return NULL;  /* not found */
  }
}
References NULL.
Referenced by str_find_aux().
luaopen_string()
LUALIB_API int luaopen_string (lua_State * L)
Definition at line 862 of file lua-5.1.5/src/lstrlib.c.
{
  luaL_register(L, LUA_STRLIBNAME, strlib);
#if defined(LUA_COMPAT_GFIND)
  lua_getfield(L, -1, "gmatch");
  lua_setfield(L, -2, "gfind");
#endif
  createmetatable(L);
  return 1;
}
References createmetatable(), lua_getfield(), lua_setfield(), LUA_STRLIBNAME, luaL_register(), and strlib.
match()
static const char * match (MatchState * ms, const char * s, const char * p) static
Definition at line 365 of file lua-5.1.5/src/lstrlib.c.
{
  init: /* using goto's to optimize tail recursion */
  switch (*p) {
    case '(': {  /* start capture */
      if (*(p+1) == ')')  /* position capture? */
        return start_capture(ms, s, p+2, CAP_POSITION);
      else
        return start_capture(ms, s, p+1, CAP_UNFINISHED);
    }
    case ')': {  /* end capture */
      return end_capture(ms, s, p+1);
    }
    case L_ESC: {
      switch (*(p+1)) {
        case 'b': {  /* balanced string? */
          s = matchbalance(ms, s, p+2);
          if (s == NULL) return NULL;
          p+=4; goto init;  /* else return match(ms, s, p+4); */
        }
        case 'f': {  /* frontier? */
          const char *ep; char previous;
          p += 2;
          if (*p != '[')
            luaL_error(ms->L, "missing " LUA_QL("[") " after "
                               LUA_QL("%%f") " in pattern");
          ep = classend(ms, p);  /* points to what is next */
          previous = (s == ms->src_init) ? '\0' : *(s-1);
          if (matchbracketclass(uchar(previous), p, ep-1) ||
             !matchbracketclass(uchar(*s), p, ep-1)) return NULL;
          p=ep; goto init;  /* else return match(ms, s, ep); */
        }
        default: {
          if (isdigit(uchar(*(p+1)))) {  /* capture results (%0-%9)? */
            s = match_capture(ms, s, uchar(*(p+1)));
            if (s == NULL) return NULL;
            p+=2; goto init;  /* else return match(ms, s, p+2) */
          }
          goto dflt;  /* case default */
        }
      }
    }
    case '\0': {  /* end of pattern */
      return s;  /* match succeeded */
    }
    case '$': {
      if (*(p+1) == '\0')  /* is the `$' the last char in pattern? */
        return (s == ms->src_end) ? s : NULL;  /* check end of string */
      else goto dflt;
    }
    default: dflt: {  /* it is a pattern item */
      const char *ep = classend(ms, p);  /* points to what is next */
      int m = s<ms->src_end && singlematch(uchar(*s), p, ep);
      switch (*ep) {
        case '?': {  /* optional */
          const char *res;
          if (m && ((res=match(ms, s+1, ep+1)) != NULL))
            return res;
          p=ep+1; goto init;  /* else return match(ms, s, ep+1); */
        }
        case '*': {  /* 0 or more repetitions */
          return max_expand(ms, s, p, ep);
        }
        case '+': {  /* 1 or more repetitions */
          return (m ? max_expand(ms, s+1, p, ep) : NULL);
        }
        case '-': {  /* 0 or more repetitions (minimum) */
          return min_expand(ms, s, p, ep);
        }
        default: {
          if (!m) return NULL;
          s++; p=ep; goto init;  /* else return match(ms, s+1, ep); */
        }
      }
    }
  }
}
References CAP_POSITION, CAP_UNFINISHED, classend(), end_capture(), MatchState::L, L_ESC, LUA_QL, luaL_error(), match(), match_capture(), matchbalance(), matchbracketclass(), max_expand(), min_expand(), NULL, s, singlematch(), MatchState::src_end, MatchState::src_init, start_capture(), and uchar.
Referenced by duk__lookup_active_label(), duk__match_regexp(), duk__regexp_match_helper(), end_capture(), gmatch_aux(), match(), matchQuality(), max_expand(), min_expand(), start_capture(), str_find_aux(), and str_gsub().
match_capture()
static const char * match_capture (MatchState * ms, const char * s, int l) static
Definition at line 354 of file lua-5.1.5/src/lstrlib.c.
{
  size_t len;
  l = check_capture(ms, l);
  len = ms->capture[l].len;
  if ((size_t)(ms->src_end-s) >= len &&
      memcmp(ms->capture[l].init, s, len) == 0)
    return s+len;
  else return NULL;
}
References MatchState::capture, check_capture(), MatchState::init, MatchState::len, NULL, s, and MatchState::src_end.
Referenced by match().
match_class()
static int match_class (int c, int cl) static
Definition at line 226 of file lua-5.1.5/src/lstrlib.c.
{
  int res;
  switch (tolower(cl)) {
    case 'a' : res = isalpha(c); break;
    case 'c' : res = iscntrl(c); break;
    case 'd' : res = isdigit(c); break;
    case 'l' : res = islower(c); break;
    case 'p' : res = ispunct(c); break;
    case 's' : res = isspace(c); break;
    case 'u' : res = isupper(c); break;
    case 'w' : res = isalnum(c); break;
    case 'x' : res = isxdigit(c); break;
    case 'z' : res = (c == 0); break;
    default: return (cl == c);
  }
  return (islower(cl) ? res : !res);
}
Referenced by matchbracketclass(), and singlematch().
matchbalance()
static const char * matchbalance (MatchState * ms, const char * s, const char * p) static
Definition at line 281 of file lua-5.1.5/src/lstrlib.c.
{
  if (*p == 0 || *(p+1) == 0)
    luaL_error(ms->L, "unbalanced pattern");
  if (*s != *p) return NULL;
  else {
    int b = *p;
    int e = *(p+1);
    int cont = 1;
    while (++s < ms->src_end) {
      if (*s == e) {
        if (--cont == 0) return s+1;
      }
      else if (*s == b) cont++;
    }
  }
  return NULL;  /* string ends out of balance */
}
References MatchState::L, luaL_error(), NULL, and s.
Referenced by match().
matchbracketclass()
static int matchbracketclass (int c, const char * p, const char * ec) static
Definition at line 245 of file lua-5.1.5/src/lstrlib.c.
{
  int sig = 1;
  if (*(p+1) == '^') {
    sig = 0;
    p++;  /* skip the `^' */
  }
  while (++p < ec) {
    if (*p == L_ESC) {
      p++;
      if (match_class(c, uchar(*p)))
        return sig;
    }
    else if ((*(p+1) == '-') && (p+2 < ec)) {
      p+=2;
      if (uchar(*(p-2)) <= c && c <= uchar(*p))
        return sig;
    }
    else if (uchar(*p) == c) return sig;
  }
  return !sig;
}
References L_ESC, match_class(), and uchar.
Referenced by match(), and singlematch().
max_expand()
static const char * max_expand (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 301 of file lua-5.1.5/src/lstrlib.c.
{
  ptrdiff_t i = 0;  /* counts maximum expand for item */
  while ((s+i)<ms->src_end && singlematch(uchar(*(s+i)), p, ep))
    i++;
  /* keeps trying to match with the maximum repetitions */
  while (i>=0) {
    const char *res = match(ms, (s+i), ep+1);
    if (res) return res;
    i--;  /* else didn't match; reduce 1 repetition to try again */
  }
  return NULL;
}
References match(), NULL, s, singlematch(), MatchState::src_end, and uchar.
Referenced by match().
min_expand()
static const char * min_expand (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 316 of file lua-5.1.5/src/lstrlib.c.
{
  for (;;) {
    const char *res = match(ms, s, ep+1);
    if (res != NULL)
      return res;
    else if (s<ms->src_end && singlematch(uchar(*s), p, ep))
      s++;  /* try with one more repetition */
    else return NULL;
  }
}
References match(), NULL, s, singlematch(), and uchar.
Referenced by match().
posrelat()
static ptrdiff_t posrelat (ptrdiff_t pos, size_t len) static
Definition at line 36 of file lua-5.1.5/src/lstrlib.c.
{
  /* relative string position: negative means back from end */
  if (pos < 0) pos += (ptrdiff_t)len + 1;
  return (pos >= 0) ? pos : 0;
}
Referenced by str_byte(), str_find_aux(), and str_sub().
push_captures()
static int push_captures (MatchState * ms, const char * s, const char * e) static
Definition at line 485 of file lua-5.1.5/src/lstrlib.c.
{
  int i;
  int nlevels = (ms->level == 0 && s) ? 1 : ms->level;
  luaL_checkstack(ms->L, nlevels, "too many captures");
  for (i = 0; i < nlevels; i++)
    push_onecapture(ms, i, s, e);
  return nlevels;  /* number of strings pushed */
}
References MatchState::L, MatchState::level, luaL_checkstack(), push_onecapture(), and s.
Referenced by add_value(), gmatch_aux(), and str_find_aux().
push_onecapture()
static void push_onecapture (MatchState * ms, int i, const char * s, const char * e) static
Definition at line 466 of file lua-5.1.5/src/lstrlib.c.
{
  if (i >= ms->level) {
    if (i == 0)  /* ms->level == 0, too */
      lua_pushlstring(ms->L, s, e - s);  /* add whole match */
    else
      luaL_error(ms->L, "invalid capture index");
  }
  else {
    ptrdiff_t l = ms->capture[i].len;
    if (l == CAP_UNFINISHED) luaL_error(ms->L, "unfinished capture");
    if (l == CAP_POSITION)
      lua_pushinteger(ms->L, ms->capture[i].init - ms->src_init + 1);
    else
      lua_pushlstring(ms->L, ms->capture[i].init, l);
  }
}
References CAP_POSITION, CAP_UNFINISHED, MatchState::capture, MatchState::init, MatchState::L, MatchState::len, MatchState::level, lua_pushinteger(), lua_pushlstring(), luaL_error(), s, and MatchState::src_init.
Referenced by add_s(), add_value(), and push_captures().
scanformat()
static const char * scanformat (lua_State * L, const char * strfrmt, char * form) static
Definition at line 725 of file lua-5.1.5/src/lstrlib.c.
{
  const char *p = strfrmt;
  while (*p != '\0' && strchr(FLAGS, *p) != NULL) p++;  /* skip flags */
  if ((size_t)(p - strfrmt) >= sizeof(FLAGS))
    luaL_error(L, "invalid format (repeated flags)");
  if (isdigit(uchar(*p))) p++;  /* skip width */
  if (isdigit(uchar(*p))) p++;  /* (2 digits at most) */
  if (*p == '.') {
    p++;
    if (isdigit(uchar(*p))) p++;  /* skip precision */
    if (isdigit(uchar(*p))) p++;  /* (2 digits at most) */
  }
  if (isdigit(uchar(*p)))
    luaL_error(L, "invalid format (width or precision too long)");
  *(form++) = '%';
  strncpy(form, strfrmt, p - strfrmt + 1);
  form += p - strfrmt + 1;
  *form = '\0';
  return p;
}
References FLAGS, luaL_error(), NULL, and uchar.
Referenced by str_format().
singlematch()
static int singlematch (int c, const char * p, const char * ep) static
Definition at line 268 of file lua-5.1.5/src/lstrlib.c.
{
  switch (*p) {
    case '.': return 1;  /* matches any char */
    case L_ESC: return match_class(c, uchar(*(p+1)));
    case '[': return matchbracketclass(c, p, ep-1);
    default:  return (uchar(*p) == c);
  }
}
References L_ESC, match_class(), matchbracketclass(), and uchar.
Referenced by match(), max_expand(), and min_expand().
start_capture()
static const char * start_capture (MatchState * ms, const char * s, const char * p, int what) static
Definition at line 329 of file lua-5.1.5/src/lstrlib.c.
{
  const char *res;
  int level = ms->level;
  if (level >= LUA_MAXCAPTURES) luaL_error(ms->L, "too many captures");
  ms->capture[level].init = s;
  ms->capture[level].len = what;
  ms->level = level+1;
  if ((res=match(ms, s, p)) == NULL)  /* match failed? */
    ms->level--;  /* undo capture */
  return res;
}
References MatchState::capture, MatchState::init, MatchState::L, MatchState::len, MatchState::level, LUA_MAXCAPTURES, luaL_error(), match(), NULL, and s.
Referenced by match().
str_byte()
static int str_byte (lua_State * L) static
Definition at line 106 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l;
  const char *s = luaL_checklstring(L, 1, &l);
  ptrdiff_t posi = posrelat(luaL_optinteger(L, 2, 1), l);
  ptrdiff_t pose = posrelat(luaL_optinteger(L, 3, posi), l);
  int n, i;
  if (posi <= 0) posi = 1;
  if ((size_t)pose > l) pose = l;
  if (posi > pose) return 0;  /* empty interval; return no values */
  n = (int)(pose -  posi + 1);
  if (posi + n <= pose)  /* overflow? */
    luaL_error(L, "string slice too long");
  luaL_checkstack(L, n, "string slice too long");
  for (i=0; i<n; i++)
    lua_pushinteger(L, uchar(s[posi+i-1]));
  return n;
}
References lua_pushinteger(), luaL_checklstring(), luaL_checkstack(), luaL_error(), luaL_optinteger(), posrelat(), s, and uchar.
str_char()
static int str_char (lua_State * L) static
Definition at line 125 of file lua-5.1.5/src/lstrlib.c.
{
  int n = lua_gettop(L);  /* number of arguments */
  int i;
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  for (i=1; i<=n; i++) {
    int c = luaL_checkint(L, i);
    luaL_argcheck(L, uchar(c) == c, i, "invalid value");
    luaL_addchar(&b, uchar(c));
  }
  luaL_pushresult(&b);
  return 1;
}
References lua_gettop(), luaL_addchar, luaL_argcheck, luaL_buffinit(), luaL_checkint, luaL_pushresult(), and uchar.
str_dump()
static int str_dump (lua_State * L) static
Definition at line 147 of file lua-5.1.5/src/lstrlib.c.
{
  luaL_Buffer b;
  luaL_checktype(L, 1, LUA_TFUNCTION);
  lua_settop(L, 1);
  luaL_buffinit(L,&b);
  if (lua_dump(L, writer, &b) != 0)
    luaL_error(L, "unable to dump given function");
  luaL_pushresult(&b);
  return 1;
}
References lua_dump(), lua_settop(), LUA_TFUNCTION, luaL_buffinit(), luaL_checktype(), luaL_error(), luaL_pushresult(), and writer().
str_find()
static int str_find (lua_State * L) static
Definition at line 538 of file lua-5.1.5/src/lstrlib.c.
{
  return str_find_aux(L, 1);
}
References str_find_aux().
str_find_aux()
static int str_find_aux (lua_State * L, int find) static
Definition at line 495 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l1, l2;
  const char *s = luaL_checklstring(L, 1, &l1);
  const char *p = luaL_checklstring(L, 2, &l2);
  ptrdiff_t init = posrelat(luaL_optinteger(L, 3, 1), l1) - 1;
  if (init < 0) init = 0;
  else if ((size_t)(init) > l1) init = (ptrdiff_t)l1;
  if (find && (lua_toboolean(L, 4) ||  /* explicit request? */
      strpbrk(p, SPECIALS) == NULL)) {  /* or no special characters? */
    /* do a plain search */
    const char *s2 = lmemfind(s+init, l1-init, p, l2);
    if (s2) {
      lua_pushinteger(L, s2-s+1);
      lua_pushinteger(L, s2-s+l2);
      return 2;
    }
  }
  else {
    MatchState ms;
    int anchor = (*p == '^') ? (p++, 1) : 0;
    const char *s1=s+init;
    ms.L = L;
    ms.src_init = s;
    ms.src_end = s+l1;
    do {
      const char *res;
      ms.level = 0;
      if ((res=match(&ms, s1, p)) != NULL) {
        if (find) {
          lua_pushinteger(L, s1-s+1);  /* start */
          lua_pushinteger(L, res-s);   /* end */
          return push_captures(&ms, NULL, 0) + 2;
        }
        else
          return push_captures(&ms, s1, res);
      }
    } while (s1++ < ms.src_end && !anchor);
  }
  lua_pushnil(L);  /* not found */
  return 1;
}
References find(), MatchState::L, MatchState::level, lmemfind(), lua_pushinteger(), lua_pushnil(), lua_toboolean(), luaL_checklstring(), luaL_optinteger(), match(), NULL, posrelat(), push_captures(), s, SPECIALS, MatchState::src_end, and MatchState::src_init.
Referenced by str_find(), and str_match().
str_format()
static int str_format (lua_State * L) static
Definition at line 756 of file lua-5.1.5/src/lstrlib.c.
{
  int top = lua_gettop(L);
  int arg = 1;
  size_t sfl;
  const char *strfrmt = luaL_checklstring(L, arg, &sfl);
  const char *strfrmt_end = strfrmt+sfl;
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  while (strfrmt < strfrmt_end) {
    if (*strfrmt != L_ESC)
      luaL_addchar(&b, *strfrmt++);
    else if (*++strfrmt == L_ESC)
      luaL_addchar(&b, *strfrmt++);  /* %% */
    else { /* format item */
      char form[MAX_FORMAT];  /* to store the format (`%...') */
      char buff[MAX_ITEM];  /* to store the formatted item */
      if (++arg > top)
        luaL_argerror(L, arg, "no value");
      strfrmt = scanformat(L, strfrmt, form);
      switch (*strfrmt++) {
        case 'c': {
          sprintf(buff, form, (int)luaL_checknumber(L, arg));
          break;
        }
        case 'd':  case 'i': {
          addintlen(form);
          sprintf(buff, form, (LUA_INTFRM_T)luaL_checknumber(L, arg));
          break;
        }
        case 'o':  case 'u':  case 'x':  case 'X': {
          addintlen(form);
          sprintf(buff, form, (unsigned LUA_INTFRM_T)luaL_checknumber(L, arg));
          break;
        }
        case 'e':  case 'E': case 'f':
        case 'g': case 'G': {
          sprintf(buff, form, (double)luaL_checknumber(L, arg));
          break;
        }
        case 'q': {
          addquoted(L, &b, arg);
          continue;  /* skip the 'addsize' at the end */
        }
        case 's': {
          size_t l;
          const char *s = luaL_checklstring(L, arg, &l);
          if (!strchr(form, '.') && l >= 100) {
            /* no precision and string is too long to be formatted;
               keep original string */
            lua_pushvalue(L, arg);
            luaL_addvalue(&b);
            continue;  /* skip the `addsize' at the end */
          }
          else {
            sprintf(buff, form, s);
            break;
          }
        }
        default: {  /* also treat cases `pnLlh' */
          return luaL_error(L, "invalid option " LUA_QL("%%%c") " to "
                               LUA_QL("format"), *(strfrmt - 1));
        }
      }
      luaL_addlstring(&b, buff, strlen(buff));
    }
  }
  luaL_pushresult(&b);
  return 1;
}
References addintlen(), addquoted(), arg, L_ESC, lua_gettop(), LUA_INTFRM_T, lua_pushvalue(), LUA_QL, luaL_addchar, luaL_addlstring(), luaL_addvalue(), luaL_argerror(), luaL_buffinit(), luaL_checklstring(), luaL_checknumber(), luaL_error(), luaL_pushresult(), MAX_FORMAT, MAX_ITEM, s, and scanformat().
str_gsub()
static int str_gsub (lua_State * L) static
Definition at line 644 of file lua-5.1.5/src/lstrlib.c.
{
  size_t srcl;
  const char *src = luaL_checklstring(L, 1, &srcl);
  const char *p = luaL_checkstring(L, 2);
  int  tr = lua_type(L, 3);
  int max_s = luaL_optint(L, 4, srcl+1);
  int anchor = (*p == '^') ? (p++, 1) : 0;
  int n = 0;
  MatchState ms;
  luaL_Buffer b;
  luaL_argcheck(L, tr == LUA_TNUMBER || tr == LUA_TSTRING ||
                   tr == LUA_TFUNCTION || tr == LUA_TTABLE, 3,
                      "string/function/table expected");
  luaL_buffinit(L, &b);
  ms.L = L;
  ms.src_init = src;
  ms.src_end = src+srcl;
  while (n < max_s) {
    const char *e;
    ms.level = 0;
    e = match(&ms, src, p);
    if (e) {
      n++;
      add_value(&ms, &b, src, e);
    }
    if (e && e>src) /* non empty match? */
      src = e;  /* skip it */
    else if (src < ms.src_end)
      luaL_addchar(&b, *src++);
    else break;
    if (anchor) break;
  }
  luaL_addlstring(&b, src, ms.src_end-src);
  luaL_pushresult(&b);
  lua_pushinteger(L, n);  /* number of substitutions */
  return 2;
}
References add_value(), MatchState::L, MatchState::level, lua_pushinteger(), LUA_TFUNCTION, LUA_TNUMBER, LUA_TSTRING, LUA_TTABLE, lua_type(), luaL_addchar, luaL_addlstring(), luaL_argcheck, luaL_buffinit(), luaL_checklstring(), luaL_checkstring, luaL_optint, luaL_pushresult(), match(), MatchState::src_end, and MatchState::src_init.
str_len()
static int str_len (lua_State * L) static
Definition at line 28 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l;
  luaL_checklstring(L, 1, &l);
  lua_pushinteger(L, l);
  return 1;
}
References lua_pushinteger(), and luaL_checklstring().
Referenced by duk_bi_nodejs_buffer_write().
str_lower()
static int str_lower (lua_State * L) static
Definition at line 68 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l;
  size_t i;
  luaL_Buffer b;
  const char *s = luaL_checklstring(L, 1, &l);
  luaL_buffinit(L, &b);
  for (i=0; i<l; i++)
    luaL_addchar(&b, tolower(uchar(s[i])));
  luaL_pushresult(&b);
  return 1;
}
References luaL_addchar, luaL_buffinit(), luaL_checklstring(), luaL_pushresult(), s, and uchar.
str_match()
static int str_match (lua_State * L) static
Definition at line 543 of file lua-5.1.5/src/lstrlib.c.
{
  return str_find_aux(L, 0);
}
References str_find_aux().
str_rep()
static int str_rep (lua_State * L) static
Definition at line 93 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l;
  luaL_Buffer b;
  const char *s = luaL_checklstring(L, 1, &l);
  int n = luaL_checkint(L, 2);
  luaL_buffinit(L, &b);
  while (n-- > 0)
    luaL_addlstring(&b, s, l);
  luaL_pushresult(&b);
  return 1;
}
References luaL_addlstring(), luaL_buffinit(), luaL_checkint, luaL_checklstring(), luaL_pushresult(), and s.
str_reverse()
static int str_reverse (lua_State * L) static
Definition at line 57 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l;
  luaL_Buffer b;
  const char *s = luaL_checklstring(L, 1, &l);
  luaL_buffinit(L, &b);
  while (l--) luaL_addchar(&b, s[l]);
  luaL_pushresult(&b);
  return 1;
}
References luaL_addchar, luaL_buffinit(), luaL_checklstring(), luaL_pushresult(), and s.
str_sub()
static int str_sub (lua_State * L) static
Definition at line 43 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l;
  const char *s = luaL_checklstring(L, 1, &l);
  ptrdiff_t start = posrelat(luaL_checkinteger(L, 2), l);
  ptrdiff_t end = posrelat(luaL_optinteger(L, 3, -1), l);
  if (start < 1) start = 1;
  if (end > (ptrdiff_t)l) end = (ptrdiff_t)l;
  if (start <= end)
    lua_pushlstring(L, s+start-1, end-start+1);
  else lua_pushliteral(L, "");
  return 1;
}
References lua_pushliteral, lua_pushlstring(), luaL_checkinteger(), luaL_checklstring(), luaL_optinteger(), posrelat(), and s.
str_upper()
static int str_upper (lua_State * L) static
Definition at line 81 of file lua-5.1.5/src/lstrlib.c.
{
  size_t l;
  size_t i;
  luaL_Buffer b;
  const char *s = luaL_checklstring(L, 1, &l);
  luaL_buffinit(L, &b);
  for (i=0; i<l; i++)
    luaL_addchar(&b, toupper(uchar(s[i])));
  luaL_pushresult(&b);
  return 1;
}
References luaL_addchar, luaL_buffinit(), luaL_checklstring(), luaL_pushresult(), s, and uchar.
writer()
static int writer (lua_State * L, const void * b, size_t size, void * B) static
Definition at line 140 of file lua-5.1.5/src/lstrlib.c.
{
  (void)L;
  luaL_addlstring((luaL_Buffer*) B, (const char *)b, size);
  return 0;
}
References luaL_addlstring().
Referenced by lua_dump(), lua_dump(), str_dump(), vdbeIncrPopulate(), and vdbeSorterListToPMA().
Variable Documentation
strlib
const luaL_Reg strlib[] static
Initial value:
= {
  {"byte", str_byte},
  {"char", str_char},
  {"dump", str_dump},
  {"find", str_find},
  {"format", str_format},
  {"gfind", gfind_nodef},
  {"gmatch", gmatch},
  {"gsub", str_gsub},
  {"len", str_len},
  {"lower", str_lower},
  {"match", str_match},
  {"rep", str_rep},
  {"reverse", str_reverse},
  {"sub", str_sub},
  {"upper", str_upper},
  {NULL, NULL}
}
Definition at line 827 of file lua-5.1.5/src/lstrlib.c.
{
  {"byte", str_byte},
  {"char", str_char},
  {"dump", str_dump},
  {"find", str_find},
  {"format", str_format},
  {"gfind", gfind_nodef},
  {"gmatch", gmatch},
  {"gsub", str_gsub},
  {"len", str_len},
  {"lower", str_lower},
  {"match", str_match},
  {"rep", str_rep},
  {"reverse", str_reverse},
  {"sub", str_sub},
  {"upper", str_upper},
  {NULL, NULL}
};
Referenced by luaopen_string().