Github User Fetcher: lundump.h File Reference
lundump.h File Reference
#include "lobject.h"
#include "lzio.h"
Macros
#define LUAC_TAIL "\x19\x93\r\n\x1a\n"
#define LUAC_HEADERSIZE (sizeof(LUA_SIGNATURE)-sizeof(char)+2+6+sizeof(LUAC_TAIL)-sizeof(char))
Functions
LUAI_FUNC Closure * luaU_undump (lua_State *L, ZIO *Z, Mbuffer *buff, const char *name)
LUAI_FUNC void luaU_header (lu_byte *h)
LUAI_FUNC int luaU_dump (lua_State *L, const Proto *f, lua_Writer w, void *data, int strip)
Macro Definition Documentation
LUAC_HEADERSIZE
#define LUAC_HEADERSIZE (sizeof(LUA_SIGNATURE)-sizeof(char)+2+6+sizeof(LUAC_TAIL)-sizeof(char))
Definition at line 26 of file lua-5.2.4/src/lundump.h.
LUAC_TAIL
#define LUAC_TAIL "\x19\x93\r\n\x1a\n"
Definition at line 23 of file lua-5.2.4/src/lundump.h.
Referenced by luaU_header().
Function Documentation
luaU_dump()
LUAI_FUNC int luaU_dump (lua_State * L, const Proto * f, lua_Writer w, void * data, int strip)
Definition at line 153 of file lua-5.1.5/src/ldump.c.
{
 DumpState D;
 D.L=L;
 D.writer=w;
 D.data=data;
 D.strip=strip;
 D.status=0;
 DumpHeader(&D);
 DumpFunction(f,NULL,&D);
 return D.status;
}
luaU_header()
LUAI_FUNC void luaU_header (lu_byte * h)
Definition at line 244 of file lua-5.2.4/src/lundump.c.
{
 int x=1;
 memcpy(h,LUA_SIGNATURE,sizeof(LUA_SIGNATURE)-sizeof(char));
 h+=sizeof(LUA_SIGNATURE)-sizeof(char);
 *h++=cast_byte(VERSION);
 *h++=cast_byte(FORMAT);
 *h++=cast_byte(*(char*)&x);            /* endianness */
 *h++=cast_byte(sizeof(int));
 *h++=cast_byte(sizeof(size_t));
 *h++=cast_byte(sizeof(Instruction));
 *h++=cast_byte(sizeof(lua_Number));
 *h++=cast_byte(((lua_Number)0.5)==0);      /* is lua_Number integral? */
 memcpy(h,LUAC_TAIL,sizeof(LUAC_TAIL)-sizeof(char));
}
References cast_byte, FORMAT, LUA_SIGNATURE, LUAC_TAIL, and VERSION.
Referenced by LoadHeader().
luaU_undump()
LUAI_FUNC Closure * luaU_undump (lua_State * L, ZIO * Z, Mbuffer * buff, const char * name)
Definition at line 195 of file lua-5.1.5/src/lundump.c.
{
 LoadState S;
 if (*name=='@' || *name=='=')
  S.name=name+1;
 else if (*name==LUA_SIGNATURE[0])
  S.name="binary string";
 else
  S.name=name;
 S.L=L;
 S.Z=Z;
 S.b=buff;
 LoadHeader(&S);
 return LoadFunction(&S,luaS_newliteral(L,"=?"));
}
References incr_top, Closure::l, LoadFunction(), LoadFunction(), LoadHeader(), LoadHeader(), LUA_SIGNATURE, luaF_newLclosure(), luaF_newproto(), luai_verifycode, luaS_newliteral, name, LoadState::name, LClosure::p, S, setclLvalue, Proto::sizeupvalues, and lua_State::top.
Referenced by f_parser(), f_parser(), f_parser(), and f_parser().