Github User Fetcher: lfunc.c File Reference
lfunc.c File Reference
#include <stddef.h>
#include "lua.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
Macros
#define lfunc_c
#define LUA_CORE
Functions
Closure * luaF_newCclosure (lua_State *L, int n)
Closure * luaF_newLclosure (lua_State *L, int n)
UpVal * luaF_newupval (lua_State *L)
UpVal * luaF_findupval (lua_State *L, StkId level)
static void unlinkupval (UpVal *uv)
void luaF_freeupval (lua_State *L, UpVal *uv)
void luaF_close (lua_State *L, StkId level)
Proto * luaF_newproto (lua_State *L)
void luaF_freeproto (lua_State *L, Proto *f)
const char * luaF_getlocalname (const Proto *f, int local_number, int pc)
Macro Definition Documentation
lfunc_c
#define lfunc_c
Definition at line 10 of file lua-5.2.4/src/lfunc.c.
LUA_CORE
#define LUA_CORE
Definition at line 11 of file lua-5.2.4/src/lfunc.c.
Function Documentation
luaF_close()
void luaF_close (lua_State * L, StkId level)
Definition at line 89 of file lua-5.2.4/src/lfunc.c.
{
  UpVal *uv;
  global_State *g = G(L);
  while (L->openupval != NULL && (uv = gco2uv(L->openupval))->v >= level) {
    GCObject *o = obj2gco(uv);
    lua_assert(!isblack(o) && uv->v != &uv->u.value);
    L->openupval = uv->next;  /* remove from `open' list */
    if (isdead(g, o))
      luaF_freeupval(L, uv);  /* free upvalue */
    else {
      unlinkupval(uv);  /* remove upvalue from 'uvhead' list */
      setobj(L, &uv->u.value, uv->v);  /* move value to upvalue slot */
      uv->v = &uv->u.value;  /* now current value lives here */
      gch(o)->next = g->allgc;  /* link upvalue into 'allgc' list */
      g->allgc = o;
      luaC_checkupvalcolor(g, uv);
    }
  }
}
References global_State::allgc, G, gch, gco2uv, isblack, isdead, lua_assert, luaC_checkupvalcolor(), luaF_freeupval(), UpVal::next, NULL, obj2gco, lua_State::openupval, setobj, UpVal::u, unlinkupval(), UpVal::v, and UpVal::value.
luaF_findupval()
UpVal * luaF_findupval (lua_State * L, StkId level)
Definition at line 47 of file lua-5.2.4/src/lfunc.c.
{
  global_State *g = G(L);
  GCObject **pp = &L->openupval;
  UpVal *p;
  UpVal *uv;
  while (*pp != NULL && (p = gco2uv(*pp))->v >= level) {
    GCObject *o = obj2gco(p);
    lua_assert(p->v != &p->u.value);
    lua_assert(!isold(o) || isold(obj2gco(L)));
    if (p->v == level) {  /* found a corresponding upvalue? */
      if (isdead(g, o))  /* is it dead? */
        changewhite(o);  /* resurrect it */
      return p;
    }
    pp = &p->next;
  }
  /* not found: create a new one */
  uv = &luaC_newobj(L, LUA_TUPVAL, sizeof(UpVal), pp, 0)->uv;
  uv->v = level;  /* current value lives in the stack */
  uv->u.l.prev = &g->uvhead;  /* double link it in `uvhead' list */
  uv->u.l.next = g->uvhead.u.l.next;
  uv->u.l.next->u.l.prev = uv;
  g->uvhead.u.l.next = uv;
  lua_assert(uv->u.l.next->u.l.prev == uv && uv->u.l.prev->u.l.next == uv);
  return uv;
}
References changewhite, G, gco2uv, isdead, isold, UpVal::l, lua_assert, LUA_TUPVAL, luaC_newobj(), UpVal::next, NULL, obj2gco, lua_State::openupval, UpVal::prev, UpVal::u, GCObject::uv, global_State::uvhead, UpVal::v, and UpVal::value.
luaF_freeproto()
void luaF_freeproto (lua_State * L, Proto * f)
Definition at line 135 of file lua-5.2.4/src/lfunc.c.
{
  luaM_freearray(L, f->code, f->sizecode);
  luaM_freearray(L, f->p, f->sizep);
  luaM_freearray(L, f->k, f->sizek);
  luaM_freearray(L, f->lineinfo, f->sizelineinfo);
  luaM_freearray(L, f->locvars, f->sizelocvars);
  luaM_freearray(L, f->upvalues, f->sizeupvalues);
  luaM_free(L, f);
}
References Proto::code, Proto::k, Proto::lineinfo, Proto::locvars, luaM_free, luaM_freearray, Proto::p, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, and Proto::upvalues.
luaF_freeupval()
void luaF_freeupval (lua_State * L, UpVal * uv)
Definition at line 82 of file lua-5.2.4/src/lfunc.c.
{
  if (uv->v != &uv->u.value)  /* is it open? */
    unlinkupval(uv);  /* remove from open list */
  luaM_free(L, uv);  /* free upvalue */
}
References luaM_free, UpVal::u, unlinkupval(), UpVal::v, and UpVal::value.
Referenced by luaF_close().
luaF_getlocalname()
const char * luaF_getlocalname (const Proto * f, int local_number, int pc)
Definition at line 150 of file lua-5.2.4/src/lfunc.c.
{
  int i;
  for (i = 0; i<f->sizelocvars && f->locvars[i].startpc <= pc; i++) {
    if (pc < f->locvars[i].endpc) {  /* is variable active? */
      local_number--;
      if (local_number == 0)
        return getstr(f->locvars[i].varname);
    }
  }
  return NULL;  /* not found */
}
References getstr, Proto::locvars, NULL, Proto::sizelocvars, LocVar::startpc, and LocVar::varname.
luaF_newCclosure()
Closure * luaF_newCclosure (lua_State * L, int n)
Definition at line 23 of file lua-5.2.4/src/lfunc.c.
{
  Closure *c = &luaC_newobj(L, LUA_TCCL, sizeCclosure(n), NULL, 0)->cl;
  c->c.nupvalues = cast_byte(n);
  return c;
}
References Closure::c, cast_byte, GCObject::cl, LUA_TCCL, luaC_newobj(), NULL, and sizeCclosure.
luaF_newLclosure()
Closure * luaF_newLclosure (lua_State * L, int n)
Definition at line 30 of file lua-5.2.4/src/lfunc.c.
{
  Closure *c = &luaC_newobj(L, LUA_TLCL, sizeLclosure(n), NULL, 0)->cl;
  c->l.p = NULL;
  c->l.nupvalues = cast_byte(n);
  while (n--) c->l.upvals[n] = NULL;
  return c;
}
References cast_byte, GCObject::cl, Closure::l, LUA_TLCL, luaC_newobj(), NULL, LClosure::p, sizeLclosure, and LClosure::upvals.
luaF_newproto()
Proto * luaF_newproto (lua_State * L)
Definition at line 110 of file lua-5.2.4/src/lfunc.c.
{
  Proto *f = &luaC_newobj(L, LUA_TPROTO, sizeof(Proto), NULL, 0)->p;
  f->k = NULL;
  f->sizek = 0;
  f->p = NULL;
  f->sizep = 0;
  f->code = NULL;
  f->cache = NULL;
  f->sizecode = 0;
  f->lineinfo = NULL;
  f->sizelineinfo = 0;
  f->upvalues = NULL;
  f->sizeupvalues = 0;
  f->numparams = 0;
  f->is_vararg = 0;
  f->maxstacksize = 0;
  f->locvars = NULL;
  f->sizelocvars = 0;
  f->linedefined = 0;
  f->lastlinedefined = 0;
  f->source = NULL;
  return f;
}
References Proto::cache, Proto::code, Proto::is_vararg, Proto::k, Proto::lastlinedefined, Proto::linedefined, Proto::lineinfo, Proto::locvars, LUA_TPROTO, luaC_newobj(), Proto::maxstacksize, NULL, Proto::numparams, Proto::p, GCObject::p, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, and Proto::upvalues.
luaF_newupval()
UpVal * luaF_newupval (lua_State * L)
Definition at line 39 of file lua-5.2.4/src/lfunc.c.
{
  UpVal *uv = &luaC_newobj(L, LUA_TUPVAL, sizeof(UpVal), NULL, 0)->uv;
  uv->v = &uv->u.value;
  setnilvalue(uv->v);
  return uv;
}
References LUA_TUPVAL, luaC_newobj(), NULL, setnilvalue, UpVal::u, GCObject::uv, UpVal::v, and UpVal::value.
unlinkupval()
static void unlinkupval (UpVal * uv) static
Definition at line 75 of file lua-5.2.4/src/lfunc.c.
{
  lua_assert(uv->u.l.next->u.l.prev == uv && uv->u.l.prev->u.l.next == uv);
  uv->u.l.next->u.l.prev = uv->u.l.prev;  /* remove from `uvhead' list */
  uv->u.l.prev->u.l.next = uv->u.l.next;
}
References UpVal::l, lua_assert, UpVal::next, UpVal::prev, and UpVal::u.
Referenced by luaF_close(), and luaF_freeupval().