Github User Fetcher: lmem.c File Reference
lmem.c File Reference
#include <stddef.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
Macros
#define lmem_c
#define LUA_CORE
#define MINSIZEARRAY 4
Functions
void * luaM_growaux_ (lua_State *L, void *block, int *size, size_t size_elems, int limit, const char *what)
l_noret luaM_toobig (lua_State *L)
void * luaM_realloc_ (lua_State *L, void *block, size_t osize, size_t nsize)
Macro Definition Documentation
lmem_c
#define lmem_c
Definition at line 10 of file lua-5.2.4/src/lmem.c.
LUA_CORE
#define LUA_CORE
Definition at line 11 of file lua-5.2.4/src/lmem.c.
MINSIZEARRAY
#define MINSIZEARRAY 4
Definition at line 43 of file lua-5.2.4/src/lmem.c.
Referenced by luaM_growaux_().
Function Documentation
luaM_growaux_()
void * luaM_growaux_ (lua_State * L, void * block, int * size, size_t size_elems, int limit, const char * what)
Definition at line 46 of file lua-5.2.4/src/lmem.c.
{
  void *newblock;
  int newsize;
  if (*size >= limit/2) {  /* cannot double it? */
    if (*size >= limit)  /* cannot grow even a little? */
      luaG_runerror(L, "too many %s (limit is %d)", what, limit);
    newsize = limit;  /* still have at least one free place */
  }
  else {
    newsize = (*size)*2;
    if (newsize < MINSIZEARRAY)
      newsize = MINSIZEARRAY;  /* minimum size */
  }
  newblock = luaM_reallocv(L, block, *size, newsize, size_elems);
  *size = newsize;  /* update only when everything else is OK */
  return newblock;
}
References block(), luaG_runerror(), luaM_reallocv, and MINSIZEARRAY.
luaM_realloc_()
void * luaM_realloc_ (lua_State * L, void * block, size_t osize, size_t nsize)
Definition at line 75 of file lua-5.2.4/src/lmem.c.
{
  void *newblock;
  global_State *g = G(L);
  size_t realosize = (block) ? osize : 0;
  lua_assert((realosize == 0) == (block == NULL));
#if defined(HARDMEMTESTS)
  if (nsize > realosize && g->gcrunning)
    luaC_fullgc(L, 1);  /* force a GC whenever possible */
#endif
  newblock = (*g->frealloc)(g->ud, block, osize, nsize);
  if (newblock == NULL && nsize > 0) {
    api_check(L, nsize > realosize,
                 "realloc cannot fail when shrinking a block");
    if (g->gcrunning) {
      luaC_fullgc(L, 1);  /* try to free some memory... */
      newblock = (*g->frealloc)(g->ud, block, osize, nsize);  /* try again */
    }
    if (newblock == NULL)
      luaD_throw(L, LUA_ERRMEM);
  }
  lua_assert((nsize == 0) == (newblock == NULL));
  g->GCdebt = (g->GCdebt + nsize) - realosize;
  return newblock;
}
References api_check, block(), global_State::frealloc, G, global_State::GCdebt, global_State::gcrunning, lua_assert, LUA_ERRMEM, luaC_fullgc(), luaD_throw(), NULL, and global_State::ud.
luaM_toobig()
l_noret luaM_toobig (lua_State * L)
Definition at line 66 of file lua-5.2.4/src/lmem.c.
{
  luaG_runerror(L, "memory allocation error: block too big");
}
References luaG_runerror().