Github User Fetcher: loadlib.c File Reference
loadlib.c File Reference
#include "lprefix.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define loadlib_c
#define LUA_LIB
#define LUA_IGMARK "-"
#define LUA_CSUBSEP LUA_DIRSEP
#define LUA_LSUBSEP LUA_DIRSEP
#define LUA_POF "luaopen_"
#define LUA_OFSEP "_"
#define LIB_FAIL "open"
#define setprogdir(L) ((void)0)
#define LIB_FAIL "absent"
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
#define LUA_PATH_VAR "LUA_PATH"
#define LUA_CPATH_VAR "LUA_CPATH"
#define ERRLIB 1
#define ERRFUNC 2
Typedefs
typedef void(* voidf) (void)
Functions
static void lsys_unloadlib (void *lib)
static void * lsys_load (lua_State *L, const char *path, int seeglb)
static lua_CFunction lsys_sym (lua_State *L, void *lib, const char *sym)
static int noenv (lua_State *L)
static void setpath (lua_State *L, const char *fieldname, const char *envname, const char *dft)
static void * checkclib (lua_State *L, const char *path)
static void addtoclib (lua_State *L, const char *path, void *plib)
static int gctm (lua_State *L)
static int lookforfunc (lua_State *L, const char *path, const char *sym)
static int ll_loadlib (lua_State *L)
static int readable (const char *filename)
static const char * getnextfilename (char **path, char *end)
static void pusherrornotfound (lua_State *L, const char *path)
static const char * searchpath (lua_State *L, const char *name, const char *path, const char *sep, const char *dirsep)
static int ll_searchpath (lua_State *L)
static const char * findfile (lua_State *L, const char *name, const char *pname, const char *dirsep)
static int checkload (lua_State *L, int stat, const char *filename)
static int searcher_Lua (lua_State *L)
static int loadfunc (lua_State *L, const char *filename, const char *modname)
static int searcher_C (lua_State *L)
static int searcher_Croot (lua_State *L)
static int searcher_preload (lua_State *L)
static void findloader (lua_State *L, const char *name)
static int ll_require (lua_State *L)
static void createsearcherstable (lua_State *L)
static void createclibstable (lua_State *L)
LUAMOD_API int luaopen_package (lua_State *L)
Variables
static const char *const CLIBS = "_CLIBS"
static const luaL_Reg pk_funcs []
static const luaL_Reg ll_funcs []
Macro Definition Documentation
DLMSG
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
Definition at line 237 of file lua-5.4.3/src/loadlib.c.
Referenced by lsys_load(), and lsys_sym().
ERRFUNC
#define ERRFUNC 2
Definition at line 377 of file lua-5.4.3/src/loadlib.c.
Referenced by loadfunc(), lookforfunc(), and searcher_Croot().
ERRLIB
#define ERRLIB 1
Definition at line 376 of file lua-5.4.3/src/loadlib.c.
Referenced by ll_loadlib(), and lookforfunc().
LIB_FAIL [1/2]
#define LIB_FAIL "open"
Definition at line 64 of file lua-5.4.3/src/loadlib.c.
Referenced by ll_loadlib().
LIB_FAIL [2/2]
#define LIB_FAIL "absent"
Definition at line 64 of file lua-5.4.3/src/loadlib.c.
loadlib_c
#define loadlib_c
Definition at line 11 of file lua-5.4.3/src/loadlib.c.
LUA_CPATH_VAR
#define LUA_CPATH_VAR "LUA_CPATH"
Definition at line 277 of file lua-5.4.3/src/loadlib.c.
Referenced by luaopen_package().
LUA_CSUBSEP
#define LUA_CSUBSEP LUA_DIRSEP
Definition at line 43 of file lua-5.4.3/src/loadlib.c.
Referenced by searcher_C(), and searcher_Croot().
LUA_IGMARK
#define LUA_IGMARK "-"
Definition at line 32 of file lua-5.4.3/src/loadlib.c.
Referenced by loadfunc(), and luaopen_package().
LUA_LIB
#define LUA_LIB
Definition at line 12 of file lua-5.4.3/src/loadlib.c.
LUA_LSUBSEP
#define LUA_LSUBSEP LUA_DIRSEP
Definition at line 47 of file lua-5.4.3/src/loadlib.c.
Referenced by searcher_Lua().
LUA_OFSEP
#define LUA_OFSEP "_"
Definition at line 55 of file lua-5.4.3/src/loadlib.c.
Referenced by loadfunc().
LUA_PATH_VAR
#define LUA_PATH_VAR "LUA_PATH"
Definition at line 273 of file lua-5.4.3/src/loadlib.c.
Referenced by luaopen_package().
LUA_POF
#define LUA_POF "luaopen_"
Definition at line 52 of file lua-5.4.3/src/loadlib.c.
Referenced by loadfunc().
setprogdir
#define setprogdir (L) ((void)0)
Definition at line 67 of file lua-5.4.3/src/loadlib.c.
Referenced by setpath().
Typedef Documentation
voidf
typedef void(* voidf) (void)
Definition at line 74 of file lua-5.4.3/src/loadlib.c.
Function Documentation
addtoclib()
static void addtoclib (lua_State * L, const char * path, void * plib) static
Definition at line 349 of file lua-5.4.3/src/loadlib.c.
{
  lua_getfield(L, LUA_REGISTRYINDEX, CLIBS);
  lua_pushlightuserdata(L, plib);
  lua_pushvalue(L, -1);
  lua_setfield(L, -3, path);  /* CLIBS[path] = plib */
  lua_rawseti(L, -2, luaL_len(L, -2) + 1);  /* CLIBS[#CLIBS + 1] = plib */
  lua_pop(L, 1);  /* pop CLIBS table */
}
References CLIBS, lua_getfield(), lua_pop, lua_pushlightuserdata(), lua_pushvalue(), lua_rawseti(), LUA_REGISTRYINDEX, lua_setfield(), and luaL_len().
Referenced by lookforfunc().
checkclib()
static void * checkclib (lua_State * L, const char * path) static
Definition at line 335 of file lua-5.4.3/src/loadlib.c.
{
  void *plib;
  lua_getfield(L, LUA_REGISTRYINDEX, CLIBS);
  lua_getfield(L, -1, path);
  plib = lua_touserdata(L, -1);  /* plib = CLIBS[path] */
  lua_pop(L, 2);  /* pop CLIBS table and 'plib' */
  return plib;
}
References CLIBS, lua_getfield(), lua_pop, LUA_REGISTRYINDEX, and lua_touserdata().
Referenced by lookforfunc().
checkload()
static int checkload (lua_State * L, int stat, const char * filename) static
Definition at line 534 of file lua-5.4.3/src/loadlib.c.
{
  if (l_likely(stat)) {  /* module loaded successfully? */
    lua_pushstring(L, filename);  /* will be 2nd argument to module */
    return 2;  /* return open function and file name */
  }
  else
    return luaL_error(L, "error loading module '%s' from file '%s':\n\t%s",
                          lua_tostring(L, 1), filename, lua_tostring(L, -1));
}
References lua_pushstring(), lua_tostring, and luaL_error().
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
createclibstable()
static void createclibstable (lua_State * L) static
Definition at line 730 of file lua-5.4.3/src/loadlib.c.
{
  luaL_getsubtable(L, LUA_REGISTRYINDEX, CLIBS);  /* create CLIBS table */
  lua_createtable(L, 0, 1);  /* create metatable for CLIBS */
  lua_pushcfunction(L, gctm);
  lua_setfield(L, -2, "__gc");  /* set finalizer for CLIBS table */
  lua_setmetatable(L, -2);
}
References CLIBS, gctm(), lua_createtable(), lua_pushcfunction, LUA_REGISTRYINDEX, lua_setfield(), lua_setmetatable(), and luaL_getsubtable().
Referenced by luaopen_package().
createsearcherstable()
static void createsearcherstable (lua_State * L) static
Definition at line 710 of file lua-5.4.3/src/loadlib.c.
{
  static const lua_CFunction searchers[] =
    {searcher_preload, searcher_Lua, searcher_C, searcher_Croot, NULL};
  int i;
  /* create 'searchers' table */
  lua_createtable(L, sizeof(searchers)/sizeof(searchers[0]) - 1, 0);
  /* fill it with predefined searchers */
  for (i=0; searchers[i] != NULL; i++) {
    lua_pushvalue(L, -2);  /* set 'package' as upvalue for all searchers */
    lua_pushcclosure(L, searchers[i], 1);
    lua_rawseti(L, -2, i+1);
  }
  lua_setfield(L, -2, "searchers");  /* put it in field 'searchers' */
}
References lua_createtable(), lua_pushcclosure(), lua_pushvalue(), lua_rawseti(), lua_setfield(), NULL, searcher_C(), searcher_Croot(), searcher_Lua(), and searcher_preload().
Referenced by luaopen_package().
findfile()
static const char * findfile (lua_State * L, const char * name, const char * pname, const char * dirsep) static
Definition at line 522 of file lua-5.4.3/src/loadlib.c.
{
  const char *path;
  lua_getfield(L, lua_upvalueindex(1), pname);
  path = lua_tostring(L, -1);
  if (l_unlikely(path == NULL))
    luaL_error(L, "'package.%s' must be a string", pname);
  return searchpath(L, name, path, ".", dirsep);
}
References lua_getfield(), lua_tostring, lua_upvalueindex, luaL_error(), name, NULL, and searchpath().
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
findloader()
static void findloader (lua_State * L, const char * name) static
Definition at line 624 of file lua-5.4.3/src/loadlib.c.
{
  int i;
  luaL_Buffer msg;  /* to build error message */
  /* push 'package.searchers' to index 3 in the stack */
  if (l_unlikely(lua_getfield(L, lua_upvalueindex(1), "searchers")
                 != LUA_TTABLE))
    luaL_error(L, "'package.searchers' must be a table");
  luaL_buffinit(L, &msg);
  /*  iterate over available searchers to find a loader */
  for (i = 1; ; i++) {
    luaL_addstring(&msg, "\n\t");  /* error-message prefix */
    if (l_unlikely(lua_rawgeti(L, 3, i) == LUA_TNIL)) {  /* no more searchers? */
      lua_pop(L, 1);  /* remove nil */
      luaL_buffsub(&msg, 2);  /* remove prefix */
      luaL_pushresult(&msg);  /* create error message */
      luaL_error(L, "module '%s' not found:%s", name, lua_tostring(L, -1));
    }
    lua_pushstring(L, name);
    lua_call(L, 1, 2);  /* call it */
    if (lua_isfunction(L, -2))  /* did it find a loader? */
      return;  /* module loader found */
    else if (lua_isstring(L, -2)) {  /* searcher returned error message? */
      lua_pop(L, 1);  /* remove extra return */
      luaL_addvalue(&msg);  /* concatenate error message */
    }
    else {  /* no error message */
      lua_pop(L, 2);  /* remove both returns */
      luaL_buffsub(&msg, 2);  /* remove prefix */
    }
  }
}
References lua_call, lua_getfield(), lua_isfunction, lua_isstring(), lua_pop, lua_pushstring(), lua_rawgeti(), LUA_TNIL, lua_tostring, LUA_TTABLE, lua_upvalueindex, luaL_addstring(), luaL_addvalue(), luaL_buffinit(), luaL_buffsub, luaL_error(), luaL_pushresult(), and name.
Referenced by ll_require().
gctm()
static int gctm (lua_State * L) static
Definition at line 363 of file lua-5.4.3/src/loadlib.c.
{
  lua_Integer n = luaL_len(L, 1);
  for (; n >= 1; n--) {  /* for each handle, in reverse order */
    lua_rawgeti(L, 1, n);  /* get handle CLIBS[n] */
    lsys_unloadlib(lua_touserdata(L, -1));
    lua_pop(L, 1);  /* pop handle */
  }
  return 0;
}
References lsys_unloadlib(), lua_pop, lua_rawgeti(), lua_touserdata(), and luaL_len().
Referenced by createclibstable().
getnextfilename()
static const char * getnextfilename (char ** path, char * end) static
Definition at line 447 of file lua-5.4.3/src/loadlib.c.
{
  char *sep;
  char *name = *path;
  if (name == end)
    return NULL;  /* no more names */
  else if (*name == '\0') {  /* from previous iteration? */
    *name = *LUA_PATH_SEP;  /* restore separator */
    name++;  /* skip it */
  }
  sep = strchr(name, *LUA_PATH_SEP);  /* find next separator */
  if (sep == NULL)  /* separator not found? */
    sep = end;  /* name goes until the end */
  *sep = '\0';  /* finish file name */
  *path = sep;  /* will start next search from here */
  return name;
}
References LUA_PATH_SEP, name, and NULL.
Referenced by searchpath().
ll_loadlib()
static int ll_loadlib (lua_State * L) static
Definition at line 411 of file lua-5.4.3/src/loadlib.c.
{
  const char *path = luaL_checkstring(L, 1);
  const char *init = luaL_checkstring(L, 2);
  int stat = lookforfunc(L, path, init);
  if (l_likely(stat == 0))  /* no errors? */
    return 1;  /* return the loaded function */
  else {  /* error; error message is on stack top */
    luaL_pushfail(L);
    lua_insert(L, -2);
    lua_pushstring(L, (stat == ERRLIB) ?  LIB_FAIL : "init");
    return 3;  /* return fail, error message, and where */
  }
}
References ERRLIB, LIB_FAIL, lookforfunc(), lua_insert, lua_pushstring(), luaL_checkstring, and luaL_pushfail.
ll_require()
static int ll_require (lua_State * L) static
Definition at line 657 of file lua-5.4.3/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  lua_settop(L, 1);  /* LOADED table will be at index 2 */
  lua_getfield(L, LUA_REGISTRYINDEX, LUA_LOADED_TABLE);
  lua_getfield(L, 2, name);  /* LOADED[name] */
  if (lua_toboolean(L, -1))  /* is it there? */
    return 1;  /* package is already loaded */
  /* else must load package */
  lua_pop(L, 1);  /* remove 'getfield' result */
  findloader(L, name);
  lua_rotate(L, -2, 1);  /* function <-> loader data */
  lua_pushvalue(L, 1);  /* name is 1st argument to module loader */
  lua_pushvalue(L, -3);  /* loader data is 2nd argument */
  /* stack: ...; loader data; loader function; mod. name; loader data */
  lua_call(L, 2, 1);  /* run loader to load module */
  /* stack: ...; loader data; result from loader */
  if (!lua_isnil(L, -1))  /* non-nil return? */
    lua_setfield(L, 2, name);  /* LOADED[name] = returned value */
  else
    lua_pop(L, 1);  /* pop nil */
  if (lua_getfield(L, 2, name) == LUA_TNIL) {   /* module set no value? */
    lua_pushboolean(L, 1);  /* use true as result */
    lua_copy(L, -1, -2);  /* replace loader result */
    lua_setfield(L, 2, name);  /* LOADED[name] = true */
  }
  lua_rotate(L, -2, 1);  /* loader data <-> module result  */
  return 2;  /* return module result and loader data */
}
References findloader(), lua_call, lua_copy(), lua_getfield(), lua_isnil, LUA_LOADED_TABLE, lua_pop, lua_pushboolean(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_rotate(), lua_setfield(), lua_settop(), LUA_TNIL, lua_toboolean(), luaL_checkstring, and name.
ll_searchpath()
static int ll_searchpath (lua_State * L) static
Definition at line 508 of file lua-5.4.3/src/loadlib.c.
{
  const char *f = searchpath(L, luaL_checkstring(L, 1),
                                luaL_checkstring(L, 2),
                                luaL_optstring(L, 3, "."),
                                luaL_optstring(L, 4, LUA_DIRSEP));
  if (f != NULL) return 1;
  else {  /* error message is on top of the stack */
    luaL_pushfail(L);
    lua_insert(L, -2);
    return 2;  /* return fail + error message */
  }
}
References LUA_DIRSEP, lua_insert, luaL_checkstring, luaL_optstring, luaL_pushfail, NULL, and searchpath().
loadfunc()
static int loadfunc (lua_State * L, const char * filename, const char * modname) static
Definition at line 562 of file lua-5.4.3/src/loadlib.c.
{
  const char *openfunc;
  const char *mark;
  modname = luaL_gsub(L, modname, ".", LUA_OFSEP);
  mark = strchr(modname, *LUA_IGMARK);
  if (mark) {
    int stat;
    openfunc = lua_pushlstring(L, modname, mark - modname);
    openfunc = lua_pushfstring(L, LUA_POF"%s", openfunc);
    stat = lookforfunc(L, filename, openfunc);
    if (stat != ERRFUNC) return stat;
    modname = mark + 1;  /* else go ahead and try old-style name */
  }
  openfunc = lua_pushfstring(L, LUA_POF"%s", modname);
  return lookforfunc(L, filename, openfunc);
}
References ERRFUNC, lookforfunc(), LUA_IGMARK, LUA_OFSEP, LUA_POF, lua_pushfstring(), lua_pushlstring(), and luaL_gsub().
Referenced by searcher_C(), and searcher_Croot().
lookforfunc()
static int lookforfunc (lua_State * L, const char * path, const char * sym) static
Definition at line 390 of file lua-5.4.3/src/loadlib.c.
{
  void *reg = checkclib(L, path);  /* check loaded C libraries */
  if (reg == NULL) {  /* must load library? */
    reg = lsys_load(L, path, *sym == '*');  /* global symbols if 'sym'=='*' */
    if (reg == NULL) return ERRLIB;  /* unable to load library */
    addtoclib(L, path, reg);
  }
  if (*sym == '*') {  /* loading only library (no function)? */
    lua_pushboolean(L, 1);  /* return 'true' */
    return 0;  /* no errors */
  }
  else {
    lua_CFunction f = lsys_sym(L, reg, sym);
    if (f == NULL)
      return ERRFUNC;  /* unable to find function */
    lua_pushcfunction(L, f);  /* else create new function */
    return 0;  /* no errors */
  }
}
References addtoclib(), checkclib(), ERRFUNC, ERRLIB, lsys_load(), lsys_sym(), lua_pushboolean(), lua_pushcfunction, and NULL.
Referenced by ll_loadlib(), and loadfunc().
lsys_load()
static void * lsys_load (lua_State * L, const char * path, int seeglb) static
Definition at line 245 of file lua-5.4.3/src/loadlib.c.
{
  (void)(path); (void)(seeglb);  /* not used */
  lua_pushliteral(L, DLMSG);
  return NULL;
}
References DLMSG, lua_pushliteral, and NULL.
Referenced by lookforfunc().
lsys_sym()
static lua_CFunction lsys_sym (lua_State * L, void * lib, const char * sym) static
Definition at line 252 of file lua-5.4.3/src/loadlib.c.
{
  (void)(lib); (void)(sym);  /* not used */
  lua_pushliteral(L, DLMSG);
  return NULL;
}
References DLMSG, lua_pushliteral, and NULL.
Referenced by lookforfunc().
lsys_unloadlib()
static void lsys_unloadlib (void * lib) static
Definition at line 240 of file lua-5.4.3/src/loadlib.c.
{
  (void)(lib);  /* not used */
}
Referenced by gctm().
luaopen_package()
LUAMOD_API int luaopen_package (lua_State * L)
Definition at line 739 of file lua-5.4.3/src/loadlib.c.
{
  createclibstable(L);
  luaL_newlib(L, pk_funcs);  /* create 'package' table */
  createsearcherstable(L);
  /* set paths */
  setpath(L, "path", LUA_PATH_VAR, LUA_PATH_DEFAULT);
  setpath(L, "cpath", LUA_CPATH_VAR, LUA_CPATH_DEFAULT);
  /* store config information */
  lua_pushliteral(L, LUA_DIRSEP "\n" LUA_PATH_SEP "\n" LUA_PATH_MARK "\n"
                     LUA_EXEC_DIR "\n" LUA_IGMARK "\n");
  lua_setfield(L, -2, "config");
  /* set field 'loaded' */
  luaL_getsubtable(L, LUA_REGISTRYINDEX, LUA_LOADED_TABLE);
  lua_setfield(L, -2, "loaded");
  /* set field 'preload' */
  luaL_getsubtable(L, LUA_REGISTRYINDEX, LUA_PRELOAD_TABLE);
  lua_setfield(L, -2, "preload");
  lua_pushglobaltable(L);
  lua_pushvalue(L, -2);  /* set 'package' as upvalue for next lib */
  luaL_setfuncs(L, ll_funcs, 1);  /* open lib into global table */
  lua_pop(L, 1);  /* pop global table */
  return 1;  /* return 'package' table */
}
References createclibstable(), createsearcherstable(), ll_funcs, LUA_CPATH_DEFAULT, LUA_CPATH_VAR, LUA_DIRSEP, LUA_EXEC_DIR, LUA_IGMARK, LUA_LOADED_TABLE, LUA_PATH_DEFAULT, LUA_PATH_MARK, LUA_PATH_SEP, LUA_PATH_VAR, lua_pop, LUA_PRELOAD_TABLE, lua_pushglobaltable, lua_pushliteral, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), luaL_getsubtable(), luaL_newlib, luaL_setfuncs(), pk_funcs, and setpath().
noenv()
static int noenv (lua_State * L) static
Definition at line 285 of file lua-5.4.3/src/loadlib.c.
{
  int b;
  lua_getfield(L, LUA_REGISTRYINDEX, "LUA_NOENV");
  b = lua_toboolean(L, -1);
  lua_pop(L, 1);  /* remove value */
  return b;
}
References lua_getfield(), lua_pop, LUA_REGISTRYINDEX, and lua_toboolean().
Referenced by setpath().
pusherrornotfound()
static void pusherrornotfound (lua_State * L, const char * path) static
Definition at line 471 of file lua-5.4.3/src/loadlib.c.
{
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  luaL_addstring(&b, "no file '");
  luaL_addgsub(&b, path, LUA_PATH_SEP, "'\n\tno file '");
  luaL_addstring(&b, "'");
  luaL_pushresult(&b);
}
References LUA_PATH_SEP, luaL_addgsub(), luaL_addstring(), luaL_buffinit(), and luaL_pushresult().
Referenced by searchpath().
readable()
static int readable (const char * filename) static
Definition at line 434 of file lua-5.4.3/src/loadlib.c.
{
  FILE *f = fopen(filename, "r");  /* try to open file */
  if (f == NULL) return 0;  /* open failed */
  fclose(f);
  return 1;
}
References NULL.
Referenced by searchpath().
searcher_C()
static int searcher_C (lua_State * L) static
Definition at line 580 of file lua-5.4.3/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  const char *filename = findfile(L, name, "cpath", LUA_CSUBSEP);
  if (filename == NULL) return 1;  /* module not found in this path */
  return checkload(L, (loadfunc(L, filename, name) == 0), filename);
}
References checkload(), findfile(), loadfunc(), LUA_CSUBSEP, luaL_checkstring, name, and NULL.
Referenced by createsearcherstable().
searcher_Croot()
static int searcher_Croot (lua_State * L) static
Definition at line 588 of file lua-5.4.3/src/loadlib.c.
{
  const char *filename;
  const char *name = luaL_checkstring(L, 1);
  const char *p = strchr(name, '.');
  int stat;
  if (p == NULL) return 0;  /* is root */
  lua_pushlstring(L, name, p - name);
  filename = findfile(L, lua_tostring(L, -1), "cpath", LUA_CSUBSEP);
  if (filename == NULL) return 1;  /* root not found */
  if ((stat = loadfunc(L, filename, name)) != 0) {
    if (stat != ERRFUNC)
      return checkload(L, 0, filename);  /* real error */
    else {  /* open function not found */
      lua_pushfstring(L, "no module '%s' in file '%s'", name, filename);
      return 1;
    }
  }
  lua_pushstring(L, filename);  /* will be 2nd argument to module */
  return 2;
}
References checkload(), ERRFUNC, findfile(), loadfunc(), LUA_CSUBSEP, lua_pushfstring(), lua_pushlstring(), lua_pushstring(), lua_tostring, luaL_checkstring, name, and NULL.
Referenced by createsearcherstable().
searcher_Lua()
static int searcher_Lua (lua_State * L) static
Definition at line 545 of file lua-5.4.3/src/loadlib.c.
{
  const char *filename;
  const char *name = luaL_checkstring(L, 1);
  filename = findfile(L, name, "path", LUA_LSUBSEP);
  if (filename == NULL) return 1;  /* module not found in this path */
  return checkload(L, (luaL_loadfile(L, filename) == LUA_OK), filename);
}
References checkload(), findfile(), LUA_LSUBSEP, LUA_OK, luaL_checkstring, luaL_loadfile, name, and NULL.
Referenced by createsearcherstable().
searcher_preload()
static int searcher_preload (lua_State * L) static
Definition at line 610 of file lua-5.4.3/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  lua_getfield(L, LUA_REGISTRYINDEX, LUA_PRELOAD_TABLE);
  if (lua_getfield(L, -1, name) == LUA_TNIL) {  /* not found? */
    lua_pushfstring(L, "no field package.preload['%s']", name);
    return 1;
  }
  else {
    lua_pushliteral(L, ":preload:");
    return 2;
  }
}
References lua_getfield(), LUA_PRELOAD_TABLE, lua_pushfstring(), lua_pushliteral, LUA_REGISTRYINDEX, LUA_TNIL, luaL_checkstring, and name.
Referenced by createsearcherstable().
searchpath()
static const char * searchpath (lua_State * L, const char * name, const char * path, const char * sep, const char * dirsep) static
Definition at line 481 of file lua-5.4.3/src/loadlib.c.
{
  luaL_Buffer buff;
  char *pathname;  /* path with name inserted */
  char *endpathname;  /* its end */
  const char *filename;
  /* separator is non-empty and appears in 'name'? */
  if (*sep != '\0' && strchr(name, *sep) != NULL)
    name = luaL_gsub(L, name, sep, dirsep);  /* replace it by 'dirsep' */
  luaL_buffinit(L, &buff);
  /* add path to the buffer, replacing marks ('?') with the file name */
  luaL_addgsub(&buff, path, LUA_PATH_MARK, name);
  luaL_addchar(&buff, '\0');
  pathname = luaL_buffaddr(&buff);  /* writable list of file names */
  endpathname = pathname + luaL_bufflen(&buff) - 1;
  while ((filename = getnextfilename(&pathname, endpathname)) != NULL) {
    if (readable(filename))  /* does file exist and is readable? */
      return lua_pushstring(L, filename);  /* save and return name */
  }
  luaL_pushresult(&buff);  /* push path to create error message */
  pusherrornotfound(L, lua_tostring(L, -1));  /* create error message */
  return NULL;  /* not found */
}
References getnextfilename(), LUA_PATH_MARK, lua_pushstring(), lua_tostring, luaL_addchar, luaL_addgsub(), luaL_buffaddr, luaL_buffinit(), luaL_bufflen, luaL_gsub(), luaL_pushresult(), name, NULL, pusherrornotfound(), and readable().
Referenced by findfile(), and ll_searchpath().
setpath()
static void setpath (lua_State * L, const char * fieldname, const char * envname, const char * dft) static
Definition at line 297 of file lua-5.4.3/src/loadlib.c.
{
  const char *dftmark;
  const char *nver = lua_pushfstring(L, "%s%s", envname, LUA_VERSUFFIX);
  const char *path = getenv(nver);  /* try versioned name */
  if (path == NULL)  /* no versioned environment variable? */
    path = getenv(envname);  /* try unversioned name */
  if (path == NULL || noenv(L))  /* no environment variable? */
    lua_pushstring(L, dft);  /* use default */
  else if ((dftmark = strstr(path, LUA_PATH_SEP LUA_PATH_SEP)) == NULL)
    lua_pushstring(L, path);  /* nothing to change */
  else {  /* path contains a ";;": insert default path in its place */
    size_t len = strlen(path);
    luaL_Buffer b;
    luaL_buffinit(L, &b);
    if (path < dftmark) {  /* is there a prefix before ';;'? */
      luaL_addlstring(&b, path, dftmark - path);  /* add it */
      luaL_addchar(&b, *LUA_PATH_SEP);
    }
    luaL_addstring(&b, dft);  /* add default */
    if (dftmark < path + len - 2) {  /* is there a suffix after ';;'? */
      luaL_addchar(&b, *LUA_PATH_SEP);
      luaL_addlstring(&b, dftmark + 2, (path + len - 2) - dftmark);
    }
    luaL_pushresult(&b);
  }
  setprogdir(L);
  lua_setfield(L, -3, fieldname);  /* package[fieldname] = path value */
  lua_pop(L, 1);  /* pop versioned variable name ('nver') */
}
References LUA_PATH_SEP, lua_pop, lua_pushfstring(), lua_pushstring(), lua_setfield(), LUA_VERSUFFIX, luaL_addchar, luaL_addlstring(), luaL_addstring(), luaL_buffinit(), luaL_pushresult(), noenv(), NULL, and setprogdir.
Referenced by luaopen_package().
Variable Documentation
CLIBS
const char* const CLIBS = "_CLIBS" static
Definition at line 62 of file lua-5.4.3/src/loadlib.c.
Referenced by addtoclib(), checkclib(), and createclibstable().
ll_funcs
const luaL_Reg ll_funcs[] static
Initial value:
= {
  {"require", ll_require},
  {NULL, NULL}
}
Definition at line 704 of file lua-5.4.3/src/loadlib.c.
{
  {"require", ll_require},
  {NULL, NULL}
};
Referenced by luaopen_package().
pk_funcs
const luaL_Reg pk_funcs[] static
Initial value:
= {
  {"loadlib", ll_loadlib},
  {"searchpath", ll_searchpath},
  {"preload", NULL},
  {"cpath", NULL},
  {"path", NULL},
  {"searchers", NULL},
  {"loaded", NULL},
  {NULL, NULL}
}
Definition at line 691 of file lua-5.4.3/src/loadlib.c.
{
  {"loadlib", ll_loadlib},
  {"searchpath", ll_searchpath},
  /* placeholders */
  {"preload", NULL},
  {"cpath", NULL},
  {"path", NULL},
  {"searchers", NULL},
  {"loaded", NULL},
  {NULL, NULL}
};
Referenced by luaopen_package().