Github User Fetcher: ldebug.h File Reference
ldebug.h File Reference
#include "lstate.h"
Macros
#define pcRel(pc, p) (cast(int, (pc) - (p)->code) - 1)
#define getfuncline(f, pc) (((f)->lineinfo) ? (f)->lineinfo[pc] : 0)
#define resethookcount(L) (L->hookcount = L->basehookcount)
#define ci_func(ci) (clLvalue((ci)->func))
Functions
LUAI_FUNC l_noret luaG_typeerror (lua_State *L, const TValue *o, const char *opname)
LUAI_FUNC l_noret luaG_concaterror (lua_State *L, StkId p1, StkId p2)
LUAI_FUNC l_noret luaG_aritherror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_ordererror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_runerror (lua_State *L, const char *fmt,...)
LUAI_FUNC l_noret luaG_errormsg (lua_State *L)
Macro Definition Documentation
ci_func
#define ci_func (ci) (clLvalue((ci)->func))
Definition at line 21 of file lua-5.2.4/src/ldebug.h.
getfuncline
#define getfuncline (f, pc) (((f)->lineinfo) ? (f)->lineinfo[pc] : 0)
Definition at line 16 of file lua-5.2.4/src/ldebug.h.
Referenced by currentline(), currentline(), luaG_traceexec(), PrintCode(), PrintCode(), and traceexec().
pcRel
#define pcRel (pc, p) (cast(int, (pc) - (p)->code) - 1)
Definition at line 14 of file lua-5.2.4/src/ldebug.h.
resethookcount
#define resethookcount (L) (L->hookcount = L->basehookcount)
Definition at line 18 of file lua-5.2.4/src/ldebug.h.
Function Documentation
luaG_aritherror()
LUAI_FUNC l_noret luaG_aritherror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 588 of file lua-5.1.5/src/ldebug.c.
{
  TValue temp;
  if (luaV_tonumber(p1, &temp) == NULL)
    p2 = p1;  /* first operand is wrong */
  luaG_typeerror(L, p2, "perform arithmetic on");
}
References luaG_typeerror(), luaV_tonumber(), and NULL.
Referenced by Arith(), and luaV_arith().
luaG_concaterror()
LUAI_FUNC l_noret luaG_concaterror (lua_State * L, StkId p1, StkId p2)
Definition at line 581 of file lua-5.1.5/src/ldebug.c.
{
  if (ttisstring(p1) || ttisnumber(p1)) p1 = p2;
  lua_assert(!ttisstring(p1) && !ttisnumber(p1));
  luaG_typeerror(L, p1, "concatenate");
}
References lua_assert, luaG_typeerror(), ttisnumber, and ttisstring.
Referenced by luaT_trybinTM(), luaT_tryconcatTM(), luaV_concat(), and luaV_concat().
luaG_errormsg()
LUAI_FUNC l_noret luaG_errormsg (lua_State * L)
Definition at line 618 of file lua-5.1.5/src/ldebug.c.
{
  if (L->errfunc != 0) {  /* is there an error handling function? */
    StkId errfunc = restorestack(L, L->errfunc);
    if (!ttisfunction(errfunc)) luaD_throw(L, LUA_ERRERR);
    setobjs2s(L, L->top, L->top - 1);  /* move argument */
    setobjs2s(L, L->top - 1, errfunc);  /* push function */
    incr_top(L);
    luaD_call(L, L->top - 2, 1);  /* call it */
  }
  luaD_throw(L, LUA_ERRRUN);
}
luaG_ordererror()
LUAI_FUNC l_noret luaG_ordererror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 596 of file lua-5.1.5/src/ldebug.c.
{
  const char *t1 = luaT_typenames[ttype(p1)];
  const char *t2 = luaT_typenames[ttype(p2)];
  if (t1[2] == t2[2])
    luaG_runerror(L, "attempt to compare two %s values", t1);
  else
    luaG_runerror(L, "attempt to compare %s with %s", t1, t2);
  return 0;
}
luaG_runerror()
LUAI_FUNC l_noret luaG_runerror (lua_State * L, const char * fmt, ...)
Definition at line 631 of file lua-5.1.5/src/ldebug.c.
{
  va_list argp;
  va_start(argp, fmt);
  addinfo(L, luaO_pushvfstring(L, fmt, argp));
  va_end(argp);
  luaG_errormsg(L);
}
luaG_typeerror()
LUAI_FUNC l_noret luaG_typeerror (lua_State * L, const TValue * o, const char * opname)
Definition at line 567 of file lua-5.1.5/src/ldebug.c.
{
  const char *name = NULL;
  const char *t = luaT_typenames[ttype(o)];
  const char *kind = (isinstack(L->ci, o)) ?
                         getobjname(L, L->ci, cast_int(o - L->base), &name) :
                         NULL;
  if (kind)
    luaG_runerror(L, "attempt to %s %s " LUA_QS " (a %s value)",
                op, kind, name, t);
  else
    luaG_runerror(L, "attempt to %s a %s value", op, t);
}