Github User Fetcher: ldump.c File Reference
ldump.c File Reference
#include "lprefix.h"
#include <stddef.h>
#include "lua.h"
#include "lobject.h"
#include "lstate.h"
#include "lundump.h"
Data Structures
struct DumpState
Macros
#define ldump_c
#define LUA_CORE
#define dumpVector(D, v, n) dumpBlock(D,v,(n)*sizeof((v)[0]))
#define dumpLiteral(D, s) dumpBlock(D,s,sizeof(s) - sizeof(char))
#define dumpVar(D, x) dumpVector(D,&x,1)
#define DIBS ((sizeof(size_t) * 8 / 7) + 1)
Functions
static void dumpBlock (DumpState *D, const void *b, size_t size)
static void dumpByte (DumpState *D, int y)
static void dumpSize (DumpState *D, size_t x)
static void dumpInt (DumpState *D, int x)
static void dumpNumber (DumpState *D, lua_Number x)
static void dumpInteger (DumpState *D, lua_Integer x)
static void dumpString (DumpState *D, const TString *s)
static void dumpCode (DumpState *D, const Proto *f)
static void dumpFunction (DumpState *D, const Proto *f, TString *psource)
static void dumpConstants (DumpState *D, const Proto *f)
static void dumpProtos (DumpState *D, const Proto *f)
static void dumpUpvalues (DumpState *D, const Proto *f)
static void dumpDebug (DumpState *D, const Proto *f)
static void dumpHeader (DumpState *D)
int luaU_dump (lua_State *L, const Proto *f, lua_Writer w, void *data, int strip)
Macro Definition Documentation
DIBS
#define DIBS ((sizeof(size_t) * 8 / 7) + 1)
Definition at line 59 of file lua-5.4.3/src/ldump.c.
Referenced by dumpSize().
dumpLiteral
#define dumpLiteral (D, s) dumpBlock(D,s,sizeof(s) - sizeof(char))
Definition at line 37 of file lua-5.4.3/src/ldump.c.
Referenced by dumpHeader().
dumpVar
#define dumpVar (D, x) dumpVector(D,&x,1)
Definition at line 49 of file lua-5.4.3/src/ldump.c.
Referenced by dumpByte(), dumpInteger(), and dumpNumber().
dumpVector
#define dumpVector (D, v, n) dumpBlock(D,v,(n)*sizeof((v)[0]))
Definition at line 35 of file lua-5.4.3/src/ldump.c.
Referenced by dumpCode(), dumpDebug(), dumpSize(), and dumpString().
ldump_c
#define ldump_c
Definition at line 7 of file lua-5.4.3/src/ldump.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/ldump.c.
Function Documentation
dumpBlock()
static void dumpBlock (DumpState * D, const void * b, size_t size) static
Definition at line 40 of file lua-5.4.3/src/ldump.c.
{
  if (D->status == 0 && size > 0) {
    lua_unlock(D->L);
    D->status = (*D->writer)(D->L, b, size, D->data);
    lua_lock(D->L);
  }
}
References DumpState::data, DumpState::L, lua_lock, lua_unlock, DumpState::status, and DumpState::writer.
dumpByte()
static void dumpByte (DumpState * D, int y) static
Definition at line 52 of file lua-5.4.3/src/ldump.c.
{
  lu_byte x = (lu_byte)y;
  dumpVar(D, x);
}
References dumpVar.
Referenced by dumpConstants(), dumpFunction(), dumpHeader(), dumpUpvalues(), and luaU_dump().
dumpCode()
static void dumpCode (DumpState * D, const Proto * f) static
Definition at line 100 of file lua-5.4.3/src/ldump.c.
{
  dumpInt(D, f->sizecode);
  dumpVector(D, f->code, f->sizecode);
}
References Proto::code, dumpInt(), dumpVector, and Proto::sizecode.
Referenced by dumpFunction().
dumpConstants()
static void dumpConstants (DumpState * D, const Proto * f) static
Definition at line 108 of file lua-5.4.3/src/ldump.c.
{
  int i;
  int n = f->sizek;
  dumpInt(D, n);
  for (i = 0; i < n; i++) {
    const TValue *o = &f->k[i];
    int tt = ttypetag(o);
    dumpByte(D, tt);
    switch (tt) {
      case LUA_VNUMFLT:
        dumpNumber(D, fltvalue(o));
        break;
      case LUA_VNUMINT:
        dumpInteger(D, ivalue(o));
        break;
      case LUA_VSHRSTR:
      case LUA_VLNGSTR:
        dumpString(D, tsvalue(o));
        break;
      default:
        lua_assert(tt == LUA_VNIL || tt == LUA_VFALSE || tt == LUA_VTRUE);
    }
  }
}
References dumpByte(), dumpInt(), dumpInteger(), dumpNumber(), dumpString(), fltvalue, ivalue, Proto::k, lua_assert, LUA_VFALSE, LUA_VLNGSTR, LUA_VNIL, LUA_VNUMFLT, LUA_VNUMINT, LUA_VSHRSTR, LUA_VTRUE, Proto::sizek, tsvalue, and ttypetag.
Referenced by dumpFunction().
dumpDebug()
static void dumpDebug (DumpState * D, const Proto * f) static
Definition at line 154 of file lua-5.4.3/src/ldump.c.
{
  int i, n;
  n = (D->strip) ? 0 : f->sizelineinfo;
  dumpInt(D, n);
  dumpVector(D, f->lineinfo, n);
  n = (D->strip) ? 0 : f->sizeabslineinfo;
  dumpInt(D, n);
  for (i = 0; i < n; i++) {
    dumpInt(D, f->abslineinfo[i].pc);
    dumpInt(D, f->abslineinfo[i].line);
  }
  n = (D->strip) ? 0 : f->sizelocvars;
  dumpInt(D, n);
  for (i = 0; i < n; i++) {
    dumpString(D, f->locvars[i].varname);
    dumpInt(D, f->locvars[i].startpc);
    dumpInt(D, f->locvars[i].endpc);
  }
  n = (D->strip) ? 0 : f->sizeupvalues;
  dumpInt(D, n);
  for (i = 0; i < n; i++)
    dumpString(D, f->upvalues[i].name);
}
References Proto::abslineinfo, dumpInt(), dumpString(), dumpVector, LocVar::endpc, AbsLineInfo::line, Proto::lineinfo, Proto::locvars, AbsLineInfo::pc, Proto::sizeabslineinfo, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizeupvalues, LocVar::startpc, DumpState::strip, Proto::upvalues, and LocVar::varname.
Referenced by dumpFunction().
dumpFunction()
static void dumpFunction (DumpState * D, const Proto * f, TString * psource) static
Definition at line 179 of file lua-5.4.3/src/ldump.c.
{
  if (D->strip || f->source == psource)
    dumpString(D, NULL);  /* no debug info or same source as its parent */
  else
    dumpString(D, f->source);
  dumpInt(D, f->linedefined);
  dumpInt(D, f->lastlinedefined);
  dumpByte(D, f->numparams);
  dumpByte(D, f->is_vararg);
  dumpByte(D, f->maxstacksize);
  dumpCode(D, f);
  dumpConstants(D, f);
  dumpUpvalues(D, f);
  dumpProtos(D, f);
  dumpDebug(D, f);
}
References dumpByte(), dumpCode(), dumpConstants(), dumpDebug(), dumpInt(), dumpProtos(), dumpString(), dumpUpvalues(), Proto::is_vararg, Proto::lastlinedefined, Proto::linedefined, Proto::maxstacksize, NULL, Proto::numparams, Proto::source, and DumpState::strip.
Referenced by dumpProtos(), and luaU_dump().
dumpHeader()
static void dumpHeader (DumpState * D) static
Definition at line 197 of file lua-5.4.3/src/ldump.c.
{
  dumpLiteral(D, LUA_SIGNATURE);
  dumpByte(D, LUAC_VERSION);
  dumpByte(D, LUAC_FORMAT);
  dumpLiteral(D, LUAC_DATA);
  dumpByte(D, sizeof(Instruction));
  dumpByte(D, sizeof(lua_Integer));
  dumpByte(D, sizeof(lua_Number));
  dumpInteger(D, LUAC_INT);
  dumpNumber(D, LUAC_NUM);
}
References dumpByte(), dumpInteger(), dumpLiteral, dumpNumber(), LUA_SIGNATURE, LUAC_DATA, LUAC_FORMAT, LUAC_INT, LUAC_NUM, and LUAC_VERSION.
Referenced by luaU_dump().
dumpInt()
static void dumpInt (DumpState * D, int x) static
Definition at line 73 of file lua-5.4.3/src/ldump.c.
{
  dumpSize(D, x);
}
References dumpSize().
Referenced by dumpCode(), dumpConstants(), dumpDebug(), dumpFunction(), dumpProtos(), and dumpUpvalues().
dumpInteger()
static void dumpInteger (DumpState * D, lua_Integer x) static
Definition at line 83 of file lua-5.4.3/src/ldump.c.
{
  dumpVar(D, x);
}
References dumpVar.
Referenced by dumpConstants(), and dumpHeader().
dumpNumber()
static void dumpNumber (DumpState * D, lua_Number x) static
Definition at line 78 of file lua-5.4.3/src/ldump.c.
{
  dumpVar(D, x);
}
References dumpVar.
Referenced by dumpConstants(), and dumpHeader().
dumpProtos()
static void dumpProtos (DumpState * D, const Proto * f) static
Definition at line 134 of file lua-5.4.3/src/ldump.c.
{
  int i;
  int n = f->sizep;
  dumpInt(D, n);
  for (i = 0; i < n; i++)
    dumpFunction(D, f->p[i], f->source);
}
References dumpFunction(), dumpInt(), Proto::p, Proto::sizep, and Proto::source.
Referenced by dumpFunction().
dumpSize()
static void dumpSize (DumpState * D, size_t x) static
Definition at line 61 of file lua-5.4.3/src/ldump.c.
{
  lu_byte buff[DIBS];
  int n = 0;
  do {
    buff[DIBS - (++n)] = x & 0x7f;  /* fill buffer in reverse order */
    x >>= 7;
  } while (x != 0);
  buff[DIBS - 1] |= 0x80;  /* mark last byte */
  dumpVector(D, buff + DIBS - n, n);
}
References DIBS, and dumpVector.
Referenced by dumpInt(), and dumpString().
dumpString()
static void dumpString (DumpState * D, const TString * s) static
Definition at line 88 of file lua-5.4.3/src/ldump.c.
{
  if (s == NULL)
    dumpSize(D, 0);
  else {
    size_t size = tsslen(s);
    const char *str = getstr(s);
    dumpSize(D, size + 1);
    dumpVector(D, str, size);
  }
}
References dumpSize(), dumpVector, getstr, NULL, s, and tsslen.
Referenced by dumpConstants(), dumpDebug(), and dumpFunction().
dumpUpvalues()
static void dumpUpvalues (DumpState * D, const Proto * f) static
Definition at line 143 of file lua-5.4.3/src/ldump.c.
{
  int i, n = f->sizeupvalues;
  dumpInt(D, n);
  for (i = 0; i < n; i++) {
    dumpByte(D, f->upvalues[i].instack);
    dumpByte(D, f->upvalues[i].idx);
    dumpByte(D, f->upvalues[i].kind);
  }
}
References dumpByte(), dumpInt(), Proto::sizeupvalues, and Proto::upvalues.
Referenced by dumpFunction().
luaU_dump()
int luaU_dump (lua_State * L, const Proto * f, lua_Writer w, void * data, int strip)
Definition at line 213 of file lua-5.4.3/src/ldump.c.
{
  DumpState D;
  D.L = L;
  D.writer = w;
  D.data = data;
  D.strip = strip;
  D.status = 0;
  dumpHeader(&D);
  dumpByte(&D, f->sizeupvalues);
  dumpFunction(&D, f, NULL);
  return D.status;
}
References DumpState::data, dumpByte(), dumpFunction(), dumpHeader(), DumpState::L, NULL, Proto::sizeupvalues, DumpState::status, DumpState::strip, and DumpState::writer.