Github User Fetcher: lobject.c File Reference
lobject.c File Reference
#include "lprefix.h"
#include <locale.h>
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lctype.h"
#include "ldebug.h"
#include "ldo.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "lvm.h"
Data Structures
struct BuffFS
Macros
#define lobject_c
#define LUA_CORE
#define L_MAXLENNUM 200
#define MAXBY10 cast(lua_Unsigned, LUA_MAXINTEGER / 10)
#define MAXLASTD cast_int(LUA_MAXINTEGER % 10)
#define MAXNUMBER2STR 44
#define BUFVFS 200
#define addsize(b, sz) ((b)->blen += (sz))
#define RETS "..."
#define PRE "[string \""
#define POS "\"]"
#define addstr(a, b, l) (memcpy(a,b,(l) * sizeof(char)), a += (l))
Typedefs
typedef struct BuffFS BuffFS
Functions
int luaO_ceillog2 (unsigned int x)
static lua_Integer intarith (lua_State *L, int op, lua_Integer v1, lua_Integer v2)
static lua_Number numarith (lua_State *L, int op, lua_Number v1, lua_Number v2)
int luaO_rawarith (lua_State *L, int op, const TValue *p1, const TValue *p2, TValue *res)
void luaO_arith (lua_State *L, int op, const TValue *p1, const TValue *p2, StkId res)
int luaO_hexavalue (int c)
static int isneg (const char **s)
static const char * l_str2dloc (const char *s, lua_Number *result, int mode)
static const char * l_str2d (const char *s, lua_Number *result)
static const char * l_str2int (const char *s, lua_Integer *result)
size_t luaO_str2num (const char *s, TValue *o)
int luaO_utf8esc (char *buff, unsigned long x)
static int tostringbuff (TValue *obj, char *buff)
void luaO_tostring (lua_State *L, TValue *obj)
static void pushstr (BuffFS *buff, const char *str, size_t l)
static void clearbuff (BuffFS *buff)
static char * getbuff (BuffFS *buff, int sz)
static void addstr2buff (BuffFS *buff, const char *str, size_t slen)
static void addnum2buff (BuffFS *buff, TValue *num)
const char * luaO_pushvfstring (lua_State *L, const char *fmt, va_list argp)
const char * luaO_pushfstring (lua_State *L, const char *fmt,...)
void luaO_chunkid (char *out, const char *source, size_t srclen)
Macro Definition Documentation
addsize
#define addsize (b, sz) ((b)->blen += (sz))
Definition at line 436 of file lua-5.4.3/src/lobject.c.
Referenced by addnum2buff(), addstr2buff(), and luaO_pushvfstring().
addstr
#define addstr (a, b, l) (memcpy(a,b,(l) * sizeof(char)), a += (l))
Definition at line 555 of file lua-5.4.3/src/lobject.c.
Referenced by luaO_chunkid().
BUFVFS
#define BUFVFS 200
Definition at line 390 of file lua-5.4.3/src/lobject.c.
Referenced by addstr2buff(), and getbuff().
L_MAXLENNUM
#define L_MAXLENNUM 200
Definition at line 220 of file lua-5.4.3/src/lobject.c.
Referenced by l_str2d().
lobject_c
#define lobject_c
Definition at line 7 of file lua-5.4.3/src/lobject.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.4.3/src/lobject.c.
MAXBY10
#define MAXBY10 cast(lua_Unsigned, LUA_MAXINTEGER / 10)
Definition at line 273 of file lua-5.4.3/src/lobject.c.
Referenced by l_str2int().
MAXLASTD
#define MAXLASTD cast_int(LUA_MAXINTEGER % 10)
Definition at line 274 of file lua-5.4.3/src/lobject.c.
Referenced by l_str2int().
MAXNUMBER2STR
#define MAXNUMBER2STR 44
Definition at line 349 of file lua-5.4.3/src/lobject.c.
Referenced by addnum2buff(), luaO_tostring(), and tostringbuff().
POS
#define POS "\"]"
Definition at line 553 of file lua-5.4.3/src/lobject.c.
Referenced by luaO_chunkid().
PRE
#define PRE "[string \""
Definition at line 552 of file lua-5.4.3/src/lobject.c.
Referenced by luaO_chunkid().
RETS
#define RETS "..."
Definition at line 551 of file lua-5.4.3/src/lobject.c.
Referenced by luaO_chunkid().
Typedef Documentation
BuffFS
typedef struct BuffFS BuffFS
Function Documentation
addnum2buff()
static void addnum2buff (BuffFS * buff, TValue * num) static
Definition at line 459 of file lua-5.4.3/src/lobject.c.
{
  char *numbuff = getbuff(buff, MAXNUMBER2STR);
  int len = tostringbuff(num, numbuff);  /* format number into 'numbuff' */
  addsize(buff, len);
}
References addsize, getbuff(), MAXNUMBER2STR, and tostringbuff().
Referenced by luaO_pushvfstring().
addstr2buff()
static void addstr2buff (BuffFS * buff, const char * str, size_t slen) static
Definition at line 443 of file lua-5.4.3/src/lobject.c.
{
  if (slen <= BUFVFS) {  /* does string fit into buffer? */
    char *bf = getbuff(buff, cast_int(slen));
    memcpy(bf, str, slen);  /* add string to buffer */
    addsize(buff, cast_int(slen));
  }
  else {  /* string larger than buffer */
    clearbuff(buff);  /* string comes after buffer's content */
    pushstr(buff, str, slen);  /* push string */
  }
}
References addsize, BUFVFS, cast_int, clearbuff(), getbuff(), and pushstr().
Referenced by luaO_pushvfstring().
clearbuff()
static void clearbuff (BuffFS * buff) static
Definition at line 418 of file lua-5.4.3/src/lobject.c.
{
  pushstr(buff, buff->space, buff->blen);  /* push buffer contents */
  buff->blen = 0;  /* space now is empty */
}
References BuffFS::blen, pushstr(), and BuffFS::space.
Referenced by addstr2buff(), getbuff(), and luaO_pushvfstring().
getbuff()
static char * getbuff (BuffFS * buff, int sz) static
Definition at line 428 of file lua-5.4.3/src/lobject.c.
{
  lua_assert(buff->blen <= BUFVFS); lua_assert(sz <= BUFVFS);
  if (sz > BUFVFS - buff->blen)  /* not enough space? */
    clearbuff(buff);
  return buff->space + buff->blen;
}
References BuffFS::blen, BUFVFS, clearbuff(), lua_assert, and BuffFS::space.
Referenced by addnum2buff(), addstr2buff(), and luaO_pushvfstring().
intarith()
static lua_Integer intarith (lua_State * L, int op, lua_Integer v1, lua_Integer v2) static
Definition at line 53 of file lua-5.4.3/src/lobject.c.
{
  switch (op) {
    case LUA_OPADD: return intop(+, v1, v2);
    case LUA_OPSUB:return intop(-, v1, v2);
    case LUA_OPMUL:return intop(*, v1, v2);
    case LUA_OPMOD: return luaV_mod(L, v1, v2);
    case LUA_OPIDIV: return luaV_idiv(L, v1, v2);
    case LUA_OPBAND: return intop(&, v1, v2);
    case LUA_OPBOR: return intop(|, v1, v2);
    case LUA_OPBXOR: return intop(^, v1, v2);
    case LUA_OPSHL: return luaV_shiftl(v1, v2);
    case LUA_OPSHR: return luaV_shiftl(v1, -v2);
    case LUA_OPUNM: return intop(-, 0, v1);
    case LUA_OPBNOT: return intop(^, ~l_castS2U(0), v1);
    default: lua_assert(0); return 0;
  }
}
References intop, l_castS2U, lua_assert, LUA_OPADD, LUA_OPBAND, LUA_OPBNOT, LUA_OPBOR, LUA_OPBXOR, LUA_OPIDIV, LUA_OPMOD, LUA_OPMUL, LUA_OPSHL, LUA_OPSHR, LUA_OPSUB, LUA_OPUNM, luaV_idiv(), luaV_mod(), and luaV_shiftl().
Referenced by luaO_rawarith().
isneg()
static int isneg (const char ** s) static
Definition at line 141 of file lua-5.4.3/src/lobject.c.
{
  if (**s == '-') { (*s)++; return 1; }
  else if (**s == '+') (*s)++;
  return 0;
}
References s.
Referenced by l_str2int().
l_str2d()
static const char * l_str2d (const char * s, lua_Number * result) static
Definition at line 251 of file lua-5.4.3/src/lobject.c.
{
  const char *endptr;
  const char *pmode = strpbrk(s, ".xXnN");  /* look for special chars */
  int mode = pmode ? ltolower(cast_uchar(*pmode)) : 0;
  if (mode == 'n')  /* reject 'inf' and 'nan' */
    return NULL;
  endptr = l_str2dloc(s, result, mode);  /* try to convert */
  if (endptr == NULL) {  /* failed? may be a different locale */
    char buff[L_MAXLENNUM + 1];
    const char *pdot = strchr(s, '.');
    if (pdot == NULL || strlen(s) > L_MAXLENNUM)
      return NULL;  /* string too long or no dot; fail */
    strcpy(buff, s);  /* copy string to buffer */
    buff[pdot - s] = lua_getlocaledecpoint();  /* correct decimal point */
    endptr = l_str2dloc(buff, result, mode);  /* try again */
    if (endptr != NULL)
      endptr = s + (endptr - buff);  /* make relative to 's' */
  }
  return endptr;
}
References cast_uchar, L_MAXLENNUM, l_str2dloc(), ltolower, lua_getlocaledecpoint, NULL, and s.
Referenced by luaO_str2num().
l_str2dloc()
static const char * l_str2dloc (const char * s, lua_Number * result, int mode) static
Definition at line 228 of file lua-5.4.3/src/lobject.c.
{
  char *endptr;
  *result = (mode == 'x') ? lua_strx2number(s, &endptr)  /* try to convert */
                          : lua_str2number(s, &endptr);
  if (endptr == s) return NULL;  /* nothing recognized? */
  while (lisspace(cast_uchar(*endptr))) endptr++;  /* skip trailing spaces */
  return (*endptr == '\0') ? endptr : NULL;  /* OK iff no trailing chars */
}
References cast_uchar, lisspace, lua_str2number, lua_strx2number, NULL, and s.
Referenced by l_str2d().
l_str2int()
static const char * l_str2int (const char * s, lua_Integer * result) static
Definition at line 276 of file lua-5.4.3/src/lobject.c.
{
  lua_Unsigned a = 0;
  int empty = 1;
  int neg;
  while (lisspace(cast_uchar(*s))) s++;  /* skip initial spaces */
  neg = isneg(&s);
  if (s[0] == '0' &&
      (s[1] == 'x' || s[1] == 'X')) {  /* hex? */
    s += 2;  /* skip '0x' */
    for (; lisxdigit(cast_uchar(*s)); s++) {
      a = a * 16 + luaO_hexavalue(*s);
      empty = 0;
    }
  }
  else {  /* decimal */
    for (; lisdigit(cast_uchar(*s)); s++) {
      int d = *s - '0';
      if (a >= MAXBY10 && (a > MAXBY10 || d > MAXLASTD + neg))  /* overflow? */
        return NULL;  /* do not accept it (as integer) */
      a = a * 10 + d;
      empty = 0;
    }
  }
  while (lisspace(cast_uchar(*s))) s++;  /* skip trailing spaces */
  if (empty || *s != '\0') return NULL;  /* something wrong in the numeral */
  else {
    *result = l_castU2S((neg) ? 0u - a : a);
    return s;
  }
}
References cast_uchar, isneg(), l_castU2S, lisdigit, lisspace, lisxdigit, luaO_hexavalue(), MAXBY10, MAXLASTD, NULL, and s.
Referenced by luaO_str2num().
luaO_arith()
void luaO_arith (lua_State * L, int op, const TValue * p1, const TValue * p2, StkId res)
Definition at line 126 of file lua-5.4.3/src/lobject.c.
{
  if (!luaO_rawarith(L, op, p1, p2, s2v(res))) {
    /* could not perform raw operation; try metamethod */
    luaT_trybinTM(L, p1, p2, res, cast(TMS, (op - LUA_OPADD) + TM_ADD));
  }
}
References cast, LUA_OPADD, luaO_rawarith(), luaT_trybinTM(), s2v, and TM_ADD.
luaO_ceillog2()
int luaO_ceillog2 (unsigned int x)
Definition at line 35 of file lua-5.4.3/src/lobject.c.
{
  static const lu_byte log_2[256] = {  /* log_2[i] = ceil(log2(i - 1)) */
    0,1,2,2,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
    7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
    7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
  };
  int l = 0;
  x--;
  while (x >= 256) { l += 8; x >>= 8; }
  return l + log_2[x];
}
luaO_chunkid()
void luaO_chunkid (char * out, const char * source, size_t srclen)
Definition at line 557 of file lua-5.4.3/src/lobject.c.
{
  size_t bufflen = LUA_IDSIZE;  /* free space in buffer */
  if (*source == '=') {  /* 'literal' source */
    if (srclen <= bufflen)  /* small enough? */
      memcpy(out, source + 1, srclen * sizeof(char));
    else {  /* truncate it */
      addstr(out, source + 1, bufflen - 1);
      *out = '\0';
    }
  }
  else if (*source == '@') {  /* file name */
    if (srclen <= bufflen)  /* small enough? */
      memcpy(out, source + 1, srclen * sizeof(char));
    else {  /* add '...' before rest of name */
      addstr(out, RETS, LL(RETS));
      bufflen -= LL(RETS);
      memcpy(out, source + 1 + srclen - bufflen, bufflen * sizeof(char));
    }
  }
  else {  /* string; format as [string "source"] */
    const char *nl = strchr(source, '\n');  /* find first new line (if any) */
    addstr(out, PRE, LL(PRE));  /* add prefix */
    bufflen -= LL(PRE RETS POS) + 1;  /* save space for prefix+suffix+'\0' */
    if (srclen < bufflen && nl == NULL) {  /* small one-line source? */
      addstr(out, source, srclen);  /* keep it */
    }
    else {
      if (nl != NULL) srclen = nl - source;  /* stop at first newline */
      if (srclen > bufflen) srclen = bufflen;
      addstr(out, source, srclen);
      addstr(out, RETS, LL(RETS));
    }
    memcpy(out, POS, (LL(POS) + 1) * sizeof(char));
  }
}
References addstr, bufflen, LL, LUA_IDSIZE, NULL, POS, PRE, and RETS.
luaO_hexavalue()
int luaO_hexavalue (int c)
Definition at line 135 of file lua-5.4.3/src/lobject.c.
{
  if (lisdigit(c)) return c - '0';
  else return (ltolower(c) - 'a') + 10;
}
References lisdigit, and ltolower.
Referenced by l_str2int().
luaO_pushfstring()
const char * luaO_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 539 of file lua-5.4.3/src/lobject.c.
{
  const char *msg;
  va_list argp;
  va_start(argp, fmt);
  msg = luaO_pushvfstring(L, fmt, argp);
  va_end(argp);
  return msg;
}
References luaO_pushvfstring().
luaO_pushvfstring()
const char * luaO_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 470 of file lua-5.4.3/src/lobject.c.
{
  BuffFS buff;  /* holds last part of the result */
  const char *e;  /* points to next '%' */
  buff.pushed = buff.blen = 0;
  buff.L = L;
  while ((e = strchr(fmt, '%')) != NULL) {
    addstr2buff(&buff, fmt, e - fmt);  /* add 'fmt' up to '%' */
    switch (*(e + 1)) {  /* conversion specifier */
      case 's': {  /* zero-terminated string */
        const char *s = va_arg(argp, char *);
        if (s == NULL) s = "(null)";
        addstr2buff(&buff, s, strlen(s));
        break;
      }
      case 'c': {  /* an 'int' as a character */
        char c = cast_uchar(va_arg(argp, int));
        addstr2buff(&buff, &c, sizeof(char));
        break;
      }
      case 'd': {  /* an 'int' */
        TValue num;
        setivalue(&num, va_arg(argp, int));
        addnum2buff(&buff, &num);
        break;
      }
      case 'I': {  /* a 'lua_Integer' */
        TValue num;
        setivalue(&num, cast(lua_Integer, va_arg(argp, l_uacInt)));
        addnum2buff(&buff, &num);
        break;
      }
      case 'f': {  /* a 'lua_Number' */
        TValue num;
        setfltvalue(&num, cast_num(va_arg(argp, l_uacNumber)));
        addnum2buff(&buff, &num);
        break;
      }
      case 'p': {  /* a pointer */
        const int sz = 3 * sizeof(void*) + 8; /* enough space for '%p' */
        char *bf = getbuff(&buff, sz);
        void *p = va_arg(argp, void *);
        int len = lua_pointer2str(bf, sz, p);
        addsize(&buff, len);
        break;
      }
      case 'U': {  /* a 'long' as a UTF-8 sequence */
        char bf[UTF8BUFFSZ];
        int len = luaO_utf8esc(bf, va_arg(argp, long));
        addstr2buff(&buff, bf + UTF8BUFFSZ - len, len);
        break;
      }
      case '%': {
        addstr2buff(&buff, "%", 1);
        break;
      }
      default: {
        luaG_runerror(L, "invalid option '%%%c' to 'lua_pushfstring'",
                         *(e + 1));
      }
    }
    fmt = e + 2;  /* skip '%' and the specifier */
  }
  addstr2buff(&buff, fmt, strlen(fmt));  /* rest of 'fmt' */
  clearbuff(&buff);  /* empty buffer into the stack */
  lua_assert(buff.pushed == 1);
  return svalue(s2v(L->top - 1));
}
References addnum2buff(), addsize, addstr2buff(), BuffFS::blen, cast, cast_num, cast_uchar, clearbuff(), getbuff(), BuffFS::L, lua_assert, lua_pointer2str, luaG_runerror(), luaO_utf8esc(), NULL, BuffFS::pushed, s, s2v, setfltvalue, setivalue, svalue, lua_State::top, and UTF8BUFFSZ.
Referenced by luaO_pushfstring().
luaO_rawarith()
int luaO_rawarith (lua_State * L, int op, const TValue * p1, const TValue * p2, TValue * res)
Definition at line 89 of file lua-5.4.3/src/lobject.c.
{
  switch (op) {
    case LUA_OPBAND: case LUA_OPBOR: case LUA_OPBXOR:
    case LUA_OPSHL: case LUA_OPSHR:
    case LUA_OPBNOT: {  /* operate only on integers */
      lua_Integer i1; lua_Integer i2;
      if (tointegerns(p1, &i1) && tointegerns(p2, &i2)) {
        setivalue(res, intarith(L, op, i1, i2));
        return 1;
      }
      else return 0;  /* fail */
    }
    case LUA_OPDIV: case LUA_OPPOW: {  /* operate only on floats */
      lua_Number n1; lua_Number n2;
      if (tonumberns(p1, n1) && tonumberns(p2, n2)) {
        setfltvalue(res, numarith(L, op, n1, n2));
        return 1;
      }
      else return 0;  /* fail */
    }
    default: {  /* other operations */
      lua_Number n1; lua_Number n2;
      if (ttisinteger(p1) && ttisinteger(p2)) {
        setivalue(res, intarith(L, op, ivalue(p1), ivalue(p2)));
        return 1;
      }
      else if (tonumberns(p1, n1) && tonumberns(p2, n2)) {
        setfltvalue(res, numarith(L, op, n1, n2));
        return 1;
      }
      else return 0;  /* fail */
    }
  }
}
References intarith(), ivalue, LUA_OPBAND, LUA_OPBNOT, LUA_OPBOR, LUA_OPBXOR, LUA_OPDIV, LUA_OPPOW, LUA_OPSHL, LUA_OPSHR, numarith(), setfltvalue, setivalue, tointegerns, tonumberns, and ttisinteger.
Referenced by constfolding(), and luaO_arith().
luaO_str2num()
size_t luaO_str2num (const char * s, TValue * o)
Definition at line 308 of file lua-5.4.3/src/lobject.c.
{
  lua_Integer i; lua_Number n;
  const char *e;
  if ((e = l_str2int(s, &i)) != NULL) {  /* try as an integer */
    setivalue(o, i);
  }
  else if ((e = l_str2d(s, &n)) != NULL) {  /* else try as a float */
    setfltvalue(o, n);
  }
  else
    return 0;  /* conversion failed */
  return (e - s) + 1;  /* success; return string size */
}
References l_str2d(), l_str2int(), NULL, s, setfltvalue, and setivalue.
luaO_tostring()
void luaO_tostring (lua_State * L, TValue * obj)
Definition at line 374 of file lua-5.4.3/src/lobject.c.
{
  char buff[MAXNUMBER2STR];
  int len = tostringbuff(obj, buff);
  setsvalue(L, obj, luaS_newlstr(L, buff, len));
}
References luaS_newlstr(), MAXNUMBER2STR, setsvalue, and tostringbuff().
luaO_utf8esc()
int luaO_utf8esc (char * buff, unsigned long x)
Definition at line 323 of file lua-5.4.3/src/lobject.c.
{
  int n = 1;  /* number of bytes put in buffer (backwards) */
  lua_assert(x <= 0x7FFFFFFFu);
  if (x < 0x80)  /* ascii? */
    buff[UTF8BUFFSZ - 1] = cast_char(x);
  else {  /* need continuation bytes */
    unsigned int mfb = 0x3f;  /* maximum that fits in first byte */
    do {  /* add continuation bytes */
      buff[UTF8BUFFSZ - (n++)] = cast_char(0x80 | (x & 0x3f));
      x >>= 6;  /* remove added bits */
      mfb >>= 1;  /* now there is one less bit available in first byte */
    } while (x > mfb);  /* still needs continuation byte? */
    buff[UTF8BUFFSZ - n] = cast_char((~mfb << 1) | x);  /* add first byte */
  }
  return n;
}
References cast_char, lua_assert, and UTF8BUFFSZ.
Referenced by luaO_pushvfstring().
numarith()
static lua_Number numarith (lua_State * L, int op, lua_Number v1, lua_Number v2) static
Definition at line 73 of file lua-5.4.3/src/lobject.c.
{
  switch (op) {
    case LUA_OPADD: return luai_numadd(L, v1, v2);
    case LUA_OPSUB: return luai_numsub(L, v1, v2);
    case LUA_OPMUL: return luai_nummul(L, v1, v2);
    case LUA_OPDIV: return luai_numdiv(L, v1, v2);
    case LUA_OPPOW: return luai_numpow(L, v1, v2);
    case LUA_OPIDIV: return luai_numidiv(L, v1, v2);
    case LUA_OPUNM: return luai_numunm(L, v1);
    case LUA_OPMOD: return luaV_modf(L, v1, v2);
    default: lua_assert(0); return 0;
  }
}
References lua_assert, LUA_OPADD, LUA_OPDIV, LUA_OPIDIV, LUA_OPMOD, LUA_OPMUL, LUA_OPPOW, LUA_OPSUB, LUA_OPUNM, luai_numadd, luai_numdiv, luai_numidiv, luai_nummul, luai_numpow, luai_numsub, luai_numunm, and luaV_modf().
Referenced by luaO_rawarith().
pushstr()
static void pushstr (BuffFS * buff, const char * str, size_t l) static
Definition at line 405 of file lua-5.4.3/src/lobject.c.
{
  lua_State *L = buff->L;
  setsvalue2s(L, L->top, luaS_newlstr(L, str, l));
  L->top++;  /* may use one extra slot */
  buff->pushed++;
  luaV_concat(L, buff->pushed);  /* join partial results into one */
  buff->pushed = 1;
}
References BuffFS::L, luaS_newlstr(), luaV_concat(), BuffFS::pushed, setsvalue2s, and lua_State::top.
Referenced by addstr2buff(), and clearbuff().
tostringbuff()
static int tostringbuff (TValue * obj, char * buff) static
Definition at line 355 of file lua-5.4.3/src/lobject.c.
{
  int len;
  lua_assert(ttisnumber(obj));
  if (ttisinteger(obj))
    len = lua_integer2str(buff, MAXNUMBER2STR, ivalue(obj));
  else {
    len = lua_number2str(buff, MAXNUMBER2STR, fltvalue(obj));
    if (buff[strspn(buff, "-0123456789")] == '\0') {  /* looks like an int? */
      buff[len++] = lua_getlocaledecpoint();
      buff[len++] = '0';  /* adds '.0' to result */
    }
  }
  return len;
}
References fltvalue, ivalue, lua_assert, lua_getlocaledecpoint, lua_integer2str, lua_number2str, MAXNUMBER2STR, ttisinteger, and ttisnumber.
Referenced by addnum2buff(), and luaO_tostring().