Github User Fetcher: lcode.h File Reference
lcode.h File Reference
#include "llex.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
Macros
#define NO_JUMP (-1)
#define foldbinop(op) ((op) <= OPR_SHR)
#define luaK_codeABC(fs, o, a, b, c) luaK_codeABCk(fs,o,a,b,c,0)
#define getinstruction(fs, e) ((fs)->f->code[(e)->u.info])
#define luaK_setmultret(fs, e) luaK_setreturns(fs, e, LUA_MULTRET)
#define luaK_jumpto(fs, t) luaK_patchlist(fs, luaK_jump(fs), t)
Typedefs
typedef enum BinOpr BinOpr
typedef enum UnOpr UnOpr
Enumerations
enum BinOpr {
OPR_ADD , OPR_SUB , OPR_MUL , OPR_MOD ,
OPR_POW , OPR_DIV , OPR_IDIV , OPR_BAND ,
OPR_BOR , OPR_BXOR , OPR_SHL , OPR_SHR ,
OPR_CONCAT , OPR_EQ , OPR_LT , OPR_LE ,
OPR_NE , OPR_GT , OPR_GE , OPR_AND ,
OPR_OR , OPR_NOBINOPR
}
enum UnOpr {
OPR_MINUS , OPR_BNOT , OPR_NOT , OPR_LEN ,
OPR_NOUNOPR
}
Functions
LUAI_FUNC int luaK_code (FuncState *fs, Instruction i)
LUAI_FUNC int luaK_codeABx (FuncState *fs, OpCode o, int A, unsigned int Bx)
LUAI_FUNC int luaK_codeAsBx (FuncState *fs, OpCode o, int A, int Bx)
LUAI_FUNC int luaK_codeABCk (FuncState *fs, OpCode o, int A, int B, int C, int k)
LUAI_FUNC int luaK_isKint (expdesc *e)
LUAI_FUNC int luaK_exp2const (FuncState *fs, const expdesc *e, TValue *v)
LUAI_FUNC void luaK_fixline (FuncState *fs, int line)
LUAI_FUNC void luaK_nil (FuncState *fs, int from, int n)
LUAI_FUNC void luaK_reserveregs (FuncState *fs, int n)
LUAI_FUNC void luaK_checkstack (FuncState *fs, int n)
LUAI_FUNC void luaK_int (FuncState *fs, int reg, lua_Integer n)
LUAI_FUNC void luaK_dischargevars (FuncState *fs, expdesc *e)
LUAI_FUNC int luaK_exp2anyreg (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_exp2anyregup (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_exp2nextreg (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_exp2val (FuncState *fs, expdesc *e)
LUAI_FUNC int luaK_exp2RK (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_self (FuncState *fs, expdesc *e, expdesc *key)
LUAI_FUNC void luaK_indexed (FuncState *fs, expdesc *t, expdesc *k)
LUAI_FUNC void luaK_goiftrue (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_goiffalse (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_storevar (FuncState *fs, expdesc *var, expdesc *e)
LUAI_FUNC void luaK_setreturns (FuncState *fs, expdesc *e, int nresults)
LUAI_FUNC void luaK_setoneret (FuncState *fs, expdesc *e)
LUAI_FUNC int luaK_jump (FuncState *fs)
LUAI_FUNC void luaK_ret (FuncState *fs, int first, int nret)
LUAI_FUNC void luaK_patchlist (FuncState *fs, int list, int target)
LUAI_FUNC void luaK_patchtohere (FuncState *fs, int list)
LUAI_FUNC void luaK_concat (FuncState *fs, int *l1, int l2)
LUAI_FUNC int luaK_getlabel (FuncState *fs)
LUAI_FUNC void luaK_prefix (FuncState *fs, UnOpr op, expdesc *v, int line)
LUAI_FUNC void luaK_infix (FuncState *fs, BinOpr op, expdesc *v)
LUAI_FUNC void luaK_posfix (FuncState *fs, BinOpr op, expdesc *v1, expdesc *v2, int line)
LUAI_FUNC void luaK_settablesize (FuncState *fs, int pc, int ra, int asize, int hsize)
LUAI_FUNC void luaK_setlist (FuncState *fs, int base, int nelems, int tostore)
LUAI_FUNC void luaK_finish (FuncState *fs)
LUAI_FUNC l_noret luaK_semerror (LexState *ls, const char *msg)
Macro Definition Documentation
foldbinop
#define foldbinop (op) ((op) <= OPR_SHR)
Definition at line 45 of file lua-5.4.3/src/lcode.h.
Referenced by luaK_posfix().
getinstruction
#define getinstruction (fs, e) ((fs)->f->code[(e)->u.info])
Definition at line 55 of file lua-5.4.3/src/lcode.h.
luaK_codeABC
#define luaK_codeABC (fs, o, a, b, c) luaK_codeABCk(fs,o,a,b,c,0)
Definition at line 48 of file lua-5.4.3/src/lcode.h.
Referenced by breakstat(), check_conflict(), check_conflict(), check_conflict(), check_conflict(), checktoclose(), code_label(), code_label(), code_loadbool(), code_loadbool(), codearith(), codearith(), codebinexpval(), codeconcat(), codenot(), codenot(), codenot(), codenot(), codeunexpval(), codeunexpval(), condjump(), condjump(), condjump(), constructor(), constructor(), constructor(), constructor(), createlabel(), discharge2reg(), discharge2reg(), discharge2reg(), discharge2reg(), forbody(), forbody(), forbody(), forbody(), funcargs(), funcargs(), funcargs(), funcargs(), gotostat(), leaveblock(), leaveblock(), luaK_dischargevars(), luaK_nil(), luaK_ret(), luaK_self(), luaK_setlist(), luaK_storevar(), pushclosure(), recfield(), recfield(), recfield(), repeatstat(), setvararg(), simpleexp(), simpleexp(), simpleexp(), and simpleexp().
luaK_jumpto
#define luaK_jumpto (fs, t) luaK_patchlist(fs, luaK_jump(fs), t)
Definition at line 60 of file lua-5.4.3/src/lcode.h.
luaK_setmultret
#define luaK_setmultret (fs, e) luaK_setreturns(fs, e, LUA_MULTRET)
Definition at line 58 of file lua-5.4.3/src/lcode.h.
NO_JUMP
#define NO_JUMP (-1)
Definition at line 20 of file lua-5.4.3/src/lcode.h.
Typedef Documentation
BinOpr
typedef enum BinOpr BinOpr
UnOpr
typedef enum UnOpr UnOpr
Enumeration Type Documentation
BinOpr
enum BinOpr
Enumerator
OPR_ADD
OPR_SUB
OPR_MUL
OPR_MOD
OPR_POW
OPR_DIV
OPR_IDIV
OPR_BAND
OPR_BOR
OPR_BXOR
OPR_SHL
OPR_SHR
OPR_CONCAT
OPR_EQ
OPR_LT
OPR_LE
OPR_NE
OPR_GT
OPR_GE
OPR_AND
OPR_OR
OPR_NOBINOPR
Definition at line 26 of file lua-5.4.3/src/lcode.h.
                    {
  /* arithmetic operators */
  OPR_ADD, OPR_SUB, OPR_MUL, OPR_MOD, OPR_POW,
  OPR_DIV, OPR_IDIV,
  /* bitwise operators */
  OPR_BAND, OPR_BOR, OPR_BXOR,
  OPR_SHL, OPR_SHR,
  /* string operator */
  OPR_CONCAT,
  /* comparison operators */
  OPR_EQ, OPR_LT, OPR_LE,
  OPR_NE, OPR_GT, OPR_GE,
  /* logical operators */
  OPR_AND, OPR_OR,
  OPR_NOBINOPR
} BinOpr;
UnOpr
enum UnOpr
Enumerator
OPR_MINUS
OPR_BNOT
OPR_NOT
OPR_LEN
OPR_NOUNOPR
Definition at line 51 of file lua-5.4.3/src/lcode.h.
{ OPR_MINUS, OPR_BNOT, OPR_NOT, OPR_LEN, OPR_NOUNOPR } UnOpr;
Function Documentation
luaK_checkstack()
LUAI_FUNC void luaK_checkstack (FuncState * fs, int n)
Definition at line 199 of file lua-5.1.5/src/lcode.c.
{
  int newstack = fs->freereg + n;
  if (newstack > fs->f->maxstacksize) {
    if (newstack >= MAXSTACK)
      luaX_syntaxerror(fs->ls, "function or expression too complex");
    fs->f->maxstacksize = cast_byte(newstack);
  }
}
References cast_byte, FuncState::f, FuncState::freereg, FuncState::ls, luaX_syntaxerror(), MAXREGS, MAXSTACK, and Proto::maxstacksize.
Referenced by forlist(), forlist(), forlist(), forlist(), and luaK_reserveregs().
luaK_code()
LUAI_FUNC int luaK_code (FuncState * fs, Instruction i)
Definition at line 381 of file lua-5.4.3/src/lcode.c.
{
  Proto *f = fs->f;
  /* put new instruction in code array */
  luaM_growvector(fs->ls->L, f->code, fs->pc, f->sizecode, Instruction,
                  MAX_INT, "opcodes");
  f->code[fs->pc++] = i;
  savelineinfo(fs, f, fs->ls->lastline);
  return fs->pc - 1;  /* index of new instruction */
}
References Proto::code, FuncState::f, LexState::L, LexState::lastline, FuncState::ls, luaM_growvector, MAX_INT, FuncState::pc, savelineinfo(), and Proto::sizecode.
Referenced by codeextraarg(), codesJ(), luaK_codeABCk(), luaK_codeABx(), and luaK_codeAsBx().
luaK_codeABCk()
LUAI_FUNC int luaK_codeABCk (FuncState * fs, OpCode o, int A, int B, int C, int k)
Definition at line 396 of file lua-5.4.3/src/lcode.c.
{
  lua_assert(getOpMode(o) == iABC);
  lua_assert(a <= MAXARG_A && b <= MAXARG_B &&
             c <= MAXARG_C && (k & ~1) == 0);
  return luaK_code(fs, CREATE_ABCk(o, a, b, c, k));
}
References CREATE_ABCk, getOpMode, iABC, lua_assert, luaK_code(), MAXARG_A, MAXARG_B, and MAXARG_C.
Referenced by codeABRK(), condjump(), finishbinexpval(), and luaK_setlist().
luaK_codeABx()
LUAI_FUNC int luaK_codeABx (FuncState * fs, OpCode o, int A, unsigned int Bx)
Definition at line 812 of file lua-5.1.5/src/lcode.c.
{
  lua_assert(getOpMode(o) == iABx || getOpMode(o) == iAsBx);
  lua_assert(getCMode(o) == OpArgN);
  return luaK_code(fs, CREATE_ABx(o, a, bc), fs->ls->lastline);
}
References CREATE_ABx, getCMode, getOpMode, iABx, iAsBx, LexState::lastline, FuncState::ls, lua_assert, luaK_code(), luaK_code(), luaK_code(), luaK_code(), MAXARG_A, MAXARG_Bx, and OpArgN.
Referenced by codeclosure(), codeclosure(), codeclosure(), discharge2reg(), forbody(), fornum(), luaK_codek(), luaK_codek(), luaK_dischargevars(), luaK_storevar(), and pushclosure().
luaK_codeAsBx()
LUAI_FUNC int luaK_codeAsBx (FuncState * fs, OpCode o, int A, int Bx)
Definition at line 417 of file lua-5.4.3/src/lcode.c.
{
  unsigned int b = bc + OFFSET_sBx;
  lua_assert(getOpMode(o) == iAsBx);
  lua_assert(a <= MAXARG_A && b <= MAXARG_Bx);
  return luaK_code(fs, CREATE_ABx(o, a, b));
}
References CREATE_ABx, getOpMode, iAsBx, lua_assert, luaK_code(), MAXARG_A, MAXARG_Bx, and OFFSET_sBx.
luaK_concat()
LUAI_FUNC void luaK_concat (FuncState * fs, int * l1, int l2)
Definition at line 185 of file lua-5.1.5/src/lcode.c.
{
  if (l2 == NO_JUMP) return;
  else if (*l1 == NO_JUMP)
    *l1 = l2;
  else {
    int list = *l1;
    int next;
    while ((next = getjump(fs, list)) != NO_JUMP)  /* find last element */
      list = next;
    fixjump(fs, list, l2);
  }
}
References fixjump(), fixjump(), fixjump(), fixjump(), getjump(), getjump(), getjump(), getjump(), next, and NO_JUMP.
Referenced by breakstat(), exp2reg(), exp2reg(), exp2reg(), exp2reg(), ifstat(), luaK_goiffalse(), luaK_goiffalse(), luaK_goiftrue(), luaK_jump(), luaK_patchtohere(), luaK_posfix(), luaK_posfix(), luaK_posfix(), test_then_block(), test_then_block(), and test_then_block().
luaK_dischargevars()
LUAI_FUNC void luaK_dischargevars (FuncState * fs, expdesc * e)
Definition at line 304 of file lua-5.1.5/src/lcode.c.
{
  switch (e->k) {
    case VLOCAL: {
      e->k = VNONRELOC;
      break;
    }
    case VUPVAL: {
      e->u.s.info = luaK_codeABC(fs, OP_GETUPVAL, 0, e->u.s.info, 0);
      e->k = VRELOCABLE;
      break;
    }
    case VGLOBAL: {
      e->u.s.info = luaK_codeABx(fs, OP_GETGLOBAL, 0, e->u.s.info);
      e->k = VRELOCABLE;
      break;
    }
    case VINDEXED: {
      freereg(fs, e->u.s.aux);
      freereg(fs, e->u.s.info);
      e->u.s.info = luaK_codeABC(fs, OP_GETTABLE, 0, e->u.s.info, e->u.s.aux);
      e->k = VRELOCABLE;
      break;
    }
    case VVARARG:
    case VCALL: {
      luaK_setoneret(fs, e);
      break;
    }
    default: break;  /* there is one value available (somewhere) */
  }
}
References expdesc::aux, const2exp(), const2val(), freereg(), freereg(), freereg(), freereg(), freeregs(), expdesc::idx, expdesc::ind, expdesc::info, expdesc::k, lua_assert, luaK_codeABC, luaK_codeABx(), luaK_setoneret(), OP_GETFIELD, OP_GETGLOBAL, OP_GETI, OP_GETTABLE, OP_GETTABUP, OP_GETUPVAL, expdesc::ridx, expdesc::s, expdesc::t, expdesc::u, expdesc::var, VCALL, VCONST, VGLOBAL, VINDEXED, VINDEXI, VINDEXSTR, VINDEXUP, VLOCAL, VNONRELOC, VRELOC, VRELOCABLE, expdesc::vt, VUPVAL, and VVARARG.
Referenced by codenot(), codenot(), codenot(), discharge2reg(), discharge2reg(), discharge2reg(), discharge2reg(), luaK_exp2anyreg(), luaK_exp2nextreg(), luaK_exp2val(), luaK_goiffalse(), luaK_goiffalse(), luaK_goiftrue(), luaK_infix(), luaK_posfix(), luaK_posfix(), luaK_posfix(), luaK_prefix(), prefixexp(), primaryexp(), primaryexp(), and primaryexp().
luaK_exp2anyreg()
LUAI_FUNC int luaK_exp2anyreg (FuncState * fs, expdesc * e)
Definition at line 422 of file lua-5.1.5/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  if (e->k == VNONRELOC) {
    if (!hasjumps(e)) return e->u.s.info;  /* exp is already in a register */
    if (e->u.s.info >= fs->nactvar) {  /* reg. is not a local? */
      exp2reg(fs, e, e->u.s.info);  /* put value on it */
      return e->u.s.info;
    }
  }
  luaK_exp2nextreg(fs, e);  /* default */
  return e->u.s.info;
}
References exp2reg(), exp2reg(), exp2reg(), exp2reg(), hasjumps, expdesc::info, expdesc::k, luaK_dischargevars(), luaK_exp2nextreg(), luaY_nvarstack(), FuncState::nactvar, expdesc::s, expdesc::u, and VNONRELOC.
Referenced by codebinexpval(), codeeq(), codeorder(), codeunexpval(), codeunexpval(), field(), finishbinexpval(), luaK_exp2anyregup(), luaK_exp2RK(), luaK_exp2val(), luaK_indexed(), luaK_infix(), luaK_prefix(), luaK_prefix(), luaK_self(), luaK_storevar(), primaryexp(), retstat(), retstat(), retstat(), and retstat().
luaK_exp2anyregup()
LUAI_FUNC void luaK_exp2anyregup (FuncState * fs, expdesc * e)
Definition at line 514 of file lua-5.2.4/src/lcode.c.
{
  if (e->k != VUPVAL || hasjumps(e))
    luaK_exp2anyreg(fs, e);
}
References hasjumps, expdesc::k, luaK_exp2anyreg(), and VUPVAL.
Referenced by fieldsel(), fieldsel(), fieldsel(), suffixedexp(), suffixedexp(), and suffixedexp().
luaK_exp2const()
LUAI_FUNC int luaK_exp2const (FuncState * fs, const expdesc * e, TValue * v)
Definition at line 83 of file lua-5.4.3/src/lcode.c.
{
  if (hasjumps(e))
    return 0;  /* not a constant */
  switch (e->k) {
    case VFALSE:
      setbfvalue(v);
      return 1;
    case VTRUE:
      setbtvalue(v);
      return 1;
    case VNIL:
      setnilvalue(v);
      return 1;
    case VKSTR: {
      setsvalue(fs->ls->L, v, e->u.strval);
      return 1;
    }
    case VCONST: {
      setobj(fs->ls->L, v, const2val(fs, e));
      return 1;
    }
    default: return tonumeral(e, v);
  }
}
References const2val(), hasjumps, expdesc::k, LexState::L, FuncState::ls, setbfvalue, setbtvalue, setnilvalue, setobj, setsvalue, expdesc::strval, tonumeral(), expdesc::u, VCONST, VFALSE, VKSTR, VNIL, and VTRUE.
Referenced by localstat().
luaK_exp2nextreg()
LUAI_FUNC void luaK_exp2nextreg (FuncState * fs, expdesc * e)
Definition at line 414 of file lua-5.1.5/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  freeexp(fs, e);
  luaK_reserveregs(fs, 1);
  exp2reg(fs, e, fs->freereg - 1);
}
References exp2reg(), exp2reg(), exp2reg(), exp2reg(), freeexp(), freeexp(), freeexp(), freeexp(), FuncState::freereg, luaK_dischargevars(), and luaK_reserveregs().
Referenced by adjust_assign(), adjust_assign(), adjust_assign(), adjust_assign(), closelistfield(), closelistfield(), closelistfield(), closelistfield(), codeclosure(), codeclosure(), codeclosure(), constructor(), constructor(), constructor(), exp1(), exp1(), exp1(), exp1(), explist(), explist(), explist(), explist1(), funcargs(), funcargs(), funcargs(), funcargs(), lastlistfield(), lastlistfield(), lastlistfield(), lastlistfield(), luaK_exp2anyreg(), luaK_infix(), luaK_posfix(), luaK_posfix(), luaK_posfix(), primaryexp(), retstat(), retstat(), retstat(), retstat(), suffixedexp(), suffixedexp(), and suffixedexp().
luaK_exp2RK()
LUAI_FUNC int luaK_exp2RK (FuncState * fs, expdesc * e)
Definition at line 444 of file lua-5.1.5/src/lcode.c.
{
  luaK_exp2val(fs, e);
  switch (e->k) {
    case VKNUM:
    case VTRUE:
    case VFALSE:
    case VNIL: {
      if (fs->nk <= MAXINDEXRK) {  /* constant fit in RK operand? */
        e->u.s.info = (e->k == VNIL)  ? nilK(fs) :
                      (e->k == VKNUM) ? luaK_numberK(fs, e->u.nval) :
                                        boolK(fs, (e->k == VTRUE));
        e->k = VK;
        return RKASK(e->u.s.info);
      }
      else break;
    }
    case VK: {
      if (e->u.s.info <= MAXINDEXRK)  /* constant fit in argC? */
        return RKASK(e->u.s.info);
      else break;
    }
    default: break;
  }
  /* not a constant in the right range: put it in a register */
  return luaK_exp2anyreg(fs, e);
}
References boolK(), boolK(), boolK(), expdesc::info, expdesc::ival, expdesc::k, luaK_exp2anyreg(), luaK_exp2K(), luaK_exp2val(), luaK_intK(), luaK_numberK(), luaK_numberK(), MAXINDEXRK, nilK(), nilK(), nilK(), FuncState::nk, expdesc::nval, RKASK, expdesc::s, expdesc::u, VFALSE, VK, VKFLT, VKINT, VKNUM, VNIL, and VTRUE.
Referenced by codeABRK(), codearith(), codearith(), codebinexpval(), codebitwise(), codecomp(), codecomp(), codecomp(), codeeq(), luaK_indexed(), luaK_infix(), luaK_self(), luaK_storevar(), recfield(), recfield(), and recfield().
luaK_exp2val()
LUAI_FUNC void luaK_exp2val (FuncState * fs, expdesc * e)
Definition at line 436 of file lua-5.1.5/src/lcode.c.
{
  if (hasjumps(e))
    luaK_exp2anyreg(fs, e);
  else
    luaK_dischargevars(fs, e);
}
References hasjumps, luaK_dischargevars(), and luaK_exp2anyreg().
Referenced by luaK_exp2RK(), luaK_posfix(), luaK_posfix(), yindex(), yindex(), yindex(), and yindex().
luaK_finish()
LUAI_FUNC void luaK_finish (FuncState * fs)
Definition at line 1786 of file lua-5.4.3/src/lcode.c.
{
  int i;
  Proto *p = fs->f;
  for (i = 0; i < fs->pc; i++) {
    Instruction *pc = &p->code[i];
    lua_assert(i == 0 || isOT(*(pc - 1)) == isIT(*pc));
    switch (GET_OPCODE(*pc)) {
      case OP_RETURN0: case OP_RETURN1: {
        if (!(fs->needclose || p->is_vararg))
          break;  /* no extra work */
        /* else use OP_RETURN to do the extra work */
        SET_OPCODE(*pc, OP_RETURN);
      }  /* FALLTHROUGH */
      case OP_RETURN: case OP_TAILCALL: {
        if (fs->needclose)
          SETARG_k(*pc, 1);  /* signal that it needs to close */
        if (p->is_vararg)
          SETARG_C(*pc, p->numparams + 1);  /* signal that it is vararg */
        break;
      }
      case OP_JMP: {
        int target = finaltarget(p->code, i);
        fixjump(fs, i, target);
        break;
      }
      default: break;
    }
  }
}
References Proto::code, FuncState::f, finaltarget(), fixjump(), GET_OPCODE, Proto::is_vararg, isIT, isOT, lua_assert, FuncState::needclose, Proto::numparams, OP_JMP, OP_RETURN, OP_RETURN0, OP_RETURN1, OP_TAILCALL, FuncState::pc, SET_OPCODE, SETARG_C, and SETARG_k.
Referenced by close_func().
luaK_fixline()
LUAI_FUNC void luaK_fixline (FuncState * fs, int line)
Definition at line 784 of file lua-5.1.5/src/lcode.c.
{
  fs->f->lineinfo[fs->pc - 1] = line;
}
References FuncState::f, Proto::lineinfo, FuncState::pc, removelastlineinfo(), and savelineinfo().
Referenced by codearith(), codebinexpval(), codeconcat(), codeunexpval(), codeunexpval(), finishbinexpval(), forbody(), forbody(), forbody(), forbody(), funcargs(), funcargs(), funcargs(), funcargs(), funcstat(), funcstat(), funcstat(), and funcstat().
luaK_getlabel()
LUAI_FUNC int luaK_getlabel (FuncState * fs)
Definition at line 94 of file lua-5.1.5/src/lcode.c.
{
  fs->lasttarget = fs->pc;
  return fs->pc;
}
References FuncState::lasttarget, and FuncState::pc.
Referenced by code_label(), code_label(), code_loadbool(), code_loadbool(), createlabel(), exp2reg(), exp2reg(), exp2reg(), exp2reg(), forbody(), labelstat(), luaK_patchtohere(), repeatstat(), repeatstat(), repeatstat(), repeatstat(), whilestat(), whilestat(), whilestat(), and whilestat().
luaK_goiffalse()
LUAI_FUNC void luaK_goiffalse (FuncState * fs, expdesc * e)
Definition at line 645 of file lua-5.2.4/src/lcode.c.
{
  int pc;  /* pc of last jump */
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VJMP: {
      pc = e->u.info;
      break;
    }
    case VNIL: case VFALSE: {
      pc = NO_JUMP;  /* always false; do nothing */
      break;
    }
    default: {
      pc = jumponcond(fs, e, 1);
      break;
    }
  }
  luaK_concat(fs, &e->t, pc);  /* insert last jump in `t' list */
  luaK_patchtohere(fs, e->f);
  e->f = NO_JUMP;
}
References expdesc::f, expdesc::info, jumponcond(), jumponcond(), jumponcond(), expdesc::k, luaK_concat(), luaK_dischargevars(), luaK_patchtohere(), NO_JUMP, expdesc::t, expdesc::u, VFALSE, VJMP, and VNIL.
Referenced by luaK_infix().
luaK_goiftrue()
LUAI_FUNC void luaK_goiftrue (FuncState * fs, expdesc * e)
Definition at line 539 of file lua-5.1.5/src/lcode.c.
{
  int pc;  /* pc of last jump */
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VK: case VKNUM: case VTRUE: {
      pc = NO_JUMP;  /* always true; do nothing */
      break;
    }
    case VJMP: {
      invertjump(fs, e);
      pc = e->u.s.info;
      break;
    }
    default: {
      pc = jumponcond(fs, e, 0);
      break;
    }
  }
  luaK_concat(fs, &e->f, pc);  /* insert last jump in `f' list */
  luaK_patchtohere(fs, e->t);
  e->t = NO_JUMP;
}
References expdesc::f, expdesc::info, invertjump(), invertjump(), jumponcond(), jumponcond(), jumponcond(), jumponcond(), expdesc::k, luaK_concat(), luaK_dischargevars(), luaK_patchtohere(), negatecondition(), negatecondition(), NO_JUMP, expdesc::s, expdesc::t, expdesc::u, VJMP, VK, VKFLT, VKINT, VKNUM, VKSTR, and VTRUE.
Referenced by cond(), cond(), cond(), cond(), luaK_infix(), test_then_block(), test_then_block(), and test_then_block().
luaK_indexed()
LUAI_FUNC void luaK_indexed (FuncState * fs, expdesc * t, expdesc * k)
Definition at line 621 of file lua-5.1.5/src/lcode.c.
{
  t->u.s.aux = luaK_exp2RK(fs, k);
  t->k = VINDEXED;
}
References expdesc::aux, cast_int, check_exp, hasjumps, expdesc::idx, expdesc::ind, expdesc::info, isCint(), isKstr(), expdesc::ival, expdesc::k, lua_assert, luaK_exp2anyreg(), luaK_exp2RK(), expdesc::ridx, expdesc::s, str2K(), expdesc::t, expdesc::u, expdesc::var, VINDEXED, VINDEXI, VINDEXSTR, VINDEXUP, vkisinreg, VKSTR, VLOCAL, VNONRELOC, expdesc::vt, and VUPVAL.
Referenced by field(), fieldsel(), fieldsel(), fieldsel(), primaryexp(), recfield(), singlevar(), singlevar(), singlevar(), suffixedexp(), suffixedexp(), and suffixedexp().
luaK_infix()
LUAI_FUNC void luaK_infix (FuncState * fs, BinOpr op, expdesc * v)
Definition at line 710 of file lua-5.1.5/src/lcode.c.
{
  switch (op) {
    case OPR_AND: {
      luaK_goiftrue(fs, v);
      break;
    }
    case OPR_OR: {
      luaK_goiffalse(fs, v);
      break;
    }
    case OPR_CONCAT: {
      luaK_exp2nextreg(fs, v);  /* operand must be on the `stack' */
      break;
    }
    case OPR_ADD: case OPR_SUB: case OPR_MUL: case OPR_DIV:
    case OPR_MOD: case OPR_POW: {
      if (!isnumeral(v)) luaK_exp2RK(fs, v);
      break;
    }
    default: {
      luaK_exp2RK(fs, v);
      break;
    }
  }
}
References dummy, isnumeral(), isnumeral(), isSCnumber(), lua_assert, luaK_dischargevars(), luaK_exp2anyreg(), luaK_exp2nextreg(), luaK_exp2RK(), luaK_goiffalse(), luaK_goiffalse(), luaK_goiftrue(), NULL, OPR_ADD, OPR_AND, OPR_BAND, OPR_BOR, OPR_BXOR, OPR_CONCAT, OPR_DIV, OPR_EQ, OPR_GE, OPR_GT, OPR_IDIV, OPR_LE, OPR_LT, OPR_MOD, OPR_MUL, OPR_NE, OPR_OR, OPR_POW, OPR_SHL, OPR_SHR, OPR_SUB, tonumeral(), and tonumeral().
Referenced by subexpr(), subexpr(), subexpr(), and subexpr().
luaK_int()
LUAI_FUNC void luaK_int (FuncState * fs, int reg, lua_Integer n)
Definition at line 654 of file lua-5.4.3/src/lcode.c.
{
  if (fitsBx(i))
    luaK_codeAsBx(fs, OP_LOADI, reg, cast_int(i));
  else
    luaK_codek(fs, reg, luaK_intK(fs, i));
}
References cast_int, fitsBx(), luaK_codeAsBx, luaK_codek(), luaK_intK(), and OP_LOADI.
Referenced by discharge2reg(), and fornum().
luaK_isKint()
LUAI_FUNC int luaK_isKint (expdesc * e)
Definition at line 1210 of file lua-5.4.3/src/lcode.c.
{
  return (e->k == VKINT && !hasjumps(e));
}
References hasjumps, expdesc::k, and VKINT.
Referenced by finishbinexpneg(), isCint(), and isSCint().
luaK_jump()
LUAI_FUNC int luaK_jump (FuncState * fs)
Definition at line 59 of file lua-5.1.5/src/lcode.c.
{
  int jpc = fs->jpc;  /* save list of jumps to here */
  int j;
  fs->jpc = NO_JUMP;
  j = luaK_codeAsBx(fs, OP_JMP, 0, NO_JUMP);
  luaK_concat(fs, &j, jpc);  /* keep them on hold */
  return j;
}
References codesJ(), FuncState::jpc, luaK_codeAsBx, luaK_concat(), NO_JUMP, and OP_JMP.
Referenced by breakstat(), breakstat(), condjump(), condjump(), condjump(), condjump(), exp2reg(), exp2reg(), exp2reg(), exp2reg(), forbody(), forbody(), forbody(), gotostat(), ifstat(), leaveblock(), leaveblock(), repeatstat(), repeatstat(), statement(), statement(), test_then_block(), test_then_block(), test_then_block(), and whilestat().
luaK_nil()
LUAI_FUNC void luaK_nil (FuncState * fs, int from, int n)
Definition at line 35 of file lua-5.1.5/src/lcode.c.
{
  Instruction *previous;
  if (fs->pc > fs->lasttarget) {  /* no jumps to current position? */
    if (fs->pc == 0) {  /* function start? */
      if (from >= fs->nactvar)
        return;  /* positions are already clean */
    }
    else {
      previous = &fs->f->code[fs->pc-1];
      if (GET_OPCODE(*previous) == OP_LOADNIL) {
        int pfrom = GETARG_A(*previous);
        int pto = GETARG_B(*previous);
        if (pfrom <= from && from <= pto+1) {  /* can connect both? */
          if (from+n-1 > pto)
            SETARG_B(*previous, from+n-1);
          return;
        }
      }
    }
  }
  luaK_codeABC(fs, OP_LOADNIL, from, from+n-1, 0);  /* else no optimization */
}
References Proto::code, FuncState::f, GET_OPCODE, GETARG_A, GETARG_B, FuncState::lasttarget, luaK_codeABC, FuncState::nactvar, OP_LOADNIL, FuncState::pc, previousinstruction(), SETARG_A, and SETARG_B.
Referenced by adjust_assign(), adjust_assign(), adjust_assign(), adjust_assign(), discharge2reg(), discharge2reg(), discharge2reg(), and discharge2reg().
luaK_patchlist()
LUAI_FUNC void luaK_patchlist (FuncState * fs, int list, int target)
Definition at line 169 of file lua-5.1.5/src/lcode.c.
{
  if (target == fs->pc)
    luaK_patchtohere(fs, list);
  else {
    lua_assert(target < fs->pc);
    patchlistaux(fs, list, target, NO_REG, target);
  }
}
References lua_assert, luaK_patchtohere(), NO_REG, patchlistaux(), patchlistaux(), patchlistaux(), patchlistaux(), and FuncState::pc.
Referenced by closegoto(), closegoto(), forbody(), forbody(), forbody(), gotostat(), luaK_patchtohere(), repeatstat(), repeatstat(), repeatstat(), repeatstat(), solvegoto(), and whilestat().
luaK_patchtohere()
LUAI_FUNC void luaK_patchtohere (FuncState * fs, int list)
Definition at line 179 of file lua-5.1.5/src/lcode.c.
{
  luaK_getlabel(fs);
  luaK_concat(fs, &fs->jpc, list);
}
References FuncState::jpc, luaK_concat(), luaK_getlabel(), and luaK_patchlist().
Referenced by exp2reg(), exp2reg(), exp2reg(), exp2reg(), forbody(), forbody(), forbody(), ifstat(), ifstat(), ifstat(), ifstat(), leaveblock(), leaveblock(), leaveblock(), luaK_goiffalse(), luaK_goiffalse(), luaK_goiftrue(), luaK_patchlist(), repeatstat(), repeatstat(), test_then_block(), test_then_block(), test_then_block(), whilestat(), whilestat(), whilestat(), and whilestat().
luaK_posfix()
LUAI_FUNC void luaK_posfix (FuncState * fs, BinOpr op, expdesc * v1, expdesc * v2, int line)
Definition at line 813 of file lua-5.2.4/src/lcode.c.
{
  switch (op) {
    case OPR_AND: {
      lua_assert(e1->t == NO_JUMP);  /* list must be closed */
      luaK_dischargevars(fs, e2);
      luaK_concat(fs, &e2->f, e1->f);
      *e1 = *e2;
      break;
    }
    case OPR_OR: {
      lua_assert(e1->f == NO_JUMP);  /* list must be closed */
      luaK_dischargevars(fs, e2);
      luaK_concat(fs, &e2->t, e1->t);
      *e1 = *e2;
      break;
    }
    case OPR_CONCAT: {
      luaK_exp2val(fs, e2);
      if (e2->k == VRELOCABLE && GET_OPCODE(getcode(fs, e2)) == OP_CONCAT) {
        lua_assert(e1->u.info == GETARG_B(getcode(fs, e2))-1);
        freeexp(fs, e1);
        SETARG_B(getcode(fs, e2), e1->u.info);
        e1->k = VRELOCABLE; e1->u.info = e2->u.info;
      }
      else {
        luaK_exp2nextreg(fs, e2);  /* operand must be on the 'stack' */
        codearith(fs, OP_CONCAT, e1, e2, line);
      }
      break;
    }
    case OPR_ADD: case OPR_SUB: case OPR_MUL: case OPR_DIV:
    case OPR_MOD: case OPR_POW: {
      codearith(fs, cast(OpCode, op - OPR_ADD + OP_ADD), e1, e2, line);
      break;
    }
    case OPR_EQ: case OPR_LT: case OPR_LE: {
      codecomp(fs, cast(OpCode, op - OPR_EQ + OP_EQ), 1, e1, e2);
      break;
    }
    case OPR_NE: case OPR_GT: case OPR_GE: {
      codecomp(fs, cast(OpCode, op - OPR_NE + OP_EQ), 0, e1, e2);
      break;
    }
    default: lua_assert(0);
  }
}
References cast, codearith(), codearith(), codebinexpval(), codebinexpval(), codebini(), codebitwise(), codecommutative(), codecomp(), codecomp(), codeconcat(), codeeq(), codeorder(), constfolding(), constfolding(), expdesc::f, finishbinexpneg(), foldbinop, freeexp(), freeexp(), GET_OPCODE, GETARG_B, getcode, getinstruction, expdesc::info, isSCint(), expdesc::k, lua_assert, LUA_OPADD, luaK_concat(), luaK_dischargevars(), luaK_exp2nextreg(), luaK_exp2val(), NO_JUMP, OP_ADD, OP_ADDI, OP_CONCAT, OP_EQ, OP_SHL, OP_SHLI, OP_SHR, OP_SHRI, OPR_ADD, OPR_AND, OPR_BAND, OPR_BOR, OPR_BXOR, OPR_CONCAT, OPR_DIV, OPR_EQ, OPR_GE, OPR_GT, OPR_IDIV, OPR_LE, OPR_LT, OPR_MOD, OPR_MUL, OPR_NE, OPR_OR, OPR_POW, OPR_SHL, OPR_SHR, OPR_SUB, SETARG_B, swapexps(), expdesc::t, TM_SHL, TM_SHR, TM_SUB, expdesc::u, and VRELOCABLE.
luaK_prefix()
LUAI_FUNC void luaK_prefix (FuncState * fs, UnOpr op, expdesc * v, int line)
Definition at line 762 of file lua-5.2.4/src/lcode.c.
{
  expdesc e2;
  e2.t = e2.f = NO_JUMP; e2.k = VKNUM; e2.u.nval = 0;
  switch (op) {
    case OPR_MINUS: {
      if (isnumeral(e))  /* minus constant? */
        e->u.nval = luai_numunm(NULL, e->u.nval);  /* fold it */
      else {
        luaK_exp2anyreg(fs, e);
        codearith(fs, OP_UNM, e, &e2, line);
      }
      break;
    }
    case OPR_NOT: codenot(fs, e); break;
    case OPR_LEN: {
      luaK_exp2anyreg(fs, e);  /* cannot operate on constants */
      codearith(fs, OP_LEN, e, &e2, line);
      break;
    }
    default: lua_assert(0);
  }
}
References cast, codearith(), codenot(), codenot(), codenot(), codeunexpval(), codeunexpval(), constfolding(), constfolding(), expdesc::f, isnumeral(), expdesc::k, lua_assert, LUA_OPUNM, luai_numunm, luaK_dischargevars(), luaK_exp2anyreg(), NO_JUMP, NULL, expdesc::nval, OP_LEN, OP_UNM, OPR_BNOT, OPR_LEN, OPR_MINUS, OPR_NOT, expdesc::t, expdesc::u, VKINT, and VKNUM.
luaK_reserveregs()
LUAI_FUNC void luaK_reserveregs (FuncState * fs, int n)
Definition at line 209 of file lua-5.1.5/src/lcode.c.
{
  luaK_checkstack(fs, n);
  fs->freereg += n;
}
References FuncState::freereg, and luaK_checkstack().
Referenced by adjust_assign(), adjust_assign(), adjust_assign(), adjust_assign(), check_conflict(), check_conflict(), check_conflict(), check_conflict(), constructor(), discharge2anyreg(), discharge2anyreg(), discharge2anyreg(), discharge2anyreg(), forbody(), forbody(), forbody(), forbody(), fornum(), fornum(), fornum(), fornum(), localfunc(), luaK_exp2nextreg(), luaK_self(), luaK_setreturns(), parlist(), parlist(), parlist(), and parlist().
luaK_ret()
LUAI_FUNC void luaK_ret (FuncState * fs, int first, int nret)
Definition at line 69 of file lua-5.1.5/src/lcode.c.
{
  luaK_codeABC(fs, OP_RETURN, first, nret+1, 0);
}
References luaK_codeABC, OP_RETURN, OP_RETURN0, and OP_RETURN1.
Referenced by close_func(), close_func(), close_func(), close_func(), retstat(), retstat(), retstat(), and retstat().
luaK_self()
LUAI_FUNC void luaK_self (FuncState * fs, expdesc * e, expdesc * key)
Definition at line 503 of file lua-5.1.5/src/lcode.c.
{
  int func;
  luaK_exp2anyreg(fs, e);
  freeexp(fs, e);
  func = fs->freereg;
  luaK_reserveregs(fs, 2);
  luaK_codeABC(fs, OP_SELF, func, e->u.s.info, luaK_exp2RK(fs, key));
  freeexp(fs, key);
  e->u.s.info = func;
  e->k = VNONRELOC;
}
References codeABRK(), freeexp(), freeexp(), freeexp(), freeexp(), FuncState::freereg, expdesc::info, expdesc::k, luaK_codeABC, luaK_exp2anyreg(), luaK_exp2RK(), luaK_reserveregs(), OP_SELF, expdesc::s, expdesc::u, and VNONRELOC.
Referenced by primaryexp(), suffixedexp(), suffixedexp(), and suffixedexp().
luaK_semerror()
LUAI_FUNC l_noret luaK_semerror (LexState * ls, const char * msg)
Definition at line 45 of file lua-5.4.3/src/lcode.c.
{
  ls->t.token = 0;  /* remove "near <token>" from final message */
  luaX_syntaxerror(ls, msg);
}
References luaX_syntaxerror(), LexState::t, and Token::token.
Referenced by check_readonly(), checkrepeated(), getlocalattribute(), jumpscopeerror(), localstat(), and undefgoto().
luaK_setlist()
LUAI_FUNC void luaK_setlist (FuncState * fs, int base, int nelems, int tostore)
Definition at line 819 of file lua-5.1.5/src/lcode.c.
{
  int c =  (nelems - 1)/LFIELDS_PER_FLUSH + 1;
  int b = (tostore == LUA_MULTRET) ? 0 : tostore;
  lua_assert(tostore != 0);
  if (c <= MAXARG_C)
    luaK_codeABC(fs, OP_SETLIST, base, b, c);
  else {
    luaK_codeABC(fs, OP_SETLIST, base, b, 0);
    luaK_code(fs, cast(Instruction, c), fs->ls->lastline);
  }
  fs->freereg = base + 1;  /* free registers with list values */
}
References cast, codeextraarg(), codeextraarg(), codeextraarg(), FuncState::freereg, LexState::lastline, LFIELDS_PER_FLUSH, FuncState::ls, lua_assert, LUA_MULTRET, luaK_code(), luaK_codeABC, luaK_codeABCk(), luaX_syntaxerror(), MAXARG_Ax, MAXARG_C, and OP_SETLIST.
Referenced by closelistfield(), closelistfield(), closelistfield(), closelistfield(), lastlistfield(), lastlistfield(), lastlistfield(), and lastlistfield().
luaK_setoneret()
LUAI_FUNC void luaK_setoneret (FuncState * fs, expdesc * e)
Definition at line 292 of file lua-5.1.5/src/lcode.c.
{
  if (e->k == VCALL) {  /* expression is an open function call? */
    e->k = VNONRELOC;
    e->u.s.info = GETARG_A(getcode(fs, e));
  }
  else if (e->k == VVARARG) {
    SETARG_B(getcode(fs, e), 2);
    e->k = VRELOCABLE;  /* can relocate its simple result */
  }
}
References GETARG_A, GETARG_C, getcode, getinstruction, expdesc::info, expdesc::k, lua_assert, expdesc::s, SETARG_B, SETARG_C, expdesc::u, VCALL, VNONRELOC, VRELOC, VRELOCABLE, and VVARARG.
Referenced by assignment(), assignment(), assignment(), luaK_dischargevars(), and restassign().
luaK_setreturns()
LUAI_FUNC void luaK_setreturns (FuncState * fs, expdesc * e, int nresults)
Definition at line 280 of file lua-5.1.5/src/lcode.c.
{
  if (e->k == VCALL) {  /* expression is an open function call? */
    SETARG_C(getcode(fs, e), nresults+1);
  }
  else if (e->k == VVARARG) {
    SETARG_B(getcode(fs, e), nresults+1);
    SETARG_A(getcode(fs, e), fs->freereg);
    luaK_reserveregs(fs, 1);
  }
}
References FuncState::freereg, getcode, getinstruction, expdesc::k, lua_assert, LUA_MULTRET, luaK_reserveregs(), SETARG_A, SETARG_B, SETARG_C, VCALL, and VVARARG.
Referenced by adjust_assign(), adjust_assign(), adjust_assign(), and adjust_assign().
luaK_settablesize()
LUAI_FUNC void luaK_settablesize (FuncState * fs, int pc, int ra, int asize, int hsize)
Definition at line 1732 of file lua-5.4.3/src/lcode.c.
{
  Instruction *inst = &fs->f->code[pc];
  int rb = (hsize != 0) ? luaO_ceillog2(hsize) + 1 : 0;  /* hash size */
  int extra = asize / (MAXARG_C + 1);  /* higher bits of array size */
  int rc = asize % (MAXARG_C + 1);  /* lower bits of array size */
  int k = (extra > 0);  /* true iff needs extra argument */
  *inst = CREATE_ABCk(OP_NEWTABLE, ra, rb, rc, k);
  *(inst + 1) = CREATE_Ax(OP_EXTRAARG, extra);
}
References Proto::code, CREATE_ABCk, CREATE_Ax, FuncState::f, luaO_ceillog2(), MAXARG_C, OP_EXTRAARG, and OP_NEWTABLE.
Referenced by constructor().
luaK_storevar()
LUAI_FUNC void luaK_storevar (FuncState * fs, expdesc * var, expdesc * e)
Definition at line 472 of file lua-5.1.5/src/lcode.c.
{
  switch (var->k) {
    case VLOCAL: {
      freeexp(fs, ex);
      exp2reg(fs, ex, var->u.s.info);
      return;
    }
    case VUPVAL: {
      int e = luaK_exp2anyreg(fs, ex);
      luaK_codeABC(fs, OP_SETUPVAL, e, var->u.s.info, 0);
      break;
    }
    case VGLOBAL: {
      int e = luaK_exp2anyreg(fs, ex);
      luaK_codeABx(fs, OP_SETGLOBAL, e, var->u.s.info);
      break;
    }
    case VINDEXED: {
      int e = luaK_exp2RK(fs, ex);
      luaK_codeABC(fs, OP_SETTABLE, var->u.s.info, var->u.s.aux, e);
      break;
    }
    default: {
      lua_assert(0);  /* invalid var kind to store */
      break;
    }
  }
  freeexp(fs, ex);
}
References expdesc::aux, codeABRK(), exp2reg(), exp2reg(), exp2reg(), exp2reg(), freeexp(), freeexp(), freeexp(), freeexp(), expdesc::idx, expdesc::ind, expdesc::info, expdesc::k, lua_assert, luaK_codeABC, luaK_codeABx(), luaK_exp2anyreg(), luaK_exp2RK(), OP_SETFIELD, OP_SETGLOBAL, OP_SETI, OP_SETTABLE, OP_SETTABUP, OP_SETUPVAL, expdesc::ridx, expdesc::s, expdesc::t, expdesc::u, expdesc::var, VGLOBAL, VINDEXED, VINDEXI, VINDEXSTR, VINDEXUP, VLOCAL, expdesc::vt, and VUPVAL.
Referenced by assignment(), assignment(), assignment(), funcstat(), funcstat(), funcstat(), funcstat(), localfunc(), recfield(), and restassign().