Github User Fetcher: lobject.c File Reference
lobject.c File Reference
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lctype.h"
#include "ldebug.h"
#include "ldo.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "lvm.h"
#include <math.h>
Macros
#define lobject_c
#define LUA_CORE
#define LL(x) (sizeof(x)/sizeof(char) - 1)
#define RETS "..."
#define PRE "[string \""
#define POS "\"]"
#define addstr(a, b, l) (memcpy(a,b,(l) * sizeof(char)), a += (l))
Functions
int luaO_int2fb (unsigned int x)
int luaO_fb2int (int x)
int luaO_ceillog2 (unsigned int x)
lua_Number luaO_arith (int op, lua_Number v1, lua_Number v2)
int luaO_hexavalue (int c)
static int isneg (const char **s)
static lua_Number readhexa (const char **s, lua_Number r, int *count)
static lua_Number lua_strx2number (const char *s, char **endptr)
int luaO_str2d (const char *s, size_t len, lua_Number *result)
static void pushstr (lua_State *L, const char *str, size_t l)
const char * luaO_pushvfstring (lua_State *L, const char *fmt, va_list argp)
const char * luaO_pushfstring (lua_State *L, const char *fmt,...)
void luaO_chunkid (char *out, const char *source, size_t bufflen)
Variables
LUAI_DDEF const TValue luaO_nilobject_ = {NILCONSTANT}
Macro Definition Documentation
addstr
#define addstr (a, b, l) (memcpy(a,b,(l) * sizeof(char)), a += (l))
Definition at line 250 of file lua-5.2.4/src/lobject.c.
Referenced by luaO_chunkid().
LL
#define LL (x) (sizeof(x)/sizeof(char) - 1)
Definition at line 244 of file lua-5.2.4/src/lobject.c.
Referenced by funcinfo(), luaO_chunkid(), and luaO_chunkid().
lobject_c
#define lobject_c
Definition at line 12 of file lua-5.2.4/src/lobject.c.
LUA_CORE
#define LUA_CORE
Definition at line 13 of file lua-5.2.4/src/lobject.c.
POS
#define POS "\"]"
Definition at line 248 of file lua-5.2.4/src/lobject.c.
Referenced by luaO_chunkid().
PRE
#define PRE "[string \""
Definition at line 247 of file lua-5.2.4/src/lobject.c.
Referenced by luaO_chunkid().
RETS
#define RETS "..."
Definition at line 246 of file lua-5.2.4/src/lobject.c.
Referenced by luaO_chunkid().
Function Documentation
isneg()
static int isneg (const char ** s) static
Definition at line 98 of file lua-5.2.4/src/lobject.c.
{
  if (**s == '-') { (*s)++; return 1; }
  else if (**s == '+') (*s)++;
  return 0;
}
References s.
Referenced by lua_strx2number().
lua_strx2number()
static lua_Number lua_strx2number (const char * s, char ** endptr) static
Definition at line 118 of file lua-5.2.4/src/lobject.c.
{
  lua_Number r = 0.0;
  int e = 0, i = 0;
  int neg = 0;  /* 1 if number is negative */
  *endptr = cast(char *, s);  /* nothing is valid yet */
  while (lisspace(cast_uchar(*s))) s++;  /* skip initial spaces */
  neg = isneg(&s);  /* check signal */
  if (!(*s == '0' && (*(s + 1) == 'x' || *(s + 1) == 'X')))  /* check '0x' */
    return 0.0;  /* invalid format (no '0x') */
  s += 2;  /* skip '0x' */
  r = readhexa(&s, r, &i);  /* read integer part */
  if (*s == '.') {
    s++;  /* skip dot */
    r = readhexa(&s, r, &e);  /* read fractional part */
  }
  if (i == 0 && e == 0)
    return 0.0;  /* invalid format (no digit) */
  e *= -4;  /* each fractional digit divides value by 2^-4 */
  *endptr = cast(char *, s);  /* valid up to here */
  if (*s == 'p' || *s == 'P') {  /* exponent part? */
    int exp1 = 0;
    int neg1;
    s++;  /* skip 'p' */
    neg1 = isneg(&s);  /* signal */
    if (!lisdigit(cast_uchar(*s)))
      goto ret;  /* must have at least one digit */
    while (lisdigit(cast_uchar(*s)))  /* read exponent */
      exp1 = exp1 * 10 + *(s++) - '0';
    if (neg1) exp1 = -exp1;
    e += exp1;
  }
  *endptr = cast(char *, s);  /* valid up to here */
 ret:
  if (neg) r = -r;
  return l_mathop(ldexp)(r, e);
}
References cast, cast_uchar, exp1(), isneg(), l_mathop, lisdigit, lisspace, readhexa(), and s.
luaO_arith()
lua_Number luaO_arith (int op, lua_Number v1, lua_Number v2)
Definition at line 73 of file lua-5.2.4/src/lobject.c.
{
  switch (op) {
    case LUA_OPADD: return luai_numadd(NULL, v1, v2);
    case LUA_OPSUB: return luai_numsub(NULL, v1, v2);
    case LUA_OPMUL: return luai_nummul(NULL, v1, v2);
    case LUA_OPDIV: return luai_numdiv(NULL, v1, v2);
    case LUA_OPMOD: return luai_nummod(NULL, v1, v2);
    case LUA_OPPOW: return luai_numpow(NULL, v1, v2);
    case LUA_OPUNM: return luai_numunm(NULL, v1);
    default: lua_assert(0); return 0;
  }
}
References lua_assert, LUA_OPADD, LUA_OPDIV, LUA_OPMOD, LUA_OPMUL, LUA_OPPOW, LUA_OPSUB, LUA_OPUNM, luai_numadd, luai_numdiv, luai_nummod, luai_nummul, luai_numpow, luai_numsub, luai_numunm, and NULL.
Referenced by constfolding(), constfolding(), lua_arith(), and luaV_arith().
luaO_ceillog2()
int luaO_ceillog2 (unsigned int x)
Definition at line 55 of file lua-5.2.4/src/lobject.c.
{
  static const lu_byte log_2[256] = {
    0,1,2,2,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
    7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
    7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
  };
  int l = 0;
  x--;
  while (x >= 256) { l += 8; x >>= 8; }
  return l + log_2[x];
}
Referenced by countint(), countint(), countint(), luaK_settablesize(), setnodevector(), setnodevector(), and setnodevector().
luaO_chunkid()
void luaO_chunkid (char * out, const char * source, size_t bufflen)
Definition at line 252 of file lua-5.2.4/src/lobject.c.
{
  size_t l = strlen(source);
  if (*source == '=') {  /* 'literal' source */
    if (l <= bufflen)  /* small enough? */
      memcpy(out, source + 1, l * sizeof(char));
    else {  /* truncate it */
      addstr(out, source + 1, bufflen - 1);
      *out = '\0';
    }
  }
  else if (*source == '@') {  /* file name */
    if (l <= bufflen)  /* small enough? */
      memcpy(out, source + 1, l * sizeof(char));
    else {  /* add '...' before rest of name */
      addstr(out, RETS, LL(RETS));
      bufflen -= LL(RETS);
      memcpy(out, source + 1 + l - bufflen, bufflen * sizeof(char));
    }
  }
  else {  /* string; format as [string "source"] */
    const char *nl = strchr(source, '\n');  /* find first new line (if any) */
    addstr(out, PRE, LL(PRE));  /* add prefix */
    bufflen -= LL(PRE RETS POS) + 1;  /* save space for prefix+suffix+'\0' */
    if (l < bufflen && nl == NULL) {  /* small one-line source? */
      addstr(out, source, l);  /* keep it */
    }
    else {
      if (nl != NULL) l = nl - source;  /* stop at first newline */
      if (l > bufflen) l = bufflen;
      addstr(out, source, l);
      addstr(out, RETS, LL(RETS));
    }
    memcpy(out, POS, (LL(POS) + 1) * sizeof(char));
  }
}
References addstr, bufflen, LL, NULL, POS, PRE, and RETS.
luaO_fb2int()
int luaO_fb2int (int x)
Definition at line 48 of file lua-5.2.4/src/lobject.c.
{
  int e = (x >> 3) & 0x1f;
  if (e == 0) return x;
  else return ((x & 7) + 8) << (e - 1);
}
luaO_hexavalue()
int luaO_hexavalue (int c)
Definition at line 87 of file lua-5.2.4/src/lobject.c.
{
  if (lisdigit(c)) return c - '0';
  else return ltolower(c) - 'a' + 10;
}
References lisdigit, and ltolower.
Referenced by gethexa(), gethexa(), readhexa(), readhexaesc(), readutf8esc(), and readutf8esc().
luaO_int2fb()
int luaO_int2fb (unsigned int x)
Definition at line 36 of file lua-5.2.4/src/lobject.c.
{
  int e = 0;  /* exponent */
  if (x < 8) return x;
  while (x >= 0x10) {
    x = (x+1) >> 1;
    e++;
  }
  return ((e+1) << 3) | (cast_int(x) - 8);
}
References cast_int.
luaO_pushfstring()
const char * luaO_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 233 of file lua-5.2.4/src/lobject.c.
{
  const char *msg;
  va_list argp;
  va_start(argp, fmt);
  msg = luaO_pushvfstring(L, fmt, argp);
  va_end(argp);
  return msg;
}
References luaO_pushvfstring().
luaO_pushvfstring()
const char * luaO_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 179 of file lua-5.2.4/src/lobject.c.
{
  int n = 0;
  for (;;) {
    const char *e = strchr(fmt, '%');
    if (e == NULL) break;
    luaD_checkstack(L, 2);  /* fmt + item */
    pushstr(L, fmt, e - fmt);
    switch (*(e+1)) {
      case 's': {
        const char *s = va_arg(argp, char *);
        if (s == NULL) s = "(null)";
        pushstr(L, s, strlen(s));
        break;
      }
      case 'c': {
        char buff;
        buff = cast(char, va_arg(argp, int));
        pushstr(L, &buff, 1);
        break;
      }
      case 'd': {
        setnvalue(L->top++, cast_num(va_arg(argp, int)));
        break;
      }
      case 'f': {
        setnvalue(L->top++, cast_num(va_arg(argp, l_uacNumber)));
        break;
      }
      case 'p': {
        char buff[4*sizeof(void *) + 8]; /* should be enough space for a `%p' */
        int l = sprintf(buff, "%p", va_arg(argp, void *));
        pushstr(L, buff, l);
        break;
      }
      case '%': {
        pushstr(L, "%", 1);
        break;
      }
      default: {
        luaG_runerror(L,
            "invalid option " LUA_QL("%%%c") " to " LUA_QL("lua_pushfstring"),
            *(e + 1));
      }
    }
    n += 2;
    fmt = e+2;
  }
  luaD_checkstack(L, 1);
  pushstr(L, fmt, strlen(fmt));
  if (n > 0) luaV_concat(L, n + 1);
  return svalue(L->top - 1);
}
References cast, cast_num, LUA_QL, luaD_checkstack, luaG_runerror(), luaV_concat(), NULL, pushstr(), s, setnvalue, svalue, and lua_State::top.
Referenced by luaO_pushfstring().
luaO_str2d()
int luaO_str2d (const char * s, size_t len, lua_Number * result)
Definition at line 158 of file lua-5.2.4/src/lobject.c.
{
  char *endptr;
  if (strpbrk(s, "nN"))  /* reject 'inf' and 'nan' */
    return 0;
  else if (strpbrk(s, "xX"))  /* hexa? */
    *result = lua_strx2number(s, &endptr);
  else
    *result = lua_str2number(s, &endptr);
  if (endptr == s) return 0;  /* nothing recognized */
  while (lisspace(cast_uchar(*endptr))) endptr++;
  return (endptr == s + len);  /* OK if no trailing characters */
}
References cast_uchar, lisspace, lua_str2number, lua_strx2number, and s.
pushstr()
static void pushstr (lua_State * L, const char * str, size_t l) static
Definition at line 173 of file lua-5.2.4/src/lobject.c.
{
  setsvalue2s(L, L->top++, luaS_newlstr(L, str, l));
}
References luaS_newlstr(), setsvalue2s, and lua_State::top.
Referenced by luaO_pushvfstring().
readhexa()
static lua_Number readhexa (const char ** s, lua_Number r, int * count) static
Definition at line 105 of file lua-5.2.4/src/lobject.c.
{
  for (; lisxdigit(cast_uchar(**s)); (*s)++) {  /* read integer part */
    r = (r * cast_num(16.0)) + cast_num(luaO_hexavalue(cast_uchar(**s)));
    (*count)++;
  }
  return r;
}
References cast_num, cast_uchar, lisxdigit, luaO_hexavalue(), and s.
Referenced by lua_strx2number().
Variable Documentation
luaO_nilobject_
LUAI_DDEF const TValue luaO_nilobject_ = {NILCONSTANT}
Definition at line 28 of file lua-5.2.4/src/lobject.c.
{NILCONSTANT};