Github User Fetcher: ltable.h File Reference
ltable.h File Reference
#include "lobject.h"
Macros
#define gnode(t, i) (&(t)->node[i])
#define gkey(n) (&(n)->i_key.tvk)
#define gval(n) (&(n)->i_val)
#define gnext(n) ((n)->i_key.nk.next)
#define invalidateTMcache(t) ((t)->flags = 0)
#define keyfromval(v) (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
Functions
LUAI_FUNC const TValue * luaH_getint (Table *t, int key)
LUAI_FUNC void luaH_setint (lua_State *L, Table *t, int key, TValue *value)
LUAI_FUNC const TValue * luaH_getstr (Table *t, TString *key)
LUAI_FUNC const TValue * luaH_get (Table *t, const TValue *key)
LUAI_FUNC TValue * luaH_newkey (lua_State *L, Table *t, const TValue *key)
LUAI_FUNC TValue * luaH_set (lua_State *L, Table *t, const TValue *key)
LUAI_FUNC Table * luaH_new (lua_State *L)
LUAI_FUNC void luaH_resize (lua_State *L, Table *t, int nasize, int nhsize)
LUAI_FUNC void luaH_resizearray (lua_State *L, Table *t, int nasize)
LUAI_FUNC void luaH_free (lua_State *L, Table *t)
LUAI_FUNC int luaH_next (lua_State *L, Table *t, StkId key)
LUAI_FUNC int luaH_getn (Table *t)
Macro Definition Documentation
gkey
#define gkey (n) (&(n)->i_key.tvk)
Definition at line 14 of file lua-5.2.4/src/ltable.h.
gnext
#define gnext (n) ((n)->i_key.nk.next)
Definition at line 16 of file lua-5.2.4/src/ltable.h.
gnode
#define gnode (t, i) (&(t)->node[i])
Definition at line 13 of file lua-5.2.4/src/ltable.h.
gval
#define gval (n) (&(n)->i_val)
Definition at line 15 of file lua-5.2.4/src/ltable.h.
invalidateTMcache
#define invalidateTMcache (t) ((t)->flags = 0)
Definition at line 18 of file lua-5.2.4/src/ltable.h.
Referenced by aux_rawset(), lua_rawset(), luaV_finishset(), luaV_finishset(), and luaV_settable().
keyfromval
#define keyfromval (v) (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
Definition at line 21 of file lua-5.2.4/src/ltable.h.
#define keyfromval(v) \
  (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
Referenced by luaX_newstring().
Function Documentation
luaH_free()
LUAI_FUNC void luaH_free (lua_State * L, Table * t)
Definition at line 374 of file lua-5.1.5/src/ltable.c.
{
  if (t->node != dummynode)
    luaM_freearray(L, t->node, sizenode(t), Node);
  luaM_freearray(L, t->array, t->sizearray, TValue);
  luaM_free(L, t);
}
luaH_get()
LUAI_FUNC const TValue * luaH_get (Table * t, const TValue * key)
Definition at line 469 of file lua-5.1.5/src/ltable.c.
{
  switch (ttype(key)) {
    case LUA_TNIL: return luaO_nilobject;
    case LUA_TSTRING: return luaH_getstr(t, rawtsvalue(key));
    case LUA_TNUMBER: {
      int k;
      lua_Number n = nvalue(key);
      lua_number2int(k, n);
      if (luai_numeq(cast_num(k), nvalue(key))) /* index is int? */
        return luaH_getnum(t, k);  /* use specialized version */
      /* else go through */
    }
    default: {
      Node *n = mainposition(t, key);
      do {  /* check whether `key' is somewhere in the chain */
        if (luaO_rawequalObj(key2tval(n), key))
          return gval(n);  /* that's it */
        else n = gnext(n);
      } while (n);
      return luaO_nilobject;
    }
  }
}
luaH_getint()
LUAI_FUNC const TValue * luaH_getint (Table * t, int key)
Definition at line 446 of file lua-5.2.4/src/ltable.c.
{
  /* (1 <= key && key <= t->sizearray) */
  if (cast(unsigned int, key-1) < cast(unsigned int, t->sizearray))
    return &t->array[key-1];
  else {
    lua_Number nk = cast_num(key);
    Node *n = hashnum(t, nk);
    do {  /* check whether `key' is somewhere in the chain */
      if (ttisnumber(gkey(n)) && luai_numeq(nvalue(gkey(n)), nk))
        return gval(n);  /* that's it */
      else n = gnext(n);
    } while (n);
    return luaO_nilobject;
  }
}
References Table::array, cast, cast_num, gkey, gnext, gval, hashnum(), luai_numeq, luaO_nilobject, nvalue, Table::sizearray, and ttisnumber.
Referenced by lua_getglobal(), lua_getglobal(), lua_geti(), lua_load(), lua_rawgeti(), lua_rawgeti(), lua_setglobal(), lua_setglobal(), lua_seti(), luaH_get(), luaH_setint(), and unbound_search().
luaH_getn()
LUAI_FUNC int luaH_getn (Table * t)
Definition at line 560 of file lua-5.1.5/src/ltable.c.
{
  unsigned int j = t->sizearray;
  if (j > 0 && ttisnil(&t->array[j - 1])) {
    /* there is a boundary in the array part: (binary) search for it */
    unsigned int i = 0;
    while (j - i > 1) {
      unsigned int m = (i+j)/2;
      if (ttisnil(&t->array[m - 1])) j = m;
      else i = m;
    }
    return i;
  }
  /* else must find a boundary in hash part */
  else if (t->node == dummynode)  /* hash part is empty? */
    return j;  /* that is easy... */
  else return unbound_search(t, j);
}
luaH_getstr()
LUAI_FUNC const TValue * luaH_getstr (Table * t, TString * key)
Definition at line 455 of file lua-5.1.5/src/ltable.c.
{
  Node *n = hashstr(t, key);
  do {  /* check whether `key' is somewhere in the chain */
    if (ttisstring(gkey(n)) && rawtsvalue(gkey(n)) == key)
      return gval(n);  /* that's it */
    else n = gnext(n);
  } while (n);
  return luaO_nilobject;
}
luaH_new()
LUAI_FUNC Table * luaH_new (lua_State * L)
Definition at line 368 of file lua-5.2.4/src/ltable.c.
{
  Table *t = &luaC_newobj(L, LUA_TTABLE, sizeof(Table), NULL, 0)->h;
  t->metatable = NULL;
  t->flags = cast_byte(~0);
  t->array = NULL;
  t->sizearray = 0;
  setnodevector(L, t, 0);
  return t;
}
luaH_newkey()
LUAI_FUNC TValue * luaH_newkey (lua_State * L, Table * t, const TValue * key)
Definition at line 405 of file lua-5.2.4/src/ltable.c.
{
  Node *mp;
  if (ttisnil(key)) luaG_runerror(L, "table index is nil");
  else if (ttisnumber(key) && luai_numisnan(L, nvalue(key)))
    luaG_runerror(L, "table index is NaN");
  mp = mainposition(t, key);
  if (!ttisnil(gval(mp)) || isdummy(mp)) {  /* main position is taken? */
    Node *othern;
    Node *n = getfreepos(t);  /* get a free place */
    if (n == NULL) {  /* cannot find a free place? */
      rehash(L, t, key);  /* grow table */
      /* whatever called 'newkey' take care of TM cache and GC barrier */
      return luaH_set(L, t, key);  /* insert key into grown table */
    }
    lua_assert(!isdummy(n));
    othern = mainposition(t, gkey(mp));
    if (othern != mp) {  /* is colliding node out of its main position? */
      /* yes; move colliding node into free position */
      while (gnext(othern) != mp) othern = gnext(othern);  /* find previous */
      gnext(othern) = n;  /* redo the chain with `n' in place of `mp' */
      *n = *mp;  /* copy colliding node into free pos. (mp->next also goes) */
      gnext(mp) = NULL;  /* now `mp' is free */
      setnilvalue(gval(mp));
    }
    else {  /* colliding node is in its own main position */
      /* new node will go into free position */
      gnext(n) = gnext(mp);  /* chain new position */
      gnext(mp) = n;
      mp = n;
    }
  }
  setobj2t(L, gkey(mp), key);
  luaC_barrierback(L, obj2gco(t), key);
  lua_assert(ttisnil(gval(mp)));
  return gval(mp);
}
luaH_next()
LUAI_FUNC int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 162 of file lua-5.1.5/src/ltable.c.
{
  int i = findindex(L, t, key);  /* find original element */
  for (i++; i < t->sizearray; i++) {  /* try first array part */
    if (!ttisnil(&t->array[i])) {  /* a non-nil value? */
      setnvalue(key, cast_num(i+1));
      setobj2s(L, key+1, &t->array[i]);
      return 1;
    }
  }
  for (i -= t->sizearray; i < sizenode(t); i++) {  /* then hash part */
    if (!ttisnil(gval(gnode(t, i)))) {  /* a non-nil value? */
      setobj2s(L, key, key2tval(gnode(t, i)));
      setobj2s(L, key+1, gval(gnode(t, i)));
      return 1;
    }
  }
  return 0;  /* no more elements */
}
luaH_resize()
LUAI_FUNC void luaH_resize (lua_State * L, Table * t, int nasize, int nhsize)
Definition at line 304 of file lua-5.2.4/src/ltable.c.
{
  int i;
  int oldasize = t->sizearray;
  int oldhsize = t->lsizenode;
  Node *nold = t->node;  /* save old hash ... */
  if (nasize > oldasize)  /* array part must grow? */
    setarrayvector(L, t, nasize);
  /* create new hash part with appropriate size */
  setnodevector(L, t, nhsize);
  if (nasize < oldasize) {  /* array part must shrink? */
    t->sizearray = nasize;
    /* re-insert elements from vanishing slice */
    for (i=nasize; i<oldasize; i++) {
      if (!ttisnil(&t->array[i]))
        luaH_setint(L, t, i + 1, &t->array[i]);
    }
    /* shrink array */
    luaM_reallocvector(L, t->array, oldasize, nasize, TValue);
  }
  /* re-insert elements from hash part */
  for (i = twoto(oldhsize) - 1; i >= 0; i--) {
    Node *old = nold+i;
    if (!ttisnil(gval(old))) {
      /* doesn't need barrier/invalidate cache, as entry was
         already present in the table */
      setobjt2t(L, luaH_set(L, t, gkey(old)), gval(old));
    }
  }
  if (!isdummy(nold))
    luaM_freearray(L, nold, cast(size_t, twoto(oldhsize))); /* free old array */
}
References Table::array, cast, gkey, gval, isdummy, Table::lsizenode, luaH_set(), luaH_setint(), luaM_freearray, luaM_reallocvector, Table::node, setarrayvector(), setnodevector(), setobjt2t, Table::sizearray, ttisnil, and twoto.
Referenced by init_registry(), init_registry(), init_registry(), lua_createtable(), luaH_resizearray(), luaV_execute(), luaV_execute(), and rehash().
luaH_resizearray()
LUAI_FUNC void luaH_resizearray (lua_State * L, Table * t, int nasize)
Definition at line 327 of file lua-5.1.5/src/ltable.c.
{
  int nsize = (t->node == dummynode) ? 0 : sizenode(t);
  resize(L, t, nasize, nsize);
}
References dummynode, isdummy, luaH_resize(), Table::node, resize(), and sizenode.
Referenced by luaV_execute(), luaV_execute(), and luaV_execute().
luaH_set()
LUAI_FUNC TValue * luaH_set (lua_State * L, Table * t, const TValue * key)
Definition at line 494 of file lua-5.1.5/src/ltable.c.
{
  const TValue *p = luaH_get(t, key);
  t->flags = 0;
  if (p != luaO_nilobject)
    return cast(TValue *, p);
  else {
    if (ttisnil(key)) luaG_runerror(L, "table index is nil");
    else if (ttisnumber(key) && luai_numisnan(nvalue(key)))
      luaG_runerror(L, "table index is NaN");
    return newkey(L, t, key);
  }
}
luaH_setint()
LUAI_FUNC void luaH_setint (lua_State * L, Table * t, int key, TValue * value)
Definition at line 518 of file lua-5.2.4/src/ltable.c.
{
  const TValue *p = luaH_getint(t, key);
  TValue *cell;
  if (p != luaO_nilobject)
    cell = cast(TValue *, p);
  else {
    TValue k;
    setnvalue(&k, cast_num(key));
    cell = luaH_newkey(L, t, &k);
  }
  setobj2t(L, cell, value);
}
References cast, cast_num, luaH_getint(), luaH_newkey(), luaO_nilobject, setnvalue, setobj2t, and value.
Referenced by collectvalidlines(), collectvalidlines(), collectvalidlines(), init_registry(), init_registry(), lua_rawseti(), lua_rawseti(), luaH_resize(), and luaV_execute().