Github User Fetcher: lauxlib.c File Reference
lauxlib.c File Reference
#include <ctype.h>
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
Data Structures
struct LoadF
struct LoadS
Macros
#define lauxlib_c
#define LUA_LIB
#define FREELIST_REF 0 /* free list of references */
#define abs_index(L, i)
#define bufflen(B) ((B)->p - (B)->buffer)
#define bufffree(B) ((size_t)(LUAL_BUFFERSIZE - bufflen(B)))
#define LIMIT (LUA_MINSTACK/2)
Typedefs
typedef struct LoadF LoadF
typedef struct LoadS LoadS
Functions
LUALIB_API int luaL_argerror (lua_State *L, int narg, const char *extramsg)
LUALIB_API int luaL_typerror (lua_State *L, int narg, const char *tname)
static void tag_error (lua_State *L, int narg, int tag)
LUALIB_API void luaL_where (lua_State *L, int level)
LUALIB_API int luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int luaL_checkoption (lua_State *L, int narg, const char *def, const char *const lst[])
LUALIB_API int luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void * luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API void luaL_checkstack (lua_State *L, int space, const char *mes)
LUALIB_API void luaL_checktype (lua_State *L, int narg, int t)
LUALIB_API void luaL_checkany (lua_State *L, int narg)
LUALIB_API const char * luaL_checklstring (lua_State *L, int narg, size_t *len)
LUALIB_API const char * luaL_optlstring (lua_State *L, int narg, const char *def, size_t *len)
LUALIB_API lua_Number luaL_checknumber (lua_State *L, int narg)
LUALIB_API lua_Number luaL_optnumber (lua_State *L, int narg, lua_Number def)
LUALIB_API lua_Integer luaL_checkinteger (lua_State *L, int narg)
LUALIB_API lua_Integer luaL_optinteger (lua_State *L, int narg, lua_Integer def)
LUALIB_API int luaL_getmetafield (lua_State *L, int obj, const char *event)
LUALIB_API int luaL_callmeta (lua_State *L, int obj, const char *event)
LUALIB_API void luaL_register (lua_State *L, const char *libname, const luaL_Reg *l)
static int libsize (const luaL_Reg *l)
LUALIB_API void luaI_openlib (lua_State *L, const char *libname, const luaL_Reg *l, int nup)
LUALIB_API const char * luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
LUALIB_API const char * luaL_findtable (lua_State *L, int idx, const char *fname, int szhint)
static int emptybuffer (luaL_Buffer *B)
static void adjuststack (luaL_Buffer *B)
LUALIB_API char * luaL_prepbuffer (luaL_Buffer *B)
LUALIB_API void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void luaL_pushresult (luaL_Buffer *B)
LUALIB_API void luaL_addvalue (luaL_Buffer *B)
LUALIB_API void luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API int luaL_ref (lua_State *L, int t)
LUALIB_API void luaL_unref (lua_State *L, int t, int ref)
static const char * getF (lua_State *L, void *ud, size_t *size)
static int errfile (lua_State *L, const char *what, int fnameindex)
LUALIB_API int luaL_loadfile (lua_State *L, const char *filename)
static const char * getS (lua_State *L, void *ud, size_t *size)
LUALIB_API int luaL_loadbuffer (lua_State *L, const char *buff, size_t size, const char *name)
LUALIB_API int luaL_loadstring (lua_State *L, const char *s)
static void * l_alloc (void *ud, void *ptr, size_t osize, size_t nsize)
static int panic (lua_State *L)
LUALIB_API lua_State * luaL_newstate (void)
Macro Definition Documentation
abs_index
#define abs_index (L, i)
Value:
                    ((i) > 0 || (i) <= LUA_REGISTRYINDEX ? (i) : \
                    lua_gettop(L) + (i) + 1)
Definition at line 32 of file lua-5.1.5/src/lauxlib.c.
#define abs_index(L, i)     ((i) > 0 || (i) <= LUA_REGISTRYINDEX ? (i) : \
                    lua_gettop(L) + (i) + 1)
Referenced by luaL_callmeta(), luaL_ref(), and luaL_unref().
bufffree
#define bufffree (B) ((size_t)(LUAL_BUFFERSIZE - bufflen(B)))
Definition at line 393 of file lua-5.1.5/src/lauxlib.c.
Referenced by luaL_addvalue().
bufflen
#define bufflen (B) ((B)->p - (B)->buffer)
Definition at line 392 of file lua-5.1.5/src/lauxlib.c.
Referenced by emptybuffer(), luaO_chunkid(), and luaO_chunkid().
FREELIST_REF
#define FREELIST_REF 0 /* free list of references */
Definition at line 28 of file lua-5.1.5/src/lauxlib.c.
Referenced by luaL_ref(), and luaL_unref().
lauxlib_c
#define lauxlib_c
Definition at line 20 of file lua-5.1.5/src/lauxlib.c.
LIMIT
#define LIMIT (LUA_MINSTACK/2)
Definition at line 395 of file lua-5.1.5/src/lauxlib.c.
Referenced by adjuststack().
LUA_LIB
#define LUA_LIB
Definition at line 21 of file lua-5.1.5/src/lauxlib.c.
Typedef Documentation
LoadF
typedef struct LoadF LoadF
LoadS
typedef struct LoadS LoadS
Function Documentation
adjuststack()
static void adjuststack (luaL_Buffer * B) static
Definition at line 410 of file lua-5.1.5/src/lauxlib.c.
{
  if (B->lvl > 1) {
    lua_State *L = B->L;
    int toget = 1;  /* number of levels to concat */
    size_t toplen = lua_strlen(L, -1);
    do {
      size_t l = lua_strlen(L, -(toget+1));
      if (B->lvl - toget + 1 >= LIMIT || toplen > l) {
        toplen += l;
        toget++;
      }
      else break;
    } while (toget < B->lvl);
    lua_concat(L, toget);
    B->lvl = B->lvl - toget + 1;
  }
}
References luaL_Buffer::L, LIMIT, lua_concat(), lua_strlen, and luaL_Buffer::lvl.
Referenced by luaL_addvalue(), and luaL_prepbuffer().
emptybuffer()
static int emptybuffer (luaL_Buffer * B) static
Definition at line 398 of file lua-5.1.5/src/lauxlib.c.
{
  size_t l = bufflen(B);
  if (l == 0) return 0;  /* put nothing on stack */
  else {
    lua_pushlstring(B->L, B->buffer, l);
    B->p = B->buffer;
    B->lvl++;
    return 1;
  }
}
References luaL_Buffer::buffer, bufflen, luaL_Buffer::L, lua_pushlstring(), luaL_Buffer::lvl, and luaL_Buffer::p.
Referenced by luaL_addvalue(), luaL_prepbuffer(), and luaL_pushresult().
errfile()
static int errfile (lua_State * L, const char * what, int fnameindex) static
Definition at line 543 of file lua-5.1.5/src/lauxlib.c.
{
  const char *serr = strerror(errno);
  const char *filename = lua_tostring(L, fnameindex) + 1;
  lua_pushfstring(L, "cannot %s %s: %s", what, filename, serr);
  lua_remove(L, fnameindex);
  return LUA_ERRFILE;
}
References LUA_ERRFILE, lua_pushfstring(), lua_remove, and lua_tostring.
Referenced by luaL_loadfile().
getF()
static const char * getF (lua_State * L, void * ud, size_t * size) static
Definition at line 529 of file lua-5.1.5/src/lauxlib.c.
{
  LoadF *lf = (LoadF *)ud;
  (void)L;
  if (lf->extraline) {
    lf->extraline = 0;
    *size = 1;
    return "\n";
  }
  if (feof(lf->f)) return NULL;
  *size = fread(lf->buff, 1, sizeof(lf->buff), lf->f);
  return (*size > 0) ? lf->buff : NULL;
}
References LoadF::buff, LoadF::extraline, LoadF::f, fread(), and NULL.
Referenced by luaL_loadfile().
getS()
static const char * getS (lua_State * L, void * ud, size_t * size) static
Definition at line 599 of file lua-5.1.5/src/lauxlib.c.
{
  LoadS *ls = (LoadS *)ud;
  (void)L;
  if (ls->size == 0) return NULL;
  *size = ls->size;
  ls->size = 0;
  return ls->s;
}
References NULL, LoadS::s, and LoadS::size.
Referenced by luaL_loadbuffer().
l_alloc()
static void * l_alloc (void * ud, void * ptr, size_t osize, size_t nsize) static
Definition at line 627 of file lua-5.1.5/src/lauxlib.c.
{
  (void)ud;
  (void)osize;
  if (nsize == 0) {
    free(ptr);
    return NULL;
  }
  else
    return realloc(ptr, nsize);
}
References free, NULL, and realloc.
Referenced by luaL_newstate().
libsize()
static int libsize (const luaL_Reg * l) static
Definition at line 235 of file lua-5.1.5/src/lauxlib.c.
{
  int size = 0;
  for (; l->name; l++) size++;
  return size;
}
References luaL_Reg::name.
Referenced by luaI_openlib().
luaI_openlib()
LUALIB_API void luaI_openlib (lua_State * L, const char * libname, const luaL_Reg * l, int nup)
Definition at line 242 of file lua-5.1.5/src/lauxlib.c.
{
  if (libname) {
    int size = libsize(l);
    /* check whether lib already exists */
    luaL_findtable(L, LUA_REGISTRYINDEX, "_LOADED", 1);
    lua_getfield(L, -1, libname);  /* get _LOADED[libname] */
    if (!lua_istable(L, -1)) {  /* not found? */
      lua_pop(L, 1);  /* remove previous result */
      /* try global variable (and create one if it does not exist) */
      if (luaL_findtable(L, LUA_GLOBALSINDEX, libname, size) != NULL)
        luaL_error(L, "name conflict for module " LUA_QS, libname);
      lua_pushvalue(L, -1);
      lua_setfield(L, -3, libname);  /* _LOADED[libname] = new table */
    }
    lua_remove(L, -2);  /* remove _LOADED table */
    lua_insert(L, -(nup+1));  /* move library table to below upvalues */
  }
  for (; l->name; l++) {
    int i;
    for (i=0; i<nup; i++)  /* copy upvalues to the top */
      lua_pushvalue(L, -nup);
    lua_pushcclosure(L, l->func, nup);
    lua_setfield(L, -(nup+2), l->name);
  }
  lua_pop(L, nup);  /* remove upvalues */
}
References luaL_Reg::func, libsize(), lua_getfield(), LUA_GLOBALSINDEX, lua_insert, lua_istable, lua_pop, lua_pushcclosure(), lua_pushvalue(), LUA_QS, LUA_REGISTRYINDEX, lua_remove, lua_setfield(), luaL_error(), luaL_findtable(), luaL_Reg::name, and NULL.
luaL_addlstring()
LUALIB_API void luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 436 of file lua-5.1.5/src/lauxlib.c.
{
  while (l--)
    luaL_addchar(B, *s++);
}
References luaL_addchar, and s.
Referenced by add_s(), add_s(), add_s(), add_s(), add_value(), addquoted(), b_pack(), luaL_addstring(), luaL_gsub(), os_date(), os_date(), putinteger(), setpath(), str_format(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), str_pack(), str_pack(), str_rep(), tconcat(), tconcat(), tconcat(), tconcat(), writer(), writer(), writer(), writer(), Xml_pushEncode(), and Xml_str().
luaL_addstring()
LUALIB_API void luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 442 of file lua-5.1.5/src/lauxlib.c.
{
  luaL_addlstring(B, s, strlen(s));
}
References luaL_addlstring(), and s.
Referenced by addquoted(), addquoted(), addquoted(), findloader(), luaL_gsub(), pusherrornotfound(), setpath(), and Xml_str().
luaL_addvalue()
LUALIB_API void luaL_addvalue (luaL_Buffer * B)
Definition at line 454 of file lua-5.1.5/src/lauxlib.c.
{
  lua_State *L = B->L;
  size_t vl;
  const char *s = lua_tolstring(L, -1, &vl);
  if (vl <= bufffree(B)) {  /* fit into buffer? */
    memcpy(B->p, s, vl);  /* put it there */
    B->p += vl;
    lua_pop(L, 1);  /* remove from stack */
  }
  else {
    if (emptybuffer(B))
      lua_insert(L, -2);  /* put buffer before new value */
    B->lvl++;  /* add new value into B stack */
    adjuststack(B);
  }
}
References adjuststack(), bufffree, emptybuffer(), luaL_Buffer::L, lua_insert, lua_pop, lua_tolstring(), luaL_Buffer::lvl, luaL_Buffer::p, and s.
Referenced by add_s(), add_s(), add_s(), add_s(), add_value(), add_value(), add_value(), add_value(), addfield(), addfield(), addfield(), addfield(), addliteral(), addliteral(), findloader(), findloader(), findloader(), searchpath(), searchpath(), str_format(), str_format(), str_format(), str_format(), utfchar(), utfchar(), and Xml_str().
luaL_argerror()
LUALIB_API int luaL_argerror (lua_State * L, int narg, const char * extramsg)
Definition at line 43 of file lua-5.1.5/src/lauxlib.c.
{
  lua_Debug ar;
  if (!lua_getstack(L, 0, &ar))  /* no stack frame? */
    return luaL_error(L, "bad argument #%d (%s)", narg, extramsg);
  lua_getinfo(L, "n", &ar);
  if (strcmp(ar.namewhat, "method") == 0) {
    narg--;  /* do not count `self' */
    if (narg == 0)  /* error is in the self argument itself? */
      return luaL_error(L, "calling " LUA_QS " on bad self (%s)",
                           ar.name, extramsg);
  }
  if (ar.name == NULL)
    ar.name = "?";
  return luaL_error(L, "bad argument #%d to " LUA_QS " (%s)",
                        narg, ar.name, extramsg);
}
References lua_getinfo(), lua_getstack(), LUA_QS, luaL_error(), lua_Debug::name, lua_Debug::namewhat, and NULL.
Referenced by addliteral(), addliteral(), b_size(), checkoption(), checkoption(), checkoption(), controloptions(), db_getinfo(), db_getinfo(), db_getinfo(), db_getinfo(), db_getlocal(), db_getlocal(), db_getlocal(), db_getlocal(), db_setlocal(), db_setlocal(), db_setlocal(), db_setlocal(), db_setuservalue(), fileerror(), g_read(), g_read(), g_read(), g_read(), getdetails(), getdetails(), getfunc(), lsqlite_checkbu(), lsqlite_checkcontext(), lsqlite_checkdb(), lsqlite_checkvm(), lsqlite_getvm(), lsqlite_open_ptr(), luaL_checkany(), luaL_checkoption(), luaL_typerror(), str_format(), str_format(), str_format(), str_format(), str_packsize(), and str_unpack().
luaL_buffinit()
LUALIB_API void luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 472 of file lua-5.1.5/src/lauxlib.c.
{
  B->L = L;
  B->p = B->buffer;
  B->lvl = 0;
}
References luaL_Buffer::buffer, luaL_Buffer::L, luaL_Buffer::lvl, and luaL_Buffer::p.
Referenced by b_pack(), findloader(), findloader(), findloader(), luaL_gsub(), os_date(), os_date(), os_date(), os_date(), push_indentStr(), pusherrornotfound(), read_all(), read_all(), read_all(), read_chars(), read_chars(), read_chars(), read_chars(), read_line(), read_line(), read_line(), read_line(), searchpath(), searchpath(), searchpath(), setpath(), str_char(), str_dump(), str_dump(), str_dump(), str_format(), str_format(), str_format(), str_format(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), str_lower(), str_pack(), str_pack(), str_rep(), str_reverse(), str_upper(), tconcat(), tconcat(), tconcat(), tconcat(), utfchar(), utfchar(), writer(), Xml_pushEncode(), and Xml_str().
luaL_callmeta()
LUALIB_API int luaL_callmeta (lua_State * L, int obj, const char * event)
Definition at line 219 of file lua-5.1.5/src/lauxlib.c.
{
  obj = abs_index(L, obj);
  if (!luaL_getmetafield(L, obj, event))  /* no metafield? */
    return 0;
  lua_pushvalue(L, obj);
  lua_call(L, 1, 1);
  return 1;
}
References abs_index, lua_call, lua_pushvalue(), and luaL_getmetafield().
Referenced by luaB_tostring(), msghandler(), msghandler(), and traceback().
luaL_checkany()
LUALIB_API void luaL_checkany (lua_State * L, int narg)
Definition at line 152 of file lua-5.1.5/src/lauxlib.c.
{
  if (lua_type(L, narg) == LUA_TNONE)
    luaL_argerror(L, narg, "value expected");
}
References LUA_TNONE, lua_type(), and luaL_argerror().
Referenced by db_getfenv(), db_getmetatable(), db_getmetatable(), db_getmetatable(), db_getmetatable(), db_setlocal(), db_setlocal(), db_setlocal(), db_setlocal(), db_setupvalue(), db_setupvalue(), db_setupvalue(), db_setupvalue(), db_setuservalue(), db_setuservalue(), io_type(), io_type(), io_type(), io_type(), luaB_assert(), luaB_assert(), luaB_assert(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_ipairs(), luaB_ipairs(), luaB_pairs(), luaB_pcall(), luaB_pcall(), luaB_pcall(), luaB_pcall(), luaB_rawequal(), luaB_rawequal(), luaB_rawequal(), luaB_rawequal(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_tonumber(), luaB_tonumber(), luaB_tonumber(), luaB_tonumber(), luaB_tostring(), luaB_tostring(), luaB_tostring(), luaB_tostring(), luaB_type(), luaB_type(), luaB_xpcall(), math_toint(), math_toint(), math_type(), math_type(), and pairsmeta().
luaL_checkinteger()
LUALIB_API lua_Integer luaL_checkinteger (lua_State * L, int narg)
Definition at line 189 of file lua-5.1.5/src/lauxlib.c.
{
  lua_Integer d = lua_tointeger(L, narg);
  if (d == 0 && !lua_isnumber(L, narg))  /* avoid extra test when d is not 0 */
    tag_error(L, narg, LUA_TNUMBER);
  return d;
}
References lua_isnumber(), LUA_TNUMBER, lua_tointeger, and tag_error().
Referenced by auxupvalue(), auxupvalue(), byteoffset(), byteoffset(), checkupval(), checkupval(), db_getinfo(), db_getinfo(), db_getlocal(), db_getlocal(), db_setcstacklimit(), db_setlocal(), db_setlocal(), g_read(), g_read(), ipairsaux(), ipairsaux(), l_checktime(), lcontext_result(), luaB_select(), luaB_select(), luaB_tonumber(), luaB_tonumber(), luaL_optinteger(), math_random(), math_random(), math_randomseed(), math_ult(), math_ult(), pushutfchar(), pushutfchar(), str_char(), str_char(), str_format(), str_format(), str_pack(), str_pack(), str_rep(), str_rep(), str_sub(), str_sub(), str_sub(), str_sub(), tinsert(), tinsert(), tmove(), tmove(), tunpack(), and unpack().
luaL_checklstring()
LUALIB_API const char * luaL_checklstring (lua_State * L, int narg, size_t * len)
Definition at line 158 of file lua-5.1.5/src/lauxlib.c.
{
  const char *s = lua_tolstring(L, narg, len);
  if (!s) tag_error(L, narg, LUA_TSTRING);
  return s;
}
References lua_tolstring(), LUA_TSTRING, s, and tag_error().
Referenced by addquoted(), addquoted(), b_pack(), b_unpack(), byteoffset(), byteoffset(), codepoint(), codepoint(), g_write(), g_write(), g_write(), g_write(), gmatch(), gmatch(), iter_aux(), iter_aux(), lfs_lock_dir(), luaB_loadstring(), luaB_tonumber(), luaL_optlstring(), str_byte(), str_byte(), str_byte(), str_byte(), str_find_aux(), str_find_aux(), str_find_aux(), str_find_aux(), str_format(), str_format(), str_format(), str_format(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), str_len(), str_len(), str_len(), str_len(), str_lower(), str_lower(), str_lower(), str_lower(), str_pack(), str_pack(), str_rep(), str_rep(), str_rep(), str_rep(), str_reverse(), str_reverse(), str_reverse(), str_reverse(), str_sub(), str_sub(), str_sub(), str_sub(), str_unpack(), str_unpack(), str_upper(), str_upper(), str_upper(), str_upper(), utflen(), utflen(), Xml_decode(), and Xml_eval().
luaL_checknumber()
LUALIB_API lua_Number luaL_checknumber (lua_State * L, int narg)
Definition at line 176 of file lua-5.1.5/src/lauxlib.c.
{
  lua_Number d = lua_tonumber(L, narg);
  if (d == 0 && !lua_isnumber(L, narg))  /* avoid extra test when d is not 0 */
    tag_error(L, narg, LUA_TNUMBER);
  return d;
}
References lua_isnumber(), LUA_TNUMBER, lua_tonumber, and tag_error().
Referenced by b_pack(), dbvm_bind_parameter_name(), dbvm_get_name(), dbvm_get_type(), lcontext_result(), lcontext_result_double(), luaL_optnumber(), math_abs(), math_abs(), math_abs(), math_abs(), math_acos(), math_acos(), math_acos(), math_acos(), math_asin(), math_asin(), math_asin(), math_asin(), math_atan(), math_atan(), math_atan(), math_atan(), math_atan2(), math_atan2(), math_ceil(), math_ceil(), math_ceil(), math_ceil(), math_cos(), math_cos(), math_cos(), math_cos(), math_cosh(), math_cosh(), math_deg(), math_deg(), math_deg(), math_deg(), math_exp(), math_exp(), math_exp(), math_exp(), math_floor(), math_floor(), math_floor(), math_floor(), math_fmod(), math_fmod(), math_fmod(), math_fmod(), math_frexp(), math_frexp(), math_ldexp(), math_ldexp(), math_log(), math_log(), math_log(), math_log(), math_log10(), math_max(), math_max(), math_min(), math_min(), math_modf(), math_modf(), math_modf(), math_modf(), math_pow(), math_pow(), math_rad(), math_rad(), math_rad(), math_rad(), math_random(), math_randomseed(), math_sin(), math_sin(), math_sin(), math_sin(), math_sinh(), math_sinh(), math_sqrt(), math_sqrt(), math_sqrt(), math_sqrt(), math_tan(), math_tan(), math_tan(), math_tan(), math_tanh(), math_tanh(), os_date(), os_date(), os_difftime(), os_difftime(), putinteger(), str_format(), str_format(), str_format(), str_format(), str_pack(), and str_pack().
luaL_checkoption()
LUALIB_API int luaL_checkoption (lua_State * L, int narg, const char * def, const char *const lst[])
Definition at line 99 of file lua-5.1.5/src/lauxlib.c.
{
  const char *name = (def) ? luaL_optstring(L, narg, def) :
                             luaL_checkstring(L, narg);
  int i;
  for (i=0; lst[i]; i++)
    if (strcmp(lst[i], name) == 0)
      return i;
  return luaL_argerror(L, narg,
                       lua_pushfstring(L, "invalid option " LUA_QS, name));
}
References lua_pushfstring(), LUA_QS, luaL_argerror(), luaL_checkstring, luaL_optstring, and name.
Referenced by f_seek(), f_seek(), f_seek(), f_seek(), f_setvbuf(), f_setvbuf(), f_setvbuf(), f_setvbuf(), lfs_g_setmode(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), os_setlocale(), os_setlocale(), os_setlocale(), and os_setlocale().
luaL_checkstack()
LUALIB_API void luaL_checkstack (lua_State * L, int space, const char * mes)
Definition at line 140 of file lua-5.1.5/src/lauxlib.c.
{
  if (!lua_checkstack(L, space))
    luaL_error(L, "stack overflow (%s)", mes);
}
References lua_checkstack(), and luaL_error().
Referenced by b_unpack(), codepoint(), codepoint(), dotty(), g_read(), g_read(), g_read(), g_read(), generic_reader(), generic_reader(), generic_reader(), generic_reader(), getargs(), getargs(), io_readline(), io_readline(), l_print(), l_print(), push_captures(), push_captures(), push_captures(), push_captures(), pushargs(), pushargs(), sort(), sort(), str_byte(), str_byte(), str_byte(), str_byte(), str_unpack(), and str_unpack().
luaL_checktype()
LUALIB_API void luaL_checktype (lua_State * L, int narg, int t)
Definition at line 146 of file lua-5.1.5/src/lauxlib.c.
{
  if (lua_type(L, narg) != t)
    tag_error(L, narg, t);
}
References lua_type(), and tag_error().
Referenced by auxupvalue(), auxupvalue(), auxupvalue(), auxupvalue(), checktab(), checktab(), checkupval(), checkupval(), checkupval(), db_busy_handler(), db_commit_hook(), db_exec(), db_progress_handler(), db_register_function(), db_rollback_hook(), db_setfenv(), db_sethook(), db_sethook(), db_sethook(), db_sethook(), db_setuservalue(), db_setuservalue(), db_setuservalue(), db_trace(), db_update_hook(), dbvm_bind_names(), foreach(), foreachi(), ipairsaux(), ipairsaux(), ll_seeall(), lsqlite_open_ptr(), luaB_cocreate(), luaB_cocreate(), luaB_cocreate(), luaB_ipairs(), luaB_load(), luaB_load(), luaB_load(), luaB_load(), luaB_next(), luaB_next(), luaB_next(), luaB_next(), luaB_pairs(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_setfenv(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_tonumber(), luaB_tonumber(), luaB_unpack(), luaB_xpcall(), luaB_xpcall(), maxn(), os_time(), os_time(), os_time(), os_time(), pairsmeta(), setn(), sort(), sort(), sort(), sort(), str_dump(), str_dump(), str_dump(), str_dump(), tconcat(), tconcat(), unpack(), and Xml_iterate().
luaL_checkudata()
LUALIB_API void * luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 124 of file lua-5.1.5/src/lauxlib.c.
{
  void *p = lua_touserdata(L, ud);
  if (p != NULL) {  /* value is a userdata? */
    if (lua_getmetatable(L, ud)) {  /* does it have a metatable? */
      lua_getfield(L, LUA_REGISTRYINDEX, tname);  /* get correct metatable */
      if (lua_rawequal(L, -1, -2)) {  /* does it have the correct mt? */
        lua_pop(L, 2);  /* remove both metatables */
        return p;
      }
    }
  }
  luaL_typerror(L, ud, tname);  /* else error */
  return NULL;  /* to avoid warnings */
}
References lua_getfield(), lua_getmetatable(), lua_pop, lua_rawequal(), LUA_REGISTRYINDEX, lua_touserdata(), luaL_typerror(), and NULL.
Referenced by check_file(), dir_iter(), gctm(), lfs_unlock_dir(), lsqlite_getbu(), lsqlite_getcontext(), lsqlite_getdb(), and lsqlite_getvm().
luaL_error()
LUALIB_API int luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 86 of file lua-5.1.5/src/lauxlib.c.
{
  va_list argp;
  va_start(argp, fmt);
  luaL_where(L, 1);
  lua_pushvfstring(L, fmt, argp);
  va_end(argp);
  lua_concat(L, 2);
  return lua_error(L);
}
References lua_concat(), lua_error(), lua_pushvfstring(), and luaL_where().
Referenced by _file_info_(), _file_lock(), add_s(), add_s(), add_s(), add_value(), add_value(), add_value(), add_value(), addfield(), addfield(), addfield(), addfield(), auxresume(), auxsort(), auxsort(), b_unpack(), byteoffset(), byteoffset(), capture_to_close(), capture_to_close(), capture_to_close(), capture_to_close(), check_capture(), check_capture(), check_capture(), check_capture(), check_file(), checkload(), checkload(), checkload(), checkstack(), checkstack(), checkstack(), classend(), classend(), classend(), classend(), codepoint(), codepoint(), controloptions(), db_create_collation(), db_register_function(), db_setfenv(), dbvm_bind_index(), dbvm_bind_values(), dbvm_check_bind_index(), dbvm_check_contents(), dbvm_check_index(), dir_iter_factory(), fieldargs(), findfile(), findfile(), findfile(), findfile(), findloader(), findloader(), findloader(), generic_reader(), generic_reader(), generic_reader(), generic_reader(), get_onecapture(), getfield(), getfield(), getfield(), getfield(), getfunc(), getiofile(), getiofile(), getiofile(), getiofile(), getnumlimit(), getnumlimit(), getoption(), getoption(), gfind_nodef(), io_readline(), io_readline(), io_readline(), io_readline(), iter_aux(), iter_aux(), lcontext_check_aggregate(), lcontext_result(), ll_module(), ll_require(), loader_preload(), loaderror(), lstop(), lstop(), lstop(), lstop(), luaB_assert(), luaB_assert(), luaB_close(), luaB_print(), luaB_print(), luaB_print(), luaB_setfenv(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_unpack(), luaI_openlib(), luaL_argerror(), luaL_checkstack(), luaopen_bit32(), make_xml_object(), match(), match(), match(), match(), matchbalance(), matchbalance(), matchbalance(), matchbalance(), math_random(), math_random(), math_random(), math_random(), opencheck(), opencheck(), opencheck(), optsize(), os_date(), os_date(), os_time(), os_time(), os_tmpname(), os_tmpname(), os_tmpname(), os_tmpname(), partition(), partition(), push_onecapture(), push_onecapture(), push_onecapture(), pushargs(), pushargs(), scanformat(), scanformat(), scanformat(), scanformat(), setfenv(), setfield(), setn(), start_capture(), start_capture(), start_capture(), start_capture(), str_byte(), str_byte(), str_byte(), str_byte(), str_dump(), str_dump(), str_dump(), str_dump(), str_format(), str_format(), str_format(), str_format(), str_rep(), str_rep(), str_rep(), tinsert(), tinsert(), tinsert(), tinsert(), tofile(), tofile(), tofile(), tofile(), trymt(), tunpack(), unpack(), unpack(), unpackint(), unpackint(), Xml_eval(), and Xml_load().
luaL_findtable()
LUALIB_API const char * luaL_findtable (lua_State * L, int idx, const char * fname, int szhint)
Definition at line 357 of file lua-5.1.5/src/lauxlib.c.
{
  const char *e;
  lua_pushvalue(L, idx);
  do {
    e = strchr(fname, '.');
    if (e == NULL) e = fname + strlen(fname);
    lua_pushlstring(L, fname, e - fname);
    lua_rawget(L, -2);
    if (lua_isnil(L, -1)) {  /* no such field? */
      lua_pop(L, 1);  /* remove this nil */
      lua_createtable(L, 0, (*e == '.' ? 1 : szhint)); /* new table for field */
      lua_pushlstring(L, fname, e - fname);
      lua_pushvalue(L, -2);
      lua_settable(L, -4);  /* set new table into field */
    }
    else if (!lua_istable(L, -1)) {  /* field has a non-table value? */
      lua_pop(L, 2);  /* remove table and value */
      return fname;  /* return problematic part of the name */
    }
    lua_remove(L, -2);  /* remove previous table */
    fname = e + 1;
  } while (*e == '.');
  return NULL;
}
References lua_createtable(), lua_isnil, lua_istable, lua_pop, lua_pushlstring(), lua_pushvalue(), lua_rawget(), lua_remove, lua_settable(), and NULL.
Referenced by ll_module(), luaI_openlib(), and luaopen_package().
luaL_getmetafield()
LUALIB_API int luaL_getmetafield (lua_State * L, int obj, const char * event)
Definition at line 203 of file lua-5.1.5/src/lauxlib.c.
{
  if (!lua_getmetatable(L, obj))  /* no metatable? */
    return 0;
  lua_pushstring(L, event);
  lua_rawget(L, -2);
  if (lua_isnil(L, -1)) {
    lua_pop(L, 2);  /* remove metatable and metafield */
    return 0;
  }
  else {
    lua_remove(L, -2);  /* remove only metatable */
    return 1;
  }
}
References lua_getmetatable(), lua_isnil, lua_pop, lua_pushstring(), lua_rawget(), and lua_remove.
Referenced by luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_pairs(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaL_callmeta(), pairsmeta(), pairsmeta(), and trymt().
luaL_gsub()
LUALIB_API const char * luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 340 of file lua-5.1.5/src/lauxlib.c.
{
  const char *wild;
  size_t l = strlen(p);
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  while ((wild = strstr(s, p)) != NULL) {
    luaL_addlstring(&b, s, wild - s);  /* push prefix */
    luaL_addstring(&b, r);  /* push replacement in place of pattern */
    s = wild + l;  /* continue after `p' */
  }
  luaL_addstring(&b, s);  /* push last suffix */
  luaL_pushresult(&b);
  return lua_tostring(L, -1);
}
References lua_tostring, luaL_addlstring(), luaL_addstring(), luaL_buffinit(), luaL_pushresult(), NULL, and s.
Referenced by do_gsub(), findfile(), loadfunc(), loadfunc(), loadfunc(), mkfuncname(), searchpath(), searchpath(), searchpath(), setpath(), setpath(), and setpath().
luaL_loadbuffer()
LUALIB_API int luaL_loadbuffer (lua_State * L, const char * buff, size_t size, const char * name)
Definition at line 609 of file lua-5.1.5/src/lauxlib.c.
{
  LoadS ls;
  ls.s = buff;
  ls.size = size;
  return lua_load(L, getS, &ls, name);
}
References getS(), lua_load(), name, LoadS::s, and LoadS::size.
luaL_loadfile()
LUALIB_API int luaL_loadfile (lua_State * L, const char * filename)
Definition at line 552 of file lua-5.1.5/src/lauxlib.c.
{
  LoadF lf;
  int status, readstatus;
  int c;
  int fnameindex = lua_gettop(L) + 1;  /* index of filename on the stack */
  lf.extraline = 0;
  if (filename == NULL) {
    lua_pushliteral(L, "=stdin");
    lf.f = stdin;
  }
  else {
    lua_pushfstring(L, "@%s", filename);
    lf.f = fopen(filename, "r");
    if (lf.f == NULL) return errfile(L, "open", fnameindex);
  }
  c = getc(lf.f);
  if (c == '#') {  /* Unix exec. file? */
    lf.extraline = 1;
    while ((c = getc(lf.f)) != EOF && c != '\n') ;  /* skip first line */
    if (c == '\n') c = getc(lf.f);
  }
  if (c == LUA_SIGNATURE[0] && filename) {  /* binary file? */
    lf.f = freopen(filename, "rb", lf.f);  /* reopen in binary mode */
    if (lf.f == NULL) return errfile(L, "reopen", fnameindex);
    /* skip eventual `#!...' */
   while ((c = getc(lf.f)) != EOF && c != LUA_SIGNATURE[0]) ;
    lf.extraline = 0;
  }
  ungetc(c, lf.f);
  status = lua_load(L, getF, &lf, lua_tostring(L, -1));
  readstatus = ferror(lf.f);
  if (filename) fclose(lf.f);  /* close file (even in case of errors) */
  if (readstatus) {
    lua_settop(L, fnameindex);  /* ignore results from `lua_load' */
    return errfile(L, "read", fnameindex);
  }
  lua_remove(L, fnameindex);
  return status;
}
References errfile(), LoadF::extraline, LoadF::f, getF(), lua_gettop(), lua_load(), lua_pushfstring(), lua_pushliteral, lua_remove, lua_settop(), LUA_SIGNATURE, lua_tostring, and NULL.
luaL_loadstring()
LUALIB_API int luaL_loadstring (lua_State * L, const char * s)
Definition at line 618 of file lua-5.1.5/src/lauxlib.c.
{
  return luaL_loadbuffer(L, s, strlen(s), s);
}
References luaL_loadbuffer, and s.
luaL_newmetatable()
LUALIB_API int luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 112 of file lua-5.1.5/src/lauxlib.c.
{
  lua_getfield(L, LUA_REGISTRYINDEX, tname);  /* get registry.name */
  if (!lua_isnil(L, -1))  /* name already in use? */
    return 0;  /* leave previous value on top, but return 0 */
  lua_pop(L, 1);
  lua_newtable(L);  /* create metatable */
  lua_pushvalue(L, -1);
  lua_setfield(L, LUA_REGISTRYINDEX, tname);  /* registry.name = metatable */
  return 1;
}
References lua_getfield(), lua_isnil, lua_newtable, lua_pop, lua_pushvalue(), LUA_REGISTRYINDEX, and lua_setfield().
Referenced by create_meta(), createmeta(), createmeta(), createmeta(), createmeta(), dir_create_meta(), lock_create_meta(), luaopen_LuaXML_lib(), and luaopen_package().
luaL_newstate()
LUALIB_API lua_State * luaL_newstate (void)
Definition at line 647 of file lua-5.1.5/src/lauxlib.c.
{
  lua_State *L = lua_newstate(l_alloc, NULL);
  if (L) lua_atpanic(L, &panic);
  return L;
}
References l_alloc(), lua_atpanic(), lua_newstate(), NULL, and panic().
Referenced by main(), and main().
luaL_optinteger()
LUALIB_API lua_Integer luaL_optinteger (lua_State * L, int narg, lua_Integer def)
Definition at line 197 of file lua-5.1.5/src/lauxlib.c.
{
  return luaL_opt(L, luaL_checkinteger, narg, def);
}
References luaL_checkinteger(), and luaL_opt.
Referenced by b_unpack(), byteoffset(), byteoffset(), codepoint(), codepoint(), db_getuservalue(), db_sethook(), db_sethook(), db_setuservalue(), db_traceback(), db_traceback(), f_seek(), f_seek(), f_setvbuf(), f_setvbuf(), f_setvbuf(), f_setvbuf(), file_lock(), file_unlock(), file_utime(), getendpos(), gmatch(), lsqlite_open(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_error(), luaB_error(), math_randomseed(), os_exit(), os_exit(), str_byte(), str_byte(), str_byte(), str_byte(), str_find_aux(), str_find_aux(), str_find_aux(), str_find_aux(), str_gsub(), str_gsub(), str_gsub(), str_sub(), str_sub(), str_sub(), str_unpack(), str_unpack(), tconcat(), tconcat(), tremove(), tremove(), tunpack(), unpack(), utflen(), and utflen().
luaL_optlstring()
LUALIB_API const char * luaL_optlstring (lua_State * L, int narg, const char * def, size_t * len)
Definition at line 165 of file lua-5.1.5/src/lauxlib.c.
{
  if (lua_isnoneornil(L, narg)) {
    if (len)
      *len = (def ? strlen(def) : 0);
    return def;
  }
  else return luaL_checklstring(L, narg, len);
}
References lua_isnoneornil, and luaL_checklstring().
Referenced by os_date(), os_date(), str_rep(), str_rep(), str_rep(), tconcat(), tconcat(), tconcat(), and tconcat().
luaL_optnumber()
LUALIB_API lua_Number luaL_optnumber (lua_State * L, int narg, lua_Number def)
Definition at line 184 of file lua-5.1.5/src/lauxlib.c.
{
  return luaL_opt(L, luaL_checknumber, narg, def);
}
References luaL_checknumber(), and luaL_opt.
Referenced by f_seek(), file_utime(), math_atan(), math_atan(), os_difftime(), and os_difftime().
luaL_prepbuffer()
LUALIB_API char * luaL_prepbuffer (luaL_Buffer * B)
Definition at line 429 of file lua-5.1.5/src/lauxlib.c.
{
  if (emptybuffer(B))
    adjuststack(B);
  return B->buffer;
}
References adjuststack(), luaL_Buffer::buffer, and emptybuffer().
luaL_pushresult()
LUALIB_API void luaL_pushresult (luaL_Buffer * B)
Definition at line 447 of file lua-5.1.5/src/lauxlib.c.
{
  emptybuffer(B);
  lua_concat(B->L, B->lvl);
  B->lvl = 1;
}
References emptybuffer(), luaL_Buffer::L, lua_concat(), and luaL_Buffer::lvl.
Referenced by b_pack(), findloader(), findloader(), findloader(), luaL_gsub(), os_date(), os_date(), os_date(), os_date(), push_indentStr(), pusherrornotfound(), read_all(), read_all(), read_all(), read_chars(), read_chars(), read_chars(), read_chars(), read_line(), read_line(), read_line(), read_line(), searchpath(), searchpath(), searchpath(), setpath(), str_char(), str_dump(), str_dump(), str_dump(), str_dump(), str_format(), str_format(), str_format(), str_format(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), str_lower(), str_pack(), str_pack(), str_rep(), str_reverse(), str_upper(), tconcat(), tconcat(), tconcat(), tconcat(), utfchar(), utfchar(), Xml_pushEncode(), and Xml_str().
luaL_ref()
LUALIB_API int luaL_ref (lua_State * L, int t)
Definition at line 481 of file lua-5.1.5/src/lauxlib.c.
{
  int ref;
  t = abs_index(L, t);
  if (lua_isnil(L, -1)) {
    lua_pop(L, 1);  /* remove from stack */
    return LUA_REFNIL;  /* `nil' has a unique fixed reference */
  }
  lua_rawgeti(L, t, FREELIST_REF);  /* get first free element */
  ref = (int)lua_tointeger(L, -1);  /* ref = t[FREELIST_REF] */
  lua_pop(L, 1);  /* remove it from stack */
  if (ref != 0) {  /* any free element? */
    lua_rawgeti(L, t, ref);  /* remove it from list */
    lua_rawseti(L, t, FREELIST_REF);  /* (t[FREELIST_REF] = t[ref]) */
  }
  else {  /* no free elements */
    ref = (int)lua_objlen(L, t);
    ref++;  /* create new reference */
  }
  lua_rawseti(L, t, ref);
  return ref;
}
References abs_index, FREELIST_REF, lua_isnil, lua_objlen(), lua_pop, lua_rawgeti(), lua_rawseti(), LUA_REFNIL, and lua_tointeger.
Referenced by db_busy_handler(), db_commit_hook(), db_create_collation(), db_progress_handler(), db_register_function(), db_rollback_hook(), db_trace(), db_update_hook(), lcontext_set_aggregate_context(), luaopen_lsqlite3(), and luaopen_LuaXML_lib().
luaL_register()
LUALIB_API void luaL_register (lua_State * L, const char * libname, const luaL_Reg * l)
Definition at line 229 of file lua-5.1.5/src/lauxlib.c.
{
  luaI_openlib(L, libname, l, 0);
}
References luaI_openlib.
Referenced by base_open(), createmeta(), luaopen_base(), luaopen_debug(), luaopen_io(), luaopen_math(), luaopen_os(), luaopen_package(), luaopen_string(), and luaopen_table().
luaL_typerror()
LUALIB_API int luaL_typerror (lua_State * L, int narg, const char * tname)
Definition at line 61 of file lua-5.1.5/src/lauxlib.c.
{
  const char *msg = lua_pushfstring(L, "%s expected, got %s",
                                    tname, luaL_typename(L, narg));
  return luaL_argerror(L, narg, msg);
}
References lua_pushfstring(), luaL_argerror(), and luaL_typename.
Referenced by lsqlite_getbu(), lsqlite_getcontext(), lsqlite_getdb(), luaL_checkudata(), and tag_error().
luaL_unref()
LUALIB_API void luaL_unref (lua_State * L, int t, int ref)
Definition at line 504 of file lua-5.1.5/src/lauxlib.c.
{
  if (ref >= 0) {
    t = abs_index(L, t);
    lua_rawgeti(L, t, FREELIST_REF);
    lua_rawseti(L, t, ref);  /* t[ref] = t[FREELIST_REF] */
    lua_pushinteger(L, ref);
    lua_rawseti(L, t, FREELIST_REF);  /* t[FREELIST_REF] = ref */
  }
}
References abs_index, FREELIST_REF, lua_pushinteger(), lua_rawgeti(), and lua_rawseti().
Referenced by cleanupdb(), collfree(), db_busy_handler(), db_busy_timeout(), db_commit_hook(), db_progress_handler(), db_rollback_hook(), db_sql_finalize_function(), db_sql_normal_function(), db_trace(), db_update_hook(), and lcontext_set_aggregate_context().
luaL_where()
LUALIB_API void luaL_where (lua_State * L, int level)
Definition at line 73 of file lua-5.1.5/src/lauxlib.c.
{
  lua_Debug ar;
  if (lua_getstack(L, level, &ar)) {  /* check function at level */
    lua_getinfo(L, "Sl", &ar);  /* get info about it */
    if (ar.currentline > 0) {  /* is there info? */
      lua_pushfstring(L, "%s:%d: ", ar.short_src, ar.currentline);
      return;
    }
  }
  lua_pushliteral(L, "");  /* else, no information available... */
}
References lua_Debug::currentline, lua_getinfo(), lua_getstack(), lua_pushfstring(), lua_pushliteral, and lua_Debug::short_src.
Referenced by luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_error(), luaB_error(), luaB_error(), luaB_error(), and luaL_error().
panic()
static int panic (lua_State * L) static
Definition at line 639 of file lua-5.1.5/src/lauxlib.c.
{
  (void)L;  /* to avoid warnings */
  fprintf(stderr, "PANIC: unprotected error in call to Lua API (%s)\n",
                   lua_tostring(L, -1));
  return 0;
}
References lua_tostring.
Referenced by luaD_throw(), and luaL_newstate().
tag_error()
static void tag_error (lua_State * L, int narg, int tag) static
Definition at line 68 of file lua-5.1.5/src/lauxlib.c.
{
  luaL_typerror(L, narg, lua_typename(L, tag));
}
References lua_typename(), and luaL_typerror().
Referenced by luaL_checkinteger(), luaL_checklstring(), luaL_checknumber(), and luaL_checktype().