Github User Fetcher: lundump.h File Reference
lundump.h File Reference
#include "llimits.h"
#include "lobject.h"
#include "lzio.h"
Macros
#define LUAC_DATA "\x19\x93\r\n\x1a\n"
#define LUAC_INT 0x5678
#define LUAC_NUM cast_num(370.5)
#define MYINT(s) (s[0]-'0') /* assume one-digit numerals */
#define LUAC_VERSION (MYINT(LUA_VERSION_MAJOR)*16+MYINT(LUA_VERSION_MINOR))
#define LUAC_FORMAT 0 /* this is the official format */
Functions
LUAI_FUNC LClosure * luaU_undump (lua_State *L, ZIO *Z, const char *name)
LUAI_FUNC int luaU_dump (lua_State *L, const Proto *f, lua_Writer w, void *data, int strip)
Macro Definition Documentation
LUAC_DATA
#define LUAC_DATA "\x19\x93\r\n\x1a\n"
Definition at line 16 of file lua-5.4.3/src/lundump.h.
LUAC_FORMAT
#define LUAC_FORMAT 0 /* this is the official format */
Definition at line 27 of file lua-5.4.3/src/lundump.h.
LUAC_INT
#define LUAC_INT 0x5678
Definition at line 18 of file lua-5.4.3/src/lundump.h.
LUAC_NUM
#define LUAC_NUM cast_num(370.5)
Definition at line 19 of file lua-5.4.3/src/lundump.h.
LUAC_VERSION
#define LUAC_VERSION (MYINT(LUA_VERSION_MAJOR)*16+MYINT(LUA_VERSION_MINOR))
Definition at line 25 of file lua-5.4.3/src/lundump.h.
MYINT
#define MYINT (s) (s[0]-'0') /* assume one-digit numerals */
Definition at line 24 of file lua-5.4.3/src/lundump.h.
Function Documentation
luaU_dump()
LUAI_FUNC int luaU_dump (lua_State * L, const Proto * f, lua_Writer w, void * data, int strip)
Definition at line 153 of file lua-5.1.5/src/ldump.c.
{
 DumpState D;
 D.L=L;
 D.writer=w;
 D.data=data;
 D.strip=strip;
 D.status=0;
 DumpHeader(&D);
 DumpFunction(f,NULL,&D);
 return D.status;
}
References DumpState::data, dumpByte(), DumpByte(), DumpFunction(), DumpFunction(), DumpFunction(), dumpFunction(), DumpHeader(), DumpHeader(), DumpHeader(), dumpHeader(), DumpState::L, NULL, Proto::sizeupvalues, DumpState::status, DumpState::strip, and DumpState::writer.
Referenced by lua_dump(), lua_dump(), pmain(), pmain(), pmain(), and pmain().
luaU_undump()
LUAI_FUNC LClosure * luaU_undump (lua_State * L, ZIO * Z, const char * name)
Definition at line 265 of file lua-5.3.6/src/lundump.c.
{
  LoadState S;
  LClosure *cl;
  if (*name == '@' || *name == '=')
    S.name = name + 1;
  else if (*name == LUA_SIGNATURE[0])
    S.name = "binary string";
  else
    S.name = name;
  S.L = L;
  S.Z = Z;
  checkHeader(&S);
  cl = luaF_newLclosure(L, LoadByte(&S));
  setclLvalue(L, L->top, cl);
  luaD_inctop(L);
  cl->p = luaF_newproto(L);
  luaC_objbarrier(L, cl, cl->p);
  LoadFunction(&S, cl->p, NULL);
  lua_assert(cl->nupvalues == cl->p->sizeupvalues);
  luai_verifycode(L, buff, cl->p);
  return cl;
}
References checkHeader(), checkHeader(), loadByte(), LoadByte, LoadFunction(), loadFunction(), lua_assert, LUA_SIGNATURE, luaC_objbarrier, luaD_inctop(), luaF_newLclosure(), luaF_newproto(), luai_verifycode, name, NULL, LClosure::p, S, setclLvalue, setclLvalue2s, Proto::sizeupvalues, and lua_State::top.