Github User Fetcher: luac.c File Reference
luac.c File Reference
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lobject.h"
#include "lstate.h"
#include "lundump.h"
#include <ctype.h>
#include "ldebug.h"
#include "lopcodes.h"
Macros
#define luac_c
#define LUA_CORE
#define luaU_print PrintFunction
#define PROGNAME "luac" /* default program name */
#define OUTPUT PROGNAME ".out" /* default output file */
#define IS(s) (strcmp(argv[i],s)==0)
#define FUNCTION "(function()end)();"
#define toproto(L, i) getproto(L->top+(i))
#define luac_c
#define LUA_CORE
#define VOID(p) ((const void*)(p))
#define UPVALNAME(x) ((f->upvalues[x].name) ? getstr(f->upvalues[x].name) : "-")
#define MYK(x) (-1-(x))
#define SS(x) ((x==1)?"":"s")
#define S(x) (int)(x),SS(x)
Functions
static void PrintFunction (const Proto *f, int full)
static void fatal (const char *message)
static void cannot (const char *what)
static void usage (const char *message)
static int doargs (int argc, char *argv[])
static const char * reader (lua_State *L, void *ud, size_t *size)
static const Proto * combine (lua_State *L, int n)
static int writer (lua_State *L, const void *p, size_t size, void *u)
static int pmain (lua_State *L)
int main (int argc, char *argv[])
static void PrintString (const TString *ts)
static void PrintConstant (const Proto *f, int i)
static void PrintCode (const Proto *f)
static void PrintHeader (const Proto *f)
static void PrintDebug (const Proto *f)
Variables
static int listing =0
static int dumping =1
static int stripping =0
static char Output [] ={ OUTPUT }
static const char * output =Output
static const char * progname =PROGNAME
Macro Definition Documentation
FUNCTION
#define FUNCTION "(function()end)();"
Definition at line 117 of file lua-5.2.4/src/luac.c.
Referenced by reader().
IS
#define IS (s) (strcmp(argv[i],s)==0)
Definition at line 67 of file lua-5.2.4/src/luac.c.
Referenced by doargs(), and pmain().
LUA_CORE [1/2]
#define LUA_CORE
Definition at line 13 of file lua-5.2.4/src/luac.c.
LUA_CORE [2/2]
#define LUA_CORE
Definition at line 13 of file lua-5.2.4/src/luac.c.
luac_c [1/2]
#define luac_c
Definition at line 12 of file lua-5.2.4/src/luac.c.
luac_c [2/2]
#define luac_c
Definition at line 12 of file lua-5.2.4/src/luac.c.
luaU_print
#define luaU_print PrintFunction
Definition at line 23 of file lua-5.2.4/src/luac.c.
Referenced by pmain(), and pmain().
MYK
#define MYK (x) (-1-(x))
Definition at line 275 of file lua-5.2.4/src/luac.c.
Referenced by PrintCode().
OUTPUT
#define OUTPUT PROGNAME ".out" /* default output file */
Definition at line 26 of file lua-5.2.4/src/luac.c.
PROGNAME
#define PROGNAME "luac" /* default program name */
Definition at line 25 of file lua-5.2.4/src/luac.c.
Referenced by combine().
S
#define S (x) (int)(x),SS(x)
Definition at line 376 of file lua-5.2.4/src/luac.c.
Referenced by PrintHeader().
SS
#define SS (x) ((x==1)?"":"s")
Definition at line 375 of file lua-5.2.4/src/luac.c.
Referenced by PrintHeader().
toproto
#define toproto (L, i) getproto(L->top+(i))
Definition at line 134 of file lua-5.2.4/src/luac.c.
Referenced by combine().
UPVALNAME
#define UPVALNAME (x) ((f->upvalues[x].name) ? getstr(f->upvalues[x].name) : "-")
Definition at line 274 of file lua-5.2.4/src/luac.c.
Referenced by PrintCode(), and PrintDebug().
VOID
#define VOID (p) ((const void*)(p))
Definition at line 221 of file lua-5.2.4/src/luac.c.
Referenced by PrintCode(), PrintDebug(), and PrintHeader().
Function Documentation
cannot()
static void cannot (const char * what) static
Definition at line 41 of file lua-5.2.4/src/luac.c.
{
 fprintf(stderr,"%s: cannot %s %s: %s\n",progname,what,output,strerror(errno));
 exit(EXIT_FAILURE);
}
References output, and progname.
Referenced by pmain().
combine()
static const Proto * combine (lua_State * L, int n) static
Definition at line 136 of file lua-5.2.4/src/luac.c.
{
 if (n==1)
  return toproto(L,-1);
 else
 {
  Proto* f;
  int i=n;
  if (lua_load(L,reader,&i,"=(" PROGNAME ")",NULL)!=LUA_OK) fatal(lua_tostring(L,-1));
  f=toproto(L,-1);
  for (i=0; i<n; i++)
  {
   f->p[i]=toproto(L,i-n-1);
   if (f->p[i]->sizeupvalues>0) f->p[i]->upvalues[0].instack=0;
  }
  f->sizelineinfo=0;
  return f;
 }
}
References fatal(), lua_load(), LUA_OK, lua_tostring, NULL, Proto::p, PROGNAME, reader(), Proto::sizelineinfo, Proto::sizeupvalues, toproto, and Proto::upvalues.
Referenced by pmain().
doargs()
static int doargs (int argc, char * argv[]) static
Definition at line 69 of file lua-5.2.4/src/luac.c.
{
 int i;
 int version=0;
 if (argv[0]!=NULL && *argv[0]!=0) progname=argv[0];
 for (i=1; i<argc; i++)
 {
  if (*argv[i]!='-')            /* end of options; keep it */
   break;
  else if (IS("--"))            /* end of options; skip it */
  {
   ++i;
   if (version) ++version;
   break;
  }
  else if (IS("-"))         /* end of options; use stdin */
   break;
  else if (IS("-l"))            /* list */
   ++listing;
  else if (IS("-o"))            /* output file */
  {
   output=argv[++i];
   if (output==NULL || *output==0 || (*output=='-' && output[1]!=0))
    usage(LUA_QL("-o") " needs argument");
   if (IS("-")) output=NULL;
  }
  else if (IS("-p"))            /* parse only */
   dumping=0;
  else if (IS("-s"))            /* strip debug information */
   stripping=1;
  else if (IS("-v"))            /* show version */
   ++version;
  else                  /* unknown option */
   usage(argv[i]);
 }
 if (i==argc && (listing || !dumping))
 {
  dumping=0;
  argv[--i]=Output;
 }
 if (version)
 {
  printf("%s\n",LUA_COPYRIGHT);
  if (version==argc-1) exit(EXIT_SUCCESS);
 }
 return i;
}
References dumping, IS, listing, LUA_COPYRIGHT, LUA_QL, NULL, Output, output, printf, progname, stripping, and usage().
Referenced by main().
fatal()
static void fatal (const char * message) static
Definition at line 35 of file lua-5.2.4/src/luac.c.
{
 fprintf(stderr,"%s: %s\n",progname,message);
 exit(EXIT_FAILURE);
}
References progname.
Referenced by combine(), main(), and pmain().
main()
int main (int argc, char * argv[])
Definition at line 189 of file lua-5.2.4/src/luac.c.
{
 lua_State* L;
 int i=doargs(argc,argv);
 argc-=i; argv+=i;
 if (argc<=0) usage("no input files given");
 L=luaL_newstate();
 if (L==NULL) fatal("cannot create state: not enough memory");
 lua_pushcfunction(L,&pmain);
 lua_pushinteger(L,argc);
 lua_pushlightuserdata(L,argv);
 if (lua_pcall(L,2,0,0)!=LUA_OK) fatal(lua_tostring(L,-1));
 lua_close(L);
 return EXIT_SUCCESS;
}
References doargs(), fatal(), lua_close(), LUA_OK, lua_pcall, lua_pushcfunction, lua_pushinteger(), lua_pushlightuserdata(), lua_tostring, luaL_newstate(), NULL, pmain(), and usage().
pmain()
static int pmain (lua_State * L) static
Definition at line 162 of file lua-5.2.4/src/luac.c.
{
 int argc=(int)lua_tointeger(L,1);
 char** argv=(char**)lua_touserdata(L,2);
 const Proto* f;
 int i;
 if (!lua_checkstack(L,argc)) fatal("too many input files");
 for (i=0; i<argc; i++)
 {
  const char* filename=IS("-") ? NULL : argv[i];
  if (luaL_loadfile(L,filename)!=LUA_OK) fatal(lua_tostring(L,-1));
 }
 f=combine(L,argc);
 if (listing) luaU_print(f,listing>1);
 if (dumping)
 {
  FILE* D= (output==NULL) ? stdout : fopen(output,"wb");
  if (D==NULL) cannot("open");
  lua_lock(L);
  luaU_dump(L,f,writer,D,stripping);
  lua_unlock(L);
  if (ferror(D)) cannot("write");
  if (fclose(D)) cannot("close");
 }
 return 0;
}
References cannot(), combine(), dumping, fatal(), IS, listing, lua_checkstack(), lua_lock, LUA_OK, lua_tointeger, lua_tostring, lua_touserdata(), lua_unlock, luaL_loadfile, luaU_dump(), luaU_print, NULL, output, stripping, and writer().
Referenced by main().
PrintCode()
static void PrintCode (const Proto * f) static
Definition at line 277 of file lua-5.2.4/src/luac.c.
{
 const Instruction* code=f->code;
 int pc,n=f->sizecode;
 for (pc=0; pc<n; pc++)
 {
  Instruction i=code[pc];
  OpCode o=GET_OPCODE(i);
  int a=GETARG_A(i);
  int b=GETARG_B(i);
  int c=GETARG_C(i);
  int ax=GETARG_Ax(i);
  int bx=GETARG_Bx(i);
  int sbx=GETARG_sBx(i);
  int line=getfuncline(f,pc);
  printf("\t%d\t",pc+1);
  if (line>0) printf("[%d]\t",line); else printf("[-]\t");
  printf("%-9s\t",luaP_opnames[o]);
  switch (getOpMode(o))
  {
   case iABC:
    printf("%d",a);
    if (getBMode(o)!=OpArgN) printf(" %d",ISK(b) ? (MYK(INDEXK(b))) : b);
    if (getCMode(o)!=OpArgN) printf(" %d",ISK(c) ? (MYK(INDEXK(c))) : c);
    break;
   case iABx:
    printf("%d",a);
    if (getBMode(o)==OpArgK) printf(" %d",MYK(bx));
    if (getBMode(o)==OpArgU) printf(" %d",bx);
    break;
   case iAsBx:
    printf("%d %d",a,sbx);
    break;
   case iAx:
    printf("%d",MYK(ax));
    break;
  }
  switch (o)
  {
   case OP_LOADK:
    printf("\t; "); PrintConstant(f,bx);
    break;
   case OP_GETUPVAL:
   case OP_SETUPVAL:
    printf("\t; %s",UPVALNAME(b));
    break;
   case OP_GETTABUP:
    printf("\t; %s",UPVALNAME(b));
    if (ISK(c)) { printf(" "); PrintConstant(f,INDEXK(c)); }
    break;
   case OP_SETTABUP:
    printf("\t; %s",UPVALNAME(a));
    if (ISK(b)) { printf(" "); PrintConstant(f,INDEXK(b)); }
    if (ISK(c)) { printf(" "); PrintConstant(f,INDEXK(c)); }
    break;
   case OP_GETTABLE:
   case OP_SELF:
    if (ISK(c)) { printf("\t; "); PrintConstant(f,INDEXK(c)); }
    break;
   case OP_SETTABLE:
   case OP_ADD:
   case OP_SUB:
   case OP_MUL:
   case OP_DIV:
   case OP_POW:
   case OP_EQ:
   case OP_LT:
   case OP_LE:
    if (ISK(b) || ISK(c))
    {
     printf("\t; ");
     if (ISK(b)) PrintConstant(f,INDEXK(b)); else printf("-");
     printf(" ");
     if (ISK(c)) PrintConstant(f,INDEXK(c)); else printf("-");
    }
    break;
   case OP_JMP:
   case OP_FORLOOP:
   case OP_FORPREP:
   case OP_TFORLOOP:
    printf("\t; to %d",sbx+pc+2);
    break;
   case OP_CLOSURE:
    printf("\t; %p",VOID(f->p[bx]));
    break;
   case OP_SETLIST:
    if (c==0) printf("\t; %d",(int)code[++pc]); else printf("\t; %d",c);
    break;
   case OP_EXTRAARG:
    printf("\t; "); PrintConstant(f,ax);
    break;
   default:
    break;
  }
  printf("\n");
 }
}
References Proto::code, GET_OPCODE, GETARG_A, GETARG_Ax, GETARG_B, GETARG_Bx, GETARG_C, GETARG_sBx, getBMode, getCMode, getfuncline, getOpMode, iABC, iABx, iAsBx, iAx, INDEXK, ISK, luaP_opnames, MYK, OP_ADD, OP_CLOSURE, OP_DIV, OP_EQ, OP_EXTRAARG, OP_FORLOOP, OP_FORPREP, OP_GETTABLE, OP_GETTABUP, OP_GETUPVAL, OP_JMP, OP_LE, OP_LOADK, OP_LT, OP_MUL, OP_POW, OP_SELF, OP_SETLIST, OP_SETTABLE, OP_SETTABUP, OP_SETUPVAL, OP_SUB, OP_TFORLOOP, OpArgK, OpArgN, OpArgU, Proto::p, PrintConstant(), printf, Proto::sizecode, UPVALNAME, and VOID.
Referenced by PrintFunction().
PrintConstant()
static void PrintConstant (const Proto * f, int i) static
Definition at line 251 of file lua-5.2.4/src/luac.c.
{
 const TValue* o=&f->k[i];
 switch (ttypenv(o))
 {
  case LUA_TNIL:
    printf("nil");
    break;
  case LUA_TBOOLEAN:
    printf(bvalue(o) ? "true" : "false");
    break;
  case LUA_TNUMBER:
    printf(LUA_NUMBER_FMT,nvalue(o));
    break;
  case LUA_TSTRING:
    PrintString(rawtsvalue(o));
    break;
  default:              /* cannot happen */
    printf("? type=%d",ttype(o));
    break;
 }
}
References bvalue, Proto::k, LUA_NUMBER_FMT, LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, LUA_TSTRING, nvalue, printf, PrintString(), rawtsvalue, ttype, and ttypenv.
Referenced by PrintCode(), and PrintDebug().
PrintDebug()
static void PrintDebug (const Proto * f) static
Definition at line 398 of file lua-5.2.4/src/luac.c.
{
 int i,n;
 n=f->sizek;
 printf("constants (%d) for %p:\n",n,VOID(f));
 for (i=0; i<n; i++)
 {
  printf("\t%d\t",i+1);
  PrintConstant(f,i);
  printf("\n");
 }
 n=f->sizelocvars;
 printf("locals (%d) for %p:\n",n,VOID(f));
 for (i=0; i<n; i++)
 {
  printf("\t%d\t%s\t%d\t%d\n",
  i,getstr(f->locvars[i].varname),f->locvars[i].startpc+1,f->locvars[i].endpc+1);
 }
 n=f->sizeupvalues;
 printf("upvalues (%d) for %p:\n",n,VOID(f));
 for (i=0; i<n; i++)
 {
  printf("\t%d\t%s\t%d\t%d\n",
  i,UPVALNAME(i),f->upvalues[i].instack,f->upvalues[i].idx);
 }
}
References LocVar::endpc, getstr, Proto::locvars, PrintConstant(), printf, Proto::sizek, Proto::sizelocvars, Proto::sizeupvalues, LocVar::startpc, UPVALNAME, Proto::upvalues, LocVar::varname, and VOID.
Referenced by PrintFunction().
PrintFunction()
static void PrintFunction (const Proto * f, int full) static
Definition at line 425 of file lua-5.2.4/src/luac.c.
{
 int i,n=f->sizep;
 PrintHeader(f);
 PrintCode(f);
 if (full) PrintDebug(f);
 for (i=0; i<n; i++) PrintFunction(f->p[i],full);
}
References Proto::p, PrintCode(), PrintDebug(), PrintFunction, PrintHeader(), and Proto::sizep.
PrintHeader()
static void PrintHeader (const Proto * f) static
Definition at line 378 of file lua-5.2.4/src/luac.c.
{
 const char* s=f->source ? getstr(f->source) : "=?";
 if (*s=='@' || *s=='=')
  s++;
 else if (*s==LUA_SIGNATURE[0])
  s="(bstring)";
 else
  s="(string)";
 printf("\n%s <%s:%d,%d> (%d instruction%s at %p)\n",
    (f->linedefined==0)?"main":"function",s,
    f->linedefined,f->lastlinedefined,
    S(f->sizecode),VOID(f));
 printf("%d%s param%s, %d slot%s, %d upvalue%s, ",
    (int)(f->numparams),f->is_vararg?"+":"",SS(f->numparams),
    S(f->maxstacksize),S(f->sizeupvalues));
 printf("%d local%s, %d constant%s, %d function%s\n",
    S(f->sizelocvars),S(f->sizek),S(f->sizep));
}
References getstr, Proto::is_vararg, Proto::lastlinedefined, Proto::linedefined, LUA_SIGNATURE, Proto::maxstacksize, Proto::numparams, printf, S, s, Proto::sizecode, Proto::sizek, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, Proto::source, SS, and VOID.
Referenced by PrintFunction().
PrintString()
static void PrintString (const TString * ts) static
Definition at line 223 of file lua-5.2.4/src/luac.c.
{
 const char* s=getstr(ts);
 size_t i,n=ts->tsv.len;
 printf("%c",'"');
 for (i=0; i<n; i++)
 {
  int c=(int)(unsigned char)s[i];
  switch (c)
  {
   case '"':  printf("\\\""); break;
   case '\\': printf("\\\\"); break;
   case '\a': printf("\\a"); break;
   case '\b': printf("\\b"); break;
   case '\f': printf("\\f"); break;
   case '\n': printf("\\n"); break;
   case '\r': printf("\\r"); break;
   case '\t': printf("\\t"); break;
   case '\v': printf("\\v"); break;
   default: if (isprint(c))
            printf("%c",c);
        else
            printf("\\%03d",c);
  }
 }
 printf("%c",'"');
}
References getstr, TString::len, printf, s, and TString::tsv.
Referenced by PrintConstant().
reader()
static const char * reader (lua_State * L, void * ud, size_t * size) static
Definition at line 119 of file lua-5.2.4/src/luac.c.
{
 UNUSED(L);
 if ((*(int*)ud)--)
 {
  *size=sizeof(FUNCTION)-1;
  return FUNCTION;
 }
 else
 {
  *size=0;
  return NULL;
 }
}
References FUNCTION, NULL, and UNUSED.
Referenced by combine(), lua_load(), lua_load(), and luaZ_init().
usage()
static void usage (const char * message) static
Definition at line 47 of file lua-5.2.4/src/luac.c.
{
 if (*message=='-')
  fprintf(stderr,"%s: unrecognized option " LUA_QS "\n",progname,message);
 else
  fprintf(stderr,"%s: %s\n",progname,message);
 fprintf(stderr,
  "usage: %s [options] [filenames]\n"
  "Available options are:\n"
  "  -l       list (use -l -l for full listing)\n"
  "  -o name  output to file " LUA_QL("name") " (default is \"%s\")\n"
  "  -p       parse only\n"
  "  -s       strip debug information\n"
  "  -v       show version information\n"
  "  --       stop handling options\n"
  "  -        stop handling options and process stdin\n"
  ,progname,Output);
 exit(EXIT_FAILURE);
}
References LUA_QL, LUA_QS, Output, and progname.
Referenced by doargs(), and main().
writer()
static int writer (lua_State * L, const void * p, size_t size, void * u) static
Definition at line 156 of file lua-5.2.4/src/luac.c.
{
 UNUSED(L);
 return (fwrite(p,size,1,(FILE*)u)!=1) && (size!=0);
}
References fwrite(), and UNUSED.
Referenced by pmain().
Variable Documentation
dumping
int dumping =1 static
Definition at line 29 of file lua-5.2.4/src/luac.c.
Referenced by doargs(), and pmain().
listing
int listing =0 static
Definition at line 28 of file lua-5.2.4/src/luac.c.
Referenced by doargs(), and pmain().
Output
char Output[] ={ OUTPUT } static
Definition at line 31 of file lua-5.2.4/src/luac.c.
{ OUTPUT }; /* default output file name */
Referenced by doargs(), and usage().
output
const char* output =Output static
Definition at line 32 of file lua-5.2.4/src/luac.c.
Referenced by cannot(), doargs(), and pmain().
progname
const char* progname =PROGNAME static
Definition at line 33 of file lua-5.2.4/src/luac.c.
Referenced by cannot(), doargs(), fatal(), and usage().
stripping
int stripping =0 static
Definition at line 30 of file lua-5.2.4/src/luac.c.
Referenced by doargs(), and pmain().