Github User Fetcher: lmathlib.c File Reference
lmathlib.c File Reference
#include "lprefix.h"
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdlib.h>
#include <time.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Data Structures
struct Rand64
struct RanState
Macros
#define lmathlib_c
#define LUA_LIB
#define PI (l_mathop(3.141592653589793238462643383279502884))
#define FIGS l_floatatt(MANT_DIG)
#define trim32(x) ((x) & 0xffffffffu)
#define UONE ((lu_int32)1)
#define scaleFIG (l_mathop(0.5) / (UONE << (FIGS - 1)))
Typedefs
typedef unsigned long lu_int32
typedef struct Rand64 Rand64
Functions
static int math_abs (lua_State *L)
static int math_sin (lua_State *L)
static int math_cos (lua_State *L)
static int math_tan (lua_State *L)
static int math_asin (lua_State *L)
static int math_acos (lua_State *L)
static int math_atan (lua_State *L)
static int math_toint (lua_State *L)
static void pushnumint (lua_State *L, lua_Number d)
static int math_floor (lua_State *L)
static int math_ceil (lua_State *L)
static int math_fmod (lua_State *L)
static int math_modf (lua_State *L)
static int math_sqrt (lua_State *L)
static int math_ult (lua_State *L)
static int math_log (lua_State *L)
static int math_exp (lua_State *L)
static int math_deg (lua_State *L)
static int math_rad (lua_State *L)
static int math_min (lua_State *L)
static int math_max (lua_State *L)
static int math_type (lua_State *L)
static Rand64 packI (lu_int32 h, lu_int32 l)
static Rand64 Ishl (Rand64 i, int n)
static void Ixor (Rand64 *i1, Rand64 i2)
static Rand64 Iadd (Rand64 i1, Rand64 i2)
static Rand64 times5 (Rand64 i)
static Rand64 times9 (Rand64 i)
static Rand64 rotl (Rand64 i, int n)
static Rand64 rotl1 (Rand64 i, int n)
static Rand64 nextrand (Rand64 *state)
static lua_Number I2d (Rand64 x)
static lua_Unsigned I2UInt (Rand64 x)
static Rand64 Int2I (lua_Unsigned n)
static lua_Unsigned project (lua_Unsigned ran, lua_Unsigned n, RanState *state)
static int math_random (lua_State *L)
static void setseed (lua_State *L, Rand64 *state, lua_Unsigned n1, lua_Unsigned n2)
static void randseed (lua_State *L, RanState *state)
static int math_randomseed (lua_State *L)
static void setrandfunc (lua_State *L)
LUAMOD_API int luaopen_math (lua_State *L)
Variables
static const luaL_Reg randfuncs []
static const luaL_Reg mathlib []
Macro Definition Documentation
FIGS
#define FIGS l_floatatt(MANT_DIG)
Definition at line 253 of file lua-5.4.3/src/lmathlib.c.
Referenced by I2d().
lmathlib_c
#define lmathlib_c
Definition at line 7 of file lua-5.4.3/src/lmathlib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.4.3/src/lmathlib.c.
PI
#define PI (l_mathop(3.141592653589793238462643383279502884))
Definition at line 26 of file lua-5.4.3/src/lmathlib.c.
Referenced by luaopen_math(), math_deg(), and math_rad().
scaleFIG
#define scaleFIG (l_mathop(0.5) / (UONE << (FIGS - 1)))
Definition at line 461 of file lua-5.4.3/src/lmathlib.c.
Referenced by I2d().
trim32
#define trim32 (x) ((x) & 0xffffffffu)
Definition at line 374 of file lua-5.4.3/src/lmathlib.c.
Referenced by I2d(), I2UInt(), Iadd(), Ishl(), rotl(), and rotl1().
UONE
#define UONE ((lu_int32)1)
Definition at line 455 of file lua-5.4.3/src/lmathlib.c.
Typedef Documentation
lu_int32
typedef unsigned long lu_int32
Definition at line 354 of file lua-5.4.3/src/lmathlib.c.
Rand64
typedef struct Rand64 Rand64
Function Documentation
I2d()
static lua_Number I2d (Rand64 x) static
Definition at line 467 of file lua-5.4.3/src/lmathlib.c.
{
  lua_Number h = (lua_Number)(trim32(x.h) >> (32 - FIGS));
  return h * scaleFIG;
}
References FIGS, Rand64::h, scaleFIG, and trim32.
Referenced by math_random().
I2UInt()
static lua_Unsigned I2UInt (Rand64 x) static
Definition at line 502 of file lua-5.4.3/src/lmathlib.c.
{
  return ((lua_Unsigned)trim32(x.h) << 31 << 1) | (lua_Unsigned)trim32(x.l);
}
References Rand64::h, Rand64::l, and trim32.
Referenced by math_random(), and project().
Iadd()
static Rand64 Iadd (Rand64 i1, Rand64 i2) static
Definition at line 402 of file lua-5.4.3/src/lmathlib.c.
{
  Rand64 result = packI(i1.h + i2.h, i1.l + i2.l);
  if (trim32(result.l) < trim32(i1.l))  /* carry? */
    result.h++;
  return result;
}
References Rand64::h, Rand64::l, packI(), and trim32.
Referenced by times5(), and times9().
Int2I()
static Rand64 Int2I (lua_Unsigned n) static
Definition at line 507 of file lua-5.4.3/src/lmathlib.c.
{
  return packI((lu_int32)(n >> 31 >> 1), (lu_int32)n);
}
References packI().
Referenced by setseed().
Ishl()
static Rand64 Ishl (Rand64 i, int n) static
Definition at line 390 of file lua-5.4.3/src/lmathlib.c.
{
  lua_assert(n > 0 && n < 32);
  return packI((i.h << n) | (trim32(i.l) >> (32 - n)), i.l << n);
}
References Rand64::h, Rand64::l, lua_assert, packI(), and trim32.
Referenced by nextrand(), times5(), and times9().
Ixor()
static void Ixor (Rand64 * i1, Rand64 i2) static
Definition at line 396 of file lua-5.4.3/src/lmathlib.c.
{
  i1->h ^= i2.h;
  i1->l ^= i2.l;
}
References Rand64::h, and Rand64::l.
Referenced by nextrand().
luaopen_math()
LUAMOD_API int luaopen_math (lua_State * L)
Definition at line 751 of file lua-5.4.3/src/lmathlib.c.
{
  luaL_newlib(L, mathlib);
  lua_pushnumber(L, PI);
  lua_setfield(L, -2, "pi");
  lua_pushnumber(L, (lua_Number)HUGE_VAL);
  lua_setfield(L, -2, "huge");
  lua_pushinteger(L, LUA_MAXINTEGER);
  lua_setfield(L, -2, "maxinteger");
  lua_pushinteger(L, LUA_MININTEGER);
  lua_setfield(L, -2, "mininteger");
  setrandfunc(L);
  return 1;
}
References lua_pushinteger(), lua_pushnumber(), lua_setfield(), luaL_newlib, mathlib, PI, and setrandfunc().
math_abs()
static int math_abs (lua_State * L) static
Definition at line 29 of file lua-5.4.3/src/lmathlib.c.
{
  if (lua_isinteger(L, 1)) {
    lua_Integer n = lua_tointeger(L, 1);
    if (n < 0) n = (lua_Integer)(0u - (lua_Unsigned)n);
    lua_pushinteger(L, n);
  }
  else
    lua_pushnumber(L, l_mathop(fabs)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_isinteger(), lua_pushinteger(), lua_pushnumber(), lua_tointeger, and luaL_checknumber().
math_acos()
static int math_acos (lua_State * L) static
Definition at line 60 of file lua-5.4.3/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(acos)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_asin()
static int math_asin (lua_State * L) static
Definition at line 55 of file lua-5.4.3/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(asin)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_atan()
static int math_atan (lua_State * L) static
Definition at line 65 of file lua-5.4.3/src/lmathlib.c.
{
  lua_Number y = luaL_checknumber(L, 1);
  lua_Number x = luaL_optnumber(L, 2, 1);
  lua_pushnumber(L, l_mathop(atan2)(y, x));
  return 1;
}
References l_mathop, lua_pushnumber(), luaL_checknumber(), and luaL_optnumber().
math_ceil()
static int math_ceil (lua_State * L) static
Definition at line 106 of file lua-5.4.3/src/lmathlib.c.
{
  if (lua_isinteger(L, 1))
    lua_settop(L, 1);  /* integer is its own ceil */
  else {
    lua_Number d = l_mathop(ceil)(luaL_checknumber(L, 1));
    pushnumint(L, d);
  }
  return 1;
}
References l_mathop, lua_isinteger(), lua_settop(), luaL_checknumber(), and pushnumint().
math_cos()
static int math_cos (lua_State * L) static
Definition at line 45 of file lua-5.4.3/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(cos)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_deg()
static int math_deg (lua_State * L) static
Definition at line 195 of file lua-5.4.3/src/lmathlib.c.
{
  lua_pushnumber(L, luaL_checknumber(L, 1) * (l_mathop(180.0) / PI));
  return 1;
}
References l_mathop, lua_pushnumber(), luaL_checknumber(), and PI.
math_exp()
static int math_exp (lua_State * L) static
Definition at line 190 of file lua-5.4.3/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(exp)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_floor()
static int math_floor (lua_State * L) static
Definition at line 95 of file lua-5.4.3/src/lmathlib.c.
{
  if (lua_isinteger(L, 1))
    lua_settop(L, 1);  /* integer is its own floor */
  else {
    lua_Number d = l_mathop(floor)(luaL_checknumber(L, 1));
    pushnumint(L, d);
  }
  return 1;
}
References l_mathop, lua_isinteger(), lua_settop(), luaL_checknumber(), and pushnumint().
math_fmod()
static int math_fmod (lua_State * L) static
Definition at line 117 of file lua-5.4.3/src/lmathlib.c.
{
  if (lua_isinteger(L, 1) && lua_isinteger(L, 2)) {
    lua_Integer d = lua_tointeger(L, 2);
    if ((lua_Unsigned)d + 1u <= 1u) {  /* special cases: -1 or 0 */
      luaL_argcheck(L, d != 0, 2, "zero");
      lua_pushinteger(L, 0);  /* avoid overflow with 0x80000... / -1 */
    }
    else
      lua_pushinteger(L, lua_tointeger(L, 1) % d);
  }
  else
    lua_pushnumber(L, l_mathop(fmod)(luaL_checknumber(L, 1),
                                     luaL_checknumber(L, 2)));
  return 1;
}
References l_mathop, lua_isinteger(), lua_pushinteger(), lua_pushnumber(), lua_tointeger, luaL_argcheck, and luaL_checknumber().
math_log()
static int math_log (lua_State * L) static
Definition at line 169 of file lua-5.4.3/src/lmathlib.c.
{
  lua_Number x = luaL_checknumber(L, 1);
  lua_Number res;
  if (lua_isnoneornil(L, 2))
    res = l_mathop(log)(x);
  else {
    lua_Number base = luaL_checknumber(L, 2);
#if !defined(LUA_USE_C89)
    if (base == l_mathop(2.0))
      res = l_mathop(log2)(x);
    else
#endif
    if (base == l_mathop(10.0))
      res = l_mathop(log10)(x);
    else
      res = l_mathop(log)(x)/l_mathop(log)(base);
  }
  lua_pushnumber(L, res);
  return 1;
}
References l_mathop, lua_isnoneornil, lua_pushnumber(), and luaL_checknumber().
math_max()
static int math_max (lua_State * L) static
Definition at line 220 of file lua-5.4.3/src/lmathlib.c.
{
  int n = lua_gettop(L);  /* number of arguments */
  int imax = 1;  /* index of current maximum value */
  int i;
  luaL_argcheck(L, n >= 1, 1, "value expected");
  for (i = 2; i <= n; i++) {
    if (lua_compare(L, imax, i, LUA_OPLT))
      imax = i;
  }
  lua_pushvalue(L, imax);
  return 1;
}
References lua_compare(), lua_gettop(), LUA_OPLT, lua_pushvalue(), and luaL_argcheck.
math_min()
static int math_min (lua_State * L) static
Definition at line 206 of file lua-5.4.3/src/lmathlib.c.
{
  int n = lua_gettop(L);  /* number of arguments */
  int imin = 1;  /* index of current minimum value */
  int i;
  luaL_argcheck(L, n >= 1, 1, "value expected");
  for (i = 2; i <= n; i++) {
    if (lua_compare(L, i, imin, LUA_OPLT))
      imin = i;
  }
  lua_pushvalue(L, imin);
  return 1;
}
References lua_compare(), lua_gettop(), LUA_OPLT, lua_pushvalue(), and luaL_argcheck.
math_modf()
static int math_modf (lua_State * L) static
Definition at line 139 of file lua-5.4.3/src/lmathlib.c.
{
  if (lua_isinteger(L ,1)) {
    lua_settop(L, 1);  /* number is its own integer part */
    lua_pushnumber(L, 0);  /* no fractional part */
  }
  else {
    lua_Number n = luaL_checknumber(L, 1);
    /* integer part (rounds toward zero) */
    lua_Number ip = (n < 0) ? l_mathop(ceil)(n) : l_mathop(floor)(n);
    pushnumint(L, ip);
    /* fractional part (test needed for inf/-inf) */
    lua_pushnumber(L, (n == ip) ? l_mathop(0.0) : (n - ip));
  }
  return 2;
}
References l_mathop, lua_isinteger(), lua_pushnumber(), lua_settop(), luaL_checknumber(), and pushnumint().
math_rad()
static int math_rad (lua_State * L) static
Definition at line 200 of file lua-5.4.3/src/lmathlib.c.
{
  lua_pushnumber(L, luaL_checknumber(L, 1) * (PI / l_mathop(180.0)));
  return 1;
}
References l_mathop, lua_pushnumber(), luaL_checknumber(), and PI.
math_random()
static int math_random (lua_State * L) static
Definition at line 557 of file lua-5.4.3/src/lmathlib.c.
{
  lua_Integer low, up;
  lua_Unsigned p;
  RanState *state = (RanState *)lua_touserdata(L, lua_upvalueindex(1));
  Rand64 rv = nextrand(state->s);  /* next pseudo-random value */
  switch (lua_gettop(L)) {  /* check number of arguments */
    case 0: {  /* no arguments */
      lua_pushnumber(L, I2d(rv));  /* float between 0 and 1 */
      return 1;
    }
    case 1: {  /* only upper limit */
      low = 1;
      up = luaL_checkinteger(L, 1);
      if (up == 0) {  /* single 0 as argument? */
        lua_pushinteger(L, I2UInt(rv));  /* full random integer */
        return 1;
      }
      break;
    }
    case 2: {  /* lower and upper limits */
      low = luaL_checkinteger(L, 1);
      up = luaL_checkinteger(L, 2);
      break;
    }
    default: return luaL_error(L, "wrong number of arguments");
  }
  /* random integer in the interval [low, up] */
  luaL_argcheck(L, low <= up, 1, "interval is empty");
  /* project random integer into the interval [0, up - low] */
  p = project(I2UInt(rv), (lua_Unsigned)up - (lua_Unsigned)low, state);
  lua_pushinteger(L, p + (lua_Unsigned)low);
  return 1;
}
References I2d(), I2UInt(), lua_gettop(), lua_pushinteger(), lua_pushnumber(), lua_touserdata(), lua_upvalueindex, luaL_argcheck, luaL_checkinteger(), luaL_error(), nextrand(), project(), and RanState::s.
math_randomseed()
static int math_randomseed (lua_State * L) static
Definition at line 618 of file lua-5.4.3/src/lmathlib.c.
{
  RanState *state = (RanState *)lua_touserdata(L, lua_upvalueindex(1));
  if (lua_isnone(L, 1)) {
    randseed(L, state);
  }
  else {
    lua_Integer n1 = luaL_checkinteger(L, 1);
    lua_Integer n2 = luaL_optinteger(L, 2, 0);
    setseed(L, state->s, n1, n2);
  }
  return 2;  /* return seeds */
}
References lua_isnone, lua_touserdata(), lua_upvalueindex, luaL_checkinteger(), luaL_optinteger(), randseed(), RanState::s, and setseed().
math_sin()
static int math_sin (lua_State * L) static
Definition at line 40 of file lua-5.4.3/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(sin)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_sqrt()
static int math_sqrt (lua_State * L) static
Definition at line 156 of file lua-5.4.3/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(sqrt)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_tan()
static int math_tan (lua_State * L) static
Definition at line 50 of file lua-5.4.3/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(tan)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_toint()
static int math_toint (lua_State * L) static
Definition at line 73 of file lua-5.4.3/src/lmathlib.c.
{
  int valid;
  lua_Integer n = lua_tointegerx(L, 1, &valid);
  if (l_likely(valid))
    lua_pushinteger(L, n);
  else {
    luaL_checkany(L, 1);
    luaL_pushfail(L);  /* value is not convertible to integer */
  }
  return 1;
}
References lua_pushinteger(), lua_tointegerx(), luaL_checkany(), and luaL_pushfail.
math_type()
static int math_type (lua_State * L) static
Definition at line 234 of file lua-5.4.3/src/lmathlib.c.
{
  if (lua_type(L, 1) == LUA_TNUMBER)
    lua_pushstring(L, (lua_isinteger(L, 1)) ? "integer" : "float");
  else {
    luaL_checkany(L, 1);
    luaL_pushfail(L);
  }
  return 1;
}
References lua_isinteger(), lua_pushstring(), LUA_TNUMBER, lua_type(), luaL_checkany(), and luaL_pushfail.
math_ult()
static int math_ult (lua_State * L) static
Definition at line 162 of file lua-5.4.3/src/lmathlib.c.
{
  lua_Integer a = luaL_checkinteger(L, 1);
  lua_Integer b = luaL_checkinteger(L, 2);
  lua_pushboolean(L, (lua_Unsigned)a < (lua_Unsigned)b);
  return 1;
}
References lua_pushboolean(), and luaL_checkinteger().
nextrand()
static Rand64 nextrand (Rand64 * state) static
Definition at line 437 of file lua-5.4.3/src/lmathlib.c.
{
  Rand64 res = times9(rotl(times5(state[1]), 7));
  Rand64 t = Ishl(state[1], 17);
  Ixor(&state[2], state[0]);
  Ixor(&state[3], state[1]);
  Ixor(&state[1], state[2]);
  Ixor(&state[0], state[3]);
  Ixor(&state[2], t);
  state[3] = rotl1(state[3], 45);
  return res;
}
References Ishl(), Ixor(), rotl(), rotl1(), times5(), and times9().
Referenced by math_random(), project(), and setseed().
packI()
static Rand64 packI (lu_int32 h, lu_int32 l) static
Definition at line 382 of file lua-5.4.3/src/lmathlib.c.
{
  Rand64 result;
  result.h = h;
  result.l = l;
  return result;
}
References Rand64::h, and Rand64::l.
Referenced by Iadd(), Int2I(), Ishl(), rotl(), and rotl1().
project()
static lua_Unsigned project (lua_Unsigned ran, lua_Unsigned n, RanState * state) static
Definition at line 532 of file lua-5.4.3/src/lmathlib.c.
{
  if ((n & (n + 1)) == 0)  /* is 'n + 1' a power of 2? */
    return ran & n;  /* no bias */
  else {
    lua_Unsigned lim = n;
    /* compute the smallest (2^b - 1) not smaller than 'n' */
    lim |= (lim >> 1);
    lim |= (lim >> 2);
    lim |= (lim >> 4);
    lim |= (lim >> 8);
    lim |= (lim >> 16);
#if (LUA_MAXUNSIGNED >> 31) >= 3
    lim |= (lim >> 32);  /* integer type has more than 32 bits */
#endif
    lua_assert((lim & (lim + 1)) == 0  /* 'lim + 1' is a power of 2, */
      && lim >= n  /* not smaller than 'n', */
      && (lim >> 1) < n);  /* and it is the smallest one */
    while ((ran &= lim) > n)  /* project 'ran' into [0..lim] */
      ran = I2UInt(nextrand(state->s));  /* not inside [0..n]? try again */
    return ran;
  }
}
References I2UInt(), lua_assert, nextrand(), and RanState::s.
Referenced by math_random().
pushnumint()
static void pushnumint (lua_State * L, lua_Number d) static
Definition at line 86 of file lua-5.4.3/src/lmathlib.c.
{
  lua_Integer n;
  if (lua_numbertointeger(d, &n))  /* does 'd' fit in an integer? */
    lua_pushinteger(L, n);  /* result is integer */
  else
    lua_pushnumber(L, d);  /* result is float */
}
References lua_numbertointeger, lua_pushinteger(), and lua_pushnumber().
Referenced by math_ceil(), math_floor(), and math_modf().
randseed()
static void randseed (lua_State * L, RanState * state) static
Definition at line 611 of file lua-5.4.3/src/lmathlib.c.
{
  lua_Unsigned seed1 = (lua_Unsigned)time(NULL);
  lua_Unsigned seed2 = (lua_Unsigned)(size_t)L;
  setseed(L, state->s, seed1, seed2);
}
References NULL, RanState::s, and setseed().
Referenced by math_randomseed(), and setrandfunc().
rotl()
static Rand64 rotl (Rand64 i, int n) static
Definition at line 420 of file lua-5.4.3/src/lmathlib.c.
{
  lua_assert(n > 0 && n < 32);
  return packI((i.h << n) | (trim32(i.l) >> (32 - n)),
               (trim32(i.h) >> (32 - n)) | (i.l << n));
}
References Rand64::h, Rand64::l, lua_assert, packI(), and trim32.
Referenced by nextrand().
rotl1()
static Rand64 rotl1 (Rand64 i, int n) static
Definition at line 427 of file lua-5.4.3/src/lmathlib.c.
{
  lua_assert(n > 32 && n < 64);
  n = 64 - n;
  return packI((trim32(i.h) >> n) | (i.l << (32 - n)),
               (i.h << (32 - n)) | (trim32(i.l) >> n));
}
References Rand64::h, Rand64::l, lua_assert, packI(), and trim32.
Referenced by nextrand().
setrandfunc()
static void setrandfunc (lua_State * L) static
Definition at line 642 of file lua-5.4.3/src/lmathlib.c.
{
  RanState *state = (RanState *)lua_newuserdatauv(L, sizeof(RanState), 0);
  randseed(L, state);  /* initialize with a "random" seed */
  lua_pop(L, 2);  /* remove pushed seeds */
  luaL_setfuncs(L, randfuncs, 1);
}
References lua_newuserdatauv(), lua_pop, luaL_setfuncs(), randfuncs, and randseed().
Referenced by luaopen_math().
setseed()
static void setseed (lua_State * L, Rand64 * state, lua_Unsigned n1, lua_Unsigned n2) static
Definition at line 592 of file lua-5.4.3/src/lmathlib.c.
{
  int i;
  state[0] = Int2I(n1);
  state[1] = Int2I(0xff);  /* avoid a zero state */
  state[2] = Int2I(n2);
  state[3] = Int2I(0);
  for (i = 0; i < 16; i++)
    nextrand(state);  /* discard initial values to "spread" seed */
  lua_pushinteger(L, n1);
  lua_pushinteger(L, n2);
}
References Int2I(), lua_pushinteger(), and nextrand().
Referenced by math_randomseed(), and randseed().
times5()
static Rand64 times5 (Rand64 i) static
Definition at line 410 of file lua-5.4.3/src/lmathlib.c.
{
  return Iadd(Ishl(i, 2), i);  /* i * 5 == (i << 2) + i */
}
References Iadd(), and Ishl().
Referenced by nextrand().
times9()
static Rand64 times9 (Rand64 i) static
Definition at line 415 of file lua-5.4.3/src/lmathlib.c.
{
  return Iadd(Ishl(i, 3), i);  /* i * 9 == (i << 3) + i */
}
References Iadd(), and Ishl().
Referenced by nextrand().
Variable Documentation
mathlib
const luaL_Reg mathlib[] static
Definition at line 705 of file lua-5.4.3/src/lmathlib.c.
{
  {"abs",   math_abs},
  {"acos",  math_acos},
  {"asin",  math_asin},
  {"atan",  math_atan},
  {"ceil",  math_ceil},
  {"cos",   math_cos},
  {"deg",   math_deg},
  {"exp",   math_exp},
  {"tointeger", math_toint},
  {"floor", math_floor},
  {"fmod",   math_fmod},
  {"ult",   math_ult},
  {"log",   math_log},
  {"max",   math_max},
  {"min",   math_min},
  {"modf",   math_modf},
  {"rad",   math_rad},
  {"sin",   math_sin},
  {"sqrt",  math_sqrt},
  {"tan",   math_tan},
  {"type", math_type},
#if defined(LUA_COMPAT_MATHLIB)
  {"atan2", math_atan},
  {"cosh",   math_cosh},
  {"sinh",   math_sinh},
  {"tanh",   math_tanh},
  {"pow",   math_pow},
  {"frexp", math_frexp},
  {"ldexp", math_ldexp},
  {"log10", math_log10},
#endif
  /* placeholders */
  {"random", NULL},
  {"randomseed", NULL},
  {"pi", NULL},
  {"huge", NULL},
  {"maxinteger", NULL},
  {"mininteger", NULL},
  {NULL, NULL}
};
Referenced by luaopen_math().
randfuncs
const luaL_Reg randfuncs[] static
Initial value:
= {
  {"random", math_random},
  {"randomseed", math_randomseed},
  {NULL, NULL}
}
Definition at line 632 of file lua-5.4.3/src/lmathlib.c.
{
  {"random", math_random},
  {"randomseed", math_randomseed},
  {NULL, NULL}
};
Referenced by setrandfunc().