Github User Fetcher: lzio.h File Reference
lzio.h File Reference
#include "lua.h"
#include "lmem.h"
Data Structures
struct Mbuffer
struct Zio
Macros
#define EOZ (-1) /* end of stream */
#define zgetc(z) (((z)->n--)>0 ? cast_uchar(*(z)->p++) : luaZ_fill(z))
#define luaZ_initbuffer(L, buff) ((buff)->buffer = NULL, (buff)->buffsize = 0)
#define luaZ_buffer(buff) ((buff)->buffer)
#define luaZ_sizebuffer(buff) ((buff)->buffsize)
#define luaZ_bufflen(buff) ((buff)->n)
#define luaZ_resetbuffer(buff) ((buff)->n = 0)
#define luaZ_resizebuffer(L, buff, size)
#define luaZ_freebuffer(L, buff) luaZ_resizebuffer(L, buff, 0)
Typedefs
typedef struct Zio ZIO
typedef struct Mbuffer Mbuffer
Functions
LUAI_FUNC char * luaZ_openspace (lua_State *L, Mbuffer *buff, size_t n)
LUAI_FUNC void luaZ_init (lua_State *L, ZIO *z, lua_Reader reader, void *data)
LUAI_FUNC size_t luaZ_read (ZIO *z, void *b, size_t n)
LUAI_FUNC int luaZ_fill (ZIO *z)
Macro Definition Documentation
EOZ
#define EOZ (-1) /* end of stream */
Definition at line 16 of file lua-5.2.4/src/lzio.h.
luaZ_buffer
#define luaZ_buffer (buff) ((buff)->buffer)
Definition at line 31 of file lua-5.2.4/src/lzio.h.
luaZ_bufflen
#define luaZ_bufflen (buff) ((buff)->n)
Definition at line 33 of file lua-5.2.4/src/lzio.h.
luaZ_freebuffer
#define luaZ_freebuffer (L, buff) luaZ_resizebuffer(L, buff, 0)
Definition at line 42 of file lua-5.2.4/src/lzio.h.
luaZ_initbuffer
#define luaZ_initbuffer (L, buff) ((buff)->buffer = NULL, (buff)->buffsize = 0)
Definition at line 29 of file lua-5.2.4/src/lzio.h.
luaZ_resetbuffer
#define luaZ_resetbuffer (buff) ((buff)->n = 0)
Definition at line 35 of file lua-5.2.4/src/lzio.h.
luaZ_resizebuffer
#define luaZ_resizebuffer (L, buff, size)
Value:
    (luaM_reallocvector(L, (buff)->buffer, (buff)->buffsize, size, char), \
    (buff)->buffsize = size)
Definition at line 38 of file lua-5.2.4/src/lzio.h.
#define luaZ_resizebuffer(L, buff, size) \
    (luaM_reallocvector(L, (buff)->buffer, (buff)->buffsize, size, char), \
    (buff)->buffsize = size)
luaZ_sizebuffer
#define luaZ_sizebuffer (buff) ((buff)->buffsize)
Definition at line 32 of file lua-5.2.4/src/lzio.h.
zgetc
#define zgetc (z) (((z)->n--)>0 ? cast_uchar(*(z)->p++) : luaZ_fill(z))
Definition at line 20 of file lua-5.2.4/src/lzio.h.
Typedef Documentation
Mbuffer
typedef struct Mbuffer Mbuffer
ZIO
typedef struct Zio ZIO
Definition at line 18 of file lua-5.2.4/src/lzio.h.
Function Documentation
luaZ_fill()
LUAI_FUNC int luaZ_fill (ZIO * z)
Definition at line 21 of file lua-5.1.5/src/lzio.c.
                       {
  size_t size;
  lua_State *L = z->L;
  const char *buff;
  lua_unlock(L);
  buff = z->reader(L, z->data, &size);
  lua_lock(L);
  if (buff == NULL || size == 0) return EOZ;
  z->n = size - 1;
  z->p = buff;
  return char2int(*(z->p++));
}
luaZ_init()
LUAI_FUNC void luaZ_init (lua_State * L, ZIO * z, lua_Reader reader, void * data)
Definition at line 48 of file lua-5.1.5/src/lzio.c.
{
  z->L = L;
  z->reader = reader;
  z->data = data;
  z->n = 0;
  z->p = NULL;
}
luaZ_openspace()
LUAI_FUNC char * luaZ_openspace (lua_State * L, Mbuffer * buff, size_t n)
Definition at line 74 of file lua-5.1.5/src/lzio.c.
{
  if (n > buff->buffsize) {
    if (n < LUA_MINBUFFER) n = LUA_MINBUFFER;
    luaZ_resizebuffer(L, buff, n);
  }
  return buff->buffer;
}
References Mbuffer::buffer, Mbuffer::buffsize, LUA_MINBUFFER, and luaZ_resizebuffer.
Referenced by LoadString(), LoadString(), luaV_concat(), and luaV_concat().
luaZ_read()
LUAI_FUNC size_t luaZ_read (ZIO * z, void * b, size_t n)
Definition at line 58 of file lua-5.1.5/src/lzio.c.
{
  while (n) {
    size_t m;
    if (luaZ_lookahead(z) == EOZ)
      return n;  /* return number of missing bytes */
    m = (n <= z->n) ? n : z->n;  /* min. between n and z->n */
    memcpy(b, z->p, m);
    z->n -= m;
    z->p += m;
    b = (char *)b + m;
    n -= m;
  }
  return 0;
}