Github User Fetcher: ldebug.h File Reference
ldebug.h File Reference
#include "lstate.h"
Macros
#define pcRel(pc, p) (cast_int((pc) - (p)->code) - 1)
#define ci_func(ci) (clLvalue(s2v((ci)->func)))
#define resethookcount(L) (L->hookcount = L->basehookcount)
#define ABSLINEINFO (-0x80)
#define MAXIWTHABS 128
Functions
LUAI_FUNC int luaG_getfuncline (const Proto *f, int pc)
LUAI_FUNC const char * luaG_findlocal (lua_State *L, CallInfo *ci, int n, StkId *pos)
LUAI_FUNC l_noret luaG_typeerror (lua_State *L, const TValue *o, const char *opname)
LUAI_FUNC l_noret luaG_callerror (lua_State *L, const TValue *o)
LUAI_FUNC l_noret luaG_forerror (lua_State *L, const TValue *o, const char *what)
LUAI_FUNC l_noret luaG_concaterror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_opinterror (lua_State *L, const TValue *p1, const TValue *p2, const char *msg)
LUAI_FUNC l_noret luaG_tointerror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_ordererror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_runerror (lua_State *L, const char *fmt,...)
LUAI_FUNC const char * luaG_addinfo (lua_State *L, const char *msg, TString *src, int line)
LUAI_FUNC l_noret luaG_errormsg (lua_State *L)
LUAI_FUNC int luaG_traceexec (lua_State *L, const Instruction *pc)
Macro Definition Documentation
ABSLINEINFO
#define ABSLINEINFO (-0x80)
Definition at line 27 of file lua-5.4.3/src/ldebug.h.
Referenced by changedline(), luaG_getfuncline(), nextline(), removelastlineinfo(), and savelineinfo().
ci_func
#define ci_func (ci) (clLvalue(s2v((ci)->func)))
Definition at line 18 of file lua-5.4.3/src/ldebug.h.
MAXIWTHABS
#define MAXIWTHABS 128
Definition at line 35 of file lua-5.4.3/src/ldebug.h.
Referenced by changedline(), getbaseline(), removelastlineinfo(), and savelineinfo().
pcRel
#define pcRel (pc, p) (cast_int((pc) - (p)->code) - 1)
Definition at line 14 of file lua-5.4.3/src/ldebug.h.
resethookcount
#define resethookcount (L) (L->hookcount = L->basehookcount)
Definition at line 21 of file lua-5.4.3/src/ldebug.h.
Function Documentation
luaG_addinfo()
LUAI_FUNC const char * luaG_addinfo (lua_State * L, const char * msg, TString * src, int line)
Definition at line 629 of file lua-5.3.6/src/ldebug.c.
{
  char buff[LUA_IDSIZE];
  if (src)
    luaO_chunkid(buff, getstr(src), LUA_IDSIZE);
  else {  /* no source available; use "?" instead */
    buff[0] = '?'; buff[1] = '\0';
  }
  return luaO_pushfstring(L, "%s:%d: %s", buff, line, msg);
}
References getstr, LUA_IDSIZE, luaO_chunkid(), luaO_pushfstring(), and tsslen.
Referenced by lexerror(), lexerror(), and luaG_runerror().
luaG_callerror()
LUAI_FUNC l_noret luaG_callerror (lua_State * L, const TValue * o)
Definition at line 698 of file lua-5.4.3/src/ldebug.c.
{
  CallInfo *ci = L->ci;
  const char *name = NULL;  /* to avoid warnings */
  const char *what = (isLua(ci)) ? funcnamefromcode(L, ci, &name) : NULL;
  if (what != NULL) {
    const char *t = luaT_objtypename(L, o);
    luaG_runerror(L, "%s '%s' is not callable (a %s value)", what, name, t);
  }
  else
    luaG_typeerror(L, o, "call");
}
References lua_State::ci, funcnamefromcode(), isLua, luaG_runerror(), luaG_typeerror(), luaT_objtypename(), name, and NULL.
Referenced by luaD_tryfuncTM().
luaG_concaterror()
LUAI_FUNC l_noret luaG_concaterror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 592 of file lua-5.3.6/src/ldebug.c.
{
  if (ttisstring(p1) || cvt2str(p1)) p1 = p2;
  luaG_typeerror(L, p1, "concatenate");
}
References cvt2str, luaG_typeerror(), and ttisstring.
luaG_errormsg()
LUAI_FUNC l_noret luaG_errormsg (lua_State * L)
Definition at line 618 of file lua-5.1.5/src/ldebug.c.
{
  if (L->errfunc != 0) {  /* is there an error handling function? */
    StkId errfunc = restorestack(L, L->errfunc);
    if (!ttisfunction(errfunc)) luaD_throw(L, LUA_ERRERR);
    setobjs2s(L, L->top, L->top - 1);  /* move argument */
    setobjs2s(L, L->top - 1, errfunc);  /* push function */
    incr_top(L);
    luaD_call(L, L->top - 2, 1);  /* call it */
  }
  luaD_throw(L, LUA_ERRRUN);
}
References lua_State::errfunc, incr_top, lua_assert, LUA_ERRERR, LUA_ERRRUN, luaD_call(), luaD_callnoyield(), luaD_throw(), restorestack, s2v, setobjs2s, lua_State::top, and ttisfunction.
Referenced by lua_error(), and luaG_runerror().
luaG_findlocal()
LUAI_FUNC const char * luaG_findlocal (lua_State * L, CallInfo * ci, int n, StkId * pos)
Definition at line 196 of file lua-5.4.3/src/ldebug.c.
{
  StkId base = ci->func + 1;
  const char *name = NULL;
  if (isLua(ci)) {
    if (n < 0)  /* access to vararg values? */
      return findvararg(ci, n, pos);
    else
      name = luaF_getlocalname(ci_func(ci)->p, n, currentpc(ci));
  }
  if (name == NULL) {  /* no 'standard' name? */
    StkId limit = (ci == L->ci) ? L->top : ci->next->func;
    if (limit - base >= n && n > 0) {  /* is 'n' inside 'ci' stack? */
      /* generic name for any valid slot */
      name = isLua(ci) ? "(temporary)" : "(C temporary)";
    }
    else
      return NULL;  /* no name */
  }
  if (pos)
    *pos = base + (n - 1);
  return name;
}
References lua_State::ci, ci_func, currentpc(), findvararg(), CallInfo::func, isLua, luaF_getlocalname(), name, CallInfo::next, NULL, and lua_State::top.
Referenced by checkclosemth(), lua_getlocal(), and lua_setlocal().
luaG_forerror()
LUAI_FUNC l_noret luaG_forerror (lua_State * L, const TValue * o, const char * what)
Definition at line 711 of file lua-5.4.3/src/ldebug.c.
{
  luaG_runerror(L, "bad 'for' %s (number expected, got %s)",
                   what, luaT_objtypename(L, o));
}
References luaG_runerror(), and luaT_objtypename().
Referenced by forlimit(), and forprep().
luaG_getfuncline()
LUAI_FUNC int luaG_getfuncline (const Proto * f, int pc)
Definition at line 83 of file lua-5.4.3/src/ldebug.c.
{
  if (f->lineinfo == NULL)  /* no debug information? */
    return -1;
  else {
    int basepc;
    int baseline = getbaseline(f, pc, &basepc);
    while (basepc++ < pc) {  /* walk until given instruction */
      lua_assert(f->lineinfo[basepc] != ABSLINEINFO);
      baseline += f->lineinfo[basepc];  /* correct line */
    }
    return baseline;
  }
}
References ABSLINEINFO, getbaseline(), Proto::lineinfo, lua_assert, and NULL.
Referenced by changedline(), getcurrentline(), luaG_traceexec(), nextline(), and PrintCode().
luaG_opinterror()
LUAI_FUNC l_noret luaG_opinterror (lua_State * L, const TValue * p1, const TValue * p2, const char * msg)
Definition at line 598 of file lua-5.3.6/src/ldebug.c.
{
  lua_Number temp;
  if (!tonumber(p1, &temp))  /* first operand is wrong? */
    p2 = p1;  /* now second is wrong */
  luaG_typeerror(L, p2, msg);
}
References luaG_typeerror(), tonumber, and ttisnumber.
Referenced by luaT_trybinTM().
luaG_ordererror()
LUAI_FUNC l_noret luaG_ordererror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 596 of file lua-5.1.5/src/ldebug.c.
{
  const char *t1 = luaT_typenames[ttype(p1)];
  const char *t2 = luaT_typenames[ttype(p2)];
  if (t1[2] == t2[2])
    luaG_runerror(L, "attempt to compare two %s values", t1);
  else
    luaG_runerror(L, "attempt to compare %s with %s", t1, t2);
  return 0;
}
References luaG_runerror(), luaT_objtypename(), luaT_typenames, objtypename, and ttype.
Referenced by lessequal(), luaT_callorderTM(), luaV_lessequal(), and luaV_lessthan().
luaG_runerror()
LUAI_FUNC l_noret luaG_runerror (lua_State * L, const char * fmt, ...)
Definition at line 631 of file lua-5.1.5/src/ldebug.c.
{
  va_list argp;
  va_start(argp, fmt);
  addinfo(L, luaO_pushvfstring(L, fmt, argp));
  va_end(argp);
  luaG_errormsg(L);
}
References addinfo(), addinfo(), lua_State::ci, ci_func, currentline(), getcurrentline(), isLua, luaC_checkGC, luaG_addinfo(), luaG_errormsg(), and luaO_pushvfstring().
Referenced by checkclosemth(), findindex(), findindex(), findindex(), findindex(), forprep(), growCI(), lua_pushnumber(), lua_replace(), lua_yield(), lua_yieldk(), lua_yieldk(), luaD_call(), luaD_call(), luaD_growstack(), luaD_growstack(), luaE_checkcstack(), luaG_callerror(), luaG_forerror(), luaG_ordererror(), luaG_tointerror(), luaG_typeerror(), luaH_newkey(), luaH_newkey(), luaH_set(), luaM_growaux_(), luaM_growaux_(), luaM_growaux_(), luaM_toobig(), luaO_pushvfstring(), luaV_concat(), luaV_concat(), luaV_div(), luaV_execute(), luaV_execute(), luaV_finishget(), luaV_finishset(), luaV_finishset(), luaV_gettable(), luaV_idiv(), luaV_mod(), luaV_settable(), setnodevector(), setnodevector(), setnodevector(), setnodevector(), and stackerror().
luaG_tointerror()
LUAI_FUNC l_noret luaG_tointerror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 610 of file lua-5.3.6/src/ldebug.c.
{
  lua_Integer temp;
  if (!tointeger(p1, &temp))
    p2 = p1;
  luaG_runerror(L, "number%s has no integer representation", varinfo(L, p2));
}
References LUA_FLOORN2I, luaG_runerror(), luaV_tointegerns(), tointeger, varinfo(), and varinfo().
Referenced by luaT_trybinTM().
luaG_traceexec()
LUAI_FUNC int luaG_traceexec (lua_State * L, const Instruction * pc)
Definition at line 833 of file lua-5.4.3/src/ldebug.c.
{
  CallInfo *ci = L->ci;
  lu_byte mask = L->hookmask;
  const Proto *p = ci_func(ci)->p;
  int counthook;
  if (!(mask & (LUA_MASKLINE | LUA_MASKCOUNT))) {  /* no hooks? */
    ci->u.l.trap = 0;  /* don't need to stop again */
    return 0;  /* turn off 'trap' */
  }
  pc++;  /* reference is always next instruction */
  ci->u.l.savedpc = pc;  /* save 'pc' */
  counthook = (--L->hookcount == 0 && (mask & LUA_MASKCOUNT));
  if (counthook)
    resethookcount(L);  /* reset count */
  else if (!(mask & LUA_MASKLINE))
    return 1;  /* no line hook and count != 0; nothing to be done now */
  if (ci->callstatus & CIST_HOOKYIELD) {  /* called hook last time? */
    ci->callstatus &= ~CIST_HOOKYIELD;  /* erase mark */
    return 1;  /* do not call hook again (VM yielded, so it did not move) */
  }
  if (!isIT(*(ci->u.l.savedpc - 1)))  /* top not being used? */
    L->top = ci->top;  /* correct top */
  if (counthook)
    luaD_hook(L, LUA_HOOKCOUNT, -1, 0, 0);  /* call count hook */
  if (mask & LUA_MASKLINE) {
    /* 'L->oldpc' may be invalid; use zero in this case */
    int oldpc = (L->oldpc < p->sizecode) ? L->oldpc : 0;
    int npci = pcRel(pc, p);
    if (npci <= oldpc ||  /* call hook when jump back (loop), */
        changedline(p, oldpc, npci)) {  /* or when enter new line */
      int newline = luaG_getfuncline(p, npci);
      luaD_hook(L, LUA_HOOKLINE, newline, 0, 0);  /* call line hook */
    }
    L->oldpc = npci;  /* 'pc' of last call to line hook */
  }
  if (L->status == LUA_YIELD) {  /* did hook yield? */
    if (counthook)
      L->hookcount = 1;  /* undo decrement to zero */
    ci->u.l.savedpc--;  /* undo increment (resume will increment it again) */
    ci->callstatus |= CIST_HOOKYIELD;  /* mark that it yielded */
    luaD_throw(L, LUA_YIELD);
  }
  return 1;  /* keep 'trap' on */
}
References CallInfo::callstatus, changedline(), lua_State::ci, ci_func, CIST_HOOKYIELD, lua_State::hookcount, lua_State::hookmask, isIT, CallInfo::l, LUA_HOOKCOUNT, LUA_HOOKLINE, LUA_MASKCOUNT, LUA_MASKLINE, LUA_YIELD, luaD_hook(), luaD_throw(), luaG_getfuncline(), mask, lua_State::oldpc, Proto::p, pcRel, resethookcount, CallInfo::savedpc, Proto::sizecode, lua_State::status, CallInfo::top, lua_State::top, CallInfo::trap, and CallInfo::u.
luaG_typeerror()
LUAI_FUNC l_noret luaG_typeerror (lua_State * L, const TValue * o, const char * opname)
Definition at line 567 of file lua-5.1.5/src/ldebug.c.
{
  const char *name = NULL;
  const char *t = luaT_typenames[ttype(o)];
  const char *kind = (isinstack(L->ci, o)) ?
                         getobjname(L, L->ci, cast_int(o - L->base), &name) :
                         NULL;
  if (kind)
    luaG_runerror(L, "attempt to %s %s " LUA_QS " (a %s value)",
                op, kind, name, t);
  else
    luaG_runerror(L, "attempt to %s a %s value", op, t);
}
References CallInfo::base, lua_State::base, cast_int, lua_State::ci, ci_func, currentpc(), getobjname(), getobjname(), getupvalname(), isinstack(), isinstack(), isLua, CallInfo::l, LUA_QS, luaG_runerror(), luaT_objtypename(), luaT_typenames, name, NULL, objtypename, ttype, CallInfo::u, varinfo(), and varinfo().
Referenced by luaG_aritherror(), luaG_callerror(), luaG_concaterror(), luaG_concaterror(), luaG_opinterror(), luaV_execute(), luaV_finishget(), luaV_finishset(), luaV_finishset(), luaV_gettable(), luaV_objlen(), luaV_settable(), tryfuncTM(), tryfuncTM(), and tryfuncTM().