Github User Fetcher: loslib.c File Reference
loslib.c File Reference
#include <errno.h>
#include <locale.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define loslib_c
#define LUA_LIB
#define LUA_STRFTIMEOPTIONS { "aAbBcdHIjmMpSUwWxXyYz%", "" }
#define LUA_TMPNAMBUFSIZE L_tmpnam
#define lua_tmpnam(b, e) { e = (tmpnam(b) == NULL); }
#define l_gmtime(t, r) ((void)r, gmtime(t))
#define l_localtime(t, r) ((void)r, localtime(t))
Functions
static int os_execute (lua_State *L)
static int os_remove (lua_State *L)
static int os_rename (lua_State *L)
static int os_tmpname (lua_State *L)
static int os_getenv (lua_State *L)
static int os_clock (lua_State *L)
static void setfield (lua_State *L, const char *key, int value)
static void setboolfield (lua_State *L, const char *key, int value)
static int getboolfield (lua_State *L, const char *key)
static int getfield (lua_State *L, const char *key, int d)
static const char * checkoption (lua_State *L, const char *conv, char *buff)
static int os_date (lua_State *L)
static int os_time (lua_State *L)
static int os_difftime (lua_State *L)
static int os_setlocale (lua_State *L)
static int os_exit (lua_State *L)
LUAMOD_API int luaopen_os (lua_State *L)
Variables
static const luaL_Reg syslib []
Macro Definition Documentation
l_gmtime
#define l_gmtime (t, r) ((void)r, gmtime(t))
Definition at line 73 of file lua-5.2.4/src/loslib.c.
Referenced by os_date().
l_localtime
#define l_localtime (t, r) ((void)r, localtime(t))
Definition at line 74 of file lua-5.2.4/src/loslib.c.
Referenced by os_date().
loslib_c
#define loslib_c
Definition at line 14 of file lua-5.2.4/src/loslib.c.
LUA_LIB
#define LUA_LIB
Definition at line 15 of file lua-5.2.4/src/loslib.c.
LUA_STRFTIMEOPTIONS
#define LUA_STRFTIMEOPTIONS { "aAbBcdHIjmMpSUwWxXyYz%", "" }
Definition at line 29 of file lua-5.2.4/src/loslib.c.
Referenced by checkoption().
lua_tmpnam
#define lua_tmpnam (b, e) { e = (tmpnam(b) == NULL); }
Definition at line 57 of file lua-5.2.4/src/loslib.c.
Referenced by os_tmpname(), and os_tmpname().
LUA_TMPNAMBUFSIZE
#define LUA_TMPNAMBUFSIZE L_tmpnam
Definition at line 56 of file lua-5.2.4/src/loslib.c.
Referenced by os_tmpname(), and os_tmpname().
Function Documentation
checkoption()
static const char * checkoption (lua_State * L, const char * conv, char * buff) static
Definition at line 171 of file lua-5.2.4/src/loslib.c.
{
  static const char *const options[] = LUA_STRFTIMEOPTIONS;
  unsigned int i;
  for (i = 0; i < sizeof(options)/sizeof(options[0]); i += 2) {
    if (*conv != '\0' && strchr(options[i], *conv) != NULL) {
      buff[1] = *conv;
      if (*options[i + 1] == '\0') {  /* one-char conversion specifier? */
        buff[2] = '\0';  /* end buffer */
        return conv + 1;
      }
      else if (*(conv + 1) != '\0' &&
               strchr(options[i + 1], *(conv + 1)) != NULL) {
        buff[2] = *(conv + 1);  /* valid two-char conversion specifier */
        buff[3] = '\0';  /* end buffer */
        return conv + 2;
      }
    }
  }
  luaL_argerror(L, 1,
    lua_pushfstring(L, "invalid conversion specifier '%%%s'", conv));
  return conv;  /* to avoid warnings */
}
References lua_pushfstring(), LUA_STRFTIMEOPTIONS, luaL_argerror(), and NULL.
Referenced by os_date().
getboolfield()
static int getboolfield (lua_State * L, const char * key) static
Definition at line 148 of file lua-5.2.4/src/loslib.c.
{
  int res;
  lua_getfield(L, -1, key);
  res = lua_isnil(L, -1) ? -1 : lua_toboolean(L, -1);
  lua_pop(L, 1);
  return res;
}
References lua_getfield(), lua_isnil, lua_pop, and lua_toboolean().
Referenced by os_time().
getfield()
static int getfield (lua_State * L, const char * key, int d) static
Definition at line 157 of file lua-5.2.4/src/loslib.c.
{
  int res, isnum;
  lua_getfield(L, -1, key);
  res = (int)lua_tointegerx(L, -1, &isnum);
  if (!isnum) {
    if (d < 0)
      return luaL_error(L, "field " LUA_QS " missing in date table", key);
    res = d;
  }
  lua_pop(L, 1);
  return res;
}
References lua_getfield(), lua_pop, LUA_QS, lua_tointegerx(), and luaL_error().
Referenced by os_time().
luaopen_os()
LUAMOD_API int luaopen_os (lua_State * L)
Definition at line 319 of file lua-5.2.4/src/loslib.c.
{
  luaL_newlib(L, syslib);
  return 1;
}
References luaL_newlib, and syslib.
os_clock()
static int os_clock (lua_State * L) static
Definition at line 122 of file lua-5.2.4/src/loslib.c.
{
  lua_pushnumber(L, ((lua_Number)clock())/(lua_Number)CLOCKS_PER_SEC);
  return 1;
}
References lua_pushnumber().
os_date()
static int os_date (lua_State * L) static
Definition at line 195 of file lua-5.2.4/src/loslib.c.
{
  const char *s = luaL_optstring(L, 1, "%c");
  time_t t = luaL_opt(L, (time_t)luaL_checknumber, 2, time(NULL));
  struct tm tmr, *stm;
  if (*s == '!') {  /* UTC? */
    stm = l_gmtime(&t, &tmr);
    s++;  /* skip `!' */
  }
  else
    stm = l_localtime(&t, &tmr);
  if (stm == NULL)  /* invalid date? */
    lua_pushnil(L);
  else if (strcmp(s, "*t") == 0) {
    lua_createtable(L, 0, 9);  /* 9 = number of fields */
    setfield(L, "sec", stm->tm_sec);
    setfield(L, "min", stm->tm_min);
    setfield(L, "hour", stm->tm_hour);
    setfield(L, "day", stm->tm_mday);
    setfield(L, "month", stm->tm_mon+1);
    setfield(L, "year", stm->tm_year+1900);
    setfield(L, "wday", stm->tm_wday+1);
    setfield(L, "yday", stm->tm_yday+1);
    setboolfield(L, "isdst", stm->tm_isdst);
  }
  else {
    char cc[4];
    luaL_Buffer b;
    cc[0] = '%';
    luaL_buffinit(L, &b);
    while (*s) {
      if (*s != '%')  /* no conversion specifier? */
        luaL_addchar(&b, *s++);
      else {
        size_t reslen;
        char buff[200];  /* should be big enough for any conversion result */
        s = checkoption(L, s + 1, cc);
        reslen = strftime(buff, sizeof(buff), cc, stm);
        luaL_addlstring(&b, buff, reslen);
      }
    }
    luaL_pushresult(&b);
  }
  return 1;
}
References checkoption(), l_gmtime, l_localtime, lua_createtable(), lua_pushnil(), luaL_addchar, luaL_addlstring(), luaL_buffinit(), luaL_checknumber(), luaL_opt, luaL_optstring, luaL_pushresult(), NULL, s, setboolfield(), and setfield().
os_difftime()
static int os_difftime (lua_State * L) static
Definition at line 266 of file lua-5.2.4/src/loslib.c.
{
  lua_pushnumber(L, difftime((time_t)(luaL_checknumber(L, 1)),
                             (time_t)(luaL_optnumber(L, 2, 0))));
  return 1;
}
References lua_pushnumber(), luaL_checknumber(), and luaL_optnumber().
os_execute()
static int os_execute (lua_State * L) static
Definition at line 80 of file lua-5.2.4/src/loslib.c.
{
  const char *cmd = luaL_optstring(L, 1, NULL);
  int stat = system(cmd);
  if (cmd != NULL)
    return luaL_execresult(L, stat);
  else {
    lua_pushboolean(L, stat);  /* true if there is a shell */
    return 1;
  }
}
References lua_pushboolean(), luaL_execresult(), luaL_optstring, and NULL.
os_exit()
static int os_exit (lua_State * L) static
Definition at line 287 of file lua-5.2.4/src/loslib.c.
{
  int status;
  if (lua_isboolean(L, 1))
    status = (lua_toboolean(L, 1) ? EXIT_SUCCESS : EXIT_FAILURE);
  else
    status = luaL_optint(L, 1, EXIT_SUCCESS);
  if (lua_toboolean(L, 2))
    lua_close(L);
  if (L) exit(status);  /* 'if' to avoid warnings for unreachable 'return' */
  return 0;
}
References lua_close(), lua_isboolean, lua_toboolean(), and luaL_optint.
os_getenv()
static int os_getenv (lua_State * L) static
Definition at line 116 of file lua-5.2.4/src/loslib.c.
{
  lua_pushstring(L, getenv(luaL_checkstring(L, 1)));  /* if NULL push nil */
  return 1;
}
References lua_pushstring(), and luaL_checkstring.
os_remove()
static int os_remove (lua_State * L) static
Definition at line 92 of file lua-5.2.4/src/loslib.c.
{
  const char *filename = luaL_checkstring(L, 1);
  return luaL_fileresult(L, remove(filename) == 0, filename);
}
References luaL_checkstring, and luaL_fileresult().
os_rename()
static int os_rename (lua_State * L) static
Definition at line 98 of file lua-5.2.4/src/loslib.c.
{
  const char *fromname = luaL_checkstring(L, 1);
  const char *toname = luaL_checkstring(L, 2);
  return luaL_fileresult(L, rename(fromname, toname) == 0, NULL);
}
References luaL_checkstring, luaL_fileresult(), and NULL.
os_setlocale()
static int os_setlocale (lua_State * L) static
Definition at line 275 of file lua-5.2.4/src/loslib.c.
{
  static const int cat[] = {LC_ALL, LC_COLLATE, LC_CTYPE, LC_MONETARY,
                      LC_NUMERIC, LC_TIME};
  static const char *const catnames[] = {"all", "collate", "ctype", "monetary",
     "numeric", "time", NULL};
  const char *l = luaL_optstring(L, 1, NULL);
  int op = luaL_checkoption(L, 2, "all", catnames);
  lua_pushstring(L, setlocale(cat[op], l));
  return 1;
}
References lua_pushstring(), luaL_checkoption(), luaL_optstring, and NULL.
os_time()
static int os_time (lua_State * L) static
Definition at line 241 of file lua-5.2.4/src/loslib.c.
{
  time_t t;
  if (lua_isnoneornil(L, 1))  /* called without args? */
    t = time(NULL);  /* get current time */
  else {
    struct tm ts;
    luaL_checktype(L, 1, LUA_TTABLE);
    lua_settop(L, 1);  /* make sure table is at the top */
    ts.tm_sec = getfield(L, "sec", 0);
    ts.tm_min = getfield(L, "min", 0);
    ts.tm_hour = getfield(L, "hour", 12);
    ts.tm_mday = getfield(L, "day", -1);
    ts.tm_mon = getfield(L, "month", -1) - 1;
    ts.tm_year = getfield(L, "year", -1) - 1900;
    ts.tm_isdst = getboolfield(L, "isdst");
    t = mktime(&ts);
  }
  if (t == (time_t)(-1))
    lua_pushnil(L);
  else
    lua_pushnumber(L, (lua_Number)t);
  return 1;
}
References getboolfield(), getfield(), lua_isnoneornil, lua_pushnil(), lua_pushnumber(), lua_settop(), LUA_TTABLE, luaL_checktype(), and NULL.
os_tmpname()
static int os_tmpname (lua_State * L) static
Definition at line 105 of file lua-5.2.4/src/loslib.c.
{
  char buff[LUA_TMPNAMBUFSIZE];
  int err;
  lua_tmpnam(buff, err);
  if (err)
    return luaL_error(L, "unable to generate a unique filename");
  lua_pushstring(L, buff);
  return 1;
}
References lua_pushstring(), lua_tmpnam, LUA_TMPNAMBUFSIZE, and luaL_error().
setboolfield()
static void setboolfield (lua_State * L, const char * key, int value) static
Definition at line 141 of file lua-5.2.4/src/loslib.c.
{
  if (value < 0)  /* undefined? */
    return;  /* does not set field */
  lua_pushboolean(L, value);
  lua_setfield(L, -2, key);
}
References lua_pushboolean(), lua_setfield(), and value.
Referenced by os_date().
setfield()
static void setfield (lua_State * L, const char * key, int value) static
Definition at line 136 of file lua-5.2.4/src/loslib.c.
{
  lua_pushinteger(L, value);
  lua_setfield(L, -2, key);
}
References lua_pushinteger(), lua_setfield(), and value.
Referenced by os_date().
Variable Documentation
syslib
const luaL_Reg syslib[] static
Initial value:
= {
  {"clock",     os_clock},
  {"date",      os_date},
  {"difftime",  os_difftime},
  {"execute",   os_execute},
  {"exit",      os_exit},
  {"getenv",    os_getenv},
  {"remove",    os_remove},
  {"rename",    os_rename},
  {"setlocale", os_setlocale},
  {"time",      os_time},
  {"tmpname",   os_tmpname},
  {NULL, NULL}
}
Definition at line 300 of file lua-5.2.4/src/loslib.c.
{
  {"clock",     os_clock},
  {"date",      os_date},
  {"difftime",  os_difftime},
  {"execute",   os_execute},
  {"exit",      os_exit},
  {"getenv",    os_getenv},
  {"remove",    os_remove},
  {"rename",    os_rename},
  {"setlocale", os_setlocale},
  {"time",      os_time},
  {"tmpname",   os_tmpname},
  {NULL, NULL}
};
Referenced by luaopen_os().