Github User Fetcher: lobject.c File Reference
lobject.c File Reference
#include "lprefix.h"
#include <locale.h>
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lctype.h"
#include "ldebug.h"
#include "ldo.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "lvm.h"
Macros
#define lobject_c
#define LUA_CORE
#define L_MAXLENNUM 200
#define MAXBY10 cast(lua_Unsigned, LUA_MAXINTEGER / 10)
#define MAXLASTD cast_int(LUA_MAXINTEGER % 10)
#define MAXNUMBER2STR 50
#define LL(x) (sizeof(x)/sizeof(char) - 1)
#define RETS "..."
#define PRE "[string \""
#define POS "\"]"
#define addstr(a, b, l) (memcpy(a,b,(l) * sizeof(char)), a += (l))
Functions
int luaO_int2fb (unsigned int x)
int luaO_fb2int (int x)
int luaO_ceillog2 (unsigned int x)
static lua_Integer intarith (lua_State *L, int op, lua_Integer v1, lua_Integer v2)
static lua_Number numarith (lua_State *L, int op, lua_Number v1, lua_Number v2)
void luaO_arith (lua_State *L, int op, const TValue *p1, const TValue *p2, TValue *res)
int luaO_hexavalue (int c)
static int isneg (const char **s)
static const char * l_str2dloc (const char *s, lua_Number *result, int mode)
static const char * l_str2d (const char *s, lua_Number *result)
static const char * l_str2int (const char *s, lua_Integer *result)
size_t luaO_str2num (const char *s, TValue *o)
int luaO_utf8esc (char *buff, unsigned long x)
void luaO_tostring (lua_State *L, StkId obj)
static void pushstr (lua_State *L, const char *str, size_t l)
const char * luaO_pushvfstring (lua_State *L, const char *fmt, va_list argp)
const char * luaO_pushfstring (lua_State *L, const char *fmt,...)
void luaO_chunkid (char *out, const char *source, size_t bufflen)
Variables
LUAI_DDEF const TValue luaO_nilobject_ = {NILCONSTANT}
Macro Definition Documentation
addstr
#define addstr (a, b, l) (memcpy(a,b,(l) * sizeof(char)), a += (l))
Definition at line 485 of file lua-5.3.6/src/lobject.c.
Referenced by luaO_chunkid().
L_MAXLENNUM
#define L_MAXLENNUM 200
Definition at line 248 of file lua-5.3.6/src/lobject.c.
Referenced by l_str2d().
LL
#define LL (x) (sizeof(x)/sizeof(char) - 1)
Definition at line 479 of file lua-5.3.6/src/lobject.c.
Referenced by luaO_chunkid().
lobject_c
#define lobject_c
Definition at line 7 of file lua-5.3.6/src/lobject.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/lobject.c.
MAXBY10
#define MAXBY10 cast(lua_Unsigned, LUA_MAXINTEGER / 10)
Definition at line 296 of file lua-5.3.6/src/lobject.c.
Referenced by l_str2int().
MAXLASTD
#define MAXLASTD cast_int(LUA_MAXINTEGER % 10)
Definition at line 297 of file lua-5.3.6/src/lobject.c.
Referenced by l_str2int().
MAXNUMBER2STR
#define MAXNUMBER2STR 50
Definition at line 365 of file lua-5.3.6/src/lobject.c.
Referenced by luaO_tostring().
POS
#define POS "\"]"
Definition at line 483 of file lua-5.3.6/src/lobject.c.
Referenced by luaO_chunkid().
PRE
#define PRE "[string \""
Definition at line 482 of file lua-5.3.6/src/lobject.c.
Referenced by luaO_chunkid().
RETS
#define RETS "..."
Definition at line 481 of file lua-5.3.6/src/lobject.c.
Referenced by luaO_chunkid().
Function Documentation
intarith()
static lua_Integer intarith (lua_State * L, int op, lua_Integer v1, lua_Integer v2) static
Definition at line 83 of file lua-5.3.6/src/lobject.c.
{
  switch (op) {
    case LUA_OPADD: return intop(+, v1, v2);
    case LUA_OPSUB:return intop(-, v1, v2);
    case LUA_OPMUL:return intop(*, v1, v2);
    case LUA_OPMOD: return luaV_mod(L, v1, v2);
    case LUA_OPIDIV: return luaV_div(L, v1, v2);
    case LUA_OPBAND: return intop(&, v1, v2);
    case LUA_OPBOR: return intop(|, v1, v2);
    case LUA_OPBXOR: return intop(^, v1, v2);
    case LUA_OPSHL: return luaV_shiftl(v1, v2);
    case LUA_OPSHR: return luaV_shiftl(v1, -v2);
    case LUA_OPUNM: return intop(-, 0, v1);
    case LUA_OPBNOT: return intop(^, ~l_castS2U(0), v1);
    default: lua_assert(0); return 0;
  }
}
References intop, l_castS2U, lua_assert, LUA_OPADD, LUA_OPBAND, LUA_OPBNOT, LUA_OPBOR, LUA_OPBXOR, LUA_OPIDIV, LUA_OPMOD, LUA_OPMUL, LUA_OPSHL, LUA_OPSHR, LUA_OPSUB, LUA_OPUNM, luaV_div(), luaV_mod(), and luaV_shiftl().
Referenced by luaO_arith().
isneg()
static int isneg (const char ** s) static
Definition at line 169 of file lua-5.3.6/src/lobject.c.
{
  if (**s == '-') { (*s)++; return 1; }
  else if (**s == '+') (*s)++;
  return 0;
}
References s.
Referenced by l_str2int().
l_str2d()
static const char * l_str2d (const char * s, lua_Number * result) static
Definition at line 274 of file lua-5.3.6/src/lobject.c.
{
  const char *endptr;
  const char *pmode = strpbrk(s, ".xXnN");
  int mode = pmode ? ltolower(cast_uchar(*pmode)) : 0;
  if (mode == 'n')  /* reject 'inf' and 'nan' */
    return NULL;
  endptr = l_str2dloc(s, result, mode);  /* try to convert */
  if (endptr == NULL) {  /* failed? may be a different locale */
    char buff[L_MAXLENNUM + 1];
    const char *pdot = strchr(s, '.');
    if (strlen(s) > L_MAXLENNUM || pdot == NULL)
      return NULL;  /* string too long or no dot; fail */
    strcpy(buff, s);  /* copy string to buffer */
    buff[pdot - s] = lua_getlocaledecpoint();  /* correct decimal point */
    endptr = l_str2dloc(buff, result, mode);  /* try again */
    if (endptr != NULL)
      endptr = s + (endptr - buff);  /* make relative to 's' */
  }
  return endptr;
}
References cast_uchar, L_MAXLENNUM, l_str2dloc(), ltolower, lua_getlocaledecpoint, NULL, and s.
Referenced by luaO_str2num().
l_str2dloc()
static const char * l_str2dloc (const char * s, lua_Number * result, int mode) static
Definition at line 251 of file lua-5.3.6/src/lobject.c.
{
  char *endptr;
  *result = (mode == 'x') ? lua_strx2number(s, &endptr)  /* try to convert */
                          : lua_str2number(s, &endptr);
  if (endptr == s) return NULL;  /* nothing recognized? */
  while (lisspace(cast_uchar(*endptr))) endptr++;  /* skip trailing spaces */
  return (*endptr == '\0') ? endptr : NULL;  /* OK if no trailing characters */
}
References cast_uchar, lisspace, lua_str2number, lua_strx2number, NULL, and s.
Referenced by l_str2d().
l_str2int()
static const char * l_str2int (const char * s, lua_Integer * result) static
Definition at line 299 of file lua-5.3.6/src/lobject.c.
{
  lua_Unsigned a = 0;
  int empty = 1;
  int neg;
  while (lisspace(cast_uchar(*s))) s++;  /* skip initial spaces */
  neg = isneg(&s);
  if (s[0] == '0' &&
      (s[1] == 'x' || s[1] == 'X')) {  /* hex? */
    s += 2;  /* skip '0x' */
    for (; lisxdigit(cast_uchar(*s)); s++) {
      a = a * 16 + luaO_hexavalue(*s);
      empty = 0;
    }
  }
  else {  /* decimal */
    for (; lisdigit(cast_uchar(*s)); s++) {
      int d = *s - '0';
      if (a >= MAXBY10 && (a > MAXBY10 || d > MAXLASTD + neg))  /* overflow? */
        return NULL;  /* do not accept it (as integer) */
      a = a * 10 + d;
      empty = 0;
    }
  }
  while (lisspace(cast_uchar(*s))) s++;  /* skip trailing spaces */
  if (empty || *s != '\0') return NULL;  /* something wrong in the numeral */
  else {
    *result = l_castU2S((neg) ? 0u - a : a);
    return s;
  }
}
References cast_uchar, isneg(), l_castU2S, lisdigit, lisspace, lisxdigit, luaO_hexavalue(), MAXBY10, MAXLASTD, NULL, and s.
Referenced by luaO_str2num().
luaO_arith()
void luaO_arith (lua_State * L, int op, const TValue * p1, const TValue * p2, TValue * res)
Definition at line 123 of file lua-5.3.6/src/lobject.c.
{
  switch (op) {
    case LUA_OPBAND: case LUA_OPBOR: case LUA_OPBXOR:
    case LUA_OPSHL: case LUA_OPSHR:
    case LUA_OPBNOT: {  /* operate only on integers */
      lua_Integer i1; lua_Integer i2;
      if (tointeger(p1, &i1) && tointeger(p2, &i2)) {
        setivalue(res, intarith(L, op, i1, i2));
        return;
      }
      else break;  /* go to the end */
    }
    case LUA_OPDIV: case LUA_OPPOW: {  /* operate only on floats */
      lua_Number n1; lua_Number n2;
      if (tonumber(p1, &n1) && tonumber(p2, &n2)) {
        setfltvalue(res, numarith(L, op, n1, n2));
        return;
      }
      else break;  /* go to the end */
    }
    default: {  /* other operations */
      lua_Number n1; lua_Number n2;
      if (ttisinteger(p1) && ttisinteger(p2)) {
        setivalue(res, intarith(L, op, ivalue(p1), ivalue(p2)));
        return;
      }
      else if (tonumber(p1, &n1) && tonumber(p2, &n2)) {
        setfltvalue(res, numarith(L, op, n1, n2));
        return;
      }
      else break;  /* go to the end */
    }
  }
  /* could not perform raw operation; try metamethod */
  lua_assert(L != NULL);  /* should not fail when folding (compile time) */
  luaT_trybinTM(L, p1, p2, res, cast(TMS, (op - LUA_OPADD) + TM_ADD));
}
References cast, intarith(), ivalue, lua_assert, LUA_OPADD, LUA_OPBAND, LUA_OPBNOT, LUA_OPBOR, LUA_OPBXOR, LUA_OPDIV, LUA_OPPOW, LUA_OPSHL, LUA_OPSHR, luaT_trybinTM(), NULL, numarith(), setfltvalue, setivalue, TM_ADD, tointeger, tonumber, and ttisinteger.
luaO_ceillog2()
int luaO_ceillog2 (unsigned int x)
Definition at line 65 of file lua-5.3.6/src/lobject.c.
{
  static const lu_byte log_2[256] = {  /* log_2[i] = ceil(log2(i - 1)) */
    0,1,2,2,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
    7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
    7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
  };
  int l = 0;
  x--;
  while (x >= 256) { l += 8; x >>= 8; }
  return l + log_2[x];
}
luaO_chunkid()
void luaO_chunkid (char * out, const char * source, size_t bufflen)
Definition at line 487 of file lua-5.3.6/src/lobject.c.
{
  size_t l = strlen(source);
  if (*source == '=') {  /* 'literal' source */
    if (l <= bufflen)  /* small enough? */
      memcpy(out, source + 1, l * sizeof(char));
    else {  /* truncate it */
      addstr(out, source + 1, bufflen - 1);
      *out = '\0';
    }
  }
  else if (*source == '@') {  /* file name */
    if (l <= bufflen)  /* small enough? */
      memcpy(out, source + 1, l * sizeof(char));
    else {  /* add '...' before rest of name */
      addstr(out, RETS, LL(RETS));
      bufflen -= LL(RETS);
      memcpy(out, source + 1 + l - bufflen, bufflen * sizeof(char));
    }
  }
  else {  /* string; format as [string "source"] */
    const char *nl = strchr(source, '\n');  /* find first new line (if any) */
    addstr(out, PRE, LL(PRE));  /* add prefix */
    bufflen -= LL(PRE RETS POS) + 1;  /* save space for prefix+suffix+'\0' */
    if (l < bufflen && nl == NULL) {  /* small one-line source? */
      addstr(out, source, l);  /* keep it */
    }
    else {
      if (nl != NULL) l = nl - source;  /* stop at first newline */
      if (l > bufflen) l = bufflen;
      addstr(out, source, l);
      addstr(out, RETS, LL(RETS));
    }
    memcpy(out, POS, (LL(POS) + 1) * sizeof(char));
  }
}
References addstr, bufflen, LL, NULL, POS, PRE, and RETS.
luaO_fb2int()
int luaO_fb2int (int x)
Definition at line 57 of file lua-5.3.6/src/lobject.c.
{
  return (x < 8) ? x : ((x & 7) + 8) << ((x >> 3) - 1);
}
luaO_hexavalue()
int luaO_hexavalue (int c)
Definition at line 163 of file lua-5.3.6/src/lobject.c.
{
  if (lisdigit(c)) return c - '0';
  else return (ltolower(c) - 'a') + 10;
}
References lisdigit, and ltolower.
Referenced by l_str2int().
luaO_int2fb()
int luaO_int2fb (unsigned int x)
Definition at line 41 of file lua-5.3.6/src/lobject.c.
{
  int e = 0;  /* exponent */
  if (x < 8) return x;
  while (x >= (8 << 4)) {  /* coarse steps */
    x = (x + 0xf) >> 4;  /* x = ceil(x / 16) */
    e += 4;
  }
  while (x >= (8 << 1)) {  /* fine steps */
    x = (x + 1) >> 1;  /* x = ceil(x / 2) */
    e++;
  }
  return ((e+1) << 3) | (cast_int(x) - 8);
}
References cast_int.
luaO_pushfstring()
const char * luaO_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 468 of file lua-5.3.6/src/lobject.c.
{
  const char *msg;
  va_list argp;
  va_start(argp, fmt);
  msg = luaO_pushvfstring(L, fmt, argp);
  va_end(argp);
  return msg;
}
References luaO_pushvfstring().
Referenced by luaO_pushvfstring().
luaO_pushvfstring()
const char * luaO_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 400 of file lua-5.3.6/src/lobject.c.
{
  int n = 0;
  for (;;) {
    const char *e = strchr(fmt, '%');
    if (e == NULL) break;
    pushstr(L, fmt, e - fmt);
    switch (*(e+1)) {
      case 's': {  /* zero-terminated string */
        const char *s = va_arg(argp, char *);
        if (s == NULL) s = "(null)";
        pushstr(L, s, strlen(s));
        break;
      }
      case 'c': {  /* an 'int' as a character */
        char buff = cast(char, va_arg(argp, int));
        if (lisprint(cast_uchar(buff)))
          pushstr(L, &buff, 1);
        else  /* non-printable character; print its code */
          luaO_pushfstring(L, "<\\%d>", cast_uchar(buff));
        break;
      }
      case 'd': {  /* an 'int' */
        setivalue(L->top, va_arg(argp, int));
        goto top2str;
      }
      case 'I': {  /* a 'lua_Integer' */
        setivalue(L->top, cast(lua_Integer, va_arg(argp, l_uacInt)));
        goto top2str;
      }
      case 'f': {  /* a 'lua_Number' */
        setfltvalue(L->top, cast_num(va_arg(argp, l_uacNumber)));
      top2str:  /* convert the top element to a string */
        luaD_inctop(L);
        luaO_tostring(L, L->top - 1);
        break;
      }
      case 'p': {  /* a pointer */
        char buff[4*sizeof(void *) + 8]; /* should be enough space for a '%p' */
        void *p = va_arg(argp, void *);
        int l = lua_pointer2str(buff, sizeof(buff), p);
        pushstr(L, buff, l);
        break;
      }
      case 'U': {  /* an 'int' as a UTF-8 sequence */
        char buff[UTF8BUFFSZ];
        int l = luaO_utf8esc(buff, cast(long, va_arg(argp, long)));
        pushstr(L, buff + UTF8BUFFSZ - l, l);
        break;
      }
      case '%': {
        pushstr(L, "%", 1);
        break;
      }
      default: {
        luaG_runerror(L, "invalid option '%%%c' to 'lua_pushfstring'",
                         *(e + 1));
      }
    }
    n += 2;
    fmt = e+2;
  }
  luaD_checkstack(L, 1);
  pushstr(L, fmt, strlen(fmt));
  if (n > 0) luaV_concat(L, n + 1);
  return svalue(L->top - 1);
}
References cast, cast_num, cast_uchar, lisprint, lua_pointer2str, luaD_checkstack, luaD_inctop(), luaG_runerror(), luaO_pushfstring(), luaO_tostring(), luaO_utf8esc(), luaV_concat(), NULL, pushstr(), s, setfltvalue, setivalue, svalue, lua_State::top, and UTF8BUFFSZ.
Referenced by luaO_pushfstring().
luaO_str2num()
size_t luaO_str2num (const char * s, TValue * o)
Definition at line 331 of file lua-5.3.6/src/lobject.c.
{
  lua_Integer i; lua_Number n;
  const char *e;
  if ((e = l_str2int(s, &i)) != NULL) {  /* try as an integer */
    setivalue(o, i);
  }
  else if ((e = l_str2d(s, &n)) != NULL) {  /* else try as a float */
    setfltvalue(o, n);
  }
  else
    return 0;  /* conversion failed */
  return (e - s) + 1;  /* success; return string size */
}
References l_str2d(), l_str2int(), NULL, s, setfltvalue, and setivalue.
Referenced by l_strton(), lua_stringtonumber(), luaV_tointeger(), luaV_tonumber_(), read_numeral(), and read_numeral().
luaO_tostring()
void luaO_tostring (lua_State * L, StkId obj)
Definition at line 371 of file lua-5.3.6/src/lobject.c.
{
  char buff[MAXNUMBER2STR];
  size_t len;
  lua_assert(ttisnumber(obj));
  if (ttisinteger(obj))
    len = lua_integer2str(buff, sizeof(buff), ivalue(obj));
  else {
    len = lua_number2str(buff, sizeof(buff), fltvalue(obj));
#if !defined(LUA_COMPAT_FLOATSTRING)
    if (buff[strspn(buff, "-0123456789")] == '\0') {  /* looks like an int? */
      buff[len++] = lua_getlocaledecpoint();
      buff[len++] = '0';  /* adds '.0' to result */
    }
#endif
  }
  setsvalue2s(L, obj, luaS_newlstr(L, buff, len));
}
References fltvalue, ivalue, lua_assert, lua_getlocaledecpoint, lua_integer2str, lua_number2str, luaS_newlstr(), MAXNUMBER2STR, setsvalue2s, ttisinteger, and ttisnumber.
Referenced by lua_tolstring(), and luaO_pushvfstring().
luaO_utf8esc()
int luaO_utf8esc (char * buff, unsigned long x)
Definition at line 346 of file lua-5.3.6/src/lobject.c.
{
  int n = 1;  /* number of bytes put in buffer (backwards) */
  lua_assert(x <= 0x10FFFF);
  if (x < 0x80)  /* ascii? */
    buff[UTF8BUFFSZ - 1] = cast(char, x);
  else {  /* need continuation bytes */
    unsigned int mfb = 0x3f;  /* maximum that fits in first byte */
    do {  /* add continuation bytes */
      buff[UTF8BUFFSZ - (n++)] = cast(char, 0x80 | (x & 0x3f));
      x >>= 6;  /* remove added bits */
      mfb >>= 1;  /* now there is one less bit available in first byte */
    } while (x > mfb);  /* still needs continuation byte? */
    buff[UTF8BUFFSZ - n] = cast(char, (~mfb << 1) | x);  /* add first byte */
  }
  return n;
}
References cast, lua_assert, and UTF8BUFFSZ.
Referenced by luaO_pushvfstring(), utf8esc(), and utf8esc().
numarith()
static lua_Number numarith (lua_State * L, int op, lua_Number v1, lua_Number v2) static
Definition at line 103 of file lua-5.3.6/src/lobject.c.
{
  switch (op) {
    case LUA_OPADD: return luai_numadd(L, v1, v2);
    case LUA_OPSUB: return luai_numsub(L, v1, v2);
    case LUA_OPMUL: return luai_nummul(L, v1, v2);
    case LUA_OPDIV: return luai_numdiv(L, v1, v2);
    case LUA_OPPOW: return luai_numpow(L, v1, v2);
    case LUA_OPIDIV: return luai_numidiv(L, v1, v2);
    case LUA_OPUNM: return luai_numunm(L, v1);
    case LUA_OPMOD: {
      lua_Number m;
      luai_nummod(L, v1, v2, m);
      return m;
    }
    default: lua_assert(0); return 0;
  }
}
References lua_assert, LUA_OPADD, LUA_OPDIV, LUA_OPIDIV, LUA_OPMOD, LUA_OPMUL, LUA_OPPOW, LUA_OPSUB, LUA_OPUNM, luai_numadd, luai_numdiv, luai_numidiv, luai_nummod, luai_nummul, luai_numpow, luai_numsub, and luai_numunm.
Referenced by luaO_arith().
pushstr()
static void pushstr (lua_State * L, const char * str, size_t l) static
Definition at line 390 of file lua-5.3.6/src/lobject.c.
{
  setsvalue2s(L, L->top, luaS_newlstr(L, str, l));
  luaD_inctop(L);
}
References luaD_inctop(), luaS_newlstr(), setsvalue2s, and lua_State::top.
Referenced by luaO_pushvfstring().
Variable Documentation
luaO_nilobject_
LUAI_DDEF const TValue luaO_nilobject_ = {NILCONSTANT}
Definition at line 33 of file lua-5.3.6/src/lobject.c.
{NILCONSTANT};