Github User Fetcher: lstring.c File Reference
lstring.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
Macros
#define lstring_c
#define LUA_CORE
#define MEMERRMSG "not enough memory"
#define LUAI_HASHLIMIT 5
Functions
int luaS_eqlngstr (TString *a, TString *b)
unsigned int luaS_hash (const char *str, size_t l, unsigned int seed)
unsigned int luaS_hashlongstr (TString *ts)
void luaS_resize (lua_State *L, int newsize)
void luaS_clearcache (global_State *g)
void luaS_init (lua_State *L)
static TString * createstrobj (lua_State *L, size_t l, int tag, unsigned int h)
TString * luaS_createlngstrobj (lua_State *L, size_t l)
void luaS_remove (lua_State *L, TString *ts)
static TString * internshrstr (lua_State *L, const char *str, size_t l)
TString * luaS_newlstr (lua_State *L, const char *str, size_t l)
TString * luaS_new (lua_State *L, const char *str)
Udata * luaS_newudata (lua_State *L, size_t s)
Macro Definition Documentation
lstring_c
#define lstring_c
Definition at line 7 of file lua-5.3.6/src/lstring.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lua-5.3.6/src/lstring.c.
LUAI_HASHLIMIT
#define LUAI_HASHLIMIT 5
Definition at line 33 of file lua-5.3.6/src/lstring.c.
Referenced by luaS_hash().
MEMERRMSG
#define MEMERRMSG "not enough memory"
Definition at line 25 of file lua-5.3.6/src/lstring.c.
Referenced by luaS_init().
Function Documentation
createstrobj()
static TString * createstrobj (lua_State * L, size_t l, int tag, unsigned int h) static
Definition at line 133 of file lua-5.3.6/src/lstring.c.
{
  TString *ts;
  GCObject *o;
  size_t totalsize;  /* total size of TString object */
  totalsize = sizelstring(l);
  o = luaC_newobj(L, tag, totalsize);
  ts = gco2ts(o);
  ts->hash = h;
  ts->extra = 0;
  getstr(ts)[l] = '\0';  /* ending 0 */
  return ts;
}
References TString::extra, gco2ts, getstr, TString::hash, luaC_newobj(), and sizelstring.
Referenced by internshrstr(), and luaS_createlngstrobj().
internshrstr()
static TString * internshrstr (lua_State * L, const char * str, size_t l) static
Definition at line 167 of file lua-5.3.6/src/lstring.c.
{
  TString *ts;
  global_State *g = G(L);
  unsigned int h = luaS_hash(str, l, g->seed);
  TString **list = &g->strt.hash[lmod(h, g->strt.size)];
  lua_assert(str != NULL);  /* otherwise 'memcmp'/'memcpy' are undefined */
  for (ts = *list; ts != NULL; ts = ts->u.hnext) {
    if (l == ts->shrlen &&
        (memcmp(str, getstr(ts), l * sizeof(char)) == 0)) {
      /* found! */
      if (isdead(g, ts))  /* dead (but not collected yet)? */
        changewhite(ts);  /* resurrect it */
      return ts;
    }
  }
  if (g->strt.nuse >= g->strt.size && g->strt.size <= MAX_INT/2) {
    luaS_resize(L, g->strt.size * 2);
    list = &g->strt.hash[lmod(h, g->strt.size)];  /* recompute with new size */
  }
  ts = createstrobj(L, l, LUA_TSHRSTR, h);
  memcpy(getstr(ts), str, l * sizeof(char));
  ts->shrlen = cast_byte(l);
  ts->u.hnext = *list;
  *list = ts;
  g->strt.nuse++;
  return ts;
}
References cast_byte, changewhite, createstrobj(), G, getstr, stringtable::hash, TString::hnext, isdead, lmod, lua_assert, LUA_TSHRSTR, luaS_hash(), luaS_resize(), MAX_INT, NULL, stringtable::nuse, global_State::seed, TString::shrlen, stringtable::size, global_State::strt, and TString::u.
Referenced by luaS_newlstr().
luaS_clearcache()
void luaS_clearcache (global_State * g)
Definition at line 103 of file lua-5.3.6/src/lstring.c.
{
  int i, j;
  for (i = 0; i < STRCACHE_N; i++)
    for (j = 0; j < STRCACHE_M; j++) {
    if (iswhite(g->strcache[i][j]))  /* will entry be collected? */
      g->strcache[i][j] = g->memerrmsg;  /* replace it with something fixed */
    }
}
References iswhite, global_State::memerrmsg, global_State::strcache, STRCACHE_M, and STRCACHE_N.
Referenced by atomic(), and atomic().
luaS_createlngstrobj()
TString * luaS_createlngstrobj (lua_State * L, size_t l)
Definition at line 147 of file lua-5.3.6/src/lstring.c.
{
  TString *ts = createstrobj(L, l, LUA_TLNGSTR, G(L)->seed);
  ts->u.lnglen = l;
  return ts;
}
References createstrobj(), G, TString::lnglen, LUA_TLNGSTR, and TString::u.
Referenced by LoadString(), loadStringN(), luaS_newlstr(), and luaV_concat().
luaS_eqlngstr()
int luaS_eqlngstr (TString * a, TString * b)
Definition at line 40 of file lua-5.3.6/src/lstring.c.
{
  size_t len = a->u.lnglen;
  lua_assert(a->tt == LUA_TLNGSTR && b->tt == LUA_TLNGSTR);
  return (a == b) ||  /* same instance or... */
    ((len == b->u.lnglen) &&  /* equal length and ... */
     (memcmp(getstr(a), getstr(b), len) == 0));  /* equal contents */
}
References getstr, TString::lnglen, lua_assert, LUA_TLNGSTR, and TString::u.
luaS_hash()
unsigned int luaS_hash (const char * str, size_t l, unsigned int seed)
Definition at line 49 of file lua-5.3.6/src/lstring.c.
{
  unsigned int h = seed ^ cast(unsigned int, l);
  size_t step = (l >> LUAI_HASHLIMIT) + 1;
  for (; l >= step; l -= step)
    h ^= ((h<<5) + (h>>2) + cast_byte(str[l - 1]));
  return h;
}
References cast, cast_byte, and LUAI_HASHLIMIT.
Referenced by internshrstr(), and luaS_hashlongstr().
luaS_hashlongstr()
unsigned int luaS_hashlongstr (TString * ts)
Definition at line 58 of file lua-5.3.6/src/lstring.c.
{
  lua_assert(ts->tt == LUA_TLNGSTR);
  if (ts->extra == 0) {  /* no hash? */
    ts->hash = luaS_hash(getstr(ts), ts->u.lnglen, ts->hash);
    ts->extra = 1;  /* now it has its hash */
  }
  return ts->hash;
}
References TString::extra, getstr, TString::hash, TString::lnglen, lua_assert, LUA_TLNGSTR, luaS_hash(), and TString::u.
Referenced by mainposition(), and mainposition().
luaS_init()
void luaS_init (lua_State * L)
Definition at line 116 of file lua-5.3.6/src/lstring.c.
{
  global_State *g = G(L);
  int i, j;
  luaS_resize(L, MINSTRTABSIZE);  /* initial size of string table */
  /* pre-create memory-error message */
  g->memerrmsg = luaS_newliteral(L, MEMERRMSG);
  luaC_fix(L, obj2gco(g->memerrmsg));  /* it should never be collected */
  for (i = 0; i < STRCACHE_N; i++)  /* fill cache with valid strings */
    for (j = 0; j < STRCACHE_M; j++)
      g->strcache[i][j] = g->memerrmsg;
}
References G, luaC_fix(), luaS_newliteral, luaS_resize(), global_State::memerrmsg, MEMERRMSG, MINSTRTABSIZE, obj2gco, global_State::strcache, STRCACHE_M, and STRCACHE_N.
Referenced by f_luaopen(), and f_luaopen().
luaS_new()
TString * luaS_new (lua_State * L, const char * str)
Definition at line 219 of file lua-5.3.6/src/lstring.c.
{
  unsigned int i = point2uint(str) % STRCACHE_N;  /* hash */
  int j;
  TString **p = G(L)->strcache[i];
  for (j = 0; j < STRCACHE_M; j++) {
    if (strcmp(str, getstr(p[j])) == 0)  /* hit? */
      return p[j];  /* that is it */
  }
  /* normal route */
  for (j = STRCACHE_M - 1; j > 0; j--)
    p[j] = p[j - 1];  /* move out last element */
  /* new element is first in the list */
  p[0] = luaS_newlstr(L, str, strlen(str));
  return p[0];
}
References G, getstr, luaS_newlstr(), point2uint, STRCACHE_M, and STRCACHE_N.
luaS_newlstr()
TString * luaS_newlstr (lua_State * L, const char * str, size_t l)
Definition at line 199 of file lua-5.3.6/src/lstring.c.
{
  if (l <= LUAI_MAXSHORTLEN)  /* short string? */
    return internshrstr(L, str, l);
  else {
    TString *ts;
    if (l >= (MAX_SIZE - sizeof(TString))/sizeof(char))
      luaM_toobig(L);
    ts = luaS_createlngstrobj(L, l);
    memcpy(getstr(ts), str, l * sizeof(char));
    return ts;
  }
}
References getstr, internshrstr(), LUAI_MAXSHORTLEN, luaM_toobig(), luaS_createlngstrobj(), and MAX_SIZE.
Referenced by luaS_new().
luaS_newudata()
Udata * luaS_newudata (lua_State * L, size_t s)
Definition at line 236 of file lua-5.3.6/src/lstring.c.
{
  Udata *u;
  GCObject *o;
  if (s > MAX_SIZE - sizeof(Udata))
    luaM_toobig(L);
  o = luaC_newobj(L, LUA_TUSERDATA, sizeludata(s));
  u = gco2u(o);
  u->len = s;
  u->metatable = NULL;
  setuservalue(L, u, luaO_nilobject);
  return u;
}
References gco2u, Udata::len, LUA_TUSERDATA, luaC_newobj(), luaM_toobig(), luaO_nilobject, MAX_SIZE, Udata::metatable, NULL, s, setuservalue, and sizeludata.
luaS_remove()
void luaS_remove (lua_State * L, TString * ts)
Definition at line 154 of file lua-5.3.6/src/lstring.c.
{
  stringtable *tb = &G(L)->strt;
  TString **p = &tb->hash[lmod(ts->hash, tb->size)];
  while (*p != ts)  /* find previous element */
    p = &(*p)->u.hnext;
  *p = (*p)->u.hnext;  /* remove element from its list */
  tb->nuse--;
}
References G, TString::hash, stringtable::hash, TString::hnext, lmod, stringtable::nuse, stringtable::size, and TString::u.
Referenced by freeobj(), and freeobj().
luaS_resize()
void luaS_resize (lua_State * L, int newsize)
Definition at line 71 of file lua-5.3.6/src/lstring.c.
{
  int i;
  stringtable *tb = &G(L)->strt;
  if (newsize > tb->size) {  /* grow table if needed */
    luaM_reallocvector(L, tb->hash, tb->size, newsize, TString *);
    for (i = tb->size; i < newsize; i++)
      tb->hash[i] = NULL;
  }
  for (i = 0; i < tb->size; i++) {  /* rehash */
    TString *p = tb->hash[i];
    tb->hash[i] = NULL;
    while (p) {  /* for each node in the list */
      TString *hnext = p->u.hnext;  /* save next */
      unsigned int h = lmod(p->hash, newsize);  /* new position */
      p->u.hnext = tb->hash[h];  /* chain it */
      tb->hash[h] = p;
      p = hnext;
    }
  }
  if (newsize < tb->size) {  /* shrink table if needed */
    /* vanishing slice should be empty */
    lua_assert(tb->hash[newsize] == NULL && tb->hash[tb->size - 1] == NULL);
    luaM_reallocvector(L, tb->hash, tb->size, newsize, TString *);
  }
  tb->size = newsize;
}
References G, TString::hash, stringtable::hash, TString::hnext, lmod, lua_assert, luaM_reallocvector, NULL, stringtable::size, and TString::u.
Referenced by internshrstr(), and luaS_init().