Github User Fetcher: lstrlib.c File Reference
lstrlib.c File Reference
#include <ctype.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Data Structures
struct MatchState
Macros
#define lstrlib_c
#define LUA_LIB
#define LUA_MAXCAPTURES 32
#define uchar(c) ((unsigned char)(c))
#define MAXSIZE ((~(size_t)0) >> 1)
#define CAP_UNFINISHED (-1)
#define CAP_POSITION (-2)
#define MAXCCALLS 200
#define L_ESC '%'
#define SPECIALS "^$*+?.([%-"
#define LUA_INTFRMLEN "l"
#define LUA_INTFRM_T long
#define LUA_FLTFRMLEN ""
#define LUA_FLTFRM_T double
#define MAX_ITEM 512
#define FLAGS "-+ #0"
#define MAX_FORMAT (sizeof(FLAGS) + sizeof(LUA_INTFRMLEN) + 10)
Typedefs
typedef struct MatchState MatchState
Functions
static int str_len (lua_State *L)
static size_t posrelat (ptrdiff_t pos, size_t len)
static int str_sub (lua_State *L)
static int str_reverse (lua_State *L)
static int str_lower (lua_State *L)
static int str_upper (lua_State *L)
static int str_rep (lua_State *L)
static int str_byte (lua_State *L)
static int str_char (lua_State *L)
static int writer (lua_State *L, const void *b, size_t size, void *B)
static int str_dump (lua_State *L)
static const char * match (MatchState *ms, const char *s, const char *p)
static int check_capture (MatchState *ms, int l)
static int capture_to_close (MatchState *ms)
static const char * classend (MatchState *ms, const char *p)
static int match_class (int c, int cl)
static int matchbracketclass (int c, const char *p, const char *ec)
static int singlematch (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * matchbalance (MatchState *ms, const char *s, const char *p)
static const char * max_expand (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * min_expand (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * start_capture (MatchState *ms, const char *s, const char *p, int what)
static const char * end_capture (MatchState *ms, const char *s, const char *p)
static const char * match_capture (MatchState *ms, const char *s, int l)
static const char * lmemfind (const char *s1, size_t l1, const char *s2, size_t l2)
static void push_onecapture (MatchState *ms, int i, const char *s, const char *e)
static int push_captures (MatchState *ms, const char *s, const char *e)
static int nospecials (const char *p, size_t l)
static int str_find_aux (lua_State *L, int find)
static int str_find (lua_State *L)
static int str_match (lua_State *L)
static int gmatch_aux (lua_State *L)
static int gmatch (lua_State *L)
static void add_s (MatchState *ms, luaL_Buffer *b, const char *s, const char *e)
static void add_value (MatchState *ms, luaL_Buffer *b, const char *s, const char *e, int tr)
static int str_gsub (lua_State *L)
static void addquoted (lua_State *L, luaL_Buffer *b, int arg)
static const char * scanformat (lua_State *L, const char *strfrmt, char *form)
static void addlenmod (char *form, const char *lenmod)
static int str_format (lua_State *L)
static void createmetatable (lua_State *L)
LUAMOD_API int luaopen_string (lua_State *L)
Variables
static const luaL_Reg strlib []
Macro Definition Documentation
CAP_POSITION
#define CAP_POSITION (-2)
Definition at line 195 of file lua-5.2.4/src/lstrlib.c.
Referenced by match(), and push_onecapture().
CAP_UNFINISHED
#define CAP_UNFINISHED (-1)
Definition at line 194 of file lua-5.2.4/src/lstrlib.c.
Referenced by capture_to_close(), check_capture(), end_capture(), match(), and push_onecapture().
FLAGS
#define FLAGS "-+ #0"
Definition at line 825 of file lua-5.2.4/src/lstrlib.c.
Referenced by scanformat().
L_ESC
#define L_ESC '%'
Definition at line 222 of file lua-5.2.4/src/lstrlib.c.
Referenced by add_s(), classend(), match(), matchbracketclass(), singlematch(), and str_format().
lstrlib_c
#define lstrlib_c
Definition at line 14 of file lua-5.2.4/src/lstrlib.c.
LUA_FLTFRM_T
#define LUA_FLTFRM_T double
Definition at line 817 of file lua-5.2.4/src/lstrlib.c.
Referenced by str_format().
LUA_FLTFRMLEN
#define LUA_FLTFRMLEN ""
Definition at line 816 of file lua-5.2.4/src/lstrlib.c.
Referenced by str_format().
LUA_INTFRM_T
#define LUA_INTFRM_T long
Definition at line 803 of file lua-5.2.4/src/lstrlib.c.
Referenced by str_format().
LUA_INTFRMLEN
#define LUA_INTFRMLEN "l"
Definition at line 802 of file lua-5.2.4/src/lstrlib.c.
Referenced by str_format().
LUA_LIB
#define LUA_LIB
Definition at line 15 of file lua-5.2.4/src/lstrlib.c.
LUA_MAXCAPTURES
#define LUA_MAXCAPTURES 32
Definition at line 28 of file lua-5.2.4/src/lstrlib.c.
Referenced by start_capture().
MAX_FORMAT
#define MAX_FORMAT (sizeof(FLAGS) + sizeof(LUA_INTFRMLEN) + 10)
Definition at line 830 of file lua-5.2.4/src/lstrlib.c.
Referenced by str_format().
MAX_ITEM
#define MAX_ITEM 512
Definition at line 823 of file lua-5.2.4/src/lstrlib.c.
Referenced by str_format().
MAXCCALLS
#define MAXCCALLS 200
Definition at line 218 of file lua-5.2.4/src/lstrlib.c.
Referenced by gmatch_aux(), str_find_aux(), and str_gsub().
MAXSIZE
#define MAXSIZE ((~(size_t)0) >> 1)
Definition at line 106 of file lua-5.2.4/src/lstrlib.c.
Referenced by str_rep().
SPECIALS
#define SPECIALS "^$*+?.([%-"
Definition at line 223 of file lua-5.2.4/src/lstrlib.c.
Referenced by nospecials().
uchar
#define uchar (c) ((unsigned char)(c))
Definition at line 33 of file lua-5.2.4/src/lstrlib.c.
Referenced by add_s(), addquoted(), match(), matchbracketclass(), scanformat(), singlematch(), str_byte(), str_char(), str_lower(), and str_upper().
Typedef Documentation
MatchState
typedef struct MatchState MatchState
Function Documentation
add_s()
static void add_s (MatchState * ms, luaL_Buffer * b, const char * s, const char * e) static
Definition at line 678 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l, i;
  const char *news = lua_tolstring(ms->L, 3, &l);
  for (i = 0; i < l; i++) {
    if (news[i] != L_ESC)
      luaL_addchar(b, news[i]);
    else {
      i++;  /* skip ESC */
      if (!isdigit(uchar(news[i]))) {
        if (news[i] != L_ESC)
          luaL_error(ms->L, "invalid use of " LUA_QL("%c")
                           " in replacement string", L_ESC);
        luaL_addchar(b, news[i]);
      }
      else if (news[i] == '0')
          luaL_addlstring(b, s, e - s);
      else {
        push_onecapture(ms, news[i] - '1', s, e);
        luaL_addvalue(b);  /* add capture to accumulated result */
      }
    }
  }
}
References MatchState::L, L_ESC, LUA_QL, lua_tolstring(), luaL_addchar, luaL_addlstring(), luaL_addvalue(), luaL_error(), push_onecapture(), s, and uchar.
Referenced by add_value().
add_value()
static void add_value (MatchState * ms, luaL_Buffer * b, const char * s, const char * e, int tr) static
Definition at line 704 of file lua-5.2.4/src/lstrlib.c.
{
  lua_State *L = ms->L;
  switch (tr) {
    case LUA_TFUNCTION: {
      int n;
      lua_pushvalue(L, 3);
      n = push_captures(ms, s, e);
      lua_call(L, n, 1);
      break;
    }
    case LUA_TTABLE: {
      push_onecapture(ms, 0, s, e);
      lua_gettable(L, 3);
      break;
    }
    default: {  /* LUA_TNUMBER or LUA_TSTRING */
      add_s(ms, b, s, e);
      return;
    }
  }
  if (!lua_toboolean(L, -1)) {  /* nil or false? */
    lua_pop(L, 1);
    lua_pushlstring(L, s, e - s);  /* keep original text */
  }
  else if (!lua_isstring(L, -1))
    luaL_error(L, "invalid replacement value (a %s)", luaL_typename(L, -1));
  luaL_addvalue(b);  /* add result to accumulator */
}
References add_s(), MatchState::L, lua_call, lua_gettable(), lua_isstring(), lua_pop, lua_pushlstring(), lua_pushvalue(), LUA_TFUNCTION, lua_toboolean(), LUA_TTABLE, luaL_addvalue(), luaL_error(), luaL_typename, push_captures(), push_onecapture(), and s.
Referenced by str_gsub().
addlenmod()
static void addlenmod (char * form, const char * lenmod) static
Definition at line 882 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l = strlen(form);
  size_t lm = strlen(lenmod);
  char spec = form[l - 1];
  strcpy(form + l - 1, lenmod);
  form[l + lm - 1] = spec;
  form[l + lm] = '\0';
}
Referenced by str_format().
addquoted()
static void addquoted (lua_State * L, luaL_Buffer * b, int arg) static
Definition at line 833 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l;
  const char *s = luaL_checklstring(L, arg, &l);
  luaL_addchar(b, '"');
  while (l--) {
    if (*s == '"' || *s == '\\' || *s == '\n') {
      luaL_addchar(b, '\\');
      luaL_addchar(b, *s);
    }
    else if (*s == '\0' || iscntrl(uchar(*s))) {
      char buff[10];
      if (!isdigit(uchar(*(s+1))))
        sprintf(buff, "\\%d", (int)uchar(*s));
      else
        sprintf(buff, "\\%03d", (int)uchar(*s));
      luaL_addstring(b, buff);
    }
    else
      luaL_addchar(b, *s);
    s++;
  }
  luaL_addchar(b, '"');
}
References arg, luaL_addchar, luaL_addstring(), luaL_checklstring(), s, and uchar.
Referenced by str_format().
capture_to_close()
static int capture_to_close (MatchState * ms) static
Definition at line 234 of file lua-5.2.4/src/lstrlib.c.
{
  int level = ms->level;
  for (level--; level>=0; level--)
    if (ms->capture[level].len == CAP_UNFINISHED) return level;
  return luaL_error(ms->L, "invalid pattern capture");
}
References CAP_UNFINISHED, MatchState::capture, MatchState::L, MatchState::len, MatchState::level, and luaL_error().
Referenced by end_capture().
check_capture()
static int check_capture (MatchState * ms, int l) static
Definition at line 226 of file lua-5.2.4/src/lstrlib.c.
{
  l -= '1';
  if (l < 0 || l >= ms->level || ms->capture[l].len == CAP_UNFINISHED)
    return luaL_error(ms->L, "invalid capture index %%%d", l + 1);
  return l;
}
References CAP_UNFINISHED, MatchState::capture, MatchState::L, MatchState::len, MatchState::level, and luaL_error().
Referenced by match_capture().
classend()
static const char * classend (MatchState * ms, const char * p) static
Definition at line 242 of file lua-5.2.4/src/lstrlib.c.
{
  switch (*p++) {
    case L_ESC: {
      if (p == ms->p_end)
        luaL_error(ms->L, "malformed pattern (ends with " LUA_QL("%%") ")");
      return p+1;
    }
    case '[': {
      if (*p == '^') p++;
      do {  /* look for a `]' */
        if (p == ms->p_end)
          luaL_error(ms->L, "malformed pattern (missing " LUA_QL("]") ")");
        if (*(p++) == L_ESC && p < ms->p_end)
          p++;  /* skip escapes (e.g. `%]') */
      } while (*p != ']');
      return p+1;
    }
    default: {
      return p;
    }
  }
}
References MatchState::L, L_ESC, LUA_QL, luaL_error(), and MatchState::p_end.
Referenced by match().
createmetatable()
static void createmetatable (lua_State * L) static
Definition at line 999 of file lua-5.2.4/src/lstrlib.c.
{
  lua_createtable(L, 0, 1);  /* table to be metatable for strings */
  lua_pushliteral(L, "");  /* dummy string */
  lua_pushvalue(L, -2);  /* copy table */
  lua_setmetatable(L, -2);  /* set table as metatable for strings */
  lua_pop(L, 1);  /* pop dummy string */
  lua_pushvalue(L, -2);  /* get string library */
  lua_setfield(L, -2, "__index");  /* metatable.__index = string */
  lua_pop(L, 1);  /* pop metatable */
}
References lua_createtable(), lua_pop, lua_pushliteral, lua_pushvalue(), lua_setfield(), and lua_setmetatable().
Referenced by luaopen_string().
end_capture()
static const char * end_capture (MatchState * ms, const char * s, const char * p) static
Definition at line 388 of file lua-5.2.4/src/lstrlib.c.
{
  int l = capture_to_close(ms);
  const char *res;
  ms->capture[l].len = s - ms->capture[l].init;  /* close capture */
  if ((res = match(ms, s, p)) == NULL)  /* match failed? */
    ms->capture[l].len = CAP_UNFINISHED;  /* undo capture */
  return res;
}
References CAP_UNFINISHED, MatchState::capture, capture_to_close(), MatchState::init, MatchState::len, match(), NULL, and s.
Referenced by match().
gmatch()
static int gmatch (lua_State * L) static
Definition at line 668 of file lua-5.2.4/src/lstrlib.c.
{
  luaL_checkstring(L, 1);
  luaL_checkstring(L, 2);
  lua_settop(L, 2);
  lua_pushinteger(L, 0);
  lua_pushcclosure(L, gmatch_aux, 3);
  return 1;
}
References gmatch_aux(), lua_pushcclosure(), lua_pushinteger(), lua_settop(), and luaL_checkstring.
gmatch_aux()
static int gmatch_aux (lua_State * L) static
Definition at line 639 of file lua-5.2.4/src/lstrlib.c.
{
  MatchState ms;
  size_t ls, lp;
  const char *s = lua_tolstring(L, lua_upvalueindex(1), &ls);
  const char *p = lua_tolstring(L, lua_upvalueindex(2), &lp);
  const char *src;
  ms.L = L;
  ms.matchdepth = MAXCCALLS;
  ms.src_init = s;
  ms.src_end = s+ls;
  ms.p_end = p + lp;
  for (src = s + (size_t)lua_tointeger(L, lua_upvalueindex(3));
       src <= ms.src_end;
       src++) {
    const char *e;
    ms.level = 0;
    lua_assert(ms.matchdepth == MAXCCALLS);
    if ((e = match(&ms, src, p)) != NULL) {
      lua_Integer newstart = e-s;
      if (e == src) newstart++;  /* empty match? go at least one position */
      lua_pushinteger(L, newstart);
      lua_replace(L, lua_upvalueindex(3));
      return push_captures(&ms, src, e);
    }
  }
  return 0;  /* not found */
}
References MatchState::L, MatchState::level, lua_assert, lua_pushinteger(), lua_replace, lua_tointeger, lua_tolstring(), lua_upvalueindex, match(), MatchState::matchdepth, MAXCCALLS, NULL, MatchState::p_end, push_captures(), s, MatchState::src_end, and MatchState::src_init.
Referenced by gmatch().
lmemfind()
static const char * lmemfind (const char * s1, size_t l1, const char * s2, size_t l2) static
Definition at line 514 of file lua-5.2.4/src/lstrlib.c.
{
  if (l2 == 0) return s1;  /* empty strings are everywhere */
  else if (l2 > l1) return NULL;  /* avoids a negative `l1' */
  else {
    const char *init;  /* to search for a `*s2' inside `s1' */
    l2--;  /* 1st char will be checked by `memchr' */
    l1 = l1-l2;  /* `s2' cannot be found after that */
    while (l1 > 0 && (init = (const char *)memchr(s1, *s2, l1)) != NULL) {
      init++;   /* 1st char is already checked */
      if (memcmp(init, s2+1, l2) == 0)
        return init-1;
      else {  /* correct `l1' and `s1' to try again */
        l1 -= init-s1;
        s1 = init;
      }
    }
    return NULL;  /* not found */
  }
}
References NULL.
Referenced by str_find_aux().
luaopen_string()
LUAMOD_API int luaopen_string (lua_State * L)
Definition at line 1014 of file lua-5.2.4/src/lstrlib.c.
{
  luaL_newlib(L, strlib);
  createmetatable(L);
  return 1;
}
References createmetatable(), luaL_newlib, and strlib.
match()
static const char * match (MatchState * ms, const char * s, const char * p) static
Definition at line 410 of file lua-5.2.4/src/lstrlib.c.
{
  if (ms->matchdepth-- == 0)
    luaL_error(ms->L, "pattern too complex");
  init: /* using goto's to optimize tail recursion */
  if (p != ms->p_end) {  /* end of pattern? */
    switch (*p) {
      case '(': {  /* start capture */
        if (*(p + 1) == ')')  /* position capture? */
          s = start_capture(ms, s, p + 2, CAP_POSITION);
        else
          s = start_capture(ms, s, p + 1, CAP_UNFINISHED);
        break;
      }
      case ')': {  /* end capture */
        s = end_capture(ms, s, p + 1);
        break;
      }
      case '$': {
        if ((p + 1) != ms->p_end)  /* is the `$' the last char in pattern? */
          goto dflt;  /* no; go to default */
        s = (s == ms->src_end) ? s : NULL;  /* check end of string */
        break;
      }
      case L_ESC: {  /* escaped sequences not in the format class[*+?-]? */
        switch (*(p + 1)) {
          case 'b': {  /* balanced string? */
            s = matchbalance(ms, s, p + 2);
            if (s != NULL) {
              p += 4; goto init;  /* return match(ms, s, p + 4); */
            }  /* else fail (s == NULL) */
            break;
          }
          case 'f': {  /* frontier? */
            const char *ep; char previous;
            p += 2;
            if (*p != '[')
              luaL_error(ms->L, "missing " LUA_QL("[") " after "
                                 LUA_QL("%%f") " in pattern");
            ep = classend(ms, p);  /* points to what is next */
            previous = (s == ms->src_init) ? '\0' : *(s - 1);
            if (!matchbracketclass(uchar(previous), p, ep - 1) &&
               matchbracketclass(uchar(*s), p, ep - 1)) {
              p = ep; goto init;  /* return match(ms, s, ep); */
            }
            s = NULL;  /* match failed */
            break;
          }
          case '0': case '1': case '2': case '3':
          case '4': case '5': case '6': case '7':
          case '8': case '9': {  /* capture results (%0-%9)? */
            s = match_capture(ms, s, uchar(*(p + 1)));
            if (s != NULL) {
              p += 2; goto init;  /* return match(ms, s, p + 2) */
            }
            break;
          }
          default: goto dflt;
        }
        break;
      }
      default: dflt: {  /* pattern class plus optional suffix */
        const char *ep = classend(ms, p);  /* points to optional suffix */
        /* does not match at least once? */
        if (!singlematch(ms, s, p, ep)) {
          if (*ep == '*' || *ep == '?' || *ep == '-') {  /* accept empty? */
            p = ep + 1; goto init;  /* return match(ms, s, ep + 1); */
          }
          else  /* '+' or no suffix */
            s = NULL;  /* fail */
        }
        else {  /* matched once */
          switch (*ep) {  /* handle optional suffix */
            case '?': {  /* optional */
              const char *res;
              if ((res = match(ms, s + 1, ep + 1)) != NULL)
                s = res;
              else {
                p = ep + 1; goto init;  /* else return match(ms, s, ep + 1); */
              }
              break;
            }
            case '+':  /* 1 or more repetitions */
              s++;  /* 1 match already done */
              /* go through */
            case '*':  /* 0 or more repetitions */
              s = max_expand(ms, s, p, ep);
              break;
            case '-':  /* 0 or more repetitions (minimum) */
              s = min_expand(ms, s, p, ep);
              break;
            default:  /* no suffix */
              s++; p = ep; goto init;  /* return match(ms, s + 1, ep); */
          }
        }
        break;
      }
    }
  }
  ms->matchdepth++;
  return s;
}
References CAP_POSITION, CAP_UNFINISHED, classend(), end_capture(), MatchState::L, L_ESC, LUA_QL, luaL_error(), match(), match_capture(), matchbalance(), matchbracketclass(), MatchState::matchdepth, max_expand(), min_expand(), NULL, MatchState::p_end, s, singlematch(), MatchState::src_end, MatchState::src_init, start_capture(), and uchar.
Referenced by end_capture(), gmatch_aux(), match(), max_expand(), min_expand(), start_capture(), str_find_aux(), and str_gsub().
match_capture()
static const char * match_capture (MatchState * ms, const char * s, int l) static
Definition at line 399 of file lua-5.2.4/src/lstrlib.c.
{
  size_t len;
  l = check_capture(ms, l);
  len = ms->capture[l].len;
  if ((size_t)(ms->src_end-s) >= len &&
      memcmp(ms->capture[l].init, s, len) == 0)
    return s+len;
  else return NULL;
}
References MatchState::capture, check_capture(), MatchState::init, MatchState::len, NULL, s, and MatchState::src_end.
Referenced by match().
match_class()
static int match_class (int c, int cl) static
Definition at line 266 of file lua-5.2.4/src/lstrlib.c.
{
  int res;
  switch (tolower(cl)) {
    case 'a' : res = isalpha(c); break;
    case 'c' : res = iscntrl(c); break;
    case 'd' : res = isdigit(c); break;
    case 'g' : res = isgraph(c); break;
    case 'l' : res = islower(c); break;
    case 'p' : res = ispunct(c); break;
    case 's' : res = isspace(c); break;
    case 'u' : res = isupper(c); break;
    case 'w' : res = isalnum(c); break;
    case 'x' : res = isxdigit(c); break;
    case 'z' : res = (c == 0); break;  /* deprecated option */
    default: return (cl == c);
  }
  return (islower(cl) ? res : !res);
}
Referenced by matchbracketclass(), and singlematch().
matchbalance()
static const char * matchbalance (MatchState * ms, const char * s, const char * p) static
Definition at line 325 of file lua-5.2.4/src/lstrlib.c.
{
  if (p >= ms->p_end - 1)
    luaL_error(ms->L, "malformed pattern "
                      "(missing arguments to " LUA_QL("%%b") ")");
  if (*s != *p) return NULL;
  else {
    int b = *p;
    int e = *(p+1);
    int cont = 1;
    while (++s < ms->src_end) {
      if (*s == e) {
        if (--cont == 0) return s+1;
      }
      else if (*s == b) cont++;
    }
  }
  return NULL;  /* string ends out of balance */
}
References MatchState::L, LUA_QL, luaL_error(), NULL, MatchState::p_end, and s.
Referenced by match().
matchbracketclass()
static int matchbracketclass (int c, const char * p, const char * ec) static
Definition at line 286 of file lua-5.2.4/src/lstrlib.c.
{
  int sig = 1;
  if (*(p+1) == '^') {
    sig = 0;
    p++;  /* skip the `^' */
  }
  while (++p < ec) {
    if (*p == L_ESC) {
      p++;
      if (match_class(c, uchar(*p)))
        return sig;
    }
    else if ((*(p+1) == '-') && (p+2 < ec)) {
      p+=2;
      if (uchar(*(p-2)) <= c && c <= uchar(*p))
        return sig;
    }
    else if (uchar(*p) == c) return sig;
  }
  return !sig;
}
References L_ESC, match_class(), and uchar.
Referenced by match(), and singlematch().
max_expand()
static const char * max_expand (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 346 of file lua-5.2.4/src/lstrlib.c.
{
  ptrdiff_t i = 0;  /* counts maximum expand for item */
  while (singlematch(ms, s + i, p, ep))
    i++;
  /* keeps trying to match with the maximum repetitions */
  while (i>=0) {
    const char *res = match(ms, (s+i), ep+1);
    if (res) return res;
    i--;  /* else didn't match; reduce 1 repetition to try again */
  }
  return NULL;
}
References match(), NULL, s, and singlematch().
Referenced by match().
min_expand()
static const char * min_expand (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 361 of file lua-5.2.4/src/lstrlib.c.
{
  for (;;) {
    const char *res = match(ms, s, ep+1);
    if (res != NULL)
      return res;
    else if (singlematch(ms, s, p, ep))
      s++;  /* try with one more repetition */
    else return NULL;
  }
}
References match(), NULL, s, and singlematch().
Referenced by match().
nospecials()
static int nospecials (const char * p, size_t l) static
Definition at line 566 of file lua-5.2.4/src/lstrlib.c.
{
  size_t upto = 0;
  do {
    if (strpbrk(p + upto, SPECIALS))
      return 0;  /* pattern has a special character */
    upto += strlen(p + upto) + 1;  /* may have more after \0 */
  } while (upto <= l);
  return 1;  /* no special chars found */
}
References SPECIALS.
Referenced by str_find_aux().
posrelat()
static size_t posrelat (ptrdiff_t pos, size_t len) static
Definition at line 46 of file lua-5.2.4/src/lstrlib.c.
{
  if (pos >= 0) return (size_t)pos;
  else if (0u - (size_t)pos > len) return 0;
  else return len - ((size_t)-pos) + 1;
}
Referenced by str_byte(), str_find_aux(), and str_sub().
push_captures()
static int push_captures (MatchState * ms, const char * s, const char * e) static
Definition at line 555 of file lua-5.2.4/src/lstrlib.c.
{
  int i;
  int nlevels = (ms->level == 0 && s) ? 1 : ms->level;
  luaL_checkstack(ms->L, nlevels, "too many captures");
  for (i = 0; i < nlevels; i++)
    push_onecapture(ms, i, s, e);
  return nlevels;  /* number of strings pushed */
}
References MatchState::L, MatchState::level, luaL_checkstack(), push_onecapture(), and s.
Referenced by add_value(), gmatch_aux(), and str_find_aux().
push_onecapture()
static void push_onecapture (MatchState * ms, int i, const char * s, const char * e) static
Definition at line 536 of file lua-5.2.4/src/lstrlib.c.
{
  if (i >= ms->level) {
    if (i == 0)  /* ms->level == 0, too */
      lua_pushlstring(ms->L, s, e - s);  /* add whole match */
    else
      luaL_error(ms->L, "invalid capture index");
  }
  else {
    ptrdiff_t l = ms->capture[i].len;
    if (l == CAP_UNFINISHED) luaL_error(ms->L, "unfinished capture");
    if (l == CAP_POSITION)
      lua_pushinteger(ms->L, ms->capture[i].init - ms->src_init + 1);
    else
      lua_pushlstring(ms->L, ms->capture[i].init, l);
  }
}
References CAP_POSITION, CAP_UNFINISHED, MatchState::capture, MatchState::init, MatchState::L, MatchState::len, MatchState::level, lua_pushinteger(), lua_pushlstring(), luaL_error(), s, and MatchState::src_init.
Referenced by add_s(), add_value(), and push_captures().
scanformat()
static const char * scanformat (lua_State * L, const char * strfrmt, char * form) static
Definition at line 857 of file lua-5.2.4/src/lstrlib.c.
{
  const char *p = strfrmt;
  while (*p != '\0' && strchr(FLAGS, *p) != NULL) p++;  /* skip flags */
  if ((size_t)(p - strfrmt) >= sizeof(FLAGS)/sizeof(char))
    luaL_error(L, "invalid format (repeated flags)");
  if (isdigit(uchar(*p))) p++;  /* skip width */
  if (isdigit(uchar(*p))) p++;  /* (2 digits at most) */
  if (*p == '.') {
    p++;
    if (isdigit(uchar(*p))) p++;  /* skip precision */
    if (isdigit(uchar(*p))) p++;  /* (2 digits at most) */
  }
  if (isdigit(uchar(*p)))
    luaL_error(L, "invalid format (width or precision too long)");
  *(form++) = '%';
  memcpy(form, strfrmt, (p - strfrmt + 1) * sizeof(char));
  form += p - strfrmt + 1;
  *form = '\0';
  return p;
}
References FLAGS, luaL_error(), NULL, and uchar.
Referenced by str_format().
singlematch()
static int singlematch (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 309 of file lua-5.2.4/src/lstrlib.c.
{
  if (s >= ms->src_end)
    return 0;
  else {
    int c = uchar(*s);
    switch (*p) {
      case '.': return 1;  /* matches any char */
      case L_ESC: return match_class(c, uchar(*(p+1)));
      case '[': return matchbracketclass(c, p, ep-1);
      default:  return (uchar(*p) == c);
    }
  }
}
References L_ESC, match_class(), matchbracketclass(), s, MatchState::src_end, and uchar.
Referenced by match(), max_expand(), and min_expand().
start_capture()
static const char * start_capture (MatchState * ms, const char * s, const char * p, int what) static
Definition at line 374 of file lua-5.2.4/src/lstrlib.c.
{
  const char *res;
  int level = ms->level;
  if (level >= LUA_MAXCAPTURES) luaL_error(ms->L, "too many captures");
  ms->capture[level].init = s;
  ms->capture[level].len = what;
  ms->level = level+1;
  if ((res=match(ms, s, p)) == NULL)  /* match failed? */
    ms->level--;  /* undo capture */
  return res;
}
References MatchState::capture, MatchState::init, MatchState::L, MatchState::len, MatchState::level, LUA_MAXCAPTURES, luaL_error(), match(), NULL, and s.
Referenced by match().
str_byte()
static int str_byte (lua_State * L) static
Definition at line 133 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l;
  const char *s = luaL_checklstring(L, 1, &l);
  size_t posi = posrelat(luaL_optinteger(L, 2, 1), l);
  size_t pose = posrelat(luaL_optinteger(L, 3, posi), l);
  int n, i;
  if (posi < 1) posi = 1;
  if (pose > l) pose = l;
  if (posi > pose) return 0;  /* empty interval; return no values */
  n = (int)(pose -  posi + 1);
  if (posi + n <= pose)  /* (size_t -> int) overflow? */
    return luaL_error(L, "string slice too long");
  luaL_checkstack(L, n, "string slice too long");
  for (i=0; i<n; i++)
    lua_pushinteger(L, uchar(s[posi+i-1]));
  return n;
}
References lua_pushinteger(), luaL_checklstring(), luaL_checkstack(), luaL_error(), luaL_optinteger(), posrelat(), s, and uchar.
str_char()
static int str_char (lua_State * L) static
Definition at line 152 of file lua-5.2.4/src/lstrlib.c.
{
  int n = lua_gettop(L);  /* number of arguments */
  int i;
  luaL_Buffer b;
  char *p = luaL_buffinitsize(L, &b, n);
  for (i=1; i<=n; i++) {
    int c = luaL_checkint(L, i);
    luaL_argcheck(L, uchar(c) == c, i, "value out of range");
    p[i - 1] = uchar(c);
  }
  luaL_pushresultsize(&b, n);
  return 1;
}
References lua_gettop(), luaL_argcheck, luaL_buffinitsize(), luaL_checkint, luaL_pushresultsize(), and uchar.
str_dump()
static int str_dump (lua_State * L) static
Definition at line 174 of file lua-5.2.4/src/lstrlib.c.
{
  luaL_Buffer b;
  luaL_checktype(L, 1, LUA_TFUNCTION);
  lua_settop(L, 1);
  luaL_buffinit(L,&b);
  if (lua_dump(L, writer, &b) != 0)
    return luaL_error(L, "unable to dump given function");
  luaL_pushresult(&b);
  return 1;
}
References lua_dump(), lua_settop(), LUA_TFUNCTION, luaL_buffinit(), luaL_checktype(), luaL_error(), luaL_pushresult(), and writer().
str_find()
static int str_find (lua_State * L) static
Definition at line 629 of file lua-5.2.4/src/lstrlib.c.
{
  return str_find_aux(L, 1);
}
References str_find_aux().
str_find_aux()
static int str_find_aux (lua_State * L, int find) static
Definition at line 577 of file lua-5.2.4/src/lstrlib.c.
{
  size_t ls, lp;
  const char *s = luaL_checklstring(L, 1, &ls);
  const char *p = luaL_checklstring(L, 2, &lp);
  size_t init = posrelat(luaL_optinteger(L, 3, 1), ls);
  if (init < 1) init = 1;
  else if (init > ls + 1) {  /* start after string's end? */
    lua_pushnil(L);  /* cannot find anything */
    return 1;
  }
  /* explicit request or no special characters? */
  if (find && (lua_toboolean(L, 4) || nospecials(p, lp))) {
    /* do a plain search */
    const char *s2 = lmemfind(s + init - 1, ls - init + 1, p, lp);
    if (s2) {
      lua_pushinteger(L, s2 - s + 1);
      lua_pushinteger(L, s2 - s + lp);
      return 2;
    }
  }
  else {
    MatchState ms;
    const char *s1 = s + init - 1;
    int anchor = (*p == '^');
    if (anchor) {
      p++; lp--;  /* skip anchor character */
    }
    ms.L = L;
    ms.matchdepth = MAXCCALLS;
    ms.src_init = s;
    ms.src_end = s + ls;
    ms.p_end = p + lp;
    do {
      const char *res;
      ms.level = 0;
      lua_assert(ms.matchdepth == MAXCCALLS);
      if ((res=match(&ms, s1, p)) != NULL) {
        if (find) {
          lua_pushinteger(L, s1 - s + 1);  /* start */
          lua_pushinteger(L, res - s);   /* end */
          return push_captures(&ms, NULL, 0) + 2;
        }
        else
          return push_captures(&ms, s1, res);
      }
    } while (s1++ < ms.src_end && !anchor);
  }
  lua_pushnil(L);  /* not found */
  return 1;
}
References find(), MatchState::L, MatchState::level, lmemfind(), lua_assert, lua_pushinteger(), lua_pushnil(), lua_toboolean(), luaL_checklstring(), luaL_optinteger(), match(), MatchState::matchdepth, MAXCCALLS, nospecials(), NULL, MatchState::p_end, posrelat(), push_captures(), s, MatchState::src_end, and MatchState::src_init.
Referenced by str_find(), and str_match().
str_format()
static int str_format (lua_State * L) static
Definition at line 892 of file lua-5.2.4/src/lstrlib.c.
{
  int top = lua_gettop(L);
  int arg = 1;
  size_t sfl;
  const char *strfrmt = luaL_checklstring(L, arg, &sfl);
  const char *strfrmt_end = strfrmt+sfl;
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  while (strfrmt < strfrmt_end) {
    if (*strfrmt != L_ESC)
      luaL_addchar(&b, *strfrmt++);
    else if (*++strfrmt == L_ESC)
      luaL_addchar(&b, *strfrmt++);  /* %% */
    else { /* format item */
      char form[MAX_FORMAT];  /* to store the format (`%...') */
      char *buff = luaL_prepbuffsize(&b, MAX_ITEM);  /* to put formatted item */
      int nb = 0;  /* number of bytes in added item */
      if (++arg > top)
        luaL_argerror(L, arg, "no value");
      strfrmt = scanformat(L, strfrmt, form);
      switch (*strfrmt++) {
        case 'c': {
          nb = sprintf(buff, form, luaL_checkint(L, arg));
          break;
        }
        case 'd': case 'i': {
          lua_Number n = luaL_checknumber(L, arg);
          LUA_INTFRM_T ni = (LUA_INTFRM_T)n;
          lua_Number diff = n - (lua_Number)ni;
          luaL_argcheck(L, -1 < diff && diff < 1, arg,
                        "not a number in proper range");
          addlenmod(form, LUA_INTFRMLEN);
          nb = sprintf(buff, form, ni);
          break;
        }
        case 'o': case 'u': case 'x': case 'X': {
          lua_Number n = luaL_checknumber(L, arg);
          unsigned LUA_INTFRM_T ni = (unsigned LUA_INTFRM_T)n;
          lua_Number diff = n - (lua_Number)ni;
          luaL_argcheck(L, -1 < diff && diff < 1, arg,
                        "not a non-negative number in proper range");
          addlenmod(form, LUA_INTFRMLEN);
          nb = sprintf(buff, form, ni);
          break;
        }
        case 'e': case 'E': case 'f':
#if defined(LUA_USE_AFORMAT)
        case 'a': case 'A':
#endif
        case 'g': case 'G': {
          addlenmod(form, LUA_FLTFRMLEN);
          nb = sprintf(buff, form, (LUA_FLTFRM_T)luaL_checknumber(L, arg));
          break;
        }
        case 'q': {
          addquoted(L, &b, arg);
          break;
        }
        case 's': {
          size_t l;
          const char *s = luaL_tolstring(L, arg, &l);
          if (!strchr(form, '.') && l >= 100) {
            /* no precision and string is too long to be formatted;
               keep original string */
            luaL_addvalue(&b);
            break;
          }
          else {
            nb = sprintf(buff, form, s);
            lua_pop(L, 1);  /* remove result from 'luaL_tolstring' */
            break;
          }
        }
        default: {  /* also treat cases `pnLlh' */
          return luaL_error(L, "invalid option " LUA_QL("%%%c") " to "
                               LUA_QL("format"), *(strfrmt - 1));
        }
      }
      luaL_addsize(&b, nb);
    }
  }
  luaL_pushresult(&b);
  return 1;
}
References addlenmod(), addquoted(), arg, L_ESC, LUA_FLTFRM_T, LUA_FLTFRMLEN, lua_gettop(), LUA_INTFRM_T, LUA_INTFRMLEN, lua_pop, LUA_QL, luaL_addchar, luaL_addsize, luaL_addvalue(), luaL_argcheck, luaL_argerror(), luaL_buffinit(), luaL_checkint, luaL_checklstring(), luaL_checknumber(), luaL_error(), luaL_prepbuffsize(), luaL_pushresult(), luaL_tolstring(), MAX_FORMAT, MAX_ITEM, s, and scanformat().
str_gsub()
static int str_gsub (lua_State * L) static
Definition at line 735 of file lua-5.2.4/src/lstrlib.c.
{
  size_t srcl, lp;
  const char *src = luaL_checklstring(L, 1, &srcl);
  const char *p = luaL_checklstring(L, 2, &lp);
  int tr = lua_type(L, 3);
  size_t max_s = luaL_optinteger(L, 4, srcl+1);
  int anchor = (*p == '^');
  size_t n = 0;
  MatchState ms;
  luaL_Buffer b;
  luaL_argcheck(L, tr == LUA_TNUMBER || tr == LUA_TSTRING ||
                   tr == LUA_TFUNCTION || tr == LUA_TTABLE, 3,
                      "string/function/table expected");
  luaL_buffinit(L, &b);
  if (anchor) {
    p++; lp--;  /* skip anchor character */
  }
  ms.L = L;
  ms.matchdepth = MAXCCALLS;
  ms.src_init = src;
  ms.src_end = src+srcl;
  ms.p_end = p + lp;
  while (n < max_s) {
    const char *e;
    ms.level = 0;
    lua_assert(ms.matchdepth == MAXCCALLS);
    e = match(&ms, src, p);
    if (e) {
      n++;
      add_value(&ms, &b, src, e, tr);
    }
    if (e && e>src) /* non empty match? */
      src = e;  /* skip it */
    else if (src < ms.src_end)
      luaL_addchar(&b, *src++);
    else break;
    if (anchor) break;
  }
  luaL_addlstring(&b, src, ms.src_end-src);
  luaL_pushresult(&b);
  lua_pushinteger(L, n);  /* number of substitutions */
  return 2;
}
References add_value(), MatchState::L, MatchState::level, lua_assert, lua_pushinteger(), LUA_TFUNCTION, LUA_TNUMBER, LUA_TSTRING, LUA_TTABLE, lua_type(), luaL_addchar, luaL_addlstring(), luaL_argcheck, luaL_buffinit(), luaL_checklstring(), luaL_optinteger(), luaL_pushresult(), match(), MatchState::matchdepth, MAXCCALLS, MatchState::p_end, MatchState::src_end, and MatchState::src_init.
str_len()
static int str_len (lua_State * L) static
Definition at line 37 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l;
  luaL_checklstring(L, 1, &l);
  lua_pushinteger(L, (lua_Integer)l);
  return 1;
}
References lua_pushinteger(), and luaL_checklstring().
str_lower()
static int str_lower (lua_State * L) static
Definition at line 79 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l;
  size_t i;
  luaL_Buffer b;
  const char *s = luaL_checklstring(L, 1, &l);
  char *p = luaL_buffinitsize(L, &b, l);
  for (i=0; i<l; i++)
    p[i] = tolower(uchar(s[i]));
  luaL_pushresultsize(&b, l);
  return 1;
}
References luaL_buffinitsize(), luaL_checklstring(), luaL_pushresultsize(), s, and uchar.
str_match()
static int str_match (lua_State * L) static
Definition at line 634 of file lua-5.2.4/src/lstrlib.c.
{
  return str_find_aux(L, 0);
}
References str_find_aux().
str_rep()
static int str_rep (lua_State * L) static
Definition at line 108 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l, lsep;
  const char *s = luaL_checklstring(L, 1, &l);
  int n = luaL_checkint(L, 2);
  const char *sep = luaL_optlstring(L, 3, "", &lsep);
  if (n <= 0) lua_pushliteral(L, "");
  else if (l + lsep < l || l + lsep >= MAXSIZE / n)  /* may overflow? */
    return luaL_error(L, "resulting string too large");
  else {
    size_t totallen = n * l + (n - 1) * lsep;
    luaL_Buffer b;
    char *p = luaL_buffinitsize(L, &b, totallen);
    while (n-- > 1) {  /* first n-1 copies (followed by separator) */
      memcpy(p, s, l * sizeof(char)); p += l;
      if (lsep > 0) {  /* avoid empty 'memcpy' (may be expensive) */
        memcpy(p, sep, lsep * sizeof(char)); p += lsep;
      }
    }
    memcpy(p, s, l * sizeof(char));  /* last copy (not followed by separator) */
    luaL_pushresultsize(&b, totallen);
  }
  return 1;
}
References lua_pushliteral, luaL_buffinitsize(), luaL_checkint, luaL_checklstring(), luaL_error(), luaL_optlstring(), luaL_pushresultsize(), MAXSIZE, and s.
str_reverse()
static int str_reverse (lua_State * L) static
Definition at line 67 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l, i;
  luaL_Buffer b;
  const char *s = luaL_checklstring(L, 1, &l);
  char *p = luaL_buffinitsize(L, &b, l);
  for (i = 0; i < l; i++)
    p[i] = s[l - i - 1];
  luaL_pushresultsize(&b, l);
  return 1;
}
References luaL_buffinitsize(), luaL_checklstring(), luaL_pushresultsize(), and s.
str_sub()
static int str_sub (lua_State * L) static
Definition at line 53 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l;
  const char *s = luaL_checklstring(L, 1, &l);
  size_t start = posrelat(luaL_checkinteger(L, 2), l);
  size_t end = posrelat(luaL_optinteger(L, 3, -1), l);
  if (start < 1) start = 1;
  if (end > l) end = l;
  if (start <= end)
    lua_pushlstring(L, s + start - 1, end - start + 1);
  else lua_pushliteral(L, "");
  return 1;
}
References lua_pushliteral, lua_pushlstring(), luaL_checkinteger(), luaL_checklstring(), luaL_optinteger(), posrelat(), and s.
str_upper()
static int str_upper (lua_State * L) static
Definition at line 92 of file lua-5.2.4/src/lstrlib.c.
{
  size_t l;
  size_t i;
  luaL_Buffer b;
  const char *s = luaL_checklstring(L, 1, &l);
  char *p = luaL_buffinitsize(L, &b, l);
  for (i=0; i<l; i++)
    p[i] = toupper(uchar(s[i]));
  luaL_pushresultsize(&b, l);
  return 1;
}
References luaL_buffinitsize(), luaL_checklstring(), luaL_pushresultsize(), s, and uchar.
writer()
static int writer (lua_State * L, const void * b, size_t size, void * B) static
Definition at line 167 of file lua-5.2.4/src/lstrlib.c.
{
  (void)L;
  luaL_addlstring((luaL_Buffer*) B, (const char *)b, size);
  return 0;
}
References luaL_addlstring().
Referenced by str_dump().
Variable Documentation
strlib
const luaL_Reg strlib[] static
Initial value:
= {
  {"byte", str_byte},
  {"char", str_char},
  {"dump", str_dump},
  {"find", str_find},
  {"format", str_format},
  {"gmatch", gmatch},
  {"gsub", str_gsub},
  {"len", str_len},
  {"lower", str_lower},
  {"match", str_match},
  {"rep", str_rep},
  {"reverse", str_reverse},
  {"sub", str_sub},
  {"upper", str_upper},
  {NULL, NULL}
}
Definition at line 980 of file lua-5.2.4/src/lstrlib.c.
{
  {"byte", str_byte},
  {"char", str_char},
  {"dump", str_dump},
  {"find", str_find},
  {"format", str_format},
  {"gmatch", gmatch},
  {"gsub", str_gsub},
  {"len", str_len},
  {"lower", str_lower},
  {"match", str_match},
  {"rep", str_rep},
  {"reverse", str_reverse},
  {"sub", str_sub},
  {"upper", str_upper},
  {NULL, NULL}
};
Referenced by luaopen_string().