Github User Fetcher: liolib.c File Reference
liolib.c File Reference
#include "lprefix.h"
#include <ctype.h>
#include <errno.h>
#include <locale.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Data Structures
struct RN
Macros
#define liolib_c
#define LUA_LIB
#define L_MODEEXT "b"
#define l_popen(L, c, m)
#define l_pclose(L, file) ((void)L, (void)file, -1)
#define l_checkmodep(m) ((m[0] == 'r' || m[0] == 'w') && m[1] == '\0')
#define l_getc(f) getc(f)
#define l_lockfile(f) ((void)0)
#define l_unlockfile(f) ((void)0)
#define l_fseek(f, o, w) fseek(f,o,w)
#define l_ftell(f) ftell(f)
#define l_seeknum long
#define IO_PREFIX "_IO_"
#define IOPREF_LEN (sizeof(IO_PREFIX)/sizeof(char) - 1)
#define IO_INPUT (IO_PREFIX "input")
#define IO_OUTPUT (IO_PREFIX "output")
#define tolstream(L) ((LStream *)luaL_checkudata(L, 1, LUA_FILEHANDLE))
#define isclosed(p) ((p)->closef == NULL)
#define MAXARGLINE 250
#define L_MAXLENNUM 200
Typedefs
typedef luaL_Stream LStream
Functions
static int l_checkmode (const char *mode)
static int io_type (lua_State *L)
static int f_tostring (lua_State *L)
static FILE * tofile (lua_State *L)
static LStream * newprefile (lua_State *L)
static int aux_close (lua_State *L)
static int f_close (lua_State *L)
static int io_close (lua_State *L)
static int f_gc (lua_State *L)
static int io_fclose (lua_State *L)
static LStream * newfile (lua_State *L)
static void opencheck (lua_State *L, const char *fname, const char *mode)
static int io_open (lua_State *L)
static int io_pclose (lua_State *L)
static int io_popen (lua_State *L)
static int io_tmpfile (lua_State *L)
static FILE * getiofile (lua_State *L, const char *findex)
static int g_iofile (lua_State *L, const char *f, const char *mode)
static int io_input (lua_State *L)
static int io_output (lua_State *L)
static int io_readline (lua_State *L)
static void aux_lines (lua_State *L, int toclose)
static int f_lines (lua_State *L)
static int io_lines (lua_State *L)
static int nextc (RN *rn)
static int test2 (RN *rn, const char *set)
static int readdigits (RN *rn, int hex)
static int read_number (lua_State *L, FILE *f)
static int test_eof (lua_State *L, FILE *f)
static int read_line (lua_State *L, FILE *f, int chop)
static void read_all (lua_State *L, FILE *f)
static int read_chars (lua_State *L, FILE *f, size_t n)
static int g_read (lua_State *L, FILE *f, int first)
static int io_read (lua_State *L)
static int f_read (lua_State *L)
static int g_write (lua_State *L, FILE *f, int arg)
static int io_write (lua_State *L)
static int f_write (lua_State *L)
static int f_seek (lua_State *L)
static int f_setvbuf (lua_State *L)
static int io_flush (lua_State *L)
static int f_flush (lua_State *L)
static void createmeta (lua_State *L)
static int io_noclose (lua_State *L)
static void createstdfile (lua_State *L, FILE *f, const char *k, const char *fname)
LUAMOD_API int luaopen_io (lua_State *L)
Variables
static const luaL_Reg iolib []
static const luaL_Reg meth []
static const luaL_Reg metameth []
Macro Definition Documentation
IO_INPUT
#define IO_INPUT (IO_PREFIX "input")
Definition at line 151 of file lua-5.4.3/src/liolib.c.
Referenced by io_input(), io_lines(), io_read(), and luaopen_io().
IO_OUTPUT
#define IO_OUTPUT (IO_PREFIX "output")
Definition at line 152 of file lua-5.4.3/src/liolib.c.
Referenced by io_close(), io_flush(), io_output(), io_write(), and luaopen_io().
IO_PREFIX
#define IO_PREFIX "_IO_"
Definition at line 149 of file lua-5.4.3/src/liolib.c.
IOPREF_LEN
#define IOPREF_LEN (sizeof(IO_PREFIX)/sizeof(char) - 1)
Definition at line 150 of file lua-5.4.3/src/liolib.c.
Referenced by getiofile().
isclosed
#define isclosed (p) ((p)->closef == NULL)
Definition at line 160 of file lua-5.4.3/src/liolib.c.
Referenced by f_gc(), f_tostring(), getiofile(), io_readline(), io_type(), and tofile().
l_checkmodep
#define l_checkmodep (m) ((m[0] == 'r' || m[0] == 'w') && m[1] == '\0')
Definition at line 89 of file lua-5.4.3/src/liolib.c.
Referenced by io_popen().
l_fseek
#define l_fseek (f, o, w) fseek(f,o,w)
Definition at line 137 of file lua-5.4.3/src/liolib.c.
Referenced by f_seek().
l_ftell
#define l_ftell (f) ftell(f)
Definition at line 138 of file lua-5.4.3/src/liolib.c.
Referenced by f_seek().
l_getc
#define l_getc (f) getc(f)
Definition at line 102 of file lua-5.4.3/src/liolib.c.
Referenced by nextc(), read_line(), and read_number().
l_lockfile
#define l_lockfile (f) ((void)0)
Definition at line 103 of file lua-5.4.3/src/liolib.c.
Referenced by read_line(), and read_number().
L_MAXLENNUM
#define L_MAXLENNUM 200
Definition at line 422 of file lua-5.4.3/src/liolib.c.
Referenced by nextc().
L_MODEEXT
#define L_MODEEXT "b"
Definition at line 36 of file lua-5.4.3/src/liolib.c.
Referenced by l_checkmode().
l_pclose
#define l_pclose (L, file) ((void)L, (void)file, -1)
Definition at line 80 of file lua-5.4.3/src/liolib.c.
Referenced by io_pclose().
l_popen
#define l_popen (L, c, m)
Value:
      ((void)c, (void)m, \
      luaL_error(L, "'popen' not supported"), \
      (FILE*)0)
Definition at line 76 of file lua-5.4.3/src/liolib.c.
#define l_popen(L,c,m)  \
      ((void)c, (void)m, \
      luaL_error(L, "'popen' not supported"), \
      (FILE*)0)
Referenced by io_popen().
l_seeknum
#define l_seeknum long
Definition at line 139 of file lua-5.4.3/src/liolib.c.
Referenced by f_seek().
l_unlockfile
#define l_unlockfile (f) ((void)0)
Definition at line 104 of file lua-5.4.3/src/liolib.c.
Referenced by read_line(), and read_number().
liolib_c
#define liolib_c
Definition at line 7 of file lua-5.4.3/src/liolib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.4.3/src/liolib.c.
MAXARGLINE
#define MAXARGLINE 250
Definition at line 352 of file lua-5.4.3/src/liolib.c.
Referenced by aux_lines().
tolstream
#define tolstream (L) ((LStream *)luaL_checkudata(L, 1, LUA_FILEHANDLE))
Definition at line 158 of file lua-5.4.3/src/liolib.c.
Referenced by aux_close(), f_gc(), f_tostring(), io_fclose(), io_noclose(), io_pclose(), and tofile().
Typedef Documentation
LStream
typedef luaL_Stream LStream
Definition at line 155 of file lua-5.4.3/src/liolib.c.
Function Documentation
aux_close()
static int aux_close (lua_State * L) static
Definition at line 214 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = tolstream(L);
  volatile lua_CFunction cf = p->closef;
  p->closef = NULL;  /* mark stream as closed */
  return (*cf)(L);  /* close it */
}
References luaL_Stream::closef, NULL, and tolstream.
Referenced by f_close(), f_gc(), and io_readline().
aux_lines()
static void aux_lines (lua_State * L, int toclose) static
Definition at line 363 of file lua-5.4.3/src/liolib.c.
{
  int n = lua_gettop(L) - 1;  /* number of arguments to read */
  luaL_argcheck(L, n <= MAXARGLINE, MAXARGLINE + 2, "too many arguments");
  lua_pushvalue(L, 1);  /* file */
  lua_pushinteger(L, n);  /* number of arguments to read */
  lua_pushboolean(L, toclose);  /* close/not close file when finished */
  lua_rotate(L, 2, 3);  /* move the three values to their positions */
  lua_pushcclosure(L, io_readline, 3 + n);
}
References io_readline(), lua_gettop(), lua_pushboolean(), lua_pushcclosure(), lua_pushinteger(), lua_pushvalue(), lua_rotate(), luaL_argcheck, and MAXARGLINE.
Referenced by f_lines(), and io_lines().
createmeta()
static void createmeta (lua_State * L) static
Definition at line 784 of file lua-5.4.3/src/liolib.c.
{
  luaL_newmetatable(L, LUA_FILEHANDLE);  /* metatable for file handles */
  luaL_setfuncs(L, metameth, 0);  /* add metamethods to new metatable */
  luaL_newlibtable(L, meth);  /* create method table */
  luaL_setfuncs(L, meth, 0);  /* add file methods to method table */
  lua_setfield(L, -2, "__index");  /* metatable.__index = method table */
  lua_pop(L, 1);  /* pop metatable */
}
References LUA_FILEHANDLE, lua_pop, lua_setfield(), luaL_newlibtable, luaL_newmetatable(), luaL_setfuncs(), metameth, and meth.
Referenced by luaopen_io().
createstdfile()
static void createstdfile (lua_State * L, FILE * f, const char * k, const char * fname) static
Definition at line 806 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = newprefile(L);
  p->f = f;
  p->closef = &io_noclose;
  if (k != NULL) {
    lua_pushvalue(L, -1);
    lua_setfield(L, LUA_REGISTRYINDEX, k);  /* add file to registry */
  }
  lua_setfield(L, -2, fname);  /* add file to module */
}
References luaL_Stream::closef, luaL_Stream::f, io_noclose(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), newprefile(), and NULL.
Referenced by luaopen_io().
f_close()
static int f_close (lua_State * L) static
Definition at line 222 of file lua-5.4.3/src/liolib.c.
{
  tofile(L);  /* make sure argument is an open stream */
  return aux_close(L);
}
References aux_close(), and tofile().
Referenced by io_close().
f_flush()
static int f_flush (lua_State * L) static
Definition at line 733 of file lua-5.4.3/src/liolib.c.
{
  return luaL_fileresult(L, fflush(tofile(L)) == 0, NULL);
}
References luaL_fileresult(), NULL, and tofile().
f_gc()
static int f_gc (lua_State * L) static
Definition at line 235 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = tolstream(L);
  if (!isclosed(p) && p->f != NULL)
    aux_close(L);  /* ignore closed and incompletely open files */
  return 0;
}
References aux_close(), luaL_Stream::f, isclosed, NULL, and tolstream.
f_lines()
static int f_lines (lua_State * L) static
Definition at line 374 of file lua-5.4.3/src/liolib.c.
{
  tofile(L);  /* check that it's a valid file handle */
  aux_lines(L, 0);
  return 1;
}
References aux_lines(), and tofile().
f_read()
static int f_read (lua_State * L) static
Definition at line 621 of file lua-5.4.3/src/liolib.c.
{
  return g_read(L, tofile(L), 2);
}
References g_read(), and tofile().
f_seek()
static int f_seek (lua_State * L) static
Definition at line 697 of file lua-5.4.3/src/liolib.c.
{
  static const int mode[] = {SEEK_SET, SEEK_CUR, SEEK_END};
  static const char *const modenames[] = {"set", "cur", "end", NULL};
  FILE *f = tofile(L);
  int op = luaL_checkoption(L, 2, "cur", modenames);
  lua_Integer p3 = luaL_optinteger(L, 3, 0);
  l_seeknum offset = (l_seeknum)p3;
  luaL_argcheck(L, (lua_Integer)offset == p3, 3,
                  "not an integer in proper range");
  op = l_fseek(f, offset, mode[op]);
  if (l_unlikely(op))
    return luaL_fileresult(L, 0, NULL);  /* error */
  else {
    lua_pushinteger(L, (lua_Integer)l_ftell(f));
    return 1;
  }
}
References l_fseek, l_ftell, l_seeknum, lua_pushinteger(), luaL_argcheck, luaL_checkoption(), luaL_fileresult(), luaL_optinteger(), NULL, and tofile().
f_setvbuf()
static int f_setvbuf (lua_State * L) static
Definition at line 716 of file lua-5.4.3/src/liolib.c.
{
  static const int mode[] = {_IONBF, _IOFBF, _IOLBF};
  static const char *const modenames[] = {"no", "full", "line", NULL};
  FILE *f = tofile(L);
  int op = luaL_checkoption(L, 2, NULL, modenames);
  lua_Integer sz = luaL_optinteger(L, 3, LUAL_BUFFERSIZE);
  int res = setvbuf(f, NULL, mode[op], (size_t)sz);
  return luaL_fileresult(L, res == 0, NULL);
}
References LUAL_BUFFERSIZE, luaL_checkoption(), luaL_fileresult(), luaL_optinteger(), NULL, and tofile().
f_tostring()
static int f_tostring (lua_State * L) static
Definition at line 177 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = tolstream(L);
  if (isclosed(p))
    lua_pushliteral(L, "file (closed)");
  else
    lua_pushfstring(L, "file (%p)", p->f);
  return 1;
}
References luaL_Stream::f, isclosed, lua_pushfstring(), lua_pushliteral, and tolstream.
f_write()
static int f_write (lua_State * L) static
Definition at line 690 of file lua-5.4.3/src/liolib.c.
{
  FILE *f = tofile(L);
  lua_pushvalue(L, 1);  /* push file at the stack top (to be returned) */
  return g_write(L, f, 2);
}
References g_write(), lua_pushvalue(), and tofile().
g_iofile()
static int g_iofile (lua_State * L, const char * f, const char * mode) static
Definition at line 318 of file lua-5.4.3/src/liolib.c.
{
  if (!lua_isnoneornil(L, 1)) {
    const char *filename = lua_tostring(L, 1);
    if (filename)
      opencheck(L, filename, mode);
    else {
      tofile(L);  /* check that it's a valid file handle */
      lua_pushvalue(L, 1);
    }
    lua_setfield(L, LUA_REGISTRYINDEX, f);
  }
  /* return current value */
  lua_getfield(L, LUA_REGISTRYINDEX, f);
  return 1;
}
References lua_getfield(), lua_isnoneornil, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_tostring, opencheck(), and tofile().
Referenced by io_input(), and io_output().
g_read()
static int g_read (lua_State * L, FILE * f, int first) static
Definition at line 566 of file lua-5.4.3/src/liolib.c.
{
  int nargs = lua_gettop(L) - 1;
  int n, success;
  clearerr(f);
  if (nargs == 0) {  /* no arguments? */
    success = read_line(L, f, 1);
    n = first + 1;  /* to return 1 result */
  }
  else {
    /* ensure stack space for all results and for auxlib's buffer */
    luaL_checkstack(L, nargs+LUA_MINSTACK, "too many arguments");
    success = 1;
    for (n = first; nargs-- && success; n++) {
      if (lua_type(L, n) == LUA_TNUMBER) {
        size_t l = (size_t)luaL_checkinteger(L, n);
        success = (l == 0) ? test_eof(L, f) : read_chars(L, f, l);
      }
      else {
        const char *p = luaL_checkstring(L, n);
        if (*p == '*') p++;  /* skip optional '*' (for compatibility) */
        switch (*p) {
          case 'n':  /* number */
            success = read_number(L, f);
            break;
          case 'l':  /* line */
            success = read_line(L, f, 1);
            break;
          case 'L':  /* line with end-of-line */
            success = read_line(L, f, 0);
            break;
          case 'a':  /* file */
            read_all(L, f);  /* read entire file */
            success = 1; /* always success */
            break;
          default:
            return luaL_argerror(L, n, "invalid format");
        }
      }
    }
  }
  if (ferror(f))
    return luaL_fileresult(L, 0, NULL);
  if (!success) {
    lua_pop(L, 1);  /* remove last result */
    luaL_pushfail(L);  /* push nil instead */
  }
  return n - first;
}
References lua_gettop(), LUA_MINSTACK, lua_pop, LUA_TNUMBER, lua_type(), luaL_argerror(), luaL_checkinteger(), luaL_checkstack(), luaL_checkstring, luaL_fileresult(), luaL_pushfail, NULL, read_all(), read_chars(), read_line(), read_number(), and test_eof().
Referenced by f_read(), io_read(), and io_readline().
g_write()
static int g_write (lua_State * L, FILE * f, int arg) static
Definition at line 660 of file lua-5.4.3/src/liolib.c.
{
  int nargs = lua_gettop(L) - arg;
  int status = 1;
  for (; nargs--; arg++) {
    if (lua_type(L, arg) == LUA_TNUMBER) {
      /* optimization: could be done exactly as for strings */
      int len = lua_isinteger(L, arg)
                ? fprintf(f, LUA_INTEGER_FMT,
                             (LUAI_UACINT)lua_tointeger(L, arg))
                : fprintf(f, LUA_NUMBER_FMT,
                             (LUAI_UACNUMBER)lua_tonumber(L, arg));
      status = status && (len > 0);
    }
    else {
      size_t l;
      const char *s = luaL_checklstring(L, arg, &l);
      status = status && (fwrite(s, sizeof(char), l, f) == l);
    }
  }
  if (l_likely(status))
    return 1;  /* file handle already on stack top */
  else return luaL_fileresult(L, status, NULL);
}
References arg, fwrite(), lua_gettop(), LUA_INTEGER_FMT, lua_isinteger(), LUA_NUMBER_FMT, LUA_TNUMBER, lua_tointeger, lua_tonumber, lua_type(), LUAI_UACINT, LUAI_UACNUMBER, luaL_checklstring(), luaL_fileresult(), NULL, and s.
Referenced by f_write(), and io_write().
getiofile()
static FILE * getiofile (lua_State * L, const char * findex) static
Definition at line 308 of file lua-5.4.3/src/liolib.c.
{
  LStream *p;
  lua_getfield(L, LUA_REGISTRYINDEX, findex);
  p = (LStream *)lua_touserdata(L, -1);
  if (l_unlikely(isclosed(p)))
    luaL_error(L, "default %s file is closed", findex + IOPREF_LEN);
  return p->f;
}
References luaL_Stream::f, IOPREF_LEN, isclosed, lua_getfield(), LUA_REGISTRYINDEX, lua_touserdata(), and luaL_error().
Referenced by io_flush(), io_read(), and io_write().
io_close()
static int io_close (lua_State * L) static
Definition at line 228 of file lua-5.4.3/src/liolib.c.
{
  if (lua_isnone(L, 1))  /* no argument? */
    lua_getfield(L, LUA_REGISTRYINDEX, IO_OUTPUT);  /* use default output */
  return f_close(L);
}
References f_close(), IO_OUTPUT, lua_getfield(), lua_isnone, and LUA_REGISTRYINDEX.
io_fclose()
static int io_fclose (lua_State * L) static
Definition at line 246 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = tolstream(L);
  int res = fclose(p->f);
  return luaL_fileresult(L, (res == 0), NULL);
}
References luaL_Stream::f, luaL_fileresult(), NULL, and tolstream.
Referenced by newfile().
io_flush()
static int io_flush (lua_State * L) static
Definition at line 728 of file lua-5.4.3/src/liolib.c.
{
  return luaL_fileresult(L, fflush(getiofile(L, IO_OUTPUT)) == 0, NULL);
}
References getiofile(), IO_OUTPUT, luaL_fileresult(), and NULL.
io_input()
static int io_input (lua_State * L) static
Definition at line 335 of file lua-5.4.3/src/liolib.c.
{
  return g_iofile(L, IO_INPUT, "r");
}
References g_iofile(), and IO_INPUT.
io_lines()
static int io_lines (lua_State * L) static
Definition at line 386 of file lua-5.4.3/src/liolib.c.
{
  int toclose;
  if (lua_isnone(L, 1)) lua_pushnil(L);  /* at least one argument */
  if (lua_isnil(L, 1)) {  /* no file name? */
    lua_getfield(L, LUA_REGISTRYINDEX, IO_INPUT);  /* get default input */
    lua_replace(L, 1);  /* put it at index 1 */
    tofile(L);  /* check that it's a valid file handle */
    toclose = 0;  /* do not close it after iteration */
  }
  else {  /* open a new file */
    const char *filename = luaL_checkstring(L, 1);
    opencheck(L, filename, "r");
    lua_replace(L, 1);  /* put file at index 1 */
    toclose = 1;  /* close it after iteration */
  }
  aux_lines(L, toclose);  /* push iteration function */
  if (toclose) {
    lua_pushnil(L);  /* state */
    lua_pushnil(L);  /* control */
    lua_pushvalue(L, 1);  /* file is the to-be-closed variable (4th result) */
    return 4;
  }
  else
    return 1;
}
References aux_lines(), IO_INPUT, lua_getfield(), lua_isnil, lua_isnone, lua_pushnil(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_replace, luaL_checkstring, opencheck(), and tofile().
io_noclose()
static int io_noclose (lua_State * L) static
Definition at line 797 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = tolstream(L);
  p->closef = &io_noclose;  /* keep file opened */
  luaL_pushfail(L);
  lua_pushliteral(L, "cannot close standard file");
  return 2;
}
References luaL_Stream::closef, io_noclose(), lua_pushliteral, luaL_pushfail, and tolstream.
Referenced by createstdfile(), and io_noclose().
io_open()
static int io_open (lua_State * L) static
Definition at line 269 of file lua-5.4.3/src/liolib.c.
{
  const char *filename = luaL_checkstring(L, 1);
  const char *mode = luaL_optstring(L, 2, "r");
  LStream *p = newfile(L);
  const char *md = mode;  /* to traverse/check mode */
  luaL_argcheck(L, l_checkmode(md), 2, "invalid mode");
  p->f = fopen(filename, mode);
  return (p->f == NULL) ? luaL_fileresult(L, 0, filename) : 1;
}
References luaL_Stream::f, l_checkmode(), luaL_argcheck, luaL_checkstring, luaL_fileresult(), luaL_optstring, newfile(), and NULL.
io_output()
static int io_output (lua_State * L) static
Definition at line 340 of file lua-5.4.3/src/liolib.c.
{
  return g_iofile(L, IO_OUTPUT, "w");
}
References g_iofile(), and IO_OUTPUT.
io_pclose()
static int io_pclose (lua_State * L) static
Definition at line 283 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = tolstream(L);
  errno = 0;
  return luaL_execresult(L, l_pclose(L, p->f));
}
References luaL_Stream::f, l_pclose, luaL_execresult(), and tolstream.
Referenced by io_popen().
io_popen()
static int io_popen (lua_State * L) static
Definition at line 290 of file lua-5.4.3/src/liolib.c.
{
  const char *filename = luaL_checkstring(L, 1);
  const char *mode = luaL_optstring(L, 2, "r");
  LStream *p = newprefile(L);
  luaL_argcheck(L, l_checkmodep(mode), 2, "invalid mode");
  p->f = l_popen(L, filename, mode);
  p->closef = &io_pclose;
  return (p->f == NULL) ? luaL_fileresult(L, 0, filename) : 1;
}
References luaL_Stream::closef, luaL_Stream::f, io_pclose(), l_checkmodep, l_popen, luaL_argcheck, luaL_checkstring, luaL_fileresult(), luaL_optstring, newprefile(), and NULL.
io_read()
static int io_read (lua_State * L) static
Definition at line 616 of file lua-5.4.3/src/liolib.c.
{
  return g_read(L, getiofile(L, IO_INPUT), 1);
}
References g_read(), getiofile(), and IO_INPUT.
io_readline()
static int io_readline (lua_State * L) static
Definition at line 629 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = (LStream *)lua_touserdata(L, lua_upvalueindex(1));
  int i;
  int n = (int)lua_tointeger(L, lua_upvalueindex(2));
  if (isclosed(p))  /* file is already closed? */
    return luaL_error(L, "file is already closed");
  lua_settop(L , 1);
  luaL_checkstack(L, n, "too many arguments");
  for (i = 1; i <= n; i++)  /* push arguments to 'g_read' */
    lua_pushvalue(L, lua_upvalueindex(3 + i));
  n = g_read(L, p->f, 2);  /* 'n' is number of results */
  lua_assert(n > 0);  /* should return at least a nil */
  if (lua_toboolean(L, -n))  /* read at least one value? */
    return n;  /* return them */
  else {  /* first result is false: EOF or error */
    if (n > 1) {  /* is there error information? */
      /* 2nd result is error message */
      return luaL_error(L, "%s", lua_tostring(L, -n + 1));
    }
    if (lua_toboolean(L, lua_upvalueindex(3))) {  /* generator created file? */
      lua_settop(L, 0);  /* clear stack */
      lua_pushvalue(L, lua_upvalueindex(1));  /* push file at index 1 */
      aux_close(L);  /* close it */
    }
    return 0;
  }
}
References aux_close(), luaL_Stream::f, g_read(), isclosed, lua_assert, lua_pushvalue(), lua_settop(), lua_toboolean(), lua_tointeger, lua_tostring, lua_touserdata(), lua_upvalueindex, luaL_checkstack(), and luaL_error().
Referenced by aux_lines().
io_tmpfile()
static int io_tmpfile (lua_State * L) static
Definition at line 301 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = newfile(L);
  p->f = tmpfile();
  return (p->f == NULL) ? luaL_fileresult(L, 0, NULL) : 1;
}
References luaL_Stream::f, luaL_fileresult(), newfile(), and NULL.
io_type()
static int io_type (lua_State * L) static
Definition at line 163 of file lua-5.4.3/src/liolib.c.
{
  LStream *p;
  luaL_checkany(L, 1);
  p = (LStream *)luaL_testudata(L, 1, LUA_FILEHANDLE);
  if (p == NULL)
    luaL_pushfail(L);  /* not a file */
  else if (isclosed(p))
    lua_pushliteral(L, "closed file");
  else
    lua_pushliteral(L, "file");
  return 1;
}
References isclosed, LUA_FILEHANDLE, lua_pushliteral, luaL_checkany(), luaL_pushfail, luaL_testudata(), and NULL.
io_write()
static int io_write (lua_State * L) static
Definition at line 685 of file lua-5.4.3/src/liolib.c.
{
  return g_write(L, getiofile(L, IO_OUTPUT), 1);
}
References g_write(), getiofile(), and IO_OUTPUT.
l_checkmode()
static int l_checkmode (const char * mode) static
Definition at line 40 of file lua-5.4.3/src/liolib.c.
{
  return (*mode != '\0' && strchr("rwa", *(mode++)) != NULL &&
         (*mode != '+' || ((void)(++mode), 1)) &&  /* skip if char is '+' */
         (strspn(mode, L_MODEEXT) == strlen(mode)));  /* check extensions */
}
References L_MODEEXT, and NULL.
Referenced by io_open().
luaopen_io()
LUAMOD_API int luaopen_io (lua_State * L)
Definition at line 819 of file lua-5.4.3/src/liolib.c.
{
  luaL_newlib(L, iolib);  /* new module */
  createmeta(L);
  /* create (and set) default files */
  createstdfile(L, stdin, IO_INPUT, "stdin");
  createstdfile(L, stdout, IO_OUTPUT, "stdout");
  createstdfile(L, stderr, NULL, "stderr");
  return 1;
}
References createmeta(), createstdfile(), IO_INPUT, IO_OUTPUT, iolib, luaL_newlib, and NULL.
newfile()
static LStream * newfile (lua_State * L) static
Definition at line 253 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = newprefile(L);
  p->f = NULL;
  p->closef = &io_fclose;
  return p;
}
References luaL_Stream::closef, luaL_Stream::f, io_fclose(), newprefile(), and NULL.
Referenced by io_open(), io_tmpfile(), and opencheck().
newprefile()
static LStream * newprefile (lua_State * L) static
Definition at line 201 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = (LStream *)lua_newuserdatauv(L, sizeof(LStream), 0);
  p->closef = NULL;  /* mark file handle as 'closed' */
  luaL_setmetatable(L, LUA_FILEHANDLE);
  return p;
}
References luaL_Stream::closef, LUA_FILEHANDLE, lua_newuserdatauv(), luaL_setmetatable(), and NULL.
Referenced by createstdfile(), io_popen(), and newfile().
nextc()
static int nextc (RN * rn) static
Definition at line 438 of file lua-5.4.3/src/liolib.c.
{
  if (l_unlikely(rn->n >= L_MAXLENNUM)) {  /* buffer overflow? */
    rn->buff[0] = '\0';  /* invalidate result */
    return 0;  /* fail */
  }
  else {
    rn->buff[rn->n++] = rn->c;  /* save current char */
    rn->c = l_getc(rn->f);  /* read next one */
    return 1;
  }
}
References RN::buff, RN::c, RN::f, l_getc, L_MAXLENNUM, and RN::n.
Referenced by readdigits(), and test2().
opencheck()
static void opencheck (lua_State * L, const char * fname, const char * mode) static
Definition at line 261 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = newfile(L);
  p->f = fopen(fname, mode);
  if (l_unlikely(p->f == NULL))
    luaL_error(L, "cannot open file '%s' (%s)", fname, strerror(errno));
}
References luaL_Stream::f, luaL_error(), newfile(), and NULL.
Referenced by g_iofile(), and io_lines().
read_all()
static void read_all (lua_State * L, FILE * f) static
Definition at line 540 of file lua-5.4.3/src/liolib.c.
{
  size_t nr;
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  do {  /* read file in chunks of LUAL_BUFFERSIZE bytes */
    char *p = luaL_prepbuffer(&b);
    nr = fread(p, sizeof(char), LUAL_BUFFERSIZE, f);
    luaL_addsize(&b, nr);
  } while (nr == LUAL_BUFFERSIZE);
  luaL_pushresult(&b);  /* close buffer */
}
References fread(), luaL_addsize, LUAL_BUFFERSIZE, luaL_buffinit(), luaL_prepbuffer, and luaL_pushresult().
Referenced by g_read().
read_chars()
static int read_chars (lua_State * L, FILE * f, size_t n) static
Definition at line 553 of file lua-5.4.3/src/liolib.c.
{
  size_t nr;  /* number of chars actually read */
  char *p;
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  p = luaL_prepbuffsize(&b, n);  /* prepare buffer to read whole block */
  nr = fread(p, sizeof(char), n, f);  /* try to read 'n' chars */
  luaL_addsize(&b, nr);
  luaL_pushresult(&b);  /* close buffer */
  return (nr > 0);  /* true iff read something */
}
References fread(), luaL_addsize, luaL_buffinit(), luaL_prepbuffsize(), and luaL_pushresult().
Referenced by g_read().
read_line()
static int read_line (lua_State * L, FILE * f, int chop) static
Definition at line 519 of file lua-5.4.3/src/liolib.c.
{
  luaL_Buffer b;
  int c;
  luaL_buffinit(L, &b);
  do {  /* may need to read several chunks to get whole line */
    char *buff = luaL_prepbuffer(&b);  /* preallocate buffer space */
    int i = 0;
    l_lockfile(f);  /* no memory errors can happen inside the lock */
    while (i < LUAL_BUFFERSIZE && (c = l_getc(f)) != EOF && c != '\n')
      buff[i++] = c;  /* read up to end of line or buffer limit */
    l_unlockfile(f);
    luaL_addsize(&b, i);
  } while (c != EOF && c != '\n');  /* repeat until end of line */
  if (!chop && c == '\n')  /* want a newline and have one? */
    luaL_addchar(&b, c);  /* add ending newline to result */
  luaL_pushresult(&b);  /* close buffer */
  /* return ok if read something (either a newline or something else) */
  return (c == '\n' || lua_rawlen(L, -1) > 0);
}
References l_getc, l_lockfile, l_unlockfile, lua_rawlen, luaL_addchar, luaL_addsize, LUAL_BUFFERSIZE, luaL_buffinit(), luaL_prepbuffer, and luaL_pushresult().
Referenced by g_read().
read_number()
static int read_number (lua_State * L, FILE * f) static
Definition at line 477 of file lua-5.4.3/src/liolib.c.
{
  RN rn;
  int count = 0;
  int hex = 0;
  char decp[2];
  rn.f = f; rn.n = 0;
  decp[0] = lua_getlocaledecpoint();  /* get decimal point from locale */
  decp[1] = '.';  /* always accept a dot */
  l_lockfile(rn.f);
  do { rn.c = l_getc(rn.f); } while (isspace(rn.c));  /* skip spaces */
  test2(&rn, "-+");  /* optional sign */
  if (test2(&rn, "00")) {
    if (test2(&rn, "xX")) hex = 1;  /* numeral is hexadecimal */
    else count = 1;  /* count initial '0' as a valid digit */
  }
  count += readdigits(&rn, hex);  /* integral part */
  if (test2(&rn, decp))  /* decimal point? */
    count += readdigits(&rn, hex);  /* fractional part */
  if (count > 0 && test2(&rn, (hex ? "pP" : "eE"))) {  /* exponent mark? */
    test2(&rn, "-+");  /* exponent sign */
    readdigits(&rn, 0);  /* exponent digits */
  }
  ungetc(rn.c, rn.f);  /* unread look-ahead char */
  l_unlockfile(rn.f);
  rn.buff[rn.n] = '\0';  /* finish string */
  if (l_likely(lua_stringtonumber(L, rn.buff)))
    return 1;  /* ok, it is a valid number */
  else {  /* invalid format */
   lua_pushnil(L);  /* "result" to be removed */
   return 0;  /* read fails */
  }
}
References RN::buff, RN::c, RN::f, l_getc, l_lockfile, l_unlockfile, lua_getlocaledecpoint, lua_pushnil(), lua_stringtonumber(), RN::n, readdigits(), and test2().
Referenced by g_read().
readdigits()
static int readdigits (RN * rn, int hex) static
Definition at line 464 of file lua-5.4.3/src/liolib.c.
{
  int count = 0;
  while ((hex ? isxdigit(rn->c) : isdigit(rn->c)) && nextc(rn))
    count++;
  return count;
}
References RN::c, and nextc().
Referenced by read_number().
test2()
static int test2 (RN * rn, const char * set) static
Definition at line 454 of file lua-5.4.3/src/liolib.c.
{
  if (rn->c == set[0] || rn->c == set[1])
    return nextc(rn);
  else return 0;
}
References RN::c, and nextc().
Referenced by read_number().
test_eof()
static int test_eof (lua_State * L, FILE * f) static
Definition at line 511 of file lua-5.4.3/src/liolib.c.
{
  int c = getc(f);
  ungetc(c, f);  /* no-op when c == EOF */
  lua_pushliteral(L, "");
  return (c != EOF);
}
References lua_pushliteral.
Referenced by g_read().
tofile()
static FILE * tofile (lua_State * L) static
Definition at line 187 of file lua-5.4.3/src/liolib.c.
{
  LStream *p = tolstream(L);
  if (l_unlikely(isclosed(p)))
    luaL_error(L, "attempt to use a closed file");
  lua_assert(p->f);
  return p->f;
}
References luaL_Stream::f, isclosed, lua_assert, luaL_error(), and tolstream.
Referenced by f_close(), f_flush(), f_lines(), f_read(), f_seek(), f_setvbuf(), f_write(), g_iofile(), and io_lines().
Variable Documentation
iolib
const luaL_Reg iolib[] static
Initial value:
= {
  {"close", io_close},
  {"flush", io_flush},
  {"input", io_input},
  {"lines", io_lines},
  {"open", io_open},
  {"output", io_output},
  {"popen", io_popen},
  {"read", io_read},
  {"tmpfile", io_tmpfile},
  {"type", io_type},
  {"write", io_write},
  {NULL, NULL}
}
Definition at line 741 of file lua-5.4.3/src/liolib.c.
{
  {"close", io_close},
  {"flush", io_flush},
  {"input", io_input},
  {"lines", io_lines},
  {"open", io_open},
  {"output", io_output},
  {"popen", io_popen},
  {"read", io_read},
  {"tmpfile", io_tmpfile},
  {"type", io_type},
  {"write", io_write},
  {NULL, NULL}
};
Referenced by luaopen_io().
metameth
const luaL_Reg metameth[] static
Initial value:
= {
  {"__index", NULL},
  {"__gc", f_gc},
  {"__close", f_gc},
  {"__tostring", f_tostring},
  {NULL, NULL}
}
Definition at line 775 of file lua-5.4.3/src/liolib.c.
{
  {"__index", NULL},  /* place holder */
  {"__gc", f_gc},
  {"__close", f_gc},
  {"__tostring", f_tostring},
  {NULL, NULL}
};
Referenced by createmeta().
meth
const luaL_Reg meth[] static
Initial value:
= {
  {"read", f_read},
  {"write", f_write},
  {"lines", f_lines},
  {"flush", f_flush},
  {"seek", f_seek},
  {"close", f_close},
  {"setvbuf", f_setvbuf},
  {NULL, NULL}
}
Definition at line 760 of file lua-5.4.3/src/liolib.c.
{
  {"read", f_read},
  {"write", f_write},
  {"lines", f_lines},
  {"flush", f_flush},
  {"seek", f_seek},
  {"close", f_close},
  {"setvbuf", f_setvbuf},
  {NULL, NULL}
};
Referenced by createmeta().