Github User Fetcher: lauxlib.h File Reference
lauxlib.h File Reference
#include <stddef.h>
#include <stdio.h>
#include "luaconf.h"
#include "lua.h"
Data Structures
struct luaL_Reg
struct luaL_Buffer
struct luaL_Stream
Macros
#define LUA_GNAME "_G"
#define LUA_ERRFILE (LUA_ERRERR+1)
#define LUA_LOADED_TABLE "_LOADED"
#define LUA_PRELOAD_TABLE "_PRELOAD"
#define LUAL_NUMSIZES (sizeof(lua_Integer)*16 + sizeof(lua_Number))
#define luaL_checkversion(L) luaL_checkversion_(L, LUA_VERSION_NUM, LUAL_NUMSIZES)
#define LUA_NOREF (-2)
#define LUA_REFNIL (-1)
#define luaL_loadfile(L, f) luaL_loadfilex(L,f,NULL)
#define luaL_newlibtable(L, l) lua_createtable(L, 0, sizeof(l)/sizeof((l)[0]) - 1)
#define luaL_newlib(L, l) (luaL_checkversion(L), luaL_newlibtable(L,l), luaL_setfuncs(L,l,0))
#define luaL_argcheck(L, cond, arg, extramsg) ((void)(luai_likely(cond) || luaL_argerror(L, (arg), (extramsg))))
#define luaL_argexpected(L, cond, arg, tname) ((void)(luai_likely(cond) || luaL_typeerror(L, (arg), (tname))))
#define luaL_checkstring(L, n) (luaL_checklstring(L, (n), NULL))
#define luaL_optstring(L, n, d) (luaL_optlstring(L, (n), (d), NULL))
#define luaL_typename(L, i) lua_typename(L, lua_type(L,(i)))
#define luaL_dofile(L, fn) (luaL_loadfile(L, fn) || lua_pcall(L, 0, LUA_MULTRET, 0))
#define luaL_dostring(L, s) (luaL_loadstring(L, s) || lua_pcall(L, 0, LUA_MULTRET, 0))
#define luaL_getmetatable(L, n) (lua_getfield(L, LUA_REGISTRYINDEX, (n)))
#define luaL_opt(L, f, n, d) (lua_isnoneornil(L,(n)) ? (d) : f(L,(n)))
#define luaL_loadbuffer(L, s, sz, n) luaL_loadbufferx(L,s,sz,n,NULL)
#define luaL_pushfail(L) lua_pushnil(L)
#define lua_assert(c) ((void)0)
#define luaL_bufflen(bf) ((bf)->n)
#define luaL_buffaddr(bf) ((bf)->b)
#define luaL_addchar(B, c)
#define luaL_addsize(B, s) ((B)->n += (s))
#define luaL_buffsub(B, s) ((B)->n -= (s))
#define luaL_prepbuffer(B) luaL_prepbuffsize(B, LUAL_BUFFERSIZE)
#define LUA_FILEHANDLE "FILE*"
#define lua_writestring(s, l) fwrite((s), sizeof(char), (l), stdout)
#define lua_writeline() (lua_writestring("\n", 1), fflush(stdout))
#define lua_writestringerror(s, p) (fprintf(stderr, (s), (p)), fflush(stderr))
Typedefs
typedef struct luaL_Buffer luaL_Buffer
typedef struct luaL_Reg luaL_Reg
typedef struct luaL_Stream luaL_Stream
Functions
LUALIB_API void luaL_checkversion_ (lua_State *L, lua_Number ver, size_t sz)
LUALIB_API int luaL_getmetafield (lua_State *L, int obj, const char *e)
LUALIB_API int luaL_callmeta (lua_State *L, int obj, const char *e)
LUALIB_API const char * luaL_tolstring (lua_State *L, int idx, size_t *len)
LUALIB_API int luaL_argerror (lua_State *L, int arg, const char *extramsg)
LUALIB_API int luaL_typeerror (lua_State *L, int arg, const char *tname)
LUALIB_API const char * luaL_checklstring (lua_State *L, int arg, size_t *l)
LUALIB_API const char * luaL_optlstring (lua_State *L, int arg, const char *def, size_t *l)
LUALIB_API lua_Number luaL_checknumber (lua_State *L, int arg)
LUALIB_API lua_Number luaL_optnumber (lua_State *L, int arg, lua_Number def)
LUALIB_API lua_Integer luaL_checkinteger (lua_State *L, int arg)
LUALIB_API lua_Integer luaL_optinteger (lua_State *L, int arg, lua_Integer def)
LUALIB_API void luaL_checkstack (lua_State *L, int sz, const char *msg)
LUALIB_API void luaL_checktype (lua_State *L, int arg, int t)
LUALIB_API void luaL_checkany (lua_State *L, int arg)
LUALIB_API int luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void luaL_setmetatable (lua_State *L, const char *tname)
LUALIB_API void * luaL_testudata (lua_State *L, int ud, const char *tname)
LUALIB_API void * luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API void luaL_where (lua_State *L, int lvl)
LUALIB_API int luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int luaL_checkoption (lua_State *L, int arg, const char *def, const char *const lst[])
LUALIB_API int luaL_fileresult (lua_State *L, int stat, const char *fname)
LUALIB_API int luaL_execresult (lua_State *L, int stat)
LUALIB_API int luaL_ref (lua_State *L, int t)
LUALIB_API void luaL_unref (lua_State *L, int t, int ref)
LUALIB_API int luaL_loadfilex (lua_State *L, const char *filename, const char *mode)
LUALIB_API int luaL_loadbufferx (lua_State *L, const char *buff, size_t sz, const char *name, const char *mode)
LUALIB_API int luaL_loadstring (lua_State *L, const char *s)
LUALIB_API lua_State * luaL_newstate (void)
LUALIB_API lua_Integer luaL_len (lua_State *L, int idx)
LUALIB_API void luaL_addgsub (luaL_Buffer *b, const char *s, const char *p, const char *r)
LUALIB_API const char * luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
LUALIB_API void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUALIB_API int luaL_getsubtable (lua_State *L, int idx, const char *fname)
LUALIB_API void luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level)
LUALIB_API void luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb)
LUALIB_API void luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void luaL_addvalue (luaL_Buffer *B)
LUALIB_API void luaL_pushresult (luaL_Buffer *B)
LUALIB_API void luaL_pushresultsize (luaL_Buffer *B, size_t sz)
LUALIB_API char * luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz)
Macro Definition Documentation
lua_assert
#define lua_assert (c) ((void)0)
Definition at line 170 of file lua-5.4.3/src/lauxlib.h.
LUA_ERRFILE
#define LUA_ERRFILE (LUA_ERRERR+1)
Definition at line 27 of file lua-5.4.3/src/lauxlib.h.
LUA_FILEHANDLE
#define LUA_FILEHANDLE "FILE*"
Definition at line 234 of file lua-5.4.3/src/lauxlib.h.
LUA_GNAME
#define LUA_GNAME "_G"
Definition at line 20 of file lua-5.4.3/src/lauxlib.h.
Referenced by luaopen_base(), and pushglobalfuncname().
LUA_LOADED_TABLE
#define LUA_LOADED_TABLE "_LOADED"
Definition at line 31 of file lua-5.4.3/src/lauxlib.h.
LUA_NOREF
#define LUA_NOREF (-2)
Definition at line 86 of file lua-5.4.3/src/lauxlib.h.
LUA_PRELOAD_TABLE
#define LUA_PRELOAD_TABLE "_PRELOAD"
Definition at line 35 of file lua-5.4.3/src/lauxlib.h.
LUA_REFNIL
#define LUA_REFNIL (-1)
Definition at line 87 of file lua-5.4.3/src/lauxlib.h.
lua_writeline
#define lua_writeline () (lua_writestring("\n", 1), fflush(stdout))
Definition at line 257 of file lua-5.4.3/src/lauxlib.h.
lua_writestring
#define lua_writestring (s, l) fwrite((s), sizeof(char), (l), stdout)
Definition at line 252 of file lua-5.4.3/src/lauxlib.h.
lua_writestringerror
#define lua_writestringerror (s, p) (fprintf(stderr, (s), (p)), fflush(stderr))
Definition at line 262 of file lua-5.4.3/src/lauxlib.h.
#define lua_writestringerror(s,p) \
        (fprintf(stderr, (s), (p)), fflush(stderr))
luaL_addchar
#define luaL_addchar (B, c)
Value:
  ((void)((B)->n < (B)->size || luaL_prepbuffsize((B), 1)), \
   ((B)->b[(B)->n++] = (c)))
Definition at line 199 of file lua-5.4.3/src/lauxlib.h.
#define luaL_addchar(B,c) \
  ((void)((B)->n < (B)->size || luaL_prepbuffsize((B), 1)), \
   ((B)->b[(B)->n++] = (c)))
luaL_addsize
#define luaL_addsize (B, s) ((B)->n += (s))
Definition at line 203 of file lua-5.4.3/src/lauxlib.h.
luaL_argcheck
#define luaL_argcheck (L, cond, arg, extramsg) ((void)(luai_likely(cond) || luaL_argerror(L, (arg), (extramsg))))
Definition at line 133 of file lua-5.4.3/src/lauxlib.h.
#define luaL_argcheck(L, cond,arg,extramsg) \
    ((void)(luai_likely(cond) || luaL_argerror(L, (arg), (extramsg))))
luaL_argexpected
#define luaL_argexpected (L, cond, arg, tname) ((void)(luai_likely(cond) || luaL_typeerror(L, (arg), (tname))))
Definition at line 136 of file lua-5.4.3/src/lauxlib.h.
#define luaL_argexpected(L,cond,arg,tname)  \
    ((void)(luai_likely(cond) || luaL_typeerror(L, (arg), (tname))))
Referenced by db_setmetatable(), getco(), luaB_rawlen(), luaB_setmetatable(), luaL_checkudata(), and str_gsub().
luaL_buffaddr
#define luaL_buffaddr (bf) ((bf)->b)
Definition at line 196 of file lua-5.4.3/src/lauxlib.h.
Referenced by searchpath().
luaL_bufflen
#define luaL_bufflen (bf) ((bf)->n)
Definition at line 195 of file lua-5.4.3/src/lauxlib.h.
Referenced by searchpath().
luaL_buffsub
#define luaL_buffsub (B, s) ((B)->n -= (s))
Definition at line 205 of file lua-5.4.3/src/lauxlib.h.
Referenced by findloader().
luaL_checkstring
#define luaL_checkstring (L, n) (luaL_checklstring(L, (n), NULL))
Definition at line 139 of file lua-5.4.3/src/lauxlib.h.
luaL_checkversion
#define luaL_checkversion (L) luaL_checkversion_(L, LUA_VERSION_NUM, LUAL_NUMSIZES)
Definition at line 47 of file lua-5.4.3/src/lauxlib.h.
#define luaL_checkversion(L)  \
      luaL_checkversion_(L, LUA_VERSION_NUM, LUAL_NUMSIZES)
luaL_dofile
#define luaL_dofile (L, fn) (luaL_loadfile(L, fn) || lua_pcall(L, 0, LUA_MULTRET, 0))
Definition at line 144 of file lua-5.4.3/src/lauxlib.h.
#define luaL_dofile(L, fn) \
    (luaL_loadfile(L, fn) || lua_pcall(L, 0, LUA_MULTRET, 0))
luaL_dostring
#define luaL_dostring (L, s) (luaL_loadstring(L, s) || lua_pcall(L, 0, LUA_MULTRET, 0))
Definition at line 147 of file lua-5.4.3/src/lauxlib.h.
#define luaL_dostring(L, s) \
    (luaL_loadstring(L, s) || lua_pcall(L, 0, LUA_MULTRET, 0))
luaL_getmetatable
#define luaL_getmetatable (L, n) (lua_getfield(L, LUA_REGISTRYINDEX, (n)))
Definition at line 150 of file lua-5.4.3/src/lauxlib.h.
luaL_loadbuffer
#define luaL_loadbuffer (L, s, sz, n) luaL_loadbufferx(L,s,sz,n,NULL)
Definition at line 154 of file lua-5.4.3/src/lauxlib.h.
luaL_loadfile
#define luaL_loadfile (L, f) luaL_loadfilex(L,f,NULL)
Definition at line 95 of file lua-5.4.3/src/lauxlib.h.
luaL_newlib
#define luaL_newlib (L, l) (luaL_checkversion(L), luaL_newlibtable(L,l), luaL_setfuncs(L,l,0))
Definition at line 130 of file lua-5.4.3/src/lauxlib.h.
#define luaL_newlib(L,l)  \
  (luaL_checkversion(L), luaL_newlibtable(L,l), luaL_setfuncs(L,l,0))
luaL_newlibtable
#define luaL_newlibtable (L, l) lua_createtable(L, 0, sizeof(l)/sizeof((l)[0]) - 1)
Definition at line 127 of file lua-5.4.3/src/lauxlib.h.
#define luaL_newlibtable(L,l)   \
  lua_createtable(L, 0, sizeof(l)/sizeof((l)[0]) - 1)
LUAL_NUMSIZES
#define LUAL_NUMSIZES (sizeof(lua_Integer)*16 + sizeof(lua_Number))
Definition at line 44 of file lua-5.4.3/src/lauxlib.h.
luaL_opt
#define luaL_opt (L, f, n, d) (lua_isnoneornil(L,(n)) ? (d) : f(L,(n)))
Definition at line 152 of file lua-5.4.3/src/lauxlib.h.
luaL_optstring
#define luaL_optstring (L, n, d) (luaL_optlstring(L, (n), (d), NULL))
Definition at line 140 of file lua-5.4.3/src/lauxlib.h.
luaL_prepbuffer
#define luaL_prepbuffer (B) luaL_prepbuffsize(B, LUAL_BUFFERSIZE)
Definition at line 216 of file lua-5.4.3/src/lauxlib.h.
luaL_pushfail
#define luaL_pushfail (L) lua_pushnil(L)
Definition at line 158 of file lua-5.4.3/src/lauxlib.h.
Referenced by byteoffset(), db_gethook(), db_getinfo(), db_getlocal(), db_getuservalue(), db_setuservalue(), db_upvalueid(), g_read(), io_noclose(), io_type(), ll_loadlib(), ll_searchpath(), load_aux(), luaB_tonumber(), luaL_execresult(), luaL_fileresult(), math_toint(), math_type(), str_find_aux(), and utflen().
luaL_typename
#define luaL_typename (L, i) lua_typename(L, lua_type(L,(i)))
Definition at line 142 of file lua-5.4.3/src/lauxlib.h.
Typedef Documentation
luaL_Buffer
typedef struct luaL_Buffer luaL_Buffer
Definition at line 23 of file lua-5.4.3/src/lauxlib.h.
luaL_Reg
typedef struct luaL_Reg luaL_Reg
luaL_Stream
typedef struct luaL_Stream luaL_Stream
Function Documentation
luaL_addgsub()
LUALIB_API void luaL_addgsub (luaL_Buffer * b, const char * s, const char * p, const char * r)
Definition at line 987 of file lua-5.4.3/src/lauxlib.c.
{
  const char *wild;
  size_t l = strlen(p);
  while ((wild = strstr(s, p)) != NULL) {
    luaL_addlstring(b, s, wild - s);  /* push prefix */
    luaL_addstring(b, r);  /* push replacement in place of pattern */
    s = wild + l;  /* continue after 'p' */
  }
  luaL_addstring(b, s);  /* push last suffix */
}
References luaL_addlstring(), luaL_addstring(), NULL, and s.
Referenced by luaL_gsub(), pusherrornotfound(), and searchpath().
luaL_addlstring()
LUALIB_API void luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 436 of file lua-5.1.5/src/lauxlib.c.
{
  while (l--)
    luaL_addchar(B, *s++);
}
References luaL_addchar, luaL_addsize, luaL_prepbuffsize(), prepbuffsize(), and s.
Referenced by add_s(), add_s(), add_s(), add_s(), add_value(), addquoted(), b_pack(), luaL_addgsub(), luaL_addstring(), luaL_addvalue(), luaL_gsub(), os_date(), os_date(), putinteger(), setpath(), str_format(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), str_pack(), str_pack(), str_rep(), tconcat(), tconcat(), tconcat(), tconcat(), writer(), writer(), writer(), writer(), Xml_pushEncode(), and Xml_str().
luaL_addstring()
LUALIB_API void luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 442 of file lua-5.1.5/src/lauxlib.c.
{
  luaL_addlstring(B, s, strlen(s));
}
References luaL_addlstring(), and s.
Referenced by addquoted(), addquoted(), addquoted(), findloader(), luaL_addgsub(), luaL_gsub(), luaL_traceback(), pusherrornotfound(), setpath(), and Xml_str().
luaL_addvalue()
LUALIB_API void luaL_addvalue (luaL_Buffer * B)
Definition at line 454 of file lua-5.1.5/src/lauxlib.c.
{
  lua_State *L = B->L;
  size_t vl;
  const char *s = lua_tolstring(L, -1, &vl);
  if (vl <= bufffree(B)) {  /* fit into buffer? */
    memcpy(B->p, s, vl);  /* put it there */
    B->p += vl;
    lua_pop(L, 1);  /* remove from stack */
  }
  else {
    if (emptybuffer(B))
      lua_insert(L, -2);  /* put buffer before new value */
    B->lvl++;  /* add new value into B stack */
    adjuststack(B);
  }
}
References adjuststack(), bufffree, buffonstack, emptybuffer(), luaL_Buffer::L, lua_insert, lua_pop, lua_remove, lua_tolstring(), luaL_addlstring(), luaL_addsize, luaL_Buffer::lvl, luaL_Buffer::p, prepbuffsize(), and s.
Referenced by add_s(), add_s(), add_s(), add_s(), add_value(), add_value(), add_value(), add_value(), addfield(), addfield(), addfield(), addfield(), addliteral(), addliteral(), findloader(), findloader(), findloader(), luaL_traceback(), searchpath(), searchpath(), str_format(), str_format(), str_format(), str_format(), utfchar(), utfchar(), and Xml_str().
luaL_argerror()
LUALIB_API int luaL_argerror (lua_State * L, int arg, const char * extramsg)
Definition at line 43 of file lua-5.1.5/src/lauxlib.c.
{
  lua_Debug ar;
  if (!lua_getstack(L, 0, &ar))  /* no stack frame? */
    return luaL_error(L, "bad argument #%d (%s)", narg, extramsg);
  lua_getinfo(L, "n", &ar);
  if (strcmp(ar.namewhat, "method") == 0) {
    narg--;  /* do not count `self' */
    if (narg == 0)  /* error is in the self argument itself? */
      return luaL_error(L, "calling " LUA_QS " on bad self (%s)",
                           ar.name, extramsg);
  }
  if (ar.name == NULL)
    ar.name = "?";
  return luaL_error(L, "bad argument #%d to " LUA_QS " (%s)",
                        narg, ar.name, extramsg);
}
References arg, lua_getinfo(), lua_getstack(), LUA_QS, lua_tostring, luaL_error(), lua_Debug::name, lua_Debug::namewhat, NULL, pushglobalfuncname(), pushglobalfuncname(), and pushglobalfuncname().
Referenced by addliteral(), addliteral(), b_size(), checkoption(), checkoption(), checkoption(), controloptions(), db_getinfo(), db_getinfo(), db_getinfo(), db_getinfo(), db_getlocal(), db_getlocal(), db_getlocal(), db_getlocal(), db_setlocal(), db_setlocal(), db_setlocal(), db_setlocal(), db_setuservalue(), fileerror(), g_read(), g_read(), g_read(), g_read(), getdetails(), getdetails(), getfunc(), interror(), interror(), lsqlite_checkbu(), lsqlite_checkcontext(), lsqlite_checkdb(), lsqlite_checkvm(), lsqlite_getvm(), lsqlite_open_ptr(), luaL_checkany(), luaL_checkany(), luaL_checkoption(), luaL_checkoption(), luaL_typeerror(), luaL_typerror(), str_format(), str_format(), str_format(), str_format(), str_packsize(), str_unpack(), typeerror(), and typeerror().
luaL_buffinit()
LUALIB_API void luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 472 of file lua-5.1.5/src/lauxlib.c.
{
  B->L = L;
  B->p = B->buffer;
  B->lvl = 0;
}
References luaL_Buffer::b, luaL_Buffer::buffer, luaL_Buffer::init, luaL_Buffer::initb, luaL_Buffer::L, lua_pushlightuserdata(), LUAL_BUFFERSIZE, luaL_Buffer::lvl, luaL_Buffer::n, luaL_Buffer::p, and luaL_Buffer::size.
Referenced by b_pack(), findloader(), findloader(), findloader(), luaL_buffinitsize(), luaL_gsub(), luaL_traceback(), os_date(), os_date(), os_date(), os_date(), push_indentStr(), pusherrornotfound(), read_all(), read_all(), read_all(), read_chars(), read_chars(), read_chars(), read_chars(), read_line(), read_line(), read_line(), read_line(), searchpath(), searchpath(), searchpath(), setpath(), str_char(), str_dump(), str_dump(), str_dump(), str_format(), str_format(), str_format(), str_format(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), str_lower(), str_pack(), str_pack(), str_rep(), str_reverse(), str_upper(), tconcat(), tconcat(), tconcat(), tconcat(), utfchar(), utfchar(), writer(), Xml_pushEncode(), and Xml_str().
luaL_buffinitsize()
LUALIB_API char * luaL_buffinitsize (lua_State * L, luaL_Buffer * B, size_t sz)
Definition at line 504 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_buffinit(L, B);
  return luaL_prepbuffsize(B, sz);
}
References luaL_buffinit(), luaL_prepbuffsize(), and prepbuffsize().
Referenced by str_char(), str_char(), str_char(), str_lower(), str_lower(), str_lower(), str_rep(), str_rep(), str_rep(), str_reverse(), str_reverse(), str_reverse(), str_upper(), str_upper(), and str_upper().
luaL_callmeta()
LUALIB_API int luaL_callmeta (lua_State * L, int obj, const char * e)
Definition at line 219 of file lua-5.1.5/src/lauxlib.c.
{
  obj = abs_index(L, obj);
  if (!luaL_getmetafield(L, obj, event))  /* no metafield? */
    return 0;
  lua_pushvalue(L, obj);
  lua_call(L, 1, 1);
  return 1;
}
References abs_index, lua_absindex(), lua_call, lua_pushvalue(), LUA_TNIL, and luaL_getmetafield().
Referenced by luaB_tostring(), luaL_tolstring(), msghandler(), msghandler(), and traceback().
luaL_checkany()
LUALIB_API void luaL_checkany (lua_State * L, int arg)
Definition at line 152 of file lua-5.1.5/src/lauxlib.c.
{
  if (lua_type(L, narg) == LUA_TNONE)
    luaL_argerror(L, narg, "value expected");
}
References arg, LUA_TNONE, lua_type(), luaL_argerror(), and luaL_argerror().
Referenced by db_getfenv(), db_getmetatable(), db_getmetatable(), db_getmetatable(), db_getmetatable(), db_setlocal(), db_setlocal(), db_setlocal(), db_setlocal(), db_setupvalue(), db_setupvalue(), db_setupvalue(), db_setupvalue(), db_setuservalue(), db_setuservalue(), io_type(), io_type(), io_type(), io_type(), luaB_assert(), luaB_assert(), luaB_assert(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_ipairs(), luaB_ipairs(), luaB_pairs(), luaB_pcall(), luaB_pcall(), luaB_pcall(), luaB_pcall(), luaB_rawequal(), luaB_rawequal(), luaB_rawequal(), luaB_rawequal(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_tonumber(), luaB_tonumber(), luaB_tonumber(), luaB_tonumber(), luaB_tostring(), luaB_tostring(), luaB_tostring(), luaB_tostring(), luaB_type(), luaB_type(), luaB_xpcall(), math_toint(), math_toint(), math_type(), math_type(), and pairsmeta().
luaL_checkinteger()
LUALIB_API lua_Integer luaL_checkinteger (lua_State * L, int arg)
Definition at line 189 of file lua-5.1.5/src/lauxlib.c.
{
  lua_Integer d = lua_tointeger(L, narg);
  if (d == 0 && !lua_isnumber(L, narg))  /* avoid extra test when d is not 0 */
    tag_error(L, narg, LUA_TNUMBER);
  return d;
}
References arg, interror(), interror(), lua_isnumber(), LUA_TNUMBER, lua_tointeger, lua_tointegerx(), tag_error(), and tag_error().
Referenced by auxupvalue(), auxupvalue(), byteoffset(), byteoffset(), checkupval(), checkupval(), db_getinfo(), db_getinfo(), db_getlocal(), db_getlocal(), db_setcstacklimit(), db_setlocal(), db_setlocal(), g_read(), g_read(), ipairsaux(), ipairsaux(), l_checktime(), lcontext_result(), luaB_select(), luaB_select(), luaB_tonumber(), luaB_tonumber(), luaL_optinteger(), luaL_optinteger(), math_random(), math_random(), math_randomseed(), math_ult(), math_ult(), pushutfchar(), pushutfchar(), str_char(), str_char(), str_format(), str_format(), str_pack(), str_pack(), str_rep(), str_rep(), str_sub(), str_sub(), str_sub(), str_sub(), tinsert(), tinsert(), tmove(), tmove(), tunpack(), and unpack().
luaL_checklstring()
LUALIB_API const char * luaL_checklstring (lua_State * L, int arg, size_t * l)
Definition at line 158 of file lua-5.1.5/src/lauxlib.c.
{
  const char *s = lua_tolstring(L, narg, len);
  if (!s) tag_error(L, narg, LUA_TSTRING);
  return s;
}
References arg, lua_tolstring(), LUA_TSTRING, s, tag_error(), tag_error(), tag_error(), and tag_error().
Referenced by addquoted(), addquoted(), b_pack(), b_unpack(), byteoffset(), byteoffset(), codepoint(), codepoint(), g_write(), g_write(), g_write(), g_write(), gmatch(), gmatch(), iter_aux(), iter_aux(), lfs_lock_dir(), luaB_loadstring(), luaB_tonumber(), luaL_optlstring(), luaL_optlstring(), str_byte(), str_byte(), str_byte(), str_byte(), str_find_aux(), str_find_aux(), str_find_aux(), str_find_aux(), str_format(), str_format(), str_format(), str_format(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), str_len(), str_len(), str_len(), str_len(), str_lower(), str_lower(), str_lower(), str_lower(), str_pack(), str_pack(), str_rep(), str_rep(), str_rep(), str_rep(), str_reverse(), str_reverse(), str_reverse(), str_reverse(), str_sub(), str_sub(), str_sub(), str_sub(), str_unpack(), str_unpack(), str_upper(), str_upper(), str_upper(), str_upper(), utflen(), utflen(), Xml_decode(), and Xml_eval().
luaL_checknumber()
LUALIB_API lua_Number luaL_checknumber (lua_State * L, int arg)
Definition at line 176 of file lua-5.1.5/src/lauxlib.c.
{
  lua_Number d = lua_tonumber(L, narg);
  if (d == 0 && !lua_isnumber(L, narg))  /* avoid extra test when d is not 0 */
    tag_error(L, narg, LUA_TNUMBER);
  return d;
}
References arg, lua_isnumber(), LUA_TNUMBER, lua_tonumber, lua_tonumberx(), tag_error(), tag_error(), tag_error(), and tag_error().
Referenced by b_pack(), dbvm_bind_parameter_name(), dbvm_get_name(), dbvm_get_type(), lcontext_result(), lcontext_result_double(), luaL_optnumber(), luaL_optnumber(), math_abs(), math_abs(), math_abs(), math_abs(), math_acos(), math_acos(), math_acos(), math_acos(), math_asin(), math_asin(), math_asin(), math_asin(), math_atan(), math_atan(), math_atan(), math_atan(), math_atan2(), math_atan2(), math_ceil(), math_ceil(), math_ceil(), math_ceil(), math_cos(), math_cos(), math_cos(), math_cos(), math_cosh(), math_cosh(), math_deg(), math_deg(), math_deg(), math_deg(), math_exp(), math_exp(), math_exp(), math_exp(), math_floor(), math_floor(), math_floor(), math_floor(), math_fmod(), math_fmod(), math_fmod(), math_fmod(), math_frexp(), math_frexp(), math_ldexp(), math_ldexp(), math_log(), math_log(), math_log(), math_log(), math_log10(), math_max(), math_max(), math_min(), math_min(), math_modf(), math_modf(), math_modf(), math_modf(), math_pow(), math_pow(), math_rad(), math_rad(), math_rad(), math_rad(), math_random(), math_randomseed(), math_sin(), math_sin(), math_sin(), math_sin(), math_sinh(), math_sinh(), math_sqrt(), math_sqrt(), math_sqrt(), math_sqrt(), math_tan(), math_tan(), math_tan(), math_tan(), math_tanh(), math_tanh(), os_date(), os_date(), os_difftime(), os_difftime(), putinteger(), str_format(), str_format(), str_format(), str_format(), str_pack(), and str_pack().
luaL_checkoption()
LUALIB_API int luaL_checkoption (lua_State * L, int arg, const char * def, const char *const lst[])
Definition at line 99 of file lua-5.1.5/src/lauxlib.c.
{
  const char *name = (def) ? luaL_optstring(L, narg, def) :
                             luaL_checkstring(L, narg);
  int i;
  for (i=0; lst[i]; i++)
    if (strcmp(lst[i], name) == 0)
      return i;
  return luaL_argerror(L, narg,
                       lua_pushfstring(L, "invalid option " LUA_QS, name));
}
References arg, lua_pushfstring(), LUA_QS, luaL_argerror(), luaL_argerror(), luaL_checkstring, luaL_optstring, and name.
Referenced by f_seek(), f_seek(), f_seek(), f_seek(), f_setvbuf(), f_setvbuf(), f_setvbuf(), f_setvbuf(), lfs_g_setmode(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_collectgarbage(), os_setlocale(), os_setlocale(), os_setlocale(), and os_setlocale().
luaL_checkstack()
LUALIB_API void luaL_checkstack (lua_State * L, int sz, const char * msg)
Definition at line 140 of file lua-5.1.5/src/lauxlib.c.
{
  if (!lua_checkstack(L, space))
    luaL_error(L, "stack overflow (%s)", mes);
}
References lua_checkstack(), LUA_MINSTACK, and luaL_error().
Referenced by b_unpack(), codepoint(), codepoint(), dotty(), g_read(), g_read(), g_read(), g_read(), generic_reader(), generic_reader(), generic_reader(), generic_reader(), getargs(), getargs(), io_readline(), io_readline(), l_print(), l_print(), luaL_setfuncs(), luaL_traceback(), push_captures(), push_captures(), push_captures(), push_captures(), pushargs(), pushargs(), sort(), sort(), str_byte(), str_byte(), str_byte(), str_byte(), str_unpack(), and str_unpack().
luaL_checktype()
LUALIB_API void luaL_checktype (lua_State * L, int arg, int t)
Definition at line 146 of file lua-5.1.5/src/lauxlib.c.
{
  if (lua_type(L, narg) != t)
    tag_error(L, narg, t);
}
References arg, lua_type(), tag_error(), tag_error(), tag_error(), and tag_error().
Referenced by auxupvalue(), auxupvalue(), auxupvalue(), auxupvalue(), checktab(), checktab(), checkupval(), checkupval(), checkupval(), db_busy_handler(), db_commit_hook(), db_exec(), db_progress_handler(), db_register_function(), db_rollback_hook(), db_setfenv(), db_sethook(), db_sethook(), db_sethook(), db_sethook(), db_setuservalue(), db_setuservalue(), db_setuservalue(), db_trace(), db_update_hook(), dbvm_bind_names(), foreach(), foreachi(), ipairsaux(), ipairsaux(), ll_seeall(), lsqlite_open_ptr(), luaB_cocreate(), luaB_cocreate(), luaB_cocreate(), luaB_ipairs(), luaB_load(), luaB_load(), luaB_load(), luaB_load(), luaB_next(), luaB_next(), luaB_next(), luaB_next(), luaB_pairs(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawget(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_rawset(), luaB_setfenv(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_tonumber(), luaB_tonumber(), luaB_unpack(), luaB_xpcall(), luaB_xpcall(), maxn(), os_time(), os_time(), os_time(), os_time(), pairsmeta(), setn(), sort(), sort(), sort(), sort(), str_dump(), str_dump(), str_dump(), str_dump(), tconcat(), tconcat(), unpack(), and Xml_iterate().
luaL_checkudata()
LUALIB_API void * luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 124 of file lua-5.1.5/src/lauxlib.c.
{
  void *p = lua_touserdata(L, ud);
  if (p != NULL) {  /* value is a userdata? */
    if (lua_getmetatable(L, ud)) {  /* does it have a metatable? */
      lua_getfield(L, LUA_REGISTRYINDEX, tname);  /* get correct metatable */
      if (lua_rawequal(L, -1, -2)) {  /* does it have the correct mt? */
        lua_pop(L, 2);  /* remove both metatables */
        return p;
      }
    }
  }
  luaL_typerror(L, ud, tname);  /* else error */
  return NULL;  /* to avoid warnings */
}
References lua_getfield(), lua_getmetatable(), lua_pop, lua_rawequal(), LUA_REGISTRYINDEX, lua_touserdata(), luaL_argexpected, luaL_testudata(), luaL_typerror(), NULL, typeerror(), and typeerror().
Referenced by check_file(), dir_iter(), gctm(), lfs_unlock_dir(), lsqlite_getbu(), lsqlite_getcontext(), lsqlite_getdb(), and lsqlite_getvm().
luaL_checkversion_()
LUALIB_API void luaL_checkversion_ (lua_State * L, lua_Number ver, size_t sz)
Definition at line 1038 of file lua-5.3.6/src/lauxlib.c.
{
  const lua_Number *v = lua_version(L);
  if (sz != LUAL_NUMSIZES)  /* check numeric types */
    luaL_error(L, "core and library have incompatible numeric types");
  if (v != lua_version(NULL))
    luaL_error(L, "multiple Lua VMs detected");
  else if (*v != ver)
    luaL_error(L, "version mismatch: app. needs %f, Lua core provides %f",
                  (LUAI_UACNUMBER)ver, (LUAI_UACNUMBER)*v);
}
References lua_version(), LUAI_UACNUMBER, luaL_error(), LUAL_NUMSIZES, and NULL.
luaL_error()
LUALIB_API int luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 86 of file lua-5.1.5/src/lauxlib.c.
{
  va_list argp;
  va_start(argp, fmt);
  luaL_where(L, 1);
  lua_pushvfstring(L, fmt, argp);
  va_end(argp);
  lua_concat(L, 2);
  return lua_error(L);
}
References lua_concat(), lua_error(), lua_pushvfstring(), and luaL_where().
Referenced by _file_info_(), _file_lock(), add_s(), add_s(), add_s(), add_value(), add_value(), add_value(), add_value(), addfield(), addfield(), addfield(), addfield(), auxresume(), auxsort(), auxsort(), b_unpack(), byteoffset(), byteoffset(), capture_to_close(), capture_to_close(), capture_to_close(), capture_to_close(), check_capture(), check_capture(), check_capture(), check_capture(), check_file(), checkload(), checkload(), checkload(), checkstack(), checkstack(), checkstack(), classend(), classend(), classend(), classend(), codepoint(), codepoint(), controloptions(), db_create_collation(), db_register_function(), db_setfenv(), dbvm_bind_index(), dbvm_bind_values(), dbvm_check_bind_index(), dbvm_check_contents(), dbvm_check_index(), dir_iter_factory(), fieldargs(), findfile(), findfile(), findfile(), findfile(), findloader(), findloader(), findloader(), generic_reader(), generic_reader(), generic_reader(), generic_reader(), get_onecapture(), getfield(), getfield(), getfield(), getfield(), getfunc(), getiofile(), getiofile(), getiofile(), getiofile(), getnumlimit(), getnumlimit(), getoption(), getoption(), gfind_nodef(), io_readline(), io_readline(), io_readline(), io_readline(), iter_aux(), iter_aux(), lcontext_check_aggregate(), lcontext_result(), ll_module(), ll_require(), loader_preload(), loaderror(), lstop(), lstop(), lstop(), lstop(), luaB_assert(), luaB_assert(), luaB_close(), luaB_print(), luaB_print(), luaB_print(), luaB_setfenv(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_unpack(), luaI_openlib(), luaL_argerror(), luaL_argerror(), luaL_checkstack(), luaL_checkstack(), luaL_checkversion_(), luaL_checkversion_(), luaL_len(), luaL_prepbuffsize(), luaL_tolstring(), luaopen_bit32(), make_xml_object(), match(), match(), match(), match(), matchbalance(), matchbalance(), matchbalance(), matchbalance(), math_random(), math_random(), math_random(), math_random(), newbuffsize(), opencheck(), opencheck(), opencheck(), optsize(), os_date(), os_date(), os_time(), os_time(), os_tmpname(), os_tmpname(), os_tmpname(), os_tmpname(), partition(), partition(), push_onecapture(), push_onecapture(), push_onecapture(), pushargs(), pushargs(), resizebox(), scanformat(), scanformat(), scanformat(), scanformat(), setfenv(), setfield(), setn(), start_capture(), start_capture(), start_capture(), start_capture(), str_byte(), str_byte(), str_byte(), str_byte(), str_dump(), str_dump(), str_dump(), str_dump(), str_format(), str_format(), str_format(), str_format(), str_rep(), str_rep(), str_rep(), tinsert(), tinsert(), tinsert(), tinsert(), tofile(), tofile(), tofile(), tofile(), trymt(), tunpack(), unpack(), unpack(), unpackint(), unpackint(), Xml_eval(), and Xml_load().
luaL_execresult()
LUALIB_API int luaL_execresult (lua_State * L, int stat)
Definition at line 247 of file lua-5.2.4/src/lauxlib.c.
{
  const char *what = "exit";  /* type of termination */
  if (stat == -1)  /* error? */
    return luaL_fileresult(L, 0, NULL);
  else {
    inspectstat(stat, what);  /* interpret result */
    if (*what == 'e' && stat == 0)  /* successful termination? */
      lua_pushboolean(L, 1);
    else
      lua_pushnil(L);
    lua_pushstring(L, what);
    lua_pushinteger(L, stat);
    return 3;  /* return true/nil,what,code */
  }
}
References inspectstat, l_inspectstat, lua_pushboolean(), lua_pushinteger(), lua_pushnil(), lua_pushstring(), luaL_fileresult(), luaL_pushfail, and NULL.
Referenced by io_pclose(), io_pclose(), io_pclose(), os_execute(), os_execute(), and os_execute().
luaL_fileresult()
LUALIB_API int luaL_fileresult (lua_State * L, int stat, const char * fname)
Definition at line 207 of file lua-5.2.4/src/lauxlib.c.
{
  int en = errno;  /* calls to Lua API may change this value */
  if (stat) {
    lua_pushboolean(L, 1);
    return 1;
  }
  else {
    lua_pushnil(L);
    if (fname)
      lua_pushfstring(L, "%s: %s", fname, strerror(en));
    else
      lua_pushstring(L, strerror(en));
    lua_pushinteger(L, en);
    return 3;
  }
}
References lua_pushboolean(), lua_pushfstring(), lua_pushinteger(), lua_pushnil(), lua_pushstring(), and luaL_pushfail.
Referenced by f_flush(), f_flush(), f_flush(), f_seek(), f_seek(), f_seek(), f_setvbuf(), f_setvbuf(), f_setvbuf(), g_read(), g_read(), g_read(), g_write(), g_write(), g_write(), io_fclose(), io_fclose(), io_fclose(), io_flush(), io_flush(), io_flush(), io_open(), io_open(), io_open(), io_popen(), io_popen(), io_popen(), io_tmpfile(), io_tmpfile(), io_tmpfile(), luaL_execresult(), os_remove(), os_remove(), os_remove(), os_rename(), os_rename(), and os_rename().
luaL_getmetafield()
LUALIB_API int luaL_getmetafield (lua_State * L, int obj, const char * e)
Definition at line 203 of file lua-5.1.5/src/lauxlib.c.
{
  if (!lua_getmetatable(L, obj))  /* no metatable? */
    return 0;
  lua_pushstring(L, event);
  lua_rawget(L, -2);
  if (lua_isnil(L, -1)) {
    lua_pop(L, 2);  /* remove metatable and metafield */
    return 0;
  }
  else {
    lua_remove(L, -2);  /* remove only metatable */
    return 1;
  }
}
References lua_getmetatable(), lua_isnil, lua_pop, lua_pushstring(), lua_rawget(), lua_remove, and LUA_TNIL.
Referenced by luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_getmetatable(), luaB_pairs(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaB_setmetatable(), luaL_callmeta(), luaL_tolstring(), luaL_typeerror(), pairsmeta(), pairsmeta(), trymt(), and typeerror().
luaL_getsubtable()
LUALIB_API int luaL_getsubtable (lua_State * L, int idx, const char * fname)
Definition at line 866 of file lua-5.2.4/src/lauxlib.c.
{
  lua_getfield(L, idx, fname);
  if (lua_istable(L, -1)) return 1;  /* table already there */
  else {
    lua_pop(L, 1);  /* remove previous result */
    idx = lua_absindex(L, idx);
    lua_newtable(L);
    lua_pushvalue(L, -1);  /* copy to be left at top */
    lua_setfield(L, idx, fname);  /* assign new table to field */
    return 0;  /* false, because did not find table there */
  }
}
References lua_absindex(), lua_getfield(), lua_istable, lua_newtable, lua_pop, lua_pushvalue(), lua_setfield(), and LUA_TTABLE.
Referenced by createclibstable(), db_sethook(), luaL_openlibs(), luaL_requiref(), and luaopen_package().
luaL_gsub()
LUALIB_API const char * luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 340 of file lua-5.1.5/src/lauxlib.c.
{
  const char *wild;
  size_t l = strlen(p);
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  while ((wild = strstr(s, p)) != NULL) {
    luaL_addlstring(&b, s, wild - s);  /* push prefix */
    luaL_addstring(&b, r);  /* push replacement in place of pattern */
    s = wild + l;  /* continue after `p' */
  }
  luaL_addstring(&b, s);  /* push last suffix */
  luaL_pushresult(&b);
  return lua_tostring(L, -1);
}
References lua_tostring, luaL_addgsub(), luaL_addlstring(), luaL_addstring(), luaL_buffinit(), luaL_pushresult(), NULL, and s.
Referenced by do_gsub(), findfile(), loadfunc(), loadfunc(), loadfunc(), mkfuncname(), searchpath(), searchpath(), searchpath(), setpath(), setpath(), and setpath().
luaL_len()
LUALIB_API lua_Integer luaL_len (lua_State * L, int idx)
Definition at line 725 of file lua-5.2.4/src/lauxlib.c.
{
  int l;
  int isnum;
  lua_len(L, idx);
  l = (int)lua_tointegerx(L, -1, &isnum);
  if (!isnum)
    luaL_error(L, "object length is not a number");
  lua_pop(L, 1);  /* remove object */
  return l;
}
References lua_len(), lua_pop, lua_tointegerx(), and luaL_error().
Referenced by addtoclib(), addtoclib(), gctm(), gctm(), gctm(), ll_addtoclib(), pushargs(), pushargs(), tconcat(), tunpack(), unpack(), and unpack().
luaL_loadbufferx()
LUALIB_API int luaL_loadbufferx (lua_State * L, const char * buff, size_t sz, const char * name, const char * mode)
Definition at line 682 of file lua-5.2.4/src/lauxlib.c.
{
  LoadS ls;
  ls.s = buff;
  ls.size = size;
  return lua_load(L, getS, &ls, name, mode);
}
References getS(), getS(), getS(), lua_load(), name, LoadS::s, and LoadS::size.
Referenced by luaB_load(), luaB_load(), and luaB_load().
luaL_loadfilex()
LUALIB_API int luaL_loadfilex (lua_State * L, const char * filename, const char * mode)
Definition at line 630 of file lua-5.2.4/src/lauxlib.c.
{
  LoadF lf;
  int status, readstatus;
  int c;
  int fnameindex = lua_gettop(L) + 1;  /* index of filename on the stack */
  if (filename == NULL) {
    lua_pushliteral(L, "=stdin");
    lf.f = stdin;
  }
  else {
    lua_pushfstring(L, "@%s", filename);
    lf.f = fopen(filename, "r");
    if (lf.f == NULL) return errfile(L, "open", fnameindex);
  }
  if (skipcomment(&lf, &c))  /* read initial portion */
    lf.buff[lf.n++] = '\n';  /* add line to correct line numbers */
  if (c == LUA_SIGNATURE[0] && filename) {  /* binary file? */
    lf.f = freopen(filename, "rb", lf.f);  /* reopen in binary mode */
    if (lf.f == NULL) return errfile(L, "reopen", fnameindex);
    skipcomment(&lf, &c);  /* re-read initial portion */
  }
  if (c != EOF)
    lf.buff[lf.n++] = c;  /* 'c' is the first character of the stream */
  status = lua_load(L, getF, &lf, lua_tostring(L, -1), mode);
  readstatus = ferror(lf.f);
  if (filename) fclose(lf.f);  /* close file (even in case of errors) */
  if (readstatus) {
    lua_settop(L, fnameindex);  /* ignore results from `lua_load' */
    return errfile(L, "read", fnameindex);
  }
  lua_remove(L, fnameindex);
  return status;
}
References LoadF::buff, errfile(), errfile(), errfile(), LoadF::f, getF(), getF(), getF(), lua_gettop(), lua_load(), lua_pushfstring(), lua_pushliteral, lua_remove, lua_settop(), LUA_SIGNATURE, lua_tostring, LoadF::n, NULL, skipcomment(), skipcomment(), and skipcomment().
Referenced by luaB_loadfile(), luaB_loadfile(), and luaB_loadfile().
luaL_loadstring()
LUALIB_API int luaL_loadstring (lua_State * L, const char * s)
Definition at line 618 of file lua-5.1.5/src/lauxlib.c.
{
  return luaL_loadbuffer(L, s, strlen(s), s);
}
References luaL_loadbuffer, and s.
luaL_newmetatable()
LUALIB_API int luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 112 of file lua-5.1.5/src/lauxlib.c.
{
  lua_getfield(L, LUA_REGISTRYINDEX, tname);  /* get registry.name */
  if (!lua_isnil(L, -1))  /* name already in use? */
    return 0;  /* leave previous value on top, but return 0 */
  lua_pop(L, 1);
  lua_newtable(L);  /* create metatable */
  lua_pushvalue(L, -1);
  lua_setfield(L, LUA_REGISTRYINDEX, tname);  /* registry.name = metatable */
  return 1;
}
References lua_createtable(), lua_getfield(), lua_isnil, lua_newtable, lua_pop, lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), LUA_TNIL, and luaL_getmetatable.
Referenced by create_meta(), createmeta(), createmeta(), createmeta(), createmeta(), dir_create_meta(), lock_create_meta(), luaopen_LuaXML_lib(), luaopen_package(), newbox(), and newbox().
luaL_newstate()
LUALIB_API lua_State * luaL_newstate (void)
Definition at line 647 of file lua-5.1.5/src/lauxlib.c.
{
  lua_State *L = lua_newstate(l_alloc, NULL);
  if (L) lua_atpanic(L, &panic);
  return L;
}
References l_alloc(), l_alloc(), l_alloc(), l_alloc(), lua_atpanic(), lua_newstate(), lua_setwarnf(), NULL, panic(), panic(), panic(), panic(), and warnfoff().
Referenced by main(), and main().
luaL_optinteger()
LUALIB_API lua_Integer luaL_optinteger (lua_State * L, int arg, lua_Integer def)
Definition at line 197 of file lua-5.1.5/src/lauxlib.c.
{
  return luaL_opt(L, luaL_checkinteger, narg, def);
}
References arg, luaL_checkinteger(), luaL_checkinteger(), and luaL_opt.
Referenced by b_unpack(), byteoffset(), byteoffset(), codepoint(), codepoint(), db_getuservalue(), db_sethook(), db_sethook(), db_setuservalue(), db_traceback(), db_traceback(), f_seek(), f_seek(), f_setvbuf(), f_setvbuf(), f_setvbuf(), f_setvbuf(), file_lock(), file_unlock(), file_utime(), getendpos(), gmatch(), lsqlite_open(), luaB_collectgarbage(), luaB_collectgarbage(), luaB_error(), luaB_error(), math_randomseed(), os_exit(), os_exit(), str_byte(), str_byte(), str_byte(), str_byte(), str_find_aux(), str_find_aux(), str_find_aux(), str_find_aux(), str_gsub(), str_gsub(), str_gsub(), str_sub(), str_sub(), str_sub(), str_unpack(), str_unpack(), tconcat(), tconcat(), tremove(), tremove(), tunpack(), unpack(), utflen(), and utflen().
luaL_optlstring()
LUALIB_API const char * luaL_optlstring (lua_State * L, int arg, const char * def, size_t * l)
Definition at line 165 of file lua-5.1.5/src/lauxlib.c.
{
  if (lua_isnoneornil(L, narg)) {
    if (len)
      *len = (def ? strlen(def) : 0);
    return def;
  }
  else return luaL_checklstring(L, narg, len);
}
References arg, lua_isnoneornil, luaL_checklstring(), and luaL_checklstring().
Referenced by os_date(), os_date(), str_rep(), str_rep(), str_rep(), tconcat(), tconcat(), tconcat(), and tconcat().
luaL_optnumber()
LUALIB_API lua_Number luaL_optnumber (lua_State * L, int arg, lua_Number def)
Definition at line 184 of file lua-5.1.5/src/lauxlib.c.
{
  return luaL_opt(L, luaL_checknumber, narg, def);
}
References arg, luaL_checknumber(), luaL_checknumber(), and luaL_opt.
Referenced by f_seek(), file_utime(), math_atan(), math_atan(), os_difftime(), and os_difftime().
luaL_prepbuffsize()
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer * B, size_t sz)
Definition at line 437 of file lua-5.2.4/src/lauxlib.c.
{
  lua_State *L = B->L;
  if (B->size - B->n < sz) {  /* not enough space? */
    char *newbuff;
    size_t newsize = B->size * 2;  /* double buffer size */
    if (newsize - B->n < sz)  /* not big enough? */
      newsize = B->n + sz;
    if (newsize < B->n || newsize - B->n < sz)
      luaL_error(L, "buffer too large");
    /* create larger buffer */
    newbuff = (char *)lua_newuserdata(L, newsize * sizeof(char));
    /* move content to new buffer */
    memcpy(newbuff, B->b, B->n * sizeof(char));
    if (buffonstack(B))
      lua_remove(L, -2);  /* remove old buffer */
    B->b = newbuff;
    B->size = newsize;
  }
  return &B->b[B->n];
}
References luaL_Buffer::b, buffonstack, luaL_Buffer::L, lua_newuserdata, lua_remove, luaL_error(), luaL_Buffer::n, newbox(), prepbuffsize(), resizebox(), and luaL_Buffer::size.
Referenced by addliteral(), addliteral(), luaL_addlstring(), luaL_buffinitsize(), os_date(), os_date(), packint(), packint(), read_all(), read_chars(), read_chars(), read_chars(), str_format(), str_format(), str_format(), str_pack(), and str_pack().
luaL_pushresult()
LUALIB_API void luaL_pushresult (luaL_Buffer * B)
Definition at line 447 of file lua-5.1.5/src/lauxlib.c.
{
  emptybuffer(B);
  lua_concat(B->L, B->lvl);
  B->lvl = 1;
}
References luaL_Buffer::b, buffonstack, checkbufferlevel, emptybuffer(), luaL_Buffer::L, lua_closeslot(), lua_concat(), lua_pushlstring(), lua_remove, luaL_Buffer::lvl, luaL_Buffer::n, and resizebox().
Referenced by b_pack(), findloader(), findloader(), findloader(), luaL_gsub(), luaL_pushresultsize(), luaL_traceback(), os_date(), os_date(), os_date(), os_date(), push_indentStr(), pusherrornotfound(), read_all(), read_all(), read_all(), read_chars(), read_chars(), read_chars(), read_chars(), read_line(), read_line(), read_line(), read_line(), searchpath(), searchpath(), searchpath(), setpath(), str_char(), str_dump(), str_dump(), str_dump(), str_dump(), str_format(), str_format(), str_format(), str_format(), str_gsub(), str_gsub(), str_gsub(), str_gsub(), str_lower(), str_pack(), str_pack(), str_rep(), str_reverse(), str_upper(), tconcat(), tconcat(), tconcat(), tconcat(), utfchar(), utfchar(), Xml_pushEncode(), and Xml_str().
luaL_pushresultsize()
LUALIB_API void luaL_pushresultsize (luaL_Buffer * B, size_t sz)
Definition at line 479 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_addsize(B, sz);
  luaL_pushresult(B);
}
References luaL_addsize, and luaL_pushresult().
Referenced by str_char(), str_char(), str_char(), str_lower(), str_lower(), str_lower(), str_rep(), str_rep(), str_rep(), str_reverse(), str_reverse(), str_reverse(), str_upper(), str_upper(), and str_upper().
luaL_ref()
LUALIB_API int luaL_ref (lua_State * L, int t)
Definition at line 481 of file lua-5.1.5/src/lauxlib.c.
{
  int ref;
  t = abs_index(L, t);
  if (lua_isnil(L, -1)) {
    lua_pop(L, 1);  /* remove from stack */
    return LUA_REFNIL;  /* `nil' has a unique fixed reference */
  }
  lua_rawgeti(L, t, FREELIST_REF);  /* get first free element */
  ref = (int)lua_tointeger(L, -1);  /* ref = t[FREELIST_REF] */
  lua_pop(L, 1);  /* remove it from stack */
  if (ref != 0) {  /* any free element? */
    lua_rawgeti(L, t, ref);  /* remove it from list */
    lua_rawseti(L, t, FREELIST_REF);  /* (t[FREELIST_REF] = t[ref]) */
  }
  else {  /* no free elements */
    ref = (int)lua_objlen(L, t);
    ref++;  /* create new reference */
  }
  lua_rawseti(L, t, ref);
  return ref;
}
References abs_index, freelist, FREELIST_REF, lua_absindex(), lua_assert, lua_isinteger(), lua_isnil, lua_objlen(), lua_pop, lua_pushinteger(), lua_rawgeti(), lua_rawlen, lua_rawseti(), LUA_REFNIL, LUA_TNIL, and lua_tointeger.
Referenced by db_busy_handler(), db_commit_hook(), db_create_collation(), db_progress_handler(), db_register_function(), db_rollback_hook(), db_trace(), db_update_hook(), lcontext_set_aggregate_context(), luaopen_lsqlite3(), and luaopen_LuaXML_lib().
luaL_requiref()
LUALIB_API void luaL_requiref (lua_State * L, const char * modname, lua_CFunction openf, int glb)
Definition at line 886 of file lua-5.2.4/src/lauxlib.c.
{
  lua_pushcfunction(L, openf);
  lua_pushstring(L, modname);  /* argument to open function */
  lua_call(L, 1, 1);  /* open module */
  luaL_getsubtable(L, LUA_REGISTRYINDEX, "_LOADED");
  lua_pushvalue(L, -2);  /* make copy of module (call result) */
  lua_setfield(L, -2, modname);  /* _LOADED[modname] = module */
  lua_pop(L, 1);  /* remove _LOADED table */
  if (glb) {
    lua_pushvalue(L, -1);  /* copy of 'mod' */
    lua_setglobal(L, modname);  /* _G[modname] = module */
  }
}
References lua_call, lua_getfield(), LUA_LOADED_TABLE, lua_pop, lua_pushcfunction, lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_remove, lua_setfield(), lua_setglobal, lua_toboolean(), and luaL_getsubtable().
Referenced by luaL_openlibs(), and luaopen_lsqlite3().
luaL_setfuncs()
LUALIB_API void luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 848 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_checkversion(L);
  luaL_checkstack(L, nup, "too many upvalues");
  for (; l->name != NULL; l++) {  /* fill the table with given functions */
    int i;
    for (i = 0; i < nup; i++)  /* copy upvalues to the top */
      lua_pushvalue(L, -nup);
    lua_pushcclosure(L, l->func, nup);  /* closure with those upvalues */
    lua_setfield(L, -(nup + 2), l->name);
  }
  lua_pop(L, nup);  /* remove upvalues */
}
References luaL_Reg::func, lua_pop, lua_pushboolean(), lua_pushcclosure(), lua_pushvalue(), lua_setfield(), luaL_checkstack(), luaL_checkversion, luaL_Reg::name, and NULL.
Referenced by createmeta(), createmeta(), createmeta(), createmetatable(), luaopen_base(), luaopen_package(), luaopen_sqlitelib(), newbox(), and setrandfunc().
luaL_setmetatable()
LUALIB_API void luaL_setmetatable (lua_State * L, const char * tname)
Definition at line 284 of file lua-5.2.4/src/lauxlib.c.
{
  luaL_getmetatable(L, tname);
  lua_setmetatable(L, -2);
}
References lua_setmetatable(), and luaL_getmetatable.
Referenced by newprefile(), newprefile(), and newprefile().
luaL_testudata()
LUALIB_API void * luaL_testudata (lua_State * L, int ud, const char * tname)
Definition at line 290 of file lua-5.2.4/src/lauxlib.c.
{
  void *p = lua_touserdata(L, ud);
  if (p != NULL) {  /* value is a userdata? */
    if (lua_getmetatable(L, ud)) {  /* does it have a metatable? */
      luaL_getmetatable(L, tname);  /* get correct metatable */
      if (!lua_rawequal(L, -1, -2))  /* not the same? */
        p = NULL;  /* value is a userdata with wrong metatable */
      lua_pop(L, 2);  /* remove both metatables */
      return p;
    }
  }
  return NULL;  /* value is not a userdata with a metatable */
}
References lua_getmetatable(), lua_pop, lua_rawequal(), lua_touserdata(), luaL_getmetatable, and NULL.
Referenced by io_type(), io_type(), io_type(), and luaL_checkudata().
luaL_tolstring()
LUALIB_API const char * luaL_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 737 of file lua-5.2.4/src/lauxlib.c.
{
  if (!luaL_callmeta(L, idx, "__tostring")) {  /* no metafield? */
    switch (lua_type(L, idx)) {
      case LUA_TNUMBER:
      case LUA_TSTRING:
        lua_pushvalue(L, idx);
        break;
      case LUA_TBOOLEAN:
        lua_pushstring(L, (lua_toboolean(L, idx) ? "true" : "false"));
        break;
      case LUA_TNIL:
        lua_pushliteral(L, "nil");
        break;
      default:
        lua_pushfstring(L, "%s: %p", luaL_typename(L, idx),
                                            lua_topointer(L, idx));
        break;
    }
  }
  return lua_tolstring(L, -1, len);
}
References lua_isinteger(), lua_isstring(), lua_pushfstring(), lua_pushliteral, lua_pushstring(), lua_pushvalue(), lua_remove, LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, lua_toboolean(), lua_tointeger, lua_tolstring(), lua_tonumber, lua_topointer(), lua_tostring, LUA_TSTRING, lua_type(), LUAI_UACINT, LUAI_UACNUMBER, luaL_callmeta(), luaL_error(), luaL_getmetafield(), and luaL_typename.
Referenced by add_s(), addliteral(), addliteral(), db_debug(), get_prompt(), luaB_print(), luaB_tostring(), luaB_tostring(), luaB_tostring(), str_format(), str_format(), and str_format().
luaL_traceback()
LUALIB_API void luaL_traceback (lua_State * L, lua_State * L1, const char * msg, int level)
Definition at line 116 of file lua-5.2.4/src/lauxlib.c.
{
  lua_Debug ar;
  int top = lua_gettop(L);
  int numlevels = countlevels(L1);
  int mark = (numlevels > LEVELS1 + LEVELS2) ? LEVELS1 : 0;
  if (msg) lua_pushfstring(L, "%s\n", msg);
  lua_pushliteral(L, "stack traceback:");
  while (lua_getstack(L1, level++, &ar)) {
    if (level == mark) {  /* too many levels? */
      lua_pushliteral(L, "\n\t...");  /* add a '...' */
      level = numlevels - LEVELS2;  /* and skip to last ones */
    }
    else {
      lua_getinfo(L1, "Slnt", &ar);
      lua_pushfstring(L, "\n\t%s:", ar.short_src);
      if (ar.currentline > 0)
        lua_pushfstring(L, "%d:", ar.currentline);
      lua_pushliteral(L, " in ");
      pushfuncname(L, &ar);
      if (ar.istailcall)
        lua_pushliteral(L, "\n\t(...tail calls...)");
      lua_concat(L, lua_gettop(L) - top);
    }
  }
  lua_concat(L, lua_gettop(L) - top);
}
References countlevels(), lua_Debug::currentline, lua_Debug::istailcall, lastlevel(), lastlevel(), LEVELS1, LEVELS2, lua_concat(), lua_getinfo(), lua_getstack(), lua_gettop(), lua_pushfstring(), lua_pushliteral, luaL_addchar, luaL_addstring(), luaL_addvalue(), luaL_buffinit(), luaL_checkstack(), luaL_pushresult(), NULL, pushfuncname(), pushfuncname(), pushfuncname(), and lua_Debug::short_src.
Referenced by db_traceback(), db_traceback(), db_traceback(), msghandler(), msghandler(), and traceback().
luaL_typeerror()
LUALIB_API int luaL_typeerror (lua_State * L, int arg, const char * tname)
Definition at line 193 of file lua-5.4.3/src/lauxlib.c.
{
  const char *msg;
  const char *typearg;  /* name for the type of the actual argument */
  if (luaL_getmetafield(L, arg, "__name") == LUA_TSTRING)
    typearg = lua_tostring(L, -1);  /* use the given type name */
  else if (lua_type(L, arg) == LUA_TLIGHTUSERDATA)
    typearg = "light userdata";  /* special name for messages */
  else
    typearg = luaL_typename(L, arg);  /* standard name */
  msg = lua_pushfstring(L, "%s expected, got %s", tname, typearg);
  return luaL_argerror(L, arg, msg);
}
References arg, lua_pushfstring(), LUA_TLIGHTUSERDATA, lua_tostring, LUA_TSTRING, lua_type(), luaL_argerror(), luaL_getmetafield(), and luaL_typename.
Referenced by tag_error().
luaL_unref()
LUALIB_API void luaL_unref (lua_State * L, int t, int ref)
Definition at line 504 of file lua-5.1.5/src/lauxlib.c.
{
  if (ref >= 0) {
    t = abs_index(L, t);
    lua_rawgeti(L, t, FREELIST_REF);
    lua_rawseti(L, t, ref);  /* t[ref] = t[FREELIST_REF] */
    lua_pushinteger(L, ref);
    lua_rawseti(L, t, FREELIST_REF);  /* t[FREELIST_REF] = ref */
  }
}
References abs_index, freelist, FREELIST_REF, lua_absindex(), lua_assert, lua_isinteger(), lua_pushinteger(), lua_rawgeti(), and lua_rawseti().
Referenced by cleanupdb(), collfree(), db_busy_handler(), db_busy_timeout(), db_commit_hook(), db_progress_handler(), db_rollback_hook(), db_sql_finalize_function(), db_sql_normal_function(), db_trace(), db_update_hook(), and lcontext_set_aggregate_context().
luaL_where()
LUALIB_API void luaL_where (lua_State * L, int lvl)
Definition at line 73 of file lua-5.1.5/src/lauxlib.c.
{
  lua_Debug ar;
  if (lua_getstack(L, level, &ar)) {  /* check function at level */
    lua_getinfo(L, "Sl", &ar);  /* get info about it */
    if (ar.currentline > 0) {  /* is there info? */
      lua_pushfstring(L, "%s:%d: ", ar.short_src, ar.currentline);
      return;
    }
  }
  lua_pushliteral(L, "");  /* else, no information available... */
}
References lua_Debug::currentline, lua_getinfo(), lua_getstack(), lua_pushfstring(), lua_pushliteral, and lua_Debug::short_src.
Referenced by luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_auxwrap(), luaB_error(), luaB_error(), luaB_error(), luaB_error(), and luaL_error().