Github User Fetcher: lcode.h File Reference
lcode.h File Reference
#include "llex.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
Macros
#define NO_JUMP (-1)
#define getinstruction(fs, e) ((fs)->f->code[(e)->u.info])
#define luaK_codeAsBx(fs, o, A, sBx) luaK_codeABx(fs,o,A,(sBx)+MAXARG_sBx)
#define luaK_setmultret(fs, e) luaK_setreturns(fs, e, LUA_MULTRET)
#define luaK_jumpto(fs, t) luaK_patchlist(fs, luaK_jump(fs), t)
Typedefs
typedef enum BinOpr BinOpr
typedef enum UnOpr UnOpr
Enumerations
enum BinOpr {
OPR_ADD , OPR_SUB , OPR_MUL , OPR_MOD ,
OPR_POW , OPR_DIV , OPR_IDIV , OPR_BAND ,
OPR_BOR , OPR_BXOR , OPR_SHL , OPR_SHR ,
OPR_CONCAT , OPR_EQ , OPR_LT , OPR_LE ,
OPR_NE , OPR_GT , OPR_GE , OPR_AND ,
OPR_OR , OPR_NOBINOPR
}
enum UnOpr {
OPR_MINUS , OPR_BNOT , OPR_NOT , OPR_LEN ,
OPR_NOUNOPR
}
Functions
LUAI_FUNC int luaK_codeABx (FuncState *fs, OpCode o, int A, unsigned int Bx)
LUAI_FUNC int luaK_codeABC (FuncState *fs, OpCode o, int A, int B, int C)
LUAI_FUNC int luaK_codek (FuncState *fs, int reg, int k)
LUAI_FUNC void luaK_fixline (FuncState *fs, int line)
LUAI_FUNC void luaK_nil (FuncState *fs, int from, int n)
LUAI_FUNC void luaK_reserveregs (FuncState *fs, int n)
LUAI_FUNC void luaK_checkstack (FuncState *fs, int n)
LUAI_FUNC int luaK_stringK (FuncState *fs, TString *s)
LUAI_FUNC int luaK_intK (FuncState *fs, lua_Integer n)
LUAI_FUNC void luaK_dischargevars (FuncState *fs, expdesc *e)
LUAI_FUNC int luaK_exp2anyreg (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_exp2anyregup (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_exp2nextreg (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_exp2val (FuncState *fs, expdesc *e)
LUAI_FUNC int luaK_exp2RK (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_self (FuncState *fs, expdesc *e, expdesc *key)
LUAI_FUNC void luaK_indexed (FuncState *fs, expdesc *t, expdesc *k)
LUAI_FUNC void luaK_goiftrue (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_goiffalse (FuncState *fs, expdesc *e)
LUAI_FUNC void luaK_storevar (FuncState *fs, expdesc *var, expdesc *e)
LUAI_FUNC void luaK_setreturns (FuncState *fs, expdesc *e, int nresults)
LUAI_FUNC void luaK_setoneret (FuncState *fs, expdesc *e)
LUAI_FUNC int luaK_jump (FuncState *fs)
LUAI_FUNC void luaK_ret (FuncState *fs, int first, int nret)
LUAI_FUNC void luaK_patchlist (FuncState *fs, int list, int target)
LUAI_FUNC void luaK_patchtohere (FuncState *fs, int list)
LUAI_FUNC void luaK_patchclose (FuncState *fs, int list, int level)
LUAI_FUNC void luaK_concat (FuncState *fs, int *l1, int l2)
LUAI_FUNC int luaK_getlabel (FuncState *fs)
LUAI_FUNC void luaK_prefix (FuncState *fs, UnOpr op, expdesc *v, int line)
LUAI_FUNC void luaK_infix (FuncState *fs, BinOpr op, expdesc *v)
LUAI_FUNC void luaK_posfix (FuncState *fs, BinOpr op, expdesc *v1, expdesc *v2, int line)
LUAI_FUNC void luaK_setlist (FuncState *fs, int base, int nelems, int tostore)
Macro Definition Documentation
getinstruction
#define getinstruction (fs, e) ((fs)->f->code[(e)->u.info])
Definition at line 44 of file lua-5.3.6/src/lcode.h.
Referenced by discharge2reg(), discharge2reg(), exprstat(), exprstat(), jumponcond(), jumponcond(), luaK_posfix(), luaK_setoneret(), luaK_setreturns(), retstat(), and retstat().
luaK_codeAsBx
#define luaK_codeAsBx (fs, o, A, sBx) luaK_codeABx(fs,o,A,(sBx)+MAXARG_sBx)
Definition at line 46 of file lua-5.3.6/src/lcode.h.
luaK_jumpto
#define luaK_jumpto (fs, t) luaK_patchlist(fs, luaK_jump(fs), t)
Definition at line 50 of file lua-5.3.6/src/lcode.h.
luaK_setmultret
#define luaK_setmultret (fs, e) luaK_setreturns(fs, e, LUA_MULTRET)
Definition at line 48 of file lua-5.3.6/src/lcode.h.
NO_JUMP
#define NO_JUMP (-1)
Definition at line 20 of file lua-5.3.6/src/lcode.h.
Typedef Documentation
BinOpr
typedef enum BinOpr BinOpr
UnOpr
typedef enum UnOpr UnOpr
Enumeration Type Documentation
BinOpr
enum BinOpr
Enumerator
OPR_ADD
OPR_SUB
OPR_MUL
OPR_MOD
OPR_POW
OPR_DIV
OPR_IDIV
OPR_BAND
OPR_BOR
OPR_BXOR
OPR_SHL
OPR_SHR
OPR_CONCAT
OPR_EQ
OPR_LT
OPR_LE
OPR_NE
OPR_GT
OPR_GE
OPR_AND
OPR_OR
OPR_NOBINOPR
Definition at line 26 of file lua-5.3.6/src/lcode.h.
                    {
  OPR_ADD, OPR_SUB, OPR_MUL, OPR_MOD, OPR_POW,
  OPR_DIV,
  OPR_IDIV,
  OPR_BAND, OPR_BOR, OPR_BXOR,
  OPR_SHL, OPR_SHR,
  OPR_CONCAT,
  OPR_EQ, OPR_LT, OPR_LE,
  OPR_NE, OPR_GT, OPR_GE,
  OPR_AND, OPR_OR,
  OPR_NOBINOPR
} BinOpr;
UnOpr
enum UnOpr
Enumerator
OPR_MINUS
OPR_BNOT
OPR_NOT
OPR_LEN
OPR_NOUNOPR
Definition at line 40 of file lua-5.3.6/src/lcode.h.
{ OPR_MINUS, OPR_BNOT, OPR_NOT, OPR_LEN, OPR_NOUNOPR } UnOpr;
Function Documentation
luaK_checkstack()
LUAI_FUNC void luaK_checkstack (FuncState * fs, int n)
Definition at line 199 of file lua-5.1.5/src/lcode.c.
{
  int newstack = fs->freereg + n;
  if (newstack > fs->f->maxstacksize) {
    if (newstack >= MAXSTACK)
      luaX_syntaxerror(fs->ls, "function or expression too complex");
    fs->f->maxstacksize = cast_byte(newstack);
  }
}
luaK_codeABC()
LUAI_FUNC int luaK_codeABC (FuncState * fs, OpCode o, int A, int B, int C)
Definition at line 804 of file lua-5.1.5/src/lcode.c.
{
  lua_assert(getOpMode(o) == iABC);
  lua_assert(getBMode(o) != OpArgN || b == 0);
  lua_assert(getCMode(o) != OpArgN || c == 0);
  return luaK_code(fs, CREATE_ABC(o, a, b, c), fs->ls->lastline);
}
References CREATE_ABC, getBMode, getCMode, getOpMode, iABC, LexState::lastline, FuncState::ls, lua_assert, luaK_code(), luaK_code(), luaK_code(), MAXARG_A, MAXARG_B, MAXARG_C, and OpArgN.
luaK_codeABx()
LUAI_FUNC int luaK_codeABx (FuncState * fs, OpCode o, int A, unsigned int Bx)
Definition at line 812 of file lua-5.1.5/src/lcode.c.
{
  lua_assert(getOpMode(o) == iABx || getOpMode(o) == iAsBx);
  lua_assert(getCMode(o) == OpArgN);
  return luaK_code(fs, CREATE_ABx(o, a, bc), fs->ls->lastline);
}
luaK_codek()
LUAI_FUNC int luaK_codek (FuncState * fs, int reg, int k)
Definition at line 250 of file lua-5.2.4/src/lcode.c.
{
  if (k <= MAXARG_Bx)
    return luaK_codeABx(fs, OP_LOADK, reg, k);
  else {
    int p = luaK_codeABx(fs, OP_LOADKX, reg, 0);
    codeextraarg(fs, k);
    return p;
  }
}
References codeextraarg(), codeextraarg(), luaK_codeABx(), MAXARG_Bx, OP_LOADK, and OP_LOADKX.
Referenced by discharge2reg(), discharge2reg(), fornum(), and fornum().
luaK_concat()
LUAI_FUNC void luaK_concat (FuncState * fs, int * l1, int l2)
Definition at line 185 of file lua-5.1.5/src/lcode.c.
{
  if (l2 == NO_JUMP) return;
  else if (*l1 == NO_JUMP)
    *l1 = l2;
  else {
    int list = *l1;
    int next;
    while ((next = getjump(fs, list)) != NO_JUMP)  /* find last element */
      list = next;
    fixjump(fs, list, l2);
  }
}
luaK_dischargevars()
LUAI_FUNC void luaK_dischargevars (FuncState * fs, expdesc * e)
Definition at line 304 of file lua-5.1.5/src/lcode.c.
{
  switch (e->k) {
    case VLOCAL: {
      e->k = VNONRELOC;
      break;
    }
    case VUPVAL: {
      e->u.s.info = luaK_codeABC(fs, OP_GETUPVAL, 0, e->u.s.info, 0);
      e->k = VRELOCABLE;
      break;
    }
    case VGLOBAL: {
      e->u.s.info = luaK_codeABx(fs, OP_GETGLOBAL, 0, e->u.s.info);
      e->k = VRELOCABLE;
      break;
    }
    case VINDEXED: {
      freereg(fs, e->u.s.aux);
      freereg(fs, e->u.s.info);
      e->u.s.info = luaK_codeABC(fs, OP_GETTABLE, 0, e->u.s.info, e->u.s.aux);
      e->k = VRELOCABLE;
      break;
    }
    case VVARARG:
    case VCALL: {
      luaK_setoneret(fs, e);
      break;
    }
    default: break;  /* there is one value available (somewhere) */
  }
}
luaK_exp2anyreg()
LUAI_FUNC int luaK_exp2anyreg (FuncState * fs, expdesc * e)
Definition at line 422 of file lua-5.1.5/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  if (e->k == VNONRELOC) {
    if (!hasjumps(e)) return e->u.s.info;  /* exp is already in a register */
    if (e->u.s.info >= fs->nactvar) {  /* reg. is not a local? */
      exp2reg(fs, e, e->u.s.info);  /* put value on it */
      return e->u.s.info;
    }
  }
  luaK_exp2nextreg(fs, e);  /* default */
  return e->u.s.info;
}
luaK_exp2anyregup()
LUAI_FUNC void luaK_exp2anyregup (FuncState * fs, expdesc * e)
Definition at line 514 of file lua-5.2.4/src/lcode.c.
{
  if (e->k != VUPVAL || hasjumps(e))
    luaK_exp2anyreg(fs, e);
}
luaK_exp2nextreg()
LUAI_FUNC void luaK_exp2nextreg (FuncState * fs, expdesc * e)
Definition at line 414 of file lua-5.1.5/src/lcode.c.
{
  luaK_dischargevars(fs, e);
  freeexp(fs, e);
  luaK_reserveregs(fs, 1);
  exp2reg(fs, e, fs->freereg - 1);
}
luaK_exp2RK()
LUAI_FUNC int luaK_exp2RK (FuncState * fs, expdesc * e)
Definition at line 444 of file lua-5.1.5/src/lcode.c.
{
  luaK_exp2val(fs, e);
  switch (e->k) {
    case VKNUM:
    case VTRUE:
    case VFALSE:
    case VNIL: {
      if (fs->nk <= MAXINDEXRK) {  /* constant fit in RK operand? */
        e->u.s.info = (e->k == VNIL)  ? nilK(fs) :
                      (e->k == VKNUM) ? luaK_numberK(fs, e->u.nval) :
                                        boolK(fs, (e->k == VTRUE));
        e->k = VK;
        return RKASK(e->u.s.info);
      }
      else break;
    }
    case VK: {
      if (e->u.s.info <= MAXINDEXRK)  /* constant fit in argC? */
        return RKASK(e->u.s.info);
      else break;
    }
    default: break;
  }
  /* not a constant in the right range: put it in a register */
  return luaK_exp2anyreg(fs, e);
}
luaK_exp2val()
LUAI_FUNC void luaK_exp2val (FuncState * fs, expdesc * e)
Definition at line 436 of file lua-5.1.5/src/lcode.c.
{
  if (hasjumps(e))
    luaK_exp2anyreg(fs, e);
  else
    luaK_dischargevars(fs, e);
}
luaK_fixline()
LUAI_FUNC void luaK_fixline (FuncState * fs, int line)
Definition at line 784 of file lua-5.1.5/src/lcode.c.
{
  fs->f->lineinfo[fs->pc - 1] = line;
}
luaK_getlabel()
LUAI_FUNC int luaK_getlabel (FuncState * fs)
Definition at line 94 of file lua-5.1.5/src/lcode.c.
{
  fs->lasttarget = fs->pc;
  return fs->pc;
}
luaK_goiffalse()
LUAI_FUNC void luaK_goiffalse (FuncState * fs, expdesc * e)
Definition at line 645 of file lua-5.2.4/src/lcode.c.
{
  int pc;  /* pc of last jump */
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VJMP: {
      pc = e->u.info;
      break;
    }
    case VNIL: case VFALSE: {
      pc = NO_JUMP;  /* always false; do nothing */
      break;
    }
    default: {
      pc = jumponcond(fs, e, 1);
      break;
    }
  }
  luaK_concat(fs, &e->t, pc);  /* insert last jump in `t' list */
  luaK_patchtohere(fs, e->f);
  e->f = NO_JUMP;
}
luaK_goiftrue()
LUAI_FUNC void luaK_goiftrue (FuncState * fs, expdesc * e)
Definition at line 539 of file lua-5.1.5/src/lcode.c.
{
  int pc;  /* pc of last jump */
  luaK_dischargevars(fs, e);
  switch (e->k) {
    case VK: case VKNUM: case VTRUE: {
      pc = NO_JUMP;  /* always true; do nothing */
      break;
    }
    case VJMP: {
      invertjump(fs, e);
      pc = e->u.s.info;
      break;
    }
    default: {
      pc = jumponcond(fs, e, 0);
      break;
    }
  }
  luaK_concat(fs, &e->f, pc);  /* insert last jump in `f' list */
  luaK_patchtohere(fs, e->t);
  e->t = NO_JUMP;
}
luaK_indexed()
LUAI_FUNC void luaK_indexed (FuncState * fs, expdesc * t, expdesc * k)
Definition at line 621 of file lua-5.1.5/src/lcode.c.
{
  t->u.s.aux = luaK_exp2RK(fs, k);
  t->k = VINDEXED;
}
luaK_infix()
LUAI_FUNC void luaK_infix (FuncState * fs, BinOpr op, expdesc * v)
Definition at line 710 of file lua-5.1.5/src/lcode.c.
{
  switch (op) {
    case OPR_AND: {
      luaK_goiftrue(fs, v);
      break;
    }
    case OPR_OR: {
      luaK_goiffalse(fs, v);
      break;
    }
    case OPR_CONCAT: {
      luaK_exp2nextreg(fs, v);  /* operand must be on the `stack' */
      break;
    }
    case OPR_ADD: case OPR_SUB: case OPR_MUL: case OPR_DIV:
    case OPR_MOD: case OPR_POW: {
      if (!isnumeral(v)) luaK_exp2RK(fs, v);
      break;
    }
    default: {
      luaK_exp2RK(fs, v);
      break;
    }
  }
}
luaK_intK()
LUAI_FUNC int luaK_intK (FuncState * fs, lua_Integer n)
Definition at line 471 of file lua-5.3.6/src/lcode.c.
{
  TValue k, o;
  setpvalue(&k, cast(void*, cast(size_t, n)));
  setivalue(&o, n);
  return addk(fs, &k, &o);
}
References addk(), cast, setivalue, and setpvalue.
Referenced by discharge2reg(), fornum(), and luaK_exp2RK().
luaK_jump()
LUAI_FUNC int luaK_jump (FuncState * fs)
Definition at line 59 of file lua-5.1.5/src/lcode.c.
{
  int jpc = fs->jpc;  /* save list of jumps to here */
  int j;
  fs->jpc = NO_JUMP;
  j = luaK_codeAsBx(fs, OP_JMP, 0, NO_JUMP);
  luaK_concat(fs, &j, jpc);  /* keep them on hold */
  return j;
}
luaK_nil()
LUAI_FUNC void luaK_nil (FuncState * fs, int from, int n)
Definition at line 35 of file lua-5.1.5/src/lcode.c.
{
  Instruction *previous;
  if (fs->pc > fs->lasttarget) {  /* no jumps to current position? */
    if (fs->pc == 0) {  /* function start? */
      if (from >= fs->nactvar)
        return;  /* positions are already clean */
    }
    else {
      previous = &fs->f->code[fs->pc-1];
      if (GET_OPCODE(*previous) == OP_LOADNIL) {
        int pfrom = GETARG_A(*previous);
        int pto = GETARG_B(*previous);
        if (pfrom <= from && from <= pto+1) {  /* can connect both? */
          if (from+n-1 > pto)
            SETARG_B(*previous, from+n-1);
          return;
        }
      }
    }
  }
  luaK_codeABC(fs, OP_LOADNIL, from, from+n-1, 0);  /* else no optimization */
}
luaK_patchclose()
LUAI_FUNC void luaK_patchclose (FuncState * fs, int list, int level)
Definition at line 179 of file lua-5.2.4/src/lcode.c.
{
  level++;  /* argument is +1 to reserve 0 as non-op */
  while (list != NO_JUMP) {
    int next = getjump(fs, list);
    lua_assert(GET_OPCODE(fs->f->code[list]) == OP_JMP &&
                (GETARG_A(fs->f->code[list]) == 0 ||
                 GETARG_A(fs->f->code[list]) >= level));
    SETARG_A(fs->f->code[list], level);
    list = next;
  }
}
References Proto::code, FuncState::f, GET_OPCODE, GETARG_A, getjump(), getjump(), lua_assert, next, NO_JUMP, OP_JMP, and SETARG_A.
Referenced by findlabel(), findlabel(), leaveblock(), leaveblock(), movegotosout(), movegotosout(), repeatstat(), and repeatstat().
luaK_patchlist()
LUAI_FUNC void luaK_patchlist (FuncState * fs, int list, int target)
Definition at line 169 of file lua-5.1.5/src/lcode.c.
{
  if (target == fs->pc)
    luaK_patchtohere(fs, list);
  else {
    lua_assert(target < fs->pc);
    patchlistaux(fs, list, target, NO_REG, target);
  }
}
luaK_patchtohere()
LUAI_FUNC void luaK_patchtohere (FuncState * fs, int list)
Definition at line 179 of file lua-5.1.5/src/lcode.c.
{
  luaK_getlabel(fs);
  luaK_concat(fs, &fs->jpc, list);
}
luaK_posfix()
LUAI_FUNC void luaK_posfix (FuncState * fs, BinOpr op, expdesc * v1, expdesc * v2, int line)
Definition at line 813 of file lua-5.2.4/src/lcode.c.
{
  switch (op) {
    case OPR_AND: {
      lua_assert(e1->t == NO_JUMP);  /* list must be closed */
      luaK_dischargevars(fs, e2);
      luaK_concat(fs, &e2->f, e1->f);
      *e1 = *e2;
      break;
    }
    case OPR_OR: {
      lua_assert(e1->f == NO_JUMP);  /* list must be closed */
      luaK_dischargevars(fs, e2);
      luaK_concat(fs, &e2->t, e1->t);
      *e1 = *e2;
      break;
    }
    case OPR_CONCAT: {
      luaK_exp2val(fs, e2);
      if (e2->k == VRELOCABLE && GET_OPCODE(getcode(fs, e2)) == OP_CONCAT) {
        lua_assert(e1->u.info == GETARG_B(getcode(fs, e2))-1);
        freeexp(fs, e1);
        SETARG_B(getcode(fs, e2), e1->u.info);
        e1->k = VRELOCABLE; e1->u.info = e2->u.info;
      }
      else {
        luaK_exp2nextreg(fs, e2);  /* operand must be on the 'stack' */
        codearith(fs, OP_CONCAT, e1, e2, line);
      }
      break;
    }
    case OPR_ADD: case OPR_SUB: case OPR_MUL: case OPR_DIV:
    case OPR_MOD: case OPR_POW: {
      codearith(fs, cast(OpCode, op - OPR_ADD + OP_ADD), e1, e2, line);
      break;
    }
    case OPR_EQ: case OPR_LT: case OPR_LE: {
      codecomp(fs, cast(OpCode, op - OPR_EQ + OP_EQ), 1, e1, e2);
      break;
    }
    case OPR_NE: case OPR_GT: case OPR_GE: {
      codecomp(fs, cast(OpCode, op - OPR_NE + OP_EQ), 0, e1, e2);
      break;
    }
    default: lua_assert(0);
  }
}
luaK_prefix()
LUAI_FUNC void luaK_prefix (FuncState * fs, UnOpr op, expdesc * v, int line)
Definition at line 762 of file lua-5.2.4/src/lcode.c.
{
  expdesc e2;
  e2.t = e2.f = NO_JUMP; e2.k = VKNUM; e2.u.nval = 0;
  switch (op) {
    case OPR_MINUS: {
      if (isnumeral(e))  /* minus constant? */
        e->u.nval = luai_numunm(NULL, e->u.nval);  /* fold it */
      else {
        luaK_exp2anyreg(fs, e);
        codearith(fs, OP_UNM, e, &e2, line);
      }
      break;
    }
    case OPR_NOT: codenot(fs, e); break;
    case OPR_LEN: {
      luaK_exp2anyreg(fs, e);  /* cannot operate on constants */
      codearith(fs, OP_LEN, e, &e2, line);
      break;
    }
    default: lua_assert(0);
  }
}
luaK_reserveregs()
LUAI_FUNC void luaK_reserveregs (FuncState * fs, int n)
Definition at line 209 of file lua-5.1.5/src/lcode.c.
{
  luaK_checkstack(fs, n);
  fs->freereg += n;
}
luaK_ret()
LUAI_FUNC void luaK_ret (FuncState * fs, int first, int nret)
Definition at line 69 of file lua-5.1.5/src/lcode.c.
{
  luaK_codeABC(fs, OP_RETURN, first, nret+1, 0);
}
luaK_self()
LUAI_FUNC void luaK_self (FuncState * fs, expdesc * e, expdesc * key)
Definition at line 503 of file lua-5.1.5/src/lcode.c.
{
  int func;
  luaK_exp2anyreg(fs, e);
  freeexp(fs, e);
  func = fs->freereg;
  luaK_reserveregs(fs, 2);
  luaK_codeABC(fs, OP_SELF, func, e->u.s.info, luaK_exp2RK(fs, key));
  freeexp(fs, key);
  e->u.s.info = func;
  e->k = VNONRELOC;
}
luaK_setlist()
LUAI_FUNC void luaK_setlist (FuncState * fs, int base, int nelems, int tostore)
Definition at line 819 of file lua-5.1.5/src/lcode.c.
{
  int c =  (nelems - 1)/LFIELDS_PER_FLUSH + 1;
  int b = (tostore == LUA_MULTRET) ? 0 : tostore;
  lua_assert(tostore != 0);
  if (c <= MAXARG_C)
    luaK_codeABC(fs, OP_SETLIST, base, b, c);
  else {
    luaK_codeABC(fs, OP_SETLIST, base, b, 0);
    luaK_code(fs, cast(Instruction, c), fs->ls->lastline);
  }
  fs->freereg = base + 1;  /* free registers with list values */
}
luaK_setoneret()
LUAI_FUNC void luaK_setoneret (FuncState * fs, expdesc * e)
Definition at line 292 of file lua-5.1.5/src/lcode.c.
{
  if (e->k == VCALL) {  /* expression is an open function call? */
    e->k = VNONRELOC;
    e->u.s.info = GETARG_A(getcode(fs, e));
  }
  else if (e->k == VVARARG) {
    SETARG_B(getcode(fs, e), 2);
    e->k = VRELOCABLE;  /* can relocate its simple result */
  }
}
luaK_setreturns()
LUAI_FUNC void luaK_setreturns (FuncState * fs, expdesc * e, int nresults)
Definition at line 280 of file lua-5.1.5/src/lcode.c.
{
  if (e->k == VCALL) {  /* expression is an open function call? */
    SETARG_C(getcode(fs, e), nresults+1);
  }
  else if (e->k == VVARARG) {
    SETARG_B(getcode(fs, e), nresults+1);
    SETARG_A(getcode(fs, e), fs->freereg);
    luaK_reserveregs(fs, 1);
  }
}
luaK_storevar()
LUAI_FUNC void luaK_storevar (FuncState * fs, expdesc * var, expdesc * e)
Definition at line 472 of file lua-5.1.5/src/lcode.c.
{
  switch (var->k) {
    case VLOCAL: {
      freeexp(fs, ex);
      exp2reg(fs, ex, var->u.s.info);
      return;
    }
    case VUPVAL: {
      int e = luaK_exp2anyreg(fs, ex);
      luaK_codeABC(fs, OP_SETUPVAL, e, var->u.s.info, 0);
      break;
    }
    case VGLOBAL: {
      int e = luaK_exp2anyreg(fs, ex);
      luaK_codeABx(fs, OP_SETGLOBAL, e, var->u.s.info);
      break;
    }
    case VINDEXED: {
      int e = luaK_exp2RK(fs, ex);
      luaK_codeABC(fs, OP_SETTABLE, var->u.s.info, var->u.s.aux, e);
      break;
    }
    default: {
      lua_assert(0);  /* invalid var kind to store */
      break;
    }
  }
  freeexp(fs, ex);
}
luaK_stringK()
LUAI_FUNC int luaK_stringK (FuncState * fs, TString * s)
Definition at line 250 of file lua-5.1.5/src/lcode.c.
{
  TValue o;
  setsvalue(fs->L, &o, s);
  return addk(fs, &o, &o);
}
References addk(), addk(), addk(), LexState::L, FuncState::L, FuncState::ls, s, and setsvalue.
Referenced by codestring(), codestring(), codestring(), and singlevar().