Github User Fetcher: lparser.h File Reference
lparser.h File Reference
#include "llimits.h"
#include "lobject.h"
#include "lzio.h"
Data Structures
struct expdesc
struct upvaldesc
struct FuncState
Typedefs
typedef struct expdesc expdesc
typedef struct upvaldesc upvaldesc
typedef struct FuncState FuncState
Enumerations
enum expkind {
VVOID , VNIL , VTRUE , VFALSE ,
VK , VKNUM , VLOCAL , VUPVAL ,
VGLOBAL , VINDEXED , VJMP , VRELOCABLE ,
VNONRELOC , VCALL , VVARARG
}
Functions
LUAI_FUNC Proto * luaY_parser (lua_State *L, ZIO *z, Mbuffer *buff, const char *name)
Typedef Documentation
expdesc
typedef struct expdesc expdesc
FuncState
typedef struct FuncState FuncState
upvaldesc
typedef struct upvaldesc upvaldesc
Enumeration Type Documentation
expkind
enum expkind
Enumerator
VVOID
VNIL
VTRUE
VFALSE
VK
VKNUM
VLOCAL
VUPVAL
VGLOBAL
VINDEXED
VJMP
VRELOCABLE
VNONRELOC
VCALL
VVARARG
Definition at line 19 of file lua-5.1.5/src/lparser.h.
             {
  VVOID,    /* no value */
  VNIL,
  VTRUE,
  VFALSE,
  VK,       /* info = index of constant in `k' */
  VKNUM,    /* nval = numerical value */
  VLOCAL,   /* info = local register */
  VUPVAL,       /* info = index of upvalue in `upvalues' */
  VGLOBAL,  /* info = index of table; aux = index of global name in `k' */
  VINDEXED, /* info = table register; aux = index register (or `k') */
  VJMP,     /* info = instruction pc */
  VRELOCABLE,   /* info = instruction pc */
  VNONRELOC,    /* info = result register */
  VCALL,    /* info = instruction pc */
  VVARARG   /* info = instruction pc */
} expkind;
Function Documentation
luaY_parser()
LUAI_FUNC Proto * luaY_parser (lua_State * L, ZIO * z, Mbuffer * buff, const char * name)
Definition at line 25 of file noparser.c.
{
  UNUSED(z);
  UNUSED(buff);
  UNUSED(name);
  lua_pushliteral(L,"parser not loaded");
  lua_error(L);
  return NULL;
}
References LexState::buff, check, chunk(), close_func(), FuncState::f, LexState::fs, Proto::is_vararg, FuncState::L, lua_assert, lua_error(), lua_pushliteral, luaS_new, luaX_next(), luaX_setinput(), name, NULL, Proto::nups, open_func(), FuncState::prev, TK_EOS, UNUSED, and VARARG_ISVARARG.
Referenced by f_parser(), f_parser(), f_parser(), and f_parser().