Github User Fetcher: ldebug.c File Reference
ldebug.c File Reference
#include <stdarg.h>
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "lcode.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lvm.h"
Macros
#define ldebug_c
#define LUA_CORE
#define noLuaClosure(f) ((f) == NULL || (f)->c.tt == LUA_TCCL)
Functions
static const char * getfuncname (lua_State *L, CallInfo *ci, const char **name)
static int currentpc (CallInfo *ci)
static int currentline (CallInfo *ci)
static void swapextra (lua_State *L)
LUA_API int lua_sethook (lua_State *L, lua_Hook func, int mask, int count)
LUA_API lua_Hook lua_gethook (lua_State *L)
LUA_API int lua_gethookmask (lua_State *L)
LUA_API int lua_gethookcount (lua_State *L)
LUA_API int lua_getstack (lua_State *L, int level, lua_Debug *ar)
static const char * upvalname (Proto *p, int uv)
static const char * findvararg (CallInfo *ci, int n, StkId *pos)
static const char * findlocal (lua_State *L, CallInfo *ci, int n, StkId *pos)
LUA_API const char * lua_getlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char * lua_setlocal (lua_State *L, const lua_Debug *ar, int n)
static void funcinfo (lua_Debug *ar, Closure *cl)
static void collectvalidlines (lua_State *L, Closure *f)
static int auxgetinfo (lua_State *L, const char *what, lua_Debug *ar, Closure *f, CallInfo *ci)
LUA_API int lua_getinfo (lua_State *L, const char *what, lua_Debug *ar)
static const char * getobjname (Proto *p, int lastpc, int reg, const char **name)
static void kname (Proto *p, int pc, int c, const char **name)
static int filterpc (int pc, int jmptarget)
static int findsetreg (Proto *p, int lastpc, int reg)
static int isinstack (CallInfo *ci, const TValue *o)
static const char * getupvalname (CallInfo *ci, const TValue *o, const char **name)
l_noret luaG_typeerror (lua_State *L, const TValue *o, const char *op)
l_noret luaG_concaterror (lua_State *L, StkId p1, StkId p2)
l_noret luaG_aritherror (lua_State *L, const TValue *p1, const TValue *p2)
l_noret luaG_ordererror (lua_State *L, const TValue *p1, const TValue *p2)
static void addinfo (lua_State *L, const char *msg)
l_noret luaG_errormsg (lua_State *L)
l_noret luaG_runerror (lua_State *L, const char *fmt,...)
Macro Definition Documentation
ldebug_c
#define ldebug_c
Definition at line 13 of file lua-5.2.4/src/ldebug.c.
LUA_CORE
#define LUA_CORE
Definition at line 14 of file lua-5.2.4/src/ldebug.c.
noLuaClosure
#define noLuaClosure (f) ((f) == NULL || (f)->c.tt == LUA_TCCL)
Definition at line 33 of file lua-5.2.4/src/ldebug.c.
Referenced by auxgetinfo(), collectvalidlines(), and funcinfo().
Function Documentation
addinfo()
static void addinfo (lua_State * L, const char * msg) static
Definition at line 574 of file lua-5.2.4/src/ldebug.c.
{
  CallInfo *ci = L->ci;
  if (isLua(ci)) {  /* is Lua code? */
    char buff[LUA_IDSIZE];  /* add file:line information */
    int line = currentline(ci);
    TString *src = ci_func(ci)->p->source;
    if (src)
      luaO_chunkid(buff, getstr(src), LUA_IDSIZE);
    else {  /* no source available; use "?" instead */
      buff[0] = '?'; buff[1] = '\0';
    }
    luaO_pushfstring(L, "%s:%d: %s", buff, line, msg);
  }
}
References lua_State::ci, ci_func, currentline(), getstr, isLua, LUA_IDSIZE, luaO_chunkid(), and luaO_pushfstring().
Referenced by luaG_runerror().
auxgetinfo()
static int auxgetinfo (lua_State * L, const char * what, lua_Debug * ar, Closure * f, CallInfo * ci) static
Definition at line 230 of file lua-5.2.4/src/ldebug.c.
{
  int status = 1;
  for (; *what; what++) {
    switch (*what) {
      case 'S': {
        funcinfo(ar, f);
        break;
      }
      case 'l': {
        ar->currentline = (ci && isLua(ci)) ? currentline(ci) : -1;
        break;
      }
      case 'u': {
        ar->nups = (f == NULL) ? 0 : f->c.nupvalues;
        if (noLuaClosure(f)) {
          ar->isvararg = 1;
          ar->nparams = 0;
        }
        else {
          ar->isvararg = f->l.p->is_vararg;
          ar->nparams = f->l.p->numparams;
        }
        break;
      }
      case 't': {
        ar->istailcall = (ci) ? ci->callstatus & CIST_TAIL : 0;
        break;
      }
      case 'n': {
        /* calling function is a known Lua function? */
        if (ci && !(ci->callstatus & CIST_TAIL) && isLua(ci->previous))
          ar->namewhat = getfuncname(L, ci->previous, &ar->name);
        else
          ar->namewhat = NULL;
        if (ar->namewhat == NULL) {
          ar->namewhat = "";  /* not found */
          ar->name = NULL;
        }
        break;
      }
      case 'L':
      case 'f':  /* handled by lua_getinfo */
        break;
      default: status = 0;  /* invalid option */
    }
  }
  return status;
}
References Closure::c, CallInfo::callstatus, CIST_TAIL, lua_Debug::currentline, currentline(), funcinfo(), getfuncname(), Proto::is_vararg, isLua, lua_Debug::istailcall, lua_Debug::isvararg, Closure::l, lua_Debug::name, lua_Debug::namewhat, noLuaClosure, lua_Debug::nparams, NULL, Proto::numparams, lua_Debug::nups, LClosure::p, and CallInfo::previous.
Referenced by lua_getinfo().
collectvalidlines()
static void collectvalidlines (lua_State * L, Closure * f) static
Definition at line 211 of file lua-5.2.4/src/ldebug.c.
{
  if (noLuaClosure(f)) {
    setnilvalue(L->top);
    api_incr_top(L);
  }
  else {
    int i;
    TValue v;
    int *lineinfo = f->l.p->lineinfo;
    Table *t = luaH_new(L);  /* new table to store active lines */
    sethvalue(L, L->top, t);  /* push it on stack */
    api_incr_top(L);
    setbvalue(&v, 1);  /* boolean 'true' to be the value of all indices */
    for (i = 0; i < f->l.p->sizelineinfo; i++)  /* for all lines with code */
      luaH_setint(L, t, lineinfo[i], &v);  /* table[line] = true */
  }
}
References api_incr_top, Closure::l, Proto::lineinfo, luaH_new(), luaH_setint(), noLuaClosure, LClosure::p, setbvalue, sethvalue, setnilvalue, Proto::sizelineinfo, and lua_State::top.
Referenced by lua_getinfo().
currentline()
static int currentline (CallInfo * ci) static
Definition at line 45 of file lua-5.2.4/src/ldebug.c.
{
  return getfuncline(ci_func(ci)->p, currentpc(ci));
}
References ci_func, currentpc(), and getfuncline.
Referenced by addinfo(), and auxgetinfo().
currentpc()
static int currentpc (CallInfo * ci) static
Definition at line 39 of file lua-5.2.4/src/ldebug.c.
{
  lua_assert(isLua(ci));
  return pcRel(ci->u.l.savedpc, ci_func(ci)->p);
}
References ci_func, isLua, CallInfo::l, lua_assert, pcRel, CallInfo::savedpc, and CallInfo::u.
Referenced by currentline(), findlocal(), getfuncname(), and luaG_typeerror().
filterpc()
static int filterpc (int pc, int jmptarget) static
Definition at line 347 of file lua-5.2.4/src/ldebug.c.
{
  if (pc < jmptarget)  /* is code conditional (inside a jump)? */
    return -1;  /* cannot know who sets that register */
  else return pc;  /* current position sets that register */
}
Referenced by findsetreg().
findlocal()
static const char * findlocal (lua_State * L, CallInfo * ci, int n, StkId * pos) static
Definition at line 128 of file lua-5.2.4/src/ldebug.c.
{
  const char *name = NULL;
  StkId base;
  if (isLua(ci)) {
    if (n < 0)  /* access to vararg values? */
      return findvararg(ci, -n, pos);
    else {
      base = ci->u.l.base;
      name = luaF_getlocalname(ci_func(ci)->p, n, currentpc(ci));
    }
  }
  else
    base = ci->func + 1;
  if (name == NULL) {  /* no 'standard' name? */
    StkId limit = (ci == L->ci) ? L->top : ci->next->func;
    if (limit - base >= n && n > 0)  /* is 'n' inside 'ci' stack? */
      name = "(*temporary)";  /* generic name for any valid slot */
    else
      return NULL;  /* no name */
  }
  *pos = base + (n - 1);
  return name;
}
References CallInfo::base, lua_State::ci, ci_func, currentpc(), findvararg(), CallInfo::func, isLua, CallInfo::l, luaF_getlocalname(), name, CallInfo::next, NULL, lua_State::top, and CallInfo::u.
Referenced by lua_getlocal(), and lua_setlocal().
findsetreg()
static int findsetreg (Proto * p, int lastpc, int reg) static
Definition at line 357 of file lua-5.2.4/src/ldebug.c.
{
  int pc;
  int setreg = -1;  /* keep last instruction that changed 'reg' */
  int jmptarget = 0;  /* any code before this address is conditional */
  for (pc = 0; pc < lastpc; pc++) {
    Instruction i = p->code[pc];
    OpCode op = GET_OPCODE(i);
    int a = GETARG_A(i);
    switch (op) {
      case OP_LOADNIL: {
        int b = GETARG_B(i);
        if (a <= reg && reg <= a + b)  /* set registers from 'a' to 'a+b' */
          setreg = filterpc(pc, jmptarget);
        break;
      }
      case OP_TFORCALL: {
        if (reg >= a + 2)  /* affect all regs above its base */
          setreg = filterpc(pc, jmptarget);
        break;
      }
      case OP_CALL:
      case OP_TAILCALL: {
        if (reg >= a)  /* affect all registers above base */
          setreg = filterpc(pc, jmptarget);
        break;
      }
      case OP_JMP: {
        int b = GETARG_sBx(i);
        int dest = pc + 1 + b;
        /* jump is forward and do not skip `lastpc'? */
        if (pc < dest && dest <= lastpc) {
          if (dest > jmptarget)
            jmptarget = dest;  /* update 'jmptarget' */
        }
        break;
      }
      case OP_TEST: {
        if (reg == a)  /* jumped code can change 'a' */
          setreg = filterpc(pc, jmptarget);
        break;
      }
      default:
        if (testAMode(op) && reg == a)  /* any instruction that set A */
          setreg = filterpc(pc, jmptarget);
        break;
    }
  }
  return setreg;
}
References Proto::code, filterpc(), GET_OPCODE, GETARG_A, GETARG_B, GETARG_sBx, OP_CALL, OP_JMP, OP_LOADNIL, OP_TAILCALL, OP_TEST, OP_TFORCALL, and testAMode.
Referenced by getobjname().
findvararg()
static const char * findvararg (CallInfo * ci, int n, StkId * pos) static
Definition at line 117 of file lua-5.2.4/src/ldebug.c.
{
  int nparams = clLvalue(ci->func)->p->numparams;
  if (n >= ci->u.l.base - ci->func - nparams)
    return NULL;  /* no such vararg */
  else {
    *pos = ci->func + nparams + n;
    return "(*vararg)";  /* generic name for any vararg */
  }
}
References CallInfo::base, clLvalue, CallInfo::func, CallInfo::l, NULL, and CallInfo::u.
Referenced by findlocal().
funcinfo()
static void funcinfo (lua_Debug * ar, Closure * cl) static
Definition at line 193 of file lua-5.2.4/src/ldebug.c.
{
  if (noLuaClosure(cl)) {
    ar->source = "=[C]";
    ar->linedefined = -1;
    ar->lastlinedefined = -1;
    ar->what = "C";
  }
  else {
    Proto *p = cl->l.p;
    ar->source = p->source ? getstr(p->source) : "=?";
    ar->linedefined = p->linedefined;
    ar->lastlinedefined = p->lastlinedefined;
    ar->what = (ar->linedefined == 0) ? "main" : "Lua";
  }
  luaO_chunkid(ar->short_src, ar->source, LUA_IDSIZE);
}
References getstr, Closure::l, Proto::lastlinedefined, lua_Debug::lastlinedefined, Proto::linedefined, lua_Debug::linedefined, LUA_IDSIZE, luaO_chunkid(), noLuaClosure, LClosure::p, lua_Debug::short_src, Proto::source, lua_Debug::source, and lua_Debug::what.
Referenced by auxgetinfo().
getfuncname()
static const char * getfuncname (lua_State * L, CallInfo * ci, const char ** name) static
Definition at line 462 of file lua-5.2.4/src/ldebug.c.
{
  TMS tm;
  Proto *p = ci_func(ci)->p;  /* calling function */
  int pc = currentpc(ci);  /* calling instruction index */
  Instruction i = p->code[pc];  /* calling instruction */
  switch (GET_OPCODE(i)) {
    case OP_CALL:
    case OP_TAILCALL:  /* get function name */
      return getobjname(p, pc, GETARG_A(i), name);
    case OP_TFORCALL: {  /* for iterator */
      *name = "for iterator";
       return "for iterator";
    }
    /* all other instructions can call only through metamethods */
    case OP_SELF:
    case OP_GETTABUP:
    case OP_GETTABLE: tm = TM_INDEX; break;
    case OP_SETTABUP:
    case OP_SETTABLE: tm = TM_NEWINDEX; break;
    case OP_EQ: tm = TM_EQ; break;
    case OP_ADD: tm = TM_ADD; break;
    case OP_SUB: tm = TM_SUB; break;
    case OP_MUL: tm = TM_MUL; break;
    case OP_DIV: tm = TM_DIV; break;
    case OP_MOD: tm = TM_MOD; break;
    case OP_POW: tm = TM_POW; break;
    case OP_UNM: tm = TM_UNM; break;
    case OP_LEN: tm = TM_LEN; break;
    case OP_LT: tm = TM_LT; break;
    case OP_LE: tm = TM_LE; break;
    case OP_CONCAT: tm = TM_CONCAT; break;
    default:
      return NULL;  /* else no useful name can be found */
  }
  *name = getstr(G(L)->tmname[tm]);
  return "metamethod";
}
References ci_func, Proto::code, currentpc(), G, GET_OPCODE, GETARG_A, getobjname(), getstr, name, NULL, OP_ADD, OP_CALL, OP_CONCAT, OP_DIV, OP_EQ, OP_GETTABLE, OP_GETTABUP, OP_LE, OP_LEN, OP_LT, OP_MOD, OP_MUL, OP_POW, OP_SELF, OP_SETTABLE, OP_SETTABUP, OP_SUB, OP_TAILCALL, OP_TFORCALL, OP_UNM, Proto::p, TM_ADD, TM_CONCAT, TM_DIV, TM_EQ, TM_INDEX, TM_LE, TM_LEN, TM_LT, TM_MOD, TM_MUL, TM_NEWINDEX, TM_POW, TM_SUB, TM_UNM, and tmname.
Referenced by auxgetinfo().
getobjname()
static const char * getobjname (Proto * p, int lastpc, int reg, const char ** name) static
Definition at line 408 of file lua-5.2.4/src/ldebug.c.
{
  int pc;
  *name = luaF_getlocalname(p, reg + 1, lastpc);
  if (*name)  /* is a local? */
    return "local";
  /* else try symbolic execution */
  pc = findsetreg(p, lastpc, reg);
  if (pc != -1) {  /* could find instruction? */
    Instruction i = p->code[pc];
    OpCode op = GET_OPCODE(i);
    switch (op) {
      case OP_MOVE: {
        int b = GETARG_B(i);  /* move from 'b' to 'a' */
        if (b < GETARG_A(i))
          return getobjname(p, pc, b, name);  /* get name for 'b' */
        break;
      }
      case OP_GETTABUP:
      case OP_GETTABLE: {
        int k = GETARG_C(i);  /* key index */
        int t = GETARG_B(i);  /* table index */
        const char *vn = (op == OP_GETTABLE)  /* name of indexed variable */
                         ? luaF_getlocalname(p, t + 1, pc)
                         : upvalname(p, t);
        kname(p, pc, k, name);
        return (vn && strcmp(vn, LUA_ENV) == 0) ? "global" : "field";
      }
      case OP_GETUPVAL: {
        *name = upvalname(p, GETARG_B(i));
        return "upvalue";
      }
      case OP_LOADK:
      case OP_LOADKX: {
        int b = (op == OP_LOADK) ? GETARG_Bx(i)
                                 : GETARG_Ax(p->code[pc + 1]);
        if (ttisstring(&p->k[b])) {
          *name = svalue(&p->k[b]);
          return "constant";
        }
        break;
      }
      case OP_SELF: {
        int k = GETARG_C(i);  /* key index */
        kname(p, pc, k, name);
        return "method";
      }
      default: break;  /* go through to return NULL */
    }
  }
  return NULL;  /* could not find reasonable name */
}
References Proto::code, findsetreg(), GET_OPCODE, GETARG_A, GETARG_Ax, GETARG_B, GETARG_Bx, GETARG_C, getobjname(), Proto::k, kname(), LUA_ENV, luaF_getlocalname(), name, NULL, OP_GETTABLE, OP_GETTABUP, OP_GETUPVAL, OP_LOADK, OP_LOADKX, OP_MOVE, OP_SELF, svalue, ttisstring, and upvalname().
Referenced by getfuncname(), getobjname(), kname(), and luaG_typeerror().
getupvalname()
static const char * getupvalname (CallInfo * ci, const TValue * o, const char ** name) static
Definition at line 516 of file lua-5.2.4/src/ldebug.c.
{
  LClosure *c = ci_func(ci);
  int i;
  for (i = 0; i < c->nupvalues; i++) {
    if (c->upvals[i]->v == o) {
      *name = upvalname(c->p, i);
      return "upvalue";
    }
  }
  return NULL;
}
References ci_func, name, NULL, LClosure::p, upvalname(), LClosure::upvals, and UpVal::v.
Referenced by luaG_typeerror().
isinstack()
static int isinstack (CallInfo * ci, const TValue * o) static
Definition at line 508 of file lua-5.2.4/src/ldebug.c.
{
  StkId p;
  for (p = ci->u.l.base; p < ci->top; p++)
    if (o == p) return 1;
  return 0;
}
References CallInfo::base, CallInfo::l, CallInfo::top, and CallInfo::u.
Referenced by luaG_typeerror().
kname()
static void kname (Proto * p, int pc, int c, const char ** name) static
Definition at line 327 of file lua-5.2.4/src/ldebug.c.
{
  if (ISK(c)) {  /* is 'c' a constant? */
    TValue *kvalue = &p->k[INDEXK(c)];
    if (ttisstring(kvalue)) {  /* literal constant? */
      *name = svalue(kvalue);  /* it is its own name */
      return;
    }
    /* else no reasonable name found */
  }
  else {  /* 'c' is a register */
    const char *what = getobjname(p, pc, c, name); /* search for 'c' */
    if (what && *what == 'c') {  /* found a constant name? */
      return;  /* 'name' already filled */
    }
    /* else no reasonable name found */
  }
  *name = "?";  /* no reasonable name found */
}
References getobjname(), INDEXK, ISK, Proto::k, name, svalue, and ttisstring.
Referenced by getobjname().
lua_gethook()
LUA_API lua_Hook lua_gethook (lua_State * L)
Definition at line 78 of file lua-5.2.4/src/ldebug.c.
{
  return L->hook;
}
References lua_State::hook.
lua_gethookcount()
LUA_API int lua_gethookcount (lua_State * L)
Definition at line 88 of file lua-5.2.4/src/ldebug.c.
{
  return L->basehookcount;
}
References lua_State::basehookcount.
lua_gethookmask()
LUA_API int lua_gethookmask (lua_State * L)
Definition at line 83 of file lua-5.2.4/src/ldebug.c.
{
  return L->hookmask;
}
References lua_State::hookmask.
lua_getinfo()
LUA_API int lua_getinfo (lua_State * L, const char * what, lua_Debug * ar)
Definition at line 281 of file lua-5.2.4/src/ldebug.c.
{
  int status;
  Closure *cl;
  CallInfo *ci;
  StkId func;
  lua_lock(L);
  swapextra(L);
  if (*what == '>') {
    ci = NULL;
    func = L->top - 1;
    api_check(L, ttisfunction(func), "function expected");
    what++;  /* skip the '>' */
    L->top--;  /* pop function */
  }
  else {
    ci = ar->i_ci;
    func = ci->func;
    lua_assert(ttisfunction(ci->func));
  }
  cl = ttisclosure(func) ? clvalue(func) : NULL;
  status = auxgetinfo(L, what, ar, cl, ci);
  if (strchr(what, 'f')) {
    setobjs2s(L, L->top, func);
    api_incr_top(L);
  }
  swapextra(L);
  if (strchr(what, 'L'))
    collectvalidlines(L, cl);
  lua_unlock(L);
  return status;
}
References api_check, api_incr_top, auxgetinfo(), clvalue, collectvalidlines(), CallInfo::func, lua_Debug::i_ci, lua_assert, lua_lock, lua_unlock, NULL, setobjs2s, swapextra(), lua_State::top, ttisclosure, and ttisfunction.
lua_getlocal()
LUA_API const char * lua_getlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 154 of file lua-5.2.4/src/ldebug.c.
{
  const char *name;
  lua_lock(L);
  swapextra(L);
  if (ar == NULL) {  /* information about non-active function? */
    if (!isLfunction(L->top - 1))  /* not a Lua function? */
      name = NULL;
    else  /* consider live variables at function start (parameters) */
      name = luaF_getlocalname(clLvalue(L->top - 1)->p, n, 0);
  }
  else {  /* active function; get information through 'ar' */
    StkId pos = 0;  /* to avoid warnings */
    name = findlocal(L, ar->i_ci, n, &pos);
    if (name) {
      setobj2s(L, L->top, pos);
      api_incr_top(L);
    }
  }
  swapextra(L);
  lua_unlock(L);
  return name;
}
References api_incr_top, clLvalue, findlocal(), lua_Debug::i_ci, isLfunction, lua_lock, lua_unlock, luaF_getlocalname(), name, NULL, setobj2s, swapextra(), and lua_State::top.
lua_getstack()
LUA_API int lua_getstack (lua_State * L, int level, lua_Debug * ar)
Definition at line 93 of file lua-5.2.4/src/ldebug.c.
{
  int status;
  CallInfo *ci;
  if (level < 0) return 0;  /* invalid (negative) level */
  lua_lock(L);
  for (ci = L->ci; level > 0 && ci != &L->base_ci; ci = ci->previous)
    level--;
  if (level == 0 && ci != &L->base_ci) {  /* level found? */
    status = 1;
    ar->i_ci = ci;
  }
  else status = 0;  /* no such level */
  lua_unlock(L);
  return status;
}
References lua_State::base_ci, lua_State::ci, lua_Debug::i_ci, lua_lock, lua_unlock, and CallInfo::previous.
lua_sethook()
LUA_API int lua_sethook (lua_State * L, lua_Hook func, int mask, int count)
Definition at line 63 of file lua-5.2.4/src/ldebug.c.
{
  if (func == NULL || mask == 0) {  /* turn off hooks? */
    mask = 0;
    func = NULL;
  }
  if (isLua(L->ci))
    L->oldpc = L->ci->u.l.savedpc;
  L->hook = func;
  L->basehookcount = count;
  resethookcount(L);
  L->hookmask = cast_byte(mask);
  return 1;
}
References lua_State::basehookcount, cast_byte, lua_State::ci, lua_State::hook, lua_State::hookmask, isLua, CallInfo::l, mask, NULL, lua_State::oldpc, resethookcount, CallInfo::savedpc, and CallInfo::u.
lua_setlocal()
LUA_API const char * lua_setlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 178 of file lua-5.2.4/src/ldebug.c.
{
  StkId pos = 0;  /* to avoid warnings */
  const char *name;
  lua_lock(L);
  swapextra(L);
  name = findlocal(L, ar->i_ci, n, &pos);
  if (name)
    setobjs2s(L, pos, L->top - 1);
  L->top--;  /* pop value */
  swapextra(L);
  lua_unlock(L);
  return name;
}
References findlocal(), lua_Debug::i_ci, lua_lock, lua_unlock, name, setobjs2s, swapextra(), and lua_State::top.
luaG_aritherror()
l_noret luaG_aritherror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 556 of file lua-5.2.4/src/ldebug.c.
{
  TValue temp;
  if (luaV_tonumber(p1, &temp) == NULL)
    p2 = p1;  /* first operand is wrong */
  luaG_typeerror(L, p2, "perform arithmetic on");
}
References luaG_typeerror(), luaV_tonumber(), and NULL.
luaG_concaterror()
l_noret luaG_concaterror (lua_State * L, StkId p1, StkId p2)
Definition at line 549 of file lua-5.2.4/src/ldebug.c.
{
  if (ttisstring(p1) || ttisnumber(p1)) p1 = p2;
  lua_assert(!ttisstring(p1) && !ttisnumber(p1));
  luaG_typeerror(L, p1, "concatenate");
}
References lua_assert, luaG_typeerror(), ttisnumber, and ttisstring.
luaG_errormsg()
l_noret luaG_errormsg (lua_State * L)
Definition at line 590 of file lua-5.2.4/src/ldebug.c.
{
  if (L->errfunc != 0) {  /* is there an error handling function? */
    StkId errfunc = restorestack(L, L->errfunc);
    if (!ttisfunction(errfunc)) luaD_throw(L, LUA_ERRERR);
    setobjs2s(L, L->top, L->top - 1);  /* move argument */
    setobjs2s(L, L->top - 1, errfunc);  /* push function */
    L->top++;
    luaD_call(L, L->top - 2, 1, 0);  /* call it */
  }
  luaD_throw(L, LUA_ERRRUN);
}
References lua_State::errfunc, LUA_ERRERR, LUA_ERRRUN, luaD_call(), luaD_throw(), restorestack, setobjs2s, lua_State::top, and ttisfunction.
Referenced by luaG_runerror().
luaG_ordererror()
l_noret luaG_ordererror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 564 of file lua-5.2.4/src/ldebug.c.
{
  const char *t1 = objtypename(p1);
  const char *t2 = objtypename(p2);
  if (t1 == t2)
    luaG_runerror(L, "attempt to compare two %s values", t1);
  else
    luaG_runerror(L, "attempt to compare %s with %s", t1, t2);
}
References luaG_runerror(), and objtypename.
luaG_runerror()
l_noret luaG_runerror (lua_State * L, const char * fmt, ...)
Definition at line 603 of file lua-5.2.4/src/ldebug.c.
{
  va_list argp;
  va_start(argp, fmt);
  addinfo(L, luaO_pushvfstring(L, fmt, argp));
  va_end(argp);
  luaG_errormsg(L);
}
References addinfo(), luaG_errormsg(), and luaO_pushvfstring().
Referenced by luaG_ordererror(), and luaG_typeerror().
luaG_typeerror()
l_noret luaG_typeerror (lua_State * L, const TValue * o, const char * op)
Definition at line 530 of file lua-5.2.4/src/ldebug.c.
{
  CallInfo *ci = L->ci;
  const char *name = NULL;
  const char *t = objtypename(o);
  const char *kind = NULL;
  if (isLua(ci)) {
    kind = getupvalname(ci, o, &name);  /* check whether 'o' is an upvalue */
    if (!kind && isinstack(ci, o))  /* no? try a register */
      kind = getobjname(ci_func(ci)->p, currentpc(ci),
                        cast_int(o - ci->u.l.base), &name);
  }
  if (kind)
    luaG_runerror(L, "attempt to %s %s " LUA_QS " (a %s value)",
                op, kind, name, t);
  else
    luaG_runerror(L, "attempt to %s a %s value", op, t);
}
References CallInfo::base, cast_int, lua_State::ci, ci_func, currentpc(), getobjname(), getupvalname(), isinstack(), isLua, CallInfo::l, LUA_QS, luaG_runerror(), name, NULL, objtypename, and CallInfo::u.
Referenced by luaG_aritherror(), and luaG_concaterror().
swapextra()
static void swapextra (lua_State * L) static
Definition at line 50 of file lua-5.2.4/src/ldebug.c.
{
  if (L->status == LUA_YIELD) {
    CallInfo *ci = L->ci;  /* get function that yielded */
    StkId temp = ci->func;  /* exchange its 'func' and 'extra' values */
    ci->func = restorestack(L, ci->extra);
    ci->extra = savestack(L, temp);
  }
}
References lua_State::ci, CallInfo::extra, CallInfo::func, LUA_YIELD, restorestack, savestack, and lua_State::status.
Referenced by lua_getinfo(), lua_getlocal(), and lua_setlocal().
upvalname()
static const char * upvalname (Proto * p, int uv) static
Definition at line 110 of file lua-5.2.4/src/ldebug.c.
{
  TString *s = check_exp(uv < p->sizeupvalues, p->upvalues[uv].name);
  if (s == NULL) return "?";
  else return getstr(s);
}
References check_exp, getstr, NULL, s, and Proto::upvalues.
Referenced by getobjname(), and getupvalname().