Github User Fetcher: loadlib.c File Reference
loadlib.c File Reference
#include "lprefix.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define loadlib_c
#define LUA_LIB
#define LUA_IGMARK "-"
#define LUA_CSUBSEP LUA_DIRSEP
#define LUA_LSUBSEP LUA_DIRSEP
#define LUA_POF "luaopen_"
#define LUA_OFSEP "_"
#define LIB_FAIL "open"
#define setprogdir(L) ((void)0)
#define LIB_FAIL "absent"
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
#define LUA_PATH_VAR "LUA_PATH"
#define LUA_CPATH_VAR "LUA_CPATH"
#define AUXMARK "\1" /* auxiliary mark */
#define ERRLIB 1
#define ERRFUNC 2
Functions
static void lsys_unloadlib (void *lib)
static void * lsys_load (lua_State *L, const char *path, int seeglb)
static lua_CFunction lsys_sym (lua_State *L, void *lib, const char *sym)
static int noenv (lua_State *L)
static void setpath (lua_State *L, const char *fieldname, const char *envname, const char *dft)
static void * checkclib (lua_State *L, const char *path)
static void addtoclib (lua_State *L, const char *path, void *plib)
static int gctm (lua_State *L)
static int lookforfunc (lua_State *L, const char *path, const char *sym)
static int ll_loadlib (lua_State *L)
static int readable (const char *filename)
static const char * pushnexttemplate (lua_State *L, const char *path)
static const char * searchpath (lua_State *L, const char *name, const char *path, const char *sep, const char *dirsep)
static int ll_searchpath (lua_State *L)
static const char * findfile (lua_State *L, const char *name, const char *pname, const char *dirsep)
static int checkload (lua_State *L, int stat, const char *filename)
static int searcher_Lua (lua_State *L)
static int loadfunc (lua_State *L, const char *filename, const char *modname)
static int searcher_C (lua_State *L)
static int searcher_Croot (lua_State *L)
static int searcher_preload (lua_State *L)
static void findloader (lua_State *L, const char *name)
static int ll_require (lua_State *L)
static void createsearcherstable (lua_State *L)
static void createclibstable (lua_State *L)
LUAMOD_API int luaopen_package (lua_State *L)
Variables
static const int CLIBS = 0
static const luaL_Reg pk_funcs []
static const luaL_Reg ll_funcs []
Macro Definition Documentation
AUXMARK
#define AUXMARK "\1" /* auxiliary mark */
Definition at line 272 of file lua-5.3.6/src/loadlib.c.
Referenced by setpath().
DLMSG
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
Definition at line 228 of file lua-5.3.6/src/loadlib.c.
Referenced by lsys_load(), and lsys_sym().
ERRFUNC
#define ERRFUNC 2
Definition at line 359 of file lua-5.3.6/src/loadlib.c.
Referenced by loadfunc(), lookforfunc(), and searcher_Croot().
ERRLIB
#define ERRLIB 1
Definition at line 358 of file lua-5.3.6/src/loadlib.c.
Referenced by ll_loadlib(), and lookforfunc().
LIB_FAIL [1/2]
#define LIB_FAIL "open"
Definition at line 64 of file lua-5.3.6/src/loadlib.c.
Referenced by ll_loadlib().
LIB_FAIL [2/2]
#define LIB_FAIL "absent"
Definition at line 64 of file lua-5.3.6/src/loadlib.c.
loadlib_c
#define loadlib_c
Definition at line 11 of file lua-5.3.6/src/loadlib.c.
LUA_CPATH_VAR
#define LUA_CPATH_VAR "LUA_CPATH"
Definition at line 268 of file lua-5.3.6/src/loadlib.c.
Referenced by luaopen_package().
LUA_CSUBSEP
#define LUA_CSUBSEP LUA_DIRSEP
Definition at line 43 of file lua-5.3.6/src/loadlib.c.
Referenced by searcher_C(), and searcher_Croot().
LUA_IGMARK
#define LUA_IGMARK "-"
Definition at line 32 of file lua-5.3.6/src/loadlib.c.
Referenced by loadfunc(), and luaopen_package().
LUA_LIB
#define LUA_LIB
Definition at line 12 of file lua-5.3.6/src/loadlib.c.
LUA_LSUBSEP
#define LUA_LSUBSEP LUA_DIRSEP
Definition at line 47 of file lua-5.3.6/src/loadlib.c.
Referenced by searcher_Lua().
LUA_OFSEP
#define LUA_OFSEP "_"
Definition at line 55 of file lua-5.3.6/src/loadlib.c.
Referenced by loadfunc().
LUA_PATH_VAR
#define LUA_PATH_VAR "LUA_PATH"
Definition at line 264 of file lua-5.3.6/src/loadlib.c.
Referenced by luaopen_package().
LUA_POF
#define LUA_POF "luaopen_"
Definition at line 52 of file lua-5.3.6/src/loadlib.c.
Referenced by loadfunc().
setprogdir
#define setprogdir (L) ((void)0)
Definition at line 67 of file lua-5.3.6/src/loadlib.c.
Referenced by setpath().
Function Documentation
addtoclib()
static void addtoclib (lua_State * L, const char * path, void * plib) static
Definition at line 331 of file lua-5.3.6/src/loadlib.c.
{
  lua_rawgetp(L, LUA_REGISTRYINDEX, &CLIBS);
  lua_pushlightuserdata(L, plib);
  lua_pushvalue(L, -1);
  lua_setfield(L, -3, path);  /* CLIBS[path] = plib */
  lua_rawseti(L, -2, luaL_len(L, -2) + 1);  /* CLIBS[#CLIBS + 1] = plib */
  lua_pop(L, 1);  /* pop CLIBS table */
}
References CLIBS, lua_pop, lua_pushlightuserdata(), lua_pushvalue(), lua_rawgetp(), lua_rawseti(), LUA_REGISTRYINDEX, lua_setfield(), and luaL_len().
Referenced by lookforfunc().
checkclib()
static void * checkclib (lua_State * L, const char * path) static
Definition at line 317 of file lua-5.3.6/src/loadlib.c.
{
  void *plib;
  lua_rawgetp(L, LUA_REGISTRYINDEX, &CLIBS);
  lua_getfield(L, -1, path);
  plib = lua_touserdata(L, -1);  /* plib = CLIBS[path] */
  lua_pop(L, 2);  /* pop CLIBS table and 'plib' */
  return plib;
}
References CLIBS, lua_getfield(), lua_pop, lua_rawgetp(), LUA_REGISTRYINDEX, and lua_touserdata().
Referenced by lookforfunc().
checkload()
static int checkload (lua_State * L, int stat, const char * filename) static
Definition at line 484 of file lua-5.3.6/src/loadlib.c.
{
  if (stat) {  /* module loaded successfully? */
    lua_pushstring(L, filename);  /* will be 2nd argument to module */
    return 2;  /* return open function and file name */
  }
  else
    return luaL_error(L, "error loading module '%s' from file '%s':\n\t%s",
                          lua_tostring(L, 1), filename, lua_tostring(L, -1));
}
References lua_pushstring(), lua_tostring, and luaL_error().
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
createclibstable()
static void createclibstable (lua_State * L) static
Definition at line 757 of file lua-5.3.6/src/loadlib.c.
{
  lua_newtable(L);  /* create CLIBS table */
  lua_createtable(L, 0, 1);  /* create metatable for CLIBS */
  lua_pushcfunction(L, gctm);
  lua_setfield(L, -2, "__gc");  /* set finalizer for CLIBS table */
  lua_setmetatable(L, -2);
  lua_rawsetp(L, LUA_REGISTRYINDEX, &CLIBS);  /* set CLIBS table in registry */
}
References CLIBS, gctm(), lua_createtable(), lua_newtable, lua_pushcfunction, lua_rawsetp(), LUA_REGISTRYINDEX, lua_setfield(), and lua_setmetatable().
Referenced by luaopen_package().
createsearcherstable()
static void createsearcherstable (lua_State * L) static
Definition at line 733 of file lua-5.3.6/src/loadlib.c.
{
  static const lua_CFunction searchers[] =
    {searcher_preload, searcher_Lua, searcher_C, searcher_Croot, NULL};
  int i;
  /* create 'searchers' table */
  lua_createtable(L, sizeof(searchers)/sizeof(searchers[0]) - 1, 0);
  /* fill it with predefined searchers */
  for (i=0; searchers[i] != NULL; i++) {
    lua_pushvalue(L, -2);  /* set 'package' as upvalue for all searchers */
    lua_pushcclosure(L, searchers[i], 1);
    lua_rawseti(L, -2, i+1);
  }
#if defined(LUA_COMPAT_LOADERS)
  lua_pushvalue(L, -1);  /* make a copy of 'searchers' table */
  lua_setfield(L, -3, "loaders");  /* put it in field 'loaders' */
#endif
  lua_setfield(L, -2, "searchers");  /* put it in field 'searchers' */
}
References lua_createtable(), lua_pushcclosure(), lua_pushvalue(), lua_rawseti(), lua_setfield(), NULL, searcher_C(), searcher_Croot(), searcher_Lua(), and searcher_preload().
Referenced by luaopen_package().
findfile()
static const char * findfile (lua_State * L, const char * name, const char * pname, const char * dirsep) static
Definition at line 472 of file lua-5.3.6/src/loadlib.c.
{
  const char *path;
  lua_getfield(L, lua_upvalueindex(1), pname);
  path = lua_tostring(L, -1);
  if (path == NULL)
    luaL_error(L, "'package.%s' must be a string", pname);
  return searchpath(L, name, path, ".", dirsep);
}
References lua_getfield(), lua_tostring, lua_upvalueindex, luaL_error(), name, NULL, and searchpath().
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
findloader()
static void findloader (lua_State * L, const char * name) static
Definition at line 569 of file lua-5.3.6/src/loadlib.c.
{
  int i;
  luaL_Buffer msg;  /* to build error message */
  luaL_buffinit(L, &msg);
  /* push 'package.searchers' to index 3 in the stack */
  if (lua_getfield(L, lua_upvalueindex(1), "searchers") != LUA_TTABLE)
    luaL_error(L, "'package.searchers' must be a table");
  /*  iterate over available searchers to find a loader */
  for (i = 1; ; i++) {
    if (lua_rawgeti(L, 3, i) == LUA_TNIL) {  /* no more searchers? */
      lua_pop(L, 1);  /* remove nil */
      luaL_pushresult(&msg);  /* create error message */
      luaL_error(L, "module '%s' not found:%s", name, lua_tostring(L, -1));
    }
    lua_pushstring(L, name);
    lua_call(L, 1, 2);  /* call it */
    if (lua_isfunction(L, -2))  /* did it find a loader? */
      return;  /* module loader found */
    else if (lua_isstring(L, -2)) {  /* searcher returned error message? */
      lua_pop(L, 1);  /* remove extra return */
      luaL_addvalue(&msg);  /* concatenate error message */
    }
    else
      lua_pop(L, 2);  /* remove both returns */
  }
}
References lua_call, lua_getfield(), lua_isfunction, lua_isstring(), lua_pop, lua_pushstring(), lua_rawgeti(), LUA_TNIL, lua_tostring, LUA_TTABLE, lua_upvalueindex, luaL_addvalue(), luaL_buffinit(), luaL_error(), luaL_pushresult(), and name.
Referenced by ll_require().
gctm()
static int gctm (lua_State * L) static
Definition at line 345 of file lua-5.3.6/src/loadlib.c.
{
  lua_Integer n = luaL_len(L, 1);
  for (; n >= 1; n--) {  /* for each handle, in reverse order */
    lua_rawgeti(L, 1, n);  /* get handle CLIBS[n] */
    lsys_unloadlib(lua_touserdata(L, -1));
    lua_pop(L, 1);  /* pop handle */
  }
  return 0;
}
References lsys_unloadlib(), lua_pop, lua_rawgeti(), lua_touserdata(), and luaL_len().
Referenced by createclibstable().
ll_loadlib()
static int ll_loadlib (lua_State * L) static
Definition at line 393 of file lua-5.3.6/src/loadlib.c.
{
  const char *path = luaL_checkstring(L, 1);
  const char *init = luaL_checkstring(L, 2);
  int stat = lookforfunc(L, path, init);
  if (stat == 0)  /* no errors? */
    return 1;  /* return the loaded function */
  else {  /* error; error message is on stack top */
    lua_pushnil(L);
    lua_insert(L, -2);
    lua_pushstring(L, (stat == ERRLIB) ?  LIB_FAIL : "init");
    return 3;  /* return nil, error message, and where */
  }
}
References ERRLIB, LIB_FAIL, lookforfunc(), lua_insert, lua_pushnil(), lua_pushstring(), and luaL_checkstring.
ll_require()
static int ll_require (lua_State * L) static
Definition at line 597 of file lua-5.3.6/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  lua_settop(L, 1);  /* LOADED table will be at index 2 */
  lua_getfield(L, LUA_REGISTRYINDEX, LUA_LOADED_TABLE);
  lua_getfield(L, 2, name);  /* LOADED[name] */
  if (lua_toboolean(L, -1))  /* is it there? */
    return 1;  /* package is already loaded */
  /* else must load package */
  lua_pop(L, 1);  /* remove 'getfield' result */
  findloader(L, name);
  lua_pushstring(L, name);  /* pass name as argument to module loader */
  lua_insert(L, -2);  /* name is 1st argument (before search data) */
  lua_call(L, 2, 1);  /* run loader to load module */
  if (!lua_isnil(L, -1))  /* non-nil return? */
    lua_setfield(L, 2, name);  /* LOADED[name] = returned value */
  if (lua_getfield(L, 2, name) == LUA_TNIL) {   /* module set no value? */
    lua_pushboolean(L, 1);  /* use true as result */
    lua_pushvalue(L, -1);  /* extra copy to be returned */
    lua_setfield(L, 2, name);  /* LOADED[name] = true */
  }
  return 1;
}
References findloader(), lua_call, lua_getfield(), lua_insert, lua_isnil, LUA_LOADED_TABLE, lua_pop, lua_pushboolean(), lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_settop(), LUA_TNIL, lua_toboolean(), luaL_checkstring, and name.
ll_searchpath()
static int ll_searchpath (lua_State * L) static
Definition at line 458 of file lua-5.3.6/src/loadlib.c.
{
  const char *f = searchpath(L, luaL_checkstring(L, 1),
                                luaL_checkstring(L, 2),
                                luaL_optstring(L, 3, "."),
                                luaL_optstring(L, 4, LUA_DIRSEP));
  if (f != NULL) return 1;
  else {  /* error message is on top of the stack */
    lua_pushnil(L);
    lua_insert(L, -2);
    return 2;  /* return nil + error message */
  }
}
References LUA_DIRSEP, lua_insert, lua_pushnil(), luaL_checkstring, luaL_optstring, NULL, and searchpath().
loadfunc()
static int loadfunc (lua_State * L, const char * filename, const char * modname) static
Definition at line 512 of file lua-5.3.6/src/loadlib.c.
{
  const char *openfunc;
  const char *mark;
  modname = luaL_gsub(L, modname, ".", LUA_OFSEP);
  mark = strchr(modname, *LUA_IGMARK);
  if (mark) {
    int stat;
    openfunc = lua_pushlstring(L, modname, mark - modname);
    openfunc = lua_pushfstring(L, LUA_POF"%s", openfunc);
    stat = lookforfunc(L, filename, openfunc);
    if (stat != ERRFUNC) return stat;
    modname = mark + 1;  /* else go ahead and try old-style name */
  }
  openfunc = lua_pushfstring(L, LUA_POF"%s", modname);
  return lookforfunc(L, filename, openfunc);
}
References ERRFUNC, lookforfunc(), LUA_IGMARK, LUA_OFSEP, LUA_POF, lua_pushfstring(), lua_pushlstring(), and luaL_gsub().
Referenced by searcher_C(), and searcher_Croot().
lookforfunc()
static int lookforfunc (lua_State * L, const char * path, const char * sym) static
Definition at line 372 of file lua-5.3.6/src/loadlib.c.
{
  void *reg = checkclib(L, path);  /* check loaded C libraries */
  if (reg == NULL) {  /* must load library? */
    reg = lsys_load(L, path, *sym == '*');  /* global symbols if 'sym'=='*' */
    if (reg == NULL) return ERRLIB;  /* unable to load library */
    addtoclib(L, path, reg);
  }
  if (*sym == '*') {  /* loading only library (no function)? */
    lua_pushboolean(L, 1);  /* return 'true' */
    return 0;  /* no errors */
  }
  else {
    lua_CFunction f = lsys_sym(L, reg, sym);
    if (f == NULL)
      return ERRFUNC;  /* unable to find function */
    lua_pushcfunction(L, f);  /* else create new function */
    return 0;  /* no errors */
  }
}
References addtoclib(), checkclib(), ERRFUNC, ERRLIB, lsys_load(), lsys_sym(), lua_pushboolean(), lua_pushcfunction, and NULL.
Referenced by ll_loadlib(), and loadfunc().
lsys_load()
static void * lsys_load (lua_State * L, const char * path, int seeglb) static
Definition at line 236 of file lua-5.3.6/src/loadlib.c.
{
  (void)(path); (void)(seeglb);  /* not used */
  lua_pushliteral(L, DLMSG);
  return NULL;
}
References DLMSG, lua_pushliteral, and NULL.
Referenced by lookforfunc().
lsys_sym()
static lua_CFunction lsys_sym (lua_State * L, void * lib, const char * sym) static
Definition at line 243 of file lua-5.3.6/src/loadlib.c.
{
  (void)(lib); (void)(sym);  /* not used */
  lua_pushliteral(L, DLMSG);
  return NULL;
}
References DLMSG, lua_pushliteral, and NULL.
Referenced by lookforfunc().
lsys_unloadlib()
static void lsys_unloadlib (void * lib) static
Definition at line 231 of file lua-5.3.6/src/loadlib.c.
{
  (void)(lib);  /* not used */
}
Referenced by gctm().
luaopen_package()
LUAMOD_API int luaopen_package (lua_State * L)
Definition at line 767 of file lua-5.3.6/src/loadlib.c.
{
  createclibstable(L);
  luaL_newlib(L, pk_funcs);  /* create 'package' table */
  createsearcherstable(L);
  /* set paths */
  setpath(L, "path", LUA_PATH_VAR, LUA_PATH_DEFAULT);
  setpath(L, "cpath", LUA_CPATH_VAR, LUA_CPATH_DEFAULT);
  /* store config information */
  lua_pushliteral(L, LUA_DIRSEP "\n" LUA_PATH_SEP "\n" LUA_PATH_MARK "\n"
                     LUA_EXEC_DIR "\n" LUA_IGMARK "\n");
  lua_setfield(L, -2, "config");
  /* set field 'loaded' */
  luaL_getsubtable(L, LUA_REGISTRYINDEX, LUA_LOADED_TABLE);
  lua_setfield(L, -2, "loaded");
  /* set field 'preload' */
  luaL_getsubtable(L, LUA_REGISTRYINDEX, LUA_PRELOAD_TABLE);
  lua_setfield(L, -2, "preload");
  lua_pushglobaltable(L);
  lua_pushvalue(L, -2);  /* set 'package' as upvalue for next lib */
  luaL_setfuncs(L, ll_funcs, 1);  /* open lib into global table */
  lua_pop(L, 1);  /* pop global table */
  return 1;  /* return 'package' table */
}
References createclibstable(), createsearcherstable(), ll_funcs, LUA_CPATH_DEFAULT, LUA_CPATH_VAR, LUA_DIRSEP, LUA_EXEC_DIR, LUA_IGMARK, LUA_LOADED_TABLE, LUA_PATH_DEFAULT, LUA_PATH_MARK, LUA_PATH_SEP, LUA_PATH_VAR, lua_pop, LUA_PRELOAD_TABLE, lua_pushglobaltable, lua_pushliteral, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), luaL_getsubtable(), luaL_newlib, luaL_setfuncs(), pk_funcs, and setpath().
noenv()
static int noenv (lua_State * L) static
Definition at line 278 of file lua-5.3.6/src/loadlib.c.
{
  int b;
  lua_getfield(L, LUA_REGISTRYINDEX, "LUA_NOENV");
  b = lua_toboolean(L, -1);
  lua_pop(L, 1);  /* remove value */
  return b;
}
References lua_getfield(), lua_pop, LUA_REGISTRYINDEX, and lua_toboolean().
Referenced by setpath().
pushnexttemplate()
static const char * pushnexttemplate (lua_State * L, const char * path) static
Definition at line 424 of file lua-5.3.6/src/loadlib.c.
{
  const char *l;
  while (*path == *LUA_PATH_SEP) path++;  /* skip separators */
  if (*path == '\0') return NULL;  /* no more templates */
  l = strchr(path, *LUA_PATH_SEP);  /* find next separator */
  if (l == NULL) l = path + strlen(path);
  lua_pushlstring(L, path, l - path);  /* template */
  return l;
}
References LUA_PATH_SEP, lua_pushlstring(), and NULL.
Referenced by searchpath().
readable()
static int readable (const char * filename) static
Definition at line 416 of file lua-5.3.6/src/loadlib.c.
{
  FILE *f = fopen(filename, "r");  /* try to open file */
  if (f == NULL) return 0;  /* open failed */
  fclose(f);
  return 1;
}
References NULL.
Referenced by searchpath().
searcher_C()
static int searcher_C (lua_State * L) static
Definition at line 530 of file lua-5.3.6/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  const char *filename = findfile(L, name, "cpath", LUA_CSUBSEP);
  if (filename == NULL) return 1;  /* module not found in this path */
  return checkload(L, (loadfunc(L, filename, name) == 0), filename);
}
References checkload(), findfile(), loadfunc(), LUA_CSUBSEP, luaL_checkstring, name, and NULL.
Referenced by createsearcherstable().
searcher_Croot()
static int searcher_Croot (lua_State * L) static
Definition at line 538 of file lua-5.3.6/src/loadlib.c.
{
  const char *filename;
  const char *name = luaL_checkstring(L, 1);
  const char *p = strchr(name, '.');
  int stat;
  if (p == NULL) return 0;  /* is root */
  lua_pushlstring(L, name, p - name);
  filename = findfile(L, lua_tostring(L, -1), "cpath", LUA_CSUBSEP);
  if (filename == NULL) return 1;  /* root not found */
  if ((stat = loadfunc(L, filename, name)) != 0) {
    if (stat != ERRFUNC)
      return checkload(L, 0, filename);  /* real error */
    else {  /* open function not found */
      lua_pushfstring(L, "\n\tno module '%s' in file '%s'", name, filename);
      return 1;
    }
  }
  lua_pushstring(L, filename);  /* will be 2nd argument to module */
  return 2;
}
References checkload(), ERRFUNC, findfile(), loadfunc(), LUA_CSUBSEP, lua_pushfstring(), lua_pushlstring(), lua_pushstring(), lua_tostring, luaL_checkstring, name, and NULL.
Referenced by createsearcherstable().
searcher_Lua()
static int searcher_Lua (lua_State * L) static
Definition at line 495 of file lua-5.3.6/src/loadlib.c.
{
  const char *filename;
  const char *name = luaL_checkstring(L, 1);
  filename = findfile(L, name, "path", LUA_LSUBSEP);
  if (filename == NULL) return 1;  /* module not found in this path */
  return checkload(L, (luaL_loadfile(L, filename) == LUA_OK), filename);
}
References checkload(), findfile(), LUA_LSUBSEP, LUA_OK, luaL_checkstring, luaL_loadfile, name, and NULL.
Referenced by createsearcherstable().
searcher_preload()
static int searcher_preload (lua_State * L) static
Definition at line 560 of file lua-5.3.6/src/loadlib.c.
{
  const char *name = luaL_checkstring(L, 1);
  lua_getfield(L, LUA_REGISTRYINDEX, LUA_PRELOAD_TABLE);
  if (lua_getfield(L, -1, name) == LUA_TNIL)  /* not found? */
    lua_pushfstring(L, "\n\tno field package.preload['%s']", name);
  return 1;
}
References lua_getfield(), LUA_PRELOAD_TABLE, lua_pushfstring(), LUA_REGISTRYINDEX, LUA_TNIL, luaL_checkstring, and name.
Referenced by createsearcherstable().
searchpath()
static const char * searchpath (lua_State * L, const char * name, const char * path, const char * sep, const char * dirsep) static
Definition at line 435 of file lua-5.3.6/src/loadlib.c.
{
  luaL_Buffer msg;  /* to build error message */
  luaL_buffinit(L, &msg);
  if (*sep != '\0')  /* non-empty separator? */
    name = luaL_gsub(L, name, sep, dirsep);  /* replace it by 'dirsep' */
  while ((path = pushnexttemplate(L, path)) != NULL) {
    const char *filename = luaL_gsub(L, lua_tostring(L, -1),
                                     LUA_PATH_MARK, name);
    lua_remove(L, -2);  /* remove path template */
    if (readable(filename))  /* does file exist and is readable? */
      return filename;  /* return that file name */
    lua_pushfstring(L, "\n\tno file '%s'", filename);
    lua_remove(L, -2);  /* remove file name */
    luaL_addvalue(&msg);  /* concatenate error msg. entry */
  }
  luaL_pushresult(&msg);  /* create error message */
  return NULL;  /* not found */
}
References LUA_PATH_MARK, lua_pushfstring(), lua_remove, lua_tostring, luaL_addvalue(), luaL_buffinit(), luaL_gsub(), luaL_pushresult(), name, NULL, pushnexttemplate(), and readable().
Referenced by findfile(), and ll_searchpath().
setpath()
static void setpath (lua_State * L, const char * fieldname, const char * envname, const char * dft) static
Definition at line 290 of file lua-5.3.6/src/loadlib.c.
{
  const char *nver = lua_pushfstring(L, "%s%s", envname, LUA_VERSUFFIX);
  const char *path = getenv(nver);  /* use versioned name */
  if (path == NULL)  /* no environment variable? */
    path = getenv(envname);  /* try unversioned name */
  if (path == NULL || noenv(L))  /* no environment variable? */
    lua_pushstring(L, dft);  /* use default */
  else {
    /* replace ";;" by ";AUXMARK;" and then AUXMARK by default path */
    path = luaL_gsub(L, path, LUA_PATH_SEP LUA_PATH_SEP,
                              LUA_PATH_SEP AUXMARK LUA_PATH_SEP);
    luaL_gsub(L, path, AUXMARK, dft);
    lua_remove(L, -2); /* remove result from 1st 'gsub' */
  }
  setprogdir(L);
  lua_setfield(L, -3, fieldname);  /* package[fieldname] = path value */
  lua_pop(L, 1);  /* pop versioned variable name */
}
References AUXMARK, LUA_PATH_SEP, lua_pop, lua_pushfstring(), lua_pushstring(), lua_remove, lua_setfield(), LUA_VERSUFFIX, luaL_gsub(), noenv(), NULL, and setprogdir.
Referenced by luaopen_package().
Variable Documentation
CLIBS
const int CLIBS = 0 static
Definition at line 62 of file lua-5.3.6/src/loadlib.c.
Referenced by addtoclib(), checkclib(), and createclibstable().
ll_funcs
const luaL_Reg ll_funcs[] static
Initial value:
= {
  {"require", ll_require},
  {NULL, NULL}
}
Definition at line 724 of file lua-5.3.6/src/loadlib.c.
{
#if defined(LUA_COMPAT_MODULE)
  {"module", ll_module},
#endif
  {"require", ll_require},
  {NULL, NULL}
};
Referenced by luaopen_package().
pk_funcs
const luaL_Reg pk_funcs[] static
Initial value:
= {
  {"loadlib", ll_loadlib},
  {"searchpath", ll_searchpath},
  {"preload", NULL},
  {"cpath", NULL},
  {"path", NULL},
  {"searchers", NULL},
  {"loaded", NULL},
  {NULL, NULL}
}
Definition at line 708 of file lua-5.3.6/src/loadlib.c.
{
  {"loadlib", ll_loadlib},
  {"searchpath", ll_searchpath},
#if defined(LUA_COMPAT_MODULE)
  {"seeall", ll_seeall},
#endif
  /* placeholders */
  {"preload", NULL},
  {"cpath", NULL},
  {"path", NULL},
  {"searchers", NULL},
  {"loaded", NULL},
  {NULL, NULL}
};
Referenced by luaopen_package().