Github User Fetcher: ltablib.c File Reference
ltablib.c File Reference
#include "lprefix.h"
#include <limits.h>
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include <time.h>
Macros
#define ltablib_c
#define LUA_LIB
#define TAB_R 1 /* read */
#define TAB_W 2 /* write */
#define TAB_L 4 /* length */
#define TAB_RW (TAB_R | TAB_W) /* read/write */
#define aux_getn(L, n, w) (checktab(L, n, (w) | TAB_L), luaL_len(L, n))
#define sof(e) (sizeof(e) / sizeof(unsigned int))
#define RANLIMIT 100u
Typedefs
typedef unsigned int IdxT
Functions
static int checkfield (lua_State *L, const char *key, int n)
static void checktab (lua_State *L, int arg, int what)
static int tinsert (lua_State *L)
static int tremove (lua_State *L)
static int tmove (lua_State *L)
static void addfield (lua_State *L, luaL_Buffer *b, lua_Integer i)
static int tconcat (lua_State *L)
static int pack (lua_State *L)
static int unpack (lua_State *L)
static unsigned int l_randomizePivot (void)
static void set2 (lua_State *L, IdxT i, IdxT j)
static int sort_comp (lua_State *L, int a, int b)
static IdxT partition (lua_State *L, IdxT lo, IdxT up)
static IdxT choosePivot (IdxT lo, IdxT up, unsigned int rnd)
static void auxsort (lua_State *L, IdxT lo, IdxT up, unsigned int rnd)
static int sort (lua_State *L)
LUAMOD_API int luaopen_table (lua_State *L)
Variables
static const luaL_Reg tab_funcs []
Macro Definition Documentation
aux_getn
#define aux_getn (L, n, w) (checktab(L, n, (w) | TAB_L), luaL_len(L, n))
Definition at line 33 of file lua-5.3.6/src/ltablib.c.
Referenced by sort(), tconcat(), tinsert(), and tremove().
ltablib_c
#define ltablib_c
Definition at line 7 of file lua-5.3.6/src/ltablib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lua-5.3.6/src/ltablib.c.
RANLIMIT
#define RANLIMIT 100u
Definition at line 274 of file lua-5.3.6/src/ltablib.c.
Referenced by auxsort().
sof
#define sof (e) (sizeof(e) / sizeof(unsigned int))
Definition at line 250 of file lua-5.3.6/src/ltablib.c.
Referenced by l_randomizePivot().
TAB_L
#define TAB_L 4 /* length */
Definition at line 29 of file lua-5.3.6/src/ltablib.c.
Referenced by checktab().
TAB_R
#define TAB_R 1 /* read */
Definition at line 27 of file lua-5.3.6/src/ltablib.c.
Referenced by checktab(), tconcat(), and tmove().
TAB_RW
#define TAB_RW (TAB_R | TAB_W) /* read/write */
Definition at line 30 of file lua-5.3.6/src/ltablib.c.
Referenced by sort(), tinsert(), and tremove().
TAB_W
#define TAB_W 2 /* write */
Definition at line 28 of file lua-5.3.6/src/ltablib.c.
Referenced by checktab(), and tmove().
Typedef Documentation
IdxT
typedef unsigned int IdxT
Definition at line 236 of file lua-5.3.6/src/ltablib.c.
Function Documentation
addfield()
static void addfield (lua_State * L, luaL_Buffer * b, lua_Integer i) static
Definition at line 160 of file lua-5.3.6/src/ltablib.c.
{
  lua_geti(L, 1, i);
  if (!lua_isstring(L, -1))
    luaL_error(L, "invalid value (%s) at index %d in table for 'concat'",
                  luaL_typename(L, -1), i);
  luaL_addvalue(b);
}
References lua_geti(), lua_isstring(), luaL_addvalue(), luaL_error(), and luaL_typename.
Referenced by tconcat().
auxsort()
static void auxsort (lua_State * L, IdxT lo, IdxT up, unsigned int rnd) static
Definition at line 357 of file lua-5.3.6/src/ltablib.c.
{
  while (lo < up) {  /* loop for tail recursion */
    IdxT p;  /* Pivot index */
    IdxT n;  /* to be used later */
    /* sort elements 'lo', 'p', and 'up' */
    lua_geti(L, 1, lo);
    lua_geti(L, 1, up);
    if (sort_comp(L, -1, -2))  /* a[up] < a[lo]? */
      set2(L, lo, up);  /* swap a[lo] - a[up] */
    else
      lua_pop(L, 2);  /* remove both values */
    if (up - lo == 1)  /* only 2 elements? */
      return;  /* already sorted */
    if (up - lo < RANLIMIT || rnd == 0)  /* small interval or no randomize? */
      p = (lo + up)/2;  /* middle element is a good pivot */
    else  /* for larger intervals, it is worth a random pivot */
      p = choosePivot(lo, up, rnd);
    lua_geti(L, 1, p);
    lua_geti(L, 1, lo);
    if (sort_comp(L, -2, -1))  /* a[p] < a[lo]? */
      set2(L, p, lo);  /* swap a[p] - a[lo] */
    else {
      lua_pop(L, 1);  /* remove a[lo] */
      lua_geti(L, 1, up);
      if (sort_comp(L, -1, -2))  /* a[up] < a[p]? */
        set2(L, p, up);  /* swap a[up] - a[p] */
      else
        lua_pop(L, 2);
    }
    if (up - lo == 2)  /* only 3 elements? */
      return;  /* already sorted */
    lua_geti(L, 1, p);  /* get middle element (Pivot) */
    lua_pushvalue(L, -1);  /* push Pivot */
    lua_geti(L, 1, up - 1);  /* push a[up - 1] */
    set2(L, p, up - 1);  /* swap Pivot (a[p]) with a[up - 1] */
    p = partition(L, lo, up);
    /* a[lo .. p - 1] <= a[p] == P <= a[p + 1 .. up] */
    if (p - lo < up - p) {  /* lower interval is smaller? */
      auxsort(L, lo, p - 1, rnd);  /* call recursively for lower interval */
      n = p - lo;  /* size of smaller interval */
      lo = p + 1;  /* tail call for [p + 1 .. up] (upper interval) */
    }
    else {
      auxsort(L, p + 1, up, rnd);  /* call recursively for upper interval */
      n = up - p;  /* size of smaller interval */
      up = p - 1;  /* tail call for [lo .. p - 1]  (lower interval) */
    }
    if ((up - lo) / 128 > n) /* partition too imbalanced? */
      rnd = l_randomizePivot();  /* try a new randomization */
  }  /* tail call auxsort(L, lo, up, rnd) */
}
References auxsort(), choosePivot(), l_randomizePivot(), lua_geti(), lua_pop, lua_pushvalue(), partition(), RANLIMIT, set2(), and sort_comp().
Referenced by auxsort(), and sort().
checkfield()
static int checkfield (lua_State * L, const char * key, int n) static
Definition at line 36 of file lua-5.3.6/src/ltablib.c.
{
  lua_pushstring(L, key);
  return (lua_rawget(L, -n) != LUA_TNIL);
}
References lua_pushstring(), lua_rawget(), and LUA_TNIL.
Referenced by checktab().
checktab()
static void checktab (lua_State * L, int arg, int what) static
Definition at line 46 of file lua-5.3.6/src/ltablib.c.
{
  if (lua_type(L, arg) != LUA_TTABLE) {  /* is it not a table? */
    int n = 1;  /* number of elements to pop */
    if (lua_getmetatable(L, arg) &&  /* must have metatable */
        (!(what & TAB_R) || checkfield(L, "__index", ++n)) &&
        (!(what & TAB_W) || checkfield(L, "__newindex", ++n)) &&
        (!(what & TAB_L) || checkfield(L, "__len", ++n))) {
      lua_pop(L, n);  /* pop metatable and tested metamethods */
    }
    else
      luaL_checktype(L, arg, LUA_TTABLE);  /* force an error */
  }
}
References arg, checkfield(), lua_getmetatable(), lua_pop, LUA_TTABLE, lua_type(), luaL_checktype(), TAB_L, TAB_R, and TAB_W.
Referenced by tmove().
choosePivot()
static IdxT choosePivot (IdxT lo, IdxT up, unsigned int rnd) static
Definition at line 346 of file lua-5.3.6/src/ltablib.c.
{
  IdxT r4 = (up - lo) / 4;  /* range/4 */
  IdxT p = rnd % (r4 * 2) + (lo + r4);
  lua_assert(lo + r4 <= p && p <= up - r4);
  return p;
}
References lua_assert.
Referenced by auxsort().
l_randomizePivot()
static unsigned int l_randomizePivot (void) static
Definition at line 258 of file lua-5.3.6/src/ltablib.c.
{
  clock_t c = clock();
  time_t t = time(NULL);
  unsigned int buff[sof(c) + sof(t)];
  unsigned int i, rnd = 0;
  memcpy(buff, &c, sof(c) * sizeof(unsigned int));
  memcpy(buff + sof(c), &t, sof(t) * sizeof(unsigned int));
  for (i = 0; i < sof(buff); i++)
    rnd += buff[i];
  return rnd;
}
References NULL, and sof.
Referenced by auxsort().
luaopen_table()
LUAMOD_API int luaopen_table (lua_State * L)
Definition at line 441 of file lua-5.3.6/src/ltablib.c.
{
  luaL_newlib(L, tab_funcs);
#if defined(LUA_COMPAT_UNPACK)
  /* _G.unpack = table.unpack */
  lua_getfield(L, -1, "unpack");
  lua_setglobal(L, "unpack");
#endif
  return 1;
}
References lua_getfield(), lua_setglobal, luaL_newlib, and tab_funcs.
pack()
static int pack (lua_State * L) static
Definition at line 194 of file lua-5.3.6/src/ltablib.c.
{
  int i;
  int n = lua_gettop(L);  /* number of elements to pack */
  lua_createtable(L, n, 1);  /* create result table */
  lua_insert(L, 1);  /* put it at index 1 */
  for (i = n; i >= 1; i--)  /* assign elements */
    lua_seti(L, 1, i);
  lua_pushinteger(L, n);
  lua_setfield(L, 1, "n");  /* t.n = number of elements */
  return 1;  /* return table */
}
References lua_createtable(), lua_gettop(), lua_insert, lua_pushinteger(), lua_setfield(), and lua_seti().
partition()
static IdxT partition (lua_State * L, IdxT lo, IdxT up) static
Definition at line 310 of file lua-5.3.6/src/ltablib.c.
{
  IdxT i = lo;  /* will be incremented before first use */
  IdxT j = up - 1;  /* will be decremented before first use */
  /* loop invariant: a[lo .. i] <= P <= a[j .. up] */
  for (;;) {
    /* next loop: repeat ++i while a[i] < P */
    while (lua_geti(L, 1, ++i), sort_comp(L, -1, -2)) {
      if (i == up - 1)  /* a[i] < P  but a[up - 1] == P  ?? */
        luaL_error(L, "invalid order function for sorting");
      lua_pop(L, 1);  /* remove a[i] */
    }
    /* after the loop, a[i] >= P and a[lo .. i - 1] < P */
    /* next loop: repeat --j while P < a[j] */
    while (lua_geti(L, 1, --j), sort_comp(L, -3, -1)) {
      if (j < i)  /* j < i  but  a[j] > P ?? */
        luaL_error(L, "invalid order function for sorting");
      lua_pop(L, 1);  /* remove a[j] */
    }
    /* after the loop, a[j] <= P and a[j + 1 .. up] >= P */
    if (j < i) {  /* no elements out of place? */
      /* a[lo .. i - 1] <= P <= a[j + 1 .. i .. up] */
      lua_pop(L, 1);  /* pop a[j] */
      /* swap pivot (a[up - 1]) with a[i] to satisfy pos-condition */
      set2(L, up - 1, i);
      return i;
    }
    /* otherwise, swap a[i] - a[j] to restore invariant and repeat */
    set2(L, i, j);
  }
}
References lua_geti(), lua_pop, luaL_error(), set2(), and sort_comp().
Referenced by auxsort().
set2()
static void set2 (lua_State * L, IdxT i, IdxT j) static
Definition at line 277 of file lua-5.3.6/src/ltablib.c.
{
  lua_seti(L, 1, i);
  lua_seti(L, 1, j);
}
References lua_seti().
Referenced by auxsort(), and partition().
sort()
static int sort (lua_State * L) static
Definition at line 411 of file lua-5.3.6/src/ltablib.c.
{
  lua_Integer n = aux_getn(L, 1, TAB_RW);
  if (n > 1) {  /* non-trivial interval? */
    luaL_argcheck(L, n < INT_MAX, 1, "array too big");
    if (!lua_isnoneornil(L, 2))  /* is there a 2nd argument? */
      luaL_checktype(L, 2, LUA_TFUNCTION);  /* must be a function */
    lua_settop(L, 2);  /* make sure there are two arguments */
    auxsort(L, 1, (IdxT)n, 0);
  }
  return 0;
}
References aux_getn, auxsort(), lua_isnoneornil, lua_settop(), LUA_TFUNCTION, luaL_argcheck, luaL_checktype(), and TAB_RW.
sort_comp()
static int sort_comp (lua_State * L, int a, int b) static
Definition at line 287 of file lua-5.3.6/src/ltablib.c.
{
  if (lua_isnil(L, 2))  /* no function? */
    return lua_compare(L, a, b, LUA_OPLT);  /* a < b */
  else {  /* function */
    int res;
    lua_pushvalue(L, 2);    /* push function */
    lua_pushvalue(L, a-1);  /* -1 to compensate function */
    lua_pushvalue(L, b-2);  /* -2 to compensate function and 'a' */
    lua_call(L, 2, 1);      /* call function */
    res = lua_toboolean(L, -1);  /* get result */
    lua_pop(L, 1);          /* pop result */
    return res;
  }
}
References lua_call, lua_compare(), lua_isnil, LUA_OPLT, lua_pop, lua_pushvalue(), and lua_toboolean().
Referenced by auxsort(), and partition().
tconcat()
static int tconcat (lua_State * L) static
Definition at line 169 of file lua-5.3.6/src/ltablib.c.
{
  luaL_Buffer b;
  lua_Integer last = aux_getn(L, 1, TAB_R);
  size_t lsep;
  const char *sep = luaL_optlstring(L, 2, "", &lsep);
  lua_Integer i = luaL_optinteger(L, 3, 1);
  last = luaL_optinteger(L, 4, last);
  luaL_buffinit(L, &b);
  for (; i < last; i++) {
    addfield(L, &b, i);
    luaL_addlstring(&b, sep, lsep);
  }
  if (i == last)  /* add last value (if interval was not empty) */
    addfield(L, &b, i);
  luaL_pushresult(&b);
  return 1;
}
References addfield(), aux_getn, luaL_addlstring(), luaL_buffinit(), luaL_optinteger(), luaL_optlstring(), luaL_pushresult(), and TAB_R.
tinsert()
static int tinsert (lua_State * L) static
Definition at line 79 of file lua-5.3.6/src/ltablib.c.
{
  lua_Integer e = aux_getn(L, 1, TAB_RW) + 1;  /* first empty element */
  lua_Integer pos;  /* where to insert new element */
  switch (lua_gettop(L)) {
    case 2: {  /* called with only 2 arguments */
      pos = e;  /* insert new element at the end */
      break;
    }
    case 3: {
      lua_Integer i;
      pos = luaL_checkinteger(L, 2);  /* 2nd argument is the position */
      luaL_argcheck(L, 1 <= pos && pos <= e, 2, "position out of bounds");
      for (i = e; i > pos; i--) {  /* move up elements */
        lua_geti(L, 1, i - 1);
        lua_seti(L, 1, i);  /* t[i] = t[i - 1] */
      }
      break;
    }
    default: {
      return luaL_error(L, "wrong number of arguments to 'insert'");
    }
  }
  lua_seti(L, 1, pos);  /* t[pos] = v */
  return 0;
}
References aux_getn, lua_geti(), lua_gettop(), lua_seti(), luaL_argcheck, luaL_checkinteger(), luaL_error(), and TAB_RW.
tmove()
static int tmove (lua_State * L) static
Definition at line 128 of file lua-5.3.6/src/ltablib.c.
{
  lua_Integer f = luaL_checkinteger(L, 2);
  lua_Integer e = luaL_checkinteger(L, 3);
  lua_Integer t = luaL_checkinteger(L, 4);
  int tt = !lua_isnoneornil(L, 5) ? 5 : 1;  /* destination table */
  checktab(L, 1, TAB_R);
  checktab(L, tt, TAB_W);
  if (e >= f) {  /* otherwise, nothing to move */
    lua_Integer n, i;
    luaL_argcheck(L, f > 0 || e < LUA_MAXINTEGER + f, 3,
                  "too many elements to move");
    n = e - f + 1;  /* number of elements to move */
    luaL_argcheck(L, t <= LUA_MAXINTEGER - n + 1, 4,
                  "destination wrap around");
    if (t > e || t <= f || (tt != 1 && !lua_compare(L, 1, tt, LUA_OPEQ))) {
      for (i = 0; i < n; i++) {
        lua_geti(L, 1, f + i);
        lua_seti(L, tt, t + i);
      }
    }
    else {
      for (i = n - 1; i >= 0; i--) {
        lua_geti(L, 1, f + i);
        lua_seti(L, tt, t + i);
      }
    }
  }
  lua_pushvalue(L, tt);  /* return destination table */
  return 1;
}
References checktab(), lua_compare(), lua_geti(), lua_isnoneornil, LUA_OPEQ, lua_pushvalue(), lua_seti(), luaL_argcheck, luaL_checkinteger(), TAB_R, and TAB_W.
tremove()
static int tremove (lua_State * L) static
Definition at line 106 of file lua-5.3.6/src/ltablib.c.
{
  lua_Integer size = aux_getn(L, 1, TAB_RW);
  lua_Integer pos = luaL_optinteger(L, 2, size);
  if (pos != size)  /* validate 'pos' if given */
    luaL_argcheck(L, 1 <= pos && pos <= size + 1, 1, "position out of bounds");
  lua_geti(L, 1, pos);  /* result = t[pos] */
  for ( ; pos < size; pos++) {
    lua_geti(L, 1, pos + 1);
    lua_seti(L, 1, pos);  /* t[pos] = t[pos + 1] */
  }
  lua_pushnil(L);
  lua_seti(L, 1, pos);  /* t[pos] = nil */
  return 1;
}
References aux_getn, lua_geti(), lua_pushnil(), lua_seti(), luaL_argcheck, luaL_optinteger(), and TAB_RW.
unpack()
static int unpack (lua_State * L) static
Definition at line 207 of file lua-5.3.6/src/ltablib.c.
{
  lua_Unsigned n;
  lua_Integer i = luaL_optinteger(L, 2, 1);
  lua_Integer e = luaL_opt(L, luaL_checkinteger, 3, luaL_len(L, 1));
  if (i > e) return 0;  /* empty range */
  n = (lua_Unsigned)e - i;  /* number of elements minus 1 (avoid overflows) */
  if (n >= (unsigned int)INT_MAX  || !lua_checkstack(L, (int)(++n)))
    return luaL_error(L, "too many results to unpack");
  for (; i < e; i++) {  /* push arg[i..e - 1] (to avoid overflows) */
    lua_geti(L, 1, i);
  }
  lua_geti(L, 1, e);  /* push last element */
  return (int)n;
}
References lua_checkstack(), lua_geti(), luaL_checkinteger(), luaL_error(), luaL_len(), luaL_opt, and luaL_optinteger().
Variable Documentation
tab_funcs
const luaL_Reg tab_funcs[] static
Initial value:
= {
  {"concat", tconcat},
  {"insert", tinsert},
  {"pack", pack},
  {"unpack", unpack},
  {"remove", tremove},
  {"move", tmove},
  {"sort", sort},
  {NULL, NULL}
}
Definition at line 426 of file lua-5.3.6/src/ltablib.c.
{
  {"concat", tconcat},
#if defined(LUA_COMPAT_MAXN)
  {"maxn", maxn},
#endif
  {"insert", tinsert},
  {"pack", pack},
  {"unpack", unpack},
  {"remove", tremove},
  {"move", tmove},
  {"sort", sort},
  {NULL, NULL}
};
Referenced by luaopen_table().