Github User Fetcher: lmathlib.c File Reference
lmathlib.c File Reference
#include <stdlib.h>
#include <math.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lmathlib_c
#define LUA_LIB
#define PI ((lua_Number)(3.1415926535897932384626433832795))
#define RADIANS_PER_DEGREE ((lua_Number)(PI/180.0))
Functions
static int math_abs (lua_State *L)
static int math_sin (lua_State *L)
static int math_sinh (lua_State *L)
static int math_cos (lua_State *L)
static int math_cosh (lua_State *L)
static int math_tan (lua_State *L)
static int math_tanh (lua_State *L)
static int math_asin (lua_State *L)
static int math_acos (lua_State *L)
static int math_atan (lua_State *L)
static int math_atan2 (lua_State *L)
static int math_ceil (lua_State *L)
static int math_floor (lua_State *L)
static int math_fmod (lua_State *L)
static int math_modf (lua_State *L)
static int math_sqrt (lua_State *L)
static int math_pow (lua_State *L)
static int math_log (lua_State *L)
static int math_exp (lua_State *L)
static int math_deg (lua_State *L)
static int math_rad (lua_State *L)
static int math_frexp (lua_State *L)
static int math_ldexp (lua_State *L)
static int math_min (lua_State *L)
static int math_max (lua_State *L)
static int math_random (lua_State *L)
static int math_randomseed (lua_State *L)
LUAMOD_API int luaopen_math (lua_State *L)
Variables
static const luaL_Reg mathlib []
Macro Definition Documentation
lmathlib_c
#define lmathlib_c
Definition at line 11 of file lua-5.2.4/src/lmathlib.c.
LUA_LIB
#define LUA_LIB
Definition at line 12 of file lua-5.2.4/src/lmathlib.c.
PI
#define PI ((lua_Number)(3.1415926535897932384626433832795))
Definition at line 21 of file lua-5.2.4/src/lmathlib.c.
Referenced by luaopen_math().
RADIANS_PER_DEGREE
#define RADIANS_PER_DEGREE ((lua_Number)(PI/180.0))
Definition at line 22 of file lua-5.2.4/src/lmathlib.c.
Referenced by math_deg(), and math_rad().
Function Documentation
luaopen_math()
LUAMOD_API int luaopen_math (lua_State * L)
Definition at line 271 of file lua-5.2.4/src/lmathlib.c.
{
  luaL_newlib(L, mathlib);
  lua_pushnumber(L, PI);
  lua_setfield(L, -2, "pi");
  lua_pushnumber(L, HUGE_VAL);
  lua_setfield(L, -2, "huge");
  return 1;
}
References lua_pushnumber(), lua_setfield(), luaL_newlib, mathlib, and PI.
math_abs()
static int math_abs (lua_State * L) static
Definition at line 26 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(fabs)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_acos()
static int math_acos (lua_State * L) static
Definition at line 66 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(acos)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_asin()
static int math_asin (lua_State * L) static
Definition at line 61 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(asin)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_atan()
static int math_atan (lua_State * L) static
Definition at line 71 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(atan)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_atan2()
static int math_atan2 (lua_State * L) static
Definition at line 76 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(atan2)(luaL_checknumber(L, 1),
                                luaL_checknumber(L, 2)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_ceil()
static int math_ceil (lua_State * L) static
Definition at line 82 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(ceil)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_cos()
static int math_cos (lua_State * L) static
Definition at line 41 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(cos)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_cosh()
static int math_cosh (lua_State * L) static
Definition at line 46 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(cosh)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_deg()
static int math_deg (lua_State * L) static
Definition at line 144 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, luaL_checknumber(L, 1)/RADIANS_PER_DEGREE);
  return 1;
}
References lua_pushnumber(), luaL_checknumber(), and RADIANS_PER_DEGREE.
math_exp()
static int math_exp (lua_State * L) static
Definition at line 139 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(exp)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_floor()
static int math_floor (lua_State * L) static
Definition at line 87 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(floor)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_fmod()
static int math_fmod (lua_State * L) static
Definition at line 92 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(fmod)(luaL_checknumber(L, 1),
                               luaL_checknumber(L, 2)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_frexp()
static int math_frexp (lua_State * L) static
Definition at line 154 of file lua-5.2.4/src/lmathlib.c.
{
  int e;
  lua_pushnumber(L, l_mathop(frexp)(luaL_checknumber(L, 1), &e));
  lua_pushinteger(L, e);
  return 2;
}
References l_mathop, lua_pushinteger(), lua_pushnumber(), and luaL_checknumber().
math_ldexp()
static int math_ldexp (lua_State * L) static
Definition at line 161 of file lua-5.2.4/src/lmathlib.c.
{
  lua_Number x = luaL_checknumber(L, 1);
  int ep = luaL_checkint(L, 2);
  lua_pushnumber(L, l_mathop(ldexp)(x, ep));
  return 1;
}
References l_mathop, lua_pushnumber(), luaL_checkint, and luaL_checknumber().
math_log()
static int math_log (lua_State * L) static
Definition at line 118 of file lua-5.2.4/src/lmathlib.c.
{
  lua_Number x = luaL_checknumber(L, 1);
  lua_Number res;
  if (lua_isnoneornil(L, 2))
    res = l_mathop(log)(x);
  else {
    lua_Number base = luaL_checknumber(L, 2);
    if (base == (lua_Number)10.0) res = l_mathop(log10)(x);
    else res = l_mathop(log)(x)/l_mathop(log)(base);
  }
  lua_pushnumber(L, res);
  return 1;
}
References l_mathop, lua_isnoneornil, lua_pushnumber(), and luaL_checknumber().
math_max()
static int math_max (lua_State * L) static
Definition at line 184 of file lua-5.2.4/src/lmathlib.c.
{
  int n = lua_gettop(L);  /* number of arguments */
  lua_Number dmax = luaL_checknumber(L, 1);
  int i;
  for (i=2; i<=n; i++) {
    lua_Number d = luaL_checknumber(L, i);
    if (d > dmax)
      dmax = d;
  }
  lua_pushnumber(L, dmax);
  return 1;
}
References lua_gettop(), lua_pushnumber(), and luaL_checknumber().
math_min()
static int math_min (lua_State * L) static
Definition at line 170 of file lua-5.2.4/src/lmathlib.c.
{
  int n = lua_gettop(L);  /* number of arguments */
  lua_Number dmin = luaL_checknumber(L, 1);
  int i;
  for (i=2; i<=n; i++) {
    lua_Number d = luaL_checknumber(L, i);
    if (d < dmin)
      dmin = d;
  }
  lua_pushnumber(L, dmin);
  return 1;
}
References lua_gettop(), lua_pushnumber(), and luaL_checknumber().
math_modf()
static int math_modf (lua_State * L) static
Definition at line 98 of file lua-5.2.4/src/lmathlib.c.
{
  lua_Number ip;
  lua_Number fp = l_mathop(modf)(luaL_checknumber(L, 1), &ip);
  lua_pushnumber(L, ip);
  lua_pushnumber(L, fp);
  return 2;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_pow()
static int math_pow (lua_State * L) static
Definition at line 111 of file lua-5.2.4/src/lmathlib.c.
{
  lua_Number x = luaL_checknumber(L, 1);
  lua_Number y = luaL_checknumber(L, 2);
  lua_pushnumber(L, l_mathop(pow)(x, y));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_rad()
static int math_rad (lua_State * L) static
Definition at line 149 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, luaL_checknumber(L, 1)*RADIANS_PER_DEGREE);
  return 1;
}
References lua_pushnumber(), luaL_checknumber(), and RADIANS_PER_DEGREE.
math_random()
static int math_random (lua_State * L) static
Definition at line 198 of file lua-5.2.4/src/lmathlib.c.
{
  /* the `%' avoids the (rare) case of r==1, and is needed also because on
     some systems (SunOS!) `rand()' may return a value larger than RAND_MAX */
  lua_Number r = (lua_Number)(rand()%RAND_MAX) / (lua_Number)RAND_MAX;
  switch (lua_gettop(L)) {  /* check number of arguments */
    case 0: {  /* no arguments */
      lua_pushnumber(L, r);  /* Number between 0 and 1 */
      break;
    }
    case 1: {  /* only upper limit */
      lua_Number u = luaL_checknumber(L, 1);
      luaL_argcheck(L, (lua_Number)1.0 <= u, 1, "interval is empty");
      lua_pushnumber(L, l_mathop(floor)(r*u) + (lua_Number)(1.0));  /* [1, u] */
      break;
    }
    case 2: {  /* lower and upper limits */
      lua_Number l = luaL_checknumber(L, 1);
      lua_Number u = luaL_checknumber(L, 2);
      luaL_argcheck(L, l <= u, 2, "interval is empty");
      lua_pushnumber(L, l_mathop(floor)(r*(u-l+1)) + l);  /* [l, u] */
      break;
    }
    default: return luaL_error(L, "wrong number of arguments");
  }
  return 1;
}
References l_mathop, lua_gettop(), lua_pushnumber(), luaL_argcheck, luaL_checknumber(), and luaL_error().
math_randomseed()
static int math_randomseed (lua_State * L) static
Definition at line 226 of file lua-5.2.4/src/lmathlib.c.
{
  srand(luaL_checkunsigned(L, 1));
  (void)rand(); /* discard first value to avoid undesirable correlations */
  return 0;
}
References luaL_checkunsigned().
math_sin()
static int math_sin (lua_State * L) static
Definition at line 31 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(sin)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_sinh()
static int math_sinh (lua_State * L) static
Definition at line 36 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(sinh)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_sqrt()
static int math_sqrt (lua_State * L) static
Definition at line 106 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(sqrt)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_tan()
static int math_tan (lua_State * L) static
Definition at line 51 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(tan)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
math_tanh()
static int math_tanh (lua_State * L) static
Definition at line 56 of file lua-5.2.4/src/lmathlib.c.
{
  lua_pushnumber(L, l_mathop(tanh)(luaL_checknumber(L, 1)));
  return 1;
}
References l_mathop, lua_pushnumber(), and luaL_checknumber().
Variable Documentation
mathlib
const luaL_Reg mathlib[] static
Definition at line 233 of file lua-5.2.4/src/lmathlib.c.
{
  {"abs",   math_abs},
  {"acos",  math_acos},
  {"asin",  math_asin},
  {"atan2", math_atan2},
  {"atan",  math_atan},
  {"ceil",  math_ceil},
  {"cosh",   math_cosh},
  {"cos",   math_cos},
  {"deg",   math_deg},
  {"exp",   math_exp},
  {"floor", math_floor},
  {"fmod",   math_fmod},
  {"frexp", math_frexp},
  {"ldexp", math_ldexp},
#if defined(LUA_COMPAT_LOG10)
  {"log10", math_log10},
#endif
  {"log",   math_log},
  {"max",   math_max},
  {"min",   math_min},
  {"modf",   math_modf},
  {"pow",   math_pow},
  {"rad",   math_rad},
  {"random",     math_random},
  {"randomseed", math_randomseed},
  {"sinh",   math_sinh},
  {"sin",   math_sin},
  {"sqrt",  math_sqrt},
  {"tanh",   math_tanh},
  {"tan",   math_tan},
  {NULL, NULL}
};
Referenced by luaopen_math().