Github User Fetcher: LuaXML_lib.h File Reference
LuaXML_lib.h File Reference
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
Macros
#define LUAXML_DEBUG 0 /* set to 1 to enable debugging output */
#define _EXPORT
Functions
int _EXPORT luaopen_LuaXML_lib (lua_State *L)
Macro Definition Documentation
_EXPORT
#define _EXPORT
Definition at line 20 of file LuaXML_lib.h.
LUAXML_DEBUG
#define LUAXML_DEBUG 0 /* set to 1 to enable debugging output */
Definition at line 5 of file LuaXML_lib.h.
Function Documentation
luaopen_LuaXML_lib()
int _EXPORT luaopen_LuaXML_lib (lua_State * L)
Definition at line 1280 of file LuaXML_lib.c.
{
    static const struct luaL_Reg funcs[] = {{"append", Xml_append},
                                            {"decode", Xml_decode},
                                            {"encode", Xml_encode},
                                            {"eval", Xml_eval},
                                            {"find", Xml_find},
                                            {"iterate", Xml_iterate},
                                            {"load", Xml_load},
                                            {"match", Xml_match},
                                            {"new", Xml_new},
                                            {"registerCode", Xml_registerCode},
                                            {"str", Xml_str},
                                            {"tag", Xml_tag},
                                            {NULL, NULL}};
    luaL_newlib(L, funcs);
    // create a metatable for LuaXML "objects"
    luaL_newmetatable(L, LUAXML_META);
    lua_pushliteral(L, "__index");
    lua_pushvalue(L, -3); // duplicate the module table
    lua_rawset(L, -3);    // and set it as metaindex
    lua_pushliteral(L, "__tostring");
    lua_pushcfunction(L, Xml_str);
    lua_rawset(L, -3); // set metamethod
    lua_pop(L, 1);     // drop value (metatable)
    // expose API constants (via the module table)
    lua_pushinteger(L, WHITESPACE_TRIM);
    lua_setfield(L, -2, "WS_TRIM");
    lua_pushinteger(L, WHITESPACE_NORMALIZE);
    lua_setfield(L, -2, "WS_NORMALIZE");
    lua_pushinteger(L, WHITESPACE_PRESERVE);
    lua_setfield(L, -2, "WS_PRESERVE");
    // register default codes
    // Note: We'll always handle "&amp;" separately!
    lua_newtable(L);
    lua_pushliteral(L, "&lt;");
    lua_setfield(L, -2, "<");
    lua_pushliteral(L, "&gt;");
    lua_setfield(L, -2, ">");
    lua_pushliteral(L, "&quot;");
    lua_setfield(L, -2, "\"");
    lua_pushliteral(L, "&apos;");
    lua_setfield(L, -2, "'");
    sv_code_ref = luaL_ref(L, LUA_REGISTRYINDEX); // reference (and pop table)
    return 1; // return module (table)
}
References funcs, lua_newtable, lua_pop, lua_pushcfunction, lua_pushinteger(), lua_pushliteral, lua_pushvalue(), lua_rawset(), LUA_REGISTRYINDEX, lua_setfield(), luaL_newlib, luaL_newmetatable(), luaL_ref(), LUAXML_META, NULL, sv_code_ref, WHITESPACE_NORMALIZE, WHITESPACE_PRESERVE, WHITESPACE_TRIM, Xml_append(), Xml_decode(), Xml_encode(), Xml_eval(), Xml_find(), Xml_iterate(), Xml_load(), Xml_match(), Xml_new(), Xml_registerCode(), Xml_str(), and Xml_tag().