Github User Fetcher: min.c File Reference
min.c File Reference
#include <stdio.h>
#include "lua.h"
#include "lauxlib.h"
Functions
static int print (lua_State *L)
int main (void)
Function Documentation
main()
int main (void)
Definition at line 32 of file min.c.
{
 lua_State *L=lua_open();
 lua_register(L,"print",print);
 if (luaL_dofile(L,NULL)!=0) fprintf(stderr,"%s\n",lua_tostring(L,-1));
 lua_close(L);
 return 0;
}
References lua_close(), lua_open, lua_register, lua_tostring, luaL_dofile, NULL, and print().
print()
static int print (lua_State * L) static
Definition at line 12 of file min.c.
{
 int n=lua_gettop(L);
 int i;
 for (i=1; i<=n; i++)
 {
  if (i>1) printf("\t");
  if (lua_isstring(L,i))
   printf("%s",lua_tostring(L,i));
  else if (lua_isnil(L,i))
   printf("%s","nil");
  else if (lua_isboolean(L,i))
   printf("%s",lua_toboolean(L,i) ? "true" : "false");
  else
   printf("%s:%p",luaL_typename(L,i),lua_topointer(L,i));
 }
 printf("\n");
 return 0;
}
References lua_gettop(), lua_isboolean, lua_isnil, lua_isstring(), lua_toboolean(), lua_topointer(), lua_tostring, luaL_typename, and printf.
Referenced by main().