Github User Fetcher: noparser.c File Reference
noparser.c File Reference
#include "llex.h"
#include "lparser.h"
#include "lzio.h"
Macros
#define LUA_CORE
Functions
LUAI_FUNC void luaX_init (lua_State *L)
LUAI_FUNC Proto * luaY_parser (lua_State *L, ZIO *z, Mbuffer *buff, const char *name)
Macro Definition Documentation
LUA_CORE
#define LUA_CORE
Definition at line 15 of file noparser.c.
Function Documentation
luaX_init()
LUAI_FUNC void luaX_init (lua_State * L)
Definition at line 21 of file noparser.c.
{
  UNUSED(L);
}
References UNUSED.
Referenced by f_luaopen(), f_luaopen(), f_luaopen(), and f_luaopen().
luaY_parser()
LUAI_FUNC Proto * luaY_parser (lua_State * L, ZIO * z, Mbuffer * buff, const char * name)
Definition at line 25 of file noparser.c.
{
  UNUSED(z);
  UNUSED(buff);
  UNUSED(name);
  lua_pushliteral(L,"parser not loaded");
  lua_error(L);
  return NULL;
}
References lua_error(), lua_pushliteral, name, NULL, and UNUSED.
Referenced by f_parser(), f_parser(), f_parser(), and f_parser().