Github User Fetcher: server.c File Reference
server.c File Reference
Implements a simple HTTP server using Civetweb to serve GitHub user information.
#include "server.h"
#include "../vendor/civetweb/civetweb.h"
#include "user.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
static int user_handler (struct mg_connection *conn, void *cbdata)
HTTP request handler for user lookup.
void start_http_server (int port)
Starts an HTTP server on the specified port.
Detailed Description
Implements a simple HTTP server using Civetweb to serve GitHub user information.
Definition in file server.c.
Function Documentation
start_http_server()
void start_http_server (int port)
Starts an HTTP server on the specified port.
Starts the HTTP server.
Configures Civetweb with basic options and handles incoming user requests. The server runs indefinitely until manually interrupted.
Parameters
port The TCP port to listen on.
Definition at line 59 of file server.c.
{
  char *port_str = NULL;
  if (asprintf(&port_str, "%d", port) == -1) {
    (void)fprintf(stderr, "Failed to allocate memory for port\n");
    return;
  }
  const char *options[] = {"listening_ports",
                           port_str,
                           "enable_keep_alive",
                           "yes",
                           "access_log_file",
                           "access.log",
                           NULL};
  struct mg_callbacks callbacks = {0};
  struct mg_context *ctx = mg_start(&callbacks, NULL, options);
  if (!ctx) {
    (void)fprintf(stderr, "Failed to start Civetweb server\n");
    return;
  }
  mg_set_request_handler(ctx, "/", user_handler, NULL);
  printf("Server started on port %s. Visit http://localhost:%s/USERNAME\n",
         port_str, port_str);
  puts("Press Ctrl+C to quit.");
  free(port_str);
  // Keep running (or use signal handler in future)
  while (1) {
    sleep(1);
  }
  mg_stop(ctx);
}
References mg_context::callbacks, free, mg_set_request_handler(), mg_start(), mg_stop(), NULL, printf, and user_handler().
Referenced by main().
user_handler()
static int user_handler (struct mg_connection * conn, void * cbdata) static
HTTP request handler for user lookup.
Parses the request URI to extract the username, fetches the corresponding GitHub user, and responds with a JSON object.
Parameters
conn The connection to the client.
cbdata Callback data (unused).
Returns
HTTP status code (e.g., 200 for success, 400 for bad request).
Definition at line 26 of file server.c.
{
  (void)cbdata; // Mark parameter as deliberately unused
  const struct mg_request_info *req_info = mg_get_request_info(conn);
  const char *uri = req_info->local_uri;
  // Validate that the URI is valid and null-terminated
  size_t uri_len = strnlen(uri, 1024); // Limit max length to avoid over-read
  if (uri_len < 2) {
    mg_printf(conn, "HTTP/1.1 400 Bad Request\r\nContent-Type: "
                    "text/plain\r\n\r\nMissing username\n");
    return 400;
  }
  const char *username = uri + 1; // skip the initial '/'
  User user = fetch_github_user(username);
  mg_printf(conn, "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n");
  mg_printf(conn,
            "{\n  \"login\": \"%s\",\n  \"name\": \"%s\",\n  \"company\": "
            "\"%s\",\n  \"location\": \"%s\"\n}\n",
            user.login, user.name, user.company, user.location);
  return 200;
}
References User::company, fetch_github_user(), mg_request_info::local_uri, User::location, User::login, mg_get_request_info(), mg_printf(), and User::name.
Referenced by start_http_server().