Github User Fetcher: mg_callbacks Struct Reference
mg_callbacks Struct Reference
#include <civetweb.h>
Data Fields
int(* begin_request)(struct mg_connection *)
void(* end_request)(const struct mg_connection *, int reply_status_code)
int(* log_message)(const struct mg_connection *, const char *message)
int(* log_access)(const struct mg_connection *, const char *message)
int(* init_ssl)(void *ssl_ctx, void *user_data)
int(* init_ssl_domain)(const char *server_domain, void *ssl_ctx, void *user_data)
int(* external_ssl_ctx)(void **ssl_ctx, void *user_data)
int(* external_ssl_ctx_domain)(const char *server_domain, void **ssl_ctx, void *user_data)
void(* connection_close)(const struct mg_connection *)
void(* connection_closed)(const struct mg_connection *)
void(* init_lua)(const struct mg_connection *conn, void *lua_context, unsigned context_flags)
void(* exit_lua)(const struct mg_connection *conn, void *lua_context, unsigned context_flags)
int(* http_error)(struct mg_connection *conn, int status, const char *errmsg)
void(* init_context)(const struct mg_context *ctx)
void(* exit_context)(const struct mg_context *ctx)
void *(* init_thread)(const struct mg_context *ctx, int thread_type)
void(* exit_thread)(const struct mg_context *ctx, int thread_type, void *thread_pointer)
int(* init_connection)(const struct mg_connection *conn, void **conn_data)
Detailed Description
Definition at line 218 of file civetweb.h.
Field Documentation
begin_request
int(* mg_callbacks::begin_request) (struct mg_connection *)
Definition at line 233 of file civetweb.h.
Referenced by handle_request().
connection_close
void(* mg_callbacks::connection_close) (const struct mg_connection *)
Definition at line 320 of file civetweb.h.
Referenced by close_connection().
connection_closed
void(* mg_callbacks::connection_closed) (const struct mg_connection *)
Definition at line 330 of file civetweb.h.
Referenced by close_connection().
end_request
void(* mg_callbacks::end_request) (const struct mg_connection *, int reply_status_code)
Definition at line 236 of file civetweb.h.
Referenced by handle_request_stat_log().
exit_context
void(* mg_callbacks::exit_context) (const struct mg_context *ctx)
Definition at line 372 of file civetweb.h.
Referenced by free_context(), and mg_start2().
exit_lua
void(* mg_callbacks::exit_lua) (const struct mg_connection *conn, void *lua_context, unsigned context_flags)
Definition at line 345 of file civetweb.h.
exit_thread
void(* mg_callbacks::exit_thread) (const struct mg_context *ctx, int thread_type, void *thread_pointer)
Definition at line 400 of file civetweb.h.
Referenced by master_thread_run(), and worker_thread_run().
external_ssl_ctx
int(* mg_callbacks::external_ssl_ctx) (void **ssl_ctx, void *user_data)
Definition at line 278 of file civetweb.h.
Referenced by free_context(), and init_ssl_ctx().
external_ssl_ctx_domain
int(* mg_callbacks::external_ssl_ctx_domain) (const char *server_domain, void **ssl_ctx, void *user_data)
Definition at line 290 of file civetweb.h.
Referenced by init_ssl_ctx().
http_error
int(* mg_callbacks::http_error) (struct mg_connection *conn, int status, const char *errmsg)
Definition at line 359 of file civetweb.h.
Referenced by mg_send_http_error_impl().
init_connection
int(* mg_callbacks::init_connection) (const struct mg_connection *conn, void **conn_data)
Definition at line 417 of file civetweb.h.
Referenced by init_connection().
init_context
void(* mg_callbacks::init_context) (const struct mg_context *ctx)
Definition at line 367 of file civetweb.h.
Referenced by mg_start2().
init_lua
void(* mg_callbacks::init_lua) (const struct mg_connection *conn, void *lua_context, unsigned context_flags)
Definition at line 342 of file civetweb.h.
init_ssl
int(* mg_callbacks::init_ssl) (void *ssl_ctx, void *user_data)
Definition at line 254 of file civetweb.h.
Referenced by init_ssl_ctx(), and init_ssl_ctx_impl().
init_ssl_domain
int(* mg_callbacks::init_ssl_domain) (const char *server_domain, void *ssl_ctx, void *user_data)
Definition at line 265 of file civetweb.h.
Referenced by init_ssl_ctx(), and init_ssl_ctx_impl().
init_thread
void *(* mg_callbacks::init_thread) (const struct mg_context *ctx, int thread_type)
Definition at line 393 of file civetweb.h.
Referenced by master_thread_run(), and worker_thread_run().
log_access
int(* mg_callbacks::log_access) (const struct mg_connection *, const char *message)
Definition at line 244 of file civetweb.h.
Referenced by log_access().
log_message
int(* mg_callbacks::log_message) (const struct mg_connection *, const char *message)
Definition at line 240 of file civetweb.h.
Referenced by mg_cry_internal_impl().
The documentation for this struct was generated from the following file:
civetweb.h