Github User Fetcher: user.h File Reference
user.h File Reference
#include <stddef.h>
Data Structures
struct User
Structure representing a GitHub user.
Functions
User fetch_github_user (const char *username)
Fetch GitHub user information for a given username.
void print_github_user (const User *user)
Print GitHub user information to standard output.
void user_free (User *user)
Free dynamically allocated memory in a User structure.
Function Documentation
fetch_github_user()
User fetch_github_user (const char * username)
Fetch GitHub user information for a given username.
Parameters
username GitHub username to fetch.
Returns
User structure populated with user information.
The returned User must be freed with user_free().
Fetch GitHub user information for a given username.
Parameters
username GitHub username.
Returns
User structure containing fetched information.
The returned User must be freed using user_free().
Definition at line 130 of file user.c.
{
  User user = {0};
  Buffer buffer = {0};
  // Check username for NULL or empty
  if (!username || *username == '\0') {
    (void)fprintf(stderr, "Invalid username\n");
    return user;
  }
  buffer_init(&buffer); // Initialize buffer after username check to avoid leaks
  // Dynamically allocate URL buffer with enough space for the URL
  size_t username_len = strnlen(username, 100); // Limit username length
  size_t url_size =
      username_len + 50; // Account for the API URL length and username
  char *url = malloc(url_size);
  if (!url) {
    (void)fprintf(stderr, "Memory allocation failed for URL\n");
    buffer_cleanup(&buffer);
    return user;
  }
  int ret =
      snprintf(url, url_size, "https://api.github.com/users/%s", username);
  if (ret < 0 || (size_t)ret >= url_size) {
    (void)fprintf(stderr, "Error: URL was truncated or snprintf failed\n");
    free(url);
    buffer_cleanup(&buffer);
    return user;
  }
  CURL *curl = curl_easy_init();
  if (!curl) {
    (void)fprintf(stderr, "curl init failed\n");
    free(url);
    buffer_cleanup(&buffer);
    return user;
  }
  curl_easy_setopt(curl, CURLOPT_URL, url);
  curl_easy_setopt(curl, CURLOPT_USERAGENT, "github_user_fetcher/1.0");
  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_callback);
  curl_easy_setopt(curl, CURLOPT_WRITEDATA, &buffer);
  CURLcode res = curl_easy_perform(curl);
  curl_easy_cleanup(curl);
  free(url); // Free dynamically allocated URL buffer
  if (res != CURLE_OK) {
    (void)fprintf(stderr, "CURL error: %s\n", curl_easy_strerror(res));
    buffer_cleanup(&buffer);
    return user;
  }
  json_error_t error;
  json_t *root = json_loads(buffer.data, 0, &error);
  // Save buffer data before cleanup
  char *buffer_data = buffer.data;
  if (!root) {
    (void)fprintf(stderr, "JSON parse error: %s\n", error.text);
    free(buffer_data);
    return user;
  }
  free(buffer_data); // Free buffer data after successful JSON parsing
  json_t *login = json_object_get(root, "login");
  json_t *name = json_object_get(root, "name");
  json_t *company = json_object_get(root, "company");
  json_t *location = json_object_get(root, "location");
  // Dynamically allocate memory for the user fields
  if (json_is_string(login)) {
    user.login = strdup(
        json_string_value(login)); // Using strdup for dynamic memory allocation
  }
  if (json_is_string(name)) {
    user.name = strdup(json_string_value(name));
  }
  if (json_is_string(company)) {
    user.company = strdup(json_string_value(company));
  }
  if (json_is_string(location)) {
    user.location = strdup(json_string_value(location));
  }
  json_decref(root);
  return user;
}
References buffer_cleanup(), buffer_init(), User::company, curl_easy_cleanup(), curl_easy_init(), curl_easy_perform(), curl_easy_setopt, curl_easy_strerror(), CURLE_OK, Buffer::data, error(), free, json_decref(), json_is_string, json_loads(), json_object_get(), json_string_value(), User::location, User::login, malloc, User::name, name, snprintf, and write_callback().
Referenced by main(), Test(), and user_handler().
print_github_user()
void print_github_user (const User * user)
Print GitHub user information to standard output.
Parameters
user Pointer to a User structure.
Print GitHub user information to standard output.
Parameters
user Pointer to the User structure.
Definition at line 230 of file user.c.
{
  if (!user) {
    (void)fprintf(stderr, "NULL user pointer\n");
    return;
  }
  printf("GitHub User:\n");
  printf("  Login:    %s\n", user->login ? user->login : "N/A");
  printf("  Name:     %s\n", user->name ? user->name : "N/A");
  printf("  Company:  %s\n", user->company ? user->company : "N/A");
  printf("  Location: %s\n", user->location ? user->location : "N/A");
}
References User::company, User::location, User::login, User::name, and printf.
Referenced by BM_PrintUser(), and main().
user_free()
void user_free (User * user)
Free dynamically allocated memory in a User structure.
Parameters
user Pointer to a User structure to free.
After calling, the fields inside User will be set to NULL.
Free dynamically allocated memory in a User structure.
Parameters
user Pointer to User.
After freeing, all pointers are set to NULL.
Definition at line 250 of file user.c.
{
  if (!user) {
    return;
  }
  free(user->login);
  free(user->name);
  free(user->company);
  free(user->location);
  // Zero out pointers after freeing
  user->login = NULL;
  user->name = NULL;
  user->company = NULL;
  user->location = NULL;
}
References User::company, free, User::location, User::login, User::name, and NULL.