Github User Fetcher: main.c File Reference
main.c File Reference
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <signal.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include "civetweb.h"
#include <sys/utsname.h>
#include <sys/wait.h>
#include <unistd.h>
Data Structures
struct tuser_data
Macros
#define _XOPEN_SOURCE 600 /* For PATH_MAX on linux */
#define IGNORE_UNUSED_RESULT(a) ((void)((a) && 1))
#define NO_RETURN
#define _LARGEFILE_SOURCE /* For fseeko(), ftello() */
#define _FILE_OFFSET_BITS 64 /* Use 64-bit file offsets by default */
#define __STDC_FORMAT_MACROS /* <inttypes.h> wants this for C++ */
#define __STDC_LIMIT_MACROS /* C++ wants that for INT64_MAX */
#define printf DO_NOT_USE_THIS_FUNCTION__USE_fprintf /* Required for unit testing */
#define DIRSEP '/'
#define WINCDECL
#define abs_path(rel, abs, abs_size) (realpath((rel), (abs)))
#define DEBUG_ASSERT(cond)
#define PATH_MAX (1024)
#define MAX_OPTIONS (100) /* TODO: Read from civetweb.c ? */
#define MAX_CONF_FILE_LINE_SIZE (8 * 1024)
#define CONFIG_FILE "civetweb.conf"
#define PASSWORDS_FILE_NAME ".htpasswd"
Enumerations
enum {
OPTION_TITLE , OPTION_ICON , OPTION_WEBPAGE , OPTION_ADD_DOMAIN ,
OPTION_HIDE_TRAY , NUM_MAIN_OPTIONS
}
Functions
static void WINCDECL signal_handler (int sig_num)
static NO_RETURN void die (const char *fmt,...)
static void warn (const char *fmt,...)
static void show_server_name (void)
static NO_RETURN void show_usage_and_exit (const char *exeName)
static char * sdup (const char *str)
static const char * get_option (const char **options, const char *option_name)
static int set_option (const char **options, const char *name, const char *value)
static int read_config_file (const char *config_file, const char **options)
static void process_command_line_arguments (int argc, char *argv[], const char **options)
static void init_system_info (void)
static void init_server_name (void)
static void free_system_info (void)
static int is_path_absolute (const char *path)
static int verify_existence (const char **options, const char *option_name, int must_be_dir)
static void set_absolute_path (const char *options[], const char *option_name, const char *path_to_civetweb_exe)
static int run_client (const char *url_arg)
static int sanitize_options (const char *options[], const char *arg0)
static void start_civetweb (int argc, char *argv[])
static void stop_civetweb (void)
int main (int argc, char *argv[])
Variables
volatile int g_exit_flag = 0
static char g_server_base_name [40]
static const char * g_server_name
static const char * g_icon_name
static const char * g_website
static int g_num_add_domains
static const char ** g_add_domain
static int g_hide_tray = 0
static char * g_system_info
static char g_config_file_name [PATH_MAX]
static struct mg_context * g_ctx
static struct tuser_data g_user_data
static struct mg_option main_config_options []
Macro Definition Documentation
__STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS /* <inttypes.h> wants this for C++ */
Definition at line 78 of file vendor/civetweb/main.c.
__STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS /* C++ wants that for INT64_MAX */
Definition at line 81 of file vendor/civetweb/main.c.
_FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64 /* Use 64-bit file offsets by default */
Definition at line 75 of file vendor/civetweb/main.c.
_LARGEFILE_SOURCE
#define _LARGEFILE_SOURCE /* For fseeko(), ftello() */
Definition at line 72 of file vendor/civetweb/main.c.
_XOPEN_SOURCE
#define _XOPEN_SOURCE 600 /* For PATH_MAX on linux */
Definition at line 45 of file vendor/civetweb/main.c.
abs_path
#define abs_path (rel, abs, abs_size) (realpath((rel), (abs)))
Definition at line 146 of file vendor/civetweb/main.c.
Referenced by set_absolute_path().
CONFIG_FILE
#define CONFIG_FILE "civetweb.conf"
Definition at line 212 of file vendor/civetweb/main.c.
Referenced by process_command_line_arguments().
DEBUG_ASSERT
#define DEBUG_ASSERT (cond)
Definition at line 168 of file vendor/civetweb/main.c.
Referenced by init_server_name().
DIRSEP
#define DIRSEP '/'
Definition at line 144 of file vendor/civetweb/main.c.
Referenced by process_command_line_arguments(), and set_absolute_path().
IGNORE_UNUSED_RESULT
#define IGNORE_UNUSED_RESULT (a) ((void)((a) && 1))
Definition at line 57 of file vendor/civetweb/main.c.
Referenced by set_absolute_path().
MAX_CONF_FILE_LINE_SIZE
#define MAX_CONF_FILE_LINE_SIZE (8 * 1024)
Definition at line 177 of file vendor/civetweb/main.c.
Referenced by read_config_file().
MAX_OPTIONS
#define MAX_OPTIONS (100) /* TODO: Read from civetweb.c ? */
Definition at line 176 of file vendor/civetweb/main.c.
Referenced by set_option(), and start_civetweb().
NO_RETURN
#define NO_RETURN
Definition at line 67 of file vendor/civetweb/main.c.
PASSWORDS_FILE_NAME
#define PASSWORDS_FILE_NAME ".htpasswd"
Definition at line 216 of file vendor/civetweb/main.c.
PATH_MAX
#define PATH_MAX (1024)
Definition at line 173 of file vendor/civetweb/main.c.
Referenced by set_absolute_path().
printf
#define printf DO_NOT_USE_THIS_FUNCTION__USE_fprintf /* Required for unit testing */
Definition at line 104 of file vendor/civetweb/main.c.
#define printf                                                                 \
    DO_NOT_USE_THIS_FUNCTION__USE_fprintf /* Required for unit testing */
Referenced by create_duktape_heap(), create_duktape_heap(), doargs(), doargs(), doargs(), doargs(), duk_alloc_hybrid(), duk_alloc_hybrid_init(), duk_free_hybrid(), duk_realloc_hybrid(), main(), main(), my_class::my_class(), print(), print_github_user(), PrintCode(), PrintCode(), PrintCode(), PrintCode(), PrintConstant(), PrintConstant(), PrintConstant(), PrintConstant(), PrintConstants(), PrintDebug(), PrintDebug(), PrintDebug(), PrintHeader(), PrintHeader(), PrintHeader(), PrintHeader(), PrintLocals(), PrintString(), PrintString(), PrintString(), PrintString(), PrintType(), PrintUpvalues(), pthreadMutexTry(), removeUnindexableInClauseTerms(), sqlite3RegisterBuiltinFunctions(), sqlite3RunParser(), sqlite3VdbeExec(), sqlite3WhereEnd(), start_http_server(), test2(), wrapped_compile_execute(), and my_class::~my_class().
WINCDECL
#define WINCDECL
Definition at line 145 of file vendor/civetweb/main.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPTION_TITLE
OPTION_ICON
OPTION_WEBPAGE
OPTION_ADD_DOMAIN
OPTION_HIDE_TRAY
NUM_MAIN_OPTIONS
Definition at line 224 of file vendor/civetweb/main.c.
     {
    OPTION_TITLE,
    OPTION_ICON,
    OPTION_WEBPAGE,
    OPTION_ADD_DOMAIN,
    OPTION_HIDE_TRAY,
#if defined(DAEMONIZE)
    ENABLE_DAEMONIZE,
#endif
    NUM_MAIN_OPTIONS
};
Function Documentation
die()
static NO_RETURN void die (const char * fmt, ...) static
Definition at line 258 of file vendor/civetweb/main.c.
{
    va_list ap;
    char msg[1024] = "";
    va_start(ap, fmt);
    (void)vsnprintf(msg, sizeof(msg) - 1, fmt, ap);
    msg[sizeof(msg) - 1] = 0;
    va_end(ap);
#if defined(_WIN32)
    MessageBox(NULL, msg, "Error", MB_ICONERROR | MB_OK);
#else
    fprintf(stderr, "%s\n", msg);
#endif
    exit(EXIT_FAILURE);
}
References NULL.
Referenced by process_command_line_arguments(), sdup(), set_option(), and start_civetweb().
free_system_info()
static void free_system_info (void) static
Definition at line 856 of file vendor/civetweb/main.c.
{
    free(g_system_info);
}
References free, and g_system_info.
Referenced by main().
get_option()
static const char * get_option (const char ** options, const char * option_name) static
Definition at line 471 of file vendor/civetweb/main.c.
{
    int i = 0;
    const char *opt_value = NULL;
    /* TODO (low, api makeover): options should be an array of key-value-pairs,
     * like
     *     struct {const char * key, const char * value} options[]
     * but it currently is an array with
     *     options[2*i] = key, options[2*i + 1] = value
     * (probably with a MG_LEGACY_INTERFACE definition)
     */
    while (options[2 * i] != NULL) {
        if (strcmp(options[2 * i], option_name) == 0) {
            opt_value = options[2 * i + 1];
            break;
        }
        i++;
    }
    return opt_value;
}
References NULL.
Referenced by set_absolute_path(), and verify_existence().
init_server_name()
static void init_server_name (void) static
Definition at line 838 of file vendor/civetweb/main.c.
{
    DEBUG_ASSERT(sizeof(main_config_options) / sizeof(main_config_options[0])
                 == NUM_MAIN_OPTIONS + 1);
    DEBUG_ASSERT((strlen(mg_version()) + 12) < sizeof(g_server_base_name));
    snprintf(g_server_base_name,
             sizeof(g_server_base_name),
             "CivetWeb V%s",
             mg_version());
    g_server_name = g_server_base_name;
    g_icon_name = NULL;
    g_website = "http://civetweb.github.io/civetweb/";
    g_num_add_domains = 0;
    g_add_domain = NULL;
}
References DEBUG_ASSERT, g_add_domain, g_icon_name, g_num_add_domains, g_server_base_name, g_server_name, g_website, main_config_options, mg_version(), NULL, NUM_MAIN_OPTIONS, and snprintf.
Referenced by main().
init_system_info()
static void init_system_info (void) static
Definition at line 825 of file vendor/civetweb/main.c.
{
    int len = mg_get_system_info(NULL, 0);
    if (len > 0) {
        g_system_info = (char *)malloc((unsigned)len + 1);
        (void)mg_get_system_info(g_system_info, len + 1);
    } else {
        g_system_info = sdup("Not available");
    }
}
References g_system_info, malloc, mg_get_system_info(), NULL, and sdup().
Referenced by main().
is_path_absolute()
static int is_path_absolute (const char * path) static
Definition at line 863 of file vendor/civetweb/main.c.
{
#if defined(_WIN32)
    return path != NULL
           && ((path[0] == '\\' && path[1] == '\\') || /* UNC path, e.g.
                                                          \\server\dir */
               (isalpha((unsigned char)path[0]) && path[1] == ':'
                && path[2] == '\\')); /* E.g. X:\dir */
#else
    return path != NULL && path[0] == '/';
#endif
}
References NULL.
Referenced by set_absolute_path().
main()
int main (int argc, char * argv[])
Definition at line 3235 of file vendor/civetweb/main.c.
{
    init_server_name();
    init_system_info();
    start_civetweb(argc, argv);
    fprintf(stdout,
            "%s started on port(s) %s with web root [%s]\n",
            g_server_name,
            mg_get_option(g_ctx, "listening_ports"),
            mg_get_option(g_ctx, "document_root"));
    while (g_exit_flag == 0) {
        sleep(1);
    }
    fprintf(stdout,
            "Exiting on signal %d, waiting for all threads to finish...",
            g_exit_flag);
    fflush(stdout);
    stop_civetweb();
    fprintf(stdout, "%s", " done.\n");
    free_system_info();
    return EXIT_SUCCESS;
}
References free_system_info(), g_ctx, g_exit_flag, g_server_name, init_server_name(), init_system_info(), mg_get_option, start_civetweb(), and stop_civetweb().
process_command_line_arguments()
static void process_command_line_arguments (int argc, char * argv[], const char ** options) static
Definition at line 738 of file vendor/civetweb/main.c.
{
    char *p;
    size_t i, cmd_line_opts_start = 1;
#if defined(CONFIG_FILE2)
    FILE *fp = NULL;
#endif
    /* Should we use a config file ? */
    if ((argc > 1) && (argv[1] != NULL) && (argv[1][0] != '-')
        && (argv[1][0] != 0)) {
        /* The first command line parameter is a config file name. */
        snprintf(g_config_file_name,
                 sizeof(g_config_file_name) - 1,
                 "%s",
                 argv[1]);
        cmd_line_opts_start = 2;
    } else if ((p = strrchr(argv[0], DIRSEP)) == NULL) {
        /* No config file set. No path in arg[0] found.
         * Use default file name in the current path. */
        snprintf(g_config_file_name,
                 sizeof(g_config_file_name) - 1,
                 "%s",
                 CONFIG_FILE);
    } else {
        /* No config file set. Path to exe found in arg[0].
         * Use default file name next to the executable. */
        snprintf(g_config_file_name,
                 sizeof(g_config_file_name) - 1,
                 "%.*s%c%s",
                 (int)(p - argv[0]),
                 argv[0],
                 DIRSEP,
                 CONFIG_FILE);
    }
    g_config_file_name[sizeof(g_config_file_name) - 1] = 0;
#if defined(CONFIG_FILE2)
    fp = fopen(g_config_file_name, "r");
    /* try alternate config file */
    if (fp == NULL) {
        fp = fopen(CONFIG_FILE2, "r");
        if (fp != NULL) {
            strcpy(g_config_file_name, CONFIG_FILE2);
        }
    }
    if (fp != NULL) {
        fclose(fp);
    }
#endif
    /* read all configurations from a config file */
    if (0 == read_config_file(g_config_file_name, options)) {
        if (cmd_line_opts_start == 2) {
            /* If config file was set in command line and open failed, die. */
            /* Errno will still hold the error from fopen. */
            die("Cannot open config file %s: %s",
                g_config_file_name,
                strerror(errno));
        }
        /* Otherwise: CivetWeb can work without a config file */
    }
    /* If we're under MacOS and started by launchd, then the second
       argument is process serial number, -psn_.....
       In this case, don't process arguments at all. */
    if (argv[1] == NULL || memcmp(argv[1], "-psn_", 5) != 0) {
        /* Handle command line flags.
           They override config file and default settings. */
        for (i = cmd_line_opts_start; argv[i] != NULL; i += 2) {
            if (argv[i][0] != '-' || argv[i + 1] == NULL) {
                show_usage_and_exit(argv[0]);
            }
            if (!set_option(options, &argv[i][1], argv[i + 1])) {
                fprintf(
                    stderr,
                    "command line option is invalid, ignoring it:\n %s %s\n",
                    argv[i],
                    argv[i + 1]);
            }
        }
    }
}
References CONFIG_FILE, die(), DIRSEP, g_config_file_name, NULL, read_config_file(), set_option(), show_usage_and_exit(), and snprintf.
Referenced by start_civetweb().
read_config_file()
static int read_config_file (const char * config_file, const char ** options) static
Definition at line 666 of file vendor/civetweb/main.c.
{
    char line[MAX_CONF_FILE_LINE_SIZE], *p;
    FILE *fp = NULL;
    size_t i, j, line_no = 0;
    /* Open the config file */
    fp = fopen(config_file, "r");
    if (fp == NULL) {
        /* Failed to open the file. Keep errno for the caller. */
        return 0;
    }
    /* Load config file settings first */
    fprintf(stdout, "Loading config file %s\n", config_file);
    /* Loop over the lines in config file */
    while (fgets(line, sizeof(line), fp) != NULL) {
        if (!line_no && !memcmp(line, "\xEF\xBB\xBF", 3)) {
            /* strip UTF-8 BOM */
            p = line + 3;
        } else {
            p = line;
        }
        line_no++;
        /* Ignore empty lines and comments */
        for (i = 0; isspace((unsigned char)p[i]);)
            i++;
        if (p[i] == '#' || p[i] == '\0') {
            continue;
        }
        /* Skip spaces, \r and \n at the end of the line */
        for (j = strlen(p); (j > 0)
                            && (isspace((unsigned char)p[j - 1])
                                || iscntrl((unsigned char)p[j - 1]));)
            p[--j] = 0;
        /* Find the space character between option name and value */
        for (j = i; !isspace((unsigned char)p[j]) && (p[j] != 0);)
            j++;
        /* Terminate the string - then the string at (p+i) contains the
         * option name */
        p[j] = 0;
        j++;
        /* Trim additional spaces between option name and value - then
         * (p+j) contains the option value */
        while (isspace((unsigned char)p[j])) {
            j++;
        }
        /* Set option */
        if (!set_option(options, p + i, p + j)) {
            fprintf(stderr,
                    "%s: line %d is invalid, ignoring it:\n %s",
                    config_file,
                    (int)line_no,
                    p);
        }
    }
    (void)fclose(fp);
    return 1;
}
References MAX_CONF_FILE_LINE_SIZE, NULL, and set_option().
Referenced by process_command_line_arguments(), and start_civetweb().
run_client()
static int run_client (const char * url_arg) static
Definition at line 995 of file vendor/civetweb/main.c.
{
    /* connection data */
    char *url = sdup(url_arg); /* OOM will cause program to exit */
    char *host;
    char *resource;
    int is_ssl = 0;
    unsigned long port = 0;
    size_t sep;
    char *endp = 0;
    char empty[] = "";
    /* connection object */
    struct mg_connection *conn;
    char ebuf[1024] = {0};
#if 0 /* Unreachable code, since sdup will never return NULL */
    /* Check out of memory */
    if (!url) {
        fprintf(stderr, "Out of memory\n");
        return 0;
    }
#endif
    /* Check parameter */
    if (!strncmp(url, "http://", 7)) {
        host = url + 7;
        port = 80;
    } else if (!strncmp(url, "https://", 8)) {
        host = url + 8;
        is_ssl = 1;
        port = 443;
    } else {
        fprintf(stderr, "URL must start with http:// or https://\n");
        free(url);
        return 0;
    }
    if ((host[0] <= 32) || (host[0] > 126) || (host[0] == '/')
        || (host[0] == ':')) {
        fprintf(stderr, "Invalid host\n");
        free(url);
        return 0;
    }
    sep = strcspn(host, "/:");
    switch (host[sep]) {
    case 0:
        resource = empty;
        break;
    case '/':
        host[sep] = 0;
        resource = host + sep + 1;
        break;
    case ':':
        host[sep] = 0;
        port = strtoul(host + sep + 1, &endp, 10);
        if (!endp || (*endp != '/' && *endp != 0) || (port < 1)
            || (port > 0xFFFF)) {
            fprintf(stderr, "Invalid port\n");
            free(url);
            return 0;
        }
        if (*endp) {
            *endp = 0;
            resource = endp + 1;
        } else {
            resource = empty;
        }
        break;
    default:
        fprintf(stderr, "Syntax error\n");
        free(url);
        return 0;
    }
    fprintf(stdout, "Protocol: %s\n", is_ssl ? "https" : "http");
    fprintf(stdout, "Host: %s\n", host);
    fprintf(stdout, "Port: %lu\n", port);
    fprintf(stdout, "Resource: %s\n", resource);
    /* Initialize library */
    if (is_ssl) {
        mg_init_library(MG_FEATURES_TLS);
    } else {
        mg_init_library(MG_FEATURES_DEFAULT);
    }
    /* Connect to host */
    conn = mg_connect_client(host, (int)port, is_ssl, ebuf, sizeof(ebuf));
    if (conn) {
        /* Connecting to server worked */
        char buf[1024] = {0};
        int ret;
        fprintf(stdout, "Connected to %s\n", host);
        /* Send GET request */
        mg_printf(conn,
                  "GET /%s HTTP/1.1\r\n"
                  "Host: %s\r\n"
                  "Connection: close\r\n"
                  "\r\n",
                  resource,
                  host);
        /* Wait for server to respond with a HTTP header */
        ret = mg_get_response(conn, ebuf, sizeof(ebuf), 10000);
        if (ret >= 0) {
            const struct mg_response_info *ri = mg_get_response_info(conn);
            fprintf(stdout,
                    "Response info: %i %s\n",
                    ri->status_code,
                    ri->status_text);
            /* Respond reader read. Read body (if any) */
            ret = mg_read(conn, buf, sizeof(buf));
            while (ret > 0) {
                fwrite(buf, 1, (unsigned)ret, stdout);
                ret = mg_read(conn, buf, sizeof(buf));
            }
            fprintf(stdout, "Closing connection to %s\n", host);
        } else {
            /* Server did not reply to HTTP request */
            fprintf(stderr, "Got no response from %s:\n%s\n", host, ebuf);
        }
        mg_close_connection(conn);
    } else {
        /* Connecting to server failed */
        fprintf(stderr, "Error connecting to %s:\n%s\n", host, ebuf);
    }
    /* Free memory and exit library */
    free(url);
    mg_exit_library();
    return 1;
}
References mg_connection::buf, free, fwrite(), mg_close_connection(), mg_connect_client(), mg_exit_library(), MG_FEATURES_DEFAULT, MG_FEATURES_TLS, mg_get_response(), mg_get_response_info(), mg_init_library(), mg_printf(), mg_read(), sdup(), mg_response_info::status_code, and mg_response_info::status_text.
Referenced by start_civetweb().
sanitize_options()
static int sanitize_options (const char * options[], const char * arg0) static
Definition at line 1139 of file vendor/civetweb/main.c.
{
    int ok = 1;
    /* Make sure we have absolute paths for files and directories */
    set_absolute_path(options, "document_root", arg0);
    set_absolute_path(options, "put_delete_auth_file", arg0);
    set_absolute_path(options, "cgi_interpreter", arg0);
    set_absolute_path(options, "access_log_file", arg0);
    set_absolute_path(options, "error_log_file", arg0);
    set_absolute_path(options, "global_auth_file", arg0);
#if defined(USE_LUA)
    set_absolute_path(options, "lua_preload_file", arg0);
#endif
    set_absolute_path(options, "ssl_certificate", arg0);
    /* Make extra verification for certain options */
    if (!verify_existence(options, "document_root", 1))
        ok = 0;
    if (!verify_existence(options, "cgi_interpreter", 0))
        ok = 0;
    if (!verify_existence(options, "ssl_certificate", 0))
        ok = 0;
    if (!verify_existence(options, "ssl_ca_path", 1))
        ok = 0;
    if (!verify_existence(options, "ssl_ca_file", 0))
        ok = 0;
#if defined(USE_LUA)
    if (!verify_existence(options, "lua_preload_file", 0))
        ok = 0;
#endif
    return ok;
}
References set_absolute_path(), and verify_existence().
Referenced by start_civetweb().
sdup()
static char * sdup (const char * str) static
Definition at line 453 of file vendor/civetweb/main.c.
{
    size_t len;
    char *p;
    len = strlen(str) + 1;
    p = (char *)malloc(len);
    if (p == NULL) {
        die("Cannot allocate %u bytes", (unsigned)len);
    }
    memcpy(p, str, len);
    return p;
}
References die(), malloc, and NULL.
Referenced by init_system_info(), run_client(), and set_option().
set_absolute_path()
static void set_absolute_path (const char * options[], const char * option_name, const char * path_to_civetweb_exe) static
Definition at line 914 of file vendor/civetweb/main.c.
{
    char path[PATH_MAX] = "", absolute[PATH_MAX] = "";
    const char *option_value;
    const char *p;
    /* Check whether option is already set */
    option_value = get_option(options, option_name);
    /* If option is already set and it is an absolute path,
       leave it as it is -- it's already absolute. */
    if (option_value != NULL && !is_path_absolute(option_value)) {
        /* Not absolute. Use the directory where civetweb executable lives
           be the relative directory for everything.
           Extract civetweb executable directory into path. */
        if ((p = strrchr(path_to_civetweb_exe, DIRSEP)) == NULL) {
            IGNORE_UNUSED_RESULT(getcwd(path, sizeof(path)));
        } else {
            snprintf(path,
                     sizeof(path) - 1,
                     "%.*s",
                     (int)(p - path_to_civetweb_exe),
                     path_to_civetweb_exe);
            path[sizeof(path) - 1] = 0;
        }
        strncat(path, "/", sizeof(path) - strlen(path) - 1);
        strncat(path, option_value, sizeof(path) - strlen(path) - 1);
        /* Absolutize the path, and set the option */
        IGNORE_UNUSED_RESULT(abs_path(path, absolute, sizeof(absolute)));
        set_option(options, option_name, absolute);
    }
}
References abs_path, DIRSEP, get_option(), IGNORE_UNUSED_RESULT, is_path_absolute(), NULL, PATH_MAX, set_option(), and snprintf.
Referenced by sanitize_options().
set_option()
static int set_option (const char ** options, const char * name, const char * value) static
Definition at line 495 of file vendor/civetweb/main.c.
{
    int i, type;
    const struct mg_option *default_options = mg_get_valid_options();
    const char *multi_sep = NULL;
    for (i = 0; main_config_options[i].name != NULL; i++) {
        /* These options are evaluated by main.c, not civetweb.c.
         * Do not add it to options, and return OK */
        if (!strcmp(name, main_config_options[OPTION_TITLE].name)) {
            g_server_name = sdup(value);
            return 1;
        }
        if (!strcmp(name, main_config_options[OPTION_ICON].name)) {
            g_icon_name = sdup(value);
            return 1;
        }
        if (!strcmp(name, main_config_options[OPTION_WEBPAGE].name)) {
            g_website = sdup(value);
            return 1;
        }
        if (!strcmp(name, main_config_options[OPTION_HIDE_TRAY].name)) {
            if (!strcmp(value, "yes")) {
                g_hide_tray = 1;
            } else if (!strcmp(value, "no")) {
                g_hide_tray = 0;
            }
            return 1;
        }
        if (!strcmp(name, main_config_options[OPTION_ADD_DOMAIN].name)) {
            if (g_num_add_domains > 0) {
                g_add_domain = (const char **)realloc(
                    (void *)g_add_domain,
                    sizeof(char *) * ((unsigned)g_num_add_domains + 1u));
                if (!g_add_domain) {
                    die("Out of memory");
                }
                g_add_domain[g_num_add_domains] = sdup(value);
                g_num_add_domains++;
            } else {
                g_add_domain = (const char **)malloc(sizeof(char *));
                if (!g_add_domain) {
                    die("Out of memory");
                }
                g_add_domain[0] = sdup(value);
                g_num_add_domains = 1;
            }
            return 1;
        }
    }
    /* Not an option of main.c, so check if it is a CivetWeb server option */
    type = MG_CONFIG_TYPE_UNKNOWN; /* type "unknown" means "option not found" */
    for (i = 0; default_options[i].name != NULL; i++) {
        if (!strcmp(default_options[i].name, name)) {
            type = default_options[i].type;
            break; /* no need to search for another option */
        }
    }
    switch (type) {
    case MG_CONFIG_TYPE_UNKNOWN:
        /* unknown option */
        return 0; /* return error */
    case MG_CONFIG_TYPE_NUMBER:
        /* integer number >= 0, e.g. number of threads */
        {
            char *chk = 0;
            unsigned long num = strtoul(value, &chk, 10);
            (void)num; /* do not check value, only syntax */
            if ((chk == NULL) || (*chk != 0) || (chk == value)) {
                /* invalid number */
                return 0;
            }
        }
        break;
    case MG_CONFIG_TYPE_STRING:
        /* any text */
        break;
    case MG_CONFIG_TYPE_STRING_LIST:
        /* list of text items, separated by , */
        multi_sep = ",";
        break;
    case MG_CONFIG_TYPE_STRING_MULTILINE:
        /* lines of text, separated by carriage return line feed */
        multi_sep = "\r\n";
        break;
    case MG_CONFIG_TYPE_BOOLEAN:
        /* boolean value, yes or no */
        if ((0 != strcmp(value, "yes")) && (0 != strcmp(value, "no"))) {
            /* invalid boolean */
            return 0;
        }
        break;
    case MG_CONFIG_TYPE_YES_NO_OPTIONAL:
        /* boolean value, yes or no */
        if ((0 != strcmp(value, "yes")) && (0 != strcmp(value, "no"))
            && (0 != strcmp(value, "optional"))) {
            /* invalid boolean */
            return 0;
        }
        break;
    case MG_CONFIG_TYPE_FILE:
    case MG_CONFIG_TYPE_DIRECTORY:
        /* TODO (low): check this option when it is set, instead of calling
         * verify_existence later */
        break;
    case MG_CONFIG_TYPE_EXT_PATTERN:
        /* list of patterns, separated by | */
        multi_sep = "|";
        break;
    default:
        die("Unknown option type - option %s", name);
    }
    for (i = 0; i < MAX_OPTIONS; i++) {
        if (options[2 * i] == NULL) {
            /* Option not set yet. Add new option */
            options[2 * i] = sdup(name);
            options[2 * i + 1] = sdup(value);
            options[2 * i + 2] = NULL;
            break;
        } else if (!strcmp(options[2 * i], name)) {
            if (multi_sep) {
                /* Option already set. Append new value. */
                char *s =
                    (char *)malloc(strlen(options[2 * i + 1])
                                   + strlen(multi_sep) + strlen(value) + 1);
                if (!s) {
                    die("Out of memory");
                }
                sprintf(s, "%s%s%s", options[2 * i + 1], multi_sep, value);
                free((char *)options[2 * i + 1]);
                options[2 * i + 1] = s;
            } else {
                /* Option already set. Overwrite */
                free((char *)options[2 * i + 1]);
                options[2 * i + 1] = sdup(value);
            }
            break;
        }
    }
    if (i == MAX_OPTIONS) {
        die("Too many options specified");
    }
    if (options[2 * i] == NULL) {
        die("Out of memory");
    }
    if (options[2 * i + 1] == NULL) {
        die("Illegal escape sequence, or out of memory");
    }
    /* option set correctly */
    return 1;
}
References die(), free, g_add_domain, g_hide_tray, g_icon_name, g_num_add_domains, g_server_name, g_website, main_config_options, malloc, MAX_OPTIONS, MG_CONFIG_TYPE_BOOLEAN, MG_CONFIG_TYPE_DIRECTORY, MG_CONFIG_TYPE_EXT_PATTERN, MG_CONFIG_TYPE_FILE, MG_CONFIG_TYPE_NUMBER, MG_CONFIG_TYPE_STRING, MG_CONFIG_TYPE_STRING_LIST, MG_CONFIG_TYPE_STRING_MULTILINE, MG_CONFIG_TYPE_UNKNOWN, MG_CONFIG_TYPE_YES_NO_OPTIONAL, mg_get_valid_options(), mg_option::name, name, NULL, OPTION_ADD_DOMAIN, OPTION_HIDE_TRAY, OPTION_ICON, OPTION_TITLE, OPTION_WEBPAGE, realloc, s, sdup(), mg_option::type, and value.
Referenced by process_command_line_arguments(), read_config_file(), set_absolute_path(), and start_civetweb().
show_server_name()
static void show_server_name (void) static
Definition at line 303 of file vendor/civetweb/main.c.
{
#if defined(BUILD_DATE)
    const char *bd = BUILD_DATE;
#else
    const char *bd = __DATE__;
#endif
#if defined(WIN32)
    (void)MakeConsole();
#endif
    fprintf(stderr, "CivetWeb v%s, built on %s\n", mg_version(), bd);
}
References mg_version().
Referenced by show_usage_and_exit(), and start_civetweb().
show_usage_and_exit()
static NO_RETURN void show_usage_and_exit (const char * exeName) static
Definition at line 319 of file vendor/civetweb/main.c.
{
    const struct mg_option *options;
    int i;
    if (exeName == 0 || *exeName == 0) {
        exeName = "civetweb";
    }
    show_server_name();
    fprintf(stderr, "\nUsage:\n");
    fprintf(stderr, "  Start server with a set of options:\n");
    fprintf(stderr, "    %s [config_file]\n", exeName);
    fprintf(stderr, "    %s [-option value ...]\n", exeName);
    fprintf(stderr, "  Run as client:\n");
    fprintf(stderr, "    %s -C url\n", exeName);
    fprintf(stderr, "  Show system information:\n");
    fprintf(stderr, "    %s -I\n", exeName);
    fprintf(stderr, "  Add user/change password:\n");
    fprintf(stderr,
            "    %s -A <htpasswd_file> <realm> <user> <passwd>\n",
            exeName);
    fprintf(stderr, "  Remove user:\n");
    fprintf(stderr, "    %s -R <htpasswd_file> <realm> <user>\n", exeName);
    fprintf(stderr, "\nOPTIONS:\n");
    options = mg_get_valid_options();
    for (i = 0; options[i].name != NULL; i++) {
        fprintf(stderr,
                "  -%s %s\n",
                options[i].name,
                ((options[i].default_value == NULL)
                     ? "<empty>"
                     : options[i].default_value));
    }
    options = main_config_options;
    for (i = 0; options[i].name != NULL; i++) {
        fprintf(stderr,
                "  -%s %s\n",
                options[i].name,
                ((options[i].default_value == NULL)
                     ? "<empty>"
                     : options[i].default_value));
    }
    exit(EXIT_FAILURE);
}
References mg_option::default_value, main_config_options, mg_get_valid_options(), mg_option::name, name, NULL, and show_server_name().
Referenced by process_command_line_arguments(), and start_civetweb().
signal_handler()
static void WINCDECL signal_handler (int sig_num) static
Definition at line 251 of file vendor/civetweb/main.c.
{
    g_exit_flag = sig_num;
}
References g_exit_flag.
Referenced by start_civetweb().
start_civetweb()
static void start_civetweb (int argc, char * argv[]) static
Definition at line 1181 of file vendor/civetweb/main.c.
{
    struct mg_callbacks callbacks;
    const char *options[2 * MAX_OPTIONS + 1];
    struct mg_init_data init;
    struct mg_error_data error;
    char error_text[256];
    int i;
    /* Start option -I:
     * Show system information and exit
     * This is very useful for diagnosis. */
    if (argc > 1 && !strcmp(argv[1], "-I")) {
#if defined(WIN32)
        (void)MakeConsole();
#endif
        fprintf(stdout,
                "\n%s (%s)\n%s\n",
                g_server_base_name,
                g_server_name,
                g_system_info);
        exit(EXIT_SUCCESS);
    }
    /* Edit passwords file: Add user or change password, if -A option is
     * specified */
    if (argc > 1 && !strcmp(argv[1], "-A")) {
        if (argc != 6) {
            show_usage_and_exit(argv[0]);
        }
        exit(mg_modify_passwords_file(argv[2], argv[3], argv[4], argv[5])
                 ? EXIT_SUCCESS
                 : EXIT_FAILURE);
    }
    /* Edit passwords file: Remove user, if -R option is specified */
    if (argc > 1 && !strcmp(argv[1], "-R")) {
        if (argc != 5) {
            show_usage_and_exit(argv[0]);
        }
        exit(mg_modify_passwords_file(argv[2], argv[3], argv[4], NULL)
                 ? EXIT_SUCCESS
                 : EXIT_FAILURE);
    }
    /* Client mode */
    if (argc > 1 && !strcmp(argv[1], "-C")) {
        if (argc != 3) {
            show_usage_and_exit(argv[0]);
        }
        exit(run_client(argv[2]) ? EXIT_SUCCESS : EXIT_FAILURE);
    }
    /* Call Lua with additional CivetWeb specific Lua functions, if -L option
     * is specified */
    if (argc > 1 && !strcmp(argv[1], "-L")) {
#if defined(USE_LUA)
        if (argc != 3) {
            show_usage_and_exit(argv[0]);
        }
#if defined(WIN32)
        (void)MakeConsole();
#endif
        exit(run_lua(argv[2]));
#else
        show_server_name();
        fprintf(stderr, "\nError: Lua support not enabled\n");
        exit(EXIT_FAILURE);
#endif
    }
    /* Call Duktape, if -E option is specified */
    if (argc > 1 && !strcmp(argv[1], "-E")) {
#if defined(USE_DUKTAPE)
        if (argc != 3) {
            show_usage_and_exit(argv[0]);
        }
#if defined(WIN32)
        (void)MakeConsole();
#endif
        exit(run_duktape(argv[2]));
#else
        show_server_name();
        fprintf(stderr, "\nError: Ecmascript support not enabled\n");
        exit(EXIT_FAILURE);
#endif
    }
    /* Show usage if -h or --help options are specified */
    if (argc == 2
        && (!strcmp(argv[1], "-h") || !strcmp(argv[1], "-H")
            || !strcmp(argv[1], "--help"))) {
        show_usage_and_exit(argv[0]);
    }
    /* Initialize options structure */
    memset((void *)options, 0, sizeof(options));
    set_option(options, "document_root", ".");
    /* Update config based on command line arguments */
    process_command_line_arguments(argc, argv, options);
    i = sanitize_options(options, argv[0]);
    if (!i) {
        die("Invalid options");
    }
    /* Setup signal handler: quit on Ctrl-C */
    signal(SIGTERM, signal_handler);
    signal(SIGINT, signal_handler);
#if defined(DAEMONIZE)
    /* Daemonize */
    for (i = 0; options[i] != NULL; i++) {
        if (strcmp(options[i], "daemonize") == 0) {
            if (options[i + 1] != NULL) {
                if (mg_strcasecmp(options[i + 1], "yes") == 0) {
                    fprintf(stdout, "daemonize.\n");
                    if (daemon(0, 0) != 0) {
                        fprintf(stdout, "Failed to daemonize main process.\n");
                        exit(EXIT_FAILURE);
                    }
                    FILE *fp;
                    if ((fp = fopen(PID_FILE, "w")) == 0) {
                        fprintf(stdout, "Can not open %s.\n", PID_FILE);
                        exit(EXIT_FAILURE);
                    }
                    fprintf(fp, "%d", getpid());
                    fclose(fp);
                }
            }
            break;
        }
    }
#endif
    /* Initialize user data */
    memset(&g_user_data, 0, sizeof(g_user_data));
    memset(&callbacks, 0, sizeof(callbacks));
    memset(&init, 0, sizeof(init));
    init.callbacks = &callbacks;
    init.configuration_options = options;
    init.user_data = &g_user_data;
    memset(&error, 0, sizeof(error));
    error.text = error_text;
    error.text_buffer_size = sizeof(error_text);
    /* Start Civetweb */
    g_ctx = mg_start2(&init, &error);
    /* mg_start copies all options to an internal buffer.
     * The options data field here is not required anymore. */
    for (i = 0; options[i] != NULL; i++) {
        free((char *)options[i]);
    }
    /* If mg_start fails, it returns NULL */
    if (g_ctx == NULL) {
#ifdef _WIN32
        /* On Windows: provide option to edit configuration file. */
        char msgboxtxt[1024];
        int ret;
        sprintf(msgboxtxt,
                "Failed to start %s with code %u:\n%s\n\nEdit settings?",
                g_server_name,
                error.code,
                error_text);
        ret =
            MessageBox(NULL, msgboxtxt, "Error", MB_ICONERROR | MB_YESNOCANCEL);
        if (ret == IDYES) {
            show_settings_dialog();
            /* Hitting "save" will also restart the server. */
            if (g_ctx != NULL) {
                return;
            }
        }
        exit(EXIT_FAILURE);
#else
        die("Failed to start %s with code %u:\n%s",
            g_server_name,
            error.code,
            error_text);
#endif
    }
#if defined(MG_EXPERIMENTAL_INTERFACES)
    for (i = 0; i < g_num_add_domains; i++) {
        int j;
        memset(options, 0, sizeof(options));
        set_option(options, "document_root", ".");
        if (0 == read_config_file(g_add_domain[i], options)) {
            die("Cannot open config file %s: %s",
                g_add_domain[i],
                strerror(errno));
        }
        j = sanitize_options(options, argv[0]);
        if (!j) {
            die("Invalid options");
        }
        j = mg_start_domain(g_ctx, (const char **)options);
        if (j < 0) {
            die("Error loading domain file %s: %i", g_add_domain[i], j);
        } else {
            fprintf(stdout, "Domain file %s loaded\n", g_add_domain[i]);
        }
        for (j = 0; options[j] != NULL; j++) {
            free((void *)options[j]);
        }
    }
#endif
}
References mg_init_data::callbacks, mg_init_data::configuration_options, die(), error(), free, g_add_domain, g_ctx, g_num_add_domains, g_server_base_name, g_server_name, g_system_info, g_user_data, MAX_OPTIONS, mg_modify_passwords_file(), mg_start2(), mg_start_domain(), mg_strcasecmp(), NULL, process_command_line_arguments(), read_config_file(), run_client(), run_lua(), sanitize_options(), set_option(), show_server_name(), show_usage_and_exit(), signal_handler(), and mg_init_data::user_data.
Referenced by main().
stop_civetweb()
static void stop_civetweb (void) static
Definition at line 1409 of file vendor/civetweb/main.c.
{
    mg_stop(g_ctx);
}
References g_ctx, and mg_stop().
Referenced by main().
verify_existence()
static int verify_existence (const char ** options, const char * option_name, int must_be_dir) static
Definition at line 878 of file vendor/civetweb/main.c.
{
    struct stat st;
    const char *path = get_option(options, option_name);
#if defined(_WIN32)
    wchar_t wbuf[1024];
    char mbbuf[1024];
    int len;
    if (path) {
        memset(wbuf, 0, sizeof(wbuf));
        memset(mbbuf, 0, sizeof(mbbuf));
        len = MultiByteToWideChar(
            CP_UTF8, 0, path, -1, wbuf, sizeof(wbuf) / sizeof(wbuf[0]) - 1);
        wcstombs(mbbuf, wbuf, sizeof(mbbuf) - 1);
        path = mbbuf;
        (void)len;
    }
#endif
    if (path != NULL
        && (stat(path, &st) != 0
            || ((S_ISDIR(st.st_mode) ? 1 : 0) != must_be_dir))) {
        warn("Invalid path for %s: [%s]: (%s). Make sure that path is either "
             "absolute, or it is relative to civetweb executable.",
             option_name,
             path,
             strerror(errno));
        return 0;
    }
    return 1;
}
References get_option(), NULL, and warn().
Referenced by sanitize_options().
warn()
static void warn (const char * fmt, ...) static
Definition at line 279 of file vendor/civetweb/main.c.
{
    va_list ap;
    char msg[512] = "";
    va_start(ap, fmt);
    (void)vsnprintf(msg, sizeof(msg) - 1, fmt, ap);
    msg[sizeof(msg) - 1] = 0;
    va_end(ap);
#if defined(_WIN32)
    MessageBox(NULL, msg, "Warning", MB_OK);
#else
    fprintf(stderr, "%s\n", msg);
#endif
}
References NULL.
Referenced by verify_existence().
Variable Documentation
g_add_domain
const char** g_add_domain static
Definition at line 197 of file vendor/civetweb/main.c.
Referenced by init_server_name(), set_option(), and start_civetweb().
g_config_file_name
char g_config_file_name[PATH_MAX] static
Initial value:
=
    ""
Definition at line 203 of file vendor/civetweb/main.c.
Referenced by process_command_line_arguments().
g_ctx
struct mg_context* g_ctx static
Definition at line 207 of file vendor/civetweb/main.c.
Referenced by main(), start_civetweb(), and stop_civetweb().
g_exit_flag
volatile int g_exit_flag = 0
Definition at line 185 of file vendor/civetweb/main.c.
Referenced by main(), and signal_handler().
g_hide_tray
int g_hide_tray = 0 static
Definition at line 199 of file vendor/civetweb/main.c.
Referenced by set_option().
g_icon_name
const char* g_icon_name static
Definition at line 191 of file vendor/civetweb/main.c.
Referenced by init_server_name(), and set_option().
g_num_add_domains
int g_num_add_domains static
Definition at line 195 of file vendor/civetweb/main.c.
Referenced by init_server_name(), set_option(), and start_civetweb().
g_server_base_name
char g_server_base_name[40] static
Definition at line 187 of file vendor/civetweb/main.c.
Referenced by init_server_name(), and start_civetweb().
g_server_name
const char* g_server_name static
Definition at line 189 of file vendor/civetweb/main.c.
Referenced by init_server_name(), main(), set_option(), and start_civetweb().
g_system_info
char* g_system_info static
Definition at line 202 of file vendor/civetweb/main.c.
Referenced by free_system_info(), init_system_info(), and start_civetweb().
g_user_data
struct tuser_data g_user_data static
Definition at line 209 of file vendor/civetweb/main.c.
Referenced by start_civetweb().
g_website
const char* g_website static
Definition at line 193 of file vendor/civetweb/main.c.
Referenced by init_server_name(), and set_option().
main_config_options
struct mg_option main_config_options[] static
Initial value:
= {
    {"title", MG_CONFIG_TYPE_STRING, NULL},
    {"icon", MG_CONFIG_TYPE_STRING, NULL},
    {"website", MG_CONFIG_TYPE_STRING, NULL},
    {"add_domain", MG_CONFIG_TYPE_STRING_LIST, NULL},
    {"hide_tray", MG_CONFIG_TYPE_BOOLEAN, NULL},
    {NULL, MG_CONFIG_TYPE_UNKNOWN, NULL}}
Definition at line 237 of file vendor/civetweb/main.c.
{
    {"title", MG_CONFIG_TYPE_STRING, NULL},
    {"icon", MG_CONFIG_TYPE_STRING, NULL},
    {"website", MG_CONFIG_TYPE_STRING, NULL},
    {"add_domain", MG_CONFIG_TYPE_STRING_LIST, NULL},
    {"hide_tray", MG_CONFIG_TYPE_BOOLEAN, NULL},
#if defined(DAEMONIZE)
    {"daemonize", MG_CONFIG_TYPE_BOOLEAN, "no"},
#endif
    {NULL, MG_CONFIG_TYPE_UNKNOWN, NULL}};
Referenced by init_server_name(), set_option(), and show_usage_and_exit().