var annotated_dup =
[
    [ "doctest", "namespacedoctest.html", [
      [ "detail", "namespacedoctest_1_1detail.html", [
        [ "types", "namespacedoctest_1_1detail_1_1types.html", [
          [ "enable_if", "structdoctest_1_1detail_1_1types_1_1enable__if.html", null ],
          [ "enable_if< true, T >", "structdoctest_1_1detail_1_1types_1_1enable__if_3_01true_00_01T_01_4.html", "structdoctest_1_1detail_1_1types_1_1enable__if_3_01true_00_01T_01_4" ],
          [ "false_type", "structdoctest_1_1detail_1_1types_1_1false__type.html", null ],
          [ "is_array", "structdoctest_1_1detail_1_1types_1_1is__array.html", null ],
          [ "is_array< T[SIZE]>", "structdoctest_1_1detail_1_1types_1_1is__array_3_01T_0fSIZE_0e_4.html", null ],
          [ "is_enum", "structdoctest_1_1detail_1_1types_1_1is__enum.html", null ],
          [ "is_pointer", "structdoctest_1_1detail_1_1types_1_1is__pointer.html", null ],
          [ "is_pointer< T * >", "structdoctest_1_1detail_1_1types_1_1is__pointer_3_01T_01_5_01_4.html", null ],
          [ "is_rvalue_reference", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference.html", null ],
          [ "is_rvalue_reference< T && >", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference_3_01T_01_6_6_01_4.html", null ],
          [ "remove_const", "structdoctest_1_1detail_1_1types_1_1remove__const.html", "structdoctest_1_1detail_1_1types_1_1remove__const" ],
          [ "remove_const< const T >", "structdoctest_1_1detail_1_1types_1_1remove__const_3_01const_01T_01_4.html", "structdoctest_1_1detail_1_1types_1_1remove__const_3_01const_01T_01_4" ],
          [ "remove_reference", "structdoctest_1_1detail_1_1types_1_1remove__reference.html", "structdoctest_1_1detail_1_1types_1_1remove__reference" ],
          [ "remove_reference< T & >", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01T_01_6_01_4.html", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01T_01_6_01_4" ],
          [ "remove_reference< T && >", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01T_01_6_6_01_4.html", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01T_01_6_6_01_4" ],
          [ "true_type", "structdoctest_1_1detail_1_1types_1_1true__type.html", null ],
          [ "underlying_type", "structdoctest_1_1detail_1_1types_1_1underlying__type.html", "structdoctest_1_1detail_1_1types_1_1underlying__type" ]
        ] ],
        [ "ContextScope", "classdoctest_1_1detail_1_1ContextScope.html", "classdoctest_1_1detail_1_1ContextScope" ],
        [ "ContextScopeBase", "structdoctest_1_1detail_1_1ContextScopeBase.html", "structdoctest_1_1detail_1_1ContextScopeBase" ],
        [ "deferred_false", "structdoctest_1_1detail_1_1deferred__false.html", null ],
        [ "ExceptionTranslator", "classdoctest_1_1detail_1_1ExceptionTranslator.html", "classdoctest_1_1detail_1_1ExceptionTranslator" ],
        [ "Expression_lhs", "structdoctest_1_1detail_1_1Expression__lhs.html", "structdoctest_1_1detail_1_1Expression__lhs" ],
        [ "ExpressionDecomposer", "structdoctest_1_1detail_1_1ExpressionDecomposer.html", "structdoctest_1_1detail_1_1ExpressionDecomposer" ],
        [ "filldata", "structdoctest_1_1detail_1_1filldata.html", null ],
        [ "filldata< const char[N]>", "structdoctest_1_1detail_1_1filldata_3_01const_01char_0fN_0e_4.html", null ],
        [ "filldata< const void * >", "structdoctest_1_1detail_1_1filldata_3_01const_01void_01_5_01_4.html", null ],
        [ "filldata< T * >", "structdoctest_1_1detail_1_1filldata_3_01T_01_5_01_4.html", null ],
        [ "filldata< T[N]>", "structdoctest_1_1detail_1_1filldata_3_01T_0fN_0e_4.html", null ],
        [ "has_insertion_operator", "structdoctest_1_1detail_1_1has__insertion__operator.html", null ],
        [ "has_insertion_operator< T, decltype(operator<<(declval< std::ostream & >(), declval< const T & >()), void())>", "structdoctest_1_1detail_1_1has__insertion__operator_3_01T_00_01decltype_07operator_3_3_07declvald5a5a279653bbfeef238ad5c984744e2.html", null ],
        [ "IExceptionTranslator", "structdoctest_1_1detail_1_1IExceptionTranslator.html", "structdoctest_1_1detail_1_1IExceptionTranslator" ],
        [ "MessageBuilder", "structdoctest_1_1detail_1_1MessageBuilder.html", "structdoctest_1_1detail_1_1MessageBuilder" ],
        [ "RelationalComparator", "structdoctest_1_1detail_1_1RelationalComparator.html", "structdoctest_1_1detail_1_1RelationalComparator" ],
        [ "Result", "structdoctest_1_1detail_1_1Result.html", "structdoctest_1_1detail_1_1Result" ],
        [ "ResultBuilder", "structdoctest_1_1detail_1_1ResultBuilder.html", "structdoctest_1_1detail_1_1ResultBuilder" ],
        [ "should_stringify_as_underlying_type", "structdoctest_1_1detail_1_1should__stringify__as__underlying__type.html", null ],
        [ "StringMakerBase", "structdoctest_1_1detail_1_1StringMakerBase.html", null ],
        [ "StringMakerBase< true >", "structdoctest_1_1detail_1_1StringMakerBase_3_01true_01_4.html", null ],
        [ "Subcase", "structdoctest_1_1detail_1_1Subcase.html", "structdoctest_1_1detail_1_1Subcase" ],
        [ "TestCase", "structdoctest_1_1detail_1_1TestCase.html", "structdoctest_1_1detail_1_1TestCase" ],
        [ "TestFailureException", "structdoctest_1_1detail_1_1TestFailureException.html", null ],
        [ "TestSuite", "structdoctest_1_1detail_1_1TestSuite.html", "structdoctest_1_1detail_1_1TestSuite" ]
      ] ],
      [ "Approx", "structdoctest_1_1Approx.html", "structdoctest_1_1Approx" ],
      [ "AssertData", "structdoctest_1_1AssertData.html", "structdoctest_1_1AssertData" ],
      [ "Contains", "classdoctest_1_1Contains.html", "classdoctest_1_1Contains" ],
      [ "Context", "classdoctest_1_1Context.html", "classdoctest_1_1Context" ],
      [ "ContextOptions", "structdoctest_1_1ContextOptions.html", "structdoctest_1_1ContextOptions" ],
      [ "CurrentTestCaseStats", "structdoctest_1_1CurrentTestCaseStats.html", "structdoctest_1_1CurrentTestCaseStats" ],
      [ "IContextScope", "structdoctest_1_1IContextScope.html", "structdoctest_1_1IContextScope" ],
      [ "IReporter", "structdoctest_1_1IReporter.html", "structdoctest_1_1IReporter" ],
      [ "IsNaN", "structdoctest_1_1IsNaN.html", "structdoctest_1_1IsNaN" ],
      [ "MessageData", "structdoctest_1_1MessageData.html", "structdoctest_1_1MessageData" ],
      [ "QueryData", "structdoctest_1_1QueryData.html", "structdoctest_1_1QueryData" ],
      [ "String", "classdoctest_1_1String.html", "classdoctest_1_1String" ],
      [ "StringMaker", "structdoctest_1_1StringMaker.html", null ],
      [ "SubcaseSignature", "structdoctest_1_1SubcaseSignature.html", "structdoctest_1_1SubcaseSignature" ],
      [ "TestCaseData", "structdoctest_1_1TestCaseData.html", "structdoctest_1_1TestCaseData" ],
      [ "TestCaseException", "structdoctest_1_1TestCaseException.html", "structdoctest_1_1TestCaseException" ],
      [ "TestRunStats", "structdoctest_1_1TestRunStats.html", "structdoctest_1_1TestRunStats" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "char_traits", "structstd_1_1char__traits.html", null ],
      [ "tuple", "classstd_1_1tuple.html", null ]
    ] ],
    [ "_cairo_matrix", "struct__cairo__matrix.html", "struct__cairo__matrix" ],
    [ "_cairo_path_data_t", "union__cairo__path__data__t.html", "union__cairo__path__data__t" ],
    [ "_cairo_rectangle", "struct__cairo__rectangle.html", "struct__cairo__rectangle" ],
    [ "_cairo_rectangle_int", "struct__cairo__rectangle__int.html", "struct__cairo__rectangle__int" ],
    [ "_cairo_rectangle_list", "struct__cairo__rectangle__list.html", "struct__cairo__rectangle__list" ],
    [ "_cairo_script_interpreter_hooks", "struct__cairo__script__interpreter__hooks.html", "struct__cairo__script__interpreter__hooks" ],
    [ "_cairo_user_data_key", "struct__cairo__user__data__key.html", "struct__cairo__user__data__key" ],
    [ "_graphene_box_t", "struct__graphene__box__t.html", "struct__graphene__box__t" ],
    [ "_graphene_euler_t", "struct__graphene__euler__t.html", "struct__graphene__euler__t" ],
    [ "_graphene_frustum_t", "struct__graphene__frustum__t.html", "struct__graphene__frustum__t" ],
    [ "_graphene_matrix_t", "struct__graphene__matrix__t.html", "struct__graphene__matrix__t" ],
    [ "_graphene_plane_t", "struct__graphene__plane__t.html", "struct__graphene__plane__t" ],
    [ "_graphene_point3d_t", "struct__graphene__point3d__t.html", "struct__graphene__point3d__t" ],
    [ "_graphene_point_t", "struct__graphene__point__t.html", "struct__graphene__point__t" ],
    [ "_graphene_quad_t", "struct__graphene__quad__t.html", "struct__graphene__quad__t" ],
    [ "_graphene_quaternion_t", "struct__graphene__quaternion__t.html", "struct__graphene__quaternion__t" ],
    [ "_graphene_ray_t", "struct__graphene__ray__t.html", "struct__graphene__ray__t" ],
    [ "_graphene_rect_t", "struct__graphene__rect__t.html", "struct__graphene__rect__t" ],
    [ "_graphene_size_t", "struct__graphene__size__t.html", "struct__graphene__size__t" ],
    [ "_graphene_sphere_t", "struct__graphene__sphere__t.html", "struct__graphene__sphere__t" ],
    [ "_graphene_triangle_t", "struct__graphene__triangle__t.html", "struct__graphene__triangle__t" ],
    [ "_graphene_vec2_t", "struct__graphene__vec2__t.html", "struct__graphene__vec2__t" ],
    [ "_graphene_vec3_t", "struct__graphene__vec3__t.html", "struct__graphene__vec3__t" ],
    [ "_graphene_vec4_t", "struct__graphene__vec4__t.html", "struct__graphene__vec4__t" ],
    [ "_hb_var_int_t", "union__hb__var__int__t.html", "union__hb__var__int__t" ],
    [ "_hb_var_num_t", "union__hb__var__num__t.html", "union__hb__var__num__t" ],
    [ "AppConfig", "structAppConfig.html", "structAppConfig" ],
    [ "cairo_font_extents_t", "structcairo__font__extents__t.html", "structcairo__font__extents__t" ],
    [ "cairo_glyph_t", "structcairo__glyph__t.html", "structcairo__glyph__t" ],
    [ "cairo_path", "structcairo__path.html", "structcairo__path" ],
    [ "cairo_text_cluster_t", "structcairo__text__cluster__t.html", "structcairo__text__cluster__t" ],
    [ "cairo_text_extents_t", "structcairo__text__extents__t.html", "structcairo__text__extents__t" ],
    [ "graphene_simd4f_t", "structgraphene__simd4f__t.html", "structgraphene__simd4f__t" ],
    [ "graphene_simd4x4f_t", "structgraphene__simd4x4f__t.html", "structgraphene__simd4x4f__t" ],
    [ "GUnixPipe", "structGUnixPipe.html", "structGUnixPipe" ],
    [ "hb_aat_layout_feature_selector_info_t", "structhb__aat__layout__feature__selector__info__t.html", "structhb__aat__layout__feature__selector__info__t" ],
    [ "hb_color_line_t", "structhb__color__line__t.html", "structhb__color__line__t" ],
    [ "hb_color_stop_t", "structhb__color__stop__t.html", "structhb__color__stop__t" ],
    [ "hb_draw_state_t", "structhb__draw__state__t.html", "structhb__draw__state__t" ],
    [ "hb_feature_t", "structhb__feature__t.html", "structhb__feature__t" ],
    [ "hb_font_extents_t", "structhb__font__extents__t.html", "structhb__font__extents__t" ],
    [ "hb_glyph_extents_t", "structhb__glyph__extents__t.html", "structhb__glyph__extents__t" ],
    [ "hb_glyph_info_t", "structhb__glyph__info__t.html", "structhb__glyph__info__t" ],
    [ "hb_glyph_position_t", "structhb__glyph__position__t.html", "structhb__glyph__position__t" ],
    [ "hb_ot_color_layer_t", "structhb__ot__color__layer__t.html", "structhb__ot__color__layer__t" ],
    [ "hb_ot_math_glyph_part_t", "structhb__ot__math__glyph__part__t.html", "structhb__ot__math__glyph__part__t" ],
    [ "hb_ot_math_glyph_variant_t", "structhb__ot__math__glyph__variant__t.html", "structhb__ot__math__glyph__variant__t" ],
    [ "hb_ot_math_kern_entry_t", "structhb__ot__math__kern__entry__t.html", "structhb__ot__math__kern__entry__t" ],
    [ "hb_ot_name_entry_t", "structhb__ot__name__entry__t.html", "structhb__ot__name__entry__t" ],
    [ "hb_ot_var_axis_info_t", "structhb__ot__var__axis__info__t.html", "structhb__ot__var__axis__info__t" ],
    [ "hb_ot_var_axis_t", "structhb__ot__var__axis__t.html", "structhb__ot__var__axis__t" ],
    [ "hb_segment_properties_t", "structhb__segment__properties__t.html", "structhb__segment__properties__t" ],
    [ "hb_user_data_key_t", "structhb__user__data__key__t.html", "structhb__user__data__key__t" ],
    [ "hb_variation_t", "structhb__variation__t.html", "structhb__variation__t" ],
    [ "User", "classUser.html", "classUser" ]
];