var hierarchy =
[
    [ "_cairo_matrix", "struct__cairo__matrix.html", null ],
    [ "_cairo_path_data_t", "union__cairo__path__data__t.html", null ],
    [ "_cairo_rectangle", "struct__cairo__rectangle.html", null ],
    [ "_cairo_rectangle_int", "struct__cairo__rectangle__int.html", null ],
    [ "_cairo_rectangle_list", "struct__cairo__rectangle__list.html", null ],
    [ "_cairo_script_interpreter_hooks", "struct__cairo__script__interpreter__hooks.html", null ],
    [ "_cairo_user_data_key", "struct__cairo__user__data__key.html", null ],
    [ "_graphene_box_t", "struct__graphene__box__t.html", null ],
    [ "_graphene_euler_t", "struct__graphene__euler__t.html", null ],
    [ "_graphene_frustum_t", "struct__graphene__frustum__t.html", null ],
    [ "_graphene_matrix_t", "struct__graphene__matrix__t.html", null ],
    [ "_graphene_plane_t", "struct__graphene__plane__t.html", null ],
    [ "_graphene_point3d_t", "struct__graphene__point3d__t.html", null ],
    [ "_graphene_point_t", "struct__graphene__point__t.html", null ],
    [ "_graphene_quad_t", "struct__graphene__quad__t.html", null ],
    [ "_graphene_quaternion_t", "struct__graphene__quaternion__t.html", null ],
    [ "_graphene_ray_t", "struct__graphene__ray__t.html", null ],
    [ "_graphene_rect_t", "struct__graphene__rect__t.html", null ],
    [ "_graphene_size_t", "struct__graphene__size__t.html", null ],
    [ "_graphene_sphere_t", "struct__graphene__sphere__t.html", null ],
    [ "_graphene_triangle_t", "struct__graphene__triangle__t.html", null ],
    [ "_graphene_vec2_t", "struct__graphene__vec2__t.html", null ],
    [ "_graphene_vec3_t", "struct__graphene__vec3__t.html", null ],
    [ "_graphene_vec4_t", "struct__graphene__vec4__t.html", null ],
    [ "_hb_var_int_t", "union__hb__var__int__t.html", null ],
    [ "_hb_var_num_t", "union__hb__var__num__t.html", null ],
    [ "AppConfig", "structAppConfig.html", null ],
    [ "doctest::Approx", "structdoctest_1_1Approx.html", null ],
    [ "doctest::AssertData", "structdoctest_1_1AssertData.html", [
      [ "doctest::detail::ResultBuilder", "structdoctest_1_1detail_1_1ResultBuilder.html", null ]
    ] ],
    [ "cairo_font_extents_t", "structcairo__font__extents__t.html", null ],
    [ "cairo_glyph_t", "structcairo__glyph__t.html", null ],
    [ "cairo_path", "structcairo__path.html", null ],
    [ "cairo_text_cluster_t", "structcairo__text__cluster__t.html", null ],
    [ "cairo_text_extents_t", "structcairo__text__extents__t.html", null ],
    [ "std::char_traits< charT >", "structstd_1_1char__traits.html", null ],
    [ "doctest::Contains", "classdoctest_1_1Contains.html", null ],
    [ "doctest::Context", "classdoctest_1_1Context.html", null ],
    [ "doctest::ContextOptions", "structdoctest_1_1ContextOptions.html", null ],
    [ "doctest::CurrentTestCaseStats", "structdoctest_1_1CurrentTestCaseStats.html", null ],
    [ "doctest::detail::types::enable_if< COND, T >", "structdoctest_1_1detail_1_1types_1_1enable__if.html", null ],
    [ "doctest::detail::types::enable_if< true, T >", "structdoctest_1_1detail_1_1types_1_1enable__if_3_01true_00_01T_01_4.html", null ],
    [ "doctest::detail::Expression_lhs< L >", "structdoctest_1_1detail_1_1Expression__lhs.html", null ],
    [ "doctest::detail::ExpressionDecomposer", "structdoctest_1_1detail_1_1ExpressionDecomposer.html", null ],
    [ "doctest::detail::types::false_type", "structdoctest_1_1detail_1_1types_1_1false__type.html", [
      [ "doctest::detail::deferred_false< T >", "structdoctest_1_1detail_1_1deferred__false.html", null ],
      [ "doctest::detail::has_insertion_operator< T, typename >", "structdoctest_1_1detail_1_1has__insertion__operator.html", null ],
      [ "doctest::detail::types::is_array< T >", "structdoctest_1_1detail_1_1types_1_1is__array.html", null ],
      [ "doctest::detail::types::is_pointer< T >", "structdoctest_1_1detail_1_1types_1_1is__pointer.html", null ],
      [ "doctest::detail::types::is_rvalue_reference< T >", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference.html", null ]
    ] ],
    [ "doctest::detail::filldata< T >", "structdoctest_1_1detail_1_1filldata.html", null ],
    [ "doctest::detail::filldata< const char[N]>", "structdoctest_1_1detail_1_1filldata_3_01const_01char_0fN_0e_4.html", null ],
    [ "doctest::detail::filldata< const void * >", "structdoctest_1_1detail_1_1filldata_3_01const_01void_01_5_01_4.html", null ],
    [ "doctest::detail::filldata< T * >", "structdoctest_1_1detail_1_1filldata_3_01T_01_5_01_4.html", null ],
    [ "doctest::detail::filldata< T[N]>", "structdoctest_1_1detail_1_1filldata_3_01T_0fN_0e_4.html", null ],
    [ "graphene_simd4f_t", "structgraphene__simd4f__t.html", null ],
    [ "graphene_simd4x4f_t", "structgraphene__simd4x4f__t.html", null ],
    [ "GUnixPipe", "structGUnixPipe.html", null ],
    [ "hb_aat_layout_feature_selector_info_t", "structhb__aat__layout__feature__selector__info__t.html", null ],
    [ "hb_color_line_t", "structhb__color__line__t.html", null ],
    [ "hb_color_stop_t", "structhb__color__stop__t.html", null ],
    [ "hb_draw_state_t", "structhb__draw__state__t.html", null ],
    [ "hb_feature_t", "structhb__feature__t.html", null ],
    [ "hb_font_extents_t", "structhb__font__extents__t.html", null ],
    [ "hb_glyph_extents_t", "structhb__glyph__extents__t.html", null ],
    [ "hb_glyph_info_t", "structhb__glyph__info__t.html", null ],
    [ "hb_glyph_position_t", "structhb__glyph__position__t.html", null ],
    [ "hb_ot_color_layer_t", "structhb__ot__color__layer__t.html", null ],
    [ "hb_ot_math_glyph_part_t", "structhb__ot__math__glyph__part__t.html", null ],
    [ "hb_ot_math_glyph_variant_t", "structhb__ot__math__glyph__variant__t.html", null ],
    [ "hb_ot_math_kern_entry_t", "structhb__ot__math__kern__entry__t.html", null ],
    [ "hb_ot_name_entry_t", "structhb__ot__name__entry__t.html", null ],
    [ "hb_ot_var_axis_info_t", "structhb__ot__var__axis__info__t.html", null ],
    [ "hb_ot_var_axis_t", "structhb__ot__var__axis__t.html", null ],
    [ "hb_segment_properties_t", "structhb__segment__properties__t.html", null ],
    [ "hb_user_data_key_t", "structhb__user__data__key__t.html", null ],
    [ "hb_variation_t", "structhb__variation__t.html", null ],
    [ "doctest::IContextScope", "structdoctest_1_1IContextScope.html", [
      [ "doctest::detail::ContextScopeBase", "structdoctest_1_1detail_1_1ContextScopeBase.html", [
        [ "doctest::detail::ContextScope< L >", "classdoctest_1_1detail_1_1ContextScope.html", null ]
      ] ]
    ] ],
    [ "doctest::detail::IExceptionTranslator", "structdoctest_1_1detail_1_1IExceptionTranslator.html", [
      [ "doctest::detail::ExceptionTranslator< T >", "classdoctest_1_1detail_1_1ExceptionTranslator.html", null ]
    ] ],
    [ "doctest::IReporter", "structdoctest_1_1IReporter.html", null ],
    [ "doctest::detail::types::is_enum< T >", "structdoctest_1_1detail_1_1types_1_1is__enum.html", null ],
    [ "doctest::IsNaN< F >", "structdoctest_1_1IsNaN.html", null ],
    [ "doctest::MessageData", "structdoctest_1_1MessageData.html", [
      [ "doctest::detail::MessageBuilder", "structdoctest_1_1detail_1_1MessageBuilder.html", null ]
    ] ],
    [ "doctest::QueryData", "structdoctest_1_1QueryData.html", null ],
    [ "doctest::detail::RelationalComparator< int, L, R >", "structdoctest_1_1detail_1_1RelationalComparator.html", null ],
    [ "doctest::detail::types::remove_const< T >", "structdoctest_1_1detail_1_1types_1_1remove__const.html", null ],
    [ "doctest::detail::types::remove_const< const T >", "structdoctest_1_1detail_1_1types_1_1remove__const_3_01const_01T_01_4.html", null ],
    [ "doctest::detail::types::remove_reference< T >", "structdoctest_1_1detail_1_1types_1_1remove__reference.html", null ],
    [ "doctest::detail::types::remove_reference< T & >", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01T_01_6_01_4.html", null ],
    [ "doctest::detail::types::remove_reference< T && >", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01T_01_6_6_01_4.html", null ],
    [ "doctest::detail::Result", "structdoctest_1_1detail_1_1Result.html", null ],
    [ "doctest::detail::should_stringify_as_underlying_type< T >", "structdoctest_1_1detail_1_1should__stringify__as__underlying__type.html", null ],
    [ "doctest::String", "classdoctest_1_1String.html", null ],
    [ "doctest::AssertData::StringContains", "classdoctest_1_1AssertData_1_1StringContains.html", null ],
    [ "doctest::detail::StringMakerBase< C >", "structdoctest_1_1detail_1_1StringMakerBase.html", null ],
    [ "doctest::detail::StringMakerBase< detail::has_insertion_operator< T >::value||detail::types::is_pointer< T >::value||detail::types::is_array< T >::value >", "structdoctest_1_1detail_1_1StringMakerBase.html", [
      [ "doctest::StringMaker< T >", "structdoctest_1_1StringMaker.html", null ]
    ] ],
    [ "doctest::detail::StringMakerBase< true >", "structdoctest_1_1detail_1_1StringMakerBase_3_01true_01_4.html", null ],
    [ "doctest::detail::Subcase", "structdoctest_1_1detail_1_1Subcase.html", null ],
    [ "doctest::SubcaseSignature", "structdoctest_1_1SubcaseSignature.html", null ],
    [ "doctest::TestCaseData", "structdoctest_1_1TestCaseData.html", [
      [ "doctest::detail::TestCase", "structdoctest_1_1detail_1_1TestCase.html", null ]
    ] ],
    [ "doctest::TestCaseException", "structdoctest_1_1TestCaseException.html", null ],
    [ "doctest::detail::TestFailureException", "structdoctest_1_1detail_1_1TestFailureException.html", null ],
    [ "doctest::TestRunStats", "structdoctest_1_1TestRunStats.html", null ],
    [ "doctest::detail::TestSuite", "structdoctest_1_1detail_1_1TestSuite.html", null ],
    [ "doctest::detail::types::true_type", "structdoctest_1_1detail_1_1types_1_1true__type.html", [
      [ "doctest::detail::has_insertion_operator< T, decltype(operator<<(declval< std::ostream & >(), declval< const T & >()), void())>", "structdoctest_1_1detail_1_1has__insertion__operator_3_01T_00_01decltype_07operator_3_3_07declvald5a5a279653bbfeef238ad5c984744e2.html", null ],
      [ "doctest::detail::types::is_array< T[SIZE]>", "structdoctest_1_1detail_1_1types_1_1is__array_3_01T_0fSIZE_0e_4.html", null ],
      [ "doctest::detail::types::is_pointer< T * >", "structdoctest_1_1detail_1_1types_1_1is__pointer_3_01T_01_5_01_4.html", null ],
      [ "doctest::detail::types::is_rvalue_reference< T && >", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference_3_01T_01_6_6_01_4.html", null ]
    ] ],
    [ "std::tuple< Types >", "classstd_1_1tuple.html", null ],
    [ "doctest::detail::types::underlying_type< T >", "structdoctest_1_1detail_1_1types_1_1underlying__type.html", null ],
    [ "User", "classUser.html", null ],
    [ "doctest::String::view", "structdoctest_1_1String_1_1view.html", null ]
];