[package]
name = "rust_sound_recorder"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "voice"
path = "src/main.rs"

[[bin]]
name = "record"
path = "src/record.rs"

[[bin]]
name = "record-video"
path = "src/record-video.rs"

[dependencies]
anyhow = "1.0.98"
cpal = "0.16"
hound = "3.5"
tokio = { version = "1", features = ["full"] }
v4l = "0.14"
bytemuck = "1.13" # NOTE: for streaming, check latest version
