name: Deploy Doxygen Docs
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enter devShell and generate docs
        run: |
          cd c
          nix develop --command bash -c '
            git submodule update --recursive
            cd ..
            cd doxygen-awesome-css
            git checkout v2.3.4
            cd ../c
            meson setup build
            make doc
          '

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./c/docs/html
          destination_dir: c
